### ISSUE TITLE
[Bug] Open Fennec causes reboot on Nexus 4 (LineageOS Android 8.1 device)

### ISSUE THREAD

**Issue by ovz93br43v7** [mozilla-mobile/fenix#16594] opened 2020-11-16 12:38 UTC
### Steps to reproduce
Install Fennec from F-Droid store on a Nexus 4 with LineageOS Android 8.1.
Start Fennec
Device crashes and makes a reboot.

I already cleared Fennec Cache and User data to prevent any trouble caused by old data, because the problem exist since update to version 82. Version 81 worked for this old device.

### Expected behavior
Start Fennec and use the browser as usual.

### Actual behavior
Start Fennec and device crashes and makes a reboot

### Device information
* Android device: Google Nexus 4 - 16 GB
* Android version: Android 8.1 (LineageOS 15.1, last available update from 02.01.2019)
* Fenix version: 82.1.3

**Comment by kbrosnan** [comment] 2020-11-17 00:37
This is an OS bug that Firefox and other applications can trigger. There is no fix on Firefox's side. If possible try to find a newer ROM for your device. Duplicate of #5663

**Closed by kbrosnan** 2020-11-17 00:37 UTC
Labels: needs:triage, 🐞 bug
