### ISSUE TITLE
[Bug]: Unable to load Twitter in Fenix Nightly only in Private Browsing mode

### ISSUE THREAD

**Issue by Fanolian** [mozilla-mobile/fenix#27719] opened 2022-11-05 06:56 UTC
### Steps to reproduce

1. Open Private Browsing mode in Fenix.
2. Go to any Twitter page, e.g. https://www.twitter.com/firefox/.
3. Click cancel when the prompt of opening link in app appears.

### Expected behaviour

The page should be loaded in Fenix successfully.

### Actual behaviour

A prompt about opening the link in app appears. Clicking cancel does not load the link in Fenix. It shows a blank page instead.
In non-PB mode, I can load the link properly.

Video of the issue: 

https://user-images.githubusercontent.com/771216/200107100-de4de21d-ef08-4318-a46f-4d42c1f58b0b.mp4

(Or original quality 66MB: https://giant.gfycat.com/GargantuanPossibleAsiandamselfly.mp4)

### Device name

Google Pixel 4a

### Android version

Android 13 October 2022 update

### Firefox release type

Firefox Nightly

### Firefox version

108.0a1 (Build #2015913675), 408d15af9+ AC: 108.0.20221103143443, 5cc49c0037 GV: 108.0a1-20221103095349 AS: 94.3.2  2022-11-03T17:07:17.965436

### Additional information

I cannot reproduce the issue in non-PB mode. (Shown in the last part of the attached video)
I cannot reproduce it in PB mode of Fenix Release 106.1.0 (Build #2015909131), 71ca6c1f7+ AC: 106.0.5, 5f06485fc3 GV: 106.0-20221010181815 AS: 94.2.1 2022-10-11T01:08:43.974343

It is reproducible either `Open links in apps` in Settings is enabled or not.
It is reproducible with all addons disabled.
I have tried turning Enhanced Tracking Protection off and deleting browsing data, except `history and site data`.

I do not have Twitter app installed. I tried installing it (But without logging on) but the issue persists.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21934)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21934

**Comment by kbrosnan** [comment] 2022-11-06 00:47
Duplicate bz-1799208

**Comment by AdinaPetridean** [comment] 2022-11-07 12:53
@Fanolian  thank you for your report! I was able to reproduce this issue on  Firefox Nightly 108.0a1- 7/11 with One plus 9 Pro (Android 12).  However I only reproduced it after reloading the twitter page (not on the first try).

**Comment by Fanolian** [comment] 2022-11-07 13:11
I tried Wikipedia and YouTube which trigger open-in-app prompts. They work but the addresses given in the prompt are `https://`, not `intent://` like Twitter. I don't know any other sites that also open an `intent://` address.

**Comment by shtstorm** [comment] 2022-11-08 20:47
The problem is with **any** Twitter link and any embedded Twitter post on any page. If you start with a page in Private Browsing mode and click on a Twitter link, the there will be one or more "intent" pop ups and the page would fail to load.

For instance, open this page in PB mode and click on this link: [Firefox 🔥 (@firefox) / Twitter](https://mobile.twitter.com/firefox)

This is probably a higher priority issue because Twitter is broken as of now in permanent PB mode.

**Comment by yoasif** [comment] 2022-11-21 17:49
This issue is now present in beta - [we are seeing reports elsewhere](https://www.reddit.com/r/firefox/comments/z14hvv/websites_on_firefox_beta_android_redirecting_to/).

**Comment by rocketsroger** [comment] 2022-11-21 19:28
More investigation is needed, but [this](https://github.com/mozilla-mobile/android-components/pull/12897) could be related.

**Comment by plwt** [comment] 2022-11-22 06:22
User feedback: https://support.mozilla.org/en-US/questions/1397340

**Comment by plwt** [comment] 2022-11-22 20:09
User feedback: https://support.mozilla.org/en-US/questions/1397560

**Comment by Fanolian** [comment] 2022-11-23 06:02
It doesn't work in non-PB mode now. Loading a twitter page will open Google Play Store.

**Comment by t-p-white** [comment] 2022-11-23 11:22
> @Fanolian thank you for your report! I was able to reproduce this issue on Firefox Nightly 108.0a1- 7/11 with One plus 9 Pro (Android 12). However I only reproduced it after reloading the twitter page (not on the first try).

Can confirm this is also the case while testing on Pixel 7

**Comment by boek** [comment] 2022-11-25 21:45
@rocketsroger @t-p-white - @zmckenney and I fell into investigating this on Friday and we found out that this may be caused by cookie banner handling set to `Enabled (Accept or accept all)`. It appears that whatever heuristics we use to detect cookie banners thinks that the `Open in App` banner is one. Accepting it redirects to `https://twitter.app.link` which then takes you to the play store.

**Comment by rocketsroger** [comment] 2022-11-28 19:19
> @rocketsroger @t-p-white - @zmckenney and I fell into investigating this on Friday and we found out that this may be caused by cookie banner handling set to `Enabled (Accept or accept all)`. It appears that whatever heuristics we use to detect cookie banners thinks that the `Open in App` banner is one. Accepting it redirects to `https://twitter.app.link` which then takes you to the play store.

Thanks Jeff, this is a good observation.

**Comment by rocketsroger** [comment] 2022-11-28 19:21
I can confirm that I can reproduce with a older Nightly but not with latest Nightly build.  @Fanolian, @yoasif and @shtstorm, can you please help me confirm this finding?  Thanks

**Comment by rocketsroger** [comment] 2022-11-28 19:22
Adding QA to confirm that with latest Nightly this is not reproducible.  Thanks

**Comment by rocketsroger** [comment] 2022-11-28 19:24
This said, I'm still trying to figure out what's causing the problem in Beta.

**Comment by rocketsroger** [comment] 2022-11-28 21:50
Confirmed @boek's and @zmckenney's investigation.  This issue is related to Cookie Banner Protection.  Thanks

**Comment by Fanolian** [comment] 2022-11-29 04:31
Confirm that this can't be reproduced in latest Nightly, PB or non-PB mode.

**Comment by rocketsroger** [comment] 2022-11-29 13:49
[Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1803117) created.

**Comment by AdinaPetridean** [comment] 2022-11-29 13:49
Verified  as fixed on the latest Nightly 109.0a1 from 29/11 with Motorola Moto G9 plus (Android 11). This issue is no longer reproducible in normal or private browsing.



https://user-images.githubusercontent.com/108326843/204545892-41a9554d-8e68-4c4c-acae-5053af423565.mp4

**Closed** 2022-11-29 16:54 UTC
Labels: 🐞 bug, eng:qa:needed, S3, needs:triage, qa-triaged
