### ISSUE TITLE
[Bug] (regression) wrong action bar or status bar color

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#7604] opened 2020-01-10 19:46 UTC
Please have a look at the screenshot, more precisely the difference between the action bar and the Android status bar. Both should have the same color.

left: Last good build, right: first bald build.

![regression](https://user-images.githubusercontent.com/1100614/72181454-acef9380-33e9-11ea-8def-1173d4d498e9.png)

It's a regression from #7480 (cc @mcarare because you wrote the PR).

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision 0a412a1a6ae218e3ea0e9f67604c37c5355eb61c

**Comment by cadeyrn** [comment] 2020-01-28 22:34
@AmyYLee Could you review this one? This regression exists in Firefox Preview since almost three weeks and was introduced with the attempt to fix #7313 which was opened by you. #7313 was only about the dark theme but the change also affected the light theme and even the dark theme doesn't look like in your mockup, it has the same bug: the action and the status bar both have a different color.

**Comment by brampitoyo** [comment] 2020-02-05 02:41
Hi @cadeyrn, I can resolve this problem, and @AmyYLee can make sure that it’s correct.

In fact, the light theme _does not_ follow dark and private theme in its use of **action bar colour**.

### Light

![Settings-Light@2x](https://user-images.githubusercontent.com/51007/73806199-ad831a80-482d-11ea-9b8c-9f67c64654fc.png)

### Dark

![Settings-Dark@2x](https://user-images.githubusercontent.com/51007/73805943-f8506280-482c-11ea-80d8-8947e6d1445a.png)

### Private

![Settings-Private@2x](https://user-images.githubusercontent.com/51007/73806097-672dbb80-482d-11ea-8c69-7ccf81055d73.png)

But one thing for sure: the colour of the action bar should _always match_ the colour of the status bar.

**Comment by brampitoyo** [comment] 2020-02-06 01:49
Hi @cadeyrn, @AmyYLee and I just talked, and here were the result of our conversation.

We checked our Fenix design spec and compared it to the colours of action+status bars and page background in some of the most popular Android apps:

#### Settings
<img width="160" src="https://user-images.githubusercontent.com/51007/73888030-baf1e080-48d1-11ea-9c42-93fd1a228c64.png">

#### YouTube
<img width="160" src="https://user-images.githubusercontent.com/51007/73887901-6e0e0a00-48d1-11ea-9aea-45d060617ea8.png">

#### Google Chrome
<img width="160" src="https://user-images.githubusercontent.com/51007/73887945-90078c80-48d1-11ea-9b0e-4d9af9932bfb.png">

#### Gmail
<img width="160" src="https://user-images.githubusercontent.com/51007/73887975-9eee3f00-48d1-11ea-840a-e5e1716b2986.png">

#### Google Play Store
<img width="160" src="https://user-images.githubusercontent.com/51007/73888013-b2010f00-48d1-11ea-9a33-b6b51b8fd810.png">

#### Google Maps
<img width="160" src="https://user-images.githubusercontent.com/51007/73888063-ce04b080-48d1-11ea-8bb2-29288070b7d0.png">

#### Facebook
<img width="160" src="https://user-images.githubusercontent.com/51007/73888100-dd83f980-48d1-11ea-9913-60aac587a467.png">

#### Facebook Messenger
<img width="160" src="https://user-images.githubusercontent.com/51007/73888121-e70d6180-48d1-11ea-813d-cac512520374.png">

The thing they share in common: the colours of action+status bars and page background are **all identical**.

So we think that we will need to change all action bar colours, so that they match page background. Yes, even on dark and private themes.

![Settings-Dark@2x](https://user-images.githubusercontent.com/51007/73898885-ade3ea00-48ef-11ea-95fa-9ace32617f88.png)

![Settings-Private@2x](https://user-images.githubusercontent.com/51007/73898893-b89e7f00-48ef-11ea-8b09-1c6f16706e16.png)


I’ll let @AmyYLee verify and approve.

**Comment by AmyYLee** [comment] 2020-02-06 08:57
> Hi @cadeyrn, @AmyYLee and I just talked, and here were the result of our conversation.
> 
> We checked our Fenix design spec and compared it to the colours of action+status bars and page background in some of the most popular Android apps:
> #### Settings
> 
> <img alt="" width="160" src="https://user-images.githubusercontent.com/51007/73888030-baf1e080-48d1-11ea-9c42-93fd1a228c64.png">
> #### YouTube
> 
> <img alt="" width="160" src="https://user-images.githubusercontent.com/51007/73887901-6e0e0a00-48d1-11ea-9aea-45d060617ea8.png">
> #### Google Chrome
> 
> <img alt="" width="160" src="https://user-images.githubusercontent.com/51007/73887945-90078c80-48d1-11ea-9b0e-4d9af9932bfb.png">
> #### Gmail
> 
> <img alt="" width="160" src="https://user-images.githubusercontent.com/51007/73887975-9eee3f00-48d1-11ea-840a-e5e1716b2986.png">
> #### Google Play Store
> 
> <img alt="" width="160" src="https://user-images.githubusercontent.com/51007/73888013-b2010f00-48d1-11ea-9a33-b6b51b8fd810.png">
> #### Google Maps
> 
> <img alt="" width="160" src="https://user-images.githubusercontent.com/51007/73888063-ce04b080-48d1-11ea-8bb2-29288070b7d0.png">
> #### Facebook
> 
> <img alt="" width="160" src="https://user-images.githubusercontent.com/51007/73888100-dd83f980-48d1-11ea-9913-60aac587a467.png">
> #### Facebook Messenger
> 
> <img alt="" width="160" src="https://user-images.githubusercontent.com/51007/73888121-e70d6180-48d1-11ea-813d-cac512520374.png">
> 
> The thing they share in common: the colours of action+status bars and page background are **all identical**.
> 
> So we think that we will need to change all action bar colours, so that they match page background. Yes, even on dark and private themes.
> 
> ![Settings-Dark@2x](https://user-images.githubusercontent.com/51007/73898885-ade3ea00-48ef-11ea-95fa-9ace32617f88.png)
> 
> ![Settings-Private@2x](https://user-images.githubusercontent.com/51007/73898893-b89e7f00-48ef-11ea-8b09-1c6f16706e16.png)
> 
> I’ll let @AmyYLee verify and approve.

@brampitoyo @cadeyrn I agree headers and background should be the same colour. Let's ensure that we still keep the drop shadow under the header and we're good. Thanks!

**Comment by cadeyrn** [comment] 2020-02-10 20:33
@mcarare Now that we have the UX feedback can you fix the regression or at least find someone else, please? It would be great not to have this regression in one more stable release because it looks… not very beautiful. Thank you! 🤗

**Comment by mcarare** [comment] 2020-02-11 10:09
@cadeyrn , @brampitoyo I think this is a matter of choice. Actually, in all material design mocks the status bar colour is darker that the action bar. There are popular apps like WhatsApp and Instagram that have the same contrast between the action bar containing the "page title" and the page background. 
Nevertheless, if this is the final UX decision, I will include this in the polish sprints. TY!

**Comment by cadeyrn** [comment] 2020-02-11 10:38
> There are popular apps like WhatsApp and Instagram that have the same contrast between the action bar containing the "page title" and the page background.

That's true that some popular apps show a different color. But most apps on my device have the same color for action bar and status bar, including all system apps, Google Chrome, Google Mail, Google Photos, Facebook, WordPress, …

> in all material design mocks the status bar colour is darker that the action bar.

I don't know the material design mocks but not even Googles use different colors in their apps.

**Comment by cadeyrn** [comment] 2020-02-19 20:16
The regression is still present in Fenix 4.0 Beta 1.

**Comment by cadeyrn** [comment] 2020-02-25 22:39
@darkwing Thank you so much for fixing this. 😊

May I nominate this issue for uplift for Fenix 4.0? It's not a big issue at all, but…

1. It affects a large population.
2. It's a regression and was already shipped for several weeks
3. It's very low risk. It's not only a one-line change, the change reverts 1:1 the old code which was implemented for many months and is well-tested.

**Comment by darkwing** [comment] 2020-02-25 23:21
Delegating that decision to @boek !

**Comment by AndiAJ** [comment] 2020-02-26 08:27
Hi, I've just checked this matter on the latest **`Nightly Build #20570604 from 02/26`** using the following devices:
✔️ Google Pixel 3a (Android 9)
✔️ Huawei Mate 20 Lite (Android 8.1.0)
❌ Samsung Galaxy S7 (Android 7)
❌ OnePlus A3 (Android 6.0.1)
❌ LG Nexus 4 (Android 5.1.1)

► Slightly different colour between the Android taskbar & Fenix action bar while in Private Mode on the Samsung Galaxy S7 & OnePlus A3

• Samsung S7
![rsz_screenshot_20200226-101524](https://user-images.githubusercontent.com/51314259/75325740-ff91eb80-5881-11ea-9130-8ec61317b270.png)

• OnePlus A3 
![rsz_screenshot_20200226-100935](https://user-images.githubusercontent.com/51314259/75325288-3ddadb00-5881-11ea-9832-9fe07494dd51.png)


► On the LG Nexus 4 the Android taskbar remains black while using the Light theme. (No issues encountered while using the Dark theme and Private Mode)

![rsz_screenshot_2020-02-26-10-13-47](https://user-images.githubusercontent.com/51314259/75325615-c9546c00-5881-11ea-8e7b-09febf6204ae.png)

@darkwing & @brampitoyo  - Please review and share your thoughts. ☺️ 
I'll remove the QA needed until further notice.

**Comment by brampitoyo** [comment] 2020-03-02 23:09
@AndiAJ The slight colour difference – similar but not quite the same – is odd. But note how the statusbar colour is identical between Samsung A7 and OnePlus A3. They’re both `#22194b`.

In our specs, the background colour of Private Theme was set to `Ink 90` `#1d1133`, as shown below:

<img width="360" src="https://user-images.githubusercontent.com/51007/75726354-0ff50b00-5d47-11ea-9f9a-b7f487f7f4bb.png">

In the case of LG Nexus 4, the statusbar is coloured `#000000`. Seeing this value led me to believe that it’s hardcoded – nothing we can do will change it.

**Comment by sv-sdeiac** [comment] 2020-03-19 13:00
Hi, I can confirm that the main issue is fixed using Firefox Preview Nightly 3/19 #20790605.
Devices:
- Google Pixel 3 (Android Q);
- LG g7 fit (Android 8.1).

 I'll close this ticket since the developer confirmed that the issue is fixed from their part, thanks.

**Closed by sv-sdeiac** 2020-03-19 13:00 UTC
Labels: Feature:DarkMode, 🐞 bug
