### ISSUE TITLE
[Bug]: webauthn.io reports that the browser does not support webauthn

### ISSUE THREAD

**Issue by WhyNotHugo** [mozilla-mobile/fenix#25027] opened 2022-04-29 11:19 UTC
### Steps to reproduce

1. Visit [webauthn.io](https://webauthn.io/)

### Expected behaviour

Should be able to test a Yubikey.

### Actual behaviour

Website reports that the browser does not support webauthn.

![Screenshot of webauthn.io with a message that reads "Oh no! This browser doesn't currently support WebAuthn."](https://user-images.githubusercontent.com/730811/165934604-efd5909b-3e5d-49d3-8906-cebb0463dddf.png)

### Android version

LineageOS 18

### Firefox release type

Firefox

### Firefox version

98.2.0

### Additional information

I'm looking at  #18347 and #17688, which seem to indicate that it does work on _some_ versions, but these issues are pretty old. Maybe there's been a big regression?

**Comment by WhyNotHugo** [comment] 2022-05-01 15:49
Nightly 101.0a1 does not work:

- When clicking "Register", nothing happens.
- When clicking "Login", the website immediately reports "the operation was aborted".

**Comment by WhyNotHugo** [comment] 2022-05-01 17:46
Can I generate a debug log on mobile somehow?

**Comment by jonalmeida** [comment] 2022-05-02 21:57
@WhyNotHugo it looks like you're using LineageOS which doesn't have the FidoApi needed (provided by Google Services). The fallback solution is to perform attestation with the websites `.well-known/assetlinks.json` which the webauthn.io example site does not use. (See also: https://developers.google.com/digital-asset-links/v1/getting-started)

So unfortunately, this is a "won't fix" bug right now until there are open-source equivalent versions we can rely on.

cc: @SoftVision-LorandJanos for reference too, so you're also aware that devices which do not have Google Play Services cannot use this feature consistently.

**Comment by WhyNotHugo** [comment] 2022-05-02 22:35
So webauthn/fido on Firefox relies on Google's privileged spyware kit being installed locally? That's very disappointing.

Pardon my ignorance, but why isn't the implementation used on desktop re-usable on Android?

> until there are open-source equivalent versions we can rely on.

Do you know of anyone with the expertise and interest in developing this? Logging into website on Android would be super useful!

**Comment by amedyne** [comment] 2022-05-04 02:33
This is a duplicate of: https://bugzilla.mozilla.org/show_bug.cgi?id=1678045
Please refer to this bug for further discussions. Thanks!

**Closed by amedyne** 2022-05-04 02:33 UTC
Labels: 🐞 bug, S3, needs:triage, qa-triaged, Feature:WebAuthn
