### ISSUE TITLE
[Bug] Intermittent completely white tab or visually wrong tab page content after closing a tab

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#12593] opened 2020-07-15 14:22 UTC
## Steps to reproduce
1. Open two websites in two tabs
1. Switch to the first tab in the tabs tray
1. _Quickly_ switch to the second tab _and_ swipe to remove the tab

### Expected behavior
The first tab is displayed.

### Actual behavior
Very often, but not every single time, the first tab is rendered completely white but still accepts input like highlighting text or scrolling. May be related to #12477, #12492, but different STR. Switching to another app and back to Fenix resolves the issue.

![video1](https://user-images.githubusercontent.com/42788925/87556279-c0d8c280-c6b6-11ea-96ed-79a6d5f0c365.gif)

### Device information
* Android device: 6.0.1, Sony Xperia Z2
* Fenix version:
Nightly 200714 06:01 (Build #21960613)
AC: 50.0.20200712190143, 22f032ca7
GV: 80.0a1-20200711092223
AS: 61.0.7

**Comment by ekager** [comment] 2020-07-16 19:54
Was able to repro and got an even "worse" situation. Instead of a white background I actually saw the deleted tab as the "background" but clicking around clicked nonvisible links. 
![Screenshot_20200716-152234](https://user-images.githubusercontent.com/25442310/87716226-8afe1180-c77c-11ea-9c83-654a53d6bff9.png)

**Comment by ekager** [comment] 2020-07-16 21:07
cc @pocmo this is also related to `SessionFeature` :/ I can't repro on `8533d96ee24a89dc3956bfa18ac73d476b88b767` the commit but can repro on the next AC update https://github.com/mozilla-mobile/fenix/commit/f863c341e81e1b4b894a6d89931cd44e773f0338

**Comment by pocmo** [comment] 2020-07-17 08:07
Moving this into our sprint and investigating...

**Comment by pocmo** [comment] 2020-07-20 12:05
A workaround patch for this just landed in AC. It will get into the next AC Nightly and then eventually into the next Fenix Nightly.

**Comment by madb1lly** [comment] 2020-07-22 15:36
Hi all,

Is this the same issue i reported two weeks ago?   #12382

I actually found slightly different actions removed the "ghost" tab so maybe not. 

Cheers 🙂

**Comment by ekager** [comment] 2020-07-22 15:49
Yeah @madb1lly that looks like the same issue. Could you check if you still see this in the latest Nightly?

**Comment by madb1lly** [comment] 2020-07-23 05:58
Hi @ekager,
Yes I had this happen yesterday before I updated about 16:00 CET. I've not had the problem since but I've not used it much either.
Cheers 🙂

**Comment by opusforlife2** [comment] 2020-07-23 15:06
STR still isn't clear to me, but this has happened to me even when I simply close a child tab and Fenix automatically switches to the parent tab. Tapping on the address bar and then back, or tapping on Home and then back, both fix the issue.

**Comment by hwinnemoe** [comment] 2020-07-24 14:25
I can still reproduce on a build that should have [this patch](https://github.com/mozilla-mobile/android-components/pull/7759/commits/ede8e25dc8b31981758350f42978440e259d6aa2):
Nightly 200724 06:05 (Build #22060612)
AC: 52.0.20200723130248, 69562438f
GV: 80.0a1-20200722094100
AS: 61.0.10

**Comment by sheepycoder** [comment] 2020-07-25 08:19
> Instead of a white background I actually saw the deleted tab as the "background" but clicking around clicked nonvisible links.

I still see this issue in the latest nightly though it is a bit rare now.

**Comment by miDeb** [comment] 2020-07-27 13:58
I can always reproduce by closing the tab by long pressing the tab counter. Switching to a different tab and back fixes it. Not sure if this is the same issue... If there's anything I can do to investigate this, please let me know :)

**Comment by ekager** [comment] 2020-07-27 14:22
@miDeb which version are you on? The latest nightly?

**Comment by miDeb** [comment] 2020-07-27 14:23
Yes! Sorry, should have specified that.

**Comment by Diana-Rus** [comment] 2020-07-27 15:46
Hi, issue is reproducible on today's build, Nightly 7/27 with Samsung Galaxy S9 (Android 8).
Before doing this steps you need to make a clear data and afterwards the STR need to be done as fast as they can be.

With Google Pixel 3XL (Android 9) didn't encounter this issue.

**Comment by pocmo** [comment] 2020-07-27 17:00
Thank you. I will take another look. 🕵️

**Comment by opusforlife2** [comment] 2020-07-30 16:19
> child tab and Fenix automatically switches to the parent tab

Apparently it doesn't even need to be a child tab. It could be _any_ two tabs.

**Comment by liuche** [comment] 2020-08-05 23:10
Talked to sebastian and has a dependency on another AC bug, but is next in line.

**Comment by pocmo** [comment] 2020-08-14 16:39
We are confident that this is going to get fixed by the following AC issue and linked PR. We are planning to land it mid/end next week:
https://github.com/mozilla-mobile/android-components/issues/7867

**Comment by madb1lly** [comment] 2020-08-21 06:29
Hi all,

I'm now experiencing the white tab version of this bug; previously I only experienced the old tab version (as I reported #12382). 

The actions to remove the old/ghost tab work every time but they won't work every time for the white tab. I have found no repeatable method of producing nor overcoming the white tab version of this bug. 

Therefore I wonder if there are actually two or more different issues which have the same or similar symptoms? I see that some other bug reports of white tab in the past few days have been closed in favour of this one yet I feel that it might be worth being a bit more open minded before assuming they are the same issues.

Cheers 🙂

**Comment by Diana-Rus** [comment] 2020-08-25 13:54
Hi, Verified as fixed on Fenix RC 80.1.0 with Samsung Galaxy S9 (Android 8)

**Comment by mobd** [comment] 2020-08-25 14:14
Is this in nightly yet? I can still reproduce on the latest build.

![ezgif-6-e993078c272d](https://user-images.githubusercontent.com/66154603/91185128-b8c86580-e6ed-11ea-9470-6c6f25068210.gif)

**Comment by Diana-Rus** [comment] 2020-08-25 14:47
Hello @mobd and @madb1lly  this was only treated for Firefox Preview 80.1.0, for the moment 😊.

**Comment by liuche** [comment] 2020-08-25 17:24
We backed the refactor out of Beta so it wouldn't regress release users, but are still debugging the fix in https://github.com/mozilla-mobile/android-components/issues/7867 on Nightly.

**Comment by abodea** [comment] 2020-09-22 09:26
Verified as fixed on the latest **Nightly** build **9/22** with **Google Pixel 4 XL (Android 11)**
Note that it works as expected in normal and private browsing.

![20200922-121324](https://user-images.githubusercontent.com/42831109/93864770-0aa0e300-fcce-11ea-9db5-a30d422672eb.gif)

**Closed by abodea** 2020-09-22 09:26 UTC
Labels: Feature:Browsing, Feature:Tabs, eng:qa:needed, needs:ac, 🐞 bug
