### ISSUE TITLE
Temporary Fix for bug#16422

### ISSUE THREAD

**Issue by Doctor-Abhi** [mozilla-mobile/fenix#16768] opened 2020-11-29 05:03 UTC
There has been a bug related to dark mode in the popup history tab, reported around 21 days ago. Here is a temporary fix if u r using a miui 12 device.

1.Just install Firefox nightly 201128 17:02 or Firefox 84.0.0-beta2
2. Go to settings->display->Dark mode->Individual apps->Firefox nightly/Firefox beta, toggle the switch for it.
3. We have now fixed the bug #16422 

Device:- Redmi K20 pro
OS:- xiaomi.eu MIUI 12.0.5.0, based on Android 10
Fenix version:- nightly 201128 17:02 and 84.0.0-beta2

![Screenshot_2020-11-29-10-23-18-037_org mozilla fenix](https://user-images.githubusercontent.com/75193430/100533776-0b09ad00-322e-11eb-9069-d3ca9436e0b0.jpg)
![Screenshot_2020-11-29-10-23-30-263_com android settings](https://user-images.githubusercontent.com/75193430/100533778-0f35ca80-322e-11eb-9cc7-20a9d28f8e35.jpg)
![Screenshot_2020-11-29-10-23-36-442_com android settings](https://user-images.githubusercontent.com/75193430/100533779-10ff8e00-322e-11eb-9dfb-0033a8d569cb.jpg)
![Screenshot_2020-11-29-10-23-40-735_com android settings](https://user-images.githubusercontent.com/75193430/100533780-1230bb00-322e-11eb-9ebc-7137591ded45.jpg)
![Screenshot_2020-11-29-10-23-48-267_com android settings](https://user-images.githubusercontent.com/75193430/100533782-14931500-322e-11eb-80f2-168f5ba39511.jpg)
![Screenshot_2020-11-29-10-23-56-184_com android settings](https://user-images.githubusercontent.com/75193430/100533784-15c44200-322e-11eb-98c1-a00ff071ffa9.jpg)
![Screenshot_2020-11-29-10-24-05-088_org mozilla firefox_beta](https://user-images.githubusercontent.com/75193430/100533786-178e0580-322e-11eb-81b5-a4025ffc5500.jpg)
![Screenshot_2020-11-29-10-24-23-225_com miui home](https://user-images.githubusercontent.com/75193430/100533787-1a88f600-322e-11eb-98bd-6fb9da50fbad.jpg)

**Comment by kbrosnan** [comment] 2020-12-02 19:42
Duplicate of #16422

**Closed by kbrosnan** 2020-12-02 19:42 UTC
Labels: needs:triage
