### ISSUE TITLE
Convert Private Tab to "normal"

### ISSUE THREAD

**Issue by glawrence** [mozilla-mobile/fenix#5965] opened 2019-10-11 18:50 UTC
### Why/User Benefit/User Problem
With the new Firefox Preview 2.1.0 I can enable "Launch links in private tab" (which is a great feature, thank you!), however there is no easy way to convert this to a "normal" tab.

### What/Requirements
There are times when I would like to be able to convert the tab to a "normal" one to pick up any state/login information from my regular browsing session. When "Launch links in private tab" is enabled, which I think is a sensible default then it is hard to copy and paste the url, it would be much easier if Firefox Preview provided an easy UI option for doing this.

### Acceptance Criteria (how do I know when I’m done?)
Open a link from another app, say an e-mail client
This link opens in a private tab in Firefox Preview
Without copy and pasting the url, provide an easy to use menu option or action to covert the private tab
I expect this would not be a "tab conversion" per se as the link would need to be opened again, it would be more "copy url, close private tab, open new normal tab, go to url" but in one simple action

**Comment by klint** [comment] 2019-10-14 08:55
I had opened a similar request: #5170

**Comment by NotWoods** [comment] 2019-12-23 08:01
Duplicate of #5170, which describes both ways.

**Closed by NotWoods** 2019-12-23 08:01 UTC
Labels: Feature:PrivateMode, 🌟 feature request
