### ISSUE TITLE
[Bug][L10n] Languages listed in Poonton are more than the languages listed in Fenix

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#19212] opened 2021-04-23 13:02 UTC
## Steps to reproduce
1. Go to https://pontoon.mozilla.org/teams/ and count the number of languages that are above 0% progress;
2. Launch Fenix and go to Settings - Language and count the number of listed languages;
### Expected behavior
Languages listed in Poonton, above 0% progress, are the same as the languages listed in Fenix.
### Actual behavior
Languages listed in Poonton, above 0% progress, are more than the languages listed in Fenix.
There are 182 languages above 0% in Poonton and 91 languages in Fenix.
### Device information

* Device vendor / model and Android version: Pixel 2 (Android 9)
* Firefox for Android version: Nightly 4/23 and Beta 89.0.0-beta.1

**Comment by Dunexus** [comment] 2021-04-23 13:49
Sorting languages on poonton by progress, it looks like only languages with 60% or more are in Fenix.

This may be by design as languages with too much translations missing may result in poor experience for end users.

**Comment by Delphine** [comment] 2021-06-09 00:02
Yes, that is correct. We usually accepts locales once they reach 70% completion.
Closing for now, please re-open if there is still an issue with this going forwards

**Closed by Delphine** 2021-06-09 00:02 UTC
Labels: Feature:Settings, S3, needs:triage, 🌐 L10N, 🐞 bug
