### ISSUE TITLE
FNX-3499 ⁃ [Bug] mailto url don't work

### ISSUE THREAD

**Issue by Dimas-sc** [mozilla-mobile/fenix#10391] opened 2020-05-04 07:45 UTC
Similar to closed issue #6231

## Steps to reproduce
Click on a mailto url, e.g. the "contacte" link at the top left of [this page](http://www.cfagirona.cat/).
![imatge](https://user-images.githubusercontent.com/2415679/80944918-e873fa80-8dea-11ea-8658-ad5d5f179cb5.png)

### Expected behavior
Email app is opened, as it is in Fennec or Chrome

### Actual behavior
Nothing happens

### Device information
* Android device: LG G7 Android 9
* Fenix version: Firefox Nightly 200502 (40.0.20200430224518)

**Comment by cadeyrn** [comment] 2020-05-04 08:28
> of this page

which page? Could you share a URL?

**Comment by Dimas-sc** [comment] 2020-05-04 08:41
> 
> 
> > of this page
> 
> which page? Could you share a URL?

Ups, sorry! Post updated, the url is cfagirona.cat

**Comment by ValentinTimisica** [comment] 2020-05-22 13:06
Investigated this and found a `mailto` that works (https://daleharvey.github.io/testapp/) and we have the one from the first comment that doesn't work.

For the `mailto` that works, `onLoadRequest` from `GeckoSession` is called and then it propagates to `AppLinksUseCases` where [context.startActivity](https://github.com/mozilla-mobile/android-components/blob/dde63c00b4cd42b2a46f743972985637604d089d/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt#L219) is called.

For the `mailto` that does't work, `onLoadRequest` from `GeckoSession` is not called at all.

I also tested this in Reference Browser and it has the same behavior as Fenix(`mailto` from https://daleharvey.github.io/testapp/ works but the `mailto` from first comment doesn't).

In Fennec it works well on all pages that I tested.

For GeckoViewExample app nothing happens when I tap on those links but I posted below the logs:
- [logs](https://pastebin.com/kQ6FMH9q) for the `mailto` that "works"
- [logs](https://pastebin.com/Awrmpb0e) for the `mailto` that "doesn't work"

Hope I'm not wrong but I think is'a a GV bug.

**Comment by Amejia481** [comment] 2020-05-22 13:35
> Investigated this and found a `mailto` that works (https://daleharvey.github.io/testapp/) and we have the one from the first comment that doesn't work.
> 
> For the `mailto` that works, `onLoadRequest` from `GeckoSession` is called and then it propagates to `AppLinksUseCases` where [context.startActivity](https://github.com/mozilla-mobile/android-components/blob/dde63c00b4cd42b2a46f743972985637604d089d/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt#L219) is called.
> 
> For the `mailto` that does't work, `onLoadRequest` from `GeckoSession` is not called at all.
> 
> I also tested this in Reference Browser and it has the same behavior as Fenix(`mailto` from https://daleharvey.github.io/testapp/ works but the `mailto` from first comment doesn't).
> 
> In Fennec it works well on all pages that I tested.
> 
> For GeckoViewExample app nothing happens when I tap on those links but I posted below the logs:
> 
>     * [logs](https://pastebin.com/kQ6FMH9q) for the `mailto` that "works"
> 
>     * [logs](https://pastebin.com/Awrmpb0e) for the `mailto` that "doesn't work"
> 
> 
> Hope I'm not wrong but I think is'a a GV bug.

It will be good to open a Bugzilla bug for the GV team to investigate

**Comment by ValentinTimisica** [comment] 2020-05-25 07:50
Seems like there was a bug opened in Bugzilla but now it's closed: https://bugzilla.mozilla.org/show_bug.cgi?id=1629243
Should I open another one?

**Comment by Amejia481** [comment] 2020-05-25 14:39
Yes, please let's open another one!

**Comment by ValentinTimisica** [comment] 2020-05-26 06:16
Created https://bugzilla.mozilla.org/show_bug.cgi?id=1640807 in bugzilla.

**Comment by ValentinTimisica** [comment] 2020-05-26 16:06
Seems like the ticket that I created was a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1596825 with Resolution: --- → FIXED. Check [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1640807#c1).

**Comment by liuche** [comment] 2020-06-05 01:35
@ValentinTimisica since the GV issue here has been closed, is there anything on the Fenix side that needs to be done to pull in these changes to `onLoadRequest` or should that have come with the GV Nightly update? If it's handled automatically by updating GV version, please add a qa-needed label, thank you!

**Comment by ValentinTimisica** [comment] 2020-06-09 07:47
It's working well for me. Adding QA to double check.

**Comment by LaurentiuApahideanSV** [comment] 2020-06-09 14:02
Verified as fixed on Firefox Preview Nightly 200606 (Build #21610607) using a OnePlus 6T (Android 9) and Huawei MediaPad M3 (Android 7.0).

**Comment by ValentinTimisica** [comment] 2020-06-10 05:49
Closing this since it's verified as fixed.

**Closed** 2020-08-11 00:38 UTC
Labels: Feature:OpenInApp, eng:qa:verified, needs:gv, needs:investigation, 🐞 bug
