### ISSUE TITLE
FNX-3403 ⁃ [Bug] Top Site uses only 4 elements/sites spaces instead of 5.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10281] opened 2020-04-29 08:58 UTC
## Steps to reproduce
Top site row has only 4 elements/sites instead of 5 thereby leaving empty space. But it uses all elements/site spaces when device is rotated/in horizontal mode
Please see the screenshot for clarification.

### Expected behavior
It should use all 5 element's/site spaces

### Actual behavior
Only uses 4 spaces

### Device information
* Android device: Motorola One Power, Android 10.
* Fenix version: Firefox Beta 5.0.0-beta.1 (Build #2015737283) and Nightly 200428 06:00 (Build #2015737139)
![Fotor](https://user-images.githubusercontent.com/42088907/80577845-175b2c80-89f7-11ea-95d9-67ce7510a0ab.jpg)UNITO-UNDERSCORE!158815002886584!
![Fotor](https://user-images.githubusercontent.com/42088907/80577868-204bfe00-89f7-11ea-921c-57a66c872408.jpg)UNITO-UNDERSCORE!158814998073416!

**Comment by SS1113** [comment] 2020-04-29 12:15
Another thing to note is that it did use all 5 spaces before but suddenly, I don't remember when it changed, but it surely did use all of the space when the device was held vertically.

**Comment by Cheap-Skate** [comment] 2020-04-29 17:53
Duplicate of #9123 I think

I have this issue too, the behavior changed a few weeks ago.

**Comment by SS1113** [comment] 2020-04-30 01:55
@Cheap-Skate I think the issue #9123 is talking about the increasing the spacing between individuals top sites so that it acquires all of the space on individual rows. So that is different. This issue talks about the number of elements each row is holding has reduced from before which was 5 on my device but is only 4 now.

**Comment by Cheap-Skate** [comment] 2020-05-30 09:09
Now #11065 has landed I now only get 3 favicons on each Top Sites row, down from 4 previously!

![Screenshot_20200530-100325_Firefox Nightly](https://user-images.githubusercontent.com/40568887/83324492-75c93400-a25d-11ea-8a2a-ca1d65040717.jpg)

**Comment by SS1113** [comment] 2020-05-30 09:29
@Cheap-Skate Yes, you're right. I'm also seeing only 3 top sites elements now, don't know what's happening, first there were 5 and then 4 and now 3...😅

**Comment by SeburoSUMO** [comment] 2020-06-01 20:18
I too am seeing three across in the latest Nightly, but the space on the right-hand side suggests there should be four across to make the page more balanced and also easier to use for people who hold a phone in the right hand using the device one-handed.

**Comment by cadeyrn** [comment] 2020-06-05 14:22
> Let's limit to 8 top sites (2 rows a 4 sites)

https://github.com/mozilla-mobile/fenix/issues/8312#issuecomment-638825961

I think this issue is still valid since some user only have 3 sites per row but the issue should be renamed to reflect that the goal are 4 sites per row.

**Comment by Diana-Rus** [comment] 2020-06-12 14:53
Hi, now it seems that there are 4 top sites per row not 3, but not yet 5, checked on the Nightly 6/12 build with:
- Google Pixel 3 XL (Android 9)
![Screenshot_20200612-172955_Firefox Nightly](https://user-images.githubusercontent.com/49859863/84514952-80abac00-acd4-11ea-85c4-e7cb94e4ce17.jpg)

- Samsung Galaxy S9 (Android 8)
![Screenshot_20200612-174121_Firefox Nightly](https://user-images.githubusercontent.com/49859863/84514971-873a2380-acd4-11ea-99e2-83176b3795d2.jpg)

- Sony Xperia Z5 (Android 7)
![Screenshot_20200612-174323](https://user-images.githubusercontent.com/49859863/84514984-8b664100-acd4-11ea-8e16-4fac632d73ea.png)

@mcarare - is there a way to have 5 top sites on a row?

**Comment by SS1113** [comment] 2020-06-12 15:09
As can be seen in the screenshots there are only 4 sites occupying space, thus there is empty space remaining at the right side, please either increase the spacing between each site or add another site towards the right position so it occupies all space as was the case before it reduced to just 4 sites. It just feels broken to me as it is now.

**Comment by Diana-Rus** [comment] 2020-06-12 15:19
Hi @SS113 , it seems that the the build with the fix is not yet present in the latest nightly, i've mistaken the build.
I'm going to create in the meantime a build taken from master, that should contain the fix.
I'll post the results here after having it checked.

**Comment by Diana-Rus** [comment] 2020-06-12 16:31
@mcarare  , @SS1113  - Re-checked with same devices, the top sites favicons are displayed correctly.
They are multiple on a row - as reference for the left and right side boundary of the flexibox, you can take in consideration the Collections border:

**Google Pixel 3 XL (Android 9)**
![Screenshot_20200612-190721](https://user-images.githubusercontent.com/49859863/84523881-be630180-ace1-11ea-92a4-ffc7da6e1aeb.png)

![Screenshot_20200612-190638](https://user-images.githubusercontent.com/49859863/84523891-c15df200-ace1-11ea-81cc-cf3dfa04940c.png)

**Samsung Galaxy S9 (Android 8)**
![Screenshot_20200612-191639_Firefox Nightly](https://user-images.githubusercontent.com/49859863/84524151-27e31000-ace2-11ea-89fb-04356ea10cf7.jpg)

![Screenshot_20200612-191612_Firefox Nightly](https://user-images.githubusercontent.com/49859863/84524163-303b4b00-ace2-11ea-875f-0794bdf7122f.jpg)

**Sony Xperia Z5 (Android 7)**
![Screenshot_20200612-190145](https://user-images.githubusercontent.com/49859863/84523943-d2a6fe80-ace1-11ea-8bd2-d567fd066437.png)

![Screenshot_20200612-190108](https://user-images.githubusercontent.com/49859863/84523961-d76bb280-ace1-11ea-85fd-3c3b10eff1d6.png)

Note:  To be taken in consideration that now the flexibox will adjust automatically and so it will depend on device used (phone/ tablet) and the width of the  device.

**Comment by sheikh-azharuddin** [comment] 2020-06-13 04:22
Yes in new build this is fixed..you have added 5 icons per row but by reducing the size of the icon and placing them close... However there is still too much space left after the 5th icon..why not utilize the space to increase spacing between the icons or increase the size of the icon....any reason for not using the space? the space on the left of the 1st icon is not same as space after last icon....

**Comment by SS1113** [comment] 2020-06-13 04:33
@sheikh-azharuddin you are right. As you can see in the screenshots om devices that QA verified with, there's no consistently in them, none of the device utilises all of the space. And in my case all of the space is used when the device is held vertically and when held horizontally it leaves space on the right side. See the screenshots

Device: Motorola One Power, Android 10.
Fenix: `Nightly 200612 18:01`.
![Screenshot_20200613-004756](https://user-images.githubusercontent.com/42088907/84559947-c006e680-ad2e-11ea-98a6-2ad3068d7b37.png)
![Screenshot_20200613-004736](https://user-images.githubusercontent.com/42088907/84559951-c4330400-ad2e-11ea-8824-ece67c05ba22.png)

**Comment by sheikh-azharuddin** [comment] 2020-06-13 04:39
> @sheikh-azharuddin you are right. As you can see in the screenshots om devices that QA verified with, there's no consistently in them, none of the device utilises all of the space. And in my case all of the space is used when the device is held vertically and when held horizontally it leaves space on the right side. See the screenshots
> 
> Device: Motorola One Power, Android 10.
> Fenix: `Nightly 200612 18:01`.
> ![Screenshot_20200613-004756](https://user-images.githubusercontent.com/42088907/84559947-c006e680-ad2e-11ea-98a6-2ad3068d7b37.png)
> ![Screenshot_20200613-004736](https://user-images.githubusercontent.com/42088907/84559951-c4330400-ad2e-11ea-8824-ece67c05ba22.png)

The vertical mode looks ugly in my phone..too much space left after the last icon....not sure why the difference in different phone maybe they are using fixed pixel instead of percentage.

![Screenshot_20200613-100848](https://user-images.githubusercontent.com/58127841/84560068-cf3a6400-ad2f-11ea-8f45-9c100b008b12.jpg)

**Comment by SS1113** [comment] 2020-06-13 04:52
@sheikh-azharuddin I don't know they said they are adjusting the top sites based on the device used. What device are you using?

@mcarare Can you please clarify what's going on here? 


@sheikh-azharuddin A request to you if you don't mind, instead of quoting the whole comment everytime you can just simply reply to it without quoting it and quote only the parts of the comment or the whole comment only if  necessary or just mentioning their username will enough. Otherwise it'll clutter the issues' comment page and it's frustrating for me because I have to scroll more to see what you actually wrote. It's just a suggestion. Thank you.

**Comment by sheikh-azharuddin** [comment] 2020-06-13 05:15
@SS1113 i am using asus rog 2.
Sorry for the quotes....

**Comment by SS1113** [comment] 2020-06-13 05:22
@sheikh-azharuddin No worries... :)

**Comment by SeburoSUMO** [comment] 2020-06-14 11:56
I filed an issue previously that was rolled up into this one looking at the spacing of the top sites (irrespective of whether it was 3, 4 or 5 a row) as the spacing looked a bit odd.  It always looked like there was space for another site in the row with a sizeable space on the right-hand side.

Having just updated (both Fenix Nightly and migrated Fennec Nightly), I can see that is no longer the case.  Sure, the top sites now show five, but more importantly, visually it looked much more balanced.

Regardless of whether it is 3, 4, or 5 a row, that it looks more balanced and equally spaced makes the user experience much nicer.

Great work and thanks to the people that have worked to get this resolved.

**Comment by sheikh-azharuddin** [comment] 2020-06-16 03:45
> I filed an issue previously that was rolled up into this one looking at the spacing of the top sites (irrespective of whether it was 3, 4 or 5 a row) as the spacing looked a bit odd. It always looked like there was space for another site in the row with a sizeable space on the right-hand side.
> 
> Having just updated (both Fenix Nightly and migrated Fennec Nightly), I can see that is no longer the case. Sure, the top sites now show five, but more importantly, visually it looked much more balanced.
> 
> Regardless of whether it is 3, 4, or 5 a row, that it looks more balanced and equally spaced makes the user experience much nicer.
> 
> Great work and thanks to the people that have worked to get this resolved.

I will open a new case....even though 5 icons added there is still space left after 5th icon looks ugly...probably this is related to large screen devices like mine...

**Comment by SS1113** [comment] 2020-06-17 04:43
@sheikh-azharuddin the top sites now look really small in the `5.2.0-beta.2`
I think the developers have finalized the design and behaviour of this so I think we won't have a say in it 😔

**Comment by sheikh-azharuddin** [comment] 2020-06-17 06:33
@SS1113 for you it's still looks better...for me there is too much space left after 5th icon ...so the space before 1st icon and space after 5th icon is not consistent... probably because I have large screen device I have this but ideally the UI should adapt to the screen size and maybe they are using fixed size pixel instead of relative values or percentage.
Looks ugly in my device

@cadeyrn please help to push this😓

![Screenshot_20200617-120220](https://user-images.githubusercontent.com/58127841/84863342-52c3c000-b064-11ea-84f5-b5da06cdf937.jpg)

**Comment by cadeyrn** [comment] 2020-06-17 06:53
> @cadeyrn please help to push this😓

How? I am still a user like you.

**Comment by sheikh-azharuddin** [comment] 2020-06-17 06:56
> > @cadeyrn please help to push this😓
> 
> How? I am still a user like you (and to be honest I don't need top sites at all - I only kept the two default top sites enabled for testing reasons).

But people listens you ...I have posted several issues no one replied except you and in most cases closed with remark duplicate

**Comment by SS1113** [comment] 2020-06-17 07:01
@cadeyrn they might be asking because you are a developer as well and you have contributed to this repository before as your `Contributor` badge indicates. Don't mind them.

And saying that you don't need need top sites and so you won't care about it is I think a bit rude to who has asked for help. You can deny them but be little more tactful. Please take what I'm saying as a request from your fellow community member.

**Comment by SS1113** [comment] 2020-06-17 07:13
@sheikh-azharuddin I think we should stop this discussion here and let the developers do what they want and how they want it. 

I have been asking too but if they don't even care to reply to the bug reporter then I think we should take it as a sign that the developers don't care what we are saying so we stop all of this! I don't see anything positive coming out of this discussion now.

And if we keep on discussing this they  might just lock this issue. I'm not replying to this thread anymore now! 

And again they already closed this issue as fixed and working as intended so...

**Comment by sheikh-azharuddin** [comment] 2020-06-17 07:18
@SS1113 true bro...they do what they think is right...🤣
No more reply after this...

**Comment by cadeyrn** [comment] 2020-06-17 07:19
> And saying that you don't need need top sites and so you won't care about it is I think a bit rude to who has asked for help. You can deny them but be little more tactful. Please take what I'm saying as a request from your fellow community member.

Please do not exaggerate. 🙄 I said this senctence to explain why I won't advocating for a change. It doesn't make sense to advocate for a change if you don't care. Mozilla should only consider the opinion of people who care about this.

**Comment by mcarare** [comment] 2020-06-17 08:07
@shahsurajk We will revisit this issue once the changes in https://github.com/mozilla-mobile/fenix/issues/11081 are implemented.
Just a note until then: Given your screenshot, if you try to add another item in the remaining space, it will not fit as to allow for same padding at the end as the padding in the left. It might seem that another item could fit, but measuring all space and taking into consideration the item size, it will not. The issue could look better if the layout would be centered, but that is not in the specs.

**Comment by SS1113** [comment] 2020-06-17 08:08
@cadeyrn I thought I always tried to be respectful to everyone. 

Apologies for my rudeness.

**Comment by shahsurajk** [comment] 2020-06-17 08:20
@mcarare I think you tagged the wrong person here.

**Comment by SS1113** [comment] 2020-06-17 08:29
> > And saying that you don't need need top sites and so you won't care about it is I think a bit rude to who has asked for help. You can deny them but be little more tactful. Please take what I'm saying as a request from your fellow community member.
> 
> That's… cheeky. And that for no reason. I said this senctence to explain why I won't advocating for a change. It doesn't make sense to advocate for a change if you don't care. Yes, sometimes I report a bug or share my thoughts even for this feature but that's all. Mozilla should consider the opinion of people who really care about this. I don't use this feature so my opinion about this is not in the same way relevant as the opinion of others. Do you advocate for features I care but you don't care? No, you don't. And if someone asks me to advocate for this feature I should explain why I won't do this, no? Again: I am a user as you or every other user. And I have my own opinions. There was nothing "rude" on my comment at all. To explain why I won't advocate is not rude. If anything, your comment to me was rude. "Be respectful in all interactions and communications" - https://www.mozilla.org/en-US/about/governance/policies/participation/

@cadeyrn I was not forcing you to advocate something which you don't want to, that'd be wrong! I was just saying that deny the request with a bit more tactfulness so someone who's asking for help doesn't get upset about it.

**Comment by SS1113** [comment] 2020-06-17 08:56
>Do you advocate for features I care but you don't care? No, you don't.

@cadeyrn I _will_ advocate if I think it'll benefit everybody in a good way! Even if it doesn't benefit me it'll benefit them ( perhaps that feature will benefit my friends, the people I know or the community).

I always try to think about me and everyone else simultaneously!

I think you got my comment wrong! But still take my apologies if I hurt you!

**Comment by cadeyrn** [comment] 2020-06-17 10:02
It's all good. But I guess one comment instead of three would have been enough. Remember that other people get notifications for each comment. Let's focus on the topic again. 😉

**Comment by SS1113** [comment] 2020-06-17 10:32
@cadeyrn yes, I know that everyone gets notifications each time I comment. But I wanted to make sure that my apologies reached you!

Thanks a lot!

**Comment by OsadebamwenEvbuomwan** [comment] 2020-06-27 03:07
Still have this.problem on Nokia 8

**Closed** 2020-08-10 19:48 UTC
Labels: Feature:TopSites, P2, eng:qa:verified, eng:ux-debt, 🐞 bug
