### ISSUE TITLE
Adding a new search partner

### ISSUE THREAD

**Issue by mkaply** [mozilla-mobile/fenix#6480] opened 2019-11-06 20:16 UTC
We're adding a new search partner to Fenix, Ecosia.

The search URL is:

https://www.ecosia.org/search?q={searchTerms}&tt=813cf1dd

This will be for Germany (de) only.

**Comment by st3fan** [comment] 2019-11-07 22:32
@pocmo the list of search partners + codes lives in A-C right?

**Comment by pocmo** [comment] 2019-11-08 11:15
@mkaply Was that change made in mozilla-central/mobile/ too? Then we could just re-import that into AC.

Otherwise we can update list.json and the plugins in AC:
- https://github.com/mozilla-mobile/android-components/blob/master/components/browser/search/src/main/assets/search/list.json
- https://github.com/mozilla-mobile/android-components/tree/master/components/browser/search/src/main/assets/searchplugins
@mkaply Would you want to create a PR for that in AC? You know those files the best.. :)

**Comment by mkaply** [comment] 2019-11-08 21:46
No, this was a specific change for just Fenix. I'll create a patch.

**Comment by veyselerden** [comment] 2019-11-12 13:21
Why just Germany? I am not in Germany but want to use Ecosia with Fenix, not Ecosia app on Android which is based on Chromium.

**Comment by pocmo** [comment] 2019-11-12 15:32
> No, this was a specific change for just Fenix.

Alright. In this case we could still consider landing the search plugin in AC. Focus and Fire TV have custom code to mix in and filter search engines. This should also work for adding this search engine dynamically.

**Comment by cadeyrn** [comment] 2019-11-20 06:26
> Why just Germany? I am not in Germany but want to use Ecosia with Fenix, not Ecosia app on Android which is based on Chromium.

Since #6551 Ecosia is shipped as optional search engine and you can manually enable it. And even if not, since #6551 you can also add custom search engines.

**Comment by liuche** [comment] 2019-11-25 22:32
@mkaply are you handling this? incl writing tests, etc.

**Comment by mkaply** [comment] 2019-11-26 17:35
It's being done here: in android components and then we can put it in Fenix

https://github.com/mozilla-mobile/android-components/pull/5059

**Comment by sv-sdeiac** [comment] 2019-12-18 10:24
Hello, I can confirm that this issue is fixed on the latest version of Firefox Preview Nightly 191218 #13520613 12/18.

Devices: 
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8.0);
- Xiaomi Mi 8 Lite (Android 9);
- Samsung Galaxy Note 8 (Android 9).

**Closed** 2020-01-03 18:21 UTC
Labels: Feature:SearchProvider, eng:qa:verified, must, needs:ac

**Comment by ghoppaccia** [comment] 2020-01-22 13:02
> > Why just Germany? I am not in Germany but want to use Ecosia with Fenix, not Ecosia app on Android which is based on Chromium.
> 
> Since #6551 Ecosia is shipped as optional search engine and you can manually enable it. And even if not, since #6551 you can also add custom search engines.

But custom engines do not give you search suggestions.
Why is it only enabled for german locale? It was there in Firefox Preview (not anymore with the latest update), but not in Nightly.

**Comment by sblatz** [comment] 2020-01-22 18:39
@ghoppaccia I have filed a bug for custom engines not giving search suggestions which should solve your issue :) 

https://github.com/mozilla-mobile/fenix/issues/7866

**Comment by clauub** [comment] 2021-04-01 07:33
@mkaply @sblatz I know this issue is closed, but I have a question based on default search engine. Is there any option to edit list.json file with my custom search engine needs ?

**Comment by pocmo** [comment] 2021-04-01 08:55
@clauub In Fenix itself you can change the search engines in settings. If this is for your own build then you can place a custom list.json into your app and override the one coming from the component.

**Comment by clauub** [comment] 2021-04-01 08:57
@pocmo  So if I'm creating a new list.json file this should work fine ?

**Comment by clauub** [comment] 2021-04-01 11:53
> @clauub In Fenix itself you can change the search engines in settings. If this is for your own build then you can place a custom list.json into your app and override the one coming from the component.

Thanks a lost, I solved it.

**Comment by imnotabr** [comment] 2021-04-09 21:24
@clauub how do you override list.json in search and the .xml files in the search plugins coming from component? 

Here is my issue: https://github.com/mozilla-mobile/fenix/issues/18908
