### ISSUE TITLE
[Bug] Sound gets distorted when changing the speed

### ISSUE THREAD

**Issue by AndRo-Marian** [mozilla-mobile/fenix#17993] opened 2021-02-14 16:06 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open the https://m.youtube.com/watch?v=S0pHPKQak88
2. Go to gear icon, select speed, change to 0.75 or any other speed.

### Expected behavior
To be slow or fast but without distortions.

### Actual behavior
Adds some weird sounds like: crackling, pauses, ...

### Device information
Huawei P10 Lite WAS-LX1
Android 8.0.0.397 C432

85.1.3 (Build #2015792283)
AC: 70.0.20, d282b98ef
GV: 85.0.2-20210208133944
AS: 67.2.0
* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by Dunexus** [comment] 2021-02-15 09:43
Duplicate of https://github.com/mozilla-mobile/fenix/issues/8456

**Comment by Mugurell** [comment] 2021-02-15 10:16
Closing this as a duplicate.
Please follow https://github.com/mozilla-mobile/fenix/issues/8456 and https://bugzilla.mozilla.org/show_bug.cgi?id=1624026.

**Closed by Mugurell** 2021-02-15 10:16 UTC
Labels: needs:triage, 🐞 bug

**Comment by AndRo-Marian** [comment] 2021-04-30 22:05
Not sure when this stared but in 68.11.0 works good like many others.
