### ISSUE TITLE
[Bug]: Zakup rzeczy w aplikacji internetowej za pomoca metody BLIK.

### ISSUE THREAD

**Issue by Wiktor1305** [mozilla-mobile/fenix#22526] opened 2021-11-21 13:19 UTC
### Steps to reproduce

1. Otwieram strone allegro.pl .
2. Wyszukuje istniejacy produkt.
3. Wchodze w okno detali produktu.
4. Naciskam przycisk "kup teraz".
5. Wybieram opcje przesylki.
6. Wybieram platnosc metoda BLIK.
7. Wpisuje niepoprawny kod BLIK.

### Expected behaviour

Strona banku laduje sie ponownie abym mogl ponowic probe wpisania poprawnego kodu BLIK.

### Actual behaviour

Przekierowanie na strone sprzedawcy i komunikat o nieprawidlowym kodzie BLIK, brak mozliwosci kolejnej proby zaplaty.

### Device name

Xiaomi Mi 10 T Lite

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

89.0.10

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18688)

**Comment by cadeyrn** [comment] 2021-11-21 19:25
I don't undestand anything due to the language but Firefox 89 is outdated and whatever your issue is you should first try if the current version of Firefox is still affected.

**Comment by SoftVision-LorandJanos** [comment] 2021-11-29 15:16
I translated the steps with the help of google translate, and edited a bit to be easily understandable, please correct me if it's wrong somewhere:

### Steps to reproduce:

1. Open the website allegro.pl.
2. Search for an existing product.
3. Enter the product detail window.
4. Press the button "buy now".
5. Choose shipping options.
6. Choose the BLIK method of payment.
7. Enter an incorrect BLIK code.

### Expected behavior:
The bank's website reloads so that I can repeat my attempt to enter the correct BLIK code.

### Actual behavior:
Redirection to the seller's website and a message about an incorrect BLIK code, no possibility of another payment attempt.

I couldn't reproduce the issue described. The behavior is the same in both Chrome and Firefox builds, I got an error message about the code being incorrect. Please try reproducing it on the latest build as well. If you still reproduce it, please make a video of the issue. Thank you!
Tested on the following builds:
- latest Nightly (2021-11-29).
- latest Beta (95.0.0-beta6).
- latest Release (94.1.2).
- Chrome.

Device used: Xiaomi Mi11 Lite (Android11).

**Comment by jonalmeida** [comment] 2023-01-17 06:39
> The behavior is the same in both Chrome and Firefox builds

This sounds like it might be a bug on the website itself. Closing as invalid for now based on Lorand's testing and cadeyrn's point about this being a very old build.

**Closed by jonalmeida** 2023-01-17 06:39 UTC
Labels: 🐞 bug, Feature:ErrorMessages, S3, needs:triage, Feature:Autofill, qa-triaged
