### ISSUE TITLE
Add-ons and themes for android version

### ISSUE THREAD

**Issue by rahul-ankamreddi** [mozilla-mobile/fenix#17155] opened 2020-12-20 17:33 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
By introducing more add-ons and themes that are available for desktop version into android version, firefox's mobile users will increase.
### How do you know that this problem exists today? Why is this important?
People like wearing new clothes, similarly, they like trying new themes on the browser that they use everyday. That is why it is important to introduce this feature.
### Who will benefit from it?
All the mobile users of mozilla firefox browser.

**Comment by cadeyrn** [comment] 2020-12-21 08:43
Duplicate of #10032 for themes. For add-ons there are already numerous other issues.

**Closed** 2020-12-21 08:46 UTC
Labels: needs:triage
