### ISSUE TITLE
RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#20402] opened 2021-07-16 22:09 UTC
bz-1720840

https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9238032/?referrer=github_plugin

```
ClassCastException: mozilla.components.browser.state.state.CustomTabSessionState cannot be cast to mozilla.components.browser.state.state.TabSessionState
    at org.mozilla.fenix.telemetry.TelemetryMiddleware.invoke(TelemetryMiddleware.kt:23)
    at org.mozilla.fenix.telemetry.TelemetryMiddleware.invoke(TelemetryMiddleware.kt:23)
...
(80 additional frame(s) were not displayed)

StoreException: Exception while reducing state
    at mozilla.components.lib.state.Store$$special$$inlined$CoroutineExceptionHandler$1$lambda$1.run(Store.kt:1)
    at android.os.Handler.handleCallback
    at android.os.Handler.dispatchMessage
    at android.os.Looper.loop
    at android.app.ActivityThread.main
...
(3 additional frame(s) were not displayed)

InvocationTargetException: None
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    at com.android.internal.os.ZygoteInit.main

RuntimeException: java.lang.reflect.InvocationTargetException
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    at com.android.internal.os.ZygoteInit.main

java.lang.reflect.InvocationTargetException
```

**Comment by jonalmeida** [comment] 2021-07-16 22:50
### Steps to reproduce
- Open this [Twitter link](https://twitter.com/jonathanmartinz/status/1415951908787916809?s=20) in a Custom Tab.
- Click the video on the tweet.

## Expected Results
This should not crash.

**Comment by jonalmeida** [comment] 2021-07-16 23:28
The bug is in `LastAccessReducer`. We assume that the session is always a TabSessionState, which is true for the `lastAccess` long, but not the case with a Custom Tab it seems.

For now, the quickest fix to stop the crash is to disable this middleware.

**Comment by jonalmeida** [comment] 2021-07-20 18:19
This exception has gone back down in Sentry, so I'm confident in closing this. Petru is alreayd working on an update in AC (linked above).

**Closed by jonalmeida** 2021-07-20 18:19 UTC
Labels: Feature:Media, b:crash, 🐞 bug

**Comment by Mugurell** [comment] 2021-07-22 06:44
The support for this feature was rewritten in AC and this issue should be resolved but when manually testing it I saw an edgecase that will still exists: user navigates to another url and media session is disabled -> we'll forget this tab had in progress media.

The soundcloud.com scenario:

    start playback
    -> we update the new LastMediaAccessState -> hasPlayedMedia == true.
    access another soundcloud page in this tab, playback continues
    -> the tab url for when media started changes but because media is playing -> hasPlayedMedia == true.
    start playing media in another tab
    -> media stops playing in the soundcloud tab
    -> GeckoView deactivates that MediaSession
    -> tab url is different from when media started, MediaSession is deactivated -> hasPlayedMedia is now false.
