### ISSUE TITLE
FNX-3264 ⁃ Download with non-Fenix App

### ISSUE THREAD

**Issue by Shabdaa** [mozilla-mobile/fenix#10062] opened 2020-04-20 16:58 UTC
When I want to download a file، it has only one option and it's download by browser. 

in Firefox Orginal it gives you options and apps to download from and it is very useful. 

Acceptance Criteria (how do I know when I’m done?)

**Comment by hakkikaancaliskan** [comment] 2020-04-20 22:27
Duplicate of #7620

**Closed** 2020-08-10 18:37 UTC
Labels: Feature:Download, feature request 🌟, needs:triage
