### ISSUE TITLE
[Bug]: Reopened tabs lose position in tab switcher interface

### ISSUE THREAD

**Issue by eberhardweber** [mozilla-mobile/fenix#20894] opened 2021-08-17 17:42 UTC
### Steps to reproduce

1. Have more than 1 tab open
2. Close a tab
3. Reopen tab with "Tab closed - Undo" dialogue
4. Reopened tab loses its position and is returned to the tab switcher list in 1st place (oldest tab, wrong position).

### Expected behaviour

The tab should be returned to its original position in the tab switcher interface.

### Actual behaviour

The tab loses its position in the tab switcher and is positioned first in the list. I have to scroll the tab switcher interface all the way up through hundreds of tabs to be able to use the tab.

At the _very least_ the tab should be the "newest" tab (_last_ item in list) and not the "oldest" (_first_ in menu). 

### Device name

Xiaomi Poco M3 Pro 5G

### Android version

Android 11 (12.0.9 Global)

### Firefox release type

Firefox

### Firefox version

Fennec 90.1.1 (Build #901120)

### Additional information

Perhaps this long-standing bug is due to the tab direction being arbitrarily and needlessly switched in an earlier version in Fenix development?

**Comment by amedyne** [comment] 2021-08-17 17:59
This is a duplicate of #10986. Closing this to refer to 10986.

**Closed by amedyne** 2021-08-17 17:59 UTC
Labels: 🐞 bug, needs:triage
