### ISSUE TITLE
FNX-12872 ⁃ [Bug] going to the previous tab became a nightmare with 5.2.0

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#11876] opened 2020-06-24 08:29 UTC
![ScreenRecord-2020-06-24-11-22-44](https://user-images.githubusercontent.com/14617699/85521671-4368e780-b60d-11ea-8cb8-815e0576ff8a.gif)

### Steps to reproduce
Try to switch the previous tab

### Actual behavior
Fenix just closes tab list as soon as it pulled a bit more.

**Comment by mcarare** [comment] 2020-06-24 09:34
This looks like same issue as #11042. Should be fixed by #11842, please try in next Nightly. Feel free to reopen if the issue is not fixed.

**Closed** 2020-08-11 05:07 UTC
Labels: needs:triage, 🐞 bug
