### ISSUE TITLE
FNX2-15559 ⁃ [Bug] Save tabs to collections button remains when we close all tabs

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12936] opened 2020-07-25 13:50 UTC
## Steps to reproduce
Open a tab
Open tab tray
Close tab

### Expected behavior
Save tabs to collection button view is gone

### Actual behavior
Remains visible, you need to move settings etc to let view gone.

### Device information
* Android device: Android 10 XZ1
* Fenix version: 25/7 nightly

cc @sblatz

**Comment by AndiAJ** [comment] 2020-07-27 08:10
Dupe of #11860  ?

**Comment by sblatz** [comment] 2020-07-27 22:14
Yeah, seems like a dupe to me :)

**Closed** 2020-08-11 12:54 UTC
Labels: Feature:HomeScreen, 🐞 bug
