### ISSUE TITLE
[Bug][Grid View] Scroll view not focused on last tab 

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#16487] opened 2020-11-10 20:23 UTC
#### Steps to reproduce
- Open 7 tabs or more
- Go back and open the 4th tab
- Go back to the tabs tray screen

### Expected behavior
- You can see the last tab (4th tab) without scrolling

### Actual behavior
- You have to scroll up to see the last tab.

### Device information

* Android device: Pixel 4
* Fenix version: 201109

**Comment by Mugurell** [comment] 2020-11-12 11:57
We can't reproduce this.
After opening tabs tray the app scrolls to it as intended and saw it always fully displayed.
Maybe there was something that got resolved in the meantime.
Asking QA to also verify.

**Comment by gabrielluong** [comment] 2020-11-16 16:00
Spoke with @vesta0 and she can also confirm that it is no longer happening.

**Comment by abodea** [comment] 2020-11-17 12:52
Verified as fixed on the latest **Nightly** 17/11 with **Google Pixel 4 XL (11).**
Note that I tried with more than 20 tabs opened with different scenarios and I couldn't reproduce this issue.
Thank you @gabrielluong!

**Closed by abodea** 2020-11-17 12:52 UTC
Labels: Feature:Tabs, eng:qa:needed, 🐞 bug
