### ISSUE TITLE
FNX-12059 ⁃ [Bug] The "Select collection" screen is broken

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#11182] opened 2020-06-03 11:58 UTC
## Steps to reproduce
1. Create one collection.
1. Open 2 or more tabs and long-click one to add it to a collection.
1. Check the title of the "Select collection" screen.
1. Tap "Add new collection"
1. Tap back, observe the list.
    1. Expected behavior
The title  "Select tabs" is incorrect.
The "Add new collection" button doesn't work. 
When going back to the previous screen, to "Select tabs", the list of collections is still displayed instead of selected tabs.
    1. Actual behavior

### Device information
* Android device: Pixel 2 (Android 10), Huawei P20 (Android 9)
* Fenix version: Nightly 6/3. NOT reproducing on Beta 5.1.0-beta3.

**Comment by mcarare** [comment] 2020-06-03 12:16
Just a note: clicking on "add new collection" text does not work, but clicking on the + button does.

**Comment by mcarare** [comment] 2020-06-03 13:08
The button part seems to be a regression from https://github.com/mozilla-mobile/fenix/pull/11053.

**Comment by sv-ohorvath** [comment] 2020-06-04 12:19
> ### Expected behavior
> The title "Select tabs" is incorrect.

@mcarare The screen title is still broken: going from Select tabs to Select collection, the title remains the same. Same for when you go back from the Name collection screen.

And now pressing the "+" on the Add new collection button, closes the screen.

**Comment by abodea** [comment] 2020-06-09 15:42
Verified as fixed on the latest **Nightly 6/9** with **Google Pixel 4 XL (10).**
Everything works as expected.

![20200609-182428](https://user-images.githubusercontent.com/42831109/84168758-75604280-aa80-11ea-9603-7af186398929.gif)

**Closed** 2020-08-11 03:21 UTC
Labels: Feature:Collections, S1, eng:qa:verified, 🐞 bug
