### ISSUE TITLE
[Bug] Top Sites sometimes cannot be removed.

### ISSUE THREAD

**Issue by jowi3** [mozilla-mobile/fenix#9260] opened 2020-03-19 21:37 UTC
## Steps to reproduce

- Add 2 or 3 rows of Top Sites.

- Try removing them, starting from the last one.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/62400461/77115896-381b8400-6a40-11ea-9586-b4b382d105dc.gif)

### Expected behavior

- "Remove" option should remove the Top Site.

### Actual behavior

- "Remove" option does not remove the selected Top Site sometimes (maybe related to row change animation).

### Device information
* Android device: Samsung J7 Prime (Android 8.1)
* Fenix version: Nightly 200318 18:01 (Build #2015729361)

**Comment by sv-sdeiac** [comment] 2020-03-20 10:59
Hi @jowi3, it seems that this issue is reproducible only if you have multiple entries from the same page. I think that this issue will be fixed when #8108 will also be fixed. 
Due to that, I'll close this issue, thanks for your ticket and if you have more updates, please feel free to add them on ticket #8108.

**Closed by sv-sdeiac** 2020-03-20 10:59 UTC
Labels: Feature:TopSites, eng:ready, needs:triage, 🐞 bug
