### ISSUE TITLE
[Bug] Favicons don't appear for some sites (but do appear on Chrome and Fennec)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#18382] opened 2021-03-09 01:18 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Like https://github.com/mozilla-mobile/fenix/issues/15033

From: https://www.reddit.com/r/firefox/comments/m084kx/having_difficulty_making_the_upgrade_from_fennec/

## Steps to reproduce

0. Set tab view to grid
1. Navigate to site
2. Use tab switcher

Site list:

- beacause.moe 
- Amazon.ca 
- konachan.com 
- yande.re 
- zerochan.net 
- Danbooru.donmai.us 
- bakarenders.com 
- minitokyo.net 

_a word of caution some of these are image hosts with nsfw content._

### Expected behavior

Favicon appears alongside name of site.

### Actual behavior

Random color with first letter of domain where favicon should appear. 

### Device information

* Device vendor / model and Android version: Pixel 2
* Firefox for Android version: Nightly 210307 17:01 (Build #2015797323)
AC: 74.0.20210307143117, 1d2587850
GV: 88.0a1-20210302034602
AS: 72.1.0

**Comment by LaurentiuApahideanSV** [comment] 2021-03-10 13:13
I can confirm the issue is reproducible on Firefox Preview Nightly 210309.

### Devices used:
- Samsung Galaxy S9 (Android 8.0)
- OnePlus 6T (Android 9)

**Comment by kbrosnan** [comment] 2021-03-11 05:04
* because.moe -> 16x16px favicon
* amazon.ca -> unknown (multi format icon including 16x16)
* konachan.com -> unknown (multi format icon including 16x16)
* yande.re -> 16x16px favicon
* zerochan.net -> unknown (multi format icon including 16x16)
* Danbooru.donmai.us -> 16x16px favicon
* bakarenders.com -> 16x16px favicon
* minitokyo.net -> unknown (multi format icon including 16x16)

I used unknown because I don't know the cause of the lack of icons.  It may be because the ico file contains multiple icon sizes including 16x16. The 16x16 icons are intentionally not used because the look poor blown up to display on high DPI displays. 

https://github.com/mozilla-mobile/android-components/issues/3814
https://github.com/mozilla-mobile/android-components/issues/4495

**Comment by j9t** [comment] 2021-06-16 08:02
Is this issue going to get further attention?

However, while the sites above seem to use 16×16 favicons, the issue is also reproducible on sites with, for example, 64×64 icons. Example: [uitest.com](https://uitest.com/), screenshots as follows (note the missing favicon in Firefox Android):

<img width="400" alt="Screen Shot 2021-06-16 at 09 55 19" src="https://user-images.githubusercontent.com/1700772/122180964-316cfe00-ce89-11eb-819f-0ea54e155381.png">

<img width="200" alt="Screenshot_20210616-094746" src="https://user-images.githubusercontent.com/1700772/122180989-37fb7580-ce89-11eb-8ee8-dd23f412b462.png">

In cases like this, the site has no markup indicating a favicon, but instead relies on it being located at /favicon.ico, as supported by other user agents (including Firefox desktop).

This behavior is also defined [by the HTML spec](https://html.spec.whatwg.org/multipage/links.html#rel-icon): “Let _request_ be a new request whose url is the URL record obtained by resolving the URL "/favicon.ico" against the Document object's URL […].”

Could Firefox for Android handle this consistently with other browsers as well as the spec?

**Comment by kbrosnan** [comment] 2021-07-08 16:52
Duplicate of 

https://github.com/mozilla-mobile/android-components/issues/10377
https://github.com/mozilla-mobile/android-components/issues/3814

**Closed by kbrosnan** 2021-07-08 16:52 UTC
Labels: Feature:TopSites, needs:ac, qa-triaged, 🐞 bug
