### ISSUE TITLE
FNX-5174 ⁃ Sometimes keyboard stays active when exiting the app

### ISSUE THREAD

**Issue by shorlander** [mozilla-mobile/fenix#1674] opened 2019-04-16 21:23 UTC
## Steps to reproduce
* Open Fenix
* Tap Search Field on Start Screen
* Press System Home Button
* Keyboard Stays Open

### Expected behavior
* Keyboard hides itself

### Actual behavior
* Keyboard stays open on top of app launcher and other apps

### Device information
* Android device: ?
Pixel 2
* Fenix version: ?
1.0.1916 (Build #11051220 68.0a1-20190408104625)

![photo](https://user-images.githubusercontent.com/684427/56244957-2da47d80-606c-11e9-815e-9d0123f73aee.jpeg)UNITO-UNDERSCORE!2019-04-16 17 20 53!

**Comment by kbrosnan** [comment] 2019-04-17 02:00
Dupe of #1668 should be fixed in a build shortly.

**Closed** 2020-08-11 12:28 UTC
Labels: 🐞 bug
