### ISSUE TITLE
Autoplay does not block video

### ISSUE THREAD

**Issue by plwt** [mozilla-mobile/fenix#22238] opened 2021-10-31 19:21 UTC
### Steps to reproduce

From a first run copy of Fenix

Set Autoplay in the permissions to "Block audio and video
Open https://www.livescience.com/mars-rover-perseverance-back-to-work-photos
Scroll down to "RECOMMENDED VIDEOS FOR YOU..."

### Expected behaviour

Video should not play

### Actual behaviour

Video plays

### Device name

Motorola Moto E5

### Android version

Android 8

### Firefox release type

Firefox

### Firefox version

93.2.0

### Additional information

User feedback: https://support.mozilla.org/en-US/questions/1355725

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18518)

**Comment by LaurentiuApahideanSV** [comment] 2021-11-01 10:19
I can confirm the issue is reproducible on Firefox Preview Nightly 2021-11-01.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by navid-zamani** [comment] 2021-11-26 05:51
This is probably the same bug:

https://www.tomshardware.com/picturestory/694-history-of-mobile-phones.html

Again, it (loads and) autopalys, if you scroll down to where the video is.

I guess it tricks Firefox into thinking the user did it, when ”it“ was merely a scrolldown event.

Can anyone with a large screen or something check if it autoplays if it is already visible on page load without scrolling?

**Comment by byzod** [comment] 2021-12-23 09:15
Still not fixed on 96b3

Try [this page](https://www.taptap.com/app/137515/topic?type=elite), click the category title to switch to [category `视频`](https://www.taptap.com/app/137515/topic?type=video) (above the posts list) and video start playing without any scrolling

It can even be reproduced on firefox desktop :/

**Comment by vinc17fr** [comment] 2023-01-04 23:06
Still not fixed in 109.0b5.

**Comment by csadilek** [comment] 2023-01-20 21:55
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811610

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2023-01-20 21:55 UTC
Labels: 🐞 bug, qa-triaged
