### ISSUE TITLE
[Bug] Unable to accept cookie prompt

### ISSUE THREAD

**Issue by drbluetongue** [mozilla-mobile/fenix#2634] opened 2019-05-18 22:48 UTC
Steps to reproduce:

Browse to https://xiaomi.eu/community/#xiaomi-miui-community-lounge.1

Click the "I accept" button on the Cookies disclaimer

Expected behavior:

Prompt goes away

Actual behavior:

Tapping Accept does nothing. Unable to dismiss the prompt.

### Device information
* Android device: Redmi Note 5 Pro Android Pie.
* Fenix version: 19/5/19 Google Play build

This works in normal Firefox Android.

**Comment by ekager** [comment] 2019-05-18 23:13
Dupe of https://github.com/mozilla-mobile/fenix/issues/2574

**Closed** 2020-08-26 06:03 UTC
Labels: 🐞 bug
