### ISSUE TITLE
[Bug] Desktop toggle loses state after clearing Fenix from memory

### ISSUE THREAD

**Issue by BubiBalboa** [mozilla-mobile/fenix#8104] opened 2020-02-05 12:08 UTC
## Steps to reproduce
request desktop view with toggle, close Fenix, clear recently open apps, open Fenix

### Expected behavior
desktop toggle should remember previous state and show the desktop view

### Actual behavior
Fenix loads mobile view, desktop toggle resets to off

### Device information
* Android device: OnePlus 6 with Android 10
* Fenix version: 200204 18:00

**Comment by lindongbin** [comment] 2020-02-05 15:13
https://github.com/mozilla-mobile/fenix/issues/7039
Need an option to set desktop mode default

**Comment by BubiBalboa** [comment] 2020-02-05 15:19
Those are two different issues, right? I don't mean that the toggle should request desktop mode for all sites but it should remember the setting for each site individually.

Desktop mode for all sites would be nice to have but I think this setting should be hidden in the setting menu.

**Comment by PyvesB** [comment] 2020-03-06 07:54
> Those are two different issues, right? I don't mean that the toggle should request desktop mode for all sites but it should remember the setting for each site individually.

If you read that other issue, you'll see that a per-site setting is one of the solutions discussed, so this is actually a duplicate. 

There would be a lot of challenges around such an approach, it was ultimately dismissed in the previous Fennec browser, hence the preferred alternative is currently a global setting.

**Comment by liuche** [comment] 2020-08-27 23:00
Dupe of #11552

**Closed by liuche** 2020-08-27 23:00 UTC
Labels: needs:triage, 🐞 bug
