### ISSUE TITLE
FNX-3379 ⁃ [Bug] error consulting the add-ons

### ISSUE THREAD

**Issue by joelocandol** [mozilla-mobile/fenix#10242] opened 2020-04-27 14:54 UTC
I updated nightly to 200427 06:01, then, my add-ons dissapear and it started to show an error loading these when I enter in the add-ons menu. But, all my add-ons still working

* Android device: 7.0
* Fenix version: 200427 06:01

**Comment by Amejia481** [comment] 2020-04-27 16:12
We are not able to simulate the issue anymore, could you provide us the logcat?  :)
QA could please help us to verify?

**Comment by softvision-miralobontiu** [comment] 2020-04-28 14:42
Hi @Amejia481 
We were not able to reproduce the issue. We've tried the following scenarios:
- had Fenix Nightly from 4/25, installed 2-3 add-ons, updated via PlayStore to 4/27 build => the add-ons were displayed as enabled and worked properly;
- migration Fennec → Fenix GV 76 from 4/6 → Fenix GV 77 from 4/16 → latest Fenix GV 77 from 4/27 (Build 200427 06:01) => the add-ons were displayed as enabled and worked properly;
- migration Fennec 68.5a1 (2020-01-20) → Fenix GV 77 from 4/27 =>  the add-ons were displayed as enabled and worked properly.

Tested with Sony Xperia Z5 Premium (Android 7.1.1), HTC 10 (Android 8), Samsung Galaxy Tab A6 (Android 5.1.1), Google Pixel 3a (Android 10), Huawei MediaPad M3 (Android 7.0), and OnePlus 6T (Android 9).

I'll remove the qa:needed label for now.
@joelocandol could you help us with more information? 

Thanks!

**Comment by Amejia481** [comment] 2020-04-28 16:09
I think we can close it. If there are any related issues please reopen.

**Closed** 2020-08-11 00:16 UTC
Labels: needs:STR, 🐞 bug
