### ISSUE TITLE
[Bug]: selecting already open tab opens "new tab" page instead

### ISSUE THREAD

**Issue by cstap5** [mozilla-mobile/fenix#26047] opened 2022-07-15 19:38 UTC
**Summary**: selecting an open tab after closing a private tab opens the "new tab" page instead

**Products affected**: Firefox for Android; Firefox Beta for Android.
**Versions affected**: current (102.2.1; 103.0.0-beta.4) and unknown number of prior versions.
**OS**: Android 12 on Samsung Galaxy

**Description**: with a tab or tabs open in the browser, closing a lone open private tab then selecting an already open (non-private) tab causes the "new tab" page to be displayed instead of the selected tab. This does not occur when selecting an open non-private tab after closing only one of multiple (2+) private tabs.

**Steps to reproduce**:
1. Open a webpage in a non-private tab
2. Open a webpage in a private tab
3. Close the private tab
4. Select the tab opened in step (1)

**Actual results**: "new tab" page is displayed

**Expected results**: open tab is displayed as when switching between several open tabs from the tab menu.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21026)

**Comment by DavidJCobb** [comment] 2022-07-25 16:30
Duplicate of #24529 and #23106.

**Comment by mcarare** [comment] 2022-07-28 12:28
@cstap5 Thank you for your report. This issue is already reported and tracked in #23106. Closing this as duplicate.

**Closed by mcarare** 2022-07-28 12:28 UTC
Labels: needs:triage
