### ISSUE TITLE
FNX-13074 ⁃ [FEATURE REQUEST] Support for External Download Manager

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#12057] opened 2020-06-27 16:51 UTC
Please add support for External Download Manager for downloading Manager, instead of downloading it within fenix itself. 

Who would benefit: everyone who downloads files

**Comment by Dunexus** [comment] 2020-06-27 17:53
Dupe of https://github.com/mozilla-mobile/fenix/issues/7620

**Comment by kbrosnan** [comment] 2020-06-27 21:39
Closing as a duplicate

**Closed** 2020-08-11 05:40 UTC
Labels: needs:triage
