### ISSUE TITLE
java.lang.IllegalThreadStateException: Expected `store` thread, but running on thread

### ISSUE THREAD

**Issue by t-p-white** [mozilla-mobile/fenix#28589] opened 2023-01-19 12:17 UTC
```
 Uncaught exception handled: 
java.lang.IllegalThreadStateException: Expected `store` thread, but running on thread `DefaultDispatcher-worker-10`. Leaked MiddlewareContext?
```

Changes made in #28565 has introduced a bug where multiple opening and closing of the app causes the application to crash.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22284)

**Comment by delia-pop** [comment] 2023-01-20 14:11
Hello, @t-p-white , is this something the QA team can verify, given the "qa:needed" label? If so, do you have any additional info to help us determine if the issue is indeed fixed? 
Based on the description above, after repeatedly opening and closing the latest Nightly 111.0a1 from 01/20 remains stable with Xiaomi 12 Pro (Android 13).

**Comment by delia-pop** [comment] 2023-01-27 14:41
Re-tested this and after repeatedly opening and closing the latest Nightly 111.0a1 from 01/27, the app remains stable with Google Pixel 6 (Android 13). Closing as verified fixed.

**Closed by delia-pop** 2023-01-27 14:41 UTC
Labels: eng:qa:needed, needs:triage

**Comment by t-p-white** [comment] 2023-01-31 11:39
> Hello, @t-p-white , is this something the QA team can verify, given the "qa:needed" label? If so, do you have any additional info to help us determine if the issue is indeed fixed? Based on the description above, after repeatedly opening and closing the latest Nightly 111.0a1 from 01/20 remains stable with Xiaomi 12 Pro (Android 13).

Hi @delia-pop apologies, I did not see the mention here. Thank you for progressing this.
