### ISSUE TITLE
[webcontent] Twitter mobile site scrolls up jumpy w/o user interaction

### ISSUE THREAD

**Issue by outloudvi** [mozilla-mobile/fenix#8522] opened 2020-02-19 08:53 UTC
## Site with issue and any steps to reproduce
Site: https://mobile.twitter.com . Both of thread pages (e.g. https://twitter.com/Twitter/status/1228330164804837377 ) and the homepage ( https://twitter.com/home ) has this problem, but it's easier to trigger on thread pages.

1. Open a Twitter page (thread or homepage, easier to trigger on thread pages)
2. Scroll down for tens of replies. Clicking "more replies" links seems to make the bug easier to trigger.
3. Page starts to scroll up till the top, one at a distance.

### Expected behavior
Page doesn't scroll unless user interaction.

### Actual behavior
Page would scroll up jumpy after sliding down for several pages and clicking to expand some replies.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
Nope.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Nope, over the past several years.

### Can you reproduce in Chrome (or other non-Mozilla browser)?
Nope.

### Device information

* Android device: Android 9, LineageOS 16.0
* Fenix version: Nightly 200218 18:00 (Build #20491808)

**Comment by outloudvi** [comment] 2020-02-19 08:55
Search on webcompat shows that the issue may be the same as mentioned at webcompat/web-bugs#47806. It seems to have been many duplicated reports there, so a priority is appreciated.

**Comment by kbrosnan** [comment] 2020-02-20 02:16
Dupe of BZ-1615562

**Closed by kbrosnan** 2020-02-20 02:16 UTC
Labels: needs:triage
