### ISSUE TITLE
[Bug] Launch links on private tab doesn't work with Chrome Custom Tabs

### ISSUE THREAD

**Issue by miladmaz12** [mozilla-mobile/fenix#5780] opened 2019-10-03 21:56 UTC
## Steps to reproduce

1. Click on a link to send to chrome custom tab (powered by Firefox Preview) from external app.
2. The link is shown in history on Firefox Preview.

### Device information

* Android device: Android Pie 9.0 OnePlus 3T
* Fenix version: Preview 2.1.0

**Comment by ekager** [comment] 2019-10-03 23:32
Closing as dupe of https://github.com/mozilla-mobile/fenix/issues/5592
This should be fixed in latest Nightly and will be in our next release

**Closed** 2019-10-03 23:32 UTC
Labels: 🐞 bug
