### ISSUE TITLE
FNX-12242 ⁃ collection and top sites sync to cloud

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11331] opened 2020-06-08 10:49 UTC
### What is the user problem or growth opportunity you want to see solved?
After fresh installation of fenix due to factory reset, rom change, phone change etc items saved to the collection and top sites are gone and are not restored after signing in. So please allow syncing of these items to cloud(firefox servers) so that these are restored after signing in. Maybe allow import and export of these items if not possible to sync to cloud. Building collection or top sites is hactic and users takes days to collect items in collection ...after reinstalling the app everything is lost which is frustrating

### How do you know that this problem exists today? Why is this important?
This is really important to sync the features else there is no point of collections or top sites.

### Who will benefit from it?
All users who uses these features

**Comment by cadeyrn** [comment] 2020-06-08 11:05
Sync collection: #6512 and #4424.
Sync top sites: #10583.

**Comment by kglazko** [comment] 2020-06-08 17:43
This is a duplicate of the ones caderyn linked with. Closing in favor of those.

**Closed** 2020-08-11 03:49 UTC
Labels: Feature:Collections, feature request 🌟
