### ISSUE TITLE
Import of VCard fails, I/O error reported

### ISSUE THREAD

**Issue by Trapfether** [mozilla-mobile/fenix#13514] opened 2020-08-12 00:58 UTC
When downloading and opening a vCard, the file is somehow changed in a way that Contacts no longer recognizes it and causes a failure. I have verified that the same exact file when opened directly from the phone's download folder imports as expected.

Open https://www.phpclasses.org/browse/file/5543.html and download the example vCard

When the notification appears, attempt to "Open" the vCard

The phone's usual contact import process should take over and import the vCard into contacts.

Instead, the contacts app displays an error saying the vCard cannot be imported, even though the same file can be imported from the devices "Downloads" folder

I am using

Google Pixel 1
Android 10 Build QP1A.191005.007.A3
I Am using Firefox for android 68.11.0

**Comment by liuche** [comment] 2020-08-15 00:49
I wonder if we need to support some kind of filetype on the AC side @Amejia481 for these kinds of downloads? What do we do for files that the Android system doesn't automatically support?

I tried opening the vCard from the Files app on my phone, and it opened in Google Drive (which couldn't open it) but suggested a different way of opening the file (which then triggered a Contacts permission).

Mostly I'm curious if there is an easy fix (like exposing a different filetype) so we can prioritize this against other downloads bugs.

**Comment by Amejia481** [comment] 2020-08-17 13:57
> I wonder if we need to support some kind of filetype on the AC side @Amejia481 for these kinds of downloads? What do we do for files that the Android system doesn't automatically support?
> 
> I tried opening the vCard from the Files app on my phone, and it opened in Google Drive (which couldn't open it) but suggested a different way of opening the file (which then triggered a Contacts permission).
> 
> Mostly I'm curious if there is an easy fix (like exposing a different filetype) so we can prioritize this against other downloads bugs.

We have to investigate to see what's happening, as we are creating [a generic intent using the content type provided as the download's metadata](https://github.com/mozilla-mobile/android-components/blob/51a2d65e0cf42d15687a512917a7c3ecc401a29e/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L213). As other apps, can open the file, it's very likely to be something that we missing in the intent creation. Assessing the issue should not be that intensive to find.

**Comment by Amejia481** [comment] 2021-02-01 20:47
Very likely to be fixed after https://github.com/mozilla-mobile/android-components/pull/9558 lands similar to https://github.com/mozilla-mobile/fenix/issues/17502

**Comment by ebalazs-sv** [comment] 2021-02-19 12:15
Verified as fixed on Nightly 2/19 GV 87 with Pixel 2 (Android 9).
The issue is still reproducible on Beta 86.0.0-beta.5 GV 86 from 2/15 and Release 86.1.0-rc.1 GV 86 from 2/16.
I will remove the qa:needed label and close this issue.

**Closed by ebalazs-sv** 2021-02-19 12:15 UTC
Labels: Feature:Download, S3, eng:qa:needed, 🐞 bug

**Comment by Amejia481** [comment] 2021-02-19 14:13
Thanks @ebalazs-sv
