### ISSUE TITLE
[Bug] No preview when swiping between tabs

### ISSUE THREAD

**Issue by SinTan1729** [mozilla-mobile/fenix#12873] opened 2020-07-23 21:16 UTC
## Steps to reproduce
1. Open at least two tabs
1. Swipe between them

### Expected behavior
Some kind of preview should be there while swiping.

### Actual behavior
No preview. Just a black placeholder until the swiping gesture is released.

### Device information
* Android device: Redmi K20 (Android 10)
* Fenix version: Nightly 200723 06:01

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3832)

**Comment by person808** [comment] 2020-07-23 22:01
Are these tabs you have just opened or tabs you have already visited before. To put it another way, when you open the tab tray, do these tabs have thumbnails or are they non-existent/blank? Currently we capture thumbnails on page load, so if you opened a new tab but you haven't actually viewed the page yet there is no thumbnail available. There is also some thumbnail related work in GeckoView that would help us capture thumbnails more often (https://github.com/mozilla-mobile/fenix/issues/12859#issuecomment-663122149). I suppose there is an argument to be made that we should show a placeholder if the thumbnail isn't available.

**Comment by jonalmeida** [comment] 2020-07-23 22:45
@person808 this definitely sounds like the same issue that #12859 suffers from as well. A temporary black background might suffice as a default for now.

**Comment by SinTan1729** [comment] 2020-07-24 06:04
@person808 I have visited those before and they do have thumbnails showing up in the tab switcher. Although another bug is that some pag s don't show thumbnails at all.

**Comment by ShatteredPixel** [comment] 2020-07-24 07:39
Perhaps this https://github.com/mozilla-mobile/fenix/issues/12642 is related. The transition between tabs gives a flash. May be that's why we we are not getting previews correctly

**Comment by Neikon** [comment] 2020-07-24 22:06
I have not preview too.
Oneplus 7
Android 10
Firefox nightly build of 24/07/2020
a little video to show how it looks @person808 
https://youtu.be/7zJn2nij2Ns

Note: twitter preview is blank in tab tray too

**Comment by person808** [comment] 2020-08-03 17:39
For twitter, it looks like the thumbnail we get is of the site's splash screen which is why the thumbnail appears blank. I tried reproducing @Neikon's video since it looks like the duckduckgo preview isn't showing when it should, but the preview shows for me. It could be possible that the thumbnail was deleted after loading mozilla.org, we don't see the tab tray after so I'm not sure.

**Comment by Neikon** [comment] 2020-08-03 21:46
I can record as many videos as you need @person808 . But swiping I never can see a thumbnail. https://youtu.be/_FvM6bA5atQ

In other hand, I hadn't noticed that duckduck's thumbnail sometimes disappears from the tab tray as well (it's not only duck, it's whatever web). I think It disappears when come to firefox after open another app but i can not reproduced when i want. I tried many times and I could record the bug in this video https://youtu.be/nRjnmP7q7zg
But in this other video https://youtu.be/5gHaERELg2s i do the same and It resist. I see sometimes it disappear when i go to android homescreen, stop the record , come back firefox.

I tried to open many apps to force android to close firefox, and thumbnails seems resist. the web reload but thumbnail is there.
Tell me if you need something more

Oneplus 7 (8GB RAM)
Android 10
Firefox nightly build of 03/08/2020

**Comment by person808** [comment] 2020-08-03 22:20
Thank you @Neikon! The videos are helpful. From video 1, it appears that something is up with the preview. If we see thumbnails in the tab tray, we should be able to load the preview for the gesture, but that is clearly not working. I'll keep an eye out and see if I can eventually reproduce this. Maybe @jonalmeida can take a look at the videos too and see if theres anything I'm missing?

**Comment by jonalmeida** [comment] 2020-08-03 22:32
Unfortunately, this issue is to the others reported that are related to thumbnails where the root cause is this GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1647797

**Comment by bifleming** [comment] 2020-08-24 21:28
Looks like both the GV bug and AC bug have been closed...

**Comment by Neikon** [comment] 2020-08-25 07:43
in today build does not work yet, but the twitter preview in the tab tray works now, it is improving but not complete.
https://youtu.be/hUUImKS0owI
NOTE: build number in video

**Comment by jonalmeida** [comment] 2020-08-25 12:07
Thanks for the video, thanks quite helpful!

@person808 I'm no longer certain this is a thumbnail issue. In the video above, we can see that we have the thumbnail when switching tabs from the tabs tray, so the gesture navigation should be able to those thumbnails.

**Comment by person808** [comment] 2020-08-25 14:56
Hm I can't seem to reproduce at all. All `TabPreview` does is call `loadIntoView` so my best guess is that is failing somehow.

**Comment by AndiAJ** [comment] 2020-08-26 12:43
Hi, **verified as fixed** on the latest **`Nightly Build 200826`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200826-153607](https://user-images.githubusercontent.com/51314259/91304742-a82df300-e7b2-11ea-86e8-02ce1ed9d250.gif)

**Comment by Neikon** [comment] 2020-08-26 13:29
It still doesn't work for me, Should i do something?
https://youtu.be/9CU_vmNK_2k
Oneplus 7, android 10

**Comment by SinTan1729** [comment] 2020-08-26 13:35
It's still happening for me. On the 200826 build.
[Here's a screen recording.](https://streamable.com/0dhj4g)

**Comment by AndiAJ** [comment] 2020-08-26 13:37
In this case I'll re-open it.
@SinTan1729 what device are you using? ☺️

**Comment by SinTan1729** [comment] 2020-08-26 13:40
I'm using a Redmi K20 (Android 10).

**Comment by abodea** [comment] 2020-09-04 09:03
Hi, **verified as fixed** on the latest **`Nightly Build 200904`** using the following devices:
• Google Pixel 4 XL (Android 11)
• Samsung Galaxy S10+ (Android 10)

![20200904-115021](https://user-images.githubusercontent.com/42831109/92221658-77327a00-eea6-11ea-85ad-740e3fd8a8f0.gif)

@SinTan1729 can you please re-check this on the latest Nightly version?
Removing `eng:qa:needed` until further notice, if @SinTan1729 cannot reproduce this issue, I will close it.

**Comment by SinTan1729** [comment] 2020-09-04 09:27
Unfortunately, it's still happening for me.
[Screen recording.](https://streamable.com/xw9nhu)

**Comment by Neikon** [comment] 2020-09-04 10:03
it doesn't work yet 
https://youtu.be/pghtYfjeBwM
Oneplus 7, android 10

**Comment by AndiAJ** [comment] 2020-09-07 07:17
Reproducible on the latest **`Nightly Build 200907`** using a Google Pixel 3a (Android 10)  while in landscape view.

**Comment by jonalmeida** [comment] 2020-09-09 23:07
> Reproducible on the latest **`Nightly Build 200907`** using a Google Pixel 3a (Android 10)  while in landscape view.
> 

Oh hey, that's a cool find! When I rotate the phone into landscape and back the bug is easily reproducibly on my Pixel 4 with Nightly 200908 06:01.

**Comment by boek** [comment] 2020-09-22 20:31
@jonalmeida any idea what could be causing this or who should I talk to about debugging it? :)

**Comment by jonalmeida** [comment] 2020-09-22 20:35
@boek I think this related to the swipe gesture layout. As AndiAJ noticed, the swipe gesture doesn't see to be able to load the thumbnail after rotating the phone, so I wonder if it's because of some conflict in the dimensions the swipe gesture layout desires (landscape) from the thumbnail which is a portrait.

**Comment by Neikon** [comment] 2021-02-02 11:13
this bug still happens to me 😥

**Comment by SinTan1729** [comment] 2021-07-21 07:46
It's still happening to me. On my OnePlus Nord CE 5G (Android 11).

**Comment by csadilek** [comment] 2022-12-22 19:44
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807078

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2022-12-22 19:44 UTC
Labels: 🐞 bug, b:landscape, Feature:Gesture, pin
