### ISSUE TITLE
FNX-5588 ⁃ [Bug] Snackbar missing for deleting bookmark from edit view

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#2316] opened 2019-05-07 11:23 UTC
## Steps to reproduce
Go to edit view of a bookmark, tap on delete icon in upper right corner

### Expected behavior
See a Snackbar ("Deleted URL" UNDO) 

### Actual behavior
No Snackbar

# Updated for QA (by Sawyer)
## Steps to reproduce
Go to edit view of a bookmark, tap on delete icon in upper right corner

### Expected behavior
See a confirmation dialog asking if the user wants to delete the bookmark. Pressing "delete" deletes the bookmark, pressing cancel dismisses the dialog.

### Actual behavior
No confirmation dialog

**Comment by harshit181** [comment] 2019-05-09 08:03
Queries on expected behavior 
Possible scenarios 
1. After pressing delete ,we go back to previous screen(can be webpage or bookmark/library  screen) ,show undo snackbar ,after pressing undo we come back to individual bookmark edit screen
2. After pressing delete ,we go back to previous screen ,show undo snackbar ,after pressing undo we remain at the previous screen (can be webpage or bookmark/library  screen)
3. After pressing delete ,we always go back to library bookmark screen ,show undo snackbar ,after pressing undo we come back to individual bookmark edit screen
4. After pressing delete ,we always go back to library  bookmark screen ,show undo snackbar ,after pressing undo we remain at the bookmark/library screen

**Comment by sblatz** [comment] 2019-05-30 20:47
@topotropic Is a confirmation dialog (similar to the one used for collections) sufficient? This view is a modal so a snackbar feels a bit weird here.

**Comment by topotropic** [comment] 2019-06-04 07:47
Let's follow above described scenario 2 and use a snackbar.
 "After pressing delete ,we go back to previous screen ,show undo snackbar ,after pressing undo we remain at the previous screen (can be webpage or bookmark/library screen)" . Thanks, @harshit181!

**Comment by sblatz** [comment] 2019-06-04 19:42
Implementing this with a snackbar is quite complex since they are two different views and will require lots more engineering effort. 

Can we make this a post MVP ticket and just do a confirmation dialog for now? 

@vesta0

**Comment by vesta0** [comment] 2019-06-04 21:26
@sblatz yes I agree with your suggestions and we have already taken this approach elsewhere in the app.

**Comment by softvision-miralobontiu** [comment] 2019-06-05 09:05
After tapping on "Delete" icon from the upper right corner, a pop-up message is displayed as is shown in the attached GIF. After allowing deletion, the page is displayed again, but no "Undo" snakcbar is displayed.
I will close the issue as verified, considering this behavior is expected.

![2019_06_05](https://user-images.githubusercontent.com/40694158/58944157-e5f7c380-8789-11e9-9d0d-a3d28c1d5f75.gif)

**Closed** 2020-08-11 14:46 UTC
Labels: Feature:History, Release Blocker, eng:qa:verified, good first issue, 🐞 bug
