### ISSUE TITLE
FNX-5072 ⁃ Selecting Bookmark folder in edit mode takes too many steps

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1514] opened 2019-04-10 05:19 UTC
## Steps to reproduce
1. Swipe up on a page
1. tap Bookmark icon
1. tap edit in the snackbar that appears
1. tap the bookmark folder icon
1. tap any folder

### Expected behavior
The bookmark is selected and  the user is moved back to the edit bookmark screen with the bookmark name, URL and selected folder shown. 

### Actual behavior
After tapping on a folder, a checkbox appears, indicating it is selected. If the user wants to "accept" this selection, they must tap back in the UI or in the Android back button.

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1915 build id 10991207

**Comment by kbrosnan** [comment] 2019-04-16 22:34
Using the menu button is a little shorter. 

1. Menu
2. Library
3. Bookmarks
4. Tap folder

**Comment by kbrosnan** [comment] 2019-04-27 03:08
Closing as a dupe of #1487 which is very similar.

**Comment by yoasif** [comment] 2019-04-27 03:23
@kbrosnan This is about editing a bookmark folder, not loading a bookmark. I don't think the use case or action is *that* similar that it is a dupe.

**Closed** 2020-08-11 11:53 UTC
Labels: Feature:Bookmarks, needs:UX-feedback
