### ISSUE TITLE
[Bug] Sites with PWAs showing "Add to home screen" instead of "Install" on Samsung S8 and N9

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#9692] opened 2020-04-03 20:25 UTC
## Steps to reproduce
* Using a Galaxy S8 [SM-G950U1] or Galaxy Note 9 [SM-N960U1] visit 
* app.starbucks.com
* 9gag.com
* trivago.com
* pinterest.com
* twitter.com
* tap on the 3 dot menu
* look for `Install` option

### Expected behavior
* Install option present

### Actual behavior
* Add to home screen offered

### Device information

* Android device: See above
* Fenix version: 4.2.1

**Comment by sblatz** [comment] 2020-04-07 17:42
After discussing this in triage, it seems like what's happening is the language is wrong but it's properly installing the PWA (at least on twitter with Galaxy S9). 

Let's investigate why it's intermittently showing the wrong text (sometimes we're seeing install, sometimes "add to homescreen" even on the same device & site after a refresh)

**Comment by sblatz** [comment] 2020-04-07 17:43
@rocketsroger may have some more insights here but we can discuss during AC triage.

**Comment by ekager** [comment] 2020-04-09 23:34
I figured out what is happening here and it's a Fenix bug:
The "label" of the menu item either reads "Add to homescreen" or "Install" based on if it's a PWA. 

It will only read as "Install" if this item is hightlighted.
https://github.com/mozilla-mobile/fenix/blob/177baf58a868cafcdafeb8de716d617c1edf9aae/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt#L140-L142

But it will only be highlighted if this is true. But `installPwaOpened` is only true the first time a user sees an "install-able" page.

https://github.com/mozilla-mobile/fenix/blob/177baf58a868cafcdafeb8de716d617c1edf9aae/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt#L264-L268

This was a fairly recent regression added in PR #8805 for #8800

**Comment by serovar** [comment] 2020-04-11 15:05
I don't know if it is related, but on my Pixel 2 XL feedbin.com shows "Add to home screen" instead of "Install" even if you can install it as a PWA with Chrome.

**Comment by ekager** [comment] 2020-04-13 17:10
@serovar definitely related! The fix I just landed should be in the next Nightly, but for now if you click "Add to homescreen" for an installable PWA will still install it as a PWA. :)

**Comment by serovar** [comment] 2020-04-13 17:17
Maybe it is not related then, since if I tap it, it adds a shortcut on my home screen, that simply opens a new tab on Fenix (while it opens properly borderless if I add it to the home screen with Chrome). I will open a new issue when I have the time, thanks for clarifying :)

**Comment by ekager** [comment] 2020-04-13 17:19
@serovar yes if you could open a new issue with what app you're trying to install that would be great. Thanks!

**Comment by AndiAJ** [comment] 2020-04-14 09:13
Hi @ekager , I've just checked on **`Fenix beta 4.3.0-beta.1 (Build #21050021)`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

❌ - "Add to home screen" is still displayed over the "Install" button
❌ - It adds after the second attempt a shortcut (opened a while ago [#9049](https://github.com/mozilla-mobile/fenix/issues/9049) )

► Video
![20200414-120456](https://user-images.githubusercontent.com/51314259/79207318-409d8980-7e49-11ea-9d77-c56106000d24.gif)

**Closed** 2020-04-14 10:26 UTC
Labels: Feature:PWA, P2, eng:qa:verified, needs:investigation, 🐞 bug
