### ISSUE TITLE
FNX-4511 ⁃ [Bug]Tab Tray: The "Collections" section shouldn't be displayed on the home screen if no tabs are open

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10733] opened 2020-05-18 10:24 UTC
## Prerequisites
Don't have any open tabs

## Steps to reproduce
1. Check the Home screen

### Expected behavior
As per #8766 the  "Collections" section shouldn't be displayed

### Actual behavior
The "Collections" section is displayed even if no tabs are open

### Device information
* Android device:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build #200518 from 5/18

### Notes
► Screenshot
![rsz](https://user-images.githubusercontent.com/51314259/82202616-d7f37200-990a-11ea-9fa7-183a3cc0632b.png)UNITO-UNDERSCORE!screenshot!UNITO-UNDERSCORE!20200518-131951!

**Comment by liuche** [comment] 2020-06-04 17:27
Dupe of some collections bug, should be fixed.

**Comment by AndiAJ** [comment] 2020-06-05 06:53
Hi @liuche , I've just checked this matter on the latest **`Nightly Build 200605 from 6/5`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

**The collections section is displayed on the home screen even if there are no open tabs.**

Perhaps @topotropic could advise? ☺️ 

I'll remove the QA needed until further notice.

**Comment by liuche** [comment] 2020-06-09 15:50
Hi @AndiAJ, actually this is the expected behavior for the Tabs Tray! Could you update the testrail cases for this? For tabs tray, we want to show the collections hint even if there are no tabs open.

**Comment by AndiAJ** [comment] 2020-06-09 15:51
Hi @liuche , sure thing, thanks for clarifying this! ☺️

**Closed** 2020-08-11 01:34 UTC
Labels: Feature:Collections, Feature:Tabs, S2, Skittle, 🐞 bug
