### ISSUE TITLE
Change tab by swiping over the address bar

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#8884] opened 2020-03-01 02:22 UTC
### Why/User Benefit/User Problem
It's a fast and intuitive method to switch tabs. We all know it and love it from Chrome but why should it be an exclusive feature for Chrome? I'd love to at last see this convenient way to switch tabs in another browser.
In comparison, the standard way to switch tabs takes 2-4 touches.
1. Tap the tabs icon
2. (Swipe to scroll in case current tab and the one above/below are not on screen. I can't figure out the system where the view is located entering the tabs overview, it doesn't seem consistent to me.)
3. (Touch the screen to stop the smooth auto scrolling)
4. Tap the desired tab
### What/Requirements
Make it possible to switch to the left/right tab by swiping over the address bar on the opposite direction actually. (When you want to change to the right tab, you pull the current tab to the left using the address bar.)
### Acceptance Criteria (how do I know when I’m done?)
You can swipe over the address bar to change to the left/right tab.

**Comment by Osyotr** [comment] 2020-03-01 12:16
Also "swipe down to show tabs" would be a nice feature to copy from chrome

**Comment by cadeyrn** [comment] 2020-03-01 13:15
Duplicate of #3481.

**Comment by topotropic** [comment] 2020-03-10 22:17
Thanks for the feedback, I'll close it since it's a dupe, see above comment.

**Closed by topotropic** 2020-03-10 22:17 UTC
Labels: needs:triage, 🌟 feature request
