### ISSUE TITLE
[Bug]: Sharing image results in File format not supported.

### ISSUE THREAD

**Issue by tomyummmm** [mozilla-mobile/fenix#21329] opened 2021-09-16 11:09 UTC
### Steps to reproduce

1. Share image using "share image" option. 
2. Select Whatsapp, choose contact through list, or direct share to contact.
3. File format not supported.
4. Share image, select Telegram, choose contact.

### Expected behaviour

Photo should be shared directly into messaging application of choice.

### Actual behaviour

Whatsapp: File format not supported
Telegram gives no error message, it just opens the chat, no image or link.

I tested this with the firefox Nightly 94.0a1 (Build #2015834283) as well, same issues.

Was advised to start a new issue by @mduchev in #12414. Possible duplicate of #19171

### Device name

Xiaomi K20 Pro / 9T Pro

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.2 (Build #2015833763)

### Additional information

https://user-images.githubusercontent.com/65211592/133601080-94a7f7da-7718-47a6-ac16-243238a5df40.mp4

**Comment by amedyne** [comment] 2021-09-20 21:20
@tomyummmm Can you share the link for the image that you are trying to share so we can investigate further?

**Comment by tomyummmm** [comment] 2021-09-21 00:04
> @tomyummmm Can you share the link for the image that you are trying to share so we can investigate further?

It happens with any photo. I just used this one from the other issue for convenience. https://upload.wikimedia.org/wikipedia/commons/a/a5/Caracal001.jpg

**Comment by SoftVision-LorandJanos** [comment] 2021-09-21 06:12
Hi @tomyummmm ! Thank you for your report!
I couldn't reproduce the issue you described.
The pictures I try to share are sent without any issue, including the same picture from your example.
Could you see if it still reproduces if you clear your data? 
I've tested on the latest Nightly (94.0a1 - 2021-09-21) and latest Beta (93.0.0beta4).
Devices used:
- Huawei P30 (Android 10).
- Xiaomi Mi11 Lite (Andoird 11).

**Comment by tomyummmm** [comment] 2021-09-23 01:45
Hi @SoftVision-LorandJanos, I have cleared my data and also tried reinstalling both the beta and nightly, both still have the same issue. Perhaps this is a problem of the custom Android ROM i have installed.

I tested with firefox beta on the Samsung Galaxy S20 and it worked fine.

Is there a way to log/debug this issue and see what is happening?

**Comment by SoftVision-LorandJanos** [comment] 2021-09-23 15:02
I believe your issue will be fixed once the ticket will be fixed you mentioned as being possibly a duplicate of.

**Comment by SoftVision-LorandJanos** [comment] 2022-03-28 08:55
As the fix will be done in #19171, I will close this ticket as a duplicate.

**Closed by SoftVision-LorandJanos** 2022-03-28 08:55 UTC
Labels: 🐞 bug, Feature:Media, S3, needs:triage, wontfix, qa-triaged
