### ISSUE TITLE
[Bug]:  unable to save or view created avatar on charat.me

### ISSUE THREAD

**Issue by a-gyaanapan** [mozilla-mobile/fenix#21427] opened 2021-09-22 04:40 UTC
### Steps to reproduce

* https://charat.me/en/origin/create/ (by default loading mobile version?)
* finish (on the image top right corner)
* shows box with pixels

### Expected behaviour

show image

### Actual behaviour

image not visible

### Android version

9

### Firefox release type

Firefox

### Firefox version

92.1.1 (Build #2921100) AC: 92.0.15, e00bef534d GV: 92.0-20210914214157 AS: 82.1.0

## OTHER
* no upload or button
* the above issues are reproducible on desktop version also

**Comment by SoftVision-LorandJanos** [comment] 2021-09-22 13:32
Hi @a-gyaanapan ! Thank you for your report.
I couldn't reproduce the issue you reported, the image is visible after tapping on "FINISH" (See video below. Please tell me if I didn't do something right).
Could you see if it reproduces on the latest Nightly? Or if you can clear your data, if it reproduces after that? Thank you!

Firefox versions tested:
- RC (92.1.1)
- Nightly (94.0a1 - 2021-09-22).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Mi11 Lite (Android 11).

https://user-images.githubusercontent.com/48829350/134352820-3a7548b1-8688-445e-9f03-9687f3feffad.mp4

**Comment by a-gyaanapan** [comment] 2021-09-22 15:19
@SoftVision-LorandJanos its strange, excuse for the noise.

i am using mull (version in op is copied from "about mull" browser) perhaps i should report there?

**Comment by SoftVision-LorandJanos** [comment] 2021-09-23 14:56
@a-gyaanapan , don't worry about it.
Yes, try reporting it there.

**Comment by SoftVision-LorandJanos** [comment] 2022-03-23 13:23
Based on the latest comments, I will close this ticket.

**Closed by SoftVision-LorandJanos** 2022-03-23 13:23 UTC
Labels: 🐞 bug, S3, Feature:Browsing, needs:triage, wontfix, qa-triaged
