### ISSUE TITLE
[Bug] Unnecessary vertical scroll on the current homescreen

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#14287] opened 2020-08-27 12:10 UTC
## Steps to reproduce
Add 8 Top Sites to Firefox
Create 5 collections, but do not expand them on the homescreen
Go to the homescreen

### Expected behavior
On a phone with a large screen, like Redmi Note 7, the Top Sites and Collections headers fit well in one screen, so vertical scroll in that configuration should not be possible

### Actual behavior
It is possible to scroll all the same, as shown in the shots below (sorry, right is before scrolling, left is after scrolling)
![image](https://user-images.githubusercontent.com/218971/91440217-8b56f580-e86e-11ea-9541-3b6eef352540.png)

On a sidenote, this makes the horizontal swiping of Top Site slides rather difficult, because it is on the top part of the screen and horizontal scroll is not easy and is often turned into vertical scroll ;)

### Device information
Redmi Note 7

* Android device: ?
* Fenix version:  #2015760371

**Comment by s-ankur** [comment] 2020-08-27 14:39
Duplicate of #8545

**Comment by Diana-Rus** [comment] 2020-09-07 13:49
Thank you @s-ankur , closing this @klint  please follow #8545 for further progress.

**Closed by Diana-Rus** 2020-09-07 13:49 UTC
Labels: needs:triage, 🐞 bug
