### ISSUE TITLE
Unable to switch between tabs with 'find in page' on

### ISSUE THREAD

**Issue by pleiozc** [mozilla-mobile/fenix#18734] opened 2021-03-31 19:57 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
When I search for keywords on various pages I can't switch between tabs with 'find in page' on (because it locks access to toolbar) and you have to use it individually per page basis. 

Or maybe is it an intended behavior? If so wouldn't be better not to lock it up and allow switching between tabs with keywords preserved for quicker access?

![toolbar](https://user-images.githubusercontent.com/79718929/113202859-ac872680-9241-11eb-8569-12d43df69ee0.png)

### Expected behavior
Being able to switch between tabs with 'find in page' on
### Actual behavior
Unable to switch between tabs with 'find in page' on
### Device information

* Firefox for Android version: **86.1.1**

**Comment by sflorean** [comment] 2021-04-01 07:04
@pleiozc thanks for reporting this! #9165 is already filed and your scenario will be tested when the issue is fixed.
Closing as duplicate!

**Closed by sflorean** 2021-04-01 07:04 UTC
Labels: needs:triage, 🐞 bug
