### ISSUE TITLE
[Bug] The selected tab is not displayed in Recently closed tabs list when closing all the opened tabs from Tabs tray, one by one

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#17461] opened 2021-01-14 13:06 UTC
## Steps to reproduce
1. Launch Fenix;
2. Open 2 or more tabs;
3. Go to Tabs tray and close all the tabs one by one;
4. Go to History -> Recently closed tabs;
5. Observe the Recently closed tabs list;
### Expected behavior
All the closed tabs are displayed in the Recently closed tabs list.
### Actual behavior
The selected tab is not displayed in Recently closed tabs list when closing all the opened tabs from Tabs tray, one by one.
Also the Recently closed tabs tabs counter is not updated before opening the list.

![20210114_144244](https://user-images.githubusercontent.com/48799384/104594278-9d98cb00-5679-11eb-91aa-14ae316f465a.gif)

### Device information

* Android device: Samsung Galaxy Tab S3 (Android 8)
* Fenix version: Nightly 1/14
* Not reproducible on Beta 1/12 and Release 1/7

**Comment by mcarare** [comment] 2021-01-14 16:23
Duplicate of https://github.com/mozilla-mobile/fenix/issues/17462 ?

**Closed by mcarare** 2021-01-14 16:23 UTC
Labels: needs:triage, 🐞 bug
