### ISSUE TITLE
Sync Pinned Sites in Home Page across all devices

### ISSUE THREAD

**Issue by shockergit** [mozilla-mobile/fenix#20309] opened 2021-07-09 10:41 UTC
Please add an option to sync top sites across all devices. It's frustrating to manually add all pin sites when changing devices or reinstalling Firefox.

**Comment by cadeyrn** [comment] 2021-07-09 11:08
Duplicate of #10583.

**Comment by mcarare** [comment] 2021-07-09 12:14
@shockergit Thank you for your report! The feature you are requesting is tracked in #10583. Closing this as duplicate.

**Closed by mcarare** 2021-07-09 12:14 UTC
Labels: needs:triage
