### ISSUE TITLE
[Bug]: The wrong Favicon icon is displayed when first accessing de.wikipedia.org

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/fenix#20332] opened 2021-07-12 13:42 UTC
### Steps to reproduce

1. Access https://de.wikipedia.org/wiki/Internet_Go_Server
2. Add page to the browser's "Bookmarks" section
3. Access the browser's "History" section
4. Observe the result

### Expected behaviour

The correct Favicon is displayed

### Actual behaviour

The wrong Favicon is displayed

### Device name

Samsung A51

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

91.0a1

### Additional information

1. As reported first here: https://github.com/webcompat/web-bugs/issues/79886
2. The issue is not reproducible after the 2nd access of the page
3. The issue is reproducible when viewing the "Bookmark" tab
4. Screenshot attached:
1st access:
![Screenshot_7](https://user-images.githubusercontent.com/75027050/125297509-f64ad700-e32f-11eb-8ae8-51886d915046.png)
2nd access: 
![Screenshot_8](https://user-images.githubusercontent.com/75027050/125297543-fcd94e80-e32f-11eb-8ba8-34f3ed3dc2d2.png)
5. Works as expected using Chrome

**Comment by rocketsroger** [comment] 2021-07-26 17:42
A-C side change is merged.  The fix should show up in Fenix Nightly in couple days.

**Comment by rocketsroger** [comment] 2021-07-27 20:42
Fix should be in the next Nightly.  Please verify.  Thanks,

**Comment by softvision-raul-bucata** [comment] 2021-07-28 12:36
The issue is still reproducible on the latest build of Firefox Nightly:

![Screenshot_27](https://user-images.githubusercontent.com/75027050/127322994-f50de78c-e6d6-46a0-984e-670f267280fc.png)


Tested with:
Browser / Version: Firefox Nightly 92.0a1 (2015824587 -🦎92.0a1-20210726093430🦎)
Operating System: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)

**Comment by sflorean** [comment] 2021-07-28 16:24
Verified as fixed on Nightly 7/28 with Pixel 3 (Android 12). 
@softvision-raul-bucata please check again, with the build from July 28, I suspect that is still reproducible for you due to the fact that you checked on the build from 26. 
Thank you!

**Closed by sflorean** 2021-07-28 16:24 UTC
Labels: eng:qa:needed, 🐞 bug

**Comment by softvision-raul-bucata** [comment] 2021-07-29 08:54
I suspect that our test account does not receive the 7/28 build. Am I correct here? This is an up-to-date build on multiple devices:


![Screenshot_17](https://user-images.githubusercontent.com/75027050/127462639-46ebdfca-2416-4bc1-996a-c24c1d3a1bcb.png)
![Screenshot_18](https://user-images.githubusercontent.com/75027050/127462649-dafb585d-12bb-4446-a198-ff78224dad08.png)

**Comment by sflorean** [comment] 2021-07-29 09:53
@softvision-raul-bucata You have the build from 7/28, the issue is still reproducible? On previous attachment, the dates were from 7/26 and the fix wasn't landed. You can check the latest build here: https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.latest.

**Comment by softvision-raul-bucata** [comment] 2021-07-29 11:08
@sflorean With the above build from the Screenshot, the issue is still reproducible using other devices as well.

Samsung:
![Screenshot_13](https://user-images.githubusercontent.com/75027050/127481359-fd30c848-8e09-4536-891e-b0529c1ec138.png)


OnePlus:
![Screenshot_16](https://user-images.githubusercontent.com/75027050/127481384-fe9779fb-0982-4ff6-a762-5578d517da6d.png)




Tested with:
Browser / Version: Firefox Nightly 92.0a1 (2015824779 -🦎92.0a1-20210726093430🦎) 
Operating System: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
Operating System: OnePlus 6 (Android 11) - 1080 x 2280 pixels, 19:9 ratio (~402 ppi pixel density)

**Comment by sflorean** [comment] 2021-07-30 08:30
Strange, did you try with a clear data or do you have some additional steps?

**Comment by softvision-raul-bucata** [comment] 2021-07-30 08:38
Tested with version Firefox Nightly 92.0a1 (2015824971 -🦎92.0a1-20210728094336🦎) the issue is no longer reproducible, so I guess it was just a matter of deployment.
