### ISSUE TITLE
Tab non-restoration (quit behavior)

### ISSUE THREAD

**Issue by dbenjaminmiller** [mozilla-mobile/fenix#13360] opened 2020-08-06 19:30 UTC
Fennec has an option to not restore tabs on launch. When this option is enabled, if the user closes Fennec using the Android multitasking function, the tabs from that session won't be restored on the next launch.

Fenix includes a wipe on quit feature which can eliminate tabs, among other things, upon quit. But this only occurs when the user chooses quit from the menu. The user should have the option to have this occur when quitting via the Android multitasking system as well. Or perhaps that should be the default and this is a bug, since the user quitting via the Android method (the only type of "native quitting"), would expect the tabs not to be restored at next launch (as they currently are).

**Comment by s-ankur** [comment] 2020-08-06 19:59
duplicate of #9446  :/
Unfortunately github's search is bad for getting the exact issue that you want to find. You can 👍 that issue if you will find the feature useful.

**Comment by jakefleming156** [comment] 2020-08-07 17:54
Dupe of [#11449](https://github.com/mozilla-mobile/fenix/issues/11449). Closing issue.

**Closed by jakefleming156** 2020-08-07 17:54 UTC
Labels: needs:triage
