### ISSUE TITLE
Cannot add some pages to Android home screen

### ISSUE THREAD

**Issue by RalfJung** [mozilla-mobile/fenix#20612] opened 2021-08-01 09:37 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

There are some websites I access fairly regularly (e.g. to quickly check the weather); it would be great to be able to add them to the android launcher home screen. (Not sure what it is called in English. "Startbildschirm" in German.)

For many websites, this option exists: "Add to home screen" (or similar, "Zum Startbildschirm hinzufügen" in the German version). However, for some websites, instead the same menu item just says "Install", and that does something different. For example when I do this for the weather page I am interested in, it adds a link to `wetteronline.de`, but I want a link to the specific forecast for my city.

Looks like Firefox lets the page take away the option of adding a particular URL to the home screen. This is the opposite of "empowering users"; I'd expect Firefox to put me in control, not the website.

### How do you know that this problem exists today? Why is this important?

Seems like a basic feature for an Android browser to be able to add things to the home screen. :)

### Who will benefit from it?

People that want to quickly access pages.

**Comment by amedyne** [comment] 2021-08-02 19:02
Hi @RalfJung Firefox for Android currently has a feature that may answer to what you are looking for. You can add a URL to the homescreen by going to **Settings-> Add to TopSites**. Let me know if this works for you. thanks!

**Comment by RalfJung** [comment] 2021-08-03 08:46
Hm, I probably used the wrong term... "Add to top sites" adds this to the "new tab" page of Firefox. I want to add a link to my Android "home screen", the thing where one launches apps -- the thing that pops up when hitting the "circle" button. (My phone is set to German so I do not know which term is used for this screen in English Android.)

**Comment by amedyne** [comment] 2021-08-03 13:19
Got it! There is an option to "Add to Home Screen" in Firefox, too.  

![Screenshot_20210803-091637](https://user-images.githubusercontent.com/68711330/128022257-826539ce-a3c0-4e0c-9fae-9d971004c888.png)

**Comment by RalfJung** [comment] 2021-08-03 15:49
Yes, I've found that.

But for some websites, that option is not available. Instead, it just says "install".  You can see this for example at https://www.wetteronline.de/wetter/stuttgart. But "install" does something else -- it will add "wetteronline.de" to the home screen, instead of adding the page for the specific city I am interested in.

**Comment by klint** [comment] 2021-08-03 18:08
Hi. I had opened an issue for the same request already, that was closed.
https://github.com/mozilla-mobile/fenix/issues/7758

**Comment by eliserichards** [comment] 2021-08-03 20:20
"Add to homescreen" is basically adding a shortcut to your device's home screen, and "Install" is available when a site is a PWA. [This reply](https://github.com/mozilla-mobile/fenix/issues/7758#issuecomment-599347609) poses a good question, and it seems like you are proposing that we do show both options @RalfJung 😄 

I believe that we can do some tweaking to make the distinction between "add to home" and "install", maybe by changing the copy or having both options available.

**Comment by RalfJung** [comment] 2021-08-04 09:53
>  and it seems like you are proposing that we do show both options @RalfJung 

That might be one option, yes. Or maybe the popup window that appears when I click "install" could offer both the PWA-powered icon and a regular ol' link. Or maybe there are other ways to achieve this.

I don't know the best way to integrate this into the Firefox UI. I am just expressing that the current situation is frustrating for users since it feels like Firefox collaborating with these websites to prevent me from doing something that Firefox can very well do. I realize that is not the intention of the current behavior, but it's an unintended consequence. Firefox is usually great at putting the user in control even when that goes against the website's interest, so I figured you might want to hear about this issue. :)  (In this case I don't even think it's the website being malicious; I don't know if PWAs would support changing the landing page so that I can immediately open the weather forecast for the city I live in, but it seems like the weather service simply did not think about this case.)

**Comment by puppe** [comment] 2021-08-24 09:00
Issue #7758 has already been mentioned. There is also #15450 which seems to be about the same problem as well.

I also want to add another concrete example where this issue is detrimental to the UX. https://www.laarc.io/ offers a PWA, and thus cannot currently be added to home screen in the “normal” way but only as a PWA. My usual workflow for similar sites (e.g. https://lobste.rs) is to scroll down the home page and to open any interesting links in new tabs. I then close the home page and go through the tabs. With a PWA, this workflow is much more cumbersome. My only option is to share the link with Firefox. This is in itself already one click more than opening the link in a new tab, but it also switches immediately to the Firefox app. I then have to switch back to the PWA.

Maybe the site operator should not offer a PWA in the first place. It does not have any advantages over a simple shortcut in this case as far as I am concerned. Others may of course find the PWA useful or might even enjoy a more focused experience where they do *not* open several tabs. In any case, I wish Firefox would present PWAs as an additional option without taking the other option away.

As a workaround, I have created a shortcut with [HTTP Shortcuts](https://http-shortcuts.rmy.ch/).

**Comment by klint** [comment] 2021-09-14 07:27
This feature request could be a nice workaround for a long lasting bug affecting PWAs, where PWAs get stuck on a blank screen : #19157
Being able to use a device homescreen shortcut would be a usable alternative not affected by the above bug.

**Comment by klint** [comment] 2021-09-25 07:35
Similar request for that on reddit : https://www.reddit.com/r/firefox/comments/puyyup/disable_pwas_on_android/

**Comment by ruslanbay** [comment] 2021-11-12 13:56
I'm actively using both "Install" and "Add to Home screen" functionalities. But for security reasons I prefer the "Add to Home screen" + "Open links in a private tab" combination.

So for me the ideal solution will be to have both options available.

Please click below to see my phone's home screen:
<details>
  <summary>Click to expand</summary>
  ![screenshot](https://user-images.githubusercontent.com/67730802/141473420-d070cd7a-8aaa-4796-a497-e3d2e10eefff.jpg)
  
  ![Screenshot_1](https://user-images.githubusercontent.com/67730802/141476376-98873eb2-58e4-41f4-b6e4-6f0ca8a3280f.jpg)
</details>

Right now if I want to create a shortcut for a PWA site then I have to: 
1. copy the URL
2. switch my phone to Airplane Mode
3. open a new tab in Firefox
4. past URL from step 1 and press Enter
5. click "Menu" -> "Add to Home screen"

It's already too many steps, but as a result I get a shortcut with default ugly looking icon.

<details>
  <summary>Click to expand</summary>
  ![Screenshot_2](https://user-images.githubusercontent.com/67730802/141476388-d9b005f3-9e4c-492f-8795-0e96d78b08fa.jpg)
</details>

**Comment by klint** [comment] 2021-11-12 14:48
Thanks for the hint about airplane! But yes, we really need both options natively! 😊

**Comment by davidmegginson** [comment] 2021-11-19 13:15
Great hack with airplane mode, @ruslanbay ! It's not a good U/X, but at least it makes it _possible_ to avoid the buggy PWA implementation. And since I use Nova Launcher instead of the default, I'm able to fix the icon afterwards.

**Comment by davidmegginson** [comment] 2021-11-19 13:17
My other use case is to be able to save a deep link to the home screen, rather than being stuck at the top level of a PWA: for example, link directly to "latest posts" for a discussion forum.

**Comment by klint** [comment] 2021-11-19 13:52
Use cases are piling up! :) 
I hope this will be implemented soon. From what I recall, the code is ready to have both options, it's just a decision matter.

**Comment by kbrosnan** [comment] 2021-11-23 22:12
Closing as a duplicate of #15450

**Closed by kbrosnan** 2021-11-23 22:12 UTC
Labels: feature request 🌟, Feature:Shortcuts, Feature:PWA
