### ISSUE TITLE
FNX3-16356 ⁃ [Bug] Pressing the "Tabs" button, then pressing back closes the app

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#2484] opened 2019-05-14 20:30 UTC
## Steps to reproduce
1. Open a tab.
1. Press the tabs counter.
1. Press back.

### Expected behavior
I return to the currently selected tab (as happens e.g. in Fennec and in Chrome).

### Actual behavior
The app goes into the background (though thankfully at least it remains in memory).

### Device information
* Android device: Moto G4 Play
* Fenix version: 1.0.1920 (#11341807)

**Comment by ekager** [comment] 2019-05-14 21:01
This is intentional - see history in https://github.com/mozilla-mobile/fenix/issues/1012

**Comment by yoasif** [comment] 2019-05-14 21:10
I have been burned by this many times -- it feels totally intuitive. 

My thought process here is: 

1. I want to switch to another tab 
2. I tap the tab switcher 
3. I decide against it
4. I tap back.

I then end up basically exiting the app. 

It'd be one thing if #1827 was implemented - at least that way, the user has an easy way back to the tab that they were originally on. Today, the user has to scroll through a list of tabs to find the one they were on.

**Comment by buttercookie42** [comment] 2019-05-14 21:23
Even if the nice diagram in https://github.com/mozilla-mobile/fenix/issues/1012#issuecomment-479608509 declares the home/tabs view to be the "root" of the app, in practice I (and probably everybody else, too?) will spend the vast majority actually browsing in a tab, which is why I think that the latter feels more naturally as the root/main view of the app.

**Comment by djc** [comment] 2019-05-16 08:00
Coming from Fennec, I also found this deeply counterintuitive.

I checked out the comment from #1012 but the model there really doesn't match my expectations. To me, the primary activity in a browser is a content view of a tab. The tab switcher feels like a "modal" dialog that helps me navigate between tabs (which are essentially a horizontal space).

**Comment by vesta0** [comment] 2019-05-29 18:52
Closing this as it works as intended but based on the great feedback we are going to user test it and re-evaluate.

**Comment by djc** [comment] 2019-05-30 12:05
@vesta0 thanks for reconsidering! Would still be nice to keep this open (or open a new feature issue) so interested folks can get feedback after your re-evaluation?

**Comment by Poopooracoocoo** [comment] 2019-12-21 06:40
aww :( so sad that this is intentional. Using Fenix just feels harder than Fennec or a Chromium based browser

**Comment by Poopooracoocoo** [comment] 2020-03-25 04:34
This is still so annoying. It just doesn't feel right.

**Closed** 2020-08-14 16:59 UTC
