### ISSUE TITLE
[Bug] Smart Keywords are not synced from Firefox desktop

### ISSUE THREAD

**Issue by ANSI-C** [mozilla-mobile/fenix#17487] opened 2021-01-15 14:21 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
define a Smart Keyword in Firefox desktop, example: "wp" for search inside Wikipedia
### Expected behavior
you should be able to type "wp" and then the search terms and be brought directly to the search results inside Wikipedia site
if you don't know this feature look at this example:
https://support.mozilla.org/en-US/kb/how-search-from-address-bar

### Actual behavior
default search engine will be used

### Device information

* Android device: yes
* Fenix version: latest mainline: Firefox Daylight 84.1.4

**Comment by cadeyrn** [comment] 2021-01-15 14:50
Duplicate of #14337, please note https://github.com/mozilla-mobile/fenix/issues/12099#issuecomment-736911627.

**Comment by kbrosnan** [comment] 2021-01-19 19:30
Closing as a duplicate

**Closed by kbrosnan** 2021-01-19 19:30 UTC
Labels: 🐞 bug
