### ISSUE TITLE
FNX-4739 ⁃ Crash when accessing about:config on certain devices

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1034] opened 2019-03-15 10:33 UTC
## Steps to reproduce
1. Open Fenix
1. Go to about:config.

### Expected behavior
about:config opens.

### Actual behavior
App crashes.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9)
* Fenix version: 1.0.1911 (#10731207)
* [Logcat](https://github.com/mozilla-mobile/fenix/files/2970529/log.txt)

### Notes
* This does not reproduce on other devices (Nexus 5, Galaxy S8, Pixel)

**Comment by cpeterso** [comment] 2019-03-27 19:03
I wonder if this bug is related to GV parent process [bug 1527778](https://bugzilla.mozilla.org/show_bug.cgi?id=1527778). That GV bug will be fixed in next Tuesday's GV 67 Beta build. I know about:config works in GeckoView 68 in Firefox for Fire TV.

**Comment by cpeterso** [comment] 2019-03-28 06:54
On my Moto g5, `about:config` crashes the RB but not Fenix. RB uses GV 68 Nightly. Fenix currently uses GV 67 Beta, but I think it still used GV 68 Nightly when this bug was filed on March 15. This crash might be a regression in GV 68.

**Comment by bsurd** [comment] 2019-04-03 11:16
This seems to be constantly reproducible on the Note 8 even with older builds. Didn't manage to reproduce with other devices.

**Comment by kbrosnan** [comment] 2019-04-27 18:07
Tested with a Galaxy Note 8 SM-N950N and Galaxy Note 9 SM-N960N and I was not able to reproduce. @bsurd is this still a problem with a recent build?

**Comment by bsurd** [comment] 2019-05-06 07:28
Still managing to reproduce this on the Note 8 (SM-N950F).

**Closed** 2020-08-11 00:30 UTC
Labels: P2, b:crash, needs:gv, 🐞 bug
