### ISSUE TITLE
[Bug] Selection outline for tab tray is changed only after the "Tab closed" snack bar is dismissed

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#10564] opened 2020-05-11 14:12 UTC
### Prerequisites
Make sure that you have multiple tabs opened.

## Steps to reproduce
1. Go to the home screen of the app;
1. Close the last selected tab;
1. Observe the newly selected tab.

### Expected behavior
The selection outline is displayed over the new tab.

### Actual behavior
The selection outline is displayed over the new tab only after the "Tab closed" snack bar is dismissed.

### Device information
Android device:

* Google Pixel 3 (Android 10);
* Samsung Galaxy Note 8 (Android 9);
* LG G7 fit (Android 8.1).

Fenix version:

* Firefox Preview Nightly 5/11 #21320625.

![20200511](https://user-images.githubusercontent.com/40264165/81571290-67000780-93aa-11ea-8056-39f5b21beb69.gif)UNITO-UNDERSCORE!170757!

**Comment by ekager** [comment] 2020-05-12 04:33
This is because we aren't _actually_ removing the tab until the undo snackbar has disappeared. We could possibly try to select the next tab and then un-select it if undo is called, but could get a bit messy.

**Comment by topotropic** [comment] 2020-07-08 09:21
@sv-sdeiac I just tried it out and had the impression that it's way better with the dedicated tab tray. Is this still an issue for you? Thanks!

**Comment by ebalazs-sv** [comment] 2021-02-16 12:28
This issue is not reproducible on the latest Nightly 2/16 with Motorola Moto G6 (Android 8).
With the Tabs Tray, when a tab is closed, the next opened tab is selected before the "Tab closed" snack bar is dismissed.
I will close this issue.

**Closed by ebalazs-sv** 2021-02-16 12:28 UTC
Labels: Feature:HomeScreen, Feature:Tabs, S2, eng:ready, 🐞 bug
