### ISSUE TITLE
[Bug] Firefox 79.05 Android - Airmouse Click and Hold mark text instead of scrolling screen.

### ISSUE THREAD

**Issue by Bogged** [mozilla-mobile/fenix#14391] opened 2020-08-28 20:43 UTC
## Steps to reproduce
 Update from previous version

### Expected behavior
AirMouse Click and hold to move screen (drag)

### Actual behavior
Highliting Text

### Device information
Android TV box MINIX U22-XJ, Android 9.
It took a long time to address the very same issue in the previous major Firefox version change. Back to square one.

* Android device: ?
* Fenix version: ?

**Comment by kbrosnan** [comment] 2020-08-28 20:45
Behavior is a duplicate of #3708

**Closed by kbrosnan** 2020-08-28 20:45 UTC
Labels: needs:triage, 🐞 bug
