### ISSUE TITLE
[Bug]: The sync card is blank when signing in with Open tabs off.

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#26409] opened 2022-08-10 13:42 UTC
### Steps to reproduce

1. On a mobile device login in with a Firefox account and open a few tabs;
2. Go to Settings->Account settings and turn of Open tabs;
3. On a second device login with the same account and observe the homepage;

### Expected behaviour

The sync card should not be displayed.

### Actual behaviour

The sync card is blank when signing in with Open tabs off.

### Device name

Samsung Galaxy S22 Ultra

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1 2022-08-10

### Additional information

![SmartSelect_20220810-163555_Firefox Nightly](https://user-images.githubusercontent.com/50983519/183916190-3dc5e102-21e5-49fa-b2c2-7273793a4a9a.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21254)

**Comment by MatthewTighe** [comment] 2022-08-11 23:27
I believe this may be a duplicate of https://github.com/mozilla-mobile/fenix/issues/26150

**Comment by SoftVision-LorandJanos** [comment] 2022-08-24 10:52
As this ticket is covered in the above mentioned one, I will close this one as duplicate.

**Closed by SoftVision-LorandJanos** 2022-08-24 10:52 UTC
Labels: 🐞 bug, needs:triage, Feature:SyncTabs, Feature:RecentTabs, TaskContinuity
