### ISSUE TITLE
[Bug] Show Desktop Site is not working the other way.

### ISSUE THREAD

**Issue by Devanshu19** [mozilla-mobile/fenix#18748] opened 2021-04-01 12:45 UTC
There are some websites which have the issue with show desktop site feature.

As seen in the video linked below, The website was easily switched to the **Desktop Mode** but its not coming back to the original **Mobile Mode**.

**Video**:
https://user-images.githubusercontent.com/66104268/113294630-df4e1f00-9314-11eb-9ec3-128be298c9cc.mp4

https://user-images.githubusercontent.com/66104268/113296544-3c4ad480-9317-11eb-9d9e-70e3f4e5c2fb.mp4

**Expected Behaviour**
Should be switching between Desktop and Mobile

**Current Behaviour**
In some websites, once switched to desktop mode, it doesn't let us go back to mobile mode.

**Manufacturer**: realme
**Brand**: realme
**Model**: RMX1911

**Firefox Details**
87.0.0-rc.1 (Build #2015799099)
AC: 73.0.11, bea80bbac
GV: 87.0-20210315170302
AS: 71.0.0

**Comment by Devanshu19** [comment] 2021-04-01 12:47
Video Added......

**Comment by sflorean** [comment] 2021-04-01 12:54
@Devanshu19 bug #17693 is already filed for your issue, I will close this as duplicate but your scenario will be covered when the issue is fixed.

**Closed by sflorean** 2021-04-01 12:54 UTC
Labels: needs:triage, 🐞 bug
