### ISSUE TITLE
Keyboard isn't triggered when tapping an input box [Bug]

### ISSUE THREAD

**Issue by henriquetguedes** [mozilla-mobile/fenix#17696] opened 2021-01-29 17:01 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
* Go to either [this website](https://programa.partidolivre.pt/) or [this one](https://www.recenseamento.mai.gov.pt/nome.aspx) on Firefox for Android
* Tap the input fields to enter search terms/codes

### Expected behavior
Keyboard should be triggered and input should be possible, as happens with Chrome for Android

### Actual behavior
Nothing happens, thus preventing the user from entering a query

### Device information

* OnePlus / OP6, Android 10
* Firefox for Android version: 84.1.4

**Comment by ekager** [comment] 2021-01-29 19:13
Can you reproduce on Nightly? Available here https://play.google.com/store/apps/details?id=org.mozilla.fenix

**Comment by henriquetguedes** [comment] 2021-01-29 19:19
Indeed, it doesn't happen on Nightly

**Comment by ekager** [comment] 2021-01-29 19:23
Going to close since not being in Nightly means you will soon get a fix. You should get an update for version 85.1.1 today and fingers crossed the fix is in there!

**Closed by ekager** 2021-01-29 19:23 UTC
Labels: Feature:IME, 🐞 bug

**Comment by henriquetguedes** [comment] 2021-01-29 19:27
Got it now, wasn't available earlier, it's fixed for both sites. Cheers
