### ISSUE TITLE
Load pictures only when connected via WiFi 

### ISSUE THREAD

**Issue by muessjoeh** [mozilla-mobile/fenix#14696] opened 2020-09-03 19:19 UTC
### What is the user problem or growth opportunity you want to see solved?

When you are on a mobile data plan, you do not want to spend valuable data on picture files, but only on the text data of the site. So it would be great if pictures would only be loaded if you are connected to a WiFi. This should be configurable. 

### How do you know that this problem exists today? Why is this important?

When I am not near of a WiFi, the images are nevertheless shown, consuming from the data plan. 

### Who will benefit from it?

Everyone with a mobile data plan.

**Comment by cadeyrn** [comment] 2020-09-03 19:38
Duplicate of #810.

**Closed** 2020-09-10 00:58 UTC
Labels: needs:triage
