### ISSUE TITLE
Make the "Quit" button more accessible

### ISSUE THREAD

**Issue by Rosabis** [mozilla-mobile/fenix#21248] opened 2021-09-12 01:16 UTC
I hope browser can show exit bottom easily, the current position requires the menu to be fully expanded to exit the browser, which seems very troublesome.
![IMG_20210912_091448](https://user-images.githubusercontent.com/32984303/132967446-de9ef598-0660-49b7-8780-15cffcaa6a4c.jpg)
![Screenshot_2021-09-12-09-14-54-728_org mozilla fenix](https://user-images.githubusercontent.com/32984303/132967449-60471584-6b20-4727-abc1-7966221fc836.png)

**Comment by LaurentiuApahideanSV** [comment] 2021-09-17 15:21
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/20667. I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-09-17 15:21 UTC
Labels: needs:triage
