### ISSUE TITLE
[Bug] No add-ons in Firefox Nightly

### ISSUE THREAD

**Issue by MinionAttack** [mozilla-mobile/fenix#12420] opened 2020-07-09 10:26 UTC
## Steps to reproduce
1. Open Firefox Nightly
1. Tap in the three dots.
1. Tap in Add-ons.

### Expected behavior
See the installed add-ons or being able to install new add-ons.

### Actual behavior
Nothing is displayed, saying "No add-ons here", and a pop-up with the text "Failed to query Add-ons!" appears.

### Device information
* Android device: Xperia Z3 on Android 6.0.1
* Fenix version: Nightly 200709 06:10 (Build #21910618)

**Comment by hwinnemoe** [comment] 2020-07-09 10:35
I can reproduce on the same Nightly version, device is a Xperia Z2 on Android 6.0.1. My add-ons are still working but I cannot access them.

**Comment by LittleAngelwings** [comment] 2020-07-09 10:47
It's a dupe of this: https://github.com/mozilla-mobile/fenix/issues/12399

**Comment by Amejia481** [comment] 2020-07-09 14:20
Thanks @LittleAngelwings

**Comment by RealGJ** [comment] 2020-07-14 14:59
Able to Reproduce in :
 Nightly 200714 06:01 (Build #21960614)
AC: 50.0.20200712190143, 22f032ca7
GV: 80.0a1-20200711092223
AS: 61.0.7

Thus please re-open this issue

**Comment by RealGJ** [comment] 2020-07-14 14:59
@Amejia481 
Able to Reproduce in :
Nightly 200714 06:01 (Build #21960614)
AC: 50.0.20200712190143, 22f032ca7
GV: 80.0a1-20200711092223
AS: 61.0.7

Thus please re-open this issue

**Comment by LittleAngelwings** [comment] 2020-07-14 20:03
@RealGJ 

There is already an open ticket for that issue: https://github.com/mozilla-mobile/fenix/issues/12399

**Closed** 2020-08-28 22:11 UTC
Labels: needs:triage, 🐞 bug
