### ISSUE TITLE
Make it possible to bypass SSL problems

### ISSUE THREAD

**Issue by julienw** [mozilla-mobile/fenix#4989] opened 2019-08-28 13:07 UTC
### Why/User Benefit/User Problem
The user is barred from accessing a website. Sometimes it works in Chrome.

### What/Requirements
When there's a SSL problem (eg: root certificate not trusted, self signed), there's an error page like it should, but no way of bypassing like on old Firefox or on Desktop.

This happens currently on https://dondesang.efs.sante.fr/ because we revoked the Certinomis root certificate.

### Acceptance Criteria (how do I know when I’m done?)

The user can bypass the error when accessing a website with a SSL problem, just like on Desktop.
("just like on Desktop" means that we can't always do it; for example we shouldn't bypass the error on websites that use HSTS).

**Comment by NotWoods** [comment] 2019-10-05 00:07
Duplicate of #4273

**Closed by NotWoods** 2019-10-05 00:07 UTC
Labels: 🌟 feature request
