### ISSUE TITLE
Bottom navigation bar shows up while scrolling

### ISSUE THREAD

**Issue by AndiLeni** [mozilla-mobile/fenix#16214] opened 2020-10-27 20:26 UTC
Since the last update, the navigation bar (at the bottom on my device) randomly shows up while scrolling down. Then the screen is frozen for a few seconds and scrolling is not possible. 

## Steps to reproduce
Go to a random website and try scrolling up and down. This bug does not seem to appear at specific events. 

### Expected behavior
The navigation bar should only show up when scrolling up. 

### Actual behavior
While scrolling down the navigation shows up and freezes the screen. 

### Device information

* Android device: LG G8s Thinq
* Fenix version: 82.1.1 (Build #2015770923)

**Comment by aleblanc** [comment] 2020-10-28 06:31
Same problem on LG G8s Thinq

**Comment by sskodje** [comment] 2020-10-28 13:50
Same problem on LG G7 Thinq. It prevents scrolling and is extremely annoying. Disabling "scroll to hide toolbar" does not fix the problem. The same thing happens, just that the navigation bar does not move when it happens.

**Comment by AndiLeni** [comment] 2020-10-28 20:28
There are a lot of similar comments on the play store page. 
This issue should be resolved as soon as possible, since it makes the browser unusable.

**Comment by liuche** [comment] 2020-10-29 03:36
Are you seeing this on Nightly? Any ideas @Mugurell about what this could be?

**Comment by Mugurell** [comment] 2020-10-29 07:07
Thank you for your reports!
Could you please share an example of a website you've seen this happening on? 
Also a short video detailing the issue?
Being able to reproduce exactly the issue you're encountering would help us greatly.

**Comment by Mugurell** [comment] 2020-10-29 07:12
> Are you seeing this on Nightly? Any ideas @Mugurell about what this could be, or if it's related to some of the gestures work?

I think these reports are for the just updated release channel but the issues are probably present on Beta and Nightly also.
These could be indeed caused by some recent pan-zoom changes but should probably only happen on particular websites.
Will work with QA to try and reproduce / get a regression range.

**Comment by Mugurell** [comment] 2020-10-29 07:29
I think I reproduced the issue (including the page "freezing") on `support.mozilla.org`
![freezeWhileScrolling](https://user-images.githubusercontent.com/11428869/97538509-30a25d00-19c9-11eb-9ecb-b1d316265eb0.gif)
[video](https://drive.google.com/file/d/1Poo15xIPMnWLpuH1DMPb6a-5Px-HLOhk/view?usp=sharing)

In the first part of the video it's seen that the toolbar does show up if scrolling on that carousel. This is current expected behavior - if a panning gesture is handled by the website we will show the toolbar.
But then the page "freezes" with the panning gesture not scrolling the website or animating the dynamic toolbar.

**Comment by AndiLeni** [comment] 2020-10-29 09:25
@Mugurell 
Thanks for taking care of the problem.

You are right, this issue is also present in the nightly version which is available on the play store.

I could not recognize a pattern on which sites the issue occures. It seems to happen at random (at least to me).
If you need help with testing feel free to reach out to me.

**Comment by AndiLeni** [comment] 2020-10-29 20:34
@Mugurell 
I just noticed, that this issue does not appear after restarting my device. 
The problem appears after browsing for several minutes and gets worse the longer I use the browser.

**Comment by sskodje** [comment] 2020-10-30 22:35
Here's a recording of scrolling down wikipedia at around one swipe per second on an LG G7. It seems to happen more often if you don't scroll continiously, and it happens on every webpage i've visited since the last update. Every time the nav bar pops up, it stops scrolling.
![firefox bug](https://user-images.githubusercontent.com/5401381/97762315-6c900c00-1b08-11eb-842a-b1608ef8666e.gif)

**Comment by DeanKertai** [comment] 2020-10-31 18:42
Seeing the same thing on my LG G8s Thinq. Firefox version 82.1.1

**Comment by AndiLeni** [comment] 2020-10-31 23:14
Two other issues with probably the same problem:
#16295
#16280

**Comment by aleblanc** [comment] 2020-11-05 22:20
Probably the same problem : #16337 
NB: Firefox Focus have not the touch problem

**Comment by AndiLeni** [comment] 2020-11-05 22:27
@Mugurell 
Any update for this issue? 
It seems like many users face this problem currently.

**Comment by Mugurell** [comment] 2020-11-06 15:57
Hello,
Indeed we are seeing more reports of this issue but it's still not clear what triggers it.
If this is easily reproduced by you can you please also try on [GVE](https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-gcp-opt)(geckoview-example.apk) and report back if you see it also happening there?
That is a stripped down version that should eliminate some possible reasons for this.

**Comment by AndiLeni** [comment] 2020-11-06 16:18
@Mugurell  I could not reproduce the issue in the GVE app.

**Comment by meson11** [comment] 2020-11-07 00:15
Same here on oneplus 6. This should be high priority. I see many reports on google play store and this is maximum anoying.

**Comment by 08scoffman** [comment] 2020-11-08 15:26
I just switched from iPhone to LG V50 and I have this exact same problem.  Scrolling just freezes at times. It seems like it's an issue specifically with Firefox on LG phones.  Very annoying.

**Comment by AndiLeni** [comment] 2020-11-15 10:26
Two more issues facing this problem.
#16530
#14527

**Comment by peter-vasut** [comment] 2020-11-15 12:59
I have noticed you mentioned #14527. If it's the same problem, try looking into [this](https://github.com/mozilla-mobile/fenix/issues/14527#issuecomment-727563013) post and check versions I mention there to see, if your issue started to happen at the same time. I think I found first bad version.

**Comment by AndiLeni** [comment] 2020-11-15 18:12
@peter-vasut 
I reverted back to 81.1.5, which is the last version that works fine for me.

**Comment by disinterestedfox** [comment] 2020-12-15 17:38
For what it's worth, I'm also having this issue on Firefox 83.1.0 on my Xiaomi Poco X3.

**Comment by Mugurell** [comment] 2021-02-03 17:01
I think this was resolved by so I'm going to close the ticket.
If this is still an issue for you feel free to leave a comment and we'll investigate.

**Closed by Mugurell** 2021-02-03 17:01 UTC
Labels: Feature:Toolbar, 🐞 bug
