### ISSUE TITLE
FNX-11963 ⁃ The collection is not necessary, can it be hidden in the settings?

### ISSUE THREAD

**Issue by tangzhui** [mozilla-mobile/fenix#11098] opened 2020-05-31 07:00 UTC
![img](https://user-images.githubusercontent.com/59478712/83346493-70e4ad00-a34f-11ea-9a60-bba81715fb08.jpeg)UNITO-UNDERSCORE!eggsif!UNITO-UNDERSCORE!7861983268789845248-01!

**Comment by SS1113** [comment] 2020-05-31 07:12
I don't get the idea of collections. They don't sync (losing the collections after spending a lot of time curating them is really frustrating!), they are not useful for anything to me, when Fenix launched without support for speed dials I used it in place of bookmarks, and now I'm using them in place of saving offline pages (only as shortcuts to the webpages). 

It's better if the feature stays hidden or at least an option to hide and occasionally give the pop-ups let the users know that this sort feature is there if you you want to use it.

**Comment by cadeyrn** [comment] 2020-05-31 07:21
Duplicate of #3753.

**Comment by sheikh-azharuddin** [comment] 2020-05-31 08:10
> I don't get the idea of collections. They don't sync (losing the collections after spending a lot of time curating them is really frustrating!), they are not useful for anything to me, when Fenix launched without support for speed dials I used it in place of bookmarks, and now I'm using them in place of saving offline pages (only as shortcuts to the webpages).
> 
> It's better if the feature stays hidden or at least an option to hide and occasionally give the pop-ups let the users know that this sort feature is there if you you want to use it.

Or maybe they can add the collection feature in desktop version and allow sync similar to new microsoft edge

**Comment by ekager** [comment] 2020-06-01 14:48
Closing for  #3753

**Closed** 2020-08-11 02:53 UTC
Labels: needs:triage
