### ISSUE TITLE
[Bug]Fenix home screen is displayed while making the transition to Settings

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9224] opened 2020-03-18 10:17 UTC
## Steps to reproduce
1. From Fenix's home screen tap the ⋮ Main menu button
2. Tap and open Settings from the overlay

### Expected behavior
Smooth transition with no animation issues.

### Actual behavior
The home screen is displayed while making the transition to Settings.
The default top sites are the most obvious.

### Device information

* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

* Fenix version: Nightly Build #20780606 from 3/18

### Notes
► Video Light theme
![20200318-120645](https://user-images.githubusercontent.com/51314259/76949684-9c8bf580-6911-11ea-97ef-02f28c6194a5.gif)

► Video Dark theme
![20200318-095255](https://user-images.githubusercontent.com/51314259/76949545-5cc50e00-6911-11ea-80c1-4fb8c5f20978.gif)

@sblatz - Could you please check ? ☺️

**Comment by darkwing** [comment] 2020-03-27 18:30
I was able to reproduce this once but every other time it quickly displays...not sure how to reliably reproduce this.

**Comment by darkwing** [comment] 2020-03-27 18:31
BTW, found this as a possible solution: https://stackoverflow.com/questions/12711418/change-preference-screen-background-color

**Comment by sblatz** [comment] 2020-03-27 18:46
I ended up removing this animation since it looked really strange to have the action bar not be part of the animation (unfortunately there's not a way to animate it). 

Closing this for now :)

**Closed by sblatz** 2020-03-27 18:46 UTC
Labels: Feature:HomeScreen, Feature:Settings, S2, 🐞 bug
