### ISSUE TITLE
[Bug]: High refreshrate disabled while browsing. Bug merged from Nightly to Beta.

### ISSUE THREAD

**Issue by BitGrub** [mozilla-mobile/fenix#28295] opened 2022-12-22 17:08 UTC
### Steps to reproduce

Steps to reproduce:
1. Have a high-refresh rate phone (>60Hz)
2. Download and install a fresh instance of Firefox Beta or Nightly (stable isn't affected yet)
3. Visit a website. Any website. The settings pages are unrestricted, but as soon as you browse the web, the browser is locked to 60fps.

### Expected behaviour

This bug was present in Nightly for at least half a year (I noticed it as soon as I got my phone in mid-late July). I was forced to move to Firefox Beta as soon add-on support was added (late October), where I could browse at 120fps until very recently. I don't know which update broke it, but it happened about a week ago. The Nightly bug went unaddressed and has now been merged to the Beta branch.

I would like to use my 120Hz screen please.

### Actual behaviour

As mentioned in the steps to reproduce, the 60 fps limit is only forced when browsing the web. Firefox settings pages are allowed to run at a full 120, so it's definitely a bug with the engine and not with my phone's settings.

### Device name

Nothing Phone (1)

### Android version

Android 13

### Firefox release type

Firefox Beta

### Firefox version

109.0b3 (Build #2015922923)

### Additional information

I hope add-on collections are introduced to Firefox Stable before this bug.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22187)

**Comment by sheikh-azharuddin** [comment] 2022-12-24 14:16
I am getting 120hz in every webpage in nightly..maybe your phone issue🙄

Attaching screenshot.

![Screenshot_2022-12-24-19-46-17-004_org mozilla fenix](https://user-images.githubusercontent.com/58127841/209439644-336259c6-664b-4986-b301-bf84fa6a0661.jpg)

**Comment by BitGrub** [comment] 2022-12-24 14:20
> I am getting 120hz in every webpage in nightly..maybe your phone issue🙄
> 
> Attaching screenshot.
> 

Maybe try using Nightly or Beta? It's pretty clear In the post..maybe your phone issue🙄

**Comment by sheikh-azharuddin** [comment] 2022-12-24 14:22
I am using nightly only from beginning..never used stable one except to test some issues.

![Screenshot_2022-12-24-19-52-36-780_org mozilla fenix](https://user-images.githubusercontent.com/58127841/209439886-8846c267-e4ef-4cd7-8f2a-f36e3ff46e94.jpg)

**Comment by BitGrub** [comment] 2022-12-24 14:24
Then it could be some other firefox bug that only affects Pixels and Nothing Phones. Or maybe there's a flag you changed in about:config 🤷

**Comment by sheikh-azharuddin** [comment] 2022-12-24 14:29
No flag changed for refresh rate ..in fact there is none bro 😅
I have set my refresh rate to adaptive in the phone settings and it always uses 120hz except for few inbuilt app
My phone is poco f4

**Comment by BitGrub** [comment] 2022-12-24 14:32
> No flag changed for refresh rate ..in fact there is none bro 😅

You do know bugs aren't intentional right? Of course it SHOULD work, and your flags SHOULDN'T affect frame rate, yet here we are bro

> I have set my refresh rate to adaptive in the phone settings and it always uses 120hz except for few inbuilt app
> My phone is poco f4

Thanks for providing some info, that is helpful

**Comment by makotokato** [comment] 2022-12-25 14:56
I think that this is dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1795138

**Comment by amocirean** [comment] 2023-01-03 13:30
Hello @BitGrub , thank you for submitting the issue.
As the previous comment stated, this issue is a duplicate of [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1795138) issue.

**Closed by amocirean** 2023-01-03 13:30 UTC
Labels: 🐞 bug, needs:triage
