### ISSUE TITLE
[Crash] IllegalStateException: Fragment HomeFragment not attached to a context.

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#9936] opened 2020-04-14 22:14 UTC
At first glance this feels like a regression from https://github.com/mozilla-mobile/fenix/pull/9436

https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7703389/events/42495484/

```
java.lang.IllegalStateException: Fragment HomeFragment{121f337} (15f152fa-9441-47d3-a86d-8d896cfc8ed7)} not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
    at kotlin.jvm.internal.Intrinsics.getRequireComponents(Intrinsics.java:1)
    at org.mozilla.fenix.home.HomeFragment.getSessionManager(HomeFragment.kt:1)
    at org.mozilla.fenix.home.HomeFragment.getListOfSessions(HomeFragment.kt:1)
    at org.mozilla.fenix.home.HomeFragment.emitSessionChanges(HomeFragment.kt:2)
    at org.mozilla.fenix.home.HomeFragment.access$emitSessionChanges(HomeFragment.kt:1)
    at org.mozilla.fenix.home.HomeFragment$onCreate$sessionObserver$1.invoke(HomeFragment.kt:1)
    at org.mozilla.fenix.home.BrowserSessionsObserver$onStart$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:4)
    at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:7)
    at kotlin.jvm.internal.Intrinsics.emitAllImpl$FlowKt__ChannelsKt(Intrinsics.java:14)
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7050)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by grigoryk** [comment] 2020-04-14 22:34
https://github.com/mozilla-mobile/fenix/pull/9436 landed on March 26, and first crashes started to happen around March 31st.

**Comment by ekager** [comment] 2020-04-21 06:23
Similarly to #6832 we hope that leak fixes for home in #10033 and #10012 will resolve these issues. We should monitor Sentry over a few more days and see if instances decrease.

**Comment by ekager** [comment] 2020-04-21 06:25
But from a quick glance looks promising 🤗
<img width="324" alt="Screen Shot 2020-04-20 at 11 22 26 PM" src="https://user-images.githubusercontent.com/25442310/79832377-23dbe700-835e-11ea-8232-88f8589db3cb.png">

**Comment by liuche** [comment] 2020-04-22 01:01
Is this just a dupe of #6832?

**Closed by liuche** 2020-04-22 01:01 UTC
Labels: b:crash, 🐞 bug

**Comment by vipin00147** [comment] 2022-03-11 07:04
set the context of your Activity that u r using
i.e MainActivity
