### ISSUE TITLE
[Bug]: "Desktop site" slider broken for unloaded/reloaded tabs

### ISSUE THREAD

**Issue by Noob729** [mozilla-mobile/fenix#25338] opened 2022-05-23 00:08 UTC
### Steps to reproduce

1. Open e.g. reddit.com in a new tab
2. Switch the tab to "Desktop mode" (Options > "Desktop site" slider)
3. Open several more tabs (to increase memory pressure)
4. At some point, FF decides to unload the first tab from memory
5. Switch back to the first tab
6. Fenix reloads the tab in "Mobile mode"

### Expected behaviour

Fenix should reload the unloaded tab in "Desktop mode".

### Actual behaviour

Fenix reloads the unloaded tab in "Mobile mode",  
even though the "Desktop site" slider is "enabled" (slid to the right)  
Toggling the slider several times has no effect.  

### Device name

Xiaomi Redmi Note 5 Pro (whyred)

### Android version

Android 8.1.0

### Firefox release type

Firefox

### Firefox version

100.2.0

### Additional information

https://support.mozilla.org/en-US/kb/unload-inactive-tabs-save-system-memory-firefox  
https://firefox-source-docs.mozilla.org/browser/tabunloader/  
Is about:unloads disabled in "Fenix Release" ?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20530)

**Comment by amocirean** [comment] 2022-05-23 12:39
Hello @Noob729 , thank you for submitting the issue.
I was not able to reproduce it on the latest RC or Nightly
Could you tell us if the issue is still occuring on the latest RC or Nightly on your device?
Also, could you provide a video regarding the issue?

Device Used: Huawei P40 Lite
Android Version: 10

**Comment by Noob729** [comment] 2022-05-25 12:44
Hello @amocirean,  
Are you a Fenix dev? Or official support? 🤔  
Yes, I can reproduce the issue on Fenix 102.0a1

**Comment by Noob729** [comment] 2022-05-25 13:04
@amocirean 
Here's a video showing the problem:  
https://file.io/4akLLIezZrXP

**Comment by zlice** [comment] 2022-05-27 19:40
It will ignore "desktop" mode even going back/forward in the same tab for me.

**Comment by Noob729** [comment] 2022-05-29 21:17
Hello @zlice  
Are you saying that:  
You open a new tab, load a site, move the "Desktop site" slider to the right.  
You get the desktop version, right?  
Then if you move the slider back to the left, you don't get the mobile version?  
(For what it's worth, that works for me.  
It's only after a forced reload that the slider is broken for me.)

**Comment by zlice** [comment] 2022-05-29 21:51
No

- open site
- change to desktop (get desktop)
- open new tab
- go back to previously desktop site
- not desktop

**or**

- open site
- change to desktop (get desktop)
- go to new link, refresh page, pretty much anything
- may go back to mobile site even though desktop mode is set

**Comment by Noob729** [comment] 2022-05-30 23:52
Hello @bigConifer  
Thanks for monitoring the bug list for dupes.  
That is so depressing. Two years, and no fix in sight :(  

I guess my bug report brings a new twist:  
With FF now unloading tabs at run-time, the problem became much more annoying.  
I need to install the Beta release, and disable tab unloading.

**Comment by bigConifer** [comment] 2022-05-31 09:47
@Noob729 Having half a dozen tickets open for the same bug doesn't speed up anything.
So please close this as dupe and comment on the tickets already existing to add your subaspects there.

**Closed** 2022-05-31 14:28 UTC
Labels: 🐞 bug, needs:triage
