### ISSUE TITLE
[Bug] close tab toast doesn't dissappear 

### ISSUE THREAD

**Issue by DPDmancul** [mozilla-mobile/fenix#8341] opened 2020-02-12 09:04 UTC
## Steps to reproduce
Close a tab

### Expected behavior
The toast will disappear in few seconds and tapping on "cancel" will reopen the closed tab

### Actual behavior
The toast doesn't disappear by self but tapping on "cancel" it doesn't reopen the closed tab but dismiss the toast

### Device information

* Android device: Redmi Note 7 - Miui 11 (Android 9)
* Fenix version: 3.2.0 (Build #20250236)

**Comment by cadeyrn** [comment] 2020-02-12 09:18
Duplicate of #7799.

**Comment by sv-sdeiac** [comment] 2020-02-12 11:40
This issue is now fixed for the Nightly build, the fix will appear on future builds of Beta/RC. 
Due to that, I'll close this ticket, thanks.

**Closed** 2020-02-12 12:07 UTC
Labels: needs:triage, 🐞 bug
