### ISSUE TITLE
FNX2-15175 ⁃ Tab Queue

### ISSUE THREAD

**Issue by jpdus** [mozilla-mobile/fenix#12338] opened 2020-07-07 10:17 UTC
### What is the user problem or growth opportunity you want to see solved?
Referring to [this issue](https://github.com/mozilla-mobile/fenix/issues/470), I wanted to highlight this problem again. (Sorry if that isn't appropriate, but the old issue was closed/removed without any resolution or answer and other users were referred to the closed isse?)

Does the reaction to the old issue mean that this feature will not make it into any current mobile Firefox?

### How do you know that this problem exists today? Why is this important?
My whole mobile browser usage depends on this feature, am stuck with the old (unsafe) app for the time being.

### Who will benefit from it?
As can be seen in the "old" issue and issues that were opened in since then (and in other places, e.g. [here on reddit](https://www.reddit.com/r/firefox/comments/fxseec/queuing_tabs_in_background_on_latest_firefox_beta/), or [here on Mozilla](https://support.mozilla.org/en-US/questions/1284795) ), I am not the only one for whom that feature is extremely important.

**Comment by cadeyrn** [comment] 2020-07-07 14:40
Duplicate of #470 as you yourself have already discovered. The conversation is restricted but it's still an open issue and not closed.

**Comment by jpdus** [comment] 2020-07-07 15:28
> Duplicate of #470 as you yourself have already discovered. The conversation is restricted but it's still an open issue and not closed.

Sorry,  but what exactly does that mean? 
_"removed this from Investigation in Fenix Q2 Feature Backlog_" (with no other following activity) sounds as if the feature is gone for good?
Many thanks and sorry for opening a Duplicate.

**Comment by cadeyrn** [comment] 2020-07-07 17:03
It was removed from the Fenix Q2 Feature Backlog project board (https://github.com/mozilla-mobile/fenix/projects/30), nothing else. This doesn't mean that it won't be implemented in the future. The issue is still open.

**Comment by kbrosnan** [comment] 2020-07-07 17:21
Closing as a duplicate.

**Comment by jmmerz** [comment] 2020-08-27 22:24
I desperately hope to see this implemented soon. I unfortunately updated Firefox on my Android phone without realizing the tab queue was missing from the new version. I used to do:
`Click a bunch of Links` -> `Switch to Firefox to read`
but now I end up doing:
`Click Link in Email` -> `Opens Firefox` -> `Switch back to Email` -> `Click Next Link` -> `Repeat many times...` -> `Switch to Firefox to read`

Seems like all the app switching will make up for any improved power usage from the new version, and the time switching back and forth definitely is eliminating the advantage of slightly better responsiveness in the Firefox UI.

**Closed** 2020-08-28 21:55 UTC
Labels: needs:triage
