### ISSUE TITLE
crashing when launching[Bug]: 

### ISSUE THREAD

**Issue by francetvjanv2021** [mozilla-mobile/fenix#28326] opened 2022-12-28 08:37 UTC
### Steps to reproduce

I keep updating firefox nightly on android, but lately, I just can't launch it at all.

opens but then crashes immediately after

### Expected behaviour

not lauching

### Actual behaviour

crash

### Device name

samsung galaxy tab s2

### Android version

7.0

### Firefox release type

Firefox Nightly

### Firefox version

110 0 a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22202)

**Comment by buttercookie42** [comment] 2022-12-28 16:24
Probably duplicate of #28310 and/or #28297, which in turn have been forwarded to https://bugzilla.mozilla.org/show_bug.cgi?id=1807716.

**Comment by csadilek** [comment] 2022-12-29 22:15
Please follow https://bugzilla.mozilla.org/show_bug.cgi?id=1807716..

**Closed by csadilek** 2022-12-29 22:15 UTC
Labels: 🐞 bug, needs:triage
