### ISSUE TITLE
[Bug]site notification

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12163] opened 2020-07-01 17:42 UTC
## Steps to reproduce
Browse the website https://telecomtalk.info it should display a message site wants to send you notification allow or block...this works fine in chromium browsers but it is not showing in fenix...I have observed this in several other sites ...in Firefox desktop it shows this message but not showing in fenix...only sites which have explicit settings to configure/enable push notification works example twitter.com....please fix this bug

### Expected behavior
Site should show a message it wants to send notification with option allow or block...

### Actual behavior
It does not show any notification ...works fine in Firefox desktop and chromium browsers. 

### Device information
* Android device: ? A10
* Fenix version: ? Latest nightly

![Screenshot](https://user-images.githubusercontent.com/58127841/86274949-09c24e80-bbc2-11ea-9c4a-16df835a0cf3.jpg)UNITO-UNDERSCORE!20200701-230446!

**Comment by liuche** [comment] 2020-07-01 21:56
This sounds like the opposite of #11033, but wondering if this is somehow related to #12077 ?

**Comment by sheikh-azharuddin** [comment] 2020-07-02 03:28
> This sounds like the opposite of #11033, but wondering if this is somehow related to #12077 ?

The 2nd case 12077 is related to resetting notification which I can do easily by going to site permissions and clearing the exceptions....the first case says user getting notification even though he didn't allow....the Twitter has embedded setting(not site setting) to push notification...this is independent of the site notification...

In my case when you browse a page such as the link which I have it should show a prompt to allow or block notification... Unlike twitter where push notification will work only after signing in , this thing normally push notification even though you have not signed in...
The prompt is coming even in Firefox desktop version not sure why not showing in fenix even after reloading the page multiple time.

**Comment by jonalmeida** [comment] 2020-07-02 06:47
@sheikh-azharuddin we should a prompt when a site requests to show notifications. For Twitter, this happens when you go into their settings and toggle the setting on.

<img width="634" alt="Screen Shot 2020-07-02 at 2 45 47 AM" src="https://user-images.githubusercontent.com/1370580/86325516-284e3700-bc0e-11ea-9f04-2690c435ec53.png">

**Comment by sheikh-azharuddin** [comment] 2020-07-02 06:49
But it is not working for some sites which don't have settings to push notifications....

Best example is https://telecomtalk.info
It does not show any notification...

**Comment by jonalmeida** [comment] 2020-07-02 07:21
This looks like an issue with the site itself and not Fenix. I do not see the site requesting desktop Firefox or Chrome to send notifications.

Please contact the site owners to notify them if you think this is a bug. I'm going to close this issue in that case.

Thanks for reporting! 🙂

**Comment by sheikh-azharuddin** [comment] 2020-07-02 07:27
This is not fair ... without proper investigation you are closing the case...the site is definitely pushing an option to allow or block notification...checked in microsoft edge, chrome, Vivaldi mobile browsers....screenshot also attached in the first thread

In Firefox desktop also it shows this....here is the screenshot from Firefox desktop-

![P_20200702_125513](https://user-images.githubusercontent.com/58127841/86329255-6b6fd080-bc35-11ea-8d25-78854819c17c.jpg)

**Comment by sheikh-azharuddin** [comment] 2020-07-02 07:29
this is not about this site only...while using firefox deskttop i have come across several sites which shows this...i specifically selectes this site to help you to fix the issue

**Comment by jonalmeida** [comment] 2020-07-06 03:20
What you're seeing is expected behaviour. Firefox by default blocks notification requests by a site if they are made without user interaction. You can read more about this behaviour in this [blog post here](https://blog.nightly.mozilla.org/2019/04/01/reducing-notification-permission-prompt-spam-in-firefox/). 

Below, you can see that when I interact with the site by tapping, the notification request shows up (as you probably did when you took the picture above):
<img width="320" alt="Screen Shot 2020-07-05 at 11 15 51 PM" src="https://user-images.githubusercontent.com/1370580/86552278-82ecd900-bf15-11ea-93fa-d5cb680e5422.png">

**Comment by sheikh-azharuddin** [comment] 2020-07-06 03:51
Thanks for the information... Whats weird even after clicking several articles in that site the send notification is not showing.... Can someone else try and let me know...

**Comment by cadeyrn** [comment] 2020-07-06 10:43
> Can someone else try

I get the prompt once I open a discussion link and only in Firefox 79 Beta. In Firefox Nightly it doesn't work at all.

**Comment by sheikh-azharuddin** [comment] 2020-07-06 10:58
Exactly! it is not working in nightly.... 
BTW why issue is closed?????

**Closed** 2020-08-28 21:24 UTC
Labels: Feature:Notifications, needs:ac, 🐞 bug
