### ISSUE TITLE
FNX3-15627 ⁃ [Bug] Animation when switching from regular to private mode doesn't "feel good"

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1533] opened 2019-04-10 20:26 UTC
### Steps to reproduce
1. switch from regular to private mode

### Expected behavior
Smooth animation when switching from regular to private mode.

### Actual behavior
A new fade animation has been implemented for switching the browsing mode. But it doesn't "feel good". It seems that there is a bright flicker for a very short moment but it's hard to say because it's so fast.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision f36da2d8f22e769294b42fbd0f2081e835071225

**Comment by bsurd** [comment] 2019-04-11 07:40
This is a dupe of #689, closing.

**Comment by cadeyrn** [comment] 2019-04-11 08:08
@bsurd: It's not a dupe. #689 was reported in two months ago and was about implementing a fade animation. The fade animation was implemented yesterday. Before that there was no fade animation at all.

My report is about the new fade animation which doesn't feel better than the previous state, quite the opposite.

**Comment by bsurd** [comment] 2019-04-11 10:48
@cadeyrn After some testing, it would seem that the fix does not work for HTC devices. Reopening the issue.

**Comment by sblatz** [comment] 2019-04-16 16:39
@cadeyrn can you show me what it looks like on HTC devices? I believe this is an HTC-only issue as they are choosing to not respect the android transition animations, and we don't have an easy way to override that.

**Comment by bsurd** [comment] 2019-04-17 07:04
Here is a short video from the [HTC 10](https://drive.google.com/open?id=1o99lLbPpmi4kaConUWS2jOnjAn-F6iNq).

**Comment by cadeyrn** [comment] 2019-04-17 07:51
![20190417_092812](https://user-images.githubusercontent.com/1100614/56270339-2de95b00-60f6-11e9-8fdf-23e0d41ec53c.gif)

@sblatz If you can't improve the transition animation would it be possible to disable the transition animation for devices without proper transition animation support?

**Comment by cadeyrn** [comment] 2019-04-18 05:31
Fixed by #1738 which removed the fade animation again.

**Closed** 2020-08-11 08:43 UTC
Labels: 🐞 bug
