### ISSUE TITLE
FNX-5500 ⁃ [Meta] Site Permissions

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#218] opened 2019-01-21 19:02 UTC
See https://github.com/orgs/mozilla-mobile/projects/8 for breakdown of work.

Site permission flows: https://whimsical.co/QXGiB45gjs1iniprdrWdBG

**Comment by bbinto** [comment] 2019-02-07 15:20
AC board: https://github.com/orgs/mozilla-mobile/projects/8

**Comment by vesta0** [comment] 2019-04-04 12:51
Duplicate of #886

**Closed** 2020-08-11 14:11 UTC
Labels: must, needs:ac
