### ISSUE TITLE
[RFE] fight back mobile access denial / per site/domain "desktop site" mode

### ISSUE THREAD

**Issue by Lanchon** [mozilla-mobile/fenix#25049] opened 2022-05-01 04:06 UTC
mobile access to perfectly capable sites is being routinely denied in order to advance an agenda: force users to install (privacy compromising) apps.

example: https://discord.com/app
on desktop: brings up a perfectly capable first class chat UI.
on mobile: redirects you to the stupid play store.

fenix has "desktop site" mode which more or less makes this site work. (whatever does not work as expected could be improved later.)

the problem is, one has to copy the URL, switch to desktop site mode, paste, go... each time! this is so unusable that many users will give in and install the app.

a solution to this would be to set desktop site mode per site/domain instead of per browser, so that future visits are taken care of. the menu "desktop site" on/off toggle could be replaced for a "desktop mode..." option that maybe asks:
- set desktop mode for this browser window
- set desktop mode for this session for site: blah.com
- always use desktop mode when browsing site: blah.com

the last option (or all options) could include a checkbox for clearing cookies for the site(s) (especially if 3rd party cookies are blocked). or for using a separate cookie jar for desktop mode for this 1st party site. or similar options.

finally, i think redirections to a playstore app page are 99% of the time an anti-feature, and as such should be intercepted. maybe options should be displayed instead:

*This site is redirecting you to the Play Store to download an app.*
*Apps are a risk to your privacy. What do you want to do?*
- Try opening the site pretending to be a desktop browser.
- Go to the Play Store as directed.
- Close this web page.

thanks!

EDIT:

i know firefox android doesn't have a very large user base. so it can't flex its muscle to force websites into "desired" behavior, whatever that might be, like chrome/safari do. but these kinds of flow interruptions, if useful enough, do provide a user visible reminder of the superiority of firefox in certain regards, and even provides talking points to regular users who value this browser.

but why am i writing this?

turns out that https://discord.com/app on my phone no longer redirects to playstore... magic! i suspected an adaptive strategy and tried private browser: same thing, no redirection. the mobile website at https://discord.com/ is conspicuously missing a link to the web app (present in desktop website); but other than that, the app works fine now.

even though discord came to its senses (sort of, link is missing), this does not invalidate this RFE. i've suffered this issue for ages, even back when google was not despicable and i was a chrome user. i understood then why google wanted to please sites and made the feature non-persistent, but i don't see a reason to keep this behavior in firefox.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-05-02 01:27
Duplication of the URI is not necessary. During utilisation of this site, merely switch the toggle that enables Desktop Mode to utilise Desktop Mode. Consequently, creation of additional tabs is not neccessary.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-05-02 01:29
I hope that if direction to Google Play via its scheme is intercepted, disablement of that interception is possible, anr hopefully extensible to alternative schemas, because I care not about privacy, but do care whether I am innecessarily interrupted.

**Comment by Lanchon** [comment] 2022-05-02 03:25
> Duplication of the URI is not necessary. 

yes it is. many sites (see example above) immediately redirect to play store. so if you toggle "desktop site" you will see the play store again.

you have to copy the link to the affected site (not click on it), open a new tab, set desktop site mode, paste, go.

...if the site does not countermeasure for that. it might store a "really a mobile device" cookie to disallow that, and so you'd need to open a private browsing tab or wipe cookies.

**Comment by Lanchon** [comment] 2022-05-02 03:35
> I hope that if direction to Google Play via its scheme is intercepted, disablement of that interception is possible

you mean the google play local app or the google play website? mi firefox simply goes to the website, as i disabled launching local apps from links and instant apps. that kind of thing sort of makes me vomit. i don't remember how i did it though.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-05-02 04:25
Why is my utilisation of Firefox relevant to that?

**Comment by Lanchon** [comment] 2022-05-02 05:55
what is relevant is that stuff like privacy and security always end up being a tradeoff with convenience. you advocate sacrificing privacy for convenience:

> because I care not about privacy, but do care whether I am unnecessarily interrupted

other browsers probably suit you better then. for users who value privacy, an interruption into a probably undesired flow is a welcomed thing, so that they discover an alternative have an app stuck down their throats. discoverability is worth being interrupted IMHO.

firefox is gaining features to fight back on the privacy front, and some such features break some websites. sooner or later, your flow will be interrupted because of this, so other browsers might be more convenient to you.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-05-03 16:19
@Lanchon no alternative browser provides what I desire, because Firefox is available via F-Droid and allows installation of extensions. Never has its apparent focus upon privacy been bothersome for me, because they have allowed all that is relevant to it to be possible to disable.

However, regardless of that, to develop a browser that is not suitable for most of humanity merely because some users do not desire some useful configurative ability is obviously silly, so I doubt that this is worth discussing.

Additionally, to arbitrarily blacklist Google Play's URI and not any alternative URIs is actually worse for privacy. Consequently, your statements have been ultimately slightly nonsensical.

**Comment by Lanchon** [comment] 2022-05-03 22:14
not being trolled into this. please dont spam this issue. thanks.

**Comment by kbrosnan** [comment] 2022-05-09 20:28
Closing this as a duplicate of https://github.com/mozilla-mobile/fenix/issues/7039. Per site desktop controls could be part of that.

**Closed by kbrosnan** 2022-05-09 20:28 UTC
Labels: feature request 🌟, Feature:RequestDesktopSite

**Comment by Lanchon** [comment] 2022-05-10 00:09
@kbrosnan not really, read that bug. it specifically requests desktop by default on all sites (which is not what i need) and discards the option of a per site setting (which is a solution for me) in the opening message.

most importantly the rationale for the feature is different: personal preference vs privacy (and freedom).

also does not identify the use of playstore links as sometimes malicious.

in all, related by not duplicate by a really long shot. so you'd do good to the proyect by reopening this. closing it was a mistake. thanks
