### ISSUE TITLE
add basic themes (firefox colorways) in firefox

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#22926] opened 2021-12-21 02:33 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently Firefox android does not support any themes like desktop version. So some basics themes can be added such as firefox colorways which was recently added in firefox desktop variant. Or kind of themes added in opera gx browser.

### How do you know that this problem exists today? Why is this important?
Just White and black looks dull and boring

### Who will benefit from it?
Users who like themes

https://support.mozilla.org/en-US/kb/personalize-firefox-colorways

![Screenshot_20211221-080201842](https://user-images.githubusercontent.com/58127841/146860937-edcca53b-c61c-4f03-91e5-184a6221f344.jpg)

**Comment by LaurentiuApahideanSV** [comment] 2022-01-06 11:12
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/10032. I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2022-01-06 11:12 UTC
Labels: needs:triage
