### ISSUE TITLE
[Bug] Long-tap on links sometimes triggers a text selection

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#10619] opened 2020-05-13 08:17 UTC
## Steps to reproduce
1. On wikipedia.com, long tap the Wikimedia Foundation Link.
1. Zoom in and out on the page and the long-tap any link from the languages displayed. 
1. Or, go to cnn.com and long-tap the Cookie Settings link at the bottom of the page.
    1. Expected behavior
Link context menu is opened.
    1. Actual behavior
The link text is selected sometimes instead of triggering the context menu.
    1. Device information

* Android device: Pixel 4 (Android 10), Huawei P9 Lite (Android 7)
* Fenix version: Nightly 5/13.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-802)

**Comment by AaronMT** [comment] 2020-05-13 14:23
This is great that our UI tests caught this actual bug!

**Comment by kbrosnan** [comment] 2020-05-13 20:10
I think this is https://bugzilla.mozilla.org/show_bug.cgi?id=1336209 which was never fixed on the Gecko side.

**Comment by madb1lly** [comment] 2020-05-19 07:59
Hi all,

This happens for me too on some pages, e.g. on this page: http://www.linux-usb.org/usb-ids.html and this page http://pciids.sourceforge.net/.

Nokia 8 on Android 9

Cheers 🙂

**Comment by karlcow** [comment] 2020-05-20 05:07
Se may have issues on webcompat because of this.

**Comment by AaronMT** [comment] 2020-05-20 14:39
fairly confident this is a recent regression because some of UI tests started failing as of last week showing this behavior in video

**Comment by madb1lly** [comment] 2021-02-25 13:17
> 
> 
> Hi all,
> 
> This happens for me too on some pages, e.g. on this page: http://www.linux-usb.org/usb-ids.html and this page http://pciids.sourceforge.net/.
> 
> Nokia 8 on Android 9
> Nightly 200518 06:00 (Build #2015740979)
> 42.0.20200515130053, 240940534
> GV: 78.0a1-20200514094044
> AS: 0.58.2
> 
> Cheers 🙂

I can no longer reproduce the bug on these pages, so I think it can be closed.
Cheers 🙂

**Comment by mariansima** [comment] 2021-08-30 08:21
This issue was reproduced on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29

**Comment by DavidJCobb** [comment] 2021-11-15 01:25
This has happened for me tons of times in both Fennec and Fenix, and on multiple devices. I can never reproduce it consistently for any given link, and not for lack of trying. As far as I know, if Firefox thinks my finger landed 0.001mm too far away from the link, I get a text selection instead, and my fleshy human fingers can't tap precisely enough to repro that. Definitely not fixed, though; it literally just happened to me a few minutes ago.

For me it's maybe one out of every few hundred or thousand long presses on links... which, in practice, is quite frequent.

**Comment by madb1lly** [comment] 2022-11-25 02:03
Has happened again recently, can't remember the site unfortunately. When I get recurrence I'll post the details.

**Comment by csadilek** [comment] 2023-01-09 20:36
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809294

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2023-01-09 20:36 UTC
Labels: 🐞 bug, S2, Feature:ContextMenu
