### ISSUE TITLE
[Bug] Backspacing from end of URL bar has serious and frustrating UX issue

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#12525] opened 2020-07-13 20:20 UTC
There's a serious bug when trying to backspace a URL. Go to instagram.com/firefox . Tap URL bar and then drag the cursor to the very end until there's no characters after the cursor, now start tapping Backspace (it doesn't happen if you hold down on the Backspace key). Notice that as you tap "Backspace", the URL bar seems to immediately refill/recomplete what you've just backspaced. It seems like as soon as a character is deleted, the URL bar autocompletes it again. This is very frustrating and I would say this is a release blocker. It happens with both Gboard and SwiftKey, btw, so I think that should narrow it down a bit.

It seems to only happen with paths? After a minute of wrestling with this, by the time the path is fully backspaced, I can backspace normally. Very strange and annoying, please look at this right away.

Google Pixel 3a XL, Android v10, Fenix Nightly.

**Comment by willfs84** [comment] 2020-09-08 16:47
https://www.reddit.com/r/firefox/comments/iorfqh/fennix_using_backspace_on_url/

**Comment by yoasif** [comment] 2020-09-08 17:02
@willfs84 Is this still happening in Nightly for you? I can't reproduce on a Pixel 2, FWIW.

**Comment by willfs84** [comment] 2020-09-10 02:32
I can no longer repro in Nightly! I guess someone fixed it

**Comment by LaurentiuApahideanSV** [comment] 2020-09-10 09:30
The issue is still reproducible on Firefox Preview Nightly 200910 (Build #2015763059).
### Devices used:
- OnePLus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)

**Comment by willfs84** [comment] 2020-09-10 17:40
Last night, I couldn't repro. I just updated Nightly and this bug is back. So something changed again in todays Nightly...

**Comment by RachitKeertiDas** [comment] 2020-09-10 18:44
Yep, 
I guess this was fixed earlier but it seems to have regressed with today's update.

### Device Tested:
Redmi Note 7S

### Nightly Version:
 
Firefox Browser Nightly 200910 06:07(Build #2015763059)

A screencast of the issue:
![output](https://user-images.githubusercontent.com/51906583/92783654-9871f980-f3c3-11ea-8417-855455716104.gif)

**Comment by RachitKeertiDas** [comment] 2020-09-24 14:10
Pinging (@jonalmeida) since he is assigned to this issue
Any chance of a fix in the near fututre (since this can be irritating for users who manipulate URLs)?

Thanks

**Comment by Sayrus** [comment] 2020-10-24 11:17
Is there any update on the subject?

Is help needed to resolve the matter? If so, can the issue get a `help wanted` flair? I'd gladly take a look and try to debug if this isn't being worked on.

**Comment by mcarare** [comment] 2021-02-18 17:16
Looked more into this. 

It seems that in `InlineAutocompleteEditText we` do not correctly check for backspace pressed.
We use logic for this in `hasBackspaceBeenPressed` as the `OnKeyListener` does not pick up the backspace from the soft keyboard. 
 
Talked offline with @jonalmeida and he is not actively working on this, so maybe @codrut-topliceanu, as you introduced this boolean and you have more insights on other issues this piece of code solved, can you pick this up and look into improving the logic to also cover this case?

**Comment by codrut-topliceanu** [comment] 2021-02-25 12:13
Will be fixed by https://github.com/mozilla-mobile/android-components/issues/9774 and its PR https://github.com/mozilla-mobile/android-components/pull/9775

**Comment by sflorean** [comment] 2021-03-05 12:40
Verified as fixed on Nightly 3/5 with Pixel 3 (Android 11).

**Closed by sflorean** 2021-03-05 12:40 UTC
Labels: Feature:Toolbar, needs:ac, 🐞 bug
