### ISSUE TITLE
FNX-12961 ⁃ Move tabs to main page (as it was before v5.2)

### ISSUE THREAD

**Issue by vrubleg** [mozilla-mobile/fenix#11956] opened 2020-06-25 15:14 UTC
### What is the user problem or growth opportunity you want to see solved?
Reduce unnecessary complexity by moving tabs back to main page.

### How do you know that this problem exists today?
A lot of angry users in the ticket #11833.

### Who will benefit from it?
Everybody.

**Comment by ekager** [comment] 2020-06-25 15:21
Thank you for your feedback. If you have specific feedback about the tabs tray or issues with it, feel free to open new issues (1 issue per bug/feature request). Closing this ticket because issues like this are not productive.

**Comment by phildenhoff** [comment] 2020-06-25 15:38
Hi @ekager, there are some reasonably clear explanations in thread #11833 as to why the new tab layout is a UX regression. I understand that GitHub issues aren't the best way to field this feedback — is there another best option other than email? There's a large number of vocal users who don't like this change, and for good reasons, and to deny their feedback seems like a missed opportunity.

**Comment by andreicristianpetcu** [comment] 2020-06-25 20:09
@phildenhoff each item in the list on that thread should be a separate issue. Some of them got fixed and some of them are new feature requests, not regressions.

**Comment by vrubleg** [comment] 2020-06-25 21:59
But this particular issue is about one feature only, about moving the tabs to the main page. At least as an option. So, the reason why it was closed is not valid.

**Comment by ekager** [comment] 2020-06-25 22:06
Maintaining two entirely different tab solutions would be very complex and a bad experience for everyone. We've done user research and dedicated a ton of UX time towards this change. The tabs tray UX changes are also setting the stage for future feature additions that make more sense in the tray. I understand you are unhappy, but please try to keep an open mind and help us fix the pain points you have with the tabs tray by filing specific feature requests or bugs.

**Comment by rokweom** [comment] 2020-06-28 12:44
I want to add some feedback too. The new tab is pretty bad. The tabs are unnecessarily big. With the old design I could pull the tab list down so that I could comfortably reach the top one. Now I have to reach almost to the top of the screen to reach the top tab, which is rather inconvenient. Also, when there's 7 tabs open (just enough to fill the whole list, at least on my phone; I guess that depends on phone size and DPI), when I try to scroll to the top of the list the tray closes instead, which is annoying as hell. "Close all tabs" function now takes two clicks instead of one. After opening a new tab, I have to manually tap the adress bar, whereas previously it opened automatically.

It wouldn't be all that bad if the tabs were smaller and if you could set the height to which the tray opens, allowing for more comfortable one-hand use.

**Comment by vrubleg** [comment] 2020-07-23 14:09
@ekager I gave it a chance. I forced myself to use it ever day for a month. It steel feels like the worst UX in comparison to mobile Chrome and Samsung Browser. I'm surprised that you can't see that it is so horrible. Just installed v5.1.1 and will be happy with the old interface for some time until it works for most websites.

**Comment by Dunexus** [comment] 2020-07-23 16:55
@vrubleg Could you tell what makes it that inconvenient for you ?
There is still some work in progress to make the new tab tray better, maybe your feedback could help.

**Closed** 2020-08-11 05:18 UTC
Labels: needs:triage
