### ISSUE TITLE
[Bug]Blocked media autoplay doesn't work properly 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5636] opened 2019-09-27 11:45 UTC
## Steps to reproduce
1. Navigate to: https://www.gq.com/story/manny-jacinto-favorite-cameras-clothes-fitness-gear
2. Navigate down the page until you reach a featured video  
3. Check whether the video start playing or not

### Expected behavior
Video autoplay should not start

### Actual behavior
Video autoplay starts

### Dependencies
- [x] ~~GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1585045~~
- [x] GV granular audio/video blocking: https://bugzilla.mozilla.org/show_bug.cgi?id=1577596

### Device information

* Android device: 
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly Build #12700627 from 27/9

### Notes
Somehow similar with #5634 
► Video
![20190927_142817](https://user-images.githubusercontent.com/51314259/65767015-4940a380-e135-11e9-856e-c804cb8c3362.gif)

**Comment by sv-ohorvath** [comment] 2019-09-30 09:42
Same behavior on 9gag.com or imgur.com gifs, songs from soundcloud, bmw.com (homepage or child pages), etc.

**Comment by hackel** [comment] 2019-09-30 15:03
Just to rub it in, this is the site I've been using to test and their video ads autoplay every time. Does `media.autoplay.allow-muted` have no effect in GV?  Tested on `\"Nightly 190926 18:01\"` (Those escaped quotes probably shouldn't appear in your Google Play listing!)

https://lifehacker.com/how-to-block-auto-play-videos-using-firefox-1833493848

**Comment by sblatz** [comment] 2019-09-30 15:48
@cpeterso is this a known issue in GV or does it seem like a Fenix problem?

**Comment by sblatz** [comment] 2019-09-30 16:46
GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1585045

**Comment by cpeterso** [comment] 2019-09-30 21:47
> @cpeterso is this a known issue in GV or does it seem like a Fenix problem?

This is probably a Gecko or GV bug. The GV team will investigate. Colin says desktop Firefox correctly blocks autoplay on the same site, suggesting this is a mobile-specific bug.

**Comment by neekless** [comment] 2019-10-01 01:28
I was able to get Autoplay to stop by setting `media.autoplay.default` to `5` in about:config. (do this and refresh the autoplaying page, it should no longer autoplay). But this setting doesn't stick; after fenix is forced closed or removed from recent apps it resets to `1`. According to the Firefox desktop `5` is block audio and video while `1` only blocks audio.

**Comment by sblatz** [comment] 2019-10-01 21:50
@vesta0 are you able to sync up with @cpeterso on the priority of this bug so we can eventually get this feature flag removed? :)

**Comment by vesta0** [comment] 2019-10-01 22:55
Done!

**Comment by jonalmeida** [comment] 2019-10-29 16:22
While this works as expected in Gecko, @vesta0 is this an API we want on GeckoView specifically so that mobile can turn it on/off for things like battery and data saving?

**Comment by cpeterso** [comment] 2019-10-29 16:46
This video was muted and Gecko allows muted videos to autoplay. So autoplaying this muted video is not a bug.

@vesta0 - Is Fenix's "Site permissions > Autoplay > Video and audio blocked" setting intended to block autoplay of both muted and unmuted videos (differing from desktop Gecko's autoplay policy)?

Blocking all video autoplay by default might be desirable on mobile because of bandwidth and battery consumption. Maybe the UI needs separate options for muted and unmuted video autoplay? Or options for autoplay only on Wi-Fi? We need a decision from PM and UX here.

https://bugzilla.mozilla.org/show_bug.cgi?id=1585045#c3

**Comment by vesta0** [comment] 2019-11-04 04:10
@cpeterso thanks for describing the current behaviour, and yes we want the recommended option to be block both video and audio autoplay, see #5163

**Comment by cpeterso** [comment] 2019-11-04 18:39
A clarification after I chatted with Vesta: Fenix wants to block autoplay of both muted and unmuted videos. They want to prevent autoplay of those annoying floating videos on news websites.

**Comment by cpeterso** [comment] 2019-11-04 18:47
The GV bug to extend GV's autoplay API to support blocking of muted video is https://bugzilla.mozilla.org/show_bug.cgi?id=1577596.

**Comment by cpeterso** [comment] 2019-11-04 19:21
Though the GV API is not ready, you can test this blocking behavior in Fenix Nightly now by manually setting GeckoView's `media.autoplay.default` about:config pref to level `5` (BLOCK_ALL).

**Comment by fluffyemily** [comment] 2020-01-21 11:47
GV issue resolved on 19th December

**Comment by vesta0** [comment] 2020-02-12 16:29
@pocmo looks like the GV issue was resolved, does this look ready for A-C to pick up?

**Comment by liuche** [comment] 2020-02-25 16:11
This landed in AC, so this will get fixed when we pick up a new AC version. However, need to decide if this should go into 4.0, which would require a new AC snapshot.

**Comment by Amejia481** [comment] 2020-02-25 19:52
@liuche should we give some time to test this on nightly, first?

**Comment by liuche** [comment] 2020-02-25 21:00
Talked to Arturo, and we can put this in 4.0 and FennecBeta, because it seems like an acceptable "beta" state for a feature (and don't think it will cause serious regressions like crashes).

**Comment by liuche** [comment] 2020-02-25 21:10
This change has landed in AC, so it should show up in the next snapshot.

**Comment by AndiAJ** [comment] 2020-02-26 15:08
Hi, **still reproducible** on the latest **`Nightly Build #20570604 from 02/26`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)

I've used the following websites:
https://codepen.io/ksy36/pen/abzEaEb
https://www.gq.com/story/manny-jacinto-favorite-cameras-clothes-fitness-gear
https://googlechrome.github.io/samples/muted-autoplay/
https://lifehacker.com/how-to-block-auto-play-videos-using-firefox-1833493848  

Odd behavior on gq.com,namely, when you visit the 1st time the video is blocked, if you refresh the page, or re-open it the autoplay kicks in.

► Video
![20200226-165531](https://user-images.githubusercontent.com/51314259/75357440-0d636300-58ba-11ea-82bf-8168b0fc62d8.gif)

I'll remove the QA needed label until further notice.

**Comment by Amejia481** [comment] 2020-02-26 19:51
This is happening because we have some limitations with what the GV API is offering us, we only can `allow` or `block` `autoplayAudible` / `autoplayInaudible`  

- `autoplayAudible` is everything that has sounds on it  (like video or songs)
- `autoplayInaudible` is everything that has moving pictures and **doesn't have sound on it** (Like animated images gif or **muted videos or songs**)

We can not differentiate between a muted videos/songs from an animated images (gif or others), for this reason @Baron-Severin and me thought that it will be a really bad user experience if we block animated images when block auto-play is on, as a result we decided  to [auto allow inaudible content](https://github.com/mozilla-mobile/fenix/blob/f99bad949e615b99857c6336de8fa2c573dea551/app/src/main/java/org/mozilla/fenix/utils/Settings.kt#L459), until we update the UI for inaudible or we got a new GV API that allows to do that.

**Comment by Amejia481** [comment] 2020-02-26 20:12
@vesta0 given the restriction listed above what should we do? 

Do we want to have the same control like desktop has ? For that we need some improvements on the underlying GV API.

<img width="203" alt="image" src="https://user-images.githubusercontent.com/773158/75382627-d6388600-58a8-11ea-8678-f43528c2b813.png">

So far this is the only caveat that we found muted videos or songs are going to play even though auto-play is set **block** video/audio, but they are not going to produce sound as they are muted. I think in the meanwhile this is not that bad

cc @snorp

**Comment by Amejia481** [comment] 2020-02-26 23:09
Holding off until we hear back on https://github.com/mozilla-mobile/fenix/issues/8503#issuecomment-591689367

**Comment by fluffyemily** [comment] 2020-04-21 11:41
This issue is still marked `needs:gv` despite all associated Bugzilla bugs marked resolved. Is any further platform work needed for this, or can we remove the GeckoView dependency?

**Comment by ekager** [comment] 2020-05-08 18:11
> Hi, **still reproducible** on the latest **`Nightly Build #20570604 from 02/26`** using the following devices:
> • Google Pixel 3a (Android 9)
> • Huawei Mate 20 Lite (Android 8.1.0)
> • Samsung Galaxy S7 (Android 7)
> • OnePlus A3 (Android 6.0.1)
> 
> I've used the following websites:
> [codepen.io/ksy36/pen/abzEaEb](https://codepen.io/ksy36/pen/abzEaEb)
> [gq.com/story/manny-jacinto-favorite-cameras-clothes-fitness-gear](https://www.gq.com/story/manny-jacinto-favorite-cameras-clothes-fitness-gear)
> [googlechrome.github.io/samples/muted-autoplay](https://googlechrome.github.io/samples/muted-autoplay/)
> [lifehacker.com/how-to-block-auto-play-videos-using-firefox-1833493848](https://lifehacker.com/how-to-block-auto-play-videos-using-firefox-1833493848)
> 
> Odd behavior on gq.com,namely, when you visit the 1st time the video is blocked, if you refresh the page, or re-open it the autoplay kicks in.
> 
> ► Video
> ![20200226-165531](https://user-images.githubusercontent.com/51314259/75357440-0d636300-58ba-11ea-82bf-8168b0fc62d8.gif)
> 
> I'll remove the QA needed label until further notice.

Testing on these sites, it seems like blocking autoplay is working on them now. 🤔 Could we retest?

**Comment by AndiAJ** [comment] 2020-05-11 12:33
Hi @ekager , I've re-checked this matter on the latest Nightly Build 200511 from 5/11 using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

✔️ codepen.io/ksy36/pen/abzEaEb
✔️ gq.com/story/manny-jacinto-favorite-cameras-clothes-fitness-gear
✔️ googlechrome.github.io/samples/muted-autoplay
❓ lifehacker.com/how-to-block-auto-play-videos-using-firefox-1833493848

After visiting lifehacker.com for the first time and accepting the Cookie policy the video seems to autoplay.
If you re-open the website the video doesn't autoplay.
► Video
![20200511-150029](https://user-images.githubusercontent.com/51314259/81561701-429d2e80-939c-11ea-9de5-8cbb770cf2d9.gif)
On the other hand, in some cases, each time you open lifehacker.com the Cookie policy banner gets displayed over and over again, even if you previously accepted the terms. (**happens on Chrome as well**)
When this happens, the video will always autoplay.

If you navigate to the website and don't accept the cookie policy the video doesn't start to autoplay.
► Video
![20200511-151314](https://user-images.githubusercontent.com/51314259/81561972-c2c39400-939c-11ea-82f0-e606de769e65.gif)

Please review and let me know how should we proceed. ☺️

**Comment by liuche** [comment] 2020-07-02 15:03
Since most of these sites are working now, and the remaining site also doesn't work with Chrome, it might be a site compat issue for this remaining site, so we will close this issue as fixed. Thank you for the testing and the details!

**Closed by liuche** 2020-07-02 15:03 UTC
Labels: Feature:Media, P1, S2, needs:ac, 🐞 bug

**Comment by ShatteredPixel** [comment] 2020-07-16 13:08
Videos are still auto-playing on Reddit mobile website even when the video auto-play is set to off
