### ISSUE TITLE
[Bug] Search Widget Causes Awesomebar to Become Bugged

### ISSUE THREAD

**Issue by jsilverstreak** [mozilla-mobile/fenix#16807] opened 2020-12-02 06:06 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Open tab bar
2. Go to android home
3. Use search widget.

### Expected behavior
Opens search menu and keyboard. Awesomebar buttons work every time.
### Actual behavior 
Opens last webpage and and the Awesomebar becomes less functional and no keyboard appears.

Touch animations play but some actions don't do anything. The privacy shield, site information, URL, tab button, downloads, history, bookmarks, synced tabs, settings, add to home screen, save to collection do not work.
Other buttons work along with the webpage.

To fix the app must either be swiped from recents, a new search attempt with the widget and an actual search (dismissing keyboard doesn't fix it), an add-on is opened, or long press new tab to open new tab.

When on blank home page(easily done using 0 tabs), hold new tab to open new private tab, it crashes. [Crash Report](https://crash-stats.mozilla.org/report/index/d8a1c885-e2e3-4ccf-be38-6d12d0201202)
### Device information

* Android device: LG G8 Android 10 ; Amazon Fire HD 10(2019) Android 9/Fire OS 7
* Fenix version: 84.0.0-beta.2 ; Nightly 201201 17:01 ; 83.1.0

**Comment by kbrosnan** [comment] 2020-12-02 17:39
Crash is 

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #20 in org.mozilla.fenix:layout/activity_home: Binary XML file line #20 in org.mozilla.fenix:layout/activity_home: Error inflating class fragment
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3316)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3455)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5371)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5279)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:57)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5330)
	at android.app.ActivityThread.access$3600(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7557)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
Caused by: android.view.InflateException: Binary XML file line #20 in org.mozilla.fenix:layout/activity_home: Binary XML file line #20 in org.mozilla.fenix:layout/activity_home: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #20 in org.mozilla.fenix:layout/activity_home: Error inflating class fragment
Caused by: java.lang.IllegalStateException: DialogFragment 0 doesn't exist in the FragmentManager
	at androidx.navigation.fragment.DialogFragmentNavigator.onRestoreState(DialogFragmentNavigator.java:6)
	at androidx.navigation.NavController.setGraph(NavController.java:13)
	at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:31)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:5)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:23)
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:42)
	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:2)
	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:1)
	at org.mozilla.fenix.HomeActivity.onCreateView(HomeActivity.kt:13)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:9)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:1)
	at org.mozilla.fenix.HomeActivity.onCreate(HomeActivity.kt:17)
	at android.app.Activity.performCreate(Activity.java:7812)
	at android.app.Activity.performCreate(Activity.java:7801)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3291)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3455)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5371)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5279)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:57)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5330)
	at android.app.ActivityThread.access$3600(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7557)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
```

**Comment by ebalazs-sv** [comment] 2020-12-14 15:23
Hi! We had tested this issue on multiple devices using the affected build but we were not able to reproduce it.

In order to be verified, @jsilverstreak could you please check if this issue is still reproducible on the latest Nightly build? Thanks!

I will remove the qa:needed label for now.

**Comment by jsilverstreak** [comment] 2020-12-14 20:34
The latest Nightly 201213 17:01 no longer has this bug.
It last shows up in in Firefox Preview 1.0.2050 (Build #<span></span>1) AC: 67.0.11, 50435d74 from [2020/12/10 ](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.debug.2020.12.10.latest/arm64-v8a)

**Comment by ekager** [comment] 2020-12-14 21:25
Thanks! Closing

**Closed by ekager** 2020-12-14 21:25 UTC
Labels: Feature:HomeScreen, Feature:Search, S2, b:crash, feature:SearchWidget, 🐞 bug
