### ISSUE TITLE
FNX-12882 ⁃ [Bug] White line on top of mobile YouTube after Firefox Preview update

### ISSUE THREAD

**Issue by liubomirwm** [mozilla-mobile/fenix#11883] opened 2020-06-24 10:55 UTC
## Steps to reproduce
Just start some song and scroll down and up.

### Expected behavior
No white line on top

### Actual behavior
White line on top exists

### Device information
* Android device: Motorola one macro
* Fenix version: 5.2.0 (Build #21701706)
AC: 46.0.0, bca4c5c91
GV: 78.0-20200612174529
AS: 60.0.0

![Screenshot](https://user-images.githubusercontent.com/16529989/85543086-69e54d80-b622-11ea-9ba2-5e7d1f4e3373.png)UNITO-UNDERSCORE!20200624-133821!

**Comment by hakkikaancaliskan** [comment] 2020-06-24 11:41
Duplicate of #11674

**Comment by ekager** [comment] 2020-06-24 19:28
Closing for #10598

**Closed** 2020-08-11 05:08 UTC
Labels: needs:triage, 🐞 bug
