### ISSUE TITLE
FNX-5566 ⁃ [Bug] Cannot download APKs and probably other file types

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#2283] opened 2019-05-05 10:38 UTC
## Steps to reproduce
Visit the taskcluster page with Fenix
https://tools.taskcluster.net/index/project.mobile.fenix.signed-nightly.nightly/latest

Click public/target.arm.apk
After download, try to open the file

### Expected behavior
I should be able to install the latest fenix version. It works in Fennec.

### Actual behavior
I get a Can't open file error.
![Screenshot](https://user-images.githubusercontent.com/922368/57192619-21a92e80-6f3b-11e9-8e12-73aaffaee954.png)UNITO-UNDERSCORE!20190505-133535!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Preview!
![Screenshot](https://user-images.githubusercontent.com/922368/57192622-253cb580-6f3b-11e9-8f4c-41f361962325.png)UNITO-UNDERSCORE!20190505-133542!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Preview!

### Device information
* Android device: OnePlus 5t
* Fenix version: May 4th build. It never worked so version is not important.
![Screenshot](https://user-images.githubusercontent.com/922368/57192630-3eddfd00-6f3b-11e9-8b4c-991f007134e2.png)UNITO-UNDERSCORE!20190428-135941!UNITO-UNDERSCORE!Settings!

**Comment by cadeyrn** [comment] 2019-05-05 10:47
Duplicate of #2109.

**Closed** 2020-08-11 14:40 UTC
