### ISSUE TITLE
FNX-14485 ⁃ [Bug] Toolbar becomes blank when opening plaintext file

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13304] opened 2020-08-05 13:01 UTC
## Steps to reproduce
I don't exactly know what this kind of file is called so please feel free to change the title if appropriate
Open https://ieeexplore.ieee.org/document/6672713/citations and click on "Cite This" button and then click on the "download" button
### Expected behavior
The text file opens 
### Actual behavior
Notice the url bar
![Screenshot_20200805-182822_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/89415638-c0799780-d749-11ea-9757-053e8c1861d5.png)

### Device information

* Android device: Asus zenfone
* Fenix version: Nightly 200803 06:07 (Build #22160613)
AC: 53.0.20200802130440, 8580c480b
GV: 81.0a1-20200801094810
AS: 61.0.10

**Comment by liuche** [comment] 2020-08-05 17:58
I'm not sure what these steps are: what is "any option", is it a specific link, or something else? Is this behind a paywall?

**Comment by s-ankur** [comment] 2020-08-05 18:02
@liuche sorry, I thought I had edited this. Is it better now?

**Comment by liuche** [comment] 2020-08-06 00:42
Ah, thank you! That makes sense.

**Comment by s-ankur** [comment] 2020-08-06 17:50
In both Android Chrome and Desktop Firefox, this opens up an about:blank page

**Comment by liuche** [comment] 2020-09-08 21:01
Looks like from investigation this is the same behavior on other browsers, so deprioritizing it for now.

**Comment by s-ankur** [comment] 2020-09-13 16:18
More troubling is that the shield icon disappears

**Comment by TrianguloY** [comment] 2020-09-13 16:58
That's the same bar as when opening an empty page with window.open()
https://trianguloy.github.io/githubPages/javascriptEval/javascriptEval.html?window.open()

**Comment by s-ankur** [comment] 2020-09-13 17:01
@TrianguloY When you do this in a custom tab, the browser opens and basically freezes. Should I open a new bug for this?

**Comment by TrianguloY** [comment] 2020-09-13 17:03
Oh, I didn't try with custom tabs, interesting. If it crashes...I guess it is a good idea to file a bug, yes.

**Comment by Mugurell** [comment] 2021-02-03 19:16
I think this is fixed now
- for https://github.com/mozilla-mobile/fenix/issues/13304#issue-673521662 after download an `about:blank` tab opens
- for https://github.com/mozilla-mobile/fenix/issues/13304#issuecomment-691696512 the browser opens but doesn't do anything

So I think this can be closed.
Can you please confirm?

**Comment by TrianguloY** [comment] 2021-02-03 21:44
I can confirm the window.open() function now displays an empty about:blank page. 

Strangely, if you scroll down on this page, the loading circle is shown but never disappears (it keeps 'loading' infinitely). It even stays there if you switch tabs by swiping on the bar, and to hide it you need to reload the page from the menu button.

Should I make a new issue with this?

**Comment by ekager** [comment] 2021-02-04 00:19
Yes, please open a new issue! Thank you!

**Closed by ekager** 2021-02-04 00:19 UTC
Labels: Feature:Toolbar, sourpatch, 🐞 bug

**Comment by Mugurell** [comment] 2021-02-04 06:49
> Strangely, if you scroll down on this page, the loading circle is shown but never disappears (it keeps 'loading' infinitely). It even stays there if you switch tabs by swiping on the bar, and to hide it you need to reload the page from the menu button.
> 
> Should I make a new issue with this?

Thank you for your support with this!
I've created https://github.com/mozilla-mobile/fenix/issues/17818 for what seems like a general issue with `about:blank`.
