### ISSUE TITLE
The Splash animation for Address Bar objects is bugged

### ISSUE THREAD

**Issue by thanuj10** [mozilla-mobile/fenix#7455] opened 2020-01-01 16:12 UTC
## Steps to reproduce
1. Open Fenix
2. Tap on any object on Address Bar (Eg - Https padlock)

### Expected behavior
The animation should be on the proper surface i.e the same surface as the object and render properly.

### Actual behavior
The splash animation is rendered behind the object creating a weird looking animation.

### Device information

* Android device: Nokia 6.1 Plus
* Fenix version: Latest Fenix Nightly Preview

**Comment by thanuj10** [comment] 2020-01-01 16:18
https://photos.app.goo.gl/Ne3pzQMPJqKbUj8F8
Adding Video for reference.

**Comment by kbrosnan** [comment] 2020-01-06 23:32
@thanuj10  Please provide a screenshot or video of what you are describing.

**Comment by ekager** [comment] 2020-01-07 06:28
Looks like #1648?

**Comment by thanuj10** [comment] 2020-01-08 15:30
@kbrosnan It's the same issue as @ekager mentioned.

**Comment by ekager** [comment] 2020-01-08 17:41
Okay closing as dupe of #1648

**Closed** 2020-02-14 05:00 UTC
Labels: 🐞 bug
