### ISSUE TITLE
FNX-12011 ⁃ [Bug] Pages that exceed the allocated space are displayed improperly when creating a collection

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#11139] opened 2020-06-02 13:19 UTC
## Steps to reproduce
1. Install Privacy Badger or Dark Reader add-on - a new tab is opened with information regarding the installed add-on.
1. Tap the tab counter.
1. Long tap the tab opened at step 1 and observe the layout of the moz-extension:// pages text.

### Expected behavior
The moz-extensions:// pages are displayed with"..." or blank space, they don't exceed the checkbox.

### Actual behavior
The moz-extensions:// pages are displayed with"..." or blank space, they exceed the checkbox.

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab A6 (Android 5.1.1), Xiaomi Mi4i (Android 5.0.2)
* Fenix version: 2/6 Nightly build, and Beta 5.1.0-beta.3

**Samsung Galaxy Tab A6:**
![Inkedlongname](https://user-images.githubusercontent.com/40694158/83523509-fb154880-a4ea-11ea-904e-694e2410227f.jpg)UNITO-UNDERSCORE!LI!

**Sony Xperia Z5 Premium:**
![sony](https://user-images.githubusercontent.com/40694158/83523506-f9e41b80-a4ea-11ea-8b9b-5ef1681aa825.png)

**Comment by mcarare** [comment] 2020-06-02 14:11
The problem is not related to extensions, but to any hostname that exceeds the allocated space.

**Comment by sv-ohorvath** [comment] 2020-06-04 12:59
Verified as fixed on Nightly 6/4.

**Closed** 2020-08-11 03:12 UTC
Labels: Feature:Collections, S3, eng:qa:verified, 🐞 bug
