### ISSUE TITLE
Browse other webpages when picture-in-picture mode is enabled

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#9947] opened 2020-04-15 07:46 UTC
### Why/User Benefit/User Problem

I have a mobile phone with a huge screen, I want to be able to browse other websites while watching videos in PIP mode

### Acceptance Criteria (how do I know when I’m done?)

Just like the desktop version of firefox

**Comment by jonalmeida** [comment] 2020-04-16 17:01
This was already discussed during the initial feature request and should be part of the next iteration of PiP. See https://github.com/mozilla-mobile/fenix/issues/2818#issuecomment-553130876.

GV API needed: https://bugzilla.mozilla.org/show_bug.cgi?id=1625012

**Comment by anotherus3r** [comment] 2021-08-10 20:06
Should we follow this issue or #6600 for this feature?

**Comment by kbrosnan** [comment] 2021-08-10 21:26
Duplicate of https://github.com/mozilla-mobile/fenix/issues/6600

**Closed by kbrosnan** 2021-08-10 21:26 UTC
Labels: feature request 🌟, needs:ac, needs:gv, Feature:Media, S2
