### ISSUE TITLE
[Bug]Tab selection checkmark is not displayed after checking synced tabs

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#19191] opened 2021-04-22 14:08 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open 2-3 pages.
2. Log in with a Firefox account on 2 devices.
3. Open tabs tray -> synced tabs.
4. While in tabs tray- go to normal tabs.
5. Perform a long tap in order to select the tabs.

### Expected behavior
Tabs are selected and the check is displayed above the links.

### Actual behavior
Tabs are selected but the "check" sign is not displayed. 

### Device information
* Device vendor / model and Android version: LG G7 Fit (Android 8.1), Huawei MediaPad M2 (Android 5.1.1).
* Firefox for Android version: Beta 89-b1, Nightly 4/22
 
![Screenshot_2021-04-22-10-58-50](https://user-images.githubusercontent.com/58466444/115728697-611def00-a38d-11eb-89ba-a3f999f0f45f.png)

**Comment by jonalmeida** [comment] 2021-04-22 16:06
Thanks! I can reproduce this bug, but it needs some investigation to know what's the cause.

**Comment by mcarare** [comment] 2021-04-23 15:12
@jonalmeida The issue can be reproduced even without signing in. If you switch from the normal tab to the sync tab and then back the issue reproduces every time. Closing and reopening tab tray restores normal behavior.

**Comment by jonalmeida** [comment] 2021-05-31 14:17
Added this to the kanban board because it may prove to be an issue later with new MR2 work.

**Comment by abodea** [comment] 2021-06-09 11:50
Verified as fixed on the latest Nightly 6/9 with Google Pixel 4 XL (11), OnePlus Nord (10).
Note that I was able to select and the checkmark was displayed without issues.

**Closed by abodea** 2021-06-09 11:50 UTC
Labels: Feature:SyncTabs, Feature:Tabs, S3, eng:qa:needed, 🐞 bug
