### ISSUE TITLE
FNX2-15273 ⁃ Optionally show top sites on url bar selection

### ISSUE THREAD

**Issue by seezer** [mozilla-mobile/fenix#12475] opened 2020-07-11 12:56 UTC
### What is the user problem or growth opportunity you want to see solved?
Easy access to top sites.
Currently accessing top sites requires at least 2 buttons: tab menu + new tab.
There is no way to navigate to a top site inside the current tab.

### How do you know that this problem exists today? Why is this important?
Disable 'show search shortcuts' and 'show search suggestions' in settings/search.

Then the screen only shows an empty space between url bar and keyboard. That had enough space for top sites in fennec and i'd appreciate it if it could be added again. Totally fine if it would be an opt-in.

### Who will benefit from it?
Everyone that doesn't use some of the above 'show' options.

**Comment by yoasif** [comment] 2020-08-28 06:49
Dupe of https://github.com/mozilla-mobile/fenix/issues/9118

**Comment by kbrosnan** [comment] 2020-08-28 22:16
Closing as a duplicate

**Closed by kbrosnan** 2020-08-28 22:16 UTC
Labels: needs:triage
