### ISSUE TITLE
[Bug] Scheduled system dark mode not respected

### ISSUE THREAD

**Issue by danielkillam** [mozilla-mobile/fenix#16843] opened 2020-12-03 17:09 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
When device switches between light and dark mode automatically based on time of day, firefox does not recognize it and stays in the previous mode.
### Expected behavior
Firefox should switch to match the system dark mode state.
### Actual behavior
Firefox does not toggle to the correct light/dark mode consistently. Sometimes swiping the app away causes it to work. Sometimes toggling system light/dark mode manually helps Firefox understand. Sometimes I have to force close the app to get it to swap.
### Device information
* Android device: Samsung Galaxy Note 20 Ultra
* Fenix version: 84.0.0-beta.2 (Build #2015776763)

**Comment by s-ankur** [comment] 2020-12-05 05:55
Hello, I think this would be a duplicate of https://github.com/mozilla-mobile/fenix/issues/11372

**Comment by danielkillam** [comment] 2020-12-05 23:20
Oh yes, it appears you're right. Hope it gets fixed someday

--
Dan Killam
Postdoctoral Researcher
Biosphere 2
Pronouns: He/him
https://dantheclamman.blog

________________________________

**Comment by danielkillam** [comment] 2020-12-05 23:20
Oh yes, it appears you're right. Hope it gets fixed someday.

**Comment by ekager** [comment] 2020-12-09 22:15
Closing for #11372

**Closed by ekager** 2020-12-09 22:15 UTC
Labels: needs:triage, 🐞 bug
