### ISSUE TITLE
download of protected files fail

### ISSUE THREAD

**Issue by mokraemer** [mozilla-mobile/fenix#15874] opened 2020-10-13 14:49 UTC
## Steps to reproduce
clicking on a pdf with target="blank" opens a new window, shows download dialog with size, but download fails afterwards
### Expected behavior
before the rewrite of firefox mobile, the download dialog was shown, the cookie is passed for the (protected) download script and the download finishes.
### Actual behavior
for some time "Download in progress" is shown before it fails (>6min)
### Device information

* Android device: Nokia 5 (TA-1053), Android 9
* Fenix version: ????

Firefox 81.1.4

**Comment by Amejia481** [comment] 2020-10-13 17:50
@mokraemer thanks for the report could you share the link that you were trying with? If it's not much trouble could you try on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)? We did some improvement on nightly hopefully this issue is fixed there.

**Comment by Amejia481** [comment] 2020-11-02 16:52
@mokraemer we did some improvement to downloads in [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix). Would you mind trying on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) to see if it's fixed for you? Hopefully it will work for you too :)

I will also ask the QA team to test a they have a wide range of devices.

**Comment by silvant** [comment] 2020-11-06 18:34
Yes, seems fixed in nightly

**Comment by Amejia481** [comment] 2020-11-17 21:11
QA team could you please help us to verify if this issue is already fixed.

**Comment by ebalazs-sv** [comment] 2020-11-18 09:42
I had tested this issue on the RC 81.1.4 build from 10/07 with the following devices:
- Motorola Moto G6 (Android 8);
- Google Pixel 2 (Android 9);
- Huawei P9 Lite (Android 7);
- Nexus 5 (Android 6.0.1);
- Nokia 6 (Android 7.1.1)

downloading pdf files from https://mccs.nl/algemene-voorwaarden/ and was not able to reproduce the issue.

@mokraemer @silvant Could you please provide the link that you where trying with so we can verify this issue? Thanks!

I will remove the qa:needed for now.

**Closed** 2021-02-01 18:56 UTC
Labels: Feature:Download, 🐞 bug
