### ISSUE TITLE
[Bug] "Desktop Site" toggle remains on while the page is stuck on Mobile Mode after switching apps

### ISSUE THREAD

**Issue by Sugarteeth** [mozilla-mobile/fenix#20214] opened 2021-07-01 09:57 UTC
There is a bug with the "Desktop Site" toggle, that requires me to close and reopen a tab to fix.

Steps to reproduce:
Go to any site with a mobile version, (fandom.com was where the bug was first noticed) and toggle on "Desktop Site"
Once the page is loaded, switch to another application using the navigation bar
Switch back to Firefox

Expected behavior:
The site should still be in Desktop Mode, and allow you to toggle off to return to Mobile Mode

Actual behavior:
The tab is now stuck in Mobile Mode, but with the "Desktop Site" toggle still on. Pressing the toggle once again (and every time afterward) will do nothing but reload the page, still stuck in the On position, and the page stuck in Mobile Mode. This can only be fixed by closing the tab completely, and reopening it again. Pages visited later in the same tab though navigation or going back are still affected.

Device information:
Samsung Galaxy A01

88.1.3 (Build #2015808505)
AC: 74.0.13, ccf500706
GV: 88.0.1-20210504152106
AS: 74.0.1

**Comment by Sugarteeth** [comment] 2021-07-01 10:05
After more testing, it appears that some websites are immune to getting stuck in Mobile Mode, notably, the Firefox Support site. It's possible this has something to do with returning to a very laggy webpage.

**Comment by Nickoriginal** [comment] 2021-07-01 12:44
Your Firefox is not actual, update it to 89.1.1 on [GitHub](https://github.com/mozilla-mobile/fenix/releases/tag/v89.1.1) or in [Google Play](https://play.google.com/store/apps/details?id=org.mozilla.firefox) first.

**Comment by Sugarteeth** [comment] 2021-07-01 23:14
> Your Firefox is not actual, first update it to [89.1.1](https://www.mozilla.org/firefox/android/89.0/releasenotes/) on [GitHub](https://github.com/mozilla-mobile/fenix/releases/tag/v89.1.1) or in [Google Play](https://play.google.com/store/apps/details?id=org.mozilla.firefox), there is a chance, that your bug would be fixed automatically.

I have updated! Thank you. Unfortunately, the problem persists into the updated version.

**Comment by Nickoriginal** [comment] 2021-07-02 04:47
I'm sorry, I can't reproduce it on my device (Samsung Galaxy A20s, Android 10). Fandom.com works correctly for me after skipping and resuming in "Desktop mode" and allows me to return to "Mobile mode"

**Comment by SoftVision-LorandJanos** [comment] 2021-07-02 09:19
Hi @Sugarteeth ! Thank you for your report! I'm not able to reproduce it either, and I tried to cover as many devices/android versions and FF versions as I could. Could you maybe see if it reproduces on the latest Nightly? And maybe see if it still happens after you clear your data on the release version (if you can). Thank you!
Tested on Release 88.1.3 (Build #2015808505) and on the latest Nightly (91.0a1 2021-07-02T05:07:53.859).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0).

**Comment by Nickoriginal** [comment] 2021-07-02 12:41
Do you can record your phone's screen with issue demonstration using screen recorder and send it here?

**Comment by TrianguloY** [comment] 2021-07-03 09:03
Duplicate of https://github.com/mozilla-mobile/fenix/issues/15352 which contains reliable steps and a video to demonstrate it (with an old version but just tested and the bug is still present)

**Comment by Nickoriginal** [comment] 2021-07-04 17:42
@TrianguloY 
Thanks!

**Comment by SoftVision-LorandJanos** [comment] 2021-07-05 10:17
Since the issue is covered in the ticket mentioned above, I'm going to close this one. Thank you!

**Closed by SoftVision-LorandJanos** 2021-07-05 10:17 UTC
Labels: Feature:Browsing, S3, needs:triage, qa-triaged, 🐞 bug
