### ISSUE TITLE
[Bug]Tabs tray-Bookmark page is not working

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#19192] opened 2021-04-22 14:32 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open 2-3 pages.
2. Open tabs tray and perform a long tap on one page.
3. Open 3dot menu.
4. Tap on "Bookmark".

### Expected behavior
The "Bookmark saved! VIEW" snack bar is displayed.

### Actual behavior
The snackbar is not displayed and the page is not added to bookmarks.

### Device information
* Device vendor / model and Android version: LG G7 Fit (Android 8.1), Huawei MediaPad M2 (Android 5.1.1)
* Firefox for Android version: Nightly 4/22, 89.0.0-beta.1

**Comment by jonalmeida** [comment] 2021-04-22 16:07
Duplicate of https://github.com/mozilla-mobile/fenix/issues/19090

**Closed by jonalmeida** 2021-04-22 16:07 UTC
Labels: Feature:Bookmarks, Feature:Tabs, S3, needs:triage, 🐞 bug
