### ISSUE TITLE
[Bug] [a11y] Several options from the settings menu are read twice

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#6994] opened 2019-12-06 09:58 UTC
## Steps to reproduce
1. Turn talkback on.
2. Go to Firefox Preview in the settings section.
3. Using talkback gestures navigate to the bottom of the menu.
4. Listen to the "About", "Help" and "Rate on Google Play" options. 

### Expected behavior
The "About", "Help" and "Rate on Google Play" options should only be read once.
### Actual behavior
The "About", "Help" and "Rate on Google Play" options are read twice.
### Device information

* Android device: Pixel 3a XL (Android 10), HTC Desire 820 (Android 6.0.1), LG G7 Fit (Android 8.1)
* Fenix version: 3.0.0-beta.3 (Build #13392157) 12/5

**Comment by mcarare** [comment] 2019-12-09 16:26
Note: After scrolling through the preference list other items begin to have repeated content descriptions. It appears that recreating the items sets off this weird behaviour

**Comment by mcarare** [comment] 2019-12-17 16:22
This also occurs with collections on home screen and any other item in a `RecyclerView`.

**Comment by sblatz** [comment] 2020-01-29 11:11
Some of these menu items are not repeated (see Logins and passwords). Let's copy what those preferences are doing to fix these items!

**Comment by mcarare** [comment] 2020-01-29 12:16
> Some of these menu items are not repeated (see Logins and passwords). Let's copy what those preferences are doing to fix these items!

IMO the problem is with the RecyclerView, not with the items themselves.

**Comment by softvision-miralobontiu** [comment] 2020-10-20 08:00
I was not able to reproduce this issue on the latest Nightly build from 10/20 with Samsung Galaxy Tab S6 (Android 10).
I'll close this issue.

**Closed by softvision-miralobontiu** 2020-10-20 08:00 UTC
Labels: Feature:Settings, P2, b:a11y, help wanted, 🐞 bug
