### ISSUE TITLE
FNX-4351 ⁃ [Bug] Remove dividers

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10525] opened 2020-05-08 16:13 UTC
## Steps to reproduce
1. Enable tab tray
1. Open some tabs
1. Open tab 3rd position from top
1. Open tab tray

### Expected behavior
1. Divider is across the width of the screen or at least centered between items (not offset to one side)
1. The open tab highlight should be the same height across its length, not thicker on one end and  thicker on the other. 

### Actual behavior
Divider seems to avoid tab thumbnail. Tab highlight looks weird because the height is inconsistent across its length. 

![Screenshot](https://user-images.githubusercontent.com/152493/81425276-470be200-9125-11ea-87f5-eb5f5f402a62.png)UNITO-UNDERSCORE!2020-05-08-12-06-11!

### Device information
* Android device: Moto G
* Fenix version: latest nightly

**Comment by LaurentiuApahideanSV** [comment] 2020-05-12 11:55
I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 200512 (Build #21330603).

Devices:
Huawei MediaPad M3 lite 10 (Android 7.0)

**Comment by topotropic** [comment] 2020-06-02 13:06
Thanks for the feedback – I'd suggest we remove the dividers.

**Comment by liuche** [comment] 2020-06-02 15:49
@boek would this be a good bug for @person808? Could start working in the tabs tray team too.

**Comment by darkwing** [comment] 2020-06-04 19:49
@liuche Yes, @person808 would be an awesome choice! I think it's basically just reverting these two:

- https://github.com/mozilla-mobile/fenix/pull/10590
- https://github.com/mozilla-mobile/fenix/pull/10325

**Comment by person808** [comment] 2020-06-04 21:01
I assume point #2 doesn't apply anymore since the tab tray looks different now.

**Comment by LaurentiuApahideanSV** [comment] 2020-06-09 11:38
Verified as fixed on Firefox Preview Nightly 200606 (Build #21610607) using a Huawei MediaPad M3 (Android 7.0).

**Closed** 2020-08-11 00:58 UTC
Labels: Feature:Tabs, S2, Skittle, eng:qa:verified, 🐞 bug
