### ISSUE TITLE
[Bug] Disabling safebrowsing in about:config is not possible.-

### ISSUE THREAD

**Issue by Maji78** [mozilla-mobile/fenix#15237] opened 2020-09-20 09:54 UTC
## Steps to reproduce
Open Firefox Nightly
Write about:config
Change these strings:
-browser.safebrowsing.malware.enabled from true to false
-browser.safebrowsing.pishing.enabled from true to false
Restart browser
Those strings are true again

### Expected behavior
Those strings would be false

### Actual behavior
They changed as soon as you restart the app.
Nevertheless, other strings remain changed without any problem but only those ones don't work
### Device information

* Android device: Lenovo P2 with LineageOS based on Android 10
* Fenix version: Nightly version 200919 06:03

**Comment by cadeyrn** [comment] 2020-09-20 13:28
Duplicate of #14163.

**Comment by Maji78** [comment] 2020-09-20 18:33
> Duplicate of #14163.

Thanks for the answer.
Is it scheduled to add this possibility?

**Comment by Amejia481** [comment] 2020-09-21 13:58
I think this is happening because [we are overriding ](https://github.com/mozilla-mobile/android-components/blob/36c9570835a8f39bea1a04d185fc45b4a3503ec3/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt#L507)the save browsing values from `about:config`

**Comment by Amejia481** [comment] 2020-09-21 13:59
I'm not sure if we have a way to get the `about:config` values from GeckoView

**Comment by kbrosnan** [comment] 2020-09-24 07:40
Closing as a duplicate

**Closed by kbrosnan** 2020-09-24 07:40 UTC
Labels: needs:triage, 🐞 bug
