### ISSUE TITLE
Toolbar misbehaving

### ISSUE THREAD

**Issue by SureshCBE** [mozilla-mobile/fenix#17268] opened 2020-12-31 06:25 UTC
When keyboard disappeared toolbar is not going to the bottom of the screen instead it is stuck in middle.
![Screenshot_20201231-113530](https://user-images.githubusercontent.com/66856125/103397549-e96a5100-4b5e-11eb-8b3a-8b87050d93a6.png)
![Screenshot_20201231-113530](https://user-images.githubusercontent.com/66856125/103397560-ee2f0500-4b5e-11eb-832a-4050b6c18c85.png)

### Device information : Nokia 4.2

* Android device: 10
* Fenix version: 84.1.2

**Comment by Mugurell** [comment] 2021-02-17 17:22
@SureshCBE Does this still reproduces for you?
I think I saw it also in the past but now I cannot reproduce it on the latest Nightly.

**Comment by sflorean** [comment] 2021-05-28 18:17
Couldn't reproduce it on the latest Nightly with Samsung Note 10 (Android 11) and Pixel 3 (Android 11). Closing this based on the lack of extra info. Please reopen if the issue reappears.

**Closed by sflorean** 2021-05-28 18:17 UTC
Labels: Feature:Toolbar, 🐞 bug
