### ISSUE TITLE
FNX2-15450 ⁃ [Bug] App link redirecting to Play Store, rather than to installed app

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/fenix#12746] opened 2020-07-20 21:00 UTC
Originally reported @ https://github.com/webcompat/web-bugs/issues/55620 by @hakkikaancaliskan

STR:

1. Have https://play.google.com/store/apps/details?id=trendyol.com&hl=en_US installed already
1. visit https://ty.gl/j08whdcd

Expected: Fenix handles the intent correctly and opens the content in the already installed app
Actual: Fenix navigates to the Play Store, even though the app is installed

Chrome Mobile has expected behavior.

(this was reported from 80 / 20200717093907)

**Comment by hakkikaancaliskan** [comment] 2020-07-20 22:02
@ekager you added open in app label but i wanna add an info.
When I turn off open links in apps option, it opens play store anyway, always opening it.

**Comment by hakkikaancaliskan** [comment] 2020-08-04 20:54
https://github.com/mozilla-mobile/android-components/pull/7971#issuecomment-668812822

**Comment by rocketsroger** [comment] 2020-08-14 16:57
Looks like the issue here is the app is not designed to open the redirected intent from the URL.  App links' assumption that if a targeted intent failed to open the app is not installed is wrong.  I'll fix this by removing this assumption.  If a targeted intent failed to open in an app but the app is installed, app links will use the fallback URL because there's no work around for this app issue.

**Comment by rocketsroger** [comment] 2020-08-19 13:52
Confirmed with `Nightly 200819 06:01` this is now fixed.  Please verify, thanks

**Comment by hakkikaancaliskan** [comment] 2020-08-19 14:05
Fixed for me too.

**Comment by abodea** [comment] 2020-08-19 14:37
Verified as fixed on the latest **Nightly 8/19** with **Google Pixel 4 XL (11).**
![20200819-173359](https://user-images.githubusercontent.com/42831109/90648796-a6a87c00-e242-11ea-9395-7ef45ef727cc.gif)

**Closed by abodea** 2020-08-19 14:37 UTC
Labels: Feature:OpenInApp, S2, eng:qa:needed, sourpatch2, 🐞 bug
