### ISSUE TITLE
[Bug] Push notifications not working 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#18809] opened 2021-04-05 23:55 UTC
I don't really know why in fenix both stable and nighlty push notifications never work.
I ve ZERO problem with Samsung internet.
I tested this url for example:
https://gauntface.github.io/simple-push-demo/
and in fenix stable did not worked in nighlty even worse after clicking the switch the page stays blank!

**Comment by sflorean** [comment] 2021-04-06 07:20
Thanks for filing this! I will close this as duplicate of #18045, and your scenario will be tested when the issue is fixed.

**Closed by sflorean** 2021-04-06 07:20 UTC
Labels: needs:triage, 🐞 bug
