### ISSUE TITLE
No More Private Sync Server (due to removing about:config -> identity.sync.tokenserver.uri)

### ISSUE THREAD

**Issue by metal450** [mozilla-mobile/fenix#14595] opened 2020-09-01 22:32 UTC
As has been documented in many places recently, the "new and improved" Firefox on Android has removed about:config.  I won't re-state all the very well-thought-out arguments [here](https://github.com/mozilla-mobile/fenix/issues/14100) and [here](https://www.reddit.com/r/firefox/comments/i51k0q/mozilla_could_turn_on_about_config_and_have/g0n9nn0/) for why this dramatically cripples what was, just a couple months ago, by far and away the best & most flexible browser out there.  Since the 1st issue was promptly shutdown & the [remaining thread](https://github.com/mozilla-mobile/fenix/issues/7865) blocks end users from participating in the discussion, I'll just focus here on the biggest regression that faces me personally:

Removing about:config seems to leave no way to set identity.sync.tokenserver.uri, which in turn means that syncing via my private sync server is now broken.  The ability to sync via a self-hosted server was the sole reason I began using Firefox instead of Chrome.

What alternative has been provided to set your self-hosted sync server URL, now that the clean/easy way of configuring it via about:config is no longer available?

**Comment by kbrosnan** [comment] 2020-09-01 22:37
This exists in the hidden settings. Go to the about Firefox page in the settings and tap the Firefox icon 5 times.

Closing as a duplicate of #3762

**Closed by kbrosnan** 2020-09-01 22:37 UTC
Labels: needs:triage, 🐞 bug

**Comment by metal450** [comment] 2020-09-01 22:59
Thanks for the quick reply.  Unfortunately, doesn't seem to work.  With the setting set that way & then re-paired with the desktop, it never succeeds to sync as it did immediately prior to the update (after trying to sync, it shows "Last synced: Dec 31, 1969).  Neither the server nor any other clients were updated.  I also have a Titanium Backup prior to the update; reverting makes sync work fine again, updating to the new version & configuring with the same URL doesn't.  I wasn't aware of this hidden setting - but unfortunately even with that, it doesn't appear to be working as it had prior to the update.

**Comment by kbrosnan** [comment] 2020-09-01 23:08
I would look at https://github.com/mozilla-mobile/fenix/issues/3762#issuecomment-682235250 as well as some of the later comments about making sure you are running recent versions of the Sync server.

**Comment by metal450** [comment] 2020-09-01 23:14
I'm running syncserver 1.8.0, which is the most recent tagged release: https://github.com/mozilla-services/syncserver/tags

**Comment by metal450** [comment] 2020-09-01 23:19
Based on https://github.com/mozilla-services/syncserver/issues/224, it looks like the fix is to set identity.sync.useOAuthForSyncToken.  Which seems like it's getting back to the original issue: now that there's no about:config, there's no way to even try setting options such as these...?
