### ISSUE TITLE
[Bug]: Address bar wrongly displaying web search query

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#21472] opened 2021-09-23 13:01 UTC
### Steps to reproduce

Make a web search from  address bar
Navigate to a non-existing URL via the address bar
Observe the error page
Tap the address bar; notice how the address bar is still showing the search query we just navigated away from

### Expected behaviour

Just show the URL of the page we are on ,despite it being nonexistant, malformed or any form of erroneous status

### Actual behaviour

Address bar does wrongly show the search query of the previous page, which would be the default web search engine.  The actual URL of the page (in this case, the fake "about" page is shown as a suggestion).
See screencast

https://user-images.githubusercontent.com/76437842/134511820-fe69148e-669f-4acc-9147-114cccb89ccb.mp4

### Device name

Samsung Galaxy OneUI 3.1

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17994)

**Comment by LaurentiuApahideanSV** [comment] 2021-09-24 10:23
I can confirm the issue is reproducible on the latest Firefox Preview Nightly 2021-09-23.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by marcel263** [comment] 2022-03-24 07:34
this is not fixed

**Comment by marcel263** [comment] 2022-11-23 07:57
still not fixed

**Comment by csadilek** [comment] 2023-01-16 20:31
This was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1799679.

**Closed by csadilek** 2023-01-16 20:31 UTC
Labels: 🐞 bug, needs:triage, qa-triaged
