### ISSUE TITLE
[Bug] Trackpad clicks and scrolling do not work in ChromeOS

### ISSUE THREAD

**Issue by temporary0211** [mozilla-mobile/fenix#16509] opened 2020-11-11 17:07 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)
Does not recognize the trackpad tap nor do they scroll using the trackpad scroll gesture. 
## Steps to reproduce
Go to site (e.g. Vanguard.com). Using trackpad navigate to a fillable box and tap (not click) on the trackpad. Perform two-finger drag to scroll website. 
### Expected behavior
Field becomes active.  Webpage contents scroll.
### Actual behavior
Trackpad tap is ignored and field does not become active.  
Contents of webpage are highlighted and scrolling does not occur.
### Device information
Using a Pixel Slate with the Google Pixel Slate keyboard running ChromeOS Version 86.0.4240.183 (Official Build) (64-bit)
* Android device: ?
* Fenix version: 83.0.0-beta.4

**Comment by kbrosnan** [comment] 2020-11-12 18:54
Duplicate of #3708

**Closed by kbrosnan** 2020-11-12 18:54 UTC
Labels: needs:triage, 🐞 bug
