### ISSUE TITLE
Allow home screen shortcut even for websites with progressive apps

### ISSUE THREAD

**Issue by ricardoV94** [mozilla-mobile/fenix#16935] opened 2020-12-09 07:12 UTC
### What is the user problem or growth opportunity you want to see solved?

Right now it is not possible to just add a shortcut to the home screen for websites with progressive apps (e.g. Instagram).

### Why is this important?

This is important because users might want to explicitly benefit from Firefox advantages over apps (extensions, copy/paste and sharing functionality, etc), and the current behavior weakens this opportunity.

**Comment by Dunexus** [comment] 2020-12-09 10:14
See https://github.com/mozilla-mobile/fenix/issues/7758

**Comment by kbrosnan** [comment] 2020-12-09 19:01
Closing as a duplicate of #7758

**Closed by kbrosnan** 2020-12-09 19:01 UTC
Labels: Feature:Shortcuts, feature request 🌟, needs:triage
