### ISSUE TITLE
FNX-4980 ⁃ [Bug] Address bar resets when putting Fenix on the background

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#1366] opened 2019-04-03 22:09 UTC
## Steps to reproduce
* Type something on the Address bar but don't navigate anywhere
* Tap on the Android Home button to make Fenix go on the background
* Open Fenix again

### Expected behavior
* The address bar contains the text that you typed
Works on Fennec Nightly, Chrome

### Actual behavior
* The address bar is empty

### Device information
* Android device: Samsung S10e
* Fenix version: 1.0.1914

**Comment by ekager** [comment] 2019-04-03 22:11
Caused by #1323

**Comment by kbrosnan** [comment] 2019-04-27 04:11
Even with #1323 fixed this is still an issue.

**Comment by dector** [comment] 2019-05-25 00:04
Will check it.

**Comment by dector** [comment] 2019-05-28 00:05
This issue has two cases:

1. Activity stays the same. (_Fixed in #1366_).
2. Activity was recreated. (_Requires saving view state implementation_).

**Comment by sblatz** [comment] 2019-05-30 21:11
@dector is working on this. I'll own making sure it gets landed! 

Currently blocked on: https://github.com/mozilla-mobile/android-components/pull/3187

**Comment by sv-ohorvath** [comment] 2019-06-10 13:54
Verified as fixed on the 6/8 build.

**Closed** 2020-08-11 11:31 UTC
Labels: Feature:Toolbar, Release Blocker, eng:qa:verified, good first issue, needs:ac, 🐞 bug
