### ISSUE TITLE
[Bug]WebAuthn with Yubikeys and in general U2F/FIDO2 devices does not work anymore since update to Firefox Daylight

### ISSUE THREAD

**Issue by mlsxlist** [mozilla-mobile/fenix#15824] opened 2020-10-10 13:07 UTC
## Steps to reproduce
Second Factor authentication with Yubikey does not work anymore since Firefox was updated to Firefox Daylight in August 2020. 

1. Visit https://demo.yubico.com/webauthn-technical/ with Firefox on Android
2. The site returns: **Your browser is not supported**
3. Try the same with Firefox Android before the Daylight update, Firefox Desktop, Google Chrome mobile, or Google Chrome.
4. When asked tap the key and the demo page returns **Registration completed!**

### Expected behavior
It should be possible to use Yubikey or in general FIDO2 devices to authenticate to Websites as it is possible with Firefox Android before the Daylight update, Firefox Desktop, Google Chrome mobile, or Google Chrome.

### Actual behavior
With the Firefox Daylight update support for WebAuthn got broken.

### Device information
* Android device: Huawei P30 PRO, Android 10
* Fenix version: 81.1.4

**Comment by cadeyrn** [comment] 2020-10-10 13:52
Duplicate of #1340.

**Closed** 2020-10-10 14:38 UTC
Labels: needs:triage, 🐞 bug
