### ISSUE TITLE
Undo close tab places tab at top of list

### ISSUE THREAD

**Issue by bgibney3** [mozilla-mobile/fenix#14475] opened 2020-08-30 03:03 UTC
Observed:

Undo of a tab closed by swiping does not restore the tab to its original position in list of open tabs.  Instead, the tab pops to the top of the list.

Expected:

Tab is restored to its original place in list of opened tabs.

Build #2015758619

**Comment by kbrosnan** [comment] 2020-08-30 08:20
Closing as a duplicate of #10986

**Closed by kbrosnan** 2020-08-30 08:20 UTC
Labels: needs:triage
