### ISSUE TITLE
Camera permission dont ask option to choose from front or back camera [Bug]

### ISSUE THREAD

**Issue by girishkuniyal** [mozilla-mobile/fenix#14106] opened 2020-08-24 08:30 UTC
## Steps to reproduce
Visit any online video chat service. and start video call/conference

### Expected behavior
It should ask permission for a camera and microphone with an option for choosing a front/back camera on phone. which is available in the previous version of firefox android.

### Actual behavior
It Only asks for a camera and microphone permission but doesn't give the option to choose which camera (front or back).

### Device information

* Fenix version: 79.0.5

**Comment by mcarare** [comment] 2020-08-24 09:40
Closing as duplicate of https://github.com/mozilla-mobile/fenix/issues/10748. @girishkuniyal Thank you for your report!

**Closed by mcarare** 2020-08-24 09:40 UTC
Labels: needs:triage, 🐞 bug

**Comment by rmganim2firefox** [comment] 2020-08-29 00:43
When will this be fixed and if it is already done how do you get the option to choose which camera front or back?

**Comment by cadeyrn** [comment] 2020-10-25 10:29
#10748 only changed the used camera from back to front and didn't adress this issue at all. In the meantime a new issue was opened. You can follow #15993 for your original request.
