### ISSUE TITLE
[Bug] Snackbars do not appear at the same height

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#14984] opened 2020-09-11 14:15 UTC
## Steps to reproduce
1. Open a website, e.g. https://www.mozilla.org/en-GB/
2. Long-press on a link an tap on _Open link in new tab_
3. Long-press on a link an tap on _Open link in private tab_

### Expected behavior
The snackbars are displayed at the same height.

### Actual behavior
The snackbar are displayed at different heights, see the gif. Note: this also shows issue 14982

![missing-snackbars-fixed-bottom-t](https://user-images.githubusercontent.com/42788925/92935080-9a31d080-f448-11ea-8192-3bec359d4896.gif)

### Device information

* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version: 
Nightly 200911 06:01 (Build #2015763249)
AC: 58.0.20200908130811, 52ac53ba1
GV: 82.0a1-20200907094115
AS: 61.0.13

**Comment by ebalazs-sv** [comment] 2020-11-06 09:54
This issue is not reproducible on Nightly 201106 GV 84 from 11/6 with Motorola Moto G6 (Android 8).
Also, the similar issue https://github.com/mozilla-mobile/fenix/issues/14982 is verified as fixed.
Due to these finding, I will close this issue.

**Closed by ebalazs-sv** 2020-11-06 09:54 UTC
Labels: needs:triage, 🐞 bug

**Comment by hwinnemoe** [comment] 2020-11-15 12:11
@ebalazs-sv Thinking about this again I guess it's just the longer text for the "Open link in private tab"-snackbar that enlarges the snackbar towards the top of the viewport while keeping the same anchor position for the lowest part of the snackbar.
