### ISSUE TITLE
[Bug] Undo Closed tabs open at the bottom of tab list

### ISSUE THREAD

**Issue by axeltrinidade** [mozilla-mobile/fenix#16194] opened 2020-10-26 21:29 UTC
### Steps to reproduce
Close a tab. 
Reopen by clicking undo from snack bar. 

### Expected behavior
Tab reopens on the top of tab list. (new tab position)

### Actual behavior
Tab reopens at the bottom of tab list. (oldest tab position) 

### Device information

* Android device: Oneplus 7, Android 10
* * Fenix version: 83.0.0-beta.1 (Build #2015771051)

**Comment by AndiAJ** [comment] 2020-10-27 07:13
Dupe of #10986

**Closed by AndiAJ** 2020-10-27 07:13 UTC
Labels: needs:triage, 🐞 bug

**Comment by BobVul** [comment] 2020-10-28 14:57
Is it really a dupe when it's worse behaviour (a regression) from a recent change?

While the long term fix may be to introduce reordering or restore in the original position, as suggested in the linked issue months ago, the change from top (newest) to bottom (oldest) happened in a very recent beta update.

If the long term fix isn't immediately possible, it would be good to at least fix the recent regression and have tabs restore to the top (newest) position. 

Note this is also inconsistent with restoring tabs via history, which does use the top (newest) position.
