### ISSUE TITLE
[Bug] Gray bar at the top of the screen in horizontal fullscreen mode

### ISSUE THREAD

**Issue by akveet** [mozilla-mobile/fenix#18564] opened 2021-03-20 11:26 UTC
## Steps to reproduce
Go to youtube.com
Open any video
Enter the fullscreen mode
Rotate to horizontal position

### Expected behavior
The video occupies all the vertical space available

### Actual behavior
There is a gray bar at the top of the screen
![Screenshot_2021-03-20-13-25-09-364_org mozilla fenix](https://user-images.githubusercontent.com/47448925/111867905-baa29080-897f-11eb-8d78-fe0d9a461f35.jpg)

### Device information

* Xiaomi redmi note 10 pro Android version: 11
* Firefox for Android version: Nightly 210319 20:42 (Build #2015799651)
 
The issue is only present in nightly. In firefox for Android beta there is no such problem.

**Comment by hakkikaancaliskan** [comment] 2021-03-20 16:00
Related to #18546

**Comment by Mugurell** [comment] 2021-03-22 06:45
Seems like a regression of https://github.com/mozilla-mobile/fenix/issues/17805.
Closing as a dupe of #18546.

**Closed by Mugurell** 2021-03-22 06:45 UTC
Labels: 🐞 bug
