### ISSUE TITLE
FNX-4343 ⁃ [Bug] frequent crashes Firefox Preview 4.3.0 e 5.0

### ISSUE THREAD

**Issue by marker10** [mozilla-mobile/fenix#10517] opened 2020-05-08 12:05 UTC
Latest version 4.3.0 frequent crashes, on many sites. Browser closes or tab error,

Firefox Preview 4.3.0
Android 6.0.1 Asus Zenfone 2

- - -
Tracking GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1630229
Needs 77 uplift

**Comment by ekager** [comment] 2020-05-12 05:00
hey @marker10 sorry about that. We are rolling 5.0 out and wondering if that will solve any of your issues. If not, some more information about maybe the sites you're on when you see crashes, if you have any add-ons enabled, if you're signed into FxA could be helpful to our investigation. Thanks!

**Comment by ekager** [comment] 2020-05-12 05:01
And possibly the same crash as https://github.com/mozilla-mobile/fenix/issues/10528

**Comment by marker10** [comment] 2020-05-13 14:29
Example sites: leroymerlin.it or slack.com.
Still problems with vers. 5. Huawei MediaPad Android 7 tablet seems to work well.

**Comment by ekager** [comment] 2020-05-13 16:40
Thanks for the info! Is there any other difference between your tablet and phone? For example do you have addons enabled on one device and not the other? Or logged in to FxA on one and not the other?

**Comment by marker10** [comment] 2020-05-13 17:15
I also tried with a clean installation on Android 6 always crashes Deactivated antitracking and addons always crashes  - On Tablet no addon and I am logged in.

**Comment by liuche** [comment] 2020-05-14 01:44
Hi @marker10, I know this is a big ask, but since you're able to reproduce 100% (and we haven't been able to get logs for this bug) would you be able to take a log of this happening? This seems possibly device-specific.

a) If you can install [Firefox Preview Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix.nightly), you can see the crash reports if you open the url `about:crashes` (you may need to trigger a crash again)
b) We also have some detailed instructions [here](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information).

If you don't want to upload the logs here, you could also email or send them over our Matrix instance (which is the Mozilla public communication platform, like IRC).

Thank you!

**Comment by marker10** [comment] 2020-05-14 15:07
On "About: crashes" I can't find anything. I have sent crash report title leroymerlin.it crashes. With Firefox preview nightly 200514 06:00 Clean installation.

**Comment by liuche** [comment] 2020-05-15 23:21
Seems like this could be our top GV crasher: https://bugzilla.mozilla.org/show_bug.cgi?id=1630229

Which has been around for a month and was recently re-opened. Technically says 76 is not affected and is 77 only, but since the crash goes back 1mo it could be in 76.

In any case, will track that GV bug against this one. Have requested aklotz ask for 77 beta uplift so we can get it into 5.1.

**Comment by liuche** [comment] 2020-05-19 20:02
Hey @marker10, we landed a fix for this in Nightly, which should be available in the Play Store. Let us know if you're still seeing this!

**Comment by marker10** [comment] 2020-05-21 11:25
> 
> 
> Hey @marker10, we landed a fix that might be the culprit for this in Nightly, which should be available in the Play Store. Let us know if you're still seeing this!
> 
> And if this isn't fixed, then maybe this is related to #10770.

Tested with the latest Nightly version. Site leroymerlin.it crashes again. app.slack.com instead seems to work, no crash. I don't remember the other sites anymore.

Nightly 200521 06:01 (Build #21420607)
43.0.20200520190033, 3aa8dc692
GV: 78.0a1-20200520033931
AS: 0.59.0

**Comment by liuche** [comment] 2020-05-26 21:25
Thank you for continuing to test! We just landed another fix into Nightly, that should go out in tomorrow's build, so if you have a chance, please try it out, and let us know if it's still not fixed.

**Comment by marker10** [comment] 2020-05-28 20:46
> Thank you for continuing to test! We just landed another fix into Nightly, that should go out in tomorrow's build, so if you have a chance, please try it out, and let us know if it's still not fixed.

Hi leroymerlin.it always crash. It's still not fixed.

Nightly 200528 06:00 (Build #21490607)
44.0.20200527130120, b1ddaff6a
GV: 78.0a1-20200525093440
AS: 0.59.0

**Comment by marker10** [comment] 2020-06-04 22:02
Firefox preview 5.1 work. Bug crash fixed. 🙂

5.1.0 (Build #21502229)
42.0.1, 5bf46033e
GV: 77.0-20200526221856
AS: 0.58.2

**Comment by liuche** [comment] 2020-06-17 00:16
I'm glad the crash has been fixed, but this loading problem is also bad. I'm going to close this issue for now though. Can you follow along in #11394 ? Does it seem a similar problem?

**Closed** 2020-08-11 00:58 UTC
Labels: b:crash, needs:gv, 🐞 bug
