### ISSUE TITLE
[Bug] Closing a PWA while having open private tabs in Fenix results in closing the PBM and tab-zero

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#16165] opened 2020-10-25 11:46 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open a website in PBM, e.g. https://www.mozilla.org/en-GB/
2. Open a PWA, e.g. the https://twitter.com/ supplied PWA
3. Close the PWA using a back-button-equivalent action of your device

### Expected behavior
The PWA is closed and Fenix' state is unchanged.

### Actual behavior
The PWA is closed as well as the PBM, thus removing all active private tabs. Furthermore, an undefined tab-zero is shown.

![close-pwa-closing-pbm](https://user-images.githubusercontent.com/42788925/97106061-bcfa0a80-16bf-11eb-8ec7-56f47a5d97dd.gif)

### Device information

* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version: Nightly 201024 17:01 (Build #2015771593)
AC: 64.0.20201023143136, d78abdf9f
GV: 84.0a1-20201022093646
AS: 63.0.0

**Comment by jonalmeida** [comment] 2020-11-16 16:12
I did a quick test on this with today's Nightly (11/15) and while the PBM tab is gone, we're no longer seeing the black screen with the broken counter.

Closing the PBM tab might be a Fenix issue now.

**Comment by hwinnemoe** [comment] 2020-11-19 09:50
I can still reproduce the issue Nightly 201118 17:04 (Build #2015776393).

**Comment by jonalmeida** [comment] 2020-12-07 19:35
We should get this re-tested with the latest GV.

**Comment by sflorean** [comment] 2020-12-10 17:22
Tested on Nightly 12/9 and I was able to reproduce the issue, with GV 85.0a1. Don't reproduce the "black screen" but the private tab is closed, following the steps provided.

**Comment by ekager** [comment] 2020-12-10 21:21
This seems to be a regression from the fix for https://github.com/mozilla-mobile/fenix/issues/14225
When I revert to just using `activity.finish()`, I can't repro. 

cc @pocmo

**Comment by pocmo** [comment] 2021-01-04 18:35
With us now finishing the PWA task, I see `AbstractPrivateNotificationService.onTaskRemoved()` getting triggered, which closes all private sessions:
https://github.com/mozilla-mobile/android-components/blob/master/components/feature/privatemode/src/main/java/mozilla/components/feature/privatemode/notification/AbstractPrivateNotificationService.kt

I think what we want is to check here that the actual "main" task got removed and not react to any task removal. In addition to that we should check if there are other cases where we listen to `onTaskRemoved()` and may need to check.

**Comment by hwinnemoe** [comment] 2021-01-12 11:07
This seems to have been resolved for some days, e.g. on 
Nightly 210111 17:02 (Build #2015786761)
AC: 71.0.20210110143120, 641cbe6b9
GV: 86.0a1-20210110092829
AS: 67.2.0.

**Comment by pocmo** [comment] 2021-01-14 15:19
Yeah, the patch landed in AC and should be in Nightly already.

**Comment by marcel263** [comment] 2021-05-03 15:30
@pocmo 

Issue has returned. Loading a custom tab invokes nothing but eventually closing it will dispose of any opened private tabs.

**Comment by pocmo** [comment] 2021-05-03 17:00
I'll reopen and flag QA.

**Comment by AndiAJ** [comment] 2021-05-04 07:40
Hi, **verified as fixed** on the latest **`Nightly 90.0a1 5/4`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
https://user-images.githubusercontent.com/51314259/116973354-11acbc80-acc5-11eb-8569-cecf674c7fed.mp4

**Closed by AndiAJ** 2021-05-04 07:40 UTC
Labels: Feature:PWA, Feature:PrivateBrowsing, S2, eng:qa:needed, 🐞 bug

**Comment by marcel263** [comment] 2021-05-16 17:45
@AndiAJ 
hello thank you for assisting. However the video shows you testing against a PWA. As I mentioned the problem occurs with custom tabs, could you try out that situation as well?
