### ISSUE TITLE
Character and word echoes don't work in web text inputs when using a screen reader

### ISSUE THREAD

**Issue by BlindMoon38** [mozilla-mobile/fenix#20492] opened 2021-07-23 22:33 UTC
### Steps to reproduce

1. Open Firefox with TalkBack enabled.
2. Go to any page with a text input, like google.com and tap it.
3. Start typing.
4. Delete some of the typed text.

### Expected behaviour

Normal Android behaviour regarding text fields when using a screen reader:
* While typing, TalkBack should repeat each character as it's being typed.
* After typing a word and pressing the space bar, TalkBack should read the last typed word.
* TalkBack should read each character as it's being deleted.

### Actual behaviour

For all three cases, TalkBack is silent.

### Device name

Xiaomi Redmi Note 8

### Android version

MIUI 12.0.4.0, Android 10

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1 (Build #2015823243) AC: 92.0.20210719094322, 97d95e60fb GV: 92.0a1-20210718090829 AS: 79.0.0

### Additional information

TalkBack version 9.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17352)

**Comment by jcsteh** [comment] 2022-02-02 00:35
This sounds like something that needs to be addressed in Gecko. We'll need to get a bug filed in Bugzilla. CC @eeejay.

@DiegoARL38, one clarification: could you verify whether this happens for simpler input boxes such as the Quick Search field on bugzilla.mozilla.org? The Google search box has some ARIA applied to it, so I'd like to rule out whether it's related to that or not.

**Comment by DiegoARL38** [comment] 2022-02-02 01:07
@jcsteh It happens in every text input I've tried it on: Bugzilla quick search, Google, GitHub comments, etc.

Sorry for the lateness, I thought I sent the answer earlier...

**Comment by behofer** [comment] 2022-02-02 18:04
@jcsteh the behaviour even occurs in the address field of the app when searching or entering a URL. So, shouldn't be related to ARIA...

**Comment by DiegoARL38** [comment] 2022-02-02 18:17
@behofer That would be related to #20491, I believe. If I'm not mistaken, this issue and #20491 are in different, unrelated components, though I could be wrong...

**Comment by behofer** [comment] 2022-02-03 07:20
@DiegoARL38 #20491 refers to the address bar, this issue refers to web text inputs (different components). However, actual behaviour and expected behaviour when Talkback enabled is exactly the same! So technically it could be the same or related root cause.

**Comment by DiegoARL38** [comment] 2022-11-24 00:59
This issue is still present...

Any news on this, @jcsteh?

**Closed** 2023-01-20 21:48 UTC
Labels: 🐞 bug, access
