### ISSUE TITLE
[Bug]: Sharing option doesn't work when using FF as in-app browser on Android

### ISSUE THREAD

**Issue by stevejalim** [mozilla-mobile/fenix#23438] opened 2022-01-27 14:50 UTC
### Steps to reproduce

1. On Android, have FF enabled as the in-app browser
2. Follow a link from some other app (eg Slack in my experience), which will open in the in-app browser
3. Attempt to share the link via the share option from the context menu

### Expected behaviour

I should see a way to share the page to other services/apps - eg Pocket

### Actual behaviour

Nothing happens - no share options appear in the UI.

If I then choose to view the same page in main FF, the share options do then work.

### Device name

Google Pixel 4a 5G

### Android version

12

### Firefox release type

Firefox

### Firefox version

96.2.0

### Additional information

I have a video example of the behavour [here](https://mozilla.slack.com/archives/C4D3JFF26/p1643275924177000?thread_ts=1643275863.176700&cid=C4D3JFF26)

**Comment by dholbert** [comment] 2022-01-31 18:01
That's the feature steve's describing as "in-app browser", yeah. (I think it's controlled by the Firefox setting "Settings | Advanced | Open links in apps".)

I can reproduce this myself, too.  I'm using a Pixel 4a as well (not the 5G model, in my case), with Firefox Nightly.  It seems the "Share via..." menu-item is just non-functional, in the lightweight Firefox session that you get when tapping a link in Slack. It does seem to be Slack-specific, for some reason; if I use e.g. Twitter instead, I see a `Share via...` menu-item that works just fine.

"Good news", though:  it's broken if I use Chrome as the in-app browser (e.g. by changing my default browser), too! If I use Chrome, there's a "Share via..." button in the meatball menu for the in-app-webpage-viewer experience, and it has no effect there.

So this is probably a slack bug.

Having said that, there's still some Firefox-specific bad-experience here, because in Chrome, there's a dedicated share button baked-into-the-toolbar (which does work), vs. Firefox does not seem to have that baked-into-the-toolbar share button in this case.

**Comment by dholbert** [comment] 2022-01-31 18:25
I forwarded this along to some Slack folks in the hopes that they can take a look (especially given that this isn't browser-specific).

I'll file a separate issue on possibly showing a dedicated share button (outside of the 3-dot-menu here), like Chrome does, so that users can use that as well; I'm not sure why we don't and they do in this case. (We do seem to show one for other apps e.g. Gmail.)

**Comment by dholbert** [comment] 2022-01-31 18:35
The "Share in Slack" and "Copy link" menu-items are non-functional too, it seems! (tested in Chrome as well as Firefox)

**Comment by dholbert** [comment] 2022-01-31 18:51
I filed https://github.com/mozilla-mobile/fenix/issues/23493 on the fact that we don't show a dedicated share button here for some reason.

**Comment by dholbert** [comment] 2022-01-31 20:01
This bug can be closed as not-our-bug; as noted above, it's a bug in the slack app itself (they control these menu items, and they're broken in Chrome too, not just Firefox).

The only things to be done here are (a) inform them (which I've done), and (b) possibly show our own built-in share button as an escape-hatch for app-controlled-menu-item brokenness (which I filed as #23493 and apparently is a dupe of #8674).

**Comment by kbrosnan** [comment] 2022-01-31 20:11
Closing.

**Closed by kbrosnan** 2022-01-31 20:11 UTC
Labels: 🐞 bug, needs:investigation
