### ISSUE TITLE
Floating appearance button in reader mode

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11779] opened 2020-06-20 09:27 UTC
### What is the user problem or growth opportunity you want to see solved?
Like fennec is it possible to show the appearance button as a floating icon/bubble. Currently to access the appearance we have to click 3 button menu and then the appearance which involves an extra step. 

### How do you know that this problem exists today? Why is this important?
It is present in fennec which is easily accessible.
Besides adding this feature which reduce the number of items in 3 dot menu

### Who will benefit from it?
All users. Attaching screenshot from fennec.

![6951](https://user-images.githubusercontent.com/58127841/85198435-316b0a00-b2d8-11ea-9233-5ffc4c6edc57.png)

**Comment by amkcpu** [comment] 2020-06-24 11:49
To be honest, I much prefer to have the appearance settings in the Fenix Customization settings (see #11282). I think most people never change the appearance and almost no one changes it frequently, which means that a floating button like this would only confuse and take away display space, disturbing the clean reading experience.

To improve discoverability, it may be good to notify the user of these settings though, when they open reader mode for the first time.

**Comment by sheikh-azharuddin** [comment] 2020-06-24 12:10
> To be honest, I much prefer to have the appearance settings in the Fenix Customization settings (see #11282). I think most people never change the appearance and almost no one changes it frequently, which means that a floating button like this would only confuse and take away display space, disturbing the clean reading experience.
> 
> To improve discoverability, it may be good to notify the user of these settings though, when they open reader mode for the first time.

Please check fennec implementation..
The floating appearance setting bubble is hiding after some scroll...

**Comment by amkcpu** [comment] 2020-09-11 10:18
Duplicate of #7912.

**Comment by csadilek** [comment] 2020-11-17 00:58
Closing feature request as dupe of https://github.com/mozilla-mobile/fenix/issues/7912.

**Closed by csadilek** 2020-11-17 00:58 UTC
Labels: Feature:ReaderMode, feature request 🌟

**Comment by sheikh-azharuddin** [comment] 2020-11-17 03:30
That duplicate request is closed

**Comment by cadeyrn** [comment] 2020-11-17 08:12
> That duplicate request is closed

No, it's still open.
