### ISSUE TITLE
[Bug][CRASH] Crash after clicking on the notification/camera/microphone info for the site

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6715] opened 2019-11-20 12:28 UTC
## Steps to reproduce

1. open any URL
2. click padlock icon next to the URL - it will show you popup with site permissions
3. click on the text right to the Notifications

### Expected behavior

There is opened Settings window related to Notifications

### Actual behavior

Crash

### Device information

* Android device: Galaxy S7 / Android 8
* Fenix version: nightly 191120

**Comment by marcinwiacek** [comment] 2019-11-20 12:35
Note: 100% reproducible.

**Comment by sv-ohorvath** [comment] 2019-11-20 13:42
@marcinwiacek I cannot reproduce this crash, do you have any extra info? Could you get a [logcat ](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information) maybe?

**Comment by marcinwiacek** [comment] 2019-11-20 15:42
11-20 15:15:51.855 15145 15145 E AndroidRuntime: FATAL EXCEPTION: main
11-20 15:15:51.855 15145 15145 E AndroidRuntime: Process: org.mozilla.fenix.nightly, PID: 15145
11-20 15:15:51.855 15145 15145 E AndroidRuntime: kotlin.KotlinNullPointerException
11-20 15:15:51.855 15145 15145 E AndroidRuntime: 	at io.reactivex.plugins.RxJavaPlugins.throwNpe(RxJavaPlugins.java:1)
11-20 15:15:51.855 15145 15145 E AndroidRuntime: 	at -$$LambdaGroup$js$UzxwWBcA25T96zHXE2jcsylXJGo.onClick(java-style lambda group:87)
11-20 15:15:51.855 15145 15145 E AndroidRuntime: 	at android.view.View.performClick(View.java:6897)
11-20 15:15:51.855 15145 15145 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:12693)
11-20 15:15:51.855 15145 15145 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:26101)
11-20 15:15:51.855 15145 15145 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
11-20 15:15:51.855 15145 15145 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
11-20 15:15:51.855 15145 15145 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
11-20 15:15:51.855 15145 15145 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
11-20 15:15:51.855 15145 15145 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-20 15:15:51.855 15145 15145 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
11-20 15:15:51.855 15145 15145 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by marcinwiacek** [comment] 2019-12-09 19:35
20 days with crash...

**Comment by marcinwiacek** [comment] 2019-12-14 18:47
still visible in 3.0.0...

**Comment by marcinwiacek** [comment] 2020-01-07 23:17
Issue is visible even on Android emulator and happens for notification, microphone, camera


2020-01-07 20:00:18.745 30126-30126/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 30126
    kotlin.KotlinNullPointerException
        at org.mozilla.fenix.settings.quicksettings.DefaultQuickSettingsController.handlePermissionToggled(QuickSettingsController.kt:99)
        at org.mozilla.fenix.settings.quicksettings.QuickSettingsInteractor.onPermissionToggled(QuickSettingsInteractor.kt:24)
        at org.mozilla.fenix.settings.quicksettings.WebsitePermissionsView$bindPermission$1.onClick(WebsitePermissionsView.kt:88)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by kbrosnan** [comment] 2020-01-08 04:45
@marcinwiacek if you do a local build with #7404 does it resolve this crash?

**Comment by sblatz** [comment] 2020-01-08 21:40
@kbrosnan Testing this now 😄

**Comment by kbrosnan** [comment] 2020-01-08 23:21
Closing this as a duplicate

**Closed by kbrosnan** 2020-01-08 23:21 UTC
Labels: Feature:QuickSettings, P2, b:crash, 🐞 bug
