### ISSUE TITLE
FNX3-17048 ⁃ Switch Tabs via Swiping Address Bar

### ISSUE THREAD

**Issue by vrudesai** [mozilla-mobile/fenix#3481] opened 2019-06-14 15:36 UTC
### Why/User Benefit/User Problem
As a user I want to be able to quickly switch back and forth between tabs by swiping right and left on the address bar.

For left-to-right languages the oldest tab is on the left and a left swiping brings you to your most recent tabs.

For right-to-left languages the oldest tab is on the right and right swiping brings you to your most recent tabs.

**Comment by Neikon** [comment] 2019-06-15 11:44
Gives us this feature pls pls pls

**Comment by Sergiu-Ghita** [comment] 2019-06-15 11:56
I'd like to work on it

**Comment by KazaHesto** [comment] 2019-06-16 05:57
This should be tested with Android Q to see how it interacts with the new navigation gestures.

**Comment by kbrosnan** [comment] 2019-06-16 21:27
Dupe of #1283 / #176

**Comment by ChristianCiach** [comment] 2019-06-29 08:16
@kbrosnan
It may be a dupe, but please compare the upvotes of this issue to the issues this is a dupe of. The discoverability of this issue is way higher, so please don't ignore this issue when assessing the importance of this feature.

**Comment by vesta0** [comment] 2019-07-09 20:53
@mozilla-mobile/ux please consider this for the tab management re-design

**Comment by lime124** [comment] 2019-07-23 03:48
removing the ux label - this is on our radar already as it's part of Q3 plans.

**Comment by vesta0** [comment] 2019-08-19 23:17
Related GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1509249

**Comment by sr0n** [comment] 2020-02-23 22:13
Just had an idea that I would like to mention - I would also like this feature implemented but quite a few people I assume also like being able to use this gesture to see the full URL as is currently the case in Fennec. Could there be an option to switch between the two if they are ever both added?

**Comment by yoasif** [comment] 2020-04-25 17:10
> @kbrosnan
> It may be a dupe, but please compare the upvotes of this issue to the issues this is a dupe of. The discoverability of this issue is way higher, so please don't ignore this issue when assessing the importance of this feature.

Pretty sure it is a dupe of https://github.com/mozilla-mobile/fenix/issues/396

**Comment by scratchmex** [comment] 2020-05-11 02:59
Following #10548 , the gesture to swipe down (or up) the address bars to trigger the tabs overview could be useful as well.

**Comment by person808** [comment] 2020-06-24 17:29
Starting to look into this now. One question for UX: do we want this gesture to work on the home page and if so, how would it work (what tabs would swiping go to)? Its a bit weird since the home page isn't a "real" tab but we do show a toolbar there.

**Comment by yoasif** [comment] 2020-06-24 17:38
@person808 Not UX, but my feedback is that we should treat the home page as a real page and that the place in the tab stack should be where a new tab would appear if someone tapped on a top site or opened a url or search. 

It would be far simpler if it were simply a tab, of course.

**Comment by person808** [comment] 2020-06-24 19:24
@yoasif Interesting idea! New tabs appear at the top of the tab tray but I'm not sure if thats treated as the first or last tab internally. So effectively the home page would be treated as the first or last page (depending on the internal tab order).

**Comment by person808** [comment] 2020-06-24 22:23
Did some investigation into how similar gestures function.

Android 10 overview: In LTR layouts, the most recent app is the rightmost card in the overview. In RTL layout, the most recent app is the leftmost card in the overview.

Chrome: Regardless of layout direction, the newest tab is the rightmost tab. You always swipe left-to-right to go to an older tab.

**Comment by person808** [comment] 2020-07-01 00:03
https://streamable.com/69gd69

@brampitoyo @apbitner Could one of you take a look at the wip gesture and see if theres anything that needs tweaking? Ignore minor animation weirdness like the home page "save to collection" appearing for a split second

Here are some concrete values I'm using right now:
1. Currently, the gesture will go to the next tab if the user lifts their finger with 25% of the next tab preview visible. This is roughly what Chrome appears to do. 
2. The animation to the next the next tab is a happens at a constant speed of 1250 dp per second (arbitrary number that feels nice to me). 
3. The "overscroll" allows swiping the tab across 20% the screen if there is no tab in that direction.
4. No gap between the tab preview and tab unlike chrome. It shouldn't be hard to add one if you want that.

Do we want to allow swiping to the home page in the way @yoasif suggested? I have that partially implemented (swiping from a tab to home page, but not swiping from home to a tab), but its definitely one of the trickier things to get right so I won't complain if you don't want it 😄

**Comment by Neikon** [comment] 2020-07-01 09:54
I personally would like to be able to swipe home->tab and tab->home

**Comment by apbitner** [comment] 2020-07-01 17:33
@person808 For now, I would recommend not including the home screen. Swiping is another way to navigate the tabs in the tab tray and since it's not included there let's leave it out for now, knowing that we could always add it later after further investigation. Let me know if you feel strongly otherwise @brampitoyo.

**Comment by szbergeron** [comment] 2020-07-01 17:42
Layman's perspective incoming: being able to swipe to a new tab page like that with a single gesture is a massive usability plus IMO. Would be awesome to keep that if possible.

**Comment by Neikon** [comment] 2020-07-01 17:49
> 
> 
> Layman's perspective incoming: being able to swipe to a new tab page like that with a single gesture is a massive usability plus IMO. Would be awesome to keep that if possible.

it would be awesome. Maybe it could be sort like, home page/tab/tab/.../tab/New tab page

**Comment by brampitoyo** [comment] 2020-07-02 03:01
If we return to the original intent of this design, we’ll find that it’s centred around quickly switching back and forth between tabs.

I’m not disagreeing with the notions put forth by @szbergeron @Neikon @person808 and others, that there could be some value in swiping to open a new tab, but it causes an additional problems that we must first solve.

This gesture was meant to go exclusively in two directions – however way you think of it: up and down the tab list, left and right, previous and next, back and forth, etc.

It’s also meant to go only one way. Meaning: if you’re on the first tab, swiping right does nothing. If you’re on the last tab, swiping left does nothing.

Being able to create a new tab breaks the simplicity of the concept, if you will. It means that this gesture is no longer exclusively navigational, but also used for something else. Now it’s got the power to invoke a new object of the same type.

Further, we  now need think about other issues:

- I can open new tabs from the last tab on the list. What about from the first tab?
- Should swipe-to-switch “wrap-around” instead of only going one way and stopping at the first and last tabs?

From these observations, it seems as if swipe-to-switch and swipe-to-open are two separate concepts, which should be differentiated in the app somehow. How exactly? This takes some more thinking with our limited time and resource, and please feel free to continue contributing ideas.

For this reason, I recommend separating swipe-to-open new tab into a new issue, so we can fully flesh it out while shipping swipe-to-switch in the meantime.

**Comment by vesta0** [comment] 2020-07-02 15:09
@brampitoyo totally agree and thanks for unpacking it. 

Let's keep this issue focused on "Swipe to Switch" and move forward with the ENG work - with the goal of shipping this in nightly and testing it.

**Comment by yoasif** [comment] 2020-07-02 15:27
@brampitoyo @vesta0 To clarify, my comment about the tab switcher working to navigate to new tabs was only in the case where a user either opens a new tab via the tab switcher context menu or the tab tray FAB. 

So it would look like:

1. Open tab tray
2. Open tab
3. swipe address bar
4. swipe *back*

In this scenario, because Fenix doesn't actually open a new tab in step 2, the user finds that the tab that they opened can't be navigated to. 

I agree on the overall point that swipe to create may not be a great idea - but that isn't the issue I would like to prevent. 

The solution to the issue above (imo) is to just have the new tab be a new tab, instead of an intermediary access point on the road to creating a new tab - that would solve the issue above.

**Comment by sheepycoder** [comment] 2020-07-23 10:45
Works fine for me. However, it is unintuitive because the tabs tray shows the tabs in the reverse order. I think there was an issue open for that so that the tabs tray displays the tabs in the correct order, however I cannot find that issue right now. I just hope, it gets implemented soon.

**Comment by andreicristianpetcu** [comment] 2020-07-23 10:56
@sheepycoder where did you get the build from?

**Comment by sheepycoder** [comment] 2020-07-23 10:58
@andreicristianpetcu This feature is available on latest nightly.

**Comment by Scripterr** [comment] 2020-07-23 11:06
Hi @andreicristianpetcu they are in new place here https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.latest  
Old link to nightly version is obslete and new place to future versions are transfered to the new directory so grab them from this new link.

**Comment by andreicristianpetcu** [comment] 2020-07-23 11:22
Thank you! I was getting it from here https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly/latest

**Comment by person808** [comment] 2020-07-23 15:12
@sheepycoder If I'm understanding you correctly, you're saying the way we order tabs is unintuitive? But its not a bug in the gesture itself where the tab order in the gesture isn't matching the order in the tab tray (topmost tab in tab tray = right most tab in the gesture, swiping left-to-right navigates "downward" in the tab tray). Just want to make sure there's not a bug where the tab order in the tab tray and in the gesture get out of sync.

**Comment by sheepycoder** [comment] 2020-07-23 15:17
@person808 Yeah, there is no bug in the gesture.

**Comment by anotherus3r** [comment] 2020-07-23 15:21
Gesture works fine for me, although I sometimes trigger the system gesture for quickly switching apps. I probably just need to get used to it, i.e. to swipe a bit higher on the address bar. Regarding the tab order, I like the suggestions in #11376.

**Comment by Neikon** [comment] 2020-07-23 15:46
it works well for me. I was hoping it was the most left tab = top tab, too. I think it's more intuitive (most left tab= top tab) and Chrome does it like this. Maybe, it would be easier for new users if we order it the same way

**Comment by sheepycoder** [comment] 2020-07-23 15:52
@Neikon yeah, that is a bug with how the tabs are displayed in the tabs tray. That will be fixed some day, though AFAIK they are low priority as of now.

**Comment by Scripterr** [comment] 2020-07-23 16:05
@person808 there is a bug when you open a website(tab A) and scroll down the page and then swipe to another tab(tab B) and swipe again to the previous tab(tab A) you will see older tab preview/thumbnail when it was opened.

**Comment by person808** [comment] 2020-07-23 16:25
@Neikon @Scripterr Could you open new issues for your comments? I don't want feedback to get lost in here. Feel free to tag me in the new issue :)

**Comment by andreicristianpetcu** [comment] 2020-07-25 19:32
found a bug https://github.com/mozilla-mobile/fenix/issues/12945

**Comment by sv-ohorvath** [comment] 2020-07-27 12:11
Verified as fixed on Nightly, 7/27. 
Devices:
Pixel 3, Android 11 emulator.
Pixel 4, Android 10
Htc Desire 820, Android 6.0.1
Nexus 9, Android 7.1.1

**Comment by AndiAJ** [comment] 2020-07-30 10:07
Hi @liuche , this feature doesn't seem to be available on **`Beta 80.0.0-beta-1`** could you please review? ☺️

**Comment by andreicristianpetcu** [comment] 2020-07-30 13:52
Found another bug on this https://github.com/mozilla-mobile/fenix/issues/13127

**Closed** 2020-08-12 17:33 UTC
Labels: Feature:Browsing, Feature:Gesture, eng:qa:verified, feature request 🌟

**Comment by katzelad** [comment] 2020-08-13 12:47
This issue is listed in the beta 80.0.0 release notes but the gesture is disabled in the release.
