### ISSUE TITLE
[Bug] When re-entering Fenix, occasionally toolbar UI is missing

### ISSUE THREAD

**Issue by jimbo1qaz** [mozilla-mobile/fenix#4529] opened 2019-08-04 04:45 UTC
## Steps to reproduce

- Install Firefox Preview (I built from source).
- Switch to another app which uses lots of RAM, so Android unloads Firefox.
- Reopen Firefox Preview.

### Expected behavior

Upon trying to replicate this bug, I end up on the tab list, with all tabs intact, and the UI functional. I feel this provides a "clean slate" so I can enter a new search term instead of reading old tabs.

Alternatively (to match Firefox Android), the page and toolbar would be present, and I can enter a new URL and switch tabs.

### Actual behavior

One time, I ended up on the webpage I was reading (either back one history entry, or on the page I was reading), but with the toolbar missing, replaced by a black/gray void at the bottom of the page. Page scrolling did not work at first, but later started working. I had to restart Firefox Preview by swiping from Recent Apps and relaunching (which brought me to the tab list) to make the toolbar come back.

I took some [Android Studio layout captures](https://github.com/mozilla-mobile/fenix/files/3464527/fenix.missing.toolbar.captures.zip) of Fenix in the no-toolbar state, as well as the normal state after restarting.

Comparing the layout captures, in the bugged layout, `id/toolbar` is missing and `id/nestedScrollQuickAction` has no children.

### Device information

* Android device: Moto G5 Plus, stock 7.0 with Magisk
* Fenix version: master bfd4849064259bc8585bf686b0a48c4d417dca55 (with `gradle.properties` `org.gradle.jvmargs` edited to reduce memory consumption)

Possibly related to https://github.com/mozilla-mobile/fenix/issues/4461 '[Bug] When re-entering Fenix, open tabs all change to "about:blank"'? This time, my tabs were still there and not replaced with about:blank. In the past, I experienced this issue.

**Comment by rituraj22** [comment] 2019-08-04 15:52
The same happened on Nightly 190802 18:05 (Build #12141932) build in my Android 9.0 phone

**Comment by jacktose** [comment] 2019-08-05 15:53
Confirmed on Nightly 190802 18:05 (Build #12141931), Android 8.1.0, Moto G5+.
It's been happening occasionally for a few days, possibly since the 190802 build.

**Comment by ekager** [comment] 2019-08-05 17:04
IIUC this should be fixed by https://github.com/mozilla-mobile/fenix/issues/4412
Is that right @csadilek ?

**Comment by jimbo1qaz** [comment] 2019-08-05 17:10
#4412 was closed 5 days ago. I think my master checkout was from 2 days ago.

**Comment by colintheshots** [comment] 2019-08-05 17:41
I can't find steps to reproduce, but I can determine why the toolbar and quick action sheet both might go uninflated. That should be enough to produce a fix, but I'm not certain how to test the fix yet.

**Comment by csadilek** [comment] 2019-08-05 21:43
> IIUC this should be fixed by #4412
> Is that right @csadilek ?

@ekager This looks like it could be related (caused by the same problem) I described in https://github.com/mozilla-mobile/fenix/issues/4427. It's possible for the BrowserFragment to be created before the sessions have been restored. Without a `sessionId` we're not creating the UI properly.

**Comment by abodea** [comment] 2019-08-14 14:34
Verified as fixed using latest debug build(from the master) with **`Samsung Galaxy s10+(Android 9), Huawei P9 Lite(Android 6), Samsung Galaxy S7(Android 7).`**
Please note that I tried to reproduce this issue following the steps from the description but the issue cannot be reproduced.

Also, I tried the following:
1. Start the download of few big apps from Play Store.
2. Open more apps that are using a lot of RAM.
3. Launch Fenix.
4. Open few tabs. 
5. Switch between apps.
6. Re-open Fenix.

But everything worked as expected. I will close this issue and re-open it in case we will be able to reproduce/see this bug in the future.

**Closed by abodea** 2019-08-14 14:34 UTC
Labels: E5, P1, eng:qa:verified, 🐞 bug

**Comment by jimbo1qaz** [comment] 2019-09-02 06:31
Happened twice to me. First time an older build, with no tabs open. Second time on a build from 2019-08-15, with tabs open.

Interestingly, both times, I got a white screen with "pull to refresh" enabled. Otherwise, "pull to refresh" is not enabled.

**Comment by jacktose** [comment] 2019-09-03 18:20
I've also had this a few times since the fix, on 1.3.1.

**Comment by nyanpasu64** [comment] 2020-08-31 13:35
I think this is the same issue as #12490, and I just hit it again on Nightly 200830, but was unable to take a layout capture.
