### ISSUE TITLE
[Bug] There is no way to access synced tabs without opening irrelevant page first

### ISSUE THREAD

**Issue by gwarser** [mozilla-mobile/fenix#16892] opened 2020-12-07 13:23 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

- Open Firefox
- Try accessing synced tabs

### Expected behavior

- They should perhaps be listed in tab menu/panel?

### Actual behavior

- I cannot find them in tab menu/panel / main menu / history / bookmarks
- I need to open irrelevant page to find synced tabs in tabs menu/panel

### Device information

* Android device: custom Android 7.1.2 (LineageOS)
* Fenix version: Nightly 201205 17:02 (Build #2015779657)

**Comment by cadeyrn** [comment] 2020-12-07 13:45
Duplicate of #14117.

**Comment by gwarser** [comment] 2020-12-07 15:29
> Duplicate of #14117.

Not exactly, but can be set as dependence to make sure synced tabs are also shown when no other page/tab is opened.

**Comment by cadeyrn** [comment] 2020-12-07 15:47
> Expected behavior
> They should perhaps be listed in tab menu/panel?

#14117 is exactly about this so I don't understand why it should not be a duplicate. I also do not understand what you mean with "when no other page/tab is opened". #14117 does not depend on open tabs. Maybe you misunderstood #14117? There is a mockup of the expected result: https://app.abstract.com/share/c6bd0c2f-8384-44f3-ba59-4946d8cea469?collectionLayerId=ec285dbe-88bf-41cc-a531-49aad233b5ae&mode=design

**Comment by gwarser** [comment] 2020-12-07 16:07
>I also do not understand what you mean with "when no other page/tab is opened".

Yes. Clearly ;)

Synced tabs are already listed in tabs panel, but only when at least one, any irrelevant page is opened in one of the tabs.

Synced tabs are not displayed when you just opened Firefox and no tab has been opened yet (button shows [0]). 

Mockup you linked bring nothing to my issue, because it clearly shows that 3 tabs have been already opened. This section may be empty or not displayed at all when no tab has been opened yet.

And before you ask - I am signed to sync.

**Comment by cadeyrn** [comment] 2020-12-07 17:13
I don't know why you're talking about the current implementation, #14417 is not yet implemented…

> Synced tabs are already listed in tabs panel, but only when at least one, any irrelevant page is opened in one of the tabs.

The current implementation is not complete and therefore no reference. Bugs in the current implementation have no meaning for #14417. This is exactly the reason why the current implementation is hidden behind a secret preference and only exists in Nightly builds.

What you describe is clearly a bug and already covered by #14007. It was was closed by mistake, but it's still a bug.

> Mockup you linked bring nothing to my issue, because it clearly shows that 3 tabs have been already opened. 

I don't know why you think it's relevant that there are three open tabs in the mockup. The mockup is about a new panel for synced tabs and it doesn't make sense at all to hide this new panel if there are no new tabs. That's the whole point of having a separate panel - so it won't depend on open tabs any longer.

**Comment by kbrosnan** [comment] 2020-12-07 18:57
Closing as a duplicate of #14320

**Closed by kbrosnan** 2020-12-07 18:57 UTC
Labels: needs:triage, 🐞 bug
