### ISSUE TITLE
FNX-5152 ⁃ [Bug] 3rd party password managers do not work with Fenix

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1635] opened 2019-04-15 13:51 UTC
## Steps to reproduce
1. Install LastPass and log in (save passwords for a few sites if needed).
1. Go to any site that has a password saved in LastPass.
1. Try to fill in login details with LastPass.

### Expected behavior
The username and password can be filled.

### Actual behavior
No username and password options appear. When trying to add a new entry Fenix reports the site as being fenix.mozilla.org and uses that as the autofill option for all available sites.

### Device information
* For this particular case I've had a user and pass saved for facebook in LastPass.
* Tried with Dashlane as well, the password fill overlay does not even appear in Fenix. 
* Android device: Nexus 6P (Android 8.1)
* Fenix version: 1.0.1916 (#11051219)

**Comment by pocmo** [comment] 2019-04-15 14:13
In this case, is Lastpass (or Dashlane) setup to be the Autofill provider for the system?

**Comment by cadeyrn** [comment] 2019-04-15 15:11
FWIW, Lockbox as 3rd party password manager works in Fenix. I didn't test any other 3rd party password manager.

HTC U11 / Android 8.0

**Comment by reinhart1010** [comment] 2019-05-18 08:19
Is this duplicate of #87?

**Comment by sv-ohorvath** [comment] 2019-05-27 08:31
Still not working properly with Bitwarden or LastPass:
- adding new website credentials (e.g. facebook, twitter) to the vault automatically from the app will fill in website name and url with:
name = org.mozilla.fenix
URL = androidapp://org.mozilla.fenix
- no autofill options after I've added the website credentials manually
- you can't name your logins with the website name and URL or otherwise they won't appear in the autofill list.

Lockwise still working.

**Comment by sarentz** [comment] 2019-05-30 17:48
I am closing this issue: from Fenix' perspective this works. There is nothing in Fenix we can do for specific password managers.

**Closed** 2020-08-11 12:20 UTC
Labels: Release Blocker, 🐞 bug
