### ISSUE TITLE
[Bug] When YouTube video played on 1.75 sound gets distorted

### ISSUE THREAD

**Issue by Dazrok2** [mozilla-mobile/fenix#13441] opened 2020-08-10 07:28 UTC
## Steps to reproduce

Play any video on YouTubeand  at1.5x or higher. 

### Expected behavior 

Sound should come as Regular Firefox

### Actual behavior

Sound is getting distorted 

### Device information

Xiomi redmi note 4x

* Fenix version: 79.1.0-beta.1

**Comment by s-ankur** [comment] 2020-08-10 07:35
Duplicate of #8456

**Comment by jakefleming156** [comment] 2020-08-10 17:01
Thank you for filing this bug. As it's a duplicate of #8456 I'll close this one.

**Closed by jakefleming156** 2020-08-10 17:01 UTC
Labels: needs:triage, 🐞 bug
