### ISSUE TITLE
[Bug] Crash while switching to private tab

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#13992] opened 2020-08-20 19:41 UTC
## Steps to reproduce
long press on a link
open in new private tab
wait 3-5 seconds
go to private tabs and click the new tab
### Expected behavior
see tab content
### Actual behavior
crash
### Device information

* Android device: one plus 5t
* Fenix version: nightly

**Comment by rafalopilowski1** [comment] 2020-08-20 19:59
@andreicristianpetcu Does turning off 'Wait Until First Paint To Show Page Content' secret setting fixes the issue?

**Comment by hwinnemoe** [comment] 2020-08-20 20:24
I can reproduce on Nightly 200820 06:08 (Build #2015759025) using the following STR:
1. Have the _Wait Until First Paint To Show Page Content_ secret setting activated
2. Open a tab in non-PBM, e.g. https://www.mozilla.org/en-GB/
3. Long-press a link and tap _Open link in private tab_
4. Wait for the snackbar to disappear.
5. Switch to PBM and open the new tab.

### Actual behaviour
79d61f4f-a0eb-4e47-8d74-1b99d5f50acc
java.lang.IllegalStateException: swipeRefresh must not be null
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=3d5fcf0b79104cefa8d89446db1770c4
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-4cf4060b-e52d-44d1-92f5-822840200820
----
```
java.lang.IllegalStateException: swipeRefresh must not be null
	at kotlin.jvm.internal.ArrayIteratorKt.checkExpressionValueIsNotNull(ArrayIterator.kt:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$19$2.emit(Collect.kt:4)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:7)
	at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$19$1$1.emit(Collect.kt:5)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:234)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by hwinnemoe** [comment] 2020-08-20 20:26
Duplicate of #13388

**Comment by mcarare** [comment] 2020-08-21 07:56
Closing this as duplicate. 
@andreicristianpetcu If you do not have 'Wait Until First Paint To Show Page Content'  option switched on, please reopen this. In that case, a stack trace would be useful. Thank you!

**Closed by mcarare** 2020-08-21 07:56 UTC
Labels: needs:triage, 🐞 bug
