### ISSUE TITLE
FNX3-15566 ⁃ [Bug] vertical alignment of address bar suggestion

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1443] opened 2019-04-06 14:32 UTC
## Steps to reproduce
1. enter something in the address bar

### Expected behavior
correct vertical alignment between favicon and text

### Actual behavior
another case of wrong vertical alignment

![Screenshot](https://user-images.githubusercontent.com/1100614/55670852-895f5180-5889-11e9-93aa-0b7381b6c8a4.png)UNITO-UNDERSCORE!20190406-151347!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision d43e902b4433348da285a2978918ccfefc389014

**Comment by vesta0** [comment] 2019-04-09 18:37
@mheubusch we need UX feedback on whether we want to go with vertical alignment or keep the text centered.

**Comment by lime124** [comment] 2019-04-24 19:13
dup of #1743 . thanks!

**Comment by cadeyrn** [comment] 2019-04-24 19:29
@lime124 It's not a duplicate. #1743 is about making all icons into the same "column", this issue is about the alignment between the favicons and the text of the results.

**Comment by lime124** [comment] 2019-04-24 19:35
i am so sorry @cadeyrn - in my haste i completely did not register the vertical bit of the bug. thanks for taking the time to clarify!

**Comment by lime124** [comment] 2019-04-24 21:59
as per shorlander: "All of the content in the list item should be vertically centered."

**Comment by bwinton** [comment] 2019-05-13 12:53
So, here are the boxes we're drawing in:
![Screen Shot 2019-05-13 at 08 50 11](https://user-images.githubusercontent.com/159571/57622741-3baac880-755c-11e9-8038-2235b1823d26.png)

They look pretty vertically centered to my untrained eye, although it's tricky to tell without the lines separating cells. What do you all think should be changed? (Should the spacing in between the text be removed and put around the text instead, maybe?)

**Comment by bwinton** [comment] 2019-05-13 13:48
This is what the padding around would look like, for reference:
![Screen Shot 2019-05-13 at 09 47 31](https://user-images.githubusercontent.com/159571/57626601-33568b80-7564-11e9-8c73-0178f36b11ea.png)

**Comment by topotropic** [comment] 2019-05-13 13:55
Looks good! Second version works better (w/o spacing); wondering if we want to reduce the padding between the results. The standard height we use for these kind of elements is 56dp.

**Comment by softvision-miralobontiu** [comment] 2019-05-16 12:47
Verified as fixed on the latest build 1.0.1920 (#11360657), with Google Pixel (Android 9), HTC 10 (Android 8.0), and Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by cadeyrn** [comment] 2019-05-16 19:56
It's _not_ fixed as you can see in the attached screenshot (4px top vs 10px bottom).

<img width="638" alt="Bildschirmfoto 2019-05-16 um 21 53 41" src="https://user-images.githubusercontent.com/1100614/57882912-24eac700-7825-11e9-8657-a5abdc0f7e90.png">

**Comment by bwinton** [comment] 2019-05-16 20:03
Hmm. The bounding box of the text seems to be higher than a capital "S", as you can see below.
![Screen Shot 2019-05-16 at 15 58 05](https://user-images.githubusercontent.com/159571/57883205-8d20b500-77f3-11e9-89e6-8eb2097d6031.png)

@shorlander, @topotropic, what do you think we should do here? Trust Android's font calculations, even though they seem to be off in this case? Override them with some magic number that we pick out of a hat based on examples from this one language?

**Comment by sv-ohorvath** [comment] 2019-05-17 07:59
Reopened for a decision.

**Comment by topotropic** [comment] 2019-05-20 12:02
> Override them with some magic number that we pick out of a hat based on examples from this one language

Let's not do that.

**Comment by shorlander** [comment] 2019-06-25 20:19
This seems caused by the height of the font itself. I think it's best to live with the small visual misalignment. The alternative of trying to manually adjust could create a worse outcome later because the font is variable and could change.

**Closed** 2020-08-11 08:40 UTC
Labels: Feature:Search, P1, eng:quality, eng:ready
