### ISSUE TITLE
[Bug]: Ruby-annotated characters are invisible in reader view.

### ISSUE THREAD

**Issue by brangpd** [mozilla-mobile/fenix#24123] opened 2022-03-06 14:19 UTC
### Steps to reproduce

1. Go to https://ja.wikisource.org/wiki/%E7%AB%B9%E5%8F%96%E7%89%A9%E8%AA%9E_(%E5%9C%8B%E6%B0%91%E6%96%87%E5%BA%AB)
2. Switch on reader view.

### Expected behaviour

Characters with ruby annotation in reader view should be visible.

In non-reader view, ruby text and characters are rendered correctly:

![Non Reader View](https://user-images.githubusercontent.com/40844407/156926905-d84cf2b6-f0ef-4c6f-b468-de9e1d51512e.jpg)

### Actual behaviour

Characters with ruby annotation in reader view are not visible.

![Reader View](https://user-images.githubusercontent.com/40844407/156926862-a740b7fd-f9dd-43e2-8448-5078196e8401.jpg)

### Device name

Redmi K30i 5G

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

97.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19746)

**Comment by Dunexus** [comment] 2022-03-07 10:07
This bug is also reproducible on the desktop version.
This issue should probably be transferred to underlying library https://github.com/mozilla/readability

**Comment by LaurentiuApahideanSV** [comment] 2022-03-18 11:51
I can confirm the issue is reproducible on Firefox Nightly 2022-18-03.
### Devices used:
- Google Pixel 6 (Android 9)
- OnePlus 6T (Android 9)

**Comment by kbrosnan** [comment] 2022-07-15 04:47
Moved to https://github.com/mozilla/readability/issues/758

**Closed by kbrosnan** 2022-07-15 04:47 UTC
Labels: 🐞 bug, Feature:ReaderMode, S3, needs:triage, qa-triaged
