### ISSUE TITLE
[Bug] EMPTY: no crashing thread identified; ERROR_NO_MINIDUMP_HEADER

### ISSUE THREAD

**Issue by 0x391F** [mozilla-mobile/fenix#18474] opened 2021-03-14 09:37 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Fenix crash (exit unexpectedly) when I viewing website. 

b19bf162-9e6b-4e27-a2f5-f922c317303e
<native crash>
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-bfa9407b-2217-4b15-bf85-39c9f0210314
----
<native crash>

### Device information

* Device vendor / model and Android version: Huawei Honor 20S, Android 10
* Firefox for Android version: 86.1.1

**Comment by kbrosnan** [comment] 2021-03-14 22:38
Duplicate of bz-1644486. If you have any specific info please add it to that bug.

**Closed by kbrosnan** 2021-03-14 22:38 UTC
Labels: needs:triage, 🐞 bug
