### ISSUE TITLE
[Bug]:  when a PWA web app is using PiP picture in picture, landscape is forced 

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#24902] opened 2022-04-21 11:40 UTC
### Steps to reproduce

* Use a PWA, like [Le Monde.fr / vidéos](https://www.lemonde.fr/videos/) that allows for full screen video playback
* In PWA, enter fullscreen and return to Android home screen for PiP to activate
* Try to open the main browser (must be same app, no mixing of Nightly/stable)
* Try to use the main browser 

### Expected behaviour

* Main browser has no screen orientatiom forced upon it

### Actual behaviour

Please see  video below which demonstrates, closing PiP and PWA from task overview clears the issue

https://user-images.githubusercontent.com/76437842/164619930-904c4812-5d43-45cb-85ca-401e2fc4ec57.mp4

* Possibly due to interaction between PWA and main browser activity, landscape mode is forced. Problem disappears after closing PiP in other activity.

### Device name

Samsung OneUI 3.1

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1 (Build #2015875179), 5eadcec62+

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20237)

**Comment by marcel263** [comment] 2022-04-22 10:21
issue #22471 probably the same

**Comment by sflorean** [comment] 2022-05-26 09:09
Closing as duplicate of #22471. This scenario will be verified as well, when a fix is available.

**Closed by sflorean** 2022-05-26 09:09 UTC
Labels: 🐞 bug, Feature:PWA
