### ISSUE TITLE
[Bug]: Screen flickers when reopening browser with web page open

### ISSUE THREAD

**Issue by jakoblm** [mozilla-mobile/fenix#23825] opened 2022-02-18 22:06 UTC
### Steps to reproduce

1) I open any web page in Fennec and then minimize the browser.
2) When I maximize Fennec again, the web page flickers briefly so that you can see the homescreen with the app icons shimmering through.
3) It also happens when I disable all add-ons.

### Expected behaviour

The web page should be displayed without flickering.

### Actual behaviour

When I maximize Fennec again, the web page flickers briefly so that you can see the homescreen with the app icons shimmering through.

### Device name

Fairphone 3+

### Android version

/e/ os 0.21 (based on Android 10)

### Firefox release type

Firefox

### Firefox version

Fennec 97.1.1

### Additional information

**Application Basics**

NameFennecVersion97.0Build ID20220214060426Distribution IDUser AgentMozilla/5.0 (Android 10; Mobile; rv:97.0) Gecko/97.0 Firefox/97.0OSLinux 29 #1 SMP PREEMPT Sat Jan 22 01:57:21 UTC 2022Multiprocess Windows 0/0 Fission Windows 0/0 Disabled by default Remote Processes 1 Google Location Service KeyMissingGoogle Safebrowsing KeyMissingMozilla Location Service KeyMissingSafe Modefalse

Fennec Features

NameVersionID

Remote Processes

TypeCountWeb Content1 / 2

**Add-ons**

NameTypeVersionEnabledIDMozilla Android Components - Ads Telemetryextension97.0.11.0214073316trueads@mozac.orgMozilla Android Components - Browser Iconsextension97.0.11.0214073244trueicons@mozac.orgMozilla Android Components - Firefox Accounts WebChannelextension97.0.11.0214073248truefxa@mozac.orgMozilla Android Components - ReaderViewextension97.0.11.0214073253truereaderview@mozac.orgMozilla Android Components - Search Telemetryextension97.0.11.0214073316truecookies@mozac.orgMozilla Android Components - Web Compatibility Interventionsextension29.1.0truewebcompat@mozilla.orguBlock Originextension1.41.4trueuBlock0@raymondhill.net

**Graphics**

FeaturesCompositingWebRenderAsynchronous Pan/Zoomtouch input enabled; autoscroll enabled; smooth pinch-zoom enabledWebGL 1 Driver WSI InfoEGL_VENDOR: Android EGL_VERSION: 1.5 Android META-EGL EGL_EXTENSIONS: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_lock_surface EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_reusable_sync EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_create_context_no_error EGL_KHR_mutable_render_buffer EGL_EXT_yuv_surface EGL_EXT_protected_content EGL_IMG_context_priority EGL_KHR_no_config_context IsWebglOutOfProcessEnabled: 0WebGL 1 Driver RendererQualcomm -- Adreno (TM) 506WebGL 1 Driver VersionOpenGL ES 3.2 V@415.0 (GIT@994be9a, I75b52107df, 1590678002) (Date:05/28/20)WebGL 1 Driver ExtensionsGL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density GL_QCOM_YUV_texture_gather WebGL 1 ExtensionsANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_float_blend EXT_sRGB EXT_texture_filter_anisotropic MOZ_debug OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_lose_contextWebGL 2 Driver WSI InfoEGL_VENDOR: Android EGL_VERSION: 1.5 Android META-EGL EGL_EXTENSIONS: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_lock_surface EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_reusable_sync EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_create_context_no_error EGL_KHR_mutable_render_buffer EGL_EXT_yuv_surface EGL_EXT_protected_content EGL_IMG_context_priority EGL_KHR_no_config_context IsWebglOutOfProcessEnabled: 0WebGL 2 Driver RendererQualcomm -- Adreno (TM) 506WebGL 2 Driver VersionOpenGL ES 3.2 V@415.0 (GIT@994be9a, I75b52107df, 1590678002) (Date:05/28/20)WebGL 2 Driver ExtensionsGL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density GL_QCOM_YUV_texture_gather WebGL 2 ExtensionsEXT_color_buffer_float EXT_float_blend EXT_texture_filter_anisotropic MOZ_debug OES_texture_float_linear OVR_multiview2 WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_contextTarget Frame Rate60GPU #1ActiveYesDescriptionModel: FP3, Product: FP3, Manufacturer: Fairphone, Hardware: qcom, OpenGL: Qualcomm -- Adreno (TM) 506 -- OpenGL ES 3.2 V@415.0 (GIT@994be9a, I75b52107df, 1590678002) (Date:05/28/20)Vendor IDQualcommDevice IDAdreno (TM) 506Driver VersionOpenGL ES 3.2 V@415.0 (GIT@994be9a, I75b52107df, 1590678002) (Date:05/28/20)RAM0GPU #2DiagnosticsAzureCanvasBackendskiaAzureContentBackendskiaAzureFallbackCanvasBackendskiaCMSOutputProfileEmpty profile dataDisplay01080x2160DisplayCount1Decision LogHW_COMPOSITINGavailable by defaultforce_enabled by user: Force-enabled by prefOPENGL_COMPOSITINGavailable by defaultforce_enabled by user: Force-enabled by prefWEBRENDERavailable by defaultWEBRENDER_QUALIFIEDavailable by defaultWEBRENDER_COMPOSITORdisabled by default: Disabled by defaultWEBRENDER_PARTIALavailable by defaultWEBRENDER_SHADER_CACHEavailable by defaultWEBRENDER_OPTIMIZED_SHADERSavailable by defaultWEBRENDER_ANGLEavailable by defaultunavailable by env: OS not supportedWEBRENDER_DCOMP_PRESENTavailable by defaultdisabled by user: User disabled via prefunavailable by env: Requires Windows 10 or laterunavailable by runtime: Requires ANGLEWEBRENDER_SOFTWAREavailable by defaultWEBGPUdisabled by default: Disabled by defaultblocked by runtime: WebGPU can only be enabled in nightlyCrash Guard Disabled FeaturesWorkaroundsFailure Log

**Media**

Audio BackendopenslMax Channels2Preferred Sample Rate48000Roundtrip latency (standard deviation)...Output DevicesNameGroupVendorStatePreferredFormatChannelsRateLatencyDefault audio output deviceEnabledAlldefault: S16LE, support: S16LE S16BE F32LE F32BE2default: 44100, support: 44100 - 44100128 - 441Input DevicesNameGroupVendorStatePreferredFormatChannelsRateLatencyDefault audio input deviceEnabledAlldefault: S16LE, support: S16LE S16BE F32LE F32BE1default: 44100, support: 44100 - 44100128 - 441Media Capabilities Enumerate database

**Environment Variables

Important Modified Preference**s

extensions.lastAppVersion97.0idle.lastDailyNotification1645135780media.gmp.storage.version.observed1network.dns.disablePrefetchtruenetwork.http.speculative-parallel-limit0network.predictor.enabledfalsenetwork.prefetch-nextfalseprivacy.purge_trackers.date_in_cookie_database0privacy.purge_trackers.last_purge1645135780350security.remote_settings.crlite_filters.checked1645135630security.remote_settings.intermediates.checked1645135630storage.vacuum.last.index0

Important Locked Preferences

fission.autostart.sessionfalse

**Accessibility**

ActivatedfalsePrevent Accessibility0

**Library Versions**

Expected minimum versionVersion in useNSPR4.334.33NSS3.743.74NSSSMIME3.743.74NSSSSL3.743.74NSSUTIL3.743.74

**Startup Cache**

Disk Cache Path/data/user/0/org.mozilla.fennec_fdroid/files/mozilla/iyjon0cr.default/startupCache/startupCache.8.littleIgnore Disk CachefalseFound Disk Cache on InittrueWrote to Disk Cachefalse

**Internationalization & Localization**

Application SettingsRequested Locales["de-DE"]Available Locales["en-US"]App Locales["en-US"]Regional Preferences["en-US"]Default Locale"en-US"Operating SystemSystem Locales["de-DE"]Regional Preferences["de-DE"]

Remote Debugging (Chromium Protocol)

Accepting ConnectionsfalseURL

**Comment by Cheap-Skate** [comment] 2022-02-19 08:00
Maybe

https://bugzilla.mozilla.org/show_bug.cgi?id=1753085

Particularly Comment 5

**Comment by jakoblm** [comment] 2022-02-19 22:36
Yes, at least the problem sounds similar there. 

As I said, when Fennec is minimized and re-maximized, the homescreen flickers as described above. 
Now I have the following to add:  When I maximize Fennec again from the thumbnail view (where all open apps are visible), the whole web page flashes black once for a moment. 

Any idea how to fix this?

**Comment by delia-pop** [comment] 2022-03-02 13:36
Hi @jakoblm,
Thank you for your report! I was able to reproduce the issue you described, as well as the similar issue described in the Bugzilla ticket mentioned above. 
I will close this ticket for now, since the issue is handled [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1753085) and you can watch its progress. 


Tested on the latest Nightly build from 03/02 and Firefox  97.2.0.
Device used: Google Pixel 6 (Android 12).

**Closed by delia-pop** 2022-03-02 13:36 UTC
Labels: 🐞 bug, needs:triage

**Comment by jakoblm** [comment] 2022-03-03 17:20
Thanks for your answer. Yes that's ok. I just hope that this problem will be addressed soon. Right now there doesn't seem to be much happening in the linked Bugzilla thread.
