### ISSUE TITLE
FNX-11972 ⁃ Back and forward button in custom tab

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11106] opened 2020-06-01 06:56 UTC
### What is the user problem or growth opportunity you want to see solved?
When I open a link in custom tab/gecko view and click the link inside the custom tab it opens the page but back button is greyed out to go back....in normal browser window clicking the link opens in new tab so probably custom tab is also treating it as a new tab window and not allowing to go back rendering the buttons ineffective. Please fix this as for custom tab there is a single view only.
Attaching screenshots

### How do you know that this problem exists today? Why is this important?
I have tested it already

### Who will benefit from it?
All users who uses custom tab

![Screenshot](https://user-images.githubusercontent.com/58127841/83383560-e5adfa80-a3d4-11ea-934e-7f453c85c313.jpg)UNITO-UNDERSCORE!20200601-122018!

![Screenshot](https://user-images.githubusercontent.com/58127841/83383568-ee063580-a3d4-11ea-83ce-075c8406d88f.jpg)UNITO-UNDERSCORE!20200601-122043!

**Comment by cadeyrn** [comment] 2020-06-01 07:16
Duplicate of #9463.

**Comment by ekager** [comment] 2020-06-01 13:40
Closing for #9463

**Closed** 2020-08-11 02:55 UTC
Labels: needs:triage
