### ISSUE TITLE
[Bug] about:config doesn't work

### ISSUE THREAD

**Issue by jpardoe** [mozilla-mobile/fenix#14323] opened 2020-08-27 22:06 UTC
## Steps to reproduce
enter about:config in address bar

### Expected behavior
Get the warning about danger and an option to continue to configuration

### Actual behavior
Get "Cannot Complete request.  Additional information about this problem or error is currently unavailable." [button] Try Again.

The URL in the address bar looks correct: resource://android/assets/low_and_medium_risk_error_pages.html?etc., etc.  It looks like  it's trying to show the "be careful" page and failing.
### Device information

* Android device: Pixel 2xl, all updates installed on Android 10
* Fenix version: 79.0.5 (Build #2015758619) Tuesday 8/18 23:00 AM

This is, I think, a duplicate of #14191 but that one lacks useful info and is neither in progress/assigned nor needs triage, so I thought I'd see if a more detailed bug report was helpful.

**Comment by hwinnemoe** [comment] 2020-08-27 22:09
Duplicate of #7865. It does work in Beta and Nightly.

**Closed** 2020-08-27 22:10 UTC
Labels: needs:triage, 🐞 bug
