### ISSUE TITLE
[Bug] Tabs don't have a preview image

### ISSUE THREAD

**Issue by kolaente** [mozilla-mobile/fenix#12167] opened 2020-07-01 19:16 UTC
## Steps to reproduce
Open the tab overview with some tabs open.

### Expected behavior
Tabs have a preview image / social media preview / something useful but no blank screen. Maybe it wouldn't even need to show something useful, but just showing a blank rectangle looks ugly and broken.

### Actual behavior
![Screenshot](https://user-images.githubusercontent.com/13721712/86282608-db536c00-bbdf-11ea-98a2-028a297bb300.png)UNITO-UNDERSCORE!20200701-211238!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Preview!

### Device information
* Android device: 10
* Fenix version: 5.2.0 (Build #21701706)

**Comment by kbrosnan** [comment] 2020-07-01 19:41
Duplicate of #12002. There is now a placeholder image until the user activates the tab in Nightly builds.

**Comment by kolaente** [comment] 2020-07-01 19:43
@kbrosnan I see, thanks for the quick answer!

**Closed** 2020-08-28 21:26 UTC
Labels: needs:triage, 🐞 bug
