### ISSUE TITLE
GeckoView? support navigator.share 

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#7938] opened 2020-01-26 06:02 UTC
### Why/User Benefit/User Problem
I think Firefox for Windows 10 supports this but it doesn't for Android. Chrome on mobile definitely supports this. I don't think Chrome supports it on desktop. Edgium supports it while UWP Edge and IE don't iirc. Not sure about Safari. 

Well anyway, it's obvious why this is important.

### What/Requirements
User can share from a webpage
### Acceptance Criteria (how do I know when I’m done?)
When a user can share from a webpage

**Comment by kbrosnan** [comment] 2020-02-15 18:52
Closing as a dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=1476515

**Closed by kbrosnan** 2020-02-15 18:52 UTC
Labels: needs:triage, 🌟 feature request
