### ISSUE TITLE
FNX-4577 ⁃ [Bug] Crash when using voice input for Search with disabled Google App

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#10803] opened 2020-05-20 16:19 UTC
## Steps to reproduce
1. Deactivate voice input on Android, e.g. by disabling the Google app
1. Open Fenix Nightly
1. Tap on search area of bottom bar
1. Tap on microphone symbol (see #1216)

### Expected behavior
A snackbar is displayed informing the user about missing permissions or deactivated voice input search / microphone symbol is not shown at all

### Actual behavior
The app crashes. This does not change if I allow Fenix to access my microphone or not.

about:crashes shows:
_android.content.ActivityNotFoundException:
No Activity found to handle Intent
{ act=android.speech.action.RECOGNIZE_SPEECH (has extras) }_

Sidenote: I could not find my crash reports on crash-stats.mozilla.org. Also, accessing about:crashes via about:support does not show any sent crash reports.

### Device information
* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version:
Nightly 200520 06:01 (Build #2015741361)
42.0.20200518130035, f0cb2cca9
GV: 78.0a1-20200517094345
AS: 0.58.2

**Comment by astarq** [comment] 2020-05-21 13:03
Do you have the google app disabled?

**Comment by B0pol** [comment] 2020-05-21 14:05
I can reproduce. I don't have any Google apps or services, I just have microG.

**Comment by astarq** [comment] 2020-05-21 14:09
I have THE google app disabled, which acts as the voice recognition provider, that'll be why it crahses. The mic button shouldn't exist when that's the case, like in other apps

**Comment by hwinnemoe** [comment] 2020-05-22 11:42
> 
> 
> Do you have the google app disabled?

Yes, the Google App is disabled. Also, Fennec does not show me the microphone button.

**Comment by astarq** [comment] 2020-05-22 11:44
Fennec has it right then.

**Comment by Diana-Rus** [comment] 2020-05-22 14:11
Hi, thank you for the report I can also reproduce this with Samsung Galaxy S9 (Android 8) on Fenix Nightly 5/22.

**Comment by yoasif** [comment] 2020-05-22 21:39
In case you needed another log:

https://gist.github.com/yoasif/66a63d8d0d217a4b8f97e8731a52814c

I also don't have a Google App on this device (Moto G XT1031).

**Comment by Diana-Rus** [comment] 2020-05-29 07:36
Hi, verified with Samsung Galaxy S9(Android 8) and Google Pixel 3 XL (Android 9) 
Scenario 1 - Mic is not displayed in browser when Google app is disabled - PASS
Scenario 2 - Mic is displayed in search widget when Google app is disabled while widget is set before disabling the Google app - FAIL (crash present)
Scenario 3 - Mic is not displayed when Google app is disabled when the widget is added after the Google app is disabled - PASS

**Comment by sblatz** [comment] 2020-05-29 17:13
Hi @Diana-Rus that sounds like an existing bug with the search widget and is unrelated to the changes I made. I'll file a separate bug for that. Since the crashes with voice in search screen are fixed, I will close this :)

**Closed** 2020-08-11 01:53 UTC
Labels: Feature:Voice, S1, 🐞 bug
