### ISSUE TITLE
[Bug] A white area covers the bottom of a website

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#20279] opened 2021-07-07 08:34 UTC
## Steps to reproduce
1. Go to https://www.travelandleisure.com, or any of the links from this website.
2. Scroll the website.

### Expected behavior
No issues when browsing the website.

### Actual behavior
A blank/white area covers the bottom of the website.

### Device information
* Devices: OnePlus 5T (Android 10), Samsung Galaxy Note 8 (Android 9)
* Firefox for Android version: RC 90.1.0
* Not reproducible on 7/7 Nightly, or Beta 90.0.0-beta.6
* On Chrome, on that area are displayed commercials
* Disabling the ETP doesn't fix the issue

https://user-images.githubusercontent.com/40694158/124726525-8515b900-df16-11eb-921f-39a2b89a6b69.mp4

**Comment by Mugurell** [comment] 2021-07-07 09:12
That seems to be just the background for ads shown by the website.
It seems to rotate them at every 30 seconds and they sometimes have issues loading.


https://user-images.githubusercontent.com/11428869/124733101-8b0e9880-df1c-11eb-9e09-ebe55f1c2a47.mov

**Comment by lobontiumira** [comment] 2021-07-07 09:28
Well, on the OnePlus device, these commercials aren't loading at all on RC build.

**Comment by Nickoriginal** [comment] 2021-07-07 18:24
I think this is mostly the site's fault because it happens on my Chrome 91 too.
<img src = https://user-images.githubusercontent.com/85299944/124809803-35aca880-df69-11eb-9256-188099c7e347.jpg width = 35%>
Also look at the list of all trackers, what cannot work together perfectly and can cause various errors.
<img src = https://user-images.githubusercontent.com/85299944/124809958-668cdd80-df69-11eb-877a-46ed80f0d73d.jpg width = 45%> <img src = https://user-images.githubusercontent.com/85299944/124810022-7c020780-df69-11eb-84b1-da86a5437745.jpg width = 45%>

**Comment by SoftVision-LorandJanos** [comment] 2022-01-04 14:22
This issue is no longer reproducible with the latest builds:
- latest Release (95.2.0).
- latest Nightly (2022-01-04).

Devices used:
- Oppo Reno 6 (Android 11).
- Samsung Galaxy Tab S3 (Android 9).

Closing the ticket as verified.

**Closed by SoftVision-LorandJanos** 2022-01-04 14:22 UTC
Labels: 🐞 bug, S3, Feature:Browsing, needs:triage, wontfix
