### ISSUE TITLE
FNX3-16629 ⁃ [Bug] long pressing in empty input fields shows select all in context menu

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2860] opened 2019-05-26 04:17 UTC
## Steps to reproduce
1. Navigate to form whereby you need to login to a website
1. Long press on either username or password field

### Expected behavior
User should see "Paste" and "Auto Fill" by default. 

### Actual behavior
It offers to select all, despite the field being empty. 

### Device information
* Android device: Android 8, LG G6
* Fenix version: 1.0.1921

**Comment by vesta0** [comment] 2019-05-31 00:40
I can't reproduce this, I only get the Paste option. @pwd-github is this still happening?

**Comment by pwd-github** [comment] 2019-05-31 08:01
This is very much still the case @vesta0

Even the search field on GitHub shows select all.

**Comment by makotokato** [comment] 2019-06-05 04:56
This is GV issue such as https://bugzilla.mozilla.org/show_bug.cgi?id=1448730

**Comment by vesta0** [comment] 2019-06-05 16:49
@cpeterso is this bug tracked in GV as well?

**Comment by cpeterso** [comment] 2019-06-05 19:53
> @cpeterso is this bug tracked in GV as well?

Let's use @makotokato's bug for this issue. I've tagged the bug for Fenix post-MVP.

https://bugzilla.mozilla.org/show_bug.cgi?id=1448730

**Comment by cpeterso** [comment] 2019-10-03 01:36
The GV bug was fixed in GV 71 Nightly last week, so I will remove this issue's `needs:gv` and `waiting` labels.

https://bugzilla.mozilla.org/show_bug.cgi?id=1448730#c14

**Comment by sflorean** [comment] 2020-04-08 14:37
Tested on Nightly 04/08 and the **Paste** option is displayed following the steps from the description, and also on search fields (google.com, twitter).
However, the "Auto-fill" option is **not** displayed.

@pwd-github can you please confirm that this is fixed for you, also.

**Comment by pwd-github** [comment] 2020-04-08 15:14
> Tested on Nightly 04/08 and the **Paste** option is displayed following the steps from the description, and also on search fields (google.com, twitter).
> However, the "Auto-fill" option is **not** displayed.
> 
> @pwd-github can you please confirm that this is fixed for you, also.

Confirmed

**Closed** 2020-08-12 17:41 UTC
Labels: P2, eng:qa:verified, 🐞 bug
