### ISSUE TITLE
[Bug]cannot receive push notification from tinder 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#15460] opened 2020-09-26 15:20 UTC
I m not able to get push notification from tinder in Samsung internet everything work as expected.
see screenshot:
https://drive.google.com/file/d/19aZneLskwq0PNRrDGq5BwFl1VfnOT07O/view
is this normal?

**Comment by jonalmeida** [comment] 2020-09-29 18:44
Duplicate of #15028

**Closed by jonalmeida** 2020-09-29 18:44 UTC
Labels: needs:triage, 🐞 bug
