### ISSUE TITLE
[Bug] Not able to scroll to tabs

### ISSUE THREAD

**Issue by Wattsernaim** [mozilla-mobile/fenix#20086] opened 2021-06-18 04:25 UTC
Tabs not scrolling. Having many tabs open for later research seems to be the norm on all browsers but not accessing them is very frustrating. After trying all areas of the screen it will eventually work but once a tab is chosen the same problem persists. Running on a Samsung galaxy S7 android version 8.0.0 and firefox version 89.1.1

**Comment by SoftVision-LorandJanos** [comment] 2021-06-18 14:30
Hi @Wattsernaim  ! Thank you for your report! I am not able to reproduce the issue you described. Could you please make a video of the issue next time you encounter this issue? Thank you!
Tested on the latest Nightly (91.0a1 Friday 6/18 @ 5:07 AM) and on Release 89.1.1 (Build #2015812947).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Comment by eliserichards** [comment] 2021-06-21 15:27
Is this happening in the tabs tray? is it stuck loading or does it seem frozen? Definitely need more info here to reproduce :)

**Comment by amedyne** [comment] 2021-06-23 17:44
Looks like a similar problem to #17212

**Comment by SoftVision-LorandJanos** [comment] 2021-06-24 08:16
As this issue is covered in #17212, I will close this one. @Wattsernaim if you have any extra information you discover in the meantime, please leave it as a comment in the mentioned issue. Thank you!

**Closed by SoftVision-LorandJanos** 2021-06-24 08:16 UTC
Labels: needs:STR, needs:info, 🐞 bug
