### ISSUE TITLE
[Bug] Tab closed popup does not close

### ISSUE THREAD

**Issue by josephdfarkas** [mozilla-mobile/fenix#8738] opened 2020-02-25 20:02 UTC
## Steps to reproduce
Close a tab and wait
### Expected behavior
Disappears after a few seconds
### Actual behavior
Does not disappear until clicking undo
### Device information
* Android device: Moto G6 running Android 9
* Fenix version: Firefox Preview 3.2.1 (Build #20250349)
28.0.3, f0dc2cadd
GV: 73.0-20200123172213

**Comment by cadeyrn** [comment] 2020-02-25 21:49
Duplicate of #7799, fixed in the next update.

**Comment by ekager** [comment] 2020-02-26 06:43
Closing as dupe

**Closed by ekager** 2020-02-26 06:43 UTC
Labels: needs:triage, 🐞 bug
