### ISSUE TITLE
[Bug] Unable to download image results from Google Images

### ISSUE THREAD

**Issue by openjck** [mozilla-mobile/fenix#19274] opened 2021-04-27 20:35 UTC
## Steps to reproduce

1. Navigate to images.google.com
2. Type a search term, for example, *fauci with dog*
3. Tap the magnifying glass icon or hit the return key to submit the search
4. Tap the first image result. A larger version of the image will appear with the title below. ([This](https://user-images.githubusercontent.com/933396/116308617-b5eaac80-a775-11eb-8f70-1ddbd64ed670.png) is the view I'm talking about.)
5. Long-press on this larger version of the image

### Expected behavior

A context menu appears. Among the items in the context menu is *Save image*, which can be used to save the image.

### Actual behavior

No context menu appears.

### Device information

* Device vendor / model and Android version: Pixel 4 XL / Android 11 / Build number RQ2A.210405.005
* Firefox for Android version: Firefox Nightly 210427 17:01 (Build #2015807115)

**Comment by openjck** [comment] 2021-04-27 20:36
Following the same *Steps to reproduce* in Chrome allows the image to be saved.

**Comment by Amejia481** [comment] 2021-04-27 20:46
I was trying to reproduce, but in my case I see the contextual menu after a long press. I'm using pixel 3 with Android 11 and latest nightly. 

https://user-images.githubusercontent.com/773158/116310339-d9aef200-a777-11eb-9bd9-7aab9a9ce98a.mp4

**Comment by openjck** [comment] 2021-04-27 20:50
@Amejia481 You skipped step 4. Tap that image first, then long-press on the larger image that appears.

**Comment by Amejia481** [comment] 2021-04-27 20:53
Oh, my bad sorry about that.

**Comment by Amejia481** [comment] 2021-04-27 21:16
I remember to see the issue before, this is a [webcompact](https://webcompat.com/) issue we don't receive the same treatment as chrome in some google pages see https://bugzilla.mozilla.org/show_bug.cgi?id=975444#c21

**Comment by MicroBeast** [comment] 2021-04-28 20:14
I have momentary 2 workarounds for that;

1. Use uBlock0 and add static filter ``www.google.com##.HxgyTd.Hxr4yc``
2. Change User Agent to Chrome. Not recommended as it will not give incentive to Webcompat issue from Google side. The first method work for me.

**Comment by openjck** [comment] 2021-04-28 23:57
I have also found that the [Google search link fix](https://addons.mozilla.org/en-US/android/addon/google-search-link-fix/) serves as a workaround.

**Comment by SoftVision-LorandJanos** [comment] 2021-04-29 13:16
Hi @Amejia481 ! Thank you for your report! I am able to reproduce the issue described by you. When trying to access the menu for download by log pressing on the image, a text below is selected as shown on the [video](https://user-images.githubusercontent.com/48829350/116556542-3b9d6200-a906-11eb-82e4-ad7faf9fc72d.mp4). I've tested on the Nightly version the issue was reported on (210427 17:01 Build #2015807115) and on the latest Nightly (210429 05:01) GV90.0a1, using a Motorola Nexus 6 with Android 7.1.1.

**Comment by Amejia481** [comment] 2021-04-29 13:22
Thank you all, I will proceed to close this ticket as there is nothing that we can do in Fenix/AC as it's a webcompact issue. The issue is tracked on https://bugzilla.mozilla.org/show_bug.cgi?id=975444#c21, please feel free to reopen otherwise. :)

**Closed by Amejia481** 2021-04-29 13:22 UTC
Labels: needs:triage, 🐞 bug
