### ISSUE TITLE
[UX] Help users clear their open tabs and easily find them later

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11582] opened 2020-06-15 03:24 UTC
## User Story
As a user with many open tabs, I want to have the option to close all tabs (or start from a clean homescreen) and have the option to easily and quickly restore a tab that I closed in my current/most recent session so I don't have to browse through all history items for it 

Specific user problems to address 
-no way currently to restore a tab that was closed prematurely or accidentally
-it's very difficult to find something specific in history if it's older than a day or if it's a specific page in a frequently used domain (e.g. a specific item on a shopping site) 

### Dependencies
- [ ] AC work to allow us to have a "last opened" value for tabs
- [ ] Fenix work to build up a Setting for it
- [ ] AC/Fenix work to build the close/restore functionality

Linked issues:
- [x] autoclose #4118
- [x] access recently closed tabs #2486
- [ ] tab tray CFR for auto close #14243

### Acceptance Criteria
* My browser helps me stay organized by not ending up with many open tabs that I am no longer using.
* I can access my recently closed tabs via a menu entry on open tabs or via History.
* On "Recently closed tabs" there is a link to see the full history.
* e 3-dot menu offers the same actions that history entries have.
* When the history is deleted, recently closed tabs are also removed

UX Flow:
https://app.abstract.com/share/4341a8c8-02f7-48a0-8952-98be0aef4c80?mode=design&sha=a3633820b169e4bc6ac37fe927c31d169dcd45d0

**Comment by FenixRevival** [comment] 2020-07-26 16:00
As I wrote in #12940 it'll be good to have Android handling tabs.

**Comment by FenixRevival** [comment] 2020-07-29 20:42
I've waited long enough, can we have some feedback on that? It's really an important feature for me and a regression from Legacy. Now Fenix is in Production.

I know the Team is doing its best, and I don't doubt they have *a lot* to do. But I wish we could have at least some ETA.

**Comment by mheubusch** [comment] 2020-08-19 14:59
@topotropic Can you confirm the Abstract file linked above is the correct/only one. I am looking for the Material banner component and don't see it here.

**Comment by topotropic** [comment] 2020-08-19 19:29
There's a GitHub issue for autoclose https://github.com/mozilla-mobile/fenix/issues/4118
and here's the one to access recently closed tabs: https://github.com/mozilla-mobile/fenix/issues/2486

**Comment by ekager** [comment] 2020-11-17 05:12
Closing because AFAICT all of these issues have been completed

**Closed by ekager** 2020-11-17 05:12 UTC
Labels: Feature:Discovery, Feature:Tabs, Skittle
