### ISSUE TITLE
Tint address bar and toolbar based on site

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17064] opened 2020-12-16 05:11 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
A feature present in chromium browser and more noticeable in vivaldi, the toolbar, status bar and address bar is tinted based on the site. Example red for gmail. 
Is it possible in fenix for tabs? It is already implemented in custom tab so why not in Firefox main tab too? 
Attaching screenshot of a custom tab of fenix

### How do you know that this problem exists today? Why is this important?
The sites will look more pleasing and soothing to eyes.. 

### Who will benefit from it?
Users who are using vivaldi or chromium browsers

![Screenshot_20201216-102729415](https://user-images.githubusercontent.com/58127841/102307728-10cff400-3f8b-11eb-98d1-6151952a5702.jpg)
![Screenshot_20201216-104018915 (1)](https://user-images.githubusercontent.com/58127841/102307751-234a2d80-3f8b-11eb-9bee-f9f6efc5cf14.jpg)

**Comment by jonalmeida** [comment] 2020-12-16 05:40
Duplicate of https://github.com/mozilla-mobile/fenix/issues/1178

**Closed by jonalmeida** 2020-12-16 05:40 UTC
Labels: needs:triage
