### ISSUE TITLE
[Bug] YouTube not loading

### ISSUE THREAD

**Issue by joeomalley1** [mozilla-mobile/fenix#18469] opened 2021-03-13 09:42 UTC
YouTube shows up as grey screen on Listverse
Video should load automatically
Only on Firefox mobile
Have uninstalled all add-ons
Uninstalled Firefox Mobile re-installed
Latest version

**Comment by Mugurell** [comment] 2021-03-13 10:31
Duplicate of https://github.com/mozilla-mobile/fenix/issues/18450.
Please follow the progress there.

**Closed by Mugurell** 2021-03-13 10:31 UTC
