### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by mahidhar96** [mozilla-mobile/fenix#16588] opened 2020-11-16 06:28 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
* Go to this link: https://www.asram.in/asram/Students-Info.html
* Click on "MBBS 1st & 2nd Semester"

OR

* Open this link https://www.asram.in/asram/PDF'S/Students%20Info/M.B.B.S%20Students%20Info/MBBS-1st-2nd-Semester-1.pdf

### Expected behavior
Should download and open a PDF (working on Google Chrome).

### Actual behavior
It either shows downloading notification for a long time OR throws downloading error.

### Device information

* Android device: Samsung Galaxy A50(One UI 2.0, Android 10), Redmi 4A(MIUI 10.2.3, Android 7.1.2), Redmi Note 5(MIUI  11.0.2, Android 8.1.0)
* Fenix version: 82.1.3

**Comment by kbrosnan** [comment] 2020-11-17 00:40
Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/15378

**Closed by kbrosnan** 2020-11-17 00:40 UTC
Labels: needs:triage, 🐞 bug
