### ISSUE TITLE
[Bug] report site icon wrong color on dark theme

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#19542] opened 2021-05-18 12:20 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
go to setting, personalitation, dark theme
Go tobany web page and click on the hamberger menu
Look at the report site icon color

### Expected behavior
The color is the same as other ico 

### Actual behavior
Icon is black instead of white

### Device information
Android 11, pixel 4a

Firefox nightly
90.0a1 (Build #2015810955)
AC: 90.0.20210516190059, be02514d7
GV: 90.0a1-20210516091748
AS: 76.0.0

Monday 5/17 @ 5:40 PM

**Comment by cadeyrn** [comment] 2021-05-18 12:30
Duplicate of #11367.

**Closed** 2021-05-18 14:48 UTC
Labels: needs:triage, 🐞 bug
