### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by siggib4** [mozilla-mobile/fenix#3730] opened 2019-06-27 21:14 UTC
Preview ist a very fast and intuitive browser. Good job!

I was happy to see there is a dark theme. Unfortunately opened site are displayed in light theme. Could you please provide a dark mode not only a dark theme, meaning the opened site are also displayed with dark background and light letters? That would be fantastic. 😀👍

* Android device: Samsung s10+
* Fenix version: 
1.0.0 (Build #11721515 🦎 68.0-20190611143747)

**Comment by yoasif** [comment] 2019-06-27 21:15
Dupe of https://github.com/mozilla-mobile/fenix/issues/2139

**Comment by ekager** [comment] 2019-06-27 21:16
Thanks for filing! We currently will show sites in dark mode that support the CSS preferred color scheme tag! But yes this is a dupe of #2139 :)

**Closed by ekager** 2019-06-27 21:16 UTC
Labels: 🐞 bug
