### ISSUE TITLE
FNX-4990 ⁃ [Bug] Password autofill always for org.mozilla.fenix with Bitwarden

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-mobile/fenix#1379] opened 2019-04-04 10:29 UTC
## Steps to reproduce
* Have bitwarden (not sure if it also applies to other pwanagers)
* Open Form that triggers pw autofill
* Click on "bitwarden vault is locked"
* Unlock vault

### Expected behavior
Bitwarden suggests logins for the host the form is on.

### Actual behavior
Bitwarden shows logins for org.mozilla.fenix

### Device information
* Android device: Nexus 5X
* Fenix version: latest from gplay?

**Comment by IOI-655321** [comment] 2019-04-04 10:40
Have you checked with Kyle (Biwardens dev) that he's added Fenix as a supported browser? He has to enable any browsers as he goes I believe, he certainly used to when he added support for DDG browser and Firefox focus.

**Comment by freaktechnik** [comment] 2019-04-04 17:56
I have not, since I am barely aware of how Android apps like password managers interact with browsers, and just started using Fenix and noticed that I always had to search for the actual site I wanted to enter my credentials for.

**Comment by vesta0** [comment] 2019-04-09 05:08
Related to #1160

**Comment by djc** [comment] 2019-05-16 08:41
On the mailing list, it was suggested this also happens with Lastpass, which means it's probably not a Bitwarden-specific problem (but instead, Fenix is incorrectly reflecting the origin to the addons API?).

**Comment by callahad** [comment] 2019-05-16 09:47
This will be fixed in the next release of Bitwarden: https://github.com/bitwarden/mobile/issues/477

We're also tracking at https://bugzilla.mozilla.org/show_bug.cgi?id=1538385

**Comment by dbperez** [comment] 2019-05-16 15:07
Does a ticket also need to be filed with LastPass to whitelist the new browser?

**Comment by freaktechnik** [comment] 2019-05-16 15:19
@dbperez according to the bugzilla bug that's being tracked.

**Comment by softvision-miralobontiu** [comment] 2019-05-27 09:52
I will close this as a duplicate of #1635 because that has more info.

**Closed** 2020-08-11 11:32 UTC
Labels: 🐞 bug
