### ISSUE TITLE
[Bug] find in page overrides permanent toolbar

### ISSUE THREAD

**Issue by isthisrubble** [mozilla-mobile/fenix#18248] opened 2021-03-02 04:13 UTC
## Steps to reproduce

- open Firefox.
- in settings > customise, make sure toolbar is set to "top" and "scroll to hide toolbar" is disabled. (unsure how much of this is related to issue, but being clear about my set-up)
- open a text-heavy webpage.
- open "find in page" from menu.

### Expected behavior

find in page toolbar thing opens, rest of Firefox is unaffected.

### Actual behavior

find in page toolbar thing opens, top toolbar vanishes. the only way to access other tabs, settings etc now is to close the find in page toolbar. if this is necessary, reopening it later does not retain the searched term.

### Device information

* Samsung Galaxy S10e, Android 11
* Firefox for Android version 86.1.1

**Comment by kbrosnan** [comment] 2021-03-02 16:57
This is pretty much a duplicate of https://github.com/mozilla-mobile/fenix/issues/9165

**Comment by isthisrubble** [comment] 2021-03-03 02:05
> This is pretty much a duplicate of #9165

looks like it, sorry, I did search first but mustn't have got the right keywords

**Closed** 2021-03-03 02:06 UTC
Labels: Feature:FindBar, Feature:Toolbar, 🐞 bug
