### ISSUE TITLE
[Bug] Switching tabs shows a white screen

### ISSUE THREAD

**Issue by bogas04** [mozilla-mobile/fenix#3904] opened 2019-07-05 13:13 UTC
## Steps to reproduce
Open Fenix
Open some tabs
Switch between them

![Screencast of STR](https://thumbs.gfycat.com/ForsakenInsecureGemsbuck-size_restricted.gif)
### Actual behavior
No white screen should occur/ghosting of tabs idk.

### Device information

* Android device: OnePlus 3T, Android Pie
* Fenix version:
Nightly 190704 18:04 (Build #11851810)
📦: 3.0.0
🦎: 68.0-20190612114833

**Comment by vesta0** [comment] 2019-07-09 20:59
@AmyYLee would #1289 address this bug?

**Comment by kbrosnan** [comment] 2019-07-09 22:41
Closing as dupe of #1289

**Closed by kbrosnan** 2019-07-09 22:41 UTC
Labels: 🐞 bug
