### ISSUE TITLE
[Bug] fivethirtyeight.com, other sites do not autocomplete from history in URL bar, unlike other sites

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8560] opened 2020-02-19 23:18 UTC
## Steps to reproduce
- Click URL bar
- Type fivethirtyeight.com and hit enter
- Click URL bar
- Type "f"

### Expected behavior
"fivethirtyeight.com" autocompletes. If I visited rockpapershotgun.com and typed "r", this would be the behavior.

### Actual behavior
"fivethirtyeight.com" does not autocomplete as this works for other pages. Even if I type "fiv" for which there is no built-in autocomplete, nothing completes.

### Device information

* Android device: P2
* Fenix version: Nightly 200219

**Comment by mcomella** [comment] 2020-02-19 23:24
Bas mentioned it's not just on fivethirtyeight and occurs randomly:

> nos.nk for example works, but nos.nl doesn't

**Comment by codrut-topliceanu** [comment] 2020-03-02 12:16
Behaviour depends on the keyboard you are using. I couldn't reproduce the bug using swiftkey but I was able to with Gboard.

**Cause:**
The cause comes from `InlineAutocompleteEditText.kt` and it's way of trying to detect whether or not the user had pressed backspace. In `override fun afterTextChanged(editable: Editable)` the code for detecting backspace is `(textLength < textLengthBeforeChange || textLength == 0)` which also triggers the first time you press the URL bar to go to the SearchFragment (url text is selected) and you press a key like "f". The previous text was longer than the new one, so we get no autocomplete.
This code was a fix for [AC #5168](https://github.com/mozilla-mobile/android-components/issues/5168)

I have managed to create a fix for this and have tested it on Gboard and Swiftkey. PR incoming.

**Comment by codrut-topliceanu** [comment] 2020-03-09 08:45
Created a [new issue](https://github.com/mozilla-mobile/android-components/issues/6202) on AC for this.

**Comment by vesta0** [comment] 2020-04-23 14:08
@codrut-topliceanu is this fixed? I see that the AC issue was closed.

**Comment by codrut-topliceanu** [comment] 2020-04-23 14:18
Yep. Should be fixed.

**Comment by abodea** [comment] 2020-04-24 12:55
Verified as fixed on Nightly 4/24 with Google Pixel 4 XL (10).

![20200424-153436](https://user-images.githubusercontent.com/42831109/80214548-b40e7a80-8643-11ea-9b40-c8ec57849ffa.gif)

**Closed by abodea** 2020-04-24 12:55 UTC
Labels: Feature:History, Feature:Search, eng:qa:needed, needs:ac, 🐞 bug

**Comment by codrut-topliceanu** [comment] 2020-04-24 13:04
@abodea Thank you. I removed the tag.
