### ISSUE TITLE
please bring back old behavior when tapping url bar

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#11070] opened 2020-05-29 23:38 UTC
one thing I really miss form old Firefox was the ability to bring both top sites and search when tapping url bar now fenix when tapping url bar just let perform a search. 
even Samsung internet browser copied old Firefox behavior.
please bring it back. 
I M using fenix 44.0.20200527130120 on android 7.1.2

**Comment by kglazko** [comment] 2020-06-01 22:32
Just to clarify, are you able to scroll down the list to view history items? We have a similar feature request here that sounds like it could describe your issue: https://github.com/mozilla-mobile/fenix/issues/1161

**Comment by kbrosnan** [comment] 2020-09-09 17:01
Closing this out as a duplicate of #1161

**Closed by kbrosnan** 2020-09-09 17:01 UTC
Labels: Feature:Search, feature request 🌟

**Comment by 0xTyagi** [comment] 2020-11-11 05:13
hi @kbrosnan 

How this issue is duplicate of mentioned  issue.  These are entirely different.
