### ISSUE TITLE
[Bug] URL bar autocomplete is only available part of the time

### ISSUE THREAD

**Issue by djc** [mozilla-mobile/fenix#7432] opened 2019-12-31 08:54 UTC
## Steps to reproduce

1. Start typing a previously typed/visited URL in the URL bar, such as newsblur.com

### Expected behavior

After one or two characters typed, the autocomplete widget (purple-background completion) appears and stays in place until my input diverges from it.

### Actual behavior

Autocompleted URL only appears on every other keypress, for example:

- "ne" yields `ne*wsblur.com*`
- typing a `w` removes the autocompletion and yields just `new`
- typing an `s` reactives the completion, yielding `news*blur.com*`

And so on, such that completion only works on odd-sized input.

### Device information

* Android device: Pixel 2
* Fenix version: current nightly

This is a regression from a few weeks ago.

**Comment by sv-sdeiac** [comment] 2020-01-03 14:46
Closing as a duplicate of bug #6935, if someone has additional information regarding this issue, please fill them on the ticket #6935, thanks.

**Closed by sv-sdeiac** 2020-01-03 14:46 UTC
Labels: Feature:Search, P2, S2, needs:ac, 🐞 bug
