### ISSUE TITLE
[UX Feedback] Tabs Tray

### ISSUE THREAD

**Issue by tstackhouse** [mozilla-mobile/fenix#14503] opened 2020-08-30 21:04 UTC
Just leaving some feedback on the new browser, so far it's been really great, though I've noticed that the tabs tray behaviour is significantly different than I'm the old version, gone are the columns of cards and they're replaced with a list with a left aligned thumbnail that is significantly smaller than the old list, not to mention that the ordering is reversed, with the newest tab on top, not on the bottom. Are there any plans to make this configurable? It would be awesome to have the old UX back, as the current list doesn't "feel" like looking at all my open tabs, which easily ranges from 30-70+ on any given day.

**Comment by hwinnemoe** [comment] 2020-08-31 18:22
Duplicate of #13098 and #10365

**Closed** 2020-09-01 02:37 UTC
Labels: needs:triage
