### ISSUE TITLE
Fenix prevents screen/display lock after timeout if media played previously

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#27897] opened 2022-11-18 14:02 UTC
### Steps to reproduce

1. Open any website. Observe that the screen gets locked after the screen timeout threshold set in OS.
2. Open any website and play any short video.
3. After this, close the tab and open another.
4. Open a completely different website.
5. Wait for the screen to time out.
6. Screen permanently on.
7. Switch away from Fenix.
8. Timeout works.
9. Switch back to Fenix.
10. No more screen timeout.

### Expected behaviour

The screen should turn off after the timeout.

### Actual behaviour

The screen remains on permanently, as long as you're on Fenix.

### Device name

multiple

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

105.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22012)

**Comment by makotokato** [comment] 2023-01-13 04:10
@opusforlife2, I cannot reproduce this on Android 13 since I don't have Android 12 device. Could you provide exactly repro step?

### STEP
1. Open https://www.google.com/
2. Create new tab then open https://dl8.webmfiles.org/big-buck-bunny_trailer.webm in this new tab
3. After stopping video, close this tab
4. Create new tab then open http://neverssl.com in this new tab
5. Wait for the screen off
6. Push power button to turn on screen
7. Change to different app (Settings app)
8. Wait for the screen off
9. Push power button to turn on screen
10. Back to Firefox

### RESULT
After timeout, screen is off

**Comment by makotokato** [comment] 2023-01-16 15:57
> Try a website like Reddit, with embedded videos.

I use something of https://www.reddit.com/r/videos/ instead, but I cannot reproduce this unfortunately.

**Comment by makotokato** [comment] 2023-01-19 02:45
@opusforlife2
could you provide an example URL for step[ 2.?

**Comment by cpeterso** [comment] 2023-01-30 03:09
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813416

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2023-01-30 03:09 UTC
Labels: 🐞 bug, needs:triage
