### ISSUE TITLE
Suggestions for collections, start page and search engine switcher

### ISSUE THREAD

**Issue by wurstsemmel** [mozilla-mobile/fenix#4031] opened 2019-07-12 16:56 UTC
### Why/User Benefit/User Problem

Overall
Nicely increased speed when rendering webpages.

a) Collections
The new collections concept feels like a bookmark folder. Collections should rather feel like a tab group. After clicking a collected tab Firefox opens the tab and it shows up under open tabs. It makes no sense that a collected tab (by definition it is already a tab) opens as a new tab, basically duplicating itself. If all open tabs and collected tabs are treated the same way we would have all tabs open and some are grouped in collections. At the moment the collections concept is confusing as it rather feels like a bookmark folder and not a collection of tabs. In other words we have now collected tabs which are treated like closed tabs which need to be (re-)opened. As said collected tabs should not need to open a new tab when accessing them. 

b) Start page
- After scrolling in the opened tab list the list keeps moving due to the magnetic animation of the big Firefox logo. This makes it difficult to hit the moving target with the finger. Please switch the magnetic behaviour off. 
- Navigating to a new website from the start page is more complicated than before. No recent sites list, collections need scrolling and additional touch. It should be easier to access recent sites and collections.

c) Search engine switcher
Switching to another search engine when searching through address bar is one click more than before. Please go back to the old interface to pick alternative search engines. 

### What/Requirements

a) Consider changes to the collections concept.
b) Switch off magnetic behaviour of firefox logo on start page and add a recent sites or make collections easier to access.
c) Consider to implement the old way of choosing alternative search engines (great feature!). 

### Acceptance Criteria (how do I know when I’m done?)

a) Collections do not feel like a bookmark folder anymore.
b) No magnetic firefox logo on start page and easier access to frequent used pages
c) Easier switch to alternative search engines

**Comment by NotWoods** [comment] 2019-12-23 07:04
Thank you for the suggestions. In the future its helpful to file separate requests instead of bundling them into one place so that we can close them one-by-one as we implement the features!

a) Duplicate of #4285
b) Now implemented 😄 
c) Duplicate of #4333

**Closed by NotWoods** 2019-12-23 07:04 UTC
Labels: 🌟 feature request
