### ISSUE TITLE
[Bug] SharedArrayBuffer not defined on Android (firefox 83.1.0)

### ISSUE THREAD

**Issue by hsdk123** [mozilla-mobile/fenix#16773] opened 2020-11-29 15:25 UTC
![image](https://user-images.githubusercontent.com/4100142/100546040-21633900-322d-11eb-92fe-dfa1eee59a1c.png)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/SharedArrayBuffer

According to the docs here, full support has been made since 79, but I see an issue on 83. 

I can confirm the page running on the desktop version, hence this isn't a csp issue.

**Comment by cadeyrn** [comment] 2020-11-29 15:29
Duplicate of #10722.

**Comment by kbrosnan** [comment] 2020-12-01 18:49
Closing as a duplicate

**Closed by kbrosnan** 2020-12-01 18:49 UTC
Labels: needs:triage, 🐞 bug
