### ISSUE TITLE
[Bug] After downloading a PDF, tapping on notification opens it in files. It should open in PDF reader.

### ISSUE THREAD

**Issue by Sgt-Miller** [mozilla-mobile/fenix#6432] opened 2019-11-04 15:40 UTC
## Steps to reproduce
Download a PDF. Tap the download completed message on notification bar.
### Expected behavior
In Firefox for Android, it asks me if I want to open using one of the PDF readers I have.  
![Screenshot_20191104-210247](https://user-images.githubusercontent.com/17806210/68133934-392c9880-ff19-11e9-9873-e470924cb762.png)
![Screenshot_20191104-210252](https://user-images.githubusercontent.com/17806210/68133935-392c9880-ff19-11e9-8717-29da77d4976d.png)

### Actual behavior
In Firefox preview, it asks me to open in one of the file managers I have
![Screenshot_20191104-210156](https://user-images.githubusercontent.com/17806210/68133955-42b60080-ff19-11e9-8ee7-a4b1b4a4428a.png)
![Screenshot_20191104-210205](https://user-images.githubusercontent.com/17806210/68133956-434e9700-ff19-11e9-970a-053315db19cd.png)

### Device information
Android 8
 2.2.0 (Build #12901947)
📦: 16.0.0, ab2555b20
🦎: 70.0-20191007080030

**Comment by NotWoods** [comment] 2019-11-05 20:47
Partial duplicate of #5959.

This has been fixed in Nightly, and will come to stable soon!

**Closed by NotWoods** 2019-11-05 20:47 UTC
Labels: Feature:Download, 🐞 bug
