### ISSUE TITLE
[Bug] Delete browsing history leaves twitter logged in

### ISSUE THREAD

**Issue by rosesandtea** [mozilla-mobile/fenix#27345] opened 2022-10-09 05:55 UTC
have a feeling this is intentional, although perhaps not explicit. i have to delete all app storage to log out of twitter (unless i use logout button). delete browsing history does not work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21766)

**Comment by rosesandtea** [comment] 2022-10-09 06:21
probably just going to switch back to chrome if it isnt handling something this basic correctly. big privacy concern....

**Comment by cadeyrn** [comment] 2022-10-09 08:48
Why should deleting the **history** log you out from a website? This doesn't make any sense. You have to delete your **cookies**. And this works in Firefox without any problems. Just tested it: I logged in Twitter, cleared my cookies, reloaded the Twitter page and I was logged out.

> probably just going to switch back to chrome if it isnt handling something this basic correctly. big privacy concern....

It's excatly the same in Chrome and in every other browser…

**Comment by SoftVision-LorandJanos** [comment] 2022-10-12 07:48
Hi @rosesandtea! Thanks for your report!
As this is not considered a bug, as you mentioned, it's the intended behavior, I'll close this ticket.

**Closed by SoftVision-LorandJanos** 2022-10-12 07:48 UTC
Labels: needs:triage

**Comment by rosesandtea** [comment] 2022-10-12 12:14
This is why I hate dealing with programmers in open source. You all look to  interpret someones words a particular way and then act on it. 

Maybe I didn't express myself clearly. If I select the option that clears the history cookies, all of it. It still happened that I'm logged in. 

Apparently, after playing with it, it only happens when you enable the option to automatically start in private mode (about:config). 

But you've already closed it. Terridict.

**Comment by rosesandtea** [comment] 2022-10-12 12:16
Yea
