### ISSUE TITLE
Allow Customised Fenix settings to be exported to a backup file format

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12962] opened 2020-07-26 16:12 UTC
Branched out from #12957. Please refer that issue for the whole context. And this is a continuation of #12961

Allow Customised Fenix settings to be exported to a backup file format. So that it becomes easy to take a backup of them so that they can import that file and get started without any hassles when they reinstall Fenix ams/or migrate/hop between different versions of Firefox. This could also include the default search engines they previously selected. I asked customised Fenix settings and other data types to be synced to Firefox account #12283 but that probably will not help to users who don't want to sign up for the Firefox account. This will provide a local backup tool of sorts.

Thank you. :grinning:

**Comment by kbrosnan** [comment] 2020-07-26 22:29
Closing as a duplicate of #12957. Until there is a plan to offer export the main issue is enough to track the request. The issue can be reopened if that is prioritized.

**Closed** 2020-08-28 23:03 UTC
Labels: needs:triage
