### ISSUE TITLE
FNX-14517 ⁃ Bookmarks should open in existing tab when navigating to bookmarks UI from a page

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#13336] opened 2020-08-06 06:59 UTC
### What is the user problem or growth opportunity you want to see solved?

Fennec migration, ease of use, user expectation, competitiveness.

### How do you know that this problem exists today? Why is this important?

Existing behavior in Fennec. People asking for it: https://www.reddit.com/r/firefox/comments/i4kmyz/firefox_android_opening_sites_from_bookmarks/

Previously requested: https://github.com/mozilla-mobile/fenix/issues/10837 https://github.com/mozilla-mobile/fenix/issues/10645

"Don't make me think" and a time saver.

Existing behavior in Chrome (where most new users will be switching from) and Firefox desktop. 

### Who will benefit from it?

People who are directly navigating from existing pages to bookmarks no longer have to clean up their old tabs; anyone who is used to the behavior in other Android browsers.

**Comment by cadeyrn** [comment] 2020-08-06 17:12
The current behaviour is intentional (there is at least one closed issue about this) and I definitely prefer the current behaviour.

**Comment by yoasif** [comment] 2020-08-06 17:21
@cadeyrn can you help me with a reference to the previous issue? I want to understand the thinking that went into that.

**Comment by yoasif** [comment] 2020-08-06 17:31
@cadeyrn the best I could find is https://github.com/mozilla-mobile/fenix/issues/3551 but that doesn't really capture the use case of opening a bookmarks when starting navigating from an existing tab, which is what my issue is about. I think that this is worth discussing.

**Comment by cadeyrn** [comment] 2020-08-06 17:43
>  This behavior is intended right now.

#10645

**Comment by yoasif** [comment] 2020-08-06 18:19
I think this merits another look, especially since that use case is not called out in any design documentation or stories that I have access to. The best I can find with that continues to be #3551, and there has not been any _discussion_ since then.

**Comment by person808** [comment] 2020-08-06 23:07
This appears to be the reason for the current behavior: https://github.com/mozilla-mobile/fenix/issues/1012#issuecomment-479608509

**Comment by yoasif** [comment] 2020-08-06 23:09
@person808 Thanks for looking into that. Today, Library no longer exists, so I think this is still worth another look. 😄

**Comment by binocry** [comment] 2020-08-07 07:48
so weird when on bookmark page 3 dot menu you can select "open to new tab" so what the point open bookmark to another tab as default?

**Comment by benediktwinder** [comment] 2020-08-24 20:50
The current behavior is not good for me. It would be great if i click on a bookmark it opens in the same tab, like other browsers.

**Comment by hotrodwinston** [comment] 2020-09-07 19:48
> The current behavior is not good for me. It would be great if i click on a bookmark it opens in the same tab, like other browsers.

Exactly this. Opening in a new tab by default without a way to change the behavior is going to drive people to other browsers - most of them chromium based making the web less open. At least give us an option.

**Comment by sonora** [comment] 2020-09-09 20:15
It also leads to secondary actions, more code, and complications: We now talk about automatically closing tabs in the background after a certain time, something which carries the risk of introducing even more in omprehensible behavior. And it was triggered by users working a lot with bookmarks and thus uncontrollably and mostly involuntarily opening large numbers of tabs...

**Comment by gtg947h** [comment] 2020-09-10 12:53
_Every other browser_ opens bookmarks in the same/existing tab.  Why does this need to be different?  90% of my browsing is from bookmarks and between this problem and having to choose close from the menu I spend way too much time clearing out old tabs.

**Comment by gtg947h** [comment] 2020-09-18 01:53
> _Every other browser_ opens bookmarks in the same/existing tab. Why does this need to be different? 90% of my browsing is from bookmarks and between this problem and having to choose close from the menu I spend way too much time clearing out old tabs.

This behavior is annoying me more and more... A 10 minute browsing session and I have 9 different tabs open; none of them were deliberately opened as new tabs.  What gives?

Between this and #5865, I find myself purging tabs every few minutes and it's really driving me nuts.  Yes, my desktop browser is set to do this, but that's almost an entirely different animal.

**Comment by haltbarmilch** [comment] 2020-09-18 06:17
> 
> 
> > _Every other browser_ opens bookmarks in the same/existing tab. Why does this need to be different? 90% of my browsing is from bookmarks and between this problem and having to choose close from the menu I spend way too much time clearing out old tabs.
> 
> This behavior is annoying me more and more... A 10 minute browsing session and I have 9 different tabs open; none of them were deliberately opened as new tabs. What gives?
> 
> Between this and #5865, I find myself purging tabs every few minutes and it's really driving me nuts. Yes, my desktop browser is set to do this, but that's almost an entirely different animal.

You speack from my heart. ;-)

**Comment by Diapolo** [comment] 2020-09-23 10:12
> > _Every other browser_ opens bookmarks in the same/existing tab. Why does this need to be different? 90% of my browsing is from bookmarks and between this problem and having to choose close from the menu I spend way too much time clearing out old tabs.
> 
> This behavior is annoying me more and more... A 10 minute browsing session and I have 9 different tabs open; none of them were deliberately opened as new tabs. What gives?
> 
> Between this and #5865, I find myself purging tabs every few minutes and it's really driving me nuts. Yes, my desktop browser is set to do this, but that's almost an entirely different animal.

You are getting the point here, it feels THAT weird using the "new" Firefox for Android, that I consinder not using it anymore. Why did the devs chose such an ugly and nonsene behaviour at all? It's also weird that clicking into the addressbar doesn't allow to anyhow select my favorites? WHO did "invent" this? Yes that is an inproductive rant, but it's a pitty that Mozilla destroys it's user base BY intention. This needs to be fixed, changed, looked at.

**Comment by maverick74** [comment] 2020-11-11 00:29
It is, for me, a major downside that everytime I want to use a tab to go to another page, I have to open that page in a new tab and then manually close the old one.

It's a really pita I would like to see reversed

**Comment by klint** [comment] 2020-11-20 11:04
I'm OK with the current behaviour, as I use tabs and the tab tray instead of bookmarks and history. 
So, if any change, please make it configurable with an option to reuse current tab or open a new one. Thanks

**Comment by PencilAmazing** [comment] 2020-11-26 19:57
> 
> 
> I'm OK with the current behaviour, as I use tabs and the tab tray instead of bookmarks and history (roughly speaking! :) ).
> So, if any change, please make it configurable with an option to either reuse current tab or open a new one. Thanks

Firefox should also have an option to be "smart": replace new tabs with the bookmarks tab and open a new tab if the current is in use.

**Comment by sonora** [comment] 2020-11-29 07:30
@klint Well, saying "I'm ok with a feature because I don't use it" is a little weird ... :)

Fact is no other browser seems to do things in this fashion? So if it is intended to do something completely different than current conventions, it had better be an obvious, beneficial, and undisputed innovation. If it is not that, and this discussion seems to indicate that much, it is simply an awkward and unconventional  oddity which will throw users off pace.

**Comment by maverick74** [comment] 2020-12-18 12:47
@yoasif 

Isn't it easy to just change the behavior of the "tap on bookmark" from opening on a new tab to open on the current tab?

it seems to be such a small detail that, however, as a big impact!

i mean... this is driving me near crazy!!!

**Comment by weijarz** [comment] 2021-01-24 04:03
It is a well known bad coding habit to open a new window for every link on a website, and when this behavior comes to the browser itself 🤔

**Comment by hotrodwinston** [comment] 2021-03-06 23:38
any progress on this? looking at other options as I'm just tired of it.

**Comment by yeezylife** [comment] 2021-05-11 00:48
I just wannna say,most browsers open bookmarks in existing tab,IOS Android or PC. Even firefox for PC do so..

**Comment by Obscerno** [comment] 2021-05-20 18:26
Repeating here what I suggested on #13336.

The functionality for bookmarklets is back in now (yay!), but tapping on them in the menu doesn't work (you have to work around it by typing in the address bar and tapping the suggestion).

I think that's related to this issue. The script fires, but it's executing in the new tab, not the page it was meant to be executed in. At least that's what I think is happening. If I'm right, resolving this would close two issues.

**Comment by simonvanderveldt** [comment] 2021-07-17 21:37
Chrome has been making some dumb changes the last couple of months, so figured I'd try Firefox again.
Ended up with 49 tabs after a single day, none of which I opened, I expected to have a single tab. No clue why the behavior is the way it is, but it simply doesn't make sense and is different from other browsers/what people expect.

How can this bug get attention?
It doesn't seem like a small thing I could hack/fix myself either, so back to Chrome it is I'm afraid until this gets fixed :(

**Comment by Dr-Battenburg** [comment] 2021-09-20 15:34
For the love of God, fix this.

**Comment by maverick74** [comment] 2021-10-29 23:39
Can someone from Mozilla, @kbrosnan  please, explain why can't we at least have an option on this subject???

It could be off by default, I don't care! In less than a week I ended up with more than 100 open tabs.
I don't care if they close automatically. That does not work for me. I want to be able to reuse my tab simple and easy as I always could...

Why aren't we allowed to reuse the tab we're in? What's your (Mozilla) point?

(it's these kind of "details" that make you keep loosing users, IYAM)

**Comment by SeburoSUMO** [comment] 2021-11-16 10:59
User feedback: https://support.mozilla.org/en-US/questions/1357977

**Comment by czlucius** [comment] 2022-01-01 09:43
I would like to help out with this issue.

**Comment by czlucius** [comment] 2022-01-01 10:26
I would like to work on this issue.
@kbrosnan has this design change been approved?

**Comment by czlucius** [comment] 2022-01-01 10:27
> The code responsible for this seems to be living here https://github.com/mozilla-mobile/fenix/blob/368d8cc214d23869063ba7fc5b0864a6bfa9223c/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt#L373
> Seems doable to just make some changes and test it.

This seems to be the code handling selection of "Top Sites" from the Home Screen(and not bookmark items)
Modifying this method results in a top site opening in the current tab but bookmarks still open in a new tab.

I will go look into the method for opening bookmarks, or if anyone knows it?

Thanks.

**Comment by czlucius** [comment] 2022-01-01 10:41
https://user-images.githubusercontent.com/58442255/147848814-2174a482-7ca7-4c7d-aece-99544ef5b5b2.mp4

**Comment by maverick74** [comment] 2022-01-10 18:33
@czlucius does this have any chance of landing (at least as an option)?

**Comment by Obscerno** [comment] 2022-01-10 21:58
@czlucius I'm really interested to know what happens in your debug version if you try to run a bookmarklet from the menu that's meant to be applied to the current page. For example, something simple like this bookmarklet that strips css from the page:

`javascript: (function() { var i, x; for (i = 0; x = document.styleSheets[i]; ++i) x.disabled = true; })();`

_(To add bookmarklets you have to bookmark a normal site, then replace the url in the bookmark with the script, by the way)_

**Comment by czlucius** [comment] 2022-01-11 06:17
> @czlucius does this have any chance of landing (at least as an option)?
> 
> Please!

I will have to wait for the fenix team to approve these changes first.

**Comment by czlucius** [comment] 2022-01-11 06:18
> @czlucius I'm really interested to know what happens in your debug version if you try to run a bookmarklet from the menu that's meant to be applied to the current page. For example, something simple like this bookmarklet that strips css from the page:
> 
> `javascript: (function() { var i, x; for (i = 0; x = document.styleSheets[i]; ++i) x.disabled = true; })();`
> 
> _(To add bookmarklets you have to bookmark a normal site, then replace the url in the bookmark with the script, by the way)_

Currently bookmarklets don't work yet, but I can try working on that.

**Comment by maverick74** [comment] 2022-01-11 10:10
> I will have to wait for the fenix team to approve these changes first(I don't know whether this design change is OK with the UX team of fenix)
> 
> I can go make a draft PR soon though, if no one from the fenix team replies to this thread.

From what I know the way fenix is working now is the way they intend it to work, so I assume they will only accept it if it comes as an off-by-default option... (would be great to have this behavior as the standard)

**Comment by czlucius** [comment] 2022-01-11 10:33
> > I will have to wait for the fenix team to approve these changes first(I don't know whether this design change is OK with the UX team of fenix)
> > I can go make a draft PR soon though, if no one from the fenix team replies to this thread.
> 
> From what I know the way fenix is working now is the way they intend it to work, so I assume they will only accept it if it comes as an off-by-default option... (would be great to have this behavior as the standard)

There seems to already be an "Open in new tab" button, although the behavior it triggers is different (it opens the tab tray with the tab instead of going to the tab).

**Comment by maverick74** [comment] 2022-01-11 11:37
> There seems to already be an "Open in new tab" button, although the behavior it triggers is different (it opens the tab tray with the tab instead of going to the tab).

Yes, i just don't get it why there is not one to "Open in the current tab"... The way it's working does not make any sense to me!!!
I have to delete all tabs at least once a week because i can't reuse the current tab i'm in to load a bookmark.

**Would be awesome if you could merge your changes!!! It would really be a good change :)**

**Comment by Obscerno** [comment] 2022-01-11 16:59
> Currently bookmarklets don't work yet, but I can try working on that.

> (Edit) I was building from an older version previously, apparently bookmarklets do work now.

Thanks for trying it! Yes they've been fixed relatively recently, the only issue now is that they aren't applied to the current page when called from the bookmarks menu. There is a workaround where you can type the bookmark name in the address bar and select the suggestion, but it would be nice if it worked from the menu too

**Comment by czlucius** [comment] 2022-01-12 13:03
This fix appears to cause another problem:
If the user opens a new tab through Tabs tray -> New Tab, and then clicks on the bookmark, presumably to open the bookmark in a new tab, the bookmark will still open in the user's previous tab.

**Comment by Cheap-Skate** [comment] 2022-01-12 18:32
> From what I know the way fenix is working now is the way they intend it to work, so I assume they will only accept it if it comes as an off-by-default option... (would be great to have this behavior as the standard)

This

@czlucius I really appreciate what you are doing but I am not sure the Fenix devs will accept it. Sorry to be so negative. Perhaps I am wrong so good luck.

I just don't understand why Fenix opens everything in a new tab. I really, really hate it. It sounds like many other users do too. It's so frustrating.

**Comment by czlucius** [comment] 2022-02-03 05:03
https://github.com/mozilla-mobile/fenix/pull/23169 just got merged into Fenix, you should see this soon in Nightly and Release.

**Comment by maverick74** [comment] 2022-02-03 09:54
@czlucius **THANK YOU SOOO MUCH!!!**

If I'm not asking too much, please share the link to the remaining bug you mentioned on the PR. Thanks :)

**Comment by haltbarmilch** [comment] 2022-02-03 13:21
@czlucius Thank you also very much. It works in the nightly version.

**Comment by Cheap-Skate** [comment] 2022-02-03 14:25
@czlucius it's fantastic!  Thanks!

Now there is a work-around for Fenix's ridiculous "Top Sites always open in a new tab" behavior:- just use Bookmarks instead of Top Sites. They open in the existing tab. It's one extra tap but it's much better than having 10000000 of tabs opening up all the time.  

If you could fix the behavior of Top Sites too you would be a Fenix Legend 👍

**Comment by klint** [comment] 2022-02-03 15:11
> If you could fix the behavior of Top Sites too you would be a Fenix Legend👍

Actually, that could also be a change in the behaviour of the "+" button rather than the "Top Sites"'s one.
Should the "+" button open a new tab by default (in this case, it make no sense to open a Top Site in the same tab where the "+" button was created. It is a "+" not a "=" ;)) ?
Or should it open whatever is chosen from the home page in the same tab where it was pressed, by default?
Well, I would appreciate a setting to toggle that default behaviour.
And of course, long-press menu on the + button should also be amended with more option ("Open in this tab")

**Comment by maverick74** [comment] 2022-02-03 15:27
I believe @klint has a point here!

In the "Top Sites" there should be an "Open In New Tab" option like in bookmarks!

**Comment by SoftVision-LorandJanos** [comment] 2022-02-04 09:56
Verified as fixed on the latest Nightly 98.0a1 (2022-02-04).
The bookmarked pages are opened in the current tab.

Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Oppo Reno 6 (Android 11).
- Google Pixel 4 (Android 12).

Closing the ticket as fixed.

**Comment by Obscerno** [comment] 2022-02-04 15:21
@SoftVision-LorandJanos #2871 can probably also be closed too; this change fixes the last issue with calling bookmarklets from the bookmarks menu.

**Comment by simonvanderveldt** [comment] 2022-02-04 21:57
Should a new issue be created for Top Sites? I assumed this used the same code as for bookmarks but that doesn't seem to be the case?

**Comment by klint** [comment] 2022-02-05 00:51
I don't think it is the same issue, assuming there is an issue with Top Sites. 
The current bug does not deal with bookmarks on the home page, but only in the menu.

**Comment by rocketsroger** [comment] 2022-02-22 19:40
Reopened this issue due to fix causing regression https://github.com/mozilla-mobile/fenix/issues/23837.

**Comment by simonvanderveldt** [comment] 2022-02-22 19:42
Oh no, we finally made it and now this :(
Can't the behavior not be fixed instead of directly falling back to reverting this change?

**Comment by rocketsroger** [comment] 2022-02-22 19:51
> Oh no, we finally made it and now this :( Can't the behavior be fixed instead of directly falling back to reverting this change?

I will assign this to myself and work on a modified fix.  However, since this is causing a regression, it's best to back it out and reapply a fix after.

**Comment by mdxe** [comment] 2022-02-22 20:18
Firefox has been a big regression the last few years... specially Firefox mobile.

**Comment by czlucius** [comment] 2022-02-23 05:12
It seems like opening in the current tab is more problematic than opening in a new tab, given Fenix's current state. I think reverting the change will be better for Fenix, so users would not be confused. 

To the Fenix devs (rocketsroger & jonalmeida), sorry for troubling you.

**Comment by maverick74** [comment] 2022-02-23 10:09
@rocketsroger can you please also work on the pinned bookmarks on the home tab 

[Improve home screen logic, always associate Home screen with an actual tab](https://github.com/mozilla-mobile/fenix/issues/20012#)(https://github.com/mozilla-mobile/fenix/issues/20012#issuecomment-1032881202)

They apparently share a lot...

**Comment by Cheap-Skate** [comment] 2022-02-23 10:56
@czlucius thanks for all your hard work.  I think it will bring benefits because it highlights how broken Fenix is at the moment. All other browsers give a simple choice to open in a new or existing tab. But Fenix does not, it is hardwired to open everything in a new tab.

Hopefully devs will take notice (I expect they already are). But I think fixing Fenix properly will be quite complicated.

**Comment by czlucius** [comment] 2022-02-23 10:58
> because it highlights how broken Fenix is at the moment. 

Just to clarify, I don't view Fenix as broken.

**Comment by rocketsroger** [comment] 2022-02-24 03:25
Thanks for reopening and tagging for me 👍

**Comment by SoftVision-LorandJanos** [comment] 2022-02-24 07:48
Verified as fixed on the latest Nightly build 99.0a1 (2022-02-24).
Device used: Oppo Reno 6 (Android 11).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-02-24 07:48 UTC
Labels: feature request 🌟, eng:qa:needed, Feature:Bookmarks, Feature:FennecTransition

**Comment by r6squeegee** [comment] 2022-05-24 07:57
I don't think this is fixed, 23946 only fixes this if you manually click on "settings" icon then  "bookmarks" then click on a bookmark. 

The scenario of bookmarks showing on the home page, doesn't work. This is my most common flow :
1) I'm on a web page, and done with it
2) I click on the url field to bring up the home screen so I can see my book marks (1 click on a big bar, adverse to 2 clicks for going to settings (small icdon) then bookmarks (on a popup menu))
3) I click on the next bookmark

That use to open the new page in the existing tab, it doesn't anymore. If I go through that routine with 8 bookmarks I end up with 8 tabs.

**Comment by rocketsroger** [comment] 2022-05-24 15:16
> I don't think this is fixed, 23946 only fixes this if you manually click on "settings" icon then "bookmarks" then click on a bookmark.

Created an issue to track this specific workflow.  https://github.com/mozilla-mobile/fenix/issues/25362.  Thanks

**Comment by rocketsroger** [comment] 2022-05-24 15:59
> And if you want to go down this rabbit hole, this comment lists some of the other strange behaviour on the homepage: [#20012 (comment)](https://github.com/mozilla-mobile/fenix/issues/20012#issuecomment-1020276854)

Looks like an [issue](https://github.com/mozilla-mobile/fenix/issues/23379) was opened by the contributor.  That said, it sounds very similar to the issue you have here with bookmarks on homepage.

**Comment by plwt** [comment] 2022-08-24 20:03
User feedback - https://support.mozilla.org/en-US/questions/1387083

**Comment by maverick74** [comment] 2022-10-12 14:48
Vote about how home opens bookmarks (new tab vs current tab) ongoing at:

https://connect.mozilla.org/t5/ideas/on-firefox-mobile-make-home-page-links-open-in-current-tab/idi-p/15672
