### ISSUE TITLE
FNX-5450 ⁃ [Fenix] Homescreen: Search bar drop-shadow disappears when scrolling up and doesn't return when you scroll back down.

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2093] opened 2019-04-26 20:41 UTC
## Steps to reproduce
1. Go to Fenix homescreen and look at the search bar drop shadow
1. Scroll up and watch it disappear. 
1. Scroll back down.
    1. Expected behavior
The drop shadow should appear when you scroll back down. 
    1. Actual behavior
The drop shadow is still gone when you scroll back down.
    1. Device information

* Pixel 3
* Fenix version: 1.0.1917
![Screenshot](https://user-images.githubusercontent.com/5992746/56835416-2a667a00-6842-11e9-8d1a-175c12bc4dd7.png)UNITO-UNDERSCORE!20190426-164028!
![Screenshot](https://user-images.githubusercontent.com/5992746/56835417-2a667a00-6842-11e9-89f7-a273fda6e370.png)UNITO-UNDERSCORE!20190426-164022!

**Comment by cadeyrn** [comment] 2019-04-26 21:05
Sounds like #1974.

**Comment by sblatz** [comment] 2019-04-26 21:14
I believe this is fixed. I'm not able to reproduce this on master. Closing as dup of #1974 that QA will verify next nightly.

**Closed** 2020-08-11 13:52 UTC
Labels: 🐞 bug
