### ISSUE TITLE
Control autoplay permissions per site

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11325] opened 2020-06-08 02:16 UTC
## User Story
* As a user, I want to be able to control autoplay permissions per site, so I can customize the behaviour for my trusted sites. 

## Dependencies
* We need new APIs to notify Fenix when a site is requesting auto-play permissions, and let it control what to do with the request.

### Acceptance Criteria
* I can control my autoplay permissions per site

Mocks:
https://share.goabstract.com/cdba1651-670e-4412-8721-4d70ca025ffd?collectionLayerId=35603d5c-263c-4c70-b3fe-1ae23bd449c8&mode=design

**Comment by amedyne** [comment] 2020-08-20 18:42
Created bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1660312 for tracking.

**Comment by owlishDeveloper** [comment] 2020-09-17 20:29
Hey folks, I am looking into this 👋

I have a question: We already have such API, `PermissionDelegate#onContentPermissionRequest`. Is there something about the API that makes implementing this feature using it impossible? CC @liuche @pocmo

**Comment by Amejia481** [comment] 2020-09-18 21:02
Thanks for the help @owlishDeveloper, 
I think we the existing api we can control the auto play permission per sites. We have to create some APIs for Fenix present/controll this requests in the UI, we can use this ticket to track the ac work https://github.com/mozilla-mobile/android-components/issues/4096. 

I think we need some help related to autoplay from gv team, on this issue https://github.com/mozilla-mobile/fenix/issues/11027, because when we provide that api users are going to encounter that issue, if you could take a look it will be much appreciated it.

**Comment by owlishDeveloper** [comment] 2020-09-22 22:40
@Amejia481 

So I looked at https://github.com/mozilla-mobile/fenix/issues/11027 - tried to reproduce on GVE. Interestingly, it reproduces on cellular connection only, but autoplays on WiFi. We already had a bug for that which I looked at and couldn't reproduce the issue https://bugzilla.mozilla.org/show_bug.cgi?id=1621825 I will re-open the bug and take a look at it again.

> I think we the existing api we can control the auto play permission per sites. We have to create some APIs for Fenix present/controll this requests in the UI, we can use this ticket to track the ac work mozilla-mobile/android-components#4096.

So it sounds to me you folks are satisfied with the existing GV endpoint and are taking the further work to AC department. I will close the Bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1660312

**Comment by Amejia481** [comment] 2020-09-23 13:48
Thanks!

**Comment by owlishDeveloper** [comment] 2020-09-30 22:39
@Amejia481 I am not sure what exactly is happening, but I am again not able to reproduce the bug in https://github.com/mozilla-mobile/fenix/issues/11027 - I just rebased on central, and it autoplays in GVE just fine on cellular connection. I closed the GV bugzilla ticket for now.

**Comment by owlishDeveloper** [comment] 2020-10-02 19:26
@Amejia481 a small update on the above ticket - I poked around some more, and turns out there's likely a timing issue with permissions. There's already work going on around that, so I duped the ticket on that one.

**Comment by Amejia481** [comment] 2020-12-03 21:54
For the moment I think we would need these engineering issues for this feature https://github.com/mozilla-mobile/fenix/issues/16846 https://github.com/mozilla-mobile/fenix/issues/16847 https://github.com/mozilla-mobile/android-components/issues/9131, and I will give them a try and file more if needed.

**Comment by Amejia481** [comment] 2021-01-25 16:23
As all the related tickets has been verified by QA we are removing the [feature flag in nightly](https://github.com/mozilla-mobile/fenix/pull/17624) and closing this issue.

**Closed by Amejia481** 2021-01-25 16:23 UTC
Labels: Feature:SitePermissions, Skittle, needs:ac, needs:gv, needs:investigation
