### ISSUE TITLE
[Bug] Having "Open links in apps" setting enabled will not allow links to be explicitly opened in Firefox

### ISSUE THREAD

**Issue by matejdro** [mozilla-mobile/fenix#12480] opened 2020-07-12 06:05 UTC
Open links in apps is useful feature, but sometimes I would want to open particular link in Firefox instead of in app. Android allows me to do that by removing defaults (so Android would ask me what to open the link with), but Firefox does not appear to support it.

This works fine in Chrome.

## Steps to reproduce
1. Have Youtube app installed on your phone
1. Disable defaults on Youtube app
1. Enable "Open links in apps" setting
1. Open any youtube link in Firefox
1. Android will ask you whether to open link in Firefox or in Youtube app
1. Select Firefox

### Expected behavior
I should get Youtube video page.

### Actual behavior
Firefox displays "302 Moved" page.

### Device information
Android device: OnePlus 7 Pro running Oxygen Os 10.0.6.GM21BA
Fenix version: 79.0.0-beta.5

**Comment by matejdro** [comment] 2020-07-12 06:06
Related to https://github.com/mozilla-mobile/fenix/issues/12113

**Comment by AndiAJ** [comment] 2020-11-06 08:18
Closing in favor of #12113

**Closed by AndiAJ** 2020-11-06 08:18 UTC
Labels: needs:triage, 🐞 bug

**Comment by Luke18033** [comment] 2022-12-24 09:05
That issue is completely different, the problem here is that Firefox doesn't respect Android's per-app "open links in app" settings, the 302 page appearing was just a side effect caused by that at the time. While that page no longer appears in current versions of Firefox for Android, this bug is otherwise still present and the system "open in app" settings are still ignored.
