### ISSUE TITLE
Ability to set your own home page

### ISSUE THREAD

**Issue by Northshorecowboy** [mozilla-mobile/fenix#15365] opened 2020-09-24 02:42 UTC
Why did Firefox eliminate the ability to set a personal home page? Users should be able to set a specific web address for their home page, or use the new blank version (with collections and history). This is yet another new feature that makes the user work more to get what they really want.

**Comment by kbrosnan** [comment] 2020-09-24 04:05
Duplicate of #7551

**Closed by kbrosnan** 2020-09-24 04:05 UTC
Labels: needs:triage
