### ISSUE TITLE
[Bug] search_count not logged in glean

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#2602] opened 2019-05-17 12:26 UTC
## Steps to reproduce
1. Start Fenix using glean.
1. Perform a couple of searches.
1. Send the app into the background in order to send telemetry.

### Expected behavior
The [search_count](https://github.com/mozilla-mobile/fenix/blob/master/app/metrics.yaml#L328) value is displayed in the gathered data.

### Actual behavior
The search_count variable is not logged.

### Device information
* Android device: any
* Fenix version: 5/17

**Comment by sblatz** [comment] 2019-06-25 16:32
This is a dupe of https://github.com/mozilla-mobile/fenix/issues/1158

**Closed** 2020-08-26 05:56 UTC
Labels: Feature:Telemetry, P1, 🐞 bug
