### ISSUE TITLE
[SitePermissions] Fenix crashes when tapping on "Blocked" in the site info panel

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7154] opened 2019-12-13 18:49 UTC
Steps to reproduce:
1. Open yelp.com and open 3-dot menu
2. Go to Settings -> Site permissions -> Location
3. Tap on "Blocked" to block location services
4. Tap back to get back to yelp.com
5. Tap on the Lock icon in the search bar to open the site info panel
6. Tap on "Blocked" next to Location

Expected:
Takes you to Site permissions -> Location

Actual:
Fenix closes/crashes

![Screenshot_20191213-134732](https://user-images.githubusercontent.com/5992746/70824026-47d75c80-1daf-11ea-86ba-501fca431e1b.png)

**Comment by kumarrus** [comment] 2019-12-19 13:21
Hi, I've looked into this issue and the crash is caused by a NPE because the scenario where a certain site permission is blocked globally but we get site permissions only based on host URL and thus `sitePermissions is null` is not handled. So, when we try to toggle the permission in [QuickSettingsController](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsController.kt)  the app crashes because of the following code:

`sitePermissions = sitePermissions!!.toggle(featureToggled).also { handlePermissionsChange(it) }`.

I have a fix for this. Can I take this bug?

**Comment by kumarrus** [comment] 2019-12-25 04:44
@boek @ekager @AmyYLee , any updates on this? Can I take on this bug?

**Comment by boek** [comment] 2019-12-25 06:11
@kumarrus definitely! Thank you!

**Comment by marcinwiacek** [comment] 2020-01-07 23:26
hmmmm, hmmmm, hmmmm, https://github.com/mozilla-mobile/fenix/issues/6715 about this was submitted even earlier and can be merged.

**Comment by sv-sdeiac** [comment] 2020-01-10 14:44
Verified as fixed using the latest version of Nightly 1/10 #20100616.

Devices:
- OnePlus 5T (Android 9);
- Xiaomi Mi 8 Lite (Android 9);
- LG G7 fit (Android 8.1).

**Closed by sv-sdeiac** 2020-01-10 14:44 UTC
Labels: Feature:SitePermissions, P2, S2, b:crash, eng:qa:needed, eng:ready, help wanted, 🐞 bug

**Comment by liuche** [comment] 2020-01-24 22:28
We're seeing this in 3.1, but this should be fixed in 3.2.
https://sentry.prod.mozaws.net/operations/fenix/issues/7137984/
