### ISSUE TITLE
copy image on image menu

### ISSUE THREAD

**Issue by djdisodo** [mozilla-mobile/fenix#17780] opened 2021-02-03 01:50 UTC
![Screenshot_20210203-104953_Firefox_Beta](https://user-images.githubusercontent.com/17721656/106686417-95470680-660d-11eb-80bb-079b1edadd44.png)
there's no copy image button here

it is there on firefox pc and other browser but not on fenix

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9586)

**Comment by LaurentiuApahideanSV** [comment] 2021-02-04 14:24
I was able to reproduce your issue on Firefox 85.1.0 but not on Firefox Nightly 210204. @djdisodo Could you please download the latest Firefox Preview Nightly and see if the issue occurs there?
### Devices used:
- Google Pixel 3 XL (Android 9)
- OnePlus 6T (Android 9)

**Comment by djdisodo** [comment] 2021-02-05 21:34
i tried it on nightly
![Uploading Screenshot_20210206-063209_Firefox_Nightly.png…]()

**Comment by djdisodo** [comment] 2021-02-05 21:34
![Screenshot_20210206-063209_Firefox_Nightly](https://user-images.githubusercontent.com/17721656/107091593-63b88000-6845-11eb-9261-432edafb3c26.png)

**Comment by ekager** [comment] 2021-02-05 22:15
Closing for https://github.com/mozilla-mobile/fenix/issues/12414

You should be able to share image directly in Nightly

**Comment by djdisodo** [comment] 2021-02-06 01:09
@ekager 
it could be a problem of android
but you can't copy image to clipboard with #17491

**Comment by ekager** [comment] 2021-02-06 01:10
Okay I'll reopen for that specific function

**Comment by GottemHams** [comment] 2022-07-28 18:07
[Google's own docs](https://developer.android.com/guide/topics/text/copy-paste) say:
> When you use the clipboard framework, you put data into a clip object, and then put the clip object on the system-wide clipboard. The clip object can take one of three forms:
> * Text
>    A text string. You put the string directly into the clip object, which you then put onto the clipboard. To paste the string, you get the clip object from the clipboard and copy the string to into your application's storage.
> * URI
>    A [Uri](https://developer.android.com/reference/android/net/Uri) object representing any form of URI. This is primarily for copying complex data from a content provider. To copy data, you put a [Uri](https://developer.android.com/reference/android/net/Uri) object into a clip object and put the clip object onto the clipboard. To paste the data, you get the clip object, get the [Uri](https://developer.android.com/reference/android/net/Uri) object, resolve it to a data source such as a content provider, and copy the data from the source into your application's storage.
> * Intent
>    An [Intent](https://developer.android.com/reference/android/content/Intent). This supports copying application shortcuts. To copy data, you create an Intent, put it into a clip object, and put the clip object onto the clipboard. To paste the data, you get the clip object and then copy the Intent object into your application's memory area.

So Android's **standard** features do not include copypasting images. If it happens to work on a device then the manufacturer either modified Android's clipboard enough to support it, or they have a custom "intermediary" app (such as a keyboard application). I seem to remember that my old LG G4's clipboard did in fact support images (through an application called `Clip Tray`), while my Nokia 6.1 does not.

You may have noticed the `URI` type you can put on the clipboard. You can encode image data into base64 and use a `data` URI to display it in certain cases: `data:image/png;base64,<image data>`. This still doesn't work with Android's clipboard though, since it's not data from "a data source such as a content provider". Even putting the URI's contents through a "content resolver" doesn't do anything: I get the option to paste but neither text nor image is pasted. This exact method supposedly works fine on e.g. Samsung Note devices. It might be possible to work around it by first storing the (decoded) image data in an actual file first, then read **that** through a URI instead. `Clip Tray` might've been doing exactly that, but I think actually pasting the image didn't work for all apps.

Perhaps the nightly version 210204 mentioned by @LaurentiuApahideanSV contains a change that somehow detects your phone's ability to copypaste images "natively". If you happen to have a phone that doesn't support it (like mine) you still won't see the option.

**Comment by meanssaddles** [comment] 2022-08-04 14:30
i still can't copy image on nightly 105.0a1, why firefox is lacking even this basic feature when chrome could do it for years?

**Comment by freMea** [comment] 2022-08-26 15:05
Using last 103.2.0 on Android 9 and this lack of feature brings me back to Vivaldi.

I need to copy images in clipboard everyday. I didn't find any site the menu offers the option.

**Comment by netronicus** [comment] 2022-09-15 23:15
I'm just back to firefox since 10+ years and I'm loving it, but this is really annoying, I'm use to copy images directly from google search and now firefox is forcing me to download the images 🙄

**Comment by feadraug** [comment] 2022-10-16 15:14
107.0a1 still haven't

**Comment by CubeOfCheese** [comment] 2022-10-26 17:10
The default samsung browser has this capability on samsung galaxy s22. This lack of a feature will probably force me to use other browsers sometimes unfortunately

**Comment by csadilek** [comment] 2023-01-09 20:41
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809305

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2023-01-09 20:41 UTC
Labels: feature request 🌟, Feature:ContextMenu
