### ISSUE TITLE
[Bug] Nightly (yet again) does not respect screen bounds in fullscreen mode

### ISSUE THREAD

**Issue by mackeev** [mozilla-mobile/fenix#16293] opened 2020-10-31 02:48 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to http://livetv.ru/allupcoming and tap a link with streaming video. 
2. Tap Fullscreen icon

### Expected behavior
Picture in fullscreen mode

### Actual behavior
Only part of the picture is within bounds. But you can move it around with your finger

### Device information

* Android device: Redmi note 5 pro
* Fenix version: latest Nightly

**Comment by kbrosnan** [comment] 2020-11-03 18:38
Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/8252

**Closed by kbrosnan** 2020-11-03 18:38 UTC
Labels: Feature:Media, needs:triage, 🐞 bug
