### ISSUE TITLE
Engagement notification for inactive users

### ISSUE THREAD

**Issue by onemahon** [mozilla-mobile/fenix#27949] opened 2022-11-22 16:11 UTC
## User Story
We'd like to use a local notification to encourage new users to re-engage with the app after an absence of usage as a way to try to convert them into regularly active users.

### Acceptance Criteria

* only show this notification for new users
* schedule notification for 48 hours after first use
* don't show the notification if the user winds up doing any other activity in the app after first use
* don't show the notification if Firefox is set as the default browser

### Telemetry

* notification triggered
* notification clicked on
* whether or not the app was granted permissions to send notifications

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22033)

**Comment by rocketsroger** [comment] 2022-11-25 04:19
Clarification of these requirements:
>     1. When, precisely, should the notification occur? Do we have a strict preference? E.g., should it be 48 hours after the user's first activity? Or should it be "some time on the day 2 days after first use"?
This notification should occur 48 hours after Firefox for Android first started.

>     2. Do we have a clear understanding of when "first use" _ends_? E.g., does activity 10 minutes after first use count? 1 hr? Anytime within the first day of use?
First use here means user have no interaction after 24 hours counting from the time Firefox for Android first started.

>     3. Is there any way to cancel the notification in the edge case where a user sets Firefox to their default browser _without_ re-opening the app? (I'd guess not, and that's probably fine from a product perspective, but worth double-checking)
Default browser check will be done right before showing the notification.  If Firefox is their default browser at that moment, we do not show the notification.

**Comment by jonalmeida** [comment] 2022-11-25 17:18
Consider also that first use might happen at 1am and it might not be a great experience to send a notification at the same time on a different day.

We should also do some testing to ensure this doesn't consider install time as first use. Auto-updates happen at night again, so 48 hours after that would be distributive to send a notification.

It's not in the acceptance criteria, but shouldn't we have a Nimbus feature flag to disable this if we find a bug once this has already been released in order to limit affected users?

**Comment by rocketsroger** [comment] 2022-11-25 17:34
> Consider also that first use might happen at 1am and it might not be a great experience to send a notification at the same time on a different day.
> 
> We should also do some testing to ensure this doesn't consider install time as first use. Auto-updates happen at night again, so 48 hours after that would be distributive to send a notification.
This notification will only show up for the new user.  No current user should get this notification.

> It's not in the acceptance criteria, but shouldn't we have a Nimbus feature flag to disable this if we find a bug once this has already been released in order to limit affected users?
We do have another [issue](https://mozilla-hub.atlassian.net/browse/FNXV2-21948) that tracks the Nimbus flag.  However, I'll be implementing that at the same time as this issue.

**Comment by AdinaPetridean** [comment] 2022-12-07 10:42
Tested on the latest Nightly 109.0a1 (2022-12-07) with Motorola Moto G9 plus (Android 11). 
After 48 hours of inactivity, the notification is triggered only when the app is brought to the foreground (when it is active).

 @rocketsroger can you confirm this is the expected behaviour?

<img src="https://user-images.githubusercontent.com/108326843/206157718-d8f07dd6-8693-4b30-9d3d-605a4d8d838e.JPEG" width="50%" />

**Comment by onemahon** [comment] 2022-12-19 06:37
Thanks @delia-pop and @AdinaPetridean!

I'm *guessing* the reason the notification doesn't arrive is because the app is still running in the background - even though the clock is set forward by two days. I think this edge case is likely acceptable (very few phones, if any, will maintain the app actively running in the background for 48 hours).

I'll create a follow-up ticket for this case, but I'd vote we defer that fix until the next version. @channingcarter are you OK with that plan? (Note: if so, we should be vigilant looking at telemetry for unexpected data or behavior, just in case I'm wrong about the scale of impact. Not sure if this is possible, but in an ideal world, it would be helpful to have a chart of notification pings according to the  amount of time between the `re_engagement_notif_shown` `timestamp` and, if it exists, a timestamp of the first time the user opens the app. We'd want to see them all showing up around the same time - 48 hours. We'd also want to display experiment-targeted users who never actually receive a `re_engagement_notif_shown` ping at all).

@delia-pop as for this note:

> On multiple occasions, when all products are installed on the device, the "Set to default browser" notifications for Nightly, Beta and RC would also not be automatically received (the user has to open the app in order to trigger them).

It sounds like you're describing a _new_ issue for the "set to default" notification, separate from the "try private browsing" notification - that's a little worrying, if so (just because I'm not sure why that would be affected). When you say "on multiple occasions" - was that rare, or frequent in your testing?

**Comment by channingcarter** [comment] 2022-12-19 11:40
I'm fine with that plan to defer the fix until 110 @onemahon .

**Comment by delia-pop** [comment] 2022-12-20 15:44
Thank you, @onemahon for your input and for reporting the edge case. 
Regarding the "Set as default browser" notification, I re-tested the notifications on the latest Nightly 110 , as well on Beta 109.0b2 and Release 108.1.0 again, and couldn't reproduce the inconsistencies initially reported. I only noticed that, similar to the engagement notification, the "Set to default browser" one is only received after opening the application foreground. 

I will close this ticket as Verified Fixed, but we will further test the notifications to make sure they work correctly.

**Closed by delia-pop** 2022-12-20 15:44 UTC
Labels: eng:qa:needed

**Comment by rocketsroger** [comment] 2022-12-27 19:03
@delia-pop to answer your question.  From my testing, when modifying system time, the app (Fenix in this case) has to be forced closed for it to work.  If the app is not forced closed, I have to wait the full delay time even with system time modified.  I don't think this is a bug but a difference in how Android OS determines when the delay time expires when the app is running vs app is closed. 

With the way we're currently using system time to test the notification, Fenix will have to be forced closed for that to work.  However, I did test (with a shorter delay) that without force closing the app, the notification will still show up.

**Comment by rocketsroger** [comment] 2022-12-27 19:07
@AdinaPetridean, It's not expected that we have to open the app for the notification to show.  Workmanager takes different considerations when determining what's the best time to perform the task (In this case showing the notification).  It's not very precise.  In this case when you opened Fenix, it determined that it's the best time to perform the task since the app is running.

I would suggest waiting 1 to 2 hours past 48 hours to make sure the notification shows up without user interaction with Fenix.  Thanks
