### ISSUE TITLE
FNX-5170 ⁃ [Fenix] Tab number is not centered to the icon

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#1669] opened 2019-04-16 19:54 UTC
This is a follow-up bug to https://github.com/mozilla-mobile/fenix/issues/904

The number inside the tab in Fenix is not centered to the icon (please see attached screenshot)

![](https://user-images.githubusercontent.com/5992746/56239768-dac4c900-605f-11e9-9491-735e475a8b95.png)

**Comment by kbrosnan** [comment] 2019-04-16 20:28
Dupe of #1541

**Closed** 2020-08-11 12:25 UTC
Labels: 🐞 bug
