### ISSUE TITLE
[Bug]Autofill with Bitwarden temporarily shows password

### ISSUE THREAD

**Issue by Shuhel100** [mozilla-mobile/fenix#18044] opened 2021-02-18 05:24 UTC
When autofill is used with Bitwarden it temporarily shows the actual password.

**Comment by hakkikaancaliskan** [comment] 2021-02-22 10:14
Which firefox version do you use?
Is is bitwarden app or extension?
What is your device and Android version?

There is no problem with bitwarden app, firefox nightly, Xperia XZ1 Android 11.

**Comment by LaurentiuApahideanSV** [comment] 2021-03-31 10:28
I tried to reproduce the issue on Firefox Preview RC 87.0.0 and Nightly 210331 but was unable to. Since the reported has not provided any more details on how to reproduce the issue I will close it.
### Device used:
- OnePlus 6T (Android 9)

**Closed by LaurentiuApahideanSV** 2021-03-31 10:28 UTC
Labels: needs:triage, 🐞 bug
