### ISSUE TITLE
[Bug] The large picture is blurred  in Nightly build

### ISSUE THREAD

**Issue by haiwx** [mozilla-mobile/fenix#9537] opened 2020-03-31 06:13 UTC
IMG URL（_Copy the link manually_） :  https://wx3.sinaimg.cn/large/e925a4f9ly1gdb2s6r1upj20prcmvnpe.jpg

### Zoom in

Release V 3.2.0：Okay 

![BaiduShurufa_2020-3-31_14-0-3](https://user-images.githubusercontent.com/13563349/77992175-1f706f80-7358-11ea-99fd-790309f4c23f.png)

Nightly（200320）：blurred

![BaiduShurufa_2020-3-31_14-0-17](https://user-images.githubusercontent.com/13563349/77992178-21d2c980-7358-11ea-8801-2a0422362150.png)

**Comment by LaurentiuApahideanSV** [comment] 2020-03-31 09:11
I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 3/31 (Build #20910607).
The issue does not occur on Firefox Preview Release 4.2.0 (Build #20852112) 3/25 and Beta 4.2.0-beta.3 (Build #20851902) 3/25.
Device: OnePlus 6T (Android 9);

**Comment by s-ankur** [comment] 2020-11-28 20:49
Duplicate of https://github.com/mozilla-mobile/fenix/issues/10232

**Comment by kbrosnan** [comment] 2020-12-02 20:44
Closing as a duplicate of bz-1680347

**Closed by kbrosnan** 2020-12-02 20:44 UTC
Labels: Feature:Browsing, S2
