### ISSUE TITLE
[Bug] The "Tab closed UNDO" snackbar is not dismissed

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7825] opened 2020-01-21 09:12 UTC
## Steps to reproduce
1. Open a few tabs.
2. Swipe one of them in order to delete it.
3. Observe the "Tab closed UNDO" snackbar.

### Expected behavior
The snackbar disappears after a few seconds.

### Actual behavior
The snackbar is displayed until the user taps on UNDO,

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: 1/20 Nightly build (#20201806)

![20200121_095136_Trim](https://user-images.githubusercontent.com/40694158/72790614-9bef1f80-3c3e-11ea-9ded-ba0a6d14338d.gif)

**Comment by cadeyrn** [comment] 2020-01-21 09:50
Duplicate of #7799.

**Closed** 2020-01-21 10:11 UTC
Labels: Feature:Snackbar, S2, needs:triage, 🐞 bug
