### ISSUE TITLE
[Bug] Ublock origin

### ISSUE THREAD

**Issue by Bhooty** [mozilla-mobile/fenix#12241] opened 2020-07-03 11:25 UTC
When I open ublock origin to enter custom lists 
The custom list box is not shown properly 
It always cuts the bottom line 
![Screenshot](https://user-images.githubusercontent.com/46019727/86464826-2c836d00-bd52-11ea-9dc7-88b8ab02e7a7.jpg)UNITO-UNDERSCORE!20200703-172157!UNITO-UNDERSCORE!Firefox Beta!

* Android device: Samsung note 8
* Fenix version: 79.0.0 beta 5

**Comment by hwinnemoe** [comment] 2020-07-03 11:31
Duplicate of #11858

**Comment by Amejia481** [comment] 2020-07-03 12:55
Thanks @hwinnemoe.
We can close this one.

**Closed** 2020-08-28 21:41 UTC
Labels: needs:triage, 🐞 bug
