### ISSUE TITLE
[Bug] When the document style position is set to fixed, the toolbar menu reserves space for it but does not display the menu.

### ISSUE THREAD

**Issue by jomisica** [mozilla-mobile/fenix#16368] opened 2020-11-04 15:31 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
The following simplified page shows the problem:
https://www.sleeping.pt/wp/testfixedbodybug.html

The following video shows the problem:
https://www.sleeping.pt/wp/wp-content/uploads/2020/10/2020_11_04_14_49_12.webm

1. Scroll down until the toolbar disappears.

2. Click anywhere in the document, to trigger the click event that makes the document fixed.

3. And we can see the space reserved for the toolbar menu but the toolbar is hidden.

When the toolbar reserves the space it does not change the window.innerHeight value either.

### Expected behavior
In this case, it is expected that the menu does not reserve space when it is hidden, and the document is set as fixed. Or reserve space but show up and change the window.innerHeight value.

### Actual behavior
Reserve the space but don't show up and don't change the window.innerHeight value.

### Device information

* Android device: A20e
* Fenix version: 82.1.1

**Comment by jomisica** [comment] 2020-11-04 18:51
This problem happens even with the toolbar menu at the top. But reserve the space at the bottom.

**Comment by jomisica** [comment] 2020-11-04 19:00
The same in beta version 83.0.0-beta.2.

**Comment by tachtler** [comment] 2020-11-05 07:22
Hi jomisica,

I have a similar issue #16386 and can confirm your problem!

Klaus.

**Comment by LaurentiuApahideanSV** [comment] 2020-11-05 10:58
I can confirm the issue is reproducible Firefox Preview Nighlty 201105 (Build #2015773803) using a Samsung Galaxy S9 (Android 8.0.0).

**Comment by Mugurell** [comment] 2021-02-02 15:46
This is reproducible on GVE also.
Moving to Bugzilla.

**Comment by Mugurell** [comment] 2021-02-02 15:47
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1690296

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by Mugurell** 2021-02-02 15:47 UTC
Labels: Feature:Toolbar, S2, 🐞 bug

**Comment by Mugurell** [comment] 2021-08-18 14:18
This should be resolved after https://github.com/mozilla-mobile/android-components/pull/10805. Please help verify.

**Comment by SoftVision-LorandJanos** [comment] 2021-09-15 10:43
Verified as fixed in the latest Nightly (94.0a1 20210915T05:08:45.157708).

Devices used:
- Xiaomi Mi11 Lite (Android 11)
- Huawei P30 (Android 10).
