### ISSUE TITLE
swipe up from bottom toolbar or swipe down from top toolbar to open tab menu

### ISSUE THREAD

**Issue by michael9602** [mozilla-mobile/fenix#16708] opened 2020-11-22 03:36 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Please add an option to open tab menu by swiping up from bottom toolbar juat like Chrome.It will make the navigation across the app much more convenient.By adding this feature,Firefox will come a step close to Chrome in terms of features.

### Who will benefit from it?
Everyone who use Firefox a lot will benefit from this feature.

**Comment by hakkikaancaliskan** [comment] 2020-11-22 15:21
Duplicate of #11862, there is a open pr for this.

**Comment by kbrosnan** [comment] 2020-12-02 23:50
Closing as a duplicate

**Closed by kbrosnan** 2020-12-02 23:50 UTC
Labels: needs:triage
