### ISSUE TITLE
Make Firefox Nightly on Android Share menu automatically sort based on previous use

### ISSUE THREAD

**Issue by jdrch** [mozilla-mobile/fenix#8030] opened 2020-01-31 23:20 UTC
### Why/User Benefit/User Problem

In the previous version, frequently shared to apps would appear at the top of the share list, and would be preloaded before the entire list was displayed. This was very efficient and saved a lot of time.

### What/Requirements

Make Firefox Nightly on Android Share menu automatically sort based on previous use

### Acceptance Criteria (how do I know when I’m done?)

When the app the user has shared to multiple times appears as the top entry on the Share menu

**Comment by cadeyrn** [comment] 2020-02-01 09:18
Duplicate of #4231.

**Closed** 2020-02-04 00:13 UTC
Labels: needs:triage, 🌟 feature request
