### ISSUE TITLE
[Bug] Tab closed button persists

### ISSUE THREAD

**Issue by jumpnjackflash** [mozilla-mobile/fenix#7942] opened 2020-01-26 18:33 UTC
## Steps to reproduce
Close a tab

### Expected behavior
Tab closed UNDO button should stay for a short time. 

### Actual behavior
Tab closed UNDO button persists indefinitely until UNDO is tapped. 

### Device information

* Android device: Android 9
* Fenix version: Nightly 200126 06:00 (Build #20260606)
29.0.0, c3ba2ed42
GV: 74.0a1-20200123095433

![Screenshot_20200126-123054](https://user-images.githubusercontent.com/58296252/73139845-e950ff80-4037-11ea-98f0-efbf3f36a387.png)

**Comment by cadeyrn** [comment] 2020-01-26 18:37
Duplicate of #7799.

**Comment by sv-ohorvath** [comment] 2020-01-27 13:33
closing as duplicate.

**Closed by sv-ohorvath** 2020-01-27 13:33 UTC
Labels: needs:triage, 🐞 bug
