### ISSUE TITLE
Ability to Tag Top Sites

### ISSUE THREAD

**Issue by mackeev** [mozilla-mobile/fenix#14844] opened 2020-09-08 08:05 UTC
### What is the user problem or growth opportunity you want to see solved?
Some of my top sides are in the same domain (different threads). They have same icons and (since recent Nightlies) nothing else to distinguish them on the list.
### How do you know that this problem exists today? Why is this important?
Please give the option (on long-press) to name icons on the list.
### Who will benefit from it?
Every user.

**Comment by mcarare** [comment] 2020-09-08 09:58
@mackeev Thank you for your report!
Although you mention tag, not name, your issue seems to be a duplicate of https://github.com/mozilla-mobile/fenix/issues/9548.
If you feel that feature would not be enough to serve your purposes, feel free to reopen this and provide more details.

**Closed by mcarare** 2020-09-08 09:58 UTC
Labels: needs:triage
