### ISSUE TITLE
[Bug]Fenix Homescreen icon long-press feature not working properly

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5296] opened 2019-09-13 09:38 UTC
## Steps to reproduce
1. From the device home screen long tap on Firefox Preview icon
2. Tap on the "Open new tab" from the pop-up overlay
3. Tap on the "Open new private tab" from the pop-up overlay

### Expected behavior
By tapping on "Open new tab" a new tab or search session should be launched in normal browsing
By taping on "Open new private tab" a new private tab or private search session should be launched 

### Actual behavior
Nothing happens

### Device information

* Android device: Samsung Galaxy Tab A (Android 9)
* Fenix version:  Fenix 2.0.0-rc.2 

### Notes
![image](https://user-images.githubusercontent.com/51314259/64853113-6482bd80-d623-11e9-81bc-d66f1b894a28.png)

**Comment by TitanNano** [comment] 2019-09-13 10:14
Since this has been filed I wanted to add that on my device with android 7.1.1 both options crash the launcher and Fenix doesn't open. Other apps obviously don't do that. I'm not sure if it's really related, but might be.

**Comment by sblatz** [comment] 2019-09-13 16:39
@jyeontaek may want to look at this :)

**Comment by abodea** [comment] 2019-09-17 13:32
Verified as fixed on the **Fenix v2.0.0-rc3** using `OnePlus 6T(Android 9), Samsung Galaxy S10+(Android 9), Google Pixel 3a (Android 9), Samsung Galaxy S8+(Android 8), Samsung Galaxy Tab A (Android 9)`

Please note that I also tried to reproduce the crash mentioned [above](https://github.com/mozilla-mobile/fenix/issues/5296#issuecomment-531182612) but the feature is not available on the devices running android 7.

**Closed by abodea** 2019-09-17 13:32 UTC
Labels: Feature:Shortcuts, S2, 🐞 bug
