### ISSUE TITLE
[Bug] "desktop view" combo stuck

### ISSUE THREAD

**Issue by ceisserer** [mozilla-mobile/fenix#14737] opened 2020-09-04 17:13 UTC
## Steps to reproduce
While browsing a webpage, I tried to switch to "desktop view" / "desktop mode" - however the combo box was already stuck at "enabled" and tapping on it didn't change its value - it always stayed "on" (and the site was reloaded - however still shown in mobile view).

Please have a look at the screencast on youtube: https://youtu.be/KkcI6JZfMP0

I've experienced this bug a couple of times (5-10x), however I wasn't able to reproduce it reliable.

Here is what I observed:
- The issue is per tab. Once a tab is in this broken state, it will stay this way forever. Even loading a different webpage / url in the same tab doesn't fix it. The new page will also load in mobile view, with no way to switch to desktop view (although the combo sticks at "desktop view" = enabled).

- Other tabs are unaffected. Even when one tab is stuck, other tabs usually continue to function as expected - even for the URL of the broken one.

### Device information

* Android device: Android 9.0, Sony Xperia XZ1 Compact (Snapdragon 835), Webrender enabled
* Fenix version: 82.a1 (but seen with earlier versions of the "new" Firefox for Android, however I never experienced this with the "old" version)

**Comment by jabdoa2** [comment] 2020-09-06 10:40
Same for me. This also happens to me in the opposite direction where the toggle is stuck in desktop mode.

**Comment by kbrosnan** [comment] 2020-09-24 04:46
Closing as a dupe of #15352 as that one has steps to reproduce.

**Closed by kbrosnan** 2020-09-24 04:46 UTC
Labels: Feature:RequestDesktopSite, 🐞 bug
