### ISSUE TITLE
the snackbar after closing a tab won't disappear  [Bug]

### ISSUE THREAD

**Issue by jawadalkassim** [mozilla-mobile/fenix#7883] opened 2020-01-23 12:11 UTC
## Steps to reproduce
Close a tab
### Expected behavior
Snackbar appears a few seconds with undo button then disappear
### Actual behavior
Snackbar appears and don't hide at all , and after a while  if you press the UNDO button the snackbar will disappear but tab don't return.
### Device information

* Android device: 8.0
* Fenix version: Nightly 200123 06:00 (Build #20230608)
29.0.0, cc808a804
GV: 74.0a1-20200122094859

**Comment by cadeyrn** [comment] 2020-01-23 12:11
Duplicate of #7799.

**Closed** 2020-01-23 12:18 UTC
Labels: needs:triage, 🐞 bug
