### ISSUE TITLE
[Bug] Fenix doesn't sign into Gmail in the Outlook app

### ISSUE THREAD

**Issue by aha999** [mozilla-mobile/fenix#8076] opened 2020-02-04 14:23 UTC
## Steps to reproduce
- Have Firefox Preview as a default browser app
- Open Microsoft Outlook app
- If it asks you that you need to sign in again with your account, click the confirmation
- Try to sign in (Fenix will open as a browser that signs you in to gmail)
- When signing in, it will get an error that will prevent you from signing in.

### Expected behavior
- When signing in to gmail on the android app Microsoft outlook, it should sign in normally, when i've set a regular Mozilla Firefox as default, then it worked.
### Actual behavior
- it fails to sign into gmail on the Outlook app
### Device information

* Android device: Lenovo P2, LineageOS 16 (android 9), API 28
* Fenix version: 3.2.0 (Google play - latest Firefox Preview)

**Comment by liuche** [comment] 2020-02-11 18:25
Hi @aha999, have you tried disabling tracking protection during this sign-in? Is it a duplicate of #6528?

**Comment by aha999** [comment] 2020-02-11 20:16
@liuche it's not the same bug. In the #6528 bug he can't click the button, but i CAN click the button. The problem in my situation is that it starts signing in but it does not complete and gives the error.

**Comment by kbrosnan** [comment] 2020-02-14 21:54
Sounds like a dupe of #7331

**Comment by aha999** [comment] 2020-02-14 21:58
@kbrosnan not sure... In outlook app it asks to sign in and Fenix opens and loads a sign in page successfully, but when i press confirm it starts loading and then fails.

**Comment by kbrosnan** [comment] 2020-02-14 23:23
Does it fail with an unknown protocol error?

**Comment by aha999** [comment] 2020-02-14 23:50
Can't check because it hasn't asked me for re-entering the password since then (when i successfully logged in with regular firefox browser in-app window).
I tried through settings, but it doesn't open the firefox window, but integrated outlook login tool.
It looks i can't replicate this with my accounts anymore until i get a same prompt.

**Comment by kbrosnan** [comment] 2020-11-09 18:24
Closing as works for me. We resolved most of the browser based auth issues from apps. If this is still happening a we can reopen.

**Closed by kbrosnan** 2020-11-09 18:24 UTC
Labels: Feature:OpenInApp, needs:triage, 🐞 bug
