### ISSUE TITLE
make it easier to use noscript (less taps)

### ISSUE THREAD

**Issue by thecodingdude** [mozilla-mobile/fenix#12039] opened 2020-06-26 23:09 UTC
### What is the user problem or growth opportunity you want to see solved?
When using an add-on like noscript you can often spend a while trying to selectively enable or disable which domains to allow scripts.

Now, in 5.2, it requires 2 taps; add-ons -> noscript before you can access the options to enable/disable scripts 

Please consider making it easier to use this addon.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2721)

**Comment by cadeyrn** [comment] 2020-06-27 07:29
What is your concrete proposal to make it easier? If your proposal is to be able to pin add-on to the first level of the menu then your issue is a duplicate of #11809.

**Comment by boek** [comment] 2023-01-31 00:38
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813940

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-31 00:38 UTC
Labels: feature request 🌟, Feature:WebExtensions
