### ISSUE TITLE
[Bug] "Open In Firefox Preview" from Custom Tab doesn't open page

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#5025] opened 2019-08-30 00:39 UTC
## Steps to reproduce
- Open link in Custom Tab (e.g. from Twitter App)
- Tap "Open in Firefox Preview"

### Expected behavior
- Page opens in Fenix

### Actual behavior
- Page flashes and then previous page opened appears

### Device information

* Android device: Samsung S10
* Fenix version: Latest nightly from Play Store

**Comment by pwd-github** [comment] 2019-08-31 18:30
Just came to report this. This is incredibly annoying, but I have observed that the tab opens and then immediately closes when Fenix is left on the tab overview. Otherwise it just shows a previous tab.

**Comment by AndiAJ** [comment] 2019-09-02 10:10
Hi, reproducible on:
• 2.0.0-rc.1
• Nightly Build #12441810

Using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Tab A (Android 9)

►Video
![20190902_1302431](https://user-images.githubusercontent.com/51314259/64107359-003e3f00-cd83-11e9-90df-de676a223a59.gif)

**Comment by AndiAJ** [comment] 2019-09-09 10:02
Hi @ekager , I've checked and the webpage is opened in Fenix.
On the other hand, **the link from the custom tab doesn't populate the URL bar from Fenix**. 

I've used the latest Nightly Build #12520610 from 9/9 with the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Andriod 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)

►Video
![20190909_124326](https://user-images.githubusercontent.com/51314259/64522049-d399a280-d301-11e9-926c-a53c1e54a2eb.gif)

**Comment by pocmo** [comment] 2019-09-09 14:39
Thank you, @AndiAJ, this looks like an important bug - although I think unrelated to this bug fixed here. I can reproduce this in Reference Browser and assume that this is related to our `feature-toolbar` refactoring that has happened just recently. I filed the following AC issue to track that:
https://github.com/mozilla-mobile/android-components/issues/4348

**Comment by ekager** [comment] 2019-09-09 16:39
Closing this bug because unrelated to #5169

**Closed by ekager** 2019-09-09 16:39 UTC
Labels: E2, Feature:CustomTabs, P2, S2, 🐞 bug

**Comment by sv-ohorvath** [comment] 2019-09-11 12:55
Verified as fixed on RC 1.4.1
Devices:
Samsung Galaxy J7(Android 6)
Pixel (Android Q)
Samsung Galaxy Tab A (Android 9)
