### ISSUE TITLE
java.lang.IllegalThreadStateException at mozilla.components.feature.downloads.DownloadMiddleware$restoreDownloads$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:4)

### ISSUE THREAD

**Issue by SinTan1729** [mozilla-mobile/fenix#14486] opened 2020-08-30 12:59 UTC
## Steps to reproduce
Just launch firefox.

### Expected behavior
Should work smoothly.

### Actual behavior
Crashes everytime.

### Device information

* Android device: Redmi K20 (Android 10)
* Fenix version: 200830 06:01

**Comment by hwinnemoe** [comment] 2020-08-30 13:02
Can you still access the Settings? Then sharing the crash report via _Settings_, _About Firefox Nightly_, _Crashes_ and pressing _Share_ would be helpful here.

**Comment by SinTan1729** [comment] 2020-08-30 13:10
No. I can't even open the app. [Here's](https://streamable.com/bdyr6w) a screen record for context.

**Comment by hwinnemoe** [comment] 2020-08-30 13:13
Do you have Fenix as your default browser? Try setting another browser as your default browser.

**Comment by SinTan1729** [comment] 2020-08-30 13:19
No defaults have been set.

**Comment by hwinnemoe** [comment] 2020-08-30 13:21
Ok, thanks :) Please use https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information to create a log for your crash, and attach it here. Also make sure to use `adb logcat -c` before reproducing the crash to clear anything else in the log. This will help the developers to find the cause for your crash.

**Comment by SinTan1729** [comment] 2020-08-30 13:29
[Here's the logcat.](https://gist.github.com/SinTan1729/84bf00ee35f97a5d420affc18d4673ed)

**Comment by hwinnemoe** [comment] 2020-08-30 13:30
https://crash-stats.mozilla.org/report/index/bp-aa3efb20-b3d5-4684-99ea-5b6a50200830

**Comment by hwinnemoe** [comment] 2020-08-30 13:35
Thanks! Since when do you have this issue, did it also occur on e.g. yesterday's Nightly?

**Comment by kawaiiDango** [comment] 2020-08-30 13:54
I'm having the same issue since today. It's impossible to open Firefox nightly anymore. My log also looks the same

![Screenshot_20200830-192028](https://user-images.githubusercontent.com/1066519/91660923-77bdc000-eaf6-11ea-9ed5-c3bcd57ac488.jpg)

**Comment by SinTan1729** [comment] 2020-08-30 13:55
> Thanks! Since when do you have this issue, did it also occur on e.g. yesterday's Nightly?

No. It started having after today's update.

**Comment by hwinnemoe** [comment] 2020-08-30 14:06
cc @Amejia481 https://github.com/mozilla-mobile/fenix/commit/c63fd3f9ac2fd511cc4b7f791353d6ff4d412fcf and https://github.com/mozilla-mobile/android-components/pull/8197/files#diff-78ef6898bdea79d57a0d51a5c39104e4R98 this might be the culprit for this

**Comment by Amejia481** [comment] 2020-08-30 15:15
Thanks for the report I'm taking a look. The issue should be only reproducible in nightly as the functionality is behind a feature flag.  https://github.com/mozilla-mobile/fenix/blob/aae8236478d41df2adb0c23e662e2c35dedd90f5/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L167

**Comment by B0pol** [comment] 2020-08-30 19:28
Does it also crashes in the background? I mean when you are not even using the browser?

**Comment by kawaiiDango** [comment] 2020-08-30 19:31
Yes

**Comment by B0pol** [comment] 2020-08-30 19:44
OK then I think I have the same bug. You can stop crashes in the background via settings -> apps -> firefox nightly and force stop, and don't open it until it's fixed

**Comment by crisalis2** [comment] 2020-08-30 22:31
This happens to me too, and I think it's the same as #14505

**Comment by Amejia481** [comment] 2020-08-31 00:13
This issue will be address after pr lands https://github.com/mozilla-mobile/android-components/pull/8291

**Comment by Amejia481** [comment] 2020-08-31 01:39
STR
1. Open Fenix download a file.
2. Kill Fenix (Using the tasks manager).
3. Reopen Fenix.

**Comment by Amejia481** [comment] 2020-08-31 02:37
The  issue should be fixed on master, and it will be fixed in the next update.

**Comment by JamesGreeners** [comment] 2020-08-31 06:56
So there is already an update for it?

**Comment by AndiAJ** [comment] 2020-08-31 09:44
Hi, **verified as fixed** on the latest **`Nightly Build 200831`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200831-123932](https://user-images.githubusercontent.com/51314259/91706856-a46de800-eb87-11ea-9025-15a3fdb994c8.gif)

**Closed by AndiAJ** 2020-08-31 09:44 UTC
Labels: Feature:Download, b:crash, eng:qa:needed, 🐞 bug
