### ISSUE TITLE
FNX-5518 ⁃ [Bug] Last signed aarch64-raptor-release index entry was 9 (!) days ago

### ISSUE THREAD

**Issue by ncalexan** [mozilla-mobile/fenix#2211] opened 2019-05-02 00:00 UTC
See https://tools.taskcluster.net/index/project.mobile.fenix.branch.master.latest.greenfield/aarch64-release-raptor

This job looks all kinds of unhappy:

https://tools.taskcluster.net/groups/df9if_LXQeKAMHSVkdLmcQ/tasks/Pu0NzJyMTNaus1T1qf3R8w/runs/0/logs/public%2Flogs%2Fchain_of_trust.log

@mitchhentges can you run point?

**Comment by mitchhentges** [comment] 2019-05-02 09:13
I'll take a look, thanks for the heads up

**Comment by mitchhentges** [comment] 2019-05-03 11:29
There's three things wrong here:
1. Caused by the `releaseRaptor` => `raptor` refactoring, Raptor artifacts weren't being given to TC properly. This is fixed by #2258 
2. The index has changed to `index.project.mobile.fenix.v2.branch.master.latest.raptor.(arm|aarch64)` (once #2258 is merged, this index should be populated)
3. That build failure you linked is particularly interesting - seems to be an exceptional chain-of-trust case. Let's not close this ticket until that issue is resolved, too

Note: I'm not happy that we didn't catch the build failures until you mentioned them here. I'm :thinking: about the best way to have a feedback loop, and the traditional Moz solution seems to be to sprinkle some sheriffs onto Fenix builds? 

> It's probably time to have sheriffs to monitor fenix and r-b on Treeherder
~releng-mobile

**Comment by JohanLorenzo** [comment] 2019-05-03 12:09
Thanks for the investigation @mitchhentges! I've seen issue number 3. Let's track it in https://github.com/mozilla-releng/scriptworker/issues/334

**Comment by mitchhentges** [comment] 2019-05-06 16:15
Issues 1 and 2 have been fixed, [indexes are showing up again](https://taskcluster-web.netlify.com/tasks/index/project.mobile.fenix.v2.branch.master.latest.raptor).
I'll leave issue 3 separate, as Johan linked.

**Closed** 2020-08-11 14:28 UTC
Labels: 🐞 bug
