### ISSUE TITLE
[Bug] The bookmark Toast message is hidden beneath the browser toolbar

### ISSUE THREAD

**Issue by SS1113** [mozilla-mobile/fenix#9267] opened 2020-03-20 02:07 UTC
## Steps to reproduce
1. Visit a website
2. Try to Bookmark the website or remove the existing bookmark
3. the pop-up/Toast message is hidden beneath the browser toolbar

### Expected behavior
The pop-up/Toast message shouldn't be hidden otherwise it makes it harder to edit the bookmark or see if the website has been successfully bookmarked

### Actual behavior
The pop-up/Toast message is hidden beneath the browser toolbar. 
See the attached screen record.

### Device information
Motorola One Power
Android 10 March Security patch

* Android device: Motorola One Power
* Fenix version: 4.1.0 (Build #20771637)
[Screen Record.zip](https://github.com/mozilla-mobile/fenix/files/4357805/Screen.Record.zip)

**Comment by sv-sdeiac** [comment] 2020-03-20 10:47
Hello @SS1113, thanks for your report.
This issue is fixed on the latest version of Firefox Preview Nightly 3/20 #20800605.

Devices:
- Google Pixel 3 (Android Q);
- LG g7 fit (Android 8.1).

I'll let this issue open and verify on beta/release after the new version will come, thanks.

**Comment by sv-sdeiac** [comment] 2020-04-06 11:21
I can confirm that the issue is not reproducible using the latest version of Firefox Preview RC 4.2.0 and beta 4.2.1.

Device: Samsung Galaxy Note 8 (Android 9).
Due to that, I'll close this issue, thanks.

**Closed by sv-sdeiac** 2020-04-06 11:21 UTC
Labels: needs:triage, 🐞 bug
