### ISSUE TITLE
[Bug]: Stuck in some kind of refresh loop when opening some GitHub notifications

### ISSUE THREAD

**Issue by saethlin** [mozilla-mobile/fenix#27979] opened 2022-11-25 21:15 UTC
### Steps to reproduce

Go to GitHub notifications
Tap on notification about a new review comment (seems more common on these, possibly exclusively?)
Become upset at refresh loop, close tab

### Expected behaviour

The page should reach a steady state

### Actual behaviour

Page keeps reloading

### Device name

OnePlus 9 Pro

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

107.1.0

### Additional information

Screen recording:
https://user-images.githubusercontent.com/12105168/204055869-8e5b587a-f833-4d4c-85e9-eed5790d7a24.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22053)

**Comment by foss-** [comment] 2022-12-12 13:33
LineageOS 19.1 Firefox 107.x
also seeing refresh loop when opening a GitHub notification from webUI, this should be trivial to reproduce and it has happened the past three versions.

**Comment by foss-** [comment] 2022-12-12 23:19
Firefox 107.2.0: reproducible
Firefox 108b6: not reproducible

What a nice coincidence Firefox 108 will be released - today 🤗

**Comment by kbrosnan** [comment] 2022-12-12 23:34
Thanks for the ping. Closing as works for me. If you see something similar in the future open a new bug.

**Closed by kbrosnan** 2022-12-12 23:34 UTC
Labels: 🐞 bug, needs:triage
