### ISSUE TITLE
[Bug] force refresh

### ISSUE THREAD

**Issue by 0xTyagi** [mozilla-mobile/fenix#7979] opened 2020-01-29 14:39 UTC
## Steps to reproduce
Long click on refresh button
### Expected behavior
Page force refresh(as fennec does)
### Actual behavior
Force refreshing is not working
### Device information

* Android device:  api 25
* Fenix version: Nightly 200129 06:01 (Build #20290608)

**Comment by cadeyrn** [comment] 2020-01-29 16:11
Duplicate of #2681 and #6329.

**Closed** 2020-01-29 16:21 UTC
Labels: needs:triage, 🐞 bug
