### ISSUE TITLE
FR: Delete data per site

### ISSUE THREAD

**Issue by 0xTyagi** [mozilla-mobile/fenix#7981] opened 2020-01-29 15:11 UTC
### Why/User Benefit/User Problem
Delete data i.e. history, cache, cookie for a particular site. Currently  to bypass the paywall either entire browsing history is deleted or use the private tabs but private tabs doesn't save to collection or preserve in history for later access. 

It may also fix #7499 
### What/Requirements
Feature parity with Firefox Desktop
### Acceptance Criteria (how do I know when I’m done?)
A data management (delete site data to related site) option in in shield menu

**Comment by kbrosnan** [comment] 2020-09-24 07:54
Closing as a duplicate of #9294 as there has been a lot more action on that issue.

**Closed by kbrosnan** 2020-09-24 07:54 UTC
Labels: feature request 🌟, needs:triage
