### ISSUE TITLE
[Bug] Homescreen toolbar and webpage toolbar alignments doesn't match

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#6410] opened 2019-11-02 16:15 UTC
![1430646776](https://user-images.githubusercontent.com/17825767/68073802-9ea74a80-fd9c-11e9-95d9-c46a94f2aee3.png)

Maybe just for me, please confirm.

### Device information
Nightly 191102 06:01 (Build #13060607)
📦: 20.0.0, 8f0f6dc12
🦎: 72.0a1-20191031095309
XZ1. Android 9

**Comment by cadeyrn** [comment] 2019-11-02 16:31
see also #6260 (as a subset of this one).

**Comment by athomasmoz** [comment] 2019-11-27 17:33
Closing as duplicate of #6835

**Closed by athomasmoz** 2019-11-27 17:33 UTC
Labels: 🐞 bug
