### ISSUE TITLE
[Bug] Firefox Nightly is displayed twice in the Browser app list

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#6735] opened 2019-11-21 09:48 UTC
## Steps to reproduce
1. Go to Settings -> Set as default browser;
2. Tap on Browser app;
3. Observe Firefox Nightly in the Browser app list;

### Expected behavior
Firefox Nightly is displayed once in the list.
### Actual behavior
Firefox Nightly in displayed twice in the list.
### Notes
This is not reproducible on Pixel 2(Android 9), Huawei Honor 8 (Android 7.0).
![69326507-92543600-0c54-11ea-9a7f-be24aeeba790](https://user-images.githubusercontent.com/42831109/69339862-ed932200-0c6e-11ea-9030-3fffaaf559ad.png)

### Device information

* Android device: Nexus 6P (Android 8.1.0)
* Fenix version: Nightly 191121 GV 72

**Comment by boek** [comment] 2019-12-27 23:08
@ebalazs-sv Do you have two versions of Nightly installed? Or is anyone else able to reproduce?

**Comment by ebalazs-sv** [comment] 2020-01-03 08:16
@boek I reproduced this issue only on Nexus 6P (Android 8.1.0) and I had Fenix Nightly and Fennec Nightly installed.
I tested this on Fenix Nightly 200103 GV 73 with Nexus 6P (Android 8.1.0), Motorola Nexus 6 (Android 7.1.1), Nexus 5 (Android 6.0.1) and this is not reproducible.

**Comment by softvision-miralobontiu** [comment] 2020-12-21 09:15
Could not reproduce with Google Pixel (Android 10), nor with Samsung Galaxy Tab s6 (Android 10) on the 12/21 Nightly build.
We will test also with Nexus 6P device.

**Comment by sflorean** [comment] 2020-12-30 10:08
Not reproducible on Nightly 12/30 with Nexus 6P. I will close this issue.

**Closed by sflorean** 2020-12-30 10:08 UTC
Labels: Feature:AndroidIntegration, Feature:Settings, P2, S2, eng:qa:needed, 🐞 bug
