### ISSUE TITLE
Wrong app icon when opening page from other app

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#846] opened 2019-03-05 10:28 UTC
## Steps to reproduce
Open Pinterest or any other app, click on URL and select Fenix to open site. Fenix opens but still shows the Pinterest (or any other app you came from) icon in app switcher view.

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1909

**Comment by sblatz** [comment] 2019-03-05 15:50
I believe this should have been fixed by #829. Please let me know if you're still able to reproduce tomorrow.

**Comment by pocmo** [comment] 2019-03-05 16:10
If this is a custom tab (is it?) then this seems to be expected: The browser is supposed to look as if it's a part of the app (including theme etc.)

**Comment by topotropic** [comment] 2019-03-06 08:14
@sblatz seems to be fixed, thanks!

**Closed** 2019-03-06 10:24 UTC
Labels: QA needed, 🐞 bug

**Comment by sv-ohorvath** [comment] 2019-03-07 15:57
Cannot reproduce this.
