### ISSUE TITLE
FNX3-17160 ⁃ Add home screen shortcut

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#3613] opened 2019-06-23 10:43 UTC
### Why/User Benefit/User Problem
As a user, I want to be able to launch a site in Fenix directly from a homescreen shortcut, so I can get to the sites I want faster.

### Acceptance Criteria
-I can create a homescreen shortcut for any site by tapping on the option in the tab menu ([InVision](https://mozilla.invisionapp.com/share/M4SBYCLJPQG#/381294677_App_Menu))
-I can choose what the shortcut will be called ([InVision](https://mozilla.invisionapp.com/share/M4SBYCLJPQG#/381294676_Add_To_Home_Screen_Dialog))
-I can tap on the homescreen shortcut to launch my frequently visited site.

**Comment by cadeyrn** [comment] 2019-06-23 10:46
Duplicate of #768.

**Comment by nahuhh** [comment] 2019-06-23 10:54
Similar to 768 but #768 seems to be specific to web app compatible websites?
I am just looking to add regular pages to my homescreen.

**Comment by Adrian57** [comment] 2019-06-30 10:58
Agree with nahuhh, this is not a duplicate of #768. Need to have main menu item: "Add to homescreen" for any web page.

**Comment by michel-slm** [comment] 2019-07-01 20:29
Would be great to have this, I add a lot of news sites to my home screen and would love to test them with Firefox Preview.

**Comment by klint** [comment] 2019-07-15 15:42
Also, the shorcut should use the favicon image of the page (unlike Firefox Focus ;) )

**Comment by lime124** [comment] 2019-07-23 03:47
removing the ux label - this is on our radar already as it's part of Q3 plans.

**Comment by NotWoods** [comment] 2019-08-30 18:39
Moved custom shortcut names to #5047

**Comment by AndiAJ** [comment] 2019-09-03 13:40
Hi, I've check this feature on **2.0.0-rc.1** but it seems that it wasn't implemented.
@NotWoods or @vesta0 - Please correct me if I'm wrong. :)

**Comment by AndiAJ** [comment] 2019-09-04 09:41
Hi, **verfied as fixed** on **Fenix Nighlty Build #12470611 from 4/9** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video Normal browsing
![20190904_122920](https://user-images.githubusercontent.com/51314259/64244235-59d47400-cf11-11e9-9ddc-3be693c06009.gif)

►Video Private  browsing
![20190904_123018](https://user-images.githubusercontent.com/51314259/64244098-2265c780-cf11-11e9-8d8a-582c01d6e098.gif)

**Comment by TitanNano** [comment] 2019-09-04 09:50
On older android version (I'm testing with 7.1.1) there is no feedback for adding a shortcut. The user has to manually go to the home screen to see if the shortcut was actually added.

**Comment by AndiAJ** [comment] 2019-09-05 06:30
This happens on higher Android versions as well.
On the other hand, I've check and learned the following:
• Chrome has the similar behavior
• Firefox RC 68.1 automatically makes the switch to the home screen.
I've used a Google Pixel 3a XL (Android 9)

@NotWoods -  Could you please help clarify this matter? :)

**Closed** 2020-08-12 17:25 UTC
Labels: Feature:FennecTransition, could, eng:qa:verified, eng:ready, needs:sumo, ux:s
