### ISSUE TITLE
Alternative way of activating PiP mode

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#20779] opened 2021-08-10 20:17 UTC
### What is the user problem or growth opportunity you want to see solved?

Some users may want to activate picture-in-picture mode as soon as the video starts playing, without having to enter full screen mode first and then going home. 

### How do you know that this problem exists today? Why is this important?

Currently, to enter PiP mode you have to open a video in full screen, then swipe up from the bottom (on gesture navigation) or press the home button. Note that I'm not sure if this is a limitation on Android's part or if it's just the way it's implemented in Firefox.

### Who will benefit from it?

Users often using picture-in-picture mode.

### Possible solutions

There could be an additional, unintrusive pop-up button, like on desktop Firefox. Another solution could be a PiP button in the media notification that shows up in the notification shade when a video is playing. Maybe even both solutions could be implemented.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17536)

**Comment by cadeyrn** [comment] 2021-08-11 08:47
Duplicate of #9889.

**Comment by boek** [comment] 2023-01-30 18:46
Closing as a dup

**Closed** 2023-01-30 18:45 UTC
Labels: feature request 🌟
