### ISSUE TITLE
In-app review prompt

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#13507] opened 2020-08-11 19:26 UTC
## User Story
- As a user, I want to have the option to easily rate the app without it disruptive to my browsing flow. 

## Dependencies
Using the [Google In-app review API](https://developer.android.com/guide/playcore/in-app-review) since it will allow user to rate the app without having the leave the browser. 

### Acceptance Criteria
- I can rate the app without being taken out of the app (to the play store)
- I am not prompted excessively for a review (max 3 times a year)

**Comment by liuche** [comment] 2020-08-18 03:07
I think we decided that this would be something that we want to do through LeanPlum.

Do we need to talk to anyone from marketing for what [specific probes](https://docs.google.com/document/d/1-RWxA9WsMr1FvYW6ap2ZVDMl235vmm2a4xvn0rFZDZI/edit?disco=AAAAKE7G-Q0&ts=5f32f2ff&usp=comment_email_document&usp_dm=false) to add @vesta0 ? (I think comment 0 may need to be updated)

**Comment by liuche** [comment] 2020-08-19 18:33
Moving this back to sourpatch bc the search work is almost done!

**Comment by liuche** [comment] 2020-08-20 17:25
Just to be explicit, this does **not require any strings**, per the Android guidelines. We can only control when the prompt is shown, and we must not show it too often.

```
Your app should not ask the user any questions before or while presenting the rating button or card, including questions about their opinion (such as “Do you like the app?”) or predictive questions (such as “Would you rate this app 5 stars”).
```

**Comment by liuche** [comment] 2020-08-28 20:14
This **should** be triggered on Nightly (but depends on Google Play Services):
- fenix is set to default browser
- restart browser 5 times

We're not entirely clear on when Google Play chooses to show this, but those steps will set it up to be able to be shown (so if it doesn't happen exactly with those steps, please note it in the comments, but we don't actually have full control over this)

If you want to trigger it again, it needs to be a fresh install because one of the restrictions is that GPS will not show the prompt too close together (by a few weeks).
This may not work if you have already rated Firefox Nightly.

Link to Google API can provide more info on how it should look.

**Comment by LaurentiuApahideanSV** [comment] 2020-08-31 14:14
I tested the issue on Firefox Preview Nightly 200831 (Build #2015761139) but was unable to trigger the In-App Review prompt. I tried the following scenario:
1. Log in the Play Store with a google account that has not rated Firefox Preview Nightly;
2. Remove all other google accounts found on the device;
3. Restart Firefox Preview more than 5 times;
4. Browse through web pages;
5. Navigate through the setting menu.

Are there any more steps that need to be completed in order for the In-App Review prompt to be shown?

**Comment by liuche** [comment] 2020-08-31 16:07
Did you set Firefox Nightly as default browser @LaurentiuApahideanSV ? Did not see that in your list of steps, but maybe it was done but not written down. Perhaps browse a site during the 5 restarts?

**Comment by liuche** [comment] 2020-08-31 19:57
@boek if I'm cutting a new 80 Release with the crashfix from #14357 could we get this uplifted too? and there was a follow-up crash with lower API level devices, maybe @eliserichards you know what that is?

**Comment by sv-ohorvath** [comment] 2020-09-01 11:58
@liuche Neither of us could trigger the Gplay review prompt on Nightly 9/1 or 80.1.2 RC (this one because is not yet in the Gplay Store, maybe?) following the criteria mentioned:
- new GPlay account, with no other reviews/apps installed
- first time installation of Nightly
- set as the default browser
- browsing & restarted the app for 5+ times
So we can't confirm the issue on this RC build.

**Comment by liuche** [comment] 2020-09-02 02:36
Hmmm, this is very strange - I was only able to trigger this once on my Nightly build.

The Google Play Services APIs are not clear on how exactly the prompt gets triggered. However, we will keep an eye out for new reviews possibly through here.

This is a low-risk change and maybe it is just unpredictable how the GPS APIs are working. I'll leave this open for now though. Maybe someone who sees this prompt show up can comment.

**Comment by Diana-Rus** [comment] 2020-09-03 14:34
@liuche unfortunately we still didn't managed to trigger the In-app review prompt on Beta 81.1.0-beta.2.
We also tried with a VPN, besides the scenarios from "https://github.com/mozilla-mobile/fenix/issues/13507#issuecomment-684799407"

**Comment by vesta0** [comment] 2020-09-16 17:39
Can we close this issue?

**Comment by liuche** [comment] 2020-09-17 01:36
I think even though QA wasn't able to reproduce this, some on the eng team could, and we're seeing a bump in positive reviews! so this is something we can close. Maybe there are some Google Play settings that we are not aware of that is making this difficult to test.

**Closed by liuche** 2020-09-17 01:36 UTC
Labels: E5, eng:qa:needed, needs:uplift, sourpatch

**Comment by softvision-miralobontiu** [comment] 2020-09-29 07:08
Hi all!
I was able to trigger the review prompt on the 9/28 Nightly build with Samsung Galaxy Note 8 (Android 9), and HTC 10 (Android 8). 
I'll remove the qa:needed label.
*Notes: 
- tapping on Undo, takes the user back to the review prompt (screenshot 2),
- tapping on Not now or Cancel, removes the prompt.

![review prompt](https://user-images.githubusercontent.com/40694158/94524457-4e9a6780-023b-11eb-947a-b703012384a5.png)
