### ISSUE TITLE
FNX-13766 ⁃ [Performance] The time from entering a url/opening a bookmark till fully loaded is high

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12664] opened 2020-07-17 11:25 UTC
## Steps to reproduce
Open any url/bookmark.
The page loads very slow.
My internet is fine.
I can open the same urls in chrome instantly.
However, very slow in Fenix (sometimes it works fine but it is rare).

I recorded a profile using the default `Web Developer` settings in `about:debugging`.
https://share.firefox.dev/2WtAyqW
Another profile with `firefox platform` settings -
https://share.firefox.dev/2Cjijxe
Another profile using some custom settings -
https://share.firefox.dev/3eA2tvj
Please tell if I need to profile differently or provide some other information.

### Device information
* Android device: 8
* Fenix version: All nightly versions I have used since I started using fenix.

**Comment by sheepycoder** [comment] 2020-07-17 13:51
A screen recording -

[20200717191605.zip](https://github.com/mozilla-mobile/fenix/files/4938162/20200717191605.zip)

**Comment by Furax-31** [comment] 2020-07-17 14:03
I have the same problem. Firefox is very very slow (all version, stable, beta, nightly). While the loading is instantaneous on Vivaldi (for example).

**Comment by eliserichards** [comment] 2020-07-17 18:02
Thank you for the profiles @sheepycoder! That's very helpful! Do you know if they are from the latest Nightly?

**Comment by sheepycoder** [comment] 2020-07-17 20:03
@eliserichards 
Yes, the profiles are recorded using the latest nightly.

**Comment by sheepycoder** [comment] 2020-07-20 12:55
Did anybody look at the profiles? Are they enough to find the issue, or more profiles or some more detail required?

**Comment by mcomella** [comment] 2020-07-22 22:57
Triage: we didn't see any java main thread issues in the profiles so we'll need someone from the platform side to take a look.

@acreskeyMoz Would you mind taking a look at the profiles to understand the source of the problems, or finding someone who could?

**Comment by acreskeyMoz** [comment] 2020-07-23 19:42
The biggest problems in the first profile (https://triplebyte.com) are the Dark Reader extension.

Almost 10 seconds of JS in the content process via this extension:
https://share.firefox.dev/3hvrv0G

And contributing to over a second of delay early on in the parent process:
https://share.firefox.dev/30EfajL

In the second profile (reddit.com) I'm also seeing huge delays in the parent process and the content process caused by the Dark Reader extension.

@sheepycoder -- thank you for collecting the profiles.
I can see that the Dark Reader extension is very problematic and I'll see what we can do about that.

In the meantime, can you please try Fenix with no additional extensions?

**Comment by acreskeyMoz** [comment] 2020-07-23 20:33
Running on the Moto G5 with the July 21 nightly Fenix:
https://triplebyte.com/interview_guide

With Dark Reader (we see Dark Reader busy in the content process during load (although nowhere near as bad as in the original shared profile)
https://share.firefox.dev/2EdEfuu

Without:
https://share.firefox.dev/2ONz7iL

The pageload is significantly faster (although still not great).

**Comment by sheepycoder** [comment] 2020-07-25 08:18
> The pageload is significantly faster (although still not great)
  
Confirmed on my phone that disabling dark reader improves the page loading times a lot, though it is still not great.

**Comment by acreskeyMoz** [comment] 2020-07-27 17:10
I've reached out to the addon developer to see what can be done to mitigate the impact of this popular addon during pageload.

Because that's by far the primary source of the performance problem in the bug I propose we close it and open others for particular sites if they are found.
In general, improving the pageload performance of Fenix is an ongoing priority.

**Comment by sheepycoder** [comment] 2020-07-28 08:19
Okay, closing this issue.

**Comment by mcomella** [comment] 2020-07-29 00:19
@acreskeyMoz Should we keep this issue open to track reaching out to the developer or is it okay to remain closed?

**Comment by acreskeyMoz** [comment] 2020-07-29 13:11
@mcomella I'd rather not keep it open in its current form (pageload in general being so poor).
We could create a new bug (or rename it) to be a DarkReader bug -- but then should it be logged against Fenix?

I had added an item to the "Android FE bi-weekly Sync up" to discuss addon performance -- maybe we can come up with best practices then?

**Comment by andreicristianpetcu** [comment] 2020-07-29 14:52
Please post here the DR perf bug here so we can track it.

**Comment by acreskeyMoz** [comment] 2020-07-29 19:41
FYI - I've heard back from the DarkReader developer that a Static mode is being developed for lower-end devices, as well as a caching mechanism.

**Closed** 2020-08-11 06:58 UTC
Labels: eng:performance
