### ISSUE TITLE
FNX3-15860 ⁃ [Bug] tab view: too much space between hostname and page title

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1852] opened 2019-04-20 06:32 UTC
### Steps to reproduce
1. open one or more tabs
1. go to home screen

### Expected behavior
There should be less space betwen the hostname and the page title, as seen in the image in #1839.

### Actual behavior
Too much space betwen the hostname and the page title.

![Screenshot](https://user-images.githubusercontent.com/1100614/56453739-e0176180-6346-11e9-9805-28bd32469371.png)UNITO-UNDERSCORE!20190420-083142!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 080dadcb7e1cc0aa53c020595505f6f493e4a143

**Comment by iadeelzafar** [comment] 2019-04-21 08:11
Thanks @cadeyrn for opening this ticket. I'm working on this and will make a PR soon.

**Comment by iadeelzafar** [comment] 2019-04-21 11:23
@cadeyrn I'm using [080dadc](https://github.com/mozilla-mobile/fenix/commit/080dadcb7e1cc0aa53c020595505f6f493e4a143) but still I'm unable to reproduce this issue. Maybe I'm missing something. Please enlighten me.
![image](https://user-images.githubusercontent.com/36811908/56469308-beef6780-6451-11e9-925e-d4acc05ffccf.png)

**Comment by iadeelzafar** [comment] 2019-04-21 11:46
Hi @cadeyrn , I pulled collin's branch and used the commit ```080dadc``` but still I'm unable to reproduce this issue. Maybe I'm missing something. Please enlighten me.
![image](https://user-images.githubusercontent.com/36811908/56469561-03303700-6455-11e9-836b-b36b06f02a9e.png)

**Comment by cadeyrn** [comment] 2019-04-21 12:23
Your screenshot shows the old tabs view from older builds. If you pull the master branch you will see the new tabs view and the issue.

**Comment by cadeyrn** [comment] 2019-04-23 07:12
After #1906 it looks like this now:

![Screenshot_20190423-085157](https://user-images.githubusercontent.com/1100614/56561440-6e8a1e00-65a7-11e9-8193-99b94146633f.png)

@boek: It looks much better now. Since you made the latest changes I'll let you decide if there is still something to improve or if the issue can be closed.

**Comment by iadeelzafar** [comment] 2019-04-23 07:18
@cadeyrn This looks fine in my opinion.

**Comment by vesta0** [comment] 2019-04-30 21:50
This is now fixed.

**Closed** 2020-08-11 10:08 UTC
Labels: Feature:HomeScreen, 🐞 bug
