### ISSUE TITLE
Have an option for back button/gesture to close tabs

### ISSUE THREAD

**Issue by bsmojver** [mozilla-mobile/fenix#19888] opened 2021-06-08 00:36 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Right now, tabs can be closed manually, on schedule, on exit etc. However, traditional option of closing the tab (present in Chrome for Android, for example), by pressing/gesturing back repeatedly, does not exist.

### How do you know that this problem exists today? Why is this important?

No option exists (to my knowledge) for the behaviour. Users switching from Chrome will come to expect this.

### Who will benefit from it?

All the folks using Chrome on Android, who are used to this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10946)

**Comment by ankitkaran99** [comment] 2021-06-08 06:20
And button for go forward is also required. That is available in chrome.

![Screenshot_20210608_114822](https://user-images.githubusercontent.com/34885126/121133106-91432380-c84f-11eb-91e7-528b49c695cf.jpg)

**Comment by bsmojver** [comment] 2021-06-08 07:48
> And button for go forward is also required. That is available in chrome.

You should probably open that as a separate feature request though.

**Comment by FrenchKoR** [comment] 2021-06-22 20:44
Hi. Same here, please add this option for back button to close tabs. It's not only about chrome users, Opera too !

**Comment by Terrails** [comment] 2021-11-05 10:20
Would really appreciate this as it's the only feature I'm missing when I switched over to Firefox on my phone. I mostly used this when opening a page from an external application and then closing it via the back button or just doing a simple search which I then close by going back.

**Comment by 1player** [comment] 2021-12-04 11:25
It's sorely needed on iOS as well. I dislike reading my RSS feed on Firefox mobile because each link opens in a new tab (as they should), and I need three taps for each link to close the tab and return to the previous tab with the RSS reader. Repeat that 50 times every morning while reading my news and it's a death from paper cuts. Safari has this feature and it's a life saver.

**Comment by cadeyrn** [comment] 2021-12-04 19:02
@1player This is the issues tracker for Firefox for Android. For Firefox for iOS you can find the issues tracker on https://github.com/mozilla-mobile/firefox-ios/issues.

**Comment by Smaehtin** [comment] 2021-12-19 11:54
I can't believe this has not been addressed yet. This is honestly some of the worst, most frustrating user-experience I have encountered in an app.
Take literally any other browser app on Android and:
1. Open a new tab
2. Go to google.com
3. Trigger the Android "back action" (back gesture, hardware/software back key)

What happens in all other browers except for Firefox? The tab is closed. On Firefox, the tab is still open. Why?

**Comment by krivit** [comment] 2021-12-26 22:09
Seconding this: although there *is* a way to close the current tab that is not too cumbersome (long press the tab button, and a popup menu appears with the option), it's not documented anywhere that I could find and is difficult to discover.

**Comment by cathodoluminescence** [comment] 2022-05-18 09:20
The long-press on tab is new to me, but it is as combersome as closing all newly opened tabs in the tab overview.

My normal usage is to go through a series of websites from the start page, one after the other. As of now, I end up with several open pages, which I then have to close manually again. Before, I just went back to the start page, opened the next page, clean & easy.

**Comment by enricojonas** [comment] 2022-05-19 05:53
Totally agree, that is irritating. Since I use FF on my computer I just gave it a shot on my mobile (again) for a couple of weeks now. But this is starting to annoy me so not sure how long I will manage before switching to something else again.

**Comment by chaoscommander** [comment] 2022-06-05 12:09
What frustrates me additionally is that this used to work until it was removed with an update (possibly the big redesign that also removed almost all other useful features).

**Comment by wekii** [comment] 2022-07-03 20:43
+1

**Comment by navid-zamani** [comment] 2022-08-23 05:57
Firefox opening a new tab with about:newtab and keeping tabs open, after picking a favorite from the about:newtab, looking at the page, and then pressing back, is THE SINGLE MOST ANNOYING thing in Firefox. Who ever thought that was a good idea, must have been the worst tab hoarder in existence.
You do it a few times, then suddenly you got a load of tabs open for no reason at all. about:newtab should be treated like any other normal URL. So ””back“ from another URL should lead to going to about:newtab in the same single tab it started in again.

I swear, the more ”smart“ software tries to be, the more annoying anc cumbersome and limited it becomed. Maybe people should chexk they are actually smart themselves, before trying to force others to use what they believe to be ”smart“ ”features“. Especially when the damn about:config has *deliberately* condescendingly been disabled because people didn’t want to put up with this this and switched it back and that was apparently too much for the feeble ego of those nannies.
I will only use Chrome-likes over my cold dead body, but I feel the Mozcolonslashslashla team *really* tries to make sure that actually happens.

This either changes, or I’m literally making my own fork that will be maximally hostile to Mozcolonslashslashla and actively do a Microsoft-style EEE on them. Should be trivial. Just start giving people freedoms. I’ll start by killing the ”cloud“.

**Comment by nicanecreed** [comment] 2022-09-06 10:12
I just switched from Chrome for multiple reasons but there are so many features missing from Firefox I'm not so sure I made the right choice. Pull down to refresh, and this as well.

When I'm on my homepage and click a shortcut, it opens that page fine and I do my business. I hit the back button and it goes back to the homepage. When I click a new shortcut, it actually opens a NEW tab with that shortcut, leaving the last one I opened, still open as well. I have about 6 shortcuts I check through in the morning (news and such) and after finished, I have 6 extra tabs open now for each one I have to manually close. It is strange behavior and not normal for what android users would expect. There are lots of extra "taps" required in Firefox... Thank you.

**Comment by Mugurell** [comment] 2022-10-10 06:27
Thank you @fice-t for opening https://github.com/mozilla-mobile/fenix/pull/27334 for adding a way close tabs with the back button if they have no history left.
Please note that the current behavior, settings and strings used in the app are aligned with Firefox on all other platforms so changing that even on just one platform has a bigger impact and has to be evaluated and approved by UX and product.

Adding here the recording for the proposed behavior and will UX for directions.

https://user-images.githubusercontent.com/13156601/194676546-0775803c-54a6-4a30-afa4-2206612b1243.mp4

**Comment by lime124** [comment] 2022-10-14 15:27
Removing needs ux label - this is a feature request/product improvement which should be a project that flows through our product road map.

**Comment by Mugurell** [comment] 2022-10-20 12:03
Reposting from https://github.com/mozilla-mobile/fenix/pull/27334#issuecomment-1285409097 for more visibility:

> @Mugurell Since [UX stated that it is up to product](https://github.com/mozilla-mobile/fenix/issues/19888#issuecomment-1279154548) is there someone I should ping from there to move this forward?

Based on the UX feedback the newly proposed gesture should go through bigger planning.
@kbrosnan to confirm the next steps.

**Comment by tbertels** [comment] 2022-11-06 09:15
Note that this works if the tab was opened from an other tab by long tapping on a link and choosing Open link in a new tab.
But then, after we swipe back to close the new tab, no undo close tab message is shown. See #27729.

**Comment by kompjuteras** [comment] 2022-11-12 10:28
This missing feature, implemented in all other browsers is the only thing that takes me out of Firefox Mobile.

**Comment by navid-zamani** [comment] 2022-11-13 10:01
> This missing feature,

You don’t understand: It’s not missing. It used to be like that in FF too! It’s much worse: It got *deliberately* removed , becausee some (clearly tab hoarder) user reported the correct funtionality as a ”bug“. And some ”developers“ did not reject the ”bug“ as madness. … It was not an accident, but a choice.

Given this self-destructivr behavior of FF, I’m close to concluding that Google got false flag moles in the FF team. ;)
I mean (given how WhatWG turned out and that) that is standard practice among government intelligence (my dad works in that area), so why would it not be standard practice in corporate intelligence? ;)

In any case, the Eternal September insane people have aggressively destroyed the WWW. It’s time to consider it, and browser ”platforms“, and HTTP deprecated.

**Comment by csadilek** [comment] 2022-12-22 19:30
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807067

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed** 2022-12-22 19:32 UTC
Labels: feature request 🌟, Feature:Tabs, Feature:Gesture

**Comment by ZOR21** [comment] 2023-01-31 11:23
Try the https://addons.mozilla.org/en-US/firefox/addon/back-to-close-we/

**Comment by navid-zamani** [comment] 2023-01-31 13:41
> Try the https://addons.mozilla.org/en-US/firefox/addon/back-to-close-we/

The problem is on mobile. Where Mozilla deliberately disabled most of the add-on API ”to save work“ for no reason, instead of keeping the exact same codebase as on desktop to actually save work, so most of the add-ons don’t work and there hence is a mere fixed list of add-ons, ruining literally the exact and only point of why people used Firefix in the first place,
killing Firefox on mobile.
We are just the stubborn remainders. And will leave when Firefox inevitably becomes a 100% Chrome clone before its corpse goes cold. (I mean the toxic ”cloud“ hostage taking of browser data, which is definitely deliberately evil, as proven by the fact that the manifest *chose* to block any other form of backup on the system, is already a thing. So we are 80% there.)

All in all, if Mozilla was a person, we’d determine that Mozilla committed assisted suicide, where assisted means deliberately and systematically driven insane by Hannibal Machiavelli Googlecter, due to being prone to it, due to being in denial about it.
I oersonally have given up on the web. Kill it with fire. And anything with ”apps“ or a ”store“ too.
I literally started writing my own post-mobile post-web post-desktop OS inspired by Plan 9 / Inferno (note: only the tip of the iceberg), and work every day to kill the HTML5 and mobile ”platforms“.

_I know, this is not the place. But *somebody has to say it*. And at that point, I don’t care anymore. … Like who’s gonna care about a new graffiti on the wall of a building in Pompeii when the eruption is already visible on the horizon? ^^_

**Comment by 424344** [comment] 2023-01-31 19:22
> Try the https://addons.mozilla.org/en-US/firefox/addon/back-to-close-we/

I tried it and it has issues when using discover in google apps.
it also doesn't work for special firefox pages, so it's not a solution.
this must be implemented natively.
