### ISSUE TITLE
[Bug] Reader mode theme change sometimes does not work

### ISSUE THREAD

**Issue by Gaspacchio** [mozilla-mobile/fenix#13213] opened 2020-08-02 15:15 UTC
## Steps to reproduce

Open a page where you can enable the reader mode, then try to change the theme (dark, sepia...).

### Expected behavior

Colours should change.

### Actual behavior

Nothing happens.

### Device information

* Android device: Samsung S8 (Android 9)
* Fenix version: Nightly 200802 06:16 (Build #22150627)

**Comment by ekager** [comment] 2020-08-02 22:07
I can reproduce in Nightly.

**Comment by csadilek** [comment] 2020-08-04 14:32
Thanks for filing! Unfortunately, I can't reproduce the problem. 

- Is it just the theme change that doesn't work or are font controls affected too (the +/- buttons)
- Does this happen on all pages e.g. does it happen on https://blog.mozilla.org/blog/2020/08/04/latest-firefox-rolls-out-enhanced-tracking-protection-2-0-blocking-redirect-trackers-by-default/

If you can still reproduce, it would be super helpful if you could attach logs here, if possible, both adb and using about:debugging to inspect the main process. @ekager if you can repro and have a minute :)

**Comment by Gaspacchio** [comment] 2020-08-04 14:36
I just tried again and it seems to be resolved. I'm on `200803` now, maybe the update fixed the issue?

**Comment by ekager** [comment] 2020-08-04 14:52
@csadilek just was able to reproduce on a NYT article on Nightly. It seems to be intermittent for me. 
https://drive.google.com/file/d/1dV9CZEjbADO6kk3qYNNtPkOenfYjLRZ5/view?usp=sharing

**Comment by csadilek** [comment] 2020-08-04 22:52
Thanks, @ekager. Took me a few tries, but was able to reproduce and spot the cause: https://github.com/mozilla-mobile/android-components/issues/7976

**Comment by csadilek** [comment] 2020-10-09 22:51
This is fixed now in latest Nightly (201009 17:03).

**Comment by sflorean** [comment] 2020-10-12 17:12
Verified as fixed on Nightly 10/12 with Samsung Galaxy Note 10(Android 10).

**Closed by sflorean** 2020-10-12 17:12 UTC
Labels: Feature:ReaderMode, eng:qa:needed, needs:ac, 🐞 bug
