### ISSUE TITLE
mdn.lol :[webcontent]

### ISSUE THREAD

**Issue by iSmokeMid69** [mozilla-mobile/fenix#28370] opened 2023-01-03 11:44 UTC
## Site with issue and any steps to reproduce
https://clks.pro/OWmgpc5supk - First URL>mdn.lol
Its A Shortlink Site And There Are 4-5 Steps To Get To Final Steps But Only On FireFox It Says This Error - 
![Screenshot_2023-01-03-17-41-49-434_org mozilla fenix](https://user-images.githubusercontent.com/112684643/210350847-2581a82e-d680-4be6-9902-7bd80ae7599c.jpg)

### Expected behavior
On Chromium Based Browsers Everything Works Meaning I Can Continue With The Steps
### Actual behavior
It Keeps Going To That Screen.html
### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No
### Can you reproduce in Chrome (or other non-Mozilla browser)?

Works Fine In Chrome
### Device information
Poco X3 Pro 
* Android device: 11
* Fenix version: 110.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22218)

**Comment by AdinaPetridean** [comment] 2023-01-03 13:27
Hello @iSmokeMid69, thank you for submitting the issue.
I was able to reproduce the issue on the latest Nightly (110.0a1) from 03.01.2023 build and Firefox 108.1.1.
Tested on: Motorola Moto G9 plus (Android 11).
Thanks!

**Comment by jonalmeida** [comment] 2023-01-17 18:48
I see the same working page in Chrome and Firefox so I'm going to close this as "works for me".

**Closed by jonalmeida** 2023-01-17 18:48 UTC
Labels: 🐞 bug, S3, Feature:Browsing, needs:triage, qa-triaged
