### ISSUE TITLE
[FEATURE REQUEST] Please add Lite Browser mode

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#12203] opened 2020-07-02 15:44 UTC
Please add a lite Browsing mode that will help to save data and speed up the browsing speed too.

Thank You.

**Comment by cadeyrn** [comment] 2020-07-02 17:28
Duplicate of #11536.

**Comment by kbrosnan** [comment] 2020-07-02 17:30
Closing as a duplicate

**Closed** 2020-08-28 21:28 UTC
Labels: needs:triage
