### ISSUE TITLE
[Bug] [Regression] Send to Device requires several additional actions

### ISSUE THREAD

**Issue by kodabb** [mozilla-mobile/fenix#17266] opened 2020-12-30 22:42 UTC
## Steps to reproduce
* in another app, hit the Share button
* tap "open in Firefox"

### Expected behavior
I should be able to select whether to Open in Firefox or Send to Device

### Actual behavior
* I need to switch to firefox
* hit hamburger menu
* hit share
* hit the device i want to share with

(total of 4 additional taps that were not present in the previous version of Firefox)

### personal comment
maybe there could be a separate "share to" option, one to open in firefox directly, one to send to device?
That would be even better as it would save one tap, but i'd just be happy in having the previous behaviour back

### Device information

* Android device: samsung galaxy tab 2018
* Fenix version: latest available version

**Comment by cadeyrn** [comment] 2020-12-30 23:42
Duplicate of #1523.

**Comment by sflorean** [comment] 2020-12-31 08:17
Closing as duplicate, based on the above comment.

**Closed by sflorean** 2020-12-31 08:17 UTC
Labels: needs:triage, 🐞 bug

**Comment by pguimier** [comment] 2022-10-21 06:00
But #1523 is locked...
