### ISSUE TITLE
[Bug] New and existing tabs never load, only displaying a blank screen

### ISSUE THREAD

**Issue by Ruin0x11** [mozilla-mobile/fenix#17507] opened 2021-01-18 07:06 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Open Firefox.
2. Open a new tab and navigate to a website.

### Expected behavior
The page starts loading with the progress bar at the bottom updating.

### Actual behavior
Nothing happens and the page is stuck at a black screen. The progress indicator at the bottom never appears. Pulling to refresh causes the refresh indicator to be stuck forever. I waited five minutes and the page still did not load. This means I can't browse any pages with Firefox. This also occurs with the tabs from the last browsing session and on startup.

![Screenshot_20210117-230410_Firefox_Nightly](https://user-images.githubusercontent.com/6700637/104882784-83304d00-5918-11eb-8e63-3ef05dcaa099.png)

### Device information

* Android device: OnePlus 7
* Fenix version: Nightly 210116

**Comment by softvision-miralobontiu** [comment] 2021-01-18 09:17
I've reproduced this issue opening an article from wikipedia.org, on Beta 85.0.0-beta.9 with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by csadilek** [comment] 2021-01-18 22:31
@softvision-miralobontiu I can't reproduce this here. Would you mind attaching logs? That should help.

/cc @agi This behaviour looks exactly what we had in https://bugzilla.mozilla.org/show_bug.cgi?id=1641715 (app responsive but page load not finishing) which is fixed in 86, but shouldn't affect 85 anyway.

**Comment by softvision-miralobontiu** [comment] 2021-01-19 08:55
Christian, I was not able to reproduce the issue today. I'll investigate more and leave a logcat, if I encounter it again.
Thanks!

**Comment by Ruin0x11** [comment] 2021-01-19 10:49
I think this is a dupe of https://github.com/mozilla-mobile/fenix/issues/16259

**Comment by mcarare** [comment] 2021-01-22 12:19
@Ruin0x11 Does this still happen on the latest Nightly (210121)?

**Comment by Ruin0x11** [comment] 2021-01-22 13:33
I have this log from 210119:

<details><summary>Log</summary>
<p>

```
[01-22 05:25:22.599 32455:32615 W/FirefoxAccountStateMachine]
Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$Start@95fa49b' for state Idle(accountState=Authenticated).

[01-22 05:25:22.631 32455:479 I/libglean_ffi]
glean_core::upload: New upload task with id 7f7bba46-026b-4b15-9ec0-3fb3697612ad (path: /submit/org-mozilla-fenix/baseline/1/7f7bba46-026b-4b15-9ec0-3fb3697612ad)

[01-22 05:25:22.631 32455:32491 I/FirefoxAccount]
Executing: get access token

[01-22 05:25:22.645 32455:32455 I/WebExtension]
releasePendingMessages: extension=fxa@mozac.org nativeApp=mozacWebchannel session=org.mozilla.geckoview.GeckoSession@c979a4b

[01-22 05:25:22.688 32455:32491 I/FirefoxAccount]
Successfully executed: get access token

[01-22 05:25:22.692 32455:32491 I/FirefoxAccount]
Executing: getTokenServerEndpointURL

[01-22 05:25:22.692 32455:32491 I/FirefoxAccount]
Successfully executed: getTokenServerEndpointURL

[01-22 05:25:22.741 32455:479 I/libglean_ffi]
glean_core::upload: Ping 7f7bba46-026b-4b15-9ec0-3fb3697612ad successfully sent 200.

[01-22 05:25:22.741 32455:479 I/libglean_ffi]
glean_core::upload::directory: File was deleted /data/user/0/org.mozilla.fenix/glean_data/pending_pings/7f7bba46-026b-4b15-9ec0-3fb3697612ad

[01-22 05:25:22.741 32455:479 I/libglean_ffi]
glean_core::upload: No more pings to upload! You are done.

[01-22 05:25:22.742 32455:32488 I/WM-WorkerWrapper]
Worker result SUCCESS for Work [ id=a66281a1-c700-496c-a292-878feefa7e33, tags={ mozilla.telemetry.glean.scheduler.PingUploadWorker, mozac_service_glean_ping_upload_worker } ]

[01-22 05:25:26.644 32455:32615 W/FirefoxAccountStateMachine]
Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$Start@95fa49b' for state Idle(accountState=Authenticated).

[01-22 05:25:26.648 32455:32491 I/FirefoxAccount]
Executing: get access token

[01-22 05:25:26.689 32455:32491 I/FirefoxAccount]
Successfully executed: get access token

[01-22 05:25:26.692 32455:32491 I/FirefoxAccount]
Executing: getTokenServerEndpointURL

[01-22 05:25:26.692 32455:32491 I/FirefoxAccount]
Successfully executed: getTokenServerEndpointURL

[01-22 05:25:27.077 32455:32455 I/GeckoSession]
handleMessage GeckoView:PageStart uri=

[01-22 05:25:27.238 32455:32455 I/GeckoSession]
handleMessage GeckoView:PageStop uri=null

[01-22 05:25:27.291 32455:32465 I/g.mozilla.feni]
Background concurrent copying GC freed 565168(18MB) AllocSpace objects, 44(9MB) LOS objects, 24% free, 73MB/97MB, paused 94us total 108.477ms

[01-22 05:25:27.713 32455:32487 I/WM-WorkerWrapper]
Worker result SUCCESS for Work [ id=b82ebdd5-2558-430f-9566-5df5cc5ef850, tags={ mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce, Common } ]

[01-22 05:25:52.565 32455:32614 I/SessionStorage/AutoSave]
Save: Periodic

[01-22 05:25:54.935 32455:32615 W/FirefoxAccountStateMachine]
Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$Start@95fa49b' for state Idle(accountState=Authenticated).

[01-22 05:25:54.939 32455:32499 I/FirefoxAccount]
Executing: get access token

[01-22 05:25:54.978 32455:32499 I/FirefoxAccount]
Successfully executed: get access token

[01-22 05:25:54.979 32455:32499 I/FirefoxAccount]
Executing: getTokenServerEndpointURL

[01-22 05:25:54.979 32455:32499 I/FirefoxAccount]
Successfully executed: getTokenServerEndpointURL

[01-22 05:25:57.867 32455:32470 I/g.mozilla.feni]
Waiting for a blocking GC ProfileSaver

[01-22 05:25:58.400 32455:32455 I/GeckoSession]
handleMessage GeckoView:PageStart uri=

[01-22 05:25:58.583 32455:32455 I/GeckoSession]
handleMessage GeckoView:PageStop uri=null

[01-22 05:26:00.014 32455:32488 I/WM-WorkerWrapper]
Worker result SUCCESS for Work [ id=db106cc0-2173-4bdd-9ad1-2302b776f0ac, tags={ mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce, Common } ]

[01-22 05:26:02.478 32455:32615 W/FirefoxAccountStateMachine]
Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$Start@95fa49b' for state Idle(accountState=Authenticated).

[01-22 05:26:02.483 32455:32490 I/FirefoxAccount]
Executing: get access token

[01-22 05:26:02.534 32455:32490 I/FirefoxAccount]
Successfully executed: get access token

[01-22 05:26:02.535 32455:32490 I/FirefoxAccount]
Executing: getTokenServerEndpointURL

[01-22 05:26:02.535 32455:32490 I/FirefoxAccount]
Successfully executed: getTokenServerEndpointURL

[01-22 05:26:02.727 32455:32455 I/GeckoSession]
handleMessage GeckoView:PageStart uri=

[01-22 05:26:02.848 32455:32455 I/GeckoSession]
handleMessage GeckoView:PageStop uri=null

[01-22 05:26:07.572 32455:32485 I/WM-WorkerWrapper]
Worker result SUCCESS for Work [ id=41e3f428-b9d2-44d4-aeb7-409137209f63, tags={ mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce, Common } ]

[01-22 05:26:09.587 32455:32615 W/FirefoxAccountStateMachine]
Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$Start@95fa49b' for state Idle(accountState=Authenticated).

[01-22 05:26:09.591 32455:32491 I/FirefoxAccount]
Executing: get access token

[01-22 05:26:09.641 32455:32491 I/FirefoxAccount]
Successfully executed: get access token

[01-22 05:26:09.641 32455:32491 I/FirefoxAccount]
Executing: getTokenServerEndpointURL

[01-22 05:26:09.642 32455:32491 I/FirefoxAccount]
Successfully executed: getTokenServerEndpointURL

[01-22 05:26:09.836 32455:32455 I/GeckoSession]
handleMessage GeckoView:PageStart uri=

[01-22 05:26:09.943 32455:32455 I/GeckoSession]
handleMessage GeckoView:PageStop uri=null

[01-22 05:26:14.673 32455:32482 I/WM-WorkerWrapper]
Worker result SUCCESS for Work [ id=4e2bed0e-1de3-4257-8527-3b158e838404, tags={ mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce, Common } ]

[01-22 05:26:22.565 32455:32614 I/SessionStorage/AutoSave]
Save: Periodic

[01-22 05:26:52.565 32455:32614 I/SessionStorage/AutoSave]
Save: Periodic

[01-22 05:26:52.580 32455:32615 W/FirefoxAccountStateMachine]
Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$Start@95fa49b' for state Idle(accountState=Authenticated).

[01-22 05:26:52.581 32455:32491 I/FirefoxAccount]
Executing: get access token

[01-22 05:26:52.622 32455:32491 I/FirefoxAccount]
Successfully executed: get access token

[01-22 05:26:52.623 32455:32491 I/FirefoxAccount]
Executing: getTokenServerEndpointURL

[01-22 05:26:52.623 32455:32491 I/FirefoxAccount]
Successfully executed: getTokenServerEndpointURL

[01-22 05:26:53.558 32455:32455 I/GeckoSession]
handleMessage GeckoView:PageStart uri=

[01-22 05:26:53.725 32455:32455 I/GeckoSession]
handleMessage GeckoView:PageStop uri=null

[01-22 05:26:57.649 32455:32482 I/WM-WorkerWrapper]
Worker result SUCCESS for Work [ id=db2bfba1-4b8e-4c4d-b9b4-14ee32fab6d7, tags={ mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce, Common } ]

[01-22 05:27:04.089 32455:32615 W/FirefoxAccountStateMachine]
Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$Start@95fa49b' for state Idle(accountState=Authenticated).

[01-22 05:27:04.093 32455:32523 I/FirefoxAccount]
Executing: get access token

[01-22 05:27:04.158 32455:32523 I/FirefoxAccount]
Successfully executed: get access token

[01-22 05:27:04.159 32455:32523 I/FirefoxAccount]
Executing: getTokenServerEndpointURL

[01-22 05:27:04.160 32455:32523 I/FirefoxAccount]
Successfully executed: getTokenServerEndpointURL

[01-22 05:27:09.196 32455:32487 I/WM-WorkerWrapper]
Worker result SUCCESS for Work [ id=8fdd4a9e-a2ba-4698-9156-24fa26c07cf7, tags={ mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce, Common } ]

[01-22 05:27:12.393 32455:32615 W/FirefoxAccountStateMachine]
Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$Start@95fa49b' for state Idle(accountState=Authenticated).

[01-22 05:27:12.395 32455:32490 I/FirefoxAccount]
Executing: get access token

[01-22 05:27:12.439 32455:32490 I/FirefoxAccount]
Successfully executed: get access token

[01-22 05:27:12.440 32455:32490 I/FirefoxAccount]
Executing: getTokenServerEndpointURL

[01-22 05:27:12.441 32455:32490 I/FirefoxAccount]
Successfully executed: getTokenServerEndpointURL

[01-22 05:27:14.302 32455:32615 W/FirefoxAccountStateMachine]
Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$Start@95fa49b' for state Idle(accountState=Authenticated).

[01-22 05:27:14.305 32455:32490 I/FirefoxAccount]
Executing: get access token

[01-22 05:27:14.365 32455:32490 I/FirefoxAccount]
Successfully executed: get access token

[01-22 05:27:14.366 32455:32490 I/FirefoxAccount]
Executing: getTokenServerEndpointURL

[01-22 05:27:14.366 32455:32490 I/FirefoxAccount]
Successfully executed: getTokenServerEndpointURL

[01-22 05:27:17.458 32455:32487 I/WM-WorkerWrapper]
Worker result SUCCESS for Work [ id=27bbf965-189d-4ec3-aa89-1e2c77ecde5f, tags={ mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce, Common } ]

[01-22 05:27:21.559 32455:32480 I/libglean_ffi]
glean_core::ping: Collecting startup-timeline

[01-22 05:27:21.559 32455:32455 I/SessionStorage/AutoSave]
Save: Background

[01-22 05:27:21.565 32455:32480 I/libglean_ffi]
glean_core::ping: Storage for startup-timeline empty. Bailing out.

[01-22 05:27:21.565 32455:32480 I/libglean_ffi]
glean_core: No content for ping 'startup-timeline', therefore no ping queued.

[01-22 05:27:21.572 32455:32480 I/libglean_ffi]
glean_core::ping: Collecting baseline

[01-22 05:27:21.576 32455:32455 I/WebAuthnFeature]
Feature stopped.

[01-22 05:27:21.585 32455:32480 I/libglean_ffi]
glean_core::upload::directory: Processing ping at: /data/user/0/org.mozilla.fenix/glean_data/pending_pings/8dac355a-8a5b-46fb-ae98-494091fe3262

[01-22 05:27:21.585 32455:32480 I/libglean_ffi]
glean_core: The ping 'baseline' was submitted and will be sent as soon as possible

[01-22 05:27:21.586 32455:32480 I/libglean_ffi]
glean_core::ping: Collecting events

[01-22 05:27:21.597 32455:32480 I/libglean_ffi]
glean_core::upload::directory: Processing ping at: /data/user/0/org.mozilla.fenix/glean_data/pending_pings/abd5b425-c0c9-40c8-9f67-227b0081cdc4

[01-22 05:27:21.598 32455:32480 I/libglean_ffi]
glean_core: The ping 'events' was submitted and will be sent as soon as possible

[01-22 05:27:21.609 32455:32455 I/FenixApplication]
onTrimMemory(), level=80, main=true

[01-22 05:27:21.627 32455:32494 I/TrimMemoryMiddleware]
Trim memory (tabs=1899, suspending=0)

[01-22 05:27:21.636 32455:553 I/libglean_ffi]
glean_core::upload: New upload task with id 8dac355a-8a5b-46fb-ae98-494091fe3262 (path: /submit/org-mozilla-fenix/baseline/1/8dac355a-8a5b-46fb-ae98-494091fe3262)

[01-22 05:27:21.965 32455:553 I/libglean_ffi]
glean_core::upload: Ping 8dac355a-8a5b-46fb-ae98-494091fe3262 successfully sent 200.

[01-22 05:27:21.966 32455:553 I/libglean_ffi]
glean_core::upload::directory: File was deleted /data/user/0/org.mozilla.fenix/glean_data/pending_pings/8dac355a-8a5b-46fb-ae98-494091fe3262

[01-22 05:27:21.968 32455:553 I/libglean_ffi]
glean_core::upload: New upload task with id abd5b425-c0c9-40c8-9f67-227b0081cdc4 (path: /submit/org-mozilla-fenix/events/1/abd5b425-c0c9-40c8-9f67-227b0081cdc4)

[01-22 05:27:22.109 32455:553 I/libglean_ffi]
glean_core::upload: Ping abd5b425-c0c9-40c8-9f67-227b0081cdc4 successfully sent 200.

[01-22 05:27:22.109 32455:553 I/libglean_ffi]
glean_core::upload::directory: File was deleted /data/user/0/org.mozilla.fenix/glean_data/pending_pings/abd5b425-c0c9-40c8-9f67-227b0081cdc4

[01-22 05:27:22.111 32455:553 I/libglean_ffi]
glean_core::upload: No more pings to upload! You are done.

[01-22 05:27:22.113 32455:32488 I/WM-WorkerWrapper]
Worker result SUCCESS for Work [ id=1df850d6-2138-42fd-8381-f505e031a1c3, tags={ mozilla.telemetry.glean.scheduler.PingUploadWorker, mozac_service_glean_ping_upload_worker } ]

[01-22 05:27:22.506 32455:32455 I/FenixApplication]
onTrimMemory(), level=80, main=true

[01-22 05:27:22.517 32455:32494 I/TrimMemoryMiddleware]
Trim memory (tabs=1899, suspending=0)

[01-22 05:27:48.320 32455:32455 I/FenixApplication]
onTrimMemory(), level=80, main=true

[01-22 05:27:48.335 32455:32494 I/TrimMemoryMiddleware]
Trim memory (tabs=1899, suspending=0)

[01-22 05:28:54.130 32455:32455 I/FenixApplication]
onTrimMemory(), level=80, main=true

[01-22 05:28:54.161 32455:32494 I/TrimMemoryMiddleware]
Trim memory (tabs=1899, suspending=0)
```

</p>
</details>

**Comment by mcarare** [comment] 2021-01-26 06:37
@Ruin0x11 As far as I can see there is no hint in the log you provided. Can you please check the latest Nighty to see if you can reproduce the issue?

**Comment by mcarare** [comment] 2021-02-01 13:14
For QA: Please try to reproduce this issue on Nightly. If it does not reproduce please close this. Thank you!

**Comment by GottemHams** [comment] 2021-02-01 16:55
Just dropping a couple of cents here:

I always check some tech sites during lunch breaks at work, I usually open like 10 tabs every time but sometimes I don't get through them all. Then the next day I want to resume from the last article I've read and Firefox will sometimes briefly show a loading bar but it will quickly disappear and the page won't actually load. If I refresh (up to) a couple of times by tapping the address bar so it goes into typing mode, followed by simply hitting enter it will usually start loading again. Using the actual refresh button doesn't seem to help.

Much less often (at least for me) the exact same thing happens for new tabs.

I had updated Firefox to the latest stable version just yesterday, so unfortunately I don't know if it applies to the nightly build, but I think it's recent enough that the problem should still be there in nightly. I do know this happened over multiple stable versions, however.

**Comment by ebalazs-sv** [comment] 2021-02-03 08:57
> For QA: Please try to reproduce this issue on Nightly. If it does not reproduce please close this. Thank you!

I tested this issue on the latest Nightly 2/3 with Samsung Galaxy Tab S3 (Android 8) and was not able to reproduce it.
Also, softvision-miralobontiu confirmed today, that this issue was not reproducible anymore on the latest builds.

I will close this issue for now and if we encounter it, this will be reopened together with the logs.

**Comment by softvision-miralobontiu** [comment] 2021-02-03 09:26
I will re-open this issue, since I've just encountered it on the aliexpres.com page trying to choose a product category.
Environment: 2/3 Nightly build, Samsung Galaxy Note 8 (Android 9) device


[logcat.txt](https://github.com/mozilla-mobile/fenix/files/5917328/logcat.txt)

**Comment by Mikaka27** [comment] 2021-02-26 17:16
Hi, user here. I saw similar thing when no website can be loaded. If some website is loaded I cannot interact with it.

I didn't managed to catch it with a performance profile yet.
However when it happened before I ran a "top" command in terminal emulator and saw that main process of fenix was using 100% cpu (meaning one thread was stuck with something).

When testing on fennec f-droid (when I get about:config), I found it to only happen when "webrender" is disabled. Maybe it's related to that, but I'm not sure. I'll try to catch it with a performance profile when it happens.

**Comment by lobontiumira** [comment] 2021-04-13 11:47
I reproduced this issue on the 4/13 Nightly on aliexpress.com, and on pinterest.com eith Samsung Galaxy Note 8 (Android 9).

**Comment by gabrielluong** [comment] 2021-04-25 22:10
Clearing assignee since I don't believe this is being worked on.

**Comment by mcarare** [comment] 2021-04-26 13:03
@lobontiumira Is this still reproducing? I tried on a Huawei P10 with Android 9 and it works as expected on both aliexpress and pintrest. Thank you!

**Comment by lobontiumira** [comment] 2021-04-26 14:11
Hi, Mihai!
Yes, I was able to reproduce it again on the Samsung Galaxy Note 8 (Android 9) device on 4/26 Nightly build, on both aliexpress.com, and pinterest.com. Only if the user long-taps the "refresh" button from the menu, the page seems to load, but not all of them. Please see the short video below:


https://user-images.githubusercontent.com/40694158/116096809-419b0500-a6b2-11eb-92a3-8f4cf294b8f2.mp4

**Comment by mcarare** [comment] 2021-04-27 12:09
QA also tested this on Gecko View Example and the issue also reproduces there. So this might be a Geckoview issue related or not to the web content of those pages.

**Comment by mcarare** [comment] 2021-04-27 12:18
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1707871

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by mcarare** [comment] 2021-04-27 12:19
Reopened for tracking fixes.

**Comment by amedyne** [comment] 2021-07-19 20:52
Removing from Kanban board until we hear from the bugzilla dependency.

**Closed** 2022-01-23 04:56 UTC
Labels: 🐞 bug, 🙅 waiting, needs:gv, Feature:Tabs, S2, Feature:Browsing, wontfix
