### ISSUE TITLE
Toggle for Tab Management

### ISSUE THREAD

**Issue by illmaren** [mozilla-mobile/fenix#14351] opened 2020-08-28 09:25 UTC
### What is the user problem or growth opportunity you want to see solved?
The new Tab Management is just not well thought out. 
Add a toggle to let the user use the old one. I mean dont dictate what the user MUST use....let them use what they want.

hundreds of bad reviews all over the internet

### Who will benefit from it?
everyone who loves the old tab mangement and hates the new.

**Comment by hwinnemoe** [comment] 2020-08-28 09:38
"This is a complete re-write, there's not a way to support both forks." https://github.com/mozilla-mobile/fenix/issues/14188#issuecomment-682216580

**Comment by s0ss** [comment] 2020-08-28 12:14
IMO this is not a dupe of #14188 
The Crux of the issue is that lots of people don't want the current tab management. Literally using the old one isn't the issue. People just don't want to use an objectively inferior tab management UI.

**Comment by cadeyrn** [comment] 2020-08-28 12:23
> IMO this is not a dupe of #14188

How is this not a dupe of #14188? "Add a toggle to let the user use the old one" (this issue) is exactly the same as "Set the old UI as opt in" (#14188).

**Comment by s0ss** [comment] 2020-08-28 12:27
Semantics. You're ignoring the issue that the tab management is inferior and focusing on the inability to literally use old code.

**Comment by Dunexus** [comment] 2020-08-28 12:30
Be careful when using *objectively*. It may be your opinion, the opinion of many but it is **not** objective.

The team will **not** maintain 2 UI code. Saying the tab management is inferior doesn't help improving it. Tab tray is still being worked on and **constructive** feedback is welcome.

**Comment by hwinnemoe** [comment] 2020-08-28 12:35
I fail to understand why you disliked my comment, this issue proposes to add a toggle for bringing back the old tab management UI. Issue #14188 proposed exactly the same idea. I'm also merely quoting the developer's stance on this.

**Comment by s0ss** [comment] 2020-08-28 12:42
Not maintaining two UIs makes perfect sense to me. Saying the old ui worked better isn't unconstructive though. Vertical listed tabs is much harder to use on mobile devices.

Sorry @hwinnemoe I was blinded by nerd rage.

Linking this issue, which represents fixing something I dislike, to a ticket that is closed as a dupe is frustrating to me. There are dozens of one star reviews on the play store and this is one of the chief UI complaints.

I am just frustrated useful things were discarded and replaced by less useful things. Sorry guys.

**Comment by illmaren** [comment] 2020-08-28 12:46
The problem I have with the new tray is that its just another "chrome like" shit. I mean if I wanted a UI like chrome I would use one of these many chrome clones out there. But now my favorite Browser, firefox, is another of these clones...for what? get more Users? Then go and make something which makes you different. Something unique to you and only you. Whats the Reason now to use Firefox? cause its fast? Chrome is fast too. Now I have no reason to use Firefox at all I mean its the same shit as everywhere else.

Thats my critic to this Tab Tray. Its exactly the same as every other browser out there. Copying makes not better.
The Tab Management was one of the strong points with Firefox in my opinion, because it made it easy to handle 40+ tabs. Now I have this long list and if I open another Tab out of one I need to search the new Tab...where is this better?

**Comment by Dunexus** [comment] 2020-08-28 12:57
Again, saying it is bad, chrome-like or whatever doesn't help to improve it.

Please explicit what makes the old one better and what could be done to improve the new one.
You say "it made it easy to handle 40+ tabs", could you explicit how it was better at handling large number of tabs ?

**Comment by hwinnemoe** [comment] 2020-08-28 12:58
#13098 likely is the issue you both should follow then, maybe also other issues regarding tab tray design, e.g https://github.com/mozilla-mobile/fenix/issues?q=is%3Aissue+label%3AFeature%3ATabs+author%3Avesta0+is%3Aopen - those are the tab management related issues opened by Fenix product manager.

**Comment by illmaren** [comment] 2020-08-28 13:11
You want specific reasons? ok

**1.** Only 3/4 of the screen are used. Why?
**2.** Only in listing forms. you loose oversight with many tabs as you need to scroll more. (add raster) 
**3.** New Tabs are not at the end of the list but below the parent tab. With this overview of Tabs its just hard to find the correct tabs if you just opend them for later usage.
**4.** The "New Tab" Button moved to a very unfamiliar and uncomfortable position. Just to fast clicks on the same position there nice and fast. Why do I need to travel with my thumb now just to open a tab? I got a S10+ and with this layout I need a second hand just to open a new Tab.
**5.** The Space for "Normal" and "Privacy" Tabs is quite a bit large eh? space lost for thing which are more important. Solution here leave it to the user to decide for the Button size...doesnt need another UI just a Option.

Here now you've got some points from me which make it hard for me to like or even use this new UI. Keep in mind I'm only talking about the Tab Tray here. Nothing else. And even then I get 5 Points out without even searching for them.

**Comment by U-B-Glade** [comment] 2020-08-28 17:44
Hello together,

first I like to say, that the new UI not use Tabs, it use Pages, Tabs by define are on the top of the screen and always viewable.

And if I like to work fast, I'd like to use real Tabs, that I can hit fast and I do not like to click twice, aspecially on Tablets where is enough Space. 

Many Comments of disappointed User say right that. 

The main critizised Points are the UI and the lost of possibilities.

**Comment by Dunexus** [comment] 2020-08-28 17:49
@U-B-Glade See https://github.com/mozilla-mobile/fenix/issues/4498 for tablet UI

**Comment by U-B-Glade** [comment] 2020-08-28 18:02
Yes I know it, but I like it also on my Smartphone, the old one was good and useable

**Comment by liuche** [comment] 2020-08-28 21:42
Thanks for the feedback. We won't be supporting two versions going forward, but we do have a feature request for compact tabs #13098

**Closed by liuche** 2020-08-28 21:42 UTC
Labels: needs:triage
