### ISSUE TITLE
[Bug] Pinned sites on the home page have incorrect names

### ISSUE THREAD

**Issue by bjherbison** [mozilla-mobile/fenix#19677] opened 2021-05-26 17:40 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)
I have a set of pinned tabs I've been using for a while. Today I actually looked at the text under the icons and realized it was incorrect for six of the eight icons.

After I went into settings to get the build number and returned to the home screen all the names were correct again.

Please let me know what information I should try to capture (and how to capture it) the next time I see the issue.

## Steps to reproduce
Pin sites and wait a few weeks. Look at the text.
### Expected behavior
The names are associated with the pinned URLs.
### Actual behavior
In the first row, Wikipedia is correct. The second icon is Google News, the third is Slashdot, and the fourth is Soylent News.
The names for six of the eight are sites I visited recently with my synced desktop browser.
![Screenshot_20210526-132401](https://user-images.githubusercontent.com/4101902/119705525-d9614f80-be26-11eb-9679-c958b5c3dbcd.jpg)

### Device information

* Device vendor / model and Android version: Google / Pixel 4 and 11.
* Firefox for Android version: Nightly 90.0a1 (Build #2015812491)

**Comment by kbrosnan** [comment] 2021-05-26 20:26
I believe I have seen this too. Was not able to get a screenshot.

**Comment by bjherbison** [comment] 2021-05-27 01:03
It's now 7 hours later and I've used my desktop Firefox a bit and my Android Firefox a bit.
Currently:
Google News is called "Element" (no [5] as before).
Slashdot is called "Coin Catalo..."
Soylent News is called "404 Not Fo...".
Similar names to before, but in different places. And the other five entries are unchanged.

(The point of this update is that the corruption happens in different, but similar ways. I don't plan to post continual travelogues, I'll only give an update if I get some significantly new information that I think might help in debugging.)

**Comment by samlh** [comment] 2021-05-30 16:53
Long pressing a site and selecting remove reproduces the issue

**Comment by rfk** [comment] 2021-05-31 03:47
I periodically observe something similar on my device, although with the auto-generated list of top sites rather than pinned sites:
![Screenshot_20210530-205051_Firefox Nightly](https://user-images.githubusercontent.com/34695/120136955-a6e49780-c216-11eb-93b7-5df0b51fe310.jpg)

**Comment by codrut-topliceanu** [comment] 2021-07-15 08:07
I think this was fixed by https://github.com/mozilla-mobile/fenix/pull/20005 .

**Comment by lobontiumira** [comment] 2021-07-21 12:27
I was not able to reproduce this issue on the 92.0a1 Nightly from 7/21. I've added some top sites, deleted some, deleted some most visited pages displayed in the top sites section, and all the pinned sites had their correct names.
Tested on multiple devices: Google Pixel (Android 10), Samsung Galaxy Tab A6 (Android 5.1.1), and HTC 10 (Android 8).
I'll close this, but feel free to reopen it if you encounter this issue again.
Thank you!

**Closed by lobontiumira** 2021-07-21 12:27 UTC
Labels: Feature:HomeScreen, S2, eng:qa:needed, 🐞 bug, 🙅 waiting
