### ISSUE TITLE
[Bug] Webpage scrolling jumps back when showing or hiding top toolbar

### ISSUE THREAD

**Issue by rilden** [mozilla-mobile/fenix#15380] opened 2020-09-24 10:28 UTC
## Steps to reproduce
- set toolbar position to top (settings>customize>toolbar>top)
- go to any site that is long enough to scroll vertically (for example: https://github.com/mozilla-mobile/fenix)
- make sure the toolbar is visible (scroll to reveal the toolbar)
- scroll down on the webpage just a small amount (less than half the height of the toolbar)
### Expected behavior
- the toolbar scrolls down a small amount but jumps back to display fully when the finger is removed from the touchscreen
- the webpage scrolls down a small amount and **remains at its new location** when the finger is removed from the touchscreen
### Actual behavior
- the toolbar scrolls down a small amount but jumps back to display fully when the finger is removed from the touchscreen
- the webpage scrolls down a small amount but **jumps back to its original location** when the finger is removed from the touchscreen
### Device information

* Android device: samsung galaxy a40
* Fenix version: ?

This bug only occurs with toolbar on top, doesn't occur with toolbar on bottom.

There are 4 cases when this error occurs:
- when the toolbar is visible and the user scrolls down less that half the height of the toolbar (this case is explained above in the steps to reproduce)
- when the toolbar is visible and the user scrolls down more than half the toolbar height but less that a full toolbar height. In this case the webpage jumps a full scrollbar height.
- when the toolbar is not visible and the user scrolls up less that half the height of the toolbar. The webpage jumps back to its original position.
- when the toolbar is not visible and the user scrolls up more than half the toolbar height but less that a full toolbar height. In this case the webpage jumps a full scrollbar height.

It's like the webpage and the toolbar are glued together. When the toolbar moves the webpage moves with it. The webpage shouldn't move when the toolbar shows or hides itself.
![20200924_134146](https://user-images.githubusercontent.com/9265760/94135411-1de9b500-fe6c-11ea-92ad-d729ffaa6bc5.gif)

**Comment by hwinnemoe** [comment] 2020-09-25 10:06
Related to/Duplicate of #6976

**Closed** 2020-10-14 23:52 UTC
Labels: needs:triage, 🐞 bug
