### ISSUE TITLE
[UX] [Bug] Open in New Tab should insert tab below current tab rather than above

### ISSUE THREAD

**Issue by robsmith11** [mozilla-mobile/fenix#10365] opened 2020-05-02 02:24 UTC
## Steps to reproduce
Open enough tabs so that the tab switching window is full and requires scrolling. 

Open a link by long pressing and clicking "open in a new tab". 

Go to the tab switching window.  The new tab will be hidden because it's been inserted above the current tab, which is at the top of the screen.  To switch to the new tab, one needs to first scroll down through the tabs. 

### Expected behavior
The new tab should be inserted below the current tab so no scrolling is required to switch to it. 

### Actual behavior
See above. 

### Device information
Firefox Nightly on Huawei Mate 20 X

* Android device: ?
See above. 
* Fenix version: ?
See above.

**Comment by topotropic** [comment] 2020-05-04 07:49
Thanks for the feedback. As far as I can see is the new tab inserted below the current tab. What's missing is, that currently FX Preview always renders from top and not with the current tab in view.

**Comment by liuche** [comment] 2020-05-14 18:55
From UX: needs some consistency of where new tabs vs appended tabs should go

(Could we copy Fennec behavior by default?)

**Comment by maverick74** [comment] 2020-08-04 20:19
I vote for this. 
It's a pita to have to go all the way up the screen to switch to a recently opened tab

**Comment by yoasif** [comment] 2020-09-10 13:49
It feels like this issue is a consequence of the tab sort order, which https://github.com/mozilla-mobile/fenix/issues/11376 attempts to fix. I would rather fix https://github.com/mozilla-mobile/fenix/issues/11376 and the issue filed here would no longer exist.

**Comment by maverick74** [comment] 2020-09-11 10:58
I agree this is sort of a duplicate of #11376 
This, along with #12861 (that is more directed to Swiping gesture) and #10454 are all related, i believe.

Would be nice to have a metabug for all this related UX issues.

and would be good to close the apparent (lots of) duplicates of #11376 .

**Comment by abodea** [comment] 2021-03-09 12:23
This issue is reproducible on the Beta 87.0.0-beta.4 build with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment] 2021-05-28 09:04
This issue still reproduces on RC 89.1.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by SoftVision-LorandJanos** [comment] 2021-11-26 08:49
This is no longer reproducible on the latest builds:
- latest Nightly (2021-11-26).
- latest Beta (95.0.0beta5).
- latest Release (94.1.2).

The new tab is opened below the current tab.

Device used: Xiaomi Mi11 Lite (Android 11).

Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2021-11-26 08:49 UTC
Labels: 🐞 bug, needs:ac, P3, needs:investigation, Feature:Tabs, wontfix
