### ISSUE TITLE
Focus on the address bar, when fenix is set to device assistance app

### ISSUE THREAD

**Issue by xuyuehang** [mozilla-mobile/fenix#16669] opened 2020-11-20 07:28 UTC
Device Assistance is a function on Android. The default is Google Assistant, which can be replaced by fennec or fenix. You can quickly enter firefox by pressing and holding the home button.
https://support.mozilla.org/en-US/kb/how-replace-google-assistant-firefox-search

When set to fennec, long press the home button to enter, it will focus on the address bar, which allows me to search quickly. When set to fenix, it only enters the application, I still need to click the address bar.

When I set it to other browsers, it behaves the same as fennec, focusing on the address bar, so I think focusing on the address bar is correct.

![fennec set to device assistance](https://user-images.githubusercontent.com/17559985/99771782-a3c06e80-2b44-11eb-8761-f0fc4bb2ceb2.gif)

**Comment by hakkikaancaliskan** [comment] 2020-11-20 09:19
Duplicate of #3722. There is a open pr for this.

**Comment by kbrosnan** [comment] 2020-12-02 23:57
Closing as a duplicate

**Closed by kbrosnan** 2020-12-02 23:57 UTC
Labels: needs:triage
