### ISSUE TITLE
Showing top sites when address box is empty

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#11296] opened 2020-06-06 10:16 UTC
### What is the user problem or growth opportunity you want to see solved?
The new tab overview (close to Fennec) is pretty good, but when I quickly want to switch to another top site I need to go to the Fenix home screen via opening a new tab.

### How do you know that this problem exists today? Why is this important?
I think that it'll be much easier if you can switch to the new site without opening a new tab.

The best option to realise it is via the address box. When the user is clicking on it and deletes is content by pressing the back button on the keyboard there is a lot space to show all top sites first.

### Who will benefit from it?
Everybody who is quickly navigating through top sites when no collection/routine is needed at that time.

**Comment by sheikh-azharuddin** [comment] 2020-06-06 10:34
> ### What is the user problem or growth opportunity you want to see solved?
> 
> The new tab overview (close to Fennec) is pretty good, but when I quickly want to switch to another top site I need to go to the Fenix home screen via opening a new tab.
> ### How do you know that this problem exists today? Why is this important?
> 
> I think that it'll be much easier if you can switch to the new site without opening a new tab.
> 
> The best option to realise it is via the address box. When the user is clicking on it and deletes is content by pressing the back button on the keyboard there is a lot space to show all top sites first.
> ### Who will benefit from it?
> 
> Everybody who is quickly navigating through top sites when no collection/routine is needed at that time.

Nice idea...a better option seems on clicking the address bar it shows a screen with address bar moves to the top and with message this time search with and then some search engines....instead of that they can show the top sites on that screen... Who changes search engine so frequently😅

**Comment by klint** [comment] 2020-06-06 23:39
The last proposal would allow the + button in the tab tray to more logically (IMHO) send the cursor to the address bar with the keyboard open, instead  of showing top sites and collections without focus on the address bar.

**Comment by yoasif** [comment] 2020-06-25 17:32
May be a dupe of https://github.com/mozilla-mobile/fenix/issues/10198

**Comment by Cheap-Skate** [comment] 2020-07-02 15:59
+1 for this idea

Currently the only way to access Top Sites is to open a new tab. That seems crazy to me. I really really want to be able to access Top Sites within my current tab, like I can on Fennec, Chrome, Samsung, etc etc.

I want to be able to
- "recycle" a tab (finished reading newspaper A, can switch to newspaper B in the same tab), or
- move back to the main page of a site when I get lost in its heirarchy (click through several articles on newspaperA.com, get lost, want to go back to newspaperA.com home page as quickly as possible)

On Fennec (and other browsers) these tasks require two taps. At the moment Fenix requires many taps and a lot of thought to find a workaround:- maybe open a new tab? or hunt through Bookmarks? or start typing the URL until the correct search/history suggestion appears? Grrrr

This seems to me like a horrible oversight, it's such an obvious thing which many (all?) other browsers allow me to do. But not Fenix.

You could do it by 
- this current proposal (tap URL bar) which would be like Fennec, or 
- by adding a Home icon to the URL bar, which would be like Chrome, or
- [other solutions?]

This is really starting to irritate me, I'm gravitating more and more to Samsung Internet. Nice browser, ad blockers, _can access Top Sites with a single tap_.

(I know @yoasif has made similar comments in various issues)

**Comment by Yves-Be** [comment] 2020-07-03 08:22
Also check https://github.com/mozilla-mobile/fenix/issues/9118, where a mock-up and the implementation of other browsers is discussed.

**Comment by Cheap-Skate** [comment] 2020-07-03 10:15
I thought some more, I think Mozilla has thrown the baby out with the bathwater.

IIRC the user feedback is that Fennec's about:home (the Awesomescreen) is too complicated. Fair enough. But Fenix's solution is _to deny access to about:home except when opening a new tab_. IMHO that's a crazy solution.

Fennec and (all?) competing browsers allow the user to go to about:home with a single tap, and interactions with about:home alter the contents of the current tab. That's really useful. But Fenix doesn't have it.

So IMHO Fenix needs to bring back about:home behavior which matches Fennec and all (?) other browsers, but Fenix needs a less complicated about:home page than Fennec.

I'm particularly interested in accessing Top Sites via about:home, but competing browsers have other stuff on about:home like Pocket, news feeds, recent history which I generally quite like too.

**Comment by tibitts** [comment] 2020-07-03 11:01
Why stop at only accessing Top Sites via about:home? Fennec gives easy and straight forward access to Top Sites, Bookmarks, and History via about:home. This would be the bare minimum which Fenix should support as well.
Why this isn't supported from day 1 in Fenix is beyond me.

**Comment by klint** [comment] 2020-07-03 11:38
We're not at Day 1 yet :)

**Comment by Cheap-Skate** [comment] 2020-07-03 16:08
> Why stop at only accessing Top Sites via about:home? 

I completely agree. I was just trying to identify two separate issues for me & I think many other commenters

1. I can't access Fenix's about:home in the way that I am used to, and
2. Fenix's about:home has been dumbed down compared to Fennec.

Issue (2) I can understand (although I am disappointed). If user feedback is Fennec's about:home was too complicated, then Fenix's should be simpler. Issue (1) I don't understand. Fenix is still missing a feature that is front-and-center on other browsers I use, mobile and desktop:- tap the URL bar or home icon; tap something on about:home (eg a Top Site); watch the new page load in the current tab.

**Comment by yoasif** [comment] 2020-08-28 06:47
Dupe of https://github.com/mozilla-mobile/fenix/issues/9118

**Comment by kbrosnan** [comment] 2020-08-28 15:56
Closing as a duplicate

**Closed by kbrosnan** 2020-08-28 15:56 UTC
Labels: Feature:Search, Feature:TopSites, feature request 🌟
