### ISSUE TITLE
FNX-3346 ⁃ Consider removing page title when Link Sharing because it breaks workflow with other apps

### ISSUE THREAD

**Issue by hookshot1** [mozilla-mobile/fenix#10193] opened 2020-04-24 14:32 UTC
recently got pushed from Firefox Beta -> preview.
I normally share links with termux, which has a link handler.

Unfortunately this update appears to break that, as sharing now also includes additional text [Title] [link], which causes it to not be recognized as a URL. 

would it be possible to 
A) revert back to plain link sharing? or
B) provide a setting to disable the extra text from being shared?

**Comment by liuche** [comment] 2020-06-02 17:48
We talked about this in triage and decided that we should strip out the title (since we'll send this anyway if it's an email). Will aim to do this for release bc it's small.

**Comment by liuche** [comment] 2020-06-02 17:48
@boek maybe another issue? should i just add these to the board 😅

**Comment by boek** [comment] 2020-06-03 06:05
@liuche yep, I'll add it! Maybe @person808 wants to take a crack at it tomorrow :)

**Comment by person808** [comment] 2020-06-05 15:32
Confirmed fixed in Nightly as of 6/5. Tested on Google Pixel 2 XL (Android 10)

**Comment by abodea** [comment] 2020-06-09 15:52
Verified as fixed on the latest Nightly build from 6/9 with Google Pixel 4 XL (10).
Note that the link is correctly shared now, for example in Gmail, only the link is displayed.

**Closed** 2020-08-10 19:36 UTC
Labels: Feature:Browsing, Feature:FennecTransition, eng:qa:verified, feature request 🌟
