### ISSUE TITLE
[Bug] Firefox Android 82.1.1 Build #2015770923 Won't Pop Keyboard on Input Fields after Couple Day Runtime

### ISSUE THREAD

**Issue by dmaas** [mozilla-mobile/fenix#16440] opened 2020-11-06 22:58 UTC
##  Steps to reproduce
1. Samsung Galaxy Note 10 (not +), Android 10, Version: N970U1UES5DTJ6 / N970U10YM5DTJ6 / N970U1UES5DTJ6, non-rooted, Firefox Android 82.1.1 (Build #2015770923) Wednesday 10/21 @ 5:28AM - but has been happening for ~6 months on previous Android and Firefox Android releases.
2. Load 10+ tabs with large pages, all with data entry fields
3. Keep phone on for 3+ days (no reboot, screen lock / standby only)
4. Navigate to https://support.mozilla.org/en-US/questions/new/mobile/form
5. Click into a data entry field on the page. 

### Expected behavior
Android on screen keyboard should pop-up. (Works in Chrome Android regardless of time device has been on.)

### Actual behavior
No keyboard pops-up.

### Device information
- Samsung Galaxy Note 10 (not +), Android 10, Version: N970U1UES5DTJ6 / N970U10YM5DTJ6 / N970U1UES5DTJ6, non-rooted, Firefox Android 82.1.1 (Build #2015770923) Wednesday 10/21 @ 5:28AM - but has been happening for ~6 months on previous Android and Firefox Android releases

### Tested Conditions
- Happens both in Private tabs and non-Private
- Happens after repeatedly reloading the page
- Happens after closing the tab and opening a new tab on the same page
- Happens after depressing away from the field until focus is lost and then clicking back into data entry field
- Happens after changing default keyboard between Samsung or Gboard
- Does not happen in Chrome Android under same conditions
- Resolved by fully rebooting device

### Non-Tested Conditions
- Killing and restarting Firefox process

### Hardware / Software Details
* Android device: Samsung Galaxy Note 10 (not +), Android 10, Version: N970U1UES5DTJ6 / N970U10YM5DTJ6 / N970U1UES5DTJ6, non-rooted
* Fenix version: Firefox Android 82.1.1 (Build #2015770923) Wednesday 10/21 @ 5:28AM - but has been happening for ~6 months on previous Android and Firefox Android releases

**Comment by valentas-kurauskas** [comment] 2020-11-12 07:45
I wanted to say I have the same problem, couldn't even type my login/password to github because of this bug.  Android 10, A415FXXU1ATJ1, Firefox 82.1.1 build #2015770923.

**Comment by ryanmobley** [comment] 2020-12-13 20:36
Same issue here. This issue is rare, but the keyboard completely stops popping up after selecting any input field within any website - existing tabs, new tabs. The keyboard still pops up for the URL box. I use Gboard, but switching to another keyboard while the problem was occurring did not fix it. Force stopping Firefox within Android settings and reopening it does fix this for me.

This is still occurring with Firefox 83.1.0 (Build #2015776403). Phone: Oneplus Six, Android 10, OxygenOS 10.3.7.

**Comment by metronightly** [comment] 2020-12-23 04:14
I have been facing the same issue on my Android 10 device on 3 of the Firefox browsers, Firefox Daylight 84.1.1, Firefox Beta 85.0.0-beta.3 and the last Firefox Nightly that I used- around Dec 8. I hope it's fixed soon.

**Comment by kbrosnan** [comment] 2021-01-04 18:07
Likely duplicate of #12982

**Closed by kbrosnan** 2021-01-04 18:07 UTC
Labels: Feature:IME, 🐞 bug
