### ISSUE TITLE
Allow not showing Mozilla shipped browser domains in autocomplete

### ISSUE THREAD

**Issue by vUksi** [mozilla-mobile/fenix#26145] opened 2022-07-22 14:08 UTC
### Steps to reproduce

1. Open new tab
2. Start writing url with the letter c
3. Url gets automatically filled to Craigslist.org

### Expected behaviour

Url should be filled with something relevant from history or bookmarks

### Actual behaviour

Every letter suggest something major site, most not in the history at all. 

### Device name

Huawei p30 pro 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

104.0a1 

### Additional information

Firefox (non nightly) still works correctly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21092)

**Comment by Mugurell** [comment] 2022-07-22 14:59
Hello @vUksi 
You can choose which type of suggestions to be presented with by going to `Settings -> Search -> Address bar` where you can enable or disable the providers you are interested in.


![image](https://user-images.githubusercontent.com/11428869/180467165-3141c719-bd43-4281-8b97-1e6ee0320c9a.png)

**Comment by vUksi** [comment] 2022-07-22 15:53
Doesn't help. Haven't changed settings and in previous version it worked.
![Screenshot_20220722_184914_org mozilla fenix](https://user-images.githubusercontent.com/6759969/180476687-a40d8a3b-e334-4609-a391-62467cba68a1.jpg)

History showing no entry of Craigslist
![Screenshot_20220722_184930_org mozilla fenix](https://user-images.githubusercontent.com/6759969/180476695-ad25359b-5115-415f-b03b-f143a96c5b2d.jpg)

Suggested Craigslist
![Screenshot_20220722_185156_org mozilla fenix_edit_69417417042532](https://user-images.githubusercontent.com/6759969/180476992-dc019773-eb44-4d08-819a-c4c9d269f366.jpg)

Sites include huffing post, Washington post, BBC news and lost of America centric sites,  not frequented in Europe.

**Comment by Mugurell** [comment] 2022-07-22 17:07
You have more providers than just history and bookmarks enabled.
In this case it's probably the "Autocomplete URLs" provider that is adding "craiglist.org".
The list of domains that can be autocompleted is available [here](https://github.com/mozilla-mobile/android-components/tree/main/components/browser/domains/src/main/assets/domains).

**Comment by vUksi** [comment] 2022-07-22 17:17
Same set of providers in Firefox (main) 
![Screenshot_20220722_200940_org mozilla firefox](https://user-images.githubusercontent.com/6759969/180490312-f00038c1-5880-4e84-b59a-c8db88d7ae8b.jpg)

URL completion works "correctly" 
![Screenshot_20220722_201036_org mozilla firefox_edit_72030371907238](https://user-images.githubusercontent.com/6759969/180490450-79cb3e65-25fd-4a37-8adc-22334020998b.jpg)

If I disable "autocomplete URLs" no url is completed, not from history or the random list of URLs. I want the URLs to autocomplete but with the relevant url from my history. 

Daylight version:

102.2.1 (Build #2015891003), 10fdf130c+
AC: 102.0.14, cd19f9a6c5
GV: 102.0.1-20220705093820
AS: 93.1.0

**Comment by cadeyrn** [comment] 2022-07-24 12:19
@Mugurell 

> You have more providers than just history and bookmarks enabled.
> In this case it's probably the "Autocomplete URLs" provider that is adding "craiglist.org".
> The list of domains that can be autocompleted is available [here](https://github.com/mozilla-mobile/android-components/tree/main/components/browser/domains/src/main/assets/domains).

There was never an option in Fenix to disable the autocompletion of domains from this list. The option to disable the autocomplete of URLs disables *every* kind of domain autocomplete. So you can't disable the autocomplete from domains from this list but keep the autocomplete for websites you visited.

**Comment by Mugurell** [comment] 2022-07-25 06:42
Thank you @cadeyrn and @vUksi, indeed only looked at this as an bug resolved with disabling autocompletion altogether.
If the desire is to keep autocompletion but without the Mozilla curated domains list then we can migrate this to a feature request.

**Comment by nvllsvm** [comment] 2022-08-23 04:16
Is there an about:config setting for disabling the built-in advertisements for sites that are not in my history?

I like having URLs from my history autocomplete, but not for anything else.

**Comment by cadeyrn** [comment] 2022-08-23 07:45
No, there is no about:config setting. And about:config wouldn't be a solution since there is no about:config in stable releases of Firefox for Android.

> built-in advertisements

That's no "advertising". That would mean that they are paid for it. And then it would have to be marked as advertising. It's a "comfort feature" to get users faster to the most popular websites.

**Comment by nvllsvm** [comment] 2022-08-23 11:54
> there is no about:config in stable releases of Firefox for Android.

The suggestions are annoying enough that I'm willing to switch to the nightlies where about:config is still enabled.

> That's no "advertisement".

I actually thought for a bit about whether advertisement was the correct word before I submitted my comment. In-spite of no one getting paid for showing these sites, I stand by my use of the word. Some of the sites suggested are for paid-only products (netflix.com) that I would never use. The suggested sites are largely irrelevant to me and sometimes result in me accidentally navigating to them because of seeing the autocomplete bar light up (I'm kind of clumsy).

I have the "Show search suggestions" toggle disabled, yet these are still suggested. From my perspective as an individual user, these are functionally equivalent to advertisements - regardless of whether Mozilla is being paid.

**Comment by djl** [comment] 2022-08-23 12:15
> It's a "comfort feature" to get users faster to the most popular websites.

For a not-insignificant number of users - myself included - this is not a comfort feature. Almost all of the suggested sites are only useful in the US or North America. Surely my own browser history should take precedence over anything else?

Netflix I can kind of see the need for, but Oracle and Lowes? I can't imagine either of those being visited enough to warrant being suggested to users. But if they are, again, the user's own browser history would already suggest these.

(I'm aware that arguing about this is off-topic and pointless and I'm not helping. Sorry! :smile:)

**Comment by cadeyrn** [comment] 2022-08-23 13:14
@nvllsvm

> The suggestions are annoying enough that I'm willing to switch to the nightlies where about:config is still enabled.

That's fine. But still it wouldn't be a solution, only a workaround for a small part of the users. The result of this feature request should be user visible option. And since about:config isn't used on Android to control user visible things at all, an option in about:config won't happen anyway.

> I stand by my use of the word

Well, you can call it whatever you want, but then it's wrong. And in public discussions it's not helpful to use wrong terms. In the worst case it confuses other people.

> Some of the sites suggested are for paid-only products (netflix.com) that I would never use. 

The term advertisement is not defined by the fact if _you_ would use it or of it's a commercial site or not. Firefox suggests popular websites according to a top list.

> The suggested sites are largely irrelevant to me and sometimes result in me accidentally navigating to them because of seeing the autocomplete bar light up (I'm kind of clumsy).

I don't think anyone has argued against that. You have a valid case and that's why this feature request exists. I also support this feature request. 😉

@djl:

> For a not-insignificant number of users - myself included - this is not a comfort feature.

I only explained what the feature is - and what not. Of course it's not useful for every user - as every feature.

> Almost all of the suggested sites are only useful in the US or North America. 

I didn't check all the links. But there are also regional lists. There is also a list for Germany or France (in Europe), for example. See the link above. But yes, I am sure that these lists contain much more websites than are useful _for you_. 

> Surely my own browser history should take precedence over anything else?

I just tested it. The browser history _does_ take precedence.

> But if they are, again, the user's own browser history would already suggest these.

Sure - once they visited the website. The point of this feature is to have domain suggestions _before_ the user vitisited the website.

**Comment by djl** [comment] 2022-08-23 13:43
> I just tested it. The browser history does take precedence.

Maybe I'm running into a different bug because this isn't true for me on both Nightly (my daily driver) or the stable build.

Here's a small sample of what I type, what gets autocompleted and what I expect.

```
| Type | Result         | Expected                          |
|-----------------------------------------------------------|
| `a`  | amazon.com     | amazon.co.uk                      |
| `b`  | bing.com       | bbc.co.uk                         |
| `c`  | craigslist.org | (redacted url beginning with `c`) |
| `d`  | diply.com      | discogs.com                       |
| `l`  | lowes.com      | lobste.rs                         |
| `n`  | netflix.com    | news.ycombinator.com              |
| `o`  | office.com     | (redacted url beginning with `o`) |
| `p`  | pinterest.com  | (redacted url beginning with `p`) |
```

In 100% of these cases, I've never visited any of the URLs being autocompleted. My own browing history is never autocompleted.

Could this be a completely different bug or is this expected?

**Comment by vUksi** [comment] 2022-08-25 06:34
My experience matches with @djl and to me this is still a bug as it used to work before nightly version 104.0a1 as expected.

For example to get a match from history for site starting with b I have to fill it almost completely before the history matching starts working (for other sites it works better but this site is a pain)

b       -> bing.com
bb      -> bbc.com
bbs     -> no match
bbs.    -> no match
bbs.i   -> no match
bbs.io  -> bbs.io-tech.fi <- finally a wanted match    

Actually just tested the non-nightly version again and I get my history over these random sites as expected.

**Comment by Wack0** [comment] 2022-08-27 10:41
Seems this has made it into a stable version (104.1.0). I've disabled URL autocomplete entirely now as it's completely useless to me.
I can understand suggested sites being used in an initial install for example but not overriding results from browser history. (For example, when I type `x` it previously autocompleted xkcd, and now autocompletes a certain ISP in the USA, a country which I do not reside in)

**Comment by aphedges** [comment] 2022-08-27 13:36
To add some more information, it started for me using stable 104 as well. However, it seems to fail intermittently. Sometimes, typing `ph` is enough for it to suggest `phoronix.com`, but other times, I need to type out the entire URL. How much I need to type and whether I can get a suggestion at all differs from minute to minute. I have seen similar problems with `lwn.net`, `cbr.com`, and many other websites that it suggested when I was using 103.

Another thing to note is that URL autocomplete seems to come from bookmarks as well. I tried it after the update on a device without any of these sites in history, but presumably because they are bookmarked, they show up in the autocomplete.

**Comment by nvllsvm** [comment] 2022-08-27 13:50
So this all is looking like two distinct issues:
- unvisited URLs are taking precedence over history and bookmarks
- suggested URLs are displaying when the "Show search suggestions" toggle is disabled

**Comment by notartom** [comment] 2022-08-27 23:56
Given that:

* This was not happening before
* Has started happening with this new version (presumably 104.1.0 Build #2015898515, which is what I'm running now)
* The UX is actively hostile to at least some users who don't want random "major" sites taking autocomplete precedence over their own history

I'd consider this a regression and a bug, and not a feature request.

**Comment by NoraCodes** [comment] 2022-08-28 02:55
Hi! I'd also like to chime in and say, whether or not it's a bug, it's certainly a regression in functionality. I love Firefox, and I use it everywhere, but this is honestly annoying enough to make me consider switching away from it. Some examples:

- Typing "ne<go>" used to get me to HackerNews, now it sends me to Netflix. I do not have a Netflix account.
- Typing "m<go>" used to send me to YouTube - "m.youtube.com". It now sends me to Microsoft. I have never owned a Microsoft product.

This is really over the top. Please don't break things without notice and then deprioritize fixing them!

**Comment by Mugurell** [comment] 2022-08-29 12:07
Thank you all for the reports!
Seems like there are few different scenarios being discussed here:
- the domains autocomplete feature from the initial report - `Every letter suggest something major site, most not in the history at all.`
    - this is currently the expected scenario and is a feature that exists from the first versions of the app
    - a matching website from a list of the most visited websites should be autocompleted only if there is no matching history
    - currently cannot be disabled without disabling autocomplete altogether. That's why this issue was migrated to a feature request.
- the autocomplete feature not using results from history, issue seen in the recent reports - `Typing "ne" used to get me to HackerNews, now it sends me to Netflix.` 
    - if there are matching history entries but are not autocompleted then this is a bug. 
    - based on the recent reports it seems indeed that there is a regression introduced in 104.
    - opened https://github.com/mozilla-mobile/fenix/issues/26687 to specifically talk about and investigate this bug.

**Comment by boek** [comment] 2023-01-30 21:33
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813800

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-30 21:33 UTC
Labels: feature request 🌟, needs:triage
