### ISSUE TITLE
Disable dynamic address bar

### ISSUE THREAD

**Issue by flatulation** [mozilla-mobile/fenix#11948] opened 2020-06-25 13:12 UTC
### What is the user problem or growth opportunity you want to see solved?
I would like to be able to disable the dynamic (hiding) address bar introduced in #8775.

### How do you know that this problem exists today? Why is this important?
The disappearing address bar is disorienting to me because it changes the bottom edge of the viewport, which is typically where my eyes are looking when scrolling. As well, it hides the most important parts of the browser chrome especially the hamburger menu, which may be fine when it is in the upper quarter of the screen like most other apps, but confusing when it is at the bottom and it disappears.

### Who will benefit from it?
Anyone who dislikes the new dynamic address bar at the bottom which was released in preview 5.2.

While I still have all the time in the world on my hands I am prepared to implement this myself.

**Comment by cadeyrn** [comment] 2020-06-25 13:14
Duplicate of #10240.

**Comment by kbrosnan** [comment] 2020-08-28 21:09
Closing as a duplicate

**Closed by kbrosnan** 2020-08-28 21:09 UTC
Labels: needs:triage
