### ISSUE TITLE
[Bug]Auto play video doesn't work after revisiting the website the second time

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4002] opened 2019-07-11 14:38 UTC
## Steps to reproduce
1. Navigate to https://www.bmw.com/en/innovation/the-development-of-self-driving-cars.html
2. Check if the video starts to play
3. Close the page
4. Revisit the above mentioned page

### Expected behavior
Video should start playing each time the user opens the web page

### Actual behavior
On the 1st attempt the video starts to play as soon as the page is loaded.
On the 2nd attempt the video isn't playing.

### Device information

* Android device: 
• Google Pixel 3A (Android 9)
• OnePlus6T (Android 9)
• Samsung Galaxy S8+ (Android 8)
• Samsung Galaxy S7 (Android 7)
• Samsung Galaxy S6 (Android 6.0.1)

* Fenix version: Latest build from master

### Notes
[► Video from OnePlus6T ](https://drive.google.com/open?id=1YMiWlzGt3oZZKAv6EKLqFFVpPu7dJ19m)

**Comment by ekager** [comment] 2019-09-20 22:40
We have just added a toggle for media autoplay so maybe we should retest with the toggle on #255

**Comment by AndiAJ** [comment] 2019-09-23 08:56
Hi @ekager , I've checked on Nightly build #12651809 from 22/9  and noticed a couple of issues using the following devices: 
• Google Pixel 3a (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

1. Video and audio blocked
The video playback still starts on the first attempt.
When re-visiting the page the playback doesn't start until I swipe up and down

![20190923_112608](https://user-images.githubusercontent.com/51314259/65413015-1dea4b80-ddf9-11e9-9416-b8d14811097f.gif)


2. Video and audio allowed
When re-visiting the page the playback doesn't start until I swipe up and down
![20190923_113009](https://user-images.githubusercontent.com/51314259/65412714-7a00a000-ddf8-11e9-82ff-c1ef4b2bad14.gif)


I'll do more testing in regards with the autoplay toggle, on the other hand I don't know how to proceed with the above described issue.
From my point of view on the 2nd attempt the video playback should start without any other actions.


Note: I've tried also disabling the tracking protection. but still the video playback doesn't start immediately after revisiting the webpage

**Comment by sv-ohorvath** [comment] 2019-09-30 09:12
Can confirm this bug is still happening with the Autoplay toggle, on the RC 2.1.0 build.

**Comment by sblatz** [comment] 2019-09-30 15:46
@cpeterso Are you aware of any GV bug surrounding this?

**Comment by colintheshots** [comment] 2019-09-30 16:53
I opened a Bugzilla bug for this against GeckoView. https://bugzilla.mozilla.org/show_bug.cgi?id=1585045

**Comment by vesta0** [comment] 2019-09-30 17:00
@lime124 it would be great to have UX feedback on the desired behaviour for the 2 scenarios listed by QA above.

**Comment by cpeterso** [comment] 2019-09-30 21:51
> I opened a Bugzilla bug for this against GeckoView. https://bugzilla.mozilla.org/show_bug.cgi?id=1585045

IIUC, this bug sounds like the opposite of GV bug 1585045 and #5636. Those bugs are about videos auto-playing when they shouldn't and this bug is about a video _not_ playing when it should. Is that correct?

**Comment by sv-ohorvath** [comment] 2019-10-01 07:48
> IIUC, this bug sounds like the opposite of GV bug 1585045 and #5636. Those bugs are about videos auto-playing when they shouldn't and this bug is about a video _not_ playing when it should. Is that correct?

Yes, that's how we should treat them.

**Comment by brampitoyo** [comment] 2019-10-02 03:59
@vesta0 The behaviour should be:

1. If video and audio blocked
    * On first attempt, playback should not start at all
    * On revisit, playback should not start at all

2. If video and audio allowed
    * On first attempt, playback should start immediately
    * On revisit, playback should start immediately

**Comment by sblatz** [comment] 2019-10-10 15:58
I'm confused--doesn't this need GV work?

**Comment by cpeterso** [comment] 2019-10-10 18:08
The GV bug was closed as WORKSFORME with this comment: https://bugzilla.mozilla.org/show_bug.cgi?id=1585045#c3

> We do allow muted video to autoplay, if user want to block muted video as well, they can set the pref "[media.autoplay.default](https://bugzilla.mozilla.org/show_bug.cgi?id=1585045#c3
)=5". As the [BMW website](https://www.bmw.com/en/innovation/the-development-of-self-driving-cars.html) plays muted video, so it won't be blocked. Our current setting is to block audible autoplay media, but changing the value of the pref to 5 can block all media.

If GV's media APIs don't allow Fenix to change the media.autoplay pref, then we can file a new GV bug to extend the API.

**Comment by fluffyemily** [comment] 2020-06-02 13:20
Do we need to create a new GV bug for this, as the current Gecko bug that is being waited on was closed 8 months ago. See @cpeterso's [comment](https://github.com/mozilla-mobile/fenix/issues/4002#issuecomment-540705520)

**Comment by Amejia481** [comment] 2020-06-02 15:17
I think we should take a look to see, where the source of the issue is originated and then decide if a new bug it is needed :)

**Comment by ekager** [comment] 2020-06-23 02:41
Looking at this issue again, this BMW video is strange because even when I have autoplay set to allow (on wifi), it won't play for me.

**Comment by ekager** [comment] 2020-06-23 02:47
Similar to https://github.com/mozilla-mobile/fenix/issues/8678 even when Fenix autoplay is allowed, video will not play.

**Comment by ekager** [comment] 2020-06-23 16:52
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1647779

**Comment by amedyne** [comment] 2020-07-23 20:15
See GV  [Bug 1621825 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1621825)

**Closed** 2021-02-11 21:32 UTC
Labels: P2, eng:ready, needs:gv, wontfix, 🐞 bug
