### ISSUE TITLE
[Bug]new setting scroll to hide toolbar not working for bottom bar 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#14944] opened 2020-09-10 13:05 UTC
as in the title []new setting scroll to hide toolbar not working for bottom bar is this normal  ?

**Comment by hwinnemoe** [comment] 2020-09-10 13:07
Duplicate of #14902

**Comment by Mugurell** [comment] 2020-09-11 05:42
Indeed, an issues that should be fixed in the next Nightly.

**Closed by Mugurell** 2020-09-11 05:42 UTC
Labels: 🐞 bug
