### ISSUE TITLE
[Bug] Unable to initiate successive searches on selected text until next search

### ISSUE THREAD

**Issue by Yetoo1** [mozilla-mobile/fenix#18565] opened 2021-03-20 11:52 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to a page with text.
2. Select some text (select a word to make it easier)
3. Long press the text selected
4. Press search in the context menu that comes up
5. In the new tab that opens due to the search find and select the same exact text (to the character) that was searched (As a tip, the text initially searched should usually be in the search engine text entry so select that for this step)
6. Do steps 3-4. 
7. Notice how search doesn't work.
8. Refresh page
9. Find and select same exact text (to the character) 
10. Do steps 3-4
11. Notice how search doesn't work.
12. Switch to the first tab that the search of this text was initiated in or go to another tab that has this exact text in it
13. Find and select same exact text (to the character)
14. Do steps 3-4
15. Notice how search doesn't work.
### Expected behavior
Search should have work at steps 7, 11, and 15.
### Actual behavior
Search doesn't work at steps 7, 11, and 15.

### Device information

* Device vendor / model and Android version: Vendor: Samsung; Model: Galaxy J3 SM-J337V; Android version: 9
* Firefox for Android version: ? (go to Settings -> About Firefox)
Nightly 210319 20:42 (Build #2015799649)
86.1.1 (Build #2015794881)

Please note that the text to be searched doesn't need to be in the same location on the page for this to work. If there are duplicates of a word on a page and each of them are attempted to be selected and searched after an initial search of that word, this issue still occurs. I started experiencing this after the big update to 79 or at least shortly after 80. This issue is very annoying when needing to re-search a term after impulsively or accidentally closing the tab with the search result.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10096)

**Comment by Mugurell** [comment] 2021-03-22 07:53
Thank you @Yetoo1 for describing the issue with so many details!
I'm not sure though what the expected behavior should be.

If nothing changed in the search terms, why should we make a new search?
We have this 2 situations:
-  the user would search for "mozilla" and then on that page she would  search again for "mozilla".
The search option is shown but tapping it does nothing since the search terms for that page have not changed.
- user searched for "mozilla firefox" and then from that page he would've searched for "mozilla" or "firefox".
The search option is shown and tapping it will result in a new search being performed because the search terms have changed.

Asking UX if we'd better not show the "Search" option in the contextual menu if the selected text to base the search on is exactly the same text as for the current search.

**Comment by Mugurell** [comment] 2021-03-22 07:54
As to why this currently happens - we explicitly filter duplicated search requests - https://github.com/mozilla-mobile/android-components/blob/b266ac3d16e15cabc969cfe33c9cf965f557e257/components/feature/search/src/main/java/mozilla/components/feature/search/SearchFeature.kt#L48

**Comment by Yetoo1** [comment] 2021-03-22 10:39
> Thank you @Yetoo1 for describing the issue with so many details!
> I'm not sure though what the expected behavior should be.
> 
> If nothing changed in the search terms, why should we make a new search?
> We have this 2 situations:
> 
>     * the user would search for "mozilla" and then on that page she would  search again for "mozilla".
>       The search option is shown but tapping it does nothing since the search terms for that page have not changed.
> 
>     * user searched for "mozilla firefox" and then from that page he would've searched for "mozilla" or "firefox".
>       The search option is shown and tapping it will result in a new search being performed because the search terms have changed.
> 
> 
> Asking UX if we'd better not show the "Search" option in the contextual menu if the selected text to base the search on is exactly the same text as for the current search.

The expected behavior is that the browser ui isn't going to change because the search page has a special status and gets to change what I can search for. The ui should always allow me to search for what I want when I want and if it's going to change it should only add functionality in relation to the selected content (as distinct from website/page) rather than remove it.

No, we have three situations:
1. The user would search for "mozilla" on an article/website/not-search-page and then on the subsequent search page the user wants to search again for "mozilla".
2. The user would search for "mozilla" and then **accidentally or impulsively** hits the android back button (or browser back) which necessarily (at least currently) closes the search tab and goes back to the article/website/not-search-page and then the user happens to want to search again for "mozilla".
3. The user would search for "mozilla" and then **purposely** hits the android back button (or browser back) which necessarily (at least currently) closes the search tab and goes back to the article/website/not-search-page but then finds another occurrence of "mozilla" in the article/website/not-search-page which happens to be the same exact case and spelling with no difference to "mozilla" in the first search and then the user wants to search "mozilla" again because the user forgot the definition because of bad memory or goldfish attention span. 

I think the second scenario you put forward isn't applicable here because "mozilla firefox" is completely different substance as a search term than "mozilla" and is out of the context to the idea of "same exact text (to the character) that was searched".

>The search option is shown but tapping it does nothing since the search terms for that page have not changed.

I find that type of behavior totally antithetical to the rest of firefox or firefox mobile ui behavior when it comes to ui buttons on any page because consistently, at least to me, since there is no on-going action or functionality missing from the default context menu (such as refresh page turning to an X to stop the page load or a context menu adding "Open link in new tab" as an option when right clicking/long tapping a link). I thought the ui was supposed only be cognizant to the content only as to add functionality because the role of the ui is to do what the user wishes rather than remove the choices that they are able to do. If the current behavior is the expected behavior and this reasoning can't convince you then the search button should disappear when on the same search page and nowhere else, but I don't know how you are going to keep track of that for the specific use case of just disappearing on search pages with custom search pages (yes, you could just ignore user wishes and disable search context menu option regardless of page simply because it is a duplicate, but that's not what you put forward). Plus that doesn't solve the issue of searching for the same exact term when going back to a page, closing the search page, and wanting to search for the term again. But I dislike even indulging that possibility because it goes in the face of KISS and this needlessly complicates the code. Because of that I would really prefer this intended "feature" to be discarded rather than indulged.

**Comment by Yetoo1** [comment] 2021-04-06 07:01
I created a PR to remove the duplicate filtering here https://github.com/mozilla-mobile/android-components/pull/10022. This may need a test, but I'm having a hard time figuring out how to get Mockito to duplicate a search request without complaining about discrepancies regarding wanted number of invocations. If someone as pointers to get Mockito to test a specific sequence multiple times so as to simulate duplicating a search, that would be great.

**Comment by Mugurell** [comment] 2021-04-06 10:59
@Yetoo1 I understand this issue is important for you but let's wait until we hear from UX what should be the expected behavior.
I'd say instead of making another search for the same search item that would give exactly the same results
We should better not show the search option for the same exact search term.
But again this is a decision for the UX team.

**Comment by Yetoo1** [comment] 2021-04-06 11:18
@Mugurell Ok. But, just to clarify if one were to search a word on a page of text, get sent to the search page with result, then goes back to that page of text to then select that same word in a different part of that page of text, your proposal would mean that the search option would not appear for that selection despite that word being a totally different set of characters (albeit same configuration) and could (I think likely) lead to confusion. 

Also, I forgot to mention that a workflow of mine includes using the search feature as a faster way of opening tabs and that workflow being interrupted due to the word not being searchable because it's considered already searched due to already existing as a search request in the browserstore is irritating. 

I understand you don't make these decisions, but I want to make sure the UX team has a good amount of perspective to read from before coming to a decision.

**Comment by Rodze** [comment] 2021-04-21 16:38
UX team just needs to see the current behavior of Firefox mobile doesn't happen anywhere because the current behavior is a bug.

If one searched for the same word twice either of the two should happen: 

1) always open a new tab with the search even if it's the nth repeated time; 

2) open a new tab or go to an open tab with the same exact search if it's still open.

Not doing anything (as it is now) or not showing the search option (as it has been proposed) doesn't make sense because the user has no idea what's happening and doesn't receive any feedback why.

**Comment by Yetoo1** [comment] 2022-04-07 00:23
This is still an issue.

**Comment by marcel263** [comment] 2022-06-22 12:23
If the behavior is to filter duplicate search results, why does this even manage to be reproducoble after closing the original search tab while attempting to open it again? What does filtering have to do with that? 
The search should not linger around in the application. This alone is enough to call it a bug not a choice by design.

**Comment by Alexandru2909** [comment] 2022-06-29 13:40
Fixed in [25047](https://github.com/mozilla-mobile/fenix/issues/25047).

**Closed** 2022-06-30 06:49 UTC
Labels: 🐞 bug, needs:UX-feedback, Feature:Search, Feature:Toolbar
