### ISSUE TITLE
[Bug]: Password manager does not register the password for Twitter

### ISSUE THREAD

**Issue by Iey4iej3** [mozilla-mobile/fenix#21486] opened 2021-09-23 20:11 UTC
### Steps to reproduce

1. Visit twitter.com
2. Choose "Log in"
3. Input the email address
4. Input the password

### Expected behaviour

There should be a prompt to save the password.

### Actual behaviour

No prompt is popped up

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

92.1.1

### Additional information

Closely related to the desktop version: https://bugzilla.mozilla.org/show_bug.cgi?id=1629912

**Comment by SoftVision-LorandJanos** [comment] 2021-09-24 10:20
Hi @Iey4iej3 ! Thank you for your report!
I can confirm that on the latest Release (92.1.1) this issue is reproducible.
Also checked on the latest Beta (93.0.0-beta4) where I could reproduce it as well.
However on the latest Nightly build (94.0a1 - 2021-09-24T05:10:09.860159) the issue is not reproducible.

Please check if you can reproduce the issue on the latest Nightly.

Since this issue should be covered by this ticket: #21379, I will close this one as duplicate. Please leave a comment there regarding any useful details about this issue.

Devices used for testing:
- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Mi11 Lite (Android 11).

**Comment by Iey4iej3** [comment] 2021-09-24 12:23
Sorry, that issue is quite different from this one: that one is about Firefox being an autofill app to fill the passwords for *other apps*, while this one is specific about an internal password filling (I don't even know this functionality, but I have no Google apps, which are proprietary). I, however, link the issue to a report for Firefox desktop. I don't know whether the password managers on the desktop and on the Android are the same.

**Comment by SoftVision-LorandJanos** [comment] 2021-09-24 14:33
Please see if you reproduce it in the latest Nightly, I couldn't reproduce it there, and that usually means that it will get to Release version. So it will be fixed there as well. Most probably by version 94.

**Comment by Iey4iej3** [comment] 2021-09-25 22:15
I *can* reproduce the issue in the nightly build `94.0a1(Build #2015836107)` (the last line is `2021-09-25T17:45:09.508697`). I run Firefox under Lineage OS 18.1. By the way, I also reproduced the issue in the latest Firefox Desktop. I will report it as soon as possible.

**Comment by SoftVision-LorandJanos** [comment] 2021-09-27 10:16
Based on the last comment, I will reopen this issue, but please share your device information. Thanks!

**Comment by Iey4iej3** [comment] 2021-09-27 10:57
I have modified, but I tend to believe that it is more OS-specific than device specific, if that matters.

**Comment by SoftVision-LorandJanos** [comment] 2021-09-27 11:00
I did verify with Android 11 and I couldn't reproduce it on nightly, that's why I thought it could be device specific.

**Comment by Iey4iej3** [comment] 2021-09-27 11:02
But maybe you tested it on MIUI?

**Comment by SoftVision-LorandJanos** [comment] 2022-03-28 05:42
This issue is no longer reproducible with the latest Nightly 100.0a1 (2022-03-28) build.
The prompt is displayed after signing in, as expected.
Device used: Oppo Reno 6 (Android 12).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-03-28 05:42 UTC
Labels: 🐞 bug, S3, Feature:Logins, needs:triage, wontfix, qa-triaged
