### ISSUE TITLE
[Bug]Tab Tray: [a11y] -Number of listed items and item in list not read properly

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11879] opened 2020-06-24 09:38 UTC
## Prerequisites
Have 3 open Tabs

## Steps to reproduce
1. Open the Tabs Tray
1. Tap on by one on the listed tabs

### Expected behavior
"1 of 3 in list of 3 items"
"2 of 3 in list of 3 items"
"3 of 3 in list of 3 items"

### Actual behavior
The number of listed items and item in list isn't read

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build 200624 from 6/24

## Notes
:heavy_check_mark: Isn't caused by @mcarare 's PR #11636 as it it reproducible on the Nightly builds from both the 19th and 22nd

► Video
![20200624-122431-online-video-cut](https://user-images.githubusercontent.com/51314259/85531389-64ced100-b617-11ea-81c9-bc00cc171e07.gif)

**Comment by BranescuMihai** [comment] 2020-07-22 17:44
Pulled this into sprint because I thought I had the OnePlus 3, turns out I can't find it, so I'll put it back into backlog

**Comment by Mugurell** [comment] 2020-07-28 07:57
@AndiAJ does this seem like a device specific issue?
It is reproducing on other devices?

**Comment by mcarare** [comment] 2020-09-10 06:18
Reopened for QA

**Comment by AndiAJ** [comment] 2020-09-16 11:32
Hi, it's **still reproducible** on the latest Nightly 200916 using a OnePlus A3 (Android 6.0.1)

**Comment by codrut-topliceanu** [comment] 2020-11-10 13:27
I've investigated this issue using _OnePlus6 (Android 9), Pixel 3XL (Android 10) and Pixel 4 (Android 11)._

**Initial condition : Have several tabs already open and be in a tab/webpage**
### On the Pixel 3XL (Android 10), no google services updates
 - After pressing tab counter to open tab tray, Talkback reads:
    - "...com , in list 10 items"
 - After tapping on another tab item in the tab tray, Talkback reads:
    - "...com"

### On the Pixel 4 (Android 11) and OnePlus6 (Android 9)
 - After pressing tab counter to open tab tray, Talkback reads:
    - "...com , 5 of 10 , in list 10 items"
 - After tapping on another tab item in the tab tray, Talkback reads:
    - "...com , 6 of 10"

### On the Pixel 3XL (Android 10) device AFTER updating all google services and apps:
 - After pressing tab counter to open tab tray, Talkback reads:
    - "...com , 5 of 10 , in list 10 items"
 - After tapping on another tab item in the tab tray, Talkback reads:
    - "...com , 6 of 10"

### Google Play : On the Pixel 3XL (Android 10) device AFTER updating all google services and apps:
 - In Google Play store -> any tab -> Tap on any list:
    -"...reddit...  *in list 20 items*"
 - Without leaving that screen -> tap away from list -> tap back to the same list:
     - " ...reddit..."

### Conclusions:
1. The accessibility description "5 of 10" items is a relatively recent addition to the Talkback app, and it is something that Fenix relays to Talkback.
2. The part that says "..in list 10 items" is only stated when first focusing a listview, as design by Talkback.

Considering all of the above it is my conclusion that there is no [a11y] bug regarding this in Fenix and _the mentioned behaviour is intended_ by Talkback developers.

**Comment by ebalazs-sv** [comment] 2020-11-11 09:32
This issue is reproducible on the latest Nightly 201111 05:01 (Build #2015774955) GV 84 from 11/11 with Nexus 5 (Android 6.0.1).
I will remove the qa:needed label.

**Comment by sflorean** [comment] 2020-11-11 14:20
Based on the comments above, (this new behavior is intended by Talkback) I will close this issue.

**Closed by sflorean** 2020-11-11 14:20 UTC
Labels: E2, Feature:Tabs, P1, S2, b:a11y, eng:qa:verified, hershey, 🐞 bug
