### ISSUE TITLE
Fennec migration: Default browser state is not saved after migration on Huawei device

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#8631] opened 2020-01-27 10:14 UTC
STR:
1. Make sure to have another browser installed, e.g. Chrome.
2. Set Fennec as default browser.
3. Update Fennec to Fenix from Gplay, or through adb.
4. Check the default browser setting.

Expected results:
The Firefox nightly app is still the default browser.

Actual result:
Default browser is reset and changed to the other installed app (Chrome).

Device: Huawei P20 lite (Android 9), Huawei Mate 20 Lite (Android 8.1.0)
*not reproducing on other types of OS's.
Build: Fennec Nightly migration build 5

**Comment by Mugurell** [comment] 2020-02-21 10:57
This was a rabbit hole but I think I managed to track and find the root causes.
Basically we would need to 
- persist the same Fennec component to handle http/s schemas - `org.mozilla.gecko.BrowserApp` so that after migration the same already set as default activity would exist in our application
- use `PackageManager.MATCH_DEFAULT_ONLY` in our own `packageManager.resolveActivity` (a-c) check for default apps to avoid the default apps status being lost.

**Comment by Mugurell** [comment] 2020-02-24 14:50
After looking into this more I managed to maintain the default status for the app using the `http/s` intent-filter for [Fenix's .App activity-alias](https://github.com/mozilla-mobile/fenix/blob/fdd3d29cd40190a1c9dd0c6bb1a8707645701e3b/app/src/main/AndroidManifest.xml#L40) similar to how this intent-filter is set for [Fennec's .App activity-alias](https://dxr.mozilla.org/mozilla-esr68/rev/3b3ba2c7342ffdfd31d71c907805de000e9a6b02/mobile/android/base/AndroidManifest.xml.in#72).
(This was based upon seeing in logs
> I/PackageManager: Adding preferred activity org.mozilla.firefox_beta/.App for user 0

when setting Fennec as the default browser)

[video showing the update process and the default status kept](https://drive.google.com/open?id=1F23pUt_QHf-zyHT9Jtwy7f20125fIdjv)

&#8205;

The bad news is though that in Fennec that `.App` is an alias for [LauncherActivity](https://dxr.mozilla.org/mozilla-esr68/rev/3b3ba2c7342ffdfd31d71c907805de000e9a6b02/mobile/android/base/java/org/mozilla/gecko/LauncherActivity.java) which more or less serves as [Fenix's IntentReceiverActivity](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt).
and in Fenix the `.App` is an alias for [HomeActivity](https://github.com/mozilla-mobile/fenix/blob/fdd3d29cd40190a1c9dd0c6bb1a8707645701e3b/app/src/main/java/org/mozilla/fenix/HomeActivity.kt) which doesn't know how to handle url Intents and I'm not sure it should know about this.

@pocmo Do you have any suggestions for a workaround here?

**Comment by pocmo** [comment] 2020-02-24 16:03
> and in Fenix the .App is an alias for HomeActivity which doesn't know how to handle url Intents and I'm not sure it should know about this.

Could we make `.App` an alias for `IntentReceiverAcivity`? Would that fix the problem? As long as we haven't shipped this to beta/release we can still change that and potentially break things for nightly - if we know the trade-offs.

**Comment by Mugurell** [comment] 2020-02-25 10:07
Thank you Sebastian. I think that would work for my above reasoning.

In the meantime @sv-ohorvath and @ebalazs-sv helped test my proposed solution and on their Huawei devices the issue still reproduces.
So it seems that there is no one issue for all Huawei devices, but multiple different issues.
We'll work together on having one of their devices shipped to me so I can continue debugging on that.

**Comment by Mugurell** [comment] 2020-02-27 18:01
Received a Huawei Honor 8 (FRD-L09) with Android 7.0 from Oana

In my tests I saw the default browser status behaving apparently random with it clearly not being stable enough to even hope to find scenarios on which to base my investigation and fixes - [video](https://drive.google.com/file/d/1Sg7BuZyM1pSUdt0skfY3w279Cpbn-h_E/view?usp=sharing)

What I saw though was that with the fix I talked about above the default browser is kept in settings after the update from Fennec to Fenix
But indeed the first time trying to open an external link we get the app picker.
This behavior though is seen also for the update of the Opera browser - [video](https://drive.google.com/file/d/1xchxcR1mvxSuyCnlSVK3LbJGkRuS-AoV/view?usp=sharing)

Related to the above situations I saw that on this device Fennec's default browser status was never remembered [video](https://drive.google.com/file/d/16YpysOidG24Bp_in5Ohd_FkyUOPEHfzB/view?usp=sharing) so already all Firefox users would have been affected by this issue.

Based on this I think there is nothing more that we can do for this particular device,
and based on the fact that my proposed fix actually fixed the issue on my Huawei Honor 5X  and Oana's Huawei P20 I think we should go with my proposed fix as a best hope solution but accept that the default browser setting will not be kept on all Huawei devices.

Asking @sarentz and @pocmo for their opinion about how we should proceed.

**Comment by ebalazs-sv** [comment] 2020-04-16 10:49
This is still reproducible on Fennec Beta Migration build 75.0.0-beta.5 from 4/14 with Huawei P9 Lite (Android 7).
cc @st3fan and @pocmo for their opinion on the Petru's proposed fix.

**Comment by Mugurell** [comment] 2020-04-16 13:45
Hello @ebalazs-sv 
Thank you for testing this again.

For fixing the Huawei issue I proposed two patches, one was merged in A-C (hope to have fixed the issue for some devices), one still to be merged in Fenix for fixing the issue on other Huawei models also. 
Indeed it is possible that the issue won't be fixed on all devices. In this case the issue I think is in Huawei's framework and would affect all applications.

Can you please test again the migration of the default browser status using this builds?
https://drive.google.com/file/d/1Xev1iJIUhY7mjL8xRPGueHLEkk2kLTQ5/view?usp=sharing
(The Fenix build contain my proposed patch for Fenix).
If there's no improvement we might drop this patch.

**Comment by ebalazs-sv** [comment] 2020-04-16 15:05
Hi!
I had tested the build received from Petru, with the following devices:
- Huawei P9 Lite (Android 7);
- Huawei Mate 20 Lite (Android 8.1.0);
- Huawei MediaPad M3 Lite 10 (Android 7.0);

and the default browser is not kept after migration.

**Comment by sv-sdeiac** [comment] 2020-04-21 14:19
Hi, I tried this ticket using Huawei P40 lite (Android 10) and the default browser is kept after migration.
@Mugurell, can you take a look at this?

Builds:
- the builds performed by @Mugurell on this [comment](https://github.com/mozilla-mobile/fenix/issues/8631#issuecomment-614662705).

**Comment by st3fan** [comment] 2020-04-30 16:40
@st3fan Spelunk through telemetry to see if we have any data on Huawei and default browser before/after Beta migration.

**Comment by st3fan** [comment] 2020-06-02 15:01
We've pushed this as far as we can and won't be making more changes.

**Closed by st3fan** 2020-06-02 15:01 UTC

**Comment by bengalih** [comment] 2022-08-20 23:32
@Mugurell - I apologize for tagging onto this issue.  I have found no other way to contact you.
I am interested in briefly discussing your research into the following:

> > Result set changed, dropping preferred activity for Intent { act=android.intent.action.VIEW dat=http://www.mozilla.org/... } type null

This is for an unrelated project, but via searches it seems your research on this issue is one of the only sources I have been able to find that references a similar issue.  Would you be willing to let me contact you out-of-band for a few minutes of your time to job your memory on this and see if you have any thoughts?

If so, please let me know best way to continue communication.  Thank very much.

**Comment by Mugurell** [comment] 2022-08-22 06:41
> This is for an unrelated project, but via searches it seems your research on this issue is one of the only sources I have been able to find that references a similar issue. Would you be willing to let me contact you out-of-band for a few minutes of your time to job your memory on this and see if you have any thoughts?

Sorry but I don't remember more than what is already written here and we don't support this migration code anymore.
(Didn't remember half of this details, it's nice that we had them documented).
In the end it seemed like a platform issue - specific to Huawei, affecting other apps also. 
If you need to investigate a similar issue my suggestion would be to checks the logs against [PackageManagerService](https://cs.android.com/android/_/android/platform/frameworks/base/+/0ab508981a52b64b348fb3c94f314bbc7a52da7a:services/core/java/com/android/server/pm/PackageManagerService.java;l=6973;drc=371fcb7cf26d34d25062a846f2a17a8615bec551) (it's important to match the Android release) and maybe take inspiration from the changes we've done here.
