### ISSUE TITLE
[Bug] No tracking protection icon shown after clicking on "report site issue"

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#12848] opened 2020-07-23 09:37 UTC
## Steps to reproduce
* Go to a website
* Click on menu ~~> addons~~ > Report site issue

### Expected behavior
* Tracking protection icon showing in toolbar

### Actual behavior
* No tracking protection icon in toolbar (empty space)
* Also doesn't appear when navigating in the tab or reloading the page

### Device information
* Android device: Pixel 3, Android 10
* Fenix version: Nightly 200723

**Comment by s-ankur** [comment] 2020-07-23 18:32
Duplicate of #11535

**Comment by s-ankur** [comment] 2020-07-24 18:36
This actually happens on any pade opened by an addon

**Comment by s-ankur** [comment] 2020-07-24 18:38
![Screenshot_20200725-000753_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/88424317-f2fec880-ce0a-11ea-9248-5fcc1ff9a89f.png)

**Comment by sv-ohorvath** [comment] 2020-09-03 14:27
This just happened on twitter.com and HuffPost for me on a fresh install with default settings, no clear STR.

**Comment by softvision-miralobontiu** [comment] 2020-10-08 12:55
I was able to reproduce this issue in normal browsing, no tracking protection icon displayed, after enabling the Custom - Only in private tabs ETP.
Environment: 10/8 Nightly, HTC 10 (Android 8)

**Comment by softvision-miralobontiu** [comment] 2021-01-15 07:14
I've encountered this issue on Beta 85.0.0-beta.8 with Sony Xperia Z5 Premium (Android 7.1.1), after installing the "Dark Reader" add-on. Not reproducible on Nightly from 1/14, nor on RC 84.1.4.

<img src="https://user-images.githubusercontent.com/40694158/104693075-b81e8300-5711-11eb-8ccc-70d693c873bd.png" width="300" height="550" />

**Comment by softvision-miralobontiu** [comment] 2021-01-19 12:18
I was able to reproduce the issue on the 1/19 Nightly build with HTC 10 (Android 8) on the https://webcompat.com/issues/new page.

**Comment by softvision-miralobontiu** [comment] 2021-01-27 09:14
Reproducible also on Beta 86.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by codrut-topliceanu** [comment] 2021-01-28 11:16
While I haven't been able to reproduce the issue with "Dark Reader" I have been able to consistently reproduce it with **"Report Site Issue..."** option from the 3 dot menu.

Opening a new tab normally would trigger in `EngineObserver`:
```
    override fun onTrackerBlockingEnabledChange(enabled: Boolean) {
        session.trackerBlockingEnabled = enabled
    }
```
which itself gets called from `GeckoEngineSession`, however when using **"Report Site Issue..."** this workflow is bypassed and that new _"webcompat.com/issues/new"_ tab is left with `SiteTrackingProtection.OFF_GLOBALLY`

I'm not yet sure why this happens, but if anyone from the GV team has any input I could really use it. 
Adding _needs-gv_ for myself here.

**Comment by Amejia481** [comment] 2021-01-28 15:00
As I mentioned on the slack chat, [here](https://github.com/mozilla-mobile/android-components/blob/9673de174eefa9fa957c351877c3ea3de3de5caf/components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarPresenter.kt#L74) is where we are observing the session and changing which status the icon should have, when the status is set then this class [TrackingProtectionIconView](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/TrackingProtectionIconView.kt) is in charge of [changing to the right icon or showing/hiding it](https://github.com/mozilla-mobile/android-components/blob/9673de174eefa9fa957c351877c3ea3de3de5caf/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/TrackingProtectionIconView.kt#L37).

Something that found a bit strange is that the icon is showing while there is not any drawable or tint set:

![image](https://user-images.githubusercontent.com/773158/106152550-8f53b000-614b-11eb-8d81-eac0828dc08a.png)


That could be an inconsistent  state where the toolbar gets initialized but  [TrackingProtectionIconView.kt](https://github.com/mozilla-mobile/android-components/blob/9673de174eefa9fa957c351877c3ea3de3de5caf/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/TrackingProtectionIconView.kt#L121) doesn't get called to apply the right configuration. I think you could debug [SiteTrackingProtection.toUpdate()](https://github.com/mozilla-mobile/android-components/blob/9673de174eefa9fa957c351877c3ea3de3de5caf/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/TrackingProtectionIconView.kt#L103) function when you click to the "Report Site Issue..." button to see if `SiteTrackingProtection.toUpdate()` gets executed  if not we have to investigate why not, because it should.  Please let me know if you need any additional help happy help :) .

**Comment by codrut-topliceanu** [comment] 2021-02-03 15:50
Still working on this but I'm gonna jot down a few things I noticed, because I stopped too soon with my debugging when I wrote my previous comment.

- Both normal tabs and "Report Site Issue" tab go through `GeckoEngineSession.createGeckoSession(...)`. However normal tabs have `defaultSettings` non-null (as they are initialised in `Core.kt`) while "Report Site Issue" has it null, leading to the issue we can see in the above posted screenshots.
- `defaultSettings` is null for "Report Site Issue" as they are not populated as a parameter when calling `GeckoWebExtension.registerTabHandler(..) -> override fun onNewTab(...)` ([link](https://github.com/mozilla-mobile/android-components/blob/a8a28338fb939d581ad62fad55cd8b6fa3bc1bc0/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt#L255))
- Adding a `DefaultSettings(trackingProtectionPolicy = TrackingProtectionPolicy.none())` as a parameter to `GeckoEngineSession` initialisation from the previously mentioned `onNewTab(..)` fixes the issue, however I don't believe that's ok. I think we should let Fenix control this by passing user preferences regarding ETP to `GeckoWebExtension`. I'll look into this solution.


> Something that found a bit strange is that the icon is showing while there is not any drawable or tint set

I didn't look into that yet, but that may be a better and simpler solution: no ETP settings -> don't show the ETP icon "space".

**Comment by codrut-topliceanu** [comment] 2021-02-04 10:17
Went with `defaultSettings` added to `GeckoWebExtension.registerTabHandler(..) -> override fun onNewTab(...)` by using the ones from `GeckoEngine` when calling  `installedExtension.registerTabHandler(webExtensionTabHandler, +defaultSettings+)`

Thank you @Mugurell for all your help with this.❤️

**Comment by Amejia481** [comment] 2021-02-04 14:53
> Went with `defaultSettings` added to `GeckoWebExtension.registerTabHandler(..) -> override fun onNewTab(...)` by using the ones from `GeckoEngine` when calling `installedExtension.registerTabHandler(webExtensionTabHandler, +defaultSettings+)`
> 
> Thank you @Mugurell for all your help with this.❤️
> 
> Will be fixed by PR [mozilla-mobile/android-components#9607](https://github.com/mozilla-mobile/android-components/pull/9607)

Awesome 🙌🏽 !

**Comment by sflorean** [comment] 2021-02-10 12:24
Verified as fixed on Nighty 2/10 with Samsung Note10 (Android 10).

**Comment by ebalazs-sv** [comment] 2021-02-11 14:20
This issue is still reproducible on Beta 86.0.0-beta.4 with Samsung Galaxy Tab S3 (Android 8).

**Comment by softvision-miralobontiu** [comment] 2021-03-08 10:50
I've encountered this issue o the Nightly debug build from 3/8 on HTC 10 (Android 8).
I'll reopen the issue.

**Closed** 2021-03-08 12:34 UTC
Labels: Feature:TrackingProtection, S2, eng:qa:verified, needs:ac, 🐞 bug
