### ISSUE TITLE
[Bug] New search experience: Search engine list shows up left arrow to insert suggestions

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14444] opened 2020-08-29 15:21 UTC
## Steps to reproduce

1. enable new search experience
2. tap address bar
3. tap search engine button

### Expected behavior

up left arrow doesn't appear next to engines.

### Actual behavior

![signal-2020-08-29-111842](https://user-images.githubusercontent.com/152493/91640202-b9147980-e9e9-11ea-814a-c2436444540c.png)

up left arrow appears; tapping them fills in search engine name as search query without changing search engine. 

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 200829 06:05 (Build #2015760755)
AC: 57.0.20200827190112, 91f7bcbca
GV: 82.0a1-20200827093043
AS: 61.0.13

**Comment by hwinnemoe** [comment] 2020-08-29 19:37
Duplicate of #13996

**Closed** 2020-09-01 02:29 UTC
Labels: needs:triage, 🐞 bug
