### ISSUE TITLE
FNX-4361 ⁃ [Bug] Back should not go tp the overview

### ISSUE THREAD

**Issue by Dischi** [mozilla-mobile/fenix#10536] opened 2020-05-09 08:05 UTC
## Steps to reproduce
Use  Google Search App to search for something or use its news feed. Select a web page. After reading the content, click "back". 

### Expected behavior
It should go back to the previous app. This always happened in older versions. 

### Actual behavior
The browser now shows the overview page. This is not back in terms of the user interaction.

### Device information
* Android device: Pixel 3
* Fenix version: Preview 5.0.0

**Comment by cadeyrn** [comment] 2020-05-09 09:19
Duplicate of #10394.

**Closed** 2020-08-11 00:59 UTC
Labels: needs:triage, 🐞 bug
