### ISSUE TITLE
[Bug] Search engine options are shown with ↖︎ Append arrow icons

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#14556] opened 2020-08-31 23:11 UTC
## Steps to reproduce

- Open a new tab page with the keyboard up
- Tap “Search engine” chip

### Expected behavior

↖︎ Append arrow icons should not be displayed to the side of each search engine option, because it’s irrelevant.

### Actual behavior

↖︎ Append arrow icons are displayed.

<img width="360" src="https://user-images.githubusercontent.com/51007/91777406-d3499400-ec43-11ea-8c97-c3bc73c0030f.png">

**Comment by brampitoyo** [comment] 2020-08-31 23:11
CC @boek

**Comment by hwinnemoe** [comment] 2020-09-01 08:08
Duplicate of #13996

**Comment by s-ankur** [comment] 2020-10-22 06:26
This is solved now @brampitoyo

**Closed** 2020-11-19 18:37 UTC
Labels: Feature:Search, 🐞 bug
