### ISSUE TITLE
[Bug] tabs tray refactor: Firefox does not respond after closing the tabs tray

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#18860] opened 2021-04-07 21:21 UTC
### Steps to reproduce

0. enable the tabs tray refactor
1. open the tabs tray
2. swipe down to close the tabs tray

### Expected behavior

You can interact with the current tab.

### Actual behavior

Only the Android bottom bar is active, the whole browser interface is darkened and Firefox no longer responds to any interaction. You have to either press the Android back button or to remove Firefox from the recent apps and restart Firefox to make Firefox responsive again.

It does not happen with the old tabs tray.

![Screenshot_20210407-230821](https://user-images.githubusercontent.com/1100614/113935664-1467df00-97f7-11eb-8543-85b3865a1de9.jpg)

### Device information

* Device vendor / model and Android version: OnePlus 7T Pro McLaren Edition witth Oxygen OS 11 (Android 11)
* Firefox for Android version: master branch revision 10eace2f99b23f7135c9215d33cc2b9ead169b2b

**Comment by jonalmeida** [comment] 2021-04-11 05:29
Duplicate of https://github.com/mozilla-mobile/fenix/issues/18885

**Closed by jonalmeida** 2021-04-11 05:29 UTC
Labels: needs:triage, 🐞 bug
