### ISSUE TITLE
FNX-4549 ⁃ [Bug] Black flash when opening tab tray

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10778] opened 2020-05-19 17:08 UTC
## Steps to reproduce
1. Open tab
1. Open tab tray

### Expected behavior
No flash.

### Actual behavior
I see a very fast black flash as the tab tray opens. 

[flash.zip](https://github.com/mozilla-mobile/fenix/files/4652081/flash.zip)

### Device information
* Android device: pixel 2
* Fenix version: latest nightly

**Comment by gabrielluong** [comment] 2020-06-09 17:52
This is probably not reproducible anymore since the tabs tray is in a bottom drawer instead of its own fragment. Closing as WORKSFORME.

**Closed** 2020-08-11 01:46 UTC
Labels: 🐞 bug
