### ISSUE TITLE
[Bug] Unable to sign in to the native Slack app through Auth0

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#7257] opened 2019-12-17 22:56 UTC
## Steps to reproduce

Make sure Firefox Preview is your default browser.

With the native Slack app, start the sign in flow to the Mozilla Slack. At one point you are redirected to the Auth0 website to finish the login flow. The native Slack app properly opens Firefox Preview and the SSO sign-in page. Sign in there with your Mozilla account and password.

### Expected behavior

After signing in successfully, Firefox Preview should switch back to the native Slack app.

### Actual behavior

Firefox Preview shows a blank page with a https://auth.mozilla.auth0.com/ link.

### Notes

This sign in flow is pretty common and it is probably not limited to the Mozilla Auth0 flow.

### Device information

* Android device: Pixel 3, Android 10
* Firefox Preview version: 3.0.0

**Comment by st3fan** [comment] 2019-12-18 00:06
@rocketsroger is this also related to app links? I assume the link that Auth0 redirects to is the native Slack app link?

**Comment by rocketsroger** [comment] 2019-12-18 00:08
> @rocketsroger is this also related to app links? I assume the link that Auth0 redirects to is the native Slack app link?

Yes this is.  It could be related https://bugzilla.mozilla.org/show_bug.cgi?id=1600704.  I'll have to retest after GV side is fixed.

**Comment by rocketsroger** [comment] 2019-12-27 16:12
After completing SSO login with mozilla Auth0, URL `https://mozilla.slack.com/sso/saml` was loaded and it fails to redirect to a `https://app.slack.com/t/mozilla/login/z-app...` link.  Needs to investigate why no `https://app.slack.com` link was triggered automatically after signed in.

One workaround is revisiting the `https://mozilla.slack.com/sso/saml` link loads a button to launch the slack app.

**Comment by rocketsroger** [comment] 2019-12-27 19:00
Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1600704.  Retest after fix from GV is merged.

**Comment by rocketsroger** [comment] 2019-12-27 22:04
Confirmed by debugging focus.  On focus I see a `onLoadRequest` for a slack:// URL right after the SAML URL.  The slack scheme triggers focus to open in third party app.

**Comment by alexandru-io** [comment] 2020-01-30 07:05
> Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1600704. Retest after fix from GV is merged.
Can I have a link to the fix from GV please?

**Comment by rocketsroger** [comment] 2020-02-10 21:45
> Can I have a link to the fix from GV please?

Fix not merged yet.  https://phabricator.services.mozilla.com/D62059

**Comment by rocketsroger** [comment] 2020-02-28 19:36
Sign in to slack works correctly with "Open links in apps" turned on.  However, it doesn't work correctly without the setting turned on.  Will need move investigation.

**Comment by rocketsroger** [comment] 2020-03-02 16:45
From discussions with GeckoView team, this issue is due to `slack://` scheme is not passed to `onLoadRequest` in `AppLinkInterceptor`.  This will require further fixes from GeckoView.

**Comment by rocketsroger** [comment] 2020-03-02 17:36
Need fix from https://bugzilla.mozilla.org/show_bug.cgi?id=1619344

**Comment by rocketsroger** [comment] 2020-03-03 21:27
Confirmed with GV 75.0.20200303095030 this is fixed.  The next nightly build should have this version.  Please verify this is fixed.

**Comment by softvision-miralobontiu** [comment] 2020-03-05 12:19
Verified as fixed on the latest Nightly build from 3/5 with Samsung Galaxy Note 8 (Android 9).
After signing in successfully, Firefox Preview switched back to the native Slack app.

**Closed by softvision-miralobontiu** 2020-03-05 12:19 UTC
Labels: P2, S1, eng:qa:needed, 🐞 bug
