### ISSUE TITLE
Let users delete specific suggested entries in the address bar.

### ISSUE THREAD

**Issue by HubKing** [mozilla-mobile/fenix#22431] opened 2021-11-13 07:50 UTC
### What is the user problem or growth opportunity you want to see solved?
FireFox shows suggestions from History when the user types a few characters in the address bar. Sometimes, the top suggestions are what the user do not want (e.g., a URL that no longer exists). It seems that currently there is no way to deleted such unwanted entries.

How about adding a delete button on the right of such entries so that the user could delete them?

### How do you know that this problem exists today? Why is this important?

For example, as the image below, when I type "t", "i", and "m", FireFox shows "www.youtube.com/post" as the top suggestion, but that URL is unusable. The correct best suggestion, in my opinion, is the second one, but even if I keep choosing the second, "www.youtube.com/post" remains as the top suggestion. This is annoying.

![image](https://user-images.githubusercontent.com/10900489/141610563-2c1110b2-e85c-4ccf-ade8-24e89dc88f57.png)

### Who will benefit from it?
Users who often search in the address bar.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18624)

**Comment by topotropic** [comment] 2021-12-21 15:08
Duplicate of https://github.com/mozilla-mobile/fenix/issues/1920

**Closed** 2023-01-30 19:37 UTC
Labels: feature request 🌟, needs:UX-feedback
