### ISSUE TITLE
[Bug] ESNI disabled after upgrade to 81.1.4 on android

### ISSUE THREAD

**Issue by temporalsphere** [mozilla-mobile/fenix#15858] opened 2020-10-12 22:27 UTC
## Steps to reproduce
goto to ensi checker on cloudflare:
https://www.cloudflare.com/ssl/encrypted-sni/
Check ESNI is working properly.
Upgrade firefox on android to 81.1.4
Check ESNI on cloudflare again.
ESNI disabled after upgrade.
Goto about:config to check - about:config not working

### Expected behavior
ESNI settings to remain unchanged after upgrade/
about:config working to correct ESNI settings.

### Actual behavior
ESNI disabled after upgrade.
Goto about:config to check - about:config not working
### Device information

* Android device: ? Official Verizon Samsung Galaxy A01
* Fenix version: ? Firefox 81.1.4

**Comment by temporalsphere** [comment] 2020-10-12 22:28
about:config disabled???
Why in God's name would you ever do that?
Really??? Really???

**Comment by KrasnayaPloshchad** [comment] 2020-10-13 15:22
Yes, about:config is banned in 81.1.4. Maybe the function can be access in this way:
1. Root the device
2. Access the data folder in root folder, then find out org.mozilla.fenix folder
3. Find out prefs.js
4. Modify the value of network.security.esni.enabled

**Comment by temporalsphere** [comment] 2020-10-14 01:11
Unfortunately in some parts of the United States you cannot root your mobile device because doing so will violate support agreements with mobile service provider.  Using official versions of the mobile device from the mobile carrier allows them to troubleshoot problems when they occur and the end-user doesn't get blamed when something goes wrong.

There are millions of users who use the Firefox web browser.  If you are going to use the Mozilla Firefox branding then you should at least adhere to the open source standards of quality that is expected from the trusted brand.  Departing from the open source community standards and doing things "your way" will only cause damage to the branding and reputation of the mozilla organization. 

I suggest you rename your browser to something other than Firefox to ensure no one mistakenly downloads this software thinking they are receiving the same level of quality.

**Comment by KrasnayaPloshchad** [comment] 2020-10-14 12:04
😵🔨

**Comment by KrasnayaPloshchad** [comment] 2020-10-14 12:51
Fortunately, I can aceess this feature on Nightly releases, it’s possible to enable in about:config.

**Comment by liuche** [comment] 2020-10-14 23:50
Dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=1500289

**Closed by liuche** 2020-10-14 23:50 UTC
Labels: needs:triage, 🐞 bug

**Comment by peimansh** [comment] 2021-03-02 16:08
It's not even possible to access it using Firefox Nightly.
version: 210301

**Comment by prono69** [comment] 2021-03-27 17:27
Firefox is getting bad I guess
