### ISSUE TITLE
[Crash]android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by hkaancaliskan** [mozilla-mobile/fenix#17714] opened 2021-01-31 11:33 UTC
```
64ea4a15-635d-4909-9da2-8e75f330241c
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{6b82d11 u0 org.mozilla.firefox_beta/org.mozilla.fenix.media.MediaSessionService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

## Steps to reproduce
1- Open a youtube video, watch some (for me https://m.youtube.com/watch?v=UBKh7tpTAgM)
2- Put firefox in background and do some other stuff (for me messaging)
3- Came back to firefox and resume video.

### Expected behavior
Firefox directly resumes video, even with no wait time

### Actual behavior
Firefox waited some time like 0.5mins and then crashed (not %100 reproducible)

### Device information

* Device vendor / model and Android version: Xperia XZ1 Android 11
* Firefox for Android version: 86.0.0-beta.1

Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=17c91a834afb414dba35e378c0f89fde
Socorro: https://crash-stats.mozilla.org/report/index/bp-2910755d-246f-4312-9ab5-960b30210131

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9549)

**Comment by Mugurell** [comment] 2021-02-01 06:18
The issue is because we started the media service without a notification.
I could't reproduce this though there are quite a few of such reports on socorro even for the old `MediaService` like https://crash-stats.mozilla.org/report/index/63d043e3-655f-4502-8f68-d37b00210131

I'm seeing that the notification is posted only from `processMediaSessionState()` and [it is possible that the Service would be created without this method being called](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt#L65-L69) so maybe this is something we can improve upon. @rocketsroger

**Comment by rocketsroger** [comment] 2021-02-01 14:52
I can't reproduce as well.  I will assign it to myself and investigate more.

**Comment by rocketsroger** [comment] 2021-02-09 22:30
Sentry issue: [FIREFOX-NIGHTLY-1X8](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/6026738/?referrer=github_plugin)

**Comment by rocketsroger** [comment] 2021-02-18 16:08
Looks like the new patch is working.  The crash rate is improving.  I'll continue to monitor this.

**Comment by test491** [comment] 2021-02-24 16:57
followed Steps to reproduce given above

##### crash is not reproducible:
* version: 86.1.1
* version: 87.0.0-beta.1 (Build #2015795065) AC: 73.0.0, 69a800e47 GV: 87.0-20210222154334 AS: 71.0.0
* version: Nightly 210224 (Build #2015795113) AC: 73.0.20210223143117, 05f3e3cc7 GV: 87.0a1-20210222084406 AS: 71.0.0

##### note: video is not resuming on all versions. it resets to beginning (to watch, i have to again tap play)

**Comment by rocketsroger** [comment] 2021-02-24 17:29
On Nightly it looks like the fix is working.  I can see a downtrend on the crash frequency (but did not completely eliminate it).  I will continue to monitor this when 86.1.1 is released.

**Comment by pascalchevrel** [comment] 2021-03-01 15:49
@rocketsroger I am seeing this crash spike with 86.1.1, do you have plans to uplift your fix to beta/release?

**Comment by rocketsroger** [comment] 2021-03-01 16:05
> @rocketsroger I am seeing this crash spike with 86.1.1, do you have plans to uplift your fix to beta/release?

Unfortunately it is already in 86.1.1.  I've been monitoring it and I don't see any uptick in this crash.  Most of the crashes in beta are with a older A-C version.  Where are you seeing the uptick? I can investigate to see if it is related.

**Comment by pascalchevrel** [comment] 2021-03-01 16:39
In https://bugzilla.mozilla.org/show_bug.cgi?id=1651221 in the crash data section you can see the sharp increase of crashes on the crash graph since we unthrottled updates last Friday

**Comment by sflorean** [comment] 2021-03-05 13:26
@rocketsroger is this ready to be verified? Do we have steps in order for QA team to reproduce it?

**Comment by rocketsroger** [comment] 2021-03-05 15:54
> @rocketsroger is this ready to be verified? Do we have steps in order for QA team to reproduce it?

@sflorean Unfortunately we don't have a way to reproduce it.  This is one of the reason why it is very hard to fix this issue.  I can confirm that this fix is in March 4th's Nightly.  I'll continue to monitor this particular crash's rate on Sentry and update here.  Thanks,

**Comment by hakkikaancaliskan** [comment] 2021-04-06 21:55
@rocketsroger does this problem solved on metrics, if so we can close the issue :)

**Comment by rocketsroger** [comment] 2021-04-07 18:50
> @rocketsroger does this problem solved on metrics, if so we can close the issue :)

From crash reporting it looks like the crash rate has lowered but not eliminated.  I'll investigate to see if we can lower the crash rate more.

**Comment by rocketsroger** [comment] 2021-04-20 14:16
Confirmed that this issue has been solved.  Closing the issue.

**Comment by rocketsroger** [comment] 2021-04-21 15:04
This has been a crash that we see for about 2 years.  I have lowered the crash rate to a point I don't think there's nothing else I can do. With https://developer.android.com/about/versions/12/behavior-changes-all#foreground-service-notification-delay this crash will hopefully be eliminated.

**Comment by MatthewTighe** [comment] 2022-03-29 23:15
@rocketsroger Coming to this thread from the crash appearing [fresh in the new Sentry portal](https://sentry.io/organizations/mozilla/issues/3109465420/events/e2ae80cccdce45c7b36215573b691c88/?project=6176959&query=is%3Aunresolved+level%3Afatal+firstSeen%3A-2w&sort=freq&statsPeriod=14d). 

I found [this article](https://medium.com/geekculture/context-startforegroundservice-did-not-then-call-service-startforeground-solved-7640d5ba394a) that suggests binding the service in the background and calling `startForeground` from a started, non-service lifecycle component. Was anything like that attempted previously? Is it something we would want to try?

**Comment by rocketsroger** [comment] 2022-03-30 14:02
> I found [this article](https://medium.com/geekculture/context-startforegroundservice-did-not-then-call-service-startforeground-solved-7640d5ba394a) that suggests binding the service in the background and calling `startForeground` from a started, non-service lifecycle component. Was anything like that attempted previously? Is it something we would want to try? If so, happy to give it a go 🙂

@MatthewTighe that's promising.  If we can eliminate the rest of this crash that will be great.  One thing to make sure is that when the user pauses the media, we should be able to swipe the notification away.  But when the media is playing, we should not be able to swipe it away.  Thanks!

**Comment by cpeterso** [comment] 2022-05-17 23:01
> I found [this article](https://medium.com/geekculture/context-startforegroundservice-did-not-then-call-service-startforeground-solved-7640d5ba394a) that suggests binding the service in the background and calling `startForeground` from a started, non-service lifecycle component. Was anything like that attempted previously? Is it something we would want to try?

@MatthewTighe - Have you created an issue to try binding the service? This crash is the #2 Fenix top crash in Socorro crash reports: https://bugzilla.mozilla.org/show_bug.cgi?id=1651221

**Comment by MatthewTighe** [comment] 2022-05-23 17:39
I'll re-open this issue so that we can keep the full context in one spot

**Comment by AndiAJ** [comment] 2022-05-25 14:13
Similar stack traces for [useAppWhileTabIsCrashedTest](https://github.com/mozilla-mobile/fenix/issues/25029) and [privateBrowsingUseAppWhileTabIsCrashedTest](https://github.com/mozilla-mobile/fenix/issues/24996) UI tests.

**Comment by rocketsroger** [comment] 2022-06-07 17:13
@rvandermeulen The only thing I can see that could have caused this recent jump is this one https://github.com/mozilla-mobile/android-components/pull/11991.  Should we revert?

**Comment by rvandermeulen** [comment] 2022-06-07 17:15
@rocketsroger Seems worth a try. We can revert on the v101 branch only to start and see what happens there before making a decision for v102+.

**Comment by rvandermeulen** [comment] 2022-06-13 23:03
@rocketsroger Crash rate for 101.2.0 is looking much lower than 101.1.1.

**Comment by rocketsroger** [comment] 2022-06-14 20:10
Reverted from both Nightly and Beta.  Thanks,

**Comment by rocketsroger** [comment] 2022-07-15 20:36
Closing since the issue is confirmed resolved.

**Closed by rocketsroger** 2022-07-15 20:36 UTC
Labels: 🐞 bug, b:crash, Feature:Media
