### ISSUE TITLE
[Bug] Button press animation on "+" is displayed under the URL section on the home screen

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8355] opened 2020-02-12 15:13 UTC
## Steps to reproduce
1. Launch Fenix.
2. Reach the home screen.
3. Tap and hold on the `+` button until the press animation is displayed.
### Expected behavior
Button press animation on "+" is displayed under the URL section on the home screen.

### Actual behavior
The press animation should be displayed above the URL section on the home screen.

### Device information

* Android device: **Samsung Galaxy S10+ (Android 9).**
* Fenix version: **Nightly 2/12.**

![20200212-162224 (1)](https://user-images.githubusercontent.com/42831109/74346236-f0a63600-4db7-11ea-86d6-8387d9822817.gif)

**Comment by eliserichards** [comment] 2020-05-05 19:29
Closing as dupe of #1648

**Closed by eliserichards** 2020-05-05 19:29 UTC
Labels: Feature:Toolbar, eng:ux-debt, 🐞 bug
