### ISSUE TITLE
Clicking on a google search result doesn't appear to record the final target url

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#18199] opened 2021-02-26 20:09 UTC
STR:
- search for a page on google
- click on a result link
- look at History - last item will be google's redirect link, not the final target link

**Comment by test491** [comment] 2021-03-01 08:15
#### reproducible

* version: `86.1.1`
* version: `87.0.0-beta.1 (Build #2015795065)`
* version: `Nightly 210228 (Build #2015795881)`

#### screenshot
![Nightly](https://user-images.githubusercontent.com/78364929/109469605-44072700-7a94-11eb-917b-b71173c6b311.jpg)

#### android 9, Galaxy J7 Nxt

**Comment by mcarare** [comment] 2021-03-02 14:37
This looks like it's the same issue as https://github.com/mozilla-mobile/fenix/issues/17389.
@grigoryk if you agree, we can close this one as duplicate and use the original issue for tracking, as it already has a linked Bugzilla issue. 

@amedyne if we close this one we can prioritize the original, but it will still be waiting on GV.

**Comment by amedyne** [comment] 2021-03-02 14:58
Yes @mcarare. This looks like the same issue. Let's prioritize the original issue #17389.

**Closed** 2021-03-02 15:23 UTC
Labels: Feature:History, 🐞 bug
