### ISSUE TITLE
[Bug] Receiving link from other device

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#11152] opened 2020-06-02 16:50 UTC
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1642212

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0

Steps to reproduce:

I send multiple links to read later and on my mobile devise using Firefox Sync account.

The Android UI (devise is Samsung Galaxy S9) shows me several notification which I have to select one by one to open in Firefox Mobile.

Actual results:

I have to click on each notification (the system only display 3 of those) to open 10 links.
And of course, when I click on the notification, it open the browser, which hide the notification, which I have to open again, and so on. And some time, I also loose said notification

Expected results:

I think there should be one notification, indicating "N new links to read", and when clicking the notification or directly in the browser, there should a Firefox page allowing me to:

```
Open one or all
Select some and open some
```

It is to be noted that on Firefox Desktop... the links are directly opened.

**Comment by jonalmeida** [comment] 2020-09-15 05:22
Duplicate of #12294

**Closed by jonalmeida** 2020-09-15 05:22 UTC
Labels: Feature:SendTab
