### ISSUE TITLE
[Bug] Synced mobile devices need a "mobile device" icon

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2884] opened 2019-05-27 14:30 UTC
## Steps to reproduce
1. Sign in to sync.
1. Open a tab and tap share in the main menu.
1. Observe the icons of the mobile device synced.
    1. Expected behavior
According to mocks, mobile devices and desktop have different icons: https://user-images.githubusercontent.com/128755/57334721-8bb60500-70ee-11e9-92fb-bca32133f5ff.png
    1. Actual behavior
Same icons for mobile & desktop.
    1. Device information

* Android device: 
* Fenix version: 5/27

**Comment by jonalmeida** [comment] 2019-05-27 16:25
@sv-ohorvath do you mind if I close this as a duplicate of #2887 since I believe that's the root cause for this issue.

**Comment by sv-ohorvath** [comment] 2019-05-28 06:19
> @sv-ohorvath do you mind if I close this as a duplicate of #2887 since I believe that's the root cause for this issue.

Not at all. I'll close it. Thank you!

**Closed** 2020-08-26 20:29 UTC
Labels: 🐞 bug
