### ISSUE TITLE
[Bug]: Inactive tabs closing despite "Close Tabs Manually" being selected

### ISSUE THREAD

**Issue by WintermutesGhost** [mozilla-mobile/fenix#20661] opened 2021-08-04 01:09 UTC
### Steps to reproduce

1. Set "Close Tabs" to "Manual"
2. Have a tab open for >1 month 😕 

### Expected behaviour

Tabs should not be automatically discarded when "Close tabs" is set to "Manually"

### Actual behaviour

Old tabs were abruptly discarded, other tabs near the 1 month inactivity window were marked as "inactive"

### Device name

One Plus 5T

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1 (Build #2015825739)

### Additional information

Recent problem since I have been using Close Tabs Manually for months with no issues. Switching to Close Tabs Monthly and back to Manual left some tabs in the "inactive" state, but that may be expected behavior.

**Comment by jonalmeida** [comment] 2021-08-04 04:00
>Tabs should not be automatically discarded when "Close tabs" is set to "Manually"

To clarify the bug for eng: The bug here, is that the UI is not reflecting the accurate value of the settings in [`TabSettingsFragment`](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/settings/TabsSettingsFragment.kt). This might be a larger bug that could be fixed in [`RadioButtonPreference`](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/settings/RadioButtonPreference.kt) to read the pref and set that value as the default.

**Comment by lnicola** [comment] 2021-08-04 19:48
Not only that. The last update changed the preference value (I had it set to Close manually), but also closed all my old tabs (hundreds of them).

**Comment by jonalmeida** [comment] 2021-08-15 02:12
We've updated the default back to manual, so we can close this bug as invalid.

The cause though was that our [UI in the layout file](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/res/xml/tabs_preferences.xml#L29) was not updated to display the default. If we ever decided to change a default, this change would need to be added as well.

**Closed by jonalmeida** 2021-08-15 02:12 UTC
Labels: 🐞 bug
