### ISSUE TITLE
[Bug]The onboarding flashes when you return from settings

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#4436] opened 2019-08-01 10:47 UTC
## Prerequisites
You have a fresh install or clear data before.

## Steps to reproduce
1. Open Firefox Preview;
2. Tap on the 3dot menu;
3. Tap on Settings;
4. Tap on back button from your device;

### Expected behavior
When Back is tapped, the onboarding tour is no longer displayed.

### Actual behavior
The onboarding tour is no longer displayed but has a flash close view.

### Device information

* Android device: Nexus 9 (Android 7.1.1)
* Fenix version: 1.2.0-rc.1 Thursday 8/1

### Notes:
- [video](https://drive.google.com/file/d/0B-OVCGyglYi_NWc3RlFFT0o3dzJRQThPZ3dsX1ZhUnF5ZnU0/view?usp=sharing);
- The disappearing of the onboarding should be smoother.

**Comment by sblatz** [comment] 2019-08-08 21:58
Can we just hide onboarding **before** navigating away? Since we intend to not show the onboarding when a user moves to Settings, it seems reasonable to just hide it immediately.

**Comment by ekager** [comment] 2019-08-09 01:01
Yep that seems like a good solution. Adding a help wanted label

**Comment by sv-ohorvath** [comment] 2019-08-16 09:11
This is still reproducible on Nightly 190816 and RC 1.3.0 on Xiaomi Mi Pad 2 (Android 5.1) & Nexus 9 (Android 7.1.1).
[Recording](https://drive.google.com/file/d/1leuzVsf7JN9snQKGI8Uz1BXGH49Boriy/view?usp=sharing)

**Comment by softvision-miralobontiu** [comment] 2019-08-21 13:57
Verified as fixed on the latest Nightly 190821 (#12330640) with OnePlus 5T (Android 9), Huawei P9 Lite (Android 6.0.1), HTC Desire 820 (Android 6.0.1), Sony Xperia Z2 Tablet (Android 6.0.1), Nexus 9 (Android 7.1.1), and Sony Xperia Z5 Premium (Android 7.1.1).

**Closed by softvision-miralobontiu** 2019-08-21 13:57 UTC
Labels: Feature:Onboarding, P3, S2, eng:qa:needed, good first issue, help wanted, 🐞 bug
