### ISSUE TITLE
[Bug] Notification permissions can't be disabled/re-enabled unless you restart the browser

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#8809] opened 2020-02-27 10:01 UTC
## Steps to reproduce
1. Go to https://pushalert.co/demo, https://www.pushengage.com/demo
2. Tap to send a demo notification, tap Block notifications on the permission request dialog.
3. Tap the lock icon and tap Allow notifications. Try to send the push notification.
4. Go to Settings>Site permissions and Allow notifications for these websites. Try to send the push notification.
5. Lastly, clear permissions for these websites. Try to send the push notification.
6. Restart the browser after allowing notifications. Try to send the push notification.
### Expected behavior
Notifications are sent after the permissions are set to allowed and refreshing the page. Same 
### Actual behavior
Notifications aren't sent until you restart the browser, refreshing the page is not enough.
### Device information

* Android device: Xiaomi Mi Pad 2 (Android 5.1), OnePlus 5T (Android 9.0), Pixel (Android 10)
* Fenix version: Beta 4.0-build2, Nightly 2/27

**Comment by Amejia481** [comment] 2020-02-27 19:02
This looks like a GeckoView issue, I opened a bug in Bugzilla for it https://bugzilla.mozilla.org/show_bug.cgi?id=1618632

**Comment by eamsen** [comment] 2020-03-17 15:35
As noted on [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1618632#c1), there seems to be a difference in behavior between calling `Settings` -> `Site permissions` -> `Exceptions` -> `Clear permissions on all sites` and calling `Delete browsing data` -> `Delete browsing data` with `Site permissions` selected.
For latter calls into GeckoView's `StorageController`, while the former doesn't, which persists the site permissions settings until the runtime is restarted.

**Comment by eamsen** [comment] 2020-03-23 15:59
Thanks, @Amejia481. Can we get QA confirmation that this issue is fixed, so that I can close the GV bug?

**Comment by Amejia481** [comment] 2020-03-23 16:34
We need Fenix to update to a new version of AC that contains the changes and this pr that depends on it https://github.com/mozilla-mobile/fenix/pull/9324 to land.

**Comment by Amejia481** [comment] 2020-03-24 19:27
@sv-ohorvath would you mind retesting it?

**Comment by sflorean** [comment] 2020-03-30 13:49
Verified as fixed on Nightly build - 3/30 with Samsung Galaxy Note10 (Android 10) and Xiaomi Mi Pad 2 (Android 5.1).

**Closed by sflorean** 2020-03-30 13:49 UTC
Labels: Feature:SitePermissions, S3, eng:qa:needed, needs:gv, needs:triage, 🐞 bug

**Comment by Amejia481** [comment] 2020-03-30 14:02
> Thanks, @Amejia481. Can we get QA confirmation that this issue is fixed, so that I can close the GV bug?

@eamsen the issue has been confirmed as fixed, now you can update the GV bug.
