### ISSUE TITLE
Forward option is missing if i have move to homepage accidentally

### ISSUE THREAD

**Issue by RadhakrishnanKandasamy** [mozilla-mobile/fenix#15317] opened 2020-09-22 18:33 UTC
I am unable to forward tab if i move to homepage accidentally. We must maintain tab history if i am coming to homepage after browsing

**Comment by s-ankur** [comment] 2020-09-22 18:37
Duplicate of https://github.com/mozilla-mobile/fenix/issues/15241.

**Comment by kbrosnan** [comment] 2020-09-24 04:28
Closing as a duplicate

**Closed by kbrosnan** 2020-09-24 04:28 UTC
Labels: needs:triage
