### ISSUE TITLE
[Bug] Black buttons in edit mode on the bookmark multi-selection toolbar

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5848] opened 2019-10-08 15:08 UTC
## Steps to reproduce
1. Go to bookmarks.
2. Long tap a bookmarked page. Tap the edit button.
3. Tap to create a new folder.
3. Observe the buttons in the multi-selection toolbar on this entire flow: the delete button, add folder button, save folder.
### Expected behavior
The buttons are white (on light theme).
### Actual behavior
The buttons on the right side are black: the delete button, add folder button, save folder.
### Device information

Android device: Pixel (Android Q), Pixel 3 (Android 9), Sony Xperia Z5 Premium (Android 7.1.1)
Fenix version: Nightly 10/8

**Comment by ekager** [comment] 2019-10-15 02:41
When we are in edit mode, the top right button should be white
![Screenshot_20191014-194020](https://user-images.githubusercontent.com/25442310/66795800-8f7a5e80-eeba-11e9-8a55-1b232261acad.png)

**Comment by BranescuMihai** [comment] 2019-10-15 16:09
I've discovered two behaviours: 
- one with purple toolbar and black button (the reported bug), because we set the purple colour to toolbar in the previous screen(library) and it remains set for the edit bookmark screen
- one with white toolbar and black button, when we come from the quickActionSheet. 

Here are the two videos attached:
[Purple toolbar](https://drive.google.com/file/d/131ChnXNMFqwpxTFLMhnssMAkCq8KGliR/view?usp=sharing)
[White toolbar](https://drive.google.com/file/d/13zLJjAQ-V2g48I1v7aU5Igamft2In12T/view?usp=sharing)

Please advise which one of the two is the desired one, thanks!

**Comment by NotWoods** [comment] 2019-10-15 16:18
The white toolbar is the desired one. We need to reset the purple color back to white in the library screen somehow or always set the toolbar color to white in the edit screen.

**Comment by BranescuMihai** [comment] 2019-10-21 13:51
Hey! Yep, it's still reproducible because the PR for this bug is still pending review, so the fix is not yet merged into master

**Comment by brampitoyo** [comment] 2019-10-23 05:11
@NotWoods is correct. For edit mode, the toolbar should be white (if on light theme). The colour of the icon would then be dark.

**Comment by AndiAJ** [comment] 2019-10-28 08:33
Hi, **verified as fixed** on the latest Nightly Build #13010606 using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4(Android 5.1.1)

► Video Light theme
![20191028_101646](https://user-images.githubusercontent.com/51314259/67663425-22f96800-f96e-11e9-94c4-5813f8a14759.gif)

► Video Dark  theme
![20191028_101727](https://user-images.githubusercontent.com/51314259/67663475-4a503500-f96e-11e9-90a4-e9496c2845a8.gif)

**Closed by AndiAJ** 2019-10-28 08:33 UTC
Labels: Feature:Bookmarks, Hacktoberfest, S3, eng:qa:verified, eng:ready, help wanted, 🐞 bug
