### ISSUE TITLE
[Bug] Jump back in: website title sometimes missing

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#21940] opened 2021-10-14 20:20 UTC
### Steps to reproduce

1. make sure you see the "jump back in" section
2. additional steps are unclear

### Expected behaviour

The card shows a page title. If no page title is available there should be a fallback, probably the domain.

### Actual behaviour

Missing page title -- looks strange with that much empty space.

![Screenshot_20211014-221719](https://user-images.githubusercontent.com/1100614/137389571-4da86da4-ddb1-4d09-9dc0-48def63c4d0b.jpg)

### Device name

OnePlus 7T Pro McLaren Edition

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

main branch revision 625233f66488412287e3400a08d1c5c55439ff2e

**Comment by jonalmeida** [comment] 2021-10-20 17:27
Duplicate of https://github.com/mozilla-mobile/fenix/issues/21940

(I left a comment on that bug already of the regression)

**Closed by jonalmeida** 2021-10-20 17:27 UTC
Labels: 🐞 bug

**Comment by jonalmeida** [comment] 2021-10-20 21:26
@cadeyrn Whoops, thanks for the catch! I meant to link #21771
