### ISSUE TITLE
[Bug] heavy-handed page refresh loses WIP content

### ISSUE THREAD

**Issue by bunnybooboo** [mozilla-mobile/fenix#12121] opened 2020-06-30 08:44 UTC
## Steps to reproduce
1. Open several tabs to be used as **source**s
1. One of these is content creation **origin** (e.g. [original content creation or commenting such as] Reddit, [or filling in text fields such as] Google Forms, Survey Monkey)
1. In **origin** begin adding some text
1. Switch tabs to **source** (tested with **copy url**)
1. Switch tabs back to **origin** (with intention to **paste url**)

### Expected behavior
Expected **origin** to retain state from where I left off, enabling me to successively switch back and forth between **source** tabs, and build a content post based on them.

### Actual behavior
**Origin** page refreshes and all drafted text is lost.

### Device information
* Android device: v9 (Build pkq1.190522.001) LG G6 (LG-H870)
* Fenix version: 5.2.0 (Build #21701706)

**Comment by TrianguloY** [comment] 2020-09-08 19:36
I want to raise awareness of this issue. This also happens if you switch apps and firefox is suspended in the background, or even if you simply turn the screen off for a while (basically when Android decides to suspend the app). Note that the app is not closed, only suspended.

On firefox fennec this doesn't happens, the tab is also reloaded but all the draft text is restored (even the scrolling position). On chrome the content is restored too.

This has happened to me several times already here on Github when simply turning the screen off, and losing the comment I was writing. And it is one of those bugs that makes you switch browsers due to desperation.

**Comment by ekager** [comment] 2020-12-17 21:43
Closing as dupe of https://github.com/mozilla-mobile/fenix/issues/12731 please comment your current experiences there

**Closed by ekager** 2020-12-17 21:43 UTC
Labels: needs:triage, 🐞 bug
