### ISSUE TITLE
FNX-4832 ⁃ Library Sign in to Sync

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1155] opened 2019-03-22 23:08 UTC
As a user with a FxA, I want to sign in to sync so I will be able to access things I've saved on other devices and get access on those devices to the things I've saved in Fenix

### Acceptance Criteria (Added by PM)
I can see the option to  log in to my Firefox Account
I can successfully sign in to my Firefox Account
When I am signed in to Fenix, I can view bookmarks and history from other devices
When I am signed in to Fenix, I can sync bookmarks and history from Fenix to other devices
When I am signed in to other devices, I can view bookmarks and history from Fenix

**Comment by bbinto** [comment] 2019-03-28 21:57
@mheubusch - is this a duplicate of #289?

**Comment by mheubusch** [comment] 2019-03-29 01:34
@bbinto i think so.should i close it or can i delete it?

**Comment by bbinto** [comment] 2019-03-29 12:16
Let's close it

**Closed** 2020-08-11 04:19 UTC
