### ISSUE TITLE
Switch a tab from and to private mode

### ISSUE THREAD

**Issue by leplatrem** [mozilla-mobile/fenix#14617] opened 2020-09-02 14:45 UTC
### What is the user problem or growth opportunity you want to see solved?

Once a tab is opened in a certain mode, it is very difficult to open it in the other mode.

Before, with both Firefox and Focus, it was easier to switch a page between the two mode since they were two distinct applications.

#### I'm in the normal mode

1. I open a link...
2. The webpage is full of undesirable content (cookies accept etc.). I decide to re-open it in *private* mode to be able to accept everything, knowing it will be erased.
3. I can't. In the share menu, I don't see *Firefox private mode* (where *Focus* would have been). For an unexplained reason, I also don't see *Copy link URL* either.
4. I have to copy URL, click on tab switcher, switch mode, open a new tab, go to URL bar, paste and open.

#### I'm in the private mode

1. I open a link...
2. I realize I have an account on this page, and probably a session opened in normal mode. I want to re-open it in *normal* mode to avoid having to login again, with 2Fa, etc.
3. I can't.
4. Same as above.

This is also more impactful if I define the private mode as default.

### Who will benefit from it?

Any user that used to use both Firefox and Focus as two different applications, and were used to switch from one to another with a single action.

**Comment by liuche** [comment] 2020-09-10 00:07
Dupe of #10132

**Closed by liuche** 2020-09-10 00:07 UTC
Labels: needs:triage
