### ISSUE TITLE
FNX-12274 ⁃ [Bug]Crash after opening NoScripts settings

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11358] opened 2020-06-09 08:26 UTC
## Steps to reproduce
1. Install NoScript
1. Open NoScript
1. Enable "Run in Private Browsing"
1. Open NoScript's settings

### Expected behavior
NoScript's settings are properly opened

### Actual behavior
Crash

### Device information
* Android device: 
• OnePlus A3 (Android 6.0.1)
• Samsung Galaxy Tab A6 (A 5.1.1)
* Fenix version: **`Nightly Build 200609 from 6/9`**

### Notes
d2148978-a5e8-4449-8f88-e039f52cd348
android.content.res.Resources$NotFoundException: File res/drawable/ic_readermode_selected.xml from drawable resource ID #0x7f08019d

## * Sentry: https://sentry.prod.mozaws.net/operations/fenix-nightly/?query=03cb9aa1dcbd4e959ca74a6751c3eea5
```
android.content.res.Resources$NotFoundException: File res/drawable/ic_readermode_selected.xml from drawable resource ID #0x7f08019d
at android.content.res.Resources.loadDrawableForCookie(Resources.java:2654)
at android.content.res.Resources.loadDrawable(Resources.java:2554)
at android.content.res.Resources.getDrawable(Resources.java:820)
at android.content.Context.getDrawable(Context.java:459)
at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:2)
at org.mozilla.fenix.browser.BrowserFragment.initializeUI(BrowserFragment.kt:6)
at org.mozilla.fenix.browser.BaseBrowserFragment.onViewCreated(BaseBrowserFragment.kt:1)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:21)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:5)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:53)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:11)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:152)
at android.app.ActivityThread.main(ActivityThread.java:5507)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/$ic_readermode_selected__0.xml from color state list resource ID #0x7f080090
at android.content.res.Resources.loadColorStateListForCookie(Resources.java:2764)
at android.content.res.Resources.loadColorStateList(Resources.java:2713)
at android.content.res.TypedArray.getColor(TypedArray.java:439)
at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1605)
at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1584)
at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:666)
at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:571)
at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1215)
at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1124)
at android.content.res.Resources.loadDrawableForCookie(Resources.java:2644)
... 20 more
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #14: invalid color state list tag gradient
at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:217)
at android.content.res.ColorStateList.createFromXml(ColorStateList.java:201)
at android.content.res.Resources.loadColorStateListForCookie(Resources.java:2760)
... 29 more
```

► Video
![20200609-111940](https://user-images.githubusercontent.com/51314259/84124346-c3a32080-aa43-11ea-8f98-80c387647683.gif)

Same stack trace as in #11357

**Comment by Amejia481** [comment] 2020-06-09 20:01
I think the cause of the crash is  https://github.com/mozilla-mobile/fenix/issues/11357, I think we could close this one. Please feel free if https://github.com/mozilla-mobile/fenix/issues/11357 doesn't fix the issue.

**Closed** 2020-08-11 03:53 UTC
Labels: Feature:WebExtensions, S2, b:crash, needs:triage, 🐞 bug
