### ISSUE TITLE
[Bug] tab count cut off

### ISSUE THREAD

**Issue by ueen** [mozilla-mobile/fenix#20248] opened 2021-07-05 11:16 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Actual behavior
<img src = https://user-images.githubusercontent.com/5067479/124463340-0b08f700-dd93-11eb-911e-b142adc2f078.png width = 40%>

### Device information
Pixel 4 5G
* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox) 8.9.1.1

**Comment by Nickoriginal** [comment] 2021-07-05 12:29
Hello!
**Firefox 89.1.1**
Not _reproducible_ on:
**Samsung Galaxy A20s** (Android 10)
**Samsung Galaxy J2 Prime** (Android 6.0.1)
<img src = https://user-images.githubusercontent.com/85299944/124471375-78258800-dda5-11eb-9650-d444fc1b9192.jpg width = 45%>
Please, name **your device model and vendor** and **Android version** to clarify the problem.

**Comment by ueen** [comment] 2021-07-05 12:49
Only happens sometimes (not sure when exactly)

Device is (as stated above) Pixel 4 5G with latest Android 11

**Comment by LaurentiuApahideanSV** [comment] 2021-07-05 12:49
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/16527. I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-07-05 12:49 UTC
Labels: needs:triage, 🐞 bug
