### ISSUE TITLE
[Bug]: "Clear Cookies and Site data" option NOT displayed [ Version: 98.1.1 ]

### ISSUE THREAD

**Issue by Siva981** [mozilla-mobile/fenix#24155] opened 2022-03-08 18:37 UTC
### Steps to reproduce

1. Test with a device that runs Firefox For Android version 98.0 or higher.

2. Visit any website. 

3. Click the lock icon on the address bar at the top or bottom.

4. Verify if there are any options listed below the "Enhanced Tracking Protection" option. 

### Expected behaviour

A "Clear Cookies And Site Data" option should be displayed below the "Enhanced Tracking Protection" option, as outlined in Release Notes and implemented in Firefox For Android versions 98.0 and higher. ( Related Issue: #9294 ) 

### Actual behaviour

The "Clear Cookies And Site Data" option is not being displayed below the "Enhanced Tracking Protection" option for any website.

### Device name

Swipe Elite Plus (manufactured in India)

### Android version

Android 5.0.2

### Firefox release type

Firefox

### Firefox version

98.1.1

## Version Information 

98.1.1 (Build #2015866891), a44eb55a9+
AC: 98.0.11, 2250f94195
GV: 98.0-20220304153049
AS: 91.0.1 

2022-03-05T01:54:32.258028

## Screenshots 

![ocr_screenshot_1646763137](https://user-images.githubusercontent.com/44178186/157302966-ee66f41d-3231-4266-8798-70a46b27f72a.png) 
.
![ocr_screenshot_1646763221](https://user-images.githubusercontent.com/44178186/157303030-0cf35b4a-9c0b-4932-8073-a504666383b6.png)

**Comment by kbrosnan** [comment] 2022-03-08 19:21
Looks like this is an error on our end. It will be in v99. Updating release notes.

**Comment by Siva981** [comment] 2022-03-09 00:39
You might also want to update the <b>What's New</b> page. 

https://support.mozilla.org/en-US/kb/whats-new-firefox-android 

It has the following text: 

## Clear cookies and website data for a single domain

You can [ delete your cookies and website data for a single domain](https://support.mozilla.org/en-US/kb/clear-cookies-and-website-data-single-domain-android) in Firefox for Android, without losing your logins for other domains.

**Comment by j-r9** [comment] 2022-03-16 12:23
This is not unique to very old versions of Android.
I am having the same issue in Daylight 98.2.0 on a Samsung A20 running Android 11.

**Comment by Siva981** [comment] 2022-03-17 00:46
> This is not unique to very old versions of Android. I am having the same issue in Daylight 98.2.0 on a Samsung A20 running Android 11.

.
I have edited the <b>Steps to reproduce</b> section and removed references to Android 5.0.

**Comment by koritime** [comment] 2022-03-20 20:42
Also experienced in 98.3 (3/13)
- from a Samsung Galaxy 21 running 12.0
![Screenshot_20220320-132604_Firefox](https://user-images.githubusercontent.com/101996215/159185163-46dc1150-2d8e-4d8b-a2f1-abc7414f722a.jpg)

**Comment by cadeyrn** [comment] 2022-03-20 22:48
>  I am having the same issue in Daylight 98.2.0 on a Samsung A20 running Android 11.

> Also experienced in 98.3 (3/13)

Please see the previous comments:

> Looks like this is an error on our end. It will be in v99.

**Comment by SoftVision-LorandJanos** [comment] 2022-03-28 09:24
This issue is reproducible on 98.3.0 as the latest Release version.
However as mentioned above, it is not reproducible on 99 and 100.
Tested with the:
- Latest Beta (99.0.0-beta5).
- Latest Nightly 100.0a1 (2022-03-28).

Device used: Oppo Reno 6 (Android 12).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-03-28 09:24 UTC
Labels: 🐞 bug, needs:triage
