### ISSUE TITLE
Bookmark keyword support - awesomebar navigation

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#12099] opened 2020-06-29 19:06 UTC
On desktop and iOS browsers we have support for bookmark keywords. It allows setting a "keyword" for a bookmark, and then navigating to that bookmark by typing that keyword into the url/awesomebar.

We have support for syncing the keywords already via a-s, so we can implement the awesomebar part of this already. (depends on https://github.com/mozilla-mobile/android-components/issues/7558).

Another part to this is to allow editing keywords from Fenix. Currently, we don't have storage APIs for this at all. I've split that into a [separate issue](https://github.com/mozilla-mobile/fenix/issues/12100).

**Comment by tanriol** [comment] 2020-06-30 00:31
Let's mention on this bug that (at least on desktop) bookmark keywords also support placeholders used for search. Furthermore, the built-in context menu option "add a keyword for this search" does exactly that, so probably a number of people use custom search via bookmark keywords.

**Comment by Coffeeling** [comment] 2020-08-10 12:33
Sync of keyword searches via bookmarks is definitely a big use case for me, and amazingly convenient in any case.

**Comment by toupeira** [comment] 2020-08-12 17:48
A few more notes on desktop behaviour:

- When entering a keyword without a value, the `%s` is removed from the bookmark URL.
- When entering a keyword and values for a bookmark that doesn't have a `%s`, the keyword is ignored and the input is treated as a normal search (see https://bugzilla.mozilla.org/show_bug.cgi?id=1435060).

**Comment by ccoenen** [comment] 2020-09-01 13:57
In Firefox for Android before 79, one could have bookmarks with a shortcut/keyword that would auto-fill into a URL in the same way this still works on the desktop. I have a bunch of shortcuts with this set up:

* `xkcd workflow` -> https://duckduckgo.com/?ia=web&q=site%3Axkcd.com+workflow
* `y astley` -> https://www.youtube.com/results?search_query=astley&search_type=&aq=f&oq=
* `wp shortcut` -> https://en.wikipedia.org/wiki/Special:Search?search=shortcut&ns0=1
* ... and so on. You get the idea.

This is immensely useful, _especially_ on mobile where an additional page load is time-consuming and where screen space is limited. I have 26 of these set up, and I use 10 _very_ regularly and another 10 every now and then. I _really_ would like this feature re-added to Firefox on Android.

(yes this screenshot is from the desktop version, it only goes to illustrate the amount of quick searches I have set up)
![proof of the 26 shortcuts I have set up on desktop](https://user-images.githubusercontent.com/124909/91824237-b9f01a00-ec3a-11ea-9869-64eb0cbecf7d.png)

needless to say, I would _really_ like those keywords / shortcuts back on my mobile phone as well :-)

**Comment by tmo7452** [comment] 2020-09-01 15:20
Same, and they are a core part of how I access some frequent sites:

`wp` = http://en.wikipedia.org/w/index.php?title=Special%3ASearch&search=%s
`yt` = https://www.youtube.com/results?search_query=%s
`gm` = https://www.google.com/maps/search/%s
`r` = https://old.reddit.com/r/%s
`az` = https://smile.amazon.com/s/ref=nb_sb_noss_1?url=search-alias%3Daps&field-keywords=%s
`ebay` = https://www.ebay.com/sch/?_nkw=%s

in addition to a ton of more niche sites, mostly fan wikis. I've been doing it this way for I think at least 8 years? This is even more important on mobile to reduce the total number of taps and swipes when I know exactly where I am going.

**Comment by j-s-a-m** [comment] 2020-09-03 06:26
The two tickets (#12099, #14327) linked by @hwinnemoe to #14570 are less explicit than #14337 ("[Bug] Smart keywords no longer work"), #14570 ("Firefox for Android 79.0.5 : Keyword searches are broken / Make keyword searches have highest priority again") and #14571 ("[Bug] 79 removed the "keyword" functionality from bookmarks - I would like it back"),

because they do not mention that Firefox for Android 79.0.5 has broken a functionality that has been working perfectly before. #12099 is in fact a **feature request** about editing keywords, #14327 is an **investigation ticket** about exposing APIs.

The linked tickets may be about a relating topic (keyword searches), but I do not consider them to be real duplicates of the aforementioned **bug tickets**.

I add this comment because I hope that this bug gets the priority it deserves.

**Comment by treestryder** [comment] 2020-09-19 01:49
Since its early days, my favorite feature of Firefox has been its Bookmarks. In particular the keyword and search feature (I have 51 setup).

I feel like, Bookmarks have been losing love by Mozilla and have even been hidden in a way. Like someone has a crazy notion that EVERYONE just "Googles" their way around the web.

**Comment by jnbooth** [comment] 2020-09-21 01:25
This missing feature is the only reason I'm still using the old Firefox.

One more note on desktop behavior, since no one else brought it up: the wildcard pattern has two forms.

**Comment by Mugurell** [comment] 2020-10-06 09:19
Bookmark keywords will be migrated to custom search engines.
Bugzilla ticket tracking the work being done on Desktop - https://bugzilla.mozilla.org/show_bug.cgi?id=1653261
Closing this ticket as such.
Will open new ones for going with custom search engines also once we have more details.

**Closed by Mugurell** 2020-10-06 09:19 UTC
Labels: E3, Feature:Bookmarks, Feature:FennecTransition, Feature:Toolbar, hershey, needs:ac

**Comment by ccoenen** [comment] 2020-10-06 15:22
Not a fan of this change. But I'll take it over there.

**Comment by muxator** [comment] 2020-10-26 09:57
> Bookmark keywords will be migrated to custom search engines

@mugurell: keyword searches has been a productivity boost for many advanced users for a long time. During that time, it peacefully coexisted with custom search engines with no clashes.

Is the decision process behind these sort of changes open? I'd like to know where's the rationale for this, since from my POV this simply seems a change that might alienate advanced and longtime users.

Also: is there the possibility of contributing code changes to restore this functionality? Under what conditions would such changes be considered for acceptance?

**Comment by rybak** [comment] 2020-10-26 10:10
> I'd like to know where's the rationale for this

My best guess as an outside observer is that one of the recent releases of Firefox for Android included a big rewrite of the code base. Such rewrites always mean sacrifices of features. In this particular case, the bookmark keywords were sacrificed for whatever reason. The root cause: most likely lack of time, possibly also exacerbated by technical difficulties of fitting an old feature with the new architecture.

**Comment by muxator** [comment] 2020-10-26 10:31
Hi @rybak, this is a possible explanation, yes. It's funny because I grew up reading a [Joel on Software's blog entry](https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/) and thinking that big software rewrites are dangerous territory. Funnily, his example was about a browser, too (Netscape).

Anyway, looking at https://github.com/mozilla-mobile/fenix/pull/14957/files (a PR by @mugurell which apparently aimed to reintroduce the keyword search feature), the technical effort _per se_ would not be too high.

This seems more like a product-level decision to me: there is this feature which is only used by advanced users, some metric shows us that it is not important to keep it, and so we are going to sacrifice it in the rewrite.

I am curious about the metric and the product-level decision. This may influence my perception of where the browser is going more than the specifics of this feature.

**Comment by lilydjwg** [comment] 2020-10-26 10:48
I'm thinking about setting up a website to do this (like DuckDuckGo's bang searches, but customized. But there's a lot more work to redo (user accounts, syncing, encryption, etc).

**Comment by muxator** [comment] 2020-10-26 11:04
@lilydjwg, while the idea could be interesting, we are talking about a _client side_ feature here.

Users could configure their browser to immediately craft a URL with custom content. This was a productivity boost that went well behind search engines. I fear hitting a third party service could be a whole different thing.

Show the map of a specific place:
```
https://www.openstreetmap.org/search?query=%s (and set "map" as keyword for "Open Street Maps")
```
Usage: <kbd>Ctrl</kbd> + <kbd>L</kbd>, `map colosseum`, <kbd>Enter</kbd> -> Map of the specific place


Translate a sentence from English to Portuguese:
```
https://translate.google.com/?sl=en&tl=pt&text=%s (and set "e2p" as keyword for "English to Portuguese")
```
Usage: <kbd>Ctrl</kbd> + <kbd>L</kbd>, `e2p this is a sentence`, <kbd>Enter</kbd> -> Translated sentence

There are no external services involved. You directly access the piece of information you want. The web feels almost like an API. This is something that needs to be implemented client-side (and synced across devices, and advertised).

**Comment by lilydjwg** [comment] 2020-10-26 11:12
Yes I know and I use it every day on my desktop (used to use it on my phone too). I mean to build a default search engine that recognize such keywords and then redirect to the desired site.

**Comment by lilydjwg** [comment] 2020-10-26 12:15
I find there is a [Custom Search Engine](https://addons.mozilla.org/firefox/addon/custom-search-engine/) addon, which is only slightly more complicated than Firefox's keyword search, but I suppose the user needs to sync search engines themselves.

**Comment by michele-bs** [comment] 2020-10-26 22:35
Keyword feature is **so precious**: its removal, or its migration to the Search Engines, sounds like an inexplicable idea.

Indeed, keywords work not only with the Search Engines, but - equally if not more - as plain shortcuts to our favourite webpages.

For example, I type **_wh_** in the URL bar to open WhatsApp Web (https://web.whatsapp.com/), **_meb_** to open the "My eBay" page (http://my.ebay.it/), **_thb_** to open the page of mozillaZine with a list of all the topics I am subscribed to (http://forums.mozillazine.org/ucp.php?i=main&mode=subscribed), and so on. This has **_nothing_** to do with Search Engines: a keyword applied to a bookmark makes it easily reachable, most of all when the bookmarked URL is complex and hard to remember, though frequently visited.

Keywords to Search Engines (%s URLs) and keywords to bookmarks are different features that coincide only at times: it's a fact that a keyword assigned to a Search Engine and a keyword assigned to a simple Bookmark seems to be the same in Firefox: but their usefulness is manifold.

Moreover, to manually create a bookmark for a %s-shaped URL makes it possible to create Search Engines in a way that is more accurate than the automatic "Add a keyword for this search" command.

**Please keep** the **traditional keywords feature** also in fenix.

Please.

**Comment by boizoe** [comment] 2020-10-28 09:32
Exactly, traditional keyword shortcuts was a great feature. Custom Search
engines is not a replacement.

Please keep them

--
brgds
Max Vorontsov
openpgp4fpr:d8ef660331fb6c091fa1d303274166cb6c93e897

**Comment by j-s-a-m** [comment] 2020-10-28 10:13
Just as a short, well-intentioned feedback: I copied the apk of the good old version 68.10.1 from another Android smartphone to all my Android devices and disabled automatic updates, so I can continue to use the bookmark keyword search feature. This feature is absolute key for me, it's in fact the feature I use most with Firefox for Android.

**Comment by muxator** [comment] 2020-10-30 13:20
The community is clearly concerned about the direction Firefox for mobile is taking. Does someone in this thread know if there is a place where this discussion about keeping the bookmark functionality can be hold?

Moreover, since it seems that a decision has already taken place: in the future it would be better if a wider consensus could be established _in advance_ for these UX changes.

Where is a community member supposed to go in order to inform himself? Was there a blog post somewhere? A mailing list entry? A steering committee? How to reach them?

**Comment by michele-bs** [comment] 2020-11-30 18:28
I have the greatest respect for all the fenix programmers, and I know that it's not easy to satisfy all the requests.

But I wonder if restoring keywords would be really so difficult or problematic... It doesn't seem so compromising, this is a little though very useful feature that honestly I don't want to lose.

Firefox for Android is not the same as before; I can't imagine that this feature has been set aside definitively. It's incomprehensible.

What can we do to make our voice to be listened?

I could... pay for it.

:-|

**Comment by kbrosnan** [comment] 2020-12-02 00:39
Desktop is looking at removing keywords. https://github.com/mozilla-mobile/fenix/issues/12099#issuecomment-704143064 there is nothing else the Fenix team can do to deliver this feature.
