### ISSUE TITLE
[Bug] Mozilla force close

### ISSUE THREAD

**Issue by JeelsBoobz** [mozilla-mobile/fenix#16910] opened 2020-12-08 02:27 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open Mozilla Fenix, but force close
Log: https://del.dog/vyrettunar

### Device information

* Android device: Android 10
* Fenix version:

**Comment by mcarare** [comment] 2020-12-08 13:25
Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/16886.

**Closed by mcarare** 2020-12-08 13:25 UTC
Labels: b:crash, needs:triage, 🐞 bug
