### ISSUE TITLE
FNX-4360 ⁃ Delete all site data for one site only

### ISSUE THREAD

**Issue by Dischi** [mozilla-mobile/fenix#10537] opened 2020-05-09 08:08 UTC
### Why/User Benefit/User Problem
Currently I can only delete all site data. That is too much, sometimes I only want to delete the data of the current site. This is possible for the desktop Firefox

I suggest an option when clicking on the lock icon.

And BTW, Firefox Preview is a great improvement.

**Comment by cadeyrn** [comment] 2020-05-09 09:20
Duplicate of #10363.

**Closed** 2020-08-11 00:59 UTC
Labels: needs:triage
