### ISSUE TITLE
 Firefox for Android 84.0+  - scrolling stutters in  Mali-G GPU series

### ISSUE THREAD

**Issue by SuSpoiled** [mozilla-mobile/fenix#19351] opened 2021-05-02 20:02 UTC
## Steps to reproduce
Scrolling and then page lagging.
### Expected behavior
In  Firefox for Android 84.0, Mali-G GPU series support has been updated and should achieve better performance.
### Actual behavior
quickly scrolling by flicking a page, there's something weird with its inertia, with some stutters when the page is slowing down.
Through the ufotest test, we found that the maximum frame rate is reached when scrolling, and the frame rate quickly decreases to about 50fps after stopping scrolling.
The problem no longer occurs after turning on the phone's performance mode.But in normal mode, the problem occurs.
### Device information
Samsung Mali-G GPU Devices,Huawei Mali-G GPU Devices.
* Android device: 10
* Fenix version: 84+

Is there a feature that enters power saving mode when not touching the screen, and can it be turned off?

**Comment by cadeyrn** [comment] 2021-05-03 06:04
Just to be clear: With Firefox 84+ you want to say that the problem started in Firefox 84 and it still exists in Firefox 88?

**Comment by Mikaka27** [comment] 2021-05-03 09:08
He could mean that, webrender was enabled on Mali G gpus on firefox 84, and remain enabled.

**Comment by SuSpoiled** [comment] 2021-05-03 11:35
> 
> 
> Just to be clear: With Firefox 84+ you want to say that the problem started in Firefox 84 and it still exists in Firefox 88?

Yes, it started at 84 and still exists at 88.

**Comment by SuSpoiled** [comment] 2021-05-03 11:36
> He could mean that, webrender was enabled on Mali G gpus on firefox 84, and remain enabled.

Yes, switching to software rendering does not have this problem.
So I suspect it's a power saving feature of the webrende.

**Comment by amedyne** [comment] 2021-05-03 14:37
Tagging @jamienicol from gfx team, looks like another Mali gpu driver bug.

**Comment by jamienicol** [comment] 2021-05-04 17:39
Hi @SuSpoiled 

We did definitely have a bug where we incorrectly calculated the scroll offset on some frames, leading to a stutter especially when the scroll was slowing down. However, this should have been fixed in 88: https://bugzilla.mozilla.org/show_bug.cgi?id=1658205

Is it possible that you saw this from 84 to 87, but is now fixed in 88? If you still see it in 88, then it's possible we have another similar bug. Does it still occur on Firefox nightly? Would you be able to record a video of it occurring?

For the ufo test, are you able to capture a performance profile using the firefox profiler?

**Comment by SuSpoiled** [comment] 2021-05-05 09:10
> 
> 
> Hi @SuSpoiled
> 
> We did definitely have a bug where we incorrectly calculated the scroll offset on some frames, leading to a stutter especially when the scroll was slowing down. However, this should have been fixed in 88: https://bugzilla.mozilla.org/show_bug.cgi?id=1658205
> 
> Is it possible that you saw this from 84 to 87, but is now fixed in 88? If you still see it in 88, then it's possible we have another similar bug. Does it still occur on Firefox nightly? Would you be able to record a video of it occurring?
> 
> For the ufo test, are you able to capture a performance profile using the firefox profiler?
@jamienicol Sorry, my native language is not English.
https://drive.google.com/drive/folders/12gxFKMSli31R1neab3rheYfnd8-U4p-X
https://share.firefox.dev/2RoCEIW
Recording the screen will be limited to 60fps. FireFox88 will reach maximum speed when touching the screen, but performance drops when not touching the screen. Refer to chrome, chrome will always keep the maximum performance. It still occur on Firefox nightly.
I don't know how to use firefox profiler, so I captured a snippet. I don't know if it's useful.
One thing is strange. Turn the phone on "performance mode" and the problem will not occur. But in "normal mode", the software rendering will not have this problem either.

**Comment by Zaotar** [comment] 2021-05-10 18:32
I can confirm  this issue.
I have Huawei P Smart 2019, running Android 10. I use Firefox 89.0.0-beta.5
Turning on phone Performance  mode addresses the issue

**Comment by mcomella** [comment] 2021-05-12 20:41
> One thing is strange. Turn the phone on "performance mode" and the problem will not occur. But in "normal mode", the software rendering will not have this problem either.

That's curious.

> I can confirm this issue.
> I have Huawei P Smart 2019, running Android 10. I use Firefox 89.0.0-beta.5
> Turning on phone Performance mode addresses the issue

@jamienicol It looks like this may still be an issue in Firefox 89.

**Comment by jamienicol** [comment] 2021-05-13 08:30
Yep, can reproduce on my Mali-G71.

The profile doesn't look like we're being overwhelmed, so it might be a frame scheduling issue or something like that.

If you move the bug to bugzilla I'll look in to it further :)

**Comment by jamienicol** [comment] 2021-05-13 10:55
> One thing is strange. Turn the phone on "performance mode" and the problem will not occur. But in "normal mode", the software rendering will not have this problem either.

In addition to this, as soon as I start profiling firefox, it also jumps up to a smooth 60FPS. And even more bizarrely, if I pull down the notification shade a wee bit, but basically the full webpage is still rendering in the background, it also jumps to 60FPS. I wonder if both of those things somehow up the CPU frequency, like performance mode does.

**Comment by SuSpoiled** [comment] 2021-05-13 11:12
> 
> 
> > One thing is strange. Turn the phone on "performance mode" and the problem will not occur. But in "normal mode", the software rendering will not have this problem either.
> 
> In addition to this, as soon as I start profiling firefox, it also jumps up to a smooth 60FPS. And even more bizarrely, if I pull down the notification shade a wee bit, but basically the full webpage is still rendering in the background, it also jumps to 60FPS. I wonder if both of those things somehow up the CPU frequency, like performance mode does.

This happens only with Firefox.Other more popular browsers are able to maintain at 60FPS or the highest refresh rate FPS..
Even Firefox has a higher CPU frequency than Chrome normally when problems occur.
![20210513190729](https://user-images.githubusercontent.com/15728705/118117728-919df980-b41e-11eb-9174-f110f072981b.jpg)
![20210513190744](https://user-images.githubusercontent.com/15728705/118117743-95ca1700-b41e-11eb-873f-a7be2d75f1d0.jpg)

**Comment by jamienicol** [comment] 2021-05-13 11:14
@SuSpoiled Could you please take another profile, but this time select "Firefox Graphics" in the settings option, like in this photo:

![Screenshot from 2021-05-13 12-11-43](https://user-images.githubusercontent.com/1907488/118118194-84fcaf80-b3e4-11eb-861e-dde48528d05d.png)

**Comment by SuSpoiled** [comment] 2021-05-13 11:30
> 
> 
> @SuSpoiled Could you please take another profile, but this time select "Firefox Graphics" in the settings option, like in this photo:
> 
> ![Screenshot from 2021-05-13 12-11-43](https://user-images.githubusercontent.com/1907488/118118194-84fcaf80-b3e4-11eb-861e-dde48528d05d.png)

@jamienicol https://share.firefox.dev/3ybHx9c
Strangely, the frame rate is high when capturing, rising from about 50FPS to about 58FPS.

**Comment by jamienicol** [comment] 2021-05-13 11:57
Yes, I see the same thing. It seems to boost the CPU frequency...

**Comment by mcomella** [comment] 2021-05-19 20:38
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1711987

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by mcomella** [comment] 2021-05-19 20:38
> If you move the bug to bugzilla I'll look in to it further :)

Done!

**Closed by mcomella** 2021-05-19 20:38 UTC
Labels: eng:performance
