### ISSUE TITLE
FNX-4714 ⁃ Full screen mode should stay immersive on rotation and configuration changes

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#1006] opened 2019-03-13 18:00 UTC
## Steps to reproduce
1. Load a Youtube Video.
1. Press the full screen button.
1. Rotate Fenix.

### Expected behavior
Fenix remains in immersive mode with the status bar hidden.

NOTE: However, we do not want to keep immersive mode after the browsing session is saved.

### Actual behavior
Fenix is mostly full screen after rotation, but not immersive. The status bar appears.

### Device information
* Android device: Pixel 3, 9.0
* Fenix version: Nightly, Build #10701328

**Comment by pocmo** [comment] 2019-03-19 17:58
@jonalmeida Is that an AC bug? Since that state is on Session and immersive mode is started from an AC feature, right?

**Comment by jonalmeida** [comment] 2019-03-20 02:11
@pocmo it isn't, but maybe it should be? The EngineSession isn't lifecycle aware so while the engine still stays in fullscreen mode, the view needs to check it's state OR be notified of the engine session should update the view when a lifecycle change takes place and stay in immersive mode. The latter which seems a bit wrong to me.

I'm not sure why it leaves immersive mode on rotation (Android system behaviour?).

We can see the current behaviour has Gecko stay in fullscreen mode on rotation even after immersive mode is exited.

**Comment by pocmo** [comment] 2019-03-20 12:38
@jonalmeida Currently `FullScreenFeature` only reacts to `Session.fullScreenMode` changes. If the feature get initialized and `Session.fullScreenMode` is already true: Should it start fullscreen mode immediately?

**Comment by jonalmeida** [comment] 2019-03-20 15:43
> Should it start fullscreen mode immediately?

Do you mean should the `fullScreenChanged` callback in the feature be fired? It's in the callback that immersive mode is entered/exited.

I tested the different combinations of what we're seeing:

| Situation            | `Session.fullScreenMode`                    | callback executed |
| -------------------- | ------------------------------------------- | ----------------- |
| Enter fullscreen     | true                                        | true              |
| Rotate in fullscreen | true (unchanged; gecko still in fullscreen) | **false**         |
| Exit fullscreen      | false                                       | true              |

Looking at Fennec and Chrome's implementation, entering fullscreen mode forces rotation into landscape mode. This might be a better solution.

**Comment by colintheshots** [comment] 2019-03-20 16:05
Keep in mind, rotation is not the only configuration change. We wouldn't want to pop out of fullscreen when night mode activates, for example.

Also, not all videos are landscape. Landscape is simply a good default.

**Comment by jonalmeida** [comment] 2019-04-03 17:58
UX mentioned that when entering fullscreen mode we should force landscape mode. 

The `FullScreenFeature` has onChanged listener which will allow the app to know when to do this - so it would make this a non-issue for a-c.

#1343 better captures the changes that need to go in, but leaving this open for @vesta0 to decide.

cc: @lime124

**Comment by vesta0** [comment] 2019-04-04 01:08
Thanks @jonalmeida

**Comment by colintheshots** [comment] 2019-05-29 08:21
This issue appears to be resolved. Most of the duplicates listed are not actually duplicates. There is another issue where we now appear to leave space for the now missing toolbar.

**Comment by colintheshots** [comment] 2019-05-29 08:31
Actually, it's still changing immersiveness on rotation. Re-opening.

**Comment by ekager** [comment] 2019-07-12 21:01
I'm not seeing this anymore. Adding a QA needed label!

**Comment by jacktose** [comment] 2019-07-14 06:50
Still happening for me in Fennec 68.0 and Fenix 190713 18:02 (Android 8.1.0).

I reported in webcompat/web-bugs#34593 and that was closed as a duplicate of [bug 1555511](https://bugzilla.mozilla.org/show_bug.cgi?id=1555511). Since the issue is in both browsers, is this a duplicate of the Bugzilla bug?

**Comment by abodea** [comment] 2019-07-15 12:49
Hi, @jacktose I have a question regarding your comment, can you check this issue https://github.com/mozilla-mobile/fenix/issues/2527 and see if your comment was meant to be added there? Both issues you mentioned from webcompat and bugzilla are not related to this issue.

**Comment by abodea** [comment] 2019-07-15 13:03
Verified as fixed using the latest build from **`7/15 190715`**.
Please note that the YouTube videos I watched were displayed correctly in full screen mode after rotating the device.
I used the following devices:
**• Google Pixel 3a (Android 9)
• Samsung Galaxy S8+(Android 8)
• Samsung Galaxy S7 (Android 7)
• Huawei Media Pad M3 Lite 10 (Android 7)
• Samsung Galaxy S6 (Android 6.0.1)
• Samsung Galaxy S10+(Android 9)**

**Comment by jacktose** [comment] 2019-07-15 14:01
@abodea, you are correct—too many tabs open.
*This* is fixed for me in Fenix 190714 18:23, Android 8.1.0, Moto G5+.

**Closed** 2020-08-10 18:27 UTC
Labels: P1, b:web-content, eng:qa:verified, 🐞 bug
