### ISSUE TITLE
[Bug][Crash] IllegalStateException: Cannot delete separators

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#6721] opened 2019-11-20 15:29 UTC
We're seeing this crash every now and then: https://sentry.prod.mozaws.net/operations/fenix-nightly/?environment=fenixNightly&query=is%3Aunresolved+Cannot+delete+separators

It seems it's possible to delete bookmark separators in the UI, but it causes this crash.

**Comment by cesarabreu** [comment] 2019-11-20 23:04
@csadilek the link that you sent is private. If you don't mind, could you send it in another way? Maybe I, or another person who also don't have access to that link, could help with it.

**Comment by cesarabreu** [comment] 2019-11-21 01:26
seems to be the same crash reported in #5920

**Comment by csadilek** [comment] 2019-11-21 03:44
@cesarabreu Sure, I can share the crash detail / stack trace here:
```
java.lang.IllegalStateException: Cannot delete separators
    at org.mozilla.fenix.library.bookmarks.viewholders.BookmarkNodeViewHolder$setupMenu$bookmarkItemMenu$1.invoke(BookmarkNodeViewHolder.kt:93)
    at -$$LambdaGroup$ks$MCj5lsY44Wa5HiR35V2pjkG5nuM.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:19)
    at -$$LambdaGroup$js$mppe6B3h9x156wUdLXL-N2k1wq4.onClick(java-style lambda group:199)
    at android.view.View.performClick(View.java:5619)
    at android.view.View$PerformClick.run(View.java:22298)
    at android.os.Handler.handleCallback(Handler.java:754)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:165)
    at android.app.ActivityThread.main(ActivityThread.java:6375)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

That's all we have, but this seems to be a different crash looking at the logcat attached to https://github.com/mozilla-mobile/fenix/issues/5920

**Comment by AfzalivE** [comment] 2019-12-12 05:19
These are the steps to reproduce this crash:

1. On Desktop Firefox, in a folder with some bookmarks already present, create a separator, preferably between two bookmarks.
2. On Fenix Android, open that folder.
3. Delete a bookmark above or below the separator.

Overflow menu is now visible for the separator, allowing user to delete it. When user tries to delete it, it causes a crash.

**Comment by darkwing** [comment] 2020-01-09 19:20
I could not duplicate on current master.  I did, however, notice a sorting issue between what I created on Desktop and what was pulled down to mobile:

<img width="503" alt="Desktop" src="https://user-images.githubusercontent.com/46655/72097789-c3f78e00-32e2-11ea-9f74-2bf9c4ab00bb.png">

![Screenshot_20200109-131819](https://user-images.githubusercontent.com/46655/72097799-c659e800-32e2-11ea-9ae3-8aa2c7b58bd6.png)

**Comment by ekager** [comment] 2020-01-30 15:32
Closing as a dupe of #5920

**Closed by ekager** 2020-01-30 15:32 UTC
Labels: Feature:Bookmarks, P2, b:crash, eng:qa:needed, eng:ready, help wanted, 🐞 bug

**Comment by sv-sdeiac** [comment] 2020-01-31 13:38
Based on https://github.com/mozilla-mobile/fenix/issues/5920#issuecomment-580709431, I'll mark this issue as verified, thanks.
