### ISSUE TITLE
Fenix Login Manager Should Be Able to Fill and Save BasicAuth Account & Password

### ISSUE THREAD

**Issue by longmoon77** [mozilla-mobile/fenix#9257] opened 2020-03-19 19:34 UTC
I hope Account and its Password in BasicAuth will be able chosen to save in data of Firefox and FirefoxSync.
It will make it easy to log in next time.
Finally,the BasicAuth GUI text has not yet been translated to other languages.
![BasicAuth_demo](https://user-images.githubusercontent.com/62339707/86545005-0b8f6780-bf5e-11ea-8d42-bb7490fcad1b.jpg)
![Version](https://user-images.githubusercontent.com/62339707/86545016-1944ed00-bf5e-11ea-9e1a-8a0058c21029.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16331)

**Comment by SS1113** [comment] 2020-07-06 01:46
@lomomcat 


Okay, are you saying that you need to save usernames and passwords in Firefox account (Firefox Sync)? If so Firefox [Lockwise](https://play.google.com/store/apps/details?id=mozilla.lockbox) can do exactly that.


By **BasicAuth**, what do you mean? Do you have steps that I can follow to get this dialogue? 


And the translations happen here: https://pontoon.mozilla.org/projects/android-l10n/ you can choose the language you want to translate and leave a suggestion with your translations of the dialogue you're taking about.

**Comment by lomomcat** [comment] 2020-07-06 03:13
@SS1113 **Firefox PC** Can save the username and password of the **BasicAuth** which is in a page to Firefox Lockwise.But **_Fenix_** couldn't.

You definitely know what **BasicAuth** is.

[BasicAuth in Wikipedia](https://en.m.wikipedia.org/wiki/Basic_access_authentication)

[BasicAuth in MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication)

[BasicAuth in IETF (RFC7617)](https://tools.ietf.org/html/rfc7617)

If you want,you can ask me to show you the **BasicAuth** of my website.

Yours truly.

**Comment by SS1113** [comment] 2020-07-06 03:21
@ekager A request, can you please at least tag this issue with correct labels? It seems this is pending without any notice. I know your team has been very very busy. But the issue is pending without any notice for at least 4 months now. 

Thanks! :)

**Comment by boek** [comment] 2023-01-25 21:20
Closing as a dup: https://bugzilla.mozilla.org/show_bug.cgi?id=1812446

**Closed by boek** 2023-01-25 21:20 UTC
Labels: feature request 🌟, needs:ac, needs:gv, Feature:Logins
