### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by PulkitGupta707** [mozilla-mobile/fenix#13377] opened 2020-08-07 04:35 UTC
## Steps to reproduce
open the link https://forms.gle/RqaDWJP92YguCcXt7

### Expected behavior
should open the page with form
![Screenshot_2020-08-07-09-59-13-17](https://user-images.githubusercontent.com/29430395/89609412-4b03e900-d867-11ea-812f-ef810099523a.jpg)

### Actual behavior
redirect me to google play services on play store.
 
![Screenshot_2020-08-07-10-01-45-16](https://user-images.githubusercontent.com/29430395/89609442-6242d680-d867-11ea-944a-4609d90eb205.jpg)
![Screenshot_2020-08-07-09-58-40-15](https://user-images.githubusercontent.com/29430395/89609446-640c9a00-d867-11ea-8de5-e330e92eb6b2.jpg)

It's working fine on chrome

### Device information
Realme C3 

* Android device: Android 10
* Fenix version: 79.1.0-beta.1 (Build #2015753459)

**Comment by s-ankur** [comment] 2020-08-07 06:56
Duplicate of #13040

**Comment by NotWoods** [comment] 2020-08-07 16:01
Closing as duplicate, thanks for the additional STR!

**Closed by NotWoods** 2020-08-07 16:01 UTC
Labels: needs:triage, 🐞 bug
