### ISSUE TITLE
[Bug]: Finished full screen video prevents device sleep

### ISSUE THREAD

**Issue by ANDMIC** [mozilla-mobile/fenix#25189] opened 2022-05-10 14:58 UTC
Once a video playing has finished in full screen, Firefox keeps the video paused and full screen which prevents the display from turning off / locking.

### Steps to reproduce

1.) Open video on webpage (example: youtube.com)
2.) turn off autoplay
3.) Full screen the video playback
4.) fast forward near the end of video
5.) wait

### Expected behaviour

Once video has finished playing, close full screen so device display sleep settings can turn off display.

### Actual behaviour

Video stays in full screen resulting in the device screen staying on causing screen burn-in and battery drain.

### Device name

Samsung Galaxy s9

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

100.1.1

### Additional information

Confirmed on behavior on second device:

Device name: Galaxy Tab A (2019)
Android Version: 11
Firefox Release type: Firefox
Firefox Version: 100.1.1

Other recently closed issues without action:
[#22662](https://github.com/mozilla-mobile/fenix/issues/22662)
[#20225](https://github.com/mozilla-mobile/fenix/issues/20225)
[#20295](https://github.com/mozilla-mobile/fenix/issues/20295)

**Comment by SoftVision-LorandJanos** [comment] 2022-05-11 04:17
Hi @ANDMIC ! Thanks for your report!
I can reproduce the issue you described, however, as mentioned [here](https://github.com/mozilla-mobile/fenix/issues/20225#issuecomment-873638657) this behavior is intended, that's why the mentioned bugs were closed without action.
Based on this, I will close this ticket.

**Closed by SoftVision-LorandJanos** 2022-05-11 04:17 UTC
Labels: 🐞 bug, needs:triage
