### ISSUE TITLE
[Bug] Top sites do not use full width in landscape mode

### ISSUE THREAD

**Issue by ecsmyth** [mozilla-mobile/fenix#8788] opened 2020-02-26 19:44 UTC
## Steps to reproduce
1. Add top sites until there are two+ rows in portrait mode
2. Rotate the phone to landscape mode

### Expected behavior
Full width of the screen is used to show as many top sites as fit before creating additional rows.

### Actual behavior
![Screenshot_20200227-022958_Firefox Nightly](https://user-images.githubusercontent.com/17688672/75381056-ee021100-588c-11ea-8acc-ab2d3676ac33.jpg)

### Device information
* Android device: Samsung Galaxy S10 Int'l
* Fenix version: Fenix Nightly 200226 build 20571807

**Comment by gabrielluong** [comment] 2020-02-26 22:10
This seems to be a regression from #8719.

**Comment by gabrielluong** [comment] 2020-02-26 22:13
Hi @topotropic, I am wondering what we should expect when we're in landscape mode for Top Sites. Above you can see the changes that was done to force it not expand and match the parent width. 

I have included screenshots from #8719 of the previous behaviour:


![](https://user-images.githubusercontent.com/40264165/75238500-c5fda980-57c9-11ea-8675-a44997332f0d.png)

![](https://user-images.githubusercontent.com/40264165/75238519-cdbd4e00-57c9-11ea-9c50-1135ef5ae507.png)

**Comment by topotropic** [comment] 2020-02-27 09:43
@gabrielluong can we keep the margins and fill up the row until it's full and the break to the next row?

**Comment by mcarare** [comment] 2020-02-28 09:00
@gabrielluong It is not a regression from #8719, it is just the fact that `GridLayoutManager` is hardcoded to show 5 elements per row ( `const val NUM_COLUMNS = 5` in `TopSiteViewHolder` )

**Comment by LaurentiuApahideanSV** [comment] 2020-03-10 12:07
Verified as fixed on Firefox Preview Nightly 200310 (Build #20700607) GV: 75.0a1-20200309091841 using a Motorala G7 (Android 9) and OnePlus 6T (Android 9). When the device is in landscape mode the Top Sites are no longer limited to 5 per row but rather the length available on the screen and there is no large spacing between top sites.

**Closed** 2020-03-10 13:50 UTC
Labels: Feature:HomeScreen, Feature:TopSites, eng:qa:verified, needs:triage, 🐞 bug
