### ISSUE TITLE
[Bug] Capacitance keyboard scrolling on Blackberry KeyOne

### ISSUE THREAD

**Issue by JuDGe3690** [mozilla-mobile/fenix#9149] opened 2020-03-13 18:13 UTC
The BlackBerry KeyOne has a physical keyboard with capacitance, which allows trackpad-like scrolling. This works in the old Firefox Android, but is not working in Firefox Preview Production (v4.0.0) on Android 8.1.0.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16261)

**Comment by JMuGT3** [comment] 2020-07-06 19:47
Same here. It was working very well a few versions ago (on Firefox preview), now not working at all. Tested on Blackberry KeyOne, Key2 and Priv.

**Comment by ekager** [comment] 2020-07-09 16:07
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1651734

**Comment by fluffyemily** [comment] 2020-07-09 16:25
Do you have a more specifc regression range for this, please (we don't have a Blackberry KeyOne to test this on)?

**Comment by agi90** [comment] 2020-07-09 16:25
You can use mozregression to find a regression range. https://mozilla.github.io/mozregression/install.html

**Comment by JMuGT3** [comment] 2020-07-09 19:17
Ok, I've just finished testing almost every version down to 2.3.0. This was the last version in which the keyboard scroll works. Something changed between 2.3.0 and 3.0.0 beta1 that made the scrolling inoperable. 
I hope it helps. If there's anything else I can help with please let me know.

**Comment by colletj** [comment] 2020-08-26 11:30
Same here on Key2. 
Was working but since the upgrade to the latest version (79.0.5 I believe) scrowling using the capacitance keyboard isn't possible anymore.

**Comment by johnb-xp** [comment] 2020-08-27 20:10
Confirmed on my KEY2 as well.

**Comment by Kitteh6660** [comment] 2020-09-01 13:19
Used to work before the update on my Key2 and now it no longer works as of Firefox for Android 79. Can confirm.

**Comment by TheGwakMan** [comment] 2020-09-03 22:52
Same problem with my key2 it's really incapacitating.

**Comment by pvanulden** [comment] 2020-09-13 11:58
KEY2 user here...good to know I am not alone. I would have thought that scrolling on the keyboard and screen generated the same type of scroll message to the app. Strange!

**Comment by johnb-xp** [comment] 2020-09-20 16:02
The settings screen does work with capacitive scrolling, but not the actual browser window.

**Comment by TrinomCZ** [comment] 2020-10-16 16:05
Yes, I can confirm, that scrolling works in the settings menu, but doesn't work on the web pages, where you actually need it.

**Comment by Cguy7777** [comment] 2020-10-23 00:36
I am also a KEY2 user experiencing this. I found [this helpful documentation](https://devblog.blackberry.com/en/2015/11/ready-set-type-developers-guide-to-the-priv-keyboard-part-2) for the Priv, which is another BlackBerry android with a capacitive keyboard. While I don't know for sure if the KeyOne and KEY2 work the same, I'd be surprised if they don't.

According to BlackBerry's documentation:

> If you have custom scrollable views, to provide consistent scrolling behavior, you should ensure that your views handle mouse scroll wheel movement with either an external mouse connected to any Android device or external touchpad that behaves as a pointer device.
>
> You should make sure that:
>
>    - Motion on the scrollwheel moves your view in the same direction as a ScrollView for vertical movement, or as a HorizontalScrollView for horizontal movement.
>
>    - You consider the magnitude of the events; if you move your view the same distance for any mouse scroll event without considering the magnitude, your view is likely to move too fast and not smoothly.

They also state that "without extra development, application UIs built with standard Android™ view containers such as ScrollView...provide scrolling behavior for motion on the touch keyboard", which probably explains why the settings menu works.

**Comment by dcoco1890** [comment] 2021-01-11 15:15
> Yes, I can confirm, that scrolling works in the settings menu, but doesn't work on the web pages, where you actually need it.

I hadn't noticed that, but mine behaves the same way on my KEYone and KEY2

**Comment by flixha** [comment] 2021-06-17 08:43
> I am also a KEY2 user experiencing this. I found [this helpful documentation](https://devblog.blackberry.com/en/2015/11/ready-set-type-developers-guide-to-the-priv-keyboard-part-2) for the Priv, which is another BlackBerry android with a capacitive keyboard. While I don't know for sure if the KeyOne and KEY2 work the same, I'd be surprised if they don't.

For the Blackberry Priv, I can confirm that the capacitance keyboard scrolling also stopped working in the newer versions of firefox, and the latest version where I saw it working was firefox version 68. The Priv is running Android 6.0.1. So that may support your suspicions that the documentation may apply in the same way for the Priv as for the KeyOne and Key2.

**Comment by WikiSteve** [comment] 2021-08-02 15:49
I also just bought a Key2 and can confirm it works in the settings window but not the browser.

**Comment by TheGwakMan** [comment] 2022-01-29 17:07
Still there...like the bug

**Comment by WikiSteve** [comment] 2022-01-29 19:15
> Still there...like the bug

Mozilla had to go out of their way to block keyboard scrolling because it still works in their settings menu.

**Comment by finisi** [comment] 2022-11-11 12:44
Scrolling is still not working on version 106.1.0 (Build #2015909131), 71ca6c1f7+ on KeyOne. However, working well in the settings menu. Come on Mozilla, you can fix this!

**Comment by jonalmeida** [comment] 2023-01-27 22:40
Closing as moved since this has already been filed in BZ-1651734.

**Closed by jonalmeida** 2023-01-27 22:40 UTC
Labels: 🐞 bug, needs:gv, Feature:Browsing
