### ISSUE TITLE
[Bug] Fenix not actually closed after exiting via Quit?

### ISSUE THREAD

**Issue by Jee-Hex** [mozilla-mobile/fenix#18686] opened 2021-03-29 16:42 UTC
## Steps to reproduce

1. (Assuming the `Delete browsing data on quit` option is already enabled) Launch Fenix.
2. Open `about:networking`.
3. Notice a bunch of startup connections (e.g. _firefox.settings.services.mozilla.com_).
4. Close Fenix via `AppMenu > Quit`.
5. Launch Fenix again.
6. Open `about:networking` again.
7. Notice the absence of almost any startup connection.

I am assuming this is related to #17790 because I tend to remove Fenix from Recent Apps screen manually after exiting via Quit. The almost instantaneous load and lack of startup connections are telltale signs. Issue is not reproducible if I force close Fenix via the Recent Apps screen, so I have for now resorted to deleting browsing data manually and then force closing Fenix. 

This might be an issue when users expect "Quit" to actually mean completely closing the app (e.g. #18103)?

### Device information

* Firefox for Android version: 
Nightly 210326 17:01 (Build #2015800971)
AC: 75.0.20210324143047, 0bc7edf4a
GV: 89.0a1-20210323094659
AS: 74.0.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10169)

**Comment by abodea** [comment] 2021-03-30 15:11
Hello, I tried to reproduce this issue but I'm not exactly sure what do you mean by `Fenix not actually closed after exiting via Quit?`
Because after I closed it via `Quit` button, when I re-launched Fenix everything was gone.
On the `about:networking` were displayed few websites after launching regarding DNS WebSockets.
Also after tapping the `Quit` button Fenix was not displayed in recent apps anymore.
Can you please provide more information and also, your device?

**Comment by Jee-Hex** [comment] 2021-03-30 18:11
Apologies. I should clarify that this was tested in airplane mode and by `about:networking` I meant `about:networking#http`. I have also removed all Top Sites in the new tab page, so please discount anything that looks likes a favicon fetch.

This is essentially the same issue as described in https://github.com/mozilla-mobile/fenix/issues/17790#issuecomment-808726463.

**Comment by opusforlife2** [comment] 2021-04-05 20:02
> This might be an issue when users expect "Quit" to actually mean completely closing the app 

Absolutely. If the Quit + Swipe from Recents combo is replaced by just Quit, it will surely be a usability increase. That is what the Quit button should be doing anyway.

**Comment by Mugurell** [comment] 2021-04-19 05:32
@pocmo There is a scenario where this is needed - https://github.com/mozilla-mobile/fenix/issues/18805 though it seems hard to reproduce and a core issue. Since actually fixing that issue may take some time I wanted to ask if the "Quit" button from the menu should also do a `Process.killProcess`.

**Comment by opusforlife2** [comment] 2021-04-22 16:34
> the "Quit" button from the menu should also do a `Process.killProcess`.

#18805 is probably fixed, but this is still worth pursuing for its own sake.

**Comment by opusforlife2** [comment] 2022-02-04 18:24
Further activity has occurred.

**Comment by opusforlife2** [comment] 2022-12-03 05:59
OI.

**Comment by opusforlife2** [comment] 2022-12-08 16:42
OI (x3).

**Comment by opusforlife2** [comment] 2022-12-11 09:39
Oi oi oi!

**Comment by Mugurell** [comment] 2022-12-31 14:19
Reopening for more investigations.

**Comment by csadilek** [comment] 2023-01-09 19:44
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809240

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2023-01-09 19:44 UTC
Labels: 🐞 bug, Feature:MainMenu, qa-triaged
