### ISSUE TITLE
FNX-3433 ⁃ [Bug] Native code crash when trying to navigate to different websites on OnePlus A3 (Android 6.0.1)

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10318] opened 2020-04-30 11:11 UTC
## Steps to reproduce
1. Navigate to Twitter.com

### Expected behavior
Twitter properly loaded

### Actual behavior
The tab crashes

### Device information
* Android device:  OnePlus A3 (Android 6.0.1)
* Fenix version: **`Nightly 200430 06:01 (Build #21210607) 40.0.20200428130031, c5f35b160 GV: 77.0a1-20200427094322 AS: 0.58.1`**

### Notes
❗ Also happens when navigating to:
•  office.com
•  southfront.org 
•  olx.ro

❗ Not reproducible on the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• Nexus 9  (Android 7)
• Samsung Galaxy Tab a 6 (Android 5.1.1)

► Video
![20200430-134912](https://user-images.githubusercontent.com/51314259/80702818-54541b80-8aea-11ea-8765-a4d69175062f.gif)

► Log

```kotlin
04-30 13:43:33.293 1228-1228/? D/GeckoSession: handleMessage GeckoView:LocationChange uri=https://mobile.twitter.com/explore
04-30 13:43:33.300 1228-1313/? D/places_ffi: bookmarks_get_all_with_url
04-30 13:43:33.303 1228-1303/? D/places_ffi: places_note_observation
04-30 13:43:33.312 1228-1228/? I/art: Note: end time exceeds epoch: 
04-30 13:43:33.350 1228-1303/? D/sql_support::conn_ext: Transaction commited after 46.604063ms
04-30 13:43:33.411 1228-1228/? I/art: Note: end time exceeds epoch: 
04-30 13:43:33.411 1228-1303/? D/places_ffi: places_note_observation
04-30 13:43:33.431 1228-1303/? D/sql_support::conn_ext: Transaction commited after 18.880156ms
04-30 13:43:33.549 1228-1303/? D/places_ffi: places_note_observation
04-30 13:43:33.564 1228-1228/? D/GeckoSession: handleMessage GeckoView:StateUpdated uri=null
04-30 13:43:33.564 1228-1228/? W/GeckoSession: No history entries found.
04-30 13:43:33.568 1228-1303/? D/sql_support::conn_ext: Transaction commited after 18.134218ms
04-30 13:43:34.338 1228-1228/? I/art: Note: end time exceeds epoch: 
04-30 13:43:34.338 1228-1303/? D/places_ffi: places_note_observation
04-30 13:43:34.350 1228-1303/? D/sql_support::conn_ext: Transaction commited after 11.492604ms
04-30 13:43:34.598 1298-2490/? I/ActivityManager: Process org.mozilla.fenix.nightly:tab0 (pid 1809) has died
04-30 13:43:34.598 719-719/? I/Zygote: Process 1809 exited due to signal (11)
04-30 13:43:34.598 1298-2490/? W/ActivityManager: Scheduling restart of crashed service org.mozilla.fenix.nightly/org.mozilla.gecko.process.GeckoChildProcessServices$tab0 in 1000ms
04-30 13:43:34.602 1228-1257/? W/GeckoEventDispatcher: No listener for GeckoView:WebExtension:Disconnect
04-30 13:43:34.603 1298-1341/? V/ActivityManager: killProcessGroupAsync took 6 ms for PID 1809 on thread 14
04-30 13:43:34.606 1228-1228/? D/GeckoNetworkManager: Incoming event disableNotifications for state OnWithListeners -> OnNoListeners
04-30 13:43:34.610 1228-1273/? I/Gecko: [Parent 1228, Unnamed thread 7f8e144240] WARNING: waitpid failed pid:1809 errno:10: file /builds/worker/checkouts/gecko/ipc/chromium/src/base/process_util_posix.cc, line 237
04-30 13:43:34.622 1298-2491/? I/ActivityManager: Start proc 2085:org.mozilla.fenix.nightly:mozilla.components.lib.crash.CrashHandler/u0a269 for service org.mozilla.fenix.nightly/mozilla.components.lib.crash.handler.CrashHandlerService
04-30 13:43:34.837 2085-2101/? E/mozac/CrashReporter: CrashHandlerService received native code crash
04-30 13:43:34.838 2085-2101/? I/mozac/CrashReporter: Received crash: NativeCodeCrash(minidumpPath=/data/user/0/org.mozilla.fenix.nightly/files/mozilla/Crash Reports/pending/2ebc5aa3-0ee0-82a4-0ea9-a54a5d469a51.dmp, minidumpSuccess=false, extrasPath=/data/user/0/org.mozilla.fenix.nightly/files/mozilla/Crash Reports/pending/2ebc5aa3-0ee0-82a4-0ea9-a54a5d469a51.extra, isFatal=false, breadcrumbs=[], uuid=be0c9b02-d829-47ef-9cf9-6712ceed779f)
04-30 13:43:34.845 1228-1303/? I/mozac/CrashReporter: Crash report submitted to 2 telemetry services
04-30 13:43:34.847 2085-2101/? I/mozac/CrashReporter: Invoking non-fatal PendingIntent
04-30 13:43:34.847 1298-2822/? I/ActivityManager: START u0 {flg=0x14000000 cmp=org.mozilla.fenix.nightly/org.mozilla.fenix.HomeActivity (has extras)} from uid 10269 pid -1 on display 0
04-30 13:43:34.854 2085-2101/? I/art: System.exit called, status: 0
04-30 13:43:34.854 2085-2101/? I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.
04-30 13:43:34.866 1298-2179/? I/ActivityManager: Process org.mozilla.fenix.nightly:mozilla.components.lib.crash.CrashHandler (pid 2085) has died
04-30 13:43:34.866 1298-2179/? W/ActivityManager: Scheduling restart of crashed service org.mozilla.fenix.nightly/mozilla.components.lib.crash.handler.CrashHandlerService in 1000ms
04-30 13:43:34.876 1298-1341/? V/ActivityManager: killProcessGroupAsync took 0 ms for PID 2085 on thread 14
04-30 13:43:34.899 1298-1714/? D/ConnectivityService: releasing NetworkRequest NetworkRequest [ id=168, legacyType=-1, [ Transports: WIFI Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
04-30 13:43:34.921 1228-1228/? W/GeckoSession: Attempted to close a GeckoSession that was already closed.
```

**Comment by eliserichards** [comment] 2020-04-30 19:10
Closing as duplicate of #9483

**Closed** 2020-08-11 00:28 UTC
Labels: S1, b:crash, 🐞 bug
