### ISSUE TITLE
[Bug] Fonts don't get rendered properly in latest Nightly (210119 17:04)

### ISSUE THREAD

**Issue by Gericop** [mozilla-mobile/fenix#17545] opened 2021-01-20 12:56 UTC
Pages in the latest (210119 17:04, build 2015788299) Firefox Nightly on Android in mobile view don't render fonts properly. See the screenshot for an example of the artifacts on the Firefox Wikipedia page.
Note: when the "Desktop site" option is enabled in the settings, the page is rendered properly. You should not enable it in order to reproduce the bug.

## Steps to reproduce

1. Open the latest nightly on Android
2. Navigate to any webpage

### Expected behavior
Fonts should be rendered properly.

### Actual behavior
Fonts are rendered randomly displaying "smudges" and other artifacts.

### Device information

* Android device: HTC 10, Android 8.0
* Fenix version: 210119 17:04, build 2015788299
 
![Screenshot_20210120-134758](https://user-images.githubusercontent.com/5181621/105177477-045d2f00-5b27-11eb-8f31-eaeb4411fd20.png)

**Comment by cadeyrn** [comment] 2021-01-20 13:11
Duplicate of #17524, which was closed in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1687554.

**Comment by mcarare** [comment] 2021-01-20 14:01
@Gericop Thank you for your report. This issue was already reported so I am closing this issue as a duplicate of #17524.

**Closed by mcarare** 2021-01-20 14:01 UTC
Labels: needs:triage, 🐞 bug
