### ISSUE TITLE
DL fails if "Download" folder is missing

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#5829] opened 2019-10-07 21:06 UTC
Trying to download a file will fail if destination directory is deleted, maybe FF should just create a folder if needed,  or inform the user why downloading cannot proceed.

**Comment by parvinderandroid** [comment] 2020-09-05 08:15
I understand that my #13134 is a duplicate and has been closed because of it, but it was far more detailed. Is there a way to bring that description of the bug here?

And why is it taking so long to fix such a small issue? I really wanna use Firefox as I love the new design but I'm stuck using other browsers because of this.

I tried it on Nightly 200905 06:01 today and the issue is still intact.

Video of the issue - https://i.imgur.com/rWRM7dx.mp4

**Comment by Amejia481** [comment] 2020-09-08 17:32
Sorry about the delay,  we are a small team. we will try to pick the issue as soon as we have some availability. If you are willing to contribute the patch I will glad to help you :)

**Comment by parvinderandroid** [comment] 2020-09-09 00:34
Hey, I am sorry I came out as so entitled earlier. I would love to contribute a patch. Could you please point me in the right direction? I have never made Android apps, but I am good at Java.

**Comment by ccapitalK** [comment] 2020-09-09 00:51
Would this issue be elligible for the good first issue tag? It seems like a fix for this wouldn't require deep understanding of the codebase.

**Comment by Amejia481** [comment] 2020-09-09 14:00
> Hey, I am sorry I came out as so entitled earlier. I would love to contribute a patch. Could you please point me in the right direction? I have never made Android apps, but I am good at Java.

Do not worry :), we have some docs that can help you to get started. Fenix is the UI of multiple underneath projects [Mozilla Android Components (AC)](https://github.com/mozilla-mobile/android-components) and [GeckoView (GV)](https://mozilla.github.io/geckoview/).

The bug is on the [feature-downloads](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/downloads/README.md) component on AC. I think specifically [here](https://github.com/mozilla-mobile/android-components/blob/9d8bcc23c391e69876761262736a56c77e995a20/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L597), where we start to writing to disk and have to check if the folder is there if not we should create it. 

These docs can help you:

- [Getting Involved (Fenix)](https://github.com/mozilla-mobile/fenix#getting-involved)
- [Contributing to AC](https://mozac.org/contributing/)

If you need any additional help just let me know :)

**Comment by Amejia481** [comment] 2020-09-09 14:04
> Would this issue be elligible for the good first issue tag? It seems like a fix for this wouldn't require deep understanding of the codebase.

I agree it could be tagged as good first issue :)
@parvinderandroid, if you want to proceed and take the issue you could assign yourself to the issue, I will tagged it as "good first issue"

**Comment by parvinderandroid** [comment] 2020-09-11 11:14
I tried a lot, but I am not able to build fenix when using `autoPublish.android-components.dir=../android-components` in `local.properties`

I am able to build and run fenix without `local.properties`, but it's failing over one reason or the other when I am trying with `local.properties`.

I don't think I'll be able to do this 😞

**Comment by Amejia481** [comment] 2020-09-11 13:26
Is there any specific error that you are encountering?  Here you can find a more detail guide of how [auto-publication](https://mozac.org/contributing/testing-components-inside-app#testing-local-components-code) works that may bring some lights, another alternative is to [publish manually your Android Component version to Maven Local](https://mozac.org/contributing/testing-components-inside-app#manual-flow-using-a-local-maven-repository-to-test-local-component-code) and set your local Fenix to use it as a dependency.

**Comment by parvinderandroid** [comment] 2020-09-15 05:11
This is what I did:

1. Clean installed Windows 10 2004 19041.450
2. Installed all updates and updated to 19041.508
3. Installed Python 3.8.5 64 Bit
4. Installed Git 2.28.0 64 Bit
5. Set Git global user.name and user.email
6. Installed Android Studio 193.6626763
7. Set Environment Variable ANDROID_SDK_ROOT=C:\Users\parvi\AppData\Local\Android\Sdk
8. Set Environment Variable JAVA_HOME=C:\Program Files\Android\Android Studio\jre
9. Added %JAVA_HOME%\bin to the PATH environment variable
10. Opened a CMD window in C:\Users\parvi\AppData\Local\Android\Sdk\tools\bin
11. Ran sdkmanager.bat --licenses
12. Accepted all 7 Licenses
13. Opened a CMD window in C:\Users\parvi\Downloads
14. Ran Download_and_Build.bat >Batch_File_Log.txt
15. My intention was to direct all output to the text file, but some output was still displayed on the screen that I have attached as a screenshot

Attachments:

Download_and_Build.bat

    @Echo on
    git clone https://github.com/mozilla-mobile/fenix
    git clone https://github.com/mozilla-mobile/android-components
    cd fenix
    echo autoPublish.android-components.dir=../android-components >local.properties
    gradlew clean app:assembleDebug

[Batch_File_Log.txt](https://github.com/mozilla-mobile/fenix/files/5222581/Batch_File_Log.txt)

![Output on Screen](https://user-images.githubusercontent.com/49319914/93168205-f3974980-f73f-11ea-92ef-202e7efadf66.png)

**Comment by Amejia481** [comment] 2020-09-18 14:10
@parvinderandroid sorry for no replying before, it's been a bumping week for me.  I will try to take a look today, I'm not that familiar with dependency substitution ([I normally use maven local that could be an alternative](https://mozac.org/contributing/testing-components-inside-app#manual-flow-using-a-local-maven-repository-to-test-local-component-code)), I will ask to other team members on our chat channel on [#fenix:mozilla.org channe](https://chat.mozilla.org/#/room/#fenix:mozilla.org) and  [#android-components:mozilla.org](https://chat.mozilla.org/#/room/#android-components:mozilla.org), please feel free to join the conversation.

**Comment by kbrosnan** [comment] 2020-09-18 14:40
The space in the android-components folder seems like a possible problem. The line where that is shown is `Could not read script 'C:\Users\parvi\Downloads\android-components \substitute-local-ac.gradle' as it does not exist.`

**Comment by parvinderandroid** [comment] 2020-09-22 11:58
> 
> 
> The space in the android-components folder seems like a possible problem. The line where that is shown is `Could not read script 'C:\Users\parvi\Downloads\android-components \substitute-local-ac.gradle' as it does not exist.`

Thank you so much. This might just do it. I am gonna try it as soon as I can.



> 
> 
> @parvinderandroid sorry for no replying before, it's been a bumping week for me. I will try to take a look today, I'm not that familiar with dependency substitution ([I normally use maven local that could be an alternative](https://mozac.org/contributing/testing-components-inside-app#manual-flow-using-a-local-maven-repository-to-test-local-component-code)), I will ask to other team members on our chat channel on [#fenix:mozilla.org channe](https://chat.mozilla.org/#/room/#fenix:mozilla.org) and [#android-components:mozilla.org](https://chat.mozilla.org/#/room/#android-components:mozilla.org), please feel free to join the conversation.

No problems at all. I have been a little busy too. I am actually in the final year of my CS degree and have a lot of work to do.

**Comment by parvinderandroid** [comment] 2020-09-24 01:10
> 
> 
> The space in the android-components folder seems like a possible problem. The line where that is shown is `Could not read script 'C:\Users\parvi\Downloads\android-components \substitute-local-ac.gradle' as it does not exist.`

Hey. So I removed the space and tried doing the same steps, the only difference being that I tried it in Windows Sandbox this time.

It still failed. I am attaching the Output on Screen and the Batch File Log:

[Batch_File_Log.txt](https://github.com/mozilla-mobile/fenix/files/5272835/Batch_File_Log.txt)


![Screenshot (1)](https://user-images.githubusercontent.com/49319914/94089427-ce39c800-fe30-11ea-80e3-dfbde0ba65b4.png)

**Comment by Amejia481** [comment] 2020-10-27 15:40
This was addressed on https://github.com/mozilla-mobile/android-components/pull/8785 it should be fixed in the next nightly version.

**Comment by Amejia481** [comment] 2020-10-27 15:42
Sorry @parvinderandroid for taking this issue for you, but I had to addressed as the issue was most severe than I initially thought

**Comment by Amejia481** [comment] 2020-10-28 19:37
QA could you help us to confirm if this issue is fixed on nightly. Thanks in advance!

**Comment by parvinderandroid** [comment] 2020-10-29 02:37
> 
> 
> Sorry @parvinderandroid for taking this issue for you, but I had to addressed as the issue was most severe than I initially thought

Hey no problem. This is awesome. What more could I possibly want?

**Comment by parvinderandroid** [comment] 2020-10-29 02:43
> 
> 
> QA could you help us to confirm if this issue is fixed on nightly. Thanks in advance!

I just checked and it's definitely fixed. Thank you so much, you guys are awesome!

Proof - https://i.imgur.com/pphDeFD.mp4

**Comment by AndiAJ** [comment] 2020-10-29 06:56
Hi, **verified as fixed** on the latest **`Nightly Build 201029`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Closed by AndiAJ** 2020-10-29 06:56 UTC
Labels: Feature:Download, P2, eng:qa:needed, good first issue, 🐞 bug
