### ISSUE TITLE
FNX-5144 ⁃ [Bug]Switch to new tab don't work

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#1627] opened 2019-04-14 04:38 UTC
## Steps to reproduce
1. Navigate to a website and open a link from that site in a new tab.
1. Click on the switch button from the snack bar to open the newly created tab.
    1. Expected behavior
On clicking switch button the new tab is opened. 
    1. Actual behavior
No effect on clicking the switch button.
    1. Device information

* Android device: 8.0.0
* Fenix version: 1.0.1915 (Build#11031226
68.0a1-20190408104625)

**Comment by vesta0** [comment] 2019-04-16 21:36
Fixed.

**Comment by vesta0** [comment] 2019-04-17 00:30
Re-opening this issue: after further investigation I noticed that it doesn't work consistently.

**Comment by ekager** [comment] 2019-04-24 22:54
Opened AC issue https://github.com/mozilla-mobile/android-components/issues/2811

**Comment by bsurd** [comment] 2019-04-25 08:58
This is reproducing quite consistently in the build from 4/24 on multiple devices. (Nexus 5, Galaxy S8, Pixel)

This was working without any kind of issues with the build from 4/23 on the above-mentioned devices. Seems to be working fine on an HTC Desire 820 tho.

**Comment by jonalmeida** [comment] 2019-04-25 16:06
From some initial investigation into this issue and I'm able to see the tabs switching in R-B, so it doesn't look like the issue exists in the component.

I'm going to follow through with this issue to see where it lies in Fenix.

**Comment by jonalmeida** [comment] 2019-04-25 19:07
This is an issue where the sessionId is always being set by the HomeFragment.

Please see the comment here for full details: https://github.com/mozilla-mobile/android-components/issues/2811#issuecomment-486799750

**Comment by ekager** [comment] 2019-04-26 00:39
Thanks for the tip @jonalmeida ! @sblatz worked on this today and I think we've gotten it to a pretty good place

**Comment by kbrosnan** [comment] 2019-04-26 06:08
This is looking good for the normal tab to normal tab case and private to private tab. Noting that #1836 is quite noticeable but the tab is correctly placed in private browsing even if the UI is not correct. Tested using a Pixel 3, Pixel 2 XL and Galaxy S6.

**Comment by jonalmeida** [comment] 2019-04-26 14:10
> Noting that #1836 is quite noticeable but the tab is correctly placed in private browsing even if the UI is not correct.

This issue can be fixed without a-c changes by simply observing the selected session now and updating the theme:
```
override fun onSelectedSessionChanged(session: Session) {
  if (session.private) {
    // set private theme
  } else {
    // set normal theme
  }
}
```

**Closed** 2020-08-11 12:18 UTC
Labels: eng:qa:verified, 🐞 bug
