### ISSUE TITLE
OpenSearchDescription import

### ISSUE THREAD

**Issue by h0cheung** [mozilla-mobile/fenix#6753] opened 2019-11-22 17:26 UTC
### Why/User Benefit/User Problem
The search engine editor is too simple and cannot add Auto Complete
### What/Requirements
Add OpenSearchDescription Import
### Acceptance Criteria (how do I know when I’m done?)
searx can be used to test if it's working well.

**Comment by liuche** [comment] 2020-09-02 17:30
Dupe of #8889

**Closed by liuche** 2020-09-02 17:30 UTC
Labels: feature request 🌟
