### ISSUE TITLE
Add functionality to reorder collections

### ISSUE THREAD

**Issue by ybc37** [mozilla-mobile/fenix#3895] opened 2019-07-05 07:11 UTC
### Why/User Benefit/User Problem
As a user having multiple collection they appear in the order of creation. So it happens that collection, which are more used than others appear lower and aren't so accessible as not so frequently used collections.

### What/Requirements
A functionality to manually reorder collections would solve this issue. Maybe a long tab on a collection would initiate reordering?

### Acceptance Criteria (how do I know when I’m done?)
When it's possible to reorder collections :)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12461)

**Comment by SteveLFC** [comment] 2020-05-04 23:50
I created a duplicate of this only I also requested the options to allow collections to be sorted Automatically in descending or ascending order or manually preferably using drag n drop.

**Comment by OddEvans** [comment] 2020-06-04 04:43
Please make this happen or at least make so when you open a new tab, the tab is directly above the one you opened it from and if you open another tab that one is above the first you opened.

Or better explained, simply make it like fennec firefox at least(I mean in the order they are open) even if it is in reverse with the collections cause it is really confusing.

**Comment by venetian-ftaires** [comment] 2020-06-13 13:04
This would be very useful. Currently feels weird seeing working with a list with no logical order.

**Comment by plwt** [comment] 2022-10-22 16:00
User feedback: https://support.mozilla.org/en-US/questions/1394043

**Comment by boek** [comment] 2023-01-26 21:34
Dup of #8141

**Closed by boek** 2023-01-26 21:34 UTC
Labels: feature request 🌟, Feature:Collections
