### ISSUE TITLE
Local xx.html file on smartphone shows as empty page.

### ISSUE THREAD

**Issue by CorDeVries** [mozilla-mobile/fenix#17394] opened 2021-01-11 13:17 UTC
There is a xx.html file on internal storage of the smartphone.  This link 
file:///storage/emulated/0/cordevries/Smartphone_Home.html  is added as one of the top Web Sites.  After selecting this link the result is an empty page in the browser window.  No error is posted; just an empty / blank page.

This same page is displayed correctly when using the official Firefox browser app.

Problem seems to be introduced after the update released on Jan 8, 2021.

xx.html file is attached here as .txt file
[Smartphone_Home.txt](https://github.com/mozilla-mobile/fenix/files/5795930/Smartphone_Home.txt)

**Comment by cadeyrn** [comment] 2021-01-11 13:35
Duplicate of #1327.

**Comment by kbrosnan** [comment] 2021-01-11 16:10
Closing as a duplicate

**Closed by kbrosnan** 2021-01-11 16:10 UTC
Labels: needs:triage
