### ISSUE TITLE
New tab tray design

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#15104] opened 2020-09-15 06:56 UTC
### What is the user problem or growth opportunity you want to see solved?
Iceweasel a fenix fork has redesigned the tab tray with grid style layout similar to old Firefox... This view can accommodate more tabs in a single page compared to row style tab in fenix.... Can you please consider implementing this in fenix? 

### How do you know that this problem exists today? Why is this important?
Tab tray design is not so good... Does not accommodate much tabs in a single view leading to more scrolls. 

### Who will benefit from it?
All users

![Screenshot_20200915-122318436](https://user-images.githubusercontent.com/58127841/93176245-9fe02c80-f74e-11ea-944a-8425f7586e2b.jpg)

**Comment by klint** [comment] 2020-09-15 08:41
It implemented, this must be optional. We are loosing much information in such a grid view. Nice screenshots pictures show less info than long page titles. Furthermore, on many modern phones, the exact same number of tabs is shown in grid and list views (8 in my case).

**Comment by cadeyrn** [comment] 2020-09-15 08:45
Duplicate of #13098. And in #10344 it was already said that a grid view is planned for the November release.

**Comment by sheikh-azharuddin** [comment] 2020-09-15 10:26
Hello all

Requesting everyone to contribute to the iceweasel project... Here in main fenix this will take months or years to implement a basic feature.... For example the translate feature is still not available but in iceweasel developer has added the add on translate web pages which is translating the pages in real time like chromium browser... Here if you ask about add on they will close the case and redirect you to a general Firefox page.... We are active developing etc....
Not to mention few people are ready to close the case marking it duplicate which refer to month or year old open case... 

So guys please help the iceweasel project to grow!  This is the true fenix browser which hear you.... Apart from that they have added too many add-ons like 40-50...

https://github.com/fork-maintainers/iceweasel/releases/tag/fork-10

**Comment by hwinnemoe** [comment] 2020-09-15 13:19
"Iceweasel Mobile could not exist without the hardworking folks at the Mozilla Corporation who work on the Mozilla Android Components and Firefox projects"

**Comment by sheikh-azharuddin** [comment] 2020-09-15 13:24
> "Iceweasel Mobile could not exist without the hardworking folks at the Mozilla Corporation who work on the Mozilla Android Components and Firefox projects"

Similarly chrome/edge/yandex/brave/Vivaldi cannot exist without chromium... Yet people still prefer the fork version due to customization and better features than the original ....

**Comment by klint** [comment] 2020-09-15 13:53
lol. 
And would you go to the Chromium dev place and ask readers to leave Chromium and use Chrome/edge/yandex/brave/Vivaldi instead?
Your last comments do not belong to this Github project.

**Closed** 2020-09-15 14:50 UTC
Labels: needs:triage
