### ISSUE TITLE
[Bug] The content of web pages is not updated when opened (in the collections)

### ISSUE THREAD

**Issue by Furax-31** [mozilla-mobile/fenix#13154] opened 2020-07-31 08:26 UTC
## Steps to reproduce

Open a favorite saved in a collection

### Expected behavior

The web page that we open should be updated

### Actual behavior

The content of the web page is not updated

### Device information

* Android device: A5 2017 - Android 9
* Fenix version: All versions : Stable, Beta and Nightly

**Comment by buttercookie42** [comment] 2020-07-31 10:04
If collections save the complete tab state and then restore that when opening the collection, that might explain it.

Restoring a tab preferentially and intentionally loads it from cache, which sort of makes sense for restoring recently closed tabs (if that is ever implemented, ahem), restoring tabs that have been discarded because of memory pressure or because the OS killed the whole browser while in background, etc., because in those instances restoring the page should behave as transparently as possible, i.e. ideally it should look just as if it had never been closed/discarded/...

For collections however, which are somewhat more bookmark-like in nature I can see how preferentially loading the page from cache could be confusing.

**Comment by ekager** [comment] 2020-08-03 19:02
Dupe of https://github.com/mozilla-mobile/fenix/issues/10417

**Closed by ekager** 2020-08-03 19:02 UTC
Labels: Skittle, 🐞 bug
