### ISSUE TITLE
[Bug] "Accept the Risk and Continue" is not working

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7038] opened 2019-12-09 19:34 UTC
## Steps to reproduce

www.programva.com

### Expected behavior

Info about SSL issue and ability of opening page / Chrome works fine.
![Screenshot_20191209-203201_Firefox Nightly](https://user-images.githubusercontent.com/24834168/70466376-46621780-1ac3-11ea-9118-d9fe60e6eacc.jpg)

### Actual behavior

Error page and nothing more

### Device information

* Android device: Samsung S7 / Android 8
* Fenix version: nighly

**Comment by NotWoods** [comment] 2019-12-09 21:25
Duplicate of #5060

**Comment by marcinwiacek** [comment] 2019-12-09 22:48
Moment, this issue is not about marking page as insecure, but about this, that you cannot open it at all.

I mean - you can't do anything in FP.

**Comment by NotWoods** [comment] 2019-12-09 23:43
Sorry, I didn't realize the issue here is that the page cannot open at all. Reopening.

**Comment by boek** [comment] 2019-12-19 01:09
@marcinwiacek are you still able to reproduce this?

**Comment by marcinwiacek** [comment] 2019-12-19 02:01
YES - you asked, because you can't reproduce or is any other reason?

Also - if browser cannot open correct page at all, then priority is rather higher than P3... unless you want to loose people using it.

**Comment by boek** [comment] 2019-12-19 02:12
@marcinwiacek i couldn’t reproduce this on any of my devices (pixel 2, 3 and an S9) on the latest nightly. I will see if I can locate an S7 to reproduce

**Comment by marcinwiacek** [comment] 2019-12-19 02:32
interesting, please try to flash / use Android 8 then.

I'm looking now and "normal" preview 3.0.0 on this device opens page OK.

**Comment by marcinwiacek** [comment] 2020-03-09 16:59
Note: with currently nightly build I see different error page & "Accept the Risk and Continue" button is not working.

**Comment by jawz101** [comment] 2020-09-22 16:44
I'm on Android 11 , Firefox 

81.1.1-beta.5 (Build #2015763955)
AC: 57.0.4, eb4aebb91
GV: 81.0-20200910180444
AS: 61.0.13

When I go to a self-signed site on my network I can't "accept the risk and continue".  The page scrolls up every time I try to press the button

**Comment by kbrosnan** [comment] 2020-09-24 08:53
The site https://www.programva.com/ is using a new cert since Aug-10. Closing as not reproducible. Jawz101 you should file a separate issue if you have not done so already.

**Closed by kbrosnan** 2020-09-24 08:53 UTC
Labels: P3, S3, b:anr, 🐞 bug
