### ISSUE TITLE
[Bug] Instagram stories always open in landscape mode

### ISSUE THREAD

**Issue by bogas04** [mozilla-mobile/fenix#4346] opened 2019-07-28 08:54 UTC
## Steps to reproduce
1. Go to Instagram feed
2. Click on any story
3. Observe how it's opened in fullscreen mode.

### Expected behavior
Should open in potrait mode or as per device orientation.

### Actual behavior
Opens in landscape mode.

### Device information

* Android device: RealmeZ Android Pie (ColorOS 6)
* Fenix version: Nightly 190726 06:03 (Build #12070610) 📦: 6.0.0 🦎: 68.0-20190711090008

**Comment by talhek** [comment] 2019-10-04 19:53
Can confirm that this is still happening with FF Preview v2.1.

**Comment by ekager** [comment] 2019-10-04 20:13
We request landscape mode when fullscreen is requested which we added in #4100. Going to close this as a dupe of #5771 but will link this exact STR there.

**Closed by ekager** 2019-10-04 20:13 UTC
Labels: b:webcompat, 🐞 bug
