### ISSUE TITLE
[Bug] Firefox Preview Search in custom tab doesn't open the tab immediately

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#9056] opened 2020-03-09 14:36 UTC
## Steps to reproduce
1. Open a custom tab.
2. Select a text. Tap Firefox Preview Search
### Expected behavior
It should open a new tab with the search, in the app.
### Actual behavior
Nothing visible happens. If you go to the app and open a tab, then a new tab will be created in the background with the search. You can see it when you return to the homescreen.
### Device information

* Android device: Nexus 9 (Android 7)
* Fenix version: Beta 4.0

**Comment by ValentinTimisica** [comment] 2020-05-07 09:29
@liuche, should `Firefox Preview search` work in custom tabs? It is indeed a bug, but I want to know if it should work here or we actually need to remove `Firefox Preview search` option from custom tabs.

**Comment by liuche** [comment] 2020-05-07 17:32
@AmyYLee should we not expose this item "Search with Firefox" in PWAs?

**Comment by AmyYLee** [comment] 2020-05-07 18:21
> @liuche, should `Firefox Preview search` work in custom tabs? It is indeed a bug, but I want to know if it should work here or we actually need to remove `Firefox Preview search` option from custom tabs.

Hi, 

Search should work in custom tabs since if you have other browsers installed it has the option to search in those browsers through this menu (i.e Edge).

**Comment by AmyYLee** [comment] 2020-05-07 18:22
> @AmyYLee should we not expose this item "Search with Firefox" in PWAs?
> ![Screenshot_20200507-103142](https://user-images.githubusercontent.com/1082253/81326133-376d9a00-904e-11ea-941d-87ae63304805.png)

@apbitner Can you reply to the above? Thanks!

**Comment by apbitner** [comment] 2020-05-07 18:34
Yes it should work in PWA's for the same reason as custom tabs.

**Comment by AndiAJ** [comment] 2020-05-20 10:33
Hi, reproducible in PWA's on both **`Beta 5.1.0-beta.1 from 5/19`** and **`Nightly 200520 from 5/20`** using a Huawei Mate 20 Lite (Android 9)

**Comment by Diana-Rus** [comment] 2020-06-15 07:33
Hi, re-checked this issue with Google Pixel 3 XL (Android 9) and Samsung Galaxy S9 (Android 8) on Nightly6/15
**- Open selected text through "Firefox Nightly Search" in Custom Tabs ❌**
GIF-Samsung
![20200615-094202](https://user-images.githubusercontent.com/49859863/84627106-f55a3280-aeee-11ea-96d2-36a703b2263f.gif)
**- Open selected text through "Firefox Nightly Search" in PWA ✔️**
GIF-Samsung
![20200615-094437](https://user-images.githubusercontent.com/49859863/84627116-fd19d700-aeee-11ea-9787-63b55182fb44.gif)

Note: 
**- When using option "Firefox Nightly Search" through custom tab the there is no new tab opened with the  search, the tabs tray is not incremented.**
- Other PWA's with which i tried: instagram,
- When selecting more than one word after which to make the search in browser, a crash will be present-i'll create a new ticket for that and relate it to this one, as it is a regression from this fix, verified with a Nightly build from 6/9 - this only happens on Samsung device.
**GIF**
![20200615-101234](https://user-images.githubusercontent.com/49859863/84629854-abc01680-aef3-11ea-8f86-244b6aa9e10a.gif)

**Comment by softvision-miralobontiu** [comment] 2020-08-05 08:22
Hi all!
This issue is not fixed yet. We have 2 scenarios:
- when there are **no opened tabs** in Firefox Nightly, selecting a text and choosing to search it, does nothing:

<img src="https://user-images.githubusercontent.com/40694158/89389015-85f20980-d70d-11ea-9b25-c3e2205e16f8.gif" width="300" height="550" />

- when there are **opened tabs**, selecting a text, and choosing to search it in the default browser, a tab is created in the background with the search. The user can see it when only when returning to the home screen:

<img src="https://user-images.githubusercontent.com/40694158/89389030-8a1e2700-d70d-11ea-84e4-5a335186120b.gif" width="300" height="550" />

I've tested on the latest Firefox Nightly from 8/4, with Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab S6 (Android 9), and OnePlus (Android 9).
I'll remove the qa:needed label.

**Comment by liuche** [comment] 2020-09-08 21:07
Not sure if the changes that @NotWoods has added in the past few weeks means this should be fixed, and should add a QA-needed label?

**Comment by NotWoods** [comment] 2020-09-08 21:08
Should have QA needed

**Closed** 2020-09-10 14:12 UTC
Labels: Feature:CustomTabs, Feature:PWA, Feature:Search, S2, eng:qa:needed, 🐞 bug
