### ISSUE TITLE
[Bug] Nightly crashes when tapping on download notification

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#6497] opened 2019-11-07 12:19 UTC
## Steps to reproduce
1. Go to https://file-examples.com/ or https://www.thinkbroadband.com/download;
2. Download a file;
3. Go to download notification and tap on it.
### Expected behavior
The downloaded file opens.
### Actual behavior
The app crashes.

### Notes
[notificationcrash.txt](https://github.com/mozilla-mobile/fenix/files/3819526/notificationcrash.txt)

### Device information

* Android device: Pixel 2 (Android 9); Pixel 3a XL(android 9); Huawei Honor 8 (Android 7.0)
* Fenix version: Nightly 191107 GV 72

**Comment by AndiAJ** [comment] 2019-11-07 12:22
Dupe of #6436

**Closed by AndiAJ** 2019-11-07 12:22 UTC
Labels: Feature:Download, S1, b:crash, 🐞 bug
