### ISSUE TITLE
FNX-12397 ⁃ [webcontent] youtube videos not going to landscape mode in fullscreen

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11461] opened 2020-06-11 04:00 UTC
## Site with issue and any steps to reproduce
Open any youtube video and click full screen icon..on full screen it stays in portrait mode instead of going to landscape mode. Please fix this bug

### Expected behavior
Video should go to landscape mode like other browsers

### Actual behavior
Video stays in portrait mode in full screen

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes same issue

### Can you reproduce in Chrome (or other non-Mozilla browser)?
Works fine in chromium browsers like brave/chrome

### Device information
* Android device: ? A10
* Fenix version: ? 79.0a1-20200609092134

**Comment by kbrosnan** [comment] 2020-06-11 05:00
Duplicate of #7602

**Comment by sheikh-azharuddin** [comment] 2020-06-11 05:02
Wait hold on...this was woking fine in yesterday 6am version... something broke in 6pm version

**Closed** 2020-08-11 04:04 UTC
Labels: needs:triage
