### ISSUE TITLE
Firefox Widget does not work with Microsoft Launcher 

### ISSUE THREAD

**Issue by E-System33** [mozilla-mobile/fenix#27160] opened 2022-09-25 08:04 UTC
Hello 

With the Microsoft launcher on Android, I can no longer use the Firefox widget.

When I click on it, nothing happens, and
with default Xiaomi launcher it works.

I have already tried deleting it and putting it back and restarting the phone 

My device :
Xiaomi Redmi 9
Android 11 
4GB RAM

Thanks 
![IMG_20220925_095723](https://user-images.githubusercontent.com/89921808/192134107-a5ece152-8a33-440a-a918-ac5826c13c62.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21663)

**Comment by amocirean** [comment] 2022-10-10 09:49
Hello @bjorn3 , thank you for submitting the issue.
I was not able to reproduce it on Nightly 107.0a1 nor Release 105.2.0. The Firefox app is immediately launched after tapping the widget from the Microsoft Launcher's home screen.
Could you tell us if the issue is still occuring on the latest RC or Nightly on your device?

Devices Used: Huawei P40 Lite (Android 10), Google Pixel 6 (Android 13).

**Comment by cpeterso** [comment] 2022-12-26 07:22
> I was not able to reproduce it on Nightly 107.0a1 nor Release 105.2.0. The Firefox app is immediately launched after tapping the widget from the Microsoft Launcher's home screen.
> Could you tell us if the issue is still occuring on the latest RC or Nightly on your device?

@E-System33 If you can still reproduce this bug, please let us know. In the meantime, I'm closing this bug as not reproducible in Firefox 105 or 107.

**Closed by cpeterso** 2022-12-26 07:22 UTC
Labels: S3, feature:SearchWidget, needs:triage, qa-triaged

**Comment by E-System33** [comment] 2022-12-29 09:16
@cpeterso @amocirean 

Sorry for the delay in responding, I didn't receive a notification, but anyway, 

My phone has been updated to Android 12 by the manufacturer, the bug didn't seem to happen again since.
  
There are two possibilities:

-The bug has been resolved by itself in a way

-A bug only on Android 11
(It is impossible for me to check because I can't downgrade an Android OS)

have a nice day ☀️

**Comment by cpeterso** [comment] 2022-12-29 18:38
Thanks for testing!
