### ISSUE TITLE
Browsing in private mode should not record history

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#604] opened 2019-02-21 02:20 UTC
When browsing in private mode, all history is remembered and can be seen in the History view under your Library.

**Comment by sblatz** [comment] 2019-02-22 18:32
I cannot reproduce this on master. Do you have a demo or STR?

**Comment by st3fan** [comment] 2019-02-25 21:12
@sblatz I cannot reproduce this either now. Is it possible the bugs that I reported were all having the same root cause - that somehow the UI was confused and that although it looks like I was in private mode, I was really in normal mode?

**Comment by sblatz** [comment] 2019-02-25 21:13
I think it's likely that the build you were on had the private mode **theme** but not the logic yet. The theme was merged in a couple days before any logic was added.

**Comment by sblatz** [comment] 2019-02-28 18:19
This should be fixed by https://github.com/mozilla-mobile/fenix/commit/e57aa67d606ac1886c71b2b275da9fbc6fc960be

but let's have QA confirm.

**Comment by sv-ohorvath** [comment] 2019-03-01 13:00
Doesn't reproduce on the latest Nightly build. Closing.

**Closed by sv-ohorvath** 2019-03-01 13:00 UTC
Labels: Feature:History, Feature:PrivateMode, QA needed
