### ISSUE TITLE
⭐️ Feature request: Force dark mode for web content.

### ISSUE THREAD

**Issue by PoetAnderson1** [mozilla-mobile/fenix#20093] opened 2021-06-19 17:11 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

As of now, Firefox is unable to "force" dark mode to websites that don't support it natively.

It would be great that Firefox could force these websites to work with dark mode, without having to rely on addons.

### How do you know that this problem exists today? Why is this important?

I know that it exists when I visit a website that only supports a light theme.

It is important to solve this since relying on addons is not the most performance-friendly solution ([#535](https://github.com/darkreader/darkreader/issues/535), [#3870](https://github.com/darkreader/darkreader/issues/3870), [#5471](https://github.com/darkreader/darkreader/issues/5471))

### Who will benefit from it?

Probably the 631,854 Firefox users that have "Dark Reader" installed.

**Comment by cadeyrn** [comment] 2021-06-19 17:29
Duplicate of #2139.

**Comment by eliserichards** [comment] 2021-06-21 15:13
Thanks for filing @PoetAnderson1! Closing this in favor of #2139 👍

**Closed by eliserichards** 2021-06-21 15:13 UTC
Labels: needs:triage

**Comment by KanadeTachibana2** [comment] 2021-09-17 21:42
can anyone please delete this issue? (I'm the author of it)

**Comment by KanadeTachibana2** [comment] 2021-09-18 12:44
> Thanks for filing @PoetAnderson1! Closing this in favor of #2139 👍 

I'm sorry for bothering you, but can you please delete this issue? (I'm the author of it)

**Comment by KanadeTachibana2** [comment] 2021-09-20 00:16
@eliserichards sorry for bothering you, but can you please delete this issue? I can't do it myself.

I'm just trying to delete my GitHub account.

**Comment by cadeyrn** [comment] 2021-09-20 06:29
> I'm just trying to delete my GitHub account.

Just delete it? All your comments will be linked to a "Ghost" account after your account deletion. You really don't have to delete your comment and ask again every few hours to delete your issue - it will send notifications to many other users every time and therefore wastes time of other people.

**Comment by KanadeTachibana2** [comment] 2021-09-20 09:39
> > I'm just trying to delete my GitHub account.
> 
> Just delete it? All your comments will be linked to a "Ghost" account after your account deletion. There is nothing "personal" at all in your issue. You really don't have to delete your comment and ask again every few hours to delete your issue - it will send notifications to many other users every time.

I suffer from anxiety and I really don't want to leave any leftovers behind after deleting my account - that's why I'm here requesting this.

I'm sorry.

but, it's just one thing.

... please?

**Comment by KanadeTachibana2** [comment] 2021-09-20 15:45
can anyone please delete this issue.

**Comment by KanadeTachibana2** [comment] 2021-09-21 15:31
can anyone please delete this issue?

it's a duplicate.

there's no need to keep this up anymore.

I'm not asking for anything else than that.

**Comment by KanadeTachibana2** [comment] 2021-09-23 01:49
can I please get my issue deleted...
