### ISSUE TITLE
[Bug] Enhanced Tracking Protection Icon Missing in Address Bar

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#9636] opened 2020-04-02 19:36 UTC
### Prerequisites
uBlock Origin has to be installed.

### Steps to reproduce
- close the browser, then reopen it
- go into one of the open tabs
- open the main menu, tap 'uBlock Origin'
- tap 'Open the logger' button: moz-extension website of uBlock Origin opens

This bug occurred on different websites. Still I couldn't reproduce it every single time. It occurs very frequently if the actions are performed in quick succession. I've tried it at different speeds, waiting longer at different points but I couldn't figure out any system. It seems to happen more often if the steps are performed quickly.

### Expected behavior
Enhanced Tracking Protection (shield) icon is supposed to be visible at its usual position on the left side of the address bar.

### Actual behavior
Enhanced Tracking Protection (shield) icon is missing on the address bar.
![20200402_230403](https://user-images.githubusercontent.com/61639215/78299504-54d2b400-7536-11ea-8965-dcdfbe0bdf00.jpg)

Screen recording in full quality: https://gofile.io/?c=VyMeIB

<img src="https://user-images.githubusercontent.com/61639215/78299636-8d728d80-7536-11ea-90ce-b7633a545f25.gif" width="272">

### Device information

* Android device: Samsung Galaxy S9+ (Android 8.0.0)
* Fenix version: 4.2.0

**Comment by s-ankur** [comment] 2020-08-27 14:59
Duplicate of #12848

**Comment by eliserichards** [comment] 2020-12-18 22:24
Closing as duplicate of #12848

**Closed by eliserichards** 2020-12-18 22:24 UTC
Labels: Feature:TrackingProtection, 🐞 bug
