### ISSUE TITLE
FNX-4461 ⁃ Let users open html documents like Chrome.

### ISSUE THREAD

**Issue by PranavBhattarai** [mozilla-mobile/fenix#10672] opened 2020-05-15 04:56 UTC
I think, if I design an HTML page but cannot see in on my favorite browser, then its bummer.
![Screenshot](https://user-images.githubusercontent.com/32763112/82012662-44b30600-9698-11ea-9ed3-9730ba8e78c0.jpg)UNITO-UNDERSCORE!20200515-103611!

I hope in future Firefox preview let user open .html file in its browser when it is installed.

**Comment by cadeyrn** [comment] 2020-05-15 06:01
Duplicate of #1327.

**Comment by sv-sdeiac** [comment] 2020-05-15 06:08
Closing as a duplicate of [1327](https://github.com/mozilla-mobile/fenix/issues/1327).

**Closed** 2020-08-11 01:23 UTC
Labels: feature request 🌟, needs:triage
