### ISSUE TITLE
[Bug] Background images are not fully rendered when the tollbar menu hides.

### ISSUE THREAD

**Issue by jomisica** [mozilla-mobile/fenix#16298] opened 2020-10-31 12:40 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Navigate to https://www.sleeping.pt/wp/2020/08/22/test-parallax-cover/

Watch the following video that shows the problem.
https://www.sleeping.pt/wp/wp-content/uploads/2020/10/2020_10_30_21_58_13-2.webm

### Expected behavior
Whenever the toolbar disappears, redraw the background image.

### Actual behavior
The background image is not redrawn.

### Device information

* Android device: Galaxy A20e 
* Fenix version: 82.1.1

**Comment by winofi** [comment] 2020-11-02 18:11
Ran into the same issue. Minimal example can be found here: https://fggs.de/asdf.html
The issue seems to be that the fixed background image size does not take the toolbar size into account. 
Result:
![image](https://user-images.githubusercontent.com/1752009/97902612-20c6a800-1d3e-11eb-9698-f2028d6fb00e.png)
Tested on same version on Xcover 4s

**Comment by LaurentiuApahideanSV** [comment] 2020-11-05 11:23
I can confirm the issue is reproducible Firefox Preview Nighlty 201105 (Build #2015773803).
### Devices used:
- Samsung Galaxy S9 (Android 8.0.0)
- OnePlus 6T (Android 9)

**Comment by Mugurell** [comment] 2021-02-02 15:54
This seems like a GV issue, moving to Bugzilla.

**Comment by Mugurell** [comment] 2021-02-02 15:54
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1690302

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by Mugurell** 2021-02-02 15:54 UTC
Labels: Feature:Toolbar, S2, 🐞 bug
