### ISSUE TITLE
When pressing the Firefox Preview icon on the homescreen a different app opens [Bug]

### ISSUE THREAD

**Issue by christophgrander** [mozilla-mobile/fenix#9062] opened 2020-03-09 20:45 UTC
## Steps to reproduce
1. Open any app that uses firefox preview to display websites. As an example I will use Feedly but the bug also shows when using twitter, etc.
2. In Feedly open a website. Note that I do not change to firefox preview But open the website directly in feedly using firefox preview.
3. Go to homescreen and press the firefox preview icon.
### Expected behavior
Firefox preview opens.
### Actual behavior
Feedly opens.
### Device information
Galaxy s9, android 10

* Fenix version: latest version from playstore as of march 9. Same behavior shown in previous version.

**Comment by softvision-miralobontiu** [comment] 2020-12-04 13:54
I was not able to reproduce this issue on the 12/4 Firefox Nightly build with Samsung Galaxy Tab S6 (Android 10), nor on Google Pixel (Android 10).
I'm closing this issue.

**Closed by softvision-miralobontiu** 2020-12-04 13:54 UTC
Labels: needs:triage, 🐞 bug
