### ISSUE TITLE
[Bug] For multiple downloads, aggregate notification is undismissable

### ISSUE THREAD

**Issue by nielmistry** [mozilla-mobile/fenix#15854] opened 2020-10-12 19:43 UTC
## Steps to reproduce
1. Download two files
2. Try to dismiss the aggregate download

[Video](https://photos.app.goo.gl/qfBssDcA6uM99QyR7)
### Expected behavior
Aggregate notification should be dismissable
### Actual behavior
Only sub-notifications are dismissable
### Device information
Pixel 2, Android 11 (RP1A.200720.009)

* Android device: Pixel 2
* Fenix version: 81.1.4

**Comment by kbrosnan** [comment] 2020-10-12 20:26
Duplicate of #14155

**Closed by kbrosnan** 2020-10-12 20:26 UTC
Labels: needs:triage, 🐞 bug
