### ISSUE TITLE
[Bug]Improperly displayed and misaligned download prompt on Android 11

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12444] opened 2020-07-10 08:38 UTC
## Steps to reproduce
1. Download any file
1. Check the Download prompt

### Expected behavior
The prompt should cover the Nav bar and should be displayed from one end to the other

### Actual behavior
Misaligned and improperly displayed prompt

### Device information
* Android device: 
• Google Pixel 3 (Android 11)
• Emulator Google Pixel 3 (Android 11)
* Fenix version: Nightly 200709 from 7/9

### Notes
► Screenshots

**Physical device**
![rsz](https://user-images.githubusercontent.com/51314259/87134706-b75bee80-c2a1-11ea-94e3-00c26d2f1d4d.png)UNITO-UNDERSCORE!screenshot!UNITO-UNDERSCORE!20200710-104924!

**Emulator**
![rsz](https://user-images.githubusercontent.com/51314259/87134800-d8bcda80-c2a1-11ea-983a-069ddfbad7fe.png)UNITO-UNDERSCORE!device-2020-07-10-105812!

**Comment by Amejia481** [comment] 2020-07-10 13:26
cc @codrut-topliceanu

**Comment by Mugurell** [comment] 2020-07-10 14:43
Ohh
An Android 11 bug! 😲

**Comment by ekager** [comment] 2020-07-10 15:52
Does the site permission prompt also behave strangely? Those are both in AC and don't implement the same `BottomSheetBehavior` as the QuickSettings and ETP panels

**Comment by Amejia481** [comment] 2020-11-12 18:43
I think the issue is not reproducible in nightly any more, QA team please help us to verify

**Comment by abodea** [comment] 2020-11-17 12:05
Verified as fixed on the latest **Nightly 17/11** with **Google Pixel 4 XL (11).**
![Screenshot_20201218-144706](https://user-images.githubusercontent.com/42831109/99388245-f64c2180-28dd-11eb-9320-3f93892194c1.png)

**Comment by abodea** [comment] 2020-11-17 12:06
@Amejia481 do we still need the `need:ac` label?

**Closed by abodea** 2020-11-17 12:05 UTC
Labels: Android:11, Feature:Download, S2, eng:qa:needed, needs:ac, 🐞 bug

**Comment by Amejia481** [comment] 2020-11-17 14:33
Thanks @abodea, I will remove it :)
