### ISSUE TITLE
[Bug] Clicking link while menu bar is hidden makes page jump

### ISSUE THREAD

**Issue by gtg947h** [mozilla-mobile/fenix#14945] opened 2020-09-10 13:07 UTC
## Steps to reproduce
Click on a link while menu bar is hidden.

### Expected behavior
Navigate to new page. Menu bar appears but doesn't force page movement

### Actual behavior
Menu bar appears as soon as click happens and causes the page to "jump" down to make room.  Very annoying

### Device information

* Android device: Moto one action
* Fenix version: 80.1.2

**Comment by hwinnemoe** [comment] 2020-09-10 13:21
Can you please mention a specific website that shows this behaviour?

**Comment by gtg947h** [comment] 2020-09-10 14:03
> Can you please mention a specific website that shows this behaviour?

It happens on all websites.  One example would be www.weather.gov

**Comment by hwinnemoe** [comment] 2020-09-10 14:15
Thanks! Then this is likely a duplicate of #6976

**Comment by kbrosnan** [comment] 2020-09-10 15:56
Closing as a duplicate

**Closed by kbrosnan** 2020-09-10 15:56 UTC
Labels: needs:triage, 🐞 bug
