### ISSUE TITLE
[Bug] Regression: Black rectangle painted painted on half of visible view on page load

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#7505] opened 2020-01-06 18:46 UTC
4bab49348707110b5fb44248d91c18020dafa49b

Pixel 2 (Android 10)

On initial page load, I am seeing a black rectangle painted in view.

- Visit cnn.com
- See black rectangle

![Untitled](https://user-images.githubusercontent.com/102331/71840159-bcd64300-308a-11ea-9a2d-e8fb70fc5e25.gif)

This doesn't seem to happen on further page loads.

**Comment by AaronMT** [comment] 2020-01-06 18:47
Maybe the same as https://github.com/mozilla-mobile/fenix/issues/7381

**Comment by cadeyrn** [comment] 2020-01-06 19:51
Since you're using a Pixel 2 which has WebRender enabled I think it's #7338.

**Comment by kbrosnan** [comment] 2020-01-06 21:43
I agree on the dupe of #7338

**Closed by kbrosnan** 2020-01-06 21:43 UTC
Labels: needs:triage, 🐞 bug
