### ISSUE TITLE
[Bug] repeated crashes with Nightly 

### ISSUE THREAD

**Issue by samth** [mozilla-mobile/fenix#19672] opened 2021-05-26 14:08 UTC
Firefox nightly on Android today crashes after a few seconds of use, every time. Below is a backtrace for the crash, which is the same error every time.

I'm on version:
90.0a1 (Build #2015812491)
AC: 90.0.20210525143110, 0f0a6ab94
GV: 90.0a1-20210525093431
AS: 76.0.1

 76722c0b-3ec6-4ebc-af64-ece5d8555fb9
mozilla.appservices.remotetabs.RemoteTabProviderException: called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"
----
mozilla.appservices.remotetabs.RemoteTabProviderException: called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"
	at mozilla.appservices.remotetabs.rust.RustError.intoException(RustError.kt:4)
	at mozilla.appservices.remotetabs.RemoteTabsProvider.setLocalTabs(RemoteTabsProvider.kt:11)
	at mozilla.components.browser.storage.sync.RemoteTabsStorage$store$2.invokeSuspend(RemoteTabsStorage.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

**Comment by lobontiumira** [comment] 2021-05-27 08:05
I was not able to reproduce the crash on the 5/25 Nightly build, neither on the 5/26 Nightly build. Tested with Samsung Galaxy Note 8 (Android 9), HTC 10 (Android 8), and Sony Xperia Z5 Premium (Android 7.1.1).

@samth could you provide us more details? 
What device did you encounter the crashes? Could you write down some steps to reproduce?
Thank you!

**Comment by samth** [comment] 2021-05-27 11:32
I have a Pixel 4a, running android 11. To reproduce, just open the browser and use it for a few seconds, it crashes every time. Here's the most recent scorroco entry: https://crash-stats.mozilla.org/report/index/bp-f94808d5-5da9-4eb9-9159-5b1d60210527

**Comment by lobontiumira** [comment] 2021-05-27 11:41
There is a related issue filed in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1649808

**Comment by lobontiumira** [comment] 2021-05-27 12:33
Closing as duplicate of #12162.

**Closed by lobontiumira** 2021-05-27 12:33 UTC
Labels: b:crash, needs:triage, qa-triaged, 🐞 bug

**Comment by samth** [comment] 2021-05-27 13:26
I don't think it's a duplicate of that (which is closed anyway). Instead it seems more like https://github.com/mozilla/application-services/issues/4035 which has the same error message. I've attached a screenshot showing the error messages in the crashes dialog. 
![Screenshot_20210527-092445](https://user-images.githubusercontent.com/244723/119834063-a02fea80-becd-11eb-99aa-030cd1ad3c0c.png)

**Comment by L31FY** [comment] 2021-05-29 04:43
I'm getting this today on both my devices. It's definitely reproducible because I can't use Firefox now.
