### ISSUE TITLE
[Bug] Open in app banner 

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#16133] opened 2020-10-22 18:08 UTC
###  Steps to reproduce

- Use a fresh install or clear the cache
- Open Firefox and search for something with Google
- "Open in app" banner appears on google search result page
- When I turn "Open in app" on and try the search again, nothing happens, no app opens

### Expected behavior
I don't see a banner

### Actual behavior
I see a banner on top of my google search results

### Device information

* Android device: ?
* Fenix version: ?

**Comment by liuche** [comment] 2020-10-22 18:19
This should be solvable in AC, we already have some ability to exclude the banner for some sites.

**Comment by liuche** [comment] 2020-10-22 18:20
cc @rocketsroger we should do this bc it affects search.

**Comment by rocketsroger** [comment] 2020-12-04 00:37
While debugging I noticed that a simpler if condition can make maintenance easier.  Also added some tests.  Still cannot reproduce the issue.

**Comment by rocketsroger** [comment] 2020-12-07 14:58
I'll close this issue since I can't reproduce it.  I've cleaned up the if condition so it's now easier to see that unless there is an app (non browser) that registers to open google.com, the app banner should now show in the search page.  Please reopen if reproducible.

**Closed by rocketsroger** 2020-12-07 14:58 UTC
Labels: Feature:OpenInApp, S3, 🐞 bug
