### ISSUE TITLE
FNX-5213 ⁃ [Bug] custom tab: toolbar makes upper content hidden

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1727] opened 2019-04-17 19:12 UTC
### Steps to reproduce
1. make sure Fenix is your default browser
1. open a link from another app with custom tab support

### Expected behavior
You can see the full content.

### Actual behavior
The toolbar hides the upper content and can - depending on how important the upper content is - make Fenix unusable as default browser for obvious reasons.

![Screenshot](https://user-images.githubusercontent.com/1100614/56314403-4472cf00-6155-11e9-9f9c-17882143a07e.png)UNITO-UNDERSCORE!20190417-210633!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision f5babaf47d7f1f13b8dcb8cc151bc113618d085b

**Comment by sblatz** [comment] 2019-04-22 14:44
This is because of https://github.com/mozilla-mobile/fenix/issues/552. @vesta0 if this is actually a blocking issue for this feature landing we need to get #552 prioritized and in a sprint.

**Comment by vesta0** [comment] 2019-04-23 04:51
@sblatz thanks for flagging this. #552 is already prioritized and [GV is working on it.](https://bugzilla.mozilla.org/show_bug.cgi?id=1536222) Is there a solution the Fenix team can work out that doesn't require GV (or possibly A-C) work?

**Comment by topotropic** [comment] 2019-04-24 12:32
@sblatz are we going to hide the toolbar on scroll?

**Comment by sblatz** [comment] 2019-04-24 14:35
@topotropic: Custom tabs do not have this behavior (in our browser or any others), and the UX didn't mention it, so it does not hide on scroll.

**Comment by topotropic** [comment] 2019-04-24 14:40
@sblatz this is how it works in Chrome as far as I know, location bar hides on scroll, no?

**Comment by sblatz** [comment] 2019-04-24 14:43
@topotropic Ah weird, sometimes Chrome doesn't collapse for me when scrolling and other times it does. The "collapsing" was [not outlined in the UX provided](https://github.com/mozilla-mobile/fenix/issues/203) but we can definitely work on it in a-c if that's the expected behavior.

**Comment by cadeyrn** [comment] 2019-04-24 14:45
For me the location bar does *not* hide on scroll in Chrome custom tabs. :-/

**Comment by topotropic** [comment] 2019-04-24 15:31
@vesta0 can you add a story for post MVP? thanks!

**Comment by cadeyrn** [comment] 2019-04-30 09:34
> @vesta0 can you add a story for post MVP? thanks!

Should this not be fixed for MVP? It's a serious issue because you can't really use Fenix as default browser if it hides content of websites…

**Comment by topotropic** [comment] 2019-04-30 09:42
@cadeyrn yes, you are right – that's reflected in https://github.com/mozilla-mobile/fenix/issues/2052  – I was talking about the automatically collapsing of the toolbar on scroll.

**Comment by vesta0** [comment] 2019-04-30 16:00
@topotropic  I think hiding the top toolbar on scroll is a UX decision (not a user story). If that is the recommended approach, please provide the updated specs. Thanks :) 

cc @mheubusch

**Comment by jonalmeida** [comment] 2019-05-02 03:25
> @topotropic Ah weird, sometimes Chrome doesn't collapse for me when scrolling and other times it does. The "collapsing" was [not outlined in the UX provided](https://github.com/mozilla-mobile/fenix/issues/203) but we can definitely work on it in a-c if that's the expected behavior.

This is because it's an attribute that third-party apps can request. We can choose to follow the Custom Tab spec or ignore it when app's request it: https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.html#EXTRA_ENABLE_URLBAR_HIDING

> This is because of #552. @vesta0 if this is actually a blocking issue for this feature landing we need to get #552 prioritized and in a sprint.

_In it's current form_, I don't believe 552 will solve this issue since the toolbar is dynamically moved to the top, but the bottom of the toolbar is not set to be the start of the geckoview window. 552 would solve the problem with the bottom scroll bar disappearing.

**Comment by topotropic** [comment] 2019-05-02 08:10
> This is because it's an attribute that third-party apps can request. We can choose to follow the Custom Tab spec or ignore it when app's request it: https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.html#EXTRA_ENABLE_URLBAR_HIDING

thanks for pointing that out, @jonalmeida. It makes sense to support this. I re-opend the UX issue and added a comment https://github.com/mozilla-mobile/fenix/issues/203

**Comment by jonalmeida** [comment] 2019-05-02 14:11
> thanks for pointing that out, @jonalmeida. It makes sense to support this. I re-opend the UX issue and added a comment #203

re your comment in that UX issue - that sounds fair for post-MVP so for today the toolbar would need to fixed. In which case @vesta0, for MVP this is not blocked.

**Comment by vesta0** [comment] 2019-05-07 15:40
Created a [new issue](https://github.com/mozilla-mobile/fenix/issues/2315) to track the [UX requested changes.](https://github.com/mozilla-mobile/fenix/issues/203#issuecomment-488585627)

Existing issue will be addressed in #2052

**Closed** 2020-08-11 12:35 UTC
Labels: Feature:CustomTabs, P1, 🙅 waiting
