### ISSUE TITLE
[Bug] "New tab opened" popup is hidden by the toolbar

### ISSUE THREAD

**Issue by wis775** [mozilla-mobile/fenix#15318] opened 2020-09-22 18:49 UTC
## Steps to reproduce
* Disable option "Scroll to hide toolbar"
* Open link in new tab

### Expected behavior
Popup "New tab opened" appears at the bottom
 
### Actual behavior
On a tablet
* The popup is mostly hidden by the toolbar and not usable.

On a mobile
* The popup is not visible.

### Device information
* Fenix version: Firefox Nightly 200920

**Comment by ekager** [comment] 2020-09-22 19:38
closing as dupe of #14982 and should be fixed in next nightly

**Closed by ekager** 2020-09-22 19:38 UTC
Labels: needs:triage, 🐞 bug
