### ISSUE TITLE
[Crash] KotlinNullPointerException in Downloads

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#8415] opened 2020-02-13 20:03 UTC
```
kotlin.KotlinNullPointerException: 
 
  at androidx.transition.CanvasUtils.throwNpe (CanvasUtils.java:1)
 
  at mozilla.components.feature.downloads.AbstractFetchDownloadService.useFileStreamScopedStorage (AbstractFetchDownloadService.kt:18)
 
  at mozilla.components.feature.downloads.AbstractFetchDownloadService.useFileStream$feature_downloads_release (AbstractFetchDownloadService.kt:8)
 
  at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$1.invoke (AbstractFetchDownloadService.kt:20)
 
  at mozilla.components.concept.fetch.Response$Body.useStream (Response.kt:1)
 
  at mozilla.components.feature.downloads.AbstractFetchDownloadService.performDownload$feature_downloads_release (AbstractFetchDownloadService.kt:19)
 
  at mozilla.components.feature.downloads.AbstractFetchDownloadService.startDownloadJob$feature_downloads_release (AbstractFetchDownloadService.kt:3)
 
  at mozilla.components.feature.downloads.AbstractFetchDownloadService$onStartCommand$1.invokeSuspend (AbstractFetchDownloadService.kt:5)
 
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:2)
 
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:15)
 
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:1)
 
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:15)
```

**Comment by ValentinTimisica** [comment] 2020-02-19 14:39
I think this is a duplicate of #7805. Seems like the first comment has the same stackTrace.

**Comment by Mugurell** [comment] 2020-03-03 16:09
I tried to reproduce this but I can't.
There are still reports for this in Sentry, I know it's of the essence to use a device with Android 10, any device, but other than this there's not much to go by and in all my tries I could not reproduce it.
Has anybody else seen this happening, are there any STRs?

**Comment by sv-sdeiac** [comment] 2020-03-05 09:27
I tried to reproduce this issue using the latest version of Firefox Preview Nightly 3/5 #20650606.

I tried with the following scenarios:
- Downloading multiple times the same file;
- Downloading different types of files(image, videos, gif, zip);
- Downloading from the Custom tab;
- Downloading using the Private browser mode;
- Downloading and disable/enable de connection to the internet.

Unfortunately, I wasn't able to reproduce this issue in any case presented above. 
Due to that, I'll close this ticket. If someone can provide steps to reproduce or more information regarding this issue, please don't hesitate to reopen the ticket, thanks.

**Closed by sv-sdeiac** 2020-03-05 09:27 UTC
Labels: Feature:Download, P1, b:crash, eng:qa:needed, needs:triage, 🐞 bug
