### ISSUE TITLE
[Bug] Web share no longer shares title or text

### ISSUE THREAD

**Issue by zepfietje** [mozilla-mobile/fenix#11946] opened 2020-06-25 11:17 UTC
## Steps to reproduce
1. Open a website that implements the Web Share API. (https://web-share.glitch.me/)
1. Press the share button (on the website, not the browser).
1. Choose a share target.

### Expected behavior
`url` and `title` or `text` get shared.

### Actual behavior
Only `url` gets shared.

I've tested multiple versions of Fenix:

* Beta 77.0.0-beta.2: `title` + `url`
* Preview 5.1.1: `title` + `url`
* Preview 5.2.0: `url`
* Nightly 200625 06:00: `url`
* Preview Nightly 200625 06:00: `url`

### Device information
* Android device: multiple Android 10 devices
* Fenix version: Firefox Preview 5.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2610)

**Comment by mcarare** [comment] 2020-06-25 11:59
This was an intended behavior change: https://github.com/mozilla-mobile/fenix/issues/10193.

**Comment by zepfietje** [comment] 2020-06-25 12:04
@mcarare are you talking about sharing using the Web Share API? I think the issue you linked to is about sharing from the browser UI, as Firefox Beta didn't have support for the Web Share API yet before being converted to Fenix).

**Comment by TitanNano** [comment] 2020-06-25 12:06
@mcarare #10193 sounds like it's about general URL sharing though the Fenix UI. I think for the `WebShare` API fenix should forward all parameters to the operating system. This is also what happens on iOS and android `WebView` / chromium.

**Comment by mcarare** [comment] 2020-06-25 13:15
`navigator.share()` is experimental (see also https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#Browser_compatibility).
Clicking the share button in page does not trigger Android share, but the custom Fenix share sheet. The sharing behavior has changed in the aforementioned PR (#10193) that is why it no longer works.

**Comment by zepfietje** [comment] 2020-06-25 13:27
@mcarare I don't get your point. The requested change in #10193 was related to sharing from the browser UI, which probably caused the regression this very issue is about. This does **not** mean the changed behavior with regard to sharing via the Web Share API is intended behavior.

**Comment by mcarare** [comment] 2020-06-25 13:34
It does mean that because using custom share for that action was intended.

**Comment by saschanaz** [comment] 2021-03-06 08:54
Note that it does not pass `text` field even when there is no `url` field: https://web-share-no-url.glitch.me/

Based on the description of https://github.com/mozilla-mobile/fenix/pull/11194 I don't think this is an intended behavior.

**Comment by zepfietje** [comment] 2021-04-15 08:01
I agree with @saschanaz.
Currently when you share `title` or `text` without `url`, nothing is actually shared.
I'm quite sure this is not the intended behavior and is in fact a regression introduced by #11194.
So @ekager, could you remove the `feature request` label from this issue as it clearly is a bug and not a feature request?

**Comment by zepfietje** [comment] 2021-05-26 09:27
I'd like to kindly follow up on this issue.

[Step 8.5 of the Web Share API specification](https://w3c.github.io/web-share/#share-method) implies that *data* members other than `url` (so `title` and `text`) should **not** be removed from *data* before sharing.

> Set *data* to a copy of *data*, with its `url` member set to the result of running the URL serializer on *url*.

This essentially proves that the current behavior is broken in fact. Therefore, I'd like to request again that this issue is treated as a critical bug rather than a feature request. Currently, sharing `title` or `text` using the Web Share API is **broken** for **all Firefox Android users**.

Hopefully we can make some progress in fixing this issue, since it's almost been a year since this regression was introduced. Let's do this!

**Comment by plwt** [comment] 2022-09-25 20:00
User feedback:  https://support.mozilla.org/en-US/questions/1390070

**Comment by boek** [comment] 2022-12-06 23:40
> I'm quite sure this is not the intended behavior and is in fact a regression introduced by https://github.com/mozilla-mobile/fenix/pull/11194.

I spent few minutes investigating what edge / chrome / safari does today and I agree that this is a regression. We initially made this change with #10193 to maintain parity with Fennec and limit the disruption during the migration. 

We should fix this to be compatible with [`navigator.share()`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility). Ultimately it should be up to the individual applications to appropriately handle the incoming Share Intent ([Even we parse the incoming string to decide whether we should load a URL or perform a search](https://github.com/mozilla-mobile/firefox-android/blob/main/android-components/components/feature/intent/src/main/java/mozilla/components/feature/intent/processing/TabIntentProcessor.kt#L71)).

If we want continue to support this workflow I say we should follow up with a feature to only share the URL as originally requested in #10193.

**Comment by jonalmeida** [comment] 2022-12-07 01:45
Adding some opinion here: #10193 should have been closed as "won't fix". The use case is that the browser should change it's standard in order to support the _third party application's ability_ to parse the URL. 

This expectation is wrong to me as it should be up to the third party app to parse out the URL.

**Comment by kbrosnan** [comment] 2022-12-08 01:43
I really wish we could be liberal in what we are sending. Unfortunately sending an image + URL broke sharing to several popular messaging apps. When sharing an image from Firefox to an app fails in Firefox but not Chrome that looks to the user like Firefox is broken.

**Comment by kbrosnan** [comment] 2022-12-12 19:34
My comment was in the context of the Android share action, not `navigator.share`.

**Comment by cpeterso** [comment] 2023-01-12 05:32
Duplicate of Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1809788 (from https://github.com/mozilla-mobile/fenix/issues/15075)

**Closed by cpeterso** 2023-01-12 05:32 UTC
Labels: 🐞 bug, feature request 🌟, Feature:Sharing
