### ISSUE TITLE
[Bug/Missing critical feature] Long press refresh button to do a hard reset

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#6329] opened 2019-10-29 15:02 UTC
### Why/User Benefit/User Problem
Currently I don't think there's a way to do a hard refresh in Fenix is there? If there is I haven't found it.

### What/Requirements
In Fennec long-press on the refresh icon will force hard refresh a page. I suggest that the same method is used in Fenix.

### Acceptance Criteria (how do I know when I’m done?)
Provide a way to hard refresh a page.

**Comment by buttercookie42** [comment] 2019-11-07 09:06
Duplicate of #2681.

**Comment by madb1lly** [comment] 2019-11-07 13:25
Thanks @buttercookie42. I honestly _did_ try to see if this bug was already raised, but I presume that GitHub's search function hid it from me!

**Closed** 2020-01-29 16:21 UTC
Labels: 🌟 feature request
