### ISSUE TITLE
[Bug]: Device continually fails to get a Web Push subscription

### ISSUE THREAD

**Issue by saltisgood** [mozilla-mobile/fenix#20365] opened 2021-07-14 12:51 UTC
### Steps to reproduce

I don't know how to get the device into an affected state, but once it is:

1. Go to a site that uses Web Push notifications. For example: https://webpushdemo.azurewebsites.net/
2. Click on the button to initiate push.

It works for any site using Web Push on the device.

### Expected behaviour

Calling `PushManager.subscribe()` should return a PushSubscription instance or an error.

### Actual behaviour

- There is an internal call to updates.push.services.mozilla.com that returns a 410 error.
- `PushManager.subscribe()` returns null and no error.

### Device name

Samsung Galaxy A71

### Android version

11

### Firefox release type

Firefox

### Firefox version

89.1.1

### Device logs

The HTTP call to register the subscription is:
POST https://updates.push.services.mozilla.com/v1/fcm/boxwood-axon-825/registration/.../subscription

Response:
410 Gone
{"code": 410, "errno": 103, "error": "", "more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes", "message": "Request did not validate UAID not found"}

(I can supply the exact endpoint and token if required but I don't know if it's sensitive or not)

### Additional information

This seems to be caused by https://github.com/mozilla-services/autopush/issues/1445
I think there should be at least some error returned due to the failure or an attempt to reset the device token or endpoint used. Resetting Firefox's storage in the Android settings does fix the problem but is not a simple solution to communicate to people.

I have 2 devices that were both affected by this with 1 that still has it. So I can perform any extra debugging if required but I don't know how it was triggered.

**Comment by sflorean** [comment] 2021-07-14 13:23
@saltisgood thank you for your report! I was able to reproduce the issue on latest Nightly with Samsung Note 10 (Android 11).
I will close this as a duplicate of #19152, please follow the discussion there.

**Closed by sflorean** 2021-07-14 13:23 UTC
Labels: needs:triage, 🐞 bug

**Comment by saltisgood** [comment] 2021-07-17 03:08
It's mentioned on that issue that the push message is delivered there. This is where you can't even register. They sound like separate issues to me.

**Comment by jonalmeida** [comment] 2021-07-22 05:19
The error that you are seeing is caused by mozilla-services/autopush#1445
