### ISSUE TITLE
[Bug]Files downloaded from Fenix always don't be recognized as a correct type

### ISSUE THREAD

**Issue by Moderpach** [mozilla-mobile/fenix#4044] opened 2019-07-13 01:24 UTC
## Steps to reproduce
Dwnload any file, such as ZIP,APK.
Check the file in the explore. The file is recognized as a File but not its real type.
![Screenshot_20190712-225352_](https://user-images.githubusercontent.com/34941512/61165204-d40afc80-a54f-11e9-8432-4bb47819a481.png)

### Expected behavior
Be recognized as its real type
### Actual behavior
Be recognize as a File type
### Device information

* Android device: xiaomi redmi 4 prime
* Fenix version: v1.0.1

**Comment by PowERGD** [comment] 2019-07-13 01:28
the problem don't exist , if you use the third-party explore.

**Comment by nahuhh** [comment] 2019-07-16 12:11
The problem does exist. 

http://gscs-b2c.lge.com/downloadFile?fileId=KROWM000196248.pdf

Above is a link to a manual for a washing machine from LG. Source link: https://www.lg.com/us/support/manuals-documents?customerModelCode=WM2101HW&csSalesCode=WM2101HW.ABWEEUS&category=CT10000010&subcategory=CT10000076

Downloaded in fenix, you cannot open it. (workaround: rename the file.)

Downloaded in chrome etc, it is properly recognized as a PDF file.

**Comment by leela52452** [comment] 2019-11-06 05:57
fenix 2.3.0 [ 20191014032640 ] downloading .md file as .txt file

file link: https://gitlab.com/leela52452/leela.gitlab.io/raw/master/_posts/2019-10-28-bad-bot.md?inline=false

![Screenshot_2019-11-06-11-05-29](https://user-images.githubusercontent.com/52065244/68272009-4b622000-005a-11ea-832a-568eb55b5d86.png)

**Comment by jonalmeida** [comment] 2019-11-25 19:58
AC bug: https://github.com/mozilla-mobile/android-components/issues/5132

**Comment by jonalmeida** [comment] 2020-02-28 12:55
A patch for this landed in a-c and should be in Fenix Nightly now.

**Comment by sv-sdeiac** [comment] 2020-03-03 10:33
Hello, I tried to verify this issue but I see that is not 100% fixed since I found some pages where the bug is still reproducible. 
There are some links where I can still reproduce the issue:
- Downloading an mp4 file by using a firefox send link;
- Downloading a pdf file such as http://download.microsoft.com/download/A/D/F/ADF027D4-0541-4CFB-9202-3C48571ABB54/483_OD_Changes.pdf or https://data.amsterdam.nl/artikelen/artikel/bewoners-centrum-blij-met-meer-groen-minder-met-toeristen/2d389e0c-4571-49d8-9a92-c39f6af89210/;

And other links where I wasn't able to reproduce the issue:
- Saving different images such as https://github.com/webcompat/web-bugs/issues/48431 or https://www.w3schools.com/howto/tryit.asp?filename=tryhow_html_download_link2;
- Downloading different videos such as in bug: https://github.com/webcompat/web-bugs/issues/49189;
- Downloading different videos  from 9gag site ( https://github.com/webcompat/web-bugs/issues/49189);

Due to that, I'll remove the qa:needed flag and let the ticket open till we find new information, thanks.

**Comment by jonalmeida** [comment] 2020-03-18 20:30
> Downloading an mp4 file by using a firefox send link;

Please file a separate bug for this, it seems unrelated to this bug which was for APKs.

> Downloading a pdf file such as http://download.microsoft.com/download/A/D/F/ADF027D4-0541-4CFB-9202-3C48571ABB54/483_OD_Changes.pdf or https://data.amsterdam.nl/artikelen/artikel/bewoners-centrum-blij-met-meer-groen-minder-met-toeristen/2d389e0c-4571-49d8-9a92-c39f6af89210/;

These don't open in Fennec as well, so my guess is that there's either something wrong with the files itself or they are `blob` types which are not supported.

**Closed by jonalmeida** 2020-03-18 20:30 UTC
Labels: Feature:Download, P1, S1, needs:ac, 🐞 bug
