### ISSUE TITLE
Allow for disabling history from custom tabs

### ISSUE THREAD

**Issue by joshsleeper** [mozilla-mobile/fenix#5590] opened 2019-09-26 00:19 UTC
### Why/User Benefit/User Problem

When I'm browsing a service like Reddit or Google News, I regularly follow links as I scroll through the app that must open a custom tab to view the content.

For example, sometimes a Reddit post will be an image that automatically opens in the Reddit app, but sometimes it'll just be a link that opens a custom tab just to show the image. Now I have some arbitrary, not-terribly-searchable history entry for some image I likely don't care about past that point.

Adding a toggle that disables history for custom tabs (or maybe allows for Private Browsing custom tabs?) would help me streamline my history to things I _actaally_ care about retaining.

Note that one common solution given is to simply use something like Firefox Focus as the default browser. While this solves the custom tab history problem, it introduces a new issue of having extra steps to open anything in the browser I actually wish to use for browsing. As such, I don't think it's a great solution for everyone.

### What/Requirements

Toggle/setting to allow for disabling browser history storage for custom tabs.

### Acceptance Criteria (how do I know when I’m done?)

Given the aforementioned setting is enabled:

1. navigate to another app (Reddit, Google News, etc.) that easily opens links in a custom tab
1. open said link in a custom tab
1. close the custom tab
1. open Firefox Preview proper and navigate to the History section
1. see that the link visited in a custom tab was not added to the browsing history

**Comment by NotWoods** [comment] 2019-09-26 02:57
It's not surfaced well in the UI yet but we do have private browsing custom tabs! For now, you can toggle the "Launch links in private tab" switch in settings and you'll get private custom tabs.

Since that addresses this use case (and we're going to improve the UI through other issues), I'm going to close this ticket.

**Closed by NotWoods** 2019-09-26 02:57 UTC
Labels: 🌟 feature request

**Comment by joshsleeper** [comment] 2019-09-26 04:05
FYI, I'd tried that setting just earlier today when I _thought_ that's the behavior I'd get, but that's not what I'm seeing!

Even after enabling that "Launch links in private tab" toggle, my custom tabs are still logging history.

**Comment by NotWoods** [comment] 2019-09-26 04:28
That's not the intended behaviour so I filed a new bug report (#5592) with your info from here.
