### ISSUE TITLE
[Bug] No sync on start

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#17059] opened 2020-12-16 00:46 UTC
Just on start ff shows no accounts or devices available:
![image](https://user-images.githubusercontent.com/14617699/102285935-4c959a00-3f48-11eb-959d-7395837683d9.png)
![image](https://user-images.githubusercontent.com/14617699/102286250-f83eea00-3f48-11eb-8f0c-c51b72bfc7be.png)

### Steps to reproduce
1. Open fenix
2. Try to share something or go to the settings

### Expected behavior
FF must not mislead users with the lack of available devices or accounts. All devices and account must be shown immediately after launch without any delay.

### Actual behavior
Devices and accounts are shown after a delay. While settings page is updated automagically, trying to share something will stuck on no devices untill next try.

### Device information

* Android device: OP3T on LineageOS 17.1 (Android 10)
* Fenix version: 81.1.0

**Comment by jonalmeida** [comment] 2020-12-16 23:42
Duplicate of https://github.com/mozilla-mobile/fenix/issues/16890.

**Closed by jonalmeida** 2020-12-16 23:42 UTC
Labels: Feature:Sync, needs:triage, 🐞 bug
