### ISSUE TITLE
[Bug] Sideloading/installing .apks doesn't work by default, enabling in Android settings doesn't work either

### ISSUE THREAD

**Issue by x2k13** [mozilla-mobile/fenix#13834] opened 2020-08-14 12:53 UTC
**Fenix Version:**
Nightly 200814 06:02 (Build #2015757873)
AC: 54.0.20200812130143, 721a690d6
GV: 81.0a1-20200811091731
AS: 61.0.10
Friday 8/14 @ 6:08 AM

**Android Version:** 10

**What should happen:**
Downloading .apk files, then tapping on the "Download complete" notification should open the installer toast/dialogue so we can install/sideload the App.

**What actually happens:**
Tapping on the notification opens a "Choose-App" toast/dialogue offering random Apps totally unrelated to installing/sideloading. So, to install the Apps via .apk forces us to use a filemanager instead.

**EDIT:**

> Duplicate of #9744. Also, you can try [#9744 (comment)](https://github.com/mozilla-mobile/fenix/issues/9744#issuecomment-627468597).

Doesn't work even if doing as https://github.com/mozilla-mobile/fenix/issues/9744#issuecomment-627468597 recommends.
You still get the Choose-App toast but no change in behaviour. Closing Fenix and restarting makes no difference.

**Comment by hwinnemoe** [comment] 2020-08-14 13:04
Duplicate of #9744

**Comment by x2k13** [comment] 2020-08-14 13:19
> Duplicate of #9744. Also, you can try [#9744 (comment)](https://github.com/mozilla-mobile/fenix/issues/9744#issuecomment-627468597).
Doesn't work even if doing as https://github.com/mozilla-mobile/fenix/issues/9744#issuecomment-627468597 recommends.

**Comment by liuche** [comment] 2020-08-20 01:48
Thanks for linking to the dupe!

**Closed by liuche** 2020-08-20 01:48 UTC
Labels: needs:triage
