### ISSUE TITLE
[Bug] elta.gr TLS certificate is not recognized

### ISSUE THREAD

**Issue by JpegXguy** [mozilla-mobile/fenix#8893] opened 2020-03-02 05:03 UTC
## Steps to reproduce
Visit https://www.elta.gr

### Expected behavior
Homepage of the site is shown

### Actual behavior
I get the "Secure Connection Failed" screen and tapping "Accept the Risk and Continue" does nothing (the security prompt remains).

After cleaning data, the behavior remains, as is expected.
Seems like the Firefox certificate store disagrees with other ones, like my desktop Firefox or Android Chrome.
 
### Device information
Huawei P Smart 2019, Android 10, Nightly 200301 (Build #2015726099)

**Comment by kbrosnan** [comment] 2020-03-02 06:57
Server is using an insecure version of TLS either version 1.0 or 1.1. Making this a dupe of #6296

**Closed by kbrosnan** 2020-03-02 06:57 UTC
Labels: needs:triage, 🐞 bug
