### ISSUE TITLE
[Bug]: Desktop mode stops working when moving back a page, while still indicating being turned on

### ISSUE THREAD

**Issue by konstantinua00** [mozilla-mobile/fenix#24924] opened 2022-04-22 15:21 UTC
### Steps to reproduce

1. Go to https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla
2. Make sure you are in Desktop Mode
3. Press any Bugzilla link
4. Press back button to go back a page

### Expected behaviour

It should stay in desktop mode. 

### Actual behaviour

After returning to support.mozilla page, it is shown in mobile version. Desktop mode toggle is still in "on" position. Turning that off reloads page and shows the page in mobile mode again. Turning it on after that changes to pc mode as normal until next press of back button.

### Device name

Redmi 7A

### Android version

Android 10 QKQ1

### Firefox release type

Firefox

### Firefox version

99.2.0 (Build #2015874209)

### Additional information

I honestly don't know whether it's better to keep Desktop Mode state when moving back a page or to store that state for each page in recent history, but it definitely should not switch to [in my eyes] inferior mobile mode on it's own

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20255)

**Comment by delia-pop** [comment] 2022-04-27 19:11
Hi @konstantinua00 ! Thank you for your report! 
I was not able to reproduce the issue you described on Firefox 99.2.0, Beta 100-beta.5 and latest Nightly from 04/27. 
Could you please re-test the issue using the latest Nightly build?
Device used: Xiaomi Redmi Note 8T (Android 9); Motorola Moto G30 (Android 11).

**Comment by bigConifer** [comment] 2022-05-30 15:11
Duplicate of #11552 (#15352).

**Comment by sflorean** [comment] 2022-05-31 14:31
Closing this issue since it's already tracked. This scenario will be verified as well, when a fix will be available.

**Closed by sflorean** 2022-05-31 14:31 UTC
Labels: 🐞 bug, Feature:RequestDesktopSite, S3, needs:triage, qa-triaged
