### ISSUE TITLE
[Bug] The tab menu cannot be dismissed on Android 5 devices

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#19664] opened 2021-05-26 09:25 UTC
## Steps to reproduce
1. Open a page.
2. Long-tap on the tab counter - the "new tab" menu is displayed.
3. Tap anywhere outside the displayed menu.

### Expected behavior
The "new tab" menu is dismissed.

### Actual behavior
The menu is still displayed. The user cannot dismiss it.

### Device information
* Devices: Samsung Galaxy Tab A6 (Android 5.1.1), Xiaomi mi4i (Android 5.0.2)
* Firefox for Android version: 5/26 Nightly, Beta 89.0.0-beta.10, and RC 89.1.0

https://user-images.githubusercontent.com/40694158/119636250-1de7ed80-be1d-11eb-9b82-c9a2b682c804.mp4

**Comment by lobontiumira** [comment] 2021-05-28 07:25
Reproducible on RC 89.1.1 with the same devices.

**Comment by Siva981** [comment] 2021-12-07 19:11
All 3 issues are reporting the same defect.

#19664 (this issue)
#17104 
#22312

**Comment by sflorean** [comment] 2021-12-13 13:37
Closing as duplicate of https://github.com/mozilla-mobile/fenix/issues/17104.

**Closed by sflorean** 2021-12-13 13:37 UTC
Labels: 🐞 bug, Feature:Toolbar, S3, Feature:ContextMenu
