### ISSUE TITLE
[Bug] The bottom part of full-screen youtube videos cannot be seen

### ISSUE THREAD

**Issue by lmocsi** [mozilla-mobile/fenix#17883] opened 2021-02-06 20:25 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open a youtube video in Firefox for Android, and make it full screen.

### Expected behavior
See the whole video.

### Actual behavior
The bottom ~8 percent of the video is off the screen.

### Device information
Samsung S10, Android 11
Firefox 85.0.1

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by lmocsi** [comment] 2021-02-06 20:28
Exact FF version:
85.1.2 (Build #2015791451)
AC: 70.0.19, 45ec22f76
GV: 85.0.1-20210204182252
AS: 67.2.0

**Comment by anotherus3r** [comment] 2021-02-07 14:37
Duplicate of #8252

**Comment by LaurentiuApahideanSV** [comment] 2021-02-10 09:23
The issue has already been reported here: https://github.com/mozilla-mobile/fenix/issues/8252. I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-02-10 09:23 UTC
Labels: needs:triage, 🐞 bug
