### ISSUE TITLE
[Bug]: black/blank page after restoring PWA(?) using task switcher

### ISSUE THREAD

**Issue by brudolp** [mozilla-mobile/fenix#22351] opened 2021-11-06 21:05 UTC
### Steps to reproduce

1. open https://music.youtube.com/ and select the 'add shortcut to home screen' option
2. close fenix and launch the yt-music shortcut
3. open the task switcher and then close it again

### Expected behaviour

usable webpage/PWA after returning from task switcher

### Actual behaviour

an empty dark-grey page is shown, issue persists after tapping on the reload button

https://user-images.githubusercontent.com/35417651/140624044-fdcbea2a-4d73-4199-ae41-f745f7ed911d.mp4

### Device name

Mi9tPro

### Android version

Android 11, custom rom

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1

### Device logs

11-06 21:40:09.749  2132 11712 I ActivityTaskManager: START u0 {act=mozilla.components.feature.pwa.PWA_LAUNCHER dat=https://music.youtube.com/... flg=0x10080000 pkg=org.mozilla.fenix cmp=org.mozilla.fenix/mozilla.components.feature.pwa.WebAppLauncherActivity bnds=[491,1056][669,1266]} from uid 10353
11-06 21:40:09.770  2132  2157 I ActivityManager: Start proc 13977:org.mozilla.fenix/u0a353 for pre-top-activity {org.mozilla.fenix/mozilla.components.feature.pwa.WebAppLauncherActivity}
11-06 21:40:09.956 13977 21514 I chatty  : uid=10353(org.mozilla.fenix) GleanAPIPool identical 1 line
11-06 21:40:09.960 13977 21514 I TetheringManager: registerTetheringEventCallback:org.mozilla.fenix
11-06 21:40:09.978 13977 21517 I chatty  : uid=10353(org.mozilla.fenix) DefaultDispatch identical 9 lines
11-06 21:40:09.987 13977 21516 I GeckoLoader: Library base=/data/app/~~q5ETkzz7p1VyQYb2FMRRQQ==/org.mozilla.fenix-3ucQX6uJLFlDGs97TbDFfQ==/lib/arm64
11-06 21:40:09.987 13977 21517 I chatty  : uid=10353(org.mozilla.fenix) DefaultDispatch identical 1 line
11-06 21:40:09.988 13977 21516 I GeckoLoader: Library base=/data/app/~~q5ETkzz7p1VyQYb2FMRRQQ==/org.mozilla.fenix-3ucQX6uJLFlDGs97TbDFfQ==/lib/arm64
11-06 21:40:09.991 13977 21516 I GeckoLoader: Library base=/data/app/~~q5ETkzz7p1VyQYb2FMRRQQ==/org.mozilla.fenix-3ucQX6uJLFlDGs97TbDFfQ==/lib/arm64
11-06 21:40:09.991 13977 21516 I GeckoLoader: Library base=/data/app/~~q5ETkzz7p1VyQYb2FMRRQQ==/org.mozilla.fenix-3ucQX6uJLFlDGs97TbDFfQ==/lib/arm64
11-06 21:40:10.064  2132  2305 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=281, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10353 AdministratorUids: [] RequestorUid: 10353 RequestorPackageName: org.mozilla.fenix] ] with score 50 and providerId 4
11-06 21:40:10.064  2838  2838 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=281, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10353 AdministratorUids: [] RequestorUid: 10353 RequestorPackageName: org.mozilla.fenix] ] with score 50 and providerId 4
11-06 21:40:10.064  2132  2253 D UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=281, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10353 AdministratorUids: [] RequestorUid: 10353 RequestorPackageName: org.mozilla.fenix] ] with score 50 and providerId 4
11-06 21:40:10.064  2132  2253 D WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=281, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10353 AdministratorUids: [] RequestorUid: 10353 RequestorPackageName: org.mozilla.fenix] ] with score 50 and providerId 4
11-06 21:40:10.077  2132  2155 I ActivityTaskManager: Displayed org.mozilla.fenix/mozilla.components.feature.pwa.WebAppLauncherActivity: +322ms
11-06 21:40:10.090  2132  5807 I ActivityTaskManager: START u0 {act=mozilla.components.feature.pwa.VIEW_PWA dat=https://music.youtube.com/... pkg=org.mozilla.fenix cmp=org.mozilla.fenix/.IntentReceiverActivity} from uid 10353
11-06 21:40:10.097 13977 13977 W org.mozilla.fenix: type=1400 audit(0.0:624): avc: denied { bind } for comm=4E65746C696E6B204D6F6E69746F72 scontext=u:r:untrusted_app:s0:c97,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c97,c257,c512,c768 tclass=netlink_route_socket permissive=0 b/155595000 app=org.mozilla.fenix
11-06 21:40:10.115  2132 13171 I ActivityTaskManager: START u0 {act=mozilla.components.feature.pwa.VIEW_PWA dat=https://music.youtube.com/... flg=0x80000 pkg=org.mozilla.fenix cmp=org.mozilla.fenix/.customtabs.ExternalAppBrowserActivity (has extras)} from uid 10353
11-06 21:40:10.175  2132  2157 I ActivityManager: Start proc 21588:org.mozilla.fenix:tab8/u0a353 for service {org.mozilla.fenix/org.mozilla.gecko.process.GeckoChildProcessServices$tab8}
11-06 21:40:10.182 21588 21588 E illa.fenix:tab: Not starting debugger since process cannot load the jdwp agent.
11-06 21:40:10.184 21588 21588 W illa.fenix:tab: Core platform API violation: Ljava/lang/reflect/Field;->accessFlags:I from Landroid/os/Build; using reflection
11-06 21:40:10.233 13977 13977 I NavController: Ignoring popBackStack to destination org.mozilla.fenix:id/browserFragment as it was not found on the current back stack
11-06 21:40:10.372  2132  2155 I ActivityTaskManager: Displayed org.mozilla.fenix/.customtabs.ExternalAppBrowserActivity: +281ms
11-06 21:40:10.439  2132  3899 W ActivityManager: Receiver with filter android.content.IntentFilter@45dc8d1 already registered for pid 13977, callerPackage is org.mozilla.fenix
11-06 21:40:10.499  2132  2132 D NotificationService: 0|org.mozilla.fenix|1|SiteControls|10353: granting content://settings/system/notification_sound
11-06 21:40:10.500  2132  2132 D NotificationService: 0|org.mozilla.fenix|1|SiteControls|10353: granting content://settings/system/notification_sound
11-06 21:40:10.639 21588 21620 I GeckoLoader: Library base=/data/app/~~q5ETkzz7p1VyQYb2FMRRQQ==/org.mozilla.fenix-3ucQX6uJLFlDGs97TbDFfQ==/lib/arm64
11-06 21:40:10.639 21588 21620 I GeckoLoader: Library base=/data/app/~~q5ETkzz7p1VyQYb2FMRRQQ==/org.mozilla.fenix-3ucQX6uJLFlDGs97TbDFfQ==/lib/arm64
11-06 21:40:10.640 21588 21620 I GeckoLoader: Library base=/data/app/~~q5ETkzz7p1VyQYb2FMRRQQ==/org.mozilla.fenix-3ucQX6uJLFlDGs97TbDFfQ==/lib/arm64
11-06 21:40:10.640 21588 21620 I GeckoLoader: Library base=/data/app/~~q5ETkzz7p1VyQYb2FMRRQQ==/org.mozilla.fenix-3ucQX6uJLFlDGs97TbDFfQ==/lib/arm64
11-06 21:40:17.052     0     0 I Killing 'illa.fenix: tab8' (21588), adj 700,
11-06 21:40:17.051  2132  2150 I ActivityManager: Killing 21588:org.mozilla.fenix:tab8/u0a353 (adj 905): empty #1
11-06 21:40:17.087     0     0 I oom_reaper: reaped process 21588 (illa.fenix:tab8), now anon-rss:0kB, file-rss:0kB, shmem-rss:5524kB
11-06 21:40:17.106  2132  3219 W ActivityManager: Scheduling restart of crashed service org.mozilla.fenix/org.mozilla.gecko.process.GeckoChildProcessServices$tab8 in 1000ms for connection
11-06 21:40:18.967  2838  2838 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=285, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10353 AdministratorUids: [] RequestorUid: 10353 RequestorPackageName: org.mozilla.fenix] ] with score 50 and providerId 4
11-06 21:40:18.967  2132  2253 D UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=285, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10353 AdministratorUids: [] RequestorUid: 10353 RequestorPackageName: org.mozilla.fenix] ] with score 50 and providerId 4
11-06 21:40:18.967  2132  2253 D WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=285, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10353 AdministratorUids: [] RequestorUid: 10353 RequestorPackageName: org.mozilla.fenix] ] with score 50 and providerId 4
11-06 21:40:18.967  2132  2305 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=285, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10353 AdministratorUids: [] RequestorUid: 10353 RequestorPackageName: org.mozilla.fenix] ] with score 50 and providerId 4
11-06 21:40:19.800  2132  2305 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=286, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10353 AdministratorUids: [] RequestorUid: 10353 RequestorPackageName: org.mozilla.fenix] ] with score 50 and providerId 4
11-06 21:40:19.801  2132  2253 D UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=286, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10353 AdministratorUids: [] RequestorUid: 10353 RequestorPackageName: org.mozilla.fenix] ] with score 50 and providerId 4
11-06 21:40:19.801  2132  2253 D WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=286, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10353 AdministratorUids: [] RequestorUid: 10353 RequestorPackageName: org.mozilla.fenix] ] with score 50 and providerId 4
11-06 21:40:19.801  2838  2838 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=286, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10353 AdministratorUids: [] RequestorUid: 10353 RequestorPackageName: org.mozilla.fenix] ] with score 50 and providerId 4
11-06 21:40:19.835  2132  2155 I ActivityTaskManager: Displayed org.mozilla.fenix/.customtabs.ExternalAppBrowserActivity: +145ms
11-06 21:40:19.995  2132  2132 D NotificationService: 0|org.mozilla.fenix|1|SiteControls|10353: granting content://settings/system/notification_sound
11-06 21:40:19.996  2132  2132 D NotificationService: 0|org.mozilla.fenix|1|SiteControls|10353: granting content://settings/system/notification_sound

### Additional information

I've enabled the 'don't keep activities' and 'background process limit =1' developer options in order to reproduce this issue reliably.
This issue usually occurs after moving the PWA to the background and restoring it after an hour.

m.twitch.tv is also affected

**Comment by klint** [comment] 2021-11-07 15:35
Maybe linked to #17380?

**Comment by klint** [comment] 2021-11-07 15:36
And  #19157?

**Comment by LaurentiuApahideanSV** [comment] 2021-11-18 16:55
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/19157. I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-11-18 16:55 UTC
Labels: 🐞 bug, needs:triage
