### ISSUE TITLE
[Bug][Crash]Crash Report

### ISSUE THREAD

**Issue by lomomcat** [mozilla-mobile/fenix#15444] opened 2020-09-26 03:07 UTC
## Steps to reproduce
Open Firefox Nightly and wait for the last opened tab to load.
### Actual behavior
Crash.
### Device information

* Android device: Xiaomi Redmi Note 8 Pro
* Fenix version: Nightly 200525 06:01

**Comment by lomomcat** [comment] 2020-09-26 03:10
4e19e1cd-df03-4e36-9517-e6b495db77fc
mozilla.appservices.fxaclient.FxaException$Network: Network error: [no-sentry] Network error: Java error: "fetch error: java.net.SocketTimeoutException"
----
```
mozilla.appservices.fxaclient.FxaException$Network: Network error: [no-sentry] Network error: Java error: "fetch error: java.net.SocketTimeoutException"
	at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:5)
	at mozilla.appservices.fxaclient.FirefoxAccount.getTokenServerEndpointURL(FirefoxAccount.kt:9)
	at mozilla.components.service.fxa.FirefoxAccount.getTokenServerEndpointURL(FirefoxAccount.kt:1)
	at mozilla.components.service.fxa.manager.FxaAccountManager.maybeUpdateSyncAuthInfoCache(FxaAccountManager.kt:13)
	at mozilla.components.service.fxa.manager.FxaAccountManager$maybeUpdateSyncAuthInfoCache$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by hakkikaancaliskan** [comment] 2020-09-26 08:43
Duplicate of #15412

**Comment by kbrosnan** [comment] 2020-09-29 17:10
Closing as a duplicate

**Closed by kbrosnan** 2020-09-29 17:10 UTC
Labels: needs:triage, 🐞 bug
