### ISSUE TITLE
Fenix ​​79 does not correctly load almost all web pages with μblock installed

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#12688] opened 2020-07-18 01:48 UTC
User Agent: Mozilla/5.0 (Android 9; Mobile; rv:79.0) Gecko/79.0 Firefox/79.0

Steps to reproduce:

I upgrade Firefox for Android Beta (aka firefox preview) to the latest version (79.0.0-beta.9 Build #2015752523 and then almost any webpage is not displayed correctly if μblock is active

Actual results:

almost all web pages are not displayed correctly.  Usually the photos are not displayed and the page is not formatted correctly.  With μblock disabled, the pages are displayed correctly

Expected results:

The web pages should have been displayed correctly

**Comment by kbrosnan** [comment] 2020-07-18 01:50
Moved from BZ-1653722

**Comment by cadeyrn** [comment] 2020-07-18 08:13
For reference: The same was reported in the Firefox support for Firefox Nightly with uBlock Origin. Purging the filter caches solved the issue.

**Comment by vishalnandagopal** [comment] 2020-07-18 08:57
Fanboys annoyance filter list added a block all CSS rule by mistake. So that was the problem.


That and easy list cookie filter list

**Comment by csadilek** [comment] 2020-07-20 12:18
OK, thanks @cadeyrn and @vishalnandagopal. Since this was caused by "faulty" filter lists we don't control, and has since be fixed, I think we can close this.

**Closed** 2020-08-28 22:35 UTC
Labels: Feature:WebExtensions, b:web-content, needs:triage, 🐞 bug
