### ISSUE TITLE
FNX-5569 ⁃ [Bug] Constant crashes when phone comes back from being idle

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#2287] opened 2019-05-06 01:29 UTC
## Steps to reproduce
* Have Fenix actively running on the device. At some point my phone goes idle
* Unlock device and launch Fenix from the Desktop icon
* Immediate crash

### Expected behavior
* No crash when I open the app

### Actual behavior
* The browser crashes and I get the Sentry crash dialog. Crashes have been submitted. Next time I will try to get a logcat.

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1919 (#11251807)

**Comment by gaby2300** [comment] 2019-05-06 01:57
I can reproduce this with a Sony Z3C device, Android 6.0.1. Fenix build 11250615
Crash report sent.

**Comment by sblatz** [comment] 2019-05-30 21:01
I believe this crash was due to our state handling a few weeks ago and should be fixed. Can we have QA try to reproduce this?

**Comment by mozillamarcia** [comment] 2019-05-30 21:09
I haven't seen this lately running Fenix on my Pixel 3. @gaby2300 can you?

**Comment by sblatz** [comment] 2019-06-04 14:54
I'm going to move this to QA needed as I believe this is fixed.

**Comment by kbrosnan** [comment] 2019-06-04 15:45
Lets close this then. File a new issue if you see something similar again.

**Closed** 2020-08-11 14:41 UTC
Labels: Release Blocker, b:crash, 🐞 bug
