### ISSUE TITLE
Confirm that this is fixed: Home screen content hangs out of the screen

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#573] opened 2019-02-18 16:19 UTC
## Steps to reproduce
Open 3 or more tabs, depends on your screen size and resolution.

### Expected behavior
Home screen can be scrolled until the end of it's content. 

### Actual behavior
Once the search bar hits the top of the screen, the home screen can not be scrolled any further. With only two tabs the sessions placeholder already gets cut off on my device.

![screenshot_20190218-171444](https://user-images.githubusercontent.com/4500858/52963834-21b87a00-33a1-11e9-8769-56cf911d7a5d.png)

### Device information

* Android device: 7.1.1
* Fenix version: 1.0

**Comment by sv-ohorvath** [comment] 2019-02-20 09:44
I can still reproduce this on the latest Master.

**Comment by colintheshots** [comment] 2019-02-20 13:13
It's not fixed, but it happens because we haven't yet implemented the Sessions feature. It's a bug, in that it's definitely broken, but also a missing feature we expected.

**Comment by boek** [comment] 2019-02-26 03:52
This is now fixed :+1:

**Closed by boek** 2019-02-26 03:52 UTC
Labels: Feature:HomeScreen, size S, 🐞 bug

**Comment by bsurd** [comment] 2019-03-06 14:12
Verified on:
 - 1.0.1910 (Build #10642115)

 Devices:
 - Nokia 6 (Android 7.1.1)
 - HTC Desire 820 (Android 6.0.1)
