### ISSUE TITLE
[Bug]: Tab group, when opening a search tab, Other tabs appears above ordinary tabs

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#21707] opened 2021-10-05 10:22 UTC
### Steps to reproduce
1. Search for cats and open a result in a new tab (creating a search group).
1. Search for dogs and open a result in a new tab (creating a search group).
2. Open the tabs tray and delete one tab from either group.

### Expected behaviour

- Title above ordinary tabs is seen above.
- No title above ordinary tabs UNLESS there is a tab group above ordinary tabs

### Actual behaviour

The title above ordinary tabs is not seen when there are normal tabs OR title above ordinary tabs when a single search tab is opened

### Device name

Galaxy A40

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Today's

### Additional information

https://user-images.githubusercontent.com/1370580/136284826-ed2fa82b-28f4-4c73-b003-94ebf651bb5e.mp4

**Comment by SoftVision-LorandJanos** [comment] 2021-10-05 13:38
Hi @Cheap-Skate ! Thank you for the report.
I could reproduce this issue when I had lots of tabs, I then deleted the group above the "Other tabs" and repeated the steps and couldn't reproduce it anymore.
After that I cleared all the browsing data and started from scratch, accessing a few sites and then made a search, and got to tabs tray. There was no tab title above those tabs.
Could you make a video of the issue you described? Or maybe give me some extra relevant details if you discover what could help reproducing it for me as well. Maybe I needed the longer history that I had the first time I checked? I also had Inactive tabs enabled in the Tabs tray, I closed that as well. So please give me some extra details about this. Thank you!

Verified on the latest Nightly (94.0a1 - 2021-10-05T05:10:10.350256).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Redmi 11 Lite (Android 11).

**Comment by Cheap-Skate** [comment] 2021-10-05 13:46
I updated to today's Nightly and the problem no longer occurs. So it maybe fixed or may be intermittent? 

Leave this bug open for a few days, I will see if it comes back.

Thanks

**Comment by SoftVision-LorandJanos** [comment] 2021-10-05 13:50
Well as I said I was able to reproduce it at first, that was after an update to the current version, but it seemed kind of an edge case. If you discover clear steps to get to the issue from scratch, please share. Thanks again!

**Comment by SoftVision-LorandJanos** [comment] 2022-04-12 06:30
Verified on the latest Nightly 101.0a1 build (2022-04-12).
The title of the ordinary tabs ("Other tabs") is displayed when a search group is created.
The titles of the groups remain when tabs from the group are deleted until the last tab is deleted.
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-04-12 06:30 UTC
Labels: 🐞 bug, Feature:Tabs, S3, needs:triage, wontfix, qa-triaged
