### ISSUE TITLE
[Bug] remove overlay when user has opened a new tab

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#16465] opened 2020-11-09 21:06 UTC
When the user taps the new tab button, the keyboard opens automatically (this is good!) but there is an overlay on top of the new tab page so you can't directly/immediately, for example, tap on one of your top sites. You have to tap the new tab page (which makes the overlay go away) _then_ you're able to interact with it. I can't think of a reason to have it this way. Screenshot of what it looks like, the overlay makes the new tab page darker/de-emphasized. it should be removed so you can interact with it immediately please.

![Screenshot_20201109-155544](https://user-images.githubusercontent.com/47801466/98596413-6850b500-22a5-11eb-94fb-0caf17dc10ff.png)

**Comment by cadeyrn** [comment] 2020-11-09 21:21
Duplicate of #16351.

**Comment by s-ankur** [comment] 2020-11-29 21:12
This issue has now been solved

**Closed** 2020-12-18 07:03 UTC
Labels: needs:triage, 🐞 bug
