### ISSUE TITLE
[Bug]: Copy Link Doesn't Work In Webview Mode

### ISSUE THREAD

**Issue by iSmokeMid69** [mozilla-mobile/fenix#28308] opened 2022-12-24 16:14 UTC
### Steps to reproduce

Set FireFox Mobile As Default Browser
Open Links From Other Apps
Click Three Dot>Copy Link>It Doesn't Work

Although Sometimes It Does Copy..I Guess It Depends On The Link ?...From My Testing It Cant Copy Mega.nz Links..Dont Know About Other Links
### Expected behaviour

It Should Copy The Link

### Actual behaviour

It Doesn't Copy The Link

### Device name

Poco X3 Pro

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22192)

**Comment by amocirean** [comment] 2023-01-03 14:11
Hello @iSmokeMid69 , thank you for submitting the issue.
I was not able to reproduce the issue on the latest Nightly (110.0a1) from 03.01.2023, latest Beta (109.0b4) or latest RC (108.1.1) builds.
Could you please tell us if the issue is still reproducible on the latest Nightly?
Tested on: Samsung Galaxy S22 Ultra (Android 13), Huawei P40 Lite (Android 10), Oppo Find X3 Neo (Android 11).
Thanks!

**Comment by csadilek** [comment] 2023-01-25 16:56
> Okay So I Tested With Another Browser And Issue Seems To Be The Same..Maybe Device Issue Or MiUi Restrictions 🙃

Thanks, closing because this is not a Firefox issue.

**Closed by csadilek** 2023-01-25 16:56 UTC
Labels: 🐞 bug, needs:triage, qa-triaged
