### ISSUE TITLE
[Bug] Add UNDO snackbar when deleting tabs from the collection

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4238] opened 2019-07-23 09:42 UTC
## Steps to reproduce
1. Create a collection with a few tabs.
2. Delete one of the tabs from the created collection.

### Expected behavior
An UNDO snackbar should be displayed.

### Actual behavior
No snackbar is displayed.

### Device information
* Android device: all
* Fenix version: RC v1.1.0-rc.2

**Comment by sv-ohorvath** [comment] 2019-07-23 10:41
duplicate of #2725

**Closed by sv-ohorvath** 2019-07-23 10:41 UTC
Labels: Feature:Collections, S2, 🐞 bug
