### ISSUE TITLE
There should be an Open in App option in Custom Tabs

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9492] opened 2020-03-29 11:32 UTC
### Why/User Benefit/User Problem
Right now if you want to open youtube links from other apps, there is a three step process of opening the custom tab, opening it in Firefox and then opening in the app itself. I think it would be better if we had a direct open in app option in the three dot menu in custom tabs
### What/Requirements
A way to open in app from custom tabs
### Acceptance Criteria (how do I know when I’m done?)
The option should be added to the three dot menu

**Comment by vesta0** [comment] 2020-05-11 20:58
@brampitoyo any user experience concerns around adding this option?

**Comment by AmyYLee** [comment] 2020-06-03 21:24
Assigning to @brampitoyo @apbitner

**Comment by apbitner** [comment] 2020-06-04 14:28
@vesta0 when opening a Youtube link from another app, shouldn't it respect the OS preference of how it should be opened? I thought our 'open in app' feature was meant to address links that're opened _within_ the browser.

**Comment by brampitoyo** [comment] 2020-06-08 04:11
Hi @vesta0, I don’t see any UX concern around adding an “Open in App” option in our custom tabs.

@apbitner is correct. The “open in app” setting was meant for when links are opened within the Fenix app.

When links are opened from another app via the Fenix custom tab (which in this case is acting more like an intermediary single-tab rather than a full app), then our policy should follow that which is set under Android System Settings → Default apps → Opening links. In most cases, the default Android System policy is to open link in their respective apps. Our custom tab should respect that.

So, in this scenario:

- Set Fenix as a default browser
- Open Twitter app
- Tap on a Reddit link that’s contained within a tweet
- Fenix custom tabs open, showing Reddit
- The Reddit page shows a link that says “Open in Reddit app”
- Tap the “Open in Reddit app” link

Should we open the Reddit app, or keep opening the link in our custom tab? We should do the former.

**Comment by s-ankur** [comment] 2020-07-29 20:52
@brampitoyo Hi, I noticed something today that does not fit your logic.
Here is the STR
Send yourself an email using the gmail app containing a twitter.com link
Have the Twitter app installed and have fenix as the default browser
Open the Twitter link
It opens in a custom tab and not the Twitter app
Why? Because of Google's redirect urls
So basically  in this scenario having an open in app option will be very helpful especially if you use Gmail a lot

**Comment by brampitoyo** [comment] 2020-07-30 01:33
@s-ankur Interesting. Your scneario doesn’t match my experience.

I’ve set my browser to Firefox (which has since upgraded to Fenix – I’m in the NZ locale):

<img width="360" src="https://user-images.githubusercontent.com/51007/88869076-f6a8aa00-d265-11ea-8ad9-1afb5dd33339.png">

When I open a Twitter link via Gmail, the system skips the Firefox in-app browser and goes straight to the Twitter app.

![Twitter](https://user-images.githubusercontent.com/51007/88869352-a716ae00-d266-11ea-84a1-b060e6b17598.gif)

When I open a YouTube link, the in-app browser is also skipped. I am redirected to the YouTube app.

![YouTube](https://user-images.githubusercontent.com/51007/88869541-302de500-d267-11ea-96b9-f02e01414aea.gif)

I get the same behaviour when opening a Reddit link on Gmail. The Reddit app is instantly opened.

![Reddit](https://user-images.githubusercontent.com/51007/88869672-800cac00-d267-11ea-81e2-b2c28a8bd890.gif)

The Instagram link seems to be an outlier: it opens the Firefox in-app browser by default. However, the website quickly shows me a button to open the Instagram app.

![Instagram](https://user-images.githubusercontent.com/51007/88870048-70419780-d268-11ea-92dc-490d9408e46c.gif)

And if you tap “Not now”, you can still access “Open in app” in the custom tab’s three-dot menu.

<img width="360" src="https://user-images.githubusercontent.com/51007/88870320-2ad19a00-d269-11ea-9e09-57126ffef9ae.png">

Does this solve your original issue of “A way to open in app from custom tabs. The option should be added to the three dot menu”?

**Comment by s-ankur** [comment] 2020-09-11 13:17
Hi, this does solve my use case, thank you!

**Comment by lbalmaceda** [comment] 2020-09-18 21:41
@brampitoyo hey good detail there in all those use cases. I wonder if you ever found out what was doing different Instagram that it didn't open the link automatically in their application that you seem to have installed, but rather used the browser instead? 

I'm running into a similar situation when using Android App Links. However, unless we host browsable content in the link we want to use (A callback URL), there's no indication for the user to continue to the app. And IMO, the "Open in app" option seems a bit hidden under the rug for the typical user. 

I've created https://github.com/mozilla-mobile/fenix/issues/15202

**Comment by apbitner** [comment] 2020-10-20 14:24
@brampitoyo solved for the issue in his comment above, which I'll copy here, showing the addition of `Open in app` to the 3-dot menu of a custom tab.

![image](https://user-images.githubusercontent.com/22176302/96599673-c9dcbf80-12b5-11eb-92e5-89b9d35d5a2f.png)

**Comment by mcarare** [comment] 2020-10-26 13:45
For QA: Please test this, it seems to be fixed since the time it was opened. Thank you!

Note: I could not reproduce this issue (having a link from Gmail opened in Fenix custom tab when app to handle it is installed), but the "Open in App " option is present in custom tabs, same as in normal ones.
To reproduce this issue, have the handling app (Twitter, Instagram) installed after you open the link from Gmail.

**Comment by sflorean** [comment] 2020-10-27 14:13
Tested on the latest Nightly build:
STR
Open twitter link from Gmail, in a custom tab.
Install Twitter.
Check Custom tab opened previously -> Result: "Open in app" option is displayed in custom tab -> three dot-menu. 

STR
Install Twitter.
Open twitter link from Gmail, in a custom tab. -> Result: the Twitter app is opened.

**Comment by mcarare** [comment] 2020-11-05 12:39
Closing this as per the comment above.

**Closed** 2020-11-05 12:41 UTC
Labels: Feature:OpenInApp, eng:ready, hershey
