### ISSUE TITLE
[Bug] Red buttons on Android 5 devices

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#8524] opened 2020-02-19 09:19 UTC
## Steps to reproduce
1. Install the latest Nightly/Beta 4.0 build.
2. Go to Settings menu & sub-menus.
3. Observe the buttons: back buttons, radio buttons/ unselected checkboxes.
### Expected behavior
Black buttons/ according to the selected theme.
### Actual behavior
Red buttons, scroll bar, checkboxes, in both light & dark theme in the Settings menu.

LE: the Request desktop site from the main menu is also in red.
### Device information

* Android device: Nexus 4 (Android 5.1.1), Xiaomi Mi Pad 2 (Android 5.1)
* Fenix version: Nightly 2/19, Beta 4.0

**Comment by AndiAJ** [comment] 2020-02-24 08:02
Hi @ekager , still reproducible on the latest `Nightly Build #20550606 from 02/24 `using the • LG Nexus 4 (Android 5.1.1)

►Screenshot
![rsz_screenshot_2020-02-24-09-49-36 (2)](https://user-images.githubusercontent.com/51314259/75136233-b197af00-56ec-11ea-82b2-aafb80515e97.png)

![rsz_screenshot_2020-02-24-09-57-54](https://user-images.githubusercontent.com/51314259/75136237-b4929f80-56ec-11ea-8bfc-ce0b7ef7364c.png)

**Comment by AndiAJ** [comment] 2020-02-25 08:11
Hi, unfortunately it's **still reproducible** on the latest **`Nightly Build #20560606`** from 02/25 using the following devices:
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

On the LG Nexus the "Desktop site " is always red while using the "Dark" theme.
On the OnePlus the "Delete browsing data" turns to red after changing a couple of times Fenix's theme. 

► Screenshot OnePlus A3
![rsz_1rsz_screenshot_20200225-094904](https://user-images.githubusercontent.com/51314259/75227629-318a4b80-57b7-11ea-91d3-876371646ee1.png)


► Screenshot LG Nexus 4 
![rsz_screenshot_2020-02-25-09-51-31](https://user-images.githubusercontent.com/51314259/75227237-795ca300-57b6-11ea-9dbd-18c00c219614.png)

**Comment by sv-ohorvath** [comment] 2020-02-27 09:05
Add the download confirmation dialog to this as well.

**Comment by ekager** [comment] 2020-02-28 06:17
Alright, let's try again 😅 
Couldn't reproduce the "Delete Browsing Data" trash icon one but I _think_ I got the others (at least on my emulator)

**Comment by softvision-miralobontiu** [comment] 2020-02-28 14:39
This is not fixed entirely yet: the "+" icon from Settings-Add-ons is red, both in light theme, and dark theme.
The rest of the buttons/items are displayed correctly.
Verified on the latest Nightly build from 2/28, and on Beta V4.0.0-beta.2, with Xiaomi Mi4i (Android 5.0.2), and Xiaomi MiPad 2 (Android 5.1).

![Screenshot_2020-02-28-16-32-33-219_org mozilla fenix nightly](https://user-images.githubusercontent.com/40694158/75557302-77117780-5a48-11ea-961b-9f51704ace0a.png)

**Comment by ekager** [comment] 2020-03-02 03:46
Okay let's close this ticket now for #8641 since I think the remaining issues overlap :)

**Closed by ekager** 2020-03-02 03:46 UTC
Labels: Feature:Settings, S3, 🐞 bug
