### ISSUE TITLE
[Bug]: Cannot re-search a highlighted word immediately after returning from initial search

### ISSUE THREAD

**Issue by JPDucky** [mozilla-mobile/fenix#25047] opened 2022-04-30 20:09 UTC
### Steps to reproduce

1. Tap and hold to highlight a word for search
2. Press search in the menu and Firefox will search said word
3. Return from search to previous page
4. Highlight the same word
5. Press search again

### Expected behaviour

It should initiate the search for the highlighted word

### Actual behaviour

Nothing happens, other than the "search" option in the highlight menu indicates that it HAS been pressed by changing colors, but no action is taken. Additionally, the "search" option can be tapped repeatedly without the highlight menu closing. 

### Device name

Samsung Galaxy S21 Ultra

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

99.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20334)

**Comment by JPDucky** [comment] 2022-04-30 20:16
Unsure why I couldn't add this via mobile but here is a screen recording search bug https://imgur.com/a/mAujFgC

**Comment by amocirean** [comment] 2022-05-05 13:48
Hello @JPDucky, thank you for submitting the issue.
I was able to reproduce it on the latest RC, Nightly or Beta.

Device Used: Huawei P40 Lite
Android Version: 10

**Comment by Alexandru2909** [comment] 2022-05-09 13:07
I believe this is because we compare two similar search requests [here](https://github.com/mozilla-mobile/android-components/blob/be0d8903cd7b6378d9057af19c78c47de17b734b/components/feature/search/src/main/java/mozilla/components/feature/search/SearchFeature.kt#L48). Since the `SearchFeature` is not restarted when switching tabs in Fenix and the null search requests are [discarded](https://github.com/mozilla-mobile/android-components/blob/be0d8903cd7b6378d9057af19c78c47de17b734b/components/feature/search/src/main/java/mozilla/components/feature/search/SearchFeature.kt#L45), searching the same word leads to comparing the previous search request with an identical new request.

**Comment by Yetoo1** [comment] 2022-06-28 16:52
@Alexandru2909 I don't see why stopping null requests from being discarded fixes this issue. Removing just [this line](https://github.com/mozilla-mobile/android-components/blob/be0d8903cd7b6378d9057af19c78c47de17b734b/components/feature/search/src/main/java/mozilla/components/feature/search/SearchFeature.kt#L48) will do the job. I manually tested this PR (#10022) (which was intended to fix this issue: https://github.com/mozilla-mobile/fenix/issues/18565 on different tracker) and duplicate searches were able to be performed.

**Comment by SoftVision-LorandJanos** [comment] 2022-06-30 05:28
Verified as fixed on the latest Nightly 104.0a1 (2022-06-30) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as Verified.

**Closed by SoftVision-LorandJanos** 2022-06-30 05:28 UTC
Labels: 🐞 bug, eng:qa:needed, Feature:Search, Feature:TextSelection, qa-triaged
