### ISSUE TITLE
Address bar

### ISSUE THREAD

**Issue by softbanana55** [mozilla-mobile/fenix#9518] opened 2020-03-30 13:49 UTC
Love the search/address bar at the bottom of the screen, it helps with one handed use and is more usable on larger phones, especially as they're getting larger these days.

However, why is the address bar thrown to the top of the screen when the keyboard is in use? Kind of defeats the purpose and is now *less* usable.

Suggestion to place the search/address bar on top of the keyboard instead? See mock-up 

![PicsArt_03-30-09 29 05](https://user-images.githubusercontent.com/62890759/77919454-34bba000-726b-11ea-9770-712d938cdc70.jpg)

**Comment by 90du** [comment] 2020-03-30 14:01
Yes i agree

**Comment by SL-Lee** [comment] 2020-03-30 14:27
Looks like a duplicate of #7461.

**Comment by mcarare** [comment] 2020-03-30 16:27
Closing as duplicate

**Closed by mcarare** 2020-03-30 16:27 UTC
Labels: needs:triage, 🌟 feature request
