### ISSUE TITLE
[Bug]Checks to delete browsing data are not saved

### ISSUE THREAD

**Issue by moon1618** [mozilla-mobile/fenix#9229] opened 2020-03-18 16:28 UTC
Delete browsing data in settings
Even if you uncheck the items you do not want to delete
When you open it again, everything is checked
Is it a bug that settings are not saved?

**Comment by sv-sdeiac** [comment] 2020-03-19 11:54
Hello @moon1618, thanks for your report.
I tried to reproduce your issue and the items unchecked are not saved after reopening the "Delete browsing data" section.

#### Devices:
- Google Pixel 3 (Android Q);
- LG g7 fit (Android 8.1).

#### Build:
- Firefox Preview Nightly 3/19 #20790605.

#### Notes:
- Since the "Delete browsing data on quit" save the last changes, there is an expectation to be saved also in the "Delete browsing data".

**Comment by FoxDie12x** [comment] 2020-03-19 13:07
I'd like to be assigned to this issue.

**Comment by moon1618** [comment] 2020-04-05 09:51
Please add a save function for this check as soon as possible.
It is inconvenient to check every time you delete history.
I'm worried that I might delete the necessary things by mistake.

**Comment by FoxDie12x** [comment] 2020-04-05 23:43
I'll get back to this issue tomorrow and see if I can get a fix for it. Sorry, didnt have the time lately.

**Comment by moon1618** [comment] 2020-05-17 12:16
Is there no progress on this issue?
Firefox Beta 76.0.0-beta.2 still can't save settings.
Is it a bug?
Or did you decide to uncheck it every time?

**Comment by ekager** [comment] 2020-05-19 02:09
It is intentional currently that we are checking every box, but I can see how one could expect these to be saved for quicker deletion.

**Comment by AmyYLee** [comment] 2020-06-03 22:40
>     * Since the "Delete browsing data on quit" save the last changes, there is an expectation to be saved also in the "Delete browsing data".

Agreed these should be consistent and saves last changes. @brampitoyo to confirm.

**Comment by brampitoyo** [comment] 2020-06-08 06:13
I am confirming @AmyYLee’s statement. @moon1618’s expectation is correct. Items that are checked/unchecked within “Delete browsing data” should be remembered across sessions.

This means that, if you choose to delete everything but Open tabs, Fenix should remember that, and not offer to check Open tabs the next time you access this Settings sub-page.

**Comment by mcarare** [comment] 2020-06-11 14:34
@brampitoyo It is my understanding that these options should be saved independently from the ones in "delete browsing data on quit" ?

Also, on checking this, I noticed that there are some noticeable inconsistencies between the two screens (option name, option description font- see below) and a strange large space on the first screen. Can you also please also give some feedback on that? (If necessary open a new issue). Thank you!

<img src = https://user-images.githubusercontent.com/48995920/84398967-41fcef80-ac09-11ea-9507-1457e63e4bef.png width = 48%> <img src = https://user-images.githubusercontent.com/48995920/84398992-488b6700-ac09-11ea-9ddb-f0bc0f5183d5.png width = 48%>

**Comment by brampitoyo** [comment] 2020-06-15 01:58
@mcarare You’re correct. The options on “Delete browsing data on quit” should be independent from “Delete browsing data”.

I will open a new issue to address design inconsistency and CC you on it.

**Comment by AndiAJ** [comment] 2020-06-22 06:32
Hi, **verified as fixed** on the latest **`Nightly Build 200622 from 6/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200622-092515](https://user-images.githubusercontent.com/51314259/85255573-36ac8e00-b46b-11ea-8ee0-1504e56ac371.gif)

**Closed by AndiAJ** 2020-06-22 06:32 UTC
Labels: E5, Feature:Settings, S2, eng:qa:needed, eng:ready, 🐞 bug
