### ISSUE TITLE
App names not visible or barely visible in share sheet

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#20352] opened 2021-07-13 12:35 UTC
# Issue

The app names in the share sheet are either not visible at all (in the section for often used apps) or barely visible (in the section for all apps). Note that the device names, although blurred for privacy, do not have this issue.

# Screenshot

![Screenshot_20210713_143027.jpg](https://user-images.githubusercontent.com/20287690/125452265-a99b7875-7532-4529-8c35-3cb07e118928.jpg)

# Device and app version

Fenix: 
91.0a1 (Build #2015821707)
AC: 91.0.20210710190117, 099c7dbce1
GV: 91.0a1-20210710094507
AS: 79.0.0

Device: 
Huawei Mate 20 lite, EMUI 10 (Android 10)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17238)

**Comment by sflorean** [comment] 2021-07-14 13:52
Tested on Nightly 7/14 and here are the results:
- LG G7 Fit (Android 8.1) - reproducible 
- Samsung Note 10 (Android 11) - not reproducible
On Chrome, with the affected device, the issue is not reproducible.

**Comment by anotherus3r** [comment] 2022-01-10 17:16
Still an issue on latest Nightly (2022-01-08T17:13:45.860487)

**Comment by anotherus3r** [comment] 2022-07-30 12:04
Seems to be fixed? Could you confirm on your affected devices, @sflorean ?

**Comment by topotropic** [comment] 2022-10-28 08:41
Is it still reproducable that the app names are not visible or can we close it, @sflorean? thanks!

**Comment by cpeterso** [comment] 2023-01-12 05:25
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809784

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2023-01-12 05:25 UTC
Labels: S3, Feature:Sharing, needs:triage, qa-triaged
