### ISSUE TITLE
show top sites when clicking the address bar

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17851] opened 2021-02-05 12:22 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
To visit a top site app from a tab one has to click multiple times. This can be reduced by showing the top sites on clicking the address bar similar to yandex browser 

### How do you know that this problem exists today? Why is this important?

Too many clicks required to access top sites from an opened tab

### Who will benefit from it?
All users

**Comment by sheikh-azharuddin** [comment] 2021-02-05 12:26
![Screenshot_20210205-175128111](https://user-images.githubusercontent.com/58127841/107033566-801fd280-67db-11eb-812e-a9a119e4caed.jpg)

**Comment by violasong** [comment] 2021-02-10 18:13
Closing as duplicate of https://github.com/mozilla-mobile/fenix/issues/9118

**Closed by violasong** 2021-02-10 18:13 UTC
Labels: Feature:Search, needs:UX-feedback
