### ISSUE TITLE
FNX-5379 ⁃ Show individual Tracking Protection lists

### ISSUE THREAD

**Issue by SKITTLE-LA** [mozilla-mobile/fenix#1983] opened 2019-04-24 15:41 UTC
### Why/User Benefit/User Problem
Users can individually enable/disable lists to their liking. Increases transparency.

### What / Requirements
List _Trackers, Cookies, Cryptominers, Fingerprinters_ (just like Desktop).
Also display option to block only in Private Mode, or all the time.

**Comment by cadeyrn** [comment] 2019-04-25 07:20
Duplicate of #1085.

**Closed** 2020-08-11 13:31 UTC
