### ISSUE TITLE
[Startup Crash] RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: java.lang.IllegalArgumentExcepti...

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#6441] opened 2019-11-04 20:52 UTC
https://sentry.prod.mozaws.net/operations/fenix/issues/6601427/

```
IllegalArgumentException: Unexpected format in VersionString
    at org.mozilla.fenix.FenixApplication.setupApplication(FenixApplication.kt:94)
    at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:2)
...
(10 additional frame(s) were not displayed)

RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: java.lang.IllegalArgumentException: Unexpected format in VersionString
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5506)
    at android.app.ActivityThread.-wrap2(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:203)
...
(4 additional frame(s) were not displayed)

Unable to create application org.mozilla.fenix.FenixApplication: java.lang.IllegalArgumentException: Unexpected format in VersionString
```

**Comment by agi90** [comment] 2019-11-04 20:52
Fenix crashes 100% of the time at startup, latest nightly. Clearing cache doesn't help.

Android 9, Samsung S10e

**Comment by agi90** [comment] 2019-11-04 21:25
Sentry issue: [FENIX-NIGHTLY-10K](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6601433/)

**Comment by gaby2300** [comment] 2019-11-04 21:46
Android 6.0.1  Sony Xperia z3c also crashes at startup

**Comment by LittleAngelwings** [comment] 2019-11-05 04:37
Have also this issue

`11-05 05:23:23.369 E/AndroidRuntime(22917): Process: org.mozilla.fenix.nightly, PID: 22917
11-05 05:23:23.369 E/AndroidRuntime(22917): java.lang.RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: java.lang.IllegalArgumentException: Unexpected format in VersionString
11-05 05:23:23.369 E/AndroidRuntime(22917): 	at mozilla.components.service.experiments.util.VersionString.compareTo(VersionString.kt:11)
11-05 05:23:23.369 E/AndroidRuntime(22917): 	at mozilla.components.service.experiments.ExperimentEvaluator.findActiveExperiment$service_experiments_release(ExperimentEvaluator.kt:30)
11-05 05:23:23.369 E/AndroidRuntime(22917): 	at mozilla.components.service.experiments.ExperimentsInternalAPI.findAndStartActiveExperiment$service_experiments_release(Experiments.kt:4)
11-05 05:23:23.369 E/AndroidRuntime(22917): 	at org.mozilla.fenix.FenixApplication.setupApplication(FenixApplication.kt:98)
11-05 05:23:23.369 E/AndroidRuntime(22917): 	at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:2)
11-05 05:23:24.637 E/WindowManager(2944): win=Window{43d725a u0 Splash Screen org.mozilla.fenix.nightly EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0, caller=com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5646 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:517 com.android.server.wm.AppWindowToken.stepAppWindowsAnimation:1745 
11-05 05:23:27.664 E/WindowManager(2944): win=Window{c1f06cc u0 org.mozilla.fenix.nightly/mozilla.components.lib.crash.prompt.CrashReporterActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0, caller=com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5646 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:517 com.android.server.wm.TaskStack.stepAppWindowsAnimation:2021`

Latest Nightly on Android 8.1.0 Samsu g Galaxy Tab A 580

**Comment by andreicristianpetcu** [comment] 2019-11-05 06:22
my stable fenix is also crashing on startup

**Comment by ekager** [comment] 2019-11-05 07:06
Thank you all for reporting! I have hopefully merged a fix in AC for this from @mythmon but it will take a bit to build the AC snapshot and get a new Nightly.
https://github.com/mozilla-mobile/android-components/issues/4957

**Comment by Rob--W** [comment] 2019-11-05 11:12
This occurred to me on Preview version "Nightly 190928 06:01" (I am not auto-updating). The app worked fine last weekend, but started to crash last night.

**Comment by staktrace** [comment] 2019-11-05 11:54
@ekager can you please post here when the build with the fix is published to the play store? Thanks!

**Comment by gaby2300** [comment] 2019-11-05 13:43
I also have the following issue: the app keeps opening by it's self. Should
I create a new issue?

**Comment by AndiAJ** [comment] 2019-11-05 14:03
Hi, same on  **Nightly 191105 06:01 (Build #13090608) 📦: 20.0.0, 1bae81951 🦎: 72.0a1-20191103094618** using:

• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Crash log
`--------- beginning of crash
2019-11-05 15:40:40.172 14649-14649/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 14649
    java.lang.RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: java.lang.IllegalArgumentException: Unexpected format in VersionString
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: Unexpected format in VersionString
        at mozilla.components.service.experiments.util.VersionString.compareTo(VersionString.kt:11)
        at mozilla.components.service.experiments.ExperimentEvaluator.findActiveExperiment$service_experiments_release(ExperimentEvaluator.kt:30)
        at mozilla.components.service.experiments.ExperimentsInternalAPI.findAndStartActiveExperiment$service_experiments_release(Experiments.kt:4)
        at org.mozilla.fenix.FenixApplication.setupApplication(FenixApplication.kt:98)
        at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:2)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-11-05 15:40:40.172 14649-14672/? D/App: Experiments active: {asFeatureSyncDisabled=false}
2019-11-05 15:40:40.172 14649-14649/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: java.lang.IllegalArgumentException: Unexpected format in VersionString, breadcrumbs=[])
2019-11-05 15:40:40.173 14649-14649/? I/mozac/CrashReporter: Showing prompt
2019-11-05 15:40:40.174 14649-14669/? E/GeckoLibLoad: Load sqlite done
2019-11-05 15:40:40.174 14649-14669/? E/GeckoLibLoad: Load nss start
2019-11-05 15:40:40.174 14649-14669/? E/GeckoLibLoad: Load nss done
2019-11-05 15:40:40.175 14649-14669/? W/GeckoLinker: /data/app/org.mozilla.fenix.nightly-IAGyNfpglfY2FZ1lZZ_36A==/lib/arm/libxul.so: unhandled flags #8 not handled
2019-11-05 15:40:40.175 14649-14669/? W/GeckoLinker: /data/app/org.mozilla.fenix.nightly-IAGyNfpglfY2FZ1lZZ_36A==/lib/arm/liblgpllibs.so: unhandled flags #8 not handled
2019-11-05 15:40:40.182 1171-1561/? I/ActivityManager: START u0 {flg=0x10018000 cmp=org.mozilla.fenix.nightly/mozilla.components.lib.crash.prompt.CrashReporterActivity (has extras)} from uid 10170
2019-11-05 15:40:40.185 767-767/? D/android.hardware.power@1.3-service.bonito-libperfmgr: LAUNCH ON
2019-11-05 15:40:40.191 1171-1196/? I/ActivityManager: Showing crash dialog for package org.mozilla.fenix.nightly u0
2019-11-05 15:40:40.194 1171-1195/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2019-11-05 15:40:40.195 1171-1195/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2019-11-05 15:40:40.202 14649-14669/? E/GeckoLibLoad: Loaded libs in 27.382919ms total, 13ms(26ms) user, 0ms(6ms) system, 0(0) faults
2019-11-05 15:40:40.202 14649-14669/? D/GeckoThread: State changed to LIBS_READY
2019-11-05 15:40:40.202 14649-14669/? W/GeckoThread: zerdatime 2254382 - runGecko
2019-11-05 15:40:40.209 14649-14669/? D/GeckoProfile: Loading profile at: null name: default
2019-11-05 15:40:40.210 14649-14669/? D/GeckoProfile: Found profile dir: /data/user/0/org.mozilla.fenix.nightly/files/mozilla/d71t33mc.default
2019-11-05 15:40:40.218 1171-1197/? I/ActivityManager: Start proc 14686:org.mozilla.fenix.nightly:tab/u0a170 for service org.mozilla.fenix.nightly/org.mozilla.gecko.process.GeckoServiceChildProcess$tab
2019-11-05 15:40:40.222 1171-6599/? E/libc: Access denied finding property "vendor.debug.egl.changepixelformat"
2019-11-05 15:40:40.227 14686-14686/? E/nix.nightly:ta: Not starting debugger since process cannot load the jdwp agent.
2019-11-05 15:40:40.252 1171-6599/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2019-11-05 15:40:40.256 1171-6599/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2019-11-05 15:40:40.263 14686-14686/? I/nix.nightly:ta: The ClassLoaderContext is a special shared library.
2019-11-05 15:40:40.267 1171-6599/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2019-11-05 15:40:40.271 14686-14686/? W/nix.nightly:ta: resources.arsc in APK '/data/app/org.mozilla.fenix.nightly-IAGyNfpglfY2FZ1lZZ_36A==/base.apk' is compressed.
2019-11-05 15:40:40.292 14686-14686/? W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2019-11-05 15:40:40.292 14686-14686/? W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
2019-11-05 15:40:40.292 14686-14686/? W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2019-11-05 15:40:40.293 14686-14686/? D/io.sentry.android.AndroidSentryClientFactory: Construction of Android Sentry.`

**Comment by jrmuizel** [comment] 2019-11-05 14:19
I was able to get Fenix Nightly 191105 06:01 working again by clearing the apps storage and cache.

**Comment by jrmuizel** [comment] 2019-11-05 14:33
But then the problem came back after a short time of use.

**Comment by andreicristianpetcu** [comment] 2019-11-05 21:49
Nightly is fixed for me. https://tools.taskcluster.net/index/project.mobile.fenix.v2.nightly/latest

Production is still broken https://tools.taskcluster.net/index/project.mobile.fenix.v2.fennec-production/latest

**Comment by ekager** [comment] 2019-11-05 22:05
Yes the newest Nightly should fix this crash. Please let us know if you're still seeing this in Nightly

**Comment by liuche** [comment] 2019-11-05 22:16
> Production is still broken https://tools.taskcluster.net/index/project.mobile.fenix.v2.fennec-production/latest

This is the FennecProduction build, which would be something that @pocmo would know more about that, but it's been broken for all the Nightly builds that I have triggered recently https://tools.taskcluster.net/groups/WwjSGdhNQbSMpxcaB0Ub7w

**Comment by dbaron** [comment] 2019-11-05 22:24
I'm still seeing 100% crashes with the nightly that came out a few hours ago.

**Comment by dbaron** [comment] 2019-11-05 22:27
Fixed for me in the nightly that just came out (was still broken in one that came out a few hours ago).

**Comment by LittleAngelwings** [comment] 2019-11-05 22:28
This new build via Play Store starts without a crash: Nightly 191105 20:32 (Build #13092042)
📦: 20.0.0, 1bae81951
🦎: 72.0a1-20191103094618

**Comment by gaby2300** [comment] 2019-11-06 00:39
I can confirm the above build starts without crashing.
Sony Xperia z3c and Android 6.0.1

**Comment by softvision-miralobontiu** [comment] 2019-11-06 08:21
Verified that the latest Nightly builds from 11/06 (#13100629, #13100630) doesn't crash. 
I installed the build from Play Store, and the taskcluster page, on the following devices:
- Sony Xperia Z2 tablet (Android 6.0.1),
- Google Pixel (Android Q),
- Nexus 5 (Android 6.0.1).

**Closed by softvision-miralobontiu** 2019-11-06 08:21 UTC
Labels: P1, b:crash, eng:qa:needed

**Comment by liuche** [comment] 2019-11-07 22:18
This bug has exposed some more issues 

- better testing of upstream changes that come down to fenix
- smoketesting Nightly
