### ISSUE TITLE
[Bug] Sync shows Last synced: 2 days ago even after sucessfull manual sync

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#10149] opened 2020-04-23 15:31 UTC
Android 9 OP3T, LineageOS 16, Fenix 4.3.0 (build #21082025)

![image](https://user-images.githubusercontent.com/14617699/80118081-9a602b00-8590-11ea-919c-ab3aa7a478f4.png)

**Comment by ekager** [comment] 2020-06-09 22:23
@532910 thanks for reporting! Have you seen this again in newer versions of Fenix?

**Comment by 532910** [comment] 2020-06-09 22:36
Yes, I see the same issue with 5.1.1 (Build #21571852) (But now it says 6 days ago)

**Comment by jdragojevic** [comment] 2020-07-15 17:23
Assuming this is still an on-going issue, might there be something in the logs that would help us track this down?  Any idea how widespread the issue is?

**Comment by 532910** [comment] 2020-08-23 21:00
Works fine now, is it fixed?

**Comment by kbrosnan** [comment] 2020-08-27 05:38
We think so. Thank you for the update! closing.

**Closed by kbrosnan** 2020-08-27 05:38 UTC
Labels: Feature:Sync, a-s, needs:investigation, 🐞 bug
