### ISSUE TITLE
[Bug]: drop down menus not working

### ISSUE THREAD

**Issue by Heclalava** [mozilla-mobile/fenix#23386] opened 2022-01-25 00:56 UTC
### Steps to reproduce

This previously was not an issue, but from 2 versions ago I'm unable to access any of the drop down menus in my router interface. I have a VPN built in to the router, and when I select the drop down menu to access the VPN server list, or any other drop down menus in the router interface the pop up window to make my selection is no longer accessible. If I use another browser (Firefox for Linux, Chrome mobile) I get the expected behaviour. 

I have tried to clear that app data from Firefox nightly, and reinstall the application. The behaviour persists. 

### Expected behaviour

A menu should open when tapping the drop down menu.

### Actual behaviour

Nothing happens when tapping the drop down menu. 

### Device name

OnePlus 6

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1 (Build #2015859243), 3e796726d+ AC: 98.0.20220123143137, de26ff7e53 GV: 98.0a1-20220123093907 AS: 90.0.0

**Comment by cadeyrn** [comment] 2022-01-25 07:29
Duplicate of #23370 that was closed as an duplicate of the upstream issue https://bugzilla.mozilla.org/show_bug.cgi?id=1751674. An fix is already in progress.

**Closed** 2022-01-25 08:05 UTC
Labels: 🐞 bug, needs:triage
