### ISSUE TITLE
add an option to disable chrome/UI animations

### ISSUE THREAD

**Issue by bogas04** [mozilla-mobile/fenix#13994] opened 2020-08-20 21:51 UTC
### What is the user problem or growth opportunity you want to see solved?

For people who prefer reduced motion in Firefox, an option could be introduced that disables animations in Firefox UI (tab tray, settings etc.).

### How do you know that this problem exists today? Why is this important?

There's no setting to disable UI animations.

### Who will benefit from it?

People suffering from difficulties with fast motions and other users who prefer no animations.

**Comment by cadeyrn** [comment] 2020-08-20 22:00
> and/or turns on prefers-reduced-motion media query for websites

It doesn't really make sense to have an option for that on the application level. There is an Android option and that should be respected. And that's a duplicate of #3597.

**Comment by ekager** [comment] 2020-12-18 04:45
Closing for #3597.

**Closed by ekager** 2020-12-18 04:45 UTC
Labels: needs:triage
