### ISSUE TITLE
66ms regression in cold view nav start, 56ms in cold main first frame (6/9/22)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#25607] opened 2022-06-13 21:38 UTC
_see also ~69ms regression to focus cold main first frame on 6/10: https://github.com/mozilla-mobile/focus-android/issues/7216_

We see a regression of 66ms to the minimum replicate (we used the minimum replicate because the median replicate changed due to bimodal behavior https://github.com/mozilla-mobile/fenix/issues/22144) in cold view nav start from Nightly 6/8 (1875ms) to Nightly 6/9 (1941ms):

![image](https://user-images.githubusercontent.com/759372/173448868-2de6d3ae-ec5a-464c-b450-5267a635aecc.png)

We see a similar 56ms regression in cold main first frame on the same dates (1.480s to 1.536s, caveat that we took the median during bimodal behavior https://github.com/mozilla-mobile/fenix/issues/25545):
![image](https://user-images.githubusercontent.com/759372/173449275-ea2c1d0d-89ce-46b0-b265-0cf01712b6a7.png)

I also found details on the cold main first frame regression while verifying the fix for #25545 – see https://github.com/mozilla-mobile/fenix/issues/25545#issuecomment-1154316663.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20699)

**Comment by MatthewTighe** [comment] 2022-06-13 23:55
Since this regression appears to be affecting Focus as well, I think it's likely to be unrelated to #25545. See https://github.com/mozilla-mobile/fenix/issues/25545#issuecomment-1154560302

**Comment by Amejia481** [comment] 2022-06-23 16:25
After some research,**I think what could be causing the regression is a glean update API**, in [Fenix](https://github.com/mozilla-mobile/fenix/pull/25434) and in [Focus](https://github.com/mozilla-mobile/focus-android/pull/7135). @mcomella please would you mind giving me a hand by double checking. Below the details on how I arrived to this conclusion. Maybe during the day I would be able to take a profile to see which specifically could be the root cause. 

### Findings.
As the regression is common between [Focus](https://github.com/mozilla-mobile/focus-android/issues/7216) and [Fenix](https://github.com/mozilla-mobile/fenix/issues/25607), this give us some hints that whatever is causing the regression should in both apps.

After verifying the [commit range](https://github.com/mozilla-mobile/fenix/compare/1a2be2065ada64003b508ad1e51c5ee02639b27c...bbf2d427d2f7191d245c8dcc295699fc7512a0d5) found in builds from TC between Nightly [6/8](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.2022.06.08.latest/armeabi-v7a)(1875ms) to Nightly [6/9](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.2022.06.09.latest/armeabi-v7a) (1941ms)

### We have in Fenix ([commit range](https://github.com/mozilla-mobile/fenix/compare/1a2be2065ada64003b508ad1e51c5ee02639b27c...bbf2d427d2f7191d245c8dcc295699fc7512a0d5) about page taken from TC nightly builds):
![image](https://user-images.githubusercontent.com/773158/175328027-f15ce5f0-2429-4371-8a20-56496fe86b3f.png)

### In Focus we have [this range of commits](https://github.com/mozilla-mobile/focus-android/compare/2a0cce63f6887933cc50e9f214108b80730782de...4577229f1b857f6ae1c94ff417f8328dfd1045f1) between 6/9 Nightly (605ms) to the 6/10 Nightly (674ms):

![image](https://user-images.githubusercontent.com/773158/175328444-9a406299-6c64-4daf-ad53-ab4d81d66561.png)


## The commits that are common in both are:

### The AC `103.0.20220609181205`  breaking change that brought up the Glean API update with it. 

**[Fenix](https://github.com/mozilla-mobile/fenix/pull/25434)**

 ![image](https://user-images.githubusercontent.com/773158/175332478-443ff041-d3dc-4558-8503-9fe72f3430ce.png)

 **[Focus](https://github.com/mozilla-mobile/focus-android/pull/7135)**
![image](https://user-images.githubusercontent.com/773158/175331917-e0df1ca1-7f2b-40ee-a203-173459828c14.png)

### The media session bug fix.

[Fenix](https://github.com/mozilla-mobile/fenix/pull/25565)
![image](https://user-images.githubusercontent.com/773158/175345852-0b6fac79-bc57-4ef0-a9aa-662c7c6e7974.png)

[Focus](https://github.com/mozilla-mobile/focus-android/pull/7197)
![image](https://user-images.githubusercontent.com/773158/175345032-525fc070-0e2d-4645-9788-b7f73e1e3669.png)


### On that day (06/09) on AC we only landed the same two changes:

![image](https://user-images.githubusercontent.com/773158/175334828-c4ad124a-b54c-4645-862d-300e4d6c50ce.png)

- [The glean update ](https://github.com/mozilla-mobile/android-components/pull/12248)
- [Media session bug fix](https://github.com/mozilla-mobile/android-components/commit/c3b680a158bcd66c355c3e409c1de89e7f8e97e9).

## To verify which commit introduced the regression:

I run `python3 measure_start_up.py -c=25 nightly cold_main_first_frame file.txt`  **on my Moto G**  for  [1f89e1177305e52182410a062e2ce078cc519fe4](https://github.com/mozilla-mobile/fenix/commit/1f89e1177305e52182410a062e2ce078cc519fe4) **which contains the media session bug fix**.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/773158/175339865-969c3d27-187e-40f9-90a1-3b823dc5bb09.png">


Raw data

```
{'max': 2411.0,
 'mean': 1624.24,
 'median': 1278.0,
 'min': 1236.0,
 'replicate_count': 25,
 'replicates': [2354.0, 1268.0, 1286.0, 1257.0, 1300.0, 1262.0, 1254.0, 1278.0,
                2411.0, 2346.0, 1273.0, 1286.0, 1270.0, 1258.0, 1258.0, 1277.0,
                1240.0, 2380.0, 2364.0, 2395.0, 2370.0, 1332.0, 1261.0, 1236.0,
                2390.0]}
```
```
2354
1268
1286
1257
1300
1262
1254
1278
2411
2346
1273
1286
1270
1258
1258
1277
1240
2380
2364
2395
2370
1332
1261
1236
2390
```

And 

I run `python3 measure_start_up.py -c=25 nightly cold_main_first_frame file.txt`  **on my Moto G** for [13c34f16dd74e37b997189701b0f816916d846e5](https://github.com/mozilla-mobile/fenix/commit/13c34f16dd74e37b997189701b0f816916d846e5) **which contains: The AC `103.0.20220609181205`  breaking change that brought up the Glean API update with it.** 


<img width="629" alt="image" src="https://user-images.githubusercontent.com/773158/175338918-812176b7-4e30-49a3-b74a-c1d8b7005022.png">

Raw data 
```

{'max': 1478.0,
 'mean': 1333.92,
 'median': 1328.0,
 'min': 1246.0,
 'replicate_count': 25,
 'replicates': [1309.0, 1339.0, 1336.0, 1322.0, 1356.0, 1390.0, 1338.0, 1342.0,
                1318.0, 1315.0, 1322.0, 1312.0, 1328.0, 1328.0, 1297.0, 1354.0,
                1374.0, 1478.0, 1306.0, 1351.0, 1308.0, 1329.0, 1246.0, 1319.0,
                1331.0]}
```

```
1309
1339
1336
1322
1356
1390
1338
1342
1318
1315
1322
1312
1328
1328
1297
1354
1374
1478
1306
1351
1308
1329
1246
1319
1331
```

If we take the median value from with the glean update vs without the it **1328.0 - 1278.0 = 50**

**Comment by mcomella** [comment] 2022-06-23 18:00
> @mcomella please would you mind giving me a hand by double checking.

Just reading what you wrote (but not reproducing it myself), your analysis seems valid.

**Comment by Amejia481** [comment] 2022-06-23 18:03
cc @badboy, to make you aware of the ticket.

**Comment by badboy** [comment] 2022-06-24 12:46
Thanks for the notification. 
Are there ways I can run the startup measurement myself locally?
I think I know a way to reliably delay Glean init, so that we don't pay the cost that early, causing the delay in getting to the first frame.

(Note: I'm out for 2 weeks, I'll hand this over to my team, but can't guarantee that we'll be able to tackle it until I'm back)

**Comment by Amejia481** [comment] 2022-06-24 19:43
Just to make you aware this is not something urgent :) 

>  Are there ways I can run the startup measurement myself locally?

Yes you could run the test locally, you just need to download the [perf-tools repo](https://github.com/mozilla-mobile/perf-tools), you can find extra steps on how to run the test [here](https://wiki.mozilla.org/Performance/Fenix/Performance_reviews#Measuring_cold_start_up_duration). When you have the result file in case you would like have the see the graph you could run `python3 analyze_durations.py --graph resuts.txt`. Just keep in mind the results above are from running the tests on a Moto G 5, running on more powerful devices, you could get different results.

**Comment by mcomella** [comment] 2022-07-06 21:58
We noticed a page load performance regression and increased noise on desktop from a change that landed on 6/8, which happens to be the same day as this regression: https://bugzilla.mozilla.org/show_bug.cgi?id=1774420#c16 Relatedly, the fenix start up dashboard appears to be more noisier on both MAIN and VIEW after 6/8. Perhaps it's all related?

**Comment by Amejia481** [comment] 2022-07-19 14:13
Thanks for the update, I'll try to run the tests and post back the results during the day!

**Comment by mcomella** [comment] 2022-07-19 20:47
> I think the Moto G5 is an arm64-v8a device, right?

@badboy I think you'll need to post an armv7 build. iirc, the Moto G5 hardware is 64-bit capabable but it only runs a 32-bit OS.

**Comment by badboy** [comment] 2022-07-20 08:12
> > I think the Moto G5 is an arm64-v8a device, right?
> 
> @badboy I think you'll need to post an armv7 build. iirc, the Moto G5 hardware is 64-bit capabable but it only runs a 32-bit OS.

damn, I'll provide the other builds in a bit.

**Comment by badboy** [comment] 2022-07-20 08:35
Here we go again, armv7 builds:

* Fenix unchanged: https://p.fnordig.de/fenix-96472c9-glean-unchanged-2022-07-21.zip
* Fenix with changed Glean: https://p.fnordig.de/fenix-96472c9-glean-ecb3d6a-2022-07-20.zip

**Comment by badboy** [comment] 2022-07-21 08:21
@Amejia481 any chance you can run those today? If this turns out to mitigate the regression we can get out a release and get it into Fenix next week.

**Comment by Amejia481** [comment] 2022-07-21 13:10
Sorry, my bad I will do it, right away!

**Comment by Amejia481** [comment] 2022-07-21 14:17
### Fenix unchanged

<img width="624" alt="image" src="https://user-images.githubusercontent.com/773158/180236123-e832159f-ace6-4201-b384-1b0d75420324.png">

==> fenix_unchanged.txt <==
{'max': 1618.0,
 'mean': 1299.32,
 'median': 1289.0,
 'min': 1231.0,
 'replicate_count': 25,
 'replicates': [1264.0, 1289.0, 1310.0, 1275.0, 1303.0, 1302.0, 1265.0, 1265.0,
                1231.0, 1298.0, 1282.0, 1248.0, 1618.0, 1272.0, 1270.0, 1297.0,
                1306.0, 1312.0, 1296.0, 1345.0, 1321.0, 1308.0, 1263.0, 1274.0,
                1269.0]}
### Fenix with changed Glean

<img width="635" alt="image" src="https://user-images.githubusercontent.com/773158/180234236-88b0f96d-3cef-4003-b385-f60d17d51f74.png">

==> fenix_with_changed_Glean.txt <==
{'max': 1493.0,
 'mean': 1293.88,
 'median': 1290.0,
 'min': 1229.0,
 'replicate_count': 25,
 'replicates': [1304.0, 1288.0, 1260.0, 1302.0, 1229.0, 1249.0, 1271.0, 1295.0,
                1290.0, 1267.0, 1289.0, 1307.0, 1276.0, 1290.0, 1277.0, 1261.0,
                1298.0, 1493.0, 1336.0, 1294.0, 1337.0, 1290.0, 1327.0, 1243.0,
                1274.0]}

**Comment by Amejia481** [comment] 2022-07-21 14:27
Results seems really similar

**Comment by badboy** [comment] 2022-07-21 14:28
So lower max with the changes but effectively unchanged median.
At the very least this is not making things worse so I am still considering rolling that out, but not yet marking this as resolved.

**Comment by Amejia481** [comment] 2022-07-21 14:36
> At the very least this is not making things worse, so I am still considering rolling that out
That's a good 👍🏽

**Comment by Amejia481** [comment] 2022-08-08 14:56
@badboy based on the results on https://github.com/mozilla-mobile/fenix/pull/26165#issuecomment-1200441663 I think we could close this ticket, could we do the same treatment on Focus for https://github.com/mozilla-mobile/focus-android/issues/7216?

**Closed by Amejia481** 2022-08-08 14:56 UTC
Labels: performance, needs:triage

**Comment by badboy** [comment] 2022-08-08 15:05
> @badboy based on the results on [#26165 (comment)](https://github.com/mozilla-mobile/fenix/pull/26165#issuecomment-1200441663) I think we could close this ticket, could we do the same treatment on Focus for [mozilla-mobile/focus-android#7216](https://github.com/mozilla-mobile/focus-android/issues/7216)?

I'll send a PR

**Comment by Amejia481** [comment] 2022-08-08 19:31
Thanks!
