### ISSUE TITLE
[Bug]: "My Account" page can be scrolled causing a visual defect on Nightly GV 96.0a1

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#22457] opened 2021-11-16 12:52 UTC
### Steps to reproduce

1. Launch Firefox Nightly GV 96.0a1.
2. Go to youtube.com and sign in with valid credentials.
3. Tap on the account's icon in the right upper corner.
4. In Portrait mode, scroll on the "Account" page.
5. Observe the visual defect present on the top and the bottom of the page.

### Expected behaviour

The page cannot be scrolled on Portrait mode and no visual defect is present.

### Actual behaviour

The page can be scrolled on Portrait mode to dismiss the toolbar, and a flicker can be observed on the top and the bottom of the page.
Please note that after rotating the device in Landscape mode, and rotating again in Portrait mode, the page can no longer be scrolled. 

### Device name

Samsung Galaxy Note10 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

GV 96.0a1 (Build 2015845995) 

### Additional information

The issue could not be reproduced on other devices, and is not encountered on Firefox Beta or Chrome.

https://user-images.githubusercontent.com/89388888/141987876-4904e8bc-0c71-4dcf-a189-3a79f6f659b0.mp4

**Comment by Mugurell** [comment] 2021-11-16 14:54
Something is definitely strange there as it also allows for pull to refresh.
@delia-pop  Seeing that it is only reproducible on one device I think the app may have gotten in a strange state which could be investigated on it's own but probably after being restarted the app will behave as expected?

**Comment by Mugurell** [comment] 2021-11-16 15:06
When the toolbar is translated we can also see the videos list behind these settings so it may be that something got stuck and the gestures actually interact with the behind screen. Would be interesting to know what would've happen if tapping a setting from this screen.

**Comment by delia-pop** [comment] 2021-11-16 15:12
Noted, I will further investigate this behavior, and provide more details.

**Comment by Mugurell** [comment] 2021-11-17 07:07
Moving this to Bugzilla since it seems like a browser issue and can be reproduced on GVE also.

**Comment by Mugurell** [comment] 2021-11-17 07:07
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1741555

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by Mugurell** 2021-11-17 07:07 UTC
Labels: 🐞 bug, needs:triage

**Comment by delia-pop** [comment] 2021-12-10 15:55
Upon further testing the following were observed:

- On Samsung Galaxy Note10 (Android 11), the issue can no longer be reproduced with the latest Nightly build from 12/10, but it can be reproduced with GVE - only in Portrait mode. The Pull Refresh was not allowed.  

https://user-images.githubusercontent.com/89388888/145601137-b63de095-3c22-48de-9671-07efd160bbb9.mp4

- On LG G7 fit (Android 8.1.0), the visual glitch was reproduced on the latest Nightly build from 12/10 only in Landscape mode.
The issue is also present on GVE, on Portrait mode with 100% repro. 

https://user-images.githubusercontent.com/89388888/145602628-20559814-ad4f-4887-a0da-b1fc43f0cf0a.mp4


- On LG G7 fit (Android 8.1.0), on Landscape mode, the visual glitch does not occur when scrolling, however on one occasion the "My Account" allowed the page in the background to be displayed on the top side of the screen. This could not be reproduced again.

https://user-images.githubusercontent.com/89388888/145602651-25a57986-bff8-4fb9-8ebb-a7db2734effd.mp4
