### ISSUE TITLE
Irrelevant fullscreen mode[Bug]: 

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#23764] opened 2022-02-15 20:45 UTC
### Steps to reproduce

Rewind the video back and forth by visiting the website below.

https://www.trt1.com.tr/diziler/seksenler/bolum/71-bolum

### Expected behaviour

The video should work in normal mode.

### Actual behaviour

Firefox enters full screen mode during video playback and does not recover.

This behavior is repeated on many video platforms like Twitter.
![Screenshot_20220215-233743_Mull](https://user-images.githubusercontent.com/60405617/154146104-e11a03eb-ded9-4e02-b3de-70854e95f426.png)

### Device name

Mi 9T 

### Android version

Android 10 

### Firefox release type

Firefox

### Firefox version

97.1.1

**Comment by reyis4402** [comment] 2022-02-15 20:48
Reddit post on the subject

https://www.reddit.com/r/firefox/comments/stcbtb/this_new_annoying_android_full_screen_made_me/

**Comment by jxu** [comment] 2022-02-15 22:27
I have same issue with YouTube. 97.1.0 (Build #2015860771) on Android 12, Pixel 4a

**Comment by jxu** [comment] 2022-02-15 23:18
Probably duplicate of #23705, #23119

**Comment by kbrosnan** [comment] 2022-02-16 00:56
Closing as duplicates

**Closed by kbrosnan** 2022-02-16 00:56 UTC
Labels: 🐞 bug, needs:triage
