### ISSUE TITLE
[Bug] Gmaps stuck if you try navigation inside the browser

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4322] opened 2019-07-26 08:58 UTC
## Steps to reproduce
1. Go to google.com/maps
2. Set a destination and tap Navigate.
### Expected behavior
Navigation works in the browser / open automatically the Maps app.
### Actual behavior
The progress bar is stuck in a reloading state. Nothing happens.
### Device information

* Android device: Pixel 3 (Android 9), Nexus 5(Android 6.0.1)
* Fenix version: Nightly 190726 #12070609, RC 1.1.0-rc2

**Comment by sblatz** [comment] 2019-07-30 16:00
This is the behavior:
![google maps bug](https://user-images.githubusercontent.com/4400286/62145399-41d15b00-b2a8-11e9-8540-df32e20c664f.gif)

I'm able to reproduce in Reference Browser--seems like a GV bug. I have [filed]()

Please note: if I let google maps continually do this reloading Fenix eventually crashes, but I'm not getting a real crash log :

```
2019-07-30 09:02:03.877 2089-2422/org.mozilla.fenix.debug D/sql_support::conn_ext: Transaction commited after 42.44625ms
2019-07-30 09:02:03.965 2089-2089/org.mozilla.fenix.debug I/SessionStorage/AutoSave: Save: Load finished
2019-07-30 09:02:03.965 2089-2089/org.mozilla.fenix.debug D/SessionStorage/AutoSave: Skipping save, other job already in flight
2019-07-30 09:02:03.967 2089-2422/org.mozilla.fenix.debug D/places_ffi: bookmarks_get_all_with_url
2019-07-30 09:02:03.982 2089-2208/org.mozilla.fenix.debug D/places_ffi: places_note_observation
2019-07-30 09:02:04.023 2089-2208/org.mozilla.fenix.debug D/sql_support::conn_ext: Transaction commited after 40.390937ms
2019-07-30 09:02:04.115 2089-2089/org.mozilla.fenix.debug I/SessionStorage/AutoSave: Save: Load finished
2019-07-30 09:02:04.115 2089-2089/org.mozilla.fenix.debug D/SessionStorage/AutoSave: Skipping save, other job already in flight
2019-07-30 09:02:04.118 2089-2195/org.mozilla.fenix.debug D/places_ffi: places_note_observation
2019-07-30 09:02:04.124 2089-2208/org.mozilla.fenix.debug D/places_ffi: bookmarks_get_all_with_url
2019-07-30 09:02:04.180 2089-2195/org.mozilla.fenix.debug D/sql_support::conn_ext: Transaction commited after 61.755156ms
2019-07-30 09:02:04.265 2089-2089/org.mozilla.fenix.debug I/SessionStorage/AutoSave: Save: Load finished
2019-07-30 09:02:04.265 2089-2089/org.mozilla.fenix.debug D/SessionStorage/AutoSave: Skipping save, other job already in flight
2019-07-30 09:02:04.267 2089-2207/org.mozilla.fenix.debug D/places_ffi: bookmarks_get_all_with_url
2019-07-30 09:02:04.280 2089-2171/org.mozilla.fenix.debug D/places_ffi: places_note_observation
2019-07-30 09:02:04.300 2089-2089/org.mozilla.fenix.debug I/Gecko: [GFX1]: Failed to create DrawTarget, Type: 3 Size: Size(1080,1803)
2019-07-30 09:02:04.301 2089-2089/org.mozilla.fenix.debug W/lla.fenix.debu: 0xebadde09 skipped times: 0
2019-07-30 09:02:04.312 2089-2171/org.mozilla.fenix.debug D/sql_support::conn_ext: Transaction commited after 31.744791ms
2019-07-30 09:02:04.383 2089-2089/org.mozilla.fenix.debug W/google-breakpad: ExceptionHandler::GenerateDump cloned child 
2019-07-30 09:02:04.383 2089-2089/org.mozilla.fenix.debug W/google-breakpad: 2748�f��g��S8�$�����
2019-07-30 09:02:04.383 2089-2089/org.mozilla.fenix.debug W/google-breakpad: ExceptionHandler::SendContinueSignalToChild sent continue signal to child
```

**Comment by sblatz** [comment] 2019-07-30 19:54
Note: this is still happening on GV 69

**Comment by snorp** [comment] 2019-08-01 16:05
This is an intent URI thing. It's trying to load `intent://navlite.app.goo.gl/...`. This should be handled by Fenix/a-c.

**Comment by cpeterso** [comment] 2019-08-01 19:52
Removing `needs:gv` label because intent URIs should be handled by Fenix or A-C, not GV.

**Comment by cpeterso** [comment] 2019-10-31 18:13
I closed the GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1581966

This is a Fenix bug. Fenix needs to add support for intent URIs, or at least recognize them so we don't get stuck in an infinite loop. That is Fenix issue #5664.

**Comment by kbrosnan** [comment] 2019-10-31 23:00
Closing this issue as a dupe of the more general #5664

**Closed by kbrosnan** 2019-10-31 23:00 UTC
Labels: P2, S2, b:crash, b:web-content, 🐞 bug
