### ISSUE TITLE
[Bug]: Autofill not working with Bitwarden

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#20987] opened 2021-08-24 12:40 UTC
### Steps to reproduce

1. Go to any website with a login field.
2. Tap on the username or password.

### Expected behavior
The autofill pop-up from Bitwarden should be displayed.

### Actual behavior
Autofill not working with Bitwarden

### Device name
Google Pixel 4 XL

### Android version
Android 10

### Firefox release type
Firefox Nightly

### Firefox version
93.0a1

### Additional information

Please note that this worked before, today I wasn't able to make the autofill pop-up appear.

**Comment by hakkikaancaliskan** [comment] 2021-08-24 16:03
Workaround for this:
1- tap to password area
2- press to three dot to open Firefox menu
3- press outside of menu to close it

Then it'll show the autofill.

**Comment by jonalmeida** [comment] 2021-08-24 19:17
Duplicate of https://github.com/mozilla-mobile/fenix/issues/16583

Already filed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1693152

**Closed by jonalmeida** 2021-08-24 19:17 UTC
Labels: 🐞 bug, S1, Feature:Autofill
