### ISSUE TITLE
[Bug] The favicons from the recent history pop-up flicker while the page is loading

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#12973] opened 2020-07-27 12:27 UTC
## Steps to reproduce
1. Load mail.yahoo.com, news.google.com, gmail.com and espn.com;
1. Long tap on the Device Back Button;
1. Select a different link from the list (e.g news.google.com);
1. Long tap on the Device Back Button;
1. Observe the favicons;
    1. Expected behavior
The favicons from the recent history pop-up are displayed without flicker while the page is loading.
    1. Actual behavior
The favicons from the recent history pop-up flicker while the page is loading.
    1. Notes
![20200727](https://user-images.githubusercontent.com/48799384/88540999-b7d3e380-d01c-11ea-8496-286fa0bee283.gif)UNITO-UNDERSCORE!151809!

### Device information
* Android device: Motorola Moto G6 (Android 8), Google Pixel 2 (Android 9), Huawei P9 Lite (Android 7), Nexus 5 (Android 6.0.1)
* Fenix version: Nightly 200727 Build #22090608 GV 80.0a1 from 7/27

**Comment by s-ankur** [comment] 2020-07-27 17:34
Duplicate of #12887

**Comment by eliserichards** [comment] 2020-07-27 22:10
Closing as a duplicate :)

**Closed** 2020-08-28 23:04 UTC
Labels: Feature:Browsing, S2, needs:triage, 🐞 bug
