### ISSUE TITLE
[Bug] Search value gets stored invisibly.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#13244] opened 2020-08-04 07:24 UTC
## Steps to reproduce
1. Open a website
2. Search some text (for example "the")
3. Close the search-box
4. Reopen the search (the textbox will be empty)
5. WITHOUT typing anything, just press down/up to find the next/previous instance of the text.
6. You'll jump to the next/previous "the". The text-field will stay empty though.

### Expected behavior
Either remember the search-query and don't make it invisible OR don't store it and erase it completely.

### Actual behavior
It gets invisibly stored.
### Device information

* Android device: Samsung Galaxy S9
* Fenix version: 200803

**Comment by s-ankur** [comment] 2020-08-04 08:39
duplicate of #9713

**Closed** 2020-08-08 00:33 UTC
Labels: needs:triage, 🐞 bug
