### ISSUE TITLE
[Bug] Cannot autofill passwords using Enpass

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10640] opened 2020-05-14 00:14 UTC
## Steps to reproduce
This is related to #9773, Enpass is marked as working but I don't see it working properly on my device. 

1. Enable Enpass autofill service.
1. Go to: https://mobile.twitter.com/login
1. Autofill pop-up randomly appears and disappears.
4.This can also be reproduced on:
https://myanimelist.net/login.php?from=%2F
1. This is the same behaviour almost everywhere the login form appears.

### Expected behavior
Autofill should work properly

### Actual behavior
Autofill doesn't work properly

### Device information
* Android device: Motorola One Power, Android 10.
* Fenix version: 76.0.0-beta.1 (Build - #2015737667) and Nightly 200511 06:21 (Build #2015739635)
![20200514](https://user-images.githubusercontent.com/42088907/81878990-fc50f680-9578-11ea-9e2c-b1bf3ac491aa.gif)UNITO-UNDERSCORE!054802!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-826)

**Comment by abodea** [comment] 2020-05-15 09:32
Hi, @SS1113 note that I was able to autofill using Enpass, I had 0 issues regarding this app.

![20200515-114920](https://user-images.githubusercontent.com/42831109/82035404-248b4300-96a8-11ea-973a-0fbd1c8cc7ea.gif)

**Comment by SS1113** [comment] 2020-05-15 09:42
@abodea It is not working on my device properly, the autofill prompt appears and disappears quickly when I click the input fields and if I keep doing it then after 10 seconds or so it works as expected. Is there a reason why this is happening on my device?

**Comment by abodea** [comment] 2020-05-15 10:02
Thank you for the response!
I will add this issue to https://github.com/mozilla-mobile/fenix/issues/9773 description as being a device-related issue.

**Comment by SS1113** [comment] 2020-05-15 11:11
@abodea I have tested it on some more devices: Xiaomi Mi A2 (Android 10),
Realme C3 (Android 10).

These devices are also exhibiting the same issue.

Tested on Fenix: 76.0.0-beta.2 (Build #2015740131)

**Comment by SS1113** [comment] 2020-06-11 06:58
The issue can still be reproduced on `Nightly 200611 06:01`.

**Comment by SS1113** [comment] 2020-06-29 06:13
This can still be reproduced on `Nightly 200628 06:01`.

**Comment by hakkikaancaliskan** [comment] 2020-07-05 18:42
What's your Fenix language? Because mine is Turkish and it's not working on it but working on English.

**Comment by SS1113** [comment] 2020-07-06 00:06
I have set the Fenix language to English (United States) and it is the default language of my phone too. So I set the language to Follow device language in Fenix.

**Comment by ShatteredPixel** [comment] 2020-07-16 02:23
I am the reporter of this issue, the above deleted account is mine. Please let me know if I can provide you any more information.

**Comment by ShatteredPixel** [comment] 2020-07-16 02:35
I am the reporter of this issue, the above deleted account was mine. Please let me know if I can provide you any more information.

**Comment by danialasghar** [comment] 2020-09-28 13:21
Can reproduce this issue on my device as well:
LG Velvet, Android 10 July security patch, Latest Beta playstore v82.

A solution to the disappearing enpass prompt I have found is click the URL bar and then click the password or user field ... the prompt to autofill will stay without doing the disappearing thing.

**Comment by danialasghar** [comment] 2020-10-24 22:53
An update to this... In the latest nightly the issue of the autofill ui seems to be fixed. 

Although web domain passing does not seem to work with enpass... it always says "login not found" and you have to manually search your enpass logins to fill them out

**Comment by Neon329** [comment] 2020-12-22 11:00
@abodea @vesta0 I have contacted Enpass about this issue in Firefox which I'm also facing and the developer response is that, quoting from the support comment:

>We have found that the flicking of auto-fill pop up is caused by Firefox & Autofill framework miss-communication bug. There is little we can do but to wait for a fix from Firefox.

I hope Firefox fixes this issue.

**Comment by Neon329** [comment] 2020-12-26 11:36
Enpass has confirmed that it's a Firefox bug. They said it's happening because of miscommunication between Firefox and Enpass.

**Comment by Djfe** [comment] 2021-01-10 01:15
my experience: it's still happening, but it's better by now.
(either because of a Firefox update or because I updated my rom)

I only have issues with Firefox and the enpass autofill.
Chrome works perfectly fine

I'm on Android 10 (havoc os, custom rom) and Fenix Release (84.1.4), keyboard: Microsoft Swiftkey

what works better now:
you open a login page and it often/mostly already shows the enpass autofill. click on it and you can login.

if you miss click or click somewhere else on the website, then it's gone. if you focus then input manually by clicking it, then it's blinking.
switch between username and password input: sometimes you don't see the autofill at all, sometimes it blinks a couple of times and then it's gone. switch between user and password field often enough and the blinking gets slower until it eventually opens and doesn't blink away. If you touch it, then you can autofill. miss click and it's blinking again.

comparison to other apps like Spotify or Chrome: rocksolid
there you can switch input fields and it never blinkse and always shows up and stays until you close it (touch somewhere else on the screen or press (hw/sw) back button)

**Comment by Djfe** [comment] 2021-01-10 02:18
I deleted my last comment due to mistakes on my side.
I'm on a OnePlus 3T Android 10 (Havoc OS, Custom Rom)
I'm using Firefox Release 84.1.4 where it's still happening.

The issue is fixed in the current nightly 86 and beta 85 (I'm very much looking forward to that)

Since you reported that it was fixed in Oktober it should have been fixed with version 84. Seems to me like this fix was delayed to Firefox 85. Soon it will be gone :)

The only thing in beta/nightly that is still annoying me:
clicking on an input makes Firefox scroll the page but it tells the autofill the old position of an input so the autofill often gets drawn at wrong positions (not directly below an input but on top of inputs or way below them)
https://youtu.be/9jBdf1hKnj8

**Comment by Neon329** [comment] 2021-01-14 11:10
@Djfe I have confirmed with **Enpass** that the autofill dialogue flickering issue is from **Firefox**'s end and not from Enpass itself. I can reproduce the bug even with latest beta `85.0.0-beta.7`.

Quoting directly from the support ticket I raised with Enpass: 

***"The autofill dialogue flickering issue is happening due to miscommunication between Firefox and Enpass."***

 Enpass said they can't do anything until Firefox fixes this issue. 

Other pasword managers seem to be also having the same issue as you can see with some of the other bugs.

The exact same issue can also be reproduced with **Bitwarden** as well.

**Comment by Djfe** [comment] 2021-01-15 14:47
I don't know where @Neon329 's post went to, but he is right. the issue is still present in beta 👍
I might've downloaded beta but accidentally tested nightly instead.
The issue is present in beta versions 4, 5, 6, 7 and 8

Is there a way to uplift the fix from nightly 86 to beta 85, still?

**Comment by Neon329** [comment] 2021-01-15 15:10
@Djfe Yeah, sorry about that. But since most pasword managers are not working with Fenix I thought I'd be a waste to leave a comment without any logs or anything. And I also saw with some other bugs that QA has tested it and it is working on their end but so many users are able to reproduce the bug. But they have marked it as "working". It's the same with Bitwarden as well. Enpass support told me that it's a bug with Firefox and not Enpass too. So I thought It wasn't going to be fixed, I deleted the comment. So many months have passed now since filing this bug but nobody from development is looking into it. 

I have switch my browser, the browser has so many issues and I cannot use it as my daily driver.

**Comment by Djfe** [comment] 2021-02-04 01:27
now this is unexpected 😯
The issue is present in Firefox Beta 86 (beta2) while it was fixed in Nightly 86.
Why is there flickering in the Beta but not in Nightly?
Different compiler flags/configs?
Or was there a fix and it was postponed and removed from 86?

**Comment by loxK** [comment] 2021-02-25 10:56
Same issue on OnePlus 6T, Firefox. All to the latest version. Even the Enpass keyboard sometimes doesn't fill after choosing an item.

**Comment by Djfe** [comment] 2021-08-24 13:24
still happening

**Comment by Djfe** [comment] 2022-02-20 16:48
not fixed, yet

**Comment by plwt** [comment] 2022-03-13 17:27
User feedback: https://support.mozilla.org/en-US/questions/1370765

**Comment by loxK** [comment] 2022-03-16 01:40
Here is the related GitHub issue: https://github.com/mozilla-mobile/fenix/issues/10640

**Comment by delia-pop** [comment] 2022-05-19 15:09
Hi @plwt , I was not able to reproduce this issue on the latest Nightly from 05/19 or GVE with Google Pixel 6 (Android 12). 
On both apps, with Enpass set as default autofill app and a login for Facebook saved, the autofill works as expected.

The current flow is as follows:
1. Tap on the username/password fields.
2. Tap on the "Autofill" enpass option above the keyboard.
3. Enter the Masters Password and select the desired saved login.
4. The data is correctly imported.

![Screenshot (May 19, 2022 6 04 57 PM)](https://user-images.githubusercontent.com/89388888/169329330-b6357efc-583c-492d-acae-f40987d2fded.png)

**Comment by Djfe** [comment] 2022-05-19 17:12
as I said in the KeePass issue:
please retest in Release. Nightly never had this bug. But the flickering has been a bug in Release for years now.

Also: the button you see on your keyboard seems to be a new feature of Android 12. Most devices are still on Android 11 and lower without keyboard integration.

**Closed** 2022-12-09 05:48 UTC
Labels: 🐞 bug, S2, Feature:Logins, wontfix, qa-triaged
