### ISSUE TITLE
FNX-4748 ⁃ [Bug] Downloads Not Starting When They Should Be

### ISSUE THREAD

**Issue by kglazko** [mozilla-mobile/fenix#10429] opened 2020-05-06 00:14 UTC
## Steps to reproduce
See: https://appbot.co/apps/2101759-firefox-preview/reviews/1628725862
"Sometimes they don't even start"

This is not consistently reproducible on a Pixel 4.

### Device information
* Android device: ?
* Fenix version: ?

**Comment by kglazko** [comment] 2020-05-06 00:17
We need to see if this issue is consistently reproducible. One time, I wasn't able to trigger the download of a ZIP file after downloading it several times, but I could not eliminate whether it was a network issue or not.

**Comment by kbrosnan** [comment] 2020-05-06 00:28
This sounds like a dupe of https://github.com/mozilla-mobile/android-components/issues/1159 / https://bugzilla.mozilla.org/show_bug.cgi?id=1501735 

Every downloads not starting issue I have seen has been the blob: problem. Without a URL to work with this is unlikely to discover new information.

**Closed** 2020-08-11 00:43 UTC
Labels: Feature:Download, needs:triage, 🐞 bug
