### ISSUE TITLE
[Bug]: getting blank card in home screen in jump back in section 

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#26142] opened 2022-07-22 05:51 UTC
### Steps to reproduce

Open any link
Click home button
The homescreen shows a blank card under jump back in section 

### Expected behaviour

Should not show any blank card

### Actual behaviour

Showing blank card

### Device name

rog 3

### Android version

android 12

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Device logs

![Screenshot_20220722-111752909 (1)](https://user-images.githubusercontent.com/58127841/180372080-6477085a-e0e9-48c2-b855-9f09518daf6e.jpg)

### Additional information

I have disabled open tabs syncing

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21088)

**Comment by LaurentiuApahideanSV** [comment] 2022-07-22 10:20
I can confirm the issue is reproducible on Firefox Nightly 104.0a1 2022-07-22.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)

**Comment by jonalmeida** [comment] 2023-01-17 15:58
Requesting for this to be re-tested. I believe it's fixed now.

**Comment by SoftVision-LorandJanos** [comment] 2023-01-19 14:46
This issue is not reproducible on the latest Nightly 111.0a1 (2023-01-19) and Beta 110.0b2 builds.
Devices used: Oppo Find X5 (Android 12) and Google Pixel 6 (Android 13).
Closing the ticket as verified.

**Closed by SoftVision-LorandJanos** 2023-01-19 14:46 UTC
Labels: 🐞 bug, eng:qa:needed, needs:triage, Feature:SyncTabs, qa-triaged
