### ISSUE TITLE
FNX-5155 ⁃ Should not have to check custom tab session before setting title

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#1639] opened 2019-04-15 17:56 UTC
Custom Tabs integration requires a check of the session in order for it to not collide with a regular session. This is a temporary work-around but needs to be investigated to fix the underlying issue.

### Device information
* Android device: ?
* Fenix version: ?

**Comment by jonalmeida** [comment] 2019-04-16 19:06
@ekager what a fix put to refactor the changes in #668?

I can see the temporary fix still in that doesn't fix this issue: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt#L277

**Comment by ekager** [comment] 2019-04-16 19:39
Sorry, based on the title of this issue, I thought this was a dupe of #1637 and closed it. Feel free to reopen if it requires a code change on our end.

**Comment by jonalmeida** [comment] 2019-04-16 19:50
Sorry, I should have placed a link to the PR as well for more context that it didn't solve the underlying issue. Cheers!

**Comment by ekager** [comment] 2019-07-12 20:59
@jonalmeida do you still want this to be investigated or can we close this issue?

**Comment by jonalmeida** [comment] 2019-07-12 21:21
This is done! But I may have linked the work to a different ticket. Closing.

**Closed** 2020-08-11 12:20 UTC
Labels: Feature:CustomTabs, eng:health, 🐞 bug
