### ISSUE TITLE
[Bug] crash when switching tabs

### ISSUE THREAD

**Issue by chartmix** [mozilla-mobile/fenix#19991] opened 2021-06-13 18:18 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Everyday usage of switching tabs

### Expected behavior
No crashes when switching tabs

### Actual behavior
Brower crashes on a daily basis when switching tabs. Happens with all betas. 
https://crash-stats.mozilla.org/report/index/76919bf9-24cc-4cc8-b521-6b1340210604
https://crash-stats.mozilla.org/report/index/22dd5c3c-b1f8-4abb-9319-c21900210512
https://crash-stats.mozilla.org/report/index/2f12da6d-acf8-4afc-a060-3e4820210503

### Device information

* Device vendor / model and Android version: Huawei P9 Android 7.0
* Firefox for Android version: 90.0.0 beta 3 (go to Settings -> About Firefox)

**Comment by LaurentiuApahideanSV** [comment] 2021-06-14 11:57
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/17600. I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-06-14 11:57 UTC
Labels: needs:triage, 🐞 bug
