### ISSUE TITLE
[Bug] Exiting Fenix custom tabs after switching apps exits the app

### ISSUE THREAD

**Issue by Manishearth** [mozilla-mobile/fenix#8557] opened 2020-02-19 22:15 UTC
## Steps to reproduce

Requires that the browser is the default. This seems related to https://github.com/mozilla-mobile/fenix/issues/8553 , however I cannot reproduce https://github.com/mozilla-mobile/fenix/issues/8553 on Nightly so I'm assuming it's fixed.

 - Open Twitter or some other app (etc)
 - Open an external link in Twitter into a custom tab
 - Switch to a different app
 - Reopen twitter from the home screen
 - Close the custom tab (pressing back or "x")

### Expected behavior

Twitter goes back to showing whatever it was showing before the external link was clicked (as it does when you do this without switching apps in between)

### Actual behavior

Twitter exits, you have to reopen it.

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 200219 18:01 (Build #20501809) 34.0.0, ea4c0d310, Wednesday 2/19 @ 6:08 PM

**Comment by softvision-miralobontiu** [comment] 2020-11-18 14:00
I was not able to reproduce this issue on the 11/18 Firefox Nightly build with Samsung Galaxy Tab S6 (Android 10).
I'll close this issue.
Please feel free to file a new issue if this behavior reoccurs.

**Closed by softvision-miralobontiu** 2020-11-18 14:00 UTC
Labels: Feature:CustomTabs, needs:triage, 🐞 bug
