### ISSUE TITLE
Enable the about:config page on the stable release

### ISSUE THREAD

**Issue by PolicyPuma4** [mozilla-mobile/fenix#19721] opened 2021-05-30 15:32 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
The `about:config` page is disabled on the stable release of Firefox for Android. It is enabled on the beta and the nightly versions. Please may the `about:config` page be enabled on the stable release with a clear warning when visiting that some preferences may not work or be unstable and will receive no technical support? Similar to the desktop versions of Firefox.

### How do you know that this problem exists today? Why is this important?
There are many preferences located in the `about:config` page which are very useful and are currently only located there. I'm aware there are preferences which will not work on the Android client however I believe it would be better practice to enable the page with a clear warning instead of disabling features for users who prefer a more stable release of Firefox.

### Who will benefit from it?
I believe anyone who needs to access a preference which currently doesn't have an option in the dedicated settings would benefit from being able to use the `about:config` page. For example I would like to enable the `security.enterprise_roots.enabled` on the stable release of Firefox however I'm currently forced to use the beta release.

**Comment by hakkikaancaliskan** [comment] 2021-05-30 16:29
There is a preference added for enterprise_roots.enabled in the secret settings in nightly, it'll come to the stable.

**Comment by lolrepeatlol** [comment] 2021-05-30 17:56
dupe of #7865

**Comment by sflorean** [comment] 2021-05-31 06:43
Thanks for report! Closing as duplicate of #7865.

**Closed by sflorean** 2021-05-31 06:43 UTC
Labels: needs:triage
