### ISSUE TITLE
Allow Collections to be exported to a data backup/portability file format

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12960] opened 2020-07-26 15:55 UTC
Branched out from #12957. Please refer that issue for the whole context. And this is a continuation of #12958.

Allow Collections to be exported to file format widely accessible. Just like with Top Sites #12958 and HTML bookmark backup file. So that it becomes easy to take a backup of them and it will also offer data portability. 

Thank you. :grinning:

**Comment by kbrosnan** [comment] 2020-07-26 22:29
Closing as a duplicate of #12957. Until there is a plan to offer export the main issue is enough to track the request. The issue can be reopened if that is prioritized.

**Closed** 2020-08-28 23:02 UTC
Labels: needs:triage
