### ISSUE TITLE
[Bug] github.com - form and virtual keyboar

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#16243] opened 2020-10-29 05:34 UTC
##  Steps to reproduce
1. Go to github.com (logged out)
2. Tap on the top right menu
3. Tap at the bottom in the search field
4. The virtual keyboard appears

### Expected behavior
The text input area is in focus visible in the layout

### Actual behavior
The text input area is being hidden by the virtual keyboard

### Device information

* Android device: Android 10 Pixel 2
* Fenix version: 84.0a1 20201026092834

**Comment by karlcow** [comment] 2020-10-29 05:58
Note: The search field stays in the visible area on Chrome.

**Comment by kbrosnan** [comment] 2020-10-29 16:22
Duplicate of #16106 see also https://bugzilla.mozilla.org/show_bug.cgi?id=1673511

**Closed by kbrosnan** 2020-10-29 16:22 UTC
Labels: needs:triage, 🐞 bug
