### ISSUE TITLE
[Feature Request] Ability to download pages

### ISSUE THREAD

**Issue by Oymate** [mozilla-mobile/fenix#12340] opened 2020-07-07 11:58 UTC
### What is the user problem or growth opportunity you want to see solved?
It will give us the ability to save and open webpages when we don't have internet. Or to save for achieving.

### How do you know that this problem exists today? Why is this important?
Since the other Firefox version has this feature it is important to import it here as well.

### Who will benefit from it?
Everyone  :-)

**Comment by Amejia481** [comment] 2020-07-07 13:12
cc @vesta0

**Comment by SS1113** [comment] 2020-07-07 13:30
@Amejia481 isn't this a duplicate of the issue: https://github.com/mozilla-mobile/fenix/issues/219 ?

**Comment by Amejia481** [comment] 2020-07-07 13:32
Yes it's thanks :)
Let's close this one.

**Closed** 2020-08-28 21:56 UTC
Labels: Feature:Download, feature request 🌟
