### ISSUE TITLE
[Bug] Don't allow duplicate collection names

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#9740] opened 2020-04-06 14:03 UTC
### Why/User Benefit/User Problem
I don't believe the user should be allowed to save the same tabs in a different collection that has the same name. Or much easier to understand, the user shouldn't be able to duplicate a collection.

![collection](https://user-images.githubusercontent.com/40694158/78566749-5b0fab80-7828-11ea-9fb5-36d6251ee06a.png)

**Comment by softvision-miralobontiu** [comment] 2020-04-06 15:07
Closing as a dupe of #2917

**Comment by J-Siu** [comment] 2020-04-19 23:20
@softvision-miralobontiu I believe this is not the same as #2917 .

If I understand correctly, #2917 Is about duplicate entries within a collection.

But this issue is about creating collections with the same name. Referring the the screenshot above, you can see 2 "Medium" collections. I am able to reproduce this on nightly build#21080611. Maybe this should reopen and categorize as bug?

**Comment by softvision-miralobontiu** [comment] 2020-04-21 08:14
@J-Siu thank you for the feedback!
I'll reopen the issue, and see what happens next.

**Comment by J-Siu** [comment] 2020-04-21 13:36
Adding screenshot to show issue more clearly:
![Screenshot_20200421-093004](https://user-images.githubusercontent.com/3171920/79872226-857a7080-83b3-11ea-9de2-9cef3d837797.jpg)

**Comment by cadeyrn** [comment] 2020-04-21 14:20
Well… the name of a collection is chosen by the user itself. If someone wants to create a few collections with the same name it's an explicit user decision. Why should Fenix restrict this? 🤔

**Comment by J-Siu** [comment] 2020-04-21 14:33
If collections having same name, then they should be one the same collection.

**Comment by cadeyrn** [comment] 2020-04-21 14:36
Why? I still don't see the argument why Fenix should restrict how users can use the collections feature if there is no technical reason to forbid this case.

**Comment by J-Siu** [comment] 2020-04-21 14:40
Allowing multiple collections with the same name is just confusing, no helping user.

**Comment by softvision-miralobontiu** [comment] 2021-01-04 14:23
This is still reproducible on the latest Nightly build from 1/4.

**Closed** 2021-07-10 17:34 UTC
Labels: Feature:Collections, S3, wontfix, 🐞 bug
