### ISSUE TITLE
[Bug] Today's update keeps crashing. 

### ISSUE THREAD

**Issue by Kreuger** [mozilla-mobile/fenix#14510] opened 2020-08-31 01:53 UTC
Hey all. Since installing today's build from the nightly channel, Firefox keeps crashing on me. Even when not using it, I kept getting a message saying that it keeps closing. I tried restarting my phone but it did nothing. I had to force stop to prevent the pop-up. Not sure what had changed.

**Comment by ekager** [comment] 2020-08-31 02:48
Probably dupe of https://github.com/mozilla-mobile/fenix/issues/14486

**Comment by kbrosnan** [comment] 2020-08-31 04:34
Closing as a duplicate

**Closed by kbrosnan** 2020-08-31 04:34 UTC
Labels: needs:triage, 🐞 bug
