### ISSUE TITLE
[Bug] ETP Custom setting dropdown selections (Cookies and Tracking Content) get reset when enabling or disabling subsequent or previous fields

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#8598] opened 2020-02-20 18:18 UTC
ae294c3fd8a7ef13ecf164ee214f25b25e8ee13f
Device: Pixel 2 (Android 10)

When making a selection of the drop-down fields in Custom ETP settings (e.g, Tracking Content in in all tabs vs: private tabs) or Cookes (e.g, All Cookies). Enabling or Disabling Cookies or Tracking Content fields will reset the values in the drop-downs that the user has made.

See video.

https://streamable.com/tgzf0

**Comment by mcarare** [comment] 2020-02-24 09:38
Duplicate of https://github.com/mozilla-mobile/fenix/issues/8565

**Closed by mcarare** 2020-02-24 09:38 UTC
Labels: Feature:TrackingProtection, b:etp, needs:triage, 🐞 bug
