### ISSUE TITLE
[Bug] Bookmarlets broken

### ISSUE THREAD

**Issue by yeswap** [mozilla-mobile/fenix#14651] opened 2020-09-03 00:23 UTC
## Steps to reproduce:
Create a bookmark containing a bookmarklet. For example this bookmarklet launches Twitter's _New Tweet_ dialog and enters the current page's URI and title: 
`javascript:location.href='http://twitter.com/intent/tweet/?text='+encodeURIComponent(document.title)+' &url='+encodeURIComponent(location.href);`

### Expected behavior 
With a web page loaded, tap the address bar and begin typing the name of the bookmarklet. When autocomplete shows the bookmarklet, tap it and the bookmarket should execute. In the case of the New Tweet bookmarklet Twitter's new tweet dialog should launch with the previous page's title and URI filled in.

### Actual behavior 
Nothing happens when the autocompleted bookmarklet name is tapped

### Device information

* Android device: ? Various, including LG G4 and Samsung G4
* Fenix version: ? 79.0.5

Note: In the previous stable Firefox for Android version tapping the address bar opened the Firefox bookmarks page and bookmarkets could be launched launched from there. That feature seems to be missing in Fenix. The method of launching bookmarks described in _Expected behavior_ above is how bookmarkets work in Chromium. I prefer way the old Firefox worked but the Chromium way is better than the current situation where bookmarklets don't work at all

**Comment by cadeyrn** [comment] 2020-09-19 08:23
Duplicate of #2871.

**Comment by amedyne** [comment] 2020-12-10 19:25
Closing, refer to dup issue #2871

**Closed by amedyne** 2020-12-10 19:25 UTC
Labels: Feature:Bookmarks, feature request 🌟, 🐞 bug
