### ISSUE TITLE
[Bug] "Added to Firefox Nightly home!" snackbar is incorrectly displayed on tablets in landscape mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#8345] opened 2020-02-12 09:52 UTC
## Steps to reproduce
1. Launch Fenix.
2. Rotate the device in landscape mode.
3. Access any website.
4. Tap on 3 dot menu and then `Add to top sites`.
### Expected behavior
The `Added to Firefox Nightly home!` snackbar should be correctly displayed.
### Actual behavior
The `Added to Firefox Nightly home!` snackbar is incorrectly displayed in landscape, as the word `home!` is on a second row.
### Device information

* Android device: **Samsung Galaxy Tab A (Android 9).**
* Fenix version: **Nightly from 2/12.**

### Notes
On the mobile devices, the snackbar is displayed correctly in landscape.

![Screenshot_20200212-115001_Firefox Nightly](https://user-images.githubusercontent.com/42831109/74323183-ce97be00-4d8d-11ea-9810-ed5221704d39.jpg)

**Comment by Sparky93** [comment] 2020-02-13 10:27
Hello, I couldn't reproduce this with **Samsung Galaxy Tab A** or **Samsung Galaxy S8**, please see the picture below:


![device-2020-02-13-122337](https://user-images.githubusercontent.com/20266431/74425280-1b49ca80-4e5c-11ea-9fb1-2da3a4aab626.png)

**Comment by Diana-Rus** [comment] 2020-02-19 17:02
Hi, I can reproduce the issue with Google Pixel C (Android 8.0.0) on Firefox Beta Preview 4.0.0-beta.1 and Firefox Preview Nightly.

- Affected snack bar/notification on Firefox Beta:
"Open Link in new private tab"
![Screenshot_20200219-184803](https://user-images.githubusercontent.com/49859863/74856051-2c0dab00-534a-11ea-86e8-de4fb6118b91.png)

Note: The word "opened" is displayed on the second row.

**Comment by mcarare** [comment] 2020-10-19 11:24
This is a side effect of using `Autosizing` on a `TextView` with more than one line and width other than a fixed one.
IMO this is an acceptable side-effect that does not occur very often. The alternatives would be either setting a fixed size for the SnackBar text or not allowing multiple rows (this might result in the text not being fully shown).

Leaving this to UX decision.

**Comment by liuche** [comment] 2020-10-22 15:11
Thanks for the context. This seems like an edge case, and doesn't prevent people from using the app, so i'm going to drop the priority.

**Comment by apbitner** [comment] 2020-10-30 19:53
If this is an edge case and changing it would affect the optimal experience for the rest, then let's leave it as is.

**Closed** 2021-05-06 01:56 UTC
Labels: Feature:Snackbar, P5, S2, b:landscape, b:tablet, wontfix, 🐞 bug
