### ISSUE TITLE
[Bug] Only last 20 Collections are displayed

### ISSUE THREAD

**Issue by yosimor** [mozilla-mobile/fenix#13999] opened 2020-08-20 23:20 UTC
## Steps to reproduce
Create more than 20 collections. Visit the list of Collections.

### Expected behavior
All Collections (more than 20) should be displayed.

### Actual behavior
Only the 20 Collections created last (top 20 entries in a FIFO stack) are displayed. If a Collection is then deleted, the Collection stack is popped, and the next oldest entry, which until then had been hidden, now becomes visible again.

### Device information

* Android device: Samsung Galaxy Note 3 (ha3g), running LineageOS 14.1-20181025-UNOFFICIAL-ha3g, based on Android 7.1.2

* Fenix version: 79.0.5 (Build #2015758617)

**Comment by kbrosnan** [comment] 2020-09-24 04:34
Closing as a duplicate of #15351 as it has slightly better info.

**Closed by kbrosnan** 2020-09-24 04:34 UTC
Labels: needs:triage, 🐞 bug
