### ISSUE TITLE
[Bug] File download does not work

### ISSUE THREAD

**Issue by igor-cali** [mozilla-mobile/fenix#16168] opened 2020-10-25 18:31 UTC
## Steps to reproduce
Click a link to a file (e.g. a pdf document) and select download.

### Expected behavior
File is downloaded to device storage.

### Actual behavior
The download notification with progress bar is displayed for a long while, then error is thrown.
The issue happens also if the External download manager setting is enabled.

### Device information

* Android device: Huawei Honor 8 w/ Android 8.0
* Fennec version:
82.1.1 (Build #821120)
AC: 60.0.5, a1a471ddc
GV: 82.0-20201022145252
AS: 63.0.0

**Comment by sh-msh** [comment] 2020-10-25 20:01
I encountered the same issue. Furthermore, the notifications regarding failed downloads do not go away / keep coming back.
A couple of days ago, tried a download four times. Failed each time. Now I always get four notifications, one for each failed download. I can sweep them away. But they keep coming back after some time. Restarting the phone does not help. The downloads are not being shown in the Downloads-VIew anymore. Any way to get rid of the zombie-notifications?
Hope this issue is correct for my report.

**Comment by Shadowspear123** [comment] 2020-10-26 16:41
Same issue

**Comment by LittleAngelwings** [comment] 2020-10-26 19:33
Some users from the German support forum have the same problem with 82.1.1., me also. The two following test files can only be downloaded with activated external download-manager or with link-support with via app.

PDF https://www.jena.de/fm/41/test.pdf
epub-file from https://www.mobileread.com/forums/showthread.php?s=c49f772cc31533114fb2d3c6aa32acd1&t=334301

With nigthly no problem to download this files with deactivated download-manager.

**Comment by kbrosnan** [comment] 2020-10-26 23:59
Please retest on [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) there are numerous fixes related to downloads that are not in the release version.

**Comment by Vagabond22** [comment] 2020-10-27 00:23
I can confirm the download bug with version 82.1.1

**Device Information:**
Android 10
Firefox Daylight 82.1.1 (Build #2015770923)

**Expected Behavior:**
After clicking a link to, e.g., pdf-files, epub-files, azw3-files etc., the respective files _should be downloaded to the download folder_, provided that in Firefox settings, "Open links in apps" is not activated. No external download manager is activated.

**Actual Behavior:**
None of the above mentioned file types are downloaded (I tested with pdf, epub and azw3 files).
Exception: JPG images are downloaded to the download folder, if you touch an image and choose "Save graphics" ("Grafik speichern" in German).

Actual behavior with the tested pdf, epub, azw3 file types:
The usual download prompt appears, but the download arrow and the progress bar keep on moving, the name of the file is shown, but no file is downloaded.
I can "Pause" or "Abort" ("Pausieren" or "Abbrechen" in German), with no file being downloaded.
In some cases, I think when not waiting "long enough", in the download notification section, the download message displayed is just "Downloads null".

It seems to be a Firefox bug, as the respective files could all be downloaded successfully to the download folder with the Google Chrome browser (that was fired up just for testing purposes).

Links to the pdf and epub files tested in the [German Firefox forum](https://www.camp-firefox.de/forum/) have already been provided by user @LittleAngelwings above. But the problem described holds for any file of the types mentioned above.

**Comment by Amejia481** [comment] 2020-10-27 14:47
> I encountered the same issue. Furthermore, the notifications regarding failed downloads do not go away / keep coming back.
> A couple of days ago, tried a download four times. Failed each time. Now I always get four notifications, one for each failed download. I can sweep them away. But they keep coming back after some time. Restarting the phone does not help. The downloads are not being shown in the Downloads-VIew anymore. Any way to get rid of the zombie-notifications?
> Hope this issue is correct for my report.

The fix is already [on Beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) and will be on stable in the next release.

**Comment by Amejia481** [comment] 2020-10-27 14:49
> Please retest on [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) there are numerous fixes related to downloads that are not in the release version.

@Vagabond22 are you able to reproduce in [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)?

**Comment by Vagabond22** [comment] 2020-10-27 15:06
I installed Nightly this afternoon and the above mentioned files/file types can be downloaded to the download folder.

**Comment by Vagabond22** [comment] 2020-10-27 15:41
@Amejia481 
When stating above that "the fix is already on Beta and will be on stable in the next release." -- does that only refer to the quoted bug of the failed-download notifications coming back (which I haven't experienced so far, btw), or to the downloed problem as a whole?

**Comment by Amejia481** [comment] 2020-10-27 20:25
> When stating above that "the fix is already on Beta and will be on stable in the next release." -- does that only refer to the quoted bug of the failed-download notifications coming back (which I haven't experienced so far, BTW)

Yes, that fix is on Beta and will be soon on the stable version.

> the download problem as a whole?

The whole download problem should be fixed nightly and moving to Beta in next releases.

**Comment by Vagabond22** [comment] 2020-10-27 20:32
@Amejia481 
Thanks a lot for the clarification and for your commitment.

**Comment by Amejia481** [comment] 2020-10-27 20:33
No problem, always glad to help :)

**Comment by hebu** [comment] 2020-10-28 06:53
As a workaround, one can long-tap a link and chose to open it with an external app, as I just found out with a PDF link.

But anyway, please release a bugfix quickly, because a browser that can't handle downloads is not a browser anymore...

**Comment by Dan884** [comment] 2020-10-28 14:31
Downloads in Nightly are not fixed yet. See #16228.

**Comment by kbrosnan** [comment] 2020-10-28 17:38
That is a different issue about web extensions. I am going to close this as there have not been any new cases where file downloads from websites do not work. 

If you encounter a issue like this please test on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix). If your problem reproduces there then please file a new issue with either a URL to a file or steps on how to trigger the file download.

**Closed by kbrosnan** 2020-10-28 17:38 UTC
Labels: Feature:Download, 🐞 bug
