### ISSUE TITLE
[Bug] Letters input entering out of order

### ISSUE THREAD

**Issue by kuba-orlik** [mozilla-mobile/fenix#7342] opened 2019-12-23 11:43 UTC
## Steps to reproduce

Open a text input (it happens especially often on Discourse forums, but in other various places as well), and type some words

### Expected behavior

Words appear as I typed them

### Actual behavior

Letters come in out of order.

You can see it happening here:

https://vimeo.com/381142629

It happens only on GeckoView-powered browsers on my phone, all other apps never have this problem.

### Device information

* Android device: LG Nexus 5X
* Fenix version: 3.0.0

**Comment by buttercookie42** [comment] 2019-12-25 21:51
Which keyboard app you're using is probably relevant here as well.

**Comment by kuba-orlik** [comment] 2019-12-27 19:12
I'm using the default Android Keyboard (AOSP)

**Comment by kuba-orlik** [comment] 2020-01-01 18:23
I've tried it with AnySoftKeyboard and the result is the same - letters come in out of order, some of them appear to the right of the text input caret

**Comment by boek** [comment] 2020-01-07 17:15
@fluffyemily will link the GV bug

**Comment by Poopooracoocoo** [comment] 2020-01-10 00:21
#7457 #4208

**Comment by Poopooracoocoo** [comment] 2020-01-10 23:44
https://bugzilla.mozilla.org/show_bug.cgi?id=1569007#c5

Here ya go @boek oe (not going to correct this just to prove how messy it can be)

**Comment by thanuj10** [comment] 2020-01-27 15:33
Can confirm it happens here as well on my Nokia 6.1 Plus running Android 10.

**Comment by makotokato** [comment] 2020-02-20 04:44
@thanuj10 , could you still reproduce this on Firefox Preview Nightly that has GV75?

**Comment by makotokato** [comment] 2020-02-20 04:58
@kuba-orlik seems to verify this issue via https://github.com/mozilla-mobile/fenix/issues/4208#issuecomment-586869622

**Comment by kuba-orlik** [comment] 2020-02-20 09:51
I've tested it some more and it seems that *sometimes* the error occurs, but is less pronounced. Instead of the text entry cursor jumping around all the time, it happens more rarely and seems to happen at most one time per input field

**Comment by fluffyemily** [comment] 2020-05-19 14:43
Issue being tracked through https://bugzilla.mozilla.org/show_bug.cgi?id=1596920. Fix landed 1st May 2020. Should be available in GV 78.

**Comment by ekager** [comment] 2020-12-17 00:48
Closing because GV bug was resolved. Please open a new issue if this is still happening.

**Closed by ekager** 2020-12-17 00:48 UTC
Labels: P2, S2, needs:gv, 🐞 bug

**Comment by Poopooracoocoo** [comment] 2020-12-17 03:54
interesting that that bug specific to GeckoView on Android was closed a dupe of a bug specific to Firefox Reality for Oculus Go.

**Comment by cadeyrn** [comment] 2020-12-17 07:43
> interesting that that bug specific to GeckoView on Android was closed a dupe of a bug specific to Firefox Reality for Oculus Go

It was not "specific to Firefox Reality for Oculus Go", it was a GeckoView bug, just initially reported for Firefox Reality. The operating system of the Oculus is based on Android and Firefox Reality is using the same Android Components and GeckoView as Firefox.
