### ISSUE TITLE
Download History is not showing

### ISSUE THREAD

**Issue by ankitkaran99** [mozilla-mobile/fenix#19878] opened 2021-06-07 18:31 UTC
I am using Firefox for Android - Nightly.

91.0a1 (Build #2015814987)
AC: 91.0.20210607143102, f7f5f2378
GV: 91.0a1-20210607094749
AS: 78.0.0

Download history doesn't show any item. It is showing in Notication Drawer, but not in Firefox.

I have attached the screenshots.
![Screenshot_20210607_233209](https://user-images.githubusercontent.com/34885126/121070580-899e6300-c7ec-11eb-96eb-4c8dad215bb2.jpg)
![Screenshot_20210607_233215](https://user-images.githubusercontent.com/34885126/121070594-8c00bd00-c7ec-11eb-81e2-c81639824b1b.jpg)

**Comment by mcarare** [comment] 2021-06-08 06:27
@ankitkaran99 Downloads that are in progress are not shown in the list. Is the list still empty when the file has finished downloading?

**Comment by ankitkaran99** [comment] 2021-06-08 06:30
After download finished, it was visible in Dowloads.

**Comment by anotherus3r** [comment] 2021-06-08 14:06
For showing in-progress and failed downloads in the download history, there's #14961

**Comment by mcarare** [comment] 2021-06-08 15:36
Closing this as a duplicate of #14961.

**Closed by mcarare** 2021-06-08 15:36 UTC
Labels: Feature:Download, needs:triage
