### ISSUE TITLE
[Bug] White space on video full screen mode with bottom toolbar enabled and "Scroll to hide toolbar" disabled

### ISSUE THREAD

**Issue by georapbox** [mozilla-mobile/fenix#15146] opened 2020-09-17 06:16 UTC
## Steps to reproduce

1. Go to Settings > Customize
2. Ensure that toolbar is set to Bottom
3. Ensure that "Scroll to hide toolbar" is disabled.
4. Play a video in Youtube, Vimeo or Twitch (I tested on those sites but I guess it's a generic issue)
5. Enter full screen mode

### Expected behavior

The video should take over the whole screen.

### Actual behavior

The video does not take over the whole screen. There is a white space at the bottom with the same height as the toolbar.
In Vimeo, in landscape mode even the video player's toolbar is not accessible (hiding behind the white bar).

![Screenshot_20200917-084830](https://user-images.githubusercontent.com/6596039/93426644-1e5eda80-f8c5-11ea-84c4-03abdccb7089.png)

Video full screen mode does not seem to be affected when toolbar is set to bottom but "Scroll to hide toolbar" is enabled or when toolbar is set to top no matter if "Scroll to hide toolbar" is enabled or disabled.

### Device information

* Android device: Motorola One (XT1941-4)
* Fenix version: Nightly 200916 06:01 (Build #2015764211)

**Comment by SL-Lee** [comment] 2020-09-17 17:44
Duplicate of #14974. See [my comment](https://github.com/mozilla-mobile/fenix/issues/14974#issuecomment-694385050) on the issue.

**Comment by Mugurell** [comment] 2020-09-29 11:41
Fixed in https://github.com/mozilla-mobile/fenix/issues/15272.

**Closed by Mugurell** 2020-09-29 11:41 UTC
Labels: needs:triage, 🐞 bug
