### ISSUE TITLE
Text Selection Magnifier

### ISSUE THREAD

**Issue by gitblogman** [mozilla-mobile/fenix#21288] opened 2021-09-14 18:36 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Is it possible to implement a feature ie magnifier on text selection.

### How do you know that this problem exists today? Why is this important?

I am using nightly latest version from playstore and it's not present there.

### Who will benefit from it?

Everyone.

**Comment by cadeyrn** [comment] 2021-09-14 19:18
Duplicate of #20618 and https://bugzilla.mozilla.org/show_bug.cgi?id=1639087.

**Comment by sheikh-azharuddin** [comment] 2021-09-15 04:03
As per the bugzilla mozilla is not considering this as priority feature ..so fix stopped!

Interestingly the magnifier thing is present in the address bar when selecting text from address but not available for web pages!

**Closed** 2021-09-21 07:52 UTC
Labels: needs:triage
