### ISSUE TITLE
UI bug in tab switcher

### ISSUE THREAD

**Issue by Doctor-Abhi** [mozilla-mobile/fenix#16744] opened 2020-11-25 16:29 UTC
The background becomes white and url becomes invisible.
Steps to reproduce the bug-
1.Open a site
2.Go to search bar and visit some other site, It gives u 2 sites now.
3.Now use the 3 dot menu to bring up the back and forward buttons
4.Long press the back button it opens the visited links.
Here is wherw the UI bug is

Device: Redmi K20 pro, running xiaomi.eu miui 12.0.5.0 based on Android 10.
Note:- I have seen this bug on both Firefox 84.0.0-beta2 and Firefox Nightly November 24,2020

![Screenshot_2020-11-25-21-42-11-852_org mozilla firefox_beta](https://user-images.githubusercontent.com/75034835/100255323-5fc8d180-2f69-11eb-9b96-4e9b84896156.jpg)
![Screenshot_2020-11-25-21-39-59-067_org mozilla firefox_beta](https://user-images.githubusercontent.com/75034835/100255374-6a836680-2f69-11eb-83c7-54506dd656dd.jpg)

**Comment by Dunexus** [comment] 2020-11-25 16:35
Duplicate of https://github.com/mozilla-mobile/fenix/issues/16422

**Closed** 2020-11-25 16:36 UTC
Labels: needs:triage

**Comment by Doctor-Abhi** [comment] 2020-11-25 16:37
it was a duplicate. Sorry, my bad.

**Comment by Dunexus** [comment] 2020-11-25 16:39
Don't worry, github search feature isn't always good at finding issues with different but related keyword.

**Comment by Doctor-Abhi** [comment] 2020-11-25 16:42
Its my first time using Github I should read more. The UI is just fine in 83.1.0 something must have gone wrong while adding the grid layout.
