### ISSUE TITLE
[Bug] Site permissions - Video autoplay is not working on Wi-Fi when it is enabled

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16206] opened 2020-10-27 13:53 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open the firefox
2. Tap Settings
3. Tap Site Permissions
4. Tap Autoplay
5. Select Block audio and video on cellular data only
6. Go back to home page
7. Search and go to m.youtube.com
8. Scroll and look at the video without starting it
### Expected behavior
The video will start autoplaying
### Actual behavior
Video does not start autoplay
### Device information
 Xiaomi Redmi Note 4X - Android 7.0
Vestel Venüs V3-Andoid 6.0.1
* Android device: yes
* Fenix version: Android for firefox beta 82.0.0

**Comment by Amejia481** [comment] 2020-11-17 15:27
@BigSamSampson we did some improvements related to autoplay could you verify if this is still an issue in [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)? I will also as to the QA team to verify.

**Comment by abodea** [comment] 2020-11-18 10:05
Hello, @Amejia481 I cannot reproduce this issue on the latest Nightly **18/11** with **Google Pixel 4 XL (11),** **Samsung Galaxy S10+ (10).**
The autoplay worked just fine.
Do you think we can close this issue? 
@BigSamSampson can you still reproduce this issue?

**Comment by Amejia481** [comment] 2020-11-18 14:42
Thanks @abodea,  @BigSamSampson I will proceed and close the issue, please feel free to reopen if needed :)

**Closed by Amejia481** 2020-11-18 14:42 UTC
Labels: Feature:Media, Feature:Settings, Feature:SitePermissions, 🐞 bug
