### ISSUE TITLE
[Dark Theme] Use darker styles for tab headers in grid view

### ISSUE THREAD

**Issue by Xashyar** [mozilla-mobile/fenix#16808] opened 2020-12-02 07:49 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
![signal-2020-12-02-090238](https://user-images.githubusercontent.com/34171942/100843517-b8c7c680-348f-11eb-8eea-418666a6ef19.jpeg)

In dark mode, tab headers and `Select tabs` button preserve their light tint, which creates a protruding contrast.

**Comment by cadeyrn** [comment] 2020-12-02 07:52
Duplicate of #16152.

**Comment by Xashyar** [comment] 2020-12-02 10:14
Thanks for the heads up! @cadeyrn

**Closed** 2020-12-02 10:13 UTC
Labels: needs:triage
