### ISSUE TITLE
FNX3-16747 ⁃ [Bug] Crash when deleting browsing data

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3035] opened 2019-05-31 07:59 UTC
## Steps to reproduce
1. Load a page.
1. Go to Settings - Delete browsing data and select "Browsing history and site data" - Allow

### Expected behavior
Data should be deleted and the user can continue using the app.

### Actual behavior
Crash

### Device information
* Android device: Motorola Moto G6 (Android 8), Sony Xperia Z5 PRemium (Android 7.1.1)
* Fenix version: 1.0.1922(#11510609)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3240337/logcat.txt)

**Comment by sblatz** [comment] 2019-05-31 19:05
Should be fixed by https://github.com/mozilla-mobile/fenix/commit/0036938312161905f3aae64060d4ce94937a2893

**Comment by LittleAngelwings** [comment] 2019-06-01 02:30
Can't reproduce issue any more in latest raptor.

**Comment by softvision-miralobontiu** [comment] 2019-06-03 06:45
Verified as fixed on the latest build 1.0.1922 (#11530616), with Sony Xperia Z5 Premium (Android 7.1.1).

**Closed** 2020-08-12 17:39 UTC
Labels: b:crash, eng:qa:verified, 🐞 bug
