### ISSUE TITLE
[Bug][L10n] Tab counter icon from Tabs tray is truncated in RTL

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#19204] opened 2021-04-23 08:05 UTC
## Steps to reproduce
1. Launch Fenix and set the language to Arabic/enable Force RTL layout direction;
2. Tap the tab counter;
3. Observe the tab counter icon from Tabs Tray;
### Expected behavior
Tab counter icon from Tabs tray is visible in RTL.
### Actual behavior
Tab counter icon from Tabs tray is truncated in RTL.
![rsz_screenshot_20210423-105638](https://user-images.githubusercontent.com/48799384/115839923-d1774f80-a423-11eb-97d4-4ca951310a34.png)

### Device information

* Device vendor / model and Android version: Pixel 2 (Android 9)
* Firefox for Android version: ? Nightly 4/23 and Beta 89.0.0-beta.1

**Comment by mcarare** [comment] 2021-04-23 15:47
Duplicate of https://github.com/mozilla-mobile/fenix/issues/19180.

**Closed by mcarare** 2021-04-23 15:47 UTC
Labels: Feature:Tabs, S2, 🌐 L10N:RTL, 🐞 bug
