### ISSUE TITLE
Instant startup crash on Motorola G4 Play

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#28310] opened 2022-12-25 21:59 UTC
### Steps to reproduce

Try launching Firefox.

### Expected behaviour

It works.

### Actual behaviour

It crashes, and I'm not even seeing the regular crash reporter (if I should be seeing it?), but instead only the generic Android crash reporter ("Firefox has stopped")

### Device name

Motorola G4 Play

### Android version

Android 6.0.1

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1, 2015-12-25 Nightly (2015923369)

### Additional information

![2022-12-25 Nightly crash](https://user-images.githubusercontent.com/7611366/209482857-64153ce0-db2c-404e-8cc3-579f20293c82.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22194)

**Comment by buttercookie42** [comment] 2022-12-25 23:11
If I've not made a mistake, the regression range is between 50cc477d14317cf671c72fce647d2d0efbef5edb and 7598cbca67eff1a0eb64726974faca111c562ed6. As the only changes in-between were affecting tests only, it must have been the upgrade from Android-Components 110.0.20221221190038 to 110.0.20221222151132.

Meanwhile today's GVE (as obtained via mozregression) launches fine.

**Comment by cpeterso** [comment] 2022-12-26 20:31
Thanks for finding the regression range! That's a huge help.

This crash is likely related to https://github.com/mozilla-mobile/fenix/issues/28297.

**Comment by cpeterso** [comment] 2022-12-27 21:23
A Fenix engineer can reproduce this crash locally. I'm closing this GitHub issue because we're now tracking the crash in Bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1807716

**Closed by cpeterso** 2022-12-27 21:23 UTC
Labels: 🐞 bug, needs:triage
