### ISSUE TITLE
[UX] Site Permission Prompts

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#332] opened 2019-01-31 17:22 UTC
This issue is all about the prompts that we show when a website needs to ask for permission to use camera, location, ... what else is there?

**Comment by lime124** [comment] 2019-01-31 23:16
@bbinto this is going to have to move to milestone 2.

**Comment by pocmo** [comment] 2019-02-01 10:44
This seems to be a duplicate of #191?

**Comment by st3fan** [comment] 2019-02-01 14:22
@lime124 Can we prioritize the permission prompts to be done early in M2? I think it is what we want to start with from an engineering perspective for the bigger Site Permissions story.

**Comment by lime124** [comment] 2019-02-02 04:48
@brampitoyo are you able to start working on this on Monday?

**Comment by brampitoyo** [comment] 2019-02-04 05:36
There are a couple of permissions that are immediately important to design for:

1. Notifications
2. Location
3. Camera
4. Microphone
5. Camera + Microphone (together)
6. Bluetooth
7. Local Storage

Furthermore, some permissions are handled differently, because Fenix will first need to ask Android System for access, *before* it can grant access to individual sites.

Fennec already has a way to handle permission prompts. I won’t attempt to reinvent the wheel here. Instead, I will simply try to align the visual design to Fenix’s house style.

Let’s tackle them one by one.

# 1. Notifications

**Need Android System access?**
No

This permissions is the most straightforward of all. No system dialogue. No “Don’t ask me”.

We simply say:

> **Allow this site to send notification?**
> [Don’t allow] [Allow]

<img width="360" src="https://user-images.githubusercontent.com/51007/52191172-42180d00-28a8-11e9-9c7a-280314eef126.png">

# 2. Location

**Need Android System access?**
Yes

Although we need to show the Android System dialogue (which we cannot alter in any way) before showing our own, location permission itself is simple:

> **Allow this site to use your location?**
> [ ] Don’t ask me again on this site
> [Don’t allow] [Allow]

<img width="320" src="https://user-images.githubusercontent.com/51007/52191260-a89d2b00-28a8-11e9-8df4-31c2ac27fb45.png"> <img width="320" src="https://user-images.githubusercontent.com/51007/52191270-b9e63780-28a8-11e9-9e6a-33680e6e4434.png">

# 3. Camera

**Need Android System access?**
Yes

This permission is complicated by the fact that:

1. The user will need to pick a camera before proceeding
2. In the future, the user may elect to pick another camera

Fennec handles problem 1 by showing a drop-down menu that will appear *on top of* the existing modal dialogue. Fenix will handle it by using radio buttons. We’re pretty confident that the radio buttons won’t ever overcrowd the screen, because smartphones don’t have that many cameras available to use.

Fennec handles problem 2 by re-showing the same dialogue. We will handle it by rewriting the dialogue.

The first time around, we say:

> Allow this site to use your camera?
> [Don’t allow] [Allow]

Every other time after that, we say:

> Select camera to use
> [Cancel] [OK]

<img width="320" src="https://user-images.githubusercontent.com/51007/52191330-0d588580-28a9-11e9-85c8-744d3b155aff.png"> <img width="320" src="https://user-images.githubusercontent.com/51007/52191336-15182a00-28a9-11e9-9240-00085452868e.png">

**Dialogue shown on subsequent triggers**

<img width="320" src="https://user-images.githubusercontent.com/51007/52191441-7f30cf00-28a9-11e9-89cc-52764901bf9c.png">

# Microphone

**Need Android System access?**
Yes

This permission behaves and looks identically to camera permission.

Instead of saying:

> Allow this site to use your camera?
> Select camera to use

We say:

> Allow this site to use your microphone?
> Select microphone to use

<img width="320" src="https://user-images.githubusercontent.com/51007/52191527-f1091880-28a9-11e9-959c-f202d693c906.png"> <img width="320" src="https://user-images.githubusercontent.com/51007/52191534-f8c8bd00-28a9-11e9-8c8d-4d0317515334.png">

**Dialogue shown on subsequent triggers**

<img width="320" src="https://user-images.githubusercontent.com/51007/52191537-03835200-28aa-11e9-9015-1eff4c723f0a.png">

# 4. Camera + Microphone (together)

This permission behaves and looks identically to camera and microphone permissions.

But there’s a twist: how do we show a list of cameras and microphones in one modal dialogue?

Android System solves this problem by showing one dialogue after the other, and labelling them “1 of 2” and “2 of 2”.

Fenix will solve this problem not by using two drop-down menus. Instead, we will show the radio list of microphones right underneath the list of cameras.

On subsequent times, we will again modify the string slightly.

**System dialogue – shown first**
<img width="320" src="https://user-images.githubusercontent.com/51007/52191613-7bea1300-28aa-11e9-9031-f8e8b9dfbf70.png"> <img width="320" src="system - camera and microphone - 2 of 2 2x](https://user-images.githubusercontent.com/51007/52191624-8a382f00-28aa-11e9-82d0-41a4afb09d03.png">

**Fenix dialogue – shown after the user taps “Allow” on system dialogue**
<img width="320" src="https://user-images.githubusercontent.com/51007/52191650-a9cf5780-28aa-11e9-917d-b59cd2648e2f.png">

**Dialogue shown on subsequent triggers**
<img width="320" src="https://user-images.githubusercontent.com/51007/52191665-c4093580-28aa-11e9-8904-7bb24a54de87.png">

# 5. Bluetooth

**Need Android System access?**
No

When a site wants to pair with another device via Bluetooth, Fenix will show a dialogue that says:

> Pair this site with
> [ ] Device 1
> [ ] Device 2
> [ ] Device 3
> [ ] etc.
> [Cancel] [Pair]

<img width="360" src="https://user-images.githubusercontent.com/51007/52191716-fca90f00-28aa-11e9-9cea-f57c06503c56.png">

**Consider including a loading indicator to the top-right corner of this dialogue**, to make it clear that Fenix will keep searching for connectible Bluetooth devices, as long as this dialogue remains open.

# 6. Local Storage

**Need Android System access?**
Yes

We say:

> Allow this site to permanently store data on your device?
> [Don’t allow] [Allow]

<img width="320" src="https://user-images.githubusercontent.com/51007/52191779-4560c800-28ab-11e9-8c66-1ef362491ef3.png"> <img width="320" src="https://user-images.githubusercontent.com/51007/52191784-4eea3000-28ab-11e9-90fd-1d6b458faaf5.png">

**Question**: does this permission also apply to times when the user needs to browse, select and upload files (e.g. select/upload files to a form or a remote server). If yes, then we will need to reword our dialogue so it’s more generic and can apply to this situation.

**Comment by brampitoyo** [comment] 2019-02-04 05:36
@st3fan Hope the mockups above help answer some of your questions! @colintheshots this issue is now ready for feedback and breakdown.

**Comment by brampitoyo** [comment] 2019-02-04 05:47
I should note one corner case that’s missing from these mockups, but doesn’t require any visual.

1. I allow Android System to let Fenix access my camera
2. I allow Fenix to let a site access my camera
3. I go into Settings > Apps & notifications > Fenix > Permissions
4. I turn the Camera toggle OFF

In this scenario, our behaviour should be as follows:

1. When the Camera permission is triggered, Fenix cannot show its permission dialogue
2. Instead, Fenix will show the Android System dialogue
    a. If, on this System dialogue, the user taps “Deny”, the toggle under Android Settings remain OFF. The dialogue closes.
    b. If the user taps “Allow”, the Android Settings toggle will be switched to ON. The dialogue closes, and the camera is now given access.

**Question**: do we have the power to invoke this Android System dialogue when we detect this scenario? If yes, then that’s not a problem.

If no, then we’ll need to think of a solution. For example: if we show an interstitial dialogue with a “Continue” button, can it then trigger the Android System permission dialogue?

**Comment by brampitoyo** [comment] 2019-02-05 03:44
I’ve just updated the mockups above to better fit its visual design with the rest of Fenix (panel flush against the bottom of the screen), and refine the copy a bit (saying the site domain instead of a saying a generic “this site”).

No other behaviour change has been made.

**Comment by bbinto** [comment] 2019-02-08 20:08
@brampitoyo please close if ready for eng.

**Comment by lime124** [comment] 2019-02-12 21:52
@st3fan @colintheshots - let us know if you have any questions or feedback. if not he issue can be closed. thanks!

**Comment by colintheshots** [comment] 2019-02-15 23:01
I'm assuming the default indeterminate Progress Bar will work for searching for Bluetooth devices?

I believe the prompt to access files will also be required for uploading any files from the SDcard. In general, we'll want that even though it's not required to access files in internal storage.

We can absolutely detect that the Camera permission isn't granted. I'm not sure if GeckoView only checks on initial page load though. We might require additional features if they don't support it. It's a bit harder to detect Never Ask Again and handle that case, but since we're a user-centric company, I think we should respect that choice.

**Comment by brampitoyo** [comment] 2019-02-17 23:59
@colintheshots 

## Progress bar

Colin wrote:
> I'm assuming the default indeterminate Progress Bar will work for searching for Bluetooth devices?

Yes. We can either use a progress bar like this:

<img width="360" src="https://user-images.githubusercontent.com/51007/52921210-92e43700-3379-11e9-9029-baf21266a957.gif">
<img width="360" src="https://user-images.githubusercontent.com/51007/52921208-8829a200-3379-11e9-9c90-6ba697ecf7b2.png">

Or a progress bar like this:

<img width="145" src="https://user-images.githubusercontent.com/51007/52921219-ac857e80-3379-11e9-88fd-2d6fdf5eeeb1.gif">
<img width="360" src="https://user-images.githubusercontent.com/51007/52921273-2ae22080-337a-11e9-9fe7-136ff829d4fa.png">

To make things easy, if Fenix already has a default progress bar (ie. while a website is loading), we can use that, but make the animation infinite.

## Uploading files

Colin wrote:
> I believe the prompt to access files will also be required for uploading any files from the SDcard.

So, in that case, let’s change our string from:
> Allow {sitename} to permanently store data on your device?

To:
> Allow {sitename} to permanently store data on your device, and ask you to upload files?

Alternatively, if Fenix can distinguish between `store data` and `upload data` intents, then we can keep the old string, and add a new one only when the user is about to upload a file:

> Allow your device to upload files to {sitename}?

## Never ask again

Colin wrote:
> It's a bit harder to detect Never Ask Again and handle that case, but since we're a user-centric company, I think we should respect that choice.

I support handling this scenario, but it will make the UI a little more complicated. Either we need to add a checkbox that says “remember my decision”, or add another button.

Do you think that we can address this issue later, or do we need to do it before Fenix 1.0 releases?

**Comment by colintheshots** [comment] 2019-02-20 17:33
I think we're good here. We show the OS dialog first and we don't have control over its contents. If we show another wasteful dialog first to offer Remember My Decision, it won't benefit the users much.

If the user denies the OS dialog once, the Android OS permission prompt will already offer Never Ask Again on the next occasion. At that point, the OS silently ignores us if we ask.

I think it's more interesting to remember the decision for that site in particular in our secondary prompt.

**Closed** 2020-08-25 07:37 UTC
Labels: eng:ready
