### ISSUE TITLE
export bookmarks

### ISSUE THREAD

**Issue by theothersophie** [mozilla-mobile/fenix#16627] opened 2020-11-18 03:31 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

I want to be able to export my bookmarks from mobile

### How do you know that this problem exists today? Why is this important?

I wiped my desktop but forgot my firefox password, so the only place I was logged in was on mobile. I would lose all my bookmarks if I reset my password. Luckily, I found an old back up on my computer.

### Who will benefit from it?

People who would like to move their bookmarks out of firefox without a desktop/locked out of desktop

**Comment by cadeyrn** [comment] 2020-11-18 08:32
Duplicate of #417.

**Comment by sflorean** [comment] 2021-01-11 08:19
Closing as duplicate, based on the above comment.

**Closed by sflorean** 2021-01-11 08:19 UTC
Labels: needs:triage
