### ISSUE TITLE
collections are not syncing 

### ISSUE THREAD

**Issue by lmalony178** [mozilla-mobile/fenix#16201] opened 2020-10-27 05:01 UTC
### android 11 -

* Android device: yes :an android
* Fenix version: firefox version :81.1.5

**Comment by cadeyrn** [comment] 2020-10-27 07:58
Duplicate of #6512.

**Comment by AndiAJ** [comment] 2020-10-27 08:27
As @cadeyrn mentioned, I'll go ahead and close it in favor of #6512

**Closed by AndiAJ** 2020-10-27 08:27 UTC
Labels: needs:triage, 🐞 bug
