### ISSUE TITLE
[Bug]: When opening a sponsored tile in private browsing, the other one is no longer displayed

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#24100] opened 2022-03-04 15:36 UTC
### Prerequisites
Have 2 sponsored tiles displayed in the Top Sites section. 

### Steps to reproduce

1. Open Fenix and Long tap on a sponsored tile.
2. Tap "Open in private tab".
3. Return to homepage and observe the Top sites section/ sponsored tiles. 

### Expected behaviour
The same sponsored tiles are correctly displayed. 

### Actual behaviour
One of the tiles, disappears. 

### Device name

Samsung A32

### Android version
Android 11

### Firefox release type
Firefox Nightly

### Firefox version
99.0a1

### Additional information
- If the sponsored tile is opened again in normal tab, after returning to the homepage, both sponsored tiles from prerequisites are displayed. 
- This issue seems to be intermittent, since I can't reproduce it every time.
- Not reproducible when only one tile is displayed.

https://user-images.githubusercontent.com/58466444/156793587-58c7245c-bf2b-4803-947b-e9617e195912.mp4

**Comment by mcarare** [comment] 2022-04-18 14:23
@sflorean can you (or someone else from QA) please retest this, I cannot reproduce it anymore? 
Since this bug was opened some related refactoring (app state) has been merged.
Thank you!

**Comment by SoftVision-LorandJanos** [comment] 2022-04-19 08:20
Verified as fixed on the latest Nightly 101.0a1 (2022-04-19).
Device used: Oppo Reno 6 (Android 12).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-04-19 08:20 UTC
Labels: 🐞 bug, eng:qa:needed, S3, Feature:TopSites
