### ISSUE TITLE
[Bug]: "Firefox pasted from your clipboard" message when trying to copy a link

### ISSUE THREAD

**Issue by Tursko** [mozilla-mobile/fenix#25248] opened 2022-05-16 14:16 UTC
### Steps to reproduce

1. Copy a URL to your clipboard (in general, doesn't have to be in firefox). I copied a link that my friend messaged me.
2. Open a new firefox tab.
3. Navigate to a website manually (lets say google.com).
4. **Hold down** on the address bar (with the intention to copy the link). 

### Expected behaviour

The copy menu should be displayed and the message "Firefox pasted from your clipboard" should not show up since I'm not pasting anything from my clipboard.

### Actual behaviour

The "Firefox pasted from your clipboard" message overlays on top of the action bar. Which means I have to wait for the message to go away before I can copy the address bar link.

### Device name

Google Pixel 5

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

100.1.2

### Additional information

![signal-2022-05-16-09-17-08-456.png](https://user-images.githubusercontent.com/18274896/168613712-d351ee9f-5dfe-47bf-9506-e586ba6ae1d6.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20463)

**Comment by marcel263** [comment] 2022-05-16 19:50
Dear, to prevent Firefox from reading the clipboard from the UI, disable "clipboard suggestions" from the Search settings. This prevents ghr clipboard from being read. Alternatively, as a radical option, one could consider disabling altogether the clipboard alerts in Android setttings.

**Comment by Tursko** [comment] 2022-05-16 19:53
Sure, but this is still a bug. It never happened before version 100 and where is it even pasting the link? No where in my eyes.

**Comment by marcel263** [comment] 2022-05-17 07:25
> Sure, but this is still a bug. It never happened before version 100 and where is it even pasting the link? No where in my eyes.

If you think it is a bug since the clipboard is empty, be prepared to have the notification with anything in the clipboard anyway unless you disable the feature altogether

Perhaps the UI could be modified to check the clipboard state before reading it thus reducing the message?

**Comment by Tursko** [comment] 2022-05-17 15:06
Clipboard isn't empty. I provide steps to reproduce the issue which involves copying something to your clipboard. This is simply a bug. Firefox is for whatever reason attempting to paste from my clipboard at a time where I'm not requesting it.

**Comment by marcel263** [comment] 2022-05-17 15:07
If you are not taking the effort to read and understand what is happening then personally I cannot help you. As stated, Firefox reads the clipboard, this can be disabled through its settings.

**Comment by Tursko** [comment] 2022-05-17 15:12
Have you attempted to reproduce the issue yourself? The issue only occurs in one specific scenario. That scenario is when holding down on the address bar. I can open the address bar, copy, paste, etc. I will never receive that message. And again, I use the copy/paste action daily and this is very much a new occurrence. 

Did Firefox only recently start reading from the clipboard after version 100?

**Comment by marcel263** [comment] 2022-05-17 15:17
Firefox reads the clipboard to check for URLs and it will prompt you for a possible "paste & go" feature. Have you tried disabling this feature as specified?

**Comment by Tursko** [comment] 2022-05-17 15:21
> Firefox reads the clipboard to check for URLs and it will prompt you for a possible "paste & go" feature. Have you tried disabling this feature as specified?

I disabled 'Show clipboard suggestions' and the same message still displays.

**Comment by marcel263** [comment] 2022-05-17 15:25
Perhaps the API is being too invasive by still checking the clipboard state regardless of reading it, and still triggering this alert. Or the Android system is being overly careful. Regardless, now that you have verifiably disabled the clipboard suggestions feature, it is surely a bug.

**Comment by Tursko** [comment] 2022-05-17 15:27
Yeah interesting. Also makes sense that Firefox is reading the clipboard for paste and go. Thanks for the help investigating further.

**Comment by Alexandru2909** [comment] 2022-05-18 14:13
Hi, @Tursko ! Fenix also checks if the clipboard is empty or not in order to show or hide the `Paste` [contextual menu](https://github.com/mcarare/fenix/blob/dbc329f8b6f287f23a4d8e51a8eed618e4e8d385/app/src/main/java/org/mozilla/fenix/utils/ToolbarPopupWindow.kt#L86). I believe this is the reason why Android displays the "Firefox pasted from your clipboard" message. 

Also, disabling the clipboard suggestions settings hides the [fill link from clipboard](https://github.com/mozilla-mobile/fenix/blob/72b9e7e1747b547640f55646bb0582fe00a4e8f3/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt#L810) suggestion.

Since this is the expected behavior, I think we can close this issue.

**Comment by Tursko** [comment] 2022-05-18 14:23
I suppose it makes sense. It only really affects me since I use the address bar at the bottom. 

Thanks!

**Closed** 2022-05-18 14:23 UTC
Labels: 🐞 bug, needs:triage

**Comment by Tursko** [comment] 2022-10-07 18:33
Is there anything I can do to prevent the message from being displayed? I have the autofill keyboard setting disabled but I always see the message.

**Comment by Alexandru2909** [comment] 2022-10-10 11:22
Hi @Tursko! I think the setting you're looking for is "Show clipboard access" under [privacy management](https://support.google.com/pixelphone/answer/2824802?hl=en).
