### ISSUE TITLE
[Bug] Able to save duplicate credentials from the same site

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#12751] opened 2020-07-20 21:39 UTC
Do we want to allow users to save dupe credentials?

## Steps to reproduce
I was able to save the same password on the same page, following these STR:

1. Go to twitter.com, fill in valid credentials, save them.
1. Verify that the credentials are saved in Logins and passwords.
1. In Logins and passwords, disable the Autofill option.
1. Go to Settings - Delete browsing data, check only Cookies and tap on the Delete browsing data.
1. Close Fenix.
1. Reopen Fenix, and go to the twitter.com page and refill the credentials from step 2.
1. The Save prompt is displayed again and the credentials are saved again - duplicate.

![](https://user-images.githubusercontent.com/40694158/87919320-46c28800-ca80-11ea-872f-b3e9daddc7b0.jpg)

### Device information
Tested on the 7/20 Nightly build with Samsung Galaxy Tab S6 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by eliserichards** [comment] 2020-07-20 21:40
Found during QA on https://github.com/mozilla-mobile/fenix/issues/10173#issuecomment-660901728

**Comment by liuche** [comment] 2020-08-10 18:30
No, we don't want to let users save duplicate credentials, and they should never have 2 of the same credentials in their logins list. Even if there is some deduping going on behind the scenes, we shouldn't show that prompt (or possibly autofill the way desktop does, but that's probably out of scope).

**Comment by softvision-miralobontiu** [comment] 2020-08-25 07:57
I was able to reproduce the duplicate credentials on RC 80.1.0-RC.1, with Samsung Galaxy Tab S6 (Android 9), with twitter.com account. Using the following STR:

1. Go to twitter.com and sign in with valid credentials.
2. When asked to save the credentials, tap on "Save".
3. Log out from twitter.com.
4. Delete the auto-filled credentials.
5. Sign in again on twitter.com, with the same credentials.

Actual results:
The prompt is displayed again, The user can save again the same credentials. Fenix doesn't recognize the duplicate. There is no grayed out "Save" button (non-clickable).

**Comment by ekager** [comment] 2020-09-15 00:21
@softvision-miralobontiu can you reproduce on Nightly?

**Comment by softvision-miralobontiu** [comment] 2020-09-28 12:30
Hi all!
(Sorry for the late response, I was on PTO.)

I wasn't able to reproduce this issue on the latest Nightly from 9/28, but, **I've reproduced it on RC 81.1.1** with Samsung Galaxy Tab S6 (Android 9) following the steps:
1. Go to twitter.com, fill in valid credentials, save them.
2. Verify that the credentials are saved in Logins and passwords.
3. In Logins and passwords, disable the Autofill option.
4. Go to Settings - Delete browsing data, check only Cookies, and tap on the Delete browsing data.
5. Close Fenix.
6. Reopen Fenix, and go to the twitter.com page and refill the credentials from step 2.
7. The Save prompt is displayed again and the credentials are saved again - duplicate.

**Comment by softvision-miralobontiu** [comment] 2020-10-06 08:20
I was not able to reproduce this issue on the latest RC build 81.1.3, nor on the latest Nightly build from 10/6 with Samsung Galaxy Tab S6 (Android 10).
I will close this issue.

**Closed by softvision-miralobontiu** 2020-10-06 08:20 UTC
Labels: Feature:Logins, needs:ac, 🐞 bug
