### ISSUE TITLE
[Bug] Unable to select "Accept the Risk and Continue" button on "Secure Connection Failed" dialog.

### ISSUE THREAD

**Issue by philip-lamb** [mozilla-mobile/fenix#10721] opened 2020-05-18 03:47 UTC
## Steps to reproduce
1. Have HTC 10 device (5" diagonal screen)
1. Visit https://untrusted-root.badssl.com/
1. Tap "Advanced".
1. Note that URL bar covers the button labelled "Accept the Risk and Continue", so wait for URL bar to auto-hide.
1. Tap "Accept the Risk and Continue".

### Expected behavior
* Button is activated and browser proceeds to site.

### Actual behavior
* Button cannot be selected by tapping, instead the previous element is selected, which is "Go Back (Recommended)". Page does not allow scrolling past last element.

### Device information
* Android device: HTC 10, Android 8.0
* Fenix version: Nightly 200517 (Build #21380606)

Depends on: https://github.com/mozilla-mobile/fenix/issues/6380

**Comment by philip-lamb** [comment] 2020-05-18 03:53
This appears to be a more general layout bug, in that buttons that appear behind the URL bar cannot be selected. Verified not present in Firefox Preview 5.0.0 (Build #21212137).

**Comment by ekager** [comment] 2020-05-18 17:55
Possible dupe of #10578 (ie see https://github.com/mozilla-mobile/fenix/issues/10578#issuecomment-628711075)

**Comment by gawa971** [comment] 2020-06-03 03:05
Maybe two or three weeks ago I ran into this bug for the first time because I started using daily a website with a self-signed certificate. It wasn't an issue because by zooming in I could still tap the "Accept the risk" button.

Since I upgraded Firefox Preview, zooming in is not enough. The button "Accept the risks" cannot be selected anymore.

I do not upgrade regularly Firefox Preview so I don't know which version made this bug worse. I just know for sure it was possible to tap by zooming with a version not older than 3weeks ago. I don't know if it helps and if tracking a regression would make sense here since even then it was already a bug. The button was usable, but just barely...

Like @philip-lamb, I think the button itself is working fine. It's probably a layout bug preventing us to click on it, maybe depending on the size of the screen ?

### Steps to reproduce
Go to https://untrusted-root.badssl.com/
Tap "Advanced"
Try to tap "Accept the risk" --> doesn't work
Zoom in on this button
Try again to tap "Accept the risk" --> worked with a previous version, doesn't work anymore

### Workaround
three dots on the bottom right -> Switch "force desktop mode" -> now the button works. Disabling the desktop mode refreshes the page in mobile mode. But since the warning has been accepted/bypassed succesfully once, it loads just fine.

### Device information
Samsung S10e
Android 10
Nightly 200602 06:01 (build #21540609)
44.0.20200531130125, 2ac91e359
GV: 78.0a1-20200529095426 (more recent than the one in [#10578 comment](https://github.com/mozilla-mobile/fenix/issues/10578#issuecomment-635426355))
AS: 0.59.0

**Comment by carriesmi** [comment] 2020-08-24 16:42
I am having same issue on Samsung M20 the button is hidden behind UI.
<p  align="center"> <img src="https://user-images.githubusercontent.com/36170228/91071899-5c663700-e656-11ea-81dd-4760626dbaf4.jpg" width="200" height="400" /> </p>

**Comment by Rodze** [comment] 2020-08-24 22:08
Yep bug still present and the desktop site workaround doesn't work either for me on Galaxy S10

**Comment by michaelof** [comment] 2020-10-18 23:13
Bug still present in 80.1.2, but:

Maybe an intermediate workaround, as I have this painful issue every time my German Fritzbox router renews it's letsencrypt keys:

The issue DOES NOT happen when device is in landscape mode.

At least on my Nokia 7.2, Android 10

**Comment by lindhe** [comment] 2020-11-25 14:10
I had this issue recently. For me, it worked i Private tab but not regular tabs. Restarting did not help, but reinstalling helped.

**Comment by sflorean** [comment] 2021-05-25 13:06
This is still reproducible on Nightly 5/25 with Pixel 3 (Android 11).

**Comment by Taubin** [comment] 2021-07-03 04:14
Still happening on 89.1.1 

I am unable to connect to local home sites due to this on my phone. Galaxy S10. 

Switching to desktop does not work either.

**Comment by SoftVision-LorandJanos** [comment] 2022-01-04 11:05
This issue is no longer reproducible on the latest Nightly (2022-01-04).
Device used: Oppo Reno 6 (Android 11).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-01-04 11:05 UTC
Labels: 🐞 bug, Feature:Toolbar, wontfix, qa-triaged
