### ISSUE TITLE
FNX-83 ⁃ Allow users to add website exceptions for advanced settings

### ISSUE THREAD

**Issue by sebast889** [mozilla-mobile/fenix#2189] opened 2019-05-01 07:17 UTC
### Why/User Benefit/User Problem
Allow users to add website exceptions for advanced settings (seen in #188) for example Javascript website exceptions to allow/block Javascript on specific websites rather than just a simple toggle on and off.

### What/Requirements
Allow users to add website exceptions for each advanced setting to allow/block exceptions for certain websites rather than just a simple toggle on and off.

### Acceptance Criteria (how do I know when I’m done?)
Allow users to add website exceptions for each advanced setting to allow/block exceptions for certain websites rather than just a simple toggle on and off.

**Comment by cadeyrn** [comment] 2019-05-01 07:29
JavaScript is an important part of the web platform. You can already disable JavaScript in Fenix via about:config. Neither Firefox for Desktop nor Firefox for Android have a visible setting for disabling JavaScript. Firefox Focus has one but Firefox Focus is a very special browser. I vote against doing this in Fenix because disabling JavaScript causes a lot of problems and if someone really wants to do this doing this then about:config should be enough. Exposing this in the visible options causes that people who don't know what they're doing will disable it and then wonder why websites no longer work. Disabling JavaScript is an advanced setting and about:config is for advanced settings.

**Comment by sebast889** [comment] 2019-05-01 07:34
@cadeyrn

Disabling Javascript is already an advanced setting, see #188. It is already a feature in other main mobile browsers so it doesn't make sense why it shouldn't be in Firefox. 

You also posted after my edit to make website exceptions more general to all advanced settings, check again top post.

**Comment by cadeyrn** [comment] 2019-05-01 08:57
> Disabling Javascript is already a proposed advanced setting

I know the early mockups. In the meantime a lot changed, this setting is no longer part of Fenix MVP. So it's no clear at all if it will be implemented in the future or not. And because of that arguments should be collected why it should be implemented or why it should not be implemented. There are reasons for it and reasons against it. ;-)

> It is already a feature in other main mobile browsers so it doesn't make sense why it shouldn't be in Firefox.

I am sure there are arguments to implement your request. But it's definitively wrong to say it wouldn't make sense *not* to do this. I already explained why I think it's a bad idea and that's a valid argument, which *makes* sense. As a full-time web developer I know the troubles caused by disabled JavaScript. And as the operator of the biggest Firefox support forum in the German/Austria/Swiss region I know that people make use of settings every day without knowing the risks and then wonder why websites are broken. That's the reality. Disabling JavaScript is a very "dangerous" setting and while I agree it's good to have an option to disable it's also good that this option is hidden.

As explained you can already disable JavaScript in all Firefox products including Fenix via about:config. So there is a way to do this without offering this "feature" in a prominent way.

And as I already said: Neither Firefox for Desktop nor Firefox for Android have a visible option for this. But there was a visible setting in Firefox for Desktop in the past and it was deliberately removed (!). So maybe the Fenix team should first talk with the Desktop team about the pros and cons.

**Comment by sebast889** [comment] 2019-05-01 09:45
All major mobile browsers, Chrome, Safari, Samsung etc. have an advanced setting to disable Javascript in their settings. For Fenix to "hide" this in about:config (that would require obscure searching online to even find out about) is what I meant doesn't make sense and would be a disservice to Fenix users that somehow should be protected from a setting to disable Javascript. Having an advanced setting like what was proposed in the mockups is the right approach in my opinion and would allow easy to add website exceptions for advanced settings in the UI like what the request here is for.

Either way, I'd like to hear from the devs on what from the mockups in #188 will be implemented in the first main release of Fenix.

**Comment by cadeyrn** [comment] 2019-05-01 16:56
> For Fenix to "hide" this in about:config (that would require obscure searching online to even find out about) is what I meant doesn't make sense

Please respect other opinions. I already explained you two times why it makes sense. It doesn't mean that there is no argument for implementing your suggestion, but don't say it doesn't make sense because that's wrong.

>  I'd like to hear from the devs on what from the mockups in #188 will be implemented in the first main release of Fenix.

Just have a look at the current settings. Settings which are out of scope for the MVP were already removed.

**Comment by sebast889** [comment] 2019-05-01 17:26
I already know everything you have mentioned, no need to explain anything to me.  Keeping it hidden in about:config is a worse option than showing it as an advanced setting in my opinion. I don't see any reason to keep discussing this over and over. It's better to wait for Fenix devs' reply. 

Also when I said first main release of Fenix I didn't mean MVP I meant the release when Fenix actually replaces Fennec. My English is not the best so don't get hung up on the exact words I use, look at the overall request.

**Comment by NotWoods** [comment] 2019-12-23 07:17
We currently let you specify exceptions for site permissions and tracking protection so I'm going to close this issue.

**Closed** 2020-08-11 14:13 UTC
Labels: feature request 🌟

**Comment by theSdev** [comment] 2020-08-25 10:26
> 
> 
> We currently let you specify exceptions for site permissions and tracking protection so I'm going to close this issue.

@NotWoods I see the exceptions page but it only lists the websites I have made an exception for beforehand, there is no way to _add_ new sites to the list as the issue title suggests, I think this should be reopened.
