### ISSUE TITLE
[Bug] A white flash will appear when accessing google.com using Dark Reader add-on

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#11884] opened 2020-06-24 11:40 UTC
## Steps to reproduce
1. Download Dark Reader add-on;
1. Go to any website;
1. Go to https://www.google.com/
    1. Expected behavior
The page should load in dark mode without issues.
    1. Actual behavior
A white flash will appear before the page is loaded.
    1. Device information

* Android device: OnePlus 6T (Android 9)
* Fenix version: Firefox Preview Nightly 200624 (Build #21760611)
![dark](https://user-images.githubusercontent.com/50983519/85549431-a74cd980-b628-11ea-9747-eafd16042456.gif)UNITO-UNDERSCORE!reader!

**Comment by B0pol** [comment] 2020-06-24 13:07
Duplicate of https://github.com/mozilla-mobile/fenix/issues/6313, it doesn't happen only for google but every pages

**Comment by Gusted** [comment] 2020-06-24 13:19
I think better approach thats not just Google but to another origin and that seems like #6313 is already tracking that issue

**Comment by abodea** [comment] 2020-12-21 09:29
Verified as fixed on the latest **Nightly 21/12** with **Google Pixel 4 XL (11), Samsung Galaxy S10+ (10).**

**Closed by abodea** 2020-12-21 09:29 UTC
Labels: eng:qa:needed, 🐞 bug
