### ISSUE TITLE
[Android] Add print as pdf option in firefox or atleast make print as pdf extension add-on

### ISSUE THREAD

**Issue by Sujan319** [mozilla-mobile/fenix#18937] opened 2021-04-11 07:46 UTC
### What is the user problem or growth opportunity you want to see solved?
--> Many times while web surfing, some valuable information we need to print webpages as pdf. In firefox mobile, this option does not exist. Sometimes there is admit card or challan in web page and below that there is print option but that doesn't work for firefox mobile.

### How do you know that this problem exists today? Why is this important?
--> Firefox mobile doesn't have this feature coz its interface doesn't contain print/ print as pdf option. Also many webpages contain print option does not work for firefox mobile.
Many people, here & there, are complaining about this. So, this is feature request for most of the mobile firefox user.

### Who will benefit from it?
--> everyone will be benefited from these if implemented as a print as pdf option or as a print as pdf add-on.

**Comment by anotherus3r** [comment] 2021-04-11 09:47
Duplicate of #10217.

**Closed** 2021-04-12 00:38 UTC
Labels: needs:triage
