### ISSUE TITLE
Move Tabs button to the left

### ISSUE THREAD

**Issue by regs01** [mozilla-mobile/fenix#22280] opened 2021-11-03 12:14 UTC
It's very difficult to use Firefox left handed. There is no pull to open tab tray swipe and Tabs button is located on the opposite side of the screen in unreachable place. Can it be at least moved to the left in place of home button?

**Comment by cadeyrn** [comment] 2021-11-03 12:26
The solution to the problem that it's difficult to use for left handed users can't be to make it difficult to use for right handed users. 🤔

A real solution would be an optional left handed mode. That's #6365.

**Comment by regs01** [comment] 2021-11-03 12:34
A real solution would be agnostic design, like Chrome, Edge and many other browsers have. I.e. - swipe to open tab tray.

But there seem to be no plans for this in coming several years, so moving one button shouldn't be a difficult task. Menu button can stay on the right. It's not being used every minute.

**Comment by cadeyrn** [comment] 2021-11-03 12:37
> so moving one button shouldn't be a difficult task.

Of course it's not difficult. That was not my point at all. Again: It's not a solution just to move the problem to other users.

**Comment by kbrosnan** [comment] 2021-11-03 20:59
Closing as a duplicate of #6365

**Closed by kbrosnan** 2021-11-03 20:59 UTC
Labels: needs:triage
