### ISSUE TITLE
[Bug]The "Sign in" button does not work for www.pcgamesupply.com

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#7312] opened 2019-12-20 16:25 UTC
## Steps to reproduce
1. Open Firefox Preview browser and go to "www.pcgamesupply.com".
2. Tap on the "Sign in" button from the top right corner.
### Expected behavior
A "Sign In" dialog box is displayed alongside with "Register" button, email field, password field and personal information manipulation agreement.
### Actual behavior
There is no "Sign In" dialog box present, the user cannot log into the site.
### Device information

* Android device: OnePlus 6T/A6013 (Android 9), Samsung Galaxy S10 Plus (Android 9), Samsun Galaxy S8+ (Android 8.0.0)
* Fenix version: Firefox Preview Nightly 191220 (Build #13540608) and GeckoView 73.0a1 - 20191216095052

Note:
- This issue does not reproduce with the ESR versions Firefox Release 68.3.0 and Firefox Beta 68.4b2.
- Please see issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1384860

**Comment by darkwing** [comment] 2019-12-20 19:21
I'm seeing this on my Pixel 4 on current master (a50d8552ac3b7c7c4feb07068f805e9c9ef98429):

![Login](https://user-images.githubusercontent.com/46655/71285744-8f1f9900-232b-11ea-84f5-e0daa2ef3cc4.png)

**Comment by Diana-Rus** [comment] 2019-12-23 08:31
Hi, I will attach a [video](https://drive.google.com/file/d/19NwhYg677YqtQWQh2fkLGRvlpsndpT-n/view?usp=sharing) with the outcome.

**Comment by boek** [comment] 2019-12-27 19:20
@Diana-Rus Looks like the page breaks when you have enhanced tracking protection enabled. Disabling fixes the button

**Comment by liuche** [comment] 2020-02-11 18:25
Going to close this as dupe of #6528

**Closed by liuche** 2020-02-11 18:25 UTC
Labels: Feature:TrackingProtection, b:web-content, b:webcompat, 🐞 bug
