### ISSUE TITLE
[Bug] Address bar behaves oddly and prevents navigation in some cases

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#17381] opened 2021-01-09 19:45 UTC
The following bug happens to me for some days on the nightly builds.
It is difficult to me to find a pattern, but I have been able to capture a recording.

The problem is that in some unclear circonstances (quite often actually), the address bar won't react anymore to any URL typed in, or pasted... Fenix won't simply not go the wanted page.

As you can see on the screen recording, the address bar is filled in when it is at the bottom on the screen. Then, when you click on it, the keyboard shows up but the address bar is now empty. Pasting the URL does not work either.

https://photos.app.goo.gl/Rd9VNm6xPzFTvgAF8

On Redmi Note 7
Android 9

**Comment by sflorean** [comment] 2021-05-28 18:37
I think I encounter this but I can't find the steps with a Pixel 3 (Android 11), also I couldn't reproduce the one posted here. @klint this is still reproducible for you?

**Comment by SoftVision-LorandJanos** [comment] 2021-11-26 09:34
I couldn't reproduce this issue on the latest builds:
- latest Nightly (2021-11-26).
- latest Beta (95.0.0beta5).
- latest Release (94.1.2).

Device used: Xiaomi Mi11 Lite (Android 11).

Closing the ticket as fixed.

@klint if this is still reproducible with the latest builds on your end, please see if you can find some steps to reproduce it, maybe see if you can discover if it might be affected by anything else, even trying on a clean build. Thank you!

**Closed by SoftVision-LorandJanos** 2021-11-26 09:34 UTC
Labels: 🐞 bug, Feature:Toolbar, wontfix, qa-triaged
