### ISSUE TITLE
[Bug]Pages are zoomed after switching from landscape to portrait 

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#17856] opened 2021-02-05 14:24 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Sign in with a Fx account.
2. Open some Pocket recommendations (or Wikipedia). 
3. Switch the device to landscape and portrait. 

### Expected behavior
The page is displayed with no issues. 

### Actual behavior
The page is zoomed.

### Device information
* Device vendor / model and Android version: LG G7 (Android 8.1.0)
* Firefox for Android version: RC 85.1.2

### Notes
- Not reproducible on: Pixel 2 (Android 9), Samsung Galaxy Tab A6 (Android 5.1.1), Huawei MediaPad M3 (Android 7.0).
- Not reproducible on Beta, Nightly builds.
- Not reproducible if the the user is not signed in.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/58466444/107045804-9ffcc980-67ce-11eb-9799-d3177341d3d9.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9630)

**Comment by Mugurell** [comment] 2021-02-05 15:02
@sflorean 
are this steps of the essence?
> Sign in with a Fx account.
 Open some Pocket recommendations.
 
 or this reproduces on all websites nonetheless?

**Comment by Mugurell** [comment] 2021-02-05 15:04
This would seem like a GV issue but if it does not reproduce on Nightly and Beta it's hard to even know where to start investigating.

**Comment by sflorean** [comment] 2021-02-05 15:14
@Mugurell I can't reproduce the issue if I'm not signed in with a Firefox account, and this is also reproducible on Wikipedia, but not on cnn homepage; mandatory will be that the pages to have a lot of content. I will update the description.

**Comment by AndiAJ** [comment] 2021-02-09 12:40
@Mugurell Similar from a while ago [#2527](https://github.com/mozilla-mobile/fenix/issues/2527)

**Comment by SoftVision-LorandJanos** [comment] 2021-04-27 14:46
This issue is reproducible on latest Beta (89.0.0-beta.2) with HTC Nexus 9 (Android 7.1.1).

**Comment by Mugurell** [comment] 2021-04-27 16:06
Thank you all!
I cannot reproduce but seeing that this might be device specific I want to ask if you could test the exact same scenario on any of the affected devices while in GVE- https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.latest/arm64-v8a.

**Comment by SoftVision-LorandJanos** [comment] 2021-11-01 14:00
This issue is not reproducible on the latest Nightly (2021-11-01T05:11:04.075119).

Device used:
- HTC Nexus 9 (Android 7.1.1).
- Samsung Galaxy Tab S3 (Android 9).
- Xiaomi Mi11 (Android 11).

Closing the ticket as fixed.

**Comment by AndiAJ** [comment] 2021-12-02 10:16
Still reproducible on Firefox 95.1.0

**Comment by AndiAJ** [comment] 2022-01-13 03:56
Still reproducible on both the latest Nightly and Firefox 97.0.0 Beta 1 after performing a couple of rotations on Wikipedia's home page

**Closed** 2022-12-03 07:40 UTC
Labels: 🐞 bug, S2, Feature:Browsing, wontfix
