### ISSUE TITLE
[Bug] Show tabs list opened from a collection

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3308] opened 2019-06-10 12:50 UTC
## Steps to reproduce
1. Create a long list of collections.
1. Scroll down until the open tabs are no longer visible.
1. Tap the 3 dots menu of a collection, select Open tabs
    1. Expected behavior
Would be nice that the homescreen scrolls up to show the opened tabs.
    1. Actual behavior
Doesn't scroll up.
    1. Device information

* Android device: HTC 10 (android 8), Nexus 5 (Android 6)
* Fenix version: 6/8

**Comment by AmyYLee** [comment] 2019-06-10 18:16
This is a dupe of https://github.com/mozilla-mobile/fenix/issues/3168

**Closed** 2020-08-26 23:13 UTC
Labels: 🐞 bug
