### ISSUE TITLE
[Bug] If you have a ton of bookmarks - bookmarks crashes or times out when loading

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#4535] opened 2019-08-05 15:59 UTC
## Steps to reproduce
Have a ton of Bookmarks (I synced) and open Bookmarks in Fenix

### Expected behavior
Bookmarks loads in chunks, doesn't freeze

### Actual behavior
Fenix freezes and sometimes crashes

### Device information

* Android device: ?
* Fenix version: ?

breakout from #4137

**Comment by ekager** [comment] 2019-08-05 16:02
Do you have an estimate of how many bookmarks you have in the root folder after syncing @kbrosnan ?

**Comment by kbrosnan** [comment] 2019-08-05 16:07
This is filed based on https://github.com/mozilla-mobile/fenix/issues/4137#issuecomment-515425288 and https://github.com/mozilla-mobile/fenix/issues/4137#issuecomment-518036708

@softvision-miralobontiu are you able to answer @ekager question?

**Comment by colintheshots** [comment] 2019-08-05 16:57
This is a duplicate of #4513, even though it was just broken out.

**Closed by colintheshots** 2019-08-05 16:57 UTC
Labels: 🐞 bug
