### ISSUE TITLE
[Bug] Deleting opened tabs, exits Settings-Delete browsing data and returns to homescreen

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4807] opened 2019-08-19 12:49 UTC
## Steps to reproduce
1. Make sure to have at least 1 tab opened.
2. Go to Settings - Delete browsing data - select Open tabs and delete.

### Expected behavior
The user should remain in Settings - Delete browsing data page, exactly like it does when deleting "Browsing history" and "Collections". Maybe it is a consequence of #4376.

### Actual behavior
The user is redirected to the homescreen.

### Device information
* Android device: Huawei P9 Lite (Android 6), Xiaomi Mi 8 Lite (Android 9)
* Fenix version: RC 1.3.0-rc.3

**Comment by mikeGolf08** [comment] 2019-08-19 19:37
#4788 & #4642

**Comment by colintheshots** [comment] 2019-08-19 22:31
I had UX sign off for this behavior in the case of deleted tabs. This is expected behavior. The problem is that the user could've left a deleted tab in the back stack that is invalid and the navigation library doesn't allow removing tabs from the back stack.

**Comment by softvision-miralobontiu** [comment] 2019-08-20 07:06
@colintheshots just to be clear: when deleting "Browsing history" and "Collections" the user remains in the Settings-Delete browsing data page, but when deleting Open tabs, the user is redirected to the home screen?
Thank you!

**Comment by topotropic** [comment] 2020-02-12 13:33
@AmyYLee I think you worked on it, could you have a look and see if it's expected behavior? Thanks!

**Comment by AmyYLee** [comment] 2020-02-12 21:04
@softvision-miralobontiu @colintheshots 

To be clear, deleting any listed items will take the user back to the Settings main screen.

**Comment by mcarare** [comment] 2020-02-17 15:18
This should be fixed now. Please retest. TY!

**Comment by abodea** [comment] 2020-02-19 10:31
Verified as fixed on the latest **Beta build 4.0.0-beta.1** with **Google Pixel 3a XL (Android 10).**
Note that now the redirect is correctly made to the Settings main screen after deleting any listed items.

**Closed by abodea** 2020-02-19 10:31 UTC
Labels: Feature:Settings, P3, S2, b:navigation, eng:qa:needed, eng:ready, 🐞 bug
