### ISSUE TITLE
Significant WebGL performance regression compared to Fennec

### ISSUE THREAD

**Issue by brianpeiris** [mozilla-mobile/fenix#14827] opened 2020-09-07 15:54 UTC
## Steps to reproduce

Visit any of the WebGL example links below and take note of the average FPS once the example has loaded.

https://threejs.org/examples/webgl_geometries.html
https://threejs.org/examples/webgl_animation_cloth.html
https://webglsamples.org/aquarium/aquarium.html

### Expected behavior

WebGL performance should be on par with Fennec and Chrome on Android. 

### Actual behavior

WebGL performance is significantly worse in Fenix. FPS in those examples is 2 to 6 times slower compared to Chrome. I see a similar disparity if I compare to a Fennec APK obtained from https://ftp.mozilla.org/pub/mobile/nightly/latest-mozilla-esr68-android-aarch64/fennec-68.5a1.multi.android-aarch64.apk

Here is a capture from the firefox profiler, set to "firefox platform" mode: https://share.firefox.dev/35ftcMz

### Device information

I've repro'd this on a Samsung S8, and also got confirmation from another user with a Pixel 4

* Android device: Samsung Galaxy S8, Android 9
* Fenix version: 80.0.1

**Comment by yoasif** [comment] 2020-09-07 17:26
Maybe https://bugzilla.mozilla.org/show_bug.cgi?id=1654459 ?

**Comment by MarcLeclair** [comment] 2020-09-09 17:10
Triage: We're going to wait until the bug   https://bugzilla.mozilla.org/show_bug.cgi?id=1654459 is fixed and see if that resolves the problem.

**Comment by mcomella** [comment] 2020-09-30 21:40
@brianpeiris We believe this about to land – can you retest this issue on Friday or later with the latest Nightly build?

**Comment by brianpeiris** [comment] 2020-10-01 16:20
Yup, I'll be ready to test.

**Comment by scanline** [comment] 2020-10-03 16:48
@mcomella Sorry for 'gatecrashing' this thread. Since the move from fennic to fenix literally any Android I came across had very poor WebGL performance (way below 10fps everytime, no matter how simple the content) - so I'd love to test this too. Is this Nightly build the same as the one distributed via the Play Store?

**Comment by brianpeiris** [comment] 2020-10-03 17:25
I can confirm that the performance issue appears to be fixed in the latest nightly from the play store (Nightly 83, 201002). Tested on my Samsung Galaxy S8, Android 9.

**Comment by mcomella** [comment] 2020-10-05 23:21
> Is this Nightly build the same as the one distributed via the Play Store?

@scanline Yes, if you download Firefox nightly from the play store, you should be able to test the fix.

Since it appears that the issue is resolved I'm going to close this issue – please reopen if you disagree.

**Closed by mcomella** 2020-10-05 23:21 UTC
Labels: eng:performance, needs:triage
