### ISSUE TITLE
[webcontent] FF fullscreen scaling is buggy on devices with gesture navigation and hidden nav bar/nav pill

### ISSUE THREAD

**Issue by eddie-LA** [mozilla-mobile/fenix#14480] opened 2020-08-30 08:53 UTC
## Site with issue and any steps to reproduce
Potentially any site, have encountered it in a lot of places that include pictures and scrolling. How to reproduce:
1. Go to any site that hosts pictures too. Example given is Facebook mobile.
2. Open any picture. The moment the display is touched, a ghost image of the nav bar shows, when it should not be shown in a phone with fullscreen gestures. Ever. 

Scrolling down in some sites (like volafile) generates the ghost nav bar, like so. (also, don't judge my memes) 
![Screenshot_20200831-153008](https://user-images.githubusercontent.com/28909420/91720035-0dad2580-eb9f-11ea-8add-59b7d85dbb04.png)

Also, opening a picture there does the opposite instead, hiding the buttons below the screen until display is touched.

### Expected behavior
After opening the picture and before touching the display - this is the behaviour. It looks correct, however... 
![Screenshot_20200830-111815](https://user-images.githubusercontent.com/28909420/91654599-cfd2d300-eab2-11ea-8468-4e7f968abe5f.png)

Upon touching the display in the place where the <</>> buttons are supposed to be in volafile.org:
![Screenshot_20200831-152613](https://user-images.githubusercontent.com/28909420/91720073-21f12280-eb9f-11ea-8d76-70c410062e2f.png)

### Actual behavior
The moment one touches the display... Notice the white bar at the bottom, that is where the Android nav bar is supposed to be.. It shouldn't be shown in fullscreen mode (gesture nav with hidden nav bar/nav pill for full screen gesture nav). 
![Screenshot_20200830-111821](https://user-images.githubusercontent.com/28909420/91654612-fc86ea80-eab2-11ea-8806-abf30f90bdc1.png)

This is shown instead when first opening an image in volafile. Notice the buttons aren't where they are supposed to be:
![Screenshot_20200831-152602](https://user-images.githubusercontent.com/28909420/91720097-2e757b00-eb9f-11ea-8fe9-cdc159ad244b.png)

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No. 

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes, that is where it happens, along with Beta. 

### Can you reproduce in Chrome (or other non-Mozilla browser)?

Chrome-based browsers do NOT exhibit this behaviour. 

### Device information

* Android device: Poco F1, Android 10
* Fenix version:  79 Release and 80 Beta

**Comment by eddie-LA** [comment] 2020-09-05 18:14
LinkedIn and other popular sites also exhibit the same behaviour, having blank space appear below during scroll operations and some other interactions.

**Comment by s-ankur** [comment] 2020-10-21 15:05
Are you still seeing this in Nightly? Its supposed to be fixed by  #8768 and #11389 but i am still seeing it on certain websites. If so then it is probably duplicate of https://github.com/mozilla-mobile/fenix/issues/14660

**Comment by abodea** [comment] 2020-12-22 14:56
Verified as fixed on the latest Nightly 22/12 with Google Pixel 4 XL (11), Samsung Galaxy S10+ (10).
Note that pictures were displayed correctly in full screen.

**Closed by abodea** 2020-12-22 14:56 UTC
Labels: eng:qa:needed
