### ISSUE TITLE
[Bug] Too little force is required to push tab tray down.

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#14204] opened 2020-08-26 06:55 UTC
## Steps to reproduce
1. Open 3 tabs
2. Switch to middle tab
3. Open tab tray
4. Try to quickly scroll down to get to the first tab

### Expected behavior
Tab tray would be hidden when pushed down more than it is now.

### Actual behavior
Tab tray is hidden as soon as it is pushed down by even a miniscule amount

### Device information

* Android device: ?
* Fenix version: Nightly 200825

**Comment by liuche** [comment] 2020-10-15 00:03
Dupe of #15543

**Closed by liuche** 2020-10-15 00:03 UTC
Labels: needs:triage, 🐞 bug

**Comment by Poopooracoocoo** [comment] 2020-10-15 04:59
@liuche 
i think the term _superseded_ in cases like this is better.

**Comment by Mugurell** [comment] 2020-10-30 16:29
Following the original STRs:
> 1. Open 3 tabs
> 4. Try to quickly scroll down to get to the first tab

With just 3 tabs opened scrolling in the list of tabs is not possible because they all fit inside tabs tray.
So any swipe gesture will get passed to the tabs tray, not to the inside list of tabs.

Based on this steps I don't see this as an issue. Tabs Tray works as intended.
