### ISSUE TITLE
[Bug]: Copy text

### ISSUE THREAD

**Issue by AdmiralCarthOnasi** [mozilla-mobile/fenix#20948] opened 2021-08-20 18:25 UTC
### Steps to reproduce

Go to on Firefox in Android 9:

https://www.i-dont-care-about-cookies.eu/abp/

Choose Select all, than Copy. Firefox crases.

### Expected behaviour

Copy text

### Actual behaviour

Crash.

### Device name

BV9500 Plzs

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

91.2.0

**Comment by marcel263** [comment] 2021-08-21 19:17
upon opening a new tab, presumably search from clipboard feature teiggering an issue, Nightly 20-08 crashes with a android.os.deadsystemexception. Reproducable with any text, e.g. 999 paragraphs of placeholder 'lorem ipsum'

**Comment by makotokato** [comment] 2021-08-23 17:52
Gecko side issue. GV should handle the exception due to too large binder data.

```
08-24 02:48:41.403  1035  1040 E statsd  : Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->1002[I] (10)0x30000->*alarm*[S] 
08-24 02:48:41.848  8180  8180 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1414176)
08-24 02:48:41.848  8180  8180 D AndroidRuntime: Shutting down VM
08-24 02:48:41.851  8180  8180 E AndroidRuntime: FATAL EXCEPTION: main
08-24 02:48:41.851  8180  8180 E AndroidRuntime: Process: org.mozilla.fenix, PID: 8180
08-24 02:48:41.851  8180  8180 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1414176 bytes
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at android.app.ApplicationPackageManager.queryIntentActivityOptions(ApplicationPackageManager.java:1253)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.addIntentOptions(MenuBuilder.java:494)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at org.mozilla.geckoview.BasicSelectionActionDelegate.onPrepareActionMode(BasicSelectionActionDelegate.java:11)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at org.mozilla.geckoview.BasicSelectionActionDelegate$Callback2Wrapper.onPrepareActionMode(BasicSelectionActionDelegate.java:1)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onPrepareActionMode(DecorView.java:2656)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode.invalidate(FloatingActionMode.java:144)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at com.android.internal.policy.DecorView.setHandledFloatingActionMode(DecorView.java:1996)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at com.android.internal.policy.DecorView.setHandledActionMode(DecorView.java:1836)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at com.android.internal.policy.DecorView.startActionMode(DecorView.java:914)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at com.android.internal.policy.DecorView.startActionMode(DecorView.java:879)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at android.app.Activity.startActionMode(Activity.java:7603)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at org.mozilla.geckoview.BasicSelectionActionDelegate.onShowActionRequest(BasicSelectionActionDelegate.java:9)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession$9.handleMessage(GeckoSession.java:6)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession$9.handleMessage(GeckoSession.java:1)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:2)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:1)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 1414176 bytes
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:550)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at android.content.pm.IPackageManager$Stub$Proxy.queryIntentActivityOptions(IPackageManager.java:5422)
08-24 02:48:41.851  8180  8180 E AndroidRuntime: 	at android.app.ApplicationPackageManager.queryIntentActivityOptions(ApplicationPackageManager.java:1240)
```

**Comment by makotokato** [comment] 2021-08-23 17:52
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1727151

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by amedyne** [comment] 2021-08-23 20:50
Closing this to track the bugzilla issue.

**Closed by amedyne** 2021-08-23 20:50 UTC
Labels: 🐞 bug, needs:triage
