### ISSUE TITLE
[Bug] can't download file

### ISSUE THREAD

**Issue by Ryukenden345** [mozilla-mobile/fenix#14235] opened 2020-08-26 17:25 UTC
![Screenshot_20200826-183339](https://user-images.githubusercontent.com/2789232/91337171-e1725d00-e7ca-11ea-8f62-f0feb70fa867.png)
## Steps to reproduce
I can't download https://github.com/wikimedia/apps-android-wikipedia/releases/download/latest/app-alpha-universal-release.apk
### Expected behavior
Firefox should download the file
### Actual behavior
The download fails
### Device information

* Android device: Umidigi A5 Pro - Android 9
* Fenix version: Firefox Nightly for Android 200825 06:07 (Build #2015759987)

**Comment by Dunexus** [comment] 2020-08-26 20:32
Duplicate of https://github.com/mozilla-mobile/fenix/issues/14052.
This has been resolved, please update to latest nightly.

**Comment by kbrosnan** [comment] 2020-08-26 20:53
closing as dupe

**Closed by kbrosnan** 2020-08-26 20:53 UTC
Labels: needs:triage, 🐞 bug
