### ISSUE TITLE
Samsung Internet like Selection

### ISSUE THREAD

**Issue by black7375** [mozilla-mobile/fenix#15850] opened 2020-10-12 17:02 UTC
More: #15397

### What is the user problem or growth opportunity you want to see solved?
- Zoom in on the area you are changing to make sure you select even small letters precisely.
- There is a natural animation by increasing the size of the cursor used during selection.
![SamsungInternet-Selection](https://user-images.githubusercontent.com/25581533/95771828-431f5580-0cab-11eb-941a-43554587ce4d.gif)

### How do you know that this problem exists today? Why is this important?
  - Don't have zooming area
![Fenix-4_Select_During](https://user-images.githubusercontent.com/25581533/94171708-1b458a80-fe81-11ea-9fbd-3e63576a1774.jpg)

### Who will benefit from it?
- Those who want to select precisely
- Those who need to select small letters
- a person with low vision

**Comment by kbrosnan** [comment] 2020-10-12 18:56
Duplicate of #3510

**Closed by kbrosnan** 2020-10-12 18:56 UTC
Labels: needs:triage
