### ISSUE TITLE
Cannot login to sync

### ISSUE THREAD

**Issue by Dcross21** [mozilla-mobile/fenix#17995] opened 2021-02-14 21:21 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Device information

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)
 
Hi can't login to sync my accounts after changing password says it's invalid what gives thanks D.Cross

**Comment by amedyne** [comment] 2021-02-16 14:15
@Dcross21 Can you provide the following info: 
    - Device vendor / model and Android version: ?
    - Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by lobontiumira** [comment] 2021-03-31 08:32
I will close this issue since I was not able to reproduce it.
Also, the reporter has not provided more details.

**Closed by lobontiumira** 2021-03-31 08:32 UTC
Labels: Feature:Sync, needs:sumo, needs:triage, 🐞 bug
