### ISSUE TITLE
FNX-4402 ⁃ [Bug] Can't open "Search by Image" addon settings

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#10591] opened 2020-05-12 11:12 UTC
## Steps to reproduce
1. Open search by image addon
1. Press the three dot menu
1. click on "Options"
    1. Expected behavior
It goes to search by image options
    1. Actual behavior
Nothing happens
    1. Device information

* Android device: 9
* Fenix version: 5.0, but also latest nightly (200512)

**Comment by dessant** [comment] 2020-05-21 12:20
The issue is also tracked for GeckoView: https://bugzilla.mozilla.org/show_bug.cgi?id=1619766

**Comment by dessant** [comment] 2020-07-12 08:12
This bug has been fixed in GeckoView 79, and it's already live in Firefox Nightly.

**Comment by B0pol** [comment] 2020-07-12 09:44
I can confirm it's working on Firefox  nightly

**Closed** 2020-08-11 01:07 UTC
Labels: Feature:WebExtensions, S2, needs:gv, 🐞 bug
