### ISSUE TITLE
[Bug] Notification of closing a tab hangs on after unlocking the device

### ISSUE THREAD

**Issue by crotopus** [mozilla-mobile/fenix#9092] opened 2020-03-11 02:57 UTC
## Steps to reproduce
1. Open a few tabs (2 or more)
2. Close one of them
3. Then immediately switch to one of previously opened tabs
4. Lock your device, the "tab has been closed" notification is still shown
5. Unlock your device
6. Tap to Undo button on the notification to dismiss it
### Expected behavior
The "tab has been closed" notification should disappear sometime after the device is unlocked.
### Actual behavior
The notification remains on the screen. Trying to undo does nothing
### Device information
OnePlus 5 and OnePlus 7T tested
* Android device: ?
* Fenix version: ?

**Comment by kbrosnan** [comment] 2020-03-11 04:22
Assuming that you are using 3.2.x. This is fixed in version 4.0. Closing as a dupe of #8472

**Closed by kbrosnan** 2020-03-11 04:22 UTC
Labels: needs:triage, 🐞 bug
