### ISSUE TITLE
[Bug] Scroll position not remembered on first tab opened

### ISSUE THREAD

**Issue by Vigonator** [mozilla-mobile/fenix#17111] opened 2020-12-18 07:23 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Open any long webpage and scroll down. Once scrolled down exit firefox and make it unload the tab either by closing the app or loading enough in different apps. Then, navigate back to the tab in firefox.

### Expected behavior

The tab should reload to the position I had scrolled to previously.

### Actual behavior

The tab reloads to the top of the webpage.
This can be circumvented by visiting a different page before reloading the tab, but that shouldnt be necessary.

### Device information

* Android device: Huawei p30 lite
* Fenix version: 84.1.1

**Comment by sflorean** [comment] 2021-07-31 09:15
I was not able to reproduce this issue on latest Nightly build with Pixel 3 (Android 12).
@Vigonator can you check and see if this is the case for you?

**Comment by sflorean** [comment] 2022-02-03 13:44
Closing this due to lack of extra information and given the fact that the issue is not reproducible on our side. Please comment/ open a new bug if the issue occurs again.

**Closed by sflorean** 2022-02-03 13:44 UTC
Labels: 🐞 bug, Feature:Gesture, wontfix, qa-triaged
