### ISSUE TITLE
[Search] PBM search bar gradient doesn't match when moved to top

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8491] opened 2020-02-18 18:01 UTC
Steps to reproduce:

1. Go to Settings -> Customize -> Select "Top"
2. Go to Private browsing homescreen 

Expected: 
Private browsing search bar background colour blends with private browsing homescreen background colour when set to top. 

Actual: 
Search bar has the background gradient to match private browsing homscreen if the search bar is set to bottom. 

![Screenshot_20200218-125629](https://user-images.githubusercontent.com/5992746/74763704-45c9c800-524e-11ea-9234-5305d1fd6e5e.png)

**Comment by ValentinTimisica** [comment] 2020-03-17 10:18
Hello @AmyYLee. I added a screenshot. Please tell me if this is ok.

![b-8491-toolbar-top](https://user-images.githubusercontent.com/52956363/76846123-aac20f00-6848-11ea-9adb-ce44e54d9222.png)

**Comment by AmyYLee** [comment] 2020-03-17 16:07
> Hello @AmyYLee. I added a screenshot. Please tell me if this is ok.
> 
> ![b-8491-toolbar-top](https://user-images.githubusercontent.com/52956363/76846123-aac20f00-6848-11ea-9adb-ce44e54d9222.png)

@ValentinTimisica Hi, I am still seeing the gradient background (faintly) in the search bar. It should blend with the gradient background of the full screen. Thanks

It should look like this
![search](https://user-images.githubusercontent.com/5992746/76876131-e0b2c380-6847-11ea-9a36-ed5857ddf3ef.png)

**Comment by ValentinTimisica** [comment] 2020-03-18 07:36
Hello @AmyYLee, I made some changes. How does it looks?

![b-8491-toolbar-top-new](https://user-images.githubusercontent.com/52956363/76936554-ca663f80-68fb-11ea-9949-140b0a2649bb.png)

**Comment by AmyYLee** [comment] 2020-03-18 17:22
> Hello @AmyYLee, I made some changes. How does it looks?
> 
> ![b-8491-toolbar-top-new](https://user-images.githubusercontent.com/52956363/76936554-ca663f80-68fb-11ea-9949-140b0a2649bb.png)

Hi @ValentinTimisica 

It still looks like there's 2 different shades of purple. Is it possible to make the search bar background transparent so the full screen background gradient is seamlessly blended behind the search bar?

**Comment by ValentinTimisica** [comment] 2020-03-18 18:06
I used a gradient (45 degree angle - starting from bottom left and ending in top right) with the colors from the image you posted above (I used a color picker to get the color from each corner of the searchBar, but maybe it's not that accurate). Can you give me the right color codes?

Regarding your question, yes, it is possible to make the search bar background transparent, but on scroll the private browsing icon will appear under the search bar (see video [here](https://drive.google.com/file/d/103BtYT_gaISItaTaZGeDxUATwfvljxz7/view?usp=sharing)). And I don't know if this will introduce any regressions. @ekager any thoughts on this?

**Comment by AmyYLee** [comment] 2020-03-18 20:44
@ValentinTimisica I think if the full background gradient ended prior to the search bar then we can have a solid colour there. If this is getting too complex then we can leave it as is.

**Comment by ValentinTimisica** [comment] 2020-03-19 08:39
@AmyYLee, if we are to use a solid color for the urlBar background I think the differences between this and the larger background which has a gradient would be even more obvious"
As such based on all of the above I think the solution demoed in my last screenshot is the best we can get. It looks good and there are no chances of regressions.

**Comment by AndiAJ** [comment] 2020-03-23 07:54
Hi, I've re-checked this matter on the latest **`Nightly Build #20830607 from 3/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

From my point of view the URL bar still doesn't match with the background gradient, on some devices it's quite obvious. 
Nevertheless, @AmyYLee - could you please review the bellow screenshots and share your thoughts? ☺️ 

<details>
    <summary>Screenshots (▼ dropdown ▼)</summary>


## ○ Google Pixel 3a
![rsz_screenshot_20200323-092402](https://user-images.githubusercontent.com/51314259/77292974-09283b00-6cea-11ea-8713-3222a487255b.png)

## ○ Huawei Mate 20 Lite
![rsz_screenshot_20200323-092504](https://user-images.githubusercontent.com/51314259/77293073-455b9b80-6cea-11ea-8b3d-479ab87745f9.jpg)

## ○ Samsung Galaxy S6
![rsz_1584948811267](https://user-images.githubusercontent.com/51314259/77293653-6d97ca00-6ceb-11ea-84ef-22e09c90abc6.jpg)

## ○ OnePlus A3
![rsz_screenshot_20200323-092430](https://user-images.githubusercontent.com/51314259/77293494-1db90300-6ceb-11ea-90fa-4fa67eb16bd2.png)


</details>

**I'll remove the QA needed label until further notice.**

**Comment by ValentinTimisica** [comment] 2020-03-23 08:30
@AmyYLee, note that for the toolbar background I used the solid color `#383372` from the [onboarding design page](https://app.abstract.com/share/e818c20f-6e49-4290-b7cd-a2c77adc9585?mode=build&selected=3923832091-935ABACB-9593-499B-95EF-ECFAC21F6601&sha=49a9ed6e7bfe7be97c2e47a45791f7008405af15).

**Comment by AmyYLee** [comment] 2020-03-23 15:50
@AndiAJ @ValentinTimisica - Hi, can we revert back to the original? Apologies, the original ask was that the search bar background blends in with the homescreen background. If we are unable to do this (or it requires a lot more work) then my preference is to revert back to the original. Having it "similar" feel like it is a mistake. Thank you for the time in trying this out.

**Comment by ValentinTimisica** [comment] 2020-03-24 13:16
Closing this because the patch has been reverted in #9359.

**Closed by ValentinTimisica** 2020-03-24 13:16 UTC
Labels: Feature:PrivateMode, Feature:Search, P2, implementation review, needs:triage
