### ISSUE TITLE
Very slow loading of bookmark list

### ISSUE THREAD

**Issue by Spinus1** [mozilla-mobile/fenix#4288] opened 2019-07-25 08:02 UTC
## Steps to reproduce
Connect to a Firefox Account with tons of bookmark
Wait the sync to be completed
Open My library and bookmark

### Expected behavior
Some bookmark are displayed as soon as you open the bookmark item

### Actual behavior
It takes about 5-10 second to get bookmark list on the screen
If you move back and forward to "bookmark subfolder" (like the folder that contains bookmark from Firefox desktop) the interface get very slow (probably it reloads bookmark each time)

### Device information
Huawei P9 lite
* Android device: 9
* Fenix version: 1.1.0 (build #12042112)

**Comment by NotWoods** [comment] 2019-07-28 13:50
Duplicate of #4137

**Closed by NotWoods** 2019-07-28 13:50 UTC
Labels: 🐞 bug
