### ISSUE TITLE
FNX-4602 ⁃ Download the files to micro SD (external memory).

### ISSUE THREAD

**Issue by marker10** [mozilla-mobile/fenix#10818] opened 2020-05-21 11:33 UTC
Hi, I would like to download the files to micro SD (external memory). On folder specified by the user (better) or the folder provided by the system for apps, in the Android - data folder.

**Comment by SS1113** [comment] 2020-05-21 12:51
Duplicate of #4417

**Comment by kglazko** [comment] 2020-06-01 22:39
Closing due to the fact it is a duplicate

**Closed** 2020-08-11 01:54 UTC
