### ISSUE TITLE
[Bug] Swipe down to refresh shouldn't be activated if there is swipe up action

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#18755] opened 2021-04-01 20:23 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Swipe up to scroll page a little bit then swipe down to go to the top of the page

### Expected behavior
Swipe down to refresh shouldn't be activated
### Actual behavior
It's activated

https://user-images.githubusercontent.com/17825767/113349648-0d495880-9341-11eb-94a7-89c400bd60ba.mp4

### Device information

* Device vendor / model and Android version: XZ1 Android 11
* Firefox for Android version: 1/4 nightly

**Comment by Mugurell** [comment] 2021-04-02 06:11
Thank you @hakkikaancaliskan !
This is a known issue.
Closing as a dupe of https://github.com/mozilla-mobile/fenix/issues/16577.

**Closed by Mugurell** 2021-04-02 06:11 UTC
Labels: needs:triage, 🐞 bug
