### ISSUE TITLE
FNX-14567 ⁃ Remember the last bookmark folder opened like Android Chrome

### ISSUE THREAD

**Issue by binocry** [mozilla-mobile/fenix#13387] opened 2020-08-07 08:37 UTC
### What is the user problem or growth opportunity you want to see solved?
Fenix needs to implement remember the last bookmark folder opened like Android Chrome
### How do you know that this problem exists today? Why is this important?
So that users don't always go back and forth to the folder bookmark toolbar just to open bookmarks, it becomes more efficient like the behavior in Chrome
### Who will benefit from it?
Ordinary users, especially those familiar with chrome

**Comment by anotherus3r** [comment] 2020-08-08 21:09
Duplicate of #9390?

**Closed** 2021-08-18 18:59 UTC
Labels: Feature:Bookmarks, wontfix
