### ISSUE TITLE
[Bug] downloads that require a user to be logged in to a website fail

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#7531] opened 2020-01-08 02:55 UTC
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1530022

## Steps to reproduce
* Login to Bugzilla
* Open a restricted eg [bug 1607647](https://bugzilla.mozilla.org/show_bug.cgi?id=1607647)
 * anyone who needs access to this just ask. This is a test bug that has no confidential information. Its sole purpose is to have an attachment behind a login.
* Download Success.html attachment

### Expected behavior

Success.html file is downloaded

### Actual behavior

Access denied Bugzilla page is saved.

### Device information

* Android device: Pixel 3
* Fenix version: Nightly

**Comment by lnicola** [comment] 2020-02-11 18:45
This happens because Fenix downloads the file twice. See #7961 for details.

**Comment by st3fan** [comment] 2020-03-27 16:36
@kbrosnan would you mind verifying this bug again? It sounds like #7961 fixed this?

**Comment by lnicola** [comment] 2020-03-27 16:39
Not working for me in Build #20870608.

**Comment by lnicola** [comment] 2020-03-27 16:40
@st3fan wait, how is #7961 supposed to have fixed this? It's a duplicate issue of it.

**Comment by st3fan** [comment] 2020-03-27 17:53
Oh I see, I thought #7961 was closed with a PR, but it is indeed a dupe of this one.

**Comment by kbrosnan** [comment] 2020-03-30 17:45
This still reproduces in Nightly and STR in comment 0.

**Comment by Amejia481** [comment] 2020-04-14 20:20
This is GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1626335, it looks like we are not sharing some headers and for this reason we are getting the access denied.

**Comment by liuche** [comment] 2020-06-25 22:01
Looks like a fix landed, but got backed out.

**Comment by lnicola** [comment] 2020-06-26 04:33
@Amejia481, @liuche I'm not sure, did you see https://github.com/mozilla-mobile/fenix/issues/7961#issue-556553954? Fenix makes two HTTP requests. The first one is fine, but the second one has weird headers, and not only cookies.

**Comment by Amejia481** [comment] 2020-06-29 15:37
> @Amejia481, @liuche I'm not sure, did you see [#7961 (comment)](https://github.com/mozilla-mobile/fenix/issues/7961#issue-556553954)? Fenix makes two HTTP requests. The first one is fine, but the second one has weird headers, and not only cookies.

Didn't have the opportunity of seeing it. It looks like https://github.com/mozilla-mobile/fenix/issues/7961 is a different issue, we could reopen to take a look at it.

A fix for this issue from GeckoView is very close to land https://bugzilla.mozilla.org/show_bug.cgi?id=1626335

**Comment by pocmo** [comment] 2020-07-13 10:23
GeckoView patch landed and latest AC Nightly should have that patch. So we should be able to verify it in the next Fenix Nightly.

**Comment by Amejia481** [comment] 2020-07-13 13:58
It's working on nightly Saturday 7/11 @ 6:08 AM

```
Nightly 200711 06:00 (Build #21930609)
AC: 50.0.20200710130140, b54541be1
GV: 80.0a1-20200709093347
AS: 61.0.7
```

**Comment by kbrosnan** [comment] 2020-07-14 00:31
@Amejia481 I still get the not logged in Bugzilla page testing in normal and private browsing. Seeing `success.html` is not enough to verify this you need to open the page an verify that you don't get the Access denied Bugzilla page.

**Comment by Amejia481** [comment] 2020-07-14 00:53
Unfortunately, you are right :(. I' getting the access denied Bugzilla page

**Comment by Amejia481** [comment] 2020-07-14 01:25
@kbrosnan are you able to download in other authenticated sites? when I initially tested I was able to download my payment statement from https://workforcenow.adp.com

**Comment by AndiAJ** [comment] 2020-07-14 07:12
Hi, I've just re-checked this on the latest **`Nightly Build 200714 from 7/14`** using a Google Pixel 3a (Android 10) and it seems that the Access denied Bugzilla page is actually saved.

► Video
![20200714-100417](https://user-images.githubusercontent.com/51314259/87395697-7540ee80-c5ba-11ea-9477-54e56b52889a.gif)

I'll remove the QA needed label until further notice

**Comment by st3fan** [comment] 2020-07-14 15:07
I think we need a better test plan for this than just Bugzilla. Different sites do different things. Some redirect to a different domain, others ask the user to tap on a link to a different domain. I think it would be really good to have a bit of a test matrix for this one to make sure we cover all cases. (And explore what those cases/variants are)

**Comment by lnicola** [comment] 2020-07-14 15:09
This might actually be #7961.

**Comment by st3fan** [comment] 2020-07-14 15:10
I see #7961 mentions a different user agent - that can definitely get in the way of authentication. Some sites hash client attributes like that to make sure the download happens from the same browser. And will reject it if it does not look like it is coming from the same.

**Comment by lnicola** [comment] 2020-07-14 15:13
@st3fan it's not just the user agent. The second request is missing the cookies.

**Comment by Amejia481** [comment] 2020-07-14 15:39
> I think we need a better test plan for this than just Bugzilla. Different sites do different things. Some redirect to a different domain, others ask the user to tap on a link to a different domain. I think it would be really good to have a bit of a test matrix for this one to make sure we cover all cases. (And explore what those cases/variants are)

I agree with @st3fan, different sites have different ways to allow to download authenticated content. 

Sorry for all the confusion, I think I understood what is happening here. I thought [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1626335) was the caused of not able to download any file from authenticated sites. But I was wrong, there were some authenticated sites that before [this patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1626335), we were able to download from, this was the case of https://workforcenow.adp.com.  It looks like when I tested I was using an old cached dependency of geckoview and there https://workforcenow.adp.com was working, now with [this patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1626335) I'm getting an HTTP 500 error and not able to download, when I omit the passing the headers I'm able to download from that site, unfortunately it looks like we are regressing with [the patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1626335).

**Comment by vesta0** [comment] 2020-07-14 17:23
This is super high priority - please let's figure out a way to fix this as soon as possible.

**Comment by Amejia481** [comment] 2020-07-14 20:21
> This is GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1626335, it looks like we are not sharing some headers and for this reason we are getting the access denied.

The initial bugs wasn't the cause for this issue I open https://bugzilla.mozilla.org/show_bug.cgi?id=1652856 for checking the for Bugzilla attachments, I think it will be useful to have a list of sites ordered by priority where files that require authentication are failing, this way we can tackle the sites with highest priority

**Comment by Amejia481** [comment] 2020-07-14 20:28
Maybe QA can help us with that

**Comment by AndiAJ** [comment] 2020-07-15 11:37
Hi @Amejia481 , please review my findings after re-checking this matter on **`79.0.0-beta.6 from 7/14`** using the following devices:
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

## Signed in

• Google Drive - apk download
✔️ Successfully downloaded and installed the apk
![20200715-122932](https://user-images.githubusercontent.com/51314259/87533730-b3fba500-c69d-11ea-8aad-dc481fe60b35.gif)

• Gmail - gif download
✔️ Successfully downloaded and opened the gif
![20200715-123459](https://user-images.githubusercontent.com/51314259/87534811-333da880-c69f-11ea-9bf4-6226eeae5e23.gif)

• Gmail -> WeTransfer link jpg, apk, pdf
✔️ Successfully downloaded
❓ Can't open the files from Fenix
✔️ Can open them from the file manager
![20200715-124433](https://user-images.githubusercontent.com/51314259/87535403-1a81c280-c6a0-11ea-9252-8166287ad88c.gif)

• Udemy - zip file
✔️ Successfully downloaded 
✔️ Can't open the files from Fenix
✔️ Can properly open them from the file manager
![20200715-123255](https://user-images.githubusercontent.com/51314259/87534059-34baa100-c69e-11ea-976e-97c77c6d5bbf.gif)

• Wizair - pdf file
✔️ Successfully downloaded and opened the pdf file
![20200715-123422](https://user-images.githubusercontent.com/51314259/87534537-d510c580-c69e-11ea-8352-f1b1a0f82a88.gif)

• Github - txt file
✔️ Successfully downloaded and opened the txt file
![20200715-123530](https://user-images.githubusercontent.com/51314259/87534952-6718ce00-c69f-11ea-80ec-33c0fe847f04.gif)

• Github link from #12297 - apk file
✔️ Successfully downloaded and opened the apk file
![20200715-134530](https://user-images.githubusercontent.com/51314259/87536463-d68fbd00-c6a1-11ea-874d-3d31a63b02b2.gif)

• Oracle - exe file
✔️ Successfully downloaded
✔️ Can't open the file (Win 10 exe file)
![20200715-131328](https://user-images.githubusercontent.com/51314259/87535929-ebb81c00-c6a0-11ea-974c-8a261a44162d.gif)


## Not signed in

•  Link from #11436 - pdf file
✔️ Successfully downloaded
❌ Can't open it from Fenix nor from the File manager
![20200715-125257](https://user-images.githubusercontent.com/51314259/87535552-5cab0400-c6a0-11ea-9e7a-7967934da871.gif)

•  Link from [#54064](https://github.com/webcompat/web-bugs/issues/54064) - zip file
❌ Download failed instantaneously
![20200715-125755](https://user-images.githubusercontent.com/51314259/87535739-a1369f80-c6a0-11ea-91b7-43c85d37e000.gif)

I'll remove the QA needed label until further notice.

**Comment by kglazko** [comment] 2020-07-15 16:08
Hi @vesta0 sounds like the action item here is: " I think it will be useful to have a list of sites ordered by priority where files that require authentication are failing, this way we can tackle the sites with highest priority". It seems like this is working on some sites and not others.

@Amejia481 What do you think about me setting up a spreadsheet to keep track of sites where downloads are reported to work/fail?

**Comment by Amejia481** [comment] 2020-07-15 16:16
That will be awesome ❤️

**Comment by avdv** [comment] 2020-07-15 18:08
One more data point: I encountered this problem when trying to download my books from manning.com, it would successfully transfer the file, but it would have the HTML page in it, not the PDF or .epub contents.

**Comment by st3fan** [comment] 2020-07-20 17:52
@kglazko great idea to setup a spreadsheet. I do want to make sure that we do not implement site-specific fixes. Instead we should understand how these websites present downloads to the browser at the HTTP level and properly deal with those cases. Or why our download request is rejected.

**Comment by Amejia481** [comment] 2020-07-20 18:01
> @kglazko great idea to setup a spreadsheet. I do want to make sure that we do not implement site-specific fixes. Instead we should understand how these websites present downloads to the browser at the HTTP level and properly deal with those cases. Or why our download request is rejected.

Agree, with the list we just want to identify which are the most common issues with authenticated downloads and address first the ones that are in the more popular sites. Something similar to what we did with fav icons :)

**Comment by chutten** [comment] 2020-07-22 19:09
Can confirm this is still an issue for downloading the ebook of the month from tor.com on Nightly 2007220608 (get a "Download Failed" prompt. Works fine on Fennec, Chrome, Samsung Internet)

**Comment by liuche** [comment] 2020-07-29 02:05
To summarize w/ the specific sites:

✅ Working for: Gmail, GDrive, Udemy, WizAir (file hosting), Github, Oracle
❌ Failing on: tor.com, dbextra, wowroms

May also be related to #7961.

**Comment by Amejia481** [comment] 2020-07-29 22:22
We are block on this bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1530022

**Comment by vesta0** [comment] 2020-07-30 04:24
@liuche this is probably good enough right now (no longer urgent) but we should still fix the remaining use cases.

**Comment by liuche** [comment] 2020-09-10 18:47
This looks like it landed in GV 2 days ago, so it should be in the next GV Nightly. I'll add a QA-needed label.

**Comment by victor-bayas** [comment] 2020-09-11 13:20
I can now download invoices from my country's IRS equivalent but the download PDF file it's corrupted (0.01mb)

**Comment by lnicola** [comment] 2020-09-11 13:25
@victor-bayas the PDF is likely an HTML page.

**Comment by victor-bayas** [comment] 2020-09-11 13:29
> @victor-bayas the PDF is likely an HTML page.

But Chromium can download it without problems, Fenix it's now Mozilla's production browser for Android

**Comment by Amejia481** [comment] 2020-09-11 13:31
I'm integrating a new GV api on AC https://github.com/mozilla-mobile/android-components/issues/8312 that will likely fixed this and other download issues, it will be pretty helpful if the QA team can verify if this issue is reproduable on the GeckoView example app, as it's using the new GV download api.

**Comment by victor-bayas** [comment] 2020-09-11 16:11
> I'm integrating a new GV api on AC https://github.com/mozilla-mobile/android-components/issues/8312 that will likely fixed this and other download issues, it will be pretty helpful if the QA team can verify if this issue is reproduable on the GeckoView example app, as it's using the new GV download api. 

Can you share the sample app to test?

**Comment by Amejia481** [comment] 2020-09-11 17:06
You can download it from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-gcp-opt)

**Comment by victor-bayas** [comment] 2020-09-11 17:20
> You can download it from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-gcp-opt)

Can't download anything with it

**Comment by Amejia481** [comment] 2020-09-11 17:47
I was able to download by clicking on the link [public/build/geckoview_example.apk](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-central.latest.mobile.android-aarch64-gcp-opt/artifacts/public/build/geckoview_example.apk)

**Comment by victor-bayas** [comment] 2020-09-11 17:51
> I was able to download by clicking on the link [public/build/geckoview_example.apk](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-central.latest.mobile.android-aarch64-gcp-opt/artifacts/public/build/geckoview_example.apk)

I'm speaking about being unable to download any files from the geckoview example browser

**Comment by Amejia481** [comment] 2020-09-11 18:03
@owlishDeveloper can help us to identify how downloads are display on the GeckoView example app, as I'm unable to see a notification when I or dialog when starting a download.

**Comment by owlishDeveloper** [comment] 2020-09-11 18:41
@Amejia481 GVE is a very simple app, it doesn't have any dialogs or notifications for downloads. When you download in it, you just wait and then you open the downloads folder and see if the file is there.

**Comment by Amejia481** [comment] 2020-09-11 18:50
Thanks for the clarification. That will help the QA team to test :)

**Comment by abodea** [comment] 2020-09-17 13:44
Re-tested on the latest Nightly build from **9/1**7 with **Google Pixel 4 XL (Android 11).**

| Website  | Download | Open File from Fenix | Open File from FileManager     |
| ------------- | :-------------: | :-------------: |  :-------------: |
| Google Drive | ✔️ |  ✔️  |   ✔️   |
| Gmail GIF |  ✔️ |  ✔️ | ✔️  |
| Gmail -> WeTransfer link jpg , apk, pdf |  ✔️ |  ❓ | ✔️  | 
| Udemy  |  ✔️ |  ✔️ | ✔️ |      
| Wizair  |  ✔️ |  ✔️ | ✔️  | 
| Github   |  ✔️ |  ✔️ | ✔️  | 
|  Link from #[11436 ](https://github.com/webcompat/web-bugs/issues/11436)- pdf file|  ✔️ |  ❌ | ❌  | 
|  Link from #[54064 ](https://github.com/webcompat/web-bugs/issues/54064 )- pdf file|  ❌|  N/A| N/A  | 

I do believe nothing really changed. 
Removing the `eng:qa:needed` until further notice.

![20200917-162046](https://user-images.githubusercontent.com/42831109/93479446-fc854800-f904-11ea-87fb-9d8c367f92f1.gif)

**Comment by liuche** [comment] 2020-09-17 22:44
@kglazko seems like some pdf opening problems here too?

**Comment by Amejia481** [comment] 2020-10-05 18:03
We recently merged [this patch](https://github.com/mozilla-mobile/android-components/commit/449abd4010c159fa90dddac00d4db7cfa002aecd) on AC, we got a new api from GV (special shout-out to @owlishDeveloper for the hard work), that will hopefully fix those issues :pray: It will be available in the next ac version.

**Comment by abodea** [comment] 2020-10-09 14:01
Hello, @Amejia481 
I re-tested on the latest Nightly for more details please check the following:
| Website  | Download | Open File from Fenix | Open File from FileManager     |
| ------------- | :-------------: | :-------------: |  :-------------: |
| Google Drive | ✔️ |  ✔️  |   ✔️   |
| Gmail GIF |  ✔️ |  ✔️ | ✔️  |
| Gmail -> WeTransfer link jpg , apk, pdf |  ✔️ |  ❓ | ✔️  | 
| Udemy  |  ✔️ |  ✔️ | ✔️ |      
| Wizair  |  ✔️ |  ✔️ | ✔️  | 
| Github   |  ✔️ |  ✔️ | ✔️  | 
|  Link from #[11436 ](https://github.com/webcompat/web-bugs/issues/11436)- pdf file|  ✔️ |  ✔️ | ✔️  | 
|  Link from #[54064 ](https://github.com/webcompat/web-bugs/issues/54064 )- pdf file|  ✔️|  ✔️| ✔️  | 

The problem right now is still when trying to open any file downloaded from WeTransfer or any transfer link.
Maybe this is the only remaining issue when trying to open a file after it was downloaded from a transfer link? It's weird because I did other downloads and I had no issues when I tried to open the files.
![image](https://user-images.githubusercontent.com/42831109/95592139-e4f73600-0a50-11eb-87fb-efd784996a22.png)

Removing `eng:qa:needed` until further notice.

**Comment by victor-bayas** [comment] 2020-10-09 14:09
@Amejia481 all working good on latest Nightly :D

Fenix used to fail to download PDF invoices from my country's companies house website but now it downloads and opens the invoice without problems.

![Screenshot_20201009-090728_Firefox Nightly.jpg](https://user-images.githubusercontent.com/49411169/95593165-f586bc80-0a0e-11eb-8790-209a1e004ca4.jpg)

**Comment by abodea** [comment] 2020-10-09 14:32
Thank you @victor-bayas!
Depending on @Amejia481 input, it's possible to open a new issue or investigate in a new issue the transfer links.

**Comment by lnicola** [comment] 2020-10-09 15:04
For me, the file name in the `Content-Disposition` header is not respected. The browser can't open the file after downloading it, the Files app shows the correct file (!), but in the file picker it shows as `downloadfile.tar`, where `tar` is the correct extension. Tested on Android 10.

**Comment by lnicola** [comment] 2020-10-09 15:27
@Amejia481 the placeholder filename comes from https://github.com/mozilla-mobile/android-components/blob/449abd4010c159fa90dddac00d4db7cfa002aecd/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt#L126. Here's a header that doesn't get parsed correctly: `content-disposition: attachment; filename*=UTF-8''kedia2017mem%2Etar`. https://tools.ietf.org/html/rfc5987 has more details on that encoding.

**Comment by Amejia481** [comment] 2020-10-15 14:59
I think we can close this issue as it's fixed in nightly and we have opened issues for the remaining work, please feel free to reopen if needed!

**Closed by Amejia481** 2020-10-15 14:59 UTC
Labels: Feature:Download, needs:ac, needs:gv, 🐞 bug
