### ISSUE TITLE
[Bug]: Folder icons not visible for bookmark folders in dark theme

### ISSUE THREAD

**Issue by sivaraam** [mozilla-mobile/fenix#23032] opened 2022-01-02 11:47 UTC
### Steps to reproduce

1. Ensure app is in dark theme
2. Tap on the overflow menu (three-dot menu)
3. Tap on "Bookmarks"

### Expected behaviour

The folder icons that are supposed to be shown to left of a bookmark folders entry are visible.

### Actual behaviour

The folder icons that are supposed to be shown to left of a bookmark folders entry is not visible as they it is a black icon in a black background. The icon is visible when long pressing on the folder.

### Device name

OnePlus Nord

### Android version

11

### Firefox release type

Firefox

### Firefox version

95.2.0

**Comment by CaFI0** [comment] 2022-01-02 16:32
This error has already been fixed in Firefox Nightly 97 [#21483](https://github.com/mozilla-mobile/fenix/issues/21483)

**Comment by SoftVision-LorandJanos** [comment] 2022-01-03 07:50
Hi @sivaraam! Thank you for your report!
This issue is reproducible on the latest Release (95.2.0) as you described.
However it was fixed in the latest Nightly 97.0a1 and because the issue was logged before, I'll close it as a duplicate.

**Closed by SoftVision-LorandJanos** 2022-01-03 07:50 UTC
Labels: 🐞 bug, needs:triage
