### ISSUE TITLE
FNX-12091 ⁃ UI test failure - TabbedBrowsingTest.openNewPrivateTabTest

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#11209] opened 2020-06-03 21:01 UTC
Firebase: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5395622059202300723/executions/bs.325131ce4fd0c7d5/testcases/2/errors

```Kotlin
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertNotNull(Assert.java:712)
at org.junit.Assert.assertNotNull(Assert.java:722)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:82)
at org.mozilla.fenix.ui.TabbedBrowsingTest$openNewPrivateTabTest$5.invoke(TabbedBrowsingTest.kt:116)
at org.mozilla.fenix.ui.TabbedBrowsingTest$openNewPrivateTabTest$5.invoke(TabbedBrowsingTest.kt:41)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.openNewTabAndEnterToBrowser(NavigationToolbarRobot.kt:117)
at org.mozilla.fenix.ui.TabbedBrowsingTest.openNewPrivateTabTest(TabbedBrowsingTest.kt:115)
```

**Comment by sv-ohorvath** [comment] 2020-06-24 08:52
dupe of https://github.com/mozilla-mobile/fenix/issues/10642. Closing because the failure cause was already removed.

**Closed** 2020-08-11 03:25 UTC
Labels: Feature:PrivateBrowsing, eng:ui-test, intermittent-test
