### ISSUE TITLE
Can not open about:config page

### ISSUE THREAD

**Issue by alicavus** [mozilla-mobile/fenix#14614] opened 2020-09-02 14:09 UTC
When I try to open `about:config` page, Firefox displays error: Cannot Complete Request

Exact URI of forwarded page: `resource://android/assets/low_and_medium_risk_error_pages.html?&title=Cannot+Complete+Request&button=Try+Again&description=%3Cp%3EAdditional+information+about+this+problem+or+error+is+currently+unavailable.%3C%2Fp%3E&image=&showSSL=false&badCertAdvanced=Advanced%E2%80%A6&badCertTechInfo=%3Clabel%3ESomeone+could+be+trying+to+impersonate+the+site+and+you+should+not+continue.%3C%2Flabel%3E+%3Cbr%3E%3Cbr%3E+%3Clabel%3EWebsites+prove+their+identity+via+certificates.+Firefox+does+not+trust+%3Cb%3Eabout%3Aconfig%3C%2Fb%3E+because+its+certificate+issuer+is+unknown%2C+the+certificate+is+self-signed%2C+or+the+server+is+not+sending+the+correct+intermediate+certificates.%3C%2Flabel%3E&badCertGoBack=Go+Back+%28Recommended%29&badCertAcceptTemporary=Accept+the+Risk+and+Continue`

App version: 80.1.2
OS: Android One (Android 10)
Device: Xiaomi Mi A3

![Screenshot_20200902-165112](https://user-images.githubusercontent.com/7072295/91992846-4a168800-ed3d-11ea-9bda-02e18575478e.png)

Note: Other *about* pages are working, as you see `about:about` is shown as it should:
![Screenshot_20200902-170525](https://user-images.githubusercontent.com/7072295/91994136-e7be8700-ed3e-11ea-87bd-9dcba415a8d0.png)

**Comment by cadeyrn** [comment] 2020-09-02 14:16
Duplicate of #7865.

**Closed** 2020-09-02 15:52 UTC
Labels: needs:triage
