### ISSUE TITLE
[Bug] Two instances of Firefox appear in recent app list

### ISSUE THREAD

**Issue by matthew-horrocks** [mozilla-mobile/fenix#15744] opened 2020-10-07 07:52 UTC
## Steps to reproduce

1. Open a number of apps, including Firefox
2. Press the Recent Apps button and scroll through recently used apps list

### Expected behavior
Only one instance of Firefox is displayed.

### Actual behavior
Two instances of Firefox are displayed. One contains an image of the last viewed tab/page, the other is black. Pressing either of the instances load Firefox at the last used tab/page.

Screen capture at [youtube](https://youtu.be/FY_Akqa_T7I)

### Device information
Google Pixel 2

* Android device: Android 11 (5th September security update)
* Fenix version: 81.1.2 (Build #2015767043)

**Comment by cadeyrn** [comment] 2020-10-07 08:04
Duplicate of #13270, already fixed in Beta.

**Comment by matthew-horrocks** [comment] 2020-10-07 08:22
@cadeyrn so it is. I did plenty of searches... no idea why I couldn't see the bug listed :) Sorry for duplicating.

**Comment by cadeyrn** [comment] 2020-10-07 08:45
No worries. It's not always easy to find existing issues on GitHub. It's easier if you already know that there is a duplicate and what to look for to find the duplicate. 😉

**Closed** 2020-10-07 17:02 UTC
Labels: needs:triage, 🐞 bug
