### ISSUE TITLE
FNX-12128 ⁃ [Bug] Report of crashing on sign in on 5.1.0

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#11235] opened 2020-06-04 18:04 UTC
## Steps to reproduce
```
Anytime I try to sign in to my firefox account of the firefox preview app it crashes. This started just after the update I got for version 5.1.0
```

Reported on Reddit:
https://www.reddit.com/r/firefox/comments/gvkces/firefox_preview_for_android_is_broken/

### Device information
* Android device: ?
* Fenix version: ?

**Comment by liuche** [comment] 2020-06-04 20:23
I tried this on Fenix 5.1 and wasn't able to repro this. I'm going to flag QA to check this because it seems like a critical problem.

**Comment by softvision-miralobontiu** [comment] 2020-06-05 13:52
Hi all!
I didn't exactly get the crash on 77.0.0-beta.2 (beta 5.1.1), but I got the "Unable to send RETRY" message when trying to send the opened tabs to the connected devices. 
I reproduces these scenarios using Samsung Galaxy Note 8 (Android 9), Sony Xperia Z5 Premium (Android 7.1.1), and OnePlus 5T (Android 9).
Here is the log, if it helps:

<details><summary>Crashlog 1</summary>
<p>

```Kotlin

Remote server error: '429' '114' 'Too Many Requests' 'Client has sent too many requests' 'https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format')
2020-06-05 15:25:49.616 27828-27924/? E/FxaDeviceConstellation: Error while running: sending device command
    mozilla.appservices.fxaclient.FxaException$Unspecified: Remote server error: '429' '114' 'Too Many Requests' 'Client has sent too many requests' 'https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format'
        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:4)
        at mozilla.appservices.fxaclient.FirefoxAccount.sendSingleTab(FirefoxAccount.kt:5)
        at -$$LambdaGroup$ks$cKqNXElLbPrDtbCs1hpElG33o2I.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:317)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invokeSuspend(Utils.kt:3)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invoke(Utils.kt:2)
        at kotlin.jvm.internal.Intrinsics.handleFxaExceptions(Intrinsics.java:6)
        at kotlin.jvm.internal.Intrinsics.handleFxaExceptions(Intrinsics.java:17)
        at kotlin.jvm.internal.Intrinsics.handleFxaExceptions(Intrinsics.java:18)
        at mozilla.components.service.fxa.FxaDeviceConstellation$sendCommandToDeviceAsync$1.invokeSuspend(FxaDeviceConstellation.kt:7)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
2020-06-05 15:25:49.619 27828-27850/? I/FxaDeviceConstellation: Executing: sending device command
2020-06-05 15:25:49.620 27828-27850/? D/fxaclient_ffi: fxa_send_tab
2020-06-05 15:25:50.215 27828-27850/? W/fxa_client::ffi: Unexpected error: Error(
    
    Remote server error: '429' '114' 'Too Many Requests' 'Client has sent too many requests' 'https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format')
2020-06-05 15:25:50.217 27828-27850/? E/FxaDeviceConstellation: Error while running: sending device command
    mozilla.appservices.fxaclient.FxaException$Unspecified: Remote server error: '429' '114' 'Too Many Requests' 'Client has sent too many requests' 'https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format'
        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:4)
        at mozilla.appservices.fxaclient.FirefoxAccount.sendSingleTab(FirefoxAccount.kt:5)
        at -$$LambdaGroup$ks$cKqNXElLbPrDtbCs1hpElG33o2I.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:317)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invokeSuspend(Utils.kt:3)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invoke(Utils.kt:2)
        at kotlin.jvm.internal.Intrinsics.handleFxaExceptions(Intrinsics.java:6)
        at kotlin.jvm.internal.Intrinsics.handleFxaExceptions(Intrinsics.java:17)
        at kotlin.jvm.internal.Intrinsics.handleFxaExceptions(Intrinsics.java:18)
        at mozilla.components.service.fxa.FxaDeviceConstellation$sendCommandToDeviceAsync$1.invokeSuspend(FxaDeviceConstellation.kt:7)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
2020-06-05 15:25:50.255 2369-2705/? I/InputDispatcher: Focus entered window: Window{6faa3e u0 org.mozilla.fenix.beta/org.mozilla.fenix.beta.App}
2020-06-05 15:25:50.693 896-896/? I/MSM-irqbalance: Decided to move IRQ48 from CPU2 to CPU0
2020-06-05 15:25:55.712 896-896/? I/MSM-irqbalance: Decided to move IRQ215 from CPU2 to CPU0
2020-06-05 15:26:00.002 2369-2663/? I/BroadcastQueue: am_broadcast_enqueue: [foreground,1,Intent { act=android.intent.action.TIME_TICK flg=0x50000014 (has extras) },11]
2020-06-05 15:26:00.009 2796-2796/? D/KeyguardUpdateMonitor: received broadcast android.intent.action.TIME_TICK
2020-06-05 15:26:00.010 2796-2796/? D/KeyguardUpdateMonitor: handleTimeUpdate
2020-06-05 15:26:00.095 2369-3649/? I/BroadcastQueue: am_broadcast_finished: [foreground,1,Intent { act=android.intent.action.TIME_TICK flg=0x50000014 (has extras) }]
2020-06-05 15:26:00.714 896-896/? I/MSM-irqbalance: Decided to move IRQ57 from CPU2 to CPU0
2020-06-05 15:26:05.722 896-896/? I/MSM-irqbalance: Decided to move IRQ222 from CPU2 to CPU0


</p>
</details>

**Comment by sv-ohorvath** [comment] 2020-06-05 14:13
Couldn't reproduce it on today's smoke tests on Beta 77.0.0-beta2. We'll keep investigating on Nightly.

**Comment by astarq** [comment] 2020-06-06 12:38
This happened once for me on Nightly.
I don't have version number, but it was the one before Nightly 200606 06:21

I couldn't reproduce it.

**Comment by liuche** [comment] 2020-06-10 01:24
I'm fine closing this now that we're in QA for 5.2.

**Comment by AndiAJ** [comment] 2020-06-19 12:14
Hi, **didn't managed to reproduce this issue** on the latest **`Nightly Build #200619 from 6/19`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

Moreover, nothing related was discovered while testing **`Fenix 5.2.0-beta.2`**

**Closed** 2020-08-11 03:30 UTC
Labels: Feature:Accounts, b:crash, eng:qa:verified, 🐞 bug
