### ISSUE TITLE
[Bug] Images not saving to gallery

### ISSUE THREAD

**Issue by ZacharyGeorgeNN** [mozilla-mobile/fenix#15666] opened 2020-10-04 02:14 UTC
Using the latest version of Firefox Android. Every time I try to save an image it doesn't save to my phone's gallery like it used to before the major update. I can see them in my downloads list, but nowhere else.

**Comment by anotherus3r** [comment] 2020-10-04 07:00
Duplicate of #8754. Fixed in latest Nightly.

**Comment by ZacharyGeorgeNN** [comment] 2020-10-04 17:24
Will it be fixed in daylight too?

**Comment by anotherus3r** [comment] 2020-10-04 18:41
@ZacharyGeorgeNN might be best to ask in #8754. Someone already asked if it will be uplifted into beta.

**Comment by Amejia481** [comment] 2020-10-05 13:35
Closing in favour of #8754.

**Comment by Amejia481** [comment] 2020-10-05 13:36
> Will it be fixed in daylight too?

We are going to added it to the uplift patches list.

**Closed by Amejia481** 2020-10-05 13:35 UTC
Labels: needs:triage, 🐞 bug
