### ISSUE TITLE
FNX-5420 ⁃ [Bug] Toolbar Covers Top Text in Custom Tab Error Page

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#2052] opened 2019-04-25 22:07 UTC
## Steps to reproduce
1. Open custom tab when not connected to internet 

### Expected behavior
Can view error page

### Actual behavior
Error page covered by top toolbar
![Screenshot](https://user-images.githubusercontent.com/25442310/56771563-dee19c80-676b-11e9-9958-bdc6c3514884.png)UNITO-UNDERSCORE!20190425-150636!

### Device information
* Android device: Pixel 3
* Fenix version: Nightly 4.25

**Comment by kbrosnan** [comment] 2019-04-25 22:15
Dupe of #1727? This is essentially web content correct?

**Comment by ekager** [comment] 2019-04-25 22:30
Technically it's the same underlying cause but since we control the error page content, we could fix this with altering that layout

**Comment by vesta0** [comment] 2019-04-30 16:55
Blocked on #552

**Comment by jonalmeida** [comment] 2019-05-10 18:06
See engineering notes in this comment regarding the fix for this: https://github.com/mozilla-mobile/fenix/issues/1727#issuecomment-488541929

**Comment by bifleming** [comment] 2019-05-29 17:47
@vesta0 can we remove this from MVP scope (and the kanban board)?

**Comment by cadeyrn** [comment] 2019-05-29 19:22
@bifleming: If this will be removed from MVP scope then #1727 has to be re-opened because that's an big problem which is - in my opinion - very important for MVP. It makes Fenix not really usable as default browser because of hidden website content in custom tabs and it was said in #1727 that the bug will be addressed here.

**Comment by jonalmeida** [comment] 2019-05-29 20:52
I'm not sure why this issue is marked as a-c. I've posted the linked issue that the fix needs to go into Fenix: https://github.com/mozilla-mobile/fenix/issues/1727#issuecomment-488541929

**Comment by softvision-miralobontiu** [comment] 2019-05-31 07:53
Verified as fixed on the latest build 1.0.1922 (#11510609), with Motorola Moto G6 (Android 8).

**Closed** 2020-08-11 13:44 UTC
Labels: Feature:CustomTabs, Release Blocker, eng:qa:verified, 🐞 bug
