### ISSUE TITLE
[Bug]: Can't add shorcut to a page that has a PWA

### ISSUE THREAD

**Issue by EDEADLINK** [mozilla-mobile/fenix#24775] opened 2022-04-13 17:50 UTC
### Steps to reproduce

1. Open webpage that has a progressive web app available (like github.com)
2. The button to add a shortcut to the page is replaced by install.
3. Try to add a shortcut to a specific page like "https://github.com/mozilla-mobile/fenix"
4. Cry

### Expected behaviour

The option to install the PWA *and* the option to add the shortcut should be accessible.

### Actual behaviour

Only the option to install the PWA is available. :(

### Device name

Oneplus 5t

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1

## Workaround

1. Disable internet access (airplane mode)
2. Visit page
3. Add shortcut to homepage

**Comment by cadeyrn** [comment] 2022-04-13 19:53
Duplicate of #15450.

**Closed** 2022-04-15 22:24 UTC
Labels: 🐞 bug, needs:triage
