### ISSUE TITLE
FNX-4728 ⁃ why top sites can not sync ?

### ISSUE THREAD

**Issue by kzwr** [mozilla-mobile/fenix#10231] opened 2020-04-27 06:39 UTC
### Why/User Benefit/User Problem
When i use Firefox Preview on other phone,top sites not auto sync.

### What/Requirements
I hope Firefox Preview can auto sync top sites.

### Acceptance Criteria (how do I know when I’m done?)
Use Firefox Preview on other phone

**Comment by cadeyrn** [comment] 2020-04-27 06:59
Duplicate of #7936.

**Comment by sv-sdeiac** [comment] 2020-04-27 07:12
Closed as a duplicate of #7936.

**Closed** 2020-08-10 19:39 UTC
