### ISSUE TITLE
[Private Browsing Mode] Hitting back button in PBM shortcut takes you to non-PBM homescreen

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#6304] opened 2019-10-28 19:05 UTC
1. Add a Private Browsing shortcut to your homescreen from Fenix settings
2. Tap on Private Browsing shortcut on homescreen
3. Hit the back arrow in the bottom nav

Expected:
Takes you to Private browsing fenix homescreen

Actual:
Takes you to non-private fenix homescreen

**Comment by boek** [comment] 2019-11-19 18:50
Added to #6694

**Comment by mcarare** [comment] 2019-11-29 08:15
An even worse behaviour:
1. Have _Open links in a private tab_ checked
2. Open a link from another app
3. The Private tab loads. Hit back button (It happens both when you wait or do not wait for it to load)). This takes you back to the other app
4. Open recent apps list, tap on Fenix.

You will see this blank white screen:
<img src = https://user-images.githubusercontent.com/48995920/69854046-c18c2800-1290-11ea-910c-a0333e8f09cf.png width = 40%>

**Comment by sblatz** [comment] 2019-12-26 15:12
I can't find the ticket now, but I believe there was discussion at some point about changing the behavior of this shortcut to just launch the user into private mode (not directly to the search screen). Do we know where we landed on that?

@brampitoyo, @AmyYLee

**Comment by sblatz** [comment] 2019-12-26 21:38
This one is a bit tricky 😕 I spent a few hours today trying to crack it. What's happening here is pressing back triggers an `onNewIntent` and then an `onCreate` which recreates the app with a new mode (normal) since we don't persist the mode. 

I'm unsure **WHY** both `onNewIntent` and `onCreate` are called when pressing the back button. Based on my research only one should be? 

### Solutions I tried
* Modify the intent extras sent in `onNewIntent` to have a private_browsing TRUE flag so that onCreate could read from its extras and properly set the mode. This didn't work because `onCreate` does not read from the same intent as `onNewIntent` (even when I do `setIntent`)

* Set the mode in the Settings. This just lead to lots of spaghetti code where we're sometimes reading the intent and sometimes reading Settings. It doesn't feel like a clean solution.

**Comment by sblatz** [comment] 2019-12-26 22:34
Here's a demo of the behavior I'm describing:

![private demo 2 2019-12-26 17_34_01](https://user-images.githubusercontent.com/4400286/71492531-edee8200-2805-11ea-8816-3d330f864102.gif)

**Comment by mcarare** [comment] 2019-12-30 09:37
@sblatz I also proposed this solution, to open the private to home, not search. It will also improve #625

**Comment by sblatz** [comment] 2019-12-30 18:20
Moving this to "waiting" until we have UX feedback here 😄

**Comment by AmyYLee** [comment] 2019-12-30 19:13
> This one is a bit tricky 😕 I spent a few hours today trying to crack it. What's happening here is pressing back triggers an `onNewIntent` and then an `onCreate` which recreates the app with a new mode (normal) since we don't persist the mode.
> 
> I'm unsure **WHY** both `onNewIntent` and `onCreate` are called when pressing the back button. Based on my research only one should be? I thought it may be because the mode is changing and thus causing a `recreate` to be called, but it happens even when I hold the mode constant.
> ### Solutions I tried
> 
>     * Modify the intent extras sent in `onNewIntent` to have a private_browsing TRUE flag so that onCreate could read from its extras and properly set the mode. This didn't work because `onCreate` does not read from the same intent as `onNewIntent` (even when I do `setIntent`)
> 
>     * Set the mode in the Settings. This just lead to lots of spaghetti code where we're sometimes reading the intent and sometimes reading Settings. It doesn't feel like a clean solution.
> 
> 
> **Update** I have the second solution _kind of_ working. It works for the use case we've described, but now is broken for a different reason: being in private mode, force closing the app, and opening again would open the user to private mode.
> 
> I wonder if we should move forward with this solution: have the private browsing shortcut just open the user to private browsing home screen. In my opinion this makes more sense as it's more consistent with how the regular fenix icon works, but I'd love to discuss with Bram/Amy! It's also a much simpler solution and still provides the proper UX for the underlying issue of wanting an "always private mode" :)

Hi, 

My intention for opening PBM directly into search mode is for an added level of privacy so the user's last opened private tabs aren't revealed when they tap on the PMB shortcut (if they had tabs opened and forgot to erase them). Curious to know what @brampitoyo thoughts are?

**Comment by sblatz** [comment] 2020-01-03 22:21
Spoke with Amy a bit more. We basically have three choices:

 1. Fix this bug BUT revert a previous decision surrounding "persisting private mode." E.g. being in private mode, force closing the app, and opening again would open the user to private mode.
We decided **NOT** to go with this because normal mode -> private mode, pause the app, open the app would cause the user's private tabs to be leaked.  

 2. Have the private browsing shortcut just open the user to private browsing home screen (potentially leaking previous private tabs they had open)

 3. Keep this bug around

We are going to go with the option that most resembles current Focus behavior. The shortcut should basically act as a "private mode" entry point. If the user leaves the app on the Browser Screen, we would let it open to that if the user pressed the private shortcut. It will **NOT** directly launch to the private search screen.

**Comment by sblatz** [comment] 2020-01-06 20:29
Spoke with Chenxia & Amy one more time 😅 

Going to move forward with **persisting** private/normal mode (even through force quits). We will make "hide private tabs after 30 minutes" a feature request follow up.

**Comment by sv-sdeiac** [comment] 2020-01-10 09:04
Hello, I can confirm that this issue is fixed using the latest version of Nightly 1/10 #20100616.

Devices:
- Motorola Moto G6 (Android 8);
- LG G7 fit (Android 8.1);
- OnePlus 5T (Android 9).

**Closed by sv-sdeiac** 2020-01-10 09:04 UTC
Labels: Feature:PrivateMode, P2, eng:qa:needed, 🐞 bug

**Comment by abodea** [comment] 2020-01-14 11:25
Reproducible on **Fenix 3.1.0-beta  3(Build #20092354) GV 72** with **Google Pixel 3a XL(Android 10).**

**Comment by sblatz** [comment] 2020-01-14 21:58
@abodea are you saying you're still having this issue? Is it happening for you on nightly?

**Comment by abodea** [comment] 2020-01-15 07:06
>sblatz commented 9 hours ago
@abodea are you saying you're still having this issue? Is it happening for you on nightly?
--
Hi @sblatz this is only for beta as I mentioned above. We are doing a full run on testrail for the latest beta.

**Comment by opusforlife2** [comment] 2020-01-31 18:12
@sblatz Hey, thanks for fixing this bug and also letting private mode persist!

I don't get the rationale for this part:
> If the user leaves the app on the Browser Screen, we would let it open to that if the user pressed the private shortcut. It will NOT directly launch to the private search screen.

That will leave the shortcut useless, as the main icon would do the same thing. Why not let the shortcut continue opening to the search screen? This will let users choose between using the normal app icon vs the shortcut for their preferred behaviour. The majority of users would use the main icon (whether in private mode or otherwise) and the extra privacy conscious could choose to use the private shortcut.

I agree with @AmyYLee here:
> My intention for opening PBM directly into search mode is for an added level of privacy so the user's last opened private tabs aren't revealed when they tap on the PMB shortcut (if they had tabs opened and forgot to erase them).
