### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by aifeierzhidian** [mozilla-mobile/fenix#17349] opened 2021-01-07 03:57 UTC
![Screenshot_20210104-011759](https://user-images.githubusercontent.com/20397338/103849352-69546600-50df-11eb-8567-4647bc8698ad.jpg)
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Device information

* Android device: ?
* Fenix version: ?

**Comment by mcarare** [comment] 2021-01-07 07:38
Duplicate of https://github.com/mozilla-mobile/fenix/issues/16422. The issue is already fixed in Nightly and Beta.

**Closed by mcarare** 2021-01-07 07:38 UTC
Labels: needs:triage, 🐞 bug

**Comment by aifeierzhidian** [comment] 2021-01-07 07:45
Thank you.
