### ISSUE TITLE
[Bug] Android (10) restarts when trying to select stored credentials

### ISSUE THREAD

**Issue by michaelof** [mozilla-mobile/fenix#16475] opened 2020-11-10 11:34 UTC
##  Steps to reproduce
Reproducible, 100%

I have a private VPS with roundcubemail webmail client (https://roundcube.net/). Running on Apache, based on OpenSuse Leap 15.2.

Fenix on my mobile is using Firefox Sync, syncing credentials, bookmarks, settings and addons, no history.

- when navigating to roundcubemail  login page, page is shown. Entering credentials manually and login is possible. 
When language is "system language" (= German for me), fenix shows the 10+ stored credentials as "Vorgeschlagene Zugangsdaten". When opening this list, Android RESTARTS! As said, reproducible 100%. FYU it's some of "fast restart", faster than a reboot, sorry for being that vague.

- For writing this issue, to have the correct English texts, I've switched my Fenix from "follow system language" (=German for me) to US English. After that, ** NO ** credentials are offered, anymore. Also when switching back to German/System language, they are "gone". Still shown in stored credentials database, but not offered anymore :( Another bug?

- FYI before switching languages, Fenix offered also 10+ saved credentials for my Nextcloud instance, same VPS/Apache. This worked fine, no Android restart. But after switching languages, credential offering is also gone for Nextcloud :(

- FYI Synced Firefoxes on Linux etc. are NOT affected, only Fenix

### Expected behavior

Fenix should offer credentials as before, usable.

### Actual behavior

Fenix crashes, and/or Android restarts GUI.

### Device information

* Android device: Nokia 7.2, Android 10
* Fenix version: 82.1.3

**Comment by michaelof** [comment] 2020-11-10 16:53
More findings: 

"Suggested logins" are back, also in english. But crashes are happening both for roundcubemail and nextcloud. 
There seems to / might be a dependency to the amount of "suggested logins", as only some of them (e.g. 5 out of 10 or so) are shown before crashing

**Comment by ekager** [comment] 2020-11-10 16:59
Is there anything in about:crashes? Is it still reproducible 100% after restart?

**Comment by michaelof** [comment] 2020-11-11 10:52
about-crashes shows only one crash, some days ago, not related.

Issue has been reproducible after power off / power on.

But switching languages has changed behaviour: Sometimes "suggested logins" are shown, sometimes not. Have had a crash/restart  also for my nextcloud also, a couple of times.

As of today, problem does NOT occur, "suggested logins" offered for all sites, and works fine.

Strange issue ... I'll watch it and come back if reoccurs. Should the issue stay open, or closed and reopened if needed?

**Comment by michaelof** [comment] 2020-11-19 09:14
Happened again 2 min.ago, today. Nextcloud login page, many stored crredentials

**Comment by ekager** [comment] 2020-11-20 07:19
We can keep the issue open. Unfortunately, I can't repro still, please update here if you get a crash report or see any specific STR :/

**Comment by ekager** [comment] 2020-12-09 22:19
Possible dupe of https://github.com/mozilla-mobile/fenix/issues/15383

**Comment by michaelof** [comment] 2020-12-30 11:24
Still in 84.1.2
As there are no logs etc., one maybe helpful finding: I'm using Anysoft keyboard on Android. It seems that the crash only or at least more frequently happens, if keyboard is open/shown. E.g.: Nextcloud login screen, when shown fullscreen, no keyboard, offered credentials mostly works. When klicking into user name field, keyboard pops up, waiting for input. If then clicking on stored credentials, mostly crashing.
Will test now with stock Google keyboard.

**Comment by michaelof** [comment] 2020-12-30 11:27
Still in 84.1.2
As there are no logs etc., one maybe helpful finding: I'm using Anysoft keyboard on Android. It seems that the crash only or at least more frequently happens, if keyboard is open/shown. E.g.: Nextcloud login screen, when shown fullscreen, no keyboard, offered credentials mostly works. When klicking into user name field, keyboard pops up, waiting for input. If then clicking on stored credentials, mostly crashing.
Will test now with stock Google keyboard.

**Comment by michaelof** [comment] 2020-12-30 11:28
Same behaviour with Gboard :(

**Comment by lobontiumira** [comment] 2021-06-30 11:46
@michaelof are you able to reproduce this issue on the RC 89.1.1 build?
Thank you!

**Comment by michaelof** [comment] 2021-06-30 11:58
@lobontiumira Hi Mira, good news: I can't reproduce the error, whatever I try, anymore. Seems to.be fixed, thanks to all who contributed!

**Comment by lobontiumira** [comment] 2021-06-30 12:00
Excellent news.
I'll close this issue.
Thank you!

**Closed by lobontiumira** 2021-06-30 12:00 UTC
Labels: Feature:Logins, b:crash, 🐞 bug
