### ISSUE TITLE
[UX] Select link's text && Select text

### ISSUE THREAD

**Issue by black7375** [mozilla-mobile/fenix#15397] opened 2020-09-24 16:25 UTC
### What is the user problem or growth opportunity you want to see solved?
Currently Firefox is difficult to select text.
I would like to refer to the case of Samsung Internet.

1. **Link Long Press**
  - Long press to select the text of the link.
  - **UX**: Separate `tab creation` and `link-related` features for easy recognition.
  - **UX**: You can `copy` links directly, but `select` is better because you can select another areas, search/translate them with text content, and so on.
![Samsung_Internet-0_LinkPress](https://user-images.githubusercontent.com/25581533/94161421-2bf00380-fe75-11ea-819c-b1df01b13cb8.jpg)

2. **Select Link's Text**
- You can copy the text from the link or perform other actions.
![SamsungI_Internet-1_LinkSelection](https://user-images.githubusercontent.com/25581533/94164742-f220fc00-fe78-11ea-9c0a-40bc8a38e8ba.jpg)

3 **Adjust the area.**
- You can make the area wider or narrow.
- **UX**: Zoom in on the area you are changing to make sure you select even small letters precisely.
- **UX**: The sensitivity of the cursor is low, so it is easy to select each letter. #15391
- **UX**: There is a natural animation by increasing the size of the cursor used during selection.
![SamsungI_Internet-2_Extend_Selection_Area](https://user-images.githubusercontent.com/25581533/94165378-ac186800-fe79-11ea-89f1-3213ea6a74f9.jpg)

4. **Selection END**
![SamsungI_Internet-3_Selection_Complete](https://user-images.githubusercontent.com/25581533/94165440-bdfa0b00-fe79-11ea-808d-17d721da0b91.jpg)

#### Summary
- Link long press
  - Feature: Link Text Selection
  - Menu: Seperate `tab creation` and `link-related` features
- During selection
  - Feature: Zooming area
  - Adjustments: Cursor's sensivity (I don't know if it's the right word)
  - Animate: Cursor's size up

### How do you know that this problem exists today? Why is this important?
Copy & Paste is a universal feature that very many users use and I think it is important.

**Link Long Pressed Menu**
- Don't have `Select Text`, dividing line.
![Fenix-0_LongPress](https://user-images.githubusercontent.com/25581533/94169299-2e0a9000-fe7e-11ea-9435-6599f2d541e0.jpg)

- 3-Dot menu has a dividing line.
![Fenix-1_SeperateMenu](https://user-images.githubusercontent.com/25581533/94169813-c99c0080-fe7e-11ea-8960-a6725f614468.jpg)

**Text Selection**
- The text of a hard-to-recognise link: Ex. [Firefox Addon](https://addons.mozilla.org/en-US/android/collections/13911619/Mobile/)
![Fenix-2_BlackColoredLink](https://user-images.githubusercontent.com/25581533/94171198-82af0a80-fe80-11ea-84c3-184ac972a502.jpg)

- Screenshot for selecting the small print in 5609
  - Don't have zooming area
  - Press and hold to select the numbers(`4,485.609`), then move the left cursor to the right(approximately `4,4` passed), the area changes very much.
![Fenix-3_Selected](https://user-images.githubusercontent.com/25581533/94171699-184a9a00-fe81-11ea-8b37-21fb3a812667.jpg)
![Fenix-4_Select_During](https://user-images.githubusercontent.com/25581533/94171708-1b458a80-fe81-11ea-9fbd-3e63576a1774.jpg)

### Who will benefit from it?
I'll only describe the features.

**Link Text Selection**
- Anyone who wants to easily select the text of the link

**Zoomig Selction Area && Cursor sensitivity down**
- Those who want to select precisely
- Those who need to select small letters
- a person with low vision

**Comment by kbrosnan** [comment] 2020-09-24 20:38
Duplicate of #1589

**Closed by kbrosnan** 2020-09-24 20:38 UTC
Labels: needs:triage

**Comment by black7375** [comment] 2020-09-24 20:49
@kbrosnan 

Did the following suggestions duplicated?
- Menu seperate
- Feature: Zooming area
- Animate: Cursor's size up

**Comment by TheOPtimal** [comment] 2020-09-25 04:53
@kbrosnan reopen this, this isn't a duplicate (or at least only a tiny part if it is)

**Comment by klint** [comment] 2020-09-25 07:58
@kbrosnan better open one ticket per feature, then.
