### ISSUE TITLE
Increase icon size of start page icons

### ISSUE THREAD

**Issue by lineinthesand** [mozilla-mobile/fenix#13929] opened 2020-08-19 16:45 UTC
### What is the user problem or growth opportunity you want to see solved?
The icons on the start page (a freshly opened tab) are simply too small. They were of acceptable size in FF mobile 68 but they are hardly visible in FF mobile 79.

### How do you know that this problem exists today? Why is this important?
I was upgraded to FF mobile 79 without prior notice of its many regressions and drawbacks

### Who will benefit from it?
Especially visually impaired persons

**Comment by cadeyrn** [comment] 2020-08-19 16:59
Duplicate of #11868.

**Comment by liuche** [comment] 2020-08-20 02:07
Dupe of #13765

**Closed by liuche** 2020-08-20 02:07 UTC
Labels: needs:triage
