### ISSUE TITLE
Desktop like tab bar option

### ISSUE THREAD

**Issue by Kuvesz** [mozilla-mobile/fenix#2344] opened 2019-05-08 13:39 UTC
Hi!

I was just trying Fenix on my tablet and as it turns out it uses the same user interface as the one on phones, which I believe doesn't use the much bigger screen of a tablet as well as it could.
Specifically I'm really missing the desktop like tabs layout, which works very well on tablets. Any chance this will change to what it is like now in Firefox Mobile (or Fennec if you prefer)?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11347)

**Comment by mheubusch** [comment] 2019-05-08 14:20
@Kuvesz Thanks for reaching out - and, yes, this is the right place to share your feedback and ideas! Our first releases will  focus on phone, but we expect to optimize for tablet later this year. I'm not sure what that means in terms of tabs, but we will  work to make the experience as useful and usable as we can.

**Comment by Kuvesz** [comment] 2019-05-08 14:26
Thank you for the quick answer, not sure what your policy is so I won't close the issue, but I'm always happy to use Mozilla's software, so whatever happens I'm looking forward to the Fenix Google Play release. :)

**Comment by mheubusch** [comment] 2019-05-08 14:30
Please leave it open - I've added it to our backlog so we have your input when we work on this in the  future. Glad you share our excitement for the upcoming release!

**Comment by Chris01277** [comment] 2019-07-19 13:50
Thanks for the link: # 2340 from Kuvasz.  I have already seen this.  
 But Kuvesz pleads for a tab design like seen at Firefox for desktop I do not necessarily want.  I think the current UI is basically OK, but in case of sufficient form factor - like a tablet - some commands from the 3-point menu should be moved or duplicated next to the URL bar.

**Comment by yoasif** [comment] 2020-05-12 20:55
Can this be renamed and tagged with Feature:FennecTransition?

I was unable to find this issue with "tabbed browser".

**Comment by yoasif** [comment] 2020-05-13 00:41
Quoting from https://github.com/mozilla-mobile/fenix/issues/10607

### What/Requirements

1. An option in the customize section of settings that allows users to enable a tabbed browser. This exists in Vivaldi as an option for "tab strip."
2. User can tap tabs to switch to them.
3. User can rearrange tabs by dragging them. 

### Acceptance Criteria (how do I know when I’m done?)

Users have visible tabs in their browser like in Fennec.

**Comment by Shaurya-Kalia** [comment] 2020-08-05 03:56
> Quoting from #10607:
> 
> Beta users have [asked](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta&hl=en_US&reviewId=gp%3AAOqpTOGnPYVCNQi36LGZLkJ39O4j8XyGbYfPy5e5B5yESJBp9qpVSnPjnFcQqCyo_vavPDHFVZKoK7uO0sG2Lw) about this.
> ### What/Requirements
> 
>     1. An option in the customize section of settings that allows users to enable a tabbed browser. This exists in Vivaldi as an option for "tab strip."
> 
>     2. User can tap tabs to switch to them.
> 
>     3. User can rearrange tabs by dragging them.
> 
> 
> ### Acceptance Criteria (how do I know when I’m done?)
> 
> Users have visible tabs in their browser like in Fennec.

I think, a good description would be a desktop like UI optimised for touch

**Comment by pocmo** [comment] 2020-08-05 11:10
Related AC issue:
https://github.com/mozilla-mobile/android-components/issues/1302

**Comment by Pomax** [comment] 2020-09-04 17:44
it looks like the project this was in (https://github.com/mozilla-mobile/fenix/projects/2#card-21229607) got closed, without this issue being moved to a still open project: as functionality that was marked as MVP, hopefully this can be moved to the project for the next release? (it's a missing feature that's forced me to using Chrome for now, since I heavily rely on instant tab switching on my tablet that has until recently only had FF and FF Nightly installed on it)

**Comment by black7375** [comment] 2020-10-12 16:39
* **Opera:**  I think it's the most typical.
* **Samsung Internet:** Tab bar under the address bar

| ![Opera](https://user-images.githubusercontent.com/25581533/94325947-9fd2fe80-ff90-11ea-96bf-bcc5393aaf52.jpg)</td> | ![Samsung](https://user-images.githubusercontent.com/25581533/94325950-a19cc200-ff90-11ea-8fca-10d6926bedb8.jpg) |
|---------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------|

* **Vivaldi:** It can also be at the bottom.

| ![Vivaldi](https://user-images.githubusercontent.com/25581533/94325953-a497b280-ff90-11ea-9ee2-163333a149b1.jpg) | ![Vivaldi_Bottom](https://user-images.githubusercontent.com/25581533/94325951-a3668580-ff90-11ea-8d5e-944976909692.jpg) |
|------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|

**Comment by Pomax** [comment] 2020-10-13 15:38
On a phone, the "tabs" (which aren't tabs at all, of course) are fine: it's the same "your 'tabs' are on a different screen" as before.

The problem is that the phone UI got forced onto tablet users, too, which these screenshots are not useful for: tablets can use the original tabs-at-the-top with the url bar in the tab's view perfectly fine. There is tons of space to keep the UI the same as it was before we were all forced onto the new UX, While giving phone users the option to force-turn-on tabs should of course be standard operation (the whole point of firefox is that you are in control of the browser), designing the UX should pretty much ignore phones completely and focus on restoring tabs to the devices that supported them before the forced updated.

**Comment by laem** [comment] 2020-10-26 21:01
I also have to use Kiwi browser ([open source chromium fork](https://github.com/kiwibrowser/src)) on my desktop mode Android, until Firefox provides an acceptable large screen UI.

**Comment by batuhankrmn** [comment] 2021-08-15 03:28
For god sake, people asked this feature for 2 years. It's the game changer feature for big screens & tablets. Seriously I'm waiting for this to make Firefox my main Android browser.

**Comment by bpwned** [comment] 2021-08-15 07:55
It's quite jarring. On Android tablets, Firefox has removed proper tabs. On iPadOS, Firefox has proper tabs but is broken in many other ways. Essentially, there is no way to use Firefox on mobile OS tablets at the moment without tremendous frustration.

**Comment by eloyperez** [comment] 2022-01-13 06:15
I switched to Vivaldi until this is fixed. 

And since sync is important to me, I had to do it on all platforms: Android/phone, Android/tablet, Mac, Windows. 

Please allow enabling the tab bar so that I can switch back to Firefox!

**Comment by Pomax** [comment] 2022-01-13 21:57
@cadeyrn rather than emojis, please triage this into the correct project - it was in the MVP list, that project got moved and closed without this work having been completed. Even if it's 2 years later, making sure it gets done is still very much worth the effort (unless of course the UX already does this now, in which case we can close this issue as resolved).

**Comment by cadeyrn** [comment] 2022-01-14 08:36
> @cadeyrn rather than downvote emojis, please triage this into the correct project

1. I do not work for Mozilla so I can't "triage this into the correct project".
2. GitHub features are there to be used. It's not your business if I see a reason to use a reaction for a comment.

**Comment by Pomax** [comment] 2022-06-06 17:53
Vivaldi really is the only browser that understands that if you're running on a tablet, you should just show a desktop UI (and while the reload button shouldn't be tucked away in the hamburger menu, that's pretty much the only gripe. It does _so many things_ right that mobile Firefox should have had from day one. (and of course ironically, for the most part actually _had_ before the decision was made to switch the codebase and release a completely new app with drastically fewer features, and effectively all power-user features removed)

**Comment by MicroBeast** [comment] 2022-06-09 23:56
> Vivaldi really is the only browser that understands that if you're running on a tablet, a desktop UI is perfectly fine (and while the reload button shouldn't be tucked away in the hamburger menu, that's pretty much the only gripe. It does _so many things_ right that mobile Firefox should have had from day one. (and of course ironically, for the most part actually _had_ before the decision was made to switch the codebase and release a completely new app with drastically fewer features, and effectively all power-user features removed)

I think that's not Vivaldi invention. It is Chromium and or Chrome that know the difference between tablet or phone (big/small screen) and change its UI accordingly. Vivaldi might just make use/enhance that with whatever their extra ideas.

**Comment by amitrgholap** [comment] 2022-06-17 13:18
Do you guys think, its funny to lose user base? Today I was using FF on Chromebook and also Win 10.. 
Win 10 : I created a gmail draft and uploaded some attachments.
Later wanted to edit the draft, download some attachments to check and upload few more and send email.
I used Chromebook for the edit draft bla bla steps. Just look at the FF GUI. Hopeless GUI. I was forced to use chrome browser to do my stuff.
(Someone might ask, why not use gmail app. Well, it has some bugs related to replying to drafts.)

**Comment by Pomax** [comment] 2022-06-19 00:54
@amitrgholap that has nothing to do with a desktop-like tab bar. Please file a separate issue (provided you can actually point to what's wrong)

**Comment by gaul** [comment] 2022-07-06 22:28
Firefox for iPad has a tab bar so this is also a feature parity issue.

**Comment by amitrgholap** [comment] 2022-07-08 12:29
> Firefox for iPad has a tab bar so this is also a feature parity issue.

I dont own iPad. But if it works on ipad, Please provide same features on android and chromebook as well.

**Comment by tbleiker** [comment] 2022-07-26 15:43
+1 for a tab bar option!

I just bought a Chromebook (Lenovo Duet 5) and I would really like to use Firefox on this tablet. However, the android version is not very comfortable to use on it.

**Comment by JasonHK** [comment] 2022-08-09 09:31
I stumble across the old screenshot of the old Firefox for Android, it's indeed has tabs when it's on tablet mode. Really hope tabs will be returning soon.

![Screenshot_20180529-235043](https://user-images.githubusercontent.com/4410086/183613802-1e577d87-3954-4e56-81cf-be5f0bec2995.jpg)

**Comment by Macmee** [comment] 2022-11-04 07:43
Another vote for tablets, I would love this!

**Comment by ryanwwest** [comment] 2022-11-07 21:48
I'd love this too; it's the one thing holding me back.

**Comment by YozenPL** [comment] 2022-11-20 10:42
Do we have any update on this? I started to use DEX and for now it is the most needed feature for me.

**Comment by thetrev** [comment] 2022-12-04 12:06
Switched to Vivaldi a few years back, because not having tabbed browsing on a tablet (where a mouse is commonly used) is an extra unneeded click when screen space is no longer at a premium. People buy into an ecosystem too, so I'm not using FF on desktop anymore either for sync purposes.

It's the only thing stopping me from coming back to Firefox.

**Comment by Dakkaron** [comment] 2022-12-24 09:03
Same thing for me as well:
I really would like to switch back to Firefox. For now I'm stuck with Vivaldi.

The two main things keeping me from switching are tablet UI (which I want to use on my phone. I got the UI scaling cranked down all the way to fit more stuff onto my screen) and keyboard shortcuts (I got a Fairberry keyboard attachment).

**Comment by MrYoshii** [comment] 2023-01-09 15:35
i don´t think thy will add this feature :/

**Comment by Pomax** [comment] 2023-01-10 17:57
Restore. Not add.

We're not asking to get a new feature developed so much as we're all asking for a feature that existed to be put back in. Because this is straight up a bug: someone removed UI that should never have been removed.

**Comment by Dakkaron** [comment] 2023-01-13 00:25
@amitrgholap I don't think so. I rather think they put FF on Android on maintainance mode. No funding for big developments. And I kinda understand it. After they rammed their market share into the ground that hard, I'd be surprised if FF on Android is generating any money at all for them.

**Comment by amitrgholap** [comment] 2023-01-13 09:12
> @amitrgholap I don't think so. I rather think they put FF on Android on maintainance mode. No funding for big developments. And I kinda understand it. After they rammed their market share into the ground that hard, I'd be surprised if FF on Android is generating any money at all for them.

Sorry. FF is an ecosystem. It cannot be divided into "per platform" market share. I am using FF, since it has all my passwords and I like the master password functionality to access my pwds across any device.

**Comment by Dakkaron** [comment] 2023-01-13 12:00
> > @amitrgholap I don't think so. I rather think they put FF on Android on maintainance mode. No funding for big developments. And I kinda understand it. After they rammed their market share into the ground that hard, I'd be surprised if FF on Android is generating any money at all for them.
> 
> Sorry. FF is an ecosystem. It cannot be divided into "per platform" market share. I am using FF, since it has all my passwords and I like the master password functionality to access my pwds across any device.

That is certainly true, for some people. But judging from the market share, which is much higher than on Android, that's probably not the majority.

Or to put it in a different way: Most people who really care about a decent integration between their PC and mobile browser, and are at the same time really annoyed by FF on Android, probably already jumped ship to Vivaldi or another competitor.

Believe me, I am really annoyed by not having sync between FF on my laptop and my phone any more, but that's outweighed by the hard lack of features on the Android app. So I am currently using FF on PC and Vivaldi on Android.

I tried using Vivaldi for both, but the desktop version of Vivaldi is much worse than FF.

**Comment by Shaurya-Kalia** [comment] 2023-01-13 13:58
Since I am getting too many mails on a bug report that i subscribed to years ago, and the comments here have turned to a discussion at this point, I felt like I should add my experience too.

I have two phones (androids), one PC (linux), laptop (windows) and tablet (android). Before version 68 of firefox, I used firefox exclusively on all these devices, and was pretty happy. After the update, I had to swallow a bitter pill in regards to loss of most addons without resorting to work arounds, but still coped as ublock origin with some scripting and dark reader could do most stuff i needed. My android tablet was least used device, mostly using during travels. But when I did use it, firefox was just too cumbersome, and I finally switched to brave. The thing is, on android, there was nothing that firefox offered that brave didn't, so I switched to it on phones too. I stuck with firefox on desktop till quite some time, but now I have now almost exclusively switched to brave on both linux and windows, because its just a lot more convenient to have a single browser on all platforms.

The takeaway from all this is that, by compromising on one platform (a major platform for that matter), firefox is incentivizing users to switch on all platforms, even where it has feature parity. I doubt I would have bothered with any chrome derivative had I not been irritated  with lack of proper UI on a device I infrequently use.

**Comment by eloyperez** [comment] 2023-01-13 16:25
And it's not just tablets now. I have a Samsung Fold 3 folding phone with a glorious 2208 x 1768 screen, and the Firefox UI just doesn't cut it on this screen. Am using Vivaldi here too

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Kuvesz** [comment] 2023-01-13 16:49
I honestly think that the current UI is workable on tablets even if it's not exactly great and most likely the tablet/samsung fold users are a vastly outnumbered by even phone users so probably the devs have a lot more important stuff to deal with. (There's like over 400 issues with the bug label on them just in this repo, so I imagine they've got a lot on their plates.)
That being said it would be great if anyone from the development team could confirm if they are planning to do any work on this in the future or if this issue should be closed as won't fix or something.

**Comment by Shaurya-Kalia** [comment] 2023-01-13 17:46
> I honestly think that the current UI is workable on tablets even if it's not exactly great and most likely the tablet/samsung fold users are a vastly outnumbered by even phone users so probably the devs have a lot more important stuff to deal with. (There's like over 400 issues with the bug label on them just in this repo, so I imagine they've got a lot on their plates.)
> That being said it would be great if anyone from the development team could confirm if they are planning to do any work on this in the future or if this issue should be closed as won't fix or something.

What am I, or any other tablet user for that matter, gain from firefox that we compromise to use 'workable but not exactly great' UI? Why shouldn't they switch to a browser that offers a great UI and almost every feature that they expect from a browser? And while they are switching for just one of their tablet devices, why shouldn't they do the same for all other devices and avail features like sync?
Someone said that firefox's android share is already less and tablet users are already a minority so it is not a priority. I would like all people with such an opinion to reflect why it is the case in first place and can they actually build a marketshare alienating users by dividing them into sub-groups and declaring all those sub groups as minority.

Firefox (desktop) holds its last base in tinkerers and privacy fanatics/google haters. Firefox android even alienates the former. Thank god they at least allowed non-recommended addons in beta, even though the experience is still needlessly convulated, but still won't bother to provide about:config below nightly. I can see there is dearth of development resources, but what bothers me more is the decision making. When resources are less, you offload more stuff for community to figure out, not make it even more complicated for community to get involved. Most people can not contribute to firefox core, but they can contribute via addons, themes, configurations etc. If you think I am talking to clouds, take a look at this [addon](https://addons.mozilla.org/en-US/firefox/addon/tablet-ui-for-firefox/). Its far more functional than current 'workable but not exactly great' UI, but is unavailable to stable users, or anyone not wishing to create a mozilla account and mess with collections

**Comment by TheBrokenRail** [comment] 2023-01-13 17:54
> Firefox (desktop) holds its last base in tinkerers and privacy fanatics/google haters. Firefox android even alienates the former.

Firefox Desktop also alienates the former. You can't install extensions without Mozilla approving/signing them unless you use a less stable version. *Way* more iOS-esque than I like. It's my computer. Why is letting me install what I want so hard for Mozilla to understand?

**Comment by boek** [comment] 2023-01-27 02:19
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812934

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-27 02:19 UTC
Labels: feature request 🌟, needs:ac, b:tablet, Feature:Tabs, Feature:FennecTransition
