### ISSUE TITLE
FNX3-16568 ⁃ Option to disable screenshots in private mode

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#2768] opened 2019-05-23 05:35 UTC
## User Story
* As a user, I want the option to disable taking screenshots in private browsing mode, so I can further protect my privacy.

### Acceptance Criteria
* I can disable taking screenshots in private mode (off by default)
* When disabled in private mode, I am not able to take a screenshot and instead I see a system notification indicating that taking screenshots isn't allowed in private mode.
* I don't see the contents of my private tab in Android multitasking view

**Comment by topotropic** [comment] 2019-05-23 12:10
We should use a system notification, similar to what Focus does.

**Comment by vesta0** [comment] 2019-05-23 14:34
Sounds good @topotropic

**Comment by buttercookie42** [comment] 2019-05-24 10:37
Should this be configurable - not least for bug reports and suchlike?

**Comment by joebloggs7657** [comment] 2019-07-09 18:04
Could this not be an option? Being able to take screenshots in private mode doesnt exactly compromise the premise of private browsing. I will say from experience in Bromite that not being able to screenshot is more of a hassle than anything related to private browsing.

**Comment by yoasif** [comment] 2019-07-09 20:30
This should be an option - perhaps even default behavior, but an option nonetheless, imo.

**Comment by ekager** [comment] 2019-07-10 00:36
If we do this, I think we should make it off by default. From Focus experience, not all users understand or want this feature, and the ones that want it are probably more likely to understand how to seek it out.

**Comment by lime124** [comment] 2019-07-23 03:48
removing the ux label - this is on our radar already as it's part of Q3 plans.

**Comment by Djfe** [comment] 2019-08-07 12:25
this is the same bug as
#2248
#3422
#3707

I think 3 of the 4 bugs should be closed as duplicates :)

**Comment by NotWoods** [comment] 2019-09-30 03:16
I've started working on the blocking functionality in Android Components (mozilla-mobile/android-components#4551).

**Comment by NotWoods** [comment] 2019-12-23 07:07
The feature has been added and should be incorporated into `BaseBrowserFragment`, in a similar manner to our list of features inside that fragment.

**Comment by KaairaGupta** [comment] 2020-01-10 13:30
@NotWoods is the feature of disabling screenshots on private mode up? Or is there any work still left to do? I asked because this issue was still showing under the good first bugs. If there is any work, i would love to contribute.

**Comment by NotWoods** [comment] 2020-01-10 17:46
You can integrate SecureWindowFeature from the feature-privatemode component in our Android Components library. You'll need to edit BaseBrowserFragment and possibly the build.gradle & Dependencies.kt files.

**Comment by KaairaGupta** [comment] 2020-01-11 18:04
@NotWoods i can't seem to find this library in the code. Please help me with it.

**Comment by KaairaGupta** [comment] 2020-01-11 18:15
Also, should i add the option in the settings or in the three-dot-menu?

**Comment by ekager** [comment] 2020-01-11 18:57
AFAICT this issue still needs UX and strings for the Settings decsribed. I don't think this is ready to be worked on yet.

**Comment by ekager** [comment] 2020-01-11 18:58
@lime124 adding back the UX label because I don't see any mocks linked

**Comment by NotWoods** [comment] 2020-01-12 07:05
@ekager Could we land an always on option for now and introduce the toggle later? I think always off makes sense as a default.

@KaairaGupta Here is the docs for [`SecureWindowFeature`](https://mozac.org/api/mozilla.components.feature.privatemode.feature/-secure-window-feature/).

**Comment by ekager** [comment] 2020-01-12 07:08
@NotWoods see comments above. From my experience on Focus, users can find this feature really annoying and I think we should wait for a way for users to turn it off before introducing it. We can get input from @vesta0 though.

**Comment by vesta0** [comment] 2020-01-22 18:32
I agree that this should be a user option that is disabled by default. I see that it has the `needs:UX-feedback` label so let's wait for @brampitoyo  to provide feedback.

**Comment by lime124** [comment] 2020-01-23 23:03
So sorry I dropped the back let me loop in Amy as well @amylee

**Comment by brampitoyo** [comment] 2020-03-12 03:39
If the code’s complete and ready to land, let’s figure out a place in Settings to put it, and the right string to call it.

I agree with @vesta0 that we probably shouldn’t turn this option on by default.

One thing we have to keep in mind is the “unintended consequence” that turning this option on will also cause Fenix private mode not to show a screenshot in the app manager view – effectively hiding potentially incriminating content. It’s a nice privacy feature, and one that we ought to include when explaining this feature.

**Comment by AmyYLee** [comment] 2020-03-12 13:37
I would recommend putting this setting under Settings -> Private browsing and add a toggle to enable/disable. Adding @betsymi for strings

![image](https://user-images.githubusercontent.com/5992746/76527147-1bca8680-6445-11ea-9470-62f757909741.png)

**Comment by brampitoyo** [comment] 2020-03-18 00:59
Copy-pasting @betsymi’s response:

> This string can read: **Allow screenshots in private tabs**. And to confirm, should be OFF by default.

**Comment by BMEduard** [comment] 2020-04-01 07:52
Hello @AmyYLee @brampitoyo , I have a question regarding the scope of this feature. Should the screenshots be disabled only for tabs? 
The example for AC samples suggests this, but what about home, search and other screens, should they also be included?

**Comment by AmyYLee** [comment] 2020-04-01 14:00
> Hello @AmyYLee @brampitoyo , I have a question regarding the scope of this feature. Should the screenshots be disabled only for tabs?
> The example for AC samples suggests this, but what about home, search and other screens, should they also be included?



> Copy-pasting @betsymi’s response:
> 
> > This string can read: **Allow screenshots in private tabs**. And to confirm, should be OFF by default.

@betsymi Hi, as per discussion above, the consensus is that the default should be to allow screenshots in private tabs as not allowing screenshots 

Do you think we can modify the strings so it reads something like "Don't allow screenshots in private tabs" and have it OFF by default.

**Comment by AmyYLee** [comment] 2020-04-01 14:04
> Hello @AmyYLee @brampitoyo , I have a question regarding the scope of this feature. Should the screenshots be disabled only for tabs?
> The example for AC samples suggests this, but what about home, search and other screens, should they also be included?

I think for consistency we should not show home search and other screens as well if the user chooses this option. There still might be open tabs on homescreen that the user doesn't want exposed. What do you think? @brampitoyo

**Comment by brampitoyo** [comment] 2020-04-02 02:15
@AmyYLee is correct. If screenshot is blocked on private tabs, it means that screenshot should also be blocked on every other page, including in-content pages, in private mode.

I wonder if it’s more correct to call this feature “Allow/Don’t allow screenshots in private browsing”? This clarifies the scope. Screenshot is either allowed or blocked in all pages, not just on websites.

**Comment by sv-sdeiac** [comment] 2020-04-08 12:11
Hi, I can confirm that the new feature is implemented using the latest version of Firefox Preview Nightly 4/8 #20990609.
Also, I can confirm that the issue works properly. Disabling the option is blocking the device to take screenshots and it blanks the videos. Enabling the option allows the device to take screenshots and videos.

Devices:
- LG g7 fit (Android 8.1);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel 3 (Android 10).

**Comment by Poopooracoocoo** [comment] 2020-04-12 08:22
@brampitoyo said:
> One thing we have to keep in mind is the “unintended consequence” that turning this option on will also cause Fenix private mode not to show a screenshot in the app manager view – effectively hiding potentially incriminating content. It’s a nice privacy feature, and one that we ought to include when explaining this feature.

a subtext could be added to explain this. @BMEduard whaddya think?

**Comment by BMEduard** [comment] 2020-04-13 10:20
"I think this is a question for UX, @AmyYLee what do you think"?

**Comment by AmyYLee** [comment] 2020-04-13 13:42
> I think this is a question for UX, @AmyYLee what do you think?

Do you mean subtext in the private browsing home screen when the user has no tabs opened? Asking @betsymi for her input. 
<img width="394" alt="Screen Shot 2020-04-13 at 09 42 28" src="https://user-images.githubusercontent.com/5992746/79124814-1d9ca800-7d6b-11ea-918d-f71a95e72bb9.png">

**Comment by Poopooracoocoo** [comment] 2020-04-14 04:02
@AmyYLee no a subtext of the disable screenshot option that tells users that Fenix's content will be hidden in the app switcher

**Comment by AmyYLee** [comment] 2020-04-14 14:54
> @AmyYLee no a subtext of the disable screenshot option that tells users that Fenix's content will be hidden in the app switcher

Can you post the screen of what you are referring to?

**Comment by Poopooracoocoo** [comment] 2020-04-14 16:05
@AmyYLee 
![Screenshot](https://user-images.githubusercontent.com/51363864/79246027-4c766380-7ebc-11ea-949a-4c8837dbc3ed.png)
The "Allow screenshots in private browsing" option should also include a description that tells users that it also hides Firefox's content in the app switcher.

**Comment by Mugurell** [comment] 2020-08-12 07:20
Closing as per https://github.com/mozilla-mobile/fenix/issues/2768#issuecomment-610921742

**Closed by Mugurell** 2020-08-12 07:20 UTC
Labels: Feature:PrivateBrowsing, eng:qa:verified, eng:ready, needs:l10n
