### ISSUE TITLE
[Bug]swipe to close is very unprecise

### ISSUE THREAD

**Issue by FernandoMiguel** [mozilla-mobile/fenix#16870] opened 2020-12-05 10:43 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Go to tab list 
Swipe right to close a tab
### Expected behavior
Tab to close 
### Actual behavior
It just returns the swipe drag movement back to the normal state and tab remains in the list 
### Device information

* Android device: tested on pixel 3xl, 2xl and Sony 5ii
* Fenix version: Nightly 201204 17:01 (and it has been happening for at least a month)

**Comment by ekager** [comment] 2020-12-09 22:18
So if I'm understanding this, you think the swipe isn't sensitive enough?

**Comment by FernandoMiguel** [comment] 2020-12-09 22:51
> So if I'm understanding this, you think the swipe isn't sensitive enough? 

Yes

**Comment by sflorean** [comment] 2021-06-14 17:40
Tested on latest Nightly and the issue is not visible with Pixel 3, @FernandoMiguel this is still the case for you? Can you please attach a video, if it is the case? thank you!

**Comment by FernandoMiguel** [comment] 2021-06-14 17:41
It's much better

**Comment by SoftVision-LorandJanos** [comment] 2021-12-15 10:45
I couldn't reproduce this issue on the latest Nightly (2021-12-15).
Considering the author's last comment as well, I will close this ticket as fixed.

**Closed by SoftVision-LorandJanos** 2021-12-15 10:45 UTC
Labels: 🐞 bug, Feature:Tabs, wontfix, qa-triaged
