### ISSUE TITLE
[Bug] Custom DoH settings in about:config (Nightly) are ignored

### ISSUE THREAD

**Issue by rail01** [mozilla-mobile/fenix#17249] opened 2020-12-28 08:36 UTC
## Steps to reproduce

1. Using Nightly branch, go to `about:config` and set custom DNS over HTTPS (DoH) provider by changing: `network.trr.custom_uri` to DNS provider of choice, `network.trr.mode` to `2` or `3` and `network.trr.bootstrapAddress` to DNS provider's IP adress
3. Go to `about:networking` and under `#dns` tab check currently used DoH provider (Cloudflare)

### Expected behavior
Custom DNS over HTTPS settings are taking expected effect.

### Actual behavior
Custom DNS over HTTPS setting are being ignored and Cloudflare DNS endpoint (value of `network.trr.uri`) is always used instead.

### Device information

* Android device: Redmi Note 7 (Android 10)
* Fenix version: 201226 (Build #2015783691)

**Comment by MicroBeast** [comment] 2021-01-06 21:29
Custom DOH seem already work again.

Roughly since Nightly 210102 17:01 (Build #2015785035)

**Comment by lobontiumira** [comment] 2021-03-18 09:43
I will close this issue becausethe reporter hasn't provide more details.
Please feel free to open a new issue if this is still reproducing for you.

**Closed by lobontiumira** 2021-03-18 09:43 UTC
Labels: needs:triage, 🐞 bug
