### ISSUE TITLE
[Bug]Bookmark folder icons color inconsistency in dark mode

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4491] opened 2019-08-02 12:16 UTC
## Prerequisites
Have a clean profile

## Steps to reproduce
1. Select Select dark theme from onboarding screen
2. Navigate to any website
3. Add it to Bookmarks
4. Tap edit from the snackbar
5. Create a new folder
6. Check the bookmark folder icons

### Expected behavior
![rsz_1negru](https://user-images.githubusercontent.com/51314259/62369267-ba9a1680-b537-11e9-8c9a-86509f0feceb.png)

### Actual behavior
![rsz_gri](https://user-images.githubusercontent.com/51314259/62369280-c8e83280-b537-11e9-9d18-23c72e1e4b1a.png)

### Device information

* Android device: 
• Google Pixel 3a (Android 9)
• Moto G6 (Android 8)

* Fenix version: 
• RC 1.2-rc2
• Nightly Build #12140610 from 2/8

### Notes
► Video
![20190802_093112](https://user-images.githubusercontent.com/51314259/62369488-6f343800-b538-11e9-9070-38d2d2658f00.gif)

**Comment by ekager** [comment] 2019-08-06 16:56
Oops dupe of #4540 and is closed :)

**Closed by ekager** 2019-08-06 16:56 UTC
Labels: Feature:Bookmarks, Feature:DarkMode, P2, 🐞 bug
