### ISSUE TITLE
Add reader view to custom tab menu 

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#7535] opened 2020-01-08 08:59 UTC
Custom tab is heavily used by applications to read pages that could make very good use of reader view, but that option is not available in the menu (whereas desktop view is there)

**Comment by s-ankur** [comment] 2020-11-27 23:26
Duplicate of https://github.com/mozilla-mobile/fenix/issues/5691

**Comment by csadilek** [comment] 2020-12-17 03:13
Thanks, closing as dupe of #5691.

**Closed by csadilek** 2020-12-17 03:13 UTC
Labels: Feature:CustomTabs, Feature:MainMenu, feature request 🌟
