### ISSUE TITLE
Https only mode

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#16612] opened 2020-11-17 11:15 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
In latest Firefox v83 desktop, https only mode setting added under privacy settings. Can you please add the same in Firefox mobile? 

### How do you know that this problem exists today? Why is this important?
Currently this setting is missing or hidden under about:config. There must a setting under UI to turn on the feature. 

### Who will benefit from it?
All users 

https://blog.mozilla.org/security/2020/11/17/firefox-83-introduces-https-only-mode/

**Comment by 5trongthany** [comment] 2020-11-17 21:50
I can second that it would be a good feature to add, though I would also wager that the community has been vocal about a number of other things they would like implemented first. While I think this should be on the roadmap(if it isn't already), the need for it is somewhat mitigated by the HTTPS Everywhere extension being available for the app.

**Comment by cadeyrn** [comment] 2020-11-17 21:59
Duplicate of #14682 and of #12347 - which was also filed by you, @sheikh-azharuddin.

**Comment by kbrosnan** [comment] 2020-11-18 01:06
Closing as a duplicate

**Closed by kbrosnan** 2020-11-18 01:06 UTC
Labels: needs:triage
