### ISSUE TITLE
Unable to log into qBittorrent web interface

### ISSUE THREAD

**Issue by buongiorgio** [mozilla-mobile/fenix#16079] opened 2020-10-21 08:35 UTC
When trying to access some web applications (e.g. qBittorrent web gui), firefox is stuck on the access page. The same web application is accessible with other mobile browser (Chrome on Android, Safari on iPhone).

## Steps to reproduce
* Go to the log in page of qBittorrent
* Enter username and password
* Hit the login button

### Expected behavior
Should enter in the web gui of qBittorrent

### Actual behavior
The username and password fields are reset, firefox remains on the login page

### Device information

* Android device: Samsung S8 (SM-G950F), Android 9, path level 1st September 2020, One UI 1.0
* Fenix version: Firefox Daylight 81.1.5 (Build #2015769595)

**Comment by kbrosnan** [comment] 2020-10-22 09:19
Duplicate of #15235

**Closed by kbrosnan** 2020-10-22 09:19 UTC
Labels: Feature:Logins, 🐞 bug
