### ISSUE TITLE
[Bug] Fenix doesn't open Links

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#18225] opened 2021-03-01 08:56 UTC
## Steps to reproduce
0. "Open links in private tabs"
1. Get some way to click on this link: https://scryfall.com/card/2xm/321/high-market
For example, send it to yourself in the messaging App of your choice.
(It will probably work with other links as well but this is the one I used)
2. Click on the Link to open it in Fenix
3. Clicking on the task-manager-like button that android has and close Fenix
4. Go back to the messaging app and click on the link a second time.
5. See bug: The link isn't opened. A blank Fenix opens instead.

### Expected behavior
Open the Link

### Actual behavior
0 tabs are open, it's as if we opened the Browser the usual way.

### Device information

* Device vendor / model and Android version: Samsung Galaxy S9
* Firefox for Android version: 210227

**Comment by Glitchy-Tozier** [comment] 2021-03-01 12:27
This also work by using homescreen shortcuts.

**Comment by mcarare** [comment] 2021-03-02 14:30
Can QA please try to reproduce this? I am unable to, with the latest master.

**Comment by Glitchy-Tozier** [comment] 2021-03-02 15:06
I, too, can't reproduce this with todays version from the Play Store. Should I close the issue?

**Comment by mcarare** [comment] 2021-03-02 15:24
@Glitchy-Tozier QA will close it if they cannot reproduce it either. Thank you for your feedback!

**Comment by LaurentiuApahideanSV** [comment] 2021-03-03 12:09
I tried to reproduce the issue on Firefox Preview RC 86.1.1 and Nightly 210303 but was unable. I will mark this issue as closed.
### Devices used:
- Samsung Galaxy S9 (Android 9)
- OnePlus 6T (Android 9)

**Closed** 2021-03-03 12:10 UTC
Labels: eng:qa:verified, 🐞 bug

**Comment by Glitchy-Tozier** [comment] 2021-03-05 09:59
Okay, it still happens. It's just inconsistent now.

**Comment by Glitchy-Tozier** [comment] 2021-03-05 10:00
Okay, it still happens. It's just inconsistent now.
