### ISSUE TITLE
[Bug] Tab on home fragment does not have title

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2709] opened 2019-05-21 21:41 UTC
Currently it's possible to get in a state where the home fragment does not display a title or favicon for a partially loaded page. We should update the home fragment with the correct information when the session observer notifies us

I think the problem is that the session observer isn't created **before** navigating to the home fragment. That is: 

1. Home fragment (we're observing)
1. Browser fragment (page loading, not observing)
1. Press home
1. Page finishes loading
1. Get to home fragment without observing the `onTitleChanged`

## Demo
![demo 2019-05-21 14](https://user-images.githubusercontent.com/4400286/58132585-84a2f280-7bd6-11e9-9e61-8dc607b33af5.gif)UNITO-UNDERSCORE!41!UNITO-UNDERSCORE!22!

**Comment by softvision-miralobontiu** [comment] 2019-05-30 08:35
Closing this as dupe of #2254

**Closed** 2020-08-26 06:13 UTC
Labels: 🐞 bug
