### ISSUE TITLE
[Bug] Tab switching animation blanks out past outline of tab during animation

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#5708] opened 2019-10-01 17:03 UTC
## Steps to reproduce

1.Open a few tabs
2. tap the tab switcher / tab a tab from the home page

### Expected behavior

The animation as the tab gets smaller shows the tab getting smaller and larger. 

### Actual behavior

The tab animation first blanks out the entire screen, then compresses the tab (when switching to the home screen). 

When moving back into a tab, the tab doesn't animate in at all really, it just appears and expands. 

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

See https://i.imgur.com/3t8YoXz.mp4

**Comment by ekager** [comment] 2019-10-02 03:06
Closing as dupe of #4708 and we'll look into the animations with that investigation

**Closed by ekager** 2019-10-02 03:06 UTC
Labels: 🐞 bug
