### ISSUE TITLE
[Bug]: Firefox will not show favicon for apple.com

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#26061] opened 2022-07-17 19:25 UTC
### Steps to reproduce

Go to apple.com then tap the tab view button

### Expected behaviour

The apple.com tab should have the Apple favicon

### Actual behaviour

Instead of showing the Apple favicon, it just shows a letter "A" in a blue box (observe screenshot)
![Screenshot_20220717-151746](https://user-images.githubusercontent.com/47801466/179421644-22f1aef2-c6c0-49d2-a6d1-5494bca1eb13.png)

### Device name

Google Pixel 3a XL

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

104.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21033)

**Comment by SoftVision-LorandJanos** [comment] 2022-07-18 05:43
Hi @willfs84! Thanks for your report!
While I was ale to reproduce the issue, I found a closed duplicate one (#22932) which was closed because the the root issue was already covered here: https://github.com/mozilla-mobile/android-components/issues/10377.
Based on that info, I will close this issue as a duplicate.

**Comment by rocketsroger** [comment] 2022-07-27 20:47
Reopen for some updates needed to show larger icons correctly.

**Comment by LaurentiuApahideanSV** [comment] 2022-08-02 14:33
I tested the issue on Firefox Nightly 105.0a1 (2022-08-02). The favicon is displayed, however the Apple logo is very small.
![1659450488660](https://user-images.githubusercontent.com/50983519/182400255-7727612a-820c-41c3-b7f9-05ceafe503b4.JPEG)
![1659450426923](https://user-images.githubusercontent.com/50983519/182400257-8427a11d-17c4-4919-90c9-7313c7ac8881.JPEG)
### Devices used:
- Samsung Galaxy S22 Ultra (Android 12)
- Google Pixel 6 (Android 13)

**Closed by LaurentiuApahideanSV** 2022-08-02 14:33 UTC
Labels: 🐞 bug, eng:qa:needed, Feature:Tabs, S4, qa-triaged
