### ISSUE TITLE
[Bug] Crash when opening Fenix from Google search bar result

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#6029] opened 2019-10-15 15:48 UTC
## Steps to reproduce
- Developer options -> Background processes -> No background processes
- Make sure Fenix is the default browser
- Open Fenix and stay on HomeFragment with at least one other open tab
- Leave Fenix and search using the Google search bar
- Tap on a result to open in Fenix
- Hit back

### Expected behavior
- Back to search results

### Actual behavior
- Crash:

```
2019-10-15 11:40:56.062 18164-18462/? E/GeckoProcessManager: Cannot get pid for tab
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1129)
        at org.mozilla.gecko.process.IChildProcess$Stub$Proxy.getPid(IChildProcess.java:4)
        at org.mozilla.gecko.process.GeckoProcessManager$ChildConnection.getPid(GeckoProcessManager.java:2)
        at org.mozilla.gecko.process.GeckoProcessManager$ChildConnection.unbind(GeckoProcessManager.java:1)
        at org.mozilla.gecko.process.GeckoProcessManager.start(GeckoProcessManager.java:34)
        at org.mozilla.gecko.process.GeckoProcessManager.start(GeckoProcessManager.java:2)
2019-10-15 11:40:56.066 18164-18462/? E/GeckoProcessManager: Cannot restart child tab
```
### Device information

* Android device: Pixel 3a
* Fenix version: 2.2.0 and Nightly 191014

**Comment by csadilek** [comment] 2019-10-15 19:17
Filed in GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1588888

**Comment by cpeterso** [comment] 2019-10-29 06:38
The GV bug is a P3 because setting background process limit to 0 is an unusual device configuration. If you disagree, please let me know.

**Comment by kbrosnan** [comment] 2020-07-28 02:41
I cannot reproduce this on a Galaxy S8 or Pixel 3 using Firefox nightly. Closing, can reopen if it can be reproduced by others.

**Closed by kbrosnan** 2020-07-28 02:41 UTC
Labels: P3, b:crash, needs:gv, 🐞 bug
