### ISSUE TITLE
[Bug]: Status bar icons (top of screen) cannot be seen when Fenix powers webview in external apps (Kuroba/Boost/Telegram)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#20857] opened 2021-08-15 06:24 UTC
### Steps to reproduce

1. Open website in Kuroba/Boost/Telegram

### Expected behaviour

Icons in top status bar are easily visible 

### Actual behaviour

icons on the status bar can barely be seen.

In the case of Boost, even the bottom navigation bar icons are messed up. They appear unusually dim.

This only happens in Web View. When URLs are opened in the full Firefox app, both status and bottom navigation bar icons appear normal. Even tried switching to light mode, both on OS and browser level but still there's a similar sort of UI problem. 

The status bar on the top and the navigation bar on the bottom aren't visible when using PWAs. 

![image](https://user-images.githubusercontent.com/152493/129469249-ad5e5d3f-4983-4edf-bd7d-7c5fc3c6a69a.png)

![image](https://user-images.githubusercontent.com/152493/129469253-8bc45bf8-8e7f-4633-b492-37b25c5070ed.png)

### Device name

Samsung Galaxy S10+

### Android version

Android 9.0

### Firefox release type

Firefox

### Firefox version

91.1.0

### Additional information

From https://www.reddit.com/r/firefox/comments/p4jbbe/a_weird_ui_bug_that_appeared_in_the_latest/

This is a regression, previous version did not have this issue.

**Comment by vgnh** [comment] 2021-08-15 10:37
How the Twitter PWA looks now:
![twitter_pwa](https://user-images.githubusercontent.com/22466712/129475546-454339f6-f9b5-4ccd-b4dd-9d7547fcf25d.png)

Notice the white space on top (where the status bar is supposed to be), and the barely visible navigation buttons on the bottom bar.
This happened after the update to ver 91.1.0 (Build #2015826187).

**Comment by Nickoriginal** [comment] 2021-08-15 10:41
Looks like duplicate of #20494.

**Comment by vgnh** [comment] 2021-08-15 10:47
I don't think this is a duplicate, as it has nothing to do with themes. Besides the other one has been closed, while the issue still exists now.

**Comment by Mugurell** [comment] 2021-08-16 10:58
For me the Twitter PWA will mean white icons in a white status bar only when using a dark theme (on a Pixel3 with Android 12).
So the issue seems to be Android version / device dependent.
But happens in both Nightly and Release.
A custom tab for Twitter shows no such issue for me.

Would be helpful to have more links for situations in which the issue reproduces to find their common cause.

**Comment by vgnh** [comment] 2021-08-17 01:44
I found a weird temporary fix for this issue, for the PWAs.

So if I have 0 tabs open in the Firefox app, and then open the Twitter PWA, I don't get a status bar and the navigation buttons on the bottom bar is hard to see.

**Fix:** If I keep a Twitter tab open in the Firefox app, and then open the Twitter PWA, the PWA has the status bar and the navigation bar appears normal.

**Comment by jeremyjackson89** [comment] 2021-09-13 21:19
> I found a weird temporary fix for this issue, for the PWAs.
> 
> So if I have 0 tabs open in the Firefox app, and then open the Twitter PWA, I don't get a status bar and the navigation buttons on the bottom bar is hard to see.
> 
> **Fix:** If I keep ~a Twitter~ any website tab open in the Firefox app, and then open the Twitter PWA, the PWA has the status bar and the navigation bar appears normal.
> The Firefox app can be closed after opening a tab.

For me that makes the nav buttons at the bottom visibile, but the status bar up top is still completely white :/
![353e8485-b369-43c0-b816-47421353cd70](https://user-images.githubusercontent.com/8271117/133157724-425795e5-2a1d-4bca-9992-30d2849f038f.png)

Pixel 3 running Android 11.

**Closed** 2022-03-20 01:50 UTC
Labels: 🐞 bug, needs:triage, wontfix
