### ISSUE TITLE
[Bug]flash when opening app from recent screen or turning on the screen

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#13299] opened 2020-08-05 11:17 UTC
## Steps to reproduce
   Str1-
1. Start fenix and open a page.
2. Go to recent app screen on phone.
3. Open the app agian and observe.
      Or
Str 2-
Open a page and switch off the phone and switch on the phone and observe.
### Expected behavior
The app doesn't flashes and app comes on screen smoothly.
### Actual behavior
Opening app from recent screen causes a white flicker.
### Device information

* Android device: 8.0.0
* Fenix version: latest nightly

**Comment by jakefleming156** [comment] 2020-08-05 17:47
Duplicate of [#6313 ](https://github.com/mozilla-mobile/fenix/issues/6313)

**Closed by jakefleming156** 2020-08-05 17:47 UTC
Labels: needs:triage, 🐞 bug
