### ISSUE TITLE
FNX3-16704 ⁃ Sort bookmarks by most recent

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2961] opened 2019-05-29 08:19 UTC
## Steps to reproduce
1. Create a few bookmarks. 
Extra step: sync with a device that has a large list of bookmarks.
1. Go to library>bookmarks. Verify the way they are sorted.
    1. Expected behavior
Most recent bookmarks should be at the top.
    1. Actual behavior
Bookmarks are sorted in the order they are created. 
If you have a large list and no way to search, sorting by most recent would be helpful.
    1. Device information

* Android device: 
* Fenix version: 5/28

**Comment by vesta0** [comment] 2019-05-30 22:06
Working as intended. UX to take into consideration.

**Comment by topotropic** [comment] 2019-07-10 13:46
Yes, I agree that it makes sense to sort after creation date to help people to find their new bookmarks quicker. Sorry for the oversight.

**Comment by colintheshots** [comment] 2019-07-17 20:06
Are we doing this? We're supporting desktop bookmarks, including separators, and users often arrange their own bookmarks carefully. Sorting bookmarks would require more UX input. What do we do with separators, i.e. do we hide them or do they fall to the bottom? Do we only sort mobile bookmarks or also desktop bookmarks? Do we sort bookmark folders by time of use as well?

**Comment by ekager** [comment] 2019-07-17 21:14
Just dropping by to say that separators (and a strict bookmark arrangement in general) are also creating an issue for #2792

**Comment by sblatz** [comment] 2019-07-19 21:33
This is actually a feature request

**Comment by vesta0** [comment] 2019-07-22 16:48
@sblatz wondering why you changed the priority from P2 to P3? If it's a feature enhancement then it may get a feature priority not a lower P priority.

**Comment by ekager** [comment] 2019-07-22 16:51
@vesta0 this is up to you. If you read above this is pretty complicated. We are syncing and presenting the user with the exact folder structure, order, and dividers that they can see on desktop. If we start sorting we would probably have to remove the separators at the minimum. See #2792 for another bookmark sorting issue.

**Comment by yoasif** [comment] 2019-07-22 17:51
This is not how Fennec does this, nor Bromite. Desktop Firefox has a "Recently Bookmarked" section if the user is using the Library toolbar icon, but not the standalone bookmarks toolbar icon or the bookmarks sidebar.

I'm not sure it is worth breaking how bookmarks work across most browsers. 

A recently bookmarked list reminds me a bit of Highlights on Fennec and Desktop -- maybe that is where to repurpose this ticket?

**Comment by vesta0** [comment] 2019-07-23 05:03
Thanks for the explanations @ekager and @yoasif !

**Comment by vesta0** [comment] 2019-07-23 05:05
Closing this ticket as the browser is currently behaving as intended and this is not a bug.

**Comment by topotropic** [comment] 2019-07-23 11:31
@vesta0 I agree that it works as intended which doesn't mean it's ideal – should we track this as feature request for bookmarks and give it a low priority so that we can revisit it later when we work on something related?

**Comment by vesta0** [comment] 2019-07-23 16:02
@topotropic if you think this is a good feature to have, then feel free to re-open it. I closed it because this was not a feature request, it was marked as a bug found by QA. And after more investigation I don't think users expect this behaviour.

**Comment by cadeyrn** [comment] 2019-07-28 15:24
I created for #4347 to address the use case to find you recent bookmarks because Firefox for Apple iOS now has this feature, too.

**Closed** 2020-08-18 00:23 UTC
Labels: P3, eng:ready, feature request 🌟
