### ISSUE TITLE
Bring back "about:config" for mobile devices

### ISSUE THREAD

**Issue by msdobrescu** [mozilla-mobile/fenix#17154] opened 2020-12-20 16:07 UTC
Please add about:config back to Firefox for mobile devices to help tune it when needed.

**Comment by sheikh-azharuddin** [comment] 2020-12-21 05:11
Available in beta and nightly version

**Comment by msdobrescu** [comment] 2020-12-21 06:05
Sorry, don't use those two, I need it regardless the branch.

**Comment by cadeyrn** [comment] 2020-12-21 08:40
Duplicate of #7865.

**Closed** 2020-12-21 08:46 UTC
Labels: needs:triage

**Comment by msdobrescu** [comment] 2020-12-21 08:54
The about:config feature is not related to debug, but to fine tune.
I don't think this is a duplicate because it is another reason than the other bug, even though the same solution to fix.
It's comfortable to you to assign it as duplicate while the other issue is closed to comment.
No wonder why this browser goes down in users' preferences.

**Comment by cadeyrn** [comment] 2020-12-21 08:59
> I don't think this is a duplicate because it is another reason than the other bug

Even if the opener of the other issue has another motivation for using about:config it's about exactly the same feature so it's a clear duplicate.

>  No wonder why this browser goes down in users' preferences.

Such comments are not helpful if you want to see this implemented. Please be polite and constructive. With such sentences, you achieve at most the opposite.

**Comment by 0x391F** [comment] 2020-12-26 14:35
OK. I want to talk about this for a long time. 
Why users need about:config? 
If you want to enable DNS over HTTPS, you only need to set network.trr.mode = 3 and set network.trr.uri = https://<DNS Server>/dns-query ;
If you want to disable WebRTC to prevent leaking IP address when you're using a proxy, you only need to set media.peerconnection.enable = false, without any plugin (Google Chrome needs a plugin to disable it); 
Yes, these are little changes, but it's very, very convenient to change them through about:config. Now I'm bearing using Firefox without it. I'm a fans of Firefox, so I still using it.
