### ISSUE TITLE
Searching history vs bookmarks

### ISSUE THREAD

**Issue by davimack** [mozilla-mobile/fenix#22909] opened 2021-12-19 18:57 UTC
It would be useful to be able to search bookmarks and history independently.  It might make sense to include a search box at the top of the history tab, and maybe an option for searching bookmarks only, from the URL bar.

The problem: I know I read it today but I've got a bajillion bookmarks with similar terms. Or, I know I've bookmarked it but I don't want to clear history to find the bookmark.

**Comment by sflorean** [comment] 2021-12-27 12:16
@davimack Thank you for report!
This issue is covered in the following tickets: 
- bookmarks: #12717
- history: #10046 
I will close this as duplicate of the first one, based on the problem mentioned above.

**Closed by sflorean** 2021-12-27 12:16 UTC
Labels: needs:triage
