### ISSUE TITLE
[Bug] Firefox Fenix does not show synced tabs from iPad

### ISSUE THREAD

**Issue by katrikm** [mozilla-mobile/fenix#15998] opened 2020-10-17 18:43 UTC
## Steps to reproduce
Open Firefox on iPad.
Login to Firefox account and turn on syncing of Open Tabs.
Open some website (and manually hit sync button to be sure).
Open FIrefox on other device. Manually sync to be sure. And then view synchronized tabs from other devices.

### Expected behavior
To be able to see open tabs from iPad in Firefox fenix on Android devices.

### Actual behavior
I'm able to see synced tabs from iPad on Firefox for Windows (every Windows machine I tried).
I can't see synced tabs from iPad on Firefox for Android (Fenix) (same behavior on every Android device I tried). I can see tabs from other devices (from several devices running Windows and Android), but not from iPad. I tried this on multiple Android devices (Pixel 4 XL, Nexus 6, Nexus 7).
I even tried fresh install of Firefox beta for Android on Pixel 4 XL. But result is the same.

### Device information

* Android device: Pixel 4 XL. Android 11, Official stock firmware: Build number RP1A.201005.004
* Fenix version: 81.1.4 and 82.0.0-beta.6

* Android device: Nexus 6. Android 10, Lineage OS, Build: lineage_shamu-userdebug 10 QQ2A.200405.005
* Fenix version: 81.1.4

* Android device: Nexus 7. Android 10, Lineage OS (unofficial ROM), Build: lineage_flo-userdebug 10 QQ3A.200805.001
* Fenix version: 81.1.4
 
Source device:
* iPad mini 5. Software version 14.0.1
* Forefox for iOS. Version 28.2 and 29.

**Comment by liuche** [comment] 2020-10-21 23:47
not send tab but synced tabs - might be helpful if there is something different about the ios sync client cc @jonalmeida

**Comment by jonalmeida** [comment] 2020-10-22 05:14
I don't think iOS is using the remote tab component because I don't see [iOS bindings here](https://github.com/mozilla/application-services/tree/main/components/tabs) like other shared components.

In iOS [this](https://github.com/mozilla-mobile/firefox-ios/blob/76faae8c6c94e22c8fbc0de72e2d06f615738e2c/Sync/Synchronizers/TabsSynchronizer.swift#L94) is the only remote tab syncing code I can find, but @eoger would know better.

**Comment by jonalmeida** [comment] 2021-03-30 23:32
Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/16989.

**Closed by jonalmeida** 2021-03-30 23:32 UTC
Labels: Feature:SyncTabs, 🐞 bug
