### ISSUE TITLE
[Bug] Choosing alternate search shortcut results in too many search suggestions

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#5961] opened 2019-10-11 17:22 UTC
## Steps to reproduce

case (1):- Tap URL bar to enter search screen. Don't select an alternate search provider - use Google default. Type "fa". Get 3x search suggestions "fa" "facebook" "fashion nova" then some stuff from History

Repeat but this time

case (2):- Tap URL bar to enter search screen. **Select Bing as search provider by tapping search shortcut**. Type "fa". Get about 20 search suggestions some from Bing, some from Google, many are duplicates eg "fa" appears 5 times from Bing and once from Google

In some way it appears cumulative, if I delete "fa" and select amazon.co.uk without leaving the search screen and re-enter text "fa" I get results from Bing AND Amazon AND Google.

If I leave the search screen and re-enter it by tapping the URL bar, the accumulation of search suggestions resets back.

I don't think it's a Bing issue, I see the same behavior for amazon.co.uk, duckduckgo.

### Expected behavior

If I select Bing I should get 3x distinct search suggestions from Bing and then History suggestions. Should not get any Google suggestions at all

### Actual behavior

Get a bunch of duplicate Bing suggestions AND some Google suggestions AND sometimes more

### Device information

* Android device: Galaxy S7 
* Fenix version: Today's Nightly

![Screenshot_20191011-181157_Firefox Nightly](https://user-images.githubusercontent.com/40568887/66671421-d9add680-ec53-11e9-8f46-ff4d4739cb96.jpg)

![Screenshot_20191011-181318_Firefox Nightly](https://user-images.githubusercontent.com/40568887/66671432-ddd9f400-ec53-11e9-83c2-1cfaeab71886.jpg)

**Comment by mcarare** [comment] 2019-11-26 15:50
For QA: Please check if the issue currently reproduces. I could not reproduce it. TY!

**Comment by Cheap-Skate** [comment] 2019-11-26 16:42
I can't reproduce either, I think it got fixed when the behavior changed back to Shortcuts button pressed by default.

**Comment by abodea** [comment] 2019-11-26 16:50
Verified as fixed on the latest **Nightly build 11/26 with Google Pixel 3a XL(Android 10).**
Note that I tried to reproduce this issue with the following:
- Google
- Bing
- Amazon.com
- DuckDuckgo
- Wikipedia

Everything works as expected I had only 3 results.
Thanks @mcarare and @Cheap-Skate.
Based on my comment and the comments from above I will close this issue.

**Closed by abodea** 2019-11-26 16:50 UTC
Labels: Feature:Search, eng:qa:needed, 🐞 bug
