### ISSUE TITLE
Fenix should append a space to suggested prefill entries when tapping arrow

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#16135] opened 2020-10-22 19:32 UTC
- [ ] AC issue: https://github.com/mozilla-mobile/android-components/issues/7895

[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

1. Type in a string like "apple sto"
2. tap on arrow next to "apple store"
3. type a postal code

What happens:

the query becomes "apple store10010" instead of "apple store 10010"

Being able to continue a search query from a suggestion without needing to type a space seems more intuitive and is the behavior in Chrome. 

### How do you know that this problem exists today? Why is this important?

[Reports ](https://www.reddit.com/r/firefox/comments/jg3w41/can_we_expect_a_space_after_pressing_the_arrow_to/) on social media. It is important because this is likely more friction than the alternative, and will result in user dissatisfaction. 

### Who will benefit from it?

Users who are used to other browsers, users who "continue" typing a phrase rather than a word.

**Comment by cadeyrn** [comment] 2020-10-22 21:37
Duplicate of the AC issue https://github.com/mozilla-mobile/android-components/issues/7895.

**Closed** 2021-10-31 22:47 UTC
Labels: needs:ac, Feature:Search, wontfix
