### ISSUE TITLE
Add option to move tab from PBM to normal mode

### ISSUE THREAD

**Issue by kleinph** [mozilla-mobile/fenix#14994] opened 2020-09-11 17:08 UTC
### What is the user problem or growth opportunity you want to see solved?

There is no easy way to move (or reopen) a tab from private browsing mode into the normal browsing mode other than copying the URL.

### How do you know that this problem exists today? Why is this important?

If opening 3rd party links in private browsing mode is enabled, it is convenient to have an option to easily move tabs to normal mode. E.g. because there already exists a login session.

See also [this comment](https://github.com/mozilla-mobile/fenix/issues/514#issuecomment-514989742) from the "open 3rd party links in PBM" issue.

### Who will benefit from it?

Everyone who uses the feature to open 3rd party links in private browsing mode.

**Comment by liuche** [comment] 2020-09-17 01:16
Dupe of #5170

**Closed by liuche** 2020-09-17 01:16 UTC
Labels: needs:triage
