### ISSUE TITLE
FNX-5449 ⁃ Native Dark Theme

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#209] opened 2019-01-20 20:08 UTC
User Story:
As a user, I want to select a browser theme that is dark or light so that it can match my default dark or light Android theme or differ from my default theme.

Acceptance Criteria
User will find enough visual contrast on both light and dark themes because they meet a11y standards
User can change themes between dark and light
User can allow Fenix to select the theme that matches their default Android theme

Note - this feature is no longer part of Battery Saving and will need UX spec for settings### Why/User Benefit/User Problem

Users want a dark theme and will switch browsers to get it. 

### What / Requirements
* Option in setting UI under "Appearance" with "Theme" and options "Light, Dark, Default" 
* Default would be based on #208 

### Acceptance Criteria (how do I know when I’m done?)
User can select a dark theme in settings and have the UI changed based on this preference. 

### Considerations
This can get weird if Fenix will support themes available on AMO -- right now, these seem to get categorized under "add-ons" in Fennec, but a theme section may make more sense like exists in Firefox desktop under customize.

**Comment by vesta0** [comment] 2019-04-01 03:45
Duplicate of #1153

**Closed** 2020-08-11 13:51 UTC
