### ISSUE TITLE
[Bug] Not all bookmarks are synced correctly

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5814] opened 2019-10-07 12:01 UTC
## Prerequisites
Make sure Bookmarks and History are both selected to sync in your FxA account.

## Steps to reproduce
1. Sign-in on Fennec with valid credentials.
2. Create some bookmarks.
3. Sign-in on Fenix with the same account from step 1 and trigger sync.

### Expected behavior
All the created bookmarks are visible in the exact folder they were saved, no duplicates.

### Actual behavior
On Fenix, one of the bookmarks is displayed outside the folder in which it was saved. Some bookmarks aren't synced at all.

On Desktop, the user has to disconnect and reconnect in order for the sync to work.
On iOS, after sync, the bookmarks were displayed exactly like on Fennec.

### Device information
* Android device: Nokia 6 (Android 7.1.1) - Fenix, Samsung Galaxy Note 8 (Android 9) - Fennec, 
* iOS 12SE - Fennec
* desktop - Windows 10 - Firefox
* Fenix version: 1.0.1941 from 10/7

![Untitled](https://user-images.githubusercontent.com/40694158/66309477-67b35580-e912-11e9-9aa8-ecc567e007ff.png)

[logcat-sync.txt](https://github.com/mozilla-mobile/fenix/files/3701477/logcat-sync.txt)

* Note: after triggering several syncs, disconnecting, reconnecting, all the bookmarks were synced correctly.

**Comment by linacambridge** [comment] 2019-10-16 17:39
Hi @softvision-miralobontiu, thanks for the report! Unfortunately, we need a bit more information to figure out the next steps.

* Could you please describe the bookmark structure you created on Fennec in step (1)? For example, any folders, duplicate URLs, and so on? In the screenshot, it looks like you created a "CWTS" folder with two bookmarks?
* Is that logcat from Fennec or Fenix? I didn't see any mention of `sync15` or `places::bookmark_sync` in it (or anything else Sync-related, like `SyncWorker`), but having those logs would be super helpful. Is there a special option we need to flip to enable detailed logging?
* Did you already have Desktop connected to the account, or did you connect it after step 3?
* On Desktop (which version of Firefox are you using?), could you please install the [About Sync add-on](https://addons.mozilla.org/en-US/firefox/addon/about-sync/), follow the instructions [here](https://wiki.mozilla.org/CloudServices/Sync/File_a_desktop_bug#Get_detailed_Sync_logs) to enable detailed logging, trigger a sync, and upload the log? If you're on Firefox Release, could you also please open `about:config`, flip `services.sync.engine.bookmarks.buffer` to true, restart Firefox, and sync again? (It should be `true` already on Nightly), and see if you notice a difference?

> On Desktop, the user has to disconnect and reconnect in order for the sync to work.

Did you mean the bookmarks never sync, Sync doesn't work at all, or something else?

**Comment by softvision-miralobontiu** [comment] 2019-10-17 12:28
Hi @linacambridge 
I was able to reproduce this issue with the following:
- on Desktop - RC 70.0
- on Google Pixel (Android Q) - RC v2.2.0-rc.2 build #12891716
- on Huawei Honor 8 (Android 7) - Firefox Nightly (Fennec) 68.2a1 (2019-10-15).

I signed-in on all three devices. I added About sync add-on on desktop. I set the service.sync.engine.bookmarks.buffer to true on desktop (there were no differences when the pref was true or false).

Not 100% reproducible STR:
1. On Fenix, I deselected Bookmarks and History, and triggered sync.
2. On Fennec I triggered sync. 
3. On Desktop I triggered sync.
4. Verified that Bookmarks and History are deselected on all 3 devices.
5. Cleared the profile ONLY on Fenix!
6. Signed-in with the same account from step 1. 
7. Selected to sync only Bookmarks. Triggered sync.
8. Triggered sync on Desktop and Fennec.
9. Verified that only Bookmarks is selected on all 3 devices.
10. Verified the Bookmarks folders to see if I had the same folders.

**Results**
The folders should have been, in this case, "wiki" and "abcde". 
On Fennec the folders were ok, on Desktop there was an extra folder, on Fenix non of the mobile folders were displayed. 
The folders were displayed again on Fenix, only after I saved a new bookmark!

**Fennec**:
![fennec](https://user-images.githubusercontent.com/40694158/67008410-12392e80-f0f2-11e9-9f0c-115cc219a01b.png)

**Fenix**:
![fenix1](https://user-images.githubusercontent.com/40694158/67008417-16654c00-f0f2-11e9-8126-a9e07b588d03.png)

**Desktop**:
![Screenshot_1](https://user-images.githubusercontent.com/40694158/67008426-19f8d300-f0f2-11e9-9603-87b9a9f9c1fa.png)

**Comment by liuche** [comment] 2019-11-21 23:57
Removing from Fenix Kanban bc it's not actionable for Fenix team.

**Comment by sblatz** [comment] 2020-01-06 18:26
Discussed this in AC triage. @grigoryk's first guess is that we're not properly refreshing the view but we probably have the data. 

I believe @Baron-Severin also refactored this recently so this may not be an issue anymore. 

QA can you please verify this is still happening?

**Comment by grigoryk** [comment] 2020-01-06 18:29
> @grigoryk's first guess is that we're not properly refreshing the view but we probably have the data.

Specifically, the following comment is why this is my first guess: "The folders were displayed again on Fenix, only after I saved a new bookmark!". This sounds like a problem with a DB->UI pipeline, not the data (read: sync) problems.

**Comment by abodea** [comment] 2020-01-08 09:43
Verified as fixed on the latest Nightly build from 1/8 using Samsung Galaxy S10+(Android 9).
Note that I tried the steps from the description and this [comment](https://github.com/mozilla-mobile/fenix/issues/5814#issuecomment-543150944).
As this issue was not 100% reproducible, in case we will see it again, we will open a new bug.
Based on my comment I will close this issue.

**Closed by abodea** 2020-01-08 09:43 UTC
Labels: Feature:Sync, P2, eng:qa:needed, needs:ac, 🐞 bug
