### ISSUE TITLE
~1+ s delay when touching the navigation bar on Pixel 5a (with long string in clipboard? WebURLFinder)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21291] opened 2021-09-14 21:13 UTC
_Report via SUMO: https://support.mozilla.org/en-US/questions/1348730_

> Problem occurs immediately upon opening the navigation bar - the keyboard takes a few seconds to appear and input does not appear immediately in the bar. This occurs with both Gboard and SwiftKey. Keyboard display is also laggy, with the highlighted keys taking time to revert to standard appearance. 
> 
> Changing the search engine (tested Bing, DuckDuckGo, and Wikipedia) and disabling all suggestions/alternate input methods does not seem to affect behavior, lag is still present. Autocorrect suggestions appear with no lag and pressing enter/return immediately attempts to load the autofilled page or search, even if the text is not fully visible in the navigation bar.   
> 
> Problem is present using Firefox 91.3.1 and Nightly 93.0a1 on Android 11 on a Pixel 5a. 
> 
> This is a fresh installation of Firefox with no account synced, and I have cleared the cache and storage for the apps after encountering the problem.
> 
> Problem does not occur using Firefox Focus 91.3.0. The only search engines on Focus I tested were Google and DuckDuckGo, but I tested with and without search suggestions. Problem also does not occur with Google Chrome. 
> 
> Happy to help with additional tests and/or videos.

---

Follow-up comment with profiles:

> The navigation bar lag has happened again. 
> 
> I recorded a log in Nightly, with the following actions: 
> 
> 1. Touch address bar. 
> 2. Type in "test." 
> 3. Hold backspace to delete "test." 
> Waiting ~5 seconds in between tasks. 
> 
> https://share.firefox.dev/3k7a2zP
> 
> I rebooted my phone and tried again, this made the lag go away. I repeated the same actions. 
> 
> https://share.firefox.dev/3A6QMIc
> 
> It looks like there are large spikes in the AndroidUI category graphs.
> 
> If it also helps, I took a log without specific timings and typed more things into the search bar. https://share.firefox.dev/3k4ReRK

**Comment by mcomella** [comment] 2021-09-15 20:56
Triage: we're concerned this might affect ever user of the Pixel 5a. If this device is about to roll out, it's going to affect a lot of people.

**Comment by csadilek** [comment] 2021-09-16 15:49
The problem here is that we're parsing the clipboard text synchronously on the main thread and also doing that too many times (every time the `SearchDialogFragmentStore` changes): https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt#L352

We shouldn't block the main thread for this operation. So parsing the URL async and adding it to the store would solve this. This would already cause `updateClipboardSuggestion` to be invoked when parsing completed.

**Comment by mcomella** [comment] 2021-09-17 17:26
PR: https://github.com/mozilla-mobile/fenix/pull/21334

I believe https://github.com/mozilla-mobile/fenix/issues/18142 is a dupe of this so I updated the title accordingly.

**Comment by mcomella** [comment] 2021-09-17 18:44
Since we're still doing the long running task and that could result in unnecessary power draw, I filed https://github.com/mozilla-mobile/fenix/issues/21363 as a probably lower priority follow-up.

**Comment by csadilek** [comment] 2021-09-17 20:06
OK, I tested more and profiled to verify that the `WebURLFinder` calls (which clearly are the cause for the slow down in the linked profiles) are now gone. So they no longer run on the main thread, and we also only run them once per view. I will go ahead and close this, and will discuss uplifting this fix as well.

**Closed by csadilek** 2021-09-17 20:06 UTC
Labels: eng:performance, needs:triage, perf:P1
