### ISSUE TITLE
(feature request) matching active tabs should appear on top of search suggestions

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#19983] opened 2021-06-12 20:53 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Open/active tabs, indicated with a green tab label,appear below search suggestions. They should appear above. It does not fit their purpose of re-discovering opened tabs. 

These active tab entries are usually outnumbered by search suggestions in the address bar. Users have to scroll all the way down to discover them, if they are lucky.

Above all, this feature exists to optimize workflow. Users generally wish to prevent duplicate tabs, limiting the need for spave reserved for search suggestions.

To prevent unecessary matches, the scope of the active tabs entries could be limited to matching domain names. Content matches could then appear below search suggestions, for more context-aware sorting.

### How do you know that this problem exists today? Why is this important?
Users will skip over this feature because it doesn't fit into their screen.

### Who will benefit from it?
Users wishing to speed up their work flow by returning to the tab they were looking for instead of wasting time loading a duplicate tab.

**Comment by lobontiumira** [comment] 2021-06-14 05:57
This is a dupe of #13833

**Closed by lobontiumira** 2021-06-14 05:57 UTC
Labels: Feature:Tabs
