### ISSUE TITLE
Search engines are not convenient as before

### ISSUE THREAD

**Issue by JonDous** [mozilla-mobile/fenix#20469] opened 2021-07-22 09:07 UTC
Firefox before 70 version had a very convenient search engines. After big update the behavior was changed. And now it's really inconvenient and people are disappointed.

<70 version: click on address bar, type a request, click on a search engine icon. 
>70 version:
1. When "show search engines" on: click on address bar, click on engine, type a request, press enter. 
But(!) click on address bar, type a request, click on search engines button, click on search engine, press enter. 
2. When "show search engines" off: click on address bar, type a request, click on search engines button, click on search engine, press enter. 
or: click on address bar, click on search engines, click on search engine, type a request, press enter. 

I really hope you understand that now you force users to make more (really more) actions! 

ps Vivaldi browser has copied old Firefox behavior and people in Russian community started to migrate.
pps Old view of engines was more friendly. Nowadays list of engines is not so convenient. Also search suggestions before were not in list as now and we can see more suggestions, more history than now. 
![Search-bookmarks-252x439](https://user-images.githubusercontent.com/68903949/126614656-f090244f-3c31-43f8-a159-545549eb7722.jpg)

**Comment by cadeyrn** [comment] 2021-07-22 09:14
Duplicate of #19913 and others.

**Comment by kbrosnan** [comment] 2021-07-22 15:37
Closing as duplicate

**Closed by kbrosnan** 2021-07-22 15:37 UTC
Labels: needs:triage
