### ISSUE TITLE
[Bug] URL search bar and Navigation device bar are overlapped when tapping back from landscape mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#7062] opened 2019-12-10 15:11 UTC
## Steps to reproduce
1. Launch Fenix.
2. Tap on the URL bar(let the URL bar empty)
3. Rotate the device in landscape mode.
4. Tap on the device back button.
5. Rotate the device in portrait mode.
### Expected behavior
The URL search bar and Navigation device bar should not be overlapped.
### Actual behavior
Tapping back from landscape mode will overlap the URL and Navigation bar.
### Device information

* Android device: **Google Pixel 3a XL(Android 10).**
* Fenix version: **Latest Nightly 12/10.**

### Note
Only after restarting the app the URL search bar and Navigation bar are displayed correctly.

![ezgif-6-f345af5dc8cd](https://user-images.githubusercontent.com/42831109/70541383-9696b380-1b6f-11ea-95f0-862f59dafb65.gif)

**Comment by abodea** [comment] 2019-12-10 15:29
I was able to reproduce this issue without accessing the URL bar only by rotating the device a few times from landscape to portrait.

**Comment by AndiAJ** [comment] 2019-12-12 15:37
Hi, as per the issue encountered by @boek in [# 4107](https://github.com/mozilla-mobile/fenix/issues/4107#issuecomment-564801636) I've re-tested this issue on the latest **Nightly Build #13460608 from 12/12**.

:point_right: **The issue is reproducible** on the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Motorola V20 (Android 7.0)
• LG K10 (Android 7.0)
• Motorola G4 (Android 6.0.1)
• OnePlusA3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video from Google Pixel 3a
![20191213_165614](https://user-images.githubusercontent.com/51314259/70724445-49e3e180-1d03-11ea-8bde-117d04f8ca6d.gif)

:point_right: **Not reproducible** on Asus Nexus 7 (Android 5.1.1)
► Video 
![20191212_170726](https://user-images.githubusercontent.com/51314259/70724708-bd85ee80-1d03-11ea-94c9-8cf925940772.gif)

►**Note** 
I've noticed that when the Asus Nexus 7 is rotated in landscape mode **the device buttons always follows the device position, namely they will move to the bottom side of the device**.

Whereas on the other devices when rotating the device in landscape, **the device buttons move to the left or right side of the device** (depending on the rotation direction)

**Comment by mcarare** [comment] 2019-12-16 14:15
Closed by reverting the fullscreen home: #7152

**Closed by mcarare** 2019-12-16 14:15 UTC
Labels: Feature:Search, S1, b:landscape, 🐞 bug
