### ISSUE TITLE
[Bug] Cannot edit bookmark folder (Not fixed in 4/21 build)

### ISSUE THREAD

**Issue by nikoloskid** [mozilla-mobile/fenix#2536] opened 2019-05-15 20:26 UTC
## Steps to reproduce
1. Open tab
1. Chose to Bookmark the opened tab
1. Click on FOLDER to save it it to another "folder" instead of default "folder" mobile.
1. Firefox Fenix crashes

### Expected behavior
* When you editing bookmark, there should be a choice to add "FOLDER" or to save it in the default mobile.

### Actual behavior
* When you try to edit bookmark and it's folder, app crashes.

### Device information
* Android device: Huawei P20 Lite
* Fenix version: 1.0.1920

**Comment by ekager** [comment] 2019-05-15 20:28
Fixed today by #2526

**Comment by LittleAngelwings** [comment] 2019-05-15 20:29
Dupe of https://github.com/mozilla-mobile/fenix/issues/2504

**Closed** 2020-08-26 05:48 UTC
Labels: 🐞 bug
