### ISSUE TITLE
[Bug] Deleted bookmark's domain still shows up as a search suggestion

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#16157] opened 2020-10-24 12:09 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Bookmark a website whose domain you have not bookmarked before (e.g. https://example.com/).
2. Delete the bookmark.
3. Search for the domain in the address bar.

### Expected behavior

The deleted bookmark is deleted permanently, including its domain. Thus, it does not show up as a search suggestion.

### Actual behavior

The deleted bookmark's domain still shows up as a search suggestion. This is kind of similar to #8531, which is about deleted history (which has already been fixed).

![](https://user-images.githubusercontent.com/45960387/97081344-73b0a900-1634-11eb-99ef-b1eba10c0884.jpg)

### Device information

* Android device: Oppo Reno 2
* Fenix version: Nightly 201023 17:03 (Build #2015771403)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8483)

**Comment by hwinnemoe** [comment] 2020-10-25 11:01
See also #14782

**Comment by liuche** [comment] 2020-10-29 03:11
Did you delete this item from your history? This sounds like a dupe of #14782.

**Comment by SL-Lee** [comment] 2020-10-29 03:49
These steps to reproduce was performed in **Private Browsing Mode**, so no history was collected. #14782 is about deleted *history*, while this issue is about deleted *bookmarks*, so this issue is not likely to be a duplicate of #14782.

**Comment by liuche** [comment] 2020-10-29 22:17
Okay, so you don't have sync set up?

**Comment by SL-Lee** [comment] 2020-10-29 23:18
I do have sync set up. However, I have configured Firefox on my other devices to not remember history (on desktop) and have always browsed in Private Browsing mode (on mobile), so it still would not be possible for site history to originate from one of my other devices.

**Comment by ekager** [comment] 2020-12-18 06:37
Filed https://github.com/mozilla/application-services/issues/3784

**Comment by SL-Lee** [comment] 2021-06-16 10:59
This bug still reproduces on **90.0.0-beta.3 (Build #2015815723** and **91.0a1 (Build #2015816523)**.

**Closed** 2022-11-24 05:57 UTC
Labels: 🐞 bug, Feature:Bookmarks, Feature:Search, a-s, wontfix
