### ISSUE TITLE
Reader mode no table outlines

### ISSUE THREAD

**Issue by GunterSR** [mozilla-mobile/fenix#8044] opened 2020-02-03 11:29 UTC
### Why/User Benefit/User Problem
In the regular Firefox for Android we had table outlines for some articles, whcih contains the table. (Example: https://en.wikipedia.org/wiki/Los_Angeles) It will make table reading a lot easier.
### What/Requirements
In Fenix this is not released yet as I can understand.  Please add it like in original Firefox.

**Comment by kbrosnan** [comment] 2020-02-04 18:32
Sounds like a dupe of https://github.com/mozilla/readability/issues/568 If you think that it is not one then open a new issue in the Readability issue tracker.

**Closed by kbrosnan** 2020-02-04 18:32 UTC
Labels: Feature:ReaderMode, needs:triage, 🌟 feature request
