### ISSUE TITLE
[Bug] Bookmarks takes a few seconds to appear

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#4862] opened 2019-08-21 17:54 UTC
### Steps to reproduce

1. make sure you have a lot of bookmarks. I have a few thousand bookmarks after syncing with my desktop Firefox. But on the root level there are only three bookmarks and and four folders.
2. open Menu > Library Bookmarks

### Expected behavior

You immediately see the three bookmarks and four folders. 

### Actual behavior

You see only the title bar, nothing else and a few seconds later (up to four seconds in my tests) the bookmarks and bookmark folders appear.

### Device information

* Android device: HTC U11 / Android 9.0
* Fenix version: Fenix 1.3.0

**Comment by ekager** [comment] 2019-08-21 23:51
Dupe of #4513

**Closed by ekager** 2019-08-21 23:51 UTC
Labels: 🐞 bug
