### ISSUE TITLE
[Bug] Fenix not setting default search engine properly

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#3869] opened 2019-07-03 14:34 UTC
## Steps to reproduce
Set locale to RU or CN

### Expected behavior
Default search engine is not Google

### Actual behavior
Default search engine is Google

### Device information
any

**Comment by AndiAJ** [comment] 2019-07-04 09:18
Hi, I can still reproduce this issue on the latest Fenix Build **`#11850611 from 4/7`** using a **Google Pixel 3XL (Android 9)** as it follows:

<details>
    <summary>Russian ✅ OK - Yandex </summary>

► **Settings:**
![Screenshot_20190704-110149](https://user-images.githubusercontent.com/51314259/60652021-1184d100-9e50-11e9-8f02-26c25fdbf9f4.png)


► **Fenix default search engines:**
![Screenshot_20190704-110135](https://user-images.githubusercontent.com/51314259/60651930-e4d0b980-9e4f-11e9-9a22-f3fa5770c886.png)
</details>


<details>
    <summary>Chinese Traditional 1st option ❌NOK - Google </summary>
   
► **Settings:**
![Screenshot_20190704-110829](https://user-images.githubusercontent.com/51314259/60652242-8952fb80-9e50-11e9-9e16-81c72ef338d7.png)


► **Fenix default search engines:**
![Screenshot_20190704-110913](https://user-images.githubusercontent.com/51314259/60652209-77715880-9e50-11e9-867f-4594d4835740.png)

</details>



<details>
    <summary>Chinese Traditional 2nd option ❌NOK - Google </summary>

► **Settings:**

![Screenshot_20190704-111146](https://user-images.githubusercontent.com/51314259/60652605-3cbbf000-9e51-11e9-8352-960b02234727.png)


► **Fenix default search engines:**
![Screenshot_20190704-111218](https://user-images.githubusercontent.com/51314259/60652581-2f9f0100-9e51-11e9-9112-ddf1db5f8cd6.png)


</details>


<details>
    <summary>Chinese Traditional 3rd option ❌NOK - Google </summary>
   
► **Settings:**

![Screenshot_20190704-111414](https://user-images.githubusercontent.com/51314259/60652717-6412bd00-9e51-11e9-80bf-add3968c4170.png)



► **Fenix default search engines:**
![Screenshot_20190704-111438](https://user-images.githubusercontent.com/51314259/60652764-742a9c80-9e51-11e9-8aeb-d5a7c9dba358.png)


</details>



<details>
    <summary>Chinese Standard 1st option ✅ OK - Baidu </summary>
   
► **Settings:**

![Screenshot_20190704-111646](https://user-images.githubusercontent.com/51314259/60652856-9ae8d300-9e51-11e9-8d52-7d789880583f.png)



► **Fenix default search engines:**

![Screenshot_20190704-111732](https://user-images.githubusercontent.com/51314259/60652912-afc56680-9e51-11e9-96a0-c037b432e688.png)


</details>



<details>
    <summary>Chinese Standard 2nd option ❌NOK - Google </summary>

► **Settings:**

   
![Screenshot_20190704-112025](https://user-images.githubusercontent.com/51314259/60652986-d2577f80-9e51-11e9-8e09-cba201b5d026.png)



► **Fenix default search engines:**

![Screenshot_20190704-112003](https://user-images.githubusercontent.com/51314259/60653017-e4d1b900-9e51-11e9-8e87-7bb52759b51e.png)

</details>



<details>
    <summary>Chinese Standard 3rd option ❌NOK - Google </summary>

► **Settings:**
  
![Screenshot_20190704-112154](https://user-images.githubusercontent.com/51314259/60653075-003cc400-9e52-11e9-8d45-79e4a24e443f.png)


► **Fenix default search engines:**

![Screenshot_20190704-112228](https://user-images.githubusercontent.com/51314259/60653102-1054a380-9e52-11e9-8796-b7eab89e582b.png)


</details>


<details>
    <summary>Chinese Standard 4th option ❌NOK - Google </summary>

► **Settings:**
   
![Screenshot_20190704-112426](https://user-images.githubusercontent.com/51314259/60653152-282c2780-9e52-11e9-8b89-3b44b2e28817.png)


► **Fenix default search engines:**
![Screenshot_20190704-112348](https://user-images.githubusercontent.com/51314259/60653195-3bd78e00-9e52-11e9-929c-bce084e2aec6.png)


</details>

@boek For each of the above mentioned languages you'll find attached pictures from the device settings as well as from Fenix.
Also, I'm not sure if for each Chinese language (Traditional or Standard) and their options should be also covered?

**Comment by liuche** [comment] 2019-07-17 19:10
Half of this has been done and fixed, but waiting for more permanent location search-engine from AC.

**Comment by k0st1x** [comment] 2019-08-21 12:38
How to use the eng language on device but use the Yandex search?

**Comment by pocmo** [comment] 2019-08-26 17:28
In AC 10.0.0 we landed `RegionSearchLocalizationProvider` which does a GeoIP lookup to determine the region and is more accurate than locale. In order to use that we need to make sure that Fenix is only using "async" methods of `SearchEngineManager` since it may do a network request if no region is cached.

**Comment by boek** [comment] 2019-10-09 23:14
Waiting on an MLS Api Key

**Comment by Baron-Severin** [comment] 2019-10-22 20:25
@boek since this was moved into the backlog, does that mean that the key is now available?  Where would I find it?

@pocmo if `RegionSearchLocalizationProvider` checks my current location, is there a way for me to verify RU and CN behavior without booking a flight?

@vesta0 to clarify requirements, is it expected that users who are _**currently in China**_ use Baidu by default, or that users who have _**selected a Chinese locale**_ use Baidu by default?  Because these will require different approaches.

**Comment by Baron-Severin** [comment] 2019-10-22 22:14
> boek since this was moved into the backlog, does that mean that the key is now available? Where would I find it?

I spoke with boek, and it looks like we've requested the key but haven't heard back yet.  We will refactor our `SearchEngineManager` calls to use the async API now, so once we get the key we can quickly drop it in.

**Comment by vesta0** [comment] 2019-11-01 14:11
@Baron-Severin to answer your question, we currently reference the system default locale so if a user's system default locale is `zh-cn` then their search engine default will be Baidu. 

Once #220 is shipped, then user can change their locale but I believe search engine default will regardless follow the locale.

cc  @mconnormoz in case further clarification needed

**Comment by Baron-Severin** [comment] 2019-11-11 17:13
We expect that changes made in #5577 will fix this bug as well.

**Comment by Baron-Severin** [comment] 2019-12-05 01:27
> We expect that changes made in #5577 will fix this bug as well.

Correction, these changes did a lot of the prework that will enable this fix, but didn't actually fix the behavior.  Moving this into the backlog, as it still needs to be done.

**Comment by abodea** [comment] 2020-02-03 15:45
Hello, @boek @vesta0 is there a list where I can see what default search engine should be displayed for each language?
I synced with Severin on slack but he couldn't help me.
Note that for Chinese Traditional now is not Google displayed, but it's `Bing`. Before moving forward with the verification I wanted to make sure I have the right list for each language.

**Comment by liuche** [comment] 2020-03-31 19:00
@flod do you know where the default search engine is listed per-locale?

**Comment by vesta0** [comment] 2020-04-20 19:47
Can we find out which devices or locales are impacted by this bug?

**Comment by sv-ohorvath** [comment] 2020-07-14 12:40
@vesta0 Does this need QA investigation? If so, we could add the QA:needed label and have someone look at it.

**Comment by liuche** [comment] 2020-07-17 17:30
This seems like the same STR as #12544 which was verified, so I'm going to close this as a dupe

**Closed by liuche** 2020-07-17 17:30 UTC
Labels: E5, Feature:SearchProvider, P1, 🐞 bug
