### ISSUE TITLE
[Bug] Most recently opened tab is not always restored when killing and restarting

### ISSUE THREAD

**Issue by Ruin0x11** [mozilla-mobile/fenix#17525] opened 2021-01-19 10:54 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to a website and navigate to some links.
2. Kill and restart the app.

### Expected behavior
The last page navigated to should be restored when the app starts up.

### Actual behavior
An arbitrary page that got visited before the last recent page is restored instead, but the latest page is also saved in the history. So you can go back to the last visited page, but you have to manually open the history view and select it.

I have to do this a lot because the Twitter mobile site takes up so much memory that the share intents I send get killed immediately by the OS, so I often restart Firefox.

### Device information

* Android device: OnePlus 7
* Fenix version: Nightly 210116

**Comment by kglazko** [comment] 2021-01-22 21:56
I tried reproducing this with the Pixel 4 and an emulator multiple times and I wasn't able to reproduce. I was hoping @AndiAJ might be able to take a look and see if he can reproduce. Just as an FYI we are only saving the last opened tab every 30 seconds or when the app goes into the background so if you are seeing this happen after 30 seconds that is an issue, if the app is killed within 30 seconds of opening a new tab then it is by design this way.

**Comment by Ruin0x11** [comment] 2021-01-23 15:56
Can you explain the reason for this design? I think it's unintuitive since I run across this issue many times per day when having to deal with Twitter's memory usage causing Android to kill background processes silently as mentioned above. And it's not like the most recent tab is lost since it's still saved in the history.

**Comment by kglazko** [comment] 2021-03-04 17:06
@vesta0 @kbrosnan Do either of you have insight into why this time was chosen?

**Comment by pocmo** [comment] 2021-03-16 17:53
There are more events that trigger a save, besides the 30 second timer and backgrounding. In addition to that we also trigger a save on state changes (e.g. tabs get added,removed,selected). The 30 seconds are only a fallback to make sure we save the state in case we miss something (e.g. website internal changes we do not observe), not the primary method of saving state.

> Go to a website and navigate to some links.
> Kill and restart the app.

If those two steps happen fast after each other then we always may miss a state change and can't complete saving. Are there other STRs that may cause problems?

**Comment by csadilek** [comment] 2021-03-16 18:56
Let's close this as we can't address the specific STR, but please re-open if there are other cases where you hit this.

**Closed by csadilek** 2021-03-16 18:56 UTC
Labels: 🐞 bug

**Comment by Ruin0x11** [comment] 2021-03-23 21:33
I don't understand why this was closed. I'm still encountering this issue on a near-daily basis, not only when killing Firefox manually but when its process gets killed by Android after going into the background, such as after reading a PDF opened through an external link. I have to manually go through the effort of looking back in my page history to find the last page I was viewing. I can reproduce it easily by navigating to a page and opening a link that gets opened in another app, or by killing the process manually by the Android app switcher after the page is fully displayed.

I think if the intention is that the state is saved after every successful page transition, then the event might not always get fired when it should.

**Comment by Ruin0x11** [comment] 2021-03-23 21:40
Video:

https://user-images.githubusercontent.com/6700637/112222189-a3fd7300-8be5-11eb-9371-0d0d31c72a4b.mp4

**Comment by Ruin0x11** [comment] 2021-06-01 18:16
I'm still hitting this issue nearly every time I use Firefox Mobile. Will this be reopened?
