### ISSUE TITLE
[Bug] Report site issue is the wrong color in Dark Mode

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17175] opened 2020-12-21 19:48 UTC
Pixel 3 Steps to Reproduce
1. Set device to Dark Mode
2. Open Fenix (nightly)
3. Open three-dot kebab menu
4. See that "Report Site Issue..." icon is the wrong color :(
<img width="325" src="https://user-images.githubusercontent.com/43795363/102816078-064e9980-4393-11eb-8f62-a679db41f810.png">

**Comment by ekager** [comment] 2020-12-21 19:54
Closing as dupe of #11367

**Closed by ekager** 2020-12-21 19:54 UTC
Labels: E1, Feature:MainMenu, Feature:Themes, eng:ux-debt, good first issue, help wanted, needs:triage, pin, 🐞 bug
