### ISSUE TITLE
[Bug] norriq.dk is always returning 404 for geckoview based browsers

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#16987] opened 2020-12-11 21:44 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Open https://www.norriq.dk/job/ansoegning?JobID=2020-35 in Fenix

### Expected behavior

Page opens to a mobile view of that site.

### Actual behavior

Page 404's

GV bug filed at https://bugzilla.mozilla.org/show_bug.cgi?id=1682041

### Device information

* Android device: Moto E5, Android 8
* Fenix version: Nightly 201210 17.02 (Build # 2015780617)

**Comment by Amejia481** [comment] 2021-01-04 15:19
This is an issue for the website's developers to fix, see  [Comment 1 (on the bugzilla bug)]( https://bugzilla.mozilla.org/show_bug.cgi?id=1682041#c1), we need to inform them about it. @denschub does the webcompat team normally contact third party website developer about webcompat issue?  Or do you know what is the right person to help us with this?

**Comment by karlcow** [comment] 2021-01-05 01:58
@Amejia481 @denschub and I are both part of the webcompat team. And It's why I asked you to contact them as you reported the issue there. Was the issue coming from somewhere else initially?

**Comment by karlcow** [comment] 2021-01-05 02:00
@SeburoSUMO did you have this issue personally, if yes You can contact them at https://www.norriq.com/contact#1901 and point them to https://bugzilla.mozilla.org/show_bug.cgi?id=1682041#c1

Thanks

**Comment by Amejia481** [comment] 2021-01-05 15:22
> @Amejia481 @denschub and I are both part of the webcompat team. And It's why I asked you to contact them as you reported the issue there. Was the issue coming from somewhere else initially?

Ah OK, sorry for the confusion. I reported it on behalf of @SeburoSUMO

**Comment by SeburoSUMO** [comment] 2021-01-05 21:35
Hi.  This was reported off the back of a request into the SUMO Support Forum from a user and could be replicated on my own device.

**Comment by karlcow** [comment] 2021-01-06 06:10
@SeburoSUMO so usually the good followup is to ask the user to contact the company specifically in their own language and inviting them to 

1. fix the issue
2. engage with us on the bug so we can help them. 

Thanks

**Comment by ksy36** [comment] 2021-01-12 20:02
Maybe @jimmymcp could help us with this issue. Hi James, we're wondering what could be a reason for returning 404 in Firefox on mobile here. Would you be able to pass this along to the relevant person or team? 

More information can be found here https://bugzilla.mozilla.org/show_bug.cgi?id=1682041#c1, looks like this behavior is caused by User Agent detection

**Comment by Nickoriginal** [comment] 2021-07-13 10:46
Hello! _Not reproducible_ in Firefox 90.1.1 on:
**Samsung Galaxy A20s** (Android 10)
**Samsung Galaxy J2 Prime** (Android 6.0.1)
<img src = https://user-images.githubusercontent.com/85299944/125439134-975a2716-819f-4677-99ba-2a04b79f1732.jpg width = 45%>
Site loads correctly without 404.

**Comment by Amejia481** [comment] 2021-07-13 14:26
Then  I think we can close this ticket, please feel free to reopen if need it.

**Closed by Amejia481** 2021-07-13 14:26 UTC
Labels: b:webcompat, 🐞 bug

**Comment by Nickoriginal** [comment] 2021-07-13 15:51
Sorry, I can't reopen it if needed, because I am not a contributor, but if it happens again, I'll react.
