### ISSUE TITLE
FNX-12051 ⁃ [Bug] New Tabs Tray gets blank for a while when the back button is pressed two times quickly or going to the Android's homescreen and coming back

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11174] opened 2020-06-03 07:39 UTC
### Steps to reproduce
1. Go to a website so that you can press back button two times to go back to the Fenix homescreen
1. Press tabs tray icon quickly
1. Observe that the tabs tray is blank for       2 to 3 seconds or even more.

This can also be reproduced if a few tabs are open in fenix and go back to the Android homescreen and come back and press the tabs tray button.

### Expected behavior
Tabs tray shouldn't be blank

### Actual behavior
Tabs tray is blank

### Device information
* Android device: Motorola One Power, Android 10.
* Fenix version: Nightly 200603 06:00
![Screenshot](https://user-images.githubusercontent.com/42088907/83609270-918a4e00-a56d-11ea-8734-31d18d0a61b5.png)UNITO-UNDERSCORE!20200603-125853!

**Comment by darkwing** [comment] 2020-06-04 20:55
I'm unable to reproduce this -- asking for QA's eyes on this.

**Comment by SS1113** [comment] 2020-06-05 05:15
@darkwing Keep at least 10 tabs open while reproducing the bug.

Though it reproduces perfectly with the above mentioned steps as well.

**Comment by AndiAJ** [comment] 2020-06-05 06:43
Hi @darkwing I've just checked this matter on the latest **`Nightly Build 200605 from 6/5`** using a Google Pixel 3a (Android 10) and it seems that it's **still reproducible**

Moreover, **Fenix crashed** while testing
Crash report: https://crash-stats.mozilla.org/report/index/991f1e5b-87c3-4181-88c5-072bb0200605

► Video
![20200605-093428](https://user-images.githubusercontent.com/51314259/83845096-e74b2b80-a710-11ea-9d3c-be4a3a2f334d.gif)

**Comment by jonalmeida** [comment] 2020-06-16 03:50
Hi @AndiAJ this should be fixed now with https://github.com/mozilla-mobile/android-components/issues/7313. Could you verify that this is no longer the case?

**Comment by Diana-Rus** [comment] 2020-06-16 13:54
Hey, seems to be fixed now, build Nightly 6/16 with:
- Google Pixel 3XL (Android 9)
![20200616-164141](https://user-images.githubusercontent.com/49859863/84782480-bdd3af00-aff0-11ea-9b29-c9fd24a38bed.gif)

- Samsung Galaxy S9 (Android 8) 
![20200616-164653](https://user-images.githubusercontent.com/49859863/84783105-874a6400-aff1-11ea-849d-cc4de392c063.gif)

- Sony Xperia Z5 (Android 7)
![20200616-162714](https://user-images.githubusercontent.com/49859863/84782727-0c814900-aff1-11ea-95af-7b0822b12a03.gif)

**Comment by jonalmeida** [comment] 2020-06-16 21:32
> When bringing from Android's homescreen and coming back there still is, a very slight blank.

Thanks, I filed https://github.com/mozilla-mobile/android-components/issues/7413 for this.

**Closed** 2020-08-11 03:21 UTC
Labels: Feature:Tabs, S2, Skittle, eng:qa:verified, 🐞 bug
