### ISSUE TITLE
No-picture mode

### ISSUE THREAD

**Issue by 0x391F** [mozilla-mobile/fenix#26268] opened 2022-08-01 14:07 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Support no-picture mode. 

### How do you know that this problem exists today? Why is this important?
A user comment in app store. 

### Who will benefit from it?
Users who want to save internet traffic to save money or let website loading faster.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21161)

**Comment by kbrosnan** [comment] 2022-08-01 16:26
Assuming this is a request for the browser to block images. That would make this a duplicate of https://github.com/mozilla-mobile/fenix/issues/12711

**Closed by kbrosnan** 2022-08-01 16:26 UTC
Labels: needs:triage
