### ISSUE TITLE
[l10n] Some locales under language list appear as locale codes (vs actual language name)

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#12528] opened 2020-07-13 23:14 UTC
## Steps to reproduce
Go to Settings  > Languages
Look at list of available languages

### Expected behavior
All locales have their names spelled out correctly in the language list

### Actual behavior
Some locales only appear as locale codes, instead of their full name.
Depending on device/carrier, see for example: Occitan (oc), Triqui (trs), Kaqchikel (cak), Venitian (vec) 

### Device information
(always on latest Fenix Nightly)
I've seen this happen on Pixel 2, Android version 10
Also Sony Z3, Android version 5.0.2
A localizer has sent us the same issue, I don't know what the device info.

The results on locales seem to vary depending on carrier and Android version. For example, on the Pixel 2 I see "Ligurian" (lij) spelled out correctly. On the older devices, I see it only as a locale code, so "lij". Axel mentioned this might be because there are different CLDR versions in different Android versions. https://github.com/unicode-org/cldr/blob/master/common/main/en.xml#L445 exists, but not "cak" or "trs". 
I believe we're using the built-in language names. Neither of them appear as locales in https://github.com/unicode-org/cldr/tree/master/common/main (also not as seed locales).

This has happened in the past with Fennec and Focus Android. I'd file issues for Focus Android so we could specify ourselves the actual locale name. Not sure we can import what we have from Focus Android to help resolve this.

**Comment by s-ankur** [comment] 2020-07-14 09:36
For me the names are correct on device language, but when you change it all of them change into language codes
![Screenshot_20200714-150403_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/87410128-6e63ad00-c5b5-11ea-96ce-51d3f5ff56b8.png)

**Comment by liuche** [comment] 2020-07-29 17:23
@person808 while you're in non-standard locales-land from #13066, is this something that could be caused by mismatch between the locale codes? (If so, this could also be a larger problem that we would need to figure out in Pontoon, e.g. where should locale code mismatch resolution happen)

**Comment by person808** [comment] 2020-07-29 17:26
I'm not sure. I think we get the locale names from Android but I haven't looked at the code for this screen.

**Comment by liuche** [comment] 2020-10-09 20:11
May need to add a mapping, and that would solve these issues:
https://github.com/boek/focus-android/blob/ba0f3231add6529585dea4ac9b7aed943069fc01/app/src/main/java/org/mozilla/focus/widget/LocaleListPreference.java#L45

**Comment by mcarare** [comment] 2020-10-29 17:10
I wonder what should we use as a fallback for a language name when the selected locale does not identify a translation for defining that language?
That is likely the reason for this https://github.com/mozilla-mobile/fenix/issues/12528#issuecomment-658080230 - almost all languages having codes instead of names for subtitle (language name translated in the selected locale).

We could fallback to translation in device language and if that fails to the translation in English. This problem is for subtitles and only for some titles.

@Delphine or someone from UX could decide how should we handle these cases?

**Comment by Delphine** [comment] 2020-10-29 21:43
I wouldn't know how to advise in details, but we've faced this in the past on Focus Android for example, and both @boek and @pocmo were involved in helping "fix" these kinds of issues. I'm certain they can help advise and we can repro what we used to do for Focus.

My initial comment might also help: 
> The results on locales seem to vary depending on carrier and Android version. For example, on the Pixel 2 I see "Ligurian" (lij) spelled out correctly. On the older devices, I see it only as a locale code, so "lij". Axel mentioned this might be because there are different CLDR versions in different Android versions. https://github.com/unicode-org/cldr/blob/master/common/main/en.xml#L445 exists, but not "cak" or "trs".
> I believe we're using the built-in language names. Neither of them appear as locales in https://github.com/unicode-org/cldr/tree/master/common/main (also not as seed locales).
> This has happened in the past with Fennec and Focus Android. I'd file issues for Focus Android so we could specify ourselves the actual locale name. Not sure we can import what we have from Focus Android to help resolve this.
> I also remember that if the on what locales your Android devices supports, and that can vary a lot.

An example of what used to be done on Focus in cases where locales didn't show up correctly translated (but I think this is only part of the problem here): https://github.com/mozilla-mobile/focus-android/pull/2717/files

**Comment by Delphine** [comment] 2021-02-25 17:59
There are more and more locales reporting this issue to me. The latest is "kmr" (Kurmanji Kurdish).
The issue is that those languages are not discoverable by users, and we are losing potential users because of this.

**Comment by mcarare** [comment] 2021-03-03 12:04
@Delphine Is there anywhere I can get a list with all locales, with both locale code and name?

Another thing that still needs a decision: For the subtitle, we display the name of the language in the selected language. If that fails, what should we display? The name of the language in the original name, or in English?

**Comment by Delphine** [comment] 2021-03-04 20:00
This is a [handy link](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).
I found what we used to do with Jeff Boek in the past for Focus Android (since we were running into similar issues)- [this list may help](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/widget/LocaleListPreference.java#L41) for locales that don't have CLDR data.

Otherwise, what we would do for locales that aren't in CLDR, is that I'd ask directly the localizers for the native name, and Jeff would add those to the list above. We could do something similar here (I don't expect there to be a ton more, given the number of locales we already have on Fenix).
Hope this helps!

**Comment by mcarare** [comment] 2021-03-05 06:32
@Delphine Thank you for the Wikipedia link. The Focus part was already in my draft PR: https://github.com/mozilla-mobile/fenix/blob/fd936d27241d4a76705b443b9e0bf3048f5b4035/app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleViewHolders.kt#L43-L70.

I will get the complete list of languages we support from` l10n.toml` file. Let me know if there are any issues with using that.

**Comment by mcarare** [comment] 2021-03-08 11:13
Talked with @topotropic offline. For a better UX, I chose to display the English name of the locale as a fallback as the subtitle, to aid any user that chooses a locale by mistake to select one he knows.

**Comment by Delphine** [comment] 2021-03-08 19:50
> I will get the complete list of languages we support from` l10n.toml` file. Let me know if there are any issues with using that.

Absolutely! that works. Thank you!

**Comment by CrowdsourceKurdish** [comment] 2021-03-14 22:23
Hello,
The cause of the problem in Kurdish (kurmanji); It is that Iso and Unicode use different language codes for Kurdish (kurmanji).
Iso 693-3 = kmr
Unicode/Cldr = ku

Currently, Chrome-based browsers use the code "ku" for Kurdish (kurmanji).

Changing it to kmr>ku will solve the problem.

**Comment by ebalazs-sv** [comment] 2021-03-16 14:25
Verified as fixed on Nightly 3/16 with Motorola Moto G6 (Android 8).
I will remove the qa:needed label and close this issue.

**Closed by ebalazs-sv** 2021-03-16 14:25 UTC
Labels: Feature:Settings, eng:qa:needed, 🌐 L10N, 🐞 bug
