### ISSUE TITLE
Firefox becomes blank and unusable

### ISSUE THREAD

**Issue by yajo** [mozilla-mobile/fenix#21819] opened 2021-10-09 05:36 UTC
### Steps to reproduce

1. Open Gmail
2. Open an email
3. Click on a link. It should open in Firefox custom tab for this to happen.
4. Select one word in the page
5. Search
6. Go back twice (it should be once only, BTW, but that's not the bug here)

### Expected behaviour

Back in the custom tab, everything works. 

### Actual behaviour

Custom tab is empty and useless. Going to main Firefox, also. See:

https://user-images.githubusercontent.com/973709/136646012-eff70f8c-17e2-452d-8bda-db6b18583c6e.mp4

### Device name

Samsung Galaxy Tab S5e 

### Android version

11

### Firefox release type

Firefox

### Firefox version

93.1.0 (Build #2015836707)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18245)

**Comment by DaliusK** [comment] 2022-01-08 14:06
I'm using Firefox Daylight 95.2.0 (build #2015851755) on a Samsung phone Android 11. I have 2.7GB/4GB RAM used with over 800MB available.

Steps that produce this bug for me:
1. Open something in a tab. Custom tab or a tab in the browser produces same behavior.
2. Navigate to other apps, use them for a while. Using google maps for a while usually does the trick. It doesn't happen all the time, but I presume android tells firefox to release the memory or something.
3. When I come back the custom tab is blank as reported above. If I have it open in the browser, sometimes it will reload the page and sometimes it just stays as a broken blank tab. Entering a new URL in that tab does nothing, the tab is completely broken and unusable, I can only close it.

It's sad that this received no attention for months now, I don't want to go back to using Chrome. Unfortunately this bug is making the browser basically completely unusable as I spent HOURS reopening tabs and reentering the URL several times due to broken tabs.

**Comment by Randomblock1** [comment] 2022-01-17 22:17
I'm also having this issue, and while I can't always reproduce it, @DaliusK 's steps seem to be about right with what I've been experiencing.
I'm using a Samsung S21 with 8GB RAM total, and plenty free, so it's not something that only occurs on low- memory devices. Daylight 96.1.1 (Build #2015855931), Android 12.

Please fix this ASAP, because losing work in a tab is unacceptable in a modern browser. I've had to switch browsers for now.

**Comment by yajo** [comment] 2022-05-07 06:14
I'm so sorry to say this. 😔 I'm completely tired of this bug. I'm also tired of waiting. 7 months later not a single answer from the core team. Several users report the same, you have the STR, a video... and still under triage. This bug happens to me every single week at least once, but sometimes more than once a day. It makes me wonder if the devs have Android devices or if they actually use Firefox on them. I can't wait anymore. I'm going to uninstall Firefox from all my Android devices until fixed. And I'm a decades-long Firefox fan. But **this bug is extremely severe** in the way it impacts the user.

I hope some day this gets fixed and I can use my favorite browser again! 💔

**Comment by yajo** [comment] 2022-11-23 07:18
I just tested today. This issue is still 100% reproducible following the steps from the 1st comment, and it's still this app's worst UX problem ever.

**Comment by csadilek** [comment] 2023-01-20 21:57
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811614

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2023-01-20 21:57 UTC
Labels: 🐞 bug, needs:triage
