### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by eyalyoli** [mozilla-mobile/fenix#6819] opened 2019-11-26 18:23 UTC
## Steps to reproduce
Goto https://imagetopdf.com/
Click on "Upload files" button
Happened for every site that uses file upload. 
### Expected behavior
Opens android OS complete action for file selection 
### Actual behavior
Browser crashes
### Device information
Huawei p20 lite
* Android device: 9
* Fenix version: 
2.3.0 (Build #13031728)
📦: 18.0.0, ef631b6df
🦎: 70.0-20191014032640

**Comment by eyalyoli** [comment] 2019-11-26 18:29
Site screenshot before issue: 
![Screenshot_20191126_202042_org mozilla fenix](https://user-images.githubusercontent.com/4116908/69661394-fa5ab000-108a-11ea-95ff-c62ee9d41aab.jpg)
Expected behavior (shot from Chrome):
![Screenshot_20191126_202829_android](https://user-images.githubusercontent.com/4116908/69661581-58879300-108b-11ea-834a-9339d3dbbdcd.jpg)

In order to upload these screenshots, I had to switch to chrome - this issue happens in every site!

**Comment by cadeyrn** [comment] 2019-11-26 19:14
Duplicate of #6279.

(And please give your issue a title, thank you!)

**Closed** 2019-11-28 17:36 UTC
Labels: 🐞 bug
