### ISSUE TITLE
[Feature suggestion] Add the ability to copy or download images when you hold them 

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#27874] opened 2022-11-17 06:31 UTC
Please add the ability to copy and download images when you hold them

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21999)

**Comment by cadeyrn** [comment] 2022-11-17 07:37
It is already possible to download images. What exactly are you missing?

**Comment by Shadow0x12** [comment] 2022-11-17 07:43
> It is already possible to download images. What exactly are you missing?

When i hold on images in the duckduckgo search images section nothing shows besides open image in another tab, I mean a shortcut to just download or copy it directly instead of opening it in another tab

**Comment by cadeyrn** [comment] 2022-11-17 09:00
When i hold on an image in the DuckDuckGo image search I get an option to save the image.

**Comment by Shadow0x12** [comment] 2022-11-17 17:41
> When i hold on an image in the DuckDuckGo image search I get an option to save the image.

But when you click the image to view it you can't copy it or download it

**Comment by Kita2345** [comment] 2022-11-18 13:43
> Harap tambahkan kemampuan untuk menyalin dan mengunduh gambar saat Anda memegangnya
> 
> ┆Masalah disinkronkan dengan [Tugas Jira ini](https://mozilla-hub.atlassian.net/browse/FNXV2-21999)



> Please add the ability to copy and download images when you hold them
> 
> ┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21999)

**Comment by yoasif** [comment] 2022-11-25 02:50
Dupe of https://github.com/mozilla-mobile/fenix/issues/17780.

**Comment by cpeterso** [comment] 2023-01-30 03:19
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809305

**Closed by cpeterso** 2023-01-30 03:19 UTC
Labels: needs:triage
