### ISSUE TITLE
[Bug]: Login Status Is Not Shown Properly (menu says "Sign in to sync")

### ISSUE THREAD

**Issue by nvxarm** [mozilla-mobile/fenix#22284] opened 2021-11-03 14:53 UTC
### Steps to reproduce

1. Launch Firefox as normal.

2. Click the button of 3 dots to open the main menu.

Usually your email will show up in the main menu, and also in the Activity of settings.

But sometimes, it won't, either in the main menu, or the Activity of settings. As below screen record.

BTW, the function of sync seems to be working, though it still looks like "you haven't log in" even after sync is done.

https://user-images.githubusercontent.com/16894061/140082883-52cd8f8b-e257-47b0-a4c6-8fc2d679f684.mp4

### Expected behaviour

Login status should be shown properly. 

### Actual behaviour

Login status can be incorrect sometimes. 

### Device name

ASUS ROG Phone 5s

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

93.2.0 (Build #2015839747)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18546)

**Comment by nvxarm** [comment] 2021-11-03 14:59
Record again with English UI in case you don't understand Chinese.


https://user-images.githubusercontent.com/16894061/140085154-0d8ac787-559e-480e-b5bc-773603f50dcc.mp4

**Comment by nvxarm** [comment] 2021-11-24 15:27
One more reproducing on the nightly version as below.

https://github.com/mozilla-mobile/fenix/issues/22540#issuecomment-977918186

**Comment by cpeterso** [comment] 2021-12-17 17:56
I see this bug, too: when I first launch Firefox (Nightly 97), the menu says "Sign in to sync", but I know I'm logged in. If I tap the "Sign in to sync" menu item, the sync settings screen shows that I am logged in, as expected. If I go back to the web page and reopen the menu, it now shows my sync account's email address instead of "Sign in to sync".

**Comment by kbrosnan** [comment] 2022-11-23 00:40
This looks like a dupe of https://github.com/mozilla-mobile/fenix/issues/25486

**Closed by kbrosnan** 2022-11-23 00:40 UTC
Labels: 🐞 bug, Feature:Sync
