### ISSUE TITLE
[Bug] Cannot open local HTML files

### ISSUE THREAD

**Issue by kamran-12** [mozilla-mobile/fenix#5292] opened 2019-09-13 07:40 UTC
### Steps to reproduce
I installed Firefox Preview for Android and tried to open a locally saved HTML file.

### Expected behavior
I should be able to open HTML using Firefox Preview.

### Actual behavior
Firefox Preview for Android is not listed as a program that opens HTML files.

### Device information

* Android device: SM-G920F, Android 7.0
* Fenix version: 1.4.1

**Comment by cadeyrn** [comment] 2019-09-13 07:54
Duplicate of #4049.

**Comment by kamran-12** [comment] 2019-09-13 10:06
> Duplicate of #4049.

I am not sure about that but it is duplicate of #3864. So what should I do about that?

**Comment by cadeyrn** [comment] 2019-09-13 10:17
#4049 is about opening local files. It's exactly what you asked for. In #4049 it was said that it's a WONTFIX. So #3864 should probably be closed as well because #4049 seems to be required for #3864 (the browser first has to support opening file:// URIs before the browser can be suggested as application for opening these files).

**Comment by NotWoods** [comment] 2019-11-22 06:48
Closing as duplicate, see above.

**Closed by NotWoods** 2019-11-22 06:48 UTC
Labels: 🐞 bug
