### ISSUE TITLE
Add ability to disable individual autocomplete providers

### ISSUE THREAD

**Issue by runboy93** [mozilla-mobile/fenix#5745] opened 2019-10-02 20:05 UTC
Fenix does have option to disable autocomplete, but it doesn't work for "default URL list", which still autocomplete random URLs, not sure if this is bug or simply missing feature, correct me if wrong.

Little annoyance.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13724)

**Comment by cadeyrn** [comment] 2019-10-03 06:55
> not sure if this is bug or simply missing feature

It's a missing feature, not a bug. The old Firefox aka Fennec also doesn't have an option to disable this feature.

I vote for adding such an option because how to disable this feature is a question that keeps coming up in Firefox support (I am the operator of the biggest German speaking Firefox support forum). It was already the case for Fennec and there were already requests for Fenix.

**Comment by ealitten** [comment] 2019-11-01 14:28
The ability to turn this off does appear in Firefox Focus, which I thought fenix was at least partially based on: https://support.mozilla.org/en-US/kb/autocomplete-settings-firefox-focus-address-bar

I do hope this feature is added, since I find it wildly annoying for my urls to autocomplete to sites I have never and will never visit (the list seems very US-focused which means it's almost never of interest to me)

**Comment by cadeyrn** [comment] 2019-11-01 14:36
> The ability to turn this off does appear in Firefox Focus, which I thought fenix was at least partially based on

Fenix is not based on Firefox Focus. Both browsers use Android Components and GeckoView but are completely independently.

**Comment by ealitten** [comment] 2019-11-01 14:48
Ah OK, I stand corrected - the common use of Android Components and GeckoView must be where I got that idea from

**Comment by omaralsharif** [comment] 2020-03-15 10:33
I really think this issue should be addressed, as it may lead to a first impression that causes the user to question the browser's privacy claim. 

Having the browser autocomplete to 'a list of popular sites' implies that the browser is collecting browsing data from somewhere. If the autocomplete is accurate, it may even imply that it has data on the user in advance. 

This may conflict with one of browser's main claims of "privacy"

**Comment by omaralsharif** [comment] 2020-03-15 10:37
I really think this issue should be addressed, as it may lead to a first impression that causes the user to question the browser's privacy claim. 

Having the browser autocomplete to 'a list of popular sites' implies that the browser is collecting browsing data from somewhere. If the autocomplete is accurate, it may even imply that it has data on the user in advance. 

This may conflict with one of browser's main claims of "privacy"

**Comment by 894-572** [comment] 2020-04-20 10:56
>Fenix does have option to disable autocomplete, but it doesn't work for "default URL list", which still autocomplete random URLs, not sure if this is bug or simply missing feature, correct me if wrong.

The URLs aren't random, but some top websites pulled from Alexa perhaps.

**Comment by 894-572** [comment] 2020-04-20 10:56
a - amazon.com
b - bing.com
c - craigslist.com
d - diply.com
f - facebook.com
[...]

Many of the websites aren't relevant for my region or can't be used where I live.

Fennec has an about:config flag, better to add the setting to Firefox options since about:config may not be available in the stable branch.

**Comment by christianfl** [comment] 2020-04-24 12:03
> Fennec has an about:config flag, better to add the setting to Firefox options since about:config may not be available in the stable branch.

This flag in Fennec disables all search autocompletion, not only the default (sponsored) ones. I couldn't even find those URLs in the source code with grep, where are they stored?

**Comment by cadeyrn** [comment] 2020-04-24 15:01
> not only the default (sponsored) ones

These are no sponsored URLs but the most popular websites according to one of the Alexa top lists.

> I couldn't even find those URLs in the source code with grep, where are they stored?

https://github.com/mozilla-mobile/android-components/tree/77db26e4b0abcbd0a84b939821519813e98ce408/components/browser/domains/src/main/assets/domains

**Comment by omaralsharif** [comment] 2020-06-06 10:35
The flags in about:config are either bugged or completely disabled at this point in time. 

I'd love bring given the option to only autocomplete from history or bookmarks (rather than the Alexa top site list), but I'd definitely be satisfied with disabling autocomplete entirely

**Comment by cadeyrn** [comment] 2020-06-06 11:06
> The flags in about:config are either bugged or completely different at this point in time, as the current urlbar flags have no effect.

There was never a about:config option for that, neither in Fennec nor in Fenix.

**Comment by crisalis2** [comment] 2020-06-16 07:56
> > The flags in about:config are either bugged or completely different at this point in time, as the current urlbar flags have no effect.
> 
> There was never a about:config option for that, neither in Fennec nor in Fenix.

No. If you set browser.urlbar.autocomplete.enabled to false in Fennec, the Alexa top sites thing gets removed: for example, if you write "a" in the urlbar, no "amazon.com" suggestion comes up.
Now, in Fenix, setting browser.urlbar.autocomplete.enabled to false makes no difference. The "amazon.com" suggestion (which not only is unremovable spam, but also not even the relevant Amazon URL for my country) and all the other ones are still there.
This single problem makes Fenix worse than Fennec for me, and I'm sure I'm not alone.

There are options in about:config, like browser.urlbar.autocomplete.enabled, that simply don't work in Fenix. @omaralsharif is correct. Another example is browser.urlbar.trimURL: in Fennec, if you set it to false, it makes the urlbar show the "http(s)://" part. In Fenix, the "http(s)://" part doesn't come back no matter what.

Please, pay some attention to this issue. There are working features in Fennec that don't work in Fenix. Having options is good. And we are talking about options that were already there at that.

**Comment by Crandel** [comment] 2020-06-28 08:14
This bug is very annoing, I think this top lists should be removed completely. Does not make any sense. If I use site, I add it to bookmarks or it will appear in history.

**Comment by Dunexus** [comment] 2020-06-28 18:05
Top sites is something available on desktop new tab. There is no reason to remove it from fenix.

**Comment by oxxm** [comment] 2020-08-25 13:44
Now with about:config is disabled for stable release of Firfox Android, there is no way to disable the Alexa Top 500 autocomplete in the url bar.

Getting those suggestions is **very very** annoying, especially that most of them are not even relevant for my geographic region anyway! Why should I get the suggestion "kohls.com" when I type in a "k"? As an example for annoyance.

Please give the user the option to disable the Alexa Top 500 sites.

**Comment by cadeyrn** [comment] 2020-08-25 13:49
Please read the previous comments. There was also no about:config setting in Fennec for that, only for disabling the whole autocompletion. An option for disabling the Alexa top sites is a valid request but it doesn't depend at all on about:config.

**Comment by oxxm** [comment] 2020-08-25 13:55
@cadeyrn oh sorry, I thought this issue is about Firefox Android (Stable) too. 

Do you know which issue number handles the official firefox release for android?

**Comment by cadeyrn** [comment] 2020-08-25 17:10
There is no difference between stable and other release channels: No option exists to disable the Alexa top sites, neither in the old nor in the new Firefox. This issue is about adding such an option in Firefox.

**Comment by oxxm** [comment] 2020-08-25 19:26
@cadeyrn Understood. Thanks for your explanation. 

With the hope that the developers of Firefox check this issue and take it into consideration. In the meantime I switched to Fennec and disabled the auto suggestions via about:config

**Comment by ku4eto** [comment] 2020-08-28 21:36
I came here literally only because of this. For some reason, with one of the latest updates on Firefox Nightly (current 200828, 2015760563), it is super annoying. It came probably a week ago, before that, this "feature" was not present.

**Comment by oxxm** [comment] 2020-08-29 09:42
does anyone know if in Firefox 80 for desktop this "feature" can be disabled? Just to avoid the update.

**Comment by s-ankur** [comment] 2020-08-29 11:38
On firefox desktop 80.0 (ubuntu), on a blank profile, i do not get these recommendations. Only debian, ubuntu and mozilla pages are recommended in this manner

**Comment by oxxm** [comment] 2020-08-30 13:48
> 
> 
> On firefox desktop 80.0 (ubuntu), on a blank profile, i do not get these recommendations. Only debian, ubuntu and mozilla pages are recommended in this manner

@s-ankur thanks for the feedback! Just updated to Firefox 80 (Desktop) and there are no suggestions based on the Alexa top sites, as you mentioned.

**Comment by liuche** [comment] 2020-09-02 21:36
@boek re: url autocomplete is it this bug that we want to work on, or #15745?

**Comment by sv-ohorvath** [comment] 2020-09-11 08:07
Verified as fixed on Nightly 9/11 and Beta 81.1.1.

**Comment by lnicola** [comment] 2020-09-11 09:00
What if I want to get completions for my URLs (from history etc.), but not for homedepot.com and whatever other default domains are shipped by Mozilla?

**Comment by sv-ohorvath** [comment] 2020-09-11 11:35
> What if I want to get completions for my URLs (from history etc.), but not for homedepot.com and whatever other default domains are shipped by Mozilla?

@lnicola Your visited websites have a higher priority in autocompletion than the default top sites. Please try this (preferably with no other history on your device, but try with your own): type "m" - it autocompletes with microsoft. Enter mozilla.org. Then open a new search and type "m" again. Your website: mozilla.rog will autocomplete first.

**Comment by hwinnemoe** [comment] 2020-09-11 11:36
I do not think this issue is about disabling auto completion completely - it is about disabling the autocompletion for the alexa top lists websites.

**Comment by sv-ohorvath** [comment] 2020-09-11 11:40
> I do not think this issue is about disabling autocompletion completely - it is about disabling the autocompletion for the alexa top lists websites.

@boek Please have another look.

**Comment by oxxm** [comment] 2020-09-11 11:43
@boek @sv-ohorvath  will the current solution disable the suggestion of the hardcoded alexa top sites? they do not make any sense in my geographic region and are just very annoying.

**Comment by crisalis2** [comment] 2020-09-11 12:38
Thanks for this! Now it works exactly how I wanted, and how I had configured Fennec to behave. User experience is like 2000% better for me right now.

@oxxm Now there's an option to completely disable url autocompletion (which is different from search/bookmarks/history suggestions). This disables Alexa, obviously, but also autocompleting urls from your history/bookmarks: for example if you had bookmarked somesite.com/somecontent, somesite.com won't come up to autocomplete the url if you type "s" (you can still have the suggestion of the bookmark itself, if you configure it).

@sv-ohorvath I understand that other people want to be able to disable only the Alexa autocompletion, but whatever you change in the future, please please let there be an option like the one now. I want to disable url autocompletion completely, for me the url bar is a search bar "by default", and autocompleting urls kind of breaks it. Now it can work exactly how I want, so keep this option too in the future, please. By the way, this issue states "Option to disable default / (or? and? or+and?) custom URL list autocomplete", and now the "and" part is solved.

**Comment by oxxm** [comment] 2020-09-11 12:58
> 
> 
> Thanks for this! Now it works exactly how I wanted, and how I had configured Fennec to behave. User experience is like 2000% better for me right now.
> 
> @oxxm Now there's an option to completely disable url autocompletion (which is different from search/bookmarks/history suggestions). This disables Alexa, obviously, but also autocompleting urls from your history/bookmarks: for example if you had bookmarked somesite.com/somecontent, somesite.com won't come up to autocomplete the url if you type "s" (you can still have the suggestion of the bookmark itself, if you configure it).

@crisalis2  Just to have a better understanding, the user will have the option to disable the autosuggestion of alexa top sites, but will loose the autosuggestion of the saved bookmarks?

You wrote: "(you can still have the suggestion of the bookmark itself, if you configure it)."
Does that mean, if the "Search bookmarks" is activated in the settings, the bookmarked sites will still be suggested, eventough alexa top sites suggestion is disabled?

Thank you for the reply.

> 
> @sv-ohorvath @boek I understand that other people want to be able to disable only the Alexa autocompletion, but whatever you change in the future, please please let there be an option like the one now. I want to disable url autocompletion completely, for me the url bar is a search bar "by default", and autocompleting urls kind of breaks it. Now it can work exactly how I want, so keep this option too in the future, please. By the way, this issue states "Option to disable default / [or? and? or+and?] custom URL list autocomplete", and now the "and" part is solved.

**Comment by crisalis2** [comment] 2020-09-11 13:19
@oxxm There are two different concepts: suggestions and autocompletion.

Suggestions mean you see your bookmarks/history or even the selected search engine's own suggestions (depending on your settings) come up under/over your top/bottom urlbar so you can select them. Fenix always had flexible options related to suggestions. Also, the Alexa thing has nothing to do with suggestions.

On the other hand, autocompletion means that the urlbar itself gets overwitten with some url. The Alexa thing is relevant here. Until now, Fenix had no options related to autocompletion, it always forced it, and its sources to complete the url were your own bookmarks/history and the Alexa top sites. Now you can disable autocompletion completely. This is independent from suggestions, so yes, you can still have suggestions from bookmarks while you don't have any Alexa autocompletion. But if you disable autocompletion, you won't have autocompletion based on bookmarks either (you will still have bookmark suggestions if you want - suggestions and autocompletion are independent things).

You should install Nightly from Google Play and just try and see yourself. It won't affect your current non-Nightly Firefox.

**Comment by oxxm** [comment] 2020-09-11 13:38
> 
> 
> @oxxm There are two different concepts: suggestions and autocompletion.
> 
> Suggestions mean you see your bookmarks/history or even the selected search engine's own suggestions (depending on your settings) come up under/over your top/bottom urlbar so you can select them. Fenix always had flexible options related to suggestions. Also, the Alexa thing has nothing to do with suggestions.
> 
> On the other hand, autocompletion means that the urlbar itself gets overwritten with some url. The Alexa thing is relevant here. Until now, Fenix had no options related to autocompletion, it always forced it, and its sources to complete the url were your own bookmarks/history and the Alexa top sites. Now you can disable autocompletion completely. This is independent from suggestions, so yes, you can still have suggestions from bookmarks while you don't have any Alexa autocompletion. But if you disable autocompletion, you won't have autocompletion based on bookmarks either (you will still have bookmark suggestions if you want - suggestions and autocompletion are independent things). Some people here are asking for that, the possibility to have urlbar autocompletion based on bookmarks/history only, without Alexa.
> 
> You should install Nightly from Google Play and just try and see yourself. It won't affect your current non-Nightly Firefox.

@crisalis2 Thank you for the great explanation about the difference between autosugesstion and autocompletion.
The newest nightly indeed does not autocomplete the url bar with the alexa sites anymore.

And thanks you, Firefox team, for reacting to user suggesstions.

**Comment by boek** [comment] 2020-09-11 16:36
Hey all, thank you for this feedback!

Let me see what we can do about allowing more fine tuning of the controls here!

**Comment by liuche** [comment] 2020-09-12 00:06
@sv-ohorvath to clarify, the feature you verified is in fact "turn off all autocomplete" - thank you for verifying! That fix is working as intended.

We have then re-purposed (and re-named this bug) to handle more specific autocomplete controls (which may be history, top sites, bookmarks, etc) with UX feedback.

**Comment by cpeterso** [comment] 2022-12-27 22:25
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807749

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2022-12-27 22:25 UTC
Labels: feature request 🌟, Feature:Search, needs:UX-investigation
