### ISSUE TITLE
Desktop mode not working correctly[Bug]

### ISSUE THREAD

**Issue by anshu1983** [mozilla-mobile/fenix#15562] opened 2020-09-30 09:56 UTC
## Steps to reproduce

1. Open a website in the mobile browser
2. Change it into desktop mode
3. Go out from Firefox app
4. Let the Firefox app be removed from the RAM
5. Re-open firefox
6. Go to the website which was changed to desktop mode

### Expected behavior
1. Website should appear again in desktop mode

### Actual behavior
Website is displayed in mobile mode. Intermittently, I have also seen that the desktop mode toggle is still enabled in the settings but the website is displayed in mobile mode. If I try to change the toggle, it does not change and remains in desktop mode even though the website refreshes. To resolve the issue, I have to force close the app and then reopen firefox. The website is loaded again but in mobile mode only. This time I am able to change it desktop mode.
### Device information

* Android device: 10
* Fenix version: 81.1.1 (Build #2015764547)

**Comment by s-ankur** [comment] 2020-09-30 10:24
Possible duplicate of https://github.com/mozilla-mobile/fenix/issues/11552

**Comment by mcarare** [comment] 2020-10-01 08:52
@anshu1983 Thank you for your report. Closing as duplicate.

**Closed by mcarare** 2020-10-01 08:52 UTC
Labels: needs:triage, 🐞 bug
