### ISSUE TITLE
[Bug] long press images with links

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#3611] opened 2019-06-23 10:14 UTC
The title probably isn't the best, but I've come across this a few times.

## Steps to reproduce
1. www.redflagdeals.com
1. Tap and hold  on the header 
1. Prompt opens 

### Expected behavior
* Prompt shows the url that tapping the header leads to (https://www.redflagdeals.com)
    1. Actual behavior
* Prompt shows the url of the image (https://assets.rfdcontent.com/graphics/rfd/v28.11.0.2/sprites/responsive_base.png)

### Device information
* Android device: 8.1.0 stock unrooted
* Fenix version: 1.0.1925 (Build #11740610 :lizard: 68.0-20190611143747)
![Screenshot](https://user-images.githubusercontent.com/50635951/59974796-24f58980-957e-11e9-837d-9645c53c0afb.png)UNITO-UNDERSCORE!20190623-060402!

www.Wal-Mart.com is another example

Scroll to the trending items, tap and hold on an image and the prompt will open. 
The prompt will show the url location of the image, when it should be showing the link that tapping it leads to

EDIT: for clarity I removed reference to "open in New tab" as that is a separate issue.

**Comment by cadeyrn** [comment] 2019-06-23 10:22
This option was temporary removed for MVP in #3326 because of a bug and will be re-added later once the bug is fixed (#2312).

**Comment by bubi-luka** [comment] 2019-06-23 10:44
The option was not removed. Please read carefully the title of this bug.

The option that @cadeyrn is refering to is for images: long click on an image and there is option "Open image in new tab". This was removed.
This bug is for links to the image (html => <a href="https://www.example.com/image-full.jpg"><img href="https://www.example.com/image-small.jpg" /></a>). Long click opens the standard menu for links and there is "Open link in new tab". On click on this link you run into bug #2312.

This problem with images in new tab is really annoying. Any info when will the root bug solved?

**Comment by cadeyrn** [comment] 2019-06-23 10:53
> Please read carefully the title of this bug.

Please read carefully the description?

The issue opener said "open image in new tab", not "open link in new tab" and this was removed in #3326. Also #2312 was exactly the bug I mentioned.

The issue opener edited the description a minute ago. But as you can see in the old versions (click on the "edited" in the first comment) you can see it's exactly as I said.

**Comment by nahuhh** [comment] 2019-06-23 10:58
Anyway, no need to fight each other. I created the confusing with my description - apologies. 🙌 *don't shoot*

I hope that now it's a bit more clear as to what I'm referring to?

**Comment by bubi-luka** [comment] 2019-06-23 11:11
@cadeyrn please accept my apologies for the harsh tone, and @nahuhh for misinterpreting the issue. I was too fast writing my comment and too slow understanding what this bug report is about.

**Comment by ekager** [comment] 2019-06-24 23:29
Looks like a dupe of #2911 which should be fixed on the AC side

**Comment by nahuhh** [comment] 2019-07-07 18:46
I was following along #2911, which is now fixed and closed. 

Looks like a different issue. 

Using the same website in question as #2911 (www.cnn.com) 

- go to CNN.com and long press the image at the top of the news article
- make note of the url that is listed in the dialog

### expected behavior
The url of the article is listed
### actual behavior
The url of the image is listed

**Comment by sblatz** [comment] 2019-07-20 01:06
Filed an [ac issue](https://github.com/mozilla-mobile/android-components/issues/3839).

**Comment by nahuhh** [comment] 2019-07-29 02:35
Confirmed fixed.
Closing

**Closed** 2020-08-27 00:41 UTC
Labels: P3, needs:ac, 🐞 bug, 🙅 waiting
