### ISSUE TITLE
[Feature Request] New toggle in search settings to prevent high traffic websites from being suggested

### ISSUE THREAD

**Issue by anabh4569** [mozilla-mobile/fenix#14336] opened 2020-08-28 04:16 UTC
### What is the user problem or growth opportunity you want to see solved?

When the search bar is clicked on, even when all other search suggestions are turned off (bookmarks, history, clipboard, etc), high traffic websites are suggested to the user. Examples (typed prefix -> suggestion):
- a -> amazon.com
- app -> apple.com
- e -> ebay.com

My suggestion is to make this feature a toggle. When the toggle is turned off, these high traffic websites are not suggested.

### How do you know that this problem exists today? Why is this important?

I know this exists because I tested it on my phone. This used to even be an issue for desktop firefox, but it was removed at some point.

This is important because it gives free advertising to high traffic websites that users might not want to support. I guess the current situation also slightly inconveniences users because if they're trying to search for a term like "app", they have to intentionally backspace to prevent being sent to apple.com.

### Who will benefit from it?

Everyone who doesn't want these type of suggestions.

**Comment by cadeyrn** [comment] 2020-08-28 06:41
Duplicate of #5745.

**Closed** 2020-09-01 01:53 UTC
Labels: needs:triage
