### ISSUE TITLE
Default device name should show both app and device name

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#3886] opened 2019-07-04 01:27 UTC
## Steps to reproduce
1. Install Fenix.
2. Sign into an account.

### Expected behavior
1. ~The default name should be '[app name]' or '[app name] on [device]'~
   - ~e.g. "Firefox Preview" or "Firefox Preview on Pixel 2".~

⚠️ **Update:** 
Verified format: `[user]'s [app name] on device`
 e.g. "Jonathan's Firefox Preview on Pixel 2"

### Actual behavior
1. The default name is '[device] [manufacturer]'.

### Device information

* Android device: Android 9
* Fenix version: 03/07/2019

This seems to be a regression from https://github.com/mozilla-mobile/fenix/issues/3317.

cc: @ryanfeeley

**Comment by ekager** [comment] 2019-07-04 04:25
Was this default specced out somewhere? It looks like it was a regression w #3317 we just need confirmation of what it *should* be and then it's just changing the default :)

**Comment by jonalmeida** [comment] 2019-07-04 14:34
Yes, here: https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/357470305

The format there is '[app name] on [person]'s [device]' but this was scoped to match desktop which is the format currently used everywhere, i.e. '[app name]' or '[app name] on [device]' .

**Comment by vesta0** [comment] 2019-07-09 04:36
I think device name should include both [app name] and [device name] e.g. Firefox Preview on Pixel 3

**Comment by liuche** [comment] 2019-07-19 21:26
Waiting on Strings confirmation.

**Comment by mheubusch** [comment] 2019-07-19 23:28
Confirmed that it should be [app name] on [device name]

I think what you see in Invision is an artifact of Ryan customizing the name of his device, not pulling in metadata from somewhere else.

**Comment by mheubusch** [comment] 2019-07-19 23:28
@liuche strings resolved

**Comment by ryanfeeley** [comment] 2019-07-20 02:17
@vesta0 @mheubusch Close. It's best to take a look what Firefox does on other platforms to stay  _ in sync_. What is does is something like **Vesta’s Firefox Preview on Pixel 3**.

Related issue: https://github.com/mozilla/fxa/issues/1816

**Comment by mheubusch** [comment] 2019-07-21 19:17
@ryanfeeley I'm seeing variance across the board, and was trying to match for Android. Firefox for Android and Firefox Beta for Android don't pull in a user's name either.  Is this a Fenix issue or FxA issue? Also, are Firefox for Linux and Pocket and Lockwise displaying correctly too? 
<img width="489" alt="Screen Shot 2019-07-21 at 2 10 12 PM" src="https://user-images.githubusercontent.com/20115914/61595862-022cb400-abc2-11e9-9924-6f4be5136890.png">

**Comment by jonalmeida** [comment] 2019-07-22 04:52
> Also, are Firefox for Linux and Pocket and Lockwise displaying correctly too?

I don't have a linux device, but here is a screenshot of Lockwise, Pock and Send.

<img width="653" alt="Screen Shot 2019-07-22 at 12 51 14 AM" src="https://user-images.githubusercontent.com/1370580/61607012-e3a6d700-ac1a-11e9-8202-ee6045ca6d73.png">

**Comment by jonalmeida** [comment] 2019-07-22 19:05
@mheubusch spoke with @ryanfeeley offline: `[name]'s [app] on [device]` is the way we have to have across all devices eventually so we should do the preferred way here (other platforms will update).

**Comment by ryanfeeley** [comment] 2019-07-22 19:50
For an items that can appear multiple times, it would be great to have ``[name]'s [app] on [device]`` for all of them.

**Comment by softvision-miralobontiu** [comment] 2019-07-31 10:09
This is not fixed yet on the latest Nightly build 190731 (#12120612) with Google Pixel 3 (Android 9), Sony Xperia Z5 Premium (Android 7.1.1), and Windows 10.

This is how the device's names are displayed:

![Screenshot_2](https://user-images.githubusercontent.com/40694158/62203622-32c7d700-b394-11e9-8184-77c6e39083b9.png)

**Comment by jonalmeida** [comment] 2019-07-31 15:02
I mentioned this offline, but it seemed a conflict resolution when merging this PR seems to have broken it's functionality: https://github.com/mozilla-mobile/fenix/commit/8ff77b90f388187e04f6a376702c6a10873ea49e

**Comment by softvision-miralobontiu** [comment] 2019-08-01 11:35
Verified as fixed on RC 1.2.0-rc.1, and latest Nightly build 190801 with Motorola Moto G6 (Android 8), and Sony Xperia Z5 Premium (Android 7.1.1).

**Closed by softvision-miralobontiu** 2019-08-01 11:35 UTC
Labels: E1, Feature:Sync, eng:qa:needed, 🐞 bug
