### ISSUE TITLE
Image Context Menu Should Include Share Option

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#7458] opened 2020-01-01 16:44 UTC
### Why/User Benefit/User Problem
Old firefox had better popup organization for when clicking on image.
It allow for clearer interaction and finding action quicker.

### What/Requirements
Add back a tabbed sharing menu with clearer share options for link and media.

### Acceptance Criteria (how do I know when I’m done?)
Firefox mobile should have two tabs (one for link, one for image), thus better visual clarity. 
![ImageSharingOptions](https://user-images.githubusercontent.com/11428869/95196196-6bf1a780-07e0-11eb-817b-e7980d0fd107.gif)

**Comment by ekager** [comment] 2020-04-29 18:36
AC ticket mozilla-mobile/android-components#3648

**Comment by kbrosnan** [comment] 2020-04-29 18:49
Which notes that this is a dupe of #3621 then.

**Comment by Octoton** [comment] 2020-04-29 19:50
I would like to disegree with the fact the this is closed
My issue was not the lack of shared option, but the fact that firefox mobile as two tab (one for link, one for image), thus better visual clarity. This help finding what you want expecily for new comer

**Comment by Mugurell** [comment] 2020-10-06 11:35
I think this ticket referred not to functionality but to UX.
Asking UX for feedback about if we should split the contextual menu options like it was on Fennec. (as seen in the first comment)

**Comment by cousteaulecommandant** [comment] 2020-12-30 13:34
> I think this ticket referred not to functionality but to UX.
> Asking UX for feedback about if we should split the contextual menu options like it was on Fennec. (as seen in the first comment)

Should the title be changed (again) to better reflect this?  Right now it doesn't reflect the fact that it refers to the request of a two-tabbed interface, thus why it was mistakenly identified as a dupe of #3621.  (The original title was closer to this.)

**Comment by Octoton** [comment] 2020-12-30 22:03
After using this navigator for some time, this issue seems better suited for my problems: https://github.com/mozilla-mobile/fenix/issues/12071

**Comment by Octoton** [comment] 2020-12-30 22:04
This one can then be close without problem by me

**Comment by cousteaulecommandant** [comment] 2020-12-31 10:46
I don't know; I kind of liked having separate "Link" and "Image" contexts on the context menu.  I think it is still worth considering, at least if there end up being as many options as there used to be – it's better than having to scroll if they overflow the screen.  (If not, then I agree that at least separating the contexts with a horizontal line is a good idea, and maybe also adding titles to each section.)

**Comment by apbitner** [comment] 2021-01-07 17:33
Between #12071 and #12414 (in which I referenced this ticket), I believe this ticket can be closed.

**Closed by apbitner** 2021-01-07 17:33 UTC
Labels: Feature:ContextMenu, Feature:FennecTransition, Feature:Media, feature request 🌟, needs:UX-feedback, needs:ac
