### ISSUE TITLE
[Bug]: Missing pictograms throughout the application on Android 5 tablet

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#23488] opened 2022-01-31 16:00 UTC
### Steps to reproduce

1. Open Fenix.
2. Tap on the URL bar and start typing in a search term.
3. From the search suggestions displayed, tap on the right side of the screen (where the arrow should be displayed).
4. Observe the arrow pictogram and the magnifying glass pictogram near the search word and "Search engine option".
5. Go to Settings and navigate throughout different menus.
6. Observe if all the pictograms are displayed within the menus.

### Expected behaviour

All the pictograms are visible throughout the application. 

### Actual behaviour

Various pictograms are not displayed throughout the application and within the Settings menu.
The functionality is present for all of them. 

Issue related: https://github.com/mozilla-mobile/fenix/issues/23484 . Note that the pictograms from the search screen are not displayed on other devices and android versions as well (Motorola Moto G30 (Android 11)).

### Device name

Huawei MediaPad M2

### Android version

(Android 5.1.1)

### Firefox release type

Firefox Nightly

### Firefox version

98.0.0-0a1

### Additional information

![Missing pictograms A5](https://user-images.githubusercontent.com/89388888/151826374-5a996502-1fdc-45e2-b572-5d447ccd63b9.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19329)

**Comment by kbrosnan** [comment] 2022-01-31 19:08
This looks like a duplicate of https://github.com/mozilla-mobile/fenix/issues/23350

**Closed as completed by kbrosnan** 2022-01-31 19:08 UTC
Labels: 🐞 bug, Feature:Search, Feature:Browsing, Feature:Settings, needs:triage
