### ISSUE TITLE
"Add"/"Edit" button next to "Bookmarks" in 3 dot menu causes lots of mis-taps (cause: tiny button size)

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#24560] opened 2022-04-01 22:29 UTC
### Steps to reproduce

1. Open the 3-dot menu.
2. Tap on Add/Edit next to Bookmarks.
3. Repeat these steps lots of times, trying to tap the button in a slightly different place each time (to mimic real world scenario of random tap locations, based on how a user is holding their device, their finger size, and probably several other factors).

### Expected behaviour

Fenix should always Add or Edit the bookmark, instead of opening the Bookmarks list.

### Actual behaviour

Sometimes, based on the tap location, Fenix opens the Bookmarks list.

The cause of this bug is very clear: Long-pressing on the Add/Edit button shows that it is a tiny little button "inlaid" within the larger Bookmarks button, and its borders are well within the bigger button's borders. This leaves quite a large area for the mis-taps to occur. Whenever a tap lands outside these tiny tiny borders and lands on the Bookmark button instead, you get this bug.

Straightforward solution: Expand the Add/Edit button's area so that its borders coincide with the right, top, and bottom borders of the Bookmarks button.

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

98.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20033)

**Comment by bigConifer** [comment] 2022-04-03 14:58
This is a duplicate of bug report #20242

**Comment by opusforlife2** [comment] 2022-04-03 17:14
Thanks. I've read through that issue. I've found a clear STR compared to the OP there, so I think this one can stay open.

**Comment by bigConifer** [comment] 2022-04-04 14:31
Well, then #20242 should be closed in favor of this.

**Comment by opusforlife2** [comment] 2022-04-13 16:57
@amedyne Will you not be closing #20242?

**Comment by csadilek** [comment] 2023-01-24 22:20
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812174

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2023-01-24 22:20 UTC
Labels: 🐞 bug
