### ISSUE TITLE
FNX3-16957 ⁃ [Crash] Crash after opening from external source

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3344] opened 2019-06-11 14:34 UTC
## Steps to reproduce
from: https://github.com/mozilla/firefox-preview-bughunting-campaign/issues/337

1. Set Firefox as a default browser on Android
1. Open a link from any app (Google, SMS, anything)
1. The app should crash while loading the page in a new tab
1. Opening the app again might make it crash again, but the tab is opened
1. Opening the tab makes it load the page properly most of the time
    1. Expected behavior
Page loading.
    1. Actual behavior
The browser crashes before opening the page. Clicking on "Restart Firefox Preview" sometimes makes it crash too, but if it doesn't the tab isn't open and you have to open the link again.
    1. Device information

* Android device:  Pixel (Android 9), Galaxy S8
* Fenix version:

**Comment by colintheshots** [comment] 2019-06-11 15:30
Wait. The source crash was from seven days ago. We've spent the last week closing crashes, including the syncNow crash on startup and the Display Already Acquired duplicate BrowserFragment crash.

It's important to clarify. Can you still reproduce this in Nightly?

**Comment by sv-ohorvath** [comment] 2019-06-11 15:50
I personally can't reproduce, but I logged this based on this message from @sylvestre: https://mozilla.slack.com/archives/CA4QR1M2R/p1560261611077200

**Comment by softvision-miralobontiu** [comment] 2019-06-13 09:25
I was not able to reproduce the crash on Samsung Galaxy Tab S3 (Android 8), and Google Pixel 3 (Android 9), with the latest build1.0.1924 (#11640609).

**Closed** 2020-08-12 17:34 UTC
Labels: P1, b:crash, eng:qa:verified, 🐞 bug
