### ISSUE TITLE
Allow Top Sites to be exported to a data backup/portability file format

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12958] opened 2020-07-26 15:45 UTC
Branched out from #12957. Please refer that issue to get the whole context. Thanks. :grinning:

Offer a data portability/backup solution for Top Sites just like how you're doing with bookmarks with an HTML file. 

[Kiwi browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser) offers an excellent solution to this with the ability to export Top Sites into a .json file which when restored gets all the Tops Sites to how they were before including their position. Please refer that browser for example it's also [open source](https://github.com/kiwibrowser/src). Fenix could offer something similar.

Screenshots:

![Screenshot](https://user-images.githubusercontent.com/68282543/88483365-f6b65a80-cf84-11ea-9601-9313b074c467.jpg)UNITO-UNDERSCORE!20200726!UNITO-UNDERSCORE!211401.jpg!

**Comment by kbrosnan** [comment] 2020-07-26 22:30
Closing as a duplicate of #12957. Until there is a plan to offer export the main issue is enough to track the request. The issue can be reopened if that is prioritized.

**Closed** 2020-08-28 23:02 UTC
Labels: needs:triage
