### ISSUE TITLE
[Bug]: Failed to install add-on

### ISSUE THREAD

**Issue by quadriflax** [mozilla-mobile/fenix#20692] opened 2021-08-05 15:30 UTC
### Steps to reproduce

Open Firefox, open settings, open add-ons, attempt to install any add-on. 

### Expected behaviour

Add-on installs.

### Actual behaviour

Error displayed: failed to install add-on.

### Device name

LG G Pad 8.0X

### Android version

Android 7.0

### Firefox release type

Firefox Nightly

### Firefox version

92.0.a1

### Additional information

92.0a1 (Build #2015826217)
AC: 92.0.20210804145319, 1efe95ff30
GV: 92.0a1-20210804093931
AS: 81.0.1

Latest nightly from 5 Aug, fresh install. Seems related to bug #20686 and bug #12399. Now I can't even get add-ons to install. Version from 3 Aug still works fine, so whatever broke started in 4 Aug nightly.

**Comment by Amejia481** [comment] 2021-08-05 16:55
Thanks for reporting. 
If it's not much trouble would you mind sharing the [logcast logs](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information) when you try to install an add-on.

**Comment by Amejia481** [comment] 2021-08-05 17:11
I tested on Android 11 and on Android 7 and I wasn't able to reproduce. Is there an specific add-on that is causing the issue? Which one are you trying?

**Comment by quadriflax** [comment] 2021-08-05 17:23
I ran the adb while connected to my PC and in debug mode. Not sure what I need to trim from here as it's just a lot of data. Let me know and I'll work it out.

Also, it's all of the addons causing the issue. This is an older tablet with a fresh install. I'm not even logged into Sync or anything.

![Screenshot_2021-08-05-13-15-13](https://user-images.githubusercontent.com/46144580/128393818-ce247ca9-a386-4d02-bdd5-7cb6ae2ef9d6.png)

**Comment by Amejia481** [comment] 2021-08-05 17:30
No worries, could you attach a file with the logs ?

**Comment by quadriflax** [comment] 2021-08-05 17:40
[adb.txt](https://github.com/mozilla-mobile/fenix/files/6940616/adb.txt)

Here ya go. Hopefully that helps. I just started it, opened Fenix, went to add-ons and tried to add uBlock Origins, the error popped, then I backed out and closed and stopped the log. Let me know if you need anything else.

**Comment by Amejia481** [comment] 2021-08-05 21:04
> [adb.txt](https://github.com/mozilla-mobile/fenix/files/6940616/adb.txt)
> 
> Here ya go. Hopefully that helps. I just started it, opened Fenix, went to add-ons and tried to add uBlock Origins, the error popped, then I backed out and closed and stopped the log. Let me know if you need anything else.
> 
> EDIT: I just rolled back to 3 Aug nightly and the add-ons install just fine.

Could you post the about "Firefox nightly" page for the  3 Aug Nightly (the good version) ?

**Comment by quadriflax** [comment] 2021-08-05 21:10
92.0a1 (Build #2015825969)
AC: 92.0.20210803143316, 2347602c39
GV: 92.0a1-20210802093840
AS: 81.0.1

Not a problem. Let me know if you need anything else.

**Comment by Amejia481** [comment] 2021-08-05 21:17
Thanks for the fast response, we are investigating we also opened an [additional ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1724298) for the GeckoView team to also team a look.

**Comment by quadriflax** [comment] 2021-08-05 21:20
I'll keep checking new nightlies and will report back any success/failure to resolve or any change in status. If you need me to pull anything else, just say the word. Thanks for the follow up!

**Comment by quadriflax** [comment] 2021-08-06 01:18
Checked out the latest nightly (5 Aug) on my daughter's tablet and my phone. Both seem to be working fine (Lenovo Tab M10 on Android 10 & Moto G Stylus 2020 on Android 11). These both have arm64-v8a instruction sets, whereas my Samsung and LG tablets have armeabi-v7a. Might that be a lead?

**Comment by quadriflax** [comment] 2021-08-06 12:11
92.0a1 (Build #2015826377)
AC: 92.0.20210805225445, 36a57288b8
GV: 92.0a1-20210805092724
AS: 81.0.1

Latest 6 Aug nightly is now throwing "failed to query" error (#20686) instead of "failed to install". Add-ons not loading at all as a result. Still no issues on the Moto G.

**Comment by Amejia481** [comment] 2021-08-06 13:20
> Checked out the latest nightly (5 Aug) on my daughter's tablet and my phone. Both seem to be working fine (Lenovo Tab M10 on Android 10 & Moto G Stylus 2020 on Android 11). These both have arm64-v8a instruction sets, whereas my Samsung and LG tablets have armeabi-v7a. Might that be a lead?

Thanks for all the info. That could be an indicator. So far, there are some additional teams that are involved in the investigation we are following the case in this bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1724298, feel free to continue updating this ticket or the bugzilla bug with your findings.

**Comment by Amejia481** [comment] 2021-08-06 13:22
> Latest 6 A

Would you mind sharing the logs of the 6 Aug nightly? Thanks in advance!

**Comment by Amejia481** [comment] 2021-08-06 13:41
@SpandexWizard we are tracking the issue here, would you mind sharing  your device's brand, model and Android OS version? Thanks in advance.

**Comment by quadriflax** [comment] 2021-08-06 13:42
Here is adb from 6 Aug nightly (pulled from my LG tablet).

[adb.txt](https://github.com/mozilla-mobile/fenix/files/6945896/adb.txt)

**Comment by cadeyrn** [comment] 2021-08-06 13:44
FWIW, I can **not** reproduce the issue. Do you also need information about devices where it dosen't happen?

**Comment by Amejia481** [comment] 2021-08-06 14:02
Thanks for helps, so far we are trying to find a pattern on devices that have the issue. I'm not able to reproduce and I tested with a pixel 3 Android 11 and Motorola Moto G5 with Android  7.

**Comment by quadriflax** [comment] 2021-08-06 14:51
Just tried latest (6 Aug) nightly on my old Moto G5+ and it had the "failed to query" error. It is also armeabi-v7a on Android 8.1.0. However, my wife's old Nokia 6.1 (Android 10) seems fine and is on arm64-v8a.

**Comment by martixy** [comment] 2021-08-06 22:09
> 92.0a1 (Build #2015826521)
AC: 92.0.20210806164329, cd1cd3e9b6
GV: 92.0a1-20210806132505
AS: 81.0.1 

Just installed nightly with the intent of testing general add on support. Add-ons do not work in any way, shape or form.

1. Simply going to the add on page gives the "failed to query" error.
2. Trying to install any officially supported add-on fails.
3. Trying to install a collection does not do anything.

Device is my old nexus 7 with android 7.1.

**Comment by SpandexWizard** [comment] 2021-08-07 00:30
i have an LG lm-x210cm (i dont remember the plebian name x.x)  it's running android 8.1.0

**Comment by quadriflax** [comment] 2021-08-08 11:30
92.0a1 (Build #2015826793)
AC: 92.0.20210808010301, 89d8b40587
GV: 92.0a1-20210807214822
AS: 81.0.1

Seems latest nightly (8 Aug) had fixed the issue. Moto G5+, Samsung tablet, and LG tablet work as intended (ie, able to load and install addons without issue). I see from Bugzilla that you've rolled back some changes, so if you need anything from me to help get further, just let me know.

**Comment by x2k13** [comment] 2021-08-09 09:03
> 92.0a1 (Build #2015826793)
> AC: 92.0.20210808010301, 89d8b40587
> GV: 92.0a1-20210807214822
> AS: 81.0.1
> 
> Seems latest nightly (8 Aug) has fixed the issue. Moto G5+, Samsung tablet, and LG tablet work as intended (ie, able to load and install addons without issue). I see from Bugzilla that you've rolled back some changes, so if you need anything from me to help get further, just let me know.

Yes and no. Fixed on my Samsung tablet, Android 10 (stock), but not on my Samsung phone, Android 11 (LineageOS 18.1). Same build, just checked again, just to be sure.  Same settings in Fenix Nightly on both devices. Apparently needs some more fixing on Android 11.

**Comment by Amejia481** [comment] 2021-08-09 13:22
Thanks for reporting  @x2k13.
Would you mind sharing which model is your Samsung phone?
If it's not much trouble would you mind sharing the [logcast logs](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information) when you try to install an add-on or enter to the add-ons screen.

**Comment by Amejia481** [comment] 2021-08-09 13:25
Could also attach a print screen of the error @x2k13?  Thanks in advance.

**Comment by x2k13** [comment] 2021-08-09 16:32
> Thanks for reporting @x2k13.
> Would you mind sharing which model is your Samsung phone?
> If it's not much trouble would you mind sharing the [logcast logs](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information) when you try to install an add-on or enter to the add-ons screen.
> Could also attach a print screen of the error @x2k13? Thanks in advance.

Hi @Amejia481 and thanks for the reply. In the meantime I have managed to get it to work. 

Step 1: Quit Fenix in app settings, clear cache, restart browser, clear browser data, remove custom addon collection. 

Step 2: Reboot. 

Now it works like it should again, which is nice.

**Comment by kbrosnan** [comment] 2021-08-09 17:22
Closing, the upstream bug has been resolved.

**Closed by kbrosnan** 2021-08-09 17:22 UTC
Labels: 🐞 bug, Feature:WebExtensions

**Comment by maxtheaxe** [comment] 2022-01-31 20:15
Unfortunately, I just installed Nightly and am running into this issue on multiple devices.
