### ISSUE TITLE
[Bug] - too many icons in toolbar???

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#17047] opened 2020-12-15 14:24 UTC
On some pages I now have 6 icons in the toolbar (shield, padlock, autoplay, Reader, tab counter, hamburger). That's a lot.  And now I only have room for about 13 characters of URL text. That's not much.

IMHO this is too much icon and too little text.

(Personally I would like to be able to hide the autoplay icon, it's wasted space for me I never allow anything to play)

![Toolbar](https://user-images.githubusercontent.com/40568887/102227116-183ac300-3ee1-11eb-850e-48ce669a63e7.jpg)

**Comment by Dunexus** [comment] 2020-12-15 16:06
See https://github.com/mozilla-mobile/fenix/issues/3727 about previous concerns about visible url width.
With the recent addition of the autoplay button, the issue is coming back.

**Comment by Amejia481** [comment] 2020-12-15 16:25
Thanks for reporting,  this is the worst case scenario as you are in page that can be use in reader mode plus some content has been blocked from playing. We could use the space more efficiently by reducing the gap between the security icon and the autoplay one. 

The icon is only visible in pages where some content is blocked from playing, same as in desktop if the content is allowed the icon will disappears.  

This icon will be multipurpose to allow users to know when some sites are using some privacy sensitive permissions of your devices similar to what Firefox desktop does. For example, when a site is using your camera/mic/location a camera/mic/location icon will show.

**Comment by Cheap-Skate** [comment] 2020-12-16 16:17
@Amejia481 thanks for the reply. I completely understand where you're coming from but I am (probably) a power user and I find it too many icons, I wonder whether casual users will understand what's going on. And having only a few characters for the URL is not good, it increases the chance of spoofing.

How about moving all the control icons (shield, padlock, autoplay) to the right, so the URL stays in the same place. Then squish the control icons together into a single "mega icon" :) :) touch target button. Tap that button to bring up a control pane to change how Firefox alters the site's behavior:- eg see certificates, alter TP settings, change autoplay settings.

Ugly? You bet!!!

Green rectangles are touch targets
![Toolbar 2](https://user-images.githubusercontent.com/40568887/102375162-1690fe00-3fba-11eb-9a68-b89d92389f17.png)

**Comment by Dunexus** [comment] 2020-12-16 16:38
@Cheap-Skate I guess keeping some buttons on the left, allows the url part to be centered and probably easier to reach from both sides (ie. for both right and left handed users).

**Comment by Cheap-Skate** [comment] 2020-12-16 16:55
@Dunexus a good point, well made!

@Amejia481 I wonder if the UX team has any feedback on how often users tap the shield, padlock (and now autoplay) icons? I almost never tap shield and never ever tap padlock. I think I will rarely/never tap autoplay icon. I understand they give useful visual feedback, but it feels like about 1/3 of my toolbar is full of big touch targets which I never touch :)

Feel free to close this if you like, it's mostly nit picking. And thanks.

**Comment by Amejia481** [comment] 2021-01-19 20:12
I think we can close this as we have removed the autoplay icon see hhttps://github.com/mozilla-mobile/fenix/pull/17437, the feature will be available on the next nightly version.

**Closed by Amejia481** 2021-01-19 20:12 UTC
Labels: Feature:Toolbar, 🐞 bug
