### ISSUE TITLE
[Regression Bug] Firefox 81 Android - PWA opens with a white screen when Firefox is not open in the background #14095

### ISSUE THREAD

**Issue by pianoworld** [mozilla-mobile/fenix#15509] opened 2020-09-28 21:03 UTC
## Steps to reproduce

visit any PWA website, i.e. trivago.com
Add toHomescreen
close Firefox and close the PWA
open the newly added PWA
The PWA opens only a white screen.

### Expected behavior

It should open the PWA app normally without browser in the back ground

### Device information

Android device: Lenovo TB-8505F, but confirmed on several other devices

First time it  appeared for us on FF79: https://github.com/mozilla-mobile/fenix/issues/14095

**Comment by ekager** [comment] 2020-09-28 21:10
Dupe of https://github.com/mozilla-mobile/fenix/issues/15335 but thank you for the regression window!

**Closed by ekager** 2020-09-28 21:10 UTC
Labels: needs:triage, 🐞 bug
