### ISSUE TITLE
Replace IntentReceiverActivity with MigrationDecisionActivity on cold startup from homescreen to improve perf

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7818] opened 2020-01-21 00:37 UTC
When clicking the homescreen icon, `IntentReceiverActivity` is opened and redirects the user to `HomeActivity`. This is a recent behavior change for migration and may be indicative of a regression.

`IntentReceiverActivity` seems like it also opens applink URLs.

`IntentReceiverActivity` seems expensive for several reasons:
- `IntentReceiverActivity.processIntent` is expensive (81.69ms)
- Running through the Activity lifecycle is expensive (creating, starting, resuming, pausing, and stopping one Activity only to start another one)
  - 32.37ms: performLaunchActivity
  - 5.24ms: handleStart
  - 17.15ms: performResumeActivity
  - 54.63ms: performTraversals (for a frame never drawn)
  - 14.53ms: executeLifecycleState (for pause)
  - Total: 123.92ms
  - Excludes starting HomeActivity (which, to be fair, some of the lifecycle work done above may not happen here again)

### Priority
**Difficulty** (1-5): 3? 4? Requires coordination with other teams, complex flow tightly coupled with app launch from many configurations

**Impact** (Pixel 2):
  - `forPerformanceTest`: ~150ms+ ?
  - production: ?

### Questions
- Why is IntentReceiverActivity in the startup path at all? HomeActivity is most commonly used so can it redirect to other activities as necessary?

Work with Sebastian and Jonathan, who originally landed these changes, on if it can change.

**Comment by jonalmeida** [comment] 2020-01-22 03:46
A reference issue for evaluating the multiple entry points into the app.

**Comment by mcomella** [comment] 2020-01-22 19:41
To summarize the less prescriptive problem statement in comment 0, for this issue my understanding is that the primary problem is that we’re routing all of our Intents through a separate, headless activity and then delegating to the Activity that actually needs to handle them. This additional Activity adds non-trivial overhead and maybe perceived performance issues when clicking on the homescreen icon. My naive solution is to route everything through HomeActivity - which handles most of our requests anyway - and delegate from there as necessary.

**Comment by pocmo** [comment] 2020-01-23 10:46
@mcomella What does the question mark behind 150ms mean? Are there more measurements required? I wonder how the full startup compares to the previous state, not looking at this activity in isolation.

Some background on why this change was made:

The migration has two requirements:
- The data migration needs an exclusive lock on the database. We can't let other code access the database since it will likely deadlock / ANR.
- We need to show a modal migration UI for all app entry points while a migration is ongoing.

We chose to let launcher intents go through `IntentReceiverActivity` because:
- This is already a "router activity" and therefore seemed like a good place to handle all entry points and redirecting them to the migration screen if needed.
- The other option of jumping from the `HomeActivity` to the migration screen seemed very risky: `HomeActivity` does a ton of stuff. We'd need to short-circuit all of that to prevent the app launching into the browser even temporarily. In addition to that our migration checks would need to be called quite often in the HomeActivity - even if there's no need for them anymore (as opposed to one check in IntentReceiverActivity for one intent).

**Comment by pocmo** [comment] 2020-01-23 13:00
I did some simple measurements - measuring the time from `IntentReceiverActivity.onCreate()` to `HomeActivity.onCreate()` (with `SystemClock.elapsedTime()`).

Some observations:
- A cold start (new app process) is 3x slower than a warm start (app process already running) - in my case avg 367ms vs. 111ms (4 measurements). This seems to hint at the main thread being busy with a bunch of other things on process start. I assume this slowdown effect is independent from which activity we launch.
- `IntentReceiverActivity` launches a coroutine to process the Intent (even though _almost_ all processor could be synchronous) - which comes with an overhead. Performing this blocking (but still calling the `suspend` methods) only took 88% (cold start) and 55% (warm start) of the time.
- Directly jumping from `IntentReceiverActivity` to `HomeActivity` without any additional code took only 55% (cold) and 24% (warm) of the time (compared to the unmodified version). I assume this means that there's some time that could be saved by processing the intents more efficiently (e.g. no coroutine if not needed, not looping twice over the list of processors to perform tasks on them).

With those measurements I was interested in whether there's the option to improve the current situation (since as described that has quite some benefits while we are shipping the migration code).

**Comment by liuche** [comment] 2020-01-23 21:26
Adding this to the Fenix AC board bc this is possibly a perf startup regression, and we need to prioritize this to hit our perf goals for shipping.

**Comment by mcomella** [comment] 2020-01-24 01:17
> I was interested in whether there's the option to improve the current situation

I'm curious about this too. My thoughts are:
- If we don't launch any coroutines, we don't waste time adding processing for scheduling (both by the Android framework and the coroutine libs)
- Currently, we're doing a view hierarchy traversal to layout and draw a frame we never actually draw (because the Activity is transparent). If we can avoid this, we'll save ourselves all that time
  - I think this might be because we yield the UI thread in `onCreate` via coroutines (instead of `finish()`ing) so the framework assumes we want to draw
- I noticed we no longer draw the white frame before we launch into the activity: I'm not sure if this was intentionally disabled, if this was a result of Activity redirection, a result of yielding the UI thread, or what. If we can re-enable this frame, it may improve perceived performance

I suspect this change results in the behavior of #7880 so we'll want to make sure we can fix that behavior if we try the options above.

---

To answer some of your questions:

> @mcomella What does the question mark behind 150ms mean?

Without actually making the change to improve performance, it's often difficult to take accurate measurements of its impact so I put a "?" to indicate the measurement is estimated. In this case, I added together the items I saw from the profile but there may have been methods I missed.

> Are there more measurements required?

We're short on time so it's not worth getting truly accurate measurements: we get just enough to prioritize issues but suspecting impact.

> I wonder how the full startup compares to the previous state, not looking at this activity in isolation.

With our existing numbers, this is hard to quantify. On Nimbledroid, we saw a regression from 1.69s to 1.89s but ND has been _very_ noisy and that change includes all of the changes that landed that day including moving Glean.initialize to run first. Note that ND milliseconds are not comparable to the profiles I took here due to different devices.

I'd estimate that getting up-to-date numbers would take > 20 minutes to do so I'm not sure it's worth the time. Also, it might not be feasible: sometimes checking older commits is broken due to SNAPSHOTs changes.

**Comment by mcomella** [comment] 2020-01-24 01:20
(if you get a duplicate email, it's because I accidentally hit submit. I noted below where I added additional content)

> I was interested in whether there's the option to improve the current situation

I'm curious about this too. My thoughts are:
- If we don't launch any coroutines, we don't waste time adding processing for scheduling (both by the Android framework and the coroutine libs)
- Currently, we're doing a view hierarchy traversal to layout and draw a frame we never actually draw (because the Activity is transparent). If we can avoid this, we'll save ourselves all that time
  - I think this might be because we yield the UI thread in `onCreate` via coroutines (instead of `finish()`ing) so the framework assumes we want to draw
- I noticed we no longer draw the white frame before we launch into the activity: I'm not sure if this was intentionally disabled, if this was a result of Activity redirection, a result of yielding the UI thread, or what. If we can re-enable this frame, it may improve perceived performance

I suspect the IntentReceiverActivity change results in the behavior of #7880 so we'll want to make sure we can fix that behavior if we try the options above.

(if you're reading from the duplicate email, I added these lines in the middle)

We should try these out in the short term to see if we can get acceptable performance for GA. I'm happy to hack on this with you: perhaps we can do this in Berlin?

> This is already a "router activity" and therefore seemed like a good place to handle all entry points and redirecting them to the migration screen if needed.

In the long term, using `IntentReceiverActivity` as a router `Activity` seems likely to have a non-negligible performance impact so we may want to change this post-migration.

---

To answer some of your questions:

> @mcomella What does the question mark behind 150ms mean?

Without actually making the change to improve performance, it's often difficult to take accurate measurements of its impact so I put a "?" to indicate the measurement is estimated. In this case, I added together the items I saw from the profile but there may have been methods I missed.

> Are there more measurements required?

We're short on time so it's not worth getting truly accurate measurements: we get just enough to prioritize issues but suspecting impact.

> I wonder how the full startup compares to the previous state, not looking at this activity in isolation.

With our existing numbers, this is hard to quantify. On Nimbledroid, we saw a regression from 1.69s to 1.89s but ND has been _very_ noisy and that change includes all of the changes that landed that day including moving Glean.initialize to run first. Note that ND milliseconds are not comparable to the profiles I took here due to different devices.

I'd estimate that getting up-to-date numbers would take > 20 minutes to do so I'm not sure it's worth the time. Also, it might not be feasible: sometimes checking older commits is broken due to SNAPSHOTs changes.

**Comment by pocmo** [comment] 2020-01-24 09:03
I have the following proposal, which is not perfect but buys us some time and reverses the impact for `fenix` builds while also improving the situation for `fennec` builds - and, most importantly, does not add risk to the ongoing migration by changing the flow completely.

1. We change `AndroidManifest.xml` to have the activity alias point to `HomeActivity` again. -> No regression in Fenix builds anymore.
2. We use our [existing migration AndroidManifest.xml override](https://github.com/mozilla-mobile/fenix/blob/master/app/src/migration/AndroidManifest.xml) to override the activity alias for Fennec builds (this seems to work nicely locally).
3. We point the activity alias in Fennec builds to a "decision activity" that launches into the migration screen or the home activity. This activity does not need anything from the `IntentReceiverActivity` (like intent processors or the async coroutine)  and therefore can be much faster (smaller "regression" [negligible?] in fennec builds).

Like some other things this is again a temporary construct while we need to migrate. Eventually this can be teared down again.

Also, unrelated to this issue, I wonder if we should look into cold `IntentReceiverActivity` starts in general - because they should have been always slow and clicking links in apps seems to be an important entry point (maybe even more than normal app launches?).

**Comment by pocmo** [comment] 2020-01-24 12:53
Trying to write a patch for the proposal above and will put it up for discussion.

**Comment by pocmo** [comment] 2020-01-24 13:57
While trying and testing different variants and comparing to the default (Going directly to `HomeActivity`) I noticed that the time to a full drawn UI is the same; but in the "router activity" case we are seeing the home screen longer (transparent activity), while in the "home activity" case we see a white screen for roughly the same time until the UI appears. However going to the white screen directly _feels_ faster. So then I tried to have my router activity have a white background and switch to the home/migration activity immediately without an animation. That feels a lot faster. So this makes me hope that we can also improve the perceived performance for fennec builds.

**Comment by mcomella** [comment] 2020-01-25 01:23
I haven't seen the PR yet but I'll comment on the high-level approach mentioned here.

> We change AndroidManifest.xml to have the activity alias point to HomeActivity again. -> No regression in Fenix builds anymore.
>
> We use our existing migration AndroidManifest.xml override to override the activity alias for Fennec builds (this seems to work nicely locally).

We can leave further discussion for Berlin as planned but to mention briefly, I think we should make the behavior in Fenix builds the same as Fennec builds. If there is a performance regression that affects our Release and Beta users, our Nightly users should see it too, especially considering most of us use Nightly day-to-day and we want to know what they will experience.

> We point the activity alias in Fennec builds to a "decision activity" that launches into the migration screen or the home activity. 

This seems reasonable to me.

> I wonder if we should look into cold IntentReceiverActivity starts in general(maybe even more than normal app launches?).

We're focusing on cold startup to homescreen right now with the expectation that some of the fixes here will improve cold startup via app link. However, cold startup via app link is another one of our release criteria and we plan to revisit our priorities in Berlin. Thanks for pointing this out though.

---

> I noticed that the time to a full drawn UI is the same;

How did you measure this? We've found it's tricky to get this number reliably and are still working to perfect it. Logcat's "Fully drawn" duration may represent that value but it's instrumented by us so is liable to break when we're changing the startup code.

> but in the "router activity" case we are seeing the home screen longer (transparent activity), while in the "home activity" case we see a white screen for roughly the same time until the UI appears.

Good find! It sounds like this roughly restores the original behavior which sounds like a good start to me!

**Comment by mcomella** [comment] 2020-01-25 02:33
I believe this fix addresses https://github.com/mozilla-mobile/fenix/issues/7880 so I put that issue into the triage queue.

**Comment by mcomella** [comment] 2020-01-25 03:08
I filed some follow-up bugs:
* For porting these fixes to IntentReceiverActivity: https://github.com/mozilla-mobile/fenix/issues/7926
* Removing "router" activities: https://github.com/mozilla-mobile/fenix/issues/7927 (I assume this is post-migration)
  * Maybe a dupe of https://github.com/mozilla-mobile/fenix/issues/7791

@pocmo Is there more work to be done in this issue? I figured not so I renamed the issue for what changed. If that was in error, feel free to fix. Otherwise, would you mind adding QA labels and such? Thanks for your help! :)

**Comment by mcomella** [comment] 2020-02-05 21:45
@pocmo Ping on ^

**Comment by pocmo** [comment] 2020-02-06 12:43
Thank you for filing the follow-up issues. I think we can close this now.

**Closed by pocmo** 2020-02-06 12:43 UTC
Labels: eng:performance

**Comment by ebalazs-sv** [comment] 2020-02-21 09:42
Hi! I had tested this on Beta Migration build 2/19, Nightly Migration build 2/14 with Huawei P9 Lite (Android 7), LG G7 fit (Android 8.1) and there is no delay when tapping the Fenix Beta and Fenix Nightly icon.
@mcomella Are there others scenarios that we can verify on this issue? Thanks!

**Comment by ebalazs-sv** [comment] 2020-03-02 09:23
@pocmo Can you please share your opinion regarding the verification of this bug? Is there another scenario that can be tested here? Thanks!

**Comment by ebalazs-sv** [comment] 2020-03-02 12:44
Discussed with pocmo about this and as it was tested in the previous comment, we can move this to Done. Thanks!
