### ISSUE TITLE
Scrolling only menu options in main menu

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#9083] opened 2020-03-10 14:06 UTC
### Why/User Benefit/User Problem

Currently Firefox Preview has got many options in main menu (visible after clicking hamburger icon on tab with page) and this menu needs to be scrolled sometimes, in the same time icons on top are probably the most often used (that's why they're there) and they're hidden.

![Screenshot_20200310-001923_Firefox Nightly](https://user-images.githubusercontent.com/24834168/76320264-b52c5800-62e0-11ea-8dd8-5e3fc12cc6f0.jpg)

In worst case scenario user after scrolling to menu bottom needs scroll to top to see icons and I suggest small change eliminating it.

### What/Requirements

Please make icons on top of main menu non scrollable - only menu options should scroll

### Acceptance Criteria (how do I know when I’m done?)

Icons are always visible on top of main menu.

Note: I have not found similar FR in existing issues (maybe it's hidden somewhere...)

**Comment by mcarare** [comment] 2020-03-10 14:35
This should be improved by https://github.com/mozilla-mobile/fenix/issues/8474 and https://github.com/mozilla-mobile/fenix/issues/8319.

**Comment by cadeyrn** [comment] 2020-03-10 14:37
Duplicate of #8986.

**Comment by marcinwiacek** [comment] 2020-03-10 14:40
I just realized, that I can close issue... Thank you and sorry for duplicate.

**Closed** 2020-03-10 14:40 UTC
Labels: needs:triage, 🌟 feature request
