### ISSUE TITLE
Share swipe to delete logic across fragments

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#14130] opened 2020-08-24 21:19 UTC
We currently have 3 re implementations of `SwipeToDeleteCallback`: the original class, `BookmarkTouchHelper`, and `TabsTouchHelper`. This logic should be extracted and shared in a base class.

**Comment by Ankita13-code** [comment] 2020-12-21 17:12
hey @NotWoods! I would like to work on this issue. Can you assign it to me?

**Comment by ekager** [comment] 2020-12-21 23:25
Assigned you @Ankita13-code ! Let me know if you have any questions

**Comment by Ankita13-code** [comment] 2020-12-22 10:23
Yeah sure! Thanks @ekager

**Comment by Ankita13-code** [comment] 2020-12-23 14:26
@ekager I've been trying to build the app quite for sometime now, but everytime it is crashing with following exception - 
java.lang.RuntimeException: StrictMode ThreadPolicy violation

Here are the complete logs:

      E/AndroidRuntime: FATAL EXCEPTION: main
          Process: org.mozilla.fenix.debug, PID: 6268
          java.lang.RuntimeException: StrictMode ThreadPolicy violation
              at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1705)
              at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$handleViolationWithTimingAttempt$0(StrictMode.java:1619)
              at android.os.-$$Lambda$StrictMode$AndroidBlockGuardPolicy$9nBulCQKaMajrWr41SB7f7YRT1I.run(Unknown Source:6)
              at android.os.Handler.handleCallback(Handler.java:873)
              at android.os.Handler.dispatchMessage(Handler.java:99)
              at android.os.Looper.loop(Looper.java:201)
              at android.app.ActivityThread.main(ActivityThread.java:6810)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
           Caused by: android.os.strictmode.DiskReadViolation
              at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
              at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
              at java.io.File.exists(File.java:815)
              at miui.util.TypefaceUtils.<clinit>(TypefaceUtils.java:327)
              at miui.util.TypefaceUtils.replaceTypeface(TypefaceUtils.java:557)
              at android.widget.TextView.replaceTypeface(TextView.java:3954)
              at android.widget.TextView.setTypeface(TextView.java:3943)
              at android.widget.TextView.setTypeface(TextView.java:2164)
              at androidx.appcompat.widget.AppCompatTextView.setTypeface(AppCompatTextView.java:711)
              at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2054)
              at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2025)
              at android.widget.TextView.applyTextAppearance(TextView.java:3664)
              at android.widget.TextView.<init>(TextView.java:1515)
              at android.widget.TextView.<init>(TextView.java:886)
              at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:100)
              at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
              at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:194)
              at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:115)
              at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1551)
              at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1602)
              at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
              at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
              at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
              at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
              at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
              at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
              at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:188)
              at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
              at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
              at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
              at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2236)
              at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2009)
              at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1965)
              at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
              at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
      E/AndroidRuntime:     at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
              at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
              at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
              at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
              at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
              at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
              at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
              at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
              at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
              at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
              at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
              at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
              at org.mozilla.fenix.HomeActivity.onStart(HomeActivity.kt:310)
              at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
              at android.app.Activity.performStart(Activity.java:7252)
              at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2970)
              at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
              at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
              at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
              at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
              at android.os.Handler.dispatchMessage(Handler.java:106)
        	      ... 5 more

**Comment by Vicarious1** [comment] 2021-06-17 02:16
@ekager is this still an issue? 

It doesnt look like BookmarkTouchHelper exists (removed in https://github.com/mozilla-mobile/fenix/commit/2be3fd05f2bc604b69033f9de474735bbc4671e8) any more and TabsTouchHelper no longer seems to share any logic with SwipeToDeleteCallback

**Comment by kbrosnan** [comment] 2021-08-20 18:08
Emily is not on this project any more. We removed swipe to delete bookmarks. @amedyne is there any work left here?

**Comment by amedyne** [comment] 2021-08-23 20:46
Closing this as we do not have the swipe to delete bookmarks.

**Closed by amedyne** 2021-08-23 20:46 UTC
Labels: good first issue, eng:ready, eng:health, Feature:Bookmarks, Feature:Tabs, help wanted
