### ISSUE TITLE
[Bug]: Android 12 Elastic Overscroll Leaving Page Stretched

### ISSUE THREAD

**Issue by georgecoffey** [mozilla-mobile/fenix#23364] opened 2022-01-22 07:35 UTC
### Steps to reproduce

1. Open a tab to a page with regular scrolling (https://github.com/mozilla-mobile/ for example)
2. Scroll to the bottom of the page. You should see the Android 12 "Rubber Band" / bounce / elastic scroll as you get to the bottom of the page and try to scroll.
3. With your finger on the bottom of the page, slowly slide your finger upwards taking about a full second.

The page will stretch as you move your finger up, but will not bounce back to normal, and will stay stretched until you trigger the lower stretch effect again. You may not be able to see the top of the page if it's stretched.

### Expected behaviour

Any attempt to scroll lower that activates the elastic scroll should return the stretch to normal after. The Firefox settings page displays the correct behavior.

### Actual behaviour

Page stays stretched if scroll is slow

### Device name

OnePlus 9 5G

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

96.2.0

### Additional information

![Screenshot_2022-01-21-23-32-06-90_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/10283743/150629452-b26aa839-933d-4d85-91c2-354ea8908f16.jpg)
![Screenshot_2022-01-21-23-33-00-06_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/10283743/150629453-8d8e62f5-0e31-4875-a40b-ba4b0e36f932.jpg)

**Comment by georgecoffey** [comment] 2022-01-22 07:44
Tested and confirmed it happens with 98.0a1 nightly on my one plus 9

**Comment by kbrosnan** [comment] 2022-01-24 16:39
duplicate of bz-1710708 via 1738691

**Closed by kbrosnan** 2022-01-24 16:39 UTC
Labels: 🐞 bug, needs:triage
