### ISSUE TITLE
[Bug]Graphic corruption/glitch on pages 

### ISSUE THREAD

**Issue by PulkitGupta707** [mozilla-mobile/fenix#13153] opened 2020-07-31 07:42 UTC
Steps to reproduce: Appears randomly

Expected behavior: There shouldn't be any corruption/glitch. This is happening after yesterday's update.

Actual behavior: When i open a page there is some pixelated graphic corruption .

Device information Realme C3 running on android 10

* Android device: Android 10
* Fenix version: Firefox beta 79.1.0-beta.1

![Screenshot_2020-07-31-13-03-12-04](https://user-images.githubusercontent.com/29430395/89012219-5738f500-d301-11ea-988b-db7e74dcb388.jpg)
![Screenshot_2020-07-31-13-02-17-06](https://user-images.githubusercontent.com/29430395/89012221-5902b880-d301-11ea-9db7-30885eaa5073.jpg)

**Comment by PulkitGupta707** [comment] 2020-07-31 07:42
![Screenshot_2020-07-31-13-12-35-78](https://user-images.githubusercontent.com/29430395/89012250-6a4bc500-d301-11ea-8a80-8af39b2234f0.jpg)
![Screenshot_2020-07-31-13-12-22-51](https://user-images.githubusercontent.com/29430395/89012253-6b7cf200-d301-11ea-9aff-54e0eb6764e8.jpg)
They are on this page as well

**Comment by jamienicol** [comment] 2020-08-05 17:35
This looks very similar to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1558374), and I can see that the Realme C3 has a Mali-G52 GPU, which would be affected.

@PulkitGupta707, can you check whether webrender is enabled by visiting about:support and reading what it says under "Compositing". It should say either "OpenGL" or "WebRender". If it says WebRender, did you manually enable webrender in about:config at any time?

**Comment by PulkitGupta707** [comment] 2020-08-05 17:45
Yes, web render was enabled and disabling it fixed the issue. Also I don't think web render actually works on mediatek devices?

**Comment by jamienicol** [comment] 2020-08-05 17:54
It's currently only enabled by default on some Adreno devices, other devices work to varying degrees. Some have issues like this, and some don't work at all. This bug should be fixed soon, at which point we may enable it by default on Mali devices such as yours. Please feel free to keep using it if you'd like, and file any more issues you see!

**Comment by estrogently** [comment] 2020-12-10 00:50
After the latest update I'm getting similar but worse glitching on my Android 10 Mali-G77 MP11 device ([screen recording](https://github.com/mozilla-mobile/fenix/files/5669527/Screen_Recording_20201210-010957_Firefox.zip)).

Happening on both my regular install of stable (`84.1.0-rc.1 (Build #2015780291); AC: 67.0.10, 899738987; GV: 84.0-20201207203640; AS: 67.0.01`) as well as a fresh install of nightly (`Nightly 201209 17:01 (Build #2015780427); AC: 70.0.20201209143130, c6d2a41d1; GV: 85.0a1-20201209034903; AS: 67.0.0`), although it's a bit less severe on nightly.

**Comment by jamienicol** [comment] 2020-12-10 15:25
Thanks for letting us know @estrogently. That looks like #16469, which should be fixed for the final 84.1.0 release

**Comment by estrogently** [comment] 2020-12-10 23:51
> 
> 
> Thanks for letting us know @estrogently. That looks like #16469, which should be fixed for the final 84.1.0 release and an upcoming nightly.

Thanks! Glad it's known and will (hopefully) be fixed in the final release.
(Not entirely sure why the RC was pushed out as an update for the normal/stable app with WebRender enabled for devices why it was known to be broken then, though)

**Comment by jamienicol** [comment] 2020-12-11 10:18
It wasn't known to be broken at the time. The issue is due to a driver bug Mali-G77.

**Comment by chromer030** [comment] 2021-01-29 15:13
A have a arm64 device with Mali-T760 and exactly this bug , but only with webrenderer , on OpenGL everything is OK , another bug is when playing a YouTube video , browser will crash and fallback to Opengl.
Latest Firefox nightly.

**Comment by jamienicol** [comment] 2021-01-29 15:58
Hi @chromer030 , could you please attach a copy of your about:support information?

**Comment by chromer030** [comment] 2021-01-29 17:57
Hi @jamienicol , Thank you very much for your response , of course.
about:support page has lots of information , hard to copy and paste , so i took 10 continuous screenshots.
I hope it can help to solve these annoying bugs.
Thank you again.

[FirefoxNightly87.zip](https://github.com/mozilla-mobile/fenix/files/5895439/FirefoxNightly87.zip)

**Comment by jamienicol** [comment] 2021-01-29 18:31
That's great, thanks. For future reference there should be a "copy text to clipboard" button at the top of the page

**Comment by jamienicol** [comment] 2021-02-08 19:56
Hi @chromer030, could you please attach a screenshot of the issue? I just want to confirm that it's definitely the same issue as this original bug report.

Could you also please try installing these apks, and seeing if this bug occurs with them? Thanks

1. https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/UfvWukkTS6ijcvYFf-m1wg/runs/0/artifacts/public/build/geckoview_example.apk
2. https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Xri5F9PbQ9GiVjlfFpzXWg/runs/0/artifacts/public/build/geckoview_example.apk

**Comment by chromer030** [comment] 2021-02-09 13:37
He @jamienicol, Of course, Thank you very much for your efforts.
I have blinking Graphical corruptions /glitches, on whatever version of Firefox which uses WebRender, using Firefox in OpenGL mode, no corruptions / glitches.
On YouTube, browser crash when try to play any video and fallback to OpenGL and plays correctly, i think there is a bug between decoder and Webrender.

#### As you can see in this screenshot , the gray rectangle is corruptions /glitches, It's not fixed, it's blinking.
![Screenshot_20210209-163949-01](https://user-images.githubusercontent.com/13361552/107370502-5119a180-6af8-11eb-9e65-77c5376142f5.jpeg)

#### And here the gray rectangle and white one. Blinking forever !

![Screenshot_20210209-164038](https://user-images.githubusercontent.com/13361552/107370851-c2f1eb00-6af8-11eb-89da-732d4144a3e3.png)

### I installed both 1 and 2 apks, same issue :

![Screenshot_20210209-164541-01](https://user-images.githubusercontent.com/13361552/107370958-e452d700-6af8-11eb-9019-3a62cc313431.jpeg)

![Screenshot_20210209-164709-01](https://user-images.githubusercontent.com/13361552/107370964-e74dc780-6af8-11eb-83b1-d78ee61fcfaa.jpeg)

**Comment by jamienicol** [comment] 2021-02-09 14:02
Thanks very much!

From your screenshot, it looks like a different issue than the one previous people in this bug were having, which explains why the second APK didn't make a difference. It might be the same as #16772. Could you try setting `gfx.webrender.allow-partial-present-buffer-age` to false, re-enable webrender if you have disabled it (set `gfx.webrender.force-disabled` to false) force-close firefox (by swiping it away in the app switcher) and restart, and see if that helps? If not, then try setting `gfx.webrender.max-partial-present-rects` to 0, force-close firefox and restart and test again?

For the youtube crashes, does it happen 100% of the time on any youtube video? Do you have any extensions installed or youtube settings to for example force the video format? Could you capture a logcat while attempting to play a video and attach that to this bug?

Thanks, your help is much appreciated :smile:

**Comment by chromer030** [comment] 2021-02-09 14:38
Wow, It worked (gfx.webrender.allow-partial-present-buffer-ag = false) , Thanks very much, No glitches anymore.
For YouTube Videos, Yes, with WebRender it happen 100 % of the time with any YouTube Video.
I just have DarkReader and Ublock, i disabled both and tried, the issue persists, and browser crash.
( I always send crash report to mozilla 🤓)
![Screenshot_20210209-175817-01](https://user-images.githubusercontent.com/13361552/107378237-03edfd80-6b01-11eb-9ca5-33e4996acf4c.jpeg)

#### here is logcat :
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/5952009/logcat.txt)

According to logcat Firefox cannot recognize and uses decoder and formats, while my device has nearly full codecs support :
![a](https://user-images.githubusercontent.com/13361552/107378980-c047c380-6b01-11eb-833d-bd61f052de1a.png)

**Comment by jamienicol** [comment] 2021-02-09 15:09
That's great news. If you're interested, basically that pref decides whether we use an OpenGL extension (KHR_partial_update). It's simply an optimization that allows us to render only the part of the screen that has changed rather than the whole screen, but unfortunately it appears to be buggy on some Mali-T devices. I'm going to disable it by default on Mali-T devices, so just feel free to leave that pref disabled.

For the youtube issue I think the codecs are fine. The problem I can see in the logcat is:
```
webrender::device::gl: Failed to compile shader: composite
webrender::device::gl: 0:5: P0003: Warning: Extension 'GL_OES_EGL_image_external_essl3' not supported
webrender::device::gl: 0:9: L0001: Typename expected, found 'samplerExternalOES'
Gecko   : [GFX1-]: wr_renderer_render: Shader(Compilation("composite", "0:5: P0003: Warning: Extension \'GL_OES_EGL_image_external_essl3\' not supported\n0:9: L0001: Typename expected, found \'samplerExternalOES\'\n"))
Gecko   : [GFX1-]: Fallback (SW-)WR to Basic
```

Currently we try to use an extension OES_EGL_image_external_essl3 to render the video frames. I can see in your about:support that your device doesn't support this extension (though it does support OES_EGL_image_external without the essl3.) This is an oversight on our part - we need to find an alternative way to render the frames. I'm afraid I don't have a pref you can change to fix this, but hopefully I can find a proper fix soon. I filed [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1691730) for tracking that issue.

**Comment by kbrosnan** [comment] 2021-07-06 21:21
looks like there is platform work that resolved this issue. closing

**Closed by kbrosnan** 2021-07-06 21:21 UTC
Labels: b:web-content, needs:gecko, 🐞 bug
