### ISSUE TITLE
[Bug] Prompt to save login despite login already being saved

### ISSUE THREAD

**Issue by caugner** [mozilla-mobile/fenix#8992] opened 2020-03-05 14:24 UTC
## Steps to reproduce

1. Login to a website using Lockwise (by selecting login data already saved).

### Expected behavior

Firefox should *not* ask me whether I want to save this login (as it's already saved).

### Actual behavior

Firefox displays a `Do you want Firefox Nightly to save this login?` prompt.

### Device information

* Android device: Fairphone FP2
* Fenix version: `75.0a1-2020030408140`

**Comment by sv-ohorvath** [comment] 2020-06-24 08:46
similar issue: https://github.com/mozilla-mobile/fenix/issues/8786

**Comment by softvision-miralobontiu** [comment] 2020-12-04 13:34
I'm closing this issue because it is a duplicate of #8786.

**Closed by softvision-miralobontiu** 2020-12-04 13:34 UTC
Labels: Feature:Logins, S2, needs:triage, 🐞 bug
