### ISSUE TITLE
[Bug]: HTML validation message doesn't show

### ISSUE THREAD

**Issue by mikenosko** [mozilla-mobile/fenix#20714] opened 2021-08-06 12:54 UTC
### Steps to reproduce

GoTo: https://codepen.io/mikenosko/pen/qBmJYdz
Click: 'Submit'

### Expected behaviour

A message popping up saying the field is required.

### Actual behaviour

Nothing happens... It seems the validation does fail - reportValidity() returns false, but there is no message notifing about it. This works on desktop Firefox browser, Chrome, Chrome on Android and Safari (not sure about iOS Safari...)

### Device name

OPPO Find X3

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

90.1.3

**Comment by cadeyrn** [comment] 2021-08-06 13:02
Duplicate of #20136 and https://bugzilla.mozilla.org/show_bug.cgi?id=1510450.

**Closed** 2021-08-09 17:03 UTC
Labels: 🐞 bug, needs:triage
