### ISSUE TITLE
[Bug]: Fenix fails to turn into landscape mode at some situation

### ISSUE THREAD

**Issue by misonln41** [mozilla-mobile/fenix#21987] opened 2021-10-18 14:17 UTC
### Steps to reproduce

1. Install any PWA which works on landscape mode (e.g. アイドルマスターシャイニーカラーズ)
2. Launch the PWA from homescreen

or

1. Turn into fullscreen mode with any video (e.g. YouTube)
2. Back to homescreen (and then Picture-in-Picture popup will be shown)
3. Tap `⛶` to go back to fullscreen watching

### Expected behaviour

Fenix turn into landscape fullscreen mode

### Actual behaviour

Fenix turn into landscape mode for half a tick, and then go back to portrait mode

https://user-images.githubusercontent.com/46831731/137748484-6bf7daa2-50c9-40ce-8d57-b82ec5c98ea5.mp4

https://user-images.githubusercontent.com/46831731/137748994-fdb87273-111f-43f1-b200-9adffbc908cf.mp4

### Device name

motorola edge s pro

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1 (Build #2015839755)

**Comment by sflorean** [comment] 2022-04-20 11:48
This is a PIP issue. Closing as duplicate of #9910.

**Closed by sflorean** 2022-04-20 11:48 UTC
Labels: 🐞 bug, Feature:Media, wontfix
