### ISSUE TITLE
Firefox Nightly copies/shares URL from previous tab

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#17791] opened 2021-02-03 12:25 UTC
Steps to reproduce...

1. Ensure your Firefox Nightly on Android has at least one tab (I have lots!)
2. Launch a new Firefox tab using an external app
3. Copy or share the URL

Result...
The PREVIOUS tab's URL is copied/shared!!!

Expected...
The CURRENT tab's URL is copied/shared

NOTE: Toggling to another tab and back again restores expected copy/share behaviour.

Previously filed as bz-1687103

**Comment by mcarare** [comment] 2021-02-04 09:58
I cannot reproduce this on latest master.

**Comment by mrandreastoth** [comment] 2021-02-08 09:31
Compared to the original issue, which was 100% reproducible, this time it is very intermittent. In fact, I think it is more likely to be triggered by opening a new tab and tapping the address bar, and then sharing, but, once again, it's random.

**Comment by mrandreastoth** [comment] 2021-02-13 12:04
This is a serious issue that's impacting me daily and had caused me much embracement having publicly posted and sent wrong links to people simply because of this serious bug. A bug like this MUST be considered a serious breach of user privacy and even security since people could share secret URLs that contain confidential information, such as login credentials and/or non-public pages. In fact, someone could inadvertently share NSFW URLs without them knowing and could then suffer severe consequences such as job dismissal, etc. As such this issue MUST be taken extremely seriously.

**Comment by Mossop** [comment] 2021-02-19 06:12
I just hit this. I had one other tab open in Fenix however it didn't seem to be loaded? I opened a link from twitter and on trying to share it the wrong url was copied. The url bar showed the correct address until tapping on it to edit at which point it changed to the wrong url. Eventually I realized I there was another tab, switching to the other tab caused that page to load and on switching back sharing and the url bar was working normally again.

**Comment by abonhote** [comment] 2021-03-02 09:18
Could it be that this bug exists in the stable version? I have Firefox for Android 86.1.1 installed, Build #2015794883, and I keep sharing the wrong links to my contacts.

**Comment by qcksilver** [comment] 2021-03-04 07:38
I can confirm this is happening on the stable version. This exact bug has happened to me multiple times recently on Firefox for android version 86.1.1 (Build #2015794883). Really serious bug and also very frustrating.

**Comment by mrandreastoth** [comment] 2021-03-04 08:52
> I can confirm this is happening on the stable version. This exact bug has happened to me multiple times recently on Firefox for android version 86.1.1 (Build #2015794883). Really serious bug and also very frustrating.

Yes, it is a very serious bug and a very frustrating one.

Note that I don't know if this bug applies to internally and/or externally created tabs, i.e., tabs created from another tab or tabs tabs created by launching a link from another app, but I suspect they result in the same issue. However, I do have a workaround for this bug. That is, when I want to share a newly created tab, in fact any tab, I manually change to the tab above it (as per the tab list) then back to the previous tab (the tab I want to share). Sharing then has always shared the correct tab. Please note that I don't know if this workaround works for the copy operation, but I suspect that it does.

**Comment by qcksilver** [comment] 2021-03-04 09:29
> Note that I don't know if this bug applies to internally and/or externally created tabs

Now that you mention it, one of the times this happened to me it was definitely from an external link. I don't remember if the other times were external or internal links.

> However, I do have a workaround for this bug. That is, when I want to share a newly created tab, in fact any tab, I manually change to the tab above it (as per the tab list) then back to the previous tab (the tab I want to share).

Thanks for this, it worked for me. To add on to this, this still worked for me if you change tabs by swiping on the url bar, which makes the process slightly less annoying and quicker than opening up the tab list (though still annoying). Just mentioning this for the people who had forgotten about the swipe to change tabs feature, like I had :)

**Comment by Whisprin** [comment] 2021-03-10 11:51
This bug should be treated as security relevant since it's leaking information to third parties without the users consent.

User wants to share URL A, instead URL B is shared as @mrandreastoth described [above](https://github.com/mozilla-mobile/fenix/issues/17791#issuecomment-778608497).

I was able to reproduce the bug like this:
* Open URL A
* close Firefox (either use your phone so Android will pause the process eventually, or manually remove Firefox from the recents list)
* Open URL B from another app (e.g. mail client)
* Firefox loads URL B and displays the correct URL below the website
* Click into the address bar -> wrong URL is displayed
* Share the URL -> wrong URL is shared

**Comment by codrut-topliceanu** [comment] 2021-03-17 13:26
This does seem like a nasty bug. 
I have not been able to reproduce it though. Tried on the following devices:
Pixel 3xl (android 10) - latest nightly and latest debug master
Motorola E4 (android 7) - latest debug master
OnePlus 6 (android 9) - latest debug master

@Whisprin @mrandreastoth Could you provide some additional details please? App build (Settings -> About), device, android version, URLs used, etc.

**Comment by abodea** [comment] 2021-03-19 15:21
Following the steps from the description, I was not able to reproduce this issue.
On the latest Nightly build 3/19 with Google Pixel 4 XL (11), I tried to reproduce it like this:
 - Launch Fenix and open 5+ tabs
 - Open Gmail, open a new link (tab) from Gmail in Fenix
 - I copied/shared the opened tab, but I had no issues there.

@mrandreastoth can you please attach a video/gif when reproducing this issue?

**Comment by Whisprin** [comment] 2021-03-19 15:33
@abodea Could you please try the steps that I outlined above?
Specifically closing Firefox from memory manually or launching a memory heavy app that will force Android to close Firefox in the background before you open the link from Gmail.

At the same time I'm trying to reproduce it with the latest Nightly.

**Comment by abodea** [comment] 2021-03-19 15:57
Hello, @Whisprin sorry I forgot to mention, I also tried to reproduce it following your steps but with 0 success.
Are you logged in (FF account?)
Do you have any addons installed? 
Can you please attach a video/gif when reproducing it?

**Comment by Whisprin** [comment] 2021-03-20 19:12
Thanks @abodea 
I wasn't able to reproduce it in Firefox Nightly either (not logged in).
However, I'm still able to reproduce it in the current stable version: 86.1.1 (Build #861120, logged in).

No Addons installed in either. Android 10 & 11, Open links in apps disabled in both

**Comment by kbrosnan** [comment] 2021-03-22 03:31
Most recent duplicate mentions nightly as a still problematic.

**Comment by anotherus3r** [comment] 2021-03-22 07:46
If you have problems reproducing the issue, you might have better luck with the steps to reproduce in #18576.

**Comment by rocketsroger** [comment] 2021-03-22 20:22
> If you have problems reproducing the issue, you might have better luck with the steps to reproduce in #18576.

Thanks, I can reproduce using custom tabs.

**Closed** 2021-03-23 14:31 UTC
Labels: Feature:Sharing, Feature:Tabs, 🐞 bug

**Comment by mrandreastoth** [comment] 2021-03-24 18:44
I have been keeping tabs on this issue and have not been able to reproduce it for some time now.
