### ISSUE TITLE
Crash to desktop when attempting to open new tab

### ISSUE THREAD

**Issue by AndyP2002** [mozilla-mobile/fenix#27538] opened 2022-10-25 15:04 UTC
Just now.. Eight tabs open. Try to open new tab with "+" button on taps screen. Display drops back to my normal phone homescreen. Firefox doesn't seem to have crashed as it still appears in the running apps, but when I manually go back to FF the new tab has not opened.

Copied from About/Crashes...
c6f2f144-dd97-4587-a419-a4ac8edb3fae
java.lang.RuntimeException: android.os.DeadSystemException
----
java.lang.RuntimeException: android.os.DeadSystemException
	at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:137)
	at org.mozilla.fenix.utils.ClipboardHandler.getText(ClipboardHandler.kt:2)
	at org.mozilla.fenix.utils.ClipboardHandler.extractURL(ClipboardHandler.kt:1)
	at org.mozilla.fenix.search.SearchDialogFragment$observeClipboardState$1$2.emit(SearchDialogFragment.kt:25)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Emitters.kt:9)
	at org.mozilla.fenix.search.SearchDialogFragment$observeClipboardState$1$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:14)
	at mozilla.components.lib.state.ext.FragmentKt$consumeFlow$1$invokeSuspend$$inlined$filter$1$2.emit(Emitters.kt:8)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:13)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:359)
	at android.app.ActivityThread.main(ActivityThread.java:7418)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@17f8647, Dispatchers.Main]
Caused by: android.os.DeadSystemException
	... 18 more

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21866)

**Comment by kbrosnan** [comment] 2022-10-26 19:13
@mcarare looks like there are some other places where we are overloading the clipboard with text. Previously #22958

**Comment by kbrosnan** [comment] 2022-10-26 19:16
https://crash-stats.mozilla.org/signature/?product=Fenix&signature=android.os.DeadSystemException%3A%20at%20android.content.ClipboardManager.getPrimaryClip%28ClipboardManager.java%29

https://sentry.io/organizations/mozilla/issues/?project=6375561&project=6295546&project=6295551&query=is%3Aunresolved+getPrimaryClip&referrer=issue-list&statsPeriod=14d

**Comment by mcarare** [comment] 2022-10-27 08:19
@AndyP2002 Can you mention what device you are using? Thank you!

**Comment by AndyP2002** [comment] 2022-10-27 08:37
Sure! It's a Sony Xperia XZ2 (H8216) running on Android 10.

**Comment by AdinaPetridean** [comment] 2022-11-23 08:39
Tested on the latest Nightly 109.0a1 (2022-11-23), with Sony Xperia (Android 6.0.1) and the application remains stable when attempting to open tabs while having a large number of characters in clipboard. 
I also tried to reproduce the crash on the older Firefox 106.1.0 and Firefox 105.1.0 versions, but with no luck. 
I will close this as fixed and remove the QA needed label, but @AndyP2002 , can you test again using the latest Nightly to see if the crash is fixed for you? If so, please re-open the ticket. Thanks!

**Closed** 2022-11-23 08:39 UTC
Labels: eng:ready, b:crash

**Comment by delia-pop** [comment] 2022-12-15 13:12
No longer reproducible on Beta 109.0b1 with Lenovo Yoga Tab 11 (Android 11) either.
