### ISSUE TITLE
[Bug] Crash on fresh start on Android SDK <26 due to regexp syntax errors

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3648] opened 2019-06-25 12:08 UTC
## Steps to reproduce
1. Install Firefox Preview from https://tools.taskcluster.net/index/project.mobile.fenix.v2.nightly/latest - the public/target.arm.apk file - through command line.
2. Open the app.

### Expected behavior
The app should open.

### Actual behavior
App crashes continuously. Cannot be opened.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1)
* Fenix version: 1.0.1926 (#11760617)

### Note
On Xiaomi mi4i (Android 5.0.2) the file cannot be installed:
"C:\Users\mirabela.lobontiu>adb install -r fenix.apk
fenix.apk: 1 file pushed. 4.7 MB/s (48862573 bytes in 9.835s)
        pkg: /data/local/tmp/fenix.apk
Failure [INSTALL_FAILED_USER_RESTRICTED]" message is displayed.

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3325112/logcat.txt)

**Comment by colintheshots** [comment] 2019-06-25 18:04
This seems to be a Xiaomi device issue affecting all command line installs and not an app bug. Please try the following steps: https://stackoverflow.com/a/48524656/1412973

**Comment by colintheshots** [comment] 2019-06-25 21:41
It appears that a native crash is occurring in the most recent Megazord libfenix.so builds. I don't have enough details yet to debug, but I do consistently get a tombstone from the crash. It wouldn't be hard to reproduce the crash with symbols intact.

**Comment by ncalexan** [comment] 2019-06-25 23:30
I just get a “boring” crash:
```GeckoProfile  D  Found profile dir.
         AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: org.mozilla.fenix.debug, PID: 2836
                         E  java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 4:
                         E  (?<major>[0-9]+)\.(?<minor>[0-9]+)(?:\.(?<patch>[0-9]+))?(?<metadata>[^0-9].*)?
                         E      ^
                         E      at java.util.regex.Pattern.compileImpl(Native Method)
                         E      at java.util.regex.Pattern.compile(Pattern.java:411)
                         E      at java.util.regex.Pattern.<init>(Pattern.java:394)
                         E      at java.util.regex.Pattern.compile(Pattern.java:381)
                         E      at kotlin.text.Regex.<init>(Regex.kt:89)
                         E      at mozilla.components.concept.engine.utils.EngineVersion$Companion.parse(EngineVersion.kt:71)
                         E      at mozilla.components.browser.engine.gecko.GeckoEngine.<init>(GeckoEngine.kt:133)
                         E      at mozilla.components.browser.engine.gecko.GeckoEngine.<init>(GeckoEngine.kt:38)
                         E      at org.mozilla.fenix.components.Core$engine$2.invoke(Core.kt:84)
                         E      at org.mozilla.fenix.components.Core$engine$2.invoke(Core.kt:42)
                         E      at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                         E      at org.mozilla.fenix.components.Core.getEngine(Core.kt)
                         E      at org.mozilla.fenix.components.Core$sessionManager$2.invoke(Core.kt:105)
                         E      at org.mozilla.fenix.components.Core$sessionManager$2.invoke(Core.kt:42)
                         E      at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                         E      at org.mozilla.fenix.components.Core.getSessionManager(Core.kt)
                         E      at org.mozilla.fenix.FenixApplication.onTrimMemory(FenixApplication.kt:195)
                         E      at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:4251)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:135)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5254)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at java.lang.reflect.Method.invoke(Method.java:372)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

And before that it’s clear that `libfenix.so` is doing fine:
```AppServices  I  Using viaduct_lib_name: fenix
                 linker  W  libjnidispatch.so: unused DT entry: type 0x6ffffffe arg 0x2e2c
                         W  libjnidispatch.so: unused DT entry: type 0x6fffffff arg 0x2
                    art  I  Background sticky concurrent mark sweep GC freed 1600(128KB) AllocSpace objects, 2(32KB) LOS objects, 8% free, 2MB/2MB, paused 8.183ms total 127.296ms
                 linker  W  libfenix.so: unused DT entry: type 0x6ffffffe arg 0x2b14
                         W  libfenix.so: unused DT entry: type 0x6fffffff arg 0x3
                    art  I  Background sticky concurrent mark sweep GC freed 277(13KB) AllocSpace objects, 0(0B) LOS objects, 3% free, 2MB/2MB, paused 10.861ms total 58.025ms
                         W  Suspending all threads took: 5.898ms
                         I  Background partial concurrent mark sweep GC freed 2046(103KB) AllocSpace objects, 2(32KB) LOS objects, 40% free, 2MB/4MB, paused 10.306ms total 113.546ms
            AppServices  I  Using rc_log_ffi_lib_name: fenix
        rc_log_ffi::ios  I  rc_log adapter initialized!
```

Perhaps the pattern syntax has evolved, and we just need to be more careful in a-c to use a backwards compatible syntax?

**Comment by ncalexan** [comment] 2019-06-25 23:33
This is an a-c bug.  It's "merely" that the regex syntax isn't valid before API 26: https://developer.android.com/reference/java/util/regex/Pattern#groupname.  I'll leave somebody else to do the re-filing, etc.

**Comment by pocmo** [comment] 2019-06-26 08:45
Duplicate of #3652 (Affects Android 5.0/5.1)

**Closed by pocmo** 2019-06-26 08:45 UTC
Labels: P1, 🐞 bug, 💥 crash

**Comment by kbrosnan** [comment] 2019-06-26 23:18
Additional signature Sentry issue: [FENIX-NIGHTLY-5N](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/5986691/)
