### ISSUE TITLE
533-1279ms regression + bimodal reintroduced for cold main start up (6/28)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#25919] opened 2022-07-06 20:24 UTC
We see a regression of 533ms from the 6/27 nightly to the 6/28 nightly:

![image](https://user-images.githubusercontent.com/759372/177635974-dea89564-1b47-40a3-95eb-bfb14f78a3db.png)

That increases if we look at 6/27 to 6/29 to 1279ms. We also see a regression on the A51 (but it is still a WIP) so we can probably reproduce this on devices that aren't just the Moto G5.

Bimodal behavior also appears starting in 6/28. **The fast case appears to not have regression but the slow case is where we see the regression.**  Here's 6/27 (before):
![image](https://user-images.githubusercontent.com/759372/177636227-85357e57-48b2-48d3-afce-7fb925aecbb0.png)

And 6/28:
![image](https://user-images.githubusercontent.com/759372/177636273-6477d2da-ac1e-4b3c-b631-b653b9f72319.png)

6/29 for completeness:
![image](https://user-images.githubusercontent.com/759372/177636524-10bb95cd-6414-46f4-925c-c5ca299c28fa.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20930)

**Comment by mcomella** [comment] 2022-07-06 20:39
Triage: we re-enabled the task continuity work on 6/27 so the timing lines up. Another notable work is autofill. We don't know for sure if these are the root cause but it's something we may want to investigate.

**Comment by Amejia481** [comment] 2022-07-08 19:12
Just to make sure we are not biased against the task continuity feature, I'm running the tests on the commits from [6/27 to 6/29](https://github.com/mozilla-mobile/fenix/compare/41755498b8ae2d414e7ac76c24260d5a689cb71c...61807c5316ab2f0db2113e886abb6bb31158aa74).

I found the range from downloading APKs TC [6/27](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.2022.06.27.latest/armeabi-v7a) ([41755498b](https://github.com/mozilla-mobile/fenix/commit/41755498b8ae2d414e7ac76c24260d5a689cb71c))  and [6/29](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.2022.06.29.latest/armeabi-v7a) ([61807c531](https://github.com/mozilla-mobile/fenix/commit/61807c5316ab2f0db2113e886abb6bb31158aa74)) and checking the Fenix commit hash under the about page.

From checking [commits](https://github.com/mozilla-mobile/fenix/compare/41755498b8ae2d414e7ac76c24260d5a689cb71c...61807c5316ab2f0db2113e886abb6bb31158aa74), the ones that are hitting code path of the tests:

## Jun 29, 2022, 3:40 a.m. EDT 883401d8a4d80d58535d014c126009cca38076f6 Build with SDK for Android 12 / API 32.

![883401d8a4d80d58535d014c126009cca38076f6](https://user-images.githubusercontent.com/773158/178051729-0c942293-8741-49ad-8a0b-7a7e2bb2eb64.png)


## Jun 28, 2022, 7:14 p.m. EDT 83e19be3850ff7852580173cfd4dd58175ab796f Enable address autofill for Nightly and Debug

![83e19be3850ff7852580173cfd4dd58175ab796f](https://user-images.githubusercontent.com/773158/178052014-710a6786-7626-43ec-8dd0-e927ee2f0f99.png)


## Jun 28, 2022, 1:42 p.m. EDT a4681de2ec0502ee690e8eb1ad0cc5a608d9986f Update Android Components version to 104.0.20220628153613


![a4681de2ec0502ee690e8eb1ad0cc5a608d9986f](https://user-images.githubusercontent.com/773158/178054489-5db64f75-8402-4f9b-a1eb-f765f6041b92.png)


## Jun 28, 2022, 12:47 p.m. EDT d6952cb2aa01a8b4e1f654840ea0d4efff8327f0 Wait to draw Pocket until after first frame.


![d6952cb2aa01a8b4e1f654840ea0d4efff8327f0](https://user-images.githubusercontent.com/773158/178052280-c6d9e744-aa32-4647-a60e-9ad7210e94a7.png)


## Jun 27, 2022, 7:18 p.m. EDT 6f77be973b7d8806e63369ea34b1d7b67438ced1 Update Android Components version to 104.0.20220627211706.

![6f77be973b7d8806e63369ea34b1d7b67438ced1](https://user-images.githubusercontent.com/773158/178052367-0c9255e3-8d7b-468a-be50-5be10819b618.png)


## Jun 27, 2022, 3:32 p.m. EDT  017d1c4d1c76d3b1076830e3231ace9851896914 Update Android Components version to 103.0.20220627143156.

![017d1c4d1c76d3b1076830e3231ace9851896914](https://user-images.githubusercontent.com/773158/178052538-4feba025-ec53-46e4-8614-4f82c905a90f.png)

**Comment by Amejia481** [comment] 2022-07-08 19:48
As the commit that are more prone to re-introduce the pattern are:

- Jun 28, 2022, 12:47 p.m. EDT https://github.com/mozilla-mobile/fenix/commit/d6952cb2aa01a8b4e1f654840ea0d4efff8327f0 Wait to draw Pocket until after first frame.
- Jun 28, 2022, 7:14 p.m. EDT https://github.com/mozilla-mobile/fenix/commit/83e19be3850ff7852580173cfd4dd58175ab796f Enable address autofill for Nightly and Debug

Given that https://github.com/mozilla-mobile/fenix/commit/d6952cb2aa01a8b4e1f654840ea0d4efff8327f0 re-enabling the tasks continuity  **was merged before** https://github.com/mozilla-mobile/fenix/commit/83e19be3850ff7852580173cfd4dd58175ab796f Enabling address autofill, **so it contains it**.

If I disabled the task continuity feature https://github.com/mozilla-mobile/fenix/commit/d6952cb2aa01a8b4e1f654840ea0d4efff8327f0 in the enabling the autofill setting https://github.com/mozilla-mobile/fenix/commit/83e19be3850ff7852580173cfd4dd58175ab796f  and run the tests.

I don't see the parttern
![Figure_1](https://user-images.githubusercontent.com/773158/178060183-44b39faa-1114-43ad-b3b3-defb0924d791.png)

**Comment by jonalmeida** [comment] 2022-08-24 19:28
We wanted to investigate why our bi-modal regression disappeared recently in the 'Moto G5 COLD MAIN first frame' graph - we narrowed down the change to [a patch][0] that landed which did two things to improve it:

 1. Calling the Account Manager's SyncNow explicitly the IO dispatcher instead of using the `lifecycleScope` (possibly the default dispatcher is quite busy and we should re-evaluate how much work it's doing overall).

![io_dispatcher](https://user-images.githubusercontent.com/1370580/186504652-2a49ec98-44e9-428f-9b4e-5ee5cadab834.png)


 1. Early-returning the `RecentSyncedTabsFeature` if Synced Tabs is not enabled for the user. This avoids drawing a placeholder UI on the screen until the Synced Tabs can be populated in it.

![dispatchSyncedTabs](https://user-images.githubusercontent.com/1370580/186504711-3e24d3be-1274-476a-8086-370408f41120.png)

We wanted to also investigate the [other patch][1] that attempted to solve this performance problem by notifying Pocket to draw to the screen after the rest of the UI is done. This patch did not work because:

 1. The patch was notifying when the UI was done drawing [_too early_][2] in a `onPreDraw` listener for the _root view_.
 2. The code that checked for when it was time to draw Pocket was too late because the expensive Compose initialization had started and was being wasted in the [Pocket ViewHolder][3].

<img width="638" alt="before_roger_" src="https://user-images.githubusercontent.com/1370580/186505059-1094d915-a5b5-4a88-be82-b9b91466cdc5.png">
)

Given this investigation so far, we decided to resolve this problem by:

 1. Notifying when the UI was done drawing _after_ the first layout is done by using the [`RecyclerView.LayoutManager.onLayoutCompleted`][4].
 2. Choosing not to add the Pocket ViewHolders in the [`SessionControlView.normalModeAdapterItems`][5] by checking for the above notification first.

This fix shows minimal perf wins (~15ms faster than before) by introducing our patch along with the patch above that removed this bi-modal regression. However, we still believe this a valuable patch to land because:

 1. It fixes the original patch that attempted to fix the regression.
 2. This is a perf win for our users that have an authenticated Sync account on their devices who would be affected by this perf regression (even though we don't have a dashboard that tracks the perf of this user flow).
 3. The patch that did fix the regression was happenstance for this particular feature - new features that land in the future can still cause this regression to happen again. Our fix is to prevent this regression from showing up again by always telling Pocket to load after we're done laying out our initial features. This means that the expensive Compose initialization will be spent on the features that we are showing on the screen and not on Pocket which is typically off the screen (and we can layout after).

<img width="626" alt="possible_fix_plus_rogers" src="https://user-images.githubusercontent.com/1370580/186505433-ff5640cb-e49a-42a8-88f6-71f59a0113aa.png">

This is the patch we tested, which we will land soon once it's cleaned up and commented appropriately:

<details>

<summary>Rough patch</summary>

```diff
diff --git a/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt b/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
--- a/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
+++ b/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
@@ -12,8 +12,10 @@
 import mozilla.components.feature.tab.collections.TabCollection
 import mozilla.components.feature.top.sites.TopSite
 import mozilla.components.service.pocket.PocketStory
+import org.mozilla.fenix.components.appstate.AppAction
 import org.mozilla.fenix.components.appstate.AppState
 import org.mozilla.fenix.ext.components
+import org.mozilla.fenix.ext.requireComponents
 import org.mozilla.fenix.ext.settings
 import org.mozilla.fenix.ext.shouldShowRecentTabs
 import org.mozilla.fenix.gleanplumb.Message
@@ -38,7 +40,8 @@
     nimbusMessageCard: Message? = null,
     showRecentTab: Boolean,
     recentVisits: List<RecentlyVisitedItem>,
-    pocketStories: List<PocketStory>
+    pocketStories: List<PocketStory>,
+    firstFrameDrawn: Boolean = false
 ): List<AdapterItem> {
     val items = mutableListOf<AdapterItem>()
     var shouldShowCustomizeHome = false
@@ -80,7 +83,7 @@
         showCollections(collections, expandedCollections, items)
     }
 
-    if (settings.showPocketRecommendationsFeature && pocketStories.isNotEmpty()) {
+    if (firstFrameDrawn && settings.showPocketRecommendationsFeature && pocketStories.isNotEmpty()) {
         shouldShowCustomizeHome = true
         items.add(AdapterItem.PocketStoriesItem)
         items.add(AdapterItem.PocketCategoriesItem)
@@ -159,7 +162,8 @@
         messaging.messageToShow,
         shouldShowRecentTabs(settings),
         recentHistory,
-        pocketStories
+        pocketStories,
+        firstFrameDrawn
     )
     is Mode.Private -> privateModeAdapterItems()
     is Mode.Onboarding -> onboardingAdapterItems(mode.state)
@@ -199,6 +203,12 @@
                     super.onLayoutCompleted(state)
 
                     JumpBackInCFRDialog(view).showIfNeeded()
+
+                    containerView.context.components.appStore.dispatch(
+                        AppAction.UpdateFirstFrameDrawn(
+                            drawn = true
+                        )
+                    )
                 }
             }
         }
diff --git a/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt b/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
--- a/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
+++ b/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
@@ -393,10 +393,6 @@
 
         displayWallpaperIfEnabled()
 
-        binding.root.doOnPreDraw {
-            requireComponents.appStore.dispatch(AppAction.UpdateFirstFrameDrawn(drawn = true))
-        }
-
         // DO NOT MOVE ANYTHING BELOW THIS addMarker CALL!
         requireComponents.core.engine.profiler?.addMarker(
             MarkersFragmentLifecycleCallbacks.MARKER_NAME, profilerStartTime, "HomeFragment.onCreateView",
```

</details>

[0]: https://github.com/mozilla-mobile/fenix/pull/26442
[1]: https://github.com/mozilla-mobile/fenix/pull/25738
[2]: https://github.com/mozilla-mobile/fenix/pull/25738/files#diff-41731714e97083a1b73584da2837ab11c22796c25b892b1e86ce4190ebba2633R389
[3]: https://github.com/mozilla-mobile/fenix/pull/25738/files#diff-fc566b4086bce02b57218c47b351d05bb4231357f161cbdde76fae109376be60R47
[4]: https://github.com/mozilla-mobile/fenix/blob/e87cebc85f077cf831737a465a9674fe8cf2f828/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt#L204
[5]: https://github.com/mozilla-mobile/fenix/blob/e87cebc85f077cf831737a465a9674fe8cf2f828/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt#L88

**Comment by jonalmeida** [comment] 2022-08-29 20:19
Removing QA needed since these performance results will be monitored during perf triage to re-validate the gains.

**Closed** 2022-08-29 20:19 UTC
Labels: performance, needs:triage
