### ISSUE TITLE
Copy /paste image to/from clipboard 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#24474] opened 2022-03-27 00:55 UTC
### Steps to reproduce

if I'm not wrong in 2020 chrome for Android added copy paste to/from clipboard feature can fenix get this too ?

### Expected behaviour

Fenix should be able to copy paste image from android clipboard 

### Actual behaviour

feature is lacking in fenix 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

100

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19978)

**Comment by LaurentiuApahideanSV** [comment] 2022-03-30 07:26
I will mark this issue as a feature request.

**Comment by yoasif** [comment] 2022-11-25 02:50
Dupe of https://github.com/mozilla-mobile/fenix/issues/17780.

**Comment by boek** [comment] 2023-01-30 20:24
Closing as a dup #17780

**Closed by boek** 2023-01-30 20:24 UTC
Labels: 🐞 bug, feature request 🌟, qa-triaged
