### ISSUE TITLE
Search bar: gray cursor appears then fades

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#524] opened 2019-02-15 16:52 UTC
Tap the URL to start a search
Search bar appears at top of screen
Gray vertical cursor appears on the right hand side of the search bar
It fades in a couple of second
easiest to see with very short URLs like https://www.theverge.com
screenshot attached

I think this artifact is new in today's build:-
Fenix build 1.0.1907 (Build #10461208 🦎 67.0a1-20190213102848)
Galaxy S7
Android 8.0.0

![screenshot_20190215-164102_fenix](https://user-images.githubusercontent.com/40568887/52871401-e3714f80-3141-11e9-84eb-58cb0f736636.jpg)

**Comment by pocmo** [comment] 2019-02-15 17:14
That almost looks like a scrollbar (see scrollbar in awesomebar)

**Comment by Cheap-Skate** [comment] 2019-02-15 17:39
Yes very plausible, it looks & behaves (fades) like a very small scrollbar.

**Comment by sblatz** [comment] 2019-02-15 18:52
I'm unable to reproduce this on the latest taskcluster build on my GS9 on 8.0.0

**Comment by Cheap-Skate** [comment] 2019-02-16 07:21
Fixed for me too, please close this and I will reopen if it returns.

**Comment by Cheap-Skate** [comment] 2019-02-16 13:22
STR on my Galaxy S7 with Android 8.0.0 & the aarch64 build:-
Kill Fenix
Relaunch Fenix
Navigate to a page eg www.bbc.co.uk
Tap URL at bottom of screen
Searchbar appears correctly without gray "scrollbar"
tap the (invisible) X button right hand side of searchbar to return to page content
tap 3 dot menu
tap Settings
tap left arrow at top of screen to go back to page content
tap URL
-> gray "scrollbar" appears in searchbar and fades after a couple of seconds
it appears every time I open the searchbar, the only way to stop it happening is to kill Fenix

On my older BQ Aquaris X5 running the arm7 build I do not see the gray scrollbar when I follow the STR above.

**Comment by Cheap-Skate** [comment] 2019-02-16 17:34
It's an Android font size issue I think

Only my Sony Xperia X Compact running Android 8.0.0 the steps to reproduce lead to the same "scrollbar" issue but only if I have the Android font size (Android gearwheel icon > Display > Font Size) set to Large. On Default font size the issue does not happen.

On my Galaxy S7 I see the "scrollbar" issue if I have my font size set to the third notch above "Tiny" but not if I have it on the second notch above "Tiny". (Can't remember which notch is the default on Galaxy).

**Comment by boek** [comment] 2019-04-03 21:55
This should be fixed now :)

**Closed by boek** 2019-04-03 21:55 UTC
