### ISSUE TITLE
[webcontent] plato.stanford.edu - Reader mode

### ISSUE THREAD

**Issue by Xashyar** [mozilla-mobile/fenix#16874] opened 2020-12-05 18:33 UTC
## Site with issue and any steps to reproduce
https://plato.stanford.edu/entries/qt-quantcomp/

Reader mode doesn't load, the first part of entries with longer introductions.

*Edit: I also can reproduce this on Firefox-Desktop
### Expected behavior
Reader mode renders the introductory part successfully
### Actual behavior
Reader mode fails to render the introductory part
### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No
### Can you reproduce in Chrome (or other non-Mozilla browser)?

No

### Device information

* Android device: All
* Fenix version: All

**Comment by LaurentiuApahideanSV** [comment] 2020-12-07 12:36
I can confirm the issue is reproducible Firefox Preview Nighlty 201207 using a OnePlus6T (Android 9).

**Comment by kbrosnan** [comment] 2020-12-08 17:38
Closing in favor of https://github.com/mozilla/readability/issues/655

**Closed by kbrosnan** 2020-12-08 17:38 UTC
Labels: Feature:ReaderMode
