### ISSUE TITLE
When "Dark" theme is chosen, Fenix switches languages[Bug]

### ISSUE THREAD

**Issue by mathiesenk** [mozilla-mobile/fenix#8890] opened 2020-03-01 22:09 UTC
Choose Icelandic for Fenix language
Go into Settings - Theme
Choose Dark Theme (the choice before is "Follow device theme")

Expected results: theme color changes and language is still Icelandic

Actual results: theme color changes AND language of Fenix changes to English

When Light theme is chosen, the language does not change

Version of Fenix: Nightly 200228 06:00 (build # 20590607)

Device information: Motorola One Vision with Android 10

**Comment by cadeyrn** [comment] 2020-03-01 22:12
Duplicate of #7559.

**Closed** 2020-03-02 07:11 UTC
Labels: needs:triage, 🐞 bug
