### ISSUE TITLE
[Bug] Autoplay is not working for a muted video

### ISSUE THREAD

**Issue by ksy36** [mozilla-mobile/fenix#7507] opened 2020-01-06 21:02 UTC
As reported here: https://github.com/webcompat/web-bugs/issues/47604

## Steps to reproduce
Visit https://corsolinux.com/ and observe the site 

### Expected behavior
Video starts  
### Actual behavior
Video doesn't start and gray background is displayed
### Device information

* Android device: Samsung Galaxy S5
* Fenix version: Nightly Build #20061806 from 06/1

I've created a reduced test case with just the video tag https://codepen.io/ksy36/pen/abzEaEb

**Comment by BranescuMihai** [comment] 2020-02-17 17:09
Setting the `media.autoplay.default` to 0 in about:config, and/or toggling the permission to 'Video and audio allowed' does nothing for me, no video starts autoplaying, regardless if it's audible or not (even though `GeckoRuntimeSettings` variable `mAutoplayDefault` seems to be set correctly). Tried most links in related bugs:
[https://codepen.io/ksy36/pen/abzEaEb](https://codepen.io/ksy36/pen/abzEaEb)
[https://www.gq.com/story/manny-jacinto-favorite-cameras-clothes-fitness-gear](https://www.gq.com/story/manny-jacinto-favorite-cameras-clothes-fitness-gear)
[https://www.bmw.com/en/innovation/the-development-of-self-driving-cars.html](https://www.bmw.com/en/innovation/the-development-of-self-driving-cars.html)
This one is the best as it contains both audible/inaudible: [https://googlechrome.github.io/samples/muted-autoplay/](https://googlechrome.github.io/samples/muted-autoplay/)

On Chrome they all work. Can someone please re-check if any scenario of autoplay still works?

**Comment by AndiAJ** [comment] 2020-02-18 12:17
Hi @BranescuMihai , indeed, **the auto-play doesn't seem to be working** on none of the above mentioned websites using the latest **`Nightly #20490606 from 2/18`**  with the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)

► Video
![20200218-140858](https://user-images.githubusercontent.com/51314259/74735401-4e73cb80-5259-11ea-91d4-3d5e19343fd6.gif)

**Comment by Baron-Severin** [comment] 2020-02-22 00:10
> On Chrome they all work. Can someone please re-check if any scenario of autoplay still works?

FYI @BranescuMihai I've been working on some fixes to site permissions, and plan to land these two PRs on Monday.  Audible autoplay works with them integrated (although inaudible autoplay is still broken)
https://github.com/mozilla-mobile/fenix/pull/8618
https://github.com/mozilla-mobile/android-components/pull/5953

**Comment by BranescuMihai** [comment] 2020-02-24 07:49
@Baron-Severin I am watching those PRs for a few days now, I was actually hoping the added permissions will solve also the inaudible part :(

**Comment by Amejia481** [comment] 2020-02-26 20:37
Related https://github.com/mozilla-mobile/fenix/issues/5636#issuecomment-591611403

**Comment by ksy36** [comment] 2020-03-04 00:45
@BranescuMihai  looks like this has been fixed, the above mentioned muted videos start playing in the recent Fenix Nightly

**Comment by BranescuMihai** [comment] 2020-03-05 14:08
There's a difference between phones, both on Android 10. 
OnePlus 7TPro is able to view: 
- https://codepen.io/ksy36/pen/abzEaEb

Samsung Note10 is able to view: 
- https://codepen.io/ksy36/pen/abzEaEb
- https://www.gq.com/story/manny-jacinto-favorite-cameras-clothes-fitness-gear (autoplay starts after you refresh)
- https://googlechrome.github.io/samples/muted-autoplay/

For https://www.bmw.com/en/innovation/the-development-of-self-driving-cars.html, I think the problem is because they use a custom component `<amp-video>`which holds the autoplay tag, instead of `<video>`. I will add a bug in bugzilla about this.

**Comment by kbrosnan** [comment] 2020-04-29 16:09
Duplicate of #8503 which has had more discussion.

**Closed by kbrosnan** 2020-04-29 16:09 UTC
Labels: Feature:Media, S2, 🐞 bug
