### ISSUE TITLE
FNX-5143 ⁃ Fenix crashes at about:config [Bug]

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#1624] opened 2019-04-13 22:38 UTC
## Steps to reproduce
Enter about:config

### Expected behavior
Fenix opens preferences tab

### Actual behavior
Fenix crashes

### Device information
* Android device: Samsung Galaxy Tab A (2016) SM-T580 
* Fenix version: 1.0.1915 (Build #11031226) German localization

**Comment by mauryat** [comment] 2019-04-15 10:10
Doesn't repro on Samsung Galaxy S8.
Fenix version: 1.0.1915 English localization

I don't think German localization matters as such because the app in the current state isn't built for other locales. 

@LittleAngelwings can you post some logs by connecting to Android Studio logcat?

There's no available emulator for the said device. The closest I could find on the Samsung Remote test lab was Tab A 2015 9.7".

**Comment by LittleAngelwings** [comment] 2019-04-15 22:28
[2019-04-16-00-08-33.txt](https://github.com/mozilla-mobile/fenix/files/3082266/2019-04-16-00-08-33.txt)
Hope this helps, it's not from Android Studio.. it's from Matlog

**Comment by kbrosnan** [comment] 2019-04-16 22:51
Dupe of #1034

**Closed** 2020-08-11 12:18 UTC
Labels: b:crash, 🐞 bug
