### ISSUE TITLE
Closed Tab "Undo" pop can't be removed [Bug]

### ISSUE THREAD

**Issue by samuelbido** [mozilla-mobile/fenix#8675] opened 2020-02-23 05:17 UTC
## Steps to reproduce
Had 11 tabs opened, then closed one.

### Expected behavior
When the pop up shows up, it disappears after a while, or user can swipe it away. 

### Actual behavior
Pop up shows up and only goes away when clicking "UNDO". Waited a while, tried to swipe it in all directions, opened new tabs and it stayed there. When I hit UNDO the closed tab wasn't restored.

### Device information

* Android device: LG G5 Android 7.1
* Fenix version: Firefox Preview 3.2.0

**Comment by SS1113** [comment] 2020-02-23 06:51
It's been already fixed in the Firefox Preview Nightly version. You can close this issue.

**Comment by cadeyrn** [comment] 2020-02-23 07:35
Duplicate of #7799.

**Closed** 2020-02-23 13:42 UTC
Labels: needs:triage, 🐞 bug
