### ISSUE TITLE
FNX-14602 ⁃ Trust System Certificates on Android

### ISSUE THREAD

**Issue by androidacy** [mozilla-mobile/fenix#13421] opened 2020-08-08 19:12 UTC
### What is the user problem or growth opportunity you want to see solved?
System certificates are currently not trusted without a way to change that

### How do you know that this problem exists today? Why is this important?

I have an AdGuard certificate in my system store

### Who will benefit from it?

Rooted users, or users with an unlocked bootloader have the opportunity to install certificates into the system store, which Fenix doesn't trust. This may also hold true for OEMs that install certificates that Fenix does not (yet) trust

**Comment by cadeyrn** [comment] 2020-08-08 19:16
Duplicate of #2286 and #3728.

**Comment by unixandria-xda** [comment] 2020-08-08 19:28
> Duplicate of #2286 and #3728.

#3728 deals with _user_ certificates not system ones. Android treats the two different

**Closed** 2021-02-14 11:38 UTC
Labels: Feature:AndroidIntegration, wontfix
