### ISSUE TITLE
⭐️ Feature request: Please add "close other tabs" 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#20128] opened 2021-06-22 18:59 UTC
since the introduction of the new home button wich even exacerbates the wrong behaviour of fenix to always open new tabs whatever the user wishes to , please add close other tabs lo long press the tab switcher (possibly near close tab)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16892)

**Comment by s3xycake** [comment] 2021-06-24 20:18
I know a lot of people love this new behavior but give us a toggle to make the home button behave like the desktop version.

**Comment by ppvnf** [comment] 2022-09-22 14:05
duplicate of #17592 and #19889

**Comment by csadilek** [comment] 2023-01-26 23:07
Closing as duplicate of https://github.com/mozilla-mobile/fenix/issues/19889.

**Closed by csadilek** 2023-01-26 23:07 UTC
Labels: 🐞 bug, feature request 🌟, Feature:Tabs, needs:triage
