### ISSUE TITLE
[Bug] Flashing animation on "Authorize this Sign-In"

### ISSUE THREAD

**Issue by MarjaE2** [mozilla-mobile/fenix#17222] opened 2020-12-25 20:54 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Open Firefox for Android.

### Actual behavior

There is a ton of animation. Users may need to block animation.

Since users need to sign in to sync settings, and to set animation settings, users should not face animation in the setup process.

### Device information

Likebook Mars.

* Android device: 8.1.
* Fenix version: ? no idea.

**Comment by amedyne** [comment] 2021-01-20 16:31
@MarjaE2 Can you provide the Firefox version that you have? Go to:Settings-> About Firefox. Thanks!

**Comment by lobontiumira** [comment] 2021-03-18 09:11
I will close this issue, since I was not able to reproduce this animation on signing in on any of the builds, beta, Nightly or RC; and due to the fact that the reporter hasn't provide more details.

**Closed by lobontiumira** 2021-03-18 09:11 UTC
Labels: needs:triage, 🐞 bug

**Comment by MarjaE2** [comment] 2021-03-18 19:28
I ununistalled Firefox, due to the flashing, and have not reinstalled.

**Comment by MarjaE2** [comment] 2021-06-06 21:53
Okay, reinstalled, checking from Optimization. It is 89.1.1. It is still very, very painful.

**Comment by MarjaE2** [comment] 2021-06-06 23:02
It's this page here. The actual display is black and white and flashes during any screen refresh.

![Screen Shot 2021-06-06 at 7 01 34 PM](https://user-images.githubusercontent.com/12875862/120942892-b9207300-c6f9-11eb-85bc-e36419d6feac.png)

**Comment by MarjaE2** [comment] 2021-06-06 23:03
I mean it flashes during any kind of animation.
