### ISSUE TITLE
A QR Code Scanning Widget

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15228] opened 2020-09-20 06:03 UTC
### What is the user problem or growth opportunity you want to see solved?
As a user a lot of times I need to scan Zoom QR codes to quickly join meetings. others will probably have similar needs for a quick QR scan. Right now we need several clicks to attain this functionality. It would be awesome if we had a widget to launch this functionality directly From the launcher.

### How do you know that this problem exists today? Why is this important?
It is cumbersome for people to launch the scan function if they are doing it several times a day

### Who will benefit from it?
Users who need QR scanning

**Comment by kbrosnan** [comment] 2020-09-24 07:41
Duplicate of #11829

**Closed by kbrosnan** 2020-09-24 07:41 UTC
Labels: Feature:QRCode, feature:SearchWidget, needs:triage
