### ISSUE TITLE
[Bug] mynoise.net no longer plays sound in the background

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14153] opened 2020-08-25 12:00 UTC
From https://www.reddit.com/r/firefox/comments/ig85in/fast_personalized_and_private_by_design_on_all/g2sc13g/

## Steps to reproduce

1. Visit https://mynoise.net/NoiseMachines/windSeaRainNoiseGenerator.php
2. switch to another tab or background Fenix

### Expected behavior

Audio continues to play, like in Fennec.

This used to also work in Fenix: https://github.com/webcompat/web-bugs/issues/35661#issuecomment-546145293

### Actual behavior

Audio is interrupted as soon as step 2 occurs. 

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 200824 06:00 (Build #2015759795)
AC: 56.0.20200821184145, 96a8a14dc
GV: 81.0a1-20200820093209
AS: 61.0.12

**Comment by yoasif** [comment] 2020-08-25 12:47
Very oddly, it just started playing with  the screen off. I had basically left my phone alone for an hour since I submitted this bug.

**Comment by s-ankur** [comment] 2020-11-28 07:06
Duplicate of https://github.com/mozilla-mobile/fenix/issues/15417?

**Comment by rocketsroger** [comment] 2020-12-15 16:08
> Duplicate of #15417?

Yes confirmed that this is a duplicate.  I'll close this issue and track it with https://github.com/mozilla-mobile/fenix/issues/15417.  Thanks

**Closed** 2020-12-15 16:09 UTC
Labels: needs:triage, 🐞 bug
