### ISSUE TITLE
[Bug] White status bar in PB when accessed from home screen on Samsung devices

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#12304] opened 2020-07-06 08:57 UTC
Prerequisites:

* Have PB shortcut added to device home screen
  1. Steps to reproduce

1. Tap on the PB from home screen.
1. Inspect the device status bar.
    1. Expected behavior
The status bar has the same color as the PB screen.
    1. Actual behavior
The status bar is white.
    1. Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 7/6

Note:

* When opening the PB on Samsung from browser the issue is not present, only when opened from device home screen shortcut
* With device Google Pixel 3 XL (Android 9) and Sony Xperia Z5 (Android 7) the status bar looks ok

<details closed>
<summary>Status bar accessed through home screen-Samsung</summary>

![Screenshot](https://user-images.githubusercontent.com/49859863/86575146-79985680-bf7f-11ea-96fc-6416f78745ea.jpg)UNITO-UNDERSCORE!20200706-114451!UNITO-UNDERSCORE!Firefox Nightly!UNITO-UNDERSCORE!2!
</details>

<details closed>
<summary>Status bar accessed through PB icon from browser-Samsung</summary>

![Screenshot](https://user-images.githubusercontent.com/49859863/86575382-d09e2b80-bf7f-11ea-970d-dae4cdc8251f.jpg)UNITO-UNDERSCORE!20200706-115514!UNITO-UNDERSCORE!Firefox Nightly!
</details>

**Comment by LittleAngelwings** [comment] 2020-07-06 20:46
Dupe of this https://github.com/mozilla-mobile/fenix/issues/8812?

**Comment by Diana-Rus** [comment] 2020-07-08 08:44
Hi, it can be related, however this happens for the private browsing shortcut.
@LittleAngelwings  - thank you for relating them

**Comment by LittleAngelwings** [comment] 2020-07-08 20:56
@Diana-Rus not at all 😉

**Comment by Diana-Rus** [comment] 2020-09-08 11:26
This also happens with device:
- OnePlus 3T, Android 10

**Closed** 2021-03-14 13:17 UTC
Labels: Feature:PrivateBrowsing, Feature:Shortcuts, S3, wontfix, 🐞 bug
