### ISSUE TITLE
[Bug] Once you use Form Fill on a website, it is repeated on every search.

### ISSUE THREAD

**Issue by vishalnandagopal** [mozilla-mobile/fenix#11555] opened 2020-06-13 15:11 UTC
## Steps to reproduce
Go to this URL

https://about.gitlab.com/why/use-continuous-integration-to-build-and-test-faster/
This page is very slow on Fenix
Scroll down and select the 'number of employees' form. Don't choose any number and go back.

Then open tab and do normal search, with your default search engine (here DDG). The form appears again and goes away in 2 seconds.

### Expected behavior
The form shouldn't appear when doing every search.

### Device information
* Android device: Android 10
* Fenix version: Latest Play Store Nightly.

**Comment by s-ankur** [comment] 2020-08-02 09:17
Duplicate of #12943

**Comment by ekager** [comment] 2020-08-02 20:08
Closing for #12943

**Closed** 2020-08-28 16:07 UTC
Labels: needs:triage, 🐞 bug
