### ISSUE TITLE
FNX-503 ⁃ [Bug] Fenix doesn't remember what tab was open

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#2152] opened 2019-04-30 00:30 UTC
## Steps to reproduce
* Open tab
* Press home
* Press recent apps button
* Swipe Fenix away
* Reopen Fenix

### Expected behavior
* Fenix reopens on the same tab that was open

### Actual behavior
* List of tabs appear

### Device information
* Android device: Samsung S10e
* Fenix version: Latest from playstore

Works in: Fennec, Chrome

**Comment by agi90** [comment] 2019-04-30 00:30
Similar to #1366

**Comment by vesta0** [comment] 2019-05-10 18:00
@lime124 please confirm that this is expected behaviour. Upon closing and restarting Fenix, the most recent tab is still selected and showing at the top and we should probably keep it this way and user test it at a later point.

**Comment by topotropic** [comment] 2019-05-13 09:22
When you open a tab, go to Fenix start screen, close the app, and re-open it again, you see the Fenix start screen. When you have a tab open, close the app, re-open it again, you should see the tab. 
We'll show what someone saw before closing the app/switching to another app.

**Comment by vesta0** [comment] 2019-05-14 04:40
Thanks @topotropic. Are you confirming that the current behaviour is correct?

**Comment by topotropic** [comment] 2019-05-14 12:22
@vesta0 No, the current behavior is: open a tab, close app, open app, you see the start screen instead of the tab

**Comment by vesta0** [comment] 2019-05-14 16:15
@topotropic when someone closes the app (instead of minimize) would it make sense to assume that they are done with their task and therefore they would expect their open tab to be minimized when they come back to the browser? I remember reading about how users don't like that most browsers try to reload the last visited page every time they open the browser. I can find the article and send you. Let me know what you think :)

**Comment by topotropic** [comment] 2019-05-14 17:12
@vesta0 sure, I don't have a strong opinion here, let's leave as is and track it as hypothesis

**Comment by kbrosnan** [comment] 2019-05-14 17:27
Android does not provide a way to tell the difference between a user swiping an app closed and the app being killed in the background.

**Comment by agi90** [comment] 2019-05-14 21:02
Yes, that's why it's really confusing. If the system is under memory pressure (common on low end devices) Android will kill Fenix in the background and lose the page state.

**Comment by buttercookie42** [comment] 2019-05-14 21:40
@vesta0 Don't we have some telemetry data on how many Fennec users customise the "Restore tabs on startup" option in Fennec as compared to other options from our settings?

@kbrosnan The presence or not of any `savedInstanceState` can be taken as a hint, even if it might not be 100% reliable, and without having looked at the code, I guess that could actually be the reason behind the current behaviour (coupled with the fact the the home/tabs view has been declared the "root" view, so in the absence of any saved instance state that is what gets opened by default?).

**Comment by vesta0** [comment] 2019-05-15 17:52
@buttercookie42 that would have been helpful but we don't track this in Fennec. 

@kbrosnan thanks for the additional detail. What is your recommendation here?

**Comment by buttercookie42** [comment] 2019-05-16 09:34
> @buttercookie42 that would have been helpful but we don't track this in Fennec.

Hmm, what happens to [this data](https://dxr.mozilla.org/mozilla-central/rev/9e68d485f7ccea5d8f065fb5f833858e71b4b04a/mobile/android/base/java/org/mozilla/gecko/preferences/GeckoPreferences.java#1148-1163), then?

**Comment by santiagofn** [comment] 2019-11-03 17:39
I'm not using Fenix on a daily basis mainly bc of this issue.
Can't understand how opening a list of "open tabs" could be more useful than showing the user it last opened page. @vesta0 mentioned an study about users complaining about this behavior but it's how "Restore previous session" works in every browser I used:
![image](https://user-images.githubusercontent.com/8375708/68089446-a8d25300-fe47-11e9-80b0-d6a20011ab75.png)

**Comment by brampitoyo** [comment] 2019-12-17 01:30
@topotropic and I have agreed that the current behaviour is indeed correct.

In fact, we would revise it slightly:

- Open tab
- Press home
- Press recent apps button
- Swipe Fenix away
- Reopen Fenix
- **`about:home` appear**

The tab you previously had opened can be accessed by:

- Press tab tray icon (it will show a number in it)
- Select the tab you want to go to

This supports what we learnt from our user study, quoting our researcher Elisabeth:

> […] a new tab would work because no one had any trouble seeing the tab tray icon or switching to that view in those most recent tests, as long as they had the reassurance of the number in the tab icon

@santiagofn Your preference is still totally correct! Some – not all – test participants preferred last opened tabs to always open after quit.

Quoting Elisabeth:

> […] people who are big fans of keeping specific tabs open like to return to where they left off, but it also didn't seem to be a major barrier if they landed back on the Fennec home screen […]

So we recommend, both:

1. Keep our current behaviour: always open `about:home`
2. At the same time, track this behaviour as a hypothesis. See whether a significant percentage of users, after reopening Firefox, **consistently go to the last opened tab**.

“Always open last tab after quit” may make it as a feature in the future. For now, we recommend working on other things while waiting and seeing the result of this behaviour.

**Comment by lime124** [comment] 2020-02-06 21:02
Let's take a look at the telemetry after migration to see what people are doing on the homescreen to validate/invalidate the hypothesis. 

> At the same time, track this behaviour as a hypothesis. See whether a significant percentage of users, after reopening Firefox, consistently go to the last opened tab.

We can also continue to monitor via milestone tests.

**Comment by liuche** [comment] 2020-04-07 01:23
Is this part of the Tabs Tray work, @topotropic ? If this isn't relevant anymore, maybe we could close it and handle it in a more recent issue.

**Comment by topotropic** [comment] 2020-04-07 16:37
Yes, I'll close it and keep track of the qual + quan research to monitor this

**Closed** 2020-08-11 14:05 UTC
Labels: Feature:AndroidIntegration, Feature:Tabs, P3, eng:ready, needs:UR, 🐞 bug
