### ISSUE TITLE
Mobile specific Amazon search attribution codes

### ISSUE THREAD

**Issue by lwa-moz** [mozilla-mobile/fenix#19162] opened 2021-04-21 14:36 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Fenix currently offers users the ability to search directly on Amazon through suggestions, as well as default search configuration, and "this time search with" one-off URL-bar searches.

These searches are attributed to 'Firefox' but not distinguished from desktop searches. We therefore have no means to understand the value of these searches relative to other platforms.

This request is to update our existing region specific Amazon codes with mobile codes (also region specific). This should resolve our existing inability to properly evaluate mobile value.

The codes are as follows: 

Country | Amazon  Store ID | Amazon Tracking IDs
-- | -- | --
US | mozilla-20 | moz-us-mbl-20
UK | mozilleuropef-21 | moz-uk-mbl-21
Germany | mozillaeurope-21 | moz-de-mbl-21
France | firefomozille-21 | moz-fr-mbl-21
Japan | mozillajapan-22 | moz-jp-mbl-22
Italy | mzdeap-21 | moz-it-mbl-21
Canada | mozillacanada-20 | moz-ca-mbl-20
Australia | mozillaaustra-22 | moz-au-mbl-22
Spain | mozillaspain-21 | moz-es-mbl-21
Netherlands | mozillanether-21 | moz-nl-mbl-21
Sweden | mozillasweede-21 | moz-se-mbl-21

A sample query string would be as follows: http://www.amazon.com/exec/obidos/external-search/?field-keywords=\{searchTerms}&mode=blended&tag=mozilla-20&sourceid=Mozilla-search

**Comment by rocketsroger** [comment] 2021-05-07 17:41
This will require A-C side search plugins changes.

**Comment by rocketsroger** [comment] 2021-05-07 20:55
To clarify the asks here.  In A-C we'll replace the URL tag of each region to the corresponding Amazon Tracking ID (ex: moz-us-mol-20 for US)

**Comment by lwa-moz** [comment] 2021-05-10 15:52
@rocketsroger that's right. The ask is to update the Amazon URL codes/tags on a region specific basis.

**Comment by rocketsroger** [comment] 2021-05-18 15:29
Confirmed with @lwa-moz that for now we'll leave the tracking ID used with India as is.

**Comment by lwa-moz** [comment] 2021-05-19 18:02
Due to issues with the Australia code, we should ship without updating that specific geo.

**Comment by lobontiumira** [comment] 2021-05-26 16:36
Tested on the 5/26 Nightly build with Samsung Galaxy Note 8 (Android 9), and here are my findings:
* US - moz-us-mbl-20
* UK - moz-uk-mbl-21
* Germany - moz-de-mbl-21
* Japan - moz-jp-mbl-22
* Italy - moz-it-mbl-21
* Canada - moz-ca-mbl-20
* Spain - moz-es-mbl-21
* Netherlands - moz-nl-mbl-21
* Sweden - moz-se-mbl-21

The following codes don't match:
* Australia - instead of moz-au-mbl-22, has the moz-us-mbl-20 Amazon tracking ID
* France - doesn't have amazon as a default search engine. I added it manually, both amazon.fr, and amazon.com, and did not match the Amazon tracking ID

@rocketsroger please review and advise.
Thank you!

**Comment by rocketsroger** [comment] 2021-05-26 17:01
> The following codes don't match:
> 
>     * Australia - instead of moz-au-mbl-22, has the moz-us-mbl-20 Amazon tracking ID
> 
>     * France - doesn't have amazon as a default search engine. I added it manually, both amazon.fr, and amazon.com, and did not match the Amazon tracking ID
> 
> 
> @rocketsroger please review and advise.
> Thank you!

I can confirm that both issue is there.  For France, this was a miss, I'll have to add Amazon to it's list.  
For Australia, we don't have a separate search engine list so it uses US settings.  This was expected.  However, that said, I'm integrating Ebay as another search engine and it makes more sense that if we do add Australia specific search engines.  I'll look into this.

Thanks for catching these! I'll update when I resolved these.

**Comment by rocketsroger** [comment] 2021-05-31 15:39
Confirmed the fix is now in Nightly.  Please verify.  Thanks!

**Comment by rocketsroger** [comment] 2021-06-01 19:09
Didn't notice I already got QA verified.  Assuming this was because only France had some issue which is fixed in Nightly now.  I'll close.  Thanks!

**Closed by rocketsroger** 2021-06-01 19:09 UTC
Labels: E2, Feature:SearchProvider, eng:qa:verified

**Comment by lobontiumira** [comment] 2021-06-02 05:45
Confirming on the 6/2 Nightly build with Samsung Galaxy Note 8 (Android 9) that France has the correct ID tracker moz-fr-mbl-21

However, Australia has amazon.com.au as a search engine, but doesn't display the Amazon ID tracker at all. 
I.e. I've searched for "puma" with tha amazon.com.au search engine, and the search link is https://www.amazon.com.au/s?k=puma

**Comment by rocketsroger** [comment] 2021-06-02 06:22
> However, Australia has amazon.com.au as a search engine, but doesn't display the Amazon ID tracker at all.
> I.e. I've searched for "puma" with tha amazon.com.au search engine, and the search link is https://www.amazon.com.au/s?k=puma

Yes, this is expected.  Currently we don't have a correct Amazon ID for Australia.  Once the search team provides me with the updated Amazon ID I will create a new issue to update it.  Thanks!
