### ISSUE TITLE
add feature translate on Firefox nightly thanks

### ISSUE THREAD

**Issue by Mozzaru** [mozilla-mobile/fenix#28433] opened 2023-01-06 03:07 UTC
Please add feature translate on Firefox nightly thanks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22240)

**Comment by cadeyrn** [comment] 2023-01-06 14:41
Duplicate of #6133.

**Closed** 2023-01-09 16:04 UTC
Labels: needs:triage
