### ISSUE TITLE
[Bug] sometimes when you tap on the URL bar and type, it does not behave correctly

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#8236] opened 2020-02-07 22:13 UTC
This issue is especially a problem for when the toolbar is set to be on the bottom. The whole point/purpose of having the toolbar at the bottom is that you can comfortably browse with 1 hand without having to "thumb stretch" to the top of the screen very often. This issue is making me have to thumb stretch to tap the "clear URL" button very often, basically cancelling out the benefits of bottom toolbar.

To repro: go to theverge.com (the issue is not specific to theverge.com, I'm just using it as an example) . Now tap on the URL once. I'm now seeing "https://www.theverge.com/2020/" in the URL bar, even though that's not the URL I'm on! Also, the "2020/" portion is highlighted with purple, whereas the "https://www.theverge.com/" is highlighted with grey (I have both Android and Fenix set to Dark theme, FYI). When I tap a letter on the keyboard, I'm expecting the entire URL to clear and be replaced by the letter I just tapped, but instead just the "2020/" clears and the letter I tapped doesn't even appear, AND "https://www.theverge.com/" is still there... So I'm forced to do a thumb stretch and tap the "clear" button in the URL bar to get rid of "https://www.theverge.com". This is happening really often and it's cancelling out the benefit of having the bar at the bottom. To make this issue even stranger, it doesn't happen consistently! My friend (who is a dev) said it sounds like it could be a race condition of some kind. If there's anything else I can do to help get this fixed I'm more than happy to help. Thank you for Fenix, it is amazing and I really love it.

Device is a Google Pixel 3a XL on Android 10, using Firefox Preview 3.2.0

**Comment by spVierSechs** [comment] 2020-02-09 01:23
URL parth highlighted in purple seem to be suggestions.

**Comment by willfs84** [comment] 2020-02-09 01:59
Yes. Are you able to repro? (btw, I just got it now when I went to "https://www.instagram.com/". It's highlighted in grey, and it's added on "explore/" which is highlighted with purple)

**Comment by Cheap-Skate** [comment] 2020-02-09 09:46
Duplicate of #7934 I think.

**Comment by willfs84** [comment] 2020-02-09 18:09
Yup looks like it. It's becoming very annoying and frustrating, can this please be given a high priority? It's driving me nuts

**Comment by willfs84** [comment] 2020-02-22 18:49
Btw I'm using SwiftKey, as mentioned in 6290. When I use Gboard, there's no issue. (it never occurred to me the keyboard could be part of the problem). This can be closed as duplicate of 6290

**Comment by sflorean** [comment] 2020-06-12 15:35
I wasn't able to reproduce the issue on the latest Nightly with Samsung Galaxy Note 10 (Android 10) or Nokia 6 (Android 7.1.1). Based on the previous comment I will close this and mark as a duplicate of #6290.

**Closed by sflorean** 2020-06-12 15:35 UTC
Labels: eng:qa:needed, needs:ac, needs:triage, 🐞 bug
