### ISSUE TITLE
[Bug] ETP pop-up can appear when toolbar is scrolled off-screen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#15402] opened 2020-09-24 18:33 UTC
## Steps to reproduce
- Clear data
- Click URL bar
- Load a site with trackers (e.g. kotaku.com)
- Scroll down

### Expected behavior
ETP pop-up points to ETP shield in toolbar.

### Actual behavior
Toolbar is offscreen so ETP pop-up points at nothing. We seem to wait for the page to completely load before showing the pop-up so I'd guess this happens to users pretty often who are probably scrolling before the page finishes loading.

![image](https://user-images.githubusercontent.com/759372/94182299-a577f980-fe55-11ea-83bc-2b344b394564.png)

### Device information

* Android device: P2
* Fenix version: Nightly 200924

**Comment by s-ankur** [comment] 2020-09-25 05:35
Duplicate of #14012, probably that can be closed

**Comment by mcomella** [comment] 2020-09-28 23:44
Thanks – I closed the other issue.

**Comment by ebalazs-sv** [comment] 2020-10-15 09:59
Verified as fixed on Nightly 201015 (Build #2015769771) GV 83.0a1 from 10/15 with Pixel 2 (Android 9).
I will remove the qa:needed label and close this issue.

**Closed by ebalazs-sv** 2020-10-15 09:59 UTC
Labels: Feature:Onboarding, Feature:Toolbar, Hacktoberfest, eng:qa:needed, eng:ready, help wanted, 🐞 bug
