### ISSUE TITLE
FNX3-17111 ⁃ [Bug] Auto-completed URL in the top url bar cuts out once page is loading

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#3561] opened 2019-06-19 17:41 UTC
## Steps to reproduce
Start typing a URL that's in the history. It will auto-complete. Press "enter" to load it.

For example, type "news" to autocomplete to "news.ycombinator.com" 

### Expected behavior
Auto-completed URL remains visible in the top url bar until URL bar moves down to the bottom. 

### Actual behavior
Auto-completed URL (e.g. "news.ycombinator.com") disappears, only what user typed in remains ("news").

It's a briefly visible bug, but feels quite janky.

**Comment by codrut-topliceanu** [comment] 2020-05-20 14:04
I'm unable to reproduce this on the latest nightly on :
Pixel 4 (Android 10)
OnePlus 6 (Android 9)
Samsung Galaxy Note 3 (Android 5)

I could use some QA assistance, if that's ok.

**Comment by softvision-miralobontiu** [comment] 2020-05-22 13:25
Verified as fixed on the latest Nightly build from 5/22 with Xiaomi Mi 8 Lite (Android 9), Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab A6 (Android 5.1.1), Google Pixel (Android 10), and OnePlus 5T (Android 9).

**Closed** 2020-08-11 15:00 UTC
Labels: Feature:Toolbar, P3, eng:qa:verified, needs:ac, 🐞 bug
