### ISSUE TITLE
[Bug] Back button misbehaving in New Tab (+)

### ISSUE THREAD

**Issue by nitin10s** [mozilla-mobile/fenix#9787] opened 2020-04-07 21:19 UTC
## Steps to reproduce
1. Click on the + icon in toolbar
2. Observe how the keyboard opens by default.
3. Press Back button of your device

### Expected behavior
The Back button should ideally just close the keyboard.

### Actual behavior
The Back button brings user back to the Home Screen instead.

**Comment by kbrosnan** [comment] 2020-04-07 23:24
This is intentional. Request is a dupe of #8556

**Closed by kbrosnan** 2020-04-07 23:24 UTC
Labels: needs:triage, 🐞 bug
