### ISSUE TITLE
Migrate Quick Settings to LibState

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#4126] opened 2019-07-17 17:58 UTC
## User Story
As a developer I'd like Quick Settings to implement LibState.

See Search component #3985 for guidelines, or reach out to Christian, Sebastian, Jeff.

## Dependencies
None

### Acceptance Criteria
* Quick Settings implements LibState
* Quick Settings has tests

**Comment by sblatz** [comment] 2019-07-29 17:02
I'm moving this into the sprint in place of #4125 since that did not need a migration.

**Comment by Mugurell** [comment] 2019-07-31 08:28
I'd like to work on this. Curious about the new architecture.

**Comment by liuche** [comment] 2019-08-16 17:45
This is waiting on ETP #1749 to land, so delayed till Sept?

**Comment by Mugurell** [comment] 2019-08-19 07:23
> This is waiting on ETP #1749 to land, so delayed till Sept?

This is just for refactoring the existing code, does not depend on other work.

**Comment by sblatz** [comment] 2019-08-19 16:14
@Mugurell there will be lots of merge conflicts if we move ahead with this ticket, so we should probably hold off. We already have the ETP built and don't want to have to have a huge rebase. Sorry for the confusion.

**Comment by Mugurell** [comment] 2019-08-20 06:43
It's ok. I'll just hold off on my branch and continue after the ETP is merged. Thanks!

**Comment by sblatz** [comment] 2019-09-27 16:09
@Mugurell this is no longer waiting 😄

**Comment by Mugurell** [comment] 2019-09-30 07:19
Thanks @sblatz !
Will get to it!

**Comment by ekager** [comment] 2019-11-01 00:10
QA should verify that the Quick Settings (lock icon dialog) actions still work as intended after this refactor

**Comment by abodea** [comment] 2019-11-06 13:50
Hi @ekager I've checked the following and haven't encountered any issues:
Build: **` Nightly 191106 06:21 (Build #13100629)📦:20.0.0, 1bae81951🦎: 72.0a1-20191103094618 from 11/6 `**
Device: **`Google Pixel 3a XL(Android 10):`**
- Go to permission.site. Allow and deny some permissions as: camera, mic, location, notification.
- Go to Settings>Site Permissions>Exceptions. Tap the website in the list. 
- Verify each permission has an icon.
- Verify each permission shows its state: allowed/not allowed.
- Tap OK. Verify the Clear permissions button clears the permissions given only to this website.

Here can be found the [full tests. ](https://testrail.stage.mozaws.net/index.php?/cases/view/247007)
Based on my comment I will **close** and mark this issue as **verified**.

**Closed by abodea** 2019-11-06 13:50 UTC
Labels: Feature:QuickSettings, P2, eng:health, eng:qa:needed
