### ISSUE TITLE
FNX-13060 ⁃ [Bug] Firefox (Fenix) doesn't respect user's desired language for web content

### ISSUE THREAD

**Issue by crisalis2** [mozilla-mobile/fenix#12043] opened 2020-06-27 00:13 UTC
I keep changing int.accept_languages to "en-US, en" and int.locale.requested to "en-US", but Firefox is so intent on changing them back after a while to match Android settings. I use a particular set of locales in Android but I don't want that in Firefox. I want websites I visit to display in English whenever possible, and my headers to just include the usual en-US,en;q=0.5. Firefox should not change the values to what it wants, but respect my choice. Websites don't display in the language I want and my HTTP_ACCEPT Headers are weird because of this.

## Steps to reproduce
Go to about:config and change int.accept_languages and int.locale.requested to a custom value, different from your Android's configured locale(s).

### Expected behavior
The values you have set for  int.accept_languages and int.locale.requested persist and thus websites you visit appear in your desired language.

### Actual behavior
After a while (it is not immediate, don't know what exactly triggers it, but try quitting from Firefox and wait like 20 minutes), Firefox changes int.accept_languages and int.locale.requested, not respecting your configuration and then making websites not display in the desired language.

### Device information
* Fenix version: 77.0.0-beta.2

**Comment by cadeyrn** [comment] 2020-06-27 07:34
Duplicate of #6502.

**Comment by kbrosnan** [comment] 2020-06-27 21:45
Closing as a duplicate

**Comment by crisalis2** [comment] 2020-07-03 13:31
Well, the other issue says to add the ability to change web content language, but the thing is, as I state here, Firefox already has that ability through the mentioned about:config entries. The problem is that after a while Firefox resets the values. The solution is for Firefox not to actively do that, and just let the new about:config values be.

**Closed** 2020-08-11 05:39 UTC
Labels: needs:triage, 🐞 bug
