### ISSUE TITLE
Notifications block touch on the buttons below them.

### ISSUE THREAD

**Issue by jtagcat** [mozilla-mobile/fenix#11199] opened 2020-06-03 20:10 UTC
## Steps to reproduce
Cause any notification.

### Expected behavior
The buttons below the notifications work.

### Actual behavior
![image](https://user-images.githubusercontent.com/38327267/83683905-aac6e500-a5d5-11ea-9944-b0003f15f2d2.png)
The whole yellow section ignores all touch. The visible buttons should be clickable. Additionally, if the page is not scrollable, you can't press the buttons below the notification.

I would start by reducing the notification's touch area to not include the navigation bar, then add the ability to dismiss notifications on touching them.

* Fenix version: 76.0b8

**Comment by kbrosnan** [comment] 2020-06-23 21:35
This should be fixed on a current nightly. A bug was fixed where items under the Location Bar were not clickable.

**Comment by ekager** [comment] 2020-06-23 21:47
I think this issue is about the toolbar not being touchable while the Tab Sent snackbar is displaying (and not being able to swipe away the snackbar)

**Comment by jonalmeida** [comment] 2020-12-16 05:59
Duplicate of #15242

**Closed by jonalmeida** 2020-12-16 05:59 UTC
Labels: Feature:Snackbar, 🐞 bug

**Comment by jtagcat** [comment] 2020-12-18 16:52
> Duplicate of #15242

jfyi it's better to mark newer issues as duplicates of the oldest one, not the other way around. Helps to keep related activity in one place.
