### ISSUE TITLE
Feature request: Add different layout(s) for tab tray

### ISSUE THREAD

**Issue by KryptonicDragon** [mozilla-mobile/fenix#14457] opened 2020-08-29 19:21 UTC
New update is cool, but I'd like to have the tab tray show a grid layout (two columns) as it did before. Navigating through all my tabs in a single-column list (especially when the tab tray doesn't even take up the whole screen anymore!!!) is too cumbersome for me.

I may be imagining this, but I remember the previous version allowing you to change between the one- and two-column layouts for the tab tray. Having this feature back would be great.

**Comment by cadeyrn** [comment] 2020-08-29 19:24
Duplicate of #13098.

**Comment by kbrosnan** [comment] 2020-08-29 20:15
Closing as a duplicate

**Closed by kbrosnan** 2020-08-29 20:15 UTC
Labels: needs:triage
