### ISSUE TITLE
[Bug] Lag in renaming a collection 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#13836] opened 2020-08-14 13:44 UTC
## Steps to reproduce
1. Create a collection.
2. Rename the collection.
3. Collapse the collection.
### Expected behavior
The renaming is made immediately.
### Actual behavior
The new name is updated after collapsing the collection or switching the tab tray on/off.
### Device information

* Android device: Pixel 4 (Android 10)
* Fenix version: 81.0.0-beta1, Nightly 8/14

**Comment by liuche** [comment] 2020-08-20 01:49
May be related to #13826 too, but seems like something about collections is lagging.

**Comment by Diana-Rus** [comment] 2020-09-02 11:45
Reproducible on Firefox Preview beta 81.1.0 - beta.1 with Google Pixel 3XL (Android 9)

**Comment by mcarare** [comment] 2020-09-14 13:37
This seems to be fixed in latest Nightly, but I can reproduce it in 81.0.0-beta2. Can QA please retest? Thank you!

**Comment by sflorean** [comment] 2020-09-16 13:26
@mcarare here are the testing results:
- Nightly 9/16 - not reproducible
- Beta 81.1.1-beta.4 from GP - reproducible

**Comment by mcarare** [comment] 2020-09-16 14:44
@liuche, given the above comment, I think this can be closed, but we still have to ensure it also works in a future Beta, by including the commit that inherently fixed the bug: https://github.com/mozilla-mobile/fenix/pull/14704/commits/c22a13cd306a03edfab19c8c712b656d6403d8ce.

**Comment by AndiAJ** [comment] 2020-09-23 12:31
Reproducible on 82.0.0-beta.1

**Closed** 2020-09-23 12:30 UTC
Labels: Feature:Collections, S2, 🐞 bug

**Comment by kleintom** [comment] 2020-09-24 01:28
I'm seeing this on today's nightly:
![nightly_rename_collection](https://user-images.githubusercontent.com/632915/94090241-c2bbb200-fdda-11ea-9b0a-9329ea416ac3.gif)
