### ISSUE TITLE
Crash: NullPointerException lookupMegazordLibrary

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#20975] opened 2021-08-23 15:51 UTC
Sentry nightly https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/12570604
this start happening on the new A-S version `82.1.0`.
```
java.lang.NullPointerException: null
    at mozilla.appservices.support.native.HelpersKt.lookupMegazordLibrary(Helpers.kt:7)
    at mozilla.appservices.support.native.HelpersKt.findMegazordLibraryName(Helpers.kt:3)
    at mozilla.appservices.places.LibPlacesFFI$Companion.<clinit>(LibPlacesFFI.kt:1)
    at mozilla.appservices.places.LibPlacesFFI.<clinit>
    at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:5)
    at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:7)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
    at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(PlacesStorage.kt:1)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage.deleteHistoryMetadataOlderThan$suspendImpl(PlacesHistoryStorage.kt:4)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage.deleteHistoryMetadataOlderThan
    at org.mozilla.fenix.historymetadata.DefaultHistoryMetadataService$cleanup$1.invokeSuspend(HistoryMetadataService.kt:6)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

java.lang.ExceptionInInitializerError: null
    at mozilla.appservices.places.LibPlacesFFI.<clinit>
    at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:5)
    at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:7)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
    at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(PlacesStorage.kt:1)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage.deleteHistoryMetadataOlderThan$suspendImpl(PlacesHistoryStorage.kt:4)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage.deleteHistoryMetadataOlderThan
    at org.mozilla.fenix.historymetadata.DefaultHistoryMetadataService$cleanup$1.invokeSuspend(HistoryMetadataService.kt:6)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

**Comment by Amejia481** [comment] 2021-08-23 15:52
Sentry issue: [FIREFOX-NIGHTLY-CDC](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/12570604/?referrer=github_plugin)

**Comment by grigoryk** [comment] 2021-08-23 18:04
This is the first bit of fall-out from https://github.com/mozilla-mobile/fenix/pull/20931. Unclear why we're failing to find the library here... Since there's nothing _special_ about that particular API call (perhaps, just when it gets hit..?) I expect we should have other similar crashes w/ different entry points.

**Comment by grigoryk** [comment] 2021-08-23 20:30
I think I see what the problem is. We're basically racing against the Megazord.init() call.

That's happening because an instance of `HistoryMetadataMiddleware` is now added to the middleware list used while initializing `core.store: BrowserStore`. This kicks off initialization of `DefaultHistoryMetadataService`, which kicks off a `cleanup` which triggers `storage.deleteHistoryMetadataOlderThan`. This causes a places initialization.

Note that this chain of events won't get triggered until something needs to access `core.store` (since that's wrapped in a `lazy`). Also, none of that is not really crash worthy as long as megazord is initialized prior to any interactions with the places storage.

This is where things get problematic. We run `Megazord.init` in FenixApplication's `onCreate`. But right before that, we initialize Glean, which touches `components.core.store`, which will kick-off places initialization on an IO thread. And this is how we get to have a race (I think!): if megazord initialization wins, all is good. If places initialization "wins", we crash since we can't init places before the Megazord.init call.

**Comment by csadilek** [comment] 2021-08-23 22:40
Closed by https://github.com/mozilla-mobile/fenix/commit/6161dc6e8d4859ee52cde78e4683553f43013a10.

**Closed** 2021-08-23 22:43 UTC
Labels: b:crash, needs:triage
