### ISSUE TITLE
[Bug] Mozilla Nighty Android app - Add to desktop feature

### ISSUE THREAD

**Issue by Elendilej** [mozilla-mobile/fenix#23117] opened 2022-01-08 06:59 UTC
Good day. I have Mozilla Nightly Android app v97.0a1. I can't use the "Add to Desktop" feature. This feature does not work at all. When I click on it, nothing happens. Is it possible to repair it? Thanks

**Comment by cadeyrn** [comment] 2022-01-08 10:41
Hi,

there is a template for creating bug reports:

https://github.com/mozilla-mobile/fenix/issues/new?assignees=&labels=%F0%9F%90%9E+bug%2Cneeds%3Atriage&template=---bug-report.yml&title=%5BBug%5D%3A+

As you can see the developers ask for several information for reporting bugs so that they can reproduce it. I suggest to have a look at the questions (like device and Android version) and update your issue with these information.

**Comment by LaurentiuApahideanSV** [comment] 2022-02-25 17:53
Since the reported hasn't provided further information in along time and we are unable to reproduce the issue I will close this issue.

**Closed by LaurentiuApahideanSV** 2022-02-25 17:53 UTC
Labels: needs:triage
