### ISSUE TITLE
Please add the function of accessing the local HTM of the mobile phone in the Android version

### ISSUE THREAD

**Issue by bowknot** [mozilla-mobile/fenix#24831] opened 2022-04-17 08:14 UTC
It's strange that this feature is available in the Android version of Firefox 68, but not in the latest Android version.

**Comment by cadeyrn** [comment] 2022-04-17 12:10
It's not "strange" at all since Firefox for Android was developed from scratch and it's not based on the old Firefox 68.

Duplicate of #7546. Please follow that issue if you're interested in this feature request.

**Closed** 2022-04-18 03:37 UTC
Labels: needs:triage
