### ISSUE TITLE
FNX-4750 ⁃ [Bug] Unable to Save Downloaded Files

### ISSUE THREAD

**Issue by kglazko** [mozilla-mobile/fenix#10431] opened 2020-05-06 00:23 UTC
## Steps to reproduce
See: https://appbot.co/apps/2101759-firefox-preview/reviews/1602732443
"unable to save files anymore. it has permissions and appears to save the files. but they are never available once downloaded."

### Device information
* Android device: ?
* Fenix version: ?

**Comment by kglazko** [comment] 2020-05-06 00:23
Cannot reproduce using a Pixel 4, QA- please let me know if you're able to reproduce this at all.

**Comment by kbrosnan** [comment] 2020-05-06 00:33
The review you are linking to mentions Gallery and Photos apps.

> Downloaded images are not showing up in the gallery nor in the Google photos app but can be viewed in the file manager

Makes this a dupe of #8754

**Comment by kglazko** [comment] 2020-05-06 00:35
Sorry, I linked the wrong Issue URL.

**Comment by kglazko** [comment] 2020-05-06 00:35
Updated with the correct one: https://appbot.co/apps/2101759-firefox-preview/reviews/1602732443

**Comment by kbrosnan** [comment] 2020-05-06 00:42
Then https://github.com/mozilla-mobile/fenix/issues/10429#issuecomment-624378379 applies. No specific URL, more testing in this area without the blob issue fixed is not a good use of time.

**Closed** 2020-08-11 00:43 UTC
Labels: Feature:Download, needs:triage, 🐞 bug
