### ISSUE TITLE
FNX-5145 ⁃ Text scaling and transparency issues on Firefox Fenix custom tabs.

### ISSUE THREAD

**Issue by thanuj10** [mozilla-mobile/fenix#1628] opened 2019-04-14 09:11 UTC
## Steps to reproduce
1. Open a custom tab
1. Open a custom tab from gmail
1. View the issues

### Expected behavior
1. Transparency and text scaling issues fixed.

### Actual behavior
1. Text scaling is weird and doesn't fit in the address bar.
https://ibb.co/cw4QQWM
https://ibb.co/SRJm1Hr
1. Weird transparency in custom tabs from Gmail.
https://ibb.co/2MykjmY

### Device information
* Android device: Nokia 6.1+/Android 9.0
* Fenix version: Fenix 1.0.1915 (4/13) Build.

Edit - Can now reproduce in normal browser intents also.

https://ibb.co/T8Hq744

**Comment by Scripterr** [comment] 2019-04-15 08:57
I'm also able reproduce it and i'm unable to hide the address bar by scrolling downwards.

**Comment by cadeyrn** [comment] 2019-04-15 09:03
(2) is a duplicate of #1621.

**Comment by vesta0** [comment] 2019-04-16 21:35
Thanks for filing this issue. We will address this in the duplicate issue.

**Closed** 2020-08-11 12:19 UTC
