### ISSUE TITLE
Task Status link for TaskCluster builds in Fenix README is invalid

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#12920] opened 2020-07-24 21:41 UTC
It links to https://github.taskcluster.net/v1/repository/mozilla-mobile/fenix/master/latest

I'm guessing the API has been updated since then. @JohanLorenzo any ideas?

**Comment by liuche** [comment] 2020-07-24 22:51
dupe of #10256 ? I should have put up a PR for that last time I looked at it

**Closed** 2020-08-28 22:57 UTC
Labels: needs:triage
