### ISSUE TITLE
Private and Non-private sessions mixed on Private Home Screen

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#615] opened 2019-02-21 04:25 UTC
## Steps to reproduce
1) enable private mode
2) delete any sessions
3) restart fenix (you should start in private mode)
4) open a web page in private mode
5) 3 dot menu to open a new tab (not a private tab)
6) go to a web page
7) go back home
8) re-enable private mode
9) you will see an odd screenshot like this
![screenshot_20190220-201118_fenix](https://user-images.githubusercontent.com/4879954/53143591-7bf63e00-354d-11e9-9f34-64267507f8e8.jpg)

### Expected behavior
the non-private tab should be on the non-private home screen

### Device information

* Android device: Galaxy S8
* Fenix version: 1.0.1908

**Comment by ekager** [comment] 2019-03-01 17:41
I can't reproduce this anymore, so closing :)

**Closed by ekager** 2019-03-01 17:41 UTC
Labels: 🐞 bug, 🕵️‍♀️ needs investigation

**Comment by bsurd** [comment] 2019-03-06 10:04
The issue is still not reproducible, marking as verified as well.

Verified on:
 - 1.0.1910 (Build #10642115)

 Devices:
 - Nokia 6 (Android 7.1.1)
 - HTC Desire 820 (Android 6.0.1)
