### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by arsdm** [mozilla-mobile/fenix#26071] opened 2022-07-18 13:48 UTC
![Screenshot_2022-07-18-19-24-16-243_org mozilla firefox](https://user-images.githubusercontent.com/109530785/179528138-f0a738b9-74b8-4ef1-addf-2a4442f662b9.jpg)
Hi,

I am unable to click on WhatsApp group links and join then through firefox browser on Android. 

I am able to join through all other browsers like Chrome, Samsung internet etc but not through firefox. 

Please fix this as fast as possible

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21041)

**Comment by arsdm** [comment] 2022-07-18 13:57
![Screenshot_2022-07-18-19-24-16-243_org mozilla firefox](https://user-images.githubusercontent.com/109530785/179527611-fbaee065-c350-48dc-a83c-d6222a3eb09f.jpg)

**Comment by arsdm** [comment] 2022-07-18 14:01
I have attached the screenshot of error message.

Regards

**Comment by plwt** [comment] 2022-07-20 11:56
User feedback: https://support.mozilla.org/en-US/questions/1383287

**Comment by amocirean** [comment] 2022-08-02 12:16
Hello @arsdm, thank you for submitting the issue.
I was not able to reproduce it on Nightly 105.0a1.
Could you tell us if the issue is still occuring on the latest RC or Nightly on your device?

Device Used: Huawei P40 Lite
Android Version: 10

**Comment by boek** [comment] 2023-01-30 21:23
Going to close this as we are no longer able to reproduce. Feel free to re-file if you can still reproduce this issue :)

**Closed by boek** 2023-01-30 21:23 UTC
Labels: needs:triage
