### ISSUE TITLE
Address bar shows search suggestions after switching search engines, even when "Show search suggestions" setting is false

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#27149] opened 2022-09-23 23:26 UTC
# Steps to reproduce:

1. In Settings > Search, set the "Show search suggestions" setting to false.
2. Return to the Firefox homepage.
3. Start to type some search terms in the address bar.
4. As expected, Firefox does not show any search suggestions.
5. Tap the address bar's "🔍Search engine" button and select a different search engine.

# Expected behavior

Firefox should not show search suggestions

# Actual behavior

Firefox shows search suggestions.

This bug was originally filed in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1790182

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21658)

**Comment by cpeterso** [comment] 2022-09-23 23:27
![image](https://user-images.githubusercontent.com/629193/192069058-5ab1abfb-9806-40a7-a310-32394451151a.png)

**Comment by fice-t** [comment] 2022-09-25 20:14
The following fixes this, but I'm not sure if this is intended behaviour:

```diff
diff --git a/app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt b/app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
index 1fa8d5f67..7c9e880a1 100644
--- a/app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
+++ b/app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
@@ -236,7 +236,6 @@ private fun searchStateReducer(state: SearchFragmentState, action: SearchFragmen
         is SearchFragmentAction.SearchShortcutEngineSelected ->
             state.copy(
                 searchEngineSource = SearchEngineSource.Shortcut(action.engine),
-                showSearchSuggestions = true,
                 showSearchShortcuts = when (action.settings.showUnifiedSearchFeature) {
                     true -> false
                     false -> action.settings.shouldShowSearchShortcuts
```

There's also the (intended or not?) behaviour where if you select your default search engine then it also re-enables search suggestions. That would be fixed by removing the `showSearchSuggestions` line just above in the `SearchDefaultEngineSelected` clause.

**Comment by cpeterso** [comment] 2022-09-26 04:49
@rocketsroger - Is setting `showSearchSuggestions = true` intentional?

It was added in commit https://github.com/mozilla-mobile/fenix/commit/7f29461c753c9ed93caa7281a1fe56609ed15277 for https://github.com/mozilla-mobile/fenix/issues/24299.

**Comment by boek** [comment] 2023-01-30 23:21
Dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1807594

**Closed by boek** 2023-01-30 23:21 UTC
Labels: needs:triage
