### ISSUE TITLE
[Bug] Tapping on a site notification doesn't open the website

### ISSUE THREAD

**Issue by astarq** [mozilla-mobile/fenix#11138] opened 2020-06-02 13:07 UTC
## Steps to reproduce
Allow notifications from a website: Instagram, Reddit, twitter > when you receive a notification, open it

### Expected behavior
Fenix opens the page 

### Actual behavior
If firefox is not in the recent apps, Firefox will open to the homepage. If it is, nothing will happen.

### Device information
* Android device: 9
* Fenix version: Nightly 200602 06:01 (Build #2015743859)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1528)

**Comment by SinTan1729** [comment] 2020-06-03 15:16
Can confirm that this happens on Android 10 too.

**Comment by jonalmeida** [comment] 2020-06-08 15:58
Related (or can be closed as a duplicate of): https://github.com/mozilla-mobile/fenix/issues/11007

**Comment by kglazko** [comment] 2020-06-08 18:15
Closed as duplicate of #11007

**Comment by jonalmeida** [comment] 2020-06-23 22:01
Re-opening for product input on what we should do here.

**Comment by TitanNano** [comment] 2020-06-23 22:31
@jonalmeida shouldn't this fire the `notificationclick` event on the sites serviceworker?

**Comment by jonalmeida** [comment] 2020-06-23 22:37
Yes, it should! Let me keep this as a bug then and figure out the empty case separately. Thanks for catching!

**Comment by jonalmeida** [comment] 2020-06-23 23:05
A-C bug where this will be investigated: https://github.com/mozilla-mobile/android-components/issues/7477

**Comment by sheikh-azharuddin** [comment] 2021-07-16 04:59
Hello team
This bug was opened more than a year ago but sadly issue is not fixed...mozilla should focus on the basic features or functions or performance rather than just design elements...🙏😐

**Comment by tzarebczan** [comment] 2022-02-28 22:19
Running into this as well, would be great to have fixed!

**Comment by eakraml** [comment] 2022-04-27 04:23
Same here and as it can be seen it is since 2020 in the backlog of https://github.com/orgs/mozilla-mobile/projects/42#card-40627349

**Comment by danbates2** [comment] 2022-05-30 11:29
Still an issue! Android 8.0 here.

**Comment by csadilek** [comment] 2023-01-09 20:18
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809277

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2023-01-09 20:18 UTC
Labels: 🐞 bug, needs:ac, Feature:Notifications, pin
