### ISSUE TITLE
[Bug] Search input appears deeper in browsing session

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2445] opened 2019-05-13 04:36 UTC
## Steps to reproduce
1. Type in "slickdeals" into location bar
1. Tap search suggestion (not URL)
1. Tap result on SERP for slickdeals.net
1. tap any deal on front page
1. tap location bar

### Expected behavior
I see something like https://slickdeals.net/f/13076452-john-wick-double-feature-4k-uhd-10?src=frontpage in the location bar.

### Actual behavior
I see "slickdeals" in the location bar.

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by bifleming** [comment] 2019-05-29 18:38
@yoasif can you still reproduce this?

**Comment by bifleming** [comment] 2019-06-07 20:03
@vesta0 If we can't reproduce, I suggest closing...

**Comment by yoasif** [comment] 2019-06-07 20:36
I can't still reproduce. Closing.

**Closed** 2020-08-26 05:28 UTC
Labels: 🐞 bug
