### ISSUE TITLE
[Bug] Crash mozilla::PresShell::EventHandler::HandleEventUsingCoordinates

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#14981] opened 2020-09-11 13:34 UTC
why hasn't this bug solved yet it makes nighlty completely unusable on my phone come on it 's been a week since I first reported it 
soccorro 
https://crash-stats.mozilla.org/report/index/74facd36-c93a-469a-8c73-2b8500200911

**Comment by hwinnemoe** [comment] 2020-09-11 13:49
Duplicate of #14624. The fix for this should be in tomorrows Nightly (200912) if I'm reading the timestamps correctly for GV and AC versions.

**Comment by kbrosnan** [comment] 2020-09-11 15:02
Closing as a duplicate

**Closed by kbrosnan** 2020-09-11 15:02 UTC
Labels: needs:triage, 🐞 bug
