### ISSUE TITLE
[Bug] Search shortcuts shouldn't be displayed when URL bar is tapped from browser

### ISSUE THREAD

**Issue by jyeontaek** [mozilla-mobile/fenix#4736] opened 2019-08-14 18:48 UTC

**Comment by cadeyrn** [comment] 2019-08-17 12:31
It's a duplicate of #4566 but since the commit references this issue I will close my issue…

**Comment by softvision-miralobontiu** [comment] 2019-08-19 11:57
Verified as fixed on the latest Nightly 190819 (#12310612) and RC 1.3.0-rc.3 with Huawei P9 Lite (Android 6), and Xiaomi Mi 8 Lite (Android 9).

**Closed by softvision-miralobontiu** 2019-08-19 11:57 UTC
Labels: P1, eng:qa:needed, feature:SearchWidget, 🐞 bug

**Comment by PopeRigby** [comment] 2019-08-21 00:30
This still isn't fixed for me
