### ISSUE TITLE
FNX-13446 ⁃ [Bug] Browser crashes when custom tab is made to open in Firefox nightly.

### ISSUE THREAD

**Issue by paritosh9199** [mozilla-mobile/fenix#12389] opened 2020-07-08 13:25 UTC
When I click on links in the third party app it opens up in custom tabs(which works as intended) but when I click on "Open in Firefox nightly" the browser crashes and a notification is displayed saying "Submitting crash report to mozilla".

I am on Firefox Nightly 200708 06:05 (Build #21900620)
AC: 50.0.20200707200739, e24828693
GV: 80.0a1-20200707094747
AS: 61.0.7

**Comment by ekager** [comment] 2020-07-08 13:28
Closing as dupe of https://github.com/mozilla-mobile/fenix/issues/12311

**Closed** 2020-08-11 06:25 UTC
Labels: needs:triage
