### ISSUE TITLE
[Bug] Reopening a just-closed tab restores it to the wrong position

### ISSUE THREAD

**Issue by GottemHams** [mozilla-mobile/fenix#17735] opened 2021-02-01 17:07 UTC
## Steps to reproduce
1. Simply open about 3 tabs with different websites (to clearly demonstrate the problem), e.g. github.com, mozilla.org and google.com
2. Go to the "tab drawer" (I think it's called that) to view all currently opened tabs
3. Tap the small X button/sign in the top-right corner of the **mozilla.org** tab
4. At the bottom (maybe the top on some devices) a purple bar should appear saying you closed a tab, with an `Undo` button at the end
5. Hit that button

### Expected behavior
The tab should've been reopened in its original position (second), exactly how Firefox for desktop works.

### Actual behavior
The tab is always placed at the very front of the tab drawer, making the new order: mozilla.org, github.com and google.com.

### Device information
* Device vendor / model and Android version: Nokia 6.1, Android 8.1.
* Firefox for Android version: 85.1.1 build #2015789955

**Comment by Dunexus** [comment] 2021-02-02 09:19
Duplicate of https://github.com/mozilla-mobile/fenix/issues/10986

**Comment by mcarare** [comment] 2021-02-03 08:55
Closing as duplicate of https://github.com/mozilla-mobile/fenix/issues/10986.

**Closed by mcarare** 2021-02-03 08:55 UTC
Labels: needs:triage, 🐞 bug
