### ISSUE TITLE
Add Drag and Drop to Rearrange Tabs

### ISSUE THREAD

**Issue by itsmecom** [mozilla-mobile/fenix#27721] opened 2022-11-05 07:56 UTC
Currently there is no option to rearrange tabs position.
adding drag and drop to rearrange tabs could be useful for many users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21936)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21936

**Comment by cadeyrn** [comment] 2022-11-05 08:26
It's already implemented in Firefox Nightly and will be included in the stable release of Firefox 108.

Duplicate of #10344.

**Closed** 2022-11-05 15:58 UTC
Labels: needs:triage
