### ISSUE TITLE
[Bug] Tab closed popup won't disappear

### ISSUE THREAD

**Issue by MishterKirby** [mozilla-mobile/fenix#8051] opened 2020-02-03 15:42 UTC
## Steps to reproduce
Close a tab
### Expected behavior
Tab closed popup should appear, then disappear after a while
### Actual behavior
Tab popup appears, and stays there until "Undo" is pressed.
### Device information

* Android device: LG Stylo 2 (LS775)
* Fenix version: 3.2.0

**Comment by cadeyrn** [comment] 2020-02-03 15:55
Duplicate of #7799.

**Closed** 2020-02-03 19:07 UTC
Labels: needs:triage, 🐞 bug
