### ISSUE TITLE
Crash when loading https://github.com/Kimundi/owning-ref-rs

### ISSUE THREAD

**Issue by jrmuizel** [mozilla-mobile/fenix#7364] opened 2019-12-25 21:44 UTC
## Steps to reproduce

Load https://github.com/Kimundi/owning-ref-rs

### Actual behavior

Fenix crashes instead of loading the page

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 191225

**Comment by hakkikaancaliskan** [comment] 2019-12-25 21:56
Duplicate of #7362

**Closed** 2019-12-27 18:52 UTC
Labels: 🐞 bug
