### ISSUE TITLE
[Bug] Notification click doesn't open target URL

### ISSUE THREAD

**Issue by collimarco** [mozilla-mobile/fenix#15878] opened 2020-10-13 18:35 UTC
## Steps to reproduce

1. Visit this page and send a notification: https://pushpad.xyz/demo
2. The notification is displayed
3. You click the notification: it disappears, but the destination URL is not opened

Related (probably a regression): https://bugzilla.mozilla.org/show_bug.cgi?id=1508279

Everything works fine on FF desktop and on all versions of Chrome.

### Expected behavior

The notification should open the target url.

### Actual behavior

The notification doesn't do anything when clicked (it just disappears).

### Device information

* Android device: Android 10 (Samsung Galaxy S10+)
* Fenix version: Firefox 81.1.4

**Comment by liuche** [comment] 2020-10-14 23:12
What happens with push notifications that include urls @jonalmeida ? I don't have other sites for testing, but this seems like it should work.

**Comment by jonalmeida** [comment] 2020-10-14 23:59
Correct, this should work but we didn't implement it.

Duplicate of: https://github.com/mozilla-mobile/fenix/issues/11138

AC tracking issue: https://github.com/mozilla-mobile/android-components/issues/7477

**Closed by jonalmeida** 2020-10-14 23:59 UTC
Labels: Feature:Notifications, 🐞 bug
