### ISSUE TITLE
[Bug] The tabs are restored as about:blank

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#6212] opened 2019-10-23 13:08 UTC
## Steps to reproduce
1. Open multiple tabs in Fenix.
2. Go to about:crashparent to trigger a crash.
3. Tap "Close"/"Restart Firefox Nightly"
4. Re-open the app, verify the tabs are restored.
### Expected behavior
The tabs previously opened are restored.
### Actual behavior
The tabs previously opened are restored as about:blank.
### Notes
Not reproducible on Firefox Preview 2.2.0 GV 70, 10/17

### Device information

* Android device: OnePlus 5T (Android 9)
* Fenix version: Nightly 191023 GV 71

**Comment by AndiAJ** [comment] 2019-10-23 13:12
@sv-ohorvath  Dupe of #5478 ?

**Closed** 2019-10-23 13:34 UTC
Labels: 🐞 bug
