### ISSUE TITLE
FNX3-16387 ⁃ [Bug] rotating the display from landscape to portrait preserves viewport width

### ISSUE THREAD

**Issue by eeejay** [mozilla-mobile/fenix#2527] opened 2019-05-15 18:23 UTC
## Steps to reproduce
1. Load `haaretz.com` in portrait mode
1. Rotate screen to landsape
1. Rotate back to portrait

### Expected behavior
Content should fit width of screen

### Actual behavior
Content remains "zoomed in"

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1920

**Comment by bifleming** [comment] 2019-05-30 21:09
@vesta0 priority?

**Comment by AndiAJ** [comment] 2019-07-15 12:14
Hi @eeejay , is this a continuous zoom in? I'm asking because I think I may have bumped into the same issue while visiting **`Udemy.com`** on the latest Nightly Build #11960610 from 15/7 using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy S8+(Android 8)
• Samsung Galaxy S7 (Android 7)
• Huawei Media Pad M3 Lite 10 (Android 7)
• Samsung Galaxy S6 (Android 6.0.1)

►Video from Google Pixel 3a
![20190715_144803](https://user-images.githubusercontent.com/51314259/61214818-a1106680-a711-11e9-89ee-08e90daac67e.gif)


It seems that this behavior occurs while playing a video from Udemy as well.
►Video from Google Pixel 3a while playing a video in normal view
![20190715_150518](https://user-images.githubusercontent.com/51314259/61215114-7ffc4580-a712-11e9-8a9c-0c70d4bbf585.gif)

►Video from Google Pixel 3a while playing a video in full screen mode
![20190715_145142](https://user-images.githubusercontent.com/51314259/61215197-c5207780-a712-11e9-9c98-715e88bec12a.gif)

@vesta0 Should I open a separate bug for the above described issue?

**Comment by jacktose** [comment] 2019-07-15 14:04
Still happening for me in Fennec 68.0 *and* Fenix 190713 18:02 (Android 8.1.0).

I reported in webcompat/web-bugs#34593 and that was closed as a duplicate of [bug 1555511](https://bugzilla.mozilla.org/show_bug.cgi?id=1555511). Since the behavior is in both browsers, is this issue a duplicate of the Bugzilla bug?

**Comment by kbrosnan** [comment] 2019-07-15 14:08
Can the behavior be reproduced in [Reference Browser](https://play.google.com/apps/testing/org.mozilla.reference.browser) which uses Gecko 70? If not then we can close this bug and it will be fixed when Fenix picks up Gecko 69+.

**Comment by ekager** [comment] 2019-07-30 22:44
We are now on 69 so let's test this. I can't reproduce locally anymore on the original site, but adding QA needed

**Comment by AndiAJ** [comment] 2019-07-31 07:24
Hi, **verified as fixed** on Nightly Build **#12112106 from 30/7** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3  (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

**Closed** 2020-08-12 17:45 UTC
Labels: P2, b:landscape, eng:qa:verified, needs:investigation, 🐞 bug
