### ISSUE TITLE
Kill process should do as "quit"

### ISSUE THREAD

**Issue by inwardmovement** [mozilla-mobile/fenix#14221] opened 2020-08-26 12:20 UTC
Closing Firefox from the task manager should do as "quit" (therefore delete navigation data if checked). I think it was the case before the last update.

`Mozilla/5.0 (Android 8.0.0; Mobile; rv:79.0) Gecko/79.0 Firefox/79.0`

**Comment by miDeb** [comment] 2020-08-26 13:08
Are you in the right bug tracker? Your user agent doesn't look like this is an android browser.

**Comment by inwardmovement** [comment] 2020-08-26 13:29
The method I used to get my user agent seemed not reliable, I fixed it thanks.

**Comment by miDeb** [comment] 2020-08-26 13:35
Then I think it's a duplicate of https://github.com/mozilla-mobile/fenix/issues/12940.

**Closed** 2020-08-26 14:15 UTC
Labels: needs:triage
