### ISSUE TITLE
[Bug] Page splashes after the browser is restored from recents

### ISSUE THREAD

**Issue by daozhihun** [mozilla-mobile/fenix#13161] opened 2020-07-31 11:17 UTC
## Steps to reproduce

* Opens serveral pages, like https://support.mozilla.org/zh-CN/kb/update-latest-version-firefox-android
* Swipe up from the tray to return to desktop.
* Use other apps.
* Open recents tray, and choose Fenix to restore it.

### Expected behavior

Previous pages are restored quickly.

### Actual behavior

The page twinkles: first turned white and the page restored.
This is not happen on current version of Firefox for Android (68.11.0), the page won't twinkle.

### Device information

* Android device: vivo iQOO 3, Android 10
* Fenix version: 79.1 beta 1

**Comment by jakefleming156** [comment] 2020-08-04 18:11
Dupe of #9915.

**Closed** 2020-08-04 18:16 UTC
Labels: Skittle, 🐞 bug
