### ISSUE TITLE
Some changes to the tabs menu

### ISSUE THREAD

**Issue by AndRo-Marian** [mozilla-mobile/fenix#12273] opened 2020-07-04 10:04 UTC
1. On the tab preview align the domain to bottom and make the title to be in 3 line. I tuink is soace for 3.
1. Make the (+) height smaller to match the height of the (+) from private window. And i like is smaller, too big.

![Screenshot](https://user-images.githubusercontent.com/48178307/86510252-d1f01c80-bdf6-11ea-87fc-a9d2441694ad.jpg)UNITO-UNDERSCORE!20200704-124932!
![Screenshot](https://user-images.githubusercontent.com/48178307/86510253-d3214980-bdf6-11ea-91cd-87365e15a682.jpg)UNITO-UNDERSCORE!20200704-124939!

**Comment by amkcpu** [comment] 2020-07-04 13:56
Request 1) is a duplicate of #10683.

**Comment by amkcpu** [comment] 2020-08-30 08:53
Request 2) is a duplicate of #13277.

**Comment by ekager** [comment] 2020-12-17 21:52
Both of the linked dupes have been closed out. Closing this as well

**Closed by ekager** 2020-12-17 21:52 UTC
Labels: needs:triage
