### ISSUE TITLE
[Bug] Release 85.1.0 makes web.de slideshow articles unusable

### ISSUE THREAD

**Issue by sonora** [mozilla-mobile/fenix#17599] opened 2021-01-23 05:18 UTC
Can I pleae report that ever since release 85.1.0 all 'slideshow type' news articles they call "Galerie" of the German news portal web.de became essentially unusable.

These pages are one of several templates the news portal uses repeatedly, and can be discovered by looking for the white text on gray background "Galerie" label of certain articles on https://web.de, in particular under https://web.de/magazine. They consist of a slideshow type series of pictures which can be swiped consecutively from right to left, while for each picture an accompanying text can be pulled up or down from the bottom to display as an overlay or collapse. All these functions worked flawlessly up to and including release 84.1.4.

85.1.0 introduces the issue that the actual content area of the page becomes blank (white) at some point, leaving only the slide counter and the 'X' exit control visible. At this point tapping the 'X' seems the only option left, you cannot advance the article any further. The issue is best reproduced if you perform a pinch zoom in any picture area of such a Galerie type web page. But the appearance of the issue is not limited to pinch zooming, it often appears, less regularly reproducible, when swiping through such a web page, or showing/hiding the overlay text.

I am using Firefox 85.1.0, with Firefox's  'Desktop site' option being off, on several devices, e.g. the Samsung Galaxy Xcover 4 and 4s.

A deep link to an example page is  https://web.de/magazine/politik/us-politik/joe-bidens-wahl-symbolisiert-neustart-usa-oval-office-35463756, but this issue applies to all articles found on https://web.de/magazine/ which are labeled with the white text on gray background expression "Galerie". On each you have to the tap 'Bildergalerie starten' to enter the article slideshow.

I attach 2 screenshots of how such a webpage appears before and when the issue appears.
 
![20210123_060919](https://user-images.githubusercontent.com/845735/105569506-604fcf80-5d42-11eb-9b3b-623b2687b285.jpg)
![20210123_060701](https://user-images.githubusercontent.com/845735/105569510-66de4700-5d42-11eb-94db-2753735e27be.jpg)

**Comment by amedyne** [comment] 2021-01-26 02:50
@sonora What Android Device and Android version do you have?

**Comment by sonora** [comment] 2021-01-26 07:17
I observe the issue on at least the following devices:
- Samsung Xcover 4s, Android 10 stock ROM
- Samsung Xcover 4, Android 9 stock ROM
- Samsung Galaxy Tab A6, Android 5.1.1 stock ROM

**Comment by sonora** [comment] 2021-02-17 07:45
Using 86.1.0-rc.1, the behavior improved slightly. The effect seems not anymore be provoked sporadically and spontaneously by swipin,  but can still reliably be reproduced by pinch zooming the images.

**Comment by Mugurell** [comment] 2021-02-24 08:50
Thank you for reporting this!
I can reproduce exactly like described here on Firefox, incl latest Nightly but interestingly this doesn't seem to be an issue with the GVE app.

@sonora Have you seen this issue happening on other websites also?
This issue might be indicative of some bigger problems or it could be something particular to this website.

**Comment by sonora** [comment] 2021-02-24 22:30
@Mugurell Thanks for responding to this!

I may have been too optimistic saying that the issue improved with v86.1, after more testing it is likely unchanged. But I am rather certain that the issue started with the advent of v85.1, before that version (or coincidentally time, not sure :) ) there was no issue whatever with swiping or pinchzooming on that web site.

I had also made the site owners web.de aware of this posting here, but received little technical enoigh response to give me much hope they understood the issue or are really looking into it.

I have not posted a separate screenshot for it, but quite frequently while tapping or swiping through such a slide show, not the picture itself but  the bottom stripe of the page goes white( the bottom area shown black in my screenshot 2 above, which is actually the collapsed picture caption). That's why this reminded me of #18004, though it may in deed be unrelated.

I have yet to find another web site exhibiting the issue, will keep my eyes open for that.

**Comment by sonora** [comment] 2021-02-24 22:55
PS: Here's a second web site with the same issue: gmx.net/magazine (again you have to look for the 'Galerie' labeled articles).

 But I think this is of limited use, they seem to simply use the very same web slideshow engine, so it's no surprise.

**Comment by Mugurell** [comment] 2021-02-25 13:29
I can reproduce this on GVE also.
Moving it to Bugzilla.

**Comment by Mugurell** [comment] 2021-02-25 13:29
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1694944

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by Mugurell** 2021-02-25 13:29 UTC
Labels: 🐞 bug

**Comment by sonora** [comment] 2021-03-29 06:31
Ever since a few days ago, the issue has disappeared for me, either with something fixed in fenix 87.0.0-rc.1, or they have made a change to their website.

**Comment by Mugurell** [comment] 2021-03-29 15:04
Thank you for the update!
I cannot reproduce this anymore even on the current Release so I'm thinking that something changed on the website.
Which is still good for us!

**Comment by sonora** [comment] 2021-03-30 08:14
Well, yes and no, because it seems we **do** have an issue in Firefox which produces a fundamental usability problem on some websites  while other browsers had no such issue.

And for now we have lost how to reproduce it, cannot investigate, so it may re-occur somewhere any time?
