### ISSUE TITLE
FNX-4661 ⁃ [Bug] I can't open the comment section in YouTube

### ISSUE THREAD

**Issue by joelocandol** [mozilla-mobile/fenix#10887] opened 2020-05-25 00:28 UTC
## Steps to reproduce
Got at the bottom of a video at the YouTube webpage and touch the "comment" bar 

### Expected behavior
Open the comment section

### Actual behavior
Nothing happens, like if I hadn't touched it

### Device information
Oukitel c5

* Android device: 7.0
* Fenix version: Nightly 200524 06:01 (Build #2015742129)

The bug had been presented in old version too (around version of 1 month o so)

**Comment by LittleAngelwings** [comment] 2020-05-25 02:20
Seems to be a dupe of this https://github.com/mozilla-mobile/fenix/issues/10720

**Comment by LaurentiuApahideanSV** [comment] 2020-05-25 10:00
The issue has already been reported here: #10720  . I will close this issue as it will be handled there.

**Closed** 2020-08-10 22:31 UTC
Labels: 🐞 bug
