### ISSUE TITLE
[Bug] Two finger scrolling selects instead of scrolling on Chrome OS

### ISSUE THREAD

**Issue by alex-mayorga** [mozilla-mobile/fenix#13414] opened 2020-08-08 00:29 UTC
## Steps to reproduce
Install https://play.google.com/store/apps/details?id=org.mozilla.fenix in Chrome OS
Load https://www.mozilla.org/ on Firefox Nightly
Try to scroll with two fingers

### Expected behavior
Web content scrolls normally

### Actual behavior
Web content is selected and scrolls erratically.

### Device information

* Android device: Lenovo 100e Chromebook
* Fenix version: 200807 06:01 (Build #2015756529)

**Comment by hwinnemoe** [comment] 2020-08-08 09:41
Duplicate of #3708

**Comment by NotWoods** [comment] 2020-08-08 16:29
Closing as duplicate. For now touchscreen usage works on Chrome OS.

**Closed by NotWoods** 2020-08-08 16:29 UTC
Labels: needs:triage, 🐞 bug
