### ISSUE TITLE
[Bug]: [a11y] The "Couldn't download wallpaper. Try Again" snackbar is not selected with talkback when tapped in the middle

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#27131] opened 2022-09-23 13:42 UTC
### Steps to reproduce

Preconditions:
The user had just installed/updated the Firefox Browser app and has stable network connection.
Turn TalkBack (or the available screen reader) on.
1. Install Fenix and skip the onboarding.
2. Visit a webpage and then return to Homepage. Visit the webpage again.
3. Disconnect from network. 
4. Go to homepage where the Wallpaper Selection Tool will be displayed.
5. Double tap on a thumbnail to trigger the "Couldn't download wallpaper. Try Again" snackbar.
6. Tap on the middle of the snackbar.

### Expected behaviour

Talkback announces "Couldn't download wallpaper. Try Again button". 

### Actual behaviour

Talkback incorrectly selects and announces the "Explore more wallpapers" when tapping the middle of the snackbar, as the snackbar overlaps the link.
The user has to tap on the left side of the snackbar in order for the Talkback to properly select and announce the error message.

### Device name

Google Pixel 6 

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 107.0a1 from 09/23

### Additional information

https://user-images.githubusercontent.com/89388888/191973799-bf43bb8d-0314-4717-b645-a0ea003dee6b.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21649)

**Comment by cpeterso** [comment] 2022-09-23 20:00
High priority for v107, but not a blocker for MR v106.

**Comment by mcarare** [comment] 2022-10-05 13:03
I also changed the title to make it obvious the problem is with the snackbar not being selected properly, not with the content read when it is selected.

**Comment by cpeterso** [comment] 2022-10-14 22:26
> Even with a standard snackbar (regardless of the duration that is set), the talkback behavior is the same, so I do not think we can do something about it. And if in this case, the try again button is reachable for Talkback users by swiping, it should be enough to ensure the feature can be used.

@mcarare In that case, do you think we should close this bug as WONTFIX or not actionable?

**Comment by mcarare** [comment] 2022-10-17 08:02
@cpeterso Yes. This is not actionable.

**Comment by cpeterso** [comment] 2022-10-18 22:15
Thanks. In that case, I'll close this issue.

**Closed by cpeterso** 2022-10-18 22:15 UTC
Labels: 🐞 bug, access, S3, needs:triage, Feature:Wallpapers
