### ISSUE TITLE
FNX2-13494 ⁃ [Bug] Sometimes the pages cannot be loaded/reloaded no matter how many times I click the reload button

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11501] opened 2020-06-12 02:03 UTC
## Steps to reproduce
This is a bit hard to reproduce but I've been facing this regularly over these past few months.

1. Open a website 
1. Quickly open a new tab and load a new website before the existing website loads.
1. Wait for a while before you get back to the previously opened tab ( or you could open further sites before getting back) after a few minutes ( I don't know how many minutes).
1. Click on the reload button.
1. Doesn't reload no matter how many times I click the reload button.

• The only way to load the website is you need click the address bar and the click the enter button on the keyboard. 

Edit: For anyone looking at this issue, please also see https://github.com/mozilla-mobile/fenix/issues/11501#issuecomment-646914623.

### Expected behavior
Website should reload on clicking the reload button

### Actual behavior
Website doesn't reload on clicking the reload button

### Device information
* Android device: Motorola One Power, Android 10.
* Fenix version: 5.2.0-beta.1 and other versions as well including Nightlies.

![20200612](https://user-images.githubusercontent.com/42088907/84456927-d50d4800-ac50-11ea-83d8-f9428d7b274f.gif)UNITO-UNDERSCORE!072136!

**Comment by sheikh-azharuddin** [comment] 2020-06-12 04:22
I faced this issue several times on slow network..the only resolution is clicking on the address bar and press the enter(go) button on the keyboard. The reload button should behave like this but it does not work

**Comment by Cheap-Skate** [comment] 2020-06-12 12:17
I have this issue too, possibly also related to poor network connectivity, or possibly related to Fenix having been backgrounded for a while (i.e. when Fenix comes back to the foreground the page won't load). It only happens occasionally.  I don't have STR I'm afraid.

**Comment by Cheap-Skate** [comment] 2020-06-14 12:53
I saw it just now when I brought Fenix out of the background. reuters.com homepage was readable & scrollable but I could not reload it however hard I tried. 

(not the same as the bug where pages turn into about:blank, I have that bug too!)

**Comment by SS1113** [comment] 2020-06-14 13:06
> (not the same as the bug where pages turn into about:blank, I have that bug too!)

I have this bug too, I have experience it regularly. With the STR I mentioned in the issue post this can be reproduced as well but one thing to keep in mind that it doesn't always reproduce.

**Comment by SS1113** [comment] 2020-06-20 01:21
@ekager @sv-ohorvath I have the exact steps to reproduce. 

**Steps to reproduce*:

1. Load https://www.androidpolice.com/
Or any other site

2. Add it as a top site by clicking "Add to top sites" in the bottom navigation three-dot menu.

3. Then at fenix homescreen click the site you have added as a top site

4. Then immediately stop its loading by clicking the stop reload icon in the bottom navigation bar menu. (Don't let the site to load!)

5. Now click the reload icon in the bottom navigation three-dot menu

5. Observe that the website doesn't load no matter how many times you click the reload button.


I have reproduced this on **Motorola One Power, Android 10, On **`5.2.0`** (migration build from Taskcluster), **`Nightly 200619 06:01`**.


I'm not sure if this is this is the root cause of the bug I have reported.

**Comment by SS1113** [comment] 2020-06-23 01:46
@ekager sorry for tagging you again, but I haven't recieved any reply from you or the QA, as you are marking it as a `S1` type issue I thought I should ping you again and know if you reproducing this issue as well.

**Comment by ekager** [comment] 2020-06-23 02:49
Thanks for the STR! I'll try to look into it this week

**Comment by ekager** [comment] 2020-06-23 19:09
I think this is a GV bug, opened https://bugzilla.mozilla.org/show_bug.cgi?id=1647823

**Comment by snorp** [comment] 2020-07-15 20:55
What's happening here is that the load is cancelled before it is "committed", so the URI of the page is never changed to the requested one. As such, reloading will end up reloading the initial about:blank. This is the expected behavior for GV, though I agree it's not very obvious at first.

I suggest Fenix or A-C mitigate this in their reload impl by first checking to see if there was ever a successful load in this tab. If yes, reload as normal. If not, just try to load whatever the initial url was (which it would've need to store somewhere earlier).

**Comment by ShatteredPixel** [comment] 2020-07-16 12:47
Hi, I am the reporter of this bug. Please let me know if I can provide you any more information. 

Thank you! :)

**Comment by ShatteredPixel** [comment] 2020-07-19 01:22
> What's happening here is that the load is cancelled before it is "committed", so the URI of the page is never changed to the requested one. As such, reloading will end up reloading the initial about:blank. This is the expected behavior for GV, though I agree it's not very obvious at first.
> 
> I suggest Fenix or A-C mitigate this in their reload impl by first checking to see if there was ever a successful load in this tab. If yes, reload as normal. If not, just try to load whatever the initial url was (which it would've need to store somewhere earlier).

@snorp I'm also experiencing this randomly even when I don't cancel the loading by clicking reload Icon in the 3-dot menu. Sites suddenly stop loading for no apparent reason when I open or type in the website's address, my network connection is stable.

**Comment by sflorean** [comment] 2020-08-04 14:56
Tested on Nightly 8/4 following the steps provided and I didn't encounter any issues when loading/reloading the pages, a couple of times. Closing as verified.

**Closed** 2020-08-12 17:29 UTC
Labels: Feature:Browsing, S1, eng:qa:verified, needs:ac, needs:investigation, 🐞 bug
