### ISSUE TITLE
FNX-4905 ⁃ [Bug] developer.android.com page appears broken

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#1255] opened 2019-03-29 13:36 UTC
## Steps to reproduce
1. Visit http://developer.android.com in the latest Fenix

### Expected behavior
CSS stylesheets are applied and look similar to Fennec or Chrome on mobile.

### Actual behavior
CSS stylesheets are not applied. The page appears broken.

### Device information
* Android device: Android Pie
* Fenix version: Build #10851633

**Comment by vesta0** [comment] 2019-04-03 21:07
@cpeterso is there a GV bug for this?

**Comment by cpeterso** [comment] 2019-04-03 22:56
I can reproduce this bug in Fenix, but not Fennec 66/67/68 or Focus+GV 65. I can't test RB because it crashes.

I filed a new GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1541632

**Comment by kbrosnan** [comment] 2019-04-27 04:37
This is fixed in a current Fenix build.

**Closed** 2020-08-11 06:43 UTC
Labels: b:web-content, eng:qa:verified, needs:gv, 🐞 bug
