### ISSUE TITLE
Android's menu button doesn't open firefox' menue

### ISSUE THREAD

**Issue by maksim-ka** [mozilla-mobile/fenix#15475] opened 2020-09-27 10:51 UTC
Hello,
In Android you have three navigation buttons which functionality can be customized. I prefer to have The recent apps button configured as Menu button. This allows me when I press it to comfortably open the  menu/settings.

I expirence this since last major update. Though will be fixed with 81.1.1 but it's not so I thought I report it. 

Thank you

**Comment by Poopooracoocoo** [comment] 2020-09-27 16:52
Dupe of #14795

**Comment by ale82to** [comment] 2020-09-28 00:29
I ve reported this bug back to Firefox preview times and developer did not bother adding proper support for keyboard Shortcuts, shame!

**Comment by sflorean** [comment] 2020-09-29 12:35
Closing as duplicate of #14795. 
Thank you @maksim-ka for your report! Please follow the discussions from the above issue.

**Closed by sflorean** 2020-09-29 12:35 UTC
Labels: needs:triage
