### ISSUE TITLE
[Bug] "Recently Bookmarked" is not shown fine

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#3964] opened 2019-07-10 08:29 UTC
## Steps to reproduce
Sign in with FxAccount, having several bookmarks saved

### Expected behavior
All bookmarks/folders/separators are shown fine

### Actual behavior
Recently Bookmark is shown as:
![Recently Bookmarked](https://user-images.githubusercontent.com/1897507/60953406-64053800-a2fd-11e9-959e-088c4e6dcda4.png)

If you click on it, google page is open with the text prefilled in the search box

## More Info
In case you can't repro, I should mention that the FxAccount used was synced before on iOS device, where there is a `Recent Bookmarks` list.

### Device information

* Android device: Pixel 3
* Fenix version: 7/9

**Comment by softvision-miralobontiu** [comment] 2019-11-25 10:05
I was not able to reproduce this issue on the latest Nightly 11/25 with Google Pixel 3 (Android Q), nor with Huawei P9 Lite (Android 7).
@isabelrios could you please, retry?

**Comment by mcarare** [comment] 2019-12-09 09:53
@isabelrios Can you please let us know if the bug is still reproducible on your part? TY!

**Comment by vesta0** [comment] 2019-12-16 19:22
Closing this as it can not be reproduced. Please feel free to re-open if this is still an issue.

**Closed by vesta0** 2019-12-16 19:22 UTC
Labels: Feature:Bookmarks, Feature:Sync, 🐞 bug
