### ISSUE TITLE
read mode freezing

### ISSUE THREAD

**Issue by carlos-rodrigues-1123** [mozilla-mobile/fenix#9276] opened 2020-03-20 14:58 UTC
### Expected behavior
Recurring freeze when in read mode, can't scroll up or down

### Device information
Xiaomi Mi A3

* Android device: ? Xiaomi Mi A3
* Fenix version: ? Last one

**Comment by sflorean** [comment] 2020-04-13 16:02
Wasn't able to reproduce with Xiaomi Redmi Note 8T (Android 9) and latest Nightly build. @carlos-rodrigues-1123 this is still an issue for you?

**Comment by carlos-rodrigues-1123** [comment] 2020-04-13 17:44
Hi. I'm sorry. It was so annoying that at the end I uninstalled it and back to regular Firefox Browser App.I will try again and any other issue I will contact you.Regards.Em 13 de abr de 2020 13:03, Sorina Florean <notifications@github.com> escreveu:
Wasn't able to reproduce with Xiaomi Redmi Note 8T (Android 9) and latest Nightly build. @carlos-rodrigues-1123 this is still an issue for you?

**Comment by ebalazs-sv** [comment] 2020-07-10 07:11
I could not reproduce this issue on Nightly 200709 GV 80 from 7/9 with Xiaomi Mi A1 (Android 9).
Since the reporter did not mentioned again about this issue, I will close it for now. 
Please reopen it if this issue occurs again, with any additional information about the behavior. Thanks!

**Closed by ebalazs-sv** 2020-07-10 07:11 UTC
Labels: needs:STR, needs:triage, 🐞 bug
