### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ZSongguo** [mozilla-mobile/fenix#21243] opened 2021-09-11 08:58 UTC
反馈一个bug
在搜索的时候如果输入字符+数字（带“.”的），浏览器就会把它识别成网址（例如搜索android4.4），打不开搜索引擎，而是出现连接失败提示，希望尽快修复！

Use translation software to translate into English:
Report a bug

When searching, if you enter characters + numbers (with "."), the browser will recognize it as a URL (for example, search for android4.4), and the search engine cannot be opened, but a connection failure prompt appears. Hope to fix it as soon as possible !

**Comment by ZSongguo** [comment] 2021-09-11 08:59
> 反馈一个bug
> 在搜索的时候如果输入字符+数字（带“.”的），浏览器就会把它识别成网址（例如搜索android4.4），打不开搜索引擎，而是出现连接失败提示，希望尽快修复！
> 
> Use translation software to translate into English:
> Report a bug
> 
> When searching, if you enter characters + numbers (with "."), the browser will recognize it as a URL (for example, search for android4.4), and the search engine cannot be opened, but a connection failure prompt appears. Hope to fix it as soon as possible !

（In the Nightly version）

**Comment by LaurentiuApahideanSV** [comment] 2021-09-28 15:09
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/10516. I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-09-28 15:09 UTC
Labels: needs:triage
