### ISSUE TITLE
[Bug] Weird dark rectangle briefly appears on new tab button when tab tray opens

### ISSUE THREAD

**Issue by cartr** [mozilla-mobile/fenix#13776] opened 2020-08-13 05:21 UTC
## Steps to reproduce

Open the tab tray.

### Expected behavior

A weird dark rectangle does not appear on top of the new tab button.

### Actual behavior

A weird dark rectangle appears on top of the new tab button and immediately fades out.

![Screenshot_20200812-221444733](https://user-images.githubusercontent.com/5241813/90097164-2afe7a80-dcea-11ea-8bff-65b5346fcee5.png)

### Device information

* Android device: ASUS ZenFone 6
* Fenix version: Nightly 200812 06:01 (Build #2015757491)

**Comment by cadeyrn** [comment] 2020-08-13 07:54
Duplicate of #11180.

**Comment by liuche** [comment] 2020-08-18 00:00
Duping to #11180

**Closed by liuche** 2020-08-18 00:00 UTC
Labels: needs:triage, 🐞 bug
