### ISSUE TITLE
[Bug] Location errors until you check the doorhanger's "don't ask again" box

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3207] opened 2019-06-06 12:25 UTC
## Steps to reproduce
1. With system permission for location turned off (default setting), go to google.com/maps
2. Tap the get location button.
3. Tap allow on the app doorhanger.
4. Tap allow on the system dialog.

##Expected behavior
Location is detected.

##Actual behavior
The system dialog for location permission appears only the 2nd/3rd time you tap Allow on the app doorhanger. 
"Google can't determine your location" error is displayed.
After system permission is set, the app's doorhanger is displayed once again.

Only works on the first try if you check the "Don't ask again" checkbox from the start.

### Device information
* Android device: Motorola Nexus 6 (Android 7.1.1), Google Pixel (Android 9), HTC 10 (Android 8.0)
HTC Desire 820 (Android 6.0.1), Nexus 5 (Android 6), Galaxy Tab A 6 (Android 5.1.1)
* Fenix version: 6/6

**Comment by Amejia481** [comment] 2019-06-07 17:44
The same behavior can be seen on Fennec. I believe every time you hit the **get location** button,  the site reloads and request the permission again, as the **don't ask again** checkbox wasn't checked.

**Comment by sv-ohorvath** [comment] 2019-06-10 07:24
@Amejia481 I pressed the get location button, allowed the permission and the button still shows as location is disabled. Had to press it 3 more times to get it running. See this video:
![20190606_154905](https://user-images.githubusercontent.com/4037709/59179107-b40ba600-8b69-11e9-92e5-5f0fc7c25c5e.gif)

**Comment by Amejia481** [comment] 2019-06-24 15:19
I'm not quite sure, but I think the issue is more related to how the web site works. Does the same issue happen with another map like web sites like [mapquest.com](https://www.mapquest.com/), [openstreetmap.org](https://www.openstreetmap.org) or others? Either way, I will further investigate with the GeckoView team.

**Comment by Amejia481** [comment] 2019-06-24 19:20
GeckoView bug https://bugzilla.mozilla.org/show_bug.cgi?id=1561041

**Comment by bifleming** [comment] 2019-06-26 20:47
@cpe

**Comment by cpeterso** [comment] 2019-06-27 16:27
@Amejia481 filed GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1561041.

**Comment by cpeterso** [comment] 2019-10-31 17:48
Adding the GV bug to GV's November sprint because this bug is on Fenix's list of top 10 GV bugs. This is a longstanding, intermittent issue.

Is this reproducible in GVE?

https://bugzilla.mozilla.org/show_bug.cgi?id=1561041#c5

**Comment by Amejia481** [comment] 2019-11-01 13:27
> Is this reproducible in GVE?

Yes, it is.

**Comment by fluffyemily** [comment] 2019-11-26 17:11
This has been determined to be a DOM issue and has been moved to the DOM team.

**Comment by Amejia481** [comment] 2020-03-11 16:34
The issue have been partially fixed, the location is found, but we are getting the permission prompt twice see 
https://bugzilla.mozilla.org/show_bug.cgi?id=1621689

**Comment by sv-ohorvath** [comment] 2020-06-11 14:18
> The issue have been partially fixed, the location is found, but we are getting the permission prompt twice see
> https://bugzilla.mozilla.org/show_bug.cgi?id=1621689

Still the same result on Nightly 6/11.

**Comment by sv-ohorvath** [comment] 2020-07-01 13:22
Again I can't get Gmaps to find my location and save the permission exception.
STR:
I try to get directions from my location to another.
The app requests permission to access my location, I allow it and check the "Don't ask again" checkbox.
The system permission prompt doesn't appear anymore.
I go to system settings, allow the app to get my location.
Return to the app and set again my location as the starting point. 
The app asks repeatedly for permission even if I check the "don't ask again" box. Finally, Gmaps returns the "can't find your location" error.

**Comment by liuche** [comment] 2020-07-01 18:50
This is currently an S3 in Bugzilla - is this something that we want to bump the Gecko priority on @vesta0? it's waiting but won't get additional push unless we ask for it in the bugzilla.

**Comment by Amejia481** [comment] 2020-07-02 13:42
This could be a regression from https://github.com/mozilla-mobile/fenix/pull/10810
I will take a look.

**Comment by Amejia481** [comment] 2020-07-02 20:52
> Again I can't get Gmaps to find my location and save the permission exception on 79.0.0-beta3.
> STR:
> I try to get directions from my location to another.
> The app requests permission to access my location, I allow it and check the "Don't ask again" checkbox.
> The system permission prompt doesn't appear anymore.
> I go to system settings, allow the app to get my location.
> Return to the app and set again my location as the starting point.
> The app asks repeatedly for permission even if I check the "don't ask again" box. Finally, Gmaps returns the "can't find your location" error.

The issue will be covered in https://github.com/mozilla-mobile/android-components/pull/7607

**Comment by Amejia481** [comment] 2020-07-08 13:40
> Again I can't get Gmaps to find my location and save the permission exception on 79.0.0-beta3.
> STR:
> I try to get directions from my location to another.
> The app requests permission to access my location, I allow it and check the "Don't ask again" checkbox.
> The system permission prompt doesn't appear anymore.
> I go to system settings, allow the app to get my location.
> Return to the app and set again my location as the starting point.
> The app asks repeatedly for permission even if I check the "don't ask again" box. Finally, Gmaps returns the "can't find your location" error.

@sv-ohorvath  I think the issue should be fixed in nightly :)

**Comment by Diana-Rus** [comment] 2020-07-09 08:29
Hi, verified the scenario from [comment](https://github.com/mozilla-mobile/fenix/issues/3207#issuecomment-652415312) with Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (Android 7).

**Scenario 1 - From description - Gmaps**
- Samsung Galaxy S9 (Android 8) - another app allow permission is generated eventhough the location was determined previously ❌
- Sony Xperia Z5 (Android 7) - another app allow permission is generated eventhough the location was determined previously ❌
<details closed><summary>GIF with outcome</summary>

![20200709-085525](https://user-images.githubusercontent.com/49859863/87016330-3fc18d00-c1d7-11ea-8b3c-b1b6be729660.gif)
</details>

**Scenario 2 - When option "Remember decision for this site" is enabled - Gmaps**
<details closed><summary>Samsung Galaxy S9 (Android 8) ✔️</summary>

![20200709-085919](https://user-images.githubusercontent.com/49859863/87007490-0aaf3d80-c1cb-11ea-8bc8-e234937d15a0.gif)
</details>
<details closed><summary>Sony Xperia Z5 (Android 7) - Gmaps ✔️</summary>

![20200709-100203](https://user-images.githubusercontent.com/49859863/87008178-08011800-c1cc-11ea-8df4-4720eb5d5056.gif)
</details>

**Scenario 3 - From [comment](https://github.com/mozilla-mobile/fenix/issues/3207#issuecomment-655526843) - Gmaps**
- Samsung Galaxy S9 (Android 8) - another app allow permission is generated eventhough the location was determined previously ✔️
- Sony Xperia Z5 (Android 7) ✔️

**Note:**
- For first scenario for Google Pixel 3 XL (Android 9) after allowing both the app and system dialogs, with "Remember decision for this site" checked the location is still not recognized.
- For Scenario 1(the one from description) when testing with  https://www.mapquest.com/ and https://www.openstreetmap.org/ there is no other notification as it is for Gmaps - it's ok on both devices ✔️
- For Scenario 2(the one from description) when testing with  https://www.mapquest.com/ and https://www.openstreetmap.org/ there is no other notification as it is for Gmaps - it's ok on both devices ✔️
- I'll leave the ticket opened in order to check the failed points.

**Comment by Amejia481** [comment] 2020-07-09 15:37
@fluffyemily  the [AC part of the bug](https://github.com/mozilla-mobile/fenix/issues/3207#issuecomment-652415312) has been fixed but we are still getting the location permission twice that part is from this Bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1621689

**Comment by sv-ohorvath** [comment] 2021-06-02 09:02
There are still some issues, let's keep it.

**Closed** 2021-12-06 10:56 UTC
Labels: 🐞 bug, 🙅 waiting, needs:gv, E5, S3, wontfix
