### ISSUE TITLE
[Bug] On the second page, the top sites are cramped

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#19129] opened 2021-04-20 09:04 UTC
## Steps to reproduce
1. Make sure you have the most visited sites toggle enabled.
2. Browse a few pages, so that the top sites area is full.
3. From the homescreen, tap the private mode icon.
4. Tap again the private mode icon in order to return to the normal browsing homescreen.
5. Long-tap one of the top sites tiles, and select to "Delete from history".
6. Swipe to the second page of the top sites tiles, and observe the layout.

### Expected behavior
The second page of the top sites' layout has no issues. The tiles are displayed correctly.

### Actual behavior
The second page of the top sites displays the tiles cramped to the left side of the homescreen.
Please see the short video below.

### Device information
* Devices: Pixel 2 (Android 9, Samsung Galaxy Note 8 (Android 9)
* Firefox for Android version: 4/20 Nightly build
* Not reproducible on Beta 88.0.0-beta.6, nor on RC 88.1.1

https://user-images.githubusercontent.com/40694158/115368449-c3c98c00-a1cf-11eb-810b-aed987bd3b41.mp4

**Comment by hakkikaancaliskan** [comment] 2021-04-20 13:33
Duplicate of #18754

**Closed** 2021-04-20 13:43 UTC
Labels: Feature:TopSites, S3, 🐞 bug
