### ISSUE TITLE
[Bug]: Dropdown menus don't work on Firefox Nightly

### ISSUE THREAD

**Issue by ltrain5555** [mozilla-mobile/fenix#23392] opened 2022-01-25 04:23 UTC
### Steps to reproduce

1. Have a tab open
2. Go to a website with a dropdown box (e.g. https://support.mozilla.org/en-US/questions/firefox?show=all)
3. Click on a dropdown box (in this case, the one which shows "Updated")

### Expected behaviour

The dropdown menu should pop up with options to select, as it does on the stable release, e.g.
![Screenshot_20220124-225651_Firefox](https://user-images.githubusercontent.com/98373530/150910347-164ba3cf-9c21-4219-a458-3042b2191105.jpg)
 

### Actual behaviour

The box is highlighted, but nothing opens, e.g.
![Screenshot_20220124-225713_Firefox Nightly](https://user-images.githubusercontent.com/98373530/150910375-cfc13b9e-a573-4bc3-aa45-c90dc2805187.jpg)
 

### Device name

Samsung Galaxy S20 Ultra 5G

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1

### Additional information

It seems somewhat similar to this issue with the hamburger buttons https://github.com/mozilla-mobile/fenix/issues/23375

**Comment by cadeyrn** [comment] 2022-01-25 07:30
Duplicate of #23370 that was closed as an duplicate of the upstream issue https://bugzilla.mozilla.org/show_bug.cgi?id=1751674. A fix is already in progress.

**Closed** 2022-01-25 08:04 UTC
Labels: 🐞 bug, needs:triage
