### ISSUE TITLE
[Bug] Unwanted refresh gesture on taskcluster log

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#18128] opened 2021-02-23 16:00 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1- go to any TC log ([example](https://firefox-ci-tc.services.mozilla.com/tasks/IRw3yqIHRaKvbq9VDZFW_A/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FIRw3yqIHRaKvbq9VDZFW_A%2Fruns%2F0%2Fartifacts%2Fpublic%252Flogs%252Flive.log))
2- scroll down
3- then scroll up

### Expected behavior
It should scroll up
### Actual behavior
Refreshing page
### Device information

* Device vendor / model and Android version: XZ1 Android 11
* Firefox for Android version: 2/22 nightly

https://user-images.githubusercontent.com/17825767/108870560-49ceb980-7609-11eb-8ea4-85ed2ccda667.mp4

**Comment by Mugurell** [comment] 2021-02-24 08:14
Could be the same issue as on https://github.com/mozilla-mobile/fenix/issues/18072

**Comment by Mugurell** [comment] 2021-04-01 06:35
Thank you @hakkikaancaliskan !
So it seems like the issue is only half resolved.

Moving it to GeckoView.

**Comment by Mugurell** [comment] 2021-04-01 06:35
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1702402

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by Mugurell** 2021-04-01 06:35 UTC
Labels: needs:gv, 🐞 bug

**Comment by sflorean** [comment] 2021-04-13 15:01
I was able to reproduce this on latest Nightly build, only when the scroll is at the end of the page, with Pixel 3 (Android 11).
