### ISSUE TITLE
[Bug]: Reader estimated time disappears after switching tabs

### ISSUE THREAD

**Issue by nickcorrado** [mozilla-mobile/fenix#22634] opened 2021-11-30 14:31 UTC
### Steps to reproduce

1. Open a page in reader view.
2. Open a new tab or switch to another existing tab.
3. Switch back. The estimated time at the top of the page is gone.

### Expected behaviour

Estimated time remains visible throughout.

### Actual behaviour

Estimated time disappears after going back to the tab.

### Device name

Samsung Galaxy S8

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

I also reproduced the bug on the latest Nightly build #2015848683.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18774)

**Comment by LaviniaL99** [comment] 2022-01-10 12:37
Hello @nickcorrado 
Thanks for your report!
I tested the above issue on the latest Nightly build 97.0a1(Build #2015856555) and latest release version RC 96.1.1 (Build #2015855931) and I was not able to reproduce the issue.

**Devices used:**

- Samsung S10E -> Android 10
- Samsung Galaxy A32 5G->  Android 11
Can you please confirm if you are still able to reproduce the problem on the latest builds? If yes, please attach a video of the interest flow.
Thanks!

**Comment by gabrielluong** [comment] 2023-01-30 23:57
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1811751

**Closed by gabrielluong** 2023-01-30 23:57 UTC
Labels: 🐞 bug, Feature:ReaderMode, help wanted, qa-triaged
