### ISSUE TITLE
[Bug] Text input position not properly set

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#16105] opened 2020-10-21 22:24 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
One of many bugs related to keyboard in the recent nightly
Open 2 tabs one of which is fenix/issues
In this tab click on the filter textbox and type a few words
Now go to the other tab and come back
Tap on the textbox again
Tap somewhere else in the textbox and start typing
### Expected behavior
It starts typing where you most recently tapped
### Actual behavior
It types where you initially tapped. There is no way to change this position without closing the tab
### Device information

* Android device: Asus Zenfone
* Fenix version: nightly

**Comment by s-ankur** [comment] 2020-10-21 22:34
@makotokato this seems related to https://github.com/mozilla-mobile/fenix/issues/15855

**Comment by kbrosnan** [comment] 2020-10-22 06:07
Could be a dupe of bz-1672095

**Comment by liuche** [comment] 2020-10-29 03:02
Looks like that ticket is fixed in bugzilla, so I'm guessing it'll be in the next Nightly (or soon after).

Can any of you check this again on the latest nightly on 10/29?

**Comment by makotokato** [comment] 2020-10-30 04:45
Nightly 201028 has the fix of https://bugzilla.mozilla.org/show_bug.cgi?id=1672095 since GV version is 84.0a1-20201026...

**Comment by s-ankur** [comment] 2020-11-06 15:24
Seems to be solved for me

**Closed** 2020-12-18 06:29 UTC
Labels: needs:triage, 🐞 bug
