### ISSUE TITLE
[Bug]When I installed too many add-ons, the browser's sync function was invalid.

### ISSUE THREAD

**Issue by lomomcat** [mozilla-mobile/fenix#16357] opened 2020-11-03 22:46 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Install many add-ons(20 add-ons or even more), and perform a data synchronization.
**Add-ons Collection Information:**
_User id: 12325762
Collection name: fenix_
### Expected behavior
Sync successfully.
### Actual behavior
The browser's sync function lose effect. Nothing happens after tapping "Sync Now".
### Device information

* Android device: Xiaomi Redmi Note 8 Pro
* Fenix version: Nightly 201103 17:00
### GIF
![Screenrecorder-2020-11-04-07-02-03-800.gif](https://user-images.githubusercontent.com/62339707/98050056-eb1fdd00-1e6b-11eb-85f3-e2fb15d5fc2c.gif)

**Comment by lomomcat** [comment] 2020-11-03 22:48
https://twitter.com/lomomcat/status/1322945581648506881

**Comment by andreicristianpetcu** [comment] 2020-11-03 23:10
Can it be a dupe of this? https://github.com/mozilla-mobile/fenix/issues/15818

**Comment by lomomcat** [comment] 2020-11-03 23:26
After this issue is resolved, I'm going to make a monthly donation to Mozilla to buy some coffee for the engineers.
https://donate.mozilla.org

**Comment by lomomcat** [comment] 2020-11-12 18:15
Please fix it soon, thanks!

**Comment by lomomcat** [comment] 2020-11-15 09:10
Many days have passed and still nothing has happened.

**Closed** 2021-05-23 17:24 UTC
Labels: Feature:WebExtensions, wontfix, 🐞 bug
