### ISSUE TITLE
[Bug] Wasm benchmark regression for PSPDFKIT

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#17232] opened 2020-12-26 14:23 UTC
## Steps to reproduce
visit https://pspdfkit.com/webassembly-benchmark/
and wait 
### Expected behavior
it should run the test, just like beta
![Screenshot_20201226-162039_Firefox_Beta](https://user-images.githubusercontent.com/922368/103153090-911a0480-4796-11eb-95de-cb6995a26d11.png)

### Actual behavior
nightly is stuck in 'Running...'
![Screenshot_20201226-162057_Firefox_Nightly](https://user-images.githubusercontent.com/922368/103153106-a5f69800-4796-11eb-93b9-aefaf29e3934.png)

### Device information

* Android device: OnePlus 5t
* Fenix version: nightly

**Comment by andreicristianpetcu** [comment] 2020-12-26 14:24
Might this be related to cranelift? https://mozilla-spidermonkey.github.io/blog/2020/12/18/newsletter-8.html
![Screenshot_20201226-162419_Firefox_Nightly](https://user-images.githubusercontent.com/922368/103153129-dcccae00-4796-11eb-9d24-d9630e9dd7b0.png)

**Comment by kbrosnan** [comment] 2021-01-07 21:39
Fairly sure this is Firefox not being able to handle the Gecko message for exceeding the dom.max_script_run_time duration. Likely dupe of  #14959. If you set dom.max_script_run_time or dom.max_script_run_time_without_important_user_input to something large like `6000` (seconds) does the test page run to completion?

**Comment by andreicristianpetcu** [comment] 2021-01-07 23:56
Nope. It's still blocked @kbrosnan 

Can I run mozregression on my phone?

**Comment by MarcLeclair** [comment] 2021-06-09 21:07
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1715649

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by MarcLeclair** 2021-06-09 21:07 UTC
Labels: Feature:ErrorMessages, eng:performance, 🐞 bug

**Comment by lars-t-hansen** [comment] 2021-06-21 08:26
Unable to reproduce on various hardware with current nightly (see the bugzilla bug).  The original problem could indeed have been related to cranelift, but we use a different ARM64 optimizing compiler now.  @andreicristianpetcu, if you're still able to reproduce this problem with the current nightly, can you follow up in https://bugzilla.mozilla.org/show_bug.cgi?id=1715649?  Thanks.
