### ISSUE TITLE
`Inactive Tabs` section should be collapsed by default

### ISSUE THREAD

**Issue by szbergeron** [mozilla-mobile/fenix#21047] opened 2021-08-27 13:02 UTC
### Steps to reproduce

1. Have a substantial number of inactive tabs and active tabs open
2. Restart app
3. Open tab tray

### Expected behaviour

Inactive tabs menu should be collapsed. This is an alternative method of solving https://github.com/mozilla-mobile/fenix/issues/20637 from having scroll position set, and allows the user to do a fling and be stopped at the boundary between active and inactive tabs if they've scrolled away from that boundary

### Actual behaviour

Inactive tabs menu is expanded, and tray is scrolled to the bottom of that menu so the active tab (and temporally clustered tabs) are scrolled out of view

### Device name

Oneplus 8t

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

93.0a1

**Comment by kbrosnan** [comment] 2021-08-30 15:20
Duplicate of https://github.com/mozilla-mobile/fenix/issues/20855 which was duped to the issue you mentioned.

**Closed by kbrosnan** 2021-08-30 15:20 UTC
Labels: 🐞 bug, needs:triage
