### ISSUE TITLE
[Bug] Subtitles are unusable on youtube.com

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#2498] opened 2019-05-15 03:59 UTC
## Steps to reproduce
* Load a video on youtube.com
* Show subtitles
* Notice how the subtitles are smashed to the left (see picture)

### Device information
* Android device: Samsung S10e
* Fenix version: Latest from playstore

Works in: GVE, Fennec, Chrome

![Screenshot](https://user-images.githubusercontent.com/4297388/57747522-b540d480-768a-11e9-86b4-9a6ed03f89fc.jpg)UNITO-UNDERSCORE!20190513-191610!UNITO-UNDERSCORE!Firefox Preview!

**Comment by bifleming** [comment] 2019-05-29 18:58
@agi90 can you still reproduce this?

**Comment by jonalmeida** [comment] 2019-05-29 18:59
I can't repro this in today's (29/05) build.

**Comment by vesta0** [comment] 2019-05-30 22:46
@agi90 please re-open this if you are able to reproduce it :)

**Comment by agi90** [comment] 2019-05-31 07:47
I can still repruduce this but I just noticed I have WebRender on (which would make this a GeckoView bug) can someone check with WebRender on?

**Comment by jonalmeida** [comment] 2019-05-31 14:16
@agi90 with webrender on I don't see the issue:
<img width="576" alt="Screen Shot 2019-05-31 at 10 14 49 AM" src="https://user-images.githubusercontent.com/1370580/58711722-07713d80-838d-11e9-972c-de9ed5156fd9.png">

However, I did notice that some videos have the same issue you reported (with and without webrender):
<img width="579" alt="Screen Shot 2019-05-31 at 10 12 31 AM" src="https://user-images.githubusercontent.com/1370580/58711731-0a6c2e00-838d-11e9-9f8a-24acff2b63c1.png">


Re-opening this as a webcompat issue.

**Comment by agi90** [comment] 2019-06-04 08:27
We should remove the Needs STR tag probably.

**Comment by vesta0** [comment] 2019-06-04 19:45
@jonalmeida Would you transfer the bug to the webcompat repo or tag them here?

**Comment by jonalmeida** [comment] 2019-06-05 14:45
I've created a webcompat issue so I'm going to close this since there isn't anything we can do from our side.

https://github.com/webcompat/web-bugs/issues/32472

**Comment by agi90** [comment] 2019-06-05 15:28
I don't understand why you say there's isn't anything we can do on Fenix? this works on Fennec and GeckoView Example

**Comment by jonalmeida** [comment] 2019-06-10 01:28
> I don't understand why you say there's isn't anything we can do on Fenix? this works on Fennec and GeckoView Example

@agi90 I can see the same issue on fennec as well, with the same video link you shared. Some videos do have subtitles showing up correctly so I assumed this was something to do with the youtube's way of rendering subtitles.

In the webcompat issue I linked to two videos where subtitles show correctly for only one.

I could be wrong, so I'll re-test this again tomorrow.

**Comment by jonalmeida** [comment] 2019-06-11 15:32
@agi90 I can reproduce the problem in Fennec *AND* found the issue that youtube has. :)

Auto-generated subtitles are squashed to the left, but subtitles that are submitted from the video owner are fine. Updating the webcompat ticket with this info as well.

**Comment by agi90** [comment] 2019-06-11 16:20
Cool, thanks for looking into this!

**Closed** 2020-08-26 05:35 UTC
Labels: b:webcompat, 🐞 bug
