### ISSUE TITLE
[bug] Custom tab text too small

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#5344] opened 2019-09-15 18:57 UTC
First reported in #5334.

## Steps to reproduce
Video attached.

The text size in the loaded url bar is tiny

### Expected behavior
Show the website name only, 
Tap-hold on the url bar current behavior shows a pop-up for "copy" 
I suggest: 
Center the popup
The pop-up header should be the url
Options for copy/private tab/open in..

### Device information

* Android device: 8.1.0 
* Fenix version: Nightly 190914 06:02 (Build #12570610)
📦: 13.0.0, 1f55c03be
🦎: 71.0a1-20190913092859
![20190914_141745](https://user-images.githubusercontent.com/50635951/64912260-a894c180-d6fa-11e9-8933-52930a4af7cc.gif)

**Comment by sv-ohorvath** [comment] 2019-09-16 13:00
This also happens on the browser URL bar (in edit mode too), on a Samsung Tab A6 (Android 5.1.1)
![screencap](https://user-images.githubusercontent.com/4037709/64959775-89cd3100-d89a-11e9-9870-0495efa9d663.png)

**Comment by jonalmeida** [comment] 2019-09-16 14:51
Looks like a regression of https://github.com/mozilla-mobile/fenix/issues/3259 from our attempt at fixing the text size issue.

**Comment by rocketsroger** [comment] 2019-09-18 17:17
Fixed in A-C 14.0.0

**Comment by jonalmeida** [comment] 2019-09-18 17:46
@rocketsroger Fenix leaves issues open and adds the 'eng:qa:needed' label for QA to verify the changes.

**Comment by rocketsroger** [comment] 2019-09-18 17:47
Understood.  I'll assign under my name then.  Thanks for letting me know.

**Comment by nahuhh** [comment] 2019-09-20 01:30
Looks fixed

**Comment by softvision-miralobontiu** [comment] 2019-09-20 12:03
Verified as fixed with Nexus 9 tablet (Android 7.1.1), Samsung Galaxy Tab A6 (Android 5.1), and Xiaomi Mi 8 Lite (Android 9) with the latest Nightly build 190919 (#12621819).

**Closed by softvision-miralobontiu** 2019-09-20 12:03 UTC
Labels: Feature:CustomTabs, a-c, eng:qa:needed, 🐞 bug
