### ISSUE TITLE
Cannot download .zip file with FF Beta6

### ISSUE THREAD

**Issue by HelmutL** [mozilla-mobile/fenix#16002] opened 2020-10-18 11:43 UTC
### Steps to reproduce
Try to download https://covid19-dashboard.ages.at/data/data.zip

### Expected behavior
download file

### Actual behavior
download is started but never ends

### Device information
Honor View 20 

* Android device: 
Android 10
* Fenix version: 
Firefox 82.0.0.beta.6
 
### Note:
There is no problem with nightly builds (83.0a1 ..)

**Comment by sflorean** [comment] 2020-10-19 13:38
Thank you for the report! Closing as duplicate of #15378.

**Closed by sflorean** 2020-10-19 13:38 UTC
Labels: needs:triage, 🐞 bug
