### ISSUE TITLE
[Bug] Scroll position lost when app exits

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#6726] opened 2019-11-20 21:13 UTC
### Steps to reproduce
- Scroll partway down a page
- Force close app
- Reopen app
- Reopen session

### Expected behavior
- Scroll position is saved (note that this is the behavior in Chrome)

### Actual behavior
- The top of the page is opened

### Device information

* Android device: Nexus 2 & Pixel 2 (both Android 10)
* Fenix version: Release

**Comment by sblatz** [comment] 2019-12-27 22:38
Is this something we need a GV API for? @cpeterso

**Comment by Baron-Severin** [comment] 2019-12-27 22:51
Depending on the performance impact (I haven't measured it), we might be able to store the current scroll position every few seconds while we're active.  I don't think we can get a reliable hook that will be triggered every possible way we can be killed.

**Comment by cpeterso** [comment] 2019-12-30 00:09
> Is this something we need a GV API for? @cpeterso

I think you can listen for scroll position changes with a GeckoView `ScrollDelegate`:

https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSession.ScrollDelegate.html

If the `ScrollDelegate` API doesn't meet your needs, talk to @fluffyemily.

**Comment by jonalmeida** [comment] 2020-03-02 18:20
When we land https://github.com/mozilla-mobile/android-components/issues/6018 we should get this for free - requires retesting.

**Comment by sblatz** [comment] 2020-03-03 18:55
I will test this tomorrow as it looks like it got closed 😄

**Comment by sblatz** [comment] 2020-03-05 20:45
This now seems to persist. Marking as QA needed 😄

**Comment by AndiAJ** [comment] 2020-03-06 09:05
Hi, **still reproducible** on the latest **`Nightly Build #20660604 from 3/6`** using the following devices:
• Google Pixel 3a XL(Android 10)
• Google Pixel 3a (Android 9)

► Video from  Google Pixel 3a (Android 9)
![20200306-103839](https://user-images.githubusercontent.com/51314259/76067896-d4ea1600-5f98-11ea-8e7d-6c3f775ead13.gif)

► Video from Google Pixel 3a XL(Android 10)
![20200306-104856](https://user-images.githubusercontent.com/51314259/76068216-6bb6d280-5f99-11ea-8793-e9b1b73c4502.gif)

**Comment by sblatz** [comment] 2020-03-09 17:08
@AndiAJ I'm still not able to reproduce this. Are you able to test again? I wonder if nightly hadn't been updated just yet.

**Comment by Diana-Rus** [comment] 2020-03-10 13:53
Hi, the issue still reproduces. It seems to be impacted by the ads sections or maybe in the amount of time the app is reopened.
OnePlus 7T Pro(Android10)
![20200310-153805](https://user-images.githubusercontent.com/49859863/76319027-43a3d800-62e7-11ea-91f5-bc9851afc328.gif)

Google Pixel 3XL(Android 9)
![20200310-152830](https://user-images.githubusercontent.com/49859863/76318072-d3488700-62e5-11ea-8f1e-9bc9b2814026.gif)

Sony Xperia Z5(Android 7)
![ezgif com-optimize](https://user-images.githubusercontent.com/49859863/76318540-887b3f00-62e6-11ea-9802-973da87aea51.gif)

Build: Firefox Preview Nightly 200310 (Build #20700606) GV: 75.0a1-20200309091841
Device: OnePlus 7T Pro (Android 10), Google Pixel 3 XL (Android 9), Samsung Galaxy S8+ (Android 8), Sony Xperia Z5 (Android 7).

**Comment by pocmo** [comment] 2020-05-04 17:34
Seems to be the same cause as https://github.com/mozilla-mobile/fenix/issues/9039

**Comment by pocmo** [comment] 2020-05-08 08:34
We landed a patch for this in AC and it should make it into the next Nightly. I'll add the QA label.

**Comment by AndiAJ** [comment] 2020-05-11 06:55
Hi, **verified as fixed** on the latest **`Nightly Build 200511  from 5/11`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200511-095053](https://user-images.githubusercontent.com/51314259/81532747-97758080-936d-11ea-93be-5f71ec3a23da.gif)

**Closed by AndiAJ** 2020-05-11 06:55 UTC
Labels: Feature:Browser, P2, eng:qa:needed, needs:ac, 🐞 bug
