### ISSUE TITLE
[Bug] Private mode tabs leaking into recently closed

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15032] opened 2020-09-12 23:08 UTC
## Steps to reproduce
Close a private mode tab
Open history/recently closed tabs
### Expected behavior
Unchanged
### Actual behavior
Private tab is recorded in history, might be considered serious violation of private mode
### Device information

* Android device: Asus Zenfone
* Fenix version: 
Nightly 200912 06:01 (Build #2015763443)
AC: 59.0.20200911130559, d974933d4
GV: 82.0a1-20200908095243
AS: 61.0.13

**Comment by s-ankur** [comment] 2020-09-12 23:09
Also for some reason GitHub is giving me the warning
`Your browser did something unexpected. Please contact us if the problem persists.`
I had to use chrome to file this bug. Is this an issue with the browser?

**Comment by cadeyrn** [comment] 2020-09-13 00:23
Duplicate of an AC issue: https://github.com/mozilla-mobile/android-components/issues/8390

**Comment by ekager** [comment] 2020-09-14 17:17
Should be fixed in next Nightly!

**Closed by ekager** 2020-09-14 17:17 UTC
Labels: needs:triage, 🐞 bug
