### ISSUE TITLE
[Bug]Firefox for Android downloads file pdf of length 0.00 MB. 

### ISSUE THREAD

**Issue by Czedula** [mozilla-mobile/fenix#15404] opened 2020-09-24 20:49 UTC
## Steps to reproduce
Go to a link which leads to a pdf file. Open the link, Firefox asks Download? answer yes, on the next screen where Firefox asks for opening the file, shows ths length of the pdf file 0.00 MB. And consequently when try to open an error message pops up, such as 'File has an invalid format, cannot open.' 

### Expected behavior
Correct file length to show and open the file. 

### Actual behavior
Described above.
![Screenshot_20200924-221051_Firefox](https://user-images.githubusercontent.com/71850927/94198773-13eda380-feb8-11ea-82a8-fa839d3180a8.jpg)

0.00 MB shown, real! and file not open. 

### Device information
Samsung Galaxy Tab S6 and Samsung Galaxy S10e

* Android device: 10
* Fenix version: ?

**Comment by Czedula** [comment] 2020-09-24 20:55
Another screenshot with the error message when trying to open the file. 
![Screenshot_20200924-225213_RAR](https://user-images.githubusercontent.com/71850927/94199372-01279e80-feb9-11ea-95fb-ac04cdb3a908.jpg)

**Comment by kbrosnan** [comment] 2020-09-24 23:34
Duplicate of #13031

**Closed by kbrosnan** 2020-09-24 23:34 UTC
Labels: Feature:Download, 🐞 bug
