### ISSUE TITLE
FNX-5234 ⁃ [Bug] Fenix crashes when Bookmarks from Library is opened

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#1762] opened 2019-04-18 08:15 UTC
## Steps to reproduce
1. Go to three-dot menu ~~> Library~~ > Bookmarks

### Expected behavior
The user should see the Bookmarks folder.

### Actual behavior
Fenix crashes and the app cannot be opened until the user clears data.

### Device information
* Android device: Samsung Galaxy Tab S3 (Android 8.0), HTC Desire 820 (Android 6.0.1),  Samsung Galaxy S8 (Android 9.0), HTC 10 (Android 8.0)
* Fenix version: 1.0.1916 (Build#11080612)
    1. Note
Please see attached logcat:

[1.txt](https://github.com/mozilla-mobile/fenix/files/3093366/1.txt)

**Comment by cadeyrn** [comment] 2019-04-18 08:17
Duplicate of #1732.

**Comment by vesta0** [comment] 2019-04-18 16:31
Will be addressed in #1732

**Closed** 2020-08-11 12:42 UTC
Labels: b:crash, 🐞 bug
