### ISSUE TITLE
Inconsistent rendering in Toolbar: Top

### ISSUE THREAD

**Issue by jsphslgr** [mozilla-mobile/fenix#19552] opened 2021-05-19 01:58 UTC
I am experiencing an intermittent bug in Beta. I have the Customize->Toolbar setting as "Top", and every so often there will be a grey bar the size of the toolbar across the bottom of the app, obscuring the bottom of a page. Scrolling further down does not work. Refreshing the page or scrolling up then down fixes the problem

With a similar frequency, sometimes the toolbar will cover the top of a page, even while I am unable to scroll up further. Refreshing the page or scrolling down then back up seems to fix the problem.

This has been happening for several revisions

**Comment by LaurentiuApahideanSV** [comment] 2021-05-19 08:29
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/14821. I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-05-19 08:29 UTC
Labels: needs:triage
