### ISSUE TITLE
[Bug] Youtube Extends Beyond screen

### ISSUE THREAD

**Issue by Bhooty** [mozilla-mobile/fenix#18106] opened 2021-02-21 21:55 UTC
My device is samsung note 8 
If i play youtube when my device is whqd+ 
For some reason video extends over the screen on landscape 
If i lower screen resolution to 1080p then the video stays within the screen border 
Hopefully u will look into it :)
![Screenshot_20210222-035239_Firefox](https://user-images.githubusercontent.com/46019727/108640049-c8204400-74c1-11eb-8699-157fd899d7d8.jpg)

**Comment by Dunexus** [comment] 2021-02-22 10:21
Duplicate of https://github.com/mozilla-mobile/fenix/issues/8252

**Comment by mcarare** [comment] 2021-02-22 15:24
@Bhooty Thank you for your report. This is being investigated under https://github.com/mozilla-mobile/fenix/issues/8252. Feel free to add comments and follow that discussion for updates.
Closing this as duplicate.

**Closed by mcarare** 2021-02-22 15:24 UTC
Labels: needs:triage, 🐞 bug
