### ISSUE TITLE
FNX-4992 ⁃ [Bug] Quick Action Sheet show/hide is erratic

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#1382] opened 2019-04-04 16:03 UTC
STR

* completely hide the Quick Actions Sheet by dragging it down
* Tab the Home icon to go to list of tabs
* Tap to go back to a tab
~~> the QAS is about one~~quarter visible, I can see its handle above the toolbar
-> the QAS handle then remains on screen even if the toolbar hides during scrolling
* now drag the QAS handle upwards, try touching just the uppermost part of its handle nearest the page content
-> sometimes the toolbar disappears downwards as the QAS expands upwards, sometimes not

-> Hiding the QAS toolbar with a quick flick often leaves its handle visible. More careful dragging hides it completely, its handle disappears.

-> the expanded QAS remains on screen even when the toolbar hides during scrolling.

-> the QAS remains visible indefinitely, perhaps it should auto hide after a time and/or when the toolbar auto hides during scrolling?

Galaxy S7
Today's Fenix Nightly

**Comment by vesta0** [comment] 2019-04-09 05:23
@shorlander can you please confirm if this is a bug or intended behaviour?

**Comment by vesta0** [comment] 2019-04-23 23:28
@mheubusch and @shorlander can we close this issue assuming it was taken into consideration in #1718 ?

**Comment by lime124** [comment] 2019-04-29 22:15
yes - that issue should sort out all the issues with QAB.

**Closed** 2020-08-11 11:32 UTC
Labels: needs:UX-feedback, 🐞 bug
