### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Tom-Loader** [mozilla-mobile/fenix#14606] opened 2020-09-02 07:40 UTC
## Steps to reproduce
Try to access about:config

### Expected behavior
low level warning should give advanced options to proceed and ignore.

### Actual behavior
The page says:

"Cannot Complete Request

Additional information about this problem or error is currently unavailable." 

No advanced options are present but the url has the correct content.

resource://android/assets/low_and_medium_risk_error_pages.html?&title=Cannot+Complete+Request&button=Try+Again&description=%3Cp%3EAdditional+information+about+this+problem+or+error+is+currently+unavailable.%3C%2Fp%3E&image=&showSSL=false&badCertAdvanced=Advanced%E2%80%A6&badCertTechInfo=%3Clabel%3ESomeone+could+be+trying+to+impersonate+the+site+and+you+should+not+continue.%3C%2Flabel%3E+%3Cbr%3E%3Cbr%3E+%3Clabel%3EWeb+sites+prove+their+identity+via+certificates.+Firefox+does+not+trust+%3Cb%3Eabout%3Aconfig%3C%2Fb%3E+because+its+certificate+issuer+is+unknown%2C+the+certificate+is+self-signed%2C+or+the+server+is+not+sending+the+correct+intermediate+certificates.%3C%2Flabel%3E&badCertGoBack=Go+Back+%28Recommended%29&badCertAcceptTemporary=Accept+the+Risk+and+Continue

### Device information
Samsung galaxy s10

80.1.2 (Build #2015761283)
AC: 54.0.5, 02934e437
GV: 80.0.1-20200827204751
AS: 61.0.10

**Comment by cadeyrn** [comment] 2020-09-02 07:42
Duplicate of #7865.

**Closed** 2020-09-02 17:21 UTC
Labels: needs:triage, 🐞 bug
