### ISSUE TITLE
browser stuck in infinite loop asking for location permission

### ISSUE THREAD

**Issue by sirwasi** [mozilla-mobile/fenix#14631] opened 2020-09-02 18:46 UTC
## Site with issue and any steps to reproduce
https://www.rotpunkt-apotheken.ch/wettbewerb/?utm_source=newsletter&utm_medium=email&utm_campaign=wettbewerb_2020_september

### Expected behavior
Browser shows site and asks once for permission to send my location

### Actual behavior
Browser asks reportedly for permission for site to access my location in an infinite loop from which I can not break out and ever manage to browse the actual content. The whole browser UI remains fully blocked in constant reloads (until close app).

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
Not possible (alert overlaps any controls)

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
No

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No

### Device information

* Android device: 10
* Fenix version: 79.0.5 (Build #2015758619)
AC: 48.0.15, 8755ac0cd
GV: 79.0.1-20200813192915
AS: 61.0.10

**Comment by clientenq** [comment] 2020-09-02 23:33
Can not reproduce.

**Comment by liuche** [comment] 2020-09-10 00:21
I can repro this - not sure if GeckoView should be throttling or Fenix.

**Comment by mcarare** [comment] 2020-09-15 09:23
I think this **might** be fixable in AC to not show the prompt if it is already shown, but on choosing an option to allow or block without checking option to remember decision could bring the prompt back again. And the app would still need to process all the permissions requests, and that could impact performance.
IMO it might be worth investigating fixing this in gecko view so that a website would not request a permission it already asked for and not received an answer yet. 
@liuche can you ping someone from GV that could look into this? Thank you!

**Comment by liuche** [comment] 2020-09-15 23:46
Thanks for investigating, @mcarare! I talked to @droeh from GV in the GV matrix channel - they would like the control to not be in GV, such as for "never notify me again".

jon linked me to some Prompts controls, is this something we could re-use? https://github.com/mozilla-mobile/android-components/blob/master/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/PromptAbuserDetector.kt
https://github.com/mozilla-mobile/android-components/blob/2264e52f07401c2676186199ae3ac1c8f608e654/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt#L358

or perhaps it's not being used for Location prompts?

**Comment by mcarare** [comment] 2020-09-16 06:25
AFAIK this is not used on permissions requests. And the requests are indeed consumed after you click once on allow or do not allow, the problem is that all the other dialogs remain opened. The fix would be in another place in AC, where we could check if we already shown the dialog for a type of request. This would also need to account for https://github.com/mozilla-mobile/fenix/issues/14637.
As a note: Any change will still result in Fenix receiving a bunch of requests and deciding to show them or not.

**Comment by bifleming** [comment] 2020-09-24 19:19
@liuche how to proceed?

**Comment by codrut-topliceanu** [comment] 2020-09-30 07:06
Fix for https://github.com/mozilla-mobile/fenix/issues/14637 will solve this issue.

**Comment by AndiAJ** [comment] 2020-11-03 08:04
Hi, **still reproducible** on the latest **`Nightly Build 201103`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201103-100116](https://user-images.githubusercontent.com/51314259/97961436-016e6000-1dbc-11eb-9201-8bf463d1ea97.gif)

**Comment by codrut-topliceanu** [comment] 2020-11-03 08:22
@AndiAJ I believe the fix will be available with AC 65. I apologise for not specifying this sooner :(

**Comment by codrut-topliceanu** [comment] 2020-11-03 15:26
The site in the original comment keeps sending permission requests to the user. 

Before the fix for #14637 this would create an infinite number of permission request dialogs to the user, and checking "Remember decision for this site" wouldn't have solved the issue. 

After the fix for #14637 only one dialog is displayed at once and checking "Remember decision for this site"  prevents the site for asking for that permission again.

I'm not entirely sure if there is any other way to improve on this as we'd have to keep another "unofficial" list of permission requests to not bombard the user with the same one over and over again, but how would we know if he hasn't just repeated the action. (i.e. pressed "share my location" again).

How should we proceed? @liuche ?

**Comment by Amejia481** [comment] 2020-11-05 14:53
> The site in the original comment keeps sending permission requests to the user.
> 
> Before the fix for #14637 this would create an infinite number of permission request dialogs to the user, and checking "Remember decision for this site" wouldn't have solved the issue.
> 
> After the fix for #14637 only one dialog is displayed at once and checking "Remember decision for this site" prevents the site for asking for that permission again.
> 
> I'm not entirely sure if there is any other way to improve on this as we'd have to keep another "unofficial" list of permission requests to not bombard the user with the same one over and over again, but how would we know if he hasn't just repeated the action. (i.e. pressed "share my location" again).
> 
> How should we proceed? @liuche ?

I think this is an issue for the website developer to fix, as the site is requesting the permission over an over again even thought the permission was granted/denied, the same issue is reproducible on [Firefox desktop](https://www.rotpunkt-apotheken.ch/wettbewerb/?utm_source=newsletter&utm_medium=email&utm_campaign=wettbewerb_2020_september). I think there is not much that we can do here, we can mark this a webcompat issue.

**Comment by Amejia481** [comment] 2020-11-05 15:11
Also we can contact the website developers and suggest that they test their site on Firefox.

**Comment by SoftVision-LorandJanos** [comment] 2021-12-10 14:47
Hi @sirwasi! Could you still reproduce this issue?
I tested on the latest builds, and it didn't asked for location permission on either of them.
Also checked on Chrome, with the same result.
Tested on:
- latest Release (95.1.0).
- latest Beta (96.0.0-beta1).
- latest Nightly 97.0a1 (2021-12-10).

Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by sirwasi** [comment] 2021-12-10 15:00
I cannot reproduce the issue anymore, tested on
    latest Release (95.1.0).
    latest Nightly 97.0a1 (2021-12-10).
on Xiaomi A3 (Android 11)

Seems to be fixed somehow, great!

**Comment by SoftVision-LorandJanos** [comment] 2021-12-10 15:04
Thank you! Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2021-12-10 15:04 UTC
Labels: 🐞 bug, Feature:SitePermissions, b:webcompat, b:web-content, S2
