### ISSUE TITLE
FNX3-15568 ⁃ [Bug] there is no consistent icon style

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1445] opened 2019-04-06 15:26 UTC
### Steps to reproduce
1. open settings

### Expected behavior
all icons have a consistent style

### Actual behavior
The icon for the "Give feedback" menu item looks out of place because it has a totally different stroke width than the other icons.

There are also other inconsistencies. For example the "Help" and the "About Fenix" icon - both have the circle around them and both looks different.

But the icon of the "Give feedback" menu item is the most striking example because it doesn't fit at all.

![Screenshot](https://user-images.githubusercontent.com/1100614/55671527-25408b80-5891-11e9-8e59-b05e9bb59bb5.png)UNITO-UNDERSCORE!20190406-151443!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision d43e902b4433348da285a2978918ccfefc389014

**Comment by Vv2233Bb** [comment] 2019-04-06 18:06
No, it's not a bug. Fenix is a mozzila project and uses mozzila's icon style. The icons are separated into two parts (mobile and desktop). Desktop has wider icons while mobile icons are slimmer but there is less of them. The icons you are talking about haven't been designed yet. They will probably update it in the future. They are awere of this and I hope it is enaugh to close this issue.

**Comment by cadeyrn** [comment] 2019-04-06 18:25
> No, it's not a bug.

It doesn't matter if we call it bug or not. It's only labeled as bug because I used the GitHub template "Bug" to report this issue and I used this template because the sections make sense for reporting such an issue.

> and I hope it is enaugh to close this issue.

Why do you **hope** that an issue get closed if it's not solved? 😳 This is an issues tracker. In issues trackers issues will be closed if they are resolved / tracked in another way / won't be fixed / another good reason. Maybe these are not the final icons and maybe it's already known to someone but I can't find any other ticket about this. If that's the case then someone from Mozilla will tell this. But your comment is not very constructive.

**Comment by Vv2233Bb** [comment] 2019-04-06 18:26
K. But make sure this isn't a dublicate

**Comment by nt1m** [comment] 2019-04-07 17:13
The cause is that Fenix is using a mixture of Desktop and Android style icons.

See: https://design.firefox.com/icons/viewer/#

The platform toggle is on the top-right.

**Comment by nt1m** [comment] 2019-04-07 17:31
FWIW, the mockups use different icons: https://mozilla.invisionapp.com/share/8ZQVRNUJW3H#/screens/350752852 that are more consistent

**Comment by cadeyrn** [comment] 2019-04-07 17:40
The invision link is password protected.
But good to know that there are already mockups with more consistent icons. :)

**Comment by nt1m** [comment] 2019-04-07 17:41
<img width="368" alt="image" src="https://user-images.githubusercontent.com/1795135/55687419-13341b00-596d-11e9-924c-03c8eec95823.png">

**Comment by ekager** [comment] 2019-04-09 02:54
I pulled some newer vector icons in from the design docs. Closing but let us know if you see any other icons out of place! Thanks!

**Comment by cadeyrn** [comment] 2019-04-09 16:12
It's much better now, thanks!

**Closed** 2020-08-11 08:40 UTC
Labels: 🐞 bug
