### ISSUE TITLE
Put the navigation buttons in the main UI for "large-enough display" devices

### ISSUE THREAD

**Issue by Pomax** [mozilla-mobile/fenix#14734] opened 2020-09-04 16:21 UTC
The new FF for Android removed tabs and navigation buttons for devices large enough to accommodate those (10" tablets, etc), and has made the user experience so horrible that at least personally I had to switch to Chrome. I hate Chrome, but the inability to switch tabs and quick-navigate without having to dive into menus is so frustrating that I can't keep using FF.

https://github.com/mozilla-mobile/fenix/issues/2344 is already open for restoring tabs, but there does not appear to be one for putting the navigational buttons back in the main UI if there is enough screen real-estate to do so, so please consider this a feature request parallel to https://github.com/mozilla-mobile/fenix/issues/2344 to also add the "back"/"forward"/"reload" buttons back into the main UI, with an option added to the custom settings to set "show nav buttons in the main UI: [never] [auto] [always]" or something similar that offers users those three choices.

**Comment by s-ankur** [comment] 2020-09-04 16:38
Duplicate of https://github.com/mozilla-mobile/fenix/issues/2344. Please check out that issue

**Comment by Pomax** [comment] 2020-09-04 16:44
definitely looks like a duplicate, but the the fact that it's been open for almost 4 months is worrisome. Is there a roadmap for issues so that folks can know when it's (probably) safe for them to switch back to FF on Android?

**Comment by Pomax** [comment] 2020-09-04 16:45
Also note that issue only asks for tabs, not also restoring the navigational UI, so it might make sense to morph this issue into the navigational elements only (if there isn't another bug for that. I couldn't find one with my search, but then github search can sometimes not surface what you'd expect)

**Comment by s-ankur** [comment] 2020-09-04 16:51
It's been added to the UX MVP Project https://github.com/mozilla-mobile/fenix/projects/2#card-21229607 . It means they consider it to be part of the minimum viable product so it has a considerable priority. The team is pretty small so the delay is understandable, at least to me. 

If you have some request not covered by the original issue, feel free to comment there or edit this issue to the specific request that you want to make

**Comment by Pomax** [comment] 2020-09-04 17:40
title and comment updated so as to be about the nav buttons, mentioning the already existing issue for tabs

**Comment by s-ankur** [comment] 2020-09-04 18:04
Sorry about misleading you, I thought that project was open. 

#4134 covers your remaining request I think.

**Comment by Pomax** [comment] 2020-09-04 19:40
Very strange: I see it mentioned in https://github.com/mozilla-mobile/fenix/issues/4498, but if I load that project board, I don't see that meta issue for tablet optimization in any of the tracks. In fact, searching that project for 44xx issues, the only issue that shows up is 4417, which is a very different issue indeed.

It still feels like this has somehow fallen off the roadmap.

**Comment by amedyne** [comment] 2020-12-10 19:51
Closing this ticket. Keeping #4498 open to be considered for future Fenix backlog.

**Closed by amedyne** 2020-12-10 19:51 UTC
Labels: Feature:Browsing, feature request 🌟

**Comment by Pomax** [comment] 2020-12-11 02:18
still salty that we had no choice in the matter and we were forced into a phone UI, so until this gets fixed, I'm going to keep using Chrome for a handful of things, and duckduckgo for everything else, as much as I loved Firefox. I'll happily switch back when it works like a normal browser on tablet again (which is the only device I use for media consumption)
