### ISSUE TITLE
The text of the button of messages is clipped at larger system font sizes

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/fenix#28495] opened 2023-01-11 11:57 UTC
**[Affected Versions]:**
- Firefox RC 109.1.0 (Build #2015926579), 7d00fc7f1+ AC: 109.1.0, 5294c37a47 GV: 109.0-20230109151414 AS: 96.1.3.
through
- Firefox Release 107.2.0 (Build #2015918523), 1490acda7+, AC: 107.0.8, e189e99662, GV: 107.0.1-20221128144904
- Firefox Release 102.2.1 (Build #2015891003), 10fdf130c+, AC: 102.0.14, cd19f9a6c5 GV: 102.0.1-20220705093820 AS: 93.1.0

**[Affected Platforms]:**
- Android 13 (Samsung Galaxy A52s)
- Android 9 (Samsung Galaxy S8)

**[Prerequisites]:**
- Have the font size of the device to a larger font (e.g. from Settings > Display > Font size and style).
- Have the device/app language set to French.

**[Steps to reproduce]:**
1. Open the app.
2. Go to the homepage.
3. Observe the button of the Default Browser Message.

**[Expected result]:**
- The text of the button is correctly displayed.

**[Actual result]:**
- The text of the button is clipped.

**[Notes]:**
- The issue is also reproducible for the ViewPoint Survey Message.
- The issue is reproducible for multiple languages.
- Attached are screenshots of the issue.

![Screenshot_20230114_111317_Firefox](https://user-images.githubusercontent.com/53752296/211777670-84cef6e5-4a9a-4d16-8fbe-3a74b4f6677f.jpg)
![Screenshot_20230110_162137_Firefox](https://user-images.githubusercontent.com/53752296/211777686-6ab37ba1-ecc3-48c7-9aaa-4c1268fd101c.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22264)

**Comment by heres-maria** [comment] 2023-01-16 08:26
The issue is also reproducible on Firefox Nightly 110.0a1 (Build #2015927787), 60818a23b+ AC: 110.0.20230115143320, 0bc72f1cc3 GV: 110.0a1-20230115094128 AS: 96.2.1.

**Comment by PrashantSaroj** [comment] 2023-01-16 16:18
I have opened similar issue for other UI components https://github.com/mozilla-mobile/fenix/issues/28551. I can fix this one too

**Comment by titooan** [comment] 2023-01-18 17:53
I think this bug is already being fixed there: https://github.com/mozilla-mobile/fenix/pull/28500 
(fix of https://github.com/mozilla-mobile/fenix/issues/28420, that seems to be of duplicate of this issue)

**Comment by cpeterso** [comment] 2023-01-27 06:21
> I think this bug is already being fixed there: #28500
> (fix of #28420, that seems to be of duplicate of this issue)

In that case, I will close this issue.

**Closed by cpeterso** 2023-01-27 06:21 UTC
Labels: 🐞 bug, needs:triage, S4
