### ISSUE TITLE
Page reload after battery saver pops up loses form data

### ISSUE THREAD

**Issue by vgabor** [mozilla-mobile/fenix#15101] opened 2020-09-15 01:50 UTC
When the battery saver schedule kicks off at the given percentage the Firefox window refreshes and loosing all changes in form text boxes which are being edited at that time, they reset to their original opening state. More than annoying when you spend half a hour to write/edit a forum post or other longer text and suddenly they lost.

**Comment by TrianguloY** [comment] 2020-09-15 08:31
Additional info: this can be easily replicated by setting the android developer setting 'background process limit: no background processes'. Then simply switching tabs, changing to another app and then back, or sometimes even turning the screen off triggers the reload.
This doesn't happens on either chrome or Firefox fennec.

Personally I think this is a big issue (S2 or even S1) because user data is being deleted.

**Comment by eliserichards** [comment] 2020-10-06 17:36
Possibly related to https://github.com/mozilla-mobile/fenix/issues/12731

**Comment by eliserichards** [comment] 2020-10-06 17:37
@st3fan to discuss further with the AC and GV teams 👍

**Comment by jonalmeida** [comment] 2020-10-06 21:35
Duplicate of https://github.com/mozilla-mobile/fenix/issues/5397.

**Comment by jonalmeida** [comment] 2020-10-26 18:37
Removing this off the AC bugs list since it's an app bug.

**Closed** 2021-05-01 21:30 UTC
Labels: Feature:Battery, Feature:Browsing, Feature:Forms, wontfix, 🐞 bug
