### ISSUE TITLE
[Bug]: Application crashes when tapping on the delete button for recently visited websites in History

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21519] opened 2021-09-27 14:17 UTC
### Steps to reproduce

1. Open a new tab in Firefox Nightly
2. Make a couple of consecutive searches on google
3. Open History from the 3-dot menu
4. Tap the "x" button on the Recently visited querry

### Expected behaviour

The application is stable at all times

### Actual behaviour

The application crashes

![243208389_541743663793280_4836312642544122859_n](https://user-images.githubusercontent.com/89511597/134924205-227f7f41-502f-46c8-8dea-460e31e93126.gif)

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

94.0.a1 2021-09-27

### Device logs

af1621ca-a5e6-476e-b7ab-136a554dab3d
java.util.NoSuchElementException: Collection is empty.
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=a7540a65893142aaba34af0b1805860f
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-2344b43c-bbe2-4435-be76-e28c80210927
----
java.util.NoSuchElementException: Collection is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:5)
	at org.mozilla.fenix.library.history.HistoryFragment.deleteHistoryItems(HistoryFragment.kt:17)
	at org.mozilla.fenix.library.history.HistoryFragment$onCreateView$historyController$4.invoke(HistoryFragment.kt:4)
	at org.mozilla.fenix.library.history.DefaultHistoryController.handleDeleteSome(HistoryController.kt:3)
	at org.mozilla.fenix.library.history.DefaultHistoryInteractor.onDeleteSome(HistoryInteractor.kt:1)
	at org.mozilla.fenix.search.SearchDialogFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:26)
	at android.view.View.performClick(View.java:7339)
	at android.view.View.performClickInternal(View.java:7305)
	at android.view.View.access$3200(View.java:846)
	at android.view.View$PerformClick.run(View.java:27787)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7078)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

### Additional information

Recently visited sites will not update if the individual searches are made in different tabs. Recently visited sites also show when using bing as a search engine but not if using wikipedia.

**Comment by GlitchWalker** [comment] 2021-09-30 12:50
I wanted to add, I'm getting the same error but it only happens when I try to delete a collection rather than any websites.

Also, I think this is related to not being able to see my whole history, but only 1-2 days. This happens intermittently, but a collection is *always* the last entry. (Included a screenshot of the end of my history)

From the looks of it, it seems as though this is linked to turning a search into a collection? 


![Screenshot_2021-09-30-13-48-46-654_org mozilla fenix](https://user-images.githubusercontent.com/26338453/135458130-275681a3-024a-4f12-a44d-37bbfc6cafe0.jpg)

**Comment by GlitchWalker** [comment] 2021-09-30 14:48
To add to my previous comment, here is the most recent crash data from settings>about>crashes

551a3086-7332-410a-8ca4-d8f311e23c00
java.util.NoSuchElementException: Collection is empty.
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=31b7989f20334f66a363870a5c1546d0
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-38829841-6344-47b2-8ff1-13a4e0210930
----
java.util.NoSuchElementException: Collection is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:5)
	at org.mozilla.fenix.library.history.HistoryFragment.deleteHistoryItems(HistoryFragment.kt:17)
	at org.mozilla.fenix.library.history.HistoryFragment$onCreateView$historyController$4.invoke(HistoryFragment.kt:4)
	at org.mozilla.fenix.library.history.DefaultHistoryController.handleDeleteSome(HistoryController.kt:3)
	at org.mozilla.fenix.library.history.DefaultHistoryInteractor.onDeleteSome(HistoryInteractor.kt:1)
	at org.mozilla.fenix.home.tips.ButtonTipViewHolder$$ExternalSyntheticLambda0.onClick(Unknown Source:22)
	at android.view.View.performClick(View.java:7509)
	at android.view.View.performClickInternal(View.java:7486)
	at android.view.View.access$3600(View.java:841)
	at android.view.View$PerformClick.run(View.java:28709)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by csadilek** [comment] 2021-09-30 18:05
Thanks for reporting, this is already being worked on and will be fixed when https://github.com/mozilla-mobile/fenix/pull/21603 lands.

**Comment by codrut-topliceanu** [comment] 2021-10-05 09:41
Unable to reproduce after https://github.com/mozilla-mobile/fenix/pull/21603 landed.

**Comment by LaurentiuApahideanSV** [comment] 2021-10-05 12:07
Verified as fixed on Firefox Preview Nightly 2021-10-05.

### Device used:
- Oppo Find X3 (Android 11)

**Closed by LaurentiuApahideanSV** 2021-10-05 12:07 UTC
Labels: 🐞 bug, b:crash, Feature:History, eng:qa:needed
