### ISSUE TITLE
[Bug] Open in app link on page doesn't work

### ISSUE THREAD

**Issue by snaggen** [mozilla-mobile/fenix#5186] opened 2019-09-10 08:34 UTC
I got a Microsoft Teams meeting link sent to me in Slack. When I click that link it opens a custom tab powered by Firefox Preview telling me to download teams or if I already have it "Open in app" (not sure exactly what it says in English since I have the Swedish text). However when I click on that link, nothing happens. 
To be able to join the meeting I have to open the Slack link in the webkit based pre-installed browser and then click the link... so I have a workaround but I would like to only use firefox. 

## Steps to reproduce
* Receive Microsoft Teams link and click it
* Click "Open in app"

### Expected behavior
Teams should be launched and meeting should be joined. 

### Actual behavior
Nothing happens when clicking the link.

### Device information

* Android device: OnePlus 6T running Lineageos 16.0
* Fenix version: 1.4.0 from google play store

**Comment by ekager** [comment] 2019-09-21 23:05
This used to work AFAIK. Does anyone know if we disabled this?

**Comment by jonalmeida** [comment] 2019-09-24 23:06
If this used to work before, and we didn't disable the feature (confirmed from product's side), we (a-c) should investigate what's happening there.

**Comment by rocketsroger** [comment] 2019-11-15 15:44
From investigation, when the user click on the `Open it` link on the Microsoft Teams, A-C is not seeing the `onLoadRequest` coming in to the `GeckoEngineSession`.  A GeckoView bug will be opened for this issue.

**Comment by rocketsroger** [comment] 2019-11-15 16:43
Bug opened for GV https://bugzilla.mozilla.org/show_bug.cgi?id=1596825

**Comment by rocketsroger** [comment] 2020-03-03 21:38
Confirmed this is fixed on latest master build.  The next nightly should have this fix.

**Comment by rocketsroger** [comment] 2020-03-03 21:39
@snaggen Can you please confirm this works on the next nightly release? Thanks,

**Comment by snaggen** [comment] 2020-03-04 10:27
Tested with current Nightly but that doesn't work, so I will try again tomorrow and see if it is included in that one.

**Comment by snaggen** [comment] 2020-03-04 19:40
Still no luck with 200304 18:00

**Comment by rocketsroger** [comment] 2020-03-09 14:43
> Still no luck with 200304 18:00

You're correct.  I can see the same issue.  I'll investigate.

**Comment by rocketsroger** [comment] 2020-03-10 13:44
Bug is reopened.  This will need a fix from GV. https://bugzilla.mozilla.org/show_bug.cgi?id=1596825

**Comment by rocketsroger** [comment] 2020-05-20 19:21
New GV API requires AC changes https://github.com/mozilla-mobile/android-components/issues/7047

**Comment by rocketsroger** [comment] 2020-05-26 19:16
Nightly with A-C version `43.0.20200526130035` will have the fix.  Please verify this is fixed.  Thanks,

**Comment by snaggen** [comment] 2020-05-27 07:32
I have verified that this works for me with for Teams links. So, this issue seems to be resolved.

**Comment by Diana-Rus** [comment] 2020-05-29 10:11
Hi, @snaggen  thank you for the confirmation, i've also did a check with a zoom link and a zoom app and it works as intended on my personal Android 9 device, EMUI 9.1.0, Huawei, on Nightly 5/29.
I'll remove the qa needed and close the ticket.

**Closed by Diana-Rus** 2020-05-29 10:11 UTC
Labels: P3, S2, eng:qa:needed, 🐞 bug
