### ISSUE TITLE
[Bug] History library lables items as being from "This month" when they're actually from last month

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#4455] opened 2019-08-01 17:05 UTC
## Steps to reproduce
1. Visit some pages near the beginning of last month (i.e. at the start of July).
2. Open the history library at the start of this month (i.e. in August).

### Expected behavior
Those pages are listed under the heading of "Last month" or "July", or alternatively simply "Last four weeks" if you don't want to deal with the moving split between "This month" and "Last month".
(Firefox/Fennec seems to [use](https://dxr.mozilla.org/mozilla-central/rev/b0124f06562982dce60b820d95aad23afd5cec90/mobile/android/base/java/org/mozilla/gecko/home/CombinedHistoryAdapter.java#29-40) Today, Yesterday, Last 7 days and then grouped by (calendar) month)

### Actual behavior
Those pages appear under the heading of "This month", even though today it's already August and those history entries are dating back from July.

### Device information

* Android device: Moto G4 Play, Android 6.0.1
* Fenix version: Nightly 190801 06:18 (build no. 12130632)

**Comment by ekager** [comment] 2019-08-01 17:51
This is working as intended as we do the splits by last 24 hours, last 7 days, last 30 days etc. So I think maybe we just need a string review here whether the header should read "Last month" or "Last 30 days"?

**Comment by lime124** [comment] 2019-08-01 21:33
@mheubusch please provide feedback and label "ready for eng" or close the issue as won't fix. thanks!

**Comment by mheubusch** [comment] 2019-08-01 22:48
If these are implemented as you note @ekager it is possible for all the labels to be wrong.  Ideally the rules would be Today =  range of T=0000 to T=2359 hours on a user's device clock; This week = All the days in the Sunday to Saturday calendar week of the user's device calendar; This month = All days in the calendar month of the user's device calendar; and Older=Any day in any month prior to the current month on the user's device calendar.

**Comment by mheubusch** [comment] 2019-08-01 22:50
@ekager the alternative is to change the labels to : Last 24 hours; Last 7 days; Last 30 days; Older - (don't see Older in the current XML file so may need to add that and the rule that says Older = anything that is prior to last 30 days. )

**Comment by kbrosnan** [comment] 2019-08-01 23:43
Much of the world believes the week runs from Monday to Sunday. Months are going to be similarly problematic, Hebrew, Chinese and Japanese calendars are common examples of non-Gregorian  calendars.

**Comment by ekager** [comment] 2019-08-01 23:57
Yeah let's do the second option :)

**Comment by mheubusch** [comment] 2019-08-02 15:44
Thanks, @ekager and thanks too @kbrosnan - it occurred to me that Sunday wasn't the start of many people's week as I wrote out the first option and I appreciate that you are helping us remove our biases and keep our content inclusive.

**Comment by abodea** [comment] 2019-08-14 11:41
Verified as fixed with the latest debug build(from master) using Samsung Galaxy s10+(Android 9).
The history library labels items were displayed in a correct order **`Last 24 hours; Last 7 days; Last 30 days; Older `.**

**Closed by abodea** 2019-08-14 11:41 UTC
Labels: eng:qa:verified
