### ISSUE TITLE
FNX-3454 ⁃ [Feature request] Autohide toolbar when it is set to bottom

### ISSUE THREAD

**Issue by yigorsm** [mozilla-mobile/fenix#10353] opened 2020-05-01 17:37 UTC
If in the settings you select the position of the toolbar at the top and scroll the page, the toolbar is hidden.
But if you select the toolbar below, then while scrolling the page, it remains visible.

I think, it would be great to make it auto-hide when it's bottom.

**Comment by cadeyrn** [comment] 2020-05-01 17:43
Duplicate of #8775.

**Comment by ekager** [comment] 2020-05-01 17:57
Closing for #8775

**Closed** 2020-08-11 00:31 UTC
Labels: Feature:Toolbar, feature request 🌟
