### ISSUE TITLE
[Bug] Cannot download referer/password protected file

### ISSUE THREAD

**Issue by myfreeweb** [mozilla-mobile/fenix#13792] opened 2020-08-13 11:24 UTC
## Steps to reproduce

- go to https://www.kapiba.ru/2017/11/mi-home.html
- find the link to https://ru.kapiba.ru/mihome/files/old/MiHome_5.8.2_63062_vevs.apk ("СКАЧАТЬ ВЕРСИЮ 5.8.2 *")
- click
- also try going to the link directly in a new tab and typing the http basic auth password (mentioned in the first link)

### Expected behavior

Should download. Works fine on desktop.

### Actual behavior

"Download failed"

### Device information

* Android device: OnePlus 7T
* Fenix version: Nightly 200812 06:01 (Build 2015757491)

**Comment by liuche** [comment] 2020-08-27 21:42
This might be a GV issue, so we'll timebox this to figure out what's going on and file a GV issue if necessary.

**Comment by liuche** [comment] 2020-09-08 21:01
will test on Gecko test browser

**Comment by LaurentiuApahideanSV** [comment] 2020-09-28 15:48
I can confirm the issue is reproducible on Firefox Preview Nightly 200928 (Build #2015766515).

### Device used:
- OnePlus 6T (Android 9)

**Comment by Amejia481** [comment] 2020-11-05 14:41
@myfreeweb we did some improvement to downloads in [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix). I was able to download the file there, would you mind trying on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) to see if it's fixed for you? Hopefully it will work for you too :)

I will also ask the QA team to test as they have a wide range of devices.

**Comment by myfreeweb** [comment] 2020-11-05 14:56
Yes, both referer and password do work now, thanks!

**Comment by Amejia481** [comment] 2020-11-05 15:00
Thanks @myfreeweb, lets wait for the QA team to verify as they have many devices :)

**Comment by AndiAJ** [comment] 2020-11-05 15:30
Hi , I've just checked this matter on the latest Nightly Build 201105 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

✔️ Managed to properly download the file from https://www.kapiba.ru/2017/11/mi-home.html (**`СКАЧАТЬ ВЕРСИЮ 5.8.38`**)
❓ Unfortunately , due to the fact that I don't have a valid password I can't download the password protected file from https://ru.kapiba.ru/mihome/files/old/MiHome_5.8.2_63062_vevs.apk

@Amejia481 - Please advise ☺️

**Comment by Amejia481** [comment] 2020-11-05 15:34
Thanks @AndiAJ, I think we can close the issue, as the initial issue was related to never been able to download :)

**Closed by Amejia481** 2020-11-05 15:34 UTC
Labels: E2, Feature:Download, eng:qa:needed, 🐞 bug
