### ISSUE TITLE
some emojis not rendering on firefox Android

### ISSUE THREAD

**Issue by vlebert** [mozilla-mobile/fenix#27497] opened 2022-10-21 19:43 UTC
Hi

Some emojis a not rendering properly on my website on firefox android while ther render properly on firefox-macos and chrome-android.

I don't even see a black square or anything, just nothing. Those emoji are 🛡  and 🗂 

Is it an issue of firefox-android?

Regards
Valerian

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21846)

**Comment by vlebert** [comment] 2022-10-21 19:45
For example here is a screenshot of this post
![Screenshot_20221021-214443](https://user-images.githubusercontent.com/49779177/197277020-c16a9578-47de-4be6-9ef1-7de26118b39e.png)

**Comment by fice-t** [comment] 2022-10-21 22:57
I can reproduce on the latest Firefox stable but not on the latest Firefox Nightly. This is likely due to the recent updating of some AndroidX dependencies.

Can you try the Firefox Nightly version from the Play Store to see if you can reproduce the issue on it?

**Comment by vlebert** [comment] 2022-10-22 05:44
Hi

Thanks for the answer. It does look ok on nihhtly :)

**Comment by kbrosnan** [comment] 2022-10-22 19:53
Working on Nightly. Closing

**Closed by kbrosnan** 2022-10-22 19:53 UTC
Labels: needs:triage
