### ISSUE TITLE
FNX-12519 ⁃ Add option to always display navigation bar

### ISSUE THREAD

**Issue by gaul** [mozilla-mobile/fenix#11567] opened 2020-06-14 09:43 UTC
### What is the user problem or growth opportunity you want to see solved?
Fenix auto-hides the navigation bar to give small devices more page real estate.  To close a page, the user must scroll back up to show the toolbar.

### How do you know that this problem exists today? Why is this important?
Firefox on larger devices, e.g., laptops, always shows the toolbar.  Some users want this functionality on mobile.

### Who will benefit from it?
Users with larger devices, e.g., tablets.

Other ideas:

* Show the toolbar when reaching the bottom of the page
* Auto-display toolbar on larger devices

**Comment by cadeyrn** [comment] 2020-06-14 10:59
Duplicate of #8801.

**Comment by gaul** [comment] 2020-06-14 12:06
Thanks for the pointer @cadeyrn!

**Closed** 2020-08-11 04:21 UTC
Labels: needs:triage
