### ISSUE TITLE
Position the current tab at centre of screen when opening tab tray

### ISSUE THREAD

**Issue by Sum1Random** [mozilla-mobile/fenix#12069] opened 2020-06-28 10:05 UTC
The current tab should (optionally?) appear in the centre of the screen (vertically) in the list of tabs when the tab tray is opened. 

This would make it easier to access tabs both immediately before and after (below and above) the current tab without having to scroll. 

Currently, opening the new Tab Tray puts the Current Tab at the top of the list. This makes scrolling a requirement to access any later tabs. 
The "open link in new tab" function adds the new tab above the current tab in the tab tray, causing it to be hidden when the tab tray is opened.

**Comment by Dunexus** [comment] 2020-06-28 18:09
Is this a regression of this feature https://github.com/mozilla-mobile/fenix/issues/10496 ?

**Comment by kbrosnan** [comment] 2020-06-28 18:30
They are likely using 5.2 which has tabs tray but some known bugs that are fixed on Nightly. Closing as a duplicate of #10496

**Comment by Sum1Random** [comment] 2020-06-29 00:49
@kbrosnan using 200628. This doesn't seem to be a bug, unless the current tab is not supposed to be located at the top of the screen when the tab tray is opened? 


I'm requesting that, upon opening the tab tray, the current tab be [able to be] placed in the centre of the screen - so the tabs both immediately _above and below_  are displayed, rather than just current and below tabs being displayed. 

Example: 
1. Have many tabs open, e.g. 20 tabs.
2. Open a tab in the middle of your tabs, e.g. 10th tab as the current tab.
3. [optional] Use "open link in new tab" on one or more links. 
4. Open the tab tray. 
- The current (10th) tab is at the top of the screen. 
- The new and above tabs (11th,12th) are hidden above (off-screen), you need to scroll to see them. 


Visually:
- Currently tabs [10],9,8,7,6 are displayed, and are off-screen - scroll to get to 11+ or 5-.
- Asking for tabs 12,11,[10],9,8 to be displayed when the tab tray is opened, scroll to get to 13+ or 7-.


Does this make more sense?

**Comment by Dunexus** [comment] 2020-06-30 07:07
Having current tab centered allow to see tabs opened from current tab (via Open link in new tab) which are located above current tab without having to scroll

**Comment by s-ankur** [comment] 2020-08-02 09:24
Hi this is still an issue in the latest nightly

**Comment by cousteaulecommandant** [comment] 2020-09-05 09:23
At the very least, it should NOT appear at the very end of the screen; otherwise it looks like it's the last open tab, which is very confusing.
I suggest implementing something similar to what older versions did with the search engine button ribbon: if the list overflows on either side, try to display only half a tab on that side, to visually reflect the fact that the list continues.
(This is in addition to the idea of showing the tab in the middle of the screen, which I agree is very convenient for showing previous tabs or newly opened tabs.)

**Closed** 2021-06-22 23:02 UTC
Labels: Feature:Tabs, wontfix, 🐞 bug
