### ISSUE TITLE
FNX-491 ⁃ [Bug] Text selection toolbar disappears while switching screen orientation

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2023] opened 2019-04-25 09:16 UTC
## Steps to reproduce
1. Select some text on a website. Leave the text selection toolbar displayed.
1. Turn the device to landscape (or from landscape to portrait).
    1. Expected behavior
Text selection toolbar is still displayed.
    1. Actual behavior
Toolbar disappears. The text is still selected.
    1. Device information

* Android device: Pixel
* Fenix version: 4/24

**Comment by colintheshots** [comment] 2019-06-05 21:42
@vesta0 I cannot reproduce this with the current STR. I can only reproduce the bug by minimizing and restoring the app.

**Comment by vesta0** [comment] 2019-06-06 17:48
@cpeterso is there a GV bug for this? Thanks :)

**Comment by cpeterso** [comment] 2019-06-13 07:59
I filed GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1559073

I can reproduce the same bug in Fennec. When I follow the STR in Chrome, both the text selection and toolbar disappear. So the GV should either:
* restore the toolbar for the selected text
* or follow Chrome's example and deselect the selected text.

**Comment by cpeterso** [comment] 2019-06-13 21:46
@vesta0 - Is this a feature or a bug? 🤷‍♂

Fenix and Fennec have different behavior than Chrome, but the same as iOS, where dismissing the text toolbar while keeping the text selected is considered an accidental feature (by users who want to take screenshots of highlighted text without toolbars).

**Comment by vesta0** [comment] 2019-06-14 15:40
@cpeterso the currect behaviour in Fenix is that the text remains selected when changing screen orientation and the toolbar disappears, but then if you scroll the toolbar reappears. It would be worth investigating why toolbar disappears in the first place. 

This is low priority.

**Comment by cpeterso** [comment] 2019-06-14 17:36
> the currect behaviour in Fenix is that the text remains selected when changing screen orientation and the toolbar disappears

btw, neither I nor Colin ([above](https://github.com/mozilla-mobile/fenix/issues/2023#issuecomment-499266405)) can reproduce this behavior when changing screen orientation. We can only reproduce after switching apps and then back to Fenix.

**Comment by eliserichards** [comment] 2020-05-05 20:26
Closing as it is no longer reproducible

**Closed** 2020-08-11 13:40 UTC
Labels: Feature:TextSelection, P3, b:landscape, needs:gv, 🐞 bug, 🙅 waiting
