### ISSUE TITLE
Reorder Tabs --- Allow User to Change Tab Order

### ISSUE THREAD

**Issue by gamepad-coder** [mozilla-mobile/fenix#14127] opened 2020-08-24 20:36 UTC
### What is the user problem or growth opportunity you want to see solved?

Add back in support for changing the order of tabs on Firefox for Android before the public release of the beta -> into the stable branch.

### Why?

Users can reorder tabs in Firefox on Desktop.
It is a core feature, and expected behavior for a web browser.

Users can reorder tabs in Firefox on Android, 
both in the tab bar and in the tab view grid.

Currently: 

Users may not reorder tabs in Firefox Beta for Anroid
nor may users reorder tabs in Firefox Nightly for Android.

The user should still have the ability to change the order of tabs 
/aka reorganize their tabs /aka "move" their tabs.

<hr>

### Clarification

This issue is not about reordering collections.
This issue is not about reordering the tabs within collections.

This issue refers to the tabs list you see when you click on the tabs button (square around the number of tabs open). 

<img width="540" alt="Screenshot_2020-08-24-14-35-46 - Copy" src="https://user-images.githubusercontent.com/65138515/91089733-9cf38f80-e619-11ea-96ec-77661a7e7b8c.png">

<hr>

### Demonstration 

Current Firefox behavior : 
1. When user attempts to Longpress on a tab, <br>then drag up or down before releasing.
2. When user attempts to Longpress+Drag <br>an already selected tab in the tabs list.

![github fenix ffn notabMvIssue_v2_reducedSize](https://user-images.githubusercontent.com/65138515/91092455-ab43aa80-e61d-11ea-8380-b160ccf09513.gif)

<hr>

### Who will benefit from it?

Use cases : 
-  Users who keep many tabs open, <br>and wish to organize current tab list (without closing).
-  Users who want to keep certain tabs at the top or bottom.
-  Users who just like playing with user interfaces.
-  Everyone who uses more than 1 tab.

### UX Design Throught-process Recommendation :

When adding in awesome, incredible features (such as Collections, seriously thanks again to all who brought them back), keep in mind the core features of the underlying software. Think about it in the context of the User's life, and the most common spectrum of User workflows and routine habits. Think about the common traits between your old and new software and other similar software. Then compare these similarities and differences and distill the core usability features. The intersections where the User has interchangeable habits which are applied regardless of context, in all the apps. Muscle memory & routes for autopilot to incorporate a routine across different platforms and different browsers. (The User's "browsing style", if that makes more sense.) And be aware that (even if the neat new features are totally awesome) the User will expect the underlying core features to be accessible, even if the controls or interface change. 

Posting this because I got a notification that the new Firefox is about to be pushed on Android, and really hoping someone will make the effort to add this in time.

**Comment by hwinnemoe** [comment] 2020-08-24 20:38
Duplicate of #2487

**Comment by ekager** [comment] 2020-08-24 20:38
closing for #2487

**Closed by ekager** 2020-08-24 20:38 UTC
Labels: needs:triage

**Comment by gamepad-coder** [comment] 2020-08-24 21:27
Whoops, missed that one in the search results. Sorry for the trouble, and thanks.
