### ISSUE TITLE
Option to disable QR scanner

### ISSUE THREAD

**Issue by Lewzke** [mozilla-mobile/fenix#24470] opened 2022-03-26 17:56 UTC
Dear Developers,
would be a great feature to disable the QR scanner above the keyboard. Not everyone uses it, **less is more**.
### Who will benefit from it?
People who use Google Lens or 3rd party QR scanner apps, people with small phones (more space for content)

Thank you for the effort!

**Comment by cadeyrn** [comment] 2022-03-26 21:36
Duplicate of #14150.

**Comment by Lewzke** [comment] 2022-03-26 21:54
Suggestion: The disable option fits right into the "Search" settings -> QR Scanner (enable/disable)

**Comment by Lewzke** [comment] 2022-03-26 22:03
> Customizable user interface is a Firefox trademark for ages. Suggestion: The disable option fits right into the "Search" settings -> QR Scanner (enable/disable)
> 
> Look at a small resolution modern phone (Unihertz Atom L Android 11), the bar is using lot o

Customizable user interface is a Firefox trademark for ages.
Suggestion: The disable option fits right into the "Search" settings -> QR Scanner (enable/disable)

Look at a small resolution modern phone (Unihertz Atom L Android 11), the bar is using lot of space from usable space. It is like an additional search bar for no reason, just for this QR button.
![2022-03-26 22 55 12](https://user-images.githubusercontent.com/40172594/160258481-63e235b8-62f3-448c-8fca-e175a9d2c83b.png)

**Comment by Lewzke** [comment] 2022-03-26 22:04
> Duplicate of #14150.
Sorry for duplicate, but that thread is very old, I am not the only user who is bothered whith this. 
Customizable user interface is a Firefox trademark for ages.
Suggestion: The disable option fits right into the "Search" settings -> QR Scanner (enable/disable)

Look at a small resolution modern phone (Unihertz Atom L Android 11), the bar is using lot of space from usable space. It is like an additional search bar for no reason, just for this QR button.
![2022-03-26 22 55 12](https://user-images.githubusercontent.com/40172594/160258497-bbba0973-70ed-4833-96d1-6439dcb1da1d.png)

**Comment by cadeyrn** [comment] 2022-03-26 22:48
> Sorry for duplicate, but that thread is very old, I am not the only user who is bothered whith this.

It doesn't make a difference whether the issue is one week, one month or one year old. Further discussion should happen in #14150.

**Closed** 2022-03-27 17:50 UTC
Labels: needs:triage
