### ISSUE TITLE
[Bug]: CSS property dvh has reversed effect

### ISSUE THREAD

**Issue by SirRhynus** [mozilla-mobile/fenix#25680] opened 2022-06-19 12:32 UTC
### Steps to reproduce

1. Have the option "Scroll to hide toolbar" enabled
2. Have a webpage with style `body { height: 100dvh; }` and an element for example h3 with style `h3 { bottom: 0; }`
3. Scroll down to have hide the toolbar

Here is an example page
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DVH reversed</title>
    <style>
        body {
            position: relative;
            height: 100dvh;
            overflow-y: hidden;
        }
        
        h3 {
            position: absolute;
            bottom: 0.5em;
            left: 6rem;
        }
    </style>
</head>
<body>
    <h1>Is dvh reversed?</h1>
    <ol>
        <!-- An ordered list as a ruler -->
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ol>
    <h3>Now, is it?</h3>
</body>
</html>
```

### Expected behaviour

The element at the bottom, eg. `<h3>Now, is it?</h3>`, should be at the bottom of the page and stay there as the toolbar vanishes, i.e. move down with the toolbar's height. See "**dynamic viewport**" in [https://www.w3.org/TR/css-values-4/#viewport-variants](https://www.w3.org/TR/css-values-4/#viewport-variants).

### Actual behaviour

The element is hidden under the bottom if the toolbar is visible and moves up with twice the toolbar's height as the toolbar vanishes.

### Device name

Moto e(7i) power

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

101.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20750)

**Comment by kbrosnan** [comment] 2022-06-21 20:01
The testcase is not scrollable due to the `overflow-y: hidden`.

On [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) the text is displayed at the bottom. With `overflow-y: auto` the text stays in the first place it was displayed.

**Comment by dholbert** [comment] 2022-06-29 18:08
Aha! Correcting myself... I can't reproduce the issue **in Firefox Nightly**.

But I can reproduce it (with both testcases!) in Firefox release!

@emilio suggests that this was likely https://bugzilla.mozilla.org/show_bug.cgi?id=1774224 which will be fixed in Firefox 102.

**Comment by kbrosnan** [comment] 2022-06-29 18:09
v102 is in the process of being released to users. It should hit 100% rollout later this week. Closing as a duplicate.

**Closed by kbrosnan** 2022-06-29 18:09 UTC
Labels: 🐞 bug, needs:triage

**Comment by SirRhynus** [comment] 2022-06-29 19:17
The `overflow-y: hidden` is intentional since it still allows me to "scroll" to hide the toolbar.
A video of the behavior for me can be found [here on my Google Drive](https://drive.google.com/file/d/1pGLbWBpu0oVGuv5xVMKO9PHX0vuhKDOc/view?usp=sharing).
The bug report that @emilio suggests seems to be of the same bug yes. So thanks you all that the fix is on it's way. And sorry if I wasn't that helpful from the start cause I was a bit busy.

**Comment by dholbert** [comment] 2022-06-30 17:37
> The `overflow-y: hidden` is intentional since it still allows me to "scroll" to hide the toolbar.

That's very odd; I can't scroll to hide the toolbar with [your original testcase](https://dholbert.org/tests/fenix-25680-dvh-1.html).  The toolbar is just always-present for me on that one, and scrolling has no effect (using Firefox release version, just like you).  But I do see that happening in your video.  *shrug* I wonder what's going on there.

> The bug report that @emilio suggests seems to be of the same bug yes. So thanks you all that the fix is on it's way.

Hooray! Thanks for taking the time to report the bug, in any case.
