### ISSUE TITLE
FNX-12161 ⁃ [Bug]Tab Tray: The "More options" overlay menu is misplaced when rotating the device in landscape mode

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#11262] opened 2020-06-05 12:55 UTC
## Steps to reproduce
1. Launch Fenix.
1. Access the tab tray and select the PB mode.
1. In portrait mode, tap on the 3 dot menu in order to open the `More optionsn` overlay menu.
1. Rotate the device in landscape mode.
    1. Expected behavior
The `More options` overlay menu is displayed correctly in the right position.
    1. Actual behavior
The "More options" overlay menu is misplaced when rotating the device in landscape mode
    1. Device information

* Android device: **Samsung Galaxy S7 (7).**
* Fenix version: **Nightly 6/5.**

![20200605-154807](https://user-images.githubusercontent.com/42831109/83878477-e7651e80-a744-11ea-89ee-b3dfbbdfb0d2.gif)

**Comment by AndiAJ** [comment] 2020-06-05 13:00
Dupe of #11261

**Closed** 2020-08-11 03:34 UTC
Labels: Feature:Tabs, S2, 🐞 bug
