### ISSUE TITLE
Telemetry for Custom tabs

### ISSUE THREAD

**Issue by bifleming** [mozilla-mobile/fenix#977] opened 2019-03-12 22:33 UTC
Similar to Custom Tabs events in Focus: https://github.com/mozilla-mobile/focus-android/blob/master/docs/Telemetry.md#custom-tabs

As a product owner, I want to track the usage of "find in page" in Fenix so that I can understand how our users leverage the feature, and detect anomalies or issues in user flow and usage.

#### Hypothesis
We believe this feature is useful to users, and successful when
- % of users coming into Fenix via custom tabs increases

#### What questions will you answer with this data?
- If the feature is usable and useful, how often to people come into Fenix via Custom tabs rather than other entry points. It'll help us to add and improve functionality

#### Probes
- see here: https://github.com/mozilla-mobile/focus-android/blob/master/docs/Telemetry.md#custom-tabs
- also make sure to track this as a way of intent/coming into the app

### Dependencies (Added by PM and Eng)
- Glean SDK (Event ping)

### Acceptance Criteria (Added by PM)
- Event pings can be queried via re:dash
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
- NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by sblatz** [comment] 2019-04-08 16:18
These events all take place inside of an android component, which will make it trickier to handle telemetry, I believe.

**Comment by sblatz** [comment] 2019-04-10 20:42
@bbinto, @vesta0 are we sure that the linked telemetry events are correct?

@pocmo brings up [a good point](https://github.com/mozilla-mobile/android-components/pull/2676#discussion_r273487204)--a custom tab is not part of the normal tab view, thus it doesn't matter which one is 'selected' or which tab # it is, right?

**Comment by bbinto** [comment] 2019-04-11 12:29
> @bbinto, @vesta0 are we sure that the linked telemetry events are correct?
Could you elaborate please what you event is in question?

The events listed for Focus are
- Custom tab opened
- "Close" button clicked 
- "Action" button clicked
- Custom menu item selected

@sblatz - all I want to do here is to know/track when a user opens a link (from a different app) in Fenix by using the apps custom tabs implementation. The app, e.g LinkedIn can decide how to present the Chrome of Fenix. For Focus we were able to also keep track of these events, 

The probe will help us to understand how many people come in from other apps via custom tabs and/or the regular intents.

Here two screenshots, one from the LinkedIn app (custom tab) vs. opened the link via the SMS app (not custom tab, opens link in default browser = Fenix)

**Comment by sblatz** [comment] 2019-04-17 14:35
I'm updating the sizing of this as it actually required me to implement "fact emitting" on the a-c side and observe those in Fenix.

**Comment by abodea** [comment] 2019-06-04 12:23
Hello, I'm still reproducing this issue for:
* "Action" button clicked (if share button available, when that's clicked)
* Custom menu item selected (open the Fenix menu, where it says powered by Fenix). 
Mentioned in the [comments ](https://github.com/mozilla-mobile/fenix/issues/977#issuecomment-482094173)above.
Tested on the latest **`Fenix version from 6/4 with Samsung Galaxy Note 9(android 8.1.0)`**.
## Please note the following: 
* [Custom tab opened](https://prnt.sc/nxfj5v) ping was sent no issues. works ✅ [app_opened_logcat](https://github.com/mozilla-mobile/fenix/files/3252221/app_opened_logcat.txt)
* ["Close" button clicked](http://prntscr.com/nxg0m1) when I closed it from gmail and (x button in the [LinkedIn example](http://prntscr.com/nxg1jn)) works ✅  [app_closed_logcat](https://github.com/mozilla-mobile/fenix/files/3252223/app_closed_logcat.txt)

* "Action" button clicked - no matter how many times I tried the ping was not sent and I received this `I/glean/GleanDebugActivity: Setting debug config Configuration(serverEndpoint=https://incoming.telemetry.mozilla.org, userAgent=Glean/0.55.0 (Android), connectionTimeout=10000, readTimeout=30000, maxEvents=500, logPings=true, httpClient=mozilla.components.lib.fetch.httpurlconnection.HttpURLConnectionClient@4c07826, pingTag=ab-test-001vv, channel=release) 
D/glean/PingMaker: Collecting events
D/glean/Glean: No content for ping 'PingType(name=events, includeClientId=true).name', therefore no ping queued.
2019-06-04 14:47:41.296 4833-4982/? D/ViewRootImpl@323e8ed[fenix]: dispatchAttachedToWindow` Doesn't work ❌[app_share_logcat](https://github.com/mozilla-mobile/fenix/files/3252222/app_share_logcat.txt)
* Custom menu item selected (open the Fenix menu, where it says powered by Fenix) - I tried to open the custom menu from Gmail, LinkedIn(custom tabs) and the ping wasn't sent I think is the same issue as above from **`Custom tab opened.`** Doesn't work ❌ [app_custom_menu_item_selected_logcat.txt](https://github.com/mozilla-mobile/fenix/files/3252220/app_custom_menu_item_selected_logcat.txt)

I will remove the QA Needed based on my comment until the issue will be fixed.

**Comment by sblatz** [comment] 2019-06-04 16:41
Did a bit of investigation. It looks like the custom tab facts are not firing properly from android components. 

This means that [these pairings](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt#L249) never happen and our telemetry won't send.

**Comment by sblatz** [comment] 2019-06-04 17:31
@abodea what app were you using to test the "action button"? Was it a share button or something else?

**Comment by sblatz** [comment] 2019-06-04 17:41
I've opened a PR in a-c that will handle the share case: https://github.com/mozilla-mobile/android-components/pull/3249

**Comment by sblatz** [comment] 2019-06-04 20:40
I synced up with @abodea who mentioned these steps:

>I opened a custom tab from linkedin:
Open Gmail
Tap on the linkedin link -> custom tab opened -> A share button is available.

Based on this, the a-c PR I opened **should** fix the problem!

**Comment by abodea** [comment] 2019-06-11 10:18
Verified as fixed on the latest build from `6/11` with Samsung Galaxy Note 9(Android 8.1.).
Please note that the remaining 2 `Action` button and `Custom menu item` are now properly displayed on the logs and glean dashboard. The events displayed without problems.
<details>
    <summary>CUSTOM_TAB</summary>
   ### And here is the CUSTOM_TAB:
{
      "events": [
        {
          "timestamp": 0,
          "category": "events",
          "name": "app_opened",
          "extra": {
            "source": "CUSTOM_TAB" } },
        { "timestamp": 911,
          "category": "custom_tab",
          "name": "menu"
        },
{
          "timestamp": 16884,
          "category": "custom_tab",
          "name": "closed"
        }
</details>
<details>
    <summary>Action_Button</summary>
   ### And here is the Action Button:
 {
      "events": [
        {
          "timestamp": 0,
          "category": "events",
          "name": "app_opened",
          "extra": {
            "source": "CUSTOM_TAB"
          }
        },
        {
          "timestamp": 46128,
          "category": "custom_tab",
          "name": "action_button"
        }
      ],
</details>

![download (12)](https://user-images.githubusercontent.com/42831109/59264229-56e82100-8c4b-11e9-8eea-fdcbda2a9ffd.png)

![download (11)](https://user-images.githubusercontent.com/42831109/59264236-5bacd500-8c4b-11e9-808e-9879bb687bb0.png)

**Closed by abodea** 2019-06-11 10:18 UTC
Labels: Feature:CustomTabs, Feature:Telemetry, MVP Blocker, QA needed
