### ISSUE TITLE
Sync search engines across devices

### ISSUE THREAD

**Issue by lle-git** [mozilla-mobile/fenix#15608] opened 2020-10-01 21:26 UTC
It would be useful to be able to sync search engines across devices (firefox for desktop included).

- Custom search engines would be concerned (not only the built-in search engines like google, ebay, bing, ...)
- Keywords for search engines would be concerned (when they are available, see #15609 )

Thanks

**Comment by kbrosnan** [comment] 2020-10-07 17:11
Closing as a dupe of https://github.com/mozilla/application-services/issues/1645

**Closed by kbrosnan** 2020-10-07 17:11 UTC
Labels: needs:triage
