### ISSUE TITLE
[Bug]: Reports of lost tabs in latest nightly

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#20649] opened 2021-08-03 16:52 UTC
### Steps to reproduce

See https://www.reddit.com/r/firefox/comments/ox0rqb/my_mobile_tabs_gone/

>Gave me a small list of random 'inactive' tabs (9 or so? What determines inactive? Some were from months ago, some were from yesterday) to restore from, which was further noted to be set for deletion in 30 days.
>
>Checked my settings, and nope -- didn't accidentally set close tabs from 'Manually' to a pre-determined time frame that are all of the other options. Extremely ticked off by this undocumented change, or is it a bug?
>
>Seems to be no way to restore the lost tabs either.

### Expected behaviour

Tabs aren't closed.

### Actual behaviour

Tabs are closed.

### Android version

Placeholder

### Firefox release type

Firefox Nightly

### Firefox version

Nightly

**Comment by ericonr** [comment] 2021-08-03 18:53
Duplicate of #20629

**Comment by csadilek** [comment] 2021-08-03 22:09
Thanks, we'll track in https://github.com/mozilla-mobile/fenix/issues/20650 for the immediate fix and #20629 for the discussion.

**Closed by csadilek** 2021-08-03 22:09 UTC
Labels: needs:triage, 🐞 bug
