### ISSUE TITLE
Clear site specific cookies and data

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17158] opened 2020-12-21 05:15 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

There is no option to clear site specific cookies or data.. This option is present in desktop version. Hoping it could be implemented in mobile version too

### How do you know that this problem exists today? Why is this important?
Currently there is no option to clear site specific cookies and data... For example let's see I want to login to a site using the different account,  in desktop we can clear all stored cookies and data which will also remove the session and sigin cookies and allowing me to login as if I have logged in freshly... Currently in mobile version you have to logout and login again.. Some sites do detect this as a fraudulent activity or user having multiple accounts.. 

### Who will benefit from it?
Users who like to have site specific controls

**Comment by rbrito** [comment] 2021-01-28 18:08
I miss this feature so, so much that the way that I'm doing things is to open private tabs when I want to use the tabs, despite the fact that I really want the sites to appear on my history (say, I don't have it bookmarked, and typing on a mobile device is painful), but I honestly don't want data under the site control to be stored on my device after I visit it.

Ideally, besides this feature, I would absolutely love to have https://github.com/Cookie-AutoDelete/Cookie-AutoDelete supported, since it is a way to discard tracking stuff from sites that one happens to visit...

**Comment by cadeyrn** [comment] 2021-01-28 19:12
Duplicate of #9294.

**Comment by t-matsuu** [comment] 2021-01-29 00:23
@cadeyrn
Interesting.
Is #9294 discuss "Manage Cookies and Site Data" in "about:preferences#privacy" in desktop?

**Comment by cadeyrn** [comment] 2021-01-29 15:15
>  Is #9294 discuss "Manage Cookies and Site Data" in "about:preferences#privacy" in desktop?

All issues in this issue tracker are about Firefox for Android. Some screenshots from the Desktop Firefox were used for comparison.

**Comment by t-matsuu** [comment] 2021-01-30 11:57
My comment means #9294 includes implementing the function like "Manage Cookies and Site Data" in "about:preferences#privacy" in desktop or not.
I want to view and manage all site data stored in my Fenix in one window, like "Manage Cookies and Site Data" in "about:preferences#privacy" on the desktop.

**Comment by clientenq** [comment] 2021-02-18 13:34
Users have needs to control who processes their personal data. This includes providing control to adjust and delete cookies specific sites use to follow user behaviour or personal preferences. Since sites do still not always follow privacy laws and regulations Fenix should provide these controls to users, like we did in the past. Since dropping relevant addons and removing features also removed providing control over cookies, users are again in need for this specifice control over their personal data via cookies. By not providing such controls firefox is denying all users to have sufficient control over their personal data, keeping firefox less privacy friendly.

**Comment by kbrosnan** [comment] 2021-05-04 21:27
Agree this is a duplicate of #9294

**Closed by kbrosnan** 2021-05-04 21:27 UTC
Labels: feature request 🌟
