### ISSUE TITLE
FNX-4723 ⁃ [meta] Sessions

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#102] opened 2018-12-04 21:05 UTC
* Session is a chronically concept of multiple tabs
* Session is created as soon as user starts new tab(s)
* Session will wrap up/saved after x minutes in background and when Fenix is closed
* Sessions can be 
  * sent/shared
  * deleted
  * opened

**Comment by vesta0** [comment] 2018-12-07 19:21
Duplicate of #111

**Closed** 2020-08-10 19:37 UTC
