### ISSUE TITLE
GleanInternalAPI.registerPingType$glean_release can block startup for a few seconds

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#13254] opened 2020-08-04 13:06 UTC
## Steps to reproduce
- Start fenix (I had no open tabs, no other apps running in the background)

### Expected behavior
Fenix starts up quickly. 

### Actual behavior
Sometimes, fenix takes some seconds to render the home screen. 
![Screen-Recording-20200804-132911](https://user-images.githubusercontent.com/44171190/89296597-d5c7c680-d662-11ea-94c6-d6ce390f726c.gif)

Profile from the slow case: https://share.firefox.dev/2DjNtoH
Fast profile: https://share.firefox.dev/3ftPMmn
Looks like this is somehow telemetry related, and in fact after turning it off the issue is gone, even after turning it on again.

### Device information

* Android device: Samsung Galaxy A50
* Fenix version: Nightly 200802 06:16 (Build #22150627)
AC: 53.0.20200801130512, c6137485e
GV: 81.0a1-20200730093956
AS: 61.0.10

**Comment by mcomella** [comment] 2020-08-04 15:51
Thanks for attaching a profile! It looks like `GleanInternalAPI.registerPingType$glean_release()` is taking a long time.
![image](https://user-images.githubusercontent.com/759372/89315447-b2375880-d62f-11ea-9d44-052cfbd97855.png)

@Dexterp37 Do you happen to know what might be causing this issue?

**Comment by mcomella** [comment] 2020-08-04 15:55
Today I think I learned what `<clint> is :) : I think `GleanMetrics.Pings.<clint>()` refers to initializing the class, which I think occurs because of the import statement: `import org.mozilla.fenix.GleanMetrics.Pings`

**Comment by Dexterp37** [comment] 2020-08-05 07:45
> 
> 
> Thanks for attaching a profile! It looks like `GleanInternalAPI.registerPingType$glean_release()` is taking a long time.
> ![image](https://user-images.githubusercontent.com/759372/89315447-b2375880-d62f-11ea-9d44-052cfbd97855.png)
> 
> @Dexterp37 Do you happen to know what might be causing this issue?

Mh, that's interesting. First of all, thanks for sharing this with us @miDeb (and @mcomella for flagging me!).

I suspect of two things, right now:

1. the `registerPingType` is probably the first call to the native libraries, so that implies we're loading the libglean_ffi.so at that point (unfortunately there's nothing we could do to make that faster), and we might want to approach this differently;
2. `registerPingType` is synchronous for different reasons. If Glean was already initialized at that point (which would exclude the (1) above) , and Fenix was already attempting to record some metrics, calling `registerPingType` is probably waiting for other measurements to be registered.

I filed [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1657292) to track this on our end.

**Comment by miDeb** [comment] 2020-08-05 09:37
@mcomella not sure if this was a typo, but fyi it's `<clinit>` not `<clint>` ;-)

**Comment by badboy** [comment] 2020-08-06 09:58
We have a [potential fix](https://github.com/mozilla/glean/pull/1132) that moves ping registration off the main thread (under the assumption that indeed it's loading the library and/or blocking on getting access to the internal mutex).

However that has some implications internally which I need to verify before I can land this.
I also wanted to try this out in Fenix.
However I'm unable to even reproduce the issue here.
I tried both profiling with [remote debugging](https://profiler.firefox.com/docs/#/./guide-remote-profiling?id=startup-profiling-fenix) as well as the Android Studio profiler, but neither give me a profile I can work with (with remote debugging I don't see _any_ Java calls, with the Android Studio profiler I can't find the part below `StartupHomeActivityLifecycleObserver` as in above profile).

@mcomella Any chance you could help me out here?
I could give you builds of a new Fenix APK to run with or we pair to go through a profiling session once?
(Due to how Glean is released it's a bit complicated to automate test builds at the moment, and we don't have proper staging releases yet either)

**Comment by mcomella** [comment] 2020-08-07 23:25
> (with remote debugging I don't see _any_ Java calls,

Perhaps you need to enable the Java main thread track? It's off by default sometimes.

![image](https://user-images.githubusercontent.com/759372/89695537-2e989880-d8c9-11ea-9a09-93f91a356b41.png)

That being said, my profiler on my P2 doesn't start early enough to capture `HomeActivity.onCreate` where this happens – perhaps the profile would start earlier if I used a lower-end phone?

@miDeb Did you do anything special to capture the profiler that early during the startup sequence?

> with the Android Studio profiler I can't find the part below `StartupHomeActivityLifecycleObserver` as in above profile).

I'm guessing the method is running quickly such that the sampling rate is too high to see the calls below it. You can:
- run on a lower-end device
- change to tracing mode, rather than sampling, which will impact the results of the profile but should capture all methods called.

> @mcomella Any chance you could help me out here?

I hope the tips above help! Otherwise, I'll try to be on at 8:30am PT on Monday. If we don't have enough overlap time (I have meetings at 9am), if you send me a build, I can try to get results for Tuesday.

**Comment by miDeb** [comment] 2020-08-08 07:38
> @miDeb Did you do anything special to capture the profiler that early during the startup sequence?

No, I just followed the instructions on https://profiler.firefox.com/docs/#/./guide-remote-profiling?id=startup-profiling-fenix (using `com.mozilla.fenix` instead of `com.mozilla.fenix.nightly`)

**Comment by badboy** [comment] 2020-09-15 11:06
We landed a fix to Glean, which was pulled in yesterday. Latest the next produced nightly should have this fix.
Unfortunately we weren't able to reproduce a similar profile, so it's hard to say if we really fixed the underlying issue.
If you encounter the problem again let us know. Until then I consider this fixed.

**Closed by badboy** 2020-09-15 11:06 UTC
Labels: eng:performance

**Comment by mcomella** [comment] 2020-09-15 16:03
@miDeb We've made a speculative fix: please let us know if you're still able to reproduce this!

**Comment by miDeb** [comment] 2020-09-15 16:05
As I've written in the first comment, I wasn't able to reproduce this anymore after turning telemetry off.
