### ISSUE TITLE
Fenix homescreen inefficiently loads content below the fold before content above it

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21555] opened 2021-09-28 23:44 UTC
## Steps to reproduce
- Open a page to create "Jump back in" section
- Bookmark a page to create "Recently saved section"
- From a web page, click the Home button in the toolbar to return to page

### Expected behavior
Either:
1. to minimize CPU/power use, layout occurs in one pass and displays all content above the fold
2. to optimize perceived performance, we generally follow ^ but some content may be loaded asynchronously causing additional layouts

### Actual behavior
We perform 1) multiple layout events and 2) layout content above the fold: **this overall takes longer, uses extra CPU/power to do redundant work, and causes jank (such as https://github.com/mozilla-mobile/fenix/issues/21550).**

See the video demonstration (I recommend going frame-by-frame):

https://user-images.githubusercontent.com/759372/135178605-c6d607f5-6054-43b8-973d-694707b51c4a.mp4

We layout the content in this order:
1. "Collections" (which is bottom-most)
2. "Recently Bookmarked" (second bottom-most)
3. "Jump back in", which is the only one displayed on screen

Here's a profile that demonstrates the behavior: https://share.firefox.dev/3ASpF3R There are 6 total layout events that take 423ms total. I hypothesize if we get this into one layout pass, it'd take slightly longer than our longest individual layout pass – 140ms – but this is very hand-wavy. **We could get a more accurate estimate by removing the sections besides top sites & collections and seeing how long it takes.** I would have done this but I ran out of time.

### Device information

* Android device: Moto G5
* Fenix version: Nightly 2021-09-27

**Comment by MarcLeclair** [comment] 2021-10-06 19:35
A patch fixed this, not sure which one but it landed last week ( I can't reproduce this) but created another issue. So I'll close this for now and open a new one for the new issue.

**Closed by MarcLeclair** 2021-10-06 19:35 UTC
Labels: eng:performance, needs:triage
