### ISSUE TITLE
FNX-4389 ⁃ [Bug] Video pauses as soon as user uses tab switcher

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10567] opened 2020-05-11 16:21 UTC
## Steps to reproduce
1. Open a tab like https://www.youtube.com/watch?v=989-7xsRLR4
1. Play video
1. Tap tab switcher (either tab tray or classic)

### Expected behavior
Video continues to play.

Chrome and Fennec do this correctly. 

### Actual behavior
Video is paused. 

### Device information
* Android device: Moto G
* Fenix version: latest nightly

**Comment by cadeyrn** [comment] 2020-05-11 18:09
Duplicate of #7238, #5527 and probably more.

tl;dr: It's not a Fenix bug. YouTube uses the Page Visibility API to stop the video once you switch the tab. That's why https://addons.mozilla.org/de/android/addon/video-background-play-fix/ exists (but not yet for Fenix).

> Chrome and Fennec do this correctly.

Nope. Both Chrome and Fennec stops the video once the user switches the tab.

**Comment by yoasif** [comment] 2020-05-11 18:31
@cadeyrn I haven't switched to a tab - I tested both Fennec and Chrome before filing. See my STR.

**Comment by ekager** [comment] 2020-05-12 04:32
You'll see the same effect if you pause Fenix while a video from YouTube is playing (not in fullscreen mode). YouTube does not want any background play, that includes detecting when you go to the tab switcher. Closing as dupe of #7238 and #5527.

**Comment by yoasif** [comment] 2020-05-13 01:40
@ekager Why does YouTube not detect when a Chrome user is using its tab switcher? Or Fennec? 

The problem here isn't that YouTube is detecting that it is in the background, it is that Fenix is backgrounding the tab before it is in the background, unlike Fennec and Chrome.

**Closed** 2020-08-11 01:02 UTC
Labels: Feature:Media, 🐞 bug
