### ISSUE TITLE
[Bug] Videos are marked as unavailable with EME enabled

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#13445] opened 2020-08-10 09:07 UTC
## Steps to reproduce
1. Open app and go to https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;panel=ALL_CONTENT;build=uncompiled .
2. Set the DRM drop down to have "Widevine DRM".
3. View the available videos.
### Expected behavior
- Notification is displayed.
- Video can be played.
### Actual behavior
- No notification is displayed.
- Video can't be played.
### Device information

* Android device: Samsung Galaxy S9 (Android 8), Google Pixel 3XL (Android 9)
* Fenix version: Nightly 8/10 GV: 81.0a1-202008060333456
* GV build: 81.0a1, build ID: 20200804022706

Note:
1. Default options on Nightly:
         - media.eme.enabled is set to true
         - media.eme.require-app-approval is set to true
2. On the geckoview_example.apk taken from bugzilla issue [1656289](https://bugzilla.mozilla.org/show_bug.cgi?id=1656289#c3) the notification is present and working (the notification can be cancelled or allowed depending on the chosen choice)
3. The same actual result is present for Clear Key
4. On the following site: https://bitmovin.com/demos/drm , the notification is not present and the video can be played, It shouldn't be playable as the notification is not present and therefore there was no allowing done. This works correctly on the GV build ID: 20200804022706.
5. Issue is for feature #1175

**Please check GIF**
![20200810-113927](https://user-images.githubusercontent.com/49859863/89766965-acdf7f80-db01-11ea-8480-1ab58f07e9da.gif)

**Comment by LaurentiuApahideanSV** [comment] 2020-12-18 13:25
The issue is fixed in Firefox 85.0.0-beta.2.
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)

**Comment by amedyne** [comment] 2021-01-08 13:11
Closing this as per comment above.

**Closed by amedyne** 2021-01-08 13:11 UTC
Labels: Feature:Media, Feature:Notifications, S1, 🐞 bug
