### ISSUE TITLE
[Bug] Your rights option is missing from Settings

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3375] opened 2019-06-12 08:42 UTC
## Steps to reproduce
Go to Settings to the bottom of the menu and observe.

### Expected behavior
The last option from the menu should be Your rights.

### Actual behavior
Your rights option is missing.

### Device information
* Android device: Motorola Nexus 6 (Android 7.1.1), Huawei P9 Lite (Android 6), OnePlus 5T (Android 9)
* Fenix version: 1.0.1924 (#11630619)

![Screenshot](https://user-images.githubusercontent.com/40694158/59336181-bbb48180-8d06-11e9-9b52-e178e297c7c3.png)UNITO-UNDERSCORE!20190612-113328!

**Comment by neekless** [comment] 2019-06-13 09:12
Seems to be intended. See https://github.com/mozilla-mobile/fenix/issues/3278 and https://github.com/mozilla-mobile/fenix/commit/811fbfc5fdbaf29a253f66146ca8ef4a69e5baa4.

**Comment by sblatz** [comment] 2019-06-14 15:56
Closing as @neekless pointed out this is expected behavior.

**Closed** 2020-08-26 23:24 UTC
Labels: P1, 🐞 bug
