### ISSUE TITLE
FNX-12355 ⁃ [Bug] Tabs Tray remains open when access through widget

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#11422] opened 2020-06-10 13:20 UTC
## Prerequisites:
* Have widget of the app on the device's homescreen.
    1. Steps to reproduce

1. Open tabs tray.
1. Put app in background.
1. Tap on the widget.
    1. Expected behavior
Normal browsing search mode is triggered.
    1. Actual behavior
Tabs tray remains opened.
    1. Device information

* Android device: Samsung Galaxy S9 (Android 8), Google pixel 3 XL (Android 9)
* Fenix version: Beta 5.2.0-beta.1 and Nightly 6/10

Note:

* After tapping on device's back button, the tabs tray will be closed.

**GIF-Samsung Galaxy S9 (Android 8)**
![20200610-161408](https://user-images.githubusercontent.com/49859863/84272228-d007a600-ab35-11ea-88df-b5046bdb4f69.gif)

**Comment by darkwing** [comment] 2020-06-22 16:14
@boek Would this be fixed by your patch from last week?

**Comment by kbrosnan** [comment] 2020-06-22 17:15
This looks fixed. Cannot reproduce using any part of the search bar or the voice Icon.

**Comment by AndiAJ** [comment] 2020-06-23 06:28
Hi, **verified as fixed** on the latest **`Nightly Build 200623 from 6/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200623-092530](https://user-images.githubusercontent.com/51314259/85368367-cddd1880-b533-11ea-80c6-d3b58a507901.gif)

**Closed** 2020-08-11 04:01 UTC
Labels: Feature:Tabs, S2, Skittle, eng:qa:verified, 🐞 bug
