### ISSUE TITLE
[Bug] After pressing on "Accept the Risk and Continue" in the notification "Secure Connection Failed", Firefox for Android marks untrusted by any reason HTTPS site connection as secure (Bugzilla 1714582)

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/fenix#19799] opened 2021-06-03 15:22 UTC
## Steps to reproduce
1. Open any untrusted site with HTTPS connection using Firefox for Android (for example, https://badssl.com/ and choose any "dangerous" link)
2. Skip notification "Secure Connection Failed" by tapping on "Accept the Risk and Continue"
3. Look at the security icon and status

### Expected behavior
Firefox for Android defines connection as unsecure even with security exception, like desktop Firefox

### Actual behavior
Firefox for Android defines connection and site's certificate as fully secure and misleads the user

### Device information

* Device vendor / model and Android version: Samsung Galaxy A20s (ARM64) with Android 10, Samsung Galaxy J2 Prime (ARMv7) with Android 6.0.1
* Firefox for Android version: 89.1.1, 90.0.0-beta.6, Nightly 2021-07-03T17:04:26.908
### Screenshots
![20210603_173638](https://user-images.githubusercontent.com/85299944/120668525-37c9a600-c497-11eb-80ea-6329561158ad.jpg)
![20210603_173603](https://user-images.githubusercontent.com/85299944/120668570-43b56800-c497-11eb-90ca-c9bb6321e127.jpg)
![20210603_173532](https://user-images.githubusercontent.com/85299944/120668608-4a43df80-c497-11eb-957e-652f42e3695e.jpg)
![20210603_173430](https://user-images.githubusercontent.com/85299944/120668648-52038400-c497-11eb-84e0-22635391801f.jpg)
(for Samsung Galaxy A20s)

<img src = https://user-images.githubusercontent.com/85299944/120669107-d1915300-c497-11eb-92f0-2c02189a59d6.png width = 45%> <img src = https://user-images.githubusercontent.com/85299944/120669124-d9e98e00-c497-11eb-9626-b99cd65b1408.png width = 45%>
<img src = https://user-images.githubusercontent.com/85299944/120669181-e5d55000-c497-11eb-9b49-54f749570320.png width = 45%> <img src = https://user-images.githubusercontent.com/85299944/120669517-3351bd00-c498-11eb-9a42-859d851bfccf.png width = 45%>
(for Samsung Galaxy J2 Prime)

## Video
https://user-images.githubusercontent.com/85299944/120673075-87aa6c00-c49b-11eb-9367-89233e267de8.mp4

**Comment by Nickoriginal** [comment] 2021-06-04 12:25
Same issue for Focus: [https://github.com/mozilla-mobile/focus-android/issues/4921](url)

**Comment by Mugurell** [comment] 2021-06-04 13:59
Thank you for the report!
This seems to be a GeckoView issue, moving the ticket to Bugzilla.
Please follow the progress there.

**Comment by Mugurell** [comment] 2021-06-04 14:00
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1714582

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Nickoriginal** [comment] 2021-06-04 14:06
It means that the same issue for Firefox Focus can be closed too?

**Comment by Mugurell** [comment] 2021-06-04 14:16
Duplicating the ticket to Bugzilla closes these automatically but I'll reopen this (and keep the Focus one open also) just to know that it's still an issue and have it verified by QA later.

**Comment by LaurentiuApahideanSV** [comment] 2021-06-10 15:46
I can confirm the issues is reproducible on Firefox Preview Nightly 6/10. @Mugurell Do you want to keep this issue open or should we closed in favor of the Bugzilla ticket?
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)

**Comment by Mugurell** [comment] 2021-06-10 16:24
I think its useful to have this open until the issue is fixed, to continue tracking it on Fenix also, prevent duplicates and be able to verify it on Fenix after the Bugzilla ticket is closed.

**Comment by Nickoriginal** [comment] 2021-07-28 12:15
[Bugzilla 1714582](https://bugzilla.mozilla.org/show_bug.cgi?id=1714582) was fixed by pushing a [commit](https://hg.mozilla.org/mozilla-central/rev/bdd3b02b105a) by @dblohm7. Waiting for a fresh Nightly today to verify it as fixed for Fenix.

**Comment by Nickoriginal** [comment] 2021-09-30 18:10
Resolved in the Firefox 93.1.0.
<img src = https://user-images.githubusercontent.com/85299944/135508406-b539e894-e9b6-4bad-83e2-f4f8feb7d8bd.jpg width = 35%>

**Comment by Nickoriginal** [comment] 2021-09-30 18:18
@Mugurell, you can verify that it is a proper fix, as you mentioned before?
> just to know that it's still an issue and have it verified by QA later.

I closed it too early without making sure it was actually resolved for all configurations.

**Comment by LaurentiuApahideanSV** [comment] 2021-10-04 08:58
Verified as fixed on Firefox Preview Nightly 2021-10-04.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Closed by LaurentiuApahideanSV** 2021-10-04 08:58 UTC
Labels: 🐞 bug, eng:qa:needed, Feature:Browsing, needs:triage, qa-triaged
