### ISSUE TITLE
[Bug] url insert button in the awesome bar search results sometimes inserts the title of the webpage instead of the url

### ISSUE THREAD

**Issue by kawaiiDango** [mozilla-mobile/fenix#14874] opened 2020-09-09 05:49 UTC
## Steps to reproduce
Search a bookmark or history item from the awesome bar. Press the ↖️ button
Sometimes the title of the webpage gets inserted. This doesn't happen every time.
![Screenshot_20200909-111006](https://user-images.githubusercontent.com/1066519/92559281-e5ec4a80-f28d-11ea-922b-5e9ed783f83d.jpg)

### Expected behavior
The URL of the page should get inserted
### Device information

* Android device: Oneplus 6, Android 10
* Fenix version: Nightly 200908 06:01 (Build #2015762675)
AC: 58.0.20200906130403, b6c304b2a
GV: 82.0a1-20200902095359
AS: 61.0.13

**Comment by umerf52** [comment] 2020-09-09 10:09
Duplicate of #13768.

**Comment by mcarare** [comment] 2020-09-09 10:38
@kawaiiDango Thank you for your report! Closing as duplicate of #13768.

**Closed by mcarare** 2020-09-09 10:38 UTC
Labels: needs:triage, 🐞 bug
