### ISSUE TITLE
[Bug] Buggy behaviour on homescreen when expanding/collasping collections

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3004] opened 2019-05-30 16:56 UTC
1. Open 3 new tabs
1. Tap on the expand arrow in a collection 

Expected: 
When expanded, collections list should scroll up to show length of list

Current:
Jumps back up to the top of the screen.

1. With collections now expanded, scroll up to show full list of collections (7 items)
1. Tap on collapse arrow

Expected
Opened tabs are shown not cut off.

Actual:
Opened tabs are shown cut off

See video for reference:
https://cl.ly/5f74470db7d1

Swiping to delete a tab from collections also causes collections view to be cut off

See video for reference:
https://cl.ly/79d0b4470d00

**Comment by mheubusch** [comment] 2019-05-31 19:51
The way collection cards expand is relative to the number of tabs in  a collection. It is designed to show as much of what is in a collection as  possible/expand to  fill  the viewport. So, if there is only 1 tab in  a collection, the collection card will shift up a bit to display that tab, and if the user is also displaying Open tabs on the homescreen, some of them will also be displayed. If there are 10 tabs in a collection, the collection card will shift up to sit 12 pixels (padding) below the hairline search bar to take over the viewport and overflow will fall below the viewport and can be accessed by scrolling.  Please see spec that @AmyYLee will add here.

**Comment by AmyYLee** [comment] 2019-06-03 22:10
@mheubusch Here is the animation for expanding/collapsing collections - The rule is that if the contents of the collection when expanded fits within the view port then the collection doesn't need to scroll up. If the position of the collection when expanded gets cut off at the bottom on expanding, the collection scrolls up to show as much of the collection as possible while still having the top of the collection card visible (see screenshot). Please let me know if there are additional questions

![Screenshot_20190603-175820(1)](https://user-images.githubusercontent.com/5992746/58837842-bc745600-862a-11e9-94fe-bb6ec874b7cb.png)

Video of animation for reference
[Colletions Expand-Condense.zip](https://github.com/mozilla-mobile/fenix/files/3249621/Colletions.Expand-Condense.zip)

**Comment by AmyYLee** [comment] 2019-06-06 17:18
Hi, 
I had mocked up an animation that smooths out the transition between expanding and collapsing a collection. Let me know if this should be filed in a new bug. @ekager @vesta0 

Expanding/Collapsing collection animation
https://cl.ly/092f42ee8781

Slow-motion version
https://cl.ly/88cf8fd7dd7a

**Comment by sblatz** [comment] 2019-06-06 17:31
This animation will be **very** difficult to implement. Currently each tab is added as a "new item" in the RecyclerView. This has several benefits, one of which is that we get the swipe to delete behavior for free that we've already implemented. As far as I'm aware, we would have to get rid of this functionality in order to implement this animation. 

We *could* implement some animation probably (right now it's just adding the items without smoothly transitioning), but I don't think this one is possible as it would have to extend a single item

**Comment by vesta0** [comment] 2019-06-06 17:50
@sblatz is there an MVP solution you'd recommend? If so please open a new issue to track that and we can move this item to post-mvp to further investigate.

**Comment by sblatz** [comment] 2019-06-06 20:08
@vesta0 I filed https://github.com/mozilla-mobile/fenix/issues/3229

**Comment by vesta0** [comment] 2019-06-06 21:28
Thank you @sblatz :)

**Comment by sblatz** [comment] 2019-07-16 19:31
@mozilla-mobile/ux Can we please consider this as part of the collections redesign?

**Comment by shorlander** [comment] 2019-07-16 19:40
> @mozilla-mobile/ux Can we please consider this as part of the collections redesign?

Yes! 👍🏻

**Comment by mheubusch** [comment] 2019-07-18 17:16
Assigning to Nicole - @lime124 Collections is in progress - do you need to move it from Waiting?

**Comment by lime124** [comment] 2019-07-25 04:09
collecting all these related issues for ux to take a look at together. removing needs ux label.

**Comment by topotropic** [comment] 2019-08-13 12:25
I think some of the initially described issues about cutting of things got resolved by removing the home screen animation (search bar snaps back into place). What's left here is Amy's proposed design https://github.com/mozilla-mobile/fenix/issues/3004#issuecomment-499587662 
@sblatz did anything change here about your initial assessment?

**Comment by sblatz** [comment] 2019-08-14 19:41
@topotropic Expanding the collections open smoothly is still going to be difficult for us to handle. 
Here is the current behavior:
![behavior 2019-08-14 12_40_12](https://user-images.githubusercontent.com/4400286/63050779-b4d5f680-be90-11e9-95b5-bb655802950f.gif)

**Comment by raphraph** [comment] 2019-08-28 08:49
@sblatz This current behaviour is why I came here to give feedback as a testing user.
Not being a developer I don't know how hard is it (or not) to implement this, but as a user I know how frustrating it is to open a collection and not seeing right away the collection content (as showed in the above gif you posted).

Since (at least for now, I don't know what is planned) it is not possible to reorganize either collections between them, or tabs inside a collection, the user can do nothing to improve his user experience. And frustration is not good for user experience ;)

Firefox Preview is already very nice to use though, so thanks to everyone working on it.

**Comment by sv-ohorvath** [comment] 2019-12-05 13:38
There are still issues with the animation/scrolling on expand/collapse/removing tabs:
noticed on Nexus 5(Android 6.0.1) and Xiaomi MiPad (Android 5.1.1). Not reproducing on a Pixel 3 (Android 10).
![20191205_153352](https://user-images.githubusercontent.com/4037709/70239990-0e7e6b80-1775-11ea-9508-19d3795e07f3.gif)

**Comment by ebalazs-sv** [comment] 2020-03-31 12:57
This is reproducible on Fenix Nightly 200331 GV 76, 3/31 with Nexus 5 (Android 6.0.1) followingthe steps:
1. Create a collection with 3 tabs;
2. Tap the arrow to expand the collection;

The page jumps back up to the top of the screen, the pages from the collection are visible after scrolling the page back down.

[Video ](https://drive.google.com/file/d/1YDLfAgU9HN9c1X-kbKr2UZa8XJzYYCD7/view)

**Comment by softvision-miralobontiu** [comment] 2020-04-14 13:35
Still reproducing the jumping behavior to the top of the screen when expanding/collapsing the collections on Beta 4.3.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Closed** 2021-07-12 20:39 UTC
Labels: Feature:Collections, eng:ux-debt, implementation review, wontfix, 🐞 bug, 🙅 waiting
