### ISSUE TITLE
Displaying web pages on full screen (including title bar)

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6078] opened 2019-10-17 09:24 UTC
### Why/User Benefit/User Problem
Currently Firefox is always displaying Android top title bar (with icons and clock) and URL bar on bottom.

Mobile devices many times don't have big screens and it would be good to use it.

### What/Requirements
Mobile Chrome implemented hiding URL bar when user starts scrolling page, I propose to implement this + additionally give option in Settings for hiding title bar (also in the same situation when user starts scrolling page).

### Acceptance Criteria (how do I know when I’m done?)
Page can be displayed on the whole/full screen.

**Comment by cadeyrn** [comment] 2019-10-17 09:37
Duplicate of #4383.

**Comment by marcinwiacek** [comment] 2019-10-17 09:40
Not exactly duplicate - I ask also for optional hiding Android title bar.

**Comment by hakkikaancaliskan** [comment] 2019-10-17 16:34
You mean hiding status bar and nav bar of Android?

**Comment by NotWoods** [comment] 2019-10-17 16:47
Duplicate of #4383 (hide URL bar) and #1984 (hide system bars)

**Closed by NotWoods** 2019-10-17 16:47 UTC
Labels: 🌟 feature request
