### ISSUE TITLE
[Bug] New tab button covers close tab button

### ISSUE THREAD

**Issue by yaakovfeldman** [mozilla-mobile/fenix#19934] opened 2021-06-10 07:41 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Open enough tabs to fill screen in tab list
2. Attempt to close last tab

### Expected behavior

Tab close button is accessible

### Actual behavior

Tab close button is obscured by new tab button.

![Screenshot_20210610-082946_Firefox Nightly](https://user-images.githubusercontent.com/17687145/121484890-8ca17b00-c9c7-11eb-9701-51aed3a08254.jpg)

I just noticed this today but it actually replaces a previous bug (that I didn't report) that has been around for months, where the 'tab closed' notification with the undo button similarly would obscure the last tab and its close button.  As can be seen in the picture below, the tab closed notification is now high enough not to obscure the buttons anymore.

![Screenshot_20210610-083037_Firefox Nightly](https://user-images.githubusercontent.com/17687145/121484887-8b704e00-c9c7-11eb-91cb-72cd625973dd.jpg)

### Device information

* Device vendor / model and Android version: Samsung S10 Android 11
* Firefox for Android version: Nightly 91.0a1 (Build #2015815371)

**Comment by lobontiumira** [comment] 2021-06-10 12:25
I confirm the issue, when the tabs are in list view, on the Google Pixel (Android 10), on the 6/10 Nightly build.
* Not reproducible on tablet Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by amedyne** [comment] 2021-06-10 12:33
@topotropic Thoughts on this?

**Comment by codrut-topliceanu** [comment] 2021-06-10 12:51
Hey. Sorry bout that. The issue is caused by https://github.com/mozilla-mobile/fenix/pull/19891 I merged the PR too soon. It will be fixed when https://github.com/mozilla-mobile/fenix/pull/19812 lands.

**Comment by Mugurell** [comment] 2021-06-10 12:53
> @topotropic Thoughts on this?

This will be resolved by allowing the last tab to be scrolled to above the fab so the close button for even the last tab will be easily accessible.

**Comment by codrut-topliceanu** [comment] 2021-06-15 07:40
https://github.com/mozilla-mobile/fenix/pull/19812 landed.

![image](https://user-images.githubusercontent.com/60002907/122012535-f786f380-cdc5-11eb-841b-589129462743.png)

![image](https://user-images.githubusercontent.com/60002907/122012585-01a8f200-cdc6-11eb-97ac-d0f9854162c0.png)

If this look is acceptable I recommend closing this issue.

**Comment by amedyne** [comment] 2021-06-15 11:55
Looks good to me. @topotropic what do you think?

**Comment by topotropic** [comment] 2021-06-15 13:25
Looks good, thanks!

**Comment by SoftVision-LorandJanos** [comment] 2021-06-18 10:27
Verified as fixed on the latest Nightly (91.0a1 - Friday 6/18 @ 5:07 AM).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Closed by SoftVision-LorandJanos** 2021-06-18 10:27 UTC
Labels: Feature:Tabs, qa-triaged, 🐞 bug
