### ISSUE TITLE
[Bug] A drop-down prompt in focus will automatically be opened on opening the tab

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12943] opened 2020-07-25 19:17 UTC
## Steps to reproduce
In this tab, use GitHub search (from menu in top left corner) to search for something (eg "var"). 
Click on language and dismiss the popup
Switch to some other tab and then switch back

### Expected behavior
Nothing

### Actual behavior
A popup opens up asking you the language. This behaviour is the same even AFTER you go to any other website in the tab.

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by s-ankur** [comment] 2020-07-25 19:26
![GifMaker_lowquality1](https://user-images.githubusercontent.com/33252312/88464740-cf0ab800-ceda-11ea-85dc-50c17a585cb4.gif)

**Comment by ekager** [comment] 2020-07-27 17:44
Also related: a prompt already dismissed will reopen when the page is reopened https://github.com/mozilla-mobile/fenix/issues/12146

**Comment by Diana-Rus** [comment] 2020-08-05 08:52
Hi, issue is partially fixed on latest Nightly 8/4 with Google Pixel 3 XL (Android 9) and Samsung Galaxy S9 (Android 8).
- issue is not encountered with STR from description ✔️
- issue is not encountered when reloading the page ✔️
- issue not encountered when putting the app in background and then bring it to foreground ✔️
- issue is still encountered in case you put the app in background, return to foreground and navigate between the tabs through the sliding option❌
<details closed><summary>Gif with issue</summary>

![20200805-115022](https://user-images.githubusercontent.com/49859863/89392155-d2d7df00-d711-11ea-91c5-038fa516655e.gif)
<details>

Testing sites: https://aaplesarkar.mahaonline.gov.in/en, github.com, daleharvey.github.io/testapp

**I'll remove the label qa-needed until further information is provided.**

**Comment by Diana-Rus** [comment] 2020-08-26 09:37
Hello, still encountering the issue from [comment](https://github.com/mozilla-mobile/fenix/issues/12943#issuecomment-669069988) on latest Nightly 8/26, verified with:
- Google Pixel 3XL (Android 9)
- Samsung Galaxy S9 (Android 8)
- Sony Xperia Z5 (Android 7)
<details closed><summary>Issue</summary>

![20200826-122848](https://user-images.githubusercontent.com/49859863/91287330-46f92600-e798-11ea-831d-17c1e1556828.gif)
</details>

@ekager could you please have a look 😊. Removing label qa-needed until further notice.

**Comment by ekager** [comment] 2020-09-09 18:35
@Diana-Rus could you retest? Thanks!

**Comment by Diana-Rus** [comment] 2020-09-10 14:28
Hi @liuche  issue still happens on Nightly 9/10 with
- Google Pixel 3XL (Android 9)
- Sony Xperia Z5 (Android 7)

<details closed><summary>Pixel 3XL (A9)</summary>

![20200910-171339](https://user-images.githubusercontent.com/49859863/92743559-5926b700-f389-11ea-9f6b-cde2dabf8a6d.gif)
</details>

Removing qa needed until further information.

**Comment by ebalazs-sv** [comment] 2021-02-10 07:21
The issue described in comment https://github.com/mozilla-mobile/fenix/issues/12943#issuecomment-669069988 is still reproducible on Nightly 2/10 with Pixel 2 (Android 9).
I will remove the qa:needd label for now.

**Closed** 2021-08-29 23:39 UTC
Labels: 🐞 bug, needs:ac, Feature:Browsing, wontfix

**Comment by mariansima** [comment] 2021-08-30 08:04
Could not reproduce this issue on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29
