### ISSUE TITLE
[Bug]Grey area appears at the bottom of the screen when new popup appears and address bar is hidden

### ISSUE THREAD

**Issue by OlgaMalevich** [mozilla-mobile/fenix#18004] opened 2021-02-15 14:28 UTC
## Steps to reproduce

1. Open Mozilla Firefox for Android
2. Go to any site where popups are opened. For example https://www.oracle.com/java/ or https://www.jetbrains.com/ru-ru/idea/
3. Scroll down untill status bar is hidden
4. Open popup

### Expected behavior
Popup is fully visible
### Actual behavior
Grey block appears at the bottom of the page and hides part of content.
**Videos:**
https://user-images.githubusercontent.com/32940528/107958261-d26aab80-6fb2-11eb-91a0-c6075ab41eb7.mp4
https://user-images.githubusercontent.com/32940528/107958284-d72f5f80-6fb2-11eb-8975-25ee9dcd3c3c.mp4

### Device information
* Device vendor / model and Android version: 
Model Xiaomi MI A1
![Android version](https://user-images.githubusercontent.com/32940528/107958070-8d467980-6fb2-11eb-9ca9-f99dfcf25881.jpg)

* Firefox for Android version: ? (go to Settings -> About Firefox)
 ![Firefox version](https://user-images.githubusercontent.com/32940528/107958064-87e92f00-6fb2-11eb-9d1a-c73806f27e0b.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9716)

**Comment by Mikaka27** [comment] 2021-02-16 12:46
Can you recheck on firefox nightly? I filed a similar bug that seems to be fixed on nightly.

**Comment by OlgaMalevich** [comment] 2021-02-16 14:40
@Mikaka27 , still reproduced on Firefox nightly.
### ARs:
https://user-images.githubusercontent.com/32940528/108077737-e8916e00-707d-11eb-8909-1fe70025ec3a.mp4
https://user-images.githubusercontent.com/32940528/108077759-f0e9a900-707d-11eb-8a3e-5c0a2ff72c87.mp4

### Firefox Nighntly version:
![image](https://user-images.githubusercontent.com/32940528/108077873-12e32b80-707e-11eb-9753-4d2d8456c57d.png)

**Comment by sonora** [comment] 2021-02-17 07:19
I believe this is similar to #17599, where often the 'grey area' covers an entire image as reported, but in some occurences appears as a grey bar only covering the image caption at the bottom of the screen (the part which in the first screenshot there contains the bottom text which can be expanded ny the user). Not sure if it is a popup in the technical sense there). The effect there, however, is unrelated to whether the address bar is hidden or not.

**Comment by Mugurell** [comment] 2021-02-24 08:52
Thank you all!
That bottom space is what the toolbar should occupy, will take this for investigations.

**Comment by Mugurell** [comment] 2021-02-24 08:53
https://github.com/mozilla-mobile/fenix/issues/17599 seems to be a separate issue, maybe particular to that specific website.

**Comment by Mugurell** [comment] 2021-02-24 10:02
Filed a new issue with GV for fixing this - https://bugzilla.mozilla.org/show_bug.cgi?id=1694607.

This would probably be resolved entirely by the GV team but let's keep this ticket open in case it would require any changes in the app.

**Comment by sflorean** [comment] 2021-04-13 15:24
The issue is still reproducible on latest Nightly build with Pixel 3 (Android 11).

**Comment by Mugurell** [comment] 2021-11-25 10:36
Still an issue.

**Closed** 2022-12-03 07:40 UTC
Labels: 🐞 bug, 🙅 waiting, needs:gv, Feature:Toolbar, wontfix

**Comment by kichappa** [comment] 2022-12-09 12:23
This is still an issue. Reproducible [here](https://kichappa.github.io/#/projects).
