### ISSUE TITLE
[Bug] HTTP-based authentication auto-fill credentials not working

### ISSUE THREAD

**Issue by rozmansi** [mozilla-mobile/fenix#13961] opened 2020-08-20 05:33 UTC
## Steps to reproduce
Attempt to logon at any of the websites that use HTTP-based authentication (not the web form based one) you have saved username and password from before (via Firefox Sync or from the old Firefox for Android upgrade).

### Expected behavior
Username and password fields filled in automatically.
When this is a new site, offer to save username and password entered.

### Actual behavior
Credential saving does not work at all. Form fields are not filled with saved username and password, nor you are presented with a choice to save them after entering them manually.

### Device information

* Android device:Android One, Android 10, build 00WW_5_140
* Fenix version: 79.0.5 (Build #2015758619), AC: 48.0.15, 8755ac0cd GV: 79.0.1-20200813192915, AS: 61.0.10

**Comment by kbrosnan** [comment] 2020-09-02 00:25
Closing as a duplicate of #13941

**Closed by kbrosnan** 2020-09-02 00:25 UTC
Labels: needs:triage, 🐞 bug

**Comment by JLJTGR** [comment] 2020-09-02 00:51
I'm worried that when #13941 is fixed that *this* issue will still be broken.  The author of #13941 clearly states that *this* is not a duplicate, even if it is related.

*This* issue is about Fenix offering to use the internal Firefox database of stored passwords and offering to store passwords in the internal database.  Not related to the external Android app Lockwise or other 3rd party password managers.

#13941 is about Fenix creating a credential dialog that will trigger Android's autofill to call upon 3rd party password managers to fill in the credentials.  This could be (external)Lockwise, Google autofull, Keepass, LastPass, etc.  *Not* the internal Firefox database of passwords.

**Comment by rozmansi** [comment] 2020-09-02 04:28
> Closing as a duplicate of #13941

Not duplicates! Please, reopen this issue.

This one is about auto-fill the HTTP auth dialogs using Firefox's internal credential store (Settings >> Logins and Passwords)

#13941 is about auto-filing the HTTP auth dialog with 3rd party autofill apps, like Google, Lockwise and such.

**Comment by rcmcronny** [comment] 2020-09-02 08:46
Please ReOpen, since the update, i am affected to. The saved passwords are NOT autofilled in the http auth dialoge, i have to enter these credentials everytime i open the site. Very annoying, this worked perfectly in firefox before fenix.

**Comment by imacat** [comment] 2020-09-06 15:40
Please reopen this issue since it is not solved yet completely.

**Comment by clientenq** [comment] 2020-09-08 10:56
@kbrosnan Kevin please reopen bug. Issue is not same issue as #13941. Although result for user is same experience the cause is not same. Just marking as duplicate does not do justice to fixing the issue.

**Comment by RES-1** [comment] 2020-09-09 08:20
> @kbrosnan Kevin please reopen bug. Issue is not same issue as #13941. Although result for user is same experience the cause is not same. Just marking as duplicate does not do justice to fixing the issue.

Same here. Please reopen this bug!

**Comment by Hubfront** [comment] 2020-10-30 22:06
It seems, that the open issue #8642 is adressing the same issue (but is falsely categorized as "feature request", should be a bug).
