### ISSUE TITLE
[Bug]: No hints are shown for required form-fields

### ISSUE THREAD

**Issue by hiaselhans** [mozilla-mobile/fenix#23824] opened 2022-02-18 20:50 UTC
### Steps to reproduce

1. [go to https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required#result)
2. fill NO data
3. click submit

### Expected behaviour

should show a hint of missing field
![image](https://user-images.githubusercontent.com/5046381/154759066-22bd81cc-9abb-48f1-9361-edb7ba501ba7.png)

### Actual behaviour

No hints are shown

### Device name

Note 2, Samsung galaxy tab

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

97.1.0

**Comment by kbrosnan** [comment] 2022-02-19 01:11
Duplicate of bz-1510450

**Closed by kbrosnan** 2022-02-19 01:11 UTC
Labels: 🐞 bug, needs:triage
