### ISSUE TITLE
FNX-5348 ⁃ Bookmarks library pane displays everything from the root down

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#1951] opened 2019-04-23 21:33 UTC
This doesn't seem correct. In Fennec we pretend our root is the `mobile` folder. `toolbar` folder is meaningless in Fenix, as well. It's nice to be able to manage it though!

One consideration we've had in the past is data integrity due to buggy bookmark syncing, but perhaps with Rust-powered dogear bookmark merging, those could be put to rest?

cc @linacambridge

![Screenshot](https://user-images.githubusercontent.com/465422/56617308-6e544780-65d4-11e9-82c4-4dfb0846e65d.png)UNITO-UNDERSCORE!1556054954!

**Comment by topotropic** [comment] 2019-04-25 15:22
We don't sync bookmarks yet so we should hide the "menu", "toolbar", "unfiled" folders and launch people directly in "mobile" when they open bookmarks

**Comment by sblatz** [comment] 2019-04-26 19:58
I posted my thoughts on this [here](https://github.com/mozilla-mobile/fenix/issues/2087#issue-437819130).

**Comment by grigoryk** [comment] 2019-04-29 19:34
To circle back here and document what we've discussed in Slack:

Let's do what we do in Fennec and on iOS. By default, in the Bookmarks pane we'll display contents of the mobile root, with a special folder pinned to the top named "Desktop Bookmarks", which contains desktop roots (but, with friendlier names - e.g. `Toolbar`, not `toolbar`).

This is similar to what @sblatz proposed in #2087, but with some more nuance. Since we have bookmark management, whatever we display should reflect an actual structure of the data. For that reason, we can't "merge" all desktop bookmarks; moves from "unsorted" into "toolbar" will be confusing, since it'll look like nothing moved at all!

It's also quite valuable to be able to see contents of these folders if you're a bookmark user. It mirrors what we display in Desktop, and lets you browse your bookmarks in a familiar way as well as fully manage them if you need to.

**Comment by linacambridge** [comment] 2019-04-29 19:41
I like @grigoryk's idea, too—show mobile as the default view, and squirrel away toolbar, menu, and unfiled under a fake "Desktop Bookmarks" folder. [Here](https://searchfox.org/mozilla-central/rev/b756e6d00728dda4121f8278a744381d8643317a/toolkit/locales/en-US/chrome/places/places.properties#5-7) are the localizable names that Desktop uses for those roots.

**Comment by vladikoff** [comment] 2019-04-30 19:38
> It's also quite valuable to be able to see contents of these folders if you're a bookmark user. It mirrors what we display in Desktop, and lets you browse your bookmarks in a familiar way as well as fully manage them if you need to.

👍 

> I like @grigoryk's idea, too—show mobile as the default view, and squirrel away toolbar, menu, and unfiled under a fake "Desktop Bookmarks" folder. Here are the localizable names that Desktop uses for those roots.

👍 

This sounds good. As of f1050eaff501bc6834f2ee1d4c1d78d3ade31cf8 if the user starts with Desktop and syncs some bookmarks, they would get "no bookmarks" and no mobile folder.

**Comment by sv-ohorvath** [comment] 2019-05-02 12:42
Not sure I understand correctly, please correct me if I'm wrong:
1. I should get a Desktop bookmarks folder if I sync with desktop
2. No desktop or other folders on my device unless I have some mobile bookmarks as well and sync.

**Comment by colintheshots** [comment] 2019-05-05 00:46
@sv-ohorvath So we're partway to a solution. https://github.com/mozilla-mobile/fenix/issues/1951#issuecomment-486719462 suggested we should start from the mobile root. So we're doing that now. However, bookmarks sync just landed so people want to see their desktop bookmarks on mobile.

The issue is there's no UX I've seen showing how the roots should be structured. I'm guessing I should basically copy Fennec and add a Show Desktop button, but I'd like UX feedback on this option.

**Comment by sv-ohorvath** [comment] 2019-05-06 07:46
@colintheshots Ok, thanks! From the comments, I thought there's something more here. 
Wouldn't it be better to close this then and have a new ticket for UX to determine how we want to show the desktop bookmarks? There is one already reported: #2252.

**Comment by topotropic** [comment] 2019-05-06 10:36
> I'm guessing I should basically copy Fennec and add a Show Desktop button, .... I assume I can just add a button to the mobile root that lets the user reach the desktop roots.

Sounds good to me. Thanks for requesting UX feedback!

**Comment by grigoryk** [comment] 2019-05-06 18:29
@colintheshots @topotropic please see suggested solution above - https://github.com/mozilla-mobile/fenix/issues/1951#issuecomment-487713804 - that should be a good starting point for what we should do here.

Bulk of the discussion on this topic is in this issue, so it makes sense to me to keep it that way (vs opening new issues).

**Comment by bifleming** [comment] 2019-05-06 21:03
@mheubusch @vesta0 It appears that the original issue has been resolved, but we need a new issue for possible UX changes. Can one of you confirm and create the new issue if needed for MVP?

**Comment by vesta0** [comment] 2019-05-06 21:43
@bifleming we can close this issue but we need to address the issue reported here #2252 with the direction to add a Show Desktop button.

**Comment by bifleming** [comment] 2019-05-06 21:47
@colintheshots pls see Vesta's comment above.

**Comment by sarentz** [comment] 2019-05-22 20:38
This is tracked in https://github.com/mozilla-mobile/fenix/issues/2252

**Closed** 2020-08-11 13:24 UTC
Labels: Feature:Bookmarks, P1, eng:qa:verified, eng:ready, 🐞 bug
