### ISSUE TITLE
[Bug]:  New Tab or plus symbol does not open a new tab

### ISSUE THREAD

**Issue by robovoice1** [mozilla-mobile/fenix#23595] opened 2022-02-06 20:31 UTC
### Steps to reproduce

Open a website in Firefox nighty mobile android
Choose new tab 
Select a bookmarked website
Result is: chosen website opens in the old tab, and not in a new one.

### Expected behaviour

After selecting new tab or plus symbol and after selecting a bookmarked website a new tab opens up. 

### Actual behaviour

Tapping on new tab or the plus symbol does not open a new tab after selecting a bookmarked website

### Device name

Google Pixel 6 pro

### Android version

Android 12 Graphene Os

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1 (Build #2015861835), af98e7bc2+

### Additional information

This is a regression and worked before!

**Comment by Cheap-Skate** [comment] 2022-02-07 10:30
You can long press a bookmark and select "open in new tab" if that helps?

**Comment by robovoice1** [comment] 2022-02-07 11:18
Your described way works, but for what is the "new tab" or the "+" function, when it opens the site in the same (already open) tab  i am wondering.
![Screenshot_20220207-120800](https://user-images.githubusercontent.com/92784377/152778004-de5aa3cf-61b4-4c1e-88a9-4183c87e78b4.png)
![Screenshot_20220207-120819](https://user-images.githubusercontent.com/92784377/152778073-e0a7896f-3360-4ef0-a34d-8439bbc49aee.png)

**Comment by Cheap-Skate** [comment] 2022-02-07 11:28
There is a whole mega thread on this issue, see #20012. I think everyone is pretty confused. 

Recently @czlucius changed the default behavior of Bookmarks, see #13336, which has definitely made some users happy, probably made some unhappy, but has not reduced the overall confusion about what "New Tab" means.

**Comment by robovoice1** [comment] 2022-02-07 11:55
Thanks for pointing this out !

It is not a bug, it is a feature. ;-)
Imho
This creates more confusion than improving the tab managment (including mislabeling)

**Comment by Cheap-Skate** [comment] 2022-02-07 12:01
I think @czlucius is doing us all a big favour with his patches, he is highlighting the confusing and unorthodox New Tab behavior. Hopefully UI devs will take notice and do something more fundamental to make it less confusing and more like other browsers.

**Comment by robovoice1** [comment] 2022-02-07 12:15
Ok, closing this "bug".

**Comment by czlucius** [comment] 2022-02-07 12:16
@robovoice1 I think this is still an issue, you may re-open it.
Thanks!

**Comment by maverick74** [comment] 2022-02-07 16:00
The problem is not the new behavior if you ask me!

@czlucius Indeed did us a big favor and as @Cheap-Skate said the long-press shows the option to open in a new tab!!!

However, user is surely confused by the "new tab" button as it expects to have a new tab when it presses it (like in Firefox desktop). The problem is the original design where the "new tab" does not open a "new tab"

So, the bug is still valid if we stick to the bug's title!

**Comment by kbrosnan** [comment] 2022-02-07 16:36
Duplicate of https://github.com/mozilla-mobile/fenix/issues/20012 then.

**Closed by kbrosnan** 2022-02-07 16:36 UTC
Labels: 🐞 bug, needs:triage

**Comment by robovoice1** [comment] 2022-02-07 17:28
If you leave this "as is", it will surely generate two more waves of endless discussions (beta, stable release)

I propose renaming new tab to open in same tab
and/or a selection (based on the use case and smartphone low/mid/top of the fenix user)
Same tab  (low/midrange smartphone users can use this)
New tab    (which actually starts a new clean tab for top smarthones)

My two cents :-)
