### ISSUE TITLE
[Bug] FireFox does not return to portrait mode if the screen was locked during a full-screen video playback.

### ISSUE THREAD

**Issue by HubKing** [mozilla-mobile/fenix#17344] opened 2021-01-07 02:15 UTC
## Steps to reproduce
1. Disable screen auto-rotation (the device's screen is in portrait mode).
2. Go to m.youtube.com and open any video.
3. Click the full screen button on the bottom right of the video.
4. The video often becomes landscape filling the entire screen. (Sometimes it remains portrait showing a big letter box. I don't know why, but if that happens, exit the full screen mode and repeat step 4 until you get landscape video).
5. Pause the video and press the power button to turn off the screen.
6. Turn on the screen again by pressing the power button or touching the fingerprint sensor.
7. Exit the full-screen video.

### Expected behavior
FireFox should return to portrait mode.

### Actual behavior
FireFox remains in landscape mode, and even if I keep rotating the device, the small manual rotate button (that was introduced in Android 9) does not appear. If I exit FireFox (not terminating) to the home screen, the screen becomes portrait, but if I click FireFox again, the screen rotates to landscape. The only way I could find to fix is terminating FireFox and open FireFox again.

### Device information
It happens on tree different devices running Android 10 with gesture navigation.

* Android device: Samsung Galaxy s5e et al.
* Fenix version: 84.1.2

**Comment by ekager** [comment] 2021-01-07 18:21
Closing as dupe of #15270 and I believe this should be fixed in Nightly (if you want to test it)

**Closed by ekager** 2021-01-07 18:21 UTC
Labels: needs:triage, 🐞 bug

**Comment by HubKing** [comment] 2021-01-08 02:50
> 
> 
> I believe this should be fixed in Nightly (if you want to test it)

Yeah, sort of. I tested the latest Nightly and it just exited the full-screen mode automatically when I unlocked the screen, as if I had pressed the back button. Not sure if this is a perfect solution, because some users would want to resume the full-screen playback, but at least it is no longer stuck in the landscape mode.
