### ISSUE TITLE
Add loading indicator when address bar is hidden

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#15534] opened 2020-09-29 13:24 UTC
### What is the user problem or growth opportunity you want to see solved?
Right now it's not possible to see if a page is loading when the address bar is hidden. In this case, the loading bar that's normally above the address bar could still be shown. I think chrome does this as well

### How do you know that this problem exists today? Why is this important?
Sometimes when you click on a link you're not sure if you actually clicked on it, so some visual feedback would be helpful. Also if a page is slow to load this would be immediately clear to the user.

**Comment by kbrosnan** [comment] 2020-10-01 18:14
Where are you seeing this? The address bar should be shown when the page is loading.

**Comment by cadeyrn** [comment] 2020-10-01 20:48
> The address bar should be shown when the page is loading

This is not working on GitHub or on mozac.org. If you scroll down so that the toolbar is no longer visible the toolbar does **not** reappear if you click a link and therefore you don't see the loading progress.

**Comment by kbrosnan** [comment] 2020-10-08 06:16
I don't get this behavior on Nightly navigating results in the navbar appearing on mozac and github.

**Comment by cadeyrn** [comment] 2020-10-08 07:13
Maybe there was a recent fix? It was definitively an issue for a very long time and it was still an issue when I wrote my last comment but I can no longer reproduce. 🙂

**Comment by kbrosnan** [comment] 2020-10-22 09:00
Closing as works for me

**Closed by kbrosnan** 2020-10-22 09:00 UTC
Labels: Feature:Toolbar, 🐞 bug

**Comment by Dunexus** [comment] 2020-10-22 12:01
@kbrosnan Just updated and it is still an issue. The loading indicator hides with the address bar.

![20-10-22-13-55-17_01](https://user-images.githubusercontent.com/13906248/96868927-04d62300-146f-11eb-84e9-1af72d64b124.gif)
