### ISSUE TITLE
[Bug] Search widget is light with dark theme

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#15996] opened 2020-10-17 12:23 UTC
## Steps to reproduce 
Switch to dark theme.
Add search widget to screen.

### Expected behavior
The widget is dark. This used to be the case in early development of the feature https://github.com/mozilla-mobile/fenix/issues/4840
![Egkr93tWoAAqvnV](https://user-images.githubusercontent.com/922368/96337069-c3b7ca80-108c-11eb-8c09-5b15b71cdec6.jpg)

### Actual behavior
It stopped working once the feature was finalized.
![Screenshot_20201017-151722_Lawnchair](https://user-images.githubusercontent.com/922368/96337075-d4684080-108c-11eb-8dcc-dbd5fe675add.png)

### Device information

* Android device: OnePlus5t with LineageOS 16
* Fenix version: Nightly

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-8276)

**Comment by andreicristianpetcu** [comment] 2020-10-17 12:25
Can I debug this locally if I build Fenix?

**Comment by andreicristianpetcu** [comment] 2020-10-18 11:11
I see this PR added this feature https://github.com/mozilla-mobile/fenix/pull/13975
@shahsurajk any pointers here I should start looking? I'm super new to Android dev.

**Comment by andreicristianpetcu** [comment] 2020-10-18 12:37
Both OS and Fenix have dark theme. ![Screenshot_20201018-153557_LineageOS_Settings](https://user-images.githubusercontent.com/922368/96367640-bddaeb80-1157-11eb-9522-954a6711a5ac.png)
![Screenshot_20201018-153638_Firefox_Nightly](https://user-images.githubusercontent.com/922368/96367642-bf0c1880-1157-11eb-8717-f5434d68bcf5.png)

**Comment by andreicristianpetcu** [comment] 2020-10-18 14:21
My android has api version 28. Might this be the issue? I tried to build it for api 28 but I get all sorts of compile issues. I can only run it in api version 30.

**Comment by andreicristianpetcu** [comment] 2020-10-18 15:12
I reproduced it locally in Android studio.
![image](https://user-images.githubusercontent.com/922368/96371948-28e2ed00-116d-11eb-8e34-a6167c91fab0.png)
![image](https://user-images.githubusercontent.com/922368/96371971-44e68e80-116d-11eb-9d5b-def94010c7e1.png)
Strangely the theme in the simulator is dark but it still looks light.

**Comment by sflorean** [comment] 2020-10-19 16:12
I was able to reproduce this on Nightly 19/10 with Google Pixel 3 (Android 11).

**Comment by shahsurajk** [comment] 2020-10-19 18:32
@andreicristianpetcu , im not sure why this is happening, tried on my Nokia 7.1 running android 10, it seems to be working, could this be an Android 11 issue?

**Comment by andreicristianpetcu** [comment] 2020-10-19 20:46
I'm running the equivalent of android 9 which is the latest LineageOS for my phone. @shahsurajk

**Comment by andreicristianpetcu** [comment] 2020-11-17 20:25
I updated to LineageOS 17.1 (based on android 10) and the search is black now. I'm not interested in this bug anymore since an update fixed it. Can we close it?

**Comment by softvision-miralobontiu** [comment] 2020-12-08 12:41
I've encountered this issue on the 84.0.0-beta.4 build with Samsung Galaxy Tab S6 (Android 10).
I had the light theme enabled, but the widget had a dark theme.

**Comment by andreicristianpetcu** [comment] 2020-12-08 20:52
Isn't is simpler to offer both light and dark widgets and let users choose? This is what ddg and vlc are doing.
![Screenshot_20201208-225021_Lawnchair](https://user-images.githubusercontent.com/922368/101539935-f2289680-39a7-11eb-9bc0-acd08d172041.png)
![Screenshot_20201208-225034_Lawnchair](https://user-images.githubusercontent.com/922368/101539937-f2c12d00-39a7-11eb-970b-6100d37a0771.png)

**Comment by lobontiumira** [comment] 2021-06-07 13:47
I was able to reproduce the issue on the 6/7 Nightly build with Samsung Galaxy Note 8 (Android 9): when the app is set to light theme, the widget has black theme.

**Comment by lobontiumira** [comment] 2021-06-11 14:23
Reproducible on Beta 90.0.0-beta.3 with Samsung Galaxy Tab A6 (Android 5.1.1).
I will update the title of the issue.

**Comment by lobontiumira** [comment] 2021-07-07 11:31
Reproducible on RC 90.1.0 build with OnePlus 5T (Android 10).

**Comment by lobontiumira** [comment] 2021-08-03 07:01
Reproducible on Beta 91.0.0-beta.6 with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by lobontiumira** [comment] 2021-09-08 13:48
Reproducible on 93.0.0-beta.1 with Lenovo Tab M10 (Android 10).

**Comment by sflorean** [comment] 2022-03-08 15:55
This is still reproducible on latest versions of Firefox.

**Comment by delia-pop** [comment] 2022-04-13 06:52
Reproducible on Beta 100.0.0-beta.4 with Google Pixel 6 (Android 12).

**Comment by delia-pop** [comment] 2022-07-13 13:19
I can no longer reproduce this issue on the latest Nightly 104 from 07/13, RC 102.2.1 and Beta 103.Beta4. The widget follows the device's theme and its updates accordingly after changing the device theme. I will close this issue for now.

**Closed by delia-pop** 2022-07-13 13:19 UTC
Labels: 🐞 bug, Feature:Themes, S2, feature:SearchWidget, qa-triaged
