### ISSUE TITLE
[Bug]: Slash at end of hostnames opens web search instead of URL

### ISSUE THREAD

**Issue by chrishamm** [mozilla-mobile/fenix#23137] opened 2022-01-10 11:05 UTC
### Steps to reproduce

In Firefox (on desktops) you can enter a hostname, append a slash (/), and hit Enter to navigate to the entered URL. This does not work in Firefox for Android unless you prepend `http://` every time which isn't auto-completed either.

I generally try to use this feature to access the web interface of my 3D printer on my LAN but entering `ender3pro/` always opens Google Search on Firefox for Android whereas it works as you'd expect on my desktop's Firefox.

### Expected behaviour

When you append a slash to an expression (i.e. if `/` is the last character), Firefox for Android should check if the entered value is a valid hostname and it should attempt to navigate to it like the normal Firefox does.

### Actual behaviour

Firefox searches for the entered hostname even though a slash is appended

### Device name

Google Pixel 4a

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

95.2.0

**Comment by kbrosnan** [comment] 2022-01-10 21:45
Duplicate of https://github.com/mozilla-mobile/fenix/issues/12641

**Closed by kbrosnan** 2022-01-10 21:45 UTC
Labels: 🐞 bug, needs:triage
