### ISSUE TITLE
[Bug] Gap in the UI above website headers

### ISSUE THREAD

**Issue by chillypeppe** [mozilla-mobile/fenix#15483] opened 2020-09-27 21:39 UTC
## Steps to reproduce
Just search something on a website with a header (e.g. duckduckgo), scroll up and down on the page
### Expected behavior
There shouldn't be any gap between the header and the top border (bromite screenshot)
![20200927_232757](https://user-images.githubusercontent.com/43646324/94376161-1c90e480-0119-11eb-998b-5882e47afb76.jpg)
### Actual behavior
There is a gap
(Bottom toolbar)
![20200927_232629](https://user-images.githubusercontent.com/43646324/94376134-e81d2880-0118-11eb-8c2f-576ffb2cf35f.jpg)
(Top toolbar)
![20200927_233359](https://user-images.githubusercontent.com/43646324/94376303-0e8f9380-011a-11eb-8664-2e786e64eca6.jpg)
### Device information
SM-G974F Samsung Galaxy S10
Android 10
* Fenix version: 81.1.1 but it appeared after an update when the new firefox was still in beta. I reported it then, but it hasn't been fixed yet.

**Comment by s-ankur** [comment] 2020-09-28 11:02
Duplicate of https://github.com/mozilla-mobile/fenix/issues/10598

**Closed** 2020-09-28 11:06 UTC
Labels: needs:triage, 🐞 bug
