### ISSUE TITLE
[Bug]: PWA Apps Have Blank Toolbar when Scroll to Hide Toolbar is Enabled

### ISSUE THREAD

**Issue by xcjs** [mozilla-mobile/fenix#24989] opened 2022-04-28 00:06 UTC
### Steps to reproduce

I'm not sure if this full set of steps is required, but it fits my situation.

1. Install Firefox for Android
2. Set the toolbar to the top
3. Set the toolbar to hide on scroll
4. Find a web site that supports installation as a PWA and install it
5. Set the toolbar to no longer hide on scroll

### Expected behaviour

Since PWAs don't display their URL, the PWA should not display the browser chrome.

### Actual behaviour

Instead, I get a "blank" toolbar at the top of my PWA that makes the web site viewport smaller. I would provide screenshots in my case, but the PWA I'm using contains private information, and I can't think of another PWA to test.

### Device name

Google Pixel 6 Pro

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

99.2.0

**Comment by amocirean** [comment] 2022-04-28 08:41
Hello @xcjs, thank you for the submitted issue.
I was able to reproduce this on the latest RC (100.1.0) and latest Nightly 101.0a1 (2022-04-28). 

- Android Version: 10
- Devices Used: Huawei P40 Lite

However, this is a duplicate of #19972 issue.

**Closed** 2022-04-28 08:43 UTC
Labels: 🐞 bug, needs:triage
