### ISSUE TITLE
[Bug] Download notification doesn't disappear even when the download is finished

### ISSUE THREAD

**Issue by purinpurin** [mozilla-mobile/fenix#9884] opened 2020-04-13 14:06 UTC
## Steps to reproduce
Download Manjaro XFCE edition.

### Expected behavior
Mark the download process as completed and the notification should be removable.

### Actual behavior
Sill show the download progress notification even after forced stopped and reopened. It cannot be canceled or cannot be paused.

### Device information
* Android device: Oneplus 6
* Android version: 10
* Rom: OxygenOS version 10.3.2
* Fenix version: 4.2.1

![Screenshot](https://user-images.githubusercontent.com/11447571/79126833-b7457300-7dc6-11ea-923a-fc9ebb5fff3e.jpg)

**Comment by SS1113** [comment] 2020-04-13 15:58
Facing the same issue, it appears at random, the notification becomes unresponsive, if clicked Cancel or Pause nothing happens but the downloads complete. 
Device: Motorola One Power, Android 10.
Firefox preview 4.2.1 (Build #20941431)

**Comment by Amejia481** [comment] 2020-04-27 20:49
This should be fixed in master.
@purinpurin and QA would you mind verifying if this is still an issue? Thanks in advance :)

**Comment by purinpurin** [comment] 2020-04-28 04:10
That's great. For me, that was the only time this abnormality had occurred. I never once again see it happens. Thank you.

**Comment by sv-ohorvath** [comment] 2020-04-28 10:39
I was able to reproduce this on Nightly 4/28 on a HTC Desire 820 (Android 6.0.1) by saving a bunch of images from google image search. 
Just long tap and save image, one after another, and at one point, one of them will hang.
I also got a download without a name.

![Screenshot_20200428-133735 1](https://user-images.githubusercontent.com/4037709/80478044-98fa7e00-8955-11ea-8ec0-f9ac51c24aa8.png)

![Screenshot_20200428-131208 1](https://user-images.githubusercontent.com/4037709/80478048-9a2bab00-8955-11ea-9a4f-efe2ad123ead.png)

**Comment by Amejia481** [comment] 2020-05-09 15:24
> @Amejia481 I was able to reproduce this on Nightly 4/28 on a HTC Desire 820 (Android 6.0.1) by saving a bunch of images from google image search.
> Just long tap and save image, one after another, and at one point, one of them will hang.
> I also got a download without a name, that keeps loading.
> Another one that it's completed and still showing.
> If I kill the app, they go away.
> 
> ![Screenshot_20200428-133735 1](https://user-images.githubusercontent.com/4037709/80478044-98fa7e00-8955-11ea-8ec0-f9ac51c24aa8.png)
> 
> ![Screenshot_20200428-131208 1](https://user-images.githubusercontent.com/4037709/80478048-9a2bab00-8955-11ea-9a4f-efe2ad123ead.png)

@sv-ohorvath this should be fixed on master, would you mind retesting? Thanks in advance.

**Comment by sv-ohorvath** [comment] 2020-05-11 08:49
Cannot reproduce this on Nightly 5/11 anymore. Verified as fixed.

**Closed by sv-ohorvath** 2020-05-11 08:49 UTC
Labels: Feature:Download, S3, eng:qa:needed, 🐞 bug
