### ISSUE TITLE
Reddit does not stay logged in when replying

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#13882] opened 2020-08-17 17:48 UTC
## Steps to reproduce

1) Make a reddit account (or use existing one)
2) Log in
3) Reply to a post

### Expected behavior

Compose screen to compose the post reply.

### Actual behavior

Reddit detects that you are logged out and offers to log in again (see screenshot).

Trying the STR immediately after this produces the exact same result, so it is never possible to compose a reply.

This is very common but not 100% reproducible. Seems like a regression from Fennec as that always has worked.

![Screenshot_20200817_091743_org mozilla fenix](https://user-images.githubusercontent.com/1104290/90427151-75a13d80-e0c2-11ea-8ec4-667b1420f57b.jpg)

### Device information

* Android device: Pixel 2 XL
* Fenix version: Nightly

**Comment by liuche** [comment] 2020-08-20 02:05
Do you have ETP strict mode turned on? Does this still happen if you turn off ETP for reddit?

**Comment by gcp** [comment] 2020-08-20 07:49
I'm using standard ETP (the default). I'll try with it fully disabled.

**Comment by softvision-miralobontiu** [comment] 2020-12-21 09:14
I was not able to reproduce this issue on the 12/21 Nightly build with Google Pixel (Android 10).
I'll close this issue.

**Closed by softvision-miralobontiu** 2020-12-21 09:14 UTC
Labels: eng:qa:needed, 🐞 bug
