### ISSUE TITLE
[Bug]: Saved logins not accessible if using pattern to unlock

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#22464] opened 2021-11-16 18:54 UTC
### Steps to reproduce

1. Have a pattern AND fingerprint set to unlock your device
2. Open Nightly (11/16)
3. Go to Settings -> Logins and passwords -> Saved logins
4. Instead of using your fingerprint to unlock, use the "Use pattern" button on the bottom left
5. Enter (correct) pattern to unlock

### Expected behaviour

Saved logins should be opened

### Actual behaviour

You stay on the "Logins and passwords" page (when using the pattern). It works properly and takes you to saved logins if you use your fingerprint to unlock. I haven't tested removing fingerprints from the device and only using pattern

### Device name

Pixel 3

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

nightly build #2015846091

### Additional information

AC 96.0.20211115143414
AS 86.2.0

**Comment by mcarare** [comment] 2021-12-20 10:30
Can QA please retest this? 
It works as expected for me, using a Nokia with Android 10, with both pattern and biometric(fingerprint) unlock.
Thank you!

**Comment by sflorean** [comment] 2021-12-20 15:10
@mcarare I wasn't able to reproduce this issue, following the steps, with Pixel 3 (Android 12) on latest Nightly build.

**Comment by mcarare** [comment] 2021-12-20 15:14
@eliserichards can you also recheck this to see if it's still an issue? Thank you!

**Comment by eliserichards** [comment] 2022-01-13 00:30
Weird, it is still broken for me :/ 

Using latest nightly 2022-01-12: The video shows opening it with the pattern (twice), and then opening it with my fingerprint

https://user-images.githubusercontent.com/43795363/149244471-d3053df6-bb7d-49e6-bed1-e81b22618d20.mov

**Comment by mcarare** [comment] 2022-01-13 14:06
@eliserichards Does it work on the manage credit cards screen? 
Does it reproduce with 3 button navigation?

Does it still happen if you set https://github.com/mozilla-mobile/fenix/blob/846274b7cdc48e567b4f60abf10da9f633a82bdb/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt#L243 to a higher value? It might be that the navigate call is happening when the fragment is still paused. 

Thank you for your time! I could not manage to reproduce this on any device I have.

**Comment by lobontiumira** [comment] 2022-01-13 14:15
I was not able to reproduce this issue using a Google Pixel (Android 10).
Tested on Fenix Nightly 97.0a1 (build 2015855787, GV 97.0a1-20220105093353).

**Comment by eliserichards** [comment] 2022-01-31 22:11
The same thing happens when I try to access Credit Cards.

Looking at logcat, there aren't even any crashes. The only differences I see between unlocking with my fingerprint vs pattern is some strictmode violations when I use the pattern: 

```
2022-01-31 14:08:34.007 3680-3680/org.mozilla.fenix.debug W/lla.fenix.debu: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2022-01-31 14:08:34.007 3680-3680/org.mozilla.fenix.debug D/StrictMode: StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V
        at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
        at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
        at java.lang.Class.getDeclaredMethodInternal(Native Method)
        at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
        at java.lang.Class.getMethod(Class.java:2066)
        at java.lang.Class.getMethod(Class.java:1693)
        at androidx.appcompat.widget.ViewUtils.makeOptionalFitsSystemWindows(ViewUtils.java:84)
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:976)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:687)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:201)
        at org.mozilla.fenix.HomeActivity.onCreate(HomeActivity.kt:215)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2022-01-31 14:08:34.009 3680-3680/org.mozilla.fenix.debug W/FenixPerf: StrictMode violation suppressed: #30
2022-01-31 14:08:34.009 3680-3680/org.mozilla.fenix.debug D/App: DebugMetricController: track event: org.mozilla.fenix.components.metrics.Event$StartOnHomeEnterHomeScreen@e74f414
2022-01-31 14:08:34.009 3680-3680/org.mozilla.fenix.debug D/ColdStartupDuration: Not measuring: is not cold start (short-circuit)
2022-01-31 14:08:34.009 3680-3680/org.mozilla.fenix.debug I/service-pocket: Scheduling pocket recommendations background refresh
2022-01-31 14:08:34.015 3680-3680/org.mozilla.fenix.debug D/GeckoRuntime: Lifecycle: onStart
2022-01-31 14:08:34.015 3680-3820/org.mozilla.fenix.debug I/libglean_ffi: glean_core: Glean disabled: not submitting any pings.
2022-01-31 14:08:34.015 3680-3820/org.mozilla.fenix.debug I/libglean_ffi: glean_core: baseline ping not submitted on active
2022-01-31 14:08:34.024 3680-3680/org.mozilla.fenix.debug D/GeckoRuntime: Lifecycle: onResume
2022-01-31 14:08:34.024 3680-3680/org.mozilla.fenix.debug D/GeckoNetworkManager: Incoming event start for state OffWithListeners -> OnWithListeners
2022-01-31 14:08:34.026 3680-3680/org.mozilla.fenix.debug I/StartupTypeTelemetry: Recorded start up: warm_main
2022-01-31 14:08:34.032 3680-3680/org.mozilla.fenix.debug D/StrictMode: StrictMode policy violation; ~duration=64 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7246)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:815)
        at android.app.ContextImpl.getDataDir(ContextImpl.java:2340)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:590)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:787)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:439)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
        at androidx.preference.PreferenceManager.getSharedPreferences(PreferenceManager.java:406)
        at androidx.preference.Preference.getSharedPreferences(Preference.java:1232)
        at androidx.preference.Preference.dispatchSetInitialValue(Preference.java:1582)
        at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1311)
        at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1326)
        at androidx.preference.PreferenceGroup.addPreference(PreferenceGroup.java:249)
        at androidx.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:170)
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:345)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109)
        at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
        at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:377)
        at org.mozilla.fenix.settings.logins.fragment.SavedLoginsAuthFragment.onCreatePreferences(SavedLoginsAuthFragment.kt:46)
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
        at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1891)
        at androidx.fragment.app.Fragment.onCreate(Fragment.java:1867)
        at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:264)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:140)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:319)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:298)
        at org.mozilla.fenix.HomeActivity.onCreateView(HomeActivity.kt:520)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
    	at android.view.LayoutInflater.inflate
2022-01-31 14:08:34.033 3680-3680/org.mozilla.fenix.debug D/StrictMode: StrictMode policy violation; ~duration=64 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7246)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:815)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:645)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:636)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:592)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:787)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:439)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
        at androidx.preference.PreferenceManager.getSharedPreferences(PreferenceManager.java:406)
        at androidx.preference.Preference.getSharedPreferences(Preference.java:1232)
        at androidx.preference.Preference.dispatchSetInitialValue(Preference.java:1582)
        at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1311)
        at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1326)
        at androidx.preference.PreferenceGroup.addPreference(PreferenceGroup.java:249)
        at androidx.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:170)
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:345)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109)
        at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
        at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:377)
        at org.mozilla.fenix.settings.logins.fragment.SavedLoginsAuthFragment.onCreatePreferences(SavedLoginsAuthFragment.kt:46)
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
        at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1891)
        at androidx.fragment.app.Fragment.onCreate(Fragment.java:1867)
        at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:264)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:140)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:319)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:298)
        at org.mozilla.fenix.HomeActivity.onCreateView(HomeActivity.kt:520)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
    	at android.view.LayoutInflate
```

I don't know much about strictmode violations. Do you think that has anything to do with it @mcarare? I think we should probably just close this ticket since it's not reproducible by anyone else 😅

**Comment by mcarare** [comment] 2022-02-16 17:56
Closing this as QA cannot reproduce it either ( see [comment](https://github.com/mozilla-mobile/fenix/issues/22464#issuecomment-1012176083)). Will revisit it if any other users report this issue. Thank you @eliserichards for feedback on this.

**Closed by mcarare** 2022-02-16 17:56 UTC
Labels: 🐞 bug, Feature:Logins
