### ISSUE TITLE
Intermittent failure goBackTest a string containing "localhost:40099/pages/generic2.html"' doesn't match the selected view. 

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#14534] opened 2020-08-31 14:15 UTC
Log https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8674547862728683861/executions/bs.e33ac228b42ab4ee/testcases/2/errors

androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'with text: a string containing "localhost:40099/pages/generic2.html"' doesn't match the selected view.
Expected: with text: a string containing "localhost:40099/pages/generic2.html"
Got: "TextView{id=2131362544, res-name=mozac_browser_toolbar_url_view, visibility=VISIBLE, width=604, height=110, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@7c4070d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=localhost:40099/pages/generic1.html, hint=Search or enter address, input-type=0, ime-target=false, has-links=false}"

at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:103)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyUrl(BrowserRobot.kt:62)
at org.mozilla.fenix.ui.NavigationToolbarTest$goBackTest$4.invoke(NavigationToolbarTest.kt:62)
at org.mozilla.fenix.ui.NavigationToolbarTest$goBackTest$4.invoke(NavigationToolbarTest.kt:30)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:107)
at org.mozilla.fenix.ui.NavigationToolbarTest.goBackTest(NavigationToolbarTest.kt:60)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
Caused by: junit.framework.AssertionFailedError: 'with text: a string containing "localhost:40099/pages/generic2.html"' doesn't match the selected view.
Expected: with text: a string containing "localhost:40099/pages/generic2.html"
Got: "TextView{id=2131362544, res-name=mozac_browser_toolbar_url_view, visibility=VISIBLE, width=604, height=110, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@7c4070d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=localhost:40099/pages/generic1.html, hint=Search or enter address, input-type=0, ime-target=false, has-links=false}"

at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:15)
at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:15)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:10)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:11)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:2)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by sv-ohorvath** [comment] 2020-09-21 07:27
Still flaky sometimes: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8776134553101625209/executions/bs.fb2181230467e988/testcases/2/test-cases

**Comment by sv-ohorvath** [comment] 2020-10-12 09:57
Flaky, 1/2: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6636221168748415517/executions/bs.7f356441d14c8f3e/testcases/2/test-cases

**Comment by sv-ohorvath** [comment] 2020-10-20 13:07
I can't make the tests fail locally, but I can reproduce manually. Both the goBackTest and the goForwardTest(#12894) fail at the same validation: verifying the correct URL is shown while loading a second URL on top of the first. Even with an increased waiting time of 30 secs, it seems that the first URL is still showing while waiting for the second. There are some issues logged around pages not loading/being stuck, one of them which I find relevant to these tests being: https://github.com/mozilla-mobile/fenix/issues/12199
Since this test isn't failing so often to block the developers, I'll leave it waiting for a bug fix.

**Comment by isabelrios** [comment] 2020-10-23 14:30
This test failed 2/2 on Oct 23rd:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7442715160734651896/executions/bs.d1843785398b4d12/test-cases

But it passed the next run

**Comment by isabelrios** [comment] 2020-10-27 10:18
Failed 2/2 on Oct 27th: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7334618060602725111/executions/bs.a1c78ba91f1a006c

**Comment by sv-ohorvath** [comment] 2020-11-16 10:27
Flaky, 1/2 on 11/16: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7315900883627794073/executions/bs.573b3b2402e2a536/testcases/2/test-cases

**Comment by sv-ohorvath** [comment] 2020-11-16 12:53
Failed 2/2 on a recent PR: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5138402659654620878/executions/bs.63c0c07ff652d6fb/testcases/2/test-cases

**Comment by sv-ohorvath** [comment] 2020-11-17 10:14
Flaky on 11/17 on master: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5213883050838883150/executions/bs.c7ac337828886999/testcases/2/test-cases

**Comment by sv-ohorvath** [comment] 2020-11-18 07:48
Flaky 11/18 on master: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5078303125591037066/executions/bs.b6436ed0128655ae/testcases/2/test-cases

**Comment by isabelrios** [comment] 2020-11-20 09:28
Flaky on 11/20th on master: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8148897951904571012/executions/bs.220a98c17c0d59c2/test-cases

**Comment by sv-ohorvath** [comment] 2020-11-23 09:28
Flaky on 11/21 & 11/23 on master: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8370720436396174481/executions/bs.460fc7148f4f022d/testcases/2/test-cases

**Comment by isabelrios** [comment] 2020-11-27 12:15
Failed 2/2 on master, although it passed in next commits:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5744182236118999127/executions/bs.f4eca6868c611d46/test-cases

**Comment by sv-ohorvath** [comment] 2020-12-03 11:35
Flaky, failed 1/2 on 12/3: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5115621980379567812/executions/bs.6a63756ed8ec2bf0/testcases/2/logs

**Comment by sv-ohorvath** [comment] 2020-12-10 09:02
Flaky on 12/9: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5997950519835096174/executions/bs.ff44e3ab2d59ac38/testcases/2/test-cases

**Comment by sv-ohorvath** [comment] 2021-01-04 08:44
Failed 2/2 on master 12/24: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9038153808390561985/executions/bs.2d96ccc65cec0dd4/testcases/2/test-cases

**Comment by sv-ohorvath** [comment] 2021-01-04 08:52
Flaky on 12/26: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5961346248632349583/executions/bs.6da2aee73b56428b/testcases/2/test-cases

**Comment by sv-ohorvath** [comment] 2021-01-05 10:56
Flaky on 3 different runs on 1/4 & 1/5/21: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8843371617926116748/executions/bs.cf4f423df8dcbe43/testcases/2/test-cases

**Comment by sv-ohorvath** [comment] 2021-01-06 09:35
Flaky on 1/6: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6399701905107462634/executions/bs.a2eebea94e0cc1ac/testcases/2/test-cases

**Comment by sv-ohorvath** [comment] 2021-01-12 09:46
Flaky on 1/12: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6209310201137899130/executions/bs.c1ffb309c84aa87c/testcases/2/test-cases

**Comment by isabelrios** [comment] 2021-01-14 15:25
Failed 2/2 on 1/14: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7364442384701193863/executions/bs.977056101fc123ea/test-cases

**Comment by isabelrios** [comment] 2021-01-15 10:59
Flaky 1/2 on 1/15: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5804609401634888780/executions/bs.fa551eb02cd77783/test-cases

**Comment by sv-ohorvath** [comment] 2021-01-18 15:32
Flaky on master 1/18: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5373163775922211064/executions/bs.7404979a88cdfea/testcases/2/test-cases

**Comment by sv-ohorvath** [comment] 2021-01-20 09:30
Failed 2/2 tries on 1/20: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7150731363913616220/executions/bs.dd92fd690d7eb70d/testcases/2/test-cases

**Comment by sv-ohorvath** [comment] 2021-01-21 08:23
Hopefully fixed by https://github.com/mozilla-mobile/fenix/pull/17546

**Closed by sv-ohorvath** 2021-01-21 08:23 UTC
Labels: eng:intermittent-test, eng:ui-test, 🙅 waiting
