### ISSUE TITLE
[Bug] LastPass doesn't work with org.mozilla.firefox_beta

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#12128] opened 2020-06-30 13:37 UTC
## Steps to reproduce
1. Sign in on LastPass. Make sure to have credentials saved for a website.
1. In Fenix beta (org.mozilla.firefox_beta) navigate to that website and open the login page.
1. Tap the LastPass notification to auto-fill the login form.
    1. Expected behavior
The login is inserted.
    1. Actual behavior
LastPass doesn't do anything, there is an error message: "Please scroll the browser window until the website address is visible, then try again."
    1. Device information

* Android device: Huawei P20 (Android 9), Pixel 4 (Android 10)
* Fenix version: Fenix 79.0.1-beta1

Note: LastPass works on Nightly, 
Auto-fill with Bitwarden works on Beta too.

**Comment by theovds** [comment] 2020-07-03 07:19
Same problem here. Maybe related to the disappearing url-bar?

**Comment by abodea** [comment] 2020-07-06 13:10
I was also able to reproduce this issue with the first RC migration build and the migrated Nightly, I do believe this is migration-related only.
There was a new issue reported in [Bugzilla ](https://bugzilla.mozilla.org/show_bug.cgi?id=1645801).

**Comment by theovds** [comment] 2020-07-22 08:52
Any news on this?

**Comment by ekager** [comment] 2020-08-01 00:53
I have LastPass as my password manager but can't get it to work on any of the channels debug, beta, nightly 👿 

Maybe we could do a quick test the most popular password managers on the newly solidified channels and see if there's a pattern where it's either our channels that don't work with the apps or the password manager apps that aren't working consistently?

**Comment by vesta0** [comment] 2020-08-01 06:52
Hey @ekager @abodea yes please let's prioritize this investigation and determine if this is something we need to fix or if we need to reach out to the LastPass team as soon as possible.

**Comment by shawnz** [comment] 2020-08-01 11:35
Since about last month this is now working fine for me in nightly as I commented in #4205 . I also just realized something: I am subscribed to the LastPass beta in Google Play. Maybe that is the reason why it works for me?

I currently have LastPass for android version 4.11.13.5703

**Comment by ekager** [comment] 2020-08-02 00:32
QA - wondering if you could help us test LastPass (and perhaps LastPass Beta) autofilling behavior on the migrated release, beta, and nightly channels. 

Some investigation was done here, but we'd like to understand if this is an issue on our end or their end before going through their support channels more aggressively. https://github.com/mozilla-mobile/fenix/issues/4205#issuecomment-655564390

Jon's comment here about what we should communicate to LastPass if we decide this is a bug on their end. https://github.com/mozilla-mobile/fenix/issues/4205#issuecomment-596615595

**Comment by ekager** [comment] 2020-08-03 18:42
Okay there's already the start of a matrix here https://github.com/mozilla-mobile/fenix/issues/9773 so let's move this testing discussion there.

**Comment by kbrosnan** [comment] 2020-09-08 17:37
Closing in favor of #9773

**Closed by kbrosnan** 2020-09-08 17:37 UTC
Labels: Feature:Browsing, Feature:Logins, S2, needs:investigation, 🐞 bug
