### ISSUE TITLE
[Bug] Tab count is shifted

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#5868] opened 2019-10-08 20:42 UTC
## Steps to reproduce
Unknown. Notes:
- I see this on a fairly regular basis
- It seems unrelated to the number of tabs (i.e. the same tab count will be displayed centered sometimes but not others)
- It seems to occur more often after not using Fenix for a while
- My device font size is larger than default: it's "Large"

### Expected behavior
Tab count is centered.

### Actual behavior
Tab count is shifted.

![Screenshot_20190915-075106](https://user-images.githubusercontent.com/759372/66431732-6e54d200-e9d1-11e9-9f35-6ce31caa927b.png)

### Device information
* Android device: Pixel 2
* Fenix version: Nightly 191008
* Device font size is set to "Large"

**Comment by cadeyrn** [comment] 2019-10-08 21:15
Duplicate of #5346.

**Comment by ekager** [comment] 2019-10-08 23:27
Closing for #5346 but I will add in that ticket that it could be related to changing device text size

**Closed by ekager** 2019-10-08 23:27 UTC
Labels: 🐞 bug
