### ISSUE TITLE
Please add socks5 proxy support.

### ISSUE THREAD

**Issue by Alex-coffen** [mozilla-mobile/fenix#14664] opened 2020-09-03 07:03 UTC
Please add socks5 proxy support. Previously it was located in the about:config but it's gone now.

**Comment by freebrowser1** [comment] 2020-09-03 07:59
Another reason to support about:config. I know, that is another issue, but the lack thereof results in a lot of feature requests like this, which area already there, but deliberately disabled requiring re-inventing the wheel.

**Comment by yoasif** [comment] 2020-09-03 16:43
Dupe of https://github.com/mozilla-mobile/fenix/issues/4105

**Closed** 2020-09-10 00:48 UTC
Labels: needs:triage
