### ISSUE TITLE
[Bug] Tapping around "+" on Add-ons manager page opens the details of the add-on page

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#8622] opened 2020-02-21 06:17 UTC
## Steps to reproduce
1. Open Settings - Add-ons and tap around the "+", not exactly on it.

### Expected behavior
Nothing happens. Only tapping on the "+" icon adds the add-on.

### Actual behavior
Tapping around the "+" icon opens the details page of the add-on, which is frustrating.

### Device information
* Android device: Sony Xperia Z2 (Android 6.0.1), Samsung Galaxy Note 8 (Android 9)
* Fenix version: Nightly 2/20 @6:05 PM, Beta v4.0.0-beta.1

![Trim](https://user-images.githubusercontent.com/40694158/75009158-a3465a80-5482-11ea-88be-b7501001289b.gif)

**Comment by Amejia481** [comment] 2020-02-21 13:58
Closing as it is the expected behaviour because the "+" button is inside of he add-on item and clicking the surrounding of the item when the add-on is not installed opens the detail page, see the the image below where you can see the boundaries of each items.

![screenshot-1582293143605](https://user-images.githubusercontent.com/773158/75039849-83fdfc00-5487-11ea-8559-99677f5c8726.jpg)

Feel free to reopen.

**Closed by Amejia481** 2020-02-21 13:58 UTC
Labels: Feature:WebExtensions, S2, needs:triage, 🐞 bug
