### ISSUE TITLE
"Private tab closed" snackbar text in Croatian is not centered

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#16794] opened 2020-11-30 23:01 UTC
## Steps to reproduce
1. Change Fenix language to Croatian.
2. Open a website in new private tab.
3. Close the tab.

### Expected behavior
Snackbar shows up with the text centered.

### Actual behavior
Part of the text is not centered. See screenshot.

Screenshot: https://ibb.co/xjc7PLh

### Device information
* Fenix version: Nightly 201130 17:01

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8928)

**Comment by eliserichards** [comment] 2020-11-30 23:09
I'll test this as part of https://github.com/mozilla-mobile/fenix/pull/16605 🤞

**Comment by anotherus3r** [comment] 2020-12-24 14:39
@eliserichards I noticed the same is happening when Fenix is set to German. Is it because of the length of the string?

**Comment by anotherus3r** [comment] 2021-06-23 10:55
Still an issue on version: 

91.0a1 (Build #2015817867)
AC: 91.0.20210622143139, 669312722f
GV: 91.0a1-20210621213500
AS: 79.0.0

**Comment by SoftVision-LorandJanos** [comment] 2021-12-20 15:56
This issue is no longer reproducible on the latest Nightly 97.0a1 (2021-12-20).
The text looks centered now:
![Screenshot_2022-01-05-17-53-29-058_org mozilla fenix](https://user-images.githubusercontent.com/48829350/146795659-c3815192-a49d-4ba6-a1dd-4a4b57347232.jpg)
Verified with a Xiaomi Mi11 Lite (Android 11).
Closing the ticket as fixed.

**Comment by anotherus3r** [comment] 2021-12-21 16:54
@SoftVision-LorandJanos I can still reproduce it on a Huawei Mate 20 lite on today's (2021-12-21) build.

**Comment by SoftVision-LorandJanos** [comment] 2021-12-23 12:14
Based on the comment above, I will reopen this ticket.
@anotherus3r please share your Android version as well, and if the layout is not exactly as on the screenshot from the description, please update that as well, in a comment. Thank you!

**Comment by anotherus3r** [comment] 2021-12-23 12:18
@SoftVision-LorandJanos 

Android 10 (EMUI 10)

Here's a screenshot from the latest Nightly (2021-12-23):
![Screenshot_20211223_131723.jpg](https://user-images.githubusercontent.com/20287690/147239599-19e755d3-5b4e-41dd-9f29-6141bb4a12a3.jpg)

**Comment by sflorean** [comment] 2022-01-04 16:33
Tested with a Huawei P40 Lite (Android 12) and Samsung A32 (Android 11) and couldn't reproduce the issue.

**Comment by SoftVision-LorandJanos** [comment] 2022-11-17 11:19
@anotherus3r , could you still reproduce the issue?

**Comment by anotherus3r** [comment] 2022-11-17 11:27
> @anotherus3r , could you still reproduce the issue?

Nope, seems to be fixed (though now on EMUI 12).

**Closed** 2022-11-17 11:38 UTC
Labels: 🐞 bug, 🌐 L10N, Feature:Tabs, Feature:Snackbar, S3
