### ISSUE TITLE
[Bug] URL is not always good proposed in URL bar

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6077] opened 2019-10-17 09:21 UTC
## Steps to reproduce
1. open www.dobreprogramy.pl
2. click on URL bar - the whole URL is marked
3. start typing wp.pl

### Expected behavior
The whole URL is replaced and typing starts from beginning of URL

### Actual behavior
Sometimes URL is rendered from the middle and Firefox is proposing some other URL on the end. It looks for me, that it happens the most often when typing is done fast after step 2 (around 1s or less) - probably something is not refreshed fast enough or some event is not sent on time and user is faster.

Note: URLs are only examples, it happens for other combinations too.

### Device information

* Android device: S7
* Fenix version: 2.1.0

**Comment by darkwing** [comment] 2020-02-12 01:02
I haven't been able to reproduce this @marcinwiacek.  Could you provide screenshots, a video, or more detail?

**Comment by darkwing** [comment] 2020-02-15 02:03
@boek You mentioned you had a video or STR here?  Could you post?

**Comment by darkwing** [comment] 2020-02-18 18:33
We can't seem to reproduce this, which means it may be fixed.  I'd love QA on this.

**Comment by LaurentiuApahideanSV** [comment] 2020-02-19 12:51
i tried to reproduce this issue on Beta 4.0.0-beta.1 (Build #20500409) 2/19 using a Samsung Galaxy S5 (Android 6.0.1) and Samsung Galaxy S8+ (Android 8.0.0) but was unable to. The issue seems fixed.

**Comment by darkwing** [comment] 2020-02-19 17:20
On my Pixel 4, repeating these steps, the entire URL is replaced with the search term.

**Comment by codrut-topliceanu** [comment] 2020-02-20 08:37
@LaurentiuApahideanSV It might be related to the keyboard you are using. Could you specify if you are using Swiftkey or some other custom keyboard. I am working on a similar issue https://github.com/mozilla-mobile/fenix/issues/6290

**Comment by LaurentiuApahideanSV** [comment] 2020-02-20 08:44
@codrut-topliceanu The keyboard I used to reproduce the issue is the default Samsung Keyboard.

**Comment by codrut-topliceanu** [comment] 2020-02-20 14:03
@LaurentiuApahideanSV Confirmed (Samsung Galaxy Note 10, Android 10). It's related to the newer Samsung Keyboard. The bug & behaviour is completely [different on swiftkey](https://github.com/mozilla-mobile/fenix/issues/6290#issuecomment-585199163). On Gboard it works as it should.

The root of all of this is the `InlineAutocompleteEditText` android component, which handles the suggestions displayed in the URL editText from the SearchFragment. I did propose a fix in #6290 for Swiftkey, but I don't think it's the right one. We can't fix this on a keyboard by keyboard basis. 

I'll continue working on it so that maybe I can find a single fix that would solve the problems for all keyboards. Though I could really use some input from @csadilek and maybe @mcomella, as they have worked on this component before.

**Comment by jonalmeida** [comment] 2020-05-04 17:32
Looks like @codrut-topliceanu is already working on this. :)

**Comment by codrut-topliceanu** [comment] 2020-05-05 08:27
@jonalmeida offering me as tribute :)))
This should be fixed by https://github.com/mozilla-mobile/android-components/issues/6751 
I am unable to reproduce it anymore. 
I could use confirmation on that though.

**Comment by jonalmeida** [comment] 2020-05-05 10:35
Whoops! I didn't realize that comment we 3 months ago! 😅

**Comment by sv-sdeiac** [comment] 2020-05-06 07:06
Hi, I can confirm that the issue is fixed using the latest version of Firefox Preview Nightly 5/6 #21270609.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9);
-LG G7 fit (Android 8.1).

**Closed by sv-sdeiac** 2020-05-06 07:06 UTC
Labels: Feature:Search, P2, eng:qa:needed, needs:ac, 🐞 bug
