### ISSUE TITLE
Limit Leanplum usage by language (Mirror Fennec)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#6836] opened 2019-11-27 14:02 UTC
Fennec does not enable Leanplum for all users. Instead it uses a Switchboard experiment. The switchboard experiment enables Leanplum only for specific languages, see `leanplum-start`:
https://firefox.settings.services.mozilla.com/v1/buckets/fennec/collections/experiments/records

We should mirror this behavior before migrating Fennec users. Otherwise we add a lot more users to Leanplum and afaik that will cost us a lot of money.

**Comment by st3fan** [comment] 2019-12-11 15:21
@lwa-moz Loren I know you are investigating removing the locale limitation in Fennec, to reach more people _before_ the migration. Can you let us know if that would be temporary or permanent?  Right now this limitation does not exist in Fenix, which would mean that after the migration, the whole user base would be on Leanplum.

@pocmo If we do this then I would suggest to not depend on Switchboard and instead use a hard-coded list. That is a lot simpler, removes some tricky timing issues and may work just as well since we don't really update that list very often.

**Comment by lwa-moz** [comment] 2019-12-11 15:38
It's my understanding that we are limiting our reach in Leanplum by language (regardless of geo). We are enabling Leanplum in Fennec for users who have set their device language to one of the following: EN, ZH, DE, FR, IT, ID, PT, ES, PL, RU

After detailed discussion with the Marketing team, we would like to add the following languages to our list: HI, FA, AR, JA

Adding these countries will give us the best balance of cost, marketing capability (from a localization and campaign implementation standpoint) and reach.

**Comment by Mugurell** [comment] 2020-01-10 08:06
For QA: 
Although this ticket appears on the migration board it is not actually about migrating anything.
We just need Fenix to be available only to a small subset of locales, the same as Fennec. But nothing is migrated from Fennec to Fenix.
So to test this would be useful to just know that indeed Leanplum gets enabled for the locales from https://github.com/mozilla-mobile/fenix/issues/6836#issuecomment-564601017 and not for any others.

**Comment by abodea** [comment] 2020-01-10 16:09
### Hello, note that I tested this issue on the latest Nightly build from **1/10** for more details please check the information from below:

| Locale |  Events displayed?| Total Occurrences modified? |
| :---         |     :---: |  :---: |
|  **"eng", // English**   |  ✅   |      Yes      |
|  **"zho", // Chinese**    |  ✅     |   Yes      |
|  **"deu", // German**    | ✅      |    Yes     |
| **"fra", // French**     |  ✅      |    Yes    |
|  **"ita", // Italian**    |  ✅    |    Yes    |
| **"ind", // Indonesian**    | ✅      |    Yes    |
| **"por", // Portuguese**    | ✅     |    Yes    |
| **"spa", // Spanish; Castilian**   | ✅      |     Yes   |
|  **"pol", // Polish**  |  ✅      |    Yes    |
|  **"rus", // Russian**   |  ✅     |     Yes   |
|  **"hin", // Hindi**   |  ✅     |   Yes     |
| **"per", // Persian**  | ✅    |    Yes    |
| **"fas", // Persian** |  ✅     |  Yes      |
| **"ara", // Arabic** | ✅     |    Yes    |
| **"jpn" // Japanese** |  ✅    |   Yes     |
| **"roa" // Romanian** |  ❌    |   No     |
| **"hun" // Hungarian** | ❌    |   No     |
| **"zul" // Zulu** |  ❌    |   No     |


Little explanation for the table:
```diff 
!Locale = the default locale set on the device and on Fenix Follow device language set.
!Events displayed = Any of the following: 
+Last Active, 
+E_Sign_In_FxA, E_Opened_App, 
+Last Session, 
+E_Interact_With_Search_URL_Area,
+E_Sign_Out_FxA, E_Sign_In_FxA, 
+E_Interact_With_Search_URL_Area, 
+E_Dismissed_Onboarding, 
+E_Opened_App_FirstRun, 
+E_Opened_App, Created
!Total Occurrences modified? = Every time when a supported locale is set, the Total occurances is modified by how many action were performed.
```

```diff 
+Supported locales -English, Chinese, German, French, Italian, Indonesian, Portuguese, Spanish; Castilian, Polish, Russian, Hindi,  Persian, Arabic, Japanese
-Not Supported locales -Romanian, Hungarian, Zulu
```
I tested this with **Google Pixel 3a XL(Android 9), Samsung Galaxy S10+(Android 9).**
Note that for the not **supported** languages there was no update in leanplum campaigns and nothing was registered.
For the **supported** languages, I had to wait between 1-2 minutes after changing the language in order to get the data on leanplum(I believe this is the intended behavior).

Below you can find some segment users in leanplum:
[eng](https://www.leanplum.com/dashboard2/4828751897952256/users/JTdCJTIydHlwZSUyMiUzQSUyMmZpbmQlMjIlMkMlMjJ2YWx1ZSUyMiUzQSUyMmE5OTgyNzBkLTY3YWQtNDM0NC05NWE0LTZiZmRjOWQ5NWUxNiUyMiU3RA==/YTk5ODI3MGQtNjdhZC00MzQ0LTk1YTQtNmJmZGM5ZDk1ZTE2/devices), [persian](https://www.leanplum.com/dashboard2/4828751897952256/users/JTdCJTIydHlwZSUyMiUzQSUyMmZpbmQlMjIlMkMlMjJ2YWx1ZSUyMiUzQSUyMjhlOGNmY2Y3LTkwNjktNDYxNy1hNjk4LTU5ODQ2MGUxZjdlYyUyMiU3RA==/OGU4Y2ZjZjctOTA2OS00NjE3LWE2OTgtNTk4NDYwZTFmN2Vj/devices), [ger](https://www.leanplum.com/dashboard2/4828751897952256/users/JTdCJTIydHlwZSUyMiUzQSUyMmZpbmQlMjIlMkMlMjJ2YWx1ZSUyMiUzQSUyMjdkMmVkNzc5LTg1ODItNDNjYS1hOTcyLTNmZWUzYzRiYzk5OCUyMiU3RA==/N2QyZWQ3NzktODU4Mi00M2NhLWE5NzItM2ZlZTNjNGJjOTk4/devices)

**Another important note, I did with an unsupported language on a Nightly version from 1/7 when the change wasn't made and that language was displayed in leanplum.** Based on this I believe this is 100% fixed.
 
@pocmo @st3fan @lwa-moz looking forward to hearing from you if my verification is enough and if you consider I should close and verify this issue or we can keep it open once we move forward with the migration and maybe redo some tests.

Based on my comment I will remove the `eng:qa:needed` until further notice.

**Comment by liuche** [comment] 2020-01-22 03:54
@lwa-moz @st3fan is this verification enough? If so, we can close this bug.

**Comment by lwa-moz** [comment] 2020-01-22 16:19
@abodea I want to make sure I understand the test process you used.

The update was to ensure that the Leanplum SDK would initialize for users on first launch when their device locale was set to a supported language. As locale verification happens on first launch, each test of the intended behavior with newly supported locales should be conducted with new device profiles. (@st3fan can correct me if this isn't the case)

The appropriate test method to verify this would be to set the device locale to the newly supported locales (HI, FA, AR, JA), run a first launch of Fenix, verify the Leanplum SDK has initialized and user specific data is passed.

**Comment by abodea** [comment] 2020-01-28 08:30
Hello @lwa-moz sorry for the late response, last week I was in PTO.
Yes for each language I did a fresh install and at first launch when the device was set to a supported language a new profile was created.
As you can see here [eng](https://www.leanplum.com/dashboard2/4828751897952256/users/JTdCJTIydHlwZSUyMiUzQSUyMmZpbmQlMjIlMkMlMjJ2YWx1ZSUyMiUzQSUyMmE5OTgyNzBkLTY3YWQtNDM0NC05NWE0LTZiZmRjOWQ5NWUxNiUyMiU3RA==/YTk5ODI3MGQtNjdhZC00MzQ0LTk1YTQtNmJmZGM5ZDk1ZTE2/devices), [persian](https://www.leanplum.com/dashboard2/4828751897952256/users/JTdCJTIydHlwZSUyMiUzQSUyMmZpbmQlMjIlMkMlMjJ2YWx1ZSUyMiUzQSUyMjhlOGNmY2Y3LTkwNjktNDYxNy1hNjk4LTU5ODQ2MGUxZjdlYyUyMiU3RA==/OGU4Y2ZjZjctOTA2OS00NjE3LWE2OTgtNTk4NDYwZTFmN2Vj/devices), [ger](https://www.leanplum.com/dashboard2/4828751897952256/users/JTdCJTIydHlwZSUyMiUzQSUyMmZpbmQlMjIlMkMlMjJ2YWx1ZSUyMiUzQSUyMjdkMmVkNzc5LTg1ODItNDNjYS1hOTcyLTNmZWUzYzRiYzk5OCUyMiU3RA==/N2QyZWQ3NzktODU4Mi00M2NhLWE5NzItM2ZlZTNjNGJjOTk4/devices) there are different profiles for each of the languages(only a few examples) but for each language at first launch I had a new profile.

**Comment by lwa-moz** [comment] 2020-02-03 16:11
Awesome @abodea - sounds like we're all good here then.

**Comment by ebalazs-sv** [comment] 2020-02-12 06:48
This was verified as fixed and confirmed in the previous comments, so I will move this to Done. Thanks!

**Comment by gueroJeff** [comment] 2020-02-14 19:22
I'm seeing inconsistencies between the language codes (apparently non-standard 3 char) used here and the locale codes (standard 2 char lang + region) we actually ship. For example, how are we differentiating messaging and user stats between zh-TW (Traditional Chinese) and zh-CN (Simplified Chinese)? This really is only an issue where we're shipping multiple localizations of the same language (es, zh, and pt) but it's an important distinction for the following reasons:
- It impacts locale conventions users rely on around their language.
- It helps to craft the right message in the right language form for the right users.
- It ensures we have an accurate picture of our users.

**Comment by Mugurell** [comment] 2020-04-30 07:04
Created a new ticket to investigate the next steps as per Jeff's comment - https://github.com/mozilla-mobile/fenix/issues/10314

**Closed by Mugurell** 2020-04-30 07:04 UTC
Labels: E5, Feature:Migration, P2
