### ISSUE TITLE
[Bug]: Webpages jump "up" every so often while scrolling down

### ISSUE THREAD

**Issue by plwt** [mozilla-mobile/fenix#25688] opened 2022-06-20 14:16 UTC
### Steps to reproduce

1. Open https://aphyr.com/posts/358-a-history-of-leather-at-pride-1965-1995
2. Wait for the page to finish loading
3. Slowly scroll down (as if reading the page) 

### Expected behaviour

Page scrolls smoothly.

### Actual behaviour

The page jumps up and is not smooth.

### Device name

Google Pixel 6 Pro (also witnessed on Moto G30)

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

Release 101.2 (also witnessed on Nightly 103)

### Additional information

SUMO Forum question: https://support.mozilla.org/en-US/questions/1380100

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20756)

**Comment by SoftVision-LorandJanos** [comment] 2022-06-21 06:09
Hi @plwt! Thanks for your report!
I couldn't reproduce this issue on the latest Nightly 103.0a1 (2022-06-21) build.
I tried scrolling with different speeds and the behavior was as expected each time.
Tested with the closest device to what this was reproduced with: Google Pixel 4 (Android 12).
Could you make a video of your issue? Thank you!

**Comment by daboross** [comment] 2022-06-23 01:07
Hi! Hope I'm not intruding. I made the original forum question.

I've installed Firefox Nightly version 103.0a1, and reproduced with that on my device, a Pixel 6 Pro.

Full version text:
```
103.0a1 (Build #2015887947), 717e95a2d+
AC: 103.0.20220622143041, 74047eecb6
GV: 103.0a1-20220622094342
AS: 93.5.0
```

Here's a video showing the behavior on that version: https://youtu.be/Y01uwaMSQ1o

The jumping occurs twice, at 0:41 and 1:05.

**Comment by kbrosnan** [comment] 2022-06-24 00:08
Would you try v102 or v103? bz-1659124 was fixed in 102 and may address your problem. https://github.com/mozilla-mobile/fenix/wiki#download

**Comment by plwt** [comment] 2022-06-24 09:25
I was able to replicate in 103 at the time of reporting and am still able to now.  The issue also occurs in 102.

**Comment by daboross** [comment] 2022-06-29 05:56
I've gotten another webpage that reproduces this recorded! The page being https://www.egscomics.com/comic/balance-164. This is the one which I've experienced for at least a year, if not longer, but it seems a lot more intermittent than https://aphyr.com/posts/358-a-history-of-leather-at-pride-1965-1995.

Even if less reproducible, it's also a *lot* more annoying on this page when it does happen, with it jumping up almost every time you reach the bottom of the page, with around 1-4 jumps per second. Here's a video of that: https://youtu.be/OfLukpq8krk

**Comment by grumpypbear** [comment] 2022-12-26 03:10
Hi, has there been a fix or follow-up to this? I'm having similar issues with the latest (and previous) build of FF 108.1.0 (Build #2015920443).

Addons privacy badger and ublock installed. I've tried with them on and off. Enhanced tracking on and off.

Using an Oppo Find x5 Pro, Android.

Video: https://youtube.com/shorts/j5BXYAsSuMA?feature=share

**Comment by jonalmeida** [comment] 2023-01-25 02:28
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812227

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by jonalmeida** 2023-01-25 02:28 UTC
Labels: 🐞 bug, S3, Feature:Browsing, needs:triage, qa-triaged
