### ISSUE TITLE
"Open in app" stopped working

### ISSUE THREAD

**Issue by erikhakansson** [mozilla-mobile/fenix#18223] opened 2021-03-01 01:42 UTC
I'm on Firefox Nightly, and since a few days back, I can no longer open links in external apps.

Links just open in the browser, and the old menu item that could manually force opening of the external app is gone.

I have verified that opening in external apps is on in settings, and I've even force killed FF to rule out temporary error.

Even weird is that when some website has an intent link, FF will open the Play Store app page for that app, even if I already have it installed. Similar to this old issue: https://github.com/mozilla-mobile/fenix/issues/13504

**Comment by hakkikaancaliskan** [comment] 2021-03-01 07:57
Actually duplicate of https://github.com/mozilla-mobile/fenix/issues/18195
Currently firefox nightly targeting Android 11 and that's causing firefox to can't see other installed apps

**Comment by erikhakansson** [comment] 2021-03-01 09:28
Ah, thank you @hakkikaancaliskan. Sounds reasonable. I'll track that issue instead.

**Comment by mcarare** [comment] 2021-03-01 15:38
Keeping this issue open to track this specific issue, not the general package visibility issue in https://github.com/mozilla-mobile/fenix/issues/18195.

**Comment by keegan-lillo** [comment] 2021-03-05 01:09
This is now fixed for me!

Nightly 210304 17:01
Pixel 4 - Android 11 - March 2021 security update.

**Comment by sflorean** [comment] 2021-03-05 13:29
Verified as fixed on Nightly 5/3 with the following devices:
- Pixel 3 (Android 11)
- LG G7 Fit (Android 8.1)

**Closed by sflorean** 2021-03-05 13:29 UTC
Labels: Android:11, Feature:OpenInApp, eng:qa:needed, needs:ac

**Comment by erikhakansson** [comment] 2021-03-05 13:31
Can confirm. Works fine now!
