### ISSUE TITLE
[Bug] fixed bottom toolbat

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#13997] opened 2020-08-20 22:39 UTC
how much longer do we have to wait to have an options for toggling dynamic(bottom) toolbar?
It s being too long since after Firefox preview dynamic toolbar is the only option. I want it FIXED. 
come on!!

**Comment by cadeyrn** [comment] 2020-08-20 22:42
Duplicate of #10240.

**Comment by mcarare** [comment] 2020-08-21 07:52
@ale82to This is included in the work for #10240. Closing this, as the issue will be tracked there.

**Closed by mcarare** 2020-08-21 07:52 UTC
Labels: needs:triage, 🐞 bug
