### ISSUE TITLE
FNX-5179 ⁃ [Bug] URL bar title looks weird

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#1680] opened 2019-04-17 01:00 UTC
## Steps to reproduce
* Load any URL with a title like most pages.

### Expected behavior
* I'm not quite sure (maybe current behavior is expected even), but it does look a bit weird since the descenders of the URL get out of the URL bar. I'd expect a bit of padding.

### Actual behavior
* URL and title are really close to the edges of the box they're in.
* Tapping on the URL and back shows just the URL (again, maybe by design, feel free to close if so).

### Device information
* Android device: OnePlus 6
* Fenix version: Whatever I copied on the previous issue :grinning:

I'm trying to attach screenshots but I haven't been able to. I'm on my phone so I'll try to do it tomorrow.

**Comment by emilio** [comment] 2019-04-17 01:08
![URL bar with title](https://user-images.githubusercontent.com/1323194/56253625-7afd0b00-60bd-11e9-9867-e68e71b18f6d.jpg)

![URL bar without title](https://user-images.githubusercontent.com/1323194/56253718-dfb86580-60bd-11e9-9ae4-2432681656ac.jpg)

 Heh, attaching files works in fennec :)

**Comment by kbrosnan** [comment] 2019-04-17 02:07
Dupe of #1637

**Comment by emilio** [comment] 2019-04-17 08:47
Ah, thanks! Looked for a dupe in the open issue list, not closed :)

**Closed** 2020-08-11 12:29 UTC
Labels: 🐞 bug
