### ISSUE TITLE
[Bug]: problem with push notification 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#27494] opened 2022-10-21 14:27 UTC
### Steps to reproduce

so this is my third attempt to get push notifications fixed in fenix even tought I have zero trust now.
the situation is as follow :
push notification for some websites (youtube with desktop userAgent ,telegram ,Twitter )are working just fine .
For other websites (FACEBOOK ,INSTAGRAM REDDIT ) are in a limbo :
let me explain more ...at first I tought they did not work at all ,since I'm very stubborn (unluckily for me ) I monitored logcat for :
"AbstractFirebasePushService: Processing message with chId"
and since I ve got root i ve looked for Id in push.sqlite under profile folder and with big surprise I saw that Facebook Instagram and reddit was sending push (logcat writing :AbstractFirebasePushService: Processing message with chId: 16digit number corresponding to website )just FINE ,they just WON'T SHOW UP  in fenix app .
can please someone explain if this is fenix fault or a webcompat issue I ve invested too much time and energy in fenix and I'm seriously considering switching to better alternative .

### Expected behaviour

Push notification in 2022 are important and should just work without all this trouble .

### Actual behaviour

push for facebook Instagram and reddit are not working right 

### Device name

poco F3 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

107

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21844)

**Comment by AdinaPetridean** [comment] 2022-10-26 12:09
@ale82to  Thanks for filing this! I will close this as duplicate of https://github.com/mozilla-mobile/fenix/issues/26998, please follow the discussion there.

**Closed** 2022-10-26 12:09 UTC
Labels: 🐞 bug, needs:triage
