### ISSUE TITLE
Unable to pay with PayPal on GOG.com [webcontent]

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#4918] opened 2019-08-25 13:47 UTC
## Site with issue and any steps to reproduce

* GOG.com and PayPal.com

Steps to reproduce:
1. Open GOG.com
2. Add a game to cart
3. Go to checkout
4. Choose PayPal as payment method and tap Pay with PayPal

### Expected behavior

Should open a PayPal page where I can choose a card and check out. In Firefox Nightly opens about:blank and proceeds to open PayPal page where I can check out.

### Actual behavior

Opens about:blank and doesn't do anything.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)

No.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?

Works in latest Firefox Nightly as expected. Haven't checked in stable Firefox for Android.

### Device information

* Android device: 9.0 Pie
* Fenix version: 1.3.1 (Build #12341950)

**Comment by 0xdec** [comment] 2019-09-05 16:26
I can reproduce this issue when trying to pay with PayPal on REI.com, RevZilla.com, and probably others that I am forgetting. Works for me in Firefox Nightly and Beta for Android.
Device: OnePlus 5T, OxygenOS 9.0.7
Fenix: 1.3.1

**Comment by Idesmi** [comment] 2019-11-07 06:13
This still happens, exactly as described by @anotherus3r

**Comment by kglazko** [comment] 2020-04-20 18:03
I can reproduce this on lovekinship.com, this does not reproduce in Fennec. On Pixel 4.

**Comment by ekager** [comment] 2020-04-27 21:37
Confirmed that turning off ETP doesn't help. Looks like it tries to open this in a new window and something goes wrong. 🤔

**Comment by karlcow** [comment] 2020-05-08 07:08
@ekager it seems there is a pattern of blank page opening when there is a need for a login on a third party site. 
For example https://github.com/webcompat/web-bugs/issues/52447

**Comment by Mugurell** [comment] 2020-05-20 14:04
This seems to happen because we get a WindowRequest.Type.OPEN with an empty url [here](https://github.com/mozilla-mobile/android-components/blob/3814f42c80cd9c126595f8f215587e7906d118a1/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/WindowFeature.kt#L49) this being called by GeckoSession#onNewSession with an empty uri [here](https://github.com/mozilla-mobile/android-components/blob/36896e190e88eafc965f55b4c5053491d198f4f3/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L431).
So we open and load a new session with an empty uri.. and then.. nothing.
Seems like a GV issue with nothing actionable on Fenix / a-c side.

Since this is also happening in geckoview_example I filed a new bug in Bugzilla - https://bugzilla.mozilla.org/show_bug.cgi?id=1639577

**Comment by amedyne** [comment] 2020-07-23 20:25
Fixed on GV80. (https://bugzilla.mozilla.org/show_bug.cgi?id=1639577)

**Comment by abodea** [comment] 2020-07-27 11:34
Verified as fixed on the latest Nightly build 7/27 with Google Pixel 4 XL (Android 11).

![20200727-135541](https://user-images.githubusercontent.com/42831109/88537437-442ed800-d016-11ea-9570-a2b805e6b1cd.gif)

**Closed by abodea** 2020-07-27 11:34 UTC
Labels: S2, b:web-content, eng:qa:needed, needs:gv, 🐞 bug
