### ISSUE TITLE
FNX-13764 ⁃ [Bug] Weird graphic glitch on the "+" button of the tabs tray

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12662] opened 2020-07-17 11:11 UTC
## Steps to reproduce
1. Open a few tabs 
1. Then swipe the tabs tray up and down continuously
1. See the square looking graphic glitch on the "+" button in the tabs tray.

See the screenshots.

### Expected behavior
No glitches on the "+" button in the tabs tray

### Actual behavior
Graphic Glitches on the "+" button in the tabs tray

### Device information
* Android device: Motorola One Power, Android 10
* Fenix version: Nightly 200714 18:01

![Screenshot](https://user-images.githubusercontent.com/68282543/87780382-417cf780-c84c-11ea-951f-bedb8d9ce410.jpg)UNITO-UNDERSCORE!20200717!UNITO-UNDERSCORE!163404.jpg!![Screenshot](https://user-images.githubusercontent.com/68282543/87780391-480b6f00-c84c-11ea-92ec-8f3509c5caef.jpg)UNITO-UNDERSCORE!20200717!UNITO-UNDERSCORE!163318.jpg!

**Comment by ekager** [comment] 2020-07-17 13:01
Dupe of #11180

**Closed** 2020-08-11 06:57 UTC
Labels: needs:triage, 🐞 bug
