### ISSUE TITLE
[Bug] Crash on launch

### ISSUE THREAD

**Issue by mirdaki** [mozilla-mobile/fenix#7630] opened 2020-01-12 20:49 UTC
## Steps to reproduce

When opening the app directly from the home screen or via another app, Firefox Preview crashes within a couple seconds. It also will randomly crash in the background while I use the device.

I have cleared the cache and storage of the app with no change. The same has started occurring for [Firefox Focus](https://github.com/mozilla-mobile/focus-android/issues/4458) as well. Let me know if I can provide any more information.

### Expected behavior

The browser loads the webpage and allows me to interact with it.

### Actual behavior

The app displays a white screen then crashes within a couple of seconds.

Once every 15 to 60 seconds Firefox Preview will display a crash dialog, even if I haven't interacted with it.

### Device information

* Android device: OnePlus 5, OxygenOS 9.0.9, Build Number ONEPLUSA5000_23_191008
* Fenix version: 3.0.2

**Comment by sv-ohorvath** [comment] 2020-01-13 10:22
@mirdaki Does this still reproduce and can you get a logcat? https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by abodea** [comment] 2020-01-14 15:54
>sv-ohorvath commented yesterday
@mirdaki Does this still reproduce and can you get a logcat? https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information
--
Hello, note that I tried to reproduce this issue on the following builds and devices:
- **Firefox Preview Latest Nightly 1/14 GV 74**
- **Firefox Preview Beta 3.1.0-beta.3 GV 7**
- **Firefox Preview RC 3.0.2 GV 71** 
- **Firefox Focus 8.025(Build #340092236) GV 71**
---------------------------------------------------
- **OnePlus 6T(Oxygen OS 9.0.1)**
- **Google Pixel 3a XL(Android 10)**

Note that I was not able to reproduce the issue, I will keep an eye for this while testing and come back with more information in case I can reproduce it.

**Comment by mirdaki** [comment] 2020-01-14 16:59
@sv-ohorvath and @abodea, here is a [gist](https://gist.github.com/mirdaki/406d195331e1a011629e1cb33a67188e) with the Firefox Preview crashes. I have one log file for the launch then crash and another file for the background crashes I've seen. Let me know if they were captured properly and if I can do anything else to help.

**Comment by mirdaki** [comment] 2020-01-19 19:51
Thanks to some [additional information](https://github.com/mozilla-mobile/focus-android/issues/4458#issuecomment-575957306) @bthylafh posted, I can confirm that the issue only affects me when I use the OpenVPN setting from ProtonVPN 2.0. It does not happen when I use IKEv2 in ProtonVPN 2.0 or when I use PIA VPN. This seems related to #7803.

**Comment by bthylafh** [comment] 2020-01-29 21:00
This bug seems to have been fixed with Fenix v3.2.0.

**Comment by ekager** [comment] 2020-01-30 15:17
Closing for #7803

**Closed by ekager** 2020-01-30 15:17 UTC
Labels: b:crash, 🐞 bug
