### ISSUE TITLE
"Delete browsing data" doesn't remove all data for the current open tab on Firefox for Android 90.1.2

### ISSUE THREAD

**Issue by arminfuerst** [mozilla-mobile/fenix#20476] opened 2021-07-23 08:44 UTC
### Steps to reproduce

1. Ensure having following setting:
    * "Delete browsing data on quit" -> Yes
    * "Open tabs" -> checked
    * "Browsing history and site data" -> unchecked
    * "Cookies" -> checked
    * "Cached images and files" -> unchecked
    * "Site permissions" -> checked
    * "Downloads" -> unchecked
2. Open "maps.google.com", on "consent.google.com":
    * click "Customize"
    * "Search customization" -> Off
    * "YouTube History" -> Off
    * "Ad personalization on Google Search" -> Off
    * "Ad personalization on YouTube & across the web" -> Off
    * click "Confirm"
3. Scroll the map to a random place being different to the place google selects automatically and remember this place.
4. From the FF-menu, select "Quit"
5. Restart FF
6. Open "maps.google.com"

### Expected behaviour

Consent dialog appears, maps starts with the location calculated by google.

### Actual behaviour

Google Maps starts directly (no consent.google.com) and displays the place selected in 3.
The deletion of browsing data generally is working, it's just not working reliably when using "Quit". To verify this, use following steps:
1. Do steps 1 to 3 from "Steps to reproduce"
2. Close tab
3. Select "Settings"
4. Select "Delete browsing data"
5. Have following options activated
    * Open tabs
    * Cookies
    * Site permissions
6. Click "Delete browsing data" and confirm
7. Open "maps.google.com"
As a result, the consent dialog reappears.
A similar bug might be that the steps described in "Actual beaviour" do not work when the tab is open (omitting step 2).

### Device name

Motorola moto g(6)

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

90.1.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17338)

**Comment by Amejia481** [comment] 2021-07-23 19:08
Are you able to reproduce on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) ? We fixed some related issues.

**Comment by arminfuerst** [comment] 2021-07-23 19:19
> Are you able to reproduce on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) ? We fixed some related issues.

I just made a short test with 92.0a1 (Build #2015823817) and it seems to work properly there.

**Comment by arminfuerst** [comment] 2021-07-23 19:27
What I can reproduce with nightly is the bug I mentioned in "Actual Behaviour":
1. Open "maps.google.com" on "consent.google.com":
    * click "Customize"
    * "Search customization" -> Off
    * "YouTube History" -> Off
    * "Ad personalization on Google Search" -> Off
    * "Ad personalization on YouTube & across the web" -> Off
    * click "Confirm"
2. Scroll the map to a random place being different to the place google selects automatically and remember this place.
3. Select "Settings"
4. Select "Delete browsing data"
5. Have following options activated
    * Open tabs
    * Cookies
    * Site permissions
6. Click "Delete browsing data" and confirm
7. Open "maps.google.com"

Expected Result: Redirection to "consent.google.com"
Actual Result: Google Maps starts directly (no consent.google.com) and displays the place selected before.

Shall I file this as a new bug or do you want to track it here?

**Comment by Amejia481** [comment] 2021-07-23 19:48
Thanks for testing!
We can continue using this one, can you help me to clarify the step 1. Open "maps.google.com" on "consent.google.com": 
I'm not able navigate to consent.google.com, I always get a 404.

**Comment by arminfuerst** [comment] 2021-07-23 20:31
You get the 404 if you call consent.google.com directly. On a clear browser (not logged in to Google, no cookies, probably you have to disable Add-ons like "Consent Blocker", "I don't care about cookies", ...), when you open maps.google.com, you are redirected to consent.google.com with some parameters (e.g. https://consent.google.com/m?continue=https://www.google.com/maps&gl=HR&m=0&pc=m&hl=en&src=1). When you configure FF to always delete all cookies, etc. you are always redirected to this page).
Is now clear what I mean?

**Comment by Amejia481** [comment] 2021-07-26 13:27
Thanks for the clarification. We are going to take a look.

**Comment by sassospicco** [comment] 2021-08-10 13:51
I noticed the same unexpected behavior and would like to add some details.

First: the problem is not limited to the _current open tab_, as this issue's title implies. The same behavior is experienced also if the Google Maps tab is closed before quitting Firefox.

Second: it would seem the cause is Firefox not clearing Local Storage and Indexed DB data.
For example, in arminfuerst's Google Maps example, the current location is saved in _Indexed DB > google.com > maps-ml > kv_.
As another example, Google Search history is saved in _Local Storage > google.com >msuggest.history..history_ and similarly persisted after quitting.

In a way, this behavior is to be expected, since in the settings we are keeping unchecked _Browsing history and site data_.
When checking it, Indexed DB and Local Storage are indeed cleared and the behavior is the expected one.

However, I humbly suggest to take this opportunity to review the _Delete browsing data on quit_ categories, specifically the _Browsing history and site data_ and the _Cookies_ ones.
I feel that the _site data_ bit (at least Local Storage and Indexed DB, I do not know if the term covers other kinds of data) is much closer (both technically and in its purpose) to the _Cookies_ category than to the _Browsing history_ one.
The categories could be reorganized as _Browsing history_ and _Cookies and site data_.

My objective as an end user, in using this feature, is basically: "Please Firefox, remember where I have been (_browsing history_), but interact with the websites just like the first time, deleting everything they saved in my phone (_cookies and site data_)".
As of now, if I want to keep my browsing history, I have to accept that [zombie cookies](https://en.wikipedia.org/wiki/Zombie_cookie) will persist.

**Comment by arminfuerst** [comment] 2021-08-10 14:19
@sassospicco: Did you try this with the stable version or the nightly build? It seems to me you are describing my original issue. When you look at the comments from July 23rd, you will notice we already reduced this issue to the one existing in nightly.

**Comment by sassospicco** [comment] 2021-08-10 14:54
Sorry for the confusion.
I was indeed describing your original issue (clearing data on Quit), but I am sorry to report that I get the same behavior in both ways (_Delete browsing data_ and _Delete browsing data on quit_) while using Nightly (92.0a1, build 2015827083): Google Maps still starts directly and displays the place selected before.

If I check _Browsing history and site data_ (while deleting or while setting up delete-on-quit), everything goes as expected (I get the consent page and the automatic location).

**Comment by arminfuerst** [comment] 2021-08-10 18:05
I just retested this and this might be another tweak. To get the consent-redirect again, I also have to delete "Browsing history and site data". Probably "site data" is the same as "Offline Website Data"? In this case, this setting should be separated, because I want to keep my browsing history, but to protect my privacy (probably only a little better...) I want to remove the "Offline Website Data".
Can someone confirm my assumption that the "site data" in "Browsing history and site data" means "Offline Website Data"?

**Comment by sassospicco** [comment] 2021-08-11 14:27
Yes @arminfuerst, this is what I was saying with my first comment.

I experimented a little more and checked the source. The _site data_ part means:

1. Cache storage
2. Indexed DB
3. Local storage and Session storage

Relevant code:

- [DeleteBrowsingDataController.deleteBrowsingData()](https://github.com/mozilla-mobile/fenix/blob/6a3adb5aeba976a7146eb96a2ef3794fae909304/app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataController.kt#L48)
- [SystemEngineSession.clearData()](https://github.com/mozilla-mobile/android-components/blob/71e124a5dbafffb800168ea615fdbc54d7398f50/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt#L188)
- [WebStorage.deleteAllData()](https://developer.android.com/reference/android/webkit/WebStorage#deleteAllData())

I agree with you: these items should be separated from _browsing history_, just like they are on Firefox for desktop.
Yesterday, I was also suggesting an alternative, to keep down the number of settings: a single _cookies and site data_ option.

**Comment by arminfuerst** [comment] 2021-08-14 07:26
I just made a search and found this change is already requested in issue #16798, so I suggest we focus here on the bug that the "Delete browsing data" doesn't work (reliably) on the open tab. Since Google seems to have switched from just storing the consent-data in a cookie, we should find a better way to reproduce - any suggestions are welcome...

**Comment by arminfuerst** [comment] 2021-08-15 17:10
I just created a very simple page to help reproduce this bug:
[https://www.fuerst.priv.at/test20476.html](https://www.fuerst.priv.at/test20476.html)
I learned that the bug I assumed doesn't exist, it must have been a combination of other facts leading me to my assumption.
When trying my test page you can observe that:
* Cookies are properly deleted when exiting Firefox and having configured it like described above
* Data in local storage is kept and can only be deleted when also deleting the browser history (which is very uncomfortable)

This behaviors can be reproduced in the recent version of Firefox for Android (91.1.0) as well as in the most recent Firefox Nightly for Android (93.0a1, Build #2015827753)
I suggest we close this bug as there is already a ticket for enabling the deletion of local storage without deleting the browser history - any objections?

**Comment by arminfuerst** [comment] 2022-02-11 18:20
> See: #17373 This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

I didn't provide further input because in my opinion everything is clear here. In my opinion, this issue is also critical as currently it's very uncomfortable to use Firefox when you care about privacy.
I am sure, many users are interested in improving the situation and - even worse - many FF users chose it because of privacy and don't even know how broken it is at the moment.
I currently can't use FF on my mobile phone as I would have to delete too much data. Since it is connected to my Sync-Account, it would delete data from my desktop computers.
As a workaround, I'm only using FF Nightly on my mobile phone at the moment and delete all data every time I close it. I'd like to keep bookmarks and the browsing history as it is very uncomfortable not to have both available.
What is expected from me to avoid getting this (in my opinion important) issue to be continued?

**Comment by Amejia481** [comment] 2022-02-14 19:36
Just to confirm, that I'm following the right idea. If we separate the following clear settings **browsing history** and **site data**, the issue will be fixed right? 

We will end up having two different  additional cleaning options:

* **Browsing history**
* **Site data**

instead of only one :

* **Browsing history and site data**

**Comment by arminfuerst** [comment] 2022-02-14 20:09
If I understand "Browsing history" and "site data" correctly, then we agree, probably it is better to describe it additionally.
On my Desktop Firefox, I checked following for "Clear history when Firefox closes":
[X] Active Logins
[X] Forms & Search History
[X] Site Preferences
[X] Offline Website Data
"Cookies": I don't delete them on my Desktop through this option, but by using the Add-On "Cookie AutoDelete", which has two advantages:
1. I don't have to close Firefox to remove all cookies, closing all relevant tabs is sufficient.
2. I can define some websites I prefer to remember cookies even when restarting Firefox.

Since this Add-On is not available on Firefox for Android anymore (it used to...), I would activate deleting Cookies and hope it won't change my setting through the Sync on Firefox on my Desktops.
I hope, it is easy to understand what I am suggesting. Feel free to ask in doubt.

**Comment by Amejia481** [comment] 2022-02-14 20:27
> closes

Sorry, would you mind indicating how do you get to this settings page? Thanks in advance!

**Comment by arminfuerst** [comment] 2022-02-14 20:33
I assume you are asking for the settings on the desktop I was trying to explain what I suggest for fenix.

- On Linux, this is Edit -> Settings or by typing ```about:preferences``` into the URL bar
- On the left side select "Privacy & Security"
- Scroll down to "History"
- Check "Clear history when Firefox closes"
- Click "Settings..." right to the line
![image](https://user-images.githubusercontent.com/29121472/153941865-c7a44be8-6a49-4532-8cf9-28412a97b898.png)
And this should open following pop-up:
![image](https://user-images.githubusercontent.com/29121472/153941929-34d33649-0850-4de6-9150-fb21a1af9645.png)

**Comment by arminfuerst** [comment] 2022-02-15 16:48
Thanks for caring about my suggestion :)

**Comment by arminfuerst** [comment] 2022-11-23 06:47
There is no activity because I think everything is documented good enough and I'm waiting for the bug to be fixed.

**Comment by csadilek** [comment] 2023-01-20 21:49
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811601

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2023-01-20 21:49 UTC
Labels: 🐞 bug, needs:triage
