### ISSUE TITLE
[Bug] Name Collection flickers on Save to collection

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7561] opened 2020-01-09 09:01 UTC
## Steps to reproduce
Press save to collection on 3 dot menu on a webpage
### Expected behavior
save to collection menu appears
### Actual behavior
save to collection menu appears but the title "Name Collection" flickers
### Device information

* Android device: Asus Zenfone M1
* Fenix version: Nightly 200109 06:02 (Build #20090616)
28.0.0, 11219297f
GV: 74.0a1-20200107215758

**Comment by topotropic** [comment] 2020-03-16 12:17
duplicate of https://github.com/mozilla-mobile/fenix/issues/7734

**Closed by topotropic** 2020-03-16 12:17 UTC
Labels: Feature:Collections, 🐞 bug
