### ISSUE TITLE
Delay when opening the first page after opening Firefox for Android (ublock?)

### ISSUE THREAD

**Issue by Mohan40** [mozilla-mobile/fenix#16473] opened 2020-11-10 07:42 UTC
## Steps to reproduce
Close the browser and reopen it. Visit a website.

### Expected behavior
Display the website immediately without any delay.

### Actual behavior
Display that the website has an Insecure Connection and Firefox waits for 8-10 seconds with a white background and then displays the page.
This only happens for the first page visited after opening Firefox. All pages open normally after the first page delay.
Add-ons : HTTPS Everywhere and uBlock Origin.

![firefox](https://user-images.githubusercontent.com/43498254/98644085-f7b5a100-2355-11eb-9d47-626f7a7b82c1.png)

### Device information
Xiaomi Mi A1 (LineageOS) and Xiaomi Mi A3(Stock)

* Android device: 10
* Fenix version: 82.1.3

**Comment by mcomella** [comment] 2020-11-13 17:24
@Mohan40 Are you able to reproduce the delay without ublock? If so, we're aware of an issue with slow first page loads with ublock https://github.com/mozilla-mobile/fenix/issues/8251 but we're unable to do any more about – it would be ideal if you could report this to the ublock developers.

We felt the insecure connection was an unrelated issue so I filed a separate ticket for that: https://github.com/mozilla-mobile/fenix/issues/16558 Let's only discuss the delay in this bug.

**Comment by Mohan40** [comment] 2020-11-14 05:12
Hi @mcomella .
I tried to reproduce the problem in different scenarios:
1). Only with uBlock: 7-8 seconds delay.
2). Only with HTTPS Everywhere: 10 seconds delay.
3). With both uBlock and HTTPS Everywhere: 8-10 seconds delay.
4). **Without using any extensions: 1-2 seconds delay or no delay.**

I think the problem is not specific to uBlock.
I also tried out the new TOR browser based on fenix. It too has the same problem(Extensions: HTTPS Everywhere and NoScript)
![tor](https://user-images.githubusercontent.com/43498254/99140227-e0ccc280-2665-11eb-83f7-8edeb28fffd9.jpg)

**Comment by mcomella** [comment] 2020-12-02 22:57
Triage: we were able to reproduce with HTTPSEverywhere and ublock but not other add-ons. We still believe it's likely to be the code run by the add-ons (i.e. there's nothing we can do). One thing we can check is if we can reproduce the same delay in fennec. If so, then it's more evidence that it's due to code run by the add-ons and the issue should be filed against the specific add-ons. If not, we should file an issue against GeckoView because this is a regression.

**Comment by Neon329** [comment] 2020-12-19 03:59
This happens with **AdGuard** extension as well. The delay when loading the page for the first time after opening Firefox and loading a website (and in custom tabs) is almost 8 to 10 seconds. After the first page loads it is much faster. Something must be done otherwise nobody would be willing to wait for 10 seconds each time they open Firefox or a custom tab and they'll think that it is a Firefox problem. Recommended Extensions are officially supported in Firefox after all. The problem is mainly with content blockers as far as I have experienced. **I only have AdGuard extension installed.**

**Comment by Dunexus** [comment] 2020-12-19 09:34
Probably related to https://github.com/mozilla-mobile/fenix/issues/17138

**Comment by mcomella** [comment] 2021-01-13 22:56
> One thing we can check is if we can reproduce the same delay [in fennec](https://archive.mozilla.org/pub/mobile/releases/68.9.0/)...

I filed https://github.com/mozilla-mobile/fenix/issues/17448 to do this action.

**Comment by Cheap-Skate** [comment] 2021-01-14 14:28
prob dup of

https://github.com/mozilla-mobile/fenix/issues/8251

Still not clear to me if/when uBO caches its filter lists and whether that should make a difference to cold start. Cold start with uBO is pretty slow on Fenix on an entry level phone. Depends on number of filters eg 200k filters takes a few seconds longer than 20k filters.

IIRC Fennec & Fenix are similarly slow but haven't checked for a while.

I think your Fennec vs Fenix test is well worth doing. I would also like to hear anything about filter list caching????

cheers & let me know if I can help

**Comment by csadilek** [comment] 2021-01-21 19:44
Closing as this only reproduces with add-ons and we investigated in https://github.com/mozilla-mobile/fenix/issues/17448.

Unfortunately, there doesn't seem to be anything more we can do other than making the specific add-ons themselves initialize faster. Please see the linked ticket for details. If you have ideas or see something we might have missed please comment there.

**Closed by csadilek** 2021-01-21 19:44 UTC
Labels: eng:performance, needs:triage
