### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by minecraftchest1** [mozilla-mobile/fenix#20827] opened 2021-08-12 21:37 UTC
### Steps to reproduce

Behavior is not always consistent or reproducible. The behavior most often happens when going to a login form that asks for a 2fa code, open the Microsoft Authenticator app, copy the OTP code, and go back to Firefox to pate the code.

This behavior sometimes happens when opening a new page.
 

### Expected behaviour

The page should just re-display.

### Actual behaviour

The page is black. Sometimes going back displays the previous page and I can open the link again. However, sometimes this behavior happens until I restart the browser.

### Device name

Samsung a10e SM-A102U

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

91.0.0-beta.5

### Device logs

None

### Additional information

[Original Message] https://matrix.to/#/!kJaSGGXicbqyevMnKy:mozilla.org/$VeujhlKf5vLymhsWFM73jt6dYzKhbIPsYqk6tQrhoP8?via=mozilla.org&via=matrix.org&via=privacytools.io

Hello. I have Firefox Beta 91.0.0-beta.5 on my Samsung a10e, and I have noticed that sometimes when opening a link, or opening a link then switching applications causes the page to load to a black screen. Sometimes I can get it to load by going to the previous page then following the link, but just as often, all of my previous pages in that tab behave the same way.

Where would be the place to report this issue? I did not see a spot on either the support page, or bugzilla.

![image](https://user-images.githubusercontent.com/42992675/129271887-df06adb5-7c48-4bf8-b127-6128e467b772.png)

**Comment by kbrosnan** [comment] 2021-08-12 22:55
Mali GPU makes this a likely duplicate of https://github.com/mozilla-mobile/fenix/issues/20733 

Would you try our [nightly build](https://play.google.com/store/apps/details?id=org.mozilla.fenix) and see if that fixes your problem?

**Closed by kbrosnan** 2021-08-12 22:55 UTC
Labels: 🐞 bug, needs:triage

**Comment by minecraftchest1** [comment] 2021-08-14 01:51
I installed Firefox nightly just now and the issue came up when using keepass2android to sign into firefox.

Firefox nightly 93.0a1

**Comment by minecraftchest1** [comment] 2021-09-23 01:46
I found that this issue also occurs when firefox is used as webview component (i believe its what its called), switch to a different app, and come back.
