### ISSUE TITLE
FNX-5432 ⁃ [Bug] Phantom history items

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#2065] opened 2019-04-26 05:07 UTC
## Steps to reproduce
* Unclear but  something to do with clearing history not cleaning up everything

### Expected behavior
* items history and bookmarks should be used for address bar autocomplete

### Actual behavior
* items that are not in history or bookmarks were autocompleted

https://www.youtube.com/watch?v=t6jj_AMybNM

### Device information
* Android device: Pixel 3
* Fenix version: 99f979e86b4fcd9ad494357c519f20ebfe654da6

**Comment by grigoryk** [comment] 2019-04-26 18:21
Interesting. Did you clear data at some point prior? I don't think we expose clearing yet in the UI, do we?

We're filtering history before displaying it in the UI, and the suggestions are powered by a different places API endpoint. Perhaps there's some misalignment there.

**Comment by kbrosnan** [comment] 2019-04-26 21:52
Yes, I cleared just prior to seeing this.

**Comment by sv-ohorvath** [comment] 2019-05-17 13:36
Can't reproduce: tried with clear data before clearing new history, tried syncing and clearing history, but didn't succeed. @kbrosnan, have you seen this issue again or should we close it?

**Comment by cadeyrn** [comment] 2019-05-17 13:43
I can reproduce - I deleted my history a few moments ago and Fenix still suggests websites from my old history.

**Comment by cadeyrn** [comment] 2019-05-17 13:47
I deleted my full history a few moments ago, deleted all bookmarks and closed all open tabs. Fenix still suggests one website which was in my history before. But other websites from my old history are not suggested.

**Comment by sarentz** [comment] 2019-05-29 18:07
@grigoryk what do you think?

**Comment by ekager** [comment] 2019-08-02 02:53
@kbrosnan do you remember if you had been signed in in the original report? I cannot reproduce this on my own device. I'm wondering if it's a strange bug because `historyStorage.deleteEverything()` only deletes local entries, and possibly if you had been logged in and something hadn't synced yet that could be the cause of the phantom item appearing?

**Comment by kbrosnan** [comment] 2019-08-02 03:21
I don't know for sure. I think I was not signed into sync.

**Comment by jdragojevic** [comment] 2019-09-03 19:02
@vesta0 @bifleming - is this still reproducible?

**Comment by bifleming** [comment] 2019-09-04 17:14
@kbrosnan can we reproduce this or can we close it?

**Closed** 2020-08-11 13:48 UTC
Labels: Feature:History, a-s, 🐞 bug, 🙅 waiting
