### ISSUE TITLE
FNX-5433 ⁃ [Bug] Opening AMP links from Bing in new tabs results in blank pages.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2066] opened 2019-04-26 05:09 UTC
## Steps to reproduce
Search a current event on Bing (It's recommended that Bing is set to US -English)
Open some AMP news links in new tabs

### Expected behavior
The pages are loaded in the newly opened tabs

### Actual behavior
The pages are not loaded most of the time, instead a blank pages is exhibited

### Device information
* Android device: 8.0
* Fenix version: 1.0.1917

**Comment by sv-ohorvath** [comment] 2019-05-17 12:24
I can't reproduce this on any of: Note 8( Android 9), P20 lite (Android 8), P9 lite (Android 6)
build: 5/17.
@Lululalu have you experienced this lately?

**Comment by Lululalu** [comment] 2019-05-17 14:23
@sv-ohorvath I tried again and this is not reproducing for me anymore. Although the AMP top bar is cut now. It's like it's hidened behind the OS top bar.

**Comment by sv-ohorvath** [comment] 2019-05-20 06:57
@Lululalu yes, please file a new bug. I'll close this and please reopen it if you see the issue again.

**Closed** 2020-08-11 13:48 UTC
Labels: b:web-content
