### ISSUE TITLE
[Bug] (Leanplum) Deep-Link schemes need to be unique per release channel

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#7661] opened 2020-01-13 21:50 UTC
We recently fixed the following bug in Fennec:

> https://bugzilla.mozilla.org/show_bug.cgi?id=1601729

Summarized, the problem is as follows: if multiple applications (like Firefox Nightly, Beta, Release) all register that they can handle the `firefox://` intent scheme, it becomes unpredictable which app will be opened when we send for example a Leanplum notification that uses that deep-link scheme. Even if the notification itself is directly targeted to a specific release channel.

Fenix has [this same problem](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/AndroidManifest.xml#L71-L98). All build flavors register the `fenix://` scheme.

In Fennec we are fixing this by introducing unique `firefox-nightly://` and `firefox-beta://` schemes. This gives every channel a unique non-conflicting intent scheme.

Something similar should be done in Fenix. Until we do, deep-linking through for example something like Leanplum is unpredictable and may not work for a group of users and our internal testers.

Cc @lwa-moz 

### Steps to reproduce:
 1. Install the release app.
 2. Send intent from the command-line: 
`adb shell am start -a android.intent.action.VIEW -d fenix://settings`
 3. Install the nightly app.
 4. Send intent from the command-line: 
`adb shell am start -a android.intent.action.VIEW -d fenix-nightly://settings`
 5. Ensure the release and nightly apps are both still installed on the device.
 6. Send intent from command-line again: 
`adb shell am start -a android.intent.action.VIEW -d fenix://settings`

### Expected:
 - At step 2, you should see the settings screen open in the release app.
 - At step 4, you should see the settings screen open in the **nightly** app.
 - At step 6, you should see the settings screen open in the release app again.

At no point should you see a screen like the one below:

<img width="532" alt="Screen Shot 2020-02-27 at 1 41 25 AM" src="https://user-images.githubusercontent.com/1370580/75502681-930e0e00-59a1-11ea-9683-049596142403.png">

**Comment by jonalmeida** [comment] 2020-01-17 20:49
Going to work on this next sprint.

**Comment by liuche** [comment] 2020-03-18 18:12
This landed now - how should we test this @lwa-moz, @jonalmeida ? If you want QA to test it, please add a label, with steps to test.

This would currently be in Nightly only, but we could as them to build a different release flavor as well.

**Comment by AndiAJ** [comment] 2020-03-19 15:17
Hi, I've just checked this using a Google Pixel 3a (Android 10)

## ✔️   Having **installed only** **`Fenix RC 4.0.0`** 
adb shell am start -a android.intent.action.VIEW -d fenix://settings
► Video
![20200319-162755](https://user-images.githubusercontent.com/51314259/77080324-d89e8380-6a01-11ea-875a-00437c2d09bb.gif)

## ❌ Having **installed** **`Fenix Beta 4.1.0-beta2`** 
adb shell am start -a android.intent.action.VIEW -d fenix://settings
► Video
![20200319-165357](https://user-images.githubusercontent.com/51314259/77080864-827e1000-6a02-11ea-943f-40eb1ea18249.gif)

## ❌ Having **installed** **`Fenix RC 4.0.0`** & **`Fenix Beta 4.1.0-beta2`** 
adb shell am start -a android.intent.action.VIEW -d fenix://settings
► Video
![20200319-163740](https://user-images.githubusercontent.com/51314259/77080367-e48a4580-6a01-11ea-98d5-2ba3090c5fb9.gif)

## ✔️ Having **installed `all of the above mentioned builds`** & **`Nightly Build #200790605 from 3/19`** 
adb shell am start -a android.intent.action.VIEW -d fenix-nightly://settings
► Video
![20200319-162904](https://user-images.githubusercontent.com/51314259/77080503-05eb3180-6a02-11ea-92c7-940930da4c6d.gif)

@liuche - Please review and advise on how should we proceed with this ticket?
Just to be sure we won't overlook testing it on Beta ☺️

**Comment by jonalmeida** [comment] 2020-03-25 05:33
> ❌ Having installed Fenix RC 4.0.0 & Fenix Beta 4.1.0-beta2
> adb shell am start -a android.intent.action.VIEW -d fenix://settings

Yes, this should fail because with beta you need to use `fenix-beta://settings` for only the beta app to open.

> ❌ Having installed Fenix Beta 4.1.0-beta2
> adb shell am start -a android.intent.action.VIEW -d fenix://settings

We should look at fixing this. `fenix://` should only work with release builds. I might have missed a build variant.

**Comment by jonalmeida** [comment] 2020-03-25 21:12
This is fixed in Nightly and needs to be in beta until we can test it. Leaving out the qa label until then.

**Comment by jonalmeida** [comment] 2020-07-21 16:24
This should be in beta now but never followed up on adding the QA label when it reached.

**Comment by AndiAJ** [comment] 2020-07-27 11:52
Hi @jonalmeida I've re-checked this matter using a Google Pixel 3a (Android 10)

❓ The Fenix Nightly package name got changed to **`org.mozilla.fenix`** hence if I use **`adb shell am start -a android.intent.action.VIEW -d fenix://settings`** it **will open the Nightly build** 
**`adb shell am start -a android.intent.action.VIEW -d fenix-nightly://settings`** doesn't work anymore

❌ Using **`adb shell am start -a android.intent.action.VIEW -d fenix://settings`** while having the latest Nightly build and the RC 79.0.0 build will open the app selector 

► Video
![20200727-144732](https://user-images.githubusercontent.com/51314259/88538733-8b1dcd00-d018-11ea-9529-a675cea4c18b.gif)

✔️ Using **`adb shell am start -a android.intent.action.VIEW -d fenix-beta://settings`** properly opens Firefox Beta 79.0.0-beta.8 from 7/17 

**Please review and share your thoughts**

**Comment by jonalmeida** [comment] 2020-07-27 14:39
> ❌ Using **`adb shell am start -a android.intent.action.VIEW -d fenix://settings`** while having the latest Nightly build and the RC 79.0.0 build will open the app selector

Thanks this looks like a regression from a build simplification that removed the nightly flags. I've filed https://github.com/mozilla-mobile/fenix/issues/12983 to track this.

**Closed** 2020-07-28 14:44 UTC
Labels: Leanplum, 🐞 bug
