### ISSUE TITLE
FNX-483 ⁃ [Bug] Pasting extremely-long data URI in the address bar will hang Fenix

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#1824] opened 2019-04-19 17:26 UTC
## Steps to reproduce
1. In Fenix, load about:telemetry.
1. Click the "Raw JSON" link.
1. Before the JSON finishes loading, press the Android Back button.

### Expected behavior
In Fennec and Focus+GV, the JSON data is loaded in the browser or you are given the open to open in a JSON Viewer app.

### Actual behavior
Fenix hangs while trying to load the JSON data.

If I kill the Fenix process and launch it again, Fenix will still hang. Perhaps the Fenix home screen is trying to show the JSON data in the list of recent sessions? I had to uninstall and reinstall Fenix to make it stop hanging.

### Device information
* Android device: Moto G5 Plus
* Fenix version: 

I originally filed this bug against GV in Bugzilla: "Loading about:telemetry's Raw JSON data will hang Fenix, even after restarting the app". But bholley's conclusion was that:

* The hang doesn't actually require visiting the page, just putting the extremely-long data URI in the URL bar is sufficient. As such, I'm pretty sure the bug involves some exponential URL text processing in Fenix.
* This worked fine on an older Fenix build I had installed, but I got the hang after upgrading. So this is a recent regression.
* It's not actually a hang, just a very long period of jank. It recovers (and displays the JSON as text) in about 2.5 minutes. The Gecko threads in the parent and content processes seem idle and responsive.

https://bugzilla.mozilla.org/show_bug.cgi?id=1542410

**Comment by karlcow** [comment] 2019-10-02 04:04
This seems to be a duplicate of #1681 
and we have a webcompat issue which is related except it is not pasting but navigating to.
on nasa Website https://github.com/webcompat/web-bugs/issues/39953

**Comment by MarcLeclair** [comment] 2019-12-02 19:42
From looking at this, #1681 is a REGEX / a "schema" that should always be "denied" ( also from A-C) which we already have rules set up for "about" ( which would work if you type in about:networking#networkID but not about:networking).

As for the Nasa Website bug ( nasa Website [#39953]( https://github.com/webcompat/web-bugs/issues/39953) the issue stems from Android Component redirecting a Data URI ( as pointed out in that issue, the href is assigned a base64 string) which 1) creates an intent and then 2) tries to start an activity with an image in the bundle which creates a TransactionTooLargeException.

**Comment by MarcLeclair** [comment] 2019-12-06 21:26
The root cause of this issue is from the fact that we don't truncate the URL which we use to do in Fenix ( from browser.js). I believe this is more something the Toolbar component should handle instead of Fenix. For more information regarding this bug ( trace file, possible solution, and reproduction of my own test case) please refer to  #5249

**Comment by mcomella** [comment] 2020-01-07 23:19
@MarcLeclair Can this issue be closed or is there additional work needed to close it?

**Comment by csadilek** [comment] 2020-05-21 17:41
OK, tested and verified this is fixed now on master after patches linked above landed.

**Closed** 2020-08-11 13:03 UTC
Labels: Feature:Toolbar, P2, S3, eng:performance, perf:onboarding-issue, 🐞 bug

**Comment by poseidon2060** [comment] 2022-12-09 11:42
Hey @MarcLeclair, I was solving issue #28094 where I am supposed to write tests for a function that shortens URI to `MAX_URI_LENGTH` which is equal to 25000 characters, I saw you mention this issue and you gave this example https://github.com/MarcLeclair/DataURIStaticTestPage/blob/master/index.html in which there is a long URI on line 42

I need a long URI to write my test, can you please guide me on how to obtain it?
I am new to Android Dev and Open Source so I don't have a lot of experience, your help will be precious.

**Comment by MarcLeclair** [comment] 2022-12-09 15:52
Hey @poseidon2060 , I would suggest to just encode a large picture to `base64` which, if I remember correctly, is what I did for this issue. I believe the JSON uri in that file  (line 42) is the one I'm referring to 😄

**Comment by poseidon2060** [comment] 2022-12-10 06:28
Thankyou that worked 😄
