### ISSUE TITLE
FNX3-16903 ⁃ [Bug] Black square artifacts on page when using WebRender

### ISSUE THREAD

**Issue by vorticalbox** [mozilla-mobile/fenix#3270] opened 2019-06-07 19:25 UTC
## Steps to reproduce
Opening a website scroll and stop

### Expected behavior
No black squares rendered

### Actual behavior
Black squares are rendered on screen in a seemingly random distribution

### Device information
* Android device: Samsung s8
* Fenix version: 1.0.1923
![Screenshot](https://user-images.githubusercontent.com/10886065/59128600-683ae000-8962-11e9-8bb3-0899ee16fad2.jpg)UNITO-UNDERSCORE!20190607-184004!UNITO-UNDERSCORE!Firefox Preview!

**Comment by cpeterso** [comment] 2019-06-10 19:15
This looks like a Gecko Graphics bug.

Do the black square appear on every web page or just randomly?

**Comment by vorticalbox** [comment] 2019-06-10 20:44
On most websites it seems to be mostly around text and div boarders

**Comment by cpeterso** [comment] 2019-06-11 01:45
Thanks. I filed a new bug in Graphics team's Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1558374

**Comment by jamienicol** [comment] 2019-06-12 14:25
Hi @vorticalbox, can you reproduce this on regular Firefox for android, or just Fenix? Could you attach the contents of your about:support page? (Go to about:support in the address bar, then click "copy text to clipboard" and paste it here.) Thanks.

**Comment by vorticalbox** [comment] 2019-06-12 14:42
It's only on fenix

```
{
  "application": {
    "name": "Fennec",
    "osVersion": "Linux 28",
    "version": "68.0b7",
    "buildID": "20190604110028",
    "userAgent": "Mozilla/5.0 (Android 9; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0",
    "safeMode": false,
    "supportURL": "https://support.mozilla.org/1/mobile/68.0/Android/en-GB/",
    "numTotalWindows": 0,
    "numRemoteWindows": 0,
    "remoteAutoStart": false,
    "autoStartStatus": 2,
    "keyLocationServiceGoogleFound": true,
    "keySafebrowsingGoogleFound": true,
    "keyMozillaFound": true
  },
  "securitySoftware": {
    "registeredAntiVirus": "",
    "registeredAntiSpyware": "",
    "registeredFirewall": ""
  },
  "processes": {
    "remoteTypes": {
      "web": 1
    },
    "maxWebContentProcesses": 1
  },
  "modifiedPreferences": {
    "browser.cache.disk.amount_written": 946575,
    "browser.cache.disk.capacity": 524288,
    "browser.cache.disk.filesystem_reported": 1,
    "dom.presentation.device.name": "SM-G950F",
    "extensions.lastAppVersion": "68.0",
    "general.useragent.updates.lastupdated": "1559224936303",
    "gfx.webrender.all": true,
    "idle.lastDailyNotification": 1560271634,
    "media.gmp.storage.version.observed": 1,
    "network.predictor.cleaned-up": true,
    "security.remote_settings.intermediates.checked": 1559673173,
    "storage.vacuum.last.index": 0
  },
  "lockedPreferences": {},
  "media": {
    "currentAudioBackend": "opensl",
    "currentMaxAudioChannels": 2,
    "currentPreferredSampleRate": 48000,
    "audioOutputDevices": [
      {
        "name": "",
        "groupId": "",
        "vendor": "",
        "type": 2,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 16,
        "maxChannels": 2,
        "defaultRate": 44100,
        "maxRate": 44100,
        "minRate": 41000,
        "maxLatency": 410,
        "minLatency": 128
      }
    ],
    "audioInputDevices": [
      {
        "name": "",
        "groupId": "",
        "vendor": "",
        "type": 1,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 16,
        "maxChannels": 1,
        "defaultRate": 44100,
        "maxRate": 44100,
        "minRate": 41000,
        "maxLatency": 410,
        "minLatency": 128
      }
    ]
  },
  "javaScript": {
    "incrementalGCEnabled": true
  },
  "accessibility": {
    "isActive": true,
    "forceDisabled": 0,
    "handlerUsed": false,
    "instantiator": ""
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.21",
      "version": "4.21"
    },
    "NSS": {
      "minVersion": "3.44",
      "version": "3.44"
    },
    "NSSUTIL": {
      "minVersion": "3.44",
      "version": "3.44"
    },
    "NSSSSL": {
      "minVersion": "3.44",
      "version": "3.44"
    },
    "NSSSMIME": {
      "minVersion": "3.44",
      "version": "3.44"
    }
  },
  "userJS": {
    "exists": false
  },
  "intl": {
    "localeService": {
      "requested": [
        "en-GB"
      ],
      "available": [
        "an",
        "ar",
        "ast",
        "az",
        "be",
        "bg",
        "bn",
        "br",
        "bs",
        "ca",
        "cak",
        "cs",
        "cy",
        "da",
        "de",
        "dsb",
        "el",
        "en-CA",
        "en-GB",
        "en-US",
        "eo",
        "es-AR",
        "es-CL",
        "es-ES",
        "es-MX",
        "et",
        "eu",
        "fa",
        "ff",
        "fi",
        "fr",
        "fy-NL",
        "ga-IE",
        "gd",
        "gl",
        "gn",
        "gu-IN",
        "he",
        "hi-IN",
        "hr",
        "hsb",
        "hu",
        "hy-AM",
        "id",
        "is",
        "it",
        "ja",
        "ka",
        "kab",
        "kk",
        "kn",
        "ko",
        "lij",
        "lo",
        "lt",
        "lv",
        "ml",
        "mr",
        "ms",
        "my",
        "nb-NO",
        "ne-NP",
        "nl",
        "nn-NO",
        "oc",
        "pa-IN",
        "pl",
        "pt-BR",
        "pt-PT",
        "rm",
        "ro",
        "ru",
        "sk",
        "sl",
        "son",
        "sq",
        "sr",
        "sv-SE",
        "ta",
        "te",
        "th",
        "tr",
        "trs",
        "uk",
        "ur",
        "uz",
        "vi",
        "wo",
        "xh",
        "zam",
        "zh-CN",
        "zh-TW"
      ],
      "supported": [
        "en-GB",
        "en-US",
        "en-CA"
      ],
      "regionalPrefs": [
        "en-GB"
      ],
      "defaultLocale": "en-US"
    },
    "osPrefs": {
      "systemLocales": [
        "en-GB"
      ],
      "regionalPrefsLocales": [
        "en-GB"
      ]
    }
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "graphics": {
    "numTotalWindows": 2,
    "numAcceleratedWindows": 2,
    "windowLayerManagerType": "WebRender",
    "windowLayerManagerRemote": true,
    "windowUsingAdvancedLayers": false,
    "adapterDescription": "Model: SM-G950F, Product: dreamltexx, Manufacturer: samsung, Hardware: samsungexynos8895, OpenGL: ARM -- Mali-G71 -- OpenGL ES 3.2 v1.r16p0-01rel0.###other-sha0123456789ABCDEF0###",
    "adapterVendorID": "ARM",
    "adapterDeviceID": "Mali-G71",
    "adapterRAM": "",
    "adapterDrivers": "",
    "driverVendor": "",
    "driverVersion": "OpenGL ES 3.2 v1.r16p0-01rel0.###other-sha0123456789ABCDEF0###",
    "driverDate": "",
    "usesTiling": true,
    "contentUsesTiling": true,
    "offMainThreadPaintEnabled": false,
    "offMainThreadPaintWorkerCount": 0,
    "targetFrameRate": 60,
    "webgl1Renderer": "ARM -- Mali-G71",
    "webgl1Version": "OpenGL ES 3.2 v1.r16p0-01rel0.###other-sha0123456789ABCDEF0###",
    "webgl1DriverExtensions": "GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_EGL_image_array ",
    "webgl1Extensions": "ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_disjoint_timer_query EXT_sRGB OES_element_index_uint OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_lose_context",
    "webgl1WSIInfo": "EGL_VENDOR: Android\nEGL_VERSION: 1.4 Android META-EGL\nEGL_EXTENSIONS: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_config_attribs EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_mutable_render_buffer EGL_EXT_protected_content EGL_IMG_context_priority EGL_KHR_no_config_context ",
    "webgl2Renderer": "ARM -- Mali-G71",
    "webgl2Version": "OpenGL ES 3.2 v1.r16p0-01rel0.###other-sha0123456789ABCDEF0###",
    "webgl2DriverExtensions": "GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_EGL_image_array ",
    "webgl2Extensions": "EXT_color_buffer_float EXT_disjoint_timer_query WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context",
    "webgl2WSIInfo": "EGL_VENDOR: Android\nEGL_VERSION: 1.4 Android META-EGL\nEGL_EXTENSIONS: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_config_attribs EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_mutable_render_buffer EGL_EXT_protected_content EGL_IMG_context_priority EGL_KHR_no_config_context ",
    "info": {
      "AzureCanvasBackend": "skia",
      "AzureFallbackCanvasBackend": "none",
      "AzureContentBackend": "skia",
      "ApzTouchInput": 1,
      "ApzAutoscrollInput": 1,
      "TileHeight": 512,
      "TileWidth": 512
    },
    "featureLog": {
      "features": [
        {
          "name": "HW_COMPOSITING",
          "description": "Compositing",
          "status": "force_enabled",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "user",
              "status": "force_enabled",
              "message": "Force-enabled by pref"
            }
          ]
        },
        {
          "name": "OPENGL_COMPOSITING",
          "description": "OpenGL Compositing",
          "status": "force_enabled",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "user",
              "status": "force_enabled",
              "message": "Force-enabled by pref"
            }
          ]
        },
        {
          "name": "WEBRENDER",
          "description": "WebRender",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "opt-in",
              "message": "WebRender is an opt-in feature"
            },
            {
              "type": "user",
              "status": "available",
              "message": "Force enabled by pref"
            }
          ]
        },
        {
          "name": "WEBRENDER_QUALIFIED",
          "description": "WebRender qualified",
          "status": "blocked-vendor-unsupported",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "env",
              "status": "blocked-vendor-unsupported",
              "message": "Unsupported vendor"
            }
          ]
        },
        {
          "name": "OMTP",
          "description": "Off Main Thread Painting",
          "status": "disabled",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            }
          ]
        }
      ],
      "fallbacks": []
    },
    "crashGuards": []
  },
  "extensions": [],
  "features": []
}
```

**Comment by jamienicol** [comment] 2019-06-12 14:46
Great, thanks! It looks like you've enabled webrender? If you set gfx.webrender.all to false in about:config does it go away?

**Comment by vorticalbox** [comment] 2019-06-12 14:58
Would love to try but about:config just returns a white page

https://i.postimg.cc/cL4MTn49/Screenshot-20190612-155738-Firefox-Preview.jpg

**Comment by cpeterso** [comment] 2019-06-12 20:54
> Would love to try but about:config just returns a white page

Fenix support for about:config has been temporarily disabled. To reset your `gfx.webrender.all` preference, you might need to clear Firefox Preview's storage data in Android's system settings: Storage > Other apps > Firefox Preview > CLEAR DATA button.

Note that this will cause Fenix to forget your browsing history and saved passwords!

**Comment by jamienicol** [comment] 2019-06-12 21:23
No need to wipe your data @vorticalbox, I think it's safe to assume this is a webrender bug.

**Comment by vorticalbox** [comment] 2019-06-13 08:16
> No need to wipe your data @vorticalbox, I think it's safe to assume this is a webrender bug.

Always better to check than to guess, cleared my data and issue is gone. Must be a webrender bug

**Comment by kbrosnan** [comment] 2019-06-29 20:21
Closing as there is no fix in the code that the Fenix project owns. Similar issues should be reported against [GeckoView](https://bugzilla.mozilla.org/enter_bug.cgi?product=GeckoView)

**Comment by yoasif** [comment] 2020-01-07 06:16
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1558374

**Closed** 2020-08-20 22:55 UTC
Labels: P2, needs:gv, 🐞 bug
