### ISSUE TITLE
FNX-12885 ⁃ Change order of new tab contextual menu entries

### ISSUE THREAD

**Issue by amkcpu** [mozilla-mobile/fenix#11885] opened 2020-06-24 12:06 UTC
### What is the user problem or growth opportunity you want to see solved?
In #10374, a contextual menu has been added when long-pressing the tab icon. The order is currently (from button to top) 1. new private tab 2. new tab 3. close.
While I really like the menu, I would prefer to have the "new tab" entry at the bottom of the list. That way, I do not have to move my finger when opening a new tab, but only tap once more, and arguably one opens way more "normal" tabs than private ones.

### How do you know that this problem exists today? Why is this important?
Contextual menu introduced in #10374. This makes opening new tabs easier.

### Who will benefit from it?
All users opening normal tabs more frequently than private tabs --> basically everyone.

**Comment by cadeyrn** [comment] 2020-06-24 12:12
Duplicate of #11677.

**Comment by mcarare** [comment] 2020-06-24 12:28
Closing as duplicate of #11677.

**Closed** 2020-08-11 05:08 UTC
Labels: needs:triage
