### ISSUE TITLE
[Bug] PWA not recognized as such if not at root of domain

### ISSUE THREAD

**Issue by creesch** [mozilla-mobile/fenix#7298] opened 2019-12-19 20:50 UTC
## Steps to reproduce

1. Go to https://demo.thelounge.chat/
2. Check the firefox menu for PWA installation.
3. Install PWA 
4. Connect to an IRC server (note that the url of this PWA changes to add the channel name)
5. Check the firefox menu again for PWA installation.
6. Install PWA

### Expected behavior

In step 2 and step 5 the menu gets a nice blue icon indication that a PWA can be installed and the "*add to homescreen*" text is changed to "*install*". 

In step 3 and step 6 it both installs as a fullscreen PWA.

(This is how it currently also works in fennec)

### Actual behavior

Only in step 2 and step 3 it is recognized as a PWA. Step 5 and 6 add it to the homescreen as a regular webpage shortcut. 

### Device information

* Android device: Nokia 7 plus with android 9
* Fenix version: Nightly 191219 18:00 (Build #13531804) 26.0.0, 8b955ae06

**Comment by NotWoods** [comment] 2019-12-20 02:30
I know that we can install PWAs that are not at the root of the domain, so I suspect that this is caused by The Lounge using the History API and changing the URL without reloading. I'll investigate, this might need a GeckoView change.

**Comment by abodea** [comment] 2020-01-29 09:32
Verified as fixed on the latest nightly from 1/29 with Samsung Galaxy S10+(Android 9).

**Closed by abodea** 2020-01-29 09:32 UTC
Labels: Feature:PWA, P2, eng:qa:needed, 🐞 bug

**Comment by creesch** [comment] 2020-01-29 12:43
Can confirm that it is also works for me, thanks!
