### ISSUE TITLE
[Bug] logs from previous builds are being displayed in taskcluster

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#12398] opened 2020-07-08 20:40 UTC
## Steps to reproduce
Notes from @AaronMT in taskcluster [Riot](https://matrix.to/#/!whDRjjSmICCgrhFHsQ:mozilla.org/$4rEDaIfM0uReoXjvtiB_Ybi0vTZUEEL1K7K_GupZjCI?via=mozilla.org&via=matrix.org):
possible caching issue going on in the fenix repo on Github. When I click on a job e.g, https://github.com/mozilla-mobile/fenix/runs/850484116, the logs for a different run are showing up. E.g, in lint-ktlint and ui-test-x86-debug here: https://github.com/mozilla-mobile/fenix/runs/850484083

@callek @tomprince based on chat in Riot, I believe we need to use a different image here, but I didn't see there was a conclusion on which one that might be. Can you point us to the right one?  With the wrong logs mapping, folks won't be able to debug any testing/build issues.

**Comment by tomprince** [comment] 2020-07-08 23:39
This is caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1595808#c15 and should be fixed by updating to the docker-image there.

**Comment by JohanLorenzo** [comment] 2020-07-13 13:39
Hey @rpappalax! 

Thanks for filing this issue. I don't have the full context, but I can say https://github.com/mozilla-mobile/fenix/pull/12407 landed and should address this issue. I'm going to close this ticket.

Please let me know if you keep seeing this bug!

**Closed** 2020-08-28 22:07 UTC
Labels: eng:automation, eng:ui-test, needs:triage, 🐞 bug
