### ISSUE TITLE
Unable to send tab to specific device

### ISSUE THREAD

**Issue by Shaurya-Kalia** [mozilla-mobile/fenix#28035] opened 2022-11-30 18:10 UTC
I have number of devices synced with single firefox account.

On trying to send tab to a device through latest nightly browser, I can only see 3 devices and an option to send to all devices.

I do not wish to send tab to all devices, but the device i wish to send the tab to is not listed in the share menu.

This was not the case earlier as the device list was scrollable (in horizontal direction).

If possible, restore the older behaviour as it is a regression

![photo_2022-11-30_23-38-01](https://user-images.githubusercontent.com/6441797/204875234-10c477ad-9957-4a8a-8524-893768b4b090.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22086)

**Comment by kbrosnan** [comment] 2022-11-30 19:10
Are you able to see the other devices on https://accounts.firefox.com/settings?

**Comment by Shaurya-Kalia** [comment] 2022-11-30 20:23
The device I wished to send to is using nightly on desktop linux. The device does show up in account settings. However strangely, it shows last login with the device as 1 year ago. I sent a tab from that desktop to a different device and it got sent, though last login is still stuck at 1 year ago. Nonetheless, I have 9 devices but only 3 are shown as above

**Comment by tarikeshaq** [comment] 2022-11-30 22:49
Hi @Shaurya-Kalia! We recently changed that send tab list to only include devices active in the past 21 days to help filter duplicates and idle devices. However, the fact that the device still says that its last login is 1 year ago is the bug here. 

One workaround is to sign out and sign back into your desktop device, which should create a new device entry with an accurate date - but I'd love to get behind why the device's access time is not updated. I'll create a bug in bugzilla to track it (as it's most likely a desktop or firefox accounts server bug) and link it here.

In the meantime, do your other devices have accurate last access times in the account settings?

**Comment by Shaurya-Kalia** [comment] 2022-12-01 15:51
I signed out and signed in with pc that was showing incorrect time since last login. Now it shows the correct time. I have now 4 devices showing in 'send to device' screen. So I am to assume that this number would rise indefinitely provided that devices have been synced within 21 days?

**Comment by tarikeshaq** [comment] 2022-12-01 17:30
Yes, that's correct - The list will show signed-in devices as long as they have been active in the last 21 days, if you sign out or stop using the device for 21 days they will be omitted, but will show up again once used

**Comment by razzeee** [comment] 2022-12-04 19:39
I've been living with this bug for some time now and finally decided to figure out what this is all about. I've tied to relogin on the mobile phone, but that didn't help, reading the above I now know why. 

I should be getting three devices instead of none.

![markup_2542.png](https://user-images.githubusercontent.com/5943908/205511579-1eb19904-62e1-4f5e-8af7-54d7745e3e5f.png)

I'm not convinced the design to not show any connected devices is user friendly.

**Comment by mans0n** [comment] 2022-12-14 15:50
I've also experienced this bug in recent days. I'd connected two desktops (stable) and one android device (nightly) on single firefox account, and I'm actively using all of them. And few weeks ago, I found out that desktops do not show up anymore on "send to device" list from android. Interestingly, I could still see the android device (and even its tabs) from desktop. (don't clearly remember about the last access time though)

And by chance I opened up my firefox account page (and fiddled some options) from one desktop, and that desktop started to show up on android. And this trick worked for the other desktop.

Hope this helps.

**Comment by tarikeshaq** [comment] 2022-12-14 16:39
Thank you @mans0n for the report, this helps! What operating systems are both of your desktop devices on (i.e windows/mac/linux)

You shouldn't need to go to the settings page, so this is most definitely a bug. I opened https://github.com/mozilla-mobile/fenix/issues/28035 since this is a server bug. We still need to identify the trigger for this though, as I am unable to reproduce

**Comment by razzeee** [comment] 2022-12-14 16:47
I'm only on linux desktops.

**Comment by tarikeshaq** [comment] 2022-12-14 17:03
Closing this issue since I filed it in https://bugzilla.mozilla.org/show_bug.cgi?id=1805700 , if anyone else comes across this, please comment there - I'll use that bug for tracking

**Closed by tarikeshaq** 2022-12-14 17:03 UTC
Labels: needs:triage

**Comment by razzeee** [comment] 2022-12-31 11:10
I lost some devices that I had to rediscover some time ago, so it seems to also affect newly registered ones.

**Comment by assarbad** [comment] 2023-01-24 20:10
> And by chance I opened up my [firefox account page](https://accounts.firefox.com/settings) (and fiddled some options) from one desktop, and that desktop started to show up on android. And this trick worked for the other desktop.
> 
> Hope this helps.

@mans0n  Same here. Your trick helped to get it to show the Linux desktop device again from Fennec and Firefox on Android. Thank you!
