### ISSUE TITLE
[Meta] AdBlocking

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#96] opened 2018-12-04 19:31 UTC
### Why/User Benefit/User Problem
- As a user, I want to not be distracted by ads

### What / Requirements
- Integrate/support for different adblock lists (see Focus)

### Acceptance Criteria (how do I know when I’m done?)
- See Focus, ads are not loaded and are blocked

**Comment by bbinto** [comment] 2019-03-18 11:11
As per [comment](https://github.com/mozilla-mobile/fenix/issues/240#issuecomment-473414507), we might pull this back into a Battery saving story after MVP, however it should land for MVP as an individual feature.

**Comment by PsudoEyes** [comment] 2019-07-24 04:49
The absence of Ad-blocker is a fatal for us to enjoy Firefox-preview.

**Comment by marekdedic** [comment] 2019-08-05 09:18
Shouldn't this better be left to add-ons like uBlock and AdBlock? With support for plugins hopefully coming, what is the reason for implementing this in the browser itself?

**Comment by creesch** [comment] 2019-08-13 09:27
Indeed, it seems to me that when #574 is implemented it also automatically resolves this userstory.

**Comment by maverick74** [comment] 2019-08-14 22:21
The  reason for this to ship in Firefox itself, instead of an add-on is that many users do not know about add-on support.

Most does not even know what an add-on is. They just install the browser and get on with it.

This should be in Firefox itself, if you ask me!

Still, add-on support in Firefox Mobile, should be more marketed!!!

**Comment by jcdickinson** [comment] 2019-08-14 23:01
Extension support is a much larger story than adblocking. Native adblocking is a quick win, especially considering that many potential beta testers could be holding out for this specific feature.

**Comment by robsmith11** [comment] 2019-09-02 21:03
Is it really a good idea to push adblocking to a broader user base?  If it's built into the browser (especially if enabled by default), it could cause problems in the longterm.

Adblocking is only viable because the majority of users don't know or bother with it.  If they did, then websites would start using ads that are more difficult to block or even shift their revenue models.

**Comment by jgoguen** [comment] 2019-09-02 21:31
Extension support would be a greater win. But the browser should probably have a basic blocking role. Offer tracking protection like the desktop browser and default deny anything known to be serving malicious code (if there's some good metric for that), but for actual ad blocking leave that to extensions.

**Comment by ChriKn** [comment] 2019-09-27 09:37
Brave browser demonstrated that people are willing to jump on a new browser for the sake of "easy to use privacy and ad-blocking". It's a shame they did this on the Chrome engine, giving Google ever more power over the internet.
The sad truth is, that on mobile you want an as hassle-free experience as possible.
I can't teach every person in my entourage how to install plugins and what they are, so I just let them use brave in the meantime.
Fenix seems to have the potential to change this. At least make it optional.

**Comment by marekdedic** [comment] 2019-09-27 10:41
@ChriKn Well, that's true. For my 2¢, I think if extensions were supported, having preinstalled uBlock or something like that (that can be removed of course) would probably be an easy win without having to re-engineer the same thing. But I'm just a "passerby" commenter :laughing:.

**Comment by cadeyrn** [comment] 2019-09-27 10:58
> having preinstalled uBlock or something like that 

There is not only one ad blocker for Firefox. Preinstalling an arbitrary ad blocker would be really bad for the competition of ad blockers and therefore for the whole add-on ecosystem of Firefox.

**Comment by marekdedic** [comment] 2019-09-27 11:00
That's true, but wouldn't the same hold for implementing a built-in ad blocker?

**Comment by cadeyrn** [comment] 2019-09-27 11:14
Of course you can argue with the question: _Why should users install an ad blocker if Fenix already has ad blocking capabilities?_

But for me there is one important difference: add-ons can always make things different. They can provide more features because a built-in feature will probably have a stronger focus on the average user and don't include all features you can think of. There is a fair competion because no add-on developer is preferred. This will not hurt the add-on ecosystem. But preinstalling an add-on means making a choice for one third party developer and against all competitors. With a built-in adblocker and uBlock already included there is probably no point for users to install any similar add-on.

**Comment by marekdedic** [comment] 2019-09-27 11:26
> a built-in feature will probably have a stronger focus on the average user and don't include all features you can think of

I agree...
> There is a fair competion because no add-on developer is preferred.

I disagree, Mozilla would be preferred...

But overall, I probably agree with you that it would hurt competition *more* to select a 3rd party developer instead of a 1st party one.

**Comment by ChriKn** [comment] 2019-09-27 11:30
Solution is easy, give a good third party option that can be disabled and replaced by a third-party one of the desire arises.

(The problem is probably that Google (the n°1 money source of Mozilla) would lose its mind/it is part of their agreement...)

**Comment by ReekyMarko** [comment] 2020-02-04 23:26
uBlock can be installed now so that should close this issue.

**Comment by jgoguen** [comment] 2020-02-04 23:43
@ReekyMarko since when? Is there a new version that hasn't hit the Play Store yet? I've got the latest Play Store version and neither uBlock Origin (the proper one) nor the top "uBlock" results say they're compatible (and can't be installed).

**Comment by ReekyMarko** [comment] 2020-02-04 23:47
It was just updated a couple of hours ago. Installing from addons.mozilla.org does not work yet.

You should have at minimum `Nightly 200204 18:00 (Build #20351804)`. Then you should have "Add-ons" under Settings -> Advanced and you can install uBlock origin from there.

**Comment by creesch** [comment] 2020-02-05 08:54
This has hit nightly, meaning it is still not released to the regular firefox preview and under test.

**Comment by ReekyMarko** [comment] 2020-02-05 08:58
Oh I just assumed everyone here is running Nightly. Might be that @jgoguen is running the stable version.

**Closed** 2020-02-24 19:24 UTC
Labels: Feature:Adblocking, 🌟 feature request
