### ISSUE TITLE
FNX-508 ⁃ [Bug] Netflix movie selection non-functional

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#2169] opened 2019-04-30 15:41 UTC
* Visit Netflix and sign-in with an active account.
* Attempt to tap on any movie title to select a movie. Nothing happens.
* Further attempt to long-tap and open any movie title in a new tab (loads a blank page)

04/30 (Pixel 2, Android 9)

**Comment by vesta0** [comment] 2019-05-03 17:06
@cpeterso is this GV related?

**Comment by cpeterso** [comment] 2019-05-03 18:17
I filed a new GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1548906

The STR work correctly in Fennec, but I can reproduce the problem in Fenix, RB, and Focus+GV. So this is a GV bug.

**Comment by AaronMT** [comment] 2019-05-03 23:03
Depends on https://github.com/mozilla-mobile/android-components/issues/1132

**Comment by cpeterso** [comment] 2019-05-04 01:46
> Depends on [mozilla-mobile/android-components#1132](https://github.com/mozilla-mobile/android-components/issues/1132)

Removing the "Needs GV work" because this is an A-C bug, not a GV bug.

**Comment by sblatz** [comment] 2019-07-01 19:47
This will require us to implement https://github.com/mozilla-mobile/fenix/issues/3223

**Comment by AndiAJ** [comment] 2019-10-31 08:51
Hi, **still reproducible** on the latest **Nightly Build #13040608 from 31/10** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)

► Video
![20191031_104358](https://user-images.githubusercontent.com/51314259/67932326-5afde680-fbcc-11e9-999e-34e9419ac134.gif)


► Log
`2019-10-31 10:49:11.184 767-1045/? I/CHRE: @ 4289.143: [AR_CHRE] still: 100
2019-10-31 10:49:12.336 12371-12371/? D/GeckoSession: handleMessage GeckoView:OnLoadRequest uri=https://www.netflix.com/title/80133311
2019-10-31 10:49:12.353 12371-12371/? D/GeckoSession: handleMessage GeckoView:ProgressChanged uri=null
2019-10-31 10:49:12.370 12371-12371/? D/GeckoSession: handleMessage GeckoView:PageStart uri=https://www.netflix.com/title/80133311
2019-10-31 10:49:13.372 12371-12371/? D/GeckoSession: handleMessage GeckoView:StateUpdated uri=null
2019-10-31 10:49:14.383 767-1045/? I/CHRE: @ 4292.344: [AR_CHRE] still: 100
2019-10-31 10:49:14.458 12371-12371/? D/GeckoSession: handleMessage GeckoView:ProgressChanged uri=null
2019-10-31 10:49:14.464 12371-12371/? D/GeckoSession: handleMessage GeckoView:PageStop uri=null
2019-10-31 10:49:14.465 12371-12371/? I/SessionStorage/AutoSave: Save: Load finished
2019-10-31 10:49:14.471 12371-12399/? D/SessionStorage/AutoSave: Saved state to disk [5ms]
2019-10-31 10:49:14.473 12371-12400/? D/places_ffi: bookmarks_get_all_with_url
2019-10-31 10:49:15.485 12371-12371/? D/GeckoSession: handleMessage GeckoView:StateUpdated uri=null
2019-10-31 10:49:17.557 761-761/? I//vendor/bin/hw/android.hardware.health@2.0-service.bonito: SRAM data: 3763000
2019-10-31 10:49:17.562 1723-1723/? D/QtiCarrierConfigHelper: WARNING, no carrier configs on phone Id: 0
2019-10-31 10:49:17.580 767-1045/? I/CHRE: @ 4295.543: [AR_CHRE] still: 100
2019-10-31 10:49:17.723 12371-12379/? W/System: A resource failed to call release. 
2019-10-31 10:49:17.723 12371-12379/? W/System: A resource failed to call release. 
2019-10-31 10:49:18.389 12944-12944/? I/GH.ConnLoggerV2: Stopped session 963e1722-608f-46ff-9bbb-735321afc1c2
2019-10-31 10:49:18.390 12944-12975/? D/GH.ConnLoggerV2: Session 963e1722-608f-46ff-9bbb-735321afc1c2, event 2, SESSION_STOPPED
2019-10-31 10:49:19.251 12371-12371/? I/SessionStorage/AutoSave: Save: Session added
2019-10-31 10:49:19.265 12371-12400/? D/SessionStorage/AutoSave: Saved state to disk [15ms]
2019-10-31 10:49:19.269 12371-12464/? D/OpenGLRenderer: endAllActiveAnimators on 0xbb768000 (RippleDrawable) with handle 0xc0263760
2019-10-31 10:49:19.323 12371-12394/? I/GeckoSession: zerdatime 4294645 - chrome startup finished
2019-10-31 10:49:19.347 12371-12371/? D/GeckoSession: handleMessage GeckoView:PageStart uri=about:blank
2019-10-31 10:49:19.351 12371-12371/? D/GeckoSession: handleMessage GeckoView:LocationChange uri=about:blank
2019-10-31 10:49:19.351 12371-12371/? D/GeckoSession: handleMessage GeckoView:PageStop uri=null
2019-10-31 10:49:19.357 12371-12371/? D/GeckoSession: handleMessage GeckoView:OnLoadRequest uri=https://www.netflix.com/title/80133311
2019-10-31 10:49:19.360 12371-12371/? D/GeckoSession: handleMessage GeckoView:OnLoadRequest uri=https://www.netflix.com/title/80133311
2019-10-31 10:49:19.369 12371-12371/? D/GeckoSession: handleMessage GeckoView:ProgressChanged uri=null
2019-10-31 10:49:19.371 12371-12371/? D/GeckoSession: handleMessage GeckoView:PageStart uri=https://www.netflix.com/title/80133311
2019-10-31 10:49:19.374 12371-12371/? D/GeckoSession: handleMessage GeckoView:ProgressChanged uri=null
2019-10-31 10:49:19.376 12371-12371/? D/GeckoSession: handleMessage GeckoView:PageStop uri=null
2019-10-31 10:49:19.377 12371-12371/? D/GeckoSession: handleMessage GeckoView:ProgressChanged uri=null
2019-10-31 10:49:19.378 12371-12371/? D/GeckoSession: handleMessage GeckoView:PageStart uri=https://www.netflix.com/title/80133311
2019-10-31 10:49:19.434 571-608/? W/SurfaceFlinger: Attempting to set client state on removed layer: org.mozilla.fenix.nightly/org.mozilla.fenix.HomeActivity#0
2019-10-31 10:49:19.435 571-608/? W/SurfaceFlinger: Attempting to destroy on removed layer: org.mozilla.fenix.nightly/org.mozilla.fenix.HomeActivity#0
2019-10-31 10:49:19.451 571-608/? W/SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - Task=19#0
2019-10-31 10:49:19.451 571-608/? W/SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - Task=19#0
2019-10-31 10:49:19.756 12371-12371/? D/GeckoSession: handleMessage GeckoView:ProgressChanged uri=null
2019-10-31 10:49:19.757 12371-12371/? D/GeckoSession: handleMessage GeckoView:PageStop uri=null
2019-10-31 10:49:20.081 12371-12371/? I/SessionStorage/AutoSave: Save: Session selected
2019-10-31 10:49:20.082 12371-12422/? D/SessionStorage/AutoSave: Delaying save (1169ms)
2019-10-31 10:49:20.089 12371-12371/? W/GeckoEventDispatcher: No listener for GeckoView:AccessibilityEnabled
2019-10-31 10:49:20.092 12371-12424/? D/places_ffi: bookmarks_get_all_with_url
2019-10-31 10:49:20.102 12371-12394/? D/GeckoScreenOrientation: unlocking
2019-10-31 10:49:20.119 12371-12371/? D/GeckoSession: handleMessage GeckoView:StateUpdated uri=null
2019-10-31 10:49:20.782 767-1045/? I/CHRE: @ 4298.744: [AR_CHRE] still: 100`

**Comment by abodea** [comment] 2020-04-24 09:28
Verified as fixed on the Nightly 4/24 with Google Pixel 4 XL (10).
Please note that the video cannot be played on the browser and it should redirect to the Play Store if the app is not installed or Open the Netflix app if it's installed.
I added this issue here https://github.com/mozilla-mobile/fenix/issues/3177#issuecomment-606690970 with the other bugs and once that issue will be fixed the redirect will work accordingly.

Note that on Chrome, when I tap on any video it auto-redirects me to the Netflix app.

**Closed** 2020-08-11 14:10 UTC
Labels: P2, b:webcompat, eng:qa:verified, 🐞 bug, 🙅 waiting
