### ISSUE TITLE
[Bug] The snackbar for deleted bookmark is displayed the navigation toolbar is not accessible

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#12386] opened 2020-07-08 12:11 UTC
## Steps to reproduce
1. Open app and go to a domain.
1. While in the tab with the domain tap on the Menu and tap the bookmark icon.
1. Tap again on the Menu and remove the bookmark.
1. From the "Edit bookmark" page tap on the recycle bin icon and choose "Delete".
1. While the snackbar is displayed tap on one of the available options.
    1. Expected behavior
The options from navigation bar can be used.(ETp icon, URL bar, tabs tray and Menu)
    1. Actual behavior
The options from navigation bar are not active.
    1. Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 7/8

<details closed>
<summary>Samsung Galaxy S9 (Android 8)</summary>

![20200708-150243](https://user-images.githubusercontent.com/49859863/86917021-1fd58f00-c12d-11ea-97a5-0025761f880c.gif)
</details>

Note:

* The actions from the navigation bar are active when others snackbars are present.

**Comment by BMEduard** [comment] 2020-07-28 05:49
After investigating, I found that the cause of this issue is the FenixSnackbar's parent layout (from BaseTransientBottomBar) that overlaps the toolbar, preventing the user from interacting with it. Since it uses the root view of the Activity as parent to survive the fragment transition, it will always show on top of the toolbar. 
A solution would be to use an arg as a flag and to show the snackbar on the destination fragment using the flag, but this would mean adding this flag for every use case where the snackbar needs to "survive" a fragment transition, which is far from ideal.

**Comment by s-ankur** [comment] 2020-09-20 20:12
Duplicate of #7709?

**Comment by jonalmeida** [comment] 2020-12-16 05:59
Duplicate of #15242

**Closed by jonalmeida** 2020-12-16 05:59 UTC
Labels: Feature:Snackbar, Feature:Toolbar, S2, 🐞 bug
