### ISSUE TITLE
FNX2-15141 ⁃ Crash on "Open in Firefox"ing a custom tab

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12285] opened 2020-07-05 08:09 UTC
1. On  clean install
1. Sign in with email
1. In the sign in custom tab, click open with firefox
1. Crash

Device: Asus Zenfone
Version: Firefox Nightly

**Comment by B0pol** [comment] 2020-07-05 13:00
I can confirm, it happens with all custom tabs.

**Comment by Raamakrishnan** [comment] 2020-07-06 02:59
I am seeing this as well. I feel like this is the crash log that will be needed https://crash-stats.mozilla.org/report/index/6decf0fb-cb86-4d88-89df-c49de0200706

**Comment by rafalopilowski1** [comment] 2020-07-06 15:21
Duplicate of #12277

**Comment by ekager** [comment] 2020-07-06 15:30
closing for #12277

**Closed** 2020-08-14 21:16 UTC
Labels: needs:triage
