### ISSUE TITLE
Add support for generating passwords

### ISSUE THREAD

**Issue by mariusGundersen** [mozilla-mobile/fenix#17068] opened 2020-12-16 09:43 UTC
### What is the user problem or growth opportunity you want to see solved?

In Firefox for desktop there is a way to generate secure passwords and to store the password and user in the synchronized list of usernames and passwords. Firefox for android has the list of usernames and passwords and has a way to add to it, but not to generate a secure password. 

### How do you know that this problem exists today? Why is this important?

The lack of secure password generation on android means that I often defer creating an account until I'm at my PC. 

### Who will benefit from it?

I don't know how many people use the secure password generation feature on desktop

**Comment by cadeyrn** [comment] 2020-12-16 09:48
It's a duplicate of #5661.

**Comment by ekager** [comment] 2020-12-17 18:55
closing as dupe of #5661.

**Closed by ekager** 2020-12-17 18:55 UTC
Labels: feature request 🌟
