### ISSUE TITLE
[Bug] Re-installing Fenix shows tabs from previous install

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#4072] opened 2019-07-16 11:54 UTC
## Steps to reproduce
1. Have some tabs open (I'm unsure if the tabs are related; I see oauth ones for me).
2. Uninstall Fenix.
3. Go to the Play Store and install the latest version.
4. Open the app.

### Expected behavior
- To see the onboarding screen and no new tabs existing.

### Actual behavior
- There are two tabs (for myself) that I had open before uninstalling the app.

### Device information

* Android device: Pixel 2
* Fenix version: 
> Nightly 190716 06:02 (Build #11970611)
> 📦: 4.0.0
> 🦎: 68.0-20190711090008
> 
> Tuesday 7/16@ 6:10 AM

Video 📹:

[HQ](https://gfycat.com/spanishquerulousgyrfalcon)

![SpanishQuerulousGyrfalcon](https://user-images.githubusercontent.com/1370580/61292503-589f8a00-a79f-11e9-9b99-8c0704860927.gif)

**Comment by jonalmeida** [comment] 2019-07-16 12:06
The last frames of the gif seem to get stripped out, you can pause at the end on the HQ version linked above to see that there are two tabs opened.

**Comment by pocmo** [comment] 2019-07-16 12:21
Looks like we didn't disable the app backup feature (AndroidManifest).

**Comment by colintheshots** [comment] 2019-07-16 13:09
That's an interesting case. The user has already seen onboarding. They had tabs cached before deleting the app. This seems like a product question. Do we want them to restore an app backup or see an empty UI?

From a customer support perspective, it may seem easier to clear all data so any bugs disappear if a database gets corrupted.

**Comment by kbrosnan** [comment] 2019-07-16 16:05
Do we need to do anything to remove the data that has been uploaded for 1.0.x clients?

**Comment by jonalmeida** [comment] 2019-07-16 16:27
Should the ticket stay open for QA testing as well?

**Comment by ix5** [comment] 2019-11-16 12:39
This is a horrible "fix". It takes away agency for people who use Android's adb backup feature or expect to set up a new device with their app data restored using Google's backup+restore mechanism.

If users want to get a "fresh start", they should just "clear data" instead of uninstalling/reinstalling.

@colintheshots please reconsider. Please note that restoring app data after uninstalling/reinstalling is *standard* Android behaviour which you are breaking!

**Comment by yoasif** [comment] 2019-11-16 18:14
@ix5 makes some good points here, imo. 

Breaking this feature makes the app feel less like an Android app. Perhaps there could be a refresh feature instead to allow for a fresh start if app data has been restored?

**Comment by jonalmeida** [comment] 2019-11-16 22:44
What you're asking for has already been done. This bug is fixed.

**Comment by yoasif** [comment] 2019-11-16 23:36
@ix5 says that the actual behavior in your report is what he expects. They *want* the appdata restored after reinstallation. 

@jonalmeida

**Comment by ix5** [comment] 2019-11-16 23:36
As far as I can see and verify on-device, backing up Firefox Preview data is not possible.
See https://github.com/mozilla-mobile/fenix/blob/6ee59322b521e52a0bb7c67c55bd934307a75e00/app/src/main/AndroidManifest.xml#L23

**Comment by jonalmeida** [comment] 2019-11-18 17:10
> @ix5 says that the actual behavior in your report is what he expects. They _want_ the appdata restored after reinstallation.

My mistake.

This was intentional because Firefox Sync will cover/have this use case and conflicts with app backups. Please file a new issue with the feature request if you feel strongly otherwise.

**Comment by Amejia481** [comment] 2021-03-09 16:34
QA team could you please help us to verify if this issue is reproducible on Android 11, we reopened this issue as we want to verify some new behavior changes on Android 11 for more info see https://github.com/mozilla-mobile/fenix/issues/18373

**Comment by abodea** [comment] 2021-03-10 11:45
Verified as fixed with Google Pixel 4 XL (Android 11).
Note that I tried with the following versions:
- **Latest RC build (86.1.1)** 
- **Latest Beta build (87.0.0b4)**
- **Nightly** 3/10.**
I've had like 3-5 tabs opened before each reinstall and every time I saw the onboarding.

**Closed by abodea** 2021-03-10 11:45 UTC
Labels: eng:qa:needed, 🐞 bug
