### ISSUE TITLE
[Feature Request] Flow layout for search suggestions as in fennec

### ISSUE THREAD

**Issue by 0xTyagi** [mozilla-mobile/fenix#12950] opened 2020-07-26 07:46 UTC
### What is the user problem or growth opportunity you want to see solved?
Current implementation of search suggestions is not as helpful as in fennec. On small screen devices (4" or less) it is very difficult to see all suggestions without scrolling or hiding keyboard moreover history and Bookmark suggestions are always hidden behind keyboard and so these suggestions are useless as these are not shown at first glance. Flow layout like as in fennec can solve this problem as this will save some space to show some other suggestions

Fenix implementation

![Screenshot](https://user-images.githubusercontent.com/59569506/88474186-d913d180-cf41-11ea-9344-72c152257066.jpg)UNITO-UNDERSCORE!2020-07-26-12-32-14-166!UNITO-UNDERSCORE!org mozilla fenix!

fennec implementation

![Screenshot](https://user-images.githubusercontent.com/59569506/88474205-efba2880-cf41-11ea-9916-ebf3da8a17cc.jpg)UNITO-UNDERSCORE!2020-07-26-12-34-16-560!UNITO-UNDERSCORE!org mozilla firefox!

**Comment by cadeyrn** [comment] 2020-07-26 13:29
Duplicate of and WONTFIX via #3105:

> User research shows that the chips are very small touch targets and it was an deliberate decision to not use them.

**Comment by 0xTyagi** [comment] 2020-07-26 16:27
>chips are very small touch targets and it was an deliberate decision to not use them.

What was stopping fenix team from making chips size larger?

Or deliberately copying chrome design.

**Comment by 0xTyagi** [comment] 2020-07-26 16:35
Chips are larger than Shield button so remove this sheild icon **"Deliberately"** 😀

**Comment by brampitoyo** [comment] 2020-07-30 02:26
I can confirm that this issue is a wonfix for us.

**Closed** 2020-08-28 23:00 UTC
Labels: Feature:Search, feature request 🌟, needs:UX-investigation
