### ISSUE TITLE
[investigate] Cookies are not being deleted

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#25478] opened 2022-05-31 16:50 UTC
**Copied from bz-1765314**

User Agent: Mozilla/5.0 (Android 12; Mobile; rv:99.0) Gecko/99.0 Firefox/99.0

Steps to reproduce:

1. I clicked on the Lock icon in the URL Bar and then hit "Clear Cookies and Site Data".
2. I hit quit in the menu. In the settings I have switched on "Delete Browsing Data on Quit" with all options checked.
3. I changed the cookie setting in "Enhanced Tracking Protection" from " All third-party cookies" to "All cookies". Then I closed and opened the app and changed it back to "All third-party cookies".

Actual results:

1. I was still logged in the website where I cleared the cookies.
2. I was still logged into all the websites after I quit and reopened the app.
3. I was logged out of the websites after I reopened the app after changing it to "All cookies". But I was logged back in after I changed it back to "All third-party cookies".

Expected results:

1. I should've been logged out of the website.
2. I should've been logged out of all the websited I was logged into before I hit quit.
3. I shouldn't have been logged back in when I changed it back to "All third-party cookies".

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20623)

**Comment by kbrosnan** [comment] 2022-05-31 16:52
We want to understand this behavior with regards to the quit function and if there are additional safeguards we would like to implement. Coordinate with @csadilek for additional information.

**Comment by ale82to** [comment] 2022-06-02 06:06
I can confirm this too i had the need to switch account for a site (everli.com )tried clear cookie and site data from the lock icon in the url bar and even after killing fenix I was logged in with old credential as usual I ended up using Samsung internet .

**Comment by Mugurell** [comment] 2022-07-06 16:25
The first scenario - clearing cookies from the lock icon while in private mode seem to be broken from it's beginning.
And this is also broken for desktop so I've opened a new ticket for this - https://bugzilla.mozilla.org/show_bug.cgi?id=1773288 since it seems like a bigger issue.

**Comment by echuber2** [comment] 2022-08-23 19:33
I've had a similar issue with recently closed tabs not being deleted (see issues https://github.com/mozilla-mobile/fenix/issues/22454 and https://github.com/mozilla-mobile/fenix/issues/24034, possibly also https://github.com/mozilla-mobile/fenix/issues/22486). Even if I close a tab, explicitly delete its entry from the "recently closed tabs list", clear history, etc., after reopening the app, the tab comes back. Given many other people noted the sticky behavior with tabs, I'm not surprised it happens with cookies too.

**Comment by echuber2** [comment] 2022-08-23 19:34
I also wonder if it's a contributing factor to the symptoms in https://github.com/mozilla-mobile/fenix/issues/12731.

**Comment by cpeterso** [comment] 2022-12-26 06:28
> The first scenario - clearing cookies from the lock icon while in private mode seem to be broken from it's beginning. And this is also broken for desktop so I've opened a new ticket for this - https://bugzilla.mozilla.org/show_bug.cgi?id=1773288 since it seems like a bigger issue.

I'm closing this GitHub issue and will reopen Bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1765314 to confirm that Fenix correctly clears cookies after https://bugzilla.mozilla.org/show_bug.cgi?id=1773288 is fixed.

**Closed by cpeterso** 2022-12-26 06:28 UTC
Labels: 🐞 bug, 🙅 waiting, Feature:PrivateBrowsing
