### ISSUE TITLE
Accessibility option to add back button in pop-up menu

### ISSUE THREAD

**Issue by spinda** [mozilla-mobile/fenix#7335] opened 2019-12-22 02:15 UTC
### Why/User Benefit/User Problem

My father just reverted to legacy Firefox for Android because "there's no back button anymore [in the pop-up menu]". I assume it was removed in the process of consolidating the swipe-up menu with the pop-up menu. He's never used the system-wide back gesture (a swipe on the physical home button, in the case of his phone), and isn't going to start now.

### What/Requirements

Add a toggle to the accessibility settings which re-adds a back button next to the forward button in the pop-up menu. In my experience, older users find in-app navigation options more natural than system-wide gestures. To my father's credit, most other apps *do* provide in-app "back" navigation options as an alternative to the global back gesture: the fact that Fenix now lacks any way to do this from within the app UI makes it an outlier.

### Acceptance Criteria (how do I know when I’m done?)

It is possible to navigate backward via the pop-up menu.

**Comment by cadeyrn** [comment] 2019-12-22 08:39
Duplicate of #6559 and mentioned in https://github.com/mozilla-mobile/fenix/issues/5905#issuecomment-553066787.

**Comment by kbrosnan** [comment] 2020-01-11 01:30
Closing as a duplicate.

**Closed by kbrosnan** 2020-01-11 01:30 UTC
Labels: Feature:MainMenu, 🌟 feature request
