### ISSUE TITLE
FNX-4626 ⁃ *New* tab tray missing options for home, new tab

### ISSUE THREAD

**Issue by astarq** [mozilla-mobile/fenix#10847] opened 2020-05-22 11:41 UTC
Version Nightly 200522 06:01 (Build #2015741747)

The new slide up tray appears when the user tabs on the tab icon, and only shows open tabs (including private tabs). There is no option to open a new tab, a new private tab, or navigate to the homescreen, meaning the user is stranded with only their open tabs

This is the current tab tray:
![Screenshot](https://user-images.githubusercontent.com/63871973/82664192-1a79bf00-9c29-11ea-8e4c-0100a6083ae0.png)UNITO-UNDERSCORE!20200522-123706!UNITO-UNDERSCORE!Firefox Nightly!

Maybe missing buttons could appear next to those for "default" and "private"

This is still better than the separate page for open tabs though!

**Comment by serovar** [comment] 2020-05-22 20:29
The strangest thing is that some users do have a "New Tab" FAB button:

![tabtray2](https://user-images.githubusercontent.com/6732420/82707031-82f18c00-9c7b-11ea-9427-a01877947734.jpg)
![tabtray1](https://user-images.githubusercontent.com/6732420/82707036-8422b900-9c7b-11ea-8206-64b964cf3b4c.png)

Source: [this Reddit discussion](https://www.reddit.com/r/firefox/comments/gogmfh/love_the_new_fenix_tab_tray_implementation_though/)

**Comment by astarq** [comment] 2020-05-22 20:48
Guess I was unlucky 😒 Seems the home button is missing for them as well, how bizarre. This is a great way of switching tabs though, so I hope they stick with it!

**Comment by ekager** [comment] 2020-05-22 23:51
@astarq what device/API version do you have?

**Comment by serovar** [comment] 2020-05-22 23:56
I have the same issue and my device is a Google Pixel 2 XL with Android 10.

**Comment by astarq** [comment] 2020-05-23 00:04
> @astarq what device/API version do you have?

Galaxy S8+, Android 9

> @astarq what device/API version do you have?

Galaxy S8+, Android 9

**Comment by yoasif** [comment] 2020-05-23 00:32
Also missing the + button on a Pixel 2 with Android 9.

**Comment by ekager** [comment] 2020-05-23 01:24
Yeah I can reproduce. Looks like if you set the `peekHeight` to 0 it shows up, but the tabs tray doesn't. Probably needs some tuning here. cc @boek

**Comment by andreicristianpetcu** [comment] 2020-05-23 10:34
I have one plus 5t with LineageOS 16 based on android 9

**Comment by serovar** [comment] 2020-05-27 19:03
Fixed for me on the latest Nightly (Nightly 200527, Build #2015742803).

**Comment by astarq** [comment] 2020-05-28 00:48
> Fixed for me on the latest Nightly (Nightly 200527, Build #2015742803).

And me

**Comment by astarq** [comment] 2020-05-28 00:49
Should I close this now?

**Comment by andreicristianpetcu** [comment] 2020-05-28 02:37
close it

**Comment by AndiAJ** [comment] 2020-06-05 06:28
Hi, **verified as fixed** on the latest **`Nightly Build 200605 from 6/5`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200605-092500](https://user-images.githubusercontent.com/51314259/83844003-dbf70080-a70e-11ea-9dc2-b892f5fb42ca.gif)

**Closed** 2020-08-10 22:08 UTC
Labels: Feature:Tabs, Skittle, eng:qa:verified, 🐞 bug
