### ISSUE TITLE
[Bug]Can't exit desktop site.

### ISSUE THREAD

**Issue by PowERGD** [mozilla-mobile/fenix#4795] opened 2019-08-18 06:26 UTC
## Steps to reproduce
Open a website.
Click more.
Click desktop site.
Click more.

### Expected behavior
Can exit desktop site mode.
### Actual behavior
Can't exit desktop site mode, unless reopenning the website.
### Device information

* Android device: Redmi 4 prime
* Fenix version: v1.3.0 rc2

**Comment by mikeGolf08** [comment] 2019-08-18 09:20
Same here - 

    Android device: Android 9 on OnePlus 3T (A3003) Oxygen OS 9.0.5
    Fenix version: Nightly 190817 06:05 (Build #12290612)
    package: 8.0.0, 78354bc12
    lizard: 69.0-20190812090043

**Comment by PopeRigby** [comment] 2019-08-21 03:16
Same

```
Android: 8.1.0
Fenix: Nightly 190820 18:01 (Build #12321805)
Package: 9.0.0, 3c8dd6f50
Gecko: 69.0-20190819100044
```

**Comment by AndiAJ** [comment] 2019-08-26 10:42
Hi, I've managed to reproduce the above described issue when requesting the desktop site of **youtube.com** on the latest Fenix Nightly Build #12380610 from 26/8, using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 lite (android 8.1.0)
• Samsung Glaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (android 5.1.1)

<details>
    <summary>Fenix VS Chrome videos</summary>

► Fenix
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/51314259/63684968-e04ccf80-c806-11e9-92e6-b6d3a78282ce.gif)

►Chrome
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/51314259/63685028-0e321400-c807-11e9-8353-1fb21828848c.gif)


</details>

Not sure, but I've noticed that after disabling the desktop version, the link remains https://www.youtube.com/?**app=desktop**

@boek based on this, I'll go ahead and **reopen this issue**.

**Comment by AndiAJ** [comment] 2019-08-26 14:21
Hi again, I've just checked with @mcarare and he told me that the change was regarding the request "Desktop site " toggle button.
I've re-checked and **everything seems to be working fine** on latest Fenix **Nightly Build #12380610** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 lite (android 8.1.0)
• Samsung Glaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (android 5.1.1)

The above mentioned Youtube issue is duplicate of #3903 
Based on this I'll **close this ticket**.

**Closed by AndiAJ** 2019-08-26 14:21 UTC
Labels: Feature:RequestDesktopSite, eng:qa:verified, 🐞 bug
