### ISSUE TITLE
[Bug]: Filename in "Open" PDF dialog overflows screen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21816] opened 2021-10-08 23:31 UTC
### Steps to reproduce

- Visit http://shawnodonnells.com
- Click "Lunch/Dinner Menu" (may require scroll down)
- Click "Download"
- Wait for download to complete

### Expected behaviour

Filename fits in dialog

### Actual behaviour

Filename overflows "Open" dialog (this doesn't affect earlier "Download" dialog)

![device-2021-10-08-162921](https://user-images.githubusercontent.com/759372/136634424-d0d22712-0c72-45e2-a429-7843b2e278d8.png)

### Device name

Moto G5

### Android version

?

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 10/8

**Comment by LaurentiuApahideanSV** [comment] 2021-11-02 17:34
I tested the issue on Firefox Preview Nightly 2021-11-02. I was able to reproduce it, however the issue also occurs on Chrome.

### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by Taknok** [comment] 2021-11-06 17:54
This break the default `MAX_PATH` on Windows (260 chars). Thus, the repo cannot be cloned anymore on Windows 10 if you do not increase the value. (To be precise, main branch cannot be checkout).

To increase the max value, run the following powershell command and reboot:

```powershell
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
-Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
```

Source: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell

**Comment by grigoryk** [comment] 2021-11-06 20:58
> This PR #22325 break the default `MAX_PATH` on Windows (260 chars). Thus, the repo cannot be cloned anymore on Windows 10 if you do not increase the value. (To be precise, main branch cannot be checkout).
> 
> To increase the max value, run the following powershell command and reboot:
> 
> ```powershell
> New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
> -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
> ```
> 
> Source: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell

Thanks, @Taknok ! That was unintentional, of course.
cc @mavduevskiy can you adjust the test file to be under the limit?

**Comment by grigoryk** [comment] 2021-11-07 03:07
Should be fixed by https://github.com/mozilla-mobile/fenix/pull/22354

**Comment by mavduevskiy** [comment] 2021-11-07 09:07
I am a bit puzzled on what to do. The very idea behind adding a file with such a long name was to test if the app can properly display downloaded file with max possible name length. Which happens to be in the range of 250-260. Which happens to be also the max path name in Windows systems. While on MacOS it is 1024, and on Linux 4096.

Shouldn't the most of developers working on Widnows increase the max path length? Having max path length the same as max file name length on most of the systems is prone to errors. Even if we cut the file name in half, some windows users might still run into the same problem if they have a long project folder path on its own.

Not holding any strong opinions though. Just want to find balance between the need to test displaying of max length file names and adjusting to Windows system requirements. 
@Taknok @grigoryk

**Comment by Taknok** [comment] 2021-11-07 10:30
I share your feelings. I report this as a remark, in order to be sure everyone was aware.
Windows is quite a pain to have a path length that short, but preventing someone since the begging to clone (checkout in reality) the main branch or event unzip the archive makes me uncomfortable, but it is a valid choice for Fenix team's. So I see 2 options here:
-  Set a paragraph in the `Readme.md` to warn for windows env that user/dev should increase max path length and reboot before cloning.
- Generate the file to download programmatically (thus, the file will not be in the repo) and set a check in graddle to check max path length and ask user/dev to increase the limit. If not done, the test will only failed on windows environment.

Another option would be to change the filename length according to environment, but I do not like this idea.

**Comment by grigoryk** [comment] 2021-11-07 18:37
https://github.com/mozilla-mobile/fenix/pull/22354 landed, I confirmed that this fixed `git clone` of the project on my Windows machine.

**Comment by sflorean** [comment] 2021-11-11 17:28
Verified as fixed on latest Nightly build, with LG G7 Fit (Android 8.1).

**Closed by sflorean** 2021-11-11 17:28 UTC
Labels: 🐞 bug, needs:triage, qa-triaged
