### ISSUE TITLE
Crash at java.lang.IllegalStateException: Fragment ChoiceDialogFragment UUID not associated with a fragment manager

### ISSUE THREAD

**Issue by Takemats** [mozilla-mobile/fenix#27840] opened 2022-11-15 10:34 UTC
b19c0899-2d1d-48d2-a49a-dce5ffaf1c57
java.lang.IllegalStateException: Fragment ChoiceDialogFragment{ff390ba} (7f318850-c7ed-444f-bb35-0806d5058a97) not associated with a fragment manager.
----
java.lang.IllegalStateException: Fragment ChoiceDialogFragment{ff390ba} (7f318850-c7ed-444f-bb35-0806d5058a97) not associated with a fragment manager.
	at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:2)
	at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:16)
	at androidx.fragment.app.DialogFragment.dismissAllowingStateLoss(DialogFragment.java:1)
	at mozilla.components.feature.prompts.PromptFeature$start$1$3.emit(PromptFeature.kt:29)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Emitters.kt:19)
	at mozilla.components.feature.prompts.PromptFeature$start$1$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:7)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1bcc2e2, Dispatchers.Main]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21989)

**Comment by kbrosnan** [comment] 2022-11-15 16:53
Probably a duplicate of https://github.com/mozilla-mobile/fenix/issues/27433

@Takemats can you reproduce with our nightly build? https://play.google.com/store/apps/details?id=org.mozilla.fenix

**Comment by cpeterso** [comment] 2022-12-13 06:10
https://bugzilla.mozilla.org/show_bug.cgi?id=1759003

**Closed by cpeterso** 2022-12-13 06:10 UTC
Labels: b:crash
