### ISSUE TITLE
FNX-12312 ⁃ [Bug] Synced tabs UI allows users to reload page and stays like that forever

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#11384] opened 2020-06-09 17:46 UTC
## Steps to reproduce
1. Open Synced tabs without a logged in account
1. Pull down

### Expected behavior
Pull down should probably not have an affordance at all. 

### Actual behavior
"loading" icon appears and never goes away if user remains on that page. 

![signal-attachment-2020-06-09-134525](https://user-images.githubusercontent.com/152493/84181846-83e63400-aa57-11ea-96a8-627921789758.png)

### Device information
* Android device: Pixel 2
* Fenix version: Nightly 200609 06:00 (Build #21610607)
45.0.20200608190110, 8ec16f840
GV: 79.0a1-20200608094842
AS: 60.0.0

**Comment by hakkikaancaliskan** [comment] 2020-06-11 12:17
https://github.com/mozilla-mobile/android-components/blob/314ba54660fe0406c62d9c9382c2d277482edb2f/components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/controller/DefaultController.kt#L38

@ekager adding this piece of code to there will fix the problem, right? I don't know how to test via local ac changes. How can I test this?
```
if (accountManager.accountProfile() == null){
    view.onError(ErrorType.SYNC_UNAVAILABLE)
}
```

**Comment by hakkikaancaliskan** [comment] 2020-06-12 09:09
duplicate of #11497 
#11497 is fixed

**Comment by jonalmeida** [comment] 2020-06-12 10:32
Closing as duplicate of #11497.

**Closed** 2020-08-11 03:55 UTC
Labels: Feature:Sync, eng:ready, good first issue, 🐞 bug
