### ISSUE TITLE
[Bug] "add to collection" shown in private browsing mode

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#14465] opened 2020-08-29 20:49 UTC
## Steps to reproduce
1. Have no normal tabs open
2. Open a private tab and navigate to a webpage
3. Open the tabs tray from the normal home page

### Expected behavior
"Add to collection" is not shown for private tabs 

### Actual behavior
It is shown

### Device information

* Android device: Samsung Galaxy A50
* Fenix version: Nightly 200829 06:05 (Build #2015760755)
AC: 57.0.20200827190112, 91f7bcbca
GV: 82.0a1-20200827093043
AS: 61.0.13

**Comment by otede** [comment] 2020-09-06 07:12
I strongly disagree!
If you don't actively perform several steps to actually save the private tabs to a collection the feature literally does not affect you! You might as well opt for removing "Add to bookmarks" for private tabs.

**Comment by miDeb** [comment] 2020-09-06 07:19
This is a bug because it's the only way to get the button show up in private mode. It is otherwise_never_ shown for private mode. If you want it to be there it should be always enabled! File a feature request!

**Comment by ekager** [comment] 2020-12-18 05:29
Closing because I don't think this is reproducible anymore.

**Closed by ekager** 2020-12-18 05:29 UTC
Labels: needs:triage, 🐞 bug
