### ISSUE TITLE
InternalPanic - called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#3212] opened 2019-06-06 13:42 UTC
https://sentry.prod.mozaws.net/operations/fenix/issues/5831528

    mozilla.appservices.places.InternalPanic: called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"
        at mozilla.appservices.places.RustError.intoException(RustError.kt:14)
        at mozilla.appservices.places.PlacesReaderConnection.queryAutocomplete(PlacesConnection.kt:13)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getSuggestions(PlacesHistoryStorage.kt:1)
        at mozilla.components.feature.awesomebar.provider.HistoryStorageSuggestionProvider.onInputChanged(HistoryStorageSuggestionProvider.kt:3)
        at mozilla.components.browser.awesomebar.BrowserAwesomeBar$onInputChanged$1.invoke(BrowserAwesomeBar.kt:4)
        at mozilla.components.browser.awesomebar.BrowserAwesomeBar$queryProvidersForSuggestions$1$invokeSuspend$$inlined$forEach$lambda$1$1.invokeSuspend(BrowserAwesomeBar.kt:2)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by jdragojevic** [comment] 2019-06-06 14:11
Closing this as a duplicate of https://github.com/mozilla-mobile/reference-browser/issues/710 and a-s issue https://github.com/mozilla/application-services/issues/904

**Closed** 2020-08-26 21:49 UTC
Labels: b:crash, 🐞 bug
