### ISSUE TITLE
[Bug] Voice search in widget opens Google results even though my default engine is DuckDuckGo

### ISSUE THREAD

**Issue by tomato73** [mozilla-mobile/fenix#17366] opened 2021-01-08 09:21 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Set default search engine to DuckDuckGo (presumably anything non-google), press microphone icon in search widget, say "test", see Google results for "test" displayed
### Expected behavior
It should show DuckDuckGo results
### Actual behavior
It shows Google results
### Device information
Galaxy Note 9
* Android device: 10 (4.9.186)
* Fenix version: 84.1.4 (Build #2015785883)

**Comment by cadeyrn** [comment] 2021-01-08 09:50
Duplicate of #15348 or #4757.

**Comment by tomato73** [comment] 2021-01-08 15:44
> Duplicate of #15348 or #4757.

I searched and found one of these, and I think two issues are being conflated. I'm not concerned about google providing the text-to-speech service, that is expected. My issue specifically is that once Google (or whatever text-to-speech provider is being used, presumably) returns the text (e.g. "test") a browser window is opened pointing to google.com/?s=test... rather than duckduckgo.com/s=test, even though duckduckgo is my default SEARCH provider. Typing the word "test" instead results in the expected behavior.

**Comment by tomato73** [comment] 2021-01-08 17:10
Maybe the step of converting speech to text and the step of submitting a search query are inextricably linked for some reason, but as a user I would guess that they are separate steps in the process.

**Comment by kbrosnan** [comment] 2021-01-08 19:12
The voice input icon is removed from the address bar when a non-google search engine is selected. Where are you pressing the microphone?

**Comment by tomato73** [comment] 2021-01-08 22:26
It's on the right, inside the bar. But I just updated and restarted my
phone, tried to reproduce this behavior, and now it is acting as expected.
Google does the text-to-speech, but the results are opened in duckduckgo.

**Comment by kbrosnan** [comment] 2021-01-12 21:12
Going to close this as not reproducible.

**Closed by kbrosnan** 2021-01-12 21:12 UTC
Labels: needs:triage, 🐞 bug
