### ISSUE TITLE
Can't use self-signed certificates anymore

### ISSUE THREAD

**Issue by mattfeest** [mozilla-mobile/fenix#15429] opened 2020-09-25 19:29 UTC
## Steps to reproduce
Try to download and install a self-signed certificate (i.e. https://mf327.com/ca.crt)
### Expected behavior
Either Firefox should import the certificate into it's own store or use the OS certificate store so you can use the certificate.
### Actual behavior
The certificate is downloaded and not installed in the Firefox store. I can install it in the Android store, but Firefox does not use it.
### Device information

* Android device: Samsung Galaxy Note 10
* Fenix version: 81.1.1

**Comment by mattfeest** [comment] 2020-10-14 00:13
soooo....

**Comment by liuche** [comment] 2020-10-15 00:29
Dupe of #2286

**Closed by liuche** 2020-10-15 00:29 UTC
Labels: needs:triage, 🐞 bug

**Comment by vladns** [comment] 2020-12-03 15:49
It's still not clear if there is a solution to the problem?
