### ISSUE TITLE
No longer possible to go back or forward by more than one page at once (back button traps no longer bypassable)

### ISSUE THREAD

**Issue by Googulator** [mozilla-mobile/fenix#13818] opened 2020-08-13 20:28 UTC
In Fennec, we had the ability to go back more than one page at once by long-pressing the back button, and selecting the page to go back to from the list that pops up, a great way to bypass back button trapping websites. Similarly for the forward button. No other browser offered this feature on phones (Chrome has something similar, but only on tablets).

In Fenix, this is either missing or broken, as long-pressing Back or Forward gives haptic feedback as before, but no list pops up.

**Comment by cadeyrn** [comment] 2020-08-13 20:54
This feature is already implemented in Firefox Nightly. Please try with Nightly and if it doesn't work provide more information about your device and Android version.

**Comment by kbrosnan** [comment] 2020-08-13 23:19
Closing as a duplicate of #1048

**Closed by kbrosnan** 2020-08-13 23:19 UTC
Labels: needs:triage
