### ISSUE TITLE
Custom search engines/Working URL  get marked as not valid

### ISSUE THREAD

**Issue by loveless90** [mozilla-mobile/fenix#8283] opened 2020-02-10 20:11 UTC
## Steps to reproduce

Enter in the "Search string to use" input-field for example:

https://de.m.wikipedia.org/wiki/%s
https://dict.leo.org/german-english/%s

### Expected behavior

After submitting a name and confirming the input by clicking the tick-mark, the search engine should be added.

### Actual behavior

Getting error: "Error connecting to <name of the search-engine>

### Device information

* Android device: ?

Samsung Galaxy S4 mini/Lineage OS 16.0

* Fenix version: ?

Nightly/Build 20410605

**Comment by cadeyrn** [comment] 2020-02-10 20:15
Duplicate of #8239.

**Comment by loveless90** [comment] 2020-02-10 20:21
I don't think that it is duplicate, because

https://www.duden.de/suchen/dudenonline/ich

has the same structure but works fine. Maybe it's because missing "www"?

**Comment by cadeyrn** [comment] 2020-02-10 20:25
#8239 has even the same search engine as example…

**Comment by loveless90** [comment] 2020-02-10 20:32
Ok, it can be, that's the same URL. But i don't think that it is problem with the query parameter.
The query of Duden has the same structure that of Leo and Duden works fine.
The other bug-report is still to be tested, so maybe it's wrong assumption.

**Comment by loveless90** [comment] 2020-02-10 21:12
The not working wikipedia URL was mine mistake, because it wasn't the search-url, but the URL of an article. So it seems that it's not the "www". But LEO and Duden have definitely the same structure of the search query.

**Comment by kbrosnan** [comment] 2020-02-10 23:26
Agree this is a duplicate, closing.

**Closed by kbrosnan** 2020-02-10 23:26 UTC
Labels: needs:triage, 🐞 bug
