### ISSUE TITLE
Backspacing in the URL bar after autocomplete keeps autocompleting, every other keystroke

### ISSUE THREAD

**Issue by blerner** [mozilla-mobile/fenix#16166] opened 2020-10-25 13:22 UTC
## Steps to reproduce
On several sites, I get the following behavior in the URL bar:
- I'm at site foo.com/some/sub/url (could be a specific .html page, or it could end in a /, it doesn't seem to matter)
- I touch the URL bar to focus it, and start backspacing to clear out the sub-url and go to a different one (e.g., go to a different subreddit)
- When I backspace, Fenix autocompletes the URL and selects the autocompleted text.  I backspace again to clear the autocomplete.
- When I backspace a third time (to delete the second letter of the URL), Fenix again autocompletes the URL.  I backspace a fourth time to clear the autocomplete.
- When I backspace a fifth time (to delete the third letter of the URL), Fenix again autocompletes the URL.  I backspace a sixth time to clear the autocomplete.

In general it takes me 2n steps to delete n characters from the URL.

### Expected behavior

Once I've dismissed the autocomplete, Fenix shouldn't suggest it again.

### Actual behavior

I can't _always_ trigger this autocomplete annoyance, but it seems to happen pretty reliably on Reddit and ArsTechnica URLs.  It only seems to trigger the autocompletion on URL segments that are completely textual: any digits in there seem to not cause this to happen.  (So on ArsTechnica, the URL slug will autocomplete, the topic will autocomplete, but the date will not.)

### Device information

* Android device: Pixel 3 running Android 11 latest updates
* Fenix version: 81.1.5

**Comment by s-ankur** [comment] 2020-10-25 18:39
Very annoying yes, but seems to be a duplicate of #12525. Thanks for filing btw

**Comment by blerner** [comment] 2020-10-25 18:42
Apologies for the noise -- I searched for "address bar" and "backspace", but not "backspacing" and "URL bar", so the search didn't find any relevant issues.  Feel free to close as dupe.

**Comment by kbrosnan** [comment] 2020-10-26 19:31
Closing as a duplicate of #12525

**Closed by kbrosnan** 2020-10-26 19:31 UTC
Labels: needs:triage, 🐞 bug
