### ISSUE TITLE
[Bug] Visiting history while syncing causes an ANR

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#4365] opened 2019-07-29 22:59 UTC
## Steps to reproduce
On a fresh install turn on sync and visit history

### Expected behavior
Does not ANR

### Actual behavior
ANR

**Comment by ekager** [comment] 2019-08-01 03:23
Do we think dupe of #4137 ?

**Comment by NotWoods** [comment] 2019-09-25 19:29
@boek Is this still an issue with paged history?

**Comment by mcarare** [comment] 2019-12-09 09:53
I haven't been able to reproduce this anymore. 
Can QA please also check this? TY!

**Comment by AndiAJ** [comment] 2019-12-10 14:27
Hi, **verified as fixed** on the latest **Nightly Build #13440604 from 12/10** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

►Video Sign in using Email
![20191210_161322](https://user-images.githubusercontent.com/51314259/70537878-d9ee2380-1b69-11ea-82d7-5f5d766040dc.gif)


►Video Sign in using QR pairing
![20191210_162035](https://user-images.githubusercontent.com/51314259/70537944-f5f1c500-1b69-11ea-8956-4f661b99266c.gif)

**Closed by AndiAJ** 2019-12-10 14:27 UTC
Labels: Feature:History, Feature:Sync, P2, b:anr, eng:qa:verified, 🐞 bug
