### ISSUE TITLE
[Bug] Twitter GIF (video without audio) causes app playing audio to pause

### ISSUE THREAD

**Issue by caugner** [mozilla-mobile/fenix#9002] opened 2020-03-05 17:31 UTC
## Steps to reproduce

1. Play audio in an app of your choice (e.g. a podcast in BeyondPod).
2. Open https://mobile.twitter.com/firefox/status/1230968940144128000 in Firefox Preview.

### Expected behavior

The audio should continue playing (like it does when opening that URL in Chrome).

### Actual behavior

The audio is paused by the GIF "playback" and a media playback notification appears:

![Screenshot_20200305-184515_Firefox_Nightly](https://user-images.githubusercontent.com/495429/76009527-a117dd80-5f11-11ea-97dc-7ec1608c09e8.png)

### Device information

* Android device: Fairphone FP2
* Fenix version: `75.0a1-2020030408140`

**Comment by kawaiiDango** [comment] 2020-04-02 21:50
The title of this issue is misleading as GIFs (the classic .gif format) play fine. The issue happens with videos without sound. I could reproduce this issue on any giphy page e.g. https://giphy.com/gifs/bestfriends-dog-quarantine-social-distancing-l4MVA5hWk3gnB7K8yH

But those aren't classic GIFs. They are MP4 videos without sound.

**Comment by caugner** [comment] 2020-04-02 23:01
Thanks for pointing that out, I have changed the title accordingly.

**Comment by sv-ohorvath** [comment] 2020-08-11 11:25
I think this is the same as https://github.com/mozilla-mobile/fenix/issues/6146. I'll close this in favor of that one because it has more info & history.

**Closed by sv-ohorvath** 2020-08-11 11:25 UTC
Labels: needs:triage, 🐞 bug

**Comment by caugner** [comment] 2020-08-31 14:33
@sv-ohorvath I don't think this is the same issue as #6146. In fact, I'm pretty sure that this issue had been fixed temporarily, but I'm observing the issue again for a few days: I'm listening to a podcast app in the background and scroll through Twitter: when a GIF or Video (muted) start to autoplay, the podcast playback stops.

**Comment by sv-ohorvath** [comment] 2020-09-01 06:50
@caugner I took the decision based on this dev's comment: https://github.com/mozilla-mobile/fenix/issues/6146#issuecomment-611485930 with what is getting fixed in that issue. And this QA's findings: https://github.com/mozilla-mobile/fenix/issues/6146#issuecomment-612946568 which sound exactly like this issue.
If I'm still wrong, I apologize, and I can reopen the issue. Thank you!
