### ISSUE TITLE
[Bug] Favicons don’t get displayed when not explicitly referenced in HTML

### ISSUE THREAD

**Issue by j9t** [mozilla-mobile/fenix#20180] opened 2021-06-26 10:07 UTC
(Note: I had originally looked for similar reports and commented on #18382. However, there hasn’t been a heartbeat, and given that the reported behavior is inconsistent with the HTML spec, other user agents, and Firefox itself, it seems useful to report.)

There is a bug in Firefox Android around the displaying of favicons. Other factors left aside, Firefox Android seems to require favicons to be hardcoded in the markup (`link` element pointing to an `icon`). (I verified and tested with the site below, but rolled back the change as this looks like a user agent problem.)

As mentioned in the note, this behavior is inconsistent [with the HTML spec](https://html.spec.whatwg.org/multipage/links.html#rel-icon), other user agents, and Firefox itself (favicons get shown Firefox for desktop, as that seems to be looking for favicon files in the root).

## Steps to reproduce

Navigate to https://uitest.com/

### Expected behavior

A favicon is shown as in Firefox for desktop and other user agents

### Actual behavior

No favicon is shown, but a generic “U”

### Device information

* Device vendor / model and Android version: Pixel 4a, Android 11
* Firefox for Android version: 89.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16922)

**Comment by LaurentiuApahideanSV** [comment] 2021-06-28 12:46
I can confirm the issue is reproducible on Firefox Preview Nightly 06/28.
### Devices used
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)

**Comment by codrut-topliceanu** [comment] 2021-07-20 13:45
It seems that there are 2 issues at work here that result in the current reported behavior.

- First, just as stated by @j9t , when downloading the resources for https://uitest.com/ we do not seem to catch the `src="https://d2g3fg8cn2k57g.cloudfront.net/media/logo.svg"` that lies in the header. If this is in need of fixing perhaps we could add a case for it in[ icons.js](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/icons/src/main/assets/extensions/browser-icons/icons.js).
- Secondly, we actually do download two images that could be used as favicons, but they are rather large (~1024x512), and the [code here](https://github.com/mozilla-mobile/android-components/blob/53c9a2b19c40f3426fc5f70dafb2431e1fa04c38/components/support/images/src/main/java/mozilla/components/support/images/decoder/AndroidImageDecoder.kt#L31) decides that they are too large to even scale down properly, though I'm not sure why, as `inSampleSize` should be able to support scaling down of larger images without trouble.

Pinging @rocketsroger & @pocmo . Do you guys have any advice on how we should proceed here?

**Comment by j9t** [comment] 2021-07-21 07:40
> when downloading the resources for https://uitest.com/ we do not seem to catch the src="https://d2g3fg8cn2k57g.cloudfront.net/media/logo.svg" that lies in the header

Just for understanding, is that some Firefox Android fallback behavior? (Any pointers to share to read up on the heuristics in use?)

**Comment by pocmo** [comment] 2021-07-21 07:57
> when downloading the resources for https://uitest.com/ we do not seem to catch the `src="https://d2g3fg8cn2k57g.cloudfront.net/media/logo.svg"` that lies in the header.

Yeah, we currently do not support decoding SVGs in the Kotlin code. That's:
https://github.com/mozilla-mobile/android-components/issues/2081

>  decides that they are too large to even scale down properly, though I'm not sure why, as `inSampleSize` should be able to support scaling down of larger images without trouble.

Afaik that was already the case with Fennec. Note that:
- we use different decoders, for example the ICO decoder does not support inSampleSize
- an upper bound may make sense: we wouldn't want to try to download gigantic images to downscale them into a tiny image. however the size you mention doesn't seem that large.


We recently talked about potentially adding a favicon API to GeckoView - relying on the code in Gecko. That seems to be the sensible long-term solution. Our current Kotlin/WebExtension solution is limited and there's only so much we can do.

**Comment by codrut-topliceanu** [comment] 2021-07-27 12:47
Added bugzilla issue : https://bugzilla.mozilla.org/show_bug.cgi?id=1722500

**Comment by astarq** [comment] 2021-07-29 22:53
Related thread: https://github.com/cryptee/web-client/issues/113

**Comment by johnozbay** [comment] 2021-07-30 10:42
Possibly also related : https://github.com/mozilla-mobile/fenix/issues/9916

**Comment by j9t** [comment] 2022-04-17 10:06
(Unstale this.)

**Comment by rocketsroger** [comment] 2022-08-03 17:22
From my testing this should be fixed with https://github.com/mozilla-mobile/android-components/pull/12555.  Please confirm.  Thanks!
![Screenshot_20220803_132127](https://user-images.githubusercontent.com/6579541/182670397-e81625cd-c289-4f17-abee-da0d47b52c84.png)

**Comment by j9t** [comment] 2022-08-04 07:21
@rocketsroger, thanks! uitest.com wasn’t actually a good example anymore (I temporarily added an element to link the favicon.ico), but [rt233.com](https://rt233.com/) is. It seems to work indeed.

What does that first section cover in your screenshot? That view doesn’t look familiar to me; does that show rt233.com correctly, too?

**Comment by rocketsroger** [comment] 2022-08-04 15:27
Tested rt233.com and it works as expected as well.  
![Screenshot_20220804_112650](https://user-images.githubusercontent.com/6579541/182886215-fb9557a9-8ac3-4e81-aa93-e53ed5d9a12e.png)

Closing this issue as fixed.  Thanks!

**Closed by rocketsroger** 2022-08-04 15:27 UTC
Labels: 🐞 bug, 🙅 waiting, needs:gv, Feature:Shortcuts, qa-triaged

**Comment by j9t** [comment] 2022-08-05 07:05
Awesome—thanks @rocketsroger and team!

**Comment by j9t** [comment] 2022-10-09 12:56
It seems there was a regression; filed #27347.
