### ISSUE TITLE
[Bug] Crash when using custom tab back button

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#2447] opened 2019-05-13 09:46 UTC
## Steps to reproduce
1. Open a custom tab.
1. Press the back button.

### Expected behavior
You are taken to the previous app from where the custom tab was opened.

### Actual behavior
The app crashes.

### Device information
* Android device: 
  * OnePlus 5T (Android 9)
  * Nexus 6P (Android 8.1)
* Fenix version: 5/13
* [Video](https://drive.google.com/file/d/1UsM_lNLzWqLRWaN0XSca66vMKhXBjDtG/view)
* Could be related to #2414 ?

**Comment by cadeyrn** [comment] 2019-05-13 18:56
Exception:

```
2019-05-13 20:55:45.320 6981-6981/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 6981
    java.lang.RuntimeException: Unable to stop activity {org.mozilla.fenix.debug/org.mozilla.fenix.customtabs.CustomTabActivity}: java.lang.IllegalArgumentException: Required value was null.
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4670)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4737)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:180)
        at android.app.ActivityThread.main(ActivityThread.java:6950)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
     Caused by: java.lang.IllegalArgumentException: Required value was null.
        at org.mozilla.fenix.browser.BrowserFragment.getSessionById(BrowserFragment.kt:689)
        at org.mozilla.fenix.browser.BrowserFragment.onStop(BrowserFragment.kt:509)
        at androidx.fragment.app.Fragment.performStop(Fragment.java:2836)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:933)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2646)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStop(FragmentManagerImpl.java:2621)
        at androidx.fragment.app.Fragment.performStop(Fragment.java:2832)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:933)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2646)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStop(FragmentManagerImpl.java:2621)
        at androidx.fragment.app.FragmentController.dispatchStop(FragmentController.java:290)
        at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:564)
        at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:207)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1454)
        at android.app.Activity.performStop(Activity.java:7161)
```

**Comment by softvision-miralobontiu** [comment] 2019-05-22 13:56
Closing this as a dupe of #2414

**Closed** 2020-08-26 05:28 UTC
Labels: b:crash, 🐞 bug
