### ISSUE TITLE
Add option to search for selected text directly in Fenix with default search engine

### ISSUE THREAD

**Issue by bxtom** [mozilla-mobile/fenix#7600] opened 2020-01-10 18:07 UTC
### Why/User Benefit/User Problem

When user selects text there is no search option (first screenshot). When Google Translate is installed 'Translate' option appears (second screenshot). When Firefox Focus is installed 'Search Privately' appears (third screenshot). When Edge is installed 'Search in Edge' appears (fourth screenshot).

### What/Requirements

Add simple 'Search' option to search directly in Fenix with default search engine selected in settings.

### Acceptance Criteria (how do I know when I’m done?)

There should be simple 'Search' option to search directly in Fenix with default search engine selected in settings.

![01](https://user-images.githubusercontent.com/29851015/72175309-3009ed00-33dc-11ea-8b90-14654dd1345b.jpg)

![02](https://user-images.githubusercontent.com/29851015/72175322-39935500-33dc-11ea-96dc-04da2f26a29e.jpg)

![03](https://user-images.githubusercontent.com/29851015/72175340-4021cc80-33dc-11ea-9a4b-9ece133c1774.jpg)

![04](https://user-images.githubusercontent.com/29851015/72175379-53349c80-33dc-11ea-8857-89f814204c71.jpg)

**Comment by cadeyrn** [comment] 2020-01-10 22:28
Duplicate of #5695.

**Comment by kbrosnan** [comment] 2020-01-10 22:45
Closing as duplicate.

**Closed by kbrosnan** 2020-01-10 22:45 UTC
Labels: 🌟 feature request
