### ISSUE TITLE
[Bug] Crashing on open tab animation

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3001] opened 2019-05-30 13:35 UTC
## Steps to reproduce
1. Open a few tabs.
1. Leave the device idle for a few minutes.
1. Tap to open the tabs, one by one. It doesn't happen frequently.
    1. Expected behavior
Tabs open.
    1. Actual behavior
App crashes while the tab expanding animation is happening.
[tab animation crash.txt](https://github.com/mozilla-mobile/fenix/files/3237201/tab.animation.crash.txt)
    1. Device information

* Android device: Pixel (Android 9)
* Fenix version: 5/30

**Comment by AaronMT** [comment] 2019-05-30 15:32
Not sure if this is related to the crash but in your log I see

```java
 java.lang.NoSuchMethodException: <init> []
        at java.lang.Class.getConstructor0(Class.java:2327)
        at java.lang.Class.getConstructor(Class.java:1725)
        at androidx.constraintlayout.motion.widget.KeyFrames.<clinit>(KeyFrames.java:2)
        at androidx.constraintlayout.motion.widget.MotionScene.<init>(MotionScene.java:18)
        at androidx.constraintlayout.motion.widget.MotionLayout.init(MotionLayout.java:6)
        at androidx.constraintlayout.motion.widget.MotionLayout.<init>(MotionLayout.java:60)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:2)

**Comment by ekager** [comment] 2019-06-03 17:52
Are either of you still seeing this bug?

**Comment by colintheshots** [comment] 2019-06-03 18:36
I cannot reproduce. It's a very odd crash trace. It looks like failed reflection in the MotionLayouts library. But why?

**Comment by sv-ohorvath** [comment] 2019-06-04 15:07
I was able to get this crashing at least 2 times a day, but now I'm not seeing it anymore.

**Comment by kbrosnan** [comment] 2019-06-04 15:48
Lets close this then. Reopen if you reproduce it before we launch else file a new issue.

**Closed** 2020-08-26 20:46 UTC
Labels: Release Blocker, b:crash, 🐞 bug
