### ISSUE TITLE
[Bug]: background video no auto play on loaded in firefox on mobile device like smartphone and tablet

### ISSUE THREAD

**Issue by santhoshnumberone** [mozilla-mobile/fenix#23675] opened 2022-02-10 17:46 UTC
### Steps to reproduce

I have a background video on a webpage, the video is `av1` inside `mp4` container and supported by firefox
Only poster image of `video` tag is displayed, video never starts playing

this is the code

```
<script lang="ts">
  import vi from './assets/videofile.mp4'
  import posterimg from './assets/PosterImage.png'
</script>

<main>
  <video
  autoplay 
  muted 
  loop
  Playsinline
  src={vi}
  poster={posterimg}>
  </video>
</main>

<style>
video 
{
  width: 100%;
  -moz-user-select: none;
  -webkit-user-select: none;
  user-select: none;
  pointer-events: none;
}
</style>
```

Raised this issue in svelte too [background video no auto play on loaded in firefox on mobile device like smartphone and tablet #7243](https://github.com/sveltejs/svelte/issues/7243)

### Expected behaviour

Video starts playing on auto after page is loaded 

### Actual behaviour

Only poster image assigned to the video tag is displayed video never starts playing 

### Device name

Sony Xperia XZ Premium

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

97.1.0

### Device logs

```
firefox browser log details from android browser


Media resource https://mywebsite.com/assets/videofile.87f84cd1.mp4 could not be decoded. mywebsite.com
Some cookies are misusing the recommended “SameSite“ attribute 2
Cookie “_ga” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite analytics.js:35:486
Cookie “_gid” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite analytics.js:35:486
Media resource https://mywebsite.com/assets/videofile.87f84cd1.mp4 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_METADATA_ERR (0x806e0006)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19453)

**Comment by santhoshnumberone** [comment] 2022-02-12 06:40
> A page showing this issue would be useful.

[Same video](https://santhoshnumberone.github.io/videotest/), same issue

**Comment by LaurentiuApahideanSV** [comment] 2022-02-16 17:13
I managed to reproduce the issue on Firefox RC 97.1.0 but not on Nightly 2022-02-16. @santhoshnumberone Could you download the latest Firefox Nightly and see if the issue occurs there?
### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android)

**Comment by santhoshnumberone** [comment] 2022-02-16 17:22
> I managed to reproduce the issue on Firefox RC 97.1.0 but not on Nightly 2022-02-16. @santhoshnumberone Could you download the latest Firefox Nightly and see if the issue occurs there?
> ### Devices used:
> - Google Pixel 6 (Android 12)
> - OnePlus 6T (Android)

Yes the video starts playing automatically on load in Nightly

**Comment by elibroftw** [comment] 2022-02-22 21:08
https://lenerva.com/

I have partly the same problem. The video works the first time I visit but the loop is chopped and if refresh the page, the video gets paused. This doesn't occur on Firefox desktop.

**Comment by elibroftw** [comment] 2022-11-23 17:33
Still an issue

**Comment by jonalmeida** [comment] 2023-01-30 23:48
Closing as fixed since OP said this was [fixed in nightly](https://github.com/mozilla-mobile/fenix/issues/23675#issuecomment-1041904598) in Feb, so it should be fixed in release now as well.

**Closed by jonalmeida** 2023-01-30 23:48 UTC
Labels: 🐞 bug, Feature:Media, needs:triage, qa-triaged
