### ISSUE TITLE
FNX-4925 ⁃ Back button doesn't work on first tap on a Twitter custom tab

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1282] opened 2019-04-01 01:55 UTC
## Steps to reproduce
-Open Twitter App
-Click on a link (default browser Fenix) to open in custom tab
-Tap on the back button to go back to Twitter

### Expected behavior
-Going back to Twitter on the first try

### Actual behavior
-Tapping on the back button doesn't work on the first try (works on second)

### Device information
* Device: Pixel 3
* Android device: 9
* Fenix version: 1.0.1914

**Comment by vesta0** [comment] 2019-04-30 06:06
This is fixed.

**Comment by sv-ohorvath** [comment] 2019-04-30 12:40
Cannot reproduce it either. closing.

**Closed** 2020-08-11 07:31 UTC
Labels: Feature:CustomTabs, eng:qa:verified, 🐞 bug
