### ISSUE TITLE
[Bug] Accept-Language headder should contain the users default language instead of en-US

### ISSUE THREAD

**Issue by marcomg** [mozilla-mobile/fenix#14160] opened 2020-08-25 13:24 UTC
## Steps to reproduce
Use android in another language (in my case Italian), go to a random page with multiple language support (including google.com).
### Expected behavior
Menu and content was published in the right language (for me Italian). 
### Actual behavior
Pages are loaded in English.

I think the fault is in user agent, i can see it is
Mozilla/5.0 (Android 10; Mobile; rv:79.0) Gecko/79.0 Firefox/79.0
and isn't mentioned language.
Firefox menu are in the correct language. 

### Device information
* Android device:
Google Pixel 3a
Android 10 build QQ3A.200805.001
* Fenix version:
79.0.5 (Build #2015758619)
AC: 48.0.15, 8755ac0cd
GV: 79.0.1-20200813192915
AS: 61.0.10.

**Comment by cadeyrn** [comment] 2020-08-25 13:33
The user agent never contains the language. Do you mean the Accept-Language header?

See also #6502.

**Comment by marcomg** [comment] 2020-08-25 13:47
Yas I am sorry, I meant the Accept-Language header.
I think I could close as duplicate?

**Comment by mcarare** [comment] 2020-08-28 13:44
Duplicate of https://github.com/mozilla-mobile/fenix/issues/6502. 
Thank you @marcomg for the report. 
And thank you @cadeyrn for the details mentioned, here and on other issues. 🌟

**Closed by mcarare** 2020-08-28 13:44 UTC
Labels: needs:investigation, 🐞 bug
