### ISSUE TITLE
[Bug] Can't open data URIs from the sync notification

### ISSUE THREAD

**Issue by lnicola** [mozilla-mobile/fenix#9486] opened 2020-03-28 20:49 UTC
## Steps to reproduce

1. Load `data:text/plain,xxx` in a desktop Firefox and send the tab over to Fenix
2. In Fenix wait for the tab to show up (these days they never show up for me unless I synchronize manually), then tap the notification.

### Expected behavior

A new tab opens displaying `xxx`.

### Actual behavior

Nothing.

### Device information

* Android device: OnePlus 6T
* Fenix version: Nightly

CC #1681.

**Comment by eliserichards** [comment] 2020-05-05 19:33
Closing as dupe of #1681

**Closed by eliserichards** 2020-05-05 19:33 UTC
Labels: needs:triage, 🐞 bug

**Comment by lnicola** [comment] 2020-05-05 19:34
Not really a duplicate, since browsing to the URL works. This is specifically about Send Tab.
