### ISSUE TITLE
[Bug] Unable to sign in to FxA: "Missing OAuth parameter: channel_id"

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#17575] opened 2021-01-21 19:55 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Sign in to FxA on desktop (I used a fresh Firefox profile with a `@mockmyid.com` account)
- Click to connect devices (QR code should show up)
- On a fresh fenix profile, click 3-dot -> settings -> Turn On Sync -> Ready to Scan
- scan the QR code

### Expected behavior
Sign in successful

### Actual behavior
Sign in failed. The error displayed in fenix is "Missing OAuth parameter: channel_id":
![image](https://user-images.githubusercontent.com/759372/105404968-73965a00-5bdf-11eb-9ea8-7b08060c7552.png)

Note: I also cannot sign in via email https://github.com/mozilla-mobile/fenix/issues/17576 which may have the same root cause though it seems like it could also be different.

### Device information

* Android device: Moto G5
* Fenix version: Nightly 210121

**Comment by mcarare** [comment] 2021-01-22 12:58
This has happened before, a while ago ( Q4 2020). The problem was present on iOS also, and no changes had to be made on the app side to get it working again. Maybe it is the same a-s problem? 
I can sign in just fine, although I cannot sign in when 2FA is enabled. 
@amedyne do you know who could we ping from a-s for this issue?

**Comment by amedyne** [comment] 2021-01-22 15:50
@mcarare Can you link issues reported before that you think are similar to this? I am checking with the a-s team who to tag.

**Comment by jonalmeida** [comment] 2021-01-22 16:43
Assigning self to investigate if/what the a-s issue may be.

**Comment by jonalmeida** [comment] 2021-01-22 18:29
I was able to reproduce this bug with the following logs which makes this issue look like #17585.

```
2021-01-22 22:28:03.336 16803-16865/org.mozilla.fenix.debug E/FirefoxAccount: Error while running: complete oauth flow
    mozilla.appservices.fxaclient.FxaException$Network: Network error: [no-sentry] Network error: Java error: "fetch error: No direct method <init>(Ljava/lang/String;Lmozilla/components/concept/fetch/Request$Method;Lmozilla/components/concept/fetch/MutableHeaders;Lkotlin/Pair;Lkotlin/Pair;Lmozilla/components/concept/fetch/Request$Body;Lmozilla/components/concept/fetch/Request$Redirect;Lmozilla/components/concept/fetch/Request$CookiePolicy;Z)V in class Lmozilla/components/concept/fetch/Request; or its super classes (declaration of \'mozilla.components.concept.fetch.Request\' appears in /data/app/~~L0gcuhPqv59e6sBJdAZuvg==/org.mozilla.fenix.debug-0YO0GbB9PWLNe6BqteV5qA==/base.apk!classes3.dex)"
        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:43)
        at mozilla.appservices.fxaclient.FirefoxAccount.completeOAuthFlow(FirefoxAccount.kt:747)
        at mozilla.components.service.fxa.FirefoxAccount$completeOAuthFlow$2$1.invoke(FirefoxAccount.kt:206)
        at mozilla.components.service.fxa.FirefoxAccount$completeOAuthFlow$2$1.invoke(FirefoxAccount.kt:30)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invokeSuspend(Utils.kt:71)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invoke(Unknown Source:10)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:31)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:63)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:70)
        at mozilla.components.service.fxa.FirefoxAccount$completeOAuthFlow$2.invokeSuspend(FirefoxAccount.kt:205)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by ddarfantasy** [comment] 2021-01-23 03:21
I was trying to deal with the problem, and I accidentally deleted my bookmarks that haven't been synced.
I know this is my own problem, but I mention it only because I want to emphasize the importance of this issue.
And this has taught me a lesson: never delete local data without a second thought and backup data more frequently.

**Comment by mcarare** [comment] 2021-01-25 08:49
> @mcarare Can you link issues reported before that you think are similar to this? I am checking with the a-s team who to tag.

https://github.com/mozilla-mobile/firefox-ios/issues/7296

**Comment by jonalmeida** [comment] 2021-01-25 18:41
@mcomella could you confirm if this is fixed for you now? It may have been related to https://github.com/mozilla-mobile/fenix/issues/17585 which was fixed on Friday.

**Comment by sflorean** [comment] 2021-02-01 15:53
Tested on different devices on Nightly 2/01 and we didn't encounter any issues when trying to sign in.

**Closed by sflorean** 2021-02-01 15:53 UTC
Labels: S1, a-s, 🐞 bug

**Comment by magusd** [comment] 2021-03-08 00:04
+1, just got this with 2fa enabled

**Comment by mcomella** [comment] 2021-03-09 00:24
> +1, just got this with 2fa enabled

@sflorean Would you be able to test if this is an issue again (if it wouldn't already be caught as part of the usual test plan process)? Thanks!
