### ISSUE TITLE
QAB container and alert/confirmation dialog corners should be rounded

### ISSUE THREAD

**Issue by kuramot6f** [mozilla-mobile/fenix#3806] opened 2019-06-29 23:43 UTC
### Why/User Benefit/User Problem
Most of corner are rounded such as icon, button, snackbar, search bar, menu, and so on.
However, QAB container and modal dialog(download confirmation dialog, alert ()'s dialog) corner hasn't been rounded yet.
I think consistency is important.

**Comment by mheubusch** [comment] 2019-07-02 20:11
@AmyYLee please verify the QAB appears as designed. if so please close this issue.

**Comment by AmyYLee** [comment] 2019-07-02 20:14
@topotropic Can you confirm?

**Comment by topotropic** [comment] 2019-07-03 19:32
The permission menus have 8dp border radius, some context menus don't (for example long press on image, or the download one) –  it would be great to add 8dp corner radius to be consistent. 

The initial QAB design didn't have corner radius but I wouldn't mind to add 8dp top left and right – what do you think @AmyYLee?

**Comment by AmyYLee** [comment] 2019-07-03 21:00
> The permission menus have 8dp border radius, some context menus don't (for example long press on image, or the download one) – it would be great to add 8dp corner radius to be consistent.
> 
> The initial QAB design didn't have corner radius but I wouldn't mind to add 8dp top left and right – what do you think @AmyYLee?

That works for me

**Comment by softvision-miralobontiu** [comment] 2019-07-12 08:17
Verified that QAB container and alert/confirmation dialogues are rounded, with the latest Nightly build 190712 (#11930609) with Google Pixel 3 (Android 9), Huawei P9 Lite (Android 6), and Samsung Galaxy Tab A6 (Android 5.1.1).

**Closed by softvision-miralobontiu** 2019-07-12 08:17 UTC
Labels: E1, QA needed, ready for eng, 💅 polish

**Comment by cadeyrn** [comment] 2019-07-12 09:20
I can't verify the fix for the QAB. On the left side there is no round corner at all, on the right side you can see a line on top without rounding.

<img width="1439" alt="Bildschirmfoto 2019-07-12 um 11 20 24" src="https://user-images.githubusercontent.com/1100614/61117571-13c1dd80-a497-11e9-917d-60b15f4642ff.png">

HTC U11, Android 8.0.

/cc @ekagerrounded.

**Comment by Scripterr** [comment] 2019-07-12 09:30
The QAB also seems to blocking some fixed content at bottom. 
![Screenshot_20190712-145849~2](https://user-images.githubusercontent.com/42364681/61118117-95117400-a487-11e9-86b7-4ee9562dec9a.png)

**Comment by cadeyrn** [comment] 2019-07-12 09:36
@Scripterr This is not related to the rounded corners at all. You should create a new issue if you think there are other problems with the QAB.

**Comment by Scripterr** [comment] 2019-07-12 09:51
I issue is related because the PR #3990 which was supposed to solve this issue is orginated from here which caused the regression.

**Comment by cadeyrn** [comment] 2019-07-12 14:02
PR #3990 says "Adds corner radius to QAB and dialogs", nothing about "blocking some fixed content at bottom"…

**Comment by ekager** [comment] 2019-07-12 14:30
So @Scripterr is correct. To have rounded corners on the QAB, we would have to cover web content, or else what would be behind the cut out corners? Just empty space? After thinking about this more I think we should undo the QAB change. Is that okay with UX @AmyYLee ?

**Comment by ekager** [comment] 2019-07-12 14:54
Just chatted with @AmyYLee and we're going to take away the rounded corners here for now and maybe reevaluate when redesigning the QAB / bringing back collapsible bar here.
