### ISSUE TITLE
FNX2-13567 ⁃ Auto Translate

### ISSUE THREAD

**Issue by anmol257** [mozilla-mobile/fenix#11682] opened 2020-06-17 11:03 UTC
### What is the user problem or growth opportunity you want to see solved?
Firefox should Autotranslate text and webpage. It will save users a lot of time and effort.

### How do you know that this problem exists today? Why is this important?
This feature is also included in other browsers. It is important because the internet is connected irrespective of languages. In the fast-evolving world, it would foster connectivity and sharing across people from different languages, thereby fulfilling the purpose of internet

### Who will benefit from it?
Everyone.
If its includes as default it would be great.
It can also be included as an add on.

**Comment by cadeyrn** [comment] 2020-06-17 11:09
Duplicate of #6133.

**Comment by anmol257** [comment] 2020-06-17 11:24
> 
> 
> Duplicate of #6133.

Ohh
Thanks for letting me know.
So should I close this issue? or leave it open.
As on  #6133, no solution has been reached upon as of yet.

**Comment by SS1113** [comment] 2020-06-17 11:33
@anmol257 you can close the issue if want otherwise someone from Mozilla will close it. Thanks for the feature request! I also want translation feature.

**Comment by sheikh-azharuddin** [comment] 2020-06-17 12:41
That thread not updated since last year...auto translation feature is also Missing in desktop version so I highly doubt they will add the feature in mobile version....one thing I don't understand what is the issue in adding auto translate feature? All other chromium browsers have this...in fact kiwi has 4 translation engines

**Comment by SS1113** [comment] 2020-06-17 12:44
@sheikh-azharuddin IIRC, someone on Reddit was mentioning that Mozilla is working on adding translation feature to desktop. So if it comes there then I'm sure it'll come to Fenix as well.

**Comment by sheikh-azharuddin** [comment] 2020-06-17 12:49
> @sheikh-azharuddin IIRC, someone on Reddit was mentioning that Mozilla is working on adding translation feature to desktop. So if it comes there then I'm sure it'll come to Fenix as well.

bergumont or some project....which is running since last year...someone said it will complete next year😓😅🤣
The question is why can't they integrate google translation engine or microsoft translation engine in the browser...what's the issue

In their free time let them develop a new engine from scratch...when we come across different languages page the only obvious reason is to switch to other browsers which defeat the purpose of firefox....a simple question if I have to use chrome/edge for translation why use firefox?

**Comment by cadeyrn** [comment] 2020-06-17 12:51
> one thing I don't understand what is the issue in adding auto translate feature?

> The question is why can't they integrate google translation engine or microsoft translation engine in the browser...what's the issue

It's very expensive if you have to pay the API usage for millions of users. It's not free, it's the business of companies like Google and Microsoft. This could be an issue (and AFAIK it was a reason why it was never enabled for the Desktop Firefox).

**Comment by sheikh-azharuddin** [comment] 2020-06-17 12:55
> > one thing I don't understand what is the issue in adding auto translate feature?
> 
> > The question is why can't they integrate google translation engine or microsoft translation engine in the browser...what's the issue
> 
> It's very expensive if you have to pay the API usage for millions of users. It's not free, it's the business of companies like Google and Microsoft. This could be an issue (and AFAIK it was a reason why it was never enabled for the Desktop Firefox).

But how come kiwi has 4 translation engine? Kiwi is now an open source browser I don't think they paid for API....also brave browser ( a baby born from firefox 😅) how come it is using Google translator? What I think the Google translation engine is part of chromium browser... chromium is an open source browser...so is it not possible to use the code or some other engine? 😣

**Comment by SS1113** [comment] 2020-06-17 12:59
@sheikh-azharuddin AFAIK, they definitely paid for the translation services!

**Comment by sheikh-azharuddin** [comment] 2020-06-17 13:04
> @sheikh-azharuddin AFAIK, they definitely paid for the translation services!

For 4 translation engines😅I doubt...

**Comment by cadeyrn** [comment] 2020-06-17 13:07
I can't speak about other browser because I know neither their implementation nor their business and finances. I only know that it's not free to use the translation APIs of the big companies.

> so is it not possible to use the code or some other engine?

The code is not the problem. Firefox for Desktop has a working translation feature (it can be enabled via about:config, you only have to get your own API keys). It's the API usage that costs.

> For 4 translation engines😅I doubt...

Why not? Usually you don't pay for the number of engines but for the amount of translated content. I don't know the prices of the different providers but I don't thinkt that it really matters whether there is one engine or four engines because four engines does not mean four times the amount of translated text.

**Comment by sheikh-azharuddin** [comment] 2020-06-17 13:22
@cadeyrn sound good...I saw the translation flag in firefox about config....is it possible to use translation API key by end users ? Or mozilla can only do it? Regarding 4 engines it provides users with multiple options to choose their preferred engine like most user don't trust google for security. Yeah probably I think they are not paying for translation API key but for translated content...maybe getting some revenue from that ...for example mozilla adds a ref for every google search...it probably provides some revenue to mozilla... which i support and is required to run a business...
I will research further on this how other browsers have implemented

**Comment by SS1113** [comment] 2020-07-07 16:53
@anmol257 the issue #6133 is talking about adding a translation feature and it doesn't mention anything about automatically translating websites so I think this issue is asking a new feature.

**Comment by anmol257** [comment] 2020-07-08 03:27
> 
> 
> @anmol257 the issue #6133 is talking about just adding a translation feature and it doesn't mention anything about automatically translating websites so I think this issue is asking a new feature. So you can keep it open.

Great Observation @SS1113 .I'll let this issue remain open. In the mean time have a great day.

**Comment by cadeyrn** [comment] 2020-07-08 07:28
I can't see any difference between #6133 and this issue. Both are about adding a website translation feature. Especially since it was said "this feature is also included in other browsers" it's clear that it's exactly the same as #6133 that also refers to the same feature of other browsers. So it's still a duplicate and any further discussion should happen there.

**Comment by ekager** [comment] 2020-08-27 15:49
closing for #6133

**Closed by ekager** 2020-08-27 15:49 UTC
Labels: needs:triage

**Comment by anmol257** [comment] 2020-08-27 16:37
@ekager 
Firefox users do deserve auto-translate feature.
So it would be great if firefox considers it.

**Comment by sheikh-azharuddin** [comment] 2020-08-27 16:43
Desktop version even don't have the feature... Highly doubt it will be added to fenix... Anyway please atleast add the add on translation web pages as a workaround

**Comment by cadeyrn** [comment] 2020-08-27 17:02
> Desktop version even don't have the feature.

It has, but disabled by default.

After it was alredy said several times (and the last time one hour ago!) that it's a duplicate of #6133 any further discussion should happen there.
