### ISSUE TITLE
[Bug] Fenix sometimes slows the graphics in other apps

### ISSUE THREAD

**Issue by lnicola** [mozilla-mobile/fenix#8177] opened 2020-02-06 18:49 UTC
## Steps to reproduce

Not sure. Turn on WebRender and use as daily browser for a while.

### Actual behavior

Sometimes the other apps start to lag. This can be easily seen when scrolling the app drawer -- it's very jittery. Scrolling in Fenix works fine IIRC. Turning off the screen has no effect, but killing Fenix fixes it.

### Device information

* Android device: OnePlus 6T, Android 10
* Fenix version: Nightly

**Comment by mcomella** [comment] 2020-11-13 17:33
@lnicola We haven't seen this ourselves so the best way for us to understand what's going on would be if you could grab a profile for us. Would you be able to? There are two methods:
1) Preferred: use the Firefox Profiler https://profiler.firefox.com/docs/#/./guide-remote-profiling?id=setup
2) Less preferred, may contain sensitive data (so perhaps send to us individually rather than posting on GH): use the system tracer built into Android: https://developer.android.com/topic/performance/tracing/on-device

We haven't used the second option yet so I'm not sure if it'd give us granular enough info to help us debug this but it may give us info outside of Firefox that may also be useful for debugging.

Let us know, thanks!

**Comment by lnicola** [comment] 2020-11-13 17:38
Thanks, I'll try to see what I can do. Generally the other apps get slowed down, not Fenix, so the system tracer will probably be more useful.

By the way, this is still happening for me.

**Comment by mcomella** [comment] 2020-12-02 22:44
Triage: I wonder if fenix is using too much memory (e.g. from memory leaks) and that causes other apps to slow down.

@lnicola Can you reproduce this in the latest Nightly? csadilek fixed a few more known memory leaks.

**Comment by mcomella** [comment] 2020-12-16 22:38
We haven't received a response and we're unable to reproduce this: closing. Please reopen this if you can still reproduce.

**Closed by mcomella** 2020-12-16 22:38 UTC
Labels: eng:performance, 🐞 bug
