### ISSUE TITLE
[Bug] Updating app with (Finnish) locale will lose bundled search engines (DDG)

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#15737] opened 2020-10-06 23:29 UTC
## Steps to reproduce
Update the app with the Finnish language set.

### Expected behavior
DDG was available as a search engine before upgrade
DDG is available as a search engine after upgrade

### Actual behavior
❌  DuckDuckGo is **not available** in the defaults search engine list on Finnish language. Restarting app doesn't bring them back.
✔️  Twitter is not available in the default search engine list;

❗  This case is solved by **clearing data** and then setting Finnish language as default

Returning to english locale doesn't bring back missing engines. Requires app restart.

Filing from #13452

**Comment by Mugurell** [comment] 2020-10-13 13:09
Hello,

I've tested while having `Suomi` as the system language
- with a fresh install of 79.0.2 and saw that it shown Twitter as an option but no DDG.
- 79.0.2 updated to the latest version from Playstore shows DDG and not Twitter (the desired behavior)
- a fresh install of Fenix Nightly shows DDG and not Twitter.

Asking QA to recheck if this is still an issue or can be closed.

**Comment by sflorean** [comment] 2020-10-13 16:23
Tested and updated Release, Beta, and Nightly versions following the steps provided with Google Pixel 3 (Android 11) & Motorola Nexus 6 (Android 7.1.1) and we couldn't reproduce the issue. Closing this as fixed.

**Closed by sflorean** 2020-10-13 16:23 UTC
Labels: Feature:SearchProvider, eng:qa:needed, 🐞 bug
