### ISSUE TITLE
[Bug]: open with app doesn't work the second time

### ISSUE THREAD

**Issue by 424344** [mozilla-mobile/fenix#24471] opened 2022-03-26 18:24 UTC
### Steps to reproduce

1. configure fenix to open links in apps
2. load the page:  https://www.androidpolice.com/go-adventuring-in-titan-quest-and-balders-gate-2-with-this-weekends-sales/
3. choose an app or game and click on its link
4. the play store app is opened showing the chosen app
5. click back
6. click on another app or game (or even the previous one)

### Expected behaviour

the play store app should be opened, like the first time.

### Actual behaviour

the web site of the play store is opened instead of the app
the web site is slower to load, and also I have to be logged in to buy an app.
Instead I want to always use the play store app.

### Device name

samsung galaxay a50

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1

**Comment by jknair0** [comment] 2022-03-27 10:16
I found similar issue. when I use google one app which on clicking on start editing opens a URL which in turn takes me to Google Photos App if Chrome is my default app. but it doesn't do the same with firefox. The website never loads.

https://user-images.githubusercontent.com/12934264/160276849-fb8803df-4dd9-4ac9-9a70-690a8152d200.mp4

https://user-images.githubusercontent.com/12934264/160276851-eae3ace5-6b97-4708-9964-7aee9a31686d.mp4

**Comment by LaurentiuApahideanSV** [comment] 2022-03-28 11:51
I can confirm the issue is reproducible on Firefox Preview Nightly 2022-03-28. The issue has also been reported here: https://github.com/mozilla-mobile/fenix/issues/23684. I will close this issue as it will be handled there.

**Closed by LaurentiuApahideanSV** 2022-03-28 11:51 UTC
Labels: 🐞 bug, needs:triage
