### ISSUE TITLE
FNX2-15250 ⁃ [Intermittent] UI test failure createBookmarkFolderTest

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#10911] opened 2020-05-25 22:16 UTC
Noticed in #10812. [UI test logs](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6172819471604749814/executions/bs.6fa71d13601d1f5d/testcases/1/test-cases).

`createBookmarkFolderTest` failed with the following stacktrace:

```
java.lang.IllegalStateException: activityTestRule.activit…wById(R.id.bookmark_list) must not be null
at org.mozilla.fenix.ui.BookmarksTest$createBookmarkFolderTest$3.invoke(BookmarksTest.kt:135)
at org.mozilla.fenix.ui.BookmarksTest$createBookmarkFolderTest$3.invoke(BookmarksTest.kt:35)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openBookmarks(ThreeDotMenuMainRobot.kt:127)
at org.mozilla.fenix.ui.BookmarksTest.createBookmarkFolderTest(BookmarksTest.kt:128)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
```

**Comment by sv-ohorvath** [comment] 2020-06-03 13:20
I cannot reproduce this running the test locally or on Firebase. 
@mcarare When possible, could you have a look if you can figure out why/when ById(R.id.bookmark_list) returns null? Thank you

**Comment by sv-ohorvath** [comment] 2020-06-09 11:36
This hasn't appeared recently looking at the test runs, might have been a one-time thing? I'm going to close it and will reopen if needed.

**Comment by kbrosnan** [comment] 2020-07-09 00:56
Another occurrence today

https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5288541269677360361/executions/bs.a418e71cd2960fbf/testcases/1/test-cases

**Comment by sv-ohorvath** [comment] 2020-07-13 12:00
Disabling test for now: https://github.com/mozilla-mobile/fenix/pull/12504

**Closed** 2020-08-27 15:40 UTC
Labels: Feature:Bookmarks, disabled-test, eng:tech-debt, eng:ui-test, intermittent-test
