### ISSUE TITLE
FNX-73 ⁃ [Bug] It's not possible to distinguish between bookmarks and history suggestions on the address bar.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2037] opened 2019-04-25 17:19 UTC
## Steps to reproduce
Browser a website
Save some pages as bookmarks
Type the title of some of the page's you browsed previously on the address bar

### Expected behavior
You can tell where the suggestions are coming from through icons (bookmarks, history, etc)

### Actual behavior
On the address bar Fenix has a magnifying glass icon for search suggestions, a chain icon for link on the clipboard, but it has no icons for history and bookmarks, instead showing empty favicons box with letters inside, which makes it impossible to tell these two apart.

### Device information
* Android device: 8.0
* Fenix version: 1.0.1917

**Comment by ekager** [comment] 2019-06-26 17:09
I do think this would help clarify awesomebar results for people. Could we just add the star favorite icon instead of the site favicon here?

**Comment by topotropic** [comment] 2019-07-11 20:06
@Verdi what's your take on this?

**Comment by Verdi** [comment] 2019-07-26 20:05
I don't know the history here or whether there was a conscious decision not to denote bookmark URLs in Fenix (maybe @shorlander knows?). 

We don't have much data on this topic. [A desktop eyetracking study](https://docs.google.com/presentation/d/124zAhCc4wnbsoUSVD18SLF6uCu09Cc6AYFtIrXz2Psw/edit#slide=id.g22bd6c370c_0_212) showed that chunking (grouping bookmarks) and favicons helped in bookmark recognition but it wasn't very significant. As far as I know, showing a bookmark star is something we’ve just always done. I suspect the favicon, title and url are much more important than a bookmark star. I doubt it hurts though. Also, I don't believe we show an icon for history - just bookmarks, open tabs and search suggestions. Looking at Fennec, Fenix and iOS, my guess is the fake favicons (colored square with a letter) are not particularly helpful. On desktop we use a globe with meridian lines. It may be that it's neutral appearance helps actual favicons stand out more.

**Comment by lime124** [comment] 2019-07-26 22:10
this is going to take some more investigation and design work to ensure there is a consistent cross-product experience of how results are being displayed. i'm going to open a new issue to cover that and link this to it. removing ux label

**Comment by ekager** [comment] 2019-08-01 03:35
I think it would also be more helpful to do #482 (deduping/merging equal results)
In AC see: https://github.com/mozilla-mobile/android-components/issues/1368 and https://github.com/mozilla-mobile/android-components/issues/1367

**Comment by pocmo** [comment] 2019-08-01 16:19
Are you sure about the merging? Those are two separate actions (Switching to an open tab vs. visiting a page). Comparing with desktop I also get both options - they just visually look different (Visit vs. Switch).

**Comment by ekager** [comment] 2019-08-01 20:38
@pocmo History and Bookmarks should both be opening a new tab with the URL, right? 
It's the current sessions that have a different action?
Like mentioned in the AC bugs, maybe we can group by action and dedupe/merge there?

**Comment by ekager** [comment] 2019-08-02 02:22
Like mentioned here https://github.com/mozilla-mobile/android-components/issues/1368

**Comment by kbrosnan** [comment] 2020-07-27 05:45
Duplicate of #12622

**Closed** 2020-08-11 13:42 UTC
Labels: Feature:Bookmarks, Feature:History, Feature:Search, P2, eng:quality, feature request 🌟
