### ISSUE TITLE
Use current tab when opening bookmark from home

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#25362] opened 2022-05-24 15:14 UTC
Issue is raised by contributor @r6squeegee
The scenario of bookmarks showing on the home page, doesn't work. This is my most common flow :

1. I'm on a web page, and done with it
2. I click on the url field to bring up the home screen so I can see my book marks (1 click on a big bar, adverse to 2 clicks for going to settings (small icon) then bookmarks (on a popup menu))
3. I click on the next bookmark

That use to open the new page in the existing tab, it doesn't anymore. If I go through that routine with 8 bookmarks I end up with 8 tabs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20546)

**Comment by Cheap-Skate** [comment] 2022-05-25 10:12
> This behaviour seems like a design decision. We should review to see if this behaviour is correct.

Yes please.

So far you & @czlucius have been addressing this piecemeal and bottom-up, we very much appreciate your efforts. But perhaps it needs a top-down look at the whole issue eg #20012 which can be summarised as:- *Every action on the Home screen opens a new tab, for no obvious reason. This is completely different to (all?) other browsers and many (most?) users find it horribly inconvenient.*

Thanks again.

**Comment by maverick74** [comment] 2022-08-06 12:57
What I find truly disturbing (and frustrating) is the amount of people complaining about this single issue without having any fixing attempt from Mozilla.

If only I could code well enough... (but then again, even if I could, it would probably end up not being accepted... Some people like to shoot themselves in the foot over and over and over again...)

**Comment by maverick74** [comment] 2022-08-06 13:25
> That use to open the new page in the existing tab, it doesn't anymore. If I go through that routine with 8 bookmarks I end up with 8 tabs.

![screenshot-mozilla-firefox](https://user-images.githubusercontent.com/14912461/183250858-3a6498d0-bc84-439f-834b-73a1a4d3bb2d.jpg)


I keep closing all tabs every week (even the important ones LOST between the garbage), but my "8 tabs" keeps preferring the horizontal position just after 2 days...

**Comment by czlucius** [comment] 2022-08-06 14:49
Technically, this problem is not very easy to solve.
Either
- Re-design/architect the app such that new tab button opens an actual tab (and not the home screen) as per #20012
or
- Adding a flag/boolean value at all entry points to the home screen to indicate whether to open in a new tab or the current one (if there is one, if not open in a new tab)

Both of these do not seem easy, require a long time, and may introduce new issues.

**Comment by maverick74** [comment] 2022-08-06 19:54
> Both of these do not seem easy, require a long time, and may introduce new issues.

Well... I would like to know who was the brainiac we should thank to for being in this mess?

He surely deserves an award! X(

All things considered, I think the second choice would need a bit less work... But I'm not a great coder so I can be very wrong.

All in all, I wish this "design decision" would just go away

**Comment by cadeyrn** [comment] 2022-08-07 11:15
>  but my "8 tabs" keeps preferring the horizontal position just after 2 days...

This is not a "8" but the infinity symbol. This is always shown if you have more than 99 open tabs. That's implemented that way and not a bug.

**Comment by 424344** [comment] 2022-08-07 14:04
> Well... I would like to know who was the brainiac we should thank to for being in this mess!

yeah, probably a ui designer who wanted to prove himself by creating something "innovative".

**Comment by maverick74** [comment] 2022-08-08 12:18
> > but my "8 tabs" keeps preferring the horizontal position just after 2 days...
> 
> This is not a "8" but the infinity symbol. This is always shown if you have more than 99 open tabs. That's implemented that way and not a bug.

... I was just joking!!! (I may look a little dumb sometimes, but I'm not THAT dumb)
I learned about infinity (and it's symbol) around my 5th school year...

And I know it pops-up after 99, also.
(and that's the point of the joke: with the current implementation, in two days, I end up with more than 99 tabs where more than 80% is garbage tabs, duplicated tabs and so on)

I was just playing with how it looks 😄.

(and yes, I know that I'm expressing myself in a bad way! In a non productive way and bla bla bla. But there is a very big pink elephant in room that no one wants to talk about... Or should I say that it seems no one wants to "work" about/on.)

**Comment by dylantrevor87** [comment] 2022-08-14 09:23
> Technically, this problem is not very easy to solve.

Instead of changing the current behaviour maybe it could be easier a different approach: I believe the issue is that users end with lots of tabs open (myself included). What I think is wrong is that these tabs are never closed when I tap on back button.
If they were automatically closed while tapping back I think the main issue would be resolved.
So please add an option to "close on back" the tabs.
Even better add this "close on back" option on desktop too!

**Comment by r6squeegee** [comment] 2022-08-15 17:47
> > Technically, this problem is not very easy to solve.
> 
> Instead of changing the current behaviour maybe it could be easier a different approach: I believe the issue is that users end with lots of tabs open (myself included). What I think is wrong is that these tabs are never closed when I tap on back button. If they were automatically closed while tapping back I think the main issue would be resolved. So please add an option to "close on back" the tabs. Even better add this "close on back" option on desktop too!

That won't solve the issue, the issue is when some one opens a new bookmark it should open in the current tab. The back button is never used.

The simplest scenario is this :
- some one has 3 news sites bookmarked, they check news twice a day.
- they click on bookmark 1, read the news, and they're finished with the site
- they click on bookmark 2, read the news, and they're finished with the site
- they clikcon bookmark 3, read the news and they're finished with the site

With normal behaviour, you still have 1 tab open and you can continue on with your life.

With the new FF behaviour, you'll have 3 tabs open. By the end of the day you'll have 6 tabs open, Next thing you know you're one of "those people" with 40 tabs open in the browser - instead of 1.

**Comment by 424344** [comment] 2022-08-15 20:35
after reading the news many users click back button to return to home page (me included, but also verified with friends of mine)
so it could at least solve partially the issue. better than nothing at all.

**Comment by jacktose** [comment] 2022-08-15 23:07
The reason I'm supporting this is not the workflow preference above but a feature regression from Fennec: breaking bookmarklets. Bookmarklets (bookmarks with javascript content) that are “opened” in the existing page to take some action on it.

**Comment by maverick74** [comment] 2022-08-25 14:09
> Bookmarklets are bookmarks with javascript content that are “opened” in the existing page to take some action on it.

So... Are you saying that it would be easy to just alter the code of bookmarklets to instead of opening a _blank page it would target the current one instead?!

**Comment by headbank** [comment] 2022-08-25 17:46
> > Bookmarklets are bookmarks with javascript content that are “opened” in the existing page to take some action on it.
> 
> So... Are you saying that it would be easy to just alter the code of bookmarklets to instead of opening a _blank page it would target the current one instead?!

No ... the problem is the context in which the script in the bookmarklet executes. Most bookmarklets manipulate, or draw upon content in, the currently-loaded page. They might load a new page or open a new tab as part of what they do, but that's not the issue.

**Comment by czlucius** [comment] 2022-08-26 03:57
Bookmarklets from the bookmarks menu work well if they do not open a new tab.

**Comment by maverick74** [comment] 2022-08-26 11:09
> No ... the problem is the context in which the script in the bookmarklet executes. Most bookmarklets manipulate, or draw upon content in, the currently-loaded page. They might load a new page or open a new tab as part of what they do, but that's not the issue.

I'm not sure i'm following you (maybe it's my _fantastic_ english...): is that on Firefox? Or in other browsers?
From your sentence i get the feeling the default behavior is to work on the current tab, and it is bookmarklets' code that specifically alter that.
This contrast with the feedback 've had that this is a very _complicated_ issue to solve...



> Bookmarklets from the bookmarks menu work well if they do not open a new tab.

Let me fix that: _Bookmarklets from the bookmarks menu work very well!!!_ :)
(I actually didn't get what you mean with _if they do not open a new tab._)

I think the biggest missing piece is (taken from @klint 's amazing resume: https://github.com/mozilla-mobile/fenix/issues/20012#issuecomment-1032881202 ):

_- If you click in the address bar or press the Home button in a tab/web page, any link obtained from the Home Page should reuse the tab you came from_

Which is what this issue is about, it seems :)

**Comment by czlucius** [comment] 2022-08-26 11:33
> Let me fix that: Bookmarklets from the bookmarks menu work very well!!! :)
(I actually didn't get what you mean with if they do not open a new tab.)

I see. I guess the new tab works as well, and that's good.

**Comment by maverick74** [comment] 2022-08-26 12:11
> I see. I guess the new tab works as well, and that's good.

I'm getting the feeling we're not on the same page... :)
While on a website, If i go to the "3 dot Menu" > Bookmarks > and tap a Bookmark, it loads that bookmark over the website i was previously.
That's what i mean that works well!

We also have the option to load bookmark on a new page (that i rarely use), that seems to be working well also...

**Comment by Unlogic-dot-se** [comment] 2022-10-07 15:10
I find it very odd that opening bookmarks via the three dot menu or via the home screen results in different behavior. 

The automatic opening of new tabs when clicking on the bookmarks on the home screen results in unnecessary tabs and inconsistent behavior like many before me have pointed out.

**Comment by israelromero19** [comment] 2022-10-10 23:46
https://mzl.la/3CJyf8y

**Comment by Obscerno** [comment] 2022-10-11 15:00
I'm trying to get this in front of an internal team through connect.mozilla.org, so maybe we can get direction on this.

If you can, [vote on the post](https://connect.mozilla.org/t5/ideas/on-firefox-mobile-make-home-page-links-open-in-current-tab/idi-p/15672) and leave a comment if you have anything to add! The more support, the more likely it'll make it.

**Comment by csadilek** [comment] 2023-01-30 20:40
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813756

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2023-01-30 20:40 UTC
Labels: 🐞 bug, needs:triage
