### ISSUE TITLE
[Bug] www.google-analytics.com not blocked even with strict ETP on apkmirror.com

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14071] opened 2020-08-22 14:30 UTC
from https://www.reddit.com/r/firefox/comments/ieh6ad/so_tracking_protection_now_allowing_google/
## Steps to reproduce

open apkmirror.com
set etp to strict mode

### Expected behavior
www.google-analytics.com is blocked
### Actual behavior
it is not
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly 200822 06:01 (Build #2015759411)
AC: 56.0.20200821184145, 96a8a14dc
GV: 81.0a1-20200820093209
AS: 61.0.12

**Comment by wisniewskit** [comment] 2020-08-24 14:34
Actually, the requests are still being blocked, but the "tracking content" summary is unaware of that fact. The way it works is that the webcompat addon needs to be able to bypass regular tracking protection to replace it with a shim ([more info here](https://groups.google.com/g/mozilla.dev.platform/c/28eWGe4s5a80)). We'll need to find a way to update the summary to indicate this.

@Amejia481, who would be best to talk to in order to figure out how to update the summary UI so it's aware that the requests are being shimmed instead of just being blocked?

**Comment by Amejia481** [comment] 2020-08-24 14:45
It depends in which layer of the stack we want to make the update, Fenix,AC,GV, or Gecko, lets chat about it and see the pros and cons. Right now the UI gets populated from [ContentBlocking:RequestLog](https://searchfox.org/mozilla-central/source/mobile/android/modules/geckoview/GeckoViewContentBlocking.jsm#40).

**Comment by Amejia481** [comment] 2020-08-24 19:55
I tested locally with different variants beta and release, and the issue is not reproducible. It could a good idea, if the QA team adds this to their test plan to avoid leaking the bug to other variants.

**Comment by ebalazs-sv** [comment] 2020-08-26 08:59
This issue is reproducible on Nightly 200826 GV 81, from 8/26 with Pixel 2 (Android 9).

The workaround from https://github.com/mozilla-mobile/fenix/issues/14071#issuecomment-678708955 solves the issue.

Not reproducible on RC 80.1.0 GV 80, from 8/25 and Beta 80.0.1-beta.2 GV 80 from 8/18.

I have added a test to our smoke test suite. I will remove the qa:needed label for now.

**Comment by Amejia481** [comment] 2020-08-26 13:31
Thanks @ebalazs-sv!

**Comment by clientenq** [comment] 2020-08-28 22:12
How can workaround from #14071 (comment) solve the issue if the stable version has no about:config ?

**Comment by Amejia481** [comment] 2020-08-28 22:14
This feature is only activate on nightly, as we are testing it and  on nightly `about:config` is accessible :)

**Comment by Amejia481** [comment] 2020-09-08 13:32
We are tracking the update of the extension on this Bugzilla bug  https://bugzilla.mozilla.org/show_bug.cgi?id=1661330

**Comment by softvision-miralobontiu** [comment] 2020-10-08 13:04
This issue still reproduces on 10/8 Nightly build on HTC 10 (Android 8):
![etp](https://user-images.githubusercontent.com/40694158/95462210-e573cc00-097f-11eb-8e56-3deaf6fa77f5.png)

**Comment by Amejia481** [comment] 2020-10-08 14:00
We[ landed a patch for exposing the right category,](https://github.com/mozilla-mobile/android-components/pull/8630) but we still need to add the category in the ui this will be covered on https://github.com/mozilla-mobile/fenix/issues/15783

**Comment by Amejia481** [comment] 2020-10-27 15:30
This should be fixed in nightly :)

**Comment by Amejia481** [comment] 2020-10-27 15:31
@s-ankur could you verify if it's working for you? :)

**Comment by s-ankur** [comment] 2020-10-27 15:36
seems to work properly

**Comment by Amejia481** [comment] 2020-10-27 15:44
Thanks for verifying, the QA team will take a look as they have a wider range of devices where they can test :)

**Comment by ebalazs-sv** [comment] 2020-10-29 08:02
Verified as fixed on Nightly 201029 05:01 (Build #2015772457) GV 84.0a1 from 10/29 with Motorola Moto G6 (Android 8), Google Pixel 2 (Android 9), Huawei P9 Lite (Android 7), Nexus 5 (Android 6.0.1).
I will remove the qa:needed label and close this issue.

**Closed by ebalazs-sv** 2020-10-29 08:02 UTC
Labels: Feature:TrackingProtection, S2, eng:qa:needed, 🐞 bug

**Comment by Amejia481** [comment] 2020-10-29 14:21
Thanks @ebalazs-sv!
