### ISSUE TITLE
[Bug] Typing in words separated by colon in address bar (e.g. "define:word") does nothing

### ISSUE THREAD

**Issue by oakkitten** [mozilla-mobile/fenix#19830] opened 2021-06-04 18:42 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Steps to reproduce

Type "define:word" into address bar, press the "go" key

### Expected behavior

The search with the phrase opens

### Actual behavior

The keyboard gets minimised and the phrase vanishes; otherwise, nothing happens

### Device information

* Device vendor / model and Android version: Xiaomi Mi A2, Android 11
* Firefox for Android version: 91.0a1 Thursday 6/3 @ 5:05 PM

**Comment by kbrosnan** [comment] 2021-06-04 20:36
Effectively a dupe of https://github.com/mozilla-mobile/fenix/issues/10516 even if the description of the current behavior changed

**Closed by kbrosnan** 2021-06-04 20:36 UTC
Labels: needs:triage, 🐞 bug

**Comment by oakkitten** [comment] 2021-06-04 21:50
I saw #10516, but its description reads that stuff like `test.whatever` is treated as URL when it's not not meant to be. `test.whatever` is a possible URL, though, so current behavior is not a bug, and offering to search that instead is more of a feature request. 

The behavior this issue is about, on the other hand, is definitely wrong and the fix that will close this issue will not close the other one or vice versa
