### ISSUE TITLE
Adaptive color for status bar and panel

### ISSUE THREAD

**Issue by WhiteApfel** [mozilla-mobile/fenix#5475] opened 2019-09-22 06:30 UTC
### Why/User Benefit/User Problem
Many sites have already implemented the definition of a dark browser theme. They set their background color values. But this color is different from the standard color of the dark theme of Firefox. It looks ugly and unnatural.
### What/Requirements
You need to check which background-color is used by the site. Then set this color to the background for all panels and bars.
Not always sites use the theme-color meta tag.
In the "Via-browser" theme-color is the color of the upper left pixel. In this case, the browser looks like a whole and makes a good impression.

The screenshots show how the same site looks on two browsers.

**Comment by WhiteApfel** [comment] 2019-09-22 06:31
![photo_2019-09-22_13-29-07](https://user-images.githubusercontent.com/29860366/65383270-37c65880-dd3d-11e9-9769-bedf30405db2.jpg)
![photo_2019-09-22_13-29-10](https://user-images.githubusercontent.com/29860366/65383271-385eef00-dd3d-11e9-8ff8-f893b9031a38.jpg)

**Comment by NotWoods** [comment] 2019-09-23 00:42
Duplicate of #1178. Websites can inform browsers which color they'd like to use for the toolbar, but we don't support it just yet.

**Closed by NotWoods** 2019-09-23 00:42 UTC
Labels: 🌟 feature request
