### ISSUE TITLE
[Bug] [Crash] IllegalStateException: SessionSuggestionProvider returned duplicate suggestion IDs

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/fenix#3486] opened 2019-06-14 17:48 UTC
I've had this profile for a while now, and running master from it. i.e. I don't have meaningful STR.

Latest build from master today, but it has been evident for a few days. Now I have it in this state, it is 100% reproducible.

### STR
1. Open the browser. 
1. Open a new tab.
1. Type the first letter of a URL or search term.

### Expected
The URL bar to be calmly waiting for the next letter.

### Observed
Crash.

```
mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalStateException: SessionSuggestionProvider returned duplicate suggestion IDs)
mozac/CrashReporter: Showing prompt
ActivityManager: START u0 {flg=0x10018000 cmp=org.mozilla.fenix.debug/mozilla.components.lib.crash.prompt.CrashReporterActivity (has extras)} from uid 10211
 FATAL EXCEPTION: main
 Process: org.mozilla.fenix.debug, PID: 8631
 java.lang.IllegalStateException: SessionSuggestionProvider returned duplicate suggestion IDs
  at mozilla.components.browser.awesomebar.BrowserAwesomeBar.processProviderSuggestions$browser_awesomebar_release(BrowserAwesomeBar.kt:161)
  at mozilla.components.browser.awesomebar.BrowserAwesomeBar$queryProvidersForSuggestions$1$invokeSuspend$$inlined$forEach$lambda$1.invokeSuspend(BrowserAwesomeBar.kt:145)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:193)
  at android.app.ActivityThread.main(ActivityThread.java:6718)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by ekager** [comment] 2019-06-14 18:06
Hi! We had a problem in which sessions being restored from collections with the same ID could clash with eachother. Do you have any collections? Try closing all open tabs and seeing if this is still happening

**Comment by csadilek** [comment] 2019-06-17 14:44
Yes, we fixed the root cause here: https://github.com/mozilla-mobile/fenix/issues/3313 and https://github.com/mozilla-mobile/fenix/issues/3280. The only way this should be possible is if there are two sessions with the same ID.

**Comment by ekager** [comment] 2019-06-24 19:39
I'm going to close this for now because I think the app got in a bad state that is now fixed. Open again if you're still seeing after closing duplicate sessions!

**Closed** 2020-08-27 00:08 UTC
Labels: 🐞 bug
