### ISSUE TITLE
Settings to not pop up keyboard on home

### ISSUE THREAD

**Issue by Matth7878** [mozilla-mobile/fenix#19099] opened 2021-04-18 08:07 UTC
### What is the user problem or growth opportunity you want to see solved?

When you go to home keyboard is automatically shown.
It hides for instance collections which is really really really annoying.
Home is poor in term of access to bookmars, limited in number of top sites and it push you to use collections (which are not sync...) but even when you do that it's a pain since you have to dismiss keyboard every time...

So please make it at least possible to not have keyboard pop up on home. I never need it, especially since when I try to use it it never found my bookmarks.
What it is needed from home is quick access and not use keyboard and hide screen with results from history / bookmarks.

### How do you know that this problem exists today? Why is this important?

Because each time I access home it's so annoying, and each nightly since Fenix replaced Fennec I hope there is some progress about this major part of UI...
It's important because home is a major part of UI and keyboard shouldn't half hide it. Besides what is the point of home if it is to type text in keyboard to search sites and all in all not use home?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10432)

**Comment by lobontiumira** [comment] 2021-04-19 12:03
I confirm the issue on RC 88.1.1, Beta 88.0.0-beta.6, and 4/19 Nightly build, with a Google Pixel (Android 10) device.

**Comment by Mugurell** [comment] 2021-04-21 15:38
I think the problem is that there is no "going to home".
The FAB from tabs tray is intended more to open a new tab so upon pressing it that scenario is better supported by focusing on the url bar and opening the toolbar.
This is working as expected based on https://github.com/mozilla-mobile/fenix/issues/13052

Tagging UX about whether this needs to be reconsidered.

**Comment by Matth7878** [comment] 2021-04-21 17:47
I don't agree. Even if you want too open a new tab either keyboard should not be shown (why would a search be more likely than using your collections or top sites?) or if keyboard is shown then it makes no sense to show home behind.

Besides if it is desired to show home behind when doing a search then it's not what's happening when you are already on a page and you tap url bar. (Please note that it is something I miss not having home in this case)

Anyway thanks for considering it. If you use Fenix surely this must be annoying. 😞

**Comment by Imerion** [comment] 2021-05-28 07:55
An option to disable the keyboard and search box focus on new tabs and home would be very useful. I don't know why the browser always assumes I want to search for something, but I don't. When I open a new tab I want to access my bookmarks 90% of the time. Having to always click two times to hide the keyboard and search focus (that for some reason covers the entire adress bar - buttons and all!) is very irritating. An option to disable this would be great and would surely make many users happy.

**Comment by Matth7878** [comment] 2021-06-05 07:49
I know have 3 collections and I regret creating the third... Every time I go to home I can never quickly access my collection because keyboard is always in the way...

Please consider this issue, it's a major UI problem as it involves a screen you need to interact with a lot. I know surely developers lack time but is it really time hard to allow not popping up keyboard on home? This issue still needs triage... :-(
Multiple time a day it's stressing me out and I am at the point where I try to avoid as much as possible to use home... :-/

**Comment by mirko77** [comment] 2021-11-02 18:40
This is still an issue on version 94.1.1. I cannot believe this is working as intended, as Firefox is the only mobile browser doing that as far as I know. Tested Chrome, Dolphin, Opera, Safari, Vivaldi. Even Microsoft got it right with Edge.
Therefore it is clearly an anti-pattern (or everybody else is doing it wrong, which is unlikely).

Having items on the home page is pretty useless if the keyboard hides them. See below, using Firefox on a 10 inches tablet with gestures, hiding the keyboard requires a back swipe every single time. 

![Screenshot_20211102_193727_org mozilla firefox](https://user-images.githubusercontent.com/1233305/139925146-c60ca617-b531-4b9b-8dd0-7ecd0be0f316.jpg)

**Comment by SpitFire-666** [comment] 2022-04-07 02:02
I think the title of this could/should be improved, eg "**Prevent keyboard from auto-appearing when launching new tab/new instance**"

I agree it's quite annoying and awkward and **should only pop up when tapping the address/search bar**. 

I tested Chrome and opening a new tab gives you a nice, uncrowded experience that allows you to see your bookmarks etc:

![image](https://user-images.githubusercontent.com/38451588/162105430-2bde9207-48da-47d6-bb3e-2813c6d7c4fb.png)


Someone has also raised this suggestion here:

https://connect.mozilla.org/t5/ideas/add-option-to-stop-keyboard-from-opening-automatically-on-new/idi-p/3133

**Comment by cadeyrn** [comment] 2022-04-07 05:56
@SpitFire-666: In current versions of Firefox there is a home button and it does exactly what you want: seeing the home screen content without enabling the keyboard. This issue can be closed as fixed.

**Comment by Imerion** [comment] 2022-04-07 09:53
I don't agree this can be closed. For most users it is not logical to click on Home to navigate to something new, it suggests going away from wherever you are and navigating to your home page. It should also, if the users has set a specific home page, navigate directly to that page and in that case it is not a solution at all. Most will think it logical to use the New Tab + button to open a new tab and not Home. Either way there is no reason to pop up the keyboard as most users will want to chose something from their Favorite/Recent list or their Bookmarks. Another of my friends switched to Vivaldi on his phone a few weeks back despite wanting to support Firefox and this was one of the reasons he cited. There really needs to be an option for this.

**Comment by SpitFire-666** [comment] 2022-04-11 00:52
> @SpitFire-666: In current versions of Firefox there is a home button and it does exactly what you want: seeing the home screen content without enabling the keyboard. This issue can be closed as fixed.

Thanks - the Home button definitely does what you say, however I (and **I suspect most people) never use it** and **instead use New Tab.** 

As stated previously, Chrome, Brave and Opera all open a new tab without the keyboard popping up automatically (it only pops up when you tap the search/address bar. 

Note that on desktop, it's normal to give keyboard focus to the address bar when opening a new tab, which is fine because this doesn't cover half your screen with a virtual keyboard.

**Comment by jonalmeida** [comment] 2023-01-30 20:23
Closing as invalid because the default behaviour is to not open the keyboard when at home.

**Closed by jonalmeida** 2023-01-30 20:23 UTC
Labels: feature request 🌟, needs:UX-feedback, Feature:HomeScreen, needs:triage, Feature:IME, qa-triaged

**Comment by Matth7878** [comment] 2023-01-30 20:31
Not invalid since you are also presented with home when wanting a new tab. Right now keyboard is in the way to access your collections for instance.
