### ISSUE TITLE
IllegalStateException - Fragment already added: SimpleRedirectDialogFragment{... SHOULD_OPEN_APP_LINK_PROMPT_DIALOG}

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#3210] opened 2019-06-06 13:17 UTC
https://sentry.prod.mozaws.net/operations/fenix/issues/5874306

```
java.lang.IllegalStateException: Fragment already added: SimpleRedirectDialogFragment{2cfa0b (d58ffd6c-3949-4765-afb4-1439e3e78145) SHOULD_OPEN_APP_LINK_PROMPT_DIALOG}
    at androidx.fragment.app.FragmentManagerImpl.addFragment(FragmentManagerImpl.java:16)
    at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:21)
    at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:51)
    at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:10)
    at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:4)
    at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:1)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6718)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by colintheshots** [comment] 2019-06-07 20:41
Duplicate of #3255, which has STR.

**Comment by softvision-miralobontiu** [comment] 2019-06-11 07:00
I'll remove the QA needed, hence this issue is closed as a dupe.

**Comment by softvision-miralobontiu** [comment] 2019-06-11 07:00
I'll remove the QA needed, hence this issue is closed as a dupe.

**Closed** 2020-08-26 21:49 UTC
Labels: Release Blocker, b:crash, needs:ac, 🐞 bug
