### ISSUE TITLE
[Bug] Performance: EngineObserver.onLocationChange sometimes blocks the UI thread for 100ms

### ISSUE THREAD

**Issue by mstange** [mozilla-mobile/fenix#8250] opened 2020-02-08 16:03 UTC
## Steps to reproduce

Navigate to a few pages (doesn't matter how, I think) so that EngineObserver.onLocationChange is called.

### Expected behavior

The UI thread should never be blocked for more than a few milliseconds at a time.

### Actual behavior

Some calls to EngineObserver.onLocationChange can take 100ms on a Moto G5. Any hitch in the UI thread directly affects GeckoView rendering: scrolling becomes briefly unresponsive or jumps, videos hitch, animations jump, paints are delayed.

Here's an example profile: https://perfht.ml/31GT8Np
(Unfortunately there aren't many Java samples in that window, so all I can see is that when I drag a selection over the time during which mozilla.components.concept.engine.EngineSession.notifyObservers is on the stack, the window is around 100ms wide.)

### Device information

* Android device: Moto G5
* Fenix version: This was a local Fenix debug build from yesterday's master. It's possible that this is less of a problem in release builds.

**Comment by emalysz** [comment] 2020-02-26 19:16
We moved this to low impact because the performance team did not think it was very actionable. The browser menu component is complex and is currently being rewritten.  

We did, however, notice that `onLocationChange` calls `Session.setWebAppManifest`, so I filed a PR that will move the manifest update feature off the main thread. This should not expect huge wins. Here is the PR: https://github.com/mozilla-mobile/android-components/pull/5928#issuecomment-586024311

**Comment by csadilek** [comment] 2020-04-20 22:25
I can't seem to reproduce this anymore on latest release builds. Most recently we landed a reader mode refactoring that, among other changes, prevents various checks from running and blocking `onUrlChanged` which is called by `EngineObserver.onLocationChange`. This could have contributed to the problem before.

I've created a custom build now logging the elapsed time in `onLocationChange`. I am seeing an average of 5.2ms with a median of 4ms (worst outlier was 13ms). Using the Gecko/Firefox profile I get similar results (between 3 - 5ms). However, I only have fast devices available right now.

@mstange would you mind taking another look when you get a chance and check if you can still reproduce on the latest Nightly release build? Thank you!

Went over all implementations of `onLocationChange` and `onUrlChanged`. There are a few String and URL comparisons which explain the remaining running time. Fenix also launches a bookmarks storage query which runs on an IO thread.

**Comment by mstange** [comment] 2020-04-22 19:41
I can no longer reproduce this - looks fixed to me!

I still see the UI thread blocking on handlers, but each invocation doesn't take a long time. I see one or sometimes two consecutive samples in these functions, but not more.

Production build: https://perfht.ml/2VU7eZg
Debug build: https://perfht.ml/2KnusSr

I've filtered these profiles to show samples matching `.wait(`, i.e. stacks that block inside `java.lang.Object.wait()`. If you switch to the flame graph or the call tree, you can still see a fair number of samples in that function. But if you look at the stack chart, you can see that most invocations to this function are short.
You can also switch to the call tree and select the root call node, and then look at the categories in the sidebar. The "Blocked" category  shows how much time the UI thread spends synchronously waiting on other threads.

**Comment by csadilek** [comment] 2020-04-22 20:12
Thanks again, Markus!

Once our refactoring browser-state is complete [1], all these handlers will simply dispatch actions to the store which will be processed in a non-blocking way. This is also why reader mode now no longer directly consumes time on `onLoadRequest` because it was recently migrated. This will take some more time though until everything is fully migrated.

[1] https://github.com/orgs/mozilla-mobile/projects/31

**Closed by csadilek** 2020-04-22 20:12 UTC
Labels: eng:performance, needs:triage, 🐞 bug
