### ISSUE TITLE
FNX-4996 ⁃ [Bug] Crash when typing some two char combos into address bar with search suggestions disabled

### ISSUE THREAD

**Issue by agashlin** [mozilla-mobile/fenix#1388] opened 2019-04-04 19:19 UTC
## Steps to reproduce
1. Set up sync to populate history
1. Disable search suggestions
1. Type two characters into the address bar, in my case "ga" and "sl" both cause this

### Expected behavior
Nothing special happens

### Actual behavior
After the second character of the combination is typed and the search results update, Fenix crashes

### Device information
* Android device: Pixel (sailfish)
* Fenix version: 1.0.1914 (Build # 10931209 gecko 67.0-20190318154932)

Likely the specifics of my history are involved as both of those partial words match the beginning of some of my frequent sites. I'm not sure if I should clear data to check as I might not be able to reproduce it later. It doesn't happen if I enable search suggestions and restart, but immediately after I disable suggestions it happens again.

Crash reports seemingly aren't being sent (about:crashes shows nothing, at least). This seems to be the relevant log:

```
04-04 11:58:06.541 18399 18937 D places_ffi: places_match_url
04-04 11:58:06.560 18399 18926 D places_ffi: places_query_autocomplete
04-04 11:58:06.591 18399 18399 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
04-04 11:58:06.616 18399 18399 I chatty  : uid=10103(org.mozilla.fenix) identical 2 lines
04-04 11:58:06.619 18399 18399 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
04-04 11:58:06.629 18399 18399 D AndroidRuntime: Shutting down VM
04-04 11:58:06.630 18399 18399 E AndroidRuntime: FATAL EXCEPTION: main
04-04 11:58:06.630 18399 18399 E AndroidRuntime: Process: org.mozilla.fenix, PID: 18399
04-04 11:58:06.630 18399 18399 E AndroidRuntime: java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
04-04 11:58:06.630 18399 18399 E AndroidRuntime:  ViewHolder 1:ViewHolder{51cf46 position=1 id=2669123195, oldPos=-1, pLpos:-1 not recyclable(1)}
04-04 11:58:06.630 18399 18399 E AndroidRuntime:  View Holder 2:ViewHolder{84bab5a position=0 id=2669123195, oldPos=-1, pLpos:-1} mozilla.components.browser.awesomebar.BrowserAwesomeBar{ba3f678 VFED..... ......ID 0,190-1080,863 #7f08006a app:id/awesomeBar}, adapter:mozilla.components.browser.awesomebar.SuggestionsAdapter@5c2e4b8, layout:androidx.recyclerview.widget.LinearLayoutManager@3fba291, context:org.mozilla.fenix.HomeActivity@5060fdb
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:45)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.View.layout(View.java:20672)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:696)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-04 11:58:06.630 18399 18399 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-04 11:58:06.630 18399 18399 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
04-04 11:58:06.630 18399 18399 I mozac/CrashReporter:  ViewHolder 1:ViewHolder{51cf46 position=1 id=2669123195, oldPos=-1, pLpos:-1 not recyclable(1)}
04-04 11:58:06.630 18399 18399 I mozac/CrashReporter:  View Holder 2:ViewHolder{84bab5a position=0 id=2669123195, oldPos=-1, pLpos:-1} mozilla.components.browser.awesomebar.BrowserAwesomeBar{ba3f678 VFED..... ......ID 0,190-1080,863 #7f08006a app:id/awesomeBar}, adapter:mozilla.components.browser.awesomebar.SuggestionsAdapter@5c2e4b8, layout:androidx.recyclerview.widget.LinearLayoutManager@3fba291, context:org.mozilla.fenix.HomeActivity@5060fdb)
```

**Comment by jonalmeida** [comment] 2019-04-05 01:03
Duplicate of https://github.com/mozilla-mobile/android-components/issues/2364

**Comment by vesta0** [comment] 2019-04-16 20:14
Fixed.

**Closed** 2020-08-11 11:33 UTC
Labels: needs:ac, 🐞 bug
