### ISSUE TITLE
[Bug] Download doesn't update media scanner

### ISSUE THREAD

**Issue by Djfe** [mozilla-mobile/fenix#15038] opened 2020-09-13 02:53 UTC
## Steps to reproduce
Download image
### Expected behavior
Open gallery app (for example Google photos) and open download folder/album to view the downloaded image.

or:
Open mail app, add attachment with android's build-in document manager.
### Actual behavior
The image often takes a long time to appear or doesn't unless you manually trigger a rescan (for example by toggling airplane mode on/off)

In the document manager: compare image section (downloads folder) vs downloads section, the downloads section contains the image instantly while images uses the media library (likewise music and videos) 
### Device information

* Android device: oneplus-3t. Android 9
ok it's a custom rom, but my guess is you will be able to easily replicate this since it works fine for me in Chrome.
* Fenix version: playstore: Release and Nightly.

**Comment by hwinnemoe** [comment] 2020-09-13 08:02
Duplicate of #8754

**Comment by ekager** [comment] 2020-12-18 05:56
Closing for #8754

**Closed by ekager** 2020-12-18 05:56 UTC
Labels: needs:triage, 🐞 bug
