### ISSUE TITLE
[Bug] Upload files not work 

### ISSUE THREAD

**Issue by marker10** [mozilla-mobile/fenix#6775] opened 2019-11-24 09:00 UTC
In any site when I want to upload a file the browser crashes, closes and then needs to be restarted.

### Device information

* Android device:: Asus_Z00ED 
* Fenix version: 2.3.0 (Build #13031728)
📦: 18.0.0, ef631b6df
GV: 70.0-20191014032640
Android 6

**Comment by cadeyrn** [comment] 2019-11-24 09:17
Duplicate of #6279 and fixed in Nightly.

**Closed** 2019-11-25 01:24 UTC
Labels: 🐞 bug
