### ISSUE TITLE
[Bug]: recent apps of share menu aren't visible immediately after tapping share button

### ISSUE THREAD

**Issue by iriman** [mozilla-mobile/fenix#25159] opened 2022-05-08 10:26 UTC
### Steps to reproduce

1. Set Android locale to Persian (right-to-left script)
2. Open a webpage in Firefox
3. Tap "3 vertical dots" to open menu.
4. Tap share button
5. Share menu will open

### Expected behaviour

I expect to see recent apps submenu immediately.

### Actual behaviour

I should scroll right to reach ~beginning of menu and then~ recent apps submenu.

### Device name

J510F

### Android version

7.1

### Firefox release type

Firefox

### Firefox version

99.2.0 (Build #2015874209)

**Comment by amedyne** [comment] 2022-05-09 18:44
@iriman Can you attach a screen recording of what is happening? thanks!

**Comment by iriman** [comment] 2022-05-10 16:39
Sorry @amedyne, I'm not happy with sharing that. 
Actually when I open that menu, the scrollable part of it always starts from left, whether device locale is LTR or RTL.
There should be some more apps on device to fill the visible space and extend the menu.

**Comment by kbrosnan** [comment] 2022-05-12 17:44
Sounds like a duplicate of https://github.com/mozilla-mobile/fenix/issues/9411 then.

**Closed by kbrosnan** 2022-05-12 17:44 UTC
Labels: 🐞 bug

**Comment by iriman** [comment] 2022-05-12 18:52
Actually this is a bug regarding design of RTL layout:

Scroll area is designed LTR (i.e. always starts from left) but order of its content (recent apps + other apps) is based on locale. Both should be of same direction.

However, if design is revised as suggested in #9411, this will not be an issue anymore.

**Comment by iriman** [comment] 2022-08-10 18:41
Hi @amedyne, this is a screen recording of the issue with FF 103.2.0

https://user-images.githubusercontent.com/8467903/183991269-b07444d6-7a46-4344-a9b6-a97052114204.mp4
