### ISSUE TITLE
Option to sort tab list top down 

### ISSUE THREAD

**Issue by FernandoMiguel** [mozilla-mobile/fenix#16869] opened 2020-12-05 10:40 UTC
A recent nightly changed the order of the tab list from older to new top down. 
Previously it was newer to older. 
I prefer the most recent on the top. 
I also have set the url bar to be on the top instead of the bottom. 
Can either an option be added to allow the list order to be chosen or at the very least have it follow the option of the toolbar location?

**Comment by kbrosnan** [comment] 2020-12-07 18:47
Duplicate of #16884

**Closed by kbrosnan** 2020-12-07 18:47 UTC
Labels: needs:triage

**Comment by mirko77** [comment] 2020-12-24 13:03
See #17205, I agree most recent at the top is the right way
