### ISSUE TITLE
[Bug]: pages reload when browser returns to focus. all content lost

### ISSUE THREAD

**Issue by github-man** [mozilla-mobile/fenix#20409] opened 2021-07-18 12:29 UTC
### Steps to reproduce

Go to a website and fill in a form.

Switch out of firefox (eg to a password manager to get a password) or leave phone unattended for a minute for the screen to lock.

Return  to firefox, the page reloads and all the content typed previously is lost.

### Expected behaviour

Page does not reload when focus switch back to firefox.

### Actual behaviour

Page reloads and all content lost.

### Device name

samsung galaxy s10

### Android version

android 10 I think (sorry I cant switch to setting to check otherwise everything I've typed here will be lost)

### Firefox release type

Firefox

### Firefox version

I assume it's the latest. am afraid to check in case I lose what I've typed.

**Comment by yump** [comment] 2021-07-19 00:48
Perhaps try disabling all Android native and Samsung-specific "battery optimization" for Fenix, as documented [here](https://dontkillmyapp.com/google) and [here](https://dontkillmyapp.com/samsung#galaxy-s10)?

**Comment by kbrosnan** [comment] 2021-07-22 17:17
Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/12731

**Closed by kbrosnan** 2021-07-22 17:17 UTC
Labels: needs:triage, 🐞 bug
