### ISSUE TITLE
[Bug] Gmail with the address bar at the bottom

### ISSUE THREAD

**Issue by paramovi** [mozilla-mobile/fenix#16698] opened 2020-11-21 07:59 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open an email in the mobile site of Gmail when using the address bar at the bottom in Firefox for Android.

### Expected behavior
Scroll down for seeing all the page.

### Actual behavior
Address bar hides the bottom of the page.

[comment]: # (### Device information)

[comment]: # (* Android device: ?)
[comment]: # (* Fenix version: ?)

**Comment by Poopooracoocoo** [comment] 2020-11-21 09:15
#13797

**Comment by sflorean** [comment] 2021-07-31 09:57
Closing as duplicate of #13797.

**Closed by sflorean** 2021-07-31 09:57 UTC
Labels: Feature:Toolbar, wontfix, 🐞 bug
