### ISSUE TITLE
[Bug] youtube notification not getting the site icon and color

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#18841] opened 2021-04-07 13:56 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Play any video in youtube
View the notification
It is grey and youtube icon or video thumbnail is missing
I remember it used to show youtube icon and change the notification color in earlier fenix version but it is no longer working for youtube. Works fine for other websites
Attaching screenshots

### Expected behavior
Should display youtube icon and change the notification color

### Actual behavior
Showing no icon and grey color

### Device information

* Device vendor / model and Android version: ? A11
* Firefox for Android version: ? (go to Settings -> About Firefox) latest nightly
*
![Screenshot_20210407-192032570](https://user-images.githubusercontent.com/58127841/113878275-1621aa80-97d7-11eb-95f9-4053dc809daf.jpg)
![Screenshot_20210407-191956868](https://user-images.githubusercontent.com/58127841/113878291-19b53180-97d7-11eb-88f9-a459140f2c1e.jpg)

**Comment by abodea** [comment] 2021-04-07 15:03
Thank you for this report!
I was able to reproduce this issue but I will close it as a duplicate of https://github.com/mozilla-mobile/fenix/issues/16958.

**Closed by abodea** 2021-04-07 15:03 UTC
Labels: needs:triage, 🐞 bug

**Comment by sheikh-azharuddin** [comment] 2021-04-07 15:14
But the previous case is related to media icon especially speaker icon missing and the case was raised as generic request for all media notification...here my case is different
It's regarding issue on youtube site..

**Comment by abodea** [comment] 2021-04-07 15:56
> But the previous case is related to media icon especially speaker icon missing and the case was raised as generic request for all media notification...here my case is different
> It's regarding issue on youtube site..

It also refer to the YT videos if you check the following https://github.com/mozilla-mobile/fenix/issues/16958#issuecomment-775943108.

**Comment by sheikh-azharuddin** [comment] 2021-04-07 16:17
Nah....it still speaks about media icon..
