### ISSUE TITLE
[Bug] Dom.ipc.processCount does not work anymore? 

### ISSUE THREAD

**Issue by michas0602** [mozilla-mobile/fenix#19539] opened 2021-05-17 20:07 UTC
As written, the setting "Dom.ipc.processCount" resets to 1 itself all the time / every restart since update to Ff 89 beta.

This is a duplicate of #19385 as I do not see why its closed and @kbrosnan answer dont really satisfy me - I am a user and I dont care for geckoview/geckodriver etc. - it currently is changeable in Firefox 88 - but not in 89 anymore. So its a bug to me - otherwise give me/us a better explanation why it does not work anymore please.

## Steps to reproduce
Set Dom.IPC.processcount t to 4 in about:config or user.js and restart Firefox

### Expected behavior
Should be 4 after I set it and restart

### Actual behavior
Value resets itself to 1 every restart

### Device information
* Device vendor / model and Android version: LG v20 with LOS 18.1
* Firefox for Android version: Firefox 89 beta

**Comment by kbrosnan** [comment] 2021-05-17 23:03
Closing duplicate. It does not work because the pref is controlled by Geckoview as I stated in the other issue. This is something that the Geckoview team will chose the best option for performance when e10s ships.

**Closed by kbrosnan** 2021-05-17 23:03 UTC
Labels: needs:triage, 🐞 bug

**Comment by michas0602** [comment] 2021-05-18 13:48
@kbrosnan Very unsatisfying explanation - you still dont answer why it is user-changeable in Ff 88, but not in Ff 89 anymore.

So e10s has been deactivated in Ff 89 by the Geckoview-team. Without any information to the users and as best option for performance. And the option to set webcontent processes is still visible+changeable in about:config until the next restart. Do I understand this in the right manner?

**Comment by michas0602** [comment] 2021-05-18 13:54
Btw, who is the person downvoting my questions all the time?! A dev here?

**Comment by kbrosnan** [comment] 2021-05-18 17:16
The behavior you are describing is expected behavior for prefs that are controlled by Geckoview.  The Fenix team largely works on the UI and the Android integration parts. For anything Gecko that is controlled by the [Geckoview team](https://geckoview.dev). You might be better off talking to them. They are working on finalizing e10s on Android.
