### ISSUE TITLE
[Bug] Private mode doesn't play nicely with sites added to home screen

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7996] opened 2020-01-30 10:52 UTC
## Steps to reproduce
1. Add a site to home screen in private mode
2. Open the site from your android home

### Expected behavior
1. Site opens in whatever mode you are currently in

### Actual behavior
1. Site opens in normal mode

### Device information

* Android device: Galaxy S9
* Fenix version: Android Nightly 1/30/20

**Comment by mcarare** [comment] 2020-01-30 13:13
@sblatz Is this supposed to work in private?

**Comment by sblatz** [comment] 2020-01-30 13:47
I'm not 100% sure. It feels weird to me that it switches to private mode, but let me ask @NotWoods 😄

**Comment by NotWoods** [comment] 2020-01-30 19:21
I don't think we've defined this anywhere. I'm currently working on tweaking the PWA site controls notification to indicate if a PWA is in private mode. Personally, I think that the PWA should match whichever mode you were in when you installed it, and update the menu design to make that more clear.

**Comment by NotWoods** [comment] 2020-02-11 22:41
Let's track updating the site controls notification here for now. Later we should ask the UX team for a menu prompt design (maybe integrate a private mode checkbox into https://github.com/mozilla-mobile/android-components/issues/5883).

Notification alterations:
- Instead of the Firefox logo, show the private mode mask
- Instead of "PWA Name", show "PWA Name (Private Mode)". (ie: `Twitter (Private Mode)`).
- Instead of the PWA color, use the private mode color.

**Comment by TitanNano** [comment] 2020-02-12 21:56
@NotWoods you can assign this to me 😄

**Comment by klint** [comment] 2020-03-05 10:22
Just to be clear, as the discussion focused on PWA only eventuelly, the request here is about both PWA *and* page shortcuts added to the phone's home screen. Not only about PWA (which are less often available than plain web pages, that can be turned into shortcuts, actually).
Thank you

**Comment by TitanNano** [comment] 2020-05-06 15:55
@sblatz my patch landed, what's the next step here?

**Comment by sblatz** [comment] 2020-05-07 19:20
@TitanNano Let's have QA verify and close this out. Thanks 😄

**Comment by softvision-miralobontiu** [comment] 2020-05-08 08:31
Hi all,

This issue is not fixed yet. The page added to the homescreen from private mode, opens in normal mode. Tested on the latest Nightly build from 5/8 @6:06 AM with OnePlus 5T (Android 9), One Plus A3 (Android 6.0.1), Samsung Galaxy Tab A6 (Android 5.1.1), and HTC 10 (Android 8).

<img src="https://user-images.githubusercontent.com/40694158/81387384-3d7f7b80-911f-11ea-8007-30d7aca08170.gif" width="300" height="550" />

**Comment by TitanNano** [comment] 2020-05-08 12:05
@softvision-miralobontiu @sblatz see https://github.com/mozilla-mobile/fenix/issues/7996#issuecomment-584892912 my patch only changed the site control notification, getting the PWA to actually launch in private mode seems to be part of https://github.com/mozilla-mobile/android-components/issues/5883. So this is not really testable yet as PWAs are still always in standard mode.

**Comment by AndiAJ** [comment] 2021-02-17 09:41
**Still reproducible** on **`86.1.0 RC1`** using a OnePlus A3 (Android 6.0.1)

**Comment by sv-ohorvath** [comment] 2021-07-06 09:40
This also happens if you toggle "Open links in private tab" ON and open a page shortcut.

**Comment by sv-ohorvath** [comment] 2021-07-06 13:04
There is also this: https://github.com/mozilla-mobile/fenix/issues/20263

**Comment by lobontiumira** [comment] 2021-07-07 11:59
Reproducible with OnePlus 5T (Android 10) on RC 90.1.0.

**Closed** 2022-04-11 22:29 UTC
Labels: 🐞 bug, Feature:PrivateBrowsing, Feature:Shortcuts, Feature:PWA, S2, wontfix
