### ISSUE TITLE
Recover search at URL bar 

### ISSUE THREAD

**Issue by 0x391F** [mozilla-mobile/fenix#17999] opened 2021-02-15 07:53 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
![Screenshot_20210215_154337](https://user-images.githubusercontent.com/56181919/107918576-eb6c6000-6fa4-11eb-9f2f-499683948c4c.jpg)
Fennec 68 and Chrome could search at URL bar i.e. input something and search. 
### How do you know that this problem exists today? Why is this important?
When I searching TLS1.3, Fenix didn't go to search engine, it attempt go to http://www.tls1.3/
### Who will benefit from it?
Everyone

**Comment by mcarare** [comment] 2021-02-15 08:20
@0x391F  What version are you using? I can search the text "tls1.3" through the search engine.

**Comment by 0x391F** [comment] 2021-02-15 08:43
> @0x391F What version are you using? I can search the text "tls1.3" through the search engine.

85.1.3

**Comment by 0x391F** [comment] 2021-02-15 08:46
> @0x391F What version are you using? I can search the text "tls1.3" through the search engine.
 I think you add a space between s and 1?

**Comment by mcarare** [comment] 2021-02-15 08:50
@0x391F No. I did not.

**Comment by 0x391F** [comment] 2021-02-15 09:01
Hmm... That's strange. But could Fenix recover the search button as Fennec and Chrome? 
![Screenshot_20210215_165849](https://user-images.githubusercontent.com/56181919/107925447-6dfa1d00-6faf-11eb-8553-cd4ba6da800b.jpg)

**Comment by mcarare** [comment] 2021-02-15 09:22
@0x391F That search already shows up, it's part of the suggestions list.
<img src = https://user-images.githubusercontent.com/48995920/107927195-573bd200-6f7f-11eb-9a7d-bf735a65d157.png width = 45%>

**Comment by 0x391F** [comment] 2021-02-15 09:58
> 
> 
> @0x391F That search already shows up, it's part of the suggestions list.
> <img alt="" width="45%" src="https://user-images.githubusercontent.com/48995920/107927195-573bd200-6f7f-11eb-9a7d-bf735a65d157.png">

Yes, I know. it needs to enable "Show search suggestions" and "Show in private sessions", below is Fennec 68.12.0 behavior, it dosen't sent the search request to search engine before user search manually: 
![IMG](https://user-images.githubusercontent.com/56181919/107931290-f4910900-6f73-11eb-99a4-63bcf533a0c9.png)

**Comment by kbrosnan** [comment] 2021-02-16 08:39
Duplicate of  #12663

**Closed by kbrosnan** 2021-02-16 08:39 UTC
Labels: Feature:Search
