### ISSUE TITLE
FNX-462 ⁃ Quick access to existing bookmarks

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#1487] opened 2019-04-09 11:17 UTC
### Why/User Benefit/User Problem
Unless I'm missing something, it currently takes 5 taps to load a bookmark (Menu, Library, Bookmarks, mobile, bookmark). This seems like 4 taps too many.

### What / Requirements
Reduce number of taps to load a bookmark

### Acceptance Criteria (how do I know when I’m done?)
Implement the UX mocks below:

**UX update**

ok, here's a small improvement to reduce number of taps from home screen:

![Home w menu](https://user-images.githubusercontent.com/353960/64729846-4eb7b000-d4de-11e9-90ce-cd6ecb22cb12.png)

**Comment by vesta0** [comment] 2019-04-09 17:26
@lime124 would love your thoughts on this.

**Comment by buttercookie42** [comment] 2019-04-10 12:43
Fennec needs three taps (or even just two if Bookmarks are your default home panel): Tap into URL bar to view home panels (or double tap on the tab counter to open a new tab), choose the bookmarks panel (if not already default), choose bookmark.

**Comment by staktrace** [comment] 2019-04-10 13:38
For the more narrow use case of "start browser to load frequently-visited bookmark", Fennec requires just a single tap since the bookmark shows up in the top sites list as soon as you open the browser. (I have it pinned there, but even without that it would probably show up there). I guess the equivalent in Fenix is to go digging through the history that shows up on the home screen. At best that's two taps, but assuming you pick the right history panel.

**Comment by buttercookie42** [comment] 2019-05-14 21:00
Could potentially apply to the whole library in general, i.e. history, and in the future if they end up in the library, too, possibly synced tabs, recently closed tabs, ... - the new design forces you to always go via the main menu, which is an additional click compared to Fennec's home panels.

**Comment by franco27** [comment] 2019-06-18 21:10
the possibility to pin websites on the "new tab" page which I think would be a good idea

**Comment by jacktose** [comment] 2019-07-10 19:49
mozilla/firefox-preview-bughunting-campaign#313 was closed as a duplicate of this, but contained this UX suggestion:

Open new tab (from menu, or + on home screen)
In [currently blank space](https://user-images.githubusercontent.com/12414794/59368506-3a9fbf00-8cf3-11e9-859d-ab46d23a5815.png), there would be a UI for selecting a bookmark (or other library item). The selected item would open in the new tab (without going through Menu > Open in new tab).

**Comment by lime124** [comment] 2019-07-23 21:23
removing the ux label - we are currently collecting all these as part of a larger bookmark effort.

**Comment by rubcap** [comment] 2019-07-24 11:57
> Could potentially apply to the whole library in general, i.e. history, and in the future if they end up in the library, too, possibly synced tabs, recently closed tabs, ... - the new design forces you to always go via the main menu, which is an additional click compared to Fennec's home panels.
The current Firefox for Android 'new tab page' works wonderful in this respect, with Top Sites/Speed Dial, Highlights, Bookmarks, History ... all easily accessible. I'd suggest to port these home panels from Fennec to Fenix.

**Comment by eggsgent** [comment] 2019-08-27 11:01
This issue together with the unexpected, and for me as a user unwanted behaviour of the Android Back button once a bookmark is opened ( https://github.com/mozilla-mobile/fenix/issues/4517 ) makes bookmarks extremely difficult to use in Fenix (1.3.1 build 12341950).

To add to the first post here, current path to open Desktop bookmarks which are located on the Bookmarks Toolbar is minimum 6 steps:

Menu > Library > Bookmarks >Desktop bookmarks > Bookmarks Toolbar > *Folder*> *Folder* > "Bookmark i want to open"

It would help if there was an option to set default root in bookmark navigation, remember last position, or other more clever ways to reduce the steps to get to bookmarks.

**Comment by rubcap** [comment] 2019-09-08 17:58
@lime124  Can we expect the return of the Fennec home panels or something similar to have quick access to bookmarks, history and top sites? Any news on the bookmarks UX redesign effort? Thank you!

**Comment by ekager** [comment] 2019-09-27 00:10
This will require AC work for adding a new menu item header type like "Your Library" in the new mock.

**Comment by mcarare** [comment] 2019-09-27 09:09
Do we have any specs for the "Your Library" text?
I think there already is a `SimpleBrowserMenuItem` in AC we could use, or modify, depending on the specs.

Also, the History item should have the same icon as in the Library page?!

**Comment by topotropic** [comment] 2019-09-27 10:42
"Your Library" has the same spec as the sub headings we use in Settings (Account, Basic....). 
And yes, this is the wrong icon 😬 it should be the same we currently use. Thanks for noticing!

**Comment by mcarare** [comment] 2019-09-27 13:19
opened AC issue: https://github.com/mozilla-mobile/android-components/issues/4560

**Comment by mcarare** [comment] 2019-10-03 15:41
@topotropic I've Implemented this locally but using subheadings attributes makes for a very different look for the "Your library" text. That is due to the fact that the menu has a different background colour than the preference screen. Can you please provide specific attributes for the category item "Your library"? :) TY

**Comment by apbitner** [comment] 2019-10-03 16:51
@mcarare The background should be white - rgb(255, 255, 255). Here are some other specs which might help - https://cl.ly/784b25e4009c. Let me know if you need anything else.

**Comment by mcarare** [comment] 2019-10-04 07:24
Thank you, @apbitner. Actually there are some info missing:
 - text color attribute for all themes (is it `accent`?)
 - text font: we don't have that font in Fenix app. In the sample looks like `sans-serif-medium`.
 - layout height is smaller than that of a regular Menu Item (48dp)?

**Comment by apbitner** [comment] 2019-10-07 15:02
-     text color attribute for all themes (is it accent?)
  - Correct
-     text font: we don't have that font in Fenix app. In the sample looks like sans-serif-medium.
  - The design team uses FirefoxSharpSans Bold for that header. If you're unable to use it, I can follow up with an engineer to see what they've been using in its place.
-     layout height is smaller than that of a regular Menu Item (48dp)?
  - Height, including padding, is 40dp

**Comment by madb1lly** [comment] 2019-10-28 15:42
+1 here for using Fennec's newtab page/UX for quick access to top/pinned sites, synced tabs (per device), history (with recently closed tabs as well) and bookmarks.... heck even pocket recommendations are sometimes interesting! The proposed reading list #913 https://github.com/mozilla-mobile/fenix/issues/913 could even be included here.

There is not much wrong with the Fennec UI, I think that instead of trying to reinvent the wheel the Fennec UI should be the starting point for Fenix... but maybe it's too late for that now.

**Comment by rubcap** [comment] 2019-10-29 17:15
My apologies for repeating the same point, but, is a _major_ redesign of the new tab page considered by the UX team (now or in a future sprint)?

Currently, accessing bookmarks and history from a new tab requires typing in the search box. I hope something like a speed dial could be added. "Tap and surf", if you'd like :wink:

Would really appreciate some feedback on this!

**Comment by AndiAJ** [comment] 2019-11-04 10:06
Hi, **verified as fixed** on the latest **Nightly Build #13080607 from 4/11** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191104_114502](https://user-images.githubusercontent.com/51314259/68112990-5bafb900-fefb-11e9-86e0-257e3e251f26.gif)


As per the discussion I had with @mcarare the remaining issues (most of them regarding the navigation flow) will be tracked in #6418

**Comment by jacktose** [comment] 2019-11-04 18:02
This was mozilla/firefox-preview-bughunting-campaign#313, which was closed as a duplicate of this issue, but this solution does not resolve that request. Reopened that as #6437.

**Closed** 2020-08-11 11:46 UTC
Labels: E5, Feature:Bookmarks, eng:qa:verified, eng:ready, needs:ac, should

**Comment by gorman42** [comment] 2020-08-24 11:10
> 
> 
> > Could potentially apply to the whole library in general, i.e. history, and in the future if they end up in the library, too, possibly synced tabs, recently closed tabs, ... - the new design forces you to always go via the main menu, which is an additional click compared to Fennec's home panels.
> 
> The current Firefox for Android 'new tab page' works wonderful in this respect, with Top Sites/Speed Dial, Highlights, Bookmarks, History ... all easily accessible. I'd suggest to port these home panels from Fennec to Fenix.

I'm frankly astonished that something so absolutely *basic* in the user experience department has been completely ignored. Firefox had a good approach with this, with the home panels in Fennec. I would never expect to downgrade my experience when updating my app on Android. But that's exactly what happened. 

And you were discussing this last year... :-(
