### ISSUE TITLE
[Bug] Fenix Nightly with WebRender cannot switch tabs

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#5984] opened 2019-10-12 15:40 UTC
## Steps to reproduce
open more than one tab
go to about:config and switch webrender on
close the app and start again
click the tab number to see all tabs
### Expected behavior
I can switch tabs
### Actual behavior
I cannot switch tabs
https://vimeo.com/365969419
### Device information

* Android device: OnePlus 5t
* Fenix version: latest nightly

This first broke 2 days ago. It works fine on a fresh profile with shelter and no webrender

**Comment by yoasif** [comment] 2019-10-12 16:51
Also seeing this on a Pixel 2, where WR is enabled by default. Menu items like Settings or Your Library don't work either.

I can open a new bug as required.

**Comment by bogas04-swiggy** [comment] 2019-10-12 19:48
Duplicate of #5951?

**Comment by ekager** [comment] 2019-10-14 19:01
Closing for #5951

**Closed by ekager** 2019-10-14 19:01 UTC
Labels: 🐞 bug
