### ISSUE TITLE
FNX-3370 ⁃ [Bug] Bookmarklets are being redirected to searches

### ISSUE THREAD

**Issue by izomiac** [mozilla-mobile/fenix#10224] opened 2020-04-26 05:33 UTC
## Steps to reproduce
Tap the address bar, type the first few characters corresponding to a bookmarklet, tap the bookmarklet.

### Expected behavior
The bookmarklet should be executed on the current page.

### Actual behavior
Google is searched for the contents of the bookmarklet.

### Device information
Firefox for Android is 75.0.0-beta.6 Build #2015735819
Pixel 2 phone and Kindle Fire HD tablet
This bug appeared in the April 21st update.

I got an unusual response when I initially submitted this to Bugzilla, so I'm linking the [Wikipedia page on Bookmarklets](https://en.wikipedia.org/wiki/Bookmarklet) since they're less commonly used.

**Comment by cadeyrn** [comment] 2020-04-26 08:18
Duplicate of #2871.

**Closed** 2020-08-10 19:38 UTC
Labels: needs:triage, 🐞 bug
