### ISSUE TITLE
UI Options Request for Preview

### ISSUE THREAD

**Issue by miaokun-normal** [mozilla-mobile/fenix#12180] opened 2020-07-02 04:01 UTC
I use the latest version of Firefox Preview and I was shocked when my beloved tabs layout has gone and the address bar now automatically hide when I scroll the content. :'(

I know some may love the new changes, but others may not. So, it would be good if Firefox include 2 UI options for the tabs layout, with the tabs showing as lines in the new tab (with no tab preview image) as the previous version of the Preview and options to not let the address bar automatically hide when scrolling through contents.

**Comment by paritosh9199** [comment] 2020-07-02 08:08
I would love to have an option in the settings that gives users option for not hiding the url bar while scrolling. Also the site preview seems to be broken. It works for some site and dosen't work for other sites. It would be better if they replaced the preview with the favicon that they used to do previous tab layout.

**Comment by cadeyrn** [comment] 2020-07-02 08:16
Duplicate of #10240 (option for address bar hiding).
For the tab layout there is also at least one other issue but I don't have a issue number.

In the future you should create one issue per feature request. Let's say Mozilla wants to implement one request but not the other one - how should they label the issue? 😉

**Comment by Dunexus** [comment] 2020-07-02 08:17
Issue about an option to disable dynamic toolbar : https://github.com/mozilla-mobile/fenix/issues/10240

For tabs UI, it would be too much work to maintain 2 UI, please feel free to provide some feedback about how to improve the new tab tray if it doesn't suit your expectations. Some improvements are already worked on.

Thumbnail preview placeholder has been added recently to tab tray to avoid this broken feeling when thumbnail isn't available.

**Comment by miaokun-normal** [comment] 2020-07-02 08:37
> 
> 
> Issue about an option to disable dynamic toolbar : #10240
> 
> For tabs UI, it would be too much work to maintain 2 UI, please feel free to provide some feedback about how to improve the new tab tray if it doesn't suit your expectations. Some improvements are already worked on.
> 
> Thumbnail preview placeholder has been added recently to tab tray to avoid this broken feeling when thumbnail isn't available.

If in that case, I think the tab UI should come back as the UI of the previous version of Firefox Preview. It looks better and more easy to use.

**Comment by DavidBE-UK** [comment] 2020-07-02 22:36
Current tab tray is designed entirely to go with the layout with the address bar at the bottom: tab tray initially only extends part way up, keeping the tabs near the bottom, and the new tab action button is right at the bottom. This does NOT fit with the layout where the address bar is at the top. When I first tried Firefox Preview last year, the address bar was at the bottom with no choice: I gave a review/feedback that I personally hate bottom controls, do not use apps with bottom controls, and would not be using this version of Firefox if there was no option to have the controls at the top. I presume I wasn't the only one as the option to move the address bar to the top appeared last December. But that's not enough - new UI areas also need to support the layout choice. If there's no going back on using a bottom sheet tab tray, it should still behave differently when the layout is set to have the address bar at the top - when toolbar top is set in the settings, then the tab tray needs to extend fully up automatically so if only one or two tabs they are near the top, not down near the bottom, and there needs to be a new tab control at the top. I can't imagine it's impossible to have the tab tray behave differently depending on the setting>toolbar setting, and this needs to happen if I'm going to use this. There seems to be some recognition that there are a fair few people who want top controls, and this needs to be factored into the tab tray design, which currently it isn't.

**Comment by sheikh-azharuddin** [comment] 2020-07-04 07:45
I have seen too many comments regarding the new tab tray which is often cumbersome and not aesthetically pleasure....why not use grid layout like microsoft edge...it has the thumbnails , site information, close button and above all more tabs can be accommodated in a single view... A simple and clean ui....

8 tabs on a single screen in my device!!

![Screenshot_20200704-131310](https://user-images.githubusercontent.com/58127841/86507746-45c80000-bdca-11ea-8cba-2b0d5a135431.jpg)

**Comment by kbrosnan** [comment] 2020-07-25 21:07
Duplicate #10240 and #11833

In the future please limit issues to one topic.

**Comment by paritosh9199** [comment] 2020-07-25 21:18
@sheikh-azharuddin IRK the current tab layout is just appalling. I don't know what the UI/UX designer was doing, instead of doing the job. UX on other browsers is just leagues ahead of Firefox. Don't get me wrong Firefox on desktop is really good. But for android and iOS it just sucks. 

tl:dr;
Just fix the damn performance and user experience issues already.

**Closed** 2020-08-28 21:26 UTC
Labels: needs:triage
