### ISSUE TITLE
Search shortcuts should treat URLs as simple search strings, just like desktop Firefox

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#12663] opened 2020-07-17 11:14 UTC
## Steps to reproduce
1. Tap on address bar. It says "Search or enter address".
2. Select the (for example) Wikipedia shortcut under "This time, search with:". Address bar _still_ says "Search or enter address". (This string, "This time, search with:", is what tells me this feature is intended to be the same as the one in desktop Firefox, which has the exact same string.)
3. Enter a search string that is a URL (or Firefox _thinks_ is a URL), such as "x.org", or "x.509" _which are valid Wikipedia page URLs._
4. Fenix tries to open them as URLs, ignoring the search shortcut selection.

### Expected behavior
If you select a search engine, Fenix should execute a search on it, just like desktop Firefox.
What should ideally happen is:

1. Tap on the address bar.
2. Enter a string to search for.
3. Tap on Wikipedia.
4. Fenix should immediately send that string to Wikipedia.

OR

Since you've specifically selected the Wikipedia search shortcut, no matter the search term, the string should be searched on Wikipedia.

1. Tap on address bar. It says "Search or enter address". This is correct behaviour.
2. Select the Wikipedia shortcut. Address bar should change to say: "Search on/with Wikipedia".
3. Enter a search string that is a URL.
4. Fenix should send it to Wikipedia.

### Actual behavior
Firefox continues to treat the search term like a URL, which is a bug. Desktop Firefox does the correct thing and sends it to Wikipedia.

### Device information
* Fenix version: Nightly 200716 18:06 (Build #21981810)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3580)

**Comment by vishalnandagopal** [comment] 2020-08-10 04:56
This is the expected behavior.



You should click on the first search result to search wikipedia, if the URL bar contains a link.

**Comment by opusforlife2** [comment] 2020-08-10 06:12
Can you try this with x.509 and tell me if it works? If so, what steps did you use?

**Comment by vishalnandagopal** [comment] 2020-08-10 13:31
Yes it works. 

1. Open Firefox , then open URL bar by clicking on it.

2. Set Wikipedia as search engine
(by any method - clicking on it in the menu that pops up, or setting it as default, etc)

3. Type 'x.509' in the URL bar.

4. Instead of pressing enter/go on the keyboard, press the first result.


A simple pic - https://i.postimg.cc/Qx11XWR1/Screenshot-20200810-185319.jpg


This is also the same case for Google Search.

If you want to go to YouTube, you type youtube.com in the URL bar and press enter

If you want to search Google for 'YouTube.com' you press the first result below URL bar.

**Comment by vishalnandagopal** [comment] 2020-08-10 13:35
Can you close the issue if there are no more problems? Fenix is already having 2.3k issues.

**Comment by opusforlife2** [comment] 2020-08-10 13:36
> Instead of pressing enter/go on the keyboard, press the first result.

Ah, Now I see. You're using **search suggestions**, which is basically performing the search and then clicking on the first result. That's fine as a workaround. It doesn't affect the validity of this bug, though.

**Comment by vishalnandagopal** [comment] 2020-08-10 17:33
> Ah, Now I see. You're using **search suggestions**, which is basically performing the search and then clicking on the first result. That's fine as a workaround. It doesn't affect the validity of this bug, though.

I'm not clicking anything. Its taking me directly to that page.


This is how it should work. Not a bug. Nothing to fix. You need to be able to directly visit URL's , therefore this is the solution of all mobile browsers.


Any alternative way? The devs might be interested for good ideas

**Comment by opusforlife2** [comment] 2020-08-10 18:12
> I'm not clicking anything. Its taking me directly to that page.

You're clicking a search suggestion. Turn off search suggestions from search settings then try it again. You won't see anything to click.

> You need to be able to directly visit URL's 

If you want to directly visit a URL, you enter the address and tap enter. Why would you select a search engine as a pointless extra middle step?

**Comment by vishalnandagopal** [comment] 2020-08-10 21:09
It is not suggested by search engine. It is just the exact thing in the URL bar.

Search for some non-existant thing. The single top result still appears.


The UI improvement here is to show only the exact same string when suggestions is off. Doesn't send anything to search engine, you also get a query/direct URL

**Comment by opusforlife2** [comment] 2020-08-10 21:25
You know, when you tell me to try something, I do test it before replying to you. You don't seem to be doing the same. **Turn off search suggestions. Your phone will not explode. You will see yourself that there is no single top result.**

**Comment by vishalnandagopal** [comment] 2020-08-11 05:08
> You know, when you tell me to try something, I do test it before replying to you. You don't seem to be doing the same. **Turn off search suggestions. Your phone will not explode. You will see yourself that there is no single top result.**

Sorry if my replies came off as rude. I already mentioned a possible improvement with search suggestions off. I tried with suggestions off in the second try too.

> The UI improvement here is to show only the exact same string when suggestions is off. Doesn't send anything to search engine, you also get a query/direct URL

**Comment by opusforlife2** [comment] 2020-08-11 13:35
No, you didn't come off as rude, I just misread the "suggestions off" part of your comment. I apologise. This is what happens when you stay up late. 🤦 

Your suggestion is a good alternative option, I agree. Personally, I would like for there to be symmetry between desktop and mobile Firefox, which is why I framed my original post as it is.

In fact, it would be great if the exact same behaviour of desktop Firefox could be followed: if you enter a string into the address bar, then tap on a search engine, Firefox should immediately execute that search through it.

**Comment by apbitner** [comment] 2021-01-08 16:55
Agreed that behavior on mobile here should be the same as desktop.

**Comment by opusforlife2** [comment] 2021-07-09 17:09
Further activity has occurred.

**Comment by opusforlife2** [comment] 2021-07-16 18:49
Excuse me, stale bot.

**Comment by opusforlife2** [comment] 2021-07-16 18:56
Oy, stale bot!

**Comment by opusforlife2** [comment] 2021-07-31 21:11
@kbrosnan or someone, please reopen this.

**Comment by cpeterso** [comment] 2022-12-27 22:16
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807731

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2022-12-27 22:16 UTC
Labels: feature request 🌟, eng:ready, Feature:Search
