### ISSUE TITLE
Crash in [@ java.lang.IllegalStateException: at androidx.fragment.app.Fragment.requireContext(Fragment.java)]

### ISSUE THREAD

**Issue by mystiquewolf** [mozilla-mobile/fenix#20208] opened 2021-06-30 13:27 UTC
Crash report: https://crash-stats.mozilla.org/report/index/7f123dc6-e7ba-4104-a357-05b240210630

Java stack trace:
```
java.lang.IllegalStateException
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
	at androidx.core.app.AppOpsManagerCompat.getRequireComponents(AppOpsManagerCompat.java:1)
	at org.mozilla.fenix.share.ShareFragment.consumePrompt(ShareFragment.kt:1)
	at org.mozilla.fenix.share.ShareFragment.access$consumePrompt(ShareFragment.kt:1)
	at org.mozilla.fenix.share.ShareFragment$onCreateView$1.invoke(ShareFragment.kt:3)
	at org.mozilla.fenix.share.DefaultShareController$shareToDevicesWithRetry$1.invokeSuspend(ShareController.kt:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```
This happened on a very slow 64 kbit/sec connection (maybe slower). I tried to send a tab to PC by clicking the button with the "Firefox on my PC" button. As the connection was slow, i clicked it multiple times. Then i clicked outside of the popup with the list of Firefoxes on my devices, then i tried to again "send to device" -> "select device". Then clicked on the device name again and i believe it crashed.

**Comment by mcarare** [comment] 2021-06-30 14:47
Looks like a duplicate of https://github.com/mozilla-mobile/fenix/issues/16538.

**Closed by mcarare** 2021-06-30 14:47 UTC
Labels: b:crash, needs:triage
