### ISSUE TITLE
Optional alphanumeric sorting function for bookmarks and folders

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#18924] opened 2021-04-10 21:54 UTC
### What is the user problem or growth opportunity you want to see solved?

The number of bookmarks increases quickly and becomes confusing as a result. This also applies if you use folders as an organizational aid.

Humans are used to leafing through alphanumeric ones. Sorting bookmarks and folders when a function is called or at regular intervals saves the user’s time and avoids incorrect sorting. 

Such a functionality should be optionally switchable and not preselected.

### How do you know that this problem exists today? Why is this important?

Sorting work is a bit tricky, especially on smartphones with their comparatively small screens.

### Who will benefit from it?

Everybody

**Comment by WebworkrNet** [comment] 2021-04-10 21:58
In addition to ticket "allow users to sort bookmarks # 4348"

**Comment by eliserichards** [comment] 2021-04-12 22:00
Closing as dupe of #4348 (I added a comment with a link to this ticket)

**Closed by eliserichards** 2021-04-12 22:00 UTC
Labels: needs:triage
