### ISSUE TITLE
[Bug]: The app crashes when returning to the add-on details menu after changing device language

### ISSUE THREAD

**Issue by hokonch** [mozilla-mobile/fenix#22995] opened 2021-12-27 11:02 UTC
### Steps to reproduce

1. Tap an add-on that hasn't been added yet in [Add-ons] and show the add-on details
2. Go to Settings app and add a new device language
3. Return to Firefox app

### Expected behaviour

Firefox never crashes.

### Actual behaviour

The app closes unexpectedly.

### Device name

Google Pixel 3a

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

95.2.0 & 97.0a1

### Device logs

----
ee162a6b-2e23-4342-a0df-2b7502bcf18e
`java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #27 in org.mozilla.fenix:layout/activity_home: Binary XML file line #27 in org.mozilla.fenix:layout/activity_home: Error inflating class fragment`
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=c5118febe8ea404cb967d1e985f0bca0
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-a689f42b-3c0c-4b0c-ac55-5a2820211227
----
~~~
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #27 in org.mozilla.fenix:layout/activity_home: Binary XML file line #27 in org.mozilla.fenix:layout/activity_home: Error inflating class fragment
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5738)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5630)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.view.InflateException: Binary XML file line #27 in org.mozilla.fenix:layout/activity_home: Binary XML file line #27 in org.mozilla.fenix:layout/activity_home: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #27 in org.mozilla.fenix:layout/activity_home: Error inflating class fragment
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property binding has not been initialized
	at org.mozilla.fenix.HomeActivity.getSupportActionBarAndInflateIfNecessary(HomeActivity.kt:16)
	at org.mozilla.fenix.ext.FragmentKt.showToolbar(Fragment.kt:3)
	at org.mozilla.fenix.addons.AddonDetailsFragment.onViewCreated(AddonDetailsFragment.kt:4)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:30)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:24)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:73)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
	at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:12)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:23)
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:48)
	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:4)
	at org.mozilla.fenix.HomeActivity.onCreateView(HomeActivity.kt:12)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at org.mozilla.fenix.perf.PerformanceInflater.inflate(PerformanceInflater.kt:5)
	at org.mozilla.fenix.HomeActivity.onCreate(HomeActivity.kt:24)
	at android.app.Activity.performCreate(Activity.java:8051)
	at android.app.Activity.performCreate(Activity.java:8031)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5738)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5630)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
~~~

### Additional information

Similar Device logs: https://github.com/mozilla-mobile/fenix/issues/21162

#### Screen recordings
https://user-images.githubusercontent.com/54430032/147465302-91246915-b924-4846-b84c-200c6faadb9f.mp4

**Comment by SoftVision-LorandJanos** [comment] 2021-12-27 13:00
Hi @hokonch ! Thank you for your report!
I can reproduce the issue you described, consistently, on all the recent builds.
Tested on the:
- latest Nightly 97.0a1 (2021-12-27).
- latest Beta 96.0.0-beta5.
- latest Release 95.2.0.
Device used: Google Pixel 4 (Android 11).

**Comment by Mugurell** [comment] 2021-12-27 13:08
This happens because [in fragment's `onCreateView` we are trying to access the `HomeActivity's toolbar`](https://github.com/mozilla-mobile/fenix/blob/fa377bf0d62aa72206450686858801e731da26fa/app/src/main/java/org/mozilla/fenix/addons/AddonDetailsFragment.kt#L39).
Scenario which works great if the activity is already created and the user navigates through the app but will crash the app in the case of changing the system language because the activity is recreated for the changes to be applied. And in this scenario the fragment is trying to access and configure a view from the new activity before it being created.

We could move the toolbar interaction to `onResume` or a bit better to `onStart` but this might still show a glitch so the best approach here seems to be to follow [Android's recommendation about registering a lifecycleObserver for when the activity is created](https://developer.android.google.cn/reference/androidx/fragment/app/Fragment).

While this scenario might not be too common the issue is bigger because this same flow of updating the toolbar from `onCreateView` is used [in many of our fragments](https://github.com/mozilla-mobile/fenix/search?q=showToolbar) - and the app will crash in each of those cases.

**Comment by SoftVision-LorandJanos** [comment] 2022-01-06 08:46
This issue is no longer reproducible on the latest Nightly (2022-01-06).
Tested with Google Pixel 4 (Android 11).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-01-06 08:46 UTC
Labels: 🐞 bug, b:crash, eng:qa:needed, Feature:WebExtensions, qa-triaged
