### ISSUE TITLE
[Bug]Android taskbar media notification detailts don't match with the one from the lock screen

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#5294] opened 2019-09-13 07:52 UTC
## Steps to reproduce
1. Navigate to Twitter.com 
2. Play any video
3. Check the Android taskbar media notification details
4. Lock the screen of the device
5. Press the power button an check the lockscreen media notification

### Expected behavior
The details of the media notifications should match

### Actual behavior
Properly displayed media notification on the Android taskbar.
Missing media notification details on lockscreen. 

### Device information

* Android device: Samsung Galaxy tab a (Android 9)
* Fenix version: 2.0.0-rc.2

### Notes

►Android taskbar
![rsz_1screenshot_20190913-103351_one_ui_home](https://user-images.githubusercontent.com/51314259/64846070-56797080-d614-11e9-8365-4624e0f2e23d.jpg)

►Lockscreen
![rsz_screenshot_20190913-103407_one_ui_home](https://user-images.githubusercontent.com/51314259/64846106-70b34e80-d614-11e9-995b-cfadc8148581.jpg)

**Comment by boek** [comment] 2019-09-16 21:36
Tested with a Pixel 2/3 with Android 9/10 and could not reproduce.
Was able to reproduce with the Galaxy S9 on Android 9. This seems to be a Samsung specific bug.

**Comment by boek** [comment] 2019-09-16 22:07
Spoke with @vesta0, since this is Samsung specific we're not going to block the release but will follow up with 2.1

**Comment by pocmo** [comment] 2019-09-17 15:50
Duplicate of https://github.com/mozilla-mobile/fenix/issues/5177

**Closed by pocmo** 2019-09-17 15:50 UTC
Labels: Feature:Media, S2, a-c, 🐞 bug, 🙅 waiting
