### ISSUE TITLE
Frequent Crash 

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#15461] opened 2020-09-26 15:55 UTC
Every time I open Firefox nightly, it crashes just after few seconds. Its happening since latest update

Firefox version: Nightly 200926 06:03 (Build #2015766131)
AC: 61.0.20200925130131, 9cc43cfa2
GV: 83.0a1-20200922094538
AS: 63.0.0

Device: Xiaomi Redmi Note 4 Android 7.0

Somehow managed to gather one of crash log:

   dc7e30fa-0428-4a02-b3f9-6e12ded1dc8f
mozilla.appservices.fxaclient.FxaException$Network: Network error: [no-sentry] Network error: Java error: "fetch error: org.mozilla.geckoview.WebRequestError: Request failed, error=0x25, category=0x5"
----
mozilla.appservices.fxaclient.FxaException$Network: Network error: [no-sentry] Network error: Java error: "fetch error: org.mozilla.geckoview.WebRequestError: Request failed, error=0x25, category=0x5"
	at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:5)
	at mozilla.appservices.fxaclient.FirefoxAccount.getTokenServerEndpointURL(FirefoxAccount.kt:9)
	at mozilla.components.service.fxa.FirefoxAccount.getTokenServerEndpointURL(FirefoxAccount.kt:1)
	at mozilla.components.service.fxa.manager.FxaAccountManager.maybeUpdateSyncAuthInfoCache(FxaAccountManager.kt:13)
	at mozilla.components.service.fxa.manager.FxaAccountManager$maybeUpdateSyncAuthInfoCache$1.invokeSuspend(FxaAccountManager.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)

**Comment by s-ankur** [comment] 2020-09-26 20:48
Duplicate of https://github.com/mozilla-mobile/fenix/issues/15412, the fix is already merged, will probably be in an update soon

**Closed** 2020-09-29 13:00 UTC
Labels: needs:triage
