### ISSUE TITLE
Show all tabs at top on tablets again

### ISSUE THREAD

**Issue by Supreeeme** [mozilla-mobile/fenix#14497] opened 2020-08-30 16:55 UTC
Before the big update, Firefox would show all of the tabs up top on tablets and not hidden behind another menu, similar to how tabs function on your typical desktop browser. I'd like to see this return.

**Comment by s-ankur** [comment] 2020-08-30 18:13
Check out  #2344, this is a duplicate of that

**Comment by kbrosnan** [comment] 2020-08-30 21:27
Closing as a duplicate

**Closed by kbrosnan** 2020-08-30 21:27 UTC
Labels: needs:triage
