### ISSUE TITLE
FNX-3257 ⁃ Display the toolbar at the end of the document

### ISSUE THREAD

**Issue by Simounet** [mozilla-mobile/fenix#10052] opened 2020-04-19 20:07 UTC
Hi there,
It could be great having the toolbar showing up when reaching the end of the document. It's quite surprising to have nothing to do after that.
Have a nice day and stay safe.

**Comment by eliserichards** [comment] 2020-05-06 19:29
Closing as a duplicate of #10065 and #9575

**Closed** 2020-08-10 18:25 UTC
Labels: Feature:Toolbar
