### ISSUE TITLE
Request desktop site does not work for all sites

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#442] opened 2019-02-12 08:52 UTC
### Steps to reproduce
1. Go to wikipedia.org.
2. Tap on the 3 dot menu and toggle the "Request desktop site" option.

### Expected behavior
* The desktop site is requested and displayed after a page reload.

### Actual behavior
* Nothing happens, the site remains in mobile version.

### Device information & notes
* Android device:
  
  * Nexus 5 (Android 6.0.1)
  * Nokia 6 (Android 7.1.1)
  * Samsung Galaxy Note 8 (Android 8)
  * Google Pixel (Android 9)
* Fenix version: 1.0 (12.08.2019 - taskcluster id: CX8is5arTZmzWLJ9BGRGAA)
* Certain pages are not affected by this (eg. google.com), while on others like wikipedia, if you request the desktop site and then navigate to a different page it will give you the desktop version of that page.
* The same issue has been logged for R-B as well [Link](https://github.com/mozilla-mobile/reference-browser/issues/593)

**Comment by ekager** [comment] 2019-02-13 01:12
Thanks @bsurd!

It looks like this webpage is a responsive page, so we are requesting the desktop site, but without also messing with the window size, we are then getting the mobile sized responsive site.

**Comment by kbrosnan** [comment] 2019-04-29 23:58
This bug then is that request desktop site should use a desktop view port size and screen density to emulate a desktop display.

**Comment by sblatz** [comment] 2019-05-07 18:37
We're actually already setting a `wideViewPort` [in a-c](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt#L327).

@cpeterso is there a possibility GV isn't setting the view port wide enough?

**Comment by bluemarvin** [comment] 2019-05-07 23:12
In addition to setting the UA, the desktop viewport must be enabled: https://searchfox.org/mozilla-central/rev/99a2a5a955960b0e58ceade1db1f7652d9db4ba1/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSessionSettings.java#189

**Comment by jonalmeida** [comment] 2019-05-10 19:10
> In addition to setting the UA, the desktop viewport must be enabled: https://searchfox.org/mozilla-central/rev/99a2a5a955960b0e58ceade1db1f7652d9db4ba1/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSessionSettings.java#189

Ah, this is new from when desktop mode was implemented. It's definitely an a-c fix needed.

**Comment by sblatz** [comment] 2019-05-10 21:20
@bluemarvin, @jonalmeida  Setting the viewport doesn't seem to have any effect on the affected site (wikipedia.org).

What's odd is that, even without this change and just using the user agent "desktop" mode, I'm getting a "wider" view port on many sites:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/57557353-a4acf900-732e-11e9-8b46-110d060cd179.png">

**Comment by jonalmeida** [comment] 2019-05-10 21:28
> What's odd is that, even without this change and just using the user agent "desktop" mode, I'm getting a "wider" view port on many sites

"Desktop mode" isn't a standard that exists or convention every site follows unfortunately, so some sites change themselves by UA or viewport. Since the site in question right now is wikipedia, we should focus on that as our initial test. I see Focus GV showing the desktop version of the site, so I'm curious what's happening there that we aren't doing (since the a-c was originally based off that).

**Comment by sblatz** [comment] 2019-05-10 21:45
@jonalmeida Even weirder: all Focus is doing is setting the user agent (https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt#L258)

**Comment by jonalmeida** [comment] 2019-05-10 23:28
> @jonalmeida Even weirder: all Focus is doing is setting the user agent (https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt#L258)

It seems like [Focus is using GV 65](https://github.com/mozilla-mobile/focus-android/blob/master/build.gradle#L10) which is before the API had been added view ports, so there might have been a regression in GV. Worth filing a bug there next!

**Comment by cpeterso** [comment] 2019-05-11 00:39
focus-android's master is out of date. The latest code is in the releases/v8.0 branch:

https://github.com/mozilla-mobile/focus-android/commits/releases/v8.0

**Comment by sblatz** [comment] 2019-05-13 17:56
@cpeterso could catch, though I still don't see Focus setting the viewport at all: https://github.com/mozilla-mobile/focus-android/blob/releases/v8.0/app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt#L243.

Of note, Focus is using [this GV](https://github.com/mozilla-mobile/focus-android/blob/releases/v8.0/build.gradle#L10) version. Is it possible there actually is a regression?

**Comment by softvision-miralobontiu** [comment] 2019-05-16 12:10
Verified as fixed on the latest build 1.0.1920 (#11360657), with Google Pixel (Android 9), Nexus 5 (Android 6.0.1), Samsung Galaxy S8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).

**Closed** 2019-05-16 12:17 UTC
Labels: Feature:Request Desktop Site, Needs GV work, P1, QA needed, a-c, 🐞 bug, 🕵️‍♀️ needs investigation
