### ISSUE TITLE
[Bug] WebRender experiment enrollment generates a Fenix Nightly app crash

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla-mobile/fenix#7864] opened 2020-01-22 15:10 UTC
**[Affected versions]:**
Firefox Preview 74.0a1 Build ID 20200115093807

**[Affected Platforms]:**
- Android 8.0.0
- Android 10.0.0

**[Notes]:**
- Have Android Studio installed on your computer.
- Connect your Android device to the PC and allow USB debugging on your device.

**[Steps to reproduce]:**
1. Open a Command Prompt on your desktop.
2. Run the adb command: adb shell am start -n org.mozilla.fenix.nightly/mozilla.components.service.experiments.debug.ExperimentsDebugActivity --ez updateExperiments true --es overrideExperiment "webrender-performance-comparison-experiment" --es branch "enable_webrender" and observe your device.
3. Verify in about:support page if the user is enrolled in the experiment.

**[Expected result]:**
Fenix Nightly app is opened with success. User is enrolled in the experiment.

**[Actual result]:**
Fenix Nightly app crashes.

**[Additional notes]:**
- Issue is also reproduced while trying to use "disable_webrender" branch.
- Logcat details - https://drive.google.com/drive/u/1/folders/1GBHph1Ludyml-WVrpElOVF8LpdZngwIQ

**Comment by liuche** [comment] 2020-01-23 02:07
```
020-01-22 10:48:03.586 1184-2667/? I/ActivityManager: START u0 {flg=0x10000000 cmp=org.mozilla.fenix.nightly/mozilla.components.service.experiments.debug.ExperimentsDebugActivity (has extras)} from uid 2000
2020-01-22 10:48:03.608 1184-1713/? I/ActivityManager: Start proc 11656:org.mozilla.fenix.nightly/u0a150 for activity org.mozilla.fenix.nightly/mozilla.components.service.experiments.debug.ExperimentsDebugActivity
2020-01-22 10:48:03.863 11656-11656/? D/ExperimentsDebugActivity: onCreate
2020-01-22 10:48:03.864 11656-11656/? I/ExperimentsDebugActivity: Force update of experiments
2020-01-22 10:48:03.864 11656-11656/? I/ExperimentsDebugActivity: Override to the following experiment/branch:webrender-performance-comparison-experiment/enable_webrender
2020-01-22 10:48:03.866 11656-11683/? E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: org.mozilla.fenix.nightly, PID: 11656
    kotlin.UninitializedPropertyAccessException: lateinit property updater has not been initialized
        at androidx.transition.CanvasUtils.throwUninitializedPropertyAccessException(CanvasUtils.java:2)
        at mozilla.components.service.experiments.ExperimentsInternalAPI.getUpdater$service_experiments_release(Experiments.kt:1)
        at mozilla.components.service.experiments.debug.ExperimentsDebugActivity$onCreate$1.invokeSuspend(ExperimentsDebugActivity.kt:3)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:15)
2020-01-22 10:48:03.870 11656-11656/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 11656
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix.nightly/mozilla.components.service.experiments.debug.ExperimentsDebugActivity}: kotlin.UninitializedPropertyAccessException: lateinit property context has not been initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2826)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2904)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6600)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property context has not been initialized
        at androidx.transition.CanvasUtils.throwUninitializedPropertyAccessException(CanvasUtils.java:2)
        at mozilla.components.service.experiments.debug.ExperimentsDebugActivity.onCreate(ExperimentsDebugActivity.kt:54)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2779)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2904) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6600) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772) 
2020-01-22 10:48:04.376 1184-1224/? W/ActivityManager: Activity pause timeout for ActivityRecord{68e7e8d u0 org.mozilla.fenix.nightly/mozilla.components.service.experiments.debug.ExperimentsDebugActivity t375 f}
2020-01-22 10:48:06.668 1184-2668/? W/ActivityManager:   Force finishing activity org.mozilla.fenix.nightly/mozilla.components.service.experiments.debug.ExperimentsDebugActivity
```

**Comment by liuche** [comment] 2020-01-23 02:08
We decided not to enable experiments in Nightly, because there were some startup crashes that had been caused by some version checking differences in the experimenter platform.

We could revisit that decision, but since we don't initialize Experimenter on Nightly at all that's probably the cause.

**Comment by kbrosnan** [comment] 2020-07-27 23:42
@liuche is experimenter still something we want to fix here. Is there value in this bug being open?

**Comment by kbrosnan** [comment] 2020-08-05 20:59
Going to close this. Comment/reopen if this is still relevant.

**Closed by kbrosnan** 2020-08-05 20:59 UTC
Labels: b:crash, needs:triage, 🐞 bug

**Comment by liuche** [comment] 2020-08-06 00:58
This was actually fixed in https://github.com/mozilla-mobile/fenix/pull/11977 but I had forgotten this issue was filed.
