### ISSUE TITLE
FNX-13072 ⁃ autofill address

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12054] opened 2020-06-27 14:16 UTC
### What is the user problem or growth opportunity you want to see solved?
Currently autofill address feature is missing. If added it will help to fill the address in multiple sites without typing too much. Chromium browsers already have this.

### How do you know that this problem exists today? Why is this important?
To fill addresses user need to type too much this will save the effort and time

### Who will benefit from it?
All users

**Comment by cadeyrn** [comment] 2020-06-27 14:20
Duplicate of already [four other](https://github.com/mozilla-mobile/fenix/issues?q=is%3Aissue+is%3Aopen+autofill+address) open issues.

**Comment by kbrosnan** [comment] 2020-06-27 21:42
Closing as a duplicate

**Closed** 2020-08-11 05:40 UTC
Labels: needs:triage
