### ISSUE TITLE
[Bug] The Dark Reader add-on has stopped working for lots of websites in recent nightlies

### ISSUE THREAD

**Issue by birdie-github** [mozilla-mobile/fenix#18574] opened 2021-03-21 15:23 UTC
For the past ten days the Dark Reader add-on has been malfunctioning in Firefox Nightly for Android.

Steps to reproduce:

1) Install the add-on, don't change any settings
2) Open https://github.com/mozilla-mobile/fenix
3) Check the results - only half the page will remain unthemed, i.e. it's black text on a white background

Not all webpages/websites are affected but a lot of them are.

It's a regression. See the attached screenshot.

![Screenshot](https://user-images.githubusercontent.com/4958603/111910408-2b69ab80-8a59-11eb-945b-8d6920ed8535.png)

**Comment by evilpie** [comment] 2021-03-21 19:24
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1697829

**Comment by birdie-github** [comment] 2021-03-21 23:20
On a second thought please close it yourself because if necessarysince the bug hasn't yet been fixed and affected people might not discover this already open bug report.

**Comment by kbrosnan** [comment] 2021-03-22 03:29
We don't keep upstream bugs open.

**Closed by kbrosnan** 2021-03-22 03:29 UTC
Labels: needs:triage, 🐞 bug
