### ISSUE TITLE
FNX-13634 ⁃ Swipe to delete bookmarks

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#12551] opened 2020-07-14 15:55 UTC
Broken out from #176 

### What is the user problem or growth opportunity you want to see solved?
Users should be able to swipe to delete bookmarks.

### How do you know that this problem exists today? Why is this important?
This is not possible currently. Deletion is done by tapping the three dot menu and selecting delete.

### Who will benefit from it?
Everyone who deletes items from bookmarks.

**Comment by person808** [comment] 2020-07-15 20:51
Going to break swipe to delete history out into a separate issue because there are some problems with implementing it that need more thought.

**Comment by ShatteredPixel** [comment] 2020-07-22 04:10
@person808 

There's a bug with this behaviour. See the GIFs. You may need to swipe a bit diagonally to reproduce it. Even if I try to swipe exactly horizontally in a straight line it reproduces most of the time and of course I can do the swipe to delete gestures action if I try harder but it's not intuitive and the swipe action seems to be triggering the 3-dot menu which I think it should not.

See the GIFs: 



Thank you. :)

**Comment by person808** [comment] 2020-07-22 15:53
Hm that definitely doesn't seem right. Could you open a new issue with what you posted and tag me? I'll add it to my backlog. Thanks!

**Comment by sflorean** [comment] 2020-07-24 15:30
Verified as fixed on Nightly 7/24 with Samsung Galaxy Note 10(Android 10) and Huawei MediaPad M2(Android 5.1.1). 

@ShatteredPixel I was able to reproduce your issue also, I will leave a comment on the bug.

**Closed** 2020-08-11 06:43 UTC
Labels: Feature:Bookmarks, Feature:Gesture, eng:qa:verified, feature request 🌟
