### ISSUE TITLE
[Bug] Fenix is unusably slow 

### ISSUE THREAD

**Issue by evilpie** [mozilla-mobile/fenix#8389] opened 2020-02-13 14:41 UTC
## Steps to reproduce
- Go to google.com
- Enter Hacker News
- Goto news.ycombinator.com

### Expected behavior
Loads in 1-2 seconds max.

### Actual behavior
Loads for ~15 seconds, hangs, app unresponsive.

### Device information

* Android device: 9
* Fenix version: Nightly 200210 GV: 74.0a1

## Additional Information
I just got updated from Firefox Nightly (Fennec) to Firefox Nightly (Fenix). I sadly now have to abandon using Nightly because it's unusable. I am attaching a screen recording. I will try to run a profiler if possible.

Videos: https://drive.google.com/drive/folders/18GtTuhNAqa1UutcQb7_PsnG3weQDLqPp?usp=sharing

**Comment by abodea** [comment] 2020-02-13 15:00
Thank you for this report @evilpie!

Note that I tried to reproduce this issue but I wasn't able to.
I updated from Firefox Nightly(Fennec) to Firefox Nightly(Fenix), note that I followed the steps from the description and the `Hacker news` website loaded in 1-2 seconds after the update.

I used Samsung Galaxy S10+ (Android 9), can you specify exactly what device are you using?

**Comment by evilpie** [comment] 2020-02-13 15:02
Samsung Galaxy S8

**Comment by ecsmyth** [comment] 2020-02-13 19:03
Unable to reproduce on:
* ZTE Maven running Nightly build 20440605
* Samsung Galazy S10 Intl build 20440606

@evilpie, if you're able to reproduce consistently, could you grab a [profile](https://profiler.firefox.com/docs/#/./guide-remote-profiling) to help us investigate?

**Comment by evilpie** [comment] 2020-02-13 19:17
Here you go: https://perfht.ml/2uL4VhD

This is using a slightly different STR, I directly entered news.ycombinator.com in the address bar, but the issue still reproduces.
The profile seems to indicate to me that for a long time we are basically not doing any work?

**Comment by ebalazs-sv** [comment] 2020-02-14 07:47
Hi!
I tested this on Nightly Migration Build 02/10 with Samsung Galaxy S8 (Android 9) and I wasn't able to reproduce it.
[Video](https://drive.google.com/file/d/11tvioCV5avOLJGMVpGixmiKTuPuHXicl/view)

**Comment by csadilek** [comment] 2020-02-14 13:59
@evilpie looking at your profile, it seems you have uBlock enabled. Can you try disabling it (Settings->Addons) and see if the problem is still reproducible? To make sure you're not running into this case: https://github.com/mozilla-mobile/fenix/issues/8251

**Comment by evilpie** [comment] 2020-02-14 14:07
After removing uBlock I had a single instance where the load took 2-3 seconds, but now it's back to being slow.

https://perfht.ml/37tEYjU

**Comment by yaomtc** [comment] 2020-02-15 16:07
Twitter has had issues with slowness/unresponsiveness, where sometimes just hitting the back button (on Twitter, not Firefox) takes several seconds to do anything at all, and if I tap it again it ends up opening the Account Info sidebar a moment later as if I clicked on my avatar that wasn't yet visible...

**Comment by boek** [comment] 2020-02-18 18:41
Closing as a dup of #8389

**Closed by boek** 2020-02-18 18:41 UTC
Labels: eng:performance, needs:group-triage, needs:triage, 🐞 bug
