### ISSUE TITLE
[Bug] browser.notifications.create() does not display notification on Android

### ISSUE THREAD

**Issue by Offerel** [mozilla-mobile/fenix#15743] opened 2020-10-07 07:37 UTC
## Steps to reproduce
* Install a webextension which uses browser.notifications.create().
* Documentation is available at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/create where Firefox Android supports this API.
* Call the procedure/function which raises this notification
* Example code:
```
browser.notifications.create("error", {
		"type": "basic",
		"title": "Example Title",
		"iconUrl": browser.runtime.getURL("icons/myicon.png"),
		"message": "Some useful text"
	});
```
or:
```
chrome.notifications.create("error", {
		"type": "basic",
		"title": "Example Title",
		"iconUrl": browser.runtime.getURL("icons/myicon.png"),
		"message": "Some useful text"
	});
```

### Expected behavior
* A notification is displayed with the options and values defined inside the browser.notifications.create() function.

### Actual behavior
* The notification is not displayed and no error message is available on the console

### Device information

* Android device: Samsung Galaxy S9
* Fenix version: Firefox Nightly

**Comment by Amejia481** [comment] 2020-10-07 13:52
Not sure if this is related to the work that you did with the push service @jonalmeida, tagging you just in case you have some background :)

**Comment by Offerel** [comment] 2020-10-07 16:05
I don't know if that helps. I have found this problem by testing a beta version of my extension, which you can find at https://github.com/Offerel/SyncMarks-Extension/blob/master/scripts/background.js at line 234, function notify().

**Comment by dessant** [comment] 2020-10-07 16:15
Duplicate of #https://github.com/mozilla-mobile/fenix/issues/14993.

**Closed** 2020-10-07 17:02 UTC
Labels: needs:triage, 🐞 bug
