### ISSUE TITLE
[Search] No animation in 3-dot menu

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8708] opened 2020-02-24 21:41 UTC
Steps to reproduce:
1. Open a new tab from homescreen and type in any URL
2. Tap on the 3-dot menu in the search bar next to the open tabs icon

Expected:
3-dot menu animates in (like the 3-dot menu on homescreen)

Actual:
No animation

**Comment by sblatz** [comment] 2020-02-26 19:44
I have fixed this in the latest nightly :)

**Comment by sblatz** [comment] 2020-02-26 19:45
Dupe of https://github.com/mozilla-mobile/fenix/issues/8644

**Closed by sblatz** 2020-02-26 19:45 UTC
Labels: Feature:Search, eng:qa:needed, implementation review, needs:triage, ux:motion-design

**Comment by sv-sdeiac** [comment] 2020-02-28 13:19
Verified as fixed using the latest version of Firefox Preview Nightly 2/28 #20590606.

Devices:
- Xiaomi Mi 8 Lite (Android 9);
- Samsung Galaxy Note 8 (Android 9).
