### ISSUE TITLE
FNX-5212 ⁃ Beta branding of the application: app identifier, different name, remove Fenix, etc.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#1726] opened 2019-04-17 19:10 UTC
> I could not find another issue or epic for this work. If there is, please discard this one.

Our beta release will need to go out with different branding. We will need at least a different app name. What other assets need to be updated?

* Product name in strings?
* Logos?
* Other Assets?

Do we need to keep the current branding in Nightly? Or can we just switch it all over? Is it ok if Nightly users get to see the branding changes we make?

**Comment by vesta0** [comment] 2019-04-18 14:36
Duplicate of #1714

**Closed** 2020-08-11 12:35 UTC
Labels: must
