### ISSUE TITLE
FNX-12964 ⁃ As a user, I'd like to know how many tabs exist in the other private/normal browsing list in the tabs tray

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#11959] opened 2020-06-25 15:50 UTC
### What is the user problem or growth opportunity you want to see solved?
Users want to be able to know if they have any tabs open in normal/private mode before clicking between the normal/private tabs.

### How do you know that this problem exists today? Why is this important?
Broken out of #11833

### Who will benefit from it?
Tabs tray users with tabs open in both modes

**Comment by sheikh-azharuddin** [comment] 2020-06-25 17:32
You can add a counter to the top section of the tab tray to indicate number of open tabs in each mode.
Sorry for large highlighter..but idea is same it will show the number close to the icon. Just a suggestion!

![7047](https://user-images.githubusercontent.com/58127841/85769731-ccfddf80-b709-11ea-98b2-8fb43932c3e1.png)

**Comment by Dunexus** [comment] 2020-06-25 21:06
If i understrand the issue well, it is a dupe of https://github.com/mozilla-mobile/fenix/issues/10874 and is covered by https://github.com/mozilla-mobile/fenix/issues/10849

**Comment by ekager** [comment] 2020-06-25 21:36
Nice thanks @Dunexus - closing for #10874 and #10849

**Closed** 2020-08-11 05:18 UTC
Labels: Feature:Tabs, needs:UX-feedback
