### ISSUE TITLE
FNX3-16642 ⁃ [Bug] Tabs briefly visible in PB and gone from normal browsing homescreen (and vice-versa)

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2874] opened 2019-05-27 13:00 UTC
## Steps to reproduce
1. Open a tab in normal browsing.
1. Switch to private browsing and back to normal. Repeat.
*same steps are valid switching from private browsing to normal.

### Expected behavior
N.b. tabs are not displayed in P.b. N.b tabs are displayed on the homescreen all the time.

### Actual behavior
Tabs are displayed in P.b. 
Returning to normal browsing, the tabs are not displayed until you scroll the homescreen up.
*Same thing if you open tabs in p.b and switch to normal.

![20190527](https://user-images.githubusercontent.com/4037709/58420894-3474d600-8097-11e9-8ac4-0771cb8d4933.gif)UNITO-UNDERSCORE!154921!

### Device information
* Android device: On Nexus 5 (Android 6) & Mi4 (Android 5)
*Not reproducing on Galaxy Note 8 (Android 9), Sony Xperia Z5 (Android 7.1.1)
* Fenix version: 5/27

**Comment by vesta0** [comment] 2019-05-30 23:24
I couldn't reproduce. @sv-ohorvath could you please verify that this is still happening?

**Comment by sv-ohorvath** [comment] 2019-05-31 08:23
Still reproducing, checked on P9 Lite (Android 6.0). I think it's an issue on Android 6 and lower.

**Comment by sblatz** [comment] 2019-06-21 16:41
@sv-ohorvath is this still happening on the latest nightly?

**Comment by sv-ohorvath** [comment] 2019-07-01 08:36
I can't reproduce on the latest nightly 6/28 build.

**Comment by sv-ohorvath** [comment] 2019-09-03 11:25
Reproducing again on RC 2.0 and Nightly 9/3.
Devices:
• HTC Desire 820 (Android 6.0.1)
• Samsung Galaxy S6 (Android 6.0.1)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

**Comment by softvision-miralobontiu** [comment] 2019-09-27 08:49
Verified as fixed on the latest Nightly build 190927 (#12700627) with Samsung Galaxy Tab A6 (Android 5.1.1), Huawei Media Pad M2 (Android 5.1.1), and Huawei P9 Lite (Android 6).

**Closed** 2020-08-12 17:41 UTC
Labels: P3, eng:qa:verified, 🐞 bug
