### ISSUE TITLE
Add DNS over HTTPS option for fenix browser.

### ISSUE THREAD

**Issue by stevenleeS0ht** [mozilla-mobile/fenix#5185] opened 2019-09-10 08:13 UTC
### Why/User Benefit/User Problem

Protecting privacy. 
Be consistent with Firefox for desktop.

### What/Requirements

add option for DNS over HTTPS (DoH).

### Acceptance Criteria (how do I know when I’m done?)

providing an option in system preference -> general. (Same as firefox for desktop).

**Comment by cadeyrn** [comment] 2019-09-10 08:19
Duplicate of #4584.

**Closed** 2019-10-04 21:55 UTC
Labels: 🌟 feature request
