### ISSUE TITLE
FNX3-16072 ⁃ [Bug] "Your Library" has to be exposed to Pontoon

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2114] opened 2019-04-28 17:01 UTC
The string "Library" was changed back to "Your Library". This string has to be exposed to Pontoon as soon as possible because according to https://groups.google.com/forum/#!topic/mozilla.dev.l10n/18JYpiyaZcU the deadline for getting the translations into the Fenix Beta is already in two days and it still can't be translated…

**Comment by mheubusch** [comment] 2019-04-29 15:00
Let's leave it as Library for now, test to understand if the issue is with "Your" vs not "Your" or if the issue is that Library is not an effective category name/organizational concept.

**Comment by mheubusch** [comment] 2019-04-29 15:00
Closing and will circle back with UX team to move to backlog.

**Comment by cadeyrn** [comment] 2019-04-29 15:10
@mheubusch The string was already changed from "Library" to "Your Library" a week ago. If the new string won't be exposed to Pontoon then #1945 has to be reverted.

/cc @ekager since you did the last change of this string, the deadline for the translations is tomorrow according to the announcement on mozilla.dev.l10n and I don't want the string to be untranslated in the first official Beta. ;-)

**Comment by mheubusch** [comment] 2019-04-29 15:12
Oh - I misunderstood - I thought it was still Library pending string uplift.  OK - Let's put that thru to pontoon so we don't have an unlocalized string.  Reopening.

**Comment by vesta0** [comment] 2019-05-10 17:51
This is fixed. Please re-opened if that's not the case.

**Closed** 2020-08-11 10:27 UTC
Labels: 🌐 L10N, 🐞 bug
