### ISSUE TITLE
[Bug] "github.com" - Can't scroll list of items on the column of a project page

### ISSUE THREAD

**Issue by rafalopilowski1** [mozilla-mobile/fenix#12295] opened 2020-07-05 14:37 UTC
## Steps to reproduce
* Open up e.g. ["Hershey's :chocolate_bar:"](https://github.com/mozilla-mobile/fenix/projects/49) project (on the browser or as a Custom Tab)
* Scroll list of items on e.g. "Backlog" column
    1. Expected behavior
List of items scrolls properly.
    1. Actual behavior
List of items doesn't scroll.
[Screencast of the issue (on Custom Tab)](https://streamable.com/sp061z) - cut as it includes another issue

Issue on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1650644

### Tracking protection
Disabling Tracking protection doesn't resolve the bug.

### Other browsers
* Firefox: List of items scrolls properly.
* Chrome: List of items scrolls properly.
    1. Device information
* Android device: OnePlus 6 (Android 10)
* Fenix version: 
> Nightly 200705 06:01 (Build #21870613)
> AC: 49.0.20200702190156, bafa9299b
> GV: 80.0a1-20200702094606
> AS: 61.0.7

**Comment by s-ankur** [comment] 2020-08-02 09:13
Seems to be fixed now, cannot reproduce on latest nightly

**Comment by rafalopilowski1** [comment] 2020-08-02 11:35
@s-ankur 

Proposed fixes ([D84938](https://phabricator.services.mozilla.com/D84938) and [D84939](https://phabricator.services.mozilla.com/D84939)) haven't landed yet. It turned out to be a edge case going beyond GitHub. You can look it up at [BZ-1650644](https://bugzilla.mozilla.org/show_bug.cgi?id=1650644).

Quoting an assignee:

> This test case has a green 100vh height element. That means the bottom part of the element is covered by the bottom dynamic toolbar initially. But the content is not scrollable at all.

([reduced test case](https://bugzilla.mozilla.org/attachment.cgi?id=9163742)) - can be reproduced on Firefox Nightly (build #22150627)

**Comment by Mugurell** [comment] 2021-02-03 19:31
I would've though this was fixed but I can still reproduce it with https://bug1650644.bmoattachments.org/attachment.cgi?id=9163742
Thank you @rafalopilowski1 !

**Comment by Mugurell** [comment] 2021-08-03 05:45
I see that scrolling works as expected in the current Nightly on https://github.com/mozilla-mobile/fenix/projects/49#column-9542273 so this seems to have gotten resolved in the meantime.
@rafalopilowski1 can you confirm?

**Comment by rafalopilowski1** [comment] 2021-08-03 08:39
@Mugurell Now it's working as expected as BZ issue has been resolved.

[https://bugzilla.mozilla.org/show_bug.cgi?id=1650644](https://bugzilla.mozilla.org/show_bug.cgi?id=1650644)

**Closed** 2021-08-03 08:40 UTC
Labels: b:web-content, needs:gv, 🐞 bug
