### ISSUE TITLE
[Bug]: Tracking content allowed after using Reader View

### ISSUE THREAD

**Issue by matiusuario** [mozilla-mobile/fenix#24803] opened 2022-04-14 18:58 UTC
### Steps to reproduce

1. Set Enhanced Tracking Protection to Strict.
2. Open a web page which supports Reader View (e.g https://www.androidcentral.com/android-tv).
3. Enable Reader View.
4. Disable Reader View.

### Expected behaviour

After disabling Reader View, Enhanced Tracking Protection should still block tracking content as it did before.

### Actual behaviour

A lot of trackers are in "Allowed" section of Enhanced Tracking Protection and advertisings are shown in the website or any other website opened in that tab until it is closed.

https://user-images.githubusercontent.com/103613625/163457797-43eee47b-04e1-4033-a68b-27ba59cabea8.mp4

### Android version

Android 8.1 (Android 10 and Android 11 too)

### Firefox release type

Firefox Nightly

### Firefox version

From Nightly 201011 17:12 to 101.0a1

### Additional information

Making a sort of dichotomic-search testing through nightly versions I found out that this bug was first introduced at Firefox Nightly 201011 17:12 (Build #2015769099; AC: 63.0.20201010143128, 621b1649a; GV: 83.0a1-20201010093708; AS: 63.0.0), affecting Beta versions since 83.0.0-beta.1 (Build #2015771051; GV: 83.0-20201019162914)

**Comment by LaurentiuApahideanSV** [comment] 2022-04-19 13:44
I can confirm the issue is reproducible on Nightly 2022-04-19. The issue has also been reported here: https://github.com/mozilla-mobile/fenix/issues/23211. I will close this issue as it will be handled there.

### Device used:
- Google Pixel 6 (Android 12)
- Oppo Find X3 Neo (Android 11)

**Closed by LaurentiuApahideanSV** 2022-04-19 13:44 UTC
Labels: 🐞 bug, needs:triage
