### ISSUE TITLE
[Bug] Theme not switching with the system theme when it is set to follow device theme

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#11372] opened 2020-06-09 15:26 UTC
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1644010

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0

Steps to reproduce:

Set system theme to change from light to dark automatically with sunset/sunrise.
Set Firefox to follow device theme.
Device: Samsung S10e
Android version: 10

Actual results:

When system changed to light theme at sunrise Firefox remained in dark mode. This persisted even if I switched theme to light and then back to follow device theme.
A restart of device made Firefox detect the theme change.
Other apps successfully detected the device theme change at the correct time.

Expected results:

Theme should have changed to light.

**Comment by wurstsemmel** [comment] 2020-11-19 08:59
I can confirm the described issue.

Further, I can force Firefox for Android to switch to light mode by closing the app completely and re-open it.

Samsung Galaxy S9
OneUI 2.5 (Android 10)
Firefox Browser 82.1.3 from Google Play Store

**Comment by masayuki-nakano** [comment] 2020-11-20 02:18
I also reproduce this bug with Samsung Galaxy Tab S5e (Android 10, OneUI 2.5).

However, I see a different thing everyday. After sunrise or sunset, I see that Fenix Nightly changes theme correctly when I switch to Fenix at first time. But after switching to another app and open link, then, the theme is back to unexpected theme. After that, unless I close the Fenix Nightly process, the wrong theme is kept.

I guess that Samsung device might behave differently at changing the theme automatically (I cannot reproduce this bug when I switch the system theme forcibly). And the market share of Samsung devices is too big. So, this bug might make a lot of Android users give up to use Fenix.

**Comment by wurstsemmel** [comment] 2020-11-23 12:07
With Firefox Browser 83.1.0 the behaviour now is more close to what @masayuki-nakano describes.

The theme switches correctly from dark to light after sunrise, but it returns to dark after a while when doing different things with the phone.

**Comment by performation9** [comment] 2021-01-11 17:31
I can confirm this issue. Switching back from dark to light theme works as expected in the morning, after some time it automatically switches back to dark mode. Simply force closing the app does not revert back to light mode! Manually switching the theme does work as expected.
I can reproduce the issue consistently on several Samsung devices running OneUI 2.5 and 2.0, it happens in the latest nightly version as well. Would be happy to help debug this issue, this is kind of annoying. Other browser and all other apps on my phone do not have this problem, so it has to be something in the way Firefox checks for dark mode.

**Comment by performation9** [comment] 2021-01-18 09:25
Got an update to OneUI 3.0. The issue still exists there. Since no other app has this issue it seems to be something wrong with firefox.

**Closed** 2021-07-24 11:24 UTC
Labels: Feature:Themes, wontfix, 🐞 bug
