### ISSUE TITLE
[Bug] Fenix doesn't get listed as an option to open html files

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#3864] opened 2019-07-03 08:05 UTC
## Steps to reproduce

Try to open an html file on android, from an email attachment for example.

### Expected behavior

Fenix can be used to view the attachment and is listed, since it's my default browser.

### Actual behavior

Fenix is not listed and i cannot view the attachment for it.

### Device information

* Android device: Galaxy A20
* Fenix version: 1.0.1926 (Build #11790618 🦎 68.0-20190612114833) AC: 2.0.0

![Screenshot_20190703-095643_Android System](https://user-images.githubusercontent.com/1323194/60574573-1414f700-9d7a-11e9-946b-5e3dc3646652.jpg)

**Comment by nahuhh** [comment] 2019-07-06 00:32
Confirmed on BlackBerry KeyOne 8.1.0

**Comment by KaairaGupta** [comment] 2020-01-20 16:18
@boek may i be assigned this? And can you please tell me a bit as to how I should start solving this problem? which files i should look at?

**Comment by kbrosnan** [comment] 2020-01-20 20:33
Closing as a dupe #7546

**Closed by kbrosnan** 2020-01-20 20:33 UTC
Labels: Feature:AndroidIntegration, P2, help wanted, 🐞 bug
