### ISSUE TITLE
[Bug] mailto urls don't work

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#6231] opened 2019-10-23 23:39 UTC
## Steps to reproduce
Click on a mailto url, e.g. the "let us know" link at the bottom of [this blog post](https://blog.mozilla.org/addons/2019/10/23/fx-preview-geckoview-add-ons-support/)

### Expected behavior
Email app is opened, as it is in Fennec

### Actual behavior
"protocol not supported" error page from Fenix

### Device information

* Android device: Sony Xperia XZ1C
* Fenix version: Nightly 191021 18:08 (Build #12941812)
📦: 18.0.0, ad4af6e34
🦎: 71.0a1-20191018095340

**Comment by anotherus3r** [comment] 2020-01-04 16:12
Can reproduce in Firefox Preview Nightly 200104 06:01 (Build #20040608) on Android 10 and Android 6.0

**Comment by boek** [comment] 2020-01-07 19:13
We should double check the `magnet` link regression with this and create an allowlist for common protocols

**Comment by kbrosnan** [comment] 2020-01-08 01:13
`mailto:` the magnet: issue is #7427

Enabling the `open link in app` setting should allow this to work in the meantime.

**Comment by karlcow** [comment] 2020-03-29 23:11
Another webcompat issue related to this, happening for mailto and sms
https://github.com/webcompat/web-bugs/issues/50799

```js
  h.yA = function() {
    var a = this.Ga();
    if (gN(a)) {
      var b = hN(a);
      a = a.V().g.getName();
      b = Nh(Ph("mailto:"), "body", null != a ? a + " - " + b : b);
      window.open(b.toString(), "_self");
    }
  };
  h.AA = function() {
    var a = this.Ga();
    if (gN(a)) {
      var b = hN(a);
      a = a.V().g.getName();
      b = Nh(Ph("sms:"), "body", null != a ? a + " - " + b : b).toString();
      af && (b = b.replace(/^sms:\?/, "sms:&"));
      window.open(b, "_self");
    }
  };
```

**Comment by rocketsroger** [comment] 2020-04-20 21:50
After investigation.  Looks like `onPageStart` is now called before `onLoadRequest`.  Issue created for GeckoView.

**Comment by rocketsroger** [comment] 2020-04-20 21:51
After some discussion.  GeckoView's team's recommendation is not to use `onPageStart` to update the current loaded URL.  Android Component should update current URL in  `onLocationChanged`

**Comment by rocketsroger** [comment] 2020-04-20 21:56
Android component issue created: https://github.com/mozilla-mobile/android-components/issues/6720

**Comment by rocketsroger** [comment] 2020-04-22 20:03
Confirmed on latest nightly Fenix with Android Component version `39.0.20200422145552` this is fixed.  Adding QA to confirm.

**Comment by abodea** [comment] 2020-04-23 11:12
Verified as fixed on Nightly 4/23 with Google Pixel 4 XL (10).
Note that everything works as expected and the email app is opened.

**Closed by abodea** 2020-04-23 11:12 UTC
Labels: Feature:OpenInApp, P2, eng:qa:needed, 🐞 bug

**Comment by Dimas-sc** [comment] 2020-04-27 12:09
Tried with Firefox Preview (Nightly) 4/24 (39.0.20200424130104) and it don't work

**Comment by Dimas-sc** [comment] 2020-05-02 14:27
Tested with Firefox Preview (Nightly) 200502 (40.0.20200430224518) and it don't work. Are you sure it's fixed?

You can try going to "contacte" mailto: link at the top left part of the webpage:
![imatge](https://user-images.githubusercontent.com/2415679/80866962-da5e9680-8c91-11ea-8ab3-28b6a162cd9d.png)
