### ISSUE TITLE
[Bug] Once we removed the tracking protection for a site, it's not possible to put it back

### ISSUE THREAD

**Issue by julienw** [mozilla-mobile/fenix#5481] opened 2019-09-23 09:27 UTC
## Steps to reproduce
1. remove tracking protection on a website (clicking on the shield in the address bar).

### Expected behavior
* It's possible to add it back by clicking on something in the same area.
(old Firefox has a stroke-out shield for example)

### Actual behavior
* Nothing is displayed beside the lock for HTTPS.

### Device information

* Android device: samsung s10e, android 9
* Fenix version: nightly 190919 (build 12621820)

### Additional notes

It's common that I disable tracking protection temporarily on some websites:
* when there's a reporting live stream with links to tweets, I disable it so that I can see them inline, but then put tracking protection back on when I'm finished with this
* when something doesn't work and I want to check this is the reason (or not)

**Comment by softvision-miralobontiu** [comment] 2019-09-23 10:13
Dupe of #5446

**Closed by softvision-miralobontiu** 2019-09-23 10:13 UTC
Labels: 🐞 bug
