### ISSUE TITLE
[Bug] Media playback notification remains after media has stopped

### ISSUE THREAD

**Issue by jrmuizel** [mozilla-mobile/fenix#6454] opened 2019-11-05 14:26 UTC
I currently have a Netflix Canada media notification from Fenix even though I don't have Netflix loaded in any tabs.

I can reproduce the problem by loading netflix and while it's loading loading another page like a google search. 

* Android device: Pixel 10 Android 10
* Fenix version: Nightly 11/05

**Comment by jonalmeida** [comment] 2019-12-02 18:21
I have STR for the same effect, that might be related: https://github.com/mozilla-mobile/reference-browser/issues/942

**Comment by Amejia481** [comment] 2020-01-09 16:17
On Netflix I'm not able to play anything, as every title I tap, I get an **Unknown protocol error**. I'm trying to reproduce it on twitter.

**Comment by jonalmeida** [comment] 2020-01-09 17:57
> On Netflix I'm not able to play anything, as every title I tap, I get an **Unknown protocol error**. I'm trying to reproduce it on twitter.

We don't support [EME](https://wiki.mozilla.org/Media/EME) on mobile which Netflix needs for video playback.

**Comment by Amejia481** [comment] 2020-01-10 12:47
In some sites,  like **Youtube** as soon as the URL changes (even in the same domain) or the back button is pressed the notification disappears right away. But in other sites like **Twitter** or **Instagram** the notification persists until we change to a new domain.  

I believe what makes this behavior change from site to site is [onPlaybackStateChange](https://github.com/mozilla-mobile/android-components/blob/7659534d26e3f0065c6df193c52194279943b606/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/media/GeckoMedia.kt#L49 ) 

But still I haven't encountered a situation where the notification gets stuck. Just the no standard behavior per site.

**Comment by jonalmeida** [comment] 2020-01-10 15:39
@Amejia481 @jrmuizel do these STRs work to reproduce the issue? https://github.com/mozilla-mobile/reference-browser/issues/942

> ### Steps to reproduce
> 1. Go to twitter and find a thread that has a gif or auto-playing video in it.
> 1. **From the main twitter feed**, go to twitter thread.
> 2. Observe the media notification show up.
> 3. Press back to return to your twitter feed.
> 4. Observe the notification tray.
> 
> ### Expected behavior
> - At 5, the notification should be gone when leaving thread thread.
> 
> ### Actual behavior
> - The media notification persists in the playing state and cannot be removed until force closing the app.
>

**Comment by Amejia481** [comment] 2020-01-10 19:19
@jonalmeida I can partially reproduce the issue because the notification, persists while I'm on any Twitter's page but as soon as I navigate to another website the notification go away, the same happens with Instagram, but not with youtube

**Comment by andreasbovens** [comment] 2020-04-02 16:13
I think the frustrating part is that the notification cannot be dismissed even after pausing the video. 

Example:
1. Go to https://m.standaard.be/cnt/dmf20200402_04910902
2. Turn off Enhanced Tracking Protection (for some reason, this blocks the video on this particular site)
3. Play video. Media notification is shown in the notification area.
4. Press pause on the video player or media notification.

The media notification is "stuck" and cannot be dismissed. This behavior is different from Chrome, where it can be dismissed.

**Comment by rocketsroger** [comment] 2020-04-21 20:20
related https://bugzilla.mozilla.org/show_bug.cgi?id=1631907.  Will investigate/retest this issue after GeckView fix is in.

**Comment by liuche** [comment] 2020-10-17 00:25
Since the GV team needs priorities, we should add `fenix:p1` label to the whiteboard so GV knows this is prioritized. (`fenix:p2` is another option, but I'm going to go with P1 since this has been around for a while, and we're prioritizing Media this quarter)

**Comment by liuche** [comment] 2020-10-17 00:28
Oh wait, reading through that bug, Agi suggests that we do the following:

> Sorry I should've clarified. You need to use the new API for this to work (and in my local testing it does work).
> Start here: https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/MediaSession.html

So this is not blocked I believe, and I'll remove the waiting label.

**Comment by rocketsroger** [comment] 2020-12-07 15:51
Not reproducible with the new `MediaSession` API.  Put back to backlog till the new `MediaSession` API is integrated in Fenix.

**Comment by rocketsroger** [comment] 2020-12-08 16:32
With https://github.com/mozilla-mobile/fenix/pull/16909.  This should be fixed in Dec 9th nightly.

**Comment by rocketsroger** [comment] 2020-12-08 16:47
Please verify.   Thanks,

**Comment by softvision-miralobontiu** [comment] 2020-12-10 09:20
Hi all!
I've verified the twitter scenario, and after tapping back from the thread, the notification is dismissed. 

And also, verified 

> 1. Go to https://m.standaard.be/cnt/dmf20200402_04910902
> 2. Turn off Enhanced Tracking Protection (for some reason, this blocks the video on this particular site)
> 3. Play video. Media notification is shown in the notification area.
> 4. Press pause on the video player or media notification.
> 5. Try to dismiss the notification.
> 
> The media notification is "stuck" and cannot be dismissed. This behavior is different from Chrome, where it can be dismissed.

the media notification can be dismissed after pausing the video.

Tested on 12/10 Firefox Nightly build, with Samsung Galaxy Tab S6 (Android 10), OnePlus 5T (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).

**Closed by softvision-miralobontiu** 2020-12-10 09:20 UTC
Labels: Feature:Media, P2, S2, eng:qa:needed, 🐞 bug
