### ISSUE TITLE
mozilla Firefox address bar

### ISSUE THREAD

**Issue by brentd-nz** [mozilla-mobile/fenix#13338] opened 2020-08-06 09:57 UTC
There needs to be an option to fix the address bar in one place. The way it currently auto hides makes the screen move around and it's hard to activate the area of the touchscreen that I want, I keep touching the wrong things because the screen content has moved.

**Comment by hwinnemoe** [comment] 2020-08-06 11:28
Duplicate of #10240.

**Closed** 2020-08-06 19:56 UTC
Labels: needs:triage
