### ISSUE TITLE
[Bug]: Awesomebar autocomplete does not use history results

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26687] opened 2022-08-29 12:05 UTC
### Steps to reproduce

- Have the autocomplete feature enabled in settings
- Have a history of accessed websites
- Start typing the beginning of previously accessed domains 

### Expected behaviour

Get a suggestion from a matching history entry.

### Actual behaviour

Get a suggestion for a domain from the list of the most visited websites.

### Firefox version

104

### Additional information

More details and reports are available in https://github.com/mozilla-mobile/fenix/issues/26145

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21411)

**Comment by Mugurell** [comment] 2022-08-29 12:12
Thank you for the reports @aphedges, @notartom, @NoraCodes 
Just as a quick test to help narrow down the issue, can you please go to app settings -> Search -> Address bar, toggle off everything but "Autocomplete URLs" and report back on whether the issue still reproduces or not?

**Comment by NoraCodes** [comment] 2022-08-29 13:04
> Just as a quick test to help narrow down the issue, can you please go to app settings -> Search -> Address bar, toggle off everything but "Autocomplete URLs" and report back on whether the issue still reproduces or not?

Yes, the issue still occurs with only Autocomplete URLs on.

**Comment by aphedges** [comment] 2022-08-29 13:27
> Just as a quick test to help narrow down the issue, can you please go to app settings -> Search -> Address bar, toggle off everything but "Autocomplete URLs" and report back on whether the issue still reproduces or not?

I only have "Autocomplete URLs", "Search browsing history", and "Search bookmarks" enabled. When I disable the latter two, it turns from an intermittent bug to always failing to autocomplete from my history/bookmarks.

**Comment by notartom** [comment] 2022-08-29 13:35
So if I have everything turned off under Settings -> Search -> Address Bar, I get no autocomplete whatsoever (IOW, type 'n', then 'e' then 'w', and the address bar just says 'new').

If I turn on _just_ 'Autocomplete URLs', typing 'n' suggests netflix.com, 'e' stays with netflix.com, 'w' changes that to newegg.com, 's' removes the autocomplete suggestion and leaves just 'news' in the address bar. Note that I don't have netflix.com or newegg.com in my history.

If I then turn on 'Search browsing history' as well, typing 'n' suggests netflix.com, 'e' stays with netflix.com, 'w' changes that to newegg.com, 's' finally suggests news.ycombinator.com, which I _do_ have in my history, and is what I wanted in the first place.

However, this behaviour doesn't appear to be 100% deterministic. I can't figure out an exact set to steps to trigger it, and I'd say that it happens in about 70% of the time? For example, when attempting to reproduce the issue for this post, 'new' would sometimes suggest news.ycombinator.com and not newegg.com. Similarly, once I'd "reached" news.ycombinator.com in the autocompelte suggestion, going back and typing just 'n' would give me news.ycombinator.com roughtly 50% of the time, the other 50% being netflix.com.

**Comment by Mugurell** [comment] 2022-08-29 13:44
Thank you!
I think I have a direction for fixing this and agree that the resulting issue would only show intermittently.

**Comment by Flying-Miko** [comment] 2022-08-31 09:48
I seems to have issue with something similar. Not with Awesomebar, but with the address bar. I used to get a bunch of different suggeestiosn on sites I have previous visited, even the ones I havent bookmarked. Now its at most only 2, not counting the bookmarked ones.

**Comment by Mugurell** [comment] 2022-08-31 11:59
@aphedges, @notartom, @NoraCodes 
A speculative fix is available in the latest Nightly - 106.0.a1 (Build #2015901291)
Can you try to test whether the reported problem is fixed for you also?

**Comment by Flying-Miko** [comment] 2022-08-31 12:51
> 

How long does it takes for the fixed to go live on the "regular" firefox?

**Comment by Mugurell** [comment] 2022-08-31 14:24
> How long does it takes for the fixed to go live on the "regular" firefox?

If we trust the fix to work and not cause other issues it could be part of a dot release in the next days.

**Comment by Mugurell** [comment] 2022-09-02 06:18
For 105, this will be in the Fenix 105.0b4 build.

**Comment by SoftVision-LorandJanos** [comment] 2022-09-05 10:50
Verified as fixed on the latest Nightly 106.0a1 (2022-09-05) and latest Beta (105.0b5).
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.

**Closed by SoftVision-LorandJanos** 2022-09-05 10:50 UTC
Labels: 🐞 bug, Feature:History, eng:qa:needed, Feature:Search, regression

**Comment by Mugurell** [comment] 2022-09-09 14:52
Fix should also be available in the next Release - 104.2.0.

**Comment by aphedges** [comment] 2022-09-09 19:48
I have updated to 104.2.0, and I can confirm the problem is fixed for me. Thank you very much!

**Comment by Flying-Miko** [comment] 2022-09-10 11:39
> I have updated to 104.2.0, and I can confirm the problem is fixed for me. Thank you very much!

How do you update? I have checked both the browser and the play store and there is no option for me.

**Comment by rvandermeulen** [comment] 2022-09-10 11:42
It's on a gradual rollout at the moment. We expect it to be made fully
available on Monday.

**Comment by rommeswi** [comment] 2022-11-23 08:56
This problem persists in 107.1 (Build #2015915067) on a Z Flip 3.  I keep getting facebook.com suggested after typing 'f' even though I have for example firefox.com and other websites starting with 'f' in my history.

**Comment by Mugurell** [comment] 2022-11-23 10:05
> This problem persists in 107.1 (Build #2015915067) on a Z Flip 3. I keep getting facebook.com suggested after typing 'f' even though I have for example firefox.com and other websites starting with 'f' in my history.

The above scenario seems probable.
Currently there are two sources for autocomplete: history and suggested domains and we'll show the first result from any source.

**Comment by SoftVision-LorandJanos** [comment] 2022-11-23 11:59
> This problem persists in 107.1 (Build #2015915067) on a Z Flip 3. I keep getting facebook.com suggested after typing 'f' even though I have for example firefox.com and other websites starting with 'f' in my history.

I tried reproducing the issue on the same build after clearing my data , and I couldn't reproduce it. facebook.com was only suggested before I got firefox.com in history.


https://user-images.githubusercontent.com/48829350/203541506-4e05b966-55aa-4382-b6aa-b115fdcbe278.mp4
