### ISSUE TITLE
[Bug]Mute/Unmute a video displays a white/grey rectangle over the volume bar

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4375] opened 2019-07-30 11:58 UTC
## Steps to reproduce
1. Navigate to https://www.formula1.com/en/video.html
2. Play any video
3. Tap on the video player volume button 
4. Tap again on the video player volume button (to mute the video)

### Expected behavior
The volume button works properly and user has access to the volume control bar

### Actual behavior
When tapping the volume button a white rectangle show up over the volume control bar
When tapping the volume button (to mute the video) a grey rectangle show up over the volume control bar

### Device information

* Android device: 
Google Pixel 3a (Android 9)

* Fenix version: Nightly Build #12110609 from 30/7

#### Notes
►[Video](https://drive.google.com/open?id=1ViF4jF2-5iHD8T5wUnmO83fDa9R5nYE6)

**Comment by ekager** [comment] 2020-04-11 00:32
Just retested and could not reproduce this on my device on this site. QA could we verify this is working properly on your devices? Thanks!

**Comment by AndiAJ** [comment] 2020-04-13 06:08
Hi, **still reproducible** on my Nightly debug **`Build #21040820 39.0.20200410130104, 464e3038d
GV: 77.0a1-20200409095500 AS: 0.55.0 from Monday 4/13`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video Fenix
![20200413-090242](https://user-images.githubusercontent.com/51314259/79096524-1d4dde00-7d66-11ea-92e0-b87b7526f929.gif)

► Video Chrome
![20200413-090345](https://user-images.githubusercontent.com/51314259/79096577-3eaeca00-7d66-11ea-80e9-85263e332c23.gif)

**Comment by ekager** [comment] 2020-04-14 16:26
Ah I understand now, the volume bar works, it's just a visual thing. I can also reproduce in Fennec.

**Comment by ekager** [comment] 2020-04-14 16:52
Filed in Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1629972

**Comment by fluffyemily** [comment] 2020-05-19 14:34
The Media team commented on the bugzilla issue at https://bugzilla.mozilla.org/show_bug.cgi?id=1629972#c1 saying that they believe this to be a Fenix problem, not a Gecko one. I see here that it is also reproducible in Fennec. I've requested more information from the Media team, but someone from Fenix might want to weigh in here somewhere.

**Comment by ekager** [comment] 2020-12-17 00:48
Bug closed as won't fix.

**Closed by ekager** 2020-12-17 00:48 UTC
Labels: Feature:Media, P2, b:webcompat, needs:gecko, 🐞 bug
