### ISSUE TITLE
[Bug] Fenix crashes when trying to login on a website 

### ISSUE THREAD

**Issue by xscd** [mozilla-mobile/fenix#7625] opened 2020-01-12 12:38 UTC
## Steps to reproduce
1-Visit eksisozluk.com
2-Try to login
### Expected behavior
Successfully login to the website
### Actual behavior
Fenix crashes 
### Device information
Samsung Galaxy S8+ 
**Android version:**
9.0
**Fenix version:**
Nightly 200112 06:01 (Build #20120607)
28.0.0, d30f96fcd
GV: 74.0a1-20200110095023

Log:
```


FATAL EXCEPTION: main
Process: org.mozilla.fenix.nightly, PID: 18377
kotlin.NotImplementedError: Unable to validate saved logins. Are you using the correct class mozilla.components.concept.storage.NoopLoginValidationDelegate (Kotlin reflection is not available)?
	at mozilla.components.feature.prompts.dialog.LoginDialogFragment$update$1.invokeSuspend(LoginDialogFragment.kt:29)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)


```

**Comment by sv-ohorvath** [comment] 2020-01-13 09:46
See also: https://github.com/mozilla-mobile/fenix/issues/7637

**Comment by softvision-sergiulogigan** [comment] 2020-01-13 10:04
Also reproducible when trying to sign into https://accounts.fitbit.com/login

**Comment by nos1609** [comment] 2020-01-13 10:25
Temporary workaround:
about:config
signon.rememberSignons false

**Comment by softvision-oana-arbuzov** [comment] 2020-01-13 15:59
Also reproducible on https://www.hulu.com/start?platform=android

**Comment by Baron-Severin** [comment] 2020-01-13 23:22
QA note: this was fixed in AC, but will not be testable in Fenix until we have a build using the new snapshot.

**Comment by sv-sdeiac** [comment] 2020-01-16 09:18
Hello, I was unable to reproduce this issue using the latest version of Firefox Preview Nightly (1/16 build #20160806) on the following devices:
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8.0);
- Samsung Galaxy S7 Edge (Android 8.0.0)
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel (Android Q).

Due to that, I'll close this issue, thanks.

**Closed by sv-sdeiac** 2020-01-16 09:18 UTC
Labels: Feature:Logins, b:crash, eng:qa:needed, needs:ac, 🐞 bug
