### ISSUE TITLE
[Bug] Can't sync or change sync checkboxes, "Choose what to sync" view does not match Sync servers

### ISSUE THREAD

**Issue by moztcampbell** [mozilla-mobile/fenix#9027] opened 2020-03-06 15:22 UTC
## Steps to reproduce

1) Disable syncing of things like History on desktop
2) Use https://addons.mozilla.org/en-US/firefox/addon/about-sync/ to verify there is no History table
3) On fenix, visit sync settings and look at what is shared

### Expected behavior

The "History" box is unchecked.

### Actual behavior

The box is checked and unchecking it will result in it re-enabling a second later automatically.

### Device information

* Android device: Pixel 3 / Android 10
* Fenix version: Firefox Preview Nightly (20200304084140)

**Comment by ekager** [comment] 2020-03-10 21:33
Looked into this with @grigoryk and it seems to be a regression from updating to AS53 here: https://github.com/mozilla-mobile/android-components/pull/6110

If we need to cut this week, we will need to ask for a pinned AC version with a downgrade to AS52. (Should be possible because doesn't look like there were any breaking API changes)

**Comment by grigoryk** [comment] 2020-03-11 06:27
Tracking a fix in https://github.com/mozilla/application-services/issues/2791

**Comment by Diana-Rus** [comment] 2020-03-13 12:16
Hi, the following scenario has been checked:
Pre-requisites:
- Created a new account on Firefox Desktop RC 74.0 that did not sync History and Bookmarks

Scenarios:
1. Connected with the new account to mobile device and inspect in "Account Settings" whether the "Bookmarks" and "History" options are not checked.
2. Same account from Scenario 1 - Manually made a sync on desktop and on mobile - On mobile in section "Choose what to Sync" the unchecked options from pre-requisites are correctly updated.
3. Existent Account - Removed the History and Bookmark on desktop made a manually sync in order to have the options saved in the same state and connected with mobile - the options are correctly displayed.

Desktop Screen - Firefox 74.0:
![Firefox RC](https://user-images.githubusercontent.com/49859863/76616841-9e2e7580-652d-11ea-9298-d6103f7ca103.PNG)

Mobile GIF - Firefox Preview Beta 4.1.0-beta.2
![20200313-131031](https://user-images.githubusercontent.com/49859863/76617464-00d44100-652f-11ea-8864-93e2b16c50f4.gif)

Note:
- Provide a combined summary file for first scenario though about:sync option from section "Log Files and Diagnostics"  -> 
[aboutsync-combined-log.txt](https://github.com/mozilla-mobile/fenix/files/4329258/aboutsync-combined-log.txt)
* In the logs it seems that it has been recognised that the option are not enabled/checked:  FirefoxAccounts	DEBUG	Received declined engines: ["bookmarks","history"]
- For Scenario 1 - eventhough I manually made a sync the options haven't been updated with what has been selected at account creation through desktop.
- What i notice that when doing a manual sync on both mobile and desktop, the options are updated accordingly.

Builds:
- Firefox Preview Beta 4.1.0-beta.2 (Build #20730532) GV: 75.0-20200309155231.
- Firefox Preview Nightly 200313 (Build #20730607) GV: 76.0a1-20200312093312

Devices: Samsung Galaxy S8+ (Android 8)

@grigoryk, @ekager  - Could you please have a look and check the scenarios, and outcome?

**Comment by st3fan** [comment] 2020-06-29 20:30
@grigoryk is this bug still relevant? Should this be a release blocker?

**Comment by grigoryk** [comment] 2020-06-29 22:46
We fixed a number of related issues, so this should be resolved. @Diana-Rus could you please retest with recent builds?

**Comment by ebalazs-sv** [comment] 2020-06-30 13:22
We had tested this issue on the Fenix Beta 79.0.0-beta.1 GV 79 from 6/30 with the following devices:
- Motorola Moto G6 (Android 8);
- OnePlus 6T (Android 9);
- Huawei MediaPad M3 lite (Android 7);

and all the scenarios from Diana's comment and from the bug description are not reproducible.
Due to that I will remove the qa:needed label and close this issue. Thanks!

**Closed by ebalazs-sv** 2020-06-30 13:22 UTC
Labels: 79ReleaseBlocker, Feature:Sync, Release Blocker, S1, a-s, eng:qa:needed, needs:triage, 🐞 bug
