### ISSUE TITLE
[Bug] Undo closing a private tab switches to the non-private tab screen

### ISSUE THREAD

**Issue by KazaHesto** [mozilla-mobile/fenix#19256] opened 2021-04-26 23:46 UTC
## Steps to reproduce

Open multiple private tabs
Open the tabs tray and swipe to close a private tab
Tap undo in the snack bar

### Expected behavior

Tab is reopened, tab tray stays on private tabs screen

### Actual behavior

Tab is reopened, tab tray switches to non-private tabs screen

### Device information

* Device vendor / model and Android version: Samsung S21 5G on Android 11
* Firefox for Android version: Nightly 210426 17:01 (Build #2015806923)

https://user-images.githubusercontent.com/19279387/116164521-317c3780-a73d-11eb-8c0f-b9e3e0c1d5af.mp4

**Comment by LaurentiuApahideanSV** [comment] 2021-04-29 09:22
I can confirm the issue is reproducible on Firefox Preview Nightly 4/29, the issue does not occur on Firefox Preview 88.1.2. I will set this issue as new.

### Devices used:
- OnePlus 6T (Android 9)
- Pixel 3 XL (Android 9)

**Comment by Nickoriginal** [comment] 2021-07-13 10:38
_Fixed_ in Firefox 90.1.1 and 90.0.0-beta.6 for **Samsung Galaxy A20s** (Android 10) and **Samsung Galaxy J2 Prime** (Android 6.0.1).
_Not reproducible_ in Nightly 91.0a1 2021-07-12T17:08:00.346.

**Comment by SoftVision-LorandJanos** [comment] 2022-01-12 16:12
This issue is no longer reproducible on the latest Nightly (2022-01-12).
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-01-12 16:12 UTC
Labels: 🐞 bug, Feature:PrivateBrowsing, wontfix, qa-triaged
