### ISSUE TITLE
[Bug] Pinch to zoom keeps hiding and showing the address bar.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2278] opened 2019-05-04 02:03 UTC
## Steps to reproduce
You can try this on Bing's homepage, or on the demo on the following page:
https://davidwalsh.name/zoom-mobile-browsers
Just try to use pinch to zoom.

## Expected behavior
Pinch to zoom, when the page doesn't scroll, doesn't trigger the address bar (This is how Chrome behaves, just in case)

### Actual behavior
Pinch to zoom trigger the address bar, even if the page doesn't scroll.

### Device information
* Android device: Galaxy A5 2017
* Fenix version: 1.0.1918

It's like Fenix is detecting multi-touch gestures as a scrolling behavior, which is weird, because trying to scroll with two fingers on Bing's homepage, just doesn't work (it does work on Chrome though).

**Comment by ekager** [comment] 2019-05-05 18:27
Similar to #1506 . I opened https://github.com/mozilla-mobile/android-components/issues/2930 in AC

**Comment by vesta0** [comment] 2019-05-14 05:22
Will need to test again once the A-C bug is fixed.

**Comment by sblatz** [comment] 2020-03-30 17:24
Closing as we'll cover this in #2695

**Comment by Mugurell** [comment] 2020-04-07 16:03
I think this is a separate issue than the one from https://github.com/mozilla-mobile/android-components/issues/2695 and it actually stems from the fact that we don't have a clear way of knowing if the panning gesture was used for scrolling or for zooming. We treat both the same.

Based on the above the A-C ticket which would resolve this would actually be https://github.com/mozilla-mobile/android-components/issues/2930

**Comment by Mugurell** [comment] 2020-04-08 07:58
Reopening this based on the above comment with work to be done in A-C to ignore zoom gestures for animating the nav bar.

**Comment by Mugurell** [comment] 2020-05-12 13:40
The patch for mozilla-mobile/android-components#2930 was merged in A-C.
As soon as we have the new A-C merged in Fenix we can verify this does not reproduce anymore.

**Comment by Mugurell** [comment] 2020-05-14 09:25
After https://bugzilla.mozilla.org/show_bug.cgi?id=1627737  and https://github.com/mozilla-mobile/android-components/issues/2930 this should not reproduce anymore.
Please help verify.

**Comment by AndiAJ** [comment] 2020-05-15 07:27
Hi, **still reproducible while using the Dynamic Top toolbar** on the latest Nightly Build 200515 from 5/15 using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

✔️ Works properly while having the Dynamic toolbar set to Bottom 

► Video Fenix
![20200515-102332](https://user-images.githubusercontent.com/51314259/82023209-95c1fa80-9696-11ea-8443-266559f0d7da.gif)

**Comment by Mugurell** [comment] 2020-05-15 07:31
Thank you Andi!
Seems there is still a bit of work left to properly support the top address bar.

**Comment by Mugurell** [comment] 2020-05-15 15:50
There seems to be more issues with the top address bar for which I've created https://github.com/mozilla-mobile/fenix/issues/10686, this being one of them.

Ticket should remain open until the issue is fixed for the top address bar also.

**Comment by Mugurell** [comment] 2020-05-28 13:12
Moving this to `waiting` because of https://github.com/mozilla-mobile/fenix/issues/10686

**Closed** 2021-03-01 05:46 UTC
Labels: P2, needs:ac, wontfix, 🐞 bug, 🙅 waiting
