### ISSUE TITLE
FNX2-15078 ⁃ [Bug]Crash [@ android.view.ViewRootImpl$CalledFromWrongThreadException: at android.view.ViewRootImpl.checkThread(ViewRootImpl.java) ]

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12201] opened 2020-07-02 14:25 UTC
## Prerequisites
Fresh install of Fenix
Sign in on both Fenix and Desktop
Exit to Fenix's home screen

## Steps to reproduce
1. Change the password on Desktop 
1. From Fenix's home screen tap the ⋮ Main menu and Synced tabs

### Expected behavior
Synced Tabs section should be displayed with the message "Connect with a Firefox Account"

### Actual behavior
Crash

### Device information
* Android device: 
• OnePlus A3 (Android 6.0.1)
• Samsung Galaxy Tab A6 (Android 5.1)
* Fenix version: Beta 79.0.0-beta.4 from 7/1

### Notes
❗ Not reproducible 100% of the times

Crash report: https://crash-stats.mozilla.org/report/index/35452efb-4b3f-457b-bb9e-af4080200702

► Video
![20200702-170438](https://user-images.githubusercontent.com/51314259/86370902-f201cd80-bc88-11ea-9926-1f7df716d846.gif)

**Comment by pocmo** [comment] 2020-07-02 15:14
```
[..]
at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:2)
at android.view.View.setFlags(View.java:10641)
at android.view.View.setVisibility(View.java:7467)
at org.mozilla.fenix.sync.SyncedTabsLayout.onError(SyncedTabsLayout.kt:4)
at mozilla.components.feature.syncedtabs.presenter.DefaultPresenter$SyncedTabsAccountObserver.onAuthenticationProblems(DefaultPresenter.kt:1)
at mozilla.components.service.fxa.manager.-$$LambdaGroup$ks$MFnwuDxQa-fCZoB6kc4cctAg3VA.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:3)
at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
at mozilla.components.service.fxa.manager.FxaAccountManager.notifyObservers(FxaAccountManager.kt)
at mozilla.components.service.fxa.manager.FxaAccountManager.stateActions(FxaAccountManager.kt:28)
at mozilla.components.service.fxa.manager.FxaAccountManager$stateActions$1.invokeSuspend(FxaAccountManager.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
```

**Comment by BranescuMihai** [comment] 2020-07-13 20:09
Seems like there is also a GV problem, there is a ~10 second window during which the Rust call for devices still returns all devices, even though we just changed the password on Desktop. Could be an intended backend architectural decision due to eventual consistency, but I created a bug anyway just to check (https://bugzilla.mozilla.org/show_bug.cgi?id=1652559).

So the current fix for this is that when you change the pass from desktop, if you check Synced tabs right away, there is a ~70% chance that you will see 'There are no tabs available'. If you wait 15-20 seconds before checking, you will see 'Please re-authenticate'

**Comment by Diana-Rus** [comment] 2020-07-22 12:37
Hi, verified as fixed, didn't reproduce the issue, no crash encountered, on Nightly 7/21 with Samsung Galaxy S9 (Android 8):
A) Received right after step 2, the following message: "You don't have any tabs opened on you other devices" and after a couple of seconds: "Please Re-authenticate" .
B) Received after a couple of seconds after step 2: "Please Re-authenticate"

<details><summary>Received messages</summary>

![Screenshot_20200722-150446_Firefox Nightly](https://user-images.githubusercontent.com/49859863/88174658-50d5b980-cc2d-11ea-87fa-ba7c00fee689.jpg)


![Screenshot_20200722-150512_Firefox Nightly](https://user-images.githubusercontent.com/49859863/88174662-53381380-cc2d-11ea-8e11-5ba8d0040883.jpg)
</details>

Note:
- Desktop Firefox Nightly version: 80.0a1 (2020-07-22) (64-bit)
- After re-authentication is made tabs are displayed

Should this string be displayed: "You don't have any tabs opened on you other devices" or should it be changed to "There are no tabs available"?

**Closed** 2020-08-12 17:18 UTC
Labels: E3, Feature:SyncTabs, S1, b:crash, eng:qa:verified, 🐞 bug
