### ISSUE TITLE
[Bug] tab page has massive logo

### ISSUE THREAD

**Issue by simonsteiner1984** [mozilla-mobile/fenix#8379] opened 2020-02-13 11:09 UTC
## Steps to reproduce
Open tab page

### Expected behavior
There shouldnt be a giant logo there, I already know what app im using

### Device information

* Android device: ?
* Fenix version: ?

**Comment by cadeyrn** [comment] 2020-02-13 11:18
Duplicate of #8275.

**Comment by abodea** [comment] 2020-02-13 12:50
Thank you for the report @simonsteiner1984.
Thanks @cadeyrn for the comment, I will close this issue based on the commend from above.
For more details please check #8275.

**Closed by abodea** 2020-02-13 12:50 UTC
Labels: needs:triage, 🐞 bug
