### ISSUE TITLE
FNX-11869 ⁃ [Bug] Receiving notifications from a website I didn't grant access to

### ISSUE THREAD

**Issue by vaindil** [mozilla-mobile/fenix#11012] opened 2020-05-28 21:51 UTC
## Bug
I started receiving notifications from a random website yesterday. Tapping the notification just opens the browser, nothing else.

I have never allowed notifications from any website on Nightly. `Settings > Site permissions > Exceptions` lists four sites for me, and all four of them show either "Blocked" or "Ask to allow" for notifications. The most recent notification at least seems to be from phys.org, but that site is not shown in my exceptions at all.

### Device information
* Android device: Pixel 2 XL
* Fenix version:

Nightly 200528 06:00 (Build #21490607)
44.0.20200527130120, b1ddaff6a
GV: 78.0a1-20200525093440
AS: 0.59.0

**Comment by TitanNano** [comment] 2020-05-28 21:57
Android Components issue: https://github.com/mozilla-mobile/android-components/issues/7161

**Comment by jonalmeida** [comment] 2020-05-29 00:09
This might be the root cause for the one @TitanNano linked above.

**Comment by TitanNano** [comment] 2020-05-30 09:52
With Fenix build `Nightly 200530 06:01 (Build #21510609) with AC 44.0.20200529205416` decent websites like Twitter are now able to let users unsubscribe from push. But subscriptions which no longer have permission, or never had, still do not obey their notification permission (see https://github.com/mozilla-mobile/android-components/issues/7161 for that). So as a workaround people could be able to get rid of unwanted existing push subscriptions by visiting the site and trying to unsubscribe through their UI.

**Comment by jonalmeida** [comment] 2020-05-30 20:11
Thanks for messaging here! I'm going to close this as fixed.

**Comment by liuche** [comment] 2020-06-29 21:00
Hi @sv-ohorvath, I know this is closed on Nightly, but could you do verification on the 79.0.0 beta build that is getting built tomorrow EUR time by sebastian? This is a bad enough use case that we want to make sure that it is absolutely not happening.

**Comment by liuche** [comment] 2020-06-29 23:24
(going to temporarily re-open this just so we can verify)

**Comment by sv-ohorvath** [comment] 2020-06-30 11:46
With the described STR (mainly from https://github.com/mozilla-mobile/fenix/issues/11033) I can confirm that the bug is fixed on Beta 79.0.1. Notification received on an *old* Nightly and nothing on this beta. Closing back this issue.

**Closed** 2020-08-11 02:37 UTC
Labels: 79ReleaseBlocker, Feature:Notifications, eng:qa:verified, needs:ac, 🐞 bug

**Comment by vaindil** [comment] 2020-08-11 04:11
Uh, everything okay?
