### ISSUE TITLE
[Bug]: Add logins dialog: save button is enabled when password field is blank

### ISSUE THREAD

**Issue by bendk** [mozilla-mobile/fenix#21414] opened 2021-09-21 17:18 UTC
### Steps to reproduce

- Open the add logins dialog
- Input a site and username, but not a password
- Click the save button

### Expected behaviour

The save button should be disabled

### Actual behaviour

The save button is enabled.  Clicking it closes the dialog, but no login is added.

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17953)

**Comment by SoftVision-LorandJanos** [comment] 2021-09-22 07:21
Hi @bendk! Thank you for your report.
I can confirm the issue is reproducible as described, with the following detail:
The checkmark is activated even after filling the Site field only (with valid data). So without any username or password.

Firefox versions tested:
- Nightly (94.0a1 - 2021-09-22).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Mi11 Lite (Android 11).

**Comment by SoftVision-LorandJanos** [comment] 2022-04-14 06:57
This issue is still reproducible on the latest Nightly 101.0a1 (2022-04-14) build.
Device used: Google Pixel 4 (Android 12).
Reopening the ticket.

**Comment by fice-t** [comment] 2022-11-14 23:39
PR that fixes this: #27430.

**Comment by SoftVision-LorandJanos** [comment] 2022-11-17 06:08
Verified as fixed on the latest Nightly 109.0a1 (2022-11-17) build.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-11-17 06:08 UTC
Labels: 🐞 bug, eng:qa:needed, S3, Feature:Logins, needs:triage, qa-triaged

**Comment by AdinaPetridean** [comment] 2022-12-15 07:57
Verified as fixed on the Firefox 109.0b1 (2022-12-15) build.
Device used: Poco M4 Pro (Android 12).
