### ISSUE TITLE
[Library] Deleting is inconsistent between history/bookmarks

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8648] opened 2020-02-21 17:57 UTC
1. Deleting one bookmark has different strings than group deleting bookmarks in the snackbar
2. Deleting all of history has confirmation pop-up and no snackbar
3. Deleting individual history items has no  confirmation pop-up or snackbar
4. Deleting individual bookmark from edit menu has confirmation pop-up and snackbar (location is too high on the screen)
5. Deleting a folder doesn't show confirmation pop-up, shows snackbar

@betsymi for strings @topotropic to confirm expected behaviour

**Comment by betsymi** [comment] 2020-03-02 19:19
@AmyYLee Can you help me track down these strings? Any screenshots available?

**Comment by AmyYLee** [comment] 2020-03-04 19:22
> @AmyYLee Can you help me track down these strings? Any screenshots available?

Spoke to @betsymi about strings and it's been resolved.

**Comment by betsymi** [comment] 2020-03-05 23:33
1. **Deleting bookmarks snackbars**
1 bookmark deleted: `Deleted [bookmark url] UNDO`
 2+ bookmarks deleted: `Bookmarks deleted UNDO`

1. **Deleting all history snackbar**
`Browsing data deleted`

3. **Deleting individual history item**
`Deleted [url]`

4. N/A for strings, keep as-is

5. **Deleting a folder**
`Are you sure you want to delete this folder?
CANCEL DELETE`

**Comment by BMEduard** [comment] 2020-04-15 09:31
Hello @betsymi, @AmyYLee. I have two questions regarding this issue:

1. Adding a confirmation pop-up for deleting individual history items will create a discrepancy since deleting individual browsing items (except folders) does not require a confirmation from the user. 
Should I still go ahead and add the confirmation pop-up or should this additional step be kept for more “impactful” actions such as deleting a bookmark folder or for deleting all the history?
2. What should the string message be for the snackbar when the user deletes multiple history items?

I also want to mention that while working on this issue I have also come across some other possible discrepancies which are listed in this new ticket: #9949 .

**Comment by AmyYLee** [comment] 2020-04-15 16:21
> Hello @betsymi, @AmyYLee. I have two questions regarding this issue:
> 
>     1. Adding a confirmation pop-up for deleting individual history items will create a discrepancy since deleting individual browsing items (except folders) does not require a confirmation from the user.
>        Should I still go ahead and add the confirmation pop-up or should this additional step be kept for more “impactful” actions such as deleting a bookmark folder or for deleting all the history?
> 
>     2. What should the string message be for the snackbar when the user deletes multiple history items?
> 
> 
> I also want to mention that while working on this issue I have also come across some other possible discrepancies which are listed in this new ticket: #9949 .

Hi @topotropic can you provide some guidance on the above? Thanks

**Comment by betsymi** [comment] 2020-04-16 14:26
@BMEduard Could you clarify what you mean by confirmation pop-up? We have snackbars (appear after) and confirmations dialogs (appear BEFORE the action is completed). 

I believe this conversation is about snackbars, but wanted to clarify before I make the recommendation so that we are using the same nomenclature.

**Comment by BMEduard** [comment] 2020-04-16 15:33
@betsymi By confirmation pop-up I mean the confirmation dialog that, as you said, appears before the action is completed.

**Comment by betsymi** [comment] 2020-04-16 16:40
> @betsymi By confirmation pop-up I mean the confirmation dialog that, as you said, appears before the action is completed.

Ah, glad I asked! No, we would **not** want a confirmation dialog if a user deletes an individual item in their history. Agree with your point, that an additional step be kept for more “impactful” actions such as deleting a bookmark folder or for deleting all the history.

> What should the string message be for the snackbar when the user deletes multiple history items?

`History deleted`

**Comment by ekager** [comment] 2020-04-29 16:49
Reopening for QA to verify the changes

**Comment by sv-sdeiac** [comment] 2020-05-05 08:06
Hi, I can confirm that those notification are now correctly displayed as in this [comment](https://github.com/mozilla-mobile/fenix/issues/8648#issuecomment-595498350). 

Build:
- Firefox Preview Nightly 5/4 #21251804.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG G7 fit (Android 8.1).

**Comment by vesta0** [comment] 2020-05-12 02:42
Can we close this issue?

**Comment by ekager** [comment] 2020-05-12 02:50
Yes! Closing

**Closed by ekager** 2020-05-12 02:50 UTC
Labels: P2, eng:qa:verified, implementation review, needs:triage
