### ISSUE TITLE
[Bug] Deleting bookmark folder doesn't work (and crashes)

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3693] opened 2019-06-26 21:03 UTC
I'm not sure if we're supposed to be able to delete bookmark folders right now, as long pressing on them does not display the edit mode.

That being said, once in edit mode (by long pressing on a real bookmark), a user is able to select and delete the bookmarks. Doing so causes a crash. See demo:

### Demo

![crash folder](https://user-images.githubusercontent.com/4400286/60214838-2a233480-981b-11e9-80ca-72442e078f97.gif)

### Stacktrace
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/4400286/60214760-f8aa6900-981a-11e9-9d2a-e406edd3cc67.png">

@colintheshots may have some insights on this

**Comment by ekager** [comment] 2019-07-16 17:28
Looks like I can still select a folder in multi-select mode and delete it, but it doesn't crash for me. @colintheshots is this expected behavior? If this is no longer crashing should we close this?

**Comment by ekager** [comment] 2019-08-06 22:00
Closing this because it doesn't crash anymore

**Closed by ekager** 2019-08-06 22:00 UTC
Labels: Feature:Bookmarks, P2, b:crash, 🐞 bug
