### ISSUE TITLE
[webcontent]

### ISSUE THREAD

**Issue by SinTan1729** [mozilla-mobile/fenix#14778] opened 2020-09-06 07:39 UTC
## Site with issue and any steps to reproduce
https://m.facebook.com/gel.07.04/posts/pcb.1028832890864302/

### Expected behavior
All images load properly.

### Actual behavior
Only the first few (8, in this case) images load.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes.

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No.

### Device information

* Android device: Redmi K20 (Android 10)
* Fenix version: Nightly 200906 06:01

**Comment by Diana-Rus** [comment] 2020-09-07 09:43
Hi, reproducing this on Nightly 9/7 with:
- Samsung Galaxy S9 (Android 8)
- Google Pixel 3XL (Android 9)

Note: Tried also on Chrome and after the page loads, with the first 8 images, the user is redirected to facebook log in page.

**Comment by Mugurell** [comment] 2021-02-03 18:50
Closing based on Diana's report - "Note: Tried also on Chrome and after the page loads, with the first 8 images, the user is redirected to facebook log in page."
This is the intended behavior, controlled by the website.

**Closed by Mugurell** 2021-02-03 18:50 UTC
Labels: Feature:Browsing, S2, b:web-content
