### ISSUE TITLE
basic print functionality

### ISSUE THREAD

**Issue by aaronwi** [mozilla-mobile/fenix#26254] opened 2022-07-30 04:16 UTC
all other android browsers have this, why is this extremely basic feature missing?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21156)

**Comment by anotherus3r** [comment] 2022-07-30 12:14
Duplicate of #10217

**Closed** 2022-07-31 05:04 UTC
Labels: needs:triage

**Comment by aaronwi** [comment] 2022-08-10 01:34
"@[kbrosnan](https://github.com/kbrosnan) kbrosnan closed this as [not planned](https://github.com/mozilla-mobile/fenix/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3A%22not+planned%22)
[10 days ago](https://github.com/mozilla-mobile/fenix/issues/26254#event-7095850619)"

so, after 3 years of "it's coming in the next release", now it's suddenly not planned at all?

**Comment by anotherus3r** [comment] 2022-08-10 13:02
> "@[kbrosnan](https://github.com/kbrosnan) kbrosnan closed this as [not planned](https://github.com/mozilla-mobile/fenix/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3A%22not+planned%22)
> [10 days ago](https://github.com/mozilla-mobile/fenix/issues/26254#event-7095850619)"
> 
> so, after 3 years of "it's coming in the next release", now it's suddenly not planned at all?

I think "not planned" is the default status when closing a duplicate issue. The other issue I mentioned is still open.

**Comment by cadeyrn** [comment] 2022-08-13 17:45
Nobody said "it's coming in the next release". But yes, it's as anotherus3r said. If you move the cursor over the "not planned" you can also see a tooltip saying that duplicates are one of the possible reasons for this message.
