### ISSUE TITLE
FNX-12621 ⁃ [Bug] Tab tray first touch isn't registered

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#11648] opened 2020-06-16 17:52 UTC
## Steps to reproduce
Have at least two apps
Switch one tab to another
Notice first touch not registered

### Expected behavior
Switches on first touch

### Actual behavior
Doesn't switch on first touch
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17825767/84809922-495e3780-b013-11ea-83fd-9ca40459c3c7.gif)

### Device information
* Android device: Xperia XZ1 Android 10
* Fenix version: 
Nightly 200615 06:01 (Build #21670608)
45.0.20200613130120, b4f036c83
GV: 79.0a1-20200612094620
AS: 60.0.0

**Comment by cadeyrn** [comment] 2020-06-16 17:55
Duplicate of #11558.

**Comment by ekager** [comment] 2020-06-16 17:55
Closing for  #11558

**Comment by hakkikaancaliskan** [comment] 2020-06-16 17:56
@ekager @cadeyrn waow, faaaast :)

**Closed** 2020-08-11 04:36 UTC
Labels: needs:triage, 🐞 bug
