### ISSUE TITLE
[Bug]: Search groups do not appear in the Recently visited section until they are closed.

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#22783] opened 2021-12-10 10:06 UTC
### Steps to reproduce

1. Search for a term using the preferred search engine;
2. Open several pages from the search result screen;
3. Visit the pages.
4. Go to the homepage.

### Expected behaviour

The search grouping should be displayed on the homepage.

### Actual behaviour

The search grouping is not displayed on the homepage until the tabs are closed.

### Device name

Oppo Find X3 Neo

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

2021-12-10

### Additional information

https://user-images.githubusercontent.com/50983519/145576492-eb11191f-1707-444e-bb76-756084bb0c9c.mp4

**Comment by amedyne** [comment] 2021-12-13 18:18
@LaurentiuApahideanSV Search term groupings will appear on Recently Visited, only after there is some activity/interaction with the opened tabs. @csadilek any other points to add?

**Comment by csadilek** [comment] 2021-12-14 04:24
@LaurentiuApahideanSV @amedyne Yes, also: A search group is only displayed under "Recently Visited" if it is NOT also displayed under "Jump Back In". The last active group is always displayed under "Jump Back In" which then isn't displayed under "Recently Visisted". That's by design, and very likely what you're seeing. Once you close the tabs, the tab group removes from "Jump Back In" and appears under "Recently Visisted".

See this ticket for details: https://github.com/mozilla-mobile/fenix/issues/22442

**Comment by csadilek** [comment] 2021-12-14 04:26
Yes, looking at the video, this is exactly what's happening. The test group is displayed under "Jump Back In" and is therefore not being displayed under "Recently Visited". So, I think this can be closed as "by design" :).

**Closed** 2021-12-14 15:13 UTC
Labels: 🐞 bug, Feature:SearchTermTabs, Feature:SearchGroupHistory
