### ISSUE TITLE
[Bug] Page links do not work

### ISSUE THREAD

**Issue by scander71** [mozilla-mobile/fenix#20447] opened 2021-07-21 03:45 UTC
I have issues with Firefox for Android.

Initially it works as it always has but after a period of time the hot links no longer work. When I click on them nothing happens. Also refreshing the tab does not reload the page.This started in the update before last and was not resolved with the latest release.

I am running 8.1.0 on Moto 5S

**Comment by Nickoriginal** [comment] 2021-07-21 05:57
> This started in the update before last and was not resolved with the latest release.

This started in 90.1.1 (before 90.1.2) or in 89.1.1 (before 90.1.1 and 90.1.2)?

**Comment by scander71** [comment] 2021-07-21 06:24
This started in 90.1.1 before 90.1.2

    On Wednesday, 21 July 2021, 3:57:45 pm AEST, Nickoriginal ***@***.***> wrote:  
 
 



This started in the update before last and was not resolved with the latest release.


This started in 90.1.1 (before 90.1.2) or in 89.1.1 (before 90.1.1 and 90.1.2)?

**Comment by cadeyrn** [comment] 2021-07-21 07:06
What are "hot links"?

**Comment by scander71** [comment] 2021-07-21 07:16
I call hot links the two embedded links on a webpage - the above two dot points. Please note this was captured on a pc not on my phone

    On Wednesday, 21 July 2021, 5:06:33 pm AEST, Sören Hentzschel ***@***.***> wrote:  
 
 


What are "hot links"?

**Comment by mcarare** [comment] 2021-07-21 12:07
@scander71 Not sure what you are referring to. Can you post a screenshot or video? Thank you!

**Comment by scander71** [comment] 2021-07-21 13:58
Can you not see the bbc screen shot I included in my last response ?

    On Wednesday, 21 July 2021, 10:07:44 pm AEST, Mihai Adrian Carare ***@***.***> wrote:  
 
 


@scander71 Not sure what you are referring to. Can you post a screenshot or video? Thank you!

**Comment by mcarare** [comment] 2021-07-21 14:08
@scander71 Please reply in the thread, not via email.

**Comment by scander71** [comment] 2021-07-21 14:18
Apologies - please find attached the screenshot

![thumbnail](https://user-images.githubusercontent.com/87743875/126504173-a2b00361-f27a-468f-bf56-dc051e323259.png)

**Comment by mcarare** [comment] 2021-07-21 14:34
@scander71 From the screenshot you posted this seems like a desktop issue. This Github repo is for the mobile version of Firefox.  
Nevertheless, I loaded the page in the mobile app and the two links ("Science failed... ") work for me.

**Comment by scander71** [comment] 2021-07-21 14:38
I was showing you an example of what I call a hot link and in my original email I stated that this capture was from a desktop not a mobile as it was quicker for me to send a response. I can generate  the same shot on my mobile but it was just trying to show you what I call a hot link which was the original question

**Comment by scander71** [comment] 2021-07-21 14:48
When I load the page initially the link works, after a few minutes it doesnt. Did you wait to load the link ? What Android version are you running on ?

**Comment by kbrosnan** [comment] 2021-07-21 17:29
Getting a profile of the hang may be useful. https://profiler.firefox.com/docs/#/./guide-remote-profiling

**Comment by lobontiumira** [comment] 2021-07-22 08:02
I was not able to reproduce this issue on the latest RC build 90.1.2, nor on the latest Nightly 92.0a1 build from 7/22, using a Google Pixel (Android 10), and a HTC 10 (Android 8).
@scander71 could you, pease, provide maybe some steps to reproduce? Did you have some addons enabled or some customed ETP settings?
Thank you!

I'll remove the qa:needed label for now.

**Comment by kbrosnan** [comment] 2021-08-09 21:33
Closing as incomplete. It can be reopened with a profile as mentioned in my previous comment.

**Closed by kbrosnan** 2021-08-09 21:33 UTC
Labels: 🐞 bug, Feature:Browsing, needs:triage, qa-triaged
