### ISSUE TITLE
[Bug] Downloaded .torrent files are not opened from firefox. Could not open file message is displayed. 

### ISSUE THREAD

**Issue by iamiceparticle** [mozilla-mobile/fenix#17502] opened 2021-01-16 14:38 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Visit website https://yts.one/movie/shubh-mangal-zyada-saavdhan-2020/ and download .torrent file

### Expected behavior
When .torrent file is opened from dowload notification flud app must open

### Actual behavior
Could not open file message is displayed. External download manager is set. It doesn't work even if external download manager is not set.
When open links in app is set it gives message no app fond to open files.
Flud app is installed in mobile.

### Device information
Samsung Galaxy A71

* Android device: Android 10 UI 2.5
* Fenix version: 85.0.0-beta.8 (Build #2015787403)

**Comment by Amejia481** [comment] 2021-02-07 18:01
@iamiceparticle  could you confirm is this still an issue, it should be fixed in nightly.

**Comment by iamiceparticle** [comment] 2021-02-08 13:53
> @iamiceparticle could you confirm is this still an issue, it should be fixed in nightly.

No it's not fixed in nightly also.
It gives error invalid file. @Amejia481 
![Uploading Screenshot_20210208-192021_Flud.jpg…]()

**Comment by Amejia481** [comment] 2021-02-08 14:53
Sorry, it looks like the image wasn't attached correctly, would you mind do it again?

**Comment by iamiceparticle** [comment] 2021-02-08 14:56
> Sorry, it looks like the image wasn't attached correctly, would you mind do it again?

![Screenshot_20210208-192021_Flud](https://user-images.githubusercontent.com/76210878/107236580-d85d0b80-6a4b-11eb-8ced-56ec77700e12.jpg)

**Comment by Amejia481** [comment] 2021-02-08 14:58
Go it, it opened the app but the app could handle the intent, we have to take another look

**Comment by Amejia481** [comment] 2021-02-08 14:58
Thanks for the fast response :)

**Comment by Amejia481** [comment] 2021-02-08 15:05
I was able to share with moto g with Android 7, with have to tests with Samsung and Android 10
![Screenshot_20210208-100203](https://user-images.githubusercontent.com/773158/107237694-02cfaa00-69f5-11eb-83fa-331ae4e01b8f.png)

**Comment by iamiceparticle** [comment] 2021-02-08 15:42
> I was able to share with moto g with Android 7, with have to tests with Samsung and Android 10
> ![Screenshot_20210208-100203](https://user-images.githubusercontent.com/773158/107237694-02cfaa00-69f5-11eb-83fa-331ae4e01b8f.png)

Ok. Thanks.

**Comment by abodea** [comment] 2021-02-10 07:44
Verified as fixed on the latest Nightly 10/2/2021 with Google Pixel 4 XL (11).
I downloaded a torrent file as is mentioned in the description and then I was able to open the file in a torrent download app.
Note that I was able to open the torrent with uTorrent and Flud apps.
@iamiceparticle please make sure you give permissions to the torrent app before trying to open anything from Fenix.

**Comment by iamiceparticle** [comment] 2021-02-10 08:02
> Verified as fixed on the latest Nightly 10/2/2021 with Google Pixel 4 XL (11).
> I downloaded a torrent file as is mentioned in the description and then I was able to open the file in a torrent download app.
> Note that I was able to open the torrent with uTorrent and Flud apps.
> @iamiceparticle please make sure you give permissions to the torrent app before trying to open anything from Fenix.

Hi thanks for the help but I am still facing the issue.
My Firefox nightly still cannot open torrent file.
And I noticed yesterday it is not able to open gif file also.

When I have clearly mentioned that I am using Samsung mobile you need to test it on Samsung mobile.

It seems to be specific to samsung One UI issue.
Anyway if you do not want users to use it on Samsung mobile, I can understand.

Anyway thanks for help. I have switched to samsung internet browser.
![Screenshot_20210210-132620_Permission controller](https://user-images.githubusercontent.com/76210878/107481488-44528780-6ba4-11eb-8930-8fcfe727ffb7.jpg)
![Screenshot_20210210-132648_Gallery](https://user-images.githubusercontent.com/76210878/107481515-503e4980-6ba4-11eb-8497-9ee641f0175f.jpg)

**Comment by abodea** [comment] 2021-02-10 08:05
> > Verified as fixed on the latest Nightly 10/2/2021 with Google Pixel 4 XL (11).
> > I downloaded a torrent file as is mentioned in the description and then I was able to open the file in a torrent download app.
> > Note that I was able to open the torrent with uTorrent and Flud apps.
> > @iamiceparticle please make sure you give permissions to the torrent app before trying to open anything from Fenix.
> 
> Hi thanks for the help but I am still facing the issue.
> My Firefox nightly still cannot open torrent file.
> And I noticed yesterday it is not able to open gif file also.
> 
> When I have clearly mentioned that I am using Samsung mobile you need to test it on Samsung mobile.
> 
> It seems to be specific to samsung One UI issue.
> Anyway if you do not want users to use it on Samsung mobile, I can understand.
> 
> Anyway thanks for help. I have switched to samsung internet browser.
> ![Screenshot_20210210-132620_Permission controller](https://user-images.githubusercontent.com/76210878/107481488-44528780-6ba4-11eb-8930-8fcfe727ffb7.jpg)
> ![Screenshot_20210210-132648_Gallery](https://user-images.githubusercontent.com/76210878/107481515-503e4980-6ba4-11eb-8497-9ee641f0175f.jpg)
> @abodea

Interesting, thank you for the response, I will re-open this bug now and I will test it on Samsung devices!

**Comment by iamiceparticle** [comment] 2021-02-10 11:07
Hi @abodea thanks for looking into it.
I tested both issue on my OPPO A9.

Both issue I could replicate on A9. I am not sure how it is working on Pixel 4.
OPPO A9 runs on Color OS 7.1 based on android 10.
Please find screenshot.
Torrent file and gif file failed to open with Firefox nightly.
![IMG-20210210-WA0000](https://user-images.githubusercontent.com/76210878/107502062-33167480-6bbe-11eb-8e5d-69e600708181.jpg)
![IMG-20210210-WA0002](https://user-images.githubusercontent.com/76210878/107502090-3f9acd00-6bbe-11eb-82b3-24268bab37c2.jpg)
![IMG-20210210-WA0001](https://user-images.githubusercontent.com/76210878/107502121-4a556200-6bbe-11eb-9aff-9063af2bb864.jpg)

**Comment by abodea** [comment] 2021-02-10 13:22
> Hi @abodea thanks for looking into it.
> I tested both issue on my OPPO A9.
> 
> Both issue I could replicate on A9. I am not sure how it is working on Pixel 4.
> OPPO A9 runs on Color OS 7.1 based on android 10.
> Please find screenshot.
> Torrent file and gif file failed to open with Firefox nightly.

Hello, note that I tested on the latest Nightly that was released a few hours ago.
![20210210-145058-1](https://user-images.githubusercontent.com/42831109/107515409-a23a9b80-6bb3-11eb-80d2-7d78d3853c59.gif)

**Comment by iamiceparticle** [comment] 2021-02-10 13:59
@abodea from where can I get it? I can see version 9 Feb 2021 23:00 on play store.

**Comment by abodea** [comment] 2021-02-16 14:10
@iamiceparticle are you still reproducing the issue? Can you check it now, please?

**Comment by iamiceparticle** [comment] 2021-02-17 06:53
@abodea I still have issue with latest Firefox nightly.

https://user-images.githubusercontent.com/76210878/108166834-c3067200-711a-11eb-90fd-4c1a4c5e7675.mp4

Here is the screen recording for the issue.

**Comment by iamiceparticle** [comment] 2021-03-12 13:19
@Amejia481 @abodea I am not sure what is the issue with Firefox nightly but this issue does not exist in latest Firefox beta.
Not sure if you want to look into the issue with Firefox nightly.
This exists on stable Firefox also.

**Comment by lobontiumira** [comment] 2021-03-22 07:56
I was not able to reproduce this issue on the 3/22 Firefox Nightly app using an OnePlus 5T (Android 10) device.
I've downloaded the file from https://yts.one/movie/shubh-mangal-zyada-saavdhan-2020/, when the download was complete, I tapped the "Open" button and Flud app opened displaying the information page of the downloaded file.

**Comment by iamiceparticle** [comment] 2021-03-22 08:10
@lobontiumira 
I just checked it. It seems it is fixed now.
Thanks for looking into it.

**Closed** 2021-03-22 08:31 UTC
Labels: Feature:Download, S3, eng:qa:verified, 🐞 bug
