### ISSUE TITLE
FNX-4497 ⁃ [Bug]  m.youtube.com - Unable to access the comments section

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#10720] opened 2020-05-18 00:51 UTC
## Steps to reproduce
1. Go to https://m.youtube.com/watch?v=nJ7zozOm8lo
1. Scroll down
1. Tap on the comment section at the bottom

### Expected behavior
The comment section is opening

### Actual behavior
The comment section doesn't open.

### Device information
* Android device: Pixel 2, Android 10
* Fenix version: Build 21380606 GeckoView 78.0a1-20200514094044

See the details in https://github.com/webcompat/web-bugs/issues/52915

Some note:

* Activating the hit testing to select the element in the inspector has no effect for this specific section.
* Adding a margin-bottom no less than 16px fixes the issue.
* It looks like the touch hit area is too close from the url bar and is not taken into account.

Opening here because it doesn't look like an issue with the site itself, but the way the hit is interpreted by Firefox preview. If there is no issue with Fenix, I'll communicate with YouTube to find a way to fix it.

**Comment by ekager** [comment] 2020-05-18 17:56
Possibly related to https://github.com/mozilla-mobile/fenix/issues/10578#issuecomment-628711075

**Comment by hakkikaancaliskan** [comment] 2020-05-21 11:44
> Possibly related to [#10578 (comment)](https://github.com/mozilla-mobile/fenix/issues/10578#issuecomment-628711075)

This happens on bottom of website, like comment section or reddit next button etc. Maybe this is about to dynamic navbar?

**Comment by ekager** [comment] 2020-06-04 01:48
Added this STR to https://bugzilla.mozilla.org/show_bug.cgi?id=1643212

**Comment by sheikh-azharuddin** [comment] 2020-06-06 10:39
Any update on the fix? Issue is there since long time... interestingly no issue is normal firefox preview version...seems issue with nightly

**Comment by hakkikaancaliskan** [comment] 2020-06-06 10:52
@sheikh-azharuddin as of https://bugzilla.mozilla.org/show_bug.cgi?id=1643212 it's fixed, fix will be in probably 1 or 2 nightly later(?).

**Comment by sheikh-azharuddin** [comment] 2020-06-06 11:07
> @sheikh-azharuddin as of https://bugzilla.mozilla.org/show_bug.cgi?id=1643212 it's fixed, fix will be in probably 1 or 2 nightly later(?).

Thanks 👍😊

**Comment by hakkikaancaliskan** [comment] 2020-06-07 16:01
I can confirm that with 45.0.20200607130045 ac build it's fixed on my on Xperia XZ1(Android 9) and emulator.

**Comment by sheikh-azharuddin** [comment] 2020-06-07 16:48
> I can confirm that with 45.0.20200607130045 ac build it's fixed on my on Xperia XZ1(Android 9) and emulator.

Great..👍
Waiting for the update...I am on 5th June build...

**Comment by AndiAJ** [comment] 2020-06-09 12:44
Hi, **verified as fixed** on the latest **`Nightly Build 200609 from 6/9`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)

► Video
![20200609-153635](https://user-images.githubusercontent.com/51314259/84148754-18f12900-aa68-11ea-9fe5-55d242ebdb21.gif)

**Closed** 2020-08-11 01:32 UTC
Labels: b:web-content, eng:qa:verified, needs:gecko, 🐞 bug
