### ISSUE TITLE
Clicks are no longer registering reliably on certain websites

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#16295] opened 2020-10-31 09:05 UTC
# Steps to reproduce

1) Go to chessable.com
2) Launch one of the courses and "review moves". (Likely needs an account)
3) Try to move pieces on the board.

### Expected behavior

4) Pieces on the chessboard drag as normal.

### Actual behavior

4) Intermittently many clicks don't register, or one has to click a piece first before it can be dragged. The buttons in the interface also stop registering clicks. In the screenshot, the buttons below the board for example do not respond.

![Screenshot_20201031-100213](https://user-images.githubusercontent.com/1104290/97775398-8cebb500-1b60-11eb-9292-58941d423d18.png)

This is a fairly recent **regression**, 2-3 weeks. The site used to work nicely with Fenix.

### Device information

* Android device: Pixel 2 XL
* Fenix version: Current Nightly, revision 3d5f376d44e0

**Comment by gcp** [comment] 2020-10-31 09:13
Sometimes clicking many times in sequence makes a click register. It's like half of the input events get dropped for some reason.

**Comment by gcp** [comment] 2020-10-31 09:18
Verified that the site works correctly with release Fenix.

**Comment by AdrianChandra** [comment] 2020-10-31 17:16
Realme 3 pro, Realme ui 1.0.

Same issue with unregistered/unresponsive touch on many website since 82.1.1. 81.1.5 Work just fine. Tried Firefox Beta 83.0.0.beta same issue. Tried Firefox Nightly 201030 17:00 same issue. 

Tried on www.goggle.com.
Touch unresponsive on search text field, but responsive on url bar. 
Touch unresponsive on link on search result, but responsive on url bar.
Need multiple touch to register the click.

**Comment by OllyHodgson** [comment] 2020-11-02 19:02
This sounds very similar to #16235.

**Comment by gcp** [comment] 2020-11-02 19:23
Yes, sounds like the same problem.

**Comment by kbrosnan** [comment] 2020-11-02 20:41
@gcp can you reproduce this on [GVE](https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-gcp-opt)? If so then mozregression bisection using GVE would be a great help.

**Comment by AdrianChandra** [comment] 2020-11-05 08:35
Yes it think its the same that bug. Also the issue is affecting all website not just spesific website.

**Comment by sflorean** [comment] 2020-11-19 06:39
@gcp this issue is now fixed in Nightly, could you please take another look and share with us if it is fixed for you, also? Thank you!

**Comment by gcp** [comment] 2020-11-19 14:18
I tried a Nightly from ~9 hours ago and it still easily reproduces.

(adb is broken here, it will be a while before I can bisect this)

**Comment by gcp** [comment] 2020-11-22 13:49
This regression seems to be in release too now.

**Comment by AdrianChandra** [comment] 2020-11-28 17:30
> @gcp this issue is now fixed in Nightly, could you please take another look and share with us if it is fixed for you, also? Thank you!

Fixed for me

**Comment by gcp** [comment] 2021-01-11 17:10
I'm still having this problem. I hope to have some breathing room to bisect it at some point, because it's making dogfeeding Fenix very problematic.

**Comment by sflorean** [comment] 2021-07-13 15:16
Closing this based on the fact that the fix is in Release version.
@gcp let me know if this works or not for you, and we can re-open this issue. 
Thank you!

**Closed by sflorean** 2021-07-13 15:16 UTC
Labels: b:web-content, wontfix, 🐞 bug
