### ISSUE TITLE
[Bug][L10n] "Account settings" from Tabs tray - Sync tabs is not translated in some languages

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#19205] opened 2021-04-23 08:14 UTC
## Steps to reproduce
1. Launch Fenix and set the language to Arabic/Japanese/Hindi;
2. Tap the tab counter;
3. Tap the Sync tabs section from Tabs tray;
4. Tap the three-dot menu;
### Expected behavior
The "Account settings" is translated in Arabic/Japanese/Hindi.
### Actual behavior
The "Account settings" is not translated in Arabic/Japanese/Hindi;
![rsz_screenshot_20210423-105657](https://user-images.githubusercontent.com/48799384/115840985-fd470500-a424-11eb-860f-07fe170415bb.png)

### Device information

* Device vendor / model and Android version: Pixel 2 (Android 9)
* Firefox for Android version: Nightly 4/23 and Beta 89.0.0-beta.1

**Comment by Delphine** [comment] 2021-06-08 23:58
Hmm I see "Account Settings" as localized on Release and Nightly. I also see every instance localized in Pontoon.
Are we sure this is still an issue? Please let me know

**Comment by LaurentiuApahideanSV** [comment] 2021-06-09 13:05
I can confirm the issue is fixed on RC 89.1.1 and Beta 90.0.0-beta.2, the Account settings is translated now.

**Comment by Delphine** [comment] 2021-06-16 23:08
Ok closing then, thank you!

**Closed by Delphine** 2021-06-16 23:08 UTC
Labels: Feature:Tabs, S3, 🌐 L10N, 🐞 bug
