### ISSUE TITLE
Add Fling/Scroll Related Config to Settings

### ISSUE THREAD

**Issue by qeomash** [mozilla-mobile/fenix#14569] opened 2020-09-01 07:46 UTC
### What is the user problem or growth opportunity you want to see solved?
I want to control how fast features such as fling or quick scrolling activate, but am unable to without modifying the (unavailable) `about:config` options.
### How do you know that this problem exists today? Why is this important?
I encounter the undesirable behavior of scrolling an extra screen and a half after a few short scrolling swipes _constantly_ while using the newest version. The inconsistency with other Android apps is honestly the reason I didn't adopt Firefox mobile years ago, and will be the primary reason I don't stay.
### Who will benefit from it?
Anyone who wants to control how their scrollbar would benefit from this UX improvement.

This is the only app on my phone that has scrolling behavior like this, so my UX is honestly quite poor. I constantly have to put the breaks on a massive jump of a scroll when skimming a page. Adding a way for the user to control how fast the page scrolls, the delay before a fling is activated, or disable fling entirely if they so choose is a must. 

See also #3744

**Comment by kbrosnan** [comment] 2020-09-02 00:53
Closing as a duplicate of #7865

**Closed by kbrosnan** 2020-09-02 00:53 UTC
Labels: needs:triage

**Comment by qeomash** [comment] 2020-09-02 01:06
@kbrosnan this isn't about `about:config`, these settings _need_ to be in the regular user settings. `about:config` is the workaround for advanced users.

**Comment by tortino** [comment] 2020-11-17 12:59
Yes, this is not a duplicate of 7865. Please reopen.

**Comment by kbrosnan** [comment] 2020-11-18 01:00
Exposing such low level preferences are not planned.
