### ISSUE TITLE
[Bug] Cannot delete multiple frecency top sites

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#14538] opened 2020-08-31 16:33 UTC
## Steps to reproduce
Have top sites turned on in settings
Visit some websites
Delete multiple auto-populated sites from top sites

### Expected behavior
sites disappear

### Actual behavior
after the first 1 or 2, sites stop getting removed even when selecting "delete from history"

### Device information

* Android device:  pixel 3
* Fenix version: Nightly 8/31

**Comment by liuche** [comment] 2020-08-31 16:35
@LaurentiuApahideanSV i saw you QA-ed #10342 did you see this problem? I also noticed that it wasn't listed in the QA acceptance criteria so maybe that was why.

**Comment by gabrielluong** [comment] 2020-08-31 20:51
This seems related to #14230. When we remove a frecent site, it seems like the top sites are updated to some cached version where it might appear that you have not removed the frecent site. If you try to remove it again, it ends up doing nothing because it's actually already gone.

**Comment by LaurentiuApahideanSV** [comment] 2020-09-01 13:59
@liuche Yes, I have encountered this issue on Firefox Preview Nightly 9/1 when manually adding the same site to top sites multiple times, see issue https://github.com/mozilla-mobile/fenix/issues/11188 for further information. The issue can also be reproduced by populating the top sites section with pages of the same website, for example populating the top sites section with multiple articles from https://edition.cnn.com/ and the trying to delete them.

**Comment by gabrielluong** [comment] 2020-09-16 16:18
This should be fixed with https://github.com/mozilla-mobile/fenix/pull/15126.

**Closed by gabrielluong** 2020-09-16 16:18 UTC
Labels: Feature:TopSites, Skittle, 🐞 bug
