### ISSUE TITLE
support a build free including upstream code

### ISSUE THREAD

**Issue by KiaraGrouwstra** [mozilla-mobile/fenix#27732] opened 2022-11-06 13:10 UTC
### What is the user problem or growth opportunity you want to see solved?

[On F-Droid](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/), Fennec is listed with anti-feature:

> The upstream source code is not entirely Free

This raises questions:

- which parts are non-free?
- what was the rationale behind these decisions?
- would it be viable to support a build that resolves this anti-feature?

### How do you know that this problem exists today? Why is this important?

Today: just checked the link.
Why: as a user, I would like to have the ability to inspect what software I am running.

### Who will benefit from it?

Wary users, open-source advocates.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21942)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21942

**Comment by cadeyrn** [comment] 2022-11-06 14:11
Duplicate of #12809.

There is also an detailled explaination why various dependencies are used. It's a shame that F-Droid confuses people with such sentences without giving more context.

**Closed** 2022-11-06 17:13 UTC
Labels: needs:triage
