### ISSUE TITLE
RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: android.view.Inflate.Exception: Binary XML file line #27

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#23057] opened 2022-01-04 16:30 UTC
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/15395580/?referrer=github_plugin

```
UninitializedPropertyAccessException: lateinit property binding has not been initialized
    at org.mozilla.fenix.HomeActivity.getSupportActionBarAndInflateIfNecessary(HomeActivity.kt:16)
    at org.mozilla.fenix.ext.FragmentKt.showToolbar(Fragment.kt:3)
    at org.mozilla.fenix.settings.about.AboutFragment.onCreateView(AboutFragment.kt:19)
    at org.mozilla.fenix.HomeActivity.onCreateView(HomeActivity.kt:12)
    at org.mozilla.fenix.perf.PerformanceInflater.inflate(PerformanceInflater.kt:5)
...
(33 additional frame(s) were not displayed)

InflateException: Binary XML file line #27 in org.mozilla.fenix:layout/activity_home: Error inflating class fragment
InflateException: Binary XML file line #27 in org.mozilla.fenix:layout/activity_home: Binary XML file line #27 in org.mozilla.fenix:layout/activity_home: Error inflating class fragment
RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #27 in org.mozilla.fenix:layout/activity_home: Binary XML file line #27 in org.mozilla.fenix:layout/activity_home: Error inflating class fragment
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
...
(8 additional frame(s) were not displayed)

Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #27 in org.mozilla.fenix:layout/activity_home: Binary XML file line #27 in org.mozilla.fenix:layout/activity_home: Error inflating class fragment
```

**Comment by mcarare** [comment] 2022-01-06 11:51
This specific crash is incidentally fixed by the change [here](https://github.com/mozilla-mobile/fenix/pull/23001/files#diff-e4df32efc2b21e9db1887d40b897bdc76a5a338f82ccff64f7ffdc3bfc64100aR89): 
 by moving the `showToolbar` call from `onCreateView` to `onResume`. 

The difference from https://github.com/mozilla-mobile/fenix/issues/22995 is that if in that case the configuration change and activity recreation is caused by the locale change, for devices with Android 12 this is caused by changing the device wallpaper. See more info on this blog [post](https://commonsware.com/blog/2021/10/31/android-12-wallpaper-changes-recreate-activities.html) and the opened [issue](https://issuetracker.google.com/issues/199995249?pli=1).

**Comment by mcarare** [comment] 2022-01-06 12:21
STR for QA, on a device with Android 12 

1. Open app.
2. Navigate to the about screen in settings.
3. Go to the device home screen
4. Change device wallpaper.
5. Go back to the app.

 The crash will occur on the release/ beta version and should be fixed on Nightly.

**Comment by SoftVision-LorandJanos** [comment] 2022-01-06 13:51
I managed to reproduce the issue on the latest Release (96.1.0) and Beta (96.0.0-beta5) with an Android 12 device.
Verified as fixed on the latest Nightly (2022-01-06).
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-01-06 13:51 UTC
Labels: b:crash, Feature:HomeScreen, eng:qa:needed, Android:12

**Comment by kbrosnan** [comment] 2022-01-10 22:36
Thanks for the investigation @mcarare and the confirmation that it is fixed @SoftVision-LorandJanos
