### ISSUE TITLE
[Bug] Missing icon for "Close private tabs" notification

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#14674] opened 2020-09-03 10:16 UTC
## Steps to reproduce

1. Open a private tab and visit any website.
2. Open the notification tray.

### Expected behavior

A mask icon should appear to the left of the "Close private tabs" notification.

### Actual behavior

The mask icon does **not** appear to the left of the "Close private tabs" notification.

![](https://user-images.githubusercontent.com/45960387/92102642-70a5f300-ee11-11ea-8590-adcf81ceefd7.jpg)

### Device information

* Android device: Oppo Reno 2
* Fenix version: Nightly 200903 06:04 (Build #2015761715)

**Comment by hwinnemoe** [comment] 2020-09-03 10:17
Duplicate of #14460

**Closed** 2020-09-03 10:18 UTC
Labels: needs:triage, 🐞 bug
