### ISSUE TITLE
[Bug] Going back to home screen should close tabs

### ISSUE THREAD

**Issue by Standard8** [mozilla-mobile/fenix#3760] opened 2019-06-28 10:46 UTC
## Steps to reproduce

1. Start Firefox Preview
2. Do a search, or open an item from a collection
3. Go back

### Expected behavior

The tab is closed. I would expect this, because I'm going back - I've finished looking at the page for that session, and I don't really want the extra step of having to close the tab manually, especially as closing preview also doesn't close the tabs.

In particular, one of my use cases is that I have a set of websites I look at every day. Currently, I'm saving them in a collection. I open the collection, look at one of the websites, then go back to the Fenix home screen and open the next one.

At the end of this, I have 3-4 open tabs, that I then have to close manually. I'm never going to want to save these as I already have them saved.

Similarly, I don't want the tab to stay open as next time I'd visit it, I'd have to reload it (again another manual step).

If I load the page from the collection again, then I get duplicate open tabs.

Whilst I can see there's occasional potential benefit in the context of keeping tabs open, to be able to save them - having to close them all manually / or reload pages feels like unnecessary extra work.

### Actual behavior

The tab remains open.

### Device information

* Android device: Samsung S6
* Fenix version: 1.0.0 (Build #11721515)

**Comment by panpiotrs** [comment] 2019-06-28 19:22
Closing them should be an option (or default, with keeping them open as option). My workflow is completely opposite. And there are settings for that in other browsers too.

**Comment by Hocuri** [comment] 2019-06-29 11:19
Duplicate of #3605 (?)

**Comment by kbrosnan** [comment] 2019-06-29 20:14
No #3605 is about all your tabs. This is about a single tab.

**Comment by gagahpangeran** [comment] 2019-07-11 03:43
I think this is good behavior and should also apply when open link in a new tab.

- Press and hold a link
- Click `Open link in a new tab`
- Click `Switch` at bottom
- Go back

I expect the tab is closed and go back to previous tab, but for now the tab remains open and go back to  open tabs screen.

I use firefox android, firefox lite, and chrome android and they all have this 'go back and close tab' behavior.

**Comment by sblatz** [comment] 2019-07-20 01:09
@mozilla-mobile/ux please keep this in mind with the tabs redesign.

**Comment by sblatz** [comment] 2019-07-20 01:10
Labeling as waiting because this behavior will be changing with our tab redesign.

**Comment by lime124** [comment] 2019-08-05 19:20
added to the larger design effort. thanks!

**Comment by topotropic** [comment] 2020-01-08 11:57
Closing because a decision addressing this was made here https://github.com/mozilla-mobile/fenix/issues/6620#issuecomment-571732037

**Closed by topotropic** 2020-01-08 11:57 UTC
Labels: Feature:HomeScreen, Feature:Tabs, P3, 🌟 feature request, 🙅 waiting
