### ISSUE TITLE
Allow change the order of bookmarks

### ISSUE THREAD

**Issue by 0x391F** [mozilla-mobile/fenix#17365] opened 2021-01-08 08:04 UTC
### How do you know that this problem exists today? Why is this important?
Chrome could change the order of bookmarks, but Firefox not. 
### Who will benefit from it?
Everyone

**Comment by cadeyrn** [comment] 2021-01-08 08:06
Duplicate of #4348.

**Comment by mcarare** [comment] 2021-01-08 08:18
Closing as duplicate of #4348.

**Closed by mcarare** 2021-01-08 08:18 UTC
Labels: needs:triage
