### ISSUE TITLE
[Bug] distorted audio while playing video at higher speed

### ISSUE THREAD

**Issue by carriesmi** [mozilla-mobile/fenix#8456] opened 2020-02-17 06:48 UTC
## Steps to reproduce
1) open any video on youtube.com (did not check on other websites)
2) change playback speed to 1.5x
### Expected behavior
The audio should be similar to youtube app and other browsers
### Actual behavior
The audio is highly distorted and unbearable

### Device information
* Android device: Samsung M20
* Fenix version: 3.2.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15756)

**Comment by sv-sdeiac** [comment] 2020-02-17 08:52
I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 2/16 #20470606 and Firefox Preview RC 3.2.1 #20250350.

Devices:
- Samsung Galaxy S8 (Android 9);
- Nokia 6 (Android 7.1.1).

Notes:
- Using the Youtube app or Google Chrome, the issue is not reproducible.

**Comment by ekager** [comment] 2020-04-11 01:27
Thanks for filing! Looks like https://bugzilla.mozilla.org/show_bug.cgi?id=1624026

**Comment by yump** [comment] 2020-09-09 07:28
I can reproduce this on a Nokia 6.1 with Fenix 81.1.0-beta.2 and Nightly Build #2015762483.

**Comment by Mugurell** [comment] 2020-10-06 10:27
Seems like this should be resolved - https://bugzilla.mozilla.org/show_bug.cgi?id=1624026#c31

**Comment by yump** [comment] 2020-10-06 10:36
Fixed on my machine.

**Comment by carriesmi** [comment] 2020-10-06 10:43
Yup it's fixed on latest nightly build.

**Comment by AndiAJ** [comment] 2020-10-06 15:14
Hi, I've just checked this matter on the latest **`Nightly Build 201006`**

✔️ Works properly on:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• Xiaomi Redmi Note 8T (Android 9)
• LG G7 FIT (Android 8)
• Huawei MediaPad M2 (Android 5.1.1)

❌ Still reproducible on:
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

I'll remove the QA needed label until further notice

**Comment by AndiAJ** [comment] 2021-02-09 14:04
Still reproducible on 85.1.3 using a OnePlus A3 (Android 6.0.1)

**Comment by Dunexus** [comment] 2021-02-15 09:43
Reported to be still reproducible by a user https://github.com/mozilla-mobile/fenix/issues/17993
>### Device information
>
>Huawei P10 Lite WAS-LX1
Android 8.0.0.397 C432
>
>85.1.3 (Build #2015792283)
AC: 70.0.20, d282b98ef
GV: 85.0.2-20210208133944
AS: 67.2.0

**Comment by Mugurell** [comment] 2021-03-23 19:00
Does this still reproduce on the current Nightly?

**Comment by AndiAJ** [comment] 2021-03-29 06:22
Hi, I've just checked this matter on the latest **`Nightly Build 210329`**

✔️ Works properly on:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)

❌ Still reproducible on:
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

**Comment by lextra2** [comment] 2022-01-19 16:17
Still an Issue for me on Amazon Fire Tablet and has been this way for years. A real shame. Meanwhile any chromium based browser works just fine, even with 2x speed.

**Closed** 2022-11-27 07:58 UTC
Labels: 🐞 bug, Feature:Media, S2, needs:gecko, wontfix
