### ISSUE TITLE
[Bug] Can't set as default browser on Android 5

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5972] opened 2019-10-11 21:38 UTC
### Acceptance Criteria
- [ ] Set as default always should work on Android 5
- [ ] Contact SUMO with the results of what we decided so they can update the Private Browsing Mode article to explain if this doesn't work on Android 5
- [ ] If this goes past the E3 timebox, then highlight it

### Details

On Android 5, when I press "always" to launch links in Fenix or Private Fenix, the preference is not remembered.

This is the root cause of #5870. 

I did a bit of investigation, and we **could** set the default on Preview v2.0. I believe adding the activity-alias for "always open links in private mode" silently breaks things on Android 5.

The issue can be seen below.

![set as default 2019-10-11 14_38_05](https://user-images.githubusercontent.com/4400286/66686581-c0496200-ec34-11e9-8355-e349afd86457.gif)

**Comment by liuche** [comment] 2019-10-15 17:47
We first want to test taking out the `activity-alias`.

Questions:
- How many Fennec users are on Android 5?
- Is this broken on all versions of 5?

Some options:
- Have a separate manifest that disables the `activity-alias` for Android 5 (and disabling the Private Mode launcher for those users)

**Comment by boek** [comment] 2019-11-26 21:02
This feature doesn't work on Android 5. The fix was to remove it until we set the minimum Android version to 6 or above.

**Comment by AndiAJ** [comment] 2019-11-27 15:18
Hi @boek , I've just checked this issue on the latest **Nightly Build #13310607 from 11/27** using the following devices:


► Have only Fenix installed (Chrome disabled) ✔️
Fenix is set as the default browser without any other actions, and work properly 
![20191127_152904](https://user-images.githubusercontent.com/51314259/69727688-b66bb780-112b-11ea-98f7-42f5f50292d0.gif)


► Having Chrome installed and afterwards install Fenix ❌
Seems that Chrome is set as default browser.
Can't actually disable it (Settings>Apps>Chrome>Clear defaults) the "Clear defaults" button seems to be disabled.
The only workaround is to disable Chrome and to have only Fenix installed.
![20191127_154628](https://user-images.githubusercontent.com/51314259/69729630-54ad4c80-112f-11ea-8d08-f8ddec76e98c.gif)

► Having only Firefox and Fenix installed (Chrome disabled) ❌
Firefox is set as default browser.
Can't disable it (Settings>Apps>Chrome>Clear defaults) the "Clear defaults" button seems to be disabled.
The only workaround is to uninstall Firefox and to have only Fenix installed.
![20191127_160441](https://user-images.githubusercontent.com/51314259/69730304-765b0380-1130-11ea-9c67-257b1cfffa18.gif)

► Having Chrome, Firefox & Fenix installed ❌
Chrome is set as default browser.
As per the above scenarios, I can't "Clear defaults" so the only workaround is to disable it.
After disabling Chrome, the default browser is Firefox, and again the "Clear defaults" button is disabled.
Fenix is set as the default browser app  automatically only after uninstalling Firefox.
![20191127_164931](https://user-images.githubusercontent.com/51314259/69734089-14ea6300-1137-11ea-84a6-6171531da3da.gif)

Please review and let me know how should we proceed.

**Comment by liuche** [comment] 2019-12-20 01:23
Wait, since the PB mode `activity-alias` was removed, does this mean this is a separate regression, unrelated to PB mode? @sblatz

**Comment by kevinslashslash** [comment] 2019-12-23 20:50
Sorry if this is the wrong ticket to post in.
My understanding is part of the root issue is a UX problem with setting the default browser on Android 5 and 6 because they did not have a screen in system settings.
An alternative approach, as done in Nova Launcher Settings > Set Default Home, is to invalidate the currently set one and then fire an intent so the user picks the default browser again.
Android invalidates the default intent handler when resolving the intent if the list of possible handlers has changed. So an app can:
Have a disabled activity/activity-alias that handles the default browser intent
Enable that component
Use packagemanager to resolve the default, it should give back the intent chooser
Disable that component
Start activity for the default intent, it'll show the intent chooser and let the user pick their default. Alternatively, the setting could just be "Clear default browser" and the preference could show the currently set browser app then change to "Not set" and the user will be prompted next time they open a link.

Using this approach Firefox on Android 5 and 6 could have a Default Browser option in settings, which is handy, and also fixes the UX issue of where to put the "Always open in private tabs" checkbox.

I'd be happy to do a pull request for this if it sounds like a good approach.

**Comment by sblatz** [comment] 2019-12-30 16:55
@liuche Yeah, this seems like some weird interaction happening with "Clear defaults"? I don't believe it should be working like this. It seems to be a separate regression from the activity-alias.

**Closed** 2021-02-12 04:27 UTC
Labels: E3, Feature:FennecTransition, Feature:PrivateBrowsing, P2, wontfix, 🐞 bug
