### ISSUE TITLE
FNX-5509 ⁃ Successful FxA login should open Sync Settings, not a web page.

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/fenix#2196] opened 2019-05-01 13:49 UTC
Not sure if we have this on file.

Reference document https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/357470306_Settings_-_New_User

## Steps to reproduce
Login to Sync via FxA

### Expected behavior
After a successful login, the app should open native `Sync Settings`

### Actual behavior
The app opens "You are now ready to use Firefox Sync" web page. (It's a bit of a dead end)

cc @grigoryk

**Comment by AmyYLee** [comment] 2019-05-10 17:57
@ryanfeeley See above

**Comment by ryanfeeley** [comment] 2019-05-10 20:55
@AmyYLee just chiming in to say @vladikoff is correct

**Comment by vladikoff** [comment] 2019-05-16 17:21
@grigoryk @vesta0  in my testing on a Mozilla Guest WiFi the current experience is kinda broken, after I sign in via pairing and go to settings the button still says "Sign In" and only kicks in after about 20-30 seconds. What can we do about this bug?

**Comment by vesta0** [comment] 2019-05-16 21:20
@vladikoff you are right, this looks like a regression. Do you know why it's happening?

**Comment by vladikoff** [comment] 2019-05-16 21:22
@vesta0 could be because we are syncing more stuff now

**Comment by vladikoff** [comment] 2019-05-21 20:28
@vesta0 @grigoryk we might need to file a different bug (marked as an MVP Blocker) for this so we don't forget. See affected users here: https://groups.google.com/forum/#!msg/fenix-nightly/H9kTciTLoBk/o81d81VOBQAJ

**Comment by vesta0** [comment] 2019-05-22 15:14
@vladikoff I agree. Would you please file a bug for it since you have more information about the potential cause?

**Comment by grigoryk** [comment] 2019-05-30 20:16
After some reflection, I don't think we actually want to do this. Having the user end up deep in settings after completing sign-in seems counter-productive. Their goal was not to look at sync status, but to either complete some task, get to their bookmarks and/or history, establish a connection between browsers, or just get through the nagging prompts and move on. Either way, displaying Sync Settings with no clear indication of "you're done, and here's what you can now do" seems strictly worse than what we have now. People often don't pay attention to subtle UIs while they're going through auth flows, and sync settings is just too subtle to be a terminal point in the flow.

This will also require changes in a-c, and I'd rather focus on stability issues right now.

I do agree that the current state is non-ideal, but let's re-address this once we have time to think through an actually good experience?

**Comment by grigoryk** [comment] 2019-05-30 20:17
Removed the blocker label, feel free to re-add it if you disagree strongly.

**Comment by sblatz** [comment] 2019-05-30 20:23
@vesta0, @bifleming just so you're aware ^^

**Comment by ryanfeeley** [comment] 2019-05-30 20:27
It's harmless to leave it at the **You are now ready to use Firefox Sync** page for now. Trailhead, and a desire to offer something better than Connect Another Device, means this page will change soon enough.

**Comment by vesta0** [comment] 2019-06-13 05:02
Closing this based on comments from @grigoryk

**Closed** 2020-08-11 14:14 UTC
Labels: P1, 🐞 bug
