### ISSUE TITLE
[Bug]: Undo close tab prevent fast closing tabs

### ISSUE THREAD

**Issue by Taknok** [mozilla-mobile/fenix#20394] opened 2021-07-16 12:44 UTC
### Steps to reproduce

1. Close a tab
2. Notification "undo close tab undo" is displayed. This notification is displayed floating over the tab list and is aligned with last tab.
3. It is not possible to tap the close button of the last tab.

### Expected behaviour

Close tab button should be accessible. This can be done by reducing the width of the notification or setting the gravity center of the notification between two lines of tabs.

### Actual behaviour

The close tab button cannot be clicked because the notification is on top of it. Thus you have to wait the end of the toast notification to close the next tab, and so on.

### Device name

OnePlus 7

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

90.1.1

### Additional information

Video of the behavior :

https://user-images.githubusercontent.com/12498020/125949487-9794223b-152e-47ca-8634-dc55f928c04c.mp4

**Comment by Nickoriginal** [comment] 2021-07-16 13:07
Duplicate of #19166

**Closed** 2021-07-16 13:10 UTC
Labels: needs:triage, 🐞 bug

**Comment by Nickoriginal** [comment] 2021-07-20 03:42
https://github.com/mozilla-mobile/fenix/issues/20430
