### ISSUE TITLE
[Bug] Dynamic navbar isn't applied in extensions

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#12239] opened 2020-07-03 10:41 UTC
## Steps to reproduce
1. Install ublock origin
1. open dashboard
1. Scroll down
    1. Expected behavior
Dynamic navbar is enabled, you can see "reset to default settings". 
    1. Actual behavior
Navbar is static, never hides, but the layout is acting like navbar is dynamic. Thus you can't see "Reset to default settings" unless you zoom
    1. Device information

* Android device: Pocophone F1, android 9
* Fenix version: nightly 200703 06:16

**Comment by hwinnemoe** [comment] 2020-07-03 10:55
Duplicate of #11858

**Comment by B0pol** [comment] 2020-07-03 13:39
> Duplicate of #11858

Not really. I was taking ublock origin _as an example_, but the issue is about dynamic navbar, not ublock origin. The same thing happens with other addons: install search by image, click on three dots then options, you'll see the navigation bar doesn't hide when you scroll.

**Comment by cadeyrn** [comment] 2020-07-03 13:47
If the issue describes the same issue it _is_ a duplicate. Even if other add-ons are also affected. It is really unlikely that there are different causes for different add-ons.

**Comment by kbrosnan** [comment] 2020-08-28 21:40
This looks to be a duplicate of #11858

**Closed by kbrosnan** 2020-08-28 21:40 UTC
Labels: needs:triage, 🐞 bug
