### ISSUE TITLE
Recently closed tabs reopen after quitting and reopening Firefox

### ISSUE THREAD

**Issue by DaVince** [mozilla-mobile/fenix#22454] opened 2021-11-16 05:18 UTC
### Steps to reproduce

1. Close one or more tabs.
2. Navigate out of Firefox and close/remove it from the open apps on Android.
3. Reopen Firefox. 

### Expected behaviour

Only the tabs that I had open on my previous session should be there. 

### Actual behaviour

Along with my other tabs, the tabs I closed are back and immediately load. 

### Device name

Fairphone 3

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

95.0.0-beta.3 (Build #2015845195)

### Additional information

This is mainly an issue for me because half the time, the open tabs are related to payment links that come from other apps, and thus payments are reinitiated or I immediately get pointed back to those related apps before I even get a chance to close the tabs again in Firefox.

If I close the tabs, wait a while, and THEN close Firefox, the tabs properly stay closed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18643)

**Comment by SoftVision-LorandJanos** [comment] 2021-11-17 08:56
Hi @DaVince! Thank you for your report!
I couldn't reproduce your issue.

Tested on the following builds:
- latest Nightly (96.0a1. 2021-11-17).
- latest Beta (95.0.0-beta4).
- latest Release (94.1.2).

Is this an intermittent issue or is it reproducible every time on your end?
If it's intermittent, please see if something else might affect the behavior.
Also, it could be helpful if you could make a video of your issue. Thank you!

**Comment by DaVince** [comment] 2021-12-19 11:08
Hi @SoftVision-LorandJanos,

Sorry for taking a while to respond. This is reproducible every time. If I close tabs and then Firefox within half a minute or so, the tabs reappear.

To be honest, I've been using the same ~100 tabs for around a year now, so probably something got corrupted somewhere or I'm hitting some sort of odd performance-related race condition. I'll back up the tabs and try again with a new profile and report back my experience.

**Comment by DaVince** [comment] 2021-12-19 11:30
So far, it does not exhibit this behavior after resetting the application data and opening/closing a few tabs, but I'd like to test further at a more convenient time to see if the behavior comes back when I open 80 or so tabs.

**Comment by sflorean** [comment] 2022-05-26 14:30
@DaVince this is still reproducible for you? Could you please add a video, if yes?

**Comment by jtagcat** [comment] 2022-05-27 10:28
Majorly suffered under the issue, seems to no longer be the case.

**Comment by DaVince** [comment] 2022-06-10 18:18
Up until two months or so ago, I still seemed to have this issue, but it hasn't happened for a while now. I think this can be closed. :)

**Comment by dursuneren** [comment] 2022-06-13 06:42
Hello. 

I've been facing the same problem for a long time. I also took a short screen recording. 
This happens when; 
- The tab is closed. 
    - Example: --> [Screen Recording](https://vimeo.com/719736513)
- Redirect to another url. 
    - For example, we are now on the google search screen, when we click on any link and redirect to another page and restart the application, it can be on the google search screen. 

I will also be sharing device and version information below. 

Thank you in advance.
___
## Firefox Version

- 101.2.0 (Build #2015885315)

## Android Version

- Android 10

**Comment by konstantinua00** [comment] 2022-07-07 21:42
Firefox version:  
102.1.1 (Build #2015887769), f61b8e3a3+
AC: 102.0.12, 1566dca4ac
GV: 102.0-20220620184213
AS: 93.1.0

Android version:
Android 10

Phone:
Redmi 7A

I doesn't save last session if it was short.  

I open the app, quickly close/open some tabs, then exit. (on my phone just switching to another app closes firefox)
When I open firefox again, newly opened tabs aren't open anymore, newly closed are open again. 
But "lost" new tabs are still recorded in "History", so it's not just reset or smth.

Of note - huge amount of open tabs, but most aren't in active use.
Long sessions seem to save, maybe last some minutes are lost? Not sure

**Comment by echuber2** [comment] 2022-08-23 19:29
> I doesn't save last session if it was short.
> 
> I open the app, quickly close/open some tabs, then exit. (on my phone just switching to another app closes firefox) When I open firefox again, newly opened tabs aren't open anymore, newly closed are open again. But "lost" new tabs are still recorded in "History", so it's not just reset or smth.
> 
> Of note - huge amount of open tabs, but most aren't in active use. Long sessions seem to save, maybe last some minutes are lost? Not sure

I've been experiencing exactly the same symptoms: when I only have FF open briefly and then switch to another app, it seems like my actions (opening/closing tabs) are simply undone when I return. Closed tabs come back and new ones are missing. But if I use FF for several minutes or longer, then the actions seem to have lasting results.

Issue https://github.com/mozilla-mobile/fenix/issues/24034 may be a duplicate of this one.

**Comment by Illiou** [comment] 2022-09-22 13:53
I've had the same issue for months now, it's driving me crazy and honestly just makes me want to switch back to Chrome. Please work on fixing this.

I'm on Android 8.0 on a Oneplus 3T. I also have around 80 tabs open, if that's a relevant factor.

**Comment by Amy-de-l-ABC** [comment] 2022-12-26 21:32
Same issue. Happens on both phone (Pixel 5, Android 11--admittedly needs updating) and tablet (Samsung Galaxy A7 Lite, Android 12). Both devices have 100+ tabs open but many/most sleeping at any given time. (On a related note--if anyone knows of a tab manager for Android, a la Workona, Toast, Toby, etc., but where you can save your entire session on mobile... I'm desperate here!)

**Comment by vehosah** [comment] 2022-12-27 19:23
Fix this damn bug

**Comment by vehosah** [comment] 2023-01-18 17:52
> Hi @DaVince! Thank you for your report! I couldn't reproduce your issue.
> 
> Tested on the following builds:
> 
>     * latest Nightly (96.0a1. 2021-11-17).
> 
>     * latest Beta (95.0.0-beta4).
> 
>     * latest Release (94.1.2).
> 
> 
> Is this an intermittent issue or is it reproducible every time on your end? If it's intermittent, please see if something else might affect the behavior. Alternatively if you could clear your data, and try reproducing it with a clean build, it might tell us if something else affects it. Also, it could be helpful if you could make a video of your issue. Thank you!

It's not on his end only, it's on everyone's end, data clearing doesn't do anything, it happens since fenix happened :)

**Comment by DaVince** [comment] 2023-01-25 07:30
> Up until two months or so ago, I still seemed to have this issue, but it hasn't happened for a while now. I think this can be closed. :)

I'd like to retract this statement as it does end up happening again lately with ~35 tabs open. Maybe it's a matter of time rather than tab count, or a combination of both.

**Comment by boek** [comment] 2023-01-26 23:46
Dup of #24034

**Closed** 2023-01-26 23:48 UTC
Labels: 🐞 bug, Feature:Tabs, S3, needs:triage, qa-triaged
