### ISSUE TITLE
Shield icon disappears from Address bar after the Enhanced Tracking Protection is disabled

### ISSUE THREAD

**Issue by smartfonreddit** [mozilla-mobile/fenix#5612] opened 2019-09-26 15:45 UTC
**What Happens**
Open any website. Tap on the purple shield icon on the address bar. Disable enhanced tracking. Purple shield disappears. Go to Settings > Enhanced Tracking > Exceptions > remove the site  from exceptions > refresh the tab; the shield re-appears on the bar. Happens on any website.

**What should happen**
The shield icon should remain on the address bar after disabling tracking, so the user can easily re-enable tracking.

Nightly 190925 18:01
Galaxy S10e

**Comment by Amejia481** [comment] 2019-09-26 18:30
Duplicate of https://github.com/mozilla-mobile/fenix/issues/5446

**Closed by Amejia481** 2019-09-26 18:30 UTC
