### ISSUE TITLE
[Bug] In latest version of Firefox nightly address bar is raised a little bit resulting bottom chin while viewing webpages

### ISSUE THREAD

**Issue by iamiceparticle** [mozilla-mobile/fenix#18580] opened 2021-03-22 10:51 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Install 21 March version 

### Expected behavior
Address bar should be closer to navigation button

### Actual behavior
Address bar is reaised, resulting bottom chin while viewing webpages

### Device information
Samsung A71, Android 11, UI 3.1

* Device vendor / model and Android version: Samsung Android 11
* Firefox for Android version: ? 21 March 2021
![Screenshot_20210322-160327_Firefox Nightly](https://user-images.githubusercontent.com/76210878/111978969-86b79e80-8b2a-11eb-9601-c308c18485cb.jpg)
![Screenshot_20210322-153523_Firefox Nightly](https://user-images.githubusercontent.com/76210878/111978984-8c14e900-8b2a-11eb-86c1-cda1f3ca7e5d.jpg)
![Screenshot_20210322-160618_Firefox Beta](https://user-images.githubusercontent.com/76210878/111979004-8fa87000-8b2a-11eb-90fb-751334750b4b.jpg)

(go to Settings -> About Firefox)

**Comment by hakkikaancaliskan** [comment] 2021-03-22 10:53
Duplicate of #18546

**Comment by sflorean** [comment] 2021-03-22 12:14
Thank you @iamiceparticle for report! Closing as duplicate of #18546.

**Closed by sflorean** 2021-03-22 12:14 UTC
Labels: needs:triage, 🐞 bug
