### ISSUE TITLE
[Bug] White space above the headers

### ISSUE THREAD

**Issue by chillypeppe** [mozilla-mobile/fenix#16244] opened 2020-10-29 07:54 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open every site with a header, github.com is a good example since it's easier to see the problem. Scroll down and then up, so you notice that a white line happeared and the header jiggles for 1px while you scroll up and down.
### Expected behavior
The white line and the jiggle shouldn't be there
![SmartSelect_20201029-084215_Firefox Nightly.jpg](https://user-images.githubusercontent.com/43646324/97540856-84f70e00-19c4-11eb-8fea-9861a41fb4b2.jpg)
### Actual behavior
![Screenshot_20201029-084155_Firefox Nightly.jpg](https://user-images.githubusercontent.com/43646324/97540870-89232b80-19c4-11eb-902e-f11906a75475.jpg)
The white line is visible and the jiggle is always there. The difference between the other bug reports about the space above the header, which you can find [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1648079) is that in one of the latest versions of firefox nightly that line has been filled instead of been transparent, but it's still there and it still bothers me.
### Device information

* Android device: Samsung Galaxy S10
* Fenix version: Nightly 201028 17:00

**Comment by s-ankur** [comment] 2020-10-29 16:29
Duplicate of https://github.com/mozilla-mobile/fenix/issues/10598, thanks for filing

**Comment by kbrosnan** [comment] 2020-10-29 18:23
Closing as a duplicate

**Closed by kbrosnan** 2020-10-29 18:23 UTC
Labels: needs:triage, 🐞 bug
