### ISSUE TITLE
[Bug] Show 'Sync is on' toast only on first login

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#4633] opened 2019-08-09 01:35 UTC
## Steps to reproduce
1. Sign into a Sync account.
2. Observe the 'Sync is on' toast.
3. Close and swipe away the app.
4. Re-open the app.

### Expected behavior
The toast is only seen once on the first login.

### Actual behavior
The toast is seen every time the app is cold booted.

### Device information

* Android device: n/a
* Fenix version: n/a

**Comment by jonalmeida** [comment] 2019-08-09 01:36
To fix this, we can use the `newAccount` bool in [the account observer](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#754) to know if this is the first login and only then show the toast.

**Comment by dragneelfps** [comment] 2019-08-09 04:38
@jonalmeida can I work on this?

**Comment by jonalmeida** [comment] 2019-08-09 14:14
@dragneelfps I've mostly gone with intuition on what the fix should be. Let's wait for @vesta0 to confirm if this an issue first.

**Comment by dragneelfps** [comment] 2019-08-09 16:38
@jonalmeida sure.

**Comment by vesta0** [comment] 2019-08-10 01:15
This is definitely looks like a regression. The expected behavior is to see the 'Sync is on' toast on the first login as @jonalmeida pointed out.

**Comment by dragneelfps** [comment] 2019-08-10 07:42
@vesta0 so should I raise a PR to fix this regression(using the `newAccount` bool as pointed out by @jonalmeida)?

**Comment by jonalmeida** [comment] 2019-08-11 23:02
> @vesta0 so should I raise a PR to fix this regression(using the `newAccount` bool as pointed out by @jonalmeida)?

@dragneelfps yes, please do! :)

**Comment by vesta0** [comment] 2019-08-12 03:29
Yes please @dragneelfps :+1:

**Comment by dragneelfps** [comment] 2019-08-12 05:47
@vesta0 I have raised PR #4676 for this issue.

**Comment by sv-ohorvath** [comment] 2019-08-16 14:11
Verified as fixed on RC 1.3.0-rc1

**Closed by sv-ohorvath** 2019-08-16 14:11 UTC
Labels: Feature:Sync, eng:qa:needed, good first issue, 🐞 bug
