### ISSUE TITLE
[webcontent]Youtube videos cut off in fullscreen.

### ISSUE THREAD

**Issue by Throneaway420** [mozilla-mobile/fenix#16313] opened 2020-11-02 07:34 UTC
## Site with issue and any steps to reproduce
Youtube.com  
On the Youtube website, go to any video, click the fullscreen button, the video will enter fullscreen mode but a sizeable portion of the bottom of the screen is cut off. 

### Expected behavior:  
The video should enter fullscreen mode with black bars on either side to allow the whole video to fit in frame, or there should be options available to the user to adjust the display mode.

### Actual behavior: 
The video fills the screen left to right, loads the top edge of the video correctly, and cuts off about 1/5 of the bottom edge of the video.

### Does toggling Tracking Protection fix the issue?: 
No

### Can you reproduce in Chrome (or other non-Mozilla browser)?:  
In Chrome the fullscreen video loads correctly, with black margins on either side and the whole video fit to the screen top to bottom. 

### Device information: 
My device is a Samsung Galaxy A51, running Android version 10, with a 6.5in screen and a 20:9 aspect ratio.

* Android device: Samsung Galaxy A51
* Fenix version: 82.1.1 (build #2015770923)  / AC: 60.0.5, a1a471ddc  /   GV: 82.0-20201014125134  /  AS: 63.0.0

**Comment by s-ankur** [comment] 2020-11-02 12:18
Duplicate of #8252, thanks

**Comment by Throneaway420** [comment] 2020-11-02 17:49
Mine won't let me scroll up or down like that user claims they could, the edge is just cut off with no way to view it.  However, if I attempt to load the site in desktop mode then click the fullscreen button, the video experiences the same cropping issue as before, but I can still scroll down and see the description and comments and everything else below the video, as if it weren't fullscreen at all.   Maybe it's a different issue than #8252 or maybe it's the same, I just thought I'd give some more details.

**Comment by kbrosnan** [comment] 2020-11-02 17:52
Closing as a duplicate.

**Closed by kbrosnan** 2020-11-02 17:52 UTC
Labels: needs:triage

**Comment by Throneaway420** [comment] 2020-11-02 17:55
It's not a duplicate, though.

**Comment by s-ankur** [comment] 2020-11-02 17:58
Maybe you can add a comment to that issue detailing specific difference in your bug. Either way, when that one gets resolved this would likely be resolved as well

**Comment by Throneaway420** [comment] 2020-11-02 18:02
"Mine won't let me scroll up or down like that user claims they could, the edge is just cut off with no way to view it. However, if I attempt to load the site in desktop mode then click the fullscreen button, the video experiences the same cropping issue as before, but I can still scroll down and see the description and comments and everything else below the video, as if it weren't fullscreen at all. Maybe it's a different issue than #8252 or maybe it's the same, I just thought I'd give some more details."

I literally just posted this description 9 minutes ago. They claim they can scroll their fullscreen video, I cannot, unless I am in desktop mode in which case the video never truly fullscreens at all, I can scroll down and see related videos and comments.  It happens regardless of whether my toolbar is on top of bottom.  To me, that sounds like a different but similar issue to #8252 .  Maybe I'm wrong and it still counts as a duplicate, but whatever, it'll either get fixed or it won't.
