### ISSUE TITLE
[Bug] Add ons show up below navigation buttons in main menu

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#18770] opened 2021-04-02 18:45 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Also seen on https://www.reddit.com/r/firefox/comments/miku9o/addon_menu_moved_to_bottom_in_fenix_nightly/

## Steps to reproduce

1. Open any web site
2. Tap meatball menu

### Expected behavior

Navigation toolbar is bottom most items.

### Actual behavior

Addons show up below navigation toolbar.

![image](https://user-images.githubusercontent.com/152493/113444502-0282d800-93c2-11eb-9c6a-caec49033d2d.png)

### Device information

* Device vendor / model and Android version: Pixel 2
* Firefox for Android version: ? Nightly 210401 17:01 (Build #2015802123)
AC: 75.0.20210401143103, 90364d8de
GV: 89.0a1-20210401094845
AS: 74.0.1

**Comment by gwarser** [comment] 2021-04-02 18:56
## Expected behavior

Double-tap on main menu should reload the page.

## Actual behavior

In current menu arrangement, first menu item in my device is "Save to collection" .

**Comment by MicroBeast** [comment] 2021-04-02 21:44
When bar on top that menu come above the icons.

**Comment by cadeyrn** [comment] 2021-04-03 08:02
FYI: The regression only affects Nightly, it does not happen in debug builds where the new menu is being implemented.

**Comment by Mugurell** [comment] 2021-04-05 07:08
@eliserichards This seems to be following the the recent changes from https://github.com/mozilla-mobile/fenix/issues/17770

**Comment by lobontiumira** [comment] 2021-04-07 06:39
Verified as fixed on the 4/7 Nightly build with Samsung Galaxy Note 8 (Android 9), and HTC 10 (Android 8).

<img src="https://user-images.githubusercontent.com/40694158/113821651-0e391a80-9785-11eb-883a-8b2faafee0c8.jpg" width="300" height="550" />

**Closed by lobontiumira** 2021-04-07 06:39 UTC
Labels: Feature:MainMenu, eng:qa:needed, 🐞 bug
