### ISSUE TITLE
[Bug] Flickery transition when tapping on the back arrow from the search page

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#7374] opened 2019-12-27 13:31 UTC
## Steps to reproduce
1. Open Fenix and tap on the search bar.
2. Tap on the back arrow displayed on the top-left corner and observe.

### Expected behavior
The homescreen is displayed, the transition is done smoothly, just like switching from normal to private browsing, for example.

### Actual behavior
The homescreen is displayed, the transition is flickery.

### Device information
* Android device: Nexus 5 (Android 6.0.1), Nexus 6P (Android 8.1), Google Pixel (Android Q)
* Fenix version: latest Nightly build from 12/27 (#13610605)

![20191227_Trim](https://user-images.githubusercontent.com/40694158/71518934-e4c0ec00-28bd-11ea-98dc-45107375e0c6.gif)

**Comment by softvision-miralobontiu** [comment] 2020-02-10 14:31
I can reproduce this issue on the latest Nightly from 2\10, on Beta 3.2.0-beta.3, and on RC 3.2.1, with Google Pixel (Android 10), and Huawei P9 Lite (Android 7).
The transition should be as smooth as tapping the back arrow from Settings to Homepage.

**Comment by darkwing** [comment] 2020-02-11 23:38
When tapping back from the Settings screen to Home, my Pixel 4 appears to have no animation at all.  I look forward to hearing what @AmyYLee has to say here.

**Comment by AmyYLee** [comment] 2020-02-12 16:51
@darkwing Hi, I had previously filed a bug about the search bar animation here

https://github.com/mozilla-mobile/fenix/issues/7158

**Comment by darkwing** [comment] 2020-02-12 17:35
This is a dupe of https://github.com/mozilla-mobile/fenix/issues/7158.  Closing.

**Closed by darkwing** 2020-02-12 17:35 UTC
Labels: Feature:HomeScreen, Feature:Search, P2, S2, eng:quality, needs:UX-feedback, ux:motion-design, 🐞 bug
