### ISSUE TITLE
High resolution images are not displayed

### ISSUE THREAD

**Issue by BoldyrevEV** [mozilla-mobile/fenix#16718] opened 2020-11-23 05:22 UTC
encodeImageFileAsURL = (element) => {
        const reader = new FileReader();
        const img = new Image();
        const file = element.files[0];

        reader.onloadend = () => {
            const dataURL = reader.result;

            img.src = dataURL;

            document.getElementById('imgs3').innerHTML = '<img src="' + reader.result + '" />';
        };

        reader.readAsDataURL(file); 
    };

## Steps to reproduce
1. upload code
2. take a picture in high resolution (on my phone 4160х3120)
3. push the button "Choose button" on example page
4. view image display

### Expected behavior
The image should be displayed in <div id = "imgs3"> </div>

### Actual behavior
Image is not displayed

### Device information
* Android device: LG G6
* Firefox version: 82.1.1

**Comment by s-ankur** [comment] 2020-11-24 18:01
Related https://github.com/mozilla-mobile/fenix/issues/10232

**Comment by kbrosnan** [comment] 2020-12-02 20:43
Closing as a duplicate of bz-1680347

**Closed by kbrosnan** 2020-12-02 20:43 UTC
Labels: needs:triage, 🐞 bug
