### ISSUE TITLE
[Bug] "Desktop site" mode doesn't presist in new 79 version

### ISSUE THREAD

**Issue by ayavilevich** [mozilla-mobile/fenix#14184] opened 2020-08-25 19:27 UTC
## Steps to reproduce

Open a tab (for example google.com).
Set "Desktop site" mode.
Close Firefox (terminate app or let activity be closed by the OS).
Open Firefox. Select previously opened tab.
The "Desktop site" mode is not set. Reloading will load the mobile version or do a redirect, etc.

### Expected behavior

As in versions before 79, once a tab is marked as "Desktop site" is will stay this way until manually changed.

### Actual behavior

State is not persistent.

### Device information

* Android device: LG V30
* Fenix version: 79.0.5

**Comment by liuche** [comment] 2020-08-27 23:12
Dupe of #11552

**Closed by liuche** 2020-08-27 23:12 UTC
Labels: needs:triage, 🐞 bug
