### ISSUE TITLE
[Bug] Trying to sync account crashes app

### ISSUE THREAD

**Issue by 0purple** [mozilla-mobile/fenix#19632] opened 2021-05-24 18:22 UTC
## Steps to reproduce
Download latest Firefox Nightly
Log in to Firefox account
Try to synchronise
### Expected behavior
Data successfully synced
### Actual behavior
App crashes
### Device information

* Device vendor / model and Android version: Xiaomi Redmi 9C NFC, 2/32GB, Android 10
* Firefox for Android version: 90.0a1 (Build #2015811913)

**Comment by 0purple** [comment] 2021-05-24 18:33
Trying to add video here also crashes the app. Here is GDrive link: https://drive.google.com/file/d/1N5J_NwC1ZhjFcpoeMF2NWOfIgUGmak4G/view?usp=drivesdk

**Comment by kbrosnan** [comment] 2021-05-24 18:49
Please use `adb` to get information about this crash. https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information

**Comment by sflorean** [comment] 2021-05-25 12:24
Tested on Nightly 5/25 with Xiaomi Redmi Note 8T (Android 9) and couldn't reproduce the issue. Scenarios covered:
- sign in with QR code and sync
- sign in with account and sync
- wait and sync (30 min)
- changed password on Desktop and sync
@0purple do you have some extra steps? or maybe some different settings? thank you!

**Comment by 0purple** [comment] 2021-05-25 17:45
Retried everything, the issue doesn`t appear anymore. I think Firefox CrashReporter sent some data, maybe you could search there.

**Comment by sflorean** [comment] 2021-05-27 12:34
Closing based on the above comment, if the issue reappears please open this ticket. Thank you!

**Closed by sflorean** 2021-05-27 12:34 UTC
Labels: needs:triage, qa-triaged, 🐞 bug
