### ISSUE TITLE
Consistent design of search engines icons

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1184] opened 2019-03-25 21:20 UTC
Throughout the mocks there are various types of icons shown for search engines:

* Circle icons
* Square icons
* Background color (of an off white)
* No background color

We should decide which of these we want to use for a consistent design.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2478)

**Comment by mheubusch** [comment] 2019-04-05 20:09
@AmyYLee can you make a quick ruling on style of search provider icons - we can update comps in search screens and in settings.

**Comment by Verdi** [comment] 2019-04-08 21:48
I spoke with @shorlander about this. We decided on replicating what we do on desktop. 

![desktop-search](https://user-images.githubusercontent.com/107992/55758926-c78d7a00-5a1d-11e9-99a5-ca7f63bc20f7.png)

- So Google and DuckDuckGo use their rounded versions.
- Amazon and Ebay use a rounded rectangle
- Bing and Wikipedia are square
- Twitter has a transparent background

**Comment by vesta0** [comment] 2019-04-17 18:27
Working as intended.

**Comment by kbrosnan** [comment] 2019-04-17 21:18
In the meeting we thought Verdi's screenshot was of the Fenix UI. It is from desktop Firefox. We should verify that search partners want us to use the same icons from Desktop @mconnormoz

**Comment by kbrosnan** [comment] 2019-04-22 15:26
Mike says using the desktop icons is fine.

**Comment by sblatz** [comment] 2019-06-26 19:44
Looks like the code for generating the search engine icons is in AC (based off of `AssetsSearchEngineProvider.kt`). 

@pocmo is it possible for us to grab different assets? It seems like these are dictated by the engine codes we're using (e.g. `google-b-m`) which I don't think we can change (since it explicitly has a mobile identifier).

**Comment by mconnormoz** [comment] 2019-08-02 18:52
we can modify the underlying plugins if needed, I'd like to be consistent across all of our mobile products if at all possible.

**Comment by darkwing** [comment] 2020-02-19 21:18
I'd like to complete this task as soon as possible.  Do we still want to use the same icons for mobile as we do on desktop?  Thank you!

**Comment by AmyYLee** [comment] 2020-02-19 22:03
> I'd like to complete this task as soon as possible. Do we still want to use the same icons for mobile as we do on desktop? Thank you!

@topotropic - as she's unifying our favicons.

**Comment by topotropic** [comment] 2020-02-26 20:53
here's the favicon issue https://github.com/mozilla-mobile/fenix/issues/7992 would be nice to create a re-usable component for favicons that we can integrate here as well

**Comment by darkwing** [comment] 2020-02-28 14:12
Assigned to @gabrielluong as he's doing the AC work.

**Comment by kbrosnan** [comment] 2022-11-28 04:38
These were updated to match desktop in another issue.

**Closed by kbrosnan** 2022-11-28 04:38 UTC
Labels: feature request 🌟, eng:quality, Feature:Search
