### ISSUE TITLE
[Bug] URL panel reappears when scrolling down

### ISSUE THREAD

**Issue by jappjapp** [mozilla-mobile/fenix#16352] opened 2020-11-03 18:44 UTC
## Site with issue and any steps to reproduce
Most or all sites, e.g.:
news.ycombinator.com
https://www.raspberrypi.org/blog/raspberry-pi-400-the-70-desktop-pc/
www.dn.se
Site in video (link below): https://learnxinyminutes.com/docs/tcl/

### Expected behavior
Content scrolls smoothly. URL panel hides when scrolling down and reappears scrolling up.

### Actual behavior
URL panel reappears (abruptly, without animation) once every 10 seconds or so while scrolling down. Content does not scroll smoothlty.

Link to 100MB mp4 showing the behaviour (will remove if it gets too much traffic)
This video shows 2 jumps.
https://u.pcloud.link/publink/show?code=XZKptHXZdn6GrNVyldBFU9umrp7vVLN5coB7

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No

### Device information

* Android device: OnePlus 6
* Fenix version:
82.1.1 (Build #2015770923)
AC: 60.0.5, a1a471ddc
GV: 82.0-20201014125134
AS: 63.0.0

**Comment by ale82to** [comment] 2020-11-04 23:14
I ve always had this issue since fenenc I tought because my phone was not very powerful snapdragon 652 cpu.

**Comment by jappjapp** [comment] 2020-11-09 07:35
At first I thought just some sites show the described behaviour, but I am realizing it seems like all sites do. Also getting the impression the page reacts to the browser, and not the other way around.

Hence, relabeling to bug.

**Comment by ale82to** [comment] 2020-11-09 12:43
since fennec always behaved like this I don't think anything can be done.

**Comment by Mugurell** [comment] 2021-02-17 17:17
@jappjapp There were some changes merged in Nightly recently.
I tried to reproduce the issue described here on https://learnxinyminutes.com/docs/tcl/ but I saw no issues with the toolbar.
Does this issue still reproduces for you?

**Comment by lordgurke** [comment] 2021-06-22 11:48
On my device the current stable and the current nightly are giving the same issue.  
A demo video can be found in #19806, which is a duplicate of this.  
Is there any data I can provide to make this debuggable?

**Comment by Mugurell** [comment] 2021-06-23 11:37
Is this happening only when the toolbar is placed at the top? Or also when the toolbar is placed at the bottom?

**Comment by lordgurke** [comment] 2021-06-23 19:58
Yes, there's no change when the bar is at the bottom. When scrolling down a page, the bar pops up seemingly random.

**Comment by lordgurke** [comment] 2021-07-04 22:19
Is there any news on this?
It's really enerving — if I can help with anything, I'm happily willing to do so.

**Comment by Mugurell** [comment] 2021-07-19 07:21
This should be ready to test in the next Nightly.

**Comment by abodea** [comment] 2021-07-21 08:28
Verified as fixed on the latest Nightly 7/21 with Google Pixel 4 XL (11), Samsung Galaxy S10+ (10), OnePlus Nord (10).
Please note that I used all the 3 websites from the description but the scrolling was smooth and the URL panel appeared and disappeared when I was scrolling up or down (correctly).

**Closed by abodea** 2021-07-21 08:28 UTC
Labels: Feature:Toolbar, eng:qa:needed, qa-triaged, 🐞 bug
