### ISSUE TITLE
Browser goes back instead of searching

### ISSUE THREAD

**Issue by rommeswi** [mozilla-mobile/fenix#28057] opened 2022-12-03 06:07 UTC
### Steps to reproduce

1. Have a tab open
2. Use the awesomebar to search google for "blabla"
3. Use the awesomebar to search google for "lorem ipsum"
4. Change the search query to "lorem" in the google webpage and press "Go" on the keyboard

### Expected behaviour

Firefox shows google.com with search results for "lorem".

### Actual behaviour

Firefox shows google.com with search results for "blabla".

### Device name

Galaxy Z Flip 3

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

107.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22083)

**Comment by csadilek** [comment] 2023-01-25 17:01
I cannot reproduce this issue in 109.1.1. @rommeswi is this still a problem for you?

**Comment by csadilek** [comment] 2023-01-30 21:14
Closing as not reproducible. Please re-file if this is still a problem. Thank you!

**Closed by csadilek** 2023-01-30 21:14 UTC
Labels: 🐞 bug, needs:triage
