### ISSUE TITLE
FNX-4953 ⁃ [Bug] An about:blank is inserted in history every time you load a new website

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1318] opened 2019-04-02 13:07 UTC
## Steps to reproduce
1. Tap the search bar and type in a search/web URL.
1. Go to History.
    1. Expected behavior
The webpage is displayed in history.
    1. Actual behavior
History shows an about:blank and then the webpage loaded.
    1. Device information

* Android device: Note 8 (Android 9), Nexus 9 (Android 6.0.1)
* Fenix version: 4/2 build
![Screenshot](https://user-images.githubusercontent.com/4037709/55404835-74b94b80-5561-11e9-96ce-15232f34af76.jpg)UNITO-UNDERSCORE!20190402-160345!UNITO-UNDERSCORE!Fenix!

**Comment by vesta0** [comment] 2019-04-17 05:13
Will be addressed here: mozilla-mobile/android-components#2606

**Comment by cadeyrn** [comment] 2019-05-11 07:23
It's fixed.

**Comment by sarentz** [comment] 2019-05-17 18:59
Closing this since the fix landed a while ago and I am not able to reproduce this.

**Comment by sv-ohorvath** [comment] 2019-05-20 08:03
Verified as fixed on the 5/20 build.

**Closed** 2020-08-11 09:06 UTC
Labels: Feature:History, P1, Release Blocker, eng:qa:verified, needs:ac, 🐞 bug
