### ISSUE TITLE
[Bug] Closed in-app tabs remain in the task manager

### ISSUE THREAD

**Issue by kyouma** [mozilla-mobile/fenix#9490] opened 2020-03-28 23:08 UTC
## Steps to reproduce
1 Open a tab in in-app variant of Fenix (for example in Telegram)
2 Close it either with return button or the cross button on the top bar
3 Check the recent apps list

### Expected behavior
Closed tabs shouldn't be shown in the recent apps list.

### Actual behavior
Closed tabs remain in the recent apps list and can be opened (but still shows white screen). If they are closed with the Android "back" button, they can be reopened. If they are closed with the cross button, they show white screen.
The cross button behavior video on Yandex Cloud: https://yadi.sk/i/-1ZW4RpEkIxUOA

### Device information

* Android device: Samsung Galaxy S10e, Android 10.
* Fenix version: Preview 4.1.0 and Nightly #20880607.

**Comment by SL-Lee** [comment] 2020-03-30 14:22
Looks like a duplicate of #8902.

**Closed** 2020-08-12 15:53 UTC
Labels: needs:triage, 🐞 bug
