### ISSUE TITLE
[Bug] Favicon not saved when Fenix is closed

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#5038] opened 2019-08-30 15:21 UTC
## Steps to reproduce
- Open Fenix
- Open this page: https://blogs.mediapart.fr/karfa-sira-diallo/blog/260819/erosions-de-souad-el-maysour-conte-de-lesclavage-des-noirs-au-maghreb
- Go back to tab list and check that favicon is here:
![image](https://user-images.githubusercontent.com/218971/64032179-317ffa80-cb4a-11e9-985a-c1233bc6e3ce.png)
- Close Fenix (close the app in the app manager)
- Open Fenix again
### Expected behavior
Favicon in the tab list should be here again
### Actual behavior
Favicon is not here:
![image](https://user-images.githubusercontent.com/218971/64032341-8885cf80-cb4a-11e9-9a91-4595bdea0fba.png)

### Device information

* Android device: Redmi Note 7 with Android 9
* Fenix version: #12420615

**Comment by Mugurell** [comment] 2020-05-26 06:43
In my testing I saw favicons are persisted as expected and in this case in particular there are no issues after restarting the app.
Passing this to QA to verify if this is still an issue and close the ticket otherwise.

**Comment by klint** [comment] 2020-05-26 10:53
Actually I can see the issue still happening with build #2015742515 (with both new and current tab tray)

**Comment by ebalazs-sv** [comment] 2020-05-26 14:18
I had tested this on the latest Fenix Nightly Build 21470624, from 5/26, with Nexus 5 (Android 6.0.1), Motorola Moto G6 (Android 8), Pixel 2 (Android 9) and I could not reproduce the issue following the steps from the description and the previously mentioned pages.

@klint Please provide any additional steps for reproducing this issue. Do you leave Fenix in the background for a while before relaunching it? Thanks!

I will remove the qa:needed label for now.

**Comment by klint** [comment] 2020-05-26 15:06
The steps (that I just reproduced the issue on an other phone, a Samsung A50, and with another URL) are, as far as I can detail them:
- by any mean, navigate to https://www.lemonde.fr/planete/live/2020/05/26/coronavirus-en-direct-suivez-la-presentation-du-plan-de-soutien-a-la-filiere-automobile_6040730_3244.html in Fenix (I did it from the mail application, or from githib app, or directly by typing it in the address bar)
- once the page is loaded, click on the "Tabs" icon to go back to Fenix home page
- check that the favicon for this tab is displayed 
- immediately, display the current tasks on the phone (||| button) and remove the Fenix task -this closes Fenix I suppose
- reopen Fenix
- you should land on the home page
- check that the favicon for the above tab is not displayed (but an initial, L)

This video shows it for another URL (which actually did not work on my Redmi Note 7 but did work on the A50): https://photos.app.goo.gl/zhWcgZvy6JZLK3dV9

**Comment by ebalazs-sv** [comment] 2020-05-27 08:41
@klint Thanks for the detailed steps to reproduce this issue!
I can reproduce this on the latest Nightly Migration build 2015742705 with Motorola Moto G6 (Android 8) using sportsdirect.com.
Since this is not reproducible on the Fenix builds, this is a Migration issue.

**Comment by klint** [comment] 2020-05-27 12:44
Just asking, but is the Firefox Nightly available on Google play the migration build, while the Fenix Preview Nightly is the Fenix normal build? Thanks

**Comment by Mugurell** [comment] 2020-05-27 12:52
> Just asking, but is the Firefox Nightly available on Google play the migration build, while the Firefox Preview Nightly is the Fenix normal build? Thanks

Yes.
The difference is that Firefox Nightly is the old Firefox which got _migrated_ to Fenix.
So users of the old Firefox would get an update to Fenix and all of their data / settings will be migrated automatically to the new app.
While Firefox Preview Nightly is the standalone app that can be installed even side by side to Firefox Nightly.

In this case it would be good to know if you were a user of the old app and got migrated to Fenix or if you are a new Fenix user.

**Comment by klint** [comment] 2020-05-27 13:16
> In this case it would be good to know if you were a user of the old app and got migrated to Fenix or if you are a new Fenix user
To be true, I can't remember where my migration nightly build comes from. I mean, whether I really migrated from the former "Firefox for Android" nightly build, or I installed it from scratch. I *think* it was the latter, from scratch.

**Comment by Mugurell** [comment] 2020-05-28 16:20
I still could not reproduce this.
Giving the steps (immediately after loading the page force close the app) it seems like we are interrupted in persisting the icon to disk so when we try to load it we just generate a default one.

@ebalazs-sv can you please try to reproduce this again and if you can post here the logs filtered by "BrowserIcons"?

**Comment by klint** [comment] 2020-05-28 16:44
> Giving the steps (immediately after loading the page force close the app) it seems like we are interrupted in persisting the icon to disk so when we try to load it we just generate a default one.

Actually, the issue happens even if I wait for a couple of minutes between each step :)

**Comment by LaurentiuApahideanSV** [comment] 2020-05-29 09:11
I reproduced the issue on Nightly Migration build 2015742705 using a OnePlus 6T (Android 9) and extracted a logcat.
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4700797/logcat.txt)

**Comment by Mugurell** [comment] 2020-05-29 15:33
Small update: can consistently reproduce this and am close to the solution.
There's indeed a bug in how we persist and read the favicons from disk.

**Comment by Mugurell** [comment] 2020-06-12 11:11
Seems like this will be resolved by the same patch from https://github.com/mozilla-mobile/android-components/pull/7266

**Comment by Mugurell** [comment] 2020-06-26 15:19
With mozilla-mobile/android-components#7266 now being merged there should be no issues anymore with the favicons.

**Comment by Diana-Rus** [comment] 2020-07-02 13:17
Hi, verified as fixed with the latest Firefox Nightly migration build the favicons are now correctly displayed with Google Pixel 3XL (Android 9) and Samsung Galaxy S9 (Android 8)
- favicons from top sites
- favicons from collection
- favicons from add to home screen
- favicons from history and bookmarks
- favicons from navigation bar (text search after domain from bookmark or history)

GIF
![20200702-160516](https://user-images.githubusercontent.com/49859863/86362682-54090580-bc7e-11ea-90f7-8b1c44d98eef.gif)

**Closed** 2020-07-02 13:18 UTC
Labels: Feature:Migration, P3, eng:qa:verified, needs:ac, 🐞 bug
