### ISSUE TITLE
Undo close tab - tab appears at the top of the tab list

### ISSUE THREAD

**Issue by Noexpert** [mozilla-mobile/fenix#18359] opened 2021-03-07 22:26 UTC
In the old Firefox version, when a user selected "undo" to a recently closed tab, the re-opened tab appeared at the end of the list of tabs. With the new version, it appears at the top / start, making discoverability difficult.

**Comment by Dunexus** [comment] 2021-03-07 23:43
Duplicate of https://github.com/mozilla-mobile/fenix/issues/10986

**Comment by mcarare** [comment] 2021-03-08 11:03
Closing as duplicate of #10986.

**Closed by mcarare** 2021-03-08 11:03 UTC
Labels: needs:triage
