### ISSUE TITLE
[Bug] Playing back any video in PBM with media notification crashes the browser

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#17668] opened 2021-01-27 20:17 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Switch to PBM
2. Open any video that triggers the media notification in the browser, e.g. https://youtu.be/eYvsIenveTY or videos on https://edition.cnn.com
3. Start the playback

### Expected behavior
The video is played back.

### Actual behavior
The browser crashes immediately with the following trace:

**Nightly 210127 17:01 (Build #2015789833)**
9c9439c7-e042-4f73-af54-d305feffa570
java.lang.IllegalArgumentException: Could not process image.
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=3fbba1e50f3748aaa9ee041d5e088788
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-ca1d1100-a89b-4302-a277-ffc420210127
----
```
java.lang.IllegalArgumentException: Could not process image.
	at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(Native Method)
	at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:101)
```

**86.0.0-beta.1 (Build #2015789705)**
4e508832-597a-413c-994d-1ef84c5daffd
java.lang.IllegalArgumentException: Could not process image.
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=2304ce79928647ceade42dba344fc325
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-fa43fc4b-e101-4cff-bec1-c881c0210127
----
```
java.lang.IllegalArgumentException: Could not process image.
	at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(Native Method)
	at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:101)
```

### Device information

* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version: Nightly 210127 17:01 (Build #2015789833)
AC: 73.0.20210126190058, 004f5cfcd
GV: 87.0a1-20210126092542
AS: 67.2.0
**and**
86.0.0-beta.1 (Build #2015789705)
AC: 72.0.1, d61ba1282
GV: 86.0-20210126185730
AS: 67.2.0

**Comment by hwinnemoe** [comment] 2021-01-27 20:18
This started to happen after updating to Nightly 210127 17:01 (Build #2015789833), playback was working fine before this.

**Comment by mstange** [comment] 2021-01-27 21:04
I can reproduce this in Firefox Nightly. Playing any YouTube video in a private browsing tab crashes.
I cannot reproduce this in GeckoView-example when "Private browsing" is checked - youtube plays normally. So this may be a Fenix or AC bug.

**Comment by mstange** [comment] 2021-01-27 21:09
The error message comes from here: https://searchfox.org/mozilla-central/rev/b9384b091e901b3283ce24b6610e80699d79fd06/widget/android/ImageDecoderSupport.cpp#62

So the exception probably occurs during the [`ImageDecoder` `decode`](https://searchfox.org/mozilla-central/rev/b9384b091e901b3283ce24b6610e80699d79fd06/mobile/android/geckoview/src/main/java/org/mozilla/gecko/util/ImageDecoder.java#75) method (asynchronously).

**Comment by mstange** [comment] 2021-01-27 23:40
@rocketsroger Might this be a regression from https://github.com/mozilla-mobile/android-components/pull/9365?

**Comment by rocketsroger** [comment] 2021-01-28 00:00
> @rocketsroger Might this be a regression from [mozilla-mobile/android-components#9365](https://github.com/mozilla-mobile/android-components/pull/9365)?

Yes, I think so.  I can see that there was a permission exception on the native code when watching youtube videos in private tab.  I'll fix.  Thanks for finding the regression.

**Comment by hakkikaancaliskan** [comment] 2021-01-28 09:13
@rocketsroger I get exact same error on fb.gg (in desktop mode) on Normal browsing mode

86-beta1

**Comment by pocmo** [comment] 2021-01-28 09:38
Patch is about to land in Android Components and should go out with one of the next Nightly versions.

@rocketsroger Can you test whether the beta branch is affected by this? If yes then we may need to uplift this to create a matching AC dot release.

**Comment by pocmo** [comment] 2021-01-28 09:39
> @rocketsroger Can you test whether the beta branch is affected by this? If yes then we may need to uplift this to create a matching AC dot release.

Ah, I see in the first comment that Beta is affected too, yeah, let's uplift.

**Comment by AndiAJ** [comment] 2021-01-28 09:52
Reproducible on both **`Nightly 210128`** and **`Beta 86.0.0-beta.1`** using a OnePlus A3 (Android 6.0.1)  when trying to play any of the featured songs from soundcloud's home page.

► Video
![20210128-114359](https://user-images.githubusercontent.com/51314259/106120633-460d5b80-615f-11eb-8f6c-cbaffd2fc886.gif)


2ad3d3c6-f9ee-417b-8e2b-191e0f9321fb
java.lang.IllegalArgumentException: Could not process image.
* Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=8201c8fcebbd45ec926ffe8fcebfd091
* Socorro: https://crash-stats.mozilla.org/report/index/bp-71d638f2-62e4-421c-b79e-7c0ab0210128
----
java.lang.IllegalArgumentException: Could not process image.
at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(Native Method)
at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:101)

**Comment by hwinnemoe** [comment] 2021-01-28 10:33
We may need to create new issues to track that the crashes in normal browsing mode also have stopped.

**Comment by softvision-miralobontiu** [comment] 2021-01-28 12:30
We were able to reproduce this crash also on http://www.cnbc.com/2017/07/20/tesla-adding-this-ceo-to-its-board-is-a-big-deal-for-silicon-valley.html when playing the video on the 1/27 Nightly build with multiple devices:
* Samsung Galaxy S8 (Android 9)
* Huawei P20 Lite (Android 8)
* Samsung Galaxy S6 Edge (Android 7.0)
* Samsung Galaxy Note 8 (Android 9)

21e53933-2fae-4f82-a1ff-1a38e9642031
java.lang.IllegalArgumentException: Could not process image.
* Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=1e0d31d8069a43fca2fd29c84b174e61
* Socorro: https://crash-stats.mozilla.org/report/index/bp-1bc0f746-578b-43cd-99d8-b00020210128

**Comment by rocketsroger** [comment] 2021-01-28 15:45
> We were able to reproduce this crash also on http://www.cnbc.com/2017/07/20/tesla-adding-this-ceo-to-its-board-is-a-big-deal-for-silicon-valley.html when playing the video on the 1/27 Nightly build with multiple devices in NORMAL browsing:

Thanks I'll make sure the fix works on CNBC as well.  This should be reproducible on any video stream that includes artwork.

**Comment by rocketsroger** [comment] 2021-01-28 23:17
Both the next Nightly and Beta will have this fix.  Please verify. Thanks

**Comment by softvision-miralobontiu** [comment] 2021-01-29 13:08
Still reproducible on the 1/29 Nightly build.
Tested on the soundcloud.com page, and on cnbc.com page.

**Comment by rocketsroger** [comment] 2021-01-29 19:28
> Still reproducible on the 1/29 Nightly build.
> Tested on the soundcloud.com page, and on cnbc.com page.

Issue created https://github.com/mozilla-mobile/android-components/issues/9556.  Not related to this PBM issue. This is when GV image processing could throw an exception.  But since it is similar I'll update once the fix is in for retest.  Thanks!

**Comment by rocketsroger** [comment] 2021-01-29 20:19
@softvision-miralobontiu After some investigation 1/29 Nightly build only picked up one of the two fixes for the crash.  1/30 Nightly build should have both the PBM Youtube crash and the CNBC/Soundcloud crash.  Please verify next Monday when you have a chance.  Thanks!

**Comment by softvision-miralobontiu** [comment] 2021-02-01 09:45
Verified as fixed on the 2/1 Firefox Nightly build with Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy Note 8 (Android 9).
I've played multiple videos, both in normal and private browsing, from cnn.com, cnbc.com, youtube.com, soundcloud.com.
Thanks!

**Closed by softvision-miralobontiu** 2021-02-01 09:45 UTC
Labels: Beta, b:crash, eng:qa:needed, needs:ac, needs:triage, 🐞 bug
