### ISSUE TITLE
[Bug] pdf or excel files are less Kb size

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#14583] opened 2020-09-01 16:41 UTC
## Steps to reproduce
Login to hdfc netbanking page, download account statement in pdf or excel. The downloaded file is 1.57KB or less than actual size. 
Works fine with edge

### Expected behavior
Files should download properly 

### Actual behavior
Files are of less size around 1kb

### Device information

* Android device: ? Rog 3
* Fenix version: ? Latest

**Comment by hwinnemoe** [comment] 2020-09-15 10:56
Duplicate of/Related to #7531

**Comment by kbrosnan** [comment] 2020-09-23 23:29
Yes this is us downloading something like a html error page instead of the correct document. Closing as a duplicate.

**Closed by kbrosnan** 2020-09-23 23:29 UTC
Labels: Feature:Download, 🐞 bug
