### ISSUE TITLE
Update "remove account" button in FxA error state to "force auth"

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2833] opened 2019-05-24 17:35 UTC
Currently our "remove account" button when in an error state just has the same behavior as signing the user out (when we go to sign back in, the email is remembered). According to @ryanfeeley, we actually want to "force auth" them on the next sign in and forget their username. The API for this does not exist yet according to @vladikoff.

[See full Slack conversation](https://mozilla.slack.com/archives/CG2FGG1ST/p1558652787183500).

**Comment by rfk** [comment] 2019-05-26 23:50
> we actually want to "force auth" them on the next sign in and forget their username. 

To clarify, I think "forget their username" is not what we want. The two options from a signin error state should be:

* Re-authenticate as the same user that was already signed in on the browser.
* Completely sign out of the browser.

What do don't want is for them to sign in to some other unrelated account, because it might result in them accidentally syncing the history and bookmarks from one account over to another.  Hence "force auth" in this context means "force the user to sign in to a specific account, or not at all".

**Comment by liuche** [comment] 2019-07-17 20:01
@bifleming said Janet said this is ready on the AS side, will leave summary.

**Comment by bifleming** [comment] 2019-07-18 18:42
Confirmed that the a-s work for this is done: https://github.com/mozilla/application-services/issues/1196

**Comment by jdragojevic** [comment] 2019-07-18 19:05
For clarity - it's available in a-s 0.35.0

**Comment by sblatz** [comment] 2019-07-22 18:34
Sounds like we're blocked on A-C then to upgrade their AS version number. I'm reaching out to them to see what we can do :)

**Comment by sblatz** [comment] 2019-07-22 19:41
@jonalmeida mentioned there are lots of breaking changes for AC to resolve when upgrading, so we may be waiting on this for a while.

**Comment by sblatz** [comment] 2019-07-22 20:23
Looks like there's an AC PR right now 🤔 https://github.com/mozilla-mobile/android-components/pull/3806

**Comment by vesta0** [comment] 2019-07-29 17:28
Waiting for Fenix to be updated to the new A-C version.

**Comment by sblatz** [comment] 2019-08-05 17:47
This is no longer waiting since https://github.com/mozilla-mobile/android-components/pull/3806/ was merged in!

**Comment by sblatz** [comment] 2019-08-05 18:22
Hmm this looks like it's still waiting on AC to give us hooks. I'm going to file an issue for it and bubble it up as a high priority.

**Comment by sblatz** [comment] 2019-08-05 18:38
@vesta0 is this supposed to be in our current sprint? I didn't even notice that it got removed at some point even though it was in our last one.

**Comment by vesta0** [comment] 2019-08-06 16:43
A-C issue: https://github.com/mozilla-mobile/android-components/issues/4027

**Comment by vladikoff** [comment] 2019-08-06 17:14
from a-s:

> - The `FirefoxAccount.beginOAuthFlow` method will redirect to a content page that
  forces the user to connect to the last seen user email. To avoid this behavior,
  a new `FirefoxAccount` instance with a new persisted state must be created.

@grigoryk do you need any changes in a-c to handle this new behaviour?

**Comment by vesta0** [comment] 2019-12-17 21:10
What is the status of this bug? I believe this is done.

**Comment by sblatz** [comment] 2019-12-27 22:26
@rocketsroger :)

**Comment by rocketsroger** [comment] 2019-12-27 22:28
@vesta0 Yes, by default account is now removed when user logs out.

**Comment by AndiAJ** [comment] 2019-12-30 08:52
Hi this is **still reproducible** on the latest **Nightly Build #13640626 from 12/30** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1) 

► Video
![20191230_103409](https://user-images.githubusercontent.com/51314259/71574660-66995b00-2af2-11ea-9643-393aad6d42d4.gif)

I'll remove the QA needed label until further notice.

**Comment by jdragojevic** [comment] 2019-12-30 18:38
@AndiAJ  - can you please clarify what you mean by still reproducible means.  There's two comments the initial description (24-May) and the clarification by Ryan Kelly (26-May).  @vesta0 can you please confirm the desired behavior.

**Comment by rocketsroger** [comment] 2019-12-30 21:29
One thing to add.  I've confirmed the behavior on Fenix nightly.  But with reference browser the last signed in email is not cached.

**Comment by sblatz** [comment] 2020-01-03 21:07
@rocketsroger does that mean we need to make a change in Fenix?

**Comment by rocketsroger** [comment] 2020-01-03 21:10
> @rocketsroger does that mean we need to make a change in Fenix?

Sorry, I haven't looked into it yet.  My guess would be yes.  Could be as simple as making the same call as the reference browser.

**Comment by rocketsroger** [comment] 2020-01-22 20:29
@sblatz Just revisited this on reference browser and it now shows the same issue as Fenix.  Last signed in FxA email address is cached.  Not sure what happened last time I tested this.  But as of today both Reference Browser and Fenix have the same behavior.

I'll have to rescind my last statement.  The required fix is probably still in A-C or lower.

**Comment by sblatz** [comment] 2020-01-22 20:32
@vesta0, @rfk is this something we still want to do? Clear the cache of the email when a user logs out?

**Comment by rfk** [comment] 2020-01-22 21:16
>  Clear the cache of the email when a user logs out?

I don't think we need this. The same behaviour reproduces on desktop - sign in, sign out, and go to sign back in again and it will default to remembering your previous email address.  As long as it's actually prompting you for the account password (rather than, say, still being signed in to accounts.firefox.com even though you signed out of the browser) then I think we can just close this.

(There's some other stuff in my earlier comments about a completely different behaviour around what to do in an error state, but we can bring that back as a separate bug if/when we decide the current behavior around error states is not sufficient)

**Comment by vesta0** [comment] 2020-01-23 20:35
I don't think we need to clear cache after user signs out but I thought this ticket was about the "remove account" event which is different, is that not the case?

**Comment by rfk** [comment] 2020-01-23 22:45
The equivalent "remove account" option on desktop also does not clear cache, doing "remove account" and then going to sign in again will default to prompting you with the same account you used previously. So I don't think we need to worry about it for Fenix either.

**Comment by boek** [comment] 2020-02-04 18:51
@vesta0 @rfk It sounds like this is working as intended. Can we close this now?

**Comment by rfk** [comment] 2020-02-04 20:48
I support closing this issue.

**Comment by vesta0** [comment] 2020-02-04 20:51
Yes, thank you!

**Comment by data-sync-user** [comment] 2020-08-11 12:57
➤ Vesta Zare commented:

Waiting for Fenix to be updated to the new A-C version.

**Closed** 2020-08-26 20:25 UTC
Labels: E2, Feature:Sync, needs:ac, should
