### ISSUE TITLE
[Bug] Language switcher issues when selecting an unsupported Android language

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/fenix#8370] opened 2020-02-13 06:00 UTC
Open the language switcher, then switch to Corsican (co). Two things will happen:
- The language name is now displayed as `co`.
- For all other language, the localized names are missing and the language code is displayed instead.

I assume this is due to Corsican not being available in Android. I wonder if there's a way to fail more gracefully, for example showing the device's language as a fallback?

### Before

![Screenshot_20200213-065314](https://user-images.githubusercontent.com/3644868/74405882-82508a80-4e2e-11ea-9db0-da0d41b9d766.jpg)

### After

![Screenshot_20200213-065624](https://user-images.githubusercontent.com/3644868/74405892-8bd9f280-4e2e-11ea-9874-d1c635f7ed47.jpg)

**Comment by Patriccollu** [comment] 2020-02-13 14:27
Thanks for taking this issue into account.

Patriccollu.

**Comment by Patriccollu** [comment] 2021-05-17 16:14
@flodolo 
The display has changed and it's far better! But there is an extra - and unexpected - **comma** :-(

![Corsican language on Fenix](https://user-images.githubusercontent.com/22452654/118521537-6deaf400-b73b-11eb-9c1e-d1a1979c71d7.jpg)

**Comment by flodolo** [comment] 2021-05-17 16:34
CC @Delphine (I'm not in charge of Fenix, so no idea how that list is generated, or why there's a comma only for Corsican)

**Comment by Patriccollu** [comment] 2021-05-17 16:36
Looks to be caused by this statement:
https://github.com/mozilla-mobile/fenix/blob/fca8fca4464f0153bf6104ce3e09bd0ddf0c9e1b/app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleViewHolders.kt#L80

**Comment by Delphine** [comment] 2021-05-18 19:18
I think @mcarare may be able to help with this?

**Comment by mcarare** [comment] 2021-05-19 07:26
@Delphine I put up a fix here: https://github.com/mozilla-mobile/fenix/pull/19555.

**Comment by mcarare** [comment] 2021-05-19 11:15
This should be fixed in the next NIghtly.

**Comment by lobontiumira** [comment] 2021-05-20 07:04
Verified as fixed on the 5/20 Nightly build with Samsung Galaxy Tab A6 (Android 5.1.1), Sony Xperia Z5 Premium (Android 7.1.1), and OnePlus 5T (Android 10).

**Closed by lobontiumira** 2021-05-20 07:04 UTC
Labels: Feature:Settings, eng:qa:needed, 🌐 L10N, 🐞 bug
