### ISSUE TITLE
Put the old V68 as Firefox Classic into the Play Store

### ISSUE THREAD

**Issue by U-B-Glade** [mozilla-mobile/fenix#14189] opened 2020-08-25 20:06 UTC
### What is the user problem or growth opportunity you want to see solved?
The new UI is unusable by many user
Many uninstall FF for ever (me to)
You and me may learn what User really like

### How do you know that this problem exists today? Why is this important?
Look to the Play Store Reviews
For me the new UI is unusable, more Klicks less Features

### Who will benefit from it?
The Project
You
The User
The free Internet

**Comment by hwinnemoe** [comment] 2020-08-27 22:47
Duplicate of #14188

**Closed** 2020-08-27 23:16 UTC
