### ISSUE TITLE
[Bug] open in app, app not installed

### ISSUE THREAD

**Issue by Djfe** [mozilla-mobile/fenix#4578] opened 2019-08-07 07:57 UTC
## Steps to reproduce
Uninstall reddit in-case it's installed
Open https://www.reddit.com/r/de/
Click "open in reddit" (link on the website. overlay at the bottom of the viewport)

### Expected behavior
Fenix opens the play store so the user can install the correct app to open link.
(or first the dialogue to choose between stores is shown, like in current Firefox for Android, it allows me to choose between the play store and fdroid)

### Actual behavior
nothing happens

### Device information
* Android device: OnePlus 3T
* Fenix version: 69.0-20190805070043

**Comment by Djfe** [comment] 2019-08-07 07:59
The same happens (nothing) when I click "Open In App" from the websites context-menu.

**Comment by matfantinel** [comment] 2019-08-13 00:39
Seems like a general issue with opening intents. I have a third party app that opens Reddit links and it opens correctly with Chrome, Brave and other Android browsers.

**Comment by NotWoods** [comment] 2019-12-23 07:50
Duplicate of #7101.

**Closed by NotWoods** 2019-12-23 07:50 UTC
Labels: 🐞 bug
