### ISSUE TITLE
[Bug]: (Copy) Performing a Search on selected text is failing the second time

### ISSUE THREAD

**Issue by yamanq** [mozilla-mobile/fenix#20879] opened 2021-08-17 02:53 UTC
### Steps to reproduce

1. Select text, press Search from context menu
2. Either navigate back, or close tab and reopen previous tab
3. Scroll the screen if context menu disappeared (This menu being hidden seems like another standalone issue)
4. Tap Search again

### Expected behaviour

Either search in a new tab or return to inactive search tab linked to it.

### Actual behaviour

Nothing happens.

### Device name

Google Pixel 2

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

93.0a1 (Build #2015828427)

### Additional information

This issue was previously created by another reporter but was deleted without notice. You can see a reference to the issue here: https://github.com/mozilla-mobile/fenix/issues/19982 (The deleted issue being #19363).

Is there a reason this bug was deleted?

The following device information was also tested:
- Android 11 Google Pixel 2 with Firefox 91.1.0
- Android 11 Samsung One UI 3.1 with Firefox for Android version: 88.1.2
- Android 7.0 Huawei P9 (EVA-L09) with Firefox 89.1.1

**Comment by SoftVision-LorandJanos** [comment] 2021-08-18 11:58
Hi @yamanq ! Thank you for your report!
I can reproduce the issue you described.

I don't know the reason why that bug was deleted but I did find another one that covers the issue you described (even if not with the same steps but it should cover the problem that causes it): #18565.
As the main issue will be covered in the above mentioned bug, I will close this one as duplicate.

Verified on the latest Release (RC91.2.0).
Device used: Xiaomi Mi11 Lite (Android 11).

**Closed by SoftVision-LorandJanos** 2021-08-18 11:58 UTC
Labels: 🐞 bug, needs:triage
