### ISSUE TITLE
FNX-5456 ⁃ [Bug] Notification bar has poor contrast on HTC Desire 820 (Android 6.0.1)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2101] opened 2019-04-26 22:32 UTC
## Steps to reproduce
1. Open Fenix on Moto G

### Expected behavior
Good contrast in notification bar. Items should be visible without squinting. 

### Actual behavior
Very low contrast in notification bar, almost impossible to see icons. 

![Screenshot](https://user-images.githubusercontent.com/152493/56839678-a4522f80-6851-11e9-83f9-70cf10c1e67f.png)UNITO-UNDERSCORE!2019-04-26-18-26-32!

### Device information
* Android device: Moto G
* Fenix version: latest from play store

**Comment by reinhart1010** [comment] 2019-04-27 06:15
I'd rather call this as a regression. You can see the difference with older builds.

![Screenshot_20190427-130558_Firefox Preview](https://user-images.githubusercontent.com/17312341/56845605-24c66e00-68ee-11e9-9bb0-1062f302f0d4.jpg)


![Screenshot_20190427-130640_Fenix](https://user-images.githubusercontent.com/17312341/56845588-f47ecf80-68ed-11e9-87e8-bbd87de202c2.jpg)

Compared with Fennec:

![Screenshot_20190427-131022_Firefox](https://user-images.githubusercontent.com/17312341/56845632-7a027f80-68ee-11e9-9fb9-c1dee286e2a8.jpg)

**Comment by yoasif** [comment] 2019-04-27 06:21
@reinhart1010 Are you on a Moto G?

Also, I am talking about the notification bar, not the navigation bar - I don't see any issue in the notification bar in any of the screenshots you posted.

**Comment by reinhart1010** [comment] 2019-04-27 07:11
Oh, so that's a different issue. This case I'm running Samsung, probably affecting Android 7.0 to 9.0.

Besides that, do your device run on Android Lollipop (5.0)? The dark notification bar icons are supported since Marshmallow (6.0).

**Comment by yoasif** [comment] 2019-04-27 07:32
My Moto G is running Android 5.1.

**Comment by ekager** [comment] 2019-05-13 20:46
Hi @yoasif is this still an issue?

**Comment by yoasif** [comment] 2019-05-13 21:03
@ekager, as of build #11310606, it is still an issue.

**Comment by ekager** [comment] 2019-05-13 22:40
Thanks, let me take another look

**Comment by sv-ohorvath** [comment] 2019-05-15 13:44
@ekager This is still an issue on an HTC Desire 820 (Android 6.0.1), but not on a Nexus 5  (Android 6.0.1) or Oneplus Two (Android 6.0.1) - API 23 🤔 
build: 5/15.

**Comment by yoasif** [comment] 2019-05-15 16:07
The issue is resolved on my Moto G, at least.

**Comment by ekager** [comment] 2019-05-17 20:44
Interesting that it's only the HTC device. See also #1998 where an HTC device is having issues with our window flags.

**Comment by boek** [comment] 2019-05-29 22:11
I don't think we can fix this unless we can get access to an HTC device where we can reproduce the issue. @vesta0 @bifleming

**Comment by kbrosnan** [comment] 2019-05-29 23:03
Could not reproduce using a HTC One A9 or HTC 10 HTV32 on Android 6.0. Tried a HTC J butterfly HTL23 running Android 5.0 without success.

**Comment by vesta0** [comment] 2019-05-31 00:51
Closing based on feedback from @kbrosnan

**Closed** 2020-08-11 13:53 UTC
Labels: Feature:AndroidIntegration, P1, Release Blocker, needs:investigation, 🐞 bug, 🙅 waiting
