### ISSUE TITLE
[Bug] URL bar shows incorrect data

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7632] opened 2020-01-12 23:28 UTC
## Steps to reproduce

1. open fresh browser without any tabs
2. open any URL -> it's opened (OK)
3. enter "test" in URL bar -> it opens Google with test (at least I tested with Google; OK)
4. press back button -> url from point 2 is opened (OK)
5. click on url bar -> it shows word from step 3 (BAD)

### Expected behavior
in 5 we see URL from step 2

### Actual behavior
in 5 we see word from step 3

### Device information

* Android device: Samsung S7/Android 8
* Fenix version: nightly 12 jan

**Comment by sv-sdeiac** [comment] 2020-01-13 09:13
Hello, I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 1/13 #20130605. 
Also, I tried with the latest version of Firefox Preview RC 3.0.2 and the issue is not reproducible.

Devices:
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8);
- Google Pixel 2 (Android 9);
- Google Pixel (Android Q).

**Comment by codrut-topliceanu** [comment] 2020-03-02 14:40
**Cause:**
There is a variable called `searchTerms` on each tab's session that stores the last used terms and it never gets deleted, only overwritten. And `searchTerms` takes precedence over the url value when being displayed in the search fragment toolbar.

**Solution:**
Clear `searchTerms` when `onBackPressed()` gets called and only if it triggers back navigation in webView, thus replicating Fennec behaviour. However navigating forward will not restore previously used search terms. 

Fix done. PR incoming.

**Comment by vesta0** [comment] 2020-04-23 14:02
@codrut-topliceanu was this fixed?

**Comment by codrut-topliceanu** [comment] 2020-04-23 14:15
@vesta0 Yep, should be fixed.

**Comment by sv-sdeiac** [comment] 2020-04-24 11:26
Hi, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 4/24 #21150607.

Devices:
- Google Pixel (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG G7 fit (Android 8.1).

**Closed by sv-sdeiac** 2020-04-24 11:26 UTC
Labels: Feature:Browser, Feature:Search, P2, S2, eng:qa:needed, 🐞 bug
