### ISSUE TITLE
[Bug] Firefix crashes Android System on Internet Connection

### ISSUE THREAD

**Issue by iosifsecheleadan** [mozilla-mobile/fenix#19338] opened 2021-05-01 10:19 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

- I'll specify up front, I'm using LineageOS, because that's likely the root of the issue. 
- Bug can be reproduced with new profile.
- Crash happens on both regular Firefox and Firefox Nightly.

## Steps to reproduce

1. Open the Firefox app. 
2. Connect to the Internet (wifi or data). 

OR 

1. Connect to the Internet (wifi or data). 
2. Open the Firefox app.

OR 

1. Open the Firefox app.
2. Close the Firefox app and delete from recently opened apps.
3. Connect to the Internet (wifi or data). 

### Expected behavior

System doesn't crash when connecting to the internet. 

### Actual behavior

The System reboots a few seconds after the Firefox app is active (either open or in the recently opened apps), with an active internet connection. 

If I first open the app, without an active internet connection, I can interact with it with no problems. I can enter settings, scan the QR code for Sync, and anything else. The crash only appears when connecting to the internet. 

### Device information

- Model : Sony Xperia Z
- Android version : 8.1.0
- LineageOS version : 15.1-20200131-NIGHTLY-yuga

Firefox Daily info

- 88.1.2 (Build #2015806937)
- AC: 74.0.12, cad1e5a98
- GV: 88.0.1-20210426133657
- AS: 74.0.1

Firefox Nightly info

- 90.0a1 (Build #2015807689)
- AC: 90.0.20210430143137, 699977fb1
- GV: 90.0a1-20210430092829
- AS: 75.2.0

### Additional info

I tried looking through logcat but (as far as I can see) the system seems to be acting normally until it crashes. If necessary I can provide logs or any additional system information.

**Comment by kbrosnan** [comment] 2021-05-01 19:58
Duplicate of https://github.com/mozilla-mobile/fenix/issues/5663 

The developer of the ROM needs to apply the patch mentioned near the end of the issue.

**Closed by kbrosnan** 2021-05-01 19:58 UTC
Labels: needs:triage, 🐞 bug
