### ISSUE TITLE
[Bug] Firefox includes two windows in the Android 11 app switcher

### ISSUE THREAD

**Issue by chrishub188** [mozilla-mobile/fenix#15044] opened 2020-09-13 13:17 UTC
## Steps to reproduce

1. Open Firefox by tapping on its icon.
2. Perform system gesture to show the Android app switcher.

### Expected behavior
One Firefox window is displayed in the Android  app switcher. Only one window needs to be removed to close the app.

### Actual behavior
Two Firefox windows are displayed in the Android app switcher. Both need to be removed to close the App. 

### Device information

* Android device: Pixel 4 (Android 11)
* Fenix version: 80.1.3 (Build #2015762835)

![Screenshot_1599997122440~2.jpg](https://user-images.githubusercontent.com/63286554/93018909-ad24dc00-f5d3-11ea-9861-5eb8098b1f26.jpg)

**Comment by hwinnemoe** [comment] 2020-09-13 13:22
Duplicate of #13270

**Comment by kbrosnan** [comment] 2020-09-21 17:42
Closing as a duplicate

**Closed by kbrosnan** 2020-09-21 17:42 UTC
Labels: needs:triage, 🐞 bug
