### ISSUE TITLE
[Bug] Fullscreen Video is clipped vertically on Pixel 4a

### ISSUE THREAD

**Issue by smarkwell** [mozilla-mobile/fenix#17767] opened 2021-02-02 17:55 UTC
## Steps to reproduce

* With a Pixel 4a
* Open a video on YouTube ( https://m.youtube.com/watch?v=y2CsKbgcK4M )
* Start the video then pause it.  It is easier to compare the clipping when the video is paused, although the clipping happens either way.
* Note what is visible in the bottom 1/10 of the frame.
* Now make the video fullscreen.
* Make sure the video is in landscape rotation.
* The bottom section of the frame is clipped/off screen.

### Expected behavior

The video should not extend beyond the bottom edge of the screen or into the curved edge of the screen.

### Actual behavior

The lower 1/10 (approx) portion of the video is cropped while in fullscreen.

Youtube page, with the video not fullscreen.

![Screenshot_20210202-100210](https://user-images.githubusercontent.com/29174/106642950-df60b700-653d-11eb-86b8-e2a277c55d93.png)

Fullscreen video in landscape.  Note, the Pixel 4a has a camera punch out so the black bar on the left is expected.  In reality there should also be a black bar on the right keeping the video away from the screens curves edge as well.

![Screenshot_20210202-100221](https://user-images.githubusercontent.com/29174/106643050-01f2d000-653e-11eb-9a17-1b77cb4ae8b0.png)

This seems to be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1605043

### Device information

* Device vendor / model and Android version: Google Pixel 4a
* Firefox for Android version: 

Nightly 210201 17:01 (Build #2015790795)
AC: 73.0.20210131143119, 697903231
GV: 87.0a1-20210129095945
AS: 69.0.0

**Comment by Dunexus** [comment] 2021-02-02 18:53
Duplicate of https://github.com/mozilla-mobile/fenix/issues/8252

**Comment by Gorilla20** [comment] 2021-02-16 05:07
I had this exact problem. Try enabling full screen mode through your phone's setting. 
Display > full screen apps > enable Firefox

**Comment by kevincox** [comment] 2021-03-11 12:20
My phone (also a Pixel 4a) does not have that setting.

**Comment by yaomtc** [comment] 2021-08-12 14:13
Nor mine.

Also, Vimeo's controls are totally cut off from the full screen view.

https://vimeo.com/585797977

![Screenshot_20210812-101006](https://user-images.githubusercontent.com/5534045/129212356-7df5a7a6-d20a-4f60-b2e3-a1eca59dd22e.png)
![Screenshot_20210812-101022](https://user-images.githubusercontent.com/5534045/129212361-83e9b833-470f-4937-8532-91c9544fe9e0.png)
![Screenshot_20210812-101038](https://user-images.githubusercontent.com/5534045/129212364-3aae7c0c-867f-40f5-9651-b773d3e27095.png)

**Closed** 2022-02-17 00:53 UTC
Labels: 🐞 bug, Feature:Toolbar, Feature:Media, wontfix
