### ISSUE TITLE
[Bug] Ublock origin, My filters, can't do copy paste on My filters

### ISSUE THREAD

**Issue by wijayafamily** [mozilla-mobile/fenix#9842] opened 2020-04-10 01:36 UTC
## Steps to reproduce
1.Settings
2.Add-ons
3.uBlock origin
4.Settings
5.My filters
6.long press on any address
### Expected behavior
it will highlight the text and copy, select all, other functions will show up, firefox preview 4.2.1 got this right, firefox preview nightly 4 builds ago also got this right.
### Actual behavior
nothing happened
### Device information

* Android device: SM-N960F, Android 10, april patch
* Fenix version: Nightly 200405 18:01

**Comment by ybhmr4s11** [comment] 2020-05-18 15:30
https://github.com/mozilla-mobile/fenix/issues/10719

**Comment by gorhill** [comment] 2020-05-18 21:06
I could not reproduce with Nightly 200517 06:01 (Build #21380606). Long pressing the editor area brought the menu from where I was offered the choice to Cut / Copy / Paste / Select All / ...

**Comment by kbrosnan** [comment] 2020-05-27 04:28
Closing as not able to reproduce.

**Closed by kbrosnan** 2020-05-27 04:28 UTC
Labels: Feature:WebExtensions, 🐞 bug
