### ISSUE TITLE
The HTMLVideoElement in fullscreen mode is oversize

### ISSUE THREAD

**Issue by Lanius-collaris** [mozilla-mobile/fenix#17271] opened 2020-12-31 19:45 UTC
## Site with issue and any steps to reproduce
Visit https://hls-js.netlify.app/demo/
Then click the fullscreen button.
### Actual behavior
The HTMLVideoElement in fullscreen mode is oversize.
![Screenshot_20210101_030957_org mozilla fenix](https://user-images.githubusercontent.com/55432068/103423672-dbf6aa80-4be2-11eb-90af-0c969fc2dc4e.jpg)

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No
### Can you reproduce in Chrome (or other non-Mozilla browser)?
No

### Device information

* Android device: android 10 huawei SEA-AL10
* Fenix version: Nightly 201230 17:00 (Build #2015784459)

**Comment by Dunexus** [comment] 2021-01-02 11:09
Seems like the same issue as https://github.com/mozilla-mobile/fenix/issues/8252

**Comment by LaurentiuApahideanSV** [comment] 2021-01-04 12:40
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/8252, I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-01-04 12:40 UTC
Labels: needs:triage
