### ISSUE TITLE
[webcontent] Wikipedia Forwarding: Missing browser title (Bugzilla 1716315)

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#20183] opened 2021-06-26 20:31 UTC
[Emily Toop (:fluffyemily)](https://bugzilla.mozilla.org/user_profile?user_id=540010)  told me to copy this issue here to GitHub: https://bugzilla.mozilla.org/show_bug.cgi?id=1716315

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16923)

**Comment by WebworkrNet** [comment] 2021-06-26 20:35
Steps to reproduce:

If a Wikipedia page redirects to another page,
the title bar of the browser remains empty.

Sample:
https://de.wikipedia.org/wiki/Internet_Go_Server
redirects to
https://de.wikipedia.org/wiki/Pandanet

Samsung Galaxy XCover 4S, Android 10
Firefox for Android version: 89.1.1 (Build #2015812947)
AC: 75.0.22, 5204f4025
GV: 89.0-20210527174632
AS: 74.0.1

According to https://phabricator.wikimedia.org/T284884,
this is probably not a general problem, but depends on the device.

Actual results:

Browser title is missing.

Expected results:

Browser title is displayed.

**Comment by WebworkrNet** [comment] 2021-06-26 20:37
Bookmark dialog

![20210614_003043](https://user-images.githubusercontent.com/43509007/123525134-f364ab00-d6ce-11eb-9db1-d50dcc56fe55.jpg)

**Comment by WebworkrNet** [comment] 2021-06-26 20:37
The behavior cannot be reproduced under Google Chrome 91.0.4472.101. The title is displayed correctly.

**Comment by SoftVision-LorandJanos** [comment] 2021-06-28 11:10
Hi @WebworkrNet ! Thank you for your report! As this issue seems to be device dependent I can list a few devices I cannot reproduce it on: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0), all tested with the above mention release version (89.1.1) and latest Nightly (91.0a1 - 2021-06-28T05:09:42.643). I will ask a colleague with identical or at least similar device (and Android) to try to reproduce it. Thank you!

**Comment by mcarare** [comment] 2021-06-29 13:24
I can reproduce this on Fenix and not on the GV example app. After the redirect, when we update `TabSessionState` content, multiple times while the page is loading, we seem to lose the title GV provides, or when we finish page loading, GV does not provide any title. This needs some more investigation.

**Comment by WebworkrNet** [comment] 2021-07-01 13:24
Brief question: What does GV stand for and what is the GV sample app? Thanks :-)

**Comment by mcarare** [comment] 2021-07-01 13:53
> Brief question: What does GV stand for and what is the GV sample app? Thanks :-)

GV is Gecko View and the GV example app is a simplistic GV-based browser used to test GV.

**Comment by WebworkrNet** [comment] 2021-07-04 01:23
I just noticed that the phenomenon also occurs when switching between two Wikipedia pages (back & forward).

**Comment by WebworkrNet** [comment] 2022-01-01 07:32
The error still exists.

**Comment by SoftVision-LorandJanos** [comment] 2022-11-24 13:53
Hi @WebworkrNet! Is this still reproducible for you using the latest builds?

**Comment by WebworkrNet** [comment] 2022-11-25 00:10
I'll be watching to see if the case reoccurs when redirecting within Wikipedia. In the meantime, however, I have a newer Samsung model in use. The previous device unfortunately stopped working.

**Comment by WebworkrNet** [comment] 2022-11-25 08:24
Problem still occurs.

**Device**: Samsung Galaxy A13 5G (SM-A136B/DSN)
**Operating System**: Android 12

**Firefox Nightly**
109.0a1 (Build #2015917801), 2d04c13c5+
AC: 109.0.20221124143318, 11c59eb927
GV: 109.0a1-20221124093251
AS: 96.0.1

**Comment by jonalmeida** [comment] 2023-01-27 21:50
Instead of migrating this bug over, I've re-opened BZ-1716315. Closing.

**Closed by jonalmeida** 2023-01-27 21:50 UTC
Labels: needs:investigation, Feature:Browsing, needs:triage, qa-triaged
