### ISSUE TITLE
FNX2-13686 ⁃ [Bug] Not all devices are displayed on Synced tabs

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#11950] opened 2020-06-25 13:57 UTC
## Steps to reproduce
1. Sign in with the same account on multiple devices - I had 2 mobile devices and desktop.
1. Trigger sync, then go to Settings - Synced tabs and observe if each connected device is displayed.

### Expected behavior
Each connected device is displayed on the Synced tabs page.

### Actual behavior
On mobile devices, the desktop isn't displayed. On desktop, both devices are displayed.

### Device information
* Android device: Google Pixel (Android 10), HTC 10 (Android 8)
* Fenix version: 6/25 Nightly

![synced tabs](https://user-images.githubusercontent.com/40694158/85733459-de90b880-b704-11ea-9d4c-63224cf8b368.png)

**Comment by yoasif** [comment] 2020-06-25 16:04
@softvision-miralobontiu FYI I also opened https://bugzilla.mozilla.org/show_bug.cgi?id=1646525 - perhaps you can follow up there as well?

**Comment by SS1113** [comment] 2020-06-25 16:59
@softvision-miralobontiu @yoasif 

Can you have a look at this issue: https://github.com/mozilla-mobile/fenix/issues/11577, seems like related to this.

**Comment by liuche** [comment] 2020-06-26 02:00
@grigoryk have there been changes that might cause other clients to disappear, or the FxA account to sign out? Also see #11577

**Comment by jonalmeida** [comment] 2020-08-18 06:15
From the 'Steps to reproduce': 

> Trigger sync, then go to Settings - Synced tabs and observe if each connected device is displayed.

Desktop sync happens on an interval. So we have to trigger sync on desktop first before we can trigger sync on mobile if you want to see immediate results.

Would QA be able to verify if this is true? Please close the ticket accordingly.

**Comment by abodea** [comment] 2020-08-19 09:59
I was not able to reproduce this issue on the latest Nightly build with Google Pixel 4 XL (11), Samsung Galaxy s10+ (10).
Note that the devices are correctly displayed on the Synced tabs section.
Should we close this issue? I also commented on the [Bugzilla bug.](https://bugzilla.mozilla.org/show_bug.cgi?id=1646525)
![image](https://user-images.githubusercontent.com/42831109/90620615-5e299800-e21b-11ea-8661-52c1460abd7d.png)

**Comment by jonalmeida** [comment] 2020-08-19 15:38
> Should we close this issue? I also commented on the Bugzilla bug.

Yeah let's close it.

I'm not sure what that bugzilla link is referencing though since I don't have permission to view it.

**Closed by jonalmeida** 2020-08-19 15:38 UTC
Labels: Feature:Sync, Feature:SyncTabs, S2, 🐞 bug

**Comment by abodea** [comment] 2020-08-19 15:50
I can add you to the CC as the bug is confidential. @jonalmeida
