### ISSUE TITLE
[Bug] Switch to tab-The option is not available for the last opened tab

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9457] opened 2020-03-27 13:49 UTC
## Steps to reproduce
1. Open app and make a search after a website.
2. Tap on the tabs tray and open a new tab.
3. Insert the site from step 1.
### Expected behavior
The "Switch to tab" option is displayed. ❓
### Actual behavior
The "Switch to tab" option is missing for the last searched site.
### Device information

* Android device: Google Pixel 3 XL (Android 9), Samsung Galaxy S9(Android 8) and Sony Xperia Z5 (Android 7)
* Fenix version: Firefox Preview Nightly 200327 (Build #20870607) GV: 76.0a1-20200325093457

Google Pixel 3 XL (Android 9) GIF:
![20200327-154015](https://user-images.githubusercontent.com/49859863/77762407-26d70680-7042-11ea-8531-20d62f9dc013.gif)

**Comment by ValentinTimisica** [comment] 2020-03-27 14:24
Seems like this is the intended behavior right now. In `SessionSuggestionProvider` constructor we pass `excludeSelectedSession = true` as you can see [here](https://github.com/mozilla-mobile/fenix/blob/2984e40db0a09aca1111547e083579df9f136030/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt#L151). Also you can check the [AC method](https://github.com/mozilla-mobile/android-components/blob/6f0781d57b086a544dfc1f5be390f6fe46584aac/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt#L68).

Curious about @boek's/@ekager's opinions on this. Is this a bug? Should we change `excludeSelectedSession = false`?

**Comment by ekager** [comment] 2020-08-02 22:50
It was intentional at some point 😆 
UX - is this something we want to change?

**Comment by AmyYLee** [comment] 2020-08-04 15:54
@topotropic for feedback

**Comment by topotropic** [comment] 2020-08-06 21:32
I think that's for @brampitoyo – looks like it's about the search results

**Comment by brampitoyo** [comment] 2020-08-11 06:06
@Diana-Rus @ValentinTimisica @ekager We definitely want to show (and visually label) currently open tabs in address bar search results (if it matches query), and allow people to easily switch to it.

I believe this is also part of #12622, where, along with open tabs, we will also visually label bookmarks and synced tabs.

**Comment by topotropic** [comment] 2020-11-05 12:47
Looks like this is working now – I'll close this issue. I also opened up 2 follow-up issues to review the priority of search suggestions (https://github.com/mozilla-mobile/fenix/issues/16391) and to fix a small bug (https://github.com/mozilla-mobile/fenix/issues/16390)

**Closed by topotropic** 2020-11-05 12:47 UTC
Labels: Feature:Browsing, Feature:Tabs, S2, 🐞 bug, 🙅 waiting
