### ISSUE TITLE
FNX-5037 ⁃ [UX nit] drop shadow on Home screen Search box is ugly & inconsistent in Dark mode

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#1449] opened 2019-04-07 17:27 UTC
Search box drop shadow on Home screen:-
I dislike the drop shadow, it makes Fenix look dated. Could get rid?
I dislike how it disappears as the search box scrolls up. Why is that necessary?
There's no drop shadow in Dark mode which seems inconsistent?

UX nit only but it annoys me :grinning: Cheers

**Comment by yoasif** [comment] 2019-04-07 18:50
FYI, I also opened this  #559

**Comment by kbrosnan** [comment] 2019-04-27 03:47
Closing as dupe of #559 the shadow will fade out when scrolled to the top when #2094 is fixed.

**Closed** 2020-08-11 11:38 UTC
Labels: Feature:HomeScreen, 🐞 bug
