### ISSUE TITLE
[webcontent] The address bar area is blank when show full height fixed element

### ISSUE THREAD

**Issue by weijarz** [mozilla-mobile/fenix#22444] opened 2021-11-15 12:30 UTC
## Site with issue and any steps to reproduce

https://reabble.com/static/firefox-layout.html

1. On first page, scroll to the 'Show Overlay' button, and the address bar is now hidden:

![Screenshot_2021-11-15-20-20-12-109_org mozilla firefox](https://user-images.githubusercontent.com/8944061/141781368-1b0a57bd-481f-40e7-85ff-dc1b22d176ad.jpg)

2. Press the 'Show Overlay' button

![Screenshot_2021-11-15-20-20-39-756_org mozilla firefox](https://user-images.githubusercontent.com/8944061/141781423-7ec0eefd-df9c-4935-87e6-26c5522bc608.jpg)

The address bar location is turning blank. And the bottom of overlay is obscured by the blank address bar.
If click the address bar area, it will appear:
![Screenshot_2021-11-15-20-20-51-888_org mozilla firefox](https://user-images.githubusercontent.com/8944061/141782017-792fdcf7-6077-4276-a777-71a41b9d7a21.jpg)

### Can you reproduce in Chrome (or other non-Mozilla browser)?

It works on chrome and safari.

### Device information

* Android device: Android 9
* Fenix version: 94.1.1

**Comment by Mugurell** [comment] 2021-11-15 13:23
Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/9970.
Should be fixed in the next few days.

**Closed by Mugurell** 2021-11-15 13:23 UTC
Labels: needs:triage
