### ISSUE TITLE
[Bug] Facebook doesn't have "Open in app" option in QAB

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6397] opened 2019-11-01 13:46 UTC
## Steps to reproduce
1. Install facebook on your device.
2. In Fenix, access the facebook page.
3. Drag the QAB and observe the options.

### Expected behavior
"Open in app" is displayed in the QAB.

### Actual behavior
"Open in app" is not displayed in the QAB.

### Device information
* Android device: Google Pixel (Android Q), Sony Xperia Z5 Premium (Android 7.1.1)
* Fenix version: 11/01 (#13050628)

**Comment by ekager** [comment] 2019-11-14 00:33
We removed the QAB, but I am seeing the option to open in app in the browser menu now when I go to m.facebook.com/events

**Comment by sv-ohorvath** [comment] 2019-11-14 11:50
@ekager It only shows up on some facebook pages as Events and Watch, not all. For instance, go to Saved, Games, MarketPlace, or just the homepage (the timeline) and it won't appear in the browser menu.

**Comment by rocketsroger** [comment] 2019-11-20 23:29
This is referring to Fennec's toolbar where there is an android Icon when the user is on a specific site.

![device-2019-11-20-182158](https://user-images.githubusercontent.com/6579541/69287253-997f3380-0bc3-11ea-848f-6d6142aad348.jpg)

**Comment by rocketsroger** [comment] 2019-11-20 23:30
@vesta0 Is this something we want down the road?

**Comment by rocketsroger** [comment] 2019-11-27 18:47
Duplicate of https://github.com/mozilla-mobile/fenix/issues/6750.  Closing this one since the other one is more general.

**Comment by rocketsroger** [comment] 2019-11-27 18:48
Duplicate of https://github.com/mozilla-mobile/fenix/issues/6750

**Closed by rocketsroger** 2019-11-27 18:48 UTC
Labels: S2, 🐞 bug
