### ISSUE TITLE
[Bug] Search widget has height of 2 cells on some phones

### ISSUE THREAD

**Issue by jyeontaek** [mozilla-mobile/fenix#4766] opened 2019-08-15 23:27 UTC
## Steps to reproduce
Place search widget on home screen.
### Expected behavior
Height should be 1 cell.
### Actual behavior
Height is 2 cells.
### Device information

* Android device: Nokia 3.1
* Fenix version: 1.3

**Comment by KaairaGupta** [comment] 2020-01-07 19:54
Hey! Is this issue prevalent on all android versions or just the old ones?

**Comment by KaairaGupta** [comment] 2020-01-10 12:52
@ekager i checked this on my device (android 9) and i was unable to reproduce it on it. So does this issue still persist? If it does I would like to work on it.

**Comment by ekager** [comment] 2020-01-10 18:15
I'm not sure, it looks like it must be device dependent so we'll need to investigate the device/version this happens on

**Comment by brampitoyo** [comment] 2020-03-03 04:31
On my OnePlus One device, Fenix’s search widget has a height of 2, which couldn’t be resized down.

<img width="360" src="https://user-images.githubusercontent.com/51007/75743143-d935e980-5d74-11ea-8078-fcde3c7e1640.png">

**Comment by Diana-Rus** [comment] 2020-03-18 09:20
Hi, I tried to reproduce the issue but without success, on the following devices:
- OnePlus 7T Pro (Android 10)
![20200318-100534](https://user-images.githubusercontent.com/49859863/76940480-051fa600-6903-11ea-825c-052a82569177.gif)
- Google Pixel 3a XL (Android 10)
![Screenshot_20200318-102725](https://user-images.githubusercontent.com/49859863/76942456-701eac00-6906-11ea-8108-e2daaabe6491.png)
- Samsung Galaxy Note9 (Android 9)
- Samsung Galaxy S9 (Android 8)
- Sony Xperia Z5 (Android 7)

Build:
Firefox Preview 1.3.0
Firefox Nightly build dated 200303 (Build #20630607)
Firefox Nightly 200318 (Build #20780606) GV 76.0a1-20200316092804

Note: 
@brampitoyo  - Can you please check whether with other search widgets is the same? With the latest nightly build are you still encountering the issue?

**Comment by brampitoyo** [comment] 2020-03-19 02:48
@Diana-Rus Yes. Unfortunately, both the latest Firefox Preview and Firefox Preview Nightly search widgets have a height of 2.

Interestingly, Fennec’s widget only has a height of 1.

<img width="360" src="https://user-images.githubusercontent.com/51007/77026636-03d0a500-69f9-11ea-8fcc-0f5e104deec6.png">

**Comment by LaurentiuApahideanSV** [comment] 2020-03-19 13:25
I tried to reproduce your issue on the latest Firefox Preview Nightly (Build #20790606) Thursday 3/19 using a OnePlus 6T (Android 9) and Huawei MediaPad M3 (Android 7.0) but was unable to. @brampitoyo Could you specify the model of the OnePlus device you are using and it's firmware?

**Comment by brampitoyo** [comment] 2020-03-22 22:50
@LaurentiuApahideanSV Thanks for checking this on device.

I’m running a OnePlus One device with LineageOS 17. I realise that this is an aftermarket OS that only very few people would have! So, if the problem is not reproducible on other official OS, I would be okay with closing this issue.

**Comment by softvision-miralobontiu** [comment] 2020-03-24 13:47
Verified on the latest Nightly from 3/24, and on Beta 4.2.0-beta.1, with OnePlus 5T (Android 9), and the issue is not reproducible.
I will flag this issue as QA:verified and close it.

**Closed by softvision-miralobontiu** 2020-03-24 13:47 UTC
Labels: P2, eng:qa:needed, feature:SearchWidget, good first issue, needs:STR, needs:investigation, 🐞 bug
