### ISSUE TITLE
(bug) new tab opens instead an opened tab

### ISSUE THREAD

**Issue by SosPosos** [mozilla-mobile/fenix#24529] opened 2022-03-30 21:38 UTC
When i in private mode and want to open tab in non private mode, it opens a new tab interface (blank page and keyboard). Need to press back to finaly open tab. I swap from private to non private all the time and it's really annoying.

Poco f3, last arrow os, android 12

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20007)

**Comment by SosPosos** [comment] 2022-03-30 21:45
Oh, and it would be cool, if you add a black wallpaper for amoled screens

**Comment by cadeyrn** [comment] 2022-03-30 21:58
@SosPosos You should open separate issues, especially since one sounds like a bug report and the other one is a feature request.

**Comment by LaurentiuApahideanSV** [comment] 2022-03-31 15:48
I tried to reproduce the issue on Firefox Nightly 2022-03-30 but was unable to. @SosPosos Could you upload a short video illustrating the issue?

### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)

**Comment by SosPosos** [comment] 2022-04-01 07:46
![Screenshot_20220401-104257_Firefox](https://user-images.githubusercontent.com/52379151/161218421-fbdc9e33-f6d1-4fc7-b994-5bb62570306c.png)
![Screenshot_20220401-104320_Firefox](https://user-images.githubusercontent.com/52379151/161218459-0edee5b1-6e30-4129-895b-804df408ca0f.png)
![Screenshot_20220401-104338_Firefox](https://user-images.githubusercontent.com/52379151/161218467-3f4f2d9a-e48f-4f0e-b52b-9f6de624b886.png)
I can upload screenshots
Don't know how to upload a video easily
Open a tab menu in private mode
Tap on non private tabs icon
Tap on any tab
Recieved a new tab interface

**Comment by mcarare** [comment] 2022-07-28 12:28
@SosPosos  Thank you for your report. This issue is already reported and tracked in #23106. Closing this as duplicate.

**Closed by mcarare** 2022-07-28 12:28 UTC
Labels: needs:triage, qa-triaged
