### ISSUE TITLE
[Bug] OOM kill loses private tabs

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#2493] opened 2019-05-14 22:02 UTC
## Steps to reproduce
1. Open some private tabs.
1. Put the app into the background.
1. Run `adb shell am kill org.mozilla.fenix` to simulate an OOM-kill.

### Expected behavior
Private tabs are restored, as in Fennec.

### Actual behavior
Private tabs have been lost.

While private tabs should by their nature be rather ephemeral, unlike on Desktop OOM-kills can happen much more often, especially on lower-end devices - possibly just seconds after the app has gone into the background (in very extreme cases possibly even when we're the foreground app) - which seems a little _too_ ephemeral.
Fennec therefore saves private tabs as part of the relevant activity's savedInstanceState, which is restored by the OS even after OOM-kills, but gets dropped when the app is swiped away, explicitly quit, force-stopped, the device rebooted, etc, thereby still keeping with the spirit of private tabs. The problem with that approach is that the `savedInstanceState` can only take at most 1 MB of data, and in practice quite a bit less because a number of other things need to store their state there, too, and we have indeed seen a few crashes in Fennec where the private tabs' session data got too large.

Some possible ideas:

1. Compress the data to fit more of it into the given limit.
1. Store a reduced (either in number of features, and/or number of past session history entries) amount of session store data if it would otherwise exceed the limit.
1. Not sure if this would be acceptable from a privacy perspective: Store the private browsing session store data on disk, but encrypt if beforehand and store the key in memory only and as part of the `savedInstanceState`. Once the app is killed and the `savedInstanceState` cleared, too, the encrypted data could no longer be read, although its presence on disk would still reveal _that_ private browsing had been used at some point. Not sure how paranoid we need to be here?
1. Don't attempt preserving private tabs against the app being killed, but register a foreground service while in private browsing to make Android more unlikely to OOM-kill the app while it is backgrounded. Although again if you're really paranoid, a problem is that Android keeps a log of notifications, even if that feature is somewhat hidden and not targeted towards general users. And if we're okay with that, then 3.) might be equally acceptable given that the profile directory on Android will be sandboxed anyway, and also more resilient?

### Device information
* Android device: Moto G4 Play, Android 6.0.1
* Fenix version: 1.0.9020, Build #11341807

**Comment by sblatz** [comment] 2019-09-20 13:19
> Don't attempt preserving private tabs against the app being killed, but register a foreground service while in private browsing to make Android more unlikely to OOM-kill the app while it is backgrounded. Although again if you're really paranoid, a problem is that Android keeps a log of notifications, even if that feature is somewhat hidden and not targeted towards general users. And if we're okay with that, then 3.) might be equally acceptable given that the profile directory on Android will be sandboxed anyway, and also more resilient?

I may be mistaken, but I think the "erase private tabs" notification we now serve should protect against this case. 

@colintheshots are you able to verify?

**Comment by buttercookie42** [comment] 2019-09-21 10:40
It does indeed make it quite a bit more unlikely, but under severe memory pressure (some other big apps running and/or a resource-constrained device) we could still get killed.

**Comment by sblatz** [comment] 2019-11-12 20:38
@vesta0 my understanding is that this is an explicit design decision by us--we do not want to store the private tabs on the device. Because of this, the trade-off is that if the system does decide to kill our app, a user will lose their private tabs. This is not going to happen super often because we do have a foreground notification now.

Can I close this as expected behavior if the system decides to kill us anyway?

**Comment by vesta0** [comment] 2019-11-15 00:54
@sblatz yes this is expected behaviour and we can close this.

**Closed** 2020-08-26 05:33 UTC
Labels: Feature:FennecTransition, needs:ac, 🐞 bug
