### ISSUE TITLE
[Bug][a11y] Homescreen-Increase touch target for "Learn more" link

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#14716] opened 2020-09-04 10:17 UTC
## Prerequisites
- Have Google Accessibility Scanner installed.
- Have a clean Firefox profile.
## Steps to reproduce
1. From the Onboarding screen tap on the "Start browsing" button.
2. Scan the home screen.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
**Section "Firefox preview is now Firefox Nightly"**
**Touch target**
org.mozilla.fenix:id/tip_learn_more
This item's height is 19dp. Consider making the height of this touch target 48dp or larger.
### Device information

* Android device: Google pixel 3XL (Android 9)
* Fenix version: Nightly 9/4

<details closed><summary>Screen</summary>

![Screenshot_20200904-131628](https://user-images.githubusercontent.com/49859863/92228715-fe84eb00-eeb0-11ea-8ab8-d302a83acb55.png)
</details>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6334)

**Comment by Vaironl** [comment] 2021-01-15 21:44
Since no one has commented on this yet, I would like to work on it.

**Comment by fevziomurtekin** [comment] 2021-01-23 14:48
Hey! I made a small changes. Sorry to two commits

**Comment by softvision-miralobontiu** [comment] 2021-03-02 14:13
On the 3/2 Nightly build using an OnePlus 5T (Android 10) device, the suggestion is:

Touch target
org.mozilla.fenix:id/learn_more
This item's height is 20dp. Consider making the height of this touch target 48dp or larger.

**Comment by fevziomurtekin** [comment] 2021-03-02 17:50
Hey! I made the change you said. 👍

**Comment by softvision-miralobontiu** [comment] 2021-03-03 07:17
I've retested on the 3/3 Nightly build fro 5:07 AM, and the fix isn't visible yet. 
The same suggestion was displayed.

<img src="https://user-images.githubusercontent.com/40694158/109768084-21dee780-7c01-11eb-9d34-57f53a710bdb.jpg" width="300" height="550" />

**Comment by neha-b2001** [comment] 2021-03-22 14:14
Hello @eliserichards, if this issue is still unresolved, could I please work on this issue?

**Comment by eliserichards** [comment] 2021-03-23 20:39
Hi @neha-b2001! Are you an Outreachy applicant? If so, please feel free to work on this issue 😄

**Comment by neha-b2001** [comment] 2021-03-24 02:57
> Hi @neha-b2001! Are you an Outreachy applicant? If so, please feel free to work on this issue 😄

Yes, @eliserichards, I am an Outreachy applicant😄 
Okay, I'll start working on it right away. Could I please be assigned this issue?

**Comment by AnishaSingh0118** [comment] 2021-03-25 17:04
Hey, Is this issue too hard to begin with?

**Comment by neha-b2001** [comment] 2021-03-29 14:55
Can someone guide me as to how to reproduce this issue? I ensured that I have the pre-requisites and followed the steps described in the issue. However, the 'Firefox Preview in now Firefox Nightly' section is not visible to me at all. I've tried to figure out if I'm doing something wrong for more than 2 days, but haven't been able to figure it out... 
Any guidance would sincerely help a lot 😅

**Comment by eliserichards** [comment] 2021-03-29 15:30
Hmm let me take a look...

**Comment by neha-b2001** [comment] 2021-03-29 18:23
> Hmm let me take a look...

Thank you 👍

**Comment by eliserichards** [comment] 2021-03-29 20:39
This tip was being shown when our app was being launched (it was called "Firefox Preview" before we released it to everyone). You can see where the tip was being created in [MigrationTipProvider.kt](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/tips/providers/MigrationTipProvider.kt):

<img width="909" alt="image" src="https://user-images.githubusercontent.com/43795363/112896641-42854a80-90a4-11eb-850a-375853328560.png">

You should be able to see the Tip on the homescreen if you temporarily change line 34 to this: 

```
override val shouldDisplay: Boolean = true
```

The actual Learn More link that you will be fixing is in [button_tip_item.xml](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/layout/button_tip_item.xml) TextView: https://github.com/mozilla-mobile/fenix/blob/0a0d48f48cba76aaad8cf9d6b882f952418f9195/app/src/main/res/layout/button_tip_item.xml#L57 
<img width="579" alt="image" src="https://user-images.githubusercontent.com/43795363/112897081-cc351800-90a4-11eb-86c3-56446c6c31e9.png">

**Comment by neha-b2001** [comment] 2021-03-30 05:53
Thank you so much @eliserichards 😄

**Closed** 2022-12-03 07:40 UTC
Labels: 🐞 bug, good first issue, Feature:HomeScreen, access, S3, help wanted, wontfix
