### ISSUE TITLE
Redundant expensive calls to `Browsers.all` in `LeanplumMetricsService.start`

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7425] opened 2019-12-31 00:46 UTC
`LeanplumMetricsService.start` calls two of our methods that take up :
- `getInstalledMozillaProducts`
- `getMozillaBrowsersDefault`

Both of these methods call `Browser.all` redundantely for a total of ~40ms on my Pixel 2. Eyeballing it, these calls together appear to take 35-40% of `LeanplumMetricsService.start()` which is already a huge part of startup.

Can we wait to call these until after startup or at least only initialize `Browsers` once?

**Comment by hawkinsw** [comment] 2020-01-02 03:07
FYI: This will not be a startup issue after @MarcLeclair lands the patch to move `setStartupMetrics` off the main thread. 

That does not mean, however, that the underlying issue will be fixed.

**Comment by mcomella** [comment] 2020-01-02 16:07
> FYI: This will not be a startup issue after @MarcLeclair lands the patch to move `setStartupMetrics` off the main thread.

@hawkinsw `setStartupMetrics` does not seem related to Leanplum: I only see `GleanMetricsService.setStartupMetrics`. Am I missing something?

**Comment by mcomella** [comment] 2020-01-02 17:20
Oh, I see a similar pattern in GleanMetricsService, which must be what Will means: https://github.com/mozilla-mobile/fenix/blob/c3389dcdb58d0853e97ed4fb9bc9e13dd1936ee8/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L507

**Comment by hawkinsw** [comment] 2020-01-02 20:24
> Oh, I see a similar pattern in GleanMetricsService, which must be what Will means:
> 
> https://github.com/mozilla-mobile/fenix/blob/c3389dcdb58d0853e97ed4fb9bc9e13dd1936ee8/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L507

Sorry, these are really two different things. `GleanMetricsService.setStartupMetrics` does use these methods and @MarcLeclair 's patch will move those off the MT. 

I will go back and look into potential mitigations w.r.t this and Leanplum. Sorry for the confusion. I will assign this to myself.

**Comment by hawkinsw** [comment] 2020-01-03 00:35
See also https://github.com/mozilla-mobile/fenix/pull/7477

**Comment by hawkinsw** [comment] 2020-01-08 08:40
QA: To verify, I think that there are two options:

1. Check that metrics (Leanplum, Glean, etc) gathered about a user's device should contain an accurate list of all installed browsers. 
1. Presumably there was a QA/regression test for guaranteeing that Fenix accurately captures the list of browsers installed on a user's device; continue to perform that test.

**Comment by pocmo** [comment] 2020-01-08 09:35
The solution you landed is great and makes sense to me. However I wonder if we should upstream this to AC and/or integrate into its `Browsers` class. This looks like something we want all apps to benefit from?

**Comment by AndiAJ** [comment] 2020-01-30 09:34
Hi I've just check this issue on the latest **Nightly Build #20300608 from 1/30** using a Google Pixel 3a (Android 9) device.

Installed Mozilla products:
• Lockwise
• Firefox Focus
• Firefox RC
• Firefox Beta
• Firefox Nightly
• Fenix RC
• Fenix Beta

►Leanplum User ID **9f9e62e9-bda8-4a3b-9dce-61b936caecbc**
![lean](https://user-images.githubusercontent.com/51314259/73432417-5ec81300-434b-11ea-9ba2-e9313e70615b.JPG)

► Generated metrics ping

``` --- kotlin 
"string_list": {
          "metrics.mozilla_products": [
            "org.mozilla.firefox",
            "org.mozilla.firefox_beta",
            "org.mozilla.fennec_aurora",
            "org.mozilla.fenix",
            "org.mozilla.focus",
            "mozilla.lockbox"
          ]
        }

```

► Comparison Leanplum VS Metrics ping

| Installed Mozilla product  | Leanplum | Metrics ping |
| ------------- | ------------- | ------------- |
| Lockwise   | ❌  | ✔️  |
| Firefox Focus  | ✔️  | ✔️  |
| Firefox RC  | ✔️  | ✔️  |
| Firefox Beta  | ❌  | ✔️  |
| Firefox Nightly  | ❌  | ✔️  |
| Fenix RC  | ❌  | ✔️  |
| Fenix Beta  | ❌  | ❌  |

Not sure why:
Quite a lot of **Mozilla products aren't displayed in Leanplum**?
**Fenix Beta** (org.mozilla.fenix.beta) isn't displayed in the metrics ping?

Another worth mentioning matter is regarding the `fxa_signed_in` & `fxa_has_synced_items `attributes from Leanplum, namely both are **set to True** even if I **haven't signed in to sync**. 

@hawkinsw & @mcomella - Please review and share your thoughts on my findings.
Also, please let me know if I missed something or if I should change my testing approach.  ☺️ 

**I'll remove the QA needed label until further notice.**

**Comment by mcomella** [comment] 2020-02-06 15:24
>  Quite a lot of Mozilla products aren't displayed in Leanplum?

From the code, Leanplum only includes probes for Firefox Release, Focus, and Klar so it looks like this is as expected.

>  Fenix Beta (org.mozilla.fenix.beta) isn't displayed in the metrics ping?

I see Fenix Beta is listed twice in this list, once checked and once not & it's included in the text list: I think this is working correctly (it's marked as installed) and the second listing is an error.

> Another worth mentioning matter is regarding the fxa_signed_in & fxa_has_synced_items attributes from Leanplum, namely both are set to True even if I haven't signed in to sync.

This seems unexpected. @AndiAJ Can you file a bug?

Please review this comment and do what you need to with the bug, Andi! I'll add the QA:needed label again so we don't forget about it.

**Comment by AndiAJ** [comment] 2020-02-07 15:29
Hi @mcomella I've re-checked this matter on the latest **Nightly #20380605 from 2/7** using a Google Pixel 3 (Android 9)

►Leanplum User ID  **cbaf1ee6-bf87-4e25-af0d-8876699cad3e**
![Capturea](https://user-images.githubusercontent.com/51314259/74041325-1ef9cf00-49ce-11ea-85b8-2b2ad717d6c8.JPG)

► Generated metrics ping
```
          "metrics.mozilla_products": [
            "org.mozilla.firefox",
            "org.mozilla.focus",
            "org.mozilla.klar"
          ]

```
As per your remarks:
> From the code, Leanplum only includes probes for Firefox Release, Focus, and Klar so it looks like this is as expected.

I've installed : Firefox Release, Focus, and Klar
| Installed Mozilla product  | Leanplum | Metrics ping |
| ------------- | ------------- | ------------- |
| Klar   | ✔️  | ✔️  |
| Firefox Focus  | ✔️  | ✔️  |
| Firefox RC  | ✔️  | ✔️  |


> > Fenix Beta (org.mozilla.fenix.beta) isn't displayed in the metrics ping?
> 
> I see Fenix Beta is listed twice in this list, once checked and once not & it's included in the text list: I think this is working correctly (it's marked as installed) and the second listing is an error.
 
It is actually a bug most probably in the code used for product detection in Fenix.
I've filled #8206 

> > Another worth mentioning matter is regarding the fxa_signed_in & fxa_has_synced_items attributes from Leanplum, namely both are set to True even if I haven't signed in to sync.
> 
> This seems unexpected. @AndiAJ Can you file a bug?

@ekager filled #7999 and will track this matter there. (the **fxa_signed_in** seems to be fixed)

Please review and let me know if any additional research should be done.
If that's the case please re-open it.

Thanks again for your help! ☺️

**Closed by AndiAJ** 2020-02-07 15:29 UTC
Labels: P2, eng:performance, eng:qa:needed
