### ISSUE TITLE
FNX-5451 ⁃ [Fenix] Drop-shadow on search bar should have a fade transition when it disappears on scroll

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2094] opened 2019-04-26 20:46 UTC
## Steps to reproduce
1. Go to Fenix homescreen and look at search bar. 
1. Scroll up until it sticks to the top. 
    1. Expected behavior
The drop-shadow on the search bar should fade out like how the Fenix logo does when you scroll up.
    1. Actual behavior
The drop-shadow abruptly disappears.
    1. Device information

* Pixel 3
* Version 1.01917

**Comment by sblatz** [comment] 2019-04-26 21:13
I believe this is fixed. I'm not able to reproduce this on master. Tagging QA needed on this so they can check on the next nightly.

**Comment by sblatz** [comment] 2019-04-26 21:13
Whoops. responded to the wrong ticket.

**Comment by sv-ohorvath** [comment] 2019-05-08 08:35
I see a smooth transition on master 5/8. devices: Pixel, MediaPad M2 (Android 5.1.1)

**Comment by sblatz** [comment] 2019-05-10 20:20
I don't believe this is actually fixed. I think what @AmyYLee is referring to is that, if you *slowly* scroll the animation all happens on a single key frame instead of slowly transitioning each frame.

@AmyYLee can you confirm?

**Comment by AmyYLee** [comment] 2019-05-28 14:49
Hi, 

I looked at the latest build and there seems to be a regression.

Current
<img width="393" alt="Screen Shot 2019-05-28 at 10 45 32" src="https://user-images.githubusercontent.com/5992746/58487576-cd5a2e80-8135-11e9-8455-b6d23ccbc5db.png">

Spec
<img width="402" alt="Screen Shot 2019-05-28 at 10 43 51" src="https://user-images.githubusercontent.com/5992746/58487606-dd720e00-8135-11e9-9d0c-1a02cc5ed7db.png">

The transition from white to grey search bar when you scroll up should be the same transition as when you tap on the search bar here: https://drive.google.com/file/d/1gPL3JO3uNgl9LmpJ8P2cnEey3YsLGyGL/view

**Comment by AndiAJ** [comment] 2019-07-03 10:07
Hi, the issue is still replicating on the latest Fenix Build #11840608 from 2019-07-03 using the following devices:
• OnePlus6T (Android 9)
• Samsung Galaxy S8+ (Android 8)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

►Video from OnePlus6T
![20190703_125218](https://user-images.githubusercontent.com/51314259/60583046-a4f7cc80-9d92-11e9-8bba-879e3e1d0ed7.gif)

@AmyYLee or  @sblatz could you please confirm if this behavior should also be implemented in the "Welcome screen" as well ?

**Comment by sblatz** [comment] 2019-07-03 15:50
Oh weird. This is only reproducible on nightly builds but not on debug ones. I'll investigate this more.

**Comment by softvision-miralobontiu** [comment] 2019-07-12 08:57
Verified as fixed on the latest Nightly build 190712 (#11930609) with Google Pixel 3, Huawei P9 Lite (Android 6), and Samsung Galaxy Tab A6 (Android 5.1.1).

**Closed** 2020-08-11 13:52 UTC
Labels: Feature:HomeScreen, P1, eng:qa:verified, 🐞 bug
