### ISSUE TITLE
[Bug]: "Save as PDF" is invisible in private browsing mode

### ISSUE THREAD

**Issue by 0x391F** [mozilla-mobile/fenix#28303] opened 2022-12-23 23:27 UTC
### Steps to reproduce

![Screenshot_20221224_071401](https://user-images.githubusercontent.com/56181919/209412874-fd555b79-806c-47ed-90ff-4b00af041085.jpg)
![Screenshot_20221224_071458](https://user-images.githubusercontent.com/56181919/209412873-b35cea9b-3fab-4bc3-86c5-86a28c9fd47d.jpg)

### Expected behaviour

This bug shouldn't appear. 

### Actual behaviour

"Save as PDF" is invisible in private browsing mode. 

### Device name

Honor 20S

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

108.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22191)

**Comment by cadeyrn** [comment] 2022-12-24 21:47
Duplicate of #28106, already fixed in Nightly.

**Comment by AdinaPetridean** [comment] 2023-01-03 09:53
@0x391F thank you for your report! 
I will close this as a duplicate of https://github.com/mozilla-mobile/fenix/issues/28106, which is already fixed in Nightly.

**Closed** 2023-01-03 09:59 UTC
Labels: 🐞 bug, needs:triage, qa-triaged
