### ISSUE TITLE
FNX-4669 ⁃ Auto password generator similar to desktop version

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#10899] opened 2020-05-25 15:41 UTC
please add the auto password generator in fenix similar to firefox desktop version.

**Comment by Dunexus** [comment] 2020-05-25 17:21
Dupe of https://github.com/mozilla-mobile/fenix/issues/5661

**Comment by sheikh-azharuddin** [comment] 2020-05-25 17:26
> Dupe of #5661

There is no update on that thread since Oct 2019 😕

**Comment by lindongbin** [comment] 2020-05-27 00:20
Many websites cannot automatically fill in passwords, I think the problem of manually selecting passwords in the input box should be solved first

**Comment by kglazko** [comment] 2020-05-27 19:42
Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/5661. Please continue discussion there.

**Comment by sheikh-azharuddin** [comment] 2020-05-27 20:25
You cannot close this without any proper update? That case is not updated since October and I don't see any progress.....for the desktop version you are advertising about new password generator feature too much yet this is missing in the android version!

**Comment by sheikh-azharuddin** [comment] 2020-05-27 20:26
> Closing as a duplicate of #5661. Please continue discussion there.

You cannot close this without any proper update? That case is not updated since October and I don't see any progress.....for the desktop version you are advertising about new password generator feature too much yet this is missing in the android version!

**Closed** 2020-08-10 22:33 UTC
