### ISSUE TITLE
Enabling 'desktop site' toggled permently

### ISSUE THREAD

**Issue by PeterKW** [mozilla-mobile/fenix#24428] opened 2022-03-23 23:54 UTC
Is there a way of enabling the 'desktop site' to be toggled permently for all website tabs from the settings page?

**Comment by cadeyrn** [comment] 2022-03-24 08:00
No, it's not possible. If it was meant as feature request and not just as a question it's a duplicate of #7039.

**Comment by LaurentiuApahideanSV** [comment] 2022-03-24 12:11
I will close this issue as duplicate of https://github.com/mozilla-mobile/fenix/issues/7039.

**Closed by LaurentiuApahideanSV** 2022-03-24 12:11 UTC
Labels: needs:triage

**Comment by PeterKW** [comment] 2022-03-25 23:23
> I will close this issue as duplicate of https://github.com/mozilla-mobile/fenix/issues/7039. 

Ah right, okay. I ended up adding the UA extension to my Android Collection to pretend to be a desktop device for the equivalent result of desktop mode.
https://addons.mozilla.org/en-GB/firefox/addon/user-agent-string-switcher/
