### ISSUE TITLE
[Bug] "Bookmark saved!" popup does not show when "Scroll to hide toolbar" is disabled.

### ISSUE THREAD

**Issue by georapbox** [mozilla-mobile/fenix#15257] opened 2020-09-21 06:26 UTC
## Steps to reproduce

1. Go to Settings > Customize
2. Ensure that "Scroll to hide toolbar" option is disabled.
3. Open any web page that is not yet bookmarked and bookmark it.

### Expected behavior

After bookmarking a web page, a purple popup with title "Bookmark saved!" and a button to edit the bookmark should appear at the bottom of the screen. 

**Screenshot with "Scroll to hide toolbar" option enabled**

![expected_screenshot](https://user-images.githubusercontent.com/6596039/93737297-79594000-fbeb-11ea-99aa-24fd560698a2.gif)

### Actual behavior

When "Scroll to hide toolbar" option is disabled the "Bookmark saved!" popup does not appear at all. See the animated gif below. The bookmark button is tapped and the page is successfully bookmarked, the popup does not appear though.

**Screenshot with "Scroll to hide toolbar" option disabled**

![actual_screenshot](https://user-images.githubusercontent.com/6596039/93737317-883ff280-fbeb-11ea-814d-6dbc51f8e62e.gif)

### Note

The same behavior was also observed while opening a link in a new tab. The purple popup with title "New tab opened" and a button to switch to it does not appear as well.

![expected_new_tab_popup_screenshot](https://user-images.githubusercontent.com/6596039/93737292-72323200-fbeb-11ea-8d5f-52dca40baebc.png)
 
### Device information

* Android device: Motorola One (XT1941-4)
* Fenix version: Nightly 200920 06:02 (Build #2015764979)

**Comment by hwinnemoe** [comment] 2020-09-21 10:08
Duplicate of #14982

**Comment by LaurentiuApahideanSV** [comment] 2020-09-22 09:22
The issue no longer occurs on Firefox Preview Nightly 200922 (Build #2015765363).
### Devices used:
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)

**Closed by LaurentiuApahideanSV** 2020-09-22 09:22 UTC
Labels: needs:triage, 🐞 bug
