### ISSUE TITLE
FNX-12281 ⁃ [Bug] multiple issues with PWAs

### ISSUE THREAD

**Issue by PatrickNogas** [mozilla-mobile/fenix#11366] opened 2020-06-09 11:32 UTC
## Steps to reproduce
Create PWA and open it

### Expected behavior
Navigation bar and status bar should follow firefox theme

### Actual behavior
Navigation bar and status bar is in white colour
(no matter if this is gesture navigation, 2 button nav, or 3 button nav it always give the same results)

### Device information
* Android device: Xiaomi Mi A3 - android 10
* Fenix version: 5.1.1

ps: it might be important that i have turned on system dark theme 

![Screenshot](https://user-images.githubusercontent.com/52964049/84142885-e50d0800-aa55-11ea-9ce5-6b52c1dc335a.png)UNITO-UNDERSCORE!20200609-132140!

**Comment by PatrickNogas** [comment] 2020-06-09 11:39
Oh and when you open something fullscreen eg. ig story and firefox status bar show up the navigation bar will become black but system status bar will remain white


![Screenshot (Jun 9, 2020 1 37 46 PM)](https://user-images.githubusercontent.com/52964049/84143292-9d3ab080-aa56-11ea-973f-82a1e9934f28.png)

**Comment by PatrickNogas** [comment] 2020-06-09 11:42
Oh and when you open something fullscreen eg. ig story the status bar will show up and navigation bar will become black
![Untitled](https://user-images.githubusercontent.com/52964049/84143484-f73b7600-aa56-11ea-89bf-9746a4224b06.png)

**Comment by kbrosnan** [comment] 2020-06-12 22:32
Please don't report multiple problems in a single issue.

Your first issue is a duplicate of #8812

Your second issue is a duplicate of #10452

**Closed** 2020-08-11 03:53 UTC
Labels: Feature:PWA, needs:triage, 🐞 bug
