### ISSUE TITLE
FNX-12427 ⁃ [Bug] Dark reader doesn't work

### ISSUE THREAD

**Issue by joelocandol** [mozilla-mobile/fenix#11483] opened 2020-06-11 18:58 UTC
I had installed dark reader since it was available, it doesn't had any problem until an update from around a week ago. Since then the add-on doesn't work neither enter in the configuration (of dark reader, not the add-ons Manager) it keeps forever in the loading screen

### Device information
Oukitel c5

* Android device: 7.0
* Fenix version: Nightly 200611 06:01 (Build #2015745585)

**Comment by liuche** [comment] 2020-06-11 19:11
@agi90 @Amejia481 has anything changed recently in the WebExtensions?

**Comment by SS1113** [comment] 2020-06-11 19:15
It works fine on `5.2.0-beta.1` but not on `Nightly 200611 06:01`.

**Comment by Amejia481** [comment] 2020-06-11 19:26
I'm able to reproduce the issue on Nightly 200611. I'm not aware of any new change on the ac/ web extension side.  I will start doing some investigation.  

So far I see, this logs on the extension console not sure if they are related
```
can't access property "config", $sync is undefined index.js:1896
Unchecked lastError value: Error: An unexpected error occurred index.js:1894
    loadSettingsFromStorage moz-extension://3460c309-8c2a-4322-b7ad-d9c4a04bc241/background/index.js:1894
```

**Comment by csadilek** [comment] 2020-06-11 19:29
@liuche this is a dupe of: https://github.com/mozilla-mobile/fenix/issues/11336

Fix already landed in GV and should be in tomorrow's Nightly.

**Closed** 2020-08-11 04:08 UTC
Labels: Feature:WebExtensions, needs:gv, 🐞 bug
