### ISSUE TITLE
[Bug] Google login does not work with tracking protection enabled

### ISSUE THREAD

**Issue by georgelemental** [mozilla-mobile/fenix#3304] opened 2019-06-09 17:11 UTC
## Steps to reproduce
1. Open Google login page with tracking protection enabled
1. Enter email
1. Click "next"
    1. Expected behavior
Password prompt appears
    1. Actual behavior
Nothing happens
    1. Device information

* Android device: Moto G5 Plus, Android 8.1.0
* Fenix version: 1.0.1923 (Build #11590615 :lizard: 68.0-20190604110028)

**Comment by vesta0** [comment] 2019-06-11 05:10
@georgelemental are you still experiencing this issue? I am not able to reproduce it.

**Comment by sblatz** [comment] 2019-06-11 18:31
I'm also unable to reproduce. I'm moving this to `blocked` until we have STR.

**Comment by vesta0** [comment] 2019-06-13 04:25
Closing this issue as I haven't been able to reproduce on several devices and don't have STR. @georgelemental feel free to re-open if you come across it again.

**Comment by softvision-miralobontiu** [comment] 2020-03-11 14:57
Removing the needs:STR label, since this issue is not reproducible and closed.

**Closed** 2020-08-26 23:12 UTC
Labels: Release Blocker, needs:investigation, 🐞 bug, 🙅 waiting
