### ISSUE TITLE
[Bug]: All installed add-ons are displayed in English. The operating system and browser are Russified. Also, the description of additions is also in Russian. 

### ISSUE THREAD

**Issue by Someone-G** [mozilla-mobile/fenix#27944] opened 2022-11-22 11:22 UTC
### Steps to reproduce

1. "Three dots" button
2. Add-ons
3. Add-on manager
4. Add uBlockOrigin in Russian (As an example)
5. Add-on uBlockOrigin in English.

### Expected behaviour

Additions must be in Russian. They are Russified.

### Actual behaviour

The description of the add-on is in Russian, and the add-on must also be Russified.

### Device name

Asus ZB602KL

### Android version

8.1

### Firefox release type

Firefox

### Firefox version

105.1.0 (Build #1051000)

### Additional information

![Screenshot_20221122-141509](https://user-images.githubusercontent.com/108881628/203301564-f6f28a5b-5ef2-4e7a-9c2f-af11442a084b.png)
![Screenshot_20221122-141516](https://user-images.githubusercontent.com/108881628/203301584-c7d9becc-62bf-43a9-9c92-ec33a48c7c0c.png)
![Screenshot_20221122-141536](https://user-images.githubusercontent.com/108881628/203301606-768ecc28-35f7-4830-8356-4e26c1b76e7e.png)
![Screenshot_20221122-141540](https://user-images.githubusercontent.com/108881628/203301620-22c083a9-6ab0-4d43-9406-34c76f51e0ef.png)
![Screenshot_20221122-141545](https://user-images.githubusercontent.com/108881628/203301636-87739daf-2a1a-4fb8-9e83-d086f637ea36.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22029)

**Comment by Someone-G** [comment] 2022-11-22 11:23
I tried to install other add-ons that are 100% Russified - they also come with English.

**Comment by cadeyrn** [comment] 2022-11-22 12:00
The current version is Firefox 107, not Firefox 105. Can you still reproduce after updating your Firefox? According to https://bugzilla.mozilla.org/show_bug.cgi?id=1795704#c27 it should be fixed in Firefox 107.

**Comment by cadeyrn** [comment] 2022-11-24 10:06
> indeed, in Firefox 107, extensions are installed with the Russian language.

Since the bug was fixed feel free to close this issue.

**Closed** 2022-11-24 11:55 UTC
Labels: 🐞 bug, needs:triage
