### ISSUE TITLE
[Bug] Firefox crashes on sign out

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7673] opened 2020-01-14 10:35 UTC
## Steps to reproduce
Click Sync Now from settings
Sign out (quickly)
click anywhere on screen 
### Expected behavior
Sign out
### Actual behavior
Crash
### Device information

* Android device: Asus Zenfone M1
* Fenix version: Nightly 200110 06:01 (Build #20100617)
28.0.0, 38520f41f
GV: 74.0a1-20200109094415

**Comment by jonalmeida** [comment] 2020-01-15 07:39
Sounds similar to https://github.com/mozilla-mobile/fenix/issues/6663#issuecomment-573018668 but can't say since we don't have logs to verify.

**Comment by jonalmeida** [comment] 2020-01-15 07:53
I did some sleuthing through our Sentry crash reports and was able to identify this crash: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6667676/events/37552554/

```
mozilla.appservices.push.StorageError: Error(

Storage Error: "No record for uaid:chid \"d6b88deb59a941c7879f1ae03bfb2782\":\"992a0f0542383f1ea5ef51b7cf4ae6c4\"")
    at mozilla.appservices.push.RustError.intoException(RustError.kt:8)
    at mozilla.appservices.push.PushManager.decrypt(PushManager.kt:16)
    at mozilla.components.feature.push.RustPushConnection.decrypt(Connection.kt:3)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invokeSuspend(AutoPushFeature.kt:15)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invoke
    at mozilla.components.feature.push.AutoPushFeatureKt$launchAndTry$1.invokeSuspend(AutoPushFeature.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
```

This is identical to the issue I thought it was.

**Comment by jonalmeida** [comment] 2020-01-15 07:53
Duplicate of https://github.com/mozilla-mobile/fenix/issues/6663.

**Closed by jonalmeida** 2020-01-15 07:53 UTC
Labels: 🐞 bug
