### ISSUE TITLE
[Bug] Open in app doesn't work with external links

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#9923] opened 2020-04-14 17:30 UTC
### Steps to reproduce
-Set Preview Nightly as default browser and "open in app" set to enabled 
-Tap on "play.google.com/music/m/Iwgmydz67i636h7aktocev2b7eq?t=NPR_News_Now" in another application (e.g. Gmail) 

### Expected behavior
-Link opens in a custom tab in Preview Nightly
-If you tap on "open in Firefox Preview Nightly" and then go to browser menu and tap on "open in app", it will open Google Play Music but it will have lost the deep link location

### Actual behavior
-Link should open in Google Play Music right away

### Device information

* Android device: Pixel 4
* Fenix version: Latest nightly

**Comment by kbrosnan** [comment] 2020-04-14 17:38
May be a dupe of #9438. Which identified https://bugzilla.mozilla.org/show_bug.cgi?id=1596825

**Comment by rocketsroger** [comment] 2020-05-04 20:07
Not related to https://bugzilla.mozilla.org/show_bug.cgi?id=1596825.  The issue here is that the current behaviour the that if user preference is if the user preference is not to launch in third party app by default, then launch fallback URL if possible.

**Comment by rocketsroger** [comment] 2020-05-08 16:38
With A-C version `41.0.20200508130136` nightly should have this fix.  Please verify.  Thanks!

**Comment by ebalazs-sv** [comment] 2020-05-11 13:05
I had tested this on Fenix Nightly 200415 (Build #21060608) with Motorola Moto G6 (Android 8) and Pixel 2 (Android 9) and I could reproduce the issue. The link from the description is opened in custom tab.
 
Verified as fixed on the latest Fenix Nightly 200511 (Build #21320626) with Motorola Moto G6 (Android 8) and Pixel 2 (Android 9). When tapping the link from the description, one is redirect to Google Play to enable and open Google Play Music.

I had filed the following related issue for the custom tab that remains open even if the link is opened in Google Play: https://github.com/mozilla-mobile/fenix/issues/10562.

**Comment by SS1113** [comment] 2020-05-22 02:40
Links still don't redirect to their respective apps for me on `Nightly 200519 18:01 (Build #2015741267)`.

**Comment by pinophyta** [comment] 2020-05-27 13:39
It works if you long press a link and select "Open in external app" option but not with a single tap.

**Comment by SS1113** [comment] 2020-05-27 13:54
@pinophyta Yes, this issue is talking about single tapping the link redirects to the destination app. I don't know why is this issue closed as fixed since it doesn't work in my end. I can still reproduce the issue #10436

Tested on `Nightly 200527 06:01`, Motorola One Power, Android 10.

**Comment by pinophyta** [comment] 2020-05-27 15:38
@SS1113 agreed. Single tapping is still broken.

**Comment by ebalazs-sv** [comment] 2020-05-28 08:41
I had tested this on the latest Fenix Nightly Build 21490606 with Motorola Moto G6 (Android 8) and Samsung Galaxy Tab S3 (Android 8) and I could not reproduce the issue following the steps:

1. Launch Fenix Nightly and go to the three dot menu -> Settings -> Set as default browser;
2. Enable the toggle to make Fenix Nightly your default browser;
3. Go to the three dot menu -> Settings and enable "Open links in apps"
4. Go to the Gmail application and tap on "play.google.com/music/m/Iwgmydz67i636h7aktocev2b7eq?t=NPR_News_Now";

The page opens in Google Play Music app. 

@pinophyta What device and Fenix version did you use for testing this issue?

I will reopen this issue for further investigation since it is reproducible on recent builds, that are mentioned in the previous comments. Thanks!

**Comment by pinophyta** [comment] 2020-05-28 14:20
@ebalazs-sv  with the above settings youtube/reddit/play music links open in firefox. Desired behaviour is to open those in external app. Long pressing and selecting "Open link in external app" does work.
Fenix Nightly 200527 (Build # 21480608) / galaxy note 9

**Comment by rocketsroger** [comment] 2020-06-16 16:17
@SS1113 though this is looks similar to https://github.com/mozilla-mobile/fenix/issues/10436.  Underlying issue is very different.  I'll reopen https://github.com/mozilla-mobile/fenix/issues/10436 to track your issue.  Since this is fixed using the STR stated in the issue, I will close it.

**Closed by rocketsroger** 2020-06-16 16:17 UTC
Labels: Feature:OpenInApp, eng:qa:verified, 🐞 bug

**Comment by SS1113** [comment] 2020-06-16 16:46
@rocketsroger I was sent to this issue by your QC engineer and they closed it as a duplicate of this bug. To be really frank I'm tagging people left and right including the developers as well cause I knew the bug I reported wasn't a duplicate of this bug as you are already saying.


Now if you can check if this issue: #10838 is the same as the one I filed or not, it'd be really helpful for me!

**Comment by rocketsroger** [comment] 2020-06-16 16:49
> Now if you can check if this issue: #10838 is the same as the one I filed or not, it'd be really helpful for me!

I've assigned https://github.com/mozilla-mobile/fenix/issues/10838 to me as well.  I will investigate in both to see if they are the same issue.  Thanks for bringing this issue to our attention and I'll be looking into this as soon as I can.

**Comment by ebalazs-sv** [comment] 2020-06-22 10:39
> I can still reproduce the issue #10436 on `Nightly 200610 06:00`.
> 
> Device: Motorola One Power, Android 10.
> 
> @ebalazs-sv can you try with the issue #10436? And confirm if it is reproducible for you?

@SS1113 Hi! The late reply is due to the PTO. 
I tested the scenarios mentioned in the description of #10436, on the latest Fenix Nightly Build #217406609 from 6/22 with Motorola Moto G6 (Android 8):
- for the first scenarios, the link opens in a custom tab;
- for the second scenario, the link opens in the YouTube app.
