### ISSUE TITLE
[Bug] Missing video control bar on rottentomatoes using a Samsung Galaxy S7

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4148] opened 2019-07-18 13:17 UTC
## Steps to reproduce
1. Navigate to https://www.rottentomatoes.com/m/the_art_of_self_defense_2019/
2. Play the video

### Expected behavior
Video is properly played and the control bar is available.

### Actual behavior
Video starts to play without the video control bar being available

### Device information

* Android device: 
• Samsung Galaxy S7 (Android 7)

* Fenix version: Nightly Build #11990109 from 18/7

### Notes
► Video
![20190718_161138](https://user-images.githubusercontent.com/51314259/61460411-5e4fc800-a977-11e9-856a-3c9b3afcc379.gif)

 ✅ Works on the following devices:
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

**Comment by ekager** [comment] 2019-08-06 21:54
This is weird that this is a webcontent bug that is device specific :/ Could you retest on that exact device on master and see if it's still happening?

**Comment by AndiAJ** [comment] 2019-08-07 09:02
Hi, re-tested on latest Fenix Nightly Build #12190111 from 7/8 using a Samsung Galaxy S7 (Android 7) and the issue is still there.
**On the other hand, no issues encountered on Fennec.**

**Comment by cpeterso** [comment] 2019-09-16 19:21
@AndiAJ - Do you see the video controls if you tap the video or rotate your phone to landscape orientation? On my Moto G5, when the video starts playing, I don't see the video controls in Fenix, Fennec, or Chrome unless I tap the video or rotate my phone.

**Comment by AndiAJ** [comment] 2019-09-17 06:58
@cpeterso Still no luck on Nightly Build #12590611 from 16/9 using a Samsung Galaxy S7 (Android 7).
I've tapped the video and rotated the phone but the video controls are still missing.
► Video
![20190917_094902](https://user-images.githubusercontent.com/51314259/65018394-a8cad200-d931-11e9-80ca-a62c003c45ab.gif)

**Comment by cpeterso** [comment] 2019-09-17 17:06
Do the video controls appear as expected in Fennec 68 and Chrome on the Galaxy S7?

Does turning of Tracking Protection in Fenix fix the problem? I can't tell from looking at the page on my phone if the video controls are part of the web page or if they are native system UI. Since this problem only seems to affect the Samsung Galaxy S7, I wonder if this is a native system UI problem.

In the meantime, I filed a new bug report for the Gecko Media team: https://bugzilla.mozilla.org/show_bug.cgi?id=1581906

**Comment by AndiAJ** [comment] 2019-09-19 07:00
@cpeterso I've checked on Fennec 68.1.1 (Playstore) & Chrome and in both cases the video control bar is available.
On the other hand, On Fenix Nightly Build #12611805 from 19/8 with or without tracking protection the video control is not displayed.

**Comment by cpeterso** [comment] 2019-09-19 18:41
Thanks! A Firefox engineer is able to reproduce the bug on his Samsung Galaxy S8, so this bug might be related to Samsung code. There is more discussion in Bugzilla here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1581906#c3

**Comment by cpeterso** [comment] 2019-09-25 18:58
Adding the `b:webcompat` label and removing the `needs:gv` label because this bug was determined to be a webcompat bug, not a Gecko bug. The Bugzilla bug has been moved from Gecko Core to Web Compatibility: https://bugzilla.mozilla.org/show_bug.cgi?id=1581906#c7

**Comment by ekager** [comment] 2020-12-11 05:29
Closing because this has been filed with the correct team. Nothing Fenix can do here.

**Closed by ekager** 2020-12-11 05:29 UTC
Labels: P3, b:web-content, b:webcompat, 🐞 bug
