### ISSUE TITLE
[Bug] Tab tray: unnecessary animation/repaint when opening tab tray

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#13428] opened 2020-08-09 14:09 UTC
## Steps to reproduce

Open the tab tray with several tabs

### Expected behavior

The tab tray opens without unwanted animation&repaint that delays it

### Actual behavior

See this video and the repaint that is happening:

https://photos.app.goo.gl/Q88Qt3UmfEC2Ep2bA

### Device information

* Android device: Redmi Note 7 Android 9
* Fenix version: #2015756915

**Comment by yoasif** [comment] 2020-08-09 17:49
Dupe of https://github.com/mozilla-mobile/fenix/issues/13293

**Comment by liuche** [comment] 2020-08-10 16:24
Please follow along in the work being done in #13293

**Closed by liuche** 2020-08-10 16:24 UTC
Labels: needs:triage, 🐞 bug
