### ISSUE TITLE
[Onboarding] Colours need updating

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7606] opened 2020-01-10 20:35 UTC
Hi, 

Please reference mock below for updated colours. Thanks

![Onboarding spec 2](https://user-images.githubusercontent.com/5992746/72190669-28dbe280-33ce-11ea-9d92-521af9501610.png)

**Comment by ekager** [comment] 2020-01-10 23:04
@apbitner mentioned a different color for the light theme cards here: https://github.com/mozilla-mobile/fenix/pull/7471#issuecomment-572239453

Could we confirm which color we are going with for these cards?

**Comment by apbitner** [comment] 2020-01-13 21:29
@ekager Sorry for any confusion, Amy's spec above is correct

**Comment by joshvocal** [comment] 2020-01-16 03:43
Could I take this one?

**Comment by ekager** [comment] 2020-01-17 17:52
Sure @joshvocal !

**Comment by joshvocal** [comment] 2020-01-22 12:19
If anyone else reading this wants to take this issue, you can take it instead of me.

**Comment by tvenissat** [comment] 2020-01-22 21:20
I would like to work on this. Can you assign this task to me @ekager?

**Comment by tvenissat** [comment] 2020-02-01 22:47
@AmyYLee Do you have drawable assets for the unselected theme images like the one shown below (light and dark theme variants)? 
![Screenshot from 2020-02-01 16-35-00](https://user-images.githubusercontent.com/10354465/73600064-f3c83900-4510-11ea-9cee-9108e8716213.png)

**Comment by AmyYLee** [comment] 2020-02-03 12:10
> @AmyYLee Do you have drawable assets for the unselected theme images like the one shown below (light and dark theme variants)?
> ![Screenshot from 2020-02-01 16-35-00](https://user-images.githubusercontent.com/10354465/73600064-f3c83900-4510-11ea-9cee-9108e8716213.png)

@tvenissat Hi, can you be more specific? Which asset do you need and in what format? Thanks

**Comment by apbitner** [comment] 2020-02-05 20:15
@tvenissat I provided these assets for another contributor on https://github.com/mozilla-mobile/fenix/issues/6980, please let me know if you need anything different

[Illustration - Toolbar Positions.zip](https://github.com/mozilla-mobile/fenix/files/4161854/Illustration.-.Toolbar.Positions.zip)

**Comment by tvenissat** [comment] 2020-02-08 02:17
@AmyYLee @apbitner Sorry for taking so long. The assets in that zip file are not the assets needed. To be clear, I need [this asset](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/drawable-xhdpi/onboarding_light_theme.png) recolored with a grey border and [this asset](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/drawable-xhdpi/onboarding_dark_theme.png) recolored with a grey border. The two assets I linked are currently used to represent the active theme since they have colored borders. I need two more assets with grey borders to represent the inactive theme.

**Comment by mcarare** [comment] 2020-02-10 12:01
@tvenissat The assets do not contain the radio button. You do not need to change the image, just the radio button colour for selected.

**Comment by tvenissat** [comment] 2020-02-10 16:16
@mcarare 

> The assets do not contain the radio button.

I never mentioned the radio button. The radio button is just shown in the design document and I didn't remove it (I'm not too familiar with image editing). The border color in the image is not done programmatically but is a part of the image itself. I can change the radio button color programmatically but I cannot change the border of the image without being provided with the asset.

![Screenshot from 2020-02-10 09-52-17](https://user-images.githubusercontent.com/10354465/74165872-572a2900-4beb-11ea-9af5-7e48f98f1a1c.png)

You are correct regarding this image. Changing the enabled radio button color to match the image border color, which appears to be #5A30C5, is all that needs when the light theme is enabled by the user. I need the same asset with a grey border to represent the light theme not being enabled by the user, as the image below demonstrates.

![Screenshot from 2020-02-10 09-52-26](https://user-images.githubusercontent.com/10354465/74165879-58f3ec80-4beb-11ea-82aa-6074baf4dc4e.png)

The problem is that this asset is not in the repository as far as I can tell. I need the theme image with a grey border to represent the disabled state. I need this for both light and dark theme images as specified in the design document.

I may be misunderstanding the design document but I think these 2 assets are necessary.

**Comment by apbitner** [comment] 2020-02-11 15:13
@tvenissat I believe you are correct, however, it appears the gray border was never implemented for the Theme onboarding card illustrations so let's not worry about it for now. I would rather just be consistent with the other card which appears to only use purple borders.

**Comment by tvenissat** [comment] 2020-02-11 16:32
@apbitner Sounds good.

**Comment by tvenissat** [comment] 2020-02-13 23:05
@AmyYLee What is the radio button color used here? I can't seem to find it anywhere else.
![Screenshot from 2020-02-13 17-00-39](https://user-images.githubusercontent.com/10354465/74486406-81494880-4e82-11ea-989c-5d7012ce3cb2.png)

**Comment by AmyYLee** [comment] 2020-02-14 19:13
> @AmyYLee What is the radio button color used here?
> ![Screenshot from 2020-02-13 17-00-39](https://user-images.githubusercontent.com/10354465/74486406-81494880-4e82-11ea-989c-5d7012ce3cb2.png)

Hi, 

The radio buttons and selected outline should be the follow. Thanks

Dark Theme:#9059FF
Light Theme:#592ACB

**Comment by tvenissat** [comment] 2020-02-18 20:55
@AmyYLee Thanks! I am close to being finished. I just have a few questions before submitting a pull request. 

1. What is the color used by the radio button when not selected (for Light and Dark themes if not the same)?
![Screenshot from 2020-02-18 14-39-31](https://user-images.githubusercontent.com/10354465/74776094-9516f500-525c-11ea-9c9f-bc1fe26ade69.png)

1. Should the new radio button colors be applied to all radio buttons in the onboarding layout? For example, should it be applied to the "Take a position" card too? I don't mean to offend, but it looks a bit inconsistent to me and I want to make sure.
![Screenshot_20200218-144838_Firefox Preview](https://user-images.githubusercontent.com/10354465/74776836-ed022b80-525d-11ea-897d-2e958628e17a.jpg)

If anything looks wrong, let me know and I'll make the changes. Thanks.

**Comment by AmyYLee** [comment] 2020-02-19 21:41
> @AmyYLee Thanks! I am close to being finished. I just have a few questions before submitting a pull request.
> 
>     1. What is the grey color used by the image border (for Light and Dark themes if not the same)?
>        ![Screenshot from 2020-02-18 14-39-31](https://user-images.githubusercontent.com/10354465/74776094-9516f500-525c-11ea-9c9f-bc1fe26ade69.png)
> 
>     2. Should the new radio button colors be applied to all radio buttons in the onboarding layout? For example, should it be applied to the "Take a position" card too? I don't mean to offend, but it looks a bit inconsistent to me and I want to make sure.
>        ![Screenshot_20200218-144838_Firefox Preview](https://user-images.githubusercontent.com/10354465/74776836-ed022b80-525d-11ea-897d-2e958628e17a.jpg)
> 
> 
> If anything looks wrong, let me know and I'll make the changes. Thanks.

@tvenissat Hi!

I've attached specifications for the elements. Yes these should be applied consistency across all radio buttons in Onboarding. I also marked the button colour as well which should be applied to "Browse Privately" and "Your Privacy" cards. Let me know if you have any questions. Thank you!

![Screen Shot 2020-02-19 at 4 37 16 PM](https://user-images.githubusercontent.com/5992746/74879211-a5030780-5336-11ea-88ad-4b4c75f00a42.png)
![Screen Shot 2020-02-19 at 4 40 28 PM](https://user-images.githubusercontent.com/5992746/74879234-b3512380-5336-11ea-8507-475ebd5b5fd9.png)
![Screen Shot 2020-02-19 at 4 40 21 PM](https://user-images.githubusercontent.com/5992746/74879236-b3e9ba00-5336-11ea-8876-a29c7760c13d.png)

**Comment by darkwing** [comment] 2020-02-24 21:52
@tvenissat How's it going with this?  Any further questions?  Thank you!

**Comment by tvenissat** [comment] 2020-02-26 20:23
@AmyYLee Sorry for the late reply. I've made the changes you specified. The button background color and the button text link color for the dark and private themes don't look quite right to me so I may have made a mistake or misunderstood you. I changed the button text link color as you specified in the original document and re-added the button backgrounds with the new colors. Also, since the private theme wasn't mentioned I kept the colors the same.

Light theme:
```xml
<color name="onboarding_card_button_background_light_theme">#F0F0F4</color>
<color name="onboarding_card_text_link_light_theme">#20123A</color>
<color name="onboarding_normal_radio_button_light_theme">#9915141A</color>
<color name="onboarding_activated_radio_button_light_theme">#592ACB</color>
```
![Screenshot_20200226-130455_Firefox Preview](https://user-images.githubusercontent.com/10354465/75383295-b94c8480-58a1-11ea-88cf-db37e68c85fc.jpg)

Dark theme:
```xml
<color name="onboarding_card_button_background_dark_theme">#4A4A55</color>
<color name="onboarding_card_text_link_dark_theme">#9059FF</color>
<color name="onboarding_normal_radio_button_dark_theme">#99FBFBFE</color>
<color name="onboarding_activated_radio_button_dark_theme">#9059FF</color>
```
![Screenshot_20200226-130510_Firefox Preview](https://user-images.githubusercontent.com/10354465/75383306-bce00b80-58a1-11ea-9da8-9093a79949b4.jpg)

Private theme:
```xml
<color name="onboarding_card_button_background_private_theme">#1FFBFBFE</color>
<color name="onboarding_card_text_link_private_theme">#9059FF</color>
<color name="onboarding_normal_radio_button_private_theme">#99FBFBFE</color>
<color name="onboarding_activated_radio_button_private_theme">#9059FF</color>
```
![Screenshot_20200226-130531_Firefox Preview](https://user-images.githubusercontent.com/10354465/75383313-bf426580-58a1-11ea-8491-9b0c484e0351.jpg)

Please correct me and I'll change it. Thank you again for putting up with all of my questions!



@darkwing Sorry for taking so long on this. I've been away from my development computer. Hopefully, I should be done soon if nothing else comes up (a man can dream lol).

**Comment by AmyYLee** [comment] 2020-02-28 20:53
@tvenissat Hi, I marked up the edits. Hope this is clear

![Release](https://user-images.githubusercontent.com/5992746/75586453-7544b580-5a42-11ea-8ee9-0a3fcf93a108.png)

**Comment by apbitner** [comment] 2020-03-02 16:40
Related ticket for Private Browsing Mode onboarding w/ specs - https://github.com/mozilla-mobile/fenix/issues/8643

**Comment by tvenissat** [comment] 2020-03-03 02:11
@AmyYLee Thank you! Yes, I'll attach a scrolling screenshot if I can manage to take one. Scrolling screenshots are broken (the "hairline" in my screenshot was caused by this) right now on my phone and I need to figure out why.

@apbitner Thank you for the link! I was curious if the private theme colors were finalized or not. I'll make sure I don't touch any more of the private theme colors in this issue. If anything needs to be removed just let me know.

**Comment by tvenissat** [comment] 2020-03-03 21:32
@AmyYLee Here are the full-length screenshots I promised. For now, I have only managed to make it work correctly with the dark theme. I will see if I can figure out what is causing this issue (I think the toolbar or toolbar position may be the problem).


<details>
  <summary>Dark Theme Screenshot</summary>

![Screenshot_20200303-135849_Firefox Preview](https://user-images.githubusercontent.com/10354465/75814800-fe682f00-5d57-11ea-99af-09d930667e9a.jpg)

</details>


<details>
  <summary>Light Theme Screenshot</summary>

![Screenshot_20200303-140426_Firefox Preview](https://user-images.githubusercontent.com/10354465/75814876-1c359400-5d58-11ea-8dd2-86c29a15b7dc.jpg)

</details>


![Screenshot from 2020-03-03 15-27-42](https://user-images.githubusercontent.com/10354465/75821295-97e90e00-5d63-11ea-8f6e-af7a32447357.png)
![Screenshot from 2020-03-03 15-28-01](https://user-images.githubusercontent.com/10354465/75821298-9881a480-5d63-11ea-804c-7db37a0a8f76.png)

The assets needed to implement these frames/borders (used by the toolbar position and theme chooser sections) are not in the repository (still not finalized?) and I cannot make the necessary changes until they are added. Otherwise, I believe all of the changes that I can make at this time have been made. If you notice anything that needs to be changed, let me know and I'll fix it.

**Comment by apbitner** [comment] 2020-03-16 17:41
@tvenissat Please let me know exactly what assets you need and I'm happy to provide them.

**Comment by Mugurell** [comment] 2020-03-17 12:40
Please note that I've just updated the themes images for rtl - https://github.com/mozilla-mobile/fenix/issues/8693
The current onboarding - themes selection assets only have the purple border.

**Comment by apbitner** [comment] 2020-03-17 16:51
I am attaching what I hope are all assets needed for gray borders. Please let me know if there are any issues.

[Gray Border Assets.zip](https://github.com/mozilla-mobile/fenix/files/4344663/Gray.Border.Assets.zip)

**Comment by Mugurell** [comment] 2020-03-17 18:31
@apbitner Following https://github.com/mozilla-mobile/fenix/issues/8693 we'll still need RTL theme picker images with gray borders.

**Comment by apbitner** [comment] 2020-03-19 15:17
@Mugurell Here are the RTL gray border assets.

[RTL Gray Borders.zip](https://github.com/mozilla-mobile/fenix/files/4355318/RTL.Gray.Borders.zip)

**Comment by BranescuMihai** [comment] 2020-04-01 16:31
Since my work on #8643 is highly connected with this one and the only thing remaining are assets, I will take this task over there.

**Comment by tvenissat** [comment] 2020-04-08 15:48
@BranescuMihai Sounds good to me. Let me know if there is anything I can help you with.

**Comment by BranescuMihai** [comment] 2020-04-10 09:27
Thanks a lot @tvenissat for the work here, the code you wrote really helped me!

**Comment by softvision-miralobontiu** [comment] 2020-05-08 14:05
Verified on the latest Nightly build from 5/8 with Sony Xperia Z5 Premium (Android 7.1.1), and OnePlus 5T (Android 9). 

The colors are updated on the following:
- the selected/unselected radio button matches the border outlines, both on RTL languages, and LTR languages,
- the background of all cards matches the collection's background, both on RTL languages, and LTR languages. Please see the screenshots below:

![LTR](https://user-images.githubusercontent.com/40694158/81413041-71719580-914d-11ea-999b-bba60b150377.png)

![RTL](https://user-images.githubusercontent.com/40694158/81413048-76364980-914d-11ea-9dd6-84049c82bce8.png)


- @AmyYLee the "Read our privacy notice" button still has a background color, as it can be seen in the screenshot below:

![read](https://user-images.githubusercontent.com/40694158/81413066-7e8e8480-914d-11ea-9897-14e2492ca0ec.png)

I'll remove the qa:needed label, but not close the issue yet.

**Comment by BranescuMihai** [comment] 2020-05-12 08:14
@softvision-miralobontiu I used [this abstract](https://app.abstract.com/share/8feabb36-05ef-4ec0-a05a-e56582a05c5f?mode=design&sha=ad755708a24ae2f9bcc48facb9bdea84a7ca8b17) to guide myself, there the background is still included. Also there's a comment from Amy above that specifies the new button backgrounds.

@AmyYLee should the card buttons have backgrounds?

**Comment by AmyYLee** [comment] 2020-05-14 14:58
> @softvision-miralobontiu I used [this abstract](https://app.abstract.com/share/8feabb36-05ef-4ec0-a05a-e56582a05c5f?mode=design&sha=ad755708a24ae2f9bcc48facb9bdea84a7ca8b17) to guide myself, there the background is still included. Also there's a comment from Amy above that specifies the new button backgrounds.
> 
> @AmyYLee should the card buttons have backgrounds?

Hi @BranescuMihai 

Please follow the abstract document for reference for colours of buttons and backgrounds. 
I had mentioned to remove the button background colour earlier because our card colour wasn't white at the time but this is no longer the case. Thanks.

**Comment by softvision-miralobontiu** [comment] 2020-05-18 12:53
Considering AmyLee's comment from above, I will close this issue as verified as fixed.

**Closed by softvision-miralobontiu** 2020-05-18 12:53 UTC
Labels: Feature:Onboarding, eng:ready, help wanted, implementation review, 🐞 bug
