### ISSUE TITLE
[Bug] Scroll and display issues with url bar on top on outlook.office.com

### ISSUE THREAD

**Issue by flashcode** [mozilla-mobile/fenix#15021] opened 2020-09-12 11:19 UTC
## Steps to reproduce

1. Login on outlook.office.com
2. Scroll the inbox view.

### Expected behavior

Icons "Mails", "Calendar" and "People" are displayed on bottom, with no empty area below.

### Actual behavior

The icons are not displayed at bottom and are moving while scrolling, see the screenshot showing the empty area below these icons:

![Screenshot_20200912_124709_org mozilla firefox_beta](https://user-images.githubusercontent.com/1776783/92994392-1c2e0200-f4fa-11ea-8954-81740678fb17.png)

This is causing issues when clicking on icons or mails, the click position is not accurate and depends on the display/scroll issues.
This happens only when the Firefox URL bar is moved to top (default is bottom); everything works fine with the URL at bottom of page.

Note: I noticed the issue only on outlook.office.com but other sites may be affected as well.

### Device information

* Android device: Huawei Mate20pro, Android 10.1.0.279
* Fenix version: Firefox 80.1.2 (Build #2015761283) and Firefox Beta 81.1.0-beta.2 (Build #2015761659) (both affected)
* I have no addons installed.

**Comment by ekager** [comment] 2020-12-18 05:54
@flashcode can you still reproduce this?

**Comment by flashcode** [comment] 2020-12-18 07:05
@ekager: yes, I confirm the problem is still there with Firefox Beta 84.0.0-beta.4 (Build #2015780083).

**Comment by flashcode** [comment] 2020-12-18 07:07
For information, it does not happen always when scrolling, but you can reproduce every time when you switch from Mails to Calendar view.

**Comment by flashcode** [comment] 2020-12-18 07:12
And same problem with Firefox 84.1.1 (Build #2015781795) (weird, Firefox Beta version is older than Firefox on Android).

**Comment by ekager** [comment] 2020-12-18 07:14
Thanks! Closing as a dupe of https://github.com/mozilla-mobile/fenix/issues/14821

**Closed by ekager** 2020-12-18 07:14 UTC
Labels: Feature:Toolbar, eng:qa:needed, 🐞 bug
