### ISSUE TITLE
[Bug]: When visiting a page with Bangla text, the URL doesn't render that text in the URL box

### ISSUE THREAD

**Issue by Oymate** [mozilla-mobile/fenix#22432] opened 2021-11-13 07:50 UTC
### Steps to reproduce

# Go to: https://bn.m.wikipedia.org/wiki/%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE_%E0%A6%AD%E0%A6%BE%E0%A6%B7%E0%A6%BE
# The URL doesn't render the Bangla text, while chromium browsers do

### Expected behaviour

The text in URL should render and be user editable

### Actual behaviour

It doesn't render properly.

### Android version

Android 

### Firefox release type

Firefox

### Firefox version

93.2.0

### Additional information

![Imagepipe_3](https://user-images.githubusercontent.com/50857856/141610672-1b49bab3-cdfb-4a5e-857e-17be68e08061.jpg)
![Imagepipe_5](https://user-images.githubusercontent.com/50857856/141610674-b5ba7893-6fe9-4779-8ca6-a4bf80e345dd.jpg)

**Comment by SoftVision-LorandJanos** [comment] 2021-11-15 07:29
Hi @Oymate. Thank you for your report!
I can confirm the issue you described is reproducible.
Tested on the latest Nightly 96.0a1 (2021-11-15T05:09:26.668704).
Verified it on Chrome as well where it is not reproducible.
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by Mugurell** [comment] 2021-11-15 14:13
Looks like our font doesn't support these glyphs.
Would be interesting to check what font does Chrome uses.

**Comment by Oymate** [comment] 2021-11-30 08:00
Likely noto sans

**Comment by surajeet310** [comment] 2022-01-09 18:53
Can I work on this ?

**Comment by Mugurell** [comment] 2022-01-10 06:48
> Can I work on this ?

Sure! Thank you!

**Comment by surajeet310** [comment] 2022-01-11 06:56
Can you tell me where to begin ?

**Comment by Mugurell** [comment] 2022-01-20 15:26
There is work being done to standardize the fonts used in the app so first I think we should consider that the url containing these glyphs can appear in multiple places in the app (like url bar, awesomebar, bookmarks, history) which means that a font supporting these should be used in much the app.
Asking @topotropic if changing the font used in all places where an url can be seen to support more glyphs is considered.

**Comment by Mugurell** [comment] 2022-01-20 15:29
> Can you tell me where to begin ?

Based on the above we first need to decide on the opportunity of this kind of a change.
Then we'd need to know which fonts support these glyphs and set using a custom font agreed by UX in multiple places in the app.
I realize this is a bit more complex than a `good first issue` but it is possible the community may know more about these fonts so I'll change the label to `help wanted`.

**Comment by Alexandru2909** [comment] 2022-02-02 14:40
Hi, I believe this is not a problem with Fenix. Tracing the url change callbacks to [GeckoSession](https://searchfox.org/mozilla-central/rev/fe800a7fd291db3c4b3e498cfe12ef2097662290/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSession.java#353), the string dispatched by the state change is formatted using the hexadecimal characters instead of their unicode representations. This behavior is identical for other other websites with Bangla URLs, other than Wikipedia.

**Comment by Alexandru2909** [comment] 2022-02-02 15:05
Submitted the issue to [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1753223)

**Comment by kbrosnan** [comment] 2022-02-07 19:31
Looks like this is going to be handled on the GV side. Closing in favor of that bug.

**Closed by kbrosnan** 2022-02-07 19:31 UTC
Labels: 🐞 bug, Feature:Toolbar, help wanted, S4, qa-triaged, Needs-UX

**Comment by Oymate** [comment] 2022-05-27 13:14
Still not fixed from GV
