### ISSUE TITLE
[Bug] Crash on long-pressing one of the bottom 4 buttons in menu ('Add to bookmarks' 'Share' 'Page forward' 'Reload')

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#9387] opened 2020-03-25 04:16 UTC
Issue #8881 reopened because problem still occurs:

## Steps to reproduce
Open the menu (three dots icon, on the right side of the address bar) when on a web page. Hold down one of the 4 buttons at the bottom without text description (f.e. the reload button) for about one or two seconds.
(Not just tap and release the button quickly. Long-press the button, hold it, don't release your finger from the screen.)

### Expected behavior
No action, button animation appearing for touching the button.

### Actual behavior
Browser crashes after long-pressing the button for about one second. See screenshots below for detailed view.

### Device information

* Android device: Samsung Galaxy S9+ (Android 8.0.0)
* Fenix version:
Firefox Preview: '4.1.0'
Firefox Preview Nightly: 'Nightly 200324 06:00'

### Screenshots (4)
![Screenshot_20200325-051255_Firefox Nightly](https://user-images.githubusercontent.com/61639215/77501195-88874d00-6e57-11ea-8716-e81ee7d16130.jpg)
![Screenshot_20200325-051143_Firefox Nightly](https://user-images.githubusercontent.com/61639215/77501198-8c1ad400-6e57-11ea-8d2a-8748a083c8e6.jpg)
![Screenshot_20200325-051543_Firefox Nightly](https://user-images.githubusercontent.com/61639215/77501256-bff5f980-6e57-11ea-87fc-55031632c015.jpg)
![Screenshot_20200325-051155_Firefox Nightly](https://user-images.githubusercontent.com/61639215/77501266-c84e3480-6e57-11ea-8690-e7f5a34bbb46.jpg)

**Comment by BranescuMihai** [comment] 2020-03-25 12:40
Can't reproduce it, but I tried only on Android 10 devices and all variations of German language. Can someone please retest so we can have a stack trace? 

I'm thinking there might be a compatibility issue with the long-press contextual menu, so please try on Android 8.0 and German as device language.

**Comment by theFireProjet** [comment] 2020-03-26 02:22
> Can't reproduce it, but I tried only on Android 10 devices and all variations of German language. Can someone please retest so we can have a stack trace?
> 
> I'm thinking there might be a compatibility issue with the long-press content description, so please try on Android 8.0 and German as device language.

I've changed device language to English (United States), the bug still occurs.

**Comment by Diana-Rus** [comment] 2020-03-26 16:34
Hi, I checked the issue on Firefox Preview Nightly 200326 (Build #20860605) GV: 76.0a1-20200324093140.

Verified with:
- Google Pixel 3a (Android 10) ✔️
- Google Pixel 3 XL (Android 9) ✔️
- Samsung Galaxy S9 (Android 8) ❌
- Sony Xperia Z5 (Android 7) ✔️
- OnePlus A3 (Android 6.0.1) ✔️

**Samsung Galaxy S9 (Android 8) - Logcat for crash: 
[Samasung Galaxy S9 - Android 8.txt](https://github.com/mozilla-mobile/fenix/files/4388440/Samasung.Galaxy.S9.-.Android.8.txt)
**

**GIF:**
![20200326-181402](https://user-images.githubusercontent.com/49859863/77670960-917b3a00-6f8f-11ea-956e-6108c5df094f.gif)

Note:
- The issue reproduced only with Samsung Galaxy S9 (Android 8)
- The issue reproduced with "Bookmark", "Share", "Forward" and "Refresh".
- I reproduced with the app being set on multiple languages: English, German, Russian.

**Comment by shawnz** [comment] 2020-04-15 13:40
This is also occurring on my Moto e5 play with Android 8.

Firefox version: Nightly 200408 06:01 (Build #20990609)
38.0.20200407190120, 4c77753ca
GV: 77.0a1-20200407093520 AS: 0.55.0

**Comment by ekager** [comment] 2020-04-17 22:45
Crash looks like Unable to add window -- token

> 2020-03-26 18:23:47.304 30043-30043/? E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: org.mozilla.fenix.nightly, PID: 30043
>     android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@e39dae7 is not valid; is your activity running?
>         at android.view.ViewRootImpl.setView(ViewRootImpl.java:957)
>         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
>         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:100)
>         at com.android.internal.view.TooltipPopup.show(TooltipPopup.java:82)
>         at android.view.View.showTooltip(View.java:28235)
>         at android.view.View.showLongClickTooltip(View.java:28262)
>         at android.view.View.performLongClickInternal(View.java:6976)
>         at android.view.View.performLongClick(View.java:6916)
>         at android.view.View.performLongClick(View.java:6934)
>         at android.view.View$CheckForLongPress.run(View.java:26034)
>         at android.os.Handler.handleCallback(Handler.java:789)
>         at android.os.Handler.dispatchMessage(Handler.java:98)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6938)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by mcarare** [comment] 2020-04-27 07:39
Root cause issue is marked as fixed, even though it still reproduces.
https://issuetracker.google.com/issues/64461213.

**Comment by cnevinc** [comment] 2020-04-29 14:11
I think all devices with API level 26 (Android 8) will be affected. Should we use toast instead of TooltipText to work around this issue?  @mcarare

**Comment by mcarare** [comment] 2020-04-30 08:32
@cnevinc Yes, that is true. I am working on a custom fix for this in AC, using a `PopupWindow`.

**Comment by Diana-Rus** [comment] 2020-05-08 13:20
Hi, issue is fixed, with Samsung Galaxy S9 (Android 8) and HTC 10 (Android 8) on Nightly 5/8 .
GIF - Samsung Galaxy S9 (Android 8):
![20200508-155621](https://user-images.githubusercontent.com/49859863/81408914-cc53be80-9146-11ea-8d9a-209b50c54d28.gif)

Note:
- When long tapped, a pop up with description, is displayed for each tapped item. (When long tapping on a bookmarked page -popup displays Edit Bookmark)
- The popup disappears after a couple of seconds and they don't seem to affect the menu's functionality.
- Each option works as intended.

**Closed by Diana-Rus** 2020-05-08 13:20 UTC
Labels: AC-by-Fenix, b:crash, eng:qa:needed, eng:ready, help wanted, needs:investigation, 🐞 bug
