### ISSUE TITLE
[Bug] Can't swipe nor to select menu buttons on 90min.com

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4152] opened 2019-07-18 14:52 UTC
## Steps to reproduce
1. Navigate to 90min.com
2. Swipe the menu buttons
![rsz_screenshot_20190718-174300777777](https://user-images.githubusercontent.com/51314259/61467152-cdcbb480-a983-11e9-865a-8bad36bde47d.png)
3. Tap on any of the buttons 

### Expected behavior
Can swipe and select any of the buttons

### Actual behavior
Can't swipe nor to select any of the buttons

### Device information

* Android device: 
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)  

* Fenix version: Nightly Build #11990109 from 18/7

### Notes

<details>
    <summary>Video from Googe Pixel 3a Firefox Preview VS Chrome</summary>

►Firefox Preview
![20190718_173207](https://user-images.githubusercontent.com/51314259/61467438-4763a280-a984-11e9-93b8-7af9f71960ba.gif)

►Chrome
![20190718_173319](https://user-images.githubusercontent.com/51314259/61467706-c22cbd80-a984-11e9-83e4-ceb8f82b1d5d.gif)

</details>

**Comment by ekager** [comment] 2019-08-06 21:52
Can reproduce on Fennec, can't reproduce on Chrome
Opened: https://bugzilla.mozilla.org/show_bug.cgi?id=1571896

**Comment by ekager** [comment] 2020-12-17 00:25
This seems to be resolved by the site itself

**Closed by ekager** 2020-12-17 00:25 UTC
Labels: P3, b:web-content, needs:gv, 🐞 bug
