### ISSUE TITLE
FNX-5028 ⁃ [Bug] Qr and shortcut buttons invalid text colors

### ISSUE THREAD

**Issue by DoggoOfSpeed** [mozilla-mobile/fenix#1438] opened 2019-04-06 06:21 UTC
## Steps to reproduce
Press QR scanner or shortcuts

### Expected behavior
After pressing, text should become white(if white theme) and black if (theme is dark) 

### Actual behavior
The text becomes almost impossible to read after pressing the button

### Device information
* Android device: Huawei p20 lite ANE-LX1 (C432) 
Fenix version: 1.0.1914 built 4/5 12:35pm

![SVID](https://user-images.githubusercontent.com/28051112/55665771-91010500-584d-11e9-86c8-14b6a7f3f83a.gif)UNITO-UNDERSCORE!20190406!UNITO-UNDERSCORE!091310!UNITO-UNDERSCORE!1 1!
![SVID](https://user-images.githubusercontent.com/28051112/55665772-91010500-584d-11e9-87a4-771c407bc3eb.gif)UNITO-UNDERSCORE!20190406!UNITO-UNDERSCORE!091409!UNITO-UNDERSCORE!1 1!

**Comment by ekager** [comment] 2019-04-08 03:04
Dupe of #1421

**Closed** 2020-08-11 11:37 UTC
