### ISSUE TITLE
FNX-13170 ⁃ [Bug] Firefox Preview or nightly crashes on certain sites.

### ISSUE THREAD

**Issue by Zadeis** [mozilla-mobile/fenix#12139] opened 2020-06-30 19:05 UTC
## Steps to reproduce
Open any article on arsTechnica and scroll at or near the end of the article.

### Expected behavior
The browser should not crash.

### Actual behavior
The browser crashes.
Socorro link: https://crash-stats.mozilla.org/report/index/25a40724-bfcd-49ee-b244-2c62a0200624

Note: I have specifically provided a Socorro link for nightly as the crash report generated by 5.2 does not record enough information but both browsers crash in the same manner.

### Device information
* Android device: Samsung Note10+ (Qualcomm)
* Fenix version: Preview 5.2 or nightly Build #21810611

**Comment by ekager** [comment] 2020-06-30 19:23
Thanks for the report! Do you have any add-ons enabled?

**Comment by sblatz** [comment] 2020-06-30 19:36
I cannot reproduce this on my Galaxy S9 on the latest nightly. Maybe an add on issue as @ekager suggested?

**Comment by kbrosnan** [comment] 2020-06-30 19:44
This is not an addon issue. It is a Gecko WebRTC issue bz-1648123 and should be fixed on nightly

**Comment by Zadeis** [comment] 2020-06-30 19:47
I either fat fingered it or auto correct changed it but it should say arstechnica and not anandtech. Either way I've updated it in the original submission.

**Comment by kbrosnan** [comment] 2020-06-30 20:02
Your nightly build according to crash stats is out of date your build is from 2020-06-18-09:41:05. A current build is 2020-06-28-09:28:14. Please update your nightly to confirm this is fixed.

**Comment by Zadeis** [comment] 2020-06-30 20:18
Well I suppose that's what I get for putting off submitting this report for a week. It seems the latest nightly fixes the issue. I'll close it. Sorry for diverting your attention to something that had been fixed.

**Closed** 2020-08-11 05:50 UTC
Labels: b:crash, needs:gecko, 🐞 bug
