### ISSUE TITLE
Setting to choose how to open app intents

### ISSUE THREAD

**Issue by bifleming** [mozilla-mobile/fenix#7099] opened 2019-12-11 23:56 UTC
## User Story
- As a user, I would like to be able to globally choose to open all app intents within the browser OR by an external 3rd party application, so I can customize my browser behaviour to fit my preferences and not be asked every time. 

### Dependencies
mozilla-mobile/android-components#4950
Meta: #3177 
- [ ] GV  https://bugzilla.mozilla.org/show_bug.cgi?id=1600704

### Strings provided by Content Strategy
[label] Open links in apps
[microcopy] Use external apps (like Maps or YouTube) when possible

### Acceptance Criteria
- [x] I can choose to always open an app link intent inside the browser. 
- [x] I can choose to always open an app link with a 3rd party application.
- [x] If I choose to always open an app link within the browser, I still have the option of then opening that site in a supported 3rd party app (keep the menu option)
- [x] When this setting is enabled, app intents will launch in 3rd party native apps. When off, app intents will load in my browser
- [ ] When I tap on a deep link to open/download a 3rd party app that I already have installed, I see an "open in app" option in my browser OR the app page opens in the Play Store app where I can tap "Open" to open the app

**Comment by liuche** [comment] 2020-01-03 18:31
Seems like @rocketsroger will be doing all of this and handling the rest of the edge cases (with help from Fenix for frontend if needed).

**Comment by sblatz** [comment] 2020-01-16 16:45
@rocketsroger mentioned that this is waiting on https://github.com/mozilla-mobile/fenix/issues/5664

**Comment by sblatz** [comment] 2020-01-31 10:39
@rocketsroger Are you able to provide an update on this?

**Comment by rocketsroger** [comment] 2020-01-31 10:44
> @rocketsroger Are you able to provide an update on this?

Unfortunately no updates.  This issue requires a custom sheet to work as designed.

**Comment by sblatz** [comment] 2020-01-31 11:04
Mocks here: https://app.abstract.com/share/1a68a45a-52be-4576-b0f7-e85b6ed73834?mode=design&sha=e90a0086037e564b9c8745b9e8cd1f4df40a6e01

**Comment by sblatz** [comment] 2020-01-31 11:05
According to Roger this is something we can now do on the Fenix side. It should line up with the GV/AC API implementation. Let's take this over as a team.

**Comment by BranescuMihai** [comment] 2020-02-04 14:19
@liuche @rocketsroger short clarification: So basically this story is more or less adding a UI toggle that is the **opposite** of the one we now have in Settings ("Open links in apps")?

Also, what is the expected behaviour when the toggle is on, so we prevent 3rd party apps, however our browser does not support the protocol, such as 'mailto'? Right now, we get an 'Unknown protocol' error. Maybe we should check if our browser can handle it, and if not, then redirect to 3rd party app regardless of that toggle. 

**Sidenote**, maybe a bug: With the current implementation ('Open links in apps' set to on), most app deeplinks redirect us to the Store, however for Tinder, there seems to be another layer of redirecting, which results in the same 'Unknown protocol' error. This might be an edge-case that we should handle.

**Comment by vesta0** [comment] 2020-02-05 22:14
@BranescuMihai I don't think this story is the opposite of what we have now. In fact, I think this story is almost done and working as intended with the exception of the following:

- Opening a play store link still doesn't work. Tapping on playstore link opens the "Unknown Protocol" error page. This is the last acceptance criteria in the description of the issue ^^

- Regression on opening 'mailto' and similar intents. This used to work in previous versions. 

@sblatz and @rocketsroger is #5664 blocking the above 2 use cases?

**Comment by vesta0** [comment] 2020-02-05 22:23
I just saw the mocks posted above and now I understand where the confusion was. I think we should stick with the existing setting toggle and just make sure that the 2 issues I mentioned above are resolved.

**Comment by rocketsroger** [comment] 2020-02-10 18:54
> I just saw the mocks posted above and now I understand where the confusion was. I think we should stick with the existing setting toggle and just make sure that the 2 issues I mentioned above are resolved.

Understood.  I'll investigate and raise issue(s) if its not related to https://github.com/mozilla-mobile/fenix/issues/5664.  Thanks,

**Comment by rocketsroger** [comment] 2020-02-10 21:34
>     * Opening a play store link still doesn't work in many cases and seems to be more than just an edge case. I get the "Unknown Protocol" error page in all the following examples: Tinder, Facebook, Pinterest, Lyft, Uber, Pocket, and many more. 

This is confirmed to be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1600704

>     * Regression on opening `mailto` and `tel:`. This used to work in previous versions.

Can't reproduce this issue.  It works for me but requires to turn on `Open links in apps`.  Is this an expected behavior? or should we always launch `mailto` and `tel` links regardless of the user settings?

**Comment by rocketsroger** [comment] 2020-02-11 19:36
>     * Regression on opening `mailto` and `tel:`. This used to work in previous versions.

Opened an issue to track this https://github.com/mozilla-mobile/android-components/issues/5892

**Comment by rocketsroger** [comment] 2020-02-28 18:53
Confirmed with fixes from https://github.com/mozilla-mobile/android-components/issues/5892, https://github.com/mozilla-mobile/android-components/issues/5407 and https://bugzilla.mozilla.org/show_bug.cgi?id=1600704 the two issues @vesta0 stated have been fixed.  I'll wait for nightly before requesting QA verification.

**Comment by rocketsroger** [comment] 2020-03-02 16:10
>     * Opening a play store link still doesn't work in many cases and seems to be more than just an edge case. I get the "Unknown Protocol" error page in all the following examples: Tinder, Facebook, Pinterest, Lyft, Uber, Pocket, and many more.
> 
>     * Regression on opening `mailto` and `tel:`. This used to work in previous versions.

Please verify these two issues are fixed on nightly.  Thanks,

**Comment by Xefir** [comment] 2020-03-02 16:33
Sadly, seems like that not all cases is fixed. I succeeded to reproduce this bug (https://github.com/mozilla-mobile/fenix/issues/8880) myself with the authentication of the Tusky app.

For testing, install Tusky and try to log-in. It open Firefox and ask for Authorize, but after confirming, a "Unknown Protocol" page is displayed instead of going back to the app.

I tested on the latest Firefox Fenix Preview Nightly on Play Store.
Thank you for your work though.

**Comment by rocketsroger** [comment] 2020-03-02 16:42
> For testing, install Tusky and try to log-in. It open Firefox and ask for Authorize, but after confirming, a "Unknown Protocol" page is displayed instead of going back to the app.
> 

We have a issue tracking this.  https://github.com/mozilla-mobile/fenix/issues/7257.  This will require more fixes from GeckoView.

**Comment by rocketsroger** [comment] 2020-03-03 20:20
>     * Opening a play store link still doesn't work in many cases and seems to be more than just an edge case. I get the "Unknown Protocol" error page in all the following examples: Tinder, Facebook, Pinterest, Lyft, Uber, Pocket, and many more.
> 
>     * Regression on opening `mailto` and `tel:`. This used to work in previous versions.

Confirmed both cases are now fixed.  Please verify so this can be closed.  Thanks,

**Comment by softvision-miralobontiu** [comment] 2020-03-05 13:50
Verified as fixed on the latest Nightly build from 3/5 with Samsung Galaxy Note 8 (Android 9):
* opening a play store link sent me to PlayStore, tapping back, takes me back to Fenix, to the opened page,
* opening "email" and "telephone" takes me to an email app or to phone.

**Closed by softvision-miralobontiu** 2020-03-05 13:50 UTC
Labels: Feature:OpenInApp, eng:qa:needed, must
