### ISSUE TITLE
Favicon not used for shortcut on start screen

### ISSUE THREAD

**Issue by victor-50** [mozilla-mobile/fenix#16449] opened 2020-11-08 10:56 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
https://freecell.net 
add to start screen
### Expected behavior
Using the favicon (stylized "F")
### Actual behavior
System letter F
### Device & build information
* Device: MOTO 5S
* Build version: 82.1.1
### Notes
Shortcuts to some other websites do use the favicon. Previous version of FF worked ok. Not clear which. Had to recreate the shortcut while I lost the previous one made at least a year ago. 
Attachments:

**Comment by cadeyrn** [comment] 2020-11-08 11:49
It's working as intended because the site only has a 16x16 px sized favicon and that's too small for Firefox.

**Comment by kbrosnan** [comment] 2020-11-09 17:14
Closing as a duplicate.

**Closed by kbrosnan** 2020-11-09 17:14 UTC
Labels: needs:triage, 🐞 bug
