### ISSUE TITLE
[Bug]  youtube.com - Phone top info bar is displayed in full screen video view

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16436] opened 2020-11-06 18:51 UTC
## Steps to reproduce
1. Open the firefox
2. Go to youtube.com
3. Play any video
4. Tap full screen mode
5. Tap settings button and change video quality
### Expected behavior
The video will change quality and nothing extra will be displayed on the screen
### Actual behavior
When changing the quality, the informational top panel of the phone is displayed, which interferes with video viewing
### Device information
 Xiaomi Redmi Note 4X - Android 7.0
Vestel Venüs V3 - Android 6.0.1
* Android device: yes
* Fenix version: firefox beta 82.0.0
 
![image](https://user-images.githubusercontent.com/66958331/98403487-1aa43480-207a-11eb-98d8-63dd78926f23.png)

**Comment by s-ankur** [comment] 2020-11-06 19:03
I think this would be a duplicate of https://github.com/mozilla-mobile/fenix/issues/6814

**Comment by kbrosnan** [comment] 2020-11-18 02:32
Closing as a duplicate

**Closed by kbrosnan** 2020-11-18 02:32 UTC
Labels: needs:triage, 🐞 bug
