### ISSUE TITLE
[Bug] cnn.com doesn't load in Firefox Nightly on wifi

### ISSUE THREAD

**Issue by jrmuizel** [mozilla-mobile/fenix#18407] opened 2021-03-09 20:29 UTC
It seems to work in release and beta. Uninstall and reinstall did not fix the problem. It seems to load fine over LTE.

Nightly 210308

**Comment by jrmuizel** [comment] 2021-03-09 21:37
But why would it only be be broken in Firefox Nightly and not beta or release?

**Comment by LittleAngelwings** [comment] 2021-03-09 21:44
Don't now. But you can see, I have no problem with the site. Tried three devices. Android 8.1.0 (Tablet)  / 9.1.0 (Huawei Smartphone) and Android 9 at Chromebook with Chrome OS 88 (picture). All with strict preferences and uBlock Origin activated.

**Comment by LaurentiuApahideanSV** [comment] 2021-03-10 10:34
@jrmuizel I tried to reproduce your issue on the latest Firefox Nightly 210309 but was unable to. Could you provide us with further information on how to reproduce the issue?
### Devices used:
- Samsung Galaxy S9 (Android 8.0)
- OnePlus 6T (Android 9)

**Comment by J-Siu** [comment] 2021-03-14 21:12
@jrmuizel Pure speculation: Check if your nightly is using DoH or not. Maybe your wifi network is blocking DoH.

**Comment by LaurentiuApahideanSV** [comment] 2021-03-31 10:42
Since the reporter has not provided any more details regarding the issue and we are unable to reproduce it I will close it.

**Closed by LaurentiuApahideanSV** 2021-03-31 10:42 UTC
Labels: Feature:Browsing, qa-triaged, 🐞 bug
