### ISSUE TITLE
FNX-5255 ⁃ [Bug] I cannot see bottom part of page

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#1810] opened 2019-04-19 08:36 UTC
## Steps to reproduce
Visit https://www.reddit.com/r/firefox/comments/bendan/abouthome_and_aboutnewtab_suddenly_forcing_light/
Scroll down.

### Expected behavior
See all the comments.

### Actual behavior
Only some comments visible.

### Device information
* Android device: OnePlus 5t

**Comment by andreicristianpetcu** [comment] 2019-04-19 08:39
![Screenshot_20190419-113741_Settings](https://user-images.githubusercontent.com/922368/56415866-b5220480-6297-11e9-9fb6-eda05a4411ce.png)
![Screenshot_20190419-113720_Fenix](https://user-images.githubusercontent.com/922368/56415868-b94e2200-6297-11e9-8e76-6abbcb73a8dc.png)
![Screenshot_20190419-113443_Fenix](https://user-images.githubusercontent.com/922368/56415874-be12d600-6297-11e9-9bb0-ddf8d988adfe.png)

**Comment by kbrosnan** [comment] 2019-04-19 17:17
Dupe of #552

**Closed** 2020-08-11 13:00 UTC
