### ISSUE TITLE
[Bug] Fenix opens a "302 Moved Permanently"  tab, before opening native app

### ISSUE THREAD

**Issue by ikurek** [mozilla-mobile/fenix#12113] opened 2020-06-29 22:57 UTC
## Steps to reproduce
1. Enable "Open links in app" in Fenix settings
1. Click on link for website which has a native app installed on device, for example GitHub.com or Reddit.com

### Expected behavior
Fenix opens native app after clicking on link.

### Actual behavior
Fenix opens a new tab, with "302 Moved Permanently" text, and then opens native app.

### Device information
Tested on latest Nightly build available in Play Store, on Android 10 devices.

* Android device: Samsung Galaxy Tab S6 (Android 10), OnePlus 6 (Android 10)
* Fenix version: Nightly 200629 06:01

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2830)

**Comment by SS1113** [comment] 2020-06-30 00:48
I think it an useful feature. Let's say a link haa gone through a link shortner and then the respective app opens, in this case having a unshortened url would be really useful as I don't have to go through the shortened url again.

**Comment by igorkurek** [comment] 2020-06-30 10:13
@SS1113 I fail to see how opening an empty website with "302 Moved Permanently" warning may be considered a feature. This looks like a bad UX - returning from application requires more back presses to skip empty site, and it can generate lots of empty tabs.

**Comment by SS1113** [comment] 2020-06-30 11:56
@igorkurek okay, for me this is how it works for me; 

I visit a lot of website which have link shorteners applied to the links in them. Now what happens is that, I takes me a lot of time to unshorten them and when the webpage that contains unshortened URL finally comes around Fenix opens that in a webpage ( just containing the with the unshortened link) also redirects to the respective app as well. This way even if I close the particular app the unshortened link is always there in the Fenix and I can easily open that in that. Particular app by clicking 'Open in app' in 3-dot menu.

Of course if the Fenix team finds it unnecessary they can remove this behaviour and I can live with that too It is just that if this is the side effects of fixing 'Open links in app' then it's very good one for me. And if they are gonna keep it I suggest them some improvements. That's it.

**Comment by welcometochristown** [comment] 2021-02-10 23:30
I get this every time I open a reddit link from google. Its really annoying. Any word on when this might be fixed?

**Comment by chriswu000** [comment] 2021-08-02 13:11
This is really annoying and I suspect affects a lot of people. Any word on if this will be fixed?  Thanks!

**Comment by erenustun** [comment] 2021-08-03 23:05
Hi Fenix Team  Please remove this in the production app. The use case of @ghost is maybe 1% of users and they are tech savvy enough to install the beta or nightly app. This is super annoying and keeps me from switching from Chrome unfortunately. Please consider doing a poll and seeing for yourself what others think. This anti-feature stagnates the greatness Fenix can be! For privacy especially.

**Comment by ishouldmomo** [comment] 2021-09-27 16:43
I'm just here to +1 this, returning to firefox with an open '302 moved' tab is quite irritating.

**Comment by plwt** [comment] 2022-02-04 21:55
User feedback: https://support.mozilla.org/en-US/questions/1366855

**Comment by ivoros** [comment] 2022-03-31 22:39
It's still going on after more than 1.5 years after this issue was opened. Any word on this from the devs?

**Comment by AlexCrosby** [comment] 2022-05-01 18:38
I have noticed this bug happens when opening an app from a Google search results link, doesn't happen for other search engines like bing which correctly go back to search results page.

**Comment by patel8786** [comment] 2022-06-18 04:13
I switched from chrome about a month ago and I can't believe that this is something Firefox users have to deal with. It's so obviously wrong.
To make matters worse, if you go back to that tab later on it reopens the app. Really annoying and unprofessional

**Comment by CorDawg** [comment] 2022-07-01 05:24
It's absolutely insane that this still is a problem. I also have an app that I disabled default links on, but firefox still insists on opening that app instead of showing me the website.

**Comment by damiengu** [comment] 2022-07-09 14:52
This issue is still here...

**Comment by ryankhart** [comment] 2022-07-23 22:02
Still an issue for me, but I may have potentially useful info that may help pinpoint the cause.

When I install the "Google Search Fixer" add-on in the short list of mobile add-ons for Firefox on Android, it prevents this 302 moved error from happening, but it has the side effect of opening every other Reddit link in Firefox rather than my default Reddit app of choice.

**Comment by BartemX** [comment] 2022-08-26 09:28
And two years later the issue still remains...

**Comment by Jolg42** [comment] 2022-08-26 09:54
Since it seems that this issue is not moving anywhere, I decided to keep using Firefox on my Android, but I disabled `Open links in app` from the menu settings.

I guess I'll open Chrome or other when I need that. (or enable / disable again but that's also not optimal) 😢 

Not sure how it will turn out in the long term for me, but I'll manage.
I'm pretty sure that the current behavior can be very confusing for non-tech people. It can be very messy and weird already for me 😓

**Comment by alexhulbert** [comment] 2022-09-03 23:14
To me this is an annoyance and pretty bad UX. No other mobile browser does this.

**Comment by rocketsroger** [comment] 2022-09-06 14:06
I can take a look at this.  I've tried searching for something like "firefox reddit" and then tap on the link.  It opened the reddit app to r/firefox and when I returned to the tab it doesn't have "302 moved" error anymore.

Is there a good way to reproduce this problem?

**Comment by ishouldmomo** [comment] 2022-09-06 14:14
I don't have the Reddit app, but I'm amazed you didn't experience the issue.
I've just searched 'Wikipedia' (with Google as engine), clicked on first result (for the WIkipedia homepage) which took me to the Wikipedia app, and returning to Firefox gives me the 302 moved page as described. See attached screen recording. All add-ons disabled. Latest Google Play release (100.1.1) on Samsung A72 / Android 12.

https://user-images.githubusercontent.com/91489321/188657935-eb60ce49-8be4-4e6d-bc06-e443f1c5dffa.mp4

**Comment by rocketsroger** [comment] 2022-09-06 14:26
Please confirm that this issue is fixed in v105+.  Thanks

**Comment by SoftVision-LorandJanos** [comment] 2022-09-07 11:07
Managed to reproduce the issue with the latest RC (104.2.0).
Verified as fixed on the latest Beta (105.0b5) and on the latest Nightly 106.0a1 (2022-09-07) builds.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-09-07 11:07 UTC
Labels: 🐞 bug, eng:qa:needed, S2, Feature:OpenInApp
