### ISSUE TITLE
Close all tabs when closing Fenix via Android

### ISSUE THREAD

**Issue by FenixRevival** [mozilla-mobile/fenix#12940] opened 2020-07-25 15:48 UTC
### What is the user problem or growth opportunity you want to see solved?
When I use the Android 'recent app switcher' button to swipe out Fenix. I want, according to my setting, to close all the opened tabs. Add an option to re-open closed tabs in the next session.
If the user didn't choose to 'delete browsing data on quit' then it shouldn't do it. This is the current situation.

### Walkthrough
1. In setting check 'delete browsing data on quit' > check 'open tabs'
1. Open a few tabs
1. Use the 'recent app switcher' button (left/right of home button)
1. Swipe the app to close it or alternatively use the "Clear all" button
1. Open Fenix: no opened tabs
1. In the menu add an option to re-open closed tabs

### How do you know that this problem exists today? Why is this important?
Android by default use this as a way to quit and delete "live data". Legacy Firefox did it (and we had the option to reopen closed tabs), others browser do it that way to (android webview particularly).
The current situation of Fenix is an exception, and it cost more time to: open menu > click on 'quit' than to use the default Android behaviour.

**Comment by kbrosnan** [comment] 2020-07-25 21:24
Duplicate of #11853 which has been duped to #11582.

**Closed** 2020-08-28 22:58 UTC
Labels: needs:triage
