### ISSUE TITLE
[Bug]: Youtube - Refreshing the page, the theme is switch from dark to white

### ISSUE THREAD

**Issue by LaviniaL99** [mozilla-mobile/fenix#23930] opened 2022-02-23 11:05 UTC
### Steps to reproduce

1.  Navigate to Settings-> Customize
2. Set the theme to Dark
3. Go back to the Homepage and navigate to YouTube.com
4. Make sure that the background is dark and refresh the page
5. Verify if the dark theme is kept after the page is refreshed

### Expected behaviour

The dark theme must be kept after the Youtube page is refreshed.

### Actual behaviour

The dark theme is not kept after the Youtube page is refreshed -> the theme is switch from dark to white. Please see the video attached for evidence.

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

### Additional information

Notes:
- Same issue is present if the device theme is set to dark and **"follow device theme"** option is selected for the app.
- Tested on Chrome as well and the theme is not changing when the page is refreshed.
- Trying to reproduce the issue on the latest RC build and GeckoView Example but i'm not able to refresh the Youtube page.

https://user-images.githubusercontent.com/96047134/155306399-181a50d7-2775-4408-8a5b-a475519f0846.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19620)

**Comment by Alexandru2909** [comment] 2022-02-25 14:35
Hi @LaviniaL99 , I managed to reproduce the issue on the latest GV Example, by reloading using the three dot menu -> reload. Can you please confirm the issue is present on GeckoView Example too?

**Comment by LaviniaL99** [comment] 2022-02-25 14:42
Hello @Alexandru2909 

I retested the flow on GV Example and i was able to reproduce the issue.

**Device used:**
-Samsung S10E-> Android 10

**Comment by Alexandru2909** [comment] 2022-11-23 08:43
Opened [1802083](https://bugzilla.mozilla.org/show_bug.cgi?id=1802083) for this, so the GV team can take a look.

**Comment by rokejulianlockhart** [comment] 2022-12-02 22:57
This does not affect me anymore via Firefox Nightly.

**Comment by delia-pop** [comment] 2022-12-28 14:44
Closing this ticket in the favor of the https://bugzilla.mozilla.org/show_bug.cgi?id=1802083 opened above.

**Closed by delia-pop** 2022-12-28 14:44 UTC
Labels: 🐞 bug, b:web-content, S3, needs:triage
