### ISSUE TITLE
FNX2-15096 ⁃ More natural order of options in the 3 dot menu?

### ISSUE THREAD

**Issue by nc-x** [mozilla-mobile/fenix#12230] opened 2020-07-03 08:50 UTC
Currently, `Quit` is the first option in the menu followed by `Settings` (when a webpage is opened, these options are preceded by the options for desktop site, adding to desktop etc., however...) . However, in most mobile/desktop apps these are the last options (And IME, being the first option means more chances of accidently being pressed).

IMO option to open new tab should come at the top https://github.com/mozilla-mobile/fenix/issues/12229 followed by all the bookmarks and history stuff, with settings,quit and help in the end.

I know a lot of discussions have probably went into designing things the way they are, but this menu currently feels counter-intuitive to me, so I opened the issue.

Also, IMO, Synced Tabs option should not be visible if syncing tabs is disabled in the settings.

And, I would also prefer to have an option to hide the What's New option (and maybe also Help option) because considering small screens of many phones, these options clutter the menu (and I don't have any need for them :D)

Edit: I just realized that more than the order of options, the existence of Quit option itself is unnatural. Because I have never really seen it in any android app I use, because the natural way that most people quit an app is throught the [recents screen](https://developer.android.com/guide/components/activities/recents)

**Comment by SS1113** [comment] 2020-07-03 15:47
Thanks for filing your feedback! 

>Also, IMO, Synced Tabs option should not be visible if syncing tabs is disabled in the setting

This has already been asked here: https://github.com/mozilla-mobile/fenix/issues/11995

>And, I would also prefer to have an option to hide the What's New option (and maybe also Help option) because considering small screens of many phones, these options clutter the menu (and I don't have any need for them :D)

This has also been asked here: https://github.com/mozilla-mobile/fenix/issues/11795

**Comment by ekager** [comment] 2020-07-06 19:00
@nc-x "Quit" has to be enabled via a setting. If you didn't enable it, then there's a bug.

**Comment by SS1113** [comment] 2020-07-06 23:17
>I just realized that more than the order of options, the existence of Quit option itself is unnatural. Because I have never really seen it in any android app I use, because the natural way that most people quit an app is throught the recents screen

https://github.com/mozilla-mobile/fenix/issues/5865


Currently the "quit" button is m has to be enabled manually as **ekager** already mentioned this is used when making the browser clear days such as history, cookies, etc... The above mentioned issue is also thinking about removing the "quit" button but I'm not with it as it is currently very useful in clearing data on browser quit.

**Comment by nc-x** [comment] 2020-07-07 07:31
Oh, I didn't know the `Delete browsing data on quit` option actually adds the menu option for quit. I am not an android developer, so I don't know anything about this but is there a reason why delete browsing data (if enabled) couldn't/shouldn't be done when exiting application normally through recents screen?
Anyways, IMO (YMMV) Quit should not be the first menu entry, because first menu entry is very easy to be mistakenly pressed (due to muscle memory or just accident).
(I have disabled the Quit option for myself for now, so you may close this issue if you think that this is a non-issue)

**Comment by SS1113** [comment] 2020-07-07 08:23
>Anyways, IMO (YMMV) Quit should not be the first menu entry, because first menu entry is very easy to be mistakenly pressed (due to muscle memory or just accident).

Yes, this is the reason why I request this feature: https://github.com/mozilla-mobile/fenix/issues/9266 but the position of the `Quit` button should also be changed. But with the talks to remove the `Quit` button altogether #5865 , I don't know what to suggest.

**Comment by liuche** [comment] 2020-08-28 23:31
closing as dupe of #14320

**Closed by liuche** 2020-08-28 23:31 UTC
Labels: needs:triage
