### ISSUE TITLE
Sent tabs not received by Fenix until Sync Now button clicked

### ISSUE THREAD

**Issue by selimsumlu** [mozilla-mobile/fenix#16721] opened 2020-11-23 13:00 UTC
I've been trying to send tabs from desktop Nightly to Fenix Nightly. Sending tabs are always successful, but I don't recieve them on my Android device until I manually sync my account even if Fenix says "Last synced: 0 minutes ago". Sending tabs from Fenix to desktop works fine.

This has been an ongoing issue for at least 10 days. Removing and restoring the Firefox account on Fenix didn't help.

Device: realme 6
Android version: 10

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8885)

**Comment by kbrosnan** [comment] 2020-12-02 20:03
@jonalmeida You have some issues tracking this. Is there something we can dupe here?

**Comment by jonalmeida** [comment] 2020-12-02 20:11
There isn't a Fenix issue that's tracking the issue so let's use this one.

This is the AutoPush bug: https://github.com/mozilla-services/autopush/issues/1445
The AC PR when it was first seen: https://github.com/mozilla-mobile/android-components/pull/9013

**Comment by mhammond** [comment] 2020-12-09 22:27
FTR, https://github.com/mozilla-mobile/android-components/pull/9112 (a PR that should be ready to land once reviewed) and https://github.com/mozilla/application-services/issues/3751 (an issue with no PR yet, but will probably get one in a week or so) should help significantly with this.

**Comment by ddarfantasy** [comment] 2021-01-30 08:08
Still reproducible and causing trouble in 85.1.1 ...

**Comment by jonalmeida** [comment] 2021-02-09 10:35
The root cause isn't specific to only Send Tab, so I'm using https://github.com/mozilla-mobile/fenix/issues/17272 to track this in Fenix.

For Send Tab behaviour, we can leave this ticket open to verify it works after the autopush bug is fixed.

**Comment by shalak** [comment] 2021-03-04 23:02
Still reproducible and causing trouble in 86.0 (64-bit)

**Comment by shalak** [comment] 2021-03-04 23:04
Still reproducible and causing trouble on Firefox 86.0 (64-bit) with Firefox Mobile 86.1.1

**Comment by AmirGamilDev** [comment] 2021-06-11 16:28
By the way, thought it worth mentioning here for anyone that might find it helpful that sync occurs if you tap the share icon.  Saves on the number of taps required to get the tab you sent to your device.  See [this comment](https://github.com/mozilla-mobile/fenix/issues/19906#issue-915653231) for a gif.

**Comment by thebiffman** [comment] 2021-11-02 19:41
This is still an issue in 93.2.0. Is this issue still depending on any other issues?

By the way, another pretty quick way to trigger the sync to recieve sent tabs is to open the "Synced tabs" list.

**Comment by mhammond** [comment] 2021-11-04 00:56
> This is still an issue in 93.2.0. Is this issue still depending on any other issues?

It should be fixed in 95, which should be on the release channel mid December. See also #8582.

**Comment by AmirGamilDev** [comment] 2022-01-02 02:52
Just performed an update of the Android app and tried again but no joy I'm afraid.

Android version info:

95.2.0 (Build #2015851755)
AC: 95.0.14, 4f3b0461e7
GV: 95.0.1-20211215221728
AS: 86.0.1

2021-12-16T05:04:36.238925

**Comment by mhammond** [comment] 2022-01-02 03:10
Can you please try again? What sometimes happens is that only when hitting "Sync Now" will the target device discover it needs to register, so it may be that it self-repaired after that.

**Comment by AmirGamilDev** [comment] 2022-01-02 04:05
Hi Mark.

Did you notice my update?  It's working now.

Thanks for the hard work by the way! 👍

**Comment by Juraj-Masiar** [comment] 2022-07-01 19:01
I'm running Nightly 104 on my two phones and two tablets and this is and always has been broken.
This is what I see when I start Firefox right this moment:
![Screenshot_20220701-205209-819](https://user-images.githubusercontent.com/6358971/176954458-a947419b-681d-4c89-a939-ceb921f7f11b.png)

9 out of 10 times I see "Sign it to sync", or more like 99/100. And even if I use the Firefox for 30 minutes, I'm still not signed it. And then the moment I manually click sync, I receive my tabs I've send to my phone or tablet.

**Comment by Juraj-Masiar** [comment] 2022-09-02 09:08
**Is it just me or the "Sign to sync" button now disappeared from the main menu?**
Now I need to go to Settings / Account / click "Sync now".
WHY are you making my life harder :(

**Comment by jonalmeida** [comment] 2022-09-02 21:42
Hey folks, please file a new issue if you are seeing similar issues turn up. 

With the fixes that Mark has added here and the feedback from them, I think we can close this particular issue.

**Closed by jonalmeida** 2022-09-02 21:42 UTC
Labels: 🐞 bug, Feature:Sync, S2, pin
