### ISSUE TITLE
The Android version of Firefox frequently crashes, affecting normal use

### ISSUE THREAD

**Issue by pruidong** [mozilla-mobile/fenix#17141] opened 2020-12-19 05:16 UTC
Version information: 

84.1.0 (Build #2015781337)
AC: 67.0.10, 899738987
GV: 84.0-20201207203640
AS: 67.0.0

Phone model: Huawei nova 3
Phone memory: 8GB
Phone space: 128GB

Crash log:

68f99e1e-9ff3-4861-805c-55278fb940e1
java.lang.StackOverflowError: stack size 8MB
----
java.lang.StackOverflowError: stack size 8MB
	at android.os.Parcel.freeBuffer(Parcel.java:2996)
	at android.os.Parcel.recycle(Parcel.java:409)
	at huawei.android.view.inputmethod.HwSecImmHelper.isUseSecureIMEInner(HwSecImmHelper.java:118)
	at huawei.android.view.inputmethod.HwSecImmHelper.isUseSecureIME(HwSecImmHelper.java:94)
	at huawei.android.view.inputmethod.HwSecImmHelper.hideSoftInputFromWindow(HwSecImmHelper.java:64)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1216)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1178)
	at org.mozilla.geckoview.SessionTextInput$DefaultDelegate.hideSoftInput(SessionTextInput.java:4)
	at org.mozilla.geckoview.GeckoEditable$7.run(GeckoEditable.java:9)
	at org.mozilla.gecko.util.ThreadUtils.runOnUiThread(ThreadUtils.java:2)
	at org.mozilla.geckoview.GeckoEditable.toggleSoftInput(GeckoEditable.java:2)
	at org.mozilla.geckoview.GeckoEditable.onCreateInputConnection(GeckoEditable.java:13)
	at org.mozilla.geckoview.SessionTextInput.onCreateInputConnection(SessionTextInput.java:1)
	at org.mozilla.geckoview.GeckoView.onCreateInputConnection(GeckoView.java:2)
	at huawei.android.view.inputmethod.HwSecImmHelper.isPasswordInputType(HwSecImmHelper.java:142)
	at huawei.android.view.inputmethod.HwSecImmHelper.hideSoftInputFromWindow(HwSecImmHelper.java:65)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1216)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1178)
	at org.mozilla.geckoview.SessionTextInput$DefaultDelegate.hideSoftInput(SessionTextInput.java:4)
	at org.mozilla.geckoview.GeckoEditable$7.run(GeckoEditable.java:9)
	at org.mozilla.gecko.util.ThreadUtils.runOnUiThread(ThreadUtils.java:2)
	at org.mozilla.geckoview.GeckoEditable.toggleSoftInput(GeckoEditable.java:2)
	at org.mozilla.geckoview.GeckoEditable.onCreateInputConnection(GeckoEditable.java:13)
	at org.mozilla.geckoview.SessionTextInput.onCreateInputConnection(SessionTextInput.java:1)
	at org.mozilla.geckoview.GeckoView.onCreateInputConnection(GeckoView.java:2)
	at huawei.android.view.inputmethod.HwSecImmHelper.isPasswordInputType(HwSecImmHelper.java:142)
	at huawei.android.view.inputmethod.HwSecImmHelper.hideSoftInputFromWindow(HwSecImmHelper.java:65)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1216)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1178)
	at org.mozilla.geckoview.SessionTextInput$DefaultDelegate.hideSoftInput(SessionTextInput.java:4)
	at org.mozilla.geckoview.GeckoEditable$7.run(GeckoEditable.java:9)
	at org.mozilla.gecko.util.ThreadUtils.runOnUiThread(ThreadUtils.java:2)
	at org.mozilla.geckoview.GeckoEditable.toggleSoftInput(GeckoEditable.java:2)
	at org.mozilla.geckoview.GeckoEditable.onCreateInputConnection(GeckoEditable.java:13)
	at org.mozilla.geckoview.SessionTextInput.onCreateInputConnection(SessionTextInput.java:1)
	at org.mozilla.geckoview.GeckoView.onCreateInputConnection(GeckoView.java:2)
	at huawei.android.view.inputmethod.HwSecImmHelper.isPasswordInputType(HwSecImmHelper.java:142)
	at huawei.android.view.inputmethod.HwSecImmHelper.hideSoftInputFromWindow(HwSecImmHelper.java:65)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1216)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1178)
	at org.mozilla.geckoview.SessionTextInput$DefaultDelegate.hideSoftInput(SessionTextInput.java:4)
	at org.mozilla.geckoview.GeckoEditable$7.run(GeckoEditable.java:9)
	at org.mozilla.gecko.util.ThreadUtils.runOnUiThread(ThreadUtils.java:2)
	at org.mozilla.geckoview.GeckoEditable.toggleSoftInput(GeckoEditable.java:2)
	at org.mozilla.geckoview.GeckoEditable.onCreateInputConnection(GeckoEditable.java:13)
	at org.mozilla.geckoview.SessionTextInput.onCreateInputConnection(SessionTextInput.java:1)
	at org.mozilla.geckoview.GeckoView.onCreateInputConnection(GeckoView.java:2)
	at huawei.android.view.inputmethod.HwSecImmHelper.isPasswordInputType(HwSecImmHelper.java:142)
	at huawei.android.view.inputmethod.HwSecImmHelper.hideSoftInputFromWindow(HwSecImmHelper.java:65)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1216)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1178)
	at org.mozilla.geckoview.SessionTextInput$DefaultDelegate.hideSoftInput(SessionTextInput.java:4)
	at org.mozilla.geckoview.GeckoEditable$7.run(GeckoEditable.java:9)
	at org.mozilla.gecko.util.ThreadUtils.runOnUiThread(ThreadUtils.java:2)
	at org.mozilla.geckoview.GeckoEditable.toggleSoftInput(GeckoEditable.java:2)
	at org.mozilla.geckoview.GeckoEditable.onCreateInputConnection(GeckoEditable.java:13)
	at org.mozilla.geckoview.SessionTextInput.onCreateInputConnection(SessionTextInput.java:1)
	at org.mozilla.geckoview.GeckoView.onCreateInputConnection(GeckoView.java:2)
	at huawei.android.view.inputmethod.HwSecImmHelper.isPasswordInputType(HwSecImmHelper.java:142)
	at huawei.android.view.inputmethod.HwSecImmHelper.hideSoftInputFromWindow(HwSecImmHelper.java:65)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1216)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1178)
	at org.mozilla.geckoview.SessionTextInput$DefaultDelegate.hideSoftInput(SessionTextInput.java:4)
	at org.mozilla.geckoview.GeckoEditable$7.run(GeckoEditable.java:9)
	at org.mozilla.gecko.util.ThreadUtils.runOnUiThread(ThreadUtils.java:2)
	at org.mozilla.geckoview.GeckoEditable.toggleSoftInput(GeckoEditable.java:2)
	at org.mozilla.geckoview.GeckoEditable.onCreateInputConnection(GeckoEditable.java:13)
	at org.mozilla.geckoview.SessionTextInput.onCreateInputConnection(SessionTextInput.java:1)
	at org.mozilla.geckoview.GeckoView.onCreateInputConnection(GeckoView.java:2)
	at huawei.android.view.inputmethod.HwSecImmHelper.isPasswordInputType(HwSecImmHelper.java:142)
	at huawei.android.view.inputmethod.HwSecImmHelper.hideSoftInputFromWindow(HwSecImmHelper.java:65)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1216)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1178)
	at org.mozilla.geckoview.SessionTextInput$DefaultDelegate.hideSoftInput(SessionTextInput.java:4)
	at org.mozilla.geckoview.GeckoEditable$7.run(GeckoEditable.java:9)
	at org.mozilla.gecko.util.ThreadUtils.runOnUiThread(ThreadUtils.java:2)
	at org.mozilla.geckoview.GeckoEditable.toggleSoftInput(GeckoEditable.java:2)
	at org.mozilla.geckoview.GeckoEditable.onCreateInputConnection(GeckoEditable.java:13)
	at org.mozilla.geckoview.SessionTextInput.onCreateInputConnection(SessionTextInput.java:1)
	at org.mozilla.geckoview.GeckoView.onCreateInputConnection(GeckoView.java:2)
	at huawei.android.view.inputmethod.HwSecImmHelper.isPasswordInputType(HwSecImmHelper.java:142)
	at huawei.android.view.inputmethod.HwSecImmHelper.hideSoftInputFromWindow(HwSecImmHelper.java:65)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1216)
	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1178)
	at org.mozilla.geckoview.SessionTextInput$DefaultDelegate.hideSoftInput(SessionTextInput.java:4)
	at org.mozilla.geckoview.GeckoEditable$7.run(GeckoEditable.java:9)
	at org.mozilla.gecko.util.ThreadUtils.runOnUiThread(ThreadUtils.java:2)
	at org.mozilla.geckoview.GeckoEditable.toggleSoftInput(GeckoEditable.java:2)
	at org.mozilla.geckoview.GeckoEditable.onCreateInputConnection(GeckoEditable.java:13)
	at org.mozilla.geckoview.SessionTextInput.onCreateInputConnection

**Comment by pruidong** [comment] 2020-12-19 05:17
In addition, when loading the web page, it seems that the web page has finished loading, but the progress bar shows that it is still loading.

**Comment by pruidong** [comment] 2020-12-19 05:18
It is strange that visiting https://firefox.com.cn/ is normal, but visiting other websites will cause the browser to crash.

**Comment by kbrosnan** [comment] 2020-12-21 09:24
This should be fixed in 85 beta. We will evaluate this for uplifting to 84. Duplicate of bz-1673681

**Closed by kbrosnan** 2020-12-21 09:24 UTC
Labels: b:crash, needs:triage
