### ISSUE TITLE
[Bug] Soundcloud: Audio plays without media notification showing

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#4793] opened 2019-08-17 18:26 UTC
## Steps to reproduce

* Play a song (e.g. on soundcloud.com) on Fenix
* Put Fenix in the background
* Open a CustomTab from Twitter app (or another app)
* Open app list and swipe Fenix away

### Expected behavior

* Music should stop, or a notification that music is playing from Fenix should display

### Actual behavior

* Music keeps playing, no way for the user to stop it (beside using Force Stop, which is a pretty obscure UX)

### Device information

* Android device: Samsung S10, Android 9
* Fenix version: Latest Nightly from today

**Comment by agi90** [comment] 2019-08-19 16:26
Looks like this is specific to soundcloud.com and it's due to https://bugzilla.mozilla.org/show_bug.cgi?id=1554297

**Comment by boek** [comment] 2019-12-28 04:37
Is this still an issue @agi90?

**Comment by kbrosnan** [comment] 2019-12-31 03:45
According to #1461 this is still an issue.

**Comment by liuche** [comment] 2020-03-27 00:44
If we want to make this a priority, we'll need to comment in the bugzilla issue https://bugzilla.mozilla.org/show_bug.cgi?id=1554297

**Comment by fluffyemily** [comment] 2020-05-19 14:12
This will be fixed by the implementation of a new Media standard, the Media Session API. There are a number of parts to this, including implementing it in Gecko and then exposing it through GeckoView. The design phase of this is under way, with implementation expected to occur in GeckoView 79. Please ping me if you want to gain access to the design doc for the spec.

**Comment by agi90** [comment] 2020-05-19 17:29
The design doc is public https://docs.google.com/document/d/1cv7dhLvf7HYr34qNP7SYBNCARBZ2HFbegRsK4PGZHZQ/edit

**Comment by softvision-miralobontiu** [comment] 2020-05-20 08:39
I've encountered the same issue using rockfm.ro on the latest beta 5.1.0-beta.1 build with Samsung Galaxy Tab S6 (Android 9).

**Comment by fluffyemily** [comment] 2020-06-02 13:14
This is being tracked under https://bugzilla.mozilla.org/show_bug.cgi?id=1623715. The implementation of Media Session inside Gecko is a pretty big task and is likely to take longer than a single release cycle. Earliest possible GV for this landing is probably GV 80.

**Comment by liuche** [comment] 2020-10-08 02:09
Let's QA this on Nightly with the next AC version, on Friday Oct 9.

Related issues would be: #7369 #10740

**Comment by softvision-miralobontiu** [comment] 2020-10-09 06:25
This is not fixed yet on the 10/9 Nightly build (AC: 63.0.20201008190100, 6249bacf5, GV: 83.0a1-20201008094950) on HTC 10 (Android 8).
Following the STR from the first comment, only force closing Fenix stopped the media from playing.

I'll remove the qa:needed label.

**Comment by AndiAJ** [comment] 2020-12-10 07:41
Hi, **verified as fixed** on the latest **`Nightly 201210`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by AndiAJ** [comment] 2020-12-17 10:57
Still reproducible on Beta 85.0.0-beta.1 using a OnePlus A3 (Android 6.0.1)

**Comment by ebalazs-sv** [comment] 2021-01-08 12:37
This issue is still reproducible on Beta 85.0.0-beta.6 with Nexus 5 (Android 6.0.1).

**Comment by alastor0325** [comment] 2021-01-11 22:20
FYI, on Nightly86.0a1, I am not able to reproduce this issue any more, Firefox shows the media notification controller while playing music on Soundclound.

**Comment by softvision-miralobontiu** [comment] 2021-01-12 12:42
Still reproducible on Beta 85.0.0-beta.7 with Sony Xperia Z5 Premium (Android 7.1.1).
I'll reopen this issue.

**Comment by pocmo** [comment] 2021-01-13 16:07
@softvision-miralobontiu / @ebalazs-sv This is not enabled in Beta yet. It was kept behind a feature flag. It's in Nightly currently and should go into the next Beta.

**Closed by pocmo** 2021-01-13 16:07 UTC
Labels: Feature:Media, P2, eng:qa:verified, needs:gv, 🐞 bug, 🙅 waiting

**Comment by AndiAJ** [comment] 2021-01-21 07:57
Still reproducible on 85.1.0-rc.1 using a OnePlus A3 (Android 6.0.1)

**Comment by AndiAJ** [comment] 2021-02-09 14:07
Still reproducible on 85.1.3 using a OnePlus A3 (Android 6.0.1)
