### ISSUE TITLE
[Feature request] Move the "Undo close tab" button so that you can quickly close tabs while in list mode

### ISSUE THREAD

**Issue by nandryshak** [mozilla-mobile/fenix#19407] opened 2021-05-06 17:45 UTC
When the tab display is in "list" mode, clicking the "X" to close the bottom-most tab shows a purple toast that says "Tab Closed - Undo". You have to wait for this to go away before you can close the new bottom-most tab, because the "X" for the next tab is hidden behind the toast. It should be moved out of the way so that you can quickly close more than one tab.

**Comment by takkaria** [comment] 2021-05-08 12:11
This is a duplicate of  #19166

**Comment by jsphslgr** [comment] 2021-05-22 01:35
It should be noted that not only is the tab "X" blocked - over 50% of the tab pane is covered by the "undo" box, so swiping away the bottom tab is also quite difficult.

**Comment by reidellawfirm** [comment] 2021-06-22 07:07
This bug/feature is extremely annoying and unnecessary since there is now an option to view closed tabs in history. Please remove this popup or allow it to be disabled.

**Comment by kbrosnan** [comment] 2021-07-12 17:03
Closing duplicate

**Closed by kbrosnan** 2021-07-12 17:03 UTC
Labels: feature request 🌟
