### ISSUE TITLE
[Bug] Black screen after opening new tab from tab tray in an open tab

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14659] opened 2020-09-03 05:13 UTC
## Steps to reproduce

1. Open Fenix
2. Open any top sites link
3. tap tab  switcher
4. tap new tab FAB

### Expected behavior

Smooth animation to new tab.

### Actual behavior

Black flash before home appears.

![recording-20200903-010701](https://user-images.githubusercontent.com/152493/92073864-b798d780-ed82-11ea-8cbb-eb42459334b2.gif)

### Device information

* Android device: Moto G xt1031
* Fenix version: latest nightly, reproducible in 80 release as well.

**Comment by yoasif** [comment] 2020-09-03 05:14
@mcomella not sure this is the same as https://github.com/mozilla-mobile/fenix/issues/11910 but I figured I'd let you know about it.

**Comment by amedyne** [comment] 2020-12-10 16:39
@yoasif I am no longer able to reproduce this in Nightly. Can you check? Thanks!

**Comment by sflorean** [comment] 2021-06-14 17:43
I was not able to reproduce this on latest Nightly with Pixel 3 and LG G7. I will close this, but please re-open (or file a new bug) if still reproduces.

**Closed by sflorean** 2021-06-14 17:43 UTC
Labels: Feature:Search, Feature:Tabs, wontfix, 🐞 bug
