### ISSUE TITLE
[Bug]: does not open the html file from the device

### ISSUE THREAD

**Issue by OmlineEditor** [mozilla-mobile/fenix#25861] opened 2022-07-01 21:15 UTC
### Steps to reproduce

1. I insert it into the address and try to open it    `file:///storage/emulated/0/temp/index.html`
2. permission to read the storage is available.
3. your program cannot open this link. another browser for example vivaldi can open.

### Expected behaviour

show html file from device

### Actual behaviour

shows nothing on the screen, just a blank white screen

### Device name

Redmi Note 7

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

101.1.1 (1011120)  F-droid

### Device logs

`E/Layer   (775):  [Surface(name=AppWindowToken{776e021 token=Token{3f55e88 ActivityRecord{a54ca2b u0 org.mozilla.fennec_fdroid/org.mozilla.fenix.HomeActivity t141}}})/@0xc1fb2f6 - animation-leash#0] No local sync point found
`

### Additional information

please make it possible to open a direct html file

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20888)

**Comment by marcel263** [comment] 2022-07-02 08:32
please check similar bugs before taking effort to rewrite such a report. This is duplicate of #7546

**Comment by OmlineEditor** [comment] 2022-07-03 17:46
> please check similar bugs before taking effort to rewrite such a report. This is duplicate of #7546

I searched but because my language is not English I could not find it

**Comment by marcel263** [comment] 2022-07-03 20:01
> > please check similar bugs before taking effort to rewrite such a report. This is duplicate of #7546
> 
> I searched but because my language is not English I could not find it

In the mentioned issue, there seems to be a suggested solution by using the "Fennec" community-maintained release on F-Droid market.

Your title turned up the correct result #7546  fine at least on this location. Perhaps you can follow the progress over there?

**Comment by SoftVision-LorandJanos** [comment] 2022-07-04 05:14
Hi @OmlineEditor! Thanks for your report!
As mentioned above, your issue will be covered.
You can follow the progress of the issue in that ticket. Thank you!
I will close this one as a duplicate.

**Closed** 2022-07-04 05:20 UTC
Labels: 🐞 bug, needs:triage, qa-triaged
