### ISSUE TITLE
[Bug] "Open link in external app" option on videos doesn't offer to open in browser

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#16732] opened 2020-11-24 20:35 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Long press a video (for example on gfycat)
- Click "open link in external app"
### Expected behavior
Firefox is is among the apps offered to open the link

### Actual behavior
There is no option to open the video in the browser. Previously this was possible, then it wasn't for a while, then it was added back, and now it's gone again. I'm not sure if this is intentional or a bug, but I often used this option if a video's controls were not working, or to copy a direct link to a video

### Device information

* Android device: Huawei Nova 6 (Android 10)
* Fenix version: Nightly 201123 17:01 (Build #2015777355)

**Comment by sflorean** [comment] 2021-07-31 09:52
Closing as duplicate of #16817.

**Closed by sflorean** 2021-07-31 09:52 UTC
Labels: Feature:Media, wontfix, 🐞 bug
