### ISSUE TITLE
[Bug] Crash when loading several sites

### ISSUE THREAD

**Issue by Furax-31** [mozilla-mobile/fenix#7371] opened 2019-12-27 09:34 UTC
## Steps to reproduce
Open : http://m.jeuxvideo.com/forums.htm - https://github.com/dashboard

### Expected behavior
Sites should open normally

### Actual behavior
Application crashes when sites open

### Device information
A5 2017 - Pie - November 2019 Security patch

* Android device: A5 2017
* Fenix version: The application has been crashing for 2-3 days (Since December 25, 2019) Last build: Nightly 191226 18:01

**Comment by boek** [comment] 2019-12-27 18:48
```
  java.lang.IllegalArgumentException: Invalid color format
        at org.mozilla.geckoview.GeckoSession.rgbaToArgb(GeckoSession.java:6042)
        at org.mozilla.geckoview.GeckoSession.fixupManifestColor(GeckoSession.java:6049)
        at org.mozilla.geckoview.GeckoSession.fixupWebAppManifest(GeckoSession.java:6056)
        at org.mozilla.geckoview.GeckoSession.access$000(GeckoSession.java:71)
        at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:478)
        at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:431)
        at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:90)
        at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:356)
        at android.os.Handler.handleCallback(Handler.java:883)
```

**Comment by Furax-31** [comment] 2019-12-27 20:52
Last build: Nightly 19227 18:01

Crash again :(

**Comment by eyalyoli** [comment] 2019-12-28 16:51
Crashes on build 191228

**Comment by lnicola** [comment] 2019-12-29 09:57
Possibly duplicate of https://github.com/mozilla-mobile/fenix/issues/7362.

**Comment by LittleAngelwings** [comment] 2019-12-29 14:01
I don't have any more crashes since this nightly:

Nightly 191228 18:01 (Build #13621813)
27.0.0, d10c36024
GV: 73.0a1-20191227094418

**Comment by sv-sdeiac** [comment] 2019-12-30 14:42
Closing as a duplicate of #7362 and also verified that the issue is not reproducible using different sites who were affected by the crash:
- http://m.jeuxvideo.com/forums.htm;
- https://github.com/dashboard;
- https://www.google.com/travel;
- https://www.irishtimes.com/opinion/what-ever-happened-to-the-irish-salmon-farming-industry-1.4123596?mode=amp.

Devices: 
- LG G7 fit (Android 8.1);
- Samsung Galaxy S8 (Android 9);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel (Android Q).

**Closed by sv-sdeiac** 2019-12-30 14:42 UTC
Labels: P1, S1, b:crash, needs:gv, 🐞 bug
