### ISSUE TITLE
Improve consistency of tabs openings

### ISSUE THREAD

**Issue by Perdu** [mozilla-mobile/fenix#20036] opened 2021-06-15 15:48 UTC
### What is the user problem or growth opportunity you want to see solved?

Improve consistency of tabs openings by always opening tabs at the top or bottom of the list.
Currently, there is some form of inconsistency regarding how tabs are added to the opened tabs list (whether in list or grid mode):
- new tabs are added at the *bottom* of the list
- tabs opened from collections are added at the *top* of the list
- cancelling the closing of a tab puts it back at the *top* of the list, whatever its original position was

### How do you know that this problem exists today? Why is this important?

It makes it a bit tedious to navigate throughout multiple tabs since there is currently no way to reorder them.

### Who will benefit from it?

People who like having ordered tabs :)
Especially people permanently having a lot of opened tabs.

**Comment by jonalmeida** [comment] 2021-06-15 18:39
> cancelling the closing of a tab puts it back at the _top_ of the list, whatever its original position was

This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/10986.

**Comment by amedyne** [comment] 2021-06-21 18:50
Closing this one and will track #10986 instead.

**Closed by amedyne** 2021-06-21 18:50 UTC
Labels: Feature:Tabs
