### ISSUE TITLE
[Bug] [L10N] [V88.1] Some strings in the onboarding page of Fenix V88.1 are not localized

### ISSUE THREAD

**Issue by bli-mozbj** [mozilla-mobile/fenix#19089] opened 2021-04-17 05:34 UTC
## Steps to reproduce
1. Change OS language to zh-CN (aka simplified Chinese) or zh-TW (aka traditional Chinese)
2. Install Fenix V88.1 (release version)
3. Launch Fenix

### Expected behavior
The onboarding page is fully translated.

### Actual behavior
Most strings are not localized.
![FF39262C-1469-4A39-B8F8-048BCFDFA420](https://user-images.githubusercontent.com/25242209/115103005-25e08200-9f81-11eb-92e7-76ec4d18b2b3.jpeg)

### More information
Not only the zh-CN and zh-TW version have this issue, but also some other languages.

**Comment by ebalazs-sv** [comment] 2021-04-19 11:13
I can reproduce this issue on RC 88.1.1 from 4/16 and Beta 88.0.0-beta.6 from 4/11 with Pixel 2 (Android 9).
This issue is not reproducible on Nightly 4/19.

**Comment by selimsumlu** [comment] 2021-04-24 12:45
Same for Turkish on 88.1.1 release.

**Comment by Amejia481** [comment] 2021-05-04 12:03
cc @Delphine

**Comment by Delphine** [comment] 2021-05-05 01:16
Is this maybe because something went wrong with string import?
This is all localized in Pontoon.

**Comment by bli-mozbj** [comment] 2021-05-06 08:56
> 
> 
> Is this maybe because something went wrong with string import?
> This is all localized in Pontoon.

It looks like the string id was updated in 869c99a, and two days after the branching of releases_v88.0.0, while the updated localizations intended for master was synced back to the 88 release branch in 6d76742.

also you can find some examples in  #19092

Maybe something like crosschannel l10n from desktop should be adopted here to avoid similar issues.  @Delphine @st3fan

**Comment by kaream671** [comment] 2021-05-06 09:40
19092

**Comment by SoftVision-LorandJanos** [comment] 2021-11-05 13:10
This issue is no longer reproducible on the latest Release build (94.1.1). I will close this ticket as fixed.

**Closed by SoftVision-LorandJanos** 2021-11-05 13:10 UTC
Labels: 🐞 bug, Feature:Onboarding, 🌐 L10N, S3, needs:triage, wontfix, qa-triaged
