### ISSUE TITLE
FNX-4565 ⁃ [Bug] App Freezes with Could not fetch region from location service in MozillaLocationService

### ISSUE THREAD

**Issue by g1nk1-m** [mozilla-mobile/fenix#10793] opened 2020-05-20 04:32 UTC
## Steps to reproduce
* Tapping on anything other than the three dot / settings icon on the homepage
* Inside the settings page, tapping on Search option

### Expected behavior
To not crash / freeze

### Actual behavior
The App freezes and and crashes after few seconds. Can't access anything other than the settings page

### Device information
* Android device: Oneplus 5T
* Android version: OOS 10 / Android 10
* Fenix version: 5.0.0 ( Build #21212137)
Tried the same on the Nightly version and had the same issue. 
[Github Gist of the Log](https://gist.github.com/g1nk1-m/85847a9df2643d6b887f97bf0d76cbd8)

**Comment by kbrosnan** [comment] 2020-05-21 15:52
Might be #5663 / https://bugzilla.mozilla.org/show_bug.cgi?id=1604056

**Comment by ekager** [comment] 2020-06-02 04:12
If you can still reproduce this in Nightly, could you possibly grab a screen recording of this happening?

**Comment by g1nk1-m** [comment] 2020-06-02 14:14
> If you can still reproduce this in Nightly, could you possibly grab a screen recording of this happening?

[Video of the issue](https://streamable.com/5yoeyc). I also found a weird temporary fix for the issue.If I switch my mobile data to SIM 2 and use it to access the app, it works normally. After using SIM 2 for accessing any page once, I can switch back the data to SIM 1 and everything works as intended. [Video of the temp fix](https://streamable.com/xja05z)

**Comment by ekager** [comment] 2020-06-02 14:17
Thanks for those videos!

**Comment by ekager** [comment] 2020-06-02 17:03
Looks like the relevant piece of the log is
```
05-20 09:40:19.184 18986 19964 D App     : Could not fetch region from location service
05-20 09:40:19.184 18986 19964 D App     : java.net.SocketTimeoutException
05-20 09:40:19.184 18986 19964 D App     : 	at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:42)
05-20 09:40:19.184 18986 19964 D App     : 	at mozilla.components.service.location.MozillaLocationService$fetchRegion$2.invokeSuspend(MozillaLocationService.kt:27)
05-20 09:40:19.184 18986 19964 D App     : 	at mozilla.components.service.location.MozillaLocationService$fetchRegion$2.invoke(Unknown Source:10)
05-20 09:40:19.184 18986 19964 D App     : 	at kotlin.jvm.internal.Intrinsics.startUndispatchedOrReturn(Intrinsics.java:2)
05-20 09:40:19.184 18986 19964 D App     : 	at kotlin.jvm.internal.Intrinsics.withContext(Intrinsics.java:9)
05-20 09:40:19.184 18986 19964 D App     : 	at mozilla.components.service.location.MozillaLocationService.fetchRegion(MozillaLocationService.kt:2)
05-20 09:40:19.184 18986 19964 D App     : 	at mozilla.components.service.location.search.RegionSearchLocalizationProvider.determineRegion(RegionSearchLocalizationProvider.kt:5)
05-20 09:40:19.184 18986 19964 D App     : 	at mozilla.components.browser.search.provider.AssetsSearchEngineProvider.loadSearchEngines(AssetsSearchEngineProvider.kt:5)
05-20 09:40:19.184 18986 19964 D App     : 	at org.mozilla.fenix.components.searchengine.FenixSearchEngineProvider$bundledSearchEngines$1.invokeSuspend(FenixSearchEngineProvider.kt:21)
05-20 09:40:19.184 18986 19964 D App     : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
05-20 09:40:19.184 18986 19964 D App     : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
05-20 09:40:19.184 18986 19964 D App     : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
05-20 09:40:19.184 18986 19964 D App     : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
```

**Comment by ekager** [comment] 2020-06-02 17:49
Closing for https://github.com/mozilla-mobile/fenix/issues/9935

**Closed** 2020-08-11 01:52 UTC
Labels: Feature:Search, b:crash, needs:ac, 🐞 bug
