### ISSUE TITLE
[Bug]Cannot open html file downloads

### ISSUE THREAD

**Issue by Oymate** [mozilla-mobile/fenix#18388] opened 2021-03-09 09:25 UTC
## Steps to reproduce
- Have a downloaded HTML file
- Click to open it
- FF doesn't open it

### Expected behavior
FF should open it

### Actual behavior
It does not

### Device information
N/A(tested on multiple)

* Device vendor / model and Android version: Android 10
* Firefox for Android version: 86.1.1 (Build #2015794883)
 
Notes:
File permission was given

**Comment by cadeyrn** [comment] 2021-03-09 09:50
Duplicate of #7546.

**Comment by mcarare** [comment] 2021-03-09 11:10
@Oymate Thank you for your report. This is already requested [here](https://github.com/mozilla-mobile/fenix/issues/7546). Closing this as duplicate.

**Closed by mcarare** 2021-03-09 11:10 UTC
Labels: needs:triage
