### ISSUE TITLE
Browser crash upon opening any Twitter video

### ISSUE THREAD

**Issue by oatastemur** [mozilla-mobile/fenix#17612] opened 2021-01-24 16:55 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

I have been having crashing issues with Firefox for a while now on my Samsung Galaxy S10e. Certain pages predictably crash the browser, and in particular it is impossible to play any video on Twitter. I initially thought this may be related to my running the Android 11 beta, but now that the final version has been released it's time to submit a bug report.

This issue exists on Firefox and also on Firefox Focus and Firefox Nightly. Browsers not based on Fenix have no such issues on my phone.

I cannot reproduce this on a Pixel (1st generation) with Android 10, and due to the lack of related bug reports that I can find, I assume it a rather specific bug, perhaps related to the Samsung drivers/Exynos 9820 SoC. However I have tried disabling hardware video decoding on the Nightly build without any success.

## Steps to reproduce
Go to https://twitter.com/twittervideo and scroll down to a video. If it does not automatically play, press start.

### Expected behavior
Video starts playing.

### Actual behavior
Browser crashes immediately before the video starts playing.

### Device information

* Android device: Samsung Galaxy S10e (SM-G970F/DS)
* Software versions: Android 11 / OneUI 3.0 / Build G970FXXU9ZTLJ
* Fenix version: 84.1.4 (Build #2015785883)

**Comment by oatastemur** [comment] 2021-01-24 17:26
After some more digging it seems that enabling the gfx.webrender.force-disabled flag in the Nightly makes this issue go away, meaning it is related to this bug: https://github.com/mozilla-mobile/fenix/issues/10655

However the issue here is that it seems to be enabled by default, while there is an outstanding bug!

**Comment by jamienicol** [comment] 2021-01-24 18:02
Hi @oatastemur, thank you for the bug report! And for the easy steps to reproduce.

If you navigate to about:crashes, are you able to send a link to a crash report?

This bug is not related to #10655, as that one is due to a driver bug on a Mali-T device. (Where webrender is only enabled on nightly.) On your Mali-G device webrender is indeed enabled on release as we did not encounter bugs during its time in nightly or beta. Sorry it has made it this far, hopefully we can fix it asap!

In the future please don't hesitate to file bugs even when running beta versions - the sooner we know the sooner we can fix them :)

**Comment by oatastemur** [comment] 2021-01-24 18:15
Hi @jamienicol, this is what I see in about:crashes.

```
02cbe0b6-1a7b-4535-9132-c59388053393
<native crash>
```

Does this id correspond to a crash report?

**Comment by jamienicol** [comment] 2021-01-24 18:55
@oatastemur Yes, that should be a crash report. Is there a link next to that called "Socorro"? If so, could you copy and paste the link?

**Comment by oatastemur** [comment] 2021-01-24 19:04
> @oatastemur Yes, that should be a crash report. Is there a link next to that called "Socorro"? If so, could you copy and paste the link?

I don't see any link. Here's a screenshot: https://user-images.githubusercontent.com/8052652/105640602-d6ede980-5e76-11eb-94e8-da3a7247bbe5.jpg

**Comment by jamienicol** [comment] 2021-01-24 19:09
What happens if you click the share button?

**Comment by oatastemur** [comment] 2021-01-24 19:14
> What happens if you click the share button?

It just shares the following text:

> 02cbe0b6-1a7b-4535-9132-c59388053393
> <native crash>
> ----
> <native crash>

**Comment by dersnek** [comment] 2021-01-25 08:32
I have the similar issue in Firefox Beta. Can't play any video on Twitter or [Pixabay](https://pixabay.com), instant browser crash every time. Videos on YouTube play fine.

100% reproducible for me on this configuration:
- Android device: Samsung Galaxy Note 10 (SM-N970F/DS)
- Software versions: Android 11 / OneUI 3.0 / Build N970FXXU6ETLL
- Fenix version: 85.0.0-beta.9 (Build #2015787947)

**Comment by jamienicol** [comment] 2021-01-25 09:30
@oatastemur hmm, it seems like for some reason the crash report wasn't submitted. I tried manually searching for the ID, but couldn't find it.

@dersnek thank you for the information. If you go to about:crashes do you see any "Socorro" links? Also, in case you weren't aware you have to restart the browser after setting gfx.webrender.force-disabled to false. Swiping the app away in the app switcher then opening it again should do the trick. If that still doesn't fix it then the bug may not be webrender specific, and just generally to do with playing videos...

**Comment by jamienicol** [comment] 2021-01-25 09:57
This could potentially be this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1688017

**Comment by dersnek** [comment] 2021-01-25 09:58
@jamienicol My crash reports look exactly the same as oatastemur's, without any links.

I was aware that a restart is required after changes like this, but it still didn't work. However, upon further investigation I found that if I do both:
```
gfx.webrender.all: false
gfx.webrender.force-disabled: true
```
then I can't reproduce this bug anymore. If any of these two settings is changed, it's reproducible 100% of the time.

**Comment by oatastemur** [comment] 2021-01-25 12:33
I tried to get some more useful logging information by building from source and attaching a debugger, but it seems that the debug build crashes on startup due to an unhandled exception: `java.lang.RuntimeException: StrictMode ThreadPolicy violation` caused by `android.os.strictmode.DiskReadViolation`. Is this a known issue?

**Comment by oatastemur** [comment] 2021-01-25 12:59
I disabled StrictMode to get around that issue. This is the crash handler log:
```
2021-01-25 12:50:09.471 9899-9899/org.mozilla.fenix.debug E/mozac/CrashReporter: CrashHandlerService received native code crash
2021-01-25 12:50:09.501 9899-9955/org.mozilla.fenix.debug I/mozac/CrashReporter: Received crash: NativeCodeCrash(timestamp=1611579009501, minidumpPath=/data/user/0/org.mozilla.fenix.debug/files/mozilla/bs6zti6b.default/minidumps/60425607-f82e-6692-1fb3-d2197f02a95b.dmp, minidumpSuccess=false, extrasPath=/data/user/0/org.mozilla.fenix.debug/files/mozilla/bs6zti6b.default/minidumps/60425607-f82e-6692-1fb3-d2197f02a95b.extra, isFatal=true, breadcrumbs=[], uuid=ebe48117-c62a-4aab-b7f6-86620bbfa862)
```

This is the application debugger output just after clicking play:
```
W/google-breakpad: ExceptionHandler::GenerateDump cloned child 
    16490
    ExceptionHandler::SendContinueSignalToChild sent continue signal to child
I/Choreographer: Skipped 54 frames!  The application may be doing too much work on its main thread.
D/GeckoViewMediaControl: handleEvent: activated
    handleActivated
D/GeckoViewMediaControl: handleEvent: playbackstatechange
    handlePlaybackStateChanged playing
```

And the logcat output for the affected browser tab:
```
2021-01-25 12:58:22.527 17767-17943/org.mozilla.fenix.debug D/GeckoViewProgressDelegate[C]: handleEvent: MozAfterPaint
2021-01-25 12:58:22.609 17767-17943/org.mozilla.fenix.debug D/GeckoViewAutofill[C]: handleEvent: focusin
2021-01-25 12:58:22.629 17767-17943/org.mozilla.fenix.debug D/GeckoViewPrompt[C]: handleEvent: click
2021-01-25 12:58:22.641 17767-17943/org.mozilla.fenix.debug D/GeckoViewProgressDelegate[C]: handleEvent: MozAfterPaint
2021-01-25 12:58:22.689 17767-18437/org.mozilla.fenix.debug W/GeckoRemoteCodecProxy: release codec when 3 output buffers unhandled
2021-01-25 12:58:22.727 17767-17943/org.mozilla.fenix.debug W/Web Content: [JavaScript Warning: "Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified"]
2021-01-25 12:58:22.764 17767-17943/org.mozilla.fenix.debug W/Web Content: [JavaScript Warning: "Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified"]
2021-01-25 12:58:22.785 17767-18410/org.mozilla.fenix.debug W/GeckoRemoteCodecProxy: release codec when 3 output buffers unhandled
2021-01-25 12:58:22.950 17767-18437/org.mozilla.fenix.debug W/GeckoRemoteCodecProxy: release codec when 3 output buffers unhandled
2021-01-25 12:58:23.676 17767-17943/org.mozilla.fenix.debug W/Web Content: [JavaScript Warning: "Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified"]
2021-01-25 12:58:23.792 17767-18123/org.mozilla.fenix.debug I/Gecko: Exiting due to channel error.
```

**Comment by oatastemur** [comment] 2021-01-25 13:20
I managed to extract `60425607-f82e-6692-1fb3-d2197f02a95b.dmp` and `60425607-f82e-6692-1fb3-d2197f02a95b.extra` from the filesystem. Are these useful, and where is a safe place to post them? They do not contain my real user profile.

**Comment by jamienicol** [comment] 2021-01-25 18:54
Thanks for getting those @oatastemur. If you want you can email them to jnicol@mozilla.com and I can have a look.

In the meantime we're disabling webrender for Mali-G76 devices (on release, beta, and nightly), and I have ordered a device with that GPU so that I can investigate further.

**Comment by jcristau** [comment] 2021-01-27 15:04
FWIW I'm using a samsung galaxy s10e phone, and have been unable to reproduce the crash on twitter.com/twittervideo

Copied my about:support data here: https://cristau.org/~julien/tmp/fenix-support.json

**Comment by hertz1** [comment] 2021-01-28 15:29
> FWIW I'm using a samsung galaxy s10e phone, and have been unable to reproduce the crash on twitter.com/twittervideo
> 
> Copied my about:support data here: https://cristau.org/~julien/tmp/fenix-support.json

I have a Galaxy S10e and this issue started after upgrading to Oneui 3.0 (Android 11).

**Comment by jamienicol** [comment] 2021-01-28 15:53
@hertz1 (or @oatastemur or @dersnek, anyone who *can* reproduce the crash): could you please attach a copy of your about:support infomation? I'm assuming an updated version of the Mali driver was shipped along with the Android 11 update, and that's causing the issue.

**Comment by hertz1** [comment] 2021-01-28 16:32
@jamienicol

[about:support.txt](https://github.com/mozilla-mobile/fenix/files/5888633/about.support.txt)

**Comment by dersnek** [comment] 2021-01-28 17:55
@jamienicol
[about-support.txt](https://github.com/mozilla-mobile/fenix/files/5889124/about-support.txt)

**Comment by jamienicol** [comment] 2021-03-01 10:53
This should be fixed now. The stable release version of Firefox should have webrender disabled on devices affected by this driver bug (Mali-G72/76 on Android 11). And beta and nightly have a workaround in place. If anyone can still reproduce the crash please let me know!

**Comment by kbrosnan** [comment] 2021-04-12 16:00
Fixed by upstream.

**Closed by kbrosnan** 2021-04-12 16:00 UTC
Labels: S1, b:crash, 🐞 bug
