### ISSUE TITLE
Share dialog and other app lists within Fenix like "Open in App" and context menus are missing almost all apps

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/fenix#18195] opened 2021-02-26 16:44 UTC
Not sure exactly what's going on here. It was working correctly last night, but is having an issue this morning, so maybe a recent Nightly update messed it up?

The issue:
I have Twitter installed as a PWA via Firefox Nightly on my Pixel 3 phone. I see a tweet in that PWA that I want to share into a Discord server with the Discord Android app. I tap the tweet's "share" button, then choose "share tweet via..." from the menu that opens. This pops up Fenix/Android's Share dialog, giving me options to send to various Firefox Sync enabled devices/applications and other Android apps that can receive the shared item.

When things are working correctly, Discord is one of the apps in the Share dialog, and I am able to share the tweet into Discord.

At the moment, none of the other Android apps are being shown in the Share dialog: 
<img src=https://user-images.githubusercontent.com/172215/109328702-9a633400-780e-11eb-9438-73aad89ab2bf.png width = 40%>

I only see "bluetooth" under "recently used", and "nearby share" under "all actions".

**Comment by KWierso** [comment] 2021-02-26 16:47
The "share" dialog in non-Nightly Fenix works correctly. It does not work for me on any site in Nightly, so steps to reproduce in Nightly are just "visit any site && select the share icon from Fenix's main menu". No PWA or Twitter needed...

**Comment by LittleAngelwings** [comment] 2021-02-26 22:41
I can't confirm this issue with firefox nightly. 
![Screenshot 2021-02-26 23 40 10](https://user-images.githubusercontent.com/44252450/109362842-26677100-788c-11eb-9204-0794c687c6bd.png)

**Comment by hakkikaancaliskan** [comment] 2021-02-26 23:17
I can confirm all apps gone with 2/26 nightly.
![Screenshot_20210227-021710_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/109365334-fcb94480-78a1-11eb-8852-0e5a9b82f186.png)

**Comment by KWierso** [comment] 2021-02-27 04:21
[Random stab in the dark]: I see [this commit](https://github.com/mozilla-mobile/fenix/commit/0e8dc6164d8d11bc5267e31c3e4f8759054f5828#diff-a9a4df7333234d458fdd9fe94a2643cf06d8250c0f5f53d110d72c68cf5fa6b9) from two days ago over in android-components slightly changed ShareViewModel.kt, related to targeting Android 11.

I'm on Android 11, and am now having troubles with the ShareView.

More detailed version information:
Nightly 210226
AC: 74.0.20210226044101, 2f8e0147b
GV: 88.0a1-20210225215504
AS: 71.0.0

I don't have a good way to hook my phone up for debugging at the moment, but if I can get my computer set back up for that, I'll see if there are any errors popping up.

**Comment by KWierso** [comment] 2021-02-27 04:45
Unfiltered `adb logcat` starting right before I open Fenix's share dialog and getting killed a second or two after the dialog opens:

```
02-26 20:40:31.162  6699  6772 I FxaDeviceConstellation: Refreshing device list...
02-26 20:40:31.162  6699  6772 I FxaDeviceConstellation: Executing: fetching all devices
02-26 20:40:31.176  2436  2744 E SQLiteLog: (1) duplicate column name: EVENT_HOST_APP_VERSION_CODE in "alter table DYNAMIC_DETECTION_CALL_API_COUNTS_LOG add column EVENT_HOST_APP_VERSION_CODE INTEGER"
02-26 20:40:31.258  1029  1029 I android.hardware.health@2.0-service.crosshatch: Entry state_: 1 charger_status: Charging batteryLevel: 100
02-26 20:40:31.258  1029  1029 I android.hardware.health@2.0-service.crosshatch: Exit state_: 1 batteryLevel: 100
02-26 20:40:31.262  2092  9868 D PowerUI : can't show warning due to - plugged: true status unknown: false
02-26 20:40:31.305  6699  6772 I FxaDeviceConstellation: Successfully executed: fetching all devices
02-26 20:40:31.305  6699  6772 I FxaDeviceConstellation: Current device needs push endpoint registration, so checking for missed commands
02-26 20:40:31.305  6699  6772 I FxaDeviceConstellation: Executing: polling for device commands
02-26 20:40:31.336  1537  1599 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.SIG_STR flg=0x10 (has extras) } to com.cheekydevs.fiswitch/.utils.SignalReceiver
02-26 20:40:31.391  6699  6772 I FxaDeviceConstellation: Successfully executed: polling for device commands
02-26 20:40:31.391  6699  6772 I AccountEventsIntegration: Received events, notifying listeners
02-26 20:40:31.391  6699  6772 I SyncTelemetry: Reported telemetry for 0 sent commands
02-26 20:40:31.391  6699  6772 I SyncTelemetry: Reported telemetry for 0 received commands
02-26 20:40:31.392  6699  6772 I FxaDeviceConstellation: Refreshed device list; saw 8 device(s).
02-26 20:40:31.392  6699  6772 I FxaDeviceConstellation: Notifying observer about constellation updates.
02-26 20:40:31.392  6699  6772 I ConstellationObserver: onDevicesUpdate triggered.
02-26 20:40:31.392  6699  6772 I VerificationDelegate: Allowed to renew?
02-26 20:40:31.392  6699  6772 I VerificationDelegate: No need to reset inner timestamp and count.
02-26 20:40:31.392  6699  6772 I VerificationDelegate: Allowed to renew!
02-26 20:40:31.392  6699  6772 I ConstellationObserver: Proceeding to renew registration
02-26 20:40:31.392  6699  6772 I ConstellationObserver: Our push subscription either doesn't exist or is expired; renewing registration.
02-26 20:40:31.392  6699  6772 W AutoPushFeature: Forcing registration renewal by deleting our (cached) token.
02-26 20:40:31.392  6699  6772 I AbstractFirebasePushService: start
02-26 20:40:31.392  6699  6772 I ConstellationObserver: Incrementing verifier
02-26 20:40:31.392  6699  6772 I ConstellationObserver: Verifier state before: timestamp=1614322998168, count=16
02-26 20:40:31.392  6699  6772 I VerificationDelegate: Incrementing verification state.
02-26 20:40:31.392  6699  6772 I ConstellationObserver: Verifier state after: timestamp=1614322998168, count=17
02-26 20:40:31.592  1035  1109 D VSC     : @ 21321.789: [WO] isFlat() nearest_rotation: 4, flat_angle: 65
02-26 20:40:31.592  1035  1109 D VSC     : @ 21321.789: [WO] orientation angle 354, orientation 4
02-26 20:40:31.751  1029  1029 I android.hardware.health@2.0-service.crosshatch: Entry state_: 1 charger_status: Charging batteryLevel: 100
02-26 20:40:31.752  1029  1029 I android.hardware.health@2.0-service.crosshatch: Exit state_: 1 batteryLevel: 100
02-26 20:40:31.760  2092 12825 D PowerUI : can't show warning due to - plugged: true status unknown: false
02-26 20:40:31.831  1000  1004 E statsd  : Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->10277[I] (10)0x30000->fiid-sync[S]
02-26 20:40:31.832  1000  1004 E statsd  : DurationMetric 2271129699865384196 dropping data for what dimension key (10)0x2010101->10277[I] (10)0x30000->fiid-sync[S]
02-26 20:40:31.832  1000  1004 E statsd  : DurationMetric 1897601926725174045 dropping data for what dimension key (10)0x2010101->10277[I] (10)0x30000->fiid-sync[S]
02-26 20:40:31.832  1000  1004 E statsd  : DurationMetric 2258810225604521452 dropping data for what dimension key (10)0x2010101->10277[I] (10)0x30000->fiid-sync[S]
02-26 20:40:31.833  1000  1004 E statsd  : DurationMetric 2346578612287077500 dropping data for what dimension key (10)0x2010101->10277[I] (10)0x30000->fiid-sync[S]
02-26 20:40:31.833  1000  1004 E statsd  : DurationMetric 1892220958478332972 dropping data for what dimension key (10)0x2010101->10277[I] (10)0x30000->fiid-sync[S]
02-26 20:40:31.987 26840 26965 I CDP     : {"date":"2021-02-26T20:40:31.987","PID":26840,"TID":26965,"message":{"text":"Overwriting device ccsTicket for cached device (last recorded displayName: %s)"},"level":3,"flags":2}
02-26 20:40:31.988 26840 26965 I CDP     : {"date":"2021-02-26T20:40:31.987","PID":26840,"TID":26965,"message":{"text":"Overwriting device ccsTicket for cached device (last recorded displayName: %s)"},"level":3,"flags":2}
02-26 20:40:31.988 26840 26965 I CDP     : {"date":"2021-02-26T20:40:31.988","PID":26840,"TID":26965,"message":{"text":"Overwriting device ccsTicket for cached device (last recorded displayName: %s)"},"level":3,"flags":2}
02-26 20:40:31.988 26840 26965 I CDP     : {"date":"2021-02-26T20:40:31.988","PID":26840,"TID":26965,"message":{"text":"Overwriting device ccsTicket for cached device (last recorded displayName: %s)"},"level":3,"flags":2}
02-26 20:40:31.988 26840 26965 I CDP     : {"date":"2021-02-26T20:40:31.988","PID":26840,"TID":26965,"message":{"text":"Adding %zu devices for stable user id %s"},"level":3,"flags":2}
02-26 20:40:31.991 26840 26943 I CDP     : {"date":"2021-02-26T20:40:31.991","PID":26840,"TID":26943,"message":{"text":"Scheduling request to submit new CCS command."},"level":3,"flags":2}
02-26 20:40:31.993 26840 27023 I CDP     : {"date":"2021-02-26T20:40:31.993","PID":26840,"TID":27023,"message":{"text":""},"level":3,"flags":2}
02-26 20:40:31.998 26840 26966 I CDP     : {"date":"2021-02-26T20:40:31.998","PID":26840,"TID":26966,"message":{"text":"Started CCS HTTP request to %s. Request ID = %u. Stable User ID = %s. Method = %s."},"level":3,"flags":2}
02-26 20:40:32.067  6699  6840 I SessionStorage/AutoSave: Save: Periodic
02-26 20:40:32.107 26840 26944 I CDP     : {"date":"2021-02-26T20:40:32.107","PID":26840,"TID":26944,"message":{"text":"Wrote settings file for stable user id %s"},"level":3,"flags":2}
02-26 20:40:32.107 26840 26944 W CDP     : {"date":"2021-02-26T20:40:32.107","PID":26840,"TID":26944,"message":{"text":"Attempted to save appregistrationsettings for stable user (%s) not in map."},"level":2,"flags":2}
02-26 20:40:32.219  1029  1029 I android.hardware.health@2.0-service.crosshatch: Entry state_: 1 charger_status: Charging batteryLevel: 100
02-26 20:40:32.219  1029  1029 I android.hardware.health@2.0-service.crosshatch: Exit state_: 1 batteryLevel: 100
02-26 20:40:32.225  2092  2577 D PowerUI : can't show warning due to - plugged: true status unknown: false
02-26 20:40:32.349  1537  2012 D ConnectivityService: NetReassign [no changes]
02-26 20:40:32.530 26840 26965 I CDP     : {"date":"2021-02-26T20:40:32.530","PID":26840,"TID":26965,"message":{"text":"CCS HTTP request succeeded. Request ID = %u. CorrelationVector = %s. CorrelationId = %s. CommandServiceRequestId = %u. HTTP Status Code = %u."},"level":3,"flags":2}
02-26 20:40:32.531 26840 26966 I CDP     : {"date":"2021-02-26T20:40:32.531","PID":26840,"TID":26966,"message":{"text":"CCS client successfully submitted new command. Request ID: %s, Request Status: %s."},"level":3,"flags":2}
02-26 20:40:32.531 26840 26943 I CDP     : {"date":"2021-02-26T20:40:32.531","PID":26840,"TID":26943,"message":{"text":"Cloud Transport successfully submitted CCS request."},"level":3,"flags":2}
02-26 20:40:32.673  6699  6713 W System  : A resource failed to call end.
02-26 20:40:32.811 26840 26944 I CDP     : {"date":"2021-02-26T20:40:32.811","PID":26840,"TID":26944,"message":{"text":"CCS Client initiated poll for changes. Stable User Id '%s', Server Name '%s', Reason '%s'."},"level":3,"flags":2}
02-26 20:40:32.811 26840 26979 I CDP     : {"date":"2021-02-26T20:40:32.811","PID":26840,"TID":26979,"message":{"text":""},"level":3,"flags":2}
02-26 20:40:32.813 26840 26966 I CDP     : {"date":"2021-02-26T20:40:32.813","PID":26840,"TID":26966,"message":{"text":"Started CCS HTTP request to %s. Request ID = %u. Stable User ID = %s. Method = %s."},"level":3,"flags":2}
02-26 20:40:32.828  1537  1599 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.SIG_STR flg=0x10 (has extras) } to com.cheekydevs.fiswitch/.utils.SignalReceiver
02-26 20:40:32.861  6699 11399 I AbstractFirebasePushService: Got new Firebase token: fhHpzwS3Q_ykGjrm0bOAxp:APA91bEEvu6nwrPl-sOopTqz0IoVbgGTKcrGLqx6DLqLKwU7Ck9yK2yVBjkFNswm5Q0XUd0PrQB-oDF8ApFuvQZyR6PA-VLxU3JnzP_tjKlG-puyWKbV-B6s_0MclkQF2He3UVTKRVXQ
02-26 20:40:32.862  6699  6759 I AutoPushFeature: Received a new registration token from push service.
02-26 20:40:32.862  6699 11399 I [INFO][Leanplum]: [com.leanplum.LeanplumCloudMessagingProvider::onRegistrationIdReceived::3]: Device registered for push notifications with registration token, fhHpzwS3Q_ykGjrm0bOAxp:APA91bEEvu6nwrPl-sOopTqz0IoVbgGTKcrGLqx6DLqLKwU7Ck9yK2yVBjkFNswm5Q0XUd0PrQB-oDF8ApFuvQZyR6PA-VLxU3JnzP_tjKlG-puyWKbV-B6s_0MclkQF2He3UVTKRVXQ
02-26 20:40:32.862  6699  6759 I push::communications::rate_limiter: No need to reset inner timestamp and count for update_token.
02-26 20:40:32.863  1000  1004 E statsd  : Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->10277[I] (10)0x30000->fiid-sync[S]
02-26 20:40:32.870  6699  6759 I push::communications::rate_limiter: Allowed to pass through for update_token!
02-26 20:40:33.194  2436  2744 E SQLiteLog: (1) duplicate column name: EVENT_HOST_APP_VERSION_CODE in "alter table DYNAMIC_DETECTION_CALL_API_COUNTS_LOG add column EVENT_HOST_APP_VERSION_CODE INTEGER"
02-26 20:40:33.249 26840 26965 I CDP     : {"date":"2021-02-26T20:40:33.249","PID":26840,"TID":26965,"message":{"text":"CCS HTTP request succeeded. Request ID = %u. CorrelationVector = %s. CorrelationId = %s. CommandServiceRequestId = %u. HTTP Status Code = %u."},"level":3,"flags":2}
02-26 20:40:33.249 26840 26966 I CDP     : {"date":"2021-02-26T20:40:33.249","PID":26840,"TID":26966,"message":{"text":"CCS Client received poll response for Stable User Id '%s'."},"level":3,"flags":2}
02-26 20:40:33.249 26840 26966 I CDP     : {"date":"2021-02-26T20:40:33.249","PID":26840,"TID":26966,"message":{"text":"CCS Client received %zu command(s) in poll response for Stable User Id '%s'."},"level":3,"flags":2}
02-26 20:40:33.585  1035  1109 D VSC     : @ 21323.783: [WO] isFlat() nearest_rotation: 4, flat_angle: 65
02-26 20:40:33.585  1035  1109 D VSC     : @ 21323.783: [WO] orientation angle 355, orientation 4
```

**Comment by hakkikaancaliskan** [comment] 2021-02-27 18:00
Also in the context menu, translate option is missing, i think fenix can't find google translate app either

**Comment by LittleAngelwings** [comment] 2021-02-27 19:11
Tranlate is in smart actions

**Comment by hakkikaancaliskan** [comment] 2021-02-27 19:44
@LittleAngelwings there was an option in context menu that opens a pop up window of google translate app. Now there isn't. Because fenix can't find other apps, so can't show that option.
![Screenshot_20210227-224200_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/109398307-2c715680-794d-11eb-9a0f-36986356df4a.png)

**Comment by LittleAngelwings** [comment] 2021-02-27 20:56
I have this entry (without Google translate App) in 3-dot menu and then smart actions. Why should there two entries? One is enough... But I giess this coud be an other issue.

**Comment by KWierso** [comment] 2021-03-04 21:41
The share pane lists my apps correctly again today.

**Comment by sflorean** [comment] 2021-03-05 13:24
Verified as fixed on Nightly 5/3 with the following devices:
- LG G7 Fit (Android 8.1)
- Pixel 3 (Android 11)

**Closed by sflorean** 2021-03-05 13:24 UTC
Labels: Android:11, Feature:Sharing, eng:qa:needed
