### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by b1100111** [mozilla-mobile/fenix#16088] opened 2020-10-21 13:27 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

The worst bug is that "delete data on quit > open tabs" does not work when android kills firefox. 

The 2nd worse bug is that every use of a bookmark opens a new tab unlike the desktop version which does not force this behavior. 

## Steps to reproduce
1. Enable "delete data on quit > open tabs" 
2. Open several tabs
3.  Do a "close all apps" in android
4.  Start firefox again and view tabs that remain. 

### Expected behavior
Tab count should be 0 upon restart in step 4.

### Actual behavior
All tabs are still there

### Device information

* Android device: ?
Yes 

* Fenix version: ?

**Comment by liuche** [comment] 2020-10-22 00:34
Dupe of #5865 and #15866. Please search for existing bugs before filing, and please be polite.

**Closed by liuche** 2020-10-22 00:34 UTC
Labels: needs:triage, 🐞 bug

**Comment by b1100111** [comment] 2020-10-22 05:26
@liuche I reread my comments a few times and not sure what might have seemed impolite other than maybe comparing one bug to another?

BTW, I did search first,  but it was hard to find those partly because they are maybe broader in scope.

**Comment by b1100111** [comment] 2021-09-14 16:31
In reading those other 2 issues, this issue (https://github.com/mozilla-mobile/fenix/issues/16088) is better focused and more to the heart of the problem.  We should reopen and prioritize it because it would be easy to fix.  The functionality of "close tabs on exit" works properly for "privacy" tabs and just needs the same for non-private tabs.
