### ISSUE TITLE
FNX3-16813 ⁃ [Search] Search bar visual design regression

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3138] opened 2019-06-04 18:21 UTC
In the latest Fenix build, the search bar looks visually wrong compared to previous builds

See latest screenshot

![](https://user-images.githubusercontent.com/5992746/58903133-a326e480-86d2-11e9-8ec9-31735aab7ea0.png)

Spec
![](https://user-images.githubusercontent.com/5992746/58903781-357bb800-86d4-11e9-92d1-a39e19eed4f7.png)
https://mozilla.invisionapp.com/d/main#/console/16853870/353418990/preview

**Comment by ekager** [comment] 2019-06-04 18:39
Ah. Caused by https://github.com/mozilla-mobile/fenix/pull/3029/

**Comment by ekager** [comment] 2019-06-04 18:39
We reuse the component_search in Search and Browser Fragment so we'll have to revert the XML changes here.

**Comment by jonalmeida** [comment] 2019-06-04 18:44
I'll take a look into this from the CT toolbar cleanup.

**Comment by sv-ohorvath** [comment] 2019-06-14 10:39
Verified as fixed on the 6/14 build. Devices: Galaxy Tab S3, Pixel, Nexus 5

**Closed** 2020-08-12 17:37 UTC
Labels: Feature:Search, eng:qa:verified, ux:visual-design, 🐞 bug
