### ISSUE TITLE
FNX-4667 ⁃ [Bug] Watching videos with WR enabled is broken, jittery video, frozen image, sometimes whole tab turns black

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#10896] opened 2020-05-25 13:31 UTC
## Steps to reproduce
1. I had 9 tabs opened, Block Origin add-on installed, and was signed-in with a new account.
1. I've changed the default search engine to Reddit.
1. Typed a random word.

### Expected behavior
The search is performed with the selected search engine, the results are displayed.

### Actual behavior
The page is black, no results are displayed - please see the GIF below.

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: 5/25 Nightly build
* Logcat: [logcat.txt](https://github.com/mozilla-mobile/fenix/files/4677380/logcat.txt)

![](https://user-images.githubusercontent.com/40694158/82816969-c67b0e80-9ea4-11ea-804b-486168b27806.gif)

**Comment by jonalmeida** [comment] 2020-05-25 16:19
I believe this is the same bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1640496

@softvision-miralobontiu did you have a video playing on a tab before this?

**Comment by softvision-miralobontiu** [comment] 2020-05-26 06:20
@jonalmeida yes! I played some videos before this.

**Comment by ekager** [comment] 2020-05-26 15:00
I just saw this while testing PiP the other day!
Changed the title to track the real bug better

**Comment by ekager** [comment] 2020-06-05 19:40
@mcomella shared a video in #11054 as well: 

>The video will start looping a few milliseconds of content (audio is fine). Subsequent interactions with the browser will make it unusable (e.g. content is all black) until I swipe it closed.

Video: https://drive.google.com/file/d/1Wgt6mBdQmRtlT7vIoPdWiYU65ushguaU/view?usp=sharing

**Comment by jbonisteel** [comment] 2020-06-08 18:05
@softvision-miralobontiu Can you still reproduce this issue with the latest version? We have been unable to reproduce it again (https://bugzilla.mozilla.org/show_bug.cgi?id=1640496 for context)

**Comment by softvision-miralobontiu** [comment] 2020-06-09 12:14
Hi all!
I was able to reproduce some parts of this issue, following the steps from comment 0, on the latest Nightly build from 6/9 with Google Pixel (Android 10).
The only difference, the tabs don't turn black, they are just frozen, their content doesn't load (reddit.com, instagram.com).
What is curious, that the exact same pages load as expected in private mode.

<img src="https://user-images.githubusercontent.com/40694158/84146068-b9911a00-aa63-11ea-8d1d-22ca4851ef93.gif" width="300" height="550" />

**Comment by LaurentiuApahideanSV** [comment] 2020-06-16 09:36
Verified as fixed on the latest Firefox Preview Nightly Build 200616 (Build #21680610)

### Device information
- OnePlus 6T (Android 9)

**Comment by LaurentiuApahideanSV** [comment] 2020-06-18 11:12
Verified as fixed on the latest Firefox Preview 5.2.0-beta.2 (Build #21682234)

### Device information
- OnePlus 6T (Android 9)

**Closed** 2020-08-10 22:32 UTC
Labels: Feature:Browsing, Feature:Media, S1, eng:qa:verified, needs:gecko, 🐞 bug
