### ISSUE TITLE
tap-hold "open in" context menu

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#5226] opened 2019-09-11 19:07 UTC
Related to #4575 and #3338

### Why/User Benefit/User Problem
- tap hold on this link: https://docs.google.com/spreadsheets/d/12-NAoBPPV_nNBqaY1vt7Gke8bthPYqnG0tMLeSDrIKI/htmlview
- view the context menu that appears.
- there is no "open in" option 
*note* there should be an open-in option on _every _link_. Not only Google sheets

### What/Requirements
Would like to be able to tap-hold on link and have an option for "open in"   
### Acceptance Criteria (how do I know when I’m done?)
Here's an example from another browser 
![Screenshot_20190915-123025](https://user-images.githubusercontent.com/50635951/64924629-be66bd00-d7b4-11e9-8817-4211ec8783a2.png)

And a shot from fenix 
![Screenshot_20190915-122953](https://user-images.githubusercontent.com/50635951/64924638-cde60600-d7b4-11e9-8857-a9a83564965c.png)

((Additional notes:
 I would like to see "open in" selections and defaults handled within fenix (as is previously was), and not by the OS. 
The issue with fenix previous implementation was that the default "tap" action was "open in". 
"Open in" on a "tap" should only be invoked if an app was set (within fenix) as the default handler for the link  ))

**Comment by nahuhh** [comment] 2019-09-13 13:35
Not sure why title was changed but this has nothing to do with Google sheets (or any specific website)

The request is to add "open in" to the menu to any and every link you tap-hold on. (Example from another browser is in the gif on the op)

**Comment by nahuhh** [comment] 2019-09-15 16:35
Updated the op for clarification

**Comment by NotWoods** [comment] 2019-12-23 07:43
Sorry for misunderstanding the issue at first! Now that we've fixed up Open in App we can work on adding it to other menus. Marking this issue as duplicate of #1754.

**Closed by NotWoods** 2019-12-23 07:43 UTC
Labels: Feature:ContextMenu, Feature:OpenInApp, 🌟 feature request
