### ISSUE TITLE
[Bug] Awesomebar "Switch to tab" arrow button populates the tab's page title instead of URL

### ISSUE THREAD

**Issue by strugee** [mozilla-mobile/fenix#13768] opened 2020-08-12 23:49 UTC
## Steps to reproduce

1. Have some **open tab** that, when you type part of its URL or whatever, will be suggested as a "Switch to tab" result in the awesomebar
 * You can get this by opening a tab with `example.com`, another with `example.org`, and then opening a third tab to reproduce this bug in
2. Type part of the other tab's URL or page title into the awesomebar, such that the "Switch to tab" suggestion is displayed in the result list
3. Tap the arrow pointing up and left at the right of the result

### Expected behavior

The awesomebar should be populated with the other tab's URL. Alternately (much less preferably), the arrow button should not be present for "Switch to tab" type results. For example: `http://example.net`

### Actual behavior

The awesomebar is populated with the other tab's page title. For example: `Example Domain`

### Device information

* Android device: Pixel 3a XL running Android 10
* Fenix version: Nightly built 2020-08-11, build #2015757299, installed via Google Play

**Comment by Mugurell** [comment] 2020-08-24 10:15
![UseSuggestion](https://user-images.githubusercontent.com/11428869/91032645-ebe5f880-e60a-11ea-8f81-25651cf05580.gif)

[video](https://drive.google.com/file/d/1j1J3NVIjyXHP4_WFpiea3RjDajZQ_eWx/view?usp=sharing)

I think this needs some ux-feedback.
The feature was implemented in https://github.com/mozilla-mobile/android-components/issues/6813 and allows to `accept suggestion from search completion without submitting in order to append something or modify it`. 

A different switch to tab button would be really nice though , maybe using a chip to it?
Should we prioritize such buttons higher in the list of suggestions?

**Comment by sv-ohorvath** [comment] 2020-08-24 13:09
There is a switch to tab function and it also has visual indicators, done here: https://github.com/mozilla-mobile/fenix/issues/12622
Similar issue, see also: of https://github.com/mozilla-mobile/fenix/issues/13835

**Comment by apbitner** [comment] 2020-09-02 15:11
Pinging @brampitoyo for Search feedback

**Comment by brampitoyo** [comment] 2020-09-09 01:44
@Mugurell I can confirm that the behaviour @strugee proposed is the correct one.

There are a few types of possible suggestions for the address bar:

1. Search keywords
2. History items
3. Bookmarks
4. Open tabs
5. Synced tabs (open tabs in another device)

Item 1 is special, because it doesn’t have any URL associated with it. They’re suggestions that we fetch from a search provider server. Tapping on the Append arrow should populate the address bar with keywords.

Items 2–5 are different. They all have URLs associated with them. **Tapping on the Append arrow should populate the address bar with the item’s URL**, not the item’s page title.

What happens next:

- If you tap Enter/Return immediately, the URL populated in the address bar will open in the current tab
    - To switch to an open tab instead, tap on the search result item
- If you type a keyword followed by Enter/Return, then Firefox will search for that URL plus the keyword you entered
    - This allows you to search for something like `https://twitter.com #mozilla`

**Comment by codrut-topliceanu** [comment] 2020-09-15 12:03
Seems to have been fixed by removing the "complete" arrow and adding "switch to tab" in the results.

![ezgif-7-1ccda2ffa47c](https://user-images.githubusercontent.com/60002907/93208052-9d88cd00-f764-11ea-9a1b-64597faf67f7.gif)

**Comment by sflorean** [comment] 2020-09-25 09:13
Verified as fixed on Nightly 9/25 with Google Pixel 3 (Android 11).

**Closed by sflorean** 2020-09-25 09:13 UTC
Labels: Feature:Toolbar, eng:qa:needed, eng:ready, hershey, 🐞 bug
