### ISSUE TITLE
[Bug] Toolbar in add-ons page has a thin gap between it and the content

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15653] opened 2020-10-03 09:20 UTC
## Steps to reproduce
Go to add-ons page 
Scroll down so that the toolbar is overlapping an add-on

### Expected behavior
The toolbar would have nothing between it and the page

### Actual behavior
There is a small gap

### Device information

* Android device: ?
* Fenix version: today's nightly

I would type more but input fields are hard to use in Firefox for Android

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7807)

**Comment by VMadalin** [comment] 2020-10-04 17:26
Thank you for your reported issue @Poopooracoocoo . I tried to reproduce it but I cannot reproduce with the lastest `master` changes. Can you please add more details about how to reproduce.

![Screenshot 2020-10-04 at 18 22 57](https://user-images.githubusercontent.com/18151158/95022416-1a75db00-066f-11eb-9b5b-5fd33423f935.png)

**Comment by Poopooracoocoo** [comment] 2020-10-05 00:56
@VMadalin I can see it in your screenshot! There's a thin grey line there that isn't on any other page.

**Comment by VMadalin** [comment] 2020-10-05 17:27
I'm quite confused @Poopooracoocoo there are you the difference between settings and addons screens:
![Screenshot 2020-10-05 at 18 18 19](https://user-images.githubusercontent.com/18151158/95111657-b8cd7380-0737-11eb-8d14-720e533f50a5.png)
![Screenshot 2020-10-05 at 18 18 44](https://user-images.githubusercontent.com/18151158/95111660-b9fea080-0737-11eb-8033-54a7bd69bede.png)

In addition, reviewing the layout hierarchy there are no view for can create that effect just the shadow of the toolbar but it's part of the component:

![Screenshot 2020-10-05 at 18 25 53](https://user-images.githubusercontent.com/18151158/95112042-50cb5d00-0738-11eb-9dd9-108cc699f98b.png)

**Comment by Poopooracoocoo** [comment] 2020-10-06 02:02
This is what I see. 

![20201006_130124](https://user-images.githubusercontent.com/51363864/95150566-27f8a580-07d4-11eb-8243-326ec648b922.jpg)
![20201006_130104](https://user-images.githubusercontent.com/51363864/95150568-2929d280-07d4-11eb-83c8-520a6016ba65.jpg)

**Comment by Mugurell** [comment] 2021-02-03 17:57
That line can be removed but it is not there as the result of a bug.
It's a feature!
We are using the default `ActionBar` from Android that by default comes with a
> hairline as a bottom border of the app bar to ensure differentiation between the top app bar and scrolling content.

https://material.io/components/app-bars-top#anatomy

&nbsp;
![image](https://user-images.githubusercontent.com/11428869/106785535-280b9380-6656-11eb-826f-11df19880619.png)
![image](https://user-images.githubusercontent.com/11428869/106788342-7ff7c980-6659-11eb-8324-e700fa6bc20c.png)

**Comment by Mugurell** [comment] 2021-02-03 17:57
Closing as per the above.

**Comment by Poopooracoocoo** [comment] 2021-02-04 01:54
@Mugurell But you're quoting the iOS bit. iOS has translucency. I don't see it in the Android mockup. I haven't seen other apps with this either. 

![image](https://user-images.githubusercontent.com/51363864/106833704-1d014380-66e8-11eb-9949-02f3f6790525.png)

**Comment by Mugurell** [comment] 2021-02-04 11:42
Looked into it more,
Seems like that line is not a border of `ActionBar` that we use but in fact a 2dp margin added in https://github.com/mozilla-mobile/fenix/issues/8520.
I understand this was added to ensure consistency with other screens so we need to find another way to achieve that instead of [this line](https://github.com/mozilla-mobile/fenix/blob/9783930ac543347df12749f10c95aa7a2e310609/app/src/main/res/layout/fragment_add_ons_management.xml#L15).

**Comment by Poopooracoocoo** [comment] 2021-08-03 12:41
@Mugurell so was this fixed?

**Comment by Mugurell** [comment] 2021-08-03 13:11
There wasn't any update in the meantime for how that screen looks. The issue is still reproducing.
Thanks for removing the "wontfix" label.

**Comment by Poopooracoocoo** [comment] 2021-08-03 14:46
btw how come so many issues are being closed now? most of the ones i've participated in haven't been fixed.

**Comment by boek** [comment] 2023-01-31 17:12
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814180

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-31 17:12 UTC
Labels: 🐞 bug, P5, Feature:WebExtensions, pin
