### ISSUE TITLE
[Bug] [Regression] Several UI features hidden under an additional tap

### ISSUE THREAD

**Issue by kodabb** [mozilla-mobile/fenix#17265] opened 2020-12-30 22:38 UTC
## Steps to reproduce
* open app on a tablet
* try to go back a page or refresh
* no button present on the main UI
* you need to press the hamburger menu
* then press the desired button

### Expected behavior
should be able to go back a page or refresh without going in the submenu, but there are no buttons available, despite the large amount of screen estate available

### Actual behavior
you need to press the hamburger menu, which is a discouraged UI feature on mobile since a few years 

### personal comment
the most used buttons should be readily available, refreshing a page and going back or forth in the history are common actions that should not require an additional tap button. Also there is a lot of "wasted space" like the address bar taking almost the entire horizontal space, which is not as useful as having buttons immediately available.

Perhaps this ui works well for a smart phone, but it's pretty discouraging to use on a tablet. Maybe the more "advanced ui" could be made available under a user option?

### Device information

* Android device: samsung galaxy tab 2018
* Fenix version: latest available version

**Comment by cadeyrn** [comment] 2020-12-30 22:40
Duplicate of #14921.

**Comment by sflorean** [comment] 2020-12-31 08:16
Closing as dupe, based on the above comment.

**Closed by sflorean** 2020-12-31 08:16 UTC
Labels: needs:triage, 🐞 bug
