### ISSUE TITLE
Intermittent debug(T) failure - org.mozilla.fenix.FenixApplicationTest - GIVEN onCreate is called THEN the duration is measured

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#18102] opened 2021-02-21 10:21 UTC
Log: https://treeherder.mozilla.org/logviewer?job_id=330634809&repo=fenix

```
[task 2021-02-21T00:40:21.225Z] SUITE: org.mozilla.fenix.FenixApplicationTest
[task 2021-02-21T00:40:21.225Z]   TEST: GIVEN onCreate is called THEN the duration is measured
[task 2021-02-21T00:40:21.225Z]     [Robolectric] org.mozilla.fenix.FenixApplicationTest.GIVEN onCreate is called THEN the duration is measured: sdk=28; resources=BINARY
[task 2021-02-21T00:40:21.225Z]     I/MonitoringInstr: Instrumentation started!
[task 2021-02-21T00:40:21.225Z]     I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
[task 2021-02-21T00:40:21.225Z]     D/SQLiteCursor: received count(*) from native_fill_window: 1
[task 2021-02-21T00:40:21.323Z]     I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
[task 2021-02-21T00:40:21.323Z]     D/SQLiteCursor: received count(*) from native_fill_window: 1
[task 2021-02-21T00:40:21.323Z]     I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
[task 2021-02-21T00:40:21.323Z]     D/SQLiteCursor: received count(*) from native_fill_window: 1
[task 2021-02-21T00:40:21.323Z]     I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
[task 2021-02-21T00:40:21.324Z]     D/SQLiteCursor: received count(*) from native_fill_window: 0
[task 2021-02-21T00:40:21.324Z]     I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
[task 2021-02-21T00:40:21.324Z]     D/SQLiteCursor: received count(*) from native_fill_window: 0
[task 2021-02-21T00:40:21.324Z]     I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
[task 2021-02-21T00:40:21.324Z]     D/SQLiteCursor: received count(*) from native_fill_window: 0
[task 2021-02-21T00:40:21.324Z]     I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
[task 2021-02-21T00:40:21.325Z]     D/SQLiteCursor: received count(*) from native_fill_window: 0
[task 2021-02-21T00:40:21.326Z]     I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
[task 2021-02-21T00:40:21.327Z]     D/SQLiteCursor: received count(*) from native_fill_window: 0
[task 2021-02-21T00:40:21.328Z]     I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
[task 2021-02-21T00:40:21.329Z]     D/SQLiteCursor: received count(*) from native_fill_window: 0
[task 2021-02-21T00:40:21.330Z]     E/glean/MetricsPingSched: MetricsPingScheduler last stored ping time was not valid
[task 2021-02-21T00:40:21.331Z]     I/glean/MetricsPingSched: The 'metrics' collection is scheduled for today, 1613868021264
[task 2021-02-21T00:40:21.332Z]     D/glean/MetricsPingSched: Scheduling the 'metrics' ping in 11978736ms
[task 2021-02-21T00:40:21.423Z]   FAILURE
[task 2021-02-21T00:40:21.423Z] 
[task 2021-02-21T00:40:21.424Z] java.lang.AssertionError
[task 2021-02-21T00:40:21.424Z] 	at org.junit.Assert.fail(Assert.java:86)
[task 2021-02-21T00:40:21.424Z] 	at org.junit.Assert.assertTrue(Assert.java:41)
[task 2021-02-21T00:40:21.424Z] 	at org.junit.Assert.assertTrue(Assert.java:52)
[task 2021-02-21T00:40:21.424Z] 	at org.mozilla.fenix.FenixApplicationTest.GIVEN onCreate is called THEN the duration is measured(FenixApplicationTest.kt:33)
[task 2021-02-21T00:40:21.424Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-02-21T00:40:21.424Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-02-21T00:40:21.424Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-02-21T00:40:21.424Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-02-21T00:40:21.424Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2021-02-21T00:40:21.424Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2021-02-21T00:40:21.424Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2021-02-21T00:40:21.424Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2021-02-21T00:40:21.425Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2021-02-21T00:40:21.425Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
[task 2021-02-21T00:40:21.425Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[task 2021-02-21T00:40:21.425Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
[task 2021-02-21T00:40:21.425Z] 	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
[task 2021-02-21T00:40:21.425Z] 	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[task 2021-02-21T00:40:21.425Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[task 2021-02-21T00:40:21.425Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2021-02-21T00:40:21.425Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2021-02-21T00:40:21.425Z] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mcarare** [comment] 2021-02-22 08:26
cc @mcomella

**Comment by mcomella** [comment] 2021-02-23 01:09
Thanks for the ping. This failed 4 times on mc (from a query I saw) and at least once here (#18108) so it seems like it occurs often enough that it's important to address.

I don't know what the root cause is but here are my initial thoughts:
- Robolectric can be pretty finicky: it's possible the interaction of our app and lifecycle is not working as I expect
- It's possible there's a race condition between Glean's metric reset code (e.g. the glean test rule) and robolectric's set up code
- Robolectric is known to not close down threads started during it. I wonder if the glean API thread, or other threads, are creating race conditions in the behavior

**Comment by mcomella** [comment] 2021-02-23 01:11
- We early return if this isn't the main process: maybe, in some tests, this conflicts with the probe being measured at the ned
- The behavior of this code changes when the migrating fenix application is used

**Comment by mcomella** [comment] 2021-02-23 22:53
With the test ignored, I don't think fixing the test is a major priority. The implementation is simple so it seems unlikely the cause is the implementation – it's more likely how this test combines with the lifecycle of the robolectric tests, which is a notably finicky API.

Furthermore,  we should be able to sanity check the correctness of this probe by comparing the number of entries compared to the `framework_start...` probe (which I'll do once that data is showing in GLAM) or the `app_opened_all_startup COLD` probe. Let's do that before we invest in trying to debug the failure further.

CC @mcarare

**Comment by mcomella** [comment] 2021-03-04 00:12
Triage: is this really just robolectric's or GleanTestRule's fault or could we have a real bug (e.g. a race condition in glean)? We should find out. If we find out it's just ^, we should remove the test and close the issue (or fix it if it seems feasible).

**Comment by eliserichards** [comment] 2021-03-16 17:35
I am similarly seeing these tests fail consistently on [this PR](https://github.com/mozilla-mobile/fenix/pull/18490): 
<img width="368" alt="image" src="https://user-images.githubusercontent.com/43795363/111354121-f96cd980-8653-11eb-92a5-8f4b866704f7.png">

This seems related?

**Comment by mcomella** [comment] 2021-03-16 17:49
> I am similarly seeing these tests fail consistently on [this PR](https://github.com/mozilla-mobile/fenix/pull/18490):
> 
> This seems related?

@eliserichards I'm not sure – I think the cause of this issue is a tricky interplay between the robolectric lifecycle, glean test rule, and the fact that my test is relying on a robolectric action before the test is run.

Whereas `StorageStats` is a more straightforward use case: a test using a glean measurement. It doesn't look like `StorageStats` or its test has changed recently so I wonder if the root cause could be a glean version upgrade or something.

**Closed** 2021-09-16 20:17 UTC
Labels: eng:performance, eng:intermittent-test
