### ISSUE TITLE
[Bug] Opening crash

### ISSUE THREAD

**Issue by Furax-31** [mozilla-mobile/fenix#7607] opened 2020-01-10 20:38 UTC
## Steps to reproduce

Open the app

### Expected behavior

Application should open

### Actual behavior

Application crash on opening

### Device information

* Android device: A5 2017 - Android Pie
* Fenix version: Last build: 200110 18:01

**Comment by marcinwiacek** [comment] 2020-01-10 20:56
01-10 21:10:18.163 25266 25306 E AndroidRuntime: Process: org.mozilla.fenix.nightly, PID: 25266
01-10 21:10:18.163 25266 25306 E AndroidRuntime: java.lang.ExceptionInInitializerError
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at mozilla.appservices.push.LibPushFFI.<clinit>(Unknown Source:0)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at mozilla.appservices.push.PushManager.<init>(PushManager.kt:6)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at mozilla.components.feature.push.RustPushConnection.updateToken(Connection.kt:13)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at mozilla.components.feature.push.AutoPushFeature$$special$$inlined$let$lambda$1.invokeSuspend(AutoPushFeature.kt:10)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: Caused by: mozilla.appservices.support.native.IncompatibleMegazordVersion: Incompatible megazord version: library "push" was compiled expecting app-services version "0.48.1", but the megazord "fenix" provides version "0.44.0"
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at mozilla.appservices.support.native.HelpersKt.lookupMegazordLibrary(Helpers.kt:13)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at mozilla.appservices.support.native.HelpersKt.findMegazordLibraryName(Helpers.kt:4)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at mozilla.appservices.push.LibPushFFI$Companion.<clinit>(LibPushFFI.kt:2)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	... 9 more

**Comment by cadeyrn** [comment] 2020-01-10 20:58
should be fixed by #7601 in the next build.

**Comment by ekager** [comment] 2020-01-10 23:05
Closing as this a new nightly is going out now (will take a few hours). Thanks for your patience!

**Closed by ekager** 2020-01-10 23:05 UTC
Labels: 🐞 bug
