### ISSUE TITLE
Be able to change the order of the tabs

### ISSUE THREAD

**Issue by Sav22999** [mozilla-mobile/fenix#14091] opened 2020-08-23 09:59 UTC
### What is the user problem or growth opportunity you want to see solved?
In the old-Firefox version you were able to change the order of the tabs. Now you are not able to do this anymore.

### Who will benefit from it?
Everyone

**Comment by jonalmeida** [comment] 2020-08-24 16:41
Duplicate of #2487

(as mentioned above).

**Closed by jonalmeida** 2020-08-24 16:41 UTC
Labels: needs:triage
