### ISSUE TITLE
[Bug] Can't download svg files

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5601] opened 2019-09-26 13:54 UTC
## Steps to reproduce
1. Go to svgomg.firebaseapp.com
2. Tap the Demo link.
3. Download the demo image using the button under it.
### Expected behavior
The image is downloaded and can be viewed.
### Actual behavior
"Firefox Nightly can't download this file type."
### Device information

* Android device: Pixel 3 (Android 9)
* Fenix version: Nightly 9/25

**Comment by NotWoods** [comment] 2019-10-06 06:54
Duplicate of mozilla-mobile/android-components#1159. The issue here is that SVGOMG generates a `blob:` URL, not that it is downloading an SVG.

**Comment by Amejia481** [comment] 2020-05-15 14:59
Now we have support for blob URLs. QA please help us to verify if this website is working as expected.

**Comment by sflorean** [comment] 2020-05-18 14:51
Verified as fixed on Nightly 5/18.
Devices: Samsung Galaxy Note10 (Android10), Nokia 6 (Android 7.1.1), Xiaomi Mi Pad 2 (Android 5.1)

**Closed by sflorean** 2020-05-18 14:51 UTC
Labels: Feature:Download, eng:qa:needed, 🐞 bug
