### ISSUE TITLE
[Bug] Application crashes when trying to login on the site

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/fenix#7637] opened 2020-01-13 09:08 UTC
## Prerequisites:
Mastodon account created and instance chosen (Create account here https://qoto.org/about). 

## Steps to reproduce
1. Navigate to https://pinafore.social
2. Tap "Log in" button.
3. Fill in the instance name (e.g Qoto.org) and tap "Log in".
4. Fill in your email and password and tap "Log in".
5. Observe behavior.

### Expected behavior
Redirect to authorization page is performed (screenshot attached).

### Actual behavior
Application crashes. Login is not performed.

### Notes
1. The issue is not reproducible on Firefox Preview 3.0.2 (🦎 71.0.1-20200108003105) and Firefox Nightly 68.5a1 (2020-01-11).
2. Also reproducible when trying to sign into https://accounts.fitbit.com/login 
3. Same root cause as [#7625](https://github.com/mozilla-mobile/fenix/issues/7625)

Crash log:
```java
2020-01-13 10:55:45.958 16338-16338/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 16338
    kotlin.NotImplementedError: Unable to validate saved logins. Are you using the correct class mozilla.components.concept.storage.NoopLoginValidationDelegate (Kotlin reflection is not available)?
        at mozilla.components.feature.prompts.dialog.LoginDialogFragment$update$1.invokeSuspend(LoginDialogFragment.kt:29)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

### Device information
* Android device: Huawei P20 Lite (Android 8.0.0) - 1080 x 2280 pixels, 19:9 ratio (~432 ppi density), Samsung Galaxy S7 Edge (Android 8.0.0) - Resolution 1440 x 2560 pixels (~534 ppi pixel density)
* Fenix version: Firefox Preview Nightly 200112 (🦎 74.0a1-20200110095023)

![AppCrashLogin](https://user-images.githubusercontent.com/12184325/72243429-95382b00-35f4-11ea-817d-d80dcdf5c770.gif)

Firefox Preview Authorization page:
![image](https://user-images.githubusercontent.com/12184325/72242598-818bc500-35f2-11ea-8580-8bd1b114ae67.png)

**Comment by sv-ohorvath** [comment] 2020-01-13 09:46
dupe of https://github.com/mozilla-mobile/fenix/issues/7625.

**Closed by sv-ohorvath** 2020-01-13 09:46 UTC
Labels: S1, b:crash, 🐞 bug
