### ISSUE TITLE
[Bug]: Sharing menu in dark mode has invisible text

### ISSUE THREAD

**Issue by GoudronViande24** [mozilla-mobile/fenix#23398] opened 2022-01-25 14:12 UTC
### Steps to reproduce

1- Open a web page
2- press the share icon in menu
3- try to read the labels

### Expected behaviour

Put white labels so it's readable

### Actual behaviour

![Screenshot_20220125-090351897](https://user-images.githubusercontent.com/42936037/150992591-62e2ffcc-8845-4859-af47-8caf9bcba491.png)

The text is too dark

### Device name

ASUS ZenFone 5z

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

95.2.0

**Comment by RotBolt** [comment] 2022-01-30 14:37
@eliserichards @mcomella I think it's an easy one. Should I start with this one, to resume my contributions on Fenix?

**Comment by Amejia481** [comment] 2022-02-01 23:17
Yes @RotBolt please proceed. I could help you with any additional things that you need :)

**Comment by SoftVision-LorandJanos** [comment] 2022-02-02 13:49
Hi @GoudronViande24! Thanks for your report!
This issue was reported a few times and was even fixed before: #18195, #22490, #23005.
One of the tickets is still open and if I understand it right, the fix for it should fix this one also: #18768.
I could reproduce the issue on the latest Nightly 98.0a1 (2022-02-02) as well, using an Oppo Reno 6 with Android 11.
@Amejia481, should we close this as duplicate of #18768?

**Comment by RotBolt** [comment] 2022-02-02 13:54
according to your comment, this should have been fixed in https://github.com/mozilla-mobile/fenix/pull/18880 PR
But did not get fixed. Any reason why is it still recurring? cc @SoftVision-LorandJanos

**Comment by RotBolt** [comment] 2022-02-02 13:59
I think over time, colors got changed and the color the previous PR raiser added, got out of date

IMHO, we should have two different colors for texts in dark and theme mode, instead of going for single color and setting contrast 
WDYT @Amejia481

**Comment by RotBolt** [comment] 2022-02-09 17:43
Let me create PR with different color, At least it will start something

**Comment by gabrielluong** [comment] 2022-02-09 21:56
This is actually gonna be fixed in https://github.com/mozilla-mobile/fenix/pull/23038.

**Closed by gabrielluong** 2022-02-09 21:56 UTC
Labels: 🐞 bug, Feature:Themes, S3, needs:triage, qa-triaged
