### ISSUE TITLE
FNX-4981 ⁃ [Meta] Launch in private browsing mode by default

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1368] opened 2019-04-03 23:09 UTC
As a user, I want the option to launch Fenix in private browsing mode.

### Acceptance Criteria
-UX completed
-User stories completed
-Strings written and approved
-QA completed
-Localization done

**Comment by NotWoods** [comment] 2019-07-09 18:58
Duplicate of #514 (Sorry for re-opening!)

**Closed** 2020-08-11 11:31 UTC
Labels: Feature:PrivateBrowsing, must
