### ISSUE TITLE
Soft keyboard breaks when switching between private and normal tabs

### ISSUE THREAD

**Issue by jjungb** [mozilla-mobile/fenix#16801] opened 2020-12-01 15:42 UTC
Version 83.1.0

Soft Keyboard will disappear and will not be usable in any webpage unless app is restarted. Without keyboard user will not be able to comment or enter password etc. This doesn't happen on all pages but do happens on hotmail and reddit for an example.

Steps to reproduce
1 go to https://old.reddit.com/r/sweden/comments/k4487m/ljudet_av_malm%C3%B6_kostade_halv_miljon_har_anv%C3%A4nts/
2 open any link in page in a private tab, example: https://www.svt.se/nyheter/lokalt/skane/malmos-ljudidentitet-kom-bort-under-pandemin
3 switch to private tab
4 switch back to original tab
5 focus the comment field
Expected: keyboard shows and user can enter a comment
Actually: keyboard will not show and user cannot enter comment.

**Comment by kbrosnan** [comment] 2021-01-04 18:07
Duplicate of #12982

**Closed by kbrosnan** 2021-01-04 18:07 UTC
Labels: Feature:IME, S2
