### ISSUE TITLE
[Bug] When closing tab (Pop-Up)

### ISSUE THREAD

**Issue by J41319** [mozilla-mobile/fenix#7963] opened 2020-01-29 01:37 UTC
## Steps to reproduce

Just keep opening and closing tabs, so the bug may appear.

### Expected behavior

When closing the tab, the pop-up to undo the action have to disappear after a few seconds.

### Actual behavior

The pop-up sometimes doesn't disappear

### Device information

Xiaomi Mi A3

* Android device: 9.0
* Fenix version: 3.2.0

Video: https://imgur.com/a/NzcyyG8

**Comment by cadeyrn** [comment] 2020-01-29 06:24
Duplicate of #7799.

**Closed** 2020-01-30 00:24 UTC
Labels: needs:triage, 🐞 bug
