### ISSUE TITLE
[Bug] Back / Forward button is missing

### ISSUE THREAD

**Issue by yurijgera** [mozilla-mobile/fenix#19833] opened 2021-06-04 20:44 UTC
Back and forward buttons are completely missing in the navbar.
There are some hidden under tripple bar, but this requires several klicks and is experience braking to use.
The android back button works but is located on the bottom of the screen where it is hard to reach depending on the situation.
Back button on the left side of the navbar (no matter if its on top or bottom of the screen) was best place to reach since the release of the first browser (Netscape in 1994). 
All browsers I know of have instantly reachable back button.
Currently the experience with missing back button is so frustrating, that I had to switch to another browser until its fixed.
The issue was already reported in 2020 and it was promised to bring back "Back" button in v80.
Now its v89 and still no back button there.

## Steps to reproduce
Start browser
Navigate to any web page
Navigate to any other web page

### Expected behavior
There is back button

### Actual behavior
No back button.

### Device information
Samsung Tab S7
Android 11
Firefox 89.1.1

**Comment by cadeyrn** [comment] 2021-06-04 20:47
Duplicate of #14921.

**Comment by yurijgera** [comment] 2021-06-04 21:10
> Duplicate of #14921.

Following that discussion I think I now unerstand the situation.
The problem seem to be the missing UI mode for tablets.
On a smartphone the Android back button is easily reachable and there is no need for the browser to display its own, allowing to save the very limited screen space.
On a tablet however, the Android back button may not be easy to reach, depending on how one currently holds the tablet. The back button in the nav bar would help. Tablets got more than enough screen space for that. But for this the browser would need to distinguish between and support smartphones and tablets separately.

**Comment by kbrosnan** [comment] 2021-06-07 17:47
Closing as a duplicate.

**Closed by kbrosnan** 2021-06-07 17:47 UTC
Labels: needs:triage, 🐞 bug
