### ISSUE TITLE
Send tab to device without opening the browser

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#1523] opened 2019-04-10 15:28 UTC
### Why/User Benefit/User Problem
If you want to share directly to your desktop without having the page load in your mobile browser.

### What / Requirements
Implementing [Android Direct Share](https://github.com/googlesamples/android-DirectShare) and/or Fennec-style sharing.

IF NOT AVAILABLE on lower API devices show a dialog with the send tab share targets.

### Acceptance Criteria (how do I know when I’m done?)
Being able to share directly to a desktop **without needing to open it on mobile first**.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7133)

**Comment by vesta0** [comment] 2019-08-23 17:33
No longer doing this.

**Comment by ryanfeeley** [comment] 2019-08-29 17:56
@vesta0 It's a feature that Fennec had, and iOS has today. Combined, users likely spend more time in other apps than Firefox Preview, so this is a great surface to let them know about the feature.

Here is what it looks like in iOS:
<img width="611" alt="image" src="https://user-images.githubusercontent.com/68213/63964269-c01a4c00-ca64-11e9-980c-0529c4dd6e66.png">

https://mozilla.invisionapp.com/share/BGTC5727HY2#/377726327_iOS_Send_Tab-

**Comment by jonalmeida** [comment] 2019-08-29 19:48
I've updated the user story to include devices that may not be supported with the 

> IF NOT AVAILABLE on lower API devices show a dialog with the send tab share targets.

**Comment by KayzzenD** [comment] 2020-05-08 20:24
This feature is very useful. I think that like most people who know this feature, without a doubt use it frequently 😄.

**Comment by madb1lly** [comment] 2020-05-08 21:54
Hi all,
@kayzzen01 you're right, I do use this a lot with Fennec, without even realising it!
Cheers 🙂

**Comment by justdave** [comment] 2020-05-19 17:30
Use case from #8937:
Having to share by opening it in the app first breaks some URLs for example:
If the link I'm sending from an email requires me to log in in order to view it, it often redirects to a login page. the login page is then what gets sent to the other device, and it loses the after-login destination.
I tend to use my phone for email even when I'm working at my laptop, but I'd rather use the laptop's web browser as long as I'm sitting at it.

**Comment by justdave** [comment] 2020-05-19 17:36
Also: the lack of this feature will be seen as a regression to people being force-upgraded from Fennec.

**Comment by jonalmeida** [comment] 2020-05-19 19:21
I've updated the title of this issue to reflect the feature request as accurately as possible.

**Comment by justdave** [comment] 2020-07-13 05:11
I now have the release version of Firefox installed alongside my nightly because it still has this feature, and that's the only thing I use it for.  In fact, if it makes the user experience better, I would be happy with a standalone app that only provided a share target to send to my other Firefox Account devices.  But as it stands, I'll be losing that feature completely when the current beta moves to release.

**Comment by Neikon** [comment] 2020-07-16 23:28
> I now have the release version of Firefox installed alongside my Nightly because it still has this feature, and that's the only thing I use it for (I still use Nightly as the default browser).

Me too

**Comment by vurtomatic** [comment] 2020-08-03 22:22
YES PLEASE PLEASE bring this back! This regression is worsening usability. Please please bring back a direct "Send tab to device" option in the share sheet. Opening a URL in the browser to send the URL to a different device doesn't make sense—I'm not interested in opening the page on my mobile if I'm trying to send it to a different device.

**Comment by ProudNoob** [comment] 2020-08-05 08:34
The number of things to do now to share your link to desktop: 

-    Hold a link
-    Click share
 -   Click "Firefox Beta"
 -   Wait for the page to load in the browser/browser to open.
 -   Click the three dots in the lower right
 -   Click share
 -   Click what other Firefox client I wish to send it to

That's... A lot of steps with time waiting for things to load. The older version of firefox handles this waaaay better. With it, you need to:


   - Hold a link
   - Click share
   - Click "Add to Firefox"
   - Click what other Firefox client I wish to send it to

This not only drops 3 steps, but also the need to load the entire browser. You can still open it with Firefox stable as well, just click "Open in Firefox", instead of one of your other Firefox clients.

The ease of sharing links with Firefox Mobile the only reason I use it over Chrome, if it keeps being like this current form then I may have to switch to Chrome to use Join app for faster and less hassle link sharing.

**Comment by mobd** [comment] 2020-08-08 22:07
Personally I like being able to open a link in one click. Maybe there can be multiple options in the initial share menu, rather than one that always goes to a menu.

**Comment by vurtomatic** [comment] 2020-08-08 22:24
Yes, that's how it was previously I think? The share sheet had options to Open in Firefox Nightly, Send to other devices.

**Comment by mobd** [comment] 2020-08-08 22:57
Sorry, maybe I didn't explain myself well. What I disliked about the share sheet in Fennec is that in the vast majority of cases I just want to open a page in the browser, but every time I'm presented with a whole menu.

An alternative could be to have two share intents in Android's share menu: one to open the link and one to send it to a device.

Or Fenix's share menu could have a "use by default" option that allows users to bypass the menu.

**Comment by vurtomatic** [comment] 2020-08-08 23:24
You mean this:

![Image of Andriod_link_share](https://user-images.githubusercontent.com/10663730/74280490-7e5b2600-4cd1-11ea-9bc8-529b19dd4c2a.png)

![Image of Fennec_open_menu](https://user-images.githubusercontent.com/10663730/74281136-bf076f00-4cd2-11ea-90e2-8948973e3e69.png)

Images from [here](https://github.com/mozilla-mobile/fenix/issues/8323).

We'd have to click on the "Share link" option which shows the Android share sheet with the option "Add to Nightly". Clicking on "Add to Nightly" gave the above options.

I think what you're asking for is a different issue from this. We're trying to get those share options back into Nightly for Android.

**Comment by madb1lly** [comment] 2020-08-10 06:24
Hi all,

@mobd I may be mistaken but IIRC with Fennec as the default browser, tapping a link in another app always opens the link directly in Fennec (unless tab queuing is enabled, in which case it is added to a list for the next time Fennec is opened, a great option, hint hint Fenix team! 😉).

If the link is _shared_ then the Add to Firefox option then shows the next screen, as @vurtomatic shows above.

Cheers 🙂

**Comment by metronidazole** [comment] 2020-08-20 07:06
Is anyone working on this? This is a major regression and I'm not sure why Fenix was forced upon everyone while lacking a major feature.

**Comment by JoGarWeb** [comment] 2020-08-28 23:27
I want this feature back !!! 😭

**Comment by Kyrluckechuck** [comment] 2020-08-29 14:31
Interesting that this is marked as a feature request and not a bug since it's a regression, no?

**Comment by Dunexus** [comment] 2020-08-29 15:47
@Kyrluckechuck
Fenix is an entire rewrite of the browser around geckoview.
As such, from a developer point of view, a bug is something already implemented in Fenix but not working as intended while a feature request is something not already implemented (even if it was present in the old firefox, aka Fennec).

**Comment by justdave** [comment] 2020-08-30 07:41
> @Kyrluckechuck

Except they released it under the same name and are billing it as an upgrade to the existing app. So the lack of a feature that was present in Fennec is a regression. And every end user who used that feature will see it that way, no matter what the developers think, especially since you're being forced to upgrade.

**Comment by Dunexus** [comment] 2020-08-30 12:27
Please understand that this github repository is a tools for developers. Issues are labeled from a developer point of view to help them knowing the status of the issue regarding to the source code and not to deny that this feature was present and is now missing.

**Comment by madb1lly** [comment] 2020-08-31 08:55
Hi @Dunexus,

I think that's an overly simplistic view of things. This repo _is_ for developers, but it's not necessary - Mozilla could have kept this internal, but they didn't because they wanted 1) volunteer contributions and 2) people to report issues.

Now, all Firefox on Android users have been transitioned to Fenix. If a feature is no longer available then in the context of "Firefox for Android" the absence of this feature is now a bug, not a feature request. If all missing features have to be feature requests then strictly this means Mozilla could release a completely featureless browser with no bugs and say that all missing features are a feature request! That would be complete nonsense, therefore it is not reasonable for missing features to be considered as feature requests, they _must_ be reported as bugs.

On topic 😉 I find myself flicking through emails on my phone and find a link that I need on my desktop, e.g. this GitHub one, it is an inconvenience to have to open in Firefox then share, it's at least one more interaction I need to do. The ability to directly share a link in another app to device is something that many Fennec users will miss.

Also, I see the "Fennectransition" label for this issue - surely the issues with this lable must now assume a higher priority since the whole userbase is now on Fenix?

Cheers 🙂

**Comment by cadeyrn** [comment] 2020-08-31 09:05
>  If a feature is no longer available then in the context of "Firefox for Android" the absence of this feature is now a bug, not a feature request.

No. A missing feature is not a bug, even if it was present in the old product. If a feature is not (yet) implemented it's _expected_ that it's not there and can't be classified as a bug. A bug is always the unintended consequence of a change.

**Comment by madb1lly** [comment] 2020-08-31 10:09
Hi @cadeyrn,

Here's how it looks to the vast majority of users:

-  I want to share direct from a link in another app to a synced Firefox instance on another device
-  I used to be able to do this
-  Now I can't
-  Therefore it's not working, it is a bug.

Did the new Firefox for Android release to all users with a textbook listing all the features which were removed and no longer present? No, it didn't. Therefore, features that were there last week but not there any more are bugs, not feature requests.

If you take your car to the garage for a service and they "update" the software and your car's engine now has less power, this is not the absence of a feature, it is analagous to a bug - you complain the garage that they've broken something, you don't "raise a feature request" to get the missing power back.

And I know you like to reply when you are "attacked" (as you have written elsewhere) but you also like to remain on topic. So let's accept that there are _strong_ differences of opinion here.

Cheers 🙂

**Comment by magikmw** [comment] 2020-08-31 10:50
@cadeyrn @madb1lly 
"Technically" it's not a bug. Developers don't see it as one.

As a project manager I can tell you that when users have their workflow changed for no apparent benefit (and I don't think there's any benefit to this feature being cut), you're going to get some strongly worded complaints. I totally agree with @madb1lly here that from users' perspective something they used is broken. It may not be a bug in the software, but it certainly does feel like a mishandling of the feature set by the project management.

Is it a bug? Let's agree it's not. Should it be on a list of features to priority when porting? Only people having access to usage data (if there is any) can tell us. Sure having it here as a 'feature request' seems much lower priority than a lot of other issues on this repo. Which feels like a slap to anyone that used it extensively - it doesn't seem like I needed to request anything for the past couple of years of using Firefox, right?

For sure it has reduced my Firefox for Android usage significantly, as sending tabs over to my desktop feels like a chore I have to relearn every time I need to do it. If the idea for the feature cut was to increase engagement (do you need that in an Ad-free app?), it failed in my case.

**Comment by Razunter** [comment] 2020-08-31 10:56
Fastest way to transfer links for me now is this: [Lynket Browser](https://play.google.com/store/apps/details?id=arun.com.chromer) as default with FF selected, open links instead of sharing, then it has FF's share menu on the panel.
It's better than sharing to FF, opening tab, sharing tab, closing tab, closing FF.

**Comment by jacktose** [comment] 2020-08-31 15:49
@vesta0 @Dunexus @cadeyrn
Obviously the dev team need to use the terms and categories that make sense for their workflow. I suggest that their should be a “Regression” or “Feature Regression” tag if it needs to be separated from the “oops it's crashing now” actual-bugs. Then it can still be categorically different from (and higher priority than) the “I want the browser to make toast” feature requests.

**Comment by csadilek** [comment] 2023-01-05 17:56
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1808750

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2023-01-05 17:56 UTC
Labels: Feature:AndroidIntegration, Feature:FennecTransition, Feature:SendTab, Feature:Sharing
