### ISSUE TITLE
[Bug] Crash when opening home screen shortcut that happens to have same url as custom tab

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15122] opened 2020-09-15 19:53 UTC
## Steps to reproduce
Open a url in a custom tab
Seperately add that url to homescreen
Click on homescreen shortcut
### Expected behavior
It opens new tab with url
### Actual behavior
Crash
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment] 2020-09-15 19:54
```
c7f9c57c-a4ab-40a9-b84e-53d3c4ba5323
java.lang.IllegalArgumentException: Selected session must exist
----
java.lang.IllegalArgumentException: Selected session must exist
	at mozilla.components.browser.session.storage.SessionStorage.save(SessionStorage.kt:6)
	at mozilla.components.browser.session.storage.AutoSave$triggerSave$1.invokeSuspend(AutoSave.kt:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)


```

**Comment by klint** [comment] 2020-09-16 08:36
I have a crash when opening PWA shortcuts. Is it the same issue?

**Comment by liuche** [comment] 2020-10-26 17:59
This is related to the PWA crash #15116

**Comment by s-ankur** [comment] 2020-10-26 19:04
@liuche did you see my comment (https://github.com/mozilla-mobile/fenix/issues/15122#issuecomment-692944202). The crash signature given by @klint seems unrelated to mine

**Comment by liuche** [comment] 2020-10-28 20:42
Are you still seeing this? This is actually a dupe of #15008 that should have been fixed in 82.

**Comment by s-ankur** [comment] 2020-10-28 20:50
No, it seems solved, thanks

**Closed** 2020-10-29 03:38 UTC
Labels: needs:triage, 🐞 bug
