### ISSUE TITLE
[Bug] Find in Page covers geckoview web content

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#18122] opened 2021-02-23 11:17 UTC
### Steps to reproduce

- _Preconditions_: Open Fenix Settings -> Customize; set `Toolbar` TOP, set `Scroll to hide toolbar` to OFF
- Open new tab and navigate to `wikipedia.org`
- Scroll to bottom of the page ( you can clearly see "Terms of Use", "Privacy Policy", etc)
- Click 3 dot menu and select `Find in Page`
- Type "Terms of Use"
- Press back to hide keyboard

### Expected behavior

- Found text/bottom of the page should be visible

### Actual behavior

- `Find in Page` editText box coves the lower part of the geckoview obscuring the found "Terms of Use" text. Cannot scroll down further to bring "Terms of Use" into view

### Device information

* Device vendor / model and Android version: Pixel 3XL(Android 10), Pixel 4 (Android 11)
* Firefox for Android version: current master, and Nightly 2100222
 
<img src="https://user-images.githubusercontent.com/60002907/108835545-4bcc5480-75d8-11eb-8f9e-d25723316df7.png" width="300"/>
<img src="https://user-images.githubusercontent.com/60002907/108835358-0ad44000-75d8-11eb-9bd6-5819c5e05f26.png" width="300"/>

Also of note: Top toolbar is missing.

**Comment by test491** [comment] 2021-02-25 14:07
reproducible also on
* version: 87.0.0-beta.1 (Build #2015795065) AC: 73.0.0, 69a800e47 GV: 87.0-20210222154334 AS: 71.0.0

> android 9, Galaxy J7 Nxt

**Comment by LaurentiuApahideanSV** [comment] 2021-03-04 10:31
I can confirm the issue is reproducible on Firefox Preview 86.1.1, 87.0.0-beta.2 and Nightly 210304.
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)

**Comment by ebalazs-sv** [comment] 2021-04-13 13:03
Verified as fixed on Nightly 4/13 with Samsung Galaxy Tab S3 (Android 8).
The "Terms of Use" is visible when the keyboard is hidden.

**Closed by ebalazs-sv** 2021-04-13 13:03 UTC
Labels: Feature:FindBar, Feature:Toolbar, eng:qa:needed, qa-triaged, 🐞 bug
