### ISSUE TITLE
[Bug] Download hangs

### ISSUE THREAD

**Issue by callegar** [mozilla-mobile/fenix#9908] opened 2020-04-14 11:07 UTC
## Steps to reproduce

Issue is not 100% reproducible. It only happens sometimes. Go to a website that provides downloads, preferrably downloads of large files in places where the network is not so good.  Trying to download the next apk of fenix itself may be an option.

Click the link to get the file downloaded

### Expected behavior

Either the file downloads fine or firefox provides an error message.

### Actual behavior

Sometimes the download hangs. The phone maintains a notification about a file being downloaded. Clicking on the notification provides a small window with a progress bar (blocked) and two buttons "Pause" and "Cancel". Neither of them works.

To get rid of the notification, the only thing to do is to go in the App settings and to force the fenix application to quit.

### Device information

Lenovo/Motorola Moto G6 with Android 9.
Fenix 4.1

**Comment by Amejia481** [comment] 2020-04-20 15:56
It looks pretty similar to https://github.com/mozilla-mobile/fenix/issues/9884

**Comment by Amejia481** [comment] 2020-04-27 20:50
This should be fixed in master.
@callegar and QA would you mind verifying if this is still an issue? Thanks in advance :)

**Comment by callegar** [comment] 2020-04-27 21:32
As soon as there is a new release with ARM64 builds, I'll be glad to test. Sorry, cannot build myself for the time being.

**Comment by sv-ohorvath** [comment] 2020-04-28 10:43
@Amejia481 isn't this a dupe of #9884?
If it is, we should close it. 
Otherwise, I can still reproduce the issues on Nightly 4/28.

**Comment by Amejia481** [comment] 2020-04-28 13:48
Agree let's close it in favor of #9884

**Closed by Amejia481** 2020-04-28 13:48 UTC
Labels: Feature:Download, S3, 🐞 bug
