### ISSUE TITLE
FNX-5326 ⁃ [Bug] Tabs disappear intermittently

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#1909] opened 2019-04-22 21:55 UTC
## Steps to reproduce
* Open a Tab and then press back or click on the tab icon

### Expected behavior
* All my tabs are shown

### Actual behavior
* Sometimes no tabs are shown, it's random, seems to appear when Fenix is brought back to the foreground but not always (see video)

### Device information
* Android device: Samsung S10e
* Fenix version: Latest from playstore

https://i.imgur.com/psqApvA.mp4

**Comment by bsurd** [comment] 2019-04-24 11:59
I've found some reliable STR for this:
1. Open one or several tabs.
2. Remain in the last opened tab for several minutes.
3. Tab the tab counter or back button.

With these steps, I've had a 100% reproduce rate.

#### Device information
* Android device: 
     * Nexus 5 (Android 6.0.1)
     * HTC 10 (Android 8)
* Fenix version: 1.0.1917 (#11131208)

**Comment by AaronMT** [comment] 2019-04-24 15:41
Comment from Reddit about this too

https://www.reddit.com/r/firefox/comments/bgubqx/firefox_preview_fenix_has_a_rad_new_icon/elnlptg/

**Comment by colintheshots** [comment] 2019-05-01 18:55
This is likely blocked by #1994.

**Comment by colintheshots** [comment] 2019-05-10 19:17
This is now blocked on #2418, since it was split away from #1994.

**Comment by sv-ohorvath** [comment] 2019-05-15 12:30
Verified as fixed on the 5/14 build.

**Closed** 2020-08-11 13:19 UTC
Labels: Feature:HomeScreen, Feature:Tabs, P1, eng:qa:verified, 🐞 bug
