### ISSUE TITLE
[Bug] Fenix does not recognize some sites as PWA, even though Fennec does

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#13791] opened 2020-08-13 09:32 UTC
## Steps to reproduce
1. In Fennec, go to theguardian.com or the Mozilla support page for example. (probably more, I'll investigate and create a larger list if needed)
2. Install them as PWA.
3. Migrate to Fenix.
4. Open the 2 PWAs installed.
5. Go to the same websites in Fenix, check if you can install them as PWA.
### Expected behavior
Fenix opens the 2 PWAs without a toolbar. 
Can install the 2 websites as PWAs.
### Actual behavior
These 2 PWA's open as standalone apps after the migration but they show a custom tab toolbar.
Opened in Fenix, these two websites don't have the Install option.
### Device information

* Android device: Pixel 4 (Android 10), HTC Desire 820 (Android 6.0.1)
* Fenix version: 79.0.4 RC

**Comment by ebalazs-sv** [comment] 2020-08-13 14:02
This issue is also reproducible on the previous build 79.0.3 GV 79, from 8/10 with Pixel 2 (Android 9).

**Comment by mcarare** [comment] 2020-09-22 11:11
This happens because theguardian.com has `BROWSER` as display option in manifest. In Fenix we do not install as PWA websites that will look the same as a normal browser window. IMO Fenix has the correct approach, as compared to Fennec.

**Comment by kbrosnan** [comment] 2021-05-19 17:56
What Mihai says makes sense to me. Lets close this and if it comes up from users we can discuss again.

**Closed by kbrosnan** 2021-05-19 17:56 UTC
Labels: Feature:PWA, S2, 🐞 bug
