### ISSUE TITLE
Crash in [@ java.lang.RuntimeException: at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java)]

### ISSUE THREAD

**Issue by JustAWhiteLily** [mozilla-mobile/fenix#15188] opened 2020-09-18 12:15 UTC
This one is ironic. Basically crashed for crashes...
## Steps to reproduce
1. Go to settings and tap on "About Firefox".
2. Tap on "Crashes".
### Expected behavior
Either crash reports of previous crashes are shown, or it shows "there are no crashes recently".
### Actual behavior
The screen goes blank (or black in Dark Mode). Then the browser crashes and shows the "Firefox has crashed" dialog.
Since the log cannot be viewed on the device due to this bug, I used adb logcat to get the information and post it in this [Gist.](https://gist.github.com/JustAWhiteLily/0094ccfa0f208972b7df0e0361667f33)
### Device information

* Android device: Honor Tablet 5 (AGS2-AL00HN). Android 9. EMUI 9.1.0
* Fenix version: 80.1.3, the latest version on Google Play

P.S. A user on Reddit mentioned a similar problem, but I have no idea of the device information in that case.

**Comment by kbrosnan** [comment] 2020-09-18 16:44
https://sentry.prod.mozaws.net/operations/firefox/issues/9266341/events/52105638/
https://sentry.prod.mozaws.net/operations/firefox/issues/9266341/events/52105638/

```
09-18 19:38:42.939 W/CursorWindow(15425): Window is full: requested allocation 10203296 bytes, free space 2096659 bytes, window size 2097152 bytes
09-18 19:38:42.953 E/SQLiteQuery(15425): exception: Row too big to fit into CursorWindow requiredPos=0, totalRows=68; query: SELECT * FROM crashes ORDER BY created_at DESC
09-18 19:38:42.965 W/mozilla.firefo(15425): Accessing hidden method Lcom/msic/qarth/PatchStore;->createDisableExceptionQarthFile(Ljava/lang/Throwable;)Z (blacklist, JNI)
09-18 19:38:42.965 E/mozilla.firefo(15425): [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
09-18 19:38:42.995 E/AndroidRuntime(15425): FATAL EXCEPTION: arch_disk_io_0
09-18 19:38:42.995 E/AndroidRuntime(15425): Process: org.mozilla.firefox, PID: 15425
09-18 19:38:42.995 E/AndroidRuntime(15425): java.lang.RuntimeException: Exception while computing database live data.
09-18 19:38:42.995 E/AndroidRuntime(15425):     at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:6)
09-18 19:38:42.995 E/AndroidRuntime(15425):     at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
09-18 19:38:42.995 E/AndroidRuntime(15425):     at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
09-18 19:38:42.995 E/AndroidRuntime(15425):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
09-18 19:38:42.995 E/AndroidRuntime(15425):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-18 19:38:42.995 E/AndroidRuntime(15425):     at java.lang.Thread.run(Thread.java:784)
09-18 19:38:42.995 E/AndroidRuntime(15425): Caused by: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=68
09-18 19:38:42.995 E/AndroidRuntime(15425):     at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
09-18 19:38:42.995 E/AndroidRuntime(15425):     at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:904)
09-18 19:38:42.995 E/AndroidRuntime(15425):     at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:851)
09-18 19:38:42.995 E/AndroidRuntime(15425):     at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
09-18 19:38:42.995 E/AndroidRuntime(15425):     at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:149)
09-18 19:38:42.995 E/AndroidRuntime(15425):     at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:137)
09-18 19:38:42.995 E/AndroidRuntime(15425):     at androidx.room.util.DBUtil.query(DBUtil.java:5)
09-18 19:38:42.995 E/AndroidRuntime(15425):     at mozilla.components.lib.crash.db.CrashDao_Impl$3.call(CrashDao_Impl.java:2)
09-18 19:38:42.995 E/AndroidRuntime(15425):     at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:5)
09-18 19:38:42.995 E/AndroidRuntime(15425):     ... 5 more
09-18 19:38:43.003 I/QarthDisFileCreator( 1211): pattern not match
09-18 19:38:43.009 E/ExceptionHandler(15425): Uncaught exception handled:
09-18 19:38:43.009 E/ExceptionHandler(15425): java.lang.RuntimeException: Exception while computing database live data.
09-18 19:38:43.009 E/ExceptionHandler(15425):   at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:6)
09-18 19:38:43.009 E/ExceptionHandler(15425):   at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
09-18 19:38:43.009 E/ExceptionHandler(15425):   at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
09-18 19:38:43.009 E/ExceptionHandler(15425):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
09-18 19:38:43.009 E/ExceptionHandler(15425):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-18 19:38:43.009 E/ExceptionHandler(15425):   at java.lang.Thread.run(Thread.java:784)
09-18 19:38:43.009 E/ExceptionHandler(15425): Caused by: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=68
09-18 19:38:43.009 E/ExceptionHandler(15425):   at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
09-18 19:38:43.009 E/ExceptionHandler(15425):   at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:904)
09-18 19:38:43.009 E/ExceptionHandler(15425):   at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:851)
09-18 19:38:43.009 E/ExceptionHandler(15425):   at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
09-18 19:38:43.009 E/ExceptionHandler(15425):   at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:149)
09-18 19:38:43.009 E/ExceptionHandler(15425):   at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:137)
09-18 19:38:43.009 E/ExceptionHandler(15425):   at androidx.room.util.DBUtil.query(DBUtil.java:5)
09-18 19:38:43.009 E/ExceptionHandler(15425):   at mozilla.components.lib.crash.db.CrashDao_Impl$3.call(CrashDao_Impl.java:2)
09-18 19:38:43.009 E/ExceptionHandler(15425):   at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:5)
09-18 19:38:43.009 E/ExceptionHandler(15425):   ... 5 more
```

**Comment by rocketsroger** [comment] 2020-10-08 14:26
Both the cause and recovery are fixed.  Closing.

**Closed by rocketsroger** 2020-10-08 14:26 UTC
Labels: Feature:CrashReporting, b:crash, needs:ac, 🐞 bug
