### ISSUE TITLE
[Bug] Scrolling on a trackpad always selects text

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#3708] opened 2019-06-27 14:56 UTC
## Steps to reproduce
On a Chromebook, scroll in the `BrowserFragment` using two fingers on the trackpad

### Expected behavior
The page should scroll up and down.

### Actual behavior
Text gets selected on the page in the opposite direction of the scrolling, starting from where the cursor is located.

What seems to happen is that when two fingers are on the trackpad, Fenix assumes one is pressing down and the second finger starts selecting text.

This doesn't happen in Focus so I don't think it's a GeckoView issue.

### Device information

* Android device: Pixelbook
* Fenix version: 1.0.0

**Comment by cpeterso** [comment] 2019-07-26 06:25
> This doesn't happen in Focus so I don't think it's a GeckoView issue.

>  kbrosnan added the `needs:gv` label

@kbrosnan - Why does this bug have the `needs:gv` label? Tiger said it is not reproducible in Focus with GV.

@NotWoods - Can you reproduce this bug in R-B?

**Comment by NotWoods** [comment] 2019-07-26 12:26
@cpeterso Please ignore past me because I was able to reproduce this in Focus after turning on GeckoView. I think it used WebView in my original testing. I can reproduce with Reference Browser as well.

**Comment by cpeterso** [comment] 2019-07-26 22:21
Looks like you already filed a GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1561927

That bug is currently a low-priority P3 because we assume running Fenix on a Chromebook is an uncommon use case. If that's not the case, please let me know! :)

**Comment by bifleming** [comment] 2019-09-10 21:49
@vesta0 can we close this one?

**Comment by vesta0** [comment] 2019-09-10 22:18
We should keep it open as a lower priority bug.

**Comment by yoasif** [comment] 2020-05-18 04:02
Some users are interested in this: https://www.reddit.com/r/firefox/comments/glqpaq/touchpad_scrolling_on_a_chromebook_highlights_text/

**Comment by Bogged** [comment] 2020-08-28 20:48
Issue is back with v75 :-(

**Comment by temporary0211** [comment] 2020-11-12 19:42
Firefox is basically unusable on ChromeOs with this bug. Since ChromeOS is the fastest growing OS platform it is hard to understand why this would be considered "low priority"

**Comment by dave2492** [comment] 2020-11-17 16:49
Yes, you can scroll with the arrow keys or with the touchscreen (if you HAVE one!).  But the two finger scroll via the trackpad still doesn't work!
Tested with Firefox 'Daylight' 82.1.3 on Pixelbook and Acer CB5-571.

**Comment by temporary0211** [comment] 2020-11-18 00:12
And tap to select also still doesn't work on ChromeOs.  For me, the dream of one browser across all platforms is dead for Firefox since I... like many others... use ChromeOs as one of my everyday platforms. Since Firefox not only has let this bug linger for years but also has failed to even consider it a high priority I see no alternative but to infer that Firefox is no longer interested in being available on all key platforms. And for me I've given up on trying to make Firefox work and moved on.

**Comment by dave2492** [comment] 2020-11-18 13:51
The comment above (in 2019) that Chromebooks are considered low priority is no longer a viable argument. Chromebooks are way popular and growing.  Also users are tiring of Google filling all our web pages with ads with products based on some earlier search that we made.  So Firefox could make some inroads here.  Instead we turn to Duck Duck Go and Brave and maybe Tor as alternatives.  Take your head out of the sand.

**Comment by temporary0211** [comment] 2020-11-30 18:30
And tap to click also still doesn't work on ChromeOs.  For me, the dream of one browser across all platforms is dead for Firefox since I... like many others... use ChromeOs as one of my everyday platforms. Since Firefox not only has let this bug linger for years but also has failed to even consider it a high priority I see no alternative but to infer that Firefox is no longer interested in being available on all key platforms. And for me I've given up on trying to make Firefox work and moved on.

**Comment by gordlonious** [comment] 2020-12-09 04:41
I just picked up a Chromebook and would be very interested in seeing this fixed! Scrolling is pretty basic. Loving Firefox on all my other devices.

**Comment by LittleAngelwings** [comment] 2021-01-21 14:34
And one more with a Chromebook. For me I missing also the rightclick, also the reload-button of a Chromebook isn't availible in Fenix. Using the new Chromebook Lenovo IdeaPad Flex 5 (i5, 8GB RAM, 12 GB SSD).

**Comment by dchee2** [comment] 2021-01-22 01:31
It's been almost 2 years. I guess it's safe to say that Firefox really don't give a shit anymore about the product. Even on other platforms, Firefox usability has started to go down the drain and exhibiting many weird quirks. Time to switch browsers yet again till Firefox pulls head out of ass again in the future. It's a vicious cycle.

**Comment by DiesL-aughing** [comment] 2021-02-28 02:28
I thought my Chromebook was broken. Is this not an issue in Debian? Because I wouldn't need much incentive to switch.

**Comment by LittleAngelwings** [comment] 2021-02-28 08:50
I think not, that is an issue with debian, Firefox at Linux (Beta) works with touchpad and scrolling. Other apps at android will work also with touchpad. It's only a thing of programing.

**Comment by LittleAngelwings** [comment] 2021-02-28 08:55
I mean that chromebooks are growing up, not only for schooling and buissness. So Mozilla could lose touch in this mobile field, if they don't react.

**Comment by kbrosnan** [comment] 2021-04-07 17:45
This should be fixed by Gecko with bz-1561927. The fix will be in Fenix when the Geckoview version is 89.0a1-20210408... or larger.

**Closed by kbrosnan** 2021-04-07 17:45 UTC
Labels: P3, needs:gv, 🐞 bug, 🙅 waiting

**Comment by gaul** [comment] 2021-04-08 10:19
I can confirm that this is fixed in Nightly 210407 17:03 (Build #2015803275).  Thanks @makotokato!

**Comment by LittleAngelwings** [comment] 2021-04-10 20:31
Can also confirm, that this issue was fixed for me on my chromebook.

**Comment by dchee2** [comment] 2021-04-12 06:46
Got an email that this is fixed so I installed FF Nightly to test it out. Yes, the scrolling no longer select text, so the problem is resolved but it exposed an underlying issue. 
Scroll with 2 fingers on touch pad until the pointer end up resting on a link. 
Remove both fingers.
Then use a single finger on the touch pad to move the pointer a little but leave it pointing at a link when you lift your finger. 
The result is as if you have long pressed the link.
Expectation is that the pointer simply is on the link but no clicking has occurred.

**Comment by makotokato** [comment] 2021-04-14 03:51
@dchee2
Please file new issue.

**Comment by slootsky** [comment] 2021-05-15 02:38
bug is back in build# 2015808511
