### ISSUE TITLE
[Bug]: Keyboard stays open when opening a new tab

### ISSUE THREAD

**Issue by aroskuski** [mozilla-mobile/fenix#22205] opened 2021-10-28 15:45 UTC
### Steps to reproduce

1. Have at least one tab open and focused
2. Open the tab drawer and tap the plus
3. Without dismissing the keyboard, tap on one of the visible top sites links to navigate to a page

### Expected behaviour

The browser navigates to the link and dismisses the keyboard

### Actual behaviour

The browser navigates to the link and the keyboard stays open until explicitly dismissed

### Device name

Google Pixel 3

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

93.2.0

### Additional information

Not 100% sure, but I think the issue started happening after upgrading to Android 12.

I can't reproduce the issue on my Pixel 1 running Android 10.

I also reproduced the issue on the following Nightly build:
95.0a1 (Build #2015842347)
AC: 95.0.20211027143128, 04bd14f2a3
GV: 95.0a1-20211027093708
AS: 86.0.0

**Comment by amedyne** [comment] 2021-11-01 16:52
I am not able to reproduce this on a Pixel 3 running Android 11.
Looks like and Android 12 issue.

**Comment by swattor** [comment] 2021-11-06 13:25
Happening regularly to me on a pixel 3a with android 12. It seems to happen in other circumstances too but haven't quite charactised them.

**Comment by DireLogomachist** [comment] 2021-11-07 21:52
I'm seeing this bug as well. On a Pixel 5 and it appeared immediately after updating to Android 12.

Pretty annoying as closing the keyboard seems to take two actions now as well. Swiping down to dismiss now only dismisses the top keyboard bar, but the main keyboard stays up too.

**Comment by tomgeor** [comment] 2021-11-08 15:48
I see this too.  Click the address bar, choose a bookmark, and the keyboard stays open. Pixel 3a Android 12 and FF 94.1.1

**Closed** 2021-11-18 07:57 UTC
Labels: 🐞 bug, Android:12

**Comment by SoftVision-LorandJanos** [comment] 2022-04-01 07:36
Tested on an older build (eg. 94.1.2RC) where I could reproduce the issue with an Android 12 device (Oppo Reno 6).
Verified as fixed on the latest Nightly 100.0a1 (2022-04-01) build.
Device used: Oppo Reno 6 (Android 12).
