### ISSUE TITLE
[Bug] The search bar is stuck in the center of the screen 

### ISSUE THREAD

**Issue by abaddon-99** [mozilla-mobile/fenix#19718] opened 2021-05-30 10:19 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

![Screenshot_20210530-130238392~2](https://user-images.githubusercontent.com/49745766/120100144-d11b5400-c147-11eb-85e2-5e2c5f76e883.jpg)
![Screenshot_20210530-130247618](https://user-images.githubusercontent.com/49745766/120100145-d1b3ea80-c147-11eb-96d6-c145012665e9.jpg)
## Steps to reproduce
1. Activate the search box(The search bar is at the bottom).
2. Hide on-screen keyboard.
3. Quickly repeat these steps until the bug is displayed
### Expected behavior
The search bar should return to its place at the bottom of the screen
### Actual behavior
The search bar remains in the center of the screen and covers the web pages
### Device information

* Device vendor / model and Android version: Xiaomi Mi A2, Android 10
* Firefox for Android version: 89.0.0-beta.10 (Build #2015812163)

**Comment by LaurentiuApahideanSV** [comment] 2021-05-31 09:06
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/19376. I will mark this issues as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-05-31 09:06 UTC
Labels: needs:triage, 🐞 bug
