### ISSUE TITLE
[Bug] Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#4652] opened 2019-08-09 14:19 UTC
BrowserFragment is occasionally throwing an `IllegalStateException` when asking for a view model.

From Sentry:
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6128076/

**Comment by csadilek** [comment] 2019-08-09 15:02
@colintheshots found an upstream issue: https://issuetracker.google.com/issues/139093676

**Comment by csadilek** [comment] 2019-08-12 14:20
This is also happening for the HomeFragment: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6128579/

**Comment by ekager** [comment] 2019-08-14 20:28
Should we close this issue now? Or are we waiting to monitor Sentry for resolved crashes?

**Comment by cadeyrn** [comment] 2019-08-19 20:41
I sometimes still get "Can not perform this action after onSaveInstanceState". Both times I got this crash (a few days ago and a few minutes ago) it was immediately after compiling a new build. But I can't reproduce a second time in a row, so I don't have STR, unfortunately.

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.savedstate.SavedStateRegistry.runOnNextRecreation(SavedStateRegistry.java:168)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:71)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:177)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:145)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at org.mozilla.fenix.home.HomeFragment.restoreLayoutState(HomeFragment.kt:211)
        at org.mozilla.fenix.home.HomeFragment.access$restoreLayoutState(HomeFragment.kt:90)
        at org.mozilla.fenix.home.HomeFragment$preDrawListener$1$onPreDraw$1.invokeSuspend(HomeFragment.kt:121)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.ResumeModeKt.resumeMode(ResumeMode.kt:67)
        at kotlinx.coroutines.DispatchedKt.resume(Dispatched.kt:309)
        at kotlinx.coroutines.DispatchedKt.dispatch(Dispatched.kt:298)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:250)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:260)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:332)
        at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:210)
        at android.app.ActivityThread.main(ActivityThread.java:7124)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
```

The latest crash was with the latest code from master branch (revision 73e3db8fe01309a647a43fe784d026cc17c9d297).

**Comment by ekager** [comment] 2019-08-19 20:42
@colintheshots do you have any ideas regarding the above log?

**Comment by boek** [comment] 2019-08-22 23:41
Going to close this as it doesn't seem to be an issue in Sentry anymore. If it's still a problem in 1.3.1 we can re-open

**Closed by boek** 2019-08-22 23:41 UTC
Labels: b:crash, 🐞 bug

**Comment by ekager** [comment] 2020-06-22 22:14
The underlying issue was marked as fixed in January https://issuetracker.google.com/issues/139093676 
Maybe we can remove the workarounds now?
