### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DarKLter** [mozilla-mobile/fenix#25286] opened 2022-05-18 16:16 UTC
I downloaded a large file but failed when it reached 3g and went back to the beginning and also ate a large ram my phone is so lag and I hope you also put where you want to put the downloaded file such as the setting where the folder you want to put

**Comment by kbrosnan** [comment] 2022-05-18 17:00
Sounds like a duplicate of https://github.com/mozilla-mobile/fenix/issues/5764

**Closed by kbrosnan** 2022-05-18 17:00 UTC
Labels: needs:triage
