### ISSUE TITLE
[Bug]: The microphone icon is not updated on the search bar widget

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21134] opened 2021-09-03 09:39 UTC
### Steps to reproduce

1. Install Fenix and add the search widget to the device home screen.
2. Open Fenix Settings > Search.
3. Disable and re-enable the "Show voice search" toggle.
4. Observe the widget is now missing the microphone icon.

### Expected behaviour

The widget displays a microphone icon on the widget when the toggle is enabled in the app settings.

### Actual behaviour

The microphone icon is not displayed until restarting the device or reinstalling the widget.

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

92.1.0 2021-09-01

### Additional information

Same behavior can be observed on Nightly 2021-09-03.

**Comment by SoftVision-LorandJanos** [comment] 2021-09-21 10:31
I can confirm the issue is reproducible with the following observations:
On all 3 devices used for testing, on Beta the behavior is exactly as described, but with the latest Nightly, while the microphone icon is not displayed as described above, it reappears after a few seconds without restarting, or reinstalling the widget. (See video below).
@mariansima please see if it is the same on your side with the latest Nightly.

Firefox versions tested:
- latest Nightly (94.0a1 - 2021-09-21)
- latest Beta (93.0.0beta4)

Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Mi11 Lite (Android 11).

https://user-images.githubusercontent.com/48829350/134155655-0187663e-891c-4d01-a64f-431f08547c63.mp4

**Comment by mariansima** [comment] 2021-09-23 07:59
After further testing on Nightly 94.0.a1 2021-09-22, the icon does update after a few seconds when the specified browser is set as default. If another browser is set as default, the icon will no longer update after toggling the "Show voice search" button. Video attached.
![242725825_258682129474865_7879339080239705376_n](https://user-images.githubusercontent.com/89511597/134469651-345d32f0-ac16-4f4c-8520-cc1bfba12ca2.gif)
.

**Comment by SoftVision-LorandJanos** [comment] 2022-03-22 15:09
This issue is no longer reproducible with the latest Nightly build (100.0a1 - 2022-03-21).
Device used: Oppo Reno 6 (Android 11).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-03-22 15:09 UTC
Labels: 🐞 bug, S3, feature:SearchWidget, needs:triage, wontfix, qa-triaged
