### ISSUE TITLE
[Bug] Crash when entering form in https://www.vhs-wissen-live.de/vortrag/afrikas-kampf-um-seine-kunst.html

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#19531] opened 2021-05-17 13:26 UTC
## Steps to reproduce
Firefox Nightly has been crashing randomly A LOT lately (for a few days), but here seems to be a repeatable crash :
Go to https://www.vhs-wissen-live.de/vortrag/afrikas-kampf-um-seine-kunst.html
Enter the Vorname field in form and type in

### Expected behavior
text should appear in form

### Actual behavior
Firefox crashes

### Device information

* Device vendor / model and Android version: Xiamo Redmi Note 7
* Firefox for Android version: ? (go to Settings -> About Firefox)  Build #2015810763

**Comment by sflorean** [comment] 2021-05-17 13:32
Thank you for filing this issue! This is a duplicate of #19508, your scenario will be covered when a fix is available.

**Closed by sflorean** 2021-05-17 13:32 UTC
Labels: needs:triage, 🐞 bug
