### ISSUE TITLE
[Bug]: TWITCH site doesn't plays videos (on Mobile data)

### ISSUE THREAD

**Issue by vivazkote** [mozilla-mobile/fenix#20767] opened 2021-08-09 21:32 UTC
### Steps to reproduce

as title says.
Go to /m.twitch.tv and try to play live stream. Video does not starts.
tested site in Opera browser, video plays.
{update} : this happens on Mobile data, on WiFi videos plays.

### Expected behaviour

Video should play.

### Actual behaviour

Video stream doesn't play.

### Device name

LG V35

### Android version

Android 8

### Firefox release type

Firefox

### Firefox version

90.1.3 (Build #2015824995)

**Comment by kbrosnan** [comment] 2021-08-09 22:41
Works for me using 90.1.3 on a Pixel 2 XL, Samsung Galaxy S6 and a Mi 4 LTE

**Comment by Nojuuu** [comment] 2021-08-10 01:27
I have same issue:
https://github.com/webcompat/web-bugs/issues/77533

**Comment by vivazkote** [comment] 2021-08-10 06:14
problem more clarified:
Issue happens on Mobile data. on WiFi video plays. (data saver is off)

**Comment by Nojuuu** [comment] 2021-08-10 14:01
I also tried it on WiFi and it seems to work, but not on mobile data.

**Comment by SoftVision-LorandJanos** [comment] 2021-08-10 15:04
Hi @vivazkote ! Than you for your report! 
I tried to reproduce the issue you described before you wrote the comment about it only reproducing with mobile data.
I didn't reproduce the issue with WiFi.
Later, considering the extra info, I tried with mobile data on a personal device and managed to reproduce it. All this with the latest Release (91.1.0).
Devices used:
- Google Pixel 4 (Android 11).
- Samsung Galaxy Tab S3 (Android 9).
- LG Nexus 5 (Android 6.0.1).
- Huawei P30 (Android 10) - where I reproduced the issue using mobile data.

**Comment by amedyne** [comment] 2021-08-13 21:02
Closing this to track this issue thru https://github.com/webcompat/web-bugs/issues/81000

**Comment by Nojuuu** [comment] 2021-08-14 19:35
> 
> 
> Closing this to track this issue thru [webcompat/web-bugs#81000](https://github.com/webcompat/web-bugs/issues/81000)

That one is closed too.

**Comment by amedyne** [comment] 2021-08-16 20:43
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1726036

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by amedyne** 2021-08-16 20:43 UTC
Labels: 🐞 bug, Feature:Media, S3, qa-triaged
