### ISSUE TITLE
[Bug] Tapping the Telephone link from daleharvey.github.io/testapp/ opens the Color chooser

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#10595] opened 2020-05-12 14:07 UTC
## Steps to reproduce
1. Launch Fenix Nightly;
1. Go to https://daleharvey.github.io/testapp/;
1. Scroll to the bottom of the page and tap the Telephone link;
    1. Expected behavior
It opens the phone app with the linked number pre-filled.
    1. Actual behavior
The Color chooser is displayed and the color can be changed.
    1. Notes
This is also reproducible in custom tab.
Not reproducible if the page is opened as a PWA.

![20200512](https://user-images.githubusercontent.com/48799384/81701643-fc66ce80-9472-11ea-98ea-e698ff6f423d.gif)UNITO-UNDERSCORE!170505!

### Device information
* Android device: Motorola Moto G6 (Android 8)
* Fenix version: Fenix Nightly 200512 (Build #21330603) GV 78

**Comment by ValentinTimisica** [comment] 2020-05-14 09:04
Note that it is not reproducible on Firefox Preview from store.

Seems like is not a problem in GV because it recognizes correctly the telephone link as you can see in the screenshot below.

<img width="1041" alt="Screen Shot 2020-05-14 at 10 36 08 AM" src="https://user-images.githubusercontent.com/52956363/81911846-81b6c400-95d6-11ea-8790-422c5d1ffb8c.png">

For me, when I press `Telephone link` it will open youtube (`Link to youtube, make sure it plays`)

[Video with bottom toolbar](https://drive.google.com/file/d/1z60Lv4CSC_YeqEDlVqTqpESgV61eS8NB/view?usp=sharing)
[Video with top toolbar](https://drive.google.com/file/d/1PpXakqGLFQS_wGel9qkMpr6v-2124uAo/view?usp=sharing)

**Comment by Amejia481** [comment] 2020-05-19 19:16
I was trying to simulated the issue, but for me in master is working as expected below details of my build. 
```
1.0.2021 (Build #1)
42.0.20200518130035, f0cb2cca9
GV: 78.0a1-20200517094345
AS: 0.58.2 3:09
Tuesday 5/19 @ 11:57 AM
```

The only issue that I encountered was  I can't clicked links at the bottom of the page just like this  bug describes https://github.com/mozilla-mobile/fenix/issues/10578#issuecomment-628711075, if I move the link using `about:debugging`  to the top of the page it works. Let's see if QA can help us to reproduce the issue.

**Comment by abodea** [comment] 2020-05-21 09:14
Note that I re-checked this issue on the latest **Nightly 5/21** with **Google Pixel 4 XL (10).**
The telephone link now redirects to the google home page. 
Note that on Chrome, I was correctly redirected.
I will remote the qa needed until further notice.

**Comment by Amejia481** [comment] 2020-05-21 15:55
> Note that I re-checked this issue on the latest **Nightly 5/21** with **Google Pixel 4 XL (10).**
> The telephone link now redirects to the google home page.
> Note that on Chrome, I was correctly redirected.
> I will remote the qa needed until further notice.
> 
> ![20200521-121307](https://user-images.githubusercontent.com/42831109/82543812-ca352b00-9b5c-11ea-9dcc-e69e08343b0a.gif)

@abodea in the video it looks like you clicked the **"External link"** by mistake, the telephone link didn't get highlighted.

To avoid issue https://github.com/mozilla-mobile/fenix/issues/10578#issuecomment-628711075,
let's use another page that doesn't have the link at the bottom of the page you can use https://davidwalsh.name/demo/phone-link-protocol.php and click the **Call Jenny!** link.

**Comment by Diana-Rus** [comment] 2020-05-22 09:45
Hi, the issue still reproduces with Samsung Galaxy S9 (Android 8) and Google Pixel 3 Xl (Android 9) when tapping on the "Telephone link" from page https://daleharvey.github.io/testapp/  .
It can be seen that the tap is present on "Telephone" link, and no link is highlighted also it depends on the device:

**GIF - Samsung Galaxy S9 (Android 8) - Access the External app same origin**
![20200522-122342](https://user-images.githubusercontent.com/49859863/82654520-8bb97200-9c29-11ea-9e8f-6b5680664aa6.gif)

**GIF - Google Pixel 3 XL (Android 9) - Access Google homepage**
![20200522-122711](https://user-images.githubusercontent.com/49859863/82654535-8f4cf900-9c29-11ea-9ba1-4f864e0d4ad2.gif)

This issue and the other one mentioned by you https://github.com/mozilla-mobile/fenix/issues/10578#issuecomment-628711075 seem to be the same issue.  I'll remove the qa-needed until further notice.

**Comment by Amejia481** [comment] 2020-05-25 14:15
Is the issue still reproducible with this link https://davidwalsh.name/demo/phone-link-protocol.php?  Click **the Call Jenny!** link.

I tested on Google Pixel 3 using the link above.
Video https://drive.google.com/file/d/1U2cMn8JKQVDFJ-fhzhDoTkGsHUwAQQdL/view?usp=sharing

**Comment by softvision-miralobontiu** [comment] 2020-05-26 11:53
Hi all,
I've retested this on https://daleharvey.github.io/testapp/ on the 5/26 Nightly build.

With Google Pixel, tapping on the telephone link does nothing - please see the GIF below:
<img src="https://user-images.githubusercontent.com/40694158/82897371-34d0d700-9f60-11ea-91e2-d51555e575c8.gif" width="300" height="550" />

With Sony Xperia Z5 Premium (Android 7.1.1), tapping on the telephone link redirects the user to the calendar page - please see the GIF below:
<img src="https://user-images.githubusercontent.com/40694158/82897382-39958b00-9f60-11ea-99fa-2ff729730a47.gif" width="300" height="550" />

However, with the link https://davidwalsh.name/demo/phone-link-protocol.php, tapping on the Call Jenny! link worked as expected with both devices.
I'll remove the qa:needed label for now.

**Comment by Amejia481** [comment] 2020-05-26 14:15
> Hi all,
> I've retested this on https://daleharvey.github.io/testapp/ on the 5/26 Nightly build.
> 
> With Google Pixel, tapping on the telephone link does nothing - please see the GIF below:
> <img alt="" width="300" height="550" src="https://user-images.githubusercontent.com/40694158/82897371-34d0d700-9f60-11ea-91e2-d51555e575c8.gif">
> 
> With Sony Xperia Z5 Premium (Android 7.1.1), tapping on the telephone link redirects the user to the calendar page - please see the GIF below:
> <img alt="" width="300" height="550" src="https://user-images.githubusercontent.com/40694158/82897382-39958b00-9f60-11ea-99fa-2ff729730a47.gif">
> 
> However, with the link https://davidwalsh.name/demo/phone-link-protocol.php, tapping on the Call Jenny! link worked as expected with both devices.
> I'll remove the qa:needed label for now.

@softvision-miralobontiu the issue that you are seeing is related to https://github.com/mozilla-mobile/fenix/issues/10578#issuecomment-628711075 that is a separated bug. I think we can close this issue as telephone links are working as expected.  In https://daleharvey.github.io/testapp/  the telephone link is not working as we are suffering from https://github.com/mozilla-mobile/fenix/issues/10578#issuecomment-628711075, if the link is moved on the top or the middle of the page the link works. Please feel free to re-open otherwise :)

**Comment by ebalazs-sv** [comment] 2020-06-05 06:29
This is still reproducible on Fenix Nightly Build 21560608 GV 79.0a1-20200602093554 from 6/4 with Motorola Moto G6 (Android 8).
The bug https://github.com/mozilla-mobile/fenix/issues/10578#issuecomment-628711075 that was mentioned previously that is related with this issue is fixed, due to that I will reopen this bug.
Thanks!

**Closed** 2021-03-04 01:14 UTC
Labels: E3, Feature:Forms, Feature:OpenInApp, S2, needs:ac, wontfix, 🐞 bug
