### ISSUE TITLE
Intermittent test failure with InactiveTabsControllerTest

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#22582] opened 2021-11-24 18:35 UTC
> SUITE: org.mozilla.fenix.tabstray.browser.InactiveTabsControllerTest
  TEST: WHEN expanded THEN notify filtered card
  FAILURE

java.lang.AssertionError: Verification failed: call 1 of 1: TabsTray(#729).updateTabs(slotCapture<List>(), any())) was not called
	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalVerify(API.kt:118)
	at io.mockk.MockKKt.verify(MockK.kt:149)
	at io.mockk.MockKKt.verify$default(MockK.kt:146)
	at org.mozilla.fenix.tabstray.browser.InactiveTabsControllerTest.WHEN expanded THEN notify filtered card(InactiveTabsControllerTest.kt:50)

**Comment by jonalmeida** [comment] 2021-11-24 18:36
Duplicate of https://github.com/mozilla-mobile/fenix/issues/22488

**Closed by jonalmeida** 2021-11-24 18:36 UTC
