### ISSUE TITLE
[Bug]There's no notification when i send page from pc to android

### ISSUE THREAD

**Issue by xivaphro** [mozilla-mobile/fenix#15218] opened 2020-09-19 12:19 UTC
### Expected behavior
after sending the tab notification should appear
### Actual behavior
no notification until i sync opened tabs manually
### Device information

* Android device: android 7
* Fenix version: nightly 200919

**Comment by hinzed1127** [comment] 2020-10-30 19:52
I see this same bug in Firefox Nightly, 201027 on Android 11. 

In recreating this, I noticed that in Firefox Daylight, v 82.1.1, when I have the browser presently open on my device, send tab to device elicits a push notification without manual sync. Otherwise, both versions of firefox mobile require manual sync to successfully receive tabs.

**Comment by 5trongthany** [comment] 2020-11-19 19:42
Can report I have the same bug. 

Firefox Nightly 201118 17:04 build #2015776395 on Android 10, build number 8901.A.0054.20200929

**Comment by jonalmeida** [comment] 2020-12-02 20:24
Closing this as a duplicate of https://github.com/mozilla-mobile/fenix/issues/16721 which we're using to track this failure.

**Closed by jonalmeida** 2020-12-02 20:24 UTC
Labels: Feature:SendTab, 🐞 bug
