### ISSUE TITLE
[Bug] Typing an email to sign into Firefox Sync removes what you typed

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19704] opened 2021-05-28 16:28 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to Settings > Turn on Sync
2. Start typing an email address until you reach the `@`: "example@"
3. Observe when typing the email hosting: "example@hosting.com"

### Expected behavior
- You can type your full email address.

### Actual behavior
1. When pressing "h", for the example above, the current text is highlighted and removed.

### Device information

* Device vendor / model and Android version: Android 11, Pixel 3
* Firefox for Android version: Firefox Nightly (27/05)

https://user-images.githubusercontent.com/1370580/120014516-2a507f80-bfb0-11eb-8622-dd643c8bc5cd.mp4

**Comment by jonalmeida** [comment] 2021-05-28 16:38
I can reproduce this bug without a custom tab (navigating to accounts.firefox.com) in Nightly and Reference Browser.

I cannot reproduce this on:
 - Chrome Canary (93) with/without Custom Tabs.
 - DuckDuckGo with/without Custom Tabs.
 - Focus (8.15.4 with GV 88) 
 - Focus (`main` branch with GV 90)

**Comment by kbrosnan** [comment] 2021-05-28 16:44
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1713354

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jonalmeida** [comment] 2021-05-28 17:01
I don't believe this is a GV bug, I can't reproduce the bug on the two Focus builds one with GV stable and the other is with GV nightly with AC engine.

I'm guessing it's something related to multiple feature integration in component-based browsers.

**Comment by makotokato** [comment] 2021-05-31 08:41
What version of Gboard? I cannot reproduce this on Gboard version 10.5.03.367007960-release-arm64-v8a (update at 2021/04/28).

**Comment by jonalmeida** [comment] 2021-06-01 15:47
@makotokato I'm using version 10.6.03.371892758-beta-arm64-v8a (beta program).

There have been others that have also seen this issue that may have different devices/keyboards. 

cc: @grigoryk @jdragojevic @mhammond 

Here is another quirk with the text field when trying to use the backspace button after moving the cursor to a new location:

https://user-images.githubusercontent.com/1370580/120352573-e4a4f700-c2ce-11eb-8c27-e6b55ff117cd.mp4

**Comment by makotokato** [comment] 2021-06-01 17:02
@jonalmeida Thanks, but I cannot still reproduce first issue...

> Here is another quirk with the text field when trying to use the backspace button after moving the cursor to a new location:

I believe that https://treeherder.mozilla.org/jobs?repo=try&revision=b79f4eca3d3a7a3325004706327dcae8cc2416a5 has this fix.

Could you test this GVE build (https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/fxSqjQx9RLmsa9X48NcXlA/runs/0/artifacts/public/build/geckoview_example.apk) whether this 1st issue still occurs?

**Comment by makotokato** [comment] 2021-06-07 11:19
I guess that this won't occurs on current FxA account site due to https://github.com/mozilla/fxa/pull/8719.

Also, I have landed https://bugzilla.mozilla.org/show_bug.cgi?id=1713354 to fix this.

**Comment by jonalmeida** [comment] 2021-06-08 15:16
Yeah, this isn't reproducible any more. I guess it was an FxA bug in the end.

**Comment by kbrosnan** [comment] 2021-06-08 21:33
Closing this as there are other changes that resolved this.

**Closed by kbrosnan** 2021-06-08 21:33 UTC
Labels: needs:triage, 🐞 bug
