### ISSUE TITLE
[Bug] Reduce the radius of the rounded corners

### ISSUE THREAD

**Issue by robmv** [mozilla-mobile/fenix#3715] opened 2019-06-27 17:44 UTC
## Steps to reproduce

Open any menu inside the application, the rounded corners of them are too big. Compare the following Chrome and Firefox Preview screenshots from the same device:

![Screenshot_20190627-132112](https://user-images.githubusercontent.com/1652983/60287871-fa3e6480-98e0-11e9-81ba-e0f9726c9741.png)
![Screenshot_20190627-132122](https://user-images.githubusercontent.com/1652983/60287877-ff031880-98e0-11e9-964f-7bd1c7b7ef21.png)

### Expected behavior

Relatively native looking controls, specially menus rounded corners within [Material Design recommendations](https://material.io/design/components/menus.html). There are too many rounded corners, not my personal taste, but the menu ones are too big.

### Actual behavior

Menu rounded corners are too big in comparison with other modern Android applications.

### Device information

* Android device: Nexus 5
* Fenix version: 1.0.0

**Comment by cadeyrn** [comment] 2019-06-27 18:29
I don't think it makes much sense to compare with Chrome because Chrome is Chrome and Fenix is Fenix. It's totally okay to have different designs. FWIW, I am not a big fan of Material design and I like the current border radius of the Fenix menu.

**Comment by robmv** [comment] 2019-06-27 19:28
Thanks for the reply. The comparison with Chrome was to show another application that uses rounded corners on Android, it is not frequent to see those menus yet.

The menu's rounded corner is too large for my taste, compare it with others non menu rounded corners on the same application.

For not being a fan of Material Design, the new UI is taking the most annoying visual aspect of it (the corners) and making it big, like children's toy like interfaces. I hope more feedback comes.

**Comment by yoasif** [comment] 2019-06-27 21:04
I agree that the current menus look a little sloppy, but didn't have a great reason to open a bug about it previously. I think that this makes sense from a platform integration perspective.

**Comment by mheubusch** [comment] 2019-07-02 20:36
@AmyYLee please review and close if border radii are as designed.

**Comment by AmyYLee** [comment] 2019-07-03 17:29
@sblatz Can you confirm if the boarder radius is 8pt? if it is, please leave it as such as this is the same radius as our tab cards. We should keep the radius consistent throughout the app. Thanks.

**Comment by ekager** [comment] 2019-07-03 17:40
The radius was not 8dp. Updating now

**Comment by ekager** [comment] 2019-07-03 18:14
Updated the menu corner radius, closing this

**Closed by ekager** 2019-07-03 18:14 UTC
Labels: 🐞 bug

**Comment by robmv** [comment] 2019-07-03 18:42
Thanks everyone involved, with this fixed, adding my next UI related issue
