### ISSUE TITLE
[Bug] Tab Queue No Longer Works

### ISSUE THREAD

**Issue by JMW882** [mozilla-mobile/fenix#14792] opened 2020-09-06 18:05 UTC
### What is the user problem or growth opportunity you want to see solved?

With the recent update in Android, the tab queue feature has gone missing. This important feature allowed users to click on links in the email and other apps, and then open all at once in separate tabs in Firefox when ready, instead of going back-and-forth piecemeal, item by item.

### How do you know that this problem exists today? Why is this important?

Worked previously. No longer working and cannot find option in Settings. This was an important feature for efficient workflow. I now cannot delete emails until after looking at links of interest.

### Who will benefit from it?

All users who are interested in a more efficient workflow. It was there before. Please fix. Thank you for considering.

**Comment by hwinnemoe** [comment] 2020-09-06 18:38
Duplicate of #1523

**Comment by ericrbg** [comment] 2020-09-08 10:44
sadly, yeah. there's been no discussion and no progress on #470 for a while though, so losing hope that it'll ever get added.

**Comment by meztesso** [comment] 2020-09-13 09:52
I hope that the feature will be avaible again. This is a very useful function and I already downgrade my ff betla only for this

**Comment by nunesgh** [comment] 2020-09-15 13:02
Also related to #1523.

I still cannot believe Mozilla released this new Firefox browser without feature parity with the previous version. We are now discussing "new" features (as #470 and #1523 are labeled) that were available on the previous version of Firefox. What a mess!

**Closed** 2020-09-16 23:24 UTC
Labels: needs:triage
