### ISSUE TITLE
[Bug] Error in Twitter Comments

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#7974] opened 2020-01-29 11:13 UTC
When you open the answer given to comments while using Twitter, the page goes to the top.

* Android device: ?

Lenovo k6 Note
* Fenix version: ?
Firefox Preview & Nightly OLD versiyon.

**Comment by reyis4402** [comment] 2020-01-29 11:15
> When you open the answer given to comments while using Twitter, the page goes to the top.
> 
>     * Android device: ?
> 
> 
> Lenovo k6 Note
> 
>     * Fenix version: ?
>       Firefox Preview & Nightly OLD versiyon.

**Comment by reyis4402** [comment] 2020-01-29 11:37
Error video

https://mobile.twitter.com/acikveozgur/status/1221156809702039552

**Comment by reyis4402** [comment] 2020-01-29 22:23
@NotWoods    Will there be a fix for the error?

**Comment by yoasif** [comment] 2020-02-02 23:54
Dupe of #6176

**Closed** 2020-02-04 00:05 UTC
Labels: needs:triage, 🐞 bug
