### ISSUE TITLE
FNX-12208 ⁃ Sharing menu lacks entries

### ISSUE THREAD

**Issue by gabrielambuehl** [mozilla-mobile/fenix#11300] opened 2020-06-06 14:58 UTC
For some reason the All actions part of the sharing menu shows only 12 actions thus sometimes preventing me from completing the sharing intention whereas other browsers properly show the 25 plus that are available on my phone....

**Comment by SS1113** [comment] 2020-06-06 15:52
Duplicate of #11177.

**Closed** 2020-08-11 03:42 UTC
Labels: needs:triage
