### ISSUE TITLE
[Bug]Add-On-Settings page is blank after tapping devices back button.

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#9274] opened 2020-03-20 13:09 UTC
## Steps to reproduce
1. Open app go to Menu/Settings/Add-ons.
2. Install U-block Origin by tapping on the "+".
3. Tap on "Settings" section.
4. Tap on the device's back button.

### Expected behavior
A redirection to U-block Origin is made.
### Actual behavior
The Settings page is blank.
### Device information

* Android device: Samsung Galaxy S9 (Android 8.0.0), Sony Xperia Z4 (Android 7)
* Fenix version: Firefox Preview Nightly 200320 (Build #20800605) GV: 76.0a1-20200318041411

Note:
- This can bring the app to a crash. I am going to provide a logcat and extra steps that produces the crash.
After step 4:
5. Tap back again.
6. Re-open app.
7. Go to Menu/Settings/Add-ons/ .
8. Disable uBlock.
9. Tap on "Details" and afterwards on "Permissions" .
10. Enable u-Block and tap on "Settings".

**Gif with issue and crash:**
![20200320-144603](https://user-images.githubusercontent.com/49859863/77166128-5c1cab00-6abc-11ea-96cc-91c953611479.gif)

**Logcat: **
[CrashAdd-ons.txt](https://github.com/mozilla-mobile/fenix/files/4359667/CrashAdd-ons.txt)

**Comment by csadilek** [comment] 2020-03-20 14:54
Dupe of https://github.com/mozilla-mobile/fenix/issues/9139. This is also reproducible in Fennec and needs to be addressed in the add-on directly. Closing here as we're relaying to the add-on developer.

**Closed by csadilek** 2020-03-20 14:54 UTC
Labels: Feature:WebExtensions, S2, needs:triage, 🐞 bug
