### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by johnthepepper** [mozilla-mobile/fenix#18606] opened 2021-03-23 16:48 UTC
I think bookmarks should be like file system (I'm sorry for google translate)

**Comment by kbrosnan** [comment] 2021-03-23 17:49
This is probably a request to export bookmarks. Which makes it a duplicate of https://github.com/mozilla-mobile/fenix/issues/417

**Closed by kbrosnan** 2021-03-23 17:49 UTC
Labels: needs:triage
