### ISSUE TITLE
Data saver when not on WiFi

### ISSUE THREAD

**Issue by NiLSPACE** [mozilla-mobile/fenix#810] opened 2019-03-02 20:54 UTC
### Why/User Benefit/User Problem

As a user I want Fenix to only load media when connected through WiFi 

### What / Requirements

Fennec currently has the option to only load media when the phone is connected through WiFi. This greatly reduces data usage when browsing using 4G. It would be great to have this option on Fenix as well.

### Acceptance Criteria (how do I know when I’m done?)

 - [ ] The option is configurable
 - [ ] Fenix uses a placeholder image for images that weren't loaded due to the data saver.
 - [ ] Add ability for the user to override the feature by pressing/holding the media element.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15505)

**Comment by madb1lly** [comment] 2020-06-23 22:30
Hi all,
This is a feature you don't realise how important it is until it's not there. We don't all have massive data allowances ( mine is 1GB) and this feature becomes even more critical when roaming.
Cheers 🙂

**Comment by B0pol** [comment] 2020-08-29 09:34
Title says when not on Wi-Fi but it should also be available on Wi-Fi, e.g. a preference could be show images: always / Wi-Fi only / never, because reducing data usage helps with low bandwith even on Wi-Fi

**Comment by s-ankur** [comment] 2020-08-29 11:42
@B0pol Although it would be nice to have as a browser feature, UBlock allows to disable all media elements if you need to

**Comment by madb1lly** [comment] 2020-08-31 09:48
Hi @s-ankur,

It's not a nice-to-have, from the perspective of most users it's a feature which has just been removed from Firefox for Android (was there before the upgrade and is now missing).

This issue should have the "Feature:Fennectransision" label added to it. 

Cheers 🙂

**Comment by W4RH4WK** [comment] 2020-08-31 10:53
@madb1lly I fully agree with you. I'd even label this as an *accessibility* feature.

**Comment by muenz** [comment] 2020-09-16 19:04
There was some pop-up in fenix asking for user feedback, also because of the many complaints.
The feature requested in this ticket is essential for me. It was one of the reasons for using Firefox on Android.
If it does not reappear very soon, I will switch to another browser that supports this.

**Comment by J0WI** [comment] 2020-10-05 22:12
Is there an `about:config` for this?  I'm only aware of [`permissions.default.image`](http://kb.mozillazine.org/Permissions.default.image).

**Comment by J0WI** [comment] 2021-01-06 14:30
> Is there an `about:config` for this? I'm only aware of [`permissions.default.image`](http://kb.mozillazine.org/Permissions.default.image).

short update: uBlock Origin can be configured to block large media elements, but it does not provide the "click-to-load" experience of Fennec and cannot distinguish free from paid networks.

**Comment by metronightly** [comment] 2021-01-29 11:07
While uBlock Origin does help to an extent, it's image blocker is not as powerful as the one that Firefox on Android had. 

The uBO setting sometimes doesn't work on some sites/pages and it doesn't work on auto play videos. This autoplay thing may/may not be a Firefox issue, because while the video doesn't 'autoplay', it certainly loads in entirety, meaning wastage of mobile data anyway.

Really hope the guys add this feature back again to Firefox on Android because Firefox Lite has it and works perfectly.

**Comment by benyaminl** [comment] 2021-08-01 16:19
Will this implemented soon? It's already 3 years and has P3 label

**Comment by javi2man** [comment] 2021-08-30 03:55
I was wondering if anyone has got the Google Data saver extension 's backup (.xpi file). Please!

**Comment by plwt** [comment] 2021-12-29 15:42
User feedback: https://support.mozilla.org/en-US/questions/1362581

**Comment by madb1lly** [comment] 2021-12-30 16:05
This is where we see the problem with the dev team being US based where they have huge data allowances and with less international travel they don't face issues with international roaming charges as frequently. Almost 3 years since the ticket was first raised and all that is needed is to add a toggle switch in settings to link to something which already exists in about:config.

**Comment by metronightly** [comment] 2021-12-31 12:11
> This is where we see the problem with the dev team being US based where they have huge data allowances and with less international travel they don't face issues with international roaming charges as frequently. Almost 3 years since the ticket was first raised and all that is needed is to add a toggle switch in settings to link to something which already exists in about:config.

Wait, this already exists in about:config? What is it ? Because I have switched to the Nightly version and it has config support.

**Comment by madb1lly** [comment] 2022-01-01 13:50
Hi @metronightly, sorry I can't remember but I think it took a bit of archaeology on Mozilla websites to find it - maybe on mozillazine?
Good luck! 🙂

**Comment by J0WI** [comment] 2022-01-02 14:55
> What is it ?

https://github.com/mozilla-mobile/fenix/issues/810#issuecomment-755331302

**Comment by JP95Git** [comment] 2022-01-23 17:27
Duplicate of #12711

**Comment by madb1lly** [comment] 2022-01-23 21:10
Or rather #12711 is a duplicate of this one ;) This issue has been around 14 months longer and has more feedback with it. If only there was a way to merge issues rather than just close and mark duplicate.

**Comment by kbrosnan** [comment] 2022-08-01 16:25
Going to close this in favor of https://github.com/mozilla-mobile/fenix/issues/12711

**Closed by kbrosnan** 2022-08-01 16:25 UTC
Labels: feature request 🌟, P3
