### ISSUE TITLE
[Bug] Undo close tab message stays indefinitely

### ISSUE THREAD

**Issue by FelixFifi** [mozilla-mobile/fenix#8357] opened 2020-02-12 16:25 UTC
## Steps to reproduce
1. Have 2 tabs open.
2. Close one and select the other one before the message disappears
=> Undo close tab message stays on the screen indefinitely + becomes non-functional
### Expected behavior
Undo close tab message disappears after a few seconds
### Actual behavior
Message is shown indefinitely and loses functionality
### Device information

* Android device: Pixel 3a, Android 10 January
* Fenix version: Firefox Preview 3.2.1 (Build #20250350)

**Comment by cadeyrn** [comment] 2020-02-12 16:47
Duplicate of #7799.

**Comment by ekager** [comment] 2020-02-12 21:15
This is fixed in master/nightly and will be fixed in the next release. thanks for your patience!

**Closed by ekager** 2020-02-12 21:15 UTC
Labels: needs:triage, 🐞 bug
