### ISSUE TITLE
[Bug] After migration, awesomebar search results did not appear

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8132] opened 2020-02-05 22:19 UTC
## Steps to reproduce
_I only reproduced once so I can't guarantee this is reproducible on every update_
- Get migrated to new Nightly
- Type in awesomebar

### Expected behavior
Awesomebar search results show history suggestions in list below search suggestions

### Actual behavior
Awesomebar only returns search suggestions, not history suggestions. Even when making new searches in new tabs, these results did not appear in my search suggestions.

Using the browser later the same day, the history search suggestions appear to be working correctly.

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 200130 09:24 – I got migrated today

**Comment by mcomella** [comment] 2020-02-05 22:21
I wonder if this is related to https://github.com/mozilla-mobile/fenix/issues/3863

**Comment by boek** [comment] 2020-02-25 05:41
@pocmo Is this intended or still an issue?

**Comment by pocmo** [comment] 2020-02-25 10:13
Oh, we were not aware of this bug being filed. :(

@ebalazs-sv Have you ever noticed such a problem?

**Comment by ebalazs-sv** [comment] 2020-02-25 11:45
@pocmo I did not notice this issue while testing. I verified this on Beta migration build 1 and it is not reproducible.

**Comment by pocmo** [comment] 2020-02-25 13:19
Thank you!

I think without any additional hints like logs this is not really actionable.

Pinging @grigoryk as a last resort... do you have any idea what may have caused that?

**Comment by st3fan** [comment] 2020-02-26 19:15
I moved this to the QA column not because we have a fix but because we can't repro this and would like some more testing in this area.

**Comment by LaurentiuApahideanSV** [comment] 2020-03-02 09:07
We tried to reproduce the issue in the latest Beta Migration Build 2 but we unable to.
Devices used: Pixel XL (Android 9), OnePlus 6T (Android 9), Huawei P9 Lite (Android 7), Google Pixel 2 (Android 9) and LG G7 fit (Android 8.1).

**Comment by kbrosnan** [comment] 2020-11-18 02:19
Closing as we are not making changes to the migration code.

**Closed by kbrosnan** 2020-11-18 02:19 UTC
Labels: Feature:Migration, 🐞 bug
