### ISSUE TITLE
[Bug] audio is not played in background one out of two times

### ISSUE THREAD

**Issue by rlucassen2** [mozilla-mobile/fenix#15017] opened 2020-09-12 08:59 UTC
FF for Android 80.1.3 build 2015762835
tested on OnePlus A5000, LineageOS 16 (Android 9)
tested on Samsung S4, LineageOS 17 (Android 10)
Until version 80 this problem did not occur.

Steps to reproduce the problem:

1) goto [http://radio.xaq.nl/](http://radio.xaq.nl/)

2) Start a radio station. In the top bar **should** appear a loudspeaker icon, indicating the the radio stream is started in the background (IOW: the stream does not stop when the phone gets to sleep) but there is no loudspeaker icon. And indeed, the stream will stop after some time due to the phone getting into sleep mode.

3) Choose another station. Now a loudspeaker icon appears in the top bar, and indeed, the stream continues, even when the phone is in sleep mode.

4) Choose another station. There's no loudspeaker icon in the top bar, the stream will stop

5) Choose another station. There's a loudspeaker icon in the top bar, the stream continues

etc etc etc...

Richard.

**Comment by rocketsroger** [comment] 2021-01-15 19:35
On Nightly with the new MediaSession API cannot reproduce.

**Comment by rocketsroger** [comment] 2021-01-15 19:35
Please confirm that this is fixed in Nightly

**Comment by sflorean** [comment] 2021-01-18 13:07
I can confirm that is not reproducible on Nightly with Samsung Galaxy Note10 (Android10), but it is reproducible on the release version of Fenix. Due to the result I will close this issue.

**Closed by sflorean** 2021-01-18 13:07 UTC
Labels: Feature:Media, S2, eng:qa:needed, 🐞 bug
