### ISSUE TITLE
FNX-3303 ⁃ [Bug] When requesting location permission, Android System dialog appears after app modal bottom sheet

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#10131] opened 2020-04-23 03:07 UTC
## Steps to reproduce
1. Within Android Settings, make sure Fenix hasn’t been granted permission to use location
1. Go to https://permission.site
1. Click “Location”

![](https://user-images.githubusercontent.com/51007/80054843-6ecf4780-8574-11ea-9193-0ff04b6b8c86.png)

### Expected behavior
1. Android System modal dialog should be shown first
1. Only after allowing the system dialog, then our own app modal bottom sheet is shown

The expected behaviour should be similar to camera and microphone permission requests.

![](https://user-images.githubusercontent.com/51007/80054862-7b53a000-8574-11ea-8ab5-8481e6baeb75.png) → ![](https://user-images.githubusercontent.com/51007/80054916-90303380-8574-11ea-9263-cc4daf426254.png)

### Actual behavior
1. App modal bottom sheet is shown first
1. Android System modal dialogue is shown afterwards

![](https://user-images.githubusercontent.com/51007/80054916-90303380-8574-11ea-9263-cc4daf426254.png) → ![](https://user-images.githubusercontent.com/51007/80054862-7b53a000-8574-11ea-8ab5-8481e6baeb75.png)

**Comment by sv-ohorvath** [comment] 2020-04-23 08:06
dupe of https://github.com/mozilla-mobile/fenix/issues/1686

**Closed** 2020-08-10 19:03 UTC
Labels: Feature:SitePermissions, 🐞 bug
