### ISSUE TITLE
Fix current visual locale issues

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#3355] opened 2019-06-11 17:49 UTC
**For QA: please test Fenix using the pseudo locale and identify relevant UI bugs such as #3335**

## User Story
* As a user, I want to be able to use Fenix in all locales

### Acceptance Criteria
* I can use Fenix in all locales
In addition to the cases identified below:
* https://github.com/mozilla-mobile/fenix/issues/4323

- - -
Edit by @sblatz: This does not include trying to support RTL just yet as we don't have that capability in Fenix yet.

**Comment by abodea** [comment] 2019-06-13 11:31
Hello please note the following:
## Pseudo locales testing:
| Type      | Working/Not working   |
| ------------- |:-------------:|
| XA locale    | ✅ |     
| XB locale   | ✅ | 

<details>
<summary>ENGLISH (XA)</summary>
   ### And here is the ENGLISH (XA):
Adds Latin accents to the base English UI text, expands the original text by adding non-accented text, and brackets each message unit to expose potential issues from expanded text. Potential issues can be layout breakage and badly formed message syntax as shown by one sentence split into multiple parts displaying as multiple bracketed messages. The English (XA) pseudolocale is shown in figure 1.
</details>

<details>
<summary>ENGLISH (XB)</summary>
### And here is the ENGLISH (XB):
AR (XB): Sets the text direction of the original left-to-right messages to the right-to-left direction, which reverses the order of the characters in the original message. The AR (XB) pseudolocale is shown in figure 2.
</details>

### Please note that I tested on the following devices:
| Device       | Type       | Works?|
| ------------- |:-------------:|                 -----:|
| Google Pixel 3(Android 9)     | **XA and XB** | ✅     |
| Google Pixel 3XL(Android 9)   | **XA and XB**    |✅    |  
| Google Pixel C tab (Android 8.0) | **XA and XB**     |   ✅|

#### I tested the following sections:
* **Home screen** containing: `Search or enter address, Open Tabs, Collections)` with all the menus available.
* **Home screen in private mode** containing: `Search or enter address and Private session tab` with all the menus available.
* **Settings section** containing: `Account, Basics, Advanced, Developer tools, About` with all the sub menus.
* **Library section** containing: `Bookmarks and History`.

Basically I verified all the menus from Fenix and everything worked as expected on `Google Pixel 3XL(A 9), Google Pixel C tab(A 8), Google Pixel 3XL(A 9).

But on **`Google Pixel 3(A 9) and Google Pixel 3XL(A 9)`** using `XA` I noticed the following on the  
### **`Account Settings`** section:
- The text **`Account settings one two three`** gets out of its designated area.
- The text **`Last Synced one two`** the square bracket is added right before `one, two` text.

Please note that this issue cannot be reproduced on Google Pixel Tab.
Here you can find the screenshot regarding the issue above:
![Screenshot_20190613-124153](https://user-images.githubusercontent.com/42831109/59422443-10283180-8dd9-11e9-9722-87ddaacd31d5.png)

### **`Collections`** section:
* When trying to add more websites to a collection but I saw that this bug is already submitted #3335.
![x3](https://user-images.githubusercontent.com/42831109/59428260-77e47980-8de5-11e9-9fe3-37e5b3bc679c.png)

###  **`Select tab`** section:
* **`The select Tabs and Deselect All`** text overlaps while using **`XA`**
![x1](https://user-images.githubusercontent.com/42831109/59428447-ef1a0d80-8de5-11e9-8d68-73091cbcbb98.png)

### **`Library`** section: 
When holding on any bookmark/History website the text spill out of its designated area using **`XA`**.
![Screenshot_20190613-142912](https://user-images.githubusercontent.com/42831109/59429143-cbf05d80-8de7-11e9-8db9-1de1cdbe403c.png)
Based on my comment I will remove the QA Needed until the issues above are fixed.

**Comment by mheubusch** [comment] 2019-06-27 01:40
@AmyYLee are there specs you can provide (or point to if they already exist) to address these spacing issues in non-English locales?  or does this have to do with how the specs scale on smaller screens/lower resolution devices? please investigate and let me know if there is a holistic way to address.

**Comment by AmyYLee** [comment] 2019-06-27 16:37
> @AmyYLee are there specs you can provide (or point to if they already exist) to address these spacing issues in non-English locales? or does this have to do with how the specs scale on smaller screens/lower resolution devices? please investigate and let me know if there is a holistic way to address.

I think we should follow native android rules for long strings which is here.

<img width="875" alt="Screen Shot 2019-06-27 at 12 13 01 PM" src="https://user-images.githubusercontent.com/5992746/60282536-35d33180-98d5-11e9-8130-540c9b9831e3.png">

For the bottom edit bar please reference below:
![Edit bar (2-lines)](https://user-images.githubusercontent.com/5992746/60283936-551f8e00-98d8-11e9-8955-b2d608945cc8.png)

**Comment by mheubusch** [comment] 2019-06-27 21:40
Amy's assumption is that these design elements will scale to accommodate text based on our use of Material Design UI components.  https://github.com/material-components/material-components-android
Are these design elements built custom or using material UI? Please assign an engineer to discuss how we approach this and resolve text issues.

**Comment by mheubusch** [comment] 2019-07-02 14:18
@ekager and @colintheshots can you follow up with me at your leisure to let me know if you are using the material components or if you are custom building this - want to make sure our design team's expectations are aligned with how things are built so we can be sure we spec components correctly in the future.

**Comment by ekager** [comment] 2019-07-02 16:05
We generally use built in Android components / Material components when available (notable exception is the toolbar which is a custom view built in AC)

**Comment by colintheshots** [comment] 2019-07-15 15:49
@mheubusch Our Toolbar and Snackbar are custom. Otherwise, we generally use Material components, as @ekager stated. We have the capability to make more custom components if the UX calls for it, but it adds more development time.

**Comment by sblatz** [comment] 2019-07-18 18:40
Can we file individual follow-ups for each additional issue? This ticket doesn't feel actionable to me. @AmyYLee, @mheubusch

**Comment by liuche** [comment] 2019-07-19 20:50
Okay - if there needs to be more UX thought that goes into each of these 4 individual parts that Andrei has provided screenshots for, these should be filed individually, and then put into the Prioritized Backlog.

However, I'm not sure what the priority of this is (I suspect P1) so I'm going to throw this back into group triage so we can figure out:
a) if each piece needs individual UX work, because this is all custom UI
b) what priority each/all of these are

**Comment by mheubusch** [comment] 2019-07-19 23:09
sorry @liuche and @colintheshots my point was, Amy's expectation is that these components are built using Material UI and should scale to accommodate text length as this flexibility is built into the components.  If they are not scaling, and the Material UI is meant to scale, is there something UX hasn't specified correctly to say "use this component and also allow it to scale to fix varying text lenghts"  - our assumption is that using an existing component that is designed to scale will scale regardless of line length or line wrapping and preserve spacing, padding, etc. We do not want to introduce custom UI.  I am simply asking that you help us understand why the spacing and padding issues are occurring if we are not using custom UI.

**Comment by liuche** [comment] 2019-07-25 21:50
@AmyYLee and @ekager - could you two talk about this to come up with a list of actionable tasks that can fix these items.

Outcomes:
1) List of actionable tasks to fix these specific problems
2) Move it to the Bug Backlog

**Comment by ekager** [comment] 2019-07-29 22:09
@AmyYLee for the overlapping collections text should we ellipsize the button text or allow multi-line? There is a contributor in https://github.com/mozilla-mobile/fenix/issues/4323 happy to work on it

**Comment by AmyYLee** [comment] 2019-08-07 17:47
@ekager > @AmyYLee for the overlapping collections text should we ellipsize the button text or allow multi-line? There is a contributor in #4323 happy to work on it cc @ValentinTimisica

I added my feedback to the bug #4323

**Comment by sblatz** [comment] 2019-09-23 20:25
I will look through the issues mentioned in this ticket and make a decision about if there's more work to do here. Any more issues we find should be created as follow-ups.

**Comment by sblatz** [comment] 2019-09-26 23:10
@AndiAJ Are you able to verify that you're not seeing issues as mentioned in your original comment? I'm a bit confused about what the problem is based on those screenshots.

**Comment by sblatz** [comment] 2019-10-07 17:47
@abodea do you have an update on this? 😄

**Comment by abodea** [comment] 2019-10-08 11:56
Hello @sblatz sorry for the delay.
#### Note the following
## Pseudo locales testing:
| Type      | Working/Not working   |
| ------------- |:-------------:|
| XA locale    | ✅ |     
| XB locale   | ✅ | 

I have re-tested all the sections from fenix:
 - While a tab is open, tap on 3 dot menu, the `Save to collection` spills out of its designated area.

![Screenshot_20191008-122641](https://user-images.githubusercontent.com/42831109/66391494-f5a44480-e9d5-11e9-8f01-cd703d24f153.png)

 - When trying to delete a collection the text spills out of its designated area.
![Screenshot_20191008-122722](https://user-images.githubusercontent.com/42831109/66391565-1e2c3e80-e9d6-11e9-98f4-f7bfcf5567b4.png)

 - Tap on 3 dot menu and the `What's New` text spills out of its designated area.
![Screenshot_20191008-122729](https://user-images.githubusercontent.com/42831109/66391636-487dfc00-e9d6-11e9-97bc-9c1d90a3d415.png)

 - @sblatz Should we let so many words on the Enhance tracking protection?
![Screenshot_20191008-122805](https://user-images.githubusercontent.com/42831109/66391769-b296a100-e9d6-11e9-928f-3ab65a334f7b.png)

 - Tracking Protection menu info button the top text spills out of its designated area.
![Screenshot_20191008-122813](https://user-images.githubusercontent.com/42831109/66391974-36508d80-e9d7-11e9-8598-700b7553f407.png)

 - Add private browsing text from the prompt is incorrectly displayed.
![Screenshot_20191008-122919](https://user-images.githubusercontent.com/42831109/66392010-5c762d80-e9d7-11e9-9403-d5a0ee0929a8.png)

 - When trying to delete a bookmark the `open in a new/private tab` text spills out of its designated area.
![Screenshot_20191008-123303](https://user-images.githubusercontent.com/42831109/66392161-c098f180-e9d7-11e9-83e5-98f533d4101f.png)

 - Enhance tracking protection text spills out of its designated area.
![Screenshot_20191008-142143](https://user-images.githubusercontent.com/42831109/66392469-9d227680-e9d8-11e9-99e5-6bf6219f8c87.png)

 - Desktop site, Add to home screen, Report site issue, Save to Collection options from the three dot menu are incorrectly displayed.
![Screenshot_20191008-142812](https://user-images.githubusercontent.com/42831109/66392586-f7233c00-e9d8-11e9-8da0-622189e0c3d7.png)

Note that those are the only issues that are right now:
As I understood all text should be fully displayed while using `XA or XB`.

| Text      | Type       | Displayed ok?       |
| ------------- |:-------------:|:-------------:|
| Save to collection     | **XA and XB** |  ❌     |
|  Delete collection  | **XA and XB**    |  ❌    |  
| What's new | **XA and XB**     |   ❌|
| Middle text from TP menu | **XA and XB**     |   ❌|
| TP info button | **XA and XB**     |   ❌|
| Open new tab(from bookmarks menu) | **XA and XB**     |   ❌|
| Enhancced Tracking Protection | **XA and XB**     |   ❌|
|  Desktop site, Add to home screen(3 dot menu) | **XA and XB**     |  ❌|
|   Report site issue, Save to Collection(3 dot menu) | **XA and XB**     |   ❌|

**Comment by vesta0** [comment] 2019-10-08 17:54
Created a spike #5855 for ENG and UX to discuss and determine next steps.

**Comment by liuche** [comment] 2019-12-10 01:29
Filed these as separate issues, grouped by location/problem, so closing this issue now.

**Closed** 2020-08-26 23:17 UTC
Labels: P2, ux:m, 🌐 L10N, 🐞 bug
