### ISSUE TITLE
Unlock the addon "I don't care about cookies" for FF Android

### ISSUE THREAD

**Issue by badger12345** [mozilla-mobile/fenix#17093] opened 2020-12-17 08:51 UTC
This addon 
https://addons.mozilla.org/de/firefox/addon/i-dont-care-about-cookies/

Is availble for FF on Windows and Mac, why not also for Android?
According to its dev Kiko, from a technical point of view, it is compatible

Please unlock this addon for FF on Android, it is a huge time saver. Because I do not care about cookies.

Thanks!

**Comment by s-ankur** [comment] 2020-12-17 11:57
While this is not a solution, if you have ublock origin, you can always subscribe to the filterlist directly 
https://filterlists.com/lists/i-dont-care-about-cookies (click on subscribe)

**Comment by pidus** [comment] 2020-12-17 12:02
@s-ankur It doesn't work as well as the add-on.

**Comment by badger12345** [comment] 2020-12-17 12:58
@s-ankur thanks for the suggestion, but as @pidus mentioned, it does not work as well as the addon itself.

My goal is to just accept all cookies. I do not want to search for the accept button on every page I visit. That is what the "I don't care about cookies" addon does, it just clicks those nasty popups away. A time saver and at the same time nerve soothing.

It already worked in all previous FF versions for Android, only since 80.x the FF team blocked it for whatever reason.

**Comment by Amejia481** [comment] 2020-12-17 15:32
@badger12345 You could create your custom list of add-ons in [nightly](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/), be aware that it's a developer feature we can't warranty that add-ons  that are not in the supported list will work as expected.

**Comment by badger12345** [comment] 2020-12-18 12:46
@Amejia481 nice suggestion. I will give it a try with a nightly build.

**Comment by Amejia481** [comment] 2020-12-18 14:23
I think we can close this issue.

**Closed by Amejia481** 2020-12-18 14:23 UTC
Labels: Feature:WebExtensions

**Comment by badger12345** [comment] 2020-12-18 14:39
@Amejia481 it is a little comlicated to create a custom list, but it does work indeed. Also the plugin works flawlessly. What keeps the FF team from enabling it in the stable version?

**Comment by Amejia481** [comment] 2020-12-18 15:00
I'm not aware of the process @kewisch could help us to clarify.

**Comment by Otiel** [comment] 2021-03-11 08:47
This addon is not yet available in stable, though it has been reported that it works on nightly. Can we re-open this issue?

**Comment by joenepraat** [comment] 2021-04-16 21:16
I wanted to open an issue for this. Can you please re-open or add it to the app? Although the ublock-origin helps, it doesn't fix the complex cookie warnings. @kewisch @Amejia481

**Comment by overflo94** [comment] 2021-04-27 15:24
I also wanted to open an issue for exactly this add-on. Please re-open this issue. The "I don't care about cookies" add-on is the only reliable way to get rid of the cookie warnings.

**Comment by badger12345** [comment] 2021-05-04 13:09
I don't care about cookies plugin works flawlessly in FF nightly for Android. I have been using it for nearly half a year. Please reopen this issue or add it to the supported addon list of FF. Thanks @kewisch @Amejia481

**Comment by eleszet** [comment] 2021-05-24 11:44
Please reopen this issue. It would be much appreciated by the cumminity and a huge time saver. Currently I don't see a lot of better ways to solve this problem so this could also push the popularity of ff.

**Comment by jonatanolofsson** [comment] 2021-05-29 21:14
@Amejia481 Could you please consider not closing this issue until it is done? It's obviously not a permanent solution to force the use of nightlies

**Comment by to-sensei** [comment] 2021-06-01 18:17
> 
> 
> I think we can close this issue.

no. we can not. this plugin NEEDS to happen.
i really miss the short period between "discovering this works on mobile" and "suddenly, it didn't work anymore", when mobile browsing actually was possible without violently cursing every time you open a new website.

this plugin working on mobile actually was THE key reason why i switched from chrome to firefox.

in terms of usability of firefox, this issue needs to be reopened and pushed to the TOP of the priority list. period.

**Comment by pwiegers** [comment] 2021-08-13 04:59
This is one of those issues that is slowly killing FF. Users clearly want a thing to happen, but for some reason this is just not happening. This /could/ be a killer feature on mobile. But if it is not happening, it will... not happen?

**Comment by it9exm** [comment] 2021-09-08 12:11
Please allow this addon in the stable version of Firefox for Android, I can't stand no more clicking agree buttons for accessing the Google homepage
.

**Comment by henricook** [comment] 2021-10-17 06:52
@Amejia481 and others who are keeping this closed and locked, please reopen and action this. It sounds like you just need to add an add-on to the whitelist for the next release?

I also am plagued by cookie warnings and use this extension on desktop to keep the internet bearable

**Comment by edo0** [comment] 2021-11-09 07:00
There is no use unfortunately, the FF development team seems so US-centric they will not give a damn about EU users needs.
I strongly recommend switching to Kiwi Browser, free and open source as well as easily supporting a plethora of extensions, including "I don't care about cookies"

**Comment by AnderssonPeter** [comment] 2021-11-10 14:21
I don't get why this addon is not on the list, it worked on a previous version on ff for Android.. Sadly i had to switch to a chrome based browser just to get this addon working..

I wan't to use firefox but this is a deal breaker, if you are non eu based, try vpn to eu and use the web... 2/3 webpages show you a gdpr dialog..

**Comment by cadeyrn** [comment] 2021-11-10 15:32
Normally every website shows such a thing _once_. I live in the EU and I never needed such an add-on. 🤔 Anyway, if it's important to you, you can either use Firefox with uBlock Origin (there is a list for that!) or Firefox Nightly with a custom collection and install the mentioned add-on. It's not perfect but at least uBlock Origin (I didn't test the other add-on) works for most websites.

**Comment by AnderssonPeter** [comment] 2021-11-10 15:46
While its fun to try beta software to try out features but to daily drive.. No thanks.

I use uBlock Origin and while its better than nothing its not even close to use the right addon, i dont get why it takes over a year to add a addon to a whitelist, also i don't get the point of the whitelist...

**Comment by edo0** [comment] 2021-11-10 16:24
> Normally every website shows such a thing _once_ within a longer period of time. I live in the EU and I never needed such an add-on

Unfortunately that seems to signal only that you do not clean your cookies as often as you should for most sites to decrease first party profiling

**Comment by to-sensei** [comment] 2021-11-10 16:30
@cadeyrn 95% of the websites i visit in total, i visit _once_. so that point is moot, even if you ignore a lack of cookie hygiene.
and yes, there are two ways to achieve this, but both are inferior to the way that _already worked before_ and was arbitrarily removed.

alternatively, i'd like someone to explain _why_ exactly "i don't care about cookies" was removed, since
1) it was working perfectly before and
2) apparently, it's been working perfectly in the nightly build for quite some time, as mentioned in this thread very often.

**Comment by LoGlo2** [comment] 2021-12-09 12:29
Please enable this plugin. There is no adequate alternative solution.

**Comment by henricook** [comment] 2021-12-09 12:38
@Amejia481 Can you listen to the community and reopen this?

**Comment by replete** [comment] 2021-12-20 11:15
Why is this closed?

**Comment by edo0** [comment] 2021-12-20 11:39
> Why is this closed?

Because Mozilla is a "global community" who gives 0 fucks about EU nationals

**Comment by it9exm** [comment] 2021-12-20 13:24
This is unacceptable. Please reopen and fix this once for all.
If it is allowed to install uBlock Origin there is no reason to block this addon.
Anybody here ever got in touch with the author for this issue? He says Mozilla is rejecting the approval.
Damn, I use incognito mode and since Google introduced that cookie consent screen, I started using Duckduckgo.
That was something, just not enough. I want this addon on mobile Firefox.

**Comment by henricook** [comment] 2021-12-21 09:20
From https://github.com/mozilla-mobile/fenix/issues/22918#issuecomment-998432756

> We are not keeping individual issues open for specific extensions. We track the extension APIs that are needed at https://bugzilla.mozilla.org Geckoview::WebExtensions

**Comment by AnderssonPeter** [comment] 2021-12-22 21:17
Has any one created a bug at https://bugzilla.mozilla.org ?

**Comment by it9exm** [comment] 2021-12-22 21:33
I have just created it:
https://bugzilla.mozilla.org/show_bug.cgi?id=1747303

**Comment by it9exm** [comment] 2022-03-28 08:01
Hello,
The mozilla bug report 1747303 has been closed with "RESOLVED WORKSFORME" because the extension does not require additional API work to run on fenix. However, the addon is still not available.
If anybody wishes to suggest the next step, please do it here.
Thank you

**Comment by henricook** [comment] 2022-06-20 16:05
It is enormously puzzling, that this is ignored. It feels like corporate interests being protected. I thought Mozilla was better than that.

**Comment by Mugen36** [comment] 2022-06-21 12:07
> It feels like the interests of advertisers being protected.

That might be indeed the case.

Although I probably attribute it to sheer incompetence.

**Comment by Mugen36** [comment] 2022-06-21 12:11
Ironically, this addon is recommend by Mozilla on Firefox for Desktop.

**Comment by Mugen36** [comment] 2022-06-28 19:06
I dont know, if this has been posted before.
We can circumvent this issue by using Fennec from Fdroid.
It allows the usage of custom collections of addons.
nobody, the dev of the addon LocalCDN, gives an detailed explaination (in German) how it done here:
https://www.kuketz-blog.de/howto-beliebige-add-ons-in-fennec-auf-android-installieren/

**Comment by danepowell** [comment] 2022-06-30 20:29
Confirmed that the method suggested by @Mugen36 works, thanks!

To clarify especially for non-German speakers:

1. Create an account on addons.mozilla.org
2. Create a "collection", I named it "fennec"
3. Add "I don't care about cookies" as well as any other add-ons you want to use to the collection
4. In Fennec from F-Droid settings, go to the about page, tap the logo 5x to become a developer
5. Open the new "custom add-on collection" settings menu item
6. Input your addons.mozilla.org user id # and collection name "fennec"
7. After Fennec restarts, you should see the selected add-ons in the add-on manager!

**Comment by PolicyPuma4** [comment] 2022-07-12 15:36
> Confirmed that the method suggested by @Mugen36 works, thanks!
> 
> To clarify especially for non-German speakers:
> 
>     1. Create an account on addons.mozilla.org
> 
>     2. Create a "collection", I named it "fennec"
> 
>     3. Add "I don't care about cookies" as well as any other add-ons you want to use to the collection
> 
>     4. In Fennec from F-Droid settings, go to the about page, tap the logo 5x to become a developer
> 
>     5. Open the new "custom add-on collection" settings menu item
> 
>     6. Input your addons.mozilla.org user id # and collection name "fennec"
> 
>     7. After Fennec restarts, you should see the selected add-ons in the add-on manager!

This is one solution however it's far from desirable for most people, Fennec has stripped features away from their build in the process of being completely open source, both DRM and FIDO don't work on Fennec.

I've actually managed install none approved add-ons on the stable release by using a MITM proxy to redirect API calls to the Mozilla add-on collection to my own, this is also far from desirable, not only was it convoluted and not easy to do, I don't believe the add-ons I've installed will update themselves once I remove the MITM proxy. Someone with a lot more knowledge than me could technically create an Android app which could act as a local MITM proxy by using a local VPN and an installable certificate similar to AdGuard however the real solution is for Mozilla to enable the custom collection secret setting in the release build, something which I'm completely dumbfounded as to why it hasn't happened already.

**Comment by vkk800** [comment] 2022-07-15 09:58
Why is this issue closed? As far as I can tell, it's still not possible to install this add-on on Android.

**Comment by HTDemony** [comment] 2022-08-13 18:19
Please 🙏 activate this extension.
Otherwise, we will forced to change our favourite browser to another with this extension activation possible.

**Comment by AnderssonPeter** [comment] 2022-08-13 19:38
If your on Android the kiwi browser supports freedom of extension choice!

The sad thing of that we know that mobile Firefox supports it but just polices you not to use it! 🤬🤬

**Comment by PolicyPuma4** [comment] 2022-08-14 13:33
> Why is this issue closed? As far as I can tell, it's still not possible to install this add-on on Android.



> Please 🙏 activate this extension. Otherwise, we will forced to change our favourite browser to another with this extension activation possible.



> If your on Android the kiwi browser supports freedom of extension choice!
> 
> The sad thing of that we know that mobile Firefox supports it but just polices you not to use it! 🤬🤬

Make sure to express your opinion on this topic here https://connect.mozilla.org/t5/ideas/expand-add-on-compatibility-in-firefox-for-android/idi-p/191.

**Comment by calla-lilly** [comment] 2022-09-10 19:01
> I don't care about cookies plugin works flawlessly in FF nightly for Android. I have been using it for nearly half a year. Please reopen this issue or add it to the supported addon list of FF. Thanks @kewisch @Amejia481

AGREE !!!!

**Comment by calla-lilly** [comment] 2022-09-10 19:02
AGREE !!!!

**Comment by calla-lilly** [comment] 2022-09-10 19:02
> Please reopen this issue. It would be much appreciated by the cumminity and a huge time saver. Currently I don't see a lot of better ways to solve this problem so this could also push the popularity of ff.

AGREE !!!!

**Comment by calla-lilly** [comment] 2022-09-10 19:03
> @Amejia481 Could you please consider not closing this issue until it is done? It's obviously not a permanent solution to force the use of nightlies



> Please reopen this issue. It would be much appreciated by the cumminity and a huge time saver. Currently I don't see a lot of better ways to solve this problem so this could also push the popularity of ff.

AGREE !!!!

**Comment by calla-lilly** [comment] 2022-09-10 19:05
> I think we can close this issue.

PLEASE REOPEN.
WHY DO ISSUES CLODE WHEN NOT RESOLVED ?????

**Comment by calla-lilly** [comment] 2022-09-10 19:05
PLEASE REOPEN.
WHY DO ISSUES CLODE WHEN NOT RESOLVED ?????

**Comment by calla-lilly** [comment] 2022-09-10 19:29
> I dont know, if this has been posted before. We can circumvent this issue by using Fennec from Fdroid. It allows the usage of custom collections of addons. nobody, the dev of the addon LocalCDN, gives an detailed explaination (in German) how it done here: https://www.kuketz-blog.de/howto-beliebige-add-ons-in-fennec-auf-android-installieren/

----REPLY-----------
Can I also transfer bookmarks on Fennec? 

-------COMMENTS, QUESTIONS, FOR FF DEVELOPERS.
PLEASE RESPOND TO ALL POINTS.  CAN YOU NOT SEE THE ONGOING PROBLEM WITH YOUR BROWSER FROM THE VIEWPOINT OF THE USERS???????-------------
Or, is bookmark transfer capability ANOTHER ignored issue that's been requested 50 million times by users and blown off?

i really don't  understand.

I thought this was opensource and that requests were made so that improvements that ae requested by users could be made to apps, programs, browsers, etc.

Why is it open source and why blow us off?

Just remove it ftom Github, along with all of your other products as YOU CLEARLY LOOK FOR REASONS NOT TO MAKE CHANGES, IMPROVEMENTS, ADDITIONS, TO FF.

We, the consumer, DONT WANT TO USE A BETA, OR A DEVELOPER VERSION, OR TO BUY AN IOS PHONE TO USE THAT VERSION, OR WHATEVER """SUGGESTIONS""' YOU MAKE THAT AREN'T AREN'T A SOLUTION, AREN'T A SOLUTION, BUT RATHER, WAYS TO MAKE US   ******JUST GO AWAY*****  
SO YOU CAN 
****** 'CLOSE THE ISSUE'  ******
****** UNRESOLVED, UNRESOLVED, UNRESOLVED.*****

SO JUST LIST THEM ALL AS CLOSED SOURCE.

*****IM SO SICK OF HALF OF A FF BROWSER.***** 

****IM LOOKING FOR AN ALTERNATIVE****

**Comment by calla-lilly** [comment] 2022-09-10 19:29
> I dont know, if this has been posted before. We can circumvent this issue by using Fennec from Fdroid. It allows the usage of custom collections of addons. nobody, the dev of the addon LocalCDN, gives an detailed explaination (in German) how it done here: https://www.kuketz-blog.de/howto-beliebige-add-ons-in-fennec-auf-android-installieren/

----REPLY-----------
Can I also transfer bookmarks on Fennec? 

-------COMMENTS, QUESTIONS, FOR FF DEVELOPERS.
PLEASE RESPOND TO ALL POINTS.  CAN YOU NOT SEE THE ONGOING PROBLEM WITH YOUR BROWSER FROM THE VIEWPOINT OF THE USERS???????-------------
Or, is bookmark transfer capability ANOTHER ignored issue that's been requested 50 million times by users and blown off?

i really don't  understand.

I thought this was opensource and that requests were made so that improvements that ae requested by users could be made to apps, programs, browsers, etc.

Why is it open source and why blow us off?

Just remove it ftom Github, along with all of your other products as YOU CLEARLY LOOK FOR REASONS NOT TO MAKE CHANGES, IMPROVEMENTS, ADDITIONS, TO FF.

We, the consumer, DONT WANT TO USE A BETA, OR A DEVELOPER VERSION, OR TO BUY AN IOS PHONE TO USE THAT VERSION, OR WHATEVER """SUGGESTIONS""' YOU MAKE THAT AREN'T AREN'T A SOLUTION, AREN'T A SOLUTION, BUT RATHER, WAYS TO MAKE US   ******JUST GO AWAY*****  
SO YOU CAN 
****** 'CLOSE THE ISSUE'  ******
****** UNRESOLVED, UNRESOLVED, UNRESOLVED.*****

SO JUST LIST THEM ALL AS CLOSED SOURCE.

*****IM SO SICK OF HALF OF A FF BROWSER.***** 

****IM LOOKING FOR AN ALTERNATIVE****

**Comment by calla-lilly** [comment] 2022-09-10 19:29
> I dont know, if this has been posted before. We can circumvent this issue by using Fennec from Fdroid. It allows the usage of custom collections of addons. nobody, the dev of the addon LocalCDN, gives an detailed explaination (in German) how it done here: https://www.kuketz-blog.de/howto-beliebige-add-ons-in-fennec-auf-android-installieren/

----REPLY-----------
Can I also transfer bookmarks on Fennec? 

-------COMMENTS, QUESTIONS, FOR FF DEVELOPERS.
PLEASE RESPOND TO ALL POINTS.  CAN YOU NOT SEE THE ONGOING PROBLEM WITH YOUR BROWSER FROM THE VIEWPOINT OF THE USERS???????-------------
Or, is bookmark transfer capability ANOTHER ignored issue that's been requested 50 million times by users and blown off?

i really don't  understand.

I thought this was opensource and that requests were made so that improvements that ae requested by users could be made to apps, programs, browsers, etc.

Why is it open source and why blow us off?

Just remove it ftom Github, along with all of your other products as YOU CLEARLY LOOK FOR REASONS NOT TO MAKE CHANGES, IMPROVEMENTS, ADDITIONS, TO FF.

We, the consumer, DONT WANT TO USE A BETA, OR A DEVELOPER VERSION, OR TO BUY AN IOS PHONE TO USE THAT VERSION, OR WHATEVER """SUGGESTIONS""' YOU MAKE THAT AREN'T AREN'T A SOLUTION, AREN'T A SOLUTION, BUT RATHER, WAYS TO MAKE US   ******JUST GO AWAY*****  
SO YOU CAN 
****** 'CLOSE THE ISSUE'  ******
****** UNRESOLVED, UNRESOLVED, UNRESOLVED.*****

SO JUST LIST THEM ALL AS CLOSED SOURCE.

*****IM SO SICK OF HALF OF A FF BROWSER.***** 

****IM LOOKING FOR AN ALTERNATIVE****

**Comment by calla-lilly** [comment] 2022-09-10 19:29
> I dont know, if this has been posted before. We can circumvent this issue by using Fennec from Fdroid. It allows the usage of custom collections of addons. nobody, the dev of the addon LocalCDN, gives an detailed explaination (in German) how it done here: https://www.kuketz-blog.de/howto-beliebige-add-ons-in-fennec-auf-android-installieren/

----REPLY-----------
Can I also transfer bookmarks on Fennec? 

-------COMMENTS, QUESTIONS, FOR FF DEVELOPERS.
PLEASE RESPOND TO ALL POINTS.  CAN YOU NOT SEE THE ONGOING PROBLEM WITH YOUR BROWSER FROM THE VIEWPOINT OF THE USERS???????-------------
Or, is bookmark transfer capability ANOTHER ignored issue that's been requested 50 million times by users and blown off?

i really don't  understand.

I thought this was opensource and that requests were made so that improvements that ae requested by users could be made to apps, programs, browsers, etc.

Why is it open source and why blow us off?

Just remove it ftom Github, along with all of your other products as YOU CLEARLY LOOK FOR REASONS NOT TO MAKE CHANGES, IMPROVEMENTS, ADDITIONS, TO FF.

We, the consumer, DONT WANT TO USE A BETA, OR A DEVELOPER VERSION, OR TO BUY AN IOS PHONE TO USE THAT VERSION, OR WHATEVER """SUGGESTIONS""' YOU MAKE THAT AREN'T AREN'T A SOLUTION, AREN'T A SOLUTION, BUT RATHER, WAYS TO MAKE US   ******JUST GO AWAY*****  
SO YOU CAN 
****** 'CLOSE THE ISSUE'  ******
****** UNRESOLVED, UNRESOLVED, UNRESOLVED.*****

SO JUST LIST THEM ALL AS CLOSED SOURCE.

*****IM SO SICK OF HALF OF A FF BROWSER.***** 

****IM LOOKING FOR AN ALTERNATIVE****

**Comment by calla-lilly** [comment] 2022-09-10 19:58
> I dont know, if this has been posted before. We can circumvent this issue by using Fennec from Fdroid. It allows the usage of custom collections of addons. nobody, the dev of the addon LocalCDN, gives an detailed explaination (in German) how it done here: https://www.kuketz-blog.de/howto-beliebige-add-ons-in-fennec-auf-android-installieren/

----REPLY-----------
Can I also transfer bookmarks on Fennec? 

-------COMMENTS, QUESTIONS, FOR FF DEVELOPERS.
PLEASE RESPOND TO ALL POINTS.  CAN YOU NOT SEE THE ONGOING PROBLEM WITH YOUR BROWSER FROM THE VIEWPOINT OF THE USERS???????-------------
Or, is bookmark transfer capability ANOTHER ignored issue that's been requested 50 million times by users and blown off?

i really don't  understand.

I thought this was opensource and that requests were made so that improvements that ae requested by users could be made to apps, programs, browsers, etc.

Why is it open source and why blow us off?

Just remove it ftom Github, along with all of your other products as YOU CLEARLY LOOK FOR REASONS NOT TO MAKE CHANGES, IMPROVEMENTS, ADDITIONS, TO FF.

We, the consumer, DONT WANT TO USE A BETA, OR A DEVELOPER VERSION, OR TO BUY AN IOS PHONE TO USE THAT VERSION, OR WHATEVER """SUGGESTIONS""' YOU MAKE THAT AREN'T AREN'T A SOLUTION, AREN'T A SOLUTION, BUT RATHER, WAYS TO MAKE US   ******JUST GO AWAY*****  
SO YOU CAN 
****** 'CLOSE THE ISSUE'  ******
****** UNRESOLVED, UNRESOLVED, UNRESOLVED.*****

SO JUST LIST THEM ALL AS CLOSED SOURCE.

*****IM SO SICK OF HALF OF A FF BROWSER.***** 

****IM LOOKING FOR AN ALTERNATIVE****

> > Why is this issue closed? As far as I can tell, it's still not possible to install this add-on on Android.
> 
> > Please 🙏 activate this extension. Otherwise, we will forced to change our favourite browser to another with this extension activation possible.
> 
> > If your on Android the kiwi browser supports freedom of extension choice!
> > The sad thing of that we know that mobile Firefox supports it but just polices you not to use it! 🤬🤬
> 
> Make sure to express your opinion on this topic here https://connect.mozilla.org/t5/ideas/expand-add-on-compatibility-in-firefox-for-android/idi-p/191.

---------------- 
I will follow the link 
AND 
WHY DO WE HAVE TO POST IN 50 PLACES ?????
I'VE ADDRESSED THIS ON FF HELP AND COMMUNITIES, AND THEY SAY COME HERE, NOW, GO THERE????

FF is just becoming so FULL OF POLITICS, WHOSE POLICIES ARE JUST NOT WORTH IT.

THERE'S GOT TO BE A BETTER PRODUCT WITH THE OPTIONS WE DESIRE AND MORE OPTIONS TO COME TO LOVE.

**Comment by it9exm** [comment] 2022-09-10 20:17
Hey, calm down.

We all know this is too much of a hassle and how strong is it, and I'm also feeling that personally, 
Although I hate to use GH for these things, I don't think it's the right place, and nobody at Mozilla will read. 
I already tried last December when some major contributor suggested to open a report in their bugzilla for the API, which was perfectly fine

Not sure what we could do, perhaps we should start a campaign? like on Twitter? #unlockfenixaddons 

I also suggest all of you to watch this from @morrolinux 
it's in Italian language, foreign people please use subs
find my comments among 1098 and upvote all of them, they point to this GH issue

https://www.youtube.com/watch?v=-jUhhrsmHoM

If you watch the full video, the guy basically says that Mozilla is in danger, and how bad is the monoculture that Google is supporting. 

Maybe you can finally conclude that Mozilla is not the problem, and that's better to look for an alternative mobile OS, rather than an alternative browser?

**Comment by calla-lilly** [comment] 2022-09-10 20:21
ANOTHER ISSUE :

INABILITY TO QUICKLY AND ****SIMPLY**** EXPORT BOOKMARKS.

I FOR ONE, AM OVER IT.

FRANKLY, IM PLANNING TO JUST OVERHAUL WITH A NEW SYSTEM THAT COMPLETELY RIDS ME OF ALL THESE ISSUES, TO INCLUDE GETTING RID OF GOOGLE AND US GOVT SURVEILLANCE COMPLETELY AND ENTIRELY.  I WONT NEED ANYTHING FROM FF.  

FF ONLY OFFERS PRIVACY IN SEARCH, ONCE YOU ACTUALLY GO TO A WEBSITE FROM THE RESULTS, YOU'RE IN FULL VIEW OF THE ENEMIES.  FF DOESN'T ADVERTISE THIS AT ALL.  THEY WANT YOU TO THINK THEY ARE THE END ALL AND BE ALL.

AND ***DO NOT*** REPLY BY STATING, " Oh, we have this clearly stated on this page right here...." ---- BURIED VIA AN OBSCURE LINK ON ONE OF 500 FF WEBSITES - ONE FOR GHIS VERSION, ONE FOR THAT VERSION, ONE FOR HELP ON THIS VERSION, ONE FOR THAT VERSIONS' COMMUNITIES, ONE FOR ISSUES (THAT NEVER GET RESOLVED),
AND 
THIS IS INCLUSIVE FOR ***ALL OLD VERSIONS AND UPDATES OF NEWER VERSIONS***.
SO BY THE TIME YOU FIGURE OUT AND/OR ARE TOLD YOU'RE IN THE WRONG PLACE, OR GET ANY RESPONSE AT ALL, (EXCEPT TO USE ANOTHER VERSION) YOU'VE WASTED 8 -20 HOURS OVER TIME TRYING TO IMPROVE THE VERSION ***YOU CHOOSE***.

WHY DO YOU THINK EVRRYTHING ISNT LISTED ON ONE WEB SITE 

JUST DISGUSTING.

ONCE I'M ALL SET UP, IM GOING TO DEVOTE A SLOT IF TIME HELPING OTHERS LEAVE FF FOR GOOD.

AND, IF YOU THINK ONE PERSON CANT HAVE AN EFFECT, CONSIDER THE ONE PERSON WHO STARTED FF IN THE BEGINNING.......

SICK OF YOUR  RUNAROUND, FF.

**Comment by calla-lilly** [comment] 2022-09-10 20:31
it9exm 
I appreciate your response.  ive NEVER recieved one so quickly.

I've used FF for a long time and am just sick of the bs.  If they arent goimg to anything about anything, THEN THEY SHOULD STOP ADVISING TO POST AN ISSUE - THAT NEVER GETS RESOLVED.

Just imagine the thousands of people who are complacent and/or lazy and/or ignorant that wiuld NEVER EVER IN A MILLION YEARS FIGURE OUT HOW TO NAVIGATE SIMPLY GETTING WHERE YOU NEED TO GO TO POST AN ISSUE THAT IS BLATANTLY IGNORED REPEATEDLY ON NUMEROUS INDIVIDUAL.POSTS FOR EACH OF MANY DIFFERENT ISSUES.

I'm just over this.  And, I meant exactly what I said.  lLike many, they've made a trunkload of money, and maybe ending them is the only way to STOP DISRESPECTING USERS.

**Comment by it9exm** [comment] 2022-09-10 20:56
@calla-lilly Just do what I said. Go there, find my comments, upvote. Then bring upvotes from other people. That's one little step.
Thank you

**Comment by calla-lilly** [comment] 2022-09-10 21:01
> 
will do.
thx.

**Comment by calla-lilly** [comment] 2022-09-10 21:09
> 
will do.
thx.
___________________
And where applicable and to whom it concerns:

Go ahead and downvote.

It just reinforces my points.

Being sweet and spice and everything nice gets you where on FF?  Nowhere.  NOWHERE.

The truth is what it is.

**Comment by pvones** [comment] 2022-12-11 08:09
Could you please reopen the issue? There is no alternative solution on Android other than the addon.

**Comment by LoGlo2** [comment] 2022-12-11 08:37
This is still a MAJOR flaw in daily usage.

**Comment by henricook** [comment] 2022-12-11 09:23
This is my biggest disappointment with Firefox/Mozilla, and I've been bullish on Firefox my whole life - just let me use the plugins I want on mobile :-/

**Comment by cadeyrn** [comment] 2022-12-11 15:50
> I understand that you can't see the importance of the addon in the US

This can't be true if you consider that they're working on a feature to eliminate these "cookie dialogs" for Firefox on Desktop, Firefox on Android and Focus on Android.

> There is no alternative solution on Android other than the addon.

You could install Firefox Nightly and enable this new feature. It can already be tested.

**Comment by pvones** [comment] 2022-12-11 19:20
> Since Mozilla is making great progress on implementing this as a native browser feature I don't think there is still a reason to enable this add-on in particular at this point. But if it's about allowing _all_ add-ons, they are also working on a general availability of add-ons for Android, see [BZ-1796184](https://bugzilla.mozilla.org/show_bug.cgi?id=1796184).

Thank you, I didn't know that. But installing a beta software isn't a solution either. Let's wait how long it will take to promote the feature to the stable version.

**Comment by pvones** [comment] 2022-12-12 17:16
@cadeyrn I tried the Firefox Nightly for Developer, switched on the Cookie Banner Reduction, but it doesn't work at all. I am still getting the annoying cookie banners on all (czech) web sites. The addon (on desktop) works fine.

**Comment by cadeyrn** [comment] 2022-12-12 17:41
@pvones If you find sites where it doesn't work you can report them there:

https://github.com/mozilla/cookie-banner-rules-list
