### ISSUE TITLE
Can't load base64 strings in audio elements

### ISSUE THREAD

**Issue by usemoslinux** [mozilla-mobile/fenix#17878] opened 2021-02-06 02:40 UTC
This might be related to #7341

## Steps to reproduce
To make it easier to reproduce, just go to https://base64.guru/converter/encode/audio, upload a 3 MB or more audio file and select "HTML audio" as output format. Then, create a new page in your server and paste the generated code. Access the page you've just created.

### Expected behavior
The audio element should load the audio file without problems.

### Actual behavior
The audio element seems "empty" and does not load the audio file. In my opinion, it seems to be a memory issue. It must be that Firefox on Android sets a memory limit of some sort. However, loading "big" files using base64 works just fine in Firefox & Chrome desktop versions, as well as in all Chromium based Android browsers (Chrome, Brave, Edge, etc.).

It is also worth mentioning that everything works fine if you use a smaller file, e.g. a 1 MB file. I have not tested it, but I imagine the same thing happens with video elements.

In my particular case, I need to load audio using base64 as I get the audio source from a TTS online service.

### Device information

* Samsung Galaxy S9+
* Firefox 85.1.1

**Comment by vthg2themax** [comment] 2021-03-07 18:54
I also can reproduce this issue with a data file on my site. If I choose a smaller file 256KB, it works, but it does not work when choosing a 8.9MB file. This is stopping me from development, because I cannot save files except to use base64 strings. If there was a bounty to fix this, I would pay it. Please let this be a reasonable 250MB or something, IE9 uses 4GB. Can we follow their example, or even try to beat it? Desktop firefox works correctly, but if we are designing for mobile first, this would not work in that case. Also Brave for Android works correctly with a 13MB file, so it is possible.

**Comment by vthg2themax** [comment] 2021-03-08 13:32
In order to keep this work item from going Stale, I shall write something here everyday. :-)

**Comment by vthg2themax** [comment] 2021-03-08 15:16
If you have a better idea, please let me know.

**Comment by cadeyrn** [comment] 2021-03-08 15:19
There is no need to comment every day. There needs to be 180 days without any activity, otherwise the stale bot won't do anything…

**Comment by vthg2themax** [comment] 2021-03-08 15:21
Okay, well every month or so then, so I don't forget. Hopefully they fix this bug, but in the interim, I will need to use brave because it works correctly with data URLs of a larger size.Thanks for the info!

**Comment by vthg2themax** [comment] 2021-03-10 17:43
According to the linked bug item, it appears this bug will not be fixed.That is a shame, and will cease my use of this browser until this problem is fixed, as it is with the Chromium browsers.

**Comment by vthg2themax** [comment] 2021-03-10 20:50
I guess the only way to continue with Firefox is to rewrite it in JavaScript. Trying to export the Uint8Array to JavaScript from Rust, and creating a new blob from it, crashes the tab in Firefox that it runs in.

**Comment by Mugurell** [comment] 2021-03-11 07:11
The app won't load URLs bigger than 2 MB in size (by default).
Moving to Geckoview for assessing whether the default url size limit should be increased.

**Comment by Mugurell** [comment] 2021-03-11 07:12
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1697727

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by Mugurell** 2021-03-11 07:12 UTC
Labels: needs:gv, 🐞 bug
