### ISSUE TITLE
Pull to refresh webpage doesnot work.[Bug]

### ISSUE THREAD

**Issue by Throb1** [mozilla-mobile/fenix#15592] opened 2020-10-01 10:47 UTC
## Steps to reproduce
Open any webpage, pull from top of the site to refresh.

### Expected behavior
Must reload the opened page.

### Actual behavior
No response

### Device information

* Android device: 10
* Fenix version: 82.0.0-beta.2

**Comment by cadeyrn** [comment] 2020-10-01 10:50
Duplicate of #9766.

**Comment by black7375** [comment] 2020-10-01 10:56
Is there a way to activate it now?

**Comment by cadeyrn** [comment] 2020-10-01 10:59
If you self compile Firefox for Android, yes, it's very easy. You only have to change a feature flag from false to true. Otherwise: no, there is no option within Firefox yet.

**Comment by black7375** [comment] 2020-10-01 11:34
thank you

**Comment by kbrosnan** [comment] 2020-10-01 14:57
Closing as a duplicate

**Closed by kbrosnan** 2020-10-01 14:57 UTC
Labels: needs:triage, 🐞 bug
