### ISSUE TITLE
Clear browser history after a specified amount of time

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12119] opened 2020-06-30 03:59 UTC
As it is right now the browsing history stays forever on the browser and it could become a privacy issue, as not everybody remembers to use a Private Browsing Mode everytime, not to mention the browser history tab becomes an unmanaged clutter if let it be. 

I'd great if the browser history cleared itself after a set period of time such as in a few hours/days/weeks or let them set a custom period.

Edit: I'm talking about the locally saved browsing history.

**Comment by Dunexus** [comment] 2020-06-30 09:42
Dupe of https://github.com/mozilla-mobile/fenix/issues/8342

**Comment by manan025** [comment] 2020-07-01 08:15
I want to work on this.

**Comment by SS1113** [comment] 2020-07-02 08:54
I'm not sure if this is a duplicate of the issue #8342, so I'm re-opening this issue.

**Closed** 2020-08-28 21:22 UTC
Labels: needs:triage
