### ISSUE TITLE
[Bug] Fenix locks up when loading Twitter login (is it all logins?)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#8700] opened 2020-02-24 20:18 UTC
## Steps to reproduce

1. Download the Fenix build from https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-production.2020.02.20/latest
2. Install
3. Run and wait for profile migration to occur
4. Navigate to Twitter login page.

### Expected behavior

I am able to enter my login and use the site.

### Actual behavior

Fenix locks up and as soon as I try to enter credentials into Twitter. 

Profile here: https://perfht.ml/2ulz3jw

Another profile after a few minutes of waiting for Fenix to work again - it never started working again, but here's the profile: https://perfht.ml/37ToPEK

I opened the new Fenix, went to the Twitter login page, tapped the username box... and Fenix stopped responding. Android asked me if I wanted to close the app or wait. I waited and captured the profile above.

Andrew Creskey seems to think:

> But it looks to me like a serious problem (not related to WebRender)
> I think the parent process main java thread is locked up in this function:
> mozilla.components.browser.engine.gecko.autofill.GeckoLoginDelegateWrapper.onLoginFetch

https://bugzilla.mozilla.org/show_bug.cgi?id=1610147#c13

### Device information

* Android device: Pixel 2
* Fenix version: 4.0.0-beta.2 (Build #2015724179)
34.0.0, 80bf35447
GV: 74.0-20200218224219

**Comment by eamsen** [comment] 2020-02-24 21:09
GeckoView's `LoginStorage.Delegate.onLoginFetch` is an async API, but its implementation in a-c is blocking. This needs to be refactored to avoid blocking on the UI thread.

**Comment by Dunexus** [comment] 2020-02-25 10:45
Seems to be the same issue talked in https://github.com/mozilla-mobile/fenix/issues/7903

**Comment by mcomella** [comment] 2020-03-02 23:37
We believe this should be addressed by #7903 but want to double-check that it's now no longer reproducible: ecsmyth is validating #7903 so can validate this one too. Note that validating #7903 is blocked on a crash fix.

**Comment by yoasif** [comment] 2020-03-03 05:28
I had downloaded https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-production.2020.02.20/latest

What build should I download to test the fix?

**Comment by ekager** [comment] 2020-03-03 05:57
The lockup fix is in Nightly, but will currently crash until a fix for #8854 lands (PR #8875)

**Comment by liuche** [comment] 2020-03-03 22:01
This should be fixed now! Going to dupe this to #8854, #7903, and https://github.com/mozilla-mobile/android-components/issues/6084

**Closed by liuche** 2020-03-03 22:01 UTC
Labels: Feature:Logins, eng:performance, needs:triage, 🐞 bug

**Comment by ecsmyth** [comment] 2020-03-04 20:24
Confirmed fixed/does not reproduce in Fenix Nightly 200304
