### ISSUE TITLE
[Bug] Downloaded images not showing up in gallery on Android

### ISSUE THREAD

**Issue by FoxTrotte** [mozilla-mobile/fenix#15153] opened 2020-09-17 10:42 UTC
## Steps to reproduce

Go on any website, download an image with download folder set as the default download folder

### Expected behavior

Pictures should show up in the gallery app, but it doesn't. Neither in the Oneplus gallery app or on the system gallery app (that shows up when trying to upload a file on any website) 

### Actual behavior

None of the downloaded pictures show up in gallery. Using a file explorer I can find the pictures in the Download folder, but none show up in gallery. 
Chrome, Ecosia and Opera browser are all set to the same folder and work as expected. 

### Device information

* Android device: Oneplus 6 - Oxygen Os 10.3.5 - Android 10
* Fenix version: 80.1.3 (Build #2015762835)

**Comment by cadeyrn** [comment] 2020-09-17 10:44
Duplicate of #8754.

**Comment by kbrosnan** [comment] 2020-09-17 14:11
Closing as a duplicate.

**Closed by kbrosnan** 2020-09-17 14:11 UTC
Labels: needs:triage, 🐞 bug
