### ISSUE TITLE
Fenix not appearing on iOS devices

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/fenix#2838] opened 2019-05-24 18:16 UTC
## Steps to reproduce
1. Sign in to FxA.Sync on Fenix and iOS
1. On iOS view send tab from inside or outside Firefox

### Expected behavior
* Fenix appears

### Actual behavior
* Fenix does not appear

### Device information
* iPhone SE and Nexus
* Fenix version: today's
![IMG](https://user-images.githubusercontent.com/68213/58348363-86ff8980-7e2e-11e9-8a0d-2a32322be840.jpeg)UNITO-UNDERSCORE!30C1E2DC4BDE-1!

**Comment by jonalmeida** [comment] 2019-06-06 19:47
I'm adding the a-s label since this is dependent on that.

**Comment by jonalmeida** [comment] 2019-07-11 17:25
@jdragojevic do we want to close this and open an issue on iOS instead? I don't believe there's any work for us to do here.

**Comment by jdragojevic** [comment] 2019-07-11 17:28
Let me try to reproduce, @jonalmeida

**Comment by sblatz** [comment] 2019-07-16 19:48
@jdragojevic any updates? :)

**Comment by jdragojevic** [comment] 2019-07-16 21:14
![image](https://user-images.githubusercontent.com/299270/61330124-ec4b7780-a7ec-11e9-9c3c-0f786ee26465.png)


I've got Fenix devices in iOS - guessing maybe a recent change to https://github.com/mozilla/application-services/issues/1125 resolved this.

**Comment by jonalmeida** [comment] 2019-07-17 00:27
Closing this issue since there's nothing for our QA to test here. Thanks Janet! ✨

**Closed** 2020-08-26 20:25 UTC
Labels: Feature:SendTab, P1, a-s, 🐞 bug, 🙅 waiting
