### ISSUE TITLE
Can't get location - permission is blocked despite being allowed

### ISSUE THREAD

**Issue by miklcct** [mozilla-mobile/fenix#28287] opened 2022-12-22 00:51 UTC
### Steps to reproduce

1. Open my website https://gbtt.uk/ on Firefox Android in Great Britain.
2. Click on the geolocation button on the query form.

### Expected behaviour

The location should be detected as long as there is GPS reception.

### Actual behaviour

The location is never returned. If in the process the app is switched away and back, the website shows error in getting location and the status bar shows location is blocked despite it was explicitly allowed.

The feature works on Chrome without problem.

### Device name

Samsung Galaxy A42 5G

### Android version

12

### Firefox release type

Firefox

### Firefox version

107.2.0

### Additional information

https://user-images.githubusercontent.com/2827264/209030842-ed3ec7ba-21f7-4c32-ab37-5bdf0af14a55.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22182)

**Comment by amocirean** [comment] 2023-01-16 12:00
Hi @miklcct , thank you for submitting the issue.
I was not able to reproduce the issue on the latest Nightly from 16th of January 2022 (110.0a1).
Tested on: Google Pixel 6 (Android 13), Samsung Galaxy S22 Ultra (Android 13), Samsung Galaxy A32 5G (Android 12).
Could you please try reproducing the issue on the latest Nightly Build?
Thanks!

**Comment by csadilek** [comment] 2023-01-25 17:09
Closing based on https://github.com/mozilla-mobile/fenix/issues/28287#issuecomment-1383945024 and the issue not being reproducible. Please re-open if this is still a problem.

**Closed by csadilek** 2023-01-25 17:09 UTC
Labels: 🐞 bug, needs:triage, qa-triaged
