### ISSUE TITLE
[Bug]: Pages are not displayed - desktop mode if the toggle was previously enabled (homescreen menu)

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#24162] opened 2022-03-09 10:50 UTC
### Steps to reproduce

1. From the Home screen, open the three-dot menu, and enable the "Desktop site" toggle.
2. Open a page and observe if it is opened as a desktop site.

### Expected behaviour

The opened page is opened as a desktop site.
The toggle is still enabled.

### Actual behaviour

The opened page is opened as a mobile site.
The toggle is not enabled.

### Device name

Sony Xperia

### Android version

6.0.1

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1, 99.0.0-beta.1

### Additional information

- Not reproducible on 98 versions.
- Not reproducible on: Huawei MediaPad M3 (Android 7), Samsung S10E (Android 10) , OnePlus 3A (Android 6.0.1).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19771)

**Comment by bigConifer** [comment] 2022-05-30 15:08
@sflorean Do you think it's independent from the other issues facing desktop mode?

When this ticket is not a dupe of #11552, the title should probably mention, that you're talking about the "Desktop site" toggle in the **home screen** menu.

**Closed** 2022-12-05 04:14 UTC
Labels: 🐞 bug, Feature:RequestDesktopSite, S3, needs:triage, wontfix
