### ISSUE TITLE
[Bug]Firefox for Android presents cached pages unless I specifically clear the cache.

### ISSUE THREAD

**Issue by gregg56** [mozilla-mobile/fenix#16155] opened 2020-10-24 00:21 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
load Firefox and visit a site such as oann.com.  On a subsequent day visit oann.com again and the cached pages from the previous visit will be presented instead of loading new pages.  I am forces to clear the cache daily to insure I get the latest pages.

### Expected behavior
I expect Firefox to load fresh pages from sites for every visit.

### Actual behavior
cached pages are loaded unti I manually clear the cache and THEN firefox will load new pages.

### Device information
Android LG G8 ThinQ Anrdoid Version 10
Firefox 81.1.5 
* Android device: ?
* Fenix version: ?

**Comment by s-ankur** [comment] 2020-10-24 09:48
Do you open these pages from collections?

**Comment by liuche** [comment] 2020-10-29 03:10
This sounds like it could be a dupe of #10417 which we are working on this sprint.

**Closed** 2020-12-18 06:31 UTC
Labels: needs:triage, 🐞 bug
