### ISSUE TITLE
[Bug] Highlighting text does not work properly and jumps all over the place. When you try to use your finger to highlight a particular sentence in a large paragraph of text, the highlighted area starts jumping around everywhere. Example: old.reddit.com comments. It's so bad that I am literally unable to highlight and copy sentences sometimes

### ISSUE THREAD

**Issue by MadridSpain** [mozilla-mobile/fenix#14884] opened 2020-09-09 12:01 UTC
## Steps to reproduce
1. Set Firefox Day to default settings, except that Automatic font sizing is turned OFF (the glitch can occur with font-sizing turned on, but it is more pronounced and easier to see when it is turned OFF).
2. Clear all data/browsing history/cookies/etc.
3. Go to any comment on the old version of reddit. This comment will do:
https://old.reddit.com/r/firefox/comments/gwquaj/firefox_devs_blatantly_ignoring_what_the/ft14y9z/
4. Pinch zoom in with your fingers. Try highlighting the first word in the comment, then highlighting the rest of the sentence. Most of the time it doesn't work properly. The highlighted text jumps all over the place and it's basically unable to highlight a precise word or sentence. For this glitch to work, you must be visiting the old.reddit version of reddit, as shown above. Try while signed out of your reddit account.
### Expected behavior
It should just highlight whatever parts of the text you highlight with your finger, just like all the old versions of Firefox.
### Actual behavior
When trying to highlight with your finger, the highlighted area acts irrationally, and jumps all over the webpage, making it hard to copy a precise word or sentence.
### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No.
### Can you reproduce in Chrome (or other non-Mozilla browser)?
No.
### Device information

* Android device: Samsung S8 (SM-G950FD Smartphone, latest version of Android operating system as of 2020/Sep/09)
* Fenix version: Firefox Day 80.1.2 (Build number 2015761283)

**Comment by MadridSpain** [comment] 2020-09-28 23:17
I have found an even better example:

http://ronpaulinstitute.org/archives/featured-articles/2020/september/28/question-the-science-go-to-gulag/

Just follow all of the above steps as I described them earlier and try highlighting and copying a sentence or two from somewhere in the middle of this article. it's nearly impossible.

**Comment by bb010g** [comment] 2020-12-13 04:01
Duplicate of #14539?

**Comment by ekager** [comment] 2020-12-18 05:50
Closing as dupe of #14539

**Closed by ekager** 2020-12-18 05:50 UTC
Labels: needs:triage, 🐞 bug

**Comment by theres-waldo** [comment] 2023-01-10 00:28
@MadridSpain do you still experience this issue in recent Firefox for Android versions? We suspect it has been fixed since the time of filing, but it would be good to confirm.
