### ISSUE TITLE
[Bug] long press back no longer opens history 

### ISSUE THREAD

**Issue by tomchiverton** [mozilla-mobile/fenix#14178] opened 2020-08-25 17:50 UTC
## Steps to reproduce
Open new tab 
Open gitlab.com
Click two links 
Long press back button 
### Expected behavior
History appears 
### Actual behavior
Nothing happens 
### Device information

* Android device: lg q6
* Fenix version: dunno. Help/about missing from menu

**Comment by cadeyrn** [comment] 2020-08-25 17:52
> Fenix version: dunno. Help/about missing from menu

Settings > About Firefox

If you're using Firefox 79 it's not a bug, the feature is not yet implemented in Firefox 79. But it's available in Firefox 80 and higher.

**Comment by kbrosnan** [comment] 2020-08-25 20:06
Closing as a duplicate of #1048

**Closed by kbrosnan** 2020-08-25 20:06 UTC
Labels: needs:triage, 🐞 bug
