### ISSUE TITLE
[Bug][a11y]: Talkback does not mention "Learn more" as a hyperlink in the wallpapers section

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#27317] opened 2022-10-06 19:45 UTC
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on
2. Open Settings > Homepage > Wallpapers
3. Tap on the "The new Independent Voices collection. Learn more" string.
4. Double tap on the "Learn more" hyperlink.

### Expected behaviour

3. "Learn more" is referred to as a hyperlink.
4. The link is opened in a new tab.

### Actual behaviour

3. Talkback does not mention "Learn more" as a hyperlink.
4. The link is not opened.

### Device name

Google Pixel 4

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

107.0a1

### Additional information

https://user-images.githubusercontent.com/48829350/194404558-91f526d7-d969-41be-afe1-3696b4da175f.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21752)

**Comment by Mugurell** [comment] 2022-10-07 07:31
Duplicate of https://github.com/mozilla-mobile/fenix/issues/27128, should be fixed in today's Nightly.

**Closed by Mugurell** 2022-10-07 07:31 UTC
Labels: 🐞 bug, access, S3, needs:triage, Feature:Wallpapers
