### ISSUE TITLE
Consider removing "Quit" feature

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#5865] opened 2019-10-08 20:15 UTC
As @sarentz has mentioned, the quit feature isn't something that aligns with really any other mobile app. It will likely go against user expectations, and we should consider removing it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13810)

**Comment by mikeGolf08** [comment] 2019-10-08 22:57
The feature needs to stay cause it is pretty handy and not common on other browser.

Is it possible to clear browsing data after closing the app via pressing home and clearing the multitasking view or after a time interval when app is in background?
I think it wasn't possible on older versions of Android because the app needed to be running to perform tasks.

**Comment by miladmaz12** [comment] 2019-10-08 23:25
Wouldn't removing quit feature make the "Clear browsing data on quit" counterproductive and unusable?

**Comment by nahuhh** [comment] 2019-10-09 16:29
The issue that I see with the feature (compared to fennec)

- Fenix = quit button disappears when "delete browsing data on quit" is disabled
- Fennec = quit button is persistent.

In my opinion, the fennec implementation makes sense, while the fenix implementation is.. confusing?

I think the best course of action is follow fennec's implementation = the quit button needs to be persistent. As in fennec, with "delete browsing data on quit" disabled, the quit button should kill the browser without clearing any data.

**Comment by st3fan** [comment] 2019-10-09 17:01
Not sure if that is true of Fennec .. it should only appear if the _clear data on exit_ (or similar named) is enabled.

**Comment by nahuhh** [comment] 2019-10-09 17:09
I stand corrected.. 
I have Fennec mobile (not the tv version) installed on androidtv os. It displays in "tablet" mode, where tabs etc are visible at the top like the desktop firefox.

Seems in "tablet" mode, the quit menu is persistent. 
On my phone "mobile", it is not.

**Comment by mikeGolf08** [comment] 2019-10-09 21:58
A clear button would be acceptable but the feature itself has to remain implemented because some want to delete specific browsing data only while keeping other which is not possible by using Private Mode all the time!

**Comment by Queuecumber** [comment] 2020-03-14 12:57
Right now in fennec if I swipe Firefox away using the recent apps it quits and if I have the option turned on, closes all my open tabs. In Fenix, if I swipe the app away, my tabs stay. This behavior should at least be consistent, e.g. fix Fenix so that it does a quit when swiped away in the recent apps menu. 

I agree that the quit button is a little weird and uncommon. There are other established ways to quit Android apps, swiping away as I mentioned or using the back button.

**Comment by kbrosnan** [comment] 2020-03-25 17:34
Swiping close the app does not return a unique signal to the app. To the App it looks like it has been killed in the background. To have the feature function in a consistent manner it requires some user action. Either something like Focus where there is a persistent notification or a button in the app.

**Comment by Queuecumber** [comment] 2020-03-25 20:02
Or you can have an option to let it remove the state when it's killed in the background for people who want that. Back button and swipe away are how you quit things on Android and you're breaking that flow as is. As I said it's also an unexpected change from current Firefox behavior.

**Comment by Phenix-Feedback** [comment] 2020-05-22 13:37
Any update on that request?

**Comment by SS1113** [comment] 2020-06-30 01:15
Please **do not** remove this feature! The quite button appears only when the "clear browsing data on quite s enabled", the button doens't even appear by default. It is such an useful feature why do you even wanna remove it?!

**Comment by XxAcielxX** [comment] 2020-07-30 18:40
> Or you can have an option to let it remove the state when it's killed in the background for people who want that. Back button and swipe away are how you quit things on Android and you're breaking that flow as is. As I said it's also an unexpected change from current Firefox behavior.

I also want this. Omg I hate hitting the Quit button to close my current session tabs.

It should be like Fennec, when you swipe away from Recent Apps Screen then all tabs should close. We have been used to this for so many years, now don't this with us please.

It's totally a privacy issue.

**Comment by FenixRevival** [comment] 2020-07-31 21:19
I fully agree with @XxAcielxX  this going against the default behaviour of Android. This _shouldn't_ be the case.

My suggestion I did in another issues was to:
* if user pin Setting made the option to clear tab while quitting: swiping should kill tabs
* if user didn't: swipe will do nothing (like todayà

**Comment by Queuecumber** [comment] 2020-09-03 15:51
Could even be a "Use quit button" checkbox on that settings page that is checked by default to account for both use cases, I think it's really easy to make everyone happy here

**Comment by jawz101** [comment] 2020-09-03 15:54
TBH, you could make that screen essentially be the equivalent of Firefox Focus/Klar, but allow some freedom to choose the types of content you want to disappear.

**Comment by gtg947h** [comment] 2020-09-13 14:09
> > Or you can have an option to let it remove the state when it's killed in the background for people who want that. Back button and swipe away are how you quit things on Android and you're breaking that flow as is. As I said it's also an unexpected change from current Firefox behavior.
> 
> I also want this. Omg I hate hitting the Quit button to close my current session tabs.
> 
> It should be like Fennec, when you swipe away from Recent Apps Screen then all tabs should close. We have been used to this for so many years, now don't this with us please.
> 
> It's totally a privacy issue.
> 
> **Edit 1**
> I'm not saying to remove the Quit Button, what I'm suggest is that:
> 
>     1. People who like to keep their session saved should use 'Close tabs on using quit button' option
> 
>     2. Those who like it old way, session should close when swipe close the browser. This should be the by default behaviour

THIS!

I hate persistent tabs/sessions with an unbridled, white-hot fury.  I don't use it on desktop browsers and I can't stand it on mobile browsers.  The only thing worse than having to specifically choose Quit is the iOS/Safari implementation of having to manually and individually close each tab before swiping away.

PLEASE bring back the old implementation where swiping away will clear the data if that option is selected.  Or at least an option to do do that.

**Comment by martin-schoettler** [comment] 2020-09-17 09:54
I have closed https://github.com/mozilla-mobile/fenix/issues/15149 as the topic is a duplicate of the discussion here. You may find my reasoning at https://github.com/mozilla-mobile/fenix/issues/15149#issue-703361075

**Comment by XxAcielxX** [comment] 2020-09-17 15:56
Why hasn't the close tabs instantly when swiping the Fenix away implemented? You guys are doing everything to please the users who don't want to close their tabs.

This feels like a discrimination.

**Comment by ekager** [comment] 2020-09-25 01:00
One option we could expose is adding a new option to auto close setting for "On Cold App Start" (or something different copy-wise) and just not restore tabs on startup if the user has selected that setting. cc @topotropic for UX feedback on that option

**Comment by iKnowLessThanYou** [comment] 2020-09-28 03:05
I'm not using the stupid quit button. Get Firefox back to how it used to be, it's really frustrating there's always so many tabs open when I want the exact opposite.

Fix your shit Firefox.

**Comment by liuche** [comment] 2020-10-22 00:39
A comment from @modb from #13227

> there could be a simple checkbox whether to remember them or not. For the rest it needs to be persisted throughout a session. This could be done by having a persistent notification in case a user chooses to clear data on quit, like mentioned before. I think this would be less of a bother to people than having to quit the app through the menu.

**Comment by ekager** [comment] 2020-12-17 19:42
See also https://github.com/mozilla-mobile/fenix/issues/11449

**Comment by jawz101** [comment] 2021-01-14 23:08
This was my thought.

![untitled_page](https://user-images.githubusercontent.com/14151703/104659811-40bf0400-56bd-11eb-9b27-c8c0a7421bfb.png)

**Comment by Queuecumber** [comment] 2021-04-10 23:17
@kbrosnan do you have any updates on the status of this issue? I think there are some really great suggestions in here from users for how this could be handled in a way that satisfies everyone

**Comment by crisalis2** [comment] 2021-05-19 04:00
> removing "Quit" feature

Sounds like a very bad idea. I use this feature regularly. I just randomly found this issue and it's left me concerned about the future.

>removing [...] feature

This should always be a big no, especially when retaining the feature in question entails no additional maintenance burden whatsoever.

**Comment by deveee** [comment] 2021-05-19 05:24
Personally, I still use FF 68.11 because newer version doesn't close tabs on exit.

**Comment by XxAcielxX** [comment] 2021-05-19 08:37
> > removing "Quit" feature
> 
> Sounds like a very bad idea. I use this feature regularly. I just randomly found this issue and it's left me concerned about the future.
> 
> > removing [...] feature
> 
> This should always be a big no, especially when retaining the feature in question entails no additional maintenance burden whatsoever.

We are not saying to remove the Quit button feature, but rather have both options. So people who like to keep their tabs and those (like me) who don't want tabs to restore on cold restart of the browser can be happy.

**Comment by gtg947h** [comment] 2022-12-11 11:30
"Swiping close the app does not return a unique signal to the app. To the App it looks like it has been killed in the background. To have the feature function in a consistent manner it requires some user action. Either something like Focus where there is a persistent notification or a button in the app is needed."

Those who want this feature restored (again I will note that this is how it *used to work!* This isn't something we want added, it's something that was *taken away*) don't care.  If the browser session has been open long enough to get auto-killed we probably just forgot to close it anyway.  We don't need or want nag notifications, or special close buttons, or four tabs trying to all reload themselves every time we start a browsing session.  

This issue not being addressed is what's keeping me still using the last pre-"upgrade" version of Fennec.  I see it keeps getting brought up again and again and yet the folks in charge seem to want to ignore it... "but if we give you an easier way to get rid of tab restore and close all your tabs then you might close all your tabs and not have them restored!"

Again, hitting the task switcher and swiping away is the convention for closing an app, just like hitting the red X box closes the program on Windows.  You're wanting everyone to go through special hoops just to close a session.  Why?

**Comment by boek** [comment] 2023-01-27 16:32
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813101

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-27 16:32 UTC
Labels: feature request 🌟, Feature:PrivateBrowsing, Feature:History, needs:UX-investigation
