### ISSUE TITLE
[Bug] Download Notification for Failed downloads never go away!

### ISSUE THREAD

**Issue by JakFrost** [mozilla-mobile/fenix#15487] opened 2020-09-28 03:57 UTC
## Steps to reproduce

1. Download a file from the Internet.
2. Watch the download fail.
3. Notification of Failed download appears in Notifications.
4. Expand multiple notifications (Drag Down).
5. Swipe Left to dismiss individual Failed Download Notifications.
6. Restart Firefox for Android.
7. Watch the same dimissed Failed Download Notifications return.
8. Force Stop the Firefox app.
9. Restart Firefox app.
10. Watch the exact same dismissed Failed Download Notifications return from zombie land.
11. Run for the hills away from zombie Failed Download Notifications and become a recluse.

### Expected behavior

1. Swipe Left to dismiss individual Failed Download Notifications.
2. Watch them disappear forever instead of reincarnate everytime the Firefox app is launched.

### Actual behavior

1. Dimissed Failed Download Notifications never disappear even after Force Stop and relaunch.
2. Failed Downloads do not show up in the Downloads list so they cannot be manually removed from there either.
3. Notifications for Downloads are actually turned Off but the Failed Download Notifications still show up anyway!

### Device information

* Android device: Google Nexus 6P (Huawei Angler) Android 8.1.0
* Fenix version: 81.1.1 (Build #2015764547), AC: 57.0.6, bdbd5ccfd, GV: 81.0.-20200917005511, AS: 61.0.13, Friday 9/18 @ 12:44 AM

### Pictures Below

![Firefox Failed Download Notification Bug - Notifications](https://user-images.githubusercontent.com/6331047/94389158-b3a76d80-0114-11eb-81c7-bdf1b44b003d.png)

![Firefox Failed Download Notification Bug - Download Notifications = Off](https://user-images.githubusercontent.com/6331047/94389162-b7d38b00-0114-11eb-9c73-d9520727a9cf.png)

![Firefox Failed Download Notification Bug - Downloads List Doesn't Show Failed Downloads](https://user-images.githubusercontent.com/6331047/94389184-c3bf4d00-0114-11eb-9c1b-bf9f710888f3.png)

![Firefox Failed Download Notification Bug - External Download Manager = Off](https://user-images.githubusercontent.com/6331047/94389187-c6ba3d80-0114-11eb-9a59-2adaddf47a02.png)

**Comment by JakFrost** [comment] 2020-09-28 03:59
### Version Information

![Firefox Failed Download Notification Bug - Firefox Version](https://user-images.githubusercontent.com/6331047/94389262-fff2ad80-0114-11eb-8a29-7208b649295c.png)

![Firefox Failed Download Notification Bug - Android Phone Info](https://user-images.githubusercontent.com/6331047/94389304-1c8ee580-0115-11eb-9d3a-bf9bffdfd785.png)

**Comment by JakFrost** [comment] 2020-09-28 04:01
### Add-ons

![Firefox Failed Download Notification Bug - Firefox Add-ons](https://user-images.githubusercontent.com/6331047/94389380-6081ea80-0115-11eb-8d49-72e87ca9f846.png)

**Comment by s-ankur** [comment] 2020-09-28 08:53
Still happens in Nightly as well

**Comment by Amejia481** [comment] 2020-09-28 21:00
This issue was already fixed in AC [59.0.0](https://github.com/mozilla-mobile/android-components/commit/dc3fff634b68e800d3bf216c248f7e6187745888). It should be Fixed in [beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) and [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix).

**Comment by softvision-miralobontiu** [comment] 2020-10-28 10:55
I was able to reproduce this issue on the 83.0.0-beta.2 build with Samsung Galaxy Tab S6 (Android10).

**Comment by Amejia481** [comment] 2020-10-28 13:46
> I was able to reproduce this issue on the 83.0.0-beta.2 build with Samsung Galaxy Tab S6 (Android10).

@softvision-miralobontiu would you mind sharing the link with which you were able to reproduce? I was trying to download the same file as the user [snowbros.zip](https://wowroms.com/en/roms/mame/snow-bros.-nick-and-tom/106840.html) shows in the screenshots but the download doesn't fail. Thanks in advance!

**Comment by softvision-miralobontiu** [comment] 2020-10-28 15:13
Hi Arturo!
I reproduced when pausing and resuming a download from https://www.thinkbroadband.com/download.
I cannot seem to reproduce it again, nor on Beta, nor on 10/28 Nightly builds.

**Comment by liuche** [comment] 2020-10-29 03:32
Let's dupe to #15527

**Closed by liuche** 2020-10-29 03:32 UTC
Labels: Feature:Download, Feature:Notifications, 🐞 bug
