### ISSUE TITLE
Support for Widevine EME DRM

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#1175] opened 2019-03-25 18:33 UTC
Existing EME work:

* [x] GV permission prompt before accessing EME media keys https://bugzilla.mozilla.org/show_bug.cgi?id=1620102
* [ ] what additional bugs are necessary?

### Why/User Benefit/User Problem
Users would like to be able to watch videos that use DRM.

### What / Requirements
Fenix has EME UI to play Widevine DRM videos.

* Gecko's EME UI requirements: https://docs.google.com/document/d/1O7mPFSW2AO2MxWM1t3CwHrwPEJ7THxHjgXWUG74JBAc/edit
* GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1340169
* ~~FFTV bug: mozilla~~mobile/firefox-tv#1698-

We do not need EME for Fenix MVP or the Fennec/Fenix transition because Fennec does not currently support EME. Fenix EME can wait until FFTV ships its EME UI first (mozilla-mobile/firefox-tv#1698).

### Acceptance Criteria (how do I know when I’m done?)
Users can watch YouTube and Amazon Prime videos that use Widevine DRM.

The following YouTube DRM video is a convenient test case for EME because it costs $0 (though you still need a credit card to "purchase" the video): https://www.youtube.com/watch?v=W6E7CGm12tA

**Comment by mcladyz** [comment] 2019-09-27 19:24
Widevine support would be great!

**Comment by mcladyz** [comment] 2019-11-05 20:42
> The following YouTube DRM video is a convenient test case for EME because it costs $0 (though you still need a credit card to "purchase" the video): https://www.youtube.com/watch?v=W6E7CGm12tA

How about [this one](https://bitmovin.com/demos/drm) for Widevine test instead? (Doesn't require an account)

**Comment by cpeterso** [comment] 2019-11-11 23:08
More GV bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1524091
https://bugzilla.mozilla.org/show_bug.cgi?id=1506924

**Comment by dbolter** [comment] 2020-02-24 18:14
Note: I think Firefox brand policy would want us to ask or notify the user when DRM is used (even if part of android system). Do we have any fenix Ux started on that front? (Is this the right issue for this topic)

**Comment by miketaylr** [comment] 2020-04-30 21:48
It looks like Starz relies on Widevine: https://github.com/webcompat/web-bugs/issues/52232#issuecomment-620563246

**Comment by ziddey** [comment] 2020-07-16 02:57
It's been implied above that permission needs to be granted for EME but the support is missing.

Can confirm that in the current android beta/nightly, widevine works swimmingly by setting `media.eme.enabled` to true and `media.eme.require-app-approval` to false in `about:config`.

**Comment by liuche** [comment] 2020-07-24 23:08
Hi QA, we want to restart this work, so could you test to see if the user's comment above^ allows playing DRM content, on Beta or Nightly with those settings updated?

Possible sites to test (from the comments in this issue):
- The following YouTube DRM video is a convenient test case for EME because it costs $0 (though you still need a credit card to "purchase" the video): https://www.youtube.com/watch?v=W6E7CGm12tA
- How about [this one](https://bitmovin.com/demos/drm) for Widevine test instead? (Doesn't require an account)

**Comment by ziddey** [comment] 2020-07-24 23:35
Ah, probably should've included some screenshots earlier:

![Screenshot_20200724-193108](https://user-images.githubusercontent.com/3846501/88442974-7e189800-cde4-11ea-8e07-69a220449e92.jpg)

![Screenshot_20200724-193141](https://user-images.githubusercontent.com/3846501/88443013-a7d1bf00-cde4-11ea-9c6f-ae783ffb57d7.jpg)

Firefox Beta 79.0.0-beta.8 (Build #2015752515)
Friday 7/17 @ 8:55 AM

**Comment by Diana-Rus** [comment] 2020-07-28 15:02
Hello, checked the following outcomes with Google Pixel 3 XL (Android 9) and Samsung Galaxy S9 (Android 8) on Nightly 7/27.

**Scenario 1**
- media.eme.enabled - true
- media.eme.require-app-approval - false
1.1 For https://bitmovin.com/demos/drm - error message is displayed "VIdeo decoder or demuxer had an error with the content(Playback video decoding error)"
1.2 For https://www.starz.com/us/en/play/58958 - error message is displayed "An unknown error occurred. Please try again"
**For this case the GV permission does not need to be present**

**Scenario 2**
- media.eme.enabled - true
- media.eme.require-app-approval - true
2.1 For https://bitmovin.com/demos/drm - detects that "No DRM" is present, audio and video work
2.2 For https://www.starz.com/us/en/play/58958 - informative message displayed, about missing WidevineCdm component

**Scenario 3 - Default Firefox Nightly Settings**
- media.eme.enabled - false
- media.eme.require-app-approval - true
3.1 For https://bitmovin.com/demos/drm - detects that the browser has no DRM, audio and video work
3.2 For https://www.starz.com/us/en/play/58958 - informative message displayed, about missing WidevineCdm component
**No GV permission prompt was present**

**Scenario 4**
- media.eme.enabled - false
- media.eme.require-app-approval - false
4.1 For https://bitmovin.com/demos/drm - detects that the browser has no DRM, audio and video work
4.2 For https://www.starz.com/us/en/play/58958 - informative message displayed, about missing WidevineCdm component

<details closed><summary>Scenarios Details</summary>

**Scenario 1**
1.1 For https://bitmovin.com/demos/drm - ![Screenshot_20200728-115051](https://user-images.githubusercontent.com/49859863/88668065-d1dbf780-d0ea-11ea-98d0-059e2c237d11.png)
1.2 For https://www.starz.com/us/en/play/58958 - ![Screenshot_20200728-115415](https://user-images.githubusercontent.com/49859863/88668104-da343280-d0ea-11ea-9868-b33bf775ff0a.png)

**Scenario 2**
2.1 For https://bitmovin.com/demos/drm - ![Screenshot_20200728-111329](https://user-images.githubusercontent.com/49859863/88667113-9e4c9d80-d0e9-11ea-906b-a1029eadfe6c.png)
2.2 For https://www.starz.com/us/en/play/58958 - ![Screenshot_20200728-111727](https://user-images.githubusercontent.com/49859863/88667101-9a208000-d0e9-11ea-94c2-903850cfbaf1.png)

**Scenario 3 - Default Firefox Nightly Settings**
3.1 For https://bitmovin.com/demos/drm - same outcome is present as for scenario 2
3.2 For https://www.starz.com/us/en/play/58958 - same outcome is present as for scenario 2

**Scenario 4**
4.1 For https://bitmovin.com/demos/drm  - same outcome is present as for scenario 2
4.2 For https://www.starz.com/us/en/play/58958  - same outcome is present as for scenario 2

</details>

Notes:
1. Will the GV issue be treated in this one? media.eme.require-app-approval when is set to true and media.eme.enabled is true, there is no notification or prompt about allowing or disallowing to play DRM content
2. Does the UI of Fenix be changed other than the Permission module (as described in the Google Doc from description)? Will there be other parts affected in Fenix?
3. Should the video eme keys be displayed when media.eme.require-app-approval is set to false, or in case from permission level, the user denies the api's request?

@liuche - as we discussed on slack, related to the youtube video, i did encounter some problems. I'll check to see for a video that will work in my country. I'll let you know about that.
I'll remove the qa-needed until further information is provided.

**Comment by ziddey** [comment] 2020-07-28 18:14
@Diana-Rus scenario 1 is the only relevant case. I'm assuming your test devices are able to play the bitmovin widevine test with Chrome?

On my end, I've confirmed working (current beta and nightly):
* oneplus 7t (Android 10) with widevine L3 (unlocked bootloader)
* essential ph1 (Android 10) with widevine L1

**Comment by cpeterso** [comment] 2020-07-28 18:30
Google has a streaming video test page for their "Shaka Player" that includes EME/DRM videos. The "Clear Key DRM" and "Widevine DRM" videos should all work in Firefox and Chrome on desktop and mobile. "Fairplay DRM" is only supported in Safari. "PlayReady DRM" is only supported in Edge (including Chromium Edge).

https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;panel=ALL_CONTENT;build=uncompiled

**Comment by Diana-Rus** [comment] 2020-07-29 18:04
Hi,
@ziddey - yes, the test devices are able to play the bitmovin widevine test using Chrome(84.0.4147.89).

@cpeterso  - thanks Chris, i've looked the videos from https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;panel=ALL_CONTENT;build=uncompiled with widevine DRM and clear key DRM

@liuche - could you please check the questions form above comment, thank you!!
Could you also look at the outcomes below?

Scenarios have been checked with Google pixel 3 XL (Android 9) and Samsung Galaxy S9 (Android 8) on Nightly 7/27
**Scenario 1 - media.eme.enabled - true and media.eme.require-app-approval - false**
- https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;panel=ALL_CONTENT;build=uncompiled

**A) Widevine DRM:**
- **Video 1 - Angel One (multicodec, multilingual, Widevine)** - audio and video plays correctly, 
- **Video 2 - Angel One (HLS, MP4, multilingual, Widevine)** - audio and video plays correctly, controls work(cancel, video progress bar, volume, full screen, ⋮ (More) option)
- **Video 3 - Angel One (HLS, MP4, multilingual, Widevine, single linear ad)** - ad is present,audio and video plays correctly, controls work(cancel, video progress bar, volume, full screen, ⋮ (More) option)
- **Video 4 - Sintel 4k (multicodec, Widevine)** - error message is displayed Shaka error MEDIA.VIDEO_ERROR
![Screenshot_20200729-194906](https://user-images.githubusercontent.com/49859863/88828935-94ec2f80-d1d4-11ea-904c-ab81942dd339.png)❗❗
Error description https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:3016
 This can be played in Chrome❗❗
- **Video 5 - Sintel 4k (multicodec, Widevine, ads)** - same error message is displayed but the ad plays(video and audio present for it)❗❗
 This can be played in Chrome❗❗
- **Video 6 - "Dig the Uke"by Stefan Kartenberg (audio only, multicodec, Widevine)** - audio plays correctly, controls work(cancel, video progress bar, volume, full screen, ⋮ (More) option)
- **Video 7 - Multi-DRM** - audio and video work correctly, controls work(cancel, video progress bar, volume, full screen, ⋮ (More) option) - the video seems to load more slowly than the rest of the cases
- **Video 8 - Multi-DRM, multi-key** - audio and video work correctly, controls work(cancel, video progress bar, volume, full screen, ⋮ (More) option) - the video seems to load more slowly than the rest of the cases
- **Video 9 - Multi-DRM, multi-key, multi-Period** - error message is displayed
![Screenshot_20200729-201528](https://user-images.githubusercontent.com/49859863/88831691-5f494580-d1d8-11ea-98b8-5a484c3cca6a.png) ❗❗
Error Description: https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6006
Same error message is encounter on Chrome as in Fenix❗❗
- **Video 9 - Tears of Steel (Widevine)** - audio and video work correctly, controls work(cancel, video progress bar, volume, full screen, ⋮ (More) option)
- **Video 10 - Multi DRM - 8 Byte IV** - audio and video work correctly, controls work(cancel, video progress bar, volume, full screen, ⋮ (More) option)
- **Video 11 - Multi DRM - MultiPeriod - 8 Byte IV** - audio and video work correctly, controls work(cancel, video progress bar, volume, full screen, ⋮ (More) option)
- **Video12 - Widevine - 16 Byte IV** -  audio and video work correctly, controls work(cancel, video progress bar, volume, full screen, ⋮ (More) option)
- **Video 13 - Widevine - 16 Byte IV - (mix of encrypted and unencrypted periods)** -  audio and video work correctly, controls work(cancel, video progress bar, volume, full screen, ⋮ (More) option)


**B) ClearKey DRM:**
- there is only one video for this and is not available-after tapping on it will displays informative message that "Browser does not support the required key systems."
This can be played in Chrome❗❗

**Comment by liuche** [comment] 2020-07-30 04:42
>     1. Will the GV issue be treated in this one? media.eme.require-app-approval when is set to true and media.eme.enabled is true, there is no notification or prompt about allowing or disallowing to play DRM content

Okay, I think this requires us to use the GeckoView APIs that exist for EME, and once we implement that permission, then the notification will show up.

> 
>     2. Does the UI of Fenix be changed other than the Permission module (as described in the Google Doc from description)? Will there be other parts affected in Fenix?

I don't think that we will need to change the Fenix UX, beyond showing the dialog asking the user to accept/reject.

> 
>     3. Should the video eme keys be displayed when media.eme.require-app-approval is set to false, or in case from permission level, the user denies the api's request?
> 

If the approval is set to false, or the user does not approve the api request, then I do not believe the key should show.

>     4. Are the error mentioned at scenario 1 supposed to happen?

Yes, I think we will need to do some further implementation on this issue, and then we will retest.

------

Thank you @Diana-Rus for the thorough testing, and helping us understand the current state of EME in Fenix. We will do some more work, and then re-request QA.

**Comment by liuche** [comment] 2020-07-30 04:47
Next steps here: 

After talking to Randall Barker from the FxR team, it sounds like this will require some AC work to trigger the EME notification and permissions.

We'll need to add and handle the `GeckoSession.PermissionDelegate.PERMISSION_MEDIA_KEY_SYSTEM_ACCESS` permission in [GeckoPermissionRequest](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequest.kt)

See the [FxR implementation](https://searchfox.org/mozilla-mobile/source/FirefoxReality/app/src/common/shared/org/mozilla/vrbrowser/browser/PermissionDelegate.java#185).

**Comment by kbrosnan** [comment] 2020-07-30 16:31
So this was broken on Nightly from July-17 by bz-1652474. Randal opened bz-1656289 to fix this, we should re-test when this is fixed.

**Comment by liuche** [comment] 2020-08-01 01:22
@kbrosnan this seems like it could be a good candidate for Hershey next sprint, what do you think? We'll need strings for the `require-app-approval` prompt though - if you know what that prompt should ask for, we can pass that on to @betsymi and get strings from her.

**Comment by kbrosnan** [comment] 2020-08-04 15:21
Randal's bug fixing EME on Android has been merged into mozilla-central. When we get a GV with a build id greater than 20200804000001 (2020-08-04-000001) this can be tested again.

**Comment by Diana-Rus** [comment] 2020-08-11 08:59
Hi, with Nightly 8/10 build that contains the eme enabling, the media.eme.enabled is set true as default in comparison with the last tested build.

- Created 4 new issues: #13445 this one I consider it major as you can't play the videos and marked it as S1 , #13463 , #13461 this one, the last one was clarified by @liuche how it should work and #13497 (mentioned in [comment](https://github.com/mozilla-mobile/fenix/issues/1175#issuecomment-665815122))

- Updated issue #13249 with results from the GV build - The clear key video from shaka player can't be played, in chrome the video can be played.

- Updated issue #13243 mentioned in [comment](https://github.com/mozilla-mobile/fenix/issues/1175#issuecomment-665815122), with results for latest Nightly build

- Verified with Samsung Galaxy S9 (Android 8), Google Pixel 3XL (Android 9) and Sony Xperia Z5 (Android 7)

@kbrosnan i understood from @liuche  that there is another eme issue that will be in a later GV build, do you know which one is it?

I'll remove the qa-needed until further information is provided.

**Comment by Diana-Rus** [comment] 2020-08-31 12:05
Hello @kbrosnan, @liuche , any news for this issue 😊?

**Comment by emilio** [comment] 2020-12-03 14:15
With https://github.com/mozilla-mobile/android-components/pull/9121 this works for me on my local build at least :)

**Closed** 2020-12-08 19:19 UTC
Labels: feature request 🌟, hershey, needs:ac, needs:gv

**Comment by LaurentiuApahideanSV** [comment] 2020-12-14 15:10
Verified as fixed on Firefox Preview Nightly 201214 (Build #2015781291)
### Devices used:
- Google Pixel 3 XL (Android 9)
- OnePlus 6T (Android 9)
