### ISSUE TITLE
[Bug]: Download Stops after closing its Tab in Private Window

### ISSUE THREAD

**Issue by RuthlessRuler** [mozilla-mobile/fenix#22395] opened 2021-11-10 05:42 UTC
### Steps to reproduce

1. Open 2 or more Private Tabs.
2. Start to download any large file in any one of the tab
3. Close the tab from which the download started once download begins

### Expected behaviour

The download should keep downloading in background until it is finished.

### Actual behaviour

The downloading stops as soon as tab closes.

### Device name

Poco X3

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

94.1.2

**Comment by RuthlessRuler** [comment] 2021-11-10 07:54
Update: it seems the download does happen in the background but the download notification is killed/removed.
Also, the files that are downloaded doesn't appear in the Downloads Tab. IDK if this intended, but it's should be implemented like Desktop version where Private windows Download are shown for the private session.

**Comment by SoftVision-LorandJanos** [comment] 2021-11-10 09:01
Hi @RuthlessRuler. Thanks for your report!
I managed to reproduce the issue you described.
However I wasn't sure either if it was intended or not this way.
I checked on Chrome to see if the behavior is the same, and it is.
@Amejia can you confirm if this is a bug or the intended behavior? Thank you!

**Comment by RuthlessRuler** [comment] 2021-11-10 10:41
@SoftVision-LorandJanos I checked with Brave, and the download progress notification is still there even after closing the tab.

Also some updates regarding the Download section:

![Screenshot_2021-11-10-15-48-36-301_org mozilla firefox](https://user-images.githubusercontent.com/20885012/141096276-c13cdfdc-0c9f-421c-98ab-8e3a73d372d4.jpg)
(In above ss, as u can see a download process is ongoing but not appearing in the download section)

![Screenshot_2021-11-10-15-56-24-387_org mozilla firefox](https://user-images.githubusercontent.com/20885012/141096356-d3c2b6d4-67bd-4fe9-ac08-ba5b752ce5cc.jpg)

(In this SS, the burgerking apk was downloaded in normal tab and Firefox Apk was downloaded in Private tab. The downloads have been accessed from Private Window (Private Tab-> Hamburger Menu->Download) So the files do appear only when they have completed downloading. Also, for some wierd reason the Private Downloads appear when accessed through regular window(Regular Tab-> Hamburger Menu-> Download) but disappear when Firefox is Restarted.)


I will try to make a Video for easier understanding of this behaviour.

**Comment by marcel263** [comment] 2021-11-10 14:09
Related #20444 download gets killed when closing custom tab, also the background audio when an unrelated tab is open containing it

**Comment by RuthlessRuler** [comment] 2021-11-10 15:22
Is it also intended that when Playing background audio, if we change the tab or switch to other app, the audio pauses?

**Comment by Amejia481** [comment] 2021-11-17 15:14
> Hi @RuthlessRuler. Thanks for your report! I managed to reproduce the issue you described. However I wasn't sure either if it was intended or not this way. I checked on Chrome to see if the behavior is the same, and it is. @amejia can you confirm if this is a bug or the intended behavior? Thank you!

Yes, this is the intended behavior there is feature that we have to integrate to match desktop behavior that is to show a dialog to inform the user https://github.com/mozilla-mobile/fenix/issues/18160

**Comment by SoftVision-LorandJanos** [comment] 2021-11-17 15:27
Thank you @Amejia481!
Based on this information, I will close this ticket.

**Comment by RuthlessRuler** [comment] 2021-11-17 17:43
Hey. @Amejia481 
 Chrome doesn't kill download when tab is closed. It kills download when session is closed. (Ie the private sessions has any one tab active). 

But in FF mobile, suppose I have 2 tabs open in private session, and I start downloading a big file from tab 1 and then close tab 1. The notification for the progress of download disappears in FF whilst the download progress taking place in Background as my private session is still active (tab 2 is running)

In Chrome, the notification doesn't get killed in such scenarios.

**Comment by Amejia481** [comment] 2021-11-17 22:29
Sorry for the misunderstanding. I see, we are actually canceling the download as soon as the tab is closed. I think we need to match FF desktop behavior and keep downloading until the last private tab is closed and then show [this dialog](https://github.com/mozilla-mobile/fenix/issues/18160) to make users aware.

**Comment by mavduevskiy** [comment] 2021-12-23 21:15
The bug has been fix. A [feature](https://github.com/mozilla-mobile/fenix/issues/18160) to show a prompt before closing the last private tab is undergoing testing.

**Closed by mavduevskiy** 2021-12-23 21:15 UTC
Labels: 🐞 bug, Feature:PrivateBrowsing, Feature:Download
