### ISSUE TITLE
 Tabs on navtab like on 'devices' : label:ChromeOS:97

### ISSUE THREAD

**Issue by fvignals** [mozilla-mobile/fenix#23478] opened 2022-01-30 21:11 UTC
## App: Firefox 96.2.0

My screen is a 13.3", the resolution: 1920x1200, unlike Chrome, doesn't display a nav tab.
Note: the device include a keyboard and mousepad, the 'nav tab button' is boring.
The same on all ChromeOS devices ? including labtops, desktops ?
[suggest]: open a chromeOS branch event it's build from Android branch.

Regards.

**Comment by PandoraHayami** [comment] 2022-01-31 03:07
Do you refer to a Tablet UI similar to the desktop browser which Chromium browsers have? If it is, would be a duplicate of #14921.

**Closed** 2022-01-31 20:12 UTC
Labels: needs:triage

**Comment by fvignals** [comment] 2022-02-05 20:25
Yes a duplicate of https://github.com/mozilla-mobile/fenix/issues/14921 https://github.com/mozilla-mobile/fenix/issues/2344
I searched for.
In my mind: under ChromeOS (Tablet resolution and up) and Tablet Android(resolution) you should use the android engine but the computer UI (and later some adjustements) for less work.
