### ISSUE TITLE
[Bug] Desktop site option not remembered when page has to be reloaded

### ISSUE THREAD

**Issue by Rodze** [mozilla-mobile/fenix#11552] opened 2020-06-13 14:01 UTC
## Steps to reproduce
1 open a new tab for www.theverge.com (or any website)

2 switch the option to request desktop site and wait for it to fully load 

3 open and browse on other tabs enough so when you come back to the verge tab it has to be reloaded and rendered again (I guess it depends on how much ram the device has).

### Expected behavior
Site is reloaded in desktop version.

### Actual behavior
Site is reloaded in mobile version, with the desktop site option enabled visually and when you try to disable it it reloads the page still in mobile version and remains visually enabled, preventing you from loading the desktop version at all.

### Device information
* Android device: Galaxy s9, Android 9
* Fenix version: Nightly 200613 06:01 (Build #2015745971)

![Screenshot](https://user-images.githubusercontent.com/499237/84570640-24449d00-ad65-11ea-9837-a9c5022bf4d3.jpg)UNITO-UNDERSCORE!20200613-104536!UNITO-UNDERSCORE!Firefox Nightly!
![Screenshot](https://user-images.githubusercontent.com/499237/84570641-260e6080-ad65-11ea-8529-82059c048c43.jpg)UNITO-UNDERSCORE!20200613-105112!UNITO-UNDERSCORE!Firefox Nightly!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2087)

**Comment by TrianguloY** [comment] 2020-08-17 08:03
I was going to report this, but after a search I saw it was already reported.

Another easier way to reproduce it:
1) Open a new tab (any url) and check 'desktop site'. Wait for the tab to fully load.
1) Press the android recent apps/multitask button and close the browser [alternatively go to android settings of the browser and press on force close]
1) Reopen the browser, go back to the previous tab.

* The tab will be reloaded in mobile mode, and the desktop site toggle will be unchecked.

**Comment by AndiAJ** [comment] 2020-11-03 15:09
Managed to repro @TrianguloY 's [STR](https://github.com/mozilla-mobile/fenix/issues/11552#issuecomment-674728003) on the latest Nightly Build 201103 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by Oymate** [comment] 2021-03-16 11:34
Duplicate? https://github.com/mozilla-mobile/fenix/issues/15352

**Comment by Rodze** [comment] 2021-09-13 04:14
> See: #17373 This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

It's still broken.

**Comment by SamuelMezger** [comment] 2022-03-12 11:40
Still relevant.

**Comment by lumnn** [comment] 2022-04-06 11:00
This can be reproduced with fewer steps on https://messenger.com

1. https://messenger.com
2. Enable Desktop Site toggle to show desktop version
3. Reload

At this point browser shows mobile version, while the toggle is still enabled.
Disabling toggle refreshes page, toggle disables, and mobile version is shown

**Comment by Oymate** [comment] 2022-05-27 13:17
Fixed for me

**Comment by sflorean** [comment] 2022-05-30 10:36
> This can be reproduced with fewer steps on https://messenger.com
> 
> 1. https://messenger.com
> 2. Enable Desktop Site toggle to show desktop version
> 3. Reload
> 
> At this point browser shows mobile version, while the toggle is still enabled. Disabling toggle refreshes page, toggle disables, and mobile version is shown

I was able to reproduce this scenario after closing/ reopening Firefox on Nightly 5/30 with Samsung A32 (Android 11) .

**Comment by TheBrokenRail** [comment] 2022-11-26 18:05
No, this issue is still a problem (although probably a duplicate of #15352). And it would be teally nice if Mozilla would actually fix this bug instead of ignoring it for *years*.

**Comment by Noob729** [comment] 2022-11-26 18:20
I don't know who thinks stale bot ever was a good idea...

**Comment by Noob729** [comment] 2022-11-26 18:25
Hello @sflorean  
How about confirming the issue, in order to prevent stale bot from messing with it?  
(I reported the issue as #25338)

**Comment by Perdu** [comment] 2022-11-28 09:31
As I reported in #27972, this also happens when Firefox remains open but tab gets unloaded for memory management.

**Comment by csadilek** [comment] 2022-12-22 21:00
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807154

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2022-12-22 21:00 UTC
Labels: 🐞 bug, Feature:RequestDesktopSite, S2, pin, qa-triaged
