### ISSUE TITLE
[Bug] unable to save images. when attempting to share images through external channels they display as binary files

### ISSUE THREAD

**Issue by agselig** [mozilla-mobile/fenix#17581] opened 2021-01-22 08:38 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Device information

* Android device: OnePlus 7T oxygen is 10.0.15.HD65AA
* Fenix version: 84.14

**Comment by cadeyrn** [comment] 2021-01-22 08:45
I have a OnePlus 7T Pro and _can_ save images. So please provide exact steps to reproduce.

**Comment by agselig** [comment] 2021-01-22 08:47
When pressing and holding on an image in most cases it will simply cause the screen to vibrate. On the occasion that I can get the dialogue that I previously have been able to recieve without issue when I attempt to save the image and later share it through apps such as WhatsApp or Twitter it is sent as a binary file

**Comment by sflorean** [comment] 2021-07-31 10:19
@agselig this is still reproducible for you? Tested on latest Nightly with Pixel 3 and couldn't reproduce it. Can you provide also a page, where you encounter this?

**Comment by sflorean** [comment] 2022-02-03 13:42
Closing this due to lack of extra information and given the fact that the issue is not reproducible on our side. Please comment/ open a new bug if the issue occurs again.

**Closed by sflorean** 2022-02-03 13:42 UTC
Labels: 🐞 bug, Feature:Download, wontfix, qa-triaged
