### ISSUE TITLE
Delete browsing data - "Browsing history and site data" is a combined entry

### ISSUE THREAD

**Issue by B0ycee** [mozilla-mobile/fenix#18104] opened 2021-02-21 17:32 UTC
-Step to reproduce:

Under Firefox Daylight, navigate to settings and select "Delete browsing data".  Second entry is labelled "Browsing history and site data".

-Expected behaviour:

"Browsing history" and "Site Data" to be separate items and not grouped.

Or

"Site data" to be grouped with "Cookies" (as Windows Firefox).

-Actual behaviour:

Single item "Browsing history and site data" appears in list and only listed method to clear "site data".  Therefore user must sacrifice all browsing history in order to clear "site data".

-Background

Clearing browsing data (& cookies) with exception to browsing history is quite a common expectation/user action.  This is supported by Windows Firefox having a specific settings section labelled "Cookies & site data" that allows only "Cookies and site data" (as well as "Cached web content") to be cleared.  This is in addition to the comparative/comprehensive "Clear history" section.

-Possible mitigation:

Documentation updated to explain to what "site data" specifically refers to within Firefox Daylight and therefore what data remains if user wishes to keep browsing history.

**Comment by cadeyrn** [comment] 2021-02-21 21:56
Duplicate of #14402.

**Comment by jonny0000** [comment] 2021-02-22 07:18
Thanks for improving[.](https://gamesapkworld.com/call-of-duty-mod-apk/)

**Comment by mcarare** [comment] 2021-02-22 08:25
@B0ycee Thank you for your report. This has already been requested [here](https://github.com/mozilla-mobile/fenix/issues/14402) so I am closing this as a duplicate.

**Closed by mcarare** 2021-02-22 08:25 UTC
Labels: needs:triage
