### ISSUE TITLE
[Bug] Impossible to go back to the results page after going to some pages.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2167] opened 2019-04-30 15:06 UTC
## Steps to reproduce
Search Chopsticks Lincoln Ne on Bing, Google, etc
Go to the restaurant's website
Try to go back to the results page

### Expected behavior
Fenix goes back to the results page (as does Chrome)

### Actual behavior
Fenix got stuck on the restaurant's website and fail to go back to the results page.

### Device information
* Android device: 8.0
* Fenix version: 1.0.1918

**Comment by yoasif** [comment] 2019-04-30 17:20
Was able to reproduce this by going to https://www.chopstickslincoln.com from a SERP on a Pixel 2.

**Comment by vesta0** [comment] 2019-05-03 16:48
This looks like a big. It works on Fennec.

**Comment by ekager** [comment] 2019-07-16 18:13
Can also reproduce in RB. Going to file a GV bug to investigate

**Comment by ekager** [comment] 2019-07-16 18:16
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1566551

**Comment by cpeterso** [comment] 2019-07-25 16:56
This is a core Gecko bug that also affects desktop Firefox. I moved Emily's bug 1566551 to the Gecko team. This bug is probably not a P1.

**Comment by kbrosnan** [comment] 2020-08-26 05:08
This usecase has a workaround of using the long press back button to get the tab history. Going to close this based on that behavior. We can pick up the Gecko change when that is prioritized.

**Closed by kbrosnan** 2020-08-26 05:08 UTC
Labels: Feature:MainMenu, b:web-content, needs:gecko, needs:investigation
