### ISSUE TITLE
[Bug] Tab history of normal browsing tab shows up in on PWA -> long press back button

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13934] opened 2020-08-19 18:40 UTC
## Steps to reproduce
Open a pwa
long press back button

### Expected behavior
Not sure, nothing maybe?

### Actual behavior
Tab history of a random regular tab shows up

### Device information

* Android device: Asus Zenofone
* Fenix version: Fenix Nightly

**Comment by LaurentiuApahideanSV** [comment] 2020-08-20 09:22
I can confirm that the issue is reproducible on the latest Firefox Preview Nightly 200820 (Build #2015759027).
### Devices used:
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)

**Comment by ekager** [comment] 2020-09-18 20:04
Same happens on custom tabs

**Comment by LaurentiuApahideanSV** [comment] 2020-09-23 09:33
Verified as fixed on Firefox Preview Beta 82.0.0-beta.1 (Build #2015765523).
### Devices used:
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)

**Closed by LaurentiuApahideanSV** 2020-09-23 09:33 UTC
Labels: Feature:Gesture, Feature:History, Feature:PWA, S2, eng:qa:needed, sourpatch, 🐞 bug
