### ISSUE TITLE
FNX-12210 ⁃ Export as PDF

### ISSUE THREAD

**Issue by bravoecho** [mozilla-mobile/fenix#11302] opened 2020-06-06 15:47 UTC
### What is the user problem or growth opportunity you want to see solved?
Export the page as PDF. It's also important that links become clickable in the resulting PDF.

### How do you know that this problem exists today? Why is this important?
* Access content offline
* Share content in a portable format
* Archive premium subscription content that one has paid for
* Printing to PDF - when possible - is no substitute, because the output is virtually always mangled in some way, whereas the original Firefox's PDF export offers a much more usable output

### Who will benefit from it?
Everyone who needs to have their content in portable format for work, study and personal reasons.

**Comment by cadeyrn** [comment] 2020-06-06 17:26
Duplicate of #3709.

**Closed** 2020-08-11 03:43 UTC
Labels: needs:triage
