### ISSUE TITLE
[Bug] Fix intermittent UI test failure - testDownloadPrompt

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#7303] opened 2019-12-20 00:02 UTC
intermittent failure on the UI testDownloadPrompt.
latest Firebase:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6337539131377699799/executions/bs.d8b346fae11c9ec0/testcases/1/test-cases

https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8780672757579522534/executions/bs.fcbd2f6bff5d9239/testcases/1/logs

**Comment by AaronMT** [comment] 2020-01-09 19:02
Getting to this now. 

There seems to be an issue with the way I am deleting a downloaded file and re-running the test. Subsequent runs of the test crash with.

```Kotlin
        // Clear Download
        runBlocking {
            for (file in Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).listFiles()) {
                if (file.isFile && (file.name.startsWith("rabbit"))) {
                    file.delete()
                }
            }
        }
```


```Kotlin
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-7
    Process: org.mozilla.fenix.debug, PID: 27482
    kotlin.KotlinNullPointerException
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.useFileStreamScopedStorage(AbstractFetchDownloadService.kt:443)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.useFileStream$feature_downloads_release(AbstractFetchDownloadService.kt:406)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$1.invoke(AbstractFetchDownloadService.kt:339)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$1.invoke(AbstractFetchDownloadService.kt:68)
        at mozilla.components.concept.fetch.Response$Body.useStream(Response.kt:79)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.performDownload$feature_downloads_release(AbstractFetchDownloadService.kt:335)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.startDownloadJob$feature_downloads_release(AbstractFetchDownloadService.kt:289)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService$onStartCommand$1.invokeSuspend(AbstractFetchDownloadService.kt:205)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
`

**Comment by jonalmeida** [comment] 2020-01-10 15:47
> (@jonalmeida - what is useFileStreamScopedStorage expecting?)

This is a private method call, and the only entry points seem to be from starting a download, resuming, and trying again.

I'm not familiar with this side of the codebase, but @sblatz had recently made changes here so I'm guessing he would know.

**Comment by AaronMT** [comment] 2020-01-10 20:20
@sblatz do you have any recommendations for what could be causing this crash? 

Again I'm just trying to clean up my download in the tearDown

**Comment by liuche** [comment] 2020-03-31 00:32
Hey @AaronMT this crash actually looks like a legitimate crash, not just a test failure. Could you file with the steps to reproduce? https://sentry.prod.mozaws.net/operations/fenix/issues/7488883/?query=is:unresolved%20KotlinNullPointerException

**Comment by liuche** [comment] 2020-05-11 16:15
@AaronMT I see you're assigned here, are you actively working on it or should we clear the assignment?

**Comment by AaronMT** [comment] 2020-05-11 16:57
I think I saw @kglazko re-enable this last week. The test hasn't ran in a while but maybe it's fixed now? (@kglazko ?) re: https://github.com/mozilla-mobile/fenix/pull/10407

**Comment by Amejia481** [comment] 2020-05-25 14:21
Yes, we enabled the test some weeks ago. We haven't seen any more occurrences. Otherwise please re open it again if need :)

**Closed by Amejia481** 2020-05-25 14:21 UTC
Labels: P1, b:crash, eng:automation, intermittent-test, 🐞 bug
