### ISSUE TITLE
when open camera in browser use default front camera

### ISSUE THREAD

**Issue by enieber** [mozilla-mobile/fenix#15421] opened 2020-09-25 13:03 UTC
## Site with issue and any steps to reproduce

https://davidwalsh.name/demo/camera.php

### Expected behavior

When open camera in mobile app the default camera is front

### Actual behavior

When open camera in mobile app the default camera is backside

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)

no

### Can you reproduce in Chrome (or other non-Mozilla browser)?

In Chrome the camera open in front after open the same link

### Device information

* Android device: 9
* Fenix version: 81.1.1 (Build #2015764545)

**Comment by LittleAngelwings** [comment] 2020-09-25 23:53
In Nightly it will be used the front cam. Testet with

Nightly 200925 06:01 (Build #2015765937)
AC: 61.0.20200923190103, 50960c843
GV: 83.0a1-20200922094538
AS: 63.0.0

**Comment by liuche** [comment] 2020-10-15 00:25
Dupe of #10748, will be in Firefox 82 which will release next week.

**Closed by liuche** 2020-10-15 00:25 UTC
Labels: needs:triage
