### ISSUE TITLE
FNX-12708 ⁃ [Bug] Tabs counter displays some  icon before displaying the number of tabs while adding a new tab

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11728] opened 2020-06-18 12:19 UTC
## Steps to reproduce
1. Close all open tabs
1. Open a website 
1. Click the tab counter to open the new Tabs Tray and add a new tab
1. See some icon pop before displaying the number of tabs (I think it's the emoticon symbol ":)" )

• Please see the attached video (ZIP file)

### Expected behavior
Should just display a number

### Actual behavior
Displays an icon (I think it's the emoticon symbol ":)" )

### Device information
* Android device: **Motorola One Power, Android 10**.
* Fenix version:  **`Nightly 200617 18:01`**.

[video.zip](https://github.com/mozilla-mobile/fenix/files/4798455/video.zip)

**Comment by mcarare** [comment] 2020-06-18 12:25
Duplicate of https://github.com/mozilla-mobile/fenix/issues/11672.

**Closed** 2020-08-11 04:45 UTC
Labels: 🐞 bug
