### ISSUE TITLE
[Feature Request] Import/Export bookmark as HTML file

### ISSUE THREAD

**Issue by Domiuns** [mozilla-mobile/fenix#12953] opened 2020-07-26 12:57 UTC
### What is the user problem or growth opportunity you want to see solved?
I think with this function the browser becomes better and more flexible

### How do you know that this problem exists today? Why is this important?
Much browser have this function, and desktop version have this important feature

### Who will benefit from it?
All user who don't use sync

Hi, I have been using Firefox for many years and the mobile version has always been deprived of this convenient feature.

**Comment by cadeyrn** [comment] 2020-07-26 13:04
Duplicate of #417.

**Comment by ekager** [comment] 2020-07-26 14:32
Closing for #417

**Closed** 2020-08-28 23:01 UTC
Labels: needs:triage
