### ISSUE TITLE
[Bug] Top Sites labels have too low contrast

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14602] opened 2020-09-02 05:00 UTC
## Steps to reproduce

1. Open home

### Expected behavior

Top sites labels should use a darker gray or black to improve contrast. Edge does a better job here. 

### Actual behavior

Top Sites text is small and hard to read. 

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by cadeyrn** [comment] 2020-09-02 06:38
Duplicate of #13850.

**Closed** 2020-09-02 17:29 UTC
Labels: needs:triage, 🐞 bug
