### ISSUE TITLE
FNX-12914 ⁃ Allow the user to access the QR scanner more easily

### ISSUE THREAD

**Issue by vaporwave9** [mozilla-mobile/fenix#11913] opened 2020-06-24 19:41 UTC
### What is the user problem or growth opportunity you want to see solved?
When I access the QR scanner on Fenix I have to click the address bar, then wait for the keyboard to fully extend and reorientate myself where the scan button is.

### How do you know that this problem exists today? Why is this important?
Exists today because I use Fenix Nightly builds and the UI location for the QR button is really suboptimal from the start.

[Screenrecorder-2020-06-24-21-51-16-365.zip](https://github.com/mozilla-mobile/fenix/files/4827636/Screenrecorder-2020-06-24-21-51-16-365.zip)

A scan QR button should be more prominent on the main window, rather than submenus and pop-outs.
Make it optional in settings and rather track who enables it?

https://github.com/mozilla-mobile/fenix/issues/1857

If you are really concerned if people will use it, then make it visible!

### Who will benefit from it?
Power users, neurotypicals who get irritated by cascading menus, QR enthusiasts and people who don't know yet how great this feature works to share links more easily.

**Comment by hakkikaancaliskan** [comment] 2020-06-24 23:18
Duplicate of #11829

**Comment by vaporwave9** [comment] 2020-06-25 11:20
Yes please continue in the other thread.

**Closed** 2020-08-11 05:13 UTC
Labels: needs:triage
