### ISSUE TITLE
[Bug] The microphone is available in the search bar only when Google is set as default search engine

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#18578] opened 2021-03-22 10:02 UTC
## Steps to reproduce
1. Set the defaut search engine to Google.
2. Open a new tab and observe if the microphone is available in the search bar.
3. Set the default search engine to a different search engine; I tried bing.com, and duckduckgo.com.
4. Open a new tab and observe if the microphone is available in the search bar.

### Expected behavior
The microphone is displayed regardless of the search engine set as default.

### Actual behavior
The microphone is  available only when google.com is set as default.

### Device information
* Device vendor / model and Android version: Samsung Galaxy Note (Android 9), OnePlus 5T (Android 10)
* Firefox for Android version: 3/22 Nightly, 87.0.0-beta.6, and 87.0.0-rc.1
* The microphone is available in widget

![search](https://user-images.githubusercontent.com/40694158/111972333-05e6ab80-8b06-11eb-8302-34437a2ccef5.png)

**Comment by Mugurell** [comment] 2021-03-22 15:17
This is how it was originally implemented in https://github.com/mozilla-mobile/fenix/issues/13766.
A possible motive would be that for actually inferring the search terms from speech we are using a Google service which will show this screen:

<img src="https://user-images.githubusercontent.com/11428869/112012808-2af11380-8b32-11eb-98ca-e57576d3fb37.png" width="33%" />

which maybe wouldn't bode well with other search services.

Asking for a confirmation from UX since there are no clear specs about this in the original ticket.

**Comment by kbrosnan** [comment] 2021-03-22 17:32
Duplicate of #15348

**Closed by kbrosnan** 2021-03-22 17:32 UTC
Labels: Feature:Search, Feature:Toolbar, S2, needs:UX-feedback, needs:triage, 🐞 bug
