### ISSUE TITLE
[Crash] Crash at launch on Lenovo yt3-x90l

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#4142] opened 2019-07-18 09:10 UTC
## Steps to reproduce
Reported by a community volunteer: https://github.com/mozilla/firefox-preview-bughunting-campaign/issues/521

1. Launch Firefox Preview
2. Immediately crash with Android report system

[logcat](https://gist.github.com/Doc73/015e61bb94c1f7f71b0c10a764f012de)
### Expected behavior
Launch app.
### Actual behavior
Crash at launch
### Device information

* Android device: Lenovo yt3-x90l, Android 6.0.1
* Fenix version: "Nightly 190714 (but even all the previous ones for about a week)"

note: I cannot reproduce it and don't have the specified device.

**Comment by ekager** [comment] 2019-08-09 01:30
Dupe of https://github.com/mozilla-mobile/fenix/issues/4338

**Closed by ekager** 2019-08-09 01:30 UTC
Labels: S3, b:crash, 🐞 bug
