### ISSUE TITLE
[Bug] The exact same web page is opened more than once when opening it from a collection

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3926] opened 2019-07-08 15:21 UTC
## Steps to reproduce
1. Launch Fenix.
2. Open more web pages.
3. Create a collection with more web sites.
4. Open that collection few times.
### Expected behavior
If the exact same website from a collection(or same collection) is already opened, when opening all the tabs from a collections, there should not be duplicates.
### Actual behavior
Even if the exact web site is already opened, when opening the same tab from a collection it is duplicated.
### Device information

* Android device: **`Google Pixel XL(Android Q Beta 4).`**
* Fenix version: **`7/8`**.

**Comment by ekager** [comment] 2019-07-08 15:39
Currently this is the "correct" behavior. We restore a duplicate session with a new unique ID. It would be difficult for us to tell if a session already exists with the exact back/forward history, and if the user has changed any of the session state, we probably shouldn't treat it as the "same" session anymore.

**Comment by ekager** [comment] 2019-08-01 04:51
I'm not sure what to do with this ticket because it's currently working as intended. I'm going to close it for now because I know UX is working on a collections redesign

**Closed by ekager** 2019-08-01 04:51 UTC
Labels: 🐞 bug
