### ISSUE TITLE
[Bug] Pwa keep on crashing on re opening after minimizing it

### ISSUE THREAD

**Issue by parthasaradhie** [mozilla-mobile/fenix#15110] opened 2020-09-15 14:21 UTC
##Logs
 [Crash Logs gist](https://gist.github.com/parthasaradhie/701b0c0ec82a42351e295148a186e74c) 

## Steps to reproduce
Add any PWA (i took twitter as an example) 
open once let it load and minimize the PWA then open it again using PWA icon.. vola it crashes... attached gif and logs for the same 

![20200915_194404](https://user-images.githubusercontent.com/12638462/93221962-fb7cdb00-f78b-11ea-9a9e-9158d39d651f.gif)

### Expected behavior
Open the PWA normally

### Actual behavior
PWA is crashing everytime i reopen while minimizing

### Device information
OnePlus 5t - Android 10

* Android device: OnePlus 5t - android10
* Fenix version: 80.1. 3

**Comment by parthasaradhie** [comment] 2020-09-15 15:00
a for of this fenix https://github.com/fork-maintainers/iceweasel/releases  doesn't have this issue at all

**Comment by ekager** [comment] 2020-09-15 23:17
Closing as dupe of https://github.com/mozilla-mobile/fenix/issues/15116

**Closed by ekager** 2020-09-15 23:17 UTC
Labels: Feature:PWA, b:crash, 🐞 bug
