### ISSUE TITLE
FNX-3383 ⁃ [Bug] Visual Bug: Text overlaps in private mode

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#10235] opened 2020-04-27 13:29 UTC
## Steps to reproduce
Any time you are on a website in private mode, just click on the Url-bar. As long as you haven't accepted/denied on the "Searchresults in Private Mode? [Y/N]", you should see the bug.

### Expected behavior
The text should not overlap. One of those sentences should probably be moved downwards, to the search engines it belongs to.

### Actual behavior
Text overlaps. See attatchment.
![1](https://user-images.githubusercontent.com/59611881/80377623-0e4d4c80-888b-11ea-8c7f-bc0698480bd5.jpeg)

### Device information
* Android device: Samsung Galaxy S9
* Fenix version: 4.3.0

**Comment by mcarare** [comment] 2020-04-27 21:33
Duplicate of https://github.com/mozilla-mobile/fenix/issues/9550, marked as fixed in nightly.

**Closed** 2020-08-10 19:39 UTC
Labels: Feature:PrivateBrowsing, 🐞 bug
