### ISSUE TITLE
add some quick action items on home screen

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12271] opened 2020-07-04 07:07 UTC
### What is the user problem or growth opportunity you want to see solved?
Currently to access history, bookmarks, add ons, synced tabs,quit browser we have to click the 3 dot menu and then the items...how about the adding the icons to home screen in a single row...

The Firefox branding could be moved a bit to the top which will align with private tab button and then utilize a single row between the branding logo and top sites to place icons of history, bookmarks, add ons synced tabs and quit browser.

### How do you know that this problem exists today? Why is this important?
This will avoid multiple clicks and easily accessible from home screen itself.

### Who will benefit from it?
All users

![Screenshot](https://user-images.githubusercontent.com/58127841/86507123-1c58a580-bdc5-11ea-96cd-a062a6523e3b.jpg)UNITO-UNDERSCORE!20200704-123549~2!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3049)

**Comment by amkcpu** [comment] 2020-07-04 08:16
I would love this feature, making accessing these menu items faster and more discoverable.
Though I personally don't mind where the icons should be placed, could also be below the top sites or even below collections - I guess that is something UX has to figure out.

**Comment by sheikh-azharuddin** [comment] 2020-07-04 08:23
It should be placed between the branding and top sites...reason is I have some screenshots in various cases where people have add too many top sites 3-4 rows and collections too...in those cases the quick access feature may hide and an additional scrolll will be required since top sites and collection are dynamic and users are free to add as many as they want....
Since this will a single fix row it should be placed on top for true easy access and easily noticeable

**Comment by sheikh-azharuddin** [comment] 2020-07-04 08:27
Btw I am good in html coding ....so is it possible to get the html code of the homepage so that I can modify and share mock screenshot?

**Comment by SS1113** [comment] 2020-07-05 11:07
This could be such an useful feature. I never thought about it! Great @sheikh-azharuddin. I'm thinking developers will consider it. Let's see.


I think shortcut for Bookmarks, history, add-ons, and synced tabs coud be placed on the top of Top Sites and below the Firefox Browser logo as you are already saying since to access them frequently they need a permanent place as if we go on adding top sites the shortcuts the place of Bookmarks, history, add-ons will move further to the bottom.

**Comment by sheikh-azharuddin** [comment] 2020-07-05 11:21
Home screen currently has 5 icons in a row for top sites
Quick feature row will have 5 icons aligned with top sites icon...
History, bookmark, synced tabs, add-ons and quit browser
The quit browser icon feels weird... It should be a power button icon

**Comment by sheikh-azharuddin** [comment] 2020-07-05 11:23
hello saipan
can i get html version of the homepage to create some mock pages....

**Comment by SS1113** [comment] 2020-07-05 11:25
Just imagine if you accidentally clicked the Quit button while selecting others shortcuts. I don't think a Quit button should be added. Perhaps any new shortcut could take its place. Or just the spacing could be increased between them to match with the Top Sites margin.

**Comment by SS1113** [comment] 2020-07-05 11:33
@sheikh-azharuddin 

> can i get html version of the homepage to create some mock pages....

I don't think the homescreen is an HTML document. I'm not a developer so I could be wrong. Though I do have some basic knowledge about several programming language including HTML, Java, C++ etc... But I cannot comment on what homescreen is made of.


I have heard one of the developers say that it is made of native code or so and it cannot be customised by extension like Firefox browser on desktop a few years ago used to do before Quantum release.


I do have an idea where you can browse the code of Fenix. I think you can browse the code in the master branch of Fenix. Give it a try. It should be the front and center on Fenix repository home page. I'll also try to browse it.

**Comment by sheikh-azharuddin** [comment] 2020-07-05 11:36
In that case maybe settings icon....

**Comment by SS1113** [comment] 2020-07-05 11:40
Here @sheikh-azharuddin this is what I found. O think it is written in **Kotlin language** (a language based on JAVA, IIRC).

![IMG_159394910699198](https://user-images.githubusercontent.com/42088907/86531852-4ccb3d00-beb4-11ea-9312-ff3c68f9a91c.jpg)

**Comment by SS1113** [comment] 2020-07-05 11:47
> master branch link please....

It should be at the front

Go here: https://github.com/mozilla-mobile/fenix
And click view code and master branch is the selected by default.

![Fotor_159394960573229](https://user-images.githubusercontent.com/42088907/86531950-56a17000-beb5-11ea-93d2-e711658d2a7b.jpg)

**Comment by SS1113** [comment] 2020-07-05 11:49
> In that case maybe settings icon...

Yeah, this could definitely work!

**Comment by sheikh-azharuddin** [comment] 2020-07-05 11:50
Thanks saipan... 🙂

**Comment by SS1113** [comment] 2020-07-05 11:56
@sheikh-azharuddin Fenix is based on Android Components. So perhaps, if you couldn't find anything in Fenix you may find something in a-c repo: https://github.com/mozilla-mobile/android-components.

**Comment by sheikh-azharuddin** [comment] 2020-07-05 12:00
Thanks saipan again.. During my school and college days i learned c, c++, java,. Net, html... Then i got a job in support related work and lost all my development skills... Only html is being used here and there so I know that but don't remember those programming languages... Guess i have to learn again 😅
No problem I love challenges👻😈

**Comment by SS1113** [comment] 2020-07-05 12:05
I'm tagging one of the developers from the UX team: @brampitoyo can you help us? Do you think that having a row containing Bookmarks, history, add-ons, synced tabs, etc. At above the Top Sites could be an useful feature? For context, please see the issue description and its below following comments.

**Comment by SS1113** [comment] 2020-07-05 12:07
@sheikh-azharuddin 

>Guess i have to learn again

Yeah, let's go! Best of luck with it!

**Comment by brampitoyo** [comment] 2020-07-08 04:35
@SS1113 @sheikh-azharuddin Yes. Those information could potentially be helpful.

In this sprint and the next, my colleague @apbitner is looking to make the most useful and frequently-accessed types of content easily accessible on the homescreen.

**Comment by yoasif** [comment] 2020-07-11 17:10
See also https://github.com/mozilla-mobile/fenix/issues/6437

**Comment by ShatteredPixel** [comment] 2020-07-16 12:09
@sheikh-azharuddin it's me **@SS1113**. I have deleted the previous GitHub account. Please let's be friends again.

P.S. Sorry developers. It's the only way I can contact them. Hope you'll forgive me. Thanks!

**Comment by sheikh-azharuddin** [comment] 2020-07-16 13:08
I am glad you are back....

**Comment by maverick74** [comment] 2020-07-23 23:00
I must confess I like a lot current Firefox home screen with it's tab-like access to bookmarks. It's easy and intuitive!

**Comment by Imold** [comment] 2020-09-02 15:36
#12941 is the better option I don't want to access my bookmarks from the home page, I want my bookmarks to be the home page.
I don't use firefox for android as my main way to browse the web, I use it when have my phone but not my pc. So for me bookmarks are critical and collections are useless.

**Comment by cadeyrn** [comment] 2020-09-19 08:39
Duplicate of #12065.

**Comment by boek** [comment] 2023-01-31 16:56
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814170

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-31 16:56 UTC
Labels: feature request 🌟, Feature:HomeScreen
