### ISSUE TITLE
[Bug] Fullscreen videos have a bottom margin when "Scroll to hide toolbar" is disabled

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#15040] opened 2020-09-13 08:22 UTC
## Steps to reproduce

1. Ensure "Scroll to hide toolbar" is disabled.
2. Open a video (e.g. from www.youtube.com) and enter full screen mode.

### Expected behavior

The video is in full screen mode.

### Actual behavior

The video has a bottom margin, presumably due to a regression from #14989.

![](https://user-images.githubusercontent.com/45960387/93013661-18bf7700-f5dd-11ea-92b5-345370bb886b.jpg)

### Device information

* Android device: Oppo Reno 2
* Fenix version: Nightly 200913 06:02 (Build #2015763635)

**Comment by evilpie** [comment] 2020-09-13 10:19
Sounds similar to #14974.

**Comment by eliserichards** [comment] 2020-09-15 21:51
Closing as a duplicate of #14974

**Closed by eliserichards** 2020-09-15 21:51 UTC
Labels: needs:triage, 🐞 bug
