### ISSUE TITLE
add show TLS information for sites in lock button in bar

### ISSUE THREAD

**Issue by minutesinch** [mozilla-mobile/fenix#14900] opened 2020-09-09 18:31 UTC
### What is the user problem or growth opportunity you want to see solved?
users can't see sites use which version of TLS, encryption and etc!
### How do you know that this problem exists today? Why is this important?
i cant see ant information about TLS just show secure connection , and  its important because users must see all site information and avoid them from store information in insecure sites
### Who will benefit from it?
all users

**Comment by cadeyrn** [comment] 2020-09-09 18:35
Duplicate of #8400.

**Comment by kbrosnan** [comment] 2020-09-09 18:57
Closing as a duplicate

**Closed by kbrosnan** 2020-09-09 18:57 UTC
Labels: needs:triage
