### ISSUE TITLE
[Bug] ClassCastException org.mozilla.gecko.util.GeckoBundle cannot be cast to java.lang.String GeckoView.Autofill

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#15011] opened 2020-09-11 23:33 UTC
Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1671137 

Fenix Nightly 82

https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9553031/?query=ClassCastException

```
ClassCastException

org.mozilla.gecko.util.GeckoBundle cannot be cast to java.lang.String 
   org.mozilla.gecko.util.GeckoBundle in getString at line 3
    org.mozilla.gecko.util.GeckoBundle in getString at line 4
    org.mozilla.geckoview.Autofill$Node$Builder in <init> at line 11
    org.mozilla.geckoview.Autofill$Support in addNode at line 5
    org.mozilla.geckoview.Autofill$Support in handleMessage at line 2
    org.mozilla.gecko.EventDispatcher$2 in run at line 1
    android.os.Handler in handleCallback at line 743
    android.os.Handler in dispatchMessage at line 95
    android.os.Looper in loop at line 150
    android.app.ActivityThread in main at line 5621
    java.lang.reflect.Method in invoke
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller in run at line 794
    com.android.internal.os.ZygoteInit in main at line 684
```

* Android device: ALE-L21 
* Fenix version: 82 Nightly

**Comment by ranaaditya** [comment] 2020-09-12 08:51
can i work on this issue @liuche ?

**Comment by liuche** [comment] 2020-10-16 01:17
Seeing probably ~150 crashes per day on release from sentry: https://sentry.prod.mozaws.net/operations/firefox/?query=is%3Aunresolved+geckobundle&statsPeriod=14d

Duped a report that indicated this being in Fenix 81 as well.

**Comment by ekager** [comment] 2020-12-09 23:02
Looks like this was fixed 1 month ago in GV.

**Comment by test491** [comment] 2021-02-24 13:16
followed Steps to reproduce from given above  [bugzilla #1671137](https://bugzilla.mozilla.org/show_bug.cgi?id=1671137)

not reproducible:

* version: 86.1.1
* version: 87.0.0-beta.1 (Build #2015795065) AC: 73.0.0, 69a800e47 GV: 87.0-20210222154334 AS: 71.0.0
* version: Nightly 210224 (Build #2015795113) AC: 73.0.20210223143117, 05f3e3cc7 GV: 87.0a1-20210222084406 AS: 71.0.0

**Comment by mariansima** [comment] 2021-08-30 08:03
Could not reproduce this issue on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29

**Comment by sflorean** [comment] 2021-08-30 14:58
Based on the comments above, I will close this.

**Closed by sflorean** 2021-08-30 14:58 UTC
Labels: 🐞 bug, b:crash, wontfix
