### ISSUE TITLE
Port the "Add to Firefox" Android share menu features from Fennec to Fenix.

### ISSUE THREAD

**Issue by smartfonreddit** [mozilla-mobile/fenix#8323] opened 2020-02-11 21:45 UTC
The Android phone has _Firefox Nightly_ (Fennec) and _Firefox Preview Nighty_ (Fenix).  

Fennec adds an entry to Android's share menu called "Add to Nightly". 

![20200211_131855](https://user-images.githubusercontent.com/10663730/74280490-7e5b2600-4cd1-11ea-9bc8-529b19dd4c2a.png)

The "Add to Nightly" entry is a Swiss army knife for sharing content. You can open a 3rd party app and share a link to another device with "Add to Nightly". Open Twitter, share a post, Android share menu opens, tap "Add to Nightly". It opens a small popup asking if you want to Send Link to Another Device, Bookmark link, or to open link in Nightly.

![Screenshot_20200211-132411_Firefox Nightly](https://user-images.githubusercontent.com/10663730/74281136-bf076f00-4cd2-11ea-90e2-8948973e3e69.png)

This makes it easy to send links to other devices because you don't have to manually open the 3rd party link in Firefox first to then send it to another device. That popup lets you do it with a single tap while outside of Firefox.

In comparison, Fenix's share menu lacks those options and will only open the link in Fenix. You will then have to dig into Fenix UI to send the link to another device.

The proposal is to make Fenix's Android share menu entry function like Fennec's.

**Comment by critical-bug** [comment] 2020-03-13 05:22
I'm using this feature to send links I found in SNS app to read them later in PC.

**Comment by rohit-gohri** [comment] 2020-04-12 06:31
The send to other device feature was highly used by me almost everyday. Since Firefox Beta updated to fenix I have had to open links in Firefox and then share it to my other devices.

**Comment by VinnikPavel** [comment] 2020-04-18 21:26
It was awesome feature. It, definitely, need to be implemented.

**Comment by klemens** [comment] 2020-05-03 16:53
This is a probably duplicate of #1523.

**Comment by KayzzenD** [comment] 2020-05-08 20:24
This feature is very useful. I think that like most people who know this feature, without a doubt use it frequently 😄.

**Comment by TReKiE** [comment] 2020-06-04 05:25
Like the comments above, I use this feature multiple times per day.  However, since the feature has to be re-created for Fenix, it would be great if it were improved.

For example, to share a link, you press Share, Add to Firefox, Send to other devices, and then select the device.  When you have more than 3 devices, you get a separate pop-up list.  Unfortunately the order of devices in this list is not consistant, so you can't rely on muscle memory.

As 99% of the time I'm sending links from my phone to my desktop Firefox to look at, it would be great if this list stayed in the same order, or even better, allowed a device to be pinned to the initial Add to Firefox share menu to make it even easier to use.

**Comment by kbrosnan** [comment] 2020-08-07 16:47
Duplicate #1523

**Closed by kbrosnan** 2020-08-07 16:47 UTC
Labels: S2, feature request 🌟, needs:triage
