### ISSUE TITLE
[Bug] Attempting to access/Close a private tab causes issues with closing Normal tabs the New Tab tray

### ISSUE THREAD

**Issue by karan-kamat** [mozilla-mobile/fenix#18879] opened 2021-04-08 16:53 UTC
## Steps to reproduce
1. Enable "Use new Tabs Tray" in secret settings
2. Open a new private tab
3. Attempt to access it multiple times
4.  Attempt to close it
5. Go to standard tabs
6. Attempt to close tab there

### Expected behavior
Private tabs get closed
Normal tabs get closed

### Actual behavior

Private tabs do not close
Normal tabs do not close until the tab tray is closed(though the number of tabs shown in the header denotes the number which should be there)

### Device information

Samsung Galaxy M51
Android 11 with One UI Core 3.1
Firefox Nightly 210408 14:26
Build #2015803443
 
Related issue: #18878 

![nightly-close-tabs](https://user-images.githubusercontent.com/59926956/114066153-07132900-98b9-11eb-8742-d0c3c8e7a207.gif)

**Comment by VitalyVPinchuk** [comment] 2021-04-26 14:51
Hello
Is it still relevant?
I couldn't reproduce it with Xiaomi Mi9T Pro.
@karan-kamat

**Comment by sflorean** [comment] 2021-04-29 12:44
I wasn't able to reproduce with the following devices, on latest Nightly build & following the steps:
- LG G7 Fit (Android 8.1)
- Samsung Note 10 (Android 11)

@karan-kamat please try again, some fixes were landed and it is possible that this is not reproducible anymore.

**Closed** 2021-04-29 12:52 UTC
Labels: needs:triage, 🐞 bug
