### ISSUE TITLE
Create a baseline for measuring crashes

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#4452] opened 2019-08-01 15:40 UTC
This is a Q3 goal identified by Engineering: To create a baseline that gives us an accurate picture of measuring this key metric. We noticed this was a gap before MVP. The only baseline we had was comparison with Fennec, which according to @sarentz was not accurate. 

Details to be filled out by @liuche and @sarentz

**Comment by liuche** [comment] 2019-08-01 21:35
Assigning myself so I can fill this out.

**Comment by liuche** [comment] 2019-08-29 21:00
Sentry
Google Play Store (might be a dupe of what is in Sentry)
Crash rate from @kbrosnan: https://docs.google.com/spreadsheets/d/1eRfHR0wgeosaix8y_9LQiJE9qR77cbfQ5agMKJYIZVo/edit#gid=0

**Comment by kbrosnan** [comment] 2019-08-29 21:39
Updated the sheet with the most recent info. 

My interest was making as similar comparison to Fennec (org.mozilla.firefox) and Fenix (org.mozilla.fenix) as possible. Below is the email I sent out when I released the sheet.

>  For Firefox Preview I compared the number of daily crashes reported in [Sentry](https://github.com/mozilla-mobile/focus-android/wiki/Crash-Reporting-with-Sentry) to the [Google Play active installs](https://support.google.com/googleplay/android-developer/answer/7003402#active_devices).
For Firefox for Android I compare the number of Crashes reported via telemetry to the Google Play active installs. We eventually want to have a [crashes per 1000 usage hours](https://missioncontrol.telemetry.mozilla.org/#/) like the rest of the products.

**Comment by liuche** [comment] 2019-09-24 02:51
We're adding a crash count in #235, which will establish the baseline for native + exception crashes. Would that be sufficient for monitoring a baseline, in a non-manual way?

**Comment by cpeterso** [comment] 2019-09-25 19:40
> We're adding a crash count in #235, which will establish the baseline for native + exception crashes. Would that be sufficient for monitoring a baseline, in a non-manual way?

SGTM. From the user's perspective, there is no difference between a native crash and an uncaught exception. 😄 Having separate counts for crashes and exceptions might be nice, but if there is a spike in one or the other, we should see it as we're monitoring Socorro's and Sentry's top crashes. 📈

**Comment by liuche** [comment] 2019-10-01 18:05
Closing as fixed by #235

**Closed** 2019-10-01 18:05 UTC
Labels: must
