### ISSUE TITLE
[Bug] Can't queue links from other apps

### ISSUE THREAD

**Issue by bcosell** [mozilla-mobile/fenix#14752] opened 2020-09-04 23:37 UTC
## Steps to reproduce

In my email or twitter or instagram or anywhere [other than FF], if I open a URL it *immediately* switches to FF and opens the tabs

### Expected behavior

That the requested URLs would be queued [somewhere I never knew how that worked :)] and only present themself when I explicitly opened FF
### Actual behavior

FF opens immediately, dragging me away from what I was doing.

### Device information

* Android device: ?   
   Samsung Galaxy Tab A 10.1" tablet

* Fenix version: ?

 I don't know exactly what "fenix" is but this is the new Firefox "daylight" release [if there's a place in FF to find the version number it has eluded me]

**Comment by clientenq** [comment] 2020-09-05 00:11
Since it is by design to _immediately_ follow up on user request when opening an app this sounds more like a feature request.

**Comment by amkcpu** [comment] 2020-09-05 08:18
Duplicate of #470.

**Comment by meztesso** [comment] 2020-09-13 09:35
The feature was in the old Firefox. I hope the tab queuing will be avaible again asap

**Comment by borisjoffe** [comment] 2020-09-16 22:41
Yea, it seems like they removed the best features of mobile Firefox (tab queue, extension support, speed, etc) and provided no way to opt out or delay upgrading until they're there.

Time to check out Chrome, Opera, and Edge again.

**Closed** 2020-09-16 23:47 UTC
Labels: needs:triage, 🐞 bug
