### ISSUE TITLE
Favorites not schowing icons[Bug]

### ISSUE THREAD

**Issue by macer22** [mozilla-mobile/fenix#8301] opened 2020-02-11 10:30 UTC
Favorites not schowing icons on start page,
i checked the sites on pc firefox and the sites clearly 
have the icons in it.

Mi 8
newest nightly preview from playstore

**Comment by sv-sdeiac** [comment] 2020-02-11 12:20
Hi @macer22, can you provide us some steps to reproduce your issue? Maybe a screenshot/video with your problem? 
Also, what is your exact device/android?
If you think that we need additional information regarding your problem, please don't hesitate to inform us, thanks.

**Comment by cadeyrn** [comment] 2020-02-11 12:40
There is only one step to reproduce: open the bookmarks in the library. The bookmarks don't have favicons at all, only the first character of the bookmark title in a colored box.

**Comment by sv-sdeiac** [comment] 2020-02-11 12:50
I am partially able to reproduce your results @cadeyrn. Indeed, some links from the list have only the first character as an icon but also, a lot of links have a specific icon.

Device:
- Samsung Galaxy S8 (Android 9);
- Motorola Moto G6 (Android 8).

Build:
- Nightly 2/11 #20420610.

**Comment by cadeyrn** [comment] 2020-02-11 13:31
Ah, right. That was my mistake. The bookmarks I tested have also no favicon in the history, because the favicons are too small for Fenix. I can confirm it works for other bookmarks.

**Comment by macer22** [comment] 2020-02-12 12:57
Can you make that fenix take what ever size it is and resize it to fit as favicon? Better pixelated favicon than colored pink box with a T on it or not?




On Tue, Feb 11, 2020 at 2:31 PM +0100, "Sören Hentzschel" <notifications@github.com> wrote:












Ah, right. That was my mistake. The bookmarks I tested have also no favicon in the history, because the favicons are too small for Fenix. I can confirm it works for other bookmarks.

**Comment by ekager** [comment] 2020-04-17 22:43
Closing for #7992

**Closed by ekager** 2020-04-17 22:43 UTC
Labels: needs:triage, 🐞 bug
