### ISSUE TITLE
FNX-4496 ⁃ Cannot install beta builds on Firefox nightly 78 & beta 77 on android

### ISSUE THREAD

**Issue by ybhmr4s11** [mozilla-mobile/fenix#10719] opened 2020-05-17 22:45 UTC
Install V78 nightly or 77 beta (has stable version in extension list)

Try to install beta build(for testing else what the use of using test builds right?)
It download instead of installing.
Cannot manually install from addon manager page in Firefox for mobile.

UBO Beta builds should be available for testing in testing versions or in case of a bonked build when it only way is to revert to a previous version
Also Should beta version not be default in beta and nightly to file bug reports

https://github.com/uBlockOrigin/uBlock-issues/issues/1042

@gorhill @ekager @bbinto @@pocmo @abodea @csadilek @Amejia481 @kbrosnan @kbrosnan 
@mheubusch @vesta0  @lime124
Can this be fixed please so can find and file issues
Regards
Jeff

**Comment by kbrosnan** [comment] 2020-05-27 04:56
Pinging several users is not an acceptable action for this project. Issues will be triaged as there is free time to look at them. Please do not do this again.

This is a dupe of #5315

**Closed** 2020-08-11 01:32 UTC
Labels: Feature:WebExtensions, needs:triage, 🐞 bug
