### ISSUE TITLE
[Bug] LoginsStorageException fatalUsing DatabaseLoginsStorage without unlocking first

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#7832] opened 2020-01-21 18:30 UTC
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/7099604/?query=is:unresolved

This is related to login autofill code in AC.  It appears to be a concurrency issue, where we are interleaving lock and unlock calls from different threads.  We should investigate usages of `AsyncLoginsStorage` and make sure that they are all accessing it in a thread safe way.

**Comment by liuche** [comment] 2020-01-24 00:07
if you're actively working on this do you want to assign yourself @Baron-Severin ?

**Comment by ekager** [comment] 2020-01-24 00:37
Looks like same bug with STR in https://github.com/mozilla-mobile/fenix/issues/7344

**Comment by Baron-Severin** [comment] 2020-01-24 01:48
> Looks like same bug with STR in #7344

I haven't been able to reproduce #7344 yet.  Seems like this fix should cover it as well, but 🤷‍♂.

**Comment by Baron-Severin** [comment] 2020-02-03 14:05
Merged a fix in https://github.com/mozilla-mobile/android-components/pull/5709

QA Note: I haven't managed to reproduce this locally, we'll need to keep an eye on crash reports to see if this fix is effective.

**Comment by AndiAJ** [comment] 2020-02-24 15:32
Hi @Baron-Severin , I've made a quick check on the latest **`Nightly Build #20550606 from 02/24`** and the crash from [#7344](https://github.com/mozilla-mobile/fenix/issues/7344#issuecomment-590385263) is still reproducible. ☺️

**Comment by ekager** [comment] 2020-02-26 07:04
I'm going to close this for #7344

**Closed by ekager** 2020-02-26 07:04 UTC
Labels: E5, P1, needs:investigation, 🐞 bug
