### ISSUE TITLE
[Bug] Deleted history still show up as search suggestions

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#8531] opened 2020-02-19 14:22 UTC
# Steps to reproduce

1. Enter a query and visit it.
2. Close the tab.
3. Quit the app via **Main Menu > Quit** (make sure **Browsing history** in **Delete browsing data on quit** is enabled).
4. Reopen Firefox Preview Nightly, and type the first few letters of the query.

In addition, manually clearing history then quitting the app via the Android recent apps list also reproduces this behavior.

1. Enter a query and visit it.
2. Close the tab.
3. Delete browsing history via **Main Menu > History > Delete history**.
4. Close the app via the Android recent apps list (swipe to close).
5. Reopen Firefox Preview Nightly, and type the first few letters of the query.

# Expected behavior

Deleted history gets deleted permanently, and does not show up as search suggestions.

# Actual behavior

The previously entered query, despite being cleared from history (it does not show up in history), still shows up as a search suggestion. The only way to remove this suggestion is to quit the app *another* time.

![](https://user-images.githubusercontent.com/45960387/74842928-19a16a80-5366-11ea-85bc-0148239c59a6.gif)

# Device information

* Android device: Oppo Reno 2, Android 9
* Fenix version: Nightly 200219 06:01 (Build #20500607)

**Comment by abodea** [comment] 2020-02-20 10:57
I was able to reproduce this issue on the latest Beta build 4.0,0-RC1 with Google Pixel 3a XL(Android 10).

**Comment by liuche** [comment] 2020-02-24 17:11
This looks like a regression - we should do a quick investigation if this is a quick fix. If not, will check w/ @vesta0 to see if this should block Beta Migration first build.

**Comment by sblatz** [comment] 2020-02-24 18:21
After a discussion among the team it sounds like an AC bug. Essentially it sounds like however history storage is marking items for deletion is not respected by the search suggestions.

A few other helpful notes:
* When I sit on the history screen for like 10 seconds after pressing delete, the suggestion does NOT show up. My guess is that some system is coming through and cleaning up the "shouldDelete" items so that even if I query through search it's not actually there.
* If I then run the `deleteEverything` again (like once the user visits the home screen) it will delete the item properly and I can search without it showing up.

It sounds like the "shouldDelete" flag (I'm assuming we're setting something like this) is not being respected by search suggestions

**Comment by grigoryk** [comment] 2020-02-24 19:11
I've reproduced this locally - specifically, if I visit `https://www.reddit.com/r/climbing`, delete history, an offending "search result" is suggested - specifically, `https://www.reddit.com` - so, just the origin.

Looking at what's in the `places.sqlite`, I see that the `moz_places`, `moz_historyvisits` etc are all empty, but `moz_origins` has the domains visits prior to deletion - and they're ending up in the suggestions.

`deleteEverything` a-c API that is called when history is deleted in fenix ends up here:
https://github.com/mozilla/application-services/blob/92b042dac34fcecb3816f67122bcbfa1dbd01bfc/components/places/src/storage/history.rs#L273

... which isn't obviously wrong - we do seem to be wiping `moz_origins` there as well, on a condition that at first glance _appears_ to be fine. (delete all origins that aren't present in moz_places).
However, contents of `moz_origins` seem to be left intact after a first call to this function. Calling it the second time does wipe `moz_origins` as well.

Perhaps there are some wrong assumptions being made about transaction isolation? Digging more...

**Comment by grigoryk** [comment] 2020-02-25 01:08
This should be fixed once https://github.com/mozilla/application-services/issues/2693 makes its way into Fenix builds.

**Comment by liuche** [comment] 2020-02-25 18:47
Since this is already in release, we aren't going to block 4.0 on this (due to lots of moving pieces) and can pick it up in a subsequent release.

**Comment by ekager** [comment] 2020-02-29 00:12
We've updated to [as-0.53.0 in AC](https://github.com/mozilla-mobile/android-components/pull/6110) and according to their changelog this change should be included! Let's test it!

**Comment by sv-sdeiac** [comment] 2020-03-02 07:59
Verified as fixed using the latest version of Firefox Preview Nightly 3/2 #20620607.
Now, the previously entered query is not anymore saved.

Devices:
- Motorola Moto G6 (Android 8);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel 3 (Android Q).

**Closed by sv-sdeiac** 2020-03-02 07:59 UTC
Labels: Feature:History, S2, eng:qa:needed, needs:triage, 🐞 bug

**Comment by raketenolli** [comment] 2022-09-28 20:26
In Firefox 105.1.0 this seems to not be fixed.
