### ISSUE TITLE
[Bug] Instant crash on firefox nightly latest update

### ISSUE THREAD

**Issue by JamesGreeners** [mozilla-mobile/fenix#14491] opened 2020-08-30 13:58 UTC
## Steps to reproduce
1. Install latest update (Nightly 200830)
2. Try opening browser
### Expected behavior
The browser to open and function properly
### Actual behavior
The browser crashes instantly, have tried restarting phone, deleting and reinstalling and force stopping the browser.
### Device information
Huawei Mate 20 Lite
* Android device: Huawei Mate 20 Lite Android 10
* Fenix version: 200830

**Comment by hwinnemoe** [comment] 2020-08-30 14:07
Please use https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information to create a log for your crash, zip it up and attach it here. Also make sure to use `adb logcat -c` before reproducing the crash to clear anything else in the log. This will help the developers to find the cause for your crash.

**Comment by ale82to** [comment] 2020-08-30 14:22
same issue here!
it's something regarding database folder under fenix android data folder.
I ve got root, deleting database folder (wich erase topsites, collection and login) solve the issue.
but adding a new topsite, close fenix and then reopen issue is back.

**Comment by hwinnemoe** [comment] 2020-08-30 14:28
@ale82to Please try to create a log for your crash, see https://github.com/mozilla-mobile/fenix/issues/14491#issuecomment-683424960

**Comment by ale82to** [comment] 2020-08-30 14:43
I got the issue!
deleting /data/data/org.mozilla.fenix/databases/mozac_downloads_database-shm
underdatabase folder solves the issue when u restart Firefox.

**Comment by hwinnemoe** [comment] 2020-08-30 14:46
Yes, but that is no solution for non-root users. This information is helpful for identifiying the issue, but please also try to create a log for your crash, see https://github.com/mozilla-mobile/fenix/issues/14491#issuecomment-683424960.

**Comment by ale82to** [comment] 2020-08-30 14:49
I cannot help with logcat as I disabled the daemon on my room in other open issue there's the logcat u r looking for that's where I understood it was download database to blame.

**Comment by kbrosnan** [comment] 2020-08-30 14:50
Looks like a duplicate of #14486

**Closed by kbrosnan** 2020-08-30 14:50 UTC
Labels: needs:triage, 🐞 bug
