### ISSUE TITLE
[Bug] Three-dot menu sometimes appears cut-off when toolbar is on bottom

### ISSUE THREAD

**Issue by rhendric** [mozilla-mobile/fenix#19973] opened 2021-06-11 17:02 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

This issue only shows up on some websites! I haven't been able to figure out a more specific trigger yet. But http://example.com does seem to be one that causes it, so:

1. Make sure that the toolbar position is set to ‘Bottom’ (three-dot menu > Settings > Customize)
2. Visit http://example.com
3. Open the three-dot menu

### Expected behavior

The entire menu should be visible, if there is space, or scrollable if not.

### Actual behavior

Initially, I see this:

<a href="https://user-images.githubusercontent.com/1570964/121722795-c485ec80-cab3-11eb-88fd-65ef7f8c4c00.png"><img alt="Screenshot" height="512" src="https://user-images.githubusercontent.com/1570964/121722795-c485ec80-cab3-11eb-88fd-65ef7f8c4c00.png"/></a>

I can flick up on the menu to reveal a little more, but essential elements like the navigation buttons are still cut off (it doesn't scroll any farther than this):

<a href="https://user-images.githubusercontent.com/1570964/121722932-ed0de680-cab3-11eb-8c29-5d3d826de6f8.png"><img alt="Screenshot" height="512" src="https://user-images.githubusercontent.com/1570964/121722932-ed0de680-cab3-11eb-8c29-5d3d826de6f8.png"/></a>

For reference, here's what it looks like normally:

<a href="https://user-images.githubusercontent.com/1570964/121723042-0c0c7880-cab4-11eb-8724-9947044448ee.png"><img alt="Screenshot" height="512" src="https://user-images.githubusercontent.com/1570964/121723042-0c0c7880-cab4-11eb-8724-9947044448ee.png"/></a>

Also, rotating the device to landscape fixes it. In this case, the entire menu doesn't fit on the screen, but I can scroll it and nothing is missing:

<a href="https://user-images.githubusercontent.com/1570964/121723562-a8cf1600-cab4-11eb-8495-1a9958f0cab0.png"><img alt="Screenshot" height="300" src="https://user-images.githubusercontent.com/1570964/121723562-a8cf1600-cab4-11eb-8495-1a9958f0cab0.png"/></a>

(The fix is not persistent; rotating the device back to portrait restores the buggy behavior on this page.)

### Device information

* Device vendor / model and Android version: Amazon Fire (KFFOWI), Android 5.1.1
* Firefox for Android version: 89.1.1-armeabi-v7a

**Comment by lobontiumira** [comment] 2021-06-14 05:59
This is a duplicate of issue #18896

**Closed by lobontiumira** 2021-06-14 05:59 UTC
Labels: needs:triage, 🐞 bug
