### ISSUE TITLE
FNX-12754 ⁃ [Bug] favicons are missing in tab tray on 5.2.0

### ISSUE THREAD

**Issue by leela52452** [mozilla-mobile/fenix#11771] opened 2020-06-19 14:29 UTC
5.2.0

i noticed there are no favicons in tab tray while trying to reproduce #5039 

![Screenshot](https://user-images.githubusercontent.com/52065244/85143328-23b27780-b239-11ea-833b-4159e3f45641.jpg)UNITO-UNDERSCORE!20200619-195227!UNITO-UNDERSCORE!Firefox Preview!

**Comment by sheikh-azharuddin** [comment] 2020-06-19 16:13
This new tab tray will show thumbnail of the website instead of favicon....

**Comment by gabrielluong** [comment] 2020-06-19 17:23
> This new tab tray will show thumbnail of the website instead of favicon....

Ah thanks for pointing that out. I was thinking about how there was a white thumbnail and perhaps we should fallback on favicon when a thumbnail is not captured, but I see the nature of the issue is about the removal of the favicons.

This isn't a bug and we do intend on shipping tabs tray with thumbnail. I can see the case where we still want to fix some bugs related to BrowserIcons, which helps potential consumers (outside of Fenix) of BrowserIcons when used as a component. The easiest way to go about that would be to checkout a previous commit which still has the icons to reproduce the issues.

Closing this issue as WONTFIX since this is not actually a bug.

**Closed** 2020-08-11 04:52 UTC
Labels: Feature:Tabs, Skittle, 🐞 bug
