### ISSUE TITLE
"Download Failed" when downloading a PDF on some websites. [Bug]

### ISSUE THREAD

**Issue by Sodel-the-Vociferous** [mozilla-mobile/fenix#14434] opened 2020-08-29 12:12 UTC
## Steps to reproduce
- Sign in to my payroll web account.
- Navigate to my pay statements.
- Click on any pay statement PDF.

### Expected behavior
- Download completes. Chrome and Firefox 68 handle this task without any issue on this site.

### Actual behavior
- Android notification: "Download failed". There are no on-device developer tools or logs to help me troubleshoot.

### Device information

* Android device: Moto G8 Power, Android 10
* Fenix version: 79.0.5

**Comment by Amejia481** [comment] 2020-08-31 18:16
@Sodel-the-Vociferous if it's not much trouble, would you mind sharing which site you where using? That will be helpful for us to replicate and fix the issue. Thanks in advance.

**Comment by dholbert** [comment] 2020-09-08 01:39
I've been running into this same issue with Fenix Nightly (and then the failure notifications respawn on every app restart, per #14790)

The PDFs that Fenix is having trouble with, most recently on my device, are the "Bottle Capacity Chart" and "Product Manual" linked under "Manuals and Guides" near the bottom here:
https://www.costco.com/wine-enthusiast-somm-series-2-door-dual-zone-wine-and-beverage-center.product.100458858.html

Both PDFs download fine in Chrome.

**Comment by LaurentiuApahideanSV** [comment] 2020-09-08 15:23
I can confirm the issue is reproducible on Firefox Preview Nightly 200908 (Build #2015762675)

### Devices used:
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)

**Comment by kevinoid** [comment] 2020-09-12 23:09
I encountered what I think is the same issue attempting to download https://enterprise.spectrum.com/content/dam/spectrum/enterprise/en/pdfs/support/Motorola%20User%20Guide_WiFi%20LAN.pdf   Tapping the Download button immediately results in "Download failed".  Remote debugging shows request initiation on the Network tab, but no status or headers.

Device information

* Android Device Google Pixel with Android 10 (Build QP1A.191005.007.A3)
* Fenix version: Nightly 200912 06:01 (Build #2015763443)

**Comment by liuche** [comment] 2020-10-14 23:42
I was able to successfully download the link you provided @kevinoid - is this still present on the latest Nightly?

**Comment by kevinoid** [comment] 2020-10-15 00:27
Thanks @liuche, I can confirm that the link (and all other PDF URLs I tested) download without issue using Nightly 201014 17:01 (Build \#2015769675).  Works for me!

**Comment by LaurentiuApahideanSV** [comment] 2020-10-15 08:45
Verified as fixed on Firefox Preview Nightly 201015 (Build #2015769771).
### Devices used:
- OnePlus 6T (Android 9)
- Samsung Galaxy S9 (Android 8.0.0)

**Closed** 2020-10-15 10:01 UTC
Labels: Feature:Download, eng:qa:verified, 🐞 bug
