### ISSUE TITLE
FNX-14233 ⁃ Ability to remove "collections" from home page (or disabling them entierly).

### ISSUE THREAD

**Issue by SergeiFranco** [mozilla-mobile/fenix#13061] opened 2020-07-29 08:26 UTC
### What is the user problem or growth opportunity you want to see solved?
My problem with tab collections is I don't use them and yet they occupy majority of home screen. The home screen is currently not customisable, thus collections cannot be removed.

### How do you know that this problem exists today? Why is this important?
The problem is that I solely rely on top sites for my browsing needs, yet compared to Fennec they icons got smaller, making them harder to distinguish from each other.

### Who will benefit from it?
End-users who don't need collections.

**Comment by cadeyrn** [comment] 2020-07-29 09:56
Duplicate of #3753 and #12377.

**Comment by liuche** [comment] 2020-08-08 00:18
Thank you caderyn!

**Closed** 2020-08-15 02:46 UTC
Labels: needs:triage
