### ISSUE TITLE
Intermittent test failure: QuickSettingsFragmentReducerTest. WebsitePermissionAction - ChangeAutoplay (matchers)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#20875] opened 2021-08-16 21:10 UTC
From my PR https://github.com/mozilla-mobile/fenix/pull/20844/checks?check_run_id=3326232256. Log:
```
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Misplaced or misused argument matcher detected here:

-> at mozilla.components.support.test.MatchersKt.any(Matchers.kt:17)
-> at mozilla.components.support.test.MatchersKt.any(Matchers.kt:17)
-> at mozilla.components.support.test.MatchersKt.any(Matchers.kt:17)

You cannot use argument matchers outside of verification or stubbing.
Examples of correct usage of argument matchers:
    when(mock.get(anyInt())).thenReturn(null);
    doThrow(new RuntimeException()).when(mock).someVoidMethod(anyObject());
    verify(mock).someMethod(contains("foo"))

This message may appear after an NullPointerException if the last matcher is returning an object 
like any() but the stubbed method signature expect a primitive argument, in this case,
use primitive alternatives.
    when(mock.get(any())); // bad use, will raise NPE
    when(mock.get(anyInt())); // correct usage use

Also, this error might show up because you use argument matchers with methods that cannot be mocked.
Following methods *cannot* be stubbed/verified: final/private/equals()/hashCode().
Mocking methods declared on non-public parent classes is not supported.

	at org.mozilla.fenix.settings.quicksettings.QuickSettingsFragmentReducerTest.WebsitePermissionAction - ChangeAutoplay(QuickSettingsFragmentReducerTest.kt:79)```

**Comment by jonalmeida** [comment] 2021-08-17 02:02
Duplicate of https://github.com/mozilla-mobile/fenix/issues/20792

**Closed by jonalmeida** 2021-08-17 02:02 UTC
Labels: needs:triage
