### ISSUE TITLE
FNX-5121 ⁃ long pressing the device's back button should trigger something.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1590] opened 2019-04-12 04:07 UTC
### Why/User Benefit/User Problem
If you long press your device's back button for some seconds on a Chromium web browser a menu is exhibited showing your history. If you do the same on Fenix, nothing happens. This is a feature that may make web browsing easier and faster. Instead of showing the history like Chrome's does, it's better in my humble opinion, to show a list of recently closed tabs, specially because users sometimes close tabs accidentally, and when that happens, Focus doesn't offer to reopen the closed tab (which is not that productive anyway, because this offers are just seconds, and if you lose them you have to search for it in the history).

### What / Requirements
A feature is triggered by long pressing the device's back button.

### Acceptance Criteria (how do I know when I’m done?)
Something useful happens after long pressing the device's back button.

**Comment by cadeyrn** [comment] 2019-04-12 05:25
Duplicate of #1048.

**Comment by vesta0** [comment] 2019-04-17 05:18
Tracked in #1048

**Closed** 2020-08-11 12:12 UTC
