### ISSUE TITLE
Bookmarks on homescreen

### ISSUE THREAD

**Issue by Imold** [mozilla-mobile/fenix#23218] opened 2022-01-14 16:57 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
The ability to basically have the bookmarks dialog be my home page

### How do you know that this problem exists today? Why is this important?
The closest thing to having bookmarks on homescreen is "Recent bookmarks"

### Who will benefit from it?
Every one who has been asking for bookmarks to be put back on the homescreen

**Comment by kbrosnan** [comment] 2022-01-14 18:49
Duplicate of https://github.com/mozilla-mobile/fenix/issues/9193

**Closed by kbrosnan** 2022-01-14 18:49 UTC
Labels: needs:triage

**Comment by purpleyuan** [comment] 2022-01-14 19:15
I don't believe this is a duplicate of #9193, which is talking about a widget. It's my understanding OP is talking about the new tab page.

**Comment by Imold** [comment] 2022-01-15 15:46
@kbrosnan no this is not a Duplicate of #9193. #9193 is about bookmarks on the homescreen of the phone, This is about bookmarks on the browser home page.
