### ISSUE TITLE
FNX3-16304 ⁃ [Bug] missing button to save collections

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#2412] opened 2019-05-10 14:13 UTC
## Steps to reproduce
Open one or more tabs
Switch to homescreen

### Expected behavior
Button to save collections is present 

### Actual behavior
no save collections button is shown

### Device information
* Android device: Huawei P smart, Samsung Galaxy Tab A (2016) SM-T580 
* Fenix version: 1.0.1919 (11300607) 5/10

**Comment by vesta0** [comment] 2019-05-10 17:03
I can't reproduce this.

**Comment by LittleAngelwings** [comment] 2019-05-10 18:58
I've used this revision https://tools.taskcluster.net/index/project.mobile.fenix.v2.nightly.2019.5.10.revision/4f119f0baa2f999676cbb97ff5982d42386bd8cb

**Comment by LittleAngelwings** [comment] 2019-05-11 07:47
Also in today's first nightly revision (11310906)

![Screenshot_20190511-094436_Firefox Preview](https://user-images.githubusercontent.com/44252450/57566896-cc08d200-73d1-11e9-917c-ceec2f1c1601.jpg)

**Comment by LittleAngelwings** [comment] 2019-05-11 17:26
At today's first branch raptor I don't have this issue. The button is shown.

**Comment by bsurd** [comment] 2019-05-15 12:20
Based on the last [commen](https://github.com/mozilla-mobile/fenix/issues/2412#issuecomment-491529720) I am closing this since it is no longer reproducible.

**Comment by cadeyrn** [comment] 2019-05-15 12:25
@bsurd The last comment was not very clear but from his comments in a Firefox forum I know that @LittleAngelwings wanted to say that the button is shown in "raptor" builds but it's missing in "nightly" builds. He confirmed today that it's still the case that it works for him in "raptor" builds but not in "nightly" builds.

**Comment by LittleAngelwings** [comment] 2019-05-15 16:20
@bsurd 
you can see in the screencast of the following issue https://github.com/mozilla-mobile/fenix/issues/2507 that there isn't the save collection button any more in the nightly build. The daily raptor builds have the save collections button. Also another member of @cadeyrn forum confirmed that he hasn't the button any more in his nightly installation.

**Comment by bsurd** [comment] 2019-05-16 14:17
Yes, you're right, reopening the issue.

**Comment by softvision-miralobontiu** [comment] 2019-05-21 14:50
Verified as fixed on the latest build 1.0.1921 (#11410622), with Google Pixel (Android 9), Sony Xperia Z5 Premium (Android 7.1.1), and Sony Xperia Z2 Tablet (Android 6.0.1).

**Comment by vesta0** [comment] 2019-05-21 15:43
Thank you @softvision-miralobontiu

**Closed** 2020-08-20 21:12 UTC
Labels: 🐞 bug
