### ISSUE TITLE
[Bug] Forward/Star/Share/Reload don't show right away in menu when keyboard open

### ISSUE THREAD

**Issue by caugner** [mozilla-mobile/fenix#8995] opened 2020-03-05 14:42 UTC
## Steps to reproduce

1. Set Firefox to show the address bar at the bottom.
2. Focus any input field that triggers the keyboard to open.
3. Open the Firefox menu (in my case: to reload the page to workaround #8993).

### Expected behavior

The Forward/Star/Share/Reload buttons should display right away, because users more likely want to use any of those actions rather than use other menu items.

### Actual behavior

The menu opens scrolled to the top, so I first have to scroll down in order to reload.

### Device information

* Android device: Fairphone FP2 ("5 inch Full HD, 1080 × 1920, Pixel Density 446 ppi", with SwiftKey keyboard)
* Fenix version: `75.0a1-2020030408140`

**Comment by softvision-miralobontiu** [comment] 2020-12-04 13:40
I didn't see this behavior recently. Could not reproduce on the 12/4 Firefox Nightly build with Google Pixel (Android 10).
Closing the issue. Please open a new issue if the situation reoccurs.
Thank you!

**Closed by softvision-miralobontiu** 2020-12-04 13:40 UTC
Labels: needs:triage, 🐞 bug
