### ISSUE TITLE
[Bug]: Fullscreen YouTube video shows toolbar-sized gap

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#23132] opened 2022-01-09 21:23 UTC
### Steps to reproduce

1. Go to any YouTube video like https://m.youtube.com/watch?v=27OzhD4YFcQ

2. Click the fullscreen button.

### Expected behaviour

The video takes the whole screen.

### Actual behaviour

There is a gap. See screenshot:

![Screenshot_20220109-222016](https://user-images.githubusercontent.com/1323194/148701432-5f82af3b-62a5-4d8c-8831-0d944b44132b.jpg)

Seems like a recent regression, doesn't reprobon release.

### Device name

One plus pro 9

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1 (Build #2015856171), 0563bf38b+ AC: 97.0.20220107193451, 379cb84d88 GV: 97.0a1-20220107155514 AS: 87.1.0

**Comment by SoftVision-LorandJanos** [comment] 2022-01-10 14:32
Hi @emilio! Thanks for your report!
I couldn't reproduce the issue you described.
Tested in the latest Nightly (2022-01-10) and latest Release (96.1.1) using the following devices:
- Oppo Reno 6 (Android 11).
- Google Pixel 4 (Android 12).

Please check if you reproduce it with a clean build. Or check if you're using other apps or made some changes in settings that might cause this issue. Thank you!

**Comment by emilio** [comment] 2022-01-10 17:18
Git bisect says: 5d8587e5d195d24a7459dcf7a54ad4ed25c14bbc is the first bad commit. @MickeyMoz do you know how to tell which gecko and android-components changes does that include?

**Comment by Mugurell** [comment] 2022-01-10 17:39
Might be because of https://github.com/mozilla-mobile/android-components/pull/11375. Will look into it.

**Comment by emilio** [comment] 2022-01-10 17:48
Yeah, thanks to @MickeyMoz who helped me to get the android-components commits (below for my own reference):

```
There are multiple options:

  *  If you have that build running somewhere, the about screen shows the A-C commit
  *  You can look at the POM file of a component of that version, e.g.L https://nightly.maven.mozilla.org/maven2/org/mozilla/components/browser-engine-gecko/97.0.20220106143323/browser-engine-gecko-97.0.20220106143323.pom
  *  You can look at treeherder and try to find the build/commit matching this timestamp :)

(The second option will list the commit: <tag>a24ab928db495a17281a0bab0d957b6399def131</tag>)
```

I came up with the range https://github.com/mozilla-mobile/android-components/compare/796891a1ea2c5b5362fc1a322d83335f24d0bd62...a24ab928db495a17281a0bab0d957b6399def131, which indeed points at your changes. Thanks for looking into it! Let me know if I can help with something :)

**Comment by sheikh-azharuddin** [comment] 2022-01-11 09:10
I am getting a white bar in the bottom
![Screenshot_20220111-111956403](https://user-images.githubusercontent.com/58127841/148913635-e79844e6-8b64-4d06-8bb9-0d7c001d4239.jpg)

**Comment by sheikh-azharuddin** [comment] 2022-01-18 05:00
Any fix for this issue? The issue was introduced overnight but yet no fix after a Week! Although it's a nightly version but we users don't have any option..I am using nightly because of custom add on support..

**Comment by Mugurell** [comment] 2022-01-19 08:29
Should be fixed in the next Nightly.

**Comment by SoftVision-LorandJanos** [comment] 2022-01-20 06:48
I've managed to reproduce the issue on a Huawei P30 (Android11).
Tested with the Nightly build mentioned in the report (97.0a1 - 2022-01-07).

Verified as fixed on the latest Nightly 98.0a1 (2022-01-20).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-01-20 06:48 UTC
Labels: 🐞 bug, eng:qa:needed, Feature:Media, S3, needs:triage, qa-triaged

**Comment by fprietog** [comment] 2022-02-07 17:03
IMHO this is a nasty bug because affects to a intensive used function; full screen video playing. 

I don't understand why this bug, that was discovered during testing of version 97, is going to be solved in version 98 instead of 97. Now we have the bug in the stable version probably for a whole releasing cicle... I think it shuold be backported.

Thanks and best regards.

**Comment by rvandermeulen** [comment] 2022-02-15 03:37
FYI, we expect to ship a 97.2.0 release later this week which will address this.
