### ISSUE TITLE
Allow deletion of history suggestions from search fragment

### ISSUE THREAD

**Issue by SpitFire-666** [mozilla-mobile/fenix#6358] opened 2019-10-31 11:19 UTC
### Why/User Benefit/User Problem
When typing a URL into the address bar, I get suggestions from my history. Some I want to remove/delete. I can't see an easy way to remove them. I can remove them from within History but that means I'd have to find each individual visit and remove them. 

### Acceptance Criteria (how do I know when I’m done?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14194)

**Comment by NotWoods** [comment] 2019-11-05 21:04
To clarify, the feature request here is to be able to delete suggestions from the search screen?

**Comment by campbellkerr** [comment] 2019-11-13 03:42
Yes! I want to remove previous site visits that show up as suggestions when typing into the address/search bar.

**Comment by hwinnemoe** [comment] 2020-09-06 12:09
Partial duplicate of #2596

**Comment by Anutrix** [comment] 2021-08-11 21:29
Any updates?

**Comment by topotropic** [comment] 2021-12-21 19:12
Duplicate of https://github.com/mozilla-mobile/fenix/issues/1920

**Comment by cpeterso** [comment] 2022-12-27 22:24
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807745

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2022-12-27 22:24 UTC
Labels: feature request 🌟, Feature:History, Feature:Search
