### ISSUE TITLE
FNX3-15611 ⁃ [Bug] horizontal scrolling can cause the address bar to appear

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1506] opened 2019-04-09 21:40 UTC
## Steps to reproduce
1. Navigate to https://www.cnn.com/2019/04/09/tech/locked-ipad-boy-trnd/index.html
1. Swipe over the carousel below the video that appears on the page. Extra points if you swipe up and down while holding the swipe right to left or left to right.

### Expected behavior
The browser toolbar is not shown while swiping in the carousel. 

### Actual behavior
The browser toolbar is shown while swiping in the carousel. 

### Device information
* Android device: Pixel 2 
* Fenix version: 1.0.1915 build id 10991207

[signal-attachment-2019-04-09-173439.zip](https://github.com/mozilla-mobile/fenix/files/3061094/signal-attachment-2019-04-09-173439.zip)

**Comment by ekager** [comment] 2019-04-09 22:55
Thanks! I opened https://github.com/mozilla-mobile/android-components/issues/2695 to look into this issue in the toolbar behavior code

**Comment by ekager** [comment] 2019-08-02 02:18
@vesta0 can we remove this as a p1 since we no longer have the hiding url bar?

**Comment by vesta0** [comment] 2019-08-09 03:55
Thanks @ekager I removed the p1 but let's keep it open to make sure this is tested once we re-introduce the dynamic nav bar.

**Comment by boek** [comment] 2019-12-28 17:52
Could we test this with the top dynamic bar?

**Comment by AndiAJ** [comment] 2019-12-30 07:33
Hi, **still reproducible** using the dynamic top bar on the latest **Nightly Build #13640626 from 12/30** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191230_092721](https://user-images.githubusercontent.com/51314259/71572372-68a9ec80-2ae7-11ea-891b-7978229b0b94.gif)

**Comment by sblatz** [comment] 2020-03-17 19:51
@snorp do we have the GV API's to handle this now? I don't believe the patch we worked on last week addresses this.

**Comment by snorp** [comment] 2020-03-17 20:20
> @snorp do we have the GV API's to handle this now? I don't believe the patch we worked on last week addresses this.

No, GV can't really do anything about this. Most likely Fenix needs to do something to detect this and not scroll the toolbar in that case.

**Comment by eliserichards** [comment] 2020-05-05 19:27
@sblatz is this bug still valid or should we close it?

**Comment by sblatz** [comment] 2020-05-05 19:56
I can still repro on nightly, yes.

**Comment by Mugurell** [comment] 2020-05-14 09:26
After https://bugzilla.mozilla.org/show_bug.cgi?id=1627737  and https://github.com/mozilla-mobile/android-components/issues/2930 this should not reproduce anymore.
Please help verify.

**Comment by AndiAJ** [comment] 2020-05-15 07:12
Hi, I-ve re-checked this matter  on the latest **`Nightly Build 200515 from 5/15`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

The Toolbar isn't displayed, but there's **still a noticeable movement** while swiping horizontally through the image slider. 
Checked it on Chrome as well, and the toolbar remains hidden without any obvious movements

► Video Fenix
![20200515-095345](https://user-images.githubusercontent.com/51314259/82021647-dec47f80-9693-11ea-9c08-4ec036c3f212.gif)

► Video Chrome
![20200515-100909](https://user-images.githubusercontent.com/51314259/82021954-7b871d00-9694-11ea-9baa-85e922831f40.gif)

@sblatz & @Mugurell - Please review and share your thoughts ☺️ 
**I'll remove the QA needed label until further notice**

**Comment by Mugurell** [comment] 2020-05-15 07:21
@AndiAJ  
From what I understand you confirm that horizontal scrolls do not anymore trigger address bar animations.
This is what we wanted and based on this I'd considered this ticket as done.

The horizontals scrolls in that carousel I think indeed should not trigger a page scroll.
But if this is happening, it is an issue in GeckoView for which I recommend filing a new ticket on Bugzilla.

**Comment by Mugurell** [comment] 2020-08-11 08:38
Closing as per https://github.com/mozilla-mobile/fenix/issues/1506#event-3339743972

**Closed by Mugurell** 2020-08-11 08:38 UTC
Labels: Feature:Toolbar, P2, eng:qa:verified, needs:ac, needs:gv, 🐞 bug
