### ISSUE TITLE
Option to open external links with private Firefox missing in the new version

### ISSUE THREAD

**Issue by Ivan171** [mozilla-mobile/fenix#7230] opened 2019-12-17 02:01 UTC
## Steps to reproduce
Update to Firefox Preview 3.0 (from 2.3)
Try to open an external link in some app (i.e Boost for Reddit)
### Expected behavior
There should be two Firefox options in the Open with dialog: Firefox Preview and Private Firefox Preview
### Actual behavior
There is only one option: Firefox Preview
### Device information

* Android device: Redmi Go with Oreo 8.1
* Fenix version: 3.0

That was one of the features i liked the most, and the only one keeping me using Fenix while it doesn't have extensions support.

I don't know if this is a regression or the feature was removed intentionally. If it was intentional, can it be reimplemented? It is very useful, and Fenix is the only browser i know that has it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14854)

**Comment by NotWoods** [comment] 2019-12-17 04:47
I think this is a regression. For now the quick fix is to set Fenix as your default, then go to "Settings" > "Set as default browser" > "Open links in a private tab".

**Comment by boek** [comment] 2019-12-18 23:54
Unfortunately this feature broke support for setting Fenix as a default browser in Android 5.0 😢  (see: https://github.com/mozilla-mobile/fenix/issues/5972).

With no way of disabling the feature for 5.0 we decided to pull the feature until we can come up with a solution. In the meantime you can set the pref like NotWoods mentioned :)

**Comment by opusforlife2** [comment] 2020-02-13 18:28
I don't know if I want to open a new issue just to ask this: Why has "Open links in a private tab" been made conditional upon setting Fenix as default browser? Is there a technical reason for it? Users who don't want to make it the default browser should still be able to take advantage of this feature.

**Comment by Lumute** [comment] 2020-02-23 01:34
I agree, this was one of the best features of Firefox Preview and really miss it...

**Comment by sblatz** [comment] 2020-05-13 20:23
You can enable this under Settings > Private browsing > Open links in a private tab

Closing this for now, but if this does not cover your use case, please re-open!

**Comment by Lumute** [comment] 2020-05-13 20:57
@sblatz no that does not cover the use case, that setting will open every single link in private mode. With version 2.3 by having separate options we were able to normally open links in full mode and open links in private mode when necessary... Right now the only way to do that is to copy the link, open a private tab and paste on the address bar which is a PITA!

Please re-open.

**Comment by Ivan171** [comment] 2020-05-13 23:33
I agree with @Lumute here.

> You can enable this under Settings > Private browsing > Open links in a private tab

This option doesn't replace what we had in the 2.3 version. Before, we could choose what link to open in a private tab. Now, every link opens in a private tab, which is not always desirable - although it is better than nothing.

**Comment by softvision-miralobontiu** [comment] 2020-06-11 11:59
I will re-open this issue.
I was able to reproduce this both with Nightly from 6/11 and with Beta 5.2.0-beta.1, using Samsung Galaxy Tab S6 (Android 9).

**Comment by jingofett** [comment] 2020-08-19 05:53
Would love for this feature to come back!

Would it be possible to do a check for the android system version?

**Comment by opusforlife2** [comment] 2021-02-15 15:06
Further activity has occurred.

**Comment by opusforlife2** [comment] 2021-08-14 18:03
Further activity has occurred.

**Comment by Lumute** [comment] 2021-08-16 14:01
Is there any chance this feature is bought back? it was super useful and if I remember correctly the problem is that is broke the default browser setting in Android 5.0. Come on! who cares about Android 5.0? that is now almost 7 mayor versions behind! you have to move on at some point...

**Comment by cpeterso** [comment] 2022-12-26 06:40
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807547

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2022-12-26 06:40 UTC
Labels: 🐞 bug, feature request 🌟, P2, Feature:PrivateBrowsing, S2
