### ISSUE TITLE
[Bug] A white screen is displayed after pasting the newly created google photos URL in a new tab

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3627] opened 2019-06-24 13:41 UTC
## Steps to reproduce
1. Launch Fenix.
2. Login with valid credential on **`Google Photos`** site.
3. Create or select any album.
4. Generate and copy the URL.
5. Open new tab tap on the URL.
6. Tap on the **`Fill link from clipboard`.**
### Expected behavior
The website(google photos) is loaded correctly and the photo album is displayed.
### Actual behavior
A white page is displayed and no albums is displayed.
### Device information

* Android device: **`Samsung Galaxy S10+(Android 9), Samsung Galaxy Note 9(Android 8.1.0).`**
* Fenix version: **`6/24 1.0.1926`**  and **`6/19 1.0.0-rc.2`**.

For more details please see the [video](https://drive.google.com/file/d/1T7qRKKmMy5mNROKdgR8Th5zPPUk_6qPE/view?usp=sharing) and the [logcat.txt](https://github.com/mozilla-mobile/fenix/files/3321124/logcat.txt).
Please note that if pressing long tap on any photo from google photos and copy the link, when pasting it in a new tab, the image is loaded.

**Comment by npark-mozilla** [comment] 2019-06-24 13:56
This issue can be seen with other news share URLs, so there is something that needs further investigation, and it might have a larger impact.

**Comment by kbrosnan** [comment] 2019-06-24 18:23
Sound like a dupe of #2576 which requires app intent urls to work.

**Closed by kbrosnan** 2019-06-24 18:23 UTC
Labels: 🐞 bug
