### ISSUE TITLE
[Bug] Typing search query in address bar shows search suggestion that severly lags / is slower than typing

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#7877] opened 2020-01-23 00:31 UTC
## Steps to reproduce

1. tap in address bar.
2. type any text. I typed "weather in 100"

### Expected behavior

The first search suggestion should always track the speed at which I am typing my query. I know that there is discussion around this in  #1742, but I disagree with the request there (I don't see an obvious way to search my query without an affordance, especially since I don't trust what the enter key might do in any specific instance across Android). 

### Actual behavior

The search suggestion lags my typing significantly. See screencast.

### Device information

* Android device: Pixel 2
* Fenix version: latest from play store

[signal-attachment-2020-01-22-192327.zip](https://github.com/mozilla-mobile/fenix/files/4100738/signal-attachment-2020-01-22-192327.zip)

---------------------------------
 
[mleclair edit]: I commented with some videos, editing for some visibility:

Dial: https://streamable.com/ef3euf --> speed: dial: up:30 down:49 rtt:60
2g: https://streamable.com/bqks5d --> speed: 2g: up:256 down:280 rtt:400
3g: https://streamable.com/x7vcrl --> speed: 3g: up:768 down:1600 rtt:15
lte: https://streamable.com/auyqw3 --> speed: 4g: up:9000 down:9000 rtt:85

**Comment by mcomella** [comment] 2020-05-14 21:02
We are wondering if this is a dupe of https://github.com/mozilla-mobile/fenix/issues/9406 – let's leave this open and, once #9406 is fixed, we can check with the reporter that this issue is addressed as well. This issue seems focused on the affordance, the first search suggestion – the one that tracks what the user is typing – while the other may be more holistic and involve the network requests.

**Comment by mcomella** [comment] 2020-06-03 23:38
Triage: it's unclear if this is a performance issue or a functional issue. MarcLeclair was unable to reproduce. One theory is that the suggestion results are all returned by the network so it's a functional issue.

It's a P1 from a UX perspective because search is important but modified by the impact (e.g. # users effected).

@MarcLeclair Please test again with high network latency to see if you can reproduce so we can prioritize accordingly.

**Comment by MarcLeclair** [comment] 2020-06-08 15:56
So I was able to reproduce it by reverse tethering my phones with different speed. At very low download speeds, the performance was left to be desired:

Dial: https://streamable.com/ef3euf  --> speed: `dial: up:30 down:49 rtt:60`
2g: https://streamable.com/bqks5d --> speed: ` 2g: up:256 down:280 rtt:400`
3g: https://streamable.com/x7vcrl --> speed: ` 3g: up:768 down:1600 rtt:15`
lte: https://streamable.com/auyqw3 --> speed: `4g: up:9000 down:9000 rtt:85` 

Also , notice that at Dial didn't get any results where as 2g did get some results, that was because the connection was so slow, I was dropping packets and we defaulted to just showing 1 recommendation ( that was still slow to show)

**Comment by grigoryk** [comment] 2020-06-08 17:55
From the [awesomebar perf dashboard](https://sql.telemetry.mozilla.org/dashboard/fenix-awesomebar-performance?p_w57759_days=7&p_w57759_org_mozilla_fenix=org_mozilla_fenix_nightly&p_w57760_days=7&p_w57760_org_mozilla_fenix=org_mozilla_fenix_nightly&p_w57761_days=7&p_w57761_org_mozilla_fenix=org_mozilla_fenix_nightly&p_w57762_days=7&p_w57762_org_mozilla_fenix=org_mozilla_fenix_nightly&p_w57763_days=7&p_w57763_org_mozilla_fenix=org_mozilla_fenix_nightly&p_w57764_days=7&p_w57764_org_mozilla_fenix=org_mozilla_fenix_nightly&p_w57765_days=7&p_w57765_org_mozilla_fenix=org_mozilla_fenix_nightly), we have data for the [search engine provider](https://sql.telemetry.mozilla.org/queries/71221?p_days=7&p_org_mozilla_fenix=org_mozilla_fenix_nightly#178952).

Split by percentiles:
<img width="225" alt="Screen Shot 2020-06-08 at 10 52 00 AM" src="https://user-images.githubusercontent.com/465422/84063607-275f1800-a976-11ea-9f63-5d6f7231e693.png">

This is for the nightly audience, so data is probably biased towards devices on faster networks. 99th percentile is just under 2 seconds (very slow), but 95th percentile is quite good at just under 300ms (just fast enough to not notice lag).

**Comment by jeanygong** [comment] 2020-06-16 19:41
@brampitoyo can you provide your UX input on this issue as it's similar to #8043.

**Comment by brampitoyo** [comment] 2020-06-16 21:49
@jeanygong @MarcLeclair @grigoryk @mcomella I agree with comment 0, that the first search suggestion should track along the user’s typing speed.

This first suggestion doesn’t need to have a Refine (↖︎) action, because it’s identical to what the user has typed.

The other suggestion provided by the server should have a Refine action, but I’ll make a separate comment on #8043.

**Comment by jonalmeida** [comment] 2020-06-16 22:06
In our sprint planning, one possible solution that came up was to add a separate awesomebar provider for only raw input text to give us the perceived performance. 

If we go with this approach, it would also lend us help for solving https://github.com/mozilla-mobile/fenix/issues/8043#issuecomment-645031150 as well, which also requires a way to distinguish the user input provider from the search suggestions.

**Comment by pocmo** [comment] 2020-07-22 09:51
A patch for this landed and should be available in the next Nightly build.

**Comment by LaurentiuApahideanSV** [comment] 2020-07-28 09:08
Verified as fixed on Firefox Preview Nightly 200728 (Build #22100630).
### Devices used
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)

**Closed by LaurentiuApahideanSV** 2020-07-28 09:08 UTC
Labels: Feature:Search, eng:performance, eng:qa:needed, 🐞 bug
