### ISSUE TITLE
FNX-3397 ⁃ Long press back button should pop up the history of the tab and allow jumping to any item in it

### ISSUE THREAD

**Issue by upsuper** [mozilla-mobile/fenix#10264] opened 2020-04-28 12:22 UTC
In the old Firefox Android app, when you navigate several times in a tab, and then long press the back button, a menu would pop up showing the history of this tab just like when you right click back button on desktop Firefox. This is quite convenient.

Fenix should probably add this as well.

**Comment by cadeyrn** [comment] 2020-04-28 12:33
Duplicate of #1048.

**Closed** 2020-08-11 00:19 UTC
Labels: needs:triage

**Comment by minutesinch** [comment] 2020-09-09 18:20
in which version?

**Comment by cadeyrn** [comment] 2020-09-09 18:27
It's already implemented in Firefox 80 (for most devices). Firefox 81 for Huawei devices.
