### ISSUE TITLE
Unable to send URL to other device via Share

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#8937] opened 2020-03-03 17:52 UTC
> https://bugzilla.mozilla.org/show_bug.cgi?id=1619662

In Fennec I could share a URL from another app and directly send it to another device without stopping in Firefox on the way there. This option is gone in Fenix, and you have to load the page in Firefox before you can send it to another device now. This breaks some URLs for example:
If the link I'm sending from an email requires me to log in in order to view it, it often redirects to a login page. the login page is then what gets sent to the other device, and it loses the after-login destination.
I tend to use my phone for email even when I'm working at my laptop, but I'd rather use the laptop's web browser as long as I'm sitting at it.

**Comment by klemens** [comment] 2020-05-03 16:53
This is a probably duplicate of #1523.

**Comment by kbrosnan** [comment] 2020-07-28 20:25
Yep thanks for the issue number.

**Closed by kbrosnan** 2020-07-28 20:25 UTC
Labels: Feature:FennecTransition, Feature:ShareSheet, Feature:Sync, feature request 🌟
