### ISSUE TITLE
[Bug] Reader view style is impacted by Request Desktop Site feature

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8799] opened 2020-02-26 23:23 UTC
## Steps to reproduce
- Visit an article
- Open reader view, observe style
- Close reader view
- Request Desktop Site
- Open reader view

### Expected behavior
Reader view style is identical

### Actual behavior
Reader view on desktop site has small text and can be zoomed in and out: it kind of breaks reader view.

Non desktop:
![Screenshot_20200226-152038](https://user-images.githubusercontent.com/759372/75397473-cd957f00-58ab-11ea-9b6e-7665c46cefce.png)

Desktop:
![Screenshot_20200226-152056](https://user-images.githubusercontent.com/759372/75397491-d5edba00-58ab-11ea-8dfe-ab2080ce59e5.png)

### Device information

* Android device: P2
* Fenix version: Nightly 200226

**Comment by csadilek** [comment] 2020-02-27 18:25
This is another case which would be fixed by https://github.com/mozilla-mobile/android-components/issues/2985.

**Comment by csadilek** [comment] 2020-05-05 21:23
This is fixed now, I am duping this to https://github.com/mozilla-mobile/fenix/issues/2633 and get QA verification going -> the zoom level of the original page (desktop or not) no longer affects reader view.

**Comment by sflorean** [comment] 2020-10-29 16:30
Checked on Nightly 10/29 with Pixel 3 (Android 11) and the issue isn't reproducible anymore. Closing as fixed.

**Closed by sflorean** 2020-10-29 16:30 UTC
Labels: needs:triage, 🐞 bug
