### ISSUE TITLE
[Bug] Downloaded PDF files do not open, but trigger an error

### ISSUE THREAD

**Issue by concastinator** [mozilla-mobile/fenix#6720] opened 2019-11-20 14:12 UTC
## Steps to reproduce

1) Tap to download any PDF file, for instance https://small.r7rs.org/attachment/r7rs.pdf.
2) A pop-up will appear containing a button labelled "Open". Tap on it to open the downloaded file.
3) Choose what program to use to open the file. I have tested both ReadEra and Google Drive PDF Viewer, with the same result.

### Expected behavior

The downloaded file should open.

### Actual behavior

The downloaded file doesn't open, and an error message is presented instead consisting of the following 3 lines:

null
Unable to perform request
content://org.mozilla.fenix.nightly.fileprovider/Download/Download/null

### Comments

1) Could this be caused by the duplication of the word "Download" in the path above?

2) The file is correctly downloaded and can be opened from the Files program. It is just not properly passed over to the PDF viewer.

### Device information

* Android device: Nokia 5 (model TA-1024) with up-to-date Android 9 (Android One program)
* Fenix version: 191120 06:01 (build 13240608)

**Comment by BranescuMihai** [comment] 2019-11-20 16:05
Will be fixed in [5032](https://github.com/mozilla-mobile/android-components/issues/5032), it's the same problem, that the path towards the file is null.

Duplicate of [6519](https://github.com/mozilla-mobile/fenix/issues/6519), but thanks for raising this up!

**Closed by BranescuMihai** 2019-11-20 16:05 UTC
Labels: 🐞 bug
