### ISSUE TITLE
[Bug]Search shortcuts and search engine settings are not displayed when pressing the shortcuts button

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6324] opened 2019-10-29 12:42 UTC
## Steps to reproduce
1. Navigate to any website
2. Tap on the URL bar
3. Tap the Shortcuts button

### Expected behavior
Search shortcuts are displayed

### Actual behavior
Only the "Search with" is displayed, the search shortcuts and search engine settings are missing 
### Device information

* Android device: 
Samsung Galaxy Tab A (Android 9)
* Fenix version: 
• 2.3.0-rc.1 from 28/10
• Nightly #13020608 from 29/10

### Notes
► Video
![20191029_141603](https://user-images.githubusercontent.com/51314259/67767999-43065580-fa5a-11e9-83b7-3309a93322d3.gif)

**Comment by ValentinTimisica** [comment] 2019-10-29 16:10
I think we need the UX help here. How should this work?

I saw the current flow was recently modified by #1620 with an explicit comment to not show any sugestions when selecting the URL - [AwesomeBarView.kt#L183](https://github.com/mozilla-mobile/fenix/blob/7813fb22d475701d5087b385150c50696006766f/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt#L183). 

So now we are left with the `🔍 Shortcuts` button which when pressed shows only the `SEARCH WITH` header with no search engines displayed.
We can either:
- Hide `SEARCH WITH` header, but this will leave us with the `🔍 Shortcuts` button that does nothing when pressed.
- Hide the `🔍 Shortcuts` button and also the `SEARCH WITH` header.

Or can you suggest anything better?

**Comment by brampitoyo** [comment] 2019-10-31 02:02
Paging @verdi, original designer on #1620, for feedback.

**Comment by liuche** [comment] 2019-11-21 01:40
This is a dupe of #6284 which was fixed and verified.

**Closed by liuche** 2019-11-21 01:40 UTC
Labels: Feature:Search, Feature:Shortcuts, S2, needs:UX-feedback, 🐞 bug
