### ISSUE TITLE
Third party certificates like the Firefox 68 and before

### ISSUE THREAD

**Issue by jenabaivab** [mozilla-mobile/fenix#13063] opened 2020-07-29 08:46 UTC
### What is the user problem or growth opportunity you want to see solved?
It would be very helpful if we could get the ability to use third party certificates like in the older variants of firefox. I am licensed user of Adguard that uses it own certificate for HTTPS filtering in browsers. It's cosmetic filtering is very fast and universal throughout the device, so using that is very essential. Compared to Adguard filtering, I have found that ublock blocking is slower on Fenix and would really be glad if this feature is made available.

### How do you know that this problem exists today? Why is this important?
There are many people in the Adguard community that are stuck on the older variant purely because the lack of 3rd party certificates. Even the devs cannot help unless Firefox adds this functionality.

### Who will benefit from it?
Anyone with an Adguard subscription or any third party adblocker for that matter like Draeneg, Adlock, Adclear etc.

**Comment by cadeyrn** [comment] 2020-07-29 09:59
Duplicate of #2286 and #3728.

**Closed** 2020-08-28 23:09 UTC
Labels: needs:triage
