### ISSUE TITLE
[Spike] Investigate Android 11 implications for device-to-device backups

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#18373] opened 2021-03-08 18:10 UTC
https://developer.android.com/about/versions/11/behavior-changes-11#device-to-device-file-transfer

There are some unknowns about how the device to device transfer will impact our app. Areas to think about: 
* Nimbus ids (should identify the device, not the person)
* Sync ids
* ...

**Comment by kbrosnan** [comment] 2021-03-08 20:01
Need to make a decision if this blocks the Android 11/API 30 work from shipping in v88?

Need to clarify if device-to-device backup can only happen on device first run or if there is some case where device-to-device backup can be triggered with complex profiles on both devices.

Is there a way we can test this behavior on emulators? Might be some useful info at https://developer.android.com/guide/topics/data/testingbackup

Some more cases to evaluate

- [ ] Glean IDs
- [ ] InstallTime
- [ ] Device model
- [ ] etc.


- [ ] Sentry
- [ ] Leanplum
- [ ] Profile data, bookmarks, history, passwords, saved website data, favicons, etc
- [ ] Firebase?

**Comment by Amejia481** [comment] 2021-03-08 20:35
@kbrosnan could the QA team help us to test?

**Comment by Amejia481** [comment] 2021-03-08 20:37
cc @grigoryk

**Comment by Amejia481** [comment] 2021-03-09 16:24
From the [docs](https://developer.android.com/about/versions/11/behavior-changes-11#device-to-device-file-transfer):

> If your app targets Android 11 or higher, you cannot disable device-to-device migration of your app's files using the allowBackup attribute. The system automatically allows this functionality.
> 
> However, you can still disable cloud-based backup and restore of your app's files by setting the allowBackup attribute to false, even if your app targets Android 11 or higher.

It states that we can't **disable device-to-device migration** on Fenix files, but we can disable cloud-based backup and restores. I think we have to focus on finding what is **device-to-device migration** and which risk could imply. [I think it is transferring data from one device](https://support.google.com/android/answer/6193424?hl=en#zippy=%2Cswitch-from-an-android-phone) to another directly without  a cloud backup, I will keep looking.

So far we I found we disabled the feature because of https://github.com/mozilla-mobile/fenix/issues/4072 we could start looking to see if we can simulated https://github.com/mozilla-mobile/fenix/issues/4072 and clarify what device-to-device migration means.

**Comment by Amejia481** [comment] 2021-03-09 19:10
There are some historical references for similar bugs on Fennec 
* https://bugzilla.mozilla.org/show_bug.cgi?id=1185920
* https://bugzilla.mozilla.org/show_bug.cgi?id=1440422

**Comment by superbonaci** [comment] 2021-03-09 20:13
If you purchase iPhone it will transfer automatically everything, Apple doesn't give any slack to developers. It's the best thing to do, you don't want to find out something is missing.

**Comment by Amejia481** [comment] 2021-03-09 20:59
QA team please help use to verify  these two test cases :

## 1) Restore a device account with Fenix using back up from a Google account.
1. Install Fenix on a device with Android 11.
2. Log into your Firefox account and wait for bookmarks, history, logings and opened tabs to sync (This account should have previous data like logins, passwords and browser history).
3. Enable automatically back ups following the steps on [Automatically back up data & settings](https://support.google.com/android/answer/2819582?hl=en#zippy=%2Cwhat-gets-backed-up%2Cadd-or-switch-backup-accounts) section and wait until the first back up finishes.
4. Switch to another android device with Android 11  (Or [factory reset the same](https://support.google.com/android/answer/6088915?hl=en)) and restore the data from the cloud following [these steps](https://support.google.com/android/answer/6193424?hl=en#zippy=%2Crestore-data-from-the-cloud%2Cswitch-from-an-android-phone#restore-data-from-the-cloud).
5. After switching you will see the Fenix app is installed and you should be able to use the browser without issues, navigate and use other basic functionality and **NONE of the browser data will be synced, you will be NOT logged on your Firefox account.**
6. You should be able to sync and your Firefox account without issue and use the browser. 


## 2) Restore a device account with Fenix using an Android phone back up.
1. Install Fenix on a device with Android 11.
2. Log into your Firefox account and wait for bookmarks, history, logings and opened tabs to sync (This account should have previous data like logins, passwords and browser history).
3. With a new device with Android 11, follow the steps on [Switch from an Android phone](https://support.google.com/android/answer/6193424?hl=en#switch-from-an-android-phone&zippy=%2Cswitch-from-an-android-phone) section.
4. After switching you will see the Fenix app is installed in the new device and you should be able to use the browser without issues, navigate and use other basic functionality and **your browser data WILL be synced, you WILL be logged on your Firefox account.**
5. You should be able to sync and your Firefox account without issue and use the browser. 
6. Please report any issues if found.

**Comment by superbonaci** [comment] 2021-03-09 21:18
Android Virtual Devices (AVD) and physical devices (Pixel) have different behavior. Would be great if you could test both.

**Comment by ix5** [comment] 2021-03-10 12:30
I'd like you to add the following case as well:

1. Install Fenix on a device with Android 11.
2. Do not log into Firefox account. Add some bookmarks.
3. With a new device with Android 11, follow the steps on Switch from an Android phone section.
4. After switching you will see the Fenix app is installed in the new device and you should be able to use the browser without issues, navigate and use other basic functionality and your browser data WILL be synced from the old device, you WILL NOT be logged on your Firefox account.
5. You should be able to use the browser.

**Comment by Amejia481** [comment] 2021-03-10 16:02
The test case number 2 will require two devices as we have to transfer the info for one existing devices to another.

**Comment by Amejia481** [comment] 2021-03-10 16:22
Thanks @ix5, I updated the test cases

**Comment by Amejia481** [comment] 2021-03-11 16:02
Thanks for testing @sflorean, it could be that Samsung has a different backup implementation from the default one and It could be causing the behavior change. If it's possible could you try to test on two pixel phones?

**Comment by sflorean** [comment] 2021-03-11 16:11
I've got the same behavior for both devices, and the bugs are reproducible on Pixel as well. We will try to check on 2 Pixel devices, but only "device backup" option is available right now.

**Comment by jtagcat** [comment] 2021-03-11 17:52
Please do not forget collections. Right now when anything happens with FF (firefox stops responding until app data is deleted, device lost/destroyed by everyday things), collections are lost. You can't retrieve them from 'open tabs' of last sync either.

For that reason, I do not use collections at all.

**Comment by Amejia481** [comment] 2021-03-11 20:06
>     * Samsung

I will close the issue as the backup behavior is been done by Android we just want to see the implications of the behavior change on Android 11  as the [docs](https://developer.android.com/about/versions/11/behavior-changes-11#change-details_4) indicates

**Comment by Amejia481** [comment] 2021-03-11 20:08
> Please do not forget collections. Right now when anything happens with FF (firefox stops responding until app data is deleted, device lost/destroyed by everyday things), collections are lost. You can't retrieve them from 'open tabs' of last sync either.
> 
> For that reason, I do not use collections at all.

Did you transfer from one device to another and that happen to your Firefox nightly?

**Comment by jtagcat** [comment] 2021-03-12 08:38
> Did you transfer from one device to another and that happen to your Firefox nightly?

No. I'm more focused on backups rather than migrations. As the collections are not included in backups/sync, and they were not mentioned here, I mentioned them here.

As far as I've used the feature, d2d migrations break things, ending up costing more time than they save.

**Comment by Mugurell** [comment] 2021-03-12 14:46
Tested migrating the data from a Pixel 3 to a OnePlus7 and got the same results as Sorina.
Basically no app data was migrated. For any of the "migrated" apps.

**Comment by jonalmeida** [comment] 2021-03-15 20:14
On the doc [Test back and restore](https://developer.android.com/guide/topics/data/testingbackup), it had a interesting snippet that hinted different manufacturers may have different implementations of the on-device service.

> The available backup transports **may differ from device to device (due to customizations by device manufacturers and service providers)**, but most Google Play enabled devices ship with the following transports..

For that reason, we also tested back-restore by USB cable between a Pixel 3 and Pixel 4, both on Android 11.

In this case as well, we did not have app data restored: Sync account, bookmarks, history, etc.

**Comment by Amejia481** [comment] 2021-03-25 17:33
I filed an issue on the Google issue tracker for Android https://issuetracker.google.com/issues/183634603

**Comment by Amejia481** [comment] 2021-04-05 18:56
From the Google issue tracker:

> In Android 11 we allowed OEM implementations of Android to adopt this behaviour (i.e. to ignore allowBackup for device-to-device migrations). However, the functionality wasn't implemented as part of stock Android 11 / AOSP, so this behavior is not guaranteed for Android 11. We're sorry the documentation didn't make this clear and we will look into updating it to better reflect the situation.

It looks this behavior was put into the documentation as guideline and it wasn't implemented as part of stock Android 11.

**Comment by superbonaci** [comment] 2021-05-08 10:57
> This means that we don't have an issue for now but this is something that we should address in the future as it's probably going to change in future Android versions.

It says OEM implementations may allow bypass allowBackup, so that means other brands apart from Pixel. You may have the issue for now, because, can anybody check if any OEM with Android 11 already has the feature? I can't because I only have one Samsung with android 11. If I had 2 I could check.

**Comment by ix5** [comment] 2021-11-05 20:41
Should revisit as A12 is out.

**Comment by jonalmeida** [comment] 2021-11-09 00:34
I don't see any new changes in Android 12 that affect backups in similar ways (the closest is `adb backup` which is not meant for end-users).

Let's close this since the investigation is already done in https://github.com/mozilla-mobile/fenix/issues/18373#issuecomment-813576131

**Closed by jonalmeida** 2021-11-09 00:34 UTC
Labels: a-s, S2, Android:11
