### ISSUE TITLE
FNX3-17010 ⁃ nit: 3 dot menu animation

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#343] opened 2019-02-01 11:10 UTC
Nit: 3 dot menu is at the bottom, when I tap it the menu animates down from the top like a windowshade. If "falls" from the center of the screen towards the 3 dot menu icon. Instead should it animate up from the bottom i.e. "rise up out of" the 3 dot menu button?

**Comment by pocmo** [comment] 2019-02-01 11:20
@Cheap-Skate What device are you using?

**Comment by Sdaswani** [comment] 2019-02-05 18:45
@lime124 to assign to Amy soon.

**Comment by lime124** [comment] 2019-02-06 19:00
removing the [UX] so this covers the eng work. we have an issue to track the UX work for animations this milestone.

**Comment by AmyYLee** [comment] 2019-02-06 19:21
@Cheap-Skate Hi, can you attach a video capture of the issue you are referring to? I am not seeing this in the reference build @pocmo

Thanks

**Comment by Cheap-Skate** [comment] 2019-02-06 21:49
If you turn on Developer Options in Android settings, then set Drawing > Window Animation Scale 10x, can you see it then? The menu drops down to cover the three dots, on my Galaxy s7 at least. I can take a video if you like. It's really a tiny nit pick :)

**Comment by lime124** [comment] 2019-02-06 21:55
@AmyYLee see above!

**Comment by AmyYLee** [comment] 2019-02-07 00:25
> Drawing > Window Animation Scale

Hi, 

Yes I set the scale to 10x but I'm unclear on what the issue is. Can you please provide a video? Thanks

**Comment by Cheap-Skate** [comment] 2019-02-07 12:20
[20190207_120117.mp4.zip](https://github.com/mozilla-mobile/fenix/files/2840669/20190207_120117.mp4.zip)

Hi Amy, video attached, this is at Window Animation Scale 10x. At the moment the Settings menu starts near the middle of the screen and expands and drops down to cover the URL bar. It looks like it is expanding out of a point in the middle of the screen. I think this is wrong. I think it should expand out of the three dot menu on the URL bar, so, start small at the bottom right and expand up and to the left to its full size.

**Comment by Cheap-Skate** [comment] 2019-02-07 13:59
![settings menu](https://user-images.githubusercontent.com/40568887/52415975-6ceca600-2ae0-11e9-8166-e1d601f56604.jpg)

I did a sketch of current behavior and what I think would be better, sorry for the terrible drawings. I think you need to tweak the animation settings. The current behavior just looks a bit unpolished IMHO.

Cheers!

**Comment by colintheshots** [comment] 2019-02-07 14:18
I don't believe there's any animation currently. It's just the normal View painting. We could add a circular reveal animation to match Material Design. Let's put this issue on the backlog to fix in a future Sprint.

**Comment by jonalmeida** [comment] 2019-02-07 16:05
@AmyYLee I've taken a video of what's being described in the ticket here with the animations slowed down. @Cheap-Skate can you verify this is what you're referring to?

![indeliblebountifulgull](https://user-images.githubusercontent.com/1370580/52424098-4ff7a900-2ac7-11e9-89ec-34322020e256.gif)
[HQ video](https://giant.gfycat.com/IndelibleBountifulGull.webm)

> I don't believe there's any animation currently. It's just the normal View painting. We could add a circular reveal animation to match Material Design. Let's put this issue on the backlog to fix in a future Sprint.

A simple override to fade in from the bottom should suffice.

I was playing around with a simple reveal animation from the corner ([similar to Chrome](https://giant.gfycat.com/HastyInfantileAntarcticfurseal.gif)) for https://github.com/mozilla-mobile/reference-browser/issues/420 that may work here as well.

**Comment by Cheap-Skate** [comment] 2019-02-07 16:17
@jonalmeida yes that's it. On the one hand, I expect most users won't notice. On the other hand, I got the impression that it is easy to fix if you want to go that way.

Of course if you are eventually going to have toolbar top or bottom as a user option you want your animation to cover both cases - drop down from top or rise up from bottom.

Thanks for looking at it.

**Comment by AmyYLee** [comment] 2019-02-07 19:29
Hi, 
I think we should reference native android animations where we can. Please see video attachment. 
[Menu Animation.mp4.zip](https://github.com/mozilla-mobile/fenix/files/2842386/Menu.Animation.mp4.zip)

**Comment by vesta0** [comment] 2019-04-01 03:49
@lime124 what is the status of this bug? Are we waiting for UX or sticking with native Android animations?

**Comment by mheubusch** [comment] 2019-04-05 19:38
@vesta0 we are using native animations in this case and wherever possible

**Comment by jonalmeida** [comment] 2019-04-08 19:09
To clarify then, the native Android animation (which @AmyYLee also shared) is that the animation would animate from the bottom.

**Comment by AmyYLee** [comment] 2019-04-08 19:52
> > Are we waiting for UX or sticking with native Android animations?
> 
> This question can be confusing since the default and the suggested are both native animations.
> 
> To clarify then, the native Android animation (which @AmyYLee also shared) is that the animation would animate from the bottom.

Yes it would animation from the bottom (basically coming out from the 3-dot menu)

**Comment by jonalmeida** [comment] 2019-06-28 22:28
This can probably be closed now.

**Comment by yoasif** [comment] 2019-06-28 22:34
The animation comes out of the menu for me in the latest Fenix.

**Comment by sblatz** [comment] 2019-07-03 20:03
I'm throwing a QA needed label on this :)

**Comment by softvision-miralobontiu** [comment] 2019-07-04 12:08
Verified as fixed on the latest Nightly build 190704 (#11850611) with Samsung Galaxy Tab S3 (Android 8).

![20190704_150420](https://user-images.githubusercontent.com/40694158/60665527-5bc87b00-9e6d-11e9-94cd-8e8425ed41c5.gif)

**Closed** 2020-08-12 17:45 UTC
Labels: Feature:MainMenu, eng:qa:verified, eng:quality, eng:ready
