### ISSUE TITLE
custom accent color across the whole firefox ui

### ISSUE THREAD

**Issue by Dev-i-l** [mozilla-mobile/fenix#17382] opened 2021-01-10 02:48 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
many years have passed by and we live in a digital age or must i say the cyberpunk age now, but despite of all that the default accent color is still the black/white. it would be nice to have an option to pick our own accent color based on our liking like i would use dark theme with muted red accent.
### How do you know that this problem exists today? Why is this important?
some people just want more customizations inside firefox to tweak it to their liking, giving a custom accent color picker will solve this problem
### Who will benefit from it?
everyone

(also vanced manager had a very cool implementation of this https://github.com/YTVanced/VancedManager/commit/cc72b1c7d12f3e6bdc2a3c3bae5cc20662b1a13c)

**Comment by Dunexus** [comment] 2021-01-10 12:12
There is this issue about themes support https://github.com/mozilla-mobile/fenix/issues/10032
Also see https://github.com/mozilla-mobile/fenix/issues/1178 about theme based on website meta theme-color.

**Comment by Dev-i-l** [comment] 2021-01-11 10:38
well, themes refer to the background of a page or settings menu, but accent color refers the "color of text in ui". so this issue is different from the other two :)

**Comment by kbrosnan** [comment] 2021-01-12 21:38
Going to close this as a duplicate of the theme's addon one. In desktop the themes have limited ability to set colors for some text.

**Closed by kbrosnan** 2021-01-12 21:38 UTC
Labels: needs:triage
