### ISSUE TITLE
[Bug] Opening a Collection scrolls the view up

### ISSUE THREAD

**Issue by smaug----** [mozilla-mobile/fenix#2902] opened 2019-05-27 20:26 UTC
## Steps to reproduce
Have several Collections, so that the viewport scrolls. Open the last one, viewport is scrolled up and the Collection isn't visible anymore (need to scroll down).

### Expected behavior
Viewport shouldn't scroll up

### Actual behavior
Viewport scrolls up

### Device information
* Android device: Honor 7, Android 6
* Fenix version: 1.0.1921

**Comment by vesta0** [comment] 2019-05-30 23:22
We may have a duplicate bug for this but I couldn't find it.

**Comment by vesta0** [comment] 2019-05-31 18:14
@mheubusch to look at this, thank you.

**Comment by mheubusch** [comment] 2019-05-31 19:53
Closing - this is a duplicate of/will be addressed in https://github.com/mozilla-mobile/fenix/issues/3004

**Closed** 2020-08-26 20:30 UTC
Labels: Feature:Collections, Release Blocker, 🐞 bug
