### ISSUE TITLE
[Bug]: Fenix does not respect Browser.EXTRA_APPLICATION_ID, Fennec did

### ISSUE THREAD

**Issue by RenateUSB** [mozilla-mobile/fenix#23329] opened 2022-01-20 12:16 UTC
### Steps to reproduce

In an Android shell:

    $ am start -a android.intent.action.VIEW -d https://httpstat.us/ -e com.android.browser.application_id MyTab
    Starting: Intent { act=android.intent.action.VIEW dat=https://httpstat.us/... (has extras) }

### Expected behaviour

I expect that different URLs will open in the same tab.
I expect that repeating the intent with the same URL will cause it to refresh (do a network fetch) each time.
I see this behavior in Fennec 68.11.0

### Actual behaviour

Different URLs open in different tabs.
Repeating the intent with the same URL will cause it to switch to the tab but not refresh (do a network fetch).
I see this behavior in Fenix 96.1.1

### Device name

Onn8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

96.1.1

### Additional information

https://support.mozilla.org/en-US/questions/1364869

**Comment by kbrosnan** [comment] 2022-01-20 21:20
Duplicate of https://github.com/mozilla-mobile/fenix/issues/4106

**Closed by kbrosnan** 2022-01-20 21:20 UTC
Labels: 🐞 bug, needs:triage
