### ISSUE TITLE
[Bug] When Scroll to Hide Toolbar is disabled, margin black bar at the bottom of fullscreen videos

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#15272] opened 2020-09-21 17:53 UTC
## Steps to reproduce
![image](https://user-images.githubusercontent.com/25442310/93802686-a2cc9880-fbf8-11ea-9ad2-067a852d10aa.png)

### Device information

* Android device: ?
* Fenix version: ?

**Comment by hwinnemoe** [comment] 2020-09-21 20:58
Related to/Duplicate of #14974, see [this comment ](https://github.com/mozilla-mobile/fenix/issues/14974#issuecomment-694385050) in the issue.

**Comment by sv-ohorvath** [comment] 2020-09-23 09:51
Verified as fixed on Beta 82.0 and Nightly 9/23.

**Closed by sv-ohorvath** 2020-09-23 09:51 UTC
Labels: eng:qa:verified, 🐞 bug
