### ISSUE TITLE
[Bug] Extensions that have not been published for Android are allowed to be installed

### ISSUE THREAD

**Issue by dessant** [mozilla-mobile/fenix#15840] opened 2020-10-11 17:40 UTC
Extensions that have not been published by extension authors for Android can be added to AMO collections and installed on Fenix, leading to support requests and negative reviews.

I have been contacted several times about Clear Browsing Data being broken on Fenix Nightly, when in fact the extension has not been published for Android, because the required API is missing.

Please filter out extensions that do not have an Android target on AMO when a collection is loaded in Fenix.

**Comment by kbrosnan** [comment] 2020-10-12 20:41
@agi @csadilek do we have an issue/bug about restricting installs to manifests with the correct appIDs?

**Comment by agi** [comment] 2020-10-12 23:12
I don't think we have one, but the same can happen with extensions that use APIs that are not currently supported in Fenix but are marked as Android compatible, so I'm not sure how much that's going to help.

**Comment by dessant** [comment] 2020-10-13 05:05
@agi, marking an incompatible extension as available for Android is a mistake on the maintainer's part, filtering out extensions without an Android target will still help projects that have been published correctly.

**Comment by KrasnayaPloshchad** [comment] 2020-10-13 16:09
Every user should claimed whether their extension designed for Firefox for Android if an user publish their extension at the Developer Hub. This can be reproduced with [Save Page WE](https://addons.mozilla.org/android/addon/save-page-we/) and [SingleFile](https://addons.mozilla.org/android/addon/single-file/), during the 68.x releases I can see Save Page WE is unable to install and SingleFile can be install directly, but both these extensions marked as “Not available on Firefox for Android” after I updated to the latest release, and now I can install them directly in the Nightly release with instructions from Mozilla Blog.

**Comment by jvillalobos** [comment] 2020-10-13 17:34
Users that are going out of their way to enable this installation method on Nightly should know that these are unsupported extensions and may not work. The compatibility setting on AMO is not a reliable method to determine what will or will not work. I don't think we should change the current behavior.

**Comment by dessant** [comment] 2020-10-13 17:43
@jvillalobos, it is a reliable method when the developer tells you that the extension is not available on Android, and it makes no sense to let people install extensions that are explicitly marked as incompatible.

You don't have to be a power user to be affected by this, the default collection that is being curated by Mozilla employees contains some extensions that have never been published or in any way compatible with Firefox for Android, and they are installable by opening the add-on manager.

**Comment by jvillalobos** [comment] 2020-10-13 17:54
[The steps needed to enable this feature](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/) are not at all trivial. Users can't just flip a switch to enable arbitrary add-ons and shouldn't expect them to work.

**Comment by dessant** [comment] 2020-10-13 17:59
Again, the default collection in Fenix contains extensions that have not been published for Android, you don't have to configure anything to install them.

@jvillalobos, is the Firefox for Android checkbox being deprecated on AMO?

![Screenshot from 2020-10-13 20-57-51](https://user-images.githubusercontent.com/7513068/95897865-e1d4b080-0d96-11eb-91d6-6ac3163a8ec2.png)

**Comment by jvillalobos** [comment] 2020-10-13 18:31
> Again, the default collection in Firefox Nightly contains extensions that have not been published for Android, you don't have to configure anything to install them.

That's surprising to me, but I'll let the Fenix people look into and respond to that.

> @jvillalobos, is the Firefox for Android checkbox being deprecated on AMO?

We're making some changes on AMO to better support Fenix and that might involve changing how that setting works. It's still TBD, however.

**Comment by jvillalobos** [comment] 2020-10-13 18:35
[This is the collection](https://addons.mozilla.org/collections/4757633/7dfae8669acc4312a65e8ba5553036/) that should be the default in the current Nightly. Do you see something different?

**Comment by dessant** [comment] 2020-10-13 19:29
Yes, that's the collection which contains untested extensions.

**Comment by dessant** [comment] 2020-10-13 20:27
https://github.com/mozilla-mobile/fenix/issues/15784

Would opening a tab that shows this GitHub issue when an incompatible extension is installed on Fenix be acceptable as a workaround? I really don't want to continue spending my time on support requests for an unsupported platform, and people usually don't read the AMO description first.

In Fennec it was easy to prevent this issue, but things are changing and I'm afraid extension developers were left for the time being to deal with the fallout.

**Comment by clientenq** [comment] 2020-10-14 17:06
> Users that are going out of their way to enable this installation method on Nightly should know that these are unsupported extensions and may not work. The compatibility setting on AMO is not a reliable method to determine what will or will not work. I don't think we should change the current behavior.

That would be reasonable if we dont take into account the large amount of complaints and negative feedback for missing extensions and FF providing Nightly with custom selection as alternative. I agree users should be aware what nightly is and is not. Providing Nightly as alternative with so many complains we can expect even normal users start using this and get disapointed (again) by the minimal addon support by FF. Since it does not look like FF will support more extensions soon while users depend on these you can expect users will find alternatives besides using Nightly. So what is a better solution then saying sorry no support or quality there, figure it out yourself to all those users requesting more professional addon support from FF?

**Comment by agi** [comment] 2020-10-14 17:15
> Again, the default collection in Firefox Nightly contains extensions that have not been published for Android, you don't have to configure anything to install them.

@dessant What unsupported extensions are available in nightly by default?

**Comment by dessant** [comment] 2020-10-14 17:20
@agi, I have linked it above: https://github.com/mozilla-mobile/fenix/issues/15784

It was removed right after I've made that comment, though keep in mind that the collection is fetched once and then loaded from a local cache. The extension will be visible and installable from the add-on manager until a new collection ID is created for the curated extension list.

**Comment by agi** [comment] 2020-10-14 17:22
> It was removed right after I've made that comment, though keep in mind that the collection is fetched once and then loaded from a local cache. The extension will be visible and installable from the add-on manager until a new collection ID is created for the curated extension list.

I don't think that's accurate, IIRC we check the collection every 24h or so.

**Comment by dessant** [comment] 2020-10-14 17:32
Regarding the main topic of the issue, how would you move forward? How can developers explicitly signal whether an extension is considered compatible or not, to avoid all the wasted time for everyone involved?

Should the [browser_specific_settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings) manifest key be extended to provide compatibility information for Firefox for Android?

**Closed** 2021-04-12 18:21 UTC
Labels: Feature:WebExtensions, wontfix, 🐞 bug
