### ISSUE TITLE
FNX3-16600 ⁃ [Bug] Homescreen sessions disappear into an unrecoverable state

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#2814] opened 2019-05-24 04:39 UTC
## Steps to reproduce (not consistent)
1. Open 5-6 tabs.
1. Background the app for some time.

![Screenshot](https://user-images.githubusercontent.com/1370580/58303062-554dda80-7dbc-11e9-9a51-ea5ac4491385.png)UNITO-UNDERSCORE!20190524-002055!

### Device information
* Android device: Pixel 2
* Fenix version: Nightly (23/05/2019)

> 1.0.1921 (Build #11431806 68.0-20190520141152)
> Thursday 5/23@ 6:05 PM

**Comment by colintheshots** [comment] 2019-06-05 21:37
@vesta0 I cannot seem to reproduce this bug. I tried Don't Keep Activities, killing the Fenix process while backgrounded, waiting awhile while backgrounded, etc.

**Comment by jonalmeida** [comment] 2019-06-05 21:47
@mozillamarcia had reported the same issue as well (linked), but maybe this was during a bad release and may no longer be an issue. I wonder if they can still repro it too.

**Comment by colintheshots** [comment] 2019-06-06 01:05
I just managed to repro this issue. Oddly enough, it doesn't repro by a simple save and restore. It's something much more complex.

**Comment by vesta0** [comment] 2019-06-06 17:52
@colintheshots sounds like this is not easy to reproduce meaning that it doesn't occur frequently. Assuming that is the case, I am removing the MVP blocker label.

Would you please provide the STR to reproduce so we can further investigate?

**Comment by pocmo** [comment] 2019-06-07 13:53
It seems like what you are seeing here is GeckoView's content process getting killed by Android (not a crash!). In this case GV recreates the content process and AC recreates the `GeckoSession`s to keep the browser responsive - however they all point to `about:blank` until the state is restored (I assume that's why you see this `A` favicon here).

So what you are seeing here is a dupe of #1577 and you can reproduce it with the STRs from #1577. Fixing #1577 depends on AC ([#3310](https://github.com/mozilla-mobile/android-components/issues/3310)) which depends on GeckoView [bug 1557096](https://bugzilla.mozilla.org/show_bug.cgi?id=1557096).

So I think we can close this and just track #1577.

**Comment by vesta0** [comment] 2019-06-10 17:34
Closing based on @pocmo comment above.

**Comment by softvision-miralobontiu** [comment] 2019-06-11 09:13
Verified as fixed on the latest build 1.0.1924 (#11620622), with Motorola Nexus 6 (Android 7.1.1), OnePlus 5T (Android 9), and Huawei MediaPad M2 (Android 5.1.1).

**Closed** 2020-08-12 17:43 UTC
Labels: eng:qa:verified, needs:ac, needs:investigation, 🐞 bug
