### ISSUE TITLE
[Bug] Top and bottom margin is not aligned after fullscreen video

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#18667] opened 2021-03-27 21:24 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Go to m.youtube.com
Open any video and make it fullscreen
Exit fullscreen mode

### Expected behavior
Top and bottom margin is aligned with system bars

### Actual behavior
They're not

![Screenshot_20210328-002130_Firefox_Beta](https://user-images.githubusercontent.com/17825767/112735267-e3b4b980-8f5b-11eb-8048-fa97a9600774.png)

### Device information

* Device vendor / model and Android version: Xperia XZ1 Android 11
* Firefox for Android version: 88 beta 1

**Comment by sflorean** [comment] 2021-03-29 06:44
Tested on 88.beta.1 and on Nightly build, with the following devices and couldn't reproduce the issue:
- Pixel 3 (Android 11)
- Samsung Note 10 (Android 11)
- LG G7 Fit (Android 8.1)

@hakkikaancaliskan can you give us the exact link that you used in order to reproduce this issue? This is reproducible on latest Nightly build?

**Comment by Mugurell** [comment] 2021-03-29 06:51
I cannot reproduce this on the current Nightly bu I can reproduce it on the current beta from playstore.

Recording of the beta app on a Pixel 3 with Android 11:

https://user-images.githubusercontent.com/11428869/112797303-e0145600-9073-11eb-80c0-6d54d4a69487.mp4

The issue is even worse for me since the url bar  is translated almost entirely under the display and cannot be interacted with. With the only solution for getting the url bar back being to restart the app.

**Comment by Mugurell** [comment] 2021-03-29 06:57
Seems to be a general issues for the "enter fullscreen - exit fullscreen" scenario.

https://user-images.githubusercontent.com/11428869/112798047-0090e000-9075-11eb-9d72-e8b5e5ff9069.mp4

**Comment by kbrosnan** [comment] 2021-03-29 18:15
We should figure out what needs uplift here. This seems like an easy to hit bug. 

- Release is unaffected v 87.0.0
- Beta is affected v 88.0.0-beta.2
- Nightly is unaffected
- GVE 88-b5pre is unaffected

**Comment by codrut-topliceanu** [comment] 2021-03-30 07:06
@jonalmeida Agreed. 
I believe the 2nd solution would be the best course of action as it won't need anything from AC. (I've tested both solutions yesterday anyway). I'll have a PR up soon.

**Comment by ebalazs-sv** [comment] 2021-04-01 13:59
Verified as fixed on Beta 88.0.0-beta.3 with LG G7 Fit (Android 8.1).
I will close this issue.

**Closed by ebalazs-sv** 2021-04-01 13:59 UTC
Labels: Beta, Feature:Browsing, needs:uplift, qa-triaged, 🐞 bug
