### ISSUE TITLE
[Bug] Unable to Ctrl-Click with Android Tablet

### ISSUE THREAD

**Issue by atupeck** [mozilla-mobile/fenix#9754] opened 2020-04-07 01:22 UTC
## Steps to reproduce
Open browser with an attached keyboard and mouse
Find link, hold Ctrl and click, no actions occur
### Expected behavior
Opens link in new tab
### Actual behavior
N/A
### Device information

* Android device: Samsung Galaxy Tab S6
* Fenix version: 4.2.1

**Comment by kbrosnan** [comment] 2020-04-07 23:56
Closing as a dupe of #3729 as this is one specific case and 3729 is more general.

**Closed** 2020-04-11 17:29 UTC
Labels: needs:triage, 🐞 bug
