### ISSUE TITLE
[Bug] On slow network, main thread blocked after clicking url bar from homescreen on cold startup due to MLS

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#9935] opened 2020-04-14 22:09 UTC
## Steps to reproduce
- Build `geckoBetaFennecBeta` or `geckoBetaForPerformanceTest`
- Start app (cold start)
- Click url bar

### Expected behavior
Quick to open

### Actual behavior
Long pause. In `forPerformanceTest` with the profiler going (so with much overhead), it takes > 10 seconds.

### Device information

* Android device: P2
* Fenix version: master 152642d98d9a984c572033ac55d363d6307ddd6a

---

I took a profile and it looks like `FenixSearchEngineProvider.installedSearchEngines` is blocking the main thread for a long time:
![Screen Shot 2020-04-14 at 15 00 43](https://user-images.githubusercontent.com/759372/79278983-cc231480-7e61-11ea-82a1-636dabf15b06.png)

I looked at blame and nothing changed in Fenix so this is likely an issue in a-c.

---

Comment form @MarcLeclair :  This issue occurs because Fenix _blocks_ the UI thread when calling `LocationServices`  in `FenixSearchEngineProvider.kt` in method `installedSearchEngine()`. The best way to see this is to put `LocationServiceS.dummy()` in the `else` branch. Since the app built locally doesn't have any token, the app makes empty http request that just hangs the app.

FYI it does occur on the first click as the most obvious but it will happen on any subsequent calls, it just seems faster ( no idea why, didn't look much further into it).

**Comment by mcomella** [comment] 2020-04-14 22:11
@csadilek Do you know what might have changed in a-c to have caused this?

**Comment by csadilek** [comment] 2020-04-15 00:13
@mcomella looks like the cause is this: https://github.com/mozilla-mobile/fenix/commit/d89fbd7af84a6b8e59aea9bd438131b5c81ef802

Basically, the lack of an API key for MLS. I've verified that switching to the dummy location provider for those builds fixes it.

**Comment by mcomella** [comment] 2020-04-15 00:35
I think the possible solutions are:
1. Use dummy MLS if API key is not available (i.e. based not on build variant but build inputs)
2. Use a production version of MLS without an API key

I'd rather we do 2. so we can mimic the performance characteristics of production builds (and developers are closer to running what production builds do in their debug builds) but I'm not sure how feasible that is.

**Comment by mcomella** [comment] 2020-04-16 00:32
For context, MLS is the Mozilla Location Service which is used to determine roughly where the user is so we can provide locale-specific search engines for them.

---

During triage we realized this could be indicative of an underlying performance problem: if a production version of MLS without an API key pauses the app for 10+ seconds, can the production version with the API key also create a critical performance issue?

@pocmo Can you explain to me why this timeout occurs if we don't have an API key? Do you think it's possible that this is indicative of an underlying performance problem we need to address? fwiw, csadilek thought it could be a perf problem but not a P1 perf problem.

Assigning self to remember to identify the priority.

**Comment by pocmo** [comment] 2020-04-22 08:30
> @mcomella looks like the cause is this: d89fbd7

This is not the cause. It is trying to put even more bandaid on this thing. :)

> @pocmo Can you explain to me why this timeout occurs if we don't have an API key? Do you think it's possible that this is indicative of an underlying performance problem we need to address? fwiw, csadilek thought it could be a perf problem but not a P1 perf problem.

There are definitely multiple weird things going on in Fenix and I didn't have the time to look into them. Fenix has some wrappers around the AC search code and those seem to change the behavior in a way that I do not understand yet.

* AC's `SearchEngineManager` does only try once per process lifetime to determine the location and only if it was never done before and is not cached. In Fenix those seemed to happen more often, sidesteping our implementation.
* Everything accessing SearchEngineManager needs to use the suspending methods asynchronously since we may need to do at least one disk read per process (or network request per install). If the app freezes then this does not seem to be the case (or the wrapper does something else synchronously)
* Our MLS implementation in AC currently uses a 10 second connect and read timeout. That is probably a bit long as well and we could consider making that shorter - although that is not the root problem here.

So yeah, it does make sense to use the dummy implementation in builds that don't have an API key. No need to ping the server for nothing. But at the same time the app should not freeze if this request takes long and as of now it can take at least 10+ seconds with those timeouts.

**Comment by pocmo** [comment] 2020-04-22 13:00
>     * Our MLS implementation in AC currently uses a 10 second connect and read timeout. That is probably a bit long as well and we could consider making that shorter - although that is not the root problem here.

FWIW, those are exactly the same timeouts as Fennec uses:
https://searchfox.org/mozilla-esr68/source/mobile/android/base/java/org/mozilla/gecko/search/SearchEngineManager.java#399

**Comment by liuche** [comment] 2020-04-23 23:51
We're blocking the main thread when fetching geolocation for search engines. This is even worse when there is no MLS key (like with the two build flavors that mcomella has mentioned). Sebastian and mcomella have good suggestions in their comments above, and these would be good perf bugs to try profiling (for before/after).

**Comment by liuche** [comment] 2020-05-14 18:23
Question for UX, while we're waiting for search engines to load, we're planning on just showing an empty list.

**Comment by ekager** [comment] 2020-06-02 17:49
See similar issue in the wild: #10793

**Comment by liuche** [comment] 2020-06-03 17:12
We should handle the technical part of this, but I've split out #11195 for the UX part of this issue, because we can work on not blocking the main thread without waiting on UX and should make progress on that early.

**Comment by sblatz** [comment] 2020-06-12 18:28
I began working on this and know where the issue is. My question is, what should the behavior even be? If the user is on a slow network and we can't reach their "default search engine" the search field is not going to work at all. We have no engine to get search suggestions against, nor an engine to pass the query to when the user presses "enter"

Does it even make sense to open this screen if a user can't do anything on it?

**Comment by mcomella** [comment] 2020-06-17 00:05
@sblatz Without context, my opinion would be that we should open the search screen immediately, loading the search engine providers asynchronously and inserting them when available. There probably needs to be some UX to indicate that the search providers are loading.

If the app freezes and is unresponsive to subsequent input, a user will rightly blame Fenix for being slow. If the app is waiting to provide functionality because it hasn't fetched those components from the network and the app makes it clear to users that that is the case, the user will rightly blame the network connection. We want the user to assign proper blame so that they can address their problem themselves (e.g. restart router) and, more selfishly, so that they're not blaming us for things that aren't our fault. 😅

**Comment by liuche** [comment] 2020-06-17 00:24
Maybe we could show some kind of "loading" animation? @sblatz could you add a screenshot of what a user might see if they are, say, on a terrible network, and don't get any search engines returned? That way, UX can help us out with a quick solution, while considering a longer one.

**Comment by pocmo** [comment] 2020-06-17 10:22
> I began working on this and know where the issue is. My question is, what should the behavior even be? If the user is on a slow network and we can't reach their "default search engine" the search field is not going to work at all. We have no engine to get search suggestions against, nor an engine to pass the query to when the user presses "enter"

Is that currently the case? The intended behavior from AC side is that we have a 10 seconds timeout to get a region from MLS. If we don't then we will use the locale instead. Once we got a region from MLS we will cache it and no longer query MLS. No search engine at all should not happen (except in the very first 10 seconds window).

**Comment by sblatz** [comment] 2020-06-17 17:41
@pocmo Well I think the root issue is that we're waiting 10 seconds for that query. We currently can't even launch the SearchFragment without that resolving, so it can potentially hang for 10 seconds before launching. 

One solution is decreasing that delay.

Another is a much larger refactor that makes it so users can get to the SearchFragment and get a callback when MLS resolves itself.

**Comment by mcomella** [comment] 2020-06-17 23:57
Blocking the main thread for any user perceptible period of time will make Fenix feel slow so I'd prefer the second solution.

**Comment by pocmo** [comment] 2020-06-18 09:24
> @pocmo Well I think the root issue is that we're waiting 10 seconds for that query. We currently can't even launch the SearchFragment without that resolving, so it can potentially hang for 10 seconds before launching.

Yeah, absolutely. This should not happen on the main thread. Your comment sounded like there can be a situation where search will not function at all (even after the 10 seconds).

> One solution is decreasing that delay.

We considered that too. We took the 10 seconds timeout from Fennec ... so it seems like something that could/should work as is.

> Another is a much larger refactor that makes it so users can get to the SearchFragment and get a callback when MLS resolves itself.

Just to clarify: You are not invoking MLS manually anywhere, right? This is about waiting for the `SearchEngineManager` to return `SearchEngine`s asynchronously, right? That's something we will probably need to do in any case since loading the search engines will always require disk I/O (the first time). If I could travel back in time I'd never expose synchronous methods on `SearchEngineManager`. :)

**Comment by liuche** [comment] 2020-06-18 17:54
Bram has made some suggestions in the bug we split out for UX feedback: https://github.com/mozilla-mobile/fenix/issues/11195#issuecomment-640390683

**Comment by sblatz** [comment] 2020-06-18 18:33
@pocmo this is the function getting called before moving to SearchFragment. 

https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/searchengine/FenixSearchEngineProvider.kt#L85

It causes a blocking because it's runBlocking. 

I don't think we're directly invoking MLS, rather just waiting for it to completely resolve to get an answer from `installedSearchEngines` which can cause up to a 10 second delay 😕. My point is: this is a pretty large refactor because there are *tons* of places that depend on this being "synchronous" in nature. I'm happy to refactor this to be async and have a callback, but it's a much larger project (unless there's something I'm missing here?)

**Comment by mcomella** [comment] 2020-06-22 18:05
@sblatz Maybe this design will require less refactoring effort: we can initialize everything to the locale search engine to start, then async fetch using the network, and update the engines when the async fetch completes. That way a user is never blocked from executing their actions and we're not fundamentally changing the UX.

For context, I'd like to get this change in by code freeze because being blocked is not a great user experience.

**Comment by sblatz** [comment] 2020-06-23 20:19
The smallest change we could do before launch is to have a default list that, if the user opens the search screen really quickly, is presented for that whole time (it never gets a callback to update even though the other engines are loading in the background). 

This is because the SearchFragment and a couple other dependencies need the enginelist *now* before presenting, and building in functionality for them to update on the fly was a much bigger (and scarier change) this close to code freeze. 

This gives us the performance win, with the least likelihood of causing critical bugs/crashes. 

@boek is pushing a PR soon!

**Comment by sblatz** [comment] 2020-06-23 21:00
@mcomella please validate this fix resolves the issue 😄

**Comment by AmyYLee** [comment] 2020-06-24 00:26
@sblatz Is UX still needed for this issue? if not, I'll remove the tag.

**Comment by mcomella** [comment] 2020-06-24 16:53
@sblatz @boek I checked out the latest master 673507d9b391dfe01aa028b94b482ff37bd2bd87 and I still see the issue in profiles: https://share.firefox.dev/2ZjPRDd

It looks like `getDefaultEngine` calls `installedSearchEngines` and we actually call `getDefaultEngine` twice.

**Comment by mcomella** [comment] 2020-06-25 18:40
I investigated the issue I discovered. It appears the following call stack happens:
```
installedSearchEngines
- installedSearchEngineIdentifiers
 - localeAwareInstalledEnginesKey
  - localizationProvider.determineRegion
   - RegionSearchLocalizationProvider.determineRegion
    - MozillaLocationService.fetchRegion
```

When the region has not been successfully fetched, we try to fetch it from the network. The connection timeout is 10s and the read timeout is 10s so, in the worst case, we'd block for 20s in a single call. If the region has been successfully fetched, we fetch it from SharedPrefs. This method gets called multiple times on SearchFragment startup so it's possible to block for longer than 20s if we're unable to connect to the server. However, if we ever connect to the server successfully once, we cache the value and this should never happen again because we can always read from SharedPrefs.

**I think we need still need to address this issue: even if it's unlikely to happen and only then likely to happen only once, the potential blocking for multiple seconds for the first user action on first run leaves a poor first impression and I'd prefer to avoid that.** Furthermore, in the event that the MLS server is down, every new user would experience this.

Notes on reproducing:
- I experienced this in my local builds because I don't have an MLS key so presumably I contact the server, receive an error response, and close the connection each time this method is called on SearchFragment startup.
- I didn't experience this in production builds on my Pixel 2 because I have a fast connection, a fast device, and was able to contact the server successfully so I repeatedly used the cached value
  - I also tried with airplane mode but there was no delay: I assume the HTTP lib knows I'm not connected to the internet and returns an error immediately
- I experienced this in production builds on an Android emulator with simulated network latency. As expected by theory, this delay (maybe 10s anecdotally? it's based on network connection) occurred once and never occurred again, even after killing the app

**Comment by liuche** [comment] 2020-06-25 21:10
Could this be causing this crash if we're loading without search engines? https://github.com/mozilla-mobile/fenix/issues/11906

**Comment by mcomella** [comment] 2020-06-26 16:56
I believe this will be resolved with the PR https://github.com/mozilla-mobile/fenix/pull/11974#pullrequestreview-437918649

**Comment by sv-ohorvath** [comment] 2020-06-29 12:05
From https://github.com/mozilla-mobile/fenix/pull/11974#pullrequestreview-437918649 this was verified from the perf perspective. @boek Does this need manual QA as well?

**Closed** 2020-07-13 17:00 UTC
Labels: E5, eng:performance, eng:qa:not-needed, size M, 🐞 bug
