### ISSUE TITLE
FNX-3451 ⁃ Use gesture to navigate between tabs

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10346] opened 2020-05-01 05:41 UTC
## User Story
As a user, I want to be able to use gestures to navigate between tabs, so I can find and process the information that I need faster. 

## Dependencies
Geckoview

### Acceptance Criteria
* I can use a gesture to navigate between tabs

**Comment by yoasif** [comment] 2020-05-01 16:22
Maybe a dupe of #396 and #176?

**Comment by Dunexus** [comment] 2020-05-01 18:58
Yes it is part of https://github.com/mozilla-mobile/fenix/issues/176 meta and was previously tracked by https://github.com/mozilla-mobile/fenix/issues/3481

**Comment by yoasif** [comment] 2020-06-08 21:05
> Yes it is part of #176 meta and was previously tracked by #3481

You mean https://github.com/mozilla-mobile/fenix/issues/396 ;)

**Closed** 2020-08-11 00:30 UTC
Labels: Feature:Gesture, Feature:Tabs, P3, Skittle, feature request 🌟
