### ISSUE TITLE
[Bug] "Search or enter address" text is flickering under search bar when switching  from normal to private or vice versa browsing

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#2869] opened 2019-05-27 08:59 UTC
### Steps to reproduce
1. Install and launch Fenix.
1. After the on-boarding tap on the **`Enable Private Mode`** button.
    1. Expected behavior
Fenix is switched to private mode and smooth animation is displayed for all elements.
    1. Actual behavior
When switching to private mode or normal mode there is a text flickering under the **`Search bar`.**
    1. Device information

* Android device: **`Samsung Galaxy Note 9 (Android 8.1.0)`**
* Fenix version: **`1.0.1922(Build #11470614 68.0-20190520141152) 5/27`**
    1. Notes
For more details please see the [Video](https://drive.google.com/file/d/19WnuHb5aqQFLYDhUuknPKhntTHeQCbXP/view?usp=sharing).

**Comment by TitanNano** [comment] 2019-05-27 11:26
duplicate of  #2642

**Comment by abodea** [comment] 2019-05-27 12:15
Hello, @TitanNano as far as I can see in issue #2642 he is referring to the icon from the search bar, I understand that it's the same search bar, but I'm referring to a complete another issue.
I didn't saw any problem with my device on the icon. Do you still is this a duplicate? If yes I will close this issue and add my part to that bug.

Regards,
Andrei

**Comment by abodea** [comment] 2019-05-27 12:31
Also, note that I tried on other devices with android 6 and 7 but I the icon didn't disappeared as described in #2642 only the text was flickering.

**Comment by TitanNano** [comment] 2019-05-27 21:01
@abodea this is a frame from your video
<img width="739" alt="image" src="https://user-images.githubusercontent.com/4500858/58439220-3b213e80-80d3-11e9-9777-9bf74c634ac7.png">
the icon is clearly disappearing, it just happens very quickly.

**Comment by abodea** [comment] 2019-05-28 06:55
Thank you @TitanNano I will close my issue and add my input on the one you mentioned above.

**Closed** 2020-08-26 20:27 UTC
Labels: 🐞 bug
