### ISSUE TITLE
[Bug] Lots of crashes when losing wifi internet access

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#17030] opened 2020-12-14 17:59 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
I ran into this when my router had some issues, so I was still connected to wifi but had no access to the internet. Maybe the easiest way to reproduce is to connect to wifi but unplug the network cable from your router (also make sure mobile date is disabled). Then open your browser and click on an open tab

### Expected behavior
No crash

### Actual behavior
Crashes. It also seems to crash when clicking the report button on the previous crash and opening the browser again.
https://crash-stats.mozilla.org/report/index/098910e5-5bd1-446a-b2b5-68cfe0201208
https://sentry.prod.mozaws.net/operations/fenix/?query=3f60a78d5c3b4fdb99c0c82d9a38dbaa
https://sentry.prod.mozaws.net/operations/fenix/?query=95a0d47c30ba471284916d747211e0aa
### Device information

* Android device: Huawei Nova 6 (Android 10)
* Fenix version: Nightly build #20201203094726

**Comment by kbrosnan** [comment] 2020-12-14 18:22
Update to a more recent Nightly version. Dupe of #16886

**Closed by kbrosnan** 2020-12-14 18:22 UTC
Labels: needs:triage, 🐞 bug
