### ISSUE TITLE
Fix SOFT_INPUT_ADJUST_RESIZE deprecation in SearchDialogFragment

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#17805] opened 2021-02-03 20:59 UTC
[Documentation](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#SOFT_INPUT_ADJUST_RESIZE) 

https://github.com/mozilla-mobile/fenix/blob/f4a7b4c066b98e8fd999268d702f4d5d81815021/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt#L103

**Comment by codrut-topliceanu** [comment] 2021-02-23 12:09
I'm looking for some input on this as it's a bit more tricky than I thought.

- So `SOFT_INPUT_ADJUST_RESIZE` is used in `SearchDialogFragment.kt` in `onStop` while `SOFT_INPUT_ADJUST_NOTHING` is used in `onStart` in order to make sure that **geckoView is not resized** when searching which would lead to smaller looking site. ( https://github.com/mozilla-mobile/fenix/issues/14279 and https://github.com/mozilla-mobile/fenix/issues/15923 , I haven't been able to reproduce that issue, unfortunately. )
- In our `AndroidManifest.xml` we declare `android:windowSoftInputMode="adjustResize"` on several activities including `HomeActivity`, this was added waaay back in https://github.com/mozilla-mobile/fenix/issues/118 (https://github.com/mozilla-mobile/fenix/commit/a6004fea2069cd0c4f013783ef933869275e2428). It seems to have been added to accommodate the Find in Page feature.
- However, in our testing, the Find in Page feature covers the geckoview leading to cases where the found text is not in view, hidden behind the Find in Page editText. (logged https://github.com/mozilla-mobile/fenix/issues/18122). So the `adjustResize` doesn't do anything in this particular case.
- The replacement for the deprecated `SOFT_INPUT_ADJUST_RESIZE` is to use `setOnApplyWindowInsetsListener` and `insets.getInsets(WindowInsets.Type.ime())` , the latter having been added in API 30.

All of these lead to the following questions:
- Do we even need `adjustResize` in the manifest? If we don't need it then we can safely remove the above mentioned code in `SearchDialogFragment.kt` and the problem is solved.
- If we do need `adjustResize` we will need to move it from the manifest to the activities where it is needed (like `HomeActivity` and maybe `AuthCustomTabActivity`, `ExternalAppBrowserActivity`) and depending on `VERSION.SDK_INT` we can choose to use either `SOFT_INPUT_ADJUST_RESIZE` or `setOnApplyWindowInsetsListener`, right?

@boek Sorry for pinging you regarding this, but any input would be appreciated.

**Comment by sflorean** [comment] 2021-03-22 16:39
Verified as fixed on latest Nightly with the following devices:
- Samsung Note 10 (Android 11).
- Nokia 6 (Android 7.1.1)
- Pixel 3 (Android 11)
Regression 18546.

**Comment by mcarare** [comment] 2021-06-30 12:15
This si not done as the fix was reverted. Reopening.

**Closed** 2022-04-24 10:51 UTC
Labels: eng:qa:verified, eng:health, help wanted, Android:11, wontfix
