### ISSUE TITLE
[Bug] Cannot switch to normal tabs if Fenix is opened in private mode 

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#5681] opened 2019-09-30 17:18 UTC
## Steps to reproduce
Long press the Firefox Icon
Touch "new private tab"
Touch the tabs icon
Close the currently open tab
Touch the mask button to leave the private mode

### Expected behavior
A normal browsing is started

### Actual behavior
A white page is exhibited

### Device information

* Android device: Galaxy A5 2017 Android 8.0
* Fenix version: 190928 nightly

**Comment by sblatz** [comment] 2019-09-30 21:10
I can reproduce this and I believe it should be a v2.1 release blocker.

**Comment by sblatz** [comment] 2019-09-30 21:15
It looks like what's happening here is we're opening directly to `BrowserFragment` when the user stops using private mode. When there's no normal session it has a "blank white screen" but if the user has an open normal tab, it just opens that.

![demo](https://user-images.githubusercontent.com/4400286/65917605-9a96a000-e38c-11e9-94ec-9f966caedaa1.gif)

**Comment by sv-ohorvath** [comment] 2019-10-01 09:23
Verified this is fixed on Nightly 10/1. Will check on the RC build as well.

**Closed** 2019-10-01 14:37 UTC
Labels: Release Blocker, 🐞 bug

**Comment by sv-ohorvath** [comment] 2019-10-02 14:27
Verified as fixed on 2.1.0-rc3
