### ISSUE TITLE
[Bug] The Flipboard PWA does not have the correct icon or name

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#17632] opened 2021-01-26 06:36 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Go to flipboard.com
Click install
### Expected behavior
The correct icon and name is shown
### Actual behavior
Only a wilhite icon and "web site" is shown
### Device information

* Android device: Redmi Note 5
* Fenix version: Nightly

**Comment by s-ankur** [comment] 2021-01-26 06:37
![Screenshot_2021-01-26-12-06-48-182_com teslacoilsw launcher](https://user-images.githubusercontent.com/33252312/105809054-fe57ca00-5fce-11eb-9f09-640a972a07ad.jpg)

**Comment by evilpie** [comment] 2021-01-26 21:00
I think flipboard's manifest file is broken: https://s.flipboard.com/webapp/images/favicon/site.webmanifest. The name is missing and the icons are 404.

**Comment by s-ankur** [comment] 2021-01-27 14:49
I guess we can close this then. Somehow flipboard is on every "Top 10 PWA" article

**Comment by mcarare** [comment] 2021-01-27 16:01
Closing this as the problem is in PWA's manifest, not in Fenix.

**Closed by mcarare** 2021-01-27 16:01 UTC
Labels: Feature:PWA, needs:triage, 🐞 bug
