### ISSUE TITLE
FNX-5413 ⁃ [Bug] Site permission string isn't wrapped

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#2034] opened 2019-04-25 15:18 UTC
Pixel 2, 04/25

![Screenshot (Apr 25, 2019 11](https://user-images.githubusercontent.com/102331/56747331-c19cd600-674b-11e9-9e52-a2c4e45b6c3a.png)UNITO-UNDERSCORE!07!UNITO-UNDERSCORE!57 AM)!

**Comment by kbrosnan** [comment] 2019-04-27 03:59
dupe of #1416

**Closed** 2020-08-11 13:42 UTC
Labels: Feature:SitePermissions, 🐞 bug
