### ISSUE TITLE
Import bookmarks to collections (to have bookmarks on the homescreen)

### ISSUE THREAD

**Issue by OlliKn** [mozilla-mobile/fenix#14427] opened 2020-08-29 08:26 UTC
When people are suposed to use collections so there must be an easy way for them to move there bookmarks to collections. Open every bookmark in a tab and the choose /add to collections/ is not the way to make the User happy with and acceptingor or even liking collections.

**Comment by cadeyrn** [comment] 2020-08-29 08:59
Collections and bookmarks are different concepts and collections are not meant as a different interface element for bookmarks. For example, tabs in a collection contains the history of the tabs, bookmarks don't do this. So I don't think it makes much sense as long as Mozilla does not decide to change the concept of collections.

But as far as I know there are plans to improve collections. I don't know the details so let's see how the future of collections will look like.

**Comment by OlliKn** [comment] 2020-08-29 10:16
Thanks for the fast answer. No ordinary User is aware of this concepts. He Sees just two places where He can reach his saved urls. The one forced on the Main Page and the other More clicks away. The User will want to migrate his urls to the Main Page. Concepts do not matter there.. So IT would make Some sense. Especially in this confusing Situation where many people try to cope with this New ways. It really really would calm some people down. But thanks again 🙂. I just wanted to mention this idea from practical User view.
Von: Sören Hentzschel <notifications@github.com>
An: mozilla-mobile/fenix <fenix@noreply.github.com>
Kopie: OlliKn <git@derknueppel.de>, Author <author@noreply.github.com>
Empfangen: 29.08.2020 10:59:29
Betreff: Re: [mozilla-mobile/fenix] Featurerequest: Enable to Transfer bookmarks to collections directly from the bookmark menue (#14427)

**Comment by s-ankur** [comment] 2020-08-29 11:09
Duplicate of  #4581

**Comment by OlliKn** [comment] 2020-08-29 11:27
Thanks for the fast answer. But IT is not Duplikate. I Was suggesting an Option in bookmarks (for Migration puposes, to help ordinary Surfers not aware of concepts) like "add bookmark as tab to collections xyz". Starting from scratch collecting his existing Sets of urls by opening every each of his hundreds in a tab to reach the Option "add to collection" is to much. The User wants to migrate an resort but not to open every URL in his bookmarks to Do so.

But IT is just a Suggestion. If you want to close the issue then Do so or ask me to Do so.

Best regards Oliver

**Comment by s-ankur** [comment] 2020-08-29 11:29
Oh I see, that was the reverse issue. Sorry

**Comment by OlliKn** [comment] 2020-08-29 11:41
No problem. It is not really my issue but when I read the comments in google play it says in 90% "I want my bookmarks back on Main Page!" So User will try how to manage this and will have the idea of adding them to collections. And when there would be an easy way to Do so IT really would calm their troubled minds an helps them to get used to the New Concept without even being aware of that. But there is in bookmarks just a dead end annoying them just More in their confusion and helplessliness. Words enough from me. Make of IT what you want. 🙂 I Like the new Firefox! Go on! 👍

**Comment by mikexsouth** [comment] 2020-09-12 10:27
I've seen some of the planned updates and I'm baffled by why Firefox is focusing on those.. almost all the comments on Google Play are commenting on this one - Bookmarks on the homepage.  THIS is the major issue with Firefox right now, and this is what Firefox need to be focusing on before they continue to lose many users. I'm baffled as to why Firefox aren't and will myself consider other browsers soon too

**Comment by OlliKn** [comment] 2020-09-12 12:43
I agree. Reading what is categorized as "nice to have" and which issues are considered to have "priority" Leads me to the impression Mozilla is far far away from its userbase... Really irritating and alarming.
Still, I stay with Firefox because it is a really good one. But many users are not patient. New Updates with no visible changes can not be understand by them...

Von: mikexsouth <notifications@github.com>
An: mozilla-mobile/fenix <fenix@noreply.github.com>
Kopie: OlliKn <git@derknueppel.de>, Author <author@noreply.github.com>
Empfangen: 12.09.2020 12:31:33
Betreff: Re: [mozilla-mobile/fenix] Import bookmarks to collections (to have bookmarks on the homescreen) (#14427)

**Comment by jawz101** [comment] 2020-10-01 23:01
https://github.com/mozilla-mobile/fenix/issues/5853

**Comment by hubyhuby** [comment] 2020-11-29 14:50
Please bring back the bookmarks on home page. People have been crating their bookmarks for the past 20 years...we need them back!

Most people don t understand anyway the purpose of the collection...I don t....and this bug is a démonstration that most don t either...

**Comment by cadeyrn** [comment] 2020-11-29 15:28
> Please bring back the bookmarks on home page. People have been crating their bookmarks for the past 20 years...we need them back!

#12065 is about showing bookmarks on the home screen. This issue is about importing bookmarks into collections.

**Closed** 2021-06-05 20:34 UTC
Labels: Feature:Bookmarks, Feature:Collections, Feature:HomeScreen, wontfix

**Comment by hubyhuby** [comment] 2021-06-06 02:50
Please bring back bookmarks. Collections are just bookmarks in disguise. No need for collection that are bot sync to desktop
