### ISSUE TITLE
Crash in [@ java.lang.RuntimeException: at android.app.ActivityThread.deliverResults(ActivityThread.java)]

### ISSUE THREAD

**Issue by KennethHeal** [mozilla-mobile/fenix#27450] opened 2022-10-18 14:59 UTC
Crash report: https://crash-stats.mozilla.org/report/index/3e5961df-c432-4b2b-8621-af26f0221010

Java stack trace:
```
java.lang.RuntimeException
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4556)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4599)
	at android.app.ActivityThread.-wrap22(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1557)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21819)

**Comment by kbrosnan** [comment] 2022-10-18 22:56
The raw crash report has some additional information

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=711619305, result=-1, data=Intent {  launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 }(has extras) }} to activity {org.mozilla.firefox/org.mozilla.firefox.App}: java.lang.IllegalArgumentException: Navigation action/destination org.mozilla.firefox:id/action_savedLoginsAuthFragment_to_loginsListFragment cannot be found from the current destination Destination(org.mozilla.firefox:id/savedLoginsFragment) class=org.mozilla.fenix.settings.logins.fragment.SavedLoginsFragment
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4556)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4599)
...
```

Does this happen when you are in another app trying to sign-in or is this happening on a web sign-in form? Some other interaction that might be related to the crash?

**Comment by KennethHeal** [comment] 2022-10-18 23:14
This happened whilst setting up email using modem auth for iirc the Outlook app.

**Comment by iorgamgabriel** [comment] 2022-11-02 15:02
@KennethHeal Can you please give us more details on how we can reproduce this bug? A video will be great . Thank you very much!

**Comment by iorgamgabriel** [comment] 2022-11-03 09:13
I made a fix for this if you can still reproduce it with the latest build please tell . Thank you ! @KennethHeal

**Comment by KennethHeal** [comment] 2022-11-07 08:08
@iorgamgabriel unfortunately I cannot recall any more precise steps, I've not had the crash since.
Thanks for the fix. I keep Fenix updated with the latest play store release build so will keep an eye out for the fix and will update if crash reoccurs

**Comment by delia-pop** [comment] 2022-11-07 15:19
The QA team is also unable to reproduce the issue. I will close this ticket for now, but please re-open or submit another ticket, if needed. Thanks!

**Closed by delia-pop** 2022-11-07 15:19 UTC
Labels: b:crash, eng:qa:needed, Feature:Logins, needs:triage
