### ISSUE TITLE
FNX3-16895 ⁃ [Bug] Page title in custom tabs is too small

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3259] opened 2019-06-07 12:46 UTC
## Steps to reproduce
1. Open a custom tab.
or Go to Settings>Sign in, or Settings>Privacy notice, etc.
1. Observe the page title in the URL bar.
    1. Expected behavior
The font size is normal.
    1. Actual behavior
Font size is tiny.
    1. Device information

* Android device: Pixel, Galaxy Note 8, Nexus 5
* Fenix version: 6/7

**Comment by sv-ohorvath** [comment] 2019-06-07 12:49
![Screenshot_20190607-154526](https://user-images.githubusercontent.com/4037709/59105077-c99b8880-893b-11e9-99cf-bfe292702ba0.png)

vs: https://user-images.githubusercontent.com/51007/53313384-03f99080-391e-11e9-8999-93d20cba7eec.png

**Comment by softvision-miralobontiu** [comment] 2019-06-12 12:21
It is not fixed on all devices. On tablets, as far as I can tell, the page titles in custom tabs are still too small.
Tested on the latest build 1.0.1924 (#11630619), with:
- Samsung Galaxy Tab A 6 (Android 5.1.1), 
- Google Pixel 3 (Android 9),
- Nexus 5 (Android 6.0.1),
- Sony Xperia Z2 tablet (Android 6.0.1). 

Please see the attached screenshot, first screenshot is from Sony tablet, the second is from Google phone:
![Screenshot_1](https://user-images.githubusercontent.com/40694158/59350645-4a37fb80-8d25-11e9-97ca-bc3d6118efce.png)

**Comment by sblatz** [comment] 2019-06-12 15:06
@softvision-miralobontiu are you able to post a full resolution sreenshot of the tablet? It looks like all the text is small, so the title being small would be expected behavior.

**Comment by softvision-miralobontiu** [comment] 2019-06-12 15:08
![Sony tablet](https://user-images.githubusercontent.com/40694158/59362920-ffc27900-8d3c-11e9-8bbe-a412845d3b8d.png)

**Comment by sblatz** [comment] 2019-06-12 16:11
@softvision-miralobontiu are you only able to reproduce this on tablets?

**Comment by softvision-miralobontiu** [comment] 2019-06-13 08:31
I am not able to reproduce at all with the latest build 1.0.1924 (#11640609), on 
- Sony Xperia Z2 tablet (Android 6.0.1),
- Samsung Galaxy Tab S3 (Android 8),
- Huawei MediaPad M2 (Android 5.1.1),
- Nexus 5 (Android 6.0.1),
- OnePlus 5T (Android 9).
Therefore, I will close this as verified as fixed.

**Closed** 2020-08-12 17:39 UTC
Labels: Feature:CustomTabs, P1, eng:qa:verified, 🐞 bug
