### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Kiwially** [mozilla-mobile/fenix#20752] opened 2021-08-09 00:50 UTC
Firefox Nightly Mobile App

Browser has just recently started constantly flashing, text momentarily disappears and reappears, videos flash constantly. Using Huwei P30 Pro, phone and chrome browser are fine.

**Comment by anotherus3r** [comment] 2021-08-09 10:08
Duplicate of #20733

**Comment by jonalmeida** [comment] 2021-08-09 14:51
Correct, closing as duplicate.

**Closed** 2021-08-09 14:51 UTC
Labels: needs:triage
