### ISSUE TITLE
Support 4.4.4 Kit-Kat

### ISSUE THREAD

**Issue by KOLANICH** [mozilla-mobile/fenix#7053] opened 2019-12-10 08:35 UTC
### Why/User Benefit/User Problem

It is impossible to update some devices to Lollypop.

### What/Requirements

Support Android 4.4.4 Kit-Kat.

### Acceptance Criteria (how do I know when I’m done?)

Should work on Kit-Kat.

**Comment by cadeyrn** [comment] 2019-12-10 08:54
Duplicate of #2100.

**Comment by abodea** [comment] 2019-12-10 10:11
Thanks @cadeyrn closing it accordingly.

**Closed by abodea** 2019-12-10 10:11 UTC
Labels: 🌟 feature request
