### ISSUE TITLE
[webcontent] YouTube video are zoomed in when switched to full screen. Results in crop. No option to zoom out.

### ISSUE THREAD

**Issue by iamiceparticle** [mozilla-mobile/fenix#18812] opened 2021-04-06 08:57 UTC
## Site with issue and any steps to reproduce
Open any YouTube video. Take this as an example, you can see the logo truncated. https://m.youtube.com/watch?v=B_ThlNKjEWY
### Expected behavior
Video should not be zoomed in. Or provide option to zoom out.
### Actual behavior
Video zoomed in. No option to zoom out.
### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No
### Can you reproduce in Chrome (or other non-Mozilla browser)?

No
### Device information

* Android device: Samsung Galaxy A71
* Fenix version: 87.0.0-rc.1 (Build #2015799099)
![Screenshot_20210406-141521_Firefox](https://user-images.githubusercontent.com/76210878/113685750-31f85400-96e4-11eb-8521-bf812c036242.jpg)
![Screenshot_20210406-141537_Firefox](https://user-images.githubusercontent.com/76210878/113685757-345aae00-96e4-11eb-80f9-5983713a3d09.jpg)

**Comment by anotherus3r** [comment] 2021-04-06 10:01
Duplicate of #8252.

**Comment by abodea** [comment] 2021-04-06 13:53
Thank you for this report, closing as dupe of #8252.
For more details please check the mentioned bug.

**Closed by abodea** 2021-04-06 13:53 UTC
Labels: needs:triage
