### ISSUE TITLE
[Bug] Website thalia.at flickers when requesting desktop view

### ISSUE THREAD

**Issue by Wasseranomalie** [mozilla-mobile/fenix#5123] opened 2019-09-05 06:53 UTC
## Steps to reproduce
* Open https://www.thalia.at/shop/home/artikeldetails/ID1778730.html
* Request desktop page
* Zoom a bit into the page and scroll to the right side of the page
* Scroll up and down (not always necessary)

### Expected behavior
Website content does not flicker.

### Actual behavior
Website content flickers.
I've captured this on my device: https://youtu.be/GZ4LsVwvjRw

This problem does not only occur on Firefox Preview, but also on Firefox for Android Nightly, therefore this might not be a regression.

### Device information

* Android device: Nexus 5X, Android 8.1
* Fenix version: Nightly 190831 06:04 (Build #12430613)

**Comment by boek** [comment] 2020-01-14 17:09
@fluffyemily will try to find a fennec issue and open it against fenix

**Comment by fluffyemily** [comment] 2020-04-21 14:31
Still waiting for a bugzilla issue for this.

**Comment by ekager** [comment] 2020-12-17 00:45
@Wasseranomalie are you still seeing this? I can't reproduce. Closing as resolved.

**Closed by ekager** 2020-12-17 00:45 UTC
Labels: P3, b:web-content, b:webcompat, needs:gv, 🐞 bug
