### ISSUE TITLE
[Bug] WebAuthn broken

### ISSUE THREAD

**Issue by sqrt-1764** [mozilla-mobile/fenix#14242] opened 2020-08-26 20:20 UTC
I now wanted to implement WebAuthn / FIDO2 in my website and checked the function in serveral browsers that are reported as working.
Despite the fact that caniuse reports this as usable in Firefox for Android since version 68. Several other references in the web report also this as working. 

So i have to assume this is broken by the update.

## Steps to reproduce
Go to https://webauthn.io

### Expected behavior
Demo login working

### Actual behavior
Getting message that webauthn is not supported by browser

### Device information
* Android device:
Pixel 3a
Nexus 5x
Lenovo Ideapad Duet

* Fenix version: 79.0.5

**Comment by Dunexus** [comment] 2020-08-26 20:29
Duplicate of https://github.com/mozilla-mobile/fenix/issues/1340

**Comment by kbrosnan** [comment] 2020-08-26 20:53
Closing as duplicate

**Closed by kbrosnan** 2020-08-26 20:53 UTC
Labels: needs:triage, 🐞 bug
