### ISSUE TITLE
[Bug] Wrong font styling in url bar

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7190] opened 2019-12-16 01:35 UTC
## Steps to reproduce

1. go into any page with big / bold /italic font - for example https://www.pcworld.pl/testy/Dynabook-Port-g-A30-E-Test-laptopa-biznesowego-nowej-marki,417102.html

2. select some text and paste it into url bar

### Expected behavior

Text has got default url bar formatting

### Actual behavior

Text is formatted according to original formatting

### Device information

* Android device: Galaxy S7/Android 8
* Fenix version: nightly
![Screenshot_20191215-193200_Firefox Nightly](https://user-images.githubusercontent.com/24834168/70873172-c3522d00-1fac-11ea-9a69-77d2ced786a7.jpg)

**Comment by cadeyrn** [comment] 2019-12-16 07:42
Duplicate of #1833.

**Closed** 2019-12-19 00:14 UTC
Labels: 🐞 bug
