### ISSUE TITLE
Add-ons completely missing

### ISSUE THREAD

**Issue by SpandexWizard** [mozilla-mobile/fenix#20706] opened 2021-08-06 08:07 UTC
I'm new to bug reporting so forgive me if this isn't proper formatting

My add-ons folder is empty, and shows a "failed to query add-ons" error. I have tried to remove the custom addon collection I use, and it did not restore the original addon list either. They don't just not show up in the list, all of my add-ons are no longer installed or disabled, evidenced by several passive add-ons no longer functioning.

I am currently on nightly 92.0a1 (Build #2015826121), on Android 

I don't know what more to add, there's nothing that triggers it it just is.
![Screenshot_2021-08-05-18-59-01](https://user-images.githubusercontent.com/80999980/128477634-bfa9a50b-3b72-4546-9de8-cb260ec039b0.png)

**Comment by SeburoSUMO** [comment] 2021-08-06 09:39
I am also seeing this in the latest Nightly on my device, also user feedback in SUMO: https://support.mozilla.org/en-US/questions/1346180

**Comment by evilpie** [comment] 2021-08-06 13:30
https://bugzilla.mozilla.org/show_bug.cgi?id=1724298

**Comment by cadeyrn** [comment] 2021-08-06 13:38
Duplicate of #20686 and #20692.

**Closed** 2021-08-06 13:39 UTC
Labels: needs:triage
