### ISSUE TITLE
Tab displays the content of another tab

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#20737] opened 2021-08-07 12:55 UTC
### Steps to reproduce

Multiple tabs are open.

### Expected behaviour

In each tab the content of the called page is displayed.

### Actual behaviour

After a while, one or more tabs display the content of a foreign tab. At the same time, the tabs with foreign content freeze.

### Device name

Samsung Galaxy XCover 4s

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

91.1.0 (Build #2015826187) AC: 91.0.12, 1d401758fb GV: 91.0-20210804193234 AS: 79.0.0

### Additional information

So far, I have observed this phenomenon only in private mode.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17508)

**Comment by WebworkrNet** [comment] 2021-08-07 15:32
The error only occurs from time to time.

**Comment by WebworkrNet** [comment] 2021-08-07 15:40
In the meantime, the error has also occurred in standard mode.

**Comment by WebworkrNet** [comment] 2021-08-09 08:46
In rare cases, the tab does not freeze. After a while, the correct content is displayed.

**Comment by mariansima** [comment] 2021-09-28 14:36
![243661893_398704335124340_7686787956826355741_n](https://user-images.githubusercontent.com/89511597/135108241-51e99c35-f519-4a83-8b43-f1ed4a4306a9.jpg)

Sometimes this issue can be reproduced (rarely) by navigating between multiple open tabs using the swipe gesture on the toolbar.

**Comment by ohhai** [comment] 2021-11-17 14:19
I have same, from time to time. When switching from tab A to tab B, url bar on tab switches properly (starts to show url B) but content of the page stays with tab A. It could be navigated, links pressed, etc, but tab B content becomes just inaccessible.
Might be related: https://github.com/mozilla-mobile/fenix/issues/20207

**Comment by Cheap-Skate** [comment] 2021-11-25 17:04
I have this issue too. As above, it most often happens when swiping between tabs. Sometimes the destination tab locks up. sometimes it locks up AND shows the wrong tab's content.  I will try to find some STR

**Comment by ohhai** [comment] 2021-12-17 23:42
Still present: version 95.2.0 (Build #2015851755)
AC: 95.0.14, 4f3b0461e7
GV: 95.0.1-20211215221728
AS: 86.0.1

**Comment by gonhidi** [comment] 2022-01-20 10:00
When I have had this happen to me, input on fields of (some, all?) pages that are not frozen stops working: the keyboard does not always show up when selecting a field, and when it does, typing on it does nothing.

This is on an up to date Pixel 3a phone. It is some days/weeks since this issue last triggered.

**Comment by DavidJCobb** [comment] 2022-02-07 17:03
This happens to me rarely, and usually when I'm opening and closing several tabs during a browsing session.

**Comment by git-bruh** [comment] 2022-09-03 09:33
Any updates on this? It's super annoying to have to re open firefox every time this bug happens

**Comment by WebworkrNet** [comment] 2022-09-19 17:08
Error also occurs under the following system environment:

**Device name**
Samsung Galaxy XCover 4s

**Android version**
Android 11

**Firefox release type**
Fennec

**Firefox version**
104.1.0 (Build #1041020), 99759dd72+
AC: 104.0.8, 3dc0ff00e7
GV: 104.0-20220824221210
AS: 93.7.2

**Comment by WebworkrNet** [comment] 2022-09-19 17:09
Error also occurs under the following system environment:

**Device name**
Samsung Galaxy XCover 4s

**Android version**
Android 11

**Firefox release type**
Fennec

**Firefox version**
104.1.0 (Build #1041020), 99759dd72+
AC: 104.0.8, 3dc0ff00e7
GV: 104.0-20220824221210
AS: 93.7.2

**Comment by mduchev** [comment] 2022-10-10 08:19
This is happening very frequently if I decide to change the tabs by swiping. It can occur only with 2 tabs opened. Can't say for sure that it happens if I manually switch between the tabs from the tab list/grid view. But swiping between tabs breaks the tab content very often. Also, the broken tab freezes and cannot be refreshed. Only stopping & starting Firefox again fixes the issue.

Here's a demo of 2 totally different sites:
![screen-20221009-232709~2](https://user-images.githubusercontent.com/8217099/194824271-959689c9-1aba-4c0f-9b84-3232acd2b6f4.gif)

**Device name**
Pixel 4 XL

**Android version**
Android 13 with latest October patch

**Firefox version**
105.2.0 (Build #2015907747), 01fbfd637+
AC: 105.0.8, 658c2d239f
GV: 105.0.2-20221003135607
AS: 94.1.0

**Comment by boek** [comment] 2023-01-26 23:48
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812870

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-26 23:48 UTC
Labels: 🐞 bug, Feature:Tabs, needs:triage
