### ISSUE TITLE
Bookmarks & History managers should have a search function

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#15055] opened 2020-09-14 01:13 UTC
Apologies if this is a duplicate but I just noticed the Bookmarks manager doesn't have a search function. The History manager should probably have one too

**Comment by Poopooracoocoo** [comment] 2020-09-14 06:30
dupe of #10046 #12717

**Comment by eliserichards** [comment] 2020-09-15 21:34
Thanks for the suggestion @willfs84! I'm going to close this as a duplicate. Feel free to follow along in the other bugs that @Poopooracoocoo listed 😄

**Closed by eliserichards** 2020-09-15 21:34 UTC
Labels: needs:triage
