### ISSUE TITLE
[Bug] The TP doorhanger is displayed on the bottom while using the Toolbar on top

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#7140] opened 2019-12-13 13:46 UTC
## Prerequisites
Set Fenix as the default browser.

## Steps to reproduce
1. Launch Fenix.
2. Set the toolbar to be on top.
3. Access any website and tap on the TP button.
### Expected behavior
The TP doorhanger should be displayed on the top.
### Actual behavior
The TP doorhanger  is displayed on the bottom while the toolbar is on top.
### Device information

* Android device: **Samsung Galaxy S10+(Android 9).**
* Fenix version: **Nightly 12/13.**

### Notes
When the toolbar is on the bottom, the doorhanger is displayed correctly.
![ezgif-6-d6dc79fbdf6b (1)](https://user-images.githubusercontent.com/42831109/70804565-79582400-1dbf-11ea-9905-1c14813cd7b7.gif)

**Comment by ekager** [comment] 2019-12-13 19:09
Closing as dupe of #7124

**Closed by ekager** 2019-12-13 19:09 UTC
Labels: Feature:NavBar, Feature:TrackingProtection, S2, 🐞 bug
