### ISSUE TITLE
As a developer I want to receive crash reports

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#906] opened 2019-03-08 05:52 UTC
### Why/User Benefit/User Problem
As a developer, I want to receive crash reports when Fenix crashes. 

### Dependencies
-  mozilla-mobile/fenix#304 (Resolved / Merged)

### Acceptance Criteria (how do I know when I’m done?)
- When Fenix crashes in application code or native A-S code, a crash report is sent to Sentry
- When Fenix crashes in GeckoView, a crash report is sent to Socorro
- When the user has opted out from sending crash reports (via settings, specified in another user story) no crash reports should be sent. This is only so for Sentry and Soccoro reports. Android will still send reports to the Google Play Store, and that is controlled byt he user at an Android level, not in Fenix.
- Crash reports should contain enough data to resolve or investigate a crash (ideal situation, but due to the nature of reports, this is simply not always the case)

**Comment by sblatz** [comment] 2019-03-15 18:22
I noticed we do not have any UX for this. I'm happy to use a Focus-inspired crash page similar to the one found below, but we will need to make a couple changes:
1. New copy for the description since we're saving history and not a private browser
2. How "restoring" a session should look (likely a restore session button similar to close tab, with copy that reflects this)

@mheubusch for copy, @lime124 for UX. 

### Current Implementation
<img width="350" alt="Screen Shot 2019-03-15 at 11 19 03 AM" src="https://user-images.githubusercontent.com/4400286/54453273-3bd14800-4714-11e9-96fb-a4c0e50fff29.png">

**Comment by lime124** [comment] 2019-03-15 18:29
@topotropic since there are session related questions

**Comment by sblatz** [comment] 2019-03-18 15:31
What I'm using for now:
<img width="350" alt="Screen Shot 2019-03-18 at 8 30 48 AM" src="https://user-images.githubusercontent.com/4400286/54541968-264c6000-4958-11e9-813a-53e48be1ba17.png">

**Comment by cadeyrn** [comment] 2019-03-18 15:39
Just a quick note: Both buttons have the same style in your screen. In Firefox for the desktop you have a primary action and a secondary action in about:tabcrashed, both buttons are differently styled. I don't know if you want to do something similar in Fenix, maybe this is something to consider. ;-)

**Comment by sblatz** [comment] 2019-03-18 16:19
Updated the buttons as so for now:

<img width="236" alt="image" src="https://user-images.githubusercontent.com/4400286/54545455-f3f23100-495e-11e9-919f-45946b460b25.png">

**Comment by topotropic** [comment] 2019-03-18 21:44
@brampitoyo I think you are working on this atm, can you have a look?

**Comment by brampitoyo** [comment] 2019-03-19 04:12
@topotropic Thanks for pinging me on this. I will have a look at this issue as a part of designing the messaging system (which @shorlander has designed the framework of).

@sblatz Stay tuned for some design! I will first make sure that whatever we use here will look great with the rest of our in-product messaging pages (e.g. 404, SSL errors, malware warnings, etc.)

**Comment by sblatz** [comment] 2019-03-20 17:46
@bbinto, @vesta0: can I get clarification on what [Telemetry events](https://github.com/mozilla-mobile/fenix/issues/1040) we want for this?

**Comment by bbinto** [comment] 2019-03-20 19:21
@sblatz - added info here https://github.com/mozilla-mobile/fenix/issues/1040

**Comment by brampitoyo** [comment] 2019-03-21 04:13
The UX has been posted on #1102.

**Comment by sblatz** [comment] 2019-03-22 16:58
This is blocked on https://github.com/mozilla-mobile/fenix/pull/1067 so that I have a baseline for telemetry events.

**Comment by sblatz** [comment] 2019-03-26 17:12
This feature has been complete for a few days now. The only thing missing from the user story is the [telemetry](https://github.com/mozilla-mobile/fenix/issues/1040) which @boek is helping me out with!

In the future, we should likely break out Telemetry stories so that they don't block an entire feature being QA ready.

**Comment by sblatz** [comment] 2019-03-26 17:23
Per a conversation with Betty, I created a [telemetry user story](https://github.com/mozilla-mobile/fenix/issues/1191) so that this could move to QA.

**Comment by sv-ohorvath** [comment] 2019-03-28 13:00
This is verified by QA. There are new issues logged for the bugs found, I'll close this ticket.

**Closed by sv-ohorvath** 2019-03-28 13:00 UTC
Labels: Epic, Feature:CrashReporting, QA needed
