### ISSUE TITLE
[Bug] App crashes after deleting several bookmarks

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5920] opened 2019-10-10 08:54 UTC
## Steps to reproduce
1. Make sure you sign-in on an account that has several bookmarks, saved on different days.
2. Go to "Your Library" - Bookmarks and delete some of the bookmarks.
3. Tap on the three-dot menu that is displayed between bookmarks and should not be displayed at all.

### Expected behavior
That three-dot menu shouldn't be displayed at all.

### Actual behavior
Selecting the three-dot menu between bookmarks crashes the app.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9)
* Fenix version: 10/10 aarch64 Nightly build

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3711389/logcat.txt)

![20191010_trim](https://user-images.githubusercontent.com/40694158/66553483-dd5a3400-eb53-11e9-8ff6-9f1f1478d963.gif)

**Comment by sv-sdeiac** [comment] 2020-01-31 12:11
Hello, I can't reproduce the issue using Firefox Preview Nightly 1/30 @20301807 since the 3dot option is not anymore displayed (step 3 from the description).

Device:
- Samsung Galaxy Note 8 (Android 9).
Due to my findings, I'll close this ticket, thanks.

**Closed by sv-sdeiac** 2020-01-31 12:11 UTC
Labels: Feature:Bookmarks, P2, S2, b:crash, eng:qa:needed, 🐞 bug
