### ISSUE TITLE
[Bug] Unable to sign in to Firefox Accounts with email: goes to account settings screen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#17576] opened 2021-01-21 20:10 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

I'm also unable to sign in to FxA with the QR code https://github.com/mozilla-mobile/fenix/issues/17575 so this issue may be the same as that one but the reason I think they may be different is because I get to my account settings when I try to sign in with email (i.e. sign in is successful but doesn't go to the browser).

## Steps to reproduce
- On a fresh fenix profile, click 3-dot -> settings -> Turn On Sync -> "Use email instead"
- Sign in (I used a @mockmyid.com account)

### Expected behavior
Successful sign in

### Actual behavior
Sign in successful to account settings web page but I am not signed into the browser.

https://user-images.githubusercontent.com/759372/105406636-8ca00a80-5be1-11eb-96a3-c109e29caa86.mp4

### Device information

* Android device: Moto G5
* Fenix version: Nightly 210121

**Comment by iamkroot** [comment] 2021-01-22 13:30
I'm unable to sign-in via QR Code pairing either. (not the same as #17575, since I don't get any missing param error)

After accepting the pairing on both devices, the desktop web site shows the successful "Devices connected" screen, but the device name is blank (IP and location are present). On the mobile side, it's just stuck on "Approval now required from your other device". I'm guessing some request failed somewhere.

**Comment by SpiderPork** [comment] 2021-01-22 15:24
Same for me

**Comment by Gericop** [comment] 2021-01-22 23:22
Can confirm this happening in Nightly 210122 as well.

**Comment by michrogit** [comment] 2021-01-23 10:06
Android device: Moto X4 
Android version: 9
Two-step authentication (Authy 2-Factor Authentication app) 

12 hours ago: Unable to sign in to FxA with email @gmail.com (redirected to account settings screen) and  also unable to sign in with the QR code. 
Updated now (Nightly 210122 - Build #2015788915), I signed in with the QR code and everything was fine. Then I disconnected the device from Sync, signed in with email and it works too.

**Comment by Gericop** [comment] 2021-01-23 10:38
Build #2015788915 fixed it.

**Comment by jonalmeida** [comment] 2021-01-25 18:49
> Build #2015788915 fixed it.

Thanks for verifying! Closing.

**Comment by kaldown** [comment] 2021-03-28 17:55
it's still there
87.0.0-rc.1 Build #20157999099

**Comment by ebalazs-sv** [comment] 2021-04-06 09:55
I had tested this issue on Nightly 4/6, Beta 88.0.0-beta.4, RC 87.0.0-rc.1 with Motorola Moto G6 (Android 8) and could not reproduce it.

**Comment by kaldown** [comment] 2021-04-06 13:39
Re-installed my FF, now it works.
But I don't think it's fair, since there was no "purge" button.

**Closed** 2022-02-09 22:20 UTC
Labels: 🐞 bug, wontfix, qa-triaged
