### ISSUE TITLE
Fennec migration: The 3 device buttons are not visible when the migration onboarding screen is displayed on Pixel 2

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#9932] opened 2020-02-28 10:17 UTC
## Preconditions:
Have Fennec Beta installed.
## Steps to reproduce
1. Replace Fennec Beta with Fenix Beta;
2. Observe the 3 Android buttons from the bottom of the screen;
### Expected behavior
The 3 device buttons are displayed.
### Actual behavior
The 3 device buttons are not visible.
### Notes:
[Video](https://drive.google.com/file/d/1EY5N0z4FcVoqokIrMANsnZXdA-liHsBy/view)
This is not reproducible on Pixel 3 (Android Q), Pixel XL (Android 9), Pixel 3a XL (Android Q), LG G7 fit (Android 8.1), Huawei P9 Lite (Android 7).
### Device information

* Android device: Google Pixel 2 (Android 9)
* Fenix version: Beta migration build 2, 02/27

**Comment by ekager** [comment] 2020-04-18 05:45
Reopening for QA

**Comment by Diana-Rus** [comment] 2020-04-24 08:28
Hi, verified the issue with Google Pixel 3 XL (Android 9) on migration build 75.0.0-beta.6 and the issue is still reproducing.
GIF:
![20200424-111932](https://user-images.githubusercontent.com/49859863/80191611-9975da80-861e-11ea-91af-975b43013a3c.gif)

**Comment by jonalmeida** [comment] 2020-04-24 19:37
This can be verified with on a nightly migration.

**Comment by jonalmeida** [comment] 2020-04-24 19:38
This can be verified with on a nightly migration.

**Comment by Diana-Rus** [comment] 2020-04-27 09:16
Hi, verified as fixed with Google Pixel 3 XL (Android 9) and Pixel 2 (Android 9) on Nightly migration build 4/27 and I'll close this ticket, but we'll keep an eye for it on further builds. Thank you 😊

Gif- Google Pixel 3 XL
![20200427-120903](https://user-images.githubusercontent.com/49859863/80355486-d50fdf00-8880-11ea-94b3-8d64cba374eb.gif)

**Closed by Diana-Rus** 2020-04-27 09:16 UTC
Labels: Feature:Migration, eng:qa:needed, 🐞 bug
