### ISSUE TITLE
[Bug] Home page is scrollable

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#15723] opened 2020-10-06 13:51 UTC
![ScreenRecord-2020-10-06-07-49-04](https://user-images.githubusercontent.com/14617699/95210366-1921eb00-07f4-11eb-896a-81160bb65fb9.gif)

**Comment by s-ankur** [comment] 2020-10-06 16:00
Duplicate of https://github.com/mozilla-mobile/fenix/issues/8545

**Closed** 2020-10-06 17:51 UTC
Labels: needs:triage, 🐞 bug
