### ISSUE TITLE
[Bug] Copy URL to Clipboard

### ISSUE THREAD

**Issue by BrokenShoeLace** [mozilla-mobile/fenix#15706] opened 2020-10-05 22:17 UTC
Copy a url to clipboard loses the page

**Comment by cadeyrn** [comment] 2020-10-06 10:38
I don't undestand this bug report. Please provide more details. Unfortunately you removed all fields (steps to reproduce, expected behaviour, actual behaviour, device information) from the bug template. These questions are asked for a good reason.

**Comment by BrokenShoeLace** [comment] 2020-10-06 10:46
Click in the address field to copy the URL for the actual page to disappear so after you copy the link you have no page to return to. 

If you use the phone gesture to go back you can get the page back or lose it all.

As there are no buttons and just an address bar there is noyhing you can do except click the X to the right of the address bar and open a tab to paste in the page again.

**Comment by kbrosnan** [comment] 2020-10-07 00:53
Tapping in the page content area will take you back to the page. You can also long press on the address bar to get an option to copy without entering it. Closing as works for me.

**Closed by kbrosnan** 2020-10-07 00:53 UTC
Labels: needs:triage, 🐞 bug
