### ISSUE TITLE
[Feature Request] Pull to refresh

### ISSUE THREAD

**Issue by lucianmarin** [mozilla-mobile/fenix#7320] opened 2019-12-20 23:18 UTC
### Why/User Benefit/User Problem

Right now the user has to bring page/site options and push on reload button.

### What/Requirements

A pull down the page gesture will refresh the page, but won't do a cold reload.

### Acceptance Criteria (how do I know when I’m done?)

- pull down gesture
- animated reload icon
- page is refresh with new content

**Comment by cadeyrn** [comment] 2019-12-20 23:22
Duplicate of #3262. According to #3262 it's in the backlog for Q2 2020.

**Comment by NotWoods** [comment] 2019-12-21 06:11
Yup, this has been difficult to implement but we're working on it.

**Closed by NotWoods** 2019-12-21 06:11 UTC
Labels: 🌟 feature request
