### ISSUE TITLE
[Bug] regression - 79.0.5 - unable to open a tab in background

### ISSUE THREAD

**Issue by anthosz** [mozilla-mobile/fenix#14477] opened 2020-08-30 07:04 UTC
## Steps to reproduce
Open a tier application (Amazon/Google news/Google Home/Twitrer/..) 
Open a link from this application

### Expected behavior
The link is open in background

### Actual behavior
The link is open in foreground

### Device information
* Android device: v 10

**Comment by wlisikpl** [comment] 2020-08-30 08:31
Settings > ADB > Enable, and in `adb`
`adb unload org.mozilla.fenix`
and than restart fenix

**Comment by anthosz** [comment] 2020-08-30 08:59
> Settings > ADB > Enable, and in `adb`
> `adb unload org.mozilla.fenix`
> and than restart fenix

It's a joke? 😱 Using adb to fix a FF bug? 😱

**Comment by wlisikpl** [comment] 2020-08-30 09:01
> > Settings > ADB > Enable, and in `adb`
> > `adb unload org.mozilla.fenix`
> > and than restart fenix
> 
> It's a joke? 😱 Using adb to fix a FF bug? 😱

By no means its a joke @anthosz. And its not something that will fix this bug permanently. Its just **temporal** solution until proper bugfix is implemented

**Comment by cadeyrn** [comment] 2020-08-30 09:04
Ignore this user. It's a troll that hates Mozilla for whatever reasons. Just look at his "creative work" like https://github.com/mozilla-mobile/fenix/pull/14478/files or "https://github.com/wlisikpl/pontoon/commit/9e17dbff51084cfd31e91d67588ccd315e206882"…

**Comment by anthosz** [comment] 2020-08-30 11:45
I don't approve of his behavior but the reason can be the new version I
guess.

A big disappointment in every way.

--
Envoyé depuis mon smartphone

Le dim. 30 août 2020 à 11:04, Sören Hentzschel <notifications@github.com> a
écrit :

**Comment by wlisikpl** [comment] 2020-08-30 12:16
@anthosz this is because Im heavily fed up with mozilla's behavior

**Comment by ekager** [comment] 2020-08-30 14:54
Closing for https://github.com/mozilla-mobile/fenix/issues/1523

**Closed by ekager** 2020-08-30 14:54 UTC
Labels: needs:triage, 🐞 bug

**Comment by kbrosnan** [comment] 2020-08-30 15:30
More likely a dupe of #470 as send tab was not mentioned.
