### ISSUE TITLE
FNX2-18726 ⁃ Import and export settings should be useful

### ISSUE THREAD

**Issue by freebrowser1** [mozilla-mobile/fenix#13451] opened 2020-08-10 12:03 UTC
### What is the user problem or growth opportunity you want to see solved?
There is no possibility to import and export settings to local storage (e.g. /storage/emulated/0) on Android. Most Android apps do have such a feature.

### How do you know that this problem exists today? Why is this important?
Because migrating to another device or even reverting to a backup when something goes wrong. Android has no possibility to backup app data to local storage without root.

**Comment by hwinnemoe** [comment] 2020-08-10 12:44
Duplicate of #2080

**Comment by liuche** [comment] 2020-08-10 22:08
Dupe, thank you, please follow in #2080

**Closed by liuche** 2020-08-10 22:08 UTC
Labels: needs:triage
