### ISSUE TITLE
[Bug] Custom Tabs and PWA destroy open private tabs in browser 

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#17163] opened 2020-12-21 13:49 UTC
Private tabs are always being closed after using Custom Tabs and/or PWA features

## Steps to reproduce
Have private tabs open in the main browser
Using a Custom Tabs-enabled app, load a link in Nightly Custom Tabs, then go back using button or gesture on the device; alternatively, load a PWA from your launcher, and navigate back

Open Firefox main browser and check for open private tabs. They are now closed due to this bug, which is reproducible for me on a Samsung device
### Expected behavior
No private tabs are closed
### Actual behavior
Upon returning to the main app, the screen flashes and the browser switches to the regular non-private tab. Private tabs have been closed without warning
### Device information

* Android device: Samsung Android 10 OneUI 2.5
* Fenix version: nightly 12-20

**Comment by hwinnemoe** [comment] 2020-12-21 16:13
Duplicate of/Related to #16165

**Comment by ekager** [comment] 2020-12-21 19:38
Closing for  #16165

**Closed by ekager** 2020-12-21 19:38 UTC
Labels: Feature:PrivateBrowsing, needs:triage, 🐞 bug
