### ISSUE TITLE
[Bug]popup history white with dark theme 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#16422] opened 2020-11-06 13:21 UTC
I cannot really believe how such visual incongruity is brought to fenix maybe it 's specific to nighty.
the popup panel that appears when long pressing back arrow in menu is blinding white even with dark theme enabled is not even possible to read tab name?!?!?!?!?!

**Comment by B0pol** [comment] 2020-11-06 21:30
Also in private browsing

Screenshots:
Firefox Nightly 201106 05:02
<img src="https://pic.infini.fr/wd0yGDOQ/tF5I9OUy.png">

**Comment by LittleAngelwings** [comment] 2020-11-06 22:15
I can confirm this issue for the dark mode.

**Comment by LaurentiuApahideanSV** [comment] 2020-11-12 09:50
I can confirm the issue is reproducible Firefox Preview Nighlty 201111 (Build #2015775051)

### Devices used:
- OnePlus 6T (Android 9)
- Samsung Galaxy S9 (Android 8.0.0)

**Comment by person808** [comment] 2020-11-29 07:19
Did a quick test. [This](https://github.com/mozilla-mobile/fenix/commit/c0e01373e1fb54937d4a38a3411e6e02c1075fac#diff-75b31066e97e27961c3c9e9668c539a133d73c10398dc76552df3f0119810ac0R36) is the problematic commit. The material components update messes up the style thats set in `TabHistoryDialogFragment`. Don't have time to properly test a fix but hopefully this helps whoever looks at this.

**Comment by axeltrinidade** [comment] 2020-12-05 05:23
Issue here too. Oneplus 7. Version 84.0.0-beta.2

**Comment by sflorean** [comment] 2020-12-16 07:14
Verified as fixed on Nightly 12/16.

**Closed by sflorean** 2020-12-16 07:14 UTC
Labels: Feature:Themes, S2, eng:qa:needed, 🐞 bug
