### ISSUE TITLE
[Bug] Toolbar on bottom may hide page elements while unable o hide it

### ISSUE THREAD

**Issue by akostadinov** [mozilla-mobile/fenix#15060] opened 2020-09-14 08:11 UTC
## Steps to reproduce
0. set toolbar to bottom (default I believe)
1. enable desktop mode
2. open facebook and create album
3. click yo upload images
4. select some images to be uploaded

### Expected behavior
The blue button to post at the bottom is visible and user can click.

### Actual behavior
The blue button at the bottom is hidden by the toolbar. And toolbar cannot be hidden.

This is a problem because mobile version of the site does not allow creating albums.

### Device information

* Android device: Galaxy S9, Android 10
* Fenix version: 80.1.2

**Comment by s-ankur** [comment] 2020-09-14 16:13
Duplicate https://github.com/mozilla-mobile/fenix/issues/13797

**Comment by s-ankur** [comment] 2020-09-14 16:19
Also toolbar hiding option has been introduced to nightly and the main browser will probably get it soon

**Comment by eliserichards** [comment] 2020-09-15 21:31
Closing as a duplicate of #13797

**Closed by eliserichards** 2020-09-15 21:31 UTC
Labels: needs:triage, 🐞 bug
