### ISSUE TITLE
Toolbar looks a bit cluttered when on a page with reader view supported

### ISSUE THREAD

**Issue by awinco** [mozilla-mobile/fenix#19987] opened 2021-06-13 07:04 UTC
![IMG_20210613_120339_227](https://user-images.githubusercontent.com/85820118/121798238-cc27cb80-cc42-11eb-95e9-085ce2206db5.JPG)
![IMG_20210613_120221_214](https://user-images.githubusercontent.com/85820118/121798268-ebbef400-cc42-11eb-8e6e-afda7fca10f3.JPG)

On the latest Nightly build (6/12) with the new home button, the toolbar looks a bit cluttered when visiting a page with reader view supported. It appears good otherwise.

**Comment by cadeyrn** [comment] 2021-06-13 09:37
How do you define "cluttered" in context of the new home button? Is it just that it's one button more now? Then you should follow #19886 where, AFAIU, the shield and padlock icon will be combined so that there will be the same amount of icons as before.

**Comment by azerto11** [comment] 2021-06-13 17:11
Hi, @awinco was my account only...sorry for the confusion. Thanks for bringing #19886 to my notice. Will keep updated.

**Comment by gabrielluong** [comment] 2021-06-13 23:51
Hi, we're looking to unify the lock and shield badge in https://github.com/mozilla-mobile/fenix/issues/19886 to address this before shipping the Home button beyond Nightly. I am closing this as a duplicate of https://github.com/mozilla-mobile/fenix/issues/19886.

**Closed by gabrielluong** 2021-06-13 23:51 UTC
Labels: needs:triage, 🐞 bug
