### ISSUE TITLE
FNX-4304 ⁃ Text Selection Toolbar re-order

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10466] opened 2020-05-07 05:57 UTC
## User Story
* As a Fenix user, I want to see the "Search in Firefox" option before the other browser search options in the text selection toolbar.

### Acceptance Criteria
* When I long press on web content, I see Copy, Select all, Share, and Firefox Search as the primary options, taking priority over other browser search options. 

**Preferred order:
Copy
Search
Select all
Share**

Example: If I have Focus and Opera installed "Search in Firefox" appears after "Search Privately" in the text selection toolbar.

![Screenshot](https://user-images.githubusercontent.com/42752644/81259323-b7234680-9005-11ea-88ba-784cfb9b7dd8.png)UNITO-UNDERSCORE!20200313-011035!

**Comment by brampitoyo** [comment] 2020-05-11 03:04
@vesta0 Agreed.

There are a couple of parts to resolving this issue:

1. The ordering of the context menu item should prioritise Search ahead of “Select all”:
    - Copy
    - Search
    - Select all
    - Share
    - ⋮ (More)
2. The ordering items under the “more” context menu should prioritise “Private search” ahead of “Find in page”:
    - Private search
    - Find in page
    - (Optional, but maybe not) Show search options from other browsers

I recommend against showing search options from other browsers that might take users out of Fenix. See Chrome for an example of option blocking – they don’t let you search with any app other than Chrome.

**Comment by vesta0** [comment] 2020-05-11 20:07
@brampitoyo we don't have "Find in page" in the context menu right now. 

I like your first suggestion. I would prefer to not exclude other browser searches from the context menu though, but move them out to the "more" context menu.

**Comment by Mugurell** [comment] 2020-05-12 15:37
Looked over this a little to offer an engineering perspective.
We currently offer the following possible actions in the floating menu:
- [cut, copy, paste, select all, `process_text`] [from GeckoView](https://dxr.mozilla.org/mozilla-central/rev/61a83cc0b74b43117a9fa6d92c3d693ea03bbffc/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/BasicSelectionActionDelegate.java#52) which represent the default possible actions.
- [search, search privately, share] from [A-C](https://github.com/mozilla-mobile/android-components/blob/6ae66368491ee698235200dbeb792ea32c47b31f/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/DefaultSelectionActionDelegate.kt#L19) which represent custom actions a GV client can provide.

Which of the above actions we show is set in code, at runtime, basically, if an action makes sense or not.

"Search privately" corresponds to the `process_text` id. But there could be any other application which can handle "android.intent.action.PROCESS_TEXT" with it's own action text, like seen in #9467.

We could theoretically reorder the default actions (because we know their hardcoded ids) and also provide totally different custom actions (in any order).

FWIK we cannot really set which actions would appear in the "more" section.
All actions are placed in the order discussed above until they overflow the set menu width / screen width after which the others are put in the overflow ("more") section.

**Comment by AmyYLee** [comment] 2020-06-03 20:19
@brampitoyo for follow-up

**Comment by liuche** [comment] 2020-06-04 16:52
To summarize, we want to move "Search" right after "copy" in the context menu, and it's okay from @vesta0 if we can't decide the cutoff.

If this is a quick fix let's do it, otherwise push it out.

**Comment by brampitoyo** [comment] 2020-06-07 21:58
@liuche Confirming that this is indeed the behaviour we wanted. Let’s move forward with what’s set out in comment 0.

**Comment by sblatz** [comment] 2020-06-11 19:50
I'm waiting to hear back from AC about the feasability of doing this.

**Comment by liuche** [comment] 2020-06-22 19:58
Will ping sebastian about this again, to figure out how risky/big this is.

**Comment by sblatz** [comment] 2020-06-25 20:31
Sebastian's suggestion here: 

> Yeah, so, that looks like we could do with not too much code. Right now we just merge the actions here: https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/selection/GeckoSelectionActionDelegate.kt#L40
Maybe we could allow providing a function for sorting those actions? Maybe a function () -> R that we can pass to sortBy? It's a bit awkward that you only have String IDs here, but you could still map them to your preferred weights.

**Comment by sblatz** [comment] 2020-06-29 22:43
Put up an AC & Fenix PR for this so that Sebastian can verify 😄

**Comment by sblatz** [comment] 2020-06-29 22:49
If this solution is good with Sebastian, this is basically done!

## Demo

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/86063550-fa0b0480-ba1f-11ea-88c0-a8def95b5cde.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/86063561-0000e580-ba20-11ea-9eb9-9aad0688431c.png">

**Comment by jandryuk** [comment] 2020-06-30 18:01
I guess it's distinct from the ordering, but can "Firefox Preview Search" be renamed to just "Search" in the menu?

**Comment by vesta0** [comment] 2020-06-30 18:58
I think that's a great idea. @betsymi can we rename "Firefox Search" to "Search"? See the original decision [here](https://github.com/mozilla-mobile/fenix/issues/5695#issuecomment-540133875).

**Comment by sblatz** [comment] 2020-06-30 21:42
I think right now it's just pulling from "App Name" (Beta, Nightly, or just "Firefox"). We can definitely hardcode that if @betsymi prefers!

**Comment by betsymi** [comment] 2020-06-30 22:53
Agree that we should lead with action verb throughout the entire menu. It's the same pattern as Copy, Select, Share, etc., so let's keep that consistency throughout. We can keep the app name. 

Search in Firefox
Search in Nightly
Search in Firefox Preview

**Comment by betsymi** [comment] 2020-06-30 22:55
> If this solution is good with Sebastian, this is basically done!
> ## Demo
> 
> <img alt="image" width="350" src="https://user-images.githubusercontent.com/4400286/86063550-fa0b0480-ba1f-11ea-88c0-a8def95b5cde.png">
> 
> <img alt="image" width="350" src="https://user-images.githubusercontent.com/4400286/86063561-0000e580-ba20-11ea-9eb9-9aad0688431c.png">

Why does this have Search privately and Search Privately?

**Comment by vesta0** [comment] 2020-06-30 23:16
@betsymi just curious, do you think it needs to pull from the App Name or can it just say "Search" ?

Search Privately comes from having Focus installed, and Search privately comes from having Opera installed. Not related to Fenix.

**Comment by jandryuk** [comment] 2020-06-30 23:23
I would prefer just "Search" to cut down on the width and let "Select All" be on the top level link Fennec.

You don't need the current app's name in it's own context menu.

Thanks for your work on this!

**Comment by betsymi** [comment] 2020-06-30 23:30
> @betsymi just curious, do you think it needs to pull from the App Name or can it just say "Search" ?
> 
> Search Privately comes from having Focus installed, and Search privately comes from having Opera installed. Not related to Fenix.

Yes, it can simple say `Search`, no app name. If I understand the discussion on this thread correctly, we will not be point to Opera (or other apps) at all, so the final implementation won't have that privately/Privately issue, correct?

**Comment by sblatz** [comment] 2020-07-01 23:21
I will update my original PR to rename these to "Search"! 😄

**Comment by sblatz** [comment] 2020-07-13 16:56
I'm assuming if a special action like "Call" or "Email" is available, that should be first in the list: 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/87331555-03e83980-c4ef-11ea-80ff-b5c65772beac.png">


Let me know if that seems wrong @vesta0, @betsymi

**Comment by Diana-Rus** [comment] 2020-07-14 09:16
Hi, verified with Google Pixel 3XL (Android 9) and Samsung Galaxy S9 (Android 8) on latest Nightly 7/14
<details closed>
<summary>Samsung Galaxy S9 (Android 8)-Primary options - ❌</summary>

![Screenshot_20200714-102524_Firefox Nightly](https://user-images.githubusercontent.com/49859863/87400421-74f82180-c5c1-11ea-87a5-0034340b6664.jpg)
</details>
<details closed>
<summary>Samsung Galaxy S9 (Android 8)-"More" context menu - ✔️</summary>

![Screenshot_20200714-102542_Firefox Nightly](https://user-images.githubusercontent.com/49859863/87400440-7cb7c600-c5c1-11ea-8b72-2410a4bf20d0.jpg)
</details>
<details closed>
<summary>Google Pixel 3XL (Android 9)-Primary options - ✔️</summary>

![Screenshot_20200714-102853](https://user-images.githubusercontent.com/49859863/87400890-17180980-c5c2-11ea-9afc-b605b1c06e00.png)
</details>
<details closed>
<summary>Google Pixel 3XL (Android 9)-"More" context menu - ✔️</summary>

![Screenshot_20200714-103021](https://user-images.githubusercontent.com/49859863/87400911-1c755400-c5c2-11ea-9af3-ded7edc35323.png)
</details>

**Note:**
 
 - On Samsung Galaxy S9 (Android 8), not all the primary options are visible in the context menu as it is for Google Pixel 3 XL (Android 9) - check the drop down for Samsung Galaxy S9 (Android 8)-Primary options.
 - On both devices I had Focus and Opera mini installed. It seems that now "Opera Mini" is not recognized, not a problem based on [comment](https://github.com/mozilla-mobile/fenix/issues/10466#issuecomment-652096035) and [comment](https://github.com/mozilla-mobile/fenix/issues/10466#issuecomment-652100817) but to confirm it.
 - Did some regression around the options to see that they are not affected
 - As first look for [email or phone number](https://github.com/mozilla-mobile/fenix/issues/10466#issuecomment-657674467), they appear in the primary options in Context menu (more exactly as first option), will have the exact results of the testing for them in bug #10260  
<details closed>
<summary>Google Pixel 3XL (Android 9)-Email✔️</summary>

![Screenshot_20200714-120807](https://user-images.githubusercontent.com/49859863/87407314-aa553d00-c5ca-11ea-939d-5717242da857.png)
</details>
<details closed>
<summary>Google Pixel 3XL (Android 9)-Call✔️</summary>

![Screenshot_20200714-120740](https://user-images.githubusercontent.com/49859863/87407323-ade8c400-c5ca-11ea-977d-0eeabf584e67.png)
</details>

**Comment by Mugurell** [comment] 2020-07-14 09:43
> * On Samsung Galaxy S9 (Android 8), not all the primary options are visible

Are they not visible because they don't fit the screen?
Do they appear in landscape?
A screenshot would help.

**Comment by Diana-Rus** [comment] 2020-07-15 15:47
Hey,checked the options for Samsung Galaxy S9 (Android 8) and they are ok, it was a different width setup applied per device when testing. I'll leave a screenshot below, the agreed order is correct.

<details closed><summary>Samsung Galaxy S9 (Android 8) - Primary Options ✔️</summary>

![Screenshot_20200715-182929_Firefox Nightly](https://user-images.githubusercontent.com/49859863/87564846-904e5400-c6c9-11ea-93b3-ea5a276d2a61.jpg)
</details>

However after a look after the Context Menu, in private browsing, the "Private search" option is located at the bottom of the "More" menu. Shouldn't the option be set in the primary options list as we have the "Search"option or as a first option in the "More" menu?

Check GIF
 
![20200715-184039](https://user-images.githubusercontent.com/49859863/87566318-84fc2800-c6cb-11ea-95ca-5facc1f69e69.gif)

**Comment by sblatz** [comment] 2020-07-20 20:26
@Diana-Rus I've now added "Search Privately" to the top of the list in private mode. Thanks for catching that. 

Could you reconfirm that part? 😄

**Comment by Diana-Rus** [comment] 2020-07-22 09:30
Hi, checked the issue with Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL (Android 9) on latest Nightly 200721, the "Private Search" option has been moved in the primary options list

<details><summary>Google Pixel 3 XL (Android 9) - Primary options list - Private Search</summary>

![Screenshot_20200722-121647](https://user-images.githubusercontent.com/49859863/88159213-aa31ee80-cc15-11ea-8613-7ceb9d90c428.png)
</details>
@sblatz - "Search Privately" for the Focus option should be before others 3rd party apps installed that can be accessed through this custom menu -> More?

<details><summary>Search Privately - Focus option</summary>

![Screenshot_20200722-121013](https://user-images.githubusercontent.com/49859863/88159430-f5e49800-cc15-11ea-90e2-d9e78c6e4dda.png)
</details>

**Closed** 2020-08-11 00:49 UTC
Labels: E3, Feature:ContextMenu, eng:qa:verified, eng:ready, feature request 🌟
