### ISSUE TITLE
[Bug] (regression) Three crash notifications after crash

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#16517] opened 2020-11-12 08:39 UTC
### Steps to reproduce

1. Let Firefox crash

### Expected behavior

There is only one crash notification.

### Actual behavior

There are three crash notifications. Two notifications disappear by themselves after a short time, one stays.

![Screenshot_20201112-093448](https://user-images.githubusercontent.com/1100614/98915916-d75b2300-24ca-11eb-8353-985ab0d51e7a.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 10.0.12 (Android 10)
* Fenix version: master branch revision 710d68977d6ea91e85d3f3e77b4c1d309e1ff041

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-8747)

**Comment by AndiAJ** [comment] 2020-11-17 07:33
Hi, **reproducible** on the latest **`Nightly Build 201117`** using a Google Pixel 3a (Android 11)

❌ Not reproducible on the following devices:
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by cadeyrn** [comment] 2021-05-25 05:28
This is still an issue.

**Comment by cadeyrn** [comment] 2021-11-21 11:30
> It will be closed if no further activity occurs.

This is still an issue.

**Comment by rocketsroger** [comment] 2022-07-15 15:06
@cadeyrn did https://github.com/mozilla-mobile/android-components/issues/10112 fixes this issue by being more clear in the notification?

**Comment by cadeyrn** [comment] 2022-07-16 12:57
It's difficult to say because I used about:crashparent to reproduce the issue but I am no longer able to reproduce - even in the stable release of Firefox 102 without the mentioned AC fix. I don't know if there was another fix in the meantime or if it's related to my new smartphone or Android 12.

**Comment by rocketsroger** [comment] 2022-07-18 13:55
> @rocketsroger It's difficult to say because I used about:crashparent to reproduce the issue but I am no longer able to reproduce - even in the stable release of Firefox 102 without the mentioned AC fix. I don't know if there was another fix in the meantime or if it's related to my new smartphone or Android 12.

Thanks, I can't reproduce either.  I think it could have been an Android 12 issue that has been fixed.  I'll close this issue for now.  Please reopen this (or create an new issue) if you see this again.  Thanks

**Closed by rocketsroger** 2022-07-18 13:55 UTC
Labels: 🐞 bug, Feature:CrashReporting, S2
