### ISSUE TITLE
[Bug] Error initializing media manager java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState - crash when "open in firefox" selected when viewing privacy notice from onboarding

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7503] opened 2020-01-06 18:15 UTC
related to #6514 
## Steps to reproduce
Click on read our privacy policy on the onboarding page
custom tab opens
press open in firefox in the three dot menu
### Expected behavior
opens link 
### Actual behavior
crash
![2020_01_06_23_2-1578333750668](https://user-images.githubusercontent.com/33252312/71838252-4c421d00-30b0-11ea-9c79-2b0c12079836.gif)

### Device information

* Android device: asus zenfone m1
* Fenix version: 
Nightly 200106 06:00 (Build #20060606)
27.0.0, 25da25a0d
GV: 73.0a1-20200105094728

**Comment by s-ankur** [comment] 2020-01-06 18:16
firefox doesnt crash if the page is fully loaded

**Comment by sv-sdeiac** [comment] 2020-01-07 14:47
I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 1/7 build #20070606.

#### Device
- LG G7 fit (Android 8.1).

There is a [crash log](https://github.com/mozilla-mobile/fenix/files/4031088/crashprivacy.txt) about this scenario.

**Comment by kbrosnan** [comment] 2020-01-07 21:11
Thank you for the log.

```
2020-01-07 16:38:35.773 22887-22887/? E/GeckoBrowserApp: Error initializing media manager
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2080)
        at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2106)
        at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:683)
        at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:637)
        at org.mozilla.gecko.BrowserApp.handleMessage(BrowserApp.java:1829)
        at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:368)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:175)
        at android.app.ActivityThread.main(ActivityThread.java:6724)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
```

**Comment by ekager** [comment] 2020-01-30 15:20
I can't reproduce on my Pixel. Could we get this tested again?

**Comment by sv-sdeiac** [comment] 2020-01-31 11:17
Hello, I can confirm that I can't reproduce anymore the crash using the latest version of Nightly 1/31 #20310607.

Devices:
- Nokia 6 (Android 7.1.1);
- LG G7 fit (Android 8.1);
- Google Pixel (Android Q).

Due to that, I'll close this issue, thanks.

**Closed by sv-sdeiac** 2020-01-31 11:17 UTC
Labels: b:crash, eng:qa:needed, 🐞 bug
