### ISSUE TITLE
Firefox prevents device from turning the screen off

### ISSUE THREAD

**Issue by kolAflash** [mozilla-mobile/fenix#28489] opened 2023-01-11 01:33 UTC
### Steps to reproduce

Wait for the screen to turn off.

(you may set the timeout down to 15 seconds via the Android system settings)

### Expected behaviour

unclear

### Actual behaviour

unclear

### Device name

Google Pixel 4a

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

108.2.0

### Additional information

Pretty much the same issue as #25041  
Altough I currently don't know which tab or website is causing this.

This is happening in a Firefox instance with a lot of open tabs. Currently I'm trying to find out which tab and which website is causing this. I'll post the information as soon as I figured it out.

The affected Firefox browser has 11 open tabs and 21 archived tabs. I wonder if this might has something to do with the archived tabs.

QUESTION: Is there a fast way to make a tab become archived, so behaviour related to archived tabs can be reproduced?

@monolied  
Can you tell how to repduce after your comment in the old issue?  
https://github.com/mozilla-mobile/fenix/issues/25041#issuecomment-1364713996

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22261)

**Comment by makotokato** [comment] 2023-01-12 08:10
@kolAflash

Are you play video or audio on Firefox before this issue occurs?

**Comment by AdinaPetridean** [comment] 2023-01-16 08:54
Hi @kolAflash  Thanks for your report!
Tested on the latest Nightly 110.0a1 (2023-01-16), with
OnePlus 9 Pro (Android 12) having 12 tabs open and many bookmarks saved and the screen turns off after 30 seconds (set in Android settings).
I also tried to reproduce this issue on the older Firefox 108.1.0 but with no luck.

**Comment by cpeterso** [comment] 2023-01-27 06:24
> Tested on the latest Nightly 110.0a1 (2023-01-16), with
> OnePlus 9 Pro (Android 12) having 12 tabs open and many bookmarks saved and the screen turns off after 30 seconds (set in Android settings).
> I also tried to reproduce this issue on the older Firefox 108.1.0 but with no luck.

Closing this issue since we don't have steps to reproduce.

**Closed by cpeterso** 2023-01-27 06:24 UTC
Labels: 🐞 bug, needs:triage, qa-triaged
