### ISSUE TITLE
[Bug] "Search" function can only be used once on the same highlighted text

### ISSUE THREAD

**Issue by scrp445** [mozilla-mobile/fenix#19982] opened 2021-06-12 20:15 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Navigate on any page
- Highlight some text (or phrase)
- In the floating menu, click on “Search” (a new tab will open)
- Close the tab (e.g with back button)
- Without deselecting the text, click on the Search option again.

### Expected behavior
New tab should be open again
### Actual behavior
Nothing happens
### Device information
Huawei P9 (EVA-L09), Android 7.0
Firefox:
89.1.1 (Build #2015812947)
AC: 75.0.22, 5204f4025
GV: 89.0-20210527174632
AS: 74.0.1

**Comment by marcel263** [comment] 2021-06-12 20:37
Please see #19363

**Comment by LaurentiuApahideanSV** [comment] 2021-06-14 14:16
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/19363. I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-06-14 14:16 UTC
Labels: needs:triage, 🐞 bug
