### ISSUE TITLE
FNX3-16441 ⁃ [Bug] Top portion of homescreen is not scrollable in landscape

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#2599] opened 2019-05-17 08:55 UTC
In association with this comments from bughunter Google group: https://groups.google.com/forum/m/#!topic/fenix-nightly/sqQGlMzSCOA

## Steps to reproduce
Open fenix in portrait mode
Open some tabs
Go to homescreen, be sure you're on top
Turn device into landscape mode

### Expected behavior
Homescreen will be scrollable to tablist etc.. 

### Actual behavior
In landscape you can't scroll from top of the homescreen to the open tabs

### Device information
* Android device: think, all devices with smaller displays
* Fenix version: latest from play store bughunter program, and 1.0.1920 (370605) from taskcluster

**Comment by kbrosnan** [comment] 2019-05-31 18:39
Dupe of #3045

**Closed** 2020-08-20 21:12 UTC
Labels: Release Blocker, b:landscape, 🐞 bug
