### ISSUE TITLE
[Bug] [Android] Tabs not closing on swipe close. 

### ISSUE THREAD

**Issue by Oleophobic** [mozilla-mobile/fenix#18695] opened 2021-03-30 09:04 UTC
I have found myself closing tabs manually and going to different menus just to do this is a massive issue since the update and more than a year has elapsed now. Quit option is NOT useful either when this can be automated even if android ends firefox in the in the background restoring tabs can solve this. 

This has not been resolved and no option exists.

**Comment by Mugurell** [comment] 2021-03-30 10:30
@Oleophobic I understand you are asking for an option of having the opened tabs automatically be closed.

Currently Firefox offers to ways to accomplish that:
- enable and use "Quit" to delete browsing data when exiting the app
- enable an automatic system for cleaning old tabs by going to tabs tray settings or in settings -> Tabs:

<img src="https://user-images.githubusercontent.com/11428869/112974636-5c359900-915b-11eb-96a3-39fdd6bbfbe2.png" width="33%" />

&nbsp;
Do you have a suggestion for another option or maybe tweaking the existent ones?

**Comment by Oleophobic** [comment] 2021-03-30 10:44
> @Oleophobic I understand you are asking for an option of having the opened tabs automatically be closed.
> 
> Currently Firefox offers to ways to accomplish that:
> 
> * enable and use "Quit" to delete browsing data when exiting the app
> * enable an automatic system for cleaning old tabs by going to tabs tray settings or in settings -> Tabs:
> 
> <img alt="" width="33%" src="https://user-images.githubusercontent.com/11428869/112974636-5c359900-915b-11eb-96a3-39fdd6bbfbe2.png">
> 
>  
> Do you have a suggestion for another option or maybe tweaking the existent ones?

This is not a solution and I've mentioned closing on app close not. Going through menus for something that is automated on every single desktop browser and firefox itself before the downgrade Mugurell. 

Firefox is opened and swipe closed multiple times. 24 Hours is also not a solution to intentionally closed sessions multiple times a day. Appreciate the info but timers and poor design, they do not solve this problem.

**Comment by hakkikaancaliskan** [comment] 2021-03-30 13:09
I think #17634 is what you're looking for.

**Comment by lobontiumira** [comment] 2021-04-07 12:17
Closing this as a duplicate of #17634.
Thank you for your report!

**Closed by lobontiumira** 2021-04-07 12:17 UTC
Labels: needs:triage, 🐞 bug

**Comment by Oleophobic** [comment] 2022-03-30 09:03
Reminder one year later and not fixed
