### ISSUE TITLE
FNX-4482 ⁃ Add downloads list + new options

### ISSUE THREAD

**Issue by ndnddkoeo3dkej9** [mozilla-mobile/fenix#10702] opened 2020-05-16 16:15 UTC
### What is the user problem or growth opportunity you want to see solved?
Your feature request questions are weird. I'll just say one thing. It is not so important if growth or if this is a problem.

It's about general improvement of the download function. But only moderate, that means to add 3 to 5 new features per category (in this case download).

### How do you know that this problem exists today? Why is this important?
It is generally known that the download function is very popular. It should be extended a bit.

### Who will benefit from it?
All users.

- - -
### Description
In Firefox Android there is a downloads list, similar to Firefox Desktop.  But there is a big difference between these two versions. The desktop version, can clear the downloads list without deleting the files.

In Firefox Preview there is no downloads list.  There should be 2 new options added.  It is best to create a new category e.g. Settings -> Downloads

**Option 1:**
Enable or disable the Downloads list.  An example of what the option name could be called:  Downloads list (on/off)

**Option 2:**
This option only works if option 1 is activated.  When deleting the downloads list entries also remove the files (as with Firefox Android) or just clear the entries in the downloads list (as with Firefox Desktop).

### Version
Android 9

Firefox Preview 5.0.0
https://github.com/mozilla-mobile/fenix/releases/tag/v5.0.0

**Comment by cadeyrn** [comment] 2020-05-16 18:28
Duplicate of #349.

**Comment by ekager** [comment] 2020-05-16 20:23
Closing for #349

**Closed** 2020-08-11 01:29 UTC
Labels: needs:triage
