### ISSUE TITLE
[Bug] Fewer tabs in the tabs tray

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#19062] opened 2021-04-15 18:29 UTC
## Steps to reproduce
Click on 7 top sited
Click on the tabs tray

### Expected behavior
I can see 7 tabs in the tabs tray with the current one selected
### Actual behavior
6 Tabs are present in the tabs tray
![Screenshot_20210415-212131_Firefox_Nightly](https://user-images.githubusercontent.com/922368/114919983-9e382d80-9e31-11eb-99a0-ac7a7bfeb8aa.png)
![Screenshot_20210415-212137_Firefox_Nightly](https://user-images.githubusercontent.com/922368/114919990-a001f100-9e31-11eb-9f2c-01d3be1e062c.png)

### Device information

* Device vendor / model and Android version: OnePlus5t LineageOS 17.1 based on Android 10
* Firefox for Android version: ? Nightly 210415 17:02 (Build #2015804811)
AC: 75.0.20210413143139, 346a44da6
GV: 89.0a1-20210412092813
AS: 74.0.1

**Comment by jonalmeida** [comment] 2021-04-15 20:11
Duplicate of https://github.com/mozilla-mobile/fenix/issues/19023

**Closed by jonalmeida** 2021-04-15 20:11 UTC
Labels: needs:triage, 🐞 bug
