### ISSUE TITLE
[Bug]: Crashed on multi tasks

### ISSUE THREAD

**Issue by nvxarm** [mozilla-mobile/fenix#22570] opened 2021-11-24 07:59 UTC
### Steps to reproduce

1. Open any site in a task
2. Open any site in another task

### Expected behaviour

Crashed

### Actual behaviour

Working

### Device name

ROG Phone 5s

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

94.1.2 (Build #2015844587)

### Device logs

```
541ba196-beac-46e3-8686-985fdfa14da1
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 167201683 Other activity: HomeActivity hashcode 255483849
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec/?query=07c8d1d67d77495aaf13bbc7cdf45a94
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-db6e5165-8505-46c1-a2b5-535400211124
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec/?query=bc5e9ae91f6a4b76938ce0bc6f50d590
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-cd2e9373-f31a-4054-9205-2b31f0211124
----
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 167201683 Other activity: HomeActivity hashcode 255483849
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:16)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:15)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:20)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:7)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:7836)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: java.lang.IllegalStateException: Display already acquired
	at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:4)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:10)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)
	... 14 more
```

### Additional information

https://user-images.githubusercontent.com/16894061/143197572-809dc5f1-5959-4955-b836-2c8ea1c99c7e.mp4

**Comment by SoftVision-LorandJanos** [comment] 2021-11-24 12:56
Hi @nvxarm! Thank you for your report!
I didn't manage to reproduce your issue with the latest Release (94.1.2.).
Also using an Android 11 device (Xiaomi Mi11 Lite).
However your as report is well documented with video and log, it should help a lot.

**Comment by nvxarm** [comment] 2021-11-24 14:10
I installed the nightly version from Play Store on the same device, and find the case can only be reproduced after you've logged in.

Below is what I saw after I logged in with my Firefox account.

As for why my mail is not displayed in the main menu, that's another known issue  (#22284)


https://user-images.githubusercontent.com/16894061/143253424-9ec7cf18-4f64-4370-ada8-9780f87cc43f.mp4


```
96.0a1 (Build #2015847531), 693a1dd8f+
AC: 96.0.20211123143336, 84bfc17589
GV: 96.0a1-20211123094249
AS: 86.2.0

2021-11-24T05:12:22.494674
```

**Comment by Mugurell** [comment] 2021-12-16 08:37
Looks like this could benefit from the same solution as in https://github.com/mozilla-mobile/focus-android/pull/5918
cc @mcarare

**Comment by mcarare** [comment] 2021-12-20 13:04
I think this is a use case other than the one in the Focus fix. When opening a custom tab in a normal tab it is expected that the custom tab session is released, but that is not the case here. I am not even sure using multiple browsers is supposed to work.

**Comment by Mugurell** [comment] 2022-01-03 16:23
Agree.
Interesting scenario about using the same app in separate tasks but seems like this is bound to cause issues.
@pocmo Looks like this is something the app is not expected to support?

**Comment by pocmo** [comment] 2022-01-03 18:28
Yeah, two HomeActivities are not something support and have excluded in the manifest. I wonder how you ended up with two in the first place. In the video you seem to have two - even before using the split screen feature.

**Comment by mcarare** [comment] 2022-01-12 10:25
Closing this as this is not something we want to support( having two open apps) and it would involve significant changes in workflow. 

I still am curious about how this situation was possible, maybe @nvxarm would want to add some more details.

**Closed by mcarare** 2022-01-12 10:25 UTC
Labels: 🐞 bug, b:crash, Feature:Browsing, needs:triage
