### ISSUE TITLE
Fenix Nightly crashes during various events[Bug]

### ISSUE THREAD

**Issue by runboy93** [mozilla-mobile/fenix#8739] opened 2020-02-25 20:04 UTC
## Steps to reproduce

Read behavior.

### Expected behavior

Fenix Nightly should not crash during these events:

- Visiting websites with media (videos, I think?)
- Delete Browsing Data

### Actual behavior

Fenix Nightly does crash during visiting websites with media (videos?), and when clearing browsing data with "Delete Browsing Data" button from menu.

I've tested these websites, and Fenix Nightly crash but very likely it will crash with websites that has any media included, such as videos?:

https://classic.wowhead.com

https://animepahe.com/play/eizouken-ni-wa-te-wo-dasu-na/d5f58b2e7e54b14d0804170b84a003752beee67b

### Device information

* Android device: Android 10 (Samsung Galaxy A71)
* Fenix version: Latest nightly (February 25th, came out few hours ago, so 18:01 build?)

**Comment by concastinator** [comment] 2020-02-25 20:42
I can confirm this, on arstechnica.com, notebookcheck.net and, the clearest example, on https://9to5mac.com/2020/02/24/apple-to-release-first-arm-mac-without-intel-processor-in-next-18-months-predicts-kuo/. On the first two sites, you have to be patient and swipe up and down several times until it crashes. The 9to5mac page, though, you just have to try to open and the browser crashes instantly.

The crashes look random and appeared, for me, starting with the version released on February 24. I don't update Nightly every day, I let Google Play do it automatically, so the previous version, which was stable, must have been released around February 20. This should help developers locate the first buggy version.

The bug is so severe, and so blatant, that I'm surprised that nobody hasn't filed it yet.

**Comment by ekager** [comment] 2020-02-26 06:52
I believe this is the same as #8750 but putting QA needed for slightly different STR

**Comment by concastinator** [comment] 2020-02-26 09:49
This seems fixed in Nightly build 20570605 released on February 26. An explanation of the bug would be useful, though, given its severity.

**Comment by sv-ohorvath** [comment] 2020-02-26 15:40
I can't reproduce it either on Nightly 2/26 and it's also fixed for the reporter of #8767, so I'll close this as fixed.

**Closed by sv-ohorvath** 2020-02-26 15:40 UTC
Labels: eng:qa:needed, needs:triage, 🐞 bug

**Comment by concastinator** [comment] 2020-02-26 15:47
@sv-ohorvath, I believe that it is good practice to also explain where the bug was and what commit fixed it, for future reference in case of regressions. The fact that developers do not care to link bug reports to commits is bad development practice, which I don't like. If I were you, I would leave this bug report open, allowing developers to step in and comment on it.

**Comment by Amejia481** [comment] 2020-02-26 15:49
Sorry @concastinator I was about to comment on this issue, there are multiple reports of the same bug, sorry for that we had a pending migration for `autoplay` site permission, you could find more information here https://github.com/mozilla-mobile/fenix/issues/8750 and https://github.com/mozilla-mobile/android-components/pull/6076
