### ISSUE TITLE
FNX-4945 ⁃ [Bug] Fenix crashes when switching between locales

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1306] opened 2019-04-01 14:41 UTC
### Steps to reproduce
1. Open Fenix.
1. On your device, in Settings, go into Language preferences.
1. Change to a different language (eg. Russian/Japanese).
1. Open Fenix from the background.

### Expected behavior
Fenix opens without any issues.

### Actual behavior
Fenix Crashes.

### Device information
* Android device:
  * Affected:
    * Nexus 6P (Android 8.1.0)
    * Samsung Galaxy Tab S3 (Android 8)
  * Unaffected:
    * Google Pixel (Android 9)
    * Huawei P9 Lite (Android 6)
* Fenix version: 1.0.1914 (#10901215)
* [Logcat](https://github.com/mozilla-mobile/fenix/files/3029919/log.txt)

**Comment by kbrosnan** [comment] 2019-04-27 04:22
Closing as works for me. @bsurd reopen if you can reproduce using a current build.

**Closed** 2020-08-11 08:43 UTC
Labels: b:crash, 🐞 bug
