### ISSUE TITLE
[Feature Request] Allow flashlight when scanning QR code in the address bar

### ISSUE THREAD

**Issue by minhingent** [mozilla-mobile/fenix#23021] opened 2021-12-31 14:08 UTC
Would it be possible to be able to to be able to turn on the phone's flashlight when scanning QR codes? In dark rooms it is not always easy to scan a QR code and turning on the flashlight should make that easier.

**Comment by marcel263** [comment] 2022-01-01 08:22
duplicate #4313

**Comment by mcarare** [comment] 2022-01-04 10:00
Duplicate of https://github.com/mozilla-mobile/fenix/issues/4313.

**Closed by mcarare** 2022-01-04 10:00 UTC
Labels: needs:triage
