### ISSUE TITLE
Break out individual Tracking protection into different areas

### ISSUE THREAD

**Issue by IOI-655321** [mozilla-mobile/fenix#2604] opened 2019-05-17 13:14 UTC
Fenix needs overall controls that separate out the various aspects of tracking protection in the menu rather than an overall toggle that doesnt really specify what its doing.

Also it would be really nice to have a per site toggle in the UI clearly accessible similar to how brave does it (and im sure firefox focus used to??)

**Comment by cadeyrn** [comment] 2019-05-17 13:20
The first is a duplicate of #1085.

A _per site_ toggle is already there. You have to press the padlock, similar to Firefox for Desktop. In Firefox Focus you have to press the menu icon.

**Comment by ekager** [comment] 2019-11-14 01:05
We now have the TP icon in the toolbar with a new TP UI and per-site toggle and blocking categories displayed to match desktop. I'm going to close this.

**Closed** 2020-08-26 05:56 UTC
Labels: feature request 🌟
