### ISSUE TITLE
[Bug] Autofill of passwords doesn't work with 80.1.2 at all

### ISSUE THREAD

**Issue by journey-of-code** [mozilla-mobile/fenix#14880] opened 2020-09-09 10:54 UTC
## Steps to reproduce
1. (might be optional) Have a Firefox-Sync account with passwords filled from versions <79
1. Have the autofill setting set to active.
2. Open any page with credentials stored in the Firefox profile.

### Expected behavior
The stored login and password should be auto-filled with the stored credentials.

### Actual behavior
Nothing on the page indicates that any login data is stored. Long-click on username doesn't bring up anything with which to autofill the login. If a login and password is entered, FF asks if it should be stored. If the login/password is stored again, it will still not work.

### Device information

* Android device: Samsung Galaxy S8+ on Android 9 (Kernel 4.4.111) with Samsung One UI 1.0
* Fenix version: 80.1.2 (Build #2015761283)

### Discussion
Discussions in the forum (see [here](https://support.mozilla.org/en-US/questions/1301896) and [here](https://support.mozilla.org/en-US/questions/1301788) ) indicate that this is a common problem. Can't believe that I'm the first to enter a bug for this.

**Comment by journey-of-code** [comment] 2020-09-09 11:28
Possibly a duplicate of: 
* #12498 (but for me it never works)
* #14756 (but it seems not be limited to HTTPDigest)
* #13961 (but for me it never works)
Related: #10222

**Comment by fj6364** [comment] 2020-09-11 23:00
I had the same problem today: my saved logins are listed under Settings, but I had to retype them again in the login boxes at the affected site.  Also, Firefox for Android needs a password generator, the same as the desktop browser.  Why can't I copy and paste my login information from Settings to the login page?  This is very inconvenient...thank you.

**Comment by journey-of-code** [comment] 2020-09-14 07:53
@ekager Why would this be a feature and not a bug? It was working before version 80. Also the current implementation makes no sense - passwords are remembered but cannot be used.

**Comment by cadeyrn** [comment] 2020-09-14 08:18
> It was working before version 80

It was working in Firefox 68 or 79? If it didn't work in 79 everything that is not an error in the implementation is a feature request and not a bug because it's a completely new browser. Independent of this - it was you yourself who opened this issue as bug report.

**Comment by journey-of-code** [comment] 2020-09-14 09:01
@cadeyrn you are right, my fault. Sorry @ekager. 
It was working with the version before the new engine was pushed through the app store. Always updated but I don't know which one was the last before the new version.

**Comment by ekager** [comment] 2020-09-14 17:24
@journey-of-code could you give an example of a site that isn't autofilling? Do you have multiple logins saved for those sites? Do those sites redirect on mobile to a mobile version of the site? Thanks!

**Comment by journey-of-code** [comment] 2020-09-16 11:15
@ekager : An interesting point. So far none of the sites I visited had the autofill for passwords. Now I checked and **(1) https://github.com works**, while **(2) https://klengymuc.eltern-portal.org/ doesn't work**. I have two (identical) logins stored in the passwords for (2) and only one for (1). Tested the assumption that multiple logins prevent autofill from working. Seems not to be the case because I found three logins for (3) https://deviantart.com where it works. All three sites have a mobile page which is displayed as default. When requesting the desktop version, behavior is unchanged - still doesn't work for (2) while it works for the others. I remember reading something about different technology used for the authorization so let's check for that:
- all use a form for the login
- all use input fields for login name and password.

**Comment by ekager** [comment] 2020-09-16 15:45
@journey-of-code thanks for the info! So it is expected that sites with multiple logins would not work on this version. Multiple login selection has landed since this version and will eventually make it's way to release very soon. If you want to double check you can download Beta or Nightly and it will hopefully work there! Closing for now as it has been fixed.

**Closed by ekager** 2020-09-16 15:45 UTC
Labels: Feature:Logins, 🐞 bug

**Comment by fj6364** [comment] 2020-09-16 16:15
Thanks again...the autofill features are active now.On 9/16/20, 11:45 ekager <notifications@github.com> wrote:

   
  Closed #14880.

**Comment by fj6364** [comment] 2020-09-16 16:17
Thank you!  The autofill features are active now.On 9/16/20, 11:45 ekager <notifications@github.com> wrote:

   
  @journey-of-code thanks for the info! So it is expected that sites with multiple logins would not work on this version. Multiple login selection has landed since this version and will eventually make it's way to release very soon. If you want to double check you can download Beta or Nightly and it will hopefully work there! Closing for now as it has been fixed.

**Comment by journey-of-code** [comment] 2020-09-17 12:07
@ekager : After removing all logins except of one, the autofill works on the site that has not been working before. Thanks for taking care!
