### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#7962] opened 2020-01-28 23:58 UTC
### Device information

When you open the answer given to comments while using Twitter, the page goes to the top

* Android device: ?

Lenovo K6 Note
* Fenix version: ?

**Comment by cadeyrn** [comment] 2020-01-29 06:26
Could you please fill out the title field of the issue? Otherwise it's not possible to know what the issue with the title "[Bug]" is about in the list of issues. Thank you…

**Comment by NotWoods** [comment] 2020-01-29 17:05
Duplicate of #7974. Please edit your existing issue in the future

**Closed by NotWoods** 2020-01-29 17:05 UTC
Labels: needs:triage, 🐞 bug
