### ISSUE TITLE
Downloading no longer works

### ISSUE THREAD

**Issue by ximikas** [mozilla-mobile/fenix#16289] opened 2020-10-30 19:03 UTC
Firefox android 82.1.1 no longer able to download any file .
Initially it was unable to download pdf datasheet from most links ,but one or two links worked ,first idea was internet problem and i switched from wi-fi to 4g ,nothing changed . Later noticed firefox crash ,if i clicked three dots and Downloads .Crash log was submitted few times . Then cleared app cache and data ,not helped ,but no longer crashing , just opens empty window " no downloads". File browser on phone opens downloads folder and shows files ,downloaded before , so folder is ok .
Problem at least with pdf files . Clicking on download link and dialog to download file with its size appears ,click accept , in notification bar displaying "downloading " ,but no actual progress , no percentage ,no file name ,just time how long ago it started and download never completes .
Android 9 , Asus Zenfone6 ZS630KL .Enough free space available on phone , tried to delete some files ,nothing changed .Phone not rooted , how to reach logs ? 
What to do next ? The same files download from pc at same time ,so its not internet or server related .Looks like new bug for me .

**Comment by Amejia481** [comment] 2020-10-30 19:38
Thanks for reporting @ximikas  are you able to reproduce in [Beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) or [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)?

**Comment by Amejia481** [comment] 2020-10-30 19:39
QA team could you please help us to verify this issue, thanks in advance!

**Comment by ximikas** [comment] 2020-10-30 19:52
Just installed firefox beta and confirming - in Beta the same download link from google results works ,pdf file quickly downloads and dialog " open" appears .

**Comment by bytesnz** [comment] 2020-10-31 15:33
I'm running on Beta 82.0.0-beta.4 (Build #2015768089) and have had the same issue for a couple of weeks. Have had 1 or 2 download, but most show as downloading starting, then failed a few minutes after.

**Comment by n-m-k** [comment] 2020-10-31 16:11
I have had the same problem for a few days. Under Firefox 82.1.1 no download is possible anymore. The download starts as usual, but does not finish.

I have tested this on 3 different devices. Samsung Note 8 (Android 9), Samsung Tab S3 (Android 9) and Samsung S4 (Android 5.01). On the Samsung S4 Firefox 80.1.3 was previously installed. The download still worked then. After updating to the current version the download does not work anymore. I have tested it under WLAN as well as under an LTE connection

Pictures that I mark on a web page I can save on the smartphone. But all types of files that are triggered by a download function I cannot download.

**Comment by quazgar** [comment] 2020-10-31 17:10
Could this be a regression caused by a possible fix for #16168?

**Comment by quazgar** [comment] 2020-10-31 17:19
Additional hint:
The download consistently fails at this percentage.
![image](https://user-images.githubusercontent.com/302587/97785475-8af81500-1ba5-11eb-9970-bc778e58eb63.png)

**Comment by ximikas** [comment] 2020-10-31 17:35
I can confirm that too ,just tested - in 82.1.1 non-beta ,in normal mode pdf downloads not possible ,but in private mode works .

**Comment by n-m-k** [comment] 2020-10-31 17:58
All types of files are hit.

**Comment by n-m-k** [comment] 2020-10-31 17:59
All types of files are hit

**Comment by n-m-k** [comment] 2020-11-01 09:53
I have just tested with the Nightly Version 201031 17:02(Build#2015772937). With this version the download works as it should.
I have tested on an old device (Device: Samsung S4, Android 5.01), because I do not want to install test versions on my productive device.

**Comment by LittleAngelwings** [comment] 2020-11-01 21:21
dupe of this? https://github.com/mozilla-mobile/fenix/issues/16168

**Comment by blankm** [comment] 2020-11-02 09:23
I also experience that behavior, mostly with PDFs. Strangely, the setting "External download manager" has absolutely no effect on the problem. Clearing cache etc doesn't help. I also started seeing this with PDFs.

82.1.1 (Build #2015770923)
AC: 60.0.5, a1a471ddc
GV: 82.0-20201014125134
AS: 63.0.0

**Comment by n-m-k** [comment] 2020-11-02 09:54
> 
> 
> I also experience that behavior, mostly with PDFs. Strangely, the setting "External download manager" has absolutely no effect on the problem. Clearing cache etc doesn't help. I also started seeing this with PDFs.
> 
> 82.1.1 (Build #2015770923)
> AC: 60.0.5, a1a471ddc
> GV: 82.0-20201014125134
> AS: 63.0.0

I can fully confirm these remarks.

**Comment by sv-ohorvath** [comment] 2020-11-02 12:46
@Amejia481 All the reported issues here sound like a dupe of https://github.com/mozilla-mobile/fenix/issues/15378, happening only on 82. Working fine on 83 Beta and current Nightly for me and others. I'm going to close this one in favor of the other since it has more history. If you need any more investigation, please let me know.

**Closed by sv-ohorvath** 2020-11-02 12:46 UTC
Labels: Feature:Download, eng:qa:needed, needs:triage, 🐞 bug

**Comment by jxu** [comment] 2021-01-07 06:08
I have this issue on Firefox 82.1.3, Android 11. How Mozilla can release a version of a browser that can't even download a PDF baffles me.

**Comment by cadeyrn** [comment] 2021-01-07 07:05
@jxu You're using an outdated version of Firefox. The current version is 84.1.3. Please test with Firefox 84.1.3 and report back if the problem still exists.

**Comment by n-m-k** [comment] 2021-01-07 15:24
Since version 84.x.x the problem no longer exists.
