### ISSUE TITLE
[Bug] Fenix doesn't show GSMArena favicon but Desktop does

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#8669] opened 2020-02-22 10:40 UTC
navigate to m.gsmarena.com
Get a generic G favicon in tabs tray and if I make it into a Top Site
Selecting "Desktop site" and using www.gsmarena.com has the same issue
Fennec also has the same issue, missing favicon

Firefox Desktop Mac correctly shows the favicon for both m.gsmarena.com and www.gsmarena.com. Likewise Chrome Android correctly shows the favicon for m.gsmarena.com

But Samsung Internet Android has the same issue as Fennec/Fenix, so it may be a malformed site????

(Fennec has had this issue for years, it seems to have been inherited by Fenix)

* Android device: Galaxy A40, Android 9.0.0
* Fenix version: Today's Nightly

**Comment by Cheap-Skate** [comment] 2020-02-22 11:14
![Screenshot_20200222-111326_Firefox Nightly](https://user-images.githubusercontent.com/40568887/75091389-7cf8eb80-5564-11ea-9c4f-7e0e1ea1a99b.jpg)

**Comment by softvision-miralobontiu** [comment] 2020-12-03 13:06
Tested on Samsung Galaxy Note 8 (Android 9), and on HTC 10 (Android 8), on the 12/3 Firefox Nightly build.
The tabs tray is now displaying a screenshot of the website, but, indeed, the top site's favicon only displays a "G":
![Untitled](https://user-images.githubusercontent.com/40694158/101021797-0ec46900-3579-11eb-9e6b-3bdf3ce5fa2d.png)

**Comment by Cheap-Skate** [comment] 2020-12-03 13:19
Oddly, I now *do* get a GSMArena favicon. I deleted it from Top Sites and re-added it and it still appears OK. Galaxy A40, Android 10, today's Nightly.   BUT now I don't always get a favicon for mozilla.org.  I think it might have something to do with when the Top Site was added and whether it is pinned or not. In the example below, the pinned mozilla.org gets a favicon but the unpinned mozilla.org, which I think comes from History, does not.  If I open a tab using the unpinned mozilla.org it correctly loads the page but it doesn't update the favicon.

So perhaps this issue is more subtle than just GSMArena? 
![Screenshot_20201203-131754_Firefox Nightly](https://user-images.githubusercontent.com/40568887/101022994-0d3f7480-356a-11eb-9e49-0bab81189ae2.jpg)

**Comment by Cheap-Skate** [comment] 2020-12-03 15:51
I see similar in History (3 dot menu -> History).  Some History entries have the correct favicon, some do not (just placeholders)
Or, enter a search term eg arstechnica and look at the History suggestions. Sometimes arstechnica.com has correct favicons, sometimes it does not (just placeholders)
![Screenshot_20201203-154918_Firefox Nightly](https://user-images.githubusercontent.com/40568887/101053004-2dc5f980-357f-11eb-8993-2e986bf29086.jpg)

**Comment by Cheap-Skate** [comment] 2020-12-04 13:38
It's complicated. On my Galaxy S7:-
- delete all browsing data
- delete all Top Sites by hand
- navigate to gsmarena.com
- look at Top Sites
-> GSMArena.com has no favicon, just a purple rectangle with a G (*unexpected*)
- go back to the GSMArena.com tab
- tap 3 dot menu and "Add to top sites"
- look at Top Sites
-> GSMArena still has no favicon (*unexpected*), but it has a pin. There is also a lower case gsmarena.com Top Site with no pin and no favicon (*unexpected*)

With arstechnica.com I see different behavior
- when arstechnica.com is not a pinned Top Site it has no favicon (*unexpected*)
- if I pin arstechnica.com by selecting "Add to top sites" from the tab, it gets the correct favicon (*expected*)

But on my Galaxy A40 GSMArena.com is pinned and has a favicon.  (my A40 is my daily driver so I don't want to clear history etc)

**Comment by kbrosnan** [comment] 2020-12-09 19:07
Duplicate of https://github.com/mozilla-mobile/android-components/issues/3814

**Closed by kbrosnan** 2020-12-09 19:07 UTC
Labels: Feature:TopSites, S3, 🐞 bug
