### ISSUE TITLE
Missing content on page [webcontent]

### ISSUE THREAD

**Issue by noman2193** [mozilla-mobile/fenix#9844] opened 2020-04-10 02:53 UTC
### Can you reproduce in Chrome (or other non-Mozilla browser)?
No, it works fine in Chrome

### Device information

* Android device: Pixel 3
* Fenix version: 4.2.1

**Comment by sv-sdeiac** [comment] 2020-04-10 13:27
Hi @noman2193 and thanks for your report.
Unfortunately, I can't reproduce your issue using Firefox Preview Nightly debug build from 4/10 or Firefox Preview Beta 4.2.1 with Google Pixel 3 (Android 10).

Can you provide specific steps or a video with your issue so we can track it? 
I'll wait for your updates, thanks.

**Comment by noman2193** [comment] 2020-04-10 15:39
Hi,

Thanks for getting back to me so quickly! I wasn't sure how to attach
screen shots, so perhaps my explanation was not clear. Please see the
attached screenshots for how the page should look and how it appears in
Firefox Preview.

cheers,
Lukasz

**Comment by kbrosnan** [comment] 2020-04-10 18:16
You can't add attachments to issues in Github via email. You need to use the web interface.

**Comment by noman2193** [comment] 2020-04-11 04:00
Sorry about that! I've attached them below. The first one (with more text and links) is in Chrome. The second one with only an image and logo (also an image) is on Firefox Preview. The rest of the website works fine. Only the homepage is missing content.

![correct display (in Chrome)](https://user-images.githubusercontent.com/24868908/79034838-07b8a700-7bf4-11ea-97f8-fd34ce9654b8.png)
![missing elements (Firefox Preview)](https://user-images.githubusercontent.com/24868908/79034840-08e9d400-7bf4-11ea-9ae7-ac3db9114e87.png)

**Comment by sv-sdeiac** [comment] 2020-04-13 07:13
Hi, thanks for your updates.
I tried another one time using the RC build 4.2.1 and Beta 4.2.1-beta.1 both from Google playstore an I wasn't able to reproduce the issue.

Devices:
- Google Pixel 3 (Android 10);
- Google Pixel 3a (Android 10);
- Google Pixel 3 XL (Android 9);
- Huawei Mate 20 Lite (Android 9);
- OnePlus A3 (Android 6.0.1).

Do you have some specific settings on your Firefox Preview?

**Comment by noman2193** [comment] 2020-04-13 07:27
No specific settings. I do have ublock origin installed, but this issue has been present from before add-ons were even available in Preview. It doesn't change anything with ublock on or off. Also, I have a Pixel 3 with Android 10, latest build. I tried it as well in Nightly, and it's the same issue.

One more thing, when I refresh the page, the text content appears for a split second and then disappears. Only the images remain. This is also the only website with which I have this issue.

But if it cannot be reproduced then indeed it might just be my phone for some  reason.

**Comment by softvision-miralobontiu** [comment] 2020-10-20 13:33
@noman2193 I cannot reproduce this issue on Google Pixel (Android 10) on the latest Firefox Nightly from 10/20.
I'll close this issue.

**Closed by softvision-miralobontiu** 2020-10-20 13:33 UTC
Labels: b:webcompat, needs:triage
