### ISSUE TITLE
[Bug] When opening links from collections or top sites they aren't loading newest contents and seem to be older cached copies?

### ISSUE THREAD

**Issue by jamesuk1981** [mozilla-mobile/fenix#16222] opened 2020-10-27 23:10 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Hi, I am using the latest version of Firefox and I am finding I am having some issues which I don't believe I had before.

Previously I would have my bookmarks as my home page, if feels pretty laborious to get to them and open multiple pages at once now so instead I have opted to have my bookmarks as my to sites and also in collections.

The issue though if when I go to sites from there it always seems to load an old cached copy of that site, I look at news sites a lot and I am finding however there page looked the last time I was on that site is what seems to open the next time I open it which might be a few hours later and I know that page has since been updated, if I refresh the site the latest contents will then load but I really don't want to have to tap refresh ever time i visit a site.

Is there anything way around this because it's really getting annoying and I never know if what I am looking at is the up to date site contents or old contents.

Maybe it was done this way to make Firefox seem faster by loading a cached copy but maybe if there was an option to always load latest contents would be great?

I hope you can help with this as I have only noticed it since the latest version you released.

Regards

James

### Device information

* Android device: Samsung S10+
* Fenix version: ? I don't know what this is?

**Comment by kbrosnan** [comment] 2020-10-28 01:07
Duplicate of #10417

Currently this is expected behavior.

**Closed by kbrosnan** 2020-10-28 01:07 UTC
Labels: needs:triage, 🐞 bug
