### ISSUE TITLE
[Bug] Crash whenever we switch to Open in Firefox

### ISSUE THREAD

**Issue by kelimuttu** [mozilla-mobile/fenix#15846] opened 2020-10-12 06:45 UTC
## Steps to reproduce
- Set Firefox as a default browser
- Open a link from other app like Telegram, a substance of Firefox will open. When we click the three dots button on the right corner, it will say Powered by Firefox.
- Click Open in Firefox. A full firefox browser app will open as a new window.
- Switch to the the original window that was opened from Telegram, you will be taken to homepage. 
- Click the latest tab you opened

### Expected behavior
- The tab would be open

### Actual behavior
- The window will be closed and you will get a crash notification
![photo_2020-10-12 13 42 51](https://user-images.githubusercontent.com/4922388/95713507-d8612080-0c90-11eb-8e4f-679a763ba429.jpeg)

### Device information

* Android device: Huawei p30 pro, android 10
* Fenix version: 81.1.4

**Comment by kbrosnan** [comment] 2020-10-12 08:30
Duplicate of https://github.com/mozilla-mobile/fenix/issues/14225

This will be fixed in the next release v82

**Closed by kbrosnan** 2020-10-12 08:30 UTC
Labels: needs:triage, 🐞 bug
