### ISSUE TITLE
[Feedback] Using alternative search engines requires too many taps

### ISSUE THREAD

**Issue by openjck** [mozilla-mobile/fenix#4333] opened 2019-07-26 19:07 UTC
I liked how easy it was to use alternative search engines in the old Firefox for Android: just type a few characters and tap the Amazon icon, for example.

Doing this requires many more taps in Fenix: first type the query, then tap <s>*Shortcuts*</s> (now *Search engine*), then tap the Amazon icon, then tap enter. Even just removing that last step would be a big improvement.

* Android device: 9 (patch level July 5, 2019)
* Fenix version: 1.0.1 (Build #11891918 🦎 68.0-20190611143747)

**Comment by argymeg** [comment] 2020-05-19 13:27
I came here to report this exact thing so I figured I should add my voice. The "old" interface is much closer to the desktop experience and much more intuitive - three taps to search is far too many. As OP said removing the last step would be an improvement (it's highly unlikely anyone is picking a different engine to then pick a different search suggestion), but also IMO it would be much nicer if the alternative options were presented in a row at the bottom like in the old interface, or got "minimised" there after the user starts typing in the search box.

**Comment by yringot** [comment] 2020-08-26 02:21
I got the new firefox mobile (79.0.5 build #2015758619) update a few days ago and searching with non-default search engines is now very time-consuming:

**Old workflow:** tap the address bar, start typing your search term and then either press return to search with default search engine, or 2) tap one of the custom search engine buttons. In both cases, the search was executed directly.

**New Firefox:** (go to settings to enable non-default search engines to be displayed) Best case: tap the address bar, enter your search term, press return or one of the non-default search engines and then return.

The problem is that many of the build-in custom search engines and definitely those newly added by myself are at the bottom of the list and obscured by the keyboard, meaning that in order to select it after typing my search terms, I have to scroll down, *causing the keyboard to collapse*. After selecting the right search engine firefox doesn't then search automatically but rather I have to tap the address bar again and then press return. So, where in the past I had a "tap, type, tap, (search results)" experience, now it is "tap, type, scroll, tap (bottom of screen to select SE), tap (top of screen into the address bar to get the keyboard back), tap (bottom of screen [return key on keyboard]), search results"

I very much would like to go back to the old behavior. To fix this, triggering the seach upon tapping the custom search engine icon would already be better: "tap, type, scroll, tap (bottom of screen to select SE), [search results]"

**Comment by miDeb** [comment] 2020-08-28 09:37
I think there are two things that could be done:
- Pop up the keyboard again when a search engine is selected. There's not much that the user could do other than opening the keyboard after selecting a search engine, so I guess we can just automatically do that. I'm going to open a PR for that.
- Add a "->" arrow button to each search engine to immediately start a search.
Currently the autocomplete arrow is shown in that position, which I don't think makes much sense. We could replace it.

**Comment by apbitner** [comment] 2020-09-11 18:30
Pinging @brampitoyo for search feedback

**Comment by brampitoyo** [comment] 2020-09-14 06:37
@miDeb responding to your post:

> Pop up the keyboard again when a search engine is selected. There's not much that the user could do other than opening the keyboard after selecting a search engine, so I guess we can just automatically do that. I'm going to open a PR for that.

Yes. Agreed. This totally makes sense!

> Add a "->" arrow button to each search engine to immediately start a search.

Popping the keyboard up on search provider selection, but not actually performing the search straight away, gives you the ability to see suggestions from that search engine and amend your keywords. We think that seeing suggestions before performing a search is important to get to the right results faster.

And should you want to start search immediately without amending your original keyword or acting on any suggestion, you can simply tap the Enter/Return key on the keyboard that has opened automatically.

So my suggestion is:

1. Pop the keyboard open immediately after selecting the search engine
2. Don’t perform the search after selecting the search engine – give people a chance to see keyword suggestions

**Comment by madb1lly** [comment] 2020-09-23 14:50
Hi @brampitoyo,

Your UX feedback doesn't really address the points made:
1. That in Fenix we have the additional tap and sometimes scroll vs Fennec to bring up the list of search engines. This didn't exist in Fennec, it wasn't necessary - we had keyboard, text entry field, alternative search providers _and_ search suggestions, all at once. 
2. In Fenix even after selecting an alternative search engine we still need to confirm the search string and confirm the search.

I think that the quickest that the current system can be used is two taps with typing in the middle:
1. Select alternative search engine: 1 tap if it's above the keyboard, otherwise swipe and 2 taps are needed before:
2. Type search string
3. Start search either by tapping enter or by selecting from search suggestions

Most times though it takes longer than that, especially if we type the search before selecting the search engine (which is normal, because this is the muscle memory from Fennec and to a lesser extent Desktop).

Instead of requiring to reconfirm the search string or choose a suggestion before launching the search, why now add the ability to  long tap a provider to use that search string directly with that provider without having to confirm the search string? Unfortunately this isn't very discoverable, but it is a compromise.

Cheers 🙂

**Comment by brampitoyo** [comment] 2020-09-24 05:40
@madb1lly thanks for providing an interesting way out of this problem:

> […] why no[t] add the ability to long tap a provider to use that search string directly with that provider without having to confirm the search string?

First of all, I do agree that Fenix does search engine selection differently than Fennec:

- Fenix: selecting a different search engine doesn’t perform a search. Instead, it shows suggestions from that search engine.
- Fennec: selecting a different search engine performs a search. It doesn’tt show suggestions from that search engine.

This change has an impact to muscle memory, especially for people who are already used to Fennec.

In this area, Fenix is paving the way. If I recall correctly, our user studies had found the interface more flexible and easier to use. So in the future, we will bring Fenix’s search engine selection mode to both iOS and Desktop.

But as you wrote, there’s a not insignificant cost to muscle memory, and a little bit of time wasted from having to confirm the search string by clicking somewhere else on the screen.

I appreciate this solution you’ve offered:

> […] add the ability to long tap a provider to use that search string directly with that provider without having to confirm the search string

This seems like it would also work on iOS, where a long-press can also commit to search directly. I will check with our search team and see how they think.

**Comment by madb1lly** [comment] 2020-09-28 12:42
Hi @brampitoyo,

Thanks for the feedback, it's good to know that this is a possible improvement.

Cheers 🙂

**Comment by PisauraXTX** [comment] 2020-10-04 08:14
> In this area, Fenix is paving the way. If I recall correctly, our user studies had found the interface more flexible and easier to use. So in the future, we will bring Fenix’s search engine selection mode to both iOS and Desktop.
> 
> But as you wrote, there’s a not insignificant cost to muscle memory, and a little bit of time wasted from having to confirm the search string by clicking somewhere else on the screen.

I would like to suggest another possible solution: Just display the selection of search engines in the bottom row above the keyboard again. I don't believe anyone needs a QR code scanner button that takes up half of the screen's width there. And the other half could better be filled with buttons for all the search engines. I don't see the use in having an extra button to press here, then move your finger halfway across the screen to pick the search engine you want to use. 

I personally don't mind having to press enter one more time, but with the added benefit of being shown suggestions for the search engine that I selected. 
If I have to either select the engine first, then type, then press enter, everything is fine. 
But if I type the search string first, I then have to click on the search engines menu button, go back up and select the search engine, then go down and press enter. It adds an extra step and a whole lot of movement which wouldn't be necessary if the search engines were simply displayed in the bottom row above the keyboard at all times.

**Comment by miDeb** [comment] 2020-10-04 15:19
@PisauraXTX if you enable "show search engines" in the search settings, it will show search engines right when you open the toolbar. Is that what you meant?

**Comment by PisauraXTX** [comment] 2020-10-05 11:49
> @PisauraXTX if you enable "show search engines" in the search settings, it will show search engines right when you open the toolbar. Is that what you meant?

No, I am talking about the bar with the QR code scanner button on the left and the search engines button on the right. I think this bar should be replaced with one showing buttons for all the enabled search engines. If you really want the QR scanner in there, it can still be included (Maybe give the option to turn it on and off). But there is no need for it to take up half of the screen's width. 

The problem with the "Show search engines" option is that 1), they disappear as soon as you type something in and 2), they take up space that was used for suggestions in previous versions.

**Comment by LaurentiuApahideanSV** [comment] 2020-12-15 12:12
Verified as fixed on Firefox Preview Nightly 201215 (Build #2015781483), when a search engine is selected the keyboard pops up.
### Devices used:
- Samsung Galaxy S9 (Android 8.0.0)
- OnePlus 6T (Android 9)

**Closed** 2020-12-15 12:49 UTC
Labels: Feature:Search, eng:qa:verified, feature request 🌟
