### ISSUE TITLE
FNX-3371 ⁃ [Bug]60fps instead of 120fps on OP8Pro

### ISSUE THREAD

**Issue by karot85** [mozilla-mobile/fenix#10225] opened 2020-04-26 08:20 UTC
## Steps to reproduce
When you go on this website https://t.co/ythS9dyhhh?amp=1 with Firefox Preview, it shows around 60FPS contrary to Chrome that gives around 120fps.

## Tested on :
It has been tested on OnePlus 8Pro with Android 10 and firefox Preview 4.3.0 Build #21082025

**Comment by cadeyrn** [comment] 2020-04-26 08:40
Duplicate of #7560.

**Comment by sv-sdeiac** [comment] 2020-04-27 07:26
Closing as a duplicate of #7560.

**Closed** 2020-08-10 19:38 UTC
Labels: 🐞 bug
