### ISSUE TITLE
[Bug] Text and images on all sites are broken

### ISSUE THREAD

**Issue by deevroman** [mozilla-mobile/fenix#16202] opened 2020-10-27 07:26 UTC
Text on all sites broken 
![Screenshot_2020-10-27-10-21-16](https://user-images.githubusercontent.com/25708359/97269620-decdcb80-183e-11eb-8dd8-cfe78f350e91.png)

Android 5.1.1 Samsung Galaxy j1
Nightly 201026 17:01 (Build #2015771977)
AC: 64.0.20201023143136, d78abdf9f
GV: 84.0a1-20201022093646
AS: 63.0.0

**Comment by deevroman** [comment] 2020-10-27 07:30
![Screenshot_2020-10-27-10-28-18](https://user-images.githubusercontent.com/25708359/97269935-5bf94080-183f-11eb-8062-c96f43f2d308.png)

**Comment by AndiAJ** [comment] 2020-10-27 08:25
Hi, I **wasn't able reproduce** this issue on the latest **`Nightly Build 201027`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
• Samsung Galaxy Tab A6 (Android 5.1.1)

**Comment by Cheap-Skate** [comment] 2020-10-27 11:02
I have seen this very rarely (once a week maybe???) Sometimes all characters are replaced with black squares, sometimes only about half the characters are replaced. Closing the tab fixes it. I will take a screenshot next time I see it.

**Comment by deevroman** [comment] 2020-10-27 13:00
It started about two builds ago and now so any pages (((

**Comment by deevroman** [comment] 2020-10-27 19:31
Alas, the problem does not disappear in `Nightly Build 201027`

**Comment by deevroman** [comment] 2020-10-27 19:51
Even reinstalling the application did not help

**Comment by mcarare** [comment] 2020-10-30 12:07
@deevroman This looks like missing fonts, I guess it only happens on websites with Cyrillic characters?
Do you have any addons active? Maybe "NoScript"?

**Comment by deevroman** [comment] 2020-10-30 15:56
`Even reinstalling the application did not help`
Because of this, there are no extensions

I will specify. Broken not only text. Here is the current page
![Screenshot_2020-10-30-18-53-39](https://user-images.githubusercontent.com/25708359/97727522-9124bd80-1ae1-11eb-83b2-840373316a3e.png)

**Comment by deevroman** [comment] 2020-11-19 16:26
Bug fixed

Nightly 201118 17:04 (Build #2015776393)
AC: 67.0.20201117165227, d5524f7a5
GV: 85.0a1-20201117094406
AS: 67.0.0

**Closed** 2020-11-19 16:26 UTC
Labels: S2, b:web-content, 🐞 bug
