### ISSUE TITLE
Drag and Swap Libraries are impossible to use

### ISSUE THREAD

**Issue by JVariance** [mozilla-mobile/fenix#18451] opened 2021-03-12 08:56 UTC
## Info

It does for example work correctly or as expected with Monument Browser. Didn't test it with a chromium based browser, though I expect it to work there, too.

## Steps to reproduce

1. Open [interact.js](https://interactjs.io/pro/) or [Draggable JS](https://shopify.github.io/draggable/).
2. Try to drag and swap example elements.

### Expected behavior

The page doesn't scroll when dragging and swapping elements.

### Actual behavior

The page does scroll when trying to drag and swap elements, so it gets nearly impossible .

### Device information

* Device vendor / model and Android version: Samsung Galaxy S7, Android 8.0.0
* Firefox for Android version: Nightly 210310 17:03 (Build #2015797899)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10029)

**Comment by Mugurell** [comment] 2021-03-12 11:36
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1698052

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Mugurell** [comment] 2021-06-22 06:42
@JVariance I think the issue has been resolved in the latest Nightly. Can you confirm?

**Comment by JVariance** [comment] 2021-06-22 10:27
> @JVariance I think the issue has been resolved in the latest Nightly. Can you confirm?

Unfortunately not. On interactjs.io you e.g. can't swap elements on y-axis, because Firefox scrolls the page instead. Same with other examples on the page.

**Comment by JVariance** [comment] 2021-06-22 10:30
I'm on version 91.0a1 (Build #2015817683)

**Comment by JVariance** [comment] 2021-07-05 16:49
Tried those just now and unfortunately it doesn't work...

https://sortablejs.github.io/Sortable/

https://svelte.dev/repl/e2ef044af75c4b16b424b8219fb31fd9?version=3.22.2

**Comment by Mugurell** [comment] 2021-07-06 14:35
@JVariance Can you please post a video for the issue you're seeing?

**Comment by JVariance** [comment] 2021-07-06 19:06
Firefox is simply scrolling the page when I rather want to reorder/drag the items, so this is an impossible task.

**Comment by Mugurell** [comment] 2021-07-09 11:10
I cannot reproduce the scrolling issue in the current Nightly:
(there is an issue with pull to refresh on the `sortable.js` page that I'm still investigating though so for the below video I've disabled pull to refresh).

https://user-images.githubusercontent.com/11428869/125069121-fdb77980-e0be-11eb-92fe-f2b9c31ef403.mp4

If this is still an issue for you a video of it would be of great help.

**Comment by JVariance** [comment] 2021-07-09 12:41
https://user-images.githubusercontent.com/62245444/125078999-6d2f6800-e0c3-11eb-966b-4d83eaefbafe.mp4

**Comment by Mugurell** [comment] 2021-07-09 14:13
Thank you!
I've created https://bugzilla.mozilla.org/show_bug.cgi?id=1719855 as a browser issue for more investigations.

**Comment by Mugurell** [comment] 2021-07-09 14:13
On our side I'd be curious if this device is somehow device specific. Would be great to test on more devices to try to find the configuration in which this reproduces or not.

**Comment by JVariance** [comment] 2021-07-09 17:27
On Galaxy S5 it's neither working.

**Comment by abodea** [comment] 2021-07-13 09:47
Hello I tested this on the latest Nightly 7/13 with Google Pixel 4 XL (11), Samsung Galaxy S10+ (10) but I was not able to reproduce this issue.
I had no issues regarding drag and Swap libraries even when the `pull-to-refresh was on.
Can you please attach a video while reproducing this issue on the S5? Might be a device-specific.

**Comment by JVariance** [comment] 2021-07-13 13:44
> Hello I tested this on the latest Nightly 7/13 with Google Pixel 4 XL (11), Samsung Galaxy S10+ (10) but I was not able to reproduce this issue.
> I had no issues regarding drag and Swap libraries even when the `pull-to-refresh was on.
> Can you please attach a video while reproducing this issue on the S5? Might be a device-specific.

It's still missbehaving.
I also already made a video. See above.

**Comment by JVariance** [comment] 2021-08-07 06:03
What I noticed is that it works if you directly perform the action (like click event).
But it won't work after a longpress before the drag action.

**Comment by Mugurell** [comment] 2021-11-09 15:27
Seems like this issue needs more investigation on GeckoView side.
Will remove my assignment in the interim.

**Comment by JVariance** [comment] 2022-12-03 08:59
@Mugurell does the "GeckoView side" know about this? It's still not fixed.

**Comment by Mugurell** [comment] 2022-12-05 11:21
> @Mugurell does the "GeckoView side" know about this? It's still not fixed.

The GeckoView ticket is https://bugzilla.mozilla.org/show_bug.cgi?id=1719855 where there are no recent developments unfortunately.

**Comment by cpeterso** [comment] 2022-12-19 21:09
We're tracking the sortablejs.github.io bug in https://bugzilla.mozilla.org/show_bug.cgi?id=1719855 and the player.fm (HTML drag-and-drop API) in https://bugzilla.mozilla.org/show_bug.cgi?id=1764177.

**Closed by cpeterso** 2022-12-19 21:09 UTC
Labels: 🐞 bug, needs:gv
