### ISSUE TITLE
[Bug] PBM notification icon is invisible

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#14460] opened 2020-08-29 19:48 UTC
## Steps to reproduce
Open a private tab

### Expected behavior
You can see the PBM icon in the notification

### Actual behavion
You can't
![Screenshot_20200829-214723_Firefox Nightly](https://user-images.githubusercontent.com/44171190/91644948-3e774880-ea41-11ea-85d5-63c7f65496ee.jpg)

### Device information

* Android device: Samsung Galaxy A50
* Fenix version: Nightly 200829 06:05 (Build #2015760755)
AC: 57.0.20200827190112, 91f7bcbca
GV: 82.0a1-20200827093043
AS: 61.0.13

**Comment by hwinnemoe** [comment] 2020-08-29 19:55
I think this may be related to #13228

**Comment by miDeb** [comment] 2020-08-29 20:03
So I bisected this and it's a regression of https://github.com/mozilla-mobile/fenix/pull/13481.

**Comment by cadeyrn** [comment] 2020-08-29 21:10
R.drawable.ic_pbm_notification was removed and replaced by R.drawable.ic_private_browsing. The problem is the fillColor of the drawable: it's used to be @android:color/white, the now used ressource has ?attr/primaryText has fillColor. Changing this to @android:color/white fixes the issue but since it's also used in other places it's not the solution. The easiest way would be to restore R.drawable.ic_pbm_notification but maybe there is a more elegant solution since the fillColor is the only difference between these two drawables. @NotWoods?

**Comment by ebalazs-sv** [comment] 2020-08-31 08:21
This is also reproducible on Nightly 200831 with Pixel 2 (Android 9).

**Comment by NotWoods** [comment] 2020-08-31 17:48
Android should process non-white fills. I think the issue is that it's not loading any color from the attribute.

**Comment by miladmaz12** [comment] 2020-09-03 14:43
This is also reproducible in the latest beta update.

**Comment by sflorean** [comment] 2020-09-11 09:07
Verified as fixed on Nightly 9/11 and 81.1.1-beta.3 with Samsung Galaxy Note 10 (Android 10) and Google Pixel 3 (Android 11).

**Closed by sflorean** 2020-09-11 09:07 UTC
Labels: Feature:Notifications, Feature:PrivateBrowsing, S2, eng:qa:needed, needs:triage, 🐞 bug
