### ISSUE TITLE
[Bug] Scrolling up causes 2 pixel gap above position:fixed element

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#17331] opened 2021-01-06 11:51 UTC
## Steps to reproduce

1. Go to any issue on github, example: https://github.com/mozilla-mobile/fenix/issues/17272
2. Scroll down
3. Scroll up

reddit.com also displays this problem.

### Expected behavior
Position fixed element should not move at all when scrolling up/down on website

### Actual behavior
There is a white 2 pixel gap above the element.
If you install dark reader extension, the problem is more visible. Now there is a transparent 2 pixel gap above the element.
When you scroll up, you can see the text/images that are under this element.
See video for better explanation:
[Problem](https://www.dropbox.com/s/6trws5oine04w28/2021_01_06_12_29_52.mp4?dl=0)

### Device information

* Android device: Samsung Galaxy J7 2017, Motorola Moto G8 Plus
* Fenix version: 84.1.2 and today's (06.01.2021) nightly

**Comment by Mikaka27** [comment] 2021-01-08 20:10
Hi, the issue no longer reproduces on firefox 84.1.4

**Comment by Mikaka27** [comment] 2021-01-08 20:19
Sorry my mistake, the issue still reproduces but only when I enable dynamic address bar. If I have address bar that does not hide when I scroll down the issue doesn't exist.

**Comment by s-ankur** [comment] 2021-01-09 05:55
Duplicate of https://github.com/mozilla-mobile/fenix/issues/10598?

**Comment by Mugurell** [comment] 2021-02-03 19:58
> Sorry my mistake, the issue still reproduces but only when I enable dynamic address bar. If I have address bar that does not hide when I scroll down the issue doesn't exist.

That's a very good observation!

Seems indeed to be the same issue as #10598. Closing as such.
Let's move the discussion to the other ticket which has more traction.

**Closed** 2021-02-04 00:05 UTC
Labels: S4, 🐞 bug
