### ISSUE TITLE
[Bug] [L10N] Privacy notice is not translated in Korean

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#4216] opened 2019-07-22 12:31 UTC
## Steps to reproduce
1. Set your device's language to Korean.
2. Go to Settings - Privacy notice and observe the text.
3. Tap on it and observe the Privacy notice page.

### Expected behavior
Both option and page should be translated.

### Actual behavior
The option from Settings and the Privacy notice page are not translated.

### Note
In Japanese, only the option Privacy notice from Settings is not translated, the actual page is.

### Device information
* Android device: Xiaomi MiPad2 (Android 5.1) - x86 architecture
* Fenix version: RC v1.1.0-rc.1 

![korean](https://user-images.githubusercontent.com/40694158/61632335-4a68d680-ac95-11e9-882c-2ae90061f9e6.png)
![korean1](https://user-images.githubusercontent.com/40694158/61632336-4a68d680-ac95-11e9-9d65-c79f94f2ff62.png)

**Comment by sblatz** [comment] 2019-07-22 20:27
Don't we depend on contributors for these translations? It's probably just not been picked up yet. 

@Delphine can you provide confirmation?

**Comment by Delphine** [comment] 2019-07-23 10:31
Thanks for flagging. Handing over to my team mate @peiying2 since I'm in charge of mobile l10n, and the Privacy notice page lives here: https://github.com/mozilla/legal-docs/tree/master/firefox_privacy_notice

**Comment by peiying2** [comment] 2019-07-23 19:37
@sblatz it is true that this document is not localized in Korean. In fact, the document is not localized in most of the languages that Firefox desktop and mobile support. The current policy is to support top 12 (desktop) locales by default. For this doc, the rest of the locales are on an older version and are redirecting users to the English version. 
For Mobile products, so far we localize a few locales based on markets (e.g. Firefox Lite). If Korean must be added to the Fx PN, per requirement, I will discuss this with Legal counsel. Please advise.

**Comment by sblatz** [comment] 2019-07-23 19:55
Thanks @peiying2 for the info :) will discuss with product!

**Comment by peiying2** [comment] 2019-07-23 19:57
> Thanks @peiying2 for the info :) will discuss with product!

The decision by legal to support top 12 is purely a budget issue. If Korean must be added, is this the only language?

**Comment by kbrosnan** [comment] 2019-07-26 00:45
This appears to be expected behavior. Should we close this?

**Comment by sblatz** [comment] 2019-07-26 16:39
Agreed. Please open a ticket if we want Korean to be a "must"

**Closed by sblatz** 2019-07-26 16:39 UTC
Labels: needs:group-triage, 🌐 L10N, 🐞 bug
