### ISSUE TITLE
FNX-4947 ⁃ [Bug] Can't reuse suggested links from opened tabs after a clear history

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1308] opened 2019-04-01 15:19 UTC
## Steps to reproduce
1. Open a few webpages, i.e. go to amazon and open a few product pages in different tabs, to have distinctive urls.
1. Go to Library and delete all history.
1. Tap the search bar on the homescreen and type the beginning of one of the urls from step 1 (i.e. amaz...). 
1. Tap one of the suggested pages, which are already opened in the current session.
    1. Expected behavior
The selected URL is loading.
    1. Actual behavior
Nothing happens.
    1. Device information

* Android device: Nexus 5 (Android 6), Note 8 (Android 9)
* Fenix version: 4/1 build

**Comment by vesta0** [comment] 2019-04-02 17:08
I can't reproduce this on pixel 3.

**Comment by sv-ohorvath** [comment] 2019-04-03 14:50
Here's a gif with the issue:
![20190403_174841](https://user-images.githubusercontent.com/4037709/55488505-e4e6d080-5638-11e9-930c-08a03a9f8cbb.gif)

**Comment by ekager** [comment] 2019-07-15 16:14
I believe this bug is the awesomebar showing your current session as a suggestion and will be addressed in #3695

**Closed** 2020-08-11 08:46 UTC
Labels: Feature:History, Feature:Search, P1, 🐞 bug
