### ISSUE TITLE
FNX3-16801 ⁃ [Bug] Hide snackbar when the user navigates away from that page/menu/screen

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3122] opened 2019-06-04 13:05 UTC
## Steps to reproduce
1. Bookmark a webpage. Tap the tabs button to see the homescreen.
or. 
1. On an opened tab, add it to a collection. Tap the tabs button to see the homescreen.
or
1. On the homescreen, add tabs to a collection. Tap a tab to open it.

### Expected behavior
The snackbars from saving a bookmark/ a collection, are hidden if the current view is changed.

### Actual behavior
The snackbars take too long to disappear and get displayed on the next screen.

### Device information
* Android device: Pixel (Android 9)
* Fenix version: 6/4

**Comment by lime124** [comment] 2019-07-25 03:40
just with some testing in the gmail app the expected behaviour seems to be a normal convention that we are not adhering to. i'm not sure if the best next step is to ping qa or a dev to double check that is where the issue lays. @boek ?

removing need ux label. if this is still an issue after that investigation please reach out again and we can take a look. thanks!

**Comment by olsenme** [comment] 2019-10-03 22:31
Does this still need worked on?

**Comment by Mugurell** [comment] 2019-10-18 14:23
Currently only the first scenario is still reproducing, in the other two cases the Snackbar being effectively hidden whenever the user navigates to a different screen.

To showcase the solution here is a video for a "Bookmark saved!" Snackbar that would otherwise be shown indefinitely on the screen. The fix included in the patch is shown to effectively hide the Snackbar whenever the user navigates to another screen - https://drive.google.com/file/d/19x_6OyvIzr-O2fM9idV6FXXT41S_WGF_/

**Comment by Mugurell** [comment] 2020-08-12 07:19
Closing as per https://github.com/mozilla-mobile/fenix/issues/3122#event-2725916752

**Closed by Mugurell** 2020-08-12 07:19 UTC
Labels: Feature:Snackbar, Hacktoberfest, P2, S3, help wanted, sourpatch, 🐞 bug
