### ISSUE TITLE
[Bug] Sync Interface Not updating after Login

### ISSUE THREAD

**Issue by jdragojevic** [mozilla-mobile/fenix#2714] opened 2019-05-22 00:33 UTC
## Steps to reproduce
Sign into your Firefox Account (either with user/pass or pairing)

Once complete, visit settings page

### Expected behavior
Signed in account name is displayed and I can see my account settings

### Actual behavior
Sign in button is still displayed.
I have to wait a bit, then re-visit the account page until I see my account

### Device information
* Android device: 
Samsung Tab S4

Also reported in mailing list thread by a number of users.
https://groups.google.com/forum/#!searchin/fenix-nightly/Sync$20Interface$20Not$20updating$20after$20Login%7Csort:date/fenix-nightly/H9kTciTLoBk/OPJvCYzNAgAJ

* Fenix version: 
nightly 2019-05-21

**Comment by grigoryk** [comment] 2019-05-23 02:19
Looking around the codebase, it seems that Fenix grew its own account caching layer. This is the first place to look for what's causing this. Most likely it's not updating the cache when it should be.

**Comment by ekager** [comment] 2019-05-23 22:59
Dupe of #2739 and seems to be fixed by PR #2791 just tested it on my device

**Closed** 2020-08-26 06:13 UTC
Labels: Release Blocker, 🐞 bug
