### ISSUE TITLE
[Bug]: The sumo article for the default browser banner is opened in background on Android 5 & 6

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#25247] opened 2022-05-16 13:07 UTC
### Preconditions:
Make sure Firefox RC 100.2 is not set as the Default browser in Device settings.

### Steps to reproduce
1. Open Fenix with a clean profile.
2. Close/ reopen for 3 times.
3. Tap on the **default browser banner** from homepage.

### Expected behaviour
A SUMO page opens (Android<= 6).

### Actual behaviour
A SUMO page opens (Android<= 6) in background. The homepage is still displayed.

### Device name
Sony Xperia

### Android version

Android 5 and 6

### Firefox release type
Firefox

### Firefox version
RC 100.2, RC 100.1.2

### Additional information
Not reproducible on Beta 101.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20462)

**Comment by plwt** [comment] 2022-05-16 19:19
Hi @sflorean.  What is the page in Kitsune that is opening?  (I might be able to help.)

**Comment by delia-pop** [comment] 2022-05-18 13:33
Hi, @plwt , 
This is the SUMO page opened from the default browser banner on Android 5/6: https://support.mozilla.org/en-US/kb/make-firefox-default-browser-android?as=u&utm_source=inproduct

**Comment by plwt** [comment] 2022-05-18 14:03
Thanks @delia-pop.  That looks like the right page (I was worried it was some other page that was opening).

**Comment by delia-pop** [comment] 2022-06-09 07:46
Tested with Huawei MediaPad M2 (Android 5.1.1) on RC 102.2.0. The issue is no longer occurring in the latest version. The SUMO page is opens correctly, and the banner is no longer displayed after returning to homepage, as expected. I will close this issue.

**Closed by delia-pop** 2022-06-09 07:46 UTC
Labels: 🐞 bug, Feature:HomeScreen, S3, Feature:Browsing, needs:triage
