### ISSUE TITLE
[Bug][a11y] Reader view: very low contrast for links in sepia and light modes

### ISSUE THREAD

**Issue by juliemoynat** [mozilla-mobile/fenix#18190] opened 2021-02-26 11:43 UTC
## Steps to reproduce

1. Go on a web page where you can activate the reader view. This one for example: https://en.wikipedia.org/wiki/Web_Accessibility_Initiative
2. Click on the reader view button in the address bar
3. Go on the appearance menu and activate Sepia then Light mode
4. Contrast for links are too low and I can't read them. (You can test contrasts thanks to a screenshot and then on your computer with [Color Contrast Analyzer](https://www.tpgi.com/color-contrast-checker/).)

### Expected behavior

The contrast ratio between the background colour and links is at least 4.5:1 to be readable and to comply to [the WCAG rule about contrast, level AA](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html).

The problem has been fixed on Firefox desktop. [The bug ticket is here](https://bugzilla.mozilla.org/show_bug.cgi?id=1546213). I think it should (must) be the same in Firefox for Android.

- In dark mode, we have:
    - background colour: #333333
    - 👍 link colour: #45a1ff - Contrast ratio = 4.7:1
    - 👎 visited link colour: rgba(255, 26, 217, 0.3) (= #FF1AD9 on the #333333 background because the alpha doesn't seem to be working… ⚠️ ) - Contrast ratio = 3.9:1 (it's not OK) 
        - _(added on 5th march 2021) [Issue created on Bugzilla and fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1695199) - New colour code: #e675fd = Contrast ratio of 5:1 (OK 👍 )_

    ![Reader view in dark mode in Firefox desktop](https://user-images.githubusercontent.com/6296770/109294193-2a17db00-782d-11eb-8d31-8a3d42f4bdd1.png)

- In light mode, we have:
    - background colour: #FFFFFF
    - 👍 link colour: #0060df - Contrast ratio = 5.6:1
    - 👍 visited link colour: #b5007f - Contrast ratio = 6.4:1

    ![Reader view in light mode in Firefox desktop](https://user-images.githubusercontent.com/6296770/109294197-2ab07180-782d-11eb-824d-d752720df25e.png)

- In sepia mode, we have:
    - background colour: #F4ECD8
    - 👍 link colour: #0060df - Contrast ratio = 4.8:1
    - 👍 visited link colour: #b5007f - Contrast ratio = 5.5:1

    ![Reader view in sepia mode in Firefox desktop](https://user-images.githubusercontent.com/6296770/109294198-2b490800-782d-11eb-91c2-1a67e77e24d5.png)

### Actual behavior

- 👍 In dark mode: contrast ratio between the background and links is 6.3:1 so it's compliant.

    ![Reader view in dark mode in Firefox mobile](https://user-images.githubusercontent.com/6296770/109293050-8f6acc80-782b-11eb-87d1-3e5e6fa77cbb.png)

- 👎 In light mode: contrast ratio between the background and links is 2.5:1 instead of 4.5:1

    ![Reader view in light mode in Firefox mobile](https://user-images.githubusercontent.com/6296770/109293055-90036300-782b-11eb-9968-1e32398fe245.png)

- 👎 In sepia mode: contrast ratio between the background and links is 2.1:1 instead of 4.5:1

    ![Reader view in sepia mode in Firefox mobile](https://user-images.githubusercontent.com/6296770/109293056-909bf980-782b-11eb-9fa2-ec835a4ddf3b.png)

- Moreover, there is no style for visited links in the Firefox mobile reader view but there is one in Firefox desktop.

### Device information

* Device vendor / model and Android version: Nexus 5X, Android 8.1.0
* Firefox for Android version: 86.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9828)

**Comment by julienw** [comment] 2021-02-26 12:44
:wave: I just want to highlight that what has been implemented in Desktop in [bug 1546213](https://bugzilla.mozilla.org/show_bug.cgi?id=1546213) isn't what has been proposed initially, because the suggested change wasn't contrasted enough. So @gijsk made some adjustments while fixing that bug.
I believe that what Julie wrote above is what has been implemented really, @juliemoynat can you please confirm?

**Comment by juliemoynat** [comment] 2021-02-26 12:50
@julienw yes, of course. I got colour hexadecimal codes from the actual version of Firefox Desktop (the fixed one).

**Comment by gijsk** [comment] 2021-02-26 12:53
I filed https://github.com/mozilla-mobile/android-components/issues/9272 for this a while back but haven't had time to address it.

**Comment by juliemoynat** [comment] 2021-03-05 10:23
@gijsk thank you for the link. So, my issue here is a duplication, right? Should I close it?

**Comment by abodea** [comment] 2021-03-08 13:02
Based on the comment above https://github.com/mozilla-mobile/fenix/issues/18190#issuecomment-786630473 I will close this issue.
For more details please check https://github.com/mozilla-mobile/android-components/issues/9272.

**Comment by Alexandru2909** [comment] 2022-06-21 08:16
Since https://github.com/mozilla-mobile/android-components/pull/12334 has been merged, I'll reopen this issue to check if the bug has been solved.

**Comment by SoftVision-LorandJanos** [comment] 2022-06-22 12:57
This issue is no longer reproducible.
Verified on the latest Nightly 103.0a1 (2022-06-22) build.
The contrast is now above 4.5:1 with Sepia activated.
Device used: Google Pixel 4 (Android 12).

![image](https://user-images.githubusercontent.com/48829350/175034523-e1bdfed7-347a-4b5b-ad32-754fc14dab19.png)
Closing the ticket as verified.

**Closed by SoftVision-LorandJanos** 2022-06-22 12:57 UTC
Labels: 🐞 bug, access, eng:qa:needed, Feature:ReaderMode, qa-triaged

**Comment by SoftVision-LorandJanos** [comment] 2022-06-23 12:30
Hi @juliemoynat!
Yes, I've checked the links as well, and no, they are still blue.
And while some of the blue shades, especially towards the edges are not contrasted enough, I found some shades which are:

![image](https://user-images.githubusercontent.com/48829350/175298581-cb429dc4-8c01-47c4-b225-4b9c73b1457b.png)


![Screenshot_20220623-152321](https://user-images.githubusercontent.com/48829350/175298871-2c6fd71f-7aec-4309-a4a0-3ca9eb7a7ca5.png)

**Comment by juliemoynat** [comment] 2022-06-23 17:13
@SoftVision-LorandJanos Thank you so much, that's great! I'm impatient to see this!
