### ISSUE TITLE
[Bug] Crash when selecting almost any text entry fields

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#19520] opened 2021-05-16 11:33 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Select a text entry field, e.g. GitHub issue title, Qwant search box. 
Firefox crashes

Note ,  does not happen with all  text entry fields ,  e.g. Firefox does not crash  when selecting the GitHub issue comment field. 

### Expected behavior
No crash . 

### Actual behavior
Firefox crashes . 

### Device information
Nokia 8 on Android 9.

* Firefox for Android version: ? (go to Settings -> About Firefox)
 Nightly
90.0a1 (Build #2015810571)
AC: 90.0.20210514190120, 33cfc2be8
GV: 90.0a1-20210514094222
AS: 76.0.0

Crash  text :
```
636585f5-8c51-45c6-af27-d9aa3f5606f8
mozilla.appservices.autofill.ErrorException$SqlError: Error executing SQL: no such trigger: credit_cards_tombstones_afterinsert_trigger
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=7a33816376ca47569102dc71566d3f6e
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-98619815-1533-46e2-92e0-13a070210516
----
mozilla.appservices.autofill.ErrorException$SqlError: Error executing SQL: no such trigger: credit_cards_tombstones_afterinsert_trigger
	at mozilla.appservices.autofill.Error.intoException(autofill.kt:14)
	at mozilla.appservices.autofill.Store.<init>(autofill.kt:7)
	at mozilla.components.service.sync.autofill.AutofillStorageConnection.init$service_sync_autofill_release(AutofillCreditCardsAddressesStorage.kt:3)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$conn$2.invoke(AutofillCreditCardsAddressesStorage.kt:1)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.getConn(Unknown Source:2)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.access$getConn$p(AutofillCreditCardsAddressesStorage.kt:1)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$getAllCreditCards$2.invokeSuspend(AutofillCreditCardsAddressesStorage.kt:2)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$getAllCreditCards$2.invoke(AutofillCreditCardsAddressesStorage.kt:2)
	at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
	at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.getAllCreditCards(AutofillCreditCardsAddressesStorage.kt:1)
	at mozilla.components.service.sync.autofill.GeckoCreditCardsAddressesStorageDelegate$onCreditCardsFetch$1.invokeSuspend(GeckoCreditCardsAddressesStorageDelegate.kt:5)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)


```

**Comment by madb1lly** [comment] 2021-05-16 11:36
I now see from the crash  text that the issue seems  to be credit cars autofill, but when i disable  this in secret settings I still get the crashes.

**Comment by anotherus3r** [comment] 2021-05-17 08:23
Same as #19058 maybe?

**Comment by madb1lly** [comment] 2021-05-17 09:45
Hi @anotherus3r,

Perhaps the same cause but not the same exhibited behaviour. I've not found anyone else reporting that the browser crashes on text entry fields, have you?

Cheers 🙂

**Comment by sflorean** [comment] 2021-05-17 10:59
@madb1lly thank you for creating this issue!
 Tested with Samsung Note 10 (Android 11) and I was able to reproduce the issue, following your steps; due to the fact that the crash signature is the same, I will close this as duplicate of #19508 and your scenario will be tested/verified when a fix will be available.

**Closed by sflorean** 2021-05-17 10:59 UTC
Labels: needs:triage, 🐞 bug
