### ISSUE TITLE
[Bug] Audio Stream Stops after display goes to sleep

### ISSUE THREAD

**Issue by meetthemeat** [mozilla-mobile/fenix#15258] opened 2020-09-21 07:09 UTC
## Steps to reproduce
* Open an audio stream like https://www.byte.fm/player/live/
* Play/ Start the stream
* Turn of the display/ let it turn off
* Wait a couple of minutes
* stream stops

### Expected behavior
Playing the audio stream continues in the background also when the device screen turns off.

### Actual behavior
Audio streams stops after a couple of minutes ~10min 

### Device information*  
* Android device: OPO2 ; LinageOS 16 (Android 9)
* Fenix version: 80.1.3

### Additional Information
I testet it with other streams (https://fm4.orf.at/player/live) and the same behavior occured. I tested it also with Chrome :-( and here it worked well but I really don't want change the browser.

**Comment by hwinnemoe** [comment] 2020-09-21 10:10
Duplicate of #9691

**Comment by kbrosnan** [comment] 2020-09-24 07:37
Closing as a duplicate

**Closed by kbrosnan** 2020-09-24 07:37 UTC
Labels: needs:triage, 🐞 bug
