### ISSUE TITLE
Advanced block autoplay settings

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#8017] opened 2020-01-31 10:54 UTC
## User Story
As a user, I want to be able to block Audio only or choose how autoplay is blocked over wifi, so I can control my experience to match my needs. 

## Dependencies

GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1593843#c27

See #255 for original issue

See [mocks](https://app.abstract.com/share/cdba1651-670e-4412-8721-4d70ca025ffd?collectionLayerId=35603d5c-263c-4c70-b3fe-1ae23bd449c8&mode=design&sha=49143c0fafdf6c2d01f7c0b665c92a9fb7c0ebec)

### Acceptance Criteria
-I can choose to only block audio. When I block audio only, only audio is blocked
-I can choose to allow audio and video over wifi only. When I am not on wifi, audio and video are blocked, and when I am on wifi audio and video auto play.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/72918787-1f6e4680-3cfb-11ea-9520-bcdafe562618.png">

**Comment by Baron-Severin** [comment] 2020-03-04 03:09
It looks like newer versions of Android encourage us to check "is this an unmetered connection?" instead of "are we on WIFI?"  @vesta0 should we stick with "allow on WIFI" or change to "allow on unmetered"?

**Comment by vesta0** [comment] 2020-03-10 05:27
Good point @Baron-Severin Let's see what @betsymi thinks!

**Comment by sv-ohorvath** [comment] 2020-03-12 10:39
@vesta0 @Baron-Severin @liuche included this in the 4.1 release notes, but I don't see any changes on Beta 4.1 or Nightly and the PR looks like it's still open. Should there be anything to verify on this issue for now?

**Comment by betsymi** [comment] 2020-03-12 14:19
> @vesta0 @Baron-Severin @liuche included this in the 4.1 release notes, but I don't see any changes on Beta 4.1 or Nightly and the PR looks like is still open. Should there be anything to verify on this issue for now?

Am still working on unpacking this. For a future state, I don't think this is a simple matter of changing the strings we have. May need to make adjustments in the design to provide more clarity for users, particularly regarding `Allow audio and video on Wi-Fi only`. Does this means that audio and video will be blocked on cellular data?

**Comment by liuche** [comment] 2020-03-12 21:34
@sv-ohorvath that was my mistake! I've removed it from the release notes.

**Comment by Baron-Severin** [comment] 2020-03-12 21:41
> Does this means that audio and video will be blocked on cellular data?

@betsymi correct.

@lime124 (sorry I don't know who designed this feature!) we recently discovered that GV always blocks autoplay over cellular data (i.e., the top two radio buttons do the same thing).  The only short term solution I can think of is removing the top button.  If you think it's important, we will have to ask GV to prioritize https://bugzilla.mozilla.org/show_bug.cgi?id=1621825.

<img src="https://user-images.githubusercontent.com/4400286/72918787-1f6e4680-3cfb-11ea-9520-bcdafe562618.png" width=250/>

**Comment by vesta0** [comment] 2020-03-13 15:43
@topotropic  ^^

**Comment by betsymi** [comment] 2020-03-16 23:24
New strings. If option 1 and 2 are the same, we can consolidate to one option. Also, to make all options easier for users to parse, I've adjusted the copy to begin with the same verb. 

**Block audio and video on cellular data only**
Audio and video will play on Wi-Fi

**Block audio only**

**Block audio and video**
Recommended

**Comment by Baron-Severin** [comment] 2020-03-18 21:56
We've had to change these strings a few times, so I've reached out to the localization team on how they want me to handle updating them again.  I should hear back soon, and then I'll merge in these changes.  Thanks everyone!

**Comment by Baron-Severin** [comment] 2020-03-20 21:51
Note to QA: for various reasons, there have been a few changes to the spec:

- There will only be three bullet points for autoplay (the top one was dropped for now)
- Strings should match [this comment](https://github.com/mozilla-mobile/fenix/issues/8017#issuecomment-599802120)
- Because of [this bug](https://github.com/mozilla-mobile/fenix/issues/7507), muted autoplay is not currently working (also true on master)

**Comment by sv-sdeiac** [comment] 2020-03-23 12:49
Hi, I can confirm that this issue is fixed using the latest Firefox Preview Nightly 3/23 #20830607.
Also, thanks @Baron-Severin for your information.


Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Tab S6 (Android 9);
- LG g7 fit (Android 8.1).

Additionally. I tested the "Block audio and video on cellular data only" option and it seems that this option is not working. The autoplay is still playing even when I am on the mobile data. 
@Baron-Severin Can you take a look there and come with more info? I'll remove the qa:needed and wait for your updates, thanks.

**Comment by Baron-Severin** [comment] 2020-03-23 15:51
> Additionally. I tested the "Block audio and video on cellular data only" option and it seems that this option is not working. The autoplay is still playing even when I am on the mobile data.

I'm on PTO this week, @Amejia481 would you mind taking a quick look?  [This](https://bugzilla.mozilla.org/show_bug.cgi?id=1621825) is the BZ ticket, [this is the code](https://searchfox.org/mozilla-central/rev/7d0c94a0e9a9fe1f83553f49b10128567d21709d/dom/html/HTMLMediaElement.cpp#2766) that I thought blocked on cellular data.

The easiest approach here might just be to reenable our wifi logic.  That should be super easy.  Search in the project for `1621825` and you'll find comments about how to hook it back up.

**Comment by Amejia481** [comment] 2020-03-23 16:20
No problem I can take a look!

**Comment by sv-ohorvath** [comment] 2020-03-24 14:37
@liuche FYI, this has landed on Beta with a defect, see https://github.com/mozilla-mobile/fenix/issues/8017#issuecomment-602569535.

**Comment by Amejia481** [comment] 2020-03-24 18:27
> Hi, I can confirm that this issue is fixed using the latest Firefox Preview Nightly 3/23 #20830607.
> Also, thanks @Baron-Severin for your information.
> 
> Devices:
> 
>     * Google Pixel 3 (Android 10);
> 
>     * Samsung Galaxy Tab S6 (Android 9);
> 
>     * LG g7 fit (Android 8.1).
> 
> 
> Additionally. I tested the "Block audio and video on cellular data only" option and it seems that this option is not working. The autoplay is still playing even when I am on the mobile data.
> @Baron-Severin Can you take a look there and come with more info? I'll remove the qa:needed and wait for your updates, thanks.

This pr https://github.com/mozilla-mobile/fenix/pull/9372  should fix the issue.

**Comment by sv-sdeiac** [comment] 2020-03-30 12:20
Hi, I can confirm that the issue found previously is now fixed using the latest version of Firefox Preview Nightly 3/29 #20891805.

Device: Huawei P40 lite (Android 9).

**Closed by sv-sdeiac** 2020-03-30 12:20 UTC
Labels: Feature:Battery, Feature:Media, Feature:SitePermissions, eng:qa:needed, 🐞 bug
