### ISSUE TITLE
FNX-14568 ⁃ [Bug] Crash when using the Tab Tray to switch from normal to private browsing (java.lang.IllegalStateException: swipeRefresh must not be null)

### ISSUE THREAD

**Issue by rafalopilowski1** [mozilla-mobile/fenix#13388] opened 2020-08-07 08:48 UTC
## Steps to reproduce
   0. Have secret option "Wait Until First Paint To Show Page Content" enabled.
   1. Open up one website
   2. Open in the background a private tab from link in already opened tab.
   3. Use toolbar to swipe the tabs (as there's only one tab, only swipe overflow is shown)
   4. Use Tab Tray to switch from normal to private browsing.
   5. Open up the tab from 2nd point.
### Expected behavior
Private tab loads properly.
### Actual behavior

Kotlin crash: `java.lang.IllegalStateException: swipeRefresh must not be null` ([Socorro](https://crash-stats.mozilla.org/report/index/defb9425-98fd-4087-9d81-da5ba0200807))
[Screencast](https://streamable.com/0lusbw)
### Device information

* Android device: OnePlus 6 (Android 10)
* Fenix version: 
   ```
   Nightly 200806 06:02 (Build #22190614)
   AC: 53.0.20200804130112, 789a73eb2
   GV: 81.0a1-20200803094100
   AS: 61.0.10
   ```

**Comment by mcarare** [comment] 2020-08-17 12:50
Can QA please try to reproduce this? I could not, on several devices, including one with Android 10.
@rafalopilowski1 Is this still reproducible for you in the latest Nightly? Thank you!

**Comment by codrut-topliceanu** [comment] 2020-08-17 13:13
I haven't been able to reproduce this either. (Pixel 3 xl, Android 10)

**Comment by rafalopilowski1** [comment] 2020-08-17 15:03
@mcarare Yes, I can still reproduce this issue on my OnePlus 6 (Android 10) 


> Nightly 200817 06:01 (Build #2015758451)
> AC: 54.0.20200813130057, 78b1263b6
> GV: 81.0a1-20200812034418
> AS: 61.0.10

### Log from Firefox Nightly:

e029155b-c737-4d5f-b45e-50b7fc8cb182
`java.lang.IllegalStateException: swipeRefresh must not be null`
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=9db8f43eeff241d886e2f9ea6469b1f0
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-722111d1-1ea3-4fd8-af18-843740200817
----
```
java.lang.IllegalStateException: swipeRefresh must not be null
	at kotlin.jvm.internal.ArrayIteratorKt.checkExpressionValueIsNotNull(ArrayIterator.kt:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$19$2.emit(Collect.kt:4)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:7)
	at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$19$1$1.emit(Collect.kt:5)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:11)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by abodea** [comment] 2020-08-19 14:11
Hi, @rafalopilowski1 I was not able to reproduce this issue on the latest **Nightly** from **8/19** with the following devices: **Google Pixel 4 XL (11), Samsung Galaxy S10+ (10), OnePlus 6T (9).**
Please note that I tried exactly with your website used in the video, I also installed the `DarkReader` as I saw it there but I couldn't reproduce this issue.
Can you try to reproduce it on the latest Nightly build? Or is there anything extra you have installed/did when you reproduced it?
I will leave the `eng:qa:needed` label and based on the response I will modify it accordingly.

**Comment by rafalopilowski1** [comment] 2020-08-19 15:55
@abodea I've also enabled "New Search Experience" and "Wait Until First Paint To Show Page Content" on Secret Settings. Nova Launcher installed; Developer options disabled; working on OxygenOS 10.3.5

After updating Firefox Nightly, STR have changed:
1. Open up one website
2. Open in the background a private tab from link in parent tab.
3. Use Tab Tray to switch from normal to private browsing.
4. Open up the child tab.
5. Close it _before first paint_  of the website. (before title of the website loads up on the Tab Tray; throttling network speed is very helpful at that)
```
Nightly 200819 06:01 (Build #2015758835)
AC: 54.0.20200818130156, 70fc79507
GV: 81.0a1-20200814094524
AS: 61.0.10
```
I've also decided to test it on wider spectrum of websites:

🔏 - private tab

### ❌ Crash:

Parent tab  | 🔏 Child tab
---|---
[https://www.onet.pl/](https://www.onet.pl/)  | [https://podroze.onet.pl/koronawirus-tunezja-czy-wakacje-za-granica-z-biurem-podrozy-sa-bezpieczne/bbl8vyn](https://podroze.onet.pl/koronawirus-tunezja-czy-wakacje-za-granica-z-biurem-podrozy-sa-bezpieczne/bbl8vyn)
[https://www.wp.pl/](https://www.wp.pl/)  | [https://wiadomosci.wp.pl/koronawirus-w-polsce-dr-pawel-grzesiowski-epidemia-wcale-nie-slabnie-6544708010785408a](https://wiadomosci.wp.pl/koronawirus-w-polsce-dr-pawel-grzesiowski-epidemia-wcale-nie-slabnie-6544708010785408a)
 [https://www.polsatnews.pl/](https://www.polsatnews.pl/) |  [https://www.youtube.com/channel/UCb7O4-iI4pEO5UZPlOBr0Ug](https://www.youtube.com/channel/UCb7O4-iI4pEO5UZPlOBr0Ug)
[https://medium.com/](https://medium.com/)  | [https://play.google.com/store/apps/details?id=com.medium.reader](https://play.google.com/store/apps/details?id=com.medium.reader)
[https://tvn24.pl/](https://tvn24.pl/) |  [https://tvn24.pl/polska/pensje-nauczycieli-po-podwyzkach-przerazajace-zwiazkowcy-groza-rzadowi-radykalnymi-metodami-4669306](https://tvn24.pl/polska/pensje-nauczycieli-po-podwyzkach-przerazajace-zwiazkowcy-groza-rzadowi-radykalnymi-metodami-4669306)
[https://www.euronews.com/](https://www.euronews.com/) |  [https://flights.euronews.com/en-GB/flights](https://flights.euronews.com/en-GB/flights)
[https://edition.cnn.com/](https://edition.cnn.com/) | [https://edition.cnn.com/2020/08/19/politics/dnc-roll-call-usa-national-unity/index.html](https://edition.cnn.com/2020/08/19/politics/dnc-roll-call-usa-national-unity/index.html)
[https://www.bbc.com/news](https://www.bbc.com/news) | [https://www.bbc.com/news/election-us-2020-53830373](https://www.bbc.com/news/election-us-2020-53830373) 
 
All tests were handled on **OnePlus 6 (Android 10)**. I've also reproduced this issue on **Xiaomi Mi A2 Lite (Android 10)** using Firefox Nightly from August 18th, 2020 following same STR.

**Comment by rafalopilowski1** [comment] 2020-08-19 16:13
I've also used Android's native crash reporting and sended a bug report to [Google Play Console](https://play.google.com/apps/publish/).

**Comment by miDeb** [comment] 2020-08-20 13:19
I think `Wait Until First Paint To Show Page Content` is the cause of this. Disabling it fixed this crash for me. Note that I used a different STR:
- Have a normal and a private tab open
- Open the tab tray from a private tab
- Close a normal tab
- undo 
- try to switch to the normal tab
I'm on the latest nightly.

**Comment by rafalopilowski1** [comment] 2020-08-20 13:55
> I think `Wait Until First Paint To Show Page Content` is the cause of this. Disabling it fixed this crash for me.

I confirm that this solves the issue. I'll edit this comment later to include screencasts when I'll have access to WiFi.

**Comment by rafalopilowski1** [comment] 2020-08-20 14:14
@abodea Should I edit issue's title and main comment to better reflect cause of the issue?

**Comment by B0pol** [comment] 2020-08-25 19:37
I come from "duplicate" #14084, which doesn't have the same steps at all but does have the same stack trace; after Nightly 200825 update

**Comment by Diana-Rus** [comment] 2020-08-31 09:25
Hello, issue is  fixed on Nightly 8/31
- Samsung Galaxy S9 (Android 8)
- Google Pixel 3XL (Android 9)

<details closed><summary>Note:</summary>

Reproduced issue with the STR from [comment](https://github.com/mozilla-mobile/fenix/issues/13388#issuecomment-677659894) on Nightly 8/21 with Samsung Galaxy S9 (Android 8) and Google Pixel 3XL (Android 9)
Samsung Crash link: https://crash-stats.mozilla.org/report/index/a11d0713-53ad-4a85-b1ee-8cc930200831
Pixel Crash link: https://crash-stats.mozilla.org/report/index/5d86fb3d-0a95-40e3-b84e-a22a10200831
</details>

**Closed by Diana-Rus** 2020-08-31 09:25 UTC
Labels: Feature:Gesture, b:crash, eng:qa:needed, hershey, 🐞 bug
