### ISSUE TITLE
FNX-5375 ⁃ [Bug] No notification when closing a tab

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1979] opened 2019-04-24 15:11 UTC
## Steps to reproduce
1. Open a tab.
1. Tap on the back or tab counter button.
1. For the opened tab, tap the x button.

### Expected behavior
A notification is displayed with an undo option to restore the tab.

### Actual behavior
The tab just closes.

### Device information
* Android device: 
  * Nexus 5 (Android 6.0.1)
  * HTC 10 (Android 8)
  * Google Pixel (Android 9)
* Preview version: 1.0.1917 (#11141216)
![gif](https://user-images.githubusercontent.com/17178945/56670913-5bb53d80-66bc-11e9-8694-bd44e5b52ce4.gif)

**Comment by kbrosnan** [comment] 2019-04-27 00:42
Dupe of #1694

**Closed** 2020-08-11 13:30 UTC
Labels: Feature:Tabs, 🐞 bug
