### ISSUE TITLE
[Bug] Private browsing search suggestions CFR and new search experience overlap

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#14901] opened 2020-09-09 18:32 UTC
## Steps to reproduce
* From a fresh profile
* Open a new private tab
* Type a few characters into the search

### Expected behavior
* information is readable

### Actual behavior
* information is displayed on top of each other

![Screenshot_20200909-095123](https://user-images.githubusercontent.com/250273/92638963-01585500-f290-11ea-8f8a-db6455cf1e68.png)

### Device information

* Android device: Pixel 2 XL
* Fenix version: Nightly Sep-09 82.0a1

**Comment by ekager** [comment] 2020-09-09 18:41
Dupe of https://github.com/mozilla-mobile/fenix/issues/14283

**Closed by ekager** 2020-09-09 18:41 UTC
Labels: Feature:Onboarding, Feature:PrivateBrowsing, Feature:Search, 🐞 bug
