### ISSUE TITLE
Fennec 85.1 doesn't show lical *.html-files

### ISSUE THREAD

**Issue by Buntbart** [mozilla-mobile/fenix#17699] opened 2021-01-29 18:12 UTC
Fennec 85.1 from F-Droid
LineageOS 14.1 (Android 7.1.2)
LineageOS 17.1 (Android 10)

Local *.html-files are not shown anymore via URL like file:///storage/emulated/0/foo.html

No error message, just an empty page is shown instead on both devices.

**Comment by cadeyrn** [comment] 2021-01-29 20:08
Duplicate of #7546.

**Comment by Buntbart** [comment] 2021-01-29 20:25
No, different issue. This one occured first with 85.1.
I now went back to 84.1.4 from F-Droid, where the URL-scheme file:///storage/emulated/0/ still works.

**Comment by Mugurell** [comment] 2021-02-01 06:33
This could be reconsidered in the future but for now Fenix will not support loading `file://` anymore.
Closing in favor of https://github.com/mozilla-mobile/fenix/issues/7546

**Closed by Mugurell** 2021-02-01 06:33 UTC
Labels: needs:triage

**Comment by Buntbart** [comment] 2021-02-01 07:48
That's quite poor.
