### ISSUE TITLE
Resizing the browser in split screen stops Youtube playback

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#905] opened 2019-03-08 04:49 UTC
## Steps to reproduce
* Using a device that supports split screen
* Open Fenix and put the phone in split screen mode by long pressing the app switch button
* Put another app in the other screen
* Open Youtube and start a video
* Tap and drag on the split screen to resize the window

### Expected behavior
* Video continues to play

### Actual behavior
* Video stops playing

* Chrome, Firefox for Android and Reference Browser all continue playback
* Vimeo continues to play back in Fenix

### Device information

* Android device: Galaxy Note 9
* Fenix version: March 7

**Comment by ekager** [comment] 2019-07-12 21:28
@kbrosnan I can't reproduce this anymore. Can you?

**Comment by NotWoods** [comment] 2019-09-25 02:11
@kbrosnan can you check if this still happens? If not we can close the issue.

**Comment by ekager** [comment] 2020-04-11 00:33
Can't reproduce on my Pixel 3. Let's verify with QA and close if we can't reproduce. Thanks!

**Comment by AndiAJ** [comment] 2020-04-13 07:02
Hi, **verified as fixed** on my Nightly debug **`Build #21040820 39.0.20200410130104, 464e3038d
GV: 77.0a1-20200409095500 AS: 0.55.0 from Monday 4/13`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• Samsung Galaxy S7 (Android 7)

► Video
![20200413-095335](https://user-images.githubusercontent.com/51314259/79099931-e4196c00-7d6d-11ea-89a1-baa38cfa90a9.gif)

**Closed by AndiAJ** 2020-04-13 07:02 UTC
Labels: Feature:AndroidIntegration, Feature:Media, P2, eng:qa:needed, 🐞 bug
