### ISSUE TITLE
[Bug] Address bar and keyboard overlap

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#18567] opened 2021-03-20 14:43 UTC
## Steps to reproduce
open a tab and click the url bar

### Expected behavior
![Screenshot_20210320-164004_Firefox_Beta](https://user-images.githubusercontent.com/922368/111873834-f5fe8880-899a-11eb-8e9b-57b492057a7b.png)
no overlap between url bar and hacker keyboard, like in beta

### Actual behavior
![Screenshot_20210320-063408_Firefox_Nightly](https://user-images.githubusercontent.com/922368/111873903-58578900-899b-11eb-99b2-06a54a1f3960.png)

there is some overlap

### Device information

* Device vendor / model and Android version: OnePlus 5t LineageOS 17.1 based on android 10
* Firefox for Android version: ? Nightly. This is a regression.

**Comment by hakkikaancaliskan** [comment] 2021-03-20 15:59
Duplicate of #18546

**Comment by Mugurell** [comment] 2021-03-22 06:35
Thank you Andrei for the details here!
Will close this as a duplicate but this scenario should definitely be tested to be fixed by #18546 .

**Closed by Mugurell** 2021-03-22 06:35 UTC
Labels: needs:triage, 🐞 bug
