### ISSUE TITLE
[Bug] Cross-out shield not displayed when ETP is OFF for a page

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#5447] opened 2019-09-20 08:55 UTC
## Steps to reproduce
1. Open a page.
2. Tap on the tracking protection shield from the left low corner.
3. Turn OFF the enhanced tracking protection.
4. Tap outside the sub-menu and observe the navigation bar.

### Expected behavior
A cross-out shield should be displayed, meaning the page has tracking protection OFF.

### Actual behavior
There is no shield displayed. 
If the user wants to enable enhanced tracking protection again, has to go to Settings - Enhanced Tracking Protection - Exceptions and delete the page from the exceptions.

### Device information
* Android device: all
* Fenix version: Nightly build 190919

![20190920_Trim](https://user-images.githubusercontent.com/40694158/65313310-d4052980-db9c-11e9-8785-8f992238f3e4.gif)

**Comment by nahuhh** [comment] 2019-09-20 10:37
Dupe of #5446

**Closed** 2019-09-20 11:39 UTC
Labels: Feature:TrackingProtection, S2, 🐞 bug
