### ISSUE TITLE
[UX feedback] Navigating between top sites needs too many taps

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#14809] opened 2020-09-07 09:31 UTC
Hi Fenix team,

Top sites should be easy to access and easy to navigate between. A typical workflow is to look at one top site, go to another, and another etc. until all activities are complete. The ideal situation (and as it was in Fennec) is:

1. Go to first top site
2. Complete activity here
3. Tap address bar to bring up top sites list
4. Select next top site
5. Repeat steps 1 to 3 until all top sites visited
6. Close tab, because only one tab was needed for all these activities

Unfortunately at the moment the (quickest I can determine) workflow is the following:
1. Go to first top site
2. Complete activity here
3. Long tap tabs tray icon
4. Tap new tab
5. Tap by back to remove search screen
6. Select next top site
7. Repeat steps 1 to 5 until all top sites visited
8. Close several tabs, one per top site visited, because each top site opens in a new tab.

I think this means twice as many taps per top site.

There are two underlying issues here:
1. There's no option to navigate an existing tab to a top site, bookmark, collection or history item in the current tab, they all require a new tab
2. There's no quick way to access the home screen, minimum 3 taps are needed from any current tab as far as I can tell.

Cheers 🙂

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6495)

**Comment by ale82to** [comment] 2020-09-19 03:18
any news on this? 
fenix general ui is really bad

**Comment by ohhai** [comment] 2021-01-11 16:18
It's also a question for me why two taps are now necessary to open top site. Before Fenix update one tap was enough.

Related to this ticket, I think:  #15866,  #14528,  #13998

**Comment by ohhai** [comment] 2021-02-04 00:43
OK, for latest v85.1.1 only one tap on pinned site is necessary to load it.
Still remains:
- focus on address bar does not show top sites list; only a blank field (at the place of page's content) is shown instead
- that blank field has no any actions - even return back to the loaded page requires tapping "back" button

**Comment by madb1lly** [comment] 2021-02-04 09:49
Hi @ohhai,

I'm on Fenix Nightly, Gecko 87, and as far as I can tell what I describe in the OP is still correct; I can't find any way to reduce the number of taps needed. 

Can you give a step by step explanation o f how you reduced the number of taps please?

Cheers 🙂

**Comment by ohhai** [comment] 2021-02-05 02:14
Seems like I have only one improvement caused by app update, not my actions (I did nothing specific). Previously it required two taps on a pinned site to load it (after you opened a new tab). Now it requires one tap there.

**Comment by madb1lly** [comment] 2021-02-06 20:20
Hi @ohhai,
Odd, I've got latest Nightly installed AFAIK and this is how I load a Top Site:

1. Tap new tab
2. Tap back to remove search screen
3. Select next top site

Cheers :)

**Comment by ohhai** [comment] 2021-02-06 23:15
>     1. Tap new tab
>     2. Tap back to remove search screen
>     3. Select next top site

Does it work if you skip step #2 (for latest versions)?

**Comment by madb1lly** [comment] 2021-02-08 12:32
Hi @ohhai,

I worked it out - there is now a toggle in settings to "Show search engines". I had this enabled, but if I disable it then I can get to top sites with one less tap! The setting has been there for ages, I just misunderstood it.

Cheers 🙂

**Comment by madb1lly** [comment] 2021-08-07 20:44
Still an issue. Really this is a regression from Fennec.

**Comment by madb1lly** [comment] 2022-02-04 10:28
Hi all,
I don't know when it happened, but it's now possible to bring up the top sites (Fenix homepage) just by tapping the address bar therefore we are back to where we were with Fennec 🙌
Ticket can now be closed 👍
Cheers 🙂

**Comment by ale82to** [comment] 2022-02-04 16:20
unless you noticed the top sites always open in new tab come on when will this abomination be fixed ?

**Comment by ohhai** [comment] 2022-11-26 11:24
Tapping address bar now shows the list of top sites. So, everything is fixed here?

**Comment by ale82to** [comment] 2022-11-26 17:39
unfortunately nothing is ever fixed since topsites are opened in new tab

**Comment by madb1lly** [comment] 2022-11-27 17:52
This issue is fixed and can be closed. The issue of top sites opening in a new tab rather than the same tab is a different issue.

**Comment by jonalmeida** [comment] 2023-01-27 22:10
Closing per author's last comment.

**Closed by jonalmeida** 2023-01-27 22:10 UTC
Labels: needs:UX-feedback, Feature:Browsing, Feature:Shortcuts
