### ISSUE TITLE
[webcontent] :hover styles (randomly?) applied when scrolling on who.int page

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/fenix#9860] opened 2020-04-10 19:53 UTC
Originally reported @ https://github.com/webcompat/web-bugs/issues/50647

This has nothing to do with TP.

STR:

1. go to https://www.who.int/news-room/q-a-detail/q-a-coronaviruses
2. start scrolling down to see the accordion questions

Expected: nothing, really
Actual: the question items get seemingly random :hover styles triggered - not where your finger was, or where it ended up. It's a bit weird. This is the CSS that's getting applied:

```css
.qa-details__content .sf-accordion__trigger-panel:hover::before {
    height: calc(100% - 10px);
}
.qa-details__content .sf-accordion__trigger-panel::before {
    content: '';
    position: absolute;
    top: 5px;
    left: 0;
    left: 0;
    width: 4px;
    height: 0;
    background-color: #008dc9;
    transition: all 0.3s ease;
}
```

**Comment by emilio** [comment] 2020-04-11 09:38
doesn't happen with the synthMouseMove pref off. I think it was turned on for android a couple months ago by Makoto?

also scroll anchoring fails badly in this page :(

**Comment by emilio** [comment] 2020-04-11 21:39
I have a fix for the scroll anchoring bits in https://bugzilla.mozilla.org/show_bug.cgi?id=1520581, fwiw.

> doesn't happen with the synthMouseMove pref off. I think it was turned on for android a couple months ago by Makoto?

cc @makotokato (who enabled the pref on android in https://bugzilla.mozilla.org/show_bug.cgi?id=1545393)

**Comment by makotokato** [comment] 2020-04-13 07:09
I guess that this may occurs on Windows when using touch.

**Comment by staktrace** [comment] 2020-07-04 17:54
This was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1633451

**Comment by softvision-miralobontiu** [comment] 2020-10-20 13:16
I was not able to reproduce this issue on the 10/20 Nightly build with HTC 10 (Android 8).
I'll close this issue.

**Closed by softvision-miralobontiu** 2020-10-20 13:16 UTC
Labels: b:web-content, needs:gecko, needs:triage
