### ISSUE TITLE
ETP doesn't work on a quick first load on first run

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#7907] opened 2020-01-24 00:18 UTC
Running on clean build on master geckoNightly flavor I can repro this locally. 

For example in `testStrictVisitContentNotification` the ETP onboarding popup does not display. After some debugging I found this is because `session.trackersBlocked.isNotEmpty()` is false when we would go to display it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15354)

**Comment by ekager** [comment] 2020-01-24 00:23
So either: 
 - Our `etp.html` page we use for the test needs updating because we are using new lists in ETP (did we update these?)? 
- Or we're not blocking/recording trackers when we should be. 

@AaronMT , @Amejia481 any initial thoughts here?

**Comment by ekager** [comment] 2020-01-24 00:47
So it looks like if we reload the page, the correct categories are blocked and the onboarding popup displays. So I'm thinking this is likely related to https://github.com/mozilla-mobile/fenix/issues/7636 and the corresponding GV change https://bugzilla.mozilla.org/show_bug.cgi?id=1609701 since we didn't actually land anything to change this in Fenix AFAICT

So @Amejia481 does Fenix need to change anything here?

**Comment by rpappalax** [comment] 2020-01-24 04:32
These are failing consistently on API 28, by the way.  I only saw 1/4 fails on API 25.
[testStrictVisitDisable](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7845989212416703910/executions/bs.7243fde113f25ed1/testcases/1/test-cases)
[testStrictVisitProtectionSheet ](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8505054118531935651/executions/bs.476ff8d427b39e79/test-cases)
[testStrictVisitContentShield](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7791250866132970831/executions/bs.870391815462fabb/test-cases)
[testStrictVisitContentNotification](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7762661492538433107/executions/bs.d5b7caf37b3b00a1/test-cases)


https://github.com/mozilla-mobile/fenix/blame/4a2cb91ad903a68ff4fae3a1cd6f2722647c3e6d/app/src/androidTest/java/org/mozilla/fenix/ui/EnhancedTrackingProtectionTest.kt
@ekager let us know if you'd like us to jump on zoom and help: @AaronMT @KMaragh and myself

**Comment by AaronMT** [comment] 2020-01-24 18:24
I too, see a refresh is required to see the onboarding bubble on the test-page.

**Comment by AaronMT** [comment] 2020-01-24 20:06
If needed, marked as disabled https://github.com/mozilla-mobile/fenix/pull/7921

**Comment by rpappalax** [comment] 2020-01-24 23:21
Thanks guys, since these are now disabled, I'll repurpose this issue to make sure the tests get fixed and re-enabled

**Comment by AaronMT** [comment] 2020-01-29 15:48
Spent a couple hours yesterday investigating this but could not figure out what's going on. I'm leaning on it's either something with the way ETP is interacting with the local test server or a result of the Gecko bug that @ekager mentioned. This worked fine last week. 

For Reference, the test page mirrors the Mozilla dummytracker domains found in https://github.com/englehardt/englehardt.github.io/tree/master/test/trackingprotection/test_pages

In Fenix, you can load https://raw.githack.com/englehardt/englehardt.github.io/master/test/trackingprotection/test_pages/tracking_protection.html and it works fine. When the test loads the local file, ETP does not kick in. When you reload the page in the middle of a test run, ETP kicks in. It would be awesome if someone can debug ETP at that point and check it's state and status on the window.

**Comment by ekager** [comment] 2020-01-30 10:56
@Amejia481 and I investigated this today and discovered some interesting things.
 
1. This behavior can also be observed outside of tests if you have a fresh Fenix install and you launch a custom tab with this link. (https://senglehardt.com/test/trackingprotection/test_pages/tracking_protection.html)
2. The issue is solved by refreshing the page
3. The issue is solved by adding a short delay to loading the page
4. It doesn't happen again if you force close Fenix and reopen the custom tab from 1

It looks like Gecko needs to load some of the tracking lists and this is not happening quickly enough on first load, first run so either they got a bit slower at loading, or we got a bit faster and starting up and are now running into this issue. 

The tests are currently disabled and we think this should only be an issue on the first run of Fenix if you get to the browser too quickly (probably only possible via a custom tab or maybe external intent). 

If you launch the same test with "about:url-classifier" you can also notice that the Google list is not fetched yet on first load which we are not 100% is related, but seems interesting.

Since it's only on first run, first load this seems like a bit of an edge case that we probably don't need to urgently investigate, but looks like the tests were working to catch something at least!

**Comment by Amejia481** [comment] 2020-01-30 15:33
@ehsan do you know at what point the tracking protection list is fetch for the first time?

**Comment by ekager** [comment] 2020-02-05 11:47
I think we can remove this from our prioritized bug backlog

**Comment by eamsen** [comment] 2020-02-05 15:14
TP and Safe Browsing blocklists are initially downloaded during the first GV startup. The initial download and subsequent updates of the blocklists occur on a background thread and don't block GV page load mechanics.
This means that there is a known race between the blocklist downloads and page load on fresh profiles (fresh install or cleaned data). This (among other fresh profile details) can be an issue for tests, but should unlikely cause issues in production.

Please let us know, if that requires further discussion.

**Comment by ekager** [comment] 2020-02-06 15:21
Moving this out of the prioritized bug backlog since it's a known race and shouldn't impact users in the wild

**Comment by Amejia481** [comment] 2020-02-07 20:40
@AaronMT I was taking with @eamsen about this issue and he mentioned that in `GeckoView` they are using some special test trackers that get loaded before Gecko fetches the tracking protection list they are `trackertest.org` and `itisatracker.org` you could give them a try in [etp.html](https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/assets/pages/etp.html) , [here](https://dxr.mozilla.org/mozilla-central/search?q=trackertest.org) you can see some examples where they are being used, hope it helps.

**Comment by sv-ohorvath** [comment] 2020-08-07 08:13
There are still issues in the automation tests with the ETP shield, please see: https://github.com/mozilla-mobile/fenix/issues/12896

**Comment by AndiAJ** [comment] 2021-08-12 06:19
Reproducible on Firefox 92.0.0 Beta 1 using a OnePlus A3 (Android 6.0.1)

**Comment by AndiAJ** [comment] 2022-03-09 11:18
Still reproducible on 99.0.0 Beta 1 using a OnePlus A3 (Android 6.0.1)

**Comment by sv-ohorvath** [comment] 2022-10-07 12:24
We also noticed that by changing from Standard to Custom TP settings on the first run, TP will start working, but not if we change from Standard to Strict...

**Comment by Amejia481** [comment] 2022-10-07 14:18
It looks like it may be an issue with downloading the list, as even when I try to force the download  by going to`about:url-classifier` -> **"provider Mozilla"** -> click the button ->  **"Trigger update"**

Same issue is reproducible in Nightly, Beta, and Release.

![image](https://user-images.githubusercontent.com/773158/194573060-6d6c6b29-eaec-431b-9e1e-1f3375cf2a2f.png)

Nightly
```
107.0a1 (Build #2015908395), 62f5f4491+
AC: 107.0.20221006143319, 0f83570d5b
GV: 107.0a1-20221006093717
AS: 94.2.1
```

**Beta**

```
106.0b5 (Build #2015908379), acdaf02af+
AC: 106.0.4, 36dfe0d2d0
GV: 106.0-20221006191955
AS: 94.2.1
```

**Release**

```
105.2.0 (Build #2015907747), 01fbfd637+
AC: 105.0.8, 658c2d239f
GV: 105.0.2-20221003135607
AS: 94.1.0
```

**Comment by Amejia481** [comment] 2022-10-07 17:03
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1794130 to continue researching on Geckoview what is the root cause.

**Comment by rocketsroger** [comment] 2022-10-12 19:52
Using testing and console debugging, I've narrowed down the issue:

1. Fails to download tracking protection block list on first start.
2. Retry timer set to 20 minutes from first start.
3a. If the user doesn't restart Fenix, when retry timer expires, list will be downloaded. (100% success rate)
3b. If the user restart Fenix (swipe away first), then the list will be downloaded right away.  (100% success rate)

In my opinion this issue is seen because of three reasons:
1. Inconsistent success rate when downloading block list at first start.
2. We don't have a default list built in.
3. Long backoff retry timer when we fails to download at first start.

**Comment by rocketsroger** [comment] 2022-10-19 14:43
From discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1794130 that this can be fixed by:
1. Preload the block list.
2. Configurable backoff/retry timer for Mozilla's block list.

**Comment by rocketsroger** [comment] 2022-10-20 19:29
Closing this issue since this is not a Fenix only issue and is being tracked with https://bugzilla.mozilla.org/show_bug.cgi?id=1794130.

**Closed by rocketsroger** 2022-10-20 19:29 UTC
Labels: 🐞 bug, 🙅 waiting, Feature:TrackingProtection, S3
