### ISSUE TITLE
FNX-5516 ⁃ [Bug] Unable to interact with Twitch due to URL bar

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#2209] opened 2019-05-01 19:15 UTC
* visit http://www.twitch.tv
* tap on any stream
* chat input is hidden under the address bar

This breaks a large part of Twitch community interaction.

05/01, Pixel 2

**Comment by kbrosnan** [comment] 2019-05-01 20:42
Duplicate of #552

**Closed** 2020-08-11 14:16 UTC
Labels: 🐞 bug
