### ISSUE TITLE
[Bug] Most visited sites appear in home screen even if it's turned off from settings > customizations > show most visited sites

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#17708] opened 2021-01-30 12:24 UTC
### Fenix version: 86.0.0-beta.1

Most visited sites seems to be appearing on home screen even if it's disabled from settings > customizations > show most visited sites.

Earlier versions of fenix didn't have this issue.

![Screenshot_20210130-170950_Firefox Beta](https://user-images.githubusercontent.com/51329626/106356237-23fa1180-62f6-11eb-9b2c-2c9c1e263949.jpg)

![Screenshot_20210130-171017_Firefox Beta](https://user-images.githubusercontent.com/51329626/106356254-396f3b80-62f6-11eb-8f4d-afe34c76490b.jpg)

**Comment by hakkikaancaliskan** [comment] 2021-01-30 15:35
Duplicate of #17655

**Comment by Mugurell** [comment] 2021-02-01 06:16
This is resolved in latest Nightly with the Beta following. Closing as such.

**Closed by Mugurell** 2021-02-01 06:16 UTC
Labels: needs:triage, 🐞 bug
