### ISSUE TITLE
FNX-12240 ⁃ [Bug] Can't interact with bottom of site

### ISSUE THREAD

**Issue by johnny88** [mozilla-mobile/fenix#11329] opened 2020-06-08 05:48 UTC
## Steps to reproduce
* Go to https://news.ycombinator.com
* Scroll to the bottom
* Try to click on the search bar

### Expected behavior
Input is focus and keyboard pops up.

### Actual behavior
Nothing

### Device information
* Android device: 
Pixel 4, Android 10 - June 5 2020 security update
* Fenix version: 
Nightly 200606 06:21 (Build #2015744627)

**Comment by Augures01** [comment] 2020-06-08 06:22
Duplicate of #11189 that is fixed in latest Nightly

**Comment by Augures01** [comment] 2020-06-08 06:31
> 
> 
> > Duplicate of #11189 that is fixed in latest Nightly
> 
> When is the latest version releasing? I have 5th June version installed... didn't find any new update in play store. Please help.

I always updates Nightly (same as Preview Nightly from Google Play) from https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly/latest

**Comment by sheikh-azharuddin** [comment] 2020-06-08 06:33
> > > Duplicate of #11189 that is fixed in latest Nightly
> > 
> > 
> > When is the latest version releasing? I have 5th June version installed... didn't find any new update in play store. Please help.
> 
> I always updates Nightly (same as Preview Nightly from Google Play) from https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly/latest

Thanks...but this is the firefox nightly preview for developers....from where I can get firefox nightly for developers versions?

**Comment by Augures01** [comment] 2020-06-08 06:35
> 
> 
> > > > Duplicate of #11189 that is fixed in latest Nightly
> > > 
> > > 
> > > When is the latest version releasing? I have 5th June version installed... didn't find any new update in play store. Please help.
> > 
> > 
> > I always updates Nightly (same as Preview Nightly from Google Play) from https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly/latest
> 
> Thanks...but this is the firefox nightly preview for developers....from where I can get firefox nightly for developers versions?

Here:
https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly/latest

**Comment by sheikh-azharuddin** [comment] 2020-06-08 06:36
> > > > > Duplicate of #11189 that is fixed in latest Nightly
> > > > 
> > > > 
> > > > When is the latest version releasing? I have 5th June version installed... didn't find any new update in play store. Please help.
> > > 
> > > 
> > > I always updates Nightly (same as Preview Nightly from Google Play) from https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly/latest
> > 
> > 
> > Thanks...but this is the firefox nightly preview for developers....from where I can get firefox nightly for developers versions?
> 
> Here:
> https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly/latest

Thanks bro😊👍
I wonder what is the difference between both versions? Or which do you prefer? 😅

**Comment by Augures01** [comment] 2020-06-08 06:38
> 
> 
> > > > > > Duplicate of #11189 that is fixed in latest Nightly
> > > > > 
> > > > > 
> > > > > When is the latest version releasing? I have 5th June version installed... didn't find any new update in play store. Please help.
> > > > 
> > > > 
> > > > I always updates Nightly (same as Preview Nightly from Google Play) from https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly/latest
> > > 
> > > 
> > > Thanks...but this is the firefox nightly preview for developers....from where I can get firefox nightly for developers versions?
> > 
> > 
> > Here:
> > https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly/latest
> 
> Thanks bro😊👍
> I wonder what is the difference between both versions? Or which do you prefer? 😅

Only in package name if I know right 🤔

**Comment by sheikh-azharuddin** [comment] 2020-06-08 06:48
> > > > > > > Duplicate of #11189 that is fixed in latest Nightly
> > > > > > 
> > > > > > 
> > > > > > When is the latest version releasing? I have 5th June version installed... didn't find any new update in play store. Please help.
> > > > > 
> > > > > 
> > > > > I always updates Nightly (same as Preview Nightly from Google Play) from https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly/latest
> > > > 
> > > > 
> > > > Thanks...but this is the firefox nightly preview for developers....from where I can get firefox nightly for developers versions?
> > > 
> > > 
> > > Here:
> > > https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly/latest
> > 
> > 
> > Thanks bro😊👍
> > I wonder what is the difference between both versions? Or which do you prefer? 😅
> 
> Only in package name if I know right 🤔

But again why have 2 apps😅🤣
My youtube issue is atleast fixed now....thanks 😊👍

**Comment by Augures01** [comment] 2020-06-08 06:54
> 
> 
> > > > > > > > Duplicate of #11189 that is fixed in latest Nightly
> > > > > > > 
> > > > > > > 
> > > > > > > When is the latest version releasing? I have 5th June version installed... didn't find any new update in play store. Please help.
> > > > > > 
> > > > > > 
> > > > > > I always updates Nightly (same as Preview Nightly from Google Play) from https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly/latest
> > > > > 
> > > > > 
> > > > > Thanks...but this is the firefox nightly preview for developers....from where I can get firefox nightly for developers versions?
> > > > 
> > > > 
> > > > Here:
> > > > https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly/latest
> > > 
> > > 
> > > Thanks bro😊👍
> > > I wonder what is the difference between both versions? Or which do you prefer? 😅
> > 
> > 
> > Only in package name if I know right 🤔
> 
> But again why have 2 apps😅🤣
> My youtube issue is atleast fixed now....thanks 😊👍

Earlier we have 3 channels of old FF development - Release, Beta, Nightly
Then Fenix development started and we have new "FF Preview Nightly for Developers", but "Release, Beta, Nightly" is for old FF for Android.
Then Nightly and Beta channel is for new FF, but Release is for old FF
Something like that 😂

**Comment by sheikh-azharuddin** [comment] 2020-06-08 10:28
This issue is fixed.. please close it

**Comment by AndiAJ** [comment] 2020-06-19 12:04
Hi, **verified as fixed** on the latest **`Nightly Build #200619 from 6/19`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200619-145913](https://user-images.githubusercontent.com/51314259/85130717-206dba80-b23e-11ea-8f7e-dceb54bbc70d.gif)

**Closed** 2020-08-11 03:49 UTC
Labels: eng:qa:verified, 🐞 bug
