### ISSUE TITLE
FNX-13017 ⁃ Ability to rearrange opened tabs

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12005] opened 2020-06-26 14:31 UTC
I always find myself to manage the opened tabs.

I always open a lot tabs when I read blog or news website, I open a lot of tabs with articles I want to read. In which I read some of the important ones and leave others opened to read them after some time and if I'm able to rearrange them it'll be really useful for me and others who work with a lot of tabs in. And in conjunction with #12001 it'll make it really easier to manage tabs and work with them.

**Comment by Dunexus** [comment] 2020-06-26 14:35
Dupe of https://github.com/mozilla-mobile/fenix/issues/2487

**Comment by SS1113** [comment] 2020-06-26 14:43
Okay @Dunexus, has the other issue #12001 also been asked? I'll close this issue now since its a duplicate.

**Comment by Dunexus** [comment] 2020-06-26 15:33
@SS1113 I don't think https://github.com/mozilla-mobile/fenix/issues/12001 has been asked before. There was a discussion about having the ability to close multiple tabs in https://github.com/mozilla-mobile/fenix/issues/11695 but yours is more specific, having "close other tabs" and "close tabs on the right" as in desktop version if i understand correctly.

**Closed** 2020-08-11 05:26 UTC
Labels: needs:triage
