### ISSUE TITLE
FNX2-15147 ⁃ [Bug] Tab Tray Preview for Reader Mode Pages is a blank rectangle

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12291] opened 2020-07-05 11:28 UTC
## Steps to reproduce
Open a site with reader mode like https://adrienne.be/ferengi_rules_of_acquisition/
Switch to tab tray

### Expected behavior
Thumbnail has the prevuew of the page

### Actual behavior
It is a blank white rectangle

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly 200705 06:01 (Build #21870613)
AC: 49.0.20200702190156, bafa9299b
GV: 80.0a1-20200702094606
AS: 61.0.7

**Comment by mcarare** [comment] 2020-07-06 07:21
Duplicate of https://github.com/mozilla-mobile/fenix/issues/11918.

**Closed** 2020-08-20 22:42 UTC
Labels: needs:triage, 🐞 bug
