### ISSUE TITLE
[Bug]: File type icon in Downloads is the wrong colour (Dark mode)

### ISSUE THREAD

**Issue by cwzilla** [mozilla-mobile/fenix#23308] opened 2022-01-19 21:52 UTC
### Steps to reproduce

1. Change theme to Dark mode
2. Go to Google and search something
2. Tap and hold on any hyperlink
2. Select **Download link**
3. View Downloads

### Expected behaviour

The file type icon should match the other icons on this page.

### Actual behaviour

The file type icon is very dark and is not visible.

![image](https://user-images.githubusercontent.com/87655586/150219809-16c0334e-5e93-4b71-921f-8eb702068558.png)

### Device name

Galaxy A51

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

95.2.0

**Comment by kbrosnan** [comment] 2022-01-20 18:37
I cannot reproduce this on Nightly using a Pixel 2 XL running Android 11 and a Pixel 6 pro on Android 12. Please check with Nightly, https://github.com/mozilla-mobile/fenix/wiki#download

**Comment by LaurentiuApahideanSV** [comment] 2022-02-03 15:51
I managed to reproduce the issue on RC 95.2.0 but not on Nightly 2022-02-03. The issue was probably fixed by https://github.com/mozilla-mobile/fenix/issues/21483. I will close this issue.

**Closed by LaurentiuApahideanSV** 2022-02-03 15:51 UTC
Labels: 🐞 bug, needs:triage
