### ISSUE TITLE
[Bug]: Push notifications broken for "Send Tab to Device" on Android

### ISSUE THREAD

**Issue by derDiesel** [mozilla-mobile/fenix#27686] opened 2022-11-03 12:39 UTC
### Steps to reproduce

1. Use Firefox Sync on 2 devices (PC and Android Mobile)
2. Activate Sync on your Mobile and PC
3. Use your PC and send an open page to your Mobile
4. Your Mobile won't show any push notification (until you start a sync manually)

### Expected behaviour

Push Notification shows up

### Actual behaviour

Push Notification doesn't shows up

### Device name

Google Pixel 7 Pro

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

106.1.0

### Additional information

Android 13, Stable Release, Oct. 2022 Patch Level with Google Play Services 22.43.12 and Google Play System Patch Level Oct. 1st 2022

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21922)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21922

**Comment by AdinaPetridean** [comment] 2022-11-09 13:53
@derDiesel thank you for your report!
I couldn't reproduce your issue on Firefox 106.1.0 and also on Nightly 108.0a1 from 09/11 with Google Pixel 6 (Android 13). The Push Notification shows up.

<img src="https://user-images.githubusercontent.com/108326843/200847835-67e02389-1cd0-47d2-ad30-089a75c9ae2c.JPEG" width="50%" />

**Comment by derDiesel** [comment] 2022-11-09 15:09
Hey Adina =) Did you pushed "Sync now" before? (screen shows 0min ago) This is the only way for me to get it work

Bug still present here with Android Patch Level Nov 2022 and Play Services 22.44.14. Found older ticket for this too; Maybe close mine or merge it. Thx =)

https://github.com/mozilla-mobile/fenix/issues/26866

**Comment by AdinaPetridean** [comment] 2022-11-09 16:05
Hi, @derDiesel 
Further investigation revealed that: 
- on Google Pixel 6 (Android 13) indeed initially I performed a sync on both desktop and mobile before sending the tab, as per your Step 2 "Activate Sync on your Mobile and PC". After testing without manual syncing the devices, the send tab is not received on the mobile device as you reported.
- on Motorola Moto G9 plus - Android 11 I can properly send and receive a tab without forcing a manual sync before / after sending the tab.
However, we will further investigate this behaviour over [26866](https://github.com/mozilla-mobile/fenix/issues/26866) and close this report as duplicate. Thanks for pointing out.

**Closed by AdinaPetridean** 2022-11-09 16:05 UTC
Labels: 🐞 bug, needs:triage, qa-triaged
