### ISSUE TITLE
[Bug] 'Fill link from clipboard' not working when clicking on the address bar in a web page

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#14715] opened 2020-09-04 10:07 UTC
## Steps to reproduce
Copy an URL in the clipboard
Open a web page (leave the Fenix homepage)
Click on the address bar

### Expected behavior
The "'Fill link from clipboard' option should be displayed

### Actual behavior
The "'Fill link from clipboard' option is not displayed (maybe because the address bar is already filled in with the current page URL? actually if you click on the x button to clear the bar, then the clipboard option appears).

### Device information
Redmi Note 7
* Android device: 9 
* Fenix version: #2015761907

**Comment by liuche** [comment] 2020-09-15 23:59
Dupe of #14744

**Closed by liuche** 2020-09-15 23:59 UTC
Labels: needs:triage, 🐞 bug
