### ISSUE TITLE
[UX Feedback] Tab View

### ISSUE THREAD

**Issue by kunoithica** [mozilla-mobile/fenix#11843] opened 2020-06-23 14:02 UTC
Just wanted to say fantastic work on the browser, it's significantly faster on my older device than any others I've tried, and is relatively stable even in it's beta state, more than can be said for some of it's competitors.

That being said, you have asked for user feedback, so here is mine. Would it be possible to move the tab view more toward something like Android Chrome does, and have all the tabs represented by a "stack of cards" each with a still frame of the page as it was when that tab was last active. Swipe up and down to cycle though the stack, flick a "card" left or right to close that tab. Tap a "card" to make it the active tab. When the "tabs" button is tapped, zoom out of the page and add it into the stack of cards. Links opened in one tab spawn new "card" in front of their parent tab. That sort of thing. 

Also, a way to reorder the tabs would be nice, so things that are open all the time, say email or banking pages could be moved to the back of the stack where they are easy to find, and pages that are in active use for only a short while, like news articles could be spawned at the front, and discarded easily.

I appreciate what you are trying to do with the tab list as it currently is, but as someone who frequently has in excess of 10 tabs open, it is simply an impractical way to navigate through them.

Also, in an unrelated point, would it be possible to add the "Swipe Down to Refresh" gesture? I'm fairly certain this would have been brought up before, but I just wanted to add it here.

In any case, great work. What you have built already leaves most of its competitors behind.

**Comment by SS1113** [comment] 2020-06-23 15:40
Pull to refresh was added but has to be to be rolled back due to various issues. Keep an eye on this: https://github.com/mozilla-mobile/fenix/issues/9766

**Comment by kbrosnan** [comment] 2020-08-28 20:21
Closing as a duplicate of 3758/2487

**Closed by kbrosnan** 2020-08-28 20:21 UTC
Labels: Feature:Tabs, needs:triage
