### ISSUE TITLE
[Bug] "Share" menu "Recently Used" is not colored in Dark theme

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#8984] opened 2020-03-05 10:54 UTC
## Steps to reproduce
In Light theme, the "Share" menu "Recently Used" items list has a shaded roundrect
In Dark theme, there is no shading

### Expected 
Dark theme share menu should have a rounded rectangle using the same shade defined in light mode 

### Actual 
No shading around Recently used

* Android device: Galaxy A40
* Fenix version: Android 9.0.0

**Comment by mcarare** [comment] 2020-03-05 13:05
@darkwing This seems to be a regression from https://github.com/mozilla-mobile/fenix/pull/8839 like https://github.com/mozilla-mobile/fenix/issues/8949. Can you please check? TY!

**Comment by darkwing** [comment] 2020-03-16 20:27
Could you post a screenshot?  I'm not understanding what the issue is based on description.

**Comment by Cheap-Skate** [comment] 2020-03-16 21:37
In Light mode there is a gray roundrect to distinguish "recently used" from "all actions". In Dark mode there is no roundrect.

Also, I think that in Dark mode the Android navigation bar changes color (from very dark gray to black) when I move to the Share menu

![Screenshot_20200316-213400_Firefox Nightly](https://user-images.githubusercontent.com/40568887/76801711-174bf800-67ce-11ea-8ce1-b328b15742dc.jpg)
![Screenshot_20200316-213342_Firefox Nightly](https://user-images.githubusercontent.com/40568887/76801726-1adf7f00-67ce-11ea-9ebf-4576050d9922.jpg)

**Comment by eliserichards** [comment] 2021-04-02 22:27
This menu is here: https://github.com/mozilla-mobile/fenix/blob/1f320fd2ad55172a7fa56c52f243a732c585173f/app/src/main/res/layout/share_to_apps.xml#L28

**Comment by ZianeA** [comment] 2021-04-03 10:16
I investigated the problem and it seems to originate from the color resource file. Both inset_dark_theme and above_dark_theme use the same color value, which is not the case for the light versions inset_light_theme and above_light_theme. The solution is to use a slightly lighter color for inset_dark_theme. Let me know the color and I'll fix it.

Dark:
https://github.com/mozilla-mobile/fenix/blob/1f320fd2ad55172a7fa56c52f243a732c585173f/app/src/main/res/values/colors.xml#L93

Light:
https://github.com/mozilla-mobile/fenix/blob/1f320fd2ad55172a7fa56c52f243a732c585173f/app/src/main/res/values/colors.xml#L21

**Comment by eliserichards** [comment] 2021-04-06 14:42
We would like to use #52525E for `inset_dark_theme` (confirmed with @topotropic).

Are you an Outreachy applicant @ZianeA? If so, please feel free to pick this up 👍

**Comment by eliserichards** [comment] 2021-04-06 15:21
No worries! Your input was extremely helpful! Sorry about that 😅

**Comment by neha-b2001** [comment] 2021-04-06 15:40
@eliserichards Could I please work on this issue (I'm an Outreachy applicant)?

**Comment by LaurentiuApahideanSV** [comment] 2021-05-10 09:10
Verified as fixed on Firefox Preview Nightly 90.0a1 (Build #2015809515) 5/10.
###Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)

**Closed** 2021-05-10 15:40 UTC
Labels: Feature:Themes, Outreachy, S2, eng:qa:verified, good first issue, help wanted, 🐞 bug
