### ISSUE TITLE
Search for bookmarks (by tags in particular) in the bookmark list

### ISSUE THREAD

**Issue by lle-git** [mozilla-mobile/fenix#15094] opened 2020-09-14 20:15 UTC
Hello,

To sum up :
	- I'd like to be able to search for bookmarks in the bookmark list of Firefox for Android
	- It would be great if the search could be done by tags

In details : 

When I go to the list of bookmarks on Firefox for Android 80.1.2, my thousands of bookmarks are displayed, but it seems curious to me, that there is no way to search (or filter or sort) a bookmark by title or tag in that huge list. 
At this point I have to … go to back to the awesomescreen to perform a search (by title or url, but there the search by tag is not possible)

Tags are promoted for good reasons in Firefox Desktop and should be promoted (search bookmarks by tags and in the bookmark list, edit tags) in Firefox for Android for those same reasons.
I'm talking about the bookmark list, but the same is true for in the awesomescreen (see https://bugzilla.mozilla.org/show_bug.cgi?id=775672)

Moreover, IMHO inconsistencies described above between Firefox Desktop and Firefox for Android should be avoided from the user experience point of view.

Do you think something could be done on that subject ?

Thanks for all the great work done in the Firefox products.

Regards

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6952)

**Comment by JeePeeNL** [comment] 2020-09-23 18:15
Yes please! Add tag support to the mobile browser, just like how it works on desktop:
https://support.mozilla.org/en-US/kb/categorizing-bookmarks-make-them-easy-to-find

**Comment by Oymate** [comment] 2020-10-08 15:11
So missing thus🔍

**Comment by Poopooracoocoo** [comment] 2020-10-24 06:10
You can also put an asterisk (*) to only search for bookmarks. Plus (+) searches bookmark tags and percent (%) searches tabs. 

it's a shame about bookmark keywords. #12099

**Comment by JeePeeNL** [comment] 2020-10-24 09:25
Not on mobile @Poopooracoocoo 
> 
> You can also put an asterisk (*) to only search for bookmarks. Plus (+) searches bookmark tags and percent (%) searches tabs.
> 
> it's a shame about bookmark keywords. #12099

**Comment by Poopooracoocoo** [comment] 2020-10-24 09:49
@JeePeeNL sorry my wording wasn't right. :) i meant that you can not only search for bookmarks on desktop but there are a bunch of operators for the address bar

**Comment by crisalis2** [comment] 2020-11-10 16:45
Tag search would be optimal, but even the most basic search would be appreciated. Otherwise I can't delete old dead bookmarks that redirect to another page. I will explain it. If I search for a dead bookmark in the address bar, I will find it, but when I tap on it and go the page, it redirects, and then it's obviously not recognized as a bookmark, so I can't delete it there. The only way to delete such dead bookmark is finding it in the list of bookmarks and delete it there, but with a huge collection of bookmarks it's basically impossible to find it unless a search option within the bookmark list is implemented.

**Comment by hebu** [comment] 2021-07-20 20:32
Since Google will shut down its bookmarks service by the end of September 2021, I just exported all my tons of Google Bookmarks, imported them in Firefox on my desktop, re-added all the tags and registered with Firefox Sync, just to find out that Firefox Android is not supporting tags in any way.

Now I am a bit disappointed and desperately searching for some alternative, as I honestly do not expect Fenix to support bookmark tagging by end of September ... any workarounds around?

**Comment by Poopooracoocoo** [comment] 2021-07-21 01:46
wait so firefox still doesn't let you search bookmarks??????? it's _almost_ funny

**Comment by hebu** [comment] 2021-07-21 07:16
Just to keep you up to date: I won't use Firefox Sync, as I finally found raindrop.io as a perfect replacement for Google Bookmarks.

Yes, Fenix won't let you search/filter inside the bookmarks list, but in the address bar. And the bookmarks list appears to be very slow, takes ages to load every time. And there's no single common list used by all devices, it's separated "desktop bookmarks" and "mobile bookmarks". That's not what I was looking for...

**Comment by JeePeeNL** [comment] 2021-07-21 07:19
> 
> 
> wait so firefox still doesn't let you search bookmarks??????? it's _almost_ funny

It does, but not by their tags. They are not synced to Firefox for Android.

**Comment by JeePeeNL** [comment] 2021-07-21 07:42
@hebu 
> 
> Just to keep you up to date: I won't use Firefox Sync, as I finally found raindrop.io as a perfect replacement for Google Bookmarks.
> 

Thanks for the tip, will look into that too. There are a few more: Tagpacker.com, Diigo.com, Pinboard.in, bookmarkninja.com, Yabs.io. You'll find many more if you Google for 'Delicious bookmarking alternative'. I used delicious for years, until they shut down, then I switched to Firefox because it's the only browser that allows you to save bookmarks with tags. It's a real shame they don't sync them to their mobile app.

**Comment by emdash** [comment] 2022-03-05 02:27
It's been a few months. This is affecting me too. How hard would it be to get some kind of bookmark filtering on Android?

**Comment by cadeyrn** [comment] 2022-03-05 11:50
@emdash:

> How hard would it be to get some kind of bookmark filtering on Android?

It's already being worked on: #24104

**Comment by Oymate** [comment] 2022-05-27 13:18
You can search now

**Comment by Poopooracoocoo** [comment] 2022-05-27 13:23
> You can search now

@Oymate does that include tags? Does that include searching via the address bar by using an operator? Or is it just the same as Chromium, for instance?

**Comment by JeePeeNL** [comment] 2022-05-27 15:02
@Oymate @Poopooracoocoo no you still can't search by tags. It only searches in the link title and url because that's the only thig that is being synchronised from the desktop version of Firefox. For some silly reason the tags are not part of the sync.

Here is another entry about this: https://github.com/mozilla-mobile/fenix/issues/5880

**Comment by sflorean** [comment] 2022-06-08 12:24
Closing this as duplicate of #5880. 

Bookmarks search was implemented here #24301 (search engine menu). And also, search icon is displayed when opening menu-> Bookmarks.

**Closed by sflorean** 2022-06-08 12:24 UTC
Labels: feature request 🌟, Feature:Bookmarks
