### ISSUE TITLE
[Bug] The user is not redirected to home screen after the search widget is added  (Discoverability Experiment)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#11183] opened 2020-06-03 12:56 UTC
## Steps to reproduce
1. Launch Fenix.
1. Perform 3 searches and go back to the home screen.
1. From the search widget prompt tap on the `Add widget`.

### Expected behavior
After successfully adding the search widget from the search widget prompt, the user should be redirected to the home screen where the search widget is placed.

### Actual behavior
The user is not redirected to the home screen after the search widget is added 

### Device information
* Android device: Google Pixel 4 XL (10).
* Fenix version: Latest Debug build (from master).

![20200603-145225](https://user-images.githubusercontent.com/42831109/83638978-afc66d00-a5b2-11ea-9e2d-b2b796d926b2.gif)

**Comment by sblatz** [comment] 2020-06-03 15:35
I don't believe we should be closing the app to show the search widget. @brampitoyo please confirm, though!

**Comment by mcarare** [comment] 2020-06-03 16:00
IMO, we should have a consistent behavior, because when we add shortcuts (private or for a website) the icons are shown after we add them to system home screen. Though I was expecting the system to handle this itself.

**Comment by brampitoyo** [comment] 2020-06-09 05:53
@sblatz Ah, I overlooked this scenario. @mcarare is correct. When the “Add widget” button is pressed, Fenix should minimise to the Android System homescreen, where the newly installed search widget is shown.

This is consistent with behaviours of adding other widgets on Android.

**Comment by heres-maria** [comment] 2020-07-02 11:02
This issue is still partially reproducible. 
On some devices the screen is focused on the homescreen where the widget was added.
But on others it is not. Instead, the browser remains focused (with the popup still displayed as per #12157), or it refocuses on the last screen displayed before focusing/launching the browser. This issue has been logged here #12192.

Tested on Firefox Preview Nightly 200702 (Build #21840611) (14d09cc4a) GV: 79.0a1-20200629094229.
This issue was reproducible using Android 9 (Samsung Galaxy S8) and Android 8 (Samsung Galaxy S9) - as per the new issue filed.
This issue was not reproducible using Android 10 (OnePlus 5, Motorola One Vision).

**Comment by sflorean** [comment] 2020-07-03 15:26
Based on the above comment, I will remove the qa label. Please add it again, if the issue needs more investigation/verifying.

**Comment by abodea** [comment] 2020-07-23 13:48
Hi @liuche was this bug intended to be in **Releng Firefox Beta 79.1.0**? Please note that I cannot trigger the search widget prompt.
I do believe this is not included yet in the build.

**Closed** 2021-03-04 03:13 UTC
Labels: Feature:Discovery, Feature:Search, S1, eng:ready, feature:SearchWidget, wontfix, 🐞 bug
