### ISSUE TITLE
[Bug] The "tab closed" toast is persistent. "Undo" does nothing but dismiss it.

### ISSUE THREAD

**Issue by TheMadRuffian** [mozilla-mobile/fenix#8715] opened 2020-02-25 07:04 UTC
## Steps to reproduce
Just close any open tab.

### Expected behavior
The toast should disappear after a said amount of time. The undo button has to restore the previously closed tab.

### Actual behavior
The toast stays indefinitely. Tapping the undo button dismisses the toast but doesn't restore the tab.

### Device information
Xiaomi Mi A1

* Android device: 10
* Fenix version: 3.2.0
![Screenshot_20200225-145638_Firefox_Preview_1_1](https://user-images.githubusercontent.com/42994263/75222850-1d0e7900-57e0-11ea-8c51-b33a2fca42dd.png)

**Comment by cadeyrn** [comment] 2020-02-25 08:33
Duplicate of #7799.

**Comment by ekager** [comment] 2020-02-26 06:53
Closing as dupe

**Closed by ekager** 2020-02-26 06:53 UTC
Labels: needs:triage, 🐞 bug
