### ISSUE TITLE
[Bug] Android navigation bar disappears (loses styling) on scroll of search suggestions 

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14706] opened 2020-09-04 05:16 UTC
## Steps to reproduce

1. type anything into address bar
2. scroll down suggestions so that keyboard disappears

### Expected behavior

Navigation bar has a white background and is easy to see.

![signal-2020-09-04-011459_001](https://user-images.githubusercontent.com/152493/92202103-31e15e80-ee4c-11ea-91cc-9a423c7c8e84.png)

### Actual behavior

navigation bar is grayish and there are no visible buttons.

![signal-2020-09-04-011459_002](https://user-images.githubusercontent.com/152493/92202090-2beb7d80-ee4c-11ea-9074-9bd0bf8fe7cf.png)

### Device information

* Android device: Pixel 2
* Fenix version: reproducible on beta and nightly

**Comment by hwinnemoe** [comment] 2020-09-04 11:50
Duplicate of/Related to #14490

**Closed** 2020-09-04 13:25 UTC
Labels: needs:triage, 🐞 bug
