### ISSUE TITLE
FNX-3341 ⁃ Add ability to accept suggestion from search completion without submitting in order to append something or modify it

### ISSUE THREAD

**Issue by cypressious** [mozilla-mobile/fenix#10185] opened 2020-04-24 12:23 UTC
### Why/User Benefit/User Problem
Let's say I want to search for "Mozilla Firefox Beta" on Google. I'm typing "Mozilla" and one of the suggestions is "Mozilla Firefox". I would like to accept it but not submit the search, so that I can append " Beta" at the end.

Chrome has this feature, see screenshot below

![grafik](https://user-images.githubusercontent.com/1191816/80211739-8969f500-8636-11ea-877a-459871ab7c8a.png)

### What/Requirements
Add Button the suggestion row. When pressing the button, the content is inserted into the address bar where I'm typing but it's not submitted.

### Acceptance Criteria (how do I know when I’m done?)
I can take a search suggestion and append something without having to fully type the first part and without submitting two searches.

**Comment by cadeyrn** [comment] 2020-04-24 15:03
Duplicate of #8043.

**Comment by eliserichards** [comment] 2020-05-06 19:19
Closing as a duplicate

**Closed** 2020-08-10 19:30 UTC
