### ISSUE TITLE
[Bug]: Some glyphs are vertically shifted with COLR fonts

### ISSUE THREAD

**Issue by khaledhosny** [mozilla-mobile/fenix#22232] opened 2021-10-30 14:17 UTC
### Steps to reproduce

The page https://www.amirifont.org/fatiha-colored.html uses a font with COLR and CPAL tables for color glyphs.

### Expected behaviour

The rendering should match https://www.amirifont.org/fatiha.html sans the colors.

### Actual behaviour

On Android the mark glyphs (colored red) as well as the numbers (colored green inside the oval shapes) are shifted up.
![Screenshot_20211030-161515~2](https://user-images.githubusercontent.com/93914/139536593-1ea49706-dd9e-4625-bd57-f67a77eee78a.png)

### Device name

Nokia 7.2

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

93.2.0

### Additional information

On Firefox desktop it renders correctly. This is a regression since the page used to show fine, but I don't remember exactly last time I checked it.

**Comment by LaurentiuApahideanSV** [comment] 2021-11-01 11:30
I can confirm the issue is reproducible on Firefox Preview Nightly 2021-11-01. I have attached screenshots of what the page looks like in Firefox and Chrome.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
![Uploading Firefox.JPEG…]()
![Chrome](https://user-images.githubusercontent.com/50983519/139664786-5111dea9-9218-4409-8d14-2e0bafe386e1.JPEG)

**Comment by Mugurell** [comment] 2021-11-01 15:34
Moving to Bugzilla. Please follow the progress there.

**Comment by Mugurell** [comment] 2021-11-01 15:35
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1738700

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by Mugurell** 2021-11-01 15:35 UTC
Labels: 🐞 bug, needs:triage, qa-triaged
