### ISSUE TITLE
Adding search engines doesn't work anymore

### ISSUE THREAD

**Issue by vpaa** [mozilla-mobile/fenix#16197] opened 2020-10-26 22:35 UTC
When you add a new search engine ( Seach -> Add Search Engine -> Other ), it seems to go through but the new engine doesn't appear on the list. If you try to add the same engine again, the app says that a search engine by that name already exists. So, the new search engines are added to some data structure but the contents of that structure are not shown to the user.

This has been found with version 81.1.5 (Build #2015769595) running on Android Galaxy S10.

**Comment by AndiAJ** [comment] 2020-10-27 08:32
Duplicate of #15892

**Closed by AndiAJ** 2020-10-27 08:32 UTC
Labels: needs:triage, 🐞 bug
