### ISSUE TITLE
[Bug] All pages are displyaed blank after updating to 84.1.1

### ISSUE THREAD

**Issue by emuzychenko** [mozilla-mobile/fenix#17208] opened 2020-12-24 15:04 UTC
## Steps to reproduce
- Open Firefox
- Enter any URL or tap any icon on the Start Page

### Expected behavior
Displaying of some content is expected.

### Actual behavior
After the last update (84.1.1), Firefox displays blank pages for all URLs I tried. The progress indicator shows that some data are downloaded from the net, but the resulting page is always empty (white or black, depending on the URL). Absolutely no content is displayed.

System reboot, cleanup of Firefox data, uninstall/reinstall Firefox don't help.

All other apps, including Android Browser and Chrome, work normally.

### Device information
* Android device: Xiaomi Redmi Note 3 Pro, MIUI 8.0.6.0 (Android 5.1.1)

* Fenix version: 84.1.1 (Build #2015781795)
AC: 67.0.12, 24dd57cfd
GV: 84.0-20201211215739
AS: 67.0.0

**Comment by cadeyrn** [comment] 2020-12-24 16:01
Duplicate of #17181, will be fixed with 82.1.2.

**Comment by csadilek** [comment] 2020-12-24 17:46
Thanks for filing! 84.1.2 is rolling out.

**Closed by csadilek** 2020-12-24 17:46 UTC
Labels: needs:triage, 🐞 bug
