### ISSUE TITLE
[Bug] Scroll problem with my android mouse

### ISSUE THREAD

**Issue by Step72** [mozilla-mobile/fenix#17254] opened 2020-12-28 17:49 UTC
Hello,

I have a [HUAWEI MediaPad M5 Lite 10 tablet](https://www.amazon.fr/gp/product/B07G3JFHJR/?tag=hu2-21) I use it with a mouse connected to USB thanks to[ this adapter.](https://www.amazon.fr/gp/product/B07YWW8C6X/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1)

For some time with my mouse, I can no longer scroll through the pages of browsers like Firefox.

Rather than scrolling the text from top to bottom or vice versa, it selects the text for me!

I can no longer also do a copy / paste in the web pages, it selects but without displaying "copy / paste" I reset my tablet but it doesn't change anything.

I reset my tablet by following [this procedure](https://www.hardreset.info/fr/devices/huawei/huawei-mediapad-m5-108/) but it doesn't change anything.

I changed the adapter, tried with another mouse, with a bluetooth mouse but it's the same :(

I sent my tablet to the after-sales service 3 times for this problem but it came back each time as repaired but the problem is still present.

The funny thing is that when I take control of my tablet with my computer and with teamviewer I use my computer mouse! Well it works.

I can scroll web pages through my computer. 

**Device information**

* Firefox device: 85.0.0.-beta.4
* Android version: 8.0

**Comment by makotokato** [comment] 2021-01-05 07:21
@Step72 

Accessibility caret will handle touch only.  So no menu may be expected.

How about this on Chrome? I guess that no way to open select menu on Chrome too. (At least, this behavior is same on OPPO A5 + Chrome).

**Comment by makotokato** [comment] 2021-01-05 07:31
And I guess that wheel scroll will works instead of drag scroll, right?

**Comment by Step72** [comment] 2021-01-05 08:39
> Accessibility caret will handle touch only. So no menu may be expected.

Exactly but why?

> How about this on Chrome? I guess that no way to open select menu on Chrome too. (At least, this behavior is same on OPPO A5 + Chrome).

On chrome I have exactly the same problem, however I installed Qwant and it works perfectly

> > Do you reproduce this on Firefox for Android 84 and Firefox Nightly for Android too?

I have exactly the same problem

**Comment by Step72** [comment] 2021-01-07 16:29
Why with Quant it works but not with Firefox or Chrome ?

**Comment by kbrosnan** [comment] 2021-01-07 18:53
Duplicate of #3708

**Closed by kbrosnan** 2021-01-07 18:53 UTC
Labels: 🐞 bug
