### ISSUE TITLE
keep scanner, search engine selection in search bar itself. why keep them above?

### ISSUE THREAD

**Issue by rocky-01** [mozilla-mobile/fenix#17256] opened 2020-12-29 02:27 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

**Comment by mcarare** [comment] 2021-01-04 08:36
Duplicate of https://github.com/mozilla-mobile/fenix/issues/16659 & https://github.com/mozilla-mobile/fenix/issues/16658.

**Closed by mcarare** 2021-01-04 08:36 UTC
Labels: needs:triage
