### ISSUE TITLE
[Bug] Tab count label misaligned to the bottom left corner instead of center

### ISSUE THREAD

**Issue by nchevobbe** [mozilla-mobile/fenix#16611] opened 2020-11-17 07:04 UTC
Sometimes, the tab count number gets aligned to the bottom left:

![Screenshot_20201116-214620](https://user-images.githubusercontent.com/578107/99356721-e7984700-28aa-11eb-80ad-1e14f7834ca5.png)

## Steps to reproduce

I often see this when I had 10 tabs, then close one (which makes it 9)

### Expected behavior

The label should always be centered

### Actual behavior

The label isn't always centered

### Device information

* Android device: Pixel 3
* Fenix version: Latest Nightly (`201116 17:01 Build #2015776011`), but I'm seeing this for a while

**Comment by kbrosnan** [comment] 2020-11-17 08:06
Duplicate of https://github.com/mozilla-mobile/fenix/issues/16527

**Closed by kbrosnan** 2020-11-17 08:06 UTC
Labels: Feature:Tabs, Feature:Toolbar, 🐞 bug
