### ISSUE TITLE
FNX-3453 ⁃ [Bug] Downloading .PDF results in blank file

### ISSUE THREAD

**Issue by kglazko** [mozilla-mobile/fenix#10352] opened 2020-05-01 17:33 UTC
## Steps to reproduce
Download .PDF from a website
Click to open with Adobe Acrobat after the file has finished
(Alternative) Click to open through Downloads

### Expected behavior
You can open the PDF and see the expected contents of the PDF

### Actual behavior
The PDF is empty

### Device information
* Android device: ?
* Fenix version: ?

**Comment by kglazko** [comment] 2020-05-04 18:59
I haven't been able to consistently reproduce this and I was wondering if this is something that folks in QA have ever noticed while testing and perhaps were able to narrow down. If not, this is an investigation we should definitely do- I'm trying to find a pattern on my end as well.

**Comment by kglazko** [comment] 2020-05-04 21:02
So far I have tried with different PDF formats: PDF/A, PDF/X, and PDF/E and cannot reproduce. Also have tried with Adobe Acrobat installed and could not reproduce.

**Comment by sblatz** [comment] 2020-05-05 18:27
I'm not able to repro on Galaxy S9, Nightly Tuesday 5/5.

**Comment by abodea** [comment] 2020-05-06 12:49
@kglazko @sblatz I re-tested this issue, for more details please check the following:

Build latest Nightly **5/6** with **Google Pixel 4 XL (10), Google Pixel 3a (10), Huawei Mate 20 Lite (9), OnePlus A3 ( 6.0.1)**
With the following websites: [africau](http://www.africau.edu/images/default/sample.pdf), [file-examples](https://file-examples.com/index.php/sample-documents-download/sample-pdf-download/), [dummy pdf](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf), [pdf995](http://www.pdf995.com/samples/pdf.pdf).
I was not able to reproduce the issue and I was able to open without problems all the downloaded PDFs. 

I will remove the `eng:qa:needed` until further notice.

**Comment by sblatz** [comment] 2020-05-06 16:37
i'm going to close this for now. We can re-open if people start encountering again 😄

**Closed** 2020-08-11 00:31 UTC
Labels: Feature:Download, P1, 🐞 bug
