### ISSUE TITLE
[Bug] massive black bar adorns custom tabs

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2885] opened 2019-05-27 14:51 UTC
## Steps to reproduce
1. Open a custom (embedded) tab

### Expected behavior
No black bar at the bottom

### Actual behavior
There's a massive black bar (about the size of the awesome bar) at the bottom

### Device information
* Android device: Android 8, LG G6
* Fenix version: 1.0.1921

**Comment by cadeyrn** [comment] 2019-05-27 14:53
Duplicate of #2789.

**Closed** 2020-08-26 20:29 UTC
Labels: 🐞 bug
