### ISSUE TITLE
[Bug] "Set by Battery Saver" doesn't do anything

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#3445] opened 2019-06-13 18:29 UTC
## Steps to reproduce
1. Go into Theme Settings and select "Set by Battery Saver"
1. Enable Battery saver manually or because of low battery

### Expected behavior
The theme changes to the dark theme, or the option is not available at all.

### Actual behavior
Nothing happens when entering battery saver mode.

### Device information
* Android device: 7.1.1
* Fenix version: 1.0.1924

**Comment by WhoIsAndi** [comment] 2019-06-19 08:37
Hi, I was able to reproduce this issue on Fenix 1.0.0-rc.2 (Build #11700147) using two tablets:
• Lenovo TB3-850M (Android 6)
• Samsung Galaxy Tab A (Android 7)

**Comment by NotWoods** [comment] 2019-11-28 20:01
I think we can close this because I don't see that menu option anymore. Please let me know if this is still reproducible and I'll reopen.

**Closed** 2020-08-27 00:04 UTC
Labels: 🐞 bug
