### ISSUE TITLE
FNX-11950 ⁃ [Bug] Cannot expand youtube comment

### ISSUE THREAD

**Issue by J-Siu** [mozilla-mobile/fenix#11085] opened 2020-05-30 17:30 UTC
## Steps to reproduce
1. Go to youtube website
1. Click on any youtube video with comments
1. Scroll down to the bottom and click "down arrow" to expand comment section.

![Screenshot](https://user-images.githubusercontent.com/3171920/83335245-796ab400-a279-11ea-9941-67e31116de9c.jpg)UNITO-UNDERSCORE!20200529-030217!

### Expected behavior
Comment section should expand.

### Actual behavior
Either nothing happen or a menu pop-up.

### Device information
* Android device: oneplus 6t
* Fenix version: 200530 06:01

**Comment by cadeyrn** [comment] 2020-05-30 17:56
Duplicate of #10720.

**Comment by J-Siu** [comment] 2020-05-30 21:17
Yes, it is duplicate, closing.

**Closed** 2020-08-11 02:52 UTC
Labels: needs:triage, 🐞 bug
