### ISSUE TITLE
[Bug] App shortcuts shows 'App isn't installed' toast

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#5362] opened 2019-09-16 14:45 UTC
## Steps to reproduce
1. Press and hold the app icon.
2. Click on the 'Open new private tab' or 'Open new tab'.

### Expected behavior
 - A new private tab is opened or a regular tab is opened, respectively.

### Actual behavior
 - You see a toast that says "App is not installed". See screenshot below.
 - Placing the shortcuts on the homescreen and clicking on them there do not work either.

### Device information

* Android device: Pixel 2 (Android 10)
* Fenix version:
> Nightly 190916 06:04 (Build #12590612)
> :package:: 13.0.0, 946a4254f
> :lizard:: 71.0a1-20190913092859

![image](https://user-images.githubusercontent.com/1370580/64967797-237ee900-d86f-11e9-9e16-cd563f935473.png)

**Comment by NotWoods** [comment] 2019-09-16 16:34
This toast shows up when android can't find an activity corresponding to the shortcut intent.

**Comment by NotWoods** [comment] 2019-09-30 03:24
The shortcuts file has the package hardcoded, so my suspicion here is that your app version wasn't `org.mozilla.fenix` or `org.mozilla.fenix.debug`.

**Comment by mcarare** [comment] 2019-11-25 15:24
@jonalmeida Can you confirm what Tiger said? TY!

**Comment by jonalmeida** [comment] 2019-11-26 18:10
I filed this bug in September, I can't really recall from then. 🙂 

The reference browser bug for this is still reproducible though, so I imagine that it's not related? https://github.com/mozilla-mobile/reference-browser/issues/935

**Comment by boek** [comment] 2019-12-03 00:09
@jonalmeida hmm. I've tried the STR on reference browser in Fenix and can't reproduce. I'm going to close it for now but if anyone runs into it again we can re-open 👍

**Closed by boek** 2019-12-03 00:09 UTC
Labels: Feature:PrivateMode, Feature:Shortcuts, needs:investigation, 🐞 bug
