### ISSUE TITLE
Open tab view when swiping from the bottom aligned tool-/searchbar

### ISSUE THREAD

**Issue by tsoj** [mozilla-mobile/fenix#14165] opened 2020-08-25 13:49 UTC
If I want to open the tab view then I have to press that small button. It feels much more natural to be also able to open this tab view when I start swiping from the toolbar (like scrolling down but not starting the gesture on the website).  
The whole gesture handling of the tab view is scrolling up and down and also closing the tab view is scrolling down, so it would make perfect sense to be also able to open the tab view using this method.

**Comment by Dunexus** [comment] 2020-08-25 14:37
Duplicate of https://github.com/mozilla-mobile/fenix/issues/11862

**Comment by liuche** [comment] 2020-08-26 19:11
Tab tray gesture is in-progress!

**Closed by liuche** 2020-08-26 19:11 UTC
Labels: needs:triage
