### ISSUE TITLE
[Bug] "Tab closed" message doesn't go away if you switch to another tab too quickly

### ISSUE THREAD

**Issue by MechJM** [mozilla-mobile/fenix#7918] opened 2020-01-24 17:21 UTC
## Steps to reproduce
Open a tab, close it and switch to another one.
### Expected behavior
A message pops up saying "Tab closed" and gives you the option to undo your action. After a few seconds it should disappear.
### Actual behavior
The message pops up, gives you the option to undo the action but doesn't go away (screenshots below).
![IMG_20200122_193301](https://user-images.githubusercontent.com/56487084/73089025-51cf9d80-3ecd-11ea-9803-ccbbe7a594e2.jpg)
![Screenshot_2020-01-24-12-29-44-834_org mozilla fenix nightly](https://user-images.githubusercontent.com/56487084/73089026-51cf9d80-3ecd-11ea-83e8-65b0f60c1ccf.jpg)

### Device information

* Android device: Xiaomi Mi 9T - Android 10
* Fenix version: Nightly 200124 06:01

**Comment by cadeyrn** [comment] 2020-01-24 17:53
Duplicate of #7799.

**Closed** 2020-01-24 18:00 UTC
Labels: needs:triage, 🐞 bug
