### ISSUE TITLE
[Bug] Second fenix app opens automatically that is only a gray screen and cannot be interacted with when switching between apps

### ISSUE THREAD

**Issue by KeaganBailey** [mozilla-mobile/fenix#15438] opened 2020-09-25 20:59 UTC
## Steps to reproduce

Open fenix and switch between apps by either swiping along the bottom of the screen or by swiping up to show all open apps. 

This started happening after updating to the new Android version 11.

### Expected behavior

Only the one fenix screen is visible

### Actual behavior

There are two fenix screens shown and one is fully gray/non-interactable
![Screenshot_20200925-164904](https://user-images.githubusercontent.com/50888763/94315228-1e5b7c00-ff50-11ea-8009-c709fa198ed7.png)
![Screenshot_20200925-164909](https://user-images.githubusercontent.com/50888763/94315236-22879980-ff50-11ea-9315-cab89f940adb.png)

### Device information

* Android device: Pixel 4 XL 
* Android version: 11
* Fenix version: 81.1.1

**Comment by cadeyrn** [comment] 2020-09-25 21:03
Duplicate of #13270.

**Closed** 2020-09-25 21:06 UTC
Labels: needs:triage, 🐞 bug
