### ISSUE TITLE
FNX-4519 ⁃ [Bug] Tab Tray: The selection circle is displayed under the navigation bar

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#10742] opened 2020-05-18 14:51 UTC
## Steps to reproduce
1. Launch Fenix and open 2-3 tabs.
1. Open the `Open tabs` section.
3 Tap and hold on any of the following: `PB, home, +` buttons.
1. Observe the selection circle.
    1. Expected behavior
The selection circle should be displayed above the navbar.
    1. Actual behavior
The selection circle is displayed under the navigation bar
    1. Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 5/18.**

![20200518-172359-1](https://user-images.githubusercontent.com/42831109/82227239-28c99180-9930-11ea-8f0d-9a58ea632482.gif)

**Comment by kbrosnan** [comment] 2020-05-19 18:16
See also #4673

**Comment by kbrosnan** [comment] 2020-05-27 05:41
dupe of #10589

**Closed** 2020-08-11 01:35 UTC
Labels: Feature:Tabs, S2, 🐞 bug
