### ISSUE TITLE
FNX-5181 ⁃ [Bug] changing theme will open the keyboard

### ISSUE THREAD

**Issue by k0ur0x** [mozilla-mobile/fenix#1683] opened 2019-04-17 03:57 UTC
## Steps to reproduce
* navigate to theme settings
* change theme

### Expected behavior
not opening the keyboard

### Actual behavior
opening the keyboard

### Device information
* Android device: P20 Lite (Android 8.0.0)
* Fenix version: 1.0.1916

**Comment by kbrosnan** [comment] 2019-04-17 04:03
Possible dupe of #1632 try the April 17th build tomorrow to see if that fixes this.

**Comment by LittleAngelwings** [comment] 2019-04-17 05:30
At the Build 1.0.1916 (11061212) 04/16 I don't have this issue and not at the  last 5 builds before.
All testet with Android 8.1.0 on Samsung Galaxy Tab A (2016) and Huawei P smart, but on both I use SwiftKey 7.2.7.20.

**Comment by cadeyrn** [comment] 2019-04-18 11:32
The keyboard also opens when switching between regular and private mode. Since both modes use a different theme it's probably related and I won't open a new issue for that.

HTC U11 / Android 8.0, Fenix revision 5e61366cb9edd1dbc686dedf2cb0ae3d202676c6 so definitively not fixed by #1632 (but maybe the opposite and it's a regression from #1632? I can test later which change introduced the bug).

**Comment by cadeyrn** [comment] 2019-04-18 18:01
Another case of unexpected keyboard opening:

1. start Fenix and make sure the keyboard is hidden
2. wait until your display is off or turn it off
3. enable your display / unlock your phone again

Expected:

Keyboard is still hidden.

Actual:

Keyboard is open.

**Comment by cadeyrn** [comment] 2019-04-19 16:36
@sblatz I confirmed by manually reverting #1659 that your change caused all the bugs described here.

**Comment by sblatz** [comment] 2019-04-19 16:38
@cadeyrn yep, that's definitely the commit that caused it. I will look into this.

**Closed** 2020-08-11 12:29 UTC
Labels: 🐞 bug
