### ISSUE TITLE
Sometimes can't scroll up in tabs list on Android app

### ISSUE THREAD

**Issue by Riley-Hart** [mozilla-mobile/fenix#17212] opened 2020-12-24 22:22 UTC
See [https://support.mozilla.org/en-US/questions/1318857](https://support.mozilla.org/en-US/questions/1318857)
for several users' descriptions of this issue.  I'd really appreciate it if you could ask them, not just me, if you need more information. I don't want to be a bottleneck but may not be able to respond quickly, and some of them are really good at describing what's going on. Thanks!

## Steps to reproduce
NOTE: I can't actually reproduce it now that I've used a workaround that fixes it (described under Actual Behavior, below), so I don't know what started the problem. Maybe reaching a certain large number of tabs? There may be clues in the Support item listed above.
Starting this morning, with the toolbar at the bottom of the screen, and with *roughly* 12 to 15 open tabs, I would swipe/pull down, with my finger on the list or grid of tabs (not on the header of the tabs window).  The issue happened in either list or grid view.  And, judging from the support forum, it also happens when the toolbar is at the top of the screen.

### Expected behavior
The list or grid of open tabs would scroll, letting me see the whole list.

### Actual behavior
The top of the tabs window moved down, collapsing the tab window like a window-shade -- as though I had put my finger on the header at the top of the tabs window before swiping/pulling down.
Workaround: Normal behavior resumes after one opens a new tab and closes it.  It's possible that simply closing enough tabs also fixes it, but I'm not sure.

### Device information

* Android device: Samsung Galaxy S7 
*  Running Android 8.0.0
* Fenix version: 84.1.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9225)

**Comment by headbank** [comment] 2020-12-24 23:27
Seeing this on my partner's Galaxy S7 Edge (Android 8.0.0). Dragging down closes the drawer when it should scroll-up the tabs (12 tabs open). Occasionally the drawer vanishes entirely while (unintentionally) closing and reappears at fully-opened position.

Similar issue whether in row or grid display mode. Workaround mentioned above only has effect for one scroll of the drawer, then back to the buggy behaviour.

**Comment by Shadowspear123** [comment] 2020-12-31 19:29
I've had this bug for a while too. Attached a screen recording below. I forgot to make it show my touches, but in the video I'm swiping downwards to scroll the tab list.

https://user-images.githubusercontent.com/50462281/103423435-81bf0080-4b74-11eb-9e77-bb7082e8c5b8.mp4

**Comment by MadMattAu** [comment] 2021-01-08 05:08
This is particularly compounded by the list now ordered with the newest item on the bottom of the list so I get 4 tabs, anything else is simply not accessible in either list or picture view.

**Comment by Shadowspear123** [comment] 2021-01-08 14:26
@MadMattAu My thoughts exactly

**Comment by DV2FOX** [comment] 2021-01-11 18:37
Since the last 2 FF4A updates that this issue happened to me too and it's annoying.

-Galaxy S7
-Latest FF ver
-Latest FW (March 2020, the newest one didn't rolled out for EU yet without the use of 3rd party apps?)

You open up the tabs list from the top right icon, it shows up (mine shows with texts and a small preview on the list unlike  SS123 's video above) and whenever i slide my finger down it wants to close the tab list instead of scrolling it to show the top tabs

I hope the FF team can do something about this ASAP, even if it's a tiny patch, i don't care. Just take ya time and fix it, please..

**Comment by DV2FOX** [comment] 2021-02-17 15:40
Can't believe that after after the last 2 patches, wich worked flawless, NOW the actual version of the app does the same mistake again.

Same issue etc as my last post from Jan 11th.. Sorry for recovering the topic but it had to get known ==;

**Comment by headbank** [comment] 2021-02-17 19:31
@DV2FOX just to be clear, you're saying this bug disappeared 3 releases ago, but reappeared in current release? (I wouldn't know as I haven't been keeping an eye on my SO's phone, but she hasn't mentioned anything.)

If so that could be a big pointer in diagnosing this (whenever someone comes to look at it).

**Comment by DV2FOX** [comment] 2021-02-17 19:59
Yep. Everytime it got updated the bug was gone but then later on, either same release or a newer one, with time it reappeared

Weird?..Yeah..Unfair?..Too!

**Comment by headbank** [comment] 2021-02-17 21:06
@DV2FOX Ah, that's quite different from how I interpreted your previous post. It seemed you were saying that the previous two releases were completely free of this bug, but then in the most recent release it returned. (That would have given scope to look at what changed between those releases to maybe identify the source of the bug.)

But if I follow your latest post correctly, what you are actually saying is that, in every release, the behaviour was the same: the bug was present but didn't occur until a while after installing the update. (There might be something the devs can learn from that too, but it's quite a different scenario. Important to be precise.)

**Comment by Shadowspear123** [comment] 2021-02-18 15:48
Unfortunately for me the bug never went away. It has been consistent throughout the past few updates. I have tabs up there from months ago that I haven’t been able to access.

**Comment by DV2FOX** [comment] 2021-02-18 19:55
@headbank Yeah, that's what i meant to say, sorry for the confusion. It'd go like this:

1. App from previous 3 updates (For example) has the bug
2. New version of the app comes. Fixes it
3. Version from step 2 , after some time, causes the bug to happen again
4. Repeat step 2 and 3 until a final fix fixes it but again, who knows if it'll happen in future reelases

**Comment by DV2FOX** [comment] 2021-02-26 12:53
Wanted to report that, FOR NOW, it's been fixed with a new touch that might've been the cause of the situation

With yesterday's update (25/2/2020) , whenever ya launch up FF well, goes ok, and now, whenever you press the Tabs icon at the top/bot (top for me ,preference), there's a brief yet SMOOTH animation where the tabs' menu sliiiiides up from the bottom softly, from a zero opacity to 100% opacity transition (i think), and ending up such animation, scrolling through the tabs works as it should.

Back then , i think, the tabs' list "just appeard" in a pop up way and instantly, no transitions nor effects.

Let's see how this one lasts, but for now, "Thank you, DJs <3c"..

**Comment by MadMattAu** [comment] 2021-02-28 04:18
I am finding that it works the first time I access it after I restart my phone.  Once it has worked once it is borked and stays that way through multiple restarts of Firefox.  Only a phone restart resets this madness.

**Comment by DV2FOX** [comment] 2021-03-02 23:12
Welp, it happened again, and i've tried MMA's "restart phone" method and on first run on the app it keeps the issue on.

My theory for now is right: Once it updates it has a 50% chance of happening or not.. If it doesn't happens then it'll happen soon or later, and not even a phone restart will help out at all.

Please keep investigating the issue

**Comment by Therdel** [comment] 2021-03-05 08:29
Found a workaround:
Without lifting the Finger, scroll a bit towards the bottom before scrolling upwards.

Explicitly: Before scrolling up (Finger moving down):
- scroll a bit downwards (Finger moving up)
- don't lift the finger
- then scroll upwards (Finger moving down) 

Having the same problem since two or three days. 12 tabs open, if that's of anyones interest. 

What affects the Problem?
- performing my described "preparation scroll" 
- restarting fixes it for the first scroll or so
- opening a new tab fixes it for the first scroll or so
- Just opened 6 tabs, now momentarily the problem disappeared (couldn't reproduce), problem reappeared after an app restart.

Device:
Huawei P10 Lite
OS:
Android 8.0.0
Firefox:
86.1.1 (Build #2015794883)
AC: 72.0.16, f4aa67a9c
GV: 86.0-20210222142601
AS: 67.2.0

**Comment by PlayXman** [comment] 2021-03-07 13:29
It's the same issue as https://github.com/mozilla-mobile/fenix/issues/14837

I can confirm @Therdel 's findings. Everything was working until I closed the app and run it again. Also, the workaround he mentions is working for me, thanks m8.
#### Device info
**OS:** Android 8.0.0
**Firefox:** 86.1.1 (Build #2015794883)

**Comment by CapitainFlam** [comment] 2021-04-14 08:40
Greatings, fellows ! 

To confirm hereby that thebug can be reproduced today, on 

galaxy note8 
android 8.0.0
kernel 4.4.111-13688770-QB20376468
(29 oct 2018)

FF BRowser for Android
87.0.0-rc.1 build #2015799099
AC 73.0.11, bea80bbac
GV 87.0-20210315170302
AS 71.0.0
tuesday 3/16 @11:37pm

**Comment by DV2FOX** [comment] 2021-04-14 10:52
The issue started happening a few days ago again.. This ain't normal..Take ya time to search for fixes for it.

Thanks for the efforts too

**Comment by pkubowicz** [comment] 2021-04-17 16:32
I experience this bug since Firefox for Android started to display tabs this way – probably since December 2020. Very rarely it's possible to normally scroll the list of open tabs as expected, but usually the tab list is just unusable: touch anything and the whole list will start to hide. 

> Workaround: Normal behavior resumes after one opens a new tab and closes it.

I cannot confirm this. Even killing the app from Android settings does not fix the tab behaviour.

I don't understand how this kind of issue can happen for such a long time. If this kind of tab presentation is problematic, present them as squares as Chrome does. The current mechanism simply does not work.

You wonder why Firefox is losing market share in favour of Chrome. Well, this issue is enough to scare every new user away. How much a browser is worth if you cannot switch tabs in it? I have to be completely mad to still use Firefox for Android. Maybe it's the effect of having Linux on desktop or too much coding in ANSI C doing something to my brain, I don't know.

Firefox Beta 88.0.0-beta.6 Build #2015803915
Sony Xperia X Compact F5321
Android 8.0

**Comment by Shadowspear123** [comment] 2021-04-17 19:25
Yeah I don’t understand how an issue that directly impacts the absolute usability of the browser this significantly can exist for this long. Every update there’s some new un-asked for “feature” but no fixes to things that have been broken by the new redesign.

**Comment by DV2FOX** [comment] 2021-04-29 16:59
Same issue. Update from 2 days ago "Starts great, gets broken later"..

**Comment by DV2FOX** [comment] 2021-05-08 21:07
4 days after the latest 88.1 update and has the same issue. There seems to be no end to this..

**Comment by pkubowicz** [comment] 2021-05-30 20:10
Version 89.0.0-beta.10 works fine for me.

**Comment by DV2FOX** [comment] 2021-05-30 21:25
"Beta"...People would want a stable one and to last like...Forever?..The better way, that is.

**Comment by PlayXman** [comment] 2021-06-06 04:15
> Version 89.0.0-beta.10 ~works fine for me.~
> Edit: still happens… I have 17 tabs and not able to get to 1st of them.

Yep..I can confirm `89.1.1` stable still has this bug. Even UI redesign hasn't helped.

**Comment by NitCelcius** [comment] 2021-06-11 12:08
Got the same problem on version 89.1.1 (stable, Google Play). My device is `SH-04H` @ Android OS version 8.0
Also confirmed the same problem on `Amazon Fire 7` @ Fire OS (based Android version is 9), which I installed firefox APK directly

Regardless of screen rotation, tabs can't be scrolled and instead the tab drawer closes.

PlayXman's temporary fix actually works! Hope this problem be fixed soon.

**Comment by DV2FOX** [comment] 2021-06-11 12:21
Yep, PX's temp fix works (Thanks, DJ!), but hopefully there's an official perma-like fix...Soon?

**Comment by codrut-topliceanu** [comment] 2021-06-24 07:36
**Recap**:
**Devices:** _Samsung Galaxy S7, Galaxy S7 Edge, Huawei P10 Lite, Galaxy Note 8, Sony Xperia X Compact, Sharp Aquos Zeta SH-04H, Amazon Fire 7_
**Android version:** _8.0, Fire OS_

I have tried and been unable to reproduce this issue on : Galaxy Note 3 (Android 5), Motorola E4(Android 7), Emulator (Android 8), OnePlus 6(Android 9), Pixel 3XL (Android 10), Pixel 4 (Android 11). Tried Grid and List mode.

I'd like to request some help from QA with this if it's possible.

**Comment by LaurentiuApahideanSV** [comment] 2021-06-25 15:27
I tried to reproduce this issue on Firefox Preview RC 89.1.1 and Nighty 6/25 but was unable to. I'll keep an eye for the issue during normal testing and if I can reproduce the issue I will leave a comment.
### Devices used:
- Samsung Galaxy S9 (Android 8.0.0)
- Google Pixel 3 XL (Android 9)
- OnePlus 6T (Android 9)

**Comment by oluc** [comment] 2021-07-03 10:37
another workaround that works for me: first scroll up, then you can scroll down

- tap and hold
- scroll a little up
- scroll down
==> scrolls the ten list down.

**Comment by PlayXman** [comment] 2021-07-14 00:19
Hey guys, I've just found another "temporary" fix:
1. If you can't scroll up in the tab list go to one of the already opened tabs
2. Choose one of the links on that page and long press on it, so you get the option to **open the link in the new tab**
3. Do so
4. ✨ You're able to scroll again. At least for the time being

### Tested on:
Firefox 89.1.1
Android 8

**Comment by PlayXman** [comment] 2021-12-11 05:05
Hello there, I was just wondering if anyone witnessed the issue lately? I wasn't able to reproduce it since Firefox >90 (Android 8; current version 95.1.0). I guess if everyone is ok with the current state, the issue can be closed.

**Comment by Riley-Hart** [comment] 2021-12-11 05:23
I can't replicate it now.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by DV2FOX** [comment] 2021-12-11 05:30
No issues on actual Android for Galaxy A52 5G , latest FF version ^^.

**Comment by MadMattAu** [comment] 2021-12-11 06:55
> Hello there, I was just wondering if anyone witnessed the issue lately? I wasn't able to reproduce it since Firefox >90 (Android 8; current version 95.1.0). I guess if everyone is ok with the current state, the issue can be closed.

Not since the new interface with the old tabs appeared, and the desire to close old tabs came in.  But now I have graphics issues that are actually worse,  so my experience is not improving.

**Comment by stibu81** [comment] 2021-12-11 16:07
No problem on Galaxy A32 5G, Android 11, Firefox 95.1.0

**Comment by PlayXman** [comment] 2021-12-12 23:58
> Not since the new interface with the old tabs appeared, and the desire to close old tabs came in. But now I have graphics issues that are actually worse, so my experience is not improving.

Hey @MadMattAu, are you able to record a video with the graphic issues? Also, sharing your phone model and os version would definitely help the devs with debugging.

**Closed** 2022-11-25 00:11 UTC
Labels: 🐞 bug, 🙅 waiting, Feature:Tabs, Feature:Gesture, wontfix
