### ISSUE TITLE
[Bug]: Scroll position in tab list does not show active tab

### ISSUE THREAD

**Issue by WesleyAC** [mozilla-mobile/fenix#20932] opened 2021-08-19 21:15 UTC
### Steps to reproduce

With many active tabs open, click on the tab switcher.

### Expected behaviour

The active tab should be visible in the viewport.

### Actual behaviour

Often, the active tab will not be scrolled into the viewport — instead, the view will either be scrolled to the complete bottom, or the complete top.

### Device name

Google Pixel 3a

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

93.0a1

### Additional information

I have my tabs settings as:

* Tab view: List
* Close tabs: Manually

I'm not sure if this is relevant, though.

**Comment by marcel263** [comment] 2021-08-19 21:55
also #19943

**Comment by jonalmeida** [comment] 2021-08-20 02:52
Do you have any inactive tabs in your tray list? This might be a duplicate of https://github.com/mozilla-mobile/fenix/issues/20637.

> I'm not sure if this is relevant, though.

It is helpful, thanks. 🙂

**Comment by argymeg** [comment] 2021-10-30 13:50
Can confirm this is happening for me again as well (it had stopped for a while after the closure of #20637). I have no inactive tabs.

**Comment by jonalmeida** [comment] 2021-11-02 02:19
> Can confirm this is happening for me again as well (it had stopped for a while after the closure of #20637). I have no inactive tabs. The workaround mentioned in the closure of #22116 also made no difference.

Could you file a new bug with STR how you reproduced it? We fixed this already in https://github.com/mozilla-mobile/fenix/pull/21177 so if there is a regression, let's file it as such.

Closing this issue, since we forgot to tag it in https://github.com/mozilla-mobile/fenix/pull/21177 and have it auto-closed.

**Closed by jonalmeida** 2021-11-02 02:19 UTC
Labels: 🐞 bug, needs:triage
