### ISSUE TITLE
No duplicates in a collection

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#4544] opened 2019-08-05 20:20 UTC
### Why/User Benefit/User Problem

It is a bit confusing to save the exact same website in a collection twice because it is not a new tab concept only but a bit like a bookmarks system as well.

### What/Requirements

It should work like the bookmarks system where it will check for duplicates.

### Acceptance Criteria (how do I know when I’m done?)

Within the adding process it will show the duplicate message for explicit save of only one website and when adding a howl tab group the duplicate website will not be added and remains as open tab.

- Add one website to collection -> Duplicate **Message**
- Add all tabs to collection -> Duplicate website is **not added and stays in open tabs**

**Comment by topotropic** [comment] 2019-09-18 20:39
dupe of https://github.com/mozilla-mobile/fenix/issues/2917

**Closed by topotropic** 2019-09-18 20:39 UTC
Labels: Feature:Collections, 🌟 feature request
