### ISSUE TITLE
[Bug] back button used in a tab open by a link from another tab does not being you back to the original tab

### ISSUE THREAD

**Issue by costin3141** [mozilla-mobile/fenix#6286] opened 2019-10-26 13:06 UTC
## Steps to reproduce
On a site with a link that on click opens the linked site in a new tab activate that link. Then, within that newly opened tab press the back button.
### Expected behavior
The newly opened tab should close and i should be again in the original tab.

This is the behavior as in Firefox for Android and is very convenient.
### Actual behavior
I get to the tab overview with all trans still existing. I am forced to manually close the new tab and activate the first one again.

### Device information
Pixel 4 xl

* Fenix version: ?
2.2.0 (Build #12901947)
📦: 16.0.0, ab2555b20
🦎: 70.0-20191007080030

**Comment by topotropic** [comment] 2019-11-18 09:53
closing as dupe of https://github.com/mozilla-mobile/fenix/issues/5963

**Closed by topotropic** 2019-11-18 09:53 UTC
Labels: 🐞 bug
