### ISSUE TITLE
[Bug] Unable to select DuckDuckGo as search engine on Firefox Preview

### ISSUE THREAD

**Issue by shellkr** [mozilla-mobile/fenix#3776] opened 2019-06-28 19:53 UTC
### Why/User Benefit/User Problem
I wouldn't chose a privacy minded browser and then only have Google as a search provider. Will not be able to use this app until that is possible.

### Acceptance Criteria (how do I know when I’m done?)
Make DuckDuckGo available as search engine from start or at least make it possible to install.

**Comment by kbrosnan** [comment] 2019-06-28 19:56
Dupe of #3736

**Closed by kbrosnan** 2019-06-28 19:56 UTC
Labels: 🌟 feature request
