### ISSUE TITLE
FNX-3244 ⁃ Install PWAs as a Webapk

### ISSUE THREAD

**Issue by szaimen** [mozilla-mobile/fenix#10038] opened 2020-04-18 18:42 UTC
### Why/User Benefit/User Problem
PWAs should be visible in the App Drawer and should have their own settings Page. Because I can then edit access rights over the system settings, search for them over the app search, etc.

### What/Requirements
Don't know what to enter here.

### Acceptance Criteria (how do I know when I’m done?)
A few points are listed in the first section of this feature request.

**Comment by kbrosnan** [comment] 2020-04-18 20:11
Dupe of https://github.com/mozilla-mobile/android-components/issues/1832

**Comment by szaimen** [comment] 2020-04-18 20:14
@kbrosnan thanks for the link but why was this closed? 
It isn't implemented as far as I have tested this. 
Aren't you planning to implement this very useful feature?

**Comment by kbrosnan** [comment] 2020-04-19 06:09
More of a question for the Android Components team. You could ask on the issue or https://chat.mozilla.org/#/room/#android-components:mozilla.org

**Comment by Dunexus** [comment] 2020-04-19 07:16
In the FAQ of this [devblog article about webapks](https://developers.google.com/web/fundamentals/integration/webapks), Google explains :

>**I am a developer of another browser on Android, can I have this seamless install process?**
>We are working on it. We are committed to making this available to all browsers on Android and we will have more details soon.`

It's been at least a year now and sadly nothing changed about this statement. Not sure about what "soon" actually means.

**Closed** 2020-08-10 18:05 UTC
Labels: feature request 🌟, needs:triage
