### ISSUE TITLE
Clear Tabs on exit

### ISSUE THREAD

**Issue by tw-e** [mozilla-mobile/fenix#3706] opened 2019-06-27 13:24 UTC
### Why/User Benefit/User Problem
There exists users who want to start with a fresh home view. They do not want to have the tabs from their previous sessions cluttering their home view.

### What/Requirements
When a user chooses the tabs are discarded and when they re-enter the browser they see a fresh home view with none of their previous tabs open.

### Acceptance Criteria (how do I know when I’m done?)
When users are done browsing the tabs from that session are not restored.

### Brave UI
![59995980-8a836c00-968b-11e9-8e3b-ddf1c4932f89](https://user-images.githubusercontent.com/51475468/60269902-ea934000-9921-11e9-832a-72590bcc4b36.jpg)

**Comment by cadeyrn** [comment] 2019-06-27 13:35
Can you please rename your issue to "Close tabs on exit" or something similar? I don't want to open this issue every time I see it because it's not clear what "I hope to add this option" is about. Thank you.

Also you says "I hope the browser can add these two options" but you only talked about one option. What is the other one?

**Comment by kbrosnan** [comment] 2019-06-27 14:37
dupe of #3605

**Closed by kbrosnan** 2019-06-27 14:37 UTC
Labels: 🌟 feature request

**Comment by tw-e** [comment] 2019-06-28 05:01
> Can you please rename your issue to "Close tabs on exit" or something similar? I don't want to open this issue every time I see it because it's not clear what "I hope to add this option" is about. Thank you.
> 
> Also you says "I hope the browser can add these two options" but you only talked about one option. What is the other one?

Hello there:

Sorry, I mean this.

There is also a reference picture underneath, sorry to forget to add a note.

@cadeyrn @kbrosnan
