### ISSUE TITLE
[Bug]Website is incompatible (GIF not loading)

### ISSUE THREAD

**Issue by pykko87** [mozilla-mobile/fenix#17594] opened 2021-01-22 21:06 UTC
I am using the latest Firefox for Android 85.1.0 on my Samsung Galaxy S20 Ultra (OneUI 3.0 based on Android 11)

When I visit the following website, the GIF is not loading: https://giphy.com/gifs/W1xcsZKbMPwzZfPkbo

Tested with Firefox for iOS and it works as expected.

**Comment by Amejia481** [comment] 2021-01-25 15:24
I think the issue is the autoplay setting is blocking the image from showing,  if you change the autoplay setting to "Allow audio" or to "Allow audio and video" then refresh the page, the GIF image should show. In Firefox [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) we added support for configuring autoplay [per website](https://drive.google.com/file/d/1mweUu_xTUyCvZJxsAtlDut0N3nZSbtAx/view), it will be roll out to other channels in new versions of the app. Please confirm, if the issue is fixed when changing settings.

**Comment by pykko87** [comment] 2021-01-25 18:02
Hello!
I've set to "Block only audio" and now it works.

There is no "Allow audio" or "Allow audio and video"

**Comment by Amejia481** [comment] 2021-01-25 18:41
Sorry for that "Allow audio and video" is only available in nightly. I think we can close this issue, please feel free to reopen if needed.

**Closed by Amejia481** 2021-01-25 18:41 UTC
Labels: S3, 🐞 bug
