### ISSUE TITLE
[Bug]: drop-down list won't open

### ISSUE THREAD

**Issue by samlux04** [mozilla-mobile/fenix#23370] opened 2022-01-23 22:09 UTC
### Steps to reproduce

Tapping on drop-down menu won't open the selection list. It happened on all website including extension's settings. https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

### Expected behaviour

A selection list should appear.

### Actual behaviour

It do nothing.

### Device name

Google Pixel 5

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1 (Build #2015859147), 611a9002b+ AC: 98.0.20220123143137, de26ff7e53 GV: 98.0a1-20220123093907 AS: 90.0.0

**Comment by sheikh-azharuddin** [comment] 2022-01-24 07:06
Seems critical bug.
I was about to file a issue then I saw this..please fix this..dropdown selection not working in any site

**Comment by sheikh-azharuddin** [comment] 2022-01-24 09:45
@Mugurell could you please look into this issue and fix?🥺

**Comment by tasosb** [comment] 2022-01-24 10:25
This is most probably a geckoview regression, I filed a bug there https://bugzilla.mozilla.org/show_bug.cgi?id=1751674

**Comment by robovoice1** [comment] 2022-01-24 13:43
Same with Pixel 4a Android 12 - GrapheneOS
And Fx mobile android nightly 

98.0a1 (Build #2015859243), 3e796726d+
AC: 98.0.20220123143137, de26ff7e53
GV: 98.0a1-20220123093907
AS: 90.0.0

**Comment by robovoice1** [comment] 2022-01-24 13:49
I tried to change language settings on common voice website with no response tapping on the box.

**Comment by kbrosnan** [comment] 2022-01-24 19:21
Closing as an upstream issue. Please follow updates on the Bugzilla report.

**Closed by kbrosnan** 2022-01-24 19:21 UTC
Labels: 🐞 bug, needs:triage

**Comment by kbrosnan** [comment] 2022-01-25 18:34
https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.latest/ is up with a fix. The Play Store app should have the update live in a few hours as Google refreshes their caches.

**Comment by samlux04** [comment] 2022-01-25 19:29
Okay, just updated from play store. Fixed confirmed.

**Comment by tasosb** [comment] 2022-01-25 19:29
It only partialy fixed the problem.
The first click-select works fine.
If you click again the html select element the dropdown doesn't open. (It needs 2 clicks).
I will send this to the gecko issue

**Comment by tasosb** [comment] 2022-01-25 19:30
> It only partialy fixed the problem. The first click-select works fine. If you click again the html select element the dropdown doesn't open. (It needs 2 clicks). I will send this to the gecko issue

@samlux04 Can you check if this is happening to your version aswell?

**Comment by kbrosnan** [comment] 2022-01-26 07:25
@emilio are the last two comments known bugs?

**Comment by kbrosnan** [comment] 2022-01-26 18:53
Looks like the discussion happened in the bug and the last few comments are talking about bz-1752133
