### ISSUE TITLE
[Bug] copy action bar appears in the wrong place

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7460] opened 2020-01-02 04:34 UTC
## Steps to reproduce:
Go to any website with some text
long press on any word
### Expected behavior
copy action bar appears near the selected text
### Actual behavior
copy action bar appears at unrelated spot 
![Screenshot_20200102-095403](https://user-images.githubusercontent.com/33252312/71651892-fe788e00-2d18-11ea-9400-4c7f1fb6da4f.png)

### Device information

* Android device: Asus Zenfone 1
* Fenix version:
 Nightly 200101 18:01 (Build #20011807)
27.0.0, 23f7db96f
GV: 73.0a1-20191231094349

**Comment by sv-sdeiac** [comment] 2020-01-03 14:06
Closed as a duplicate of #6877

**Closed by sv-sdeiac** 2020-01-03 14:06 UTC
Labels: 🐞 bug
