### ISSUE TITLE
[Bug] Rectangle anchor on tabs drawer instead of pill

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#15323] opened 2020-09-22 20:55 UTC
## Steps to reproduce
1. Open tabs drawer.
2. Observe the anchor that denotes where you can put your finger to expand the tab drawer.

### Expected behaviour
 - The anchor should look like the default pill shape.

### Actual behaviour
 - The anchor looks like a rectangle instead which does not match the regular style (see screenshot below).

<img width="521" alt="Screen Shot 2020-09-22 at 4 50 44 PM" src="https://user-images.githubusercontent.com/1370580/93936504-4a7ac100-fcf4-11ea-9f6c-a38ec4aeffa9.png">

### Device information

* Android device: Android 11, Pixel 4
* Fenix version: Nightly 200922 06:07

**Comment by Octoton** [comment] 2020-09-22 21:11
Same for me on android 9

**Comment by cadeyrn** [comment] 2020-09-22 21:19
Duplicate of #15219.

**Comment by ekager** [comment] 2020-09-22 22:12
closing for #15219

**Comment by jonalmeida** [comment] 2020-09-22 22:13
Oh shoot, I thought I searched well enough to find any existing issue. 🤷‍♂️

**Closed by ekager** 2020-09-22 22:12 UTC
Labels: needs:triage, 🐞 bug
