### ISSUE TITLE
[Bug] Tracking protection icon disappears if disabled on website

### ISSUE THREAD

**Issue by ReekyMarko** [mozilla-mobile/fenix#5667] opened 2019-09-30 07:40 UTC
Steps to reproduce:

1. Go to any site
2. Disable tracking protection
3. Exit the tracking protection menu

Now the tracking protection icon is not visible in the address bar, and there is seemingly no way to turn it back on.

**Comment by Amejia481** [comment] 2019-09-30 13:16
Duplicate of https://github.com/mozilla-mobile/fenix/issues/5446

**Closed by Amejia481** 2019-09-30 13:16 UTC
