### ISSUE TITLE
Toolbar menu content should be consistent between new tab page and other pages

### ISSUE THREAD

**Issue by cartr** [mozilla-mobile/fenix#13780] opened 2020-08-13 06:19 UTC
### What is the user problem or growth opportunity you want to see solved?

Currently, the three-dots menu button on the toolbar presents two completely different-looking menus depending on if you're in the new tab page or a webpage. (The "new tab page" version of the menu has Help and What's New options, as well as a divider between Add-ons and History. The "webpage" version of the menu has Forward/Back/Reload/etc, and many additional options for saving and sharing the page.) To make the UI easier to understand, these menus should be the same, with options not applicable to the current context being greyed out instead of hidden.

### How do you know that this problem exists today? Why is this important?

This was a consistent source of frustration for me during my first couple days using Fenix -- I'd build up a little muscle memory in one menu, and then I'd open the other menu and need to rescan all the options again.

This issue is especially likely to create a bad user experience for people trying Fenix for the first time, making them more likely to give up and switch to a different browser.

### Who will benefit from it?

Imagine you've just downloaded Firefox for Android and are trying to figure out how it works. You open the app (arriving at the new tab page), you see a three-dot menu button on the toolbar, and you tap it. Later, when you're looking at a webpage, you tab the button again and get a completely different menu! What the heck!?

Imagine you have a question about how to use Firefox for Android. You vaguely remember that there's a Help option in the three-dot menu, so you open the menu and look for it. Unfortunately, you have a webpage open at the time, so you get the version of the menu that doesn't have a Help option. You conclude that Firefox for Android must not have help after all, so you switch back to Chrome, where help articles are readily available in the menu at all times.

**Comment by kbrosnan** [comment] 2020-09-09 22:06
closing as a duplicate of #14320

**Closed by kbrosnan** 2020-09-09 22:06 UTC
Labels: Feature:Toolbar
