### ISSUE TITLE
FNX-12521 ⁃ Add option to directly open a new tab on longpress on tabs icon

### ISSUE THREAD

**Issue by JVariance** [mozilla-mobile/fenix#11569] opened 2020-06-14 11:27 UTC
### What is the user problem or growth opportunity you want to see solved?
When longpressing the tabs icon, a menu opens up with the opportunity to either close the current tab, open a new tab or open a new private tab.
This is not really faster than clicking on the tab icon and afterwards clicking on the new tab/plus button.

Instead Firefox could include an option in settings to either open the menu or directly open a new tab based on the mode the user is in (normal or private).

### Who will benefit from it?
Everyone, who wants to add new tabs the fastest way possible.

**Comment by cadeyrn** [comment] 2020-06-14 13:46
Duplicate of #11513.

**Comment by NotWoods** [comment] 2020-06-15 15:38
Closing as duplicate

**Closed** 2020-08-11 04:21 UTC
Labels: needs:triage
