### ISSUE TITLE
[Bug] Dark mode inconsistencies, toggles on its own 

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#20094] opened 2021-06-19 19:00 UTC
![Screenshot_20210615-180700_Firefox Nightly](https://user-images.githubusercontent.com/76437842/122652776-dd8c3e80-d140-11eb-80b7-fb9be3e2a44d.png)
![Screenshot_20210625-113243_Firefox Nightly](https://user-images.githubusercontent.com/76437842/123428557-3b4bdb00-d5c6-11eb-86fc-9046c3699771.png)

![Screenshot_20210619-110422_Firefox Nightly](https://user-images.githubusercontent.com/76437842/122653252-c00ca400-d143-11eb-9583-f8cfe5f299af.png)

![Screenshot_20210618-092226_Firefox Nightly](https://user-images.githubusercontent.com/76437842/122652787-eed54b00-d140-11eb-99bf-19ab28162719.png)
![Screenshot_20210615-180634_Firefox Nightly](https://user-images.githubusercontent.com/76437842/122652927-cdc12a00-d141-11eb-88f3-6a85108172a2.png)

 [comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Toggle Android dark mode, switch apps and/or go through phone standby 
### Actual behavior
Firefox, including Dark Reader add-on if present and configured, will toggle dark mode regardless of user action. Some elements remain dark, some white. Bad contrast it the result, presenting the user with illegible text, and a bad unpredictable experience

### Device information

* Device vendor / model and Android version: Samsung Galaxy device running OneUI 3.1 on Android 11
* Firefox for Android version: nightly 06-18

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11077)

**Comment by eliserichards** [comment] 2021-06-21 14:58
Possibly an issue with `android:fillColor="@color/mozac_ui_icons_fill"` for the icons

**Comment by lobontiumira** [comment] 2021-06-22 12:39
I was not able to reproduce this issue on the 6/22 Nightly 91.0a1 build.
Tested with Google Pixel (Android 10), and Samsung Galaxy Note 8 (Android 9).
I will ask my colleagues to try on an Android 11 device as well.

**Comment by SoftVision-LorandJanos** [comment] 2021-06-22 13:26
Hi @marcel263 ! I've tested with Android 11, and made a downgrade to the Nightly version you've used to log the issue. I can't reproduce the issue either. All seems well, both with dark theme and with Dark reader add-on. Could you try clearing the data and see if it still reproduces? Thank you!
Tested on the latest Nightly (91.0a1 Tuesday 6/22 @ 5:07 AM) and on Nightly (91.0a1 Tuesday 6/18 @ 5:07 AM).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Comment by marcel263** [comment] 2021-06-22 16:22
https://user-images.githubusercontent.com/76437842/122963608-b8890d00-d386-11eb-8391-e38b6b94499c.mp4

In this screencast, switching to Firefox triggers dark mode regardless of system settings.

**Comment by marcel263** [comment] 2021-06-22 16:25
https://user-images.githubusercontent.com/76437842/122963958-1158a580-d387-11eb-9b05-a04501f1fcbb.mp4

In this screencast, it is visible how system dark mode is enabled, with Firefox still disregarding it.

**Comment by marcel263** [comment] 2021-06-22 16:29
> Hi @marcel263 ! I've tested with Android 11, and made a downgrade to the Nightly version you've used to log the issue. I can't reproduce the issue either. All seems well, both with dark theme and with Dark reader add-on. Could you try clearing the data and see if it still reproduces? Thank you!
> Tested on the latest Nightly (91.0a1 Tuesday 6/22 @ 5:07 AM) and on Nightly (91.0a1 Tuesday 6/18 @ 5:07 AM).
> Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

Hello, thank you for to reply. While I firstly would like to point out the two screencasts above to demonstrate the spontaneous malfunction for future reference, I will test your suggestion.

**Comment by marcel263** [comment] 2021-06-26 14:57
> Hi @marcel263 ! I've tested with Android 11, and made a downgrade to the Nightly version you've used to log the issue. I can't reproduce the issue either. All seems well, both with dark theme and with Dark reader add-on. Could you try clearing the data and see if it still reproduces? Thank you!
> Tested on the latest Nightly (91.0a1 Tuesday 6/22 @ 5:07 AM) and on Nightly (91.0a1 Tuesday 6/18 @ 5:07 AM).
> Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).
To give you an update, the app reset did not solve the issue. Please see the screencasts above for a look on what happens.

**Comment by SoftVision-LorandJanos** [comment] 2021-06-28 14:55
Well, it still not reproduces on my end. However I encounter some other ones recently reported, but they are light theme based. The home icon is not visible (#20154) and The Site report issue also (#19558). I suspect they might be related to your issue.

**Comment by marcel263** [comment] 2021-07-04 14:01
Worth noting that it occurs often while video player Newpipe is in use

**Comment by sflorean** [comment] 2022-04-19 11:54
@marcel263 this is still reproducible? the above mentioned issues are fixed and verified.

**Comment by sflorean** [comment] 2022-06-15 13:04
Closing this based on the fact that a fix was landed and any new information wasn't added.

**Closed by sflorean** 2022-06-15 13:04 UTC
Labels: 🐞 bug, Feature:Themes, qa-triaged
