### ISSUE TITLE
[Bug] Sharing multiple tabs to another browser, only opens 1 tab

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#4178] opened 2019-07-19 12:44 UTC
## Steps to reproduce
1. Create a collection with a minimum of 2 pages.
2. Share the created collection to another browser.

### Expected behavior
All the pages from the created collection should be opened in the chosen browser.

### Actual behavior
Only the first page opens in the chosen browser.

### Device information
* Android device: all
* Fenix version: v1.1.0-rc.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12642)

**Comment by softvision-miralobontiu** [comment] 2019-07-23 12:13
Also reproducible if trying to share multiple opened tabs, not in a collection, through a browser; only the last tab is opened in the selected browser.

* Note: if sharing through Gmail, works as expected.

**Comment by jonalmeida** [comment] 2019-07-29 14:59
Forgot to reply to this earlier: this looks possible since we see Twitter sending different messages to different app types (Whatapp/Gmail/Instagram). We may need to have finer intent filters or add the multiple urls as a string array extra.

**Comment by pwd-github** [comment] 2019-10-11 07:30
Just came to report this. Perhaps the share icon on collections should be disabled until a plan of action is formulated?

**Comment by softvision-miralobontiu** [comment] 2019-11-29 12:29
Still reproducible on the latest Nightly build from 11/29.

**Comment by Diana-Rus** [comment] 2020-03-26 12:31
Hi, is still present on Firefox Preview Nightly 200326 (Build #20860605) GV: 76.0a1-20200324093140

**Comment by Diana-Rus** [comment] 2020-04-29 11:05
Hi, reproducible on Beta 5.0.0-beta.1- 4/29 with Google Pixel 3 XL (Android 9).

**Comment by softvision-miralobontiu** [comment] 2020-05-20 07:49
Still reproducible on Beta 5.1.0-beta.1 with Samsung Galaxy Tab S6 (Android 9).

**Comment by sv-ohorvath** [comment] 2020-07-07 08:24
@liuche Maybe this can be re-prioritized? It affects moving your collections from the old Nightly app to the new one.

**Comment by pwd-github** [comment] 2020-07-07 08:27
It's fixed in that now the problem is that there's no longer an issue of losing all the other tabs. That said, it would be nice to be able to "open all"

**Comment by softvision-miralobontiu** [comment] 2020-12-30 09:59
This issue is still reproducible on all versions of Fenix: 12/29 Nightly, Beta 85.0.0-beta.4, and RC 84.1.2.

**Comment by genodeftest** [comment] 2021-01-16 15:12
What happens:
Consider you have 3 tabs open, with `[URL0]`, `[URL1]`, `[URL2]`. Fenix will put them into a single string `[URL0]\n\n[URL1]\n\n[URL2]` with `\n` being the line feed character (`0x0A`). This is also what you can see when sharing multiple tabs with another app, e.g the Signal messenger.

What should happen:
Probably depends on the browser. Is there a standard for it? Firefox Desktop (at least on Linux) would expect the URLs to be separated by spaces instead of `\n`.

It looks like there could be two different approaches for fixing this issue:
1. Change the format Fenix uses to generate the strings to share an URL. This would need to be compatible with different apps though, which may be hard. In this example, we would need it to be compatible with messengers (somewhat human-readable) and applications like web browsers to recognize it as a list. Since URLs are usually long and messengers usually support line breaks, how about just separating the URLs by a single space instead of two line feeds? This *could* be compatible with most software out there.
2. Change the format Fenix and firefox Desktop accept URLs in.

See also this issue reported at KDE connect: https://bugs.kde.org/show_bug.cgi?id=431694

**Comment by lobontiumira** [comment] 2021-05-28 07:53
This issue still reproduces on all builds, with all devices.

**Comment by lobontiumira** [comment] 2021-09-09 06:56
This issue still reproduces on all the builds.

**Comment by WebworkrNet** [comment] 2021-10-22 03:09
This issue is still reproducible on 
94.0.0-beta.4 (Build #2015840411)
AC: 94.0.8, 3cf45a1dab
GV: 94.0-20211017185800
AS: 85.4.0

**Comment by SoftVision-LorandJanos** [comment] 2022-04-21 09:36
This issue is still reproducible.
Tested on the latest Nightly 101.0a1 (2022-04-21) build.
Device used: Google Pixel 4 (Android 12).

**Comment by ohhai** [comment] 2022-11-26 11:20
Does this bot require to retest it every time with no reasons?

**Comment by SoftVision-LorandJanos** [comment] 2022-11-29 14:59
Still reproducible on the latest Nightly 109.0a1 (2022-11-29).
Device used: Oppo Find X5 (Android 12).

**Comment by jonalmeida** [comment] 2023-01-17 02:45
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810646

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by jonalmeida** 2023-01-17 02:45 UTC
Labels: 🐞 bug, P3, needs:investigation, Feature:Collections, Feature:SendTab, S2, pin
