### ISSUE TITLE
Copy about:version to clipboard

### ISSUE THREAD

**Issue by superbonaci** [mozilla-mobile/fenix#18306] opened 2021-03-03 07:55 UTC
Add here option to copy information to clipboard:

![](https://i.imgur.com/cCvE951.jpg)

Like this:

![](https://i.imgur.com/Ptj532k.jpg)

Currently I have to use [Universal Copy](https://play.google.com/store/apps/details?id=com.camel.corp.universalcopy) to do the job.

**Comment by mcarare** [comment] 2021-03-03 10:00
Similar to https://github.com/mozilla-mobile/fenix/issues/18306, except the copy mechanism (long press vs button).

**Comment by superbonaci** [comment] 2021-03-03 10:11
At least be able to select text.

**Comment by superbonaci** [comment] 2021-03-03 10:12
@mcarare #18306 is this.

**Comment by anotherus3r** [comment] 2021-03-03 12:52
> At least be able to select text.

You should already be able to select it.

![Screenshot_20210303_135142.jpg](https://user-images.githubusercontent.com/20287690/109808688-b8260400-7c27-11eb-97ef-d98d3d7c8755.jpg)

**Comment by kbrosnan** [comment] 2021-03-03 18:32
Closing as a duplicate of #18306, The long press option is a cleaner solution.

**Closed by kbrosnan** 2021-03-03 18:32 UTC
Labels: feature request 🌟, needs:triage

**Comment by superbonaci** [comment] 2021-03-03 19:12
I see, the only portion that is selectable is the middle paragraph. Would like that I can select too first and third paragraphs.
