### ISSUE TITLE
Redundant 'plus'

### ISSUE THREAD

**Issue by 0xTyagi** [mozilla-mobile/fenix#7500] opened 2020-01-06 15:14 UTC
![IMG_20200106_203210](https://user-images.githubusercontent.com/59569506/71826864-eb5a1b00-3096-11ea-8477-cf80104e1bea.jpg)
### Why/User Benefit/User Problem
what is the purpose of '+' in menubar when urlbar and '+' do the same thing
### What/Requirements
Plus button may be removed 
### Acceptance Criteria (how do I know when I’m done?)

redundant plus sign removed.

**Comment by cadeyrn** [comment] 2020-01-06 15:42
Duplicate of #6409. And the plus icon will be replaced in #1063.

**Closed** 2020-01-06 16:32 UTC
Labels: 🌟 feature request
