### ISSUE TITLE
about:config settings NOT saved

### ISSUE THREAD

**Issue by TheToolGuy** [mozilla-mobile/fenix#19227] opened 2021-04-24 19:19 UTC
This started 6 weeks ago:

about:config settings are NOT saved !!!

Every single time I start Firefox Nightly I have to change a setting in about:config to be able to use Firefox... (security.enterprise_roots.enabled=true)
I need this setting because I use AdGuard app to filter ADS (I do not use the addon). AdGuard installs a completely valid certificate in system.

(6 weeks further and still saving settings is not fixed, should be simple!!!)

**Comment by cadeyrn** [comment] 2021-04-24 20:50
To quote https://github.com/mozilla-mobile/fenix/issues/18990#issuecomment-818894076

> This is a dupe of #3728 and fallout from [bz-1678191](https://bugzilla.mozilla.org/show_bug.cgi?id=1678191)

**Comment by TheToolGuy** [comment] 2021-04-25 11:02
> To quote [#18990 (comment)](https://github.com/mozilla-mobile/fenix/issues/18990#issuecomment-818894076)
> 
> > This is a dupe of #3728 and fallout from [bz-1678191](https://bugzilla.mozilla.org/show_bug.cgi?id=1678191)
> 
> > This started 6 weeks ago […] 6 weeks further and still saving settings is not fixed
> 
> Less than 3 weeks but okay…
> 
> > should be simple!!!
> 
> You could create a pull requests if it's easy to fix?

How is a  toggle hard to fix ???

**Comment by cadeyrn** [comment] 2021-04-25 18:44
I didn't say it's hard to fix. You said it's easy to fix. So I asked you if you don't want to create a pull request. You can only say that it's easy to fix if you know how to fix the issue.

**Comment by kbrosnan** [comment] 2021-04-26 07:34
Closing as a duplicate

**Closed by kbrosnan** 2021-04-26 07:34 UTC
Labels: needs:triage

**Comment by TheToolGuy** [comment] 2021-04-28 20:03
It is NOT a duplicate ....

security.enterprise_roots.enabled  is a TOGGLE ... but someone made the choice to reset this TOGGLE every single time the app is restarted ...

So either remove this setting completely or make it work again and SAVE the change the user made !

**Comment by m1chj** [comment] 2021-04-29 08:17
This is not a duplicate and I believe @TheToolGuy is right. I switched to working browser already but before uninstalling firefox beta I was having the same issue with **security.enterprise_roots.enabled** resetting back to **false** after not using the browser for a while on both my devices.

**Comment by cadeyrn** [comment] 2021-04-29 08:40
As quoted above it is a fallout of bz-1678191 and supporting this option is a duplicate of #3728. There is no point in having multiple issues for the same thing. And if you read #3728 you can read:

> Hopefully this sprint will add a toggle in the secret settings.

Therefore it was right to close it as a duplicate.

**Comment by TheToolGuy** [comment] 2021-05-14 19:06
> 
> 
> As quoted above it is a fallout of [bz-1678191](https://bugzilla.mozilla.org/show_bug.cgi?id=1678191) and supporting this option is a covered by #3728. There is no point in having multiple issues for the same thing. And if you have a look at #3728 you can read:
> 
> > Hopefully this sprint will add a toggle in the secret settings.
> 
> Therefore it was right to close it as a duplicate.

Why don't you tell the solution to this BUG ???

I found the 'Secret Settings' menu and enabled 'Use third party CA certificates'.
This setting is sticky, but hard to find for normal users, they will use another browser if this one misbehaves ...

![Screenshot_20210514-205907_Firefox Nightly](https://user-images.githubusercontent.com/42601723/118317288-245e9700-b4f8-11eb-9911-c13d1f66f756.jpg)
