### ISSUE TITLE
visual indication of bookmarks during autosuggestion

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#3918] opened 2019-07-07 00:23 UTC
### Why/User Benefit/User Problem
Currently there is no way to distinguish between bookmarks and history. Attached image. The red dot painted on the screenshot indicates a bookmark.
### What/Requirements
- When suggesting bookmarks, there should be a star where I drew the red dot or to the left of the site icon
![image_2019-07-06_20-14](https://user-images.githubusercontent.com/50635951/60762351-ce7f5500-a02b-11e9-97c0-b116063d00c1.jpg)

**Comment by ekager** [comment] 2019-07-08 01:47
Closing as a dupe of #2037.

**Closed by ekager** 2019-07-08 01:47 UTC
Labels: 🌟 feature request
