### ISSUE TITLE
Typing a URL, loading the page then quitting Fenix reverts to previous page on relaunch

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#22658] opened 2021-12-02 13:41 UTC
### Steps to reproduce

1. open a new tab & navigate to a URL eg bbc.co.uk
2. type a different URL eg arstechnica.com & hit Enter
3. type bbc.co.uk and hit enter to reload bbc site
4. type arstechnica.com again & hit Enter
5. wait for arstechnica.com to load
6. kill Fenix in the task switcher
7. relaunch Fenix
8. arstechnica appears briefly in the URL bar but then bbc.co.uk loads **<--- incorrect behavior**

This does not happen with a newly opened tab hence steps 1 and 2 to give the tab some history. But I think it does occur with any tab with history ie where navigation has previously occurred.

### Expected behaviour

arstechnica.com should load

### Actual behaviour

arstechnica.com appears briefly but then bbc.co.uk loads

### Device name

Galaxy M32

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

#2015848875  2021-12-01T05:13:00

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18790)

**Comment by SoftVision-LorandJanos** [comment] 2021-12-03 13:49
Hi @Cheap-Skate!
I was not able to reproduce this issue.
I tried the exact steps you described, then cleared the data for the browser and retook the same steps, then I tried with a different pair of pages and still couldn't reproduce.
I also tried it with pages loading completely and then by closing while loading as well, without the described result, except for the RC, where if I didn't let arstechnica.com load, after force-close and reload, bbc.co.uk was loaded.
Could you make a video of the issue?
Maybe try after a clear data, or see if you can find any detail that might have lead to this behavior.
Thank you!
Tested on the:
- latest Nightly (2021-12-03).
- latest Beta (95.0.0-beta6).
- latest RC (95.1.0).
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by Cheap-Skate** [comment] 2021-12-03 15:48
You are correct, I do not see it on a clean install. But I do see it on both my phones running Nightly. Perhaps it is related to one of my add ons or sync? I will try to find what's going on & will report back.

Thanks for checking

**Comment by Cheap-Skate** [comment] 2021-12-03 15:55
It's uBlock Origin. If I clean install Fenix Beta then try my STR from comment 0 it behaves correctly. But if I then install uBlock Origin and try the STR again I see the incorrect behavior.

Don't know if this is a uBlock or a Fenix issue.

(I used Beta because I do not want to mess up my Nightly setup. )

**Comment by boek** [comment] 2023-01-30 19:48
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813711

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-30 19:48 UTC
Labels: 🐞 bug, b:web-content, S3, needs:triage, qa-triaged
