### ISSUE TITLE
[Bug]: 'Customize homepage' button is missing on empty homepage

### ISSUE THREAD

**Issue by ris58h** [mozilla-mobile/fenix#28371] opened 2023-01-03 13:44 UTC
### Steps to reproduce

1. Turn off all homepage blocks in Settings > Homepage.
2. Open homepage. 

### Expected behaviour

'Customize homepage' button should be present.

### Actual behaviour

No 'Customize homepage' button is present.

### Device name

s10e

### Android version

android 12

### Firefox release type

Firefox

### Firefox version

108

### Additional information

May be related to https://github.com/mozilla-mobile/fenix/issues/28341

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22219)

**Comment by amocirean** [comment] 2023-01-03 14:15
Closing as duplicate of #28341 .

**Closed by amocirean** 2023-01-03 14:15 UTC
Labels: 🐞 bug, needs:triage
