### ISSUE TITLE
[Bug] Address bar covering the website content

### ISSUE THREAD

**Issue by victor-bayas** [mozilla-mobile/fenix#10973] opened 2020-05-28 02:34 UTC
## Steps to reproduce
1. Install and enable uBlock
1. Go to settings
1. Scroll down till the end
    1. Expected behavior
Full webpage is shown including the reset settings button, works correctly in Fennec 68
![Screenshot](https://user-images.githubusercontent.com/49411169/83091594-1f8fa180-a061-11ea-8df6-2c4dd8cd66f1.jpg)UNITO-UNDERSCORE!20200527-212424!UNITO-UNDERSCORE!Firefox!
    1. Actual behavior
The address bar is covering the reset settings button
![Screenshot](https://user-images.githubusercontent.com/49411169/83091635-359d6200-a061-11ea-8bed-ed8f0974b614.jpg)UNITO-UNDERSCORE!20200527-212324!UNITO-UNDERSCORE!Firefox Nightly!
    1. Device information

* Android device: SM-G970F Android 10 with OneUI 2.1
* Fenix version: Nightly 200527 18:16 (Build #2015742803)

PD: It also happens in VirusTotal scan results, hiding the rescan button

Sample URL: https://www.virustotal.com/gui/file/544ca9b28670dfece0d5c55a60de3f5230b91d5cfadeb84497409b4ef52dbb4f/summary

**Comment by sheikh-azharuddin** [comment] 2020-05-28 13:23
This happens in preference page too..(about: config).. it hides last element.

**Comment by victor-bayas** [comment] 2020-05-31 21:22
As a workaround you can set the address bar to the top

**Comment by usr-dot-com** [comment] 2020-07-19 12:17
> 
> 
> As a workaround you can set the address bar to the top

Not really a good workaround when the address bar at the bottom is one of the cool features that Firefox offers

**Comment by victor-bayas** [comment] 2020-09-25 22:53
The bug it's now present when using the address bar at the top, no workaround :(

**Comment by s-ankur** [comment] 2020-10-22 20:39
Duplicate of https://github.com/mozilla-mobile/fenix/issues/11858

**Closed** 2020-11-01 15:33 UTC
Labels: Feature:Toolbar, Feature:WebExtensions, 🐞 bug
