### ISSUE TITLE
[Collections] Options menu shouldn't scroll

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#3008] opened 2019-05-30 17:53 UTC
When opening the options menu in a collection when it's positioned near the bottom of the screen, the menu is cut off and the user is required to scroll to see the items. 

The menu should be shown in it's entirety and flushed to the bottom in this case. 

Actual behaviour: 
https://cl.ly/54749b546d73

Spec for correct placement:
![](https://user-images.githubusercontent.com/5992746/58652692-25359880-82e2-11e9-871a-43ea4bd55f2a.png)

**Comment by mheubusch** [comment] 2019-05-31 19:30
This is  a MVP blocker - the requirement is that if the menu gets cut off when positioned over the options icon, the menu should adjust to be flush to the bottom of the viewport in both portrait and landscape.

**Comment by topotropic** [comment] 2019-06-05 11:14
related: https://github.com/mozilla-mobile/fenix/issues/2825

**Comment by sblatz** [comment] 2019-06-20 20:51
I'm closing this as a dupe of https://github.com/mozilla-mobile/fenix/issues/2825

**Closed** 2020-08-26 20:47 UTC
Labels: Feature:Collections, P1, Release Blocker, implementation review, 🐞 bug
