### ISSUE TITLE
Home fragment items disappear with certain scroll

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#386] opened 2019-02-06 16:15 UTC
When you scroll down while touching just above the Fenix logo, the logo, menu item and the private browsing button all disappear.

![disappear 2019-02-06 08_14_55](https://user-images.githubusercontent.com/4400286/52355528-4eef4a80-29e7-11e9-8b15-3d975866eb63.gif)

**Comment by ekager** [comment] 2019-02-06 17:30
@boek maybe that new feature you grabbed from alpha3 is the thing that is causing this bug? We may have to wait for the newest motionlayout to fix this

**Comment by vesta0** [comment] 2019-03-18 03:46
Duplicate of #696

**Closed by vesta0** 2019-03-18 03:46 UTC
Labels: Feature:HomeScreen, 🐞 bug, 🙅 blocked
