### ISSUE TITLE
FNX3-16418 ⁃ [Bug] Too many 3-dots menus on the history list

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2570] opened 2019-05-16 17:42 UTC
## Steps to reproduce
Go to the history

### Expected behavior
Only on menu at the top right

### Actual behavior
There is one menu for each history entry, with only one option (delete). This could be avoided by swiping to delete. When history entries are selected, multiple menus are even less needed.

### Device information
* Android device: Galaxy A5
* Fenix version: 1.0.1920

**Comment by cadeyrn** [comment] 2019-05-16 18:26
There are few menu items which can be added, see #2435.

**Comment by Lululalu** [comment] 2019-05-16 18:52
@cadeyrn In this case, at least when multiple entries are selected, the multiple menus could be hidened.

**Comment by lime124** [comment] 2019-07-25 04:20
@topotropic to confirm that we intend to add additional items in the menu for history as per your comment: https://github.com/mozilla-mobile/fenix/issues/2435#issuecomment-494156479

in the case of multi-select of history items, we should be hiding the individual 3 dot menus from each item - it can cause confusion. i believe that is a bug?

**Comment by topotropic** [comment] 2019-07-26 14:40
yes, please hide the 3-dot list item menus for history and bookmarks when in multi-select

**Comment by mcarare** [comment] 2019-09-06 15:18
@lime124 Just to clarify: When an item is selected, we want to hide **it's** menu or menus for **all** items?

**Comment by topotropic** [comment] 2019-09-06 17:13
@mcarare please hide all 3-dot menus when in selection mode

**Comment by sv-ohorvath** [comment] 2019-09-19 13:55
Verified as fixed on Nightly 9/18.

**Comment by Lululalu** [comment] 2019-10-01 03:45
@sv-ohorvath unfortunately it's not fixed for me. When I select an entry in the history list some still exhibit the menus.

**Comment by mcarare** [comment] 2019-10-01 07:26
@Lululalu can you reproduce this also for Bookmarks, or it's just for History?

**Comment by sv-ohorvath** [comment] 2019-10-01 07:38
@mcarare I can reproduce that on both bookmarks & history.
@Lululalu thanks, I didn't notice that!

**Comment by AndiAJ** [comment] 2019-10-14 08:42
Hi, I've just checked on the latest **Nightly Build #12870607 from 14/10** using the following devices :
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

There's still a minor inconsistency when selecting one or more items from the history list.
The **3 dot menu is displayed for one** of the other (unselected) listed items.
On the other hand it seems to be **disappearing after navigating through the list**.

► Video One item selected
![20191014_1118241](https://user-images.githubusercontent.com/51314259/66738540-7603f300-ee77-11e9-9896-e6ba0f63a3f3.gif)

► Video Three items selected
![20191014_113225](https://user-images.githubusercontent.com/51314259/66738382-0aba2100-ee77-11e9-82cd-19016b18b1b9.gif)

@mcarare Please review the above the above mentioned matter. :)
I'll remove the QA needed label until further clarifications.

**Comment by boek** [comment] 2019-10-28 16:49
@mcarare ^^ :)

**Comment by AndiAJ** [comment] 2019-11-21 10:21
Hi, **still reproducible** on the latest **Nightly Build #13250607 from 11/21** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191121_121514](https://user-images.githubusercontent.com/51314259/69329223-5a9bbd00-0c59-11ea-8bfb-7c43d849ebe5.gif)

**Comment by mcarare** [comment] 2019-11-27 09:45
For QA: Please test in next Nightly. Please note that the favicon blinking issue will be investigated and addressed in the future!

**Comment by softvision-miralobontiu** [comment] 2019-12-02 09:50
Verified that the three-dot menus aren't displayed if one of the history listings is selected.
Tested with Huawei MediaPad M2 (Android 5.1.1), Google Pixel 3 (Android Q), and Nexus 5 (Android 6.0.1) on the latest Nightly build 191202.

**Closed** 2020-08-12 17:44 UTC
Labels: Feature:History, eng:qa:verified, eng:ready, feature request 🌟
