### ISSUE TITLE
[Bug] User able to take screenshots of private browsing activity when setting is off.

### ISSUE THREAD

**Issue by dsohn0** [mozilla-mobile/fenix#20211] opened 2021-06-30 23:40 UTC
Steps to reproduce:

0. In Settings>Private browsing, confirm "Allow screenshots in private browsing" is not selected. 
1. Open browser in incognito mode and go a page.  
2. Attempt to take a screenshot.
At such a page, a screenshot will not be taken and the user will get a message saying "Can't take screenshot due to security policy." 
3. Tap the tab button. User can now see all tabs including the link opened above.  Try to take a screenshot of the screen. The user will get the same rejection message as above.
4. Tap the non incognito tabs button. 
5. Open a new tab or open a tab open already. 
6. From this tab, tap the tab icon, then tap the incognito tab icon. Take a screenshot.

Issue: User is able to take screen shot of previews of open tabs. 

This issue is also present should the user open a new incognito tab instead of proceeding with step 4. 

Alt Step 4: Click the +Private button. A new incognito tab will open, with the url bar selected and keyboard open. 
5: Tap the down button to close the keyboard. 
6. Tap the tab icon. Take a screenshot. 

Issue: User is able to take screen shot of previews of open tabs.

Should the user open a new incognito tab, the issue persists only if the user closes the new tab without taking any actions without doing anything other than opening and closing the new tab. If the user opens settings, goes to a url, goes to the home screen and comes back, etc, user remains unable to take a screenshot.

Example screenshot of private mode. Note user can zoom into information inside the private tabs to get a better definition in the resulting screenshot.

![Screenshot_20210630-163825_Firefox](https://user-images.githubusercontent.com/35327408/124044258-dcb99f00-d9c1-11eb-85e1-1385674b744b.jpg)

Firefox 89.1.1

**Comment by Nickoriginal** [comment] 2021-07-01 05:57
Duplicate of #17855

**Comment by Nickoriginal** [comment] 2021-07-01 06:11
Your trick with keyboard works!

https://user-images.githubusercontent.com/85299944/124074500-3bc3f600-da4c-11eb-9547-83034f986159.mp4

**Closed** 2021-07-01 07:32 UTC
Labels: needs:triage
