### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by xpseudonym** [mozilla-mobile/fenix#16303] opened 2020-10-31 22:44 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
click through downlod procedure

### Expected behavior
download dialogue progresses to download item

### Actual behavior
download dialogue stalls with download progress line 'cycling' in pre-download state and doesn't progress to show download progress

### Device information
* Android device: LG-815
* Fenix version:
82.1.1 (Build #2015770923)
AC: 60.0.5, a1a471ddc
GV: 82.0-20201014125134
AS: 63.0.0

**Comment by anotherus3r** [comment] 2020-11-01 14:19
Duplicate of #16289

**Comment by kbrosnan** [comment] 2020-11-01 18:31
closing aas a duplicate

**Closed by kbrosnan** 2020-11-01 18:31 UTC
Labels: needs:triage, 🐞 bug
