### ISSUE TITLE
[Bug] tabs show about:blank after crash

### ISSUE THREAD

**Issue by damanteg** [mozilla-mobile/fenix#15046] opened 2020-09-13 15:18 UTC
[Bug] Firefox for android forgets tabs opened/crashes and changes the tabs I had opened to about:blank and I cannot restore them.

**Comment by s-ankur** [comment] 2020-09-13 16:19
Duplicate of #5478

**Comment by pocmo** [comment] 2020-09-15 09:07
This can happen if the content process crashes while the app is in the background. Afaik we only handle this in the app if the app is in the foreground. If it isn't then on the next resume there's no crash overlay that allows you to restore those tabs.

**Comment by eliserichards** [comment] 2020-09-15 21:41
@pocmo can we close this as a dupe of #5478?

**Comment by pocmo** [comment] 2020-09-16 08:55
I closed #5478. I would like to keep this one for specifically addressing the "about:blank after content process crash in the background" issue.

**Closed** 2021-09-18 23:24 UTC
Labels: 🐞 bug, wontfix
