### ISSUE TITLE
Keyword search on Firefox for Android

### ISSUE THREAD

**Issue by lle-git** [mozilla-mobile/fenix#15609] opened 2020-10-01 21:34 UTC
It would be useful to have keyword search on firefox for android.
It would be the same as and compatible with keyword search on firefox for desktop (same usage and synchronisation across devices possible).
Thanks.

**Comment by cadeyrn** [comment] 2020-10-02 06:32
Duplicate of #12099.

**Closed** 2020-10-07 17:11 UTC
Labels: needs:triage
