### ISSUE TITLE
FNX-12507 ⁃ [Bug] (regression) prefers-color-scheme no longer works

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#11556] opened 2020-06-13 16:00 UTC
### Steps to reproduce
1. make sure that you have the dark theme enabled
1. open https://bugzilla.mozilla.org

### Expected behavior
BMO has the dark theme.

### Actual behavior
BMO has the light theme.

It works as expected in Fenix 5.1.0 and is no longer working in Fenix Nightly. But it still works in Firefox Nightly on macOS.

### Device information
* Android device: OnePlus 7T Pro McLaren Edition with Oxygen OS 10.0.9 (Android 10)
* Fenix version: master branch revision 704fc6f9833ab41790f3f83a76e6b53dfb333fbc

**Comment by cadeyrn** [comment] 2020-06-13 17:17
Regressed by the last AC update.

Working: AC 45.0.20200610130052 with GV 79.0a1-20200609092134
Not working: AC 45.0.20200612130101 with GV 79.0a1-20200611093454

**Comment by emilio** [comment] 2020-06-15 11:29
https://bugzilla.mozilla.org/show_bug.cgi?id=1645770 fixes it. This should be closed as a dupe of that.

**Comment by cadeyrn** [comment] 2020-06-15 11:33
Thanks! I will close this issue once I verified that the fix works. 😊

**Comment by cadeyrn** [comment] 2020-06-17 20:40
I can verify that it's fixed now. Thanks!

**Closed** 2020-08-11 04:20 UTC
Labels: needs:triage, 🐞 bug
