### ISSUE TITLE
[Bug] Search auto-history-fill arrow doesn't do the expected action 

### ISSUE THREAD

**Issue by officiallor** [mozilla-mobile/fenix#14777] opened 2020-09-06 06:57 UTC
## Steps to reproduce
Go to search bar and search something similar that you have visited previously. For example github.com and you find that you want to go to /mozilla-mobile but you have on your search history only /mozilla-mobile/fenix. What you would normally do is that you would press the arrow and edit the link.

### Expected behavior
Show the URL github.com/mozilla-mobile/fenix on the search bar and then erase "fenix". 

### Actual behavior
Sometimes it displays the title of the page on the search bar and not the URL. When it displays the URL, when you try to erase, something unexpected happens when you press backspace: It selects the word again even if you have erased the previous part ![Screenshot_2020-09-06-09-53-49-491_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/8017707/92320034-08305f00-f027-11ea-87bc-a6e6347edbf5.jpg) 

### Device information

* Android device: Mi8 Android 10
* Fenix version: ?

**Comment by liuche** [comment] 2020-09-10 18:54
Dupe of #13768

**Closed by liuche** 2020-09-10 18:54 UTC
Labels: needs:triage, 🐞 bug
