### ISSUE TITLE
FNX2-15511 ⁃ when keypad is out, swiping anywhere switches the tabs

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12865] opened 2020-07-23 18:30 UTC
## Steps to reproduce
(Related to #3481)
Open the keypad e.g. write a comment for this issue
Swipe sideways anywhere

### Expected behavior
Scroll the page maybe

### Actual behavior
Changes tabs

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly 200723 06:01 (Build #22050611)
AC: 52.0.20200722023149, 5c2458cb8
GV: 80.0a1-20200721094241

**Comment by person808** [comment] 2020-07-23 18:44
Hi! I'm unable to reproduce this on my Pixel 2 XL running Android 10. Where on the screen are you swiping (over the text box/address bar/web page/etc?). If you are able to provide a screen recording with [show taps](https://www.skyneel.com/show-touches-in-android-phone) enabled that would be very helpful.

**Comment by person808** [comment] 2020-07-23 18:45
As a side note, we should disable the swipe to switch tabs when the keyboard is visible. Chrome does the same thing.

**Comment by s-ankur** [comment] 2020-07-23 18:52
@person808 Take a look

![GifMaker_lowquality](https://user-images.githubusercontent.com/33252312/88326454-aef4c080-cd43-11ea-9af9-f6e1690acb5b.gif)

**Comment by person808** [comment] 2020-07-23 18:54
Thanks! Weird that I can't reproduce. What Android version do you have?

**Comment by s-ankur** [comment] 2020-07-23 18:56
It's LineageOS with Android 9

**Comment by Augures01** [comment] 2020-07-23 19:05
Can reproduce on Samsung S6 Edge, Android 7.0

**Comment by hakkikaancaliskan** [comment] 2020-07-23 19:47
I'm able to reproduce on XZ1 with Android 10
Los 17.1

**Comment by madb1lly** [comment] 2020-07-23 20:40
Hi all,
I also have this bug with latest nightly on Nokia 8 with android 9.
Cheers 🙂

**Comment by person808** [comment] 2020-07-24 21:50
@hakkikaancaliskan Would you be able to post a recording as well? I tracked down the issue on older android versions but I still can't reproduce it on Android 10. If its an issue on Android 10 then we definitely need to disable the gesture when the keyboard is open which is unfortunately a harder task.

**Comment by hakkikaancaliskan** [comment] 2020-07-24 21:56
@person808 here is the video :)
http://imgur.com/a/B1L9BDJ

**Comment by s-ankur** [comment] 2020-07-25 18:49
It would be very helpful if this issue is prioritised. At the moment it is very difficult to type something and make corrections

**Comment by Neikon** [comment] 2020-07-26 09:51
this bug doesn't affect me.
https://www.youtube.com/watch?v=_Vx9v6PAGjo&feature=youtu.be&app=desktop

Oneplus 7, Andoird 10
Firefox Nightly 200725 06:01

**Comment by hakkikaancaliskan** [comment] 2020-07-26 09:57
@person808 please check my comment. I've edited it.

**Comment by staktrace** [comment] 2020-07-30 10:21
For the record I ran into this as well, and filed https://github.com//mozilla-mobile/fenix/issues/13112 for it (now closed in favor of this one). There's a video linked on that issue if you need it. Running android 9 on a Sony XZ1C.

**Comment by sflorean** [comment] 2020-07-30 13:24
Verified as fixed Nightly 7/30, with Google Pixel 3 (Android 11) and Huawei MediaPad M2(Android 5.1.1).
Note that I was able to reproduce the bug on affected Nightly builds.

**Closed** 2020-08-11 12:41 UTC
Labels: Feature:Gesture, Feature:IME, eng:qa:needed, eng:qa:verified, 🐞 bug
