### ISSUE TITLE
[Bug]: Autofill does not work on another apps

### ISSUE THREAD

**Issue by Disil** [mozilla-mobile/fenix#23707] opened 2022-02-13 13:58 UTC
### Steps to reproduce

1. Enable 'autofill in other apps' option in settings.
2. Go into a website, fill the log in form, and firefox will offers to save the password (Of course we need to save them so autofill work)
3. Go into another apps (in this case will be samsung internet)
4. Go to the same website that you already 'saved the password'. 
5. Press on the log in form

### Expected behaviour

An autofill menu should open or pop up to choose the credential

### Actual behaviour

Nothing, but in Samsung Keyboard there is button that says 'Unlock Firefox Beta' with fingerprint icon. When it is pressed, nothing happened.

### Device name

Samsung Galaxy A10s

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

98.0.0-beta.1

### Additional information

![Screenshot_20220213-205548_Via](https://user-images.githubusercontent.com/26422376/153756416-94bd559b-d9ab-4585-93b0-fdadd49e394c.jpg)
This is how the 'unlock firefox beta' button appeared. Notice how it is appeared in keyboard, and have a fingerprint icon on it. I don't have any kind of lock screen in this device.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19475)

**Comment by SoftVision-LorandJanos** [comment] 2022-02-15 06:48
Hi @Disil ! Thank you for your report!
I can confirm that your issue is reproducible.
The same "Unlock Firefox Beta" and "Unlock Firefox Nightly" (for Nightly) is displayed with no function on tapping.
Tested with the latest Nightly 99.0a1 (2022-02-15) and latest Beta (98.0.0-beta1).
Device used: Oppo Reno 6 (Android 11).

**Comment by Alexandru2909** [comment] 2022-02-18 08:29
Hi @Disil , since you mentioned that you don't have any screen lock type set up, the issue seems to be that we don't [handle](https://github.com/mozilla-mobile/android-components/blob/5d98bab2f9836d26a4cdbde8f0bddcfa98d1eee8/components/feature/autofill/src/main/java/mozilla/components/feature/autofill/ui/AbstractAutofillUnlockActivity.kt#L60) this case. Tagging UX to check how should we deal with the case when the user wants to use `Autofill in other apps` but no screen lock type is set.

**Comment by Disil** [comment] 2022-02-18 09:07
I set up a password, and it still doesnt work. It ask me to enter my pin, and then there is 'Search firefox beta' button appear. When i clicked on them, nothing happened.

**Comment by KazaHesto** [comment] 2022-03-07 15:46
I also have this issue, and have a lock screen enabled. Seems to only affect Nightly and Beta, Release has no issues

**Comment by Juriyx** [comment] 2022-03-09 23:35
Hi. I confirm this issue on all versions - the latest stable version (97.3.0), Beta (98.0.0-beta.4) and Nightly (100.0a1).
A button with fingerprint icon and "Unlock Firefox" text appears at the top of Gboard keyboard, I click on it and nothing happens. Touch to fingerprint on the right side of my smartphone (Poco F3) also doesn't give anything.

MIUI 12.5.6.0, Android 11

**Comment by Juriyx** [comment] 2022-03-09 23:48
My proposition is to remove the request for entering the password or fingerprint, because the device is already unlocked!

**Comment by Juriyx** [comment] 2022-03-10 18:06
Temporary solution is to use the Firefox Lockwise app. Yes, it is deprecated but I think that everyone can use it until the bug will be fixed.

**Comment by bananer** [comment] 2022-03-10 18:07
For me it was not working with Firefox Nightly but fixed after moving to stable.

**Comment by KazaHesto** [comment] 2022-03-10 23:19
Stable recently updated for me and that broke it
Annoying since I moved to stable to fix this

**Comment by Juriyx** [comment] 2022-03-10 23:22
> 

I do not argue with you, but on my configuration, autocomplete does not work with any version of Firefox

**Comment by Juriyx** [comment] 2022-03-10 23:23
> For me it was not working with Firefox Nightly but fixed after moving to stable.
I do not argue with you, but on my configuration, autocomplete does not work with any version of Firefox

**Comment by KazaHesto** [comment] 2022-03-10 23:29
> > For me it was not working with Firefox Nightly but fixed after moving to stable.
> 
> I do not argue with you, but on my configuration, autocomplete does not work with any version of Firefox

I didn't note down what version my stable was at, it's possible it was older than you tested? I'm using a Samsung Galaxy S21, Android 12, and the broken version of stable it just updated to is 98.1.1

**Comment by Juriyx** [comment] 2022-03-10 23:35
> it's possible it was older than you tested?

Maybe

**Comment by KazaHesto** [comment] 2022-03-11 02:22
Using builds from https://archive.mozilla.org/pub/fenix/nightly/ , the first bad build appears to be:

98.0a1 (Build #2015862031), bae20d650+
AC: 98.0.20220207143129, ec0201897a
GV: 98.0a1-20220206065831
AS: 91.0.1

2022-02-07T17:11:19.529657

**Comment by KazaHesto** [comment] 2022-03-11 04:43
Filed https://github.com/mozilla-mobile/fenix/issues/24199 since this issue seems initially focused on when there is no lock screen set up

**Comment by bananer** [comment] 2022-03-11 06:35
Just installed the update for Firefox stable and autofill stopped opening from other apps as well for me.

Was working on: 97.3.0 (Build #2015866875), aeec125a5+
AC: 97.0.13, 0465a6f809
GV: 97.0.2-20220304162637
AS: 87.1.0

Broken on: 98.1.1 (Build #2015866891), a44eb55a9+
AC: 98.0.11, 2250f94195
GV: 98.0-20220304153049
AS: 91.0.1

**Comment by amedyne** [comment] 2022-03-14 18:52
@Mugurell Can you check and validate if the changes referred to here https://github.com/mozilla-mobile/fenix/issues/23707#issuecomment-1064706930 is the cause?

**Comment by Disil** [comment] 2022-03-16 14:06
The 'unlock firefox beta' button has completely disappeared in the latest beta updates, 
99.0.0-beta.2 (Build #2015868713), 775895401+
AC: 99.0.2, 3bb1385eee
GV: 99.0-20220313185831
AS: 91.1.0

**Comment by bananer** [comment] 2022-03-17 06:38
I can confirm it's fixed in Nightly 100.0a1 (Build #2015869227)

**Comment by Juriyx** [comment] 2022-03-17 09:58
> The 'unlock firefox beta' button has completely disappeared in the latest beta updates,
> 99.0.0-beta.2

On my Poco F3, there is no such change

**Comment by Juriyx** [comment] 2022-03-17 10:01
> I can confirm it's fixed in Nightly 100.0a1 (Build #2015869227)

No changes, at least on my Poco F3

**Comment by Mugurell** [comment] 2022-03-17 17:18
@Disil @Juriyx After https://github.com/mozilla-mobile/fenix/issues/24199 one particular scenario should be fixed - that selected logins are actually autofilled.

If there are other issues we'd need complete steps to reproduce (including the login url / app in which login is not autofilled and a video) to be able to investigate the same exact scenario.

Regarding the scenario described for this ticket - https://github.com/mozilla-mobile/fenix/issues/23707#issue-1135892267 I now tested on Fenix v97 (before the regression now fixed in https://github.com/mozilla-mobile/fenix/issues/24199) and saw there also that indeed autofill does not work in Samsung Browser. Neither in Chrome. So in this case indeed the fix from https://github.com/mozilla-mobile/fenix/issues/24199 would not help.
I remember https://github.com/mozilla-mobile/fenix/issues/21942#issuecomment-944314757 about how our functionality is not compatible with Chrome, it seems to be the same with Samsung Browser (which is based on Chromium).

**Comment by Juriyx** [comment] 2022-03-17 20:51
> one particular scenario should be fixed - that selected logins are actually autofilled.

As I wrote earlier, I didn't get to this step, because tap on the button "Unlock Firefox" does nothing. This is the main problem in my case.
Checked in TeamViewer app, for example, but it doesn't matter which app I choose to test.

P. S. I thought that this topic is about entering passwords in other applications, but I have no need to enter passwords using Firefox in other browsers. This is some strange scenario 😀 (IMHO)

**Comment by Disil** [comment] 2022-03-17 23:16
> P. S. I thought that this topic is about entering passwords in other applications, but I have no need to enter passwords using Firefox in other browsers.

Well for users who swapped browsers daily (between Firefox and other browser) this is a problem. I test the autofill again on Via Browser and it shows the Unlock Firefox button, and as always, it does nothing.

**Comment by Mugurell** [comment] 2022-03-18 07:12
I'd say from a user standpoint it is reasonable to expect the autofill feature from Fenix to work in any installed apps.
Though because this is a highly complex functionality with multiple apps involved and system features also, it seems like there may be different issues which need to be investigated separately.

I'll take Samsung Browser just as an example of where an autofill issue reproduces and note that for the moment we can't support that.
For reports about "Unlock.." not working I'll need more details to be able to reproduce:
- device model and android version
- the current current screen lock set in system settings (we do not currently support "no lock")
- the 3rd party application in which autofill is tried

**Comment by Mugurell** [comment] 2022-03-18 07:16
@Disil If as per the first comment you don't have any screen lock set then at this time autofill is expected to not work - https://github.com/mozilla-mobile/android-components/issues/9756

@Juriyx Is this the same situation for you - no screen lock set? 

Would appreciate if just for test you could set another screen lock method and report back.
Just want to understand the exact scenarios we need to fix.

**Comment by Disil** [comment] 2022-03-18 07:47
> * (we do not currently support "no lock")

@Mugurell I set up pin screen lock. And at first I thought it will work, because it ask me to insert my pin. After that there's a button that says "Search Firefox Beta' which is useless. When pressed, it disappear and nothing happens.

> * the 3rd party application in which autofill is tried

I tried it on a bunch of browser, even trying them on Firefox Release and Nightly, it still does nothing.

**Comment by Mugurell** [comment] 2022-03-18 08:11
> > * (we do not currently support "no lock")
> 
> @Mugurell I set up pin screen lock. And at first I thought it will work, because it ask me to insert my pin. After that there's a button that says "Search Firefox Beta' which is useless. When pressed, it disappear and nothing happens.

Can you please try the same scenario in the current Firefox Nightly?

**Comment by xatr0z** [comment] 2022-03-18 09:25
I'm experiencing the same problem on a new phone (old one was still using lockwise besides firefox though).

After installing Firefox NIghtly (*and* switching autofill app to nightly instead of normal firefox);
* One app which AFAIK didnt work before (Twitter) shows my username, after clicking on it it fills user+password
* But most apps still have the same issue (ie Nextdoor); sometimes the acounts are visible less then a second after which they disappear and only the *Search Firefox Nightly* option is available. But clicking this doesnt do anything
* Other app (nl.ouderportaal.ouderapp) shows an account but gives the old 'Verification failed' popup, no information is autofilled

**Comment by Mugurell** [comment] 2022-03-18 09:51
@xatr0z 
> Other app (nl.ouderportaal.ouderapp) shows an account but gives the old 'Verification failed' popup, no information is autofilled

The "Verification failed" might be expected, it being part of the current functionality as another important step to secure credentials access - https://github.com/mozilla-mobile/android-components/issues/9777, https://github.com/google/digitalassetlinks/blob/master/well-known/details.md
I'd expect other password managers to show a similar dialog when first trying to autofill in that specific app.

Seems like that app need a certain url first entered before the username+password pair so I can't easily test now.
Does clicking "Yes" in the "Verification failed" dialog autofills the credentials?

**Comment by xatr0z** [comment] 2022-03-18 09:55
@Mugurell Unfortunately no,  after clicking yes nothing happens (same as next door)

For other readers. As suggested elsewhere I'm currently using lockwise so I can reach my passwords without manually looking up each app.

**Comment by Juriyx** [comment] 2022-03-18 12:13
> Is this the same situation for you - no screen lock set?
> 
> Would appreciate if just for test you could set another screen lock method and report back. Just want to understand the exact scenarios we need to fix.

I have a PIN and fingerprints set. I will check with a password only.

**Comment by DiegoARL38** [comment] 2022-03-18 16:58
Came from #24199.

When tapping the Unlock Firefox Nightly button while in a login field, nothing happens. The focus returns to the input field and the Unlock Firefox Nightly button reappears.

As an aside, I use TalkBack as my screen reader.

* Firefox Nightly 100.0a1 2022-03-18T05:08:55.900797.
* Xiaomi Redmi Note 8 with MIUI 12.5.1.0, Android 11.
* TalkBack version 12.1.
* Apps tested: Twitter, Reddit.
* Unlocking methods set: pin, fingerprint.

**Comment by Juriyx** [comment] 2022-03-19 16:46
The same situation with a password only

**Comment by DiegoARL38** [comment] 2022-03-26 06:14
I managed to get it working thanks to @mike-pt in this [#24423 comment](https://github.com/mozilla-mobile/fenix/issues/24423#issuecomment-1079584213).

Sadly, after unlocking, no login suggestions appear. Fortunately, going to another screen in the app, going back to the login screen, and tapping the username field makes a Search Firefox Nightly button appear, and tapping it displays the Firefox's login search UI.

Tested in both Twitter and Reddit.

I'd recommend adding a message to inform users of the possible need to give the Display popup windows while running in the background permission when enabling autofill in other apps in Firefox settings. I wouldn't have known to do it, nor that it is needed in my device or use case.

**Comment by plwt** [comment] 2022-07-21 20:31
User feedback:- https://support.mozilla.org/en-US/questions/1383349

**Comment by hien4990** [comment] 2022-11-11 11:02
me not work either i tested with tecnopova 2 and lenovo tab m10 gen 3

**Comment by Antorell** [comment] 2022-11-20 20:27
Firefox's autofill doesn't work, still. I'm using it on a Xiaomi Redmi 11 note NFC with Android 11 Using Firefox 107.1.0 or the current Android Beta. It asks for a fingerprint to unlock Firefox that doesn't do anything. And there's no visible option to disable the fingerprint to unlock security measure. Otherwise the autofill works fine with Microsoft Authenticator, Edge or Google Chrome.

**Comment by Mugurell** [comment] 2023-01-12 17:44
The above reports are a bit old.
For everyone who still sees this issues: can you please add here
- the Firefox version used
- the keyboard used
- the device used: model and Android version
- in which 3rd party application you are trying to autofill?

Testing this for myself I saw that:
- On a Samsung S7 with Android 8 autofill popup for Fenix / Google or Bitwarden.
- On both: 
    - OnePlus 7 with Android 11 and the GBoard keyboard
    - Pixel 7 with Android 13 and the GBoard keyboard
the inline autofill does work as expected:


https://user-images.githubusercontent.com/11428869/212140382-b589fc7e-5d52-4406-bb9c-775349ea2d8e.mov

**Comment by Antorell** [comment] 2023-01-12 18:11
Firefox doesn't ask to save passwords in android app when it's set as default Autofill on my phone.

I just tested it right now as I wrote the reply on:
Firefox Android 108.2.0
Microsoft Swiftkey Keyboard
Redmi Note 11 NFC (EU version V13.0.2.0.SGKEUXM) - MIUI 13 with Android 12
Microsoft Authenticator

I use Microsoft Authenticator to Autofill, I've also used Chromium Edge for Android. Both don't have any issue to suggest passwords in app, and they both ask to save passwords when I enter a password that's not in the list of saved site/pass password.

**Comment by delia-pop** [comment] 2023-01-13 15:27
Tested on the latest Nightly 110.0a1 from 01/13 with Xiaomi Redmi Note 8T (Android 11). I was able to log in to Twitter without issues using the saved logins from Fenix. Both passcode and fingerprint unlocking methods were used. 

https://user-images.githubusercontent.com/89388888/212356372-d930037d-f4c7-44c4-9e41-4472af8562ca.mp4

**Comment by SoftVision-LorandJanos** [comment] 2023-01-16 12:31
I couldn't reproduce the issue on the latest nightly 110.0a1 (2022-01-16) build, using a Xiaomi Mi11 Lite (Android 11).
Autofill worked as expected.

**Comment by Mugurell** [comment] 2023-01-16 13:02
Thank you all for the reports!
Looks like this issue was resolved based on the above reports and the ones from https://github.com/mozilla-mobile/fenix/issues/24199 with https://github.com/mozilla-mobile/android-components/pull/11893 fixing an issue with autofill not working immediately after unlocking Firefox from the keyboard and as such I will close this ticket.

**Closed by Mugurell** 2023-01-16 13:02 UTC
Labels: 🐞 bug, Feature:Logins, qa-triaged, Needs-UX

**Comment by Antorell** [comment] 2023-01-16 13:04
What about Firefox not asking to save passwords?

https://user-images.githubusercontent.com/25066224/212684816-620e299e-3aaf-4975-b14d-40cb7baec602.mp4

**Comment by Mugurell** [comment] 2023-01-16 13:05
For the scenario from https://github.com/mozilla-mobile/fenix/issues/23707#issuecomment-1380804471 - Firefox recognizing user entered credentials in other apps @Antorell please open a new ticket showcasing the functionality present in other applications.
Note that Firefox will recognize credentials entered when browsing with Firefox and Microsoft Edge might do the same but I am not sure that a password manager can recognize credentials being entered in a third party application to offer to remember them.
