### ISSUE TITLE
Tab displays content from another tab

### ISSUE THREAD

**Issue by davidrpk** [mozilla-mobile/fenix#24563] opened 2022-04-02 02:52 UTC
### Steps to reproduce

This happens occasionally and despite this happening for a long time I haven't figured out how to reproduce. 

1. Open tab and browse to web page. While it is loading switch to another tab 
2. In second tab, browse to a different web page
3. Switch back to first tab 
4. Switch back to second tab.
5. Second tab will have loaded url for first tab

The key seems to be switching between tabs while they are still loading.

This does not seems to be specific to any particular URL as it appears to happen with random websites. 

This also occurs in the non-beta release type.

### Expected behaviour

In the example shown in the video, the first tab in the list should be showing the pbtech website (as demonstrated in the third tab in the list)

### Actual behaviour

Pressing the refresh button either does nothing (ie: still shows incorrect page) or causes a blank page. Editing the url of the tab either does nothing (ie: still shows incorrect page) or results in a blank page.

In the following video you can a tab showing the wrong contents:
The first tab in the list is showing the contents of the URL of the second tab in the list. 
The third tab in the list is what the first tab in the list  should be showing.

Video: 

https://user-images.githubusercontent.com/20670590/161362832-73d3e6f0-9b96-48fe-a731-725f31db526e.mp4

### Device name

Samsung A70

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

99.0.0-beta.5 (Build #2015870731), 288604bf2+ AC: 99.0.7, c4546a1c69 GV: 99.0-20220324185704 AS: 91.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20036)

**Comment by marcel263** [comment] 2022-04-02 22:15
Reproducible. Only fix is to completely close the tab and load the URL manually again. Either the tab contents get mixed or the screen stays empty.

**Comment by kbrosnan** [comment] 2022-04-04 18:45
@MozillaNoah would you have a look and see if there is some logging or debug info we can get here?

**Comment by MozillaNoah** [comment] 2022-04-05 21:42
Hey everyone, just wanted to provide a quick update. I'm still looking into this and it's proving to be a bit tricky to pin down. @davidrpk, the next time this occurs, could you possibly check to see if there was a silent crash and post whatever you see here? 

You can check for these by either navigating to this url in Firefox (about:crashes) or going to Settings -> About Firefox Fenix -> Crashes.

Thanks for your patience with this! I might need to upload a custom APK which has some extra logging to help track down the culprit.

**Comment by davidrpk** [comment] 2022-04-05 22:13
Sure no probs. Let me know how I can help.

**Comment by davidrpk** [comment] 2022-04-07 22:05
It happened again today. I can confirm that there were no new crashes listed in the logs.
I was paying a bit more attention this time about what I was doing so I have a bit more information about how it was triggered:

1. Creating a new tab, 
2. Entered a URL and hit Go
3. The progress bar appeared to start loading the page
4. While the page was loading, I switched to a different application
5. I switched back to Firefox
6. I was presented with a blank tab with no progress bar (the correct behaviour would be to display the page which was loading, or at least attempt to reload the URL)
7. Switched to a different tab in Firefox (which already had a loaded page)
8. The existing page reloaded successfully
9. Switched back to broken tab and it displayed the content of the tab which had just successfully reloaded.

**Comment by marcel263** [comment] 2022-04-08 05:26
It should be added that the disabling of "optimize battery usage" for Nightly had no effect on reducing the prevalence of this bug on a similar Samsung phone.

**Comment by MozillaNoah** [comment] 2022-04-28 21:38
Hi everyone, just popping in for another update from my end. I've spent a few hours on just trying to reproduce this, and have only done so once by using an emulator with the app version listed in the bug (v99 beta 5) and throttling the internet. 

@marcel263, would you be willing to share what version of Firefox you've been using while experiencing this bug?

For anyone wanting to help track this down, I've uploaded some [custom debug APKs to Google Drive](https://drive.google.com/drive/folders/10axxha2yMNQXkiR7fxt98whsxek7PisS?usp=sharing) which have some additional logging to potentially help get to the bottom of this. Huge thanks in advance for anyone willing to install this and post some logs. (For transparency, I've added screenshots of the logs below)

In the meantime, I'll continue to investigate this. Thanks for your patience with all of this!

**Fenix.AbstractBrowserTabViewHolder.setSelectionInteractor()**
![Screen Shot 2022-04-28 at 11 23 55 AM](https://user-images.githubusercontent.com/87384386/165849111-0beab135-43eb-4010-bcb4-8f3b009da2d6.png)

**AC.EngineViewPresenter.renderTab()**
![Screen Shot 2022-04-28 at 11 25 57 AM](https://user-images.githubusercontent.com/87384386/165849140-5eff803d-9b99-4b9e-afa0-ebd3c3965b94.png)

**Comment by mduchev** [comment] 2022-10-10 08:13
Isn't this a duplicate of https://github.com/mozilla-mobile/fenix/issues/20737

**Comment by mcarare** [comment] 2022-10-11 16:05
> * The existing page reloaded successfully
> * Switched back to broken tab and it displayed the content of the tab which had just successfully reloaded.

@mduchev Sorry to ask this so late after the fact. When you say the broken tab displayed the tab content it was the image of the previous tab, or could you actually interact with the elements on the page? I suspect the tab was irremediably broken and you saw only the screenshot of the previous page. Thank you for your input on this issue!

**Comment by mduchev** [comment] 2022-10-11 17:57
@mcarare Can't say for sure, since I'm not entirely sure how to reproduce it and test it now. Pretty sure that I cannot interact and the I see only a "snapshot" of the page. I can't refresh it as well.

**Comment by mcarare** [comment] 2022-10-18 17:32
eng note: I managed to reproduce this issue. 

- The tab that ends up in this state has content that you can interact with, but it is not the original loaded URL (that keeps showing up in the toolbar and tab title). It also receives the content of the last visited "valid" tab, so it does not just render another tab, but the last normally loaded.
This behavior is similar to the one described [here](https://github.com/mozilla-mobile/fenix/issues/27427#issuecomment-1280098184).

- `TabSessionState` is identical to the state when the tab displayed the expected content.

**Comment by Rob--W** [comment] 2022-10-26 16:48
FYI: I reported an issue with the same symptoms as this bug, but a 100% reproduction rate at https://bugzilla.mozilla.org/show_bug.cgi?id=1797558 (which in turn was originally filed at https://github.com/uBlockOrigin/uBlock-issues/issues/2271).

**Comment by boek** [comment] 2022-11-21 18:35
Investigating this with @zmckenney using the steps to reproduce in [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1797558). We were able to reproduce this issue in the GeckoView sample app, so it's possible that Fenix / AC is also not responsible with this issue.

**Comment by boek** [comment] 2023-01-26 23:34
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812857

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-26 23:34 UTC
Labels: 🐞 bug, Feature:Tabs
