### ISSUE TITLE
[Bug] Dark theme not working properly on hold back button extended history

### ISSUE THREAD

**Issue by Apache77** [mozilla-mobile/fenix#17140] opened 2020-12-19 02:30 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Set theme to dark, open new tab, browse multiple links, long press back button. 
### Expected behavior
Dark theme should be applied on the list
### Actual behavior
Light theme background remains but site title names are also set to white color as they should be when dark theme is active - unable to read title names
![Screenshot_20201219-043459__01](https://user-images.githubusercontent.com/76235260/102678867-dd23e280-41b3-11eb-9d3a-3cb7764b6883.jpg)

### Device information

* Android device: OnePlus 3 android 9
* Fenix version: 84.1.1 (Build #2015781795)

**Comment by Doctor-Abhi** [comment] 2020-12-19 04:08
> ## Steps to reproduce
> 
> Set theme to dark, open new tab, browse multiple links, long press back button.
> ### Expected behavior
> 
> Dark theme should be applied on the list
> ### Actual behavior
> 
> Light theme background remains but site title names are also set to white color as they should be when dark theme is active - unable to read title names
> ![Screenshot_20201219-043459__01](https://user-images.githubusercontent.com/76235260/102678867-dd23e280-41b3-11eb-9d3a-3cb7764b6883.jpg)
> ### Device information
> 
>     * Android device: OnePlus 3 android 9
> 
>     * Fenix version: 84.1.1 (Build #2015781795)

Duplicate of #16422 , Fixed in latest nightly and 85.0.0-beta1 and 2

**Comment by mcarare** [comment] 2020-12-22 15:44
Closing as duplicate. The issue is already fixed in Nightly.

**Closed by mcarare** 2020-12-22 15:44 UTC
Labels: needs:triage, 🐞 bug
