### ISSUE TITLE
[Bug] "Share image" menu shares the link to the image instead of actual image (see Brave browser for correct behaviour)

### ISSUE THREAD

**Issue by ANSI-C** [mozilla-mobile/fenix#17488] opened 2021-01-15 14:24 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
go to any website with images, long press an image and select "share image" to share with another application

### Expected behavior
the image itself, unchanged, should be shared

### Actual behavior
the textual link to image is being shared instead
### Device information

* Android device: yes
* Fenix version: Firefox Daylight 84.1.4

**Comment by Dunexus** [comment] 2021-01-15 14:54
Duplicate of https://github.com/mozilla-mobile/fenix/issues/12414

**Comment by mcarare** [comment] 2021-01-15 18:01
Closing as duplicat of https://github.com/mozilla-mobile/fenix/issues/12414.

**Closed by mcarare** 2021-01-15 18:01 UTC
Labels: needs:triage, 🐞 bug
