### ISSUE TITLE
FNX2-15318 ⁃ [Bug] Search engine issues on non-EN locales

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#12544] opened 2020-07-14 12:02 UTC
## Steps to reproduce
Scenario 1:

1. Set the device language to Russian.
1. Clean app install, open the app.
1. Observe the default search engine on the first run.
1. Restart the app. Observe the search engine.
    1. Expected behavior
For some non-EN locales, the default engine should be Yandex or Baidu(?).
    1. Actual behavior
On first launch, the engine is set right as Yandex. After a restart, it got changed to Google.

Scenario 2: From https://github.com/mozilla-mobile/fenix/issues/11875#issuecomment-658015456

### Device information
* Android device: Pixel 4 (Android 10)
* Fenix version: 79.0-beta6.

**Comment by s-ankur** [comment] 2020-07-14 18:25
Related #12236

**Comment by sv-ohorvath** [comment] 2020-07-17 07:08
We've verified the fix on Nightly 7.17 and both scenarios work now as expected.

**Comment by Mugurell** [comment] 2020-08-12 07:23
Closing as per https://github.com/mozilla-mobile/fenix/issues/12544#issuecomment-659911359

**Comment by boek** [comment] 2020-09-17 20:50
@sv-ohorvath I believe this is working as intended.

When we moved to MLS to determine the set of search engines to use it caused some performance issues due to having to wait for a network request to select the region. So as a work around we load a fallback set from the device locale until that request is completed which looks like what you're experiencing here

**Comment by sv-ohorvath** [comment] 2020-09-18 09:40
So, to clarify: before this, having the device language set to Russian was setting Yandex as default and kept it that way. And now this will be the expected behavior?:
> Actual behavior
>     On first launch, the engine is set right as Yandex. After a restart, it got changed to Google.

**Comment by boek** [comment] 2020-09-18 17:39
@sv-ohorvath Correct, If Google is the default browser for the region you tested in (by using MLS) it will override the search engines set by your devices locale

**Comment by sv-ohorvath** [comment] 2020-09-21 09:40
I see the revert was merged into Nightly so I've verified the following cases:
- VPN region set to Turkey, device language EN: Google search engine at first run and after a restart
- VPN set to Turkey, device language TR: Yandex search engine at first run and after a restart
- VPN set to Romania, device language TR: Yandex search engine at first run and Google after a restart
- VPN set to Romania, device language EN: Google search engine at first run and after a restart
@boek if that looks good, should I close this issue now?

**Comment by amedyne** [comment] 2021-01-07 04:39
@sv-ohorvath Closing this per comments last September 21.

**Closed by amedyne** 2021-01-07 04:39 UTC
Labels: E3, Feature:HomeScreen, Feature:Search, S1, eng:qa:verified, 🐞 bug
