### ISSUE TITLE
[Bug]Login Sync engine should be OFF by default for new users

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6737] opened 2019-11-21 13:30 UTC
## Steps to reproduce
1. Sign in to sync with a **newly created account**
2. From Settings navigate to your Account and wait for the sync to end
3. Check the "Logins" check box from the "Choose what to sync" section
4. From Settings navigate to "Passwords" 
5. Check the "Sync logins" status

### Expected behavior
The "Logins" check box from the "Choose what to sync" section should **not be checked** after the first sync.
The Sync logins" status should be **set to OFF**.

### Actual behavior
The "Logins" check box from the "Choose what to sync" section **is checked** after the first sync.
The Sync logins" status is **set to ON**.

### Device information

* Android device: Google Pixel 3a XL (Android 9)
* Fenix version: Nightly Build #13250607 from 11/21

### Notes
► Video
![20191121_151739](https://user-images.githubusercontent.com/51314259/69342197-af4c3180-0c73-11ea-9dab-81a4d798696c.gif)

**Comment by liuche** [comment] 2019-11-21 17:25
@AndiAJ just to be clear, "Newly created account" should be "account created through Fenix", not pairing an account newly created on Desktop. Let me update the AC to be more clear, sorry for the confusion.

Could you retest with that condition?

**Comment by AndiAJ** [comment] 2019-11-22 07:25
@liuche indeed, the account was created and accessed **exclusively through Fenix**

As you can see in the video after creating the account, I've entered the verification code and afterwards the **first sync** kicked in automatically (**Last synced:never**)

**Comment by Baron-Severin** [comment] 2019-12-10 23:48
@AndiAJ I think this one is actually working as intended.  When I create an account from Fenix I'm taken to the attached page, and the "Account settings" screen is respecting whatever choices I make there.  Would you mind verifying this behavior?

![choose-sync](https://user-images.githubusercontent.com/13170306/70579073-6695e300-1b64-11ea-95f3-6d5640fa9cb4.png)

**Comment by AndiAJ** [comment] 2019-12-12 13:40
Hi @Baron-Severin , this doesn't happen in my case, the above mentioned "Account settings" screen isn't displayed, on the latest Nightly Build #13460608 from 12/12

► Video
![20191213_144445](https://user-images.githubusercontent.com/51314259/70714661-46475f00-1cf1-11ea-940f-f0044ab65aaf.gif)

Another worth mentioning matter are the differences between Fennec and Fenix, namely, when the user adds and confirms the password and age for the newly created account.

► Fennec RC (Choose what to sync is displayed)
![rsz_screenshot_20191213-150109](https://user-images.githubusercontent.com/51314259/70715041-1a78a900-1cf2-11ea-9281-d0f7598131a3.png)

► Fenix 
![rsz_screenshot_20191213-150051](https://user-images.githubusercontent.com/51314259/70715218-793e2280-1cf2-11ea-9c13-0f279e6e2a2c.png)

Please review and share your thoughts on these matters. :relaxed:

**Comment by Baron-Severin** [comment] 2019-12-12 17:40
@AndiAJ weird!  I'm glad I took a screenshot or I would think I was going crazy, because I no longer see the flow I described either.  Do you know if we have any documentation describing the expected behavior here?  It seems to me that we will need to reach out to AS to either change the flow so that the user can select what to sync, or update the default to not include logins.

**Comment by ekager** [comment] 2019-12-16 20:34
Hi all - I talked to @vladikoff and it seems that we should be able to see the screen that @Baron-Severin saw. It looks like Nightly is not showing it, but stable is? Explains why you saw it once while testing possibly @Baron-Severin :)

**Comment by rfk** [comment] 2020-02-10 01:15
Howdy folks. I stumbled across this bug and just wanted to flag that I consider it a pretty serious issue - Firefox Accounts show be offering the "choose what to sync" screen during the signup process for all new users who are connecting to sync, but from the discussion above it sounds like that may be broken in the latest Fenix nightly.

I've filed a corresponding bug on the FxA side to investigate what's happening here: https://github.com/mozilla/fxa/issues/4084

**Comment by vladikoff** [comment] 2020-02-11 20:42
cc @grigoryk https://github.com/mozilla/fxa/issues/4084#issuecomment-584841181

**Comment by ekager** [comment] 2020-03-06 07:10
Closing this Fenix issue and hopefully CWTS should work for all channels now from https://github.com/mozilla/fxa/issues/4084 landing

**Comment by AndiAJ** [comment] 2020-03-10 09:40
Hi, @ekager I've just checked this matter on the latest **`Nightly Build #20700607 from 03/10`** using the following devices:
• Google Pixel 4XL (Android 10)
• Google Pixel 3a (Android 9)

It seems that **the CWTS signup isn't properly reflected in Fenix**.
After the auto-sync is done the Logins along with the History and Bookmarks sync options are enabled by default even though I've disabled them in the CWTS signup screen.


►Video from Google Pixel 4XL
![20200310-112400](https://user-images.githubusercontent.com/51314259/76298843-c49ca880-62c2-11ea-9df8-c936f1d10ce1.gif)

►Video from  Google Pixel 3a
![20200310-111838](https://user-images.githubusercontent.com/51314259/76299519-ea767d00-62c3-11ea-902b-87ca8fdcb4bc.gif)

Please review, I'll remove te QA needed label.

**Comment by ekager** [comment] 2020-06-10 03:37
Closing this for https://github.com/mozilla-mobile/fenix/issues/11172 which will dig into the CWTS states

**Closed by ekager** 2020-06-10 03:37 UTC
Labels: Feature:Logins, P2, S2, 🐞 bug, 🙅 waiting
