### ISSUE TITLE
[Bug]: Orientation lock after launching from external intents from PiP 

### ISSUE THREAD

**Issue by czlucius** [mozilla-mobile/fenix#22471] opened 2021-11-17 05:32 UTC
### Steps to reproduce

1. Play a video in a tab, in landscape mode
2. Open it in fullscreen
3. Use the home button/navigation controls to navigate to the Android home screen, so that the video continues in Picture in Picture mode.
4. On the home screen, rotate to portrait mode
5. Launch an app shortcut (long click on Firefox icon and select New Tab or New private tab)
6. Enter a website into the address bar (e.g. https://mozilla.org)

### Expected behaviour

On step 6, the website should open in portrait mode

### Actual behaviour

The app rotates to landscape mode, and the user cannot switch to portrait mode even if the phone is in the portrait orientation. The user cannot go back to portrait mode unless he goes to the tab playing the video and exit fullscreen mode.

### Device name

Samsung Galaxy S20 FE 5G

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

Screen recording below illustrates the issue.

https://user-images.githubusercontent.com/58442255/142140465-196540f0-5e9d-4f20-8cee-e553d9e7a5ba.mp4

This is related to #18727, which is already closed

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18652)

**Comment by SoftVision-LorandJanos** [comment] 2021-11-17 08:15
Hi @czlucius! Thank you for your report!
I've managed to reproduce the issue you described.

Tested on:
- latest Nightly (96.0a1. 2021-11-17).
- latest Beta (95.0.0-beta4).
- latest Release (94.1.2).

Device used: Xiaomi Mi11 (Android 11).

**Comment by czlucius** [comment] 2021-11-17 08:21
Thanks

I think this problem was not discovered when I added my fix to fenix few months ago.
See this PR: https://github.com/mozilla-mobile/fenix/pull/20486

**Comment by czlucius** [comment] 2022-01-20 17:07
I'd like to work on this issue.

**Comment by Mugurell** [comment] 2022-02-17 14:03
I could not reproduce on a Pixel 3 with Android 12.
@czlucius @SoftVision-LorandJanos   Can the STRs be distilled a bit more? Is this an intermittent issue? Are there other steps needed?


https://user-images.githubusercontent.com/11428869/154497438-214b77e3-acfa-48f8-95cd-dce11eb2fd85.mp4

**Comment by czlucius** [comment] 2022-02-17 14:14
I just tried on my device, seems like the bug is no longer reproducible. 
I used the same device listed above, but updated to Android 12.

**Comment by czlucius** [comment] 2022-02-25 03:46
New steps to reproduce:
1. Launch a YouTube video 
2. Go to the home screen
3. Launch Fenix from the search widget (not from the app shortcuts)


Note that this may not be a problem with PiP because this happens regardless of whether the video was playing at Step 1.

Thanks.

**Comment by Mugurell** [comment] 2022-03-01 12:10
Thank you @czlucius!
Interestingly the above scenario will crash the app for me most of the times - created https://github.com/mozilla-mobile/fenix/issues/24040 to address this.

Other than your above steps a scenario that would lead to the described issue:
- have a website shortcut added to homescreen
- play a fullscreen video, enter pip
- tap to open the website shortcut from device's homescreen.

The problem I think is somewhere in the [AC's MediaSessionFullscreenFeature](https://github.com/mozilla-mobile/android-components/blob/4132a8ae8607fd18c8e4e929b08838a0102a599d/components/feature/media/src/main/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeature.kt) which seems to set screen orientation more often than expected and in some scenarios not the orientation that we'd want.

**Comment by Mugurell** [comment] 2022-06-06 06:05
There is a similar issue for when using custom tabs - https://github.com/mozilla-mobile/fenix/issues/25413 but with the crash from https://github.com/mozilla-mobile/fenix/issues/24040 now being resolved resolved I think we can close this.

**Closed** 2022-06-08 16:29 UTC
Labels: 🐞 bug, eng:qa:needed, b:landscape, S3, needs:triage, qa-triaged
