### ISSUE TITLE
Done button after editing folder of bookmarks

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#5816] opened 2019-10-07 14:01 UTC
### Why/User Benefit/User Problem

After adding a new bookmark it is possible to save it in a selectable folder by pressing **EDIT** . If the user does so it is necessary to press the back button twice to get back to the website.

### What/Requirements

It would be good to have a **Done** button next to the **+**(New folder)-Button on top of the bookmark folders.

### Acceptance Criteria (how do I know when I’m done?)

After saving a bookmark and pressing the edit button the user is able to change the folder of the bookmark and thereafter closing/saving the editor by clicking on a **Done/Save** button.

**Comment by topotropic** [comment] 2020-02-11 08:43
dupe of https://github.com/mozilla-mobile/fenix/issues/3813

**Closed by topotropic** 2020-02-11 08:43 UTC
Labels: Feature:Bookmarks, 🌟 feature request
