### ISSUE TITLE
[Bug]Show animation when a new tab backs to the homepage firstly

### ISSUE THREAD

**Issue by Moderpach** [mozilla-mobile/fenix#5026] opened 2019-08-30 03:03 UTC
## Steps to reproduce
1.Open a new tab page.
2.Click tab controller.
### Expected behavior
Show enemy when a new tab page back to the homepage firstly.
### Actual behavior
Back to the homepage without a scale animation.
### Device information

* Android device: 9.0.0
* Fenix version: v1.3.1

**Comment by AmyYLee** [comment] 2019-09-03 19:21
@PowERGD Hi, can you provide a video recording of what you are referring to? I have checked my version and it looks like there is a transition animation from a website back to the homescreen (website screen slides down and the layer below reveals the homescreen). Thanks

**Comment by PowERGD** [comment] 2019-09-04 11:46
![Video_20190904_074303_251](https://user-images.githubusercontent.com/34941512/64252104-95d8fa80-cf4c-11e9-9c94-a9db42584bf5.gif)
@AmyYLee 
Thanks

**Comment by AmyYLee** [comment] 2019-09-05 21:14
Hi, 

Here is a recording with an animation transition. This might be a regression? 

Video link: https://cl.ly/e081f4a57b3c

Build version:
![Screenshot_20190905-171244](https://user-images.githubusercontent.com/5992746/64381144-85825780-d000-11e9-991d-8df77c3a7eff.png)

**Comment by AmyYLee** [comment] 2019-09-05 21:15
@ekager Do you know what might be the issue? I see a transition animation on my build but it doesn't look like there is a transition between homescreen and an open tab in this bug.

**Comment by ekager** [comment] 2019-09-05 21:38
Right when a new tab is created and then we go back to the homescreen - the number of tabs has changed the home screen is adjusting to show the new number of tabs right when the transition is attempting to happen. I'm not sure if we can fix this with the current transition implementation, but we could investigate.

**Comment by ekager** [comment] 2020-03-03 01:54
Closing because we are changing this animation

**Closed by ekager** 2020-03-03 01:54 UTC
Labels: ux:motion-design, 🌟 feature request
