### ISSUE TITLE
[Feature req] Share site to desktop PC

### ISSUE THREAD

**Issue by kilianhann** [mozilla-mobile/fenix#11780] opened 2020-06-20 12:11 UTC
### What is the user problem or growth opportunity you want to see solved?
When I have a URL in another app, I often want to get it on my desktop computer. To do this, I use the android share-menu.
With the old version, I just had to klick on the share button, choose Firefox and then got the option to open it on this device or other devices.
With the new version, the link opens directly in Firefox and I have to klick share there again to choose the desktop PC.
It would be great if I could share the link directly to a Desktop PC (to read articles there ...).

### How do you know that this problem exists today? Why is this important?
It was available in the old Firefox and I have used it a lot. It woud be great if you implement it again.

### Who will benefit from it?
All users who use firefox on more than one device

**Comment by B0pol** [comment] 2020-06-21 08:27
![Screenshot_20200621-102533_Firefox_Preview_1_1](https://user-images.githubusercontent.com/58657617/85220177-c38f1300-b3a9-11ea-9ac9-519c85144c19.png)
It's already available, just connect to firefox sync

**Comment by Tajnymag** [comment] 2020-06-26 12:31
@B0pol No, it isn't. Op isn't talking about sharing from Fenix but is talking about sharing from other applications. 

Currently the "Send To Device" is available in the domain of Fenix. That is impractical, when you want to send a link fex. from WhatsApp

**Comment by justdave** [comment] 2020-07-13 20:11
Duplicate of #1523

**Comment by person808** [comment] 2020-07-14 00:28
Closing as duplicate

**Closed** 2020-08-28 19:36 UTC
Labels: needs:triage
