### ISSUE TITLE
Open in Background Tab

### ISSUE THREAD

**Issue by fabiocosta0305** [mozilla-mobile/fenix#9958] opened 2020-04-15 14:44 UTC
### Why/User Benefit/User Problem

When you open a tab on some other place (for example, Facebook), it opens directly. But sometimes this makes other apps to get out from memory, specially on low end devices. 

By bringing back the Tab Queue (I believe it's called this way - in Portuguese was "Filas de Abas") from the old Firefox, this would either be a good usability feature, by allowing you to queue everything you want to see from outside and get into Firefox when you have time or can open it, and a resource saving featury, as you would just need to open Firefox once you had everything you want to read cached on it

### What/Requirements

Just to replicate the Tab Queue feature from old Firefox

### Acceptance Criteria (how do I know when I’m done?)

When the Tab Queue feature is back

**Comment by cadeyrn** [comment] 2020-04-15 15:42
Duplicate of #470.

**Closed** 2020-04-15 16:59 UTC
Labels: needs:triage, 🌟 feature request

**Comment by JMW882** [comment] 2020-09-06 17:55
Tab queue was a fantastic feature and time saver. Please bring it back ASAP!
