### ISSUE TITLE
[Bug] Tab outline is less tall than tab itself

### ISSUE THREAD

**Issue by djc** [mozilla-mobile/fenix#7692] opened 2020-01-14 19:08 UTC
## Steps to reproduce

1. This seems to happen always/quite often when backing out from a content activity to the tab switcher

### Expected behavior

Outline matches tab background.

### Actual behavior

![Screenshot_20200114-200559](https://user-images.githubusercontent.com/158471/72373946-960eb100-3709-11ea-9fd5-5dd04b77399a.png)

### Device information

* Android device: Pixel 2
* Fenix version: latest Nightly

**Comment by cadeyrn** [comment] 2020-01-14 19:18
Duplicate of #6560 which was closed because the tabs on the start screen will be removed with #7115.

**Closed** 2020-01-14 20:23 UTC
Labels: 🐞 bug
