### ISSUE TITLE
add a way to disable inactive tab collection

### ISSUE THREAD

**Issue by SpandexWizard** [mozilla-mobile/fenix#20707] opened 2021-08-06 08:41 UTC
To put it aimply I hate the inactice tabs system. I only leave a tab open in the first place so that I remember it's there and that I want to come back to it. And moving those tabs around makes things incredibly confusing and reduces my ability to multitask. (Particularly when new tabs are being assigned inactive, but that's a different matter).  I know one lone person isn't going to change the devs' minds, that this feature is going to stay, even though I'm not the only person who thinks it's... Not a feature, to put it as delicately as I can But I'd ask that there be some kind of way to just turn it off. I can't even find a means to set a threshold for what counts as inactive but I'd be /thrilled/ if I could set it to "never"

**Comment by cadeyrn** [comment] 2021-08-06 13:39
Duplicate of #20684 which was closed as duplicate of #20663 (although it's not _exactly_ the same).

**Comment by jonalmeida** [comment] 2021-08-06 19:28
Duplicate of #20684

**Comment by jonalmeida** [comment] 2021-08-06 19:28
I re-opened it as well since it isn't an exact duplicate.

**Closed by jonalmeida** 2021-08-06 19:28 UTC
Labels: needs:triage

**Comment by SpandexWizard** [comment] 2021-08-07 00:25
#20684 seems to want the same thing i do, and i did not see it before posting. my bad. however, @20663 is not the same thing at all. i dont want to collapse the inactive tabs box, or hide it. i want it to stop being used by firefox, i want my tabs to be left alone. and i think that's what #20684 wants too. i want a toggle to disable inactive tabs, or a setting to tell it 'no tabs are old enough to be inactive', or SOMETHING that will prevent my tabs from moving into the inactive tabs folder.
