### ISSUE TITLE
[Bug] Deleting folders+websites still results in a "deleting selected folders" popup in bookmarks

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13158] opened 2020-07-31 10:35 UTC
## Steps to reproduce
In bookmarks multiselect some folders and websites
Delete using three dot menu option

### Expected behavior
A message like "deleting items" or "deleting folders and items" 

### Actual behavior
A popup like "Deleting selected folders"
### Device information

* Android device: ?
* Fenix version: Nightly

**Comment by AndiAJ** [comment] 2020-07-31 11:13
Dupe of #6977 and #6974

**Comment by s-ankur** [comment] 2020-07-31 12:57
@AndiAJ this is about the message that pops up when you delete the items, I don't see how it is related to either of the above issues

**Comment by s-ankur** [comment] 2020-07-31 12:58
Edited for clarity

**Comment by AndiAJ** [comment] 2020-07-31 12:58
Sorry @s-ankur , got mistaken. ☺️

**Closed** 2021-03-04 07:49 UTC
Labels: Feature:Bookmarks, wontfix, 🐞 bug
