### ISSUE TITLE
Increased error rate for `recent_synced_tabs.recent_synced_tab_time_to_load` metric: Invalid state

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/fenix#27436] opened 2022-10-17 15:27 UTC
We see a spike in errors for the [`recent_synced_tabs.recent_synced_tab_time_to_load`](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/recent_synced_tabs_recent_synced_tab_time_to_load) metric on release.

Graph: https://mozilla.cloud.looker.com/dashboards/382?Channel=mozdata.fenix.metrics&Submission+Date=14+day+ago+for+14+day
Spike started 2022-10-12.

Docs about `invalid_state`: https://mozilla.github.io/glean/book/reference/metrics/timing_distribution.html#recorded-errors

> If a non-existing/stopped timer is stopped again.

We didn't see that on Nightly afaik.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21816)

**Comment by kbrosnan** [comment] 2022-10-17 23:43
That would be the start of the 106 release.

**Comment by cpeterso** [comment] 2022-10-24 04:58
I think this bug is a dupe of #26372 that I filed in August about the regression on Nightly caused by #24549.

**Closed by cpeterso** 2022-10-24 04:58 UTC
Labels: needs:triage
