### ISSUE TITLE
[Bug] Selection Action Menu doesn't work on some videos

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#16077] opened 2020-10-21 02:16 UTC
### Steps to reproduce
- Open a video on ted.com
- Long press on the video to trigger the Selection Action Menu (also didn't know this existed :) )

### Expected behavior
- User would expect that tapping on SAVE FILE TO DEVICE would save the video.
- User would expect that tapping on OPEN LINK IN EXTERNAL APP would do something. 

### Actual behavior
- Download fails
- Open link in external app does nothing

### Device information

* Android device: Pixel 4
* Fenix version: Nightly 201020 and Beta 82.0.0-beta 6

![image](https://user-images.githubusercontent.com/42752644/96665015-f1697180-1321-11eb-9481-bb22bba6c6c3.png)

**Comment by Mugurell** [comment] 2020-12-11 14:28
When testing with TED I see we're trying to download from a blob (`blob:https://www.ted.com/5f4..`).
I think in these cases we should not offer the option to download at all.
I see Chrome not offering a download option for TED videos.

I'm seeing that Firefox desktop also doesn't offer a download option in this case.

Asking @agi (since this blobs are constructed in GV or even lower) if this is something that could be done or even if it's something that we should support.

(The other option, "Open link in external app" is also broken. I'd say this should also be hidden)

**Comment by owlishDeveloper** [comment] 2020-12-15 16:52
I'm not Agi, but I worked on downloads, so chiming in here. GV should be able to deal with blob URLs, I implemented this functionality this summer/fall. The fact that the download fails here might be a bug and needs looking into. As for opening in external app, that is probably something that needs to be added on the networking level.

As for whether we _want_ to make the menu items functional or not is a separate question. It seems if neither Chrome nor Firefox are offering this functionality, the priority on this is low even if we want this? Maybe the actual solution here is to remove the menu items for either all blob urls or just TED. (btw, I'm not sure if we enable people to download things from TED, wouldn't it be a legal issue too?)

**Comment by Mugurell** [comment] 2020-12-15 17:10
Maybe this a question that @vesta0 / @amedyne can help with
> If we enable people to download things from TED, wouldn't it be a legal issue

Also in the context that Chrome/Firefox desktop doesn't allow for this.

**Comment by Mugurell** [comment] 2020-12-15 17:30
Talked more on Riot about this.
Agi suggested to move this to Bugzilla.

**Comment by Mugurell** [comment] 2020-12-15 17:30
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1682599

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Mugurell** [comment] 2020-12-15 17:49
Regarding whether we should allow downloading from TED or not Agi said:

> there is a feature in the HTML spec that is specifically built so that user agents cannot download videos (but still are allowed to play it) called Encrypted Media Source Extensions. If the website wants to forbid people from downloading videos they use that
..
which guarantees that the browser cannot download the video (because we only see encrypted data)

So it seems like we should allow downloading from TED and the issue for why we don't could possibly be resolved in GV.

**Comment by Mugurell** [comment] 2020-12-16 14:46
Waiting on BZ - https://bugzilla.mozilla.org/show_bug.cgi?id=1682599 to verify if this will be resolved.

**Comment by Mugurell** [comment] 2021-06-15 05:20
Still waiting on GV.

**Comment by AndiAJ** [comment] 2021-07-16 07:35
Reproducible on Firefox Beta 91.0.0-beta.1 using a OnePlus A3 (Android 6.0.1)

**Comment by agi** [comment] 2022-01-24 20:12
This should be fixed now, can anybody verify?

**Comment by amedyne** [comment] 2022-01-24 20:51
Tagging QA to verify.

**Comment by sflorean** [comment] 2022-01-31 11:59
Verified as fixed on latest Nightly build & latest RC from Play Store. The context menu is not displayed when performing a long tap action.

**Closed by sflorean** 2022-01-31 11:59 UTC
Labels: 🐞 bug, eng:qa:needed, Feature:ContextMenu
