### ISSUE TITLE
[Bug] html on file system not supported any more

### ISSUE THREAD

**Issue by rolfausohnder** [mozilla-mobile/fenix#17477] opened 2021-01-15 06:53 UTC
## Steps to reproduce
Try to open an html-file from your phone's internal memory or SD-card.

### Expected behavior
The browsers installed on the device should be able to open the html file, including firefox.

### Actual behavior
Chrome can open the file, firefox can't open it, and isn't shown in the list of applications that the user can use to open html files.

### Device information
Samsung S9 with Android 10 and latest updates
Fenix Version 85.0.0-beta.7 and Version 84.1.4
 
comment : this used to work well in the past

**Comment by cadeyrn** [comment] 2021-01-15 07:18
Duplicate of #7546.

**Comment by rolfausohnder** [comment] 2021-01-15 12:37
> 
> 
> local html files are blocked, see [mozilla-mobile/android-components@67d138f](https://github.com/mozilla-mobile/android-components/commit/67d138fe074177e51895fc191451ce64e170a29f)

So you are saying this is a feature rather than a bug ?

**Comment by abodea** [comment] 2021-01-15 13:57
Thank you for this report @rolfausohnder, as @cadeyrn said in the comment above, dupe of #7546. I will close this issue, for more info and details please follow up on the #7546 bug.

**Closed by abodea** 2021-01-15 13:57 UTC
Labels: needs:triage, 🐞 bug
