### ISSUE TITLE
[Bug]: [Firefox Android] 3 dot menu icons in Bookmarks are displayed as close ("X") icons 

### ISSUE THREAD

**Issue by Flying-Miko** [mozilla-mobile/fenix#27240] opened 2022-10-01 22:18 UTC
### Steps to reproduce

Open the bookmarks menu

### Expected behaviour

Each bokmark should have a 3 dot menu at its right

### Actual behaviour

The bookmark  have a "x" icon which implements the same functionality as the 3 dot menu.

### Device name

Samsung Galaxy A71

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

105.1.0 (Build #2015904299), b1e7cbeeb+ AC: 105.0.7, e2aeb82d54 GV: 105.0-20220915150737 AS: 94.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21703)

**Comment by bigConifer** [comment] 2022-10-02 16:19
Duplicate of #26093.

PS: This is a copy-paste of the original ticket which is closed as fixed. Following that issue you will see that the fix unfortunately did'n make it into version 105, but is now planned to be part of release 106.

Besides, you have already opened #26725 for exactly the same bug. Please close both of your tickets as duplicate.

**Closed** 2022-10-02 17:40 UTC
Labels: 🐞 bug, needs:triage
