### ISSUE TITLE
[Bug] Show HTTPS version if both http/https of same site suggested in results

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14210] opened 2020-08-26 08:30 UTC
## Steps to reproduce
Visit the http and https version of the same site so that both get saved in history
### Expected behavior
Only one entry when you type the url
### Actual behavior
![Screenshot_20200826-135046_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/91280628-a3624280-e7a4-11ea-89f7-b0306b9f3316.png)

### Device information

* Android device: Asus Zenfone
* Fenix version: nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5554)

**Comment by Dunexus** [comment] 2020-08-26 09:21
Duplicate of https://github.com/mozilla-mobile/fenix/issues/482

**Comment by s-ankur** [comment] 2020-08-26 10:45
@Dunexus that issue is about suggessions form two different categories. Here it seems that the website is suggested twice just from history alone

**Comment by Dunexus** [comment] 2020-08-26 10:51
The first one is http from history, the third one http**s** from history and the fourth one http from bookmark.

The first and fourth duplicate is covered by #482 (same url, one from history, the other from bookmark).

Do you know if desktop would show both http (first one) and https (third one) as two distinct suggestions or merges them as duplicate from one another ?

**Comment by evilpie** [comment] 2020-08-26 10:51
`https://` vs `http://`. Might be a good idea to only suggest `https://` when it exists in history.

**Comment by s-ankur** [comment] 2020-08-26 12:04
On desktop firefox, I have synced it with android so it should have the same history. There I can only see one URL the https one

**Comment by liuche** [comment] 2020-08-27 23:18
This is suggesting from history, but yes, it could be nice if the suggestion also filtered out http if https existed in the results.

**Comment by boek** [comment] 2023-01-31 00:43
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813943

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-31 00:43 UTC
Labels: feature request 🌟, Feature:Toolbar
