### ISSUE TITLE
[Bug] When you lock your device while the tab tray is open, the tray reopens when you unlock it

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#14269] opened 2020-08-27 07:30 UTC
## Steps to reproduce
1. Open tab tray
2. Lock device
3. Unlock device

### Expected behavior
Tab tray would stay open

### Actual behavior
Tab tray reopens when you unlock your device

### Device information

* Android device: ?
* Fenix version: Nightly 200826

**Comment by s-ankur** [comment] 2020-08-27 17:27
Cant reproduce on latest nightly (Asus Zenfone LineageOS 16)

**Comment by ekager** [comment] 2020-12-18 05:16
Thanks for the update! Closing

**Closed by ekager** 2020-12-18 05:16 UTC
Labels: needs:triage, 🐞 bug
