### ISSUE TITLE
[Synced tabs] An option to be redirected to the sign-in page through the Synced tabs page

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#12198] opened 2020-07-02 12:24 UTC
### What is the user problem or growth opportunity you want to see solved?
The user should be redirected to the sign-in page from the Synced tabs page, without having to go back to Settings - Turn on Sync.
Also, when the "Open tabs" option is disabled, and the "Please enable tab syncing" blank page is displayed in the Synced tabs page, it would be great if there was an option to be redirected to the Account settings page without having to go back to Settings - Account.

### How do you know that this problem exists today? Why is this important?
It makes it easier for the user to sign-in.

### Who will benefit from it?
All the users.

**Comment by amkcpu** [comment] 2020-07-16 20:46
Duplicate of #11205.

**Comment by ekager** [comment] 2020-07-16 20:48
Closing for #11205.

**Closed** 2020-08-28 21:28 UTC
Labels: Feature:SyncTabs, needs:triage
