### ISSUE TITLE
No control over Tracking protection

### ISSUE THREAD

**Issue by 1known** [mozilla-mobile/fenix#3705] opened 2019-06-27 13:14 UTC
Opening the settings of Firefox preview, there is only a toggle for on and off.

Like Firefox for desktop, there should be a way to select what we want to protect and what exactly are we protecting ourselves from.

Just like Firefox for Android, preview only has a toggle with zero control and zero information for the user.

Huawei P Smart and Samsung S8

Preview version- 1.0.1926

**Comment by cadeyrn** [comment] 2019-06-27 13:17
Duplicate of #1085.

**Closed** 2019-06-27 14:36 UTC
Labels: 🐞 bug
