### ISSUE TITLE
[Bug] infinite reload with intent:// location

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#5664] opened 2019-09-30 01:33 UTC
This will be fixed by this GV bug
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1600704

## Steps to reproduce
1. Go to https://www.netflix.com/watch/80191852

### Expected behavior
Get the app prompt? Or maybe the page of the movie. 
This might relate to #3177

### Actual behavior
Infinite reloading with 302 in the http response. Usually Firefox desktop in these circumstances would stop after 20 attempts. Here it doesn't stop.

### Device information

* Android device: Pixel 2 Android 10
* Fenix version: Nightly 190927 06.21 (Build #12700628)

**Comment by karlcow** [comment] 2019-09-30 01:34
It was found through the report on https://github.com/webcompat/web-bugs/issues/40394

**Comment by tdsmith** [comment] 2019-10-02 04:14
I can also observe this by visiting https://olin.repair and clicking the "sign our support form" link, which is a link to https://bit.ly/olincares. (I can't observe this by entering the URL directly into the address bar.) Bit.ly redirects for a forms.gle URL, which redirects to an intent, which enters a redirect loop.

A HAR capture: https://gist.github.com/tdsmith/2f45c4686f05f5f12d12a146543dfe06 -- I terminated the redirect loop by turning off the screen on my device.

**Comment by cpeterso** [comment] 2019-10-31 18:14
I closed the GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1581966

This is a Fenix bug. Fenix needs to add support for intent URIs, or at least recognize them so we don't get stuck in an infinite loop.

See also Google Maps infinite loop issue #4322.

**Comment by kbrosnan** [comment] 2019-10-31 23:03
Added the tags and project boards from #4322.

**Comment by rocketsroger** [comment] 2019-11-08 16:09
@vesta0 What is the expected fix for this issue? Do we just want to avoid infinite load?  Thanks,

**Comment by vesta0** [comment] 2019-11-09 22:14
@rocketsroger yes we should avoid the infinite reload.

**Comment by rocketsroger** [comment] 2019-11-12 15:46
> @rocketsroger yes we should avoid the infinite reload.

Understood.  Thanks,

**Comment by rocketsroger** [comment] 2019-11-21 20:54
Tested on Fenix nightly and confirmed infinite reload is fixed on both netflix and olin.repair.  Please confirm.

**Comment by AndiAJ** [comment] 2019-11-22 15:07
Hi, I've just checked this issue on the latest **Nightly Build #13261307** from 11/22 using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

✔️ Netflix 
![20191122_163325](https://user-images.githubusercontent.com/51314259/69435379-1dfabf00-0d48-11ea-8ef3-75c3aee450e0.gif)

❓ olin.repair.  - Not sure how fast the infinite reload avoidance should kick-in.
After tapping on "sign our support form" link it takes approx. 40 seconds for the page to stop loading and afterwards an "Address Not Found" page is displayed.
![20191122_163445](https://user-images.githubusercontent.com/51314259/69436447-0a505800-0d4a-11ea-96af-92c64352a11e.gif)

@rocketsroger - I would kindly ask you to review the above, and advise. :relaxed:
**I'll remove the QA needed label until further notice.**

**Comment by rocketsroger** [comment] 2019-11-22 15:20
@AndiAJ Thanks!  I didn't notice the 40 seconds timeout.  I'll investigate.

**Comment by rocketsroger** [comment] 2019-12-02 18:05
Bug opened for GeckoView
https://bugzilla.mozilla.org/show_bug.cgi?id=1600704

**Comment by liuche** [comment] 2020-01-15 02:15
@rocketsroger is the App Links work still ongoing? If so, I'm going to put this into the Bug Backlog.

**Comment by rocketsroger** [comment] 2020-01-15 15:31
> @rocketsroger is the App Links work still ongoing? If so, I'm going to put this into the Bug Backlog.

Yes, we are blocked waiting for a GeckoView fix.  Once the GV fix is merged, this issue needs to be retested to confirm.

**Comment by liuche** [comment] 2020-01-16 19:46
@rocketsroger is it this GV bug? https://bugzilla.mozilla.org/show_bug.cgi?id=1600704

**Comment by rocketsroger** [comment] 2020-01-16 19:58
> @rocketsroger is it this GV bug? https://bugzilla.mozilla.org/show_bug.cgi?id=1600704

Yes, this is the main GV issue that the app links feature is blocked on.

**Comment by rocketsroger** [comment] 2020-02-28 19:25
Netflix case is now working correctly.  User clicking on video will be forwarded to market place to install the Netflix app.

**Comment by rocketsroger** [comment] 2020-02-28 19:26
The olin.repair case will need some changes to work correctly when "Open links in apps" is not turned on.

**Comment by rocketsroger** [comment] 2020-03-02 16:35
Issue with olin.replair will be fixed with https://github.com/mozilla-mobile/android-components/issues/6147

Adding QA to confirm nightly fixed the original Netflix issue.

**Comment by rocketsroger** [comment] 2020-03-02 17:58
Looks like the app install issue is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1619344.  Removing QA needed tag and will retest after the fix is merged in

**Comment by rocketsroger** [comment] 2020-03-09 13:28
Confirmed issue is fixed on nightly.  Please verify.

**Comment by LaurentiuApahideanSV** [comment] 2020-03-10 14:35
I tested the issue on Firefox Preview Nightly 200310 (Build #20700607) GV: 75.0a1-20200309091841 using a Motorala G7 (Android 9) and OnePlus 6T (Android 9). The Netflix work correctly and open the Google Play store, however when tapping on the "sign our support form" from the https://olin.repair/ page the "Adress Not Found" or "This site can’t be reached" error message is displayed on Firefox Preview and Chrome respectively.

**Comment by rocketsroger** [comment] 2020-03-10 15:21
> https://olin.repair/ page the "Adress Not Found" or "This site can’t be reached" error message is displayed on Firefox Preview and Chrome respectively.

That's interesting.  Maybe it is blocking access using IP address.  I've just tested with the latest nightly from Google Play and the form still works for me on Fenix nightly.  Thanks for confirming this is fixed, I'll close.

**Closed by rocketsroger** 2020-03-10 15:21 UTC
Labels: P2, S2, b:web-content, eng:qa:verified, 🐞 bug
