### ISSUE TITLE
FNX-5423 ⁃ [Bug] Location permission is full screen (on mapquest.com)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2055] opened 2019-04-25 22:52 UTC
## Steps to reproduce
1. Navigate to mapquest.com

### Expected behavior
Permission request should not cover all page content. 

### Actual behavior
Permission request covers 99% of page content. 

![signal-attachment-2019-04-25-185224](https://user-images.githubusercontent.com/152493/56773223-4a873200-678b-11e9-8474-59ddc41dee7e.png)

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by kbrosnan** [comment] 2019-04-25 22:54
Dupe of #1557

**Closed** 2020-08-11 13:47 UTC
Labels: 🐞 bug
