### ISSUE TITLE
[Bug]: Unable to do anything else while bookmark is being deleted

### ISSUE THREAD

**Issue by Allenout** [mozilla-mobile/fenix#21531] opened 2021-09-28 00:58 UTC
### Steps to reproduce

1.Open a bookmarked page
2.Delete Bookmark
3.While "Deleted (Bookmark Name)" is playing, click or do anything such as click and open the search bar.

### Expected behaviour

1.Open bookmark page
2.Delete a bookmark
3.Be able to do something else while "Deleted (Bookmark Name)" is playing.

### Actual behaviour

1.Open a bookmarked page
2.Delete Bookmark
3.While "Deleted (Bookmark Name)" is playing, I am unable to click the search bar until "Deleted (Bookmark Name)" is gone which could be a few seconds.

### Device name

OnePlus 6

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

91.2.0

**Comment by LaurentiuApahideanSV** [comment] 2021-11-24 16:17
I can confirm the issue is reproducible on the latest Firefox Preview Nightly 2021-11-24. The issue has already been reported here: https://github.com/mozilla-mobile/fenix/issues/9539#issuecomment-832529639. I will mark this issue as closed as it will be handled there.
### Device used:
- Oppo Find X3 (Android 11)

**Closed by LaurentiuApahideanSV** 2021-11-24 16:17 UTC
Labels: 🐞 bug, needs:triage
