### ISSUE TITLE
[Bug] Long pause before app launch when clicking homescreen icon on cold startup

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#7880] opened 2020-01-23 11:06 UTC
### Steps to reproduce

0. open the Android recent apps screen and remove all instances of Firefox Preview 
1. open the Firefox Preview stable release
2. do the same with Firefox Preview Nightly

Please note: step 0 is important. After Firefox Preview is "warmed up", subsequent openings of Firefox Preview are fast in both cases.

### Expected behavior

Same performance or an even better performance in Nightly due to the latest performance optimizations.

### Actual behavior

Firefox Preview Stable: Firefox Preview starts immediately. You see a black screen for a short moment which fades to the light browser's start screen. Not perfect, but okay. It feels smooth.

(Maybe related that I use a dark sytem and the light Fenix theme)

Firefox Preview Nightly: There is a very noticeable delay before Firefox Preview opens, it doesn't feel smooth at all. You can even see how the size of the launcher icon changes during the start. Firefox Preview stable starts so fast that you can't see the same.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: 3.0.2 / master branch revision 1ee0243efa454c7eb9221035c7d11138e36c70e0

**Comment by cadeyrn** [comment] 2020-01-23 11:22
I attached a screencast. First I opened the stable release, then Nightly. It doesn't look like a large delay in the screencast but the small delay has a large _perceptual_ impact.

![ezgif-3-6f796764c188](https://user-images.githubusercontent.com/1100614/72980383-cb3a9380-3dda-11ea-9d6d-1442884c9a3e.gif)

**Comment by pocmo** [comment] 2020-01-23 17:38
Like the same as #7818.

**Comment by liuche** [comment] 2020-01-23 21:26
Adding this to the Fenix AC board bc this is possibly a perf startup regression, and we need to prioritize this to hit our perf goals for shipping.

**Comment by mcomella** [comment] 2020-01-24 01:21
I noticed we no longer draw the white frame before we launch into the activity: I'm not sure if this was intentionally disabled, if this was a result of Activity redirection, a result of yielding the UI thread (due to coroutine processing), or what. If we can re-enable this frame, it may improve perceived performance.

**Comment by mcomella** [comment] 2020-01-25 02:30
I expect this to be addressed by the fix for https://github.com/mozilla-mobile/fenix/issues/7818.

**Comment by cadeyrn** [comment] 2020-01-25 09:28
Now there is no longer a long pause before app launch but a black screen. But the black screen appears **much, much longer** than in Firefox Preview Stable.

**Comment by abodea** [comment] 2020-01-28 15:27
I re-checked this issue on the latest Nightly from 1/28 with Google Pixel 3a XL(Android 10).
I have the same behavior as Cadeyrn described above.
I will remove the qa needed label until further notice.

**Comment by mcomella** [comment] 2020-02-17 14:31
Moving back to triage given this issue is still occurring (sorry for the delay).

**Comment by emalysz** [comment] 2020-02-21 06:13
@abodea Would you be able to attach a video of this? I tried to reproduce by building with the geckoNightlyFennecNightly variant, as is from the app store, and also tried changing my android theme to Dark mode with Fenix light, but I was still unable to reproduce. Thanks!

**Comment by mcomella** [comment] 2020-02-24 21:50
There are no delays on the Beta build according to one reporter: https://github.com/mozilla-mobile/fenix/issues/7818#issuecomment-589577516

**Comment by abodea** [comment] 2020-02-25 15:11
Hello, @emalysz  I re-tested this issue for more details please check the following:
I tested 4 scenarios:
### 1. For this, I used the latest RC installed from Play Store and the Nightly from 1/28(the one I tested [here](https://github.com/mozilla-mobile/fenix/issues/7880#issuecomment-579300038))
**Device: Google Pixel 3a XL(Android 10).**
Note that for the RC there is still a pause before the app is launched.
For nightly there is a black screen displayed.
The big pause before launch was present only on the Android 10 and for the RC build.

![rc-128Nightly](https://user-images.githubusercontent.com/42831109/75255463-a75bda80-57ea-11ea-9cbb-516496565268.gif)

### 2. For this, I used the latest RC installed from Play Store and the latest Nightly from 2/25.
**Device: Google Pixel 3a XL(Android 10).**
Note that for the RC there is still a pause before the app is launched.
For nightly there is a black screen displayed.
The big pause before launch was present only on the Android 10 and for the RC build.
![rc-latestNightly](https://user-images.githubusercontent.com/42831109/75255926-644e3700-57eb-11ea-8eed-f09b010a4db9.gif)

### 3. For this, I used the latest RC installed from Play Store and the Nightly from 1/28(the one I tested [here](https://github.com/mozilla-mobile/fenix/issues/7880#issuecomment-579300038))
**Device: Samsung Galaxy S10+(Android 9).**
On this device, there is no pause before the launch on the RC build.
Here you can see 2 cases, first, the apps were just added to the background, and then I closed them and re-open.
For the nightly, it can be seen the black screen right before the homescreen is displayed.

![rc-128NightlyS10](https://user-images.githubusercontent.com/42831109/75256735-9613cd80-57ec-11ea-9d3b-90c76086084e.gif)


### 4. For this, I used the latest RC installed from Play Store and the latest Nightly from 2/25.
**Device: Samsung Galaxy S10+(Android 9).**
On this device, there is no pause before the launch on the RC build.
It can be noticed that when launching the Nightly build there is a black screen displayed.
![RC-latestNightlyS10](https://user-images.githubusercontent.com/42831109/75259139-391a1680-57f0-11ea-8cbb-682a8fa0b491.gif)


@emalysz if you will try to launch the RC first and then the Nightly on a cold start you will notice the difference better.

**Comment by mcomella** [comment] 2020-02-26 18:53
>  used the latest RC installed from Play Store 

If RC refers to the build in the "Firefox Preview" channel, I noticed the fix is not in that build: the RC (v3.2.1) was built on 1/25 and [the patch that fixes it](https://github.com/mozilla-mobile/fenix/pull/7917) landed on 1/24 - close enough that it's possible it didn't make it in. I also confirmed that commit is not in the v3.2.1 git tag.

> Now there is no longer a long pause before app launch but a black screen.

So I think the long pause issue is fixed, according to the reporter and Andrei's report above: think we should move this issue to "Done".

> The black screen appears much, much longer than in Firefox Preview Stable or in Firefox Preview Nightly before the latest change. So it's still a big regression. And since I use the light Fenix theme it's even worse to see a black screen for such a long time.

But there may be a new unrelated issue that the system's placeholder frame takes a long time to disappear. Looking at the implementation, if the pause is longer, it is probably unrelated to the fix made here and is a separate regression. The performance group is actively trying to reduce startup time including this time between this system placeholder frame and the first frame drawn by the app: we're addressing it in many separate issues (see [our project board](https://github.com/mozilla-mobile/fenix/issues/6572)). I would recommend not opening a new issue for this because it's already being worked on.

However, there is also a possibility that performance is worse on certain devices such as the reporter's OnePlus: perhaps we should file a new issue to try performance on this device before saying it will be covered by our current area of focus. Note: I think the impression of the black/white screen is exacerbated by this issue - https://github.com/mozilla-mobile/fenix/issues/6572 - which affects the OnePlus McLaren by default.

@emalysz Would you mind following up?

**Closed** 2020-02-26 20:29 UTC
Labels: eng:performance, perf:P1, 🐞 bug
