### ISSUE TITLE
[Bug] Animation jank when clicking URL bar and closing it

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7381] opened 2019-12-27 17:37 UTC
## Steps to reproduce
- Click URL bar (observe)
- Press back (observe)

### Expected behavior
Smooth animation to open enter address page. Smooth animation to close page.

### Actual behavior
Jank when opening page. In separate non-animated frames, the following happens in order:
- Web page flashes to white
- "Search or enter address" appears at top of screen
- ^ "Search or enter address" is replaced by URL
- URL is highlighted
- Keyboard is raised, bumping "Scan | Shortcuts" menu from bottom of screen to above keyboard

Jank when closing page. In separate, non-animated frames, the following happens in order:
- The "Search or enter address" bar disappears and the toolbar appears at the bottom of the screen
- The toolbar relayouts where a bookmarks star is shown and other items are reordered
- The toolbar relayouts to final layout where TP is shown instead of star
- The web page appears and a black bar appears where the toolbar was (it moves to the bottom of the screen, hidden by the animating out keyboard)

I took a video: download it and play the video in slow motion (e.g. by moving individual frames with the arrow keys in Quicktime): https://drive.google.com/file/d/1NyETDyDbu77Mehcjwr05W66Fao-6Dz7X/view?usp=sharing

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 191226

**Comment by darkwing** [comment] 2020-02-11 23:36
This could be much smoother.

**Comment by sblatz** [comment] 2020-02-26 18:58
I'm working on this as part of search polish and have already made improvements on Home -> Search 😄

**Comment by AndiAJ** [comment] 2020-03-10 11:08
Hi, **still reproducible** on the latest **`Nightly Build #20700607 from 03/10`** using the following devices:
• Google Pixel 4XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

Most of the inconsistencies described by @mcomella seem to be **happening closing the search fragment**.

►Video from Google Pixel 3a 
![20200310-124457](https://user-images.githubusercontent.com/51314259/76306601-e0f31200-62cf-11ea-84b4-09daa4400fb3.gif)

►Video from Huawei Mate 20 Lite 
![20200310-124940](https://user-images.githubusercontent.com/51314259/76306674-04b65800-62d0-11ea-9f11-c85594b2828f.gif)

►Video from OnePlus A3 
![20200310-125214](https://user-images.githubusercontent.com/51314259/76306765-29123480-62d0-11ea-8108-156ef62595f2.gif)

@sblatz - Please review. ☺️ 
I'll remove the QA needed until further notice.

**Comment by sblatz** [comment] 2020-04-13 18:06
@mcomella do you feel like this new animation is good enough? The icon doesn't flash to being a star anymore, the animation is not "jittery" anymore. Please let me know what issues you still have with it :)

For what it's worth there's only so much we can do to make this animation feel "smooth" since the keyboard has to be dismissed and its animation is handled by the system 😕 

![fixed animation](https://user-images.githubusercontent.com/4400286/79146091-ad941f00-7d76-11ea-87c4-5b70a34a8e8c.gif)

**Comment by mcomella** [comment] 2020-04-14 22:48
@sblatz Yeah, this looks much better on my P2 – I'm happy to close.

> For what it's worth there's only so much we can do to make this animation feel "smooth" since the keyboard has to be dismissed and its animation is handled by the system

To that point, I wonder how other apps animate to look smooth while animating the keyboard. Can we learn from them?

**Closed** 2020-04-20 17:49 UTC
Labels: Feature:Search, P2, eng:quality, 🐞 bug
