### ISSUE TITLE
[Bug] Drop-down menu list not working properly

### ISSUE THREAD

**Issue by Qbsoon** [mozilla-mobile/fenix#18984] opened 2021-04-13 07:50 UTC
After recent updates drop-down menu list (this one with bookmarks, history, etc.) is not working properly. When I open it, when my phone is in landscape mode it's ok, but when it's in portrait mode I see only half (upper-half) of the list. And I can click on something and it works. But when I try to swipe to see the whole list, it shows me the whole list, but then none of the buttons are working.

## Steps to reproduce
Open browser.
Open some site.
Open drop-down menu list.

### Expected behavior
Well, it should show the full list and all buttons should be working.

### Actual behavior
It shows only upper-half of the list and when I swipe, it shows full list, but it's buttons aren't working anymore.

### Device information

* Device vendor / model and Android version: Samsung SM-A715f/DS, Android 11, One UI 3.1
* Firefox for Android version: Nightly 210411 17:01 (Build #2015804043)

EDIT: Just updated to Nightly 210412 17:03 (Build #2015804235) and buttons work after swiping, but I still have to swipe.

**Comment by cadeyrn** [comment] 2021-04-13 07:55
> Just updated to Nightly 210412 17:03 (Build #2015804235) and buttons work after swiping

This was #18814.

> but I still have to swipe

This is by design.

**Comment by Qbsoon** [comment] 2021-04-13 07:58
> 
> This was #18814.
> 
Oh, I searched for it, but still didn't found

> 
> This is by design.
>
Oh, will it be switchable in the options or wherever? I'd love to have quick access to share and refresh buttons.

**Comment by cadeyrn** [comment] 2021-04-13 08:01
The bottom bar with the back, forward, share and reload icons will be fixed, they're already working on it. See https://github.com/mozilla-mobile/android-components/pull/10058.

**Comment by Qbsoon** [comment] 2021-04-13 08:03
> 
> 
> The bottom bar with the back, forward, share and reload icons will be fixed, they're already working on it. See [mozilla-mobile/android-components#10058](https://github.com/mozilla-mobile/android-components/pull/10058).

Ok, thanks for the answers.

**Comment by Mugurell** [comment] 2021-04-13 09:10
This is the intended behavior following https://github.com/mozilla-mobile/fenix/issues/17772

**Closed by Mugurell** 2021-04-13 09:10 UTC
Labels: needs:triage, 🐞 bug
