### ISSUE TITLE
[Bug]: Single searches are not displayed in the Recent Searches section while enrolled in the experiments/rollout

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-mobile/fenix#21799] opened 2021-10-08 10:02 UTC
### Steps to reproduce

**[Prerequisites]:**
- Be enrolled in one of these experiments/rollout: [New user experiment](https://experimenter.services.mozilla.com/nimbus/mr2-home-screen-impact-assessment-experiment), [Upgraded user experiment](https://experimenter.services.mozilla.com/nimbus/upgraded-user-home-screen-impact-assessment-experiment), [All users Rollout](https://experimenter.services.mozilla.com/nimbus/all-users-home-screen-android)

**[Steps to reproduce]:**   
1. Open a tab and search for anything.
2. Tap the home button from the browser toolbar.
3. Observe the "Recent searches" section.

### Expected behaviour

- The previous search is displayed.

### Actual behaviour

- Single searches are not displayed in the section.

### Device name

Oneplus 6

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

94.0.0-beta.1

### Additional information

Other devices that can reproduce the issue:
- Huawei P20 Lite, Android 8
- Samsung Galaxy S8, Android 9

Attached a screen recording:

https://user-images.githubusercontent.com/18304511/136537717-515df0ea-60c1-42e6-b651-c32b4c2ff8a2.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18234)

**Comment by csadilek** [comment] 2021-10-09 17:20
This is by design, as we're not displaying the original search separately in the history search groups.

For tabs we decided to add the original search to the group because it's already being displayed and would feel off, but I see how this difference can be confusing. We already filed this as: https://github.com/mozilla-mobile/fenix/issues/21659 to reconsider.

So I'll close this as a dupe then.

**Closed as completed by csadilek** 2021-10-09 17:20 UTC
Labels: 🐞 bug, S3, needs:triage, wontfix
