### ISSUE TITLE
[Bug] 79 removed the "keyword" functionality from bookmarks - I would like it back

### ISSUE THREAD

**Issue by ccoenen** [mozilla-mobile/fenix#14571] opened 2020-09-01 08:07 UTC
## Expected behavior

Keywords should be available also on Firefox on Android, in the way described below

## Actual behavior

Keywords have been removed in Firefox 79

## Device information

* Android device: (does not matter)
* Fenix version: 79.0.5

## Rationale

In Firefox for Android before 79, one could have bookmarks with a shortcut/keyword that would auto-fill into a URL in the same way this still works on the desktop. I have a bunch of shortcuts with this set up:

* `xkcd workflow` -> https://duckduckgo.com/?ia=web&q=site%3Axkcd.com+workflow
* `y astley` -> https://www.youtube.com/results?search_query=astley&search_type=&aq=f&oq=
* `wp shortcut` -> https://en.wikipedia.org/wiki/Special:Search?search=shortcut&ns0=1
* ... and so on. You get the idea.

This is immensely useful, _especially_ on mobile where an additional page load is time-consuming and where screen space is limited. I have 26 of these set up, and I use 10 _very_ regularly and another 10 every now and then. I _really_ would like this feature re-added to Firefox on Android.

(yes this screenshot is from the desktop version, it only goes to illustrate the amount of quick searches I have set up)
![proof of the 26 shortcuts I have set up on desktop](https://user-images.githubusercontent.com/124909/91824237-b9f01a00-ec3a-11ea-9869-64eb0cbecf7d.png)

**Comment by hwinnemoe** [comment] 2020-09-01 08:37
Duplicate of #12099, #14327

**Comment by ccoenen** [comment] 2020-09-01 13:53
sorry, you're right. I was looking for "shortcut" first, but only learned afterwards that these are called "keywords" in the english original.

**Comment by hwinnemoe** [comment] 2020-09-01 14:48
You can set your Firefox to English via _Settings_, _Language_. That way you can be sure to use the same terms as are used here.

**Comment by ccoenen** [comment] 2020-09-01 14:49
next time :-)

**Comment by jonalmeida** [comment] 2020-09-01 18:09
Closing as duplicate. Thanks @ccoenen and @hwinnemoe !

**Closed by jonalmeida** 2020-09-01 18:09 UTC
Labels: needs:triage, 🐞 bug

**Comment by Matt-17** [comment] 2022-02-05 00:49
Wow. I thought this was a bug or for later implementation. But removing this feature on desktop will make me change my browser as I use them every hour since 20 years.
