### ISSUE TITLE
[Bug] Autofill of website in omnibox will start search

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#7986] opened 2020-01-29 17:12 UTC
## Steps to reproduce

1. Type in a few chars from a website you want to visit and is bookmarked
2. See that the auto completion took place and the whole web address is in omnibox now
3. Press enter

### Expected behavior

It does open the website.

### Actual behavior

It starts a search

![Screenshot_20200129-175937_Firefox Preview](https://user-images.githubusercontent.com/52482050/73379504-a6ef2300-42c2-11ea-9b90-baf2f875a7f1.jpg)

![Screenshot_20200129-175952_Firefox Preview](https://user-images.githubusercontent.com/52482050/73379511-ace50400-42c2-11ea-8498-01b91c3ad58e.jpg)

### Device information

* Android device: Samsung Galaxy Note 10 Android 10
* Fenix version: 3.2.0 (Build #20250236)
28.0.2, 1deaef19a
GV: 73.0-20200123180644

**At my Oneplus 3T OOS9.0.6 Android 9 Fenix Nightly it seems fixed with one of the last updates.**

**Comment by cadeyrn** [comment] 2020-01-29 21:28
Duplicate of #7800 (fixed in Fenix Nightly).

**Closed** 2020-01-30 00:26 UTC
Labels: needs:triage, 🐞 bug
