### ISSUE TITLE
[Bug] play.google.com icon is not displayed.

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#19811] opened 2021-06-04 05:36 UTC
Hi, Why play.google.com icon is not displayed?

# Chrome
![IMG_20210604_100018.jpg](https://user-images.githubusercontent.com/23485114/120750791-31314200-c51c-11eb-822a-0acbe53bc644.jpg)

# Firefox
![IMG_20210604_100318.jpg](https://user-images.githubusercontent.com/23485114/120750813-3b534080-c51c-11eb-8b97-05db0671f56d.jpg)

**Comment by Nickoriginal** [comment] 2021-06-04 15:47
I can't reproduce this issue on my device (Samsumg Galaxy A20s):
![Screenshot_20210604-184347_Firefox](https://user-images.githubusercontent.com/85299944/120828306-0c14f180-c565-11eb-8b08-0fdebb0df632.jpg)

**Comment by xmha97** [comment] 2021-06-04 18:24
I think this problem has been fixed on nightly version.
![Firefox on Android](https://user-images.githubusercontent.com/23485114/120846658-b271ee80-c587-11eb-8f19-e237b2b323e1.jpg)

**Comment by amedyne** [comment] 2021-06-08 21:15
Closing this issue per latest comment.

**Closed by amedyne** 2021-06-08 21:15 UTC
Labels: needs:triage, 🐞 bug
