### ISSUE TITLE
[Bug] "What's new" present menu-icon takes me to a google search for a URL

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#5676] opened 2019-09-30 15:54 UTC
## Steps to reproduce
1. Tap the a "present-icon" what's-new item in your Fenix menu. (Not sure what causes this menu item to be there, but it was there for me).

### Expected behavior
Fenix should go to a what's new page.

### Actual behavior
Fenix goes to a google search no-results-found page, having just *searched* for the URL that it intended to go to. Specifically, it goes to:
https://www.google.com/search?q=https%3A%2F%2Fsupport.mozilla.org%2F1%2Fmobile%2F%22Nightly19092818%3A00%22%2FAndroid%2Fen-US%2Fwhats-new-firefox-preview&ie=utf-8&oe=utf-8&client=firefox-b-1-m

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 190928 18:00 (gecko 71.0a1)

**Comment by ekager** [comment] 2019-09-30 15:56
Closing as dupe of #5595

**Closed by ekager** 2019-09-30 15:56 UTC
Labels: 🐞 bug
