### ISSUE TITLE
New Tab screen is missing bookmarks

### ISSUE THREAD

**Issue by thirdconspiracy** [mozilla-mobile/fenix#14799] opened 2020-09-07 00:31 UTC
### What is the user problem or growth opportunity you want to see solved?
Prior to the (amazing) update, clicking new tab would present me with 3 options: 
* History
* Bookmarks
* something else I cannot recall (featured?)

Now, I can no longer have mobile bookmarks shown.  When clicking a bookmark, I don't know if it'll open in existing tab or a new one.  I don't know if I should open a new tab before clicking a bookmark.  

As a firefox android user,
when I want to open a bookmark,
I would like a large button (new tab icon preferred) and one finger press to view bookmarks.  
I would also like to have control of where the bookmark opens (existing or new tab).

### How do you know that this problem exists today? Why is this important?
* The bookmarks menu link is much smaller than the new tab icon so Fitz law says it's worse UX
* Clicking a bookmark, I never know if it will open in my current tab or a new one
* It's more keystrokes to think about instead of all new activity happening from the new tab icon

### Who will benefit from it?
* Everyone who likes fewer keystrokes (finger pokes) and used the bookmarks bar often

**Comment by amkcpu** [comment] 2020-09-07 09:46
Duplicate of #12941.

**Closed** 2020-09-08 23:03 UTC
Labels: needs:triage
