### ISSUE TITLE
Set initial loading content page color to non-white when using dark mode

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#6313] opened 2019-10-29 06:56 UTC
### Why/User Benefit/User Problem

Currently opening a new page temporarily shows a pure white page before loading actual content regardless of the browser theme.

### What/Requirements

Fenix does not give a way to control this while on Windows this can be controlled by `browser.in-content.dark-mode` pref (which is on by default on Nightly 71 and makes the page gray).

The white flash is the page clear color, which Fenix can already set clear color using GV API `CompositorController.setClearColor`.

Fenix clear color should probably change the clear color depending on Fenix's or Android's dark mode settings.

This bug was originally filed in Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1589576

### Acceptance Criteria (how do I know when I’m done?)

Opening a new page when dark mode is enabled does not flash a pure white page before loading actual content.

**Comment by nt1m** [comment] 2019-10-29 09:45
@cpeterso `browser.in-content.dark-mode` is enabled by default even on Release since Firefox 70. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1565051

I think Fenix should just follow the theme that's chosen by the user though.

**Comment by ekager** [comment] 2020-04-23 19:00
From Bugzilla:
> The white flash is the page clear color, which Fenix can already set clear color using GV API CompositorController.setClearColor.

**Comment by ekager** [comment] 2020-04-23 20:53
Chatted with the GV team on Riot and unfortunately the above solution likely does not work anymore with WR enabled. FxR uses a dummy surface with the correct color until they get a `onFirstContentfulPaint` and that's probably the direction we'd have to go as well to fix this.

**Comment by dholbert** [comment] 2020-04-30 17:42
Here's a screencast of what this looks like, FWIW:
https://www.dropbox.com/s/zne4d8tdfwybtnj/flash-of-white.mp4?dl=0

There's a flash of white (due to this bug) at around 0:04, while the keyboard is disappearing.

**Comment by 532910** [comment] 2020-04-30 19:30
There was a gif in #10158

**Comment by ekager** [comment] 2020-05-01 18:06
Opened AC issue https://github.com/mozilla-mobile/android-components/issues/6757

**Comment by Kreuger** [comment] 2020-05-08 01:31
@ekager Hey is therr any update on this? I see you submitted 2 commits for this. Does that mean it's being improved?

**Comment by ekager** [comment] 2020-05-08 02:57
@Kreuger yeah I have a work in progress that will hide the web content until the content appears so it should improve the behavior a bit. Unfortunately on a site that doesn't support dark mode and is very white (ie CNN) it'll still be jarring when the content appears

**Comment by Kreuger** [comment] 2020-05-09 03:47
@ekager Ok thanks for the update!

**Comment by B0pol** [comment] 2020-05-16 21:05
It's definitively greater! But sadly not fixed entirely.
It's now fixed when browsing inside the browser: e.g. switching tab in browser, or opening a new tab in browser.
But it still happens a lot when you open the browser via an external app.

I found out that when you kill the browser and open for the first time the browser (via an external app, or not), it won't do the white flash, but then **every next time** you open the browser **via an external app==, the white flash is there to kill your eyes.

See this GIF:
![fenix-white-flash](https://user-images.githubusercontent.com/58657617/82130205-9effb400-97c9-11ea-857a-a2f017963257.gif)
(I enabled dark reader because it makes the white flash more noticeable, but it's also reproducible without dark reader).
I'm using nightly 200516.

**Comment by ekager** [comment] 2020-05-16 21:37
Thanks for the details @B0pol ! https://github.com/mozilla-mobile/fenix/pull/10707 should resolve this last issue

**Comment by Kreuger** [comment] 2020-05-28 18:13
Hello I'm just wondering what the E5 label means. It's not mentioned in the labels on the wiki.

**Comment by lnicola** [comment] 2020-05-28 18:15
@Kreuger it's labelled as "estimation point", which is a measure of the difficulty of a task, used for project management purposes.

**Comment by Kreuger** [comment] 2020-05-29 06:28
Thanks!

**Comment by B0pol** [comment] 2020-06-05 08:19
Why has https://github.com/mozilla-mobile/fenix/commit/d66762910fd402b8456b3e74dade62a713bb1a66 been reverted? It fixes two situations as I said above (top sites and search query), it's way better than nothing.

**Comment by cadeyrn** [comment] 2020-06-05 08:30
> Why has d667629 been reverted?

https://github.com/mozilla-mobile/fenix/pull/10707#issuecomment-630258174

**Comment by opusforlife2** [comment] 2020-07-22 01:32
Has any developer tested this with the extension Dark Background and Light Text? I was just using Fennec where I have it installed and remembered with some surprise that it _doesn't have any white flashes between page loads._ And this is a browser that doesn't even _have_ a dark mode. This is probably the reason why I found the shift to Fenix so jarring.

Maybe the extension could be a temporary solution until someone resumes work on this issue. It's a Recommended Extension on desktop, as well. No hurdles there.

To be clear, Fennec with the extension disabled _does_ show white flashes between pages, but _doesn_'t with the extension enabled.

**Comment by jenabaivab** [comment] 2020-07-29 12:32
Is this being worked on? I have tried this with both beta and nightly, but both give similar results.
Anybody knows any workarounds at least?

**Comment by Rushilotti** [comment] 2020-07-29 22:38
> Is this being worked on? I have tried this with both beta and nightly, but both give similar results.
> Anybody knows any workarounds at least?

If your mobile is rooted you can use userChrome.css and user content.css to change this but there is no fix for non rooted phones. Hope devs will fix this ASAP as this is so annoying and irritates me all the time and I don't want to root my phone just for the sake of this.

**Comment by ekager** [comment] 2020-08-04 21:19
Hey everyone! Thanks for your patience on this issue. If you would like to help us test this I have added a potential fix to secret settings, but we want to make sure it works before releasing it to nightly (since the worst case is pretty bad -> the engine content won't show up). First you'll need to build a debug build and then you can tap five times the Firefox logo on the "About" screen to enable the "Secret Settings" screen in the settings. Then the new setting to toggle is "Wait Until First Paint To Show Page Content". 

If you do end up testing it please report any issues with STR if possible in this issue and tag me. Thanks for your help! :)

**Comment by andreicristianpetcu** [comment] 2020-08-04 21:33
thank you @ekager 
can you please trigger a new build? https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.latest/arm64-v8a

**Comment by ekager** [comment] 2020-08-04 21:38
Secret settings are only available in debug builds for now because of the higher risk of breakage (which is what we previously did for the tabs tray) @andreicristianpetcu 

We could think about opening this up to more testers in Nightly once we minimize some risk 👍

**Comment by ekager** [comment] 2020-08-04 21:43
Actually on second thought, since it's in secret settings that's probably fine 😆 I'll change that and update here when that's done :)

**Comment by andreicristianpetcu** [comment] 2020-08-04 21:46
I found it here https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.debug.latest/arm64-v8a

**Comment by cadeyrn** [comment] 2020-08-05 08:07
@ekager This causes a worse user experience because now it flickers - there is first a white flash before the screen becomes dark.

**Comment by Booligoosh** [comment] 2020-08-05 10:10
It's working perfectly for me in the latest update, thank you!! (I have Dark Reader installed if that's relevant)

**Comment by jenabaivab** [comment] 2020-08-05 10:13
I tested the new build, and I have to say I agree with @cadeyrn . While this is definitely better than the current scenario, the flickering is also an issue now. Whenever I search, or change the tab content, it flickers bright white. At least now we are going somewhere with this, so it's great in my opinion. Just a bit more polishing and it'll be perfect.

**Comment by andreicristianpetcu** [comment] 2020-08-05 10:34
Thank you @ekager ! New tab works great. I don't use dark reader.
The only issue I have is the one mentioned above.
![ScreenRecord-2020-08-05-13-31-31](https://user-images.githubusercontent.com/922368/89402951-4d0f6000-d720-11ea-95cc-fe9da8832ed0.gif)

**Comment by Booligoosh** [comment] 2020-08-05 10:36
Oh, now that you mention it, I'm seeing that issue as well (with dark reader). Still an improvement though :)

**Comment by ekager** [comment] 2020-08-06 00:04
Hey ya'll! Landed some changes today that I think will improve the white flashes. Keep the feedback coming! I am going to be offline next week but will try to follow-up ASAP.

**Comment by cadeyrn** [comment] 2020-08-06 19:47
With the latest changes there are no longer white flashes.

**Comment by igalic** [comment] 2020-08-06 20:18
on

> Nightly 200806 06:02 (Build #22190614)
> AC: 53.0.20200804130112, 789a73eb2
> GV: 81.0a1-20200803094100
> AS: 61.0.10

from

> Thursday 8/6 @ 6:13 AM

still seeing white flash on page load

**Comment by mobd** [comment] 2020-08-07 01:32
It works almost perfectly for me, there are still white flashes with some redirects (in this case when using duckduckgo's bangs)

![ezgif-7-c539fa9f4b1e](https://user-images.githubusercontent.com/66154603/89598984-877f1700-d85e-11ea-9dba-d5dad0069e94.gif)

**Comment by yoasif** [comment] 2020-08-07 03:11
> y'all better appreciate this gif, and the hours and hours of work, blood and tears it took to convert an mp4 to a gif, because github doesn't accept mp4

@igalic I just zip up the mp4s - tip for next time.

**Comment by B0pol** [comment] 2020-08-07 08:51
GIF is better because we can stream it on GitHub.

You can lower your record quality (no need for 1080p) and convert to GIF with video transcoder on F-Droid (lower framerate or quality if it's higher than 10 MB), it will take you only few minutes

**Comment by jenabaivab** [comment] 2020-08-07 09:09
Current scenario on the latest Nightly Version

I'm guessing now the work to be done is by dark reader dev team. Basically negate the delay in changing the background. What do you guys think?
Or maybe increase the duration of black background a little till  the Extension kicks in.


![ezgif-5-afbd0bd4fc47](https://user-images.githubusercontent.com/60446763/89629462-7ca69f80-d8bb-11ea-9672-deb66c8b3ac8.gif)

**Comment by jenabaivab** [comment] 2020-08-07 09:13
Okay maybe not entirely. There are still flashes when I go back from settings to the webpage or from search tab to the web page

**Comment by Gusted** [comment] 2020-08-07 11:42
> I'm guessing now the work to be done is by dark reader dev team. Basically negate the delay in changing the background. What do you guys think?

Hi!

I'm from the dark reader team, who is just silent eating popcorn and watching this issue as it's impact our Fenix users.
I can confirm the first CSS we inject into the page is 
```CSS
html {
    background-color: #181a1b !important;
}
```
To make the page when not fully loaded yet already dark and try to prevent any further flashes. However it seems like their a is a notice able time between the Extensions starts(and the white flash starts) and until the code is injected(white flash ended). It's a bit unfortunate. As just injecting from Fenix side a dark html background-color and than after the First Contentful Paint removing it and hoping we were fast enough to inject our own CSS to take it over from their. 

I think their should get some conversation between us and Fenix developers about how to solve this issue on a good and reliable way. As a fast white flash is very annoying, I self get it on my phone way too often.

Regards,
Gusted

**Comment by jenabaivab** [comment] 2020-08-07 12:35
@Gusted I was about to contact the dark reader team on github, ha. Although, I think something has to be done from Fenix team as well regarding other pages. Like when the tab is switched, there is a flash, even though the page is loaded from before. Same with switching from the search tab to the main window. Minor things to tweak now for the perfect dark mode.

**Comment by Gusted** [comment] 2020-08-07 12:55
> even though the page is loaded from before.

Then it's probably out of memory and than it's technically not loaded into the memory anymore 🤷🏽‍♀️ 
Anyway, Firefox have contacted dark reader before and we are willing to implement fixes on our side too. So it will be hopefully fixed.

**Comment by jenabaivab** [comment] 2020-08-07 13:04
> Then it's probably out of memory and than it's technically not loaded into the memory anymore
I actually thought the same way, but I opened three tabs at the same time, and tried switching between them multiple times in a range of 30 seconds. Same result. :/


> Firefox have contacted dark reader before and we are willing to implement fixes on our side too. So it will be hopefully fixed.
That's awesome!

**Comment by jenabaivab** [comment] 2020-08-07 13:07
> Then it's probably out of memory and than it's technically not loaded into the memory anymore

I actually thought about this. I tried opening 3 tabs at the same time, and tried switching between them quickly in a matter of 30 seconds. Same result :/



> Firefox have contacted dark reader before and we are willing to implement fixes on our side too.

That's awesome!

**Comment by andreicristianpetcu** [comment] 2020-08-07 16:53
Pages don't seem to load now :( I need to open a new tab with the link. I'm also using new tab experience, if that matters.

![Screenshot_20200807-194824_Firefox_Nightly](https://user-images.githubusercontent.com/922368/89669124-8f36ce00-d8e7-11ea-9bb9-1fb366d3fff7.png)
![Screenshot_20200807-195145_Firefox_Nightly](https://user-images.githubusercontent.com/922368/89669128-91009180-d8e7-11ea-890c-954ab3a18eca.png)

**Comment by igalic** [comment] 2020-08-07 17:03
I've experienced that, or something similar for a while now, where reusing a tab is pretty much impossible, and sometimes after closing a tab, the one underneath will revert to showing the contents of the closed tab

but, I'm pretty, and sure, those issues are unrelated

**Comment by andreicristianpetcu** [comment] 2020-08-08 21:04
New finding! If I get a black tab like in my previous example and swipe left/right to switch tab and back again, I see the page content.

**Comment by opusforlife2** [comment] 2020-08-09 12:06
Is Reader Mode part of this effort? There is always a white flash before a page loads in Reader mode (whether Dark or Sepia). If it is unrelated to this issue, I'll open a new one.

**Comment by B0pol** [comment] 2020-08-11 06:23
There are still white flashes that happen a lot.

1. Go to a page
2. Open a link in a new tab
3. Close it by pressing the back button

Another one but is trickier, and maybe related to the dark reader & memory thing

1. Open a page
2. Leave fenix for few minutes
3. Open it again, white flash.

I will try to reproduce the second bug with a native dark website so that we can know if it is unrelated to darkreader

**Comment by jenabaivab** [comment] 2020-08-17 05:54
Anybody seeing any improvements for the white flashes? I'm still getting them regularly when closing search windows or changing tabs and such.

**Comment by hwinnemoe** [comment] 2020-08-20 20:38
Activating _Wait Until First Paint To Show Page Content_ causes a crash using the following STR: #13388.

**Comment by jenabaivab** [comment] 2020-09-02 06:21
Anybody seeing any changes? Is it being worked on?
On my device, there is still a bright flash when switching pages. Like going from settings/search to opened pages.

**Comment by igalic** [comment] 2020-09-02 07:13
I'm running 

Nightly 200901 06:03 (Build #2015761331)
AC: 57.0.20200831130101, b70bef444
GV: 82.0a1-20200829091226
AS: 61.0.13

on OnePlus 5t, running OxygenOS 10

and i still see white flashes every time Firefox starts or loads a new page, and often when it reloads the same page, too

**Comment by Gusted** [comment] 2020-09-02 14:54
> As just injecting from Fenix side a dark html background-color and than after the First Contentful Paint removing it and hoping we were fast enough to inject our own CSS to take it over from there.

As a person of my promises(I felt the urge to do something about this when posting that comment), I finally got around had a better look at the code injecting a white-flash killer CSS and thought the best idea to just shove it up a bit, to not rely on anything other than 2 little checks to make sure no bugs happen. So it won't go down the road on waiting until it receives a signal from the background-script to send all the settings and data along and then do some calculations to get the right background-color. All that micro-code was probably the notice-able small split second white flash people commented about here.

To not make this comment any longer than necessary. Here is the [PR about moving the white-flash killer CSS](https://github.com/darkreader/darkreader/pull/3533) moving to one of the first code being executed into the page. As of this also a new release has been made 4.9.17. Which has been since of writing successful pushed into [AMA](https://addons.mozilla.org/en-US/firefox/addon/darkreader/) 7 hours ago and should be available on Firefox Mobile. I hope this improves a lot from our side as well and reduce the white flash a lot(and the split-second white flash that was burning my eyes).

Have a nice day everyone!

Regards,
Gusted

**Comment by assist726** [comment] 2020-09-03 03:59
@Gusted Thanks so much, can finally make the switch from Kiwi over to Firefox.

Also just noticed if the page is stuck loading it would appear dark on view but in the multi-tab manager it would still appear white. Doesn't particularly bother me but figured I would point it out

**Comment by jenabaivab** [comment] 2020-09-03 05:41
![ezgif-2-f857fc688ecf](https://user-images.githubusercontent.com/60446763/92075359-f60bb200-edd5-11ea-9487-8e8f48a49ff8.gif)

@Gusted currently on the latest version. Both FF nightly and dark reader. Guess it needs a little more tuning.

**Comment by crisalis2** [comment] 2020-09-03 05:44
Thanks for the work! 

I noticed remaining flashes.

Keyboard-related. Something similar happens sometimes when the urlbar autohides.
![1](https://user-images.githubusercontent.com/65630147/92074941-a74f1f80-edb7-11ea-9836-f58790ac734f.gif)

Reader view-related.
![2](https://user-images.githubusercontent.com/65630147/92074953-afa75a80-edb7-11ea-947d-d37899682415.gif)

When quitting Firefox.
![3](https://user-images.githubusercontent.com/65630147/92074995-c5b51b00-edb7-11ea-93a6-9850510d4e01.gif)

Search. This doesn't happen most of the time, but sometimes it does.
![4](https://user-images.githubusercontent.com/65630147/92075032-db2a4500-edb7-11ea-8460-0dd7c317c67a.gif)

Same when loading pages in general: just now logging in on Github saw it. Most of the time there is no white when loading pages, though (it has improved a lot).

**Comment by Gusted** [comment] 2020-09-03 05:48
> Guess it needs a little more tuning.

Unfortunately I idd everything in power I can to get the css injected as wast as possible and the whole code itself should run under 16.66ms(1 animation/render frame)so its really a bit up to Firefox to probablyppolish the set initial color functionality and fast the the scripts get injected into the page and than bring executed. Something we can't control unfortunately.

**Comment by Rushilotti** [comment] 2020-09-03 07:34
I am on Firefox nightly latest version and I am still getting these flashes @Gusted

**Comment by 532910** [comment] 2020-09-03 08:00
still not fixed in the last nightly

**Comment by Rushilotti** [comment] 2020-09-03 08:18
I checked it on both beta and firefox nightly by downloading the latest dark reader addon.

Only the flashing happen when you loading something for the first time on a tab. After that every thing is dark. Even if you change the url in the same tab the dark background is there which is a good thing.

However if I change the tab the flash again occurs for the first load and remains dark after that whatever you are browsing.

Its a great step up from the previous every page white flash.

Thanks @Gusted for this.

May be firefox devs chip in and fix this even further I hope.

I can now switch from kiwi to newer firefox.

**Comment by 532910** [comment] 2020-09-03 08:32
> Only the flashing happen when you loading something for the first time on a tab.

False.

![ScreenRecord-2020-09-03-11-31-22](https://user-images.githubusercontent.com/14617699/92091276-31f44680-edd9-11ea-97da-1c012fc376c3.gif)

**Comment by B0pol** [comment] 2020-09-03 08:41
Did you enable « Wait Until First Paint To Show Page Content »?

If you don't, there is no difference between stable and nightly version, I.e. no fixes

@532910 @jenabaivab

**Comment by 532910** [comment] 2020-09-03 08:44
> secret settings

I see no secret settings, could you say, where they are?

**Comment by Rushilotti** [comment] 2020-09-03 08:57
> > Only the flashing happen when you loading something for the first time on a tab.
> 
> False.
> 
> ![ScreenRecord-2020-09-03-11-31-22](https://user-images.githubusercontent.com/14617699/92091276-31f44680-edd9-11ea-97da-1c012fc376c3.gif)
> 
> ![image](https://user-images.githubusercontent.com/14617699/92091406-62d47b80-edd9-11ea-82ea-6194f9d1c202.png)

May be reinstall dark reader?  I have no white flash after first page load.

**Comment by hwinnemoe** [comment] 2020-09-03 09:25
@532910 Tap five times on the "Firefox Browser"-logo on _About Firefox Nightly_, then the _Secret Settings_ option becomes available via _Settings_

**Comment by 532910** [comment] 2020-09-03 09:42
Still flashes white even with `Wait Until First Paint To Show Page Content` turned on and not `when you loading something for the first time`.

I see it **always**.

Hint to reproduce: make you internet connection slow.

**Comment by opusforlife2** [comment] 2020-09-03 11:46
At least in the case of Reader Mode, I've noticed there is a period where the tab stays on `about:blank`, which is a blinding white regardless of your chosen Fenix theme. I wonder how much of a difference it would make if `about:blank` was made dark grey or black when Fenix is set to Dark theme. If this page acts as an interstitial in other situations as well, there could be improvements there too.

**Comment by jenabaivab** [comment] 2020-09-03 12:52
> Did you enable « Wait Until First Paint To Show Page Content » in secret settings?
> 
> If you don't, there is no difference between stable and nightly version, I.e. no fixes
> 
> @532910 @jenabaivab

Always has been enabled

**Comment by jenabaivab** [comment] 2020-09-04 14:31
I think now it's on FF devs. Random flashes everywhere. Even when closing the settings page to resume browsing. A little more work from FF team should help iron out the remaining discrepancies.

**Comment by liuche** [comment] 2020-09-08 17:42
Is this something that GV can do, to set the background depending on app theme? I would say this is a P2, it's a really annoying bug but isn't say, a crash.

**Comment by liuche** [comment] 2020-09-08 17:42
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1663732

**Comment by spphinslove** [comment] 2020-09-13 16:14
I think this desktop version also has this problem.
![图片](https://user-images.githubusercontent.com/11383988/93023109-41686080-f61f-11ea-9816-ba56fa9286da.png)

**Comment by saschanaz** [comment] 2020-09-13 16:18
@spphinslove What version are you using? AFAIK it has been showing gray screen instead recently.

**Comment by andreicristianpetcu** [comment] 2020-09-13 18:20
@spphinslove does it happen with this theme also? https://addons.mozilla.org/en-US/firefox/addon/borderless-dark/ if yes, please report it on bugzilla and link it here

**Comment by hwinnemoe** [comment] 2020-09-13 19:46
This is already reported by https://github.com/mozilla-mobile/fenix/issues/6313#issuecomment-689033972, it tracks both WebRender for Android as well as WebRender for desktop Nightly 83.

**Comment by spphinslove** [comment] 2020-09-14 16:00
> 
> 
> @spphinslove does it happen with this theme also? https://addons.mozilla.org/en-US/firefox/addon/borderless-dark/ if yes, please report it on bugzilla and link it here

I use this theme also white screen,it's a bug?
link is here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1664837
![Uploading 图片.png…]()

**Comment by spphinslove** [comment] 2020-09-14 16:04
> 
> 
> @spphinslove What version are you using? AFAIK it has been showing gray screen instead recently.

80.0.1 x64

**Comment by linsui** [comment] 2020-10-02 05:52
I can see white flash on PWA while it seems fixed in browser.

**Comment by igalic** [comment] 2020-10-02 17:58
not for me, @linsui, I'm getting white flashes in both

**Comment by ShalokShalom** [comment] 2020-10-16 01:27
All loading screens all white all the time with all dark themes.
Mobile and desktop.

**Comment by mbestavros** [comment] 2020-10-25 20:01
@ekager Not sure if this is the right issue to report it, but --

I just updated to the latest Fenix Nightly:

```
Nightly 201024 17:01 (Build #2015771595)
AC: 64.0.20201023143136, d78abdf9f
GV: 84.0a1-20201022093646
AS: 63.0.0
```

The hidden pref to "Wait until first paint to show page content" seems to be gone in this build. My understanding from reading this issue and related Bugzilla issues is that this was eventually intended once a better fix had been implemented in GeckoView/Android Components etc. My hope was that meant the fix had made it to Nightly -- but unfortunately, I'm still noticing white flashes all over the place. Loading pages, opening new tabs (sometimes) -- it's happening in lots of places it didn't when the experimental feature was still available.

Just FYI, since it seems like there is work in this area happening right now.

**Comment by ekager** [comment] 2020-10-26 16:37
Yes, this is expected we want to remove the hacks that the hidden pref was working around. Instead, we can now change the "clear color" of the engine, but there is still currently a short flash. One followup issue filed is https://github.com/mozilla-mobile/android-components/issues/8752

**Comment by LaurentiuApahideanSV** [comment] 2020-11-02 13:37
Verified as fixed on Firefox Preview Nightly 201102 (Build #2015773227).
### Devices used:
- Samsung Galaxy S9 (Android 8.0.0)
- OnePlus 6T (Android 9)

**Closed** 2020-11-02 13:38 UTC
Labels: E5, Feature:Themes, eng:qa:verified, feature request 🌟, needs:gv

**Comment by crisalis2** [comment] 2020-11-06 03:30
Shouldn't page color match Firefox's dark UI color? Right now they are two very different shades of gray.

**Comment by opusforlife2** [comment] 2020-11-06 05:30
My eyes thank you every day, @ekager.

**Comment by strugee** [comment] 2020-11-06 18:13
@crisalis2 yes, open a new issue and reference this one in it.
