### ISSUE TITLE
[Bug] Favicon for 2 pages of the same site do not load at the same time

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#5040] opened 2019-08-30 15:30 UTC
## Steps to reproduce
- Open Fenix
- Open the 2 following URLs: 
https://www.franceculture.fr/emissions/series/comment-achever-une-oeuvre-travail-et-processus-de-creation

https://www.franceculture.fr/religion-et-spiritualite/mes-quatre-annees-aux-cotes-du-pape-francois?utm_medium=Social&utm_source=Facebook#Echobox=1566724293
- go back to the Tab list

### Expected behavior
Both tabs should show the same favicon

### Actual behavior
Only one of the 2 tabs show the correct favicon, the other shows the default one.
Depending on the order you have opened the 2 urls, it will be either one or the other.

![image](https://user-images.githubusercontent.com/218971/64032889-a7d12c80-cb4b-11e9-8378-cd602d3c46de.png)

### Device information

* Android device: Redmin Note 7 Android 9
* Fenix version: #12420615

**Comment by NotWoods** [comment] 2019-08-30 15:50
Duplicate of #5039

**Closed by NotWoods** 2019-08-30 15:50 UTC
Labels: 🐞 bug
