### ISSUE TITLE
[Bug] Cannot share tabs between versions of Firefox

### ISSUE THREAD

**Issue by concastinator** [mozilla-mobile/fenix#7394] opened 2019-12-28 10:15 UTC
## Steps to reproduce

1. Install both Firefox Preview 3 and Firefox Preview Nightly.
2. Open at least 2 tabs in any of the browsers (Nightly, for instance).
3. Go to to the screen with open tabs in Nightly and choose "Share tabs" in the "dots" menu.
4. In the list of applications to share with choose the other browser (Preview 3, in our example).
5. Switch to Preview 3 and notice that a single tab has been shared (and opened, which should not happen), instead of all of them.

### Expected behavior

All the open tabs should be shared between browsers, and none should be opened by default.

### Actual behavior

A single tab is shared, and this is opened by default.

### Remarks

1. The same happens if one wants to share collections.
2. Sharing between the browser and Messages, Keep Notes or WhatsApp works as expected; it seems to be broken only between browsers (I have not tested browsers other than Preview 3 and Nightly).

### Device information

* Android device: Nokia 5 (model TA-1024) with Android 9 (Android One program).
* Fenix version: Preview 3.0.1 and Nightly 191226 18:01 (build 13601807).

**Comment by AndiAJ** [comment] 2019-12-30 12:25
Dupe of [#4178](https://github.com/mozilla-mobile/fenix/issues/4178) ?

**Closed** 2019-12-30 15:16 UTC
Labels: Feature:SendTab, P2, S2, 🐞 bug
