### ISSUE TITLE
Reinstate Ability to View Source

### ISSUE THREAD

**Issue by userX-324-A** [mozilla-mobile/fenix#14758] opened 2020-09-05 04:43 UTC
The current version of FF Android removed the ability to view page source. Please add it back. Seeing the underlying source is invaluable when troubleshooting, debugging, and automating.

**Comment by RachitKeertiDas** [comment] 2020-09-05 05:55
Possible duplicate of #3972.

**Comment by s-ankur** [comment] 2020-09-05 17:30
Duplicate of https://github.com/mozilla-mobile/fenix/issues/3710

**Comment by svein83** [comment] 2020-09-14 16:29
The removal of this functionality made the browser a toy for consumers instead of a tool for developers...

**Closed** 2020-09-16 23:51 UTC
Labels: needs:triage
