### ISSUE TITLE
[Bug]annoying keyboard behavior 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#16709] opened 2020-11-22 12:27 UTC
since last 3 days in nighlty when home page changes were introduced where u can both tap top sites or perform search, keyboard (swiftkey) is misbehaving really bad. 
in I tap url bar and perform search keyboard is NOT DISMISSED also tapping a bookmark or history entry from url bar won't dismiss keyboard when loading tab. 
super annoying
also me as many other people on reddit would have like to see top sites when tapping url bar not a solid background (even the overlay has been removed lately) so disappointing and frustrating .

**Comment by hakkikaancaliskan** [comment] 2020-11-22 15:27
Duplicate of #16668 
Please don't open new issue. It's weekend. I'm sure devs will care about it.

**Comment by sflorean** [comment] 2020-11-23 17:03
Closing as a dupe of #16668.

**Closed by sflorean** 2020-11-23 17:03 UTC
Labels: needs:triage, 🐞 bug
