### ISSUE TITLE
FNX3-16977 ⁃ [Bug] Home screen(Logo and search bar) are displayed when changing the theme at first launch

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3379] opened 2019-06-12 10:33 UTC
## Steps to reproduce
1. Launch Fenix.
1. Scroll down.
1. Change the theme from **`Light`** to **`Dark`.**
    1. Expected behavior
When changing the theme a smooth transition should be displayed.
    1. Actual behavior
When changing the theme the **`Firefox preview**` Logo and search bar are displayed.
    1. Device information

* Android device: **{{HTC One M9(Android 6) Samsung Galaxy Note 9(Android 8.1) }}**
* Fenix version: **{{ 6/12}}**
    1. Notes
Please note that for devices with a larger screen you should scroll down in order to reproduce this issue(Samsung Galaxy Note 9(Android 8.1)).
* [video](https://drive.google.com/file/d/1IOZjvnIvCs5rrNj6Rmpfgsy8Hbniq2DV/view?usp=sharing)

**Comment by sblatz** [comment] 2019-07-20 00:41
This is because we're recreating the activity and then scrolling the user to that position. This is likely a very difficult fix.

**Comment by NotWoods** [comment] 2019-10-05 00:14
This seems to be fixed with the new home screen design.

**Comment by sv-ohorvath** [comment] 2019-10-09 12:32
I can't reproduce this either on the latest Nightly 10/9.
Devices: Pixel 3 (Android 9), HTC Desire 820 (Android 6.0.1)

**Closed** 2020-08-12 17:34 UTC
Labels: Feature:Onboarding, P5, S2, eng:qa:verified, 🐞 bug
