### ISSUE TITLE
[Bug]Broken test app color selection in both the browser and in custom tabs

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8965] opened 2020-03-04 09:36 UTC
## Prerequisites
Have any of the bellow mentioned Mozilla products set as default browser.

## Steps to reproduce
1. Open https://daleharvey.github.io/testapp/ in a custom tab
2. Tap and open the "Choose a color" ![rsz_screenshot_20200304-112952](https://user-images.githubusercontent.com/51314259/75865340-1305ff00-5e0c-11ea-8bfa-7991ca211e8e.png)

### Expected behavior
Properly displayed color selection segment

### Actual behavior
Improperly displayed (blank), can't distinguish the actual featured color options

### Device information

* Android device:
• Huawei Mate 20 Lite (Android 8.1.0)
• Huawei P9 Lite (Android 7.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: 
• Nightly #20640607 from 3/4
• Beta 4.0.0-beta.3

### Notes
❗️ Works on Fennec.

► Video
![20200304-112200](https://user-images.githubusercontent.com/51314259/75865013-88250480-5e0b-11ea-9142-81c9b0f59852.gif)

**Comment by Diana-Rus** [comment] 2020-04-14 15:12
Hi, issue reproduces with Google Pixel 3 XL (Android 9) and Samsung Galaxy S9 (Android 8) with Beta 4.3.0-beta.1.

**Comment by ekager** [comment] 2020-04-18 05:41
Will be addressed by https://github.com/mozilla-mobile/android-components/pull/6704

**Comment by ekager** [comment] 2020-04-23 05:00
AC PR has merged, so the next Fenix Nightly should pick up the changes.

**Comment by sv-sdeiac** [comment] 2020-04-24 09:15
Hi, the issue is still reproducible using the latest version of Firefox Preview Nightly 4/24 #21150607.

Devices:
- Samsung Galaxy Note 8 (Android 9);
- Samsung Galaxy Tab S6 (Android 9);
- Xiaomi Mi 8 Lite (Android 9);
- LG G7 fit (Android 8.1);
- Huawei MediaPad M2 (Android 5.1.1).

I'll retry with the next build when it comes just to see if the issue is still reproducible. Till that, I'll remove the qa:needed flag, thanks.

**Comment by sv-sdeiac** [comment] 2020-04-27 06:30
Hi, I can confirm that using the latest version of Firefox Preview Nightly 4/27 #21180608 the issue is fixed.

Devices:
- Huawei MediaPad M2 (Android 5.1.1);
- LG G7 fit (Android 8.1);
- Samsung Galaxy Note 8 (Android 9).

**Closed by sv-sdeiac** 2020-04-27 06:30 UTC
Labels: Feature:CustomTabs, S2, b:web-content, needs:ac, 🐞 bug
