### ISSUE TITLE
FNX-4658 ⁃ [Bug] Share button is giant on In-App browser

### ISSUE THREAD

**Issue by javierlm** [mozilla-mobile/fenix#10884] opened 2020-05-24 21:15 UTC
## Steps to reproduce
Open any link in an app, and see the bottom bar of Firefox Beta with an enormous share button.

### Expected behavior
The size of the share button must be proportional to the rest of buttons.

### Actual behavior
The size is quite big.

![Screenshot](https://user-images.githubusercontent.com/34691743/82765099-a8ad9b00-9e0b-11ea-94b9-af787c9f5089.jpg)UNITO-UNDERSCORE!20200524-220812!

### Device information
Oneplus 6, latest stable update.

* Android device: Oneplus 6
* Fenix version: Firefox Beta 75.0.0-beta.6(Build #2015735819)
It happens with Firefox Nightly too. Version 200524 06:01 (Build #21450607)

**Comment by Dunexus** [comment] 2020-05-24 21:53
Looks like this is same as https://github.com/mozilla-mobile/fenix/issues/10451

**Comment by mcarare** [comment] 2020-05-25 10:46
Duplicate of #10451.

**Closed** 2020-08-10 22:31 UTC
Labels: needs:triage, 🐞 bug
