### ISSUE TITLE
FNX-4423 ⁃ Tab strip / Tabbed browser (like Fennec)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10607] opened 2020-05-12 19:29 UTC
### Why/User Benefit/User Problem
As a user, I would like to see tabs on Fenix like I am used to in Fennec and on desktop. 

![signal-attachment-2020-05-12-152608](https://user-images.githubusercontent.com/152493/81736767-17cadd00-9465-11ea-909c-139c9bbe071e.png)

Beta users have [asked](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta&hl=en_US&reviewId=gp%3AAOqpTOGnPYVCNQi36LGZLkJ39O4j8XyGbYfPy5e5B5yESJBp9qpVSnPjnFcQqCyo_vavPDHFVZKoK7uO0sG2Lw) about this.

### What/Requirements
1. An option in the customize section of settings that allows users to enable a tabbed browser. This exists in Vivaldi as an option for "tab strip."
1. User can tap tabs to switch to them.
1. User can rearrange tabs by dragging them. 

### Acceptance Criteria (how do I know when I’m done?)
Users have visible tabs in their browser like in Fennec.

**Comment by kbrosnan** [comment] 2020-05-12 20:28
Dupe of #2344

**Closed** 2020-08-11 01:10 UTC
Labels: b:tablet, feature request 🌟
