### ISSUE TITLE
[Bug] back button crashes

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#7174] opened 2019-12-15 00:06 UTC
## Steps to reproduce
open a page
hit back
### Expected behavior
not crash
### Actual behavior
it crashed
### Device information

* Android device: OnePlus5t
* Fenix version: latest nightly

**Comment by LittleAngelwings** [comment] 2019-12-15 05:18
Can confirm this for this nightly build: Nightly 191214 18:00 (Build #13481808)
26.0.0, d06f59e53
GV: 73.0a1-20191212095326

`12-14 23:55:30.463 E/WindowManager(2942): win=Window{71e9c43 u0 Splash Screen org.mozilla.fenix.nightly EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0, caller=com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5646 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:553 com.android.server.wm.DisplayContent.lambda$-com_android_server_wm_DisplayContent_21578:476 
12-14 23:55:33.006 E/mozac-webcompat(15459): Failed to install WebCompat webextension: webcompat@mozilla.com
12-14 23:55:33.006 E/mozac-webcompat(15459): 	at org.mozilla.geckoview.CallbackResult.sendError(CallbackResult.java:2)
12-14 23:55:33.006 E/mozac-webcompat(15459): 	at org.mozilla.gecko.EventDispatcher$JavaCallbackDelegate$1.run(EventDispatcher.java:3)
12-14 23:55:49.408 E/MessageQueue-JNI(15459): java.lang.NoSuchMethodError: No interface method canClearSelection()Z in class Lmozilla/components/concept/engine/EngineView; or its super classes (declaration of 'mozilla.components.concept.engine.EngineView' appears in /data/app/org.mozilla.fenix.nightly-8lK9X0Pacd56pWrXL3_zLQ==/base.apk)
12-14 23:55:49.408 E/MessageQueue-JNI(15459): 	at mozilla.components.feature.session.SessionFeature.onBackPressed(SessionFeature.kt:4)
12-14 23:55:49.408 E/MessageQueue-JNI(15459): 	at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.onBackPressed(ViewBoundFeatureWrapper.kt:3)
12-14 23:55:49.408 E/MessageQueue-JNI(15459): 	at org.mozilla.fenix.browser.BaseBrowserFragment.onBackPressed(BaseBrowserFragment.kt:3)
12-14 23:55:49.408 E/MessageQueue-JNI(15459): 	at org.mozilla.fenix.browser.BrowserFragment.onBackPressed(BrowserFragment.kt:1)
12-14 23:55:49.408 E/MessageQueue-JNI(15459): 	at org.mozilla.fenix.HomeActivity.onBackPressed(HomeActivity.kt:5)
12-14 23:55:49.410 E/AndroidRuntime(15459): Process: org.mozilla.fenix.nightly, PID: 15459
12-14 23:55:49.410 E/AndroidRuntime(15459): java.lang.NoSuchMethodError: No interface method canClearSelection()Z in class Lmozilla/components/concept/engine/EngineView; or its super classes (declaration of 'mozilla.components.concept.engine.EngineView' appears in /data/app/org.mozilla.fenix.nightly-8lK9X0Pacd56pWrXL3_zLQ==/base.apk)
12-14 23:55:49.410 E/AndroidRuntime(15459): 	at mozilla.components.feature.session.SessionFeature.onBackPressed(SessionFeature.kt:4)
12-14 23:55:49.410 E/AndroidRuntime(15459): 	at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.onBackPressed(ViewBoundFeatureWrapper.kt:3)
12-14 23:55:49.410 E/AndroidRuntime(15459): 	at org.mozilla.fenix.browser.BaseBrowserFragment.onBackPressed(BaseBrowserFragment.kt:3)
12-14 23:55:49.410 E/AndroidRuntime(15459): 	at org.mozilla.fenix.browser.BrowserFragment.onBackPressed(BrowserFragment.kt:1)
12-14 23:55:49.410 E/AndroidRuntime(15459): 	at org.mozilla.fenix.HomeActivity.onBackPressed(HomeActivity.kt:5)
12-14 23:55:57.023 E/audit   (2682): type=1327 audit(1576364157.021:13477): proctitle="org.mozilla.fenix.nightly:mozilla.components.lib.crash.CrashReporter"
12-14 23:55:58.957 E/WindowManager(2942): win=Window{2ac1cd8 u0 org.mozilla.fenix.nightly/mozilla.components.lib.crash.prompt.CrashReporterActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0, caller=com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5646 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:517 com.android.server.wm.TaskStack.stepAppWindowsAnimation:2021 
12-14 23:55:59.246 E/WindowManager(2942): win=Window{c383b05 u0 Splash Screen org.mozilla.testpilot.notes EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0, caller=com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5646 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:553 com.android.server.wm.DisplayContent.lambda$-com_android_server_wm_DisplayContent_21578:476 
12-14 23:56:01.243 E/audit   (2682): type=1327 audit(1576364161.241:13478): proctitle="org.mozilla.testpilot.notes"
12-14 23:56:01.817 E/WindowManager(2942): win=Window{78cf7b2 u0 org.mozilla.testpilot.notes/org.mozilla.testpilot.notes.MainActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8, caller=com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5646 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:553 com.android.server.wm.DisplayContent.lambda$-com_android_server_wm_DisplayContent_21578:476 
[2019-12-14-23-58-47.txt](https://github.com/mozilla-mobile/fenix/files/3964626/2019-12-14-23-58-47.txt)
`

**Comment by LittleAngelwings** [comment] 2019-12-15 05:25
Btw: duplicate of this https://github.com/mozilla-mobile/fenix/issues/7173

**Comment by lindongbin** [comment] 2019-12-15 07:11
fixed

Nightly 191215 06:01 (Build #13490610)
26.0.0, d06f59e53
GV: 73.0a1-20191212095326

**Comment by LittleAngelwings** [comment] 2019-12-15 09:07
Verified as fixed in lasted Nightly.

Nightly 191215 06:01 (Build #13490609)
26.0.0, d06f59e53
GV: 73.0a1-20191212095326

**Comment by andreicristianpetcu** [comment] 2019-12-16 07:03
fixed

**Closed** 2019-12-16 07:03 UTC
Labels: 🐞 bug
