### ISSUE TITLE
[Feature Request] Order/Sort For Bookmark

### ISSUE THREAD

**Issue by zpcol** [mozilla-mobile/fenix#14502] opened 2020-08-30 20:09 UTC
creating a new folder on bookmarks is always in the bottom row, uncomfortable.

**Comment by cadeyrn** [comment] 2020-08-30 20:23
Duplicate of #4348.

**Comment by kbrosnan** [comment] 2020-08-30 21:23
Closing as a duplicate

**Closed by kbrosnan** 2020-08-30 21:23 UTC
Labels: needs:triage
