### ISSUE TITLE
FNX-3358 ⁃ [Bug] Firefox shows blank screen when the tab was shut after launching from home screen shortcut

### ISSUE THREAD

**Issue by ra-hardy** [mozilla-mobile/fenix#10211] opened 2020-04-25 12:45 UTC
## Steps to reproduce
1. Launch Firefox and close any tabs
1. Launch Firefox again from a home screen shortcut
1. Use the phone's task switcher to go to the first 'instance' of Firefox and close the tab
1. Use the phone's task switcher to go to the second instance of Firefox

### Expected behavior
Unclear - as the tab was closed the second instance shouldn't exist.  Or maybe it should show the web page for the tab that was closed

### Actual behavior
Firefox shows a blank screen (black or white)

### Device information
* Android device: Samsung Galaxy S10, Android 10, One UI 2.1
* Fenix version: 75.0.0-beta.6

**Comment by sv-sdeiac** [comment] 2020-04-27 08:33
Hi @ra-hardy, thanks for your report. 
Unfortunately, I was not able to reproduce your problem using the latest version of Firefox Preview Nightly 4/27 #21180608.

Devices:
- LG G7 fit (Android 8.1);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel (Android 10).

Could you send us a video with your exact steps to reproduce the issue, it will help us to understand how to track the problem. 
I'll wait for your updates, thanks.

**Comment by ra-hardy** [comment] 2020-04-27 12:48
I've put a video here at this link. Let me know if I should upload instead
https://photos.app.goo.gl/XVWQxQusP619dnGy7

**Comment by ebalazs-sv** [comment] 2020-04-27 14:09
@ra-hardy Thanks for the video! 

I had tested this on the latest Beta Migration build 75.0.0-beta.6 (Build #2015735817) from 4/21, with Nexus 5 (Android 6.0.1), OnePlus 6T (Android 9) and I can reproduce your issue following the steps:
1. Add home screen shortcuts on Fennec Beta;
2. Migrate to Fenix Beta;
3. Launch Fenix Beta;
4. Open a home screen shortcut;
5. Go to Fenix Beta and close the opened tab;
6. Go to Recent Apps and tap the custom tab;

The home screen shortcut that is opened in a custom tab becomes unusable. 
There are 2 related migration issues regarding this:
https://github.com/mozilla-mobile/android-components/issues/6328
https://github.com/mozilla-mobile/android-components/issues/6327

**Comment by eliserichards** [comment] 2020-04-27 18:54
Possibly related to #10239?

**Comment by Mugurell** [comment] 2020-06-16 13:56
I tested this in latest release / beta and nightly and for me it is not reproduceable.
Might have been fixed in the issues Eliza mentioned in https://github.com/mozilla-mobile/fenix/issues/10211#issuecomment-620011678.

@ebalazs-sv , @ra-hardy Can you please confirm if this is still reproducing for you and if so with what applications?

**Comment by Mugurell** [comment] 2020-06-18 06:10
Small update: This is still reproduceable. Seems related to https://github.com/mozilla-mobile/fenix/issues/11472.

**Comment by ebalazs-sv** [comment] 2020-06-22 12:25
@Mugurell I had tested this on the latest Beta Migration 5.2.0-beta.2 (Build #2015746673) from 6/16, with Nexus 5 (Android 6.0.1), Motorola Moto G6 (Android 8) and I could not reproduce the issue, due to the fact that the home screen shortcuts are opened only in the custom tab and not in the Fenix app as well.

**Comment by Mugurell** [comment] 2020-06-23 14:55
Thank you Eliza!
Based on the above and with #11472 and #9144 being verified as fixed I think we can close this then.

**Closed** 2020-08-10 19:37 UTC
Labels: Feature:CustomTabs, Feature:Migration, 🐞 bug
