### ISSUE TITLE
[Bug] noticeable movement of "Shortcuts" button when tapping the address bar

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#4565] opened 2019-08-06 19:19 UTC
### Actual behavior

There was a recent change to show all the search engines when tapping the address bar. This causes a movement of the "Shortcuts" button which is much more visible than before. It was not a problem before this change because the "Shortcuts" button was not active and you didn't notice the movement from bottom to top. But now the button has an active state by default and after tapping the address bar you first the blue button on the bottom and then you see how it moves to the top which is very noticeable. That's bad for the _perceived performance_ of Fenix.

### Expected behavior

You should not notice the movement of a blue button from the bottom to the top. Maybe set the active status after the transition and not before?

### Device information

* Android device: HTC U11 / Android 9.0
* Fenix version: master branch revision 3c1ce90f6f8ab6478b498ec9fdf5ab59831255bc

**Comment by codrut-topliceanu** [comment] 2020-02-10 11:27
@cadeyrn Is this still reproducible? I'm not seeing it on the latest build from master.

**Comment by cadeyrn** [comment] 2020-02-10 11:33
I think it looks okay now. But please note that I have a much faster device now, I can no longer speak about the HTC U11.

**Comment by codrut-topliceanu** [comment] 2020-02-10 11:35
It looks okay on LG K4 (android 6) as well.

**Comment by AndiAJ** [comment] 2020-02-11 12:59
Hi, I've re-check this matter on the latest **`Nightly #20420611 from 2/11 `** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

The issue seems to be **still reproducible**. 
Analyzing the **time lapsed** video can offer a better overview of the actual movement and trajectory of the "Shortcuts" button.

► Video from Samsung Galaxy S7
![20200212-222209](https://user-images.githubusercontent.com/51314259/74237969-67bacc00-4cdd-11ea-8640-c84122086d13.gif)


► **Time lapsed** video from Samsung Galaxy S7
![20200212-222315](https://user-images.githubusercontent.com/51314259/74238733-0eec3300-4cdf-11ea-92ff-c6464feebf65.gif)

@cadeyrn - I would kindly ask you to confirm if this was the problem encountered by you in the past? ☺️

**Comment by darkwing** [comment] 2020-02-12 02:00
@AmyYLee Unless you see an issue here, I think we should close this.

**Comment by AmyYLee** [comment] 2020-02-12 16:55
> @AmyYLee Unless you see an issue here, I think we should close this.

@darkwing yes please close this.

**Closed** 2020-02-12 17:02 UTC
Labels: Feature:Search, P2, S2, needs:UX-feedback, 🐞 bug
