### ISSUE TITLE
Firefox for Android 79.0.5 : Keyword searches are broken / Make keyword searches have highest priority again

### ISSUE THREAD

**Issue by j-s-a-m** [mozilla-mobile/fenix#14570] opened 2020-09-01 07:53 UTC
Since the latest update(s) of Firefox for Android the keyword searches are not working as expected anymore.

Example / steps to reproduce:

I have a Jira keyword search defined in my Firefox bookmarks like "j" stands for

https://issues.mycompany.com/jira/secure/QuickSearch.jspa?searchString=%s

But when I enter "j TICKET-1234" into the "Search or address" text field of the new Firefox, I get a Google search for  "j TICKET-1234".

Please make sure that keywords defined in favorites always have highest priority.

This bug is completely breaking my workflows

**Comment by hwinnemoe** [comment] 2020-09-01 08:36
Duplicate of #12099, #14327

**Closed** 2020-09-01 21:38 UTC
Labels: needs:triage

**Comment by j-s-a-m** [comment] 2020-09-03 06:21
For the record:

The two tickets (#12099, #14327) linked by @hwinnemoe are less explicit than #14337 ("[Bug] Smart keywords no longer work"), #14570 ("Firefox for Android 79.0.5 : Keyword searches are broken / Make keyword searches have highest priority again") and #14571 ("[Bug] 79 removed the "keyword" functionality from bookmarks - I would like it back"), 

because they do not mention that new latest Firefox for Android has broken a functionality that has been working perfectly before. #12099 is in fact a **feature request** about editing keywords, #14327 is an **investigation ticket** about exposing APIs.

The linked tickets may be about a relating topic (keyword searches), but I do not consider them to be real duplicates of the aforementioned **bug tickets**.

**Comment by hwinnemoe** [comment] 2020-09-03 10:52
_(I will only answer in this issue to lower the amount of notifications this message creates.)_

I did not close your issue, that was a mozilla developer.

Firefox for Android starting with version 79 is a completely new implementation: "Fenix (internal codename) is the all-new Firefox for Android browser, based on GeckoView and Mozilla Android Components." (https://github.com/mozilla-mobile/fenix#firefox-for-android). Thus, any features that have not been implemented (yet) are feature requests, not bugs.

You mention that #12099 is about editing keywords - that is false. #12099 _is_ about adding support for bookmark keywords, editing keywords is #12100.

If you want to voice your support for a feature, please do not copy & paste the same text into three different issues. This creates notifications for all users and developers that follow these issues. You can always +1 the issue of a feature you would like to get implemented. Always feel free to add a comment if you think that a feature request misses an essential aspect of that feature.

**Comment by j-s-a-m** [comment] 2020-09-04 06:49
Thanks for the explanations.

Removing basic functionality like the bookmark keyword feature in successor versions of established software is one of the biggest mistakes you can do. I have seen that before. App reputation in Google Play Store is easy to destroy, but hard to rebuild.

To me, it's a question of mindset whether missing features should be considered as bugs or not. To the majority of users, it does not really matter whether the implementation has been rewritten from scratch or not. The average user only notices that that latest version of Firefox for Android is breaking things that were fine before. But of course, technically speaking, the missing features are now feature requests.
