### ISSUE TITLE
[Bug] Firefox Nightly keeps crashing

### ISSUE THREAD

**Issue by paai** [mozilla-mobile/fenix#19441] opened 2021-05-08 14:27 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Install Firefox Nightly (FN) from Google play

### Expected behavior
A functioning Firefox Nightly

### Actual behavior

FN shows blank screen and after a minute or so goes in an endless  crash - restart - crash loop.

### Device information
LG V400 with cyanogenmod 12.1, android 5.1 

* Firefox for Android version: ? (go to Settings -> About Firefox)
 
I cannot even get to the version information in FN because of the crashes.

Firefox Nightly has been running satisfactory for weeks. Three days ago (5 may) I updated it from Google Play and since then it has not worked any more.

I  did a factory reset and installed  FN as the only app on the tablet. That did not change the problem.

Vanilla Firefox and other programs run OK.

**Comment by kbrosnan** [comment] 2021-05-09 16:54
Please provide crash IDs or a logcat. https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by paai** [comment] 2021-05-09 18:05
Sorry, cannot do that, because when FN crashes, it gets stuck in a loop 
that only gives the 'close' or 'restart firefox' message. I have to go 
to Android settings->apps and stop Firefox.

**Comment by kbrosnan** [comment] 2021-05-10 08:11
Then use the logcat steps further down the page.

**Comment by lobontiumira** [comment] 2021-05-20 12:15
I was not able to reproduce the crash. I've installed Firefox Nightly from PlayStore on a Samsung Galaxy Tab A6 (Android 5.1.1), and on a Xiaomi Mi4i (Android 5.0.2) device.

**Comment by SoftVision-LorandJanos** [comment] 2021-11-18 07:50
This issue is not reproducible on the latest Nightly 96.0a1 (2021-11-18).
I will close this ticket as fixed.
Tested with: Xiaomi Mi11 (Android 11).

**Closed by SoftVision-LorandJanos** 2021-11-18 07:50 UTC
Labels: 🐞 bug, b:crash, needs:triage, wontfix, qa-triaged
