### ISSUE TITLE
Desktop website due to "Tablet" string in the user agent

### ISSUE THREAD

**Issue by Akraz86** [mozilla-mobile/fenix#28258] opened 2022-12-20 18:45 UTC
### Steps to reproduce

Visit any webpage in the browser

### Expected behaviour

USER-AGENT: Mozilla/5.0 (Android 13, Mobile; rv:110.0_)Gecko/110.0 Firefox/110.0

### Actual behaviour

USER-AGENT: Mozilla/5.0 (Android 13, Tablet; rv:110.0_)Gecko/110.0 Firefox/110.0

### Device name

Google Pixle 6

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

110

### Additional information

I do not know where to turn for this issue.

Ive been using Firefox Nightly on my Pixel-phones for a year or two now. A couple months ago, Firefox Nightly did an update, and a lot of web pages I visit have been returning strange on my phone. Either the text is way too small, almost like Desktop mode is enabled, or graphs and texted are skewed.

I have tried disabling my apps, which there are only 3: Dark Reader, Bitwarden, uBlock Origin. But it does not solve the issue.

Last night I started to research browser request data and a few websites returned some output on my Pixel 6 phone

USER-AGENT: Mozilla/5.0 (Android 13, Tablet; rv:110.0_)Gecko/110.0 Firefox/110.0

My work phone, a Samsung S21FE, Returns the following on Nightly

USER-AGENT: Mozilla/5.0 (Android 13, Mobile; rv:110.0_)Gecko/110.0 Firefox/110.0

When I switch my Firefox Nightly to Desktop Mode on this webpage, the USER-AGENT returns as

Mozilla/5.0 (x11: Linux x86_64; rv:110.0) Gecko/20100101 Firefox/110.0

Switching back to mobile mode thinks the phone is a tablet.

When I open normal Firefox or Firefox Focus, my user-agent returns as USER-AGENT: Mozilla/5.0 (Android 13, Mobile; rv:108.0_)Gecko/110.0 Firefox/108.0

So everything is fine, but Firefox Nightly thinks my phone is a Tablet... WHY!!!

I have tried looking online from Mozilla white-papers and resetting the user-agent in the browser does not work, nor does it apply to phone browsers. I cant find anything about this online.

Hoping someone here can really help me out. Thank you

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22167)

**Comment by Akraz86** [comment] 2022-12-20 18:55
![Screenshot_20221220-135426](https://user-images.githubusercontent.com/121126784/208744284-145e8eb3-2e18-4fdd-900d-dc82cb1eb1b7.png)


Firefox nightly on my pixel 6 phone

**Comment by kbrosnan** [comment] 2022-12-20 21:27
It is because of the Tablet in the user agent. How are you triggering that or did you use something to override the user agent? Are you using the Mozilla build of Firefox or a fork?

**Comment by Akraz86** [comment] 2022-12-20 21:33
> It is because of the Tablet in the user agent. How are you triggering that or did you use something to override the user agent? Are you using the Mozilla build of Firefox or a fork?

I want to believe my browsing issues are because of the Tablet identifcation in the user-agent.

I am using Firefox Nightly installed from the Google Play Store. No funny business. no mods. I run a vanilla Pixel 6, not rooted or anything fancy.

**Comment by Akraz86** [comment] 2022-12-21 15:44
I have Chrome, normal Firefox, Firefox Focus to prove and troubleshoot my issue and they all return as Mobile. Firefox Nightly is the only browser returning as Tablet.

**Comment by cpeterso** [comment] 2023-01-09 19:05
Thanks for reporting this bug. This is probably a regression from the code change in https://bugzilla.mozilla.org/show_bug.cgi?id=1798617. I'll move this bug report from GitHub to Bugzilla and assign it to an engineer.

**Comment by cpeterso** [comment] 2023-01-09 19:05
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809221

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2023-01-09 19:05 UTC
Labels: 🐞 bug, needs:triage

**Comment by cpeterso** [comment] 2023-01-09 23:33
@Akraz86 Firefox QA is not able to reproduce this bug on a Google Pixel 6. Are you using a non-default display resolution for your Pixel 6? Can you copy the text from your Firefox's `about:support` page and share it in this bug report?

**Comment by Akraz86** [comment] 2023-01-09 23:52
> @Akraz86 Firefox QA is not able to reproduce this bug on a Google Pixel 6. Are you using a non-default display resolution for your Pixel 6? Can you copy the text from your Firefox's `about:support` page and share it in this bug report

Hello

No my phone is pretty vanilla. 

Here is my about support paste


Troubleshooting Information
This page contains technical information that might be useful when you’re trying to solve a problem. If you are looking for answers to common questions about Nightly, check out our support website.
Application Basics
Name 	Firefox Nightly
Version 	110.0a1
Build ID 	20230107093442
Distribution ID 	
User Agent 	Mozilla/5.0 (Android 13; Tablet; rv:109.0) Gecko/110.0 Firefox/110.0
OS 	Linux 33 #1 SMP PREEMPT Tue Sep 20 02:33:52 UTC 2022
Application Binary 	/data/app/~~ck9vGxu-eMjftN3eNfITQw==/org.mozilla.fenix-D4p25hJKpSfVu7nEK4NLRg==/lib/arm64/dummy
Build Configuration 	about:buildconfig
Memory Use 	about:memory
Performance 	about:processes
Registered Service Workers 	about:serviceworkers
Multiprocess Windows 	0/0
Fission Windows 	0/0 Disabled by default
Remote Processes 	3
Google Location Service Key 	Found
Google Safebrowsing Key 	Found
Mozilla Location Service Key 	Found
Safe Mode 	false
Memory Size (RAM) 	7.4 GB
Disk Space Available 	49.7 GB
Crash Reports for the Last 3 Days
Report ID 	Submitted

All Crash Reports

This application has not been configured to display crash reports.
Nightly Features
Name 	Version 	ID
Remote Processes
Type 	Count
Web Content	2 / 2
GPU	1
Add-ons
Name 	Type 	Version 	Enabled 	ID
Bitwarden - Free Password Manager	extension	2022.12.1	true	{446900e4-71c2-419f-a6a7-df9c091e268b}
Dark Reader	extension	4.9.62	true	addon@darkreader.org
Google Search Fixer	extension	1.6	true	{58c32ac4-0d6c-4d6f-ae2c-96aaf8ffcb66}
Mozilla Android Components - Ads Telemetry	extension	110.0.20230107143316.0107143803	true	ads@mozac.org
Mozilla Android Components - Browser Icons	extension	110.0.20230107143316.0107144001	true	icons@mozac.org
Mozilla Android Components - Firefox Accounts WebChannel	extension	110.0.20230107143316.0107143758	true	fxa@mozac.org
Mozilla Android Components - ReaderView	extension	110.0.20230107143316.0107143713	true	readerview@mozac.org
Mozilla Android Components - Search Telemetry	extension	110.0.20230107143316.0107143803	true	cookies@mozac.org
Mozilla Android Components - Web Compatibility Interventions	extension	109.0.0	true	webcompat@mozilla.org
Mozilla Android Components - WebCompat Reporter	extension	2.0.1	true	webcompat-reporter@mozilla.org
uBlock Origin	extension	1.46.0	true	uBlock0@raymondhill.net
Graphics
Features
Window Device Pixel Ratios	2.2222222222222223,2.2222222222222223,2.2222222222222223,2.2222222222222223
Compositing	WebRender
Asynchronous Pan/Zoom	touch input enabled; autoscroll enabled; smooth pinch-zoom enabled
WebGL 1 Driver WSI Info	EGL_VENDOR: Android
EGL_VERSION: 1.4 Android META-EGL
EGL_EXTENSIONS: EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_ANDROID_get_native_client_buffer EGL_ANDROID_presentation_time EGL_EXT_surface_CTA861_3_metadata EGL_EXT_surface_SMPTE2086_metadata EGL_KHR_get_all_proc_addresses EGL_KHR_swap_buffers_with_damage EGL_EXT_gl_colorspace_scrgb EGL_EXT_gl_colorspace_scrgb_linear EGL_EXT_gl_colorspace_display_p3_linear EGL_EXT_gl_colorspace_display_p3 EGL_EXT_gl_colorspace_display_p3_passthrough EGL_EXT_gl_colorspace_bt2020_linear EGL_EXT_gl_colorspace_bt2020_pq EGL_ANDROID_image_native_buffer EGL_ANDROID_native_fence_sync EGL_ANDROID_recordable EGL_EXT_create_context_robustness EGL_EXT_image_gl_colorspace EGL_EXT_pixel_format_float EGL_EXT_protected_content EGL_EXT_yuv_surface EGL_IMG_context_priority EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_fence_sync EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_mutable_render_buffer EGL_KHR_no_config_context EGL_KHR_partial_update EGL_KHR_surfaceless_context EGL_KHR_wait_sync EGL_NV_context_priority_realtime 
IsWebglOutOfProcessEnabled: 1
WebGL 1 Driver Renderer	ARM -- Mali-G78
WebGL 1 Driver Version	OpenGL ES 3.2 v1.r36p0-01eac0.ecf5cbce9c793f75e7a31c960ecf9020
WebGL 1 Driver Extensions	GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_astc_decode_mode GL_EXT_texture_compression_astc_decode_mode_rgb9e5 GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_unpack_subimage GL_EXT_color_buffer_float GL_EXT_float_blend GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_EGL_image_array GL_EXT_texture_filter_anisotropic GL_OES_texture_float_linear GL_ARM_texture_unnormalized_coordinates GL_EXT_shader_framebuffer_fetch GL_EXT_clip_control 
WebGL 1 Extensions	ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_float_blend EXT_sRGB EXT_texture_filter_anisotropic MOZ_debug OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_lose_context
WebGL 2 Driver WSI Info	EGL_VENDOR: Android
EGL_VERSION: 1.4 Android META-EGL
EGL_EXTENSIONS: EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_ANDROID_get_native_client_buffer EGL_ANDROID_presentation_time EGL_EXT_surface_CTA861_3_metadata EGL_EXT_surface_SMPTE2086_metadata EGL_KHR_get_all_proc_addresses EGL_KHR_swap_buffers_with_damage EGL_EXT_gl_colorspace_scrgb EGL_EXT_gl_colorspace_scrgb_linear EGL_EXT_gl_colorspace_display_p3_linear EGL_EXT_gl_colorspace_display_p3 EGL_EXT_gl_colorspace_display_p3_passthrough EGL_EXT_gl_colorspace_bt2020_linear EGL_EXT_gl_colorspace_bt2020_pq EGL_ANDROID_image_native_buffer EGL_ANDROID_native_fence_sync EGL_ANDROID_recordable EGL_EXT_create_context_robustness EGL_EXT_image_gl_colorspace EGL_EXT_pixel_format_float EGL_EXT_protected_content EGL_EXT_yuv_surface EGL_IMG_context_priority EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_fence_sync EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_mutable_render_buffer EGL_KHR_no_config_context EGL_KHR_partial_update EGL_KHR_surfaceless_context EGL_KHR_wait_sync EGL_NV_context_priority_realtime 
IsWebglOutOfProcessEnabled: 1
WebGL 2 Driver Renderer	ARM -- Mali-G78
WebGL 2 Driver Version	OpenGL ES 3.2 v1.r36p0-01eac0.ecf5cbce9c793f75e7a31c960ecf9020
WebGL 2 Driver Extensions	GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_astc_decode_mode GL_EXT_texture_compression_astc_decode_mode_rgb9e5 GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_unpack_subimage GL_EXT_color_buffer_float GL_EXT_float_blend GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_EGL_image_array GL_EXT_texture_filter_anisotropic GL_OES_texture_float_linear GL_ARM_texture_unnormalized_coordinates GL_EXT_shader_framebuffer_fetch GL_EXT_clip_control 
WebGL 2 Extensions	EXT_color_buffer_float EXT_float_blend EXT_texture_filter_anisotropic MOZ_debug OES_draw_buffers_indexed OES_texture_float_linear OVR_multiview2 WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context
Target Frame Rate	90
GPU #1
Active	Yes
Description	Model: Pixel 6, Product: oriole, Manufacturer: Google, Hardware: oriole, OpenGL: ARM -- Mali-G78 -- OpenGL ES 3.2 v1.r36p0-01eac0.ecf5cbce9c793f75e7a31c960ecf9020
Vendor ID	ARM
Device ID	Mali-G78
Driver Version	OpenGL ES 3.2 v1.r36p0-01eac0.ecf5cbce9c793f75e7a31c960ecf9020
RAM	0
Diagnostics
AzureCanvasBackend	skia
AzureCanvasBackend (UI Process)	skia
AzureContentBackend	skia
AzureContentBackend (UI Process)	skia
AzureFallbackCanvasBackend (UI Process)	skia
CMSOutputProfile	Empty profile data
Display0	1080x2400@90Hz scales:2.225000|1.000000
DisplayCount	1
GPUProcessPid	974
GPUProcess	
Device Reset	
Decision Log
HW_COMPOSITING	
default	available		
user	force_enabled	Force-enabled by pref	
OPENGL_COMPOSITING	
default	available		
user	force_enabled	Force-enabled by pref	
GPU_PROCESS	
default	available		
WEBRENDER	
default	available		
WEBRENDER_COMPOSITOR	
default	disabled	Disabled by default	Blocklisted; failure code FEATURE_FAILURE_DISABLED
WEBRENDER_PARTIAL	
default	available		
WEBRENDER_SHADER_CACHE	
default	available		
WEBRENDER_OPTIMIZED_SHADERS	
default	available		
WEBRENDER_ANGLE	
default	available		
env	unavailable	OS not supported	Blocklisted; failure code FEATURE_FAILURE_OS_NOT_SUPPORTED
WEBRENDER_DCOMP_PRESENT	
default	available		
user	disabled	User disabled via pref	Blocklisted; failure code FEATURE_FAILURE_DCOMP_PREF_DISABLED
env	unavailable	Requires Windows 10 or later	Blocklisted; failure code FEATURE_FAILURE_DCOMP_NOT_WIN10
runtime	unavailable	Requires ANGLE	Blocklisted; failure code FEATURE_FAILURE_DCOMP_NOT_ANGLE
WEBGPU	
default	disabled	Disabled by default	Blocklisted; failure code FEATURE_FAILURE_DISABLED
VP8_HW_DECODE	
default	available		
VP9_HW_DECODE	
default	available		
BACKDROP_FILTER	
default	available		
CANVAS_RENDERER_THREAD	
default	blocked	Disabled by pref	Blocklisted; failure code FEATURE_FAILURE_DISABLED_BY_PREF
ACCELERATED_CANVAS2D	
default	disabled	Disabled by default	Blocklisted; failure code FEATURE_FAILURE_DISABLED
Media
Audio Backend	opensl
Max Channels	2
Preferred Sample Rate	48000
Roundtrip latency (standard deviation)	...
Output Devices
Name 	Group 	Vendor 	State 	Preferred 	Format 	Channels 	Rate 	Latency
Default audio output device			Enabled	All	default: S16LE, support: S16LE S16BE F32LE F32BE	2	default: 44100, support: 44100 - 44100	128 - 441
Input Devices
Name 	Group 	Vendor 	State 	Preferred 	Format 	Channels 	Rate 	Latency
Default audio input device			Enabled	All	default: S16LE, support: S16LE S16BE F32LE F32BE	1	default: 44100, support: 44100 - 44100	128 - 441
Media Capabilities

Environment Variables
Name 	Value
Important Modified Preferences
	Name 	Value browser.search.region	CA
extensions.formautofill.creditCards.used	2
extensions.lastAppVersion	110.0a1
gfx.blacklist.gpu.process.failureid	FEATURE_FAILURE_ANDROID_12
idle.lastDailyNotification	1673299528
media.gmp.storage.version.observed	1
network.dns.disablePrefetch	true
network.http.speculative-parallel-limit	0
network.predictor.enabled	false
network.prefetch-next	false
network.trr.blocklist_cleanup_done	true
privacy.purge_trackers.date_in_cookie_database	0
privacy.purge_trackers.last_purge	1673299531188
security.remote_settings.crlite_filters.checked	1653441359
security.remote_settings.intermediates.checked	1653441359
storage.vacuum.last.index	0
user.js Preferences

Your profile folder contains a user.js file, which includes preferences that were not created by Nightly.
Important Locked Preferences
	Name 	Value fission.autostart.session	false
Accessibility
Activated 	true
Prevent Accessibility 	0
Library Versions
	Expected minimum version	Version in use
NSPR	4.35	4.35
NSS	3.87	3.87
NSSSMIME	3.87	3.87
NSSSSL	3.87	3.87
NSSUTIL	3.87	3.87
Startup Cache
Disk Cache Path 	/data/user/0/org.mozilla.fenix/files/mozilla/hn53w9p5.default/startupCache/startupCache.8.little
Ignore Disk Cache 	false
Found Disk Cache on Init 	true
Wrote to Disk Cache 	true
Internationalization & Localization
Application Settings
Requested Locales 	["en-CA","en-US"]
Available Locales 	["an","ar","ast","az","be","bg","bn","br","bs","ca","cak","cs","cy","da","de","dsb","el","en-CA","en-GB","en-US","eo","es-AR","es-CL","es-ES","es-MX","et","eu","fa","ff","fi","fr","fy-NL","ga-IE","gd","gl","gn","gu-IN","he","hi-IN","hr","hsb","hu","hy-AM","id","is","it","ja","ka","kab","kk","kn","ko","lij","lo","lt","lv","ml","mr","ms","my","nb-NO","ne-NP","nl","nn-NO","oc","pa-IN","pl","pt-BR","pt-PT","rm","ro","ru","sk","sl","son","sq","sr","sv-SE","ta","te","th","tr","trs","uk","ur","uz","vi","wo","xh","zam","zh-CN","zh-TW"]
App Locales 	["en-CA","en-US","en-GB"]
Regional Preferences 	["en-CA","en-US"]
Default Locale 	"en-US"
Operating System
System Locales 	["en-CA","en-US"]
Regional Preferences 	["en-CA","en-US"]
Remote Debugging (Chromium Protocol)
Accepting Connections 	false
URL

**Comment by rvandermeulen** [comment] 2023-01-12 03:30
@Akraz86 We believe we have a fix which should be available starting in the 2023-01-12 Nightly builds. If you have a minute, can you please verify that things work as expected after you get that update from the Play Store? Thanks!

**Comment by Akraz86** [comment] 2023-01-12 03:57
> @Akraz86 We believe we have a fix which should be available starting in the 2023-01-12 Nightly builds. If you have a minute, can you please verify that things work as expected after you get that update from the Play Store? Thanks!

Hello. I assume this will be tomorrow's update? I just got an update now but it's still the 11th technically. I am EST-5. 

Regardless, today's update did not fix the issue. I will wait for tomorrow's and report back :) thank you so much

**Comment by rvandermeulen** [comment] 2023-01-12 03:59
Correct, the build hasn't started yet :)

**Comment by Akraz86** [comment] 2023-01-12 04:01
> Correct, the build hasn't started yet 😄. You can confirm via the About screen that you've got a build from the 12th.

Excellent! I look forward to tomorrow :D

**Comment by rvandermeulen** [comment] 2023-01-12 14:00
The update should be live now.

**Comment by Akraz86** [comment] 2023-01-12 14:10
> Correct, the build hasn't started yet 😄. You can confirm via the About screen that you've got a build from the 12th.

Excellent! I look forward to tomorrow :D

> The update should be live now.

It works! This is amazing thank you so much. 

I'm humbled you and your team took this ticket seriously and fixed it. I really appreciate it.

**Comment by rvandermeulen** [comment] 2023-01-12 14:11
Thanks for the confirmation!
