### ISSUE TITLE
[Bug]: Unable to download images from i.ylilauta.org

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/fenix#23800] opened 2022-02-17 15:52 UTC
### Steps to reproduce

1. Navigate to https://i.ylilauta.org/96/45/96453830cad9b5a7.jpg
2. Long press the image.
3. Select "Save image" from "Context" menu.
4. Observe behavior.

### Expected behaviour

Image is downloaded and available on the device.

### Actual behaviour

Download fails.

### Device name

Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)

### Android version

Android 9, Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 99.0a1 (🦎 99.0a1-20220216094238)

### Additional information

1. The issue is not reproducible on Chrome.
2. The issue is reproducible on Firefox Release.
3. This was reported here: https://github.com/webcompat/web-bugs/issues/99751
4. This might be dependent on https://bugzilla.mozilla.org/show_bug.cgi?id=1690037 
5. Screenshot attached.

![image](https://user-images.githubusercontent.com/12184325/154518826-4c778752-15d7-46fd-8079-cbdf2805c4a9.png)

**Comment by Sopsy** [comment] 2022-02-17 16:03
I would like to add that this is a regression.
Works on Firefox 96 and older, the issue first appearead on Firefox 97.

**Comment by kbrosnan** [comment] 2022-02-17 18:45
Sounds like a duplicate of https://github.com/mozilla-mobile/fenix/issues/23798

**Closed by kbrosnan** 2022-02-17 18:45 UTC
Labels: 🐞 bug, needs:triage
