### ISSUE TITLE
[Bug] Two Firefox tasks in recent app switcher (permanently on Android 11 Beta; briefly on cold startup in Android 10)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#13270] opened 2020-08-04 18:38 UTC
Originally reported by our community in https://github.com/mozilla-mobile/fenix/issues/12577#issuecomment-667085187

## Steps to reproduce
- Cold start Firefox and very quickly...
- Hit the recent app switcher button

### Expected behavior
One Firefox task is present in the recent app switcher

### Actual behavior
Two Firefox tasks are present in the recent app switcher. The second task (it's inactive) will quickly dismiss itself.

![image](https://user-images.githubusercontent.com/68282543/87494267-2e133600-c66c-11ea-8fa2-5541324da577.jpg)

Our community uploaded recordings of the issue:
- https://github.com/mozilla-mobile/fenix/files/5006834/Screen.Record.2.apps.zip
- https://github.com/mozilla-mobile/fenix/files/5006840/App.isn.t.available.error.zip
  - In this case, a toast says, "App is not available". I suspect it's because the recent app switcher button was hit twice – i.e. we were trying to switch to the second Firefox task that is now dismissed

### Device information
* Android device: P2
* Fenix version: migration RC1 or 2 (can't remember); I'm unable to reproduce on Nightly 200804

---

I would want someone with more task experience to chime in but it _seems_ harmless so I'd be tempted to set a low priority. @pocmo Do you agree that this is harmless?

Given I can't reproduce on the Nightly but can reproduce on the migration build, I suspect this may be related to the migration code. I noticed a discrepancy in taskAffinity: all the fenix activities have `taskAffinity=""` except for the activities/alias in `.../migration/AndroidManifest.xml` which have `taskAffinity="${applicationId}.BROWSER"` ([search](https://searchfox.org/mozilla-mobile/search?q=taskaffinity&path=)) so perhaps that's related.

**Comment by pocmo** [comment] 2020-08-05 12:07
I agree that this should be harmless.

The task affinity may be the cause here. Looking at the commits I noticed that I introduced this here: https://github.com/mozilla-mobile/fenix/commit/f1a3dffba27df72b34836a2fb7b0c4a668586faa - This was a workaround to launch into the Fennec task that still could be around during the migration (It's weird). Maybe at some point after the migration we can just get rid of that again.

**Comment by jawz101** [comment] 2020-08-15 13:39
This isn't brief for me.  The second instance won't go away in its own

**Comment by mcomella** [comment] 2020-08-17 15:29
> This isn't brief for me. The second instance won't go away in its own.

Thanks for letting us know, @jawz101 A few questions so we can try to reproduce that issue:
- Are you using different steps to reproduce the issue than the ones mentioned above?
- Did you install Firefox from the Google Play store?
- Which release channel of Firefox are you using? e.g. Release, Beta, Nightly, etc.
- Do you have anything else different about your system that might cause your behavior to be different from mine? I'm running stock Android on a Pixel 2. e.g.
  - Are you running stock Android?
  - Do you have any developer options enabled?

> It really looks clunky if this not going to change.

If two are sticking around forever and a non-trivial number of users will see it, I agree it's clunky and we should change it. We want to understand in what cases it can stick around forever so we can understand the number of users impacted by it.

**Comment by jawz101** [comment] 2020-08-17 17:19
Pixel 3a, android 11 dev prev RPB3.200720.005, installed Firefox Android beta 80.0.0-beta.6.

Stock Android, Android developer options not enabled.  Though I did accidentally enable the Firefox for Android beta developer menu (pressed the logo 5 times).

using Nova Launcher

**Comment by mcomella** [comment] 2020-08-18 00:09
Suspected action items to try to reproduce permanent 2 tasks:
- Try on Android 11
- Try with Nova launcher

> Though I did accidentally enable the Firefox for Android beta developer menu (pressed the logo 5 times). I don't know how to turn that back off.

I don't believe it can be turned off but afaik there are no settings that should affect this issue.

**Comment by jawz101** [comment] 2020-08-25 22:49
I just got a Pixel 4a and was on Android 10 for a few days with no issue.  Upgraded to 11 beta and the 2 Firefox instances show in the recents

**Comment by mcomella** [comment] 2020-08-25 23:15
That's great info, thank you!

**Comment by jawz101** [comment] 2020-08-28 04:46
Nightly does not seem to have the issue

**Comment by RespectIsEverything** [comment] 2020-08-28 14:50
Pixel 3a, Nova Launcher, Android 11 Beta 3, Release channel

Same issue.

One instance is correct.
Second instance is just a blank screen; like a Private Tab.

Could it be a background process that was given visibility?

**Comment by RespectIsEverything** [comment] 2020-08-28 20:44
It makes one wonder.
How many issues go undetected due to improper nomenclature?

This bug was absent from Google's indexing.
Had been searching for "instances". 
Reverted thought process to layman's terms... Android "task switcher".
Adjusted criteria from "instances" to "tasks".
Bug found.

**Comment by jawz101** [comment] 2020-09-01 01:11
![Screenshot_20200831-201045](https://user-images.githubusercontent.com/14151703/91783541-0f530980-ebf0-11ea-8667-6f3055292414.png)

**Comment by RespectIsEverything** [comment] 2020-09-04 14:04
Still present in 80.1.2

**Comment by pocmo** [comment] 2020-09-08 16:12
For those that are affected (unfortunately I am not able to reproduce this in an Android 11 emulator): What happens if you switch between the two instances?

**Comment by RespectIsEverything** [comment] 2020-09-08 17:06
Both instances are indeed separate.
They can be reordered apart from one another in recent apps switcher.

When pressing blank instance it positions both instances together again.
When pressing icon on home screen/app drawer, it positions both instances together again

Behavior present on Pixel Launcher/Nova Launcher.
Same recent apps switcher is utilized by both launchers.
Is recent app switcher now a system process?

Screen Recording attached:
[https://1drv.ms/u/s!AkZMMNsar4-lmdR0NBdbCRoG_TM8vA?e=42Uz2h](url)

**Comment by pocmo** [comment] 2020-09-08 17:17
Thank you! This is helpful.

I am pretty sure this is caused by us launching into the Fennec task to avoid a stale Fennec task hanging during the migration.

If you have time helping to confirm this then you could try:

1. Try to reproduce this issue with Nightly. If my assumption is correct then this should not happen with Nightly. https://play.google.com/store/apps/details?id=org.mozilla.fenix

2. Do you see a different behavior depending on whether the app was launched from the home screen or from a link in a third-party app? (with killing the app before trying).

**Comment by RespectIsEverything** [comment] 2020-09-08 21:47
1. Bug is absent. Behavior is as expected in nightly channel.
2. Bug is absent. Behavior is as expected when launching from 3rd party app.

Android 11 exited Beta today. Bug is still present.
And not to sound unappreciative or pretentious, but I expect "stable" channel releases to be just that.
I stay away from Nightly/Beta releases on my productivity devices to avoid problems like this :/

**Comment by pocmo** [comment] 2020-09-09 14:35
Got the Android 11 update and can now see it on one my devices. Will take this issue for the next sprint.

**Comment by jawz101** [comment] 2020-09-20 22:55
This is god-damned annoying

**Comment by jacres** [comment] 2020-09-21 14:57
Seeing the same behaviour here. Pixel 2, Android 11, Firefox 80.1.3

**Comment by baszczewski** [comment] 2020-09-23 08:46
I can confirm this issue.
Firefox 81.1.1, Android 11, Google Pixel 3a, default launcher. 
One of Firefox instances in task manager is blank even after fresh browser start.

**Comment by pocmo** [comment] 2020-09-23 17:11
Patch landed in `master` / Nightly. But Nightly is not affected. Looking at uplifting to the 82 release branch to get it into Beta asap.

**Comment by jawz101** [comment] 2020-09-25 15:31
since it didn't make it into beta...

**Comment by payton-quinn** [comment] 2020-09-25 18:42
+1 

Also happening on my Pixel 3XL running Firefox stable on Android 11

**Comment by cadeyrn** [comment] 2020-09-25 20:30
> Also happening on my Pixel 3XL running Firefox stable on Android 11

That's expected since the bugfix landed in the Nightly branch two days ago. It will take a few weeks until it reaches the stable channel.

**Comment by UglyCasan0va** [comment] 2020-09-27 17:03
Happens to me on Android 11 with Nova Launcher

**Comment by cadeyrn** [comment] 2020-09-27 21:40
@UglyCasan0va:

> Patch landed in master / Nightly. But Nightly itself is not affected. 

or…

> the bugfix landed in the Nightly branch two days ago. It will take a few weeks until it reaches the stable channel.

**Comment by pocmo** [comment] 2020-09-28 12:05
> since it didn't make it into 82beta...

I was too late for the first Beta. But it should make its way into the second 82 Beta.

**Comment by JChops** [comment] 2020-10-02 03:14
Android 11 on Pixel 4 installing beta fixed this for me

**Comment by pocmo** [comment] 2020-10-02 16:18
@JChops Awesome, thank you for verifying.

**Closed by pocmo** 2020-10-02 16:18 UTC
Labels: Android:11, Feature:AndroidIntegration, 🐞 bug

**Comment by nightwishhh** [comment] 2020-10-23 10:54
Same bug on Pixel 5, Android 11, Firefox 81.1.5.
No bug on Firefox Nightly

**Comment by cadeyrn** [comment] 2020-10-23 11:03
> Same bug on Pixel 5, Android 11, Firefox 81.1.5.

That's expected. It was fixed in Firefox 82.
