### ISSUE TITLE
Dark theme widget

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#8701] opened 2020-02-24 20:30 UTC
### Why/User Benefit/User Problem

Further to https://support.mozilla.org/en-US/questions/1280616, user would like to be able to dark theme the widget background to match phone theme.

**Comment by cadeyrn** [comment] 2020-02-24 20:34
Duplicate of #4840.

**Closed** 2020-02-25 00:04 UTC
Labels: needs:triage, 🌟 feature request
