### ISSUE TITLE
Add support for keyboard shortcuts like Ctrl-R and Ctrl-L

### ISSUE THREAD

**Issue by lilydjwg** [mozilla-mobile/fenix#17723] opened 2021-02-01 04:09 UTC
### What is the user problem or growth opportunity you want to see solved?

With Fenix keyboard shortcuts like Ctrl-R (reload) and Ctrl-L (focus urlbar) no longer work.

### How do you know that this problem exists today? Why is this important?

Fenix doesn't response to these keys.

These shortcut keys are usable with a physical keyboard, either directly attached to the device (via USB or bluetooth) or with a tool like [scrcpy](https://github.com/Genymobile/scrcpy).

### Who will benefit from it?

* people attaching a keyboard for typing on the phone
* people using a scrcpy-like tool to ease their experience working on both computer and phone.

**Comment by Mugurell** [comment] 2021-02-01 07:08
I don't think this is a recent regression as in "shortcuts no longer work".
Should could repurpose this ticket to a feature request to then consider adding support for external keyboards?

**Comment by lilydjwg** [comment] 2021-02-01 07:20
Yes, this is a feature request for fenix. The old Firefox before fenix had support for this.

**Comment by evilpie** [comment] 2021-02-01 10:57
Duplicate of #3729

**Comment by lilydjwg** [comment] 2021-02-01 11:14
@evilpie that issue seems to be a little different: it asks for a vim-like keyboard access, with a new set of shortcuts that may conflict with existing web pages. Here I'm asking for shortcuts that the desktop Firefox already has, and are intended to be used like desktop apps.

**Comment by evilpie** [comment] 2021-02-01 11:47
No the issue is for both. See also all the other duplicates of it.

**Comment by Mugurell** [comment] 2021-02-01 15:40
It's good that these tickets are linked now and this request can be tracked in the one already existing.
Let's keep discussion around this focused in one ticket.
Closing this as it's the newer one.

**Closed by Mugurell** 2021-02-01 15:40 UTC
Labels: Feature:IME, feature request 🌟
