### ISSUE TITLE
[Bug]: Firefox crashes on startup.

### ISSUE THREAD

**Issue by kenzoEnomoto** [mozilla-mobile/fenix#28356] opened 2022-12-31 10:42 UTC
### Steps to reproduce

1. Start Firefox.

### Expected behaviour

Firefox starts.

### Actual behaviour

Firefox doesn't start.

### Device name

ASUS_X013D

### Android version

Android 5.1.1

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1

### Device logs

F/libc (11775): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 11819 (GleanAPIPool)
I/DEBUG (20630): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG (20630): Build fingerprint: 'asus/JP_Phone/ASUS_X013D_1:5.1.1/LMY47V/13.0209.1705.116-20170621:user/release-keys'
I/DEBUG (20630): Revision: '0'
I/DEBUG (20630): ABI: 'arm'
I/DEBUG (20630): pid: 11775, tid: 11819, name: GleanAPIPool >>> org.mozilla.fenix <<<
I/DEBUG (20630): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
I/DEBUG (20630): r0 00000000 r1 0000001a r2 80000000 r3 a0478865
I/DEBUG (20630): r4 9e3c5955 r5 99f03120 r6 a0516f0c r7 99efe360
I/DEBUG (20630): r8 99efe378 r9 99efe374 sl 99f03120 fp a02ebda4
I/DEBUG (20630): ip 20000000 sp 99efe348 lr a0496a49 pc a0496a6e cpsr 200b0030
I/DEBUG (20630):
I/DEBUG (20630): backtrace:
I/DEBUG (20630): #00 pc 0001fa6e /data/app/org.mozilla.fenix-2/lib/arm/libmozglue.so
I/DEBUG (20630): https://github.com/mozilla-mobile/fenix/issues/1 pc 0001fa45 /data/app/org.mozilla.fenix-2/lib/arm/libmozglue.so

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22212)

**Comment by cadeyrn** [comment] 2022-12-31 13:50
Duplicate of [BZ-1807716](https://bugzilla.mozilla.org/show_bug.cgi?id=1807716), I guess. Should be fixed by #28350. Please test the next Nightly build if it still crashes for you.

**Comment by csadilek** [comment] 2023-01-02 16:09
Yes, Closing as dupe of [BZ-1807716](https://bugzilla.mozilla.org/show_bug.cgi?id=1807716), please update to latest Nightly and let us know if the problem still persists.

**Closed by csadilek** 2023-01-02 16:09 UTC
Labels: 🐞 bug, needs:triage

**Comment by kenzoEnomoto** [comment] 2023-01-02 23:37
I updated to latest Nightly but the problem still persists.

**Comment by csadilek** [comment] 2023-01-03 00:09
@kenzoEnomoto Can you share the version information from Settings->Firefox Nightly here, please?

**Comment by kenzoEnomoto** [comment] 2023-01-03 02:25
@csadilek 
Firefox Nightly cannot be started, so it is not possible to check the version in that way.
The latest update was made about an hour ago on Google Play Store.

**Comment by csadilek** [comment] 2023-01-03 03:11
@kenzoEnomoto OK, I was thinking the problem is intermittent, but, of course, if it crashes every time that won't work :(. Sorry, and thanks for confirming. We will continue investigating.
