### ISSUE TITLE
[Bug] Shorcuts and QR scanner bar doesn't appear sometimes

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3690] opened 2019-06-26 20:37 UTC
### Demo
![demo 2019-06-26 13_36_46](https://user-images.githubusercontent.com/4400286/60213025-766c7580-9817-11e9-98f4-7c9eddfbbcb9.gif)

**Comment by ekager** [comment] 2019-06-26 22:38
I think this is also caused by the constraintlayout bug #3668 ... :(

**Comment by abodea** [comment] 2019-06-27 12:38
Verified as fixed on the latest build **`6/27`** with **`Samsung Galaxy S7(Android 7), Huawei Mate 20 Lite(Android 8.1.0), Google Pixel 3 XL (Android 9), Google Pixel XL(Android Q Beta 4).`**

**Closed by abodea** 2019-06-27 12:38 UTC
Labels: Feature:Search, QA needed, 🐞 bug

**Comment by sv-ohorvath** [comment] 2019-07-05 09:00
Also verified on the RC 1.0.1. Nexus 9 (Andriod 7.1.1), Pixel 3 (Android 9)
