### ISSUE TITLE
FNX-12382 ⁃ [Bug] Passwords are visible when reopening Fenix

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#11447] opened 2020-06-10 21:21 UTC
### Actual behavior
If the user goes to the home screen or locks the phone from Settings > Logins and passwords > Saved logins, the browser automatically goes back to the Logins and passwords page which doesn't contain any private data. From there, the user needs to verify their identity again to view the saved logins.
However, if the user views a page with specific login data including the password, the browser doesn't go back to the Logins and passwords page. If somebody reopens the browser later, it's still possible to display all passwords without verifying the identity.

### Expected behavior
The browser should behave in the same way in the whole Saved logins section. The saved logins should hide when going to the home screen/locking the phone the same way they already do in the case described above.
This is a regression from version 5.0.0. Before, the behaviour was equal in both cases.

### Steps to reproduce
1. Go to Settings > Logins and passwords > Saved logins > specific saved login
  * minimize and reopen Firefox
1. Go to Settings > Logins and passwords > Saved logins
  * minimize and reopen Firefox

### Device information
* Android device: Samsung Galaxy S9+ (SM-G9650/DS)
* Android version: 8.0.0
* Fenix version: 5.1.1

**Comment by sheikh-azharuddin** [comment] 2020-06-11 03:00
This is already resolved. Please update to latest build and check once.
When firefox screen is minimized on any credentials screen it is going back to the page logins and passwords, and to view password again you to have authenticate again...works as per your expectations

**Comment by theFireProjet** [comment] 2020-06-11 15:04
> 
> 
> This is already resolved. Please update to latest build and check once.
> When firefox screen is minimized on any credentials screen it is going back to the page logins and passwords, and to view password again you to have authenticate again...works as per your expectations

You're right, sounds exactly like what I was talking about. I've tested again in the latest Firefox Nightly version: Nightly 200611 60:01 on my phone Samsung Galaxy S9+ (SM-G9650/DS), Android 8.0.0
From what I can tell, you're right, **this** problem is solved but we are back to the behaviour from Firefox Preview 5.0.0 where neither the saved logins list nor the passwords are censored in the recent apps overview:
<img src="https://user-images.githubusercontent.com/61639215/84402974-71a9f880-ac05-11ea-8ada-3f8043ac5a32.jpg" alt="Screenshot_20200611-170008_Firefox Nightly" width="360">
<img src="https://user-images.githubusercontent.com/61639215/84402983-7373bc00-ac05-11ea-8e37-f0dc4449a3e8.jpg" alt="Screenshot_20200611-170001_Firefox Nightly" width="360">

**Comment by mcarare** [comment] 2020-06-22 08:41
Thank you for the detailed report! Closing as duplicate of https://github.com/mozilla-mobile/fenix/issues/10727

**Closed** 2020-08-11 04:02 UTC
Labels: needs:triage, 🐞 bug
