### ISSUE TITLE
[Bug] Text selection context menu shows up too high on Nightly

### ISSUE THREAD

**Issue by serovar** [mozilla-mobile/fenix#6877] opened 2019-11-30 12:06 UTC
## Steps to reproduce
Select some text.
### Expected behavior
The text selection context menu should show up right above the selected text.
### Actual behavior
The text selection context menu shows up way above the selected text.
### Device information

* Android device: Pixel 2 XL, Stock Android 10 (November patch)
* Fenix version: Nightly 191130 06:00 (Build #13340607)
![Screenshot_20191130-125520](https://user-images.githubusercontent.com/6732420/69900333-ab9e6600-1369-11ea-8ebd-f45afa750ffa.png)

**Comment by ekager** [comment] 2019-12-02 16:08
Opened Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1600652

**Comment by sv-sdeiac** [comment] 2020-01-06 13:58
Hello, I can confirm that this issue is no longer reproducible using the latest version of Firefox Preview Nightly 1/6 #200106. 

#### Devices:
- Nexus 5 (Android 6.0.1);
- Nokia 6 (Android 7.1.1);
- Google Pixel (Android 9).

Due to my findings, I'll close the issue, thanks.

**Closed by sv-sdeiac** 2020-01-06 13:58 UTC
Labels: P3, needs:gv, 🐞 bug
