### ISSUE TITLE
[Bug] App Actions in private custom tabs can look funky

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#7511] opened 2020-01-06 23:40 UTC
## Steps to reproduce
1. Make Fenix your default browser
2. Enable opening links in private mode by default
3. open a custom tab from twitter

### Expected behavior
Contrast is good

### Actual behavior
<img width="752" alt="image" src="https://user-images.githubusercontent.com/1250545/71857001-bc45a880-309a-11ea-8d38-c8e35505b68e.png">

### Device information

* Android device: ?
* Fenix version: ?

**Comment by Baron-Severin** [comment] 2020-01-07 17:38
Important note: websites pass us their own toolbar color + assets, and we normally assume that they are ensuring they provide decent contrast.  Since we change the toolbar color in private mode, I don't see how it would be possible to modify assets in a way that will consistently ensure contrast while staying in sync with site branding.

**Comment by NotWoods** [comment] 2020-01-11 06:18
We could override the tint to be the same as the other buttons, and single color items like "tweet" would be fine. However, it would make any full-color toolbar items extra white.

**Comment by NotWoods** [comment] 2020-01-11 06:19
Assigning myself to fix a tinting bug so this is possible with AC.

**Comment by boek** [comment] 2020-02-04 22:25
@AmyYLee @lime124 asks what do you suggest here? We also get another color from the originating application (e.g. Twitter) that they expect this asset to sit on top of. But when we override that with the private browsing mode we can get odd combinations like this

**Comment by brampitoyo** [comment] 2020-02-05 03:08
@Baron-Severin I wonder if we need to stay in sync with the site branding on Private Custom Tabs, when our Private Browsing Mode is designed not to be neutral, but instead to put its unique identity forward?

My initial recommendation would be as @NotWoods suggested: override the tint so text and icons always appear white.

@NotWoods, can you explain why items would look extra white?

Otherwise, @AmyYLee is working on colour and will be able to advise here.

**Comment by NotWoods** [comment] 2020-02-05 05:24
Hypothetically, an app could request for a toolbar icon that's full color:
![private_custom](https://user-images.githubusercontent.com/1782266/73813333-8298b800-4794-11ea-85d2-d89835192c42.png)
The private tint might look something like this:
![private_custom_tint](https://user-images.githubusercontent.com/1782266/73813332-82002180-4794-11ea-90d1-f175b5d550f5.png)

However, we also don't know of any apps that do this. It might be fine to proceed for now and see if any bug reports come in.

**Comment by brampitoyo** [comment] 2020-02-06 03:50
@NotWoods I know that the example you’ve posted only makes up one case among many, but based on that, I’d like to walk back on my previous decision.

Up to this point, I always thought that an app is only permitted to display a monochromatic icon on that toolbar. If that’s the case, then tinting white will make the appearance consistent.

The other icon type that I’m aware of is the product icon, which can be full colour.

But it turned out that an app can also request to show a full colour icon which is not a product icon? This is a totally new piece of information. If that’s the case, then the icon will be designed to stand out against almost any background, and it seems that we should honour their choice?

As you wrote, I haven’t come across any app that does this. Let’s just proceed for now and see whether it results in any bug. We hope not!

**Comment by NotWoods** [comment] 2020-02-06 04:39
Sounds good! I've updated Android Components so that we can override the tint here.

**Comment by AmyYLee** [comment] 2020-02-06 08:54
> @NotWoods I know that the example you’ve posted only makes up one case among many, but based on that, I’d like to walk back on my previous decision.
> 
> Up to this point, I always thought that an app is only permitted to display a monochromatic icon on that toolbar. If that’s the case, then tinting white will make the appearance consistent.
> 
> The other icon type that I’m aware of is the product icon, which can be full colour.
> 
> But it turned out that an app can also request to show a full colour icon which is not a product icon? This is a totally new piece of information. If that’s the case, then the icon will be designed to stand out against almost any background, and it seems that we should honour their choice?
> 
> As you wrote, I haven’t come across any app that does this. Let’s just proceed for now with tinting all single colour item white, and see whether it results in any bug. We hope not!

@brampitoyo Thanks for replying, I agree with tinting white and see how it goes.

**Comment by darkwing** [comment] 2020-02-11 20:35
@NotWoods Does your AC PR fix this issue or is further work needed?

**Comment by NotWoods** [comment] 2020-02-11 22:36
No further work is needed as I updated Fenix as well.

**Comment by liuche** [comment] 2020-04-01 17:41
Looks like this PR got merged a while ago, so I'm going to put the QA label on it.

**Comment by sflorean** [comment] 2020-04-07 14:18
Tested on Nightly build 04/07 with Samsung Galaxy Note 10 (Android 10 ) and Nokia 6 (Android 7.1.1) and the issue is fixed.
Screenshot:

![Screenshot_20200407-165002_Firefox Nightly](https://user-images.githubusercontent.com/58466444/78679744-49dfa100-78f3-11ea-96d3-4e1e81bc001c.jpg)

@NotWoods I think the option "tweet" is too close to the URL link, should I open a new issue or you already considered this?

**Closed by sflorean** 2020-04-07 14:18 UTC
Labels: Feature:CustomTabs, Feature:PrivateMode, P2, S3, eng:qa:needed, eng:ready, 🐞 bug

**Comment by NotWoods** [comment] 2020-04-07 15:43
Feel free to open a new issue
