### ISSUE TITLE
FNX-5044 ⁃ Add a notification for background play

### ISSUE THREAD

**Issue by akarshanbiswas** [mozilla-mobile/fenix#1458] opened 2019-04-08 05:42 UTC
### Why/User Benefit/User Problem
Users will be able to control playback while firefox/fenix is minimized just like in fennec

### What / Requirements
A persistent notification when fenix plays a media

### Acceptance Criteria (how do I know when I’m done?)
When fenix behaves same as fennec when playing media.

**Comment by kbrosnan** [comment] 2019-04-27 05:14
dupe of #1112

**Closed** 2020-08-11 11:42 UTC
Labels: Feature:Media
