### ISSUE TITLE
FNX-4922 ⁃  [Bug] Open a link from whatsapp not works

### ISSUE THREAD

**Issue by pasqualedante** [mozilla-mobile/fenix#1279] opened 2019-03-30 19:15 UTC
## Steps to reproduce
Receive a whatsapp message that contains a link

### Expected behavior
If I have set Fenix as default browser, clicking on the link, Fenix is opened to the linked page.

### Actual behavior
I have set Fenix as default browser, clicking on the link, Fenix is opened with the last opened session

### Device information
Pocophone F1 (android 9)
Today build 3/30 12:24 PM

**Comment by vesta0** [comment] 2019-04-01 00:39
I can't reproduce this on pixel 3. @sv-ohorvath please verify.

**Comment by sv-ohorvath** [comment] 2019-04-01 08:46
I am able to reproduce this, and it's not related only to WhatsApp. You can also pen links from other apps. STR:
1. Make Fenix the default browser.
2. Open Fenix, open a few tabs.
3. Kill Fenix from task manager.
4. Open a link from another app.

Results: The link will open in a background tab, while the app is loading the previously opened tab.
Also, the app is flashing a few times while it's loading.

*not reproducible with the app running in the background, or if there are no tabs opened before.

**Comment by kbrosnan** [comment] 2019-04-19 19:38
This is not custom tabs this is basic functionality that needs to work before we ship. We must reliably accept links from other apps. Clearing priority for re-triage.

**Comment by colintheshots** [comment] 2019-04-25 18:49
@bifleming @vesta0 Adding this bug as P1 to the first beta. This is definitely a release blocker. Emily and I will pair program this one and plan to fix it today.

**Comment by colintheshots** [comment] 2019-04-25 21:16
I have a proposed one-liner fix, but I'm asking Sawyer to see how it fits into his changes to sessionId in the BrowserFragment. Stay tuned. We may have this fixed today.

**Comment by vesta0** [comment] 2019-04-25 22:16
Thank you @colintheshots

**Comment by sv-ohorvath** [comment] 2019-04-30 12:26
@colintheshots I can still reproduce this with the same steps on the 4/29 build.

**Comment by sv-ohorvath** [comment] 2019-05-03 09:09
Is this the same as #2181?

**Comment by sv-ohorvath** [comment] 2019-05-06 08:05
Ok, verified this is finally fixed on the 5/6 build.
New issue: #2290

**Closed** 2020-08-11 07:27 UTC
Labels: Feature:AndroidIntegration, P1, needs:ac, 🐞 bug
