### ISSUE TITLE
[Bug] Long Pressing Back button while using external app's in-app browser mode shows history for last active firefox tab.

### ISSUE THREAD

**Issue by kennethtran93** [mozilla-mobile/fenix#15488] opened 2020-09-28 03:58 UTC
## Steps to reproduce
1. In Android Settings, ensure Firefox is set to default.
2. Open Firefox Browser App.
   a. Create or load up a tab with some history.
3. Press Home and switch/open the Twitter App.  Don't close/remove from recent history the Firefox Browser App.
4. In Twitter app:
   a. ensure setting for 'Use in-app browser' is enabled.
   b. Find a tweet with a link and tap on the link to open in the in-app browser.
   c. Within that in-app browser, hold the back button.
   d. See history for the tab loaded up in step 2.

### Expected behavior
I shouldn't see any tab history from the actual Firefox browser when using in-app browser of external app.

### Actual behavior
Can see the tab history of the active tab in Firefox from the in-app browser
![2020-09-27 20 37 43](https://user-images.githubusercontent.com/6724477/94389138-e301ae80-0103-11eb-9d5c-0fd8f4af2f04.png)

### Device information

* Android device: Samsung Galaxy S10 - Android 10
* Fenix version: 81.1.1

**Comment by s-ankur** [comment] 2020-09-28 14:42
Duplicate of https://github.com/mozilla-mobile/fenix/issues/13934. Thanks!

**Comment by ekager** [comment] 2020-09-28 17:08
Closing for #13934

**Closed by ekager** 2020-09-28 17:08 UTC
Labels: needs:triage, 🐞 bug
