### ISSUE TITLE
add a user option to switch between static and auto hiding urlbar

### ISSUE THREAD

**Issue by DetlevCM** [mozilla-mobile/fenix#12299] opened 2020-07-05 19:06 UTC
### What is the user problem or growth opportunity you want to see solved?
A toggle button to select between a static or self hiding address bar. (As used to be available.)

### How do you know that this problem exists today? Why is this important?
The auto-hiding urlbar leads to worse usability. For 1.5 lines extra text I end up clicking random links or minimizing firefox because I tap where the tab selection would be. For peopple using tabs, this is a huge nuissance.
I originally posted this (a little bit ranty) on the forum:
https://support.mozilla.org/en-US/questions/1293323

Having to remeber to scroll up every time to retrieve the urlbar is just annoying - especially if one wishes to switch between tabs regularly.
In addition, this used to be a "user choice feature" . (I always retained the static urlbar.)

### Who will benefit from it?
Anybody who regularly uses tabs or types urls in the urlbar.

**Comment by sheikh-azharuddin** [comment] 2020-07-05 19:17
I guess you can disable it through preference(about:config) settings.. Search for dynamictoolbar

**Comment by cadeyrn** [comment] 2020-07-05 19:18
Duplicate of #10240.

**Comment by DetlevCM** [comment] 2020-07-05 19:19
I tried looking for it using "urlbar" or "hide" - this would be a better workaround. Not necessarily a longterm solution, but a shortterm workaround. Thanks.

**Comment by DetlevCM** [comment] 2020-07-05 20:22
Looking around some more, looks like about:config does not control this aspect (and does not respond on my phone).

This was also referenced here:
https://github.com/mozilla-mobile/fenix/issues/8801
https://github.com/mozilla-mobile/fenix/issues/11567

**Comment by kbrosnan** [comment] 2020-07-05 21:53
@sheikh-azharuddin do not suggest `about:config` as a way to make changes to the UI. Prefs that affect UI bits like the dynamic toolbar are not going to work in Fenix. The only prefs that are expected to work are ones that interact with core functions of Gecko such as disabling javascript.

**Closed** 2020-08-28 21:02 UTC
Labels: needs:triage
