### ISSUE TITLE
FNX-5563 ⁃ [Bug] I can see half of the share/bookmark bar

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#2279] opened 2019-05-04 02:27 UTC
## Steps to reproduce
Open a new tab.

### Expected behavior
The share/bookmark bar should be collapsed.
![Screenshot](https://user-images.githubusercontent.com/922368/57172788-79f20a80-6e2d-11e9-8d36-217b69cdf623.png)UNITO-UNDERSCORE!20190504-052624!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Preview!

### Actual behavior
The bottom bar is half visible.
![Screenshot](https://user-images.githubusercontent.com/922368/57172777-5fb82c80-6e2d-11e9-82c9-085fd6b3a27e.png)UNITO-UNDERSCORE!20190504-052620!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Preview!

### Device information
* Android device: OnePlus 5t
* Fenix version: the latest build from 3rd of May
![Screenshot](https://user-images.githubusercontent.com/922368/57172805-aa39a900-6e2d-11e9-9d94-2d0f336f6c27.png)UNITO-UNDERSCORE!20190428-135941!UNITO-UNDERSCORE!Settings!

**Comment by cadeyrn** [comment] 2019-05-04 06:44
Duplicate of #2245.

**Closed** 2020-08-11 14:40 UTC
Labels: 🐞 bug
