### ISSUE TITLE
[Bug] Can't upload images using Samsung Gallery, Google Photos, or other apps.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2673] opened 2019-05-21 03:22 UTC
## Steps to reproduce
Go to website where you can post images (I tried it on Post Images).
Touch upload, it will open the files app.
Inside the files app open the hamburger menu on the top left.
Select another app, like Google Photos.
Select an image to upload on the app you chose.

### Expected behavior
The image is uploaded

### Actual behavior
The image is not uploaded. After touching the image, it goes back to the files app.

### Device information
* Android device: Galaxy A5 2017 (8.0)
* Fenix version: 1.0.1921

**Comment by bifleming** [comment] 2019-05-21 19:06
@kbrosnan can we get a little more detail on what exactly is going on here?

**Comment by Amejia481** [comment] 2019-05-22 18:26
The issue is caused as we are using [launchMode="singleInstance"](https://github.com/mozilla-mobile/fenix/blob/9057eed6d7eaa6313ffcd9285044bb76c099ed82/app/src/main/AndroidManifest.xml#L27) in Fenix. This provokes that when the file manager app opens an external application, it creates a separated task for it, as a result when the user picks a file it returns to the file manager app instead of Fenix.

Here you can see the difference of Sample Browser that is using `launchMode="singleTask"` vs Fenix https://drive.google.com/file/d/1PCfd_21PmbcFHxa8xl1jqs-6uHxqKpfB/view?usp=sharing

I'm working on an alternative for this.

**Comment by Amejia481** [comment] 2019-05-23 16:21
@sblatz I noticed that you worked on https://github.com/mozilla-mobile/fenix/commit/e200807a7acce23d1ae2d43924459a151a88552e that added `launchMode="singleInstance"`. I'm seeming the issue described above because of it. Do we really need it? Is there not an alternative to using this `launchMode`?

**Comment by Amejia481** [comment] 2019-05-23 17:03
I noticed that in Reference browser we are using [launchMode="singleTask"](https://github.com/mozilla-mobile/reference-browser/blob/3370a0a22eee3edcb949b264749fa7febcaef398/app/src/main/AndroidManifest.xml#L29), could this be an alternative?

**Comment by sblatz** [comment] 2019-05-24 14:37
@Amejia481 let's make sure https://github.com/mozilla-mobile/fenix/issues/706 doesn't regress. If it doesn't when using `singleTask` it should be fine to use 😄

**Comment by sarentz** [comment] 2019-05-24 14:39
@sblatz so `singleInstance` was not added for a specific reason / requirement?

**Comment by sblatz** [comment] 2019-05-24 14:42
@sarentz I can't remember if I tried using `singleTask` before `singleInstance` and `singleInstance` fixed a lot of crashers we were having related to external launching. `singleTask` may also do this :)

**Comment by Amejia481** [comment] 2019-05-24 14:47
Thanks @sblatz  I will take a look at it.

**Comment by Amejia481** [comment] 2019-05-24 15:32
@sblatz I'm seeing the same crash on master ([video demo](https://drive.google.com/file/d/1-xb0Gmid8buclWnfhJKEnRR-FZmjrGXi/view?usp=sharing)), without using `singleTask` just by following the steps on #706. Do you have the same issue? I'm using a Pixel 3.

**Steps**
1. Navigate to a website from within Fenix
2. While BrowserFragment is open, press the middle button 
3. Open a link from an external source (I used  the Messages app)

**Crash**
```
2019-05-24 11:17:35.951 27804-27804/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 27804
    java.lang.RuntimeException: Unable to resume activity {org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity}: java.lang.RuntimeException: Failed to call observer method
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2675)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:908)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2087)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1861)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1817)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2684)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2646)
        at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:2612)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:268)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:479)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:468)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:195)
        at android.app.Activity.performResume(Activity.java:7325)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.IllegalStateException: Display already acquired
        at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:2181)
        at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:390)
        at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:353)
        at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:84)
2019-05-24 11:17:35.951 27804-27804/org.mozilla.fenix.debug E/AndroidRuntime:     at mozilla.components.feature.session.EngineViewPresenter.renderSession$feature_session_release(EngineViewPresenter.kt:51)
        at mozilla.components.feature.session.EngineViewPresenter.start(EngineViewPresenter.kt:31)
        at mozilla.components.feature.session.SessionFeature.start(SessionFeature.kt:27)
        at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.start$support_base_release(ViewBoundFeatureWrapper.kt:157)
        at mozilla.components.support.base.feature.LifecycleBinding.start(ViewBoundFeatureWrapper.kt:193)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
```

**Comment by Amejia481** [comment] 2019-05-24 15:42
@sblatz  the same issue happens with the `singleTask`. I'm not quite sure if this problem is related to the activity `launchMode`.

**Comment by sblatz** [comment] 2019-05-24 17:42
@Amejia481 I cannot reproduce this on my Galaxy S9 on master 😓

**Comment by Amejia481** [comment] 2019-05-24 19:01
I noticed the option **"Don't keep activities"** is  activated on my phone from a previous test. After disabled it the crash disappears. I think #706 is  still present, and it's more connected with the activity recreation  than with the **the activity launchMode** option. Please activate this option and try it. 

![image](https://user-images.githubusercontent.com/773158/58347085-e9568b00-7e2a-11e9-8e95-458d09605033.png)

From the AC side, I'm unable to do much as the behavior is induced by the activity launchMode, and we don't have much control of how third party apps reacts to it. 

If we don't have a strong reason why we need the launchMode. I think we should go back to the default launchMode, as [the documentation](https://developer.android.com/guide/topics/manifest/activity-element#lmode), and @colintheshots  https://github.com/mozilla-mobile/fenix/pull/829#issuecomment-469546912 described:

> The other modes — singleTask and singleInstance — are not appropriate for most applications, since they result in an interaction model that is likely to be unfamiliar to users and is very different from most other applications."

**Comment by Amejia481** [comment] 2019-05-27 13:03
This [Sentry exception](https://sentry.prod.mozaws.net/operations/fenix/issues/5811387/) looks like the same stack trace as #706 

```
java.lang.RuntimeException: Failed to call observer method
    at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:6)
    at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:2)
    at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:2)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
    at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:48)
    at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
    at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
    at androidx.fragment.app.Fragment.performStart(Fragment.java:10)
    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:105)
    at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:6)
    at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:54)
    at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:11)
    at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:4)
    at androidx.fragment.app.Fragment.performResume(Fragment.java:3)
    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:108)
    at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:209)
    at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
    at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:3)
    at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:3)
    at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:2)
    at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:1)
    at android.app.Activity.performResume(Activity.java:7317)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3803)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3843)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:198)
    at android.app.ActivityThread.main(ActivityThread.java:6729)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

java.lang.RuntimeException: Unable to resume activity {org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: java.lang.RuntimeException: Failed to call observer method
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3811)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3843)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:198)
    at android.app.ActivityThread.main(ActivityThread.java:6729)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by Amejia481** [comment] 2019-05-27 17:23
To sum up:

✅  I tested with `launchMode="singleTask"` and I'm not able to replicated #706.
 
💥   Using the option "**Don't keep activities"**. I'm able to replicated #706 with both  `launchMode="singleTask"` and `launchMode="singleInstance"`. What leads me to think that #706 is still there or a similar issue.

As we don't have a robust set of tests yet, that helps us to detect any regressions of switching to the **standard launchMode**, I will go with `singleTask` as it's the closest behavior to `singleInstance`,
and it allows other activities to be part of its task, that will fix this issue.

[Documentation android:launchMode](https://developer.android.com/guide/topics/manifest/activity-element).
 
> The **"singleTask"** and **"singleInstance"** modes also differ from each other in only one respect: A "singleTask" activity allows other activities to be part of its task. It's always at the root of its task, but other activities (necessarily "standard" and "singleTop" activities) can be launched into that task. A "singleInstance" activity, on the other hand, permits no other activities to be part of its task. It's the only activity in the task. If it starts another activity, that activity is assigned to a different task — as if FLAG_ACTIVITY_NEW_TASK was in the intent. 

### Follow up
I think we need a further investigation about #706 or a similar issue that is causing these [crashes on Sentry](https://sentry.prod.mozaws.net/operations/fenix/issues/5811387/).  For this reason I opened #2893, for investigating why we have a crash when  **"Don't keep activities"** option is activated

**Comment by softvision-miralobontiu** [comment] 2019-05-29 08:37
This issue is fixed only when "Don't keep activities" is OFF. 
Tested with the latest build 1.0.1922 (#11490609), with Nexus 6P (Android 8.1.0), and Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by Amejia481** [comment] 2019-05-29 14:22
@softvision-miralobontiu Could you help me to clarify what is the issue you are seeing on Nexus 6P (Android 8.1.0)?

* I used the same device with **"Don't keep activities"** ON ([video demo](https://drive.google.com/file/d/1FJ3Aa3IlO6fUOgTs6ZsRa_4LJJ8-ibfh/view?usp=sharing))  and I was able to upload a file using a third party apps (Google photos).

* The issue with **"Don't keep activities"** ON option should be only present trying to simulate #706, for this I opened #2893.

**Comment by softvision-miralobontiu** [comment] 2019-05-29 14:41
Here are 2 videos with the behavior when "Don't keep activities" is:
- [OFF](https://drive.google.com/open?id=1eZWneEpF2VzavVCf2T0iticDY1BZ0hYH)
- [ON](https://drive.google.com/open?id=18Wgzw0h9nos6QvAHCpC1YjniR0jKWhwz)

**Comment by Amejia481** [comment] 2019-05-29 14:45
Thanks!

**Comment by Amejia481** [comment] 2019-05-29 15:29
I'm unable to replicated the issue using the same device(Emulator Nexus P Android 8.1.0) [video](https://drive.google.com/file/d/1rfDcyr3ZGhw9QOv9eCrz9V_I8Rhz81F6/view?usp=sharing).
I think you can open an issue describing the specs of your device.

**Comment by bifleming** [comment] 2019-05-29 17:44
@softvision-miralobontiu Not sure why this is set to 'blocked'. If a bug is retested and still needs work, please set the bug back to 'In Progress' and add a comment @mentioning the developer.  We use 'blocked' to identify a bug or story that cannot move forward because it is dependent on some other work or information.

**Comment by softvision-miralobontiu** [comment] 2019-05-30 07:04
Got it!

Based on Arturo's [comment](https://github.com/mozilla-mobile/fenix/issues/2673#issuecomment-496987012) I will close this issue and open a new one describing the behavior on Nexus 6P device.

**Closed** 2020-08-26 06:10 UTC
Labels: P1, 🐞 bug
