### ISSUE TITLE
[Bug] Tab closed message does not disappear

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#7985] opened 2020-01-29 17:07 UTC
## Steps to reproduce

1. Open any website
2. Open links as new tabs
3. Close one tab and go back to the previous one

### Expected behavior

Tab closed message render but will disappear again after a few seconds.

### Actual behavior

Message stays there and only goes away when tapping at **undo** but actually clicking that button will not bring back the tab.

![Screenshot_20200129-175852_Firefox Preview](https://user-images.githubusercontent.com/52482050/73379249-347e4300-42c2-11ea-88ae-f9441258d32c.jpg)

### Device information

* Android device: Samsung Galaxy Note 10 Android 10
* Fenix version: 3.2.0 (Build #20250236)
28.0.2, 1deaef19a
GV: 73.0-20200123180644

**This bug is present since a few weeks on Nightly now!**
**Same on latest Nightly at my Oneplus 3T OOS9.0.6 Android 9**

**Comment by cadeyrn** [comment] 2020-01-29 17:29
Duplicate of #7799.

**Closed** 2020-01-30 00:24 UTC
Labels: needs:triage, 🐞 bug
