### ISSUE TITLE
[Bug] Paused/interrupted download shows as completed in-app notification

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6564] opened 2019-11-12 12:35 UTC
## Steps to reproduce
1. Download a large file. Pause it.
Or, cut-off the WIFI.
2. Check the in-app download notification.
3. Check the system notification,
4. Tap Open
### Expected behavior
"Download failed. Try again" should be displayed.
### Actual behavior
"Download completed. Open" is displayed in-app. 
The system notification shows it as completed.
The file is not entirely downloaded, so it won't open.
On Android 10, tapping Open crashes the app.
### Device information

* Android device: Pixel (Android 10), Sony Xperia  Z5 (Android 7.1.1)
* Fenix version: Nightly 11/12

**Comment by sblatz** [comment] 2019-11-13 19:19
Dupe of https://github.com/mozilla-mobile/fenix/issues/6434

**Closed** 2019-11-15 09:41 UTC
Labels: Feature:Download, S1, b:crash, 🐞 bug
