### ISSUE TITLE
[Bug] Swipe on the address bar to switch tabs - wrong order

### ISSUE THREAD

**Issue by bxtom** [mozilla-mobile/fenix#15457] opened 2020-09-26 13:14 UTC
## Steps to reproduce

Open link in new tab. Tab opens to the left of the currently active tab. Meanwhile on desktop new tab opens to the right.

### Expected behavior

New tab should open to the right of the currently active tab to be consistent with desktop browser. 

### Actual behavior

Tab opens to the left of the currently active tab. Makes swiping confusing experience.

### Device information

* Android device: OnePlus 5T, Android 10.
* Fenix version: latest nightly.

**Comment by marco-sanjuan** [comment] 2020-09-26 13:40
Agree.

This is important not only to be consistent with desktop browser, but consistent with most people way of thinking, as we read from left to right.

**Comment by black7375** [comment] 2020-09-29 21:29
It's a policy I don't understand either.

**Comment by yoasif** [comment] 2020-09-30 17:56
Dupe of https://github.com/mozilla-mobile/fenix/issues/13172

**Closed** 2020-10-15 00:38 UTC
Labels: needs:triage, 🐞 bug
