### ISSUE TITLE
Add an option to "Delete browser data on quit" when closing the activity

### ISSUE THREAD

**Issue by AndRo-Marian** [mozilla-mobile/fenix#18366] opened 2021-03-08 13:53 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Make an another category like "Delete browser data on quit" when exiting the android activity window.

### What is the user problem or growth opportunity you want to see solved?
I want to close tabs when I close the activity.

### Who will benefit from it?
Who want it. Like for closing tabs

**Comment by amedyne** [comment] 2021-03-08 14:54
Same request as #18103. Closing this to refer to other ticket.

**Comment by AndRo-Marian** [comment] 2021-03-08 14:57
I don't think is the same thing #18103

**Comment by kbrosnan** [comment] 2021-03-08 16:44
This is a duplicate of #5865

**Closed by kbrosnan** 2021-03-08 16:44 UTC
Labels: feature request 🌟
