### ISSUE TITLE
FNX-13091 ⁃ [Bug] new tabs UI makes it hard to scroll to newest tab

### ISSUE THREAD

**Issue by tarosk** [mozilla-mobile/fenix#12073] opened 2020-06-28 14:54 UTC
## Steps to reproduce
Open link(s) in new tabs in bacground
Open tabs list
List is possioned on current tab (thats ok) 
Scroll to down to reveal opened tabs on top of current tab
More often then not, you scroll too much, which is misinterpreted as gesture to close Tabs list - this is very frustrating if you try to get to the most recent tab opened in background. 

### Expected behavior
Disable gesture to close tabs list
Alternative B: revert to previous tabs interface. 

### Device information
Firefox preview 5.2.0 (Build #21701706)

**Comment by tarosk** [comment] 2020-06-28 14:58
Video of the issue

**Comment by sheikh-azharuddin** [comment] 2020-06-28 17:58
Works fine for me... Which Firefox version you have?

![2020-06-28-23-25-20](https://user-images.githubusercontent.com/58127841/85954715-f23c5900-b968-11ea-9e19-fc21e8ec94cb.gif)

**Comment by kbrosnan** [comment] 2020-06-28 18:32
Duplicate of #11042 which is fixed on Nightly builds

**Closed** 2020-08-11 05:41 UTC
Labels: Feature:Tabs, needs:UX-feedback, 🐞 bug
