### ISSUE TITLE
[Bug] First search from urlbar very slow, 2 minutes

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#14500] opened 2020-08-30 19:26 UTC
This sounds like it could be an MLS load issue #9935

from reddit https://www.reddit.com/r/firefox/comments/iit3nb/firefox_on_android_takes_around_2_minutes_to_give/g39zbj4/

## Steps to reproduce
On first start (?) type search through urlbar

### Expected behavior
Webpage with search results loads

### Actual behavior
The screen is completely white, takes ~2 minutes for search to load. 

Doesn't happen on subsequenty searches

### Device information

* Android device: ?
* Fenix version: ?

**Comment by mcomella** [comment] 2020-09-02 22:48
> This sounds like it could be an MLS load issue #9935

Triage: we agree this seems like it could be related to MLS. However, that sounds more like an implementation issue than a performance problem – **could someone from the fenix investigate to see if this seems plausible in the code?**

**Comment by mcomella** [comment] 2020-09-02 23:23
To be explicit, we should never block anything on the MLS request: if the user has a good internet connection but the MLS server is down, we don't want them to wait to use the browser. In that case, we should fallback to our best guess search engines and populate the real engines when they're available.

**Comment by mcomella** [comment] 2020-09-14 16:17
We've also been seeing issues where the app is blocked for a long time (30+ seconds) on DNS resolution: https://bugzilla.mozilla.org/show_bug.cgi?id=1664492

**Comment by mcomella** [comment] 2020-09-14 20:18
If someone is able to reproduce, the best thing to do is get a profile and it will probably pinpoint the root cause of the issue.

**Comment by sflorean** [comment] 2020-10-13 15:07
Tested on Nightly 10/12 with different devices & Android versions and we couldn't see any issue when interacting with the urlBar for the first time.

**Comment by Mugurell** [comment] 2020-10-13 15:32
Closing as such.
If this is still an issue for you please comment / reopen.

**Closed by Mugurell** 2020-10-13 15:32 UTC
Labels: Feature:Search, eng:performance, hershey, needs:investigation, 🐞 bug
