### ISSUE TITLE
[Bug]Firefox account login problems

### ISSUE THREAD

**Issue by JustAWhiteLily** [mozilla-mobile/fenix#15133] opened 2020-09-16 11:23 UTC
## Steps to reproduce
1. Go to Settings and tap on Turn on Sync.
2. Choose "Use email instead" and the browser goes to Firefox Sync sign up page.
3. Enter your email of your Firefox account and tap on "Continue".
### Expected behavior
Proceed to the webpage that asks for a 6-digit verification code received by email.
### Actual behavior
The browser freezes and shows "Firefox is not responding. Do you want to close it?" Then the browser returns to the previous "Turn on Sync" page.
### Device information

* Android device: Honor Tablet 5 (AGS2-AL00HN). Android 9. EMUI 9.1.0 (This device does not have GMS)
* Fenix version:  80.1.3
[
The log is here.](https://gist.github.com/JustAWhiteLily/96d1b8687df6860b5edab34a3fa36e7a)

Note: Firefox also has at least another three issues on this device and a 5-year-old Huawei smartphone running Android Nougat has almost the same problems.

**Comment by ekager** [comment] 2020-12-18 06:04
@JustAWhiteLily thanks for filing! Can you still reproduce this?

**Comment by JustAWhiteLily** [comment] 2020-12-20 09:11
> 
> 
> @JustAWhiteLily thanks for filing! Can you still reproduce this?

I think this problem still exists in the latest stable release.

**Comment by JustAWhiteLily** [comment] 2020-12-20 10:31
> 
> 
> @JustAWhiteLily thanks for filing! Can you still reproduce this?
Here are the results from the latest version available from Google Play:
<script src="https://gist.github.com/JustAWhiteLily/54e555df073b77bf8350b13d332da8f1.js"></script>

**Comment by lobontiumira** [comment] 2021-06-24 11:31
@JustAWhiteLily I was not able to reproduce this issue on the latest RC build 89.1.1 with Google Pixel (Android 10), Sony Xperia Z5 Premium (Android 7.1.1), nor with Xiaomi mi4i (Android 5.0.2).
Could you retest please?
Thank you!

**Comment by JustAWhiteLily** [comment] 2021-06-26 11:52
> 
> 
> @JustAWhiteLily I was not able to reproduce this issue on the latest RC build 89.1.1 with Google Pixel (Android 10), Sony Xperia Z5 Premium (Android 7.1.1), nor with Xiaomi mi4i (Android 5.0.2).
> Could you retest please?
> Thank you!

I almost forget that I once filed this bug. I don't know if it still exist now.

**Comment by sflorean** [comment] 2021-12-29 13:58
Closing based on the comments above. Please re-open if the issue occurs again. Thank you!

**Closed by sflorean** 2021-12-29 13:58 UTC
Labels: 🐞 bug, Feature:Sync, b:anr, Feature:Accounts, wontfix, qa-triaged
