### ISSUE TITLE
[Bug]: Add logins dupe username error flashes then disappears

### ISSUE THREAD

**Issue by bendk** [mozilla-mobile/fenix#21403] opened 2021-09-21 14:32 UTC
### Steps to reproduce

- Save a login in FF
- Open the add logins dialog
- Edit the site field to match the saved login
- Edit the username field to to match the same login

### Expected behaviour

Duplicate login error is displayed

### Actual behaviour

Duplicate login error flashes for a moment, then disappears

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

**Comment by SoftVision-LorandJanos** [comment] 2021-09-22 13:24
Hi @bendk! Thank you for your report.
I can confirm the issue is reproducible as described.

Firefox versions tested:
- Nightly (94.0a1 - 2021-09-22).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Mi11 Lite (Android 11).

**Comment by SoftVision-LorandJanos** [comment] 2022-03-21 15:33
As mentioned in #21404, the error message for an already existing username is displayed, and remains displayed which is the same behavior on edit.
The site field is not editable once the manually added login is created.
Tested on the latest Nightly 100.0a1 (2022-03-21).
Device used: Google Pixel 4 (Android 12).
Closing the ticket as verified.

**Closed by SoftVision-LorandJanos** 2022-03-21 15:33 UTC
Labels: 🐞 bug, S3, Feature:Logins, needs:triage, wontfix, qa-triaged
