### ISSUE TITLE
Delete Website-Data for specific domain

### ISSUE THREAD

**Issue by benjaminwolkchen** [mozilla-mobile/fenix#9294] opened 2020-03-20 20:30 UTC
### Why/User Benefit/User Problem
You can delete e.g the Cookies and Website-Data for only one Domain - without losing your logins for other domains.
### What/Requirements
A option when clicking e.g. on the SSL-Lock to delete all cookies for that specific domain.
### Acceptance Criteria (how do I know when I’m done?)
If you can clear all Cookies and Website-Data only for one specific domain.

**Comment by Poopooracoocoo** [comment] 2020-03-21 10:23
Fenix's page info sheet should be like the page info popup on Firefox for desktop! :D

current mobile:
![Screenshot_1584786065](https://user-images.githubusercontent.com/51363864/77224468-0c240e00-6bba-11ea-95ef-2ae5b5d8d688.png)


desktop:
![image](https://user-images.githubusercontent.com/51363864/77224441-cb2bf980-6bb9-11ea-9c7b-b5e91f17351d.png)

**Comment by Poopooracoocoo** [comment] 2020-03-23 04:11
Reverse the items of desktop page info popup and you get something like a sheet :P 

![image](https://user-images.githubusercontent.com/51363864/77278533-aea3d480-6d13-11ea-8230-45d888090d28.png)


for reference, here's fennec:
![image](https://user-images.githubusercontent.com/51363864/77251476-a6f81780-6ca2-11ea-9585-f739902ed23d.png)

it's strange that Fenix's page info sheet is Grey 10 of the Photon Design System. I've discussed the theme inconsistency between desktop and Fenix in #4235

**Comment by Poopooracoocoo** [comment] 2020-03-25 07:48
![image](https://user-images.githubusercontent.com/51363864/77513250-c2dd0280-6ec8-11ea-95c4-0d43d0db1355.png)
![image](https://user-images.githubusercontent.com/51363864/77513408-0afc2500-6ec9-11ea-9163-0a2a0eea0f31.png)

**Comment by Poopooracoocoo** [comment] 2020-03-26 02:24
New concepts:
tracking protection sheet:
![image](https://user-images.githubusercontent.com/51363864/77603367-033d8e80-6f64-11ea-9e58-de4f1a5d521d.png)
page info sheet:
![image](https://user-images.githubusercontent.com/51363864/77603770-09803a80-6f65-11ea-93ac-35a783e5c396.png)

**Comment by Dunexus** [comment] 2020-03-26 09:12
This is somehow related to https://github.com/mozilla-mobile/fenix/issues/4235 as it discuss where does UX team want to put the limit between cross-platform consistency and per-platform integration and specific limits and needs.

cc @betsymi as you mentionned that inconsistency across platforms was a reason you are getting more involved in these details on mobile (https://github.com/mozilla-mobile/fenix/issues/8653#issuecomment-590878871)

**Comment by betsymi** [comment] 2020-03-31 16:34
> This is somehow related to #4235 as it discuss where does UX team want to put the limit between cross-platform consistency and per-platform integration and specific limits and needs.
> 
> cc @betsymi as you mentionned that inconsistency across platforms was a reason you are getting more involved in these details on mobile ([#8653 (comment)](https://github.com/mozilla-mobile/fenix/issues/8653#issuecomment-590878871))

For the time being, I think we are as aligned as we can be here in Fenix mobile and desktop. It's not 1:1, but we've brought them together as much as we can given the platform limitations of each. 

There are ongoing conversations in both platforms about the 🛡 and 🔒 icons and what information is housed in each. There has also been discussion of consolidating to a single icon. Nothing has been decided though. At this time, we are keeping things as they are. 

### 🛡ETP shield

The desktop screenshot from the beginning of this thread is from an older UI that we phased out in Firefox 70. Fenix doesn't have the `None Detected` section because it's lengthy, nor the Protection Report link since that doesn't exist on mobile. 

**🛡in Fenix**  
![Screenshot_20200331-112646](https://user-images.githubusercontent.com/43555492/78051062-c9450180-7342-11ea-801c-889a237f5f71.png)

**🛡 in desktop**

![Screen Shot 2020-03-31 at 11 27 49 AM](https://user-images.githubusercontent.com/43555492/78051122-da8e0e00-7342-11ea-842c-42a79f74841a.png)

### 🔒Site security

We house permissions here in desktop, but in a different place on Fenix. In desktop, it takes an additional click to see the details about the security certificate that are housed behind the >

🔒 **in Fenix**

![Screenshot_20200331-112700](https://user-images.githubusercontent.com/43555492/78051373-3193e300-7343-11ea-8929-ad04178941b1.png)

🔒 **in desktop**

![Screen Shot 2020-03-31 at 11 28 01 AM](https://user-images.githubusercontent.com/43555492/78051405-3eb0d200-7343-11ea-93df-a444d38a2a38.png)

![Screen Shot 2020-03-31 at 11 30 27 AM](https://user-images.githubusercontent.com/43555492/78051414-41abc280-7343-11ea-911a-96968563e158.png)

**Comment by Poopooracoocoo** [comment] 2020-04-02 07:36
@betsymi As I was saying in the edit of my first comment are separate buttons for tracking protection and site info necessary?

**Comment by yoasif** [comment] 2020-04-05 17:49
This is really required, as I am currently unable to do good testing of site issues when cookies may make a difference, especially if I am trying to test what happens with uBlock Origin (we can't run add-ons in private mode). 

Also, paywalls that detect private browsing mode, where dumping cookies and site data would work to view page content.

**Comment by yoasif** [comment] 2020-04-05 17:50
This seems to be a dupe of  #7981

**Comment by Poopooracoocoo** [comment] 2020-04-07 11:49
@benjaminwolkchen @Dunexus do you guys prefer a separate button and popup for tracking protection?

**Comment by BobbyWibowo** [comment] 2021-01-29 14:57
Is there any known alternative to do this aside from clearing ALL cookies at the moment?

**Comment by sheikh-azharuddin** [comment] 2021-09-13 15:12
Any update? This feature is present in other browsers..we need this to clear a specific site cookies rather than deleting all!

**Comment by JonahGroendal** [comment] 2021-11-04 22:50
As a web developer it's very frustrating that I can't do this! Any word on adding this feature?

**Comment by LaurentiuApahideanSV** [comment] 2022-01-10 18:15
I tested the issue on the latest Firefox Preview Nightly 2022-01-10.
The "Clear cookies and site data" button is present after tapping the lock icon.
I tested it's functionality by following these steps:
1. Go to a site that requires cookies (cnn.com, bbc.com)
2. Accept the cookies;
3. Tap the lock icon;
4. Tap the "Clear cookies and site data" button and Delete;
5. Reload the site.
6. The prompt requesting Cookies is shown again.

I will mark this issue as fixed.

### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 6 (Android 12)
![1641836213790](https://user-images.githubusercontent.com/50983519/148817513-3e776f94-25ab-4c09-9749-6a9642075969.JPEG)

**Closed** 2022-01-12 08:35 UTC
Labels: feature request 🌟, eng:qa:verified
