### ISSUE TITLE
FNX-5591 ⁃ [Bug] Switching back from private browsing issue

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2323] opened 2019-05-07 20:13 UTC
## Steps to reproduce
1. Open page in normal browsing
1. Menu > New Private Tab
1. Press Back

### Expected behavior
1. Back in normal browsing with correct tab count showing

### Actual behavior
1. In private browsing mode and tabs say "0"

**Comment by ekager** [comment] 2019-05-08 20:57
@vesta0 I'm picking this up :)

**Comment by bsurd** [comment] 2019-05-13 12:11
Fenix now crashes following the STR, the user remaining blocked in private mode. Closing and reopening the app seems to fix the issue, normal browsing being displayed with the correct number of tabs, if you were in normal private browsing..

[Video here](https://drive.google.com/open?id=1uExiUE6G_Px-qOoTf0tIR5cuAzApp7Gh)

@ekager could you have a look into this?

**Comment by cadeyrn** [comment] 2019-05-13 19:46
The crash reported in the last comment was fixed in #2450.

**Comment by bsurd** [comment] 2019-05-14 15:06
This now works as intended, I have noticed #2411 during testing.

**Closed** 2020-08-11 14:49 UTC
Labels: Feature:PrivateBrowsing, P1, b:crash, eng:qa:verified, 🐞 bug
