### ISSUE TITLE
Option to reuse tabs

### ISSUE THREAD

**Issue by lvmm** [mozilla-mobile/fenix#15341] opened 2020-09-23 09:13 UTC
### What is the user problem or growth opportunity you want to see solved?
Since version 80(?) firefox opens new tabs for each new bookmark or URL. Provide an option to reuse current tab by default and open new tabs only when explicitly requested.

### How do you know that this problem exists today? Why is this important?
Firefox gets cluttered with useless tabs, difficult to find the ones needed, memory usage probably suffers too.

### Who will benefit from it?
Everyone efficient and organized.

**Comment by cadeyrn** [comment] 2020-09-23 09:24
Duplicate of #13336.

**Comment by Northshorecowboy** [comment] 2020-09-24 02:36
Agree 100% with the user that opened this discussion. I now end up with countless tabs open. Very inefficient. Much prefer the old system that let the user decide when to open a new tab. SAME AS THE DESKTOP BROWSER DOES. Plus, I now find when I've closed the browser, all the previous tabs have migrated to the home page creating unwanted confusing clutter. What a mess.

**Comment by kbrosnan** [comment] 2020-09-24 04:07
Closing as a duplicate of #13336.

**Closed by kbrosnan** 2020-09-24 04:07 UTC
Labels: needs:triage
