### ISSUE TITLE
[Bug] Videos in some Android resolution are cut 

### ISSUE THREAD

**Issue by JoGarWeb** [mozilla-mobile/fenix#16845] opened 2020-12-03 20:32 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Recently I Bougth a new phone, this phone have a resolution of 720x1517px. First i think who was the phone, but i try to emulate with Android Virtual Device and I have same results. This not happened in Chromium Based Browsers (I tested in Bromite Browser).

## Steps to reproduce
Create AVD virtual Machine with Resolution of 720x1517px
Install Firefox
Go to youtube.com and play some video. 
Play the video in Full Screen

Now you will notice that only the bottom part of the video has been cut off.
![Video on YouTube](https://user-images.githubusercontent.com/7904563/101084768-0f0e3580-3574-11eb-9dc8-7a9677b8fe55.png)

![Video on Full Screen](https://user-images.githubusercontent.com/7904563/101084861-31a04e80-3574-11eb-90f3-893b66382467.png)

### Expected behavior
The video plays without cuts

### Actual behavior
The video has been cut at the bottom.

### Device information

* Android device: Nokia 5.3 Android 10
* Fenix version: Tested on: "2201202 17:05" and "83.1.0"

**Comment by TyDraniu** [comment] 2020-12-04 10:37
Dupe of #8252 ?

**Closed** 2021-08-05 22:25 UTC
Labels: 🐞 bug, Feature:Media, wontfix
