### ISSUE TITLE
[Bug] Selection Handlers are low in responsiveness

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5204] opened 2019-09-10 22:17 UTC
## Steps to reproduce
-Open a site that contains text
-Long press to select/highlight part of the text
-Try to move the selection handlers to expand or narrow down the selection 

### Expected behavior
-Selection handlers are responsive

### Actual behavior
-Selection handlers are jumpy

### Device information

* Android device: Pixel 3
* Fenix version: Latest nightly

**Comment by ekager** [comment] 2019-09-12 03:24
Dupe of #5037

**Closed by ekager** 2019-09-12 03:24 UTC
Labels: P2, needs:group-triage, 🐞 bug
