### ISSUE TITLE
FNX-5122 ⁃ Long press the tab icon to open a new tab.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1591] opened 2019-04-12 04:18 UTC
### Why/User Benefit/User Problem
With less touches it makes the process of opening a new tab easier and faster.

### What / Requirements
A new tab is opened as soon as the tab icon is long pressed.

### Acceptance Criteria (how do I know when I’m done?)
Long pressing the tab icon opens a new tab.

**Comment by cadeyrn** [comment] 2019-04-12 07:20
Duplicate of #425.

**Comment by vesta0** [comment] 2019-04-17 05:17
Thanks for the suggestion @Lululalu We will work on it here: #176

**Closed** 2020-08-11 12:12 UTC
