### ISSUE TITLE
[Bug] Tracking protection is off inside the custom tab browser even through the settings inside Firefox Preview has it turned on

### ISSUE THREAD

**Issue by ehsan** [mozilla-mobile/fenix#2467] opened 2019-05-14 03:08 UTC
## Steps to reproduce
1. Download and run the latest version of Firefox Preview.
1. Go to Settings and enable Tracking Protection.
1. Go to Gmail and click on an HTTPS link.
1. Click on the lock icon. The settings here show that Tracking Protection is turned off.

### Expected behavior
It should be turned on.

### Actual behavior
It is turned off.

### Device information
* Android device: HTC one m9
* Fenix version: 1.0.1919

**Comment by ekager** [comment] 2019-05-14 16:52
Dupe of #2336

**Closed** 2020-08-26 05:31 UTC
Labels: 🐞 bug
