### ISSUE TITLE
[Bug] Previous tab flashes on swipe to switch tab

### ISSUE THREAD

**Issue by hkaancaliskan** [mozilla-mobile/fenix#18131] opened 2021-02-23 17:21 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1- open multiple tabs via collections
2- swipe toolbar to switch tabs
### Expected behavior
No flash of previous tab
### Actual behavior
Previous tab flashes over new tab
### Device information

* Device vendor / model and Android version: XZ1 Android 11
* Firefox for Android version: 2/22 nightly

Note: Especially visible on cold start.

https://user-images.githubusercontent.com/17825767/108882028-febaa380-7614-11eb-9f72-4eeab7bc3acf.mp4

**Comment by codrut-topliceanu** [comment] 2021-03-10 12:01
I'm afraid I haven't been able to find a fix for this.
The issue seems to stem from the way we restore tabs in `SessionControlController.handleCollectionOpenTabsTapped(..)` as using the `addTabUseCase` instead of `restoreUseCase` seems to circumvent the problem altogether.

Further notes:

- issue reproducible even when switching tabs via tab tray
- issue is not dependant on site load status. Even waiting for a site to fully load and then switching tabs you still see the content of the original tab for a split second
- opening the collection tabs while having an open tab already still reproduces the issue

**Comment by mariansima** [comment] 2021-09-07 12:38
This issue still occurs on Samsung A8 (Android 9) with Firefox Nightly 93.0a1 2021-09-07

**Comment by Cheap-Skate** [comment] 2021-09-24 14:13
I still have this issue (just commenting to stop Stalebot closing it)

**Comment by jonalmeida** [comment] 2022-02-01 19:24
Closing as duplicate of BZ-1753085. I've linked this issue in there as well.

**Closed by jonalmeida** 2022-02-01 19:24 UTC
Labels: 🐞 bug
