### ISSUE TITLE
Reverse tab order

### ISSUE THREAD

**Issue by Taknok** [mozilla-mobile/fenix#14385] opened 2020-08-28 18:52 UTC
**What is the growth opportunity you want to see solved?**
Avoid long thumb travel across the screen by reversing the tab list when using bottom navigation bar.

**Why?**
The new navigation bar and buttons are at the bottom of the screen. This is to easy navigation with phone getting bigger and avoid long thumb travel across the screen. But when opening the tab menu in Fenix the latest opened tabs are at the top of the screen. Those latest opened tabs have an high probability to be the destination of the user. Thus, reversing the tag lost order will easy access to more recents tabs as the user will already has touch the bottom of the screen to open the tab menu.

**Who will benefit from it?**
User in general and their thumb.

**Comment by AVHon** [comment] 2020-08-28 21:23
This seems like a good idea for 2 reasons: it minimizes travel distance for users who choose to have the navbar at the bottom, and it maintains the behavior of Firefox 68's tab organization (which added new tabs at the bottom of the list).

**Comment by amkcpu** [comment] 2020-08-28 23:07
Duplicate of #11376

**Comment by liuche** [comment] 2020-08-28 23:33
Thank you, please follow along in that issue^!

**Closed by liuche** 2020-08-28 23:33 UTC
Labels: needs:triage

**Comment by OsadebamwenEvbuomwan** [comment] 2020-08-28 23:35
Pls Change this back to the old way, I don't like moving my thumb more. 
![Screenshot_20200829-003208](https://user-images.githubusercontent.com/40303809/91622529-61e1bb00-e98f-11ea-8a36-dfbeec9b256a.png)
OLD. Had add new tab at the bottom.

![Screenshot_20200829-003145](https://user-images.githubusercontent.com/40303809/91622539-73c35e00-e98f-11ea-91aa-5c19c18c55da.png)
NEW. Had add new tab at the top pls fix.

**Comment by person808** [comment] 2020-08-29 01:14
@OsadebamwenEvbuomwan that is unrelated to this issue and should be filed as a new issue.

**Comment by Taknok** [comment] 2020-08-29 08:28
My point is not about the position of the button to create a new tab, but about going to an existing tab.
