### ISSUE TITLE
FNX2-13444 ⁃ [Bug] Inconsistencies with the ETP shield being highlighted

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11387] opened 2020-06-09 18:00 UTC
## Steps to reproduce
-On a fresh install, navigate to cnn.com 

### Expected behavior
-The ETP shield is highlighted and the CFR is shown

### Actual behavior
* The ETP shield is not highlighted right away but if you tab on one of the cnn articles then the shield is highligherd and the CFR shows after the 2nd interaction. 

### Device information
* Android device: Pixel 4
* Fenix version: Latest Firefox Beta/Firefox Preview

**Comment by sv-ohorvath** [comment] 2020-06-10 06:31
@vesta0 @Amejia481 I've found this issue on automation tests too but couldn't reproduce manually. I think it's the same issue, isn't it? https://github.com/mozilla-mobile/fenix/issues/11370

**Comment by Amejia481** [comment] 2020-06-15 15:01
I can replicate the issue on nightly. So far, what I could find it's that we are not getting a call on 
[onContentBlocked](https://github.com/mozilla-mobile/android-components/blob/28c9be258747ff964d0a92808a57ae31f791cb31/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L726) on the first load of a session, still I'm trying to figure out if it's an ac issue or gv one. 

STR:
1. Open a new tab.
2. Go to ccn.com (The shield doesn't get highlighted).
3. If you fresh or try to go to ccn.com on the same tab the shield gets highlighted.

**Comment by Amejia481** [comment] 2020-06-17 15:07
I opened a bugzilla ticket for the gv and privacy team to help us to further investigate  https://bugzilla.mozilla.org/show_bug.cgi?id=1646392

**Comment by Amejia481** [comment] 2020-06-29 13:37
It's been more than a week since the last time that I was able to reproduce. @vesta0 @ekager  are you able to reproduce in nightly ?

**Comment by Amejia481** [comment] 2020-06-29 13:38
> I can replicate the issue on nightly. So far, what I could find it's that we are not getting a call on
> [onContentBlocked](https://github.com/mozilla-mobile/android-components/blob/28c9be258747ff964d0a92808a57ae31f791cb31/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L726) on the **first load of a session**, still I'm trying to figure out if it's an ac issue or gv one.
> 
> STR:
> 
>     1. Open a new tab.
> 
>     2. Go to ccn.com (The shield doesn't get highlighted).
> 
>     3. If you fresh or try to go to ccn.com on the same tab the shield gets highlighted.

QA please help us to verify if this is still reproducible, thanks in advance.

**Comment by Amejia481** [comment] 2020-06-29 14:01
> It's been more than a week since the last time that I was able to reproduce. @vesta0 @ekager are you able to reproduce in nightly ?

@sv-ohorvath the test is still flaky?

**Comment by sv-ohorvath** [comment] 2020-06-29 15:57
> > It's been more than a week since the last time that I was able to reproduce. @vesta0 @ekager are you able to reproduce in nightly ?
> 
> @sv-ohorvath the test is still flaky?

We haven't seen it fail recently, but it wasn't too frequent before either, so I can't really tell. I'll try to run it a few times tomorrow.

**Comment by softvision-miralobontiu** [comment] 2020-06-30 10:10
I was able to reproduce this issue on the latest Beta build 79.0.0-beta.1 (#21820831) with HTC 10 (Android 8), and Samsung Galaxy Tab S6 (Android 9).
Maybe the logcat might help.
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4851005/logcat.txt)

**Comment by Amejia481** [comment] 2020-06-30 13:09
> I was able to reproduce this issue on the latest Beta build 79.0.0-beta.1 (#21820831) with HTC 10 (Android 8), and Samsung Galaxy Tab S6 (Android 9).
> Maybe the logcat might help.
> [logcat.txt](https://github.com/mozilla-mobile/fenix/files/4851005/logcat.txt)

@softvision-miralobontiu thanks!

This is the same behaviour that I see. I haven't been able to reproduce on nightly any more. I'm not sure what should be we do here @vesta0 @ekager?

**Comment by st3fan** [comment] 2020-06-30 15:39
I added a release blocker label on this one because it sounds serious, but I think we could decide to ship without a fix.

@ekager @Amejia481 If we do not see this on Nightly, is it possible that a fix was not included in the 79 branch? Are we aware of any issues that were worked on related to this?

**Comment by softvision-miralobontiu** [comment] 2020-07-01 11:09
I was able to reproduce this issue on the 79.0.0-beta.3 build with Samsung Galaxy Tab S6 (Android 9).
I'll remove the qa:needed label.

**Comment by ekager** [comment] 2020-07-01 19:04
I can still repro on geckoNightlyDebug geckoBetaDebug variants locally and on my Nightly build.
Make sure you don't have any add-ons enabled while testing this because I noticed ublock can eat some of the trackers that we would report (not sure if that's expected?).

**Comment by Amejia481** [comment] 2020-07-02 13:24
> I can still repro on geckoNightlyDebug geckoBetaDebug variants locally and on my Nightly build.
> Make sure you don't have any add-ons enabled while testing this because I noticed ublock can eat some of the trackers that we would report (not sure if that's expected?).

Thanks for the info, I was able to reproduce the issue in nightly, [we are continue trying to find the source of the issue ](https://bugzilla.mozilla.org/show_bug.cgi?id=1646392).

**Comment by Amejia481** [comment] 2020-07-08 15:01
[A patch has landed on GV ](https://bugzilla.mozilla.org/show_bug.cgi?id=1646392), we are waiting for the new gv version get updated on ac and the subsequent version of ac that has the fixed land of Fenix

**Comment by Amejia481** [comment] 2020-07-10 18:59
This should be fixed on nightly

**Comment by abodea** [comment] 2020-07-13 15:03
Verified as fixed on the latest **Nightly 7/13** with **Google Pixel 4 XL (11).**
Note that the ETP shield is being highlighted, I had more than 5 tries and it worked correctly.

**Closed** 2020-08-12 17:29 UTC
Labels: E13, P1, eng:qa:verified, needs:gv, 🐞 bug
