### ISSUE TITLE
FNX-5209 ⁃ [Bug] Resuming after full screen mode breaks app

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1722] opened 2019-04-17 19:00 UTC
## Steps to reproduce
1. Go to youtube
1. Open a video in full screen
1. Press the home button
1. Open Fenix again

### Expected behavior
1. Fenix appears in full screen with the video paused

### Actual behavior
1. Fenix displays a black screen, pressing back back leaves the app "cut off" at the top

![](https://user-images.githubusercontent.com/4400286/56313839-6abe4d80-6108-11e9-863c-2e0f5eeaf1aa.png)

**Comment by vesta0** [comment] 2019-04-24 03:47
I get the expected behaviour (Fenix appears in full screen with the video paused) but pressing the back button launches the whole site in full screen (top of the app overlaps with phone indicators).

**Comment by colintheshots** [comment] 2019-06-05 18:13
Fixed with the fix to #3103. PR#3112.

**Comment by AndiAJ** [comment] 2019-06-28 11:48
Hi, I wasn't able to reproduce this issue on the latest Fenix build (#11790617 from 28/6) using the following devices:

• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy J7 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

However, I would have a couple of questions:
1. Should the video be **paused** when resuming Fenix?
2. Should Fenix be **resumed in full screen**? I'm asking this because as per [#3103](https://github.com/mozilla-mobile/fenix/issues/3103) it can either be resumed in full screen or normal view

#### **On none of the above mentioned devices the video was resumed in full screen mode**

The video from the Samsung Galaxy J7 gives the best overview of what is actually happening
![2019_06_28_14_26_43](https://user-images.githubusercontent.com/51314259/60340155-7d2fef80-99b3-11e9-8225-ef8de3985e7b.gif)

Based on what @sblatz & @colintheshots will confirm I'll proceed in opening a new bug or not.

**Comment by sblatz** [comment] 2019-06-28 18:32
@AndiAJ I think it'd be a good idea to just open a new issue and mark it with a label "Needs UX Feedback" so that we can get confirmation on that :)

**Closed** 2020-08-11 12:34 UTC
Labels: Feature:HomeScreen, P2, b:web-content, eng:qa:verified, 🐞 bug
