### ISSUE TITLE
[Bug] The keyboard is triggered while opening links in new tabs from wikipedia

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3556] opened 2019-06-19 14:30 UTC
## Steps to reproduce
1. Open wikipedia.com. Tap the search bar.
1. Long tap a link - open in new tab.
1. While the "switch to tab" snackbar is still displayed, long-tap another link.
    1. Expected behavior
The context menu is displayed.
    1. Actual behavior
The keyboard is triggered while the context menu is displayed.
This happens on wikipedia, elefant.ro, amazon.com. It has something to do with websites that have a search bar on the homepage.
Can't repro on other website: cnn, planet.mozilla.org,
    1. Device information

* Android device: HTC 10 (Android 9)
* Fenix version: 1.0.0 rc2

**Comment by sblatz** [comment] 2019-06-21 16:47
This looks like a dupe of https://github.com/mozilla-mobile/fenix/issues/2071. Please re-open if I'm wrong :)

**Closed** 2020-08-25 20:24 UTC
Labels: 🐞 bug
