### ISSUE TITLE
[Bug] "Tab sent!" popup prevents opening of the tabs overview until it disappears.

### ISSUE THREAD

**Issue by mystiquewolf** [mozilla-mobile/fenix#16927] opened 2020-12-08 20:12 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Send a tab to computer
2. While the "Tab sent!" popup is still shown try to tap on the number of tabs, in order to show the tabs overview.
### Expected behavior
I should be able to open the tabs overview while the "Tab sent!" popup is shown.
### Actual behavior
Currently it makes me angry because i have to wait for it to disappear before i'm able to close the tab.
### Device information
* Android device: Motorola One Macro
* Fenix version: 83.1.0

**Comment by s-ankur** [comment] 2020-12-09 12:41
Duplicate  #15242

**Comment by s-ankur** [comment] 2020-12-09 12:43
And i think https://github.com/mozilla-mobile/fenix/issues/11199 should also be duped in as well

**Comment by jonalmeida** [comment] 2020-12-16 05:58
Duplicate of #15242

Thanks @s-ankur !

**Closed by jonalmeida** 2020-12-16 05:58 UTC
Labels: Feature:SendTab, Feature:Snackbar, 🐞 bug
