### ISSUE TITLE
[Bug] "Share" problem on in-app tabs

### ISSUE THREAD

**Issue by kamran-12** [mozilla-mobile/fenix#5330] opened 2019-09-14 11:16 UTC
### Steps to reproduce
Open links in different apps using in-app Fenix tab. I did this using Telegram, Feedly, and Reddit. When you opened the link, press the 3-dot button to make sure it is "Powered by Firefox Preview". If something else is used, go to settings, clear that app's defaults and repeat the process.

### Expected behavior
It should have a normal-looking Share button outside the 3-dot menu

### Actual behavior
When using Feedly there is a super-weird share button left to 3-dot menu button and it works. This button doesn't appear with Telegram and Reddit.

![image](https://user-images.githubusercontent.com/46045997/64907372-87d06a00-d702-11e9-85ee-6d4c8b5e48f2.png)

### Device information
* Android device: Samsung, Android 7.0
* Fenix version: 1.4.1

**Comment by ekager** [comment] 2019-09-14 18:30
I think the not working menu item is a dupe of #4997 that was fixed by #5029 and should be in the next release.

The large toolbar item needs investigation. Could you please give me more STR on how to get to this state? I don't use Feedly and I'm not sure how to trigger a custom tab there. :)

**Comment by nahuhh** [comment] 2019-09-14 18:59
Share button on custom tab opened from Reddit confirmed working  on 
Nightly 190914 06:02 (Build #12570610)
📦: 13.0.0, 1f55c03be
🦎: 71.0a1-20190913092859
![20190914_145540](https://user-images.githubusercontent.com/50635951/64912640-3921d080-d700-11e9-9883-a34623b26d09.gif)

**Comment by talsemgeest** [comment] 2019-09-18 21:41
I've been seeing the same large share button when using Feedly. To reproduce, in Feedly settings make sure "Preferred Browser" is set to "Built-in" which causes it to use custom tabs. Then simply tap on an article, then tap on the article title which will open it in the custom tab.

**Comment by ekager** [comment] 2019-09-18 21:50
Ah thank you @talsemgeest ! Seeing it now. Filed https://github.com/mozilla-mobile/android-components/issues/4457

**Comment by NotWoods** [comment] 2019-09-26 03:30
I'm going to close the Fenix ticket since all the work is on the Android Components side.

**Comment by NotWoods** [comment] 2020-02-04 00:29
I couldn't reproduce the issue of the button not working. Tapping the share icon brings up a share sheet for me. QA team can you also double-check that you can open a share sheet using the button?

**Comment by AndiAJ** [comment] 2020-02-04 14:20
Hi, I've re-checked this matter on the latest **`Nightly Build #20350605 from 2/4`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3 XL (Android 9)
• Samsung Galaxy S9 (Android 8.0.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Reddit
❌ No share button is available.

► Feedly
❌ The oversized share button issue is still there.
✔️ Tapping the button opens the a share sheet.

► Video
![20200204_161639](https://user-images.githubusercontent.com/51314259/73752762-2caf1a80-476a-11ea-856a-5891aba0265c.gif)

@ekager & @NotWoods - Please review an advise. ☺️ 
I'll remove the QA needed until further notice.

**Comment by NotWoods** [comment] 2020-02-04 16:53
Closing since the tap behaviour is working as intended. I'll leave the Android Components issue for the sizing problem.

**Closed by NotWoods** 2020-02-04 16:53 UTC
Labels: P3, 🐞 bug
