### ISSUE TITLE
preserve some cookies when deleting browsing data

### ISSUE THREAD

**Issue by tortino** [mozilla-mobile/fenix#14447] opened 2020-08-29 16:40 UTC
### What is the user problem or growth opportunity you want to see solved?
deleting all browsing data is unconvenient, since users are logged off of all web sites.
I'd like to set some exceptions for cookies, that will not be deleted.
so please add an option to specify exceptions for cookies in "delete browsing data" functionality.
### How do you know that this problem exists today? Why is this important?
It's convenient for users to avoid having to login again in web sites.
### Who will benefit from it?
all users that logs in into web sites.

**Comment by cadeyrn** [comment] 2020-08-29 16:41
Duplicate of #13855.

**Comment by kbrosnan** [comment] 2020-08-29 16:49
Closing as a duplicate

**Closed by kbrosnan** 2020-08-29 16:49 UTC
Labels: needs:triage
