### ISSUE TITLE
Audio/video playback ceases on loss of focus (Firefox for Android v 79.0.5)

### ISSUE THREAD

**Issue by aaggcc** [mozilla-mobile/fenix#14367] opened 2020-08-28 15:46 UTC
Following upgrade to Firefox for Android 79.0.5, Firefox ceases audio playback on any of:

- another tab is opened
- FF settings is opened
- switching to another (existing) tab 
- you switch to another app
- the screen is locked

Playback might continue for a few seconds, as if a buffer is emptied.

On returning to the tab, playback usually resumes.

This is a change in behaviour. I have been in the habit of listening to streamed radio with the screen locked. 

This is on a Moto G5 plus, w Android 8.1.0

**Comment by hwinnemoe** [comment] 2020-08-28 15:47
Duplicate of #9691

**Comment by aaggcc** [comment] 2020-08-28 15:51
Don't think it does dup #9691. That mentions loss of data when retruning to the tab; I don't see that here.
Similar, probably related, but not a duplicate.

**Comment by hwinnemoe** [comment] 2020-08-28 15:56
I think data loss is not required to be classified as issue #9691, that was mentioned in a comment but not the initial report. Also, see the other other duped issues and comments.

**Comment by kbrosnan** [comment] 2020-08-28 17:53
This is a duplicate.

**Closed by kbrosnan** 2020-08-28 17:53 UTC
Labels: needs:triage
