### ISSUE TITLE
[Bug][RTL] The Learn More's arrow icon in ETP settings is pointing in the wrong direction

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/fenix#7862] opened 2020-01-22 14:23 UTC
[Originally filed as bug against GeckoView by @itiel](https://bugzilla.mozilla.org/show_bug.cgi?id=1608187). Screenshots attached in Bugzilla for more information.

**Comment by NotWoods** [comment] 2020-01-26 04:44
We should be able to add a flag to the drawable to make it flip for right-to-left layouts.

**Comment by lyrjie** [comment] 2020-01-29 10:59
I'll take it if that's ok

**Comment by sv-sdeiac** [comment] 2020-02-05 08:45
Verified as fixed using the latest version of Firefox Preview Nightly 2/5 @20360606.

Devices:
- Nokia 6 (Android 7.1.1);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel 3 (Android Q).

**Comment by sv-sdeiac** [comment] 2020-02-05 15:55
I'm sorry about the last comment.
The issue is still reproducible using the latest version of Nightly  2/5 @20360606.

**Comment by NotWoods** [comment] 2020-02-05 22:17
Should be fixed now

**Comment by sv-sdeiac** [comment] 2020-02-06 08:26
Verified as fixed using the latest version of Firefox Preview Nightly 2/6 #20370604.

Devices:
- Nokia 6 (Android 7.1.1);
- Motorola Moto G6 (Android 8);
- Google Pixel 3 (Android Q).

**Closed by sv-sdeiac** 2020-02-06 08:26 UTC
Labels: Feature:TrackingProtection, eng:qa:needed, good first issue, help wanted, needs:triage, 🐞 bug
