### ISSUE TITLE
Add "Close tab" button next to address bar or allow page action for extensions

### ISSUE THREAD

**Issue by gwarser** [mozilla-mobile/fenix#16702] opened 2020-11-21 14:03 UTC
Sorry for empty issue - i tapped on enter accidentally - I hope it's fine after my edits.

### What is the user problem or growth opportunity you want to see solved?

I want to have easy access to close tabs

### How do you know that this problem exists today? Why is this important?

I tried to switch to "never close tab" workflow and leave it for browser "close tab after", but it only creates more confusion for me. It's not easy to find the right tab in tabs menu/widget.

It's not easy to close tabs, I need to open tabs menu and here "New tab" (+) button is covering access to tabs. Also after I close one, I see "toast" notification wchich again covers more tabs which makes closing them difficult. I Fennec I was able to use add-on to add small button to address bar ([Close tab button](https://addons.mozilla.org/pl/android/addon/close-tab-button/)) to solve my issue, but it's not implemented correctly now - I see "X" "close tab" button deep in browser menu which makes access to it's feature difficult.

**Comment by ekager** [comment] 2020-12-18 07:27
Closing as dupe of #14203

**Closed by ekager** 2020-12-18 07:27 UTC
Labels: feature request 🌟
