### ISSUE TITLE
[Bug] The media indicator always shown in URL bar

### ISSUE THREAD

**Issue by 0x391F** [mozilla-mobile/fenix#18140] opened 2021-02-24 03:59 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
The media indicator always shown in URL bar, though the website doesn't have any media, for example, GitHub. 
![Screenshot_20210224_115917](https://user-images.githubusercontent.com/56181919/108945542-be503980-7697-11eb-8be1-9a43c9efacf6.jpg)

### Device information

* Device vendor / model and Android version: Huawei honor 20S, Android 10
* Firefox for Android version: 86.1.1

**Comment by mcarare** [comment] 2021-02-24 07:43
@0x391F I cannot see the media indicator in the screenshot you uploaded. Please upload the relevant screenshot!

**Comment by hakkikaancaliskan** [comment] 2021-02-24 07:48
@mcarare i think he/she meant to autoplay indicator

**Comment by mcarare** [comment] 2021-02-24 07:50
> @mcarare i think he/she meant to autoplay indicator

I know, there is no autoplay/media icon in the screenshot.

**Comment by hakkikaancaliskan** [comment] 2021-02-24 07:53
![Screenshot_20210224-105153_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/108965776-62cd7e00-768e-11eb-9a63-b1618dd2de3e.png)

Isn't that blue dot autoplay indicator?

**Comment by mcarare** [comment] 2021-02-24 08:03
Oh, sorry, I kept reading icon instead of indicator (the blue-dot indicator).

@0x391F Can you also provide the link you were on? There are some issues where videos are attached, and that would mean showing the blue-dot indicator.

**Comment by 0x391F** [comment] 2021-02-24 09:09
> Oh, sorry, I kept reading icon instead of indicator (the blue-dot indicator).
> 
> @0x391F Can you also provide the link you were on? There are some issues where videos are attached, and that would mean showing the blue-dot indicator.

This issue:
https://github.com/mozilla-mobile/fenix/issues/18140
![Uploading Screenshot_20210224_170737.jpg…]()

**Comment by hakkikaancaliskan** [comment] 2021-02-24 09:13
It's not shown on this issue with nightly, A11

**Comment by mcarare** [comment] 2021-02-24 10:50
Not seeing this on Nightly / Beta 86 - beta 5 / Beta 86.1.1.

@0x391F can you please upload a print screen with what the app shows if you click on the lock icon?

**Comment by 0x391F** [comment] 2021-02-24 11:33
> Not seeing this on Nightly / Beta 86 - beta 5 / Beta 86.1.1.
> 
> @0x391F can you please upload a print screen with what the app shows if you click on the lock icon?

![Screenshot_20210224_193158](https://user-images.githubusercontent.com/56181919/108994639-00e53680-76d7-11eb-87a7-9f27a7ef43e7.jpg)

**Comment by sheikh-azharuddin** [comment] 2021-02-25 03:43
Not showing in latest nightly on android 10.
![Screenshot_20210225-091211705 (1)](https://user-images.githubusercontent.com/58127841/109099730-928d8c00-7749-11eb-88d6-5313f7788761.jpg)

**Comment by sflorean** [comment] 2021-03-08 16:12
Tested on Huawei P40 Lite (Android 11) and LG G7 (Android 8.1) and couldn't reproduce the issue on both RC and Nightly builds. @0x391F could you check on Nightly, and see if this is reproducible? Thank you!

**Comment by mariansima** [comment] 2021-09-07 12:32
Could not reproduce this issue on Samsung A8 (Android 9) with Firefox Nightly 93.0a1 2021-09-07

**Comment by sflorean** [comment] 2021-09-27 08:33
Closing based on the comments above and the lack of extra information.

**Closed by sflorean** 2021-09-27 08:33 UTC
Labels: 🐞 bug, Feature:Media, qa-triaged
