### ISSUE TITLE
[Bug] Back/history stack does not work on Huawei P8 lite 2017

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14322] opened 2020-08-27 21:37 UTC
From: https://www.reddit.com/r/firefox/comments/ih9vmb/firefox_for_android_fenix_79_release_fennec_is/g30gb12/

## Steps to reproduce

1. Visit some pages
2. Hold Android back button 

### Expected behavior

tab stack appears

### Actual behavior

nothing happens.

### Device information

* Android device: Huawei P8 lite 2017
* Fenix version: beta

**Comment by cadeyrn** [comment] 2020-08-27 21:50
Duplicate of #13498.

**Closed** 2020-08-27 21:55 UTC
Labels: needs:triage, 🐞 bug
