### ISSUE TITLE
[Bug] Fill link from clipboard overlaps search engines

### ISSUE THREAD

**Issue by aL3xa** [mozilla-mobile/fenix#18641] opened 2021-03-25 22:10 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- copy link so that it's in the clipboard
- tap address bar
- tap "Search engines"

### Expected behavior
Should be able to select any of the available search engines.

### Actual behavior
Search engines are overlapped by "Fill link from clipboard" making it impossible to select the one underneath the "Fill link..."

### Device information

* Device vendor / model and Android version: Motorola One Fusion+, Android 10
* Firefox for Android version:  (go to Settings -> About Firefox) 86.1.1 / Nightly 210324

**Comment by mcarare** [comment] 2021-03-25 22:29
"Fill link from clipboard" should be hidden when "Search engine" is tapped.

**Comment by lobontiumira** [comment] 2021-03-31 08:39
Thank you @aL3xa fot the report!
I was not able to reproduce this issue on neither of the Firefox builds (3/31 Nightly, RC 87.0.0, nor Beta 88.0.0-beta.2). Tested with Xiaomi Mi 8 Lite (Android 9), Google Pixel (Android 10), and Samsung Galaxy Note 8 (Android 9).
Could you help us with a short video, please?

**Comment by LaurentiuApahideanSV** [comment] 2021-05-10 10:51
Verified as fixed on Firefox Preview Nightly 90.0a1 (Build #2015809515) 5/10.

### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)

**Closed** 2021-05-10 15:40 UTC
Labels: Feature:Search, eng:qa:verified, good first issue, qa-triaged, 🐞 bug
