### ISSUE TITLE
Deleted history item is displayed on search suggestion

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#25103] opened 2022-05-04 09:04 UTC
### Steps to reproduce

1. Have a few items in history from different web pages.
2. Delete the items from at least 1 web page.
3. Tap on the search icon and begin typing part of the deleted item.
4. Observe the suggestions.

### Expected behaviour

There are no suggestions about the deleted item(s).

### Actual behaviour

Search suggestions are displayed for deleted item(s).

### Device name

Google Pixel 4

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

101.0.0-beta1

### Additional information

https://user-images.githubusercontent.com/48829350/166652059-a2dc6e8b-d891-4d33-82c0-02f1d92bed74.mp4

- Also reproducible on other devices. Example: Samsung Galaxy Tab S3 (Android 9).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20367)

**Comment by Alexandru2909** [comment] 2022-05-05 12:51
I noticed that the sites that were deleted do not correspond to the ones that appear in the search. When the user types the `wikipedia.org` link in the search bar, history records these visits:

<img width="722" alt="Screenshot 2022-05-05 at 15 43 50" src="https://user-images.githubusercontent.com/35462038/166926065-98d0c8f5-047b-4fa5-9155-866001444a91.png">

Because the `https://wikipedia.org/` visit is not shown as a history item, it is not removed when the `LINK` visits are deleted:

https://user-images.githubusercontent.com/35462038/166926697-8f259aa5-800a-40d1-bb32-310cae307bd4.mp4

 This could be the case for the `https://en.wikipedia.org` search results from the original video.

**Comment by amocirean** [comment] 2022-11-24 12:33
This issue is still reproducible on the latest Nightly of 24th of November 2022 (109.0a1). Tested using the following devices: Samsung Galaxy S22 Ultra (Android 13)
Removing the wontfix label.

**Comment by cpeterso** [comment] 2022-12-27 02:46
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807633

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2022-12-27 02:46 UTC
Labels: 🐞 bug, Feature:History, Feature:Search, S3, needs:triage
