### ISSUE TITLE
[Bug] OpenStreetMap Wiki slow rendering

### ISSUE THREAD

**Issue by Wasseranomalie** [mozilla-mobile/fenix#12712] opened 2020-07-19 11:51 UTC
## Steps to reproduce
* Visit https://wiki.openstreetmap.org/w/index.php?title=Austria/Radwege&mobileaction=toggle_view_mobile (mobile page)
* Click onto "Radwege in Wien"
* Scroll

### Expected behavior
Faster rendering times, comparable to Chrome.

### Actual behavior
Long rendering-times for the page. The page is sometimes completely black for several seconds and after that text needs to sharpen additional seconds.

### Device information
* Android device: Nexus 5X (Android 8.1)
* Fenix version: Nightly 200718 06:04 (Build #22000612)
* Renderer: OpenGL

Webrender seems to improve the situation at least a bit, but the page also stays black for several seconds on each large scroll.

Screen recording: [OpenStreetMaps.zip](https://github.com/mozilla-mobile/fenix/files/4943635/OpenStreetMaps.zip)
It may look like the recording got stuck because the clock didn't change anymore after some time, but the recording is still in real time and the clock also kept running on my device during the recording (maybe an optimization technique of the recorder software or my device on it's processing capability limit).

**Comment by yoasif** [comment] 2020-09-03 05:50
Filed a bugzilla - https://bugzilla.mozilla.org/show_bug.cgi?id=1662960

I think this can be closed.

**Comment by yoasif** [comment] 2020-09-14 22:56
Patch was sent upstream: https://phabricator.wikimedia.org/T262859

This is also a dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=1381071

**Comment by ekager** [comment] 2020-12-17 22:36
Closing because there's an issue filed in Bugzilla

**Closed by ekager** 2020-12-17 22:36 UTC
Labels: needs:triage, 🐞 bug
