### ISSUE TITLE
[Bug] "Delete Private Tabs" problem

### ISSUE THREAD

**Issue by kamran-12** [mozilla-mobile/fenix#5293] opened 2019-09-13 07:48 UTC
### Steps to reproduce
Just open one or more private tabs and make sure "Delete Private Tabs" notification appears.

### Expected behavior
When I close the last private tab (leaving no open private tabs) notifications should go away.

### Actual behavior
That notification stays there when no private tabs left. It disappears only if I close Fenix from the open apps list.

### Device information

* Android device: SM-G920F, Android 7.0
* Fenix version: 1.4.1

**Comment by alexandergitter** [comment] 2019-09-13 11:41
Same here. I found a good way to reproduce this issue is the following:
1. Open a private tab
2. Close all private tabs
3. Leave private mode by clicking on the icon in the top right corner
4. While Fenix is still open, pull down the notification drawer and click the Firefox "Delete Private Tabs" notification

- Redmi Note 4, Android 8.1 (LineageOS 15.1)
- Fenix version: 1.4.1

**Comment by cadeyrn** [comment] 2019-09-13 11:47
Duplicate of #5075, already fixed in Fenix Nightly.

**Closed** 2019-09-25 09:32 UTC
Labels: 🐞 bug
