### ISSUE TITLE
[Bug] (regression) "tab closed" snackbar no longer disappears

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#7799] opened 2020-01-18 15:32 UTC
### Steps to reproduce

1. close a tab
2. open another open tab while the "tab closed" snackbar is still visible

### Expected behavior

The snackbar disappears.

### Actual behavior

The snackbar stays visible. Pressing the "undo" link closes the snackbar (but does not execute the "undo" action).

This is a recent regression.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision ffb2e72b97b1d066c040087dca2d2035f7e7e9b0

**Comment by cadeyrn** [comment] 2020-01-18 16:14
@mcomella I bisected the issue. This a regression from the second commit of #7423 (remove unnecessary CoordinatorLayout in fragment_home).

**Comment by djc** [comment] 2020-01-21 14:19
I'm also seeing this.

**Comment by ekager** [comment] 2020-01-21 18:27
@mcomella could we make the root of `activity_home.xml` a coordinator layout instead of a linear layout? This should probably solve this problem without introducing more nested layouts?

**Comment by mcomella** [comment] 2020-01-22 19:50
@ekager Thanks for looping me in. I'm not sure that will work because the fragment container relies on the `LinearLayout` in order to dynamically size it when the Toolbar disappears and `CoordinatorLayout` is roughly a `FrameLayout`, according to the docs.

Is the `CoordinatorLayout` necessary to make snackbars go away? My understanding is that they should be independent over any particular view type. Perhaps it's getting attached to the wrong view?

**Comment by mcomella** [comment] 2020-01-22 19:58
I tried making the anchorView the root container of the activity, rather than `bottom_bar`, but now the Snackbar doesn't appear at all. I wonder if this would work correctly if we attached it to the root container of the home fragment.

Also, we may reintroduce the CoordinatorLayout in #7700 so it's possible this will be fixed with that patch.

**Comment by mcomella** [comment] 2020-01-22 21:17
In the old implementation, the Snackbar would be dismissed when switching between fragments. In the current implementation, the Snackbar remains. I'm not sure why this would be the case.

It's possible the previous `findSuitableParent` algorithm would choose the `CoordinatorLayout` at the top of the fragment view hierarchy but, now that there's no `CoordinatorLayout`, it's selecting the view at the top of the HomeActivity hierarchy, so it's not dismissed when changing fragments. I'm not sure why this would prevent the Snackbar from being hidden altogether.

https://github.com/mozilla-mobile/fenix/blob/e1722b95b3cd3afb5c3d28cd848c505122f782d3/app/src/main/java/org/mozilla/fenix/components/FenixSnackbar.kt#L129

**Comment by mcomella** [comment] 2020-01-22 21:18
> I tried making the anchorView...

I noticed that `anchorView` was for which view to place the Snackbar above, not the view to which the Snackbar is bound.

**Comment by mcomella** [comment] 2020-01-22 21:32
I confirmed the problem is fixed when I make the "suitable parent" of the SnackBar as `R.id.homeLayout`:
```kotlin
            do {
                if (view is ViewGroup && view.id == R.id.homeLayout) {
                    return view
                }

                if (view is CoordinatorLayout) {
                    // ...
```

I'm not sure what the "correct" solution is though.

**Comment by mcomella** [comment] 2020-01-22 21:46
Handing this off to @emalysz, who worked on the original implementation with me.

**Comment by emalysz** [comment] 2020-01-23 19:16
Should be fixed once https://github.com/mozilla-mobile/fenix/pull/7878 lands

**Comment by andreicristianpetcu** [comment] 2020-01-26 14:13
Quick workaround: swipe to delete removes the notification!

![Screenshot_20200126-161308_Firefox_Nightly](https://user-images.githubusercontent.com/922368/73136482-c5e97d00-4056-11ea-98e7-ade0c7680206.png)

**Comment by cadeyrn** [comment] 2020-01-26 14:19
> Quick workaround: swipe to delete removes the notification!

Simply pressing the "undo" button also removes the snackbar (it does not execute the undo action). ;-)

**Comment by sv-ohorvath** [comment] 2020-01-27 13:39
Reproducing on Beta 3.2.0

**Comment by jdrch** [comment] 2020-01-31 23:10
Same issue here.

**Comment by neitsab** [comment] 2020-02-05 08:59
How come stable Fenix (3.2.2) was released with such a visible issue still standing? Right now this affects all current versions of FF Preview (release, beta, nightly). Even the migration APK for Fennec has the bug 😅

**Comment by emalysz** [comment] 2020-02-05 12:49
Waiting for https://github.com/mozilla-mobile/fenix/pull/8085 to land, which fixes this issue.

**Comment by sv-sdeiac** [comment] 2020-02-06 13:34
Verified as fixed on the latest version of Firefox Preview Nightly 2/6 #20370604.

Devices:
- Nokia 6 (Android 7.1.1);
- Samsung Galaxy S8 (Android 9);
- Google Pixel 3 (Android Q).

**Closed by sv-sdeiac** 2020-02-06 13:34 UTC
Labels: Feature:Snackbar, Feature:Tabs, S2, eng:qa:needed, needs:triage, 🐞 bug
