### ISSUE TITLE
[Bug] Crash when trying to log in to google in a private tab [@ android.os.TransactionTooLargeException: at android.os.BinderProxy.transactNative(Native Method) ]

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#16117] opened 2020-10-22 13:27 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- open google.com in a private tab
- try to log in (enter user name, password)

### Expected behavior
 after entering the password, tapping next should log you in to your account

### Actual behavior
- crash https://crash-stats.mozilla.org/report/index/1e4808af-a543-4a2f-8b8d-bb1700201022

### Device information

* Android device: Samsung Galaxy A50
* Fenix version: nightly

**Comment by kbrosnan** [comment] 2020-10-22 16:32
Duplicate of #15995

**Closed by kbrosnan** 2020-10-22 16:32 UTC
Labels: Feature:IME, b:crash, 🐞 bug
