### ISSUE TITLE
FNX-13511 ⁃ [Feature Request]Preview when selecting text

### ISSUE THREAD

**Issue by lomomcat** [mozilla-mobile/fenix#12443] opened 2020-07-10 01:33 UTC
**Now:**
![Screenshot](https://user-images.githubusercontent.com/62339707/87106409-f8e39e00-c28f-11ea-8b41-06f3f76a0b19.jpg)UNITO-UNDERSCORE!2020-07-10-09-22-58-342!UNITO-UNDERSCORE!org.mozilla.fenix.jpg!

**Future like this:**
![IMG](https://user-images.githubusercontent.com/62339707/87106470-19abf380-c290-11ea-902d-04b26e5232cc.jpg)UNITO-UNDERSCORE!20200710!UNITO-UNDERSCORE!093101.jpg!

It is suitable for mobile browsers.

Thanks to engineers!

**Comment by ekager** [comment] 2020-07-10 01:39
Thanks for the request! Closing as a dupe of https://github.com/mozilla-mobile/fenix/issues/3510

**Comment by lomomcat** [comment] 2020-07-10 01:40
> Thanks for the request! Closing as a dupe of https://github.com/mozilla-mobile/fenix/issues/3510

OK, thanks!

**Closed** 2020-08-11 06:31 UTC
Labels: needs:triage
