### ISSUE TITLE
[Bug]: push notification not working latest nighlty 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#22394] opened 2021-11-10 03:13 UTC
### Steps to reproduce

since a couple of days notification for fenix nighlty stopped working, looking at logcat I found several errors :Error executing SQL: no such column: uaid
CommunicationException: Communication Error: "response has no `uaid

### Expected behaviour

push notification MUST work

### Actual behaviour

Fenix is nothing but a disappointment and web push notications are not working. 

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

96

**Comment by Mugurell** [comment] 2021-11-10 14:12
Tried with https://www.bennish.net/web-notifications.html and the notifications seem to work as expected.

@ale82to Can you offer more info about the scenario you're using for us to try and reproduce?

**Comment by sheikh-azharuddin** [comment] 2021-11-12 05:09
For me it's working fine in Android 11..but on clicking the push notification it should ideally take to the webpage but instead takes to the browser homescreen or if browser is already open nothing happens!

**Comment by ale82to** [comment] 2021-11-14 08:35
really disgusted it's 2021 still cannot enable push notification for facebook mobile, logcat shows this error :
11-14 09:38:39.882 W/App     (10565): mozilla.appservices.push.PushException$CommunicationException: Communication Error: "response has no `uaid`"
🤢

**Comment by jonalmeida** [comment] 2021-11-19 21:13
There were changes to push recently that could have affected this. cc @mhammond

**Comment by mhammond** [comment] 2021-11-22 02:44
> 11-14 09:38:39.882 W/App (10565): mozilla.appservices.push.PushException$CommunicationException: Communication Error: "response has no uaid"

I expect that error to start going away in all builds with an "AS" version of 86.2.0 and later.

**Comment by mhammond** [comment] 2021-11-22 07:29
> with an "AS" version of 86.2.0 and later.

Actually, sentry implies this hasn't gone away entirely in that version :(

**Comment by jonalmeida** [comment] 2021-12-01 16:31
Filed https://github.com/mozilla/application-services/issues/4691 because this seems like a perma-failure that is not making it's way to Sentry because we don't log `CommunicationError`.

> Tried with https://www.bennish.net/web-notifications.html and the notifications seem to work as expected.

This test site seems to be showing an example of Web Notification which doesn't test Web Push as well.

**Comment by eliserichards** [comment] 2021-12-03 00:13
[This PR](https://github.com/mozilla-mobile/android-components/pull/11353) should fix this issue. We'll uplift to beta on monday if it looks good over the weekend

**Comment by jonalmeida** [comment] 2021-12-06 16:38
This has been working for me on nightly over the weekend. So I'd be keen to upstream the a-s bump.

**Comment by SoftVision-LorandJanos** [comment] 2021-12-10 13:41
This issue is no longer reproducible on the:
- latest Beta (96.0.0-beta1).
- latest Nightly 97.0a1 (2021-12-10).

Verified with https://cleverpush.com/en/test-notifications/ and the notifications are received as expected.
Device used: Xiaomi Mi11 Lite (Android 11).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2021-12-10 13:41 UTC
Labels: 🐞 bug, eng:qa:needed, Feature:Notifications
