### ISSUE TITLE
[Bug] Sharing a tab that is in reader mode doesn't load in desktop Firefox

### ISSUE THREAD

**Issue by amjd** [mozilla-mobile/fenix#17129] opened 2020-12-18 19:17 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open any website in Fenix and enable reader mode. 
2. Share tab with desktop Firefox through Share button.
3. The tab appears in desktop Firefox but doesn't load. I believe that's because the URL for reader mode is different in mobile and desktop Firefox.

### Expected behavior
The tabs that are in reader mode should be loaded in desktop Firefox, and preferably in reader mode.

### Actual behavior
The tabs that are in reader mode don't load and have a URL like this:
```
moz-extension://d7e444f5-d44b-4937-b273-cbe3687d5800/readerview.html?url=https%3A%2F%2Fgadgets.ndtv.com%2Fmobiles%2Fnews%2Flg-rollable-slide-price-usd-2359-leak-expected-launch-june-2021-tipster-2340487%3Famp%3D1%26akamai-rum%3Doff&id=274877907133
```

When I manually change it to the following, it loads fine:
```
about:reader?url=https%3A%2F%2Fgadgets.ndtv.com%2Fmobiles%2Fnews%2Flg-rollable-slide-price-usd-2359-leak-expected-launch-june-2021-tipster-2340487%3Famp%3D1%26akamai-rum%3Doff&id=274877907133
```

### Device information

* Android device: LG G8X Thinq
* Fenix version: 83.1.0 (Build #2015776403)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9165)

**Comment by jonalmeida** [comment] 2020-12-21 19:59
I believe this is a duplicate of https://github.com/mozilla-mobile/fenix/issues/5190.

cc: @csadilek

**Comment by csadilek** [comment] 2020-12-21 21:01
@jonalmeida yeah, but it depends. For bookmarks and also the Share fragment we decided to use the original article URL instead which makes sense and we could do this here as well.

If we want to share a reader URL directly to desktop then yes we need solve #5190 somehow.

**Comment by amjd** [comment] 2021-06-20 08:06
Can someone take a look again and evaluate whether this issue needs to be picked up? Automatically marking inactive issues as stale can result in genuine issues being ignored.

**Comment by jonalmeida** [comment] 2023-01-17 02:09
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810635

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by jonalmeida** 2023-01-17 02:09 UTC
Labels: 🐞 bug, Feature:ReaderMode, Feature:SendTab, pin
