### ISSUE TITLE
[Bug] Task not removed after open in Firefox button pressed

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#16435] opened 2020-11-06 18:39 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open a link in custom tab (I've opened in telegram x) 
Press open in Firefox button
### Expected behavior
Tab opened in Firefox and custom tab task is removed from Android recents screen
### Actual behavior
Task not removed from Android recents screen

![Screenshot_20201106-212441_Trebuchet](https://user-images.githubusercontent.com/17825767/98401965-918bfe00-2077-11eb-9708-8f61d5474846.png)

### Device information

* Android device: Xperia XZ1 
* Fenix version: 05/11 Nightly
 
Also there was a related(?) issue/crash that @pocmo fixed via `finishAndRemoveTask()`: #14225
No crash on this issue, when I try to open this task, it throws me back to homescreen.

**Comment by pocmo** [comment] 2020-11-30 14:28
I can reproduce this with Telegram. I wonder how this came back. As mentioned above this is similar to #14225 and was fixed. It's possible to get it into a similar state as #14225 and crash with "display already acquired".

**Comment by pocmo** [comment] 2020-11-30 15:54
This is a slightly different case, where we go through `DefaultBrowserToolbarMenuController` and call `finish()`. This keeps the extra task around and it looks like `finishAndRemoveTask()` is not an option here. 🤔

**Comment by pocmo** [comment] 2020-12-01 09:31
Patch landed yesterday and should be available in the next Nightly build.

**Closed by pocmo** 2020-12-01 09:31 UTC
Labels: Feature:AndroidIntegration, Feature:CustomTabs, 🐞 bug

**Comment by hakkikaancaliskan** [comment] 2020-12-01 09:51
@pocmo I've downloaded from TC and looks like issue fixed :) Thanks 🎉
