### ISSUE TITLE
IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView(...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#3818] opened 2019-07-01 10:41 UTC
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/5990843/

```
IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
    at org.mozilla.fenix.home.HomeFragment$onCreateView$listener$1.onPreDraw(HomeFragment.kt:1)
...
(13 additional frame(s) were not displayed)

Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
```

**Comment by colintheshots** [comment] 2019-07-02 20:30
Fixed by https://github.com/mozilla-mobile/fenix/pull/3786

**Comment by colintheshots** [comment] 2019-07-08 22:00
The issue wasn't resolved the PR in question. I meant to tag a similar crash issue. I have another PR in flight to fix this one.

**Comment by colintheshots** [comment] 2019-07-16 20:15
This crash hasn't happened since July 7th in nightly. This appear to be fixed. There are no steps to reproduce for QA. Closing.

https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/5991152/?query=is:unresolved

**Closed by colintheshots** 2019-07-16 20:15 UTC
Labels: b:crash, 🐞 bug
