### ISSUE TITLE
Add "Send tab" as a discrete "share" target.

### ISSUE THREAD

**Issue by eyaler** [mozilla-mobile/fenix#23693] opened 2022-02-11 16:00 UTC
This is regarding streamlining of the share experience. my main use case for tab syncing is when i see an interesting link on some social app and i want to send it to a tab on my computer. i would like to use firefox send tab option in a quicker way. similar to the way that apps as facebook offer several sharing options (to profile, to group, in chat), i suggest allowing more options for sharing to firefox, and instead if share to firefox + send tab, to offer in advance the option to share to remote firefox tab, or at least bring me to this menu. additionally there is some friction due to (a) the opened url takes time to load and in the meantime i am never sure if it will share the new link that is not loaded yet (b) the share menu can take a long time (>10 seconds) until the sync tab options are shown although i am logged in to sync. (c) in my use cases many of the shared links e.g (youtube, twitter, facebook) are defined in FF to automatically open in their respective apps. so if you do "open in browser" you have to be quick to get to the share menu before you are transferred to the app. having a direct option to open to the share menu can allow you to complete share action and perhaps also avoid the unwanted app opening.

**Comment by kbrosnan** [comment] 2022-02-11 18:52
Duplicate of https://github.com/mozilla-mobile/fenix/issues/1523

**Closed by kbrosnan** 2022-02-11 18:52 UTC
Labels: needs:triage
