### ISSUE TITLE
Bypassing In-app Browser

### ISSUE THREAD

**Issue by NovaTangerine** [mozilla-mobile/fenix#3681] opened 2019-06-26 12:15 UTC
## Steps to reproduce
1. Made Fenix default browser
2. Open link from Twitter timeline. Link opened in Fenix app rather than Twitter in-app browser.
3. Switched default browser back to Chrome. Twitter in-app browser now works properly again, but is Fenix-themed (i.e. Has the Fenix loading bar and the option to open the page in Fenix, etc.)

This ONLY happens on Twitter for some reason. Other apps' in-app browsers work fine with Fenix.

### Expected behavior
When set as the default browser, the Fenix should still open the in-app browser when clicking a link in an app that has the in-app browser enabled.

### Actual behavior
When set as the defuult browser, Fenix opens Twitter links in the external app instead of the in-app browser.

### Device information

* Android device: OnePlus 6
* Fenix version: 1.0.1926 Build #11770619

**Comment by ekager** [comment] 2019-06-26 16:34
It's not an in app browser being bypassed, it's using your phone's default browser's custom tabs. And currently Twitter doesn't support us using custom tabs, but we've reached out to the team there to try to fix this. Dupe of https://github.com/mozilla-mobile/fenix/issues/1503

**Closed by ekager** 2019-06-26 16:34 UTC
Labels: 🐞 bug
