### ISSUE TITLE
feature request: ascending/descending tab list option

### ISSUE THREAD

**Issue by isthisrubble** [mozilla-mobile/fenix#17110] opened 2020-12-18 06:50 UTC
### What is the user problem or growth opportunity you want to see solved?

The most recent update switched the open tabs list from newest at the top to newest at the bottom. Some users will prefer the original sorting system and be annoyed by this change. Giving the users the ability to pick which direction their tab list runs would prevent user frustration and confusion.

### How do you know that this problem exists today? Why is this important?

I know it exists today because my app just updated and I thought initially that my most recent tabs had been closed because I couldn't find them.

It's important because for many users this new sorting system will feel counterintuitive (history, for example, has the most recent page at the top, not the bottom), and it's nice to give people control over their user experience.

(as it is, it seems like the behaviour of the app was changed for no reason and I for one don't understand why this was forced on everyone instead of adding a new sorting _option_)

### Who will benefit from it?

people who liked the old way of sorting, people who like to have options.

**Comment by ekager** [comment] 2020-12-18 07:09
Dupe of https://github.com/mozilla-mobile/fenix/issues/16884

**Closed by ekager** 2020-12-18 07:09 UTC
Labels: needs:triage

**Comment by isthisrubble** [comment] 2020-12-18 08:32
@ekager they're talking about grid view in that one, I think?

**Comment by ekager** [comment] 2020-12-18 17:35
I think it's general, but also see https://github.com/mozilla-mobile/fenix/issues/11376
