### ISSUE TITLE
[Bug] Add / edit bookmarks: Incorrect browser function performed at times

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#20242] opened 2021-07-04 14:09 UTC
Press the star button

### Expected behavior
The current website is added as a bookmark or the bookmark editing dialog is opened.

### Actual behavior
However, the list of existing bookmarks / folders is temporarily opened instead.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16959)

**Comment by WebworkrNet** [comment] 2021-07-04 14:13
### Device information

* Samsung Galaxy XCover 4s
* Android 10
* Firefox Daylight for Android version: 89.1.1 (Build #2015812947)
AC: 75.0.22, 5204f4025
GV: 89.0-20210527174632
AS: 74.0.1

**Comment by WebworkrNet** [comment] 2021-07-04 14:24
The error occurs in both portrait and landscape format.

I think an unconscious operating error, i.e. tapping the wrong button to the left, is rather unlikely.

In my opinion, damage to the display can also be ruled out.

**Comment by WebworkrNet** [comment] 2021-07-04 14:30
![20210704_162616](https://user-images.githubusercontent.com/43509007/124388893-23bad380-dce5-11eb-8981-032346d05e76.jpg)

**Comment by WebworkrNet** [comment] 2021-07-04 14:35
![20210704_163357](https://user-images.githubusercontent.com/43509007/124389063-d4c16e00-dce5-11eb-94de-e021b7dba470.jpg)

**Comment by Nickoriginal** [comment] 2021-07-04 16:58
Not reproducible on:
**Samsung Galaxy A20s** (Android 10)
**Samsung Galaxy J2 Prime** (Android 6.0.1)
**Firefox 89.1.1**

https://user-images.githubusercontent.com/85299944/124393094-7bffce80-dd01-11eb-8d1a-033414562007.mp4
> However, the list of existing bookmarks / folders is temporarily opened instead.

It cannot be opened temporarily? In my Firefox it leaves until closed manually.

**Comment by SoftVision-LorandJanos** [comment] 2021-07-05 12:37
Hi @WebworkrNet ! Thanks for the report! I couldn't reproduce this issue either. I've tried both on the latest release you've tested on and the latest Nightly (91.0a1 - 2021-07-05T05:06:51.686), and the adding/editing flow was without any issue. Could you please make a video about it? And maybe try it on the latest Nightly, if it reproduces. Thank you!
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0)

**Comment by rdragonrydr** [comment] 2021-07-09 01:16
I have seen this myself in the following Android version (and just checked it again to be sure):
*    Android 8.1.0 on a RCA Voyager 7 tablet, model RCT6873W42BMF8
*    Firefox Daylight 89.1.1 Build no.2015812945; AC 75.0.22, 5204f4025; GV 89.0-202010527174632; AS 74.0.1; Friday 5/28 @ 2:05 AM (I have no idea what most of this means, so if I included something personally identifying, please warn me).

You have to tap slightly off-center vertically on the add/edit button. The actual hitbox for that button does not extend the full vertical height of the row, while the bookmark browser button does. I imagine that the buttons are nested rather than side-by-side.

**Comment by WebworkrNet** [comment] 2021-09-30 19:28
> > However, the list of existing bookmarks / folders is temporarily opened instead.
> 
> It cannot be opened temporarily? In my Firefox it remains after opening until manually closed.

@ncalexan it was meant in the sense as @rdragonrydr it has described.

**Comment by WebworkrNet** [comment] 2021-09-30 19:33
> > However, the list of existing bookmarks / folders is temporarily opened instead.
> 
> It cannot be opened temporarily? In my Firefox it remains after opening until manually closed.

@ncalexan it was meant in the sense as @rdragonrydr it has described.

**Comment by WebworkrNet** [comment] 2021-09-30 19:36
@SoftVision-LorandJanos, I will try to reproduce the error in the current Nightly in a video. However, since the phenomenon does not occur regularly, i.e. only temporarily, I cannot promise whether I will succeed with the video.

**Comment by rdragonrydr** [comment] 2021-09-30 19:52
I think the hitbox might be weird horizontally too? Tapping too far left (over/near the star on what _should_ be the save/edit button) will _also_ open the bookmarks menu rather than the save/edit dialog.

In my case, once the bookmarks menu appears, I have to manually close it (but I didn't want it open in the first place), rather than it only opening temporarily. I'll repeat; this is not a misclick, or at least it shouldn't have been. Rather, the button is smaller than it physically appears.
Should I open that as a separate issue?

**Comment by WebworkrNet** [comment] 2021-09-30 20:35
Once again to clarify: With temporary was meant that the error sometimes occurs and sometimes not.

**Comment by WebworkrNet** [comment] 2021-09-30 20:38
@rdragonrydr I think we are talking about one and the same problem. We do not need another ticket in my opinion.

**Comment by WebworkrNet** [comment] 2021-09-30 21:11
@SoftVision-LorandJanos, since the finger tap itself is not recorded, a video probably doesn't make much sense in my eyes. I would have to put my smartphone into developer mode first, which I have avoided so far.

I think @rdragonrydr is on the right track.

**Comment by bigConifer** [comment] 2022-04-04 14:34
There is issue #24560 with additional information on this bug.
So this issue can be closed as duplicate.

**Comment by SoftVision-LorandJanos** [comment] 2022-11-14 06:20
Hi @WebworkrNet!
Could you still reproduce the issue?
I still wasn't able to reproduce it using the latest builds.

**Comment by WebworkrNet** [comment] 2022-11-14 08:55
**Device**: Samsung Galaxy A13 5G (SM-A136B/DSN)
**Operating System**: Android 12

Firefox Nightly
108.0a1 (Build #2015915689), 9113bdb51+
AC: 108.0.20221113143151, fd674c3b35
GV: 108.0a1-20221112215806
AS: 95.0.1

Bug still occurs.

**Comment by rdragonrydr** [comment] 2022-11-14 14:24
I regularly have this on my RCA Voyager 7 tablet as well, still.
The button isn't very wide (meaning that presses to the left and right due to size relative to finger will perform the wrong action) and there's also a space above and below it where pressing will open the bookmark menu rather than saving the bookmark.

As you can see in the image (apparently screenshot is _not_ working, so I had to use my phone to take a picture of my tablet...), the "add" button exists as a tiny hitbox completely surrounded by the "bookmarks" drawer. Pressing anywhere in that drawer will open the bookmarks menu, while only pressing the word "add" will actually save it. As you can see, it is surrounded on all sides by a moat of "open bookmarks" that I keep pressing by accident!

![20221114_091916](https://user-images.githubusercontent.com/19354077/201683841-6e7a3363-2fa8-4a5e-8442-1e1585b28604.png)

**Comment by bigConifer** [comment] 2022-11-18 17:08
@SoftVision-LorandJanos
Again, this issue can be closed as duplicate.
> There is issue https://github.com/mozilla-mobile/fenix/issues/24560 with additional information on this bug.

Moreover please follow the bugzilla ticket https://bugzilla.mozilla.org/show_bug.cgi?id=1795115 (migrated from https://github.com/mozilla-mobile/android-components/issues/11958)

**Comment by csadilek** [comment] 2023-01-24 22:20
Closing in favour of #24560.

**Closed by csadilek** 2023-01-24 22:20 UTC
Labels: 🐞 bug, Feature:Bookmarks, needs:triage, qa-triaged
