### ISSUE TITLE
Crash in [@ core::option::expect_failed | webrender_api::resources::ApiResources::update_blob_image] on opening moz-extension page of uninstalled addon

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13904] opened 2020-08-18 18:43 UTC
## Steps to reproduce
Open a moz extension page from an addon
Uninstall the addon that opened the page
Return to the page

### Expected behavior
Nothing, just show a page not found error or about blank

### Actual behavior
```
Crash
e4de63a3-dfa0-4e65-b1db-a8fdf554cb02
<native crash>
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-c35623e9-ce42-41e3-80a7-b45db0200818
----
<native crash>
```

### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by s-ankur** [comment] 2020-08-18 19:04
Ok found a reliable str for this:
On a web page, goto Addons manager and install privacy badger and decentraleyes
Then uninstall decentraleyes and press back to return to browsing
Firefox immediately crashes

**Comment by kbrosnan** [comment] 2020-08-18 20:23
Closing as a duplicate of https://github.com/mozilla-mobile/android-components/issues/7393

**Closed by kbrosnan** 2020-08-18 20:23 UTC
Labels: needs:triage, 🐞 bug
