### ISSUE TITLE
Can't save main image on Google image search

### ISSUE THREAD

**Issue by abigail-makolo** [mozilla-mobile/fenix#9484] opened 2020-03-28 20:21 UTC
## Steps to reproduce

- Launch the Firefox Preview app
- Search for anything on Google e.g. 'Mozilla Firefox'
- Tap the Images tab on the Google Search results page
- Tap on any single image to open it up in a larger view
- Long-press the image in an attempt to trigger a menu which will allow you to save the image.

### Expected behavior

- A context menu should appear with an option to save the image

### Actual behavior

- Context menu fails to appear, so the image cannot be saved as illustrated below:

![image](https://user-images.githubusercontent.com/57357223/77832688-1f922480-7138-11ea-9760-45ff9db6909b.png)

### Other information

- This was tested using a different search engine (Bing) on Fenix and the main image could be downloaded as expected.
- This was also tested using a different browser (Google Chrome) and downloading the main images off Bing and Google search engines worked as expected.
- This issue is one of those found in [this UX review (see attached document in issue)](https://github.com/mozilla-mobile/outreachy-UX-2020/issues/2) conducted on the app.

### Device information

* Android device: Samsung A20
* Fenix version: Firefox Mobile 73.0

**Comment by Diana-Rus** [comment] 2020-04-13 12:32
Hi, I also reproduce the issue with Samsung Galaxy S9 (Android 8) Sony Xperia Z5 (Android 7) and Google Pixel 3 XL (Android 9) using a Nightly debug build 39.0.20200412130044,d433836f0 GV: 77.0a1-20200410095419 AS: 0.55.0.

**Comment by Amejia481** [comment] 2020-04-20 17:58
Duplicate of https://github.com/mozilla-mobile/fenix/issues/10020

**Comment by Amejia481** [comment] 2020-04-22 20:42
Sorry closing, this issue is related to the contextual menu not showing when the large image is long pressed

**Comment by Amejia481** [comment] 2020-04-22 21:00
It looks like this is GeckoView bug, I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1632299 for investigating.

**Comment by Amejia481** [comment] 2020-04-27 14:22
From the Bugzilla bug:

> The Google Image result page serves GeckoView a page where the top "image" is not accessible by long-pressing.
> Changing the user agent to Chrome solves this issue.

**Closed** 2021-02-11 21:32 UTC
Labels: Feature:ContextMenu, Feature:Download, S2, b:webcompat, wontfix, 🐞 bug, 🙅 waiting
