### ISSUE TITLE
FNX-4618 ⁃ [Bug] Open links in apps does not open links in apps

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#10838] opened 2020-05-21 21:38 UTC
## Steps to reproduce
With "Open links in apps" toggled to on

* Search for Youtube in Google
* Select the link for YouTube

### Expected behavior
YouTube App opens

### Actual behavior
YouTube page opens

### Device information
* Android device: Moto E5, Android 8
* Fenix version: Nightly 200519 06:00 (Build #21400606)

**Comment by ImranR98** [comment] 2020-05-22 00:52
This is also a problem for my banking app (CIBC in Canada). When someone sends me money, the link in my email takes me to a webpage with an 'open in app' button. Clicking this button should open the bank app, but doesn't. Works fine in the regular Firefox app.

**Comment by SS1113** [comment] 2020-05-22 02:33
Duplicate of #9923.

**Comment by agreenbhm** [comment] 2020-06-14 13:50
For me, this is also happening with the official Wikipedia app and the Reddit app "Relay for Reddit". If I choose the option "open in app" when already on the page it will open with the correct app at that point. Also, Amazon does not open in the app, but also does not show "open in app" in the menu, so I can't manually switch it either.

**Comment by SS1113** [comment] 2020-06-15 09:19
@vesta0 @ekager I also reported this #10436 bug it was closed and marked as duplicate in favour of #9923. Is the bug that I reported defferent than this or am I not understand this clearly?

**Comment by kbrosnan** [comment] 2020-06-16 17:28
In my investigation of #10838 this looks to be an issue with Google search links. I suspect that whatever they do for redirection breaks the open in app feature.

## Steps to reproduce
* Enable open in app in the settings
* Search for `maangchi youtube` on Firefox (or whatever Youtube content you want) using Google
* Click on Google search link to a Youtube video 
* Tab opens to play video

### Expected behavior
Content opens in Youtube app

### Actual behavior
Content opens in Firefox tab

### Workaround
* Request desktop site allows the Google page to open in app
* DuckDuckGo mobile search allows open in app to work

**Comment by rocketsroger** [comment] 2020-06-17 14:40
> This is also a problem for my banking app (CIBC in Canada). When someone sends me money, the link in my email takes me to a webpage with an 'open in app' button. Clicking this button should open the bank app, but doesn't. Works fine in the regular Firefox app.

@ImranR98 your issue seems like its different from this.  We recently had a new fix from GeckoView and it was meant to fix issues related to yours.  Can you please check with the latest nightly to see if your issue has been resolved?  Thanks,

**Comment by rocketsroger** [comment] 2020-06-17 16:14
Confirmed that the YouTube issue from google search is due to how google redirect its search before loading the YouTube URL.  Currently app links does not automatically open links in an external app if the link was loaded due to a redirect.  This is to prevent sites from opening an external app without user's gesture.  The fix is to open links in external apps even with redirect.  This is a requirement discussion.

**Comment by rocketsroger** [comment] 2020-06-17 16:15
@vesta0 Should we assume that the user wants any links to be opened in external apps even if the link is open due to a redirect?

**Comment by vesta0** [comment] 2020-06-25 02:46
@rocketsroger yes that should be the expected behaviour for when "open in app" it toggled on.

**Comment by rocketsroger** [comment] 2020-06-25 14:24
> @rocketsroger yes that should be the expected behaviour for when "open in app" it toggled on.

Understood.  I'll make the changes.  Thanks,

**Comment by SS1113** [comment] 2020-06-27 15:06
I can still reproduce the issue #10436 on the latest **`Nightly 200627 06:01`** on **Motorola One Power, Android 10**.

**QA** if you're testing this then please test the mentioned issue as well since this bug and the mentioned one are same issues.

**Comment by rocketsroger** [comment] 2020-06-27 17:15
> I can still reproduce the issue #10436 on the latest **`Nightly 200627 06:01`** on **Motorola One Power, Android 10**.
> 
> **QA** if you're testing this then please test the mentioned issue as well since this bug and the mentioned one are same issues.

The fix was merged last night.  Once A-C version is updated next week this issue should be fixed.  Thanks,

**Comment by SS1113** [comment] 2020-06-28 09:48
@rocketsroger this works perfectly on all apps I have tested on **`Nightly 200628 06:01`** but I have found some websites where it doesn't redirect to the  Play Store.

1. https://www.androidpolice.com/2020/06/27/the-best-free-and-open-source-alternatives-to-gmail-on-android/ 

On the above site there're 2 links where they redirect to FairMail and K-9 Mail. Click on them and see it doesn't redirect to the Play Store app but instead opens the Play Store website. On Chrome browser it redirects to the Play Store on clicking those links.

 2. https://www.apkmirror.com/apk/mozilla/firefox-preview-nightly-for-developers/firefox-preview-nightly-for-developers-nightly-200505-0600-release/

Here click on the Play Store icon and see it doesn't redirect to the Play Store and instead redirects to the Play Store website. On Chrome browser it opens the Play Store app

**Comment by rocketsroger** [comment] 2020-06-29 14:11
Fenix nightly with A-C "48.0.20200628130058" this should be fixed

**Comment by rocketsroger** [comment] 2020-06-29 14:13
> @rocketsroger this works perfectly on all websites I have tested, on **`Nightly 200628 06:01`** but I have found some websites where it doesn't redirect to the Play Store

Do you mind opening a new issue?  I'll have to investigate, since play store redirect is different than this issue.  Thanks!

**Comment by SS1113** [comment] 2020-06-29 14:19
> > @rocketsroger this works perfectly on all websites I have tested, on **`Nightly 200628 06:01`** but I have found some websites where it doesn't redirect to the Play Store
> 
> Do you mind opening a new issue? I'll have to investigate, since play store redirect is different than this issue. Thanks!

Yes, I'll create a new issue for it. And let you know in a moment when I have done so.

**Comment by SS1113** [comment] 2020-06-29 14:30
@rocketsroger  Here's the issue for Play Store links #12092.

**Comment by rocketsroger** [comment] 2020-06-29 14:46
> @rocketsroger Here's the issue for Play Store links #12092.

Thanks!

**Comment by sv-ohorvath** [comment] 2020-06-30 11:59
I have verified the STR from the description and the comment below, both issues are fixed on Beta 79.0.1. Closing.

> > I can still reproduce the issue #10436 on the latest **`Nightly 200627 06:01`** on **Motorola One Power, Android 10**.
> > **QA** if you're testing this then please test the mentioned issue as well since this bug and the mentioned one are same issues.
> 
> The fix was merged last night. Once A-C version is updated next week this issue should be fixed. Thanks,

**Comment by rocketsroger** [comment] 2020-07-10 16:33
I have made changes to prevent some bad redirect cases.  Google search result directly to external apps (Facebook, Twitter, Youtube etc) will stop working.  The user have to use the menu to open the page in app after it is loaded.  https://github.com/mozilla-mobile/android-components/issues/7637.

**Closed** 2020-08-10 22:06 UTC
Labels: E3, Feature:OpenInApp, eng:qa:verified, needs:ac, 🐞 bug

**Comment by ncodee** [comment] 2021-06-01 21:21
Having the same issue with Firefox v89 on Android.

**Comment by rocketsroger** [comment] 2021-06-01 21:24
> Having the same issue with Firefox v89 on Android.

@ncodee there's a lot of different possibilities with this issue. Can you please open an issue with how to reproduce it? Please let me know once you opened it and I'll investigate.  Thanks,

**Comment by vrindavan** [comment] 2021-06-20 00:55
I have it turned off, but still it opens all links in apps. I don't want that.

**Comment by OlegAlekos** [comment] 2021-06-24 12:46
App-links are not working in any version i have tried!!!
I see a lot of "closed" bugs, but unfortunatly it is the only Mobile android Browser that is also mainstream that doesn't Respect the App-Link( with digital asset on Server) That OPENS THE APP!!!!!
Please fix. It is dragging down the android experience. 

Thank you!

**Comment by rocketsroger** [comment] 2021-06-24 15:06
> I have it turned off, but still it opens all links in apps. I don't want that.

Please let me know how to reproduce this.  Currently our implementation is that if the browser cannot show the intent directly it finds an app to open it.  However, if you let me know the exact use case I can do some more investigation.  Thanks,

**Comment by rocketsroger** [comment] 2021-06-24 15:08
> App-links are not working in any version i have tried!!!
> I see a lot of "closed" bugs, but unfortunatly it is the only Mobile android Browser that is also mainstream that doesn't Respect the App-Link( with digital asset on Server) That OPENS THE APP!!!!!
> Please fix. It is dragging down the android experience.
> 
> Thank you!

@OlegAlekos I want to help and improve your experience with our browser.  Please open an issue and let me know.  I will investigate and try to make your experience better.  Thanks for letting us know.

**Comment by orchidalloy** [comment] 2021-08-30 20:51
This still happens with Reddit links on google searches for the app "RIF for Reddit". Once in the site it prompts you to open in app, and that button does work correctly.

**Comment by pic2022** [comment] 2022-01-21 15:06
This STILL doesn't work. What are you guys doing?

**Comment by rocketsroger** [comment] 2022-01-21 15:13
> This STILL doesn't work. What are you guys doing?

@pic2022 please let me know how to reproduce this problem.  When you say it doesn't work, what site were you on and what app did you expect it to open?  Thanks

**Comment by nebiont** [comment] 2022-02-10 04:05
> @pic2022 please let me know how to reproduce this problem. When you say it doesn't work, what site were you on and what app did you expect it to open? Thanks

For me it happens when clicking a URL in an external app. For example: 

- Search for something using the google search app
- Click on one of the returned URLs
- URL opens in Firefox
- Need to open menu and click 'Open in App' in order for it to open in the app. 
- If I do the same search from the URL bar in Firefox, and then click one of the returned URLs it will properly open the app.

Here is another example that just happened to me:

- Had an amazon URL sent to me via Facebook Messenger
- Clicked on the URL in Facebook Messenger
- Page opened in Firefox
- Had to open the menu and click 'Open in App' in order for it to open in the Amazon app.

**Comment by rocketsroger** [comment] 2022-02-10 19:23
> 

I see.  Looks like your issue is with opening a URL in Firefox that can already be opened with the app.  Currently when Firefox Android first load a URL we don't redirect automatically to the app.  The thought was that since the user is loading the URL, opening the app is probably not what the user want.  I can look into this and see if we should auto open 3rd party app if the URL is coming from another app.  thanks

**Comment by pic2022** [comment] 2022-02-10 20:08
> > > @pic2022 please let me know how to reproduce this problem. When you say it doesn't work, what site were you on and what app did you expect it to open? Thanks
> > 
> > 
> > For me it happens when clicking a URL in an external app. For example:
> > ```
> > * Search for something using the google search app
> > 
> > * Click on one of the returned URLs
> > 
> > * URL opens in Firefox
> > 
> > * Need to open menu and click 'Open in App' in order for it to open in the app.
> > 
> > * If I do the same search from the URL bar in Firefox, and then click one of the returned URLs it will properly open the app.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here is another example that just happened to me:
> > ```
> > * Had an amazon URL sent to me via Facebook Messenger
> > 
> > * Clicked on the URL in Facebook Messenger
> > 
> > * Page opened in Firefox
> > 
> > * Had to open the menu and click 'Open in App' in order for it to open in the Amazon app.
> > ```
> 
> I see. Looks like your issue is with opening a URL in Firefox that can already be opened with the app. Currently when Firefox Android first load a URL we don't redirect automatically to the app. The thought was that since the user is loading the URL, opening the app is probably not what the user want. I can look into this and see if we should auto open 3rd party app if the URL is coming from another app. thanks

Yeah sorry it took me a while to get to this.
Exactly what @nebiont is experiencing. Another example, in the Google (app) search bar on Android, not in Firefox. 

I search "pokemon - reddit"

I see the results. 


I click on one of them, it opens up Firefox when I have a reddit app installed. Why not just open directly to that app?

If you can make this an option, that'd be amazing.

**Comment by rocketsroger** [comment] 2022-02-10 20:57
> If you can make this an option, that'd be amazing.

Sounds good, I've created an issue to track this.  Once I have a chance I'll look for a solution.  Thanks https://github.com/mozilla-mobile/fenix/issues/23681
