### ISSUE TITLE
[Bug] "Set as default browser" toggle always disabled

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#14073] opened 2020-08-22 14:58 UTC
## Steps to reproduce
Set Fenix as the default browser.
### Expected behavior
The toggle should turn on.
### Actual behavior
Regardless of whether Fenix is the default browser or not, the toggle always stays off.

---
If the menu entry has no other purpose except to open the OS "Default apps" menu, then maybe the toggle should be removed?

Another alternative is that the menu entry should only appear if Fenix is _not_ the default browser, and disappear if it is.
### Device information

* Device: Xiaomi Mi 5 (LineageOS 16)
* Fenix version: Nightly 200822 06:01 (Build #2015759411)

**Comment by abodea** [comment] 2020-10-20 12:03
I was not able to reproduce this on the latest **Nightly** from **10/20** with **Google Pixel 4 XL (11).**
@opusforlife2 can you please check if is still reproducible for you?

**Comment by opusforlife2** [comment] 2020-10-20 20:48
@abodea Yes. I've tried switching the default to another browser and back. The toggle stays off. I thought this might be an LOS 16 bug, but s-ankur doesn't have it on the same OS.

**Comment by ekager** [comment] 2020-10-20 21:01
Just checking - do you have multiple versions of Fenix installed?

**Comment by opusforlife2** [comment] 2020-10-20 21:10
Fenix, and Fennec Beta (68). Does that count?

**Comment by amedyne** [comment] 2021-02-15 15:52
I am not able to reproduce this on Firefox 85.1.3. @opusforlife2 please re-open if you still have this issue.

**Comment by opusforlife2** [comment] 2021-02-19 17:35
@amedyne Yeah, I do. But I can't reopen it, only a Fenix team member can.

**Comment by opusforlife2** [comment] 2021-02-19 18:05
By the way, Fennec Beta is gone. Only Fenix Nightly remains. Issue still present.

**Comment by amedyne** [comment] 2021-02-19 18:18
Thank you for rechecking this @opusforlife2. By the way, aside from Firefox do you have Firefox Beta and Firefox release installed on the same phone?

**Comment by opusforlife2** [comment] 2021-02-19 18:21
Oof. I just commented this above, mate. Only Nightly. Nothing else.

**Comment by sflorean** [comment] 2021-03-31 13:12
Issue #6347 is filed for this issue, and your scenario/device will be checked when will be fixed. Thank you for report! 
Closing as duplicate.

**Closed by sflorean** 2021-03-31 13:12 UTC
Labels: Feature:Settings, 🐞 bug
