### ISSUE TITLE
direct access to the bookmarks

### ISSUE THREAD

**Issue by franco27** [mozilla-mobile/fenix#3532] opened 2019-06-18 14:39 UTC
URL: None

Browser / Version: fenix 1.0.1924 (Build #11660624 :lizard: 68.0-20190611143747)
Operating System: Android 7.0
Tested Another Browser: Yes

Hello

I would like direct access to the bookmarks.
Each time, we have to make 3 clicks to go there:

1. click on the menu
1. click on "your library".
1. click on "bookmarks".
1. and 4th click to select the bookmark.
The possibility of pinning websites on the "new tab" page would be appreciated.
(a Speeddial)

Because on the home page or tab window, it is already occupied by the open tabs or collection and the search bar.

Thank you in advance for considering this feature.
Several clicks before being in the bookmarks is not practical.

**Comment by kbrosnan** [comment] 2019-06-18 21:06
Duplicate of #1487

**Closed** 2020-08-27 00:20 UTC
Labels: Feature:Bookmarks, feature request 🌟

**Comment by anewuser** [comment] 2020-08-27 18:29
People subscribed to this might want to follow #12065 instead.
