### ISSUE TITLE
FNX-4861 ⁃ Add Telemetry for presence of other Mozilla products

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#1192] opened 2019-03-26 17:20 UTC
@bbinto updated on March 27, 2019

#### Description & Product Manager / Data Scienties User Story
* We want to know if and what other Mozilla products the user has installed. It will help us to understand usage, improve on cross-linking products and services. 

#### Hypothesis
* By knowing what Mozilla apps the user has installed, we can help them explore other Mozilla products that they will like 
* Increase overall Mozilla MAUs

#### What probes (suggested, if applicable)
Following events/settings should be set

* Fenix as default browser
* Fennec as default browser
* Focus as default browser
* User has installed Focus
* User has installed Lockbox
* User has installed the legacy Firefox Android browser

### Dependencies (Added by PM and Eng)
* Leanplum SDK

### Acceptance Criteria (Added by PM)
* Event pings can be viewed and triggered by Leanplum
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
* NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by bbinto** [comment] 2019-03-27 21:59
Hey @boek - let me know if that description works for you (I updated it)

**Comment by sblatz** [comment] 2019-04-23 21:33
Resizing this to a 3 as it's taking more work than just a normal telemetry ticket. I have to create a new util file that scans for these things :)

**Comment by abodea** [comment] 2019-06-04 15:13
I can still reproduce this issue for the `User has installed Lockbox` because in the meantime lockbox changed to lockwise and maybe the fix from the code contains lockbox instead of lockwise tested with **`Fenix version from 6/4 with Samsung Galaxy Note 9(android 8.1.0)`**.
## Please note the following
* **Fennec Nightly** -as default browser  ✅ [nightly_logcat.txt](https://github.com/mozilla-mobile/fenix/files/3253046/nightly_logcat.txt)
* **Fennec Beta** - as default browser ✅ [beta_logcat.txt](https://github.com/mozilla-mobile/fenix/files/3253049/beta_logcat.txt)
* **Fennec RC** - as default browser ✅ [firefox_logcat.txt](https://github.com/mozilla-mobile/fenix/files/3253045/firefox_logcat.txt)
* **Focus** - as default browser ✅ [focus_logcat.txt](https://github.com/mozilla-mobile/fenix/files/3253048/focus_logcat.txt)
* **Fenix** - as default browser ✅ [fenix_logcat.txt](https://github.com/mozilla-mobile/fenix/files/3253051/fenix_logcat.txt)
* **Chrome** - as default browser ✅ [chrome_logcat.txt](https://github.com/mozilla-mobile/fenix/files/3253050/chrome_logcat.txt)
* **None** - as default browser. ✅ [none_logcat.txt](https://github.com/mozilla-mobile/fenix/files/3253047/none_logcat.txt)
* **Lockwise** - installed ❌ but it wasn't displayed on the metrics [lockwise_logcat.txt](https://github.com/mozilla-mobile/fenix/files/3253044/lockwise_logcat.txt)
- Please note that the Mozilla products mentioned above with ✅ were displayed on the metrics but Lockwise wasn't displayed(maybe this because when the fix landed it was Lockbox but in the meantime it changed to lockwise).

![metrics](https://user-images.githubusercontent.com/42831109/58890965-4fc58e00-86f4-11e9-97cd-d954dcf8dc55.png)

I will remove the QA Needed until the lockwise ping will be fixed.

**Comment by abodea** [comment] 2019-06-05 09:30
Verified as fixed on the **`latest version with the build from 6/5 using Samsung Galaxy Note 9(Android 8.1.0).`**

Please note that the lockwise product appeared on the **`string_list`** but it is with the **`mozilla.lockbox`** name instead of **`mozilla.lockwise`** but I believe this is a bug on the **lockwise** side as the packageName is still **`mozilla.lockbox`** instead of **`mozilla.lockwise`** and I submitted this issue [ #739](https://github.com/mozilla-lockwise/lockwise-android/issues/739) on lockwise.
@sblatz if you can confirm that what I said above is ok regarding the lockbox/lockwise name issue please let me know.
![download (10)](https://user-images.githubusercontent.com/42831109/58945989-974c2880-878d-11e9-855f-e2fb83bc72f8.png)
Based on my comment above and this comment I will close this issue,

**Comment by sblatz** [comment] 2019-06-05 15:16
@abodea yes, their package name is correctly written as `mozilla.lockbox`.

**Comment by abodea** [comment] 2019-06-06 07:23
@sblatz Matthew and Devin confirmed that lockwise team deliberately excluded package names from the rebranding effort. Then `mozilla.lockbox` will always be displayed on the `metrics.mozilla_products`, can you confirm that this is ok?

**Comment by sblatz** [comment] 2019-06-06 14:30
@abodea yes, that's okay :)

**Closed** 2020-08-11 05:14 UTC
Labels: Feature:Telemetry, Release Blocker, eng:qa:verified
