### ISSUE TITLE
[Bug] The main menu starts at the bottom, hiding the "Add-ons" menu item on certain resolutions

### ISSUE THREAD

**Issue by eberhardweber** [mozilla-mobile/fenix#16882] opened 2020-12-06 12:49 UTC
## Steps to reproduce

The main menu in Firefox for Android has been designed to scroll if it cannot fit the phone screen. It starts from the bottom. This becomes a problem when more features are populated while the user is navigating a website (i.e. "Find in page") in addition to its basic functionality. 

On certain screen resolutions, this has the unfortunate side-effect of completely hiding the "Add-ons" menu without telling users, and there is nothing about the browser menu that signals to the user that the menu starts from the bottom instead of from the top, and that the menu element has been hidden.

Furthermore, it is extremely taxing to always have to scroll the menu to reveal the "Add-ons" item. It is by far my most used menu item given that many add-ons require constant maintenance (uBlock Origin to name the most important one). No other item comes close.

### Expected behavior

The menu should either 

a) visually tell the user the menu always begins from the bottom
b) or always start at the top instead of the bottom if there is no space. 

### Actual behavior

Here are screenshots of the behavior on my 1080 x 1920 device:

![Screenshot_20201206-144215519](https://user-images.githubusercontent.com/30755220/101280381-7117a680-37d1-11eb-88ec-e9c46164f42c.jpg)

![Screenshot_20201206-144227436](https://user-images.githubusercontent.com/30755220/101280399-7d9bff00-37d1-11eb-96b1-e5adc1ccc683.jpg)

### Device information

    Android device: Xiaomi Mi A1
    Fenix version: Beta (84.0.0-beta.2) -> Nightly (201205 17:02)

**Comment by anotherus3r** [comment] 2020-12-06 20:41
Similar: #16717

**Comment by sflorean** [comment] 2021-07-31 09:29
@eberhardweber this is still reproducible for you?
Tested on 1080 x 2160 device and the addons option was displayed, without scrolling.

**Comment by sflorean** [comment] 2022-02-03 14:33
Closing this due to lack of extra information and given the fact that the issue is not reproducible on our side. Please comment/ open a new bug if the issue occurs again.

**Closed by sflorean** 2022-02-03 14:33 UTC
Labels: 🐞 bug, Feature:Toolbar, wontfix, qa-triaged
