### ISSUE TITLE
[Bug] No longer supported

### ISSUE THREAD

**Issue by Kreuger** [mozilla-mobile/fenix#12185] opened 2020-07-02 08:29 UTC
Hey guys. I got the notification about how my current version of the app is no longer supported and to switch to the "other" Firefox preview. However when I clicked the link, it took me to the same play store listing as the version I have installed? Also I can't get that notification to come back up so I can try it again.

**Comment by manan025** [comment] 2020-07-02 11:07
Which version are you currently using?
The latest version available right now on Google Play Store is 5.2.0 which was released on June 23, 2020.
Please attach the screenshot of the app version from app settings. If you are using an older version then I will check the code.

**Comment by irvin** [comment] 2020-07-02 11:15
I got several local user reporting same issues, they use the 2 July version of Nightly ( https://play.google.com/store/apps/details?id=org.mozilla.fennec_aurora )  but still got the message that looks like should goes to preview.

**Comment by manan025** [comment] 2020-07-02 11:29
[Firefox Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fennec_aurora) is currently in Early Access, Which means that the latest version may not be the same for all the devices.

**Comment by klint** [comment] 2020-07-02 13:21
I got the message today when updating my Fenix Migration Nightly to build #2015749619

**Comment by irvin** [comment] 2020-07-02 13:42
![image](https://user-images.githubusercontent.com/165936/86366038-e45e3f00-bcac-11ea-99af-20203cb98e7e.jpeg)
![image](https://user-images.githubusercontent.com/165936/86366050-e7592f80-bcac-11ea-81ee-e656f750112e.jpeg)

**Comment by Kreuger** [comment] 2020-07-02 17:50
My build info is the same as irvin has posted.

**Comment by kbrosnan** [comment] 2020-07-02 18:00
Duplicate of #12207 

We are in the middle of the process of simplifying Firefox versions in the Play store. This information is correct. We have yet to get the Nightly build updated on the Firefox Preview <org.mozilla.fenix>. It will be updated soon.

**Comment by Kreuger** [comment] 2020-07-03 20:21
I understand that youre simplifying things. However the link just took me to the same version that I currently have installed.

**Comment by Dunexus** [comment] 2020-07-03 21:23
This was a bug, see https://github.com/mozilla-mobile/fenix/issues/12207#issuecomment-653162518. It should be fixed now.

**Closed** 2020-08-28 21:27 UTC
Labels: needs:triage, 🐞 bug
