### ISSUE TITLE
Focus on top sites when opening address bar

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#14917] opened 2020-09-10 00:24 UTC
### What is the user problem or growth opportunity you want to see solved?

To really function like the name is proposing top sites need to be present when opening the address bar and not like it's current behavior where you need to tap first to focus on it.

### How do you know that this problem exists today? Why is this important?

In the current solution you need to tap on the top sites after opening the address bar and then you can select a top site to open.

### Who will benefit from it?

Everybody who uses top sites or want them to be pinned because it's not a daily or hourly routine (Collections) more a check which one does once in a while. With a more handy functioning of the top sites it can really act like a top site.

**Comment by amkcpu** [comment] 2020-09-11 08:12
Duplicate of #14288.

**Closed** 2020-09-17 00:58 UTC
Labels: needs:triage
