### ISSUE TITLE
[Bug]: User isn't getting redirected after sign-out, the page just keeps loading

### ISSUE THREAD

**Issue by BraedanR** [mozilla-mobile/fenix#25438] opened 2022-05-30 13:45 UTC
### Steps to reproduce

**This requires the Air Canada mobile app installed**

1. Select firefox as default browser for device
2. Login into aeroplan account
3. Logout of aeroplan account (click on aeroplan tab - bottom right, navigate to user settings icon - top right)
4. User experiences endless spinner

### Expected behaviour

After clicking sign out, the user should be redirected back to the app.

### Actual behaviour

No redirection occurs.

One observation is by opening the url in the mozilla browser (instead of a webview from the app) and refreshing, the user is redirected.

### Device name

Samsung Galaxy S9

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

99.1.1

### Additional information

![image](https://user-images.githubusercontent.com/22818416/171004048-4a1dd7bc-4152-459d-84ee-5f3cec50851b.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20593)

**Comment by jonalmeida** [comment] 2022-06-17 23:49
Thanks for reporting! I'm assigning this to myself to investigate the bug. I have some suspicions this has to do with window requests in Custom Tabs not having app link support.

**Comment by allab** [comment] 2022-07-06 17:07
Hello @jonalmeida , we still have not heard from you. It's disrupting login flow for our customers and we'd like to at least to get an ETA on when we can have the results of the investigation and if any action needs to be taken from our side!

**Comment by jonalmeida** [comment] 2022-07-14 00:50
Hi @allab @BraedanR , sorry I'm on PTO until next week. I've been having trouble reproducing this bug  with a developer build, because it seems like the CustomTab intent that the AC app is creating is specific for `org.mozilla.firefox` and therefore ignoring my default browser app (dev build). When trying to fake the app ID with my build and debug signing key, I'm seeing some Android OS crash.

There are resources on the Android docs on how to create a Custom Tab intent without specifying the app ID. This might be related, but I'm unsure at this point without further investigation.

This is also useful to add however because there are variations of the Firefox browser as well on the play store (Firefox Beta/Firefox Nightly/Firefox Focus) which can all be set as a default browser.

**Closed** 2023-01-20 20:56 UTC
Labels: 🐞 bug, needs:triage, wontfix

**Comment by jonalmeida** [comment] 2023-01-26 03:52
@allab @BraedanR I was able to reproduce this bug with Firefox as well as Samsung.

This looks like a bug with the completion of the logout process on the site. 

A solution would be to make the site call `window.close();` once the logout process is complete. This would tell the browser to close the tab.

If you have any more questions or bug reports, please file them on bugzilla.mozilla.org as we are transitioning our bug reporter there.
