### ISSUE TITLE
[Bug] Gmail Custom Tab gap appears instead of TP icon

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#5287] opened 2019-09-13 02:41 UTC
## Steps to reproduce
1. Open a custom tab from Gmail

### Expected behavior
The tracking protection icon should appear.

### Actual behavior
A big gap is visible where the tracking protection icon should be.

### Device information

* Android device: Pixel 3 XL
* Fenix version: Nightly 190912 11:48 (Build #12551154)
📦: 13.0.0, f5ab632eb
🦎: 71.0a1-20190910095613

![Screenshot_20190912-213516](https://user-images.githubusercontent.com/626405/64834092-25faed80-d5a6-11e9-9982-b2ad218988e7.png)

**Comment by ekager** [comment] 2019-09-16 22:19
Closing as dupe of #5250

**Closed by ekager** 2019-09-16 22:19 UTC
Labels: Feature:CustomTabs, Feature:TrackingProtection, 🐞 bug
