### ISSUE TITLE
Places history storage appears to be missing preview URLs

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26591] opened 2022-08-22 20:58 UTC
This was discovered during investigation into https://github.com/mozilla-mobile/fenix/issues/26124

The tab pickup feature attempts to find match preview URLs from synced history to a recent synced tab so the image can be displayed on the home screen. When this behavior was initially being worked on, I thought I remembered that `HistoryStorage` had plenty of `previewImageUrl` to match. Now, however, I am not seeing any.

This should be investigated further to determine why there aren't preview image URLs available. I inspected this by placing debug breakpoints at [this line](https://searchfox.org/mozilla-mobile/rev/99f85f445e999edb88c2cca1530aec1fa6a39939/fenix/app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeature.kt#139) and inspecting the `history` variable there.

I would be curious to know whether anything changed at the A-S layer recently that may be causing the lack of preview image URLs. It's also possible that I'm misremembering their existence, but I don't think that's the case.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21359)

**Comment by MatthewTighe** [comment] 2022-08-22 22:20
Though I forgot to land https://github.com/mozilla-mobile/fenix/pull/26195 when I finished it, the code was initially committed on 7/25. It looks like there were some updates to the Places storage at the A-S layer since then that could be worth investigating: 
https://github.com/mozilla/application-services/commits/main/components/places/src/storage/history.rs

**Comment by rocketsroger** [comment] 2022-08-25 18:40
![Screenshot_20220825_142102](https://user-images.githubusercontent.com/6579541/186742873-b5ee6275-5b48-4151-bbe9-88382ee93af4.png)

From some debugging and testing I can confirm that we are retrieving the preview image url if it's available.  

@LaurentiuApahideanSV please confirm that if you visited the site locally (on Fenix Nightly) first (ex: apple.com) and close it, then open it on the remote browser (desktop).  Then sync tab in jump back should show the correct icon. Thanks,

**Comment by rocketsroger** [comment] 2022-08-25 20:15
I've noticed that on "Jump back in" local tab icon is not working correctly comparing to the sync tab.  I'll fix.  Thanks

**Comment by rocketsroger** [comment] 2022-09-06 21:14
After some debugging, I've confirmed that `previewImageUrl` does work on Nightly.  Closing since this is not an issue anymore.

**Comment by SoftVision-LorandJanos** [comment] 2022-09-16 13:10
Verified as fixed on the latest Nightly 106.0a1 (2022-09-16) build.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as fixed.
![Screenshot_2022-09-16-14-59-14-53_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/48829350/190634911-0c4df966-ab4c-4f6a-8a7a-9081dec71043.jpg)

**Closed by SoftVision-LorandJanos** 2022-09-16 13:10 UTC
Labels: eng:qa:needed, TaskContinuity
