### ISSUE TITLE
[Feature Request] Swipe up to open tab tray

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#13116] opened 2020-07-30 11:43 UTC
Please add a gesture support for Opening tab tray when we swipe the URL bar up.

https://photos.app.goo.gl/XwMZB5wesjNRdiP59

**Comment by cadeyrn** [comment] 2020-07-30 11:55
Duplicate of #11862.

**Comment by ekager** [comment] 2020-07-30 13:58
Closing as dupe of #11862

**Closed by ekager** 2020-07-30 13:58 UTC
Labels: needs:triage
