### ISSUE TITLE
[Bug] Bottom bar no longer retracts on any webpage, sometimes blocking navigation

### ISSUE THREAD

**Issue by Ruin0x11** [mozilla-mobile/fenix#18344] opened 2021-03-05 18:01 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to a website.
2. Scroll down.

### Expected behavior
The bottom navigation bar should retract at some point.

### Actual behavior
The bar never retracts, blocking the bottom part of the page it covers.

https://user-images.githubusercontent.com/6700637/110154890-a95f5e80-7d99-11eb-9590-709cdb05ad39.mp4

### Device information

* Device vendor / model and Android version: OnePlus 7 Android 9
* Firefox for Android version: Nightly 210303 17:03 (Build #2015796555)
AC: 74.0.20210302143118, cce45da40
GV: 88.0a1-20210302034602
AS: 72.1.0

**Comment by hwinnemoe** [comment] 2021-03-05 18:50
Duplicate of #18305 and fixed in Nightly 210304 17:01 (Build #2015796745).

**Closed** 2021-03-06 17:43 UTC
Labels: needs:triage, 🐞 bug
