### ISSUE TITLE
FNX3-16576 ⁃ [Bug] URL is not pre-selected when you exit from the library menu

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2777] opened 2019-05-23 09:36 UTC
## Steps to reproduce
1. Open a webpage.
1. Go to the library menu and exit back.
1. Tap the url bar.
    1. Expected behavior
The URL is selected and you can start typing to replace it.
    1. Actual behavior
The URL is not selected, the text cursor is at the beginning of the URL.
    1. Device information

* Android device: Nexus 5 (Android 6), P9 Lite (Android 6.0), Sony Xperia Z5 Premium (Android 7.1.1)
*not reproducing on: Galaxy Note 8 (Android 9)
* Fenix version: 5/23

**Comment by sv-sdeiac** [comment] 2019-07-05 08:09
Other steps to encounter this issue are:
1. Go to a page;
2. Tap on the text from the URL bar;

Notes: 
- Not reproducible if you tap on the empty part of the URL bar;
- Reproducible always when you go to a page;
- Fenix version: 1.0.1-rc.1

**Comment by NotWoods** [comment] 2019-11-15 03:35
Could not reproduce on Nightly 191109, this bug may be fixed now.

**Comment by AndiAJ** [comment] 2019-11-15 13:16
Hi, **verified as fixed** on the latest **Nightly Build #13190606 from 11/15** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191115_150825](https://user-images.githubusercontent.com/51314259/68945899-330ca680-07ba-11ea-97da-f10b02e520db.gif)

**Closed** 2020-08-12 17:43 UTC
Labels: Feature:Search, eng:qa:verified, 🐞 bug
