### ISSUE TITLE
[Bug] Reader view stuck in back button loop

### ISSUE THREAD

**Issue by Paulire** [mozilla-mobile/fenix#15746] opened 2020-10-07 10:05 UTC
## Steps to reproduce
Open a webpage which would work with reader mode. Open reader mode. Pressing the back button repeatedly.

### Expected behavior
After pressing back it should return you to the webpage view. Then pressing back again should take you to the previous page.

### Actual behavior
Pressing back on webview takes you back to reader mode. Pressing it again takes you back to the webview and the cycle continues. This also happens on nightly.

### Device information

* Android device: Android 10 on Motorolla G8 Power
* Fenix version: Fenix 81.1.1

**Comment by s-ankur** [comment] 2020-10-07 11:37
Duplicate of https://github.com/mozilla-mobile/fenix/issues/15470, thanks for reporting!

**Comment by mcarare** [comment] 2020-10-07 12:18
Closing as duplicate of #15470 .

**Closed by mcarare** 2020-10-07 12:18 UTC
Labels: needs:triage, 🐞 bug
