### ISSUE TITLE
[Bug]: wrap the top site text

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#26852] opened 2022-09-07 11:28 UTC
### Steps to reproduce

Post implementing backplating for topsites, the site name/title seems truncated while it seems there is too much space between the favicon and the title

So probably wrapping the text of the title to 2 line will make it look better

### Expected behaviour

Title should look fine 

### Actual behaviour

While there is too much space between favicon and site title,it seems text being truncated unnecessarily 

### Device name

rog 3

### Android version

android 12

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Device logs

![Screenshot_20220907-165458079 (1)](https://user-images.githubusercontent.com/58127841/188867566-2ec9844c-e5a9-4a2b-88a1-71a29781ea80.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21494)

**Comment by Cheap-Skate** [comment] 2022-09-09 06:28
Agree with this. My first row of Top Sites now just say The V...   The T...  The T...  The A... Which is not much use

Plus, the pin icon uses a lot of space, perhaps move the pin elsewhere eg to the top right of the favicon?

Ie:- 2 rows of text plus move the pin icon elsewhere.

Thanks!

**Comment by sheikh-azharuddin** [comment] 2022-09-09 08:41
Pin was pinned to the top left side which was actually good..not sure why they moved below and now inside

**Comment by hokonch** [comment] 2022-10-24 16:27
See also: https://github.com/mozilla-mobile/fenix/pull/26614

---

From the l10n perspective, this issue is even worse.
When you tap [Add to shortcut] on Japanese websites, the title generated for Top Sites is only two characters. Of course, it certainly does not make sense.
Renaming increases the number of Japanese characters available by one. But it remains difficult to come up with a distinguishable title with such few characters.
![Screenshot](https://user-images.githubusercontent.com/113707818/197573232-384ceb82-b725-4bec-8416-dfbce0587cbd.png)

**Comment by onemahon** [comment] 2022-11-03 22:12
Appreciate the feedback! We had moved the site name into the rectangular cards to ensure the text would still be legible against custom background wallpapers & colors, but that clearly interfered with other aspects of usability.

We're working on a reversion for this now, and we'll try to come up with a more robust way of solving that other problem in the future.

**Comment by Cheap-Skate** [comment] 2022-11-08 16:47
The new version with the text outside the backplating looks much better, thanks a lot. 

(I think there is room for more improvement eg 2 lines of text with wrap and the pin moved elsewhere, but what you have done is great)

**Comment by sheikh-azharuddin** [comment] 2022-11-08 17:50
The pin should be moved to top left corner like earlier version

**Comment by onemahon** [comment] 2022-11-09 15:49
Yeah, we're going to wind up revisiting the Top Site design later to make sure we're accommodating the variety of use cases & accessibility concerns that they entail. For now, I'm closing this issue as a dupe of #27746, since that at least resolves the core problem of the site names being truncated too aggressively.

Thanks so much for reporting the issue in the first place!

**Closed by onemahon** 2022-11-09 15:49 UTC
Labels: 🐞 bug, needs:triage
