### ISSUE TITLE
[Bug] Tab Closed Bottom Strip Remains

### ISSUE THREAD

**Issue by maxdule** [mozilla-mobile/fenix#8347] opened 2020-02-12 10:43 UTC
## Steps to reproduce
Have 2+ tabs opened in tabs view
Close one tab (swipe to the right)
Click to open one of the remaining tabs

### Expected behavior
Bottom purple `Tab closed --- UNDO` stripe should remain for a short period of time and disappear automatically.

### Actual behavior
Stripe remains all the time. Click on UNDO does remove it, but the behavior is quite annoying as it happens on all websites, 100% of the time.

### Device information
Xiaomi Mi 9 SE

* Android device: 9.PKQa.181121.001
* Fenix version: 3.2.1 (Build #20250350), 28.0.3, f0dc2cadd, GV: 73.0-20200123172213

**Comment by cadeyrn** [comment] 2020-02-12 10:44
Duplicate of#7799.

**Closed** 2020-02-12 10:46 UTC
Labels: needs:triage, 🐞 bug
