### ISSUE TITLE
[Bug] Migration screen is localized with 2 different languages.

### ISSUE THREAD

**Issue by nbp** [mozilla-mobile/fenix#8382] opened 2020-02-13 12:59 UTC
## Steps to reproduce
While migrating from Firefox for Android nightly to Fenix.

### Expected behavior
I expect to see a migration screen which is written in a single language (French).

### Actual behavior
The migration screen contains a header which is localized in English, while the list of checkmarks is localized in French.

The list of checkmarks includes "parameters", "passwords", …

### Device information

* Android device: 9
* Fenix version: Nightly 200210 10:05 (Build #2015722195)

**Comment by kbrosnan** [comment] 2020-02-14 22:02
@Delphine were the strings for the migration screen only partially translated for the French locale?

**Comment by softvision-miralobontiu** [comment] 2020-11-18 09:39
I was not able to reproduce this issue. I'll close this issue.

<img src="https://user-images.githubusercontent.com/40694158/99512811-94012880-2992-11eb-96b6-c3abdd4efd02.jpg" width="300" height="550" />

**Closed by softvision-miralobontiu** 2020-11-18 09:39 UTC
Labels: needs:triage, 🌐 L10N, 🐞 bug
