### ISSUE TITLE
[Bug] Complete tab overlay moves when trying to scroll through open tabs

### ISSUE THREAD

**Issue by lordgurke** [mozilla-mobile/fenix#14837] opened 2020-09-08 00:07 UTC
## Steps to reproduce
 * Open several tabs by tap-and-holding links on a website and choosing "Open in new tab".
 * Repeat this several times - about 6-7 times on most smartphone display resolutions should work. You need enough tabs that you need to scroll through the list to see them all.
 * Then, open the tab overlay by tapping the open tab counter in the address bar.
 * Try to scroll through the tabs by swiping up and down. Instead, the whole tab overlay will move up and down and you can't scroll through the tabs. Tabs not visible can't be opened.

It might out of a sudden beginn to work, mostly if you try to pull the tab overlay up to the top of the screen.
I tried swiping by touching and pulling the points marked with green circles in the screenshot and tried to move it in the directions of the orange arrow.

![grafik](https://user-images.githubusercontent.com/25770486/92421235-d975ce00-f177-11ea-86ea-af4c4a30722f.png)

### Expected behavior
Scrolling up and down through the tab list, when swiping up and down.

### Actual behavior
The tab overlay is moving up and down, the tabs are not scrolled.
Happens in normal mode and also in private mode.

### Device information

* Android device: HTC One, Android 8
* Fenix version: 80.1.2 Build 2015761283

**Comment by siebl** [comment] 2020-09-08 13:03
Same Issue with my HTC 10, Android 8.0.0

**Comment by liuche** [comment] 2020-09-10 00:17
If there are lots of open tabs, the tabs tray should open fully-opened, allowing scrolling. is this not the case?

**Comment by siebl** [comment] 2020-09-10 06:48
The tabs tray opens just fine in the first place:
![Screenshot_20200910-083606](https://user-images.githubusercontent.com/14271835/92690170-c9f5b100-f340-11ea-9852-d982ffcbab2b.png)

When i scroll down to the bottom of my tabs and want to scroll to the top again, the problem begins: As you can see in the screenshot, the tray looks fine. Clicking and draging downwards on the tabs moves the tray, as if I was draging on the little line in the header. When the tray covers about half of the screen, it jumps up to the top again
![Screenshot_20200910-084206](https://user-images.githubusercontent.com/14271835/92690872-fd850b00-f341-11ea-8a25-2bd19c346d20.png)
(After scrolling down)
![Screenshot_20200910-084218~2](https://user-images.githubusercontent.com/14271835/92690941-18577f80-f342-11ea-9dd8-60b272beb75b.png)
(finger drags down where red circle is)

**Comment by clientenq** [comment] 2020-09-11 11:17
Can confirm. Overlay moves down instead of providing tab list scrolling down.

possible workaround:
Hold top to resize/scroll the overlay to maximum screen size. Overlay is then locked for scrolling tab list down.

**Comment by clientenq** [comment] 2020-09-11 11:44
> If there are lots of open tabs, the tabs tray should open fully-opened, allowing scrolling. is this not the case?

The overlay can be resized by the user. No need to open full screen by default. Also the overlay has 2 tabs. When the private tab list is short it should thus also not open full screen.

Imho best solution is to not make scrolling depended on the size of the overlay. Overlay should after opening only resize on request of user via the resize control at top of overlay.

In addition I think the resize control was intended to remember te user prefered size of the overlay. Just because the list of tabs is long it does not mean the user prefers a maximum size at opening over being able to view the current open tab and scrolling. I certainly do not on a tablet. To much white space also when opend maximized.

**Comment by lordgurke** [comment] 2020-09-12 12:25
Exactly as mentioned above, but as an update:
With the latest release (80.1.3 / Build 2015762835) the problem is gone.

**Comment by siebl** [comment] 2020-09-14 05:43
As @lordgurke said: Last update seems to solve the problem. Since the update I cannot reproduce the Issue on my device anymore.

**Comment by PlayXman** [comment] 2020-09-14 13:05
I have `80.1.3` and I have been able to reproduce it again. I started private session, opened more than 6 tabs and after that I wasn't able to scroll through tabs - only whole tray moved.
Even regular tabs have gotten "stuck". Not even closing the app helps.

**Comment by hebu** [comment] 2020-09-16 05:54
I can confirm your description, @PlayXman 

On 80.1.3, the only way to scroll down the list is to swipe up first and then swipe down, or else it would try to close the tab overlay.

**Comment by lordgurke** [comment] 2020-09-17 04:54
Unfortunately, the problem seems **not** to be fixed for me, either. Had the opportunity to run in the bug again.
After the update it worked for a few days, now the problem occurs again.

**Comment by siebl** [comment] 2020-09-18 06:00
Just ran into the same Issue again, so the bug is not fixed in my case.
Only thing changing I could think of, is that I ran an app to remove cached, temp and installation files. Might just be coincidence but could be a weak lead aswell.

**Comment by ekager** [comment] 2020-12-18 05:08
Can anyone still reproduce this?

**Comment by PlayXman** [comment] 2020-12-18 08:02
> 
> Can anyone still reproduce this?

On stable version yes. Nightly, not sure, didn't test it very thoroughly.

**Comment by softvision-miralobontiu** [comment] 2020-12-21 12:06
I wasn't able to reproduce this issue on the latest Nightly from 12/21 with Google Pixel (Android 10), and HTC 10 (Android 8).
I'll close this issue.

**Closed by softvision-miralobontiu** 2020-12-21 12:06 UTC
Labels: Feature:Tabs, eng:qa:needed, 🐞 bug
