### ISSUE TITLE
[Bug] New tab view only shows URL bar + keyboard

### ISSUE THREAD

**Issue by evilpie** [mozilla-mobile/fenix#14306] opened 2020-08-27 17:08 UTC
## Steps to reproduce
- Open tabstray
- Press + to open a new tab

### Expected behavior
- About half of the screen is my top sites, the rest is the URL bar and keyboard
This is the behavior I observed in the emulator.

### Actual behavior
- The whole screen is covered by the URL bar, search engine selection and the keyboard
![image](https://user-images.githubusercontent.com/296445/91473047-9de62480-e898-11ea-925c-029eea809571.png)

### Device information

* Android device: Samsung S8
* Fenix version: Nightly 200827

**Comment by s-ankur** [comment] 2020-08-27 17:22
Dupe of #14057?

**Comment by miDeb** [comment] 2020-08-27 18:51
@s-ankur no, this looks like it's the old search experience, but it still automatically opens. Weird...

**Comment by s-ankur** [comment] 2020-08-27 18:53
I think new search got merged. I can't see the option in secret settings. These are the remaining issues about new search that will be fixed as regular nightly issues

**Comment by person808** [comment] 2020-08-27 19:07
This is an issue with new search when the "Show search engines" setting is on (Its off by default).

**Comment by evilpie** [comment] 2020-08-27 19:10
> This is an issue with new search when the "Show search engines" setting is on (Its off by default).

Indeed! Disabling this option fixes it. Thanks

**Comment by LittleAngelwings** [comment] 2020-08-28 06:56
Not for me. I have the option disabled and I have the issue also.

Nightly 200827 07:01 (Build #2015760379)
AC: 57.0.20200826190111, c93fc20af
GV: 81.0a1-20200820093209
AS: 61.0.13

**Comment by liuche** [comment] 2020-08-28 23:30
Can you double check @LittleAngelwings? there's a bug with when shortcuts item is highlighted/off - have you toggled the setting off in Settings > Search > Show Search engines (off)? Or please provide more information on your setup, I can't repro this.

**Comment by ekager** [comment] 2020-12-18 05:21
@evilpie is this still an issue for you?

**Comment by evilpie** [comment] 2020-12-18 11:01
@ekager I still get the same behavior when enabling "Show search engines" under "Search" and opening a new tab with **+**.

**Closed** 2021-06-23 13:19 UTC
Labels: Feature:Search, wontfix, 🐞 bug
