### ISSUE TITLE
When selected as the Assistance App, make Fenix behave like Fennec i.e. long press Home brings up new tab with keyboard present

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#7013] opened 2019-12-07 10:08 UTC
Select Fennec as Assistance App (Android Settings > Apps > 3 dot menu > Default Apps > Device Assistance app). Long press Home button:- 
- Fennec comes to foreground 
- with a new tab open, 
- the caret in the search text box and 
- the keyboard present.

ATM Fenix does not do this, with Fenix as Assistance App, long press Home just brings Fenix to the foreground but does not do the rest

Please could Fenix be changed to work like Fennec

(PS I think the Fenix search widget _does_ behave like Fennec which is a good start)

**Comment by kbrosnan** [comment] 2020-04-28 21:09
Found #3722 which this is a dupe of.

**Closed by kbrosnan** 2020-04-28 21:09 UTC
Labels: Feature:AndroidIntegration, feature request 🌟
