### ISSUE TITLE
[Bug] Password fields should not automatically start with capital letter

### ISSUE THREAD

**Issue by majurgens** [mozilla-mobile/fenix#19335] opened 2021-04-30 21:09 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Go to any page with a password field eg Gmail.com
Select the password field
Android keyboard automatically opens with Caps selected for the first letter

### Expected behavior
Do not default to starting with a capital letter for passwords

### Actual behavior
Android keyboard automatically opens with Caps selected for the first letter

### Device information

* Device vendor / model and Android version: Samsung galaxy tab s6 Android v11
* Firefox for Android version: ? (go to Settings -> About Firefox) 88.1.2
 
I know that this is a setting on my keyboard to capitalise the first letter. I am assuming that this can be overridden by applications

**Comment by Dunexus** [comment] 2021-05-01 07:28
Password, unlike sentences, don't expext first letter to be a capital. Most passwords starts with lowercase letter.

**Comment by kbrosnan** [comment] 2021-05-01 20:05
Using https://accounts.google.com and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password on a Pixel 2 XL with Gboard I get a lowercase keyboard.

**Comment by LaurentiuApahideanSV** [comment] 2021-05-12 13:51
I can confirm the issue is reproducible on Firefox Preview RC 88.1.3 and Nightly 5/12 using a Samsung Galaxy S9 (Android 8). In order to reproduce the issue the Samsung Keyboard has to be selected as the Default keyboard and the Auto capitalize option has to be on, with these settings enabled the issue does not occur on Chrome.

**Comment by makotokato** [comment] 2021-05-18 05:46
I think that Samsung's keyboard will look `TYPE_TEXT_FLAG_CAP_SENTENCE` flag even if having `TYPE_TEXT_VARIATION_PASSWORD`.  I can add a workaround in GeckoView.

**Comment by makotokato** [comment] 2021-05-18 05:52
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1711626

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by makotokato** [comment] 2021-06-24 04:14
@majurgens
This is merged to Firefox Nightly, so could you verify this?

**Comment by LaurentiuApahideanSV** [comment] 2021-06-24 15:13
I retested the issue on Firefox Preview Nightly 6/24 using a Samsung Galaxy S9 (Android 8) and the issue no longer occurs.

**Comment by makotokato** [comment] 2021-06-24 16:02
@LaurentiuApahideanSV or @kbrosnan 
Could you close this issue? This issue was moved to BMO and verified for fix.

**Comment by majurgens** [comment] 2021-06-25 00:03
> 
> 
> @majurgens
> This is merged to Firefox Nightly, so could you verify this?

Seems to be fixed in Nightly. Thanks

**Comment by LaurentiuApahideanSV** [comment] 2021-06-25 14:19
Since the issue no longer occurs I will mark this issue as closed. Once the fix is uplifted on the release version it will be fixed there as well.

**Closed by LaurentiuApahideanSV** 2021-06-25 14:19 UTC
Labels: Feature:IME, qa-triaged, 🐞 bug
