### ISSUE TITLE
Copy to clipboard from Share menu doesn't work

### ISSUE THREAD

**Issue by ProvocaTeach** [mozilla-mobile/fenix#25678] opened 2022-06-19 02:35 UTC
### Steps to reproduce

1. Have a tab open.
2. Tap the hamburger menu in the bottom right.
3. Tap the "share" icon at the bottom of the menu.
4. Tap "copy to clipboard" under "Recently Used". (Note: tapping "copy to clipboard" under "All Actions" does not reproduce the bug; see screenshot.) 
![Screenshot_20220618-192518_Firefox](https://user-images.githubusercontent.com/68936059/174463260-2b1f5e59-df0f-45a5-a3a8-ec2a366d2dd3.jpg)

### Expected behaviour

The URI in the address bar should be copied to the clipboard.

### Actual behaviour

A toast appears saying, "Cannot share to this app" (see screenshot). 
![Screenshot_20220618-192558_Firefox](https://user-images.githubusercontent.com/68936059/174463273-3e0ded4f-4b3c-479a-a824-d09850662159.jpg)

### Device name

Samsung Galaxy S10

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

101.2.0

### Additional information

Just to underscore why I thought this was worth reporting...

Because sharing links is so common, it is likely to be one of the first actions a user would take in the app. I worry that many would-be Firefox users would abandon the mobile browser based on this.

I have instinctively reached for the "Share" button many times (even though I know I can just hold down the address bar to copy) because that's what I used to do in Chrome.

I also am not a Firefox developer 😅

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20749)

**Comment by ProvocaTeach** [comment] 2022-06-20 10:12
Hi @Alexandru2909, thanks for the reply. Interesting – so Firefox has its own implementation of the share menu and prepends the OS copy button to the list of options.

At the risk of asking a dumb noob question, what were the reasons for sidestepping the default share menu? It might have lightened up the codebase and prevented these bugs. Copying URLs seems to work on apps that use it.

Asking users not to install other apps or avoid Samsung phones seems like dangerous territory from a UX perspective....

**Comment by Alexandru2909** [comment] 2022-06-20 10:31
Sorry for any misunderstanding I might have caused, I did not mean the users should not install other apps nor that they should avoid Samsung phones. I was just suggesting that this issue seems not to be related to Fenix. 

I also tried to reproduce this issue on a Note10 device, but could not find the `Copy to clipboard` share app.

**Comment by hkaancaliskan** [comment] 2022-06-20 17:21
@ProvocaTeach I think they implemented their own share menu because of "send to device" section, that's not possible to add it to android's default menu.
Of course you can use Samsung phones or whatever app you want, but every app can add their own tool to share menu, you should know which item whose :) they can't actually change icon or text of it because another app may add something like that and it'll overlap again :)
imho they could separate the copy link button from the menu like android's direct share item in share menu

**Comment by makotokato** [comment] 2022-06-27 08:26
Related to https://github.com/mozilla-mobile/fenix/issues/15394

**Comment by makotokato** [comment] 2022-06-27 08:37
When I test this, I cannot reproduce this with Galaxy S8 (Android 9)

**Comment by devfilmer** [comment] 2022-07-24 04:33
I have had this same issue for several versions. I. Using a a Google Pixel 6, I had the same issue on Pixel 4 in the past more than a year or so).
How is the share app recent list innumerated?

**Comment by makotokato** [comment] 2022-07-25 05:47
@devfilmer 
Could you provide exactly reproduce step?

**Comment by devfilmer** [comment] 2022-07-25 13:41
The steps are exactly as stated in the original post.
The nuance is .. this is the copy to clipboard on recently used.

Open Browser window
Click 3 dot "hamburger" menu in bottom right corner
Click share icon at bottom of list second from the end icon
Click "copy to clipboard" in recently used group at bottom left

Purple error message slides up from bottom
Cannot share to this app

**Comment by devfilmer** [comment] 2022-07-25 13:46
Uploading screen-20220725-094341~2.mp4…

**Comment by topotropic** [comment] 2022-10-28 08:39
Are we able to fix this or should we close it? @makotokato @Alexandru2909

**Comment by devfilmer** [comment] 2022-10-28 16:00
Please fix.
This is the only bug I ever see with Firefox.

I'm sure MANY users see this issue.
Sharing a link is a fundamental activity.

**Comment by amocirean** [comment] 2022-11-01 08:56
Hello @ProvocaTeach , thank you for submitting the issue.
I was not able to reproduce the issue on the latest Firefox Nightly(108.0a1) nor latest Firefox Beta (107.0b5). The Copy to Clipboard from the Share menu works as intended, the text is getting copied and I am able to paste it anywhere.
I've tested this using the following devices: Google Pixel 6 (Android 13), Samsung A32 5g (Android 12).
Please let us know if you can still reproduce the issue on the latest Nightly or Beta.

Thanks!

**Comment by riccjohn** [comment] 2022-11-06 22:31
I have the same issue. It's been affecting me for months, so I'm not sure when it began. 

Firefox version: 106.1.0 (Build #2015909131), 71ca6c1f7+
AC: 106.0.5, 5f06485fc3
GV: 106.0-20221010181815
AS: 94.2.1

Phone: Google Pixel 6

Android: 13
Android Build: TP1A.221005.002
Kernel: 5.10.107-android13-4-00004-gf0fe4f768061-ab8935229
#1 Thu Aug 11 01:16:28 UTC 2022

**Comment by cpeterso** [comment] 2023-01-12 05:18
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809780

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2023-01-12 05:18 UTC
Labels: 🐞 bug, Feature:Sharing, needs:triage
