### ISSUE TITLE
[Bug] Unclear what to do to complete editing a bookmark

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#6996] opened 2019-12-06 13:15 UTC
Navigate to a URL
Hit the 3 dot menu then "star" to bookmark the page
Hit the EDIT text in the toast message
I move to the edit bookmark screen

When I have completed the edit, what do I do??? There is no "Save bookmark" icon to tap. How do I save the edited bookmark?

The actual answer is press <- at the top left which is counter-intuitive, <- should undo the last action not save???

I suggest the options at the top of the screen should be CANCEL or SAVE as text or appropriate icons (eg tick/check mark).

**Comment by topotropic** [comment] 2020-01-15 11:16
dupe of https://github.com/mozilla-mobile/fenix/issues/3813

**Closed by topotropic** 2020-01-15 11:16 UTC
Labels: Feature:Bookmarks, P2, S2, needs:UX-feedback, 🐞 bug
