### ISSUE TITLE
FNX-3348 ⁃ [Bug]"Run in private browsing" should remain enabled even if the user disables the Add-on

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10196] opened 2020-04-24 15:15 UTC
## Steps to reproduce
1. Install any of the featured Add-ons and open it
1. Enable "Run in private browsing"
1. Disable the Add-on
1. Exit to the Add-ons manager
1. Re-open the Add-on and check the state of the "Run in private browsing" option

### Expected behavior
"Run in private browsing" should remain enabled (*As per Firefox on Desktop*)

### Actual behavior
"Run in private browsing" is also disabled

### Device information
* Android device: Google Pixel 3a (Android 10)
* Fenix version: Nightly Build #21150608 from 4/24

### Notes
► Video
![20200424-180656](https://user-images.githubusercontent.com/51314259/80228278-88958b00-8657-11ea-9bea-6ebe24449736.gif)

Related to #6123

**Comment by Amejia481** [comment] 2020-04-24 15:23
I think we should hide the **"Run in private browsing"** when the add-on is disabled, similar to what we are doing with the **"Settings"** section because when an add-on is disabled we can't apply any changes to **"Run in private browsing"**

**Comment by Amejia481** [comment] 2020-05-01 19:26
@AndiAJ  @psymoon landed a related patch, would mind retesting? :)

**Comment by AndiAJ** [comment] 2020-05-04 07:44
Hi @Amejia481 & @psymoon , I've just checked this matter on the latest **`Nightly 200504 from 5/4`** using the following devices: 

• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

✔️ The "Run in private browsing" is hidden when the add-on is disabled
✔️ The status of the "Run in private browsing" is properly displayed after re-enable 
❌ The "Run in private browsing" can't be used after the user disables and re-enables the Add-on
❓ Noticed sometimes a delay in hiding the "Run in private browsing" after disabling the Add-on

► Video delay in hiding "Run in private browsing"
![20200504-103421-online-video-cut](https://user-images.githubusercontent.com/51314259/80945222-03973800-8df4-11ea-834c-345709aa63a0.gif)


► Video "Run in private browsing" can't be used after the user disables and re-enables the Add-on
![20200504-102325](https://user-images.githubusercontent.com/51314259/80944637-b4043c80-8df2-11ea-9562-75d07e735e3d.gif)


I'll **remove the QA needed label** until further notice.

**Comment by psymoon** [comment] 2020-05-05 21:12
@AndiAJ "The "Run in private browsing" can't be used after the user disables and re-enables the Add-on" - does this happen all the time? I can't seem to reproduce this.

**Comment by AndiAJ** [comment] 2020-05-06 10:43
Hi @psymoon, yes, unfortunately quite often.
Re-checked on the latest Nightly Build 200506 from 5/6 using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1) 

► Video "Run in private browsing" can't be used after the user disables and re-enables the Add-on
![20200506-102237](https://user-images.githubusercontent.com/51314259/81168291-67aa2f80-8f9f-11ea-96b7-85ba206cd4f0.gif)



► Video Delay in hiding the "Run in private browsing" 
![20200506-102129-online-video-cut (1)](https://user-images.githubusercontent.com/51314259/81148077-45ef7f00-8f84-11ea-8f0e-a192d08df91f.gif)

**Comment by AndiAJ** [comment] 2020-05-07 08:49
Hi, I've re-checked this matter on the latest Nightly build 200507 from 5/7 using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1) 

✔️ The "Run in private browsing" is hidden when the add-on is disabled
✔️ The status of the "Run in private browsing" is properly displayed after re-enable
✔️ "Run in private browsing" can be used after the user disables and re-enables the Add-on

► Video -  "Run in private browsing" is hidden and the status of the "Run in private browsing" is properly displayed after re-enable
![20200507-112257](https://user-images.githubusercontent.com/51314259/81271982-7eab5900-9055-11ea-9dc6-b9d52423f0b8.gif)


► Video "Run in private browsing" can be used after the user disables and re-enables the Add-on
![20200507-101349](https://user-images.githubusercontent.com/51314259/81270783-e95b9500-9053-11ea-8da8-a0cb616a2227.gif)



On the other hand, I've bumped into other issues:

❌  Delay in hiding the "Run in private browsing.
This seem to be **happening only with HTTS Everywhere**, because of this I've opened a new issue #10475

❌ A regression, filled #10473 

I'll mark this issue **verified as fixed**, the remaining issues will be tracked in separate bugs.

**Closed** 2020-08-10 19:36 UTC
Labels: Feature:WebExtensions, S2, eng:qa:verified, needs:triage, 🐞 bug
