### ISSUE TITLE
[Bug] if a webpage is closed using quick tab menu all previous opened tab becomes blank.

### ISSUE THREAD

**Issue by rkogaurav** [mozilla-mobile/fenix#13825] opened 2020-08-14 05:11 UTC
## Steps to reproduce
![20200814_103625](https://user-images.githubusercontent.com/30550628/90215827-9182b600-de1a-11ea-9ee4-59d9353b3d13.gif)

1. open a any webpage.

2. open another webpage in new tab.

3. close the webpage using quick tab menu Close tab option.

4. all previous opened tab shows blank white page.

5. only way pages show up again is switching between tabs or changing between landscape and potrait.

### Expected behavior
when we close a tab all previous opened tabs should not become blank .

### Actual behavior
all opened tabs become blank.

### Device information

* Android device: samsung SM-A505F (exyno)
* Fenix version: nightly and beta

**Comment by hwinnemoe** [comment] 2020-08-14 10:16
Related to/Duplicate of #12593

**Closed** 2020-08-14 10:54 UTC
Labels: needs:triage, 🐞 bug

**Comment by rkogaurav** [comment] 2020-08-14 10:56
ok looks similar closing.
