### ISSUE TITLE
[Bug] Instagram shows as notifications not turned on but its actually allowed

### ISSUE THREAD

**Issue by hkaancaliskan** [mozilla-mobile/fenix#16713] opened 2020-11-22 15:57 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Go to https://www.instagram.com/direct/inbox/
Allow notifications
Reload page

### Expected behavior
Notifications working properly and not showing banner again and again

### Actual behavior
Instagram shows banner about "turn on notifications" and dm's not received(?) 

### Device information

* Android device: Xperia XZ1 
* Fenix version: 11/21 Nightly

![Screenshot_20201122-185139_Firefox_Nightly~2](https://user-images.githubusercontent.com/17825767/99908550-5edb3a00-2cf4-11eb-9739-baeb03f55480.png)

**Comment by hakkikaancaliskan** [comment] 2021-01-16 16:17
Looks like it's fixed.
Nightly 210115 17:01 (Build #2015787531)
AC: 71.0.20210114143040, 96d4bc2e3
GV: 86.0a1-20210113100240
AS: 67.2.0

**Comment by hakkikaancaliskan** [comment] 2021-01-16 16:27
Nope, it's not. It was fixed at first but when I restart fenix it came back.

**Comment by hakkikaancaliskan** [comment] 2021-01-16 16:28
STR:
1- give Instagram notification permission
2- close tab and fenix
3- reopen fenix and go to dm
You'll see banner

**Comment by hakkikaancaliskan** [comment] 2021-07-15 18:53
Still an issue

**Comment by hakkikaancaliskan** [comment] 2021-07-16 09:23
Not reproducible on nightly anymore
If someone could verify we could close the issue

**Closed** 2022-01-26 23:44 UTC
Labels: 🐞 bug, Feature:Notifications, wontfix
