### ISSUE TITLE
[Bug] https://arnaud.at/emoji crashes Fenix Nightly

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla-mobile/fenix#6293] opened 2019-10-27 12:57 UTC
## Steps to reproduce

Open Fenix Nightly, click in the address bar and enter the following URL:

https://arnaud.at/emoji

and then let it load.

### Expected behavior

Does not crash Fenix after a few seconds. Probably also the demo to work, but that's secondary for now.

### Actual behavior

Fenix crashes after a few seconds. If you open it from another page (Open in new Tab), it freezes before you can even switch to the tab.

### Device information

* Android device: Nokia 5, Android 9
* Fenix version: Nightly 191027 Build #13000608; 19.0.0 6e6311ea4; 72.0a1-20191025095546

**Comment by ValentinTimisica** [comment] 2020-02-21 15:07
I tried to reproduce it but the app does't crash when I load that url. Can someone from QA try to reproduce this?

**Comment by softvision-miralobontiu** [comment] 2020-02-21 15:09
Tested on the latest Nightly build from 2/21 with Nokia 6 (Android 7.1.1), and Samsung Galaxy Note 8 (Android 9), and I was not able to reproduce the crash.
I will close this issue.

**Closed by softvision-miralobontiu** 2020-02-21 15:09 UTC
Labels: P2, S2, b:crash, 🐞 bug

**Comment by MichaelKohler** [comment] 2020-02-21 15:18
Yep can't reproduce anymore either.
