### ISSUE TITLE
[Bug] Unable have open tabs closed when closing Firefox app

### ISSUE THREAD

**Issue by antimatter84** [mozilla-mobile/fenix#15390] opened 2020-09-24 14:44 UTC
## Steps to reproduce
Open several tabs, close Firefox and open it again. Tabs are still there.

### Expected behavior
An option to configure Firefox to close its open tabs when Firefox itself is closed. This was possible with pre-80 Firefox version.

### Actual behavior
Tabs cannot be closed when Firefox is closed. There is only a way to close them after a time period with the shortest being one day. In one day, the tab list can be quite full.

### Device information

* Android device: Google Pixel 3a, Android 11
* Fenix version: 81.1.1

**Comment by hwinnemoe** [comment] 2020-09-25 09:47
See also/ Duplicate of #11449

**Comment by antimatter84** [comment] 2020-09-25 15:55
The feature described in #11449 does not work for me.

**Comment by liuche** [comment] 2020-10-15 00:07
In settings, there is "Delete browsing data on Quit" where the items will be deleted after clicking the quit item in the menu. Simply swipe-close is complicated bc apps can't distinguish between if the user swipe-closes, or if Android memory pressure kills an app.

You could also set Fenix to close your tabs after 1 day.

For now, the best place to follow along would be #11449, so I'm going to close this issue in favor of that one.

**Closed by liuche** 2020-10-15 00:07 UTC
Labels: needs:triage, 🐞 bug

**Comment by vehosah** [comment] 2023-01-18 18:03
> In settings, there is "Delete browsing data on Quit" where the items will be deleted after clicking the quit item in the menu. Simply swipe-close is complicated bc apps can't distinguish between if the user swipe-closes, or if Android memory pressure kills an app.
> 
> You could also set Fenix to close your tabs after 1 day.
> 
> For now, the best place to follow along would be #11449, so I'm going to close this issue in favor of that one.

Pity that the bot closed this also
