### ISSUE TITLE
FNX-5259 ⁃ [Bug] Site info panel should hide while loading the "report a problem" link

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1814] opened 2019-04-19 12:17 UTC
## Steps to reproduce
1. Open the quick settings panel.
1. Tap the Report a problem link under the TP toggle.
    1. Expected behavior
The settings panel is dismissed.
    1. Actual behavior
The settings panel is still displayed.
    1. Device information

* Android device: HTC 10 (Android 8.0), HTC Desire 820 (Android 6.0.1)
* Fenix version: 4/18 build

**Comment by cadeyrn** [comment] 2019-04-19 12:29
Duplicate of #1720.

**Closed** 2020-08-11 13:01 UTC
