### ISSUE TITLE
[Bug]: Address bar suggestions can take a very long amount of time to appear after typing something

### ISSUE THREAD

**Issue by DavidJCobb** [mozilla-mobile/fenix#23717] opened 2022-02-14 09:27 UTC
### Steps to reproduce

Type something into the address bar and wait, with only suggestions from history and bookmarks enabled.

### Expected behaviour

Address bar suggestions should take no longer than a couple seconds to appear. If necessary, there should be some sort of loading indicator.

### Actual behaviour

Address bar suggestions can take very long amounts of time to appear, with no loading indicator.

Testing just now, it took about twelve seconds for suggestions for the input `fenix issues` to appear; this is almost immediately after starting the browser, albeit with a very large saved session.

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

97.1.0 (Build #2015860771), 365e9fb59+

### Additional information

I'd expect this bug to be related to history size, bookmarks size, and/or the number of tabs (whether loaded or unloaded) in the current session. If that's the case, then I can't provide useful information by installing any debug builds with extra logging unless it's possible to import my session, add-ons, etc., in full from the release build. (I know that was needed to diagnose favicons as the cause of similar lag in #20351.)

If I see autosuggest times longer than 12 seconds I'll try to remember to post them here. I remember seeing times well in excess of 30 seconds before when searching for pages I knew I had bookmarked. Only difficulty is that I have to run Firefox in split screen with a stopwatch app to get accurate times.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19482)

**Comment by DavidJCobb** [comment] 2022-02-14 09:32
`resist and disorder` took eight seconds to produce three suggestions, including [this bookmarked page](https://m.youtube.com/watch?v=TRhErLqpdto).

If I typed `resist snd disorder`, immediately erased it by holding backspace, and then typed `resist and disorder`, then it took about twenty-two straight seconds for the same results to appear.

**Comment by mcomella** [comment] 2022-02-16 22:03
@DavidJCobb Would you be able to take a performance profile when you reproduce the behavior? Here are some instructions: https://profiler.firefox.com/docs/#/./guide-remote-profiling

**Comment by DavidJCobb** [comment] 2022-02-21 20:43
[This profiler session](https://share.firefox.dev/33Gsaeq) reproduces the `resist snd disorder` to `resist and disorder`  case, including me actually selecting the suggested site to navigate to it.

**Comment by mcomella** [comment] 2022-05-25 22:10
Looking at the profile, we see a pattern like this for the history provider:
![image](https://user-images.githubusercontent.com/759372/170374649-449dde24-9878-42c5-b67d-aab8749e723a.png)

I wonder if this is that the history provider locks the DB, cancel is called but it only yields after the access completes, but then we have another key press queued up which locks the DB (presumably not cancelled for the same reasons), etc. That's why we see that stepping pattern with overlap and increasing access times.

Later, we also see an extremely long read:
![image](https://user-images.githubusercontent.com/759372/170374841-86012a06-e17f-46d1-ba97-d020310610f6.png)

I'm not exactly sure why we'd see this or what's causing it.

**Comment by Earlopain** [comment] 2022-06-15 14:23
I'm having the same issue, but my profile just contains these long loads. It also doesn't take as long, but 6 seconds are still uncomfortable and makes me think that I should have typed it out myself instead of waiting.
https://share.firefox.dev/39oOpIy
![image](https://user-images.githubusercontent.com/14981592/173849158-8c867c7c-814c-4b18-b970-20794c730b71.png)

**Comment by mcomella** [comment] 2022-07-06 20:55
Triage: https://github.com/mozilla-mobile/fenix/issues/25875 looks like a dupe of this bug but there may be additional discussion/debugging information (such as profiles) in there until we confirm they are the same.

**Comment by Mugurell** [comment] 2022-07-25 06:57
@DavidJCobb There have been some recent changes about the history suggestions (more context [here](https://github.com/mozilla-mobile/fenix/issues/25875)).
Does the issue reported here still reproduces for you / has it been resolved?

**Comment by Mugurell** [comment] 2022-07-27 14:01
Based on the feedback from https://github.com/mozilla-mobile/fenix/issues/25875 it seems like this issue was resolved.
Feel free to leave a comment if the problem persists for you.

**Closed by Mugurell** 2022-07-27 14:01 UTC
Labels: 🐞 bug, performance, needs:triage
