### ISSUE TITLE
Missing pin icon on pinned pages

### ISSUE THREAD

**Issue by mrninko** [mozilla-mobile/fenix#14746] opened 2020-09-04 20:08 UTC
### What is the user problem or growth opportunity you want to see solved?
Missing pin icon on ponned pages on landing page.

### How do you know that this problem exists today? Why is this important?
It was available before 81.1.0-beta.2
To keep track of which pages are pinned and which are not.

### Who will benefit from it?
Everyone who use pinned pages.

**Comment by gabrielluong** [comment] 2020-09-04 21:35
Thanks for the report. This is a duplicate of #14145, which is underway!

**Closed by gabrielluong** 2020-09-04 21:35 UTC
Labels: needs:triage
