### ISSUE TITLE
[Bug] Language is not setup correctly on Android 8 which doesn't have officially dark mode

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#7644] opened 2020-01-13 18:28 UTC
## Steps to reproduce
1. settings
2. language
3. select some language other than "follow device language" (for example Polish)

### Expected behavior
language is changed

### Actual behavior
on Android 8 (S7) nothing happens, works OK on Android 10 (Pixel)

### Device information

* Fenix version: nightly 13 jan

**Comment by cadeyrn** [comment] 2020-01-13 18:36
What are your device _and_ Fenix theme settings? Could be a duplicate of #7559. Please see https://github.com/mozilla-mobile/fenix/issues/7559#issuecomment-572997231.

**Comment by marcinwiacek** [comment] 2020-01-13 18:44
Android 8 doesn't have dark theme settings................................................... it was added later in the system.

**Comment by cadeyrn** [comment] 2020-01-13 19:24
So you have a light system theme and #7654 shows that your Fenix theme is the dark theme. So it's really a duplicate of #7559.

**Comment by marcinwiacek** [comment] 2020-01-13 19:41
@cadeyrn please distinguish two test cases - one, when system theme is updated, when FP is really off (cold app start) and one, when app is resumed from background.

**Closed** 2021-02-12 04:27 UTC
Labels: wontfix, 🐞 bug
