### ISSUE TITLE
FNX-11893 ⁃ [Bug]Tab Tray -White screen caused by the fact that the page view remains visible after closing the tab

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11037] opened 2020-05-29 13:29 UTC
## Prerequisites
Have an open tab

## Steps to reproduce
1. Tap the Tabs Tray
1. Remove the tab
1. Dismiss the Tabs Tray
1. Tap the URL Bar
1. Tap the device back button

### Expected behavior
Steps 3 : The page view should be dismissed (Fenix home screen :question:)
Step 5 : The user should be properly re-directed to the home screen

### Actual behavior
Steps 3 : The page view remains displayed with an empty URL bar 
Step 5 : White screen

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build 200529 from 5/29

### Notes
► Video
![20200529-161127](https://user-images.githubusercontent.com/51314259/83264921-7adca380-a1c9-11ea-8c26-bbf218ef5d8d.gif)

**Comment by hwinnemoe** [comment] 2020-05-29 13:38
Possible duplicate of #10905?

**Comment by AndiAJ** [comment] 2020-06-03 07:31
As per [this fix](https://github.com/mozilla-mobile/fenix/issues/10998#issuecomment-638011105) the above mentioned issue is no longer reproducible  on the latest **`Nightly Build 200603 from 6/3`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

**Closed** 2020-08-11 02:43 UTC
Labels: Feature:Tabs, S2, Skittle, eng:qa:verified, 🐞 bug
