### ISSUE TITLE
Increased error rate for `recent_synced_tabs.recent_synced_tab_shown` and `tabs_tray.access_point` due to invalid labels

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/fenix#25437] opened 2022-05-30 13:14 UTC
We're seeing a spike in errors for the [`recent_synced_tabs.recent_synced_tab_shown`](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/recent_synced_tabs_recent_synced_tab_shown) metric and [`tabs_tray.access_point`](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/tabs_tray_access_point) metric due to invalid labels.
([Our monitoring dashboard](https://mozilla.cloud.looker.com/dashboards/382?Channel=mozdata.org%5E_mozilla%5E_fenix.metrics&Submission+Date=7+day+ago+for+7+day))

The code is here: 
* https://github.com/mozilla-mobile/fenix/blob/5ea4c6533a7e564e3576a159b9d0aea8a954a447/app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeature.kt#L113
* https://github.com/mozilla-mobile/fenix/blob/5ea4c6533a7e564e3576a159b9d0aea8a954a447/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt#L137

Labels are restricted to lowercase alphanumerics, underscores, dashes and dots ([see also our docs](https://mozilla.github.io/glean/book/reference/metrics/index.html#label-format)).
From the code above it looks like these might potentially be user-defined values.
In any case these should be sanitized before recording them.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20592)

**Comment by mcarare** [comment] 2022-05-30 15:20
@badboy It seems that the problem is with the value sen. In both cases, there are Enums with values (so no user-defined values), but the value sent contains uppercase letters. I am going to put a fix for these.

**Comment by mcarare** [comment] 2022-05-31 10:27
Fixed in https://github.com/mozilla-mobile/fenix/pull/25440. Will reopen if the situation reoccurs.

**Closed by mcarare** 2022-05-31 10:27 UTC
Labels: needs:triage
