### ISSUE TITLE
[Firefox 79 Android] PWA opens with a white screen when Firefox is not open in the background

### ISSUE THREAD

**Issue by pianoworld** [mozilla-mobile/fenix#14095] opened 2020-08-23 19:31 UTC
## Steps to reproduce

1) visit any PWA website, i.e.  trivago.com
2) Add toHomescreen
3) close Firefox and close the PWA
4) open the newly added PWA

The PWA opens only a white screen.

### Expected behavior

It should open the PWA app normally.

This bug could be reproduced on all PWAs we tried on  Firefox 79 on Android. Firefox Nightly doesn't have this bug by the way.

* Android device: Lenovo TB-8505F,  but confirmed on several other devices

**Comment by liuche** [comment] 2020-08-25 01:51
Which version of 79 were you testing? The most recent version should be 79.0.5 - if you can reproduce it on the Firefox Beta channel, that would also be concerning.

**Comment by pianoworld** [comment] 2020-08-25 18:46
@liuche Thanks for your reply. Yes I was using  79.0.5. I can reproduce the white screen issue on  Firefox beta (80.0.1-beta2) as well :(. Now I could also reproduce it on Nightly (200706 06:01). So it's a serious thing.

Twitter shows the same bug. The only PWA that is working is this one (strange): https://itegration.com/pwa/

**Comment by yoasif** [comment] 2020-08-26 04:05
I can reproduce this on https://itegration.com/pwa/ and https://www.computerbase.de/ on 

Nightly 200825 06:07 (Build #2015759987)
AC: 56.0.20200821184145, 96a8a14dc
GV: 81.0a1-20200820093209
AS: 61.0.12

**Comment by jonalmeida** [comment] 2020-09-05 18:48
This sounds like the bug https://github.com/mozilla-mobile/fenix/issues/10689 which we closed as cannot reproduce.

**Comment by diabolic-preacher** [comment] 2020-09-06 06:21
This is reproducible in Firefox Nightly for Developers (Early Access) which I was stuck with an old version of from the Play Store because there was no message or notification that there will be no more updates to it or that despite it saying "Firefox Nightly" in Apps section of Android Settings, there is actually a much newer Firefox Nightly for regular users which also show up as Firefox Nightly in Apps.

**Comment by diabolic-preacher** [comment] 2020-09-06 06:26
> This sounds like the bug #10689 which we closed as cannot reproduce.

I did try both versions with ublock with my exceptions imported from an exported rules file, the Nightly forDevelopers can still reproduce the issue while newer Nightly can't.

**Comment by Mugurell** [comment] 2020-09-07 05:52
> > This sounds like the bug #10689 which we closed as cannot reproduce.
> 
> I did try both versions with ublock with my exceptions imported from an exported rules file, the Nightly forDevelopers can still reproduce the issue while newer Nightly can't.

`Firefox Preview Nightly for Developers` is not supported anymore. It won't receive future updates.
If you're interested in the development channel app please use `Firefox Nightly` - https://play.google.com/store/apps/details?id=org.mozilla.fenix

**Comment by Mugurell** [comment] 2020-09-07 05:53
@ QA I cannot reproduce.
Based on the above report from @diabolic-preacher and #10689 looks like this can be closed?

**Comment by abodea** [comment] 2020-09-07 10:30
Verified as fixed on the latest **Nightly 9/7** with **Google Pixel 4 XL (11).**
Note that I had no issues regarding blank/white screen when opening a PWA.
@pianoworld do you still reproduce this issue on the latest Nightly build?

**Closed by abodea** 2020-09-07 10:30 UTC
Labels: Feature:PWA, eng:qa:needed, 🐞 bug

**Comment by pianoworld** [comment] 2020-09-07 10:49
@abodea Just checked, can't reproduce it anymore! Good job.

**Comment by pianoworld** [comment] 2020-09-28 20:38
This white screen bug reappeared: Firefox 81.1.1 (Build #2015764547)

**Comment by diabolic-preacher** [comment] 2020-10-02 12:47
> This white screen bug reappeared: Firefox 81.1.1 (Build #2015764547)
I also was surprised to see this issue recur again after so long. Initially I thought it was random but noticed that it is reproducible in the exact same way even on Nightly 200929 17:11 (Build #2015766795)
AC: 61.0.20200925190057, 01306f87c
GV: 83.0a1-20200922094538
AS: 63.0.0

**Comment by pianoworld** [comment] 2020-10-02 13:01
@diabolic-preacher https://github.com/mozilla-mobile/fenix/issues/15335 Hope it will be fixed soon!

**Comment by diabolic-preacher** [comment] 2020-10-04 09:41
This looks like it is fixed in Nightly 201002 17:06 (Build #2015767371)
AC: 62.0.20201002143132, d96b23188
GV: 83.0a1-20201001094020
AS: 63.0.0 again 👍🏽

**Comment by pianoworld** [comment] 2020-10-04 19:19
@diabolic-preacher Are you sure? For me issue still exists on:

Nightly 201004 17:02 (Build #2015767755)
AC: 62.0.20201002143132, d96b23188
GV: 83.0a1-20201001094020
AS: 63.0.0

Sunday 10/4 @ 5:11

**Comment by diabolic-preacher** [comment] 2020-10-05 02:19
> @diabolic-preacher Are you sure? For me issue still exists on:
> 
> Nightly 201004 17:02 (Build #2015767755)
> AC: 62.0.20201002143132, d96b23188
> GV: 83.0a1-20201001094020
> AS: 63.0.0
> 
> Sunday 10/4 @ 5:11

Just updated and verified again. Killed the process after quitting the browser and did clear cache from the android apps menu which was the pre condition for the issue happening before. Regardless the pwa loads properly
