### ISSUE TITLE
FNX-4403 ⁃ [Feature request] Add a zoom bubble when selecting text

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10593] opened 2020-05-12 13:19 UTC
### Why/User Benefit/User Problem
When selecting the text it gets covered by the finger that makes it harder to know what exactly is being selected. So if something like a zoom bubble is there then user can see exactly where, what and how much of the text is being selected.

### Acceptance Criteria (how do I know when I’m done?)
![Screenshot](https://user-images.githubusercontent.com/42088907/81695983-e21cf880-9452-11ea-853c-de92823044de.jpg)UNITO-UNDERSCORE!20200512!UNITO-UNDERSCORE!184009!

**Comment by SS1113** [comment] 2020-05-12 13:25
Duplicate of #3510. Didn't notice it earlier, I tried searching but didn't find similar issues. I'm closing this issue.

**Closed** 2020-08-11 01:08 UTC
Labels: needs:triage
