### ISSUE TITLE
Odd disappearing character in url bar

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#817] opened 2019-03-04 06:29 UTC
## Steps to reproduce
See this video: https://photos.app.goo.gl/kd9w38rSzDhgqfoK7

### Expected behavior
When I open the url bar, there isn't an odd disappearing cursor.

### Actual behavior
In addition to demonstrating #787 , after I go back from settings and I open the url bar, there is a cursor at the end of the search bar which disappears.

### Device information

* Android device: Galaxy S8
* Fenix version: This weekend's

**Comment by bsurd** [comment] 2019-03-12 12:46
I was able to reproduce this on a Samsung Galaxy Note 8 (Android 9).

#### Steps to reproduce:
 1. Open Fenix.
 2. Tap on the 3dot menu and select Settings.
 3. Go back and tap on the search bar.

#### Device information
* Reproducible on:
     * Samsung Galaxy Note 8 (9)
* Not reproducible on:
     * Nexus 5 (6.0.1)
     * Nexus 9 (7.1.1)
     * Samsung Galaxy 8 (8)
     * Samsung Galaxy Tab S3 (8)
     * Nexus 6P (8.1.0)
     * Google Pixel (9)
* Fenix version: 1.0.1910 (#10642115)

#### Notes:
* Following these steps the issue is reproducible 100% of the times, if I don't go into the Settings the issue never reproduces.
* Was not able to reproduce the issue on the other devices no matter what I tried.
* [Logcat](https://github.com/mozilla-mobile/fenix/files/2956804/log.txt)
![gif](https://user-images.githubusercontent.com/17178945/54200884-07bc1400-44d5-11e9-8ae6-fa3068f1815e.gif)

**Comment by vesta0** [comment] 2019-04-02 18:11
@sv-ohorvath please verify this has been fixed.

**Comment by bsurd** [comment] 2019-04-03 11:23
Verified on the Note 8 and the issue is no longer reproducible. Closing the issue.

**Closed by bsurd** 2019-04-03 11:23 UTC
Labels: P1, QA needed, a-c, 🐞 bug
