### ISSUE TITLE
FNX-3359 ⁃ [Bug] Single home screen shortcut results in multiple tabs

### ISSUE THREAD

**Issue by ra-hardy** [mozilla-mobile/fenix#10212] opened 2020-04-25 12:58 UTC
## Steps to reproduce
Close any tabs or instances of Firefox.

1. Add a home screen shortcut for a website
1. Use the home screen shortcut to launch Firefox
1. Use the same shortcut to launch again
1. Launch Firefox from it's main icon and not a shortcut

### Expected behavior
In the main Firefox instance there should be one tab showing for the shortcut that was launched.

### Actual behavior
In Firefox, there are two tabs used for the same shortcut.
This is similar to #10210, but that is about the instances showing in the task switcher and not tabs.

### Device information
* Android device: Samsung Galaxy S10, Android 10, One UI 2.1
* Fenix version: 75.0.0-beta.6

**Comment by kbrosnan** [comment] 2020-04-26 19:08
duplicate of #5201

**Closed** 2020-08-10 19:38 UTC
Labels: needs:triage, 🐞 bug
