### ISSUE TITLE
RuntimeException: Error receiving broadcast Intent { act=mozilla.components.feature.downloads.OPEN flg=0x10 pkg=org...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#6436] opened 2019-11-04 16:54 UTC
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6599952/

```
ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://org.mozilla.fenix.nightly.fileprovider/Download/Download/null typ=application/vnd.android.package-archive flg=0x10000001 }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1792)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
    at android.app.ContextImpl.startActivity(ContextImpl.java:1433)
    at android.app.ContextImpl.startActivity(ContextImpl.java:1385)
    at android.content.ContextWrapper.startActivity(ContextWrapper.java:334)
...
(10 additional frame(s) were not displayed)

RuntimeException: Error receiving broadcast Intent { act=mozilla.components.feature.downloads.OPEN flg=0x10 pkg=org.mozilla.fenix.nightly (has extras) } in mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1@1150109f
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:927)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:210)
    at android.app.ActivityThread.main(ActivityThread.java:5839)
...
(4 additional frame(s) were not displayed)

Error receiving broadcast Intent { act=mozilla.components.feature.downloads.OPEN flg=0x10 pkg=org.mozilla.fenix.nightly (has extras) } in mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1@1150109f
```

**Comment by pocmo** [comment] 2019-11-04 16:55
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=mozilla.components.feature.downloads.OPEN flg=0x10 pkg=org.mozilla.fenix.nightly (has extras) } in mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1@1150109f
```

**Comment by pocmo** [comment] 2019-11-04 16:56
@sblatz That looks like it may be a regression from the downloads work?

**Comment by AndiAJ** [comment] 2019-11-07 12:24
Hi @pocmo reproducible on the latest **Nightly Build #13110606 from 7/11** using the following devices:
• Google Pixel 3a XL (Android 9)
• Pixel 2 (Android 9)
• Huawei Honor 8 (Android 7.0)

```Kotlin
 --------- beginning of crash
2019-11-07 14:15:38.002 30593-30593/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 30593
    java.lang.RuntimeException: Error receiving broadcast Intent { act=mozilla.components.feature.downloads.OPEN flg=0x10 pkg=org.mozilla.fenix.nightly (has extras) } in mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1@d0abd79
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://org.mozilla.fenix.nightly.fileprovider/Download/Download/null typ=application/msword flg=0x10000001 }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
        at android.app.ContextImpl.startActivity(ContextImpl.java:917)
        at android.app.ContextImpl.startActivity(ContextImpl.java:888)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1.onReceive(AbstractFetchDownloadService.kt:34)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-11-07 14:15:38.003 30593-30593/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.RuntimeException: Error receiving broadcast Intent { act=mozilla.components.feature.downloads.OPEN flg=0x10 pkg=org.mozilla.fenix.nightly (has extras) } in mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1@d0abd79, breadcrumbs=[Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Nov 07 14:14:14 GMT+02:00 2019), Breadcrumb(message=Changing to fragment historyFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Nov 07 14:14:25 GMT+02:00 2019), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Nov 07 14:14:26 GMT+02:00 2019)])
2019-11-07 14:15:38.003 30593-30593/? I/mozac/CrashReporter: Showing prompt
2019-11-07 14:15:38.009 1174-2853/? I/ActivityManager: START u0 {flg=0x10018000 cmp=org.mozilla.fenix.nightly/mozilla.components.lib.crash.prompt.CrashReporterActivity (has extras)} from uid 10184
2019-11-07 14:15:38.013 769-769/? d/android.hardware.power@1.3-service.bonito-libperfmgr: LAUNCH ON
2019-11-07 14:15:38.020 30593-30593/? I/Process: Sending signal. PID: 30593 SIG: 9
2019-11-07 14:15:38.024 1174-1198/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2019-11-07 14:15:38.025 1174-1198/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2019-11-07 14:15:38.060 30622-30848/? I/Gecko: Exiting due to channel error.
2019-11-07 14:15:38.076 1174-1354/? W/InputDispatcher: channel 'd45ef44 org.mozilla.fenix.nightly/org.mozilla.fenix.HomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2019-11-07 14:15:38.076 1174-1354/? E/InputDispatcher: channel 'd45ef44 org.mozilla.fenix.nightly/org.mozilla.fenix.HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-11-07 14:15:38.077 1174-4102/? I/WindowManager: WIN DEATH: Window{d45ef44 u0 org.mozilla.fenix.nightly/org.mozilla.fenix.HomeActivity}
2019-11-07 14:15:38.078 1174-5091/? I/ActivityManager: Process org.mozilla.fenix.nightly (pid 30593) has died: fore TOP 
2019-11-07 14:15:38.078 1174-4102/? W/InputDispatcher: Attempted to unregister already unregistered input channel 'd45ef44 org.mozilla.fenix.nightly/org.mozilla.fenix.HomeActivity (server)'
2019-11-07 14:15:38.078 1174-1201/? W/libprocessgroup: kill(-30593, 9) failed: No such process
2019-11-07 14:15:38.078 1174-5091/? W/ActivityManager: Scheduling restart of crashed service org.mozilla.fenix.nightly/org.mozilla.fenix.downloads.DownloadService in 1000ms
2019-11-07 14:15:38.082 685-685/? I/Zygote: Process 30593 exited due to signal (9)
2019-11-07 14:15:38.103 1174-6207/? I/ActivityManager: Process org.mozilla.fenix.nightly:tab (pid 30622) has died: fore SVC 
2019-11-07 14:15:38.113 685-685/? I/Zygote: Process 30622 exited cleanly (0)
2019-11-07 14:15:38.115 30960-30960/? E/h.CrashReporte: Not starting debugger since process cannot load the jdwp agent.
2019-11-07 14:15:38.119 1174-1200/? I/ActivityManager: Start proc 30960:org.mozilla.fenix.nightly:mozilla.components.lib.crash.CrashReporter/u0a184 for activity org.mozilla.fenix.nightly/mozilla.components.lib.crash.prompt.CrashReporterActivity
`

**Comment by sblatz** [comment] 2019-11-07 16:00
@AndiAJ do you have steps to reproduce on this? :)

**Comment by AndiAJ** [comment] 2019-11-07 16:41
Sure! :)

1. Navigate to https://file-examples.com/index.php/sample-documents-download/sample-doc-download/
2. Download a file
3. From the Android task bar tap on the download confirmation notification

► Video
![20191107_183700](https://user-images.githubusercontent.com/51314259/68408464-1525bd00-018e-11ea-9cfc-96ca33203d2d.gif)

**Comment by sblatz** [comment] 2019-11-07 22:03
Awesome, this looks like it is actually a failed download, but is claimed to be completed. This should be fixed by https://github.com/mozilla-mobile/android-components/issues/4999

**Comment by cpeterso** [comment] 2019-11-07 22:28
GV bug for this crash: https://bugzilla.mozilla.org/show_bug.cgi?id=1594734

mozilla-mobile/android-components#4999 will be fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1594905.

**Comment by pocmo** [comment] 2019-11-08 08:59
@sblatz I think regardless of the download being completed/failed we have an issue in `openFile()`:
https://github.com/mozilla-mobile/android-components/blob/master/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L361-L377

For a bunch of files it can happen that there is just no application / activity that can open it. In that case `startActivity` will throw `ActivityNotFoundException` like in the stacktrace @AndiAJ  posted. We can either query package manager and ask it whether there's an activity that can handle the intent or just catch `ActivityNotFoundException`.
The quickest, most pragmatic choice for this error case is probably to just show an error toast.

**Comment by sblatz** [comment] 2019-11-08 16:49
Ah, thank you for the clarification on this, @pocmo! I'll dig into it :)

**Comment by sblatz** [comment] 2019-11-08 21:59
@brampitoyo what string should we use when a user does not have an app installed to open the file? 

I was thinking something along the lines of: "Cannot open file"

**Comment by brampitoyo** [comment] 2019-11-12 00:53
@sblatz Android natively shows a toast with “Can’t open file”:

<img width="360" src="https://user-images.githubusercontent.com/51007/68632421-57b31500-0553-11ea-889a-e66037271053.png">

So, we should also follow that example and show a toast above our URL bar:

<img width="360" src="https://user-images.githubusercontent.com/51007/68632448-70bbc600-0553-11ea-8fce-b2d907d903a4.png">

What should we say? What about something along the lines of “No application to open this file”. It’s more descriptive, but is it also more confusing? If that’s the case, then I agree with your suggestion: “Cannot open file”.

**Comment by sblatz** [comment] 2019-11-12 16:44
Now that https://github.com/mozilla-mobile/android-components/pull/5031 is merged, this should be testable in our next nightly :)

**Comment by sv-ohorvath** [comment] 2019-11-13 09:53
Still reproducing on Nightly 191113. Now also when tapping Open in the in-app notification of a completed download.
you can also try these files: 
- Download a zip file from https://www.thinkbroadband.com/download
- Or the tar.gz file from the assets of these builds: https://github.com/mozilla-lockwise/lockwise-addon/releases
- Or a .cia file from https://drive.google.com/file/d/1sC85X65g0B08JH05gzFgIsg-c6TqjbDK/view?usp=sharing

**Comment by sv-ohorvath** [comment] 2019-11-15 13:47
@sblatz The crash is fixed but there's no snackbar notification displayed if you tap open from the in-app notification. Will this: https://github.com/mozilla-mobile/fenix/issues/6436#issuecomment-552684301 be implemented?

**Comment by sblatz** [comment] 2019-11-16 00:30
Should be fixed by: https://github.com/mozilla-mobile/fenix/pull/6648

**Comment by softvision-miralobontiu** [comment] 2019-11-25 15:10
Verified as fixed on the latest Nightly build from 11/25 with Google Pixel 3 (Android Q), and Huawei P9 Lite (Android 7).

**Closed by softvision-miralobontiu** 2019-11-25 15:10 UTC
Labels: E3, Feature:Download, S2, b:crash, eng:qa:needed, needs:strings, 🐞 bug
