### ISSUE TITLE
Home screen behind awesomebar does not return to website on back press

### ISSUE THREAD

**Issue by czlucius** [mozilla-mobile/fenix#23890] opened 2022-02-22 15:45 UTC
### Steps to reproduce

1. Open a website (e.g. https://Wikipedia.org)
2. Tap on the awesomebar
3. Press the back button/perform the back gesture

### Expected behaviour

It should return to the website.

### Actual behaviour

It just closes the keyboard with the home screen still open. Another back press exits the app. The user will have to press "Jump back in" to get back to the new tab, and this bug is exacerbated in Private Mode, where no "Jump back in" button is available.

### Device name

Samsung Galaxy S20 FE 5G 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1 (Build #2015864619)

### Device logs

N/A

### Additional information

This does not occur on Release.

**Comment by LaurentiuApahideanSV** [comment] 2022-02-23 14:11
I can confirm the issue is reproducible on Nightly 2022-02-23. The issue has also been reported here: https://github.com/mozilla-mobile/fenix/issues/23735. I will close this issue as duplicate.

### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android 9)

**Closed by LaurentiuApahideanSV** 2022-02-23 14:11 UTC
Labels: 🐞 bug, needs:triage
