### ISSUE TITLE
Crash in [@ android.app.RemoteServiceException: at android.app.ActivityThread$H.handleMessage(ActivityThread.java)]

### ISSUE THREAD

**Issue by valenting** [mozilla-mobile/fenix#17848] opened 2021-02-05 07:54 UTC
Crash report: https://crash-stats.mozilla.org/report/index/bbb274c3-2041-434f-a163-bef0f0210204

Java stack trace:
```
android.app.RemoteServiceException
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Happened about once a day in the past week.
I usually have a YouTube video playing when a notification comes in, or I pull down the notification bar. Then it crashes.

**Comment by hwinnemoe** [comment] 2021-02-05 13:10
Related to/Duplicate of #17848

**Comment by rocketsroger** [comment] 2021-02-08 21:14
Still couldn't reproduce but the steps to reproduce does give me an idea.  I'll try to land a fix and monitor to see if it lowers the crash rate.

**Closed** 2021-09-04 21:24 UTC
Labels: wontfix
