### ISSUE TITLE
[Bug] Keepass2android password auto fill not popping up

### ISSUE THREAD

**Issue by sophiekuehn** [mozilla-mobile/fenix#14635] opened 2020-09-02 19:35 UTC
## Steps to reproduce
Set up Keepass2android as the default auto fill service in android settings. Open a database and access access a login form in Firefox to be filled out automatically. 

### Expected behavior
KeePass auto fill popup pops up 

### Actual behavior
Nothing happens. 

### Device information

* Android device: Samsung Galaxy S7
* Fenix version: 79.0.5

**Comment by Dunexus** [comment] 2020-09-03 08:51
Duplicate of https://github.com/mozilla-mobile/fenix/issues/14633

**Closed** 2020-09-10 00:29 UTC
Labels: needs:triage, 🐞 bug
