### ISSUE TITLE
[Bug] Firefox Beta 5 V.89 Freezes phone

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#19470] opened 2021-05-11 16:14 UTC
Phone is freezing when using Firefox Beta 5 V.89,
Actually when I open keyboard to reply anyone through Firefox phone freezes, I cannot even switch off or lock the phone... It is happening to me with Firefox only... Not only on opening keyboard it sometimes freezes on zooming in web pages.... 

After 5-6 mins when it became normal I also cleared data of Firefox and after some hours I faced this issue again on zooming in web pages.... This time it got struck for 10-11 mins...

Steps to reproduce this issue :

Open Firefox Beta 5 (V.89),
Open any website like Twitter or realme Community,
Then create a new tweet or reply someone...
It will take too long to open keyboard or it will freeze the screen... And you can also do this on Instagram.... Just open instagram.com then open any story or play any video it will freeze for some time... 

And when it freezes the whole phone?
I was replying someone on realme community then web page got zoomed in by mistake then phone freezes...

Android Version : 10
FireFox version : 89.0.0-beta 5

**Comment by kbrosnan** [comment] 2021-05-11 16:24
It would be helpful to get a [profile of this behavior](https://profiler.firefox.com/docs/#/./guide-remote-profiling).

**Comment by Androiduser-7** [comment] 2021-05-11 16:53
> It would be helpful to get a [profile of this behavior](https://profiler.firefox.com/docs/#/./guide-remote-profiling).

I don't have a PC🙃

**Comment by zivian** [comment] 2021-05-17 10:32
@ ghost my simple irrelevant question (out of curiousity)
do u have google play store app on your mobile?

**Comment by zivian** [comment] 2021-05-17 10:33
@ghost 

my simple irrelevant question (out of curiousity)

do u have google play store app on your mobile?

**Comment by zivian** [comment] 2021-05-17 10:36
@kbrosnan out of curiousity, please excuse my behavior

do we have data about how much percentage of fenix stable, beta and nightly have pre-installed google play services And store on their mobiles?

**Comment by lobontiumira** [comment] 2021-06-30 13:18
@ghost, are you experiencing these behaviours on the latest Firefox Beta lately?
I've tested on the 90.0.0-beta.6 build with Google Pixel (Android 10), and everything worked as expected.

Thanks!

**Comment by sflorean** [comment] 2021-12-29 14:00
Closing this due to the fact that is not reproducible on our side and lack of extra information. Please reopen if the issue occurs again. Thank you!

**Closed by sflorean** 2021-12-29 14:00 UTC
Labels: 🐞 bug, b:anr, Feature:Browsing, needs:triage, wontfix, qa-triaged
