### ISSUE TITLE
Add Bookmarks and not recently items in the home page

### ISSUE THREAD

**Issue by heberjeur** [mozilla-mobile/fenix#24832] opened 2022-04-17 10:33 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
When I want to open to a specific bookmark page I need to do 4-5 clicks, chrome for example needs 2 clicks !
### How do you know that this problem exists today? Why is this important?
As a user, I want my browser homescreen to show me content that is most relevant and useful to me.
### Who will benefit from it?
I don't want to access recently bookmarks from the home page, I want my bookmarks to be a separate items in the home page. So for me to access quickly to bookmarks are critical.

**Comment by marcel263** [comment] 2022-04-17 18:09
Please try "show all", then search for the bookmarks. This is available at least in the development version of the browser (Nightly). 3 taps maximum.

**Comment by heberjeur** [comment] 2022-04-17 22:27
Yes, I try it, but I have many bookmarks inside folders, before I can do it with few clicks, even chrome is simpler than Firefox now.

**Comment by marcel263** [comment] 2022-04-18 04:56
> Yes, I try it, but I have many bookmarks inside folders, before I can do it with few clicks, even chrome is simpler than Firefox now.

Then don't use folders, of course folders cause you to need more clicks, which would be true for any browser. You may also use the Search icon in the top right. This works with Firefox Beta and Nightly. In such a way, you have 3 clicks to find what you need.

**Comment by DavidJCobb** [comment] 2022-04-30 17:06
Maybe duplicate of #23227, #10050, and a few others I can't seem to find right now.

**Closed** 2022-05-17 16:25 UTC
Labels: needs:triage
