### ISSUE TITLE
Move active search field to bottom

### ISSUE THREAD

**Issue by wiwie** [mozilla-mobile/fenix#3993] opened 2019-07-11 04:40 UTC
### Why/User Benefit/User Problem
Currently the active search text field is placed on top and search suggestions underneath. This does not allow one handed editing of the URL (placing the cursor) or pressing the delete button.

### What/Requirements
Place the active search text field on the bottom and search suggestions above it.

### Acceptance Criteria (how do I know when I’m done?)
The active search text field is placed at the bottom in the same place as the "inactive" one.

**Comment by 3v1n0** [comment] 2019-08-24 09:43
I agree going back and down isn't accessible, so also results should be shown in an inverted order, bottom to top.

**Comment by rmbq** [comment] 2019-11-12 11:11
Totally agree, i made some (very bad) screenshot 
![photo_2019-11-12_11-49-17](https://user-images.githubusercontent.com/2061140/68667082-70b4c980-0545-11ea-8ad4-008cb05463e1.jpg)
![fenix_search](https://user-images.githubusercontent.com/2061140/68667094-76121400-0545-11ea-9ef0-0b672984fd36.jpg)
![photo_2019-11-12_11-49-24](https://user-images.githubusercontent.com/2061140/68667103-790d0480-0545-11ea-9414-c1e397135891.jpg)
![fenix_addr](https://user-images.githubusercontent.com/2061140/68667105-7a3e3180-0545-11ea-9776-031b96c50d1d.jpg)

**Comment by kbrosnan** [comment] 2020-01-12 18:33
Dupe of #7461 where more discussion happened.

**Closed by kbrosnan** 2020-01-12 18:33 UTC
Labels: Feature:HomeScreen, Feature:Search, 🌟 feature request
