### ISSUE TITLE
Add option to keep toolbar persistent

### ISSUE THREAD

**Issue by dbenjaminmiller** [mozilla-mobile/fenix#13359] opened 2020-08-06 19:23 UTC
This is a feature from Fennec. The user can choose to not hide the toolbar when scrolling down. Some users prefer the toolbar to remain in place, and this could potentially improve accessibility for some users.

**Comment by s-ankur** [comment] 2020-08-06 19:25
Duplicate of #10240

**Closed** 2020-08-06 19:33 UTC
Labels: needs:triage
