### ISSUE TITLE
[Bug] Fennec 81.1.5 don't show added custom search providers

### ISSUE THREAD

**Issue by ovz93br43v7** [mozilla-mobile/fenix#16046] opened 2020-10-20 05:30 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce / ### Actual behavior
Install Fennec from F-Droid
go to settings and then to search
add for example Name: "Metager", search-string: "https://metager.de/meta/meta.ger3?eingabe=%s"
click on OK
Pop-up is shown "metager created"
But "metager" don't show up in the list of the search providers

I tired it again with "metager" then I get the message that "metager" already exists.
I tired also other search providers like "Startpage", but same result no custom search provider gets in the list. 
I also tired to clear app cache and memory but this don't change the behavior.  

### Expected behavior
Install Fennec from F-Droid
go to settings and then to search
add for example Name: "Metager", search-string: "https://metager.de/meta/meta.ger3?eingabe=%s"
click on OK
Pop-up is shown "metager created"
Select "metager" as standard search provider from the list of search providers

### Device information

* Android device: Google Pixel 3
* Fennec version: 81.1.5 (Build #811520)

**Comment by liuche** [comment] 2020-10-22 01:33
Dupe of #15892 and should be fixed in Nightly, Beta, and release.

**Closed by liuche** 2020-10-22 01:33 UTC
Labels: needs:triage, 🐞 bug
