### ISSUE TITLE
System-wide share sheet for Sync missing in FF 80+

### ISSUE THREAD

**Issue by frumble** [mozilla-mobile/fenix#14643] opened 2020-09-02 21:21 UTC
Until recently, Firefox has featured a system-wide share sheet for sending links via Firefox Sync from apps like your Twitter client right to your desktop computer or tablet. This was an essential part of the workflow of many users.
In Firefox for Android 80, this feature is gone.
For me, it’s more like a bug, but I’m wise enough to know that the development process has been more concerned of the big features so far – hence I file it as a feature request. Which it is not, it is a key function missing in Firefox Daylight.

**Comment by Dunexus** [comment] 2020-09-03 10:07
Duplicate of https://github.com/mozilla-mobile/fenix/issues/1523

**Comment by liuche** [comment] 2020-09-10 00:33
Thanks for filing - please follow aloing in #1523

**Closed by liuche** 2020-09-10 00:33 UTC
Labels: needs:triage
