### ISSUE TITLE
FNX3-16953 ⁃ [Bug] downloads from Firefox Send don't work

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#3336] opened 2019-06-11 11:41 UTC
* [ ] Being investigated in GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1432949#c22

### Steps to reproduce
1. upload a file to send.firefox.com
1. copy the download URL
1. open the download URL
1. press the "Download" button
1. confirm that you want to download the file

### Expected behavior
Fenix downloads the file.

### Actual behavior
There is an Android notification:

```
<Untitled>
Download unsuccessful.
```

Not only that the download fails, also the "Untitled" is… interesting.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 4d82c297432e0f86d54e2d3496e0654bbb36a447

**Comment by kbrosnan** [comment] 2019-06-12 18:28
Expect that this is similar or dupe of #1657

**Comment by cadeyrn** [comment] 2019-08-03 08:21
I can verify that downloading from Firefox Send works with the new Gecko based download manager.

**Comment by jimbo1qaz** [comment] 2019-08-04 01:22
On master 4fc4759e, I tried uploading and downloading from Firefox Send. The download succeeded with the right filename, but I instead got a 12-byte file containing `Unauthorized`.

**Comment by cadeyrn** [comment] 2019-08-04 06:45
Oh, you're right. I have only tested if the download works but I didn't open the file. I can confirm that Fenix downloaded a useless 12 byte file. :(

Since #1657 didn't fix this - can this issue be reopened, please?

**Comment by NotWoods** [comment] 2019-08-04 20:48
Looks like Firefox Send just returns the "Unauthorized" response to Fenix everytime, no matter the downloading system we use. I'll follow up with their team during the week.

Adding the "needs:gv" label in case GeckoView messes with Firefox Send somehow.

**Comment by jimbo1qaz** [comment] 2019-08-04 20:52
How about trying a TLS MITM and downloading from Firefox Send, to see if there's any errors in the packets and HTTP headers? (or maybe logging packet headers in the app rather than in packet capture)

**Comment by cpeterso** [comment] 2019-08-29 07:28
GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1572813

Firefox Send breaks in Fenix due to a compat issue with Gecko Service Workers, possibly related to e10s in GV.

In the GV bug, Tiger wrote:
> If GeckoView has the same behaviour then the Send team can whitelist it like Safari.

Should the Send team temporarily whitelist Fenix until we fix this GV bug? To whitelist Fenix but not Fennec, Send can check the User-Agent string:

Gecko version <= 68 is Fennec.
Gecko version >= 69 is Fenix.

**Comment by NotWoods** [comment] 2019-08-29 12:34
I've asked the Send team to whitelist Fenix for now.

**Comment by cadeyrn** [comment] 2019-09-25 18:27
@NotWoods 

> I've asked the Send team to whitelist Fenix for now.

It's still an issue. Was there any feedback from the Send team?

Would be really great if the problem could be solved. Not because Firefox Send is such an important service but because Firefox services should work in Firefox browsers at least, I guess. ;-)

**Comment by NotWoods** [comment] 2019-09-25 18:42
Firefox Send is planning to fix this issue. I'll see if there's an issue I can link to here.

**Comment by NotWoods** [comment] 2019-09-25 19:21
Filed mozilla/send#1404. Send tried to fix the issue already but that didn't work out, so we need to investigate more.

**Comment by cpeterso** [comment] 2019-09-25 19:50
> Filed [mozilla/send#1404](https://github.com/mozilla/send/issues/1404). Send tried to fix the issue already but that didn't work out, so we need to investigate more.

@NotWoods , does "we need to investigate more" mean the Send team, the Fenix team, or the GV team? 😅

**Comment by NotWoods** [comment] 2019-09-25 21:16
Honestly I have no clue where the issue is now. 🙂

I left instructions for the Send team to debug since they know how the product works the best.

**Comment by cpeterso** [comment] 2019-11-11 23:05
TBD whether this fix requires a Service Workers fix in Gecko.

**Comment by bashims** [comment] 2020-02-15 16:57
Having the same or similar problem. See the screenshots attached.

Version: Firefox Preview 3.0 nightly 200215 06:00

**Comment by cat-in-136** [comment] 2020-04-17 10:33
Umm. Today, decryption seems to work well. I doubt that Fenix is not able to download files from the URL of the blob where the decrypted data is stored.

**Comment by liuche** [comment] 2020-05-05 17:02
@kglazko Have a look at these and the other linked bugs, maybe they give some more insight into STRs for some downloads problems or paths to look into?

**Comment by liuche** [comment] 2020-05-14 18:30
Should take a look into whether or not this is a Firefox Send issue, or another Downloads issue.

**Comment by Amejia481** [comment] 2020-05-15 13:59
> Should take a look into whether or not this is a Firefox Send issue, or another Downloads issue, like a spike.
It is being investigated in the gv bug https://bugzilla.mozilla.org/show_bug.cgi?id=1432949#c22

**Comment by kglazko** [comment] 2020-05-20 22:05
I noticed that the issue was resolved in Bugzilla 31 minutes ago, does this mean this ticket will be addressed? @Amejia481

**Comment by Amejia481** [comment] 2020-05-20 22:09
> I noticed that the issue was resolved in Bugzilla 31 minutes ago, does this mean this ticket will be addressed? @Amejia481

We need to test with the latest GV version

**Comment by Amejia481** [comment] 2020-05-25 02:09
This should be fixed on master, QA please help us to verify, thanks in advance.

**Comment by Amejia481** [comment] 2020-05-25 14:52
It looks like the new AC version hasn't being updated, we need this version to land first https://github.com/mozilla-mobile/fenix/pull/10820

**Comment by Amejia481** [comment] 2020-05-26 14:24
Now the new version of ac has landed we are ready to test!

**Comment by softvision-miralobontiu** [comment] 2020-05-27 09:14
Verified as fixed on the latest Nightly build from 5/27 with Google Pixel (android 10), and Sony Xperia Z5 Premium (Android 7.1.1).

**Closed** 2020-08-11 14:29 UTC
Labels: E3, Feature:Download, P2, eng:qa:verified, 🐞 bug
