### ISSUE TITLE
[Android] Option to close tabs on app close not persist sessions on (automated option to not persist session on app close)

### ISSUE THREAD

**Issue by Oleophobic** [mozilla-mobile/fenix#21818] opened 2021-10-09 03:26 UTC
### How do you know that this problem exists today? Why is this important?
We are required to perform repetitive tasks since the 2020 update adding barriers to app launch and exit experience because now we are required to go into a menu and click an option to close the sessions which there is now no option to automate, browsing is done multiple times a so day keeping every prior session for a day is not useful because pages and firefox will load slowly along with every other tab from the previous session, private browsing will not save logins and website cookies so that is not a solution. I close the app intentionally and this is a nightmare for people like me i had to go to edge on mobile because this has affected the entire functionality i had used firefox for. 

### Who will benefit from it?
People people with physical and intellectual disabilities
This is not asking to change the behaviour for every user, simply for those who will want/ need this.

**Comment by DavidJCobb** [comment] 2021-11-01 12:32
Duplicate of #5865 and #22064?

**Closed** 2022-05-09 16:18 UTC
Labels: needs:triage, wontfix
