### ISSUE TITLE
[Bug]: "Zoom on all websites" option enabled breaks the video ration on twitter.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/fenix#24076] opened 2022-03-03 14:26 UTC
### Preconditions:
"Zoom in on all websites" option activated from the "Accessibility" section of the browser's settings.

### Steps to reproduce

1. Navigate to: https://mobile.twitter.com/cctv_idiots.
2. Play a video.
3. Pinch to zoom in.
4. Observe the result.

### Expected behaviour

The video aspect ratio fits the page when zoomed in.

### Actual behaviour

The video aspect ratio breaks when the page is zoomed in.

### Device name

Samsung A51 -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 99.0a1 (2015866539 -🦎99.0a1-20220302065857🦎)

### Additional information

Screen recording attached:

![pinch to zoom in](https://user-images.githubusercontent.com/75027050/156583943-8005a157-fe31-4ec5-b329-1bd8ff4baace.gif)

**Comment by amocirean** [comment] 2022-04-28 13:23
Hello!
I was not able to reproduce the issue on latest RC (101.1.0) or Latest Nightly 101.0a1 (2022-04-28).
Does the issue still occur on the latest RC/Nightly on your device?

- Android Version: 11
- Devices Used: Xiaomi Mi 11 Lite

**Comment by softvision-raul-bucata** [comment] 2022-04-28 14:48
@amocirean I can confirm that the issue is no longer reproducible.


**Tested with:**

Browser / Version: Firefox Nightly 101.0a1 (2015876907 -🦎101.0a1-20220425094217🦎)
Operating System: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
Operating System: Google Pixel 3 (Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)





[inv_17/2022]

**Comment by sflorean** [comment] 2022-05-05 11:58
I will close this issue based on the above comment. Feel free to re-open/ leave a comment if the issue reappears. Thank you!

**Closed by sflorean** 2022-05-05 11:58 UTC
Labels: 🐞 bug, Feature:Media, S3, needs:triage, qa-triaged
