### ISSUE TITLE
FNX-12920 ⁃ [Bug] [Crash] TabsTray: IllegalStateException initialInfo must not be null

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#11919] opened 2020-06-24 20:33 UTC
Quite a few of these in Sentry with different signatures:

https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8876915/
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8880252/
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8876643/
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8872872/
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8876654/
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8871375/

**Comment by ekager** [comment] 2020-06-24 21:04
cc @mcarare could you take a followup look at this?

**Comment by hakkikaancaliskan** [comment] 2020-06-24 21:24
Duplicate of #11901
Fix pr #11904

**Comment by ekager** [comment] 2020-06-24 21:53
Ah nice! Closing for #11901

**Closed** 2020-08-11 05:14 UTC
Labels: Feature:Tabs, Skittle, b:crash, 🐞 bug
