### ISSUE TITLE
ability to reorder bookmarks, top sites atleast before the end of next year.

### ISSUE THREAD

**Issue by rocky-01** [mozilla-mobile/fenix#17161] opened 2020-12-21 11:59 UTC
No one likes these features 😂
No one use these features 😃
No browser on Android has these features. 😄

**Comment by cadeyrn** [comment] 2020-12-21 12:10
Duplicate of #4348 for bookmarks.
Duplicate of #8305 for top sites.

**Comment by mcarare** [comment] 2020-12-21 12:20
Closing as duplicate.

**Closed by mcarare** 2020-12-21 12:20 UTC
Labels: needs:triage
