### ISSUE TITLE
[Bug] biblioteca.cubxity.dev - Unable to view bottom content

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#10724] opened 2020-05-18 08:29 UTC
## Steps to reproduce
1. Go to https://biblioteca.cubxity.dev/book?id=1
1. Scroll down

### Expected behavior
See the bottom of the page

### Actual behavior
Can't see the bottom of the page, multiple scroll action, increment the bottom with small steps. After 5 to 10 of them we can finally reach the bottom.

### Device information
* Android device: Pixel 2 android 10
* Fenix version: Gv 78.0a1 May 17.

initially reported on https://github.com/webcompat/web-bugs/issues/52907

**Comment by LaurentiuApahideanSV** [comment] 2020-05-18 09:32
I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 200518 (Build #21390610).

Devices:
OnePlus 6T (Android 9);
Huawei MediaPad M3 lite 10 (Android 7.0)

**Comment by collares** [comment] 2020-05-22 16:30
Probable dupe of #10780

**Closed** 2021-03-04 01:14 UTC
Labels: S2, wontfix, 🐞 bug
