### ISSUE TITLE
Debug build crashes at startup on older devices

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/fenix#17920] opened 2021-02-08 18:59 UTC
## Steps to reproduce

Install latest debug build from https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.debug.latest/arm64-v8a

Crash:

```
02-08 10:56:02.185 21990 21990 E AndroidRuntime: FATAL EXCEPTION: main
02-08 10:56:02.185 21990 21990 E AndroidRuntime: Process: org.mozilla.fenix.debug, PID: 21990
02-08 10:56:02.185 21990 21990 E AndroidRuntime: java.lang.RuntimeException: StrictMode ThreadPolicy violation
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1768)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$handleViolationWithTimingAttempt$0$StrictMode$AndroidBlockGuardPolicy(StrictMode.java:1687)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.os.-$$Lambda$StrictMode$AndroidBlockGuardPolicy$9nBulCQKaMajrWr41SB7f7YRT1I.run(Unknown Source:6)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: Caused by: android.os.strictmode.DiskReadViolation
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1524)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1193)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:165)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:152)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:271)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at com.android.server.enterprise.storage.EdmStorageProviderBase.getValues(EdmStorageProviderBase.java:388)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at com.android.server.enterprise.storage.EdmStorageProviderBase.getValuesList(EdmStorageProviderBase.java:1104)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at com.android.server.enterprise.storage.EdmStorageProvider.getValuesList(EdmStorageProvider.java:300)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at com.android.server.enterprise.application.ApplicationPolicy.getApplicationStateEnabledAsUser(ApplicationPolicy.java:3745)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at com.android.server.enterprise.application.ApplicationPolicy.getApplicationStateEnabledAsUser(ApplicationPolicy.java:3714)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:26031)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.setComponentEnabledSetting(PackageManagerService.java:26007)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3774)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5145)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1056)
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1029)
```

### Device information

* Device vendor / model and Android version: Samsung S10e, Android 10

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9672)

**Comment by mcomella** [comment] 2021-02-08 22:10
To be explicit, the performance team is not planning to address this issue but I'm adding it to our board to track it (because StrictMode failures are indicative of performance issues). Please prioritize this issue!

**Comment by mcomella** [comment] 2021-02-08 22:18
The stack trace isn't clear what's actually causing this issue.

Some reasons StrictMode violations may sneak into master builds:
- OEMs create StrictMode failures that local testers do not see due to their device selection
- Local testers do not have certain SDKs enabled locally (e.g. Firebase push) so the code that executes them doesn't get tested under StrictMode

We could consider enabling StrictMode in Nightly builds to get better tester coverage on these issues and identify the most prominent StrictMode errors in crash reporting.

**Comment by mcomella** [comment] 2021-02-08 22:28
agi can only reproduce on the S10e, not the S7. I know Samsung has some special enterprise functionality and the trace implies this may be related:
```
02-08 10:56:02.185 21990 21990 E AndroidRuntime: 	at com.android.server.enterprise.storage.EdmStorageProviderBase.getValues(EdmStorageProviderBase.java:388)
```

Since it doesn't seem to be occurring asynchronously (i.e. not due to a method we called), we may need to do some blanket fix (e.g. create a allowlist of StrictMode violations [like in this article](https://medium.com/@tokudu/how-to-whitelist-strictmode-violations-on-android-based-on-stacktrace-eb0018e909aa).

**Comment by oatastemur** [comment] 2021-02-08 23:39
I had the same problem when debugging a different issue on my Galaxy S10e: https://github.com/mozilla-mobile/fenix/issues/17612#issuecomment-766785195

If you need to run the Debug build you can disable StrictMode by changing a line in the source code.

**Comment by mcomella** [comment] 2021-02-09 00:47
I see the same StackTrace in this issue: https://github.com/mozilla-mobile/fenix/issues/15430#issuecomment-699192045 We fixed it for a very particular case but it doesn't seem to apply to what agi's experiencing – maybe there was an OS upgrade. It looks like it applies to Galaxy A50, Galaxy Note 10, and LG G7 FIT.

When we address this, we may be able to back out the fixes for those issues.

**Comment by mcomella** [comment] 2021-02-09 01:12
I ended up trying to write a patch using `penaltyListener` for P+ but it doesn't seem to work properly. I think `penaltyListener` stops working after we call `resetAfter` but I'm not quite sure why. I think this because I can cause a StrictMode violation to fail if I create one inside of `StrictModeManager.enableStrictMode` but I can't in `HomeActivity.onCreate`.

**Comment by mcomella** [comment] 2021-02-09 01:22
> I ended up trying to write a patch using penaltyListener for P+ but it doesn't seem to work properly. I think penaltyListener stops working after we call resetAfter but I'm not quite sure why.

It seems to be caused by `attachListenerToDisablePenaltyDeath` but unclear why the listener is affected but `penaltyDeath` is not.

**Comment by mcomella** [comment] 2021-02-09 01:39
Got something working locally – let's check with agi if it's working.

**Comment by mcomella** [comment] 2021-02-09 22:25
It works for agi. I refactored a bit since we tested but I don't think I broke anything so I'm just going to push.

**Comment by mcomella** [comment] 2021-02-09 22:27
PR: https://github.com/mozilla-mobile/fenix/pull/17939

**Comment by mcomella** [comment] 2021-02-11 23:23
This should be addressed with https://github.com/mozilla-mobile/fenix/commit/b41041c7397bd0a483e095d5902d943c47d8c648

**Comment by mcomella** [comment] 2021-02-11 23:28
QA: can you validate that, in a debug build, the app doesn't crash on start up on the Galaxy S10e?

Furthermore, my fix for this bug may have addressed https://github.com/mozilla-mobile/fenix/issues/16347 – can you test if the same crash occurs on these devices? Specifically, Samsung Galaxy Note10 (Android10) and LG G7 FIT (Android 8), and maybe the Galaxy A50. If it's fixed for these devices, can you close that bug too as a duplicate? Note: I only expect my fix to work on Android 9+ (so maybe not the LG G7 FIT).

**Comment by abodea** [comment] 2021-02-12 12:04
Note that I was able to reproduce this issue on the Samsung Galaxy S10+ (Android  10).
Also, note that I was not able to install the debug builds from [here ](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.debug.latest/arm64-v8a) as mentioned in the description and I've built from master.
It was a little bit hard to identify the crash-report as I couldn't access the app, getting a crash at startup all the time but I found it in the end and you can check it [here ](https://crash-stats.mozilla.org/report/index/fb427760-0c85-4996-a45a-091850210212#tab-annotations).
Based on my comment I will remove `eng:qa:needed` until further notice.

**Comment by mcomella** [comment] 2021-03-10 22:09
Triage: I already spent time on this and landed a solution but it didn't work in some cases. Neither Marc nor myself has a device to reproduce so it'd be time consuming to try to fix. It doesn't seem super high priority as the only case I've heard of that hits this is agi sharing debug builds to get info from users and no one else has hit this during development. As such, because this seems medium effort, low impact, we're going to set it as low impact/priority for the perf team. It should be fixable by any android dev who can reproduce though so it doesn't need our expertise

A workaround for local development is to disable strict mode.

**Comment by lobontiumira** [comment] 2021-04-06 12:11
I was able to reproduce the crash on Xiaomi Mi 8 Lite (Android 9), following these steps:
1. Install debug build with AC: 75.0.20210405143037, a69f74ece, and GV 89.0a1-20210405094633 on Xiaomi Mi 8 Lite (Android 9).
2. Open the app.

Fenix crashes.
```
2021-04-06 14:59:25.150 26001-26115/org.mozilla.fenix.debug E/GeckoLibLoad: Load sqlite start
2021-04-06 14:59:25.156 26001-26115/org.mozilla.fenix.debug E/GeckoLibLoad: Load sqlite done
2021-04-06 14:59:25.156 26001-26115/org.mozilla.fenix.debug E/GeckoLibLoad: Load nss start
2021-04-06 14:59:25.156 26001-26115/org.mozilla.fenix.debug E/GeckoLibLoad: Load nss done
2021-04-06 14:59:25.369 26001-26115/org.mozilla.fenix.debug E/GeckoLibLoad: Loaded libs in 211.891927ms total, 10ms(520ms) user, 30ms(90ms) system, 57(72) faults
2021-04-06 14:59:26.064 26001-26115/org.mozilla.fenix.debug E/GeckoConsole: [JavaScript Error: "NotFoundError: Could not open the file at /data/user/0/org.mozilla.fenix.debug/files/mozilla/s47n4k79.default/startupCache/webext.sc.lz4" {file: "resource://gre/modules/ExtensionParent.jsm" line: 1742}]
    _readData@resource://gre/modules/ExtensionParent.jsm:1742:12
2021-04-06 14:59:26.148 26001-26115/org.mozilla.fenix.debug E/GeckoConsole: [JavaScript Error: "Error: File resource://default-theme/ does not contain a valid manifest" {file: "resource://gre/modules/addons/XPIInstall.jsm" line: 669}]
2021-04-06 14:59:26.148 26001-26115/org.mozilla.fenix.debug E/GeckoConsole: [JavaScript Error: "Error: File resource://default-theme/ does not contain a valid manifest" {file: "resource://gre/modules/addons/XPIInstall.jsm" line: 669}]
2021-04-06 14:59:26.253 26001-26209/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: org.mozilla.fenix.debug, PID: 26001
    java.lang.RuntimeException: StrictMode ThreadPolicy violation
        at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.penaltyDeath(ThreadPenaltyDeathWithIgnoresListener.kt:44)
        at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.onThreadViolation(ThreadPenaltyDeathWithIgnoresListener.kt:38)
        at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$onThreadPolicyViolation$1(StrictMode.java:1719)
        at android.os.-$$Lambda$StrictMode$AndroidBlockGuardPolicy$FxZGA9KtfTewqdcxlUwvIe5Nx9I.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:815)
        at miui.util.TypefaceUtils.<clinit>(TypefaceUtils.java:327)
        at miui.util.TypefaceUtils.replaceTypeface(TypefaceUtils.java:557)
        at android.widget.TextView.replaceTypeface(TextView.java:3937)
        at android.widget.TextView.setTypeface(TextView.java:3926)
        at android.widget.TextView.setTypeface(TextView.java:2147)
        at androidx.appcompat.widget.AppCompatTextView.setTypeface(AppCompatTextView.java:711)
        at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2037)
        at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2008)
        at android.widget.TextView.applyTextAppearance(TextView.java:3647)
        at android.widget.TextView.<init>(TextView.java:1498)
        at android.widget.TextView.<init>(TextView.java:869)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:100)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
        at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:194)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:115)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1551)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1602)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at org.mozilla.fenix.perf.PerformanceInflater.inflate(PerformanceInflater.kt:42)
        at org.mozilla.fenix.home.HomeFragment$onCreateView$1.invoke(HomeFragment.kt:199)
        at org.mozilla.fenix.home.HomeFragment$onCreateView$1.invoke(HomeFragment.kt:130)
        at org.mozilla.fenix.ext.GleanKt.measureNoInline(Glean.kt:23)
        at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:198)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
2021-04-06 14:59:26.255 26001-26209/org.mozilla.fenix.debug E/AndroidRuntime:     at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at org.mozilla.fenix.HomeActivity.access$onStart$s-594849490(HomeActivity.kt:127)
        at org.mozilla.fenix.HomeActivity$onStart$1.invoke(HomeActivity.kt:339)
        at org.mozilla.fenix.HomeActivity$onStart$1.invoke(HomeActivity.kt:127)
        at org.mozilla.fenix.ext.GleanKt.measureNoInline(Glean.kt:23)
        at org.mozilla.fenix.HomeActivity.onStart(HomeActivity.kt:338)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
        at android.app.Activity.performStart(Activity.java:7252)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2970)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2021-04-06 14:59:26.263 26001-26001/org.mozilla.fenix.debug E/libc: Access denied finding property "ro.serialno"
2021-04-06 14:59:26.280 26001-26209/org.mozilla.fenix.debug E/ExceptionHandler: Uncaught exception handled: 
    java.lang.RuntimeException: StrictMode ThreadPolicy violation
        at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.penaltyDeath(ThreadPenaltyDeathWithIgnoresListener.kt:44)
        at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.onThreadViolation(ThreadPenaltyDeathWithIgnoresListener.kt:38)
        at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$onThreadPolicyViolation$1(StrictMode.java:1719)
        at android.os.-$$Lambda$StrictMode$AndroidBlockGuardPolicy$FxZGA9KtfTewqdcxlUwvIe5Nx9I.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:815)
        at miui.util.TypefaceUtils.<clinit>(TypefaceUtils.java:327)
        at miui.util.TypefaceUtils.replaceTypeface(TypefaceUtils.java:557)
        at android.widget.TextView.replaceTypeface(TextView.java:3937)
        at android.widget.TextView.setTypeface(TextView.java:3926)
        at android.widget.TextView.setTypeface(TextView.java:2147)
        at androidx.appcompat.widget.AppCompatTextView.setTypeface(AppCompatTextView.java:711)
        at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2037)
        at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2008)
        at android.widget.TextView.applyTextAppearance(TextView.java:3647)
        at android.widget.TextView.<init>(TextView.java:1498)
        at android.widget.TextView.<init>(TextView.java:869)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:100)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
        at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:194)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:115)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1551)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1602)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at org.mozilla.fenix.perf.PerformanceInflater.inflate(PerformanceInflater.kt:42)
        at org.mozilla.fenix.home.HomeFragment$onCreateView$1.invoke(HomeFragment.kt:199)
        at org.mozilla.fenix.home.HomeFragment$onCreateView$1.invoke(HomeFragment.kt:130)
        at org.mozilla.fenix.ext.GleanKt.measureNoInline(Glean.kt:23)
        at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:198)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
2021-04-06 14:59:26.280 26001-26209/org.mozilla.fenix.debug E/ExceptionHandler:     at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at org.mozilla.fenix.HomeActivity.access$onStart$s-594849490(HomeActivity.kt:127)
        at org.mozilla.fenix.HomeActivity$onStart$1.invoke(HomeActivity.kt:339)
        at org.mozilla.fenix.HomeActivity$onStart$1.invoke(HomeActivity.kt:127)
        at org.mozilla.fenix.ext.GleanKt.measureNoInline(Glean.kt:23)
        at org.mozilla.fenix.HomeActivity.onStart(HomeActivity.kt:338)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
        at android.app.Activity.performStart(Activity.java:7252)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2970)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

[logcat Xiaomi.txt](https://github.com/mozilla-mobile/fenix/files/6264500/logcat.Xiaomi.txt)

**Comment by AaronMT** [comment] 2023-01-10 22:00
Still an issue, and same problem on a starqlteue (S9, API 26) [at least confirmed from attempting an instrumented run on Firebase Test Lab) (01/10 debug ARM builds)

**Comment by boek** [comment] 2023-01-31 16:24
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814129

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-31 16:24 UTC
Labels: 🐞 bug, performance
