### ISSUE TITLE
local ipv6 addresses not recognized

### ISSUE THREAD

**Issue by lufebe16** [mozilla-mobile/fenix#15779] opened 2020-10-08 09:47 UTC
I'm accessing an own webservice on the local lan. The server is reachable at fix addresses 192.168.1.25 (ipv4) and fc01::105 (ipv6). In earlier versions of firefox (~68) I bookmarked: http://[fc01::105]:8082/image for it. On the newest version and even on the newest beta the call results in a weired google search result page, instead of the request service.

(On the newest beta an access was possible under the ipv4 local address, such as http://192.168.1.25:8082/image.).

This is a request to support local ipv6 addresses too.

**Comment by cadeyrn** [comment] 2020-10-08 09:53
Duplicate of #4343.

**Closed** 2020-10-21 22:52 UTC
Labels: needs:triage
