### ISSUE TITLE
[Bug]: Weird rendering on android 5

### ISSUE THREAD

**Issue by Emojigit** [mozilla-mobile/fenix#20323] opened 2021-07-11 04:28 UTC
### Steps to reproduce

Open a page in fexin on android 5

### Expected behaviour

All things should render smoothly

### Actual behaviour

There are some weird render result such as square and triangles at the edge of round elements
![Screenshot_2021-07-11-12-16-51](https://user-images.githubusercontent.com/55009343/125182772-662f6380-e243-11eb-98a9-6cd6cd3f94f8.png)
![Screenshot_2021-07-11-12-18-11](https://user-images.githubusercontent.com/55009343/125182775-6a5b8100-e243-11eb-88e6-27c090289b29.png)

### Device name

Sony Xperia

### Android version

Android 5

### Firefox release type

Firefox

### Firefox version

89.1.1

**Comment by jonalmeida** [comment] 2021-07-11 04:31
@Emojigit there isn't enough information to use in this issue unfortunately.

- Which Sony Xperia do you have?
- Can you share the version of Firefox you're currently running? You can find this in the About Firefox screen in Settings.

**Comment by Emojigit** [comment] 2021-07-11 04:44
> @Emojigit there isn't enough information to use in this issue unfortunately.
> 
>     * Which Sony Xperia do you have?
> 
>     * Can you share the version of Firefox you're currently running? You can find this in the About Firefox screen in Settings.

Xperia E2363, firefox 89.1.1

**Comment by Nickoriginal** [comment] 2021-07-11 04:59
Looks like a duplicate of bug #19783 and Bugzilla [1714227](https://bugzilla.mozilla.org/show_bug.cgi?id=1714227).

**Comment by Nickoriginal** [comment] 2021-07-12 12:40
Also, you can test release [88.1.4](https://github.com/mozilla-mobile/fenix/releases/tag/v88.1.4) on your device, because, as was stated in [#19873](https://github.com/mozilla-mobile/fenix/issues/19783), issue occured after updating to 89.1.1.

**Comment by Nickoriginal** [comment] 2021-07-12 12:44
Also, you can test release [88.1.4](https://github.com/mozilla-mobile/fenix/releases/tag/v88.1.4) on your device (if you not did it before) because, as was stated in [#19873](https://github.com/mozilla-mobile/fenix/issues/19783), issue occured after updating to 89.1.1.

**Comment by kbrosnan** [comment] 2021-07-12 17:15
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1720169

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by kbrosnan** 2021-07-12 17:15 UTC
Labels: needs:triage, 🐞 bug

**Comment by Nickoriginal** [comment] 2021-07-13 10:52
https://github.com/mozilla-mobile/fenix/issues/19783

**Comment by Nickoriginal** [comment] 2021-07-13 10:54
https://github.com/mozilla-mobile/fenix/issues/19782
