### ISSUE TITLE
[Bug] Saved logins broken, no longer saves HTTP Auth logins

### ISSUE THREAD

**Issue by rzubek** [mozilla-mobile/fenix#15306] opened 2020-09-22 13:50 UTC
## Steps to reproduce

- In settings, enable the option to save login information. 
- Log in to a site that uses HTTP Authentication, using the standard username/password login popup. 
- Once logged in, you _should_ be getting an option to save those login credentials, and they should be prefilled on subsequent visits.
- In FF 80.0 and later, observe that those login credentials no longer get saved. This functionality used to work in versions prior to 80, and stopped working in version 80 and 81.

### Expected behavior

Since the user opted in, the browser should offer to save these login credentials, and prefill them on future visits.

### Actual behavior

Even though the user opted in, the browser fails to ask to save this login credentials, and they don't not show up under "saved logins" settings panel. On future visits, login credentials are not prefilled and must be re-entered each time.

This is a regression that started with FF 80.0.

### Device information

* Android device: NVidia Shield K1, however this behavior is not device-dependent
* Fenix version: 80.x and 81.x

Please note that I reproduced this with Sync turned off, I don't know if Sync functionality affects this. Also I only tested this with official releases, not nightly builds.

**Comment by cadeyrn** [comment] 2020-09-22 14:14
Duplicate of #13941. Maybe more #13961 but #13961 was duped to #13941.

**Comment by kbrosnan** [comment] 2020-10-22 09:15
Closing as a duplicate of #13941.

**Closed by kbrosnan** 2020-10-22 09:15 UTC
Labels: needs:triage, 🐞 bug

**Comment by rzubek** [comment] 2020-10-22 15:39
Another related issue that describes the same symptoms: https://github.com/mozilla-mobile/fenix/issues/14756
