### ISSUE TITLE
[Bug] Top Sites Show on Home when Setting Is Disabled

### ISSUE THREAD

**Issue by josejuan05** [mozilla-mobile/fenix#17896] opened 2021-02-08 05:36 UTC
## Bug Description
With the "Show Most Visited Sites" toggle disabled in Beta, sometimes the most visited sites panel appears on the home screen. Toggling the setting on and off didn't fix it. Force killing the app and/or clearing the cache does not fix it. "Quit"-ing the app from the menu seems to fix it.
## Steps to reproduce
Disable the Top Sites panel in Beta then browse around for somewhere between 1 hour and 1 week. Suddenly the panel reappears and there's little to nothing you can do about it without closing everything.
### Expected behavior
It shouldn't reappear, and if it does it should be able to be re-disabled.
### Actual behavior
It does reappear, and there's no way to make it go away short of quitting the browser.
### Device information

* Device vendor / model and Android version: Pixel 3
* Firefox for Android version: 86.0.0-beta.2 (Build #2015790811)
AC: 72.0.5, 4f36d0f93
GV: 86.0-20210131185630
AS: 67.2.0

**Comment by josejuan05** [comment] 2021-02-08 05:42
Correction: the "Quit" action doesn't seem to fix this without clearing history.

**Comment by cadeyrn** [comment] 2021-02-08 06:58
Duplicate of #17655 - it's already fixed in Nightly and should also be fixed in the next Beta release.

**Closed** 2021-02-08 07:02 UTC
Labels: needs:triage, 🐞 bug
