### ISSUE TITLE
[Bug] Bing doesn't show suggestions

### ISSUE THREAD

**Issue by Sav22999** [mozilla-mobile/fenix#14029] opened 2020-08-21 17:03 UTC
If the default search engine is Bing, when you write in the address bar, (and in Settings "show suggestions" is enabled) it doesn't show anything

# Device information
LG G6 (Europe)

* Android device: 9

**Comment by s-ankur** [comment] 2020-08-24 05:55
I cannot reproduce on Asus Zenfone m1 (Latest Nightly).

**Comment by mcarare** [comment] 2020-08-24 07:51
Cannot reproduce it either, on multiple devices.

**Comment by Sav22999** [comment] 2020-08-24 08:29
I've deleted the data and reopened the app. Now it works

**Comment by mcarare** [comment] 2020-08-24 09:21
Closing this as per reporter's comment https://github.com/mozilla-mobile/fenix/issues/14029#issuecomment-678986608.

**Closed by mcarare** 2020-08-24 09:21 UTC
Labels: Feature:Search, Feature:SearchProvider, needs:triage, 🐞 bug
