### ISSUE TITLE
[Bug] Dynamic navigation toolbar is not working for all sites

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#10843] opened 2020-05-22 08:07 UTC
## Steps to reproduce
1. Open app and navigate to amazon.com .
1. Scroll throughout the page.(Upwards and downwards)
    1. Expected behavior
The navigation bar is dynamic in both normal and private mode.
    1. Actual behavior
The navigation bar is not dynamic neither in normal mode nor in private mode.
    1. Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 5/22
GIF:
![20200522-105207](https://user-images.githubusercontent.com/49859863/82645699-fb286500-9c1b-11ea-8dcb-e082471899bd.gif)

Note: Same problem i encountered with baidu.com

Related to feature flag -enabled for nightly and debug build: #8775

**Comment by karlcow** [comment] 2020-05-26 00:05
Probable duplicate https://github.com/webcompat/web-bugs/issues/53267

**Comment by sblatz** [comment] 2020-06-15 22:15
I believe this is expected given our implementation. This is because the content we're getting back is "embedded" content that tells us its handling the press.

@fluffyemily / @snorp do we need to reconsider this approach?

**Comment by softvision-miralobontiu** [comment] 2020-07-01 08:48
I was able to reproduce this behavior on twitter.com, in normal browsing on the latest Beta 79.0.0-beta.3 with Samsung Galaxy Tab S6 (Android 9).

**Comment by Diana-Rus** [comment] 2020-07-08 10:44
Hi, it seems that the issue isn't reproducible anymore, verified on the latest Nightly 7/8 with Samsung Galaxy S9 (Android 8) and Google Pixel 3XL (Android 9)
<details closed>
<summary>Samsung Galaxy S9 (Android 8)-Amazon</summary>

![20200708-133016](https://user-images.githubusercontent.com/49859863/86908860-e185a300-c11f-11ea-952a-16fe240e9313.gif)
</details>
<details closed>
<summary>Samsung Galaxy S9 (Android 8)-Twitter</summary>

![20200708-133953](https://user-images.githubusercontent.com/49859863/86909493-d4b57f00-c120-11ea-89d4-0d67751486be.gif)
</details>

I'm going to close the issue, but in case at some point it's going to reproduce can be reopened.

**Comment by ebalazs-sv** [comment] 2020-07-17 11:07
This is reproducible on Beta 79.0.0-beta.9 (Build #2015752521) GV 79 from 7/17 with Motorola Moto G6 (Android 8), on twitter.com, so I will reopen this issue.

**Comment by softvision-miralobontiu** [comment] 2020-08-06 11:08
I was able to reproduce this issue on the 80.0.0-beta.3 build with Samsung Galaxy Tab S6 (Android 9) on tripadvisor.com.

**Comment by softvision-miralobontiu** [comment] 2020-09-09 08:57
Reproduced it today on the latest RC build 80.1.3 with Samsung Galaxy Tab S6 (Android 9) on twitter.com.

**Comment by AndiAJ** [comment] 2020-10-01 08:47
Reproducible on **`feedbin.com`** having the toolbar set to **bottom** on **RC 81.1.2** using a OnePlus A3 (Android 6.0.1)

**Comment by softvision-miralobontiu** [comment] 2020-10-07 08:24
This issue is still reproducible on Beta 82.0.0-beta.4 and on RC 81.1.3 with Samsung Galaxy Tab S6 (Android 10) on twitter.com.

**Comment by Mugurell** [comment] 2021-02-03 19:47
On the latest Nightly I see the toolbar scrolling on
- amazon.com
- tripadvisor.co.uk
- feedbin.com
- twitter.com

There may be websites on which the toolbar will stay fixed (for example google maps) which have to be investigated on a case by case basis.
The first step being to confirm if there are differences in behavior with other browsers.

If the sites from this ticket show now the expected behavior I propose closing this ticket and open new ones for any new issue that is discovered (after confirming a difference with other browsers)

**Closed** 2021-08-10 00:17 UTC
Labels: 🐞 bug, Feature:Toolbar, S2, wontfix
