### ISSUE TITLE
Show a prompt when trying to leave private browsing with active downloads

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#18160] opened 2021-02-24 20:51 UTC
In Firefox desktop when users are in private browsing and try to leave it (closing all private tabs) and have some downloads in progress, a prompt is shown to users indicating that if they leave the downloads will be canceled. 

![image](https://user-images.githubusercontent.com/773158/109063132-cd92af80-76b6-11eb-8b2b-f2b5c69dad88.png)

**Comment by Amejia481** [comment] 2021-02-24 21:29
On the other hand Chrome does something similar, but instead of showing a prompt when when leaving private browsing it just cancel any pending downloads associated.

**Comment by mavduevskiy** [comment] 2021-12-23 21:29
The changes could be seen in the latest Nightly build.

**Comment by SoftVision-LorandJanos** [comment] 2021-12-27 07:46
Verified as fixed in the latest Nightly (2021-12-27).
The prompt is displayed when trying to close the private tabs.
The buttons "Stay in private browsing" and "Cancel 1 download" work as intended.
The prompt has a bit different design than the one presented in the description:
![Screenshot_20220108-092918](https://user-images.githubusercontent.com/48829350/147448134-6f3e32a4-0984-46a1-8674-ee7a0ba89487.png)
Device used: Google Pixel 4 (Android 11).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2021-12-27 07:46 UTC
Labels: feature request 🌟, eng:qa:needed, Feature:Download, E3, S3
