### ISSUE TITLE
FNX3-16972 ⁃ [Bug] Crash when selecting copy item from Share Menu

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#3371] opened 2019-06-11 22:22 UTC
From the trace it looks like it's my adobe CC app that's giving this second "copy to clipboard" option here. Not sure if there's anything we can do because Pocket's share sheet has the same crash. Maybe we could catch it though? 

> 2019-06-11 15:19:04.776 8014-8014/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: org.mozilla.fenix.debug, PID: 8014
>     java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.SEND typ=text/plain flg=0x10000001 cmp=com.adobe.cc/.share.CopyToClipboardActivity clip={text/plain T:https://blog.mozilla.org/firefox/firefox-data-privacy-promise/} (has extras) } from ProcessRecord{e0f3ff1 8014:org.mozilla.fenix.debug/u0a400} (pid=8014, uid=10400) not exported from uid 10312
>         at android.os.Parcel.createException(Parcel.java:2069)
>         at android.os.Parcel.readException(Parcel.java:2037)
>         at android.os.Parcel.readException(Parcel.java:1986)
>         at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3821)
>         at android.app.Instrumentation.execStartActivity(Instrumentation.java:1705)
>         at android.app.Activity.startActivityForResult(Activity.java:5094)
>         at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
>         at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
>         at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:791)
>         at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:933)
>         at androidx.fragment.app.Fragment.startActivity(Fragment.java:1176)
>         at androidx.fragment.app.Fragment.startActivity(Fragment.java:1164)
>         at org.mozilla.fenix.share.ShareFragment$subscribeToActions$1.accept(ShareFragment.kt:131)
>         at org.mozilla.fenix.share.ShareFragment$subscribeToActions$1.accept(ShareFragment.kt:34)
>         at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
>         at com.uber.autodispose.HalfSerializer.onNext(HalfSerializer.java:121)
>         at com.uber.autodispose.AutoDisposingObserverImpl.onNext(AutoDisposingObserverImpl.java:76)
>         at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
>         at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
>         at io.reactivex.subjects.SerializedSubject.onNext(SerializedSubject.java:104)
>         at org.mozilla.fenix.share.AppShareItemViewHolder$1.onClick(AppShareView.kt:112)
>         at android.view.View.performClick(View.java:7251)
>         at android.view.View.performClickInternal(View.java:7228)
>         at android.view.View.access$3500(View.java:802)
>         at android.view.View$PerformClick.run(View.java:27843)
>         at android.os.Handler.handleCallback(Handler.java:883)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7116)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
>      Caused by: android.os.RemoteException: Remote stack trace:
>         at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1050)
>         at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:751)
>         at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:574)
>         at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1299)
>         at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:512)

**Comment by jonalmeida** [comment] 2019-06-11 22:52
App link for personal reference: https://play.google.com/store/apps/details?id=com.adobe.cc

**Comment by jonalmeida** [comment] 2019-06-12 13:10
@ekager I looked into this today and it seems like there's nothing we can do to fix this. It's the state of the app that isn't allowing our intent to be received but it's also in it's intent filter AndroidManifest.xml as well  ¯\_(ツ)_/¯ .

We _could_ catch the exception, but maybe show a toast or something that sharing failed? Crashing for now should be fine since this is in the control of the third party app.

In the [ShareFragment](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt#L131-L132):
```kotlin
try {
    startActivity(intent)
    dismiss()
} catch (e: SecurityException) {
    // show toast here?
}
```

**Comment by jonalmeida** [comment] 2019-06-12 17:42
Clearing assignment until this bug is triaged.

**Comment by jonalmeida** [comment] 2019-06-12 18:16
cc: @AmyYLee

**Comment by AmyYLee** [comment] 2019-06-12 21:16
I think it makes sense to have a snack bar notification here to indicate sharing failed. 
"Can't share page" or "Sharing failed" @mheubusch Do you have suggestions for copy for a snackbar to say that it cannot share a page?

**Comment by jonalmeida** [comment] 2019-06-14 02:48
> I think it makes sense to have a snack bar notification here to indicate sharing failed.
> "Can't share page" or "Sharing failed" @mheubusch Do you have suggestions for copy for a snackbar to say that it cannot share a page?

@AmyYLee I'm also assuming that we don't close the share menu either, right?

**Comment by AmyYLee** [comment] 2019-06-27 17:35
> > I think it makes sense to have a snack bar notification here to indicate sharing failed.
> > "Can't share page" or "Sharing failed" @mheubusch Do you have suggestions for copy for a snackbar to say that it cannot share a page?
> 
> @AmyYLee I'm also assuming that we don't close the share menu either, right?

@jonalmeida The share menu should close and the snackbar appears afterwards. It should behave the same way as our confirmations. Thanks!

**Comment by mheubusch** [comment] 2019-06-27 23:00
@ekager @jonalmeida I think  **Can't share link**  is good if the source of the problem is the page itself. Not sure I completely understand the issue, however.  If the issue is that a given app can't receive the link, maybe *Can't send link to this app* is clearer.

**Comment by jonalmeida** [comment] 2019-06-28 17:59
> If the issue is that a given app can't receive the link, maybe Can't send link to this app is clearer.

This is the right situation, so we can use this string. Thanks Michelle and Amy!

**Comment by sv-ohorvath** [comment] 2019-09-16 13:40
Verified as fixed on Nightly 9/16.

**Closed** 2020-08-12 17:34 UTC
Labels: eng:qa:verified, eng:ready, 🐞 bug
