### ISSUE TITLE
Add option to "promote" extensions to main menu

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/fenix#17056] opened 2020-12-15 21:57 UTC
It would be really nice if we could have an option to promote certain Addon's actions to the main menu, similar to what happens today for Report Site Issue.

Something like an option "Promote to main Menu" in the addon settings that moves the browser action to the main menu.

This would help with extensions which the user interacts a lot (for example, I open the uBlock action many times and clicking on add-ons -> uBlock all the time gets annoying).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9116)

**Comment by BlitW0** [comment] 2020-12-20 19:50
Duplicate of https://github.com/mozilla-mobile/fenix/issues/11809

**Comment by boek** [comment] 2023-01-31 16:16
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814119

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-31 16:16 UTC
Labels: feature request 🌟, Feature:WebExtensions, needs:UX-investigation
