### ISSUE TITLE
Add ability to 'Copy Link Text'

### ISSUE THREAD

**Issue by Ruin0x11** [mozilla-mobile/fenix#7641] opened 2020-01-13 16:57 UTC
### Why/User Benefit/User Problem
As a user I frequently want to copy the text of a link instead of the link itself. Chrome/Brave on Android has this feature but Firefox Preview does not currently. If I want to copy the text I have to do something like select the surrounding non-link text and manually move the cursor onto the link text, which is error prone since the text selection cursor can easily jump across the entire page if there is no text nearby.

### What/Requirements
There should be a 'Copy Link Text' option in the long press menu on a link that copies the link's text to the clipboard.

### Acceptance Criteria (how do I know when I’m done?)
Same as requirements.

**Comment by kbrosnan** [comment] 2020-01-13 17:23
Might need geckoview work if Fenix does not have a way to get the anchor text.

**Comment by kbrosnan** [comment] 2020-09-24 20:36
Duplicate of #1589

**Closed by kbrosnan** 2020-09-24 20:36 UTC
Labels: Feature:ContextMenu, feature request 🌟, needs:gv
