### ISSUE TITLE
[Bug] URL Autocomplete reappear with Gboard backspace button

### ISSUE THREAD

**Issue by Sayrus** [mozilla-mobile/fenix#11700] opened 2020-06-17 17:33 UTC
## Steps to reproduce
With GBoard (Works fine with the default keyboard):

* Open an URL with a path (not just a domain root)
* Press backspace
* Press backspace (As many times as you want until you only have the domain)
![ffpreview](https://user-images.githubusercontent.com/22404472/84930029-39506180-b0c0-11ea-9e67-fbe1b0517f22.gif)

This suspiciously looks like the same behavior as #4481.

### Expected behavior
Two characters has been deleted

### Actual behavior
The first time one char gets deleted
The second the auto completion is removed
You can actually repeat the process as shown in the gif

### Device information
* Android device: Xiaomi Mi Mix 3 (MIUI 11.0.3, Android 10)
* Fenix version: 5.1.1 (Build #21571852), 42.0.1

**Comment by DavidJCobb** [comment] 2020-09-02 14:29
It seems like #12525 is a duplicate of this and has gotten a little more attention.

**Comment by ekager** [comment] 2020-12-17 20:42
closing for #12525  then

**Closed by ekager** 2020-12-17 20:42 UTC
Labels: needs:triage, 🐞 bug
