### ISSUE TITLE
[Bug] Connecting Fenix/Android device to Sync account silently activates sync of credit card data even it got configured on desktop to not get synced, should be kept unchanged or announce change

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#19715] opened 2021-05-29 18:54 UTC
### Steps to reproduce
1. On Desktop (Firefox 89.0 RC2 used), create a Firefox account.
2. Connect Sync with the Firefox account.
3. Configure Sync to only sync open tabs (this step might not be necessary).
4. Scan the code with Firefox Nightly for Android 90.0a1
5. Press the 'Sync now' button on desktop.
6. Check what gets synced.

### Expected behavior
"Open Tabs"

### Actual behavior
"Open Tabs" + "Credit Cards"

### Device information

* Device vendor / model and Android version: Sony Xperia XZ2 Compact, Android
* Firefox for Android version: latest 90.0a1

**Comment by abodea** [comment] 2021-05-31 08:31
Thank you for this report!
Please note that I was not able to reproduce this issue with the latest RC (desktop) and latest Nightly 5/31 with Google Pixel 4XL (11).
Can you please re-try on the latest Nightly for Fenix?

**Comment by Archaeopteryx** [comment] 2021-06-01 12:27
I can still produce. Check Nighty for Android syncs and desktop afterwards to get the credit card sync added.

**Comment by mcarare** [comment] 2021-06-02 09:21
@Archaeopteryx Between steps 3 and 4 did you press the sync now button on desktop Firefox? 
Just changing the selected engines to be synced does not change the sync list in app services. That being said, it is normal that if you change the selected engines on mobile when you press sync in desktop it would also have the list saved and synced on mobile.

**Comment by Archaeopteryx** [comment] 2021-06-02 11:11
Yes, the "Sync Now" button gets clicked after the synced categories got updated.

**Comment by mcarare** [comment] 2021-06-02 11:17
@Archaeopteryx I cannot reproduce the issue with the steps you described. When I sign in from the mobile app no other engines than the ones selected on the desktop are checked. The same, when pressing sync now I do not have any new engines selected if I do not make any changes from the mobile app.

**Comment by mcarare** [comment] 2021-06-09 09:51
As we cannot reproduce this  I am closing this until the reporter comes back with more info or someone else encounters this issue.

**Closed by mcarare** 2021-06-09 09:51 UTC
Labels: Feature:Autofill, cc-autofill, qa-triaged, 🐞 bug
