### ISSUE TITLE
Swipe up to show tabs

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#17238] opened 2020-12-27 03:22 UTC
Swipe up to show tabs
![Firefox](https://user-images.githubusercontent.com/23485114/103163194-0d046300-4810-11eb-9d41-af21195a187d.gif)

**Comment by sheikh-azharuddin** [comment] 2020-12-27 04:20
I would like swipe to show additional items
Like add-ons (active add ons with batch no like desktop version),  share button, page info, save to pdf, add to top sites, save to collection,desktop site etc

**Comment by Dunexus** [comment] 2020-12-27 09:58
Seems like a duplicate of https://github.com/mozilla-mobile/fenix/issues/11862

**Comment by ekager** [comment] 2021-01-08 19:05
Closing as dupe of #11862. Please copy over mocks/feedback there

**Closed by ekager** 2021-01-08 19:05 UTC
Labels: needs:triage
