### ISSUE TITLE
[Bug] [org.mozilla.experiments.nimbus.ErrorException$RequestError]: Crash when opening the home screen with no active internet connection

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#16886] opened 2020-12-06 21:17 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

https://crash-stats.mozilla.org/signature/?product=Fenix&signature=org.mozilla.experiments.nimbus.ErrorException%24RequestError%3A%20at%20org.mozilla.experiments.nimbus.Error.intoException%28nimbus.kt%3A9%29

## Steps to reproduce
0. Have an open tab.
1. Disable mobile data and wifi.
2. Open the home screen. Happens both when switching from a web page to the home screen and cold starting the app.

### Expected behavior
No crash

### Actual behavior
Crash

### Device information

* Android device: samsung galaxy a50
* Fenix version: nightly

**Comment by miDeb** [comment] 2020-12-06 21:23
I recently had an issue with my conmection where all my conmections were timing out. When trying to open fenix the home screen would not load and the browser crashed after a few seconds. That makes me think that this request _might_ be happening on the main thread, related to https://github.com/mozilla-mobile/fenix/issues/16852 (but that's really just a hypothesis).

**Comment by sv-ohorvath** [comment] 2020-12-07 12:09
We were able to reproduce (not with 100% rates) the crash manually and with automated UI tests. I also saw this crash in Firebase UI Tests: https://github.com/mozilla-mobile/fenix/issues/16889

**Comment by jhugman** [comment] 2020-12-07 18:22
This appears to be fixed by https://github.com/mozilla/nimbus-sdk/pull/67, but is not yet released.

Filing [this Jira ticket][1] to track the bug in Nimbus.

[1]: https://jira.mozilla.com/browse/SDK-140

**Comment by GabrielGanne** [comment] 2020-12-08 09:02
Hi,

I also have this issue, and I'd like to add that no crash report seems to be submitted (`about:crashes` stays empty).
I have no idea if this is related though.
Hope it helps.

Best regards

**Comment by 9ary** [comment] 2020-12-08 14:17
The crash reports can be found in Settings > About > Crashes.

**Comment by GabrielGanne** [comment] 2020-12-08 15:10
> 
> 
> The crash reports can be found in Settings > About > Crashes.

Found them. I didn't know it was different on mobile.
Thank you.

**Comment by csadilek** [comment] 2020-12-11 22:29
This should be fixed in latest Nightly 201211 17:01.

**Comment by ebalazs-sv** [comment] 2020-12-14 10:01
Verified as fixed on Nightly 201214 05:03 (Build #2015781291) GV 85 from 12/14 with Pixel 2 (Android 9) manually and also with automated UI tests.
I will close the issue and remove the qa:needed label.

**Closed by ebalazs-sv** 2020-12-14 10:01 UTC
Labels: S1, b:crash, eng:qa:needed, 🐞 bug
