### ISSUE TITLE
[Bug] Images and Videos aren’t getting opened in Facebook.

### ISSUE THREAD

**Issue by pb-10** [mozilla-mobile/fenix#3300] opened 2019-06-09 12:19 UTC
## Steps to reproduce:
Opened private browsing. Went to Facebook.com and tried to open images and videos.

### Device information
* Android device: Mi A1, Android Version 9
* Fenix version: 1.0.1923

**Comment by vesta0** [comment] 2019-06-11 05:02
@pb-10 I can load images and play videos on facebook as expected. If you are still experiencing this bug, would you please provide more detail steps to reproduce it?

**Comment by sblatz** [comment] 2019-07-16 20:27
@pb-10 any update on this? :)

**Comment by sblatz** [comment] 2019-07-18 19:25
I'm going to close this as we're not able to reproduce. @pb-10 please re-open if you're still experiencing!

**Comment by softvision-miralobontiu** [comment] 2020-03-11 14:54
I was not able to reproduce the issue on the latest Nightly build from 3/11 with Xiaomi Redmi Note 8T (Android 9). 
Removing the needs:STR label.

**Closed** 2020-08-26 23:11 UTC
Labels: P5, S3, 🐞 bug
