### ISSUE TITLE
FNX-79 ⁃ Provide option for top navigation

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2115] opened 2019-04-28 19:19 UTC
### Why/User Benefit/User Problem
* The location of the navigation bar when at the bottom is inconsistent due to moving up when the keyboard is on the screen.
* The navigation bar when at the bottom is easily hidden by thumbs.
* Bottom navigation breaks Fitts' Law — Missing the navigation bar, risks enacting a tab on the system navigation. 
* Given all of the above, bottom navigation is more trend than design.
* Parity with Google Chrome.

### Acceptance Criteria (how do I know when I’m done?)
Users will have the ability to choose whether they have the navigation bar at the top or the bottom.

**Comment by reinhart1010** [comment] 2019-05-20 08:41
Duplicate: https://groups.google.com/forum/m/#!topic/fenix-nightly/8w3otl7mLdQ

**Comment by reinhart1010** [comment] 2019-05-20 08:47
Duplicate: https://groups.google.com/forum/m/#!topic/fenix-nightly/0w2uBcyXjok

**Comment by tpine** [comment] 2019-07-02 07:35
The Google Groups links only work if you are a member of the Fenix Nightly group. They are not accessible otherwise so marking this as a duplicate of other issues does not help now it's in open preview.

**Comment by reinhart1010** [comment] 2019-07-02 10:25
@tpine and in the meantime I can't close each Google Groups threads the same way as BMO and GitHub. It's quite annoying since people there are likely to open duplicate threads, wanting/listing the same issue as one described here.

**Comment by tpine** [comment] 2019-07-03 01:47
@reinhart1010 I'm sorry if my comment came off a bit cold I've been sick the last week but could I make a suggestion?

Most users now are going to be using the more mainstream options for non core collaborators so it might make sense to mark duplicates on the Google groups side instead of the publicly accessible issue boards.

**Comment by reinhart1010** [comment] 2019-07-03 12:37
> so it might make sense to mark duplicates on the Google groups side...
In those posts I commented
> This has been discussed in <GitHub link>
instead of
> Duplicate of: <GitHub link>

I think it's better to change the issue comment here from:
> Duplicate: <external link>
to
> SeeAlso: <external link>
to avoid confusion.

For those of you who interact with r/firefox (Reddit), Mozilla Discourse, Telegram, and other forums I personally suggest to refer to respective GitHub issues (mozilla-mobile/fenix, webcompat/web-bugs, mozilla/GeckoView) and append SeeAlso text similar to the ones in bugzilla.mozilla.org.

**Comment by robmv** [comment] 2019-07-03 18:53
UI behaviour options aren't always good, It adds to much complexity to have all those different UI layouts. I think a good URL bar should be first objective, be it at the bottom or at the top. IMHO the current bottom implementation is not better than the simplest one on the top. Let me add my pet peeves:

- Reduce the useful area the user have for scrolling single handed (#3876)
- There isn't currently any implementation of the URL bar auto hiding, like all mayor browsers have (including Fenec). I don't think a good option could be implemented with the URL bar at the bottom.
- Users tend to read pages from top to bottom, having the URL bar on the bottom visually distract when you are reading text. Is like having a big status bar with text on the bottom, and status bar are a dying breed too.

**Comment by cadeyrn** [comment] 2019-07-03 19:22
> There isn't currently any implementation of the URL bar auto hiding, like all mayor browsers have (including Fenec). I don't think a good option could be implemented with the URL bar at the bottom.

Why not? It was already implemented. It was temporary disabled for the MVP release but it's expected that the auto-hide behaviour will re-implemented.

> Users tend to read pages from top to bottom, having the URL bar on the bottom visually distract when you are reading text.

It never distracted me.

>  for scrolling single handed

single handed is a good argument - for the bottom bar. It makes it much easier to use the browser with only hand.

> UI behaviour options aren't always good, It adds to much complexity to have all those different UI layouts

That's the only point I agree with.

**Comment by robmv** [comment] 2019-07-03 19:45
> Why not? It was already implemented. It was temporary disabled for the MVP release but it's expected that the auto-hide behaviour will re-implemented.

Good, will have to test it to make an opinion.

> single handed is a good argument - for the bottom bar. It makes it much easier to use the browser with only hand. And I never had problems with scrolling with the bottom bar.

Do some user testing, don't have to tell them you are evaluating the bar location, just give them some pages and ask for them to scroll single handed, and count how many of them start the scroll gesture from the URL bar, and the current implementation doesn't detect a scroll from there, the Share/Bookmark drawer open gesture gets in the way (#3876). They miss to scroll frequently, not always, but enough to be annoying. Fixing #3876 could be a start, and adding the URL bar as a zone valid to start the scroll gesture is other.

> 
> > UI behaviour options aren't always good, It adds to much complexity to have all those different UI layouts
> 
> That's the only point I agree with.

**Comment by cadeyrn** [comment] 2019-07-03 22:24
> Do some user testing

I use Fenix Nightly with the bottom toolbar since a few months. It's definitively easier to use the browser with only one hand compared to browsers with a top toolbar. With the old Firefox or with Chrome it's not easy at all. It's very difficult for me to reach the address bar, the tab switcher, the menu or the reload feature - basic features of the browser. Thanks to the bottom toolbar all of this is very easy in Fenix. If I consider the feedback on some of my channels (comments on my blog about Mozilla related topics and the biggest Firefox forum in the German speaking region) there is clearly more positive feedback about the bottom toolbar than negative feedback. Of course it's not possible to make everyone happy but a lot of people really like the bottom toolbar for exactly that reason.

> and the current implementation doesn't detect a scroll from there, the Share/Bookmark drawer open gesture gets in the way (#3876)

This has nothing to do with the bottom navigation at all. Even with a top toolbar the quick action bar could be on the bottom. It's also possible to have the toolbar on the bottom and place the quick action bar on the top. By that I mean that your issue with the scrolling and the quick action bar does not mean that the address bar on the bottom is a bad idea. Two seperate topics.

**Comment by lime124** [comment] 2019-07-23 21:41
@apbitner for consideration during your explorations.

**Comment by vesta0** [comment] 2019-10-01 04:04
Thanks for filing! We will address this in #5694

**Closed** 2020-08-11 14:00 UTC
Labels: Feature:Search, P3, feature request 🌟, needs:UR
