### ISSUE TITLE
FNX-5618 ⁃ [Bug] Reader view is slow

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2365] opened 2019-05-09 04:41 UTC
## Steps to reproduce
Navigate to any of:

https://www.nbcnews.com/news/amp/ncna1003476
https://splinternews.com/dont-cross-the-line-1834606709/amp
https://www.nbcnews.com/news/amp/ncna1003271

1. Swipe up quick actions bar, tap "Read"

### Expected behavior
Reader view opens in <1 a second.

### Actual behavior
Reader view takes around 9 seconds to load.

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by csadilek** [comment] 2019-05-09 14:46
Thanks @yoasif. We found the cause in our Android component and putting a fix up today: https://github.com/mozilla-mobile/android-components/issues/2964

**Comment by csadilek** [comment] 2019-05-09 22:56
This is fixed now and should roll out with the next update.

**Closed** 2020-08-11 14:54 UTC
Labels: needs:ac, 🐞 bug
