### ISSUE TITLE
FNX2-15084 ⁃ [Bug] Firefox nightly has moved and New Nightly link points to org.mozilla.fennec_aurora

### ISSUE THREAD

**Issue by gabrielambuehl** [mozilla-mobile/fenix#12207] opened 2020-07-02 17:23 UTC
## Steps to reproduce
Start nightly 200702. See Screenshot. Press on the button. 

### Expected behavior
Get some useful Indication of what is happening and be told how to get the proper nightly. 

### Actual behavior
Get redirected to regular non nightly preview. 

### Device information
* Android device: ?
* Fenix version: ?

**Comment by gabrielambuehl** [comment] 2020-07-02 17:23
![Screenshot_2020-07-02-19-18-05-073_org mozilla fenix nightly](https://user-images.githubusercontent.com/38832083/86391111-8bd17680-bc99-11ea-9ea6-806decc3e92f.jpg)

**Comment by kbrosnan** [comment] 2020-07-02 17:28
We are in the middle of the process of simplifying Firefox versions in the Play store. This information is correct. We have yet to get the Nightly build updated on the Firefox Preview <org.mozilla.fenix>. It will be updated soon.

**Comment by Dunexus** [comment] 2020-07-02 17:58
@kbrosnan I have this message on both Fenix Nighly <org.mozilla.fenix.nighly> and Fennec Nighly <org.mozilla.fennec_aurora>. Both messages redirect to Fennec Nighly <org.mozilla.fennec_aurora> play store page.
Is this expected behavior ? It seems weird to have this on Fennec Nighly <org.mozilla.fennec_aurora> redirecting to its own play store page.

**Comment by kbrosnan** [comment] 2020-07-02 18:36
Actually there is a bug here 

@sblatz we either need to hardcode https://github.com/mozilla-mobile/fenix/blob/0a9afbed42089de200dbeecb4b3679fb6705e614/app/src/main/java/org/mozilla/fenix/components/tips/providers/MigrationTipProvider.kt#L96 and https://github.com/mozilla-mobile/fenix/blob/0a9afbed42089de200dbeecb4b3679fb6705e614/app/src/main/java/org/mozilla/fenix/components/tips/providers/MigrationTipProvider.kt#L83 or we need to fix https://github.com/mozilla-mobile/fenix/blob/dce16964c0a64db9f330d0f2943bd15a227411bf/app/src/main/java/org/mozilla/fenix/components/metrics/MozillaProductDetector.kt#L14

**Comment by sheikh-azharuddin** [comment] 2020-07-02 19:03
So both fennec nightly and fenix nightly are gone...
New nightly will be Firefox preview?

**Comment by filips123** [comment] 2020-07-02 19:05
Will Firefox Preview <org.mozilla.fenix> branding on Play Store be updated to Nightly branding? Curently, they are still using old Preview branding. Or will nightly versions now use Preview branding instead?

**Comment by yoasif** [comment] 2020-07-02 19:29
Given some of the confusion around this change, can we see if it would be possible to migrate top sites when using Sync to make the transition as seamless as possible? I just did this transition myself and it was disappointing to see that I lost my top sites in the move. 

See https://github.com/mozilla-mobile/fenix/issues/7936

Even a basic version that did top sites sync on mobile only would be nice to have.

**Comment by liuche** [comment] 2020-07-02 20:31
For verification, making the org.mozilla.fennec_aurora and org.mozilla.fenix.nightly builds (per #9208 https://github.com/mozilla-mobile/fenix/issues/9208#issuecomment-621816462 ) and testing that the link takes you to the "new" Firefox Nightly (which is org.mozilla.fenix, and used to be Firefox Preview, but has now been rebranded to "Firefox Nightly").

(My mistake in the earlier bug for not specifying that the link should open org.mozilla.fenix!)

**Comment by SS1113** [comment] 2020-07-03 02:27
Developers -- generally most of the time, I'm with you but when you make it  _this much_ confusing -- I have to ask you -- do you really want to lose your userbase by doing this?! 

Have you _ever_ seen the discussions that go on /r/firefox or /r/Android ?! I always try to help the users there and redirect them to use the appropriate Firefox versions and to make Fenix even better by making them request features and file bug reports -- but now even I don't know what's going on here now!

I never said anything until now, I was with you -- and still am, but I'll say this one thing to you...


**THIS. IS. REALLY. CONFUSING. TO. USERS!  CAN. YOU. PLEASE.... STOP. IT?!**

_Please_ I request you to at least document this somewhere in a way that'll at least make it clear to general users which version to use or recommend. Those recent merged commits -- I don't understand them!

**Comment by Rupurudu** [comment] 2020-07-03 03:12
> Developers -- generally most of the time, I'm with you but when you make it _this much_ confusing -- I have to ask you -- do you really want to lose your userbase by doing this?!
> 
> Have you _ever_ seen the discussions that go on /r/firefox or /r/Android ?! I always try to help the users there and redirect them to use the appropriate Firefox versions and to make Fenix even better by making them request features and file bug reports -- but now even I don't know what's going on here now!
> 
> I never said anything until now, I was with you -- and still am, but I'll say this one thing to you...
> 
> **THIS. IS. REALLY. CONFUSING. TO. USERS! CAN. YOU. PLEASE.... STOP. IT?!**
> 
> _Please_ I request you to at least document this somewhere in a way that'll at least make it clear to general users which version to use or recommend. Those recent merged commits -- I don't understand them!
> 
> I know fenix is currently in a transition period but this is not how you handle it. At least don't push those versions to the Play Store untill you are done! Please see the Mozilla's Play Store page -- How many versions do you even want to have?!

While I'm not a developer, I think this change is good for the long run. They are dropping from 5 versions to 3 just like pre-fenix. 
Firefox and Firefox Beta will stay as-is, Firefox Preview will be Firefox Nightly, Old Firefox Nightly and Firefox Preview Nightly are getting removed from the Play Store.

The _appropriate_ Firefox version for the general public has always been the Firefox browser. This is the first result when you search for "Firefox" in the Play Store. Currently, this is the Fennec browser. Fenix is not ready for stable and it'll replace Fennec when it's ready. If you want to use the Fenix, install Firefox Beta. Don't use Nightly and soon to be removed versions and you are good to go.

**Comment by SS1113** [comment] 2020-07-03 03:22
>While I'm not a developer, I think this change is good for the long run. They are dropping from 5 versions to 3 just like pre-fenix.
Firefox and Firefox Beta will stay as-is, Firefox Preview will be Firefox Nightly, Old Firefox Nightly and Firefox Preview Nightly are getting removed from the Play Store.

Have you seen the Play Store page of [Mozilla](https://play.google.com/store/apps/dev?id=7083182635971239206) right now! And I know the situation will become much better after the transition happens but what I'm saying is this is _not_ the way to handle. If you read Reddit then you'll realise the general users' pain! There must be other ways to handle it!

>The appropriate Firefox version for the general public has always been the Firefox browser. This is the first result when you search for "Firefox" in the Play Store. Currently, this is the Fennec browser. Fenix is not ready for stable and it'll replace Fennec when it's ready. If you want to use the Fenix, install Firefox Beta. Don't use Nightly and soon to be removed versions and you are good to go.

I'm not sure what version are "soon to be removed" and versions what are permanent anymore!  And why do you think Firefox Beta/Firebox Preview is not an appropriate version for general users? Even Fenix developers team agrees that it a production/quite stable ( I can't remember where amd when I read it but someone from Mozilla said this and I agree with them).

**Comment by Rupurudu** [comment] 2020-07-03 03:39
> Have you seen the Play Store page of [Mozilla](https://play.google.com/store/apps/dev?id=7083182635971239206) right now! And I know the situation will become much better after the transition happens but what I'm saying is this is _not_ the way to handle. If you read Reddit then you'll realise the general users' pain! There must be other ways to handle it!
Yeah, It's a mess. I think Mozilla shouldn't have 5 different versions of the same app in the first place. We practically never used fennec_aurora for a long time and after Fenix merged to the beta, there is no need for _Preview_ anymore.

And yeah, I read people asking which version to use every couple of days on reddit. This is finally ending now. 

> I'm not sure what version are "soon to be removed" and versions what are permanent anymore! And why do you think Firefox Beta/Firebox Preview is not an appropriate version for general users? Even Fenix developers team agrees that it a production/quite stable ( I can't remember where amd when I read it but someone from Mozilla said this and I agree with them).

The old [Firefox Nightly (fennec_aurora)](https://play.google.com/store/apps/details?id=org.mozilla.fennec_aurora) and [Firefox Preview Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix.nightly) are the versions getting removed. 

There are reasons why Fenix is not pushed to the stable. UI is still changing, (We just got a new tab design for example) and extension support is garbage. Fennec can run any extension desktop Firefox can. Fenix can't because extension support is not complete. 

I expect they can push Fenix to stable when both developers and user base is generally happy with the UI and the full extension support is implemented.

**Comment by kbrosnan** [comment] 2020-07-03 03:56
There were some technical reasons along with keeping the apps with the largest active userbases why the 3 builds were chosen. The people in r/firefox made some incorrect assumptions about what builds were going to survive. The active full featured browsers are:

* Nightly <[org.mozilla.fenix](https://play.google.com/store/apps/details?id=org.mozilla.fenix)>
* Beta <[org.mozilla.firefox_beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta)>
* Release <[org.mozilla.firefox](https://play.google.com/store/apps/details?id=org.mozilla.firefox)>

**Comment by sv-ohorvath** [comment] 2020-07-03 14:39
We checked the links to the new Nightly channel and now they are working as expected. So I'll close this. Thanks!

**Closed** 2020-08-12 17:22 UTC
Labels: eng:qa:verified, 🐞 bug
