### ISSUE TITLE
Editing a custom search engine has slow response on Save

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#23536] opened 2022-02-02 15:28 UTC
### Steps to reproduce

1. Go to Settings>Search.
2. Add a new custom search engine. Save
3. Edit the new engine: change its title.
4. Press Save.

### Expected behaviour

Changes saved. Returns to Search engines list.

### Actual behaviour

Sometimes nothing happens for a long while. I tapped the button a few times and no result.
Sometimes it works instantly, or after a short wait.

### Device name

Pixel 2 

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

Release 97.1.0, Nightly 98.0a1

### Device logs

Nothing appears in the logs while tapping the button.

### Additional information

![20220202_171742](https://user-images.githubusercontent.com/4037709/152184089-e92328e4-63fb-4a5d-97d1-42a7261a1e5e.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19362)

**Comment by jonalmeida** [comment] 2022-02-02 19:41
> Sometimes nothing happens for a long while. I tapped the button a few times and no result.
> Sometimes it works instantly, or after a short wait.

@sv-ohorvath When adding a search engine, we need to try and connect to it first to verify we can make queries to it (we send out a search query for "1" and you can see this in about:debugging). So the save might be taking a while because the search engine site is slow to respond. This is another candidate for discussion in https://github.com/mozilla-mobile/fenix/issues/23521 I think.

**Comment by jonalmeida** [comment] 2022-02-02 19:43
Ah, elefant.ro is a genuine e-commerce site, so if every UI test run is making a request to it from Firebase, we might have triggered their DDOS response and are now rate-limited or blocked from the Firebase IP addresses.

**Comment by sv-ohorvath** [comment] 2022-02-03 10:24
> Ah, elefant.ro is a genuine e-commerce site, so if every UI test run is making a request to it from Firebase, we might have triggered their DDOS response and are now rate-limited or blocked from the Firebase IP addresses.

That is possible, but the issue is reproducible in manual testing as well with that website.

**Comment by amocirean** [comment] 2022-11-24 12:54
This issue is still reproducible on the latest Nightly of 24th of November 2022 (109.0a1). Tested using Samsung Galaxy S22 Ultra (Android 13) and Oppo Find X3 Neo (Android 11).
The slow response also occurs on adding the custom search engine.
Removing the wontfix label.

**Comment by cpeterso** [comment] 2022-12-27 21:12
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807708

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2022-12-27 21:12 UTC
Labels: 🐞 bug, Feature:Search, S3, needs:triage
