### ISSUE TITLE
[Bug] USB Keyboard -- Unable to unhide (or even access) Navigation Bar

### ISSUE THREAD

**Issue by gamepad-coder** [mozilla-mobile/fenix#13946] opened 2020-08-19 22:00 UTC
## Steps to reproduce

1. Plug in a USB Keyboard to an Android device running the latest version of Firefox Nightly.

2. Navigate to any site (i.e. be on a webpage tab, not on the home screen or other setting screens)

3. Scroll down the page using your finger or stylus on the touchscreen.

4. The Navigation Bar / (aka) URL Bar / (aka) Address Bar at the bottom should now be hidden from view, and the page will fill the screen, no Firefox interface currently visible.

5. The problem. The USB keyboard cannot unhide the Navigation Bar. No USB keyboard press nor hotkey is able to navigate to the Navigation Bar. It remains hidden and impossible to interact with via the USB keyboard.

### Expected behavior

F6 is typical Firefox input to focus the Navigation Bar on Desktop, and is expected to work with a keyboard here. 

Ctrl+L is common in many Android browsers, including the current stable Chrome for Android.

In the current release of vanilla Firefox for Android, the Navigation Bar can be reached / unhidden with a USB keyboard by scrolling to the very bottom of a page. Holding down PageDown to repeat the function until the bottom of the page is reached is currently the only viable way to unhide the Navigation Bar with the keyboard alone (in the stable release branch on Android).

But in the latest Firefox Nightly, it is impossible with a USB keyboard alone.

### Actual behavior

An additional device or input interface is required to browse when a USB keyboard is attached.

### Further Information & Use Case

I am using an IBM Spacesaver II. It is plugged in via USB and mouse functionality is included in the keyboard. 

My Android device is out of arm's reach. 
Mouse works as expected across the Android environment. 

However, if Firefox Nightly has the URL Bar / (aka) Navigation Bar / (aka) Address Bar hidden, it cannot be reached even using the mouse / (aka trackpoint) on the keyboard.

### Summary

Use of Firefox Nightly is impossible using a USB Keyboard alone.

### Device information

App Name : Firefox Nightly
Version : 81.0a1
Build ID : 20200813092915

### Unrelated

I absolutely love this new Firefox.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5165)

**Comment by headbank** [comment] 2020-08-28 18:29
If I may, I have a couple of points to broaden this bug's scope:

1. It applies probably to any external physical keyboard. I can confirm same issue with a Jelly Comb foldable Bluetooth keyboard.

2. My Bluetooth keyboard also has a touchpad that supports scrolling, but using this touchpad scroll in Firefox does not unhide the toolbar either. Nothing to test with but I'd bet that scrolling with a physical mouse (Bluetooth or plug-in) would not work either.

3. Worth specifying that **hide** as well as unhide is equally unsupported with these input methods. So, if the toolbar is displayed, while you are using keyboard/mouse you are stuck with it onscreen.

**Comment by Mugurell** [comment] 2021-02-03 18:59
Hardware keyboards are not yet supported.
Linking this to one ticket about keyboard shortcuts that may have more traction - https://github.com/mozilla-mobile/fenix/issues/3729.

**Comment by headbank** [comment] 2021-08-03 08:24
Maybe wrong place to raise this but I don't see the logic behind this bot's activity.

A bug doesn't stop being a bug or become any less valid because no dev has felt inclined to give it any attention yet (if that is even the case, because the devs do not always announce it when they are actually working on a bug). It just comes across as a tactic for making the statistics look better than they are.

**Comment by Dunexus** [comment] 2021-08-03 08:46
@headbank I can understand this bot can seem frustrating but the goal is not to remove tickets for statistics but to keep it clean and easy to use for planning future work.
It notifies the reporter of the issue to check if the issue is still relevant (it may have been fixed in the meantime) and close it if nobody is able to tell.
It just need an update to keep it open and avoids the repo to be filled with non-relevant issues.

Quoting the bot documentation : 
> # Is closing stale issues really a good idea?
>
> In an ideal world with infinite resources, there would be no need for this app.
>
> But in any successful software project, there's always more work to do than people to do it. As more and more work piles up, it becomes paralyzing. Just making decisions about what work should and shouldn't get done can exhaust all available resources. In the experience of the maintainers of this app—and the hundreds of other projects and organizations that use it—focusing on issues that are actively affecting humans is an effective method for prioritizing work.
>
>To some, a robot trying to close stale issues may seem inhospitable or offensive to contributors. But the alternative is to disrespect them by setting false expectations and implicitly ignoring their work. This app makes it explicit: if work is not progressing, then it's stale. A comment is all it takes to keep the conversation alive.

**Comment by kbrosnan** [comment] 2021-09-20 20:25
The real problem here is that this is a feature request not a bug. Bugs are subject to periodic verification that they continue to be present in newer versions. Feature requests are only manually closed if completed or deferred. I have moved this to a request.

**Comment by jonalmeida** [comment] 2023-01-30 20:26
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813742

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by jonalmeida** 2023-01-30 20:26 UTC
Labels: feature request 🌟, Feature:IME
