### ISSUE TITLE
[Bug] Blocking autoplay video (or just muting sound) is not working on Reddit AMP pages

### ISSUE THREAD

**Issue by jant90** [mozilla-mobile/fenix#20233] opened 2021-07-02 15:51 UTC
When visiting a Reddit AMP page videos on there will autoplay with sound, even when autoplay is blocked (also, just blocking sound doesn't work either). I'm not familiar with other sites using AMP that use video so I couldn't test, but it's possible this happens on other (AMP) sites as well. When opening the tab overview I'm able to pause the video, so Firefox is aware of the video playing.

In my case these videos are outside the viewport so pausing is not easily possible without scrolling and searching the video first which makes this behavior all the more frustrating.

As far as I can tell this happens both Google (google.com/amp) and Reddit (amp.reddit.com) AMP pages when following them from the Google search results. When manually opening an AMP page (e.g. by pasting an url in the address bar) videos won't autoplay.

This issue has been going on for a long time, e.g. I found [this 2 year old post on Reddit](https://www.reddit.com/r/firefox/comments/cwgobf/i_have_block_autoplay_enabled_but_the_reddit_amp/) describing this very issue.

Short video showing this issue (be sure to enable sound):

https://user-images.githubusercontent.com/16788798/124297785-baf41f80-db5b-11eb-932b-b38f9235ff29.mp4

## Steps to reproduce
1. Search Google for a Reddit post, e.g. "Xbox One Tech Support Reddit" (gaming subreddits often have videos).
2. Follow the link to a Reddit AMP page.
3. Wait a few seconds until a video starts autoplaying.
Note: videos don't always play automatically but when scrolling past it autoplay seems to trigger consistently. 

### Expected behavior
Videos won't autoplay (or are muted) when autoplay video (or audio) is turned off in settings.

### Actual behavior
Videos play with sound.

### Device information
* Samsung Galaxy S10e
* Android 11
* Firefox 89.1.1 with Google Search Fixer add-on (might change AMP results?)

P.S. I **HATE** AMP and I wish it would die.

**Comment by Nickoriginal** [comment] 2021-07-02 16:25
Do you can provide a link to any Reddit AMP page?

**Comment by Nickoriginal** [comment] 2021-07-02 16:38
https://amp.reddit.com/r/xboxone/comments/88jbo6/thanks_to_the_guy_who_recommended_buying/
Reproducible in Firefox 89.1.1 on **Samsung Galaxy A20s**, Android 10. Video plays with sound when it shouln't with Autoplay -> Block audio and video enabled.

**Comment by jant90** [comment] 2021-07-02 18:14
Thanks for confirming. I wasn't sure whether I should include urls because when opening them directly I can't reproduce the issue (as I mentioned in the OP).

**Comment by LaurentiuApahideanSV** [comment] 2021-07-05 10:11
@jant90 What option did you use to turn of autoplay?

**Comment by jant90** [comment] 2021-07-05 10:14
The only native option in Firefox, in settings go to **Site permissions** > **Autoplay** and choose option "**Block audio and video**".

**Comment by Nickoriginal** [comment] 2021-07-05 10:20
> The only native option in Firefox, in settings go to **Site permissions** > **Autoplay** and choose option "**Block audio and video**".
<img src = https://user-images.githubusercontent.com/85299944/124456754-bfa31880-dd93-11eb-8603-8f7bbddfcfe1.jpg width = 45%>

**Comment by LaurentiuApahideanSV** [comment] 2021-07-05 12:50
I can confirm the issue is reproducible on Firefox RC 89.1.1 and Nightly 2021-07-05.

### Devices used:
- OnePlus 6T (Android 9)
- Samsung Galaxy S8 (Android 8.0.0)

**Comment by mcarare** [comment] 2021-07-13 10:28
cc @Amejia481 because you might have more insight on this. To me, it seems like a problem in GV, not something we can handle in Fenix.

**Comment by Amejia481** [comment] 2021-07-13 14:29
Sure, I will take a look and report back 👍🏽 .

**Comment by Amejia481** [comment] 2021-07-13 15:47
It looks like this is a platform issue, I'm able to reproduce the same problem using the mobile view on Firefox desktop
I just have to navigate to https://amp.reddit.com/r/xboxone/comments/88jbo6/thanks_to_the_guy_who_recommended_buying/ and scroll to the videos section, just waiting for a few second for the videos to load. I will open a bugzilla bug for it.

<img width="915" alt="image" src="https://user-images.githubusercontent.com/773158/125483155-8720720c-7c14-46f7-9d62-778c4f9ac1b2.png">

<img width="342" alt="image" src="https://user-images.githubusercontent.com/773158/125483475-1c327a95-67dd-4108-9181-72bbd1715237.png">

**Comment by Amejia481** [comment] 2021-07-13 16:14
This is the bug https://bugzilla.mozilla.org/show_bug.cgi?id=1720337

**Comment by SeburoSUMO** [comment] 2021-07-30 22:05
User feedback with further example: https://support.mozilla.org/en-US/questions/1345456#answer-1431490

**Comment by amedyne** [comment] 2021-08-09 12:49
Closing this one to track platform issue in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1720337

**Closed by amedyne** 2021-08-09 12:49 UTC
Labels: 🐞 bug, 🙅 waiting, needs:gv, Feature:Media, qa-triaged
