### ISSUE TITLE
FNX2-15669 ⁃ [Bug] leak after downloading a file (SimpleDownload DialogFragment Leaked)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#13095] opened 2020-07-29 21:40 UTC
### Steps to reproduce
1. Have LeakCanary enabled
1. Download a file (I downloaded a .apk file)

### Expected behavior
No leak.

### Actual behavior
SimpleDownload DialogFragment Leaked

┬───
│ GC Root: System class
│
├─ android.view.accessibility.AccessibilityManager class
│    Leaking: NO (BrowserFragment↓ is not leaking and a class is never leaking)
│    ↓ static AccessibilityManager.sInstance
├─ android.view.accessibility.AccessibilityManager instance
│    Leaking: NO (BrowserFragment↓ is not leaking)
│    ↓ AccessibilityManager.mAccessibilityStateChangeListeners
├─ android.util.ArrayMap instance
│    Leaking: NO (BrowserFragment↓ is not leaking)
│    ↓ ArrayMap.mArray
├─ java.lang.Object[ ] array
│    Leaking: NO (BrowserFragment↓ is not leaking)
│    ↓ Object[].[2]
├─ org.mozilla.fenix.browser.BrowserFragment instance
│    Leaking: NO (Fragment#mFragmentManager is not null)
│    ↓ BrowserFragment.downloadsFeature
│                      ~~~~~~~~~~~~~~~~
├─ mozilla.components.support.base.feature.ViewBoundFeatureWrapper instance
│    Leaking: UNKNOWN
│    ↓ ViewBoundFeatureWrapper.feature
│                              ~~~~~~~
├─ mozilla.components.feature.downloads.DownloadsFeature instance
│    Leaking: UNKNOWN
│    ↓ DownloadsFeature.dialog
│                       ~~~~~~
╰→ mozilla.components.feature.downloads.SimpleDownloadDialogFragment instance
​     Leaking: YES (ObjectWatcher was watching this because mozilla.components.feature.downloads.SimpleDownloadDialogFragment received Fragment#onDestroy() callback and Fragment#mFragmentManager is null)
​     key = ed2c55fc-0738-44df-9e79-2f36fd9cff25
​     watchDurationMillis = 8423
​     retainedDurationMillis = 3419

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: OnePlus
LeakCanary version: 2.4
App process name: org.mozilla.fenix.debug
Analysis duration: 10173 ms

### Device information
* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 10.0.9 (Android 10)
* Fenix version: master branch revision 9066d0bf20aa08ea2a0bf45c4e68bc644f68d68b

**Comment by ekager** [comment] 2020-07-29 21:42
AC issue https://github.com/mozilla-mobile/android-components/issues/7180 
We can keep this open for now

**Comment by cadeyrn** [comment] 2020-07-29 21:46
Ah. I used the search function but in the wrong repository. 😅

**Comment by mcomella** [comment] 2020-08-07 22:43
> AC issue [mozilla-mobile/android-components#7180](https://github.com/mozilla-mobile/android-components/issues/7180)
> We can keep this open for now

The upstream issue was closed so closing this as well.

Please reopen if you believe the issue is not fixed!

**Closed** 2020-08-11 14:08 UTC
Labels: needs:ac, 🐞 bug
