### ISSUE TITLE
[Bug] Video crashes Firefox

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#17687] opened 2021-01-29 09:37 UTC
## Steps to reproduce

1. Go to the following page
 https://www.huaweicentral.com/huawei-summarizes-emui-11-features-for-maximum-customizations/amp/

2. Play the video

### Expected behavior

Video plays and Firefox remains running.

### Actual behavior

Video starts playing then Firefox crashes.

### Device information

* Samsung / Note 9 and Android version: 10

* Firefox for Android version:
Nightly 210128 17:01 (Build #2015790027)
AC: 73.0.20210127143126, f15fd3145
GV: 87.0a1-20210127093943
AS: 67.2.0

**Comment by hakkikaancaliskan** [comment] 2021-01-29 10:42
Duplicate of #17668

**Comment by sflorean** [comment] 2021-02-03 16:25
Closing as duplicate. Bug 17668 is fixed and verified.

**Closed by sflorean** 2021-02-03 16:25 UTC
Labels: needs:triage, 🐞 bug
