### ISSUE TITLE
FNX-12694 ⁃ [Bug] Settings action bar is multi-select colored after opening multiple tabs from history

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11714] opened 2020-06-18 00:15 UTC
## Steps to reproduce
* Open history
* Long press and select multiple tabs (note action bar color)
* Click 3-dot menu
* Click Open in New Tab
* CLick 3-dot on homescreen
* Click Settings

### Expected behavior
Action bar is white

### Actual behavior
Action bar is multi-select color (dark blue):
![image](https://user-images.githubusercontent.com/759372/84963389-1c1a9380-b0be-11ea-9439-5a159391ba31.png)

### Device information
* Android device: Galaxy S5
* Fenix version: Nightly 200617

**Comment by s-ankur** [comment] 2020-06-18 07:29
Duplicate of #8114

**Comment by mcarare** [comment] 2020-06-18 07:41
Closing as duplicate of #8114.

**Closed** 2020-08-11 04:42 UTC
Labels: Feature:History, Feature:Settings, needs:triage, 🐞 bug
