### ISSUE TITLE
[Bug]: Favicon is not displayed in tabs/bookmarks for apple.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/fenix#22932] opened 2021-12-21 09:36 UTC
### Steps to reproduce

1. Navigate to: https://www.apple.com/.
2. Wait for the page to load.
3. Tap on the "Tabs" icon located in the toolbar.
4. Observe the favicon for the page.

### Expected behaviour

The favicon is correctly displayed with the company logo.

### Actual behaviour

The favicon is displayed containing the letter "A".

### Device name

Samsung A51  -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1

### Additional information

1. Not reproducible using Chrome.
2. Reproducible regardless of the status of ETP.
3. Screenshot attached:
 ![Screenshot_9](https://user-images.githubusercontent.com/75027050/146906867-7f0ca8ff-d7ac-43bb-8d52-30de6c4af721.png)

**Comment by kbrosnan** [comment] 2021-12-22 16:07
16x16px favicon Duplicate of https://github.com/mozilla-mobile/android-components/issues/10377

**Closed by kbrosnan** 2021-12-22 16:07 UTC
Labels: 🐞 bug, needs:triage
