### ISSUE TITLE
[Bug] Bottom URL bar position: sticky inconsistency

### ISSUE THREAD

**Issue by mattok** [mozilla-mobile/fenix#14421] opened 2020-08-29 07:30 UTC
# Issue
The URL bar behaves in an inconsistent manner with respect to `position: sticky` when placed relative to the bottom and top. Behaviour when the URL bar is at the bottom is incorrect.

This is particularly annoying where this technique is used to place buttons near the bottom of the screen on mobile devices or within mobile apps for easy access by fingers, since they then become inaccessible:

![Android-bottom-bar-screenshot](https://user-images.githubusercontent.com/2501023/91631257-2ddaba00-e9d0-11ea-9e40-e42cb3bd15cc.png)

# Steps to reproduce

Visit a page that uses styles `position:sticky` in combination with`top:` or `bottom:` to place elements relative to the visible content window.

# Actual behaviour

- With the URL bar at the top, items placed relative to the top using `position: sticky` and `top: ...` are placed relative to the bottom of the URL bar (visible content window), and so appear beneath it and within view.
- With the URL bar at the bottom, items placed relative to the bottom using `position: sticky` and `bottom: ...` are placed relative to the bottom of the app window/device, and so (can) appear underneath the URL bar it instead. This is problematic.

# Expected behaviour
The behaviour when the URL bar is at the bottom ought to be consistent with behaviour when the URL bar at the top, with respect to `position: sticky`. 

# Device information

79.0.5 (Build #2015758617)
AC: 48.0.15, 8755ac0cd
GV: 79.0.1-20200813192915
AS: 61.0.10

**Comment by cadeyrn** [comment] 2020-08-29 08:44
Duplicate of #13797. But since position: sticky is not mentioned in the other issue you could add your information there, could be helpful for the developers.

**Comment by mattok** [comment] 2020-08-29 09:25
I did see issue #13797. It is plausible that they have the same underlying cause, but I wasn't sure, and so I wasn't sure whether this was necessarily an exact duplicate.

**Comment by liuche** [comment] 2020-09-01 02:04
Saw your comment in the other bug, so we should verify that when we QA a fix, closing this one now.

**Closed by liuche** 2020-09-01 02:04 UTC
Labels: needs:triage

**Comment by mattok** [comment] 2020-09-03 08:09
Here's a [minimal example](https://codepen.io/mattok/full/XWdeQZY). If you can't see the yellow sticky zone at the bottom because it is hidden under the address bar, there's a problem.
