### ISSUE TITLE
Ability to display number of open tabs when exceeds 99

### ISSUE THREAD

**Issue by superbonaci** [mozilla-mobile/fenix#16363] opened 2020-11-04 06:15 UTC
When open tabs exceed 99 it just displays infinite symbol. Would like to have a way to see how many there are exactly.

![](https://i.imgur.com/06pJuZi.jpg)

**Comment by superbonaci** [comment] 2020-11-04 06:57
Just displaying them on tabs menu and synced tabs would be enough.

**Comment by kbrosnan** [comment] 2020-11-04 08:22
Closing as a duplicate of #14886

**Closed by kbrosnan** 2020-11-04 08:22 UTC
Labels: needs:triage

**Comment by superbonaci** [comment] 2020-11-08 02:39
The issue has not been fixed.
