### ISSUE TITLE
[Bug] Alt text does not fully display

### ISSUE THREAD

**Issue by BFKelleher** [mozilla-mobile/fenix#19254] opened 2021-04-26 21:14 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

When I try to view a long alt text, it gets cut off after a certain number of characters by an elipsis.

## Steps to reproduce
Find an image with a long alt text (e.g. xkcd.com comics)
Long press on the image to view the alt text.
Notice how alt text is cut off by elipsis.

### Expected behavior
Full alt text displays or is accessible through pressing on the truncated alt text.

### Actual behavior
Alt text is truncated without the option to view the whole thing.

### Device information

* Device vendor / model and Android version: Google Pixel 5 US / Android 11 April Security Update build number RQ2A.210405.005
* Firefox for Android version: 88.1.1 (go to Settings -> About Firefox)
 
![Screenshot_20210426-170755](https://user-images.githubusercontent.com/4306729/116151571-c6861e80-a6b2-11eb-991c-bfba6787b84b.png)
![Screenshot_20210426-171407](https://user-images.githubusercontent.com/4306729/116151612-d271e080-a6b2-11eb-97d3-97b9d069b28f.png)

**Comment by LaurentiuApahideanSV** [comment] 2021-04-29 10:04
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/580. I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-04-29 10:04 UTC
Labels: needs:triage, 🐞 bug
