### ISSUE TITLE
[Bug]: search bar becomes very small after fold from large to small screen 

### ISSUE THREAD

**Issue by Yourhopegaming** [mozilla-mobile/fenix#27540] opened 2022-10-25 16:27 UTC
### Steps to reproduce

1. Obtain foldable device (occurs 100% of the time on fold 4)
2. Open Firefox in unfolded mode and open a website (only happens if app is started in unfolded mode)
3. Close phone
4. Search bar is now the wrong size

### Expected behaviour

The search bar should resize to the proper size as if app is opened in folded mode 

### Actual behaviour

The searchbar is very small, with the lock icon detailing website security taking up most of the space. Upon clicking on visible part of searchbar (not very easy), original size and function is restored and now works properly when folded

### Device name

Samsung Galaxy Z Fold 4

### Android version

Android 12L/13

### Firefox release type

Firefox

### Firefox version

106.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21867)

**Comment by Yourhopegaming** [comment] 2022-10-25 16:31
![Screenshot_20221025_092813_Firefox](https://user-images.githubusercontent.com/48527619/197831006-fe71da0d-6fe6-48ba-b9da-875bd3025cf4.jpg)
![Screenshot_20221025_092821_Firefox](https://user-images.githubusercontent.com/48527619/197831037-3b0839c6-56dc-4b26-a5af-872b21ae6e70.jpg)

**Comment by mcarare** [comment] 2022-10-25 17:11
This is likely from [this](https://github.com/mozilla-mobile/fenix/blob/1f9b1fa0d5cddff956581c8dab5ed7ab7bf0448b/app/src/main/res/values-sw600dp/bools.xml). We should investigate how to handle foldable devices in this scenario.

**Comment by zmckenney** [comment] 2022-12-06 22:26
Reopened due to issue with BrowserFragment calling a null toolbar when BaseBrowserFragment has not initialized the UI or toolbar. [Bugzilla 1804107](https://bugzilla.mozilla.org/show_bug.cgi?id=1804107) ticket here with STR.

**Comment by SoftVision-LorandJanos** [comment] 2022-12-07 08:00
@Yourhopegaming, we do not yet have foldable devices.
Could you check if the issue is reproducible for you with the latest Nightly build?
Thank you!

**Comment by zmckenney** [comment] 2022-12-15 00:43
@SoftVision-LorandJanos This can also be tested on tablets which support multitasking (such as most Samsung tablets now). Putting 2 apps side by side and changing the dimensions of Fenix when opened should work correctly.

Also, I use a foldable device (Samsung ZFold3) as my daily driver but @Yourhopegaming if you can confirm it working as well that'd be great! 😃

**Comment by Yourhopegaming** [comment] 2022-12-15 00:50
@SoftVision-LorandJanos @zmckenney It appears that it is working in Nightly thanks for your help for fixing this issue it was very annoying. Sorry for the late reply

**Comment by amocirean** [comment] 2022-12-16 07:14
Hello!
Using a Folded Device Emulator in Android Studio with Android 13, the issue is not occurring in Firefox 109.0b1 or Nightly 110.0a1.
Based on the results and the previous comments, I will close this issue as fixed.

Thanks!

**Closed by amocirean** 2022-12-16 07:14 UTC
Labels: 🐞 bug, eng:qa:needed, needs:triage
