### ISSUE TITLE
[Bug] Share button in Custom Tab in Feedly is too big

### ISSUE THREAD

**Issue by cypressious** [mozilla-mobile/fenix#13416] opened 2020-08-08 11:01 UTC
## Steps to reproduce

Open Custom tab in Feedly app.

### Expected behavior

The share button has the correct size.

### Actual behavior

![Screenshot_20200808-125726](https://user-images.githubusercontent.com/1191816/89708380-e59f1d80-d976-11ea-805a-e84fb1467df4.png)

The share button is too big

### Device information

* Android device: Sony Xperia XZ Premium
* Fenix version: Nightly 200808 06:09 (Build #2015756723)
AC: 54.0.20200807130552, 1d5e94f0d
GV: 81.0a1-20200806033456
AS: 61.0.10

**Comment by cadeyrn** [comment] 2020-08-08 11:08
Duplicate of #10451.

**Closed** 2020-08-08 11:44 UTC
Labels: needs:triage, 🐞 bug
