### ISSUE TITLE
[Bug] Autofill not working with Bitwarden

### ISSUE THREAD

**Issue by SinTan1729** [mozilla-mobile/fenix#16583] opened 2020-11-15 09:17 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to any website with login field
2. Choose Autofill with Bitwarden from the drop-down
3. Select the login entry from Bitwarden

### Expected behavior
Login should be put in.
### Actual behavior
Nothing happens, fields stay blank.
### Device information

* Android device: Redmi K20 (Android 10)
* Fenix version: Nightly 201114 17:01
* Bitwarden version : 2.6.2

**Comment by hakkikaancaliskan** [comment] 2020-11-15 09:21
Similar to #7742
What is your device/fenix language?

**Comment by SinTan1729** [comment] 2020-11-15 09:54
It's English (United States).

**Comment by 9ary** [comment] 2020-12-03 15:09
I've been facing the same problem, whenever whenever Bitwarden needs to be unlocked, autofill fails and the dropdown stops showing up until I refresh the page (I can then autofill directly from the dropdown). I have a OnePlus 7T, Android 10, system language is US English and Nightly is configured to use the system language. This used to work fine.

**Comment by wallismith** [comment] 2020-12-03 15:48
@hakkikaancaliskan I have the same exact issue as @9ary, but since I'm on Android 11, I use the keyboard inline autofill option instead of the drop-down option.

Device information:

    Android device: Google Pixel 3
    Android version : Android 11
    Fenix version: Nightly 201202 17:05
    Device/Fenix language: English (United States)
    Bitwarden version : 2.7.0

Note: Firefox Focus is the only Firefox browser that works consistently, 100% of the time.

**Comment by FuLygon** [comment] 2020-12-05 10:34
im facing the same problem, this does not happen in Firefox stable i think, IceWeasel which is a fork of fenix didn't have this bug as well

**Comment by SinTan1729** [comment] 2020-12-05 16:30
> @hakkikaancaliskan I have the same exact issue as @9ary, but since I'm on Android 11, I use the keyboard inline autofill option instead of the drop-down option.
> 
> Device information:
> 
>     Android device: Google Pixel 3
>     Android version: Android 11
>     Fenix version: Nightly 201202 17:05
>     Device/Fenix language: English (United States)
>     Bitwarden version: 2.7.0
> 
> Note: Firefox Focus is the only Firefox browser that works consistently, 100% of the time.
> 

That seems like an issue in the Gecko engine then, since Firefox Focus is based on Chromium.

**Comment by 9ary** [comment] 2020-12-05 16:38
> That seems like an issue in the Gecko engine then, since Firefox Focus is based on Chromium.

Focus uses GeckoView since version 7.0, just like Fenix.

**Comment by SinTan1729** [comment] 2020-12-17 14:22
I just disabled Autofill service in my phone's settings and set it back to Bitwarden. It seems to have fixed the issue. I'll have to check if it's a temporary fix though, or if it survives a reboot.

**Comment by 9ary** [comment] 2020-12-17 14:28
That didn't seem to work at all for me.

**Comment by hakkikaancaliskan** [comment] 2020-12-17 20:44
As i wrote earlier inline autofill was not working for me on firefox beta but working fine on nightly.

**Comment by 9ary** [comment] 2020-12-23 14:34
Is information available anywhere on how to bisect Fenix? Since this is a regression I'd like to help investigate this further and get it solved quickly as it is a daily annoyance for me.

**Comment by ThracianKnight1907** [comment] 2021-01-17 14:04
I'm seeing this bug as well on Firefox v85.0.0-beta8. I remember this used to work at some point though

**Comment by Ruin0x11** [comment] 2021-01-19 17:39
Same problem. I think Chrome has an option to trigger the autofill prompt as a context option. I'm getting tired of having to unlock my vault twice to log in to a new site.

**Comment by SinTan1729** [comment] 2021-01-20 05:52
> Same problem. I think Chrome has an option to trigger the autofill prompt as a context option. I'm getting tired of having to unlock my vault twice to log in to a new site.

Yes. This problem has been unresolved for too long. I had to switch to Brave for the time being.

**Comment by vic-blt** [comment] 2021-01-25 09:38
Same issue on "Fennec" version.
It was perfectly working months ago.

**Device information**
   
- Android device: OnePlus 7T Pro
- Android version: Android 10
- Fennec version: 84.1.4
- Bitwarden version: 2.6.1

**Comment by neekless** [comment] 2021-02-04 02:21
This is becoming quite a nuisance as I have passwords randomly generated by bitwarden and the autofill doesn't work. Very tempted to install an older version of Fenix to fix this but everyone knows this is a bad idea when it comes to browsers. However no one from the team seems to be able to address this.

**Comment by iamperson347** [comment] 2021-02-06 13:11
Not sure if this is a firefox issue or bitwarden. However, when I fail to get an autofill box, sometimes clicking the menu (3 dot icon) and the re-selecting the field on the webpage triggers the autofill to show up.

**Comment by iamperson347** [comment] 2021-02-06 13:16
Not sure if this is a firefox issue or bitwarden. However, when I fail to get an autofill box, sometimes clicking the menu (3 dot icon) and the re-selecting the field on the webpage triggers the autofill to show up.

**Comment by Mikaka27** [comment] 2021-02-06 13:38
> Not sure if this is a firefox issue or bitwarden. However, when I fail to get an autofill box, sometimes clicking the menu (3 dot icon) and the re-selecting the field on the webpage triggers the autofill to show up.

I think that's not what the issue is. For me the autofill box does show up, but when I go to bitwarden app and select login, I'm returned to firefox but login/password fields are left empty.

**Comment by iamperson347** [comment] 2021-02-06 15:21
Possibly related to https://github.com/bitwarden/mobile/issues/1223

**Comment by smithed** [comment] 2021-02-11 06:24
someone on that issue just posted that they have the same issue with keepass. sounds like bitwarden works with other browsers and other password managers _dont_ work with firefox. I only started having this issue relatively recently, its super disappointing to see its been open coming up on 3 months. :(

**Comment by neekless** [comment] 2021-02-11 10:48
The face that the same version of bitwarden works on v83.1.0 and not on anything above v84.0.0-beta.1 shows the problem is with Fenix. A GV or AC change is to blame.

**Comment by 9ary** [comment] 2021-02-11 10:57
This is the changelog for geckoview's autofill implementation. https://hg.mozilla.org/mozilla-central/log/tip/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/Autofill.java

Only two commits modified it around the time this problem appeared, I'd probably bet on this one: https://hg.mozilla.org/mozilla-central/rev/5928e980f6590058e1d779b55828304d7f4f22ad.

**Comment by 9ary** [comment] 2021-02-12 17:30
The bug was introduced with 35d0a78cc0f13102389b5d8112fbceb30608819d, "Update Android Components version to 66.0.20201105143119.". Next step is bisecting AC then.

**Comment by 9ary** [comment] 2021-02-12 19:32
https://github.com/mozilla-mobile/android-components/commit/7899ed6bbd64acbdc347d5ae6d50624551d944b8 is the commit that introduced this regression. I can confirm that reverting this commit on top of the latest Fenix and AC commits fixes this problem.
The latest GVE build is also unaffected.

**Comment by 9ary** [comment] 2021-02-12 19:41
@csadilek I'm tagging you because you committed that change, any insight would be helpful.

**Comment by csadilek** [comment] 2021-02-16 19:39
@9ary Thanks for digging into this. The change you linked above releases the GeckoView when the application stops, which is the right thing to do. However, this causes autofill to no longer work when switching back from the `Bitwarden` application to Fenix, which we need to fix. I will move this ticket and start a discussion with the GV team about this.

FWIW, autofill will work with Bitwarden if "inline autofill" is enabled in Bitwarden's settings, because then there is no app switch involved, but that's of course limited to the keyboards that support that.

**Comment by csadilek** [comment] 2021-02-16 19:41
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1693152

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2021-02-16 19:41 UTC
Labels: Feature:Logins, 🐞 bug

**Comment by 9ary** [comment] 2021-02-16 19:46
> @9ary Thanks for digging into this. The change you linked above releases the GeckoView when the application stops, which is the right thing to do. However, this causes autofill to no longer work when switching back from the `Bitwarden` application to Fenix, which we need to fix. I will move this ticket and start a discussion with the GV team about this.

Thanks!

> FWIW, autofill will work with Bitwarden if "inline autofill" is enabled in Bitwarden's settings, because then there is no app switch involved, but that's of course limited to the keyboards that support that.

I have it enabled, but you still have to go through the app when the password store is locked. It was the same on previous Android versions with the Android autofill menu, inline autofill merely moves this functionality to the keyboard.

**Comment by csadilek** [comment] 2021-02-16 19:58
> It was the same on previous Android versions with the Android autofill menu, inline autofill merely moves this functionality to the keyboard.

Sure, understood. Only mentioned it to point out that it's the application switch that breaks bit.

**Comment by smithed** [comment] 2021-02-17 01:52
Given that it sounds like this is a more in-depth fix, is there any way the regression could be temporarily fixed for the next build by going back to the old way (not releasing GeckoView) and then fixing both issues at once later on?
Obviously I have no idea what is actually involved in this or what problem was solved by releasing it, but as others have pointed out it is really annoying and from my view as a user, it doesn't seem like I minded when GeckoView wasn't released :)

**Comment by FuLygon** [comment] 2021-07-09 13:07
It been half a year, did anyone even look into this yet or this issue was ignored

**Comment by StevenRudenko** [comment] 2021-07-09 13:10
seems it is a Bitwarden issue, as 1password works fine (they don't hide browser (no onStop() event in this case and no issue)

**Comment by FuLygon** [comment] 2021-07-09 13:16
> seems it is a Bitwarden issue, as 1password works fine (they don't hide browser (no onStop() event in this case and no issue)

It not bitwarden issue cuz it work fine on other browser, even old version of firefox work (i can't remember which version, i used to downgrade and it still work), technically it just not able to fill password **directly** from the app, password fill normally from drop down list once vault was unlocked

**Comment by smithed** [comment] 2021-07-09 13:44
> seems it is a Bitwarden issue, as 1password works fine (they don't hide browser (no onStop() event in this case and no issue)

 

Is that the case even if your 1password vault is locked? Firefox works fine as long as you logged into and unlocked bitwarden _before_ attempting to use your web browser.

 

As I understand it:

The problem is that when you need to log into your vault the active app switches to bitwarden and android tells firefox its no longer in front. The change above then closes out the geckoview, whatever that actually means, and presumably reopens it when firefox is back in the foreground, but in the process whatever autofill sequence is supposed to happen gets interrupted, causing you to be in a state where bitwarden is now ready to log in but firefox is no longer asking it to. You can refresh the page which resets the autofill process, and sometimes by clicking back and forth between username, password, and other fields on the page you can trick firefox into restarting autofill, but its unreliable.

Personally I gave up on this a few weeks ago and switched to Vivaldi. It's not quite as good as Firefox but it's good _enough_. I just have Firefox in the background so I can send pages from my desktop to my phone. Plus if this issue gets fixed it's easy to switch back.

**Comment by Ruin0x11** [comment] 2021-07-09 16:50
This issue has caused me to switch to Brave whenever I need to autofill a password.

Please fix this.

**Comment by FuLygon** [comment] 2021-07-09 17:11
There a workaround which I been using for the past couple of month, when unlocked the vault, instead of picking password to fill from the app, just go back after unlocking the vault, then pick the password to fill from the drop down list, if I pick password from the app, this cause the drop down list to disappear until I refresh the page. Don't know if this gonna work for everyone but atleast it work for me even though it pretty annoying to get used to. 

Hope this get fix soon, I try to stick with firefox just because of the extension support, otherwise I might have switch to something else.

**Comment by 9ary** [comment] 2021-07-09 17:31
Yes this works reliably, something's wrong with Firefox (likely a race condition during onResume or onRestart).

**Comment by Qrbaker** [comment] 2021-09-23 01:28
Oddly, I have found that bitwarden autofill works fine if, once you have unlocked the app, you navigate back to the browser _without selecting the login_; instead selecting the login from the keyboard toast.

**Comment by kloklojul** [comment] 2022-01-15 07:35
Still not working even years later

**Comment by ctbull2** [comment] 2022-01-20 04:32
I had to stop using Firefox on mobile due to this bug.  Strange that the issue only manifested for me in the last few months when it looks like the issue has existed for others for a long time.

**Comment by kloklojul** [comment] 2022-02-05 06:15
Why is this closed when this is still an on going Bug?

**Comment by 9ary** [comment] 2022-02-05 08:47
It's been moved to bugzilla because the bug is in geckoview, not Fenix. https://github.com/mozilla-mobile/fenix/issues/16583#issuecomment-780072691

**Comment by neekless** [comment] 2022-02-07 01:06
The priority seems strangely low for this issue. It's been quite some time and you're breaking standard Android behavior.
