### ISSUE TITLE
about:config Cannot Complete Request

### ISSUE THREAD

**Issue by 01bd881d** [mozilla-mobile/fenix#15947] opened 2020-10-16 00:21 UTC
## Steps to reproduce
Enter about:config in url bar and hit enter (I can't configure a proxy, there no addons compatible for the new version and without about:config theres no way to configure it)

### Expected behavior
Open up about config page

### Actual behavior
![e7778b3d-10ce-4e6d-ae9f-f36af9457165](https://user-images.githubusercontent.com/68550777/96198567-9d2e4e00-0f2b-11eb-8888-b5be3566dddf.jpg)

resource://android/assets/low_and_medium_risk_error_pages.html?&title=Cannot+Complete+Request&button=Try+Again&description=%3Cp%3EAdditional+information+about+this+problem+or+error+is+currently+unavailable.%3C%2Fp%3E&image=&showSSL=false&badCertAdvanced=Advanced%E2%80%A6&badCertTechInfo=%3Clabel%3ESomeone+could+be+trying+to+impersonate+the+site+and+you+should+not+continue.%3C%2Flabel%3E+%3Cbr%3E%3Cbr%3E+%3Clabel%3EWeb+sites+prove+their+identity+via+certificates.+Firefox+does+not+trust+%3Cb%3Eabout%3Aconfig%3C%2Fb%3E+because+its+certificate+issuer+is+unknown%2C+the+certificate+is+self-signed%2C+or+the+server+is+not+sending+the+correct+intermediate+certificates.%3C%2Flabel%3E&badCertGoBack=Go+Back+%28Recommended%29&badCertAcceptTemporary=Accept+the+Risk+and+Continue

### Device information

* Android device: Huawei P8 Lite (Android 5.0)
* Fenix version: 81.1.4 (Build #2015768387)

**Comment by liuche** [comment] 2020-10-16 00:28
Dupe of #7865

**Closed by liuche** 2020-10-16 00:28 UTC
Labels: needs:triage, 🐞 bug
