### ISSUE TITLE
Dark mode on all websites like Opera or Samsung Internet

### ISSUE THREAD

**Issue by moizahmed97** [mozilla-mobile/fenix#7330] opened 2019-12-21 10:37 UTC
### Why/User Benefit/User Problem
Dark mode is all the rage now, however most websites still have the blinding white background 
a browser side dark mode that darkens the background and changes certain CSS properties of text would be if immense help for all users
### What/Requirements
A button that enables browser sided dark theming just as it has been done in Samsung Internet (Android browser) or on in the new version of Opera on android

**Comment by kbrosnan** [comment] 2019-12-21 15:37
Duplicate of #2139

**Closed by kbrosnan** 2019-12-21 15:37 UTC
Labels: 🌟 feature request
