### ISSUE TITLE
[Bug] history page briefly flashes when navigating away from a tab 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#9868] opened 2020-04-11 20:25 UTC
## Steps to reproduce
Open overview
open a page from history in 3dot menu
open overview
### Expected behavior
overview opens
### Actual behavior
history page opens. then all icons load and the history page disapears and overview opens
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment] 2020-09-01 18:35
I am not seeing this anymore, can be closed

**Comment by softvision-miralobontiu** [comment] 2020-10-20 13:11
I'll close this, as I cannot reproduce this either on the 10/20 Nightly build.

**Closed by softvision-miralobontiu** 2020-10-20 13:11 UTC
Labels: needs:triage, ux:motion-design, 🐞 bug
