### ISSUE TITLE
Support of 3rd party password manager

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#87] opened 2018-12-03 13:03 UTC
### Why/User Benefit/User Problem
Allow users to fill in their logins from their preferred password manager, e.g. LastPass

### What / Requirements
Show dialog/prompt to use 3rd party app to fill in login information

### Acceptance Criteria (how do I know when I’m done?)
- Password manager app can access Fenix
- Fenix offers dialog to select preferred pwd manager
- Fenix fills out logins automatically
- Focus app parity

**Comment by lime124** [comment] 2019-02-01 01:21
@bbinto as far as I can tell, all the UI is going to be either via the 3rd party apps or something provided by the OS. It doesn't seem like there's anything for UX to provide to simply access their passwords in the app of their choice. @colintheshots am I missing something?

@bbinto If you are you wanting some sort of specific Fenix UI that is getting new users to go and download Lockbox, I think that should be a separate GitHub issue from this one which is just letting people get access to whatever they are already using. 

Am I misunderstanding something?

**Comment by bbinto** [comment] 2019-02-08 19:35
Next Lockbox update early March

**Comment by bbinto** [comment] 2019-02-08 19:40
Idea re: flow
- Keep password in library, detect if Lockbox is installed, if not, promote, otherwise open Lockbox directly


GV has implemented Autofill API

**Comment by bbinto** [comment] 2019-02-08 19:44
@linuxwolf to confirm if his test was done on Focus GV, and post results here.

**Comment by linuxwolf** [comment] 2019-02-08 21:27
Original tests may not been using the GeckoView engine in Firefox.

However, after verifying "Latest GeckoView" is toggled on, can confirm that Lockbox can fill into a page on Firefox Focus for Android.

**Comment by sandysage** [comment] 2019-02-27 19:56
I think this is also related: https://github.com/mozilla-mobile/reference-browser/issues/574

**Comment by sandysage** [comment] 2019-02-27 19:59
Just to close the loop here, I believe we're planning to use [the autofill api](https://developer.android.com/guide/topics/text/autofill) as @bbinto mentions above, and not the accessibility route. Further discussion in #550.

**Comment by bbinto** [comment] 2019-03-13 11:51
I'd like to suggest that this ticket/meta/epic is about the support of 3rd party passwords in general, i.e Autofill API. 

@sandysage your suggestions, covered in #821 and #550 is def. a wonderful "nice to have" but not required for MVP. We'll keep it in the backlog and personally, I think, at a high priority.

@sandysage - I wonder if your engineers could help out with this work instead?

**Comment by bbinto** [comment] 2019-03-13 11:56
@pocmo and @st3fan - has the required A/C work been done (support of 3rd party password manager), and if so, has this been loaded into Fenix nightly yet?

**Comment by mheubusch** [comment] 2019-04-05 21:10
@vesta0 do we need Fenix stories for this? The only stories seem to be for reference browser.

**Comment by bifleming** [comment] 2019-05-03 23:08
@vesta0 are we not doing this Meta? what's the path forward?

**Comment by reinhart1010** [comment] 2019-05-18 08:18
Duplicate: https://groups.google.com/forum/m/#!topic/fenix-nightly/ImcINWPjbB8

**Comment by reinhart1010** [comment] 2019-05-20 08:38
Duplicate: https://groups.google.com/forum/m/#!topic/fenix-nightly/Yp0bDF47YiA

**Comment by IndefiniteBen** [comment] 2019-05-20 21:11
To summarise the Google groups (though they aren't clear)/ explain the issue:
The autofill API correctly pops up, but shows password for the package name instead of the URL of the site. 

Using the 'draw over other apps' method of Lastpass filling, when I press search it puts "Firefox Preview" in the search box. If I search for a site and tap it, Lastpass asks me if I want to associate that site with the app "Firefox Preview". I searched for disqus and added it this way, which is why you see that listed along with my firefox sync account/s (I need to clean up my passwords...). You can't see the text because I'm using the Android Q Beta and dark mode, which is also broken in other apps.
![Screenshot_20190520-223155](https://user-images.githubusercontent.com/17594572/58052219-84621300-7b54-11e9-9d13-92516460ccc9.png)

**Comment by vesta0** [comment] 2019-05-21 04:10
We are in the process of getting 3rd party managers work in Fenix.

**Comment by sv-ohorvath** [comment] 2019-05-27 08:33
See https://github.com/mozilla-mobile/fenix/issues/1635#issuecomment-496128571

**Comment by bifleming** [comment] 2019-05-29 17:45
@vesta0 can you provide info on what is blocking this?

**Comment by leonardehrenfried** [comment] 2019-05-30 06:09
I'm happy to provide test cases and/or do qa for this feature, as I'm missing it a lot.

**Comment by vesta0** [comment] 2019-05-30 21:31
@bifleming we are waiting for password manager providers to whitelist Fenix in their upcoming releases.

**Comment by leonardehrenfried** [comment] 2019-05-31 08:19
@vesta0 Does it make sense for us as paying customer of these providers (Lastpass in my case) to ask for support in order to speed this up?

**Comment by vesta0** [comment] 2019-05-31 13:54
Thanks @leonardehrenfried I believe the work is already in progress or ready to land on their end :)

**Comment by vesta0** [comment] 2019-06-13 04:49
Hi @sv-ohorvath we expect that Fenix has now been whitelisted on 1password, dashlane,  Bitwarden, and LogMeIn. Would you please verify? 

I am not sure about LastPass yet so it would be great to check that also. Thanks!

**Comment by IndefiniteBen** [comment] 2019-06-13 10:25
I just tried with LastPass and get the same situation as in my previous comment.

**Comment by sv-ohorvath** [comment] 2019-06-13 12:31
Hi @vesta0, I checked all the above. No changes indeed for any of them:
LastPass: 
- when there are no matching sites, a popup "no matching websites" should be displayed with a button to add the website you are on. (works on Fennec)
- when there are some other saved credentials, you can associate them with Fenix. But Fenix will show all credentials saved when there are no matches.
- where you have associated a login with a matching website, it will only fill-in the password, the first time. The second time it works.

BitWarden is still the same v.1.22.0, from Feb 4, 2019, so it's not fixed yet, still the same behavior as before.

LogMeIn's password manager is LastPass.

DashLane: not showing any saved logins (works with Fennec).

1password: You have to manually add websites in 1pass, but there are no logins suggestions in Fenix. Works with Fennec.

**Comment by vesta0** [comment] 2019-06-13 16:06
Thank you @IndefiniteBen and @sv-ohorvath for testing. I will follow up with them.

**Comment by arunsathiya** [comment] 2019-06-29 14:38
Thank you for your efforts in making third-party password managers available. I have nudged 1Password's Android team to take a look at this as well - https://discussions.agilebits.com/discussion/105040/support-for-the-new-firefox-preview-aka-firefox-fenix/p1?new=1

**Comment by arunsathiya** [comment] 2019-06-29 14:43
Actually, giving it another try, I see 1Password's autofiller now. Unsure why it did not appear on the first attempt.

**Comment by vesta0** [comment] 2019-06-29 16:36
Thank you @arunsathiya for nudging and testing :)

**Comment by tdsmith** [comment] 2019-06-29 16:40
The Lastpass update I received from Google Play Store this morning now shows the correct suggestions for Firefox Preview. 🎉

**Comment by vesta0** [comment] 2019-06-29 16:57
Great! Thanks for letting us know @tdsmith !

**Comment by leonardehrenfried** [comment] 2019-06-30 13:19
@tdsmith Are you on the beta app of Lastpass or the ordinary release?

**Comment by diablogriff** [comment] 2019-06-30 13:36
I'm on nightly resdm

**Comment by IndefiniteBen** [comment] 2019-07-01 10:43
I can second what @tdsmith said. I had to opt-in for the Lastpass beta and wait for the update first, but it worked immediately after installing the beta. Hopefully this change makes it to the stable Lastpass soon!

**Comment by theovds** [comment] 2019-07-01 17:15
FYI: Today I received an update for Lastpass and it worked immediately. I'm not using the beta version.

**Comment by cpeterso** [comment] 2019-07-01 18:54
> FYI: Today I received an update for Lastpass and it worked immediately. I'm not using the beta version.

@theovds - What is the version number of the (non-beta) Lastpass that works correctly for you?

**Comment by theovds** [comment] 2019-07-01 19:05
> 
> 
> > FYI: Today I received an update for Lastpass and it worked immediately. I'm not using the beta version.
> 
> @theovds - What is the version number of the (non-beta) Lastpass that works correctly for you?

It's version 4.10.4345 (Built: 6/27/19)

**Comment by sv-ohorvath** [comment] 2019-07-02 12:48
FYI: The 3rd party apps like LastPass and Bitwarden won't work with the new Nightly package name (org.mozilla.fenix.nightly). The PlayStore version the (public release version) works now with both.

**Comment by cpeterso** [comment] 2019-07-02 17:40
> The 3rd party apps like LastPass and Bitwarden won't work with the new Nightly package name (org.mozilla.fenix.nightly). The PlayStore version (the public release version) works now with both.

@vesta0 and @sarentz - We should ask LastPass and Bitwarden (and others?) to whitelist our pre-release package names (`org.mozilla.fenix.nightly` and `org.mozilla.fenix.beta`?) and Reference Browser. Who do you recommend reaches out to these third-party password managers?

When we asked Google to whitelist Fenix for Android WebAuthn, we gave them Fenix's pre-release package names.

**Comment by vesta0** [comment] 2019-07-02 21:36
@cpeterso the package name is the same right now between prod and nightly so it might be a different problem. @st3fan what do you think? 

I can reach out to them once we set up our separate nightly and beta channels.

**Comment by vesta0** [comment] 2019-08-08 23:19
Hi @sv-ohorvath would you please re-test this with 1password, dashlane, and Bitwarden and let us know the most recent status before I reach out to them? Thanks so much!

**Comment by andreicristianpetcu** [comment] 2019-08-09 10:40
@vesta0 I tested with Bitwarden and it filtered the password corredtly based on the site! Nightly build.

**Comment by matteocontrini** [comment] 2019-08-09 10:51
I can confirm that 1Password works as well

**Comment by sv-ohorvath** [comment] 2019-08-12 11:13
Cannot search the list of all passwords on 1Pass saved from other apps. Can only see the passwords saved from Fenix. Chrome can search through all the website-related items in the vault.
Dashlane only shows the autofill pop-up for Fenix, there should also be a hovering bubble (the app logo hovering) to search/add new passwords, like on Chrome.
Bitwarden works ok with new/existing passwords.
the device used: Pixel 3 (Android 9)

**Comment by vesta0** [comment] 2019-08-12 14:43
Thanks @sv-ohorvath do 1Pass and Dashboard work similarly to Chrome in Fennec?

**Comment by sv-ohorvath** [comment] 2019-08-13 08:04
Hey @vesta0, tried to find out why they didn't work the same and it seems it's a time matter, the other saved passwords will appear but they need some time, Chrome and Fennec don't show the others immediately either. So all 3: Dashlane, 1Password, Bitwarden seem to work fine on Fenix Nightly. Should we close this?

**Comment by vesta0** [comment] 2019-08-13 21:09
Thank you @sv-ohorvath and all of our contributors who helped test this!

**Closed by vesta0** 2019-08-13 21:09 UTC
Labels: Feature:Passwords, must, 🌟 feature request, 🙅 waiting

**Comment by linuxandria** [comment] 2020-01-24 14:04
I can confirm this isn't fixed.
Latest LastPass beta isn't showing any AutoFill prompts, and it's been granted accesibility permission

**Comment by st3fan** [comment] 2020-01-24 14:18
@vesta0 it may be a good idea to re-test this - i am pretty sure we asked all of the password managers to whitelist all our build flavors but that was a long time ago so maybe it is a good idea to verify again

**Comment by 3eresa** [comment] 2020-01-29 03:06
@st3fan I just tested LastPass stable version 4.11.4.4946 on the latest Play Store Preview Nightly 200128 18:00 and Preview 3.0.2 LastPass will not fill through the autofill api. It does work on Chrome stable and Firefox version 68.4.2 not sure if it is a whitelist issue or what.

Tested on Essential PH-1 Android 10

**Comment by jacobhanson1010** [comment] 2020-02-10 03:44
Having the same issue with nightly and preview using Lastpass. It's the only thing keeping me from using preview!

**Comment by sys9kdr** [comment] 2020-02-20 15:31
I have the same issue with preview nightly and LastPass. LastPass says "LastPass was unable to auto-fill this app".

Firefox Nightly
Version 	75.0a1
Build ID 	20200218093736

LastPass 4.11.4.4946

![Screenshot_20200221_002406_org mozilla fenix nightly](https://user-images.githubusercontent.com/1529486/74949746-83427700-5441-11ea-862d-b3ccfcf863d4.jpg)

**Comment by 3eresa** [comment] 2020-03-12 12:09
Still unable to use LastPass through the auto fill API on Nightly 200311 18:01 with LastPass version 4.11.7.5061 on Pixel 3 Android 10 build QQ2A.200305.002. Preview version 3.2.1 doesn't work. Stable version 68.6.0 works fine as does latest Chrome. This is the only thing preventing me from adopting the new Firefox.

**Comment by leonardehrenfried** [comment] 2020-03-13 10:18
@3eresa: This isn't going to be the answer you are expecting but all my password manager problems went away after I switched from Lastpass to Bitwarden. Therefore I suspect a Lastpass problem, whose I perceived to be getting worse and worse, hence me switching.

**Comment by 3eresa** [comment] 2020-03-18 13:24
Still not working with latest LastPass on most recent Nightly 200318 06:01. Yes I understand I could change personal password managers to avoid this issue however my work uses LastPass Enterprise and there is not much I can do about that. There are nearly 17 million LastPass users. This is going to be an issue when this goes from development releases to final if it's not resolved.
