### ISSUE TITLE
Crash reporter UI problems on Android 10 and 11

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#25223] opened 2022-05-12 19:53 UTC
`about:crashparent`, `about:crashcontent`, and `about:crashgpu` behave differently on Android 10 and 11 compared to (the correct behavior on) Android 8.1, 9, and 12. Fixing this bug seems like a high priority because we may be missing out on important crash data from Android 10 and 11 users (who make up about 60% of all Android users).

These three different types of crashes all have slightly different behavior, but I will only provide detailed examples for the `about:crashparent` scenario here. I can provide more details about the incorrect behavior of `about:crashcontent` or `about:crashgpu`, if needed.

1. After loading `about:crashparent` on Android 10 or 11, the Fenix app disappears. There is no indication that Fenix crashed, other than three tiny ⚠️ notification icons appear in the system status bar:

![image](https://user-images.githubusercontent.com/629193/168155912-04c1ef90-2031-481d-bce5-33957f55de4c.png)

The expected behavior is that Fenix should show a "Sorry" dialog with an option to submit a crash report:

![image](https://user-images.githubusercontent.com/629193/168156165-e7a6614a-1ff0-4d92-9d4d-59c4b4e634f7.png)

2. Opening the notification drawer shows THREE notifications about the Fenix crash:

![image](https://user-images.githubusercontent.com/629193/168155974-9911945e-f5de-435c-bdcc-d2f6e3f94ff2.png)

The “Sending crash report to Mozilla” notification has an animated progress bar as if a crash report is being submitted without user permission! Is a crash report being uploaded without user consent? Nothing happens if you tap the “Sending” notification.

Nothing happens if you tap the first “Sorry” notification. If you tap the second “Sorry” notification, a dialog pops up with an option to submit a crash report and/or restart Firefox:

![image](https://user-images.githubusercontent.com/629193/168156335-ab9ffdc3-a8b7-4819-8342-de36fb0a4614.png)

If you expand the second “Sorry” notification instead of tapping it, a dim “Report” button is revealed: 

![image](https://user-images.githubusercontent.com/629193/168156576-5e4da063-4b90-497e-bff6-de0705bd384b.png)

If you tap the “Report” button, the notification drawer closes and reveals the home screen. Nothing seems to happen, but a new “Sending” notification appears in the notification drawer if you open it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20454)

**Comment by cpeterso** [comment] 2022-05-12 19:59
This bug might be the same as https://github.com/mozilla-mobile/fenix/issues/23088.

Jira issue: https://mozilla-hub.atlassian.net/browse/FNXV2-20454

**Comment by cadeyrn** [comment] 2022-05-12 20:08
> Opening the notification drawer shows THREE notifications about the Fenix crash

See also #16517.

**Comment by rocketsroger** [comment] 2022-07-11 16:58
I think the first step is to be clear on what is happening.  I'll update the string as specified in https://github.com/mozilla-mobile/android-components/issues/10112.

**Comment by rocketsroger** [comment] 2022-07-19 20:06
Confirmed with Android 11, this is not reproducible anymore.  Closing this and will implement the new behaviour with [the issue linked above.](https://github.com/mozilla-mobile/fenix/issues/26080)

**Closed** 2022-07-19 20:06 UTC
Labels: needs:triage

**Comment by cpeterso** [comment] 2022-07-19 21:44
> Confirmed with Android 11, this is not reproducible anymore. Closing this and will implement the new behaviour with [the issue linked above.](https://github.com/mozilla-mobile/fenix/issues/26080)

@rocketsroger - Did you say on Slack that you could reproduce the three notifications on Android 10 (using an emulator)? Will the crash reporter changes in #26080 avoid the three notification problem on Android 10?

**Comment by rocketsroger** [comment] 2022-07-19 21:47
> > Confirmed with Android 11, this is not reproducible anymore. Closing this and will implement the new behaviour with [the issue linked above.](https://github.com/mozilla-mobile/fenix/issues/26080)
> 
> @rocketsroger - Did you say on Slack that you could reproduce the three notifications on Android 10 (using an emulator)? Will the crash reporter changes in #26080 avoid the three notification problem on Android 10?

Sorry, I wasn't clear.  I meant I could not reproduce the issue with emulator on Android 10.
