### ISSUE TITLE
[Bug] Bottom elements on websites are incorrectly positioned when address bar is hidden

### ISSUE THREAD

**Issue by kolaente** [mozilla-mobile/fenix#9371] opened 2020-03-24 18:18 UTC
## Steps to reproduce

1. Set the address bar position to top.
2. Go to a website with a bottom bar of some kind, I observed this at https://dev.to/fy09/golang-why-doesn-t-string-type-inherit-all-the-methods-of-strings-package-5ag2
3. Scroll a bit to the bottom to hide the address bar

### Expected behavior

The bottom elements on the website stay at the bottom of the screen

### Actual behavior

The bottom elements have a bottom margin of what seems to be the height of the address bar.

![Screenshot_20200324-191736_Firefox_Preview](https://user-images.githubusercontent.com/13721712/77462244-281af000-6e04-11ea-9e3a-a153cc9ecbfb.png)
![Screenshot_20200324-191742_Firefox_Preview](https://user-images.githubusercontent.com/13721712/77462245-28b38680-6e04-11ea-8686-9b5c4af21b0c.png)

### Device information

* Android device: Oneplus 6 with lineagos 16 (nightly build from 22-03-2020)
* Fenix version: 4.1.0 (Build #20771637)
36.0.2, 6638a3365
GV: 75.0-20200309155231
AS: 0.53.3

**Comment by hiikezoe** [comment] 2020-03-25 06:56
This is also a dup of #6940.

**Comment by liuche** [comment] 2020-03-31 01:08
Dupe of #9481

**Closed by liuche** 2020-03-31 01:08 UTC
Labels: needs:triage, 🐞 bug
