### ISSUE TITLE
[Bug] radio groups on first run are a mess in Talkback

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/fenix#9722] opened 2020-04-05 02:37 UTC
## Steps to reproduce
Install a fresh Fenix or delete your Fenix storage
Enable Talkback
Swipe through first run cards with radio groups

### Expected behavior
Swiping to the first option reads the whole thing and swiping again moves to the next option.

### Actual behavior
Swiping navigates the group then the internals of the group from the control to the label to description all before moving to the next radio option. 

### Device information

* Android device: Galaxy S10e
* Fenix version: Friday 4/3 @ 6:10 AM

For example, here's what I expect to hear when I get to the Protect Yourself radio choice:

Swipe right: "Not checked radio button. Standard. Blocks fewer trackers but allows pages to load normally. Double tap to activate." 
Swipe right: "Checked radio button. Strict recommended. Blocks more trackers for better protection and performance, but may cause some sites to not work properly. Double tap to activate." 

But what I actually get is this: 

Swipe right: "Standard. Blocks fewer trackers but allows pages to load normally. Double tap to activate." 
Swipe right: "Not checked radio button. Double tap to toggle."
Swipe right: "Standard"
Swipe right: "Blocks fewer trackers but allows pages to load normally."
Swipe right: "Strict recommended. Blocks more trackers for better protection and performance, but may cause some sites to not work properly. Double tap to activate."
Swipe right: "Checked radio button. Double tap to toggle."
Swipe right: "Strict recommended."
Swipe right: "Blocks more trackers for better protection and performance, but may cause some sites to not work properly."

See the difference? The first one is clean and quick and the second one is a mess. 

And it's the same basic problem for the "Theme" and "Take a position" cards but it might even be a little worse there actually. For the cards with image radio choices, the labels under the images aren't grouped with the image they belong to.

**Comment by asadotzler** [comment] 2020-04-05 02:39
This is an accessibility P2. The feature is available and works but is difficult to use because of inconsiderate focus/swipe behavior. This kind of bug prevents Fenix from being a delightful experience for users with disabilities.

**Comment by BranescuMihai** [comment] 2020-06-24 20:40
Seems like it's more difficult than initially expected, don't think I can finish it before code freeze so I'm unassigning myself. @mcarare have any thoughts on this? I know you have experience with accessibility issues

**Comment by sflorean** [comment] 2020-07-24 08:30
Testing results on Nightly 7/24 for the Protect Yourself radio choice:

Swipe right: "Checked Standard default. Standard. Pages will load normally. Double-tap to toggle."
Swipe right: "Not Checked Strict. Blocks more trackers, ads, and popups. Pages load faster, but some functionality might not work. Double-tap to toggle."

After swiping right a couple of times and reach to "Dark theme" selected, swiping again I got the following "No next link". 

@mcarare could you please, tell your opinion about the "No next link" item?

**Comment by mcarare** [comment] 2020-07-24 09:32
@sflorean That is the standard "end of page" announcement for Talkback, I suspect the screen was scrolled to a point where no other element is visible and added to the a11y tree. It should not reproduce at the same point if the screen is scrolled more. And either way, it's not directly related to radio buttons.

**Comment by sflorean** [comment] 2020-07-24 15:07
> @sflorean That is the standard "end of page" announcement for Talkback, I suspect the screen was scrolled to a point where no other element is visible and added to the a11y tree. It should not reproduce at the same point if the screen is scrolled more. And either way, it's not directly related to radio buttons.

After clear data, I'm not able to reproduce anymore. Closing as verified.

**Closed by sflorean** 2020-07-24 15:07 UTC
Labels: E5, Feature:Onboarding, P2, b:a11y, 🐞 bug

**Comment by abodea** [comment] 2020-08-25 13:36
Verified as fixed on **Fenix RC 80.1.0** with **Google Pixel 4 XL (11).**
