### ISSUE TITLE
FNX3-16834 ⁃ [Telemetry] Deleting a bookmarks folder

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#3174] opened 2019-06-05 17:39 UTC
This is leftover from the original issue: #974

As a product owner, I want to track how often users delete a bookmarks folder, so that I can understand how our users interact with folder management options.

We believe this feature is useful to users, and successful when
    % of users creating/deleting bookmarks or syncing bookmarks
    % of users opening website via bookmark increases

What questions will you answer with this data?
-Do users delete bookmark folders and how often.

Probes:
    Folder deleted

Dependencies
    Glean SDK (Event ping)

Acceptance Criteria (Added by PM)
    Event ping can be queried via re:dash
    We are sending telemetry events for the action listed in the requirements
    We have documented the telemetry
    We have asked a data steward to review the telemetry

**Comment by sblatz** [comment] 2019-06-26 21:10
This is blocked on https://github.com/mozilla-mobile/fenix/issues/3693

**Comment by AndiAJ** [comment] 2019-07-03 13:59
Hi, for deleting **only one folder** the problem is **verified as fixed** on the latest **`Fenix Build #11840608 from 2019-07-03`** using the following devices:
• OnePlus6T (Android 9) (Ping **97630faf-680f-4f0f-93e8-866c7af11cc7** from the logcat)
• Samsung Galaxy S8+ (Android 8) (Ping **0decdb64-18cc-4ace-8e3a-6782cf2bc594** from the logcat)
• Samsung Galaxy S7 (Android 7.0) (Ping **9efedc65-b0dc-4d43-9567-c4260cc42115** from the logcat)

On the other hand, I've tried the following:
•Delete multiple folders 
•Delete multiple folders along with a normal bookmark
As these event type pings aren't included in the Yaml I'm not sure if they are properly generated.

For deleting multiple folders the events ping looks like this:
 {
          "timestamp": 0,
          "category": "bookmarks_management",
          "name": "folder_remove"
        },
        {
          "timestamp": 22106,
          "category": "bookmarks_management",
          "name": "multi_removed"
        }

For deleting multiple folders along with a normal bookmark events ping looks like this:
 {
          "timestamp": 0,
          "category": "bookmarks_management",
          "name": "multi_removed"
        },
        {
          "timestamp": 21352,
          "category": "bookmarks_management",
          "name": "multi_removed"
        }

Please find attached and review the following documents:
OnePlus6T logcat - [OnePlus.txt](https://github.com/mozilla-mobile/fenix/files/3355235/OnePlus.txt)
[OnePlus6T pings from the dashboard](https://debug-ping-preview.firebaseapp.com/pings/00f03785-96eb-49f4-9a07-4426e0211a75/aj-bookfolder-07)
 
Samsung Galaxy S8+ logcat - [S8.txt](https://github.com/mozilla-mobile/fenix/files/3355248/S8.txt)
[Samsung Galaxy S8+pings from the dashboard](https://debug-ping-preview.firebaseapp.com/pings/04235d9d-f3ea-4bf2-8337-1719094df863/aj-bookfolder-05)

Samsung Galaxy S7 logcat - [S7.txt](https://github.com/mozilla-mobile/fenix/files/3355250/S7.txt)
[Samsung Galaxy S7 pings from the dashboard](https://debug-ping-preview.firebaseapp.com/pings/de934fe4-c50e-40aa-8161-db93dc6efee6/aj-bookfolder-06)

@sblatz & @vesta0 please be kind and confirm if this is related to only delete one folder of bookmarks and if the above mentioned 2 scenarios will follow up.
Also, please confirm if the undo will also be implemented separately.
As the multi-select feature for bookmark folders isn't working yet, I've used the workaround described in #1539 

Until your confirmation, I'll leave this ticket as it is.

**Comment by sblatz** [comment] 2019-07-03 17:51
This seems fine to me, but @vesta0 can you confirm?

**Comment by vesta0** [comment] 2019-07-03 19:09
@AndiAJ @sblatz this is sufficient, we like to know how often users interact with bookmark folders and delete them, don't need to track one vs multiple at this time. Thanks!

**Comment by AndiAJ** [comment] 2019-07-04 06:48
Many thanks for clarifying this topic, in this case I'll mark this as **QA verified** and close it.

**Closed** 2020-08-12 17:21 UTC
Labels: Feature:Telemetry, eng:qa:verified, must
