### ISSUE TITLE
[Bug] Tapping on Fenix icon after opening custom tab opens the custom tab

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#7939] opened 2020-01-26 11:16 UTC
## Steps to reproduce

* Open link in custom tab from app (e.g. Reddit)
* Press Android Home Button
* Tab on Fenix icon in App Launcher

### Expected behavior
* Fenix home page opens (or a tab in Fenix)

### Actual behavior
* Custom tab from app opens

### Device information

* Android device: Samsung S10e, Android 10
* Fenix version: Latest Nightly from playstore

**Comment by fluffyemily** [comment] 2020-02-21 15:15
I have also experienced this. Plus, if I interact with tabs in Fenix, after running through this scenario, then return to the original app, the custom tab shows the complete Fenix UI, not the custom tab that was expected.

**Comment by agi90** [comment] 2020-02-21 18:06
This bugs gets as far as making one app opening an other if you opened an app from the custom tab. E.g. for a while my Twitter app icon would open Reddit :(

**Comment by lnicola** [comment] 2020-04-18 08:12
Does this still happen? I haven't seen it in a while.

**Comment by sflorean** [comment] 2020-06-12 08:14
Tested on Nightly 6/11 and couldn't reproduce this issue on the following devices:
- Samsung Galaxy Note 10 (Android 10)
- Nokia 6 (Android 7.1.1).

**Comment by lnicola** [comment] 2020-06-12 08:22
I still haven't seen this in a while.

**Comment by liuche** [comment] 2020-06-12 22:01
Thanks! Sounds like we can close this.

**Closed by liuche** 2020-06-12 22:01 UTC
Labels: Feature:CustomTabs, P2, S2, needs:investigation, 🐞 bug
