### ISSUE TITLE
[Bug]: Toolbar swiping activates even in fullscreen videos when toolbar is not shown

### ISSUE THREAD

**Issue by kparal** [mozilla-mobile/fenix#27346] opened 2022-10-09 11:34 UTC
### Steps to reproduce

1. Go to **Settings -> Customize** and set **Scroll to hide toolbar** to **disabled** and **Swipe toolbar sideways to switch tabs** to **enabled** (the bug occurs only in this combination of settings)
2. Open **several tabs** (any websites)
3. Open websites with video, e.g. https://www.youtube.com (happens on other sites as well)
4. Rotate your phone to a **landscape** mode (this is an important step)
5. Play some video and switch it into **fullscreen**
6. See that the bottom toolbar is not shown during fullscreen video playback (which is correct).
7. Try to **swipe on the bottom edge** of the screen left and right, as if the toolbar was there. See that you actually **can swipe** there and switch to a different tab.
8. Back in the fullscreen video, try to use the progress bar slider to **move in the video forward and backward**. Depending on the how close is the slider to the bottom edge of the screen (depending on the website and perhaps your phone dimensions), sometimes it can get extremely tricky to move in the video instead of activating swiping on the invisible toolbar.
9. Repeat the whole process, but this time with **Scroll to hide toolbar** set to **enabled**. The problem doesn't appear. It only appears if the combination of both settings mentioned in step 1 is set as described.

### Expected behaviour

Toolbar swiping shouldn't work when the toolbar is not displayed (e.g. in a fullscreen video).

### Actual behaviour

Toolbar swiping works in a fullscreen video in the described situation, which makes seeking in video very hard.

### Device name

Samsung Galaxy A33

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

105.2.0

### Additional information

See a screencast of the problem below. In the second half of the video, you can see how difficult it is for me to seek to a different part of the video. My touches are interpreted as tab swiping.

https://user-images.githubusercontent.com/755451/194754619-fafd13e2-b958-44d5-b276-0f3d9b89bbd1.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21767)

**Comment by kparal** [comment] 2022-10-09 11:43
Please note: This problems **does not occur** if you use your phone in portrait mode, and the action of making a video fullscreen automatically switches it into the landscape mode. This bug occurs only if your phone is in landscape mode **before** you make the video fullscreen.

**Comment by fice-t** [comment] 2022-10-13 19:26
As requested by @Mugurell in #27346: this can also happen outside of fullscreen mode, however I've only been able to reproduce it on my physical device and not on an emulator. This may be due to physical/virtual differences, or it may be due to my device being a Samsung S21 FE which may do gestures differently than Google. Recording:


https://user-images.githubusercontent.com/13156601/195690369-8cbf8d75-4063-44dc-8b65-1ec9c54547ba.mp4

This only happens when navigation swipe gestures are enabled (either Samsung-style or Google-style), and not when the navigation buttons are enabled.

**Comment by Mugurell** [comment] 2022-10-14 06:35
The above might be a separate bug but I cannot reproduce on a OnePlus with navigation gestures. Will try testing on other devices.

**Comment by kparal** [comment] 2022-10-14 08:19
I can't reproduce the bug from @fice-t on my Samsung Galaxy A33 either.

**Comment by delia-pop** [comment] 2022-11-22 16:00
Verified fixed on latest Nightly 109.0a1 from 11/22 with Samsung Galaxy Note10 (Android 12). Switching tabs by swiping is no longer possible in full screen. Note that I was also not able to reproduce the behavior described by @fice-t while testing. 

https://user-images.githubusercontent.com/89388888/203361630-072a1cc2-b998-4aa3-bddf-40d5fab38291.mp4

**Closed by delia-pop** 2022-11-22 16:00 UTC
Labels: 🐞 bug, eng:qa:needed

**Comment by delia-pop** [comment] 2022-12-15 13:21
Also verified on Beta 109.0b1 with Lenovo Yoga Tab 11 (Android 11).
