### ISSUE TITLE
FNX-14637 ⁃ SPIKE (huawei) Can't set Firefox Nightly as default browser (stuck to Firefox release)

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#13457] opened 2020-08-10 13:42 UTC
Timebox to: 1 day

Spike Deliverables:
Investigate, determine whether we can do anything about it (create another ticket) OR close this issue.

## Steps to reproduce

1) Open Firefox, Settings
2) Confirm "Set as default browser" is enabled (it was from when it was still Fennec).
3) Open Firefox Nightly, Settings
4) Flip "Set as default browser"
5) Get attached settings screen - no way to select the default browser.

![Screenshot_20200810_122106_com android settings](https://user-images.githubusercontent.com/1104290/89788723-e58e5180-db1f-11ea-9b75-e9fdcb3f986b.jpg)

### Expected behavior

Able to make Nightly the default.

### Device information

* Android device: Huawei MediaPad M5 8
* Fenix version: Nightly

**Comment by liuche** [comment] 2020-08-15 00:28
We fixed #13827 (which is not the same issue, I understand) but may have been fallout from default browsing issues. Is this still showing up on the latest nightly?

**Comment by sv-ohorvath** [comment] 2020-08-17 08:45
We can't reproduce on Android 7 devices as Huawei MediaPad M3 (Android 7.0) or P9 lite, but can confirm the issue on a Huawei P20 lite (Android 9). This issue seems to be older and might be an OS-specific issue.

**Comment by gcp** [comment] 2020-08-17 11:31
It doesn't seem to be related to #13827 as it still occurs on current Nightly.

From the screenshot below, there are actually settings to set the Default browser, but the OS thinks it is Chrome. This makes me wonder if Huawei accidentally broke it in the OS and it's perennially stuck on what it was before the last OS update.

![Screenshot_20200810_121742_com android settings](https://user-images.githubusercontent.com/1104290/90391720-e37f4200-e08d-11ea-90f6-8517d4e23695.jpg)

**Comment by mcarare** [comment] 2020-10-12 12:56
With some additional investigation and taking into account de comment above, there seems to be no actionable item for this issue. Closing this.

**Closed by mcarare** 2020-10-12 12:56 UTC
Labels: Feature:Browsing, hershey, 🐞 bug
