### ISSUE TITLE
[Enhancement] create an informative page for about:config that explains why it doesn't work in the stable release

### ISSUE THREAD

**Issue by Pomax** [mozilla-mobile/fenix#14733] opened 2020-09-04 16:13 UTC
This can't _possibly_ be intentional, especially given that customized settings are basically nonexistent at the moment.

**Comment by Pomax** [comment] 2020-09-04 16:14
![photo_2020-09-04_09-14-24](https://user-images.githubusercontent.com/177243/92261870-13508700-ee8f-11ea-9477-d662a49fc740.jpg)

**Comment by s-ankur** [comment] 2020-09-04 16:43
Duplicate of https://github.com/mozilla-mobile/fenix/issues/7865.

About config is available in nightly as well as beta versions for now. Also note that due to some technical reasons about config is no longer used to alter UI related customisation, just internal behaviour in fenix

**Comment by Pomax** [comment] 2020-09-04 16:46
Then please consider this a signal that the about:config page in regular FF for Android should say what you just said. It shouldn't be a network error, but a page that goes "this option is only available on Nightly, please visit (playstore link) to install it" or the like.

**Comment by s-ankur** [comment] 2020-09-04 16:53
Yes, the error page does seem pretty uninformative.

**Comment by amkcpu** [comment] 2020-09-05 07:56
> the about:config page load in regular FF for Android should say what you just said

This is a great idea, giving more transparency.
Suggestion: Change the title of this issue and the description in the first comment so that this issue can be properly triaged and tracked. Maybe, they can implement this soon!

**Closed** 2020-09-16 23:17 UTC
Labels: needs:triage, 🐞 bug

**Comment by Pomax** [comment] 2020-09-17 04:09
@liuche did this land? (if so, is there a crosslink for the PR?)

**Comment by liuche** [comment] 2020-09-17 22:53
Dupe of #7865

**Comment by Pomax** [comment] 2020-09-18 16:33
No, it isn't. This issue acknowledges that about:config doesn't exist except in Nightly, and is for making sure that what folks _see_ when they mistaken go there has an informative page instead of a network error.
