### ISSUE TITLE
Select and open a link in text

### ISSUE THREAD

**Issue by ddarfantasy** [mozilla-mobile/fenix#16916] opened 2020-12-08 11:23 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
If I select a https link display in plain text, I want to have an option to open in a new tab without copying it first.
### How do you know that this problem exists today? Why is this important?
Saving my time to copy a link. I don't think it's hard to implement.
### Who will benefit from it?
Most users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9015)

**Comment by jonalmeida** [comment] 2023-01-27 21:57
Duplicate of #9956

**Closed by jonalmeida** 2023-01-27 21:57 UTC
Labels: feature request 🌟, Feature:TextSelection, Feature:Browsing
