### ISSUE TITLE
[Bug] Unstable scolling when toolbar position is set to 'top'

### ISSUE THREAD

**Issue by supervinh0000** [mozilla-mobile/fenix#13393] opened 2020-08-07 14:04 UTC
## Steps to reproduce
- Set toolbar position to "top"
- Go to random page
- When toolbar is visible, do a small, quick "Swipe up"

### Expected behavior
Page scolling and toolbar hiding should happen in the same time, not one first and then the other

### Actual behavior
Page only go up a little (sometime unstable and shot to the top or bottom of the page), because it only start scolling after the toolbar is fully hidden

### Device information
Redmi note 8 - Android 10 - Lastest stable Firefox 79.0.2

**Comment by jakefleming156** [comment] 2020-08-07 19:43
Looks like a dupe of #13340. Follow along in that bug.

**Closed by jakefleming156** 2020-08-07 19:43 UTC
Labels: needs:gv, 🐞 bug
