### ISSUE TITLE
[Bug] there are 2 different open private browsing widgets/shortcuts

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#11806] opened 2020-06-22 10:25 UTC
## Steps to reproduce
1. Use the add private browsing shortcut from settings
1. Long click on the fenix icon in launcher and long press on the tab option to get another shortcut
    1. Expected behavior
The two shortcuts should look the same since they have the same function
    1. Actual behavior
One is blue coloured and the other is white
    1. Device information
![Screenshot](https://user-images.githubusercontent.com/33252312/85277177-7e82e380-b472-11ea-8c8d-8159b293044e.png)UNITO-UNDERSCORE!20200622-155237!UNITO-UNDERSCORE!Trebuchet!

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by LaurentiuApahideanSV** [comment] 2020-06-24 09:53
I can confirm that the issue is reproducible on the latest Firefox Preview Nightly 200624 (Build #21760611). However according to https://github.com/mozilla-mobile/fenix/issues/7033 I don't think this can be fixed.

**Comment by kbrosnan** [comment] 2020-08-28 20:15
Closing as a dupe of #7033

**Closed by kbrosnan** 2020-08-28 20:15 UTC
Labels: Feature:HomeScreen, Feature:PrivateBrowsing, 🐞 bug
