### ISSUE TITLE
[Bug] Awesome bar(Scan and Shortcuts) disappear when keyboard is minimized

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#3557] opened 2019-06-19 14:48 UTC
## Steps to reproduce
Tap the search bar
Minimize the keyboard using the "v" button
Tap again the search bar

### Expected behavior
The awesome bar(scan and shortcuts) shouldn't disappear when the keyboard is minimized

### Actual behavior
The awesome bar(scan and shortcuts) disappears when the keyboard is minimized

### Device information
* Android device: **Google Pixel 3XL (Android 9)**
* Fenix version: **1.0.0-rc.2**(*19.06*)

### Notes: 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/51314259/59775763-5f2f0480-92ba-11e9-95c9-b8f614b42d2f.gif)

**Comment by WhoIsAndi** [comment] 2019-06-19 14:51
This dupe of #3555

**Closed** 2020-08-27 00:21 UTC
Labels: 🐞 bug
