### ISSUE TITLE
[Bug] tab closed notification not disappearing

### ISSUE THREAD

**Issue by daveybops** [mozilla-mobile/fenix#8472] opened 2020-02-18 00:27 UTC
## Steps to reproduce
Start by having more than one tab open. List tabs. Close a tab and select another tab to view but do so before the closed tab notice disappears.
### Expected behavior
Closed tab notice should disappear.
### Actual behavior
Closed tab notice does not disappear. Workaround, go to tab list view, close another tab, wait for notice to disappear veggie selecting another tab to view.
### Device information

* Android device: LG H-870 v1.0 software V30b EU-XX
* Fenix version: 3.2.0 (Build #20250236)
28.0.2, 1deaef19a
GV: 73.0-20200123180644

**Comment by LittleAngelwings** [comment] 2020-02-18 05:01
duplicate of this: https://github.com/mozilla-mobile/fenix/issues/7799

Issue already fixed in nightly since two weeks.

**Comment by ekager** [comment] 2020-02-18 05:59
This will be fixed when we next release. Closing

**Closed by ekager** 2020-02-18 05:59 UTC
Labels: needs:triage, 🐞 bug
