### ISSUE TITLE
FNX-11981 ⁃ [Bug] Remove scroll to tab logic

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#11113] opened 2020-06-01 16:30 UTC
## Steps to reproduce
1. Open a tab 
1. Switch to private mode from tab switcher

### Expected behavior
1. Private tab is scrolled down a bit, hiding the branding and the private browsing button

### Actual behavior
1. Should stay scrolled to the top

**Comment by darkwing** [comment] 2020-06-01 17:45
Closing as dupe of https://github.com/mozilla-mobile/fenix/issues/10997

**Closed** 2020-08-11 02:56 UTC
Labels: Feature:HomeScreen, Skittle, 🐞 bug
