### ISSUE TITLE
[Bug] java.lang.IllegalStateException: Display already acquired

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#6812] opened 2019-11-26 15:45 UTC
Updated link, this is still happening constantly: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6545777/

Socorro [link](https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.IllegalStateException%3A%20at%20mozilla.components.browser.engine.gecko.GeckoEngineView%24currentGeckoView%241.onAttachedToWindow%28GeckoEngineView.kt%3A5%29&date=%3E%3D2019-07-21T07%3A02%3A00.000Z&date=%3C2020-01-21T07%3A02%3A00.000Z#graphs) with hundreds of crashes a day.

Overview is, if a user types to search for a tab that is already open and clicks on the suggestions, the browser will crash.

## Steps to reproduce
1. Have a list of opened tabs, make one of them pretty unique (e.g. search for unique123)
2. Open a tab from the list (not unique123)
3. Click on the url and type in one of the open tabs (unique123) and select link from suggestions
4. After the page is loaded click on opened tabs icon to navigate home

The app crashes.

`Caused by: java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity Other activity: HomeActivity`

Breadcrumbs: looks like browserFragment is opening twice, this is 100% reproducible.

Note: There was no custom tab session or private session. Also rebooted phone before testing to make sure there was no old session force killed.

Fenix version: Current master branch @ commit 5a429b9

**Comment by vesta0** [comment] 2020-01-06 21:07
I can't reproduce this. @mcarare do you know if this is still an issue?

**Comment by mcarare** [comment] 2020-01-07 09:40
The bug is not reproducible for me either, and it was 100% reproducible before. I'm going to close this.

**Comment by liuche** [comment] 2020-01-21 07:04
Reopening and updating with some links, this has hundreds of crashes a day.

**Comment by sv-ohorvath** [comment] 2020-01-27 15:05
We've verified the Beta 3.2.0 build and couldn't reproduce the crash. I'll close this as fixed.

**Closed by sv-ohorvath** 2020-01-27 15:05 UTC
Labels: P2, S1, b:crash, eng:qa:needed, 🐞 bug
