### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by NerdHarder615** [mozilla-mobile/fenix#17584] opened 2021-01-22 16:40 UTC
I updated my Android Firefox Nightly to version 210121 18:20. After the update I noticed that sync hasn't been working correctly. I am not able to send tabs to connect devices. When I try that option I can send to other locally installed apps, but my list of connected devices is blank. I tried clearing all the data from the app and now I can't log back in to sync from Nightly on Android. Firefox stable is working fine on my phone, and I haven't had any issues with the Linux versions of stable or nightly.

* Android device: Pixel 2

I asked around on Reddit to see if anyone else was having this issue and there are others with the same issue:
https://www.reddit.com/r/firefox/comments/l2mm2c/firefox_nightly_android_sync_not_working/

**Comment by jonalmeida** [comment] 2021-01-22 19:35
Duplicate of https://github.com/mozilla-mobile/fenix/issues/17585

**Closed by jonalmeida** 2021-01-22 19:35 UTC
Labels: needs:triage, 🐞 bug
