### ISSUE TITLE
[Bug] *critical* getting borders on full screen videos A11

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#18593] opened 2021-03-23 06:08 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open any video in youtube and click full screen button
It shows borders both on top and bottom completely ruining the experience. Works fine in chromium browsers

### Expected behavior

Should not show any border
### Actual behavior
Showing white borders 
### Device information

* Device vendor / model and Android version: ? A11 rog3
* Firefox for Android version: ? (go to Settings -> About Firefox) latest nightly
![Screenshot_20210323-113433630](https://user-images.githubusercontent.com/58127841/112101136-2c6f1a00-8bcc-11eb-8d7f-adf46c1b30e6.jpg)

**Comment by sflorean** [comment] 2021-03-23 06:13
@sheikh-azharuddin thanks for the report! #18546 is already filed for you issue, and this scenario will be tested when the issue is fixed. Closing as duplicate.

**Closed by sflorean** 2021-03-23 06:13 UTC
Labels: needs:triage, 🐞 bug

**Comment by sheikh-azharuddin** [comment] 2021-03-23 06:37
Thanks ..just now downloaded new build and it seems issue is fixed...

Thanks again😃
