### ISSUE TITLE
[Bug] Padding in some checkboxes is improper in settings

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#7928] opened 2020-01-25 08:07 UTC
## Steps to reproduce
Open settings
Go to set as default browser
tap/ hold the open links in .. checkbox

### Expected behavior
The padding is proper like this option:
![Screenshot_20200125-133820](https://user-images.githubusercontent.com/33252312/73118283-e5df4a80-3f49-11ea-8787-ec1af756f12d.png)

### Actual behavior
Very low padding
![Screenshot_20200125-133449](https://user-images.githubusercontent.com/33252312/73118268-c1836e00-3f49-11ea-83f2-3c52880125d5.png)

### Device information

* Android device: Asus zenfone m1
* Fenix version: Nightly 200124 06:01 (Build #20240607)
29.0.0, ae1ba0f02
GV: 74.0a1-20200122094859

**Comment by s-ankur** [comment] 2020-01-25 08:11
Similar problem in clear browsing data option
![Screenshot_20200125-134015](https://user-images.githubusercontent.com/33252312/73118297-3060c700-3f4a-11ea-9580-86976363f237.png)

**Comment by s-ankur** [comment] 2020-01-25 08:22
And here:
![Screenshot_20200125-135109](https://user-images.githubusercontent.com/33252312/73118420-cc3f0280-3f4b-11ea-9fcd-e360d0b33bcd.png)

**Comment by kbrosnan** [comment] 2020-02-15 19:22
This is still an issue after the Settings re-org #8240

**Comment by miDeb** [comment] 2020-03-06 11:05
I could only reproduce the last one (Show in private sessions).

**Comment by mcarare** [comment] 2020-03-27 23:55
For QA: This seems to be fixed. 
Note for https://github.com/mozilla-mobile/fenix/issues/7928#issuecomment-578387538: this was fixed and checked in https://github.com/mozilla-mobile/fenix/issues/8600.

**Comment by sv-sdeiac** [comment] 2020-03-30 13:38
Hi, I can confirm that the issue is fixed using the latest version of Firefox Preview Nightly 3/29 #20891805.

Devices: 
- Google Pixel (Android 10);
- LG g7 fit (Android 8.1).

**Closed by sv-sdeiac** 2020-03-30 13:38 UTC
Labels: Feature:Settings, eng:qa:needed, help wanted, needs:triage, 🐞 bug

**Comment by s-ankur** [comment] 2020-04-16 11:19
Hi, I can still see this issue in latest nightly
![Screenshot_20200416-163928_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/79450193-1f1cd900-7fd4-11ea-8fff-1274adf4252c.png)

**Comment by s-ankur** [comment] 2020-04-18 07:40
@sv-sdeiac I think this needs to be reopened

**Comment by miDeb** [comment] 2020-04-18 08:16
This is intentional: https://github.com/mozilla-mobile/fenix/issues/8600#issuecomment-597588790.
