### ISSUE TITLE
FNX-11891 ⁃ [Bug] Getting notifications from Twitter despite not giving permissions

### ISSUE THREAD

**Issue by djc** [mozilla-mobile/fenix#11033] opened 2020-05-29 12:58 UTC
## Steps to reproduce
If I have a Twitter tab open, I now sometimes get notifications from it (a la, "211 interactions with your tweet", or "DM from so-and-so"). This started happening somewhere in the past 2-3 days.

### Expected behavior
Since I'm pretty sure not having given any permission to Fenix to push notifications on behalf of any websites, I was surprised that I'm getting notifications. I checked the Settings > Site permissions > Exceptions list and Twitter is not in there.

### Actual behavior
Get unwanted Twitter notifications.

### Device information
* Android device: Pixel 2
* Fenix version: Nightly from the Play Store

**Comment by cadeyrn** [comment] 2020-05-29 12:59
Duplicate of #11012.

**Comment by djc** [comment] 2020-05-29 13:02
@cadeyrn thanks!

**Closed** 2020-08-11 02:42 UTC
Labels: needs:triage, 🐞 bug
