### ISSUE TITLE
[feature request] Loading/progress bar to be always visible

### ISSUE THREAD

**Issue by aha999** [mozilla-mobile/fenix#9141] opened 2020-03-13 10:55 UTC
When i click a link, it would be really nice if the progress loading bar was always shown. Currently it is hidden if the search bar is hidden, it's only visible as a part of search bar / toolbar, but not if the toolbar is minimized/hidden...

The problem i have with this is, when i tap a link and it starts loading a website, i'm not sure it started loading because content starts to open depending on a internet connectivity, and i don't know if i pressed a button if it didn't start opening/loading already, so i have to swipe up to check if a progress bar is visible/loading.

Please make the progress bar/loading bar/indication always visible. And it takes very little space, which informs us if the website is loading, without having to swipe to see if it's doing anything.

**Comment by cadeyrn** [comment] 2020-03-13 11:08
Duplicate of #9031.

**Closed** 2020-03-13 11:35 UTC
Labels: needs:triage
