### ISSUE TITLE
[Bug] Youtube fullscreen Video cut in the bottom

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#13335] opened 2020-08-06 06:31 UTC
Not happening on all devices.

## Steps to reproduce
1. Go to https://m.youtube.com/watch?v=4MnGAw-LU9Q
2. Play and full screen

### Expected behavior
Video is full screen and we can see the total video

### Actual behavior
It seems that only on **some devices**, the video is cut at the bottom. Visible around ~3min.
I can't reproduce myself on a pixel 2.

### Device information

* Android device:  Nokia 6.2 with a 1080 x 2340 screen
* Fenix version: 81

See https://github.com/webcompat/web-bugs/issues/56260

**Comment by LaurentiuApahideanSV** [comment] 2020-08-20 16:10
I can confirm that the issue is reproducible on the latest Firefox Preview Nightly 200820 (Build #2015759027).

### Devices used:
- OnePlus 6T (Android 9)

**Comment by kbrosnan** [comment] 2020-08-28 23:26
Closing as a duplicate of  #8252

**Closed by kbrosnan** 2020-08-28 23:26 UTC
Labels: 🐞 bug
