### ISSUE TITLE
Invisible text on last viewed pages list in dark theme. [Bug]

### ISSUE THREAD

**Issue by michal1315** [mozilla-mobile/fenix#17001] opened 2020-12-12 18:54 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Firefox 84.1.0 with theme set to dark. 
Open few pages in single tab, long press back button to open list of recent viewed pages.
### Expected behavior
Text of site title is visible like in light theme.
### Actual behavior
![Screenshot_2020-12-12-19-37-40-336_org mozilla firefox](https://user-images.githubusercontent.com/35575000/101992339-c3196a00-3cb2-11eb-83c7-46af75672fd9.jpg)

### Device information

* Android device: Xiaomi Mi6 MIUI 11.0.6
* Android version: 9
* Fenix version: Firefox 84.1.0

**Comment by LittleAngelwings** [comment] 2020-12-12 21:30
duplicate of this https://github.com/mozilla-mobile/fenix/issues/16422?

**Comment by michal1315** [comment] 2020-12-12 22:02
Yaa, its looks same. 
  Dnia 12 grudnia 2020 22:30 LittleAngelwings   napisał(a):  
 duplicate of this  github.com #16422 ?

**Comment by mcarare** [comment] 2020-12-14 11:51
@michal1315 Thank you for your report!
Closing this as a duplicate of https://github.com/mozilla-mobile/fenix/issues/16422.

**Closed by mcarare** 2020-12-14 11:51 UTC
Labels: needs:triage, 🐞 bug
