### ISSUE TITLE
Wrong URL (404 error) should not be proposed in search

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6681] opened 2019-11-18 22:51 UTC
## Steps to reproduce

1. try to open wrong url - for example www.dobreprogramya.pl
2. try to open good URL - for example www.dobreprogramy.pl
3. open other page and try to typing www.dobre in URL bar

### Expected behavior

Browser is not remembering wrong URLs and doesn't propose them

OR

browser has got ability of removing URL suggestions

### Actual behavior

Browser is proposing dobreprogramya.pl

### Device information

* Android device: S7 / Android 8
* Fenix version: hightly 191118

**Comment by NotWoods** [comment] 2019-11-19 16:45
We already have an issue for removing history suggestions from the search bar here: #6358.

I'll update this issue to focus on the other option, not suggesting a URL if it doesn't load.

**Comment by NotWoods** [comment] 2019-11-22 07:05
Turns out we have an issue for the other option too!
Duplicate of #2064.

**Closed by NotWoods** 2019-11-22 07:05 UTC
Labels: Feature:Search, 🌟 feature request
