### ISSUE TITLE
Unable to add new search engine or edit existing ones

### ISSUE THREAD

**Issue by pampasdev** [mozilla-mobile/fenix#4357] opened 2019-07-29 18:28 UTC
### Why/User Benefit/User Problem
Currently we cannot add new search engine nor can we edit the existing ones.
### What/Requirements

- User should be able to add new search engines when he clicks on the search box or any text box which supports get request

- User should be able to edit the existing search engines this is useful in case the default search engine is not configured for regional site of search engine.

**Comment by cadeyrn** [comment] 2019-07-29 18:53
Duplicate of #1437.

**Comment by kbrosnan** [comment] 2019-08-13 20:58
closing as dupe

**Closed by kbrosnan** 2019-08-13 20:58 UTC
Labels: 🌟 feature request
