### ISSUE TITLE
[Bug] Tab icon shows wrong number of tabs while swiping tabs

### ISSUE THREAD

**Issue by OlliKn** [mozilla-mobile/fenix#15229] opened 2020-09-20 06:19 UTC
## Steps to reproduce
Open four tabs. Swipe around these tabs. Open a new tab. Swipe around again. Close one tab. 

### Expected behavior
The tab icon shows always the number 4.

### Actual behavior
While swiping it shows 5. After completing swipe it shows 4 again. 

### Device information
Honor 6x, lineageos 15

* Android device: ?
* Fenix version:  81.1.1 (Build #2015764547)

**Comment by s-ankur** [comment] 2020-09-20 06:38
Duplicate of https://github.com/mozilla-mobile/fenix/issues/12859. It's not just the tab counter, the whole UI is outdated

**Comment by OlliKn** [comment] 2020-09-20 06:50
Okay. So I will close it 😉

**Closed** 2020-09-20 06:51 UTC
Labels: needs:triage, 🐞 bug
