### ISSUE TITLE
FNX-3305 ⁃ [Bug] NFC Yubikey support

### ISSUE THREAD

**Issue by kmazurek244** [mozilla-mobile/fenix#10133] opened 2020-04-23 07:13 UTC
## Steps to reproduce
Login to Google account with hardware key NFC Yubikey with 2FA.

### Expected behavior
Browser waits for hardware nfc interaction and reads output from nfc. 

### Actual behavior
Goes to hw interaction and then immediately to error page. 

### Device information
Samsung S10+ with latest firmware (G975FXXU4CTC9). 

* Android device: yes
* Fenix version: 75.0.0-beta.6

**Comment by cadeyrn** [comment] 2020-04-23 07:16
same as #10135.

**Comment by mcarare** [comment] 2020-04-23 09:20
Duplicate of #10135.

**Closed** 2020-08-10 19:03 UTC
Labels: needs:triage, 🐞 bug
