### ISSUE TITLE
Toolbar position setting 'top' doesn't affect toolbar on home page

### ISSUE THREAD

**Issue by DavidBE-UK** [mozilla-mobile/fenix#7186] opened 2019-12-16 01:02 UTC
As I hate bottom controls on Android (and won't use apps that have them), I'm very pleased to see the new setting option to move the toolbar to the top, However, the one page it doesn't affect is the home page, where the toolbar (search/address entry, new tab control, three dot menu) remain at the bottom. Please have thsi follow the toolbar top/bottom setting too. Then I'll be able to actually use the app.

**Comment by cadeyrn** [comment] 2019-12-16 07:45
Duplicate of #6820.

**Closed** 2019-12-19 00:18 UTC
