### ISSUE TITLE
FNX3-16927 ⁃ [Bug] History gets stored in private browsing.

### ISSUE THREAD

**Issue by pb-10** [mozilla-mobile/fenix#3301] opened 2019-06-09 12:21 UTC
### Device information
* Android device: Mi A1, Android Version 9
* Fenix version: 1.0.1923

**Comment by cadeyrn** [comment] 2019-06-09 14:34
Please provice exact steps to reproduce because I can't reproduce the issue.

**Comment by pb-10** [comment] 2019-06-09 14:53
Hey there,
I’ve edited the “steps to reproduce” for this bug. Please check it out. And if you have any further issues then you can contact me anytime. Love contributing to Mozilla and Open Source✌🏻

**Comment by otede** [comment] 2019-06-10 18:35
Just checked it out today on my install. It doesn't occur on my system. Steps:
1. Switched to private mode
2. Looked up in duckduckgo.com for ifttt and visited ifttt.com.
3. Switched back to normal mode without closing anything.
Result:
Not a trace of ifttt.

**Comment by vesta0** [comment] 2019-06-11 04:05
Hi @pb-10 thank you for raising this issue. If this is still happening on your device, would you be able to provide a screen demo or an example of a site browsed in PB that keeps showing up in history?

**Comment by softvision-miralobontiu** [comment] 2019-06-13 09:43
I was not able to reproduce this issue on the latest build 1.0.1924 (#11640609), with Huawei P9 Lite (Android 6), and Samsung Galaxy Tab S3 (Android 8).

**Closed** 2020-08-12 17:39 UTC
Labels: eng:qa:verified, 🐞 bug
