### ISSUE TITLE
[Bug] Downloading from Firefox Send or any service with similar tecnologies does not work

### ISSUE THREAD

**Issue by SSUPII** [mozilla-mobile/fenix#6144] opened 2019-10-20 20:07 UTC
## Steps to reproduce

- Upload from any device any file to Firefox Send
- Open the download link on the mobile device
- Download the file

### Expected behavior

- The download of the file should start

### Actual behavior

- "Firefox Preview can't download this file type" is printed as a toast message
- Download does not start

### Device information

* Android device: ASUS ZenFone 3 Laser (TIM) on Android 7.1.1
* Fenix version: 
2.1.0 Build 12821601
Package: 14.0.1 81385d712
Gecko: 70.0-20190923100040

**Comment by cadeyrn** [comment] 2019-10-20 20:21
Duplicate of #3336.

**Comment by NotWoods** [comment] 2019-10-20 20:21
Duplicate of mozilla-mobile/android-components#1159 and #3336

**Comment by NotWoods** [comment] 2019-10-20 20:21
Whoops, @cadeyrn beat me to it!

**Closed by NotWoods** 2019-10-20 20:21 UTC
Labels: 🐞 bug

**Comment by cadeyrn** [comment] 2019-10-20 20:30
> Whoops, @cadeyrn beat me to it!

Sometimes I am _too_ fast. I deleted my comment after I saw your comment but before you wrote this comment. 😅
