### ISSUE TITLE
[Bug]Three dot menu doesn't animate

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#5418] opened 2019-09-19 06:02 UTC
## Steps to reproduce
1.open a webpage.
2.click on the menu button.
### Expected behavior
The menu animates from bottom to top.
### Actual behavior
It don't animates at all.
### Device information

* Android device: 8.0.0
* Fenix version:Nightly 190918 18:01 (Build #12611806)
📦: 13.0.0, 3cb2ac19c
🦎: 71.0a1-20190916093313

**Comment by hakkikaancaliskan** [comment] 2019-09-19 07:54
Delete and quit button brokes it. 
You can disable it for now.

**Comment by Scripterr** [comment] 2019-09-19 08:08
This doesn't have anything to do with delete or quit button because I'm not using quit feature.

**Comment by hakkikaancaliskan** [comment] 2019-09-19 08:15
Then... Not producible for me.
Android 9, XZ1
Nightly 190918 18:01 (Build #12611806)
📦: 13.0.0, 3cb2ac19c
🦎: 71.0a1-20190916093313

**Comment by NotWoods** [comment] 2019-09-30 03:28
Duplicate of mozilla-mobile/android-components#3032. This code lives in our Android Components repository so we'll close the issue here.

**Closed by NotWoods** 2019-09-30 03:28 UTC
Labels: 🐞 bug
