### ISSUE TITLE
[Bug] Download digital certificate pdf COVID19

### ISSUE THREAD

**Issue by xpwd-lab** [mozilla-mobile/fenix#9735] opened 2020-04-06 09:35 UTC
Hello

![Screenshot_20200406-112833_Firefox Preview](https://user-images.githubusercontent.com/63072894/78544436-6f3cb400-77fa-11ea-9e0d-b32e258a7b52.jpg)

I can't download the pdf of the digital certificate COVID19 on Firefox Preview. It works on Firefox Windows.

URL : https://media.interieur.gouv.fr/deplacement-covid-19/

**Comment by sunazerty** [comment] 2020-04-06 10:06
The PDF is generated on the fly. I think that GeckoView can't handle that properly right now, whereas Gecko can.

**Comment by kbrosnan** [comment] 2020-04-06 15:44
Does not seem to be the blob: issue. Attached are the headers that desktop sees.

![Screenshot_2020-04-06-issue-9735](https://user-images.githubusercontent.com/250273/78577173-8e2f4c00-77e2-11ea-9a26-a7ea048539ad.png)

**Comment by sunazerty** [comment] 2020-04-06 17:22
On the contrary, I think it is the blob issue:
![image](https://user-images.githubusercontent.com/16479754/78586479-cb73f800-783b-11ea-92bd-ab6da30c63c4.png)

**Comment by miketaylr** [comment] 2020-04-06 18:33
https://github.com/webcompat/web-bugs/issues/51214#issuecomment-609957604

From https://media.interieur.gouv.fr/certificate.js

```js
$('#form-profile').addEventListener('submit', async event => {
  event.preventDefault()

  saveProfile()
  const reasons = getAndSaveReasons()
  const pdfBlob = await generatePdf(getProfile(), reasons)
  downloadBlob(pdfBlob, 'attestation.pdf')

  snackbar.classList.remove('d-none')
  setTimeout(() => snackbar.classList.add('show'), 100)

  setTimeout(function () {
    snackbar.classList.remove('show')
    setTimeout(() => snackbar.classList.add('d-none'), 500)
  }, 6000)
})
```

**Comment by kbrosnan** [comment] 2020-04-06 18:47
Closing as a dupe of mozilla-mobile/android-components/issues/1159

**Comment by Amejia481** [comment] 2020-05-15 15:26
Now we have support for blob URLs. QA please help us to verify if this website is working as expected.

**Comment by madb1lly** [comment] 2020-05-16 22:55
Hi all, 
I tested today and confirm it works now 😃

**Comment by AndiAJ** [comment] 2020-05-18 07:02
Hi, **verified as fixed** on the latest **`Nightly Build #200518 from 5/18`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200518-093609](https://user-images.githubusercontent.com/51314259/82183394-8e952980-98ee-11ea-8f12-bfc10ba6fd28.gif)

**Closed by AndiAJ** 2020-05-18 07:02 UTC
Labels: Feature:Download, eng:qa:needed, 🐞 bug

**Comment by jeromebrenier** [comment] 2020-06-05 23:25
It is correcty fixed in the nightly build, but generate a browser crash with the release version :

![crash_firefox_covid](https://user-images.githubusercontent.com/58886951/83929689-93822600-a794-11ea-8d34-aa52dd8db061.PNG)

**Comment by Amejia481** [comment] 2020-06-08 15:21
it will be fixed when the release build gets the new AC version.
