### ISSUE TITLE
FNX-11878 ⁃ long press delay

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11021] opened 2020-05-29 04:03 UTC
## Steps to reproduce
On long press on any textbox content or webpage content such as while editing in github it takes around 2-3 seconds for the menu(copy,paste,select all) to appear.

### Expected behavior
The menu should appear immediately within a second like other browser such as chrome

### Actual behavior
Menu appears in 2-3 seconds . Too much delay

### Device information
* Android device: ? Yes. A10
* Fenix version: ? 21490607. Latest version

![Screenshot](https://user-images.githubusercontent.com/58127841/83219943-33bac800-a161-11ea-845e-6b1c5db69f8f.jpg)UNITO-UNDERSCORE!20200529-093144!

**Comment by SS1113** [comment] 2020-05-29 04:41
duplicate of #10618.

**Comment by mcarare** [comment] 2020-05-29 06:01
Closing as duplicate of #10618.

**Closed** 2020-08-11 02:39 UTC
Labels: needs:triage, 🐞 bug
