### ISSUE TITLE
[Bug] After opening a custom tab in normal browser and going home every resume launches to browser

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla-mobile/fenix#3829] opened 2019-07-01 19:56 UTC
### Prerequisites:
- The Fenix browser is set as default browser on Android device.
- App is closed with no tabs in memory. 

## Steps to reproduce:
1. Open a link from a 3rd party app (Gmail).
2. After the page is loaded, tap the "Tabs" button.
3. Swipe or close the tab with the opened page.
4. While the "Undo" purple bar is displayed at bottom, tap the device back button.
5. Observe the browser behavior a few seconds.
6. Open the menu and try open one of the options.
7. Tap the device back button and observe again the browser behavior.

### Expected behavior:
- Step 5: The page is reloaded, it can be normally used and the "Tabs" button shows 1 tab opened.
- Step 7:  You are returned to the previously loaded page. 

### Actual behavior:
- Step 5: The page is reloaded, works for 1 second before it freezes and the "Tabs" button changes from 1 tab to 0 tabs opened.
- Step 7: You are returned to a blank white page.

### Notes:
- If "Find in page", "Share" or "Report site issue" options are chosen when executing steps 1 to 6, nothing happens in this state.  

### Device information
Android 7.0

* Android device: Samsung Galaxy S6
* Fenix version: v1.0.0 (Build #11721515 68.0-20190611143747)

**Comment by AndiAJ** [comment] 2019-07-04 13:05
Hi the issue is still replicating on the latest Fenix Build #11850611 from 4/7 using the following devices:

• Google Pixel 3XL (Android 9)
• Samsung Galaxy S8+ (Android 8)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

<details>
    <summary>Extra details and video</summary>

At **step 6**  I've selected;
• Share
• Find in Page
• Desktop site
• Settings

As for **step 7**,I've tapped the tabs counter, hit the back button and resumed Fenix

► [Video Google Pixel 3XL](https://drive.google.com/file/d/1WxFf_kxumjQzpQQel-KxIk8OqkaYfAok/view?usp=sharing)

</details>

**Comment by ekager** [comment] 2019-07-17 17:34
Could we retest this? Or get new STR? I can't reproduce with the initial STR any longer on master

**Comment by AndiAJ** [comment] 2019-07-18 09:18
Hi, it seems that the problem in the [above mentioned STR](https://github.com/mozilla-mobile/fenix/issues/3829#issue-462884486) isn't there anymore on the latest **Nightly Build #11990109 from 18/7** tested on the following devices:
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)  

**On the other hand I've bumped into a new issue.**

## Alternative STR
1. Open a link from a 3rd party app (Gmail).
2. After the page is loaded, tap the "Tabs" button.
3. Swipe or close the tab with the opened page.
4. While the "Undo" purple bar is displayed at bottom, tap the device back button.
5. Resume FP

### Expected behavior 
After resuming FP, you should be redirected to the home screen.

### Actual behavior
After resuming FP, the tab used to perform the above mentioned actions (Close + Undo + Device back button) is automatically opened.


The actual state in which FP is after taping the device back button, namely, the home screen being displayed, can be seen in the Android Application Manager Tray as per the attached video.

► Video from Huawei Mate 20 Lite
![20190718_115000](https://user-images.githubusercontent.com/51314259/61445374-f1780600-a955-11e9-800a-5d00f7d38733.gif)

**Comment by ekager** [comment] 2019-07-18 20:13
Thanks for the new STR! I am able to reproduce this behavior without the tab deletion/undo.

STR:
1. Open Fenix from custom tab
2. Press tabs to go back to home
3. Press back button
4. Resume Fenix

It looks like `IntentReceiverActivity` is getting the resumed call and `OPEN_TO_BROWSER` is still true.

@pocmo I think this may be related to your changes in #4028. Do you have any ideas of why this would be happening?

**Comment by pocmo** [comment] 2019-07-23 11:46
Mh, my assumption is that after the activity was destroyed and when clicking on the app in the "recent apps" screen then the original intent that launched this activity is re-delivered.

We had a similar issue in Focus where this could re-open a URL that was already closed. In Focus we look at `FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY` and in this case do not process the intent:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/session/IntentProcessor.kt#L32-L37

I can try to figure out today if this is causing this here too.

**Comment by ekager** [comment] 2019-07-30 22:29
Thank you @pocmo for the history I think I got the fix working :)

**Comment by softvision-miralobontiu** [comment] 2019-08-05 12:31
Verified as fixed on a locally build from 8/5 master with LG G7 Fit (Android 8), and Sony Xperia Z5 Premium (Android 7.1.1).

**Closed by softvision-miralobontiu** 2019-08-05 12:31 UTC
Labels: S2, eng:qa:needed, 🐞 bug
