### ISSUE TITLE
[Bug] Video conference: wrong camera is used

### ISSUE THREAD

**Issue by muessjoeh** [mozilla-mobile/fenix#14729] opened 2020-09-04 14:10 UTC
## Steps to reproduce

When I start a video conference with Red Medical, the browser asks whether it is allowed to use "the camera" (there are two of them, front and back). When I allow it, it uses the back camera. It is impossible to make a video conference with the back camera! 

### Expected behavior

It should ask whether to use the front or back camera. 

### Actual behavior

It asks nothing and uses the wrong one. 

### Device information
Samsung Galaxy A6 + running Android 10. Firefox 79.0.5

**Comment by hwinnemoe** [comment] 2020-09-04 14:12
Duplicate of #10748

**Closed** 2020-09-11 19:50 UTC
Labels: needs:triage, 🐞 bug
