### ISSUE TITLE
[Bug] Swipe to switch tabs animation jumps

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#13127] opened 2020-07-30 13:50 UTC
Edit: I believe this is caused by #12909, not by scrolling before swiping between tabs

## Steps to reproduce
open 2 tabs 
swipe left and right to switch tabs
![ScreenRecord-2020-07-30-16-44-14_1](https://user-images.githubusercontent.com/922368/88930885-c58ba200-d284-11ea-9168-f1914a6a7126.gif)

### Expected behavior
not do any flicker
### Actual behavior
has a short flicker
### Device information

* Android device: oneplus 5t
* Fenix version: nightly

**Comment by DaFlowah** [comment] 2020-07-30 15:35
Not a big deal, but yes, I have the same.
OnePlus 5 on stock ROM (OxygenOS 9.0.10 based on Android 9) + Magisk.
Firefox Nightly 200730.

**Comment by person808** [comment] 2020-07-30 17:55
Hold on I think this was a recent regression, unrelated to the scrolling

**Comment by andreicristianpetcu** [comment] 2020-07-30 19:15
It was a regression. It worked fine in the first swipe implementation.

**Comment by DaFlowah** [comment] 2020-08-01 10:56
Seems to be fixed in the latest Nightly: 200801

**Comment by andreicristianpetcu** [comment] 2020-08-01 11:18
ohhh.... you want QA to verify it. reopening.

It works fine for me.

**Comment by sv-ohorvath** [comment] 2020-08-04 10:21
Verified as fixed on Nightly 8/4 on two devices: Pixel 4 (Android 10), Htc Desire 820 (Android 6.0.1).

**Closed by sv-ohorvath** 2020-08-04 10:21 UTC
Labels: Feature:Gesture, eng:qa:needed, sourpatch, 🐞 bug
