### ISSUE TITLE
[Bug] "No bookmarks here" flashes on screen before I see the contents of a bookmarks folder

### ISSUE THREAD

**Issue by ckarlof** [mozilla-mobile/fenix#4040] opened 2019-07-12 22:16 UTC
## Steps to reproduce
Sign into Sync and have a Desktop Bookmarks folder.
Navigate into the Desktop Bookmark folders.

### Expected behavior
I see smooth transitions between each navigation.

### Actual behavior
The screen flashes "No bookmarks here" before showing the contents of the folder.

### Device information
* Android device: Pixel 3
* Fenix version: Nightly #11931815

I don't know if it's related, but sometimes when I start Fenix and navigate to my Bookmarks in the Library, it shows "No Bookmarks Here", which eventually resolves itself and shows me my Bookmarks. I tried to debug with Lina over adb and couldn't find anything fishy in the logs.

**Comment by ekager** [comment] 2019-07-13 06:09
This is because we are initializing these components with empty lists because we need to load history and bookmarks async and then update the lists/views. We should definitely look at this when refactoring our components.

**Comment by boek** [comment] 2019-08-01 04:20
@ekager Did you mean to reference this ticket with that commit?

**Comment by ekager** [comment] 2019-08-01 04:23
I think that will resolve this issue? @ckarlof could you let us know if this is better in tomorrow's build? :)

**Comment by boek** [comment] 2019-08-01 04:23
I'm a dummy! @ekager is right!

**Comment by abodea** [comment] 2019-08-01 09:30
Verified as fixed in **`1.2.0-rc.1 (Build #12130445)📦: 6.0.2🦎: 69.0-20190729080047`** using **`Google Pixel 3a XL(Android 9) and Samsung Galaxy Tab A(Android 9).`**

Please note that after a successfully login and sync, when entering the bookmarks folder everything is displayed correctly.(But sometimes after login and accessing very fast the bookmarks folders ~2-4 seconds the No Bookmarks here is displayed, but I believe that is intended as the sync wasn't really made at that short time.
@boek @ekager if you can please confirm that this is the intended behavior when accessing the bookmarks folder very fast after a login.

**Closed by abodea** 2019-08-01 09:30 UTC
Labels: Feature:Bookmarks, Feature:Library, P3, eng:qa:needed, 🐞 bug

**Comment by ckarlof** [comment] 2019-08-02 00:35
I can also verify the problem as fixed on my phone. Thanks @ekager! I think @abodea has a good point about perhaps filing a separate issue around providing better feedback during the initial sync. It would be nice to let users know we're still populating their bookmarks.
