### ISSUE TITLE
Firfox crash 

### ISSUE THREAD

**Issue by AhmedHamdyHosny** [mozilla-mobile/fenix#27533] opened 2022-10-24 21:56 UTC
17641d17-970b-4dd0-b415-a27bda8b1bf5
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{cf9cdd4 u0 org.mozilla.firefox/org.mozilla.fenix.media.MediaSessionService}
----
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{cf9cdd4 u0 org.mozilla.firefox/org.mozilla.fenix.media.MediaSessionService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2389)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8393)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21864)

**Comment by jonalmeida** [comment] 2022-10-25 04:35
Duplicate of https://github.com/mozilla-mobile/fenix/issues/25608

**Closed by jonalmeida** 2022-10-25 04:35 UTC
Labels: needs:triage
