### ISSUE TITLE
[Bug] Fenix build downloads Miniconda3-4.5.11-Linux-x86_64.sh on every rebuild

### ISSUE THREAD

**Issue by theres-waldo** [mozilla-mobile/fenix#8039] opened 2020-02-02 16:33 UTC
## Steps to reproduce

1. Build Fenix with `./gradlew clean app:assembleGeckoNightlyDebug`.
2. Rebuild with the same command.

### Actual behavior

The build output shows:

```
> Task :app:Bootstrap_CONDA_'Miniconda3'
Downloading Miniconda3-4.5.11-Linux-x86_64.sh
```

on every incremental rebuild, and this step takes a while (~1 minute), adding significant latency to incremental rebuilds.

### Expected behavior

Only download it the first time, not for incremental rebuilds.

### Device information

* Android device: Moto G5
* Fenix version: recent master branch

**Comment by kbrosnan** [comment] 2020-02-02 21:15
Is there a reason you are building with `clean`? Does it download Miniconda if you omit `clean`?

**Comment by theres-waldo** [comment] 2020-02-02 21:28
> Is there a reason you are building with `clean`?

If I omit `clean`, Fenix startup-crashes with an error like:


> java.lang.RuntimeException: LOAD mozglue: ABI: unknown (0x0), armeabi-v7a: Data: /data/user/0/org.mozilla.fenix.debug, ax=false, ddx=false, -1x=false, -2x=false, nativeLib: /data/app/org.mozilla.fenix.debug-BA6hQD_3hkh1M-1BT31sOA==/lib/arm, dirx=true, libx=false


I should mention I'm building against a local GeckoView.

**Comment by mcomella** [comment] 2020-02-12 16:46
I also see this and I'm not building any dependencies locally. In the logs, I see:
```
> Task :app:Bootstrap_CONDA_'Miniconda3'
Downloading Miniconda3-4.5.11-MacOSX-x86_64.sh
Bootstraping to /Users/mcomella/.gradle/glean/bootstrap-4.5.11/Miniconda3
PREFIX=/Users/mcomella/.gradle/glean/bootstrap-4.5.11/Miniconda3
```

It seems this task may occur due to glean. @Dexterp37 is this expected behavior? I'm not sure it's a high priority but is this something your team can look into?

**Comment by Dexterp37** [comment] 2020-02-12 17:12
> 
> 
> I also see this and I'm not building any dependencies locally. In the logs, I see:
> 
> ```
> > Task :app:Bootstrap_CONDA_'Miniconda3'
> Downloading Miniconda3-4.5.11-MacOSX-x86_64.sh
> Bootstraping to /Users/mcomella/.gradle/glean/bootstrap-4.5.11/Miniconda3
> PREFIX=/Users/mcomella/.gradle/glean/bootstrap-4.5.11/Miniconda3
> ```
> 
> It seems this task may occur due to glean. @Dexterp37 is this expected behavior? I'm not sure it's a high priority but is this something your team can look into?

If you do a _clean_ build, it deletes any file you already downloaded, so this is probably the right behaviour. If you build without cleaning, it does an incremental build and re-uses the downloaded environment.

**Comment by mcomella** [comment] 2020-02-12 19:08
@Dexterp37 I disagree – I think dependencies should be cached locally: for example, we cache all of our gradle dependencies and only download them when they need to be updated. If we had to download all of our dependencies each time, it would take a very long time to build.

Furthermore, I would prefer our clean builds not to require on a valid network connection for a commit we've already built. For example, if you're working on the go without internet (e.g. an airplane) and perform a clean build, you might be completely blocked from continuing to work.

**Comment by Dexterp37** [comment] 2020-02-13 12:50
> 
> 
> @Dexterp37 I disagree – I think dependencies should be cached locally: for example, we cache all of our gradle dependencies and only download them when they need to be updated. If we had to download all of our dependencies each time, it would take a very long time to build.

Our dependencies are cached locally: but they get deleted when asking for a "clean" build. 

> Furthermore, I would prefer our clean builds not to require on a valid network connection for a commit we've already built. For example, if you're working on the go without internet (e.g. an airplane) and perform a clean build, you might be completely blocked from continuing to work.

Offline builds are probably also broken for other reasons as well, but it's good to track that too. 

I filed [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1615256) for tracking this on our side. Feel free to close this, since work should not happen in Fenix.

**Comment by mcomella** [comment] 2020-02-17 13:07
> I filed this bug for tracking this on our side. Feel free to close this, since work should not happen in Fenix.

@boek How does Fenix track issues intended to be worked on upstream like these? Do we keep this open or close it?

**Comment by mdboom** [comment] 2020-03-04 18:42
Fixed by https://github.com/mozilla/glean/pull/753

**Closed** 2020-03-05 14:50 UTC
Labels: needs:triage, 🐞 bug
