### ISSUE TITLE
[Bug]: Gap where URL would be when using site as an ”installed app”

### ISSUE THREAD

**Issue by synthead** [mozilla-mobile/fenix#26151] opened 2022-07-22 17:21 UTC
### Steps to reproduce

With Home Assistant, you can ”install” it like so:

![Screenshot_20220722-101640](https://user-images.githubusercontent.com/820984/180491181-8bad901e-b11b-4425-b446-45623f3630c7.jpg)

When viewing the ”app” that's installed, the URL bar that would normally be hidden has a visual gap:

![Screenshot_20220722-101420](https://user-images.githubusercontent.com/820984/180491320-f125207c-9564-4bf1-a710-08514d41ce64.jpg)

Steps to reproduce:

1. Have Home Assistant available (although other sites that can be ”installed” should do also work
2. View installed ”app”
3. Observe gap where the URL bar would be in Firefox that shouldn't be there in the ”app”

### Expected behaviour

No gap should be visible

### Actual behaviour

Gap is visible

### Device name

OnePlus 7t

### Android version

11

### Firefox release type

Firefox Nightly

### Firefox version

104.0a1 (Build #2015893515), ce92a0ab3+ AC: 104.0.20220721143105, be61b4862d GV: 104.0a1-20220721065915 AS: 93.6.0

### Device logs

No crash

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21096)

**Comment by LaurentiuApahideanSV** [comment] 2022-07-25 10:35
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/19972, I will close this issue as it will handled there.

**Closed by LaurentiuApahideanSV** 2022-07-25 10:35 UTC
Labels: 🐞 bug, needs:triage
