### ISSUE TITLE
Ability to rearrange tabs / reorder tabs / arrange tabs / order tabs, just like on old Firefox 68

### ISSUE THREAD

**Issue by MadridSpain** [mozilla-mobile/fenix#17114] opened 2020-12-18 10:09 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Before Fenix, on Firefox 68 and before, you could rearrange tabs to whatever order you wanted. This was a tremendously useful feature. By longpressing any of your tabs in Grid view, you could drag them into a different order (just like you can on desktop Firefox). But now, on all versions of Fenix, there is no way to rearrange the order of your tabs. They are set in a list in whatever order you opened them. Yes, you can choose to view them in list or grid view, but you **can't rearrange them**.

### How do you know that this problem exists today? Why is this important?

This is a **massive step backwards**. If you have 20 tabs open, you are forced to scroll through all of them in whatever order you opened them, without any possibility of reordering them. If you had several YouTube tabs open of videos you wanted to watch, you could arrange them all together. If you had several Twitter threads you opened throughout the day, you could rearrange all those tabs next to each other so that when you wanted, you could go through them without having to hunt them all down randomly. If you were filling out some important forms or doing some emails, you could place those tabs at the beginning of your tabs list, and then have your other tabs arranged to come after. etc. etc. etc.

### Who will benefit from it?

Everyone. The same people who benefited from this feature when it was available on Fennec for years will benefit from it here. The removal of it was one of the worst decisions Firefox made with Fenix. It's one of those things I don't understand why Firefox got rid of it. By removing it, you don't benefit any of the users who weren't using it. You only hurt the people who **were** using it. It takes away control from users and makes them no longer seek Firefox out. This feature is one of the things that would have separated it from browsers like Brave.

**Comment by cadeyrn** [comment] 2020-12-18 11:11
Duplicate of #16130 / #16408.

**Comment by koshkas1** [comment] 2020-12-18 15:13
Wow...just when I thought this issue couldn't get worse the new update rolled out and made it so. It used to be that new tabs were input above the old tabs, now they are opened at the bottom, whicheans you have to do a lot more scrolling to find them. Without the ability to change this and rearrange tabs this is frustrating.

**Comment by ekager** [comment] 2020-12-18 17:35
Closing as a dupe of the linked issues. Also see ascending/descending tabs feature request #16884 and #11376

**Closed by ekager** 2020-12-18 17:35 UTC
Labels: needs:triage

**Comment by waaronking** [comment] 2021-07-19 21:23
For anyone looking to upvote this feature request please see: https://github.com/mozilla-mobile/fenix/issues/16884 @koshkas1 @MadridSpain
