### ISSUE TITLE
Improve integration with Android Autofill Framework

### ISSUE THREAD

**Issue by grafail** [mozilla-mobile/fenix#19981] opened 2021-06-12 15:43 UTC
### What is the user problem or growth opportunity you want to see solved?
The [Android Autofill Framework](https://developer.android.com/guide/topics/text/autofill) is not currently supported by Firefox, which forces users of apps like LastPass which support the framework to need to switch apps and copy the required credentials.
There seems to be an old ticket about this as well (https://bugzilla.mozilla.org/show_bug.cgi?id=1352011).

### How do you know that this problem exists today? Why is this important?
Most other browsers (and apps) support this feature. I am currently using the nightly version and it is still not supported (an autofill option should appear in the context menu). This is really important, as not only it affects users while browsing on Firefox, but even when they are using apps that utilise the WebView API for authentication.

### Who will benefit from it?
Everyone using a third party password management service that supports the autofill framework.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11014)

**Comment by Udayanithig** [comment] 2021-06-13 02:59
Yes, autofill is broken on firefox (Android). It is not reliable and consistent. Developers need to work on it.

**Comment by agi** [comment] 2021-06-16 17:46
@grafail Hi there, AFAIK we already support the Android Autofill framework already in Firefox. Is there something not working on your end? could you give us steps to reproduce.

**Comment by grafail** [comment] 2021-06-16 18:37
1) Use Lastpass and turn Autofill with the Oreo Autofill API on

2) Browse to a page with a saved password

3) Autofill should appear in the context menu or a box should pop up under

This works on other browsers and inside apps (not in Webview using Firefox).

**Comment by allisonkarlitskaya** [comment] 2021-06-18 08:07
> @grafail Hi there, AFAIK we already support the Android Autofill framework in Firefox. Is there something not working on your end? could you give us steps to reproduce.

This has been pretty broken for a long time, in at least two ways:
 1. firefox doesn't trigger the password manager to offer autofill in any consistent way.  Sometimes you can force it if you click back and forth between the fields a lot or switch to the password manager app and back again to firefox, but it's completely inconsistent.  This part works 100% fine with Chrome, Firefox Klar, pretty much every other browser.  It also works with Firefox Nightly, which is interesting.  This is talked about since a long time here: https://github.com/mozilla-mobile/fenix/issues/14633 (in context of KeyPass, but applies to every password manager I've tested it with).
 1. if the autofill does get triggered and you open the password manager app (for example, in the case you need to unlock it) then when you select the password in question and are transferred back to Firefox, the form fields don't actually get filled.  I remember seeing some other bug about that at some point, but I can't seem to find it again.

It's definitely not the case that Firefox is working with Android's autofill framework in any reliable way.  This is broken since a long time for a lot of people, across many Firefox versions, password mangers, and Android versions.

**Comment by grafail** [comment] 2021-06-18 08:17
@allisonkarlitskaya In my case with LastPass I cannot get it to trigger at all.

**Comment by allisonkarlitskaya** [comment] 2021-06-18 09:02
I've also tested with Lastpass and Bitwarden.  I can confirm Lastpass to be broken with Android 11 and Bitwarden to be broken with Android 11 and also the Android 12 beta.  I'm using "Firefox" 89.1.1, as installed from the Play Store.

**Comment by Udayanithig** [comment] 2021-06-18 16:13
> ### What is the user problem or growth opportunity you want to see solved?
> The [Android Autofill Framework](https://developer.android.com/guide/topics/text/autofill) is not currently supported by Firefox, which forces users of apps like LastPass which support the framework to need to switch apps and copy the required credentials.
> There seems to be an old ticket about this as well (https://bugzilla.mozilla.org/show_bug.cgi?id=1352011).
> 
> ### How do you know that this problem exists today? Why is this important?
> Most other browsers (and apps) support this feature. I am currently using the nightly version and it is still not supported (an autofill option should appear in the context menu). This is really important, as not only it affects users while browsing on Firefox, but even when they are using apps that utilise the WebView API for authentication.
> 
> ### Who will benefit from it?
> Everyone using a third party password management service that supports the autofill framework.
> 

    I am using dashlane, and I don't have any issues with Nightly builds. But the stable and beta version autofill is broken.

**Comment by Udayanithig** [comment] 2021-06-18 16:14
I'm using **dashlane**, and I don't have any problems with the nightly build. But the stable and beta version autofill is broken.

**Comment by dplepage** [comment] 2021-07-04 14:56
I'm on Android 11 and many sites work but a few still don't. The login pop-up from boardgamegeek.com, for example, doesn't autofill properly in Firefox proper but does seem to work now in Firefox nightly; the login at account.synology.com, which prompts for an email before even showing a password field, doesn't trigger autofill at all in any version I've tried, and there doesn't seem to be any way to force it to autofill.

**Comment by grafail** [comment] 2021-07-04 15:17
@dplepage I'm on Android 11 (One UI if it matters) as well using the latest nightly version with LastPass and it still does not seem to work at any site (including boardgamegeek.com). What password manager are you using? Maybe this is a LastPass specific issue (or maybe has to do with One UI)?

**Comment by dplepage** [comment] 2021-07-04 16:17
I'm using 1password. 

On the Synology login, Firefox doesn't recognize the email prompt as something that could be autofilled; if I manually enter my email, it will let me autofill the password field that then appears.

On BGG the behavior is weird - if I just go to https://boardgamegeek.com/ and hit "sign in", it works fine, but I was trying to sign in from https://boardgamegeek.com/boardgame/273477/obscurio and the behavior was

1. When the sign in pop-up appeared, the username box was focused and the "autofill" option appeared
2. Choosing to autofill filled the username field but not the password.
3. Selecting the password field did not offer autofill as an option.
4. After reloading, I found that if I *didn't* choose to autofill the username right when it popped up, it would not offer again, no matter how many times I unfocused or refocused that field.

Also, I was wrong when I said it worked in nightly - I only checked the main BGG page there, not realizing that the problem only arose on certain pages.

**Comment by Udayanithig** [comment] 2021-07-15 10:54
I am just confused. Autofill is working fine on firefox nightly but when it comes to beta or stable version, auto-fill is glitchy. I'm on 91.0.0-beta.1 and 90.1.1 (Stable).

**Comment by Udayanithig** [comment] 2021-07-23 06:27
Yes, that's right.

**Comment by Udayanithig** [comment] 2021-08-12 08:02
I'm done and switched to Vivaldi. Bye Firefox 👋

**Comment by gbakeman** [comment] 2021-09-07 22:12
@Udayanithig Mentioned not having issues on nightly, and by doing a [search for "autofill"](https://github.com/mozilla-mobile/fenix/search?q=autofill&type=commits), it looks like Autofill as a user preference has been available since v92.0 beta 2. There's also [a commit](https://github.com/mozilla-mobile/fenix/commit/145f1898f188f2250e3760b8c0a8c62f21d757d4) tagged for 92.0 beta 2 and 92.1.1 that enabled Autofill, but it's failing so I don't know if it made it. I think at least some of those commits might be relevant to this issue. Can anyone with those versions (or newer) of Firefox mobile test and see how it goes?

**Comment by grafail** [comment] 2021-09-07 22:30
> @Udayanithig Mentioned not having issues on nightly, and by doing a [search for "autofill"](https://github.com/mozilla-mobile/fenix/search?q=autofill&type=commits), it looks like Autofill as a user preference has been available since v92.0 beta 2. There's also [a commit](https://github.com/mozilla-mobile/fenix/commit/145f1898f188f2250e3760b8c0a8c62f21d757d4) tagged for 92.0 beta 2 and 92.1.1 that enabled Autofill, but it's failing so I don't know if it made it. I think at least some of those commits might be relevant to this issue. Can anyone with those versions (or newer) of Firefox mobile test and see how it goes?

Just tried again with 93.0a1 and still I cannot get autofill to work. Throughout the last few months, autofill only appeared once or twice completely randomly and just as a one time thing (i.e. same page did not autofill after refreshing).

**Comment by iamperson347** [comment] 2021-10-12 00:36
Chrome also had issues with this but it appears to have been fixed earlier this year. It seems other chromium based browsers are also working correctly with autofill framework. 

When I attempt to autofill in Firefox, Bitwarden does correctly trigger. However, when I select an entry, nothing gets filled when returning to Firefox.

**Comment by tails618** [comment] 2021-11-27 14:59
I'm experiencing the same issue on Nightly w/ Bitwarden. It generally shows up when I click the login fields, but if I click something else it goes away and it reappears sporadically - sometimes when I click a login field again, sometimes when i close the keyboard, sometimes when I switch apps, etc.

**Comment by PyvesB** [comment] 2022-02-20 07:41
This may well be a Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1693152

I'm unsure whether Bitwarden can do anything to improve things on their side, or whether the bulk of the fix lies on the Firefox side.

**Comment by cachemoney8096** [comment] 2022-02-20 21:52
I believe it is, considering it doesn't seem to work great with other password managers either, and I've found Bitwarden works better in other apps. Haven't tested another browser, though.

**Comment by iamperson347** [comment] 2022-06-10 21:08
For those following this issue, it appears this is fixed in the nightly builds and appears to be targeted for Firefox 102.

**Closed** 2022-12-09 15:37 UTC
Labels: Feature:Logins, wontfix, Feature:Autofill
