### ISSUE TITLE
Crashing trying to load bookmarks

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/fenix#5056] opened 2019-08-31 16:58 UTC
## Steps to reproduce
Go to Menu -> Library -> Bookmarks
### Expected behavior
Bookmarks viewed
### Actual behavior
Crash
### Device information
* Android device: Galaxy S10e on Android 9
* Fenix version: Nightly 190831 06:04

**Comment by colintheshots** [comment] 2019-09-04 18:52
Duplicate of #5055

**Closed by colintheshots** 2019-09-04 18:52 UTC
Labels: 🐞 bug
