### ISSUE TITLE
[Bug] Wrong version string for 2.1.0 release

### ISSUE THREAD

**Issue by birdie-github** [mozilla-mobile/fenix#5813] opened 2019-10-07 10:23 UTC
You have released version **"2.1.0"** instead of **2.1.0**, so even the release notes can't be open.

Please push 2.1.1 without quotes.

I'm talking about Android.

**Comment by NotWoods** [comment] 2019-11-22 07:17
Duplicate of #5595

**Closed by NotWoods** 2019-11-22 07:17 UTC
Labels: 🐞 bug
