### ISSUE TITLE
[Bug]: The tabs list resets to the top instead of focusing on the open tab.

### ISSUE THREAD

**Issue by yellowmatter** [mozilla-mobile/fenix#27145] opened 2022-09-23 19:29 UTC
### Steps to reproduce

1. Have a tab open
2. Go to the tabs list

### Expected behaviour

The tabs list should appear focusing on the open tab.

### Actual behaviour

The tabs list resets to the top. 

### Device name

OnePlus 6

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

104.2.0

### Additional information

It seems to happen randomly. I repeated the process of clicking on the tabs list button and then on the android's back button multiple times, as well as switching to another tab and back. Also tried only clicking on a tab and on the tabs list button, and not the back button, and it also resets to the top occasionally. I would say it happens with a few clicks, so it happens very regularly, sometimes with a couple clicks.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21656)

**Comment by bigConifer** [comment] 2022-09-23 23:36
Duplicate of #23584

See https://github.com/mozilla-mobile/fenix/issues/23584#issuecomment-1039030740.

**Comment by SoftVision-LorandJanos** [comment] 2022-09-29 12:42
Hi @yellowmatter. Thanks for your report!
This issue is reproducible, however as commented above, it is covered in the mentioned ticket.
Closing this as duplicate.

**Closed by SoftVision-LorandJanos** 2022-09-29 12:42 UTC
Labels: 🐞 bug, needs:triage
