### ISSUE TITLE
Reopen to last tab

### ISSUE THREAD

**Issue by thepooptoob** [mozilla-mobile/fenix#14416] opened 2020-08-29 07:17 UTC
Opening to a blank page and not being where I left off in a long list of tabs is excruciating. Please add this setting immediately.

**Comment by cadeyrn** [comment] 2020-08-29 08:41
Duplicate of #12062.

**Comment by liuche** [comment] 2020-09-01 01:22
We're working on this this sprint!

**Closed by liuche** 2020-09-01 01:22 UTC
Labels: needs:triage
