### ISSUE TITLE
[crash] latest nightly crashing whenever opening tab view page

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#18533] opened 2021-03-18 04:14 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open any website..click tab button
Firefox is crashing

### Expected behavior
It should show the tabs

### Actual behavior
It's crashing

### Device information

* Device vendor / model and Android version: ? Rog3, A10
* Firefox for Android version: ? (go to Settings -> About Firefox)Latest nightly 17mar

a24294e3-a22f-470b-9cd3-8ecc2bc83578
java.lang.ClassCastException: androidx.recyclerview.widget.LinearLayoutManager cannot be cast to androidx.recyclerview.widget.GridLayoutManager
----
java.lang.ClassCastException: androidx.recyclerview.widget.LinearLayoutManager cannot be cast to androidx.recyclerview.widget.GridLayoutManager
	at org.mozilla.fenix.tabtray.FenixTabsAdapter.onBindViewHolder(FenixTabsAdapter.kt:15)
	at org.mozilla.fenix.tabtray.FenixTabsAdapter.onBindViewHolder(FenixTabsAdapter.kt:5)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:150)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:121)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:22490)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:3)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:31)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:121)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:22490)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:8)
	at android.view.View.layout(View.java:22490)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:22490)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:59)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:25)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:7)
	at android.view.View.layout(View.java:22490)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22490)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22490)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22490)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22490)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:798)
	at android.view.View.layout(View.java:22490)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3204)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2661)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1792)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7883)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
	at android.view.Choreographer.doFrame(Choreographer.java:798)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:7532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by sheikh-azharuddin** [comment] 2021-03-18 04:17
Interestingly this is crashing on grid view only...with **list** view setting page is unresponsive!

![Screenshot_20210318-094704087](https://user-images.githubusercontent.com/58127841/111572606-f1857480-87ce-11eb-87f9-ed5aab61defd.jpg)

**Comment by sheikh-azharuddin** [comment] 2021-03-18 04:26
I believe this might be due to the commit  #17822

**Comment by hwinnemoe** [comment] 2021-03-18 06:08
@sheikh-azharuddin Can you check if the secret setting _Use new Tabs Tray_ is activated on your Nightly? I can only reproduce when I activate this secret setting on Nightly 210317 17:01 (Build #2015799241).

4fe00ab1-9fce-4ba5-824c-372aeefc3492
java.lang.ClassCastException: androidx.recyclerview.widget.LinearLayoutManager cannot be cast to androidx.recyclerview.widget.GridLayoutManager
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=62489080e1624f28bd7542fdcfdf0a28
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-105c0bb0-e57a-4f32-b36d-348550210318
----
```
java.lang.ClassCastException: androidx.recyclerview.widget.LinearLayoutManager cannot be cast to androidx.recyclerview.widget.GridLayoutManager
	at org.mozilla.fenix.tabtray.FenixTabsAdapter.onBindViewHolder(FenixTabsAdapter.kt:15)
	at org.mozilla.fenix.tabtray.FenixTabsAdapter.onBindViewHolder(FenixTabsAdapter.kt:5)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:150)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:121)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:3)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:31)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:121)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:8)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:59)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:25)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:7)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2685)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2175)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1935)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1111)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6017)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:234)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by Raamakrishnan** [comment] 2021-03-18 07:37
Seeing same behavior. Tab tray becomes unresponsive with list view.
@hwinnemoe I had the "Use new Tab tray" enabled. Disabling it fixes it

**Comment by sheikh-azharuddin** [comment] 2021-03-18 07:52
Yep after disabling the setting it is fixed now...quite curious this setting I had enabled since last few builds but facing issue starting yesterday build so maybe something else changed too

**Comment by mcarare** [comment] 2021-03-18 11:08
@jonalmeida Is there an issue opened for implementing grid items in the refactored tab tray?

**Comment by jonalmeida** [comment] 2021-03-18 11:47
> @jonalmeida Is there an issue opened for implementing grid items in the refactored tab tray?

There isn't one, but I've filed a placeholder for now (#18535). 

Maybe it's best to not make this setting available in nightly builds (debug only for now) so folks outside of engineering don't use it unknowingly.

**Comment by jonalmeida** [comment] 2021-03-18 11:49
I'm going to close this as won't fix because, for now, this feature isn't implemented so crashes are expected.

**Closed by jonalmeida** 2021-03-18 11:49 UTC
Labels: Feature:Tabs, b:crash, needs:triage, 🐞 bug
