### ISSUE TITLE
[Bug] Slow link opening

### ISSUE THREAD

**Issue by SlowNicoFish** [mozilla-mobile/fenix#12030] opened 2020-06-26 20:29 UTC
## Steps to reproduce
Click a link on an android device with firefox preview as the default browser

### Expected behavior
Load in a webpage rather fast

### Actual behavior
The browser opens and stalls on a white screen for more than 5 seconds

### Device information
* Android device: Pixel 3XL
* Android version: 10
* Fenix version:Nightly 200626 06:01 (Build #21780613)

**Comment by hakkikaancaliskan** [comment] 2020-06-26 20:40
Could you please share an example website for testing?

**Comment by SlowNicoFish** [comment] 2020-06-26 20:53
I tried this link in a custom tab with some extensions installed

https://auth.voxmedia.com/login?community_id=372&return_to=https://www.theverge.com/

Https redirect
Decentraleyes
Privacy badger
Ublock Origin

**Comment by SlowNicoFish** [comment] 2020-06-26 20:56
One guess is that Https redirect extension might cause a slowdown.
But I really have no idea

**Comment by sheikh-azharuddin** [comment] 2020-06-26 20:57
Works fine here...trying disabling all add ons and try again
Maybe some add on causing issue. I feel privacy badger is the culprit

**Comment by SlowNicoFish** [comment] 2020-06-26 20:58
Alright. Seems to work without extensions. I'm gonna try to isolate the extension

**Comment by SlowNicoFish** [comment] 2020-06-26 21:04
HTTPS Everywhere and pricacy badger both look like they could be the cause. When both these add ons are acivated there seem to be a slowdown

**Comment by hakkikaancaliskan** [comment] 2020-06-26 21:06
HTTPS Everywhere has more filter than ublock and when you select more filter on ublock no need to use privacy badger.
uBlock + Decentraleyes is my suggestion.

**Comment by sheikh-azharuddin** [comment] 2020-06-26 21:08
> HTTPS Everywhere and pricacy badger both look like they could be the cause. When both these add ons are acivated there seem to be a slowdown

I found privacy badger to be culprit in most of the pages...for example in some websites where you can sign with Google account using OAuth it fails.... I don't use https everywhere as firefox already has awesome preference to handle that not sure why they are not promoting it...while https everywhere does not handle all http to https default preference setting does.

Set both preference setting to true. 
![7068](https://user-images.githubusercontent.com/58127841/85901366-399fd980-b7f1-11ea-96a7-98c94f9b9c6f.png)

**Comment by RealGJ** [comment] 2020-06-27 05:17
Duplicate of #11890

**Comment by ekager** [comment] 2020-06-29 16:11
@RealGJ does your bug #11890 also have to do with privacy badger?

**Comment by RealGJ** [comment] 2020-07-01 11:40
@ekager yes. I do use privacy badger. However, I tried after uninstalling privacy badger too, and issue is still there

**Closed** 2021-03-04 04:13 UTC
Labels: Feature:WebExtensions, wontfix, 🐞 bug
