### ISSUE TITLE
Add option in Settings to disable the opening of bookmark in a new tab, instead of the selected one

### ISSUE THREAD

**Issue by Sav22999** [mozilla-mobile/fenix#13920] opened 2020-08-19 09:10 UTC
### Who will benefit from it?
A user reviewed on Play Store and asked this feature, which is very useful

**Comment by s-ankur** [comment] 2020-08-19 10:48
Duplicate of #13336. I don't think there needs to be an option for this, instead it should be the expected behaviour that bookmarks open in same tab. That is how other browsers do it as well and there is already an open in new tab option in bookarks three dot menu

**Comment by ekager** [comment] 2020-12-17 22:50
Closing for #13336

**Closed by ekager** 2020-12-17 22:50 UTC
Labels: Feature:Bookmarks, needs:triage
