### ISSUE TITLE
[Bug] Fullhdfilmizlesene.com - Video Screen Size Disorder

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#11670] opened 2020-06-17 06:00 UTC
## Steps to reproduce
1. Open the Yaani Browser App
1. Go to Fullhdfilmizlesene.com website
1. Tap on any Movie of your Choice
1. When the movie starts to play, tap on "Full Screen Mode" Button
1. Now tap on "minimize Screen" button
    1. Expected behavior
When you enter full screen mode, and change back the video screen size should fit on the page
    1. Actual behavior
The video screen size becomes larger and half way
    1. Device information
Mobile Maker:Huawei,Mobile Carrier:Wi-Fi,Mobile Operating System:Android,Mobile Major Operating System Version:Android 8.x,Mobile Operating System Version:Android 8.1,Mobile Model:Y7

* Android device: Android 8.1
* Fenix version: 5.1.1

![4456387](https://user-images.githubusercontent.com/66958331/84860897-96282980-b078-11ea-8ece-baa642fa19c6.png)

Here is LOG File: [Bug4456387_logcat.txt](https://github.com/mozilla-mobile/fenix/files/4790608/Bug4456387_logcat.txt)

**Comment by s-ankur** [comment] 2020-08-27 15:00
Duplicate of  #8252

**Comment by kbrosnan** [comment] 2020-08-28 16:10
Closing as a duplicate

**Closed by kbrosnan** 2020-08-28 16:10 UTC
Labels: 🐞 bug
