### ISSUE TITLE
[Bug] Desktop Mode toggle doesn't save its state correctly.

### ISSUE THREAD

**Issue by maroonmoon13** [mozilla-mobile/fenix#13202] opened 2020-08-01 23:00 UTC
## Steps to reproduce
Open www.bing.com
Do a search 
Enable desktop mode 
Create a new tab and open www.reddit.com.
Keep browsing reddit for a few minutes in mobile mode. 
Switch to the tab where Bing was opened 
The tab will refresh and the mobile site will open even though desktop mode is enabled 
The browser will become unresponsive from then on 
### Expected behavior
The refreshed tab should open in desktop mode and not make the browser unresponsive 
### Actual behavior
Explained above 
### Device information
Pixel 3
* Android device: 
* Fenix version: latest beta

**Comment by TrianguloY** [comment] 2020-08-30 23:15
More info (I was going to report this, but good thing I checked first).

In order to trigger the bug the page in desktop mode needs to be unloaded (but only that tab, not the browser,). This can be achieved by browsing for a few minutes in another tab. If when switching to the desktop tab it is shown immediately, go back and try again. If it is loaded instead, the bug is triggered (and the page is loaded in mobile mode).

The browser doesn't becomes unresponsive (not for me at least). The only unresponsiveness is that the desktop site toggle does nothing anymore. It is enabled (even though the page is shown in mobile mode) and clicking it makes the tab reload, but in mobile mode and the toggle is kept enabled (can't be turned off).

Navigating in this tab loads all links in mobile mode too.

If you close the tab, the bug disappears (it is a tab-related issue) and other tabs are not affected (unless you trigger the bug on them too).

**Comment by maroonmoon13** [comment] 2020-08-31 00:11
Yes, in case my browser remains usable, I also have the desktop mode setting not behave

**Comment by JackPShafer** [comment] 2020-08-31 17:53
> More info (I was going to report this, but good thing I checked first).
> 
> In order to trigger the bug the page in desktop mode needs to be unloaded (but only that tab, not the browser,). This can be achieved by browsing for a few minutes in another tab. If when switching to the desktop tab it is shown immediately, go back and try again. If it is loaded instead, the bug is triggered (and the page is loaded in mobile mode).
> 
> The browser doesn't becomes unresponsive (not for me at least). The only unresponsiveness is that the desktop site toggle does nothing anymore. It is enabled (even though the page is shown in mobile mode) and clicking it makes the tab reload, but in mobile mode and the toggle is kept enabled (can't be turned off).
> 
> Navigating in this tab loads all links in mobile mode too.
> 
> If you close the tab, the bug disappears (it is a tab-related issue) and other tabs are not affected (unless you trigger the bug on them too).

Thank you @TrianguloY !

This is exactly what happens for me too.  The browser is still responsive for me. The tab is stuck in mobile mode, even though the 'Desktop site' toggle is stuck on active.

**Comment by mcomella** [comment] 2020-09-02 23:47
@maroonmoon13 What do you mean when you say the browser becomes unresponsive? Are you experiencing different behavior than the commenters above?

Triage: if the browser is unresponsive, this is borderline a performance problem. If that's not an issue, this isn't a performance problem.

**Comment by MarcLeclair** [comment] 2020-09-09 17:25
Triage: It looks like  the "Desktop toggle" isn't saving its state correctly. We'll switch this issue to a bug to be fixed since it doesn't look like most of you have unresponsive issue (we'll open another one for responsiveness if we notice it happening or we get more info from @maroonmoon13).

**Comment by maroonmoon13** [comment] 2020-09-09 17:51
I tried replicating this with the latest version, and it seems that the unresponsiveness is gone. But the toggle switch doesn't remember the state and starts behaving erratically.

**Comment by kbrosnan** [comment] 2020-09-24 04:46
Closing as a dupe of #15352 as that one has steps to reproduce.

**Closed by kbrosnan** 2020-09-24 04:46 UTC
Labels: Feature:Browsing, Feature:RequestDesktopSite, eng:performance, needs:triage, 🐞 bug
