### ISSUE TITLE
Better media controls in media notification.

### ISSUE THREAD

**Issue by eNV25** [mozilla-mobile/fenix#14739] opened 2020-09-04 17:37 UTC
### What is the user problem or growth opportunity you want to see solved?
The current media notification only has a play/pause button. Additional buttons for media-forewards media-backwards track-forwards track-backwards could be there.

### How do you know that this problem exists today? Why is this important?
This is implemented well in kiwi browser.
I am using YouTube Music (PWA mode) with Video Background Play Fix extension.

### Who will benefit from it?
Users, user experience will be better.

**Comment by eNV25** [comment] 2020-09-04 17:46
# [Bugzilla: [meta] Control any media without interacting directly with pages where media are](https://bugzilla.mozilla.org/show_bug.cgi?id=1572869)

**Comment by kbrosnan** [comment] 2020-10-07 18:57
Closing as a duplicate of  #5290

**Closed by kbrosnan** 2020-10-07 18:57 UTC
Labels: Feature:Media, feature request 🌟
