### ISSUE TITLE
[Bug] Search engines not synchronized

### ISSUE THREAD

**Issue by vicanfon** [mozilla-mobile/fenix#5423] opened 2019-09-19 09:16 UTC
## Steps to reproduce

Writing a shortcut of already created search engine on firefox desktop doesn't work on firefox preview.
For instance "u music" doesn't for launching a search on youtube with the search engine "https://www.youtube.com/results?search_query=%s". I can see that the bookmark is properly synchronized.

### Device information

* Android device: ?
* Fenix version: Nightly 190918

**Comment by AaronMT** [comment] 2019-09-19 19:39
I don't believe search engines syncing is planned at the moment.

**Comment by NotWoods** [comment] 2019-09-30 03:22
Blocked by #5489

**Comment by liuche** [comment] 2019-11-21 01:42
Dupe of #2497

**Closed by liuche** 2019-11-21 01:42 UTC
Labels: Feature:Search, Feature:SearchProvider, Feature:Sync, 🐞 bug, 🙅 waiting
