### ISSUE TITLE
"Open links in app" doesn't open the separate app

### ISSUE THREAD

**Issue by Sangeppato** [mozilla-mobile/fenix#7494] opened 2020-01-05 11:25 UTC
I'm on Firefox Nightly Preview and I've enabled the new "Open links in app" default option.
It works, but when the app is opened, it appears inside the Firefox app when in "multitasking", instead of a separate one. This can cause issues when you want to go back to the browser.

See the attachment to understand what I mean:
![Screenshot_20200105-122115](https://user-images.githubusercontent.com/37263823/71779361-5ed82b80-2fb6-11ea-9f24-f33b04a22d7a.png)

Firefox should open the separate Reddit app that should appear on its side, like Chrome does

**Comment by hakkikaancaliskan** [comment] 2020-01-05 12:08
Also as a side issue: when you go back to browser with back button, you see current website instead of the previous website.
For example:
1- search youtube on google
2- open YouTube
3- go back to browser with back button
4- you see youtube.com is open instead of google
Can someone confirm this?

**Comment by Sangeppato** [comment] 2020-01-05 13:03
Yes, I forgot to mention this. Basically you will see 2 times the same website: once in the app and another one in the browser page

**Comment by NotWoods** [comment] 2020-01-05 17:09
@rocketsroger Could [`FLAG_ACTIVITY_NEW_TASK`](https://developer.android.com/guide/components/activities/tasks-and-back-stack) be used here?

**Comment by Sangeppato** [comment] 2020-01-05 17:51
Note that if you disable the global "open in app" option and instead manually tap the same function each time you're on reddit/youtube, everything works as expected

**Comment by rocketsroger** [comment] 2020-01-06 13:05
@NotWoods I think you're right, `FLAG_ACTIVITY_NEW_TASK` will probably fix this, I'll look into this.
@Sangeppato I've debugged the side issue where the page is also loaded on the browser side.  In most cases it looks like an redirect was happening when you tap on the reddit link.  I can see this with Google searching Facebook post results as well.  But can't reproduce with Twitter search results.  I'll create an issue for the side effect for further investigation.

**Comment by rocketsroger** [comment] 2020-01-06 13:33
Issue opened for side affect https://github.com/mozilla-mobile/android-components/issues/5471

**Comment by rocketsroger** [comment] 2020-01-06 15:31
A-C issue for this https://github.com/mozilla-mobile/android-components/issues/5473

**Comment by rocketsroger** [comment] 2020-01-06 18:08
main issue fixed by https://github.com/mozilla-mobile/android-components/issues/5473

**Closed** 2020-01-06 18:08 UTC
Labels: Feature:OpenInApp, 🐞 bug

**Comment by Sangeppato** [comment] 2020-01-08 19:20
@rocketsroger 
Thank you!
