### ISSUE TITLE
[Bug] ETP setting is not persistent

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#14949] opened 2020-09-10 14:42 UTC
## Steps to reproduce
Open any page
Click on the shield icon
Toggle to "on" (if not already on)

### Expected behavior
ETP is on if opening shield menu again

### Actual behavior
ETP is always off, not persisted

### Device information

* Android device: pixel 3
* Fenix version: Nightly 9/9

**Comment by liuche** [comment] 2020-09-10 14:53
Should double check that #14785 will not also handle this issue, since it seems similar.

**Comment by hwinnemoe** [comment] 2020-09-10 22:30
It is still blocking actively but reports the state falsely in the user-facing UI.

**Comment by codrut-topliceanu** [comment] 2020-09-15 11:43
I'm unable to reproduce it anymore (I was able to yesterday), except with the steps in https://github.com/mozilla-mobile/fenix/issues/14785. 
I'll tag this issue for QA when https://github.com/mozilla-mobile/fenix/issues/14785 gets merged, if that's ok.

**Comment by hwinnemoe** [comment] 2020-09-15 11:58
I can still reproduce on Nightly 200915 06:08.

**Comment by hwinnemoe** [comment] 2020-09-20 09:36
This is now fixed in Nightly 200920 06:02 (Build #2015764977).

**Comment by AndiAJ** [comment] 2020-09-21 07:57
Hi, **verified as fixed** along with #14785 & #15152  on the latest **Nightly Build 200921** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Closed by AndiAJ** 2020-09-21 07:57 UTC
Labels: Feature:SitePermissions, Feature:TrackingProtection, eng:qa:needed, hershey, 🐞 bug
