### ISSUE TITLE
Unable to attach images to tweets on Twitter.com 

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/fenix#17885] opened 2021-02-06 23:29 UTC
This started up sometime in the last week or so on my Nightly install of Fenix.
It works on the release install of Fenix, haven't checked Beta.

Steps to reproduce:
Sign in to an account on twitter.com
Create a new tweet or reply to another.
Click the button to attach an image.
If the file picker doesn't open automatically, choose the file picker from the options of image sources.
Select an image. 

At this point, the image should be uploaded to twitter and shown as part of your currently drafted tweet. But with this issue, nothing happens, the tweet will still be blank. 

I'm on a Pixel 3 with Android 11. I installed the February security update yesterday, but this issue was happening before that, too.

I'm not in a position to bisect failing builds or do an adb log to see if anything is silently failing, but I can try following up in a few days if it's needed.

**Comment by struthiocamelus** [comment] 2021-02-07 13:18
I can reproduce this as well on a Samsung Galaxy Note 9.

In addition, it seems file uploads do not work anywhere. Unfortunately I too haven't been able to check logcat or the remote console, but once I get a chance I'll update.

**Comment by sharbet** [comment] 2021-02-07 15:06
Yeah, this affects all websites, so recent update must've broken something.
Yandex image search and google image search doesn't work either.

**Comment by hwinnemoe** [comment] 2021-02-07 15:47
Related to/Duplicate of #17817

**Comment by birdie-github** [comment] 2021-02-07 17:28
A dupe of #17817, maybe close this bug report?

**Comment by Mugurell** [comment] 2021-02-08 08:04
Thank you all!
Seem like a duplicate to an issue that will be fixed in the next Nightly.

**Closed by Mugurell** 2021-02-08 08:04 UTC
Labels: needs:triage
