### ISSUE TITLE
[Bug] Twitter PWA Navigation Bar (navbar) is offset from bottom of screen and overlays main content

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#9137] opened 2020-03-13 04:54 UTC
## Steps to reproduce

1. Navigate to twitter.com
2. login
3. add as app
4. open app

### Expected behavior

Navigation bar appears stuck to bottom of screen.

### Actual behavior

Navigation bar is offset by 20-40pixels (hard to tell with high dpi), content appears below the navbar and navbar overlays content. 

![signal-attachment-2020-03-13-005240](https://user-images.githubusercontent.com/152493/76590902-0b59f080-64c5-11ea-99f4-a2f91e166eef.png)

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by KWierso** [comment] 2020-03-13 06:00
Is this a dupe of https://github.com/mozilla-mobile/fenix/issues/8768 ?

**Comment by liuche** [comment] 2020-03-17 02:06
Yes! it's a dupe.

**Closed by liuche** 2020-03-17 02:06 UTC
Labels: needs:triage, 🐞 bug
