### ISSUE TITLE
[Bug] Cannot upload photos if "Don't keep activities" is ON

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#2997] opened 2019-05-30 08:10 UTC
## Steps to reproduce
1. Go to the device's settings and enable the "Don't keep activities"
1. Go to https://imgbb.com/
1. Upload a photo.

### Expected behavior
I should be able to load the selected photo.

### Actual behavior
Here are 2 videos with the behavior when "Don't keep activities" is:

* [OFF](https://drive.google.com/file/d/1eZWneEpF2VzavVCf2T0iticDY1BZ0hYH/view)
* [ON](https://drive.google.com/file/d/18Wgzw0h9nos6QvAHCpC1YjniR0jKWhwz/view)

### Device information
* Android device: Nexus 6P (Android 8.1.0)
* Fenix version: 1.0.1922 (#11500615)

### Note:
Not reproducible on https://postimages.org/

[logcatNexus.txt](https://github.com/mozilla-mobile/fenix/files/3236040/logcatNexus.txt)

**Comment by colintheshots** [comment] 2019-06-05 21:36
@vesta0 I cannot seem to reproduce this bug, even with Don't Keep Activities enabled on an older OS.

**Comment by vesta0** [comment] 2019-06-06 17:33
Thanks @colintheshots 

@softvision-miralobontiu please let me know if you can still re-produce it.

**Comment by softvision-miralobontiu** [comment] 2019-06-07 08:44
Hi all,
I can still reproduce the issue with the latest build 1.0.1923 (#11580610), with Nexus 6P (Android 8.1.0).

**Comment by softvision-miralobontiu** [comment] 2019-10-18 09:20
I found a workaround:
1. Open https://imgbb.com/
2. Tap on the "Upload" button.
3. Reload the page.
4. Tap again on the "Upload" button.

Result: after reloading, the page works, the image can be uploaded. 
Tested on the latest Nightly build 10/18, with Nexus 6P (Android 8.1).

Maybe the logcat will help:
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3743178/logcat.txt)

**Comment by karlcow** [comment] 2020-05-06 06:42
Maybe a similar issue 
https://github.com/webcompat/web-bugs/issues/51489

**Comment by Mugurell** [comment] 2020-10-06 11:23
@softvision-miralobontiu Is this still an issue? I can't reproduce.

**Comment by softvision-miralobontiu** [comment] 2020-10-06 13:08
We were able to reproduce this issue on the latest Nightly build from 10/6 using a Google Pixel 3a (Android 11), and Motorola Nexus 6 (Android 7.1.1). On these devices, we could not upload a picture using the camera, only uploading a picture from Files.

**Comment by Mugurell** [comment] 2020-10-21 18:58
I managed to reproduce this. Indeed, the application used matters.
@liuche Can we take it? If it can be reproduced it can be fixed.

**Comment by sflorean** [comment] 2020-12-30 10:07
Still reproducible on Nexus 6P and latest Nightly build (12/30).

**Comment by sflorean** [comment] 2021-01-15 09:41
Verified as fixed on latest Nightly with Nexus 6 (Android 7.1.1).

**Closed by sflorean** 2021-01-15 09:41 UTC
Labels: Feature:Media, S3, eng:qa:needed, 🐞 bug
