### ISSUE TITLE
Status bar text and icons not visible with website opened in light mode 

### ISSUE THREAD

**Issue by Shaurya-Kalia** [mozilla-mobile/fenix#27387] opened 2022-10-12 18:33 UTC
The android statusbar text and icons are same color as background when a website is opened in firefox nightly with dark mode disabled. The issue does not occur on homepage but only when a website is opened.

![Screenshot_2022-10-13-00-01-18-84_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/6441797/195421034-c3c8bc49-edd7-47b1-b8c2-67a825d14970.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21789)

**Comment by fice-t** [comment] 2022-10-13 04:07
What exact version did you build with? This was very recently fixed by an update to used `androidx` library, so a new Nightly version should do the trick.

**Comment by andrejmoltok** [comment] 2022-10-13 19:38
So, from now on I should be using Night mode for this to work properly? I am end-user, never built Firefox, besides on phone I would know how.

**Comment by fice-t** [comment] 2022-10-13 20:02
No, I meant that it should be fixed on an up-to-date version of the app (Firefox Nightly -- 107.0a1) from the Google Play Store. Can you update and check if you can still reproduce this? If you still can, please post your exact Firefox version and Android version.

**Comment by andrejmoltok** [comment] 2022-10-13 20:30
I have downloaded a Nightly for Developers and the problem is gone on Android.

**Comment by SoftVision-LorandJanos** [comment] 2022-10-14 04:57
Hi @Shaurya-Kalia! Thanks for your report! 
This issue is fixed, and recently verified in #26674, please update to the latest version. Thank you!

**Closed by SoftVision-LorandJanos** 2022-10-14 04:57 UTC
Labels: needs:triage

**Comment by Shaurya-Kalia** [comment] 2022-10-14 07:49
Just checked in latest nightly and its fixed in both devices
