### ISSUE TITLE
FNX3-16321 ⁃ [Bug] Snackbar change Tab is in a-c design

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#2433] opened 2019-05-11 08:01 UTC
## Steps to reproduce
Open any site
click with a long press on a link
open this link in a new tab

### Expected behavior
Snackbar for opened and change tab appears in fenix design (e.g. blue white) 

### Actual behavior
Snackbar in a-c styles appears

### Device information
* Android device: Huawei P smart, Samsung Galaxy Tab A (2016) SM-T580 
* Fenix version: 1.0.1919, till today's nightly revisions

![Screenshot](https://user-images.githubusercontent.com/44252450/57567051-d6c46680-73d3-11e9-8fde-2cbd76370b51.jpg)UNITO-UNDERSCORE!20190511-095416!UNITO-UNDERSCORE!Firefox Preview!

**Comment by cadeyrn** [comment] 2019-05-11 08:07
Duplicate of #1997.

**Comment by pocmo** [comment] 2019-05-16 14:19
Closing as duplicate of #1997 (Thanks @cadeyrn!)

**Closed** 2020-08-13 14:18 UTC
Labels: 🐞 bug
