### ISSUE TITLE
In Reader View, code/pre blocks use sans-serif/serif instead of monospace

### ISSUE THREAD

**Issue by nyanpasu64** [mozilla-mobile/fenix#18222] opened 2021-03-01 01:37 UTC
## Steps to reproduce

- In Firefox Fenix, visit a page with code blocks (pre or code tags) ([example site](https://nyanpasu64.github.io/blog/an-unsafe-tour-of-rust-s-send-and-sync/)).
- Tap the Reader View button in the address bar.

### Expected behavior

Code blocks are rendered in a monospace font.

### Actual behavior

Code blocks are rendered in a sans-serif font.

This is due to https://github.com/mozilla-mobile/android-components/blob/584a6fc02a11a4c5928dcfd4089110871f242a75/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css#L41-L47.

```css
.mozac-readerview-body.sans-serif * {
  font-family: sans-serif !important;
}

.mozac-readerview-body.serif * {
  font-family: serif !important;
}
```

These CSS rules override `pre` and `code` defaulting to a monospace font.

### Device information

* Device vendor / model and Android version: moto g power (2021), Android 10
* Firefox for Android version: Nightly 210227 17:01 (Build #2015795787); AC: 74.0.20210227143138, 5437eb229; GV: 88.0a1-20210227094458; AS: 72.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9850)

**Comment by kbrosnan** [comment] 2021-03-01 18:11
Opened an issue with the upstream repo https://github.com/mozilla/readability/issues/676

**Comment by kbrosnan** [comment] 2021-03-01 18:20
Talked with Gijs and he pointed out that this is is AC code.

**Comment by LaurentiuApahideanSV** [comment] 2021-03-31 14:04
I can confirm the issue is reproducible on Firefox RC 87.0.0 and Nightly 210331.

### Device used:
- OnePlus 6T (Android 9)
- Google Pixel 3XL (Android 9)

**Comment by nyanpasu64** [comment] 2021-09-27 19:03
still broken

**Comment by nyanpasu64** [comment] 2022-03-26 20:01
still happens

**Comment by fice-t** [comment] 2022-10-21 23:33
This is fixed with the following diff:

```diff
diff --git a/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css b/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css
index 34ff31c5d2..5344489f0d 100644
--- a/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css
+++ b/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css
@@ -38,11 +38,11 @@
   color: #eeeeee;
 }

-.mozac-readerview-body.sans-serif * {
+.mozac-readerview-body.sans-serif {
   font-family: sans-serif !important;
 }

-.mozac-readerview-body.serif * {
+.mozac-readerview-body.serif {
   font-family: serif !important;
 }
```

I tried a more fine-grained change, but I couldn't get it to work:
<details><summary>Failed approach</summary>

```diff
diff --git a/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css b/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css
index 34ff31c5d2..a35c265505 100644
--- a/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css
+++ b/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css
@@ -38,11 +38,11 @@
   color: #eeeeee;
 }

-.mozac-readerview-body.sans-serif * {
+.mozac-readerview-body.sans-serif *:not(code, pre) {
   font-family: sans-serif !important;
 }

-.mozac-readerview-body.serif * {
+.mozac-readerview-body.serif *:not(code, pre) {
   font-family: serif !important;
 }

@@ -267,6 +267,7 @@
    are properly wrapped inside content width */
 .mozac-readerview-content code,
 .mozac-readerview-content pre {
+  font-family: monospace !important;
   white-space: pre-wrap !important;
   margin-bottom: 20px !important;
 }
```

</details>

<details><summary>Failed approach 2</summary>

```diff
diff --git a/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css b/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css
index 34ff31c5d2..a35c265505 100644
--- a/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css
+++ b/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css
@@ -38,11 +38,11 @@
   color: #eeeeee;
 }

-.mozac-readerview-body.sans-serif * {
+.mozac-readerview-body.sans-serif :not(code, pre) {
   font-family: sans-serif !important;
 }

-.mozac-readerview-body.serif * {
+.mozac-readerview-body.serif :not(code, pre) {
   font-family: serif !important;
 }

@@ -267,6 +267,7 @@
    are properly wrapped inside content width */
 .mozac-readerview-content code,
 .mozac-readerview-content pre {
+  font-family: monospace !important;
   white-space: pre-wrap !important;
   margin-bottom: 20px !important;
 }
```

</details>

@csadilek Is there a reason why A-C uses a wildcard here? The [CSS that Desktop uses](https://searchfox.org/mozilla-central/rev/c5c002f81f08a73e04868e0c2bf0eb113f200b03/toolkit/themes/shared/aboutReader.css#155) does not use wildcards for `font-family` setting.

**Comment by gabrielluong** [comment] 2023-01-30 23:52
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813891

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by gabrielluong** 2023-01-30 23:52 UTC
Labels: 🐞 bug, needs:ac, Feature:ReaderMode, qa-triaged
