### ISSUE TITLE
back button on "About Fenix" should not close the browser

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#714] opened 2019-02-27 20:51 UTC
## Steps to reproduce

1. start Fenix
2. press the menu button
3. press the settings menu item
4. press the "About Fenix" item
5. press the back button of your device

### Expected behavior

Fenix should navigate back to the settings (the same scren after step 3).

### Actual behavior

Fenix is gone, you're on the Android (not the browser's!) home screen.

### Device information

* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 59c514996b4a6f677f623cbae12372d53c51a189

**Comment by sblatz** [comment] 2019-02-27 22:13
I believe this is a dupe of #517. All browser fragment tabs do this at this time, unfortunately.

**Closed by sblatz** 2019-02-27 22:13 UTC
