### ISSUE TITLE
FNX-12038 ⁃ Option to play video in the background

### ISSUE THREAD

**Issue by linuxlover** [mozilla-mobile/fenix#11161] opened 2020-06-02 21:59 UTC
I like the new firefox (Preview)

One option is missing for me. 
Give option to play background video. In that way i can play youtube in one tab and meantime checking some thing on other tabs or even switch off the screen.

**Comment by kbrosnan** [comment] 2020-06-02 22:04
Youtube stops video playback when the user switches away from the tab. Duplicate of #10366

**Comment by vishalnandagopal** [comment] 2020-06-08 18:07
There is a way to implement this.

Chromium browsers run a background channel.
It is enabled in settings ' Play background Videos'

I have previously tested on Brave Browser. It worked well.

**Closed** 2020-08-11 03:16 UTC
Labels: needs:triage
