### ISSUE TITLE
[Bug]: Nightly crashed after changing the wallpaper

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#26723] opened 2022-08-31 07:29 UTC
### Steps to reproduce

1. Have a fresh install.
2. Go to Settings>Homepage>Wallpapers and change the wallpaper.
3. Close and reopen the app.

### Expected behaviour

The app opens without issues with the newly set wallpaper.

### Actual behaviour

The app crashes.

### Device name

Oppo Find X5

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1 (2022-08-31)

### Device logs

[CrashOnLaunchAfterSettingAWappaper.txt](https://github.com/mozilla-mobile/fenix/files/9459467/CrashOnLaunchAfterSettingAWappaper.txt)

### Additional information

- There was no crash notification.
- The log was created when reproducing the issue offline.

https://user-images.githubusercontent.com/48829350/187649192-a767489e-34e2-496f-a770-298f9d0088c6.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21428)

**Comment by Mugurell** [comment] 2022-08-31 12:06
This seems to follow the recent changes and is easy to reproduce.
Will investigate.

**Comment by Mugurell** [comment] 2022-08-31 12:41
Exception:
>     android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
>        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9392)
>        at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1757)
>       at android.view.View.requestLayout(View.java:25595)
>        at android.view.View.requestLayout(View.java:25595)
>        at android.view.View.requestLayout(View.java:25595)
>        at android.view.View.requestLayout(View.java:25595)
>        at android.view.View.requestLayout(View.java:25595)
>        at android.view.View.requestLayout(View.java:25595)
>        at android.view.View.requestLayout(View.java:25595)
>        at android.view.View.requestLayout(View.java:25595)
>        at android.view.View.requestLayout(View.java:25595)
>        at android.view.View.requestLayout(View.java:25595)
>        at android.widget.ImageView.setImageDrawable(ImageView.java:605)
>        at androidx.appcompat.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:1)
>        at android.widget.ImageView.setImageBitmap(ImageView.java:769)
>        at androidx.appcompat.widget.AppCompatImageView.setImageBitmap(AppCompatImageView.java:1)
>        at org.mozilla.fenix.home.WallpapersObserver.showWallpaper$app_nightly(WallpapersObserver.kt:15)
>        at >org.mozilla.fenix.home.WallpapersObserver$observeWallpaperUpdates$1$1.invokeSuspend(WallpapersObserver.kt:1)

It's interesting that this seems intermittent on Nightly and I can't reproduce it locally.
But based on the stacktrace the solution is simple.

**Comment by delia-pop** [comment] 2022-09-01 10:49
Verified as fixed on the latest Nightly 106 updated from main locally. The app no longer crashes on startup when a wallpaper is selected. 

https://user-images.githubusercontent.com/89388888/187896667-128b285e-d829-418c-9782-2981f97cfbd7.mp4

**Closed by delia-pop** 2022-09-01 10:49 UTC
Labels: 🐞 bug, b:crash, eng:qa:needed, S2, Feature:Wallpapers
