### ISSUE TITLE
[Bug] "Save to collection" button animates down from top of tab tray before tabs are shown (from tab tray)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#13950] opened 2020-08-19 22:43 UTC
like #13293

## Steps to reproduce

1. Open enough tabs to fill tab tray
2. tap tab tray switcher button
3. tap private tabs icon
4. tab regular tabs icon

### Expected behavior

Tabs appear without distracting animation. 

### Actual behavior

"Save to collection" button animates down as soon as the tab tray appears and before any tabs appear. This is distracting and makes the tab tray feel slow - and is completely unnecessary as it isn't even easy to see what is animating down. The physics of the button also seems very strange. 

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by yoasif** [comment] 2020-08-28 05:57
@jonalmeida can you take a look here?

**Comment by jonalmeida** [comment] 2020-08-28 21:11
@yoasif if you get a chance, could you take a video of what you're seeing? I'm having trouble reproducing it locally.

**Comment by yoasif** [comment] 2020-08-28 23:10
@jonalmeida Here you go:

![signal-2020-08-28-190654](https://user-images.githubusercontent.com/152493/91621713-11a03400-e962-11ea-91a7-009447d125ee.gif)

**Comment by jonalmeida** [comment] 2020-08-28 23:24
Wow, that's interesting! It settles a hypothesis I've had for a while with the way tabs are loaded in the tray.

Notes mostly for myself: in Fenix we have [`onTabsUpdated`](https://github.com/mozilla-mobile/fenix/blob/96207630fce1e9ab058543a445e0e9f7b7aba0e1/app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt#L181) which is invoked when tabs are added, but not _when tabs are done loading on the screen_. 

So what we're seeing is a case where we are notified that we can put the 'Add to collections' (ATC) button on the screen, but the UI has not finished loading the tabs into the `RecyclerView.Adapter`.

This is more visibly seen when you have many tabs and/or an older phone.

What we need, is a notification that tells us when the adapter is done loading tabs and only then show the ATC button.

Thanks for helping nip the problem in the bud @yoasif !

**Comment by jonalmeida** [comment] 2021-06-16 18:46
I think we can close this as WONTFIX now because we've removed the second adapter that contains the collections button.

**Closed by jonalmeida** 2021-06-16 18:46 UTC
Labels: Feature:Tabs, wontfix, 🐞 bug
