### ISSUE TITLE
[Bug] Main menu opens twice when tapping quickly

### ISSUE THREAD

**Issue by callahad** [mozilla-mobile/fenix#4690] opened 2019-08-12 17:00 UTC
## Steps to reproduce

1. Visit a website
2. Quickly double-tap the three-dot menu

### Expected behavior

1. The first tap opens the menu
2. The second tap triggers the Refresh button (or equally acceptably, does nothing at all)

### Actual behavior

* The menu opens twice, and thus requires two interactions to dismiss.

This screenshot shows the second main menu in the middle of its animation, as it appears atop the first main menu:

![Fenix-Doppelmenu](https://user-images.githubusercontent.com/24193/62883027-11b79c80-bd2b-11e9-9f32-fbae52574d2b.png)

### Device information

* Android device: Pixel 3a, running Android Q Beta 6
* Fenix version: Nightly 190811 06:05 (Build #12230729), :package: 8.0.0 8f87df870, :lizard: 69.0-20190808090046

**Comment by kbrosnan** [comment] 2019-08-13 21:41
I can reproduce this on Android Q using a Pixel 2 XL. I am not able to reproduce this on a Pixel 3 running Android 9, Note 9, Galaxy S8 or a Nexus 5x. Looks to be Android Q only.

**Comment by cadeyrn** [comment] 2019-08-13 21:44
I can reproduce on HTC U11 with Android 9.0.

**Comment by sblatz** [comment] 2019-08-14 20:01
I was able to reproduce this on my Galaxy s9 on 9.0.

This definitely feels like an edge case as you have to tap *very* quickly. But perhaps we should disable the button while the menu is inflating.

**Comment by KaenDagger** [comment] 2019-09-01 12:28
I could do this

**Comment by KaenDagger** [comment] 2019-09-01 18:17
Correct me if wrong. This would require change" MenuButton Component". I could disable the button onClick. and after some delay enable the menu button again

**Comment by sblatz** [comment] 2019-09-05 20:34
@KaenDagger 

>  and after some delay enable the menu button again. 

I would just enable it again when the animation is done :)

**Comment by mcarare** [comment] 2019-09-27 08:54
related issue: #3584

**Comment by Mugurell** [comment] 2019-10-01 15:36
This is really bugging me on release.
Happy to see there's already a bug filed for it.

I just put up a PR for https://github.com/mozilla-mobile/android-components/issues/4588 which would close the menu if it is already showing when tapping the three-dot menu.
(using talkback it would be possible to show many new menu popups as the three-dot menu would remain focused and any double tap would again trigger it's click listener)

But I think the issue here is different than the one from a-c referenced above and for fixing this I'm leaning more towards a throttled click listener which would ignore all click events 300/500 ms after registering the first click of the three-dot menu.

**Comment by AndiAJ** [comment] 2019-11-26 10:48
Hi, I've just checked this issue on the latest **Nightly Build #13300628 from 11/26** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

Compared to the other devices I've noticed quite an odd behavior on the Google Pixel 3a XL (**Android 10**) and Huawei Mate 20 Lite.
The menu is dismissed whereas on the other 4 devices the menu remains displayed.

► Video Google Pixel 3a XL
![20191126_122623](https://user-images.githubusercontent.com/51314259/69622754-3de0fa00-104a-11ea-995e-e63108afe562.gif)

► Video Huawei Mate 20 Lite
![20191126_123700](https://user-images.githubusercontent.com/51314259/69623127-f444df00-104a-11ea-98ef-bb2494c3187b.gif)

@sblatz - Please advise. :)
**I'll remove the QA needed label until further notice.**

**Comment by sblatz** [comment] 2019-11-26 19:25
@Mugurell any ideas what's going on here? 😅

**Comment by sblatz** [comment] 2019-11-26 19:27
We should roll back this PR if we can't figure this out. 

@boek can you please watch this while I'm on PTO to make sure this doesn't ship? 😬

**Comment by Mugurell** [comment] 2019-11-27 09:26
> @Mugurell any ideas what's going on here? 😅

I'd say @AndiAJ 's findings for when testing on Google Pixel 3a XL (Android 10) and Huawei Mate 20 Lite represent the expected behavior as per my comment above - https://github.com/mozilla-mobile/fenix/issues/4690#issuecomment-537095199 which proposed a solution but nothing was implemented.

- The first scenario - "menu being closed" happens if tapping fast enough, the menu is not yet on the screen so the second tap is also made on the menu button. The second tap closing the menu is the expected outcome and as per my comment above replaces the initial issue - `Main menu opens twice when tapping quickly`
- The second scenario - "the menu remains displayed" happens if user did not tap fast enough/the device didn't record the second tap in time for the second tap to be on the menu button also, but on the newly shown menu (in a part which doesn't react to touches).

The above is happening on both Nightly and Release versions of Fenix.

I'll work on a quick implementation of a throttled click listener for the menu button to fix this.

**Comment by Mugurell** [comment] 2019-11-28 15:41
The above patches resolve the same issue for the menus in `HomeFragment`-  https://drive.google.com/file/d/1EnpIhAeLp8Wd72A3kQXPC0SsBGoAoAu5/view?usp=sharing

https://github.com/mozilla-mobile/android-components/issues/5176 fixes the menu issue for the browser toolbar.

**Comment by Mugurell** [comment] 2020-04-30 06:39
Closing this following Chenxia's and Sebastian's review comments - https://github.com/mozilla-mobile/fenix/pull/6854#issuecomment-605304129, https://github.com/mozilla-mobile/android-components/pull/5184#issuecomment-584120464

**Closed by Mugurell** 2020-04-30 06:39 UTC
Labels: Feature:AndroidIntegration, Feature:MainMenu, P5, S3, needs:ac, 🐞 bug
