### ISSUE TITLE
[Bug] Notification banner after closing a private tab does not disappears

### ISSUE THREAD

**Issue by hammershrk** [mozilla-mobile/fenix#8009] opened 2020-01-30 23:58 UTC
## Steps to reproduce
Open a few private tabs
close one of the tabs
switch to a remaining open private tab

### Expected behavior
A notification banner indicating that you've closed a private tab and allowing you to undo (re open the tab) is displayed momentarily

### Actual behavior
The notification is persistent and doesn't disappear. If you open sites such as The Guardian that asks you to accept cookies, the banner blocks the 'accept' button and you need to return to the all open tabs menu scroll up and down a number of times for the banner to disappear.

### Device information

* Android device: Essential PH1 with Android 10
* Fenix version: 3.2.0

**Comment by cadeyrn** [comment] 2020-01-31 06:26
Duplicate of #7799.

**Closed** 2020-02-04 00:14 UTC
Labels: needs:triage, 🐞 bug
