### ISSUE TITLE
[Bug] link opens Playstore page instead of app

### ISSUE THREAD

**Issue by Smollejan** [mozilla-mobile/fenix#13504] opened 2020-08-11 15:34 UTC
## Steps to reproduce
VIDEO: https://youtu.be/20rx6nX7MCg

### Expected behavior
Link to open DigiD app opens DigiD app.
### Actual behavior
Link to open DigiD app opens Playstore page of DigiD app while the app is installed on my device.
### Device information

* Android device: Xiaomi Mi-9T Miui 11.0.5
* Fenix version: 80.0.0-beta.5

**DigiD is used to logon to government sites in The Netherlands. 
*** It was working fine a few versions ago.

**Comment by liuche** [comment] 2020-08-13 14:48
There may be other dupes in the OpenInApp feature label. You could talk to Roger from the AC team if you want more guidance.

**Comment by Smollejan** [comment] 2020-08-14 18:26
Thank you! It's weird tho, because is was working perfectly a few versions ago.

**Comment by liuche** [comment] 2020-08-18 01:49
This is a dupe of #13040

**Comment by Smollejan** [comment] 2020-08-20 08:47
Fixed: https://github.com/mozilla-mobile/fenix/issues/12746 Thanks!

**Comment by Smollejan** [comment] 2020-09-10 20:25
The issue is back after 80.1.2 update.

**Closed** 2021-03-16 22:10 UTC
Labels: Feature:OpenInApp, hershey, wontfix, 🐞 bug
