### ISSUE TITLE
[Bug] Fix strict mode violation on Nightly caused by org.mozilla.fenix.components.Analytics.getExperiments

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#16984] opened 2020-12-11 19:40 UTC
Fix the following strict mode violation:
https://gist.github.com/travis79/88779741ced2bddf03fe68797c3faa8f

**Comment by mcomella** [comment] 2020-12-16 22:58
Triage: the folks who implemented this change are in a better position to address this issue than the performance team so we'll defer to them.

This may also be the cause of a very large regression in nightly: #17086.

**Comment by mcomella** [comment] 2020-12-18 17:44
This doesn't seem to be the cause of the major regression: that is a network call and this is for disk IO. We'll need to wait to see if this gets fixed with the fix for the regression though.

**Comment by mcomella** [comment] 2021-01-07 01:25
This call does not exist:
```
        at java.io.File.listFiles(File.java:1216)
        at org.mozilla.fenix.components.Analytics$experiments$2.invoke(Analytics.kt:115)
```

It likely came from a local build so we're going to close this as WORKSFORME. Please reopen if you see this again.

**Closed by mcomella** 2021-01-07 01:25 UTC
Labels: eng:performance, 🐞 bug
