### ISSUE TITLE
[Bug] Sometimes closed tabs are restored 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5843] opened 2019-10-08 12:51 UTC
## Steps to reproduce
1. Add a page shortcut on the homescreen. Launch Fenix from the shortcut.
2. Load a few tabs.
3. Go to homescreen, tap the 3 dot button, tap Close all tabs.
4. Swipe to kill the app.
5. Launch Fenix again (using the shortcut or the app launcher).
### Expected behavior
Tabs are not restored.
### Actual behavior
sometimes the tabs are restored: all or just some of the latest ones.
### Device information

* Android device: Pixel 3 (Android 9)
* Fenix version: Nightly 10/8

**Comment by boek** [comment] 2019-12-28 03:18
This is working as intended. With the **undo** functionality we delay actually deleting the tabs until a user takes an action. Force closing the application prevents us from actually closing the tabs after that window.

**Comment by boek** [comment] 2019-12-28 03:18
I want to close this, but the more I think about it I feel like it could be a common use case. going to bump this to triage to discuss

**Comment by Baron-Severin** [comment] 2020-01-14 19:11
We should timebox this to avoid going down a rabbit hole.

Refactor note: currently we're flipping these between two states (created / deleted), with some delays before moving between them.  We can't reliably execute code when the app is being killed, leading to this edge case.  If we instead moved between three states (created / deletionScheduled / deleted) it could handle this.  When starting the app, anything in state `deletionScheduled` could be cleaned up.

It will be important for `deletionScheduled` to include _when_ it was scheduled, to avoid the edge case of "delete tab -> wait .4999 seconds -> delete second tab -> wait .0001 seconds -> both tabs are deleted".

**Comment by AndiAJ** [comment] 2020-02-26 13:14
Hi, **verified as fixed** on the latest **`Nightly Build #20570604 from 02/26`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20200226-150425](https://user-images.githubusercontent.com/51314259/75347986-a1c5c980-58aa-11ea-9b3b-147b83410df0.gif)

**Closed by AndiAJ** 2020-02-26 13:14 UTC
Labels: P2, S2, eng:qa:needed, 🐞 bug
