### ISSUE TITLE
[Bug] Using Twitter in a pwa pauses audio in other apps when scrolling past videos.

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#7835] opened 2020-01-21 19:13 UTC
## Steps to reproduce

1. Login to Twitter on fenix
2. Install as pwa
3. Play audio in another app. I used antennapod and played a podcast
4. Open Twitter pwa
5. Scroll past Twitter posts that include embedded videos, eg https://mobile.twitter.com/StandUpAmerica/status/1219675114268233728

### Expected behavior

Antennapod does not pause, like it doesn't when browsing Twitter in Fenix directly.

### Actual behavior

Antennapod stops playing audio.

### Device information

* Android device: pixel  2
* Fenix version: latest nightly

**Comment by TitanNano** [comment] 2020-01-21 21:49
I also experience this. Muted videos shouldn't interrupt other audio.

**Comment by NotWoods** [comment] 2020-01-24 02:47
Duplicate of https://github.com/mozilla-mobile/android-components/issues/4253.

**Closed by NotWoods** 2020-01-24 02:47 UTC
Labels: Feature:Media, needs:triage, 🐞 bug
