### ISSUE TITLE
FNX2-13002 ⁃ [Bug] When "Open links in apps" is enabled websites which have Play Store links don't redirect to the Play Store app and instead open them on the Play Store's website

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12092] opened 2020-06-29 14:27 UTC
Have the "Open links in apps" enabled in settings.

When the "Open links in apps" is enabled the website which have Play Store links don't redirect to to the Play Store app and instead open them on the Play Store website.

### Steps to reproduce
1. https://www.androidpolice.com/2020/06/27/the-best-free-and-open-source-alternatives-to-gmail-on-android/ 

On the above site there're 2 links where they redirect to FairMail and K-9 Mail. Click on them and see it doesn't redirect to the Play Store app but instead opens the Play Store website. On Chrome browser it redirects to the Play Store on clicking those links.

1. https://www.apkmirror.com/apk/mozilla/firefox-preview-nightly-for-developers/firefox-preview-nightly-for-developers-nightly-200505-0600-release/

Here click on the Play Store icon and see it doesn't redirect to the Play Store and instead redirects to the Play Store website. On Chrome browser it opens the Play Store app. 

Device: Motorola One Power, Android 10.
Fenix: **`Nightly 200629 06:01`**.

**Comment by SS1113** [comment] 2020-06-30 00:59
@rocketsroger I have a question. When the site is open in the specified app, it has a  text on the following webpage: 

___
## 302 Moved 

The site has moved here. 

___

I find this useful however this is really small, seems like the webpage was designed for desktop. Is it dependent on website the Fenix controls it?

**Comment by rocketsroger** [comment] 2020-06-30 14:21
> @rocketsroger I have a question. When the site is open in the specified app, it has a text on the following webpage:
> ## 302 Moved
> 
> The site has moved here.
> 
> I find this useful however this is really small, seems like the webpage was designed for desktop. Is it dependent on website the Fenix controls it?

This is due to the design of the site and our behaviour of opening the destination in app.  When you tap on the link, it first redirect to this page before redirecting to destination that will be opened by the app.  However, since we open the destination in an app, when the user return they will see the page that does the redirect.

**Comment by rocketsroger** [comment] 2020-07-10 18:50
After investigation, the main reason for this is if the request is new window then we're not intercepting the request.  I'll look into removing this condition.  New window request should be intercepted.

**Comment by ShatteredPixel** [comment] 2020-07-16 03:19
rocketsroger, I am the reporter of this issue. Please let me know if I can provide you any more information. Thanks. :)

**Comment by rocketsroger** [comment] 2020-07-16 03:33
> rocketsroger, I am the reporter of this issue. Please let me know if I can provide you any more information. Thanks. :)

This one should be fixed soon in Nightly. I'll update.  Thanks,

**Comment by rocketsroger** [comment] 2020-07-17 13:28
This should be fixed in Nightly.  Please verify.  Thanks!

**Comment by ShatteredPixel** [comment] 2020-07-17 13:49
> This should be fixed in Nightly.  Please verify.  Thanks!

It's working perfectly! Thanks for such a great work on this.


Tested on: `Nightly 200717 07:50`.

Thanks again!

**Comment by ShatteredPixel** [comment] 2020-07-17 13:56
It's a bit off-topic but I'm experiencing another unexpected issue when the "Open link in app" is enabled. 


I have these some apps installed GitHub, LiveChart.me, YouTube app, etc.

As soon as as type GitHub.com, LiveChart.me and YouTube.com 

Chrome doesn't behave like this and it's not that I want the Chrome's behaviour but don't you think if the users are typing the website address in Fenix intentionally then they will want to go to the website and not get redirected the installed app?

**Comment by rocketsroger** [comment] 2020-07-17 14:01
> Do you think I should open an issue for this?

I didn't notice this when I was testing the new change.  Yes, please open an issue for this.  I'll look into fixing this.  Thanks!

**Comment by ShatteredPixel** [comment] 2020-07-17 14:16
#12670 this is the issue I opened for the issue mentioning above.

Thanks.

**Comment by LaurentiuApahideanSV** [comment] 2020-07-20 10:55
Verified as fixed on Firefox Preview Nightly 200720 (Build #22020612).
### Devices used
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)

**Comment by rocketsroger** [comment] 2020-07-20 13:07
Verified fixed.

**Closed** 2020-08-12 17:22 UTC
Labels: eng:qa:verified, 🐞 bug
