### ISSUE TITLE
[Bug]: Autoplay settings are ignored at amp.reddit.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/fenix#22460] opened 2021-11-16 14:59 UTC
### Steps to reproduce

**Preconditions**
Autoplay settings set to "Block audio and video"

1. Access https://amp.reddit.com/r/piano/comments/g2t2pz/recording_yamaha_p125_to_a_daw/
2. Observe the result

### Expected behaviour

The media content should be blocked regarding audio and video playback

### Actual behaviour

The video plays with both audio and video playback

### Device name

Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 96.0a1 (2015845995 -🦎96.0a1-20211115093917🦎)

### Additional information

1 .The issue is reproducible regardless of the settings made in the "Autoplay" settings of the browser
2. Reproducible regardless of the status of ETP
3. Reproducible on the latest build of Firefox Nightly
4. Works as expected using Chrome

**Comment by Mugurell** [comment] 2021-11-16 15:28
Moving to Bugzilla since it reproduces also on `geckoview_example`.
Interestingly it doesn't reproduces on desktop.

**Comment by Mugurell** [comment] 2021-11-16 15:28
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1741424

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by Mugurell** 2021-11-16 15:28 UTC
Labels: 🐞 bug, needs:triage
