### ISSUE TITLE
[Bug] Intent url when the app is not installed errors

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#8257] opened 2020-02-10 06:05 UTC
## Steps to reproduce

Go to https://oxide.computer/blog/on-the-metal-9-jonathan-blow/

Click "Google Play Music" button, with "Open links in apps" checked in settings, and Google play music not installed / disabled.

### Expected behavior

Remain on play.google.com, probably, where it offers me to install the app.

### Actual behavior

Fenix navigates to intent://play.google.com/music/m/Iycdfnasjwyvpe7ona6zwjwhkr4?t=On_The_Metal&u=0#Intent;scheme=googleplaymusic;package=com.google.android.music;S.browser_fallback_url=https%3A%2F%2Fplay.google.com%2Fmusic%2Fm%2FIycdfnasjwyvpe7ona6zwjwhkr4%3Ft%3DOn_The_Metal%26u%3D0%26nomobilenative%3D1;S.android.intent.extra.REFERRER_NAME=https%3A%2F%2Fplay.google.com%2Fmusic%2Fm%2FIycdfnasjwyvpe7ona6zwjwhkr4;end and errors out with "unknown protocol".

It seems there's affallback url in there that Fenix should try to use?

### Device information

* Android device: Galaxy A20
* Fenix version: Nightly

**Comment by kbrosnan** [comment] 2020-02-10 17:42
Unknown protocol error? if so dupe of #7331

**Comment by emilio** [comment] 2020-02-10 19:11
yes, unknown protocol.

Duplicate of #7331 then.

**Comment by rocketsroger** [comment] 2020-02-10 20:04
Reopening to confirm if it is the same issue.  The result might look the same but the issue could be different.

**Comment by rocketsroger** [comment] 2020-02-10 21:54
Confirmed. Same as https://github.com/mozilla-mobile/fenix/issues/7331.  Closing.

**Closed by rocketsroger** 2020-02-10 21:54 UTC
Labels: needs:triage, 🐞 bug
