### ISSUE TITLE
[Bug]today nighlty still crashing a lot 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#14685] opened 2020-09-03 13:53 UTC
today nighlty is still crashing a lot here s the soccorro :https://crash-stats.mozilla.org/report/index/bp-b29105a8-d593-4cf0-bbc6-b4fba0200903

**Comment by evilpie** [comment] 2020-09-03 14:10
Duplicate of #14624 / https://bugzilla.mozilla.org/show_bug.cgi?id=1662830

**Closed** 2020-09-03 18:34 UTC
Labels: needs:triage, 🐞 bug
