### ISSUE TITLE
add save to pdf or base64 to Firefox for Android

### ISSUE THREAD

**Issue by 12sunflowers** [mozilla-mobile/fenix#26256] opened 2022-07-30 14:20 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Who will benefit from it?

add save to pdf or base64 to Firefox for Android

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21158)

**Comment by cadeyrn** [comment] 2022-07-30 19:28
Duplicate of #3709. They're already working on it.

**Comment by 12sunflowers** [comment] 2022-07-30 23:24
> Duplicate of #3709. They're already working on it.

Ok, thanks, and when its will be released?

**Comment by kbrosnan** [comment] 2022-07-31 05:02
Features generally will be available in the release builds 9-12 weeks after the feature is available in nightly. This has not landed yet on nightly so it is not possible to give an estimate at this time.

**Closed by kbrosnan** 2022-07-31 05:02 UTC
Labels: needs:triage
