### ISSUE TITLE
FNX-13134 ⁃ [Tab List] Tab tray should be opened like a real tray (with a swipe)

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#12111] opened 2020-06-29 22:34 UTC
### What is the user problem or growth opportunity you want to see solved?
The Tab list is displayed in a tray that behaves like a real tray... except when opening it: one must press the tab count icon, which is not a natural move in this case.
Also, there is no way to discover that one has to press on the tab icon to display the tab list tray.

### How do you know that this problem exists today? Why is this important?
Firstly, pressing that icon is not self a understanding gesture (no visible hint that the user has to do that), and secondly, the normal gesture for a tray is to open it in the same way it is handled later or closed, ie by a swiping move (bottom-up in this case.
Also, the closed tray could be displayed as a... closed tray, with a tiny visible line just above the URL bar, as it was the case for the page actions tray in the early days of Fenix. 

I suppose that all that has to be reversed when the URL bar is placed at the top of the screen.

### Who will benefit from it?
Every user would benefit of it, with a more discoverable and more natural way of opening the tab tray .

**Comment by person808** [comment] 2020-06-30 00:05
Duplicate of #11862.

**Closed** 2020-08-11 05:46 UTC
Labels: Feature:Tabs
