### ISSUE TITLE
color the address bar and status bar based on site

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17455] opened 2021-01-14 02:42 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
In chromium browsers for some sites the address bar, toolbar and status bar is tinted with the website color.. Not like vivaldi which color every site.. Can this feature be implemented in main browser window for light theme? 
You already have the feature in custom tabs and pwa so i dont see any difficulty to make it work in main browser 

### How do you know that this problem exists today? Why is this important?
The feature is present in all chromium browsers. In fact in fenix this works in custom tabs and pwa.. So there is no reason not to implement in main browser window 🙂

### Who will benefit from it?
All users 

Fenix custom tab

![Screenshot_20210114-080713551 (1)](https://user-images.githubusercontent.com/58127841/104537493-124f1380-5640-11eb-9a47-f38f96055484.jpg)

**Comment by Dunexus** [comment] 2021-01-14 09:20
Duplicate of https://github.com/mozilla-mobile/fenix/issues/1178

**Comment by LaurentiuApahideanSV** [comment] 2021-01-14 09:36
This is indeed a duplicate of https://github.com/mozilla-mobile/fenix/issues/1178. I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-01-14 09:36 UTC
Labels: needs:triage
