### ISSUE TITLE
[Bug] sending tabs from desktop to mobile can be lost easily

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#17062] opened 2020-12-16 01:30 UTC
While sending tab from fenix to desktop opens a new tab, sending tab from desktop to fenix just creates a notification.

1. Notifications can be accidentally cleared.
2. If I share 10 tabs I must tap 10 notifications.
3. For each notification I have to select an app to open it.

## Expected behaviour:
Tabs must open in fenix the same way they do on desktop.

**Comment by jonalmeida** [comment] 2020-12-16 05:43
Duplicate of https://github.com/mozilla-mobile/fenix/issues/12294

**Closed by jonalmeida** 2020-12-16 05:43 UTC
Labels: needs:triage, 🐞 bug
