### ISSUE TITLE
[Bug]about:config does not work

### ISSUE THREAD

**Issue by freebrowser1** [mozilla-mobile/fenix#12288] opened 2020-07-05 09:39 UTC
## Steps to reproduce
Use Fenix 5.2.0 and type about:config in the address bar.

### Expected behavior
The advanced settings should appear

### Actual behavior
An error message appears. The about:config is a very useful feature of firefox for e.g. setting a permanent user agent which shows a decent web page.
Currently Fenix only shows a WAP version of some websites as the word 'mobile' is in the user agent whch cannot be changed permanently. Only it can be done once by clicking on 'Show desktop version' which only works one time for one site.

### Device information
* Android device: MI Pro 8
* Fenix version: 5.2.0

**Comment by cadeyrn** [comment] 2020-07-05 09:43
This is not a bug but expected - about:config is only enabled on pre-release channels. But you say that you use Firefox Preview 5.2.0 - users of 5.2.0 were migrated to the Nightly channel and there *is* about:config enabled.

The issue is a duplicate of #7865 and others.

**Comment by freebrowser1** [comment] 2020-07-05 11:28
But, when Fenix is released, will it then be possible to access about:config, or at least change the user agent permanently to a normal 'desktop' one without 'mobile' in it, i.e. rendering a normal web page ?

**Comment by cadeyrn** [comment] 2020-07-05 11:31
> or at least change the user agent permanently to a normal 'desktop' one without 'mobile' in it, i.e. rendering a normal web page ?

This is #7039.

**Comment by nbmrjuhneibkr** [comment] 2020-07-28 16:20
Apparently, Mozilla thinks that users who want to have access to additional options such as UserAgent should only be using unstable builds of the browser. Want to have a stable build and additional customization? Can't have both, because Mozilla won't let you.
This is unacceptable.

**Comment by klint** [comment] 2020-08-05 14:37
> Apparently, Mozilla thinks that users who want to have access to additional options such as UserAgent switching should only be using unstable builds of the browser. Want to have a stable build and additional customization? Can't have both, because Mozilla won't let you.
> This is unacceptable.

Beta builds are pretty stable, on the contrary to nightly ones (and even those ones are ok on general) in my experience. And I've been using beta builds for years.

**Comment by kbrosnan** [comment] 2020-08-27 06:35
Closing as a duplicate

**Closed by kbrosnan** 2020-08-27 06:35 UTC
Labels: needs:triage, 🐞 bug

**Comment by Diapolo** [comment] 2020-09-23 10:23
This needs to be re-enabled ASAP, Firefox is currently unusable as power user!

**Comment by Diapolo** [comment] 2020-09-23 10:24
> > Apparently, Mozilla thinks that users who want to have access to additional options such as UserAgent switching should only be using unstable builds of the browser. Want to have a stable build and additional customization? Can't have both, because Mozilla won't let you.
> > This is unacceptable.
> 
> Beta builds are pretty stable, on the contrary to nightly ones (and even those ones are ok on general) in my experience. And I've been using beta builds as my main browser for years.

You / we should not be forced to use a Beta to be able to change advanced browser options, this is paternalistic!

**Comment by andreicristianpetcu** [comment] 2020-09-23 11:41
What sort of power user is afraid of beta? 😄
