### ISSUE TITLE
[Bug] Tabs are being saved/reloaded after closing application despite being set not to

### ISSUE THREAD

**Issue by ForrestHerman** [mozilla-mobile/fenix#14675] opened 2020-09-03 10:21 UTC
### Steps to reproduce
- Delete browsing data on quit: On
- Open tabs: Checked/On
### Expected behavior
After closing Firefox and opening a new instance no open tabs will be present
### Actual behavior
After closing Firefox and opening new instance all previous tabs are still present
### Device information

* Android device: 
-Model: Huawei Mate 10
-Build Number: 10.0.0.158
-Android Version: 10.0
-EMUI Version: 10.0.0
* Fenix version: 79.0.5

**Comment by cadeyrn** [comment] 2020-09-03 10:26
> After closing Firefox

How exactly do you close Firefox?

Is the issue still present in the current version, Firefox 80?

**Comment by ForrestHerman** [comment] 2020-09-03 11:41
> > After closing Firefox
> 
> How exactly do you close Firefox?
> 
> Is the issue still present in the current version, Firefox 80?

After updating to 80.1.2 the issue still exists.

Closing Firefox by pressing the Android Overview button and swiping up to close Firefox. This was the same method used prior to the upgrade to Fenix.

**Comment by DavidJCobb** [comment] 2020-09-03 14:49
This looks like a duplicate of #14662 (which itself looks to be a duplicate of two other issues).

**Comment by amkcpu** [comment] 2020-09-03 21:03
> Closing Firefox by pressing the Android Overview button and swiping up to close Firefox. This was the same method used prior to the upgrade to Fenix.

AFAIK, this only works when you tap the `Quit` button in the three-dot navigation menu to close the app.

If I am not mistaken, the problem with the previous implementation was that an Android app (at least prior to Android 11) does not know why it was removed from memory, it might be that the user closed it, or also because the user ran out of memory (RAM). This last situation can happen a lot on low-end devices and makes for a very bad user experience because you would constantly lose your open tabs even though you did not mean to close Firefox.

**Comment by buttercookie42** [comment] 2020-09-04 09:25
I'm not sure how reliable that is, but I think it is sort of possible to distinguish between OOM kills and the user swiping away the app in the task switcher by the virtue of the latter clearing the savedInstanceState data as well, i.e. if savedInstanceState data is present on startup assume you were OOM-killed and restore regardless, otherwise act according to the user preference regarding session restoring. (At least approximatively this is [what Fennec was doing](https://dxr.mozilla.org/mozilla-esr68/rev/6863f516ba386cfadfd2f60ac45411dc7a0850cf/mobile/android/base/java/org/mozilla/gecko/GeckoApp.java#1747-1774).)

**Comment by bcosell** [comment] 2020-09-04 23:28
_AFAIK, this only works when you tap the Quit button in the three-dot navigation menu to close the app._

But when you go to the bother of doing the three-dot 'qujt' it *doesn't* close the app -- all it does is all the cleanup and FF is still running... you then have to kill FF separately/

I understand the issue of "mysterious" removals from memory, but why isn't the choice about what to do when it is removed from memory left up to the user, instead of being hardwired in as "not clearing tabs"??

**Comment by liuche** [comment] 2020-09-10 00:52
I'm going to dupe this since that discussion is already happening. A different way of framing it could be "what is restored" on session restart (which also affects the state of the app if it gets unexpectedly killed in the background). The balance right now is erring on the side of not having data loss, but we'll revisit it.

**Closed by liuche** 2020-09-10 00:52 UTC
Labels: needs:triage, 🐞 bug
