### ISSUE TITLE
[Bug] Fullscreen videos force landscape orientation regardless of device orientation.

### ISSUE THREAD

**Issue by AndyMan1** [mozilla-mobile/fenix#19899] opened 2021-06-08 20:14 UTC
## Steps to reproduce

1. hold device vertically/portrait.
2. (optional) lock orientation to vertical/portrait (happens both with and without lock).
3. open any video (ex. Big Buck Bunny https://vimeo.com/1084537 )
4. press the fullscreen button to open the video fullscreen.
5. video opens in landscape orientation
6. rotate device horizontally and vertically to see the fullscreen video stays horizontal/landscape regardless of how the device is held.

### Expected behavior
The video should auto rotate to respect the current orientation the device is in. Especially when said orientation is locked. If I'm holding my device vertically/portrait, I want to view the video in that orientation. If I wanted to view the video horizontally/landscape, I would be holding it that way, or would rotate into that orientation. 

### Actual behavior
The browser forces the video to be horizontal/landscape, no matter how I hold the device or lock orientation.

### Device information

* Device vendor / model and Android version: Galaxy Tab A 8 w/ Android 10; Pixel 3A w/ Android 11
* Firefox for Android version: 89.1.1

**Comment by sflorean** [comment] 2021-06-09 05:14
Thank you for filing this! I will close this as duplicate of  #7602, but you scenario will be covered when a fix is landed.

**Closed by sflorean** 2021-06-09 05:14 UTC
Labels: needs:triage, 🐞 bug
