### ISSUE TITLE
[Bug] Search engines gone, and can't be readded

### ISSUE THREAD

**Issue by LinAGKar** [mozilla-mobile/fenix#13341] opened 2020-08-06 13:15 UTC
When Firefox was updated to Fenix, all the search engines I've added vanished. There also seems to be no good way to add them back, as you've deliberately broken Mycroft, and Fenix doesn't pick up search engines from web pages (the only search engines that show up under "Add search engine" seems to be a few blessed by Mozilla. The only way to add search engines is to manually add them using the URL, which in addition to needlessly making it more difficult, is suboptimal since it doesn't get an icon or search suggestions.

### Device information

* Android device: 9
* Fenix version: 79.0.2

**Comment by cadeyrn** [comment] 2020-08-06 17:28
> all the search engines I've added vanished

This is expected according to the official upgrade page in the knowledge base. Manually added Search engines has to be re-added. So it's not a bug.

> There also seems to be no good way to add them back

You can add every search engine you want. No, it't not an easy "one click and done" solution but it's possible and works. If you want an easier way to add search engines, you're probably talking about OpenSearch engines. Then it's a duplicate of #8889.

**Comment by liuche** [comment] 2020-08-07 20:59
Yes, caderyn is correct - you can still add any new search engines by adding the search url, but currently we don't have support for the OpenSearch standard.

**Closed by liuche** 2020-08-07 20:59 UTC
Labels: needs:triage, 🐞 bug
