### ISSUE TITLE
add "firefox preview" to selected text context menu

### ISSUE THREAD

**Issue by nahuhh** [mozilla-mobile/fenix#3612] opened 2019-06-23 10:32 UTC
Not sure if the same as #533
Title sounds the same but the conversation is confusing

### Why/User Benefit/User Problem
1. Selecting text from anywhere in the os
1. Context menu opens (copy paste etc) 
1. Within the context menu should be an entry for "Firefox preview"
1. Selecting firefox preview should open the selected text in Firefox preview. 
(Simply entered into the url bar of a new tab and followed.)

Currently I have to copy text, open preview and then paste it. 
I include links here because sometimes links aren't clickable
Like this: WalMart.com

Selecting "WalMart.com" and then choosing "Firefox preview" from the context menu should allow me to follow the link

**Comment by NotWoods** [comment] 2019-07-04 03:13
Similar Focus implementation: mozilla-mobile/focus-android#506

**Comment by ekager** [comment] 2019-07-04 03:23
Seems like a good idea! We would needs strings and which actions to add from UX/Product here

**Comment by lime124** [comment] 2019-07-26 04:11
hi @nahuhh ! if i'm understanding what you are requesting, i believe preview already does this...

STR
1. open keep and type a url (really any text box seemed to work
2. press and hold to select text
3. select browser from context menu

See screenshot: here the list shows Preview which you can select and then Preview will open and go to the URL.

![Screenshot_20190725-210106](https://user-images.githubusercontent.com/287322/61925326-b1e68680-af20-11e9-8708-b9584f980743.png)

If this works for you, could you please close the issue? If I've totally misunderstood what you are trying to say I'm really sorry. Could you please elaborate more on what the problem is?

Removing ux label until there is a further ask from my team. Thanks!

**Comment by nahuhh** [comment] 2019-07-26 10:30
No, that's not what I'm looking for. That is the stock Android implementation and only works for web links
 
Attached video
In the clip, "web search(google app), private search (ff focus),  translate (Google), open with (open link with app)"and more 3rd party apps are available. Firefox preview is not (but should be)

![20190726_062141](https://user-images.githubusercontent.com/50635951/61945646-838f9800-af6e-11e9-99c9-44c38580351d.gif)

**Comment by NotWoods** [comment] 2019-07-26 14:29
UX team: We would appreciate designs for what the text displayed in the popup should be. (ie: "Search in Firefox Preview", "Search", "Open in Firefox", etc)

**Comment by lime124** [comment] 2019-07-26 18:25
thanks notwoods for a clear ask and thanks nahuhh for providing the additional information. passing to @mheubusch for the string recommendation.

**Comment by lime124** [comment] 2019-10-02 20:31
I believe this is related to #5695 . @boek did we say the scope of the other ticket was for the whole OS or just limited to Fenix?

**Comment by jpfaller** [comment] 2019-10-09 18:40
See #5695 and #5696

**Comment by vesta0** [comment] 2019-10-09 18:59
This will be addressed in the bugs mentioned above!

**Closed** 2020-08-27 00:41 UTC
Labels: feature request 🌟
