### ISSUE TITLE
Memory usage jumps with one website and rendering stops

### ISSUE THREAD

**Issue by roaima** [mozilla-mobile/fenix#26554] opened 2022-08-19 16:30 UTC
## Steps to reproduce

1. Go to https theguardian.com/uk, an English language newspaper website with multiple clickable headlines. _I have not been able to reproduce the problem on any other website_.
4. Long press any headline or article to open it in a new tab.
5. Repeat by opening three more headlines or articles, each in a new tab.
6. Firefox will stop responding for (at best) a minute or two.

### Expected behavior

1. The page should allow me to continue selecting items for opening in new tabs, so that I have a set of pages ready to read.
2. When I review these other pages in their respective tabs, rendering should be near instantaneous exactly as usual.

### Actual behavior

- Firefox stops accepting long press - or indeed any press. On a good day I can scroll up and down the part of the page that has already been rendered, but unrendered visuals "below the visible page" will not be rendered and I end up scrolling a blank page.
- New tabs and those I might have had open before this test will not render - I get a blank page for each.
- After a minute or so, Firefox might start to respond again, sluggishly recognising some earlier presses, but rendering is gone.

The workaround is to press Home on the Android device and swipe out Firefox. Wait a minute. Restart Firefox. At this point rendering will work fine again until I open more than two or three tabs from this particular website.

Looking in the phone's Settings / System / Developer options / Memory, I see that during this event Firefox memory usage has suddenly escalated from around 500MB way up to multiple GB - often near the limit of the phone. This can cause even the phone's app launcher to struggle to run.

### Device information

* Android device: OnePlus 5T (Android 10) with 8GB RAM
* Fenix version: ?

* Firefox 103.2.0 (Build #2015895963)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21341)

**Comment by LaurentiuApahideanSV** [comment] 2022-08-22 13:22
I can confirm  the issue is reproducible on Firefox Nightly 105.0a1 2022-08-21.
### Device used:
- OnePlus 6T (Android 9)

**Comment by mcomella** [comment] 2022-08-24 22:00
Triage: thanks for reporting! @LaurentiuApahideanSV, since you can reproduce, would you be able to answer a few questions for us?
1. Are you able to reproduce the issue in chrome?
2. Could you grab a performance profile so we can better understand the root cause? https://profiler.firefox.com/docs/#/./guide-profiling-android-directly-on-device

**Comment by LaurentiuApahideanSV** [comment] 2022-08-25 09:20
I tested the issue on Chrome and it does not occur, I was able to open many tabs without issues. The issue is still reproducible on Nightly 106.0a1 (2022-08-25). Here are the performance profiles: https://profiler.firefox.com/public/7qqacntbqznkn9ppx87k435rttkq44vvzn72ye8

**Comment by mcomella** [comment] 2022-08-31 21:20
Triage: we suspect the root cause is a platform issue because, in the first profile, there are large jank markers in the child process w/ near 100% CPU use over 30 seconds and we see a lengthy GC calls when the original reporter mentioned unexpectedly high memory usage. By contrast, the JVM profile has nothing out of the ordinary.

Since this is a platform issue, we'll track this on Bugzilla and close this GitHub issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1788530 Thank you for filing!

**Closed by mcomella** 2022-08-31 21:20 UTC
Labels: performance, needs:triage, qa-triaged
