### ISSUE TITLE
[Bug] Buy in YouTube Music not visible

### ISSUE THREAD

**Issue by liubomirwm** [mozilla-mobile/fenix#7802] opened 2020-01-18 19:54 UTC
## Steps to reproduce
Use Bulgarian language (not sure if it will reproduce in English).
1. Open YouTube Music app and select to buy student subscription. When you buy student subscription it will ask to open sheerId site where you will be checked to be a student. This opens as a WebView (don't know how it is called, but not the full Firefox Preview browser) . After confirmation you are redirected back to YouTube Music to pay. _The goal is really to open the YouTube Music payment page in the Firefox WebView, not Firefox Preview full browser._ If you can do this i don't think you would need to go through student buying and SheerId.
2. if you have an already entered card and try to pay, you enter your card security code, and the Blue buy button cannot be seen, unless you choose "open with Firefox Preview" from the menu.

### Expected behavior
The Blue "finish payment" button should be visible and not below the name if the opened page (bottom bar of Firefox WebView). The photo attached is from Firefox Preview full browser, so you can get the idea what button it is.

![image](https://user-images.githubusercontent.com/16529989/72669592-6aa70180-3a3c-11ea-949e-906c23f9ffe7.png)
This blue button above is visible both when opened via Firefox Preview and Firefox WebView
### Actual behavior
The blue button is not visible when openen in Firefox WebView, it stays below the bottom bar with the site name/title. I didn't take a screenshot of it but couldn't get it to scroll so the button is visible.

### Device information

* Android device: Motorola One Macro
* Fenix version: 3.0.2 Build #20081833

**Comment by ekager** [comment] 2020-04-17 21:53
Sounds like a custom tab toolbar issue. I'm assuming this has been fixed now 🤔

**Comment by AndiAJ** [comment] 2020-04-22 10:19
Hi, I'll mark this issue **verified as fixed** as I couldn't reproduce it on the latest **`Nightly Build #21130610 from 4/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

►Video
![20200422-130813](https://user-images.githubusercontent.com/51314259/79970503-b1712100-849b-11ea-8839-888490247785.gif)

@liubomirwm - I case you still encounter the issue please re-open. ☺️

**Closed by AndiAJ** 2020-04-22 10:19 UTC
Labels: eng:qa:needed, needs:triage, 🐞 bug
