### ISSUE TITLE
Make it easier to close a tab by swiping a lesser distance in the tab manager

### ISSUE THREAD

**Issue by smartfonreddit** [mozilla-mobile/fenix#3746] opened 2019-06-28 02:19 UTC
### Why/User Benefit/User Problem

After heavily using the browser for multitasking, I came to the conclusion that closing tabs is too annoying. Most of the time I fail to close the tab from the first attempt, while doing what I would consider as a normal-sized finger swing, because the finger doesn't always slide 70% of the horizontal screen width. The single-tap close "X" button in the corner isn't always practical to use.

### What/Requirements

Close the tab when it's swiped at 25% of the width, or implement easier shortcuts to close the tab.

Because closing a tab prompts the user to undo it, it's OK to be less forgiving and close the tab easier. That is how it used to work few weeks ago until something was changed in the recent builds.

**Comment by kbrosnan** [comment] 2019-06-28 02:28
Dupe of #3738

**Closed by kbrosnan** 2019-06-28 02:28 UTC
Labels: 🌟 feature request

**Comment by openjck** [comment] 2019-07-26 19:15
I'm not sure if #3738 is a strict duplicate. It seems to be talking about tab management workflows in general. I think it's worth focusing on swipe distance in particular. It's too hard to close tabs via swipe.
