### ISSUE TITLE
FNX-3273 ⁃ [Bug] The cursor jumps around while trying to select the text, same as bug #8072

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10076] opened 2020-04-21 05:11 UTC
#8072, I misclassified it as a [webcontent] issue but I think It's a bug. Can you please take a look?

**Comment by sflorean** [comment] 2020-04-23 13:48
dupe of #8072

**Closed** 2020-08-10 18:40 UTC
Labels: needs:triage, 🐞 bug
