### ISSUE TITLE
[Bug] "Tabs sent!" snackbar is displayed under the tabs tray overlay

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#15077] opened 2020-09-14 13:11 UTC
## Prerequisites
 Sign in with a Firefox account that has more than 1 device connected.

## Steps to reproduce
1. Open 3-4 tabs.
2. Open tabs tray.
3. Tap on the three-dot menu -> Share all tabs.
4. Tap on one of the devices connected from the "Send to device" section.

### Expected behavior
The "Tabs sent!" snackbar is displayed over the tabs tray overlay.

### Actual behavior
The "Tabs sent!" snackbar is displayed under the tabs tray overlay, and it is visible only if the tabs tray is closed quickly.

### Device information
* Android device:  Xiaomi Mi Pad 2 (Android 5.1), Samsung Galaxy Note 10 (Android 10)
* Fenix version: 81.1.1-beta.4, Nightly 9/14.

**Comment by Mugurell** [comment] 2020-10-13 11:52
Currently the snackbar is placed on top of the bottom toolbar or at the bottom of the screen when the toolbar is placed at top.
And then the tabs tray shown in front of the browser and toolbar.

We could maybe play with the Z index to make the snackbar appear over the tabs tray but there's also the fab which would cause other issues. Even with the snackbar on top of the toolbar it's baseline would be below that of the fab so they would clip each other.
![image](https://user-images.githubusercontent.com/11428869/95856695-19296a00-0d63-11eb-8381-79e2e5df4c1d.png)

Asking UX how it all should look / work. Simplest solution would be to dismiss the tabs tray when the user presses the share button.

**Comment by topotropic** [comment] 2020-10-15 18:08
I don't see a snackbar at all, weird. Could we re-use what we have when you close a tab on the tab tray? It shows the snackbar above the floating action button.

**Comment by Mugurell** [comment] 2020-10-19 18:59
> I don't see a snackbar at all, weird. Could we re-use what we have when you close a tab on the tab tray? It shows the snackbar above the floating action button.

To see the snackbar you have to close the tabs tray immediately after sharing to a device (before the snackbar would be automatically dismissed). The snackbar is shown on top of the parent activity, behind tabs tray which is a dialog shown on top of the activity.

Looked into this a bit, I don't think it will be reasonable possible to show "share snackbar" on top of tabs tray.
The "Tab closed" snackbar appears on top of tabs tray because it is shown from tabs tray and we can set that to be the layout in which the snackbar will be shown.
But to allow sharing tabs we navigate the user to the ShareFragment which then shows a snackbar without knowing about tabs tray, without having the possibility of attaching the snackbar to the tabs tray layout.
To be able to show that snackbar here I think we'd need to duplicate much of the code from the ShareFragment so the only feasible solution I think is closing the tabs tray when we navigate the user to ShareFragment.

Asking @ekager for a second opinion.

**Comment by topotropic** [comment] 2021-01-08 16:42
Ok, that makes sense! From a consistency point of view it would be great to keep the tab tray open because this is what happens when you use other actions like "close" or "add to collection" on the tab tray. 

Is it possible at all to detect the underlying tab tray (behind the share sheet)? And if yes, how much work would it be to display the snackbar there? Thanks!

**Comment by Mugurell** [comment] 2021-02-03 18:35
@topotropic With the current implementation I'd say it's not possible. They are different screens that don't know one about the other.

**Comment by Mugurell** [comment] 2021-06-04 14:42
Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/19182.

**Closed by Mugurell** 2021-06-04 14:42 UTC
Labels: Feature:Snackbar, Feature:Tabs, S2, needs:UX-feedback, 🐞 bug
