### ISSUE TITLE
Prevent malicious redirects; when redirects happen, provide an easy way to access history

### ISSUE THREAD

**Issue by Shaurya-Kalia** [mozilla-mobile/fenix#8083] opened 2020-02-04 18:36 UTC
### Why/User Benefit/User Problem
Currently firefox stable has back forward buttons that can be long pressed to see the sites visited in that current tab and get to them directly, rather than repeatedly pressing back. It is also useful in some (shady) sites that redirect back to a page when just back is pressed 

### What/Requirements
A back button in addition to forward button that can be long pressed

### Acceptance Criteria (how do I know when I’m done?)
Long pressing a back button shows the history for the particular tab and clicking on an entry directly takes to it

### Summary of issue

- Fenix UX team wanted to reduce overcrowding of the menu toolbar. Because of that, they’re deferring to the use of system back button whenever possible.
- @danielzgtg expanded OP’s initial point on https://github.com/mozilla-mobile/fenix/issues/5905#issuecomment-590017252. Quote:
    > “…when a malicious ad is loaded and sends me to pages that use scripts to spam the back stack to crowd out the site I wanted to stay on. [In this case…] Using the device back button is not a solution […] The only way to get out of this situation is to […] scroll down to the last good website, and tap there.
- Fenix UX team notes the fact that users can already access the “History” page in the main menu

### How might we

- Prevent malicious redirects in the first place?
- In case malicious redirects are unavoidable, can we make it obvious and easy to access history?

Note that we specifically didn’t write “the browser needs a long-press back button”, because we don’t want to prescribe a solution in the design process. There can be multiple ways to solve this problem and get the same outcome

**Comment by cadeyrn** [comment] 2020-02-04 20:43
Duplicate of #6559.

**Comment by brampitoyo** [comment] 2020-02-23 23:52
Summary of issue up to this point:

**Comment by danielzgtg** [comment] 2020-02-24 00:31
@brampitoyo Thank you for further considering this issue.

https://github.com/mozilla-mobile/fenix/issues/5905#issuecomment-590131979

> Also note that History is a page that’s already easy to access from the main menu. With it, you can go back several pages into the stack (although the history presented is of all tabs, not just for any specific tab).

This does not work in private browsing, whereas long-press back did work there.

> Note that the final design may not be in the form of a long-press back button, but it will solve your malicious redirect problem.

Old Firefox also had long-press forward in addition to the long-press back. Fenix currently has neither but still has a forward button. How about we make long-press forward show both forward and back tab history?

**Comment by kbrosnan** [comment] 2020-02-24 01:36
Showing history on long press on back button is #1048

**Closed by kbrosnan** 2020-02-24 01:36 UTC
Labels: Feature:MainMenu, b:navigation, 🌟 feature request

**Comment by Poopooracoocoo** [comment] 2020-03-31 04:35
Chrome has a flag called history manipulation intervention. I thought Firefox already had this by default, done and dusted.
