### ISSUE TITLE
[Bug]: Account settings' "Device name" field only shows the prefix of long device names

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#23184] opened 2022-01-13 19:51 UTC
### Steps to reproduce

1. Open the Account settings menu.
2. Make sure you are signed into FxA Sync.
3. Tap your Device name to edit it.
4. Enter new device name long enough that it word wraps in the editor dialog.
5. Tap OK to accept the new device name.

### Expected behaviour

The full device name, `Firefox Nightly on Samsung Galaxy A32`, should be visible.

### Actual behaviour

Only the prefix `Firefox Nightly on Samsung Galaxy` of the full device name `Firefox Nightly on Samsung Galaxy A32` is visible.

### Device name

Samsung Galaxy A32

### Android version

11

### Firefox release type

Firefox Nightly

### Firefox version

98

**Comment by kbrosnan** [comment] 2022-01-13 21:40
Duplicate of https://github.com/mozilla-mobile/fenix/issues/5833

**Closed by kbrosnan** 2022-01-13 21:40 UTC
Labels: 🐞 bug, needs:triage
