### ISSUE TITLE
FNX-5001 ⁃ When Battery Saver mode changes, the app crashes

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#1399] opened 2019-04-05 00:56 UTC
## STR
1. Change theme option to 'Set by Battery Saver'.
1. Enable Battery Saver mode (from the Quick Settings).
1. Observe the crash.

https://sentry.prod.mozaws.net/operations/fenix/issues/5486466/

```
NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.app.ActivityThread.getLooper()' on a null object reference
    at android.app.Activity.recreate(Activity.java:5584)
    at androidx.core.app.ActivityCompat.recreate(ActivityCompat.java:2)
    at androidx.appcompat.app.AppCompatDelegateImpl.applyDayNight(AppCompatDelegateImpl.java:30)
    at androidx.appcompat.app.AppCompatDelegateImpl.attachBaseContext(AppCompatDelegateImpl.java:1)
    at androidx.appcompat.app.AppCompatActivity.attachBaseContext(AppCompatActivity.java:2)
...
(15 additional frame(s) were not displayed)

RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.app.ActivityThread.getLooper()' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
    at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4823)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4732)
    at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
...
(9 additional frame(s) were not displayed)

Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.app.ActivityThread.getLooper()' on a null object reference
```

**Comment by jonalmeida** [comment] 2019-04-05 00:59
cc: @ekager since it looks like it's still being worked on and this bug might already be addressed in any currently open PRs.

**Comment by ekager** [comment] 2019-04-05 02:47
Thanks for the cc! 

I dug a little deeper and there's a note in the docs under [`MODE_NIGHT_AUTO_BATTERY`](https://developer.android.com/reference/androidx/appcompat/app/AppCompatDelegate.html#MODE_NIGHT_AUTO_BATTERY)

> Please note: this mode should only be used when running on devices which do not provide a similar device-wide setting.

I think because Pixels (and other phone's on P+ maybe?) automatically change the system mode to dark on battery saver mode anyway we should remove the battery saver option because "follow system" is doing the same thing (and I think this is related to the crash). If anyone has insight into which devices should have this setting, please let me know.

**Comment by bsurd** [comment] 2019-04-09 10:48
Tested on 6 different devices but I was not able to reproduce the initial crash on older builds so I can't really confirm if this is fixed or not. @jonalmeida could you confirm this on your device.

I did encounter a different issue while testing and logged #1484 for it. Devices used are also mentioned there.

**Comment by ekager** [comment] 2019-04-09 19:56
Going to close this since you weren't able to reproduce.

**Comment by jonalmeida** [comment] 2019-04-09 20:10
> Going to close this since you weren't able to reproduce.

Yes, this isn't reproducible any more since the option is gone away from the UI.

**Closed** 2020-08-11 11:33 UTC
Labels: 🐞 bug
