### ISSUE TITLE
[Bug] Entire viewport goes white when scrolling quickly on Twitter (menu, navbar and post icons disappear)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#9170] opened 2020-03-16 05:29 UTC
## Steps to reproduce

1. Navigate to twitter.com
2. Login
3. Scroll down quickly

### Expected behavior

The Home / Latest Tweets header, navbar, and feather post icon should remain sticky on the screen while scrolling posts into view.

### Actual behavior

The header, navbar and post icons disappear, leaving behind an entirely white screen while scrolling.

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

See video: [signal-attachment-2020-03-16-012500.zip](https://github.com/mozilla-mobile/fenix/files/4336204/signal-attachment-2020-03-16-012500.zip)

**Comment by sv-sdeiac** [comment] 2020-03-17 08:11
Hello, I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly  3/17 #20770605.

Devices:
- LG g7 fit (Android 8);
- Samsung Galaxy Tab S6 (Android 9);
- Google Pixel 3 (Android Q).

**Comment by yoasif** [comment] 2020-09-14 06:43
Seeing this in reference browser as well, so filed to https://bugzilla.mozilla.org/show_bug.cgi?id=1664743

**Comment by ekager** [comment] 2020-12-17 19:07
@yoasif are you still seeing this? The Bugzilla was duped and then closed out so I'm going to close this for now

**Closed by ekager** 2020-12-17 19:07 UTC
Labels: Feature:Browsing, S2, needs:triage, 🐞 bug
