### ISSUE TITLE
[Bug] Cannot open some search suggestions in Private Browsing mode

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#2993] opened 2019-05-30 00:45 UTC
## Steps to reproduce
* Open a tab in private browsing mode
* Try to select a suggestion (site that has previously been visited)

### Expected behavior
* The tab would open

### Actual behavior
* Selection does nothing and I cannot open a tab with that suggestion. In my case it is not opening suggestions of previously loaded sites, but will open suggestions of sites (or searches) I haven't yet visited

### Device information
* Android device: Pixel 3
* Fenix version: 1.01922 (Build #11491818)

**Comment by vesta0** [comment] 2019-05-30 22:15
I can't reproduce this. @mozillamarcia could you provide exact steps to reproduce?

**Comment by vesta0** [comment] 2019-06-04 22:11
Closing for now. @mozillamarcia please re-open if you can still reproduce this.

**Comment by softvision-miralobontiu** [comment] 2020-03-11 11:46
Cannot reproduce this issue on the latest Nightly build from 03/11 with Xiaomi Redmi Note 8T (Android 9).
Removing the needs:STR label.

**Closed** 2020-08-26 20:38 UTC
Labels: 🐞 bug
