### ISSUE TITLE
[Bug]: "Scroll to hide toolbar" option adds gap in PWA/TWA

### ISSUE THREAD

**Issue by adil192** [mozilla-mobile/fenix#25239] opened 2022-05-14 13:45 UTC
### Steps to reproduce

1. In Firefox Settings > Customise:
    - Set Toolbar to Top (the bug doesn't happen with a bottom toolbar)
    - Set "Scroll to hide toolbar" to false/off
2. Install a PWA through firefox. The one I'm using is https://adil.hanney.org/nonogram/
3. Open the PWA and see the top gap where the toolbar would usually be.

<img src="https://user-images.githubusercontent.com/21128619/168428429-720cbb86-2b47-4d86-b6c9-704ae38cdcd2.png" width="200" />

### Expected behaviour

There should be no gap like this:

<img src="https://user-images.githubusercontent.com/21128619/168428376-c5dc187b-825b-4504-b33d-8dceedfbe7dd.png" width="200" />

(Screenshot was taken with "Scroll to hide toolbar" set to true/on)

### Actual behaviour

Large gap at the top of the screen where the toolbar usually is (normal browser screenshot for reference)

<img src="https://user-images.githubusercontent.com/21128619/168428364-4dc527fc-d77b-4832-a7fb-90d8d22489f1.png" width="200" /> <img src="https://user-images.githubusercontent.com/21128619/168428608-97920201-7cee-42a4-bf45-af166caed782.png" width="200" />

### Device name

Google Pixel 6

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

100.1.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20459)

**Comment by marcel263** [comment] 2022-05-14 17:58
Dear,

this report is likely duplicate of  #19972 yes?

**Comment by adil192** [comment] 2022-05-14 18:19
> this report is likely duplicate of #19972 yes?

Yes, sorry, I couldn't find a similar issue before posting

**Comment by Mugurell** [comment] 2022-05-16 11:49
Thank you both. Closing this as duplicate in favor of https://github.com/mozilla-mobile/fenix/issues/19972.

**Closed by Mugurell** 2022-05-16 11:49 UTC
Labels: 🐞 bug, needs:triage
