### ISSUE TITLE
[Bug]Snackbars are not displayed right above URL bar

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#8773] opened 2020-02-26 15:46 UTC
## Steps to reproduce
1. Open app and tap on youtube.com site.
2. Long tap on the URL bar.
3. Tap on "Copy". 
### Expected behavior
Snackbar is displayed right above URL bar.
### Actual behavior
Snackbar is displayed more higher than right above URL bar
### Device information

* Android device: OnePlus 6T(Android 9), Samsung Galaxy S9 (Android 8.0.0) and Sony Xperia Z5 (Android 7.0.0)
* Fenix version: Firefox Preview Nightly 200226 (Build #20570604) GV:75.0a1-20200225094028

Notes:
- Affected snackbars:
   - Browsing data deleted
   - Add to Top Site
   - Bookmark saved
   - URL copied to clipboard
- Firefox Nightly Build dated Tuesday 02/25 displays the snackbars correctly.
- Please check GIF:
![20200226-173154](https://user-images.githubusercontent.com/49859863/75361161-8dd89280-58bf-11ea-87a1-370b0f9e204b.gif)

**Comment by Diana-Rus** [comment] 2020-02-26 16:36
It may have come with the new feature - Dynamic bottom toolbar: https://github.com/mozilla-mobile/fenix/issues/4383

**Comment by sv-sdeiac** [comment] 2020-03-02 09:07
Verified as fixed using the latest version of Firefox Preview Nightly 3/2 #20620607.

Devices:
- Motorola Moto G6 (Android 8);
- Samsung Galaxy Note 8 (Android 9).

**Comment by softvision-miralobontiu** [comment] 2020-03-03 13:46
I will re-open the issue due to the fact I encountered 2 more snackbars wrongly displayed:
- "New tab opened Switch", and 
- "New private tab opened Switch". 

Tested on the 3/3 Nightly build with Samsung Galaxy Note 8 (Android 9), HTC 10 (Android 8), and Huawei P9 Lite (Android 7).

![Screenshot_20200303-153757_Firefox Nightly](https://user-images.githubusercontent.com/40694158/75781396-bea84400-5d65-11ea-9da9-05c2cc681d5b.jpg)

**Comment by sblatz** [comment] 2020-03-03 17:32
I'm working on a fix for this!

**Comment by AndiAJ** [comment] 2020-03-04 08:46
Add-ons confirmation snackbars are also improperly displayed on both **`Nightly #20640607 from 3/4`** and **`Beta 4.0.0-beta.3`** using a OnePlus A3 (Android 6.0.1)

**Comment by AndiAJ** [comment] 2020-03-17 12:07
Hi, as per the above mentioned comments, I've just checked this matter on the latest **`Nightly Build #20770606 from 3/17`** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

| Satus  | Ssnackbar|
| ------------- | ------------- |
| ✔️ |  "URL copied to clipboard" |
| ✔️ |  "Added to top sites" |
| ✔️ |  "Bookmark saved" |
| ✔️ | "Deleted the bookmark" |
| ✔️ | "Deleting browsing data" (On quit) |
| ✔️ | "Browsing data deleted" |
| ❌ | "Successfully installed uBlock" |
| ❌ | "Successfully uninstalled uBlock" |

►Video
![20200317-132837](https://user-images.githubusercontent.com/51314259/76854539-f03a0880-6857-11ea-8f57-e2be0d3119ba.gif)

As most of the snackbars are properly displayed, **I'll go ahead and mark this issue as fixed**.
@sblatz  - For the install/uninstall uBlock snackbar matter I've opened a new issue #9196 ☺️

**Closed by AndiAJ** 2020-03-17 12:07 UTC
Labels: Feature:NavBar, S2, eng:qa:needed, needs:triage, 🐞 bug

**Comment by bubi-luka** [comment] 2020-03-28 18:40
In the current all of the snackbars I have tried are positioned with too much space above the bottom URL bar. Regression?

- Android device: Huawei p20 lite, Android 9, EMUI 9.1
- Fenix version: Nightly 200328 6:01 (Build #20880607
