### ISSUE TITLE
FNX-5189 ⁃ [Bug] Suggestions aren't visible in landscape mode

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#1692] opened 2019-04-17 11:39 UTC
## Steps to reproduce
1. Go to Fenix on landscape mode and type something in the search bar.

### Expected behavior
The user should see the suggestions.

### Actual behavior
The user cannot see the suggestions.

### Device information
* Android device: Nokia 6 (Android 7.0)
* Fenix version: 1.0.1916 (Build #11061212) 

![2019](https://user-images.githubusercontent.com/40694158/56284616-aa436480-611d-11e9-9bf6-efffc760395c.gif)UNITO-UNDERSCORE!04!UNITO-UNDERSCORE!17!UNITO-UNDERSCORE!14!UNITO-UNDERSCORE!26!UNITO-UNDERSCORE!39!

**Comment by sv-ohorvath** [comment] 2019-04-18 11:45
Dupe of #1304.

**Closed** 2020-08-11 12:30 UTC
