### ISSUE TITLE
Add option to enable desktop mode by default

### ISSUE THREAD

**Issue by grmblgrmbl** [mozilla-mobile/fenix#26576] opened 2022-08-22 10:42 UTC
A tablet in landscape mode, with keyboard and mouse, is much closer to a desktop/laptop computer, and typical mobile layouts do not fit these well as opposed to smaller, lower resolution, portrait smartphones. I'd like the option to enable desktop mode by default, because enabling desktop mode is often the first thing I do, and it does not stay reliably in this mode.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21352)

**Comment by cadeyrn** [comment] 2022-08-22 10:59
Duplicate of #7039.

**Closed** 2022-08-22 14:08 UTC
Labels: needs:triage
