### ISSUE TITLE
App-links: Add a context menu option to open the current page in an external app.

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/fenix#3338] opened 2019-06-11 12:16 UTC
This is the fenix part of #3330.

The a-c part is [ac#3370][1].

[1]: https://github.com/mozilla-mobile/android-components/issues/3370

**Comment by Djfe** [comment] 2019-08-07 08:04
seems to be implemented and both issues are closed

**Comment by NotWoods** [comment] 2019-12-23 07:52
Duplicate of #1754

**Closed** 2020-08-26 23:16 UTC
Labels: feature request 🌟
