### ISSUE TITLE
White url bar placeholder seen at bottom while panning with top toolbar.

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#14821] opened 2020-09-07 14:01 UTC
## Steps to reproduce
- have Fenix use the toolbar at top
- first time access `thetimes.co.uk` so that the cookies consent dialog is shown
- scroll or zoom in/out on that dialog
- [Video](https://drive.google.com/file/d/1pMzYh-_4nyn9KFeScZ-3g4ibyoOkeXgD/view?usp=sharing)

### Expected behavior
No visual artifacts.

### Actual behavior
White area shown at bottom where the bottom toolbar would be.

### Device information
* Fenix version: Happening on Fenix release (GV 80.0.1) and on Fenix Nightly (GV 82)

### GV tracking
https://bugzilla.mozilla.org/show_bug.cgi?id=1663444

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6524)

**Comment by liuche** [comment] 2020-09-18 01:12
@Mugurell the GV team recommends trying on Fenix to make the top toolbar "fixed" in position. The belief is that this bug is not specific to iframes but really with how the top toolbar is rendered.

**Comment by JCown** [comment] 2020-11-24 15:12
Can confirm this issue, please check this website as a living example: https://www.receptagemini.pl/
Turning off the option "hide toolbar on scroll" (in the same view when you can choose whether the toolbar should be pinned to the top or to the bottom) fixes this issue so it's probably related to that dynamic toolbar.
Also another issue is realted to zooming, after zooming you cannot really zoom out to "default" view (turning off option mentioned above also fixes this issue)

**Comment by michal1315** [comment] 2020-12-18 14:23
This issue was not fixed from a months, first time i saw it in preview phase. So i'm start thinking that people who make Firefox for Android don't use this browser as its daily browser. It's really sad.

**Comment by michal1315** [comment] 2020-12-18 14:24
![IMG_20201218_142944](https://user-images.githubusercontent.com/35575000/102624942-09544a80-4145-11eb-9932-10889fb5c0fa.jpg)
![IMG_20201218_143008](https://user-images.githubusercontent.com/35575000/102624970-11ac8580-4145-11eb-8972-6d91dbb94630.jpg)

**Comment by flashcode** [comment] 2020-12-18 14:37
I opened a similar issue (#15021) which has been closed as duplicate of this one.

I can confirm that if in Settings > Customize I uncheck the option "Scroll to hide toolbar", this works fine.

**Comment by michal1315** [comment] 2020-12-18 15:49
Yaa man but it's not a solution, its work correct in any other browser, even in Firefox focus which like fenix base on geckoview.
![Screenrecorder-2020-12-18-16-36-42-505(0)](https://user-images.githubusercontent.com/35575000/102633632-f778a480-4150-11eb-91d4-adfb1a7c8dbe.gif)

**Comment by Mugurell** [comment] 2021-02-17 18:59
For the issue seen on Reddit - placeholder shown for an animated toolbar while the page loads,
I think what Sorina proposed here - https://github.com/mozilla-mobile/fenix/issues/10200 would fix this.
Asking UX if we should implement this - not animate the toolbars if the page is loading.

**Comment by Mugurell** [comment] 2021-02-17 19:01
The issue seen on `thetimes` seems a bit similar to https://github.com/mozilla-mobile/fenix/issues/16298

**Comment by Mugurell** [comment] 2021-02-17 19:05
I think the issue with the fullscreen image from https://github.com/mozilla-mobile/fenix/issues/14821#issuecomment-748168249 is fixed in the current Nightly.
But now there's the pull to refresh that is triggered.

**Comment by jsphslgr** [comment] 2021-06-10 21:07
The issue from #19552 can be consistently triggered when visiting a Wikipedia entry, scrolling down a short ways, and tapping a footnote. If "scroll to hide toolbar" is turned off the problem goes away.

**Comment by Mugurell** [comment] 2021-12-08 07:38
Still an issue.
Added a link to this on Bugzilla - https://bugzilla.mozilla.org/show_bug.cgi?id=1694607

**Comment by fice-t** [comment] 2022-10-06 05:27
@Mugurell I can't seem to reproduce this on the current nightly.

**Comment by Mugurell** [comment] 2022-10-06 06:00
> @Mugurell I can't seem to reproduce this on the current nightly.

Thank you for updating.
If you are referring to the issue reported for `thetimes.co.uk` it may be that that website's design changed over time and just avoids the buggy functionality.
Testing now I still see the issue reported for wikipedia here - https://github.com/mozilla-mobile/fenix/issues/14821#issuecomment-859068904 and the GeckoView ticket is still open - https://bugzilla.mozilla.org/show_bug.cgi?id=1663634 so unfortunately this is still an issue. But it's nice if there are fewer websites on which it is encountered.

**Comment by gabrielluong** [comment] 2023-01-30 23:33
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813879

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by gabrielluong** 2023-01-30 23:33 UTC
Labels: 🐞 bug, 🙅 waiting, needs:UX-feedback, needs:gv, Feature:Toolbar
