### ISSUE TITLE
[Bug]: can't change to dark theme

### ISSUE THREAD

**Issue by walkerxk** [mozilla-mobile/fenix#23104] opened 2022-01-07 05:33 UTC
### Steps to reproduce

1.change theme to dark
2.back to homepage
3.view the setting in the theme, it go back to "follow device theme"

### Expected behaviour

still dark theme

### Actual behaviour

go back to "follow device theme"

### Device name

redmi K30 Pro

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1

### Device logs

https://crash-stats.mozilla.org/report/index/3992658c-8891-449b-a838-e254a0211102

**Comment by walkerxk** [comment] 2022-01-07 05:38
i have record a screenshot of this
https://www.youtube.com/watch?v=IiOazvfbTys

**Comment by mcarare** [comment] 2022-01-07 09:56
This is caused by https://github.com/mozilla-mobile/fenix/pull/22941
Not sure the behavior was intended or not. Maybe this should be evaluated by UX (what settings takes precedence: theme or wallpaper) 
cc: @Amejia481

**Comment by 06000208** [comment] 2022-01-07 14:31
This has made it impossible to use firefox's dark theme on some phones, as not all phones have the ability to control whether a wallpaper is considered light or dark, and the default is light.

I don't think it's a matter of what settings take precedence, because there is no apparent wallpaper settings in firefox, this is always on, and the user's theme setting is always disregarded in favor of matching the wallpaper. Meaning it may not be possible to manually change the theme at all?

**Comment by Amejia481** [comment] 2022-01-07 14:40
> This is caused by #22941 Not sure the behavior was intended or not. Maybe this should be evaluated by UX (what settings takes precedence: theme or wallpaper) cc: @Amejia481

Thanks for tagging me. I'm taking a look!

**Comment by Amejia481** [comment] 2022-01-07 14:45
> s not all phones have the ability to control whether a wallpaper is considered light or dark, and the default is light.

We are developing the feature and it's only active on nightly, you can switch between wallpapers  by tapping on the Firefox logo, the setting page is a work in progress  https://github.com/mozilla-mobile/fenix/pull/22953

**Comment by notJerl** [comment] 2022-01-09 01:13
I feel like pushing a feature like this out without an accessible settings page or notice that it's there is a great way to deeply confuse your users. I would never have thought to tap the Firefox logo for any reason, so to me it just looked like the theme setting broke. I don't think it's very helpful for you to get feedback on this feature from Nightly users if we don't even know it's a feature in the first place.

**Comment by Amejia481** [comment] 2022-01-10 13:08
Sorry for the inconveniences, there is a fix (https://github.com/mozilla-mobile/fenix/commit/28928e4bddc1f12fefb37c73f74d06ad4d8bae20) that will be available in the next nightly update.  Even thought it doesn't look like but the feedback we are getting help us to polish and shape the feature early.

**Comment by Mugurell** [comment] 2022-02-08 08:36
This seems to be fixed.

**Comment by SoftVision-LorandJanos** [comment] 2022-02-08 11:39
Verified as fixed on the latest Nightly 98.0a1 (2022-02-08) using the following devices:
- Xiaomi Mi11 Lite (Android 11) - as the closest to the one this issue was reproduced on.
- Oppo Reno 6 (Android 11).
- Samsung Galaxy Tab S3 (Android 9).
- LG Nexus 5 (Android 6.0.1).

Tested on the build on which the issue was reproduced, as well: Nightly 97.0a1 (2022-01-07), before and after clearing data.

Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-02-08 11:39 UTC
Labels: 🐞 bug, eng:qa:needed, Feature:Themes, regression, Needs-UX
