### ISSUE TITLE
Hide Synced Tabs UI when Firefox Accounts does not have "Sync Tabs" enabled

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11995] opened 2020-06-26 10:19 UTC
### What is the user problem or growth opportunity you want to see solved?
It does not make sense to have the synchronised tab item under 3 dot menu of tabs...it should be only in home screen 3 dot menu..besides if we turn off sync tabs from sync menu this should not be visible at all

### How do you know that this problem exists today? Why is this important?
While the synchronised tab feature is not promoted or highlighted too much in firefox desktop here in fenix it is highlighted too much

### Who will benefit from it?
All users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2679)

**Comment by cadeyrn** [comment] 2020-06-26 10:23
> It does not make sense to have the synchronised tab item under 3 dot menu of tabs

I do not understand why you think it doesn't make sense. For me it's even much more relevant than history or bookmarks.

**Comment by sheikh-azharuddin** [comment] 2020-06-26 10:25
I have disabled sync open tabs....in that case why should I see this everywhere?

**Comment by SS1113** [comment] 2020-06-26 10:32
@sheikh-azharuddin you may not be using that feature (I also don't) but lots of other users use that feature and it is super important to them! Having that "Synced tabs" entry is really important. I think the decisions on what items to be presented in the 3-dot menu item are done on the basis of number of users using them.

I don't think it should be removed as it'll cause trouble to the users who are using them. How do you expect the users who are using them can get a quick/accessible way access to their synced tabs; it should be at the 3-dot main menu to be accessible. Tab syncing is one the most important features of a browser even if you and I don't use it, others use it extensively!

**Comment by sheikh-azharuddin** [comment] 2020-06-26 10:34
But I have disabled that feature...so why should I see it?

**Comment by SS1113** [comment] 2020-06-26 10:43
> But I have disabled that feature...so why should I see it?

Browser makers have to balance out the number of settings they present to users otherwise it'll make users feel overwhelmed! In this case the tabs syncing feature is really important.

Just like how I suggest to [keep add-ons entry](https://github.com/mozilla-mobile/fenix/issues/11630) as it was one of the most important features of Fenix. So instead of removing it they decided to keep it and decided to remove [what's new](https://github.com/mozilla-mobile/fenix/issues/11795) instead with my suggestion, as it was not very useful after users view what's new in there browser and make  dynamic appear and disappear based on the context.

**Comment by sheikh-azharuddin** [comment] 2020-06-26 10:55
If you have already decided then nothing much to say ...

**Comment by cadeyrn** [comment] 2020-06-26 10:59
> I have disabled sync open tabs....in that case why should I see this everywhere?

Maybe Mozilla want to take the oppotunity to advertise sync on this panel, I don't know. But to hide the menu item for user who are not signed in is a different discussion than hiding it for all users. 

> If you have already decided then nothing much to say ...

Neither @SS1113 nor I work for Mozilla, we can't decide anyhing for Fenix.

**Comment by SS1113** [comment] 2020-06-26 11:01
@sheikh-azharuddin please don't close the issue suddenly, let the developers also have a say on this. I'm not sure what they'll say. I was just presenting my side of opinions.

**Comment by sheikh-azharuddin** [comment] 2020-06-26 11:07
I want that item to be dynamic ...it should be visible only when user has enabled the setting to sync open tabs..

Plus I don't understand the too much need of sync tabs...why would I need it?? To spy on my wife what tabs she has opened? 🤣

If I want to view something in desktop from mobile I can easily click share button and send tab to the device. 
Why will I open all the tabs in both browsers...

**Comment by cadeyrn** [comment] 2020-06-26 11:15
> Plus I don't understand the too much need of sync tabs...why would I need it?? To spy on my wife what tabs she has opened?

Well… Ideally your wife has her own Firefox Account. ;-)

> If I want to view something in desktop from mobile I can easily click share button and send tab to the device.

You can only click a share button on a device that you have in front of you.

**Comment by liuche** [comment] 2020-06-26 23:13
One thing that we could do is hide this feature if you've turned off tab syncing - I think that would be a reasonable next step.

This also won't be the long-term home for Synced Tabs - they will live in the tabs tray, but for now, we've put them in there so the feature exists, however, I can update this title so that Synced Tabs aren't shown when you have tab syncing disabled.

Thanks for the perspective and for taking the time to file a bug!

**Comment by SS1113** [comment] 2020-06-27 00:45
Hi, @sheikh-azharuddin. Look what's happening! See, the feature you were asking about is being considered! So when the next time an idea hits your head don't try to hide it no matter what anyone says! And share your perspective and opinions without any hesitations so that we can all do the same! 

So can you please share your next idea with us here, so that the browser we use and love can really improve?

**Comment by sheikh-azharuddin** [comment] 2020-06-27 03:36
Thanks Saipan and liuche 😊😃

**Comment by sheikh-azharuddin** [comment] 2020-06-27 03:43
Thanks Saipan and liuche 😊😃
Also I have one query regarding sync settings...do they also sync across devices? I mean let's say I have 2 PC P1 and P2 and one mobile device M1

Let's say I use P1 and M1 for personal use and P2 is actually office pc where I have used my firefox account...
In office PC I don't want to sync history only tabs, bookmarks , settings I turned off history but what I have seen this is also turning off history for other devices too P1 and M1. Also is this expected? What If I want different sync setting for different device?

**Comment by SS1113** [comment] 2020-06-27 04:09
> Let's say I use P1 and M1 for personal use and P2 is actually office pc where I have used my firefox account...
> In office PC I don't want to sync history only tabs, bookmarks , settings I turned off history but what I have seen this is also turning off history for other devices too P1 and M1. Is this expected?

AFAIK, Sync settings are handled this way and it is an expected behaviour.

Let's say, If you turned off history syncing on one then it'll turn off across all the devices you have connected and if you enable it; it'll be enabled across the devices.

**Comment by jonalmeida** [comment] 2023-01-17 16:30
This issue was filed when Sync Tabs was under the three-dot menu. I'm going to close this as "won't fix" as a result since we have it in the tabs tray now.

**Closed by jonalmeida** 2023-01-17 16:30 UTC
Labels: feature request 🌟, Feature:SyncTabs

**Comment by sheikh-azharuddin** [comment] 2023-01-17 18:04
> This issue was filed when Sync Tabs was under the three-dot menu. I'm going to close this as "won't fix" as a result since we have it in the tabs tray now.

🙏So features requests are getting closed when it no longer applicable after some years 😂

Similarly I see some of my requests were closed and moved to bugzilla but is there anyone working on those bugs?
