### ISSUE TITLE
Downloads prompts do not show again when a user denies system permission twice

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#17650] opened 2021-01-26 23:22 UTC
If you try to download a file and deny the system dialog permission, and then do it again after that you are never going to get the system permission dialog again and all future downloads are going to be cancel by default without users noticing.

 
To fix that we have to do something similar to what we did on this [pr](https://github.com/mozilla-mobile/fenix/commit/0a23d66756c79c65f89830d07e187fd10ec2b99c), we have to use [shouldShowRequestPermissionRationale](https://developer.android.com/reference/androidx/core/app/ActivityCompat#shouldShowRequestPermissionRationale(android.app.Activity,%20java.lang.String)) to verify if permissions have been denied permanently and users have to go to the settings page and grant the permission there, for more information see  https://developer.android.com/training/permissions/requesting#request-permission

**Comment by VitalyVPinchuk** [comment] 2021-02-24 12:32
Hello @Amejia481 
Could I try to fix it?

**Comment by Amejia481** [comment] 2021-02-24 14:46
Thanks @VitalyVPinchuk for being interested in this issue, I was taking a closer look and I think it could take more work that I'm initially estimate, we prefer to work on the issue, please feel free to take other one, sorry for the inconveniences.

**Comment by ebalazs-sv** [comment] 2021-03-10 12:17
This issue is not reproducible on Nightly 3/10, Beta 87.0.0-beta.4 from 3/8 and Release 86.1.1 from 2/23 with the following devices:
- Motorola Moto G6 (Android 8);
- LG G7 Fit (Android 8.1);
- Pixel 2 (Android 9);
- Samsung Note 10 (Android 11).

**Comment by ebalazs-sv** [comment] 2021-03-10 15:01
The Nightly tested has the AC version 74.0.20210309154120 and I could not reproduce the issue on this build, neither on the latest Beta or Release builds.

**Comment by Amejia481** [comment] 2021-03-10 15:15
Did you see the download dialog after denying permissions twice?

**Comment by ebalazs-sv** [comment] 2021-03-10 15:21
> Did you see the download dialog after denying permissions twice?

Yes, the downloads dialog is displayed after denying the permissions twice.

**Comment by Amejia481** [comment] 2021-03-15 16:38
Sorry for the delay, the fixed is on nightly.

The expected behavior is the dialog is shown when the permission is denied, indicating the user to go the settings page and allow the permission, if the user do so the download dialog will show the next time we try to download a file.

https://user-images.githubusercontent.com/773158/111185807-c1e52b00-8588-11eb-835d-171ceca4a8bc.mp4

**Comment by lobontiumira** [comment] 2021-03-17 14:42
Verified as fixed on the 3/17 Nightly build, using a Google Pixel (Android 10). 
After denying the download, the "Files and media permission access needed to download files. Go to Android settings, tap permissions, and tap allow. DISMISS   GO TO SETTINGS" propmt is displayed. Tapping on "GO TO SETTINGS" redirects the user to the Android permissions. Tapping on "DISMISS" dismisses the prompt; if trying to download again and denying again, the prompt is displayed again.


<img src="https://user-images.githubusercontent.com/40694158/111485851-a83a1400-873f-11eb-917e-eb00b5b9dbf1.png" width="300" height="550" />

**Closed by lobontiumira** 2021-03-17 14:42 UTC
Labels: E3, Feature:Download, S3, eng:qa:needed, 🐞 bug

**Comment by Amejia481** [comment] 2021-03-17 15:12
Thanks @lobontiumira !
