### ISSUE TITLE
Find and report RTL problems

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#5497] opened 2019-09-23 20:41 UTC
### Why/User Benefit/User Problem
As a user, I want to use the browser in my preferred RTL language and have a good experience.

### What/Requirements
App doesn't look broken
(In order to test, you can set the Android System language to an RTL language, and even though the strings won't change, the app will switch to RTL direction.)

### Acceptance Criteria (how do I know when I’m done?)
- [ ] App doesn't have broken RTL UI (that is not being reflowed properly)
- [ ] web content is supporting RTL
- [x] Each bug is filed with a [screenshot](https://github.com/mozilla-mobile/fenix/issues/5497#issuecomment-542505169) 
- [ ] Each fix from above list screenshotted bugs ^ includes screenshots of the **fix** (these can be broken into separate PRs)

~~This issue is done when we have issues filed for the RTL issues.~~ Since these screenshots are all listed here, the fixes can be against this issue as well.
We are NOT doing adding RTL languages, that's #5496

**Comment by liuche** [comment] 2019-09-23 21:34
@Delphine here's the bug to track RTL investigation for Reza :)

**Comment by 5y** [comment] 2019-10-16 04:16
- Open tabs menu texts should align to right.
![image](https://user-images.githubusercontent.com/1941933/66887132-f295ef00-efa7-11e9-91e9-79af4e17722e.png)



- No collections icon should align to the right.
![image](https://user-images.githubusercontent.com/1941933/66887376-ca5ac000-efa8-11e9-95af-11d10e22d803.png)



- The "Turn on Sync text" should align to the right.
![image](https://user-images.githubusercontent.com/1941933/66887505-39d0af80-efa9-11e9-9b40-172da81e1972.png)



- The desktop Site should align to the right.
![image](https://user-images.githubusercontent.com/1941933/66887604-700e2f00-efa9-11e9-8a86-74163fa20229.png)



- Find on the page button is out of the page.
![image](https://user-images.githubusercontent.com/1941933/66887718-e27f0f00-efa9-11e9-9f00-88fd72cf08af.png)

**Comment by liuche** [comment] 2019-10-19 00:24
I think these all seem like reasonable items that we should fix! I'm going to throw an eng:ready label on this.

**Comment by mcarare** [comment] 2019-10-21 13:31
@liuche For c) - the icon is mirrored correctly, because the icon is aligned to end in normal mode (LTR). It is reversed from the "_save to collection tex_t" where it is aligned to start. 
So IMO the RTL version is correct.

**Comment by mcarare** [comment] 2019-10-21 14:37
@5y Can you please retest  "_e) Find on the page button is out of the page_."
I cannot reproduce this. TY!

**Comment by brampitoyo** [comment] 2019-10-31 01:22
I also with @liuche that all of these issues look reasonable, without requiring any more UX feedback since what we need to do is already very clear.

**Comment by mcarare** [comment] 2019-10-31 07:25
@brampitoyo see my comment about c).

**Comment by 5y** [comment] 2019-10-31 23:12
@mcarare Considering the C, The icon is fine. the textbox should be aligned.

**Comment by mcarare** [comment] 2019-11-01 08:37
@5y Thank you for your input! 👍
Actually, I wanted to ask about b). I already fixed c) 
And if  _e) Find on the page button is out of the page._ is still reproducible

**Comment by 5y** [comment] 2019-11-01 23:20
@mcarare 
You are welcome.
d- Solved.
Regarding the "b", If we change the strings with RTL language strings such as Persian, It is more user-friendly for the users to have icon on the right side of the text.

+ I found another problem in the URL bar at the bottom. The conflict between the icon and the URL bar text.
![Screenshot_۲۰۱۹۱۱۰۱-۱۹۱۴۰۷](https://user-images.githubusercontent.com/1941933/68061639-41e45b00-fcdc-11e9-9423-1381ed4d2a63.png)

**Comment by cadeyrn** [comment] 2019-11-02 18:50
> I found another problem in the URL bar at the bottom. The conflict between the icon and the URL bar text.

This is fixed since #6016.

**Comment by brampitoyo** [comment] 2019-11-03 21:01
@mcarare wrote:
> see my comment about c).

The fix you proposed on #6152 looks great to me. Is there a specific feedback that you’re looking for?

@5y wrote:
> Regarding the "b", If we change the strings with RTL language strings such as Persian, It is more user-friendly for the users to have icon on the right side of the text.

<img src="https://user-images.githubusercontent.com/1941933/68061639-41e45b00-fcdc-11e9-9423-1381ed4d2a63.png" width="160">

I agree. The “No collection” icon should be placed on the right side.

**Comment by mcarare** [comment] 2019-11-04 08:41
@brampitoyo So, you want to keep the position in RTL same as LTR (to the right of text)? IMO mirroring some layouts partially it's not the greatest idea. There are no other layouts in this screen that we don't mirror.

**Comment by brampitoyo** [comment] 2019-11-05 04:43
@mcarare Sorry. I think I’m just a little unclear as to the fix that you’re suggesting.

Would you mind posting a mockup of your proposed fix? I don’t have enough experience with RTL layout to know that mirroring is sometimes correct, and sometimes incorrect.

What would your suggestion be?

**Comment by mcarare** [comment] 2019-11-05 08:29
@brampitoyo My suggestion is leave it as it is, because IMO it is correct.

**LTR**:<img src = https://user-images.githubusercontent.com/48995920/68190767-b2c69400-ffb6-11e9-9b16-c8ca6ce55272.png  width = 45%>**RTL**: <img src =https://user-images.githubusercontent.com/48995920/68190768-b2c69400-ffb6-11e9-9522-65a489575d1d.png width = 45%>

**Comment by 5y** [comment] 2019-11-06 17:44
@mcarare 
Yes, We can leave it as it is. However, Align the icons on the right side of the RTL language is more userfriendly, Because we usually align them on the right side of the words, phrases ...

**Comment by liuche** [comment] 2019-11-21 18:05
Hi @mcarare if something is in progress, could you move it to the In Progress column in the kanban? That way it's easy to see what work is available to work on. (And move it back + unassign if you stop working on it).

**Comment by 5y** [comment] 2019-11-21 19:48
@liuche @mcarare 
Please let me know if I can be of further assistance on this.

**Comment by mcarare** [comment] 2019-11-22 07:30
@liuche It's not in progress, I've already fixed some issues, and waiting for UX feedback on the others.

**Comment by brampitoyo** [comment] 2019-11-24 23:28
@mcarare @5y Hi Mihai and Reza,

Icons inside start page sections are arranged in a special way:

<img width="215" src="https://user-images.githubusercontent.com/51007/69503192-44a13b80-0f7c-11ea-894a-2edf2a69d3bb.png">

Compared to icons in menus, dialogs and other pages:

<img width="215" src="https://user-images.githubusercontent.com/51007/69503251-a1045b00-0f7c-11ea-8e00-dea31435cb41.png"><img width="215" src="https://user-images.githubusercontent.com/51007/69503253-a2ce1e80-0f7c-11ea-90db-8af40d24a4e4.png"><img width="215" src="https://user-images.githubusercontent.com/51007/69503254-a497e200-0f7c-11ea-8372-e84dd280946f.png">

I agree that the start page icon arrangement is different from the rest, but it was also designed intentionally.

For consistency, we should follow this special arrangement in RTL languages, as @mcarare suggested above on https://github.com/mozilla-mobile/fenix/issues/5497#issuecomment-549716100

Therefore, if the LTR layout is:
<img width="215" src="https://user-images.githubusercontent.com/48995920/68190767-b2c69400-ffb6-11e9-9b16-c8ca6ce55272.png">

Then the RTL layout should be:
<img width="215" src="https://user-images.githubusercontent.com/48995920/68190768-b2c69400-ffb6-11e9-9522-65a489575d1d.png">

And the copy underneath that says “Collect the things that matter to you” should be right-aligned.

**Comment by 5y** [comment] 2019-11-25 07:26
@brampitoyo 
Basically all of the icons in the Menu's should be aligned to the right, It means we have icons first and then the text. The order from Right-To-Left is : [RTL-aligned text ] [icon].

Considering " Save to Collection", the RTL version that you mentioned is correct:
 
![image](https://user-images.githubusercontent.com/1941933/69520504-e4ce7480-0f2a-11ea-97d0-ea1703031012.png)

**Comment by mcarare** [comment] 2019-11-27 08:39
For QA: Please also check on multiple devices if this is reproducible:
> e) Find on the page button is out of the page. < is reproducible

Thank you!

**Comment by sv-ohorvath** [comment] 2019-12-02 14:01
Verified all as fixed on Nightly 12/2.
Devices: Samsung Galaxy Tab 3 (Android 8.0), Mi 4i (Android 5.0.2), Samsung Galaxy S8 (Android 9)

**Closed by sv-ohorvath** 2019-12-02 14:01 UTC
Labels: P2, eng:qa:needed, eng:ready, help wanted, 🌐 L10N:RTL, 🐞 bug
