### ISSUE TITLE
[Bug][L10n] Tabs section from Settings is not translated in Hindi

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#17619] opened 2021-01-25 12:17 UTC
## Steps to reproduce
1. Launch Fenix and change the language to Hindi;
2. Go to three-dot menu and open Settings;
3. Tap the "Tabs" section
4. Observe the translation of the "Tabs" section;
### Expected behavior
All the elements of Tabs section are translated in Hindi;
### Actual behavior
Some elements from the "Tabs" section are not translated in Hindi.
![rsz_screenshot_20210125-141205](https://user-images.githubusercontent.com/48799384/105704694-dbb6aa00-5f17-11eb-8ca9-e55316915f3a.png)
![rsz_screenshot_20210125-141157](https://user-images.githubusercontent.com/48799384/105704700-de190400-5f17-11eb-9348-4ccb9a23293f.png)

### Device information

* Android device: Pixel 2 (Android 9)
* Fenix version: Nightly 1/25, Beta 85.0.0-beta.9, Release 85.1.0-RC.2;

**Comment by sflorean** [comment] 2021-01-25 13:19
Reproducible also with Kazakh language, the Tabs section.

**Comment by Delphine** [comment] 2021-02-03 00:19
Both locales have translated "Tabs" for Fenix (just checked in Pontoon).
Could there be an issue again with l10n string imports?
CC @escapewindow and @MihaiTabara for feedback, thanks!

**Comment by escapewindow** [comment] 2021-02-03 00:55
It looks like everything's working, and the update-projects hook didn't find any new changes for Fenix. It did find some changes for android-components, though. https://firefox-ci-tc.services.mozilla.com/tasks/groups/fDaNSnCUT6KY85Fns_z4Jg

**Comment by Delphine** [comment] 2021-02-03 01:07
Thanks for the quick reply Aki! Will keep on investigating this, then

**Comment by Delphine** [comment] 2021-02-24 19:10
Seems like Hindi currently has 106 unstranslated strings, so this may be the reason it appears untranslated. 
I will close this for now, and we can double-check again once Hindi is 100% complete.

**Comment by Delphine** [comment] 2021-02-25 17:44
Closing for now, but we should check again once Hindi reaches 100%

**Closed by Delphine** 2021-02-25 17:44 UTC
Labels: Feature:Settings, 🌐 L10N, 🐞 bug
