### ISSUE TITLE
[Bug] Starbucks PWA custom tabs have wrong color

### ISSUE THREAD

**Issue by apbitner** [mozilla-mobile/fenix#5585] opened 2019-09-25 21:26 UTC
## Steps to reproduce

- Go to app.starbucks.com and save as PWA
- Tap on the 'Learn more' button in the middle of the screen

### Expected behavior
- Opens up new page in PWA, full-screen; Or,
- Opens up new page in a custom tab with correct design
### Actual behavior
- Opens up new page in a custom tab with icons that have the wrong color
![image](https://user-images.githubusercontent.com/22176302/65640950-22f1fb00-dfb1-11e9-9864-d15c555aa7fd.png)

### Device information

* Android device: Android 10, Pixel 3
* Fenix version: 1.0.1939 (Build #1)

**Comment by NotWoods** [comment] 2019-09-25 23:25
The custom tab should be showing a background color of `#00A862`.

https://appsco.pe/app/starbucks

**Comment by liuche** [comment] 2019-10-25 17:15
@NotWoods we're going through this in our sprint planning, could you give an update?

**Comment by NotWoods** [comment] 2019-10-25 18:33
I can't reproduce the issue, so perhaps we should close it.

**Comment by abodea** [comment] 2019-10-28 10:32
I re-checked this issue using the latest Nightly build from 28/10 **`Nightly 191028 06:00 (Build #13010606 📦: 19.0.0, 6e6311ea4🦎: 72.0a1-20191025095546`**.
Note that I can still reproduce this issue, the custom tab top bar color is white instead of `#00A862`.
Also note that @apbitner in the description + attachment talked about the images color in the top bar ![download (7)](https://user-images.githubusercontent.com/42831109/67668989-ad939480-f979-11e9-97cc-013a369ca2c1.png) you can see the issue by zooming on this image, but @NotWoods said about the background color for the top bar here https://github.com/mozilla-mobile/fenix/issues/5585#issuecomment-535263406 wich are 2 different things.
Note that now the color icons is correct but the top bar color in custom tab should be `#00A862` instead of white.
![12](https://user-images.githubusercontent.com/42831109/67671600-ea15bf00-f97e-11e9-8463-cbf217ab8fea.jpg)
Based on my comment I will remove the `eng:qa:needed` label.

**Comment by NotWoods** [comment] 2019-11-22 07:15
I'm only able to find issues with the Starbucks PWA. For some reason, its web manifest doesn't have a theme color once parsed. I'm not sure if Starbucks doesn't serve us the theme_color or that it gets stripped out at some point in our code, more investigation needed.

**Comment by NotWoods** [comment] 2019-12-18 20:48
I found the issue with Starbucks. Their theme color is `#00A862` but GeckoView removes the leading zeros when parsing the manifest, creating `#A862`. Android Components can't parse this four-digit color so it gets discarded.

**Comment by AndiAJ** [comment] 2019-12-31 09:37
Hi, **verified as fixed** on the latest **Nightly Build #13650606 from 12/31** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191231_112110](https://user-images.githubusercontent.com/51314259/71617060-ec380c00-2bc1-11ea-9367-285f89493503.gif)

**Closed by AndiAJ** 2019-12-31 09:37 UTC
Labels: Feature:PWA, P5, b:webcompat, eng:qa:verified, needs:gv, 🐞 bug
