### ISSUE TITLE
[feature request] display the source code of the viewed pages

### ISSUE THREAD

**Issue by gbdomubpkm** [mozilla-mobile/fenix#24313] opened 2022-03-17 12:03 UTC
Hello.
I can't display the source code of  viewed pages with Fenix. Is this feature is missing ? If yes, it would be nice to implement it. If it is possible, how to do that ?
Thanks
Regards

**Comment by cadeyrn** [comment] 2022-03-17 12:07
Duplicate of #3710.

**Closed** 2022-03-17 12:32 UTC
Labels: needs:triage
