### ISSUE TITLE
[Bug]Downloaded images are not appearing in the Gallery app

### ISSUE THREAD

**Issue by dbiciusca** [mozilla-mobile/fenix#15048] opened 2020-09-13 17:17 UTC
## Steps to reproduce
Download any image from the internet. 
### Expected behavior
When I download an image in Firefox or Firefox beta latest builds, the image doesn't appear in the Gallery app. I don't have this issue on version 79 which I downgraded to.
Also, if I install any media rescan apps, the images appear just fine, so there is nothing wrong with the images. 
### Actual behavior
The downloaded images shouls trigger media rescan and the pictures should appear in gallery.
### Device information

* Android device: Huawei P30 Pro witn Android 10
* Fenix version: 80.1.3

**Comment by hwinnemoe** [comment] 2020-09-13 19:41
Duplicate of #8754

**Comment by kbrosnan** [comment] 2020-09-13 23:11
Closing as a duplicate

**Closed by kbrosnan** 2020-09-13 23:11 UTC
Labels: needs:triage, 🐞 bug
