### ISSUE TITLE
[Bug]: blank and unresponsive screen since version 98

### ISSUE THREAD

**Issue by Carles-Figuerola** [mozilla-mobile/fenix#24226] opened 2022-03-11 20:58 UTC
### Steps to reproduce

After the apk is updated to version 98 or 99 beta, opening the app makes a blank screen (no decoration, no url bar, no buttons or anything to interact). Rolling back to 97.3.0 makes firefox work again.

### Expected behaviour

firefox should show menus and web content

### Actual behaviour

The app cannot be interacted with

### Device name

Sony Xperia XZ1

### Android version

Android 8

### Firefox release type

Firefox

### Firefox version

98.0.0

### Device logs

Cannot pull logs from the application. Checked catlog while opening the app but could not find anything obvious (no tracebacks, at least), can find something better if anyone knows a keyword I can search for

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-19819)

**Comment by Carles-Figuerola** [comment] 2022-03-11 21:01
Some logs:
```
2022-03-11 14:59:24.469 1646-3407/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.mozilla.firefox_beta/.App bnds=[20,336][236,559]} from uid 10187
2022-03-11 14:59:24.481 1646-3407/? D/ActivityTrigger: activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{60d8c0 org.mozilla.firefox_beta}
2022-03-11 14:59:24.481 1646-3407/? E/ActivityTrigger: activityStartTrigger: not whiteListedorg.mozilla.firefox_beta/org.mozilla.firefox_beta.App/2015867611
2022-03-11 14:59:24.482 1646-3407/? D/ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{60d8c0 org.mozilla.firefox_beta} is now in focus and seems to be in full-screen mode
2022-03-11 14:59:24.482 1646-3407/? E/ActivityTrigger: activityResumeTrigger: not whiteListedorg.mozilla.firefox_beta/org.mozilla.firefox_beta.App/2015867611
2022-03-11 14:59:24.490 1646-2757/? D/ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{60d8c0 org.mozilla.firefox_beta} is now in focus and seems to be in full-screen mode
2022-03-11 14:59:24.490 1646-2757/? E/ActivityTrigger: activityResumeTrigger: not whiteListedorg.mozilla.firefox_beta/org.mozilla.firefox_beta.App/2015867611
2022-03-11 14:59:24.503 1646-2757/? I/ActivityManager: Start proc 6704:org.mozilla.firefox_beta/u0a622 for activity org.mozilla.firefox_beta/.App
2022-03-11 14:59:24.597 3477-3477/? D/KP2AAF: event: 2048, package = org.mozilla.firefox_beta
2022-03-11 14:59:24.603 3477-3477/? D/KP2AAF: event: 32, package = org.mozilla.firefox_beta
2022-03-11 14:59:24.696 3477-3477/? D/KP2AAF: event: 2048, package = org.mozilla.firefox_beta
2022-03-11 15:01:25.184 1646-1704/? W/ActivityManager: Activity pause timeout for ActivityRecord{d7113f2 u0 org.mozilla.firefox_beta/.App t40882}
2022-03-11 15:01:35.191 1646-1704/? W/ActivityManager: Activity stop timeout for ActivityRecord{d7113f2 u0 org.mozilla.firefox_beta/.App t40882}
```

**Comment by kbrosnan** [comment] 2022-03-14 18:36
@Carles-Figuerola are you able to start this build of our base Geckoview browser? https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-gcp-opt

**Comment by Carles-Figuerola** [comment] 2022-03-14 18:55
I think this is behaving the same way firefox 98+ does, it's a blank page and it kinda hangs most of the phone's UI in general:

![image](https://user-images.githubusercontent.com/13749641/158241605-3805e427-277c-4598-be1b-2a30c1576dcc.png)

**Comment by navidmafi** [comment] 2022-04-22 06:05
This exact issue is happening on Xperia XZ f8332 and forced me to downgrade to a working version.
Based on testing older APKs from mirror sites, I can confirm that the issue starts from 98.1.0 and 97.3.0 works fine.

**Comment by Beurt** [comment] 2022-04-25 19:53
I confirm the exact same behavior on a Sony xz1c with both Fenec and Firefox > 97.1.1 (from 98.0).

Blank Fenec/Firefox, unresponsive interface. I tried to clean cache and data, to install/uninstall. No result. The downgrade is the only solution, as reported above.

**Comment by agi** [comment] 2022-04-25 20:38
Hi @Carles-Figuerola @Gregory-K @navidmafi @Beurt Thank you so much for your reports! We really appreciate it. Would any of you be able to test [this APK](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-central.latest.mobile.android-aarch64-gcp-opt/artifacts/public%2Fbuild%2Fgeckoview_example.apk?bewit=bW96aWxsYS1hdXRoMC9hZHxNb3ppbGxhLUxEQVB8YXNmZXJyb1wxNjUwOTE5MDM2XC8yUFZTaENkeXJ2dzZkTXdzei9IR1l0NnFXcTJxL2twb1BHbDhlbGxEU2c9XGV5SmpaWEowYVdacFkyRjBaU0k2ZXlKMlpYSnphVzl1SWpveExDSnpZMjl3WlhNaU9sc2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2U1c1MGNtRnVaWFJYYVd0cElpd2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2VTNSaGRITkVZWE5vWW05aGNtUWlMQ0poYzNOMWJXVTZiVzk2YVd4c1lTMW5jbTkxY0RwaFkzUnBkbVZmYzJOdFgyeGxkbVZzWHpFaUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHBoWTNScGRtVmZjMk50WDJ4bGRtVnNYeklpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcGhZM1JwZG1WZmMyTnRYMnhsZG1Wc1h6TWlMQ0poYzNOMWJXVTZiVzk2YVd4c1lTMW5jbTkxY0RwaGJHeGZiR1JoY0Y5MWMyVnljeUlzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09tRnNiRjl6WTIxZmJHVjJaV3hmTVNJc0ltRnpjM1Z0WlRwdGIzcHBiR3hoTFdkeWIzVndPbUZzYkY5elkyMWZiR1YyWld4Zk1pSXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T21Gc2JGOXpZMjFmYkdWMlpXeGZNeUlzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09tVm5aVzVqYVdGZmRYTWlMQ0poYzNOMWJXVTZiVzk2YVd4c1lTMW5jbTkxY0RwdlptWnBZMlZmY21WdGIzUmxJaXdpWVhOemRXMWxPbTF2ZW1sc2JHRXRaM0p2ZFhBNmNHaHZibVZpYjI5clgyRmpZMlZ6Y3lJc0ltRnpjM1Z0WlRwdGIzcHBiR3hoTFdkeWIzVndPblJsWVcxZmJXOWpieUlzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09uUmxZVzFmYlc5amIxOWlaVzVsWm1sMFpXUWlMQ0poYzNOMWJXVTZiVzk2YVd4c1lTMW5jbTkxY0RwMmNHNWZZMjl5Y0NJc0ltRnpjM1Z0WlRwdGIzcHBiR3hoTFdkeWIzVndPblp3Ymw5a1pXWmhkV3gwSWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZkbkJ1WDJ0cGJuUnZNVjl3Y205a0lpd2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2ZG5CdVgydHBiblJ2TVY5emRHRm5aU0lzSW1GemMzVnRaVHBzYjJkcGJpMXBaR1Z1ZEdsMGVUcHRiM3BwYkd4aExXRjFkR2d3TDJGa2ZFMXZlbWxzYkdFdFRFUkJVSHhoYzJabGNuSnZJbDBzSW5OMFlYSjBJam94TmpVd09URTRNRGMyTVRJNUxDSmxlSEJwY25raU9qRTJOVEE1TVRrNE56WXhNamtzSW5ObFpXUWlPaUpYUzBORGFHeHJhbE5VTW5acWRuUTJUa1pxWHpKQmIyRldVRzFtTFVWUlVXRmxVR1Z1V2tFd1NrY3RaeUlzSW5OcFoyNWhkSFZ5WlNJNklrMVFTeXRLVjIwNWNWVmpkMWhZY21SbVEyWkZSbWhrVldGblNHTkZlRGhpUVVsTWRtTXZNWEo2V1ZrOUlpd2lhWE56ZFdWeUlqb2ljM1JoZEdsakwzUmhjMnRqYkhWemRHVnlMM2RsWWkxelpYSjJaWElpZlgwPQ) it's the test build of GeckoView, it will help us identify where the problem is.

**Comment by Beurt** [comment] 2022-04-25 20:42
> Hi @Carles-Figuerola @Gregory-K @navidmafi @Beurt Thank you so much for your reports! We really appreciate it. Would any of you be able to test [this APK](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-central.latest.mobile.android-aarch64-gcp-opt/artifacts/public%2Fbuild%2Fgeckoview_example.apk?bewit=bW96aWxsYS1hdXRoMC9hZHxNb3ppbGxhLUxEQVB8YXNmZXJyb1wxNjUwOTE5MDM2XC8yUFZTaENkeXJ2dzZkTXdzei9IR1l0NnFXcTJxL2twb1BHbDhlbGxEU2c9XGV5SmpaWEowYVdacFkyRjBaU0k2ZXlKMlpYSnphVzl1SWpveExDSnpZMjl3WlhNaU9sc2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2U1c1MGNtRnVaWFJYYVd0cElpd2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2VTNSaGRITkVZWE5vWW05aGNtUWlMQ0poYzNOMWJXVTZiVzk2YVd4c1lTMW5jbTkxY0RwaFkzUnBkbVZmYzJOdFgyeGxkbVZzWHpFaUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHBoWTNScGRtVmZjMk50WDJ4bGRtVnNYeklpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcGhZM1JwZG1WZmMyTnRYMnhsZG1Wc1h6TWlMQ0poYzNOMWJXVTZiVzk2YVd4c1lTMW5jbTkxY0RwaGJHeGZiR1JoY0Y5MWMyVnljeUlzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09tRnNiRjl6WTIxZmJHVjJaV3hmTVNJc0ltRnpjM1Z0WlRwdGIzcHBiR3hoTFdkeWIzVndPbUZzYkY5elkyMWZiR1YyWld4Zk1pSXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T21Gc2JGOXpZMjFmYkdWMlpXeGZNeUlzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09tVm5aVzVqYVdGZmRYTWlMQ0poYzNOMWJXVTZiVzk2YVd4c1lTMW5jbTkxY0RwdlptWnBZMlZmY21WdGIzUmxJaXdpWVhOemRXMWxPbTF2ZW1sc2JHRXRaM0p2ZFhBNmNHaHZibVZpYjI5clgyRmpZMlZ6Y3lJc0ltRnpjM1Z0WlRwdGIzcHBiR3hoTFdkeWIzVndPblJsWVcxZmJXOWpieUlzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09uUmxZVzFmYlc5amIxOWlaVzVsWm1sMFpXUWlMQ0poYzNOMWJXVTZiVzk2YVd4c1lTMW5jbTkxY0RwMmNHNWZZMjl5Y0NJc0ltRnpjM1Z0WlRwdGIzcHBiR3hoTFdkeWIzVndPblp3Ymw5a1pXWmhkV3gwSWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZkbkJ1WDJ0cGJuUnZNVjl3Y205a0lpd2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2ZG5CdVgydHBiblJ2TVY5emRHRm5aU0lzSW1GemMzVnRaVHBzYjJkcGJpMXBaR1Z1ZEdsMGVUcHRiM3BwYkd4aExXRjFkR2d3TDJGa2ZFMXZlbWxzYkdFdFRFUkJVSHhoYzJabGNuSnZJbDBzSW5OMFlYSjBJam94TmpVd09URTRNRGMyTVRJNUxDSmxlSEJwY25raU9qRTJOVEE1TVRrNE56WXhNamtzSW5ObFpXUWlPaUpYUzBORGFHeHJhbE5VTW5acWRuUTJUa1pxWHpKQmIyRldVRzFtTFVWUlVXRmxVR1Z1V2tFd1NrY3RaeUlzSW5OcFoyNWhkSFZ5WlNJNklrMVFTeXRLVjIwNWNWVmpkMWhZY21SbVEyWkZSbWhrVldGblNHTkZlRGhpUVVsTWRtTXZNWEo2V1ZrOUlpd2lhWE56ZFdWeUlqb2ljM1JoZEdsakwzUmhjMnRqYkhWemRHVnlMM2RsWWkxelpYSjJaWElpZlgwPQ) it's the test build of GeckoView, it will help us identify where the problem is.

For the moment @agi the link is not working:

```json
{

    "code": "AuthenticationFailed",
    "message": "Unauthorized: Access expired\n\n---\n\n* method:     findArtifactFromTask\n* errorCode:  AuthenticationFailed\n* statusCode: 401\n* time:       2022-04-25T20:41:00.692Z",
    "requestInfo": {
        "method": "findArtifactFromTask",
        "params": {
            "0": "public/build/geckoview_example.apk",
            "indexPath": "gecko.v2.mozilla-central.latest.mobile.android-aarch64-gcp-opt",
            "name": "public/build/geckoview_example.apk"
        },
        "payload": { },
        "time": "2022-04-25T20:41:00.692Z"
    }

}
```

**Comment by agi** [comment] 2022-04-25 20:58
Ah sorry about that! Can you download the `geckoview_example.apk` file from here: https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-gcp-opt

**Comment by Beurt** [comment] 2022-04-25 21:08
> @Beurt Ah sorry about that! Can you download the `geckoview_example.apk` file from here: https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-gcp-opt

For me @agi it is also a blank screen (and unresponsive interface).

![Screenshot_20220425_230556](https://user-images.githubusercontent.com/12588136/165175257-6c508696-ba43-44b4-a164-2d6d81bf264c.png)

**Comment by Gregory-K** [comment] 2022-04-25 22:05
@agi I've tried the apk and the result was the same (like @Beurt posted right above).

I've attached a logcat in case it helps  
> [logcat.log](https://github.com/mozilla-mobile/fenix/files/8558286/logcat.log)

**Comment by cpeterso** [comment] 2022-04-25 22:11
The corresponding Jira issue: https://mozilla-hub.atlassian.net/browse/FNXV2-19819

**Comment by agi** [comment] 2022-04-25 23:09
Thank you @Beurt @Gregory-K ! Looks like this is a Gecko/GeckoView bug then.

**Comment by agi** [comment] 2022-04-25 23:09
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1766342

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jamienicol** [comment] 2022-04-26 10:49
If anybody affected by this is able to run [mozregression](https://mozilla.github.io/mozregression/) to help us track down the cause of this issue, that would be really helpful.

If your computer is running Linux or Macos, it's easiest to install mozregression from the command line, by running `pip install --user mozregression`. On windows, you can install `mozregression-gui.exe` from [here](https://github.com/mozilla/mozregression/releases).

Next you'll need to connect your phone to your computer, and ensure you have USB debugging enabled on your phone.

Then you can run mozregression. On the command line run `mozregression --app gve --good 97 --bad 98`. Or in the GUI, click the scissor icon to start a new bisection, on the first page select "gve" from the "Application" drop down menu then click "next". Click "next" again on the next page ("Profile selection"), then on the final page ("Build selection"). For last know good build, change "date" to "release" and enter 97. And for first known bad build, change "date" to "release" and enter 98. Then hit finish.

This will download a series of versions of firefox. For each one, enter "good" or "bad", and eventually it will tell you what change caused the issue. Please let me know if you need any help with that. Thanks!

**Comment by jamienicol** [comment] 2022-04-26 10:54
@navidmafi @Beurt are you both running Android 8.0 as well?

**Comment by jamienicol** [comment] 2022-04-26 10:59
Also, in a working build of Firefox (97), could each of you please go to about:support, click on "copy text to clipboard", and attach the contents to this bug?

**Comment by navidmafi** [comment] 2022-04-26 13:28
@jamienicol 
I'm running android 8 Oreo
Also here is the information you requested:
https://pastebin.mozilla.org/XNFcjY08
I will _try_ to track down the problem using mozregression as soon as I have time.

**Comment by Gregory-K** [comment] 2022-04-26 14:59
@jamienicol

Android v8.0.0

about:support  
https://pastebin.mozilla.org/MkMV31x2

mozregression (win10)  
https://pastebin.mozilla.org/KmA68FzQ

**Comment by Carles-Figuerola** [comment] 2022-04-26 17:16
* `about:support`
https://pastebin.mozilla.org/z8eRm5B6

* `mozregression --app gve --good 97 --bad 98`
https://pastebin.mozilla.org/5jgOATcM

**Comment by cpeterso** [comment] 2022-04-26 17:51
>     * `mozregression --app gve --good 97 --bad 98`
>       https://pastebin.mozilla.org/5jgOATcM

Thanks! The mozregression log is a huge help. From the log, here is the regressing pushlog:

https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=524ae1444004ec35dfcc348104060e91e1efce82&tochange=b34a32e1fc3e6fe4e0b7bcbb68cca4b797e9733d

Some GeckoView changes from Agi, but nothing that stands out as an obvious cause of the blank screen. Since bug happens at app startup, maybe [Bug 1751041](https://bugzilla.mozilla.org/show_bug.cgi?id=1751041) (Compute the process startup timestamp early during startup) is related?

**Comment by navidmafi** [comment] 2022-04-27 04:33
Can we get 2 builds before this exact and after it to test if it is related?

**Comment by jamienicol** [comment] 2022-04-27 10:31
Before bug 1751041: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/cvNzqVZWQJqVNZCvSSaDWw/runs/0/artifacts/public/build/geckoview_example.apk

After: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/PYSwbRC_RICaoJQJDRDVLg/runs/0/artifacts/public/build/geckoview_example.apk

**Comment by Gregory-K** [comment] 2022-04-27 11:46
> Before bug 1751041
good - working

> After
bad - WSoD (white screen of death)

**Comment by navidmafi** [comment] 2022-04-27 11:56
The first build works fine.
The second one, does not.
This issue is indeed related to that bug

**Comment by jamienicol** [comment] 2022-04-27 12:41
Thank you both for testing, it is much appreciated!

**Comment by rvandermeulen** [comment] 2022-05-17 01:45
We've landed a fix for this issue on the Nightly and Beta channels. Any verification we can get from users who were seeing this bug would be greatly appreciated!

**Comment by Carles-Figuerola** [comment] 2022-05-17 01:56
Just installed the nightly and beta versions from the play store and they loaded up fine! 

beta: 101.0.0-beta5 (build 2015880707)
nightly: 102.0a1 (build 2015880867)

I also just literally upgraded phones 2 days ago, but I'm ecstatic that the fix was found and resolved!!

**Comment by navidmafi** [comment] 2022-05-17 03:38
The issue seems to be resolved in lastest beta and nightly versions. (Installed from play store)

Thank you everyone for your time and effort

**Comment by kamil445** [comment] 2022-05-17 09:40
I also can confirm! 

Had this bug too on my Xperia Z2 D6503 Android 6.0.1 and latest Beta and Dev working!

Thanks for fixing this!

**Comment by Gregory-K** [comment] 2022-05-17 13:42
Confirmed. The issue has been resolved in both the latest `nightly` and `beta` versions.

**Closed** 2022-11-25 00:11 UTC
Labels: 🐞 bug, needs:triage, wontfix
