### ISSUE TITLE
[Bug] download starts but doesn't finish

### ISSUE THREAD

**Issue by mbrodesser** [mozilla-mobile/fenix#16521] opened 2020-11-12 09:43 UTC
## Steps to reproduce
1. Open https://www.danskitchen.de/speisekarte.
2. Click "Klick mich und such dir was leckeres aus".

### Expected behavior
Download should start.

### Actual behavior
Download starts, but doesn't seem to proceed for several minutes, doesn't finish.

### Device information
* Android device: Moto G5
* Fenix version:
82.1.1 (Build #2015770921)
AC: 60.0.5, a1a471ddc
GV: 82.0-20201014125134
AS: 63.0.0 

Works with Nightly, fails with Firefox Daylight. No plugins installed. Same behavior on other websites.

**Comment by kbrosnan** [comment] 2020-11-12 15:16
Closing as works for me

**Closed by kbrosnan** 2020-11-12 15:16 UTC
Labels: needs:triage, 🐞 bug

**Comment by AndiAJ** [comment] 2020-11-12 15:30
Dupe of #15378

**Comment by mbrodesser** [comment] 2020-11-12 16:15
This doesn't seem to be a duplicate of #15378, because it already happens for the first download. It reproduces reliably on my device. As this is [known to be broken](https://mozilla.slack.com/archives/C04U5001K/p1605194139072600?thread_ts=1605175093.071700&cid=C04U5001K), it should be clearly stated. If it's fixed in the next release and that arrives soon at end-users, that's of course fine.

**Comment by PranavBhattarai** [comment] 2020-11-14 04:07
@mbrodesser You are right. This happens in the first download, let alone mutiple download. 
This kind of major problem should wait major release. It's so frustating for end users, and they will move on immediately.

**Comment by mohibo** [comment] 2021-02-04 17:14
> 
> 
> Closing as works for me
and because its working for you,does it mean it works for everyone?
