### ISSUE TITLE
[Bug]: Address data must not be null

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#25789] opened 2022-06-28 16:22 UTC
Seeing a couple new crashes in nightly related to null address autofill data properties:
[1](https://sentry.io/organizations/mozilla/issues/3373619075/?project=6295546&query=is%3Aunresolved+level%3Afatal+firstSeen%3A-1w&sort=freq&statsPeriod=14d) [2](https://sentry.io/organizations/mozilla/issues/3371736205/?project=6295546&query=is%3Aunresolved+level%3Afatal+firstSeen%3A-1w&sort=freq&statsPeriod=14d)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20826)

**Comment by gabrielluong** [comment] 2022-06-28 17:49
Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/25735

**Closed by gabrielluong** 2022-06-28 17:49 UTC
Labels: 🐞 bug, Feature:Autofill

**Comment by MatthewTighe** [comment] 2022-06-28 18:43
This should be resolved by https://bugzilla.mozilla.org/show_bug.cgi?id=1774481
