### ISSUE TITLE
[Bug] Downloading fails if 'Download' folder doesn't exist in storage

### ISSUE THREAD

**Issue by parvinderandroid** [mozilla-mobile/fenix#13134] opened 2020-07-30 18:33 UTC
## Steps to reproduce

1. Delete 'Download' folder from storage
2. Open https://www.bromite.org/
3. Scroll to bottom
4. Click Download

### Expected behavior

1. Downloading begins
2. Downloading finishes

### Actual behavior

1. Downloading immediately fails

### DEVICE INFORMATION

* Android device: Huawei Honor 8 Pro (DUK-L09) - Android 9.0
* Fenix version: 79.1.0-beta.1 & Nightly 200730 06:21

### VIDEO OF ISSUE:

https://i.imgur.com/VJ3cyCr.mp4

**Comment by FrostedIce339** [comment] 2020-08-04 07:10
I am able to reproduce the issue. I tried deleting the Download folder in my device's internal storage and tried downloading an APK from Apkmirror.com and the download failed with 'Download failed' with 'Try again' dialogue and if iI press dialogue it fails again. And If the Download folder is available, I am able to download files.  

I am also getting a 'null download failed' dialogue and the notification cannot be dismissed and I have to Force stop the Firefox app to make it disappear from the notification bar.

**Comment by omicron-b** [comment] 2020-08-24 21:14
Duplicate of #5829 ?

**Comment by kbrosnan** [comment] 2020-08-28 23:15
Closing as a duplicate.

**Closed by kbrosnan** 2020-08-28 23:15 UTC
Labels: Feature:Download, 🐞 bug
