### ISSUE TITLE
[Bug] Manual Sign in Onboarding card has overlapping text on Russian locale

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/fenix#20219] opened 2021-07-01 14:05 UTC
## Steps to reproduce
1. Call appearance of the first run page in Firefox (install developer version of the Firefox or clear data of your installed Firefox (warning, data loss!)
2. Change your system locale to Russian (to reproduce this bug)
3. Change your screen orientation to portrait mode (if it isn't)
4. Look at the strings "Синхронизация Firefox между устройствами" and "Перенесите закладки, историю и пароли в Firefox на этом устройстве" in the Manual Sign-in Onboarding card.
### Expected behavior
These strings should be not so close each other and looking normally, like in landscape mode.
![Screenshot_20210701-162905_Firefox Beta](https://user-images.githubusercontent.com/85299944/124136499-83b73d00-da8d-11eb-925a-533f1c95f37d.jpg)
### Actual behavior
These strings located too close each other and looking weird.
![Screenshot_20210630-225129_Firefox Nightly](https://user-images.githubusercontent.com/85299944/124136748-b8c38f80-da8d-11eb-9da3-477ea0673440.jpg)
### Device information
* Device vendor / model and Android version: Samsung Galaxy A20s, Android 10
* Firefox for Android version: 89.1.1, 90.0.0-beta.6, Nightly 2021-06-30T17:07:09.023
### Note
Firefox 89.1.1 on Samsung Galaxy J2 Prime (Android 6.0.1) is not affected
![Screenshot_20210701-162832](https://user-images.githubusercontent.com/85299944/124137466-65057600-da8e-11eb-932c-dcb774bc2297.png)

**Comment by Nickoriginal** [comment] 2021-07-01 20:39
https://github.com/mozilla-mobile/fenix/issues/19661

**Comment by SoftVision-LorandJanos** [comment] 2021-07-05 13:05
Hi @Nickoriginal ! Thank you for the report! I was able to reproduce this issue on Motorola Nexus 6 (Android 7.1.1) and on Google Pixel 4 (Android 11), but I couldn't reproduce it with a Samsung Galaxy Tab 3 (Android 9).
Tested with the latest Beta (90.0.0-beta.6) and latest Nightly (91.0a1 - 2021-07-05T05:06:51.686).

**Comment by Nickoriginal** [comment] 2021-07-05 18:45
Fixed in Nightly **91.0a1 2021-07-05T17:06:08.350**
<img src = https://user-images.githubusercontent.com/85299944/124509235-424ec680-ddda-11eb-83e5-ba5707095d0b.jpg width = 45%>

**Comment by SoftVision-LorandJanos** [comment] 2021-07-06 12:12
Verified as fixed on the latest Nightly (91.0a1 - 2021-07-06T05:07:23.106).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0).

**Closed by SoftVision-LorandJanos** 2021-07-06 12:12 UTC
Labels: Feature:Onboarding, eng:qa:needed, needs:triage, 🌐 L10N, 🐞 bug

**Comment by Nickoriginal** [comment] 2021-07-06 14:57
Fixes #19661 too.

**Comment by Nickoriginal** [comment] 2021-08-07 12:06
Fixed in Firefox 91.1.0
