### ISSUE TITLE
[Bug]keyboard reappears after url entry - Swiftkey only

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#16668] opened 2020-11-20 07:26 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Latest Nightly
Swiftkey
Tap url bar
Type a url
Hit enter
Keyboard disappears then reappears
Newlyn loaded page has keyboard over it. 
Doesn't happen with Samsung stock keyboard. 
New behavior only started with this build
Might be related to #16628??? 

### Expected behavior

Keyboard shouldn't reappear

### Device information

* Android device: Galaxy A40
* Fenix version: today's 201119 17:01

**Comment by ale82to** [comment] 2020-11-21 13:14
I noticed this issue too so annoying

**Comment by ale82to** [comment] 2020-11-22 12:29
still happening so annoying

**Comment by miDeb** [comment] 2020-11-23 20:10
Happens for me with both Gboard and the stock Samsung keyboard. Device: Galaxy A50, fx nightly

**Comment by ebalazs-sv** [comment] 2020-11-26 11:48
I can reproduce this issue on the latest Nightly 11/26 with Pixel 2 (Android 9).
### Steps to reproduce:
1. Launch Fenix;
2. Tap the URL bar and visit a page (i.e. facebook.com);
3. Observe the keyboard after the page is loaded;

### Expected result:
The keyboard is not displayed.

### Actual result:
The keyboard is displayed after the page is loaded;

### Video:
![20201126_134514](https://user-images.githubusercontent.com/48799384/100347285-cb548280-2fed-11eb-8b57-aea4c53a1225.gif)

**Comment by eliserichards** [comment] 2020-11-30 23:57
Thanks so much for filing this!

@violasong this is the issue related to the thread that you posted 😄

**Comment by aviegdown** [comment] 2020-12-13 21:37
issue still able to reproduce when selecting **history link** for example 
![ezgif-6-1a7172bbcc91](https://user-images.githubusercontent.com/72583750/102024686-16301180-3dc6-11eb-9f3a-98be5f3c28e1.gif)

**Comment by Croman12** [comment] 2020-12-14 02:16
Seems fixed on the 12-12 build on my Xiaomi 9T on Android 10 (with SwiftKey). Thanks to all de developers!

**Comment by ale82to** [comment] 2020-12-14 03:43
absolutely NO FIXED for me I ve never seen a bug taking that long to be fixed 😷

**Comment by ebalazs-sv** [comment] 2020-12-14 07:08
Verified as fixed on Nightly 201214 05:03 (Build #2015781291) GV 85 from 12/14 with Pixel 2 (Android 9).

@ale82to Hi! Steps to reproduce the issue and a video will help us see if the issue is the same. Also, are you using the latest Nightly build? Thanks!

I will close the issue and remove the qa:needed label for now.

**Closed by ebalazs-sv** 2020-12-14 07:08 UTC
Labels: Feature:Search, S2, Skittle, eng:qa:needed, 🐞 bug

**Comment by ale82to** [comment] 2020-12-14 13:25
I tried both https://firefoxci.taskcluster-artifacts.net/RBwE1ixVQ4y_RuvH1kBqhw/0/public/build/arm64-v8a/target.apk
and nighlty from apk mirror both have the issue for me with swiftkey

**Comment by ekager** [comment] 2020-12-14 17:38
If you're still having issues please continue the discussion in https://github.com/mozilla-mobile/fenix/issues/16973
