### ISSUE TITLE
[Bug] Swipe to close tab feels bad

### ISSUE THREAD

**Issue by BubiBalboa** [mozilla-mobile/fenix#3606] opened 2019-06-22 16:56 UTC
## Steps to reproduce
Swipe a tab to the left or right to close it.

### Expected behavior
The tab should consider the speed with which it was swiped and have "momentum". A quick swipe of around 1/3 of the width should suffice to delete a tab.

### Actual behavior
The tab is hard to swipe away. It feels like a rubber band. You have to swipe at least 2/3 of the width to close a tab.

### Device information
* Android device: OnePlus6 
* Fenix version: 1.0.1925

**Comment by kbrosnan** [comment] 2019-06-23 05:11
Dupe of #3135

**Closed** 2020-08-27 00:40 UTC
Labels: 🐞 bug
