### ISSUE TITLE
Separate Top Sites toggle to only show Pinned Sites

### ISSUE THREAD

**Issue by Juan-132** [mozilla-mobile/fenix#26159] opened 2022-07-24 11:42 UTC
### What is the user problem or growth opportunity you want to see solved?
https://github.com/mozilla-mobile/fenix/issues/25739

I would propose for two Top Sites toggles in settings
* Top Sites (Pinned) 
* Top Sites (History) 

This way users have a choice. 

### How do you know that this problem exists today? Why is this important?
This behavior was present in earlier versions of Firefox. 
But changed by the developers (top sites now include history) 
Users hsve commented in the bug thread that they still value the choice, to disable history in top sites. 

### Who will benefit from it?
Users who value the customization option, to turn of history.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21101)

**Comment by delia-pop** [comment] 2022-07-28 16:51
@Juan-132 thank for reporting. I will mark this as feature request.

**Comment by Juan-132** [comment] 2022-07-29 09:50
@delia-pop thank you for your reply! 

Could you inform me what the process is for deciding on this feature request? (go/no-go) 

Would it be OK to develop a pull request to implement this as specified above?

**Comment by rocketsroger** [comment] 2022-08-22 21:44
Confirmed with @athomasmoz that we want to support an option for users to turn off history top sites.

**Comment by kbrosnan** [comment] 2023-01-21 03:44
Closing this out.

**Comment by delia-pop** [comment] 2023-01-27 11:25
Removing the QA Needed label since there is nothing to verify.

**Closed by delia-pop** 2023-01-27 11:25 UTC
Labels: feature request 🌟, eng:qa:needed, Feature:Shortcuts, qa-triaged
