### ISSUE TITLE
[Bug]: Search bar widget can't be resized vertically 

### ISSUE THREAD

**Issue by Athesis** [mozilla-mobile/fenix#25384] opened 2022-05-25 13:39 UTC
### Steps to reproduce

Tap and hold on widget until resizing border appears 

### Expected behaviour

Resizable to a single line

### Actual behaviour

Cannot be resized vertically 
![image1](https://user-images.githubusercontent.com/1258670/170275683-f8ef7d77-d715-42b3-93a8-5b2fef03e964.png)

### Device name

Sony Xperia 5 III 

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

100.3.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20562)

**Comment by SoftVision-LorandJanos** [comment] 2022-05-26 04:54
Hi @Athesis! Thanks for your report!
I wasn't able to reproduce your issue.

I don't have a Sony device but I tested it on some other devices with the build you mentioned:
- Samsung Galaxy Tab S3 (Android 9).
- Xiaomi Mi11 Lite (Android 11).
- Google Pixel 4 (Android 12).

I also tested with the:
- latest RC (101.1.0).
- latest Nightly 102.0a1 (2022-05-25T17:07:50.913223).


All with the same result.
Could you check if you reproduce it on the above mentioned builds?
Thank you!

**Comment by tcchawla** [comment] 2022-05-26 12:18
Hello @SoftVision-LorandJanos 

I faced the same issue, not being able to resize the widget vertically. I tested the latest build on the OnePlus 6 (Android 11).

Thank you!

**Comment by SoftVision-LorandJanos** [comment] 2022-05-26 13:07
I've made a mistake.
The widget screen was never supposed to be resizable vertically, only horizontally.
Here's the ticket with the implementation details: #201.
There are no specifications that say if it should or shouldn't be able to resize the bar, but I've talked to a Fenix Android developer who checked this matter from the code, and there were no signs that this behavior is supported.
If you want, you can open another ticket as a feature request that will give a chance for this detail to be implemented as well.
However since this behavior is not considered a bug, I will close this ticket. Thank you!

**Closed by SoftVision-LorandJanos** 2022-05-26 13:07 UTC
Labels: 🐞 bug, S3, feature:SearchWidget, needs:triage, qa-triaged
