### ISSUE TITLE
[Bug] tabs button stopped working in nightly

### ISSUE THREAD

**Issue by antonholmberg** [mozilla-mobile/fenix#5940] opened 2019-10-11 11:13 UTC
## Steps to reproduce
Try to press the tab button that goes to "home" or try to press the adress bar when a page is already opened, so not when you are already on the tab list

### Expected behavior
Should go to the tab list or allow you to type in the adress bar

### Actual behavior
Nothing happens.

### Device information

* Android device: OnePlus7 Pro
* Fenix version: Nightly 191010

**Comment by ekager** [comment] 2019-10-15 02:30
Dupe of #5984

**Closed by ekager** 2019-10-15 02:30 UTC
Labels: 🐞 bug
