### ISSUE TITLE
Kurdish Kurmanji is "Kmr" in mobile phone language dropdown list

### ISSUE THREAD

**Issue by amedcj** [mozilla-mobile/fenix#17924] opened 2021-02-08 22:04 UTC
Hello.
A few days ago i installed Firefox Android Nightly on my smartphone. It's language was English and i wanted to set it as Kurdish (Kurmanji dialect) but I didn't find it in the list. Then i saw "Kmr" and i selected it.
In this list all languages are shown with their names; English names and original names, like that:
Italiano
Italian

It is like that for all languages but there is no name for Kurdish Kurmanji only the language code "KMR".
It should be "the name of the language" instead of "the language code".

And for the name of the language, maybe we can do something like the name of Spanish.
Like that:
Kurdish (Kurmanji)
Kurdî (Kurmancî)

That will be very usefull for otehr Kurdish dialects too.

Please find attached two pictures.

![20210208_223219](https://user-images.githubusercontent.com/2435399/107287059-b4a4c000-6a61-11eb-8dec-5aa26def130e.jpg)
![Screenshot_20210208-223450_Firefox Nightly](https://user-images.githubusercontent.com/2435399/107287061-b53d5680-6a61-11eb-9275-4c5e5f72c1c9.jpg)

**Comment by LaurentiuApahideanSV** [comment] 2021-02-10 14:32
I can confirm the issue is reproducible on Firefox Nightly 2/10. The issue also occurs for Kaqchikel (caq) and Triqui (trs).

**Comment by amedcj** [comment] 2021-02-12 09:33
Hi.
When your choose Kurdish, that problem occurs für more languages: An, Cak, Co, Gn, Kmr, Oc, Sat, Su, Trs, Vec.
![Screenshot_20210212-100929_Firefox Nightly](https://user-images.githubusercontent.com/2435399/107751191-5f94d280-6d1d-11eb-9118-7f7b59d562bf.jpg)

And All other languages are shown with their language codes instead of Kurdish translation of their names.
Example, name of Turkish is like that in English:
Türkçe
Turkish

But it is like that in Kurdish (for name of Turkish and all other languages:
Türkçe
Tr
![20210212_103444](https://user-images.githubusercontent.com/2435399/107751363-99fe6f80-6d1d-11eb-8772-eb5266c35368.jpg)
![Screenshot_20210212-102352_Firefox Nightly](https://user-images.githubusercontent.com/2435399/107751365-9b2f9c80-6d1d-11eb-83f3-9e4464803316.jpg)

**Comment by Delphine** [comment] 2021-03-02 19:45
This seems to be the same issue as #12528

**Comment by amedyne** [comment] 2021-03-02 20:49
Closing this one and will track #12528 .

**Closed by amedyne** 2021-03-02 20:49 UTC
Labels: 🌐 L10N, 🐞 bug
