### ISSUE TITLE
FNX-13018 ⁃ [Bug] Tabs UI dismisses on scroll - Unable to select tab

### ISSUE THREAD

**Issue by ro-savage** [mozilla-mobile/fenix#12004] opened 2020-06-26 14:30 UTC
## Steps to reproduce
* Select and open second item on tab list (happens most often when one the 2nd tab in list)
* Open tabs list
* Top tab is hidden from view, and must scroll to view
* when scrolling the tab list is sometimes dismissed

### Expected behavior
* Tab UI should indicate that there is a tabs above the selected table
* Scrolling should always hit the 'top of list' bounce, and only when at the top of the list should a pull down dismiss.

### Actual behavior
* Tabs above the selected tab are hidden
* Scrolling to view the tabs above the selected can often dismiss tab list

### Device information
* Android device: Huiewi P20 Pro. Android 9.1.0
* Fenix version: 5.2.0

**Comment by ro-savage** [comment] 2020-06-26 14:35
![SVID_20200627_021806_1](https://user-images.githubusercontent.com/9244507/85868702-c4e39400-b81e-11ea-853e-999790d12631.gif)

**Comment by kbrosnan** [comment] 2020-06-27 21:48
Duplicate of #11042 which is fixed on Nightly builds

**Closed** 2020-08-11 05:26 UTC
Labels: Feature:Tabs, needs:triage, 🐞 bug
