### ISSUE TITLE
[Bug]: URL suggestions and autocomplete fail intermittently

### ISSUE THREAD

**Issue by Obscerno** [mozilla-mobile/fenix#20351] opened 2021-07-13 11:54 UTC
### Steps to reproduce

I have found this tends to happen more often the longer I use the app. I'll open it, it works, and then after a few pages the autocomplete stops working, and eventually I just stop getting suggestions at all.

So to reproduce, I'd say type into the search bar, if you get results, refresh the page, try again, and just keep going.

I have 28 tabs open too, just giving that info in case it's relevant.

### Expected behaviour

Suggestions should pop up, and autocomplete should fill in the rest of the url. This happens sometimes but not always.

### Actual behaviour

Sometimes just autocomplete doesn't work. An example of me trying to go to reddit.com/r/patientgamers:

![125446781-55b361e5-54af-4a64-b0b3-17f11fc59aae](https://user-images.githubusercontent.com/33399601/127899375-6fa8015a-6996-4ba0-9107-4ef37d64aa88.png)

And sometimes neither autocomplete or suggestions work:

![125446862-dc2717ee-68cb-485c-809b-45b438d3cb11](https://user-images.githubusercontent.com/33399601/127899579-67149107-b577-451d-acd6-50f93009c43e.png)

*Edit: I downsized these images for desktop display. Here's [original image 1](https://user-images.githubusercontent.com/33399601/125446781-55b361e5-54af-4a64-b0b3-17f11fc59aae.png), and [original image 2](https://user-images.githubusercontent.com/33399601/125446862-dc2717ee-68cb-485c-809b-45b438d3cb11.png).*

### Device name

moto g(8) power

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

91.0a1

**Comment by amedyne** [comment] 2021-07-30 15:29
@sorina can you validate if your team is seeing this problem and #20564 ?

**Comment by SoftVision-LorandJanos** [comment] 2021-08-02 10:41
Hi @Obscerno ! Thank you for you report!
I tried to reproduce the issue you described in a few configurations, but I couldn't reproduce. Since it was reproduced and logged by more people, I'm sure I miss something. I've tried to open as many tabs as possible, used the website mentioned above, and bugzilla.mozilla.org with many other sites accessed before re-typing the address and even after closed-restarted the apps.
Could I ask for a video of the issue? Or maybe if you have extra details that might help reproducing on other devices as well? @Miteirao , @marcel263 could you help here also? Thank you!

Firefox versions used:
- 90.1.2 (Release).
- 90.1.3 (Release).
- 91.0a1 (Nightly).
- 92.0a1 (Latest Nightly - 2021-08-02T05:08:16.189754).

Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Google Pixel 4 (Android 11).
- LG Nexus 5 (Android 6.0.1).

**Comment by Obscerno** [comment] 2021-08-02 16:50
Hi @SoftVision-LorandJanos! Yes here's a video of it in action:

https://user-images.githubusercontent.com/33399601/127895950-9729d19f-2197-43f2-9c22-03c2e84d6955.mp4

I wasn't able to capture the autocomplete actually working, because though it happens, it is rare.

During this test I disabled all add-ons, but I do use ublock and leechblock in my day to day.

Also, my default search engine is duckduckgo.

I can't think of any other details that might help, but if I do think of more I'll share them!

**Comment by ohhai** [comment] 2021-08-02 16:55
History autocompletion always working for me after Firefox restart (swipe it aside from the recent apps list in Android, then start again).

**Comment by Obscerno** [comment] 2021-08-02 17:08
@ohhai maybe you could provide a more useful video than me, if yours goes from working to not working.

> History autocompletion always working for me after Firefox restart (swipe it aside from the recent apps list in Android, then start again).

I've tried this, and restarting my phone, but neither works for me to reset to a state where autocomplete works. The only thing that seems to get it back to normal for me is time away from using the app. Like, in the morning it usually works properly, and by the time I've browsed a few pages it stops working again.

(Note that as far as I know waiting a long time isn't required to reproduce the bug, but it does temporarily make the bug go away, for me anyway)

**Comment by Obscerno** [comment] 2021-08-02 17:36
@SoftVision-LorandJanos one more thought: the issue with me isn't for the base url "reddit.com" but for the specific page "/r/patientgamers" that I visit all the time (and would normally get suggested to me). So maybe repeatedly refreshing some more deeply nested pages will give you better results?

Also, I don't get bookmarks suggested to me either, which I normally would (although they had recently started showing up at the very bottom of the list of suggestions, which was weird when it happened, before suggestions broke entirely). Maybe making a bookmark and checking for autocomplete on that will help reproduce?

**Comment by ohhai** [comment] 2021-08-02 18:00
@Obscerno 
> @SoftVision-LorandJanos one more thought: the issue with me isn't for the base url "reddit.com" but for the specific page "/r/patientgamers" that I visit all the time (and would normally get suggested to me). 

Do you mean that you still have history autocompletion for base urls?
For my case it seems breaking completely. Have all or nothing, in other words. (related only to history entries - still have suggestions from search engine, for example).
I can make video with it not working, but it would be not useful. I think. Will try to find the thing which breaks it.


@SoftVision-LorandJanos
Can we fetch any useful logs from browser when it fails? Using debugging by USB or something else.

**Comment by amedyne** [comment] 2021-08-02 18:46
@Obscerno Can you confirm if you have Autocomplete URLs set to ON?

**Comment by Obscerno** [comment] 2021-08-02 19:06
> Do you mean that you still have history autocompletion for base urls?

@ohhai yes I do!

> @Obscerno Can you confirm if you have Autocomplete URLs set to ON?

@amedyne yes I do have that set to on!

**Comment by ohhai** [comment] 2021-08-02 20:37
> > Do you mean that you still have history autocompletion for base urls?
> 
> @ohhai yes I do!

Hmm, so we might have different issues. However it gives us nothing at this step, I think.
Need steps for reproduce :(

Just in case: my config for "Search" settings page is following:
* Default search engine: google
* Disabled items:
-- show search engines
-- show voice search
-- show search suggestions
* Enabled items:
-- autocomplete URLs
-- show clipboard suggestions
-- search browsing history
-- search bookmarks
-- search synchronized tabs

Besides that, I have noticeable addition for reproducing.
Couple of hours ago I tried to do that, failed and left browser at the same tab filled with correct suggestions.
After these hours I took the phone and continued to play with URL bar staying on the same tab. And it broke shortly.
So, two assumptions here:
- timing might matter as already described
- seems like the only activity which affects it for me is URL bar editing - not another tabs opening / switching / closing, etc

**Comment by Obscerno** [comment] 2021-08-02 21:17
> Hmm, so we might have different issues.

Yeah seems like it. :/

I'll also provide my search settings just in case.

- Default search engine: duckduckgo
- Disabled items:
    - show search engines
    - show clipboard suggestions
    - search synched tabs
    - show voice search
    - show search suggestions
- Enabled items:
    - autocomplete URLs
    - search browsing history
    - search bookmarks

**Comment by Miteirao** [comment] 2021-08-03 03:17
Tonight I noticed that it's about time: I typed a known word and looked a while to a Olympic jump, then the suggestions came in after a long delay.
Now the question is to discover why some terms come instantly and others delayed.

**Comment by Obscerno** [comment] 2021-08-03 11:07
> Tonight I noticed that it's about time: I typed a known word and looked a while to a Olympic jump, then the suggestions came in after a long delay.
> Now the question is to discover why some terms come instantly and others delayed.

YES. It's exactly the same for me, I never noticed because I never tried waiting more than a few seconds. Now if only we could find a way to reproduce the issue. I wonder if size of history has something to do with it?

**Comment by Obscerno** [comment] 2021-08-03 14:27
I will add that waiting a long time only makes the suggestions load. The autocomplete does not fill when the suggestions finally come in.

**Comment by Mugurell** [comment] 2021-08-03 16:56
Can someone post a logcat for when this issue happens?
https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#reproducing-the-crash
(it's not necessary for the app to crash, there might be important details about slowdowns also)

**Comment by ohhai** [comment] 2021-08-03 19:41
@Obscerno 
> Yeah seems like it. :/

I realized another thing. Do you have base urls autocompletion right  _inside_  the url bar? If so, I have it always working too. The breaking thing is suggestion list  _below_  the url bar. Sorry, I should differentiate it.

As for waiting time influence, I see it as well. Seems depending on opened tabs number: bigger is slower.

Regarding logs, `adb logcat` prints nothing for me for some reason. `adb shell` and then `logcat` works fine. Device is not rooted.
Might be wroth mentioning at that wiki page.

These lines seem related, but search engine suggestions are disabled and synced tabs suggestions are not the topic and work strange - they appear after 6'th symbol entered in url bar
```
E/Metrics (23331): Unknown suggestion provider: mozilla.components.feature.awesomebar.provider.SearchEngineSuggestionProvider@989ab35
E/Metrics (23331): Unknown suggestion provider: mozilla.components.feature.syncedtabs.SyncedTabsStorageSuggestionProvider@8e5921f
```

All lines are here (warning, 12 MB): https://gist.github.com/ohhai/89d0a05de447094b5d5d45a09b7ba448/raw/97822dc7827e115769dcc1d265aefb4b509c545b/gistfile1.txt

**Comment by blatruwe** [comment] 2021-08-03 19:44
08-03 21:34:43.281 20052 20052 E glean/Dispatchers: Exceeded maximum queue size, discarding task
08-03 21:34:43.282 20052 20112 E glean/Dispatchers: Exceeded maximum queue size, discarding task
08-03 21:34:43.283 20052 20052 E Metrics : Unknown suggestion provider: mozilla.components.feature.awesomebar.provider.SearchEngineSuggestionProvider@59b843d

full dump here: https://pastebin.com/rwQ6GRuL

**Comment by Obscerno** [comment] 2021-08-03 20:22
Here's a log from me: https://gist.githubusercontent.com/Obscerno/d1603fb41ad9f9b00720fc4c08d262ae/raw/f92616d0e6d9b65fb2998b813eaf36521d4c4dbc/log.txt

**Comment by Mugurell** [comment] 2021-08-04 09:34
Thank you all for the help!

Just want to double check some scenarios that could hint about the issue:
- there is no issue with the network connection? Accessing any address works as expected?
- does temporarily changing the default search engine makes any difference?
- does enabling all search providers from `3 dot menu -> Search -> Address bar` makes any difference?
(Probably need keep this setup for more searches to ensure results consistency)

**Comment by Obscerno** [comment] 2021-08-04 11:20
I just want to specify, I have search suggestions disabled, the issue is with history suggestions. That said, here are my answers:

- Internet connection: no issue. All pages load as expected.
- Changing search engine: makes no difference.
- Enabling all search providers: do you mean "Show search engines"? If so, it makes no difference.
- Other visual slowdown: no, I don't notice any other slowdown.
- Multiple websites: it happens for every site as far as I can tell.
- Yes I use uBlock Origin regularly (though I disabled it for my test log) and also use the app DNS66.

**Comment by Obscerno** [comment] 2021-08-04 12:04
Another update: I just did a mass closing of tabs (I rarely close tabs, I just let them accumulate) and this sped everything up massively. Not only are history suggestions popping in quickly, but autocomplete (which has basically been dead) is working again.

@ohhai and @Miteirao what are your tab situations like?

**Comment by Obscerno** [comment] 2021-08-04 12:21
I've tried opening a ton of wikipedia tabs but I'm not getting any slowdown anymore. The old tabs had been marked as "inactive" (and we're shown in this very intrusive list that hid all of my active tabs, which is annoying btw), so that's why I deleted them.

I don't know if they have to be aged to the point where Firefox considers them inactive before causing issues, but I'll leave them open and cross my fingers that I get the bug again so I can keep helping debug it.

**Comment by Mugurell** [comment] 2021-08-04 13:34
@Obscerno I think the issue might be related to a specific website from the ones you had open before, one for which we are slow to load the favicon and we stall everything until that happens.
Could be the same cause for everyone.
I know it's a lot to ask but if someone has some this issue reproducing and some time it would be great to
- save all current tabs to a new collection
- load from that collection one by one the tabs, after each such load trying a new search
  - if the search results are instant, open the next tab for the collection
  - if the search results are empty for even a second we know the last opened tab (and it's website is at culprit)
  
One thing I saw in the video from https://github.com/mozilla-mobile/fenix/issues/20351#issuecomment-891175855 is that the issue starts at 0:02. The suggestions do not change according to the text input. So speculating further I think the website we'd search for contains "red" in title or url.

**Comment by Obscerno** [comment] 2021-08-04 14:01
If I get the issue again I'll definitely give you a tab breakdown.

> One thing I saw in the video from [#20351 (comment)](https://github.com/mozilla-mobile/fenix/issues/20351#issuecomment-891175855) is that the issue starts at 0:02. The suggestions do not change according to the text input. So speculating further I think the website we'd search for contains "red" in title or url.

Regarding this, if I had typed 'red' in that video and waited, eventually the correct suggestions would have popped up after a long delay. At the time I recorded the video I didn't know about the timing issue, so I didn't wait for them to pop up. I can't test it now, but it happened for every input not just the reddit ones.

**Comment by ohhai** [comment] 2021-08-04 21:01
As for questions in https://github.com/mozilla-mobile/fenix/issues/20351#issuecomment-892512842 :

- network connection is fine
- switching default search engine and enabling all search providers - don't not fix it at least
- no other visual slowdown (however the only exising movement at that time should be suggestions filling and it just absent)
- happens with multiple websites. Works like "all or nothing"
- I use ublock addon. Tried to disable it, doesn't help.

Also I add +1 to @Obscerno - my issue also is with history suggestions, nothing with suggestions from search engine.

As for tabs number: I have 70 for now and for sure I saw its big influence at suggestions speed (when used previous stable FF builds). Also created this: #18096
However when the subject issue is "fixed" after FF restart (might need to restart phone) - history suggestions load fast and smooth.

Regarding collections and favicons: OK, and I also disabled this: http://kb.mozillazine.org/Browser.chrome.site_icons

**Comment by ohhai** [comment] 2021-08-08 21:46
Disabling favicons (setting browser.chrome.site_icons to false) doesn't help.
I have some steps for reproduce which also show favicons as unrelated, maybe.
Just in case: all of this is about history suggestions absence - that suggestions which are NOT inside URL bar.

• Close all tabs. Counter on the tabs button shows 0.
• Restart browser
• Enter someurlpart1 to URL bar, ensure that multiple suggestions appear
• Lock phone and leave for 1 hour
• Unlock phone, erase* someurlpart1 and enter different someurlpart2* (which was visited before as well)
• Observe absence of suggestions
• Enter someurlpart1 again
• Observe absence of suggestions
• Wait 5 min, ensure no suggestions appear after this

*: if just edit someurlpart1 (not erasing completely), then suggestions do not disappear.

FF Nightly version:
92.0a1 (Build #2015826779)
AC: 92.0.20210808010301, 89d8b40587
GV: 92.0a1-20210807214822
AS: 81.0.1

**Comment by ohhai** [comment] 2021-08-08 22:42
I will not edit previous post, but have to add an interesting point.
I did wait 15 minutes instead of 5 in last step and suggestion list appeared!

Now just don't understand. This list fills instantly when it works fine after browser restart.
The phone is LG V20, uses Snapdragon 820 + 4 GB RAM

**Comment by Mugurell** [comment] 2021-08-25 15:08
Hello,
We tried to reproduce and investigate more what may be the issue but we need some help from the ones who can reproduce this.

This is an apk which will record more logs around the feature - https://drive.google.com/file/d/1KQrxMaUid7ExhdvCevD7IB2-9pQIyAj1/view
It contains [this](https://github.com/mozilla-mobile/android-components/pull/10879/files) and [this](https://github.com/mozilla-mobile/fenix/pull/21007/files) changes on top of the current Nightly code.
A logcat from this apk would [look like this](https://paste.mozilla.org/siAkO3KP/raw) and allow for a deeper understanding of where the bottleneck is.

The scenario that we need help with:
- install the above apk
- sync the firefox profile to this app also (with at least all bookmarks, history and open tabs checked) to ensure an as similar as possible app setup
- extract the logs from the device when this issue is encountered (https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#reproducing-the-crash).

**Comment by dbenjaminmiller** [comment] 2021-08-29 17:08
Having the same issue. I've never had synced tabs enabled, for whatever that's worth. Can try getting a log later.

**Comment by Mugurell** [comment] 2021-08-30 16:44
Thank you all for the help!

Seems like there is an issue with the icons for search suggestions to be shown though it's still not clear what the exact conditions for this are other than that indeed the problems compound with the more rapid searches made.
We are waiting at max 12 seconds to download a favicon, if more and more favicons  are needed but we are slow to download them that number can quickly increase)
In the interim we can show a generated icon sooner rather than allow waiting for even minutes.

Here is an apk with the logs from above and the patch from https://github.com/mozilla-mobile/android-components/pull/10754 - https://drive.google.com/file/d/1dIoicZiDOhOdQLgtIQhlSATzZ_q8u-Di (max 12 seconds timeout for each icon).

Here is an apk with the logs from above and the patch from https://github.com/mozilla-mobile/android-components/pull - https://drive.google.com/file/d/1esdD8l5kVa53bBTas_nkt75eQs1A-L0s (max 12 seconds timeout for all icons from a provider).

Would be great if someone which has this issue reproducing would try first the first apk to confirm the general approach works and maybe then the second apk to see if there's even an greater improvement.

**Comment by ohhai** [comment] 2021-08-30 17:46
@Mugurell 
Last apk found some leaks for me. Previous versions did not show this (same device):
https://gist.github.com/ohhai/c30be5bc25742af31b8819d8423e26e0

**Comment by Mugurell** [comment] 2021-08-31 06:36
@ohhai This is something that we'll need to address but should not impact the functionality we need tested. This leak detection is only available in debug build like the ones I provided. Can be toggled off in app settings -> "LeakCanary".

**Comment by ohhai** [comment] 2021-09-03 20:26
@Mugurell
This is log for apk with "max 12 seconds timeout for each icon", but please verify that it's this version. I tried to look at "Settings" -> "About Firefox Preview", but it shows me same for both apks from https://github.com/mozilla-mobile/fenix/issues/20351#issuecomment-908501913
Hope I got it correctly that this apk has higher probability to fix something, than "max 12 seconds timeout for all icons from a provider" version.
Still reproduces. Phone is in "airplane mode", entered text at ~23:08:30, results from synced tabs appear after ~5.5 minutes, results from history appear after ~30 seconds more.
https://gist.github.com/ohhai/0e7c93b33a58af5bb11c0edc54672bb2

**Comment by Mugurell** [comment] 2021-09-10 15:44
Thank you all for the help!

Please be sure we are trying to find the root cause and fix this. The data provided until now helped indentifying a larger area of code that may impact this but it seems like there is still one issue with the execution being hanged, not clear at the moment how and why.

As a one big effort can someone which has this issue reproducing on any of the debug apks from https://github.com/mozilla-mobile/fenix/issues/20351#issuecomment-908501913 can provide a bugreport - https://developer.android.com/studio/debug/bug-report to us?

The scenario we're looking for is to just get into the state where suggestions are delayed as reported above and then take a bugreport either from Developer Settings either from terminal then share the resulting zip with us.

Please note that the data there would contain information about all your running applications and the state of the device.
No personal information or data from the apps but the state they are in.
As such it would be great if someone could help us with this privately and not posting the file publicly. One can just email me at plingurar @ mozilla . com

**Comment by ohhai** [comment] 2021-09-15 20:00
@Mugurell 
Done, sending to email in progress.

**Comment by Mugurell** [comment] 2021-09-16 16:48
Thank you very much for helping on email with bugreports and generally on this ticket!
The suggestions are definetly slow and I think we're closing in on what may be the cause(es)!

One potential cause for this was identified in https://github.com/mozilla-mobile/fenix/issues/21291 and is already being worked on.

Another potential cause is our code for downloading icons with many requests possibly slowing down each other.
To test this last scenario here - https://drive.google.com/file/d/1rMIIDQJygifYX3Jbu7quayZ15hvdH7OS/view?usp=sharing is a new apk with the same logs from https://github.com/mozilla-mobile/fenix/issues/20351#issuecomment-905590775 and with the `HttpIconLoader` and `DataUriIconLoader` from here https://github.com/mozilla-mobile/android-components/blob/71e124a5dbafffb800168ea615fdbc54d7398f50/components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt#L90-L91 disabled.

For me this means almost instant suggestions and if confirmed to "fix" the issue with slow suggestions for others then we'd know where to focus our attention.

**Comment by ohhai** [comment] 2021-09-18 09:09
@Mugurell 
Now can't reproduce it! Will try more, since it did not fail instantly for me. Same checks from other guys will be very valuable.

Suggestions are really fast now. Could it be so for regular builds?

If icons are mandatory for this list, could they load at last steps? I mean a possible case when firstly the suggestion list is shown, and then its icons are updated after they are loaded. This will give much faster feedback after user input.

**Comment by blatruwe** [comment] 2021-09-19 19:06
@Mugurell 
With the latest build, the suggestions are indeed really fast. At the moment I couldn't reproduce the issue with this 'fix'.

**Comment by spinda** [comment] 2021-10-18 20:18
I've been dealing with this problem daily for... one? two years now? I always assumed it was something uniquely broken about my Firefox profile, so seeing progress toward a fix is just amazing. I can reproduce this consistently, so please let me know if there's any testing or diagnostics that I can help with.

**Comment by Mugurell** [comment] 2021-11-18 11:56
Hello and sorry for the wait.
A fix for this has been merged in Nightly. Overall suggestions should be significantly faster. 
Thank you all for helping!

Though we weren't able to reproduce I'll keep the ticket open a bit more for feedback on whether others can confirm an improvement or there is an issue still.

**Comment by blatruwe** [comment] 2021-11-23 20:25
I have been using the latest nightly for a few days. Suggestions are now definitely better. Didn't experience any hanging so far.

**Closed** 2022-01-28 04:56 UTC
Labels: 🐞 bug, Feature:Search, Feature:Toolbar, needs:triage

**Comment by mavit** [comment] 2022-01-28 08:01
I still experience these symptoms with Firefox 96.2.0.
