### ISSUE TITLE
[Bug] Crash after taking scrollshot of youtube comments

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#15255] opened 2020-09-21 02:21 UTC
## Steps to reproduce
Go to the comment section of a youtube video and take a scrollshot.

### Expected behavior
I can take a scrollshot with no problem

### Actual behavior
After a while the app crashes. Stacktrace:

f6dda3cc-a555-4d42-b0b0-d5afd13160de
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.ArrayIteratorKt.checkParameterIsNotNull, parameter e1
----
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.ArrayIteratorKt.checkParameterIsNotNull, parameter e1
	at kotlin.jvm.internal.ArrayIteratorKt.throwParameterIsNullException(ArrayIterator.kt:5)
	at kotlin.jvm.internal.ArrayIteratorKt.checkParameterIsNotNull(ArrayIterator.kt:1)
	at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector$CustomScrollDetectorListener.onScroll(Unknown Source:2)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:726)
	at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector.handleTouchEvent$browser_toolbar_release(BrowserGestureDetector.kt:4)
	at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.onInterceptTouchEvent(BrowserToolbarBottomBehavior.kt:2)
	at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.onInterceptTouchEvent(BrowserToolbarBottomBehavior.kt:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.performIntercept(CoordinatorLayout.java:13)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onInterceptTouchEvent(CoordinatorLayout.java:3)
	at android.view.ViewGroup.checkInterception(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2773)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2919)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2919)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2919)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2919)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2919)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2919)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2919)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2919)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2919)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:654)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1988)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4146)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:600)
	at android.view.View.dispatchPointerEvent(View.java:13791)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5888)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5683)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5127)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5180)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5146)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5303)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5154)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5360)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5127)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5180)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5146)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5154)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5127)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8035)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7986)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7940)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8228)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:233)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:215)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8152)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8271)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
	at android.view.Choreographer.doCallbacks(Choreographer.java:875)
	at android.view.Choreographer.doFrame(Choreographer.java:769)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8347)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

### Device information

* Android device: Huawei Nova 6 (Android 10)
* Fenix version: Nightly 200920 06:02 (Build #2015764979)
AC: 60.0.20200918190104, d30fc6970
GV: 82.0a1-20200918094500
AS: 61.0.13

**Comment by mobd** [comment] 2020-09-21 02:24
I tested this with the google search fixer enabled as well as disabled, both crashed the app

**Comment by kbrosnan** [comment] 2020-09-21 17:52
Duplicate of https://github.com/mozilla-mobile/android-components/issues/8356

**Closed by kbrosnan** 2020-09-21 17:52 UTC
Labels: needs:triage, 🐞 bug
