### ISSUE TITLE
[Bug] Tab turns white and becomes unusable

### ISSUE THREAD

**Issue by evilpie** [mozilla-mobile/fenix#13866] opened 2020-08-16 12:47 UTC
This happens about once a day for me, but I haven't yet found reliable steps to reproduce. This has been happening intermittently for a few weeks now. I think this might happen more often when switching away from Fenix and back, but I am not sure.
What happens is that the whole webpage turns white.

1. Reloading does not help
2. Going back or forward doesn't help
3. Opening a new tab and going back to the broken tab *makes it work*!

### Device information

* Android device: Galaxy S8 (Android 9)
* Fenix version: Nightly 200815

**Comment by hwinnemoe** [comment] 2020-08-16 13:41
Sounds related to/duplicate of #12593

**Comment by liuche** [comment] 2020-08-18 01:53
We're working on a fix for the white tab, see #12593

**Closed by liuche** 2020-08-18 01:53 UTC
Labels: needs:triage, 🐞 bug
