### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xucaen** [mozilla-mobile/fenix#25422] opened 2022-05-28 03:27 UTC
### Steps to reproduce

Go to website and start entering a form
Accidentally swipe which causes you to navigate to previous page or to some other page.
Swipe again to go back to the form in the form is empty

### Expected behaviour

I expect my form to remain filled in if I accidentally navigate away from the page

### Actual behaviour

The forms getting erased when I go back to it.

### Device name

g moto

### Android version

11

### Firefox release type

Firefox

### Firefox version

100

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20583)

**Comment by DavidJCobb** [comment] 2022-06-05 16:09
Duplicate of #9039 and #12731.

**Closed** 2022-12-11 04:49 UTC
Labels: 🐞 bug, needs:triage, wontfix
