### ISSUE TITLE
[Bug] When the toolbar-on-top is visible on sites with fixed content at the top of the page (e.g. topbars, navbars), there is a 1px gap between the site content and the browser toolbar

### ISSUE THREAD

**Issue by DavidJCobb** [mozilla-mobile/fenix#14845] opened 2020-09-08 08:46 UTC
## Steps to reproduce

1. Configure Firefox's toolbar to show on the top.
2. Go to a mobile website with fixed-position content at the top of the page, such as [reddit](https://www.reddit.com/r/skyrimmods/comments/infu2z/a_question_about_the_iscasting_condition_function/) or [YouTube](https://m.youtube.com/watch?v=tv7yHglIDsc).
3. Scroll down to the comments; the browser toolbar will auto-hide when you do. If you are using the YouTube test case, expand the comments.
4. Scroll up slowly, such that the browser toolbar becomes visible. Continue to scroll up, and watch the boundary between the browser toolbar and the page's fixed-position topbar.

### Expected behavior

The top edge of the page's fixed-position content should be exactly flush with the bottom edge of the browser toolbar. It should not be possible to see any of the content "underneath" it.

### Actual behavior

There is a single-pixel gap between the top edge of the page's fixed-position content and the bottom edge of the browser toolbar. It is possible to see content beneath the fixed-position content, i.e. page content on reddit and the comments pane on YouTube.

### Device information

* Android device: Galaxy A50
* Fenix version: 80.1.2.

**Comment by DavidJCobb** [comment] 2020-09-08 08:48
reddit test: page content, including the post title, is visible:

![Screenshot_20200908-103847_Firefox](https://user-images.githubusercontent.com/831497/92454343-b3c0e700-f1c0-11ea-826c-12ddac229b8e.jpg)

Youtube test: comment content (in this case, the rating UI) is visible:

![Screenshot_20200908-103929_Firefox](https://user-images.githubusercontent.com/831497/92454351-b4f21400-f1c0-11ea-9141-2df0b3bce750.jpg)

**Comment by DavidJCobb** [comment] 2020-09-08 11:21
Ah -- I should've submitted this as a web content issue report. Apologies.

**Comment by Diana-Rus** [comment] 2020-09-08 11:54
Reproducing issue on Nightly 9/8 with
- Samsung Galaxy S9 (Android 8)
- Google Pixel 3XL (Android 9)

Note:
- It also happens when the toolbar is positioned at the bottom of the browser
- It's visible when having dark theme applied to the browser see 

<details closed><summary>screen</summary>

![Screenshot_20200908-145207_Firefox Nightly](https://user-images.githubusercontent.com/49859863/92473216-14611b80-f1e3-11ea-9616-2f2fce5059d7.jpg)
</details>

**Comment by Mugurell** [comment] 2020-09-08 12:01
Closing as duplicate of https://github.com/mozilla-mobile/fenix/issues/10598
Please continue the discussion here.

We have a GV ticket for this - https://bugzilla.mozilla.org/show_bug.cgi?id=1648079.

**Closed by Mugurell** 2020-09-08 12:01 UTC
Labels: Feature:Browsing, Feature:Toolbar, S2, b:web-content, 🐞 bug
