### ISSUE TITLE
Go back from a tab to home screen should close the tab

### ISSUE THREAD

**Issue by meson11** [mozilla-mobile/fenix#17204] opened 2020-12-24 08:17 UTC
the last back action in a tab is to return to the home screen, but the tab keeps open.  here it is very annoying to have to close the tab manually. i understand, that if the tab closes because you go back unintended, you may came back not so easily. may be a close tab warning, a back to closed tab popup or an option to chose the behavior would be nice.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9219)

**Comment by cathodoluminescence** [comment] 2021-01-13 18:36
If this behaviour is intentional, please add the option to change it to the "Tabs" settings menu.

As of right now, I build up a large tabs list within short time, often with multiple tabs of the same page.

**Comment by nikunjbhatt** [comment] 2021-02-12 08:23
Also, after closing a tag or returning back to the home screen by pressing "back" button or through gesture, I have 2 suggestions:
1. On the home screen, show a button "Undo close tab" or "Reopen last closed tab". OR
2. Show a toast or floating message for a few seconds after closing tab or coming back to the home page having button as "Undo close tab" or "Reopen last closed tab" or "Restore last closed tab".

**Comment by meson11** [comment] 2021-02-12 08:30
@nikunjbhatt I would go with your second suggestion, because this behaviour already exists when you close a tab regularly.

**Comment by nikunjbhatt** [comment] 2021-02-12 10:47
#17551 seems same/similar to / duplicate of this.

**Comment by cbwee** [comment] 2021-03-09 01:13
>here it is very annoying to have to close the tab manually. i understand, that if the tab closes because you go back unintended, you may came back not so easily. may be a close tab warning, a back to closed tab popup or an option to chose the behavior would be nice.

It is also very annoying to me, but it happened to me only if
1.  I search something in the address bar first,
2.  open the search results, choose "Open link in new tab",
3.  close the search results page.

If I keep the search results page opened, the new tab would be closed after the back button is pressed.

But keeping that search results opened is still not the solution, since when I opened multiple search results in new tabs, if I press the back button to close the new tab, it always goes back to the search results page, instead of going to the tab which is above it in the tab list.

To me, it would be better to just close the tab after the back button is pressed, and show a "Tab closed / Undo" popup if needed.

**Comment by rafaeldrs** [comment] 2021-05-05 08:34
Any news about this? I find this behaviour extremely annoying

**Comment by boek** [comment] 2023-01-27 23:47
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813262

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-27 23:47 UTC
Labels: feature request 🌟, needs:UX-feedback
