### ISSUE TITLE
"Send all tabs" doesn't give any feedback

### ISSUE THREAD

**Issue by KopfKrieg** [mozilla-mobile/fenix#19380] opened 2021-05-04 17:21 UTC
### What is the user problem or growth opportunity you want to see solved?

If a single tab is sent using the "send to device" function I get a nice toast-like message which confirms that the tabs were sent successfully (or not, in case of a problem).

However, if I use the "send all tabs" function (same for multiple selected tabs) I won't get any feedback. The tabs get sent to my other device, and that's it. No confirmation, nothing.

So, please streamline the UI/UX for sending tabs, it should work the same no matter if I only send a single tab, multiple, or maybe all tabs. Also, from a UX point-of-view feedback if sending the tabs was successful is absolutely required.

### Who will benefit from it?

All users that use Firefox Sync.

**Comment by jonalmeida** [comment] 2021-05-04 19:22
Duplicate of https://github.com/mozilla-mobile/fenix/issues/19182

**Closed by jonalmeida** 2021-05-04 19:22 UTC
Labels: needs:triage
