### ISSUE TITLE
[Bug] three dot menu in bookmarks page does not reappear after deselecting in multi select

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13038] opened 2020-07-28 19:21 UTC
## Steps to reproduce
Open bookmarks
Open multi select by long tapping an item
Select and deselect another item

### Expected behavior
Three dot bar disappear during multi select reappears

### Actual behavior
It does not reappear
![Screenshot](https://user-images.githubusercontent.com/33252312/88711238-83077f80-d135-11ea-89a2-3a7ca956c550.png)UNITO-UNDERSCORE!20200729-005008!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by person808** [comment] 2020-07-29 00:00
Was able to reproduce on latest master (Android 10)

**Comment by person808** [comment] 2020-08-06 17:59
I'm actually going to close this since #13318 contains the behavior we actually want.

**Closed** 2020-08-28 23:08 UTC
Labels: Feature:Bookmarks, sourpatch, 🐞 bug
