### ISSUE TITLE
[Bug] Tracking protection breaks api.whatsapp.com

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#8122] opened 2020-02-05 19:20 UTC
## Steps to reproduce
go to google images and click on any image and share it with whatsapp like so:
![Screenshot_20200206-004648](https://user-images.githubusercontent.com/33252312/73874984-5b9dbd00-484c-11ea-8cce-adee2249bcc0.png)

it will open api.whatsapp.com
### Expected behavior
the site works  with/without tracking prot.
### Actual behavior
Its completely broken
![Screenshot_20200206-004654](https://user-images.githubusercontent.com/33252312/73875001-65272500-484c-11ea-99e2-152c5e553cee.png)

### Device information

* Android device: Asus Zenfone m1
* Fenix version: Nightly 200204 18:00 (Build #20351804)
30.0.0, c0b80f6b6
GV: 74.0a1-20200203085242

**Comment by softvision-miralobontiu** [comment] 2020-11-02 13:34
I was not able to reproduce this issue on the 11/2 Nightly build using a Google Pixel (Android 10).
@s-ankur please retest on the latest build.
Thank you!

**Comment by s-ankur** [comment] 2020-11-02 15:56
Yes seems to be fixed.

**Comment by Amejia481** [comment] 2020-11-02 16:06
Looks like we could close this one, please feel free to reopen if needed!

**Closed by Amejia481** 2020-11-02 16:06 UTC
Labels: Feature:TrackingProtection, b:etp, 🐞 bug
