### ISSUE TITLE
FNX3-17162 ⁃ Long pressing the address bar should not copy link

### ISSUE THREAD

**Issue by ReekyMarko** [mozilla-mobile/fenix#3615] opened 2019-06-23 15:32 UTC
_I think this should be done the same way as in fennec, with options "paste and go", "paste", "copy address" etc opening up on long press_

**### This ticket will just address removing the long press copy function.**

**Comment by dishanrajapaksha** [comment] 2019-06-23 16:14
I agree. Default copy would replace an address already in the clipboard too.

**Comment by vesta0** [comment] 2019-07-02 05:51
Perceived performance study suggests that users find this behaviour counter intuitive and in some cases they may inadvertently lose their clipboard content.

**Comment by yoasif** [comment] 2019-07-02 06:10
Ouch. Is this basically a dupe of https://github.com/mozilla-mobile/fenix/issues/3615?

**Comment by cadeyrn** [comment] 2019-07-02 06:19
@yoasif: This _is_ #3615. 😉

**Comment by yoasif** [comment] 2019-07-02 06:57
Even more amusing.

**Comment by softvision-miralobontiu** [comment] 2019-07-17 08:53
Verified that long-tapping on the URL bar doesn't copy the link.
Tested on the latest Nightly build 190717 (#11980613) with Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab A6 (Android 5.1.1), and HTC 10 (Android 8), and on the latest Nightly build 190717 (#11980614) (aarch64) with Nexus 6P (Android 8.1.0).

**Comment by tom-james-watson** [comment] 2019-07-17 08:56
Just looking at the referenced commit - it seems like all that has been done is to remove the copy functionality. The point of the original issue was that long-pressing the URL bar should function similar to how it does in normal Firefox Android - a popup menu with various options should appear instead of defaulting to copy.

Which would mean this shouldn't be closed yet?

**Comment by vesta0** [comment] 2019-07-17 18:26
As noted in the description, this ticket will just address removing the long press copy function based on results from a recent user study. 

New functionality regarding Paste and Go will be addressed later on in this bug #2089

**Comment by andreicristianpetcu** [comment] 2019-07-17 19:50
<img width="278" alt="workflow_2x" src="https://user-images.githubusercontent.com/922368/61406741-24ce7c80-a8e5-11e9-947a-d5d9cd336c1b.png">
I'm terribly sorry for being this xkcd person but this totally broke my workflow and the other ticket seems about paste/paste & go, not about copy.

**Comment by andreicristianpetcu** [comment] 2019-07-17 20:00
I hope you can find a simpler way for me to copy this address. https://github.com/mozilla-mobile/fenix/issues/4133

**Comment by yoasif** [comment] 2019-07-17 22:25
> New functionality regarding Paste or Paste and Go will be addressed later on in this bug #2089

This ticket wasn't about paste though, it was about the context menu that should appear when long pressing an existing URL in the address bar. Can this be reopened, or is this Fennec parity item not being considered @vesta0?

**Comment by vesta0** [comment] 2019-07-18 14:54
@andreicristianpetcu and @yoasif long pressing on an existing currently brings up a context menu with open/copy/cut/paste/etc. Would you please try again and let me know what is specifically broken for you, ideally with a screencap? Thanks!

**Comment by vesta0** [comment] 2019-07-18 14:56
The other Fennec context menu (paste & go, paste, copy address, add page shortcut) will be considered in this ticket #2089

**Comment by nahuhh** [comment] 2019-07-18 15:09
In the attached video I am holding on the address bar - nothing happens. (Previously it would copy the url)
After I lift my finger off of the screen, the url autosuggest screen opens. Still no contact menu
It is only on this screen that I can tap-hold the url to access the context menu.

In a nutshell, while viewing a website, you cannot tap-hold on the url bar. It does nothing  
![20190718_110041](https://user-images.githubusercontent.com/50635951/61468474-5aa64c00-a94b-11e9-8219-cf500dca887d.gif)

**Comment by vesta0** [comment] 2019-07-18 15:14
Thanks for clarifying!

All the long press options will be addressed in #4155 

Tapping on the nav bar and having the open/copy/cut/paste/etc should work today.

**Comment by djc** [comment] 2019-07-26 08:52
@vesta0 without #4155 implemented, this removal feels like a significant step back in usability for the Nightly audience. Maybe this removal could be reverted until the new functionality lands?

**Comment by ReekyMarko** [comment] 2020-08-12 11:16
Is this another accidental reopen? This was addressed ages ago

**Comment by nahuhh** [comment] 2020-08-12 11:38
Appears to be

**Closed** 2020-08-12 15:55 UTC
Labels: E1, Feature:Toolbar, eng:qa:verified, should
