### ISSUE TITLE
about change screen orientation

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#7167] opened 2019-12-14 02:11 UTC
`updateOrientationState(lock) {
        if (!this.video.mozOrientationLockEnabled) {
          return;
        }
        if (lock) {
          if (this.video.mozIsOrientationLocked) {
            return;
          }
          let dimenDiff = this.video.videoWidth - this.video.videoHeight;
          if (dimenDiff > 0) {
            this.video.mozIsOrientationLocked = this.window.screen.mozLockOrientation(
              "landscape"
            );
          } else if (dimenDiff < 0) {
            this.video.mozIsOrientationLocked = this.window.screen.mozLockOrientation(
              "portrait"
            );
          } else {
            this.video.mozIsOrientationLocked = this.window.screen.mozLockOrientation(
              this.window.screen.orientation
            );
          }
        } else {
          if (!this.video.mozIsOrientationLocked) {
            return;
          }
          this.window.screen.mozUnlockOrientation();
          this.video.mozIsOrientationLocked = false;
        }
      },`

these code from firefox desktop videocontrols.js
maybe can set an option when video on fullscreen change orientation or not

**Comment by lindongbin** [comment] 2019-12-14 02:23
Bad experience
https://i.imgur.com/aUjbUO7.mp4
https://i.imgur.com/RlgG5GF.mp4
https://i.imgur.com/RNSYHwx.mp4

**Comment by NotWoods** [comment] 2019-12-14 22:14
Duplicate of #5771. We plan to eventually use the correct orientation but we need GeckoView to supply the video aspect ratio for that. For now we use the user's device rotation settings so that you can choose to rotate rather than being locked to landscape.

**Closed by NotWoods** 2019-12-14 22:14 UTC
Labels: 🌟 feature request
