### ISSUE TITLE
[Bug] Flag emoji not displaying correctly

### ISSUE THREAD

**Issue by neekless** [mozilla-mobile/fenix#5628] opened 2019-09-27 02:02 UTC
## Steps to reproduce
Go to any page that displays country flag emoji

### Expected behavior
Flag emoji displays correctly

### Actual behavior
![Screenshot_20190927-095722](https://user-images.githubusercontent.com/22426822/65736508-b408c500-e0ca-11e9-8af0-e9a2de461e72.jpg)
Top: fenix
Bottom: brave

This happens on fennec as well

### Device information
* Android device: Pixel 2xl Android 9
* Fenix version: "Nightly 190926 18:01" (Build #12691822)
📦: 14.0.1, 81385d712
🦎: 71.0a1-20190923094800

**Comment by mcarare** [comment] 2019-09-27 13:24
I cannot reproduce this on Fenix or Fennec with Huawei P10 - Android 9. The flags are rendered correctly.

**Comment by neekless** [comment] 2019-09-27 13:51
Might be due to me using the JoyPixels emoji set. I will try again later with the default set.

**Comment by neekless** [comment] 2019-09-28 01:16
I can confirm that this issue doesn't happen with the default emoji set on my phone and only occurs when the emoji set is changed (I did it using the JoyPixels magisk module).
I guess this is similar to https://github.com/mozilla-mobile/fenix/issues/5417.

I've also read https://bugzilla.mozilla.org/show_bug.cgi?id=1505650#c10 and while I still think this should be fixed (as chromium-based browsers have no problem displaying them), I understand this is low priority. I will leave this open but feel free to close if necessary.

**Comment by ekager** [comment] 2019-10-02 03:29
Thanks for the followup! I commented in https://github.com/mozilla-mobile/fenix/issues/5417 with this issue so we can track those problems there and close this ticket

**Closed by ekager** 2019-10-02 03:29 UTC
Labels: P5, needs:STR, 🐞 bug

**Comment by softvision-miralobontiu** [comment] 2020-03-11 15:04
Removing the needs:STR due to the [comment](https://github.com/mozilla-mobile/fenix/issues/5628#issuecomment-537319929) above.
