### ISSUE TITLE
Search suggestions crowd out history suggestions

### ISSUE THREAD

**Issue by callahad** [mozilla-mobile/fenix#1161] opened 2019-03-23 09:55 UTC
### Why/User Benefit/User Problem
When typing into the address bar, I'd like to see both search suggestions and suggestions from my own browsing history, but the search suggestions are massive and crowd out any suggestions from my local history.

### What / Requirements
Display search suggestions more compactly so that they can coexist with local history suggestions.

### Acceptance Criteria (how do I know when I’m done?)
* It's possible to see at least one history result and one search suggestion at the same time.

Here's a comparison screenshot between Fenix (left) showing 4 search suggestions and Reference Browser (right) showing 10 search suggestions _and_ 3 history suggestions:

![](https://user-images.githubusercontent.com/24193/54864619-a5bfa200-4d51-11e9-9122-ef97b17692a7.png)

**Comment by callahad** [comment] 2019-03-23 10:19
Related to #479

**Comment by pocmo** [comment] 2019-03-25 12:23
FYI: PR #1137 limited the search suggestions we show to 3. But that's only an interim "solution" to make it a little bit better.

**Comment by Verdi** [comment] 2019-03-27 00:14
I think the UX team is agreed that the small suggestion "chicklets" is not what we want. Limiting the number suggestions is probably the right thing to do.

**Comment by mheubusch** [comment] 2019-04-07 11:52
@Verdi can you specify the number of suggestions or other criteria for dev for this?

**Comment by mheubusch** [comment] 2019-04-12 15:40
@Verdi Where will specs be delivered for eng? In  this issue or  another one?

**Comment by Verdi** [comment] 2019-04-12 22:26
@mheubusch I'll add everything here. I spoke with Mike Connor about this and we were thinking there might be something to do besides a single, hard-coded number of search suggestions. I'll have to discuss with engineering.

**Comment by Verdi** [comment] 2019-04-30 20:45
Let's keep the 3 search suggestion limit that we're currently doing. I think that's the best trade-off (currently available) between suggestion usefulness (diminished beyond 3) and history suggestion visibility while the keyboard is up.

**Comment by buttercookie42** [comment] 2019-08-19 07:01
> I think the UX team is agreed that the small suggestion "chicklets" is not what we want.

While I absolutely prefer the two-line layout for bookmarks and history [1], for search suggestions the two-line layout seems somewhat redundant, though, because the second line is the same for every search suggestion from the same search engine.

[1] And still think desktop switching away from it was a mistake...

**Comment by lovasoa** [comment] 2020-02-28 09:12
This issue is also a big problem for me in the app. The useful information in suggestions is often only a few characters, and yet they take up the majority of the screen.

**Comment by kbrosnan** [comment] 2020-09-09 16:47
Duplicate of #12950

**Closed by kbrosnan** 2020-09-09 16:47 UTC
Labels: Feature:Search, eng:ready, feature request 🌟
