### ISSUE TITLE
FNX-4670 ⁃ Pull down to refresh

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#10898] opened 2020-05-25 15:39 UTC
We desperately need this usable feature as we are used to similar feature in other browser such as Chrome/brave/edge etc,.

i remember this was added in april but was removed due to high sensitivity. Actually in firefox implementation pull down to refresh was working even in the middle of the page that's why it was irritating whereas in chrome or other browser pull down to refresh works only when you are on the top of the webpage which makes sense. Maybe this will help to fix the feature and add it.

**Comment by jonalmeida** [comment] 2020-05-25 16:15
Duplicate of https://github.com/mozilla-mobile/fenix/issues/9766

**Closed** 2020-08-10 22:32 UTC
Labels: needs:triage
