### ISSUE TITLE
The updated/Proton "tab" button is too short, looks wrong

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#19526] opened 2021-05-17 01:12 UTC
Icons/buttons were updated as part of Proton refresh, but the "tab" button on the toolbar is now rectangular, it just doesn't look right to the point that it's distracting, it's too short! It should be same height as before. It also seems/feels/looks like the target size is smaller, even though I suspect it's the same. Screenshot attached, up top is Fenix stable, below is Nightly with the Proton buttons/icons
![toolbar tab button](https://user-images.githubusercontent.com/47801466/118419875-4d636100-b68b-11eb-9b8c-5de2c404d67a.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10707)

**Comment by Dunexus** [comment] 2021-05-17 08:34
Cc @Amejia481 as you worked on the proton icon update

**Comment by Amejia481** [comment] 2021-05-17 13:36
Thank for tagging me @Dunexus, the icon is size is the same what have changed were the borders that are less wider than before, you can see more details here https://github.com/mozilla-mobile/android-components/pull/10129#issuecomment-824365576, I will tagged @brampitoyo from UX just to confirm that everything is as expected.

**Comment by willfs84** [comment] 2021-05-17 15:54
But even if it's as expected, that doesn't mean this is WONTFIX/INVALID. A) it looks bad and 'off' from a design and aesthetic perspective (because it's not as tall as it used to be), but more importantly B) it being shorter makes it seem/look like the tap target size is smaller. I understand this might not actually be the case, but the fact that it makes it seem/look that way is a valid issue, so UX needs to make a change here

**Comment by willfs84** [comment] 2021-05-18 02:18
Sorry to "double post" but I mentioned this to a colleague today and he brought up another good point: making the icon/button so short is forcing to use a super tiny text size for the number of tabs open inside the icon, which is a real problem. I don't have poor vision and the text size is too small for me. UX should increase the height and maybe even the width slightly, that way you can increase the font size inside the icon

**Comment by SoftVision-LorandJanos** [comment] 2021-11-18 10:00
This is still reproducing. It looks the same as when the ticket was created.
However as it is intended, I can change the bug label to a feature request one.
Tested on the latest Nightly 96.0a1 (2021-11-18).
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by boek** [comment] 2023-01-31 16:29
I'm going to close this as working as intended.

**Closed by boek** 2023-01-31 16:29 UTC
Labels: feature request 🌟, Feature:Toolbar, needs:triage, qa-triaged
