### ISSUE TITLE
[Bug] The "Help" menu entry does a web search with the help URL

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-mobile/fenix#4648] opened 2019-08-09 13:27 UTC
## Steps to reproduce

- Open Fenix to the "Home" page;
- Click on the "3 dots menu" on the top right (the one containing Setttings, Library and Help";
- Select "Help"

### Expected behavior

An help page is opened in Fenix.

### Actual behavior

The help URL is used as a search keyword for the default search engine: the results page of the default search engine is shown.

### Device information

* Android device: Samsung Galaxy A5
* Fenix version:  nigthly 190808 23:13 (build #12202320)

**Comment by Pheonix73** [comment] 2019-08-09 15:52
@Dexterp37 could you send a screenshot of the help page that was opened on fenix?

**Comment by Dexterp37** [comment] 2019-08-09 15:58
There you go!

![fenix_help_bug](https://user-images.githubusercontent.com/883721/62792283-3adbf100-bacf-11e9-845a-c9e5da7e4d9b.jpg)

**Comment by yoasif** [comment] 2019-08-09 16:06
I can reproduce this, except that it uses DuckDuckGo -- seems like it is using the default search engine to search for "https://support.mozilla.org/1/mobile/Nightly 190807 19:14/Android/en-US/faq-android"

**Comment by cadeyrn** [comment] 2019-08-09 18:19
Duplicate of #3892.

**Comment by sblatz** [comment] 2019-08-14 20:03
Closing as dup of #3892.

**Closed by sblatz** 2019-08-14 20:03 UTC
Labels: 🐞 bug
