### ISSUE TITLE
Automate LeakCanary checking in existing UI tests

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4506] opened 2019-08-02 17:54 UTC
LeakCanary has the capacity to fail UI tests when a leak occurs during the test. We should add memory leak checking to our existing UI tests (when not actively being used for performance testing, since it slows them down).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-12897)

**Comment by sblatz** [comment] 2019-09-27 16:05
Removing this from our Kanban since it looks like @rpappalax is digging into this.

**Comment by mcomella** [comment] 2020-08-04 00:10
@rpappalax Is this still something you're looking into? There are several memory leaks already in the product and some users are reporting high memory usage https://github.com/mozilla-mobile/fenix/issues/12374 and stuttering that seem related https://github.com/mozilla-mobile/fenix/issues/12302 so it'd be great to prevent additional memory leaks from being introduced!

---

I found [the documentation](https://square.github.io/leakcanary/recipes/#running-leakcanary-in-instrumentation-tests) and it mentions:
> Running leak detection in UI tests means you can detect memory leaks automatically in Continuous Integration prior to those leaks being merged into the codebase. However, as LeakCanary runs with a 5 seconds delay and freezes the VM to take a heap dump, this can introduce flakiness to the UI tests. Therefore it is automatically disabled by setting LeakCanary.config.dumpHeap to false when JUnit is on the runtime classpath.

It sounds like you can still run the memory leak checks without doing the heap dump that creates flakiness but I suppose the documentation is unclear.

In any case, given the possibility of disrupting the stability of the tests (and some tests failing due to the existing memory leaks), I was thinking it might be less problematic for your team to introduce the change but let me know if not!

**Comment by mcomella** [comment] 2020-08-04 00:13
Moving to triage: we may want to add this to our top 10 inter team bug list.

**Comment by hwinnemoe** [comment] 2020-08-04 05:49
Could this have prevented leaks that originated in GV? [BZ-1655580](https://bugzilla.mozilla.org/show_bug.cgi?id=1655580) was only caught by manual obversation of the memory usage during specific actions. And it was specific to Fenix, the issue was not reproducible on GeckoView Example.

**Comment by mcomella** [comment] 2020-08-04 17:29
@hwinnemoe No, the tooling only works for the JVM. That's a good point though – I'll check with folks on how we catch memory leaks in GV embedded in fenix.

**Comment by mcomella** [comment] 2021-08-19 15:57
We want to catch memory leaks in testing so let's keep this open.

**Comment by mcomella** [comment] 2022-03-30 20:40
Triage: we're concerned this could introduce additional flakiness to our tests. If it's flaky or it significantly slows down UI tests, we could introduce this as a Tier 2 test that doesn't run on every PR.

**Comment by cpeterso** [comment] 2022-12-23 20:38
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807307

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2022-12-23 20:38 UTC
Labels: eng:automation, P2, eng:health, performance, E3, pin, perf:resource-use
