### ISSUE TITLE
FNX-4398 ⁃ [Bug] Clipboard manager doesn't work on page editable fields

### ISSUE THREAD

**Issue by hoqogi** [mozilla-mobile/fenix#10579] opened 2020-05-12 00:40 UTC
## Steps to reproduce
Tap on a text field somewhere, then launch clipboard manager 

### Expected behavior
Clipboard manager is displayed 

### Actual behavior
![Screenshot](https://user-images.githubusercontent.com/64539966/81625703-52e7f480-9402-11ea-80cf-ffd3bc6b7537.jpg)UNITO-UNDERSCORE!20200512-034014!UNITO-UNDERSCORE!Firefox Preview!

Clipboard manager button is inactive

### Device information
samsung s10

* Android device: 10
* Fenix version: 5.0

**Comment by sv-sdeiac** [comment] 2020-05-12 07:59
Hi @hoqogi, I wasn't able to reproduce your issue using the latest version of Firefox Preview Nightly 5/12 #21330603.

What keyboard did you use? 
Also, if you have some additional information about your issue, please let us know.

Devices:
- Samsung Galaxy Note 8 (Android 9);
- Samsung Galaxy Tab S6 (Android 9).

**Comment by hoqogi** [comment] 2020-05-12 09:09
@sv-sdeiac 
I'm using Samsung Keyboard, version is what's latest.

Additional information? The clipboard manager button is active when editing address or searching within the page. It works in every other app I use.
![Screenshot_20200512-120713_Firefox Preview](https://user-images.githubusercontent.com/64539966/81665330-420ea180-9449-11ea-8571-0c2428930759.jpg)

**Comment by hoqogi** [comment] 2020-05-12 09:13
But for when you type text inside the page it is inactive, greyed out.

**Comment by Augures01** [comment] 2020-05-12 09:37
Some more info:
Samsung Keyboard clipboard manager also doesn't work in stable Firefox for Android builds.
You can open it with addressbar, but you can't use it with text fields on site pages.
Looks like it's not a problem with Firefox, but with Samsung Keyboard, because in Samsung Browser (or Chrome) you can't see clipboard button with text fields at all.
P.S. I'm on Samsung S6 Edge with Android 7.0

**Comment by sv-sdeiac** [comment] 2020-05-13 06:32
Hi, from the last comment it seems that there is a Samsung keyboard bug and not a Firefox Preview bug. 
Also, I am still not able to reproduce the problem.

Due to that, I'll close this ticket, thanks for your time.

**Closed** 2020-08-11 01:04 UTC
Labels: Feature:IME, 🐞 bug
