### ISSUE TITLE
Swipe longer on last tab to open a new one

### ISSUE THREAD

**Issue by JVariance** [mozilla-mobile/fenix#20042] opened 2021-06-16 04:39 UTC
### What is the user problem or growth opportunity you want to see solved?

If you are in the last tab and swipe to the left, there's a blank space indicating that you've reached the end of the tab list. (screenshot 1).

### How do you know that this problem exists today? Why is this important?

I often wished to be able to directly open a new tab in this situation by swiping a bit longer, more or less like the typical refresh gesture by dragging (screenshot 2)

### Who will benefit from it?

Everyone. It's a fluent gesture, that's way more pleasant than ending the swipe and afterwards clicking two times to add a new tab.

![Screenshot_20210616-062040_Firefox Nightly.jpg](https://user-images.githubusercontent.com/62245444/122158866-9f0b3100-ce6d-11eb-92f3-fac2294383f7.jpg)
![20210616_062652.jpg](https://user-images.githubusercontent.com/62245444/122158876-a3374e80-ce6d-11eb-8869-5e2a2effba51.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11054)

**Comment by Dunexus** [comment] 2021-06-16 08:18
Duplicate of https://github.com/mozilla-mobile/fenix/issues/13809

**Comment by csadilek** [comment] 2022-12-22 19:30
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807068

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2022-12-22 19:30 UTC
Labels: feature request 🌟, Feature:Tabs, Feature:Gesture, needs:triage
