### ISSUE TITLE
Clear browsing data when closing the app

### ISSUE THREAD

**Issue by ppvnf** [mozilla-mobile/fenix#27099] opened 2022-09-22 02:23 UTC
### What is the user problem or growth opportunity you want to see solved?

Fenix has the option [Clear browsing data on exit](https://support.mozilla.org/en-US/kb/clear-your-search-history-firefox-android#w_clear-browsing-data-on-exit), however this option won't clear your history when you close Firefox on the Android task switcher. I consider cumbersome having to open the Firefox menu (three dots) and then press quit. 

This is especially a problem if you want to close Fenix and other Android tasks at the same time, since, in order to clear Firefox history, you can't just terminate all tasks together (because Fenix won't consider being closed as exiting the browser).

On Firefox for desktop, for instance, you don't need to click exit to trigger the similar option [Automatically clear the cache](https://support.mozilla.org/en-US/kb/how-clear-firefox-cache#w_automatically-clear-the-cache). Simply closing the browser window is enough for the history to be cleaned (when this option is enabled).

 
### How do you know that this problem exists today? Why is this important?

I found out because I am a Firefox user for desktop that is also trying to switch to the Android version (you have improved a lot, I am only waiting for extensions to be re-enabled). 

It's a privacy issue, since closing Firefox (on the Android task switcher) won't clear the history.

### Who will benefit from it?

Users who have the option "Clear browsing data on exit" enabled and are used to Firefox for desktop behavior.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21628)

**Comment by Dunexus** [comment] 2022-09-22 12:33
Duplicate of https://github.com/mozilla-mobile/fenix/issues/3950

Also, see this comment about why it would be hard to solve : https://github.com/mozilla-mobile/fenix/issues/2152#issuecomment-492332285
> Android does not provide a way to tell the difference between a user swiping an app closed and the app being killed in the background.

**Comment by Dunexus** [comment] 2022-09-22 14:11
> I am not entirely convinced that the answer you quoted is still applicable though. Android has gone through several updates since then and devices have become much more powerful, so apps being killed in the background are not very relevant right now IMO.

To be honest, this is beyond my knowledge. I quoted a dev as they probably understand the behavior better than I do.

> Sorry, I am still not very experienced with Github. Should I close this issue and move the discussion to https://github.com/mozilla-mobile/fenix/issues/3950, to https://github.com/mozilla-mobile/fenix/issues/5865 or to https://github.com/mozilla-mobile/fenix/issues/22064? https://github.com/mozilla-mobile/fenix/issues/5865 seems the one with more discussion, altough the name of the issue is somewhat confusing.

I will let someone from dev team answering this but it could be great to consolidate all this discussion on a single issue.

**Comment by ppvnf** [comment] 2022-09-22 14:26
> I will let someone from dev team answering this but it could be great to consolidate all this discussion on a single issue.

True. I've found out an even more up to date related issue (https://github.com/mozilla-mobile/fenix/issues/17634), so that one may be the best one to continue the discussion, but I will wait for the dev team answer.

**Comment by ppvnf** [comment] 2022-11-04 23:50
@kbrosnan would you mind verifying if the issues below (and this one) are indeed duplicates?

https://github.com/mozilla-mobile/fenix/issues/3950, https://github.com/mozilla-mobile/fenix/issues/5865, https://github.com/mozilla-mobile/fenix/issues/17634 and https://github.com/mozilla-mobile/fenix/issues/22064

**Comment by cpeterso** [comment] 2023-01-31 22:58
Thanks for finding the related bugs. This bug is a duplicate of #22064, which we're now tracking in Bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1807538

**Closed by cpeterso** 2023-01-31 22:58 UTC
Labels: feature request 🌟, needs:triage
