### ISSUE TITLE
[Bug]: The language of the Add-ons cannot follow the browser

### ISSUE THREAD

**Issue by LTHPKBTE** [mozilla-mobile/fenix#27518] opened 2022-10-24 11:01 UTC
### Steps to reproduce

Although I haven't changed any settings, when I update my Firefox Nightly 108, addons' language change to english.
![IMG_20221024_184817](https://user-images.githubusercontent.com/53574505/197510612-cb08d638-7b15-4d03-82e2-8b77c1bb3aa6.jpg)

### Expected behaviour

The language setting of the addons follows the system(Chineise).

### Actual behaviour

The language of the addons is changed to English.

### Device name

Redmi K30 Pro

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

108.0a1 (Build #2015911371), 5f136e822+

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21858)

**Comment by hokonch** [comment] 2022-10-24 14:41
Duplicate of https://github.com/mozilla-mobile/fenix/issues/27298, which is tracked on https://bugzilla.mozilla.org/show_bug.cgi?id=1795704 now.

**Closed** 2022-10-24 14:45 UTC
Labels: 🐞 bug, needs:triage
