### ISSUE TITLE
Release to Huawei AppGallery

### ISSUE THREAD

**Issue by oliverkardos** [mozilla-mobile/fenix#18913] opened 2021-04-10 12:44 UTC
Dear Developers, 

Please release Firefox for Android onto Huawei AppGallery. These devices are now extremely popular not just in China but also in Europe. As you might know, these devices don't have Google services, meaning they don't have Google Chrome, only an OEM browser which is lagging behind with updates and not as great as Chrome or Firefox. You would have excellent chances with Firefox here. But for the end user, it is so difficult to install it manually using apks, let alone managing updates.
Could you please officially release Firefox to this store? 

Thank you

**Comment by anotherus3r** [comment] 2021-04-10 12:51
Duplicate of #13420.

**Comment by LaurentiuApahideanSV** [comment] 2021-05-19 11:43
This is indeed a duplicate of https://github.com/mozilla-mobile/fenix/issues/13420. I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-05-19 11:43 UTC
Labels: needs:triage
