### ISSUE TITLE
 StrictMode.resetPoliciesAfter – strict number of checks, and add performance team as code owners for the file

### ISSUE THREAD

**Issue by sraturi** [mozilla-mobile/fenix#13959] opened 2020-08-20 03:37 UTC
There are currently two versions

- resetPoliciesAfter(in fenix)
- resetAfter (outside of fenix)
- usages in GV (maybe we shouldn't worry about these right now & file a follow-up)

We want to restrict the number of calls to these methods to prevent regressions.

**Comment by Archaeopteryx** [comment] 2020-09-29 23:24
@mcomella Can you reland this? Despite what the retriggers of the task showed, the failure for which this got reverted was caused by the push which landed before.

**Comment by mcomella** [comment] 2020-09-30 15:24
@Archaeopteryx As far as I can tell, my changes weren't backed out – perhaps you have the wrong issue?

**Comment by mcomella** [comment] 2020-10-06 21:14
Addressed in https://github.com/mozilla-mobile/fenix/pull/15570

**Closed by mcomella** 2020-10-06 21:14 UTC
Labels: eng:performance, needs:triage

**Comment by Mugurell** [comment] 2020-10-07 12:46
I think this causes the app to crash when changing orientation with the following log:

> org.mozilla.fenix.debug E/ExceptionHandler: Uncaught exception handled: 
    java.lang.IllegalStateException: Failed to initialize GeckoRuntime
        at org.mozilla.geckoview.GeckoRuntime.create(GeckoRuntime.java:490)
        at GeckoProvider.createRuntime(GeckoProvider.kt:56)
        at GeckoProvider.getOrCreateRuntime(GeckoProvider.kt:28)
        at org.mozilla.fenix.components.Core$engine$2.invoke(Core.kt:108)
        at org.mozilla.fenix.components.Core$engine$2.invoke(Core.kt:81)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.mozilla.fenix.components.Core.getEngine(Unknown Source:2)
        at org.mozilla.fenix.FenixApplication.onConfigurationChanged(FenixApplication.kt:484)

the problem seemingly stemming from [components.core.engine.profiler?.addMarker(..)](https://github.com/mozilla-mobile/fenix/blob/4302cd20b225790feffacd3e6277a748d3895cbf/app/src/main/java/org/mozilla/fenix/StrictModeManager.kt#L130)
@mcomella can you please check?

**Comment by mcomella** [comment] 2020-10-07 17:02
Thanks. I confirmed that I see the same behavior so I opened https://github.com/mozilla-mobile/fenix/issues/15751
