### ISSUE TITLE
[Bug] Received tab is intercepted by Focus instead of Fenix when signed in into Fenix but Focus is default browser

### ISSUE THREAD

**Issue by mailinglists35** [mozilla-mobile/fenix#17173] opened 2020-12-21 19:33 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
setup Firefox Focus as default browser
sign in into firefox account in Firefox Fenix
In firefox account, disable history, tab syncing, bookmarks, logins (I **don't want** to sync anything across all my signed in copies of firefox. I only want to send tabs/url on demand from one to another)

Send tab from desktop Firefox to Fenix

### Expected behavior
Fenix receives the notification, Fenix displays the status bar notification, Fenix opens the tab when user taps the notification, Focus receives no URL, Focus displays no notification

### Actual behavior
Focus receives the notification, Focus displays the status bar notification, Focus opens the tab when user opens notification, Fenix receives no URL, Fenix displays no notification

Even if Fenix is open, Focus receives the notification & everything!

Fenix receives the url only if I set Fenix as default browser or if I enable synced tabs

### Device information

* Android device: 10
* Fenix version: 84.1.1
* Focus version: 8.10.0
 
### Additional information
I use Focus as default because

1) I don't want external links to pollute my browsing history that I want to keep clean (clean does not mean zero, but clean of stuff I did not enter manually into the browser)

2) I don't want to be forced-signed into my main browser by google & friends whenever I authenticate in some app using oauth2

3) when is default browser, Fenix opens links from other apps in **normal** mode even if I leave the app in **incognito** mode. I want Fenix to receive links from other apps **in the state I Ieft it in**, like it does on iOS: I leave it in normal mode, open in normal mode. I leave it in incognito mode, open in incognito mode!

**Comment by jonalmeida** [comment] 2020-12-21 19:57
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/12627.

So let's keep the conversation in one place so we can find a better UX expectation of everyone.

**Closed by jonalmeida** 2020-12-21 19:57 UTC
Labels: Feature:SendTab, 🐞 bug

**Comment by mailinglists35** [comment] 2020-12-21 20:09
thanks, I couldn't find it when searching
