### ISSUE TITLE
Installed web apps (PWA) frequently launch blank white screen, no browser content

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/fenix#15335] opened 2020-09-23 04:33 UTC
I have Twitter installed as a web app on my Pixel 3 via a Nightly installation from Google Play. For the last day or three, the launcher for the twitter web app frequently fails to display any content (it just shows a blank white screen, seemingly forever, but I usually quit the app after a minute or two).

I haven't tried hooking up remote debugging yet to see if there's anything useful being logged (I'm in the process of moving and I've already packed my usb-a to usb-c cables), but I can try to do that myself if I'm the only one seeing this.

Sometimes twitter's web app launches just fine (though it and Fenix-proper both seem to be taking a bit longer to actually display anything in the last few days). I'd guess about 1 in 10-20 launch attempts actually works, but I haven't figured out any pattern to it.

Twitter.com loads just fine in a regular Fenix tab, and my shortcut to facebook.com (not an installed web app) loads just fine, fwiw.

**Comment by ekager** [comment] 2020-09-23 07:03
I saw this once also and IIRC a back press on the white screen fixed the weird state. If you notice solid STR please update this bug! I had a feeling it might be related to what the state of tabs were in normal app browsing as well.

**Comment by KWierso** [comment] 2020-09-23 07:12
Swiping back on the white screen takes me back to my Android launcher home screen, and my next launch of the Twitter web app *does* open up correctly.

**Comment by KWierso** [comment] 2020-09-23 07:33
Did an `adb logcat | grep org.mozilla.fenix`, here's what that printed out when I started up the webapp to the white screen, swiped back out of the webapp, then successfully relaunched it: https://gist.github.com/KWierso/52bd67c384e909e75528fe62c33915b6

Hope it helps!

**Comment by ekager** [comment] 2020-09-23 21:57
cc @pocmo this looks like it could be an engine session linking issue after restore? I did some preliminary logging and we are finding a session with an id, a manifest, and initial URL.

**Comment by sv-ohorvath** [comment] 2020-09-24 13:19
I couldn't reproduce with twitter, but this happens on other PWAs like pwa-directory.appspot.com or crypt.ee, STR:
1. Install the PWA.
2. Swipe to close Fenix.
3. Launch the PWA.

This was once fixed on https://github.com/mozilla-mobile/fenix/issues/10689 but might be a regression?

**Comment by ekager** [comment] 2020-09-24 18:01
Good find! I commented again in https://bugzilla.mozilla.org/show_bug.cgi?id=1641715

**Comment by ekager** [comment] 2020-09-28 21:10
User STR from #15509

## Steps to reproduce

visit any PWA website, i.e. trivago.com
Add toHomescreen
close Firefox and close the PWA
open the newly added PWA
The PWA opens only a white screen.

### Expected behavior

It should open the PWA app normally without browser in the back ground

### Device information

Android device: Lenovo TB-8505F, but confirmed on several other devices

First time it  appeared for us on FF79: https://github.com/mozilla-mobile/fenix/issues/14095

**Comment by makepanic** [comment] 2020-10-08 13:33
Hi,

we were hit by the same issue.
I did some tests with older firefox versions (via [uptodown](https://firefox.en.uptodown.com/android/versions) , [apkmirror](https://www.apkmirror.com/apk/mozilla/firefox/#variants) and [apkpure](https://apkpure.com/firefox-browser-fast-private-safe-web-browser/org.mozilla.firefox/versions)) and found that the following versions had this issue:

* 80.1.2 -  no about:blank
* 81.1.0-RC.1 - no about:blank
* 81.1.0 - no about:blank
* 81.1.1 - about:blank
* 81.1.3 - about:blank
* 81.1.4 - about:blank

I guess that means between 81.1.0 and 81.1.1 there was some sort of regression

**Comment by tmtron** [comment] 2020-10-11 09:07
Same issue here. 

Broken state (always close all apps before the test):
1. When I open the PWA from the homescreen, then only the blank page is shown.
2. When I open Firefox first (and do not visit any URL: i.e. remain on the default page), then open the PWA , then only the blank page is shown.

Working state:
1. Open Firefox, visit any URL (e.g. google.com), then open the PWA: working
2. Open the PWA - blank screen. Go to homescreen (keep the blank PWA open) and open the PWA again: working

Version info:
* Firefox: 81.1.4 (Build #2015768387)
* Android 10: Kernel: 4.9.186-19495925 (Sept, 9, 2020)

**Comment by KWierso** [comment] 2020-11-17 00:06
This was fixed for me for quite a while, but appears to have popped back up after updating Nightly in the Google Play Store sometime today or yesterday.

**Comment by KWierso** [comment] 2020-11-17 00:08
If it helps, this is what Nightly says I'm currently using. Unsure what I was on previously, but I assume it was yesterday's build. 

Nightly 201116 17:01 (Build #2015776011)
AC: 67.0.20201115143123, 52cf9b7c9
GV: 84.0a1-20201114094625
AS: 67.0.0

**Comment by csadilek** [comment] 2020-11-17 16:38
I can reproduce this reliably now on master, and it works fine for me with AC 66.0.20201109143146 and GV 84.0a1-20201109095222.

Commented and attached logs to https://bugzilla.mozilla.org/show_bug.cgi?id=1641715

**Comment by csadilek** [comment] 2020-11-17 16:53
Thanks for reporting @KWierso, looks like the cause is already identified in `https://bugzilla.mozilla.org/show_bug.cgi?id=1641715` and only Nightly should be affected by this.

**Comment by Amejia481** [comment] 2021-01-14 18:40
The bugzilla ticket was [closed with a patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1641715#c21) we should verify if this is still an issue.

**Comment by makepanic** [comment] 2021-01-15 07:17
Can confirm that it works for me now with the most recent firefox nightly on android.

**Comment by sflorean** [comment] 2021-01-18 13:49
Tested on latest Nightly build and the following pwa: twitter, apkmirror, pwa-directory.appspot.com and crypt.ee and I didn't encounter any issues following the above steps.

**Closed by sflorean** 2021-01-18 13:49 UTC
Labels: Feature:PWA, S1, eng:qa:needed, 🐞 bug

**Comment by IrwanKhaliq** [comment] 2021-04-19 22:39
I just add `basename='/index.html'` on my index.html and it works for me
see code below for more :

```js
import React from 'react';
import {BrowserRouter as Router, Route, Switch} from 'react-router-dom';
import LoginPage from './components/LoginPage/LoginPage';
import Dashboard from './components/Dashboard/Dashboard';

function App() {
  return (
    <Router basename='/index.html'>
      <Switch>
        <Route path='/' exact component={LoginPage} />
        <Route path='/dashboard' component={Dashboard}/>
      </Switch>
    </Router>
  );
}

export default App;

```

Hope it would help.
