### ISSUE TITLE
rearrange bookmarks, bookmark folders by "click and drag" option

### ISSUE THREAD

**Issue by rocky-01** [mozilla-mobile/fenix#15645] opened 2020-10-02 22:16 UTC
I want see feature "click and drag" option to rearrange bookmarks, bookmark folders

Almost every browser in has option to rearrange bookmarks except Firefox since all these years.

Everyone benefit from it.

**Comment by cadeyrn** [comment] 2020-10-02 22:30
Duplicate of #4348.

**Closed** 2020-10-02 23:42 UTC
Labels: needs:triage
