### ISSUE TITLE
FNX3-16467 ⁃ Extension support

### ISSUE THREAD

**Issue by unixandria-xda** [mozilla-mobile/fenix#2631] opened 2019-05-18 17:57 UTC
### Why/User Benefit/User Problem
The only and I emphasize only reason I ever used the old Firefox was for extension support. It's not just adblockers either. I had a web dark mode extension, https everywhere, Facebook container, etc

Now I just tried to install a few extension. And it doesn't work

I'm sure I'm not the only one who uses FF on Android solely for the extension support. And I can also say that if extension support is not implemented, I alongside a bunch of other people will no longer be using it

Don't get me wrong, ohmygod is the new version of it faster and prettier. But so is chrome and kiwi browser. And kiwi support extension. 

### What/Requirements
At least basic web extension support, if not everything on addons.mozilla.org

### Acceptance Criteria (how do I know when I’m done?)
When content block/change/etc works. At least parody with old FF

I know there is a closed issue over this. I don't care; this is important to me. #1 feature in a browser I need: extension support. Please, please, please don't become Chrome at least in this aspect

**Comment by cadeyrn** [comment] 2019-05-18 18:03
Duplicate of #574.

**Comment by vesta0** [comment] 2019-05-21 17:30
Thanks for filing this @alexa-v2 ! Will address this in #574

**Closed** 2020-08-20 17:44 UTC
Labels: feature request 🌟
