### ISSUE TITLE
[Bug] Sending tabs to multiple devices is not working without a forced sync

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#8582] opened 2020-02-20 15:00 UTC
## Steps to reproduce
1. Sign in with the same account on several devices, and on desktop.
2. Create a collection with one or multiple tabs.
3. Select to share the collection to all devices connected.

### Expected behavior
All the tabs from the collection are sent to all the connected devices.

### Actual behavior
The tabs are sent only on desktop.
If sync is triggered manually, the tabs are sent.

### Device information
* Android devices: Sony Xperia Z2 (Android 6.0.1), Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab S3 (Android 8), Windows 10
* Fenix version: Beta 4.0.0-beta.1, Nightly 2/20
* Reproducible also if trying to send a tab that is not in a collection.

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4231400/logcat.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15849)

**Comment by jonalmeida** [comment] 2020-02-21 17:14
Is this bug consistent? I can't reproduce it yet. Send Tab can be flaky if there are network issues in a test environment.

**Comment by liuche** [comment] 2020-02-24 17:01
If this is working let's deprioritize this - is it device specific?

**Comment by softvision-miralobontiu** [comment] 2020-02-25 12:29
I was able to reproduce again using Google Pixel (Android 10), HTC 10 (Android 8), and Windows 10, on Beta 4.0.0-beta.1. Here are the steps:
- on desktop and HTC 10, I signed in with the same account, and leave the app in the background for 2 hours,
- on Pixel I signed in with the same account after 2 hours after I signed in on the other 2,
- I've sent 5 tabs from Pixel to all the connected devices,
- on desktop, the tabs sent where opened, but on HTC not.

**Comment by jonalmeida** [comment] 2020-02-26 16:34
I'm still unable to reproduce this locally. I've been able to successfully send collections to multiple devices that are desktop and mobile using today's (26/02/2020) nightly with Desktop Nightly (75.0a1 (2020-02-24)) and Reference Browser's nightly (26/02/2020).

> Reproducible also if trying to send a tab that is not in a collection.

If this is reproducible without sending a collection that means all send tab would be affected, but it sounds like only some devices have this issue? I wonder if there is so device or location limitations (if not network).

**Comment by jonalmeida** [comment] 2020-02-26 17:17
I see now what's the cause after setting up a fresh device install. When you log into Sync for each device, a push command notifies desktop that a new device is registered.

On Fenix though, I see that after a fresh install has taken place (push registration seems to have happened already) but we don't get notified on other devices.

### Steps to reproduce
1. Setup sync on Android Device A and a desktop (for comparison).
2. Setup sync on Android Device B.
3. Send tab from Device A to all devices (i.e. send to Device B and desktop) soon after.

After I press sync now on the device that didn't receive the tab the first time, send tabs with push work after that.

I wonder if this might be the outcome from us removing the device commands change @rfk ?

**Comment by jonalmeida** [comment] 2020-02-26 18:41
Even with my STRs, this is a little harder to reproduce since it depends on timing. I don't believe this is a release blocker.

**Comment by sv-ohorvath** [comment] 2020-02-28 09:20
On an Android 5.1 (Xiaomi Mi Pad 2), I'm receiving the tabs after several minutes, and after syncing 2-3 times.

**Comment by jonalmeida** [comment] 2020-03-04 16:01
Un-assigning since I'm not actively working on this and it's a somewhat expected outcome from our changes and we aren't too worried about it.

**Comment by Diana-Rus** [comment] 2020-04-15 08:53
Hi, I did reproduced the scenarios from [comment](https://github.com/mozilla-mobile/fenix/issues/8582#issuecomment-592424802) and description on Beta 4.3.1-beta.1
- Send a couple of tabs from Pixel 3 XL(Android 9) to desktop and Samsung Galaxy S9 (Android 8)
- Re-send a couple of tabs to desktop and only after a couple of minutes i received the sent tabs

Devices:
- Google Pixel 3 XL (Android 9)
- Samsung Galaxy S9 (Android 8)
- Windows 10

**Comment by scheinercc** [comment] 2020-07-03 13:45
> On an Android 5.1 (Xiaomi Mi Pad 2), I'm receiving the tabs after several minutes, and after syncing 2-3 times. (but this is also true for sending only to this device, not necessarily to all)

I am not receiving them at all anymore. If I remember to manually push, I sometimes get tabs from a day ago or older.
Android 7.1.2 on a Fairphone

**Comment by softvision-miralobontiu** [comment] 2020-07-15 11:51
I was able to reproduce the issue on the Beta 79.0.0-beta.6 build with Samsung Galaxy Tab S6 (Android 9), Sony Xperia Z5 Premium (Android 7.1.1), and Windows 10.
After forcing sync twice, I received on the Sony device the tab sent from the Samsung device.

**Comment by Diana-Rus** [comment] 2020-07-31 06:03
Reproducible on Beta 80.0.0-beta.2 with Google Pixel 3 XL (Android 9) and Windows 10.

**Comment by softvision-miralobontiu** [comment] 2020-12-31 08:08
I was able to reproduce this issue on 12/31 Nightly build with the following devices:
- Google Pixel (Android 10),
- Samsung Galaxy Tab S6 (Android 10),
- HTC 10 (Android 8), 
- Windows 10.

On all the devices (except desktop) I had to manually trigger sync to receive the tabs.

**Comment by scheinercc** [comment] 2021-01-01 12:05
For what it is worth, I am on Fairphone 3 with Android 10 now and still seeing the same issue sending a single tab from any of my desktops - Nightly and Dev Edition.

**Comment by Atemu** [comment] 2021-02-25 09:08
I am still experiencing this issue on home-brewed LOS17.1 with MicroG on the newest Fenix nightly.

FF is registered for cloud messaging and set to be started on push message but MicroG says it received no messages yet eventhough I sent a tab multiple times.  
(Yes, this isn't the official Google cloud messaging implementation but it works for all other apps I've used so far)

Only after manual sync does it show the notification.

What can I do to help debug this?

**Comment by Atemu** [comment] 2021-02-25 09:14
If you're also affected, opening the share menu is faster than going in the settings and also triggers a sync.

I've also just noticed that FF re-registeres for cloud pushes every time you sync; I'm not sure that's intended or necessary.

**Comment by scheinercc** [comment] 2021-03-31 14:19
There is a new thread about this issue over on Reddit: https://www.reddit.com/r/firefox/comments/mh3uvj/send_tab_to_device_doesnt_work/

**Comment by Otiel** [comment] 2021-09-27 19:29
Another recent thread on Reddit:

https://www.reddit.com/r/firefox/comments/p575ib/send_tabs_to_device_no_longer_working_or_working

**Comment by scheinercc** [comment] 2021-09-28 09:20
I just tested the above scenario again, sent two tabs from a Nightly on desktop to 2 devices, a DevEdition on desktop and a Nightly on Android. _Please note: the same applies for me sending a single tab to Android as well._

The tabs appeared within a second on the other desktop. 

On Android I opened the "Account Settings" view and watched the "Syncronise Now / Last synchronised: X minutes ago" button. It toggled to "Synchronising ..." after a 7 minute interval, but the tabs did not arrive.

I then clicked the button to trigger a manual sync. The tabs appeared right away, just **_before_** the button text changed from "Syncronise Now" to Synchronising ...".
It almost seems to me like that click event is triggering something additional.

@jonalmeida do you know if https://github.com/mozilla/application-services/pull/4347 should have take care of that? Also, should this ticket rather be in https://github.com/mozilla/application-services/issues?

**Comment by Atemu** [comment] 2021-10-18 10:21
This just started working for me. Both uni- and broadcast tab sends now make it to my phone nearly instantly.  

I haven't updated in a while so this might not be the first version it was fixed in but it works on 95.0a1 now.

**Closed** 2022-11-27 07:59 UTC
Labels: 🐞 bug, Feature:SendTab, S2, wontfix
