### ISSUE TITLE
No share button in the in-app browser

### ISSUE THREAD

**Issue by aha999** [mozilla-mobile/fenix#8674] opened 2020-02-22 21:54 UTC
When Firefox preview is opened as the app browser, its menu doesn't include the share option. (I opened a link in Reddit and 'mini-fenix' opens)
- Please add a share button to the in-app browser firefox preview

Version: Nightly 200221 06:00 (Build #2015724275)

![](https://i.imgur.com/7wek9hF.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15922)

**Comment by harshlele** [comment] 2020-02-24 05:13
can i work on this

**Comment by brampitoyo** [comment] 2020-04-27 21:48
Paging @apbitner who has designed our custom tabs.

**Comment by apbitner** [comment] 2020-04-28 17:25
I actually believe it was @AmyYLee, reassigning.

**Comment by AmyYLee** [comment] 2020-06-04 16:19
@aha999 Can you tell me what app you opened the tab in? 

This is what I'm seeing on a few apps I've tested

![image](https://user-images.githubusercontent.com/5992746/83782297-9cbca700-a65d-11ea-80ed-b9b8b9b56bff.png)

**Comment by aha999** [comment] 2020-06-05 00:18
@AmyYLee i don't get half the options if used in reddit app. i tried with Firefox Nightly and Firefox Preview just now... it's same as in my first screenshot, no options like in your screenshots.

**Comment by AmyYLee** [comment] 2020-06-08 18:50
Hi, unless there is a specific reason why we aren't showing these options (see screenshot below) in custom tabs for the Reddit app, I think we should include them.

![Screen Shot 2020-06-08 at 14 48 55](https://user-images.githubusercontent.com/5992746/84068711-694c8600-a997-11ea-80b3-a2620d2b9ec4.png)

**Comment by jonalmeida** [comment] 2020-06-08 22:08
@AmyYLee to clarify: 'Share via Tweet', 'Share via Direct Message', 'Copy link', 'Share via...' are all coming from the third party app.

In Focus, we always show the 'Share' icon in the toolbar:
<img width="521" alt="Screen Shot 2020-06-08 at 6 05 22 PM" src="https://user-images.githubusercontent.com/1370580/84085085-cefa3b80-a9b2-11ea-92b4-01bc11ce899c.png">

Adding a static share option in the menu, might lead to duplicate share buttons (one from us and one from the third party app).

**Comment by AmyYLee** [comment] 2020-06-09 14:47
@jonalmeida in Fenix we don't have a share button in toolbar (unless I'm misunderstanding your point) so I think adding it in the menu is okay.

**Comment by jonalmeida** [comment] 2020-06-09 18:25
@AmyYLee sorry, I was suggesting adding it to the custom tab menu since it's common for apps to add their own share menu item. That would mean, the menu could have a 'Share via' from the app and another 'Share' menu from us.

We can also ignore that case. 🙂

**Comment by AmyYLee** [comment] 2020-06-09 21:31
@jonalmeida We currently have 4 icons in the search bar (Focus has 3). I'm hesitant to another icon into the search bar. Especially since apps like Twitter will also have an additional "tweet" button in the bar. I would like to add a "share via..." in the Reddit app. If there is a wider issue with apps not providing a share option we can revisit. Thanks.

**Comment by dholbert** [comment] 2022-01-31 19:19
> @jonalmeida in Fenix we don't have a share button in toolbar (unless I'm misunderstanding your point)

This^^ is no longer true; in current Nightly, I **do** see a "share" button in the in-app-browser toolbar in some apps, e.g. in Gmail -- here's a screenshot of the Firefox Nightly in-app-browser launched from Gmail (share button present):
![image](https://user-images.githubusercontent.com/426803/151854138-37552348-5f69-43a5-8be3-a4f6b18586c1.png)

However the Share button is still missing when the in-app browser is launched form other apps, e.g. from Slack:
* Firefox Nightly in-app-browser launched from Slack (share button missing):
![image](https://user-images.githubusercontent.com/426803/151854031-78cbf9c3-199b-4400-9b08-1bcfd3d47783.png)

(But it's present if you use Chrome as your default browser.)

**Comment by jonalmeida** [comment] 2022-01-31 19:36
@dholbert the share icon that you are seeing in Gmail is controlled by the third-party app itself. It's part of the [Custom Tab config](https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsIntent#EXTRA_SHARE_STATE) that the app can choose to set if they want that icon to show up in their app experience. The same is true for some of the three-dot menu items which the app specifies for us (usually the ones without an icon in front of it is indication that they came from the third-party app so we don't have an icon for it).

What this means is that not all apps will have a share menu unless we add one that persists all the time. There are cons to overriding that experience as well, e.g. some app sites do not want to allow sharing of certain URLs.

**Comment by boek** [comment] 2023-01-26 23:26
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812846

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-26 23:26 UTC
Labels: feature request 🌟, eng:ready, Feature:CustomTabs
