### ISSUE TITLE
[Bug] Desktop mode toggle stuck at enabled. Includes reliable steps to reproduce it.

### ISSUE THREAD

**Issue by TrianguloY** [mozilla-mobile/fenix#15352] opened 2020-09-23 17:43 UTC
This bug has been reported several times (https://github.com/mozilla-mobile/fenix/issues/14737, https://github.com/mozilla-mobile/fenix/issues/13202, https://github.com/mozilla-mobile/fenix/issues/11552 and other closed issues) however none of them had a reliable way to trigger the bug, and it was practically irreproducible on an emulator. Here I present steps to reproduce it reliably on an emulator, so to avoid having this comment lost on one of the previous issues (as it has been with others) I decided to open a new issue.

## Steps to reproduce

0) REQUIRED: make sure the background process limit from the android developer options is set as 'no background processes'.
1) Open this github (doesn't work with all pages, does work with this github repository)
2) Enable desktop mode for the tab
3) Press the recent apps button
4) Open Firefox again

![bug](https://user-images.githubusercontent.com/10616202/94048946-89804380-fdd4-11ea-8241-637f3b01a91f.gif)

### Expected behavior
The page should still be in desktop mode (or alternatively but not desired, go back to mobile mode with the desktop mode switch disabled)

### Actual behavior
The page goes back to mobile mode but the desktop mode switch is kept enabled. Pressing it does nothing.

### Device information

* Android device: Emulator 30.0.26-6755297 --- 8.1 (Oreo) - API 27
* Fenix version: debug 1.0.2039 (TrianguoY fork, master branch, no modifications) but can be reproduced in nightly since a few months ago at least.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7322)

**Comment by SL-Lee** [comment] 2020-09-27 08:25
I found another set of steps to reproduce this issue:

1. Open any website in a new tab.
2. Open the main menu and request the desktop version of that website.
3. Close the tab, and immediately tap on "Undo" in the "Tab closed" snackbar.
4. The tab should restore itself, and opens the **mobile version** of the site.
5. Open the main menu, and observe the desktop site toggle: it is in the enabled state, even when the website is **not** the desktop version. Tapping on it does not change the state.

![](https://user-images.githubusercontent.com/45960387/94360132-e2eeb800-00dd-11eb-9a41-26f788196064.gif)

**Comment by mcarare** [comment] 2020-09-29 11:28
This is reproducible on sample browser also. Although the session reports it is in desktop mode, on session add, the loaded version of the website is the mobile one. We can force a reload, but we lack the API to condition the reload.  The true desktop/ mobile version check seems to depend on: https://bugzilla.mozilla.org/show_bug.cgi?id=1653296

**Comment by mcarare** [comment] 2020-11-19 18:41
With the second STR (https://github.com/mozilla-mobile/fenix/issues/15352#issuecomment-699603805) this is not reproducible anymore. On page restore the page loads the mobile version, and the switch is set accordingly. However, limiting background processes still reproduces the issue.

**Comment by mcarare** [comment] 2020-11-24 12:15
At the moment we do not have any access to an API to check if the desktop version is loaded in a session. 
Also, considering the only reproducible STR involves limiting background processes (acts somewhat different than the system closing a process due to memory restrictions) this should not be a priority, and it is likely to be solved along with the implementation of other suggestions for desktop mode, like https://github.com/mozilla-mobile/fenix/issues/11552.

**Comment by TrianguloY** [comment] 2020-11-24 13:15
@mcarare I was able to just reproduce it by opening the tab in desktop mode, opening a second heavy tab and navigating a minute or so there, and then switching back to the first tab. The tab was in mobile mode and the desktop switch was stuck on enabled. Version Nightly 201122 17:03 (Build #2015777163)

I may be wrong, please correct me otherwise by sharing an official documentation where it is explained, but the limit background processes toggle is exactly what android does, but instead of waiting to have low memory it just does it right away. On high end devices or emulators having low memory usually never happens, and that toggle serves to 'emulate' it.

Note that switching to another app and then reopening firefox doesn't seem to work. I haven't tested, but my theory is that only the tab process should be killed, not the whole app, for this bug to occur.

**Comment by samlh** [comment] 2021-05-23 22:36
Still happens on latest Firefox Nightly when a tab is unloaded for memory pressure - I still hit this pretty regularly.

The easiest way I know of to fix the issue is to close the tab and then do re-open tab. You can then re-enter desktop browsing mode.

**Comment by Nickoriginal** [comment] 2021-07-04 17:39
**Firefox 89.1.1**
Not _reproducible_ on:
**Samsung Galaxy A20s**
_Reproducible_ on:
**Samsung Galaxy J2 Prime**
Tested with "No background processes" switch enabled, on Samsung Galaxy A20s page after resuming still was in desktop mode.

**Comment by TrianguloY** [comment] 2021-12-31 22:29
I just tested the steps on a real device and they still reproduce the bug. This is NOT fixed.
The alternate steps shot closing and pressing undo, however, seem to be fixed.

**Comment by Noob729** [comment] 2022-05-30 23:58
Someone ought to shoot @stale bot to make it dump core.

**Comment by TheBrokenRail** [comment] 2022-09-19 20:08
Just a reminder that this is *still* an issue on Firefox v104 and beyond annoying.

![Screenshot_20220919-160654_Firefox](https://user-images.githubusercontent.com/17478432/191107304-3d4a002a-e428-4331-a0a7-fa54a592f733.jpg)

**Comment by PandoraHayami** [comment] 2022-09-25 20:34
Can we talk about the fact that this issue has been here since even fenix's stable release and it's still a thing in Firefox 105?

**Comment by csadilek** [comment] 2022-12-22 20:59
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807153

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2022-12-22 20:59 UTC
Labels: 🐞 bug, 🙅 waiting, Feature:RequestDesktopSite, Feature:Browsing
