### ISSUE TITLE
[Bug]: Bottom UI glitches out

### ISSUE THREAD

**Issue by bbhtt** [mozilla-mobile/fenix#26327] opened 2022-08-05 09:05 UTC
### Steps to reproduce

This happens pretty randomly so I don't have exact steps other than browsing some sites. Although I can reproduce it consistently while searching for issues on Github (see attached video and screenshot)

It started with the nightly builds published on Google Playstore on August 3-4.

I think it is coming from the space used by the keyboard app which is the part that glitches out.

https://user-images.githubusercontent.com/62639087/183043312-ad10a7f9-1d21-485b-996b-ea0fa0ce4439.mp4

### Expected behaviour

There shouldn't be a glitch

### Actual behaviour

The app glitches.

### Device name

Nokia C03

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1 20220804094607

### Additional information

about:support: [aboutsupport.txt](https://github.com/mozilla-mobile/fenix/files/9267125/aboutsupport.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21202)

**Comment by bbhtt** [comment] 2022-08-06 14:49
I ran mozregreesion and the range I got is https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=8badf082001c2f6a4e35b50f99d58304dae0cdda&tochange=c1ef6a96e57ccf20b08b8e78ab2d0638832f8b46 The only bug that could be related is https://bugzilla.mozilla.org/show_bug.cgi?id=1780093 I'm not entirely sure if the range is correct since there is no reliable reproduction steps for the issue, it took a lot of tries on each build.

From TC the last good build was 2015895819 (August 2 latest) and the first bad build was 2015896011 (August 3 latest)

**Comment by NyanCatTW1** [comment] 2022-08-07 08:59
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1783542

**Comment by delia-pop** [comment] 2022-08-08 09:10
Hello, @bbhtt . Thank you for reporting.
I was able to reproduce this issues on google.com with Lenovo Yoga Tab 11 (Android 11).

https://user-images.githubusercontent.com/89388888/183382759-ab594562-32b7-439d-b9fb-0ba12c3dc00d.mp4

**Comment by delia-pop** [comment] 2022-08-08 09:17
I will close this ticket since https://bugzilla.mozilla.org/show_bug.cgi?id=1783542 was opened for the GV team to handle. Please follow the progress on the issue on Bugzilla.

**Closed by delia-pop** 2022-08-08 09:17 UTC
Labels: 🐞 bug, S3, Feature:Browsing, needs:triage, qa-triaged
