### ISSUE TITLE
[Bug] Software keyboard raised for location bar only on second attempt

### ISSUE THREAD

**Issue by hsivonen** [mozilla-mobile/fenix#9578] opened 2020-04-01 09:08 UTC
## Steps to reproduce

1. Navigate to some page.
2. Scroll such that the location bar is visible.
3. Tap the location field.
4. Observe that the keyboard didn't show up.
5. Press the Android system back button.
6. Tap the location field again.

### Expected behavior

Expected the software keyboard to show up on the first attempt when tapping the location field.

### Actual behavior

Most of the time, the software keyboard shows up on the second attempt only.

### Device information

* Android device: Nokia 9
* Fenix version: 38.0.20200331130030

### Additional information

I believe this bug showed up less than a week ago, most likely to you three days ago.

**Comment by mcarare** [comment] 2020-04-01 09:33
Duplicate of https://github.com/mozilla-mobile/fenix/issues/9500. This is fixed in the latest nightly. If you still encounter issues while using this latest version, please feel free to reopen this issue.

**Closed by mcarare** 2020-04-01 09:33 UTC
Labels: needs:triage, 🐞 bug
