### ISSUE TITLE
[Bug] "Tab closed" snackbar doesn't go away

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#7833] opened 2020-01-21 19:00 UTC
## Steps to reproduce

I haven't been able to reliably reproduce this but the 2 times it happened:

-Have a few tabs open already
-Close one tab

### Expected behavior

-Undo tab closed snackbar should go away after a couple of seconds 

### Actual behavior

-Undo tab closed snackbar doesn't go away until the app is force killed. 

### Device information

* Android device: Pixel 3
* Fenix version: Latest Nightly

![Screenshot_20200121-031625](https://user-images.githubusercontent.com/42752644/72834197-4aeb2580-3c56-11ea-8765-3797123c7915.png)
![Screenshot_20200121-031505](https://user-images.githubusercontent.com/42752644/72834203-4e7eac80-3c56-11ea-9677-7adc434d4b0f.png)
![Screenshot_20200121-031727](https://user-images.githubusercontent.com/42752644/72834207-51799d00-3c56-11ea-9b25-a30cbf4a6e8e.png)

**Comment by cadeyrn** [comment] 2020-01-21 19:01
It's a duplicate of #7799.

**Closed** 2020-01-21 19:01 UTC
Labels: needs:group-triage, needs:triage, 🐞 bug
