### ISSUE TITLE
[Bug]: cannot enable push notifications for Twitter

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#22487] opened 2021-11-18 06:10 UTC
### Steps to reproduce

with nighlty (stable works just fine) I'm no longer able to enable push notification for Twitter, i ve got message browser not supported from Twitter, the issue started to happen from 31 of October. 

### Expected behaviour

push notification must work 

### Actual behaviour

push notication won't work 🤢 

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

96

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18661)

**Comment by sflorean** [comment] 2022-05-18 15:26
@ale82to this is still reproducible for you? I wasn't able to reproduce it on latest versions.

**Comment by delia-pop** [comment] 2022-08-10 10:18
Hi, @ale82to. I cannot reproduce this issue on the latest Nightly 105. I will closed this ticket based on your comment "other websites like webtelegram , Twitter or YouTube hopefully work as expected" from https://github.com/mozilla-mobile/fenix/issues/26307.

**Closed by delia-pop** 2022-08-10 10:18 UTC
Labels: 🐞 bug, needs:triage
