### ISSUE TITLE
[Bug] I connected to sync and disabled bookmark syncing. Later on I found bookmark syncing had been enabled again.

### ISSUE THREAD

**Issue by Mossop** [mozilla-mobile/fenix#7332] opened 2019-12-21 15:58 UTC
## Steps to reproduce

Don't know if this reproduces.

1. Connect to sync.
2. Go into sync settings and uncheck bookmarks.
3. A few hours later look at settings again.

### Expected behavior

Bookmark syncing should still be disabled.

### Actual behavior

Bookmark syncing is enabled.

### Device information

* Android device: Moto G7
* Fenix version: 3.0.1 build 13502256

**Comment by liuche** [comment] 2019-12-31 18:58
@grigoryk since we're pulling the enabled engines from Sync, any ideas why this might be happening? Seems like a bug in Sync, but also let us know if you have ideas otherwise.

**Comment by sv-sdeiac** [comment] 2020-01-06 09:12
Hello, I was able to reproduce this issue only one time using the fresh install of the Firefox Preview 3.0.1 #13502256 on LG G7 fit (Android 8.1).
My steps are:
1. Log-in on a valid account;
2. Wait till the first sync is over;
3. Uncheck the bookmarks option; 
4. Wait till the second sync is over;

Actual results:
After the second sync is finished, the bookmark option is enabled. 

In my opinion, is that the second sync is the problem here since the device pulls all the information from the server and forget the modification from the device made before the last sync. 

* Notes:
- I wasn't able to reproduce after the first attempt;
- I wasn't able to reproduce using Nexus 5 (Android 6.0.1),  Nokia 6 (Android 7.1.1) and Google Pixel (Android Q). - Please notice that those devices were tested after my first attempt at LG G7 fit.

**Comment by vesta0** [comment] 2020-01-06 17:40
We will coordinate with A-S team to fix this.

**Comment by mcarare** [comment] 2020-01-07 13:01
@vesta0 Currently the selection of what to sync is synced across devices. If you deselect one option on a device and sync, after you sync on another device the option will be unselected too.

Is this the intended behaviour? It seems odd, but from the code it seems to be intentional. 

This would also explain this issue, cause the first sync is treated "like" another device syncing with default values (all checked).

@grigoryk Can you help us to clarify what is the original design for this? TY!

**Comment by liuche** [comment] 2020-01-09 04:42
This is intended behavior - the engines enabled is "global", so if you enable a disabled engine on one of your devices, that selection will be enabled on all devices.

Debatable whether this is the "best" behavior, or what a user would expect, but this is how sync is intended to work right now, so I'm going to close this bug.

**Comment by Mossop** [comment] 2020-01-09 16:04
@liuche Can you clarify how the intended behaviour you describe relates to my original report? Are you saying that because I already have bookmark syncing enabled on my desktop that disabling bookmark syncing on my phone will never work?

**Comment by liuche** [comment] 2020-01-09 21:53
Yes, I just confirmed with the Sync team that device syncing preferences are per account, not per device. So if you were to disable bookmark syncing on one device, your bookmarks for that account stop syncing.

I'm not sure if that will change in the future, but that would be worth bringing up with the Sync team.

**Comment by Mossop** [comment] 2020-01-09 21:55
Why do we show the checkbox if it isn't possible to disable the bookmark syncing?

**Comment by liuche** [comment] 2020-01-09 21:59
I guess that depends on whether we consider Mobile devices to be full-featured clients - I don't think FxA differentiates between "type" of device, and it's possible that there are FxA users that sync between Mobile devices? but you do raise a reasonable concern, that users who consider their Mobile device a secondary device might not realize that they are turning off an engine for all of their devices.

**Comment by Mossop** [comment] 2020-01-09 22:07
I think maybe you misread my comment of six hours ago. If the expected behaviour of unchecking the checkbox on mobile is to disable bookmark syncing for all devices then I don't understand why this issue has been closed. This issue I reported was that a few hours after unchecking the bookmarks checkbox going back to the options showed that it was checked again. I had not touched the sync options in the meantime on any of my other devices.

**Comment by mcarare** [comment] 2020-01-13 13:35
@liuche To keep the current behaviour of global settings for sync engines but avoid unexpected behaviour like the one described in this issue I propose to disable the options during a sync.  What do you think? Can we also have UX sign off on this?

**Comment by topotropic** [comment] 2020-01-13 15:32
@Mossop did you uncheck multiple boxes at once? it seems that unchecking a box immediately triggers sync, that means whatever you first deselect syncs and the second one gets ignored.

**Comment by Mossop** [comment] 2020-01-13 17:40
No, just hte one.

**Comment by liuche** [comment] 2020-01-13 23:49
Interesting - I closed the issue since it sounded like our QA couldn't repro it, except when changing the global engine setting from another device, which is intended behavior.

Could you give us more details on this @Mossop?
- Is your desktop still syncing Bookmarks through your FxA, even though it is now unchecked and not syncing on Fenix?
- How often does Fenix stop syncing your bookmark engine?

@grigoryk or @linacambridge, could you think of something on the Sync side that could be causing an engine to unexpectedly stop syncing? Or how Fenix could be getting out of sync with the global FxA state?

**Comment by grigoryk** [comment] 2020-01-14 00:09
> I had not touched the sync options in the meantime on any of my other devices.

This is indeed pointing out a bug, somewhere in the Sync ecosystem. Settings are global, any connected device can control them, but they shouldn't change without an explicit user interaction.

**Comment by rfk** [comment] 2020-01-14 00:34
@grigoryk I feel like we've discussed some racy behaviour for Fenix in this area in the past, e.g. if the user goes into settings to edit their CWTS options at the same time as Fenix is refreshing those options in the background, then the local changes might be overwritten. Could that be what's happening here?

**Comment by grigoryk** [comment] 2020-01-14 03:24
It could be, yeah. I don't think we can say for certain one way or another without logs of this happening.

**Comment by rfk** [comment] 2020-01-17 02:41
> I feel like we've discussed some racy behaviour for Fenix in this area in the past, 

This is the one I was thinking of above: https://github.com/mozilla/application-services/issues/2161

**Comment by liuche** [comment] 2020-03-31 19:24
@jdragojevic could your team take a look at this? @vesta0 has seen it come up a few times, so could you prioritize it?

**Comment by jdragojevic** [comment] 2020-04-01 15:48
@liuche it sounds like this is a duplicate of https://github.com/mozilla/application-services/issues/2161 as mentioned by Ryan above.  I'd recommend we close this in favor of that and then try to work together to get that resolved.  At the moment, I believe we were hoping to get some input from @grigoryk.

**Comment by liuche** [comment] 2020-04-07 01:46
Duping to https://github.com/mozilla/application-services/issues/2161

**Closed** 2020-04-07 01:46 UTC
Labels: Feature:Sync, P2, S1, a-s, needs:investigation, needs:product, 🐞 bug
