### ISSUE TITLE
[Bug] menu button on different position on start screen and tab view

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#6260] opened 2019-10-24 20:28 UTC
### Steps to reproduce

1. switch between the start screen and an open tab
2. look at the menu button

### Expected behavior

menu button doesn't change the position

### Actual behavior

menu button jumps.

### Device information

* Android device: HTC U11 / Android 9.0
* Fenix version: master branch revision 6290c0c82610be319cdc39de3b633a28947bab1f

**Comment by nahuhh** [comment] 2019-10-27 11:04
(Good) Address bar when on tab/home page
- The spacing address bar on the start/tab page is done correctly. Works properly using a mouse as well. 
-touch zones/indicators on menu and + look good and are functional
- dark theme does not have a light grey border on the bottom

(Bad) Address bar when viewing a website
- input zone extends too far to the right.
- Menu button pushed over to the right / cutoff (has a rectangular touch zone)
- the tab button touch zone is oversized 
- occasionally mouse clicks on androidTV won't register   
- dark theme has a light grey border on the bottom

**Comment by nahuhh** [comment] 2019-11-01 06:37
Menu button jumping is more pronounced in landscape
Spacing looks good on the home/tab page, and squished on a web page 
 
![20191101_023212](https://user-images.githubusercontent.com/50635951/68006852-42cfab00-fc50-11e9-87a5-80a499513b14.gif)

**Comment by athomasmoz** [comment] 2019-11-27 17:33
Closing as duplicate of #6835

**Closed by athomasmoz** 2019-11-27 17:33 UTC
Labels: 🐞 bug
