### ISSUE TITLE
[Bug]: FxA account menu item doesn't always reflect latest account state

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26050] opened 2022-07-15 22:01 UTC
The option in the toolbar three dot menu doesn't always accurately reflect the latest account state. Now that https://github.com/mozilla-mobile/fenix/pull/25956 has introduced the `SyncStore`, the account property should be observable in order to make sure an accurate state is always reflects.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21028)

**Comment by jonalmeida** [comment] 2023-01-17 03:37
We have another issue that is actively worked on which this is similar to.

Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/25486

**Closed by jonalmeida** 2023-01-17 03:37 UTC
Labels: 🐞 bug, Feature:Sync
