### ISSUE TITLE
Enable adding search engines via opensearchdescription

### ISSUE THREAD

**Issue by fpunktk** [mozilla-mobile/fenix#15915] opened 2020-10-15 13:16 UTC
### What is the user problem or growth opportunity you want to see solved?
Users can't add search engines via opensearchdescription.
### How do you know that this problem exists today? Why is this important?
I've tried it, it is not mentioned in the knowledgebase for firefox for android, but here (indirectly) for firefox desktop: https://support.mozilla.org/de/kb/suchmaschinen-in-firefox-hinzufuegen-oder-entfernen
### Who will benefit from it?
Users who want to set a custom search engine that provides opensearchdescription.

**Comment by cadeyrn** [comment] 2020-10-15 13:28
Duplicate of #8889.

**Comment by liuche** [comment] 2020-10-22 00:46
Thanks for filing, this is a dupe.

**Closed by liuche** 2020-10-22 00:46 UTC
Labels: needs:triage
