### ISSUE TITLE
[Bug] Favicon for 2 pages of the same site do not load at the same time

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#5039] opened 2019-08-30 15:30 UTC
## Steps to reproduce
- Open Fenix
- Open the 2 following URLs: 
https://www.franceculture.fr/emissions/series/comment-achever-une-oeuvre-travail-et-processus-de-creation

https://www.franceculture.fr/religion-et-spiritualite/mes-quatre-annees-aux-cotes-du-pape-francois?utm_medium=Social&utm_source=Facebook#Echobox=1566724293
- go back to the Tab list

### Expected behavior
Both tabs should show the same favicon

### Actual behavior
Only one of the 2 tabs show the correct favicon, the other shows the default one.
Depending on the order you have opened the 2 urls, it will be either one of the other.

![image](https://user-images.githubusercontent.com/218971/64032889-a7d12c80-cb4b-11e9-8378-cd602d3c46de.png)

### Device information

* Android device: Redmin Note 7 Android 9
* Fenix version: #12420615

**Comment by codrut-topliceanu** [comment] 2020-05-26 11:45
I was unable to reproduce this on the latest nightly on Pixel 3 XL (Android 10). I could use a second pair of eyes on this :)

![tab icons work](https://user-images.githubusercontent.com/60002907/82896893-65644100-9f5f-11ea-8761-4a2f90a415cb.gif)

**Comment by klint** [comment] 2020-05-26 12:26
@codrut-topliceanu can you please check with the following 2 urls on your end?

While https://www.lemonde.fr is ok for me,
https://www.lemonde.fr/culture/article/2020/04/20/de-killing-eve-a-derapages-quatre-bonnes-raisons-de-rester-devant-la-tele_6037241_3246.html is not
Actually any page in lemonde.fr apart from the home page will fail.

**Comment by codrut-topliceanu** [comment] 2020-05-26 12:35
@klint Those pages load for me, and their icons look okay, I think. I'm afraid I don't have a Xiaomi Redmi to test it on :(

> Actually any page in lemonde.fr apart from the home page will fail.

Do you mean that the pages don't load at all?

Screenshot from Pixel 3xl:

<img src="https://user-images.githubusercontent.com/60002907/82900860-d0187b00-9f65-11ea-9617-c3eb8e201fb4.png" width = 220/>

**Comment by klint** [comment] 2020-05-26 13:21
Oops, I think I commented in the wrong issue, sorry for wasting your time :) 
And yes, I can confirm that I can't see this very issue happening anymore.
Thanks for your help anyway.

**Comment by LaurentiuApahideanSV** [comment] 2020-05-29 10:10
I was able to reproduce the issue on Firefox Preview Nightly 200229 (Build #21500608) using a OnePlus 6T by performing the following steps:

1. Open https://www.franceculture.fr;
2. Open any article in a new tab;
3. Tap the tab counter and wait for both of the favicons to load;
4. Restart Firefox Preview.

**Comment by codrut-topliceanu** [comment] 2020-06-05 13:21
Will be fixed by https://github.com/mozilla-mobile/android-components/issues/7264 and its PR : https://github.com/mozilla-mobile/android-components/pull/7266 .

**Comment by cadeyrn** [comment] 2020-06-05 13:43
Based on the explanation in https://github.com/mozilla-mobile/android-components/issues/7264 I guess #6340 has the same cause. Maybe worth checking #6340 once the patch landed and closing #6340 as a duplicate if it no longer happens.

**Comment by codrut-topliceanu** [comment] 2020-06-25 09:16
AC fix merged

**Comment by sflorean** [comment] 2020-07-17 12:29
Verified as fixed on Nightly 7/17 with Samsung Galaxy Note 10(Android 10), and LG G7 FIT (Android 8), following the steps from the description and additional str added.

**Closed by sflorean** 2020-07-17 12:29 UTC
Labels: P3, eng:qa:needed, needs:ac, 🐞 bug
