### ISSUE TITLE
[Bug] Tracking Protection is not Working

### ISSUE THREAD

**Issue by maxdule** [mozilla-mobile/fenix#6661] opened 2019-11-18 09:16 UTC
## Steps to reproduce
Open any site.

### Expected behavior
Shield should be there  - being blue when there is blocked content.

### Actual behavior
There is no shield, regardless of content that that should be blocked present or not. (settings are not changed - tracking protection is on).

NOTE: The site does not look the same as in standard Firefox, or Firefox on desktop (the standard Firefox for Android and Firefox on desktop behave in expected manner).

### Device information

* Android device: ?
Xiaomi Mi 9 SE
* Fenix version: ?
Firefof Preview 2.3.0 (Build #13031728)
18.0.0, ef631b6df
70.0-20191014032640

**Comment by cadeyrn** [comment] 2019-11-18 09:29
> There is no shield
> Firefof Preview 2.3.0

This is expected. The shield icon is not a feature of Firefox Preview 2.3.0.

**Comment by sv-ohorvath** [comment] 2019-11-18 10:16
I think this is a duplicate of #6042

**Closed by sv-ohorvath** 2019-11-18 10:16 UTC
Labels: 🐞 bug

**Comment by maxdule** [comment] 2019-11-18 10:40
@cadeyrn The icon itself is less of a problem.

The protection de facto **not working** is a bigger one. But does seem like a duplicate of #6042

**Comment by maxdule** [comment] 2019-11-22 12:37
@cadeyrn I may have not described the issue well - I just wanted to write less.

The icon is not an issue, **tracking protection not working IS**. As I already stated, open any website with known trackers, there is obvious difference between desktop Firefox, Firefox for Android and Firefox Preview.
