### ISSUE TITLE
Add a option to make the toolbar not hidden

### ISSUE THREAD

**Issue by konan8205** [mozilla-mobile/fenix#14257] opened 2020-08-26 23:43 UTC
### What is the user problem or growth opportunity you want to see solved?
See #14255. Some websites opening with Fenix have the compatibility issue of scrolling pages.

Other mobile web browsers, such as Chrome, have a fixed toolbar. I suggest making these toolbars available on Fenix as well to prevent this web issue.

### How do you know that this problem exists today? Why is this important?
There have always been problems with the websites I use often. I think that making the toolbar fixed is essential for the website with this compatibility issue.

### Who will benefit from it?
People who use the same site as me or who want the scrollbar to be fixed.

**Comment by Poopooracoocoo** [comment] 2020-08-27 05:07
dupe of #8801

**Comment by kbrosnan** [comment] 2020-08-27 05:10
Closing as duplicate

**Closed by kbrosnan** 2020-08-27 05:10 UTC
Labels: needs:triage
