### ISSUE TITLE
Toggle to get url bar on top or bot instead of forced bot. 

### ISSUE THREAD

**Issue by 1known** [mozilla-mobile/fenix#3704] opened 2019-06-27 13:10 UTC
When scrolling down on a page, on either small or large screen, but handed people will have issues not to touch the url bar and by accident slide up the share and bookmark quick access bar which is quite frustrating. 

UI wise, the url bar on bottom has a line that separates Android navigation buttons and doesn't integrate that well, as Firefox for android does with url bar on top, where the Android notification bar melds with the Firefox or Chrome url bar and adapting the color (like focus also does).

**Comment by dylmye** [comment] 2019-06-27 19:34
Dupe of #2115?

**Comment by ekager** [comment] 2019-06-27 20:28
Thanks for filing! Closing for #2115.

**Closed by ekager** 2019-06-27 20:28 UTC
Labels: 🌟 feature request

**Comment by cup** [comment] 2019-08-05 23:21
https://github.com/mozilla-mobile/fenix/issues/3721
