### ISSUE TITLE
Intermittent UI test failure - mediaSystemNotificationInPrivateModeTest

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#12645] opened 2020-07-16 19:08 UTC
### Firebase Test Run:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6097071229668485400/executions/bs.1cb0becdb5639ef1/testcases/2/test-cases

### Stacktrace:
```Kotlin
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
at org.mozilla.fenix.ui.robots.BrowserRobot.clickMediaPlayerPlayButton(BrowserRobot.kt:332)
at org.mozilla.fenix.ui.MediaNotificationTest$mediaSystemNotificationInPrivateModeTest$3.invoke(MediaNotificationTest.kt:147)
at org.mozilla.fenix.ui.MediaNotificationTest$mediaSystemNotificationInPrivateModeTest$3.invoke(MediaNotificationTest.kt:28)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:106)
at org.mozilla.fenix.ui.MediaNotificationTest.mediaSystemNotificationInPrivateModeTest(MediaNotificationTest.kt:145)
at java.lang.reflect.Method.invoke(Native Method)
```

### Build: master (discovered in https://github.com/mozilla-mobile/fenix/pull/12640)
(CC @sv-ohorvath)

**Comment by sv-ohorvath** [comment] 2020-08-05 07:48
Also seen on MediaNotificationTest.tabMediaControlButtonTest:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8498317768625901405/executions/bs.e6b6f5ca5b5337de/testcases/2/test-cases

**Comment by sv-ohorvath** [comment] 2020-08-25 11:21
With the strict mode policy violation pop-up the tests still fail: https://github.com/mozilla-mobile/fenix/runs/1012701657
No changes made to the test, but with a fix for the pop-up, tests pass: https://github.com/mozilla-mobile/fenix/runs/1012879656

I'll wait for https://github.com/mozilla-mobile/fenix/issues/13368 to get merged and re-test.

**Comment by sv-ohorvath** [comment] 2020-08-31 06:58
This is fixed, but I've seen it now fail (very rarely) with this error:
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertFalse(Assert.java:64)
at org.junit.Assert.assertFalse(Assert.java:74)
at org.mozilla.fenix.ui.robots.NotificationRobot.verifySystemNotificationGone(NotificationRobot.kt:45)

I'll keep this disabled until I find the cause/fix for that too.

**Closed** 2020-09-08 10:49 UTC
Labels: disabled-test, eng:ui-test, intermittent-test
