### ISSUE TITLE
[Bug] trust OS certs

### ISSUE THREAD

**Issue by I-Percy** [mozilla-mobile/fenix#18412] opened 2021-03-09 23:42 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean) No just fix this already. 

[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points) Annoying. This is quite redundant. 

[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information) No. 

## Steps to reproduce

Open a website with a DNS of dns.adguard.com

### Expected behavior

Should open the site

### Actual behavior
Reports the error "Secure Connection Failed" and upon selecting "Advanced" and then "Accept the Risk" nothing happens and it displays the same message again. Extremely frustrating.

### Device information
Device: Google Pixel 4XL (64Gb)
OS: Android 11

* Device vendor / model and Android version: Google/Pixel4XL and Android 11
* Firefox for Android version: ? (go to Settings -> About Firefox) Can't access this. Secure connection failed.

**Comment by I-Percy** [comment] 2021-03-09 23:44
Every site works just fine on Chrome but not on Firefox. Firefox works fine on my PC but not on my phone. Please fix.

**Comment by kbrosnan** [comment] 2021-03-10 00:26
You need to use Beta or Nightly and use the `about:config` pref `security.enterprise_roots.enabled`. This is a duplicate of #3728

**Closed by kbrosnan** 2021-03-10 00:26 UTC
Labels: needs:triage, 🐞 bug
