### ISSUE TITLE
[Bug]: text input gets deleted while typing in Facebook and Twitter posts.

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#20342] opened 2021-07-12 20:12 UTC
### Steps to reproduce

1. Open Facebook or Twitter websites
2. Create a new post
3. Type some words in the text input field, us usual

### Expected behaviour

The text should be captured correctly

### Actual behaviour

at some points, after a few words, the text I just have entered gets deleted and the caret jumps back at the beginning of the empty field...
It is quite impossible for me to use Facebook and Twitter websites.

This has been happening for some weeks now.

### Device name

Redmi Note 7

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

91.0a1

### Additional information

I use the Swiftkey keyboard, version 7.8.2.5

**Comment by ale82to** [comment] 2021-07-12 20:39
it happens on reddit too!

**Comment by mcarare** [comment] 2021-07-13 10:29
@klint I cannot reproduce this. Do you have maybe a video that shows the issue? Thank you!

**Comment by klint** [comment] 2021-07-13 13:49
See an example here (and please don't joke about my typing skills ;) ). It happens towards the end.
[https://photos.app.goo.gl/fydtEA3HEbzh1Fou7](url)

**Comment by jonalmeida** [comment] 2021-07-14 06:08
> See an example here (and please don't joke about my typing skills ;) ). It happens towards the end.
> [url](https://photos.app.goo.gl/fydtEA3HEbzh1Fou7)

@makotokato this looks similar to what I was seeing during Sync sign-in. Could this be related?

**Comment by SoftVision-LorandJanos** [comment] 2021-07-14 12:45
Hi @klint ! Thanks for the report!

I can't reproduce it either, it's very strange. Could you check with an other browser if it happens as well? Maybe another device if you have one? Thank you!

Tested using the latest Nightly (91.0a1 - 2021-07-14T05:06:58.101).

Verified on the following devices:
- Samsung Galaxy Tab 3 (Android 9).
- Google Pixel 4 (Android 11).
- LG Nexus 6 (Android 7.1.1).

**Comment by DD-Indeed** [comment] 2021-07-14 17:05
This happens on me too, writing tweets is bugged. If you try to add new line with Shift + Enter, it doesn't move the cursor to the next line. And, if you then move the cursor to the new line manually and add another new line, it doubles the first sentence you just wrote. So the whole row changing and typing is broken on the newest Firefox on Twitter at least.

**Comment by makotokato** [comment] 2021-07-16 01:37
@klint 

Do you can reproduce this on Firefox stable 89 or 90?  I would like to know whteher this issue is regression.

**Comment by klint** [comment] 2021-07-16 06:19
Hi. I just have tested with Firefox 90 and I was not able to reproduce it so far. With 91 and 92, it fails though (note that I have tested without any add-on, and it was failing as well).

**Comment by makotokato** [comment] 2021-07-16 07:04
Thanks. I guess that this occurs when you type "space" or select correct word from software keyboard's spellchecker (I cannot watch screen cast now, so I cannot confirm this for it).
 I try to reproduce this (I guess that it depends on timing issue)

**Comment by klint** [comment] 2021-07-16 08:12
Sorry, I had moved the video to the bin, now it is restored again. 
Unfortunately, I cannot tell whether it was one of the cases you mentionned, but I'll try to check more carefully in my next attempt.

**Comment by klint** [comment] 2021-07-17 07:57
It seems to be related to the autocorrection actually. I have deactivated it and the issue is gone...so far (but without autocorrection, it's quite impossible to write 😉)

**Comment by makotokato** [comment] 2021-07-20 14:47
Yes, I guess that it depends on composing state. GBoard uses this state when using autocorrect.

I found a reason (https://bugzilla.mozilla.org/show_bug.cgi?id=1721395) of this issue. (But I don't know whether all). So I will fix it soon.

**Comment by makotokato** [comment] 2021-07-20 14:50
And I guess that reporter uses SwiftKey. I will try it more.

**Comment by klint** [comment] 2021-07-20 14:55
> 
> 
> And I guess that reporter uses SwiftKey. I will try it more.

Yes I do: I use the Swiftkey keyboard, version 7.8.2.5

**Comment by klint** [comment] 2021-07-20 14:58
> And I guess that reporter uses SwiftKey. I will try it more.
Is the question for me? Yes, I do: 
> I use the Swiftkey keyboard, version 7.8.2.5
Thanks :)

**Comment by klint** [comment] 2021-07-29 08:39
Happens also on github.com now 😕.

**Comment by klint** [comment] 2021-08-06 08:51
Hi 
Maybe a stupid question, but has the fix for bug https://bugzilla.mozilla.org/show_bug.cgi?id=1721395 been integrated into Fenix Nightlies already? Thanks

**Comment by jonalmeida** [comment] 2021-08-06 22:48
@klint Yes, that change should be in the latest nightly. It landed in GeckoView 04/08/2021 and we're at GeckoView 06/08/2021.

**Comment by klint** [comment] 2021-08-07 09:09
Thank you for confirming. But I'm sad to report that the issue is still there. 😕

**Comment by clavelm** [comment] 2021-08-16 05:53
I'm getting the same problem here since some months.
I'm on Android (10, 11, Oxygen OS or LineageOS), using the latest Firefox Nightly and SwiftKey.
It seems to be on "intelligent" text zones (like here on github, or on Twitter,…) 
Sometimes, the whole text would disappear (and with no ctrl+z to rewind…). On Twitter, sometimes, the space would be missing after words, necessitating to press the space button many times to get a space before typing the next word.
Sometimes, a letter would stay after the cursor and it's impossible to go after it with navigation arrows or with a touch.
When inserting text, sometimes the cursor will jump after the following word instead of staying before it. 
It's happening a lot but not consistently, and I didn't do extensive testing to pinpoint the problem, for example by removing extensions and using a vanilla Firefox Nightly.
On the same device, I have that problem only on the Firefox app, not on any other app or browser (kiwi, Chrome, duckduckgo browser).

**Comment by gcp** [comment] 2021-08-18 10:54
Confirm this still reproduces with Nightly. It's quite infuriating as Swiftkey is the default on some Huawei devices I have.

**Comment by makotokato** [comment] 2021-08-18 11:42
If you can connect your Android phone via USB cable and you have Android SDK environment, could you capture a log via the following?

1. create `org.mozilla.fenix-geckoview-config.yaml` file with the following content.
```
env:
  MOZ_LOG: GeckoEditableSupport:5
```

2. `adb push org.mozilla.fenix-geckoview-config.yaml /data/local/tmp/.`
3. `adb shell am set-debug-app --persistent org.mozilla.fenix`
4. `adb logcat > debug.log`
5. Launch Fenix and you reproduce this issue.
6. Share or Attach `debug.log`.

After capturing log, you should remove org.mozilla.fenix-geckoview-config.yaml then run `adb shell am clear-debug-app`

**Comment by clavelm** [comment] 2021-08-25 11:46
@makotokato 
[debug.zip](https://github.com/mozilla-mobile/fenix/files/7046639/debug.zip)
Here a video while logging. The problems start around 1:10 after adding an @ in twitter. https://youtu.be/uQGj7nkyb2E

**Comment by robsmith11** [comment] 2021-08-28 16:12
This is an extremely annoying issue.  Many paragraphs are sometimes randomly deleted.   It's been happening for at least a month on Nightly with SwiftKey on my Huawei Mate 20 X.

**Comment by makotokato** [comment] 2021-08-30 13:09
@clavelm
Thanks.  Although I would like to confirm this issue, Does this issue mean that all inputted content is removed after you type "return" (around 1:25)?

**Comment by clavelm** [comment] 2021-08-30 13:42
> @clavelm
> Thanks. Although I would like to confirm this issue, Does this issue mean that all inputted content is removed after you type "return" (around 1:25)?

I'm not pressing "return" at that moment, but "."
The text is removed but the dot and an auto-insert trailing space are staying.

**Comment by gcp** [comment] 2021-08-30 14:12
Note that AFAIK Swiftkey is free in the Play Store and this problem is really easy to reproduce.

**Comment by makotokato** [comment] 2021-08-30 14:52
Thanks.  I guess that this occurs when you click ".".

```
08-25 13:31:14.764 30694 30733 I Gecko   : [Child 30694: Main Thread]: D/GeckoEditableSupport IME: NOTIFY_IME_OF_SELECTION_CHANGE: SelectionChangeData={ mOffset=6, mString="" (Length()=0), GetWritingMode()=h-ltr, mReversed=false, mCausedByComposition=true, mCausedBySelectionEvent=false, mOccurredDuringComposition=false }
08-25 13:31:14.764 30694 30733 I Gecko   : [Child 30694: Main Thread]: D/GeckoEditableSupport IME: NOTIFY_IME_OF_COMPOSITION_EVENT_HANDLED

08-25 13:31:17.294 30694 30733 I Gecko   : [Child 30694: Main Thread]: D/GeckoEditableSupport IME: IME_REPLACE_TEXT: text=""
08-25 13:31:17.295 30694 30733 I Gecko   : [Child 30694: Main Thread]: D/GeckoEditableSupport IME: Current selection: { mOffset=6, mData="", Length()=0, EndOffset()=6 }
08-25 13:31:17.338 30694 30733 I Gecko   : [Child 30694: Main Thread]: D/GeckoEditableSupport IME: NOTIFY_IME_OF_TEXT_CHANGE: TextChangeData={ mStartOffset=0, mRemoveEndOffset=6, mAddedEndOffset=0, mCausedOnlyByComposition=false, mIncludingChangesDuringComposition=false, mIncludingChangesWithoutComposition=true }
08-25 13:31:17.339 30694 30733 I Gecko   : [Child 30694: Main Thread]: D/GeckoEditableSupport IME: NOTIFY_IME_OF_SELECTION_CHANGE: SelectionChangeData={ mOffset=0, mString="" (Length()=0), GetWritingMode()=h-ltr, mReversed=false, mCausedByComposition=false, mCausedBySelectionEvent=false, mOccurredDuringComposition=false }
08-25 13:31:17.341 30694 30733 I Gecko   : [Child 30694: Main Thread]: D/GeckoEditableSupport IME: IME_REPLACE_TEXT: text="…"
08-25 13:31:17.341 30694 30733 I Gecko   : [Child 30694: Main Thread]: D/GeckoEditableSupport IME: Current selection: { mOffset=0, mData="", Length()=0, EndOffset()=0 }
```

Software keyboard requests that it set selection to all unfortunately, Then text is removed.  I try to reproduce this. (Swiftkey sometimes seted unexpected selection when I debugged Swiftkey 1 or 2 years ago, so I suspect Swifteky behavior and we need more workaround for it.).

**Comment by makotokato** [comment] 2021-08-31 02:13
This seems to be regression by https://bugzilla.mozilla.org/show_bug.cgi?id=1713334 if this occurs from 91.

**Comment by makotokato** [comment] 2021-09-09 07:50
@klint 
Do you verify this on Firefox Nightly (94+)?

**Comment by klint** [comment] 2021-09-09 08:25
> 
> 
> @klint or @clavelm
> Do you verify this on Firefox Nightly (94+) since I have fixed my known issue on 94?

Yes, I do! So far, so good on my side. Thanks a lot.

**Comment by fm-sys** [comment] 2021-09-11 11:14
I'm using the regular Firefox mobile and I'm affected as well.

```
91.4.0 (Build #2015831131)
AC: 91.0.17, 67ce1935b5
GV: 91.0.3-20210830133508
AS: 79.0.0
```
As far as I understood it was fixed in the nightlys. Can we backport the fix or when can I suspect the fix to be released? This issue is very annoying so should be released as fast as possible, please! 🙏

**Comment by makotokato** [comment] 2021-09-14 03:21
@fm-sys 
Also, this will be fixed in Firefox 93 that will be released at 3 weeks later.

**Comment by amedyne** [comment] 2022-02-01 18:34
@klint Can you validate if this is working now? Thank you!

**Comment by fm-sys** [comment] 2022-02-01 20:00
As far as I can tell, it seems to be fixed... Thank you!

**Closed** 2022-02-01 20:16 UTC
Labels: 🐞 bug, Feature:Browsing
