### ISSUE TITLE
Re-connect or Remove Sync

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#3946] opened 2019-07-09 04:41 UTC
## User Story
- As a user, when sync issues occur, I want an option to re-connect/login or remove my account to prevent any further warnings to pop up ([screen](https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/357473106))

### Acceptance Criteria
- I know that sync has failed and I have the option to reconnect
- I know that sync has failed and I have the option to remove my account

**Comment by sblatz** [comment] 2019-07-10 18:44
This is a dupe of https://github.com/mozilla-mobile/fenix/issues/2327

**Comment by sblatz** [comment] 2019-07-10 18:44
We can have QA verify to ensure this functionality is here.

**Comment by AndiAJ** [comment] 2019-07-11 14:00
Hi **verified as fixed** on **latest build from master** using the following devices:
• Google Pixel 3A (Android 9)
• Samsung Galaxy S8+ (Android 8)
• Samsung Galaxy S7 (Android 7)

► Video from Google Pixel 3A
![20190711_094613](https://user-images.githubusercontent.com/51314259/61057104-4cad7400-a3fd-11e9-8340-f62b074d5a3c.gif)

**Closed by AndiAJ** 2019-07-11 14:00 UTC
Labels: Feature:Sync, QA verified, must, ready for eng
