### ISSUE TITLE
[Bug] Open in new tab from PWA doesn't switch to main app

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#6142] opened 2019-10-20 08:39 UTC
## Steps to reproduce

 * Go to e.g. twitter.com.
 * Add to home screen.
 * Click on your new homescreen icon.
 * Press and hold a link from a tweet in your timeline.
 * Press "open in new tab"

### Expected behavior

 * Switch to the new tab by opening the main Firefox Preview app.

### Actual behavior

 * Seems to do nothing (other than showing a toast). Actually opens the tab but you have to manually switch over.

### Device information

* Android device: Galaxy A20
* Fenix version: Nightly 191017 18:01 (Build #12901814)
📦: 16.0.0, ab2555b20
🦎: 71.0a1-20191004094656

**Comment by emilio** [comment] 2019-10-20 08:42
Update: Apparently the tabs are in the Fenix app, but you have to manually switch to the browser to file a bug report to notice ;)

**Comment by NotWoods** [comment] 2019-10-20 20:25
Partially a duplicate of #5085. We're not handling links that open a new tab properly at the moment.

I'll update this issue to focus on the context menu portion.

**Comment by NotWoods** [comment] 2019-11-08 16:38
Closing since we removed the context menu option for now.

**Closed by NotWoods** 2019-11-08 16:38 UTC
Labels: Feature:PWA, 🐞 bug
