### ISSUE TITLE
Move top sites to bottom

### ISSUE THREAD

**Issue by LinAGKar** [mozilla-mobile/fenix#15183] opened 2020-09-18 06:55 UTC
Currently, the top sites are at the top of the new tab page, making them hard to reach with one hand, while the bottom is occupied by the useless collections placeholder. It would be better if the top sites where moved to the bottom, at least if you have no collections.

**Comment by jenabaivab** [comment] 2020-09-18 10:28
Yes this would be very helpful.

**Comment by hwinnemoe** [comment] 2020-09-18 11:13
Duplicate of #14536

**Comment by kbrosnan** [comment] 2020-09-18 19:00
Closing as a duplicate.

**Closed by kbrosnan** 2020-09-18 19:00 UTC
Labels: needs:triage
