### ISSUE TITLE
FNX2-15161 ⁃ [Bug] Firefox Beta and Nightly fail to download anything from any website

### ISSUE THREAD

**Issue by parvinderandroid** [mozilla-mobile/fenix#12306] opened 2020-07-06 10:08 UTC
## STEPS TO REPRODUCE
1. Open Firefox (Beta or Nightly)
1. Open https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.19.5
1. Click on Assets
1. Click on NewPipe_v0.19.5.apk
1. Start Download

### EXPECTED BEHAVIOUR
1. Downloading begins
1. Downloading finishes

### ACTUAL BEHAVIOUR
1. Downloading immediately fails

### DEVICE INFORMATION
* Android device: Huawei Honor 8 Pro (DUK-L09) - Android 9.0
* Fenix version: 79.0.0-beta.4 & Nightly 200705 06:01

### VIDEO OF ISSUE:
https://i.imgur.com/H9Qwxfc.mp4

**Comment by cadeyrn** [comment] 2020-07-06 10:16
I cannot reproduce, downloads works without problems.

Firefox 79 Beta 5
OnePlus 7T Pro McLaren Edition
Oxygen OS 10.0.9 (Android 10)

**Comment by SS1113** [comment] 2020-07-06 10:51
@parvinderandroid 

Isn't this same as the already reported bug  #12297, #12280. Please do not file multiple issues for the same bug. You can edit the same issue by clicking on 3-dot menu on the description box and click 'edit' and enter any updates about the issue you are facing.

Thanks! :)

**Comment by Diana-Rus** [comment] 2020-07-06 11:47
Hi, i didn't managed to reproduce your issue with neither Firefox Beta 79.0.5 nor with Nightly 7/6. Tried with Google Pixel 3 XL (Android 9) and Samsung Galaxy S9 (Android 8).
I also tried with a Huawei P10 device with Android 9 and EMUI (9.1.0) on latest Nightly. The apk files can be downloaded correctly.
I'll close this issue, but in case you encounter an issue with the app, please see whether there is one similar or create a new one 😊.
Note: I cal also see from your video that the network is not that stable, especially the cellular data, it can also because of that.
Thank you!

**Closed** 2020-08-20 14:06 UTC
Labels: needs:triage, 🐞 bug
