### ISSUE TITLE
FNX-12473 ⁃ Dark Mode doesn't works on webpages

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#11524] opened 2020-06-12 17:24 UTC
Most of the times Dark mode doesn't works on many websites. Even with Dark reader installed

Steps to reproduce: 
Open google.com
Open GitHub.com
Open digitalocean.com

Fenix version:
Nightly 200611 06:01 (Build #21630608)
45.0.20200610130052, e5839f921
GV: 79.0a1-20200609092134
AS: 60.0.0

Device: Xiaomi Redmi Note 4

**Comment by starsep** [comment] 2020-06-12 17:45
I confirm that Dark Reader doesn't work on this nightly version. When I navigate to Add-ons -> Dark Reader it keeps showing `Loading, please wait`. The same version of Dark Reader (4.9.9) works fine on current Google Play release of Firefox Preview.

**Comment by sheikh-azharuddin** [comment] 2020-06-12 18:10
> I confirm that Dark Reader doesn't work on this nightly version. When I navigate to Add-ons -> Dark Reader it keeps showing `Loading, please wait`. The same version of Dark Reader (4.9.9) works fine on current Google Play release of Firefox Preview.

Probably this is broken since last few updates...I have seen another guy reported this few days ago

**Comment by yoasif** [comment] 2020-06-12 18:15
Dupe of https://github.com/mozilla-mobile/fenix/issues/11336

**Comment by ekager** [comment] 2020-06-12 18:16
closing for #11336

**Closed** 2020-08-11 04:14 UTC
Labels: needs:triage
