### ISSUE TITLE
FNX-5339 ⁃ OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Furt...

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#1931] opened 2019-04-23 17:52 UTC
https://sentry.prod.mozaws.net/operations/fenix/issues/5556607/

```
IllegalArgumentException: Required value was null.
    at org.mozilla.fenix.browser.BrowserFragment.getSessionByIdOrUseSelectedSession(BrowserFragment.kt:2)
    at org.mozilla.fenix.browser.BrowserFragment.access$getSessionByIdOrUseSelectedSession(BrowserFragment.kt:1)
    at org.mozilla.fenix.browser.BrowserFragment$onStart$1.accept(BrowserFragment.kt:5)
...
(13 additional frame(s) were not displayed)

OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | Required value was null.
    at org.mozilla.fenix.components.toolbar.ToolbarUIView$$special$$inlined$apply$lambda$2.invoke(ToolbarUIView.kt:1)
...
(12 additional frame(s) were not displayed)

The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | Required value was null.
```

**Comment by cpeterso** [comment] 2019-04-23 17:53
This crash first started on April 16.

**Comment by sblatz** [comment] 2019-05-14 20:29
This was last seen April 27th, and we've made changes to this portion of the code that would've been causing this crash. How should we proceed @vesta0?

**Comment by sblatz** [comment] 2019-05-15 17:21
I'm closing this as fixed as we haven't been able to reproduce since April 27th. Please re-open if you encounter it again.

**Closed** 2020-08-11 13:21 UTC
Labels: P1, b:crash
