### ISSUE TITLE
[Bug]: Missing content SUMO page for TCP

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#26956] opened 2022-09-13 12:28 UTC
### Steps to reproduce

1. Perform a Clear Data. 
2. Visit a webpage and observe the TCP CFR displayed above the toolbar.
3. Tap the hyperlink in the CFR. 
4. Observe the SUMO page opened.
### Expected behaviour.

The content on the https://support.mozilla.org/1/mobile/%25VERSION%25/%25OS%25/%25LOCALE%25/enhanced-tracking-protection-android SUMO page is displayed.

### Actual behaviour

The content is missing and the "Page no found" error is displayed.

### Device name

Xiaomi Pad5 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 106.0a1 - 09/13

### Additional information

<img src="https://user-images.githubusercontent.com/108326843/189899913-7d887873-9780-4c7b-81a2-3ebc11f02458.JPEG" width="50%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21552)

**Comment by kbrosnan** [comment] 2022-09-13 17:26
SUMO will build the page when it gets closer to the release.

**Comment by cpeterso** [comment] 2022-11-04 21:36
The updated SUMO is now live. The Total Cookie Protection section is only visible for visitors with Firefox >= 107.

https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-android#mobile::m107

**Comment by cpeterso** [comment] 2022-11-04 21:40
Oops. I see the problem is that the CFR points to a different URL path:

CFR: `/kb/enhanced-tracking-protection-android`
Actual page: `/kb/enhanced-tracking-protection-firefox-android`

**Comment by cpeterso** [comment] 2022-11-04 22:05
Reopening. Even if the SUMO team adds a redirect, we should fix the URL in the CFR code so we can remove the redirect later.

**Comment by cpeterso** [comment] 2022-11-08 18:37
The SUMO redirect from the TCP CFR's URL https://support.mozilla.org/kb/enhanced-tracking-protection-android to the article's URL https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-android is now live.

Ryan Johnson on SUMO team recommends that we replace the TCP CFR's SUMO URL with an "in-product" link. I'm waiting for more details from Ryan.

**Comment by Mugurell** [comment] 2022-11-14 11:53
@cpeterso @DreVla Just added added a patch that would directly open https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-android.
But it seems like in this case the `inproduct` param is missing - while it is automatically added in the redirect process for the old link - https://support.mozilla.org/1/mobile/108.0a1/Android/en-US/enhanced-tracking-protection-android.
https://support.mozilla.org/1/mobile/108.0a1/Android/en-US/enhanced-tracking-protection-firefox-android doesn't seem to exist.
Can we get the full URL to use?

For reference this is the link previously received from SUMO - https://support.mozilla.org/1/mobile/%25VERSION%25/%25OS%25/%25LOCALE%25/enhanced-tracking-protection-android ([Jira specs](https://mozilla-hub.atlassian.net/browse/FNXV2-20991?focusedCommentId=573995)) - currently used in the app.

**Comment by cpeterso** [comment] 2022-11-15 05:44
@Mugurell Sorry this has gotten so confusing. I had to ask the SUMO web engineer to explain the difference to me.

He says the Fenix code should use `https://support.mozilla.org/1/mobile/%25VERSION%25/%25OS%25/%25LOCALE%25/enhanced-tracking-protection-android`

Note that this URL uses `enhanced-tracking-protection-android` (without "firefox"), even though the SUMO article's URL includes "firefox" like https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-android! That is OK.

Example:

`https://support.mozilla.org/1/mobile/%25VERSION%25/%25OS%25/%25LOCALE%25/enhanced-tracking-protection-android` will be converted to https://support.mozilla.org/1/mobile/108.0a1/android/en-US/enhanced-tracking-protection-android, which SUMO will redirect to the real page https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-android.

**Comment by Mugurell** [comment] 2022-11-15 07:50
> @Mugurell Sorry this has gotten so confusing. I had to ask the SUMO web engineer to explain the difference to me.
> 
> He says the Fenix code should use `https://support.mozilla.org/1/mobile/%25VERSION%25/%25OS%25/%25LOCALE%25/enhanced-tracking-protection-android`
> 
> Note that this URL uses `enhanced-tracking-protection-android` (without "firefox"), even though the SUMO article's URL includes "firefox" like https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-android! That is OK.


It's great that we got the full URL to use.

What the SUMO team provided now
> https://support.mozilla.org/1/mobile/%25VERSION%25/%25OS%25/%25LOCALE%25/enhanced-tracking-protection-android

is exactly what we got before ([Jira specs](https://mozilla-hub.atlassian.net/browse/FNXV2-20991?focusedCommentId=573995)) 

> https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/enhanced-tracking-protection-android

and what is currently used in the app and also the link from the original comment of this ticket:

https://github.com/mozilla-mobile/fenix/blob/be7c0ba4019e07b92f8d9ecbf18cce5754bc2b24/app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt#L45


So it seems like there is nothing to do.

**Comment by cpeterso** [comment] 2022-11-15 08:13
> So it seems like there is no update needed.
> When this ticket was opened the SUMO page wasn't up.
> It seems that in this time it got published with the right content and users can access the intended URL by tapping the link in the CFR.

I'm glad no code change is needed after all. In that case, I'll close this bug.

The app's in-product URL ("enhanced-tracking-protection-android") wasn't working last week, even though the ETP SUMO article was up. I guess the SUMO team didn't point the in-product URL to the real SUMO article until I ask them about redirects last week.

**Comment by SoftVision-LorandJanos** [comment] 2022-11-17 06:13
Verified as fixed on the latest Nightly 109.0a1 (2022-11-17) build.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-11-17 06:13 UTC
Labels: 🐞 bug, eng:qa:needed, needs:triage, S4, TaskContinuity
