### ISSUE TITLE
[Bug]: Dark theme, URL share menu, contrast too low

### ISSUE THREAD

**Issue by HubKing** [mozilla-mobile/fenix#23005] opened 2021-12-29 13:22 UTC
### Steps to reproduce

1. Use "Dark theme" for FireFox.
2. Go to mobile YouTube website.
3. Open any video.
4. Click the "Share" button below the video.

### Expected behaviour

Readable text.

### Actual behaviour

<img width="270" alt="screen" src="https://user-images.githubusercontent.com/10900489/147666494-167b3c45-f560-4aa7-b6d7-df5f801f6abf.png">

In the "All Actions" section, the icon labels are barely readable because the contrast is very low.

### Device name

Pixel 3

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

95.2.0

**Comment by yagueto** [comment] 2021-12-29 14:00
Might be a duplicate of #18768

**Comment by SoftVision-LorandJanos** [comment] 2021-12-30 07:10
Hi @HubKing! Thank you for your report!
I can confirm the issue is reproducible.
The fix for the above mentioned bug should fix this one as well, so I will close this one as a duplicate.
Tested on: latest Nightly (2021-12-30).
Device used: Xiaomi Mi11 Lite (Android 11).

**Closed by SoftVision-LorandJanos** 2021-12-30 07:10 UTC
Labels: 🐞 bug, needs:triage
