### ISSUE TITLE
White "Run in private browsing" icon

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#14939] opened 2020-09-10 11:53 UTC
## Prerequisites
Set Fenix's theme to **Light**

## Steps to reproduce
1. Install any of the featured Add-ons
2.  Tap on the installed add-on from the Add-ons page.
3. Check the elements

### Expected behavior
Properly displayed "Run in private browsing" icon

### Actual behavior
White Run in private browsing" icon

### Device information

* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly 200910

### Notes
❗ Properly displayed on Google Pixel 3a (Android 10)

► Screenshot 
![rsz_screenshot_20201020-144510](https://user-images.githubusercontent.com/51314259/92725854-6c2f8c00-f375-11ea-9473-9eddcf53c78a.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6692)

**Comment by hwinnemoe** [comment] 2020-09-10 11:58
Related to/Duplicate of #14933

**Comment by cadeyrn** [comment] 2020-09-18 07:29
This issue should be reopened. It's related to #14933 because it's probably a regression from the same change but it's not a duplicate. While all devices were affected by #14933 this issue only exists on some devices (I can't reproduce) and my PR for #14933 didn't do anything with the icon in the add-ons manager.

**Comment by AndiAJ** [comment] 2020-09-18 07:36
Indeed, while the icon from Settings is displayed properly, the "Run in private browsing" icon is white for each extension.

**Comment by hwinnemoe** [comment] 2021-05-03 13:45
I can still reproduce on Nightly 90.0a1 (Build #2015808073)
AC: 90.0.20210502143118, ef96feb9c
GV: 90.0a1-20210502092952
AS: 75.2.0.

**Comment by lobontiumira** [comment] 2021-06-02 13:10
Reproducible on Beta 90.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by hwinnemoe** [comment] 2021-12-01 13:57
Still reproducible on

96.0a1 (Build #2015848873), 9fa9ae337+
AC: 96.0.20211130143618, 395aa21e64
GV: 96.0a1-20211130093553
AS: 86.2.0

2021-12-01T05:13:00.119862

**Comment by Mugurell** [comment] 2022-10-17 06:34
> I can't reproduce this on the latest nightly. CC @Mugurell

Thank you for checking.
@AndiAJ to confirm and close if this has been fixed on all releases.

**Comment by AndiAJ** [comment] 2022-10-17 08:35
👋🏽 @Mugurell , unfortunately it's still reproducible on the latest Nightly build 107.0a1 from 10/17 using a OnePlus A3 (Android 6.0.1)

► Screenshot
<img width="523" alt="image" src="https://user-images.githubusercontent.com/51314259/196130135-45e58b0e-01ad-4799-a847-3e599efc8f66.png">

**Closed** 2023-01-31 00:30 UTC
Labels: 🐞 bug, S2, Feature:WebExtensions
