### ISSUE TITLE
[Bug] QR code scan issues on OnePlus A3

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#4000] opened 2019-07-11 12:56 UTC
## Prerequisites
Log in to Firefox desktop with a valid user and navigate to firefox.com/pair and generate the pairing QR code

## Steps to reproduce
1. Tap Turn on sync
2. Tap Ready to scan

### Expected behavior
Scan of the QR code should be performed immediately / reliably.

### Actual behavior
Somtimes nothing happens, the camera seems to distort the image

### Device information

* Android device: OnePlus A3 (Android 6)
* Fenix version: Latest build from master

### Notes

[VIdeo](https://user-images.githubusercontent.com/51314259/74909790-ba714380-53c1-11ea-9c61-c5cf2c19f060.gif)

**Comment by kumarharsh** [comment] 2019-07-20 21:11
+1 - the camera opens but it is *never* able to scan the square QR code. I think it's because the camera is squishing the image in the horizontal direction, so the QR code square is **taller than it is wide** in the image captured by the camera. Please look into this.

**Comment by sblatz** [comment] 2019-07-22 20:31
Labeling as a p2 as it could hurt FxA onboarding and turn new users away. Let's investigate if this is device specific.

**Comment by csadilek** [comment] 2019-07-22 22:56
@sblatz might be worth verifying if this still happens now that https://github.com/mozilla-mobile/fenix/issues/3889 is fixed in Nightly.

**Comment by sblatz** [comment] 2019-07-23 16:56
@csadilek thanks for that fix! Going to throw a QA needed on this.

**Comment by AndiAJ** [comment] 2019-07-24 09:18
Hi, still no luck, the image seems to be distorted **on the latest Nightly Build #190724 from 24/7** using 
• OnePlus 6T (Android 9)
• OnePlus 3 (Android 6.0.1)

[OnePlus 6T video](https://drive.google.com/open?id=115u44L6n8z01d1nI0L2C1bCSF2EGOKb7)
[OnePlus 3 ](https://drive.google.com/open?id=1EGJMM0j9dKFh0LuyLTP8XfkIWZxYB7yj)

**Comment by AndiAJ** [comment] 2019-10-17 10:17
Hi, the scanning issue is happening when trying to scan a QR code from the URL bar as well using a OnePlus 3 (Android 6.0.1) on:
 
• Fenix 2.2.0-rc.2
• Nightly Build #12900612 from 17/10

**Comment by vesta0** [comment] 2019-12-16 18:58
Adding this to the AC board - this is high priority as it impacts a lot of devices and their ability to login to FxA.

**Comment by AndiAJ** [comment] 2020-01-09 09:12
Reproducible on **Fenix 3.0.2 Build #20081833 from 1/8** using a OnePlus A3 (Android 6)

**Comment by kumarharsh** [comment] 2020-01-09 09:30
Which QR Codes can Firefox Preview scan? Almost all codes in the Wikipedia article are not scannable using a OnePlus 6 device: https://en.wikipedia.org/wiki/QR_code

**Comment by cadeyrn** [comment] 2020-01-10 19:26
FWIF I can **not** reproduce with OnePlus 7T Pro and Android 10.

**Comment by csadilek** [comment] 2020-02-19 00:28
@AndiAJ We were able to reproduce this on the OnePlus6T, scanning the code from firefox.com/pair. We've verified and landed a fix, but couldn't get a OnePlus A3 to verify. Can you confirm this is working now (should be on tonight's build)?

**Comment by AndiAJ** [comment] 2020-02-19 07:53
Hi @csadilek , I've re-checked this matter on the latest **`Nightly 200219 Build #20500606 from 2/19`** using the following devices:
• OnePlus6T (Android 9)
• OnePlus A3 (Android 6)

It still doesn't work properly, 1 out of 10 attempts were successful on each device.
The isolated successful attempt per device happened after I when back to the Fenix Settings screen and afterwards re-tried.

**Comment by csadilek** [comment] 2020-02-19 14:04
@AndiAJ Sorry for the additional roundtrip. I don't see the fix being applied in latest Fenix either. Will investigate.

**Comment by csadilek** [comment] 2020-02-19 20:50
@AndiAJ OK, the fix is now in the latest Nightly "200219 18:01" and I can no longer reproduce the problem on the OnePlus 6T. Can you take another look, please? :)

**Comment by AndiAJ** [comment] 2020-02-20 07:30
Hi @csadilek , I've re-checked this matter on the latest Nightly 200219 Build #20510607 from 2/20 using the following devices:
• OnePlus 6T (Android 9)
• OnePlus A3 (Android 6.0.1)
• OnePlus A2005 (Android 6.0.1)

On both the OnePlus 6T & OnePlus A2005 scan now works flawlessly.
On the other hand on the OnePlus A3 there still seem to be some issues, namely the camera seems to be zooming in too much. 

► Video from OnePlus6T 
![20200220-090839](https://user-images.githubusercontent.com/51314259/74909942-058b5680-53c2-11ea-9ca3-d87ee80c3b68.gif)

► Video from OnePlus A3 
![20200220-091209](https://user-images.githubusercontent.com/51314259/74909790-ba714380-53c1-11ea-9c61-c5cf2c19f060.gif)

► Video from OnePlus A2005
![20200220-092251](https://user-images.githubusercontent.com/51314259/74910594-8860e100-53c3-11ea-8cd4-c23abc36a47e.gif)

@csadilek - Please review and share your thoughts ☺️ 
I'll remove the QA needed label until further notice.

**Comment by csadilek** [comment] 2020-02-20 15:41
Thanks for verifying. As this is working fine now on the OnePlus 6, OnePlus 7T, and A2005 as well as various other devices we tested, I am updating the title here and marking this for triage again and suggest lowering priority.

I'll try and get an A3 to test and we can revisit.

**Closed** 2021-05-15 20:31 UTC
Labels: Feature:QRCode, Feature:Sync, P3, needs:investigation, wontfix, 🐞 bug
