### ISSUE TITLE
[Bug] Tabs list focus set to bottom of list of synced tabs, seemingly random

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#14525] opened 2020-08-31 12:25 UTC
## Steps to reproduce
Not clear of the steps to reproduce, but:
1. Be signed into Firefox account and select to sync tabs
2. Have other synced devices with open tabs to sync (I have many... maybe 1000 in total, please don't judge me! 😆)
3. Open the tabs list

### Expected behaviour
Focus in the tab list is on the currently live tab and this is shown on the display.

### Actual behaviour
Seemingly at random, my tabs list opens close to the bottom of my list of all tabs, nowhere near my tabs which are currently open on Fenix.

### Device information

* Android device: Nokia 8 Android 9
* Fenix version: 

Nightly 200830 06:01 (Build #2015760947)
AC: 57.0.20200829130559, 1b8b72ac3
GV: 82.0a1-20200827093043
AS: 61.0.13

**Comment by jonalmeida** [comment] 2020-09-01 13:15
Duplicate of #13905.

**Closed by jonalmeida** 2020-09-01 13:15 UTC
Labels: Feature:SyncTabs, 🐞 bug
