### ISSUE TITLE
FNX3-16425 ⁃ [Bug] Blob downloads - Can't download certain file type

### ISSUE THREAD

**Issue by nikoloskid** [mozilla-mobile/fenix#2579] opened 2019-05-16 20:12 UTC
## Steps to reproduce
1. When trying to download .conf file, I am getting Firefox Preview can't download this file type

### Device information
* Android device: Huawei P20 Lite
* Fenix version: 1.0.1920

File types mentioned in this issue:

* .conf
* .cert
* .pdf

**Comment by vesta0** [comment] 2019-07-02 16:55
Thanks for reporting this @nikoloskid could you provide steps to reproduce? Are you downloading from a authenticated site (requiring login)?

**Comment by vesta0** [comment] 2019-07-15 17:25
@sv-ohorvath please let us know if you can re-produce this.

**Comment by sv-ohorvath** [comment] 2019-07-16 12:11
I've downloaded 2 types: .conf and .config files from an email, no problems downloading from there.
devices: Huawei P20 lite (Android 9), Galaxy S8 (Android 9).
@nikoloskid If you're still experiencing this problem, please give us more details and reopen the bug. Thnak you!

**Comment by evertonstz** [comment] 2019-09-27 15:13
This problem still happens on the latest Fenix from Playstore, here's how you can reproduce it:

- open Fenix, paste this link to a .cia file that's hosted on Mega: https://mega.nz/#!KVg0DSaa!Ub2Mcq45UJF_LOG0PtGum3sQpeWhlm4eTmZSMEs9fDM

- download the file, you'll get the following error (same as OP): https://imgur.com/a/YJP3p8x

**Comment by ripdog** [comment] 2019-10-01 03:09
I encountered this bug when trying to download a .conf file from Mullvad. It was my generated wireguard config.

**Comment by wisniewskit** [comment] 2019-10-08 13:39
This is also happening for files on Mega, as reported at https://webcompat.com/issues/41768

This link can be saved fine in Fennec, but Fenix rejects it: https://mega.nz/#!j7x0wQDR!j7YAxYNDxILDgpdpZaQrEIC_SphjObeyaG54BU4J-V8

**Comment by sblatz** [comment] 2019-11-12 20:31
QA can you verify this is still happening?

**Comment by evertonstz** [comment] 2019-11-12 20:57
> 
> 
> QA can you verify this is still happening?

Yes, still happens.

**Comment by sblatz** [comment] 2019-11-12 22:09
@evertonstz I believe this would be fixed in our nightly & beta build :)

**Comment by sv-ohorvath** [comment] 2019-11-13 09:19
Still reproducing on Nightly 191113. Can't download the files evertonstz and wisniewskit shared here.
Devices: Pixel (Android 10), Mi 4i (Android 5.0.2).

**Comment by sv-ohorvath** [comment] 2019-11-21 09:50
Can't download a jpg file from: https://www.wallpaperflare.com/the-joker-wallpaper-heath-ledger-monochrome-batman-movies-wallpaper-peaec/download/1080x2061

**Comment by dwoffinden** [comment] 2019-12-03 09:15
I get this trying to download PDF statements from my bank (tsb.co.uk) :/

**Comment by ripdog** [comment] 2019-12-03 20:41
Just my observations, but the commonality between these issues seems to be that these files are generated in JS, rather than being downloaded directly. For example, my wireguard configuration file is generated by JS as it contains sensitive information not uploaded to the remote server. That wallpaperflare.com link performs download using 

```javascript
            canvas.toBlob(function(blob){
                saveAs(blob, 'wallpaperflare.com_wallpaper.jpg',"image/jpeg");
            },"image/jpeg",1);
```


See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1501735

**Comment by yaomtc** [comment] 2019-12-18 23:30
This is happening to me right now when attempting to download JPEGs generated on the fly by Nintendo, here: https://switch.nintendo.com/year-in-review/

This is with Firefox Preview 3.0.1.

**Comment by matmartin15** [comment] 2020-02-25 13:12
I was trying to export my Spotify playlist to a text (.txt) file using https://www.playlist-converter.net/ on Firefox Preview 3.2.0. (Build #20200123180644).  Firefox Preview was unable to download this file type.

**Comment by jonalmeida** [comment] 2020-03-10 23:16
In my testing so far with all the links above, as @ripdog also mentioned, all these sites generate `blob` URLs and GeckoView explicitly [does not handle non-http or https requests](https://dxr.mozilla.org/mozilla-central/rev/6f21f98dcfcd3420ea528c6ede104fd4d1d36e75/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoWebExecutor.java#127-129) right now.

A-C tracking bug: 
  - https://github.com/mozilla-mobile/android-components/issues/1159

GV tracking bugs: 
  - https://bugzilla.mozilla.org/show_bug.cgi?id=1501735
  - https://bugzilla.mozilla.org/show_bug.cgi?id=1432949

**Comment by andrecc-7** [comment] 2020-03-24 21:54
This bug can also be reproduced in "firefox send" with simple .txt files.

**Comment by cadeyrn** [comment] 2020-03-25 06:47
The Firefox Send issue is #3336.

**Comment by PandoraDay** [comment] 2020-03-31 13:42
> I get this trying to download PDF statements from my bank (tsb.co.uk) :/

Same problem. Although I can navigate through my bank site with Fenix, when I try to download a PDF, it downloads a Null PDF file, which can't be opened with Acrobat Reader nor any other software. The problem does not happen with Chrome or New Microsoft Edge.

Might be compatibility issues?

Nexus 6P with Android 8.1.0 & Firefox Preview 4.1.0

![PDF Null Download](https://user-images.githubusercontent.com/1472746/78032565-d3f39c80-732a-11ea-9bb6-cbbc92c69739.png)

![Corrupt PDF](https://user-images.githubusercontent.com/1472746/78032584-da821400-732a-11ea-86e0-828f1844eb31.png)

**Comment by sylvestre** [comment] 2020-04-06 07:27
@vesta0 FYI, in France, with the lockdown, we need to have a form ( https://media.interieur.gouv.fr/deplacement-covid-19/ ) on our cell. When generating it, it fails with Fenix because of this bug.
Can we reconsider this triage? thanks

**Comment by Dunexus** [comment] 2020-04-06 10:02
> 
> 
> @vesta0 FYI, in France, with the lockdown, we need to have a form ( https://media.interieur.gouv.fr/deplacement-covid-19/ ) on our cell. When generating it, it fails with Fenix because of this bug.
> Can we reconsider this triage? thanks

An issue has even been open about this specific use case : https://github.com/mozilla-mobile/fenix/issues/9735

**Comment by miketaylr** [comment] 2020-04-06 18:46
(We have at least 3 dupes from webcompat.com so far, we'll keep duping them against #9735)

**Comment by jensrutschmann** [comment] 2020-04-24 10:56
I can also reproduce this with the pkpass files you get from DHL when buying a packet stamp.

> Firefox Preview
Nightly 200422 16:13 (Build #21131617)
39.0.20200422145552, 1ee8c073e
GV: 77.0a1-20200422093542
AS: 0.57.0

**Comment by mathieutu** [comment] 2020-04-24 12:45
I encountered the same issue, but with the same file. 
Works well from standard url, but have this message when from blob source.

Maybe the mega and other issues are coming from that?

**Comment by liuche** [comment] 2020-05-06 02:22
Taking a look at the files from [this comment](https://github.com/mozilla-mobile/fenix/issues/2579#issuecomment-535981773), this is definitely the same as the blob filetype problem, so I'm going to dupe.

**Comment by fluffyemily** [comment] 2020-05-12 18:44
The underlying GV issue mentioned here has been resolved.

**Comment by liuche** [comment] 2020-05-14 00:27
Oh, I realize that I duped this to the AC bug - reopening so this can be QA-ed on Fenix.

Please look at the sites listed here and in the AC issue: https://github.com/mozilla-mobile/android-components/issues/1159

**Comment by kglazko** [comment] 2020-05-14 00:48
Thank you, Chenxia! QA, please note there are some known issues that are being discussed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1432949#c14

**Comment by Amejia481** [comment] 2020-05-15 15:07
Now we have support for blob URLs. QA please help us to verify if these websites are working as expected.

**Comment by sflorean** [comment] 2020-05-21 15:25
Verified as fixed on the latest Nightly build 5/21, checked most of the linked closed bugs (where the specific link was still available). 
Devices: Samsung Galaxy Note 10 (Android 10), Motorola Nexus 6 (Android 7.1.1), Huawei MediaPad M2	(Android 5.1.1).

**Comment by liuche** [comment] 2020-05-22 20:53
Estimating the Fenix eng effort partially included in this AC issue https://github.com/mozilla-mobile/android-components/issues/1159

**Closed** 2020-08-12 17:44 UTC
Labels: E5, Feature:Download, P2, S1, eng:qa:verified, 🐞 bug

**Comment by weirdal3333** [comment] 2020-09-14 02:36
This also happens when trying to download a bin file from a ftp server. 
Build# 2015762833
Try downloading either file from this directory: ftp://ftp.dd-wrt.com/betas/2020/09-10-2020-r44340/tplink_archer-c7-v4/

**Comment by kbrosnan** [comment] 2020-09-14 02:52
This issue was about a specific method of providing downloads using the`blob:` protocol and has been resolved. 

If you are seeing download issues please test the [nightly build](https://play.google.com/store/apps/details?id=org.mozilla.fenix) if it is still broken in the nightly build open a new issue.
