### ISSUE TITLE
Missing passwords after update

### ISSUE THREAD

**Issue by Azuus** [mozilla-mobile/fenix#14978] opened 2020-09-11 11:07 UTC
## Steps to reproduce
Hello. After a recent update to your browser, I lost all my saved passwords except for my FireFox account password. How do I recover my passwords? I apologize if you do not understand something because I am Russian and do not know English I use a translator

### Device information

* Android device: ?
* Fenix version: ?

**Comment by kbrosnan** [comment] 2020-09-11 16:39
Did you use Master Password (Primary Password) in the old version of Firefox for Android?

**Comment by Azuus** [comment] 2020-09-12 01:23
> Did you use Master Password (Primary Password) in the old version of Firefox for Android?

Yes

**Comment by Azuus** [comment] 2020-09-13 13:50
> 
> 
> Did you use Master Password (Primary Password) in the old version of Firefox for Android?

???

**Comment by Azuus** [comment] 2020-09-14 01:46
will I get an answer? :(

**Comment by kbrosnan** [comment] 2020-09-14 02:43
There will be a setting to recover the master password data in 81. Duplicate of https://github.com/mozilla-mobile/fenix/issues/13926

**Closed by kbrosnan** 2020-09-14 02:43 UTC
Labels: Feature:Logins, 🐞 bug
