### ISSUE TITLE
[Bug]today nighlty crashing once again 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#14786] opened 2020-09-06 13:21 UTC
unfortunately I don't think the soccorro will be any useful anyway I M posting it.
https://crash-stats.mozilla.org/report/index/cc26bd0d-c5ac-4f09-95b1-33cd90200906#tab-rawdump

**Comment by liuche** [comment] 2020-09-17 00:05
Are there any steps to repro? If there is a particular site that you're encountering this on, that would be helpful too, but you're right, this crash dump is not very useful 😂

**Comment by sflorean** [comment] 2020-11-03 16:08
@ale82to this issue is still reproducible for you? I wasn't able to replicate on latest Nightly.

**Comment by sflorean** [comment] 2021-03-31 14:16
Closing this due to lack of information. Will be re-opened if we can/have steps to reproduce.

**Closed by sflorean** 2021-03-31 14:16 UTC
Labels: 🐞 bug
