### ISSUE TITLE
[Bug] (Custom Tabs, UI) Wrong share button color

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/fenix#4504] opened 2019-08-02 17:40 UTC
## Steps to reproduce
Use Fenix to open link from another application.

![Custom Tabs UI issue](https://i.imgur.com/JsZcfi5.png?1)

### Expected behavior
Share button is white.

### Actual behavior
Share button is black.

### Device information

* Android device: Xiaomi Mi 4X (Android 7.1.2 / MIUI Global 10.3)
* Fenix version: Build #12140611

**Comment by aaudin90** [comment] 2019-08-02 18:57
I can take it

**Comment by aaudin90** [comment] 2019-08-05 18:18
Can not reproduce. Are there any similar errors on another device?

**Comment by ekager** [comment] 2019-08-05 18:28
I believe this is the button that the host application is able to send us the icon and color for. Any fix for this would be in Android Components, we could possibly check the contrast for the color passed to us and adjust the color before adding the icon.

**Comment by NotWoods** [comment] 2019-08-06 03:15
@dector Can you let us know which app you opened the custom tab in? I'll try and investigate further.

**Comment by aaudin90** [comment] 2019-08-06 06:50
Open link from Mail.ru, and i have blue share button on white background. Maybe i have ideas

**Comment by dector** [comment] 2019-08-06 12:30
@NotWoods This issue is 100% reproducible for me on up-to-date Xiaomi 4X device with any link and any app.

**Comment by klint** [comment] 2019-09-26 13:06
Also, the shape of the share button on my Redmi Note 7 is not inline with the rest of the bar (too big and grey color
![image](https://user-images.githubusercontent.com/218971/65690191-cbb26000-e06e-11e9-9761-470abbbdea88.png)

**Comment by vesta0** [comment] 2020-01-06 18:12
The 3rd party app passes on the share button, we will look into how to handle what they pass on better.

**Comment by Baron-Severin** [comment] 2020-01-06 23:40
We're unable to reproduce this on recent builds.  Jumping into the code, it looks like AC has rewritten a substantial chunk of how these buttons are created/sized/laid out.  QA, would you mind verifying that this is now working as intended?

Please note that custom tabs in **_private mode_** have some coloring issues that are being tracked in #7511, but they shouldn't block this bug.

**Comment by AndiAJ** [comment] 2020-01-07 14:33
Hi, **verified as fixed**, on the latest **Nightly Build #20070606 from 01/07** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Custom tabs
![20200107_154516](https://user-images.githubusercontent.com/51314259/71902674-3d6c7080-316b-11ea-8e32-816fc03e730f.gif)

► Private Custom tabs
![20200107_162254](https://user-images.githubusercontent.com/51314259/71902692-42312480-316b-11ea-9819-3bf0f0b832a3.gif)

**Closed by AndiAJ** 2020-01-07 14:33 UTC
Labels: AC-by-Fenix, Feature:CustomTabs, P2, eng:qa:needed, 🐞 bug
