### ISSUE TITLE
[Bug]Wikipedia Top Sites icon is missing for a second on fresh install

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#8718] opened 2020-02-25 10:11 UTC
### Prerequisites
Make sure that you have a fresh install.

## Steps to reproduce
1. Close the onboarding screen;
2. Pay attention to the Top Sites list.

### Expected behavior
There is no glitch or visual defects.

### Actual behavior
The Wikipedia icon is missing for a second.

### Device information

Android device:
- Google Pixel 3 (Android Q);
- Samsung Galaxy S8 (Android 9);
- Nexus 9 (Android 7.1.1).

 Fenix version: Firefox Preview Nightly 2/25 @20560606.

 Notes: This issue is displayed only for the first time after closing the onboarding screen.
![20200225_114639](https://user-images.githubusercontent.com/40264165/75237263-ba10e800-57c7-11ea-9de4-97e3432938f8.gif)

**Comment by mcarare** [comment] 2020-02-25 10:55
@NotWoods Do you think this could be improved with changes to `BrowserIcons` in AC, or should we consider other options (like having a drawable as Top Articles has). TY!

**Comment by NotWoods** [comment] 2020-02-25 16:52
cc @ekager

I think this is due to loading the icon taking a short while, but there might not be a good workaround for fresh installs. Ideally we shouldn't hardcore all the top sites icons.

**Comment by softvision-miralobontiu** [comment] 2020-11-18 15:33
I was not able to reproduce this issue lately.
Closing this issue.

**Closed by softvision-miralobontiu** 2020-11-18 15:33 UTC
Labels: Feature:TopSites, S2, needs:ac, needs:triage, 🐞 bug
