### ISSUE TITLE
[Bug] Tab Close Button too small

### ISSUE THREAD

**Issue by benjaminwolkchen** [mozilla-mobile/fenix#3442] opened 2019-06-13 17:22 UTC
### Why/User Benefit/User Problem
* Easier Workflow.
    1. What/Requirements
Larger Tab Close Buttons
    1. Acceptance Criteria (how do I know when I’m done?)

**Comment by ekager** [comment] 2019-06-13 17:45
Dupe of https://github.com/mozilla-mobile/fenix/issues/610

**Closed** 2020-08-27 00:04 UTC
Labels: feature request 🌟
