### ISSUE TITLE
[Pull To Refresh][Bug] overscroll-behavior: none must disable pull-to-refresh

### ISSUE THREAD

**Issue by mstange** [mozilla-mobile/fenix#16576] opened 2020-11-14 19:45 UTC
## Steps to reproduce

 1. Load [this testcase](https://bugzilla.mozilla.org/attachment.cgi?id=9187859)
 2. Attempt a pull-to-refresh gesture.

### Expected behavior

No pull to refresh should be triggered, because the page is using `overscroll-behavior: none`.

### Actual behavior

Pull to refresh triggers, incorrectly.

### Device information

* Android device: Moto G5
* Fenix version: Nightly 201112

Honoring `overscroll-behavior: none` is a requirement for web compatibility. This property is used, for example, on pages which implement their own built-in pull to refresh gesture handling.

**Comment by Mugurell** [comment] 2020-11-16 21:04
First I thought that GV should just return `HANDLE_CONTENT`.
But it should do this only if the page is scrolled to the top.
Which I think would complicate things..
@hiikezoe @theres-waldo Do you think GV should handle this? That CSS would complicate things even more on Fenix.

**Comment by theres-waldo** [comment] 2020-11-16 23:01
GV has access to information like "are we scrolled to the top", so it could handle this, yes.

I think a good start here would be to:
 1. Agree on a place where the expected behaviour of the flags (i.e., under which circumstances each one is returned) is documented precisely. (At the [declarations in PanZoomController.java](https://searchfox.org/mozilla-central/rev/ff82c973f8ccb0475ec32439e9ec07014b3a681f/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/PanZoomController.java#66) perhaps? Or it could be somewhere else if that's too "internal to GV".)
 2. Propose a patch to the descriptions mentioning `overscroll-behavior`.
 3. We will try to change the GV behaviour to match the new descriptions.

**Comment by Mugurell** [comment] 2020-11-17 14:05
> GV has access to information like "are we scrolled to the top", so it could handle this, yes.
>
> I think a good start here would be to:
> 
>     1. Agree on a place where the expected behaviour of the flags (i.e., under which circumstances each one is returned) is documented precisely. (At the [declarations in PanZoomController.java](https://searchfox.org/mozilla-central/rev/ff82c973f8ccb0475ec32439e9ec07014b3a681f/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/PanZoomController.java#66) perhaps? Or it could be somewhere else if that's too "internal to GV".)
Using PZC as the source of truth for these flags seems good to me.
In [AC we are already mapping](https://github.com/mozilla-mobile/android-components/blob/5a3b15e58d32ff9d5a84551010a0bac9a91748b4/components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt#L150) those flags to [our own](https://github.com/mozilla-mobile/android-components/blob/cd134a34c94a4419167aa55b7c09babc9b6f60d8/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt#L135) which could maybe have better descriptions.
(The mapping is done for ease of use in constructs like `engineView.getInputResult`)

>     2. Propose a patch to the descriptions mentioning `overscroll-behavior`.

I don't see why Fenix / AC would be interested in these kind of properties.
Maybe returning the same "HANDLE_CONTENT" would for these also?

**Comment by hiikezoe** [comment] 2020-11-18 00:23
> > ```
> > 2. Propose a patch to the descriptions mentioning `overscroll-behavior`.
> > ```
> 
> I don't see why Fenix / AC would be interested in these kind of properties.
> Maybe returning the same "HANDLE_CONTENT" would work for these also?

Because even if the root element has `overscroll-behavior:none`, there are cases that Fenix should move the dynamic toolbar in the case, say a content height is over 100vh.

**Comment by hiikezoe** [comment] 2020-11-20 02:13
Filed a GeckoView bug https://bugzilla.mozilla.org/show_bug.cgi?id=1678505

**Comment by sflorean** [comment] 2021-04-13 15:15
I wasn't able to reproduce this issue on latest Nightly build with:
- Samsung Note 10(Android 11)
- Pixel 3 (Android 11).
Closing this as fixed, since the Bugzilla bug is also fixed started with GV 88.

**Closed by sflorean** 2021-04-13 15:15 UTC
Labels: Feature:Gesture, needs:gv, 🐞 bug
