### ISSUE TITLE
PWAs are slow to open

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26270] opened 2022-08-01 14:21 UTC
STRs:
- Access https://daleharvey.github.io/testapp/
- Press `Install` in the 3dot menu
- Open the newly installed PWA from device's homescreen

Expected result
- The PWA is fast to open

Actual result
- The PWA installed from Fenix Release - v105 is visibly slower to open that both the 105 Nightly and latest Chrome

Details
- Tested on a OnePlus 7 running Android 11
- Might be device specific

Video showing the cold start on Fenix Nightly - 105 / Fenix Release 103 / Chrome Release 103:

https://user-images.githubusercontent.com/11428869/182168694-b8c9fd75-b254-4fd0-a7b1-67b728b5282c.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21163)

**Comment by kudlav** [comment] 2022-08-02 12:14
Duplicate of: https://github.com/mozilla-mobile/fenix/issues/22408

**Closed** 2022-08-02 13:26 UTC
Labels: Feature:PWA, needs:triage
