### ISSUE TITLE
Android Status Bar: white text on white background

### ISSUE THREAD

**Issue by MichaelMalott** [mozilla-mobile/fenix#26808] opened 2022-09-04 09:44 UTC
### Steps to reproduce

1. Open any webpage.

### Expected behaviour

Statusbar should have contrasting text color

### Actual behaviour

See screenshots:
![Screenshot_20220904-113903](https://user-images.githubusercontent.com/44677171/188307277-1b4417e3-fabe-49e7-b6b5-ca4325e0c63f.jpg)

Last three updates (or more) from Firefox nightly shown above. Compare to the current version of firefox android below (104.1.0)

![Screenshot_20220904-113958](https://user-images.githubusercontent.com/44677171/188307308-187a7085-241f-429a-bb53-03d09c663248.jpg)
Firefox v104.1.0

Interestingly enough in the Firefox nightly gui on tab selection or menus the statusbar is contrasting, but not always on settings.

![Screenshot_20220904-114251](https://user-images.githubusercontent.com/44677171/188307460-9b892dda-aa91-4964-baa4-61eb25430d0a.jpg)
![Screenshot_20220904-114306](https://user-images.githubusercontent.com/44677171/188307468-4601207b-4b0c-4fdd-9625-cb4055034b08.jpg)

### Device name

OnePlus 8T

### Android version

ANDROID 11 (Oxygen OS)

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1 (Build #2015901675), b43243685+

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21473)

**Comment by kud** [comment] 2022-09-11 14:26
Hey. I've got the same issue. It doesn't happen with the dark theme. Only the light theme.

![Screenshot_20220911-162232](https://user-images.githubusercontent.com/655838/189532826-165217f4-0f06-4cca-bacc-f5a558f9ff65.jpg)

**Comment by Matth7878** [comment] 2022-09-19 04:41
Can confirm using white theme and nightly.
Really annoying 😕

**Comment by kud** [comment] 2022-09-24 22:37
I've temporarily switched to the dark theme.

**Comment by sidvishnoi** [comment] 2022-10-02 08:18
Same as https://github.com/mozilla-mobile/fenix/issues/26674

**Comment by fice-t** [comment] 2022-10-13 04:09
@MichaelMalott This should have been fixed by #25991. Can you reproduce on the latest Nightly?

**Comment by ashjoubert** [comment] 2022-10-20 22:06
This bug has now been published in Firefox stable 106.1.0. Workaround is dark mode. Really annoying.

**Comment by AllesMeins** [comment] 2022-10-23 08:38
I can confirm this issue with the latest Firefox update. Some additional info: for me the problem appears every time I open a new webpage (so on the Firefox start screen the status bar color is still as it should be) but once a pages loads the icons turn white. 
And the problem goes away if I switch tabs even for those pages where the status bar was white before.

**Comment by plwt** [comment] 2022-11-18 22:15
User feedback (multiple users) - https://support.mozilla.org/en-US/questions/1393515

**Comment by ashjoubert** [comment] 2022-11-18 22:52
This issue is fixed for me in Firefox 107.1.0 (stable on Google Play).

**Comment by sidvishnoi** [comment] 2022-11-19 03:45
Can confirm on Beta 107.0b6 too.

**Comment by boek** [comment] 2023-01-30 22:14
Hey @MichaelMalott, going to close this as it was reported as being fixed in 107. Please file a new bug in Bugzilla if you're still able to reproduce.

**Comment by SoftVision-LorandJanos** [comment] 2023-01-31 08:41
I can confirm, I managed to reproduce this issue on 106 and older versions, and verified as fixed on 107.0a1 from 2022-10-13 and newer.
Rechecked on the latest Nightly 111.0a1 (2023-01-31) with the same device and the issue is not reproducible.
Device used: Xiaomi Mi11 Lite (Android 11).
Closing the ticket as verified.

**Closed by SoftVision-LorandJanos** 2023-01-31 08:41 UTC
Labels: 🐞 bug, eng:qa:needed, needs:triage
