### ISSUE TITLE
[Bug] Featured Google images are not correctly opened from "All" section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#17013] opened 2020-12-14 08:24 UTC
## Steps to reproduce
1. Tap on the search bar and search `images`.
2. Open any featured image. 

### Expected behavior
The featured image should be displayed like it's opened from the `Images` section.
### Actual behavior
The image is displayed, but with other elements on the page, instead of showing the full image.
### Device information

* Android device: **Google Pixel 4 XL (11).**
* Fenix version: **Nightly 14/10.**

### Notes
When opening any image from the `Images` section, the correct behavior is displayed.

![20201214-102010](https://user-images.githubusercontent.com/42831109/102057301-67f09000-3df6-11eb-8d4f-ca0fc5c6c107.gif)

**Comment by hakkikaancaliskan** [comment] 2020-12-14 08:49
No problem with google search fixer addon

**Comment by kbrosnan** [comment] 2020-12-14 18:24
Dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=975444#c21

**Closed by kbrosnan** 2020-12-14 18:24 UTC
Labels: S2, b:web-content, b:webcompat, 🐞 bug
