### ISSUE TITLE
[Onboarding] PBM colors need updating

### ISSUE THREAD

**Issue by apbitner** [mozilla-mobile/fenix#8643] opened 2020-02-21 16:42 UTC
PBM onboarding should match the spec found here: https://share.goabstract.com/e818c20f-6e49-4290-b7cd-a2c77adc9585?mode=design&sha=4e5f44342a4bd8185ae5ddeb4f14888784d9193c

Please use the **Inspect** tab in the link above for correct color values.

Changes include:

 - [x] Update search bar color
- [x] Update background gradient of Sign In card
- [x] Update background color of all other cards
- [x] Update color of card icons in the upper-left of most cards
- [ ] For 'Choose your theme' and 'Take a position' cards, update selected and unselected border colors for the radio button illustrations
- [x] Update selected radio button colors
- [x] Update button colors for 'Open settings', 'Read our privacy notice' and 'Start browsing'

Specs
-------
![PBM](https://user-images.githubusercontent.com/22176302/75696132-b1f5f400-5c70-11ea-9969-5c6f88e397ce.png)

**Comment by BranescuMihai** [comment] 2020-03-20 09:39
It seems there is already a task on the toolbar colour (#8491 ), @ValentinTimisica is working on that

**Comment by BranescuMihai** [comment] 2020-03-25 00:02
@apbitner @AmyYLee could you please add the abstracts for dark/light mode for this screen? All colours in our code are connected and I want to check if any of the other two should also be modified.

**Comment by AmyYLee** [comment] 2020-03-25 16:19
> @apbitner @AmyYLee could you please add the abstracts for dark/light mode for this screen? All colours in our code are connected and I want to check if any of the other two should also be modified.

Hi @BranescuMihai 

An issue was filed for Light/Dark themes here https://github.com/mozilla-mobile/fenix/issues/7606
and this is the Abstract file

https://share.goabstract.com/8feabb36-05ef-4ec0-a05a-e56582a05c5f?mode=design&sha=ffec9de54b80fae6a128c4a6663149c2f6f235ca

**Comment by BranescuMihai** [comment] 2020-03-26 22:05
Thanks @AmyYLee ! Here are the screenshots for all 3 versions:
<details>
  <summary>Private Theme Screenshot</summary>
<img src="https://user-images.githubusercontent.com/1709373/77700032-1f6d1a00-6fbc-11ea-9c15-eff351ccb924.jpg" width="200px"/>
</details>
<details>
  <summary>Dark Theme Screenshot</summary>
<img src="https://user-images.githubusercontent.com/1709373/77700044-24ca6480-6fbc-11ea-97d9-2f4cb5778345.jpg" width="200px"/>
</details>
<details>
  <summary>Light Theme Screenshot</summary>
<img src="https://user-images.githubusercontent.com/1709373/77700042-23993780-6fbc-11ea-89c6-8a84b583efa7.jpg" width="200px"/>
</details>

I also added the drop-shadow to the cards, as specified [here](https://user-images.githubusercontent.com/5992746/72190669-28dbe280-33ce-11ea-9d92-521af9501610.png)

@apbitner About the theme/toolbar borders, I noticed you added grey assets for light/dark [here](https://github.com/mozilla-mobile/fenix/issues/7606#issuecomment-600180489). 
We would also need the selected(purple version) for the toolbar illustrations (since for theme we already have them)
Also, is it possible to get the SVG versions instead of the PNGs? It would be easier to add them like that

**Comment by apbitner** [comment] 2020-03-27 17:53
@BranescuMihai Here are the purple, selected states for the Toolbar card for both light and dark. Let me know if you need anything else.

[SVG.zip](https://github.com/mozilla-mobile/fenix/files/4395144/SVG.zip)

**Comment by AmyYLee** [comment] 2020-03-27 21:04
@BranescuMihai Hi, these look great!

As you mentioned above the 2 outstanding things are ensuring that the purple frame matches the radio button colour when it's selected and ensuring it turns grey when in deselected state.

Deselect state should be grey (@apbitner has provided assets)
<img width="408" alt="Screen Shot 2020-03-27 at 16 58 55" src="https://user-images.githubusercontent.com/5992746/77800174-9baf3e00-704c-11ea-950f-a6337fd7534c.png">

Frame should be the same purple as selected radio button (@apbitner has provided assets)
<img width="408" alt="Screen Shot 2020-03-27 at 16 58 55" src="https://user-images.githubusercontent.com/5992746/77800291-d87b3500-704c-11ea-8eb6-8fc50b7383db.png">

Other than that, everything else looks good!

**Comment by BranescuMihai** [comment] 2020-04-01 12:50
@apbitner thanks for the Toolbar assets! I noticed that for the selected state there are 2 shades of purple stroke, so we would need the same from the Theme illustration (in the app we use only one shade). I prefer SVG for these as well

**Comment by apbitner** [comment] 2020-04-01 14:21
Yes, the purple stroke is different for light vs dark/PBM. Here are SVG's for Theme selected states.

[Theme Selected.zip](https://github.com/mozilla-mobile/fenix/files/4415733/Theme.Selected.zip)

**Comment by BranescuMihai** [comment] 2020-04-01 16:33
@apbitner I realised that the size of all these images was around 3mb(and it doubles with rtl), which is way bigger than we should include for such as small usecase. Luckily, I see the diff between light/dark themes is only the border colour, which can be modified in code, thus using only one resource.

Can I get the grey ones again, but in SVG format?
Also, the rtl ones need to be updated to SVG as well to follow this optimisation. Can I get those as well? (both grey and purple - for both toolbar and theme)

Thanks a bunch!

**Comment by apbitner** [comment] 2020-04-02 15:49
I am working with @shorlander to see if we can get SVG versions of these assets, including the logos in SVG format

**Comment by shorlander** [comment] 2020-04-13 17:46
[onboarding-illustrations.zip](https://github.com/mozilla-mobile/fenix/files/4470886/onboarding-illustrations.zip)

@BranescuMihai

**Comment by BranescuMihai** [comment] 2020-04-22 08:10
@shorlander @apbitner thanks! please add also the RTL versions for the toolbar top/bottom, those are the last assets needed

**Comment by ekager** [comment] 2020-04-29 21:59
cc @shorlander @apbitner could we get the remaining svg assets: "RTL versions for the toolbar top/bottom"?

**Comment by sblatz** [comment] 2020-05-07 18:11
@AmyYLee & @apbitner  why does the onboarding "start browsing" button have a different accent color than every other button in the app? Can we please consolidate these colors? 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/81329420-65a1a880-9053-11ea-9b30-e4e4a0eadd9e.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/81329466-76521e80-9053-11ea-84b4-d689b6b27e37.png">

**Comment by AmyYLee** [comment] 2020-05-07 18:25
> @AmyYLee & @apbitner why does the onboarding "start browsing" button have a different accent color than every other button in the app? Can we please consolidate these colors?
> 
> <img alt="image" width="350" src="https://user-images.githubusercontent.com/4400286/81329420-65a1a880-9053-11ea-9b30-e4e4a0eadd9e.png">
> 
> <img alt="image" width="350" src="https://user-images.githubusercontent.com/4400286/81329466-76521e80-9053-11ea-84b4-d689b6b27e37.png">

@sblatz Hi, all the buttons, toggles, switches in dark theme should have the same colour. See below. 

<img width="247" alt="Screen Shot 2020-05-07 at 14 24 13" src="https://user-images.githubusercontent.com/5992746/81330756-8fb49400-906e-11ea-892c-65ce14549bfc.png">

**Comment by sblatz** [comment] 2020-05-07 19:08
@AmyYLee So then you'd expect it to look like this?

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/81334779-6cccb480-905b-11ea-94ea-51af3eb622b4.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/81334802-76eeb300-905b-11ea-9fb4-f80517a7683d.png">

**Comment by AmyYLee** [comment] 2020-05-07 22:02
@sblatz Yes!

**Comment by AmyYLee** [comment] 2020-05-07 22:02
> @AmyYLee So then you'd expect it to look like this?
> 
> <img alt="image" width="350" src="https://user-images.githubusercontent.com/4400286/81334779-6cccb480-905b-11ea-94ea-51af3eb622b4.png">
> 
> <img alt="image" width="350" src="https://user-images.githubusercontent.com/4400286/81334802-76eeb300-905b-11ea-9fb4-f80517a7683d.png">

Yes :-)

**Comment by BranescuMihai** [comment] 2020-05-08 08:20
Thanks for the addition @sblatz ! I was also wondering why the finish button is different

**Comment by Diana-Rus** [comment] 2020-05-13 11:13
Hi, verified the color scheme in Firefox Nightly Preview 200513 (Build #21340609) 5/13 with Google Pixel 3 XL (Android 9) and Samsung Galaxy S9 (Android 8):
**Scenarios PBM- Onboarding:**
1.Verify that the "Sign In" gradient background gradient look as intended - ❓
2.The background color for all of the other cards look as intended - ✔️
3.The color of each of the cards icon look as intended - ✔️
4.Selected 'Choose your theme' and 'Take a position' cards the border color looks as intended - ✔️
5.When unselected 'Choose your theme' and 'Take a position' cards the border color looks as intended✔️
6.The selected radio buttons colors look as intended - ✔️
7.The colors for 'Open settings', 'Read our privacy notice' look as intended - ❓ (as per https://github.com/mozilla-mobile/fenix/issues/8643#issuecomment-625519477 )
8.The color for 'Start browsing' button look as intended (Comment https://github.com/mozilla-mobile/fenix/issues/8643#issuecomment-625519477)- ✔️

**Scenarios Light theme - Onboarding:**
As per: https://github.com/mozilla-mobile/fenix/issues/8643#issuecomment-607279285

9.Selected 'Choose your theme' and 'Take a position' cards the border color looks as intended - ✔️
10.When unselected 'Choose your theme' and 'Take a position' cards the border color looks as intended - ✔️

**Scenarios Dark theme - Onboarding:**
11.Selected 'Choose your theme' and 'Take a position' cards the border color looks as intended - ✔️
12.When unselected 'Choose your theme' and 'Take a position' cards the border color looks as intended - ✔️
13.The color for 'Start browsing' button look as intended same accent (Comment https://github.com/mozilla-mobile/fenix/issues/8643#issuecomment-625519477)- ✔️

<details>
<summary>Google Pixel 3 XL - Android 9 - PBM Screens</summary>
<br>

![Screenshot_20200513-110751](https://user-images.githubusercontent.com/49859863/81796647-671d1600-9516-11ea-8e97-f1fe22bdbe9c.png)

![Screenshot_20200513-110800](https://user-images.githubusercontent.com/49859863/81796661-6c7a6080-9516-11ea-8ace-e7a8d520d317.png)

![Screenshot_20200513-110807](https://user-images.githubusercontent.com/49859863/81796676-71d7ab00-9516-11ea-99a7-ca87f4ade118.png)

</details>

Note:

- @AmyYLee  - For scenario 1 - the gradient is applied differently as from the provided specs the lighter shade is in the opposite corner of the card. In specs the #B733E1 starts from bottom left corner of the card and in app it is in the top right corner. Should it remain the same as in screen for RTl language?
- @AmyYLee - For dark theme, buttons "Open Settings" and "Read our privacy" should they have the same background fill as the "Start browsing" button ?

- The color for "New Tab" button from apps Homescreen is not #9059FF - (comment https://github.com/mozilla-mobile/fenix/issues/8643#issuecomment-625421654) in dark mode

I will remove the qa-needed label until further notice.

**Comment by AmyYLee** [comment] 2020-05-19 21:39
> Hi, verified the color scheme in Firefox Nightly Preview 200513 (Build #21340609) 5/13 with Google Pixel 3 XL (Android 9) and Samsung Galaxy S9 (Android 8):
> **Scenarios PBM- Onboarding:**
> 1.Verify that the "Sign In" gradient background gradient look as intended - ❓
> 2.The background color for all of the other cards look as intended - ✔️
> 3.The color of each of the cards icon look as intended - ✔️
> 4.Selected 'Choose your theme' and 'Take a position' cards the border color looks as intended - ✔️
> 5.When unselected 'Choose your theme' and 'Take a position' cards the border color looks as intended✔️
> 6.The selected radio buttons colors look as intended - ✔️
> 7.The colors for 'Open settings', 'Read our privacy notice' look as intended - ✔️ (as per [#8643 (comment)](https://github.com/mozilla-mobile/fenix/issues/8643#issuecomment-625519477) )
> 8.The color for 'Start browsing' button look as intended (Comment [#8643 (comment)](https://github.com/mozilla-mobile/fenix/issues/8643#issuecomment-625519477) ✔️
> 
> **Scenarios Light theme - Onboarding:**
> As per: [#8643 (comment)](https://github.com/mozilla-mobile/fenix/issues/8643#issuecomment-607279285)
> 
> 9.Selected 'Choose your theme' and 'Take a position' cards the border color looks as intended - ✔️
> 10.When unselected 'Choose your theme' and 'Take a position' cards the border color looks as intended - ✔️
> 
> **Scenarios Dark theme - Onboarding:**
> 11.Selected 'Choose your theme' and 'Take a position' cards the border color looks as intended - ✔️
> 12.When unselected 'Choose your theme' and 'Take a position' cards the border color looks as intended - ✔️
> 13. Dark theme, buttons "Open Settings" and "Read our privacy"have the same background fill as the "Start browsing" button ❓
> 14.The color for 'Start browsing' button look as intended same accent (Comment [#8643 (comment)](https://github.com/mozilla-mobile/fenix/issues/8643#issuecomment-625519477) ✔️
> Google Pixel 3 XL - Android 9 - PBM Screens
> 
> Note:
> 
>     * @AmyYLee  - For scenario 1 - the gradient is applied differently as from the provided specs the lighter shade is in the opposite corner of the card. In specs the #B733E1 starts from bottom left corner of the card and in app it is in the top right corner. Should it remain the same as in screen for RTl language? 

@Diana-Rus  We had issues with having the search bar gradient seamlessly blending with the gradient background of the screen when the search bar is at the top. We decided to keep the gradient unchanged (bottom left corner with #B733E1) for bottom/top search bar location. The search bar background gradient direction should follow the direction as the background gradient for private mode in RTI. 
> 
>     * @AmyYLee - For dark theme, buttons "Open Settings" and "Read our privacy" should they have the same background fill as the "Start browsing" button ? 

@Diana-Rus No, it should follow the spec. 
> 
>     * The color for "New Tab" button from apps Homescreen is not #9059FF - (comment [#8643 (comment)](https://github.com/mozilla-mobile/fenix/issues/8643#issuecomment-625421654)) in dark mode 

@Diana-Rus I'm not sure what you are referencing for "New Tab" button from apps homescreen. Can you share a screenshot?
> 
> 
> I will remove the qa-needed label until further notice.

**Comment by Diana-Rus** [comment] 2020-05-21 15:31
Thank you for your reply , 
- I understand about the toolbar. 
- For the "Sign In" card remain as it is now(see screenshot)?
**Screenshot**
![Screenshot_20200521-172900-edited](https://user-images.githubusercontent.com/49859863/82575415-1e5a0280-9b91-11ea-92e3-f7ecd8dc0a7a.png)

- For the dark theme should we take in consideration this specs -> that all the buttons, toggles, switches in dark theme should have the same colour (#9059FF)

> > @AmyYLee & @apbitner why does the onboarding "start browsing" button have a different accent color than every other button in the app? Can we please consolidate these colors?
> > <img alt="image" width="350" src="https://user-images.githubusercontent.com/4400286/81329420-65a1a880-9053-11ea-9b30-e4e4a0eadd9e.png">
> > <img alt="image" width="350" src="https://user-images.githubusercontent.com/4400286/81329466-76521e80-9053-11ea-84b4-d689b6b27e37.png">
> 
> @sblatz Hi, all the buttons, toggles, switches in dark theme should have the same colour. See below.
> 
> <img alt="Screen Shot 2020-05-07 at 14 24 13" width="247" src="https://user-images.githubusercontent.com/5992746/81330756-8fb49400-906e-11ea-892c-65ce14549bfc.png">

- Or should it match with the specs mentioned in the description from here: #7606 ?

- For "New Tab" it was an observation that it does not matches the color from comment https://github.com/mozilla-mobile/fenix/issues/8643#issuecomment-625421654
**Screenshot**
![Screenshot_20200521-182403-edited](https://user-images.githubusercontent.com/49859863/82575400-19954e80-9b91-11ea-99b3-b32094a26299.png)

**Comment by AmyYLee** [comment] 2020-05-25 16:10
> Thank you for your reply ,
> 
>     * I understand about the toolbar.
> 
>     * For the "Sign In" card remain as it is now(see screenshot)?
>       **Screenshot**
>       ![Screenshot_20200521-172900-edited](https://user-images.githubusercontent.com/49859863/82575415-1e5a0280-9b91-11ea-92e3-f7ecd8dc0a7a.png)
> Keep as is. 

>     * For the dark theme should we take in consideration this specs -> that all the buttons, toggles, switches in dark theme should have the same colour (#9059FF)
> @Diana-Rus Yes - majority of buttons will have this colour. There are a few exceptions for secondary buttons that will be grey (mostly found in settings pages and delete buttons).  
> 
> > > @AmyYLee & @apbitner why does the onboarding "start browsing" button have a different accent color than every other button in the app? Can we please consolidate these colors?
> > > <img alt="image" width="350" src="https://user-images.githubusercontent.com/4400286/81329420-65a1a880-9053-11ea-9b30-e4e4a0eadd9e.png">
> > > <img alt="image" width="350" src="https://user-images.githubusercontent.com/4400286/81329466-76521e80-9053-11ea-84b4-d689b6b27e37.png">
> > 
> > 
> > @sblatz Hi, all the buttons, toggles, switches in dark theme should have the same colour. See below.
> > <img alt="Screen Shot 2020-05-07 at 14 24 13" width="247" src="https://user-images.githubusercontent.com/5992746/81330756-8fb49400-906e-11ea-892c-65ce14549bfc.png">
> 
>     * Or should it match with the specs mentioned in the description from here: #7606 ?
> 
>     * For "New Tab" it was an observation that it does not matches the color from comment [#8643 (comment)](https://github.com/mozilla-mobile/fenix/issues/8643#issuecomment-625421654)
>       **Screenshot**
>       ![Screenshot_20200521-182403-edited](https://user-images.githubusercontent.com/49859863/82575400-19954e80-9b91-11ea-99b3-b32094a26299.png)

@Diana-Rus New tab button should be #9059FF

**Comment by BranescuMihai** [comment] 2020-06-11 14:41
Since the last bug on this is no longer relevant, I'll close this

**Closed by BranescuMihai** 2020-06-11 14:41 UTC
Labels: Feature:Onboarding, P2, implementation review, needs:triage
