### ISSUE TITLE
[Bug] Issues with set toolbar on top

### ISSUE THREAD

**Issue by scyim** [mozilla-mobile/fenix#15288] opened 2020-09-22 00:15 UTC
## Steps to reproduce
 
Set Tool bar on top
 
### Expected behavior

1. no white margin

2. Bottom lazy to hide or follow tool bar without gap.

### Actual behavior

1. May websites show white space margin which should place the bottom
e.g. bing.com (mobile version).

may duplicated with #14907

![Screenshot_20200922-075912__01.jpg](https://user-images.githubusercontent.com/13778752/93833426-2646c200-fcab-11ea-9cff-13f0de96230e.jpg)

2. When scoll up a gap appears between YouTube navigate bar(bottom menu) with Tool bar (or screen border when tool bar on top) 

![Screenshot_20200922-074238__01.jpg](https://user-images.githubusercontent.com/13778752/93833445-3363b100-fcab-11ea-980d-7ad871e20860.jpg)

### Device information

* Android device: ?
* Fenix version: Nightly0921 & release version

**Comment by s-ankur** [comment] 2020-10-21 15:02
Duplicate of https://github.com/mozilla-mobile/fenix/issues/14821

**Closed** 2020-10-22 00:47 UTC
Labels: Feature:Toolbar, 🐞 bug
