### ISSUE TITLE
[Bug] Download percentage progress is not displayed in portrait mode for files with long name

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11103] opened 2020-05-31 16:26 UTC
## Steps to reproduce
Download any file with long name it nevers shows the percentage

### Expected behavior
It should show the percentage

### Actual behavior
Progress percentage not showing 

### Device information
* Android device: ? A10
* Fenix version: ?Latest nightly build

Attaching reference screenshot from chrome download panel where it shows MB download/total size.

![Screenshot](https://user-images.githubusercontent.com/58127841/83357359-69c39c00-a35b-11ea-9f85-c099070a73af.jpg)UNITO-UNDERSCORE!20200531-214639!

![Screenshot](https://user-images.githubusercontent.com/58127841/83357339-51ec1800-a35b-11ea-8f53-dfb7217f27db.jpg)UNITO-UNDERSCORE!20200531-214827!

**Comment by sheikh-azharuddin** [comment] 2020-05-31 16:27
Also if you see download speed is slow in firefox as compared to chrome...it failed twice too.
Not sure..my net speed is really good..you can check the speed while downloading in chrome

**Comment by cadeyrn** [comment] 2020-05-31 16:45
Duplicate of #10703.

**Comment by sheikh-azharuddin** [comment] 2020-06-01 04:57
> Duplicate of #10703.

10703 is a feature request which again points to another old ticket raised last year...here my case is a bug...the percentage is not showing for files with large name...maybe you can reduce the name like chrome and show the percentage to fix the bug as of now.... MB download/total size can be regarded as a feature request

**Comment by victor-bayas** [comment] 2020-06-05 01:14
The progress bar is not filling accordingly to the download percent, to reproduce just download a Win10 ISO from https://tb.rg-adguard.net/public.php

![Screenshot_20200604-201205_Firefox Nightly](https://user-images.githubusercontent.com/49411169/83825732-d1e9e900-a69f-11ea-9976-58e559f191c1.jpg)

**Comment by Amejia481** [comment] 2021-02-01 20:50
QA team could you please help us to verify is this is still an issue? Thanks in advance.

**Comment by ebalazs-sv** [comment] 2021-02-03 10:13
@Amejia481 This issue is reproducible on the latest Nightly 2/3, Beta 86.0.0-beta.2 and Release 85.1.1 with Motorola Moto G6 (Android 8), downloading the file from:
https://m.apkshub.com/down/com.microsoft.emmx_42.0.4.3892_free 
with the file name
com.microsoft.emmx_42.0.4.3892_free-www.apkshub.com.apk

- Not reproducible in landscape mode.
- Not reproducible on tablet: Samsung Galaxy Tab S3 (Android 8).

I will remove the qa:needed label for now.

**Comment by Amejia481** [comment] 2021-02-03 14:56
Thanks @ ebalazs-sv :)

**Closed** 2021-08-09 16:46 UTC
Labels: 🐞 bug, Feature:Download, S3, wontfix
