### ISSUE TITLE
[Bug] Address bar completion is stuck after pressing enter

### ISSUE THREAD

**Issue by w3Abhishek** [mozilla-mobile/fenix#15464] opened 2020-09-26 21:01 UTC
## Steps to reproduce

* Enter URL or search term in the address bar
* Tap Enter in on-screen keyboard

### Expected behavior

Completion section should disappear after clicking enter

### Actual behavior

Sometimes closes and sometimes sticks
Ref: https://youtu.be/OR7516clqj4

### Device information

* Android device: Realme 5
* Fenix version: Nightly 200926 06:03

**Comment by Shamp0o** [comment] 2020-10-12 11:04
Same behavior here on Xiaomi Redmi Note 5 running LineageOS 17.1. Fenix version: 82.0.0-beta.4

**Comment by eliserichards** [comment] 2020-10-27 18:05
Same behavior reported here with some additional details: https://www.reddit.com/r/firefox/comments/jiwqal/this_panel_doesnt_go_away_whenever_i_search_by/

**Comment by giwrgosmant** [comment] 2021-01-04 17:42
Same behavior on POCO F1 running Pixel Experience Plus Android 10. Firefox Stable Version: 84.1.2 (Build #2015783137)
Really annoying, I had to go back on Chromium base browser because of this.😕 I hope for a fix soon 🤞

**Comment by SPLESHER1** [comment] 2021-01-04 18:13
Same behavior on POCO F1. Firefox Stable Version: 84.1.2 (Build #2015783137)

**Comment by w3Abhishek** [comment] 2021-01-07 07:32
I hope this solves the issue.

**Comment by sflorean** [comment] 2021-01-08 16:29
I wasn't able to reproduce the issue on latest Nightly build with Pixel 3 (Android 11). @giwrgosmant @SPLESHER1 could you check this on Nightly? on stable version will still be reproducible until the bug is landed on release.

**Comment by giwrgosmant** [comment] 2021-01-08 16:48
> 
> 
> I wasn't able to reproduce the issue on latest Nightly build with Pixel 3 (Android 11). @giwrgosmant @SPLESHER1 could you check this on Nightly? on stable version will still be reproducible until the bug is landed on release.

Hello,

I've just tested it and it persists. Tested with Nightly from Play Store and Firefox Beta 85.0.0-beta.6 from Github.
POCO F1 running Android 10 Pixel Experience Plus.

**Comment by mcarare** [comment] 2021-01-08 17:25
> 
> Hello,
> 
> I've just tested it and it persists. Tested with Nightly from Play Store and Firefox Beta 85.0.0-beta.6 from Github.
> POCO F1 running Android 10 Pixel Experience Plus.

Nightly 210107?

**Comment by giwrgosmant** [comment] 2021-01-08 17:43
> 
> 
> > Hello,
> > I've just tested it and it persists. Tested with Nightly from Play Store and Firefox Beta 85.0.0-beta.6 from Github.
> > POCO F1 running Android 10 Pixel Experience Plus.
> 
> @giwrgosmant Nightly 210107?

Seems the nightly version wasn't 210107 at time I tried it. Now I've tried with 210107, all seems fine atm 👍 
I will let you know if I encounter the issue again. Thanks!

**Comment by mcarare** [comment] 2021-01-08 18:23
I cannot reproduce this (even before the fix) on Nightly or Beta. Also used a  Xiaomi Redmi Note 8 Pro, the nearest I have to the reported devices( I do not have a custom OS tough).

**Comment by giwrgosmant** [comment] 2021-01-08 20:00
> 
> 
> I cannot reproduce this (even before the fix) on Nightly or Beta. Also used a Xiaomi Redmi Note 8 Pro, the nearest I have to the reported devices( I do not have a custom OS tough).

I've recorded a video reproducing that on 210107 Nightly. Check [here](https://mega.nz/file/T9sTEQhQ#RIq2yETZCpEmzGnvt4CKrxKlfJjnPAsRDxZXaA2Y5Rs)

**Comment by mcarare** [comment] 2021-01-18 14:19
@giwrgosmant Do you have gesture navigation enabled and/or customized on your device? Does the issue still occurs when you switch back to 3-button or 2-button navigation?

**Comment by giwrgosmant** [comment] 2021-01-18 15:41
> @giwrgosmant Do you have gesture navigation enabled and/or customized on your device? Does the issue still occurs when you switch back to 3-button or 2-button navigation? 

Yeah I have gesture navigation enabled.
I tried with 3-button and 2-button navigation and the problem seems solved, I switched back to gesture navigation and issue came back. So the problem is with gesture navigation 🤔

**Comment by mcarare** [comment] 2021-01-18 15:44
@giwrgosmant Yes, but I think the problem occurs only with a custom OS that implements its own gesture navigation or when using a custom launcher (with a custom gesture navigation as well).
On standard gesture navigation, I am unable to reproduce this.

**Comment by giwrgosmant** [comment] 2021-01-19 04:22
> @giwrgosmant Yes, but I think the problem occurs only with a custom OS that implements its own gesture navigation or when using a custom launcher (with a custom gesture navigation as well).
> On standard gesture navigation, I am unable to reproduce this. 

They use the standard Android 10 navigation, I don't think they modified anything regarding this. 🤔

**Comment by giwrgosmant** [comment] 2021-02-09 10:22
@mcarare I am on Android 11 Pixel Experience now with Navigation bar pill always on and I don't face this issue anymore.
It seems to be related with navigation bar pill which I hide in options back in Android 10 version, but I still don't understand why this affect Firefox at all.

**Comment by mcarare** [comment] 2021-02-09 11:14
@giwrgosmant I have tested this in standard Android 10 with different devices and using gesture navigation does not break this feature in Fenix, so I am unable to see what custom OS's change in gestures that interferes with dismissing the dialog fragment.

**Comment by mcarare** [comment] 2021-02-24 13:34
Another report, with 
> My phone is Sony Xperia H3123 running Lineage OS 17.1 (Android 10)

**Comment by GottfriedCP** [comment] 2021-02-24 13:49
> 
> 
> Another report, with
> 
> > My phone is Sony Xperia H3123 running Lineage OS 17.1 (Android 10)

@giwrgosmant your suggestion seems to solve my problem

**Comment by giwrgosmant** [comment] 2021-02-24 16:23
> 
> 
> > Another report, with
> > > My phone is Sony Xperia H3123 running Lineage OS 17.1 (Android 10)
> 
> @giwrgosmant your suggestion seems to solve my problem

You mean the navigation pill always on?

**Comment by mariansima** [comment] 2021-08-30 08:02
Could not reproduce this issue on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29

**Closed** 2021-09-06 11:15 UTC
Labels: 🐞 bug, needs:investigation, Feature:Search, Feature:Toolbar, wontfix
