### ISSUE TITLE
FNX3-16316 ⁃ Support Add-ons

### ISSUE THREAD

**Issue by maverick74** [mozilla-mobile/fenix#2428] opened 2019-05-10 22:44 UTC
### Why/User Benefit/User Problem
Add-ons allow users to customize the browser with extra features

### Acceptance Criteria (how do I know when I’m done?)
When one goes to AMO and is able to install add-ons

I think this is probably already planned (i can't even imagine Firefox without it), but the intention is to have a bug report where one can follow the implementation progress of this feature.

**Comment by yoasif** [comment] 2019-05-10 22:46
Dupe of #574

**Comment by kbrosnan** [comment] 2019-05-10 22:47
Closing dupe

**Comment by maverick74** [comment] 2019-05-10 22:54
Ups. 

Didn't search for "Web extensions"!

Sorry about that, guys. My fault.

**Comment by NatoBoram** [comment] 2020-06-22 19:07
#574 got closed in favour of #5315, which got its scope arbitrarily changed then closed by @vesta0. This is no longer a duplicate.

**Comment by maverick74** [comment] 2020-08-12 02:02
@data-sync-user Why is this reopened? It was a dupe!

**Comment by Dunexus** [comment] 2020-08-12 07:32
@maverick74 data-sync-user is a bot and it didn't behave as expected. It re-opened some issues by mistake.

**Closed** 2020-08-12 15:55 UTC
Labels: feature request 🌟

**Comment by NatoBoram** [comment] 2020-08-25 19:33
Still not a dupe, but the closest I found was https://github.com/mozilla-mobile/fenix/issues/14034.
