### ISSUE TITLE
[Bug] Fenix doesn't trigger the installation of download apks

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#5692] opened 2019-10-01 03:02 UTC
### Steps to reproduce
Go to apkmirror.com
Download any apk
Touch the "download completed" notification

###Expected behavior
The installation process of the apk is started

### Actual behavior
Fenix asks what the user wants to do with the file and gives no option to install. Also, the notification sound every time a download is completed is pretty annoying.

### Device information

* Android device: Galaxy A5 2017 Android 8.0
* Fenix version: 190930

**Comment by ekager** [comment] 2019-10-02 03:12
Have you given Fenix the system permission to "install unknown apps"? 
For me it's Settings -> Apps -> Firefox Preview -> Advanced -> Install Unknown Apps

**Comment by Lululalu** [comment] 2019-10-02 04:20
@ekager I actually didn't, but Fenix never asked me to grant this permission.

**Comment by ekager** [comment] 2019-10-05 17:57
Let's get this tested and see if all .apk downloads -> installations fail in Fenix currently (with Install Unknown Apps permission granted)

**Comment by sv-ohorvath** [comment] 2019-10-15 08:29
I can download and install apks from apkmirror without issues on 3 different devices: Pixel (Android 9), Galaxy S8 (Android 9), P9 Lite (Android 7.0) with Fenix Nightly 10/15:
![20191015_112752](https://user-images.githubusercontent.com/4037709/66814281-035e4a80-ef3f-11e9-993d-34198582e4b7.gif)

**Comment by kbrosnan** [comment] 2019-10-15 19:04
Closing as cannot reproduce.

**Closed by kbrosnan** 2019-10-15 19:04 UTC
Labels: Feature:Download, 🐞 bug
