### ISSUE TITLE
Need more intuitive page updating

### ISSUE THREAD

**Issue by GunterSR** [mozilla-mobile/fenix#8045] opened 2020-02-03 11:32 UTC
### Why/User Benefit/User Problem
It saves more time then finding update button in the menu.
### What/Requirements
On Chromium browsers you can pull down the page at the top and page will be updated easily.

**Comment by cadeyrn** [comment] 2020-02-03 11:55
Duplicate of #3262.

**Closed** 2020-02-04 00:05 UTC
Labels: needs:triage, 🌟 feature request
