### ISSUE TITLE
FNX-3333 ⁃ [webcontent] page shift up and down on one side

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10174] opened 2020-04-24 02:01 UTC
## Site with issue and any steps to reproduce
reddit.com desktop mode

### Expected behavior
the page should not flash/shift up and down on one side

### Actual behavior
it is flashing/shifting up and down on one side very fast and hurt my eye

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
I have this off should I turn this on?

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
no

### Can you reproduce in Chrome (or other non-Mozilla browser)?

no

### Device information
* Android device: N960F android 10 april patch
* Fenix version: Nightly 200422 16:13

I have to take multiple screenshot to see it, so I am sorry for the screenshot bar.

![Screenshot](https://user-images.githubusercontent.com/63433757/80167188-f024e980-8609-11ea-9ff1-c9074896c323.jpg)UNITO-UNDERSCORE!20200411-052741!UNITO-UNDERSCORE!Firefox Nightly!

**Comment by eliserichards** [comment] 2020-05-05 19:13
Closing as dupe of #10160

**Closed** 2020-08-10 19:26 UTC
Labels: Feature:Toolbar, b:web-content, 🐞 bug
