### ISSUE TITLE
[Bug] Custom protocol handling results in error page

### ISSUE THREAD

**Issue by andreasbovens** [mozilla-mobile/fenix#7731] opened 2020-01-15 16:38 UTC
## Steps to reproduce

1. Go to https://europa.eu/european-union/contact/call-us_en
2. Tap on the phone number link.

### Expected behavior

The dial app is opened straight away, with the phone number pre-filled.

### Actual behavior

An "Unknown Protocol" error page is shown and a "tel:" protocol link is shown in the address bar. The three-dot menu however has a blue indicator dot, which highlights "Open in App". When tapping the "Open in App" menu option, the number is passed on correctly to the dial app. 

Similar behavior can be seen with other apps that rely on custom protocols. E.g. Zoom, which uses zoomus:// links.

Note: this doesn't happen when "Open links in apps" is checked, but afaiu, that does more than just protocol handling. Should this toggle be on by default perhaps?

### Device information

* Android device: OnePlus 5
* Fenix version: Latest Nightly 200114 18:01

**Comment by freaktechnik** [comment] 2020-01-15 21:40
Even worse for some redirects you can't even do the open with app workaround. For example when trying to authorize slack, you're just stranded on the last page of the auth flow. Same applies to oauth flows of other apps that happen in a custom tab (slack opens in browser).

**Comment by childnode** [comment] 2020-01-21 06:32
dup #7691

**Comment by kbrosnan** [comment] 2020-02-07 03:05
Actually a dupe of #6231

**Closed by kbrosnan** 2020-02-07 03:05 UTC
Labels: needs:triage, 🐞 bug
