### ISSUE TITLE
New tab button moved and not customisable

### ISSUE THREAD

**Issue by AndyP2002** [mozilla-mobile/fenix#14467] opened 2020-08-29 22:10 UTC
With the inexplicable rush to move everything to the bottom of the screen, at least you gave us the option to move the search and URL bar back to the top. No such choice with the new tab "+" button. Please give us the option to put it back at the top. I don't like the whole layout of the tabs screen tbh - would much prefer a horizontal list (as that is how tabs have always been displayed on desktop etc!

**Comment by hwinnemoe** [comment] 2020-09-04 11:48
Duplicate of/Related to #14403

**Comment by ekager** [comment] 2020-12-18 05:30
Closing for #14403

**Closed by ekager** 2020-12-18 05:30 UTC
Labels: needs:triage
