### ISSUE TITLE
[Bug] Tab bar and tab icon are unresponsive in Nightly with WebRender enabled

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#5960] opened 2019-10-11 17:16 UTC
## Steps to reproduce
-Open a tab in Nightly
-Tap on the nav bar or the tab icon

### Expected behavior
-when tapping on nav bar, keyboard should open
-when tapping on tab icon, homepage should open

### Actual behavior
-nothing happens but back button takes user back to the homepage

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 191011

**Comment by hakkikaancaliskan** [comment] 2019-10-11 17:28
Duplicate of #5951 ?

**Comment by jamienicol** [comment] 2019-10-14 13:01
I bisected Fenix and found that f9afd97a687a501553bcc91c78d7c945f8678f7a is the regressing commit.

It seems like we now wait until `engineView.captureThumbnail()` completes before opening the tab drawer or settings page etc? However, if you dig in to the gecko code, you can see that [`RecvRequestScreenPixels()`](https://searchfox.org/mozilla-central/source/gfx/layers/ipc/UiCompositorControllerParent.cpp#174) is only implemented for the layers gfx backend, not webrender. The graphics code will never send a `SendScreenPixels()` back, so the callback will never be invoked. Hence nothing happens.

[Bug 1547737](https://bugzilla.mozilla.org/show_bug.cgi?id=1547737) is tracking implementing this function for webrender. Hopefully that should land in the next week or two, but in the meantime I will see if we can simply return null (rather than not return at all) whilst webrender is enabled.

**Comment by jamienicol** [comment] 2019-10-14 13:04
Alternatively, and I don't know whether this is possible, but in Fenix maybe it would make sense to add a timeout waiting for `captureThumbnail()`. And then proceed to show the tab switcher / settings menu / whatever if the thumbnail hasn't arrived within that time?

**Comment by jamienicol** [comment] 2019-10-14 13:17
Ugh, I meant to leave these comments in #5951. Sorry for the noise.

**Comment by ekager** [comment] 2019-10-14 18:59
Closing for #5951

**Closed by ekager** 2019-10-14 18:59 UTC
Labels: 🐞 bug
