### ISSUE TITLE
[Bug] Close Reading Mode button disappears upon scrolling

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#3885] opened 2019-07-03 22:21 UTC
## Steps to reproduce
Open a news article in Reader Mode. Reproduced successfully on Bloomberg. https://www.bloomberg.com/opinion/articles/2019-07-02/trump-s-tariff-barrage-on-airbus-boeing-forces-eu-into-a-corner
Scroll the page with the Quick Action Bar open.

### Expected behavior
The Close button remains and works.

### Actual behavior
The Close button disappears and gets replaced by the Quick Action Bar options before Reader Mode was selected. It seems that the page refreshes the Quick Action Bar state several times while scrolling.

### Device information

* Android device: Pixel 3 XL
* Fenix version: Nightly July 2nd

**Comment by csadilek** [comment] 2019-07-03 22:35
Yes, this can happen on some sites until https://github.com/mozilla-mobile/android-components/issues/2985 can land (currently blocked on GV fixes and enhancements).

**Comment by sblatz** [comment] 2019-11-12 20:36
Does this still happen now that the quick action bar is gone?

**Comment by csadilek** [comment] 2019-11-13 14:50
@sblatz Yes, this would still be happening, as the problem is unrelated to the QAB. The linked issue in A-C is blocked on better extension page support in GV.

**Comment by csadilek** [comment] 2020-05-06 13:46
This is fixed now as of Nightly 200506 06:01.

**Comment by csadilek** [comment] 2020-05-06 15:06
@AndiAJ Maybe you can verify this one too :). Thanks!

**Comment by AndiAJ** [comment] 2020-05-06 15:38
Sure @csadilek . ☺️ 
**Verified as fixed** on **`Nightly Build 200506 from 5/6`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200506-183417](https://user-images.githubusercontent.com/51314259/81197215-b1f3d680-8fc8-11ea-8b0f-4ca33a8ba1d0.gif)

**Closed by AndiAJ** 2020-05-06 15:38 UTC
Labels: Feature:ReaderMode, P3, eng:qa:needed, 🐞 bug
