### ISSUE TITLE
[Bug] devices to sync are gone

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#11577] opened 2020-06-14 23:36 UTC
Several days ago all worked fine. Moreover, sync account is connected right now, but it shows no devices:

![image](https://user-images.githubusercontent.com/14617699/84606660-91b11480-aeb0-11ea-8e0e-e364508d7504.png)
![image](https://user-images.githubusercontent.com/14617699/84606662-95449b80-aeb0-11ea-9fae-a8251e1d527a.png)

**Comment by SS1113** [comment] 2020-06-15 01:15
Same is the case on my device as well on the `Nightly 200614 06:01`.

Device: Motorola One Power, Android 10.

**Comment by 532910** [comment] 2020-06-15 02:12
5.1.1 (#21571852), LineageOS 16 on Android 9,
so it looks like a mozilla's sync-serever side issue.

**Comment by 532910** [comment] 2020-06-24 20:13
I've re added fenix device, but nothing has changed.

**Comment by SS1113** [comment] 2020-06-25 01:34
@532910 this seems to have been fixed in the latest `Nightly 200624 06:01` and `Firefox Preview 5.2` I can see my all my added devices. Please update you Firefox version and check again!

**Comment by 532910** [comment] 2020-06-25 01:46
it updates automatically and is 5.2.0, and I re-logged in on updated fenix

**Comment by SS1113** [comment] 2020-06-25 01:53
Are you willing to try re-installing Firefox? Make sure you backup your data first!

**Comment by 532910** [comment] 2020-06-25 05:10
Nope, I'm not willing. But I logged in with nightly and both fenixes show each other, and both don't show PC. PC shows all devices. I can send tabs from PC to both fenixes but not vice versa.

**Comment by SS1113** [comment] 2020-06-25 05:21
Okay, in that case we need someone from the development team to know what's going on. I don't know why this is happening.

**Comment by SS1113** [comment] 2020-06-26 02:06
@532910 I was finally able to find an issue #11950 that was looking similar to this to me, and posted this issue on it. Seems like the developers took notice and they're investigating this now.

So you can be sure that this will be resolved.

**Comment by dkbg** [comment] 2020-10-08 04:59
My experience with the old Firefox (Fennec) and its custom share menu is that I'd be able to send a tab to another device from my phone even if that device is currently offline/not currently signed into Firefox Sync but has been in the past (i.e. it's been registered at some point as an active device and is listed on accounts.firefox.com under "Devices & apps"). Now with Fenix and the native Android share menu, other devices are only listed if they're currently signed in and there's been a sync on both my phone and the other device to ensure the other device can be seen by my phone in the Firefox Sync infrastructure.

This surely can't be expected behaviour and this must be a regression, since it largely defeats the purpose of the feature if you can't send a tab to an offline device to be held in a queue. Otherwise, the way it seems to work now, you have to be in the same location as the other device or it has to always be online.

**Comment by sflorean** [comment] 2021-03-31 15:28
Issue #11950 is fixed and verified, please check the following discussions there if it is the case. Closing this as verified, as well.

**Closed by sflorean** 2021-03-31 15:28 UTC
Labels: Feature:Sync, 🐞 bug
