### ISSUE TITLE
[Bug] Firefox Nightly Add-on Collection stops updating

### ISSUE THREAD

**Issue by eberhardweber** [mozilla-mobile/fenix#16885] opened 2020-12-06 19:38 UTC
## Steps to reproduce

After five or so changes and refreshes to my Firefox Nightly add-on collection, manually refreshing the list via the Debug Menu element "Custom Add-on collection" stopped updating the add-on list completely. 

The list that is loaded to my Nightly browser is two or three updates behind the one I have made at addons.mozilla.org, and none of the changes are being applied to the browser.

### Expected behavior

The add-on list should be able to be refreshed as many times and as often as the user wants.

### Actual behavior

The collection stops being refreshed. 

The only way I was able to update my add-on collection was making a completely new list with a new ID.

### Device information

Android device: Xiaomi Mi A1
Fenix version: Nightly (201205 17:02)

**Comment by eberhardweber** [comment] 2020-12-06 21:07
To update on this bug, my second collection has stopped refreshing just after one update.

**Comment by kbrosnan** [comment] 2020-12-07 18:59
I recall that the data is cached and will only update around once a day. @csadilek this is expected behavior?

**Comment by csadilek** [comment] 2020-12-07 22:49
@kbrosnan We deactivate the client-side cache in Fenix for users with custom add-on collections to prevent this, but AMO recently started caching on the server-side, which is likely the cause of this. We're discussing next steps later this week, but in the meantime the workaround above is the only option if newly added add-ons need to be available right away.

**Comment by diox** [comment] 2020-12-10 18:40
Yes, AMO now has a one hour caching on the collection endpoint Fenix is using. We intend to tweak that cache, possibly drop it entirely for non-mozilla collections to fix this issue. This is tracked in https://github.com/mozilla/addons-server/issues/16151

**Comment by pcgeek86** [comment] 2020-12-15 16:55
I can confirm that in Firefox Nightly, collections do not get updated. Please consider adding a mechanism to forcibly refresh the custom add-ons collection in Fenix.

If I add a new extension to a collection on AMO, using the desktop browser, I would like it to appear in Fenix right away, so that I can install it.

**Comment by csadilek** [comment] 2021-01-08 21:52
Thanks for filing. Fix https://github.com/mozilla/addons-server/issues/16151 landed. Closing.

**Closed by csadilek** 2021-01-08 21:52 UTC
Labels: Feature:WebExtensions, S4, 🐞 bug

**Comment by diox** [comment] 2021-01-08 22:48
Note: there will still be a 3 minutes cache on the endpoint even for non-mozilla collections. It isn't set by our app but sits at a higher level in the stack, and we'd like to keep it.
