### ISSUE TITLE
[Bug] select HTML tag keep showing up if dismissed without an option chosen

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#13196] opened 2020-08-01 13:10 UTC
## Steps to reproduce
1. Find a `<select>` HTML tag, e.g. [
`<select>` on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select)
2. Dismiss the dialog **without choosing an option**
3. Change tab -> action A
3 bis. Go to the url bar and type anything -> action B

(As they are extremely similar I report them with the same issue)
### Expected behavior
Action A -> nothing happens, you just browse the other tab

Action B -> you get the results for what you typed
### Actual behavior
Action A & B-> the `<select>` dialog with its options shows up.
### Device information

* Android device: Pocophone F1, /e/ OS 0.9 (based on LineageOS 16, Android 9)
* Fenix version: Nightly 200801 06:06 (Build #22140616)

Record of the bug:
![fenix_select_bug](https://user-images.githubusercontent.com/58657617/89102393-057b9200-d409-11ea-9a3d-25b3afd64b6d.gif)

**Comment by s-ankur** [comment] 2020-08-01 14:16
Duplicate of #12943

**Comment by s-ankur** [comment] 2020-08-01 14:17
@B0pol it does not matter if you select an option or not. Only matters of it was last in focus

**Comment by ekager** [comment] 2020-08-01 16:21
Closing for #12943

**Closed by ekager** 2020-08-01 16:21 UTC
Labels: needs:triage, 🐞 bug
