### ISSUE TITLE
[Bug] The Spotify app is always opened when accessing any playlist from Fenix

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#4405] opened 2019-07-31 09:31 UTC
## Steps to reproduce
1. Launch Fenix.
2. Access www.spotify.com.
3. Login with valid credentials.
4. Access any playlist from spotify.
### Expected behavior
The playlist is correctly opened in fenix browser.
### Actual behavior
Spotify app is opened every time when accessing a playlist on Fenix.
### Device information

* Android device: **`Samsung Galaxy s10+(Android 9).`**
* Fenix version: **`Latest Nightly build 7/31.`**
[Video](https://drive.google.com/file/d/1lkKsjJduSgmSOcMhoRi5TkpWyYLc17ZV/view?usp=sharing)

**Comment by mcarare** [comment] 2019-08-01 15:25
@abodea IMO this is not a bug. This is a feature introduced in Android 6 which lets app open specific URLs without the open dialog. Spotify is default handler of links in spotify.com, open.spotify.com, accounts.spotify.com. Chrome and any other browser will have the same behaviour. This can be disabled only in device's system settings (see App Links).
I think this issue can be closed.

**Comment by abodea** [comment] 2019-08-01 15:32
Hi @mcarare I added this bug based on this issue https://github.com/mozilla-mobile/android-components/issues/3695.
It will be a feature for many websites that can be opened in external apps using the button from QAB.

**Comment by mcarare** [comment] 2019-08-01 16:22
IMO These are different issues and use cases. The feature you referenced is about opening a page in an app, via QAB, not handling a web link click, like in the issue you described here.

**Comment by Mugurell** [comment] 2019-08-05 15:18
Clicking on a Spotify playlist, let's say
https://open.spotify.com/playlist/37i9dQZF1DXdPIbPNr916x
will result in a few redirects
- https://open.spotify.com/user/spotify/playlist/37i9dQZF1DX3PFzdbtx1Us?
- https://app.adjust.com/6ypk9q?deep_link=spotify%3A%2F%2Fuser%2Fspotify%2Fplaylist%2F37i9dQZF1DX3PFzdbtx1Us&campaign=&adgroup=&creative=&label=sp_cid%3A3146ed6da541dd097435e9c97b2598d7&tracker_limit=200000&redirect=http%3A%2F%2Fopen.spotify.com%2Fuser%2Fspotify%2Fplaylist%2F37i9dQZF1DX3PFzdbtx1Us%3F%3Fnd%3D1
- intent://user/spotify/playlist/37i9dQZF1DX3PFzdbtx1Us?adjust_reftag=cQ5knjdWD5m0V#Intent;scheme=spotify;package=com.spotify.music;S.market_referrer=adjust_reftag%3DcQ5knjdWD5m0V;S.browser_fallback_url=http%3A%2F%2Fopen.spotify.com%2Fuser%2Fspotify%2Fplaylist%2F37i9dQZF1DX3PFzdbtx1Us%3Fnd%3D1;end

the latter for which [we would get an `AppLinkRedirect`](https://github.com/mozilla-mobile/android-components/blob/688d1f236598a1ec3b548e324265c589a9557b87/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt#L101) like

>AppLinkRedirect(appIntent=Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=spotify://user/spotify/playlist/37i9dQZF1DX3PFzdbtx1Us?adjust_reftag=csHngdU62eod1 pkg=com.spotify.music (has extras) }, webUrl=http://open.spotify.com/user/spotify/playlist/37i9dQZF1DX3PFzdbtx1Us?nd=1, isFallback=true)

which [we'll then open in an external app](https://github.com/mozilla-mobile/android-components/blob/688d1f236598a1ec3b548e324265c589a9557b87/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt#L124).

Being that the Spotify website specifically sends us a deeplink to open the Spotify app I'd say the situation described here is not a bug the intended behavior, and also the same behavior seen in other browsers for the same STRs.

**Comment by boek** [comment] 2019-12-28 16:49
This should be resolved with #3177

**Closed by boek** 2019-12-28 16:49 UTC
Labels: S2, 🐞 bug
