### ISSUE TITLE
[Bug] Font sizes on non-mobile pages are tiny

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#4458] opened 2019-08-01 17:14 UTC
## Steps to reproduce
Visit any of
* https://history.nasa.gov/afj/ap11fj/01launch.html
* http://diamondgeezer.blogspot.com/
* https://web.archive.org/web/20140613214731/http://www.corante.com/pipeline/20040101.shtml
* or any other page that doesn't have a mobile/responsive layout and correspondingly doesn't have a `<meta name="viewport" content="width=device-width, initial-scale=1">` (or similar) tag

### Expected behavior

Font size of the main text content of the page (side bars, nav bars, etc. may remain tiny) is readable.
See behaviour in Chrome, or in Fennec with "Use system font size" (and therefore font inflation) turned on.

### Actual behavior

Font sizes are rather on the tiny side.

### Device information

* Android device: Moto G4 Play, Android 6.0.1
* Fenix version: Nightly 190801 06:18 (build 12130632) GV 69.0-20190729080047

**Comment by sblatz** [comment] 2019-08-08 21:45
This is a GV issue. I've reproduced in Reference Browser.

@cpeterso is there a bugzilla filed?

**Comment by ekager** [comment] 2019-08-09 03:52
Some more history to this issue: Font inflation used to be on included with the automatic setting but there were some issues (see #3639 #4050). We should definitely revisit this issue

**Comment by vesta0** [comment] 2019-08-09 04:03
@snorp what is the desired implementation here for Fennec parity? The current state of Fenix is fontInflation is not enabled at any time. Also see the 2 bugs Emily has referenced above.

**Comment by buttercookie42** [comment] 2019-08-09 06:09
@sblatz Yes and no. It's indeed the default state of GeckoView, but it's equally the application's choice to enable font inflation or not.

Now I can't guarantee that there won't be any other layout issue at all with font inflation, but the particular problem that led to #3639 has already been fixed in Gecko through the fix for #2606, and as I far as I can tell, this has also helped with at least part of #4050.

**Comment by cpeterso** [comment] 2019-08-10 01:33
> This is a GV issue. I've reproduced in Reference Browser.
> 
> @cpeterso is there a bugzilla filed?

I don't know of a GV bug for this. What is the desired behavior? The text on pages like http://diamondgeezer.blogspot.com/ is really tiny (but different) in both Fenix and Fennec.

We should fix GV's default settings if web content looks bad out of the box. We don't want every GV-powered app to have to discover and fix the same font size problems if we can fix them in GV. :)

I see that using the system font size  is enabled by default in Fenix (the "Accessibility > Automatic Font Sizing" setting), but I don't know if that also enables font inflation.

> @snorp what is the desired implementation here for Fennec parity? The current state of Fenix is fontInflation is not enabled at any time. Also see the 2 bugs Emily has referenced above.

snorp asked Fenix to disable font inflation in #3639 but @buttercookie42 recommended enabling it there. Fenix and GV aren't beholden to Fennec UX parity if we can do better now.

**Comment by cpeterso** [comment] 2019-08-14 21:27
@apbitner - We need some UX feedback on Fenix's (and thus probably GeckoView's) default font settings. For example, do we want to use system font sizes ("Automatic Font Sizing" setting) and/or enable font inflation for non-mobile content by default? I think we discussed font defaults when you designed Fenix's font size controls.

@buttercookie42 is a Fennec and GeckoView contributor and has found (like this Fenix bug) and fixed some mobile font bugs in Fennec and GeckoView, so he has experience and opinions on fonts. :)

**Comment by lime124** [comment] 2019-08-14 23:01
assigning to @apbitner removing ux label. thanks!

**Comment by apbitner** [comment] 2019-08-15 15:47
@cpeterso @buttercookie42 TBH when we added the 'Automatic Font Sizing' toggle to Fenix accessibility settings I thought that would include font inflation. Would fixing that suffice, vs needing an additional toggle?

**Comment by buttercookie42** [comment] 2019-08-16 15:48
@apbitner That was the original GeckoView behaviour because it directly mimicked the behaviour of Fennec's "Use system font size" toggle, however as of [bug 1561135](https://bugzilla.mozilla.org/show_bug.cgi?id=1561135) the automatic font size setting in GeckoView was decoupled from the font inflation setting, so turning on the former no longer automatically turns on the latter.

While this was done with the main intention of turning font inflation in Fenix off (prompted by #3639), which I disagree with, especially now that [bug 1552781](https://bugzilla.mozilla.org/show_bug.cgi?id=1552781) has been fixed (which in hindsight seems to have affected quite a number of pages), in the end I do actually agree with the premise that *in GeckoView*, turning on `setAutomaticFontSizeAdjustment` should be orthogonal to the state of `setFontInflation`. An app could always get back the old behaviour by simply always flipping both switches together, which is in fact what Fennec does (although in Fennec, the default state of that setting - and therefore font inflation - is off).

So the main question is still whether we're okay with allowing font inflation to be turned back on in some way or other, or even having it turned on by default again.

**Comment by apbitner** [comment] 2019-08-20 17:21
@buttercookie42 I will leave the implementation up to engineering, but is there any reason _not_ to include font inflation with our current 'Automatic Font Sizing' toggle? Right now the description for that toggle reads 'Font size will match your Android settings', but that's not exactly happening because we don't have font inflation, correct?

**Comment by bifleming** [comment] 2019-08-21 19:32
@ekager @boek please see buttercookie42's comment above about turning font inflation back on...

**Comment by liuche** [comment] 2019-08-22 18:23
There are 3 kinds of controls for font size:
- `fontInflation` - GV makes an educated guess: font sizes will be increased on all pages that are lacking a <meta> viewport tag by `fontSizeFactor`
- `fontSizeFactor` - fontsize multiplier used everywhere in the app when inflating
- `automaticFontSizeAdjustment` - matching the Android System font size

> is there any reason _not_ to include font inflation with our current 'Automatic Font Sizing' toggle? 

There have been some on Font Inflation breakages on some sites (bugzilla, mozilla sites), so it's kind of a site compatibility issue.

(Alternatively, we might also want to recommend a different font size to GeckoView to include by default.)

I guess it's a question of what sites we are willing to break. I'm leaning towards turning it on by default bc the broken sites seem low-usage #3639 #4050.

@snorp any concerns? o/w let's just turn it on. Not sure if there is telemetry we can add to see if this is a problem, or do we have to just look at user reviews.

**Comment by buttercookie42** [comment] 2019-08-22 21:05
> font sizes will be increased on all pages that are lacking a viewport tag by `fontSizeFactor`

Not quite. For font inflation, a `fontSizeFactor` of 1.0 simply means to apply the default amount of font inflation, which is intended to bring the main content of those kinds of pages to approximately the same readability as a page using the same nominal font sizes in a `width=device-width` viewport. `fontSizeFactors` smaller or larger than 1.0 then just further decrease/increase the amount of font size scaling applied.

> `fontSizeFactor` - fontsize multiplier used everywhere in the app when inflating

More precisely, outside of font inflation, we apply a simple text zoom based on the factor. The text zoom is therefore applied on all pages where font inflation doesn't apply - whether because the page is ineligible for font inflation [2], or because font inflation has been turned off completely via the runtime settings.

> automaticFontSizeAdjustment - matching the Android System font size

I.e. the `fontSizeFactor` is simply set to match the OS font size factor.

> Not sure if there is telemetry we can add to see if this is a problem, or do we have to just look at user reviews.

If we could detect particular kinds of brokenness via telemetry, it would be preferable to just apply the same logic during font inflation itself to prevent the brokenness from happening in the first place. [3]

[1] But because pages without a viewport tag will be rendered using the desktop viewport, they will (when zoomed out so you don't have to scroll horizontally) still appear with a more tiny font size than mobile pages.
[2] There are a few more reasons where font inflation is turned off, but the main one is the presence of a `width=device-width` meta viewport tag as *the* signifier for a mobile-friendly page.
[3] Okay, font inflation needs to happen *during* layouting of the page, whereas telemetry could simply look at the finished result afterwards, so it's not quite the same thing, but generally I think that point stands.

**Comment by bifleming** [comment] 2019-09-04 16:45
@liuche @ekager What are next steps on this?

**Comment by liuche** [comment] 2019-09-06 17:46
Let's enable font inflation.

**Comment by cpeterso** [comment] 2019-09-10 22:01
> **Let's enable font inflation**. I looked at this issue a little, and it looks strictly better for these sites. #2477 should also help here later on.

If Fenix will enable font inflation by default, GV should probably change its font inflation default to match. In the meantime, Fenix can enable font inflation now without waiting for GV to change.

I filed a new GV bug to match Fenix's new default: https://bugzilla.mozilla.org/show_bug.cgi?id=1580344

**Comment by liuche** [comment] 2019-09-13 20:41
hey @ekager can you make sure to add labels and move things to the right column in the future? I realized I was moving this around when I didn't need to.

**Comment by sv-ohorvath** [comment] 2019-09-16 13:34
Verified as fixed on Nightly 9/16. Devices: Samsung Galaxy Tab A6 (Android 5.1.1), Galaxy S8 (Android 9)

**Closed by sv-ohorvath** 2019-09-16 13:34 UTC
Labels: P3, eng:qa:needed, needs:gv, 🐞 bug
