### ISSUE TITLE
[Bug] Send to Firefox device missing from other apps, eg youtube app

### ISSUE THREAD

**Issue by FeeFox** [mozilla-mobile/fenix#14196] opened 2020-08-25 22:17 UTC
## Steps to reproduce
in Youtube android app, tap icon to send/forward

### Expected behavior
Add to device shows within Youtube, with an icon for my laptop's Firedox to send to my laptop
### Device information
Samsung S9 and Windows laptop

* Android device: ? Samsung S9
* Fenix version: ? what is fenix

**Comment by jonalmeida** [comment] 2020-08-25 23:52
Duplicate of https://github.com/mozilla-mobile/fenix/issues/1523.

**Closed by jonalmeida** 2020-08-25 23:52 UTC
Labels: needs:triage, 🐞 bug
