### ISSUE TITLE
Ability to close multiple tabs using multiple finger swipe

### ISSUE THREAD

**Issue by Sgt-Miller** [mozilla-mobile/fenix#11695] opened 2020-06-17 15:56 UTC
### What is the user problem or growth opportunity you want to see solved?
I end up having multiple tabs after a browsing session (like 20). I'm in the latest nightly where tab view is quite large. To remove say 10 tabs, i have to swipe 10 times. Instead if I use multiple fingers, i should be able to swipe multiple tabs (and close them) at same time.

### How do you know that this problem exists today? Why is this important?
Saves time.

### Who will benefit from it?
Everyone who use many tabs. Adding this feature will not affect those who use only few tabs or those who want to clise one tab at a time.

**Comment by yoasif** [comment] 2020-06-17 21:01
This feels too weird, imo and would break expectations of how these swipes work in other Android apps.

**Comment by Dunexus** [comment] 2020-06-17 21:07
Swipe multiple elements is not what is usually done in android.
Maybe allowing closing multiple tabs via a multiselect mode (see https://github.com/mozilla-mobile/fenix/issues/10163) is more consistent with android behavior.

**Comment by amkcpu** [comment] 2020-08-26 16:21
> Maybe allowing closing multiple tabs via a multiselect mode (see #10163) is more consistent with android behavior.

See #2735.

**Comment by kbrosnan** [comment] 2020-08-26 17:13
Closing as a duplicate of #2735

**Closed by kbrosnan** 2020-08-26 17:13 UTC
Labels: needs:triage
