### ISSUE TITLE
[Bug] 'Your Privacy' onboarding card does not mention automatic telemetery enabled

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#3717] opened 2019-06-27 18:20 UTC
In the onboarding card 'Your Privacy', there is no mention that telemetry is enabled by default (see screenshot below).

### Expected behavior
 - Mention that telemetry is enabled **[Vesta] and how to disable it**
 - (nice-to-have) A toggle switch to disable it in onboarding? ### [Vesta] might be too many options in onboarding

### Actual behavior
 - No mention of telemetry enabled.

### Device information

* Android device: n/a
* Fenix version: 27/06/19

![Screenshot_20190711-131508](https://user-images.githubusercontent.com/1370580/61071973-570d4500-a3e0-11e9-9194-e09cf05777b9.png)

**Comment by vesta0** [comment] 2019-07-03 05:36
@mheubusch @apbitner  can we have strings and updated designs for this?

**Comment by mheubusch** [comment] 2019-07-11 11:09
The onboarding card was approved by legal.  The issue is that the data collection settings should be updated to reflect the same language in the privacy notice - that Usage and interaction data is collected by default. Note that the label for the section is Data collection (not choices) and the telemetry collection is called Usage and interaction data

<img width="342" alt="Screen Shot 2019-07-11 at 7 07 14 AM" src="https://user-images.githubusercontent.com/20115914/61046281-bcdeda00-a3aa-11e9-94e2-29ec9f097b33.png">

<img width="395" alt="Screen Shot 2019-07-11 at 7 06 36 AM" src="https://user-images.githubusercontent.com/20115914/61046289-c1a38e00-a3aa-11e9-9cb9-05a5092de832.png">

**Comment by mheubusch** [comment] 2019-07-11 11:12
@vesta0 please move into dev if you approve the previously designed solution.

**Comment by jonalmeida** [comment] 2019-07-11 17:49
FYI: I've added a screenshot into the issue to ensure we're referring to the same thing.

**Comment by vesta0** [comment] 2019-07-15 03:01
@mheubusch the proposed changes does provide more clarification. If you and Legal both approved onboarding then we can close this issue.

**Closed by vesta0** 2019-07-15 03:01 UTC
Labels: Feature:Onboarding, Feature:Telemetry, Needs Product, P1, 🌐 L10N, 🐞 bug, 🙅 waiting
