### ISSUE TITLE
FNX3-16433 ⁃ [Bug] Long press - paste options

### ISSUE THREAD

**Issue by nikoloskid** [mozilla-mobile/fenix#2590] opened 2019-05-16 23:29 UTC
## Steps to reproduce
![60699281](https://user-images.githubusercontent.com/12738743/57893134-09da8000-7842-11e9-9895-2300aa21778b.jpg)UNITO-UNDERSCORE!584242731985684!UNITO-UNDERSCORE!8319928792877367296!UNITO-UNDERSCORE!n!

This bug was also issued by a user on e-mail at "Fenix Nightly" group, I have the issue on Gboard but after a few tries I got the paste option, while the other user issue is with Swiftkey which is switching to number keyboard, but does not bring paste option also.

1. I copied my account number from a cloud
1. Opened a tab 
1. Long press on a account number field, there is no option for paste/select all.

### Expected behavior
* Copied the account number, long pressed it on the field and should have option to paste.

### Device information
* Android device: Huawei P20 Lite / 8.0
* Fenix version: 1.0.1920

**Comment by vesta0** [comment] 2019-05-30 22:29
@cpeterso is there a bug open for this in bugzilla?

**Comment by cpeterso** [comment] 2019-05-31 22:14
I can reproduce a lesser version of this bug in Fennec 69 Nightly and Fenix on my Moto G5 Plus (Android 8.1 with the default Gboard keyboard).

When I long press in the input form in Chrome, I get the "PASTE" menu and no keyboard. If I long press in the input form in Fennec or Fenix, I see a "PASTE | SELECT ALL" menu flash open for a moment, then close as the keyboard opens. With the keyboard open, I can then long press a second time to open the "PASTE | SELECT ALL" menu again.

I filed a new GV bug: 

Mullvad login page: https://mullvad.net/en/account/login/

**Comment by sblatz** [comment] 2019-07-01 19:54
Sounds like this is blocked on the GV patch.

**Comment by vesta0** [comment] 2019-07-08 18:22
To be tested after update to GV 69

**Comment by bifleming** [comment] 2019-07-24 19:48
Waiting on GV 69 OR uplift to 68

**Comment by ekager** [comment] 2019-07-30 22:33
Since we're now on GV69 can we retest and close this if it's fixed? :)

**Comment by AndiAJ** [comment] 2019-07-31 12:59
Hi, **verified as fixed** using both Gboard and Switkey on **Nightly Build #12112106** from **31/7** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)

► Video Huawei Mate 20 Lite - **Gboard**
![20190731_154935](https://user-images.githubusercontent.com/51314259/62213540-d4a6ee00-b3ab-11e9-87f1-2a68aa13f749.gif)


► Video Huawei Mate 20 Lite - **Switkey**
![20190731_155301](https://user-images.githubusercontent.com/51314259/62213638-0a4bd700-b3ac-11e9-82ff-5a0cc77874c8.gif)

**Closed** 2020-08-12 17:44 UTC
Labels: P1, eng:qa:verified, 🐞 bug
