### ISSUE TITLE
[Bug] Sometimes when i load a new page, it just reloads the current webpage, and the new webpage is instead loaded to the previous tab

### ISSUE THREAD

**Issue by larserno** [mozilla-mobile/fenix#18403] opened 2021-03-09 17:21 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Does not happen all the time.
Don´t know how to reproduce
### Expected behavior
New page loads in the current tab
### Actual behavior
My current webpage gets reloaded, and the new webpage is instead loaded to my previous tab
### Device information
Xiaomi mi 10, MIUI 12.2.4 Global, android 11
Firefox Nightly 210304 17:01
* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by EsliStavenga** [comment] 2021-03-15 22:38
Same here, mostly seems to happen after fully closing the app (removing it from multitasking) and then opening the app again

Oneplus 7 Pro
86.1.1 (Build #2015794883)

**Comment by lobontiumira** [comment] 2021-03-30 13:52
I was not able to reproduce this on the 3/30 Nightly build with Xiaomi Mi 8 Lite (Android 9).

**Closed** 2021-10-03 17:09 UTC
Labels: 🐞 bug, Feature:Tabs, needs:triage, wontfix, qa-triaged
