### ISSUE TITLE
Lazy load TabPreview in BaseBrowserFragment

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#13907] opened 2020-08-18 20:35 UTC
The TabPreview in the BaseBrowserFragment layout is a good candidate for lazy loading since its only needed for swiping between tabs.

context: https://github.com/mozilla-mobile/fenix/issues/13330#issuecomment-675177794

**Comment by jonalmeida** [comment] 2020-09-19 13:48
From https://github.com/mozilla-mobile/fenix/issues/13763#issuecomment-695175204, this issue is for using a ViewStub to inflate the TabPreview.

Let's run the profiler a few times so that can see how much we would be saving and if it's substantial enough to do this work.

**Comment by jonalmeida** [comment] 2021-03-24 03:38
Let's keep this since it was filed as a view regression and we should address/verify if it no longer exists before closing.

**Comment by mcomella** [comment] 2022-01-26 23:03
Triage: we don't know if this refactor will really benefit performance for sure. If it is and it's non-trivial, we're likely to pick it up during another performance investigation and refile so I think we can close this.

**Closed by mcomella** 2022-01-26 23:03 UTC
Labels: performance, pin
