### ISSUE TITLE
[Bug] inconsistent margins in bottom bar

### ISSUE THREAD

**Issue by fotonmoton** [mozilla-mobile/fenix#3793] opened 2019-06-29 09:29 UTC
## Steps to reproduce
Open link in Firefox Prrview
### Expected behavior
Margins between bottom bar elements are the same
### Actual behavior
Tabs button right margin are larger than left, options button right margin larger than url input left margin.
### Device information

* Android device: Xiaomi Note 4X, Android 7.0
* Fenix version: 1.0.0 (Build #11721515 🦎 68.0-20190611143747

![Screenshot_2019-06-29-12-21-13-870_org mozilla fenix](https://user-images.githubusercontent.com/7763084/60382289-aca13380-9a69-11e9-8f20-0703f9a573c8.png)

**Comment by sblatz** [comment] 2019-07-22 20:33
Can we get @ux confirmation on the expected margins here

**Comment by topotropic** [comment] 2019-07-23 12:09
![bottom-bar](https://user-images.githubusercontent.com/353960/61711019-587d2c80-ad53-11e9-8057-a2917d987af4.png)
this is a dupe of https://github.com/mozilla-mobile/fenix/issues/1469

**Comment by Scripterr** [comment] 2019-07-23 13:35
I would also like to point out one more related issue regarding url bar that there is no clear distinction between the bottom bar and the web content sometimes. Like there is a drop shadow/elevation between the url bar and QAB, which doesn't help much but will be more helpful if it is between the webcontent and bottom bar.
![Screenshot_20190723-184042~2](https://user-images.githubusercontent.com/42364681/61715178-097fc900-ad4c-11e9-9f86-62f047055063.png)

**Comment by sblatz** [comment] 2019-07-23 16:52
Closing this as a dup of #1469, thanks @topotropic!

**Comment by sblatz** [comment] 2019-07-23 16:52
@Scripterr can you please file a follow up issue for that? :)

**Closed by sblatz** 2019-07-23 16:52 UTC
Labels: P3, eng:quality, 🐞 bug
