### ISSUE TITLE
[Bug] Deleted bookmarks reappear briefly

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#2512] opened 2019-05-15 14:13 UTC
## Steps to reproduce
1. Bookmark a few pages.
1. Go to Settings - Bookmarks.
1. From three-dot menu delete each bookmarked page.

### Expected behavior
The deleted bookmarks should not be displayed anymore.

### Actual behavior
The deleted bookmarks reappear briefly.

### Device information
* Android devices: Google Pixel (Android 9), HTC 10 (Android 8)
* Fenix version: 1.0.1920 (#11350639)

### Note
The issue is reproducible even when each page is long-tapped and deleted from three-dot menu from the top of the page.

![bookmarks](https://user-images.githubusercontent.com/40694158/57782149-4fa92280-7734-11e9-84de-a289b631248c.gif)

**Comment by softvision-miralobontiu** [comment] 2019-05-15 14:13
Here is the logcat:
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3182891/1.txt)

**Comment by sv-ohorvath** [comment] 2019-05-15 14:17
dupe of #2226

**Closed** 2020-08-26 05:49 UTC
