### ISSUE TITLE
FNX-5036 ⁃ [UX nit] Search box on Home screen not identical to search box on Search screen

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#1448] opened 2019-04-07 17:25 UTC
STR

* Go to Home screen
* scroll so search box is at top of screen
* tap search box to move to Search screen

-> the search boxes look subtly different on the two screens

* Search screen box is less tall than Home screen
* Search screen box has gray font, Home screen is black
* Search screen has larger font than Home screen
* Search screen Google icon is slightly left & down of Home screen Google icon
* Search screen text justification is slightly further right than Home screen

(there are probably more issues)

A nit but it does annoy me :grinning:  cheers now

**Comment by kbrosnan** [comment] 2019-04-27 04:57
Dupe of #1197

**Closed** 2020-08-11 11:38 UTC
Labels: Feature:HomeScreen, Feature:Search, eng:quality, needs:UX-feedback
