### ISSUE TITLE
[Bug] apple.com can be spoofed

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#16127] opened 2020-10-22 16:32 UTC
## Steps to reproduce 
visit https://www.xn--80ak6aa92e.com/

### Expected behavior
See the fact that it's a punicode character in the URL and see that it's not apple.com
![Screenshot_20201022-193548_Ungoogled_Chromium](https://user-images.githubusercontent.com/922368/96903010-e9ced780-149d-11eb-8246-1c6dfa47b53d.png)
![Screenshot_20201022-193603_Ungoogled_Chromium](https://user-images.githubusercontent.com/922368/96903011-eb000480-149d-11eb-9121-dccca664dcb6.png)

### Actual behavior
see it as if it's https://apple.com
![Screenshot_20201022-193517_Firefox_Nightly](https://user-images.githubusercontent.com/922368/96902992-e4718d00-149d-11eb-841b-c3041f7e0022.png)

### Device information

* Android device: All/OnePlus5t
* Fenix version: All/Nightly
 
https://en.m.wikipedia.org/wiki/IDN_homograph_attack

**Comment by kbrosnan** [comment] 2020-10-22 16:38
Duplicate of #5640

**Closed by kbrosnan** 2020-10-22 16:38 UTC
Labels: needs:triage, 🐞 bug
