### ISSUE TITLE
[Bug] master crashes with geckoNightlyDebug BV

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/fenix#4962] opened 2019-08-27 20:39 UTC
## Steps to reproduce
- Launch Fenix

### Expected behavior
- Fenix launches

### Actual behavior
- Fenix Crahes
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 27352
    java.lang.RuntimeException: Unable to create application org.mozilla.fenix.DebugFenixApplication: kotlin.UninitializedPropertyAccessException: lateinit property fretboard has not been initialized
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property fretboard has not been initialized
        at org.mozilla.fenix.FenixApplication.getFretboard(FenixApplication.kt:40)
        at org.mozilla.fenix.ExperimentsKt.isInExperiment(Experiments.kt:28)
        at org.mozilla.fenix.components.BackgroundServices.<init>(BackgroundServices.kt:82)
        at org.mozilla.fenix.components.Components$backgroundServices$2.invoke(Components.kt:17)
        at org.mozilla.fenix.components.Components$backgroundServices$2.invoke(Components.kt:15)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.mozilla.fenix.components.Components.getBackgroundServices(Unknown Source:7)
        at org.mozilla.fenix.FenixApplication.setupPush(FenixApplication.kt:187)
        at org.mozilla.fenix.FenixApplication.setupApplication(FenixApplication.kt:69)
        at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:49)
        at org.mozilla.fenix.DebugFenixApplication.onCreate(DebugFenixApplication.kt:42)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.RuntimeException: Unable to create application org.mozilla.fenix.DebugFenixApplication: kotlin.UninitializedPropertyAccessException: lateinit property fretboard has not been initialized)
I/mozac/CrashReporter: Showing prompt
Process 27352 terminated.
```
### Device information

* Android device: Pixel 2
* Fenix version: master

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13183)

**Comment by cadeyrn** [comment] 2019-08-27 20:42
Duplicate of #4960.

**Closed as completed** 2019-08-27 20:44 UTC
Labels: 🐞 bug
