### ISSUE TITLE
[Settings] Entering PIN doesn't unlock Saved passwords

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#7095] opened 2019-12-11 21:01 UTC
Steps to reproduce:

1. Go to Settings -> Passwords
2. Tap on "Saved logins"
3. Select "Use PIN" when asked to authenticate
4. Enter device PIN

Expected: 
Shows Saved logins list

Actual:
Authentication screen closes and goes back to Logins and passwords screen.

**Comment by liuche** [comment] 2019-12-17 18:48
In triage, it's been repro-ed on Pixel 2, some Pixel 3

**Comment by cadeyrn** [comment] 2019-12-18 12:28
Oh, I thought it's not yet implemented. But seeing this comment and the screen in #7268 it seems that it's supposed to work. 😅

If you need one more data point: It does **_not_** work on my OnePlus 7T Pro.

**Comment by mcarare** [comment] 2020-01-03 16:11
This seems to happen only when the prompt is previously dismissed.

**Comment by abodea** [comment] 2020-01-08 12:57
Verified as fixed on the latest **Nightly** build from **1/8** with **Samsung Galaxy S10+(Android 9).**

**Closed by abodea** 2020-01-08 12:57 UTC
Labels: Feature:Logins, eng:qa:needed, 🐞 bug

**Comment by cadeyrn** [comment] 2020-01-08 20:05
It's still **not** working.

Fenix master branch revision 2bdde4898687c15e9f2c7d0dc5c67f6c3a5ad716
OnePlus 7T Pro McLaren Edition with Android 10

**Comment by ekager** [comment] 2020-01-09 04:12
Hi @cadeyrn just checking - does it crash or just not work? Do you see any similar behavior in other apps?

I ask because I found this thread about biometrics not working correctly on OnePlus 7T Pro 
https://forums.oneplus.com/threads/biometric-unlock-not-working-for-apps.1128033/

**Comment by cadeyrn** [comment] 2020-01-09 07:38
@ekager It doesn't crash, it just not work. On the "Logins and passwords" screen I press the "Saved logins" row, then the "Unlock to view your saved logins" screen appears. After unlocking I am on the "Logins and passwords" screen again. It happens with both the PIN as well as with the fingerprint sensor as authentication methid.

Biometrics are working on my device in Firefox Lockwise and in my online banking app.

**Comment by mcarare** [comment] 2020-01-09 08:22
@caderyn So the issue is with auth, not just with PIN auth. This should be opened in another issue.

**Comment by cadeyrn** [comment] 2020-01-09 08:27
Well, the original report does not mention biometrics at all and the original report is still reproducible. I can open a new issue but it's exactly the same issue.

**Comment by cadeyrn** [comment] 2020-01-10 18:48
I opened #7603.

**Comment by AmyYLee** [comment] 2020-02-14 16:22
@ekager I wanted to confirm that it still doesn't work with PIN entry on Pixel 3. It works with biometrics.
