### ISSUE TITLE
[Bug] Tab tray sometimes starts at synced tabs instead of open tab

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#15047] opened 2020-09-13 16:50 UTC
## Steps to reproduce

0. Have synced tabs
1. Have opened tabs
2. Tap tab tray

### Expected behavior

The tab I am opening the tab from should be visible in the tray without scrolling. 

### Actual behavior

I see a random synced tab instead of the tab I expect to see. I have to scroll up to find the tab. 

![signal-2020-09-13-124450](https://user-images.githubusercontent.com/152493/93023839-d6d40800-f5bf-11ea-9102-3a14eaed5a63.gif)

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by jonalmeida** [comment] 2020-09-14 14:15
Duplicate of https://github.com/mozilla-mobile/fenix/issues/13905

**Closed by jonalmeida** 2020-09-14 14:15 UTC
Labels: needs:triage, 🐞 bug
