### ISSUE TITLE
Pages not loading. 

### ISSUE THREAD

**Issue by Kreuger** [mozilla-mobile/fenix#16746] opened 2020-11-25 22:03 UTC
Intermittently over the last few days, pages will load super slow or not at all. It's rather frustrating that I can't browse the internet and have to switch browsers. I'm on Android 10 using a Pixel 3 XL and Firefox Nightly 201123 build 2015777355.

**Comment by sflorean** [comment] 2021-01-11 15:06
Tested on Pixel 3 (Android 11) on latest Nightly and couldn't reproduce the issue. @Kreuger do you still reproduce this?

**Comment by Kreuger** [comment] 2021-01-11 19:50
Yes but I got tired of it not working and uninstalled the Nightly. There were no specific steps or websites. It just wouldnt load anything.

**Comment by ebalazs-sv** [comment] 2021-01-26 11:18
@Kreuger I can not reproduce this issue on the latest Nightly 1/26 with Motorola Moto G6 (Android 8).
When you will reproduce this issue, please provide the steps to reproduce and reopen it.

**Comment by Amejia481** [comment] 2021-01-26 14:06
I was also experiencing this on nightly yesterday, I don't have a set of step but the issue is there.

**Comment by Amejia481** [comment] 2021-01-26 14:16
Let's try to find a set of steps to reproduce.

**Comment by Amejia481** [comment] 2021-01-26 16:33
I'm not sure if is there a correlation but every time the page gets stuck loading I see these stack traces, the only happen when I kill the app and open it multiple times.



```
2021-01-26 11:05:38.028 1454-2023/org.mozilla.fenix.debug I/libglean_ffi: glean_core::upload: New upload task with id 34857670-42be-49d1-a363-0b4bcde66bb1 (path: /submit/org-mozilla-fenix-debug/baseline/1/34857670-42be-49d1-a363-0b4bcde66bb1)
2021-01-26 11:05:38.033 1454-2023/org.mozilla.fenix.debug D/glean/ConceptFetchHttpUploader: Submitting ping to: https://incoming.telemetry.mozilla.org/submit/org-mozilla-fenix-debug/baseline/1/34857670-42be-49d1-a363-0b4bcde66bb1
2021-01-26 11:05:55.873 1454-1742/org.mozilla.fenix.debug I/SessionStorage/AutoSave: Save: Periodic
2021-01-26 11:05:55.952 1454-1521/org.mozilla.fenix.debug D/SessionStorage/AutoSave: Saved state to disk [74ms]
2021-01-26 11:06:08.042 1454-2023/org.mozilla.fenix.debug W/glean/ConceptFetchHttpUploader: IOException while uploading ping
    java.net.SocketTimeoutException
        at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:67)
        at mozilla.components.service.glean.net.ConceptFetchHttpUploader.performUpload$service_glean_release(ConceptFetchHttpUploader.kt:99)
        at mozilla.components.service.glean.net.ConceptFetchHttpUploader.upload(ConceptFetchHttpUploader.kt:67)
        at mozilla.telemetry.glean.net.BaseUploader.upload(Unknown Source:18)
        at mozilla.telemetry.glean.net.BaseUploader.doUpload$glean_release(BaseUploader.kt:26)
        at mozilla.telemetry.glean.scheduler.PingUploadWorker.doWork(PingUploadWorker.kt:111)
        at androidx.work.Worker$1.run(Worker.java:85)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-01-26 11:06:08.069 1454-2023/org.mozilla.fenix.debug I/libglean_ffi: glean_core::upload: Recoverable upload failure while attempting to send ping 34857670-42be-49d1-a363-0b4bcde66bb1, will retry. Error was RecoverableFailure


```

And


```
2021-01-26 11:06:31.550 1454-1525/org.mozilla.fenix.debug E/GeckoConsole: [JavaScript Error: "[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 692"  data: no]"]
    L10nRegistry.loadSync@resource://gre/modules/L10nRegistry.jsm:692:19
    fetchFile@resource://gre/modules/L10nRegistry.jsm:607:31
    generateResourceSetSync/<@resource://gre/modules/L10nRegistry.jsm:512:19
    generateResourceSetSync@resource://gre/modules/L10nRegistry.jsm:507:22
    generateResourceSetsForLocaleSync@resource://gre/modules/L10nRegistry.jsm:449:44
    generateResourceSetsForLocaleSync@resource://gre/modules/L10nRegistry.jsm:458:15
    generateBundlesSync@resource://gre/modules/L10nRegistry.jsm:186:7
    next@resource://gre/modules/Localization.jsm:147:49
    formatWithFallbackSync@resource://gre/modules/Localization.jsm:287:5
    formatValuesSync@resource://gre/modules/Localization.jsm:396:17
    formatValueSync@
```

**Comment by Amejia481** [comment] 2021-01-26 16:35
Also I see this one when the page gets stock and I try load the same page over and over the common factor is that the loading progress gets stuck on 15%.



```
2021-01-26 11:27:53.353 8762-8905/org.mozilla.fenix.debug D/GeckoViewProgress: ProgressTracker updateProgress data={"prev":0,"uri":"https://wiki.mozilla.org/Main_Page","locationChange":false,"pageStart":true,"pageStop":false,"firstPaint":false,"pageShow":false,"parsed":false} progress=15
2021-01-26 11:27:53.354 8762-8905/org.mozilla.fenix.debug D/GeckoViewProgress: StateTracker onStateChange: isTopLevel=true, flags=0xf0001, status=NS_OK loadType=1
2021-01-26 11:27:53.366 8762-8762/org.mozilla.fenix.debug D/GeckoSession: handleMessage GeckoView:ProgressChanged uri=null
2021-01-26 11:27:53.367 8762-8762/org.mozilla.fenix.debug D/GeckoSession: handleMessage GeckoView:PageStart uri=https://wiki.mozilla.org/Main_Page
2021-01-26 11:27:53.367 8762-8762/org.mozilla.fenix.debug I/GeckoSession: handleMessage GeckoView:PageStart uri=
2021-01-26 11:27:54.361 8762-8762/org.mozilla.fenix.debug D/GeckoSession: handleMessage GeckoView:StateUpdated uri=null
2021-01-26 11:27:54.838 8762-9039/org.mozilla.fenix.debug I/SessionStorage/AutoSave: Save: Periodic
2021-01-26 11:27:54.887 8762-8917/org.mozilla.fenix.debug D/SessionStorage/AutoSave: Saved state to disk [47ms]
2021-01-26 11:27:55.349 8762-8905/org.mozilla.fenix.debug D/GeckoScreenOrientation: unlocking
2021-01-26 11:27:57.495 8762-8905/org.mozilla.fenix.debug I/Gecko: [Parent 8762: Main Thread]: D/AntiTracking Check partitioning exception list for url https://wiki.mozilla.org and https://bam.nr-data.net
2021-01-26 11:27:57.496 8762-8905/org.mozilla.fenix.debug I/Gecko: [Parent 8762: Main Thread]: D/AntiTracking Testing permission type 3rdPartyStorage^https://bam.nr-data.net for https://wiki.mozilla.org/Main_Page resulted in 0 (failure)
2021-01-26 11:27:57.598 8762-8905/org.mozilla.fenix.debug I/Gecko: [Parent 8762: Main Thread]: D/AntiTracking Check partitioning exception list for url https://wiki.mozilla.org and https://bam.nr-data.net
2021-01-26 11:27:57.598 8762-8905/org.mozilla.fenix.debug I/Gecko: [Parent 8762: Main Thread]: D/AntiTracking Testing permission type 3rdPartyStorage^https://bam.nr-data.net for https://wiki.mozilla.org/Main_Page resulted in 0 (failure)
2021-01-26 11:27:57.601 8762-8905/org.mozilla.fenix.debug I/Gecko: [Parent 8762: Main Thread]: D/AntiTracking Computing whether channel 0x6cb9fe2040 has access to URI https://bam.nr-data.net/events/1/4c203d12f7?a=149389314&v=1194.94d5a62&to=MVRbZkFTD0MCBkJYXAgeeFFHWw5eTARVRVoJXxZEWlcW&rst=10872
2021-01-26 11:27:57.602 8762-8905/org.mozilla.fenix.debug I/chatty: uid=11230(org.mozilla.fenix.debug) Gecko identical 2 lines
2021-01-26 11:27:57.602 8762-8905/org.mozilla.fenix.debug I/Gecko: [Parent 8762: Main Thread]: D/AntiTracking Computing whether channel 0x6cb9fe2040 has access to URI https://bam.nr-data.net/events/1/4c203d12f7?a=149389314&v=1194.94d5a62&to=MVRbZkFTD0MCBkJYXAgeeFFHWw5eTARVRVoJXxZEWlcW&rst=10872
2021-01-26 11:27:58.349 8762-8762/org.mozilla.fenix.debug D/LeakCanary: Scheduling check for retained objects because found new object retained
2021-01-26 11:27:58.350 8762-8762/org.mozilla.fenix.debug D/LeakCanary: Ignoring request to check for retained objects (found new object retained), already scheduled in 0ms
2021-01-26 11:27:58.350 8762-8762/org.mozilla.fenix.debug I/chatty: uid=11230(org.mozilla.fenix.debug) AndroidUI identical 1 line
2021-01-26 11:27:58.350 8762-8762/org.mozilla.fenix.debug D/LeakCanary: Ignoring request to check for retained objects (found new object retained), already scheduled in 0ms
2021-01-26 11:27:58.414 8762-8832/org.mozilla.fenix.debug I/lla.fenix.debu: Explicit concurrent copying GC freed 41330(1795KB) AllocSpace objects, 3(60KB) LOS objects, 75% free, 7788KB/31MB, paused 93us total 64.086ms
2021-01-26 11:27:58.421 8762-8780/org.mozilla.fenix.debug D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks. Callsite: readFromParcel
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1929)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:305)
        at android.view.SurfaceControl.finalize(SurfaceControl.java:1104)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
        at java.lang.Daemons$Daemon.run(Daemons.java:139)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by Amejia481** [comment] 2021-01-26 16:42
> I'm not sure if is there a correlation but every time the page gets stuck loading I see these stack traces, the only happen when I kill the app and open it multiple times.
> 
> ```
> 2021-01-26 11:05:38.028 1454-2023/org.mozilla.fenix.debug I/libglean_ffi: glean_core::upload: New upload task with id 34857670-42be-49d1-a363-0b4bcde66bb1 (path: /submit/org-mozilla-fenix-debug/baseline/1/34857670-42be-49d1-a363-0b4bcde66bb1)
> 2021-01-26 11:05:38.033 1454-2023/org.mozilla.fenix.debug D/glean/ConceptFetchHttpUploader: Submitting ping to: https://incoming.telemetry.mozilla.org/submit/org-mozilla-fenix-debug/baseline/1/34857670-42be-49d1-a363-0b4bcde66bb1
> 2021-01-26 11:05:55.873 1454-1742/org.mozilla.fenix.debug I/SessionStorage/AutoSave: Save: Periodic
> 2021-01-26 11:05:55.952 1454-1521/org.mozilla.fenix.debug D/SessionStorage/AutoSave: Saved state to disk [74ms]
> 2021-01-26 11:06:08.042 1454-2023/org.mozilla.fenix.debug W/glean/ConceptFetchHttpUploader: IOException while uploading ping
>     java.net.SocketTimeoutException
>         at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:67)
>         at mozilla.components.service.glean.net.ConceptFetchHttpUploader.performUpload$service_glean_release(ConceptFetchHttpUploader.kt:99)
>         at mozilla.components.service.glean.net.ConceptFetchHttpUploader.upload(ConceptFetchHttpUploader.kt:67)
>         at mozilla.telemetry.glean.net.BaseUploader.upload(Unknown Source:18)
>         at mozilla.telemetry.glean.net.BaseUploader.doUpload$glean_release(BaseUploader.kt:26)
>         at mozilla.telemetry.glean.scheduler.PingUploadWorker.doWork(PingUploadWorker.kt:111)
>         at androidx.work.Worker$1.run(Worker.java:85)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:923)
> 2021-01-26 11:06:08.069 1454-2023/org.mozilla.fenix.debug I/libglean_ffi: glean_core::upload: Recoverable upload failure while attempting to send ping 34857670-42be-49d1-a363-0b4bcde66bb1, will retry. Error was RecoverableFailure
> ```
> 
> And
> 
> ```
> 2021-01-26 11:06:31.550 1454-1525/org.mozilla.fenix.debug E/GeckoConsole: [JavaScript Error: "[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 692"  data: no]"]
>     L10nRegistry.loadSync@resource://gre/modules/L10nRegistry.jsm:692:19
>     fetchFile@resource://gre/modules/L10nRegistry.jsm:607:31
>     generateResourceSetSync/<@resource://gre/modules/L10nRegistry.jsm:512:19
>     generateResourceSetSync@resource://gre/modules/L10nRegistry.jsm:507:22
>     generateResourceSetsForLocaleSync@resource://gre/modules/L10nRegistry.jsm:449:44
>     generateResourceSetsForLocaleSync@resource://gre/modules/L10nRegistry.jsm:458:15
>     generateBundlesSync@resource://gre/modules/L10nRegistry.jsm:186:7
>     next@resource://gre/modules/Localization.jsm:147:49
>     formatWithFallbackSync@resource://gre/modules/Localization.jsm:287:5
>     formatValuesSync@resource://gre/modules/Localization.jsm:396:17
>     formatValueSync@
> ```

I commented the `initializeGlean` and still I'm able to reproduce.

**Comment by Amejia481** [comment] 2021-01-26 19:22
I was able to reproduce in geckoview example app, I will open a ticket for the gv team to take a look: 

https://user-images.githubusercontent.com/773158/105894060-dde53b00-5fe1-11eb-9ffe-c3a357be0e77.mp4

[geckoview_example_logs1.txt](https://github.com/mozilla-mobile/fenix/files/5875565/geckoview_example_logs1.txt)
[geckoview_example_logs2.txt](https://github.com/mozilla-mobile/fenix/files/5875566/geckoview_example_logs2.txt)

**Comment by Amejia481** [comment] 2021-01-26 19:31
I opened a bug for the geckoview team to take a look https://bugzilla.mozilla.org/show_bug.cgi?id=1688957

**Comment by Amejia481** [comment] 2021-01-26 21:52
After testing on Chrome we discovered that was an network issue, closing because this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1688957#c3

**Closed by Amejia481** 2021-01-26 21:52 UTC
Labels: S1, needs:gv, 🐞 bug, 🙅 waiting
