### ISSUE TITLE
Do not suggest random websites when entering something into the url bar

### ISSUE THREAD

**Issue by polychloriert** [mozilla-mobile/fenix#14422] opened 2020-08-29 07:36 UTC
### What is the user problem or growth opportunity you want to see solved?
When starting to type something into the url bar because I e.g. wnat to look something up with the default search engine, FF will suggest random website URLs for autocompletion which I have never visited. This bevahivor should be controllable via the settings menu.

### How do you know that this problem exists today? Why is this important?
This looks to be a privacy leak and is annoying. 

### Who will benefit from it?
People who value their privacy.

**Comment by s-ankur** [comment] 2020-08-29 08:17
Duplicate of  #5745

Also this is not at all a privacy issue. The domains are taken from a list of most popular websites by country. 


https://github.com/mozilla-mobile/android-components/tree/master/components/browser/domains/src/main/assets/domains

**Comment by kbrosnan** [comment] 2020-08-30 14:46
Closing as a duplicate

**Closed by kbrosnan** 2020-08-30 14:46 UTC
Labels: needs:triage
