### ISSUE TITLE
[Bug] Unable to reorder tabs

### ISSUE THREAD

**Issue by twidi** [mozilla-mobile/fenix#8385] opened 2020-02-13 13:36 UTC
## Steps to reproduce

- Have some tabs opened
- Long press on a tab to move it at another place in the tabs list

### Expected behavior

- The long-pressed tab can be moved

### Actual behavior

- A new page "select tabs" is opened

### Device information

* Android device: Huawei mate 20 pro, Android 10
* Fenix version: "Firefox preview 200210 10:05 (Build #2015722195) 31.0.0"

**Comment by cadeyrn** [comment] 2020-02-13 13:47
Duplicate of #2487.

**Comment by abodea** [comment] 2020-02-13 14:46
Thank you for adding this @twidi!
Thanks, @cadeyrn, closing as a duplicate of #2487.

**Closed by abodea** 2020-02-13 14:46 UTC
Labels: needs:triage, 🌟 feature request
