### ISSUE TITLE
FNX2-15615 ⁃ [Bug] Tab history vibrates in position very fast on swipe up /flick up

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13016] opened 2020-07-28 07:56 UTC
## Steps to reproduce
have enough tab history so that it fills at least 2 pages
open tab history with long back button click and position it so that it takes up the whole screen
flick up/ swipe up quickly

### Expected behavior
Tab history behaves normally and is scrolled up

### Actual behavior
Tab history is extremely janky and "vibrates" in position for a while and finally scrolls up later. It vibrates fast enough that it is difficult to catch on screen recording

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by person808** [comment] 2020-07-28 16:26
Hm I wonder if https://github.com/mozilla-mobile/fenix/issues/12887 is related (leaving a note for myself). We definitely need to be more efficient when binding the list items.

**Comment by person808** [comment] 2020-08-03 18:00
I tried reproducing on my Pixel 2 XL by opening a bunch of different websites in the same tab, but I didn't notice anything visually wrong. We recently landed some small performance improvements for tab history. Do you still see this on the latest nightly @s-ankur?

**Comment by person808** [comment] 2020-08-03 18:24
Ah I see it now, it is hard to notice sometimes. https://streamable.com/m0ye2y. You can see that the highlight on cheese.com jumps around. It almost looks like we're scrolling through the same items until we finally catch up and scroll through the rest of the tab history. In fact, if I put my finger down to stop the scroll at the right moment, its as if we didn't scroll at all (I'm still near the top of the tab history list)

**Comment by s-ankur** [comment] 2020-08-03 18:31
@person808 correct, and I can reproduce on latest nightly as well

**Comment by sv-ohorvath** [comment] 2020-08-12 09:14
Verified as fixed on 80.0.0-beta6 on several devices:
Samsung Galaxy Tab S6 (Android 9), Sony Xperia Z5 Premium (Android 7.1.1), Motorola Moto G6 (Android 8), OnePlus A3 (Android 6.0.1), Google Pixel 3a (Android 10) and Huawei Mate 20 Lite (Android 10)

**Closed** 2020-08-12 09:16 UTC
Labels: Feature:Browsing, Feature:History, sourpatch, sourpatch2, 🐞 bug
