### ISSUE TITLE
[Bug]: Press fullscreen on youtube in vertical screen goes to full screen mode with a white line on the bottom

### ISSUE THREAD

**Issue by zhenggu** [mozilla-mobile/fenix#21727] opened 2021-10-06 02:13 UTC
### Steps to reproduce

1. Access youtube.com from firefox, and click a video
2. Change to vertical screen on your phone
3. Press full screen from the video

### Expected behaviour

The full screen should be the same as press fullscreen button in horizontal screen: 
no status bar on the top and white line on the bottom
![horizontal](https://user-images.githubusercontent.com/14901481/136129593-f238ea64-bfad-436d-a064-0cdf86fba909.jpeg)

### Actual behaviour

Full screen with status bar on the top and white line on the bottom
![vertical](https://user-images.githubusercontent.com/14901481/136129675-0ce61bfe-0057-41f5-ad62-0b9a4a6a0c98.jpeg)

### Device name

Xiaomi 10

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

92.1.1

**Comment by zhenggu** [comment] 2021-10-10 12:00
The interesting thing is that when I upgrade my Mi 10 to android 11, the issue has gone. Is there any compatible issue with the lower API?

**Comment by LaurentiuApahideanSV** [comment] 2021-11-02 14:17
I tried to reproduce the issue on Firefox Preview Nightly 2021-11-02, but was unable to. @zhenggu Can you confirm the issue is fixed after the firmware update?
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by sflorean** [comment] 2022-05-05 12:52
Closing this based on the comments above.

**Closed by sflorean** 2022-05-05 12:52 UTC
Labels: 🐞 bug, needs:triage, wontfix, qa-triaged
