### ISSUE TITLE
[Bug] Compressed recent tabs

### ISSUE THREAD

**Issue by J41319** [mozilla-mobile/fenix#20151] opened 2021-06-24 01:21 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Just open tabs and switch between pinned and recent tabs

### Expected behavior

Recent tabs should not be compressed

### Actual behavior

Recent tabs are compressed

### Device information

* Device vendor / model and Android version: Xiaomi Mi A3 - Android 11
* Firefox for Android version: 89.1.1

https://user-images.githubusercontent.com/50890947/123187799-3590b100-d471-11eb-931e-c92fbb2aa56a.mp4

https://user-images.githubusercontent.com/50890947/123187811-3cb7bf00-d471-11eb-869c-65b1007f4aa3.mp4

**Comment by SoftVision-LorandJanos** [comment] 2021-06-24 14:07
Hi @J41319 ! Thank you for your report! As I remember, there was a similar issue before, I can't however find it here. I am unable to reproduce it. I've tried on 3 devices (I don't have Xiaomi), one with Android 11 included. And beside the build you logged the issue with, I also tried with the latest Nightly, and while I've tried to do as close as possible to how I saw on your videos, it was without success, so if you have any extra info regarding, maybe a step or a setup that might be important, please share. Maybe check if it reproduces after a clear data, or see if it reproduces on the latest Nightly.
Tested on the latest Release 89.1.1 and latest Nightly (91.0a1 2021-06-24T05:07:09.024).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Comment by J41319** [comment] 2021-06-24 15:32
> 
> 
> Hi @J41319 ! Thank you for your report! As I remember, there was a similar issue before, I can't however find it here. I am unable to reproduce it. I've tried on 3 devices (I don't have Xiaomi), one with Android 11 included. And beside the build you logged the issue with, I also tried with the latest Nightly, and while I've tried to do as close as possible to how I saw on your videos, it was without success, so if you have any extra info regarding, maybe a step or a setup that might be important, please share. Maybe check if it reproduces after a clear data, or see if it reproduces on the latest Nightly.
> Tested on the latest Release 89.1.1 and latest Nightly (91.0a1 2021-06-24T05:07:09.024).
> Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

I did the same thing last beta and nightly versions and the problem doesn't happen, apparently the problem is happening in the last stable version. Sometimes it happens and sometimes it doesn't.

**Comment by kbrosnan** [comment] 2021-07-06 17:58
This sounds like it will be fixed in v90 according to the previous comment.

**Closed by kbrosnan** 2021-07-06 17:58 UTC
Labels: Feature:HomeScreen, S3, needs:triage, qa-triaged, 🐞 bug
