### ISSUE TITLE
[Bug] New search experience is overlaid on "Allow search suggestions in private sessions?"

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14342] opened 2020-08-28 05:55 UTC
## Steps to reproduce

1. Enable new search experience 
2. enter private browsing 
3. type anything

### Expected behavior

nothing is overlaid on "Allow search suggestions in private sessions?"

### Actual behavior

![signal-2020-08-28-015330](https://user-images.githubusercontent.com/152493/91526471-b0308480-e8d1-11ea-937e-8494ba15b729.png)

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by s-ankur** [comment] 2020-08-28 07:28
Duplicate of https://github.com/mozilla-mobile/fenix/issues/14283

**Comment by Diana-Rus** [comment] 2020-08-28 12:25
Closing issue as dupe of #14283 , thank you @s-ankur !

**Closed by Diana-Rus** 2020-08-28 12:25 UTC
Labels: needs:triage, 🐞 bug
