### ISSUE TITLE
[Bug] Two instances of firefox shown in app switcher instead of one

### ISSUE THREAD

**Issue by payton-quinn** [mozilla-mobile/fenix#15361] opened 2020-09-23 21:34 UTC
## Steps to reproduce

Open app
Swipe up to bring up the app switcher
View two firefox instances instead of one.

### Expected behavior

One instance of firefox shown in the app switcher.

### Actual behavior

Two instances of firefox shown in the app switcher

### Device information

* Android device: Pixel 3XL, Android 11
* Fenix version: 81.1.1 (Build #2015764547)

**Comment by payton-quinn** [comment] 2020-09-23 21:37
![ezgif-7-72352b2edaf2](https://user-images.githubusercontent.com/59527089/94072307-47daa300-fdaa-11ea-981f-915ff815c1a2.gif)

**Comment by ekager** [comment] 2020-09-23 21:51
closing as dupe of #15044

**Closed by ekager** 2020-09-23 21:51 UTC
Labels: needs:triage, 🐞 bug
