### ISSUE TITLE
[Bug]: push notification stopped working

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#25824] opened 2022-06-30 05:30 UTC
### Steps to reproduce

since yesterday push notification for both nightly and stable fenix stopped working ,log cat show this error :
mozilla.appservices.push.PushException$CommunicationException: Communication Error: "Unhandled client error Response { request_method: Put, url: Url { scheme: \"https\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"updates.push.services.mozilla.com\")), port: None, path: \"/v1/fcm/firefox-8dc06/registration/4dcc2512-1664-4e13-ab50-cd97af251b13\", query: None, fragment: None }, status: 410, headers: Headers { headers: [Header { name: HeaderName(\"access-control-expose-headers\"), value: \"\" }, Header { name: HeaderName(\"date\"), value: \"30 Jun 2022 05:26:45 GMT\" }, Header { name: HeaderName(\"connection\"), value: \"keep-alive\" }, Header { name: HeaderName(\"content-type\"), value: \"application/json\" }, Header { name: HeaderName(\"access-control-allow-methods\"), value: \"DELETE\" }, Header { name: HeaderName(\"content-length\"), value: \"175\" }, Header { name: HeaderName(\"cache-control\"), value: \"max-age=86400\" }, Header { name: HeaderName(\"access-control-allow-origin\"), value: \"*\" }, Header { name: HeaderName(\"access-control-allow-headers\"), value: \"\" }, Header { name: HeaderName(\"server\"), value: \"nginx\" }, Header { name: HeaderName(\"strict-transport-security\"), value: \"max-age=31536000;includeSubDomains\" }] }, body: [123, 34, 99, 111, 100, 101, 34, 58, 32, 52, 49, 48, 44, 32, 34, 101, 114, 114, 110, 111, 34, 58, 32, 49, 48, 53, 44, 32, 34, 101, 114, 114, 111, 114, 34, 58, 32, 34, 34, 44, 32, 34, 109, 111, 114, 101, 95, 105, 110, 102, 111, 34, 58, 32, 34, 104, 116, 116, 112, 58, 47, 47, 97, 117, 116, 111, 112, 117, 115, 104, 46, 114, 101, 97, 100, 116, 104, 101, 100, 111, 99, 115, 46, 105, 111, 47, 101, 110, 47, 108, 97, 116, 101, 115, 116, 47, 104, 116, 116, 112, 46, 104, 116, 109, 108, 35, 101, 114, 114, 111, 114, 45, 99, 111, 100, 101, 115, 34, 44, 32, 34, 109, 101, 115, 115, 97, 103, 101, 34, 58, 32, 34, 82, 101, 113, 117, 101, 115, 116, 32, 100, 105, 100, 32, 110, 111, 116, 32, 118, 97, 108, 105, 100, 97, 116, 101, 32, 73, 110, 118, 97, 108, 105, 100, 32, 83, 101, 110, 100, 101, 114, 73, 68, 34, 125] }"
is this some kind of mozilla server issue ?

### Expected behaviour

Fenix should not be so damn frustrating to use 

### Actual behaviour

push notification are not working 

### Device name

poco f3

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

104

### Device logs

mozilla.appservices.push.PushException$CommunicationException: Communication Error: "Unhandled client error Response { request_method: Put, url: Url { scheme: \"https\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"updates.push.services.mozilla.com\")), port: None, path: \"/v1/fcm/firefox-8dc06/registration/4dcc2512-1664-4e13-ab50-cd97af251b13\", query: None, fragment: None }, status: 410, headers: Headers { headers: [Header { name: HeaderName(\"access-control-expose-headers\"), value: \"\" }, Header { name: HeaderName(\"date\"), value: \"30 Jun 2022 05:26:45 GMT\" }, Header { name: HeaderName(\"connection\"), value: \"keep-alive\" }, Header { name: HeaderName(\"content-type\"), value: \"application/json\" }, Header { name: HeaderName(\"access-control-allow-methods\"), value: \"DELETE\" }, Header { name: HeaderName(\"content-length\"), value: \"175\" }, Header { name: HeaderName(\"cache-control\"), value: \"max-age=86400\" }, Header { name: HeaderName(\"access-control-allow-origin\"), value: \"*\" }, Header { name: HeaderName(\"access-control-allow-headers\"), value: \"\" }, Header { name: HeaderName(\"server\"), value: \"nginx\" }, Header { name: HeaderName(\"strict-transport-security\"), value: \"max-age=31536000;includeSubDomains\" }] }, body: [123, 34, 99, 111, 100, 101, 34, 58, 32, 52, 49, 48, 44, 32, 34, 101, 114, 114, 110, 111, 34, 58, 32, 49, 48, 53, 44, 32, 34, 101, 114, 114, 111, 114, 34, 58, 32, 34, 34, 44, 32, 34, 109, 111, 114, 101, 95, 105, 110, 102, 111, 34, 58, 32, 34, 104, 116, 116, 112, 58, 47, 47, 97, 117, 116, 111, 112, 117, 115, 104, 46, 114, 101, 97, 100, 116, 104, 101, 100, 111, 99, 115, 46, 105, 111, 47, 101, 110, 47, 108, 97, 116, 101, 115, 116, 47, 104, 116, 116, 112, 46, 104, 116, 109, 108, 35, 101, 114, 114, 111, 114, 45, 99, 111, 100, 101, 115, 34, 44, 32, 34, 109, 101, 115, 115, 97, 103, 101, 34, 58, 32, 34, 82, 101, 113, 117, 101, 115, 116, 32, 100, 105, 100, 32, 110, 111, 116, 32, 118, 97, 108, 105, 100, 97, 116, 101, 32, 73, 110, 118, 97, 108, 105, 100, 32, 83, 101, 110, 100, 101, 114, 73, 68, 34, 125] }"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20860)

**Comment by AdinaPetridean** [comment] 2022-07-05 14:05
@ale82to  thank you for your report! I was able to reproduce the issue on latest Nightly  - 104.0a1 - 7/5 with motorola moto g(9) plus (Android 11).
I will close this as a duplicate of [#23594](https://github.com/mozilla-mobile/fenix/issues/23594), please follow the discussion there.

**Closed** 2022-07-06 12:03 UTC
Labels: 🐞 bug, S3, needs:triage, Feature:Notifications, qa-triaged

**Comment by sledges** [comment] 2022-08-24 17:31
> body: [123, 34, 99, 111, 100, 101, 34, 58, 32, 52, 49, 48, 44, 32, 34, 101, 114, 114, 110, 111, 34, 58, 32, 49, 48, 53, 44, 32, 34, 101, 114, 114, 111, 114, 34, 58, 32, 34, 34, 44, 32, 34, 109, 111, 114, 101, 95, 105, 110, 102, 111, 34, 58, 32, 34, 104, 116, 116, 112, 58, 47, 47, 97, 117, 116, 111, 112, 117, 115, 104, 46, 114, 101, 97, 100, 116, 104, 101, 100, 111, 99, 115, 46, 105, 111, 47, 101, 110, 47, 108, 97, 116, 101, 115, 116, 47, 104, 116, 116, 112, 46, 104, 116, 109, 108, 35, 101, 114, 114, 111, 114, 45, 99, 111, 100, 101, 115, 34, 44, 32, 34, 109, 101, 115, 115, 97, 103, 101, 34, 58, 32, 34, 82, 101, 113, 117, 101, 115, 116, 32, 100, 105, 100, 32, 110, 111, 116, 32, 118, 97, 108, 105, 100, 97, 116, 101, 32, 73, 110, 118, 97, 108, 105, 100, 32, 83, 101, 110, 100, 101, 114, 73, 68, 34, 125]

This translates to `{"code": 410, "errno": 105, "error": "", "more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes", "message": "Request did not validate Invalid SenderID"}`. I hope this gives more insights.
