### ISSUE TITLE
[Bug] Website header gets detached

### ISSUE THREAD

**Issue by guilhermehrt** [mozilla-mobile/fenix#13205] opened 2020-08-02 02:30 UTC
## Steps to reproduce
1. Open any website that has a pinned header
2. When you're not at the top of the page, scroll up

### Expected behavior
Nothing happens

### Actual behavior
The header gets detached [Printscreen](http://imgur.com/gallery/J1AQV5I)

### Device information

* Android device: Samsung Galaxy Tab A
* Fenix version: Nightly 200801 06:06 (Build #22140615)

**Comment by s-ankur** [comment] 2020-08-02 09:06
Duplicate of #10598

**Closed** 2020-08-08 00:31 UTC
Labels: needs:triage, 🐞 bug
