### ISSUE TITLE
[Bug] New tabs do not close automatically after pressing the back button.

### ISSUE THREAD

**Issue by cbwee** [mozilla-mobile/fenix#18378] opened 2021-03-08 22:59 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Search anything in the address bar.
2. Open a few search results with "Open link in new tab"
3. Go to one of the results (new tabs) opened.
4. Press the back button in Android's navigation bar.
5. The new tab is closed automatically.
6. Close the tab that shows the search results in step 2.
7. Now go to any of the new tabs opened in step 2.
8. Press the back button.
9. The tab only becomes blank, but it is not closed automatically.

### Expected behavior
New tabs opened with the option "Open link in new tab", should close automatically after pressing the back button.

### Actual behavior
When the original search results page is closed, they only become blank, and do not close.

### Device information
* Device vendor / model and Android version: POCO M3 (Xiaomi M2010J19CG) / Android 10
* Firefox for Android version: Nightly 210308 17:04 (Build #2015797515)

**Comment by kbrosnan** [comment] 2021-03-09 00:12
Duplicate of #17204

**Closed by kbrosnan** 2021-03-09 00:12 UTC
Labels: needs:triage, 🐞 bug
