### ISSUE TITLE
[Bug]: URL history suggestions somehow disappear until restart

### ISSUE THREAD

**Issue by ohhai** [mozilla-mobile/fenix#20523] opened 2021-07-26 21:36 UTC
### Steps to reproduce

1. Restart Firefox: swipe it away from apps list and open again.
2. Start it. Enter address part of any previously visited site in URL bar and ensure that it will be present in history suggestion dropdown list.
3. Use browser for some time, open and close tabs.
4. Enter same address part in URL bar

### Expected behaviour

Same history suggestions (as in 2.) shall be shown.

### Actual behaviour

No any results from history are shown.

### Device name

LG V20

### Android version

8.0.0

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

### Additional information

Version:
92.0a1 (Build #2015824203)
AC: 92.0.20210722190406, b360a589a0
GV: 92.0a1-20210722094752
AS: 81.0.1
2021-07-25T17:07:47.511

**Comment by marcel263** [comment] 2021-07-26 23:21
Hello, I can reproducre the issue, it seems to be a duplicate of #20351

**Comment by ohhai** [comment] 2021-07-26 23:26
Thanks! I did search by "history", so missed it.

**Comment by SoftVision-LorandJanos** [comment] 2021-08-02 10:44
Hi @ohhai ! Thank you for your report!
I didn't manage to reproduce the issue you described, however the issue is covered in #20351 as mentioned above, where you can see the details of how I tried to reproduce it.
If you have any extra details about the conditions that this issue can be reproduced, please mention them in a comment for that bug. I will close this one as duplicate. Thank you!

**Closed by SoftVision-LorandJanos** 2021-08-02 10:44 UTC
Labels: needs:triage, 🐞 bug
