### ISSUE TITLE
[Bug] After exiting fullscreen, the address bar overlaps with the phone notification area

### ISSUE THREAD

**Issue by ra-hardy** [mozilla-mobile/fenix#18750] opened 2021-04-01 15:37 UTC
## Steps to reproduce
1. Go to https://www.robdev.org.uk/london_webcam/
2. Click the fullscreen icon on one of the videos
3. Exit fullscreen

### Expected behavior
The address bar should be below the notification area after exiting fullscreen

### Actual behavior
The adderss bar overlaps with the notification area. See screenshot

### Device information
* Samsung Galaxy S10
* Firefox for Android 88.0.0-beta.2 build #2015801419
* Android 11 One UI 3.1

![Screenshot_20210401-162510_Firefox Beta](https://user-images.githubusercontent.com/12749172/113318486-6e086f00-9308-11eb-9596-864ec29c1aa8.jpg)

**Comment by Mugurell** [comment] 2021-04-02 06:15
Thank you @ra-hardy !
This will be fixed in the next update.
Closing as a dupe of https://github.com/mozilla-mobile/fenix/issues/18667.

**Closed by Mugurell** 2021-04-02 06:15 UTC
Labels: needs:triage, 🐞 bug
