### ISSUE TITLE
Import bookmarks from an html file

### ISSUE THREAD

**Issue by Someone-G** [mozilla-mobile/fenix#27945] opened 2022-11-22 11:25 UTC
Hello. Please add the ability to import (and export) bookmarks from an html file from the internal memory of the device. Thank you.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22030)

**Comment by cadeyrn** [comment] 2022-11-22 12:01
Duplicate of #417.

**Closed** 2022-11-22 15:56 UTC
Labels: needs:triage
