### ISSUE TITLE
[Bug] overflow menu doesn't change position when rotating the screen

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3390] opened 2019-06-12 15:57 UTC
As originally found in [this comment](https://github.com/mozilla-mobile/fenix/issues/986#issuecomment-501261223), when rotating the display while a menu is inflated, we will clip the menu (requiring the user to scroll). 

Some discussion with @Amejia481 revealed that the menu does not get a `redraw` call and thus we can't just re-inflate it upwards/downards as appropriate. One possible solution is to just dismiss the menu on rotation (this is what Chrome does).

Either way, this is likely low priority.

<img width=400 src=https://user-images.githubusercontent.com/40694158/59352830-48bd0200-8d2a-11e9-8afb-def446fc29c6.gif>

**Comment by s-ankur** [comment] 2020-05-04 18:39
No longer seems to be an issue

**Comment by sv-sdeiac** [comment] 2020-05-05 06:00
Hi, this issue is still reproducible if you set the toolbar to "Top" in settings ->Customize. 

Build:
- Firefox Preview Nightly 5/4 #21251804.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG G7 fit (Android 8.1).

### Notes
- It seems that this issue is not reproducible if the toolbar is set to the bottom.

**Comment by lobontiumira** [comment] 2021-05-28 13:17
This is no longer a valid issue, since the homescreen has a different layout on the 5/28 Nightly build.
I'll close this issue.

**Closed by lobontiumira** 2021-05-28 13:17 UTC
Labels: Feature:MainMenu, P5, S3, b:landscape, 🐞 bug
