### ISSUE TITLE
[Bug] "null Downloads failed" notification, when you have some failed downloads and you swipe away the last notification

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#14970] opened 2020-09-11 01:34 UTC
## Steps to reproduce
1. Follow STR for  #14790, with several failed downloads.
2. Swipe away all of the notifications for the individual failed downloads.

### Expected behavior
"null" shouldn't be shown as a string

### Actual behavior
The system tray grouping section briefly says "null Download failed", before disappearing altogether.

### Device information

* Android device: Pixel 3, running Android 10 and 11 (recently upgraded from 10 to 11, and I've noticed this issue with both)
* Fenix version: Nightly 200910 06:07 (installed from play store, latest version currently available)

Screenshot showing the "null Downloads failed" notification:
![screenshot](https://user-images.githubusercontent.com/426803/92838964-449bec00-f394-11ea-82d1-0dc0e6c44024.png)

**Comment by dholbert** [comment] 2020-09-11 01:37
screencast: https://www.dropbox.com/s/qnr1nxrytdu8k4e/null-download-failed.mp4?dl=0

(The issue is visible at approximately 0:05 in the screencast.)

**Comment by hwinnemoe** [comment] 2020-09-11 11:04
Related to/Duplicate of #13798

**Closed** 2020-09-16 16:33 UTC
Labels: Feature:Download, needs:triage, 🐞 bug
