### ISSUE TITLE
FNX2-15342 ⁃ Allow removing apps from recent apps list on share sheet

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#12587] opened 2020-07-15 09:25 UTC
Initially posted here: https://github.com/mozilla-mobile/fenix/issues/9332#issuecomment-603136441.
See: https://github.com/mozilla-mobile/fenix/issues/9332#issuecomment-658627920.

**Comment by cadeyrn** [comment] 2020-07-15 09:28
Duplicate of #11566.

**Comment by kbrosnan** [comment] 2020-08-28 22:29
Closing as a duplicate.

**Closed by kbrosnan** 2020-08-28 22:29 UTC
Labels: Feature:ShareSheet, feature request 🌟, needs:triage
