### ISSUE TITLE
FNX-4369 ⁃ [Bug] İmage

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#10546] opened 2020-05-10 16:06 UTC
Images I downloaded in the browser do not appear in other applications

### Device information
Lenovo k6 Note

* Android device: ?
Android 9
* Fenix version: ?
Preview Lastest version

**Comment by SS1113** [comment] 2020-05-10 16:18
Duplicate of #8750

**Closed** 2020-08-11 01:00 UTC
Labels: needs:triage, 🐞 bug
