### ISSUE TITLE
FNX-12821 ⁃ [UX feedback] [new Tabs Tray] Make it not so easy to close the new Tabs Tray

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11836] opened 2020-06-23 06:28 UTC
Currently it is very easy to close the Tabs Tray accidentally while the tabs stack is being scrolled downwards when there are lots of tabs let's say 20 or 30 tabs. When there are these many tabs there are no indicators that will say that the user has reached the at the topmost scroll position and can't scroll down any more downwards vertically and ends up closing the Tabs Tray instead. This is really frustrating for the user as tabs navigation one of the very central features of a browser and the user is expected to use it extensively and if we make the user close the Tabs Tray every time the user scrolls downwards and reaches at the topmost position then the user will get frustrated and they will have to scroll down very cautiously for as to not close the tabs tray instead. 

Please the see the video (because I'm not sure if I'm using the correct term for up/downward direction). 

I'm suggesting to make it not so easy to close the Tabs Tray and add some visual indicators such as scroll bars and/or a scroll end effect (see the video) to indicate that the user has reached topmost/end scroll position and can't scroll down/up any further and also create some sort of blockage when the user has reached the to the topmost scroll position so that they don't unintentionally close the Tabs Tray instead.

GIF for Tabs Tray closing while I was scrolling to the top and unintentionally closed the Tabs Tray:

![20200623](https://user-images.githubusercontent.com/42088907/85368244-857c2580-b548-11ea-9087-3db71c05fc47.gif)UNITO-UNDERSCORE!114515!

Scroll end effect GIF:

![20200623](https://user-images.githubusercontent.com/42088907/85368251-8745e900-b548-11ea-814c-67b56a3edfc1.gif)UNITO-UNDERSCORE!113942!

**Comment by SS1113** [comment] 2020-06-23 06:37
CC @brampitoyo

**Comment by person808** [comment] 2020-06-23 17:00
Duplicate of #11042, should be fixed by #11842

**Comment by SS1113** [comment] 2020-06-24 02:51
@person808 Do you think a scroll bar can be added so users know where exactly their position in the in the tabs tray is? For example if they're in the middle, the end or the starting position of the tabs stack.

**Comment by person808** [comment] 2020-06-24 03:56
@SS1113 That sounds like good feedback and I don't think there's an issue for it yet. Feel free to open a new issue for that :)

**Comment by SS1113** [comment] 2020-06-24 04:11
@person808 Done! Here it is: https://github.com/mozilla-mobile/fenix/issues/11873

Thanks!

**Closed** 2020-08-11 05:03 UTC
Labels: Feature:Tabs
