### ISSUE TITLE
[Bug] Validating feedly logins doesn't redirect to app

### ISSUE THREAD

**Issue by Monakiel** [mozilla-mobile/fenix#8010] opened 2020-01-31 02:21 UTC
## Steps to reproduce
1)From Feedly Application, connect with feedly login

2)They redirect to a webpage like [This link](https://feedly.com/v3/auth/login?state=A6zQQ4uA-3OvIHlVvE6V3zwAfQmWwrXcqcM2udA9kNtWvwzVDREtOO6yglN4CNYtojM3UIFJqjJd4vrPIZxom2IoJGM1wynNXDWBiTy1y0yxzVfzRBSIVb9PgdFVEO3Bi7s963SR-uQ7D-wMt_B6MX6TjHfJQ0oQ_yAQ2XP9zNbm8UnH1Urdsl0Vv4KSy2CaZzi1Fg) 

3)entered credentials then validate login

### Expected behavior
After pressing on validate, redirects in the mobile app and log correctly. 

### Actual behavior
Nothing happens after pressing on validate. 

### Device information
* Android device: Xiaomi Mi 9T Pro android 10
* Fenix version: 3.0.2 (Build #20081833)
📦: 24.0.1, ee4587f74
🦎: 71.0.1-20200108003105

**Comment by kbrosnan** [comment] 2020-02-14 23:23
Sounds like a dupe of #7331. Do you get an unknown protocol error?

**Comment by aitorpazos** [comment] 2020-06-18 15:22
Looks duplicate of #7691

**Comment by kbrosnan** [comment] 2020-11-09 18:21
This should be resolved

**Closed by kbrosnan** 2020-11-09 18:21 UTC
Labels: Feature:OpenInApp, needs:triage, 🐞 bug
