### ISSUE TITLE
[Bug] Keyboard doesn't always popup on text box focus

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#14249] opened 2020-08-26 21:58 UTC
## Steps to reproduce
Click on a text box. I'm not sure exactly what triggers it but I've come across it mostly on github using the search or comment section.

### Expected behavior
The keyboard pops up.

### Actual behavior
Nothing happens. Reloading the page doesn't help, you have to open the page again in a new tab to get it working.

### Device information

* Android device: Huawei Nova 6 (Android 10)
* Fenix version: Nightly 200826 06:01 (Build #2015760179)
AC: 56.0.20200825130329, 6fbe53de9
GV: 81.0a1-20200820093209
AS: 61.0.12

**Comment by mobd** [comment] 2020-08-26 22:16
I seem to be able to reliably reproduce it now:
- Open a page with a text box in a regular tab.
- Open a private tab and switch to it.
- Switch back to the regular tab.
After that I can't get my keyboard to popup at all. However, other tabs that I may have had open still work fine, it only happens if I directly switch to a tab from a private tab.

**Comment by miDeb** [comment] 2020-08-27 06:08
Duplicate of https://github.com/mozilla-mobile/fenix/issues/12982

**Closed** 2020-08-27 11:55 UTC
Labels: needs:triage, 🐞 bug
