### ISSUE TITLE
Crash in [@ java.lang.RuntimeException: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java)]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#14852] opened 2020-09-08 15:15 UTC
Similar to https://github.com/mozilla-mobile/fenix/issues/6436

Crash report: https://crash-stats.mozilla.org/report/index/394f182b-8987-4fa1-b8b6-8190a0200908
Sentry: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9509776/?query=is%3Aunresolved (looks like started Sept 1)

Java stack trace:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	... 1 more
Caused by: mozilla.components.lib.state.StoreException: Exception while reducing state
	at mozilla.components.lib.state.Store$$special$$inlined$CoroutineExceptionHandler$1$lambda$1.run(Store.kt:1)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7073)
	... 3 more
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.mozilla.firefox_beta/org.mozilla.fenix.downloads.DownloadService (has extras) }: app is in background uid UidRecord{ba745a5 u0a1159 CEM  idle change:cached procs:1 proclist:17880, seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1666)
	at android.app.ContextImpl.startService(ContextImpl.java:1611)
	at android.content.ContextWrapper.startService(ContextWrapper.java:677)
	at mozilla.components.feature.downloads.DownloadMiddleware.sendDownloadIntent(DownloadMiddleware.kt:4)
	at mozilla.components.feature.downloads.DownloadMiddleware.invoke(DownloadMiddleware.kt:17)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$$inlined$forEach$lambda$1.invoke(ReducerChainBuilder.kt:3)
	at mozilla.components.feature.media.middleware.MediaMiddleware.invoke(MediaMiddleware.kt:39)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$$inlined$forEach$lambda$1.invoke(ReducerChainBuilder.kt:3)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$threadCheck$1.invoke(ReducerChainBuilder.kt:4)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$$inlined$forEach$lambda$1.invoke(ReducerChainBuilder.kt:3)
	at mozilla.components.lib.state.Store$dispatch$1.invokeSuspend(Store.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by liuche** [comment] 2020-09-08 16:14
Looks Downloads related, @Amejia481 or @kglazko could you coordinate/take a look? If this is in Nightly, it may be in Beta too so if it's a problem we'll want to uplift this fix.

**Comment by Amejia481** [comment] 2020-09-08 16:16
I will take a look

**Comment by kbrosnan** [comment] 2020-09-08 17:02
This is the top crash in Beta so yes this needs an 81 fix.

**Comment by Amejia481** [comment] 2020-09-09 15:13
This will be addressed when https://github.com/mozilla-mobile/android-components/pull/8364 lands and Fenix picks the new ac version.

**Comment by dholbert** [comment] 2020-09-10 18:43
I'm hitting this reliably several times per day, FWIW; I'll glance at my phone and notice a notification telling me "Sorry, Firefox Nightly had a problem and crashed".  Logcat shows "ActivityManager: Background start not allowed: service Intent { cmp=org.mozilla.fenix/.downloads.DownloadService (has extras) } to org.mozilla.fenix/.downloads.DownloadService" which is what brought me to this issue here.

Looks like the Play Store has a update for Nightly available for me right now. Not sure if it has the fix mentioned above yet (I'm guessing yes since it was merged 23 hours ago).  In any case, I can report back regarding whether this seems fixed or not.

**Comment by sv-ohorvath** [comment] 2020-09-11 11:22
@Amejia481 @liuche is this supposed to be uplifted to 81.1.1.beta3 now? If so, do we have any STR for QA? Thanks!

**Comment by Amejia481** [comment] 2020-09-11 13:15
@sv-ohorvath I think it's already uplifted, for the steps to reproduce @dholbert could help us as he was hitting issue. I wasn't able to replicate it on my own.

**Comment by sv-ohorvath** [comment] 2020-09-11 14:26
I see this notification on Beta, I don't have STR, I just noticed it there, may it be something related?: 
![Screenshot_20200911-172219](https://user-images.githubusercontent.com/4037709/92937346-e6ced900-f453-11ea-9018-09697a48abf3.png)

**Comment by Amejia481** [comment] 2020-09-11 14:40
I think this is another issue https://github.com/mozilla-mobile/fenix/issues/14970. I'm not aware of the exact STR, but I think it was related to restarting the downloads. Some steps close to the STR could be downloading a file and completing the download, then kill the app and restart. There I think it was when the app was crashing, we could try with the devices where the crash was more prevalent, Android 9 and 10 you can see the specific brands and models [here](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9509776/events/).

**Comment by Amejia481** [comment] 2020-09-11 14:51
Another thing that can give us a hint, if the issue was fixed, it's the patch that fixed the issue was introduced on ac `58.0.20200910190642` **(2020-09-10)**. So far I haven't seen any occurrence on [sentry](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9509776/?query=is%3Aunresolved) for that ac version or above.

**Comment by dholbert** [comment] 2020-09-11 15:50
I haven't hit the crash since my comment yesterday (when I installed the update).  Previously I was seeing this several times per day, so I'd call this confirmation that this is fixed.

(Regarding the STR: I think it was something like: start fenix, then switch apps, then wait for a little while.)

**Comment by sv-ohorvath** [comment] 2020-09-14 13:23
We didn't encounter this while testing this beta build either, so I'll close this issue. Thanks @dholbert for confirming!

**Closed by sv-ohorvath** 2020-09-14 13:23 UTC
Labels: Feature:Download, b:crash
