### ISSUE TITLE
[Bug] Crashes while logging in to Google or GitHub

### ISSUE THREAD

**Issue by djc** [mozilla-mobile/fenix#7691] opened 2020-01-14 19:05 UTC
## Steps to reproduce

1. Login to GitHub (for example, for an OAuth authorization) or Google (for example, to install a Play Store app)

### Expected behavior

1. Login proceeds as usual

### Actual behavior

Firefox crashes on each attempt. After reopening Firefox, something seems stuck with that origin and it's showing a broken lock even though the URL has a https scheme.

### Device information

I've started noticing this for the first time a few days ago, and it's happened a few times since then.

* Android device: Pixel 2
* Fenix version: latest Nightly

**Comment by djc** [comment] 2020-01-14 21:20
The latest instance involved logging in to GitHub's new Android app, which I vol es the Oauth authorization flow. I think it was maybe trying to redirect back to the app after authorization? In any case, I managed to make it work after temporarily setting my default browser to Fennec Nightly.

**Comment by childnode** [comment] 2020-01-21 06:31
@djc [can confirm](https://github.com/webcompat/web-bugs/issues/47723) that custom scheme ends up in 

fenix is not "OAuth for native apps" https://tools.ietf.org/html/rfc8252 compatible at this time!

**Comment by ricvelozo** [comment] 2020-03-19 01:18
Tried to login in GitHub app today, and I got a "unsupported protocol" error in Fenix. Opening the OAuth link in Fennec worked.

**Comment by kbrosnan** [comment] 2020-07-27 23:48
Duplicate of https://github.com/mozilla-mobile/android-components/issues/5555

**Closed by kbrosnan** 2020-07-27 23:48 UTC
Labels: Feature:OpenInApp, b:crash, 🐞 bug
