### ISSUE TITLE
[Bug]: rendering broken in 94.1.2

### ISSUE THREAD

**Issue by shiroyagi** [mozilla-mobile/fenix#22435] opened 2021-11-13 17:44 UTC
### Steps to reproduce

1. go to a website eg. en.wikipedia.org
2. scroll down the page

### Expected behaviour

Text and images should be legible

### Actual behaviour

Some images are corrupted or not drawn.  Some text is replaced with incorrect characters (some not ASCII), sometimes overlapping.  Scrolling backwards and forwards will change which text and images are rendered correctly, so after a while it may be possible to read the whole page.

### Device name

Motorola Moto X

### Android version

Android 5.1

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

The same behaviour applies to Fennec 94.1.1.  The previous release of Firefox and Fennec 93.1.0 work correctly.

**Comment by shiroyagi** [comment] 2021-11-13 17:52
See below:

![Screenshot_2021-11-13-17-46-32](https://user-images.githubusercontent.com/8389325/141653947-9c6e7127-2fcd-4a5b-889f-d11f2d4d6185.png)

![Screenshot_2021-11-13-17-46-22](https://user-images.githubusercontent.com/8389325/141653953-6a450f29-b290-4db5-a42d-a36b82f2d0bb.png)

**Comment by Mugurell** [comment] 2021-11-15 13:04
This seems to be device specific.
Can you please try newer versions of Firefox, like the current Nightly or Beta and test if that is still affected? 

cc @jamienicol

**Comment by shiroyagi** [comment] 2021-11-15 13:31
Yes, same problem with nightly 96.0a1.  Note you may have to scroll back and forth a few times to replicate the problem.  Sometimes I see it almost immediately and nearly everywhere, other times not so much.

**Comment by Mugurell** [comment] 2021-11-15 13:55
Moving to Bugzilla for more investigation from the graphics team.
Please follow the progress there.

**Comment by Mugurell** [comment] 2021-11-15 13:55
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1741174

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by Mugurell** 2021-11-15 13:55 UTC
Labels: 🐞 bug, needs:triage

**Comment by jamienicol** [comment] 2021-11-15 14:13
@shiroyagi thank you for the bug report. Could you please go to about:support, click "copy text to clipboard", and attach the text to this bug?

Since you say this is a regression in version 94, it would be incredibly helpful if you could run the program [mozregression](https://mozilla.github.io/mozregression/install.html). You can either install the GUI version from the link there, or if you are running Linux or Macos I find it's easier to use the command line:

```
pip install --user mozregression
```

Then plug your phone in to the computer and make sure USB debugging is enabled. Open the mozregression application and click the scissor icon to start a new bisection. On the first screen, select `gve` from the "application" drop down menu then click next. Then click "next" again to skip the profile selection screen, then on the "build selection" screen change the "date" dropdown menus to say "release", and and select 93 as "good" and 94 as "bad". Then click "finish".

Alternatively, if using the command line just run

```
mozregression --app gve --good 93 --bad 94
```

This will download and run a series of versions of firefox. For each one, see if you are affected by the bug, then enter either "good" or "bad". Eventually this will tell you what change to the code caused the bug.

I know that's a bit complicated, sorry. But it will be incredibly helpful to us! Please let me know if you need any help with that!

**Comment by shiroyagi** [comment] 2021-11-15 14:47
This is from my usual install.  A fresh install of nightly (no extensions etc) gave the same result:
[support.txt](https://github.com/mozilla-mobile/fenix/files/7539382/support.txt)
I will try the bisection later.  Should I comment here or #1741174 in future?

**Comment by jamienicol** [comment] 2021-11-15 16:24
On bugzilla would be preferable, but here is fine too if that's easier for you

**Comment by jamienicol** [comment] 2021-11-15 19:22
Yes that's correct. But the result is a little bit surprising. Would you be able to try again just to confirm you get the same result? Thanks!

**Comment by shiroyagi** [comment] 2021-11-15 19:26
It took quite a long time as the number of builds jumped back up:
`17:05.00 INFO: ************* Switching to autoland by process of elimination (no branch detected in commit message)`

**Comment by jamienicol** [comment] 2021-11-15 19:32
Unfortunately no it can't detect that. However, if you notice that after a certain point all of your answers are the same (all good or all bad) then it is probable that you've gone wrong somewhere.

Do you still have the full log available or have you closed the window? If you still have the log then please post it

**Comment by shiroyagi** [comment] 2021-11-15 19:36
Yes
[mozregression.txt](https://github.com/mozilla-mobile/fenix/files/7541261/mozregression.txt)

**Comment by jamienicol** [comment] 2021-11-15 19:44
Thank you! It's my evening here now, but tomorrow I will create some builds for you to test to confirm.

**Comment by jamienicol** [comment] 2021-11-16 13:07
@shiroyagi could you please try these two builds and see if you can reproduce the bug in them:

1. https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Dt29Ax8cRMWqe7uibTA0PA/runs/0/artifacts/public/build/geckoview_example.apk
2. https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/XkYHya1yR_uuqVcGIBmL8Q/runs/0/artifacts/public/build/geckoview_example.apk

**Comment by shiroyagi** [comment] 2021-11-16 14:32
1. Dt29 does have the bug
2. XkYH does not have the bug

**Comment by jamienicol** [comment] 2021-11-19 18:32
Thanks for testing. That does confirm that your bisection was correct.

Would you be able to test whether setting `widget.non-native-theme.scrollbar.size.override` to `-1` in about:config fixed the issue?

**Comment by shiroyagi** [comment] 2021-11-19 19:51
Using the app above 1. Dt29 if I set widget.non-native-theme.scrollbar.size to -1 it seems to partly fix it.  Scrolling quickly I can see some of the text is sometimes corrupt as before, but as soon as scrolling stops it is quickly drawn correctly.

There is no widget.non-native-theme.scrollbar.size.override, adding it seems to have the same effect.

2. XkYH appears to behave better than this: I can't see any corruption even with fast scrolling, although it does occasionally stutter.

I assume there is no way to use about:config in Firefox, although I notice it is still available in Fennec.

**Comment by jamienicol** [comment] 2021-11-22 10:32
@shiroyagi oh. I've just realized that `widget.non-native-theme.scrollbar.size.override` was only very recently added (and widget.non-native-theme.scrollbar.size was removed). In those builds above the `override` version doesn't exist yet so should have no effect.

Dt29 is the first build with the new scrollbar rendering code. Setting the size to -1 helps, but does not fix it entirely.
XkYH is the last build with the old scrollbar rendering code. So is unaffected.

So it seems like a driver bug which is triggered by the new scrollbar rendering code.

Unfortunately there is no about:config on Firefox stable, but you can install Beta or Nightly from the play store and use it in those.

**Comment by shiroyagi** [comment] 2021-11-22 12:55
Thanks, probably my mistake was not to refresh the page after testing widget.non-native-theme.scrollbar.size=-1 and replacing it with widget.non-native-theme.scrollbar.size.override.

So if this is a driver bug, what will the resolution be?  Will there be a code change to, eg, detect this hardware/version or will it rely on users setting about:config?

FYI I have never seen similar behaviour in any other app.

**Comment by jamienicol** [comment] 2021-11-26 12:10
I'm trying to get my hands on a device which can reproduce the issue, and then I will find a workaround for it. Apologies for any inconvenience this has caused in the meantime.
