### ISSUE TITLE
[Bug] App stuck in landscape mode

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#15270] opened 2020-09-21 15:13 UTC
## Steps to reproduce

This is reported by a user and it also happened to me last week: "After watching several YouTube videos in full screen while landscape. After exiting full screen the browser is stuck in landscape mode. And to fix it I have to close the app (minimising it doesn't work)."

### Expected behavior

- After existing full screen, browser should exit landscape mode

### Actual behavior

- After existing full screen, browser gets stuck in landscape mode

### Device information

* Android device: ?
* Fenix version: 80.1.3

**Comment by ekager** [comment] 2021-01-06 04:17
Yesterday, the new media session API was turned on in https://github.com/mozilla-mobile/fenix/pull/17302. The orientation code seems to be improved there in the newer [`MediaSessionFullscreenFeature`](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/media/src/main/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeature.kt#L47) and it should return the user to their original orientation when fullscreen is exited.

**Comment by sflorean** [comment] 2021-01-08 10:31
Tested on Nightly 1/8 with Samsung Galaxy Note 10(Android 10) and couldn't reproduce the issue. Checked on Chrome also, and  the testing results are the same. The video exits landscape mode when it is ended, or when the device is opened (power button off/on). 
@ekager

**Comment by ekager** [comment] 2021-01-21 21:35
Great, thanks! Closing now

**Closed by ekager** 2021-01-21 21:35 UTC
Labels: Feature:Media, 🐞 bug
