### ISSUE TITLE
[Bug] Youtube does not completely go full screen

### ISSUE THREAD

**Issue by freebrowser1** [mozilla-mobile/fenix#14548] opened 2020-08-31 19:28 UTC
## Steps to reproduce
Select any video on Youtube and play it. Set the device in Landscape mode (which is much more convenient to play videos).
Click on the 'full screen' square symbol bottom right in the embedded video to make it full screen.

### Expected behavior
Video goes full screen

### Actual behavior
On the right is some white space and on the bottom also (but less) white space, it is not really full screen.

### Device information

* Android device: Oneplus 6
* Fenix version: 80beta (latest)

![Screenshot_20200831-212609](https://user-images.githubusercontent.com/26625141/91758834-e8390f80-ebd0-11ea-82e8-0de97e8d719d.jpg)

**Comment by kbrosnan** [comment] 2020-08-31 20:07
Duplicate of #8252

**Closed by kbrosnan** 2020-08-31 20:07 UTC
Labels: needs:triage, 🐞 bug
