### ISSUE TITLE
FNX-12555 ⁃ Add option to use Desktop mode for all sites by default

### ISSUE THREAD

**Issue by janot** [mozilla-mobile/fenix#11591] opened 2020-06-15 12:11 UTC
Quite annoying to enable it on every site manually, also I have to re-enable it after some time.
Desktop mode is often needed because lots of sites have crappy mobile versions.

Here's an example of how it's done in Kiwi Browser:
![Screenshot](https://user-images.githubusercontent.com/1689966/84655855-63681f00-af1a-11ea-8886-9065e21a5339.png)UNITO-UNDERSCORE!Kiwi!UNITO-UNDERSCORE!Browser!UNITO-UNDERSCORE!20200615-150254!
![Screenshot](https://user-images.githubusercontent.com/1689966/84655866-6a8f2d00-af1a-11ea-8e11-ec9c00141b7b.png)UNITO-UNDERSCORE!Kiwi!UNITO-UNDERSCORE!Browser!UNITO-UNDERSCORE!20200615-150301!

**Comment by cadeyrn** [comment] 2020-06-15 12:27
Duplicate of #7039.

**Comment by NotWoods** [comment] 2020-06-15 15:37
Closing as duplicate

**Closed** 2020-08-11 04:27 UTC
Labels: needs:triage
