### ISSUE TITLE
[Bug]: Firefox Android 96.3.0 crashes when I tap the address bar or when I open a new tab

### ISSUE THREAD

**Issue by skylinestar1986** [mozilla-mobile/fenix#23474] opened 2022-01-30 04:45 UTC
### Steps to reproduce

1. Tap the address bar

### Expected behaviour

Brings up my keyboard for me to type an address

### Actual behaviour

App closes itself

### Device name

Huawei Honor View20 PCT-L29

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

96.3.0

### Device logs

https://crash-stats.mozilla.org/report/index/df1fdbd3-c00a-42ec-9ef4-7440d0220128

**Comment by kbrosnan** [comment] 2022-01-31 19:48
Duplicate of https://github.com/mozilla-mobile/fenix/issues/22958

**Closed by kbrosnan** 2022-01-31 19:48 UTC
Labels: 🐞 bug, needs:triage

**Comment by Khyta** [comment] 2023-01-12 21:48
I noticed the same issue happening on my phone as well.

# Steps to reproduce

1. Open a new tab
2. Search for something
3. Wait a bit
4. Click on the address bar and try to open a new tab or search something

# Expected behavior
- Keyboard pop up and that it would let me type in a new address
- Browse my tabs

# Actual behavior
Watch firefox hang and an android popup appear, telling that Firefox isn't responding

# Device name
Pixel 6

# Android version
13

# Firefox release type
Firefox for Android

# Firefox Version
108.2.0 (Build #2015925643)

# Device logs
## Android logs
```
type: ANR
osVersion: google/oriole/oriole:13/TQ1A.230105.002/2023011000:user/release-keys
package: org.mozilla.firefox:2015925643
process: org.mozilla.firefox

activity: org.mozilla.firefox/.App
cause: ANR Input dispatching timed out (d52bb26 org.mozilla.firefox/org.mozilla.firefox.App (server) is not responding. Waited 5003ms for MotionEvent)
info: ANR in org.mozilla.firefox (org.mozilla.firefox/.App)
PID: 17356
Reason: Input dispatching timed out (d52bb26 org.mozilla.firefox/org.mozilla.firefox.App (server) is not responding. Waited 5003ms for MotionEvent)
Parent: org.mozilla.firefox/.App
ErrorId: 71ddbd61-0b3b-46bb-9809-252a3b68a711
Frozen: false
Load: 3.37 / 2.76 / 2.45
----- Output from /proc/pressure/memory -----
some avg10=0.44 avg60=0.60 avg300=0.51 total=60206887
full avg10=0.19 avg60=0.20 avg300=0.21 total=28624226
----- End output from /proc/pressure/memory -----

CPU usage from 1ms to 9866ms later (2023-01-12 22:33:27.489 to 2023-01-12 22:33:37.354) with 99% awake:
  257% 17356/org.mozilla.firefox: 188% user + 69% kernel / faults: 339934 minor 142 major
  39% 1576/system_server: 24% user + 15% kernel / faults: 60684 minor 61 major
  14% 1998/com.android.systemui: 10% user + 4.4% kernel / faults: 35674 minor 8 major
  14% 2465/com.teqtic.lockmeout:DetectionAccessibilityService: 10% user + 3.5% kernel / faults: 7410 minor 2 major
  11% 3895/dev.patrickgold.florisboard: 8.8% user + 2.9% kernel / faults: 13203 minor 29 major
  9.1% 17516/org.mozilla.firefox:gpu: 4.3% user + 4.7% kernel / faults: 13751 minor 2341 major
  8.5% 638/surfaceflinger: 4.9% user + 3.5% kernel / faults: 3079 minor 1 major
  7.7% 156/kswapd0: 0% user + 7.7% kernel
  6.6% 10084/com.microsoft.teams: 5.1% user + 1.5% kernel / faults: 5304 minor 1436 major
  4.9% 18559/net.mullvad.mullvadvpn:mullvadvpn_daemon: 2.3% user + 2.6% kernel / faults: 6865 minor 389 major
  4.8% 17477/org.mozilla.firefox:tab10: 3.9% user + 0.9% kernel / faults: 2668 minor 92 major
  3% 1526/irq/447-fts: 0% user + 3% kernel
  0.6% 1237/media.swcodec: 0.2% user + 0.3% kernel / faults: 6120 minor 18 major
  1.8% 640/android.hardware.graphics.composer@2.4-service: 1.5% user + 0.3% kernel
  1.4% 306/decon0_kthread: 0% user + 1.4% kernel
  0.3% 1169/media.extractor: 0.1% user + 0.1% kernel / faults: 3229 minor 3 major
  1.2% 1667/kworker/u16:20-events_unbound: 0% user + 1.2% kernel
  1.1% 787/android.hardware.power-service.pixel-libperfmgr: 0.7% user + 0.4% kernel / faults: 3 minor 3 major
  1% 313/mali_jd_thread: 0% user + 1% kernel
  0.8% 600/sugov:0: 0% user + 0.8% kernel
  0.7% 209/thermal_BIG: 0% user + 0.7% kernel
  0.7% 1811/android.hardware.input.processor-service: 0.5% user + 0.2% kernel / faults: 1 minor 1 major
  0.7% 2368/com.android.phone: 0.5% user + 0.2% kernel / faults: 699 minor 159 major
  0.7% 3899/kworker/u16:2-kverityd: 0% user + 0.7% kernel
  0.7% 29953/com.whatsapp: 0.4% user + 0.3% kernel / faults: 8 minor 1 major
  0.7% 31913/kworker/u17:1-ufs_clk_gating_0: 0% user + 0.7% kernel
  0.6% 12/rcu_preempt: 0% user + 0.6% kernel
  0.6% 901/twoshay: 0.5% user + 0.1% kernel
  0.6% 2325/com.shannon.imsservice: 0.4% user + 0.2% kernel / faults: 709 minor 184 major
  0.5% 57/rcuop/5: 0% user + 0.5% kernel
  0.1% 1209/media.codec: 0% user + 0% kernel / faults: 1237 minor 13 major
  0.5% 2181/com.shannon.qualifiednetworksservice: 0.4% user + 0.1% kernel / faults: 772 minor 239 major
  0.5% 2214/com.android.networkstack.process: 0.3% user + 0.2% kernel / faults: 780 minor 190 major
  0.5% 13276/kworker/u16:6-kverityd: 0% user + 0.5% kernel
  0.4% 13/rcuog/0: 0% user + 0.4% kernel
  0.4% 49/rcuog/4: 0% user + 0.4% kernel
  0.4% 50/rcuop/4: 0% user + 0.4% kernel
  0.4% 179/spi11: 0% user + 0.4% kernel
  0.4% 585/logd: 0.2% user + 0.2% kernel / faults: 59 minor 8 major
  0.4% 586/lmkd: 0.1% user + 0.3% kernel
  0.4% 601/sugov:4: 0% user + 0.4% kernel
  0.4% 1625/kworker/u16:1-events_unbound: 0% user + 0.4% kernel
  0.1% 2294/com.shannon.rcsservice: 0% user + 0% kernel / faults: 911 minor 233 major
  0.4% 3898/kworker/u16:0-kverityd: 0% user + 0.4% kernel
  0.4% 10805/kworker/6:1-memlat_wq: 0% user + 0.4% kernel
  0.3% 61/ksoftirqd/6: 0% user + 0.3% kernel
  0.3% 64/rcuop/6: 0% user + 0.3% kernel
  0.3% 213/thermal_MID: 0% user + 0.3% kernel
  0.3% 639/android.hardware.graphics.allocator-V1-service: 0% user + 0.3% kernel / faults: 160 minor 3 major
  0.3% 960/statsd: 0% user + 0.3% kernel / faults: 229 minor 3 major
  0.3% 961/netd: 0.1% user + 0.2% kernel / faults: 376 minor 1 major
  0% 2256/com.samsung.slsi.telephony.oem.oemrilhookservice: 0% user + 0% kernel / faults: 702 minor 115 major
  0% 2341/com.samsung.slsi.telephony.oemril: 0% user + 0% kernel / faults: 729 minor 144 major
  0.3% 2437/com.android.launcher3: 0.1% user + 0.2% kernel / faults: 15 minor
  0% 3952/com.android.nfc: 0% user + 0% kernel / faults: 685 minor 115 major
  0.3% 4551/kworker/u17:2-f2fs_post_read_wq: 0% user + 0.3% kernel
  0.3% 5287/kworker/u16:5-kverityd: 0% user + 0.3% kernel
  0.3% 8896/kworker/4:2: 0% user + 0.3% kernel
  0.3% 16262/kworker/7:1-events: 0% user + 0.3% kernel
  0.2% 11/ksoftirqd/0: 0% user + 0.2% kernel
  0.2% 46/ksoftirqd/4: 0% user + 0.2% kernel
  0.2% 71/rcuop/7: 0% user + 0.2% kernel
  0% 201/eh_comp_thread: 0% user + 0% kernel
  0.2% 216/thermal_LITTLE: 0% user + 0.2% kernel
  0.2% 618/keystore2: 0.1% user + 0.1% kernel / faults: 51 minor
  0% 797/tombstoned: 0% user + 0% kernel / faults: 34 minor 1 major
  0.2% 962/zygote64: 0% user + 0.2% kernel / faults: 380 minor 5 major
  0.2% 1025/android.hardware.sensors@2.1-service.multihal: 0.1% user + 0.1% kernel / faults: 1 minor 1 major
  0.2% 1050/vendor.google.wifi_ext@1.0-service-vendor: 0.1% user + 0.1% kernel / faults: 5 minor 1 major
  0% 1052/audioserver: 0% user + 0% kernel / faults: 134 minor 8 major
  0.2% 1079/android.hardware.vibrator-service.cs40l25: 0% user + 0.2% kernel / faults: 47 minor 5 major
  0% 1163/cameraserver: 0% user + 0% kernel / faults: 295 minor 32 major
  0% 1175/mediaserver: 0% user + 0% kernel / faults: 98 minor
  0.2% 1668/android.hardware.thermal@2.0-service.pixel: 0% user + 0.2% kernel / faults: 1 minor 1 major
  0% 2276/com.android.se: 0% user + 0% kernel / faults: 678 minor 94 major
  0.2% 10069/kworker/3:0-memlat_wq: 0% user + 0.2% kernel
  0.2% 10349/kworker/u17:0-f2fs_post_read_wq: 0% user + 0.2% kernel
  0.2% 14066/kworker/2:0-events: 0% user + 0.2% kernel
  0.2% 32425/kworker/0:0-memlat_wq: 0% user + 0.2% kernel
  0.1% 1/init: 0.1% user + 0% kernel / faults: 10 minor 12 major
  0.1% 14/rcuop/0: 0% user + 0.1% kernel
  0% 23/migration/1: 0% user + 0% kernel
  0.1% 28/rcuop/1: 0% user + 0.1% kernel
  0% 30/migration/2: 0% user + 0% kernel
  0.1% 35/rcuop/2: 0% user + 0.1% kernel
  0% 37/migration/3: 0% user + 0% kernel
  0.1% 42/rcuop/3: 0% user + 0.1% kernel
  0.1% 68/ksoftirqd/7: 0% user + 0.1% kernel
  0.1% 84/kcompactd0: 0% user + 0.1% kernel
  0.1% 159/dmabuf-deferred: 0% user + 0.1% kernel
  0.1% 188/simpleinteracti: 0% user + 0.1% kernel
  0.1% 290/kworker/2:1H-kblockd: 0% user + 0.1% kernel
  0.1% 292/kworker/4:1H-kblockd: 0% user + 0.1% kernel
  0.1% 314/mali_apc_thread: 0% user + 0.1% kernel
  0% 354/kworker/3:1H-kblockd: 0% user + 0% kernel
  0% 437/kworker/0:1H-mem_rx_work: 0% user + 0% kernel
  0% 551/loop0: 0% user + 0% kernel
  0.1% 602/sugov:6: 0% user + 0.1% kernel
  0% 608/vold: 0% user + 0% kernel / faults: 33 minor 2 major
  0% 809/loop5: 0% user + 0% kernel
  0% 811/loop7: 0% user + 0% kernel
  0% 824/loop13: 0% user + 0% kernel
  0% 842/loop22: 0% user + 0% kernel
  0.1% 845/loop23: 0% user + 0.1% kernel
  0% 857/loop27: 0% user + 0% kernel
  0% 863/loop29: 0% user + 0% kernel
  0% 873/loop31: 0% user + 0% kernel
  0.1% 987/rlsservice: 0.1% user + 0% kernel
  0% 1014/android.hardware.health-service.gs101: 0% user + 0% kernel / faults: 8 minor 11 major
  0% 1170/media.metrics: 0% user + 0% kernel / faults: 41 minor 2 major
  0.1% 1203/wificond: 0% user + 0.1% kernel / faults: 1 minor 1 major
  0.1% 1254/aocd: 0% user + 0.1% kernel
  0.1% 2704/f2fs_ckpt-254:5: 0% user + 0.1% kernel
  0.1% 4402/com.rubenmayayo.reddit: 0.1% user + 0% kernel / faults: 2 minor 1 major
  0% 5597/app.vanadium.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0: 0% user + 0% kernel / faults: 1 minor 3 major
  0.1% 9750/com.google.android.googlequicksearchbox:search: 0.1% user + 0% kernel / faults: 30 minor 4 major
  0.1% 13369/com.fsck.k9: 0% user + 0.1% kernel / faults: 11 minor 6 major
  0.1% 13452/com.android.vending: 0% user + 0.1% kernel / faults: 8 minor 7 major
  0.1% 14092/kworker/5:2-memlat_wq: 0% user + 0.1% kernel
  0.1% 14212/kworker/1:3-memlat_wq: 0% user + 0.1% kernel
  0% 17205/kworker/5:1-events: 0% user + 0% kernel
  0.1% 23502/com.synology.dsdrive: 0% user + 0.1% kernel / faults: 13 minor 8 major
 +0% 18031/org.mozilla.firefox:tab20: 0% user + 0% kernel
55% TOTAL: 34% user + 18% kernel + 0.7% iowait + 0.9% irq + 0.6% softirq
CPU usage from 49ms to 516ms later (2023-01-12 22:33:27.537 to 2023-01-12 22:33:28.005):
  130% 17356/org.mozilla.firefox: 123% user + 7.9% kernel / faults: 2301 minor
    99% 17409/DefaultDispatch: 95% user + 3.9% kernel
    11% 17455/Socket Thread: 7.9% user + 3.9% kernel
    7.9% 17402/Gecko: 7.9% user + 0% kernel
    3.9% 17475/Cache2 I/O: 0% user + 3.9% kernel
    3.9% 17634/SSL Cert #4: 3.9% user + 0% kernel
    3.9% 17848/DefaultDispatch: 0% user + 3.9% kernel
    3.9% 17852/SSL Cert #6: 3.9% user + 0% kernel
  50% 1576/system_server: 13% user + 36% kernel / faults: 757 minor
    44% 18023/AnrConsumer: 10% user + 34% kernel
  12% 18559/net.mullvad.mullvadvpn:mullvadvpn_daemon: 4.1% user + 8.2% kernel
    4.1% 18600/llvadvpn_daemon: 0% user + 4.1% kernel
    4.1% 18601/llvadvpn_daemon: 0% user + 4.1% kernel
    4.1% 18787/llvadvpn_daemon: 0% user + 4.1% kernel
  4.3% 156/kswapd0: 0% user + 4.3% kernel
  2.1% 12/rcu_preempt: 0% user + 2.1% kernel
  2.1% 50/rcuop/4: 0% user + 2.1% kernel
  2.1% 57/rcuop/5: 0% user + 2.1% kernel
  2.1% 61/ksoftirqd/6: 0% user + 2.1% kernel
  2.1% 201/eh_comp_thread: 0% user + 2.1% kernel
  2.3% 600/sugov:0: 0% user + 2.3% kernel
  2.6% 1254/aocd: 0% user + 2.6% kernel
  3.4% 10069/kworker/3:0-memlat_wq: 0% user + 3.4% kernel
30% TOTAL: 19% user + 8.8% kernel + 0.8% irq + 1.1% softirq

```

## Firefox logs
d6b386b9-93f4-476a-a721-6f7a627b9168
<native crash>
----
<native crash>

# Additional information
- I'm using GrapheneOS with Sandboxed Google Play Services
- Keyboard is FlorisBoard
