### ISSUE TITLE
Opening the tab drawer does not always scroll to the current tab

### ISSUE THREAD

**Issue by bew** [mozilla-mobile/fenix#26371] opened 2022-08-08 20:41 UTC
### Steps to reproduce

1. Have many tabs open, focus the tabs near the end (not the beginning)
2. Open the tabs drawer 

### Expected behaviour

Always scroll to the current tab

### Actual behaviour

From time to time the tab drawer does not scroll at all and stays at the top.

I didn't find a way to reproduce the problem reliably :/
Whether the tabs are displayed in a list/grid, and whether the toolbar is at the top/bottom gives the same behavior.

### Device name

OnePlus 5

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1 (Build #2015896875)

### Additional information

Here is a video where I repeatedly open the tab drawer and the view does not _always_ scroll to the active tab:

https://user-images.githubusercontent.com/9730330/183510440-f5a4d945-7edc-4fda-87d2-b7adfc7709d0.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21225)

**Comment by bigConifer** [comment] 2022-09-23 23:35
Duplicate of #23584

See https://github.com/mozilla-mobile/fenix/issues/23584#issuecomment-1039030740.

**Comment by csadilek** [comment] 2023-01-24 18:23
See https://github.com/mozilla-mobile/fenix/issues/23584, this feature was removed.

**Closed by csadilek** 2023-01-24 18:23 UTC
Labels: 🐞 bug, needs:triage

**Comment by bew** [comment] 2023-01-25 01:39
I don't see how it's related, https://github.com/mozilla-mobile/fenix/issues/23584#issuecomment-1385684699 says that search groups feature was removed, but in my case I'm already not using search groups. So this shouldn't impact this issue

**Comment by csadilek** [comment] 2023-01-25 01:59
Ah, indeed, apologies, I thought this was related to search tab groups as well, but it isn't. Moving to Bugzilla to keep it.

**Comment by csadilek** [comment] 2023-01-25 01:59
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812221

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
