### ISSUE TITLE
Remember private mode

### ISSUE THREAD

**Issue by MightyLoggor** [mozilla-mobile/fenix#5110] opened 2019-09-04 19:36 UTC
### Reasons
1. User wants to open external links on private mode by default.
2. User is concerned where short links or 'strange' domains may take them.

### Suggestion
- Add a toggle feature in the settings so the app will remember if it should open external links in private mode by default.

**Comment by NotWoods** [comment] 2019-09-27 18:28
Duplicate of #4390. This is a feature now 😄

**Closed** 2019-10-04 23:20 UTC
Labels: 🌟 feature request
