### ISSUE TITLE
[Bug] A space (presumably for the toolbar) is visible at the bottom of a page after moving the toolbar to the top

### ISSUE THREAD

**Issue by wisniewskit** [mozilla-mobile/fenix#17032] opened 2020-12-14 19:55 UTC
## Steps to reproduce

Customize the toolbar so it is at the top of the page
Visit https://mrotherguy.github.io/fx-nightly-changelog/changes/
Swipe/scroll the page up and down until the bottom of the page shows a toolbar-sized space underneath it.

### Expected behavior

No extra toolbar-sized space.

### Actual behavior

An extra toolbar-sized blank space under the page content.

### Device information

* Android device: Samsung Galaxy S7 Edge, Android 8.0.0
* Fenix version: Latest Nightly (Saturday 12/12 2020 @ 5:06 PM; 201212 17:00 Build #2015781003)
 
(Issue was originally reported at https://webcompat.com/issues/63372)

**Comment by ekager** [comment] 2020-12-18 07:14
Closing as dupe of https://github.com/mozilla-mobile/fenix/issues/14821

**Closed by ekager** 2020-12-18 07:14 UTC
Labels: needs:triage, 🐞 bug
