### ISSUE TITLE
FNX-5264 ⁃ [Bug] Delete session button in private mode

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#1819] opened 2019-04-19 15:42 UTC
## Steps to reproduce
Open a private tab,  any website
change to tablist view

### Expected behavior
No session delete button, in line with the normal mode without sessions

### Actual behavior
delete session button is present 

### Device information
* Android device: Samsung Galaxy Tab A (2016) SM-T580, Android 8.1.0 
* Fenix version: 1.0.1916 (11091214) 

![Screenshot](https://user-images.githubusercontent.com/44252450/56431975-0b109f80-62cc-11e9-9b6c-165cb5d2bf36.jpg)UNITO-UNDERSCORE!20190419-173515!UNITO-UNDERSCORE!Fenix!

**Comment by boek** [comment] 2019-04-19 17:00
Hey @LittleAngelwings, this is actually working as intended! The intent was to allow you to quickly end your private session.

If you believe this isn't useful or could be improved please let us know and I can take it back to the product team :)

**Comment by cadeyrn** [comment] 2019-04-19 17:08
@boek Just a thought: If we assume that it's a good idea to have a button to quickly close all open tabs from the private session then it it's probably also a good idea for regular sessions as well to have such a button. So I suggest to be consistent and show the button either in both modes or none of them.

**Comment by boek** [comment] 2019-04-19 17:28
@cadeyrn You're right! We had a primary action button in "normal mode" as well with the session prototype, though that was removed earlier this week. We're in the process of replacing that now :)

**Comment by LittleAngelwings** [comment] 2019-04-19 18:05
I think also it's better in both or none. It's more conformity about this feature.

**Comment by klint** [comment] 2019-05-19 08:07
Wording of that button in private mode and in French is quite confusing: "Supprimer la collection" ("Remove collection").
It should rather read "Supprimer la session" or "Supprimer les sessions" ("Remove session(s)")

**Comment by cadeyrn** [comment] 2019-05-19 08:37
@klint: This will be addressed in #2529.

**Closed** 2020-08-11 13:02 UTC
