### ISSUE TITLE
Fenix lacks the single most useful feature that firefox had over chromium

### ISSUE THREAD

**Issue by LifeIsStrange** [mozilla-mobile/fenix#14102] opened 2020-08-24 00:04 UTC
Being able to play videos, especially YouTube videos in the background for free is a unique feature, it is the raison d'être of why people *pay* for YouTube music premium. 

Even alternative YouTube players such as newpipe cannot play videos/music on the background without showing a very annoying picture in picture. 

Firefox was able to fix that thanks to this *trivial* addon. It is trivial it actually just disable the page visibility and full-screen API for the YouTube domain which make the YouTube anti background hack ineffective. 
https://addons.mozilla.org/en-US/firefox/addon/video-background-play-fix/

Mozilla is about empowering users and porting this technically trivial (great news) yet crucial addon should be prioritarized. 
Loosing it make me loose my main reason of using and sharing to my friends Firefox on Android.

**Comment by buttercookie42** [comment] 2020-08-24 08:03
The addon issues aside, it seems that as per #9691 Firefox might currently also be a little over-aggressive in throttling background tabs even when they're actually playing back media.

**Comment by amkcpu** [comment] 2020-08-24 19:54
Duplicate of #10366.

**Comment by ekager** [comment] 2020-08-24 21:01
closing for #10366.

**Closed by ekager** 2020-08-24 21:01 UTC
Labels: Feature:WebExtensions, feature request 🌟, needs:triage
