### ISSUE TITLE
[Bug] Website page does not size correctly: nytimes.com crossword

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#16136] opened 2020-10-22 20:21 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Open https://www.nytimes.com/crosswords/game/mini
Swipe down a little to begin the crossword (it "recoils" back to fill the screen)
Tap the crossword grid

### Expected behavior

Keyboard is fully visible

### Actual behavior

Bottom row of keyboard is hidden by addressbar

### Device information

* Android device: 10 (also visible in 8.0.0)
* Fenix version: 81.1.5 (also visible in Nightly as at 21/10 @ 1706

Found from https://support.mozilla.org/en-US/questions/1309706

**Comment by s-ankur** [comment] 2020-10-22 20:37
Seems like dupe of https://github.com/mozilla-mobile/fenix/issues/13797

**Comment by liuche** [comment] 2020-10-28 18:44
Thanks! please see the linked issue to follow along on our work to fix this.

**Closed by liuche** 2020-10-28 18:44 UTC
Labels: needs:triage, 🐞 bug
