### ISSUE TITLE
Feature Request - Close tabs when browser is closed. Not only when using quit in the menu.

### ISSUE THREAD

**Issue by DarkRookie00** [mozilla-mobile/fenix#21254] opened 2021-09-12 16:45 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
I would like the tabs to close when closing the app normally on my phone. I do not want to Menu -> Quit. It is very unintuitive. I want to bring up the app list and close it from there.

### How do you know that this problem exists today? Why is this important?
Because it existed in an earlier version that I continue to use to this day. The old version even has a setting for this. Under Menu -> Settings -> Advance - Restore tabs.
Because I do not want my browser to continue where I left off. I close an app, I am done with it. I do not want to open an app to have old data being reloaded each time.

### Who will benefit from it?
Anyone who would want to enable to setting.

**Comment by LaurentiuApahideanSV** [comment] 2021-09-17 10:46
This is a duplicate of https://github.com/mozilla-mobile/fenix/issues/20128, I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-09-17 10:46 UTC
Labels: needs:triage
