### ISSUE TITLE
[Bug] Flash any time a tab is brought into the foreground

### ISSUE THREAD

**Issue by jenabaivab** [mozilla-mobile/fenix#15236] opened 2020-09-20 09:10 UTC
## Steps to reproduce
1. Open any tab
2. Go to settings, extensions, downloads, or any other app via home button
3. Switch back to the tab and there is a white flash
4. Also occurs when closing tabs from the tray

### Expected behavior
No white flash
### Actual behavior
Flashes everytime. Easy to reproduce too.

### Device information

* Android device: 10
* Fenix version: 200919 06:03

![ezgif-1-b0586c65bbe7](https://user-images.githubusercontent.com/60446763/93708096-259a1880-fb51-11ea-9063-29fa17d39e6f.gif)

Same thing happens when I switch apps. The moment FF is brought into the background, there is this bright flash provided I am seeing a tab, not any settings or downloads page.

Edit - You can't see the second flash while going back to Wikipedia due to frame loss in the mp4 to gif conversion. It still exists though.

**Comment by PlayXman** [comment] 2020-09-23 06:36
I can confirm that. I'm on `80.1.3` version and I have probably much slower phone (Huawei p10 lite) than @jenabaivab because I can see "the flash" much cleaner whenever I visit bookmarks, history, or settings and return back to web page. It seems like the whole layout is rendered from the scratch - white background, address bar, and after that webpage itself.

It's not so slow, although it's noticeable.

**Comment by jenabaivab** [comment] 2020-10-01 09:51
Any fixes for this maybe please? Tried using FIrefox Beta and found this same issue.

**Comment by ekager** [comment] 2020-12-18 06:42
This should be fixed now by the solution to #6313

**Closed by ekager** 2020-12-18 06:42 UTC
Labels: needs:triage, 🐞 bug
