### ISSUE TITLE
top navigation

### ISSUE THREAD

**Issue by cup** [mozilla-mobile/fenix#4550] opened 2019-08-05 23:22 UTC
open this issue as every other has been closed and refed as a duplicate of a
locked issue.

this is an important issue and should be open for discussion.

**Comment by cadeyrn** [comment] 2019-08-06 05:07
Duplicate of #2115. If #2115 is locked it should not be circumvented by opening another issue...

**Comment by boek** [comment] 2019-08-06 15:32
Hey @cup, rest assured this is something that we are thinking about. We locked the conversation to collaborators only as the discussion before hand was not constructive.

**Closed by boek** 2019-08-06 15:32 UTC
