### ISSUE TITLE
FNX2-15337 ⁃ [Bug] Severe startup lags (two Firefox apps in app switcher)

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12577] opened 2020-07-15 01:14 UTC
## Steps to reproduce
So far I have been able to successfully reproduce this by following the below steps but it also happens without the device restarts that too several times in a day. I'd say in 2 or 3 startups out of 5.

* Restart the device
* Launch Fenix
* Fenix takes more than 30 seconds to launch

- - -
Note: And I have also noticed that when this happens there are 2 Fenix previews in the Android task manager screen, attaching screenshots of this. Please let me know if you need more information regarding the startup lags. I can also get you any logs if you give me the correct instructions. The lag also affects installed PWAs.

- - -
### Expected behavior
Fenix should launch in a few seconds if not immediately

### Actual behavior
Fenix takes more than 30 seconds to launch

### Device information
* Android device: Motorola One Power on Android 10
* Fenix version: Fennec migration build `null (Build #2015749827)
AC: 48.0.3, ce6247fb8
GV: 79.0-20200629163142
AS: 61.0.7`

![qoi1zsjws](https://user-images.githubusercontent.com/68282543/87494267-2e133600-c66c-11ea-8fa2-5541324da577.jpg)

- - -
**Edit:** This is also happening on the [RC 1](https://github.com/mozilla-mobile/fenix/releases/tag/v79.0.0) release candidate. Hope somebody looks into it soon, otherwise this might end up in the Release version!

**Edit:** And I'm also getting a "Force close" dialogue from the Android system and startup lags have increase dramatically some of them are even several dozen seconds sometimes!

**Comment by ShatteredPixel** [comment] 2020-07-15 01:14
CC @mcomella

**Comment by ShatteredPixel** [comment] 2020-07-17 10:45
Can somebody even care to respond? I know you may be busy but if you make it too late then I may not be available to give you more details in time in future.

**Comment by eliserichards** [comment] 2020-07-17 17:54
Hi @ShatteredPixel, we appreciate you opening the issue. We will investigate once it has gone through our engineering processes in place to triage and prioritize. Thanks!

**Comment by ShatteredPixel** [comment] 2020-07-22 03:45
@eliserichards This is also happening on the [RC1](https://github.com/mozilla-mobile/fenix/releases/tag/v79.0.0) release candidate. Hope somebody looks into it soon otherwise this might end up in the Release version!

**Comment by mcomella** [comment] 2020-07-24 23:25
@ShatteredPixel Thanks for reporting and sorry for the delay – I've been a little disorganized.

We haven't been able to reproduce so let us know if you feel there is anything special to your configuration that we might not have tested. Some initial questions from us:
- Is this a build you built yourself?
  - If so, can you see if you can reproduce on [the official RC2 build](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.fennec-production.2020.07.24.revision.8e5d2c0465c9f1bb3dfe791e243ae7071fdbd4b9.arm64-v8a/artifacts/public/build/arm64-v8a/geckoProduction/target.apk)? Unfortunately, testing this build might require uninstalling your current build :( 
- Does this happen on a fresh install? i.e. if you don't change any settings?
- How many PWAs do you have installed? We haven't tested with PWAs before. Do you have a sample PWA we can install and try out?
- Are you signed into a Firefox Account and have sync enabled? Do you know if you have an exceptionally large history or bookmarks list?
- How many tabs do you have open?

Anything else you can think of would be great, thank you!

**Comment by ShatteredPixel** [comment] 2020-07-25 01:22
@mcomella 


> - Is this a build you built yourself?
>   - If so, can you see if you can reproduce on [the official RC2 build](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.fennec-production.2020.07.24.revision.8e5d2c0465c9f1bb3dfe791e243ae7071fdbd4b9.arm64-v8a/artifacts/public/build/arm64-v8a/geckoProduction/target.apk)? Unfortunately, testing this build might require uninstalling your current build :( 

The builds I'm talking about are something that I have downloaded from the Taskcluster: https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/project.mobile.fenix.v2.fennec-production.latest/artifacts/public/build/arm64-v8a/geckoProduction/target.apk

Under the 'fennec-production' label. It's a migration build with the package name `org.mozilla.firefox`and yes the build link you gave me installed on top of the build I already had. Both have the same APK package name i.e `org.mozilla.firefox`.

> - Does this happen on a fresh install? i.e. if you don't change any settings?

I have 3 add-ons installed uBO, Dark Reader, Search by Image. But I have tried disabling them and the problem still reproduces. Apart from that I don't have a lot of settings changed. 

- Zoom on all websites and Open links in apps are enabled.


- I do have a about 27 Top Sites.
- I do have 4 Collections.
  - Collection 1 has 3 websites stored
  - Collection 2 has 5 websites stored
  - Collection 3 has 39 websites stored
  - Collection 4 has 5 websites stored
  - Collection 5 has 1 websites stored



  
> - How many PWAs do you have installed? We haven't tested with PWAs before. Do you have a sample PWA we can install and try out?


I have a single PWA which is Twitter: https://mobile.twitter.com/home


> - Are you signed into a Firefox Account and have sync enabled? Do you know if you have an exceptionally large history or bookmarks list?

I am signed into a Firefox account and have only Bookmarks sync enabled. I have not counted the number bookmarks I have bit they should be around 200 and most them are under a folder I have manually created (there 5 folders in total). However I have noticed one thing that I do seem to have a lot of history items, I couldn't count them but they did seem to be a lot to me. I'll try to clear them and will try to reproduce the issue again.

> - How many tabs do you have open?

I don't keep any tabs open and as soon as the work gets done I clear them. However, sometimes I do have something like 10 or so open tabs but they have never gone above 15 or so.

> Anything else you can think of would be great, thank you!

Apart from the device restart steps to reproduce I gave in the issue description (comment 0) there's no clear pattern to the startup lags it happens very randomly but recently they have become more severe and more frequent. And I'm also getting Force close dialogue from the Android system. In fact as soon as installed the [build](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.fennec-production.2020.07.24.revision.8e5d2c0465c9f1bb3dfe791e243ae7071fdbd4b9.arm64-v8a/artifacts/public/build/arm64-v8a/geckoProduction/target.apk) you gave me and I launched Fenix, it gave me a Force close/wait dialogue. It happened with previous migration builds too (3 including this build).

___ 

It a bit off-topic but the Taskcluster builds here: https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2 are not updating from previous 4 days not even the Nightlies. Have the build links changed again?

**Comment by mcomella** [comment] 2020-07-27 19:12
Thanks for all the detailed info – this is great! I'll try to replicate your configuration to reproduce.

> It's a bit off-topic but the Taskcluster builds here: https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2 are not updating from previous 4 days not even the Nightlies. Have the build links changed again?

Yes, they're now at: https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix I believe they should be stable from now on but I'm not 100% certain.

**Comment by mcomella** [comment] 2020-07-27 23:40
@ShatteredPixel Thanks for working with us! We have a few more questions...

- How long ago did you originally install this Firefox profile? How have you updated it (do you just download new APKs from TaskCluster or GitHub?)? How often do you update it?
- Could you provide us with a video of you reproducing the behavior? We're wondering if we're launching the app differently and that's why we haven't been able to reproduce
- (After providing the video above) Can you temporarily try uninstalling the Twitter PWA (by removing it from your homescreen) and seeing if you can still reproduce? We hope it's not too much trouble!

Thanks in advance!

**Comment by kbrosnan** [comment] 2020-07-28 15:06
It is unlikely that they will respond @mcomella, they deleted their account for the second time.

**Comment by mcomella** [comment] 2020-07-28 18:33
Thanks kbrosnan. Extrapolating with what I talked to csadilek about, I think our options are:
- Try to reproduce using the configuration provided above
- Since having two Firefox apps in the app switcher implies a "new task" issue, we can ask folks with more experience in task code (pocmo, NotWoods, mihai?) if they have any ideas

I'll sync up with csadilek on what's the best use of our time.

**Comment by mcomella** [comment] 2020-07-30 23:08
@pocmo @NotWoods I believe you have some experience with our Activity tasks code. Can you think of any situations that'd result in two Firefox applications, like in the original comment? https://github.com/mozilla-mobile/fenix/issues/12577#issue-656990472

---

@rafalopilowski1 Are you able to reproduce this issue? I saw your 👍 on the original post. If you have any information which would help us reproduce, that would be great!

**Comment by githubtemp1472** [comment] 2020-07-31 12:01
Hi, @mcomella the original reporter here. 
 
> @ShatteredPixel Thanks for working with us! We have a few more questions...

>     * How long ago did you originally install this Firefox profile? How have you updated it (do you just download new APKs from TaskCluster or GitHub?)? How often do you update it?

 I installed most of my updates through the Taskcluster. It must have been at least 3 months that I was updating my builds from the Taskcluster only since there are no immediate builds available from your GitHub release page, so I just moved to the Taskcluster. And yes, I used to update them as soon as you released them sometimes as fast as in just a few minutes of you uploading them. 


>     * Could you provide us with a video of you reproducing the behavior? We're wondering if we're launching the app differently and that's why we haven't been able to reproduce


Attaching the Screen Record. But let me first confirm that as soon as **I re-installed the browser** the startup lags disappeared like magic. Also see that there are **two apps seem to be launching and one of them disappears automatically**. Just see the video and you will understand what I am saying. My feelings tell me that the startup lags that I was getting were due to this 2 app launches. When reproducing just  be be very quick when pressing the Android navigation bar's app switcher button. Okay? And the video files are in ZIP format so you can see the the video with full frame rate. unzip them to see the video. And also notice in another video that you will see that I was also getting a **"App isn't available"** error. 


>     * (After providing the video above) Can you temporarily try uninstalling the Twitter PWA (by removing it from your homescreen) and seeing if you can still reproduce? We hope it's not too much trouble!

I completely reinstalled the browser and also don't have any PWAs and the startup lags are no longer reproducing. though I still see 1 or 2 sometimes 3 seconds of lags every now and then. The startup lags didn't occur in earlier versions ( mostly from previous 1 month's builds didn't have this).

> Thanks in advance!

Yeah, Thanks a lot. :) 


Device: Motorola One Power, Android 10. 

Fenix: 79.0.1 (the release version)


[Screen Record (2 apps).zip](https://github.com/mozilla-mobile/fenix/files/5006834/Screen.Record.2.apps.zip)
[App isn't available error.zip](https://github.com/mozilla-mobile/fenix/files/5006840/App.isn.t.available.error.zip)

**Comment by rafalopilowski1** [comment] 2020-07-31 13:54
@mcomella 
I've tested RC1 and RC2 of Firefox migration builds on OnePlus 6 (Android 10). I was using a fresh profile/installation.
 - I can confirm, that on these builds, there are two Firefox apps in app switcher on every startup. One of them disappers almost immediately. 
 - On my device I can't observe severe startup lags, but my device is still quite fast, so that might be a case.

**Comment by mcomella** [comment] 2020-08-01 00:37
Thanks folks – this is really helpful. I'll respond more thoroughly on Monday. Have a good weekend!

**Comment by mcomella** [comment] 2020-08-04 18:48
I see two issues here:
1. long pauses when starting Firefox
2. two Firefox tasks present in the recent app switcher on startup

To keep the discussions separate, I filed a new bug for 2: https://github.com/mozilla-mobile/fenix/issues/13270

For 1), let's continue the the discussion here...

> I installed most of my updates through the Taskcluster. It must have been at least 3 months that I was updating my builds from the Taskcluster only since there are no immediate builds available from your GitHub release page, so I just moved to the Taskcluster. And yes, I used to update them as soon as you released them sometimes as fast as in just a few minutes of you uploading them.

Given this isn't an update path we test, I wonder if there could have been a build that most users didn't receive that created inconsistencies in your profile data and caused the app to take an exceptionally long time to start up.

I also noticed that there is a bug where users can see a white screen when launching a PWA: https://github.com/mozilla-mobile/fenix/issues/13008 That could also have been related.

> though I still see 1 or 2 sometimes 3 seconds of lags every now and then. The startup lags didn't occur in earlier versions ( mostly from previous 1 month's builds didn't have this).

I noticed there's another issue open that mentions blocking startup for a few seconds and offending code was only introduced maybe a month ago: https://github.com/mozilla-mobile/fenix/issues/13254 Perhaps this is the issue you're now seeing?

Given we're unable to reproduce the 30 second startup lags described in the original post and the original poster cannot reproduce the issue anymore, it doesn't seem like it may be prominent so I think we should close the issue as unactionable. If you see this issue again, please reopen the bug or file a new one!

@csadilek Do you agree that we should close this issue as unactionable?

**Comment by pocmo** [comment] 2020-08-05 16:11
(If you see this again: You said that the force close dialog pops up, which makes it likely that this is an ANR with maybe a deadlock. If you are able to provide the trace file then this may help find the cause: https://developer.android.com/topic/performance/vitals/anr#pull_a_traces_file)

**Comment by csadilek** [comment] 2020-08-07 20:08
@mcomella yes, agreed, let's close as we have other tickets on file.

Reporter closed their account since. Thanks for filing, please re-open should this reproduce.

**Closed** 2020-08-13 17:30 UTC
Labels: eng:performance, 🐞 bug
