### ISSUE TITLE
Firefox Android fails to download pdf files from links.

### ISSUE THREAD

**Issue by AndyP2002** [mozilla-mobile/fenix#16571] opened 2020-11-14 12:16 UTC
I have noticed this on three occasions in the last few days.
The pdf appears to be downloading (animated down-arrow in notification area) but after a long time I get a "download failed" in the notification area.

If I open the same link in Chrome, the pdf not only downloads successfully, it also displays automatically.

One example from the youGov official website:
https://yougov.co.uk/topics/politics/articles-reports/2014/09/11/blue-most-attractive-eye-colour(popup:search/eye%20colour;type=surveys)
Third result down:
https://d25d2506sfb94s.cloudfront.net/cumulus_uploads/document/cqzhgj7jld/InternalResults_140903_eye_colour_W.pdf

Firefox version: 82.1.3 (Build #2015774641) on Samsung Tab A10 (2019) SM-T510 with Android 10

**Comment by Whisprin** [comment] 2020-11-16 12:55
To add some more context to the issue:
Search for "PDF test": https://duckduckgo.com/?q=PDF+test&t=h_&ia=web

Doesn't work (download is never started):
* First link: http://www.orimi.com/pdf-test.pdf
* Second link: https://s1.q4cdn.com/806093406/files/doc_downloads/test.pdf

Works (file is downloaded):
* https://opensource.apple.com/source/cups/cups-136.9/cups/test/testfile.pdf

When I click on a link to a PDF file for the first time:
* Firefox display the download prompt
* I click on download
* A download notification with a running progress bar appears but there's no progress (file size is 0,02 MB)
* The notification stays there until I click on Cancel
* A new notification appears: Title: Downloads, Body: null
* The notification disappears after a few seconds

When I try to download the same link again:
* Firefox just shows a loading bar at about 20% which doesn't progress

The download is not visible in the "Downloads" menu of Fennec (also not as failed).

**Comment by Amejia481** [comment] 2020-11-16 16:06
Thank you, @Whisprin and @AndyP2002 for reporting,
I thinks this the same as https://github.com/mozilla-mobile/fenix/issues/15378, the issue should be fixed on Firefox 83.
You can validate by checking if you are able to reproduce in [Beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) or [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) ?

Please feel free to reopen if needed.

**Closed by Amejia481** 2020-11-16 16:06 UTC
Labels: needs:triage

**Comment by Whisprin** [comment] 2020-11-16 16:20
Seems to be fixed in version 84 for me

**Comment by AndyP2002** [comment] 2020-11-21 10:54
Confirmed, seems to be fixed on v83 main release (which I waited for rather than download betas)
