### ISSUE TITLE
Pin toolbar

### ISSUE THREAD

**Issue by daozhihun** [mozilla-mobile/fenix#14330] opened 2020-08-28 00:09 UTC
### What is the user problem or growth opportunity you want to see solved?

Need an option to pin the toolbar to prevent it from hiding automatically when scrolling down.
In previous version of Firefox for Android, we could pin the toolbar to prevent it from hiding when scroll the page. This is useful when someone want the toolbar to show forever and get quick access to it without scrolling up.

### How do you know that this problem exists today? Why is this important?

In recent days, the mobile phones get longer and longer, from 16:9 to 18:9 even 20:9, there is enough room for the toolbar.

### Who will benefit from it?

Users who want the toolbar show forever to get quick access to it without scrolling up.
Need an option like previous version of Firefox mobile.

**Comment by cadeyrn** [comment] 2020-08-28 06:25
Duplicate of #10240.

**Comment by maxstarkenburg** [comment] 2020-08-28 22:48
This was the change that has most bugged me today after the update, and one of the reasons I have disliked other mobile browsers. Perhaps my scrolling habits or fingers are different from others', but the constant reappearance and disappearance is so distracting to me.

Hopefully it'll get re-added soon, I guess as a portion of #10240, though I doubt I ever would have realized by title alone that this issue was part of that issue, haha. I also hope the wider scope of that issue doesn't delay this one change.

**Closed** 2020-09-01 01:53 UTC
Labels: needs:triage
