### ISSUE TITLE
[Bug] intl.accept_languages about:config pref does not persist on Fenix Nightly

### ISSUE THREAD

**Issue by argymeg** [mozilla-mobile/fenix#16287] opened 2020-10-30 16:24 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1) Go to `about:config`, and change (or reset) the `intl.accept_languages` pref.
2) Check browser headers on a website, the `Accept-Language` header is following the change.
3) Close and reopen the browser.
4) Check browser headers again.

### Expected behavior
The `Accept-Language` header is still following the change.

### Actual behavior
The `Accept-Language` header has been reset to its original value, along with the about:config pref.
### Device information

* Android device: Sony Xperia 1 II
* Fenix version: Nightly 201029 17:03
 
This is related to #6502 but I believe is a separate issue, as this doesn't have to do with exposing the pref to the user.

**Comment by crisalis2** [comment] 2020-11-01 06:33
I created basically the same issue, #12043. It got closed in favor of the other issue you mentioned, #6502. Somehow this whole thing has been completely overlooked until now, even though from time to time someone creates an issue related to this. The sad part is that #6502 as an issue is almost as if it didn't exist: has no priority assigned, barely any comments or thumbs up (only mine, actually), and probably no dev is interested in it or even really knows/remembers it exists. I recommend you leave some comment in #6502 and upvote it, hopely some day this will be fixed/implemented.

**Comment by argymeg** [comment] 2020-11-01 14:02
Apologies, I only looked at open issues so I missed yours. Like you said, I really wouldn't consider it a duplicate. IMO, in addition to the obvious annoyance, this is a significant privacy concern - any efforts at resisting fingerprinting are significantly undermined if Firefox is broadcasting to the world my specific combination of installed languages.

**Comment by kbrosnan** [comment] 2020-11-02 20:43
Closing as a duplicate of #6502. about:config is not a supported method of tweaking Fenix behavior.

**Closed by kbrosnan** 2020-11-02 20:43 UTC
Labels: needs:triage, 🐞 bug
