### ISSUE TITLE
[Bug] Empty Settings view after tapping the back button

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9139] opened 2020-03-13 09:53 UTC
## Prerequisites
Have uBlock Origins installed

## Steps to reproduce
1. Open uBlocks  "Settings" section
2. Tap the device back button

### Expected behavior
Should properly exit to uBlocks options & settings view.

### Actual behavior
Empty Settings section

### Device information

* Android device: OnePlus A3 (Android 6.0.1)

* Fenix version: 
• Fenix Beta 4.1.0-beta.2 Build #20730532 from 3/13
• Fenix Nightly Build #20730607 from 3/13

### Notes
► Video
![20200313-112411](https://user-images.githubusercontent.com/51314259/76610117-1f334000-6521-11ea-96dc-7db56dcb09c7.gif)

**Comment by csadilek** [comment] 2020-03-17 14:50
This, as well as https://github.com/mozilla-mobile/fenix/issues/8808, are ultimately caused by us ignoring uBlock's configuration to open the options page in a tab: https://github.com/gorhill/uBlock/blob/master/platform/firefox/manifest.json#L77

I will put up a PR to fix this so that the settings/options pages is opened in a tab instead, preventing many of these problems.

**Comment by csadilek** [comment] 2020-03-17 20:28
@AndiAJ re: my comment above. The uBlock options/settings page is now opened in a tab as configured by the add-on (It was always opened in a tab if triggered via the browser action popup). This is the correct behaviour, so I think we can close this bug. Can you verify.

**Comment by AndiAJ** [comment] 2020-03-18 07:01
Hi @csadilek , I've just re-tested this matter on the latest **`Nightly Build #20780606 from 3/18`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

Indeed now it's opened in a new tab, on the other hand if you tap the device back button the settings section remains empty (a page refresh will do the trick).
It should actually exit to Fenix's home screen.

Could you please review and share your thought? ☺️ 

► Video
![20200318-085106](https://user-images.githubusercontent.com/51314259/76933972-04811280-68f7-11ea-8d89-93737d97a400.gif)

**Comment by csadilek** [comment] 2020-03-18 14:26
@AndiAJ ah indeed. That's actually a bug in the latest uBlock and also reproducible in Fennec.

This is another one to put on the list to relay to the add-on developer. Not something we can fix. /cc @kewisch

**Closed by csadilek** 2020-03-18 14:26 UTC
Labels: Feature:WebExtensions, S2, needs:triage, 🐞 bug
