### ISSUE TITLE
[Bug]: Missing all necessary plugins

### ISSUE THREAD

**Issue by KatseNarniaan** [mozilla-mobile/fenix#22227] opened 2021-10-29 14:59 UTC
### Steps to reproduce

1. Try to install an addon, for example Stylus. (https://addons.mozilla.org/en-US/firefox/addon/styl-us/)
2. No way to install it.

### Expected behaviour

1. Go to https://addons.mozilla.org/en-US/firefox/addon/styl-us/
2. Click "Add to Firefox"
3. The addon is installed and works.

### Actual behaviour

1. Go to https://addons.mozilla.org/en-US/firefox/addon/styl-us/
2. "Add to Firefox" button is greyed out, and clicking it does nothing.
3. Click "Download file" and click "Open" and it says "no app found to open xpi files"

### Device name

OnePlus 9

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

93.1.0

### Additional information

It seems 67,581 people have managed to install the Stylus addon and its' rating is 4,6 stars. Why is it not working now?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18511)

**Comment by mariansima** [comment] 2021-11-29 11:23
Hey @KatseNarniaan Thanks for your submission! Unfortunately this add-on seems to be incompatible with Firefox for Android. You can search for other apps from the redirect link on the page you mentioned or search for add-ons directly in the app menu.
![262114109_580435929679615_8210836508623501258_n](https://user-images.githubusercontent.com/89511597/143859010-f9281ba7-c2db-451d-a602-418c0ff6130b.jpg)

**Comment by KatseNarniaan** [comment] 2021-11-29 11:27
What is wrong with this browser? Obviously there is something seriously wrong with the addon system of the browser when there are almost no addons for it. Fix it ASAP,  please!

**Comment by mariansima** [comment] 2021-11-29 11:41
Hey @KatseNarniaan you can find add-ons in the 3-dot menu. Or go to Settings > Advanced > Add-ons and choose from the list. The add-on from this issue is for desktop only. If you want to see it for Android consider reaching out to the developers. Closing this issue.

**Comment by cadeyrn** [comment] 2021-11-29 12:35
> If you want to see it for Android consider reaching out to the developers

I guess you mean reaching out to the developers of the add-on because _this_ is already the right place to reach out to the Firefox developers, right? Then it's not helpful advice since the compatibility of add-ons is not the primary reason why no other add-on for Firefox for Android exists. It's because it was an explicit decision from Mozilla to only support a few add-ons for now. AFAIU there are currently no plans to expand the support.

**Comment by mariansima** [comment] 2021-11-29 12:49
> I guess you mean reaching out to the developers of the add-on because _this_ is already the right place to reach out to the Firefox developers, right?

Yes, my mistake.

> it was an explicit decision from Mozilla to only support a few add-ons, at least for the near and mid term. Who knows what someday is. But AFAIU there are currently no plans to expand the add-on support in Firefox for Android.

I was not aware of this, thank you for clarifying.

**Comment by KatseNarniaan** [comment] 2021-11-29 12:52
> It's because it was an explicit decision from Mozilla to only support a few add-ons, at least for the near and mid term. Who knows what someday is. But AFAIU there are currently no plans to expand the add-on support in Firefox for Android.

This needs to be fixed ASAP!

**Comment by sflorean** [comment] 2022-05-26 14:27
Closing as duplicate of #20736.

**Closed by sflorean** 2022-05-26 14:27 UTC
Labels: 🐞 bug, S3, Feature:WebExtensions, needs:triage, qa-triaged
