### ISSUE TITLE
[Bug] Fenix Nightly crashes at sign out when logged in with QR code

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#6614] opened 2019-11-15 09:13 UTC
### Prerequisites
Make sure you have a valid account and you are connected on Desktop.

## Steps to reproduce
1. On Desktop, go to firefox.com/pair - Show code.
2. On Firefox Preview Nightly go to Turn on Sync - Ready to scan.
3. Scan the QR code and approve the device on Desktop and confirm the pairing on mobile.
4. Go to Account settings and Sign out.
### Expected behavior
The user is signed out.
### Actual behavior
The user is signed out and Fenix crashes.
### Notes
This is not reproducible all the time.
[signoutcrash.txt](https://github.com/mozilla-mobile/fenix/files/3850627/signoutcrash.txt)
[Video](https://drive.google.com/file/d/1CbmM9jsO_cK_lha6BtEf9dBllK8fCzGT/view?usp=sharing)
### Device information

* Android device: Huawei Honor 8 (Android 7.0)
* Fenix version: Nightly 191115 GV 72

**Comment by boek** [comment] 2019-12-27 23:19
```
Storage Error: "No record for uaid:chid \"ff0a7cc223fe40629b8c17d7f9346279\":\"992a0f0542383f1ea5ef51b7cf4ae6c4\"")
        at mozilla.appservices.push.RustError.intoException(RustError.kt:8)
        at mozilla.appservices.push.PushManager.decrypt(PushManager.kt:16)
        at mozilla.components.feature.push.RustPushConnection.decrypt(Connection.kt:3)
        at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invokeSuspend(AutoPushFeature.kt:20)
        at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invoke(AutoPushFeature.kt)
        at mozilla.components.feature.push.AutoPushFeatureKt$launchAndTry$1.invokeSuspend(AutoPushFeature.kt:5)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
```

**Comment by kbrosnan** [comment] 2020-01-10 00:39
Sentry issue: [FENIX-3JE](https://sentry.prod.mozaws.net/operations/fenix/issues/6861431/)

**Comment by kbrosnan** [comment] 2020-01-10 00:40
Sentry issue: [FENIX-3QP](https://sentry.prod.mozaws.net/operations/fenix/issues/6938689/)

**Comment by ValentinTimisica** [comment] 2020-03-02 15:30
Tried multiple times to reproduce this but without any success. Also, I saw in [FENIX-3QP](https://sentry.prod.mozaws.net/operations/fenix/issues/6938689/) sentry issue that it has been marked as resolved due to inactivity. In [FENIX-3JE](https://sentry.prod.mozaws.net/operations/fenix/issues/6861431/) sentry issue we only have 2 occurrences in the last 30 days.

**Comment by Diana-Rus** [comment] 2020-04-01 07:15
Hi, i was able to reproduce a crash 1 time after multiple attempt on the build Nightly 191115 GV 72 with Google Pixel 3 Xl (Android 9) with STR from issue.

I have also checked on build Nightly 3/31 (Build #20910606) and build Nightly 4/01 (Build 209206707) with Google Pixel 3 XL (Android 9), Huawei P9 Lite (Android 7) and Sony Xperia Z5 (Android 7) and did not encounter any crash.

Is there a possibility for someone to take a look at the sentry issue [FENIX-3JE](https://sentry.prod.mozaws.net/operations/fenix/issues/6861431/) and see whether there there have been other occurrences in the last days?

**Comment by ValentinTimisica** [comment] 2020-04-21 09:46
Checked now and the issue has been marked as resolved in sentry. There is no occurrence in the last 30 days.

**Closed** 2020-05-06 01:32 UTC
Labels: P2, S1, a-s, b:crash, eng:qa:verified, needs:ac, 🐞 bug
