### ISSUE TITLE
[Bug]Broken Tabs selection counter

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#13025] opened 2020-07-28 14:12 UTC
## Prerequisites
Have 6 tabs open

## Steps to reproduce
1. Log tap the first listed tab
1. Tap the close button
1. While the deletion confirmation snack is displayed tap to select the next tab
1. Repeat the steps until are left with only one open tab

### Expected behavior
The Tab selection count should be properly adjusted

### Actual behavior
The Tab selection count is continuously incremented

### Device information
* Android device: all
* Fenix version: Nightly Build #200728 from 7/28

### Notes
►Video
![20200728-170255](https://user-images.githubusercontent.com/51314259/88676997-6f3c2900-d0f5-11ea-8067-3b944c31cd91.gif)

**Comment by ekager** [comment] 2020-07-28 14:21
Dupe of #12992

**Closed** 2020-08-28 23:08 UTC
Labels: Feature:Collections, Feature:Tabs, S2, Skittle, needs:triage, 🐞 bug
