### ISSUE TITLE
[Bug] Possible intermittent UI test failure - SettingsAboutTest.verifyAboutFirefoxPreview

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#9685] opened 2020-04-03 16:46 UTC
In my PR https://github.com/mozilla-mobile/fenix/pull/9607, I received a UI test failure ([firebase](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4945431146187137688/executions/bs.7d3456f0d9f01a64)) in `SettingsAboutTest.verifyAboutFirefoxPreview`. However, I only touched unit test code and build code – no production app or UI test code – so the UI test results should remain unchanged.

aaronmt briefly looked into this and noted:
> Open bug with the intermittent label for now mcomella -- that one is weird, "Test instrumentation process crashed. Check org.mozilla.fenix.ui.SettingsAboutTest#verifyAboutFirefoxPreview.txt for details"

Also from the video tab:
> Video is not available for test cases shorter than 0.5 seconds or where Firebase Test Lab records at a low framerate, such as for virtual devices. 

---

aaronmt continued investigation:

> Oh the log-cat shows it got the crash reporter dialog and quit
I wonder if we can do some kind of graceful shutdown or better crash identification 04-03 11:54:46.113: I/ActivityManager(1663):   Force finishing activity ActivityRecord{fb957a6 u0 org.mozilla.fenix.debug/mozilla.components.lib.crash.prompt.CrashReporterActivity t5}
Are there many crash reports from Firebase AVD devices (how do you even identify them?)

**Comment by AaronMT** [comment] 2020-04-06 01:06
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5253904521782985921

Crash happening, is there any way to associate a report here with full details?

> 04-05 20:29:14.754: I/ActivityManager(1662): Start proc 9736:org.mozilla.fenix.debug:mozilla.components.lib.crash.CrashHandler/u0a95 for service org.mozilla.fenix.debug/mozilla.components.lib.crash.handler.CrashHandlerService


> 04-05 20:29:14.980: I/mozac/CrashReporter(9736): Received crash: NativeCodeCrash(minidumpPath=/data/user/0/org.mozilla.fenix.debug/files/mozilla/5l1x879t.default/minidumps/68ecf2dd-4442-24dd-a687-da33c63b7a6f.dmp, minidumpSuccess=false, extrasPath=/data/user/0/org.mozilla.fenix.debug/files/mozilla/5l1x879t.default/minidumps/68ecf2dd-4442-24dd-a687-da33c63b7a6f.extra, isFatal=true, breadcrumbs=[])

> 04-05 20:29:15.029: I/ActivityManager(1662): Process org.mozilla.fenix.debug (pid 7743) has died: fore TOP 


> 04-05 20:29:14.983: I/ActivityManager(1662): START u0 {flg=0x10018000 cmp=org.mozilla.fenix.debug/mozilla.components.lib.crash.prompt.CrashReporterActivity (has extras)} from uid 10095
04-05 20:29:14.992: I/WindowManager(1662): WIN DEATH: Window{66d3117 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity}

**Comment by sv-ohorvath** [comment] 2020-05-29 12:42
A more recent crash in this test: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5054681088551426089/executions/bs.efdb4b92e00b7e2/testcases/2/test-cases
 
taken from: https://github.com/mozilla-mobile/fenix/runs/693200739

**Comment by sv-ohorvath** [comment] 2020-06-15 13:17
I'm seeing this Test Instrumentation crash more often and in other tests as well:
verifyBasicNavigationToolbarFunctionality
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7287191204756880523/executions/bs.960426304d4a9b/testcases/2/test-cases
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8567795915680826663/executions/bs.95c241f917dd0fc5/testcases/2/test-cases

threeDotMenuItemsTest
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8567795915680826663/executions/bs.cfff703900824186/testcases/2/test-cases

**Comment by ekager** [comment] 2020-06-16 19:25
Came here to report that threeDotMenuItemsTest crashing as well

**Comment by rpappalax** [comment] 2020-06-30 13:53
@AaronMT @sv-ohorvath let's try and re-enable once this has landed later this week: https://github.com/mozilla-mobile/fenix/issues/12048

**Comment by rpappalax** [comment] 2020-06-30 22:50
this is a dupe of: https://github.com/mozilla-mobile/fenix/issues/11642

**Closed by rpappalax** 2020-06-30 22:50 UTC
Labels: Feature:Settings, disabled-test, eng:ui-test, intermittent-test
