### ISSUE TITLE
[Bug]: Open in app not working on second use

### ISSUE THREAD

**Issue by plwt** [mozilla-mobile/fenix#21904] opened 2021-10-13 17:43 UTC
### Steps to reproduce

From a first run copy of Firefox for Android:

Open the three dot menu
Select Settings
Select the option to Open links in apps
Go to https://www.google.com/maps/dir/?api=1&destination=
Once opened in Google Maps app, close Google Maps and enter again in Firefox for Android

### Expected behaviour

Page opens again in Firefox for Android

### Actual behaviour

Page opens in Firefox for Android

### Device name

Samsung S5, Samsung S7, Motorola Moto E5

### Android version

Android 8 (Moto E5)

### Firefox release type

Firefox

### Firefox version

93.1.0

### Additional information

User feedback: https://support.mozilla.org/en-US/questions/1352172

**Comment by VampireSilence** [comment] 2021-10-13 23:51
**Expected behaviour**

Route opens in Google Maps over and over again.

**Actual behaviour**

The first route opens in Google Maps, but the following routes open in Google Maps **Go** (until you restart FF).

**Comment by plwt** [comment] 2021-11-29 20:27
User feedback: https://support.mozilla.org/en-US/questions/1359491

**Comment by blogmangit** [comment] 2021-12-08 14:58
please firefox  team do something about this still not fixed on nightly android 08 Dec 2021.

**Comment by blogmangit** [comment] 2021-12-09 15:52
Firefox  Team this issue seems to be fixed on "Firefox Android Reference Browser Nightly Build 09 Dec 2021" Please look into this If possible to fix now on nightly

**Comment by LaurentiuApahideanSV** [comment] 2022-02-22 10:44
I can confirm the issue is reproducible on Firefox Nightly 2022-02-22. A newer and detailed issue has been summitted here: https://github.com/mozilla-mobile/fenix/issues/23684. I will close this issue since it will be handled there.
### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android 9)

**Closed by LaurentiuApahideanSV** 2022-02-22 10:44 UTC
Labels: 🐞 bug, needs:triage
