### ISSUE TITLE
FNX-14345 ⁃ [Bug] Selection is drawn on top of fenix UI

### ISSUE THREAD

**Issue by pukafever** [mozilla-mobile/fenix#13164] opened 2020-07-31 13:39 UTC
## Steps to reproduce

- Open deepl.com
- Open another page
- Close the second page
- The selector is drawn on top of the fenix UI

### Expected behavior

The page should close without drawing the selector on top of the UI

### Actual behavior

![ezgif.com-video-to-gif.gif](https://user-images.githubusercontent.com/43613824/89040303-d8b17700-d343-11ea-8384-ef7b4245cbf2.gif)

### Device information

* Android device: Samsung S8 (Android 9)
* Fenix version: Nightly 200726 10:10 (Build #22081018)

**Comment by liuche** [comment] 2020-08-08 00:31
sorry, I don't understand this issue, what selection is drawn on top?

**Comment by Gaspacchio** [comment] 2020-08-10 14:55
Sorry, @liuche, I know that wasn't clear, but it's kind of hard to explain. Have you seen the gif?

The radio selection that you can see in the screenshot below appears on top of the tab selector.

![Screenshot_20200810-165100_Firefox Nightly](https://user-images.githubusercontent.com/43613824/89796508-08256800-db2a-11ea-9ec2-ee73e3eeb17d.jpg)

**Comment by hwinnemoe** [comment] 2020-08-10 15:05
I think it is this moment that is meant with "drawn on top":

![image](https://user-images.githubusercontent.com/42788925/89797316-12943180-db2b-11ea-9dee-f5a93d55b209.png)

**Comment by ekager** [comment] 2020-12-17 22:39
Dupe of https://github.com/mozilla-mobile/fenix/issues/11043

**Closed by ekager** 2020-12-17 22:39 UTC
Labels: needs:triage, 🐞 bug
