### ISSUE TITLE
FNX-499 ⁃ When launching Fenix, Enable private browsing button is focused instead of Search or address

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/fenix#2142] opened 2019-04-29 20:16 UTC
## Steps to reproduce
Launch Fenix

### Expected behavior
Search or enter address is focused

### Actual behavior
Enable private browsing button is focused

### Device information
* Android device: ? Galaxy S6
* Fenix version: ? Firefox Preview 1.0.1918 (Build #11181249 68.0a1-20190422094240)

**Comment by asadotzler** [comment] 2019-04-30 21:24
Would love to get this but we'd probably ship without it.

**Comment by fobo66** [comment] 2019-07-18 14:04
I'd like to work on it. Found a root cause, preparing a fix now

**Comment by chiragmantri** [comment] 2019-07-29 16:03
@asadotzler is this issue fixed? or is there any work item left for this?

**Comment by fobo66** [comment] 2019-07-29 16:14
I've fixed this, it appears to be working fine now

**Comment by sv-ohorvath** [comment] 2019-08-01 15:09
Partially fixed. I logged a follow-up bug since this one has already landed in RC 1.2: https://github.com/mozilla-mobile/fenix/issues/4447.

**Comment by mcarare** [comment] 2019-08-02 12:56
The fix also causes  #4489, I think it should be revisited. Also, IMO the focus change is against good practices in accessibility.

**Comment by ekager** [comment] 2019-08-02 16:03
Okay @mcarare I can back out the change and maybe we can make a meta ticket about home screen a11y issues as we look at redesign options

**Comment by ekager** [comment] 2019-08-02 16:40
I'm going to undo these changes because it seems to cause other issues (#4447 and #4489), so let's reopen this and we can bring it up as an accessibility concern about the homescreen.

**Comment by fobo66** [comment] 2019-08-04 12:59
Looks like this issue cannot be properly fixed (without accessibility focus change) because of homescreen layout hierarchy

**Comment by lime124** [comment] 2019-08-05 17:41
oops forgot to remove needs ux label - i've added it to an a11y audit so we can look at this then.

**Comment by mcarare** [comment] 2020-04-29 11:01
This is fixed, as a result of the changes implemented as per comment: https://github.com/mozilla-mobile/fenix/issues/1718#issuecomment-566674558.

**Closed** 2020-08-11 14:04 UTC
Labels: Feature:HomeScreen, b:a11y, 🐞 bug
