### ISSUE TITLE
Display link text in context menu

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#6065] opened 2019-10-17 04:01 UTC
Originally filed as part of #6064 by @marcinwiacek 

### Why/User Benefit/User Problem
Current context menu on web pages (available after longer pressing link/image) is displaying menu options + URL. 

This is not very user friendly - URLs are many times complicated and user can't check if there was pressed correct link.

### What/Requirements
It should display at URL + title in the header of context menu - see https://bugs.chromium.org/p/chromium/issues/detail?id=847454#c19

### Acceptance Criteria (how do I know when I’m done?)
There is displayed more info about URL in the context menu. If it's an image the alt text should be used (#580).

**Comment by marcinwiacek** [comment] 2019-10-17 09:03
Please display URL AND text, not text INSTEAD OF URL.

Both info are required.

**Comment by Crandel** [comment] 2019-10-17 09:14
I agree, there are a lot websites that has one title for a lot of pages

**Comment by wisniewskit** [comment] 2019-10-17 15:24
On webcompat.com, users are also suggesting to allow them to expand truncated alt-text when long-tapping on an image like Xkcd comics: https://webcompat.com/issues/42153

**Comment by kbrosnan** [comment] 2020-01-14 00:06
This is a dupe of #580. Unless you want the text for the anchor element to be displayed.

**Closed by kbrosnan** 2020-01-14 00:06 UTC
Labels: Feature:ContextMenu, 🌟 feature request

**Comment by marcinwiacek** [comment] 2020-01-14 09:51
https://github.com/mozilla-mobile/fenix/issues/6065#issuecomment-543080065 - I'm proposing, that we can display info for link, but also info for pictures.
