### ISSUE TITLE
Allow disabling the reader mode

### ISSUE THREAD

**Issue by 07416** [mozilla-mobile/fenix#17832] opened 2021-02-04 16:59 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
It's very easy to accidentally press the reader mode icon in the address bar ~~-- this opens the current incomplete implementation which lacks any customization options  (background color selection, font, page width).~~

### How do you know that this problem exists today? Why is this important?
~~Very inconvenient with the dark theme and Dark Reader addon as the reader mode uses a white background.~~

The `reader.parse-on-load.enabled` (to `false`) preference doesn't (appear to) work on mobile.

And most notably, the reader mode has never worked with paginated articles from what I know and obviously can fail to parse some article content.

### Who will benefit from it?
Users who don't want to use the reader mode ~~and at the time those who prefer to wait for feature-parity with the desktop Firefox.~~

**Comment by Dunexus** [comment] 2021-02-04 17:05
> incomplete implementation which lacks any customization options (background color selection, font, page width)

There are customization options. Open reader mode > 3-dot menu > Appearance.

**Comment by 07416** [comment] 2021-02-04 17:20
> There are customization options. Open reader mode > 3-dot menu > Appearance.

Thank you, edited out.

The reader mode should follow system theme (assuming this isn't a bug affecting my installation).

**Comment by kbrosnan** [comment] 2021-02-04 21:04
This issue has several requests in it. Please only report single issues in a report. Closing

* Disable reader mode
* about:config pref does not work - This is expected and not a bug. about:config will only work on Gecko prefs.
* Readability.js detecting paginated content https://github.com/mozilla/readability/issues/12

**Closed by kbrosnan** 2021-02-04 21:04 UTC
Labels: needs:triage

**Comment by sollyucko** [comment] 2021-11-27 19:32
The button to toggle Reader Mode is really easy to accidentally press and reloads the page, losing form data! https://android.stackexchange.com/questions/242949/firefox-reader-mode-lost-my-form-input
