### ISSUE TITLE
downloaded file has bin extension instead of opensudoku

### ISSUE THREAD

**Issue by maurerle** [mozilla-mobile/fenix#17263] opened 2020-12-30 13:39 UTC
Downloading new sudokus for the opensudoku app from their website:
https://opensudoku.moire.org/ downloads a file with bin extension instead of opensudoku extension which is why it can not get recognized by the app.

## Steps to reproduce
1. Open https://opensudoku.moire.org/sudoku/easy.opensudoku in Fennec Android downloaded from F-Droid
2. Downloaded file gets saved as easy.bin instead of easy.opensudoku

### Expected behavior
File gets saved as easy.opensudoku
### Device information

* Android device: Redmi Note 7 lavender (reproduced on a samsung too)
* Fenix version: Fennec 84.1.2 from F-Droid

**Comment by sflorean** [comment] 2020-12-30 15:22
I wasn't able to reproduce the issue on Nightly 30/12 with Xiaomi Redmi Note 8T (Android 9).

**Comment by maurerle** [comment] 2020-12-30 15:28
I just downloaded Firefox for Android Beta from the Play Store which is Version 85.0.0-beta.4 and could reproduce the issue on Android 10.
The other device which reproduced the issue is also running on Android 10?

**Comment by maurerle** [comment] 2020-12-30 15:31
Just tested current Firefox Nightly 201229 and could also reproduce the issue

**Comment by sflorean** [comment] 2020-12-30 16:35
Thanks @maurerle for the extra info, I was able to reproduce it on an Android 10 devices.

**Comment by maurerle** [comment] 2020-12-30 17:05
The .bin extension seems to come from here:
https://github.com/mozilla-mobile/android-components/blob/51bd9843331f62f63cdef5f9c98361198158c67d/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt#L148-L152

It is unclear to me why this code branch is taken as the filename obviously contains a dot?

the mime-type of the file is [application/octet-stream]

**Comment by evilpie** [comment] 2021-01-04 13:20
I suspect what might happen is that `changeExtension` changes the extension for files with the MIME type `application/octet-stream`. @Amejia481

**Comment by Amejia481** [comment] 2021-01-04 17:06
Thanks for the report I added the issue to our backlog

**Comment by Amejia481** [comment] 2021-01-29 14:57
The fix should be in master, QA team please help us to verify. Thanks in advance!

**Comment by Amejia481** [comment] 2021-01-29 14:59
> I suspect what might happen is that `changeExtension` changes the extension for files with the MIME type `application/octet-stream`. @Amejia481

The problem was that we were not considering generic MIME types you can see more details on https://github.com/mozilla-mobile/android-components/issues/9526 and https://github.com/mozilla-mobile/android-components/issues/9526 :)

**Comment by maurerle** [comment] 2021-01-29 15:05
Thanks @Amejia481! when will the fix be availbale in Firefox Nightly?

**Comment by Amejia481** [comment] 2021-01-29 15:10
It should be available in the next update.  You can check the version by going to `Settings` -> `About Firefox Nightly`  the AC version should be `73.0.20210128143151` or higher

**Comment by maurerle** [comment] 2021-01-31 11:46
Yes its working now. Tested with current Firefox Nightly.
Thank you!

**Comment by sflorean** [comment] 2021-02-01 09:22
I can confirm that this is also fixed in latest Nightly builds. Closing as verified.

**Closed by sflorean** 2021-02-01 09:22 UTC
Labels: Feature:Download, S3, eng:qa:needed, needs:ac, 🐞 bug
