### ISSUE TITLE
[webcontent] Website crashes Fenix & SystemUI

### ISSUE THREAD

**Issue by tegutistgut** [mozilla-mobile/fenix#19461] opened 2021-05-11 10:28 UTC
https://www.sparkasse.de/unsere-loesungen/privatkunden/rund-ums-konto/online-banking.html

EDIT: This bug seems to affect every website from "https://sparkasse.de".
Maybe related to a svg rendering bug. (I ain't no programmer but it _could_ be related to the "logo_ini.svg" file on every website from them)

(Its a German Banking Website)

Website should load normally (like on other Browsers i.e. DuckDuckGo)

Firefox first lags and becones unresponsive after that the SystemUI of Android crashes.

### "Does toggling Tracking Protection fix the issue?" 

No, Firefox freezes almost immediately.

### "Can you reproduce in Chrome (or other non-Mozilla browser)?" 

No, this error seems only to affect Firefox Mobile on Android (Fenix)

### Device information

* Android device: Samsung Galaxy A51, Android 11, OneUI 3.1, Security patch 1.April 2021, Google Play systemupdate 1.April 2021.

* Fenix version: 
88.1.3 (from the Google Play Store) (Build #2015808507)
AC: 74.0.13, ccf500706
GV: 88.0.1-20210504152106
AS: 74.0.1

**Comment by LaurentiuApahideanSV** [comment] 2021-05-11 14:07
I can confirm the issue is reproducible on Firefox Preview RC 88.1.3 and Nightly 5/10.
### Devices used:
- Pixel 3 XL (Android 9)
- Samsung Galaxy S9 (Android 8)

**Comment by kbrosnan** [comment] 2021-05-11 22:05
I think this is bz-1673653. Using a Note 9 I am able to render the page but it is choppy.  I see some big chunks of time rendering SVGs and there is a 7000x7000px sparse SVG sprite sheet as part of the page. @jamienicol does that look correct to you?

* https://share.firefox.dev/3hk6r0g
* https://share.firefox.dev/3tFd2F9

**Comment by tegutistgut** [comment] 2021-05-12 07:01
something new:
This bug seems to affect every website from "https://sparkasse.de".
Maybe related to a svg rendering bug. (I ain't no programmer but it _could_ be related to the "logo_ini.svg" file on every website from them)

**Comment by jamienicol** [comment] 2021-05-12 09:42
Yes @kbrosnan that looks correct. Currently we rasterize the gigantic svg as a single image on the main content thread, then get killed trying to upload it as a single texture in webrender.

Unrelated, we are currently making a change to upload large textures in smaller tiles, which should help a small amount. Then in bug 1673653 we are switching to use the same infrastructure we use for inline SVGs, so that they get rasterized off of the main thread. Then on top of that we will likely make it so that we only rasterize and upload the required parts, which should dramatically in cases like this where the spritesheet is large and sparse.

@tegutistgut the SVG that is causing the problem is `sprite-6825441c.svg`. (`logi_ini.svg` is tiny in comparison.) Does blocking that "fix" it?

**Comment by tegutistgut** [comment] 2021-05-12 09:49
> @tegutistgut the SVG that is causing the problem is `sprite-6825441c.svg`. (`logi_ini.svg` is tiny in comparison.) Does blocking that "fix" it? 

Hey thanks for the answer.  But im not able to find the `sprite-6825441c.svg` URL to block it.

Neither in the network analysis in the f12 toolbar and neither when i lookup the source of the website (crtl/stgr + U)


Whats the URL of the svg file? 

Thx

**Comment by tegutistgut** [comment] 2021-05-12 09:59
@jamienicol yes i blocked following url: 

`www.sparkasse.de/etc/designs/shared/static/images/svg/sparkasse/sprite-6825441c.svg`

In ublock origin, but sadly it didst fixed the crash.

BUT, this time only the tab crashed and the rest of Firefox and my phone was OK.
After the sparkasse.de tab froze, it closed and brought me back to the home page of Firefox.

**Comment by jamienicol** [comment] 2021-05-12 10:57
How are you blocking the svg? Do you still see any icons on the page after blocking?

I'm not using ublock, but if I block the request in the devtools then it completely fixes the issue on that page for me.

**Comment by tegutistgut** [comment] 2021-05-12 10:59
@jamienicol I blocked it by putting the URL into my ublock origin blocklist.
But the tab still freezes and crashes (1
this takes up to 1-3 seconds)


And im sorry, but i dont know what the devtools are.

**Comment by jamienicol** [comment] 2021-05-12 11:10
The devtools are like the f12 toolbar but for your android device. In the firefox android settings there should be a "Remote debugging via USB" option which you need to enable. Then you can plug your phone in to your computer, and in Firefox on the computer go to about:debugging, and connect to your phone.

But if the tab crashes you won't be able to use this...

I got it to work with ublock, but it looked like I had to restart the browser for it to take effect? Does that help? What if you try blocking '*.svg'? Can you take a screenshot of the page before it crashes so I can see if it has been blocked correctly?

**Comment by tegutistgut** [comment] 2021-05-12 11:39
@jamienicol hey again.

I did a mistake: i said that i had put

`www.sparkasse.de/etc/designs/shared/static/images/svg/sparkasse/sprite-6825441c.svg`
in my blacklist/blocklist but I accidentally had put it in my whitelist 🤦‍♂️

Now I created a new rule in ublock origin: 

`||sparkasse.de/etc/designs/shared/static/images/svg/sparkasse/sprite-6825441c.svg`

And the website is working normal again.

Here is a Screenshot of the website:
(Pic)


Thanks again for your help and solving my problem!!

**Comment by kbrosnan** [comment] 2021-05-12 17:17
Closing as an upstream Gecko issue.

**Closed by kbrosnan** 2021-05-12 17:17 UTC
Labels: b:crash, qa-triaged
