### ISSUE TITLE
IllegalStateException: Fragment HomeFragment not attached to a context.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#6832] opened 2019-11-27 10:22 UTC
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6162466/
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6162466/
Socorro [link](https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.IllegalStateException%3A%20at%20androidx.fragment.app.Fragment.requireContext%28Fragment.java%29&date=%3E%3D2019-07-21T07%3A06%3A00.000Z&date=%3C2020-04-22T07%3A06%3A00.000Z#graphs)

```
IllegalStateException: Fragment HomeFragment{1a41004} (84c6a2c6-6203-448c-b564-fee8f55208fc)} not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
    at androidx.fragment.app.Fragment.getResources(Fragment.java:1)
    at org.mozilla.fenix.home.HomeFragment$onViewCreated$2.invokeSuspend(HomeFragment.kt:9)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
...
(2 additional frame(s) were not displayed)

Fragment HomeFragment{1a41004} (84c6a2c6-6203-448c-b564-fee8f55208fc)} not attached to a context.
```

**Comment by pocmo** [comment] 2019-11-27 10:23
Because of the UUID in the stack trace this is split over multiple crash reports in Sentry.

Crash stats seems to be a bit smarter:
https://crash-stats.mozilla.com/signature/?product=Fenix&version=72.0a1&signature=java.lang.IllegalStateException%3A%20at%20androidx.fragment.app.Fragment.requireContext%28Fragment.java%29&date=%3E%3D2019-11-20T10%3A20%3A00.000Z&date=%3C2019-11-27T10%3A20%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#reports

According to crash stats the crash volume is increasing and it's now our top 6 crash.

**Comment by vesta0** [comment] 2020-01-06 17:55
Need STR for this.

**Comment by Baron-Severin** [comment] 2020-01-08 19:11
Note to QA: this is a very rare crash, and I don't think we're going to be able to reproduce it.  I'm also very confident in the fix.  If you don't mind, I think it's safe can call this `qa-not-needed`.

**Comment by Baron-Severin** [comment] 2020-01-10 21:59
Closed by #7509

**Comment by liuche** [comment] 2020-01-21 19:02
I'm still seeing issues for this https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6162466/

**Comment by boek** [comment] 2020-01-21 19:10
We will monitor this over the next sprint

**Comment by boek** [comment] 2020-02-11 05:55
this is definitely a race condition/memory leak. [This PR](https://github.com/mozilla-mobile/fenix/pull/7772) reliably causes the crash

**Comment by ekager** [comment] 2020-04-21 06:18
Possible that leak fixes for home in https://github.com/mozilla-mobile/fenix/pull/10033
and https://github.com/mozilla-mobile/fenix/pull/10012 will resolve these issues. We should monitor Nightly and see if instances start to decrease.

**Comment by liuche** [comment] 2020-04-22 01:06
Looks like some change since mid-march in [socorro](https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.IllegalStateException%3A%20at%20androidx.fragment.app.Fragment.requireContext%28Fragment.java%29&date=%3E%3D2019-10-22T01%3A03%3A00.000Z&date=%3C2020-04-22T01%3A03%3A00.000Z#graphs) 🤔

**Comment by ekager** [comment] 2020-04-23 04:02
Okay another fix landed - after the next Nightly goes out let's monitor crash stats 🤞🏻

**Comment by AaronMT** [comment] 2020-05-14 17:04
java.lang.IllegalStateException: Fragment HomeFragment{32dd527} (861da8e7-151f-4367-9f5a-af37c10c6e3b)} not attached to a context.
     FATAL EXCEPTION: main
Process: org.mozilla.fenix.debug, PID: 9206
java.lang.IllegalStateException: Fragment HomeFragment{32dd527} (861da8e7-151f-4367-9f5a-af37c10c6e3b)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
	at org.mozilla.fenix.ext.FragmentKt.getRequireComponents(Fragment.kt:22)
	at org.mozilla.fenix.home.HomeFragment.getSessionManager(HomeFragment.kt:150)
	at org.mozilla.fenix.home.HomeFragment.getListOfSessions(HomeFragment.kt:836)
	at org.mozilla.fenix.home.HomeFragment.getListOfTabs(HomeFragment.kt:842)
	at org.mozilla.fenix.home.HomeFragment.emitSessionChanges(HomeFragment.kt:832)
	at org.mozilla.fenix.home.HomeFragment.access$emitSessionChanges(HomeFragment.kt:111)
	at org.mozilla.fenix.home.HomeFragment$onCreateView$sessionObserver$1.invoke(HomeFragment.kt:188)
	at org.mozilla.fenix.home.HomeFragment$onCreateView$sessionObserver$1.invoke(HomeFragment.kt:111)
	at org.mozilla.fenix.home.BrowserSessionsObserver$onStart$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:137)

https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8796887443883565548/executions/bs.e2cfcee6e6e97791

**Comment by AaronMT** [comment] 2020-05-19 21:00
Another crash

https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8814662090942448693/executions/bs.b7e71229a2ddee82/issues

```Kotlin
java.lang.IllegalStateException: Fragment HomeFragment{ed2a8} (c8f516b5-7891-4bf9-92db-114042a3c802)} not attached to a context.
     FATAL EXCEPTION: main
Process: org.mozilla.fenix.debug, PID: 8890
java.lang.IllegalStateException: Fragment HomeFragment{ed2a8} (c8f516b5-7891-4bf9-92db-114042a3c802)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
	at org.mozilla.fenix.ext.FragmentKt.getRequireComponents(Fragment.kt:22)
	at org.mozilla.fenix.home.HomeFragment.getSessionManager(HomeFragment.kt:150)
	at org.mozilla.fenix.home.HomeFragment.getListOfSessions(HomeFragment.kt:836)
	at org.mozilla.fenix.home.HomeFragment.getListOfTabs(HomeFragment.kt:842)
	at org.mozilla.fenix.home.HomeFragment.emitSessionChanges(HomeFragment.kt:832)
	at org.mozilla.fenix.home.HomeFragment.access$emitSessionChanges(HomeFragment.kt:111)
	at org.mozilla.fenix.home.HomeFragment$onCreateView$sessionObserver$1.invoke(HomeFragment.kt:188)
	at org.mozilla.fenix.home.HomeFragment$onCreateView$sessionObserver$1.invoke(HomeFragment.kt:111)
	at org.mozilla.fenix.home.BrowserSessionsObserver$onStart$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:137)```

**Comment by sflorean** [comment] 2020-05-21 13:23
I was able to reproduce this crash on Nightly 5/21. Device: Motorola Nexus 6 (Android 7.1.1). 
STR:
1. Launch Fenix with a clean profile.
2. Tap on "Read our privacy notice" link from the "Your privacy card" - onboarding.

Reproducible 3/3.
https://crash-stats.mozilla.org/report/index/be958eb3-64a8-4f7a-9608-1b0b90200521

**Comment by ekager** [comment] 2020-06-25 21:52
cc @sflorean are you still able to reproduce with those STR?

**Comment by sflorean** [comment] 2020-07-17 09:19
@ekager sorry for the late reply here! Tested with the same device on Nightly 7/16 and on 79.0.0-beta.7 and the issue isn't reproducible anymore.

**Closed** 2020-07-17 09:50 UTC
Labels: P1, S1, b:crash, eng:qa:not-needed, needs:investigation, 🐞 bug
