### ISSUE TITLE
Firefox Beta fails to download files from Mediafire.

### ISSUE THREAD

**Issue by parvinderandroid** [mozilla-mobile/fenix#12280] opened 2020-07-04 15:23 UTC
I have tried it in both normal mode and private mode.

Video of issue here:

https://i.imgur.com/YCnmUwO.mp4

**Comment by parvinderandroid** [comment] 2020-07-05 15:49
It is a duplicate of the new issue #12997

**Comment by SS1113** [comment] 2020-07-05 16:08
Duplicate of #12297  

Thanks for filing the issue! :)

**Closed** 2020-08-28 21:47 UTC
Labels: needs:triage
