### ISSUE TITLE
[Bug] When opting for "Top Toolbar", some websites show a bottom padding. 

### ISSUE THREAD

**Issue by shashke** [mozilla-mobile/fenix#15916] opened 2020-10-15 14:48 UTC
## Steps to reproduce
Select "Top" in Toolbar section of customize option. Then, go for any scroll-able content website, goal.com/en & Bing Rewards in my case, do a scroll down. While doing that, contents loads with a bottom padding as if its replicating a behavior of a non-existent bottom toolbar. 

### Expected behavior
The content should cover the whole screen and shouldn't have a gap.

### Actual behavior
Content has a gap from bottom.

### Device information
Google Pixel (2016), 32GB
* Android device: Yes, Android Q, Lineage OS 17.1 (SDK 29)
* Fenix version: 81.1.4

**Comment by liuche** [comment] 2020-10-22 00:50
Dupe of ##14821, please follow along there.

**Closed by liuche** 2020-10-22 00:50 UTC
Labels: needs:triage, 🐞 bug
