### ISSUE TITLE
[Bug]: Unwanted redirects on pressing back button

### ISSUE THREAD

**Issue by iamiceparticle** [mozilla-mobile/fenix#23473] opened 2022-01-30 04:43 UTC
### Steps to reproduce

1. Open a tab.
2. Open link https://www.timesnownews.com/india/article/amar-jawan-jyoti-to-be-merged-with-national-war-memorial-flame-on-friday-all-you-need-to-know/851452.
3. Press back button.

### Expected behaviour

Must go back to Firefox new tab page.

### Actual behaviour

Redirects multiple times to timesnownews pages.

https://user-images.githubusercontent.com/76210878/151686890-5f3bd99e-83a1-4235-8fb0-bfb612e06666.mp4

### Device name

Samsung Galaxy A71

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19320)

**Comment by iamiceparticle** [comment] 2022-01-30 04:44
Samsung internet browser doesn't redirects. And even chrome doesn't redirects.

**Comment by sheikh-azharuddin** [comment] 2022-01-31 10:10
This is called back button hijacking! Some websites do it deliberately to prevent users leaving their webpage..if i remember chromium based browsers have already fixed it back in 2019/20..not sure fixed in firefox or not

**Comment by LaurentiuApahideanSV** [comment] 2022-02-02 11:50
I can confirm the issue is reproducible on Firefox Nightly 2022-02-02.
### Device used:
- Realme GT Master Edition (Android 11)

**Closed** 2022-11-26 20:47 UTC
Labels: 🐞 bug, S3, needs:triage, wontfix, qa-triaged
