### ISSUE TITLE
Firefox nightly crashing 

### ISSUE THREAD

**Issue by CyberGeek009** [mozilla-mobile/fenix#20528] opened 2021-07-27 08:06 UTC
It always crashes when i try to clear history. 
android version 11
Firefox version  92.0a1
crash report
7b037c41-d60d-4cc2-bc79-e41e6e22b51e
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
----
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.remove(ArrayList.java:503)
	at org.mozilla.fenix.home.sessioncontrol.viewholders.topsites.TopSitesPagerAdapter.onBindViewHolder(TopSitesPagerAdapter.kt:25)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:9)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:135)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:8)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:119)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
	at android.view.View.measure(View.java:25969)
	at android.view.ViewGroup.measureChild(ViewGroup.java:7080)
	at androidx.viewpager2.widget.ViewPager2.onMeasure(ViewPager2.java:1)
	at android.view.View.measure(View.java:25969)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7112)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25969)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:16)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:11)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:119)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
	at android.view.View.layout(View.java:23313)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:22)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
	at android.view.View.layout(View.java:23313)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23313)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23313)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23313)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23313)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23313)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23313)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:867)
	at android.view.View.layout(View.java:23313)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3978)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3379)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2340)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9057)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1040)
	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
	at android.view.Choreographer.doFrame(Choreographer.java:791)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1025)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:255)
	at android.app.ActivityThread.main(ActivityThread.java:8192)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by jonalmeida** [comment] 2021-07-27 15:17
Duplicate of https://github.com/mozilla-mobile/fenix/issues/20449

**Closed by jonalmeida** 2021-07-27 15:17 UTC
Labels: Feature:TopSites, b:crash, needs:triage
