### ISSUE TITLE
[Bug] "null" toast when opening/closing keyboard

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#15427] opened 2020-09-25 16:52 UTC
This is a bug in Android 11 with autofill. See https://github.com/mozilla-lockwise/lockwise-android/issues/1219, which was fixed in https://github.com/mozilla-lockwise/lockwise-android/pull/1224.

## Steps to reproduce
Open keyboard

### Expected behavior
No toast

### Actual behavior
A toast shows up with "null" text

<img width="346" alt="image" src="https://user-images.githubusercontent.com/43795363/94294531-95c7e600-ff25-11ea-8b1d-393e81d3b0b4.png">

### Device information

* Android device: Pixel 3 API 30 (Android 11)
* Fenix version: Latest master, 81.1.2

**Comment by eliserichards** [comment] 2020-09-25 17:39
```
2020-09-25 12:05:53.322 511-511/? E/RemoteFillService: Error calling on fill request
    java.lang.RuntimeException: null
        at com.android.server.autofill.RemoteFillService$1.onFailure(RemoteFillService.java:165)
        at android.service.autofill.IFillCallback$Stub.onTransact(IFillCallback.java:128)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)
```

**Comment by tex0l** [comment] 2020-10-28 13:30
@eliserichards may I ask why the [fix hasn't been rolled out in production](https://github.com/mozilla-lockwise/lockwise-android/issues/1225) yet? Is there an issue we can help you with?

**Comment by mcarare** [comment] 2021-01-26 11:45
QA, can you also test this? I have tested on a Pixel 4 with Android 11, and I could not reproduce this.

**Comment by abodea** [comment] 2021-01-29 09:34
I was not able to reproduce this issue on the latest Nightly 1/29 with Google Pixel 4 XL (11).
Note that I used different autofill apps, I used the Fenix Autofill and nothing happened regarding the `null` toast when opening/closing the keyboard.

**Comment by mcarare** [comment] 2021-02-11 13:40
Closing this as it is not reproducible anymore. Will reopen if it shows up again.

**Closed by mcarare** 2021-02-11 13:40 UTC
Labels: Android:11, Feature:Logins, Skittle, help wanted, 🐞 bug
