### ISSUE TITLE
[Bug] Home screen scrolls when it doesn't need to

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#8545] opened 2020-02-19 19:35 UTC
## Steps to reproduce
1.  Enter private browsing mode
2.  Scroll up

### Expected behavior

The home screen doesn't vertically scroll because there's very little content on it

### Actual behavior

The home screen *does* vertically scroll, enough to hide the logo

### Device information

* Android device: Pixel 4
* Fenix version: Master

![ScrollingHome](https://user-images.githubusercontent.com/46655/74868929-a9222b80-531c-11ea-8c06-1b8c5dddaf40.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15819)

**Comment by 532910** [comment] 2020-10-06 17:51
![ScreenRecord-2020-10-06-07-49-04](https://user-images.githubusercontent.com/14617699/95210366-1921eb00-07f4-11eb-896a-81160bb65fb9.gif)

**Comment by gouri-panda** [comment] 2020-11-08 20:18
This looks like a good first issue. Can I work on this issue?

**Comment by VaishnaviShri** [comment] 2021-04-03 07:51
Hi! I am an Outreachy applicant. Can I work on this issue, please?

**Comment by lobontiumira** [comment] 2021-04-07 08:21
Verified as fixed on the 4/7 Nightly build with Samsung Galaxy Note 8 (Android 9), and HTC 10 (Android 8).

**Comment by jonalmeida** [comment] 2021-04-14 17:15
To fix https://github.com/mozilla-mobile/fenix/issues/19030, I'm going to revert the change for this PR and re-open the issue.

**Comment by lobontiumira** [comment] 2021-04-21 14:29
Reproducible on 4/21 Nightly, and Beta 89.0.0-beta.1, with Samsung Galaxy Note 8 (Android 9), and Xiaomi Mi 8 Lite (Android 9).

**Comment by lobontiumira** [comment] 2021-05-18 13:01
Reproducible on RC 88.1.4, and Beta 89.0.0-beta.8 builds with Samsung Galaxy Note 8 (Android 9).

**Comment by Nickoriginal** [comment] 2021-07-20 03:57
Reproducible in Firefox 90.1.2, 91.0.0-beta.2 and Nightly 92.0a1 2021-07-19T17:08:15.507

**Comment by Nickoriginal** [comment] 2021-07-20 04:34
It's better to partitioning required actions for the normal homescreen and the private homescreen areas and what we want to see there.
### Desired behaviour
https://user-images.githubusercontent.com/85299944/126261473-6d0c9e75-fcd3-4ac1-9369-60c07dcf124e.mp4

Private home screen should not be scrollable at all, because it doesn't contain (and will not contain) any info that will go beyond it.

**Comment by lobontiumira** [comment] 2021-09-24 06:23
This issue still reproduces on all builds: 9/24 Nightly, Beta 93.0.0-beta.4, and RC 92.1.1, with all devices.

**Comment by SoftVision-LorandJanos** [comment] 2022-12-07 05:51
This issue is no longer reproducible on the latest Nightly 109.0a1 (2022-12-07) build.
Device used: Pixel 4 (Android 13).
Closing the ticket as verified.

**Closed by SoftVision-LorandJanos** 2022-12-07 05:51 UTC
Labels: 🐞 bug, good first issue, Feature:HomeScreen, eng:qa:needed, help wanted
