### ISSUE TITLE
[Bug] Long press on gopher links does not work

### ISSUE THREAD

**Issue by PurpleCodingWizard** [mozilla-mobile/fenix#13861] opened 2020-08-15 18:04 UTC
## Steps to reproduce
1. Visit this site: http://defanor.uberspace.net/ 
2. Search: 'my gopher site'
3. Long press on the link
### Expected behavior
Long press should display link info, as it would for regular http links.
### Actual behavior
Does nothing.
### Device information

* Android device: 10
* Fenix version: 80.0.0-beta.6 (Build #2015757457)

**Comment by liuche** [comment] 2020-08-20 02:03
Looks like this isn't registering as a valid url due to the protocol
gopher://uberspace.net/1/~defanor

@rocketsroger is this something that should be related to the protocol changes you were making/GV made?

**Comment by rocketsroger** [comment] 2020-08-20 02:09
> @rocketsroger is this something that should be related to the protocol changes you were making/GV made?

Don't think this is related.  But I can take a look.  I'll self assign.  Thanks,

**Comment by rocketsroger** [comment] 2020-09-14 15:44
This issue is fixed in latest nightly.  Adding QA to verify.  Thanks

**Comment by rocketsroger** [comment] 2020-09-14 15:44
@PurpleCodingWizard  Can you please confirm that this issue is fixed?  Thanks

**Comment by sflorean** [comment] 2020-09-16 11:38
I was able to reproduce the issue on Beta builds and I can confirm that this is fixed on Nightly 9/16 and URL, copy link, share link options are displayed when a long tap is performed. 

Open the link in a new tab and in the private tab options are not displayed. cc @rocketsroger

**Comment by PurpleCodingWizard** [comment] 2020-09-16 12:16
I downloaded nightly and confirm the same^. Copy and share link is available on long press.

**Comment by rocketsroger** [comment] 2020-09-21 17:08
> Open the link in a new tab and in the private tab options are not displayed. This is expected? the other links have all context menu options.
> cc @rocketsroger

Yes, this is expected.  If Fenix does not support the scheme we can't open in our browser.  So all we can do is allow user to open in 3rd party app (if an app is installed), copy link or share link.

**Comment by rocketsroger** [comment] 2020-09-21 17:08
Closing this issue since we've confirmed that Nightly is working as expected now.  Thanks for your help confirming!

**Closed by rocketsroger** 2020-09-21 17:08 UTC
Labels: Feature:ContextMenu, b:web-content, 🐞 bug
