### ISSUE TITLE
Home button opens new tab

### ISSUE THREAD

**Issue by eylenburg** [mozilla-mobile/fenix#27996] opened 2022-11-28 09:46 UTC
### Steps to reproduce

1. Have a tap open
2. Tap on the "Home" button on the left of the address bar

### Expected behaviour

Should show start page with pinned sites etc. 
This should be in the same tab of course, like on Desktop Firefox and in any other browser.

### Actual behaviour

Opens a new tab (which then shows the start page with pinned sites etc) rather than showing the start page in the same tab. The old tab remains so that over time you'll accumulate lots of unneeded old tabs.

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

107.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22062)

**Comment by Cheap-Skate** [comment] 2022-11-29 06:58
Duplicate of #20012 I think

**Comment by boek** [comment] 2023-01-30 23:37
Closing as a dup #20012

**Closed by boek** 2023-01-30 23:37 UTC
Labels: 🐞 bug, needs:triage
