### ISSUE TITLE
[Bug] Frequently used website in new omnibar is not autocompleted like before

### ISSUE THREAD

**Issue by Ruin0x11** [mozilla-mobile/fenix#14299] opened 2020-08-27 15:39 UTC
## Steps to reproduce

1. Open the URL bar.
2. Type 'n'.

### Expected behavior

I frequently use 'news.ycombinator.com'. In the precious release before it autoupdated I'm expec5 'news.ycombinator.com' to be autocompleted when typing 'n'.

### Actual behavior

'netflix.com' is autocompleted even though it shows up nowhere on the frequently used sites list.

![Screenshot_20200827-083409_Firefox_Nightly](https://user-images.githubusercontent.com/6700637/91463860-bc203600-e840-11ea-8a15-e707fa70819b.png)

### Device information

Nightly 200827 07:01 (Build #2015760379)
AC: 57.0.20200826190111, c93fc20af
GV: 81.0a1-20200820093209
AS: 61.0.13

**Comment by s-ankur** [comment] 2020-08-27 15:43
Duplicate of #14212

**Comment by ekager** [comment] 2020-12-18 05:19
Closing as dupe of #14212

**Closed by ekager** 2020-12-18 05:19 UTC
Labels: needs:triage, 🐞 bug
