### ISSUE TITLE
[Bug] Push notifications

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#17237] opened 2020-12-27 03:15 UTC
Can't enable push notifications on Twitter.
![Firefox](https://user-images.githubusercontent.com/23485114/103163106-d548eb80-480e-11eb-9289-6179b8a1fecd.jpg)

**Comment by sheikh-azharuddin** [comment] 2020-12-27 05:04
Works fine here with nightly...please check if you have tweaked some settings (example useragent)

![Screenshot_20201227-103253467](https://user-images.githubusercontent.com/58127841/103164255-ef92c180-482e-11eb-8458-9af8b6fcedde.jpg)

**Comment by ale82to** [comment] 2020-12-29 15:19
I ve reported this issue long ago it 's not a matter of stable /beta nighlty version thing.
after some times something got corrupted with root i have to manually delete push.sqlite under app data folder.
still I don't understand why push notification are so unreliable in fenix, I cannot enable them for both Facebook and Instagram

**Comment by sflorean** [comment] 2020-12-30 16:23
Thanks for reporting! Dupe of #15477.

**Closed by sflorean** 2020-12-30 16:23 UTC
Labels: needs:triage, 🐞 bug
