### ISSUE TITLE
[Bug] Cannot open ZIP file after downloading from Fenix

### ISSUE THREAD

**Issue by kglazko** [mozilla-mobile/fenix#10428] opened 2020-05-06 00:04 UTC
## Steps to reproduce
Download ZIP file
Wait for 'Download Completed' notification 
Press 'Open' button

### Expected behavior
I will be taken to the ZIP file in my Files app

### Actual behavior
I am given a notification that says 'Cannot Open File'

### Device information
* Android device: Pixel 4
* Fenix version: ?

**Comment by kglazko** [comment] 2020-05-11 23:01
Investigation results: Upon checking after-download behaviors, Fennec will open its own about:downloads page and show the Zip file in the list, but will do nothing upon clicking it. Chrome will also show the download in-browser in the downloads section, and upon clicking clicking will show a 'Cannot Open File' snackbar message.

The difference in the interactions is that you can see the Zip has been successfully downloaded, at least shows in the Downloads list- even if you can't open it. That makes it seem more like a limitation of a browser vs. a potential error with a Zip download.

Proposed solutions: 
- Display a different message for Zipfiles in the Snackbar (i.e. Cannot Open Zip Files)
- Display a different message for Zipfiles in the Snackbar and include an 'Open Files' link that will take users to their default File Manager where they can see the downloaded Zip file.
- Implement a visual Download Manager in the future

@vesta0 @liuche @Amejia481

**Comment by vesta0** [comment] 2020-05-12 03:55
Thanks for investigating @kglazko ! Let's go with your first proposed solution for now until we build the Downloads interface #4417

**Comment by kglazko** [comment] 2020-05-21 16:58
See https://github.com/mozilla-mobile/android-components/issues/7064 for PR

**Comment by liuche** [comment] 2020-06-22 19:36
This should have a new string explaining what is/is not possible in the UI.

**Comment by AndiAJ** [comment] 2020-06-23 09:09
Hi, I've just checked this matter on the latest **`Nightly Build 200623 from 6/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

Depending on the device, after tapping "Open":
1. The user isn't re-directed to the stock  File manager, the snackabar with the **Old String is displayed** ("Could not open file") in Fenix
2. The user is redirected to the stock File manager app displaying an error message 
3. If the user has additional File manager apps he will be redirected to those apps and an error message will be displayed

► Video from Google Pixel 3a - Stock File Manager
![20200623-120513](https://user-images.githubusercontent.com/51314259/85384790-2ae3c900-b54a-11ea-9ebb-b7e988d713ae.gif)

► Video from Google Pixel 3a - having another File Manager app installed
![20200623-120430](https://user-images.githubusercontent.com/51314259/85384693-11428180-b54a-11ea-8620-ed5fa57c1860.gif)

► Video from Huawei Mate 20 Lite - Stock File Manager
![20200623-120313](https://user-images.githubusercontent.com/51314259/85384605-fb34c100-b549-11ea-9b3e-135c57a85f8f.gif)

@kglazko - Please review and share your thoughts. ☺️ 
I'll remove the QA needed label until further notice.

**Comment by kglazko** [comment] 2020-06-23 15:20
@Amejia481 Oh no this is definitely not the right behavior- did this get rolled out in AC or something? Or did this AC that had our changes ever land in Fenix?

**Comment by kglazko** [comment] 2020-06-24 20:42
In #7048 @Amejia481 left a comment when merging suggesting we update this string so that translators see it. I didn't notice it and didn't create a follow up PR until now, and I think this is why we may be seeing the issues, especially since new l10n landed recently.

**Comment by flodolo** [comment] 2020-06-26 08:23
> In #7048 @Amejia481 left a comment when merging suggesting we update this string so that translators see it. I didn't notice it and didn't create a follow up PR until now, and I think this is why we may be seeing the issues, especially since new l10n landed recently.

Is that the right PR? I don't see any comment about changing strings in #7048, and as far as I can tell, that string never changed while I was managing merges
https://github.com/kglazko/android-components/commits/38d14391ff03206d944779845ca312e3dec599a8/components/feature/downloads/src/main/res/values/strings.xml

To be clear, it's too late to undo this, but I'd like to understand if I'm missing something.

**Comment by kglazko** [comment] 2020-06-26 17:23
I'm sorry, that is not the right PR, I copy-pasted from Android Components and it linked the wrong issue. https://github.com/mozilla-mobile/android-components/pull/7048 Should be the correct one!

**Comment by flodolo** [comment] 2020-06-26 17:29
> I'm sorry, that is not the right PR, I copy-pasted from Android Components and it linked the wrong issue. [mozilla-mobile/android-components#7048](https://github.com/mozilla-mobile/android-components/pull/7048) Should be the correct one!

Thanks. After looking at the PR, it doesn't seem to me that the string was changed. As far as I can tell, it landed directly with the correct value

```
<string name="mozac_feature_downloads_open_not_supported">No app found to open %1$s files</string>
```

**Comment by AndiAJ** [comment] 2020-07-16 11:10
Hi, I've just re-checked this on the latest **`Nightly Build 200716 from 7/16`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

**Still, the "Could not open file" message is displayed if the File manager can't open zip files.**

►Video
![20200716-135207](https://user-images.githubusercontent.com/51314259/87664396-d6f58a00-c76d-11ea-881d-365ec9743e2d.gif)

@kglazko - Please review and share your thoughts

**Comment by eliserichards** [comment] 2020-11-12 18:44
Hey @AndiAJ, would it be possible to check this one more time on the recent nightly? We're not sure if this is still relevant

**Comment by Amejia481** [comment] 2021-02-01 20:53
Very likely to be fixed after https://github.com/mozilla-mobile/android-components/pull/9558 lands similar to https://github.com/mozilla-mobile/fenix/issues/17502

**Comment by AndiAJ** [comment] 2021-02-18 14:47
Hi, I've re-checked this matter on the latest **Nightly 210218** using the following devices:
• Google Pixel 3a (Android 11)
• OnePlus A3 (Android 6.0.1)

❓ On Both devices, the "Could not open file" message is displayed with the Stock File manager.
► Video

https://user-images.githubusercontent.com/51314259/108372785-d5aaa500-7207-11eb-85b3-0092b87c9f98.mp4

✔️ I've installed the following File managers:
• Google Pixel 3a (Android 11) ➡️  [File Manager](https://play.google.com/store/apps/details?id=com.alphainventor.filemanager&hl=en&gl=US)
• OnePlus A3 (Android 6.0.1) ➡️ [CX File Explorer](https://play.google.com/store/apps/details?id=com.cxinventor.file.explorer&hl=en&gl=US)

In both cases after tapping the "Open" button the .Zip file is properly opened in the file manager.

► Video
• Google Pixel 3a (Android 11) ➡️  File Manager

https://user-images.githubusercontent.com/51314259/108373482-9c266980-7208-11eb-86a0-81dd54fbe0b7.mp4



► Video
• OnePlus A3 (Android 6.0.1) ➡️ CX File Explorer

https://user-images.githubusercontent.com/51314259/108373722-dee84180-7208-11eb-9027-c91101822b6e.mp4

@eliserichards and @Amejia481 - Please review and share your thoughts ☺️

**Comment by Amejia481** [comment] 2021-02-18 15:45
Thanks @AndiAJ, I will take a look.

**Comment by Amejia481** [comment] 2021-02-24 14:59
> Hi, I've re-checked this matter on the latest **Nightly 210218** using the following devices:
> • Google Pixel 3a (Android 11)
> • OnePlus A3 (Android 6.0.1)
> 
> ❓ On Both devices, the "Could not open file" message is displayed with the Stock File manager.
> ► Video
> 20210218_161717.mp4
> 
> ✔️ I've installed the following File managers:
> • Google Pixel 3a (Android 11) ➡️ [File Manager](https://play.google.com/store/apps/details?id=com.alphainventor.filemanager&hl=en&gl=US)
> • OnePlus A3 (Android 6.0.1) ➡️ [CX File Explorer](https://play.google.com/store/apps/details?id=com.cxinventor.file.explorer&hl=en&gl=US)
> 
> In both cases after tapping the "Open" button the .Zip file is properly opened in the file manager.
> 
> ► Video
> • Google Pixel 3a (Android 11) ➡️ File Manager
> 20210218_163102.1.mp4
> 
> ► Video
> • OnePlus A3 (Android 6.0.1) ➡️ CX File Explorer
> 20210218_164539.mp4
> 
> @eliserichards and @Amejia481 - Please review and share your thoughts ☺️

@AndiAJ we put a patch for improving the message when we can't not find an app for opening the file, it should be in master.

**Comment by softvision-miralobontiu** [comment] 2021-02-25 13:16
Hi all!
I downloaded .zip files from multiple websites (thinkbroadband.com/download, learningcontainer.com, and file-examples.com), using a Google Pixel (Android 10), and a Sony Xperia Z5 Premium (Android 7.1.1). 
After tapping on the "Open" button from the "Download complete" snackbar, I was redirected to the stock File manager. 
I got the following error message "The archive is either in unknown format or damaged" on some downloaded files.

Not sure if this is the expected behavior. I'll remove the qa:needed label until further notice.

**Comment by softvision-miralobontiu** [comment] 2021-03-02 12:11
Hi @Amejia481 
I've retested the issue on the 3/2 Nightly build with OnePlus 5T (Android 10) on the https://www.thinkbroadband.com/download, and got this snackbar "No app found to open zip files".
On RC 86.1.1, and beta 87.0.0-beta.2 build, the snackbar message is "Could not open file".

The proposed and agreed upon solution eas to "Display a different message for Zipfiles in the Snackbar (i.e. Cannot Open Zip Files)".

Could you please review, and let us know if the new behavior is the expected one?

**Comment by Amejia481** [comment] 2021-03-02 16:18
We are using the "No app found" message because when we download a file Fenix doesn't open the file itself it delegates to any app available on the device that can open that type of file, and when we can't find an app that is able to open the file we show the message, if later the user installs an app that can handle that type of files we will be able to open the download file via the new app. This message is more clear about why we can't open the file and let users know that have to install an app for handling that type of file as the previous message give the impression that Fenix is the one that can't open the file.

**Comment by softvision-miralobontiu** [comment] 2021-03-03 12:28
Thanks, Arturo!
Indeed, after installing an app that can read the .zip files, tapping the "Open" button, redirects the user to that app.
I'll close this issue

**Closed by softvision-miralobontiu** 2021-03-03 12:28 UTC
Labels: E5, Feature:Download, S3, 🐞 bug
