### ISSUE TITLE
Always allow "add to home screen", even if the site can be installed as a PWA

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/fenix#15450] opened 2020-09-26 10:23 UTC
### What is the user problem or growth opportunity you want to see solved?
I don't always want to install a site as a PWA. Sometimes I just want to pin a link to a soecific page to my Android home screen. Right now, if the site offers itself as a PWA, I am unable to pin a direct link to the current page, as it only offers the "install" option. 

### How do you know that this problem exists today? Why is this important?
Feature was requested at https://www.reddit.com/r/firefox/comments/izi92r/unable_to_add_a_firefox_bookmark_of_a_twitter/

### Who will benefit from it?
Users who only want links to particular pages of certain websites  rather than running the entire site as a PWA.

One option would be to add another link/button in the "install" popup, next to "cancel" and "add automatically" ("add this page", maybe?).

Or leave the "add to home screen" intact as a top level menu item, even if the "install" option is available.

I also thought maybe there could be options to "add to home screen" to the long-press menus for individual top sites, history or bookmark entries, but that feels clunkier to me.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7503)

**Comment by klint** [comment] 2020-09-26 10:45
I fully agree. See  #7758

**Comment by JohannVII** [comment] 2020-09-29 05:52
I endorse adding the "Install" option as an additional option rather than a replacement for linking the page directly in a shortcut.

I also endorse restoring the ability to create launcher shortcuts from e.g. entries in the bookmark list, though that's technically a different issue that should be split into its own tracker entry.

**Comment by klint** [comment] 2020-09-29 07:31
Just a question: could this option be added to the share sheet as yet another way to share a page...by sending it to the launcher? Thus sparing a slot on the 3 dots menu. Like "install" as well. 
But discoverability could be a problem.

**Comment by nudgegoonies** [comment] 2020-10-14 18:34
I fully agree. This is horrible.

**Comment by dyura** [comment] 2021-11-24 16:26
I also  opened a similar issue  #22560 . Definitely on Home screen we need  shortcuts  to specific URLs and not to the home pages. But, we also need to create PWA when needed.

**Comment by plwt** [comment] 2022-01-02 18:44
User feedback: https://support.mozilla.org/en-US/questions/1362939

**Comment by bjweichel** [comment] 2022-01-02 21:54
I wrote the above feedback post.  That being said, there are literally pages of posts listed on the Mozilla Support Forum of people asking why they can't find "Add to Home Screen" for some sites.  9 of the first 10 results to a forum [search](https://support.mozilla.org/en-US/products/mobile#search) for "Add to home screen" are for this problem.  Plus the 6 github issues here.

I wrote my post primarily to clarify what the root cause was for others (I figured there was no solution at present).  I think this should be considered a bigger deal and something badly needing fixed.  I personally spent over an hour trying to understand this and find a workaround, to no avail.

**Comment by davidmegginson** [comment] 2022-01-03 02:09
> I personally spent over an hour trying to understand this and find a workaround, to no avail.

There is a workaround, but it's ugly:

1. Copy the URL you want to save.
2. Put your phone in airplane mode.
3. Paste the URL into the Firefox address bar and try to open you (you'll get a page warning that you have no internet connection, but your URL will still be in the address bar).
4. Choose "Add to Home screen" from the FF menu and do whatever your launcher of choice wants you to do.
5. Go back online (turn off airplane mode).

You should now have an icon on your home screen that opens the link as a web page. Unfortunately, it will be using the default Android icon unless you're have a third-party launcher that lets you assign your own icons to anything (I use Nova Launcher, FWIW).

But the point stands: Firefox users shouldn't need these hacks for such a common task. FF needs to be fixed.

**Comment by baack** [comment] 2022-01-22 13:33
**Who** is that person that decided to remove "Add to Home Screen" function for no actual reason?
This person should be answering every person that faces this issue - a lot of people are desperately trying to add something to home screen and fail. Just because of one stupid decision of this person.

You make remove "Install" feature if you have to choose (ridiculous), but **DO NOT BREAK THINGS that work fine**.

And it's not a feature request, it's a bug that should be fixed.

**Comment by klint** [comment] 2022-01-22 14:13
Yep, the more I use Firefox, the more I feel this is the feature i miss the most. PWA mode gives the user such a poor experience (compared to full fledged Firefox experience of the same web page), that one can wonder why this mode even exists in a first place 😉. 
This issue has been commented for long now, by many people. I don't get it why such an easy and wanted addition to the menu is not done yet. Especially as the code to split the 2 options has been there for a year. 
We are not asking to implement a brand new PDF page generator here, merely to add an obvious menu option.

**Comment by davidmegginson** [comment] 2022-01-22 14:25
@klint - it must be dogma: somebody was really on board with PWAs a decade ago, and can't accept that they didn't end up taking the world by storm. :) As an XML guy, I understand how that feels, but, dear MozTeam, it's time to let go of PWAs and move on.

**Comment by baack** [comment] 2022-01-22 14:41
Thanks @davidmegginson, your workaround worked for me. Unfortunately wrong (default) icon as you predicted. But the link works, thank you.

Another workaround I found is to to click on "Add to Home Screen" before the page loaded completely (during short period of time during load). But it did not work for me, even if I clicked on "Add to Home Screen" menu item during page load - it all was ending as PWA with actually wrong URI.

**Comment by klint** [comment] 2022-01-22 14:44
Actually both modes are useful in their ways. Yet, the most useful remains the normal mode, definitely! 😊

**Comment by klint** [comment] 2022-02-09 10:15
Hi Fenix devs!
Any update or plans regarding this long lasting and wanted request? Why don't you want to unleash the full power of Firefox beyond PWA (which are so limited) ?

**Comment by baack** [comment] 2022-02-18 07:12
Please remove `feature-request` flag. It's not a feature request, it's a regression (a bug when something that worked before stops working).

**Comment by cadeyrn** [comment] 2022-02-18 07:20
> It's not a feature request, it's a regression (a bug when something that worked before stops working).

No, that's not true. Since it's working as intened and implemented it's not a bug but a request for a change.

**Comment by tperich** [comment] 2022-05-06 15:17
Any progress on this? Even the workaround doesn't work for me since FF caches the whole site...

**Comment by klint** [comment] 2022-06-02 12:53
Sigh, Firefox 100 is over and still no shortcuts in addition to PWA :(

**Comment by cpeterso** [comment] 2022-12-24 07:42
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807425

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2022-12-24 07:42 UTC
Labels: feature request 🌟, Feature:HomeScreen, Feature:PWA
