### ISSUE TITLE
[Bug] Firefox Preview attemts to access the camera in the Background

### ISSUE THREAD

**Issue by nical** [mozilla-mobile/fenix#4833] opened 2019-08-20 16:07 UTC
## Steps to reproduce

No idea. My phone (galaxy s9) has a "permission history" feature that pops a notification when an app tries to access certain permissions in the background.
So far the only app that this permission history thing has flagged is Firefox Preview, two times (Aug 19th and Aug 20th) about trying to access the Camera.

### Expected behavior

The browser should not try to access the camera while in the background.

### Actual behavior

It seems it did try to access the camera.

### Device information

* Android device: Samsung Galaxy S9
* Fenix version: 1.2.0 build #12181645

**Comment by petzichen** [comment] 2019-09-06 23:04
I can confirm that.
I have granted the authorization. On my Xiaomi Mi 9T sometimes the pop-up camera (front) is opened and closed again after a page call from another app.

**Comment by kbrosnan** [comment] 2019-09-17 17:47
This is [GV bug 1578073](https://bugzilla.mozilla.org/show_bug.cgi?id=1578073)

**Comment by karlcow** [comment] 2019-12-18 05:36
I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1604700
related to https://github.com/webcompat/web-bugs/issues/46217

**Comment by superlevure** [comment] 2020-03-14 21:29
Same problem on my mi 9T

**Comment by ekager** [comment] 2020-04-17 21:47
Looks like https://bugzilla.mozilla.org/show_bug.cgi?id=1578073 has landed. Let's retest in Nightly.

**Comment by Diana-Rus** [comment] 2020-04-22 14:41
Hi, i managed to reproduced the issue with Samsung Galaxy S9 (Android 8) on Firefox Preview Release 1.3.0 Build (Build #12271643)
1. I had the "App permission monitor" enabled and for Firefox Preview to be registered in the permission history .
2. The androids camera settings for firefox was allowed.
3. I accessed webcamtest.com and put Firefox in background until site loaded.

**Samsung Galaxy S9 - GIF - Firefox Preview RC 1.3.0 - build #12271643**
![20200422-161903](https://user-images.githubusercontent.com/49859863/79988023-d58e2b80-84b6-11ea-82a1-39d36e494c59.gif)

**Samsung Galaxy S9 - GIF - Firefox Preview Nightly 4/22 build #21130610**
![20200422-163234](https://user-images.githubusercontent.com/49859863/79988953-f1460180-84b7-11ea-8c86-f4363decdcbd.gif)

**Note:**
-  The actual access for camera on Firefox RC is not given for the site. The user manually needs to give access by in browser pop up notification for the visited site.
-  For Firefox Preview Nightly it can be seen from GIF that the "Permission history" only displayed the Firefox Preview RC notifications.

@petzichen  and @superlevure  are you able to check on the latest Firefox Preview Nightly whether the camera pops up? 
At the moment i do not have at hand a device with pop up camera.

**Comment by kbrosnan** [comment] 2020-06-25 17:56
This was fixed by BZ-1578073. The webcam test site is actively using the camera which is expected behavior. 

If you still see Firefox using the camera on versions that use Geckoview 75+ please open a new issue.

**Closed by kbrosnan** 2020-06-25 17:56 UTC
Labels: P3, needs:gv, 🐞 bug, 🙅 waiting
