### ISSUE TITLE
[Bug] File downloads don't work when adblocker is installed

### ISSUE THREAD

**Issue by AquaBytez** [mozilla-mobile/fenix#2639] opened 2019-05-19 18:44 UTC
While in private browsing mode, no downloads work. I'll get the prompt to download the file, but no visual feedback whatsoever after the download "starts". After a while, a message from the Android Download Manager will pop up, as follows 
!["<Download Unsuccessful>"](https://user-images.githubusercontent.com/6633649/57986557-4d044100-7a44-11e9-86c4-61815364f215.jpg)

Fenix has the storage permission, and is allowed to install apks from unknown sources just in case.

For reference, my device is a OnePlus 6T A6013, running OxygenOS 9.0.13

**Comment by vesta0** [comment] 2019-06-03 17:45
@AquaBytez I can't reproduce this. Would you please provide more information on file types you were trying to download or exact steps to reproduce? Thanks!

**Comment by AquaBytez** [comment] 2019-06-03 17:56
After a lot of digging, this seems to be caused by my AdBlockers, in my case, [Blokada](https://blokada.org/). As soon as the adblocker is disabled, downloads work again. The following blocklists are in use: **Energized Blu**, **Goodbye Ads by Jerryn70** and **Dan Pollock's hosts file**.

This is a Fenix bug, as having the Adblocker enabled doesn't prevent other browsers from downloading files

**Comment by vesta0** [comment] 2019-06-03 20:15
@AquaBytez does this only impact download in private browsing? If it's caused by adblockers then it should impact all downloads I think.

**Comment by AquaBytez** [comment] 2019-06-04 01:19
I'm not able to reliably reproduce it outside of private browsing, but after a lot more testing, it seems like it also affects normal sessions. 

If there's any way I can produce a log to make this easier to track down, let me know how to do so.

**Comment by vesta0** [comment] 2019-07-16 16:31
@AquaBytez please let us know if you are still experiencing this issue. I suspect that only downloads on authenticated sites are still an issue (currently being addressed).

**Comment by AquaBytez** [comment] 2019-07-16 16:50
Updated 15 minutes ago. Downloads still don't work.

**Comment by Coch3se** [comment] 2019-07-16 16:53
I just tried to download an APK from GitHub that was giving me problems and it is working now.

**Comment by vesta0** [comment] 2019-07-16 17:06
@AquaBytez what types of downloads still don't work? Could you provide steps to reproduce?

**Comment by AquaBytez** [comment] 2019-07-16 17:09
![Download Unsuccesul](https://imgur.com/a/ve3Mfq6)

**Comment by vesta0** [comment] 2019-07-16 17:11
@AquaBytez it would be super helpful if you could provide an example of a site that you are downloading from, and the file type.

**Comment by AquaBytez** [comment] 2019-07-16 17:15
This doesn't work https://download.servo.org trying to download the android build results in the image above

**Comment by Coch3se** [comment] 2019-07-16 17:28
@AquaBytez I was able to download your file https://imgur.com/qDJmK6t

**Comment by AquaBytez** [comment] 2019-07-16 17:33
That's odd. Could you try this setup? https://imgur.com/a/bC1EXJQ

Because as soon as I turn off the app, everything works just fine.

**Comment by Coch3se** [comment] 2019-07-16 17:51
@AquaBytez I can't download the file if I enable "Goodbye Ads" or "Dan Pollocks". With only "Energized Blue" enabled I have no problem with the download.

**Comment by AquaBytez** [comment] 2019-07-16 17:53
I wonder which host is being blocked that prevents downloads from working.... At least we were able to narrow it down to those two lits.

**Comment by Coch3se** [comment] 2019-07-16 22:03
Just got an update to both Blokada and Fenix and downloads are back to download unsuccessful after `5 minutes

**Comment by siddhugolu** [comment] 2019-08-03 15:10
Experiencing the same issue, even when the AdBlock is off. While trying to download any file, whether in a private or a normal session (for example, through Firefox Send), it prompts asking whether I want to download or not, and immediately shows in the notification bar that the download was unsuccessful. Storage and Install from unknown sources permissions are given.

Platform: Android 9, Mi A1
AdBlock: [https://www.f-droid.org/en/packages/org.jak_linux.dns66/](url)

**Comment by jimbo1qaz** [comment] 2019-08-04 01:05
I think this is a bug on Android. https://github.com/julian-klode/dns66/issues/31

Try excluding Firefox Fenix or Downloads Manager from your adblocker app.

**Comment by siddhugolu** [comment] 2019-08-04 05:53
Experiencing the same behavior after excluding Firefox Focus and Preview from the AdBlock list. Crucially, I was able to download other files (for example, from Google Drive, or Yandex drive), but it's files from Firefox Send that's causing the issue.

I have installed the latest Firefox Preview that is available on the play store. This is definitely an unusual behavior. If no one else is able to reproduce this issue, I'll have to resign myself to thinking this has something to do with my phone itself.

**Comment by jimbo1qaz** [comment] 2019-08-04 05:55
@siddhugolu Firefox Send not working is a separate bug: https://github.com/mozilla-mobile/fenix/issues/3336

**Comment by siddhugolu** [comment] 2019-08-04 08:19
@jimbo1qaz Oh! Sorry for spamming then. I should've searched differently.

**Comment by NotWoods** [comment] 2019-08-04 20:50
@siddhugolu Could you check to see if you can download the file using [Reference Browser](https://github.com/mozilla-mobile/reference-browser#test-channel-on-google-play-store)? It uses the new Gecko downloading system currently in Fenix master.

**Comment by siddhugolu** [comment] 2019-08-05 06:03
@NotWoods I was able to download the file using Reference Browser, but it downloaded a 12 byte garbage file (with the original filename), as reported in bug: #3336

**Comment by NotWoods** [comment] 2019-08-05 13:27
Does that happen on other sites or just Firefox Send? If it's just Send we can close this issue since #3336 is tracking that.

**Comment by siddhugolu** [comment] 2019-08-05 18:31
@NotWoods I'm facing the download problem only with Firefox Send. Not sure whether OP is still facing the issue or not.

**Comment by NotWoods** [comment] 2019-08-05 21:56
@AquaBytez Can you also try to reproduce on Reference Browser?

**Comment by pocmo** [comment] 2019-09-16 17:19
QA: Can this still be reproduced? We recently changed the download manager implementation.

**Comment by sv-ohorvath** [comment] 2019-09-19 14:29
> my device is a OnePlus 6T A6013, running OxygenOS 9.0.13

I cannot reproduce on a Galaxy S8, Android 9 device, with Blokada on. But given that the reporter has a custom OS it might be different. 
@AquaBytez Please let us know if you still have this issue, if not we can close this.

**Comment by matfantinel** [comment] 2019-09-29 16:52
I am still having this issue, on a Galaxy S10e with Android 9. Had the same on my previous Xperia XZ1c.

File in question was from Android Filehost.

**Comment by jerome-tgl** [comment] 2020-01-17 09:49
I can download files on OnePlus 6T with Android 10, Firefox Preview 3.0.2 and Blokada 4.4.3, but the process is quite buggy.

Here's what happens when I tap a link to file on a webpage.

  ↓ Download (`file_size`)
  `file_name`
             [Download]

Tapping the download

  ✔ Download complete (`file_size`)
               [Open]

NB: file_name and file_size is "null" if the file happens to be an image (and if the image is saved via a long press > download image)

Tapping the Open briefly displays an empty file preview (titled "null") for PDF. For images, the native Android modal shows up and let me select an image app. Selecting the OnePlus gallery will open it but fails to display the image (Photo loading impossible).

But all files are actually saved into my Download directory, somehow.

**Comment by Amejia481** [comment] 2021-02-01 20:58
We did some improvements to our download stack, please take a look in the latest [Firefox nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) and if the issue still persist please feel free to reopen.

**Closed by Amejia481** 2021-02-01 20:58 UTC
Labels: Feature:Download, P3, S4, needs:investigation, 🐞 bug
