### ISSUE TITLE
Undo closing tab notice hovers over last tab, stopping the user from closing multiple tabs

### ISSUE THREAD

**Issue by ubalklen** [mozilla-mobile/fenix#20677] opened 2021-08-04 16:55 UTC
I often open multiple tabs, only to close many of them some time later. Unfortunately, if the tab I want to close has reached the bottom of the tab view, I have to wait few seconds to be able to close it because the "undo closing tab" notice hovers over the tab's X mark.

![undo](https://user-images.githubusercontent.com/42127323/128221625-c0d7125c-4423-493f-a28f-cc8f6dc7f75a.jpeg)

This is specially annoying if multiple tabs have to be closed because I have to wait the banner to move away for each tab.

**Comment by jonalmeida** [comment] 2021-08-05 06:04
Duplicate of #19166

**Closed by jonalmeida** 2021-08-05 06:04 UTC
Labels: needs:triage
