### ISSUE TITLE
FNX3-16300 ⁃ [Bug] Tapping on location bar shows option to search current URL in search engine, visit current URL 2x

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2406] opened 2019-05-10 10:10 UTC
## Steps to reproduce
1. open any page in fenix, like https://www.cnbc.com/2019/05/09/huawei-cfo-seeks-to-end-extradition-case-citing-trump-comments.html
1. tap location bar

### Expected behavior
no suggestions appear, or a single suggestion like  #2368 

### Actual behavior
The first suggestion I see is the URL that I am on, along with a search symbol and my selected search engine. 

![signal-attachment-2019-05-10-060435](https://user-images.githubusercontent.com/152493/57519900-5d9d1480-72ea-11e9-867e-b098ee3745cf.png)

I also see the page I am on listed twice -- once with the page title, as the title, and once with the url as the title without the https:// protocol listed. 

Tapping on the entry that lists my search engine does not take me to a search for that URL (as expected given the search engine label), but takes me to my current URL.

This is different from #2393 because I didn't type anything - just tapped the location bar. 

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by pocmo** [comment] 2019-05-22 13:16
A fix for this landed in AC and should get into Fenix with the next snapshot + Nightly.

**Comment by pocmo** [comment] 2019-05-27 15:29
This was fixed in AC and the new behavior can be observed in RB. However the Fenix implementation seems to differ and the change doesn't affect it.

**Comment by pocmo** [comment] 2019-05-29 20:05
I have to toss this back to the Fenix team (Unassigned and removed from AC board): The issue is fixed in AC and the `AwesomeBarFeature`. Unfortunately Fenix doesn't use that. The fix in the feature was straightforward: Only call `onInputChanged()` after a call to `onInputStarted()`. Locally I added those as events to Fenix and then tried to do the same via the `SearchState`. However multiple things are updating the toolbar URL triggering all kinds of events multiple times. 🤷‍♂

**Comment by mcarare** [comment] 2020-01-06 13:20
For QA: I think this was fixed, and I cannot reproduce it anymore. Can you please check? TY!

**Comment by softvision-miralobontiu** [comment] 2020-01-06 14:58
Verified that by tapping on the search bar, after a page is loaded, it does not display any suggestions.
Tested on the latest Nightly build from 01/06 (#20060606) with Google Pixel (Android 10), Google Pixel 3 (Android 10), HTC Desire 820 (Android 6.0.1).

**Closed** 2020-08-12 17:45 UTC
Labels: Feature:Search, P2, S1, eng:qa:verified, 🐞 bug
