### ISSUE TITLE
[Bug] The "+" sign next to the address/search box is redundant

### ISSUE THREAD

**Issue by concastinator** [mozilla-mobile/fenix#6627] opened 2019-11-15 16:11 UTC
## Steps to reproduce

Launch the browser. Notice that you can input web addresses and search terms by tapping either on the address/search box, or on the neighbouring "+" ("plus") sign. This is a redundancy that costs space at the bottom of the browser.

### Expected behavior

There should be a single way to open a new tab.

### Actual behavior

There are two ways of opening a new tab. Worse, they are immediately close to each other, duplicating functionality at no advantage to the user.

### Possible solution

The "+" button should be either simply removed, or replaced with a more useful one (for instance, with the mask symbolizing private browsing, which would allow to free some UI space at the top).

### Device information

* Android device: Nokia 5 (model TA-1024) with up-to-date Android 9 (Android One program)
* Fenix version: 191115 06:01 (build 13190607)

**Comment by cadeyrn** [comment] 2019-11-15 16:41
Duplicate of #6409

**Comment by abodea** [comment] 2019-11-15 17:34
Thank you for adding this issue @concastinator!
Based on the comment above from @cadeyrn I will close this issue as a duplicate.

**Closed by abodea** 2019-11-15 17:34 UTC
Labels: 🐞 bug
