### ISSUE TITLE
FNX-12414 ⁃ [Bug] Fenix Freezes after closing Tabs

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#11472] opened 2020-06-11 14:56 UTC
There's still a way to get the app to freeze and arrive at the first two screens shown in issue #10239.

## Steps to reproduce
1. Completely exti Fenix. (not running in the background 
1. Open a link from outside Fenix. (for example, you could either click "open with" in some other app or use your launcher... if it has the functionality to do so.
1. Click back (on that android-bottom-row) or close the tab manually. Close all other tabs as well, private ones as well as regular ones.
1. Click back yet again to close the app. It'll keep running in the background as most apps do.
1. Reopen Fenix by clicking on it in the Task-Manager-like view. Klicking on the Fenix-icon does NOT trigger the glitch. Maybe because it somehow resets the app.
1. Enjoy the frozen screen.

### Expected behavior 
No freeze. The same behaviour as if you opened the tab (from No. 2) from within Fenix.

### Device information
* Android device: Samsung Galaxy S9
* Fenix version: 5.1.1

**Comment by Mugurell** [comment] 2020-06-17 17:23
Thanks!
This does seem like a pretty common scenario that definitely needs to be fixed.
![WhiteScreenFenix](https://user-images.githubusercontent.com/11428869/84911230-921ffa00-b0c0-11ea-81c7-373d081ff968.gif)

**Comment by Mugurell** [comment] 2020-06-17 17:23
Seems like this is reproducing since at least January.

**Comment by Mugurell** [comment] 2020-06-23 09:22
This should be fixed by the patch from #9144.

**Comment by AndiAJ** [comment] 2020-06-23 10:48
Hi, **verified as fixed** on the latest **`Nightly Build 200623 from 6/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200623-134317](https://user-images.githubusercontent.com/51314259/85395031-33db9700-b558-11ea-8db6-f94404ddd01d.gif)

**Closed** 2020-08-11 04:05 UTC
Labels: S2, eng:qa:verified, 🐞 bug
