### ISSUE TITLE
FNX3-14673 ⁃ PlacesConnectionBusy: Error executing SQL: database is locked

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#1148] opened 2019-03-22 20:45 UTC
https://sentry.prod.mozaws.net/operations/fenix/issues/5376638/

```
PlacesConnectionBusy: Error executing SQL: database is locked
    at org.mozilla.places.RustError.intoException(RustError.kt:6)
    at org.mozilla.places.WritablePlacesConnection.noteObservation(PlacesConnection.kt:7)
    at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordVisit$2.invoke(PlacesHistoryStorage.kt:17)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:2)
    at kotlinx.coroutines.BuildersKt.withContext
...
(8 additional frame(s) were not displayed)

Error executing SQL: database is locked
```

**Comment by kbrosnan** [comment] 2019-03-22 20:46
Looks to be an [A-C issue](https://github.com/mozilla-mobile/android-components/issues/2499). Sadly Sentry does not make it possible to reference bugs outside your Project.

**Comment by jonalmeida** [comment] 2019-03-25 18:21
Different entry path, but seems to the same root cause: https://sentry.prod.mozaws.net/operations/fenix/issues/5378329/?query=user:%22id:android:78790e1fff632b88%22

This was a bug mconley was seeing on his device as well.

**Comment by bifleming** [comment] 2019-06-03 17:09
@grigoryk do you know if this is still happening?

**Comment by grigoryk** [comment] 2019-06-03 18:01
Still happening as of a-s 0.29.0 (https://sentry.prod.mozaws.net/operations/fenix/issues/5815037/?query=is:unresolved%20busy) - but quite infrequently.

**Comment by grigoryk** [comment] 2019-06-03 18:14
Issues supposed to be fixed in a-s 0.30.0, so let's wait and see how that version does in Sentry.

**Comment by jdragojevic** [comment] 2019-06-05 16:47
There are still some instances of the crash with 0.30.0: https://sentry.prod.mozaws.net/operations/fenix/issues/5408227/events/30792083/ 

cc @thomcc

**Comment by jdragojevic** [comment] 2019-06-07 14:08
Application services team is tracking this issue in our repository as: https://github.com/mozilla/application-services/issues/1230.

In yesterday's planning meeting https://github.com/mozilla/application-services/issues/1230 was moved into the upcoming sprint and the approach is to add some retry logic with backoff. 

A-S ask for Fenix team is to implement *not* crashing when the PlacesConnectionBusy is encountered, but to continue reporting the error instances to Sentry so we get a sense of the frequency.

**Comment by pocmo** [comment] 2019-07-23 17:42
Sentry issue: [FENIX-NIGHTLY-89](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6035107/)

**Comment by kbrosnan** [comment] 2019-08-19 19:17
This has been resolved.

**Comment by jdragojevic** [comment] 2020-08-11 03:19
Reopened via unito

**Closed by jdragojevic** 2020-08-11 03:19 UTC
Labels: Feature:History, Feature:Sync, a-s, b:crash, needs:ac, 🐞 bug, 🙅 waiting
