### ISSUE TITLE
[Bug] White line at the top of every webpage

### ISSUE THREAD

**Issue by SlowNicoFish** [mozilla-mobile/fenix#17417] opened 2021-01-12 15:54 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open any webpage
2. Scroll down a little bit
3. Scroll up to the top of the webpage again
4. Spot the white line
![Screenshot_20210112-164855](https://user-images.githubusercontent.com/19305293/104338447-cfcdef80-54f6-11eb-91d1-9d3503047af9.jpg)

### Expected behavior
No white line at top

### Actual behavior
There is a white line at the top of every webpage

### Device information

* Android device: Oneplus 8T
* Fenix version: 84.1.4

**Comment by kbrosnan** [comment] 2021-01-12 16:53
Do you have tabs on top?

**Comment by SlowNicoFish** [comment] 2021-01-12 16:56
Nope, on the bottom.
And it seems to be showing the background color of the page I'm on. So for example now that I'm on githubs dark mode page it shows a line with the color of githubs background

**Comment by LaurentiuApahideanSV** [comment] 2021-01-14 10:50
I can confirm the issue is reproducible on Firefox Preview Nighlty 210114.

### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)

**Comment by ddarfantasy** [comment] 2021-01-25 00:27
Is it a dup of #10598 ?

**Comment by Mugurell** [comment] 2021-02-03 19:55
Thank you for the report!
Seems indeed to be the same issue as https://github.com/mozilla-mobile/fenix/issues/10598. Closing as such.

**Closed by Mugurell** 2021-02-03 19:55 UTC
Labels: S4, 🐞 bug
