### ISSUE TITLE
[Bug] Reader view gets re-rendered with default appearance settings after a while when switching tabs

### ISSUE THREAD

**Issue by korbel** [mozilla-mobile/fenix#17865] opened 2021-02-05 18:10 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Open a page in reader view
2. Make sure your appearance settings differs for the default ones (font, color, size)
3. Keep it open
4. Switch tabs, browse the internet (not sure what triggers re-rendering, open lots of tabs, wait a few minutes, close them, play around)
5. Switch back to the reader view tab
6. See how it gets re-rendered with the default appearance settings
7. Refresh the page to fix appearance

### Expected behavior

Whenever reader view gets re-rendered, it should use the user selected settings instead of the default appearance settings.

### Actual behavior

Sometimes (not sure what triggers it), reader view gets re-rendered with the default appearance settings when switching tabs or applications back and forth on the device. Refreshing the page gets the appearance back, but it may lose track of the scrolling.

[Here is a screen recording of the bug](https://youtu.be/Mj-eD-ezj9Q) 

### Device information

* Device vendor / model and Android version: OnePlus 6 with Android 10 (OxygenOS 10.3.8)
* Firefox for Android version: 85.1.1 (Build #2015789955)

**Comment by korbel** [comment] 2021-02-05 18:42
It seems it does the same if I don't do anything just wait 1 minute on another tab. It might be timed.

**Comment by AndiAJ** [comment] 2021-02-17 09:12
**Reproducible** on **`86.1.0 RC1`** using a OnePlus A3 (Android 6.0.1)

**Comment by Frivolous2** [comment] 2021-02-27 22:32
Same on 86.1.1. Don't even have to wait a minute, happens instantly once I switch to a tab by sliding on address bar and then sliding back.

**Comment by lobontiumira** [comment] 2021-04-12 13:19
Reproducible on Beta 88.0.0-beta.6 with OnePlus 5T (Android 10).

**Comment by korbel** [comment] 2021-04-12 18:34
v84.0.0-beta.1 seems to be the version introduced this bug, I could not reproduce it on v83.1.0. (someone please confirm it!)
Android components was upgraded here from v63.0.9 to v67.0.2.
Diff: https://github.com/mozilla-mobile/android-components/compare/v63.0.9...v67.0.2

It contains a fix for issue https://github.com/mozilla-mobile/android-components/issues/8868 which may or may not have caused this. I have not idea what I am looking at though.

I hope it helps.

**Comment by korbel** [comment] 2021-04-13 12:19
I looked into it a bit more. This is indeed a bug in [mozilla-mobile/android-components](https://github.com/mozilla-mobile/android-components).
The config used by the reader view is a WeakReference which gets garbage collected after a while (thus the 1 minute wait for me). This is to prevent memory leak I believe. Before v84 it wasn't an issue because the re-rendering process (is it even necessary?) was just ignored when the config was missing. This behavior however was changed with this commit: https://github.com/mozilla-mobile/android-components/commit/bd8f1128d648b059997eddbbd5a7ca2c5a517114#diff-e2be446bd5ff1905ad70d697b45a145dd42fb5920473e78661e19d913df36a43L275-R265
Now it will use the default settings if it can't find the config.

**Comment by csadilek** [comment] 2021-04-22 18:26
This should be fixed now in latest Nightly (210422 17:00). I can no longer repro there.

**Comment by korbel** [comment] 2021-04-22 21:25
I couldn't reproduce the issue either in today's nightly.

**Comment by csadilek** [comment] 2021-04-22 22:27
@AndiAJ @lobontiumira Can you verify please when you get a chance? Thanks!

**Comment by lobontiumira** [comment] 2021-04-23 08:00
I could not reproduce this anymore on the 4/23 Nightly build, nor on Beta 89.0.0-beta.1 build.
Tested with OnePlus 5T (Android 10).

**Closed by lobontiumira** 2021-04-23 08:00 UTC
Labels: Feature:ReaderMode, S2, eng:qa:needed, 🐞 bug

**Comment by JPLeBreton** [comment] 2021-06-03 19:27
This just happened to me again in the 89.1.1 release I just updated from the Play store.

**Comment by korbel** [comment] 2021-06-03 19:46
Afaik the fix will land in v90

**Comment by csadilek** [comment] 2021-06-03 19:48
Yes, Thanks @korbel. @JPLeBreton the fix for this landed in 90 and is now in beta.
