### ISSUE TITLE
[Bug] New Search Experience: The autofill arrow does nothing

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13758] opened 2020-08-12 13:34 UTC
## Steps to reproduce
Enable new search experience
open the toolbar and type something
click on the arrow next to the suggestions   

### Expected behavior
the autofill sugesstion is filled into the input of the toolbar
### Actual behavior
Nothing
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly
Related  #13052

**Comment by cadeyrn** [comment] 2020-08-12 15:00
I guess you use the "New Search Experience"? Because it should work with the default experience. I can confirm that it's broken with the new (still in progress) experience.

**Comment by s-ankur** [comment] 2020-08-12 15:11
Thanks @cadeyrn, I've edited the issue now. Apparently the secret settings remain applied even after the secret settings disappears from the settings menu (after an update for example)

**Comment by liuche** [comment] 2020-08-28 22:34
Is this still an issue now that Search is fully landed?

**Comment by cadeyrn** [comment] 2020-08-28 22:38
> Is this still an issue now that Search is fully landed?

The background color of the autofill button has a different color when pressing (grey in old search experience, purple in the new search experience) but it works now.

**Comment by liuche** [comment] 2020-08-31 20:46
I'm going to close this issue then. Revisiting the colors would be a separate bug.

**Closed by liuche** 2020-08-31 20:46 UTC
Labels: Feature:Search, 🐞 bug

**Comment by s-ankur** [comment] 2020-08-31 20:51
Autofilling search engines autofills their titles now. Is there an issue for this?

**Comment by liuche** [comment] 2020-09-01 00:31
yes! it's #12641
