### ISSUE TITLE
[Bug] Long pressing an image in anonymous view crashes the browser

### ISSUE THREAD

**Issue by Asmial** [mozilla-mobile/fenix#14364] opened 2020-08-28 14:34 UTC
## Steps to reproduce

1. Search for any image in startpage.com
2. Click on any image
3. Click on "view image anonymously"
4. Long press the image

### Expected behavior
The long press context menu of any image should appear with options such as save image or copy image.

### Actual behavior
Firefox locks itself until app is closed from the multi task screen.

### Device information

* Android device: SM-G965F (Samsung Galaxy S9 plus 64GB)
* Fenix version: 79.0.5 (Build #2015758619)
* Android version: 10 (Stock OS)
* Security patch: August 1st, 2020

**Comment by hwinnemoe** [comment] 2020-08-28 14:52
Duplicate of #13027

**Closed** 2020-08-28 15:40 UTC
Labels: needs:triage, 🐞 bug
