### ISSUE TITLE
full screen videos not displaying properly

### ISSUE THREAD

**Issue by sfinlayson126** [mozilla-mobile/fenix#24193] opened 2022-03-10 19:29 UTC
On Android the video doesn't always show up properly in full screen. The video with be shifted down and to the right so part of the video isn't visible.

Actual video:
![Screenshot_20220310-084209](https://user-images.githubusercontent.com/77430559/157739706-b15e338f-7eb3-4fbe-b0b6-7c143ea05dba.png)

Full screen:
![Screenshot_20220310-084203](https://user-images.githubusercontent.com/77430559/157739744-2a0880d4-b213-4077-af0c-2d45fc2fe482.png)

**Comment by LaurentiuApahideanSV** [comment] 2022-03-17 10:21
I can confirm the issue is reproducible on Nightly 2022-03-17. The issue has also been reported here: https://github.com/mozilla-mobile/fenix/issues/8252. I will close this issue as it will be handled there.
### Device used:
- Google Pixel 6 (Android 12)

**Closed by LaurentiuApahideanSV** 2022-03-17 10:21 UTC
Labels: needs:triage
