### ISSUE TITLE
Reload without cache

### ISSUE THREAD

**Issue by vbrandl** [mozilla-mobile/fenix#14181] opened 2020-08-25 19:14 UTC
### What is the user problem or growth opportunity you want to see solved?

Reload a page while ignoring all caching headers.

### How do you know that this problem exists today? Why is this important?

In the old design, pressing and holding the reload button would reload with caching disabled. Everytime a user experiences caching issues, this would help

### Who will benefit from it?

Everyone used to the old UI

**Comment by person808** [comment] 2020-08-25 19:19
This is implemented in beta I believe. Duplicate of https://github.com/mozilla-mobile/fenix/issues/2681

**Closed** 2020-08-26 00:17 UTC
Labels: needs:triage
