### ISSUE TITLE
[Bug] A selected tab can be reselected when the title changes

### ISSUE THREAD

**Issue by TrianguloY** [mozilla-mobile/fenix#14954] opened 2020-09-10 16:08 UTC
This is a minor bug, but easy to perform on slow devices / slow internet.

## Steps to reproduce

1) Open a page
2) As fast as possible, open the tabs tray (press the [1] button)
3) As fast as possible, long tap the current tab to select it.
4) Wait for the page to update (either while being loaded, or with the final title)

### Expected behavior

The page keeps being selected

### Actual behavior

The page is unselected, but the selection remains as '1'. You can select it again, and increase the selection number to 2 or even more.

![Multimedia1 (2)](https://user-images.githubusercontent.com/10616202/92758871-7199d000-f38f-11ea-91c8-fcce8e148fd8.gif)

## Fast device

If you have a fast device and fast internet connection, so fast that when you open the tabs tray the page is already opened, you won't be able to reproduce this bug with the previous steps (or if you are using an emulator, but there you can set the network type to HSDPA or slower). However the bug also happens if the page's title is changed using 'document.title', so yu can try this:

1) Open this testing page: https://trianguloy.github.io/githubPages/javascriptEval/javascriptEval.html?setInterval(()=%3Edocument.title=Math.random(),1000)
2) Press run.
3) Open the tabs tray, note the changing title of the tab.
4) Select the tab, and then select again, and again, and again...

![Multimedia1](https://user-images.githubusercontent.com/10616202/92758891-78c0de00-f38f-11ea-9518-e37f8e2f43b9.gif)

### Device information

* Android device: Tested on a Nexus 5X, android 8.1.0, also on an 8.1.0 emulator
* Fenix version: Build #2015763059 (also happens on previous versions)

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-6713)

**Comment by TrianguloY** [comment] 2020-09-10 16:27
Append: This can also lead to a 'ghost' selection if the tab is closed while selected: testing link: https://trianguloy.github.io/githubPages/javascriptEval/javascriptEval.html?a=window.open()%0AsetInterval(()=%3Ea.close(),5000)
In the original steps, if you try to save the 'ghost' selected tab on a collection, the current tab is saved normally. On the closed tab, if you try to save the nonexistent selected tab, nothing happens (pressing 'save' does nothing) even if you select other tabs.

**Comment by Alexandru2909** [comment] 2022-01-26 11:53
I can still reproduce this issue on Samsung Note 10(Android 12). The problem seems to be that when checking if the item is selected, the `SelectionHolder` holds a version of the tab with different `TabSessionState.content`. The `TabSessionState.id` seems to be the same in this case and could be used to better verify the selected/deselected state of the tab.

**Comment by SoftVision-LorandJanos** [comment] 2022-05-18 08:41
This issue is no longer reproducible with the latest Nightly 102.0a1 (2022-05-18) build.
Device used: google Pixel 4 (Android 12).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-05-18 08:41 UTC
Labels: 🐞 bug, eng:ready, eng:qa:needed, Feature:Tabs, help wanted, pin
