### ISSUE TITLE
Media Controls Not Appearing on Game Videos

### ISSUE THREAD

**Issue by joel-madero** [mozilla-mobile/fenix#21302] opened 2021-09-15 02:19 UTC
Repro steps:

(1) Go to MLB.com
(2) click on any game that played or is currently playing
Example: https://www.mlb.com/gameday/padres-vs-giants/2021/09/14/632491#game_state=live,game_tab=,game=632491
(3) click on "video" on right side of screen
(4) click any video listed

Observed: during commercial intro you'll see mute/unmute icon, once actual content starts controls no longer accessible. Clicking (pushing) on video doesn't make them appear resulting in inability to unmute, pause, etc...

Expected: controls should pop up when video is "clicked" on.

Note: chrome and opera both work as expected. Also, interestingly enough controls do appear on videos directly on "video" page of MLB.com itself (https://www.mlb.com/video).

**Comment by LaurentiuApahideanSV** [comment] 2021-09-16 16:31
I can confirm the issue is reproducible on Firefox Preview 93.0.0-beta.2 and Nightly 2021-09-16. Possibly related to https://github.com/mozilla-mobile/fenix/issues/14730.

### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by SoftVision-LorandJanos** [comment] 2022-03-17 15:45
I've managed to reproduce this issue on the Nightly version it was tested on (2021-09-16).
This issue is no longer reproducible on the latest Nightly 100.0a1 (2022-03-17).
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-03-17 15:45 UTC
Labels: 🐞 bug, Feature:Media, wontfix, qa-triaged

**Comment by joel-madero** [comment] 2022-05-18 01:32
This is still a problem with 100.2.0.
