### ISSUE TITLE
[Bug]: Firefox for Android doesn't show search suggestion with custom search engine

### ISSUE THREAD

**Issue by TobiPeterG** [mozilla-mobile/fenix#21622] opened 2021-10-01 09:48 UTC
### Steps to reproduce

1. add custom search engine to firefox on Android (like Brave search)
2. select the search engine / set it to default
3. attempt a search
(e.g. search for "Angel", no suggestions will be shown, Desktop shows e.g. "Angelina Jolie")

### Expected behaviour

Search suggestions should be displayed when using a custom search engine

### Actual behaviour

No search suggestions are displayed when using a custom search engine

### Device name

Xiaomi Mi 9

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

### Additional information

The issue doesn't exist on Firefox Desktop; here, search suggestions work normally, even with custom search engines.

**Comment by kbrosnan** [comment] 2021-10-01 15:21
Duplicate of https://github.com/mozilla-mobile/fenix/issues/7866

**Closed by kbrosnan** 2021-10-01 15:21 UTC
Labels: 🐞 bug, needs:triage
