### ISSUE TITLE
[Bug] about: scheme is marked as insecure

### ISSUE THREAD

**Issue by dvalter** [mozilla-mobile/fenix#5171] opened 2019-09-08 18:57 UTC
## Steps to reproduce
Navigate to about:config
### Expected behavior
"Secure connection" badge would show generic web (Fennec) or Firefox (Desktop) logo; Expanded info would be "It's a secure Firefox page"
### Actual behavior
"Secure connection" badge shows "Insecure connection" icon and text
### Device information

* Android device: aarch64; Android 8.1
* Fenix version: 69.0 (Google Play), 71.0a1-20190509094317

**Comment by NotWoods** [comment] 2019-09-09 17:32
Kind of a duplicate of #5002 

We'll add a third "default" state for about pages and loading pages. See mozilla-mobile/android-components#4156

**Closed by NotWoods** 2019-09-09 17:32 UTC
Labels: 🐞 bug

**Comment by dvalter** [comment] 2019-09-09 19:48
> We'll add a third "default" state for about pages and loading pages. See [mozilla-mobile/android-components#4156](https://github.com/mozilla-mobile/android-components/issues/4156)

Does not seem to be a complete solution as it differs from both desktop and Fennec for no reason. As I've mentioned above, Fennec and Firefox Desktop uses the same text to highlight the fact that about: pages are secure belongs to Firefox
