### ISSUE TITLE
Please bring back the option to have only selected shortcuts (not history!) on the new tab page

### ISSUE THREAD

**Issue by alexolog** [mozilla-mobile/fenix#25969] opened 2022-07-11 01:55 UTC
### What is the user problem or growth opportunity you want to see solved?
Users want the option to see only their selected shortcuts on the new tab page instead of their recent history, to avoid clutter and privacy issues.
This option used to be available until it was removed in #23159

### How do you know that this problem exists today? Why is this important?
Users keep complaining.
See for example: #25739, #25330, #25254, #25163, #24536, #24506, #25141 (and possibly others)
Also see the overwhelmingly negative response on https://connect.mozilla.org/t5/discussions/android-v100-history-update/m-p/6616

### Who will benefit from it?
Users that want a quick and easy way to access a small selection of shortcuts without having their recent history displayed.
Users that like choice.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20962)

**Comment by kbrosnan** [comment] 2022-07-11 06:07
This has been discussed. UX is evaluating some possible changes but for right now the decision stands. This is a dupe of the other bugs mentioned.

**Closed by kbrosnan** 2022-07-11 06:07 UTC
Labels: needs:triage

**Comment by alexolog** [comment] 2022-07-11 14:26
What is the point of closing the bugs with "please log a feature request" (https://github.com/mozilla-mobile/fenix/issues/25163#issuecomment-1123193993), then immediately closing it when logged?
