### ISSUE TITLE
FNX2-15102 ⁃ [Bug] Addons language don't change when browser's language changes

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#12238] opened 2020-07-03 10:36 UTC
## Steps to reproduce
1. Install an addon which is translated. (E.g ublock Origin)
1. Change browser's language to a language supported by this addon. (You can pick English (as old language) and French (as new language) with ublock origin).
    1. Expected behavior
The addon is in the new browser's language (French)
    1. Actual behavior
The addon's languages is still the old browser's language (English).
    1. Device information

* Android device: Pocophone f1, android 9
* Fenix version:  nightly 200703 06:16

workaround: go to app info, kill firefox, reopen firefox

**Comment by Amejia481** [comment] 2020-07-03 12:58
Same as https://github.com/mozilla-mobile/fenix/issues/8188

**Comment by Amejia481** [comment] 2020-07-03 13:01
There is not much that we can do at the moment as mentioned on https://github.com/mozilla-mobile/fenix/issues/8188#issuecomment-588300299, the fix will required further changes in the add-on itself and possibly [i18n api](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n), the same behaviour can be seen on Fennec too.

**Comment by sflorean** [comment] 2020-07-20 14:23
Closing as a dupe of #8188.

**Closed** 2020-08-20 17:55 UTC
Labels: Feature:WebExtensions, 🐞 bug
