### ISSUE TITLE
Preventing default for click events on GeckoView browsers prevents <select> options from opening.

### ISSUE THREAD

**Issue by wisniewskit** [mozilla-mobile/fenix#6169] opened 2019-10-21 20:49 UTC
If a `<select>` element has related `click` events `preventDefault`ed, GeckoView browsers do not display the options UI (tested on Fenix and ReferenceBrowser), whereas other browsers still show the option-selecting UI (including Firefox desktop and Fennec)

This is causing webcompat issues, breaking at least the state/province selector on Decipher Inc surveys, as per https://webcompat.com/issues/40397

Here is a trivial reduced test-case:
```
<!DOCTYPE html>
<html>  
<head>      
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<select onclick="event.preventDefault()">
  <option>1</option>
  <option>2</option>
</select>
</body>
</html>
```

**Comment by miketaylr** [comment] 2019-10-22 14:11
cc @vesta0

**Comment by wisniewskit** [comment] 2019-10-22 14:47
Just in case, note that returning `false` from the handler also prevents default and causes this glitch, not just explicitly calling `clickEvent.preventDefault()` (as per the Chaussea issue referenced above).

**Comment by Amejia481** [comment] 2019-10-22 15:15
I can reproduce this issue on the latest GeckoView example app. I opened bug for the GeckoView team to take a look at it https://bugzilla.mozilla.org/show_bug.cgi?id=1590435

**Comment by cpeterso** [comment] 2019-11-12 17:19
The GV bug fix landed today and should be available in tomorrow's GV 72 Nightly build:

https://bugzilla.mozilla.org/show_bug.cgi?id=1590435#c9

**Comment by ekager** [comment] 2020-12-11 05:35
Closing because the GV bug landed over a year ago :) 
Please open a new issue if this is still a problem!

**Closed by ekager** 2020-12-11 05:35 UTC
Labels: P2, b:webcompat, 🐞 bug
