### ISSUE TITLE
FNX-487 ⁃ [Bug] Flash of black when leaving GV engine

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#1901] opened 2019-04-22 20:58 UTC
## Dependencies
* [ ] Maybe [Graphics bug](
https://bugzilla.mozilla.org/show_bug.cgi?id=1588581#a1431651_430528) in GV/Gecko

## Steps to reproduce
* Load a page
* Press tabs button

### Expected behavior
Tabs screen appears smoothly (with animation?)

### Actual behavior
There's a flash of black (or white, depending on Light/Dark mode) and the tabs screen suddenly appears

This also happens when creating a new tab from an open tab (i.e. load page, click 3-dot, select "New tab")

### Next steps
GV doesn't think this is a Gecko problem, but rather a problem in Fenix not destroying the SurfaceView in time. So the next steps here are to verify that we're handling the SurfaceView correctly.

```I'm not convinced the black flash when navigating away is graphics' fault. We set everything inactive in GeckoView.Display.onSurfaceDestroyed(), which I presume happens when the SurfaceView is destroyed by navigating away from the browser fragment. No rendering can occur after this point. I'm not sure what we could do, when we don't have a surface to render in to. Isn't the problem that there is a delay between the SurfaceView being destroyed and the TabsFragment being created and shown? So the android UI displays black during this time.```

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1917

- - -
**Edit by @sblatz**

### Acceptance Criteria
* I do not see a black/white flash when moving from browser -> Settings
* I do not see a black/white flash when moving from browser -> Library
* I do not see a black/white flash when moving from browser -> Fenix Home
(black/white flash depending on if user is in Dark/Light Mode)

**Comment by yoasif** [comment] 2019-04-27 05:40
I noticed this on a Moto G today. Screencast attached. 


[recording_20190426_232847.zip](https://github.com/mozilla-mobile/fenix/files/3123527/recording_20190426_232847.zip)

**Comment by sv-ohorvath** [comment] 2019-05-23 13:07
Still reproducing on 5/23 build. Pixel and Galaxy Note 8.

**Comment by sblatz** [comment] 2019-09-27 15:50
The only way for us to handle this is to "screenshot" the GV and animate with that. 
We should consider handling the bugs surrounding this all at one time since there's a few mentioning it.

**Comment by sblatz** [comment] 2019-10-01 17:46
I will add a Gif to demo. 

I will link to the other related issues since it will be the same underlying fix 😄

**Comment by sblatz** [comment] 2019-10-01 19:55
Basically the same issue as https://github.com/mozilla-mobile/fenix/issues/4708 but lets make sure that animation looks good too (navigate from browser -> home).

**Comment by sv-ohorvath** [comment] 2019-10-10 10:41
Verified as fixed with a Pixel 3(Android 9), Htc Desire 820 (Android 6.0.1), Huawei P20 lite (Android 9), on the latest Nightly 10/10.

**Comment by ekager** [comment] 2019-10-14 18:58
We have to remove the fix that replaced the view with the engineView thumbnail  for now because of #5984 ->
WR doesn't implement the thumbnail callback so this would hang and never navigate from the buttons.
I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1588581 for the GV team to look into since this is reproducible on RB, Fenix, and samples-browser

**Comment by cpeterso** [comment] 2019-10-31 18:20
The GV bug has been added to GV's November sprint.

https://bugzilla.mozilla.org/show_bug.cgi?id=1588581#a1431651_430528

**Comment by fluffyemily** [comment] 2019-12-05 15:41
Moved to the Graphics team

**Comment by liuche** [comment] 2020-01-06 19:31
There have been improvements on the Graphics side, but now this is [bounced back](https://bugzilla.mozilla.org/show_bug.cgi?id=1588581#c10) to Fenix/AC.

`Isn't the problem that there is a delay between the SurfaceView being destroyed and the TabsFragment being created and shown? So the android UI displays black during this time.`

Also can't be reproed by Jamie. I'm going to add a qa-needed label here.

QA, could you check to see if this is still happening in Fenix, the behavior that is in the **Acceptance Criteria** in comment 0? And check for black OR white flashes (even though the comment only says black)>

**Comment by ekager** [comment] 2020-01-06 19:37
I left an intermediate fix in that hides the GV and instead just shows the "background" which made the transition a bit less jarring. In light mode, it will be white, dark mode will be black

**Comment by AndiAJ** [comment] 2020-01-07 10:04
Hi, as per @liuche 's [comment](https://github.com/mozilla-mobile/fenix/issues/1901#issuecomment-571278895) I've just checked this matter on the latest **Nightly Build #20070606 from 01/07** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)

The **problem is still there**, on the other hand, @ekager 's  intermediate fix seems to be working. ☺️ 

<details>
    <summary>Dark theme videos (Dropdown)</summary>

► Moving from browser -> Fenix Home
![20200107_111951](https://user-images.githubusercontent.com/51314259/71886054-3c741880-3144-11ea-8210-26fabd1cf823.gif)

► Moving from browser -> Library
![20200109_041640](https://user-images.githubusercontent.com/51314259/71886241-8826c200-3144-11ea-81b4-ae51aa65ac17.gif)

► Moving from browser -> Settings
![20200109_041741](https://user-images.githubusercontent.com/51314259/71886333-adb3cb80-3144-11ea-83ea-4a68101fd8ec.gif)


</details>


<details>
    <summary>Light theme videos (Dropdown)</summary>

► Moving from browser -> Fenix Home
![20200109_041921](https://user-images.githubusercontent.com/51314259/71886904-ab9e3c80-3145-11ea-8c93-8d5801a31c99.gif)

► Moving from browser -> Library
![20200109_041941](https://user-images.githubusercontent.com/51314259/71886596-2b77d700-3145-11ea-883e-27ccac07bf0e.gif)

► Moving from browser -> Settings
![20200109_042100](https://user-images.githubusercontent.com/51314259/71886685-4fd3b380-3145-11ea-9113-f79017113b86.gif)

</details>

I'll remove the QA needed label until further notice.

**Comment by liuche** [comment] 2020-01-13 22:45
GV doesn't think this is a Gecko problem, but rather a problem in Fenix not destroying the SurfaceView in time. So the next steps here are to verify that we're handling the SurfaceView correctly.

```I'm not convinced the black flash when navigating away is graphics' fault. We set everything inactive in GeckoView.Display.onSurfaceDestroyed(), which I presume happens when the SurfaceView is destroyed by navigating away from the browser fragment. No rendering can occur after this point. I'm not sure what we could do, when we don't have a surface to render in to. Isn't the problem that there is a delay between the SurfaceView being destroyed and the TabsFragment being created and shown? So the android UI displays black during this time.```

**Comment by liuche** [comment] 2020-01-14 23:54
@vesta0 should we move this into the polish sprint? I think this popped back into the sprint because it was reopened but wasn't explicitly added and has just been a holdover, but I don't think it's as important as some of the other work that's going on. Can we swap this out for #255 ?

**Comment by sblatz** [comment] 2020-01-16 17:38
For what it's worth, this sounds like a [known issue](https://stackoverflow.com/a/12636285) with `SurfaceViews`. It seems like using a `TextureView` may fix this, but that's something the GV team would have to decide if it's worth changing as I'm assuming that would require a lot of work. Though, it sounds like in https://bugzilla.mozilla.org/show_bug.cgi?id=1594860 GV may be moving away from a SurfaceView which would also probably fix this.

> but better still would be if the SurfaceView wasn't destroyed until the next fragment is ready?

Jamie's comment from the Bugzilla sounds like an interesting option. I'm going to timebox investigating whether or not we can hold onto the fragment until the transition happens. Again, this doesn't seem *ideal* and is a temporary solution as it's a bit hacky to hold that around.

**Comment by sblatz** [comment] 2020-01-16 17:56
Some notes:
1. We cannot just delay a call to `onDestroy` as an exception gets thrown: `did not call through to super.onDestroy()`
2. The navigation library we're using does not allow for us to hold on to that other fragment (it must be destroyed and restored when we navigate back.) This is by design.

My only other thought here is to take a screenshot (not with the gecko function). I'm going to try that now.

**Comment by sblatz** [comment] 2020-01-16 19:09
I've spent a bit more time on this. It looks like GV does not allow a bitmap to be drawn from its view (which is probably why they have their own `captureThumbnail`) 

I really don't think we have any other choice here than the interim solution that @ekager provided.

I would bounce this back to GV. I think either a switch from SurfaceView -> another view OR implementing `captureThumbnail` for users without WebRender.

**Comment by sblatz** [comment] 2020-01-16 20:13
Sounds like the captureThumbnail API has been updated so I can fix this!

**Comment by sblatz** [comment] 2020-01-21 17:34
Looks like there is still a GV bug. If a user presses "home" while the tab is still loading (engineView is completely white) captureThumbnail will never get launched. I'm filing now.

**Comment by AndiAJ** [comment] 2020-02-25 12:55
Hi, **verified as fixed** on the latest **`Nightly Build #20560606 from 02/25`** using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

<details>
    <summary>Dark theme time lapsed videos (Dropdown)</summary>

► Moving from browser -> Fenix Home
![20200225-121346](https://user-images.githubusercontent.com/51314259/75248563-103c5600-57dd-11ea-8be3-9042d96a48e0.gif)

► Moving from browser -> Library
![20200225-121457](https://user-images.githubusercontent.com/51314259/75248689-47126c00-57dd-11ea-8d45-88146c86adea.gif)

► Moving from browser -> Settings
![20200225-121612](https://user-images.githubusercontent.com/51314259/75248731-627d7700-57dd-11ea-8cc9-f9a2693e9910.gif)


</details>


<details>
    <summary>Light theme time lapsed videos (Dropdown)</summary>

► Moving from browser -> Fenix Home
![20200225-122056](https://user-images.githubusercontent.com/51314259/75248805-8d67cb00-57dd-11ea-98d1-9327301dc41a.gif)

► Moving from browser -> Library
![20200225-122146](https://user-images.githubusercontent.com/51314259/75248880-b8eab580-57dd-11ea-9f62-aa006676e55c.gif)

► Moving from browser -> Settings
![20200225-122219](https://user-images.githubusercontent.com/51314259/75248940-d6b81a80-57dd-11ea-8b2e-2a8aafd2438d.gif)


</details>

**Closed** 2020-08-11 13:18 UTC
Labels: E5, Feature:HomeScreen, P2, eng:qa:verified, needs:gv, 🐞 bug
