### ISSUE TITLE
FNX-12546 ⁃ [Bug]The Add-on install cancellation button isn't responsive

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11588] opened 2020-06-15 08:29 UTC
## Steps to reproduce
1. Open the Add-ons manager
1. Tap the Install button
1. After the instalaltion and verification begins tap the **cancel** button (after approx 1 second) 

### Expected behavior
The installation of the Add-ons should be cancelled 

### Actual behavior
The Add-ons are installed anyway

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly build 200615 from 6/15

### Notes
❗ **M3s also affected**
► Video
![20200615-111950](https://user-images.githubusercontent.com/51314259/84635115-70294a80-aefb-11ea-8d80-dce52be7ac4b.gif)

**Comment by csadilek** [comment] 2020-06-15 13:26
@AndiAJ I will move to this to A-C. Unfortunately, there isn't much we can do here. Not all steps of add-on installation are cancelable, and the API currently doesn't tell us which steps are / are not. Most importantly, the download step is cancelable with this. Towards the end of installation you may hit a point where it's too late to cancel (as in your video above), but this seems acceptable to me.

/cc @agi90

**Comment by agi90** [comment] 2020-06-15 15:26
Yep especially if you've downloaded the addon before, the download step (the only one cancelable) takes very little.

**Comment by csadilek** [comment] 2020-06-15 15:30
OK, I am closing this, as it's all by design. We can open a feature request for finer grained cancellation if we this affects users.

**Comment by agi90** [comment] 2020-06-15 17:33
Yeah please open a bug if you need a "onCancelable" notification.

**Closed** 2020-08-11 04:26 UTC
Labels: Feature:WebExtensions, S2, 🐞 bug
