### ISSUE TITLE
[Bug] Failed to query add-ons when custom add-ons are loaded

### ISSUE THREAD

**Issue by quadriflax** [mozilla-mobile/fenix#15529] opened 2020-09-29 10:24 UTC
## Steps to reproduce
Attempt to load add-ons.

### Expected behavior
List of add-ons displays.

### Actual behavior
Error failed to query add-ons displays, no add-ons listed.

### Device information

* Android device: Samsung Tab A (2019) with Android 10.
* Fenix version: 
Nightly 200929 05:08 (Build #2015766697)
AC: 61.0.20200925190057, 01306f87c
GV: 83.0a1-20200922094538
AS: 63.0.0

Same problem as https://github.com/mozilla-mobile/fenix/issues/12399; only appears to happen if custom add-on list is added in settings. When custom list is removed, it appears to work again as expected.

**Comment by cadeyrn** [comment] 2020-09-29 10:33
I cannot reproduce with default settings. What do you mean by "custom add-on list is added in settings"?

**Comment by serovar** [comment] 2020-09-29 11:05
I have the same issue.

> What do you mean by "custom add-on list is added in settings"?

Starting from the latest Nightly, when you activate the debug menu ("Secret Settings") by tapping the Firefox logo in Settings --> About Firefox Nightly, you have the option to add your own custom Add-on collection.


![Screenshot_20200929-130327](https://user-images.githubusercontent.com/6732420/94550700-7518cc80-0254-11eb-9c00-34a52e87d333.png)
![Screenshot_20200929-130502](https://user-images.githubusercontent.com/6732420/94550704-7649f980-0254-11eb-8bba-7ef5bd2a98d4.png)

**Comment by cadeyrn** [comment] 2020-09-29 11:20
Maybe I have to wait for the next update, in my version from the Google Play Store it's not yet included. Thanks.

**Comment by serovar** [comment] 2020-09-29 11:29
You can download it from [taskcluster ](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.latest)if you don't want to wait.

**Comment by joelocandol** [comment] 2020-09-29 12:53
![Screenshot_20200929-085105](https://user-images.githubusercontent.com/59028737/94560811-2279e900-0231-11eb-9bf4-108bdb894a3c.png)

Same problem after active custom add-ons list 
Android 7.0 Oukitel c5

**Comment by Amejia481** [comment] 2020-09-29 13:36
@quadriflax  what values for `userID` and `collection name` are you inputting int the dialog? Could you try by using 16314372 myCollection respectively?

**Comment by quadriflax** [comment] 2020-09-29 13:41
> @quadriflax what values for `userID` and `collection name` are you inputting int the dialog? Could you try by using 16314372 myCollection respectively?

Tried the above, same results.

**Comment by serovar** [comment] 2020-09-29 13:42
Just tried them, same issue.

**Comment by Amejia481** [comment] 2020-09-29 14:02
Sorry my bad, the right values are `16314372` `test`. This message show up when the values are not correct.

**Comment by Amejia481** [comment] 2020-09-29 14:03
By the way, if you save with both values empty it should reset to the default values.

**Comment by serovar** [comment] 2020-09-29 14:13
> 
> 
> Sorry my bad, the right values are `16314372` `test`. This message show up when the values are not correct.

It works (I see LASER CAT)

**Comment by Amejia481** [comment] 2020-09-29 14:15
Then I think we can close this issue, feel free to reopen it need :)
![image](https://user-images.githubusercontent.com/773158/94570228-a1285380-023c-11eb-87c8-15f35a170541.png)

**Comment by quadriflax** [comment] 2020-09-29 14:15
Yay! Works here, too. I was able to load my list. I entered my user name, not the ID number on the account. But I was able to load new addons. Thanks!

**Closed by Amejia481** 2020-09-29 14:15 UTC
Labels: needs:triage, 🐞 bug

**Comment by serovar** [comment] 2020-09-29 14:17
@quadriflax How did you get your User ID and collection name? If I go to my "Android" collection on AMO, I get this link: https://addons.mozilla.org/en-US/firefox/collections/13213756/android/, so I supposed my ID was 13213756 and the name "android" (but I also tried "Android"), but it did not work.

**Comment by quadriflax** [comment] 2020-09-29 14:24
That should be your ID (it shows on the left of your screen, too, under "Firefox user"). Not sure why it won't work for you, but when I click your link it's not loading and says I can't perform that action at the top, so maybe something is wonky with your list/account. Try making a new list and see if that works.

**Comment by serovar** [comment] 2020-09-29 14:25
I tried setting up a new "test" collection and it works... strange, but thanks!

**Comment by andornaut** [comment] 2020-09-30 15:49
In my testing, the ID and collection name must match their respective values in the Collection URL, not the display name. 

https://addons.mozilla.org/en-US/firefox/collections/<USER ID>/COLLECTION NAME>/

So, for example, given a collection named "Abc Def", you must enter "Abc-Def" as the "Collection name" in the "Add-ons" screen.

IMHO this is sufficiently non-obvious that this issue (or another) should be opened to improve the user experience.

**Comment by Poopooracoocoo** [comment] 2020-09-30 15:57
Mozilla ought to add that to the blog post! https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by dhowe** [comment] 2021-05-16 09:40
The suggestion regarding spaces from @andornaut fixed this issue for me. But it should probably not be closed, at least until there is decent documentation.

**Comment by Poopooracoocoo** [comment] 2021-05-16 11:27
bro does ff for android STILL not have add-ons????? it's been a whole ass year

**Comment by bonkmaykrQ** [comment] 2021-11-24 16:17
> In my testing I found that the ID and collection name must match their respective values in the Collection URL, not the display name.
> 
> `https://addons.mozilla.org/en-US/firefox/collections/<USER ID>/<COLLECTION NAME>/`
> 
> So, for example, given a collection named "Abc Def", you must enter "Abc-Def" (note the dash) as the "Collection name" in the "Add-ons" screen.
> 
> IMHO this is sufficiently non-obvious that this issue (or another) should be opened to improve the user experience.

This fixed my problem. For whatever reason the collection's name in the URL was just my username... I guess because that's what I set it to. So it wants your URL, not the actual name.

The placeholder text needs to be changed to make this less confusing.

**Comment by jsshwqz** [comment] 2022-09-03 05:28
这个问题我今天也遇到了，目前暂未解决

**Comment by jsshwqz** [comment] 2022-09-03 05:30
> > 在我的测试我发现这个ID和集合名称，必须符合他们各自的价值中收集的网址，不显示的名字。 
> > `https://addons.mozilla.org/en-US/firefox/collections/<USER ID>/<COLLECTION NAME>/`
> > 因此，例如，给定一个集合名为"Abc Def"，你必须进入"Abc清"(注意：破折号)作为"集合名称"中的"附加"屏幕。 
> > 恕我直言，这是充分的非显而易见，这个问题(或另一)应当开放，以提高用户的经验。
> 
> 这一定是我的问题。 无论出于何种原因收集的名字在URL只是我的用户名...我猜因为这是我设置了它。 因此，它想要你的网址，而非实际名称。
> 
> 该文本需要改变使这个小混淆。

**Comment by SD777x** [comment] 2022-10-03 15:04
> 



> In my testing I found that the ID and collection name must match their respective values in the Collection URL, not the display name.
> 
> `https://addons.mozilla.org/en-US/firefox/collections/<USER ID>/<COLLECTION NAME>/`
> 
> So, for example, given a collection named "Abc Def", you must enter "Abc-Def" (note the dash) as the "Collection name" in the "Add-ons" screen.
> 
> IMHO this is sufficiently non-obvious that this issue (or another) should be opened to improve the user experience.

Thank you!  I was going nuts  trying to resolve this.  FF devs should definitely update with this information.
