### ISSUE TITLE
Ensure we schedule local push notifications at a normal time

### ISSUE THREAD

**Issue by jgiglio** [mozilla-mobile/fenix#20887] opened 2021-08-17 10:37 UTC
I had all notification categories on silent, I believe.  New categories were apparently created for "marketing" , which sent me a noisy push at 2am to tell me Firefox wasn't default.  Not cool.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17613)

**Comment by cadeyrn** [comment] 2021-08-17 11:24
>  which sent me a noisy push at 2am to tell me Firefox wasn't default. Not cool.

Well, you are responsible for whether your smartphone makes noise or not, no? I am sure that Firefox is not the only app that sends notifications and somewhere in the world it's always 2am…

**Comment by Nickoriginal** [comment] 2021-08-18 15:21
Your issue have not sence. Looking at the its title, you want that Firefox didn't send notifications to you at 2 a.m? I recommend to you to disable "Marketing" notifications manually if you want.
However, these recently appeared notifications can be frequent for some users and there is no way to stop their indignation except disabling them or reducing their frequency to unacceptable.

**Comment by Nickoriginal** [comment] 2021-08-18 15:22
https://github.com/mozilla-mobile/fenix/issues/20429

**Comment by jgiglio** [comment] 2021-08-18 20:29
> > which sent me a noisy push at 2am to tell me Firefox wasn't default. Not cool.
> 
> Well, you are responsible for whether your smartphone makes noise or not, no? I am sure that Firefox is not the only app that sends notifications and somewhere in the world it's always 2am…

I did silence every category of notification for Firefox.  You all added a new one (marketing) which defaults to making noise.  Then you sent push messages in the middle of the night.  Surely you can add logic to not send pointless "marketing" push messages at 2am.

**Comment by interfect** [comment] 2021-11-19 00:16
The bug here is that this line sends the notification with `IMPORTANCE_DEFAULT`:

https://github.com/mozilla-mobile/fenix/blob/6a3adb5aeba976a7146eb96a2ef3794fae909304/app/src/main/java/org/mozilla/fenix/onboarding/DefaultBrowserNotificationWorker.kt#L91

That's [documented to make noise](https://developer.android.com/reference/android/app/NotificationManager#IMPORTANCE_DEFAULT), which is not appropriate for a marketing nag that the user can deal with when they're good and ready. *Especially* if I'm [reading this](https://github.com/mozilla-mobile/fenix/blob/6a3adb5aeba976a7146eb96a2ef3794fae909304/app/src/main/java/org/mozilla/fenix/onboarding/DefaultBrowserNotificationWorker.kt#L107) [code right](https://github.com/mozilla-mobile/fenix/blob/6a3adb5aeba976a7146eb96a2ef3794fae909304/app/src/main/java/org/mozilla/fenix/onboarding/DefaultBrowserNotificationWorker.kt#L121-L123) and the notification just kicks off 24 hours after... something. Possibly after app update? Which is likely to happen automatically at night?

Anyway, this needs to be sent as [`IMPORTANCE_LOW`](https://developer.android.com/reference/android/app/NotificationManager#IMPORTANCE_LOW) so the user will see it in the shade, but won't get a beep at some arbitrary time to wake them up so they can change their default browser.

**Comment by Nickoriginal** [comment] 2021-11-25 21:19
It sounds good. What I've also noticed: you cannot disable marketing notification or silent it until you receive it at the first time with noise and inconvenience.

**Comment by interfect** [comment] 2022-10-30 21:25
It looks like this should probably be closed as won't-fix; https://github.com/mozilla-mobile/fenix/pull/22501#issuecomment-1290852866 notes that the current behavior is as designed.

**Closed** 2023-01-30 18:50 UTC
Labels: needs:triage
