### ISSUE TITLE
Support content:// scheme 

### ISSUE THREAD

**Issue by nextLane** [mozilla-mobile/fenix#14745] opened 2020-09-04 19:46 UTC
## Steps to reproduce
Try opening a content:// URL in latest versions of Firefox, firefox is unable to open that. Previous versions of firefox could open it.
### Expected behavior
It should open.
### Actual behavior
It's not opened, no action taken.
### Device information

* Android device: yes
* Fenix version: 80.1.2

**Comment by sunasing** [comment] 2020-09-21 13:43
Checking to see if we have any udpate on this issue?

**Comment by amedyne** [comment] 2020-12-10 19:56
Duplicate of #1327

**Closed by amedyne** 2020-12-10 19:56 UTC
Labels: Feature:Browsing, feature request 🌟, 🐞 bug
