### ISSUE TITLE
variable position of new tabs

### ISSUE THREAD

**Issue by ubrainlessgit** [mozilla-mobile/fenix#17998] opened 2021-02-15 05:53 UTC
Firefox beta for android

 if u open a new tab it opens at the very bottom of the list of tabs( tabs in lust view. I havent checked in grid view) . However,

1.  if u close a tab and then immediately press undo, it reopens at the very top. If u have several tabs
( eg 12)open u arent even aware that it reopened at the top 

2. Opening a tab from collections opens it at the very top, in contrast to opening a new tab in general which opens at the bottom of the list

Firefox beta on android ,Samsung galaxy s7

86.0.0-beta.4 (Build #2015792683)
AC: 72.0.11, 70a065e35
GV: 86.0-20210209185733
AS: 67.2.0

**Comment by Dunexus** [comment] 2021-02-15 09:31
The first part is already covered by https://github.com/mozilla-mobile/fenix/issues/10986. I can't remember of an open issue about the second part so maybe repurpose this issue to cover this part.

**Comment by lobontiumira** [comment] 2021-03-31 13:09
Thank you for the report @ubrainlessgit!

The first issue is a duplicate of #10986, as Dunexus mentioned.
The second one is covered by #18210.

Therefore, I will close this issue.

**Closed by lobontiumira** 2021-03-31 13:09 UTC
Labels: Feature:Tabs, 🐞 bug
