### ISSUE TITLE
FNX-5332 ⁃ [Bug] White dot in the main menu as Private tab icon

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1916] opened 2019-04-23 08:04 UTC
## Steps to reproduce
1. Go to PB. Open a tab.
1. Open the main menu, check the Private tab icon
    1. Expected behavior
The mask icon.
    1. Actual behavior
A dot.
    1. Device information

* Android device: Pixel
* Fenix version: 4/22

**Comment by sblatz** [comment] 2019-04-23 19:53
This should be fixed.

**Comment by bsurd** [comment] 2019-04-24 09:06
This has been verified, the issue is no longer reproducible.

**Closed** 2020-08-11 13:20 UTC
Labels: eng:qa:verified, 🐞 bug
