### ISSUE TITLE
[Bug] about:config does not work

### ISSUE THREAD

**Issue by lineinthesand** [mozilla-mobile/fenix#13927] opened 2020-08-19 16:31 UTC
## Steps to reproduce
Type about:config into the address bar

### Expected behavior
Configuration options should open

### Actual behavior
Configuration options are not displayed

### Device information
Android oreo
Firefox mobile version 79

**Comment by cadeyrn** [comment] 2020-08-19 16:39
It's not a bug. It's intended that about:config is only enabled in pre release builds.
Duplicate of #7865.

**Closed** 2020-08-20 01:11 UTC
Labels: needs:triage, 🐞 bug
