### ISSUE TITLE
Undo button annoyingly placed so it obstructs last open tabs

### ISSUE THREAD

**Issue by aha999** [mozilla-mobile/fenix#20554] opened 2021-07-28 16:24 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
When you have multiple tabs open in Android Firefox and by default the dropdown tab card style of tabs, if you close a tab, an undo button appears, that's great, but it's just above the last open tab.

So if you want to close multiple last tabs, you can't close a last tab repeadetly before waiting for Undo button to disappear.

### How do you know that this problem exists today? Why is this important?
This problem is present on current versions of Android devices at least, and it's important because it gets really annoying extremely fast, if you want to close some tabs...
### Who will benefit from it?
Any user that has multiple tabs open, and the Undo button is obstructing the last open tab for opening or closing it.

**Comment by marcel263** [comment] 2021-07-29 12:53
#19166

**Comment by jonalmeida** [comment] 2021-08-02 03:27
Duplicate of #19166

**Closed by jonalmeida** 2021-08-02 03:27 UTC
Labels: needs:triage
