### ISSUE TITLE
enable auto fill for http auth dialog 

### ISSUE THREAD

**Issue by fichtennadel** [mozilla-mobile/fenix#13941] opened 2020-08-19 21:35 UTC
## User Story
- As a user, I want the http auth dialog to be auto fill enabled, so I can use a 3rd party password manager app to fill it. 

## Dependencies
- none known, related but not duplicated by #9773 (which is about html forms, not the http auth dialog) 

### Acceptance Criteria
- Android auto fill is offered for http auth dialog and fills user and password 

### Examples

https://jigsaw.w3.org/HTTP/Basic/

Fennec (ok):
![Screenshot_20200819-232253_Firefox](https://user-images.githubusercontent.com/2324670/90691776-34e92600-e274-11ea-9690-63ae0ec7336d.jpg)

Fenix (missing):
![Screenshot_20200819-232316_Firefox Nightly](https://user-images.githubusercontent.com/2324670/90691828-50543100-e274-11ea-84f9-14a644aff351.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5159)

**Comment by fichtennadel** [comment] 2020-08-20 09:12
maybe related to https://github.com/mozilla-mobile/fenix/issues/13961
(no duplicate, #13961 is about auto fill within FF, this one is about from 3rd party)

**Comment by athompson673** [comment] 2020-09-27 18:32
I am also experiencing the same issue. After the update, my credentials for HTTP basic auth were still saved, and visible in the list of saved logins, but would not auto-fill nor give a prompt to auto-fill once I begin typing. Re-installing firefox did not solve the issue. Firefox 81.1.1 (Build #2015764547) Android 10 (OxygenOS 10.0.0)

**Comment by rzubek** [comment] 2020-10-22 15:42
@kbrosnan should this be a bug / regression, not a feature request? 
This used to work in versions prior to 80.x (see https://github.com/mozilla-mobile/fenix/issues/15306)

**Comment by athompson673** [comment] 2020-10-25 02:47
@kbrosnan I really don't think tagging this issue with "feature request" is appropriate. This has been basic functionality for a long time. It is a clear and reproducible regression of basic functionality. I find it hard to believe this was an intended regression, and must now be justified as a "new" feature to get it added back in. Marking it as such in the bug tracker limits the visibility of the bug making it less likely to be fixed.

**Comment by tosiara** [comment] 2020-10-25 10:27
I also agree that this is a regression

**Comment by cadeyrn** [comment] 2020-10-25 10:46
A not yet implemented feature is a feature request and not a regression and since Fenix is a new product it's correct to label it as feature request. It's a technical term and only relevant for the developers. From the user's POV it doesn't matter at all how you call it and I don't think it's useful to discuss the label because it doesn't change the fact that it doesn't work in the current version and that you want to see this implemented. These comments only cause notifcation spam but doesn not accelerate the development of this feature.

**Comment by Hubfront** [comment] 2020-10-30 21:44
It's a bug, if the internal password manager can't handle basic authentification.

**Comment by Hubfront** [comment] 2020-11-17 16:32
Support for basic authentification by the internal password manager has recently been given priority P2 in the bugzilla for firefox. Its obviously not the highest priority, so its unclear, when this bug will be fixed.

So maybe until then, maybe the autofill could be opened for a 3rd party password manager like bitwarden? Bitwarden seems to support basic auth.

**Comment by kw217** [comment] 2020-12-17 21:35
Is this a duplicate of https://github.com/mozilla-mobile/fenix/issues/8642 ?

**Comment by kacnje** [comment] 2021-01-26 09:28
This behavior is really annoying. I hope developers will correct it soon.

**Comment by kw217** [comment] 2021-02-16 14:35
Seems there's a positive update on https://bugzilla.mozilla.org/show_bug.cgi?id=1676216

**Comment by boek** [comment] 2023-01-25 21:12
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812446

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-25 21:12 UTC
Labels: feature request 🌟, Feature:Logins
