### ISSUE TITLE
[Bug] Private session lost when switch to off an Android permission on Fenix

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#2387] opened 2019-05-09 18:22 UTC
[Video demo](https://drive.google.com/file/d/1WZi_gLLYO2x9aQXITO9uBE-eOhbT15ck/view?usp=sharing) :space_invader: 

## Steps to reproduce
1. Open a site in private mode.
1. Go to Android setting for Fenix.
1. Set to OFF any given Android permission.
1. Go back to Fenix.

### Expected behavior
The site that I was on loads.

### Actual behavior
It loads what ever I had on normal browsing 

### Device information
* Android device: Pixel 3

**Comment by buttercookie42** [comment] 2019-05-09 23:03
The same question is potentially also relevant for when Android OOM-kills the app.
Fennec stores the session store data for private tabs through Android's savedInstanceState mechanism (whereas normal tabs are simply written into the profile directory), so explicitly quitting the app or swiping it away from the task switcher clears the savedInstanceState and therefore all private tabs, too, but an OOM-kill or as in this case a permission revocation-kill leaves the savedInstanceState intact and allows Fennec to recreate the private browsing session.

**Comment by vesta0** [comment] 2019-05-29 18:22
This is the current intended behaviour. Would love UX feedback on this.

**Comment by buttercookie42** [comment] 2019-05-29 18:51
See also #2493.

**Comment by lime124** [comment] 2019-07-23 22:02
@AmyYLee to comment.

**Comment by liuche** [comment] 2019-10-05 01:02
@AmyYLee for more context:

Should we save Private tabs when the app is killed, to (maybe) be reloaded on restart? In this case, it's due to some action a user took that isn't obvious will kill the app (and #2493 is because an app is killed by memory pressure).

**Comment by yoasif** [comment] 2019-10-06 04:00
FWIW, Safari on iOS (not sure about other browsers) saves private tabs forever until closed manually. Given the massive marketshare of that browser, it may simply be that people expect this.

I think it is a nice feature to have, and with the "Quit" option now present in Fenix, that can act as a signal to dump private tabs.

**Comment by AmyYLee** [comment] 2019-11-28 19:12
> @AmyYLee for more context:
> 
> Should we save Private tabs when the app is killed, to (maybe) be reloaded on restart? In this case, it's due to some action a user took that isn't obvious will kill the app (and #2493 is because an app is killed by memory pressure).

Hi, 

I looked at bug #2493 and it makes sense to clear tabs when the app is killed in that scenario (OOM-kill). In this scenario, the user has revoked a permission in app settings and returned back to Fenix. When the user is in non-private mode and revokes a permission, when they return to Fenix it reloads the site they were last on. I think we should follow this behaviour in PBM. If the user wants to kill the PBM tab without opening the app, they can do so in notifications. This way we are giving the user the choice to return to their PBM tab or killing it in notifications without needing to open Fenix.

**Comment by boek** [comment] 2019-12-02 23:56
@AmyYLee I'm not sure if we can determine if the app was killed from being OOM or by a setting change. So we will have to have the same behavior for both

**Comment by boek** [comment] 2019-12-02 23:58
Since the intended behavior is to not persist private tabs to disk and this is a bit of an edge case I am going to close this

**Comment by mcarare** [comment] 2019-12-03 10:45
@boek I think this could only be solved using `savedInstanceState`. But we will then have problems with the case when we don't want to persist the mode. Either way, we would have to trade one behaviour for another.

**Comment by AmyYLee** [comment] 2019-12-04 16:18
> @AmyYLee I'm not sure if we can determine if the app was killed from being OOM or by a setting change. So we will have to have the same behavior for both

In that case let's go with "When the user is in non-private mode and revokes a permission, when they return to Fenix it reloads the site they were last on."

**Closed** 2020-08-26 05:21 UTC
Labels: Feature:PrivateBrowsing, 🐞 bug
