### ISSUE TITLE
FNX-13761 ⁃ [Bug] Reader mode settings stays on when opening another page

### ISSUE THREAD

**Issue by Gaspacchio** [mozilla-mobile/fenix#12659] opened 2020-07-17 08:05 UTC
## Steps to reproduce
* Go to a page where you can enable reader mode: https://en.wikipedia.org/wiki/Mozilla
* Open the appearance settings (three dots, the appearance)
* Switch to another app
* Tap on a link in this app
* Firefox will open and the reader mode appearance setting will stay on the new page

### Expected behavior
Settings should not be shown.

### Actual behavior
![Screenshot](https://user-images.githubusercontent.com/43613824/87763175-a87eba00-c814-11ea-8b3a-c8fb086b7d4c.jpg)UNITO-UNDERSCORE!20200717-095905!UNITO-UNDERSCORE!Firefox Nightly!

The settings overlap the new page.

### Device information
* Android device: Samsung Galaxy S8 (Android 9)
* Fenix version: Nightly 200716 (Build #21980630)

**Comment by s-ankur** [comment] 2020-07-17 10:16
Duplicate of #7591

**Comment by Gaspacchio** [comment] 2020-07-17 10:37
I confirm the duplicate, closing this issue.

**Closed** 2020-08-11 06:55 UTC
Labels: needs:triage, 🐞 bug
