### ISSUE TITLE
possibility to reorder tabs (as it was working already)

### ISSUE THREAD

**Issue by xcalc** [mozilla-mobile/fenix#18217] opened 2021-02-28 14:27 UTC
Tabs can be shown now as a grid again but not reordered per Dragn'Drop as before in tabs overview.
Collections are no replacement for this.
Despite the fact that many websites are now applications one could use the tab overview like an app launcher. 
Maybe one could switch or add/remove collections here also where pages are loaded only if launched for obvious reasons of course.

**Comment by cadeyrn** [comment] 2021-02-28 14:40
Duplicate of #16130 and 16408.

**Closed** 2021-03-01 18:24 UTC
Labels: needs:triage
