### ISSUE TITLE
[Bug] Closed tabs from last browsing session reappear the next time I open the browser

### ISSUE THREAD

**Issue by Shadowspear123** [mozilla-mobile/fenix#17551] opened 2021-01-20 16:08 UTC
## Steps to reproduce

Close two or three tabs.
Close browser.
Reopen browser.

### Expected behavior
The only tabs that should still be there are the ones you haven't closed yourself.

### Actual behavior
The two or three or sometimes even 4 tabs you closed will reopen and reload.

### Device information
Samsung galaxy S8 Android 8.0
I have around 20 tabs open normally.

* Fenix version: Latest Fenix Stable

**Comment by reiny2000** [comment] 2021-01-21 14:44
I'm also experiencing this, only that after I try to close a tab the browser crashes immediately and when I reopen it the tabs are still there.

**What I tried so far**
I tried opening multiple tabs in private window and in that case I can close them.

I also tried cleared cache, force stopped, restarted my phone and disabled addons.

**Device and browser information**
I'm using Nightly 210120 17:01 (Build #2015788491) on a Moto Z Android 8.0.0

**Comment by pocmo** [comment] 2021-01-21 17:17
@reiny2000 Is there a crash report URL in `about:crashes` for the crash you are experiencing?

**Comment by pocmo** [comment] 2021-01-21 17:18
I assume the crash is:
https://github.com/mozilla-mobile/android-components/issues/9409

**Comment by reiny2000** [comment] 2021-01-21 20:59
Yeah, it looks similar.

bca4414d-7954-4d0f-86b9-b4b34151f660
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: recently_closed_tabs.uuid (code 1555)
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=3ab1839f3cf94b8fa70b203a79a6b826
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=27181239f05948368c4cd023e224f68e
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-d7cdb9a1-eec6-4b91-88bc-d26620210121
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-d9ad6d0d-af65-41bf-bd8b-a18f50210121
----
>android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: recently_closed_tabs.uuid (code 1555)
>	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
>	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
>	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
>	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
>	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:1)
>	at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:3)
>	at mozilla.components.feature.recentlyclosed.db.RecentlyClosedTabDao_Impl.insertTab(RecentlyClosedTabDao_Impl.java:3)
>	at mozilla.components.feature.recentlyclosed.RecentlyClosedTabsStorage.addTabsToCollectionWithMax(RecentlyClosedTabsStorage.kt:26)
>	at mozilla.components.feature.recentlyclosed.RecentlyClosedMiddleware$addTabsToStorage$1.invokeSuspend(RecentlyClosedMiddleware.kt:4)
>	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
>	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>	at java.lang.Thread.run(Thread.java:764)

**Comment by pocmo** [comment] 2021-01-22 10:35
@reiny2000 Thank you. A patch for this will be in the next Nightly build. How exactly are you closing a tab? I wasn't able to reproduce this myself.

**Comment by reiny2000** [comment] 2021-01-22 10:42
Like i normally do, tapping on the tabs number button when i'm on a page and swiping or tapping x on the tab I want to close. The number of tabs goes down, firefox crashes and when i restart the browser the tabs reappear.

**Comment by nikunjbhatt** [comment] 2021-02-12 10:43
What I have observed is - if I have come to home screen by pressing back button then the tab history doesn't seems reverting to the new tab page, it is saving the last page of the website as current page. So, after coming "back" to home screen and closing/quitting the browser, and then reopening the browser, the last page/site is reopening instead of home page of the browser.

**Comment by mcarare** [comment] 2021-03-01 16:35
QA: Can you please check if this is still an issue?

**Comment by nikunjbhatt** [comment] 2021-03-01 20:59
@mcarare 
> QA: Can you please check if this is still an issue?

I checked in 86.1.1, there is no new version/update available in play store, means I must on the latest version, and the problem I mentioned in my previous comment still exist.

**Comment by ebalazs-sv** [comment] 2021-03-02 09:48
I had tested this issue on the specified build Nightly 210120 with Motorola Moto G6 (Android 8) and Samsung Galaxy S3 (Android 8), and could not reproduce it.
@Shadowspear123 @reiny2000 @nikunjbhatt Is this issue still reproducible on the latest Nightly build?

**Comment by pocmo** [comment] 2021-03-02 16:11
Can you reproduce this all the time or does it happen only occasionally?
Are you able to collect device logs and make them available? Especially logs with the tag `SessionStorage/AutoSave` are interesting.

I can imagine the following things happening here:
* When the list of tabs changes we see this as a trigger to save the current state to disk. In your case you may be closing the app to fast for this to happen or complete. If saving completed the log should contain a message like `Saved state to disk [2ms]`.
* If we just recently saved the state then we may delay saving the state again. Some changes may delay saving, others will always be saved immediately. In Fenix this delay can be up to 2 seconds, which may be long enough for you to kill the app before that. In this case the log may mention things like `Delaying save (1000ms)`. However the app going to the background should always cause the state to get saved immediately.
* Saving the state actually failed (`Failed to save state to disk`), which would be weird to only happen in this case though.

So I am wondering:
* Do you see anything related in the device logs?
* Does this happen every time or only occasionally?
* Does it happen if you perform the steps slower (in case the save is delayed)?

**Comment by nikunjbhatt** [comment] 2021-03-02 22:02
@ebalazs-sv 
I tested in Nightly 210302 17:01 (Build #2015796363)
and the problem still exist.

**Closed** 2021-10-04 22:12 UTC
Labels: 🐞 bug, Feature:Tabs, wontfix, qa-triaged
