### ISSUE TITLE
[Bug] Bottom bar blocks web page in custom tabs

### ISSUE THREAD

**Issue by ReekyMarko** [mozilla-mobile/fenix#7008] opened 2019-12-06 23:41 UTC
Now that the bar is in the bottom for custom tabs too, it is blocking the bottom part of the page. This does not happen in the full browser. Below are screenshots of the same page in both:

![](https://i.imgur.com/BpAvrUe.png) 
![](https://i.imgur.com/dmrn4JY.png)

**Comment by NotWoods** [comment] 2019-12-07 06:50
Duplicate of #6946

**Closed** 2019-12-07 06:50 UTC
