### ISSUE TITLE
[Bug] (regression) collection name is not correctly aligned

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#9496] opened 2020-03-29 14:40 UTC
### Steps to reproduce

1. make sure you have at least one collection
2. open the Fenix start screen

### Expected behavior

The collection name is vertically centered.

### Actual behavior

The collection name is no longer correctly aligned since the improved collection design. The attached screenshot shows both the old and the new design with some colored lines to show the issue.

![regression](https://user-images.githubusercontent.com/1100614/77851861-9d5b3c00-71db-11ea-8d7d-6e13aa20072c.png)

It's not a big issue but it's a bit eyecatching for me that there is something wrong. :)

/cc @mcarare 

### Device information

* Android device: OnePlus 7T Pro McLaren Edition, OxygenOS 10.0.7 (Android 10)
* Fenix version: master branch revision 394f386ac31e22851a26cb487cf068fbbd29c3c7

**Comment by LittleAngelwings** [comment] 2020-03-29 15:53
Here is one more screenshot from my homescreen. The collection name will be only half to see. 

![Screenshot_20200329-175048_Firefox Nightly](https://user-images.githubusercontent.com/44252450/77853768-368f5000-71e6-11ea-8b49-7c5e946ce417.jpg)

**Comment by ekager** [comment] 2020-03-29 18:41
Regression from #9129
cc @mcarare if you want to follow up on this?

**Comment by sv-sdeiac** [comment] 2020-03-30 09:07
Hi, I also confirm that the issue from the description is reproducible using the latest version of Firefox Preview Nightly 3/29 #20891805.

Devices:
- Google Pixel (Android 10);
- Samsung Galaxy Tab S6 (Android 9);
- LG g7 fit (Android 8.1).

Also, I wasn't able to reproduce the issue displayed by @LittleAngelwings. I tried using a big resolution or editing the size text from the app to ensure that is not related. Additionally, I tried also with different languages and still can't reproduce it.

**Comment by ekager** [comment] 2020-03-30 15:30
Opening for verification

**Comment by LittleAngelwings** [comment] 2020-03-30 18:59
My reported issues is only on my Samsung Galaxy Tab A6 SM-T580 with Android 8.1.0.
On my Huawei Smartphone P Smart (2017) I haven't this problem,

**Comment by LittleAngelwings** [comment] 2020-03-31 03:12
Collection name is complete shown for me with the latest build via GP

Nightly 200330 18:00 (Build #20901803)
38.0.20200329190103, 1341d92fa
GV: 76.0a1-20200327094805
AS: 0.55.0

**Comment by sflorean** [comment] 2020-03-31 11:49
Verified as fixed on Nightly build 200331.
Devices: Samsung Galaxy Note10 (Android 10), Nokia 6 (Android 7.1.1), Xiaomi Mi Pad 2 (Android 5.1).

**Closed by sflorean** 2020-03-31 11:49 UTC
Labels: Feature:Collections, S2, eng:qa:needed, 🐞 bug
