### ISSUE TITLE
[Bug] tab back history menu does not respect dark theme

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#16797] opened 2020-12-01 02:08 UTC
Set Firefox to dark theme. Now go to a website and keep tapping links (to create some back history for that tab). Now long-press on the Android system back button to bring up the tabs back history menu, observe it is not in Dark theme. Device is Google Pixel 3a XL, Android 11, Firefox Nightly. 

![Screenshot_20201130-210021](https://user-images.githubusercontent.com/47801466/100688350-25d44280-3350-11eb-93f7-02923250113d.png)

**Comment by Doctor-Abhi** [comment] 2020-12-01 04:45
Its a know issue. Reported roughly 24 days ago.  See #16768 for a dirty fix. They have been ignoring this bug i don't know why.

**Comment by Dunexus** [comment] 2020-12-01 09:41
Duplicate of https://github.com/mozilla-mobile/fenix/issues/16422

**Comment by kbrosnan** [comment] 2020-12-01 18:39
Closing as a duplicate

**Closed by kbrosnan** 2020-12-01 18:39 UTC
Labels: needs:triage, 🐞 bug
