### ISSUE TITLE
Sometimes when entering an url, the webpage stay the same and I have to enter it another time

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#23774] opened 2022-02-16 01:28 UTC
### Steps to reproduce

1. Write an url of your choice in the main URL bar
2. Click the Enter icon on keyboard to go to this URL

### Expected behaviour

1. the keyboard should disappear 
2. In the URL bar, the URL of the page I currently am should be replaced by the URL I typed
3. It should normally load the website of the new URL I entered

### Actual behaviour

The keyboard disappear as expected but then the page stay the same. And the new URL I wrote doesnt replace the old one. The current url and current webpage are still here.
It's as if nothing happened, and I hadnt wrote any url.

### Device name

Samsung S10

### Android version

Android 12 and 11

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

### Additional information

This problem only occurs every now and then. Not everytime but enough for me to write this bug report.
It happened in Android 11, now in Android 12, and it's happening since many many time, and since much older versions of Nightly. So its an old problem that never got fixed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19522)

**Comment by marcel263** [comment] 2022-02-16 08:11
this has been reproducible for more than a year

**Comment by pimpontitit** [comment] 2022-02-16 11:36
Hi
You mean it's a known problem ? Are you experiencing this problem too ?

**Comment by pimpontitit** [comment] 2022-02-16 12:16
> this has been reproducible for more than a year

Hi
You mean it's a known problem ? Are you experiencing this problem too ?

**Comment by marcel263** [comment] 2022-02-16 15:21
> > this has been reproducible for more than a year
> 
> Hi You mean it's an already known problem ? Or just that you are experiencing this problem too ?

Yes, it has been reproducible for a long time. Because it is such an obvious problem there was no motivation to report the bug, assuming the developers already know about it.
 
Problems of the same category:

Opening tab list sometimes requires two taps
After reopening the browser and selecting a different tab from the tab list, it loads a different tab while displaying the correct URL
tabs become blank/dark and have to be manually reopened (copy/paste URL)
Automatic reload problem still not mitigated. Just closing the browser for a few instances makes the tab reload on reopening

**Comment by pimpontitit** [comment] 2022-02-16 19:47
Hi
Good to know.
Hope it'll be fixed.
I dont remember encountering those issues, except the last one : reopening the app make the tab load again, thats not good if you're working on something important.
Maybe the same thing when you change tabs. 
I'm writing something on a tab, i switch tabs for a moment and when I come back it reloads...

**Comment by sflorean** [comment] 2022-02-23 07:41
I was able also to reproduce this on Nightly , with Pixel 4XL (Android 12) but I don't have exact steps to reproduce since is not 100% reproducible.

**Comment by amocirean** [comment] 2022-11-24 12:49
Hello!
On my side, I've tested this on the latest Nightly from 24th of November (109.0a1) and haven't been able to reproduce this issue. Tested on Samsung Galaxy S22 Ultra (Android 13) and Oppo Find X3 Neo (Android 11)
Is this issue still reproducible to you on the latest Nightly?

**Comment by DiegoARL38** [comment] 2022-11-24 14:43
This is still reproducible, though rarely... It happens once or twice in a day of normal use. I'm using a Xiaomi Redmi Note 8 with MIUI 12.5.2.0 (Android 11).

**Comment by cpeterso** [comment] 2022-12-27 21:12
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807707

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2022-12-27 21:12 UTC
Labels: 🐞 bug, Feature:Search, Feature:Browsing, needs:triage, qa-triaged
