### ISSUE TITLE
After a search group is run, the Recently visited section does not display sites that are visited for the first time

### ISSUE THREAD

**Issue by albertrem** [mozilla-mobile/fenix#22823] opened 2021-12-13 13:52 UTC
Follow these steps to reproduce
Try searching for a term on a preferred search engine;
Look through the search results;Look at the pages.Make sure that the search group appears in the Recently visited section on the homepage[.](https://newshungama.com/)Visit a site that you have not visited before;
browse the homepage.
Behave as you are expected to.
Recently visited sites will appear in the Recent Visits section.

Actual behaviour
The site is not displayed in the Recently visited section after a a search group has been created.

Device name
Oppo Find X3 Neo

Android version
Android 11

Firefox release type
Firefox Nightly

Firefox version
2021-12-10

Device logs
No response

**Comment by sv-ohorvath** [comment] 2022-02-14 16:22
duplicate of https://github.com/mozilla-mobile/fenix/issues/22785

**Closed by sv-ohorvath** 2022-02-14 16:22 UTC
Labels: needs:triage
