### ISSUE TITLE
 schedule dark mode

### ISSUE THREAD

**Issue by jimmyisawesome** [mozilla-mobile/fenix#17151] opened 2020-12-20 06:00 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
well not many devices run a10 and higher and it's a pain to turn off night mode manually so it would be nice to provide an option to toggle night mode during specific periods of time
### How do you know that this problem exists today? Why is this important?
i have experienced the problem
### Who will benefit from it?
everyone

**Comment by anotherus3r** [comment] 2020-12-20 14:21
Also, not all devices have scheduled dark mode, just manual toggling of it (e.g. Huawei devices with EMUI 10.0/Android 10).

**Comment by cadeyrn** [comment] 2020-12-21 08:41
Duplicate of #4236.

**Closed** 2020-12-21 08:48 UTC
Labels: needs:triage
