### ISSUE TITLE
Add bookmarks and history in the home screen

### ISSUE THREAD

**Issue by heberjeur** [mozilla-mobile/fenix#20851] opened 2021-08-14 08:38 UTC
I want my bookmarks and history back on home screen.
It'd be great if users can have one tap access to bookmark and history from the new home screen 
It's important to make home screen as useful as possible 

This is the major feature right now, and this is what developpers need to be focusing on before they continue to lose many users. 

I stick with 68.11 and I can not update until I can make the home default to my bookmarks and history !

**Comment by cadeyrn** [comment] 2021-08-15 19:01
Duplicate of #12065.

**Comment by amedyne** [comment] 2021-08-17 17:59
Closing this as duplicate of #12065

**Closed by amedyne** 2021-08-17 17:59 UTC
Labels: needs:triage
