### ISSUE TITLE
[Bug]: When a web site supports PWA, it is impossible to create a Home screen shortcut on Android with any specific URL of this web site

### ISSUE THREAD

**Issue by dyura** [mozilla-mobile/fenix#22560] opened 2021-11-23 21:37 UTC
This is a design problem. The point is, when Firefox detects a valid manifest.jason on a web page, Firefox does not allow us to create a shortcut on the home screen with the URL of that page, because in this case Firefox only allows us to create a shortcut for the Progressive Web App ( PWA). The "Add to Home Screen" menu item has been replaced with the "Install" item. However, when we open the PWA, we are not navigating to the original URL that was opened in the tab, but to the URL specified in manifest.jason as the start_url value. In most cases, start_url contains the URL from the site's home page. For example, when we open a particular page on the following news sites: https://www.theglobeandmail.com/, https://www.cbc.ca/ and https://www.spiegel.de/, we cannot add a shortcut to this page because we can only install a shortcut for the PWA that will navigate to the home pages of the above sites. This goes against the very idea of ​​adding shortcuts to the home screen with specific URLs.
I don't see the point in such a PWA, because if we need to open the home page of news sites, we can use Firefox bookmarks, collections, or pinned sites.

### Steps to reproduce

1. Open a page with any article on cbc.ca. For example, “About CBC News” page. https://www.cbc.ca/news/about-cbc-news-1.1294364
2. Select  "Install" item in the menu. 
3. A shortcut to CBC PWA application is created.

### Expected behaviour

We click the created shortcut and get the original page "About CBC News" https://www.cbc.ca/news/about-cbc-news-1.1294364.

### Actual behaviour

We click the created shortcut and get the home page https://www.cbc.ca 

### Device name

Gogole Pixel 4a

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

I believe we need to have both items in the menu "Add to Home Screen" to create a shortcut to a specific URL and "Install" when we need a PWA

**Comment by kbrosnan** [comment] 2021-11-23 22:12
Closing as a duplicate of #15450

**Closed by kbrosnan** 2021-11-23 22:12 UTC
Labels: 🐞 bug, Feature:Shortcuts, needs:triage
