### ISSUE TITLE
[Bug] Previously deleted Top Sites very briefly shown on Top Site removal

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#8584] opened 2020-02-20 15:55 UTC
Build: cb7791d7edfd43d84c1a4b428c43742a804f0e1a
Device: Pixel 2 (Android 10)

On Top Site removal, previously deleted Top Sites are briefly shown. This looks rather jarring and surprising to see previously deleted content. This happens with the default Top Sites alongside custom added Top Sites.

![flicker](https://user-images.githubusercontent.com/102331/74953054-28703780-53cf-11ea-9121-c788e6cec0e7.gif)

**Comment by softvision-miralobontiu** [comment] 2020-11-18 14:07
I was not able to reproduce this issue on the 11/18 Nightly build with Samsung Galaxy Tab S6 (Android 10).
I'll close this issue.

**Closed by softvision-miralobontiu** 2020-11-18 14:07 UTC
Labels: Feature:TopSites, needs:triage, 🐞 bug
