### ISSUE TITLE
[Bug] Open in new tab opens image, not URL

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#3891] opened 2019-07-04 19:00 UTC
## Steps to reproduce

As reported in GPS review:

"One major gripe I've noticed however is that when for example Im om a news site that uses images as link/article header,while holding press to open in new tab. It opens then url for the image, not the one for the article. "

### Device information

* Android device: Android 9
* Fenix version: Current release in GPS (assumed)

**Comment by sblatz** [comment] 2019-07-23 18:29
This was fixed on the [AC side](https://github.com/mozilla-mobile/android-components/issues/3434).
Can QA please confirm?

**Comment by kbrosnan** [comment] 2019-07-25 22:05
21 days ago is close to the 1.0 launch. I've not seen any other reports. Going to close this out as a dupe of the issue Sawyer mentions.

**Closed by kbrosnan** 2019-07-25 22:05 UTC
Labels: P3, 🐞 bug

**Comment by Mrfiregem** [comment] 2019-10-26 20:02
This is still an issue, at least with however the [Ohio legislation site](https://www.legislature.ohio.gov) structures their link images.

Long pressing on either the logo or type along the top prompts to open the image instead of the homepage


Nightly 191026 06:00 (Build #12990607)
📦: 19.0.0, 6e6311ea4
🦎: 72.0a1-20191025095546
