### ISSUE TITLE
[Bug] no playback of embedded MP4 file since version 79.0.5

### ISSUE THREAD

**Issue by batterscher** [mozilla-mobile/fenix#14182] opened 2020-08-25 19:14 UTC
## Steps to reproduce
open page https://www.isnichwahr.de/r324747-hoppla.html (with embedded MP4-file using VIDEO tag)

### Expected behavior
playback of video file starts after loading

### Actual behavior
playback does not start; no access to manual playback control available

### Device information

* Android device: Samsung Galaxy S9 (SM-G960F), Android 10, Kernel-Version 4.9.118.188474185
* Fenix version: 79.0.5 (Build #2015758619)

**Comment by kbrosnan** [comment] 2020-08-27 06:27
This site breaks if autoplay is disabled. I get the same behavior as Fenix in desktop if I set it to block audio and video autoplay. Closing as a dupe of #11027

**Closed by kbrosnan** 2020-08-27 06:27 UTC
Labels: Feature:Media, 🐞 bug

**Comment by kbrosnan** [comment] 2020-08-27 06:28
As a workaround go into the Firefox settings, Site permissions and set Autoplay to `Block audio only`
