### ISSUE TITLE
Share of AMP page shares AMP URL instead of canonical URL [Bug]

### ISSUE THREAD

**Issue by JNavas2** [mozilla-mobile/fenix#9036] opened 2020-03-07 00:56 UTC
## Steps to reproduce
Open AMP URL
[https://www.politico.com/amp/news/2020/03/06/warren-team-wonders-how-they-blew-it-122628](https://www.politico.com/amp/news/2020/03/06/warren-team-wonders-how-they-blew-it-122628).
Touch Share > Gmail.
### Expected behavior
New Gmail message with the _canonical_ URL:
[https://www.politico.com/news/2020/03/06/warren-team-wonders-how-they-blew-it-122628](https://www.politico.com/news/2020/03/06/warren-team-wonders-how-they-blew-it-122628)
_This is the behavior in Chrome, and is the preferred URL to share._
### Actual behavior
New Gmail message with the _AMP_ URL:
[https://www.politico.com/amp/news/2020/03/06/warren-team-wonders-how-they-blew-it-122628](https://www.politico.com/amp/news/2020/03/06/warren-team-wonders-how-they-blew-it-122628)
### Device information
Device model: Google Pixel 3a (sargo)
Android version: 10 (QQ2A.200305.002)
Carrier: T-Mobile USA
Fenix Nightly #20660605
### Comments
1. See [What’s in an AMP URL?](https://blog.amp.dev/2017/02/06/whats-in-an-amp-url/)
2. Getting the canonical URL is not simply a matter of removing "amp", since AMP URL structure varies (as I discovered when writing my [NoAMP app](https://play.google.com/store/apps/details?id=com.navasgroup.noamp)).
3. (FWIW, I despise AMP.)

**Comment by NotWoods** [comment] 2020-07-18 19:04
Duplicate of #2769 and mozilla-mobile/android-components#4531 (the latter is to use canonical URLs for all pages, so it should cover this bug too :smile:)

**Comment by JNavas2** [comment] 2020-07-18 19:13
With respect, #2769 and #4531 do not necessarily solve this problem, since they are about URL _trimming_, unrelated to AMP, and trimming does _not_ remove AMP. Please reopen this BUG. Thank you.

**Comment by softvision-miralobontiu** [comment] 2020-12-04 13:47
@JNavas2 I could not reproduce this issue on the 12/4 Firefox Nightly build with Google Pixel (Android 10).
Could you, please, verify as well?
Thanks!

**Comment by JNavas2** [comment] 2020-12-04 16:47
@softvision-miralobontiu

**Comment by JNavas2** [comment] 2020-12-04 16:50
@softvision-miralobontiu 
Thank you.
I verified that the problem persists in 12/3 Nightly.
I'm not yet able to test 12/4 Nightly because it's not yet available on Play.
I will test it when it becomes available.

**Comment by JNavas2** [comment] 2020-12-05 00:30
@softvision-miralobontiu 
I've now tested Firefox Nightly 12/4, and the problem persists. Screen recordings:
- Chrome: https://youtu.be/AKGf9SNNsYA
- Firefox Nightly 12/4: https://youtu.be/2XIyyPhrj78

In both cases I start with a CNN article in news.google.com,
touch the link icon to open the article AMP link,
and then Share it to Google Tasks.
- Chrome shares the canonical link: https://www.cnn.com/2020/12/04/politics/trump-georgia-senate/index.html
- Firefox Nightly shares the AMP link: https://amp.cnn.com/cnn/2020/12/04/politics/trump-georgia-senate/index.html

Hope that helps.

![Screenshot_20201204-155745 (Small)](https://user-images.githubusercontent.com/14850792/101227525-03db0880-364d-11eb-8c2a-eb6639db86d1.png)

**Comment by Dunexus** [comment] 2021-06-05 08:31
Keep it open, still reproducible.

**Closed** 2021-12-09 15:42 UTC
Labels: 🐞 bug, b:webcompat, b:web-content, Feature:Browsing, wontfix
