### ISSUE TITLE
[Bug]Crash when opening the Fenix github page & daleharvey testapp in a custom tab

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#7372] opened 2019-12-27 10:42 UTC
## Steps to reproduce
1. Navigate to https://github.com/mozilla-mobile/fenix

## Alternative Steps to reproduce
1. From Gmail open https://daleharvey.github.io/testapp/ in a custom tab

### Expected behavior
The desired pages should be properly loaded

### Actual behavior
Crash in both cases

### Device information

* Android device: 
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)

* Fenix version: Nightly Build #13610606 from 12/27

### Notes

**1.**  **Fenix Github page**
►Video
![20191227_121448](https://user-images.githubusercontent.com/51314259/71514034-96075800-28a5-11ea-94f9-655e088bf7a6.gif)

►Logcat
```kotlin--------- beginning of crash
2019-12-27 12:21:03.802 27682-27682/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 27682
    java.lang.IllegalArgumentException: Invalid color format
        at org.mozilla.geckoview.GeckoSession.rgbaToArgb(GeckoSession.java:3)
        at org.mozilla.geckoview.GeckoSession.fixupManifestColor(GeckoSession.java:1)
        at org.mozilla.geckoview.GeckoSession.fixupWebAppManifest(GeckoSession.java:1)
        at org.mozilla.geckoview.GeckoSession.access$000(GeckoSession.java:1)
        at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:36)
        at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:1)
        at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:2)
        at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:1)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-12-27 12:21:03.804 27682-27682/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalArgumentException: Invalid color format, breadcrumbs=[Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri Dec 27 12:19:25 GMT+02:00 2019), Breadcrumb(message=Changing to fragment searchFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri Dec 27 12:20:32 GMT+02:00 2019), Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri Dec 27 12:20:35 GMT+02:00 2019), Breadcrumb(message=Changing to fragment searchFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri Dec 27 12:20:48 GMT+02:00 2019), Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri Dec 27 12:20:53 GMT+02:00 2019), Breadcrumb(message=Changing to fragment searchFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri Dec 27 12:20:54 GMT+02:00 2019), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri Dec 27 12:21:00 GMT+02:00 2019)])
2019-12-27 12:21:03.805 27682-27682/? I/mozac/CrashReporter: Showing prompt
```

**2. Daleharvey test app opened in a custom tab**
► Video
![20191227_121827](https://user-images.githubusercontent.com/51314259/71514202-3f4e4e00-28a6-11ea-9c51-3cee2ac76a55.gif)

► Logcat
```kotlin--------- beginning of crash
2019-12-27 12:22:15.216 28980-28980/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 28980
    java.lang.IllegalArgumentException: Invalid color format
        at org.mozilla.geckoview.GeckoSession.rgbaToArgb(GeckoSession.java:3)
        at org.mozilla.geckoview.GeckoSession.fixupManifestColor(GeckoSession.java:1)
        at org.mozilla.geckoview.GeckoSession.fixupWebAppManifest(GeckoSession.java:2)
        at org.mozilla.geckoview.GeckoSession.access$000(GeckoSession.java:1)
        at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:36)
        at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:1)
        at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:2)
        at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:1)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-12-27 12:22:15.217 28980-28980/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalArgumentException: Invalid color format, breadcrumbs=[Breadcrumb(message=Changing to fragment externalAppBrowserFragment, isCustomTab: true, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri Dec 27 12:22:14 GMT+02:00 2019)])
2019-12-27 12:22:15.218 28980-28980/? I/mozac/CrashReporter: Showing prompt

```

**Comment by AndiAJ** [comment] 2019-12-27 10:51
Duplicate of #7362 ?

**Comment by LittleAngelwings** [comment] 2019-12-27 14:15
Yes, it is a dupe ofhttps://github.com/mozilla-mobile/fenix/issues/7362

**Closed** 2019-12-27 18:42 UTC
Labels: S1, b:crash, 🐞 bug
