### ISSUE TITLE
Missing the ability to install unlisted Web Extensions in Firefox Nightly

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [mozilla-mobile/fenix#18135] opened 2021-02-23 21:56 UTC
### What is the user problem or growth opportunity you want to see solved?

It is impossible to install unlisted Web Extensions in Firefox Nightly.

Currently, in order to use a simple custom extension in Nightly, one has to:

1) Create a Firefox Account;
2) Create a collection;
3) Upload the extension to be listed at addons.mozilla.org (unlisted extensions CANNOT be installed);
4) Waste the time of the reviewer to look at the extension;
5) Pollute the add-on database with an extension that is of very little use to the general public.

Curiously, issue #11308, which raised roughly the same issue, was closed as a duplicate of #14034, which is now closed and did not address this specific problem.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9794)

**Comment by GavinBrelstaff** [comment] 2021-03-24 14:51
I have an addon that uses innerHTML on the web pages dervd by google calendar.
So naturally I cannot expect it to be hosted on Mozilla store.
So I host it myself and give instructions on how to install it - https://quicklook-606e5.firebaseapp.com/ 6

For the current version of Firefox on Android this is no longer possible - by design.

Is there any future scenario where this limitation may eventually be relaxed?

I ask because my non-to-for profit addon has/had a genuine use-case for exploring publicly available satellite images while on a smart phone in the field.

**Comment by abodea** [comment] 2021-04-07 13:22
Thank you for this report @automatedbugreportingfacility!
Can you still reproduce this issue?
Please check the following [blog ](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/)if you didn't already.

Hello @caitmuenster can you please review this issue as mentioned in the description I saw that https://github.com/mozilla-mobile/fenix/issues/14034#issuecomment-701468009 the initial bug was closed.

**Comment by automatedbugreportingfacility** [comment] 2021-04-07 14:26
@abodea: yes, definitely still a problem. I am aware of the blog post you have linked to -- it says:

>Starting September 30, you will be able to install any extension listed on addons.mozilla.org (AMO) in Nightly.

However, extensions that are NOT listed on addons.mozilla.org cannot be installed. For this reason, I had to upload my private extension to AMO. Also, a reviewer had to be involved in the process, which was completely unnecessary and wasted their time.

Please note that I am not asking for the ability for anyone to install anything everywhere here. The solution for this extremely inefficient process must meet the following criteria:

1) *Only* available in Firefox Nightly;
2) Behind a pref that the user/developer *EXPLICITLY* enables (for example: extensions.installUnlisted, which defaults to false).

Since every installed extension needs to be listed now, deploying / testing custom private extensions incurs additional work for add-on reviewers, whose time is very valuable. Hence my proposal, which both makes it easier for WebExtension developers to test/use their work and less taxing for Mozilla reviewers.

**Comment by caitmuenster** [comment] 2021-04-07 18:00
Hi @automatedbugreportingfacility, I'm sorry that this has been frustrating. We don't currently have plans to support unlisted extensions on Firefox for Android, but it's something that may be considered in the future.

**Comment by Faeranne** [comment] 2021-05-13 15:13
Just to clarify, if we make a personal addon only for our own use, we will have to post it on AMO?  Since I am working on a tool specifically for tracking my own browsing habbits (with my own private server, not one being published) privately installing the addon is pretty much mandatory (since a reviewer can't actually run the addon).

**Comment by caitmuenster** [comment] 2021-05-17 21:12
Hi @Faeranne, that is correct -- extensions _not_  listed on AMO cannot run on Nightly. And, judging from your description, I would expect your extension to be rejected during the review process because it's for personal use and the reviewers wouldn't be able to test it.  Again, I apologize for the frustration.

**Comment by Faeranne** [comment] 2021-05-18 13:59
The addon was approved, then removed for that very reason.  Can you suggest a method for running this addon on my ohone, even if I have to use a different version of Firefox?  Without mobile support, my addon quickly breaks down in usefulness.

I've tried just rebuilding Nightly as my own app to see if I can install it, but somehow, despite having it disabled, google's "anti-malware" service removed it from my phone.  So even if I rebuilt it for myself, I can't install it.

**Comment by caitmuenster** [comment] 2021-05-18 18:59
Hi @Faeranne, currently there is no supported method for installing an unlisted extension on Firefox for Android.

**Comment by asdofindia** [comment] 2021-06-06 10:55
I am able to `web-ext run` my unlisted addon even in the stable version. But, Firefox cares for "safety" of users more than "freedom" of users.

**Comment by lnicola** [comment] 2022-02-03 05:36
No, bot, installing extensions still doesn't work.

**Comment by Ryzhehvost** [comment] 2022-02-03 11:23
This issue is should be top priority, without this feature firefox is not usable at all. I sill use firefox 68.11 because new firefox is broken.

**Comment by OneOfMany07** [comment] 2022-04-06 04:17
I agree this is dumb.  Why should a developer need to record an add-on with Mozilla to test it on their own phone?  If Mozilla want statistics they can have the browser phone home about any unsigned add-on installations.

Recommend, but give the user what they want.

This is a big strike against Mozilla use for me.  I switched from Chrome because Google blocked add-ons in Android (to protect their ad revenue).  And I've honestly been unimpressed on a number of fronts.  Maybe it is time to give Kiwi a try.

**Comment by Sandjan** [comment] 2022-04-06 08:57
> Hi @automatedbugreportingfacility, I'm sorry that this has been frustrating. We don't currently have plans to support unlisted extensions on Firefox for Android, but it's something that may be considered in the future.

I find it a bit pathetic that such a simple basic functionality that one would hope is not too difficult to implement does not exist.
Is there still no solution for this?

**Comment by kamzil** [comment] 2022-06-29 00:05
The functionality has already been implemented in forks, but the maintainers just don't want to include it in Fenix for some reason.

**Comment by PolicyPuma4** [comment] 2022-08-20 19:48
Make sure to express your opinions here https://connect.mozilla.org/t5/ideas/expand-add-on-compatibility-in-firefox-for-android/idi-p/191.

**Comment by nathanmp** [comment] 2022-11-17 18:50
Has there been a fix for this? This is an important issue for me - like Faeranne, I want to make an addon to collect data about my web history and let me annotate websites, but I'm unable to do so because it couldn't be reviewed.

I don't think security concerns should be a significant concern here - to install an unlisted addon, a user would have to download Nightly, enable dev mode, change the "allow custom addons" setting, and then add an unlisted extension (through a .xpi file presumably). Anyone who wanted to develop a harmful extension would be better off making one that's secretly harmful and submitting it to AMO instead of releasing an .xpi to target the small group of people who jump through all those hoops.

**Comment by boek** [comment] 2023-01-31 16:25
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814131

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-31 16:25 UTC
Labels: feature request 🌟, Feature:WebExtensions, qa-triaged

**Comment by JYone3A** [comment] 2023-02-13 15:15
> ... extensions _not_ listed on AMO cannot run on Nightly. And, judging from your description, I would expect your extension to be rejected ... I apologize for the frustration.

An explanation for this would be much more helpful than an apology.

This feature existed, and does exist in the desktop version, so implementing it cannot be the problem. It puts an additional workload on AMO reviewers. It does not help at all with security. It makes some things, like developing a custom extension at work, impossible.

That's so much more than frustrating, and it might force people to switch to another browser.

**Comment by cadeyrn** [comment] 2023-02-13 15:58
@JYone3A: You answered to a comment from almost two years ago. Things changed in the meantime. It's already known that they're working on a general availability of add-ons (https://bugzilla.mozilla.org/show_bug.cgi?id=1796184). And as you can see directly above your comment this issue was moved to Bugzilla two weeks ago.

**Comment by JYone3A** [comment] 2023-02-14 07:56
@cadeyrn as far as I understood, they are only working on allowing all Addons from AMO, but will not allow unlisted/unsigned sideloading of XPIs

**Comment by cadeyrn** [comment] 2023-02-14 09:58
I don't know their internal plans. But what I see it that _this_ issue was moved to Bugzilla and it's still open.

**Comment by JYone3A** [comment] 2023-02-15 15:46
Well, exactly that's the problem I guess. The situation is just very frustrating and we don't know if and when something will change. This issue here is not referenced in the link you posted, so I am not sure how this is gonna be taken into account over there.
