### ISSUE TITLE
[Bug] "Recently Used" in Share Menu Obstructs Full Applications List

### ISSUE THREAD

**Issue by jc-wood** [mozilla-mobile/fenix#9410] opened 2020-03-25 20:58 UTC
The share menu on Android is a huge mess. The "Recently Used" list can currently grow so large that it obscures the full app list. See screenshot below.

[Link](https://pgrkcg.by.files.1drv.com/y4mMxHQE0glt6LrdM1XOvF81S0TgCacx6tO2sfuj4Gp3hyDJj9cKReJxIDzxFVlKPyInZUtMGDTpMSC-ZLffU5eAQUAFVpef7iIQqsL6cPTAWYyOaaD_Yez-Z6QI2tXkh7QsynIN1x1o4nAolB2ILSsebWCusCd2PmfKE2t0p60o6549Eqnvi18CZW8F9bHHJw0BMITrv33CaHmAzNDQnx2Og)

## Steps to reproduce

1. Share a URL to several different applications.
1. Keep sharing to different applications until "Recently Used" list obstructs the right-hand applications pane.

### Expected behavior

"Recently Used" list does not expand to a width that would obstruct the full applications list.

### Actual behavior

"Recently Used" list expands to a width that obstructs the full applications list.

### Device information

* Android device: OnePlus 7 Pro GM1915, Android 10.0.2
* Fenix version: 4.1.0 (Build #20771637)

**Comment by SL-Lee** [comment] 2020-03-30 14:24
Looks like a duplicate of #8759.

**Comment by sflorean** [comment] 2020-11-23 17:20
@jc-wood a lot of issues have been fixed around the share menu, can you please check on latest Nightly to see if the behavior is fixed? thank you!

**Comment by jc-wood** [comment] 2020-11-23 17:23
Looks fixed.

**Comment by sflorean** [comment] 2020-11-23 17:24
Thank you. Closing as fixed.

**Closed by sflorean** 2020-11-23 17:24 UTC
Labels: needs:triage, 🐞 bug
