### ISSUE TITLE
[Bug] Restored tabs from collections show old cached content

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#10417] opened 2020-05-05 12:00 UTC
## Steps to reproduce
I don't have concrete STR but I see this frequently, where I open Fenix and tap on a link to news.ycombinator.com in one of my collections. This is from a cold start, sometimes even after a device reboot, so it's definitely not Fenix sticking around in the background.

### Expected behavior
Page opens with latest version.

### Actual behavior
Page opens with the same content I was seeing last time I opened the page, typically a day or two previously. My assumption is that the page is fresh but after a reading a few headlines I get suspicious because they all look familiar. I reload the page and see that now I get fresh content.

### Device information
* Android device: Sony Xperia XZ1C
* Fenix version: Nightly 200504 06:01 (Build #21250608)
40.0.20200430224518, 2227e0a76
GV: 77.0a1-20200430082621
AS: 0.58.2

**Comment by ekager** [comment] 2020-05-05 17:40
Dupe of https://github.com/mozilla-mobile/fenix/issues/5869. Unfortunately still waiting on bugzilla.mozilla.org/show_bug.cgi?id=1630000

**Comment by PyvesB** [comment] 2020-05-10 06:59
@ekager @eliserichards I'm facing this problem as well. Is this really a duplicate? The two issues you linked seem specific to back button behaviour, whereas this is related to collections, and only became a problem in the past few days. 😉

**Comment by ekager** [comment] 2020-05-11 17:46
Ah I understand. I will reopen and retitle

**Comment by ContentPersonality2** [comment] 2020-05-12 10:12
I'm having this issue too. I believe it's specific to collections and I can confirm its happening on mspoweruser.com and bbc.co.uk/news.

**Comment by JNavas2** [comment] 2020-06-15 03:54
It seems the restoring of old (cached) content is **by design**–see [Comment](https://github.com/mozilla-mobile/fenix/issues/11506#issuecomment-643264112) on #11506
> This is intentional behavior with collections currently. We are restoring the state of the tab with history as well.

I think this unfortunate, because it greatly reduces the usefulness of Collections to me.
I had hoped/assumed Collections would be like Tab Groups.
I'll have to go back to using Bookmark folders. :disappointed:

**Comment by maroonmoon13** [comment] 2020-06-15 14:09
I agree it's a big "regression" as collections in FF never worked like that. I have been using it since the first preview, and Its a learning curve to get used to this new implementation. But I do feel that for a bunch of stale tabs, a lot of prime real estate on the front page is being wasted. I have removed everything from collections and added everything as top sites. But that's just a bunch of icons which cannot be even moved around or categorized. that's why, "regression"

**Comment by JNavas2** [comment] 2020-06-15 15:40
A simple solution to this problem would be a **Setting to switch the behavior of Collections** between:

- Saved content
- Current content

**Comment by maroonmoon13** [comment] 2020-06-15 15:44
Agree. But then we have to contend with Top sites, Bookmarks and collections doing pretty much the same thing when loading current content.

**Comment by maroonmoon13** [comment] 2020-06-15 15:45
Edge has top sites (limited in number), bookmarks and collections to save sites. But it does not waste so much space on a feature which is limited in use.

**Comment by JNavas2** [comment] 2020-06-15 15:56
> @maroonmoon13 
Agree. But then we have to contend with Top sites, Bookmarks and collections doing pretty much the same thing when loading current content.

Yes, it's a confusing UX mess that needs to be cleaned up:

- Bookmark access is currently too clumsy to be useful.
- I don't want to waste Fenix home screen space on saved content.

Top Sites would be more useful to me if:

1. Top Sites could be edited and rearranged.
2. A folder (bookmark) could be a Top Site.
3. In other words, "Quick Access" rather than Top Sites.

**Comment by maroonmoon13** [comment] 2020-06-15 15:58
Nailed it.

**Comment by madb1lly** [comment] 2020-06-18 06:19
Hi all,

I didn't realise this is how collections now work, and now I know this I might actually use them. I only see collections as useful if they save content _and_ history. If I want current content then I can use bookmarks or top sites (I know the bookmarks workflow is a pain now, I know), so it's important that collections offers something different.

I'll be using this and testing it now to see how well it fits to what I was hoping for 😃

Cheers 🙂

**Comment by Standard8** [comment] 2020-06-18 06:49
The new beta version has top sites, and that might be enough for my use cases, if it becomes customisable.

If collections are to be kept as a set of "saved content", I would like to suggest that they are renamed. "Save to collection" and "Collections" do not suggest to me in any form that they are saved versions of the pages rather than a collection of saved pages... and I could see users being frustrated by that not being made clear.

"Saved Pages", "Saved Content" might be better, although I think they still don't represent it well enough.

**Comment by PyvesB** [comment] 2020-06-18 07:14
@madb1lly @Standard8 unfortunately, even in their new state, collections aren't actually "saved content". If you try to load a collection item without Internet connectivity, it will fail. Similarly, if your Internet connection is slow, Collection items will take forever to load.

**Comment by cadeyrn** [comment] 2020-06-18 09:03
> The new beta version has top sites, and that might be enough for my use cases, if it becomes customisable.

You can already add and remoe top sites. But note that there are plans to limit the number of maximum top sites to 8. It may be enough or not enough for your use case.

>" Save to collection" and "Collections" do not suggest to me in any form that they are saved versions of the pages rather than a collection of saved pages... and I could see users being frustrated by that not being made clear.
>
> "Saved Pages", "Saved Content" might be better, although I think they still don't represent it well enough.

That's true, the name does not really reflect the functionality. Unfortunately your suggestions have a similar problem as explained by PyvesB. I think collections are kind of "tab groups". If we see collections as tab groups it opens a few opportunities for enhancements, for example #5967.

**Comment by madb1lly** [comment] 2020-06-19 10:32
Hi @PyvesB,
Thanks for the clarification. The lack of adhoc offline viewing of tabs with Fenix is pretty frustrating compared to what Fennec can do, but that's another topic.
Cheers 🙂

**Comment by JNavas2** [comment] 2020-06-19 19:59
Yes, there needs to be an Option for **Collections to be treated as Tab Groups**
that open to show **current content** (rather than stale content). :+1: :+1:

**Comment by madb1lly** [comment] 2020-06-20 08:58
Hi @JNavas2,

I agree an option could be useful but doesn't this scale content reflect more on the websites?  Shouldn't they be programmed to show current content? Some sites work like this don't they, like Twitter?

On desktop when opening a previous session's tabs the content shown is old isn't it, unless the site intentionally refreshes?

Cheers 🙂

**Comment by ContentPersonality2** [comment] 2020-06-20 09:13
> A simple solution to this problem would be a **Setting to switch the behavior of Collections** between:
> 
> - Saved content
> - Current content

This is the best solution in my option. I really want to be able to use the collections feature as a sort of bookmark grouping feature again rather than a way of saving websites for offline viewing.

**Comment by JNavas2** [comment] 2020-06-20 18:36
@madb1lly
The use case is the ability to have **saved tab groups** that open to show _current_ content.
A _News_ tab group might open to show _current_ content from AP, CNN, UPI, in 3 tabs,
or an individual _News_ tab could be opened with _current_ content.
In desktop that can easily be done with a Bookmark folder on Toolbar or in Menu.
In Fenix there's currently no good way to do that.
Hence the interest in Collections, and the desire to have Collection tabs open to _current_ content.

**Comment by madb1lly** [comment] 2020-06-20 22:14
Hello @JNavas2,

I don't doubt your use case nor disagree that it's an important one, I'm just comparing the behaviour you're seeing to how tabs work on desktop. It seems to me that tabs in collections work the same as tabs in the main stack (and how tabs in the Simple Tab Groups extension work on desktop), whereas what you're describing you'd like _is_ how bookmarks work. I think it's quite useful to have two different things that work different ways, but the problem is that they're not both equally accessible at the moment. I think top sites work like bookmarks, not like tabs, in that when you load them they show current content, but I presume that top sites isn't sufficient for you at the moment (you've suggested some improvements above).

If bookmarks were more readily available from the homescreen would this be a good way to achieve the desired result?

Cheers 🙂

**Comment by maroonmoon13** [comment] 2020-06-20 22:45
I think rather than using a setting to choose the behavior of collection, we should use gestures. Swipe right to load the current version, swipe left to load the saved version. I am not a big fan of swipe to delete collections, as there is no easy way to undo it, its far to easy to delete one by accident, and re-adding the page to the collection puts it at the bottom of the collection.
Discoverability is same as current collection behavior, which is poor to be frank. Hardly anyone will anticipate that collections are good for saved pages and not to be used for bookmarks.

**Comment by Matth7878** [comment] 2020-06-21 07:10
I agree with above comments IMHO collections should be tab group with choice in behavior between saved content or current content.
Besides collections all other annoyances steam from top sites being too limited (text too short, icon) and bookmarks not easily accessible or editable. ☹️

**Comment by JNavas2** [comment] 2020-06-21 19:12
> @madb1lly
> If bookmarks were more readily available from the homescreen would this be a good way to achieve the desired result?

Maybe. Much would depend on the implementation. As it is now:
- Top Sites is too limited and clumsy to be useful to me, a waste of home real estate.
- Collections don't address any use case for me, a bigger waste of home real estate.
- Bookmarks access is too painful to be useful.
- Given the current home layout, I find it difficult to imagine how Bookmarks could be elevated to home other than by changes to Top Sites or Collections.

**Comment by ekager** [comment] 2020-06-23 21:05
@mmanjos also reported in #11864 that sometimes refresh doesn't work on some pages saved to a collection

**Comment by yoasif** [comment] 2020-06-23 21:20
@ekager Isn't #11864 just a flat out bug unrelated to the core design feedback we are seeing here in this bug?

FWIW, while I do think collections have issues, restoring prior state on restore is not one of them.

**Comment by AmyYLee** [comment] 2020-06-24 00:30
@topotropic for feedback

**Comment by AmyYLee** [comment] 2020-07-10 20:13
@topotropic Does this need deeper UX investigation?

**Comment by topotropic** [comment] 2020-07-15 08:34
I agree that this behavior is not ideal and we'll revisit it as part of the upcoming Collections work.

**Comment by jillesvangurp** [comment] 2020-08-26 15:30
I would argue it's a bug of what clearly is a bookmarking feature. The fact that it was intended as something else just means whatever that was supposed to be needs to be scrapped and rethought. Whatever that was, was lost in translation.

**Comment by Poopooracoocoo** [comment] 2020-09-12 08:49
related: #219 #7325

**Comment by handyguy2** [comment] 2020-09-24 05:03
> 
> 
> I agree with above comments IMHO collections should be tab group with choice in behavior between saved content or current content.
> Besides collections all other annoyances steam from top sites being too limited (text too short, icon) and bookmarks not easily accessible or editable. ☹️

Not to mention that top sites are not synced, and it appears the android version cannot have more than two rows of top sites, although they can overflow to a second page (not as convenient).

**Comment by Juraj-Masiar** [comment] 2020-10-06 06:41
This is really annoying bug. I have a Weather collection that gives me outdated weather forecast reports. Not good at all! If none of my other web-browsers serves me old content, why Fenix does? 
Isn't there some standardized caching mechanism that tells browsers which content to cache and which not? I'm pretty sure there is.

**Comment by Poopooracoocoo** [comment] 2020-10-06 07:15
> Not to mention that top sites are not synced, and it appears the android version cannot have more than two rows of top sites, although they can overflow to a second page (not as convenient).

see #7936

**Comment by madb1lly** [comment] 2020-10-06 14:15
Hi @Juraj-Masiar,

AFAIK collections are intended to show cached page content. If you want fresh content then bookmarks will do what you want.

However, it could be useful to have an option for each collection to show cached or current page content when the collection is opened.

Cheers 🙂

**Comment by JNavas2** [comment] 2020-10-06 15:51
@madb1lly 
> AFAIK collections are intended to show cached page content. If you want fresh content then bookmarks will do what you want.

Actually, they won't, because accessing Bookmarks is much less convenient.
Save for later review is a good capability, but this is a poor design.
Home screen should be reserved for what _the user most often wants_.

**Comment by handyguy2** [comment] 2020-10-06 16:06
It takes at least 5 clicks to access a bookmark. WAY to complicated and slow. Top sites need to be be synced and easily customizable.  What's the point of having an account, if not all settings are saved?

**Comment by Matth7878** [comment] 2020-10-06 16:54
What you are asking is to be able to have bookmarks folder instead of collections on homepage. But I agree it would be usefull to have an option for collections to decide wether they should refresh or not when viewing them.

**Comment by maroonmoon13** [comment] 2020-10-06 17:00
As has been pointed out numerous times, Top sites could be very useful in implementing the behavior we want. But just when I was getting used to it, it has been further constrained by showing just 2 rows with 4 icons each. Not that accessing the bookmarks was stupidly cumbersome, Now I have to scroll to get to top sites as well. 

Half of the UI is taken up by Collections, which to be frank is the least useful features among Top sites, bookmarks, and access saved content. Why the messing with the UI rather than giving us functionality like moving and configuring?

**Comment by mmanjos** [comment] 2020-10-06 17:06
I'm still surprised there's any desire to implement a feature based on
cached content these days with ubiquitous mobile data and wifi access. The
last time I wanted to read a cached page on a mobile device was when I
synced a webpage to my Palm IIIc in its charging cradle.

From a user perspective, it feels like a bug when I load from a collection
to receive an old cached document. Especially so when there's no UI element
or training that pops up explaining that saving something to a collection
makes it offline/cached.

**Comment by JNavas2** [comment] 2020-10-06 17:06
@maroonmoon13 
> Half of the UI is taken up by Collections, which to be frank is the least useful features among Top sites, bookmarks, and access saved content. Why the messing with the UI rather than giving us functionality like moving and configuring?

**Amen.**

**Comment by PyvesB** [comment] 2020-10-06 17:13
> I'm still surprised there's any desire to implement a feature based on cached content these days with ubiquitous mobile data and wifi access. 

It isn't actually fully cached, you need fully working Internet access for the collection item to load, as highlighted in https://github.com/mozilla-mobile/fenix/issues/10417#issuecomment-645827442. So even in the cases where you're offline, it isn't useful.

**Comment by jillesvangurp** [comment] 2020-10-07 08:13
I think the problem with this feature is that it competes for real estate with  bookmarks, is not differentiated from bookmarks in any obvious way, and has behavior that is very subtly different from bookmarks in a way that is also completely opaque to the user: it shows you stale content without telling you it is stale content and without a convenient way to refresh (other than digging in the menu for the reload button). That's why there's an endless amount of duplicates being reported because it's an obviously broken bookmark feature that shows you stale content. 

The debate in Mozilla seems to be about whether this is salvageable at all and we're basically discussing  to add flags to bookmarks to turn them into this weird notion of a collection item, which translates as an offline copy of a page. IMHO it's not worth the UI real estate given that this is a niche feature that the vast number majority of users will ignore. I actually like this as a bookmark UI. I've used firefox for months assuming that it was a bookmark UI and I assumed the caching weirdness was just buggy behavior. Fix that and  its fine. Then store the collections in the bookmarks folder so they get synced and everything will be perfect from my point  of view. I have no use for offline browsing. I have a 4G phone and pay for it to be online all the time.

**Comment by Poopooracoocoo** [comment] 2020-10-07 09:54
And Firefox for desktop doesn't have tab collections. You can't sync them yet either. 

Tabs have history and bookmarks don't. I have yet to use collections but if bookmark all tabs were added today, I'd use it immediately. Not all of the tabs I have open have one page in their history though, so I'd have to navigate back on each page and bookmark them, not before of course sorting through all of the pages I've already bookmarked. 

I can see the use of an offline page but the aggressive, intentional caching of tab collections confuses me. Unless I was typing something or have intentionally saved it, I don't want an old cached page (unless it's of course a tab I've recently accessed!).
 P.S. I've linked my feature request for bookmark all tabs above ;)

**Comment by madb1lly** [comment] 2020-10-07 12:34
Hi all,

I totally agree that if one wants bookmarks on the homescreen and/or not collections then that should be possible, but that's not the topic of this issue, that discussion is happening here: #12065 .

If tab collections were actually swappable then I think their use case and the reason why they show cached content would be more obvious, but currently they're not. It's actually very cumbersome to swap collections, which is the only reason I'm not using them more (I actually use them as a way to manage my tab hoarding, but not quite bookmarks).

Still, it's clear that the fact that collections use cache is not clear and needs to be explained to the user and preferably have an option to disable this.

Cheers 🙂

**Comment by liuche** [comment] 2020-10-22 18:08
For this bug, we want to refresh the page when loading a page from collections.

This won't have any other changes, we'll still keep the backstack.

**Comment by yoasif** [comment] 2020-10-22 19:48
@liuche I think that solves the thing people dislike most about the existing behavior. Now to see how many complain that they lost form data from a saved tab in a collection... 😬

**Comment by eliserichards** [comment] 2020-12-07 17:35
## For QA: 

According to @liuche's [comment](https://github.com/mozilla-mobile/fenix/issues/10417#issuecomment-714666960) above, we want to keep the backstack of the page at the time that it was added to the collection, but have a fresh version of the page (e.g. if it is a news site, we should see the latest news not the news at the time we added to the collection). To keep the backstack, we `restore` the page; then we `reload` to make it up-to-date.

I was testing with Wikipedia. Click through a few different wiki pages, add page to collection. When we open the page from the collection, we should see the backstack of all of the pages we visited before adding to the collection. We should also see that the wiki page is the most recent version of itself (the page has reloaded). A news site would also be a good example of this to check if it is up-to-date.

**Comment by softvision-miralobontiu** [comment] 2020-12-14 09:42
Verified as fixed on the 12/14 Nightly build with Samsung Galaxy Tab S6 (Android 10).
I saved the bbc.com news site in a collection, opened the page from the collection after three days, and the page displayed the latest news.
The first image is from 12/11, the second is from today, 12/14:

![Untitled](https://user-images.githubusercontent.com/40694158/102065489-4c3eb700-3e01-11eb-9d34-be7f4d9aca76.png)

**Closed by softvision-miralobontiu** 2020-12-14 09:42 UTC
Labels: Feature:Collections, Skittle, eng:qa:needed

**Comment by toxpal** [comment] 2020-12-30 10:10
The issue still exists for me on 84.1.2 (Xperia 5 II/Android 10). Some sites work just fine, but others always display last cached versions when opening tabs from collections.

Let's say I add website domain.com to collection. When I open domain.com from collection later, app displays old version (even if I open website several days later), and I need to manually reload page. After I reload, this reloaded version is stored in cache, so the next time I open collection again, it displays this cached version, and so on.

Happens on some websites only. For example, with 9to5linux.com. The issue only started after major update to version 80. Used app for years in the past, never had such problem.

**Comment by cadeyrn** [comment] 2020-12-30 23:31
@toxpal This is expected since the issue is not yet fixed in Firefox 84. It takes some time to get changes from Nightly via Beta to stable releases.
