### ISSUE TITLE
[Pull To Refresh][Bug] Drag and drop on ddg maps triggers pull to refresh

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#17275] opened 2021-01-01 10:06 UTC
## Steps to reproduce
open any ddg navigation for example
https://duckduckgo.com/?q=nicolae+licaret+8&t=fpas&ia=web&iaxm=directions&end=what%3ASta%25C5%25A3ia%2520Pia%25C5%25A3a%2520Iancului%2Cwhere%3A%25C8%2598oseaua%2520Mihai%2520Bravu%252C%252093%25E2%2580%259395%252C%2520Bucharest%252C%2520021312%252C%2520Romania&transport=drive&start=what%3ASta%25C5%25A3ia%2520%25C5%259Etefan%2520cel%2520Mare%2Cwhere%3A%25C8%2598oseaua%2520%25C8%2598tefan%2520Cel%2520Mare%252C%2520Bucharest%252C%2520Romania
Drag down on the map

### Expected behavior
The map is moved down and I'm able to see north of the original position
### Actual behavior
pull to refresh is triggered
![Screenshot_20210101-120111_Firefox_Nightly](https://user-images.githubusercontent.com/922368/103436924-b3de6a00-4c29-11eb-994d-11d0cdf92462.png)

### Device information

* Android device: OnePlus 5t
* Fenix version: Nightly

**Comment by Amejia481** [comment] 2021-01-04 16:42
cc @Mugurell

**Comment by Mugurell** [comment] 2021-01-06 16:50
Thank you!
Will look into this.

**Comment by Mugurell** [comment] 2021-01-08 12:21
@hiikezoe I see `INPUT_RESULT_UNHANDLED` being returned when panning in the map.
We shouldn't really do anything in this case either (that's why the toolbar is not animated) but for the time being for pull to refresh we acknowledged we still need to use this return.
But either way shouldn't `INPUT_RESULT_HANDLED_CONTENT` be returned in this case?

**Comment by hiikezoe** [comment] 2021-01-11 22:37
I believe so. We need to investigate what the site is doing for the drag scrolling.

**Comment by lilydjwg** [comment] 2021-02-06 04:28
#16580 should be the same issue.

**Comment by sflorean** [comment] 2021-04-06 14:48
Closing this as dupe of #16580! @andreicristianpetcu your scenario will be tested when the issue is fixed, but please check the latest Nightly because some related patches were landed.

**Closed by sflorean** 2021-04-06 14:48 UTC
Labels: Feature:Gesture, 🐞 bug
