### ISSUE TITLE
Clicking Google search results doesn't leave a proper history entry

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#13456] opened 2020-08-10 13:34 UTC
## Steps to reproduce

1) Search on Google for a term
2) Click the search results

Later, or on another device, use the History. Try to find the websites you were on. You'll only see "www.google.com" domains instead.

Screenshot:

![Screenshot_20200810_123020_org mozilla fenix](https://user-images.githubusercontent.com/1104290/89788081-df4ba580-db1e-11ea-9a2e-4391797cb59e.jpg)

### Expected behavior

Side on which you're redirected is entered in history. (This worked correctly in Fennec)

### Actual behavior

See screenshot.

### Device information

* Android device: Pixel 2 XL
* Fenix version: Nightly

**Comment by s-ankur** [comment] 2020-08-10 15:51
Duplicate of #12482

**Closed** 2020-08-10 15:55 UTC
Labels: needs:triage, 🐞 bug

**Comment by gcp** [comment] 2020-08-10 16:16
I guess that's really #7544 then.
