### ISSUE TITLE
[Bug] [a11y] Default search engine list - The selected enabled options are not recognized as activated

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#8625] opened 2020-02-21 08:56 UTC
Pre-conditions:
-Have TalkBack enabled

## Steps to reproduce
1. Open app.
2. Go to "Menu"/"Settings"/"Search" option.
3. Tap on the default search engine. (Google)
### Expected behavior
The TalkBack recognizes the default engine through the radio button's active state.
### Actual behavior
The TalkBack does not recognizes the default engine through the radio button's state.
### Device information

* Android device: Google Pixel C (Android 8.0.0)
* Fenix version: Firefox Preview Beta 4.0.0-beta.1

Note:
- After making a different search engine as default there isn't any description of activating it though TalkBack.
- This issue seems to be related with #8581 . Having at base the radio button not recognized as checked/activated/enabled.

**Comment by asadotzler** [comment] 2020-04-05 15:57
This is an accessibility P2. The feature is available and works but is difficult to use. This kind of bug prevents Fenix from being a delightful experience for users with disabilities.

**Comment by sflorean** [comment] 2020-08-19 09:25
@mcarare Tested on Nightly 8/19 and taping on "Google" entry the following is displayed by TalkBack: "Google. Double-tap to activate." even if the search engine is already set as default.

**Comment by codrut-topliceanu** [comment] 2020-08-19 09:45
@sflorean if you use drag left & drag right to navigate through the controls, when the radio button is focused, Talkback will say "radio button for Google..." and specify whether it is enabled.

**Comment by sflorean** [comment] 2020-08-19 09:50
@codrut-topliceanu indeed, following drag left & right the issue is fixed. Closing as verified.

**Closed by sflorean** 2020-08-19 09:50 UTC
Labels: P2, S2, b:a11y, needs:triage, 🐞 bug
