### ISSUE TITLE
Firefox Nightly 103.0a1 UI refreshes at 60Hz on a 120Hz panel with privacy.resistFingerprinting enabled

### ISSUE THREAD

**Issue by slashdragos** [mozilla-mobile/fenix#25530] opened 2022-06-05 22:02 UTC
Open any website and start scrolling. Firefox Nightly 103.0a1 refreshes at 60Hz on a 120Hz panel.

On a 120Hz panel, Firefox should scroll at 120 FPS.

Firefox 103 only displays 60 FPS on a 120Hz panel.

Note that this behaviour cannot be reproduced within Settings menu.

I can reproduce this issue on both Galaxy Note20 Ultra (N9860) and Galaxy S22 Ultra (N908B), both running Android 12. This issue has been present for less than 48 hours, so it only affects the last few builds published on PlayStore as of 05/05/2022.

Nightly 103:
![nightly_103_0a1](https://user-images.githubusercontent.com/106933291/172072421-8e17de2f-f9d2-4c94-954b-c2f544429c31.png)

Stable 101:
![stable_101_1_1](https://user-images.githubusercontent.com/106933291/172072438-99aca73a-014d-4aa5-a03c-2ffcc3c95631.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20650)

**Comment by Mugurell** [comment] 2022-06-06 05:46
Duplicate of https://github.com/mozilla-mobile/fenix/issues/20630

**Comment by Mugurell** [comment] 2022-06-06 12:07
@slashdragos In regards to the issue it is more of a platform limitation - the underlying surface the webpage is drawn on has that limit of only updating at 60Hz but some OEMs will choose to allow certain application to render at an even higher framerate. Like it happens on most devices for the release version of Firefox.
Firefox Nightly unfortunately doesn't generally benefit of that exemption from the 60Hz limit but at the moment this is not something that we can control.

**Comment by slashdragos** [comment] 2022-06-06 12:58
I did some more testing this morning, and upon a fresh install of Nightly, everything works fine at 120Hz.
I did find the culprit, although this might be intended behaviour: "privacy.resistFingerprinting" limits Firefox to 60 fps. It would be nice if I could keep privacy.resistFingerprinting=true but keep 120fps. It doesn't make a ton of sense to me limiting the engine to 60 fps, as my phone will appear less unique anyway since it will go as low as 24Hz, hence limiting Firefox to 24fps as well, since this implementation seems to limit Fx to 60fps only, rather than requesting the device to use 60Hz constantly.

**Comment by Mugurell** [comment] 2022-06-06 16:29
I don't have a recent Samsung device now to test but looked again on a OnePlus supporting a 90 Hz refresh rate while having `privacy.resistFingerprinting` as both `false` and then `true`.
Both by using this steps - https://github.com/mozilla-mobile/fenix/issues/20630#issue-958505543 and by visiting `testUfo.com` I still get 60 Hz on Release and 90 Hz on Nightly.

It could be that Samsung added an exemption for `org.mozilla.fenix` also.
Curious if you could try entering `adb shell dumpsys display | grep -A 16 DisplayModeDirector` in terminal and checking what the reported values from `PRIORITY_APP_REQUEST_REFRESH_RATE` are when browsing. With or without the `privacy.resistFingerprinting` setting.

**Comment by slashdragos** [comment] 2022-06-06 17:13
`   PRIORITY_APP_REQUEST_REFRESH_RATE_RANGE -> Vote{width=-1, height=-1, minRefreshRate=60.0, maxRefreshRate=Infinity, disableRefreshRateSwitching=false, baseModeRefreshRate=0.0}
 mModeSwitchingType: SWITCHING_TYPE_WITHIN_GROUPS mAlwaysRespectAppRequest: false
 SettingObserver mRefreshRateMode: REFRESH_RATE_MODE_SEAMLESS
`

I get the exact same result regardless of privacy.resistFingerprinting state. I should also point out that I have tried the latest Nightly x64 on Windows LTSC, running on a 360Hz display, and privacy.resistFingerprinting=true limits the Windows version as well to 60fps. This is definitely an intended behaviour by the developers, although I wish I could have both privacy.resistFingerprinting=true and high framerate.

**Comment by Mugurell** [comment] 2022-06-07 07:15
Thank you for double checking this.
Reopening this ticket to have QA test if Samsung did recently change to remove limitations for `org.mozilla.fenix` also.

**Comment by mcomella** [comment] 2022-06-08 20:43
Performance triage: this sounds like 1) a functional decision regarding `resistFingerprinting` and 2) potentially a functional issue with certain devices and the view we draw web content into so we're removing the performance label. Please add the label again if further investigation finds a performance problem – thanks! 😁

**Comment by hkaancaliskan** [comment] 2022-06-15 21:02
RFP forces to 60hz and this is intentional (but idk why). If anyone understands why, please explain 🥲
https://bugzilla.mozilla.org/show_bug.cgi?id=1692609

**Comment by SoftVision-LorandJanos** [comment] 2022-06-21 10:41
Using a Samsung Galaxy Tab S3 (Android 9), I've tested this on the latest Nightly 103.0a1 (2022-06-20) and after enabling `gfx.webrender.debug.profiler` from `about:config` I've seen a maximum FPS of 60. That is with and without `privacy.resistFingerprinting` enabled.
Same can be said about the Beta and the Release versions, also checked on testufo.com, with the same results.

**Closed** 2022-06-21 10:41 UTC
Labels: eng:qa:verified, needs:triage

**Comment by apacelus** [comment] 2022-09-10 02:57
Is there any hope for this to be "fixed"(or rather a separate toggle to exist for refresh rate)?
