### ISSUE TITLE
[Bug] Page titles and favicons aren't shown

### ISSUE THREAD

**Issue by kamran-12** [mozilla-mobile/fenix#5352] opened 2019-09-16 11:00 UTC
### Steps to reproduce
Open one Wikipedia page and open one link with "Open in New Tab" (I don't know which other sites are also affected).

### Expected behavior
Favicons and page titles for all tabs.

### Actual behavior
![image](https://user-images.githubusercontent.com/46045997/64952908-96e62200-d892-11e9-9ba7-febc34290930.png)

### Device information
* Android device: Samsung Galaxy S6, Android 7.0
* Fenix version: 1.4.1

**Comment by ekager** [comment] 2019-09-16 14:49
Closing as dupe of #5351

**Closed by ekager** 2019-09-16 14:49 UTC
Labels: 🐞 bug

**Comment by kamran-12** [comment] 2019-09-16 15:57
> Closing as dupe of #5351

Yes, I accidentally posted the same thing twice due to a technical problem. Delete this if possible.
