### ISSUE TITLE
[Bug]: can't secure connection for hourofengineering.com

### ISSUE THREAD

**Issue by JustinWebDev** [mozilla-mobile/fenix#27707] opened 2022-11-04 13:50 UTC
### Steps to reproduce

1. type "hourofengineering.com" in the address bar, go

### Expected behaviour

Firefox should render the page using an HTTPS connection without error.

### Actual behaviour

Firefox says "Secure Connection Failed", indicating the site does not prove its identity.

### Device name

Samsung SM-T280 tablet

### Android version

Android 5.1.1

### Firefox release type

Firefox

### Firefox version

106.1.0

### Additional information

This error also happened on a Windows 11 laptop, but after several retries the page eventually rendered.  I tried on a few other W10 computers and did not see this problem.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21930)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21930

**Comment by kbrosnan** [comment] 2022-11-04 14:52
Incomplete certificate chain. https://www.ssllabs.com/ssltest/analyze.html?d=hourofengineering.com&s=3.213.103.0&latest

Duplicate of bz-1520297

**Closed by kbrosnan** 2022-11-04 14:52 UTC
Labels: 🐞 bug, needs:triage

**Comment by JustinWebDev** [comment] 2022-11-05 23:41
If you don't mind, @kbrosnan how you know the problem is an incomplete chain?  The Qualys site does not give any reason or details for the "B" grade.

**Comment by kbrosnan** [comment] 2022-11-06 00:50
> This server's certificate chain is incomplete. Grade capped to B.
