### ISSUE TITLE
[Bug]: Download Notifications Dissapear Randomly on Android 11

### ISSUE THREAD

**Issue by hazardphotos** [mozilla-mobile/fenix#23631] opened 2022-02-08 05:13 UTC
### Steps to reproduce

Download a file
The download notification appears that illustrate that your download is in progress.
Randomly these notifications "disappear" and cannot be found again
This makes it difficult to determine whether a download has been completed or not.
This behaviour occurs with both small downloads (30mb) or large (2gb) downloads.

### Expected behaviour

It should be possible to see progress of the download
The "download completed" dialog box should appear when each download has been complete - these are closed by selecting the X in the top tight hand corner

### Actual behaviour

Download Notifications just stop appearing at random.
Sometimes the download complete dialogue box does not appear, even if the quiet notification shows download complete
![Screenshot_2022-02-08-05-20-57-38_ffb2f5e1b976ff98cfc94f359fbce8de](https://user-images.githubusercontent.com/99236843/152923369-8f808631-69b5-417e-bb12-c877a2687808.jpg)

### Device name

oppo find x3 pro

### Android version

11

### Firefox release type

Firefox Beta

### Firefox version

97.0.0-beta.6 (Build #2015859995)

### Additional information

![Screenshot_2022-02-08-05-11-39-31_ffb2f5e1b976ff98cfc94f359fbce8de](https://user-images.githubusercontent.com/99236843/152922298-4455dcc3-e3af-4334-910a-4c5e2adffc61.jpg)
![Screenshot_2022-02-08-05-12-45-58_ffb2f5e1b976ff98cfc94f359fbce8de](https://user-images.githubusercontent.com/99236843/152922423-cb9ba169-486d-462d-b903-651e1980b140.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19425)

**Comment by marcel263** [comment] 2022-02-08 12:05
Good day,

Does it also happen when the usage of Nightly?
do you have disabled  battery optimization for both Beta and Nightly?
Does it coincide with loading Firefox through other apps with the Custom Tabs feature? It is a known bug when closing the Custom Tabs, the download stops #20444 

To close, what is shown in the Download screen from the three-dot menu?

**Comment by hazardphotos** [comment] 2022-02-08 17:40
Just to confirm that this issue does NOT appear on the latest Android
nightly as of today 8th Feb 2022

Version 98.0a1 (Build #2015862123), d1b3c4979+

So i will stay on these for a while !

Many Thanks for your kind reply.

**Comment by delia-pop** [comment] 2022-07-28 16:20
Hi, @hazardphotos. This issue is not reproducible on the latest Fenix versions as well. Since there are no other updates from your side either, I will close the ticket. Please re-open if you experience the issue again.

**Closed by delia-pop** 2022-07-28 16:20 UTC
Labels: 🐞 bug, needs:triage
