### ISSUE TITLE
[Bug] Distorted audio in stream from mediaDevices.getUserMedia

### ISSUE THREAD

**Issue by uxmaster** [mozilla-mobile/fenix#19208] opened 2021-04-23 10:46 UTC
## Steps to reproduce
* Go to https://webrtc.github.io/samples/src/content/getusermedia/record/
* Tap [Start camera]
* Allow the access 
* Tap [Start recording]
* Say something
* Tap [Stop recording]
* Play the recorded stuff (tap [Play] or [Download] to play it outside Firefox)

### Expected behavior
The recorded audio should be clear.

### Actual behavior
The recorded audio is distorted, see https://drive.google.com/file/d/1Xr6SbskmGrXO3pfykYlWAonx9WS9Hesa/view

The audio is also distorted when there is no video recorded:
https://kaliatech.github.io/web-audio-recording-tests/dist/#/test1

Or when there is no recording at all, but just sending over WebRTC PeerConnection like at:
https://talky.io or https://speakapp.link

### Device information

* Samsung Galaxy S7 (SM-G930F) and Android version: 8.0.0
* Firefox for Android version: 88.1.1

**Comment by abodea** [comment] 2021-04-29 13:05
Thank you for this report @uxmaster!
I tried to reproduce this on the latest Nightly 4/29 with One PLus nord (10) but I was not able to reproduce it.
Can you try to reproduce it without headphones?

**Comment by kbrosnan** [comment] 2021-05-05 00:33
Sounds like a duplicate of bz-1706131

**Comment by uxmaster** [comment] 2021-05-18 14:38
Actually, I didn't use headphones to record this. I had them on, listening to music from a different device.

The weird thing is when I just a moment ago tried to replicate the issue, the sound was OK. So I reloaded the page and tried again and it was distorted. And every further attempt lead to distorted sound. Also in all today's cases, the distortion starts not from the beginning, but with a 1-2 second delay.

Looks like maybe some resources are not released and they interfere with subsequent recordings...

**Comment by SoftVision-LorandJanos** [comment] 2021-11-18 15:43
This issue is not reproducible. The recorded audio was clear.
Tested on the latest Nightly 96.0a1 (2021-11-18).
Device used: Xiaomi Mi11 Lite (Android 11).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2021-11-18 15:43 UTC
Labels: 🐞 bug, needs:triage, wontfix, qa-triaged
