### ISSUE TITLE
[Bug]cannot open about:config page

### ISSUE THREAD

**Issue by pangyf10** [mozilla-mobile/fenix#16471] opened 2020-11-10 06:37 UTC
# Steps to reproduce
In URL bar, input `about:config` and go.
or open about:about page,click about:config
## Expected behavior
open about:config page
## Actual behavior
open a page，the url is `resource://android/assets/low_and_medium_risk_error_pages.html?&title=Cannot+Complete+Request&button=Try+Again&description=%3Cp%3EAdditional+information+about+this+problem+or+error+is+currently+unavailable.%3C%2Fp%3E&image=&showSSL=false&badCertAdvanced=Advanced%E2%80%A6&badCertTechInfo=%3Clabel%3ESomeone+could+be+trying+to+impersonate+the+site+and+you+should+not+continue.%3C%2Flabel%3E+%3Cbr%3E%3Cbr%3E+%3Clabel%3EWebsites+prove+their+identity+via+certificates.+Firefox+does+not+trust+%3Cb%3Eabout%3Aconfig%3C%2Fb%3E+because+its+certificate+issuer+is+unknown%2C+the+certificate+is+self-signed%2C+or+the+server+is+not+sending+the+correct+intermediate+certificates.%3C%2Flabel%3E&badCertGoBack=Go+Back+%28Recommended%29&badCertAcceptTemporary=Accept+the+Risk+and+Continue`
web page say`Cannot Complete Request`
# Device information

* Android device: Mi 10 pro, android 10
* Fenix version: 82.1.3 release

**Comment by cadeyrn** [comment] 2020-11-10 08:11
This is expected, about:config is only enabled in Nightly and Beta builds.

**Comment by sflorean** [comment] 2020-11-10 17:26
Closing as dupe of #7865.

**Closed by sflorean** 2020-11-10 17:26 UTC
Labels: needs:triage, 🐞 bug
