### ISSUE TITLE
[Bug] regression: many full screen videos and controls scroll

### ISSUE THREAD

**Issue by dbenjaminmiller** [mozilla-mobile/fenix#14820] opened 2020-09-07 14:00 UTC
## Steps to reproduce

1. (may be required) have a screen with a longer than 16:9 aspect ratio
2. Open a page such as https://www.cnn.com/videos/media/2020/09/05/fox-news-donald-trump-atlantic-military-report-contradiction-stelter-bts-nr-vpx.cnn/video/playlists/business-media/ and play the video full screen

### Expected behavior

The video appears in its entirety, fit to the screen. The controls also should be fit to the screen. This is the actual behavior in Fenix 80.1.2 stable release so this is a regression.

### Actual behavior

The entire video and its controls are scrollable up and down in landscape mode.

### Device information

* Android device: Sony Xperia 1 ii /Android 10
* Fenix version: Nightly 200907 06:01 (Build #2015762483)
AC: 58.0.20200904130229, b6c304b2a
GV: 82.0a1-20200902095359
AS: 61.0.13

**Comment by Mugurell** [comment] 2020-09-08 07:56
Based on https://github.com/mozilla-mobile/fenix/issues/14841 seems like the issue is a bit older.

**Comment by Mugurell** [comment] 2020-09-08 08:18
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1663591for this.

**Comment by dbenjaminmiller** [comment] 2020-09-08 11:02
Interesting that for me it's not a problem on release.

**Comment by Mugurell** [comment] 2020-09-08 11:33
For me this is also an intermittent issue.

**Comment by neatwheat** [comment] 2020-10-09 10:41
Can confirm the issue for 
82.0.0-beta.2 (Build #2015766793) too

**Comment by Mugurell** [comment] 2020-10-12 07:36
Based on the comments from https://bugzilla.mozilla.org/show_bug.cgi?id=1659761 this should have been fixed in Nightly but also Beta (using >= GV 81).
QA, can you please confirm? Maybe we should reopen the GV issue if this is still not fixed.

**Comment by sflorean** [comment] 2020-10-13 14:03
Tested on Nightly 10/13 and Beta 82.0.0 - beta.4 (Play Store version) and couldn't reproduce the issue. 
Devices:
- Samsung Galaxy Note10 (Android 10)
- Motorola Nexus 6 (Android 7.1.1)
- Google Pixel 3 (Android 11)

**Comment by Mugurell** [comment] 2020-10-14 06:21
> Can confirm the issue for
> 82.0.0-beta.2 (Build #2015766793) too

If this is still an issue for you on nightly / beta can you please tell us on which exact video (link?) you've encountered this issue?
Any other details that might belp us in reproducing it?
Maybe there's another separated issue or something particular to a certain website.

**Comment by viraniac** [comment] 2020-11-22 11:41
I am on firefox for android version 83 and am also facing this issue. The video plays fine on some sites like youtube and engadget but not on others. For some sites, videos gets stretched and the controls goes out of the screen in landscape fullscreen mode and I have to scroll the video to access controls.

Here are some details that might help
Device: Oneplus 5t
Resolution: 18:9
video url: https://www.dailymotion.com/video/x7xes6a

I have my address bar at the top. and I have my bottom navigation bar hidden.

**Comment by michaeldel** [comment] 2021-02-15 16:55
I still have the same bug on Firefox 85.1.1. MIUI Global 11.0.2 stable (Android 7.1.2). I have the address bar at the top, which seems to cause other strange scrolling behavior like #17396 that I encounter as well.

**Comment by Mugurell** [comment] 2021-02-15 18:04
Using the two links from https://github.com/mozilla-mobile/fenix/issues/14820#issuecomment-731734856 I indeed see some issues in the current Release but on the current Nightly (v. 87) the videos look okay.
@viraniac @michaeldel can you please confirm if this is still an issue for you on the current Nightly?

**Comment by viraniac** [comment] 2021-02-15 18:15
@Mugurell,


Nightly seems to be working fine for videos. The current release does't
show the reference links properly when I click on the numbers in the
wikipedia text. This seems to have been resolved in Nightly too.

Thanks & Regards
Gunjan Gupta

**Comment by michaeldel** [comment] 2021-02-24 08:15
@Mugurell it seems fixed on nightly to me as well.

**Comment by Mugurell** [comment] 2021-02-24 09:47
I guess we can close this then.
Thank you all!

**Closed by Mugurell** 2021-02-24 09:47 UTC
Labels: S3, 🐞 bug, 🙅 waiting
