### ISSUE TITLE
[Bug] Persistent notification for private mode

### ISSUE THREAD

**Issue by siddhugolu** [mozilla-mobile/fenix#5207] opened 2019-09-11 06:52 UTC
## Steps to reproduce
Open a private tab.
Go to the notification bar and select the option for "DELETE AND OPEN"
Exit the browser.
Pull down the notification bar again. The Firefox Private bar is still there.

![bug](https://user-images.githubusercontent.com/9106868/64674584-c9f17580-d48e-11e9-9aa7-1b06d5a80bc1.png)

### Expected behavior
There shouldn't be any persistent notification for private mode. Even there is one, it should go away when the private mode is exited.
### Actual behavior
Persistent notification is displayed, despite exiting the app.
### Device information

* Android device: Mi A1 Android 9
* Fenix version: 1.4.0

**Comment by cadeyrn** [comment] 2019-09-11 07:04
> There shouldn't be any persistent notification for private mode

I disagree. It's a great feature already known from other browsers like Firefox Focus and Chrome.

> Even there is one, it should go away when the private mode is exited.

Switching to the Android home screen is not "exiting the app". You can use the Android recent apps view to really "exit" the app. If you use the recent apps screen the notification goes away.

The notification should go away if there are zero private tabs. And that's a bug in Firefox Preview 1.4 beause it doesn't work. But it's already fixed in Firefox Preview Nightly.

**Comment by neekless** [comment] 2019-09-11 17:13
Fixed in https://github.com/mozilla-mobile/fenix/commit/bb2a685ad9d632030dffe81d773facb2c6559fdb

**Comment by ekager** [comment] 2019-09-12 03:14
Yes this should be fixed in the next release. Closing as a dupe of #5075

**Closed by ekager** 2019-09-12 03:14 UTC
Labels: 🐞 bug
