### ISSUE TITLE
Make collections and contents sortable/drag 'n drop-able

### ISSUE THREAD

**Issue by x2k13** [mozilla-mobile/fenix#8807] opened 2020-02-27 06:52 UTC
### Why/User Benefit/User Problem
Collections and their contents are sorted on a "added last" basis, making them sortable by different criteria would add a better handling of collections.
### What/Requirements
Add a function to sort collections and their contents, preferably making collections and their contents drag 'n drop-able (like Vivaldi or Opera already have it).
### Acceptance Criteria (how do I know when I’m done?)
When we can sort/drag'n drop collections and their contents freely.

**Comment by cadeyrn** [comment] 2020-02-27 07:11
Duplicate of #8141.

**Closed** 2020-03-16 12:13 UTC
Labels: Feature:Collections, needs:triage, 🌟 feature request
