### ISSUE TITLE
I can no longer queue tabs in Fenix[Bug]

### ISSUE THREAD

**Issue by Shadowspear123** [mozilla-mobile/fenix#16005] opened 2020-10-18 16:33 UTC
## Steps to reproduce

Click on a web link in another app on your phone.

In Fennec, if you had the tab queue option enabled, the link would load up in the background and you would get a notification that there is a tab (or tabs) waiting. The tabs would be open the next time you opened Fennec.

### Expected behavior

There should be an option to open links in the background.

### Actual behavior

Te link opens immediately in fenix and is not queued in the background. 

### Device information

* Android device: Galaxy S8, Android 8.0
* Fenix version: 81.1.3

*Might be related but is an old issue:  #470

**Comment by cadeyrn** [comment] 2020-10-18 18:36
As you already noticed it's a duplicate of #470. Yes, it's "old" but still open.

**Comment by Poopooracoocoo** [comment] 2020-10-19 02:53
they probably feel like mozilla isn't listening to them as they've locked the issue. they can't even react to that issue.

**Comment by gabrielluong** [comment] 2020-10-19 03:36
Hi all, thanks for filing this. This is someone I am interested in investigating. Looking at #470, it seems like it was prioritized for investigating in Q2 of this year and probably fell off the radar. While I can't promise anything in the short term, I will bring this feature up and hope to take it on in the near future. In the meantime, I am gonna refer everyone back to #470 for this feature. Thanks!

**Closed by gabrielluong** 2020-10-19 03:36 UTC
Labels: needs:triage, 🐞 bug

**Comment by ericrbg** [comment] 2020-10-27 12:30
Gabriel, is there any chance that #470 could be opened to discussion again? It'd be nice if we could have some updates on it, as opposed to the apparent radio silence on the issue.

**Comment by Poopooracoocoo** [comment] 2020-10-27 12:52
but there's not much to discuss, is there? The Mozilla peeps can still add comments for their mock-ups and stuff. there are some other issues that are locked but should be unlocked. and in the case of the issue about an option to show the full url, there's not much to be said that no one else has already said
