### ISSUE TITLE
[Bug]  Review Firefox preview -Font is too small

### ISSUE THREAD

**Issue by FisaVuma** [mozilla-mobile/fenix#9587] opened 2020-04-01 13:41 UTC
## Steps to reproduce
Installed Firefox preview on Samsung S10 plus and Samsung S10
### Expected behavior
Application to pick device settings or give option to set on installation
### Actual behavior
Font too small by default. 
Does not pick up device settings
Smaller font is used on open tabs and Search page
### Device information
* Android device: Samsung S10 plus and Samsung S10
* Fenix version: Firefox preview 4.1.0 (Build #20771637)

**Comment by Diana-Rus** [comment] 2020-05-12 14:00
Hi, could you please try with the latest version of Firefox Preview Release. The latest available version on Play Store is now 5.0.0 (Build #21212137)

Note:
You also have in browser's Settings/Accessibility/Automatic font sizing - option.

@FisaVuma - In case you still reproduce your problems can you provide a video or screenshot with your issue?

**Comment by softvision-miralobontiu** [comment] 2020-10-20 13:39
I cannot reproduce this issue on the latest Nightly build from 10/20 on Samsung Galaxy Note 8 (Android 9), and Samsung Galaxy Tab S6 (Android 10). And since the reporter hadn't replied, I'll close this issue.

**Closed by softvision-miralobontiu** 2020-10-20 13:39 UTC
Labels: needs:triage, 🐞 bug
