### ISSUE TITLE
Very slow to search stored passwords

### ISSUE THREAD

**Issue by abda11ah** [mozilla-mobile/fenix#22795] opened 2021-12-10 21:38 UTC
I have the latest firefox stable build on android 7.1.2 from playstore.
I have hundreds of passwords stored online and the search interface (filter passwords by domains) is very slow (about 5sec or more to filter them).
On chrome or vivaldi it is quick, like a real time filtering.

**Comment by MarcLeclair** [comment] 2021-12-16 01:18
Hey @abda11ah , thank you for reporting this! Would you be able to grab a profile when trying to search for your password? 

Just follow the steps over here: https://profiler.firefox.com/docs/#/./guide-remote-profiling. It would really help to diagnose the issue here! 

Also, would you mind sharing your what Android device you have?

Thank you!

@mcomella  Could you try to reproduce this?

**Comment by abda11ah** [comment] 2021-12-16 07:32
My device is a Meizu M6 Note running Android 7.1.2 (LineageOS 14.1)

**Comment by mcomella** [comment] 2021-12-20 23:59
I was able to reproduce: I have 104 logins and there is a small (1s subjective?) user perceptible delay between typing a character and the results on my Moto G5. I can imagine this delay gets longer for more logins.

I took a profile: https://share.firefox.dev/3qc0ntl There is a ~50ms measure/layout/draw delay but otherwise we don't see anything including the onTextChanged listeners that dispatched this call even when we increase the sampling rate: https://share.firefox.dev/3yOGvAG

**Comment by pbhj** [comment] 2021-12-29 11:06
Well this was weird for me: I normally have very slow listing of the logins on search, but when I checked now (repeating a search I'd done since opening the browser) it was very quick, instantaneous even. That's not always the case, for router addresses it's almost impossible to tell which of the 192.168.1.1 admin in list is the one you want, each search they seem to change order, and you can't seem to go back to the search list so you have to repeat the several seconds long search over and over, the delay makes it even more infuriating.

**Comment by mcomella** [comment] 2022-01-06 00:57
Triage: @mcomella will get a profile with all the JVM threads to understand which code is at fault. If it's native or the stack clearly indicates it, we can ping the app services team if they know what's happening.

Side thought: could this delay also happen for autofill?

**Comment by mcomella** [comment] 2022-01-06 18:24
I found large delays in the JVM stack. It appears that the way we sort is slow. This thread seems to receive the initial background dispatch: https://share.firefox.dev/3pZmbcM It seems our sorting is slow, which [calls `urlToTrimmedHost` for each item](https://searchfox.org/mozilla-mobile/rev/8c43e50f46628bf8e65434911c2f2e3f9b2a82ef/fenix/app/src/main/java/org/mozilla/fenix/settings/logins/SortingStrategy.kt#15):
```kotlin
return logins.sortedBy { it.origin.urlToTrimmedHost(publicSuffixList) }
```

Though the stack is broken into many subtrees, [`StringKt.urlToTrimmedHost`](https://searchfox.org/mozilla-mobile/rev/8c43e50f46628bf8e65434911c2f2e3f9b2a82ef/android-components/components/lib/publicsuffixlist/src/main/java/mozilla/components/lib/publicsuffixlist/ext/String.kt#17) gets called in 217/222 samples so it's the likely bottleneck and we can focus on it to see what's slow: https://share.firefox.dev/3eVTLKm **Most of the time is spent waiting on another thread**, some amount of time in `getHostWithoutCommonPrefixes` (though there's high overhead with this profiler so it might be overrepresented), and some time in coroutine overhead.

wrt waiting on another thread, the [only async function is `stripPublicSuffix`](https://searchfox.org/mozilla-mobile/rev/8c43e50f46628bf8e65434911c2f2e3f9b2a82ef/android-components/components/lib/publicsuffixlist/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixList.kt#128). The function dispatches to different default dispatcher threads (four total), making it more difficult to analyze. We seem to get non-trivial samples from methods like `mozilla.components.lib.publicsuffixlist.PublicSuffixList$stripPublicSuffix$1.invokeSuspend` (48 = 7 + 11 + 17 + 13. So  ~480ms) but also spend a lot of time in the coroutine dispatching code (it almost seems as if most of the threads are involved in each key typed – is this getting thrown between multiple threads? I don't see other suspension points though).

So **I think the primary issue is that `stripPublicSuffix` takes a long time to run when called many times.** I don't think stripping the suffix would improve alphabetical sorting so I think we can just remove that line and see if performance is acceptable. Also, it seems unnecessary to dispatch for `stripPublicSuffix` given we're already on a background thread so I think that'd be a welcome optimization too (reducing coroutine overhead, avoiding clogging up the default dispatchers, and saving battery).

**Comment by mcomella** [comment] 2022-01-06 18:37
csadilek pointed out every call of `sortedBy`'s lambda hits the `scope.async` and that's why the observed coroutine overhead may be so high.

**Comment by mcomella** [comment] 2022-01-06 19:41
If needed, here's my patch to capture profiles of background threads using the `Debug` API (since the Firefox profiler doesn't support background threads yet): [profile.patch.zip](https://github.com/mozilla-mobile/fenix/files/7824307/profile.patch.zip)

**Comment by grigoryk** [comment] 2022-01-11 22:56
Just hit this on my Nexus 6P, it's absolutely unusably slow there with my profile (I have a few hundred login records).

**Comment by grigoryk** [comment] 2022-01-11 23:31
I entirely agree with: "I don't think stripping the suffix would improve alphabetical sorting" - we're sorting by `origin`, so it doesn't really matter what the suffix is for alphabetical sorting, and actually it could result in non-stable sorting order for origins such as `amazon.ca` vs `amazon.com`.

Confirmed locally that yes, this solves the performance problem and search is nice and snappy for me locally now on an old/slow device.

I'll fix up another little problem I saw w/ this UI and will push up a patch.

**Comment by grigoryk** [comment] 2022-01-11 23:48
Looking back through commits, doesn't seem like there's a particularly good reason we were trimming here. All I could find is https://github.com/mozilla-mobile/fenix/pull/9986#discussion_r420638558 which is lacking explanation of why this is actually useful.

And currently, we're dealing with an `origin` (not a full `url` when this was initially written, I think), i.e. `https://accounts.firefox.com` vs `https://accounts.firefox.com/signin`. So, the suffix stripping isn't even doing much beyond removing `com` in vast majority of cases.

So, seems like all of this trimming stuff can be cleaned up.

**Comment by grigoryk** [comment] 2022-01-12 01:33
https://github.com/mozilla-mobile/fenix/pull/23163 makes this work very nicely for me - fast, and scroll position is now reset to the first item after changing search terms or changing sort type.

**Comment by grigoryk** [comment] 2022-01-13 20:36
The fix is now available on Nightly, and should make its way to Beta sometime soon. Closing the issue, please feel free to re-open if you're still having problems with the logins search functionality.

Thanks for filing!

**Closed by grigoryk** 2022-01-13 20:36 UTC
Labels: performance, Feature:Logins

**Comment by LaurentiuApahideanSV** [comment] 2022-01-17 11:46
I tested the issue on Firefox Beta 97.0.0-Beta.2 and Nightly 2022-01-17. The search speed in the "Logins and passwords" section has been greatly improved compared to Firefox RC 96.1.1.

### Device used:
- Huawei MediaPad M3 (Android 7.0)
