### ISSUE TITLE
FNX-12054 ⁃ [Bug] The Fenix Share Sheet is missing several items

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11177] opened 2020-06-03 08:12 UTC
## Steps to reproduce
The Fenix Share Sheet is missing several apps that can be shared to: Add to Pocket, WhatsApp, Discord, Wikipedia search, Mega, Twitter's Direct Message, RAR etc...

But the `77.0.0-beta.1` contains all share shortcuts

### Expected behavior
The share sheet should contain all items/apps that can  be shared to

### Actual behavior
The Share Sheet doesn't contain all app share targets

### Device information
* Android device: Motorola One Power, Android 10
* Fenix version: Nightly 200603 06:00

**Comment by cadeyrn** [comment] 2020-06-03 09:24
Pocket and Twitter Direct Message are available on my device. But I can confirm that WhatsApp and a few others are missing in Fenix but not in Firefox Beta.

**Comment by neekless** [comment] 2020-06-09 17:22
Mine has WhatsApp as an available share target. What's interesting is I no longer have Telegram X as an available target, which is strange because I've used sharing to Telegram X plenty of times in past versions. I'm not sure from which version did I start losing Telegram X share target. Could it be that Fenix has a fixed limit on number of share targets thus some would not be shown?
![Screenshot_20200610-011704](https://user-images.githubusercontent.com/22426822/84179550-a9823600-aa75-11ea-8f71-d4ca9ba16dfe.png)

**Comment by SS1113** [comment] 2020-06-09 19:55
@neekless I don't think developers have done this intentionally. Since it is really important that all share targets are presented in the share sheet otherwise how do you expect to share/open in app the links if the particular app is not there? I cannot even share links to copy them!

**Comment by gabrielambuehl** [comment] 2020-06-12 19:04
That seems to have fixed it for me after installing today's build.

**Comment by SS1113** [comment] 2020-06-12 19:35
This is fixed for me as well.

Tested on: Motorola One Power, Android 10.
Fenix: Nightly 200612 18:01.

**Comment by abodea** [comment] 2020-06-15 15:08
Verified as fixed on the latest **Nightly 6/15** with **Google Pixel 4 XL (10).**

**Closed** 2020-08-11 03:21 UTC
Labels: Feature:ShareSheet, eng:qa:verified, eng:ready, 🐞 bug
