### ISSUE TITLE
Crash in [@ mozilla::a11y::RemoteAccessibleBase<T>::Shutdown]

### ISSUE THREAD

**Issue by freakedenough** [mozilla-mobile/fenix#23365] opened 2022-01-22 08:14 UTC
Crash report: https://crash-stats.mozilla.org/report/index/4b3e4775-6175-4820-a59b-06a740220122

MOZ_CRASH Reason: ```MOZ_DIAGNOSTIC_ASSERT(!IsDoc())```

Top 10 frames of crashing thread:
```
0 libxul.so mozilla::a11y::RemoteAccessibleBase<mozilla::a11y::RemoteAccessible>::Shutdown accessible/ipc/RemoteAccessibleBase.cpp:63
1 libxul.so mozilla::a11y::DocAccessibleParent::ShutdownOrPrepareForMove accessible/ipc/DocAccessibleParent.cpp:185
2 libxul.so mozilla::a11y::DocAccessibleParent::ShutdownOrPrepareForMove accessible/ipc/DocAccessibleParent.cpp:194
3 libxul.so mozilla::a11y::DocAccessibleParent::ShutdownOrPrepareForMove accessible/ipc/DocAccessibleParent.cpp:194
4 libxul.so mozilla::a11y::DocAccessibleParent::ShutdownOrPrepareForMove accessible/ipc/DocAccessibleParent.cpp:194
5 libxul.so mozilla::a11y::DocAccessibleParent::ShutdownOrPrepareForMove accessible/ipc/DocAccessibleParent.cpp:194
6 libxul.so mozilla::a11y::DocAccessibleParent::RecvHideEvent accessible/ipc/DocAccessibleParent.cpp:244
7 libxul.so mozilla::a11y::PDocAccessibleParent::OnMessageReceived ipc/ipdl/PDocAccessibleParent.cpp:8391
8 libxul.so mozilla::dom::PContentParent::OnMessageReceived ipc/ipdl/PContentParent.cpp:6479
9 libxul.so mozilla::ipc::MessageChannel::MessageTask::Run ipc/glue/MessageChannel.cpp:1851
```

**Comment by cadeyrn** [comment] 2022-01-22 15:42
Same crash signature as in #23346 that was closed as an duplicate of the upstream issue https://bugzilla.mozilla.org/show_bug.cgi?id=1751268.

**Closed** 2022-01-22 18:30 UTC
Labels: needs:triage
