### ISSUE TITLE
[Bug]: no input keyboard when input sync password

### ISSUE THREAD

**Issue by wxie2017** [mozilla-mobile/fenix#20503] opened 2021-07-26 04:36 UTC
### Steps to reproduce

1. open Firefox for Android
2. menu -> sign in to sync
3. use email instead
4. tap password

### Expected behaviour

The input keyboard should come up for input password.

### Actual behaviour

No input keyboard, so I cannot input any thing.

### Device name

redmi Note 5A

### Android version

Android 7.1.2

### Firefox release type

Firefox Nightly

### Firefox version

90.1.2 (Build #2015823033)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17357)

**Comment by LaviniaL99** [comment] 2022-01-20 13:59
Hello @wxie2017 

Thanks for your report!
I tested the above issue on the latest Nightly 98.0a1 (2022-01-20) and I was not able to reproduce the issue.

**Devices used:**

- Samsung S10E -> Android 10
- Samsung Galaxy A32 5G -> Android 11

Can you retest the flow on the latest build and let me know if you are still able to reproduce the issue? If yes, please attach a video for it.

**Comment by wxie2017** [comment] 2022-03-07 23:51
Hi, LaviniaL99:

The issue was tested under xiaomi Mi8 with LineageOS 18.1 (Android 11)
for Firefox 97.2.0.
The issue is not reproduced.

wxie

在 2022-01-20星期四的 06:00 -0800，LaviniaL99写道：

**Comment by fice-t** [comment] 2022-10-16 16:42
@SoftVision-LorandJanos Seems like this can be closed.

**Comment by SoftVision-LorandJanos** [comment] 2022-10-24 14:11
Since this issue wasn't and is not reproducible, I'll close this ticket.

**Closed by SoftVision-LorandJanos** 2022-10-24 14:11 UTC
Labels: 🐞 bug, S3, needs:triage, Feature:IME, qa-triaged
