### ISSUE TITLE
FNX-4940 ⁃ [Telemetry] Add uri_count to ping

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#1301] opened 2019-04-01 13:05 UTC
Similar to Focus: https://github.com/mozilla-mobile/focus-android/blob/master/docs/Telemetry.md#uri-count

#### What questions will you answer with this data?
* As a product manager, I want to know how many websites URIs are being visited per session

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
* The amount of URI count is a good indicator for us to know how useful and sticky the app is

#### What probes (suggested, if applicable)
* URI count, see row 30 in https://docs.google.com/spreadsheets/d/1P2_aGEE9OtjM3x71d0GBhnHDhzxEL02xEHuKn1no23E/edit#gid=0
* similar to Focus

### Dependencies (Added by PM and Eng)
* Needs a ping which resets per session

### Acceptance Criteria (Added by PM)
* Baseline pings can be queried via re:dash
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
* NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by boek** [comment] 2019-04-18 16:40
This can be done pretty easily with the `counter` metric type

**Comment by bsurd** [comment] 2019-05-17 12:49
The [total_uri_count](https://github.com/mozilla-mobile/fenix/blob/master/app/metrics.yaml#L126) is not displayed in the events when sending telemetry. Looked in both baseline and events JSON files and the data wasn't available anywhere.

**Comment by colintheshots** [comment] 2019-06-05 17:15
total_uri_count should be in the metrics ping. I noticed a new regression from last week that might cause some URI counts to not get counted and I'm fixing it.

```
    val totalUriCount: CounterMetricType by lazy {
        CounterMetricType(
            name = "total_uri_count",
            category = "events",
            sendInPings = listOf("metrics"),
            lifetime = Lifetime.Ping,
            disabled = false
        )
    }
```

**Comment by colintheshots** [comment] 2019-06-05 19:31
It should now be moved to the baseline ping.

**Comment by vesta0** [comment] 2019-06-10 15:10
@colintheshots I re-added the QA needed label based on your comment.

**Comment by AndiJoltan** [comment] 2019-06-11 09:36
Hi all, the **uri_count total_uri_count is now sent with the baseline ping**, it works.

#### Please find attached and review the following:
•1 search performed: Logcat: [UriCount3.txt](https://github.com/mozilla-mobile/fenix/files/3275710/UriCount3.txt)
	            Glean Dashboard:https://debug-ping-preview.firebaseapp.com/pings/2311bde3-47fc-4272-9a8b-b1cce4e7eaf5/aj-uritest-04

•4 searches performed: Logcat: [UriCount1.txt](https://github.com/mozilla-mobile/fenix/files/3275717/UriCount1.txt)
	              Glean Dashboard: Glean Dashboard:https://debug-ping-preview.firebaseapp.com/pings/2311bde3-47fc-4272-9a8b-b1cce4e7eaf5/aj-uritest-00

•8 searches performed: Logcat: [UriCount2.txt](https://github.com/mozilla-mobile/fenix/files/3275713/UriCount2.txt)
	              Glean Dashboard: (second baseline) https://debug-ping-preview.firebaseapp.com/pings/2311bde3-47fc-4272-9a8b-b1cce4e7eaf5/aj-uritest-03


Before closing this ticket, in order to have a better understanding regarding the` search_count VS uri_count ` I would like to ask, **why the uri_count is always higher than the search_count ? what is the difference between the two?**
Please review the above attached logs and confirm if from your point of view the uri_count works properly.

Until then, based on this comment I'll remove the QA needed label.

**Comment by sblatz** [comment] 2019-06-25 16:20
@colintheshots or @boek are you able to explain [this behavior](https://github.com/mozilla-mobile/fenix/issues/1301#issuecomment-500766118)?

**Comment by boek** [comment] 2019-06-26 00:23
Looks like there is a bug that is causing UriOpened to get called an extra time in a session. I filed a follow up bug #3676 and we can track/fix it there.

**Comment by boek** [comment] 2019-06-26 00:24
@WhoIsAndi

**Comment by WhoIsAndi** [comment] 2019-06-26 08:16
@boek sure thing ! I'll go ahead and close this issue.

**Closed** 2020-08-11 08:19 UTC
Labels: Feature:Telemetry, P1
