### ISSUE TITLE
[Bug] Intermittent test failure debug(T) process intent with flag launched from history followed by java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#15981] opened 2020-10-16 22:41 UTC
Log: https://treeherder.mozilla.org/logviewer.html#/jobs?job_id=318864655&repo=fenix&lineNumber=12344

```
[task 2020-10-16T18:50:41.807Z]   TEST: process intent with flag launched from history
[task 2020-10-16T18:50:41.807Z]     [Robolectric] org.mozilla.fenix.IntentReceiverActivityTest.process intent with flag launched from history: sdk=28; resources=BINARY
[task 2020-10-16T18:50:45.807Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-10-16T18:50:47.807Z]     Oct 16, 2020 6:50:47 PM io.mockk.impl.log.JULLogger warn
[task 2020-10-16T18:50:47.807Z]     WARNING: Failed to transform class org/mozilla/fenix/ext/ContextKt
[task 2020-10-16T18:50:47.807Z]     java.lang.OutOfMemoryError: GC overhead limit exceeded
[task 2020-10-16T18:50:47.807Z]     
[task 2020-10-16T18:51:51.608Z]   FAILURE
[task 2020-10-16T18:51:51.708Z] 
[task 2020-10-16T18:51:51.709Z] java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by Archaeopteryx** [comment] 2020-10-20 20:17
@pocmo  These `java.lang.OutOfMemoryError: GC overhead limit exceeded` are frequently failing debug(T) runs. Can you take a look at this?

**Comment by JohanLorenzo** [comment] 2020-11-03 16:14
Duplicate of https://github.com/mozilla-mobile/fenix/issues/16262. That one has more info. Let's continue the conversation there.

**Closed by JohanLorenzo** 2020-11-03 16:14 UTC
Labels: 🐞 bug
