### ISSUE TITLE
Tab Tray should expand to top of screen when navigation toolbar is set to the top

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14909] opened 2020-09-09 21:17 UTC
Like https://github.com/mozilla-mobile/fenix/issues/11298 but I think this fits in with the Android platform a bit better. 

### What is the user problem or growth opportunity you want to see solved?

Users who prefer a top toolbar layout have different needs and preferences than those using the bottom toolbar layout. Some of those users who were Fennec users are looking at other options because our layout is currently geared towards a bottom toolbar layout by default. 

Google Voice has a nice example of this - not by default, but a tray that can be extended to the top of the screen. We can do this instead by default for top toolbar users (extended to top), while allowing making it smaller like we do in the default layout. 

Here's a short video demonstrating:

![signal-2020-09-09-170917](https://user-images.githubusercontent.com/152493/92655422-611a2480-f2bf-11ea-8e46-e73c722c44ca.gif)

### How do you know that this problem exists today? Why is this important?

Play Store reviews, social media conversations. It is important to demonstrate that we listen to feedback and also to simply provide a better experience. Users have noted  that because the new tab button is a FAB, they cannot use the double tap to open a new tab maneuver still available to bottom toolbar users (eg https://github.com/mozilla-mobile/fenix/issues/14403) - this would be a prerequisite for that feature. 

### Who will benefit from it?

Anyone who is using a top toolbar layout or prefers [not to use gestures](https://github.com/mozilla-mobile/fenix/issues/14911) in this instance.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6642)

**Comment by cadeyrn** [comment] 2020-09-09 21:23
You already know that it's a duplicate of #11298. Why do we need another issue for the same request? 🤔

**Comment by yoasif** [comment] 2020-09-09 21:32
@cadeyrn it is not the same request - I don't think it is a duplicate.

**Comment by boek** [comment] 2023-01-27 01:50
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812911

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-27 01:50 UTC
Labels: feature request 🌟, Feature:Toolbar, Feature:Tabs
