### ISSUE TITLE
FNX-5190 ⁃ [Bug] No snackbar is displayed when a tab is closed

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#1694] opened 2019-04-17 13:43 UTC
## Steps to reproduce
1. On the home screen, go to Current session.
1. Close a tab.

### Expected behavior
There is no snackbar displayed.

### Actual behavior
A snackbar with an "Undo" button should be displayed.

### Device information
* Android device: Sony Xperia Z5 (Android 7.1.1)
* Fenix version: 1.0.1916 (Build#11061212)

![2019](https://user-images.githubusercontent.com/40694158/56292152-4b86e680-612f-11e9-8f37-3347467cbe2b.gif)UNITO-UNDERSCORE!04!UNITO-UNDERSCORE!17!UNITO-UNDERSCORE!15!UNITO-UNDERSCORE!59!UNITO-UNDERSCORE!42!

**Comment by vesta0** [comment] 2019-04-30 05:00
@softvision-miralobontiu is there an undo button in the UX specs?

**Comment by yoasif** [comment] 2019-04-30 05:53
Fennec shows an undo snackbar once a tab is closed, FYI.

**Comment by vesta0** [comment] 2019-05-01 17:39
I don't think this is necessary (they can always access it from history if it was closed accidentally) but I will leave it to UX to think through FYI @lime124

**Comment by yoasif** [comment] 2019-05-01 21:32
At least on my Moto G, it is far too easy to close a tab while simply trying to scroll through the home view, so a snackbar would really be appreciated. 

The only other browser on Android (besides Focus) that I have seen that doesn't use a snackbar to allow a user to reopen closed tabs is Samsung Internet, and *it* has a menu option in the tab switcher to "reopen closed tab" (a little like Firefox Desktop's undo closed tab in the tab menu). 

History feels far too hard to discover on accidental close, at least imo.

**Comment by topotropic** [comment] 2019-05-02 08:26
Let's display a undo snackbar – please use the same display time as we use for other undo snackbars (for example the delete bookmark one).

**Comment by lime124** [comment] 2019-05-02 20:55
@vesta0 i think this should be a p1 as this creates a pretty bad experience when people accidentally close their tabs. it's not data loss b/c it can be recovered from history, but when it's easy to make mistakes we should make it easy to recover.

**Comment by ekager** [comment] 2019-05-02 20:57
Part of the Collections Spec is a Snackbar with UNDO action for Collections and Tabs within collections. It will be simple to also hook this action up for the tabs in the normal tab view.

**Comment by bsurd** [comment] 2019-05-06 07:57
The snackbar is now displayed whenever closing a tab. Logged #2289 for the undo action as it does not work as intended.

**Closed** 2020-08-11 12:30 UTC
Labels: Feature:HomeScreen, Feature:Tabs, P1, eng:qa:verified, eng:ready, 🐞 bug
