### ISSUE TITLE
[Bug] The Saved Logins section is dismissed when resuming Fenix from a multitask to another app

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#6618] opened 2019-11-15 13:34 UTC
## Steps to reproduce
1. Launch Fenix.
2. Access the `Passwords` section from the settings menu.
3. Tap on `Saved logins`(unlock it if biometrics or pin is set).
4. Add Fenix to the background or multi-task to another app. 
5. Resume Fenix.
### Expected behavior
Saved logins with all the passwords section are still displayed.
### Actual behavior
The Saved Logins screen is dismissed and the user is returned to the previous screen.
### Device information

* Android device: **`Google Pixel 3a XL(Android 10).`**
* Fenix version: **`Nightly 11/15`**
![ezgif-1-c2420e9b32b7](https://user-images.githubusercontent.com/42831109/68946977-f2625c80-07bc-11ea-9b53-9d4382805998.gif)

**Comment by hakkikaancaliskan** [comment] 2019-11-15 15:16
Isn't this expected behavior for security.
Also for that fragment, they should set secure flags to hide password from app switcher.

**Comment by ekager** [comment] 2019-11-15 21:22
Correct this is the intended behavior. In both of the logins fragments we are popping out on pause. Closing this bug.

**Closed by ekager** 2019-11-15 21:22 UTC
Labels: Feature:Logins, S2, 🐞 bug
