### ISSUE TITLE
Share options should use vertical scroll to keep with consistency with the rest of the app

### ISSUE THREAD

**Issue by jcosentino** [mozilla-mobile/fenix#14493] opened 2020-08-30 14:49 UTC
I think that the share options (Click share icon, options pop up) should be vertically scrollable, but they're currently horizontally scrollable. I feel that this is inconsistent with how the rest of the app behaves. For example, traversing the settings and dismissing the new tab page are both vertical.
See: https://imgur.com/cYRiWno

**Comment by ekager** [comment] 2020-12-18 05:45
Closing as duplicate of #9411

**Closed by ekager** 2020-12-18 05:45 UTC
Labels: needs:triage
