### ISSUE TITLE
navigation bar overlap

### ISSUE THREAD

**Issue by Terredombres** [mozilla-mobile/fenix#14377] opened 2020-08-28 17:31 UTC
Very frustrating issue with the navigation bar being located at the bottom and not disappearing when scrolling down, thus completely blocking access to the typing block and send button on chat pages.

**Comment by cadeyrn** [comment] 2020-08-28 18:12
Unfortunately you forgot to mention the affected site. Without this information it's not able for Mozilla or others to check your issue. It should work on most websites but it's known that it's not working on all websites in Firefox 79 (which version do you use?). Maybe it's already fixed in Beta or Nightly. Could you provide the missing information?

**Comment by Terredombres** [comment] 2020-08-28 18:37
Hi,
Yes it was on "offer up". Because the text of sent messages is about the
length of the screen (which you can scroll through), and the space to write
new messages has a height of almost the same as the navigation bar, it's
virtually impossible to scroll down and swipe from the very bottom of the
page because the navigation bar blocks that bottom part of the page. The
navigator thinks I'm just scrolling through the most recent sent message,
when really I'm trying to access the space to send new messages. I had to
download Chrome to be able to pursue that conversation.
Thanks for your attention to this,
Cecile

**Comment by s-ankur** [comment] 2020-08-28 18:50
Hello Cecile, could you tell us which website you had this problem on?

**Comment by Terredombres** [comment] 2020-08-28 19:01
The website called offer up.

**Comment by yoasif** [comment] 2020-08-28 19:10
I can reproduce the issue:

![signal-2020-08-28-150727](https://user-images.githubusercontent.com/152493/91606711-9712ec80-e940-11ea-9799-eaf160c16a0e.gif)

**Comment by s-ankur** [comment] 2020-08-28 19:13
Seems like a duplicate of  #14361

**Comment by yoasif** [comment] 2020-08-28 19:14
@s-ankur that issue seems to be resolved in Nightly, FWIW.

**Comment by s-ankur** [comment] 2020-08-28 19:16
There's actually a large number of issues about this  #13797,  #14070 etc. I'm not sure all are resolved

**Comment by Terredombres** [comment] 2020-08-28 19:30
Alright,  thank you for your feedback, I appreciate it. I'm not sure what
are the perks of having the navigation bar at the bottom.

**Comment by s-ankur** [comment] 2020-08-28 19:42
For users whose phones have larger screens it can be difficult to reach the navigation bar with your thumb if it is at the top. So we have a bottom option

For now you can change the navigation bar to top. Go to settings then open customize and then in toolbar section click on top. You will then have the navigation bar at the top, like Chrome does so you wont have to deal with this problem

As for this problem, I am sure it will be soon resolved as well.

**Comment by Terredombres** [comment] 2020-08-28 19:52
Oh perfect, thank you!!

**Comment by liuche** [comment] 2020-08-28 22:01
These all seem related, so going to consolidate them to #13797

**Closed by liuche** 2020-08-28 22:01 UTC
Labels: needs:triage
