### ISSUE TITLE
Ability to remove saved logins/passwords from within Firefox Preview

### ISSUE THREAD

**Issue by ballisonmoz** [mozilla-mobile/fenix#7898] opened 2020-01-23 19:39 UTC
### Why/User Benefit/User Problem
Users currently have to go through Firefox Desktop and to about:logins to remove outdated/incorrect logins and passwords from their account and browser. Adding this feature in Fenix allows users to manage everything without leaving the app and cuts out an unnecessary and tedious step.

**Comment by kbrosnan** [comment] 2020-01-23 20:39
duplicate of #5774

**Closed by kbrosnan** 2020-01-23 20:39 UTC
Labels: needs:triage, 🌟 feature request
