### ISSUE TITLE
[Bug] Autocomplete saved credentials on HTTP basic auth prompt not working

### ISSUE THREAD

**Issue by Lillebo** [mozilla-mobile/fenix#17509] opened 2021-01-18 12:24 UTC
## Steps to reproduce
Go to any website using basic HTTP auth, i.e. https://jigsaw.w3.org/HTTP/Basic/ (user: "guest", pass: "guest")

Experience issues of both getting a prompt for saving the credentials in the first place and autocompleting saved credentials in the auth dialog upon later visits.

### Device information

* Android device: Pixel 5
* Fenix version: Firefox Daylight 84.1.4

**Comment by cadeyrn** [comment] 2021-01-18 12:43
Duplicate of #8642.

**Closed** 2021-01-18 12:54 UTC
Labels: needs:triage, 🐞 bug
