### ISSUE TITLE
[Bug] URL bar blocks content at the bottom of a page

### ISSUE THREAD

**Issue by mnatator** [mozilla-mobile/fenix#14409] opened 2020-08-29 06:23 UTC
## Steps to reproduce
Open a page that has a height of about 100% of a screen

### Expected behavior
It should be possible to view all content, even the bottom content of the page.
### Actual behavior
the URL bar covers the bottom part of the page, since it is not possible to scroll, the url bar does not disappear.
### Device information

* Android device: Galaxy S 8
* Fenix version: 79.0.5 (Build #2015758619)

**Comment by DavidJCobb** [comment] 2020-08-29 07:02
I'm new here but this looks like a duplicate of #13797 and the other bugs mentioned in its comments?

**Comment by s-ankur** [comment] 2020-08-29 08:25
@mnatator can you add the url as well so it can be tested after this issue is fixed?

**Comment by MicroBeast** [comment] 2020-09-02 12:09
Name: Firefox Beta
Version: 80.0b7
Build ID: 20200811133449
From: Google Play Store

Effected with bug: ``about:config``

How to reproduce:

Use search to filter. On my case, I filter ``autoplay``. It return results about 2 pages. Obviously bug can't be seen if the filter result fit one screen. Scroll down to most bottom. Here; the last config can't be seen.

**Comment by ekager** [comment] 2020-12-18 05:26
closing as duplicate of #13797

**Closed by ekager** 2020-12-18 05:26 UTC
Labels: needs:triage, 🐞 bug
