### ISSUE TITLE
[Bug]  lots of tabs opened results in tab content not (re)loaded

### ISSUE THREAD

**Issue by liar666** [mozilla-mobile/fenix#16149] opened 2020-10-23 14:53 UTC
###  Steps to reproduce

I have the (bad) habit of opening a lot of tabs in FF for android (I read headlines of news in an RSS reader and click the 'share' -with firefox- button every time an article seems of interest, to read it later. As a consequence opened tabs might pile up drastically as I do not necessarily find time to read articles in depth beofre a long time).

During the course of the last week, I accumulated ~150 tabs, in several rounds where I read news in RSS reader & open tabs in FF, then close both apps (to save energy), then re-open one or the other app from time to time.

Today, I wanted to read the whole articles. Unfortunately, When I go to most of the tabs, I get a blank page as content. When I ask for reloading of the page, I get an all black page as content (my theme is the dark one).

The only solutions I found are either to copy the URL, close the tab, open another tab, paste the url, then I get the content. Many times, just copying the URL, and pasting it again, gets the page actually reloaded & content displayed.

### Expected behavior

Whatever the number of tabs opened, when I open one tab, I should see the content of the page as the content of the tab (and particularly if I force a reload of the page!)

### Actual behavior

Most tabs remain blank/black when visiting/reloading them

### Device information

* Android device: Doogee N10
* Fenix version: 81.4.1

**Comment by s-ankur** [comment] 2020-10-23 15:14
> Unfortunately, When I go to most of the tabs, I get a blank page as content. When I ask for reloading of the page, I get an all black page as content (my theme is the dark one).

 Possibly dupe of #15046

**Comment by liuche** [comment] 2020-10-29 03:06
@pocmo is this helpful for #15046, or does it sound like a different issue?

**Comment by ekager** [comment] 2020-12-18 06:29
@liar666 have you seen any improvements on this issue?

**Closed** 2021-06-23 07:37 UTC
Labels: Feature:Tabs, wontfix, 🐞 bug
