### ISSUE TITLE
[Bug] Grid tab view no longer displays as a grid

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#20257] opened 2021-07-05 19:31 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Make sure that Grid view is selected
2. Open multiple new tabs
3. View tabs in tab drawer

### Expected behavior

Tabs are viewed as a grid

### Actual behavior

Tabs viewed as wide tabs (see image attached to https://support.mozilla.org/en-US/questions/1342405)

### Device information

* Device vendor / model and Android version: Pixel 3 64GB, Android 11
* Firefox for Android version: 89.1.1 (Build #2015812947)

Please see SUMO questions https://support.mozilla.org/en-US/questions/1342405

**Comment by Nickoriginal** [comment] 2021-07-06 05:36
Hello!
**Firefox 89.1.1**
_Not reproducible_ on:
**Samsung Galaxy A20s** (Android 10)
**Samsung Galaxy J2 Prime** (Android 6.0.1)
<img src = https://user-images.githubusercontent.com/85299944/124547713-393f1300-de35-11eb-96ea-6f9c5f385210.jpg width = 45%>

**Comment by SoftVision-LorandJanos** [comment] 2021-07-06 06:22
Hi @SeburoSUMO ! Thanks for the report! I was not able to reproduce your issue. I’ve used a device close to yours (Google Pixel 4 with Android 11) with the same FF build (89.1.1 (Build #2015812947)), and the grid is activated as expected. Could you check on the latest Nightly or if you can, clear your data on the same build and check if it’s still reproducible? Thank you!

**Comment by OlliKn** [comment] 2021-07-06 07:13
Got the same issue on All nightlys since the New gridview was launched.
Honor 6x, lineageos 16

**Comment by OlliKn** [comment] 2021-07-06 07:21
Screenshot:
![Firefox_Nightly_1](https://user-images.githubusercontent.com/61148677/124558954-6e4e6400-de3b-11eb-8233-ddfba79df76d.png)

**Comment by codrut-topliceanu** [comment] 2021-07-07 11:08
@OlliKn @SeburoSUMO 
I'm also unable to reproduce this issue, could you record a video of the erroneous behavior please? 🙏 
It would help us a great deal in getting the issue fixed.

**Comment by OlliKn** [comment] 2021-07-07 11:33
> @OlliKn @SeburoSUMO
> I'm also unable to reproduce this issue, could you record a video of the erroneous behavior please? 🙏
> It would help us a great deal in getting the issue fixed.


https://user-images.githubusercontent.com/61148677/124751622-2442ac80-df27-11eb-8ae3-cbacd4caa247.mp4

**Comment by codrut-topliceanu** [comment] 2021-07-07 14:27
I have managed to reproduce this behavior using a low resolution emulator

<img src="https://user-images.githubusercontent.com/60002907/124770713-3b8f9300-df43-11eb-86fa-e208d6808beb.png" width=250 />

![image](https://user-images.githubusercontent.com/60002907/124771059-83161f00-df43-11eb-96e6-4fab4c4a2508.png)

We have a lower limit for set for a grid column item `MIN_COLUMN_WIDTH_DP` (minimum of 1 of course). This can be changed to keep the number of columns to 2:

<img src="https://user-images.githubusercontent.com/60002907/124776511-2c5f1400-df48-11eb-9857-cf4794d738de.png" width = 250 />

I can't say if that looks good or not, but it's a small fix. 
I'll upload a PR for this and tag this issue with needs-UX-feedback as I'm not entirely sure if this look is okay on lower DPI devices.

**Comment by OlliKn** [comment] 2021-07-07 18:00
The uploaded Video has a low Resolution due bandwith limitations from my side. The screen Resolution of the Device is 1080 x 1920 pixels. My fault. I should have mentioned earlier.

**Comment by SeburoSUMO** [comment] 2021-07-07 19:54
@SoftVision-LorandJanos - I am sorry I have not been able to respond.  The question came into Mozilla Support from a user.  I cannot replicate the issue myself.

@OlliKn - Thank you so much for picking this up, getting involved and providing some valuable input.

@codrut-topliceanu - I think that 2 columns look great and it is what most users would expect.  Although the text may not be readable on lower resolution devices, it will still be possible to distinguish between tabs in the majority of cases.

**Comment by codrut-topliceanu** [comment] 2021-07-08 07:21
> The uploaded Video has a low Resolution due bandwith limitations from my side. The screen Resolution of the Device is 1080 x 1920 pixels. My fault. I should have mentioned earlier.

This is very strange. Perhaps android's measurement of the DPI is at odds with Honor 6x somehow. 🤷‍♂️ 
The PR should still work though.

**Comment by OlliKn** [comment] 2021-07-11 11:07
Now it works! Thank you!
91.0a1 (Build #2015821131)
AC: 91.0.20210708143124, 6533d0dbc7
GV: 91.0a1-20210708091856
AS: 79.0.0

**Comment by abodea** [comment] 2021-07-13 10:18
Verified as fixed with latest Nightly from 7/13 using Google Pixel 4 XL (11).

**Closed by abodea** 2021-07-13 10:18 UTC
Labels: Feature:Tabs, eng:qa:needed, qa-triaged, 🐞 bug
