### ISSUE TITLE
FNX-5472 ⁃ [Bug] name in about:support isn't Fenix

### ISSUE THREAD

**Issue by bdekoz** [mozilla-mobile/fenix#2127] opened 2019-04-29 17:50 UTC
## Steps to reproduce
open up 'about:support' url on Fenix

### Expected behavior
Name field is "Fenix". 

### Actual behavior
Name field is "Fennec"

### Device information
* Android device: amazon-fire stick 4k, pixel 2
* Fenix version: 20190422094240

**Comment by cadeyrn** [comment] 2019-04-29 19:05
Duplicate of #1353.

**Closed** 2020-08-11 14:01 UTC
Labels: 🐞 bug
