### ISSUE TITLE
[Bug] Search Suggestion Freezing

### ISSUE THREAD

**Issue by AnotherAnand** [mozilla-mobile/fenix#17460] opened 2021-01-14 12:40 UTC
Whenever I try to search something the search suggestions gets freezed (image attached) and to make the browser usable again I need to go to recents screen and come back again to the browser. I noticed this it happens only when I use Pixel Launcher 11 and not other launcher. My android version is android 11. 
![Screenshot_20210114-164619_Firefox](https://user-images.githubusercontent.com/65772232/104592019-92eb2f80-5693-11eb-9b2a-cb0b446e5038.png)
(This is my first issue so forgive me if i did something wrong. Also my english is not that good.)

**Comment by amedyne** [comment] 2021-01-19 19:35
Closing this issue as a duplicate of https://github.com/mozilla-mobile/fenix/issues/17469. Will keep #17469 for monitoring.

**Closed by amedyne** 2021-01-19 19:35 UTC
Labels: Feature:Search
