### ISSUE TITLE
`MetricController.track` & `Event.wrapper` may use non-trivial power: called frequently

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21292] opened 2021-09-14 22:39 UTC
`MetricController.track` calls [the `Event.wrapper` method, which is a long chain of comparisons,](https://searchfox.org/mozilla-mobile/rev/14b6f198ebbe966e5d31eb9ab5fbf6b15fc1ce75/fenix/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#101) twice to submit telemetry. To test the impact of these methods, I did a simple workflow:
- click wiki homescreen
- click url bar, nav amazon.com
- click tabs tray, new tab
- search "foobar" and click default search result

I added custom markers and took profiles:
- Event.wrapper: https://share.firefox.dev/3lipdoU
- MetricController.track: https://share.firefox.dev/2Xha5QD (the profiler marker is misnamed GleanMetricsService)

In these profiles of this simple workflow, we see:
- `MetricController.track` is called 19 times for a total duration of 57.3ms
- `Event.wrapper` is called 36 times for a total of 24.3ms (I believe this is a subset of MetricController)
- (caveat: these duration may be inflated because these calls are fast and clock granularity might not be good enough)
- (note: I used `window.filteredMarkers.map((m) => m.end - m.start).reduce((acc, i) => acc + i)` to measure this)

These durations will be unnoticeable to the user, however, they will use battery. wrt `Event.wrapper`, this doesn't need to be a long chain of comparisons – perhaps by calling the Glean API directly and removing `MetricController` – so we can stop the users' device from doing work it doesn't need to. We should investigate `MetricController` for similar wins.

wrt prioritization, there may be larger gains we can do to improve battery life (e.g. https://github.com/mozilla-mobile/fenix/issues/15921) but those are likely harder to implement so it could be worth addressing this issue.

Note: https://github.com/mozilla-mobile/fenix/issues/19967 may also address this issue.

**Comment by mcarare** [comment] 2022-03-03 16:35
This issue will serve as a meta. I will link here the issues handling the removal of the wrapper in separate components. This will make QA work easier and ensure we do not have regressions by tackling the whole work in smaller pieces.

**Comment by mcarare** [comment] 2022-03-04 12:46
- [ ] Remove wrapper for Tabs Tray telemetry: https://github.com/mozilla-mobile/fenix/issues/24098

**Comment by MatthewTighe** [comment] 2022-04-05 00:04
👋 This work looks like great stuff! 

I'm working on some new telemetry and wanted to make sure I followed suit with the changes being done here. Is there a way to verify Glean metrics in test without using Robolectric and the `GleanTestRule`? My concern there is just around test performance - I try to avoid Robolectric if possible as it tends to increase test startup and run times pretty dramatically.

I didn't see anything here at a glance, so I filed [an enhancement request](https://bugzilla.mozilla.org/show_bug.cgi?id=1763029) for Glean. Please let me know if there's a method I missed somewhere.

@mcarare @Alexandru2909

**Comment by mcomella** [comment] 2022-04-05 16:49
> Is there a way to verify Glean metrics in test without using Robolectric and the GleanTestRule?

I commented in your enhancement request about some prior discussion. I used to mock the telemetry APIs in tests but [the Glean folks discouraged it](https://bugzilla.mozilla.org/show_bug.cgi?id=1626874#c6) and I agree with their reasoning though it is a shame about the robolectric test times.

**Comment by mcarare** [comment] 2022-05-03 11:33
This can be closed as all `MetricController.track` and `Event.wrapper `usages have been removed from the app.

**Closed by mcarare** 2022-05-03 11:33 UTC
Labels: Feature:Telemetry, performance, perf:P3, meta
