### ISSUE TITLE
[Bug] Fix intermittent UI test failure - toggleShowVisitedSitesAndBookmarks

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#8713] opened 2020-02-25 00:26 UTC
```
 androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with text: is "Library" and has parent matching: with id: 2131296999)
View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION
```

[firebase log](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6817250470168511187/executions/bs.ed0b8ccd48bbdf96/testcases/1/test-cases)

**Comment by AaronMT** [comment] 2020-02-25 15:18
The ideal fix is waiting for the `org.mozilla.fenix.library.LibraryFragment` fragment to load with an idling resource.

**Comment by AaronMT** [comment] 2020-05-14 17:20
I think this test refers to `toggleShowVisitedSitesAndBookmarks` which is still disabled

**Comment by AaronMT** [comment] 2020-06-02 14:22
Dupe of https://github.com/mozilla-mobile/fenix/issues/8714

**Closed by AaronMT** 2020-06-02 14:22 UTC
Labels: intermittent-test, 🐞 bug
