### ISSUE TITLE
FNX-5098 ⁃ [Bug] The location doorhanger on hm.com uses the entire screen

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1557] opened 2019-04-11 14:04 UTC
## Steps to reproduce
1. Go to hm.com
1. Wait for the location doorhanger to appear.
1. Go to mapquest.com and compare.
    1. Expected behavior
A small doorhanger, like on mapquest.com.
    1. Actual behavior
![Screenshot](https://user-images.githubusercontent.com/4037709/55961475-9f00bc80-5c77-11e9-8654-0af3921a6a55.jpg)UNITO-UNDERSCORE!20190411-162250!UNITO-UNDERSCORE!Fenix!

### Device information
* Android device: Galaxy S8 (Android 9), Pixel (Android 9)
Not reproducing on HTC 10 (Android 8.0), Huawei P20 lite (Android 8), HTC Desire 820 (Android 6.0.1)
* Fenix version: 4/11

**Comment by kbrosnan** [comment] 2019-04-16 22:03
Confirmed on the April 16th build

**Comment by vesta0** [comment] 2019-04-24 03:22
Looks like it may have been fixed.

**Comment by kbrosnan** [comment] 2019-04-24 03:52
I saw this on a local build from today on a different site.

**Comment by sv-ohorvath** [comment] 2019-04-24 12:57
Still reproducing on hm.com as well. Build 4/24

**Comment by vesta0** [comment] 2019-04-24 16:25
FYI for investigation: I wasn't able to reproduce when I had my device font size set to Large. Once I changed the device font size back to default, I started seeing this issue.

**Comment by bsurd** [comment] 2019-05-08 11:27
Verified as fixed on the latest master with a Nexus 5 (A6.0.1) & Nexus 6P (A8.1). The doorhanger no longer uses the entire screen and is now displayed like all other requests.

**Closed** 2020-08-11 11:58 UTC
Labels: Feature:SitePermissions, P1, eng:qa:verified, 🐞 bug
