### ISSUE TITLE
Bug: Home bar blank

### ISSUE THREAD

**Issue by PopeRigby** [mozilla-mobile/fenix#4574] opened 2019-08-06 23:05 UTC
I have no idea what is triggering this, but every once and a while, I'll open Fenix and the home bar will be completely blank.
![](https://imgur.com/a/WM4ER5y)

**Comment by ekager** [comment] 2019-08-06 23:07
Closing as dupe of #4529

**Closed by ekager** 2019-08-06 23:07 UTC
