### ISSUE TITLE
[BUG] Fenix is too slow when started fresh

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#11890] opened 2020-06-24 13:54 UTC
Issue: When fresh session of fenix is started, it doesn't load pages as fast as normal. But if waited for 30 second after fresh session, its speed is back to normal.

How to reproduce : just start a fresh session of fenix and load any website

Fenix : Nightly 200624 06:01 (Build #2015748083)
AC: 47.0.20200623130149, 88694edfb
GV: 79.0a1-20200622093309
AS: 61.0.2

Device : Xiaomi Redmi Note 4 Android 7.0

Video : https://mega.nz/file/3UAxCKLC#kxl0Wy-FG6yMQtD2G5VoPz7ZKt8GzfXk69XFd--5ssU

**Comment by Furax-31** [comment] 2020-07-23 13:46
I think the addons are the cause, I have the same problem :(

**Comment by ekager** [comment] 2020-12-17 20:51
@RealGJ do you still have this problem?

**Comment by RealGJ** [comment] 2020-12-18 17:59
@ekager yes! Problem still persists

**Comment by ekager** [comment] 2020-12-18 18:00
And do you use any addons?

**Comment by RealGJ** [comment] 2020-12-18 18:03
@ekager yes sir! I've following add ons :

Ublock origin, Dark Reader, Decentraleyes Google search fixer, view page source (Mobile), Android pdf.js

**Comment by Dunexus** [comment] 2020-12-19 09:38
Probably related to https://github.com/mozilla-mobile/fenix/issues/17138

**Comment by mcomella** [comment] 2021-01-07 01:47
We've seen this issue before https://github.com/mozilla-mobile/fenix/issues/16473 and we believe the culprit is that some add-ons use a non-trivial amount of system resources.

@RealGJ Are you able to reproduce this problem with all add-ons disabled?

**Comment by RealGJ** [comment] 2021-01-08 12:48
Hello @mcomella !! I've just tried to reproduce issue after removing all add-ons!! And there I'm unable to reproduce it while no Add-ons were installed!!

**Comment by mcomella** [comment] 2021-01-13 22:45
In that case, I think this is the same as #16473 so I will close this issue as a duplicate. Thanks for reporting!

**Closed by mcomella** 2021-01-13 22:45 UTC
Labels: eng:performance, 🐞 bug
