### ISSUE TITLE
FNX3-16759 ⁃ Create a Fenix Leanplum Attribute that tells us whether a user has any Sync engines enabled (Next Phase)

### ISSUE THREAD

**Issue by ItsDevyani** [mozilla-mobile/fenix#3060] opened 2019-05-31 20:45 UTC
## User Story - Marketing as the user
* As a Marketer, I would like to know whether or not a user is signed into Sync, so that I can send them an in app message or push notif prompting them to sign into Sync and drive greater retention (MAU) with Fenix
* e.g. targeting users that have an FxA account, but don't have all their Sync engines disabled.

## Dependencies
* Data pass through from the application services team? (Identify other dependencies with help from Vesta and Stefan.)

### Acceptance Criteria
* I (The marketer) can segment the users by whether or not they are signed into Sync in Leanplum 
* I (The marketer) can target the users with relevant messages delivered via Leanplum based on their sign-in status
* I (The marketer) can measure the number of users who signed in to Sync after seeing my campaign

**Comment by liuche** [comment] 2019-08-02 17:38
Asking Loren what we want this data to look like (per engine? or something).

**Comment by sblatz** [comment] 2019-08-06 16:17
Loren confirmed that marketing wants to measure if a user has *all* of their sync preferences disabled or has ANY of them disabled.

**Comment by liuche** [comment] 2019-08-17 01:12
@bifleming since this landed 9 days ago, I would assume that it's going out with the 1.3 release.

**Comment by AndiAJ** [comment] 2019-08-19 07:17
Hi, **verified as fixed** on Fenix **1.3.0-rc.3** from 19/8 with a couple of observations and questions.

1. Sing in to Sync ✅
Ping e5848fde-0aec-49d1-b476-9ce787d82aba


2. Sync preferences

Bookmarks ✅
Ping 648ec130-c672-4e20-adc2-822c7d5856d0
Ping f9b50e69-d421-4198-8bea-23dd12ae60f9
Ping 603e4bf1-6d25-4529-879f-67bde3d32473

History ✅
Ping a45301b3-9f9c-46e7-8066-9101dced2647
Ping 33f12193-ef2a-4aa8-af96-8cb25151743c
Ping 0657c5ce-6b45-461b-b7d7-bcf565f0e98b

3. Sign out ✅
Ping eb3eeb65-3f30-4477-8561-ffc6d70f454d

@sblatz I would have a couple of questions just to be sure everything works fine
After successfully signing in Ping e5848fde-0aec-49d1-b476-9ce787d82aba I've noticed that the **rename_button from the collections sections gets triggered**.

Another aspect worth mentioning is that after signing in the sync starts and it generates:
2x bookmarks_sync 
2x history_sync

Afterwards only one for each sync item gets generated. 

#### Notes
[Logcat](https://github.com/mozilla-mobile/fenix/files/3514628/Sync.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-190800)

**Comment by sblatz** [comment] 2019-08-19 15:26
Hey @AndiAJ 
> rename_button from the collections sections gets triggered.

I'm submitting a PR to fix this. Thanks for catching this!

As far as the sync events getting triggered twice, that's just an artifact of how our syncing system works, and is expected behavior :)

**Closed** 2020-08-12 17:21 UTC
Labels: E3, Feature:Telemetry, eng:qa:verified, must
