### ISSUE TITLE
[Bug] Tab closed pop up only goes away when you click undo

### ISSUE THREAD

**Issue by alexjohnchapman** [mozilla-mobile/fenix#8888] opened 2020-03-01 07:51 UTC
## Steps to reproduce
Close a tab.

### Expected behavior
The "tab closed" pop up should leave after a few seconds. Clicking "undo" should reopen the closed tab.

### Actual behavior
The pop up doesn't leave until you press "undo". Pressing "undo" does not reopen the closed tab

### Device information

* Android device: Oneplus 3, Android 9
* Fenix version: 3.2.0 (Build #20250236)

**Comment by cadeyrn** [comment] 2020-03-01 08:15
Duplicate of #7799, fixes with the next update.

**Closed** 2020-03-01 15:40 UTC
Labels: needs:triage, 🐞 bug
