### ISSUE TITLE
Android Action Center Player UI Problem

### ISSUE THREAD

**Issue by W0lfDev** [mozilla-mobile/fenix#26536] opened 2022-08-18 21:55 UTC
The ui is all glitched. The buttons aren't visible and no background image is displayed.

I'm running miui 13 with android 12

Hope this gets fixed soon cause I really like firefox.

![Screenshot_2022-08-19-00-55-04-775_com.miui.home.jpg](https://user-images.githubusercontent.com/96019707/185502127-282cb02c-cdcf-47b1-beec-6956b58e44dd.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21333)

**Comment by AdinaPetridean** [comment] 2022-08-22 13:21
@W0lfDev thank you for your report! I was able to reproduce this issue on: Firefox 103.2.0 and on the latest Nightly from 08/22  with Xiaomi Pad5 (Android 11) -MIUI  13.0.6.
Please note this issue has been already reported. I will close this as a duplicate of 
[#18841] and [#17670]

<img src="https://user-images.githubusercontent.com/108326843/185930844-a0a8f3b5-a331-462f-b3df-d6b2adfaf1df.JPEG" width="50%" />

**Closed by AdinaPetridean** 2022-08-22 13:21 UTC
Labels: 🐞 bug, Feature:Media, S3, needs:triage, qa-triaged
