### ISSUE TITLE
[Bug] Fenix crashes when loading page + ANR

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/fenix#5436] opened 2019-09-19 20:10 UTC
## Steps to reproduce

1. Open any web-site in Fenix.
2. Browse.

### Expected behavior

No crash.

### Actual behavior

Almost every second time Fenix is crashing while loading page. Progress bar is filled around 25-35% at that time. Sometimes it happens while scrolling.

Mozilla Crash dialog and ANR dialog are shown.

### Device information

* Android device: Xiaomi Mi 4X (Android 7.1.2 / MIUI Global 10.3).
* Fenix version: still reproducible on build #13031728.

P.S. I'm investigating crash reason and probably will be able to add some logs. But crash is also submitted to Mozilla via crash report dialog.

**Comment by dector** [comment] 2019-09-20 10:45
<details>
<summary>ANR log</summary>

<pre>
E/ActivityManager: ANR in org.mozilla.fenix (org.mozilla.fenix/.HomeActivity)
    PID: 17278
    Reason: Input dispatching timed out (org.mozilla.fenix/org.mozilla.fenix.HomeActivity, Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 10.  Wait queue head age: 8649.5ms.)
    Load: 6.28 / 5.18 / 5.39
    CPU usage from 0ms to 6840ms later (2019-09-20 14:42:43.053 to 2019-09-20 14:42:49.893):
      104% 17278/org.mozilla.fenix: 89% user + 14% kernel / faults: 27565 minor 95 major
      24% 1540/system_server: 13% user + 11% kernel / faults: 4732 minor 945 major
      15% 174/kswapd0: 0% user + 15% kernel
      12% 17329/org.mozilla.fenix:tab: 8.7% user + 3.3% kernel / faults: 12491 minor 31 major
      5.2% 1729/com.android.systemui: 3.6% user + 1.6% kernel / faults: 3612 minor 392 major
      4.9% 1991/com.android.phone: 2.9% user + 2% kernel / faults: 2486 minor 678 major
      4.8% 16733/com.xiaomi.glgm: 1.3% user + 3.5% kernel / faults: 2474 minor 40 major
      3.9% 539/surfaceflinger: 2% user + 1.9% kernel / faults: 543 minor 1 major
      2% 326/mmc-cmdqd/0: 0% user + 2% kernel
      2% 372/core_ctl/0: 0% user + 2% kernel
      2% 16526/com.miui.powerkeeper: 1.3% user + 0.7% kernel / faults: 2161 minor 35 major
      1.7% 12724/kworker/u17:8: 0% user + 1.7% kernel
      0% 447/debuggerd64: 0% user + 0% kernel / faults: 195 minor 45 major
      1.3% 32192/kworker/u17:0: 0% user + 1.3% kernel
      1.1% 1690/adbd: 0.2% user + 0.8% kernel / faults: 167 minor 1 major
      0% 2540/com.fingerprints.serviceext: 0% user + 0% kernel / faults: 1196 minor 245 major
      1% 12723/kworker/u17:6: 0% user + 1% kernel
      0.8% 434/logd: 0.2% user + 0.5% kernel / faults: 396 minor 2 major
      0% 446/debuggerd: 0% user + 0% kernel / faults: 211 minor 40 major
      0.7% 405/kworker/6:1H: 0% user + 0.7% kernel
      0.7% 1290/kworker/u17:2: 0% user + 0.7% kernel
      0.5% 289/irq/72-ft5x06_7: 0% user + 0.5% kernel
      0.5% 12604/kworker/u16:8: 0% user + 0.5% kernel
      0.4% 7/rcu_preempt: 0% user + 0.4% kernel
      0.4% 58/ksoftirqd/6: 0% user + 0.4% kernel
      0.4% 331/kmemsw_chkd: 0% user + 0.4% kernel
      0.4% 12719/kworker/u17:1: 0% user + 0.4% kernel
      0.4% 14927/kworker/u16:6: 0% user + 0.4% kernel
      0.2% 398/ueventd: 0% user + 0.2% kernel / faults: 37 minor
      0.2% 717/netd: 0.1% user + 0.1% kernel / faults: 70 minor
      0.2% 833/msm_irqbalance: 0.1% user + 0.1% kernel / faults: 56 minor 1 major
      0.2% 1308/kworker/u17:7: 0% user + 0.2% kernel
      0% 2338/mcd: 0% user + 0% kernel / faults: 224 minor 13 major
      0.2% 9531/mdss_fb0: 0% user + 0.2% kernel
      0.2% 10685/logcat: 0.1% user + 0.1% kernel / faults: 25 minor 1 major
      0.2% 15460/com.teslacoilsw.launcher: 0.1% user + 0.1% kernel / faults: 184 minor
      0.2% 32377/kworker/u16:3: 0% user + 0.2% kernel
      0.1% 26/ksoftirqd/2: 0% user + 0.1% kernel
      0.1% 45/rcuop/4: 0% user + 0.1% kernel
      0.1% 61/rcuop/6: 0% user + 0.1% kernel
      0.1% 321/cfinteractive: 0% user + 0.1% kernel
      0.1% 524/healthd: 0% user + 0.1% kernel / faults: 80 minor
      0.1% 588/sensors.qcom: 0% user + 0.1% kernel / faults: 82 minor 1 major
      0.1% 681/jbd2/dm-1-8: 0% user + 0.1% kernel
      0.1% 692/thermal-engine: 0.1% user + 0% kernel / faults: 40 minor
      0.1% 1526/com.google.android.inputmethod.latin: 0% user + 0.1% kernel / faults: 510 minor
      0.1% 2362/irq/165-408000.: 0% user + 0.1% kernel
      0.1% 2680/com.qualcomm.qcrilmsgtunnel: 0% user + 0.1% kernel / faults: 647 minor 4 major
      0.1% 7298/kworker/3:1H: 0% user + 0.1% kernel
      0.1% 11759/VosRXThread: 0% user + 0.1% kernel
      0.1% 12265/kworker/4:0: 0% user + 0.1% kernel
      0.1% 15080/kworker/6:2: 0% user + 0.1% kernel
      0.1% 16913/org.wikipedia: 0% user + 0.1% kernel / faults: 236 minor 5 major
    2.1% TOTAL: 0% user + 0% kernel + 0% softirq
    CPU usage from 5330ms to 5880ms later (2019-09-20 14:42:48.383 to 2019-09-20 14:42:48.934) with 99% awake:
      104% 17278/org.mozilla.fenix: 104% user + 0% kernel / faults: 414 minor
        100% 17394/DefaultDispatch: 100% user + 0% kernel
        1.7% 17278/g.mozilla.fenix: 1.7% user + 0% kernel
        1
</pre>

</details>

**Comment by ekager** [comment] 2019-11-20 21:14
@dector are you still seeing this on latest nightly?

**Comment by dector** [comment] 2019-11-26 07:16
Sorry for the delay. Currently I'm using builds from Google Play. But I'll check nightly build this week.

**Comment by dector** [comment] 2019-12-18 09:45
Still reproducible on the latest build from Google Play (update from 13th of December) but happens not that often.

**Comment by boek** [comment] 2019-12-28 03:43
@dector this is strange, I'm still not able to reproduce. Do you have webrender enabled?

**Comment by dector** [comment] 2020-01-02 23:08
@boek Unfortunately I can't check if it's enabled (as `about:support` says that it's an opt-in feature) because `about:config` isn't loading: I have "Cannot complete request" when trying to open it.

Is there other way to enable it?

**Comment by dector** [comment] 2020-01-15 15:43
@boek Are crashes uploaded successfully?

**Comment by dector** [comment] 2020-01-19 11:15
It's a bit better after latest update from Play. Experiencing only freezes but no more crashes for some time.

**Comment by abodea** [comment] 2020-03-05 14:21
Hello @dector.
I tried to reproduce this on the latest Nightly build from 3/5 following the steps from the description.
I used: Samsung Galaxy S7 (A 7) and Samsung Galaxy S10+ (A 9).
Note that I didn't encounter any crashes or freezes.

Are you still reproducing this?
Please provide new STR if it will be the case and the website where Firefox Preview crashes.

**Comment by ekager** [comment] 2020-03-11 17:49
@dector please let us know if this is still happening or if we can close this bug

**Comment by dector** [comment] 2020-03-11 22:56
Just upgraded to the latest version. I'm experiencing freezes (sometimes up to 2-3) when pages are loading or when I'm selecting UI elements (however not when I'm scrolling :thinking:).

I guess we can close this issue for now. I'll try to profile browser when I'll have time to do it. Thanks, @boek, @abodea and @ekager !

**Comment by abodea** [comment] 2020-03-12 07:53
Thank you @dector!
Based on the comments above, I will close this issue and I will remove the **needs:STR** label.

**Closed by abodea** 2020-03-12 07:53 UTC
Labels: P3, needs:STR, 🐞 bug
