### ISSUE TITLE
[Bug][RTL] Potentially don't set automatic direction based on the text directionality, for text across the UI

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/fenix#7861] opened 2020-01-22 14:21 UTC
[Original bug filed under GeckoView by @itiel](https://bugzilla.mozilla.org/show_bug.cgi?id=1608218). Screenshots attached to original bug to demonstrate.

> Currently, (almost) everywhere in the UI the alignment of varios text elements is decided based of the text directionality.
> This usually makes sense, but this an issue where English text actually should appear.
> See the attached screenshots with examples for this.
> 
> While it's possible to address each text element separately, I don't see any reason (well, from RTL POV anyway) not to make the text align to the left for LTR, and to the right for RTL.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15324)

**Comment by Delphine** [comment] 2022-04-21 22:18
Seems like this is still an issue, and that if/when fixed, could potentially fix other right-to-left issues in Fenix (as per [this](https://github.com/mozilla-mobile/fenix/issues/21306#issuecomment-1101778924) comment).
@amedyne Not sure you are the right person to flag for this, but this currently affects all 4 of our right-to-left locales (Hebrew, Arabic, Urdu and Persian).

**Comment by ItielMaN** [comment] 2022-11-19 15:56
Still an issue.

**Comment by Delphine** [comment] 2022-12-14 20:51
Hi @cpeterso, there seems to be growing interest in launching more broadly right-to-left locales on Firefox for Android, and this is still a major issue that has been going on for almost 3 years.
Currently there are still some other RTL issues - but fixing this one may also just fix the rest.
Could you help get this one prioritized? thanks

**Comment by cpeterso** [comment] 2022-12-14 23:48
> Currently there are still some other RTL issues - but fixing this one may also just fix the rest.
> Could you help get this one prioritized? thanks

I talked to Android PM and we moved this bug near the top of our Android backlog. I don't have an ETA, though.

**Comment by delia-pop** [comment] 2023-01-16 15:38
Verified as fixed on the latest Nightly 110.0a1 from 01/16 with Google Pixel 6 (Android 13), Xiaomi 12 Pro (Android 13) and Lenovo Yoga Tab 11 (Android 11). 
The URLs and other UI elements are correctly aligned to the right when RTL language is used.
Please note that the following issues were observed while testing: https://github.com/mozilla-mobile/fenix/issues/28550 , https://github.com/mozilla-mobile/fenix/issues/28498, https://github.com/mozilla-mobile/fenix/issues/26728, https://github.com/mozilla-mobile/fenix/issues/28342.

**Comment by mavduevskiy** [comment] 2023-01-16 19:44
@delia-pop 
Does it mean those issues were solved and can be closed or do we still need to work on those?

**Comment by mavduevskiy** [comment] 2023-01-17 19:58
Reverted [the fix](https://github.com/mozilla-mobile/fenix/pull/28568) due to a [regression](https://github.com/mozilla-mobile/fenix/issues/28498).

**Comment by jonalmeida** [comment] 2023-01-17 21:13
@mavduevskiy and I spoke offline, and when we land this fix again. We can test to make sure that it doesn't cause the same regression again.

**Comment by gabrielluong** [comment] 2023-02-08 06:25
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1815637

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by gabrielluong** 2023-02-08 06:25 UTC
Labels: 🐞 bug, 🌐 L10N:RTL
