### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mini536** [mozilla-mobile/fenix#15336] opened 2020-09-23 04:43 UTC
### What is the user problem or growth opportunity you want to see solved?

I hope that the browser has the function of deciding whether to load images or not based on conditions, like Firefox 68.
### How do you know that this problem exists today? Why is this important?

Because of the lack of this function, the loading speed of web pages in places with slow network speed is very slow.
### Who will benefit from it?

All people in places with poor internet conditions.

**Comment by Dunexus** [comment] 2020-09-23 07:30
Duplicate of https://github.com/mozilla-mobile/fenix/issues/12711

**Comment by kbrosnan** [comment] 2020-09-24 04:21
Closing as a duplicate

**Closed by kbrosnan** 2020-09-24 04:21 UTC
Labels: needs:triage
