### ISSUE TITLE
[Bug] Tracking Protection pop-up is not fully displayed on landscape(only after dragging it up)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#4109] opened 2019-07-17 09:43 UTC
## Steps to reproduce
1. Launch Fenix.
2. Reach any website.
3. Turn the device in landscape mode.
4. Tap on the Tracking Protection button.
### Expected behavior
The Tracking Protection pop-up is fully displayed exactly like in portrait mode.
### Actual behavior
The Tracking Protection pop-up is not fully displayed on landscape(only after dragging it up)
### Device information

* Android device: **`Samsung Galaxy S10+(Android 9).`**
* Fenix version: **`Latest Nightly 7/17`**
[Video](https://drive.google.com/file/d/1xrFUF7_1IvQDlwUtE-wkOwwl7iPBAUp5/view?usp=sharing)

**Comment by ekager** [comment] 2019-07-17 16:28
Dupe of #3521

**Closed by ekager** 2019-07-17 16:28 UTC
Labels: S2, b:landscape, 🐞 bug
