### ISSUE TITLE
FNX2-15601 ⁃ [Bug]Crash Code Report(Always Crash)

### ISSUE THREAD

**Issue by lomomcat** [mozilla-mobile/fenix#12985] opened 2020-07-27 15:42 UTC
## Steps to reproduce
Click **Settings** and click **Search**, then select a search engine that is different from the default search engine.

### Expected behavior
Select successfully.

### Actual behavior
Crash.

### Device information
* Android device: Xiaomi Redmi Note 8 Pro
* Fenix version: Nightly 200727 06:00
* Android Version: 10 (MIUI 12, latest patch)
* SoC: MediaTek Helio G90T (MT6785V) (ARM64, ARMv8.2-A)

**Comment by lomomcat** [comment] 2020-07-27 15:44
**Crash Code**

03fd1561-7fe3-48f6-98d1-5d853ee5b8ca
java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to androidx.constraintlayout.widget.ConstraintLayout
----
```
java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to androidx.constraintlayout.widget.ConstraintLayout
	at org.mozilla.fenix.settings.search.SearchEngineListPreference.onCheckedChanged(SearchEngineListPreference.kt:3)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:180)
	at org.mozilla.fenix.settings.search.SearchEngineListPreference$makeButtonFromSearchEngine$1.onClick(SearchEngineListPreference.kt:1)
	at android.view.View.performClick(View.java:7252)
	at android.view.View.performClickInternal(View.java:7225)
	at android.view.View.access$3600(View.java:822)
	at android.view.View$PerformClick.run(View.java:27743)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7573)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
```

**Comment by karan-kamat** [comment] 2020-07-27 15:46
Also happens with my Xiaomi Redmi Note 5 Pro

- Running Android 9(MIUI 11)
- SoC:Snapdragon 636
- Fenix version: Nightly 200727 06:00

**Comment by lomomcat** [comment] 2020-07-27 15:48
@ekager @hakkikaancaliskan 
I'm so sorry to disturb you.
It still crashed.

**Comment by hakkikaancaliskan** [comment] 2020-07-27 15:57
> @ekager @hakkikaancaliskan
> I'm so sorry to disturb you that it still crashed.

This should be fixed with tomorrow's nightly. Could you try this on that?

**Comment by lomomcat** [comment] 2020-07-27 15:58
> > @ekager @hakkikaancaliskan
> > I'm so sorry to disturb you that it still crashed.
> 
> This should be fixed with tomorrow's nightly. Could you try this on that?

Okay, thanks.

**Comment by kbrosnan** [comment] 2020-07-27 16:13
Sounds like a duplicate of #12929

**Closed** 2020-08-26 18:48 UTC
Labels: Feature:Settings, b:crash, 🐞 bug
