### ISSUE TITLE
[Bug] Web page scrolling not smooth

### ISSUE THREAD

**Issue by GO-jack** [mozilla-mobile/fenix#18781] opened 2021-04-03 12:01 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
scrolling any web page.
### Expected behavior
scrolling smooth.
### Actual behavior

on the latest Nightly scrolling not smooth

[Nightly scrolling web page screen recording](https://github.com/GO-jack/issue/raw/main/Screen_Recording_20210403-173626_Firefox%20Nightly.mp4)

![firefoxn2021 jpg](https://user-images.githubusercontent.com/68154921/113477167-a8ae0b00-94b2-11eb-9042-ce17a090fd34.jpg)

on the Daylight scrolling smooth and without the issue

[Daylight scrolling web page screen recording](https://github.com/GO-jack/issue/raw/main/Screen_Recording_20210403-172519_Firefox.mp4)

![firefox2021](https://user-images.githubusercontent.com/68154921/113477251-283bda00-94b3-11eb-95ca-be4bba5d9495.jpg)

### Device information

* Device vendor / model and Android version:  Samsung A52 5G / Android 11
* Firefox for Android version: 
![firefoxn2021 jpg](https://user-images.githubusercontent.com/68154921/113477167-a8ae0b00-94b2-11eb-9042-ce17a090fd34.jpg)

**Comment by Mugurell** [comment] 2021-04-05 06:38
Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/18640
Please follow the discussion there offering more details about what you feel should be improved.

There might be situations in which the scroll might stutter and we can look into this situations one by one since they should be edgecases but I haven't seen any jank in the above video.

**Closed by Mugurell** 2021-04-05 06:38 UTC
Labels: needs:triage, 🐞 bug
