### ISSUE TITLE
FNX3-13608 ⁃ [Bug] Sometimes the dynamic address bar at the bottom cannot appear

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#10045] opened 2020-04-19 01:16 UTC
Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1631754

## Steps to reproduce
https://i.imgur.com/gyy02tb.mp4

### Device information
* Android device: ?
* Fenix version: ?

**Comment by JLRoberts** [comment] 2020-04-20 02:10
https://github.com/mozilla-mobile/android-components/pull/6710

Proposed change for this issue in android-components

**Comment by sblatz** [comment] 2020-04-27 16:53
This is caused by this GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1631754

**Comment by liuche** [comment] 2020-04-28 16:51
@boek I made a comment on the BZ ticket and put it into the GV board, but I'm not sure how it ranks against other GV bugs. Would like to get this in bc it's blocking dynamic bottom toolbar getting turned on in release.

**Comment by eliserichards** [comment] 2020-05-06 19:34
Closing in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1631754

**Comment by madb1lly** [comment] 2020-05-19 07:53
Hi all,

I have some cases where the dynamic bottom nav bar gets stuck, it doesn't fully reappear on a downward scroll. It seems to happen on the same sites as this issue, e.g. GitHub. Is that the same as this issue or shall I raise a new one? 

Thanks 🙂

**Comment by staktrace** [comment] 2020-05-19 13:50
I've also been seeing this behaviour where the bottom toolbar ends up in a partially visible state. It seems like a more recent regression.

**Comment by fluffyemily** [comment] 2020-05-19 14:52
Fix landed 14th May 2020 and will be available in GV 78.

**Comment by cadeyrn** [comment] 2020-05-30 07:30
> Fix landed 14th May 2020 and will be available in GV 78.

Fenix Nightly already uses GV 78 (my build uses GV 78 from 2020-05-28) and it happened two times in the last three days that there was no toolbar at all. Both times it happened on GitHub.

**Comment by miDeb** [comment] 2020-05-30 09:14
@cadeyrn 
https://github.com/mozilla-mobile/android-components/pull/7102 should work around this issue.

**Comment by liuche** [comment] 2020-06-08 22:07
Hi @AndiAJ, could you and the SV team see if this is still reproducible? We'd like to turn on dynamic nav bar if these issues are fixed :)

**Comment by abodea** [comment] 2020-06-09 11:05
Verified as fixed on the latest **Nightly 6/9**, for more details please check the following:
Devices: **Google Pixel 4 XL (10), Samsung Galaxy S10 + (10), Samsung Galaxy S7 ( 7), LG Nexus 4 ( 5.1.1)**.

Note that I verified this issue for the top and bottom dynamic navbar.

![20200609-130252](https://user-images.githubusercontent.com/42831109/84135442-aaee3700-aa52-11ea-8902-55ab1bf0543b.gif)

For https://github.com/mozilla-mobile/fenix/issues/10073 I tried to reproduce it, but I couldn't.

**Comment by lindongbin** [comment] 2020-06-26 13:40
not fix when enable ublock on http://m.ceriah.com/qingyunian/2107287.html

**Closed** 2020-08-10 18:25 UTC
Labels: Feature:Toolbar, eng:qa:verified, 🐞 bug
