### ISSUE TITLE
"Allow audio only" autoplay setting

### ISSUE THREAD

**Issue by kaipoeritz** [mozilla-mobile/fenix#16009] opened 2020-10-18 18:08 UTC
I am missing the desktop version of "allow audio" on my Android Firefox.
Could you add it please?
Android [https://imgur.com/a/eVkJyZ5](https://imgur.com/a/eVkJyZ5) 
Desktop [https://imgur.com/uU9I6jy](https://imgur.com/uU9I6jy)

**Comment by liuche** [comment] 2020-10-22 01:20
Do we expose the Audio, no Video setting in GeckoView?

**Comment by agi** [comment] 2020-10-22 18:35
@liuche I don't understand what we're missing, from the screenshot we have three possible options

- Allow both audible and inaudible autplay
- Block audible autoplay but allow inaudible
- Block audible and inaudible autoplay

and it seems to be the same as Desktop?

**Comment by cadeyrn** [comment] 2020-10-22 18:48
@agi Only the second and third options are the same. On Android the first option makes a difference between WiFi and cellular data, Firefox on desktop does not distinguish. There is no "always allow" option in Firefox for Android.

**Comment by liuche** [comment] 2020-10-23 05:45
Sorry, that's my mistake - I thought the request was for "play audio, block video" as the title says ("allow audio only"). However, a) Desktop doesn't provide the "audio only setting" as seen in the screenshot, and b) if the request is for "allow audio, video on cellular" that is a dupe of #10464.

**Closed by liuche** 2020-10-23 05:45 UTC
Labels: Feature:SitePermissions, feature request 🌟
