### ISSUE TITLE
[Bug][a11y] Add private shortcut button needs resizing

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#17904] opened 2021-02-08 11:32 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)
## Prerequisites
Have Google Accessibility Scanner installed.

## Steps to reproduce
1. From the Home screen, tap on the upper right Private Browsing icon and switch to Private Mode. (perform the switch 3 times).
2. Using the Accessibility Scanner, scan the Add Private Browsing Shortcut to your Home screen contextual recommender.

### Expected behavior
The Private Browsing Shortcut recommender is properly scanned and no suggestions are made.

### Actual behavior
![Screenshot_20210204_164533_com google android apps accessibility auditor](https://user-images.githubusercontent.com/58466444/107213900-c8c0d100-6a11-11eb-85ae-f542faf49b6f.jpg)

### Device information
* Device vendor / model and Android version: Huawei P40 Lite (Android 11).
* Firefox for Android version: 86.0.0-beta.2.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9664)

**Comment by eliserichards** [comment] 2021-03-22 23:28
https://github.com/mozilla-mobile/fenix/pull/17985

**Comment by liacds** [comment] 2021-03-30 03:02
can I work on this issue?

**Comment by liacds** [comment] 2021-03-30 06:53
I can't seem to reproduce this issue in the latest version on Pixel 2, everything works as expected

**Comment by Apurwa96** [comment] 2021-03-30 10:10
Hi, This is my first time contributing to opensource, let me know if I can work on this.

**Comment by codesuperstarr** [comment] 2021-03-30 13:54
I am an outreachy applicant. Please, I request to be assigned this issue.

**Comment by eliserichards** [comment] 2021-03-30 17:28
Hello all! @liacds, are you an Outreachy applicant? If so, since you were the first to comment, you can pick this issue up :)

**Comment by liacds** [comment] 2021-03-30 17:39
@eliserichards Yes, thank you :)

**Comment by topotropic** [comment] 2021-04-08 15:54
Thanks for the ping! If this is a problem with the button here, it might be a problem in other places as well. Our component in Figma has a height of 36dp – I remember that Sawyer worked on componentizing buttons at some point last year, so it would be great if we could systematically solve this and not just increase the size of the button here to fix this single case.

**Comment by Mugurell** [comment] 2021-04-12 15:27
Sorry for the mixup @fevziomurtekin. Your PR looked good but looks like another PR was approved and validated by UX in the meantime.
Your contribution would be much appreciated on other tickets like maybe the ones from https://github.com/mozilla-mobile/fenix/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by LaviniaL99** [comment] 2021-12-22 15:00
The issue is still reproducing on Firefox 96.0.0-beta4.

**Comment by lobontiumira** [comment] 2022-09-08 11:28
Still reproducible on the 105.0b5 Beta build with Samsung Galaxy Note 8 (Android 9).

**Comment by AdinaPetridean** [comment] 2022-10-20 09:27
Still reproducible on the 107.0b1 build with Xiaomi Pad5 (Android 12).

**Comment by SoftVision-LorandJanos** [comment] 2022-12-07 11:49
This issue is no longer reproducible on the latest Nightly 109.0a1 (2022-12-07) build.
There is no longer a "Consider making this clickable item larger" suggestion.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as fixed.

![Screenshot_2022-12-07-13-43-01-92_80a9469f53bfe75dbc6e8989be28e2f0](https://user-images.githubusercontent.com/48829350/206172167-29da84c3-ea89-4f69-8a80-89e372a7422b.jpg)

**Comment by delia-pop** [comment] 2022-12-15 13:54
Also verified fixed on Beta 109.0b1 with Lenovo Yoga Tab 11 (Android 11).

**Comment by AdinaPetridean** [comment] 2023-01-20 11:49
This issue is still reproducible on the latest Nightly 111.0a1 from 20/01/2023 and on Firefox 110.0b2 with Nokia 6 (Android 7.1.1).


<img src="https://user-images.githubusercontent.com/108326843/213688372-b885310a-cad2-477a-bd8f-77767a43b097.png" width="50%" />

**Comment by jonalmeida** [comment] 2023-01-31 00:35
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813934

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by jonalmeida** 2023-01-31 00:35 UTC
Labels: 🐞 bug, eng:qa:verified, Feature:PrivateBrowsing, access, S3
