### ISSUE TITLE
[Bug] Show native video controls in context menu, like Fennec

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14730] opened 2020-09-04 14:49 UTC
From: https://www.reddit.com/r/firefox/comments/img2ug/android_show_controls_option_is_gone_on_embedded/

## Steps to reproduce

1. Navigate to https://www.reddit.com/r/reactiongifs/comments/imfj9f/me_watching_any_magic_trick/
2. Tap image
3. Long press on video

### Expected behavior

"Show Controls" option, like in Fennec:

![signal-2020-09-04-104620](https://user-images.githubusercontent.com/152493/92252244-f8384400-ee9b-11ea-8c44-7be734aeef8c.png)

### Actual behavior

No "Show Controls" option.

Fenix has the controls available, interestingly - if you "open link in external app" and choose Fenix as the external app, the controls appear. 

### Device information

* Android device: Pixel 2
* Fenix version: nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6355)

**Comment by liuche** [comment] 2020-09-16 23:20
Are these media options exposed already through AC/GV, or would we need to add them in GV first? @agi in case you know

**Comment by agi** [comment] 2020-09-17 17:53
I don't think we support this right now. We would need some API to show controls for a given video.

**Comment by wh0** [comment] 2021-03-16 23:12
I'll take a look and see if I can reopen. thanks for the update

**Comment by wh0** [comment] 2021-09-13 17:43
leave open please

**Comment by wh0** [comment] 2022-03-12 20:45
leave open

**Comment by wh0** [comment] 2022-11-23 01:32
leave open

**Comment by jonalmeida** [comment] 2023-01-30 23:54
Closing as duplicate of #18508 since that is already a feature request.

**Closed by jonalmeida** 2023-01-30 23:54 UTC
Labels: 🐞 bug, needs:ac, needs:gv, Feature:Media
