### ISSUE TITLE
[Bug] "Sync cards" is disabled when it's enabled for the account

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/fenix#19554] opened 2021-05-19 05:14 UTC
STR:

* Have Fenix signed in to an existing account where credit-cards are configured to sync (ie, presumably configured that way on a desktop profile)
* Jump through the hoops to enable CC autofill on Fenix.
* View "Credit cards" preferences - note the "Sync cards" option - it should be enabled but is disabled.

(I'll try and dig into this, but opening it now so I don't forget. For all I know it is permanently disabled and there's a TODO to enable it :) Note that the state of this checkbox will not come from the new autofill component, but instead via the "sync manager" component)

**Comment by mcarare** [comment] 2021-05-25 06:44
Reopened for QA.

**Comment by abodea** [comment] 2021-05-26 12:09
Verified as fixed on the latest **Nightly 5/26** with **OnePlus Nord (Android 10).**
Please note that after I signed in, I checked the `Sync card` but it was off.
After the account synced it turned ON, but I do believe this is the intended behavior, so after a sign-in and then sync, it should be enabled.
@gabrielluong if you can confirm please that this is the intended behavior, thank you!

**Closed by abodea** 2021-05-26 12:09 UTC
Labels: Feature:Autofill, cc-autofill, eng:qa:needed, 🐞 bug
