### ISSUE TITLE
"Follow device theme" defaults to dark mode on light mode

### ISSUE THREAD

**Issue by reinhart1010** [mozilla-mobile/fenix#25596] opened 2022-06-12 01:54 UTC
### Steps to reproduce

**Note:** this bug occurs occasionally and difficult to reproduce (only in a handful of small cases). I'll update if there's a standard way to reproduce it.

### Expected behaviour

The appearance setting should match the device theme.

### Actual behaviour

Still using dark mode on light.

![Screenshot_20220612-085030_Settings](https://user-images.githubusercontent.com/17312341/173210966-059fe8e2-9c4c-4bec-9a7d-1741419713ec.jpg)

### Device name

Samsung Galaxy A73 5G

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

102.0.0-beta3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20691)

**Comment by marcel263** [comment] 2022-06-13 10:14
Dear, your issue proving the theming incincistency issue is recognized as #20094 or at least similar. In that case, the issue went away after a coinciding moment of upgrading the OS to 11, and reinstalling Nightly.

**Comment by hkaancaliskan** [comment] 2022-06-17 21:39
I also have the same problem with A52 (android 12).
When phone switches to dark mode automatically and Firefox was open before switching (left in light mode), Firefox will open up as light mode and won't update the theme. Clearing the Firefox from ram and opening it again fixes the problem.
My guess is Firefox is saving device theme for "follow device theme" option and not updating it when it called back from ram.

**Comment by czlucius** [comment] 2022-06-18 14:56
https://github.com/mozilla-mobile/fenix/issues/11372 (currently closed)

**Comment by dipeve** [comment] 2022-10-21 00:06
> I also have the same problem with A52 (android 12). When phone switches to dark mode automatically and Firefox was open before switching (left in light mode), Firefox will open up as light mode and won't update the theme. Clearing the Firefox from ram and opening it again fixes the problem.
> 
> Changing phone theme manually is working as expected, Firefox follows it. Firefox needs to stay in background for some time to reproduce this bug.
> 
> My guess is Firefox is saving device theme for "follow device theme" option and not updating it when it called back from ram.

Yeah, the same thing has been happening for a long time (S21, android 12, september security patch). It happens in the morning and evening after my phone automatically changes theme, and Firefox is in the background, not closed but out of focus. When opening it has the previous theme, and to solve it I have to change the theme manually with Firefox in the foreground or close it and open it again.

**Comment by Cheap-Skate** [comment] 2022-10-29 17:08
I have this issue too, Galaxy M32, Android 12

**Comment by major-mayer** [comment] 2022-11-22 13:26
> > I also have the same problem with A52 (android 12). When phone switches to dark mode automatically and Firefox was open before switching (left in light mode), Firefox will open up as light mode and won't update the theme. Clearing the Firefox from ram and opening it again fixes the problem.
> > Changing phone theme manually is working as expected, Firefox follows it. Firefox needs to stay in background for some time to reproduce this bug.
> > My guess is Firefox is saving device theme for "follow device theme" option and not updating it when it called back from ram.
> 
> Yeah, the same thing has been happening for a long time (S21, android 12, september security patch). It happens in the morning and evening after my phone automatically changes theme, and Firefox is in the background, not closed but out of focus. When opening it has the previous theme, and to solve it I have to change the theme manually with Firefox in the foreground or close it and open it again.

I can confirm that I have exactly the same issue on a Poco F3 (AOSP Rom)  with Android 12 installed.

**Comment by major-mayer** [comment] 2022-11-22 13:29
It would be great if some maintainer could take a look into this, since the issue is already open for a few months and all the linked issues seem to be closed.

**Comment by delia-pop** [comment] 2022-11-23 12:22
Hi, please note that we also encountered and separately reported this issue on https://github.com/mozilla-mobile/fenix/issues/26903, which is now closed as duplicate. 
The issue occurred initially in Firefox 104.2.0 with OPPO A15s (Android 10) and later on Firefox Nightly 107.0a1 09/21 with Xiaomi Pad5 (Android 11). Updating the Xiaomi tab from Android 11 to Android 12 "fixed" the issues. 

In the latest version of RC 107.1.0 build1/build 2, the issue was still occurring with OPPO A15s (Android 10).

**Comment by major-mayer** [comment] 2022-11-23 17:40
Hi @MozillaNoah,
thanks for your response and raising the issue's priority.
As for the reproduction steps, I can only link to what @hkaancaliskan said:

> I also have the same problem with A52 (android 12). When phone switches to dark mode automatically and Firefox was open before switching (left in light mode), Firefox will open up as light mode and won't update the theme. Clearing the Firefox from ram and opening it again fixes the problem.
> 
> Changing phone theme manually is working as expected, Firefox follows it. Firefox needs to stay in background for some time to reproduce this bug.
> 
> My guess is Firefox is saving device theme for "follow device theme" option and not updating it when it called back from ram.

This is exactly what i experienced.

**Comment by czlucius** [comment] 2022-11-24 09:57
This is one method of reproducing the bug:
1. Schedule dark mode for a time
2. Wait till the set time, with Firefox open
3. Firefox may switch the theme.
4. Go to home screen, and launch Firefox from the home screen widget (or any intent in general)

**Comment by Cheap-Skate** [comment] 2022-12-07 13:38
> * it is a OEM issue with their fork of Android which does not handle configuration changes in the way that is expected

I concur, I think it's a Samsung bug interacting with Fenix (or a Fenix bug?). I will see if the problem still occurs when I get my Android 13 upgrade in a few weeks.  Thanks for checking.

**Comment by dipeve** [comment] 2022-12-18 18:28
Hi, in a Samsung S21, on android 13, it still happens twice a day when the device theme changes automatically (dark=>light=>dark) and firefox is opened but inactive. I mostly keep firefox in memory during the day.
And for context, no other app have this behavior.

Add a video for reference.
https://user-images.githubusercontent.com/53589762/208312887-211fa591-8bfa-4750-8591-0b2552454e21.mp4

**Comment by csadilek** [comment] 2023-01-30 20:55
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813771

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2023-01-30 20:55 UTC
Labels: 🐞 bug, needs:triage
