### ISSUE TITLE
[Bug]Zoomed in about:cache

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9124] opened 2020-03-12 10:05 UTC
## Steps to reproduce
1. Navigate to about:cache
2. Observe
3. Tap the refresh button from the  ⋮ main menu overlay
4. Observe

### Expected behavior
The about: cache page shouldn't be zoomed in when opening it for the 1st time.

### Actual behavior
When first opening the about;cache the page is zoomed in.
Only after refreshing the page it gets properly displayed

### Device information

* Android device: 
• Google Pixel 4XL (Android 10)
• Google Pixel 3a (Android 9)
• OnePlus A3 (Android 6.0.1)

* Fenix version: 
• Fenix Nightly Build #20711809 from 3/11
• Fenix Beta 4.1.0-beta.1 from 3/12 

### Notes
►Video
![20200312-115457](https://user-images.githubusercontent.com/51314259/76509987-8e456180-6459-11ea-8c52-9947cbbce9d4.gif)

**Comment by Diana-Rus** [comment] 2020-03-12 15:59
Hi, the same outcome is encountered when accessing other about pages: about:about, about:support, about:networking, about:crashes, about:performance, about:memory, about:telemetry, about:webrtc, about:url-classifier, about:credits. about:mozilla.


Note: about:config, about:logo pages are not affected

Device: Samsung Galaxy S8+ (Android 8)
Build: Firefox Preview Beta 4.1.0-beta1

**Comment by kbrosnan** [comment] 2020-03-12 17:18
Closing as a dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=1477698

**Closed by kbrosnan** 2020-03-12 17:18 UTC
Labels: S2, needs:triage, 🐞 bug
