### ISSUE TITLE
[Bug] StrictMode death when opening app from Search Widget

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#15430] opened 2020-09-25 19:44 UTC
## Steps to reproduce
1. Open debug from search widget

### Expected behavior
open app

### Actual behavior
crash because of strict mode violation

### Device information

* Android device: ?
* Fenix version: ?

**Comment by philippbara** [comment] 2020-09-25 22:36
Wanted to start contributing to this project but couldn't get the app to launch on my **Samsung Galaxy A50 (Android 10)**. Didn't have any problem with the **Pixel 2 virtual device**. Guess this is the same issue:

2020-09-26 00:26:46.871 11588-11588/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 11588
    java.lang.RuntimeException: StrictMode ThreadPolicy violation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1768)
        at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$handleViolationWithTimingAttempt$0$StrictMode$AndroidBlockGuardPolicy(StrictMode.java:1687)
        at android.os.-$$Lambda$StrictMode$AndroidBlockGuardPolicy$9nBulCQKaMajrWr41SB7f7YRT1I.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7814)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
     Caused by: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1524)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1193)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:165)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:152)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
        at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:271)
        at com.android.server.enterprise.storage.EdmStorageProviderBase.getValues(EdmStorageProviderBase.java:388)
        at com.android.server.enterprise.storage.EdmStorageProviderBase.getValuesList(EdmStorageProviderBase.java:1104)
        at com.android.server.enterprise.storage.EdmStorageProvider.getValuesList(EdmStorageProvider.java:300)
        at com.android.server.enterprise.application.ApplicationPolicy.getApplicationStateEnabledAsUser(ApplicationPolicy.java:3783)
        at com.android.server.enterprise.application.ApplicationPolicy.getApplicationStateEnabledAsUser(ApplicationPolicy.java:3735)
        at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:25692)
        at com.android.server.pm.PackageManagerService.setComponentEnabledSetting(PackageManagerService.java:25668)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3774)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4994)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)

Would be happy to work on this issue if you don't think its to complex for a newbie! Cheers

**Comment by mcarare** [comment] 2020-10-19 14:33
I cannot reproduce this with the latest `StrictModeManager` changes. 
@ekager does it still happen to you?

**Comment by sflorean** [comment] 2020-10-27 11:47
I was able to reproduce this issue on Samsung Galaxy Note10 (Android10) and LG G7 FIT (Android 8) on the latest debug build.

2020-10-27 13:46:27.456 15878-15878/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 15878
    java.lang.RuntimeException: StrictMode ThreadPolicy violation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1768)
        at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$handleViolationWithTimingAttempt$0$StrictMode$AndroidBlockGuardPolicy(StrictMode.java:1687)
        at android.os.-$$Lambda$StrictMode$AndroidBlockGuardPolicy$9nBulCQKaMajrWr41SB7f7YRT1I.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1524)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1193)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:165)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:152)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
        at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:271)
        at com.android.server.enterprise.storage.EdmStorageProviderBase.getValues(EdmStorageProviderBase.java:388)
        at com.android.server.enterprise.storage.EdmStorageProviderBase.getValuesList(EdmStorageProviderBase.java:1104)
        at com.android.server.enterprise.storage.EdmStorageProvider.getValuesList(EdmStorageProvider.java:300)
        at com.android.server.enterprise.application.ApplicationPolicy.getApplicationStateEnabledAsUser(ApplicationPolicy.java:3745)
        at com.android.server.enterprise.application.ApplicationPolicy.getApplicationStateEnabledAsUser(ApplicationPolicy.java:3714)
        at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:25996)
        at com.android.server.pm.PackageManagerService.setComponentEnabledSetting(PackageManagerService.java:25972)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3774)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5148)
        at android.os.Binder.execTransactInternal(Binder.java:1056)
        at android.os.Binder.execTransact(Binder.java:1029)
2020-10-27 13:46:27.457 15878-15878/org.mozilla.fenix.debug E/ExceptionHandler: Uncaught exception handled: 
    java.lang.RuntimeException: StrictMode ThreadPolicy violation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1768)
        at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$handleViolationWithTimingAttempt$0$StrictMode$AndroidBlockGuardPolicy(StrictMode.java:1687)
        at android.os.-$$Lambda$StrictMode$AndroidBlockGuardPolicy$9nBulCQKaMajrWr41SB7f7YRT1I.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1524)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1193)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:165)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:152)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
        at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:271)
        at com.android.server.enterprise.storage.EdmStorageProviderBase.getValues(EdmStorageProviderBase.java:388)
        at com.android.server.enterprise.storage.EdmStorageProviderBase.getValuesList(EdmStorageProviderBase.java:1104)
        at com.android.server.enterprise.storage.EdmStorageProvider.getValuesList(EdmStorageProvider.java:300)
        at com.android.server.enterprise.application.ApplicationPolicy.getApplicationStateEnabledAsUser(ApplicationPolicy.java:3745)
        at com.android.server.enterprise.application.ApplicationPolicy.getApplicationStateEnabledAsUser(ApplicationPolicy.java:3714)
        at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:25996)
        at com.android.server.pm.PackageManagerService.setComponentEnabledSetting(PackageManagerService.java:25972)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3774)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5148)
        at android.os.Binder.execTransactInternal(Binder.java:1056)
        at android.os.Binder.execTransact(Binder.java:1029)

**Comment by sflorean** [comment] 2020-11-03 14:26
We tested this issue on a debug build from 11/3 and here are our findings:
- **not reproducible**:  Google Pixel 3a (Android 11), Huawei Mate 20 Lite (Android 10), OnePlus A3 (Android 6.0.1)
- **reproducible**: Samsung Galaxy Note10(Android 10), LG G7 FIT (Android 8).

**Comment by mcarare** [comment] 2020-11-04 11:31
As per the comment above and the issue opened for the new strict mode violation unrelated to the widget (https://github.com/mozilla-mobile/fenix/issues/16347), I am closing this.

**Closed by mcarare** 2020-11-04 11:31 UTC
Labels: eng:health, eng:ready, hershey, 🐞 bug
