### ISSUE TITLE
[Bug] Crashing when accessing old Collections item 

### ISSUE THREAD

**Issue by benjsnellings** [mozilla-mobile/fenix#17219] opened 2020-12-25 18:30 UTC
## Steps to reproduce
Open an older collections item. For some reason newer ones do not cause issue. I cannot say what date exactly the issue started, as i was not paying that much attention. Some time within the last month.

### Expected behavior
Collections tab opens a new link

### Actual behavior
Onclick causes a app crash
https://crash-stats.mozilla.org/report/index/afa7cd35-6393-4825-bb91-204400201225

### Device information

* Android device: Pixel 2 XL - unrooted, lastest patch
* Fenix version: 201224

**Comment by sflorean** [comment] 2020-12-31 13:10
Tested on Pixel 3 (Android 11) and couldn't reproduce this issue on latest Nightly build. @benjsnellings Do you have any additional steps?

**Comment by benjsnellings** [comment] 2020-12-31 16:06
Like I mentioned in the description I cannot seem to create a new collections item with the issue, only for items that were made before some build

**Comment by csadilek** [comment] 2021-01-07 19:27
@benjsnellings Would mind checking if this still happens for you in latest Nightly? We landed some fixes that hopefully covered this.

**Comment by benjsnellings** [comment] 2021-01-07 19:30
It appears to be working now

**Closed** 2021-01-07 19:50 UTC
Labels: needs:triage, 🐞 bug
