### ISSUE TITLE
Crash [@ java.lang.OutOfMemoryError: at java.util.Arrays.copyOf(Arrays.java) ]

### ISSUE THREAD

**Issue by argha54325** [mozilla-mobile/fenix#19476] opened 2021-05-12 02:38 UTC
```
ab58f3a3-7e51-4f88-9327-0821c6e008a1
<native crash>
----
<native crash>
```
```
d19137ef-b37b-4c06-b94d-85c65736560b
java.lang.OutOfMemoryError: Failed to allocate a 1048588 byte allocation with 756544 free bytes and 738KB until OOM
* Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec/?query=6be1ba78784f4b45a59f285fdf4809f6
* Socorro: https://crash-stats.mozilla.org/report/index/bp-28c065c0-7fd1-4974-85c1-9af810210506
----
java.lang.OutOfMemoryError: Failed to allocate a 1048588 byte allocation with 756544 free bytes and 738KB until OOM
at java.util.Arrays.copyOf(Arrays.java:3256)
at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
at androidx.core.app.AppOpsManagerCompat.copyTo(AppOpsManagerCompat.java:3)
at androidx.core.app.AppOpsManagerCompat.copyTo$default(AppOpsManagerCompat.java:1)
at androidx.core.app.AppOpsManagerCompat.readBytes(AppOpsManagerCompat.java:2)
at mozilla.components.browser.icons.loader.HttpIconLoaderKt$toIconLoaderResult$1.invoke(HttpIconLoader.kt:2)
at mozilla.components.concept.fetch.Response$Body.useStream(Response.kt:1)
at mozilla.components.browser.icons.loader.HttpIconLoader.load(HttpIconLoader.kt:17)
at mozilla.components.browser.icons.BrowserIcons.access$loadIconInternal(BrowserIcons.kt:13)
at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:2)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)

```
 ```
ad19ac60-1498-4925-acd9-427586e2983a
<native crash>
* Socorro: https://crash-stats.mozilla.org/report/index/bp-3b8e2a66-6dcf-4e47-8a21-ef1460210427
----
<native crash>
```
 ```
ffbad415-cec2-4e89-ac37-4696d1394355
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1150092 bytes
* Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec/?query=f3e50f6195b340b4bf3cc3df598617f7
* Socorro: https://crash-stats.mozilla.org/report/index/bp-a87a7858-f1ca-479c-b813-f50b80210423
----
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1150092 bytes
at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4209)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6776)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Caused by: android.os.TransactionTooLargeException: data parcel size 1150092 bytes
at android.os.BinderProxy.transactNative(Native Method)
at android.os.BinderProxy.transact(Binder.java:628)
at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:4183)
at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4201)
... 7 more
```

**Comment by argha54325** [comment] 2021-05-12 02:39
I don't have any knowledge of what all those are.. If anybody understand the true reason of these crashes Just let me know the reason??

**Comment by kbrosnan** [comment] 2021-05-12 17:11
Looks similar to https://github.com/mozilla-mobile/android-components/issues/10076

**Comment by argha54325** [comment] 2021-05-14 17:38
> Looks similar to [mozilla-mobile/android-components#10076](https://github.com/mozilla-mobile/android-components/issues/10076)

Why this error is happening in my phone everytime?

**Comment by lobontiumira** [comment] 2021-05-20 09:17
Closing this issue as a dupe of #17600.

**Closed by lobontiumira** 2021-05-20 09:17 UTC
Labels: b:crash, needs:triage
