### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by eduaddad** [mozilla-mobile/fenix#987] opened 2019-03-13 09:42 UTC
Is the translations available and if not how can I help with the translation of the future program?

**Comment by Foorack** [comment] 2019-03-13 13:50
Duplicate of https://github.com/mozilla-mobile/fenix/issues/217

**Comment by vesta0** [comment] 2019-04-01 05:30
@eduaddad yes we are working on localization of the browser. Thanks for offering to help, we will get back to you!

**Comment by Delphine** [comment] 2019-04-01 15:13
@eduaddad Hi and thanks for your interest in translating. What language are you interested in contributing to?
We translate using our own tool called Pontoon, I'll be glad to let you a bit more about this. You can reach out to me here: delphine at mozilla dot com
thanks

**Closed** 2019-04-03 21:33 UTC

**Comment by eduaddad** [comment] 2019-04-03 22:11
@Delphine 

Brazilian portuguese

**Comment by Delphine** [comment] 2019-04-03 22:13
@eduaddad Ok please send me an email to the address I mentioned above, so that we can be in contact about this (I don't have yours). thanks

**Comment by eduaddad** [comment] 2019-04-03 22:13
@Delphine  duduaddad@gmail.com

**Comment by Delphine** [comment] 2019-04-03 22:20
email sent, thanks so much!

**Comment by eduaddad** [comment] 2019-04-03 22:24
Could you indicate the translation so I can translate? @Delphine

**Comment by Delphine** [comment] 2019-04-03 22:57
I've sent all the info needed via email. let's follow-up there, please :)
