### ISSUE TITLE
Desktop's "Always use private browsing mode" equivalent for Fenix

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#6472] opened 2019-11-06 10:41 UTC
Just like desktop Firefox, there should be a toggle to enable private browsing mode permanently, so that no matter how the user opens a tab (tapping on a link, app intent, tapping on a bookmark), it opens in private browsing mode only. Across app restarts as well as phone restarts. No non-private tabs unless that setting is turned off.

### Design Work

- [x] Request for Comments from UX team
- [ ] ~Usability testing if a new pattern or potentially confusing UI~ Not required – this is a behaviour change
- [x] Request for Comments from Fenix team and/or A/C, GV, Sync, etc as needed
- [x] Interaction details included
- [x] Accessibility ~- is this a review by someone,~ just keeping it in mind?
- [ ] ~For existing UI changes, deltas are highlighted~ No UI – this is a behaviour change
- the[ ] ~Strings/content reviewed and approved~ No string – this is a behaviour change
    - [ ] ~Are they too long for the component in other locales~

### Deliverable

- [ ] ~Assets uploaded to Google Drive~
- [ ] ~Links to deliverables (spec, assets) posted in comment 0~

### Deliverable Links

- User flow: https://miro.com/app/board/o9J_kvokVqQ=/
- ~Spec: (link to e.g. Abstract artboards)~
- ~Assets: (link to Google Drive folder)~

### Behaviours

> Once you've enabled private browsing through all the settings that are available in Fenix, you shouldn't be surprised with a non-private tab, no matter how a link is opened.
> —@opusforlife2

To do this, Private Browsing is complemented with behaviours as listed below:

- If Fenix private browsing is accessed from its private homescreen icon:
    - Tapping “Back” will dismiss the search screen and return to `about:privatebrowsing`
    - Tapping “Back” a second time will quit to homescreen
    - Tapping “Back” should _never_ return you to normal browsing, unless normal browsing exists in your history stack #6304 
- Any bookmarks or history item you open while under private mode, should also open in private mode (#7041)

**Comment by cadeyrn** [comment] 2019-11-06 11:21
There is already an option to open links in private mode and you can create a launcher icon for private mode. Which use case is not covered by these two options?

**Comment by athomasmoz** [comment] 2019-11-27 17:15
There is a setting for this, however it requires you to have Firefox Preview set as your default browser. Assigning for UX for input

**Comment by athomasmoz** [comment] 2019-11-27 17:35
Closing as a duplicate of #6382

**Comment by opusforlife2** [comment] 2019-12-01 18:56
@athomasmoz I do have Fenix set as my default browser. I'm not sure what setting you're referring to. For more context on where this issue originated from, see here: https://github.com/mozilla-mobile/fenix/issues/4780#issuecomment-544094389

**Comment by opusforlife2** [comment] 2019-12-07 18:09
@sblatz ?

**Comment by sblatz** [comment] 2019-12-09 14:55
Hey @opusforlife2! If you go to Settings > Set as Default Browser > Open links in a private tab

If you do this in addition to "adding a private browsing shortcut" (Settings > Add private browsing shortcut) that should cover your use case.

Please let me know if this does not :)

**Comment by opusforlife2** [comment] 2019-12-09 19:39
@sblatz It doesn't work for history and bookmarks.

Another problem which I've stated before and am copying from https://github.com/mozilla-mobile/fenix/issues/4780#issuecomment-545064021, is this: "One minor nitpick with the current behavior: When you open Fenix using the private browsing shortcut, it takes you straight to the address bar in private browsing mode, but if you tap back, it switches to non private browsing."

Can it not open to the regular home page, but in private browsing mode?

**Comment by sblatz** [comment] 2019-12-09 22:43
> Can it not open to the regular home page, but in private browsing mode?

I think this is a good point for UX to consider.

**Comment by brampitoyo** [comment] 2019-12-12 01:32
@opusforlife2 I tend to agree with @sblatz.

You can make private browsing “permanent” by:

- Accessing Fenix from your phone homescreen through its private icon
- Using Fenix private custom tabs when opening third-party links

I agree that those aren’t complete, and needs to be complemented with other behaviours as listed below:

- If Fenix private browsing is accessed from its private homescreen icon:
    - Tapping “Back” will dismiss the search screen and return to `about:privatebrowsing`
    - Tapping “Back” a second time will quit to homescreen
    - Tapping “Back” should _never_ return you to normal browsing, unless normal browsing exists in your history stack
- Any bookmarks or history item you open while under private mode, should also open in private mode (thanks @sblatz for filing #7041!)

Does this sound reasonable, @opusforlife2?

**Comment by opusforlife2** [comment] 2019-12-12 11:45
@brampitoyo Your bullets summarize it perfectly.

My ultimate aim here is that once you've enabled private browsing through all the settings that are available in Fenix, you shouldn't be surprised with a non-private tab, no matter how a link is opened.

**Comment by brampitoyo** [comment] 2019-12-16 03:38
Thanks @opusforlife2!

@sblatz I’ve updated comment 0 with user flow and behaviours. They’re mostly copy-pasted from my comment up above. Hopefully it will enable anybody to implement without digging through the comment section!

**Comment by vesta0** [comment] 2020-04-28 05:06
@brampitoyo will you please test to see if the current browser behaviour matches your suggestion captured in the description (comment 0)? Thank you!

**Comment by opusforlife2** [comment] 2020-07-30 16:13
This is done, right? It can be closed?

**Comment by brampitoyo** [comment] 2020-08-03 03:05
Thanks @vesta0. I’ve tested the Private Browsing shortcut and confirmed that the behaviour matched my specs on comment 0. With everything matching, we can now close this issue.

Thanks again to @opusforlife2 for originally filing this issue.

**Closed by brampitoyo** 2020-08-03 03:05 UTC
Labels: Feature:PrivateBrowsing, eng:ready, feature request 🌟
