### ISSUE TITLE
Improvement of the picture in picture mode

### ISSUE THREAD

**Issue by kayschubertwebde** [mozilla-mobile/fenix#21457] opened 2021-09-22 21:20 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Firefox has already implemented the Android picture in picture mode, but this can be improved even further. Currently when you use this feature the main window of Firefox disappears.
### How do you know that this problem exists today? Why is this important?
I know from an other app (a video app from Germany: RTL TVNOW), that it is possible to have the main window still open during using this feature. So if you would implement this feature in the same way like this app, you could continue browsing during watching a video as a thumbnail.
### Who will benefit from it?
All users

**Comment by jonalmeida** [comment] 2021-09-23 00:02
Duplicate of https://github.com/mozilla-mobile/fenix/issues/6600

**Closed by jonalmeida** 2021-09-23 00:02 UTC
Labels: needs:triage
