### ISSUE TITLE
FNX-4371 ⁃ Swipe address bar to change tab or open tabs overview

### ISSUE THREAD

**Issue by scratchmex** [mozilla-mobile/fenix#10548] opened 2020-05-11 01:26 UTC
### Why/User Benefit/User Problem
If I want to switch between 2 tabs I need 2 clicks, one in the address bar tabs icon and one in the actual tab I want to switch to 
An improvement of this behavior could be the ability to swipe left or right on the address bar to switch between the previous or next bar currently open. In addition, I think it could be a smoother experience to be able to swipe down (in case the address bar is in the top, or up in the other case) to open the tabs overview.

### What/Requirements
* A function and animation to switch between tabs with that gesture
* a function and animation to activate the tabs overview with that gesture
    1. Acceptance Criteria (how do I know when I’m done?)

**Comment by SS1113** [comment] 2020-05-11 02:55
Duplicate of #3481

**Comment by ekager** [comment] 2020-05-11 02:56
closing as dupe of #3481

**Comment by scratchmex** [comment] 2020-05-11 02:57
I think only misses the swipe down (or up) for tabs overview. Sorry, I was sure I searched before opening.

**Comment by SS1113** [comment] 2020-05-11 03:06
@scratchmex you can track the all the gestures Meta here #176

**Closed** 2020-08-11 01:00 UTC
Labels: needs:triage
