### ISSUE TITLE
[Bug] Crash on opening search settings

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#12944] opened 2020-07-25 19:30 UTC
## Steps to reproduce
1. Open Fenix
1. Three dot menu
1. Settings
1. Search

### Expected behavior
Search settings opens

### Actual behavior
Fenix crashes

### Device information
* Android device: Moto E5
* Fenix version: Nightly 200725 06:01 (Build #22070612)

**Comment by kbrosnan** [comment] 2020-07-25 21:00
Is there a crash ID? https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by LittleAngelwings** [comment] 2020-07-25 21:24
@kbrosnan 

Here is a Socorro for this issue: https://crash-stats.mozilla.org/report/index/f742542d-8bb9-4d3a-97f8-9d8230200725
It's from my try to reproduce it.

**Comment by SeburoSUMO** [comment] 2020-07-25 22:35
Not all the crashes from this issue had a link to Socorro, but one that did was:

https://crash-stats.mozilla.org/report/index/636a7ad8-faf0-4ab2-8b4e-1d09a0200725

**Comment by hakkikaancaliskan** [comment] 2020-07-26 07:58
Duplicate of #12929

**Comment by ekager** [comment] 2020-07-26 14:34
Closing for  #12929

**Closed** 2020-08-14 00:25 UTC
Labels: b:crash, needs:triage, 🐞 bug
