### ISSUE TITLE
Toolbar is unclickable after pressing the back button.

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#536] opened 2019-02-15 21:13 UTC
## Steps to reproduce
1. Enter a url to the toolbar/search bar.
2. When the page is loaded, click the toolbar.
3. Observe that the awesomebar opens and you are able to edit the toolbar bar address.
4. Press the back system button.
5. Click on the toolbar again.

### Expected behavior
Step 3 should be repeatable, i.e. you can click and edit the toolbar.

### Actual behavior
The toolbar is unclickable.

### Device information

* Android device: Android 9 (Pixel 2)
* Fenix version: Latest nightly (15/02/2019)

My guess is that when you click the back button, the ToolbarUIView is not re-inited so the `onUrlClicked` state is left as false:
```kotlin
onUrlClicked = {
    actionEmitter.onNext(SearchAction.ToolbarTapped)
    false
}
```

**Comment by colintheshots** [comment] 2019-02-17 03:08
This is a dupe of #523. We were cleaning up disposables too aggressively because Lifecycle doesn't handle all Fragment lifecycle callbacks. Fixed properly with the fix to #541.

**Closed by colintheshots** 2019-02-17 03:08 UTC
Labels: 🐞 bug
