### ISSUE TITLE
[Bug] Can't download images that require cookies to be passed to the request (CloudFlare)

### ISSUE THREAD

**Issue by Ruin0x11** [mozilla-mobile/fenix#12795] opened 2020-07-21 18:45 UTC
## Steps to reproduce
1. Go to a website behind CloudFlare or similar protection.
1. Try to download an image hosted on the same domain.

### Expected behavior
The image is saved.

### Actual behavior
The download fails with "failed to download". This is because the cookies saved by CloudFlare are required for any request to a resource on the domain, but when downloading an image only they are not sent.

I tried this using Chromium on Android and it works.

See also #12182.

### Device information
* Android device: OnePlus 7T
* Fenix version: 79.0.0-beta.9 (Build #2015752523)
AC: 48.0.5, c14ffa848
GV: 79.0-20200713185329
AS: 61.0.7

**Comment by kbrosnan** [comment] 2020-07-21 19:01
Please check this behavior on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix). There has been some work in this area and the problem may be solved there. If it is not fixed on nightly then this is a likely dupe of #7531

**Comment by Ruin0x11** [comment] 2020-07-21 22:32
@kbrosnan I thought Nightly was deprecated, since it gave me a message saying it was no longer going to receive security updates. Then it redirected me to download Firefox Beta instead on the Play Store.

**Comment by Dunexus** [comment] 2020-07-22 09:09
The message shown on nighlty is that nightlies can be unstable, if you want something more stable, please download beta.
It has been added as some users used nightly as their main browser and were in trouble when the was some king of regressions or crashes introduced in nightly.

However, Firefox Preview Nighly <org.mozilla.fenix.nightly> has been deprecated, you should now use Firefox Nightly <[org.mozilla.fenix](https://play.google.com/store/apps/details?id=org.mozilla.fenix)>

**Comment by Ruin0x11** [comment] 2020-07-22 09:25
Oh I see, I got the deprecation message specifically and ended up with two copies of Nightly, that would explain it. I'll try Nightly instead.

**Comment by lnicola** [comment] 2020-07-22 12:16
CC https://github.com/mozilla-mobile/fenix/issues/7961

**Comment by liuche** [comment] 2020-07-29 02:03
@Ruin0x11 did you get this to work?

**Comment by Ruin0x11** [comment] 2020-07-29 05:12
No, it still doesn't work.

![Screenshot_20200728-221034_Firefox_Nightly](https://user-images.githubusercontent.com/6700637/88759345-6b250100-d11f-11ea-99c3-87d18296e659.png)

Nightly 200725 06:01 (Build #22070613)
AC: 52.0.20200724130127, 71b462d5b
GV: 80.0a1-20200723095657
AS: 61.0.10

**Comment by mobd** [comment] 2020-09-29 04:33
Any update on this?

**Comment by Amejia481** [comment] 2020-09-29 17:55
> Any update on this?

Hopefully https://github.com/mozilla-mobile/android-components/pull/8433 will fix this issue.

**Comment by Amejia481** [comment] 2020-11-06 15:42
I think this should be fixed nightly, @Ruin0x11 could you give a try? :) 
QA team could you help us to verify :)

**Comment by ebalazs-sv** [comment] 2020-11-10 08:44
Verified as fixed on Nightly 201110 05:01 (Build #2015774761) GV 84.0a1 from 11/10 with the devices:

- Motorola Moto G6 (Android 8);
- Google Pixel 2 (Android 9);
- Huawei P9 Lite (Android 7).

The images from https://i.warosu.org/data/jp/img/ are downloaded.
Also, this is not reproducible on the latest Beta 83.0.0-beta.4 GV 83 from 11/9 and on the latest Release 82.1.3 GV 82 from 11/9.

I will remove the qa:needed label and close this issue.

**Closed by ebalazs-sv** 2020-11-10 08:44 UTC
Labels: Feature:Download, eng:qa:needed, 🐞 bug

**Comment by Ruin0x11** [comment] 2021-02-15 17:20
Can this be reopened? It doesn't work for Pixiv on latest (210213 17:03).

![Screenshot_20210215-091804_Firefox_Nightly](https://user-images.githubusercontent.com/6700637/107976766-ebea0400-6f6e-11eb-9829-8129a15005da.png)

https://www.pixiv.net/artworks/72525281

**Comment by Amejia481** [comment] 2021-02-16 15:23
> Can this be reopened? It doesn't work for Pixiv on latest (210213 17:03).
> 
> ![Screenshot_20210215-091804_Firefox_Nightly](https://user-images.githubusercontent.com/6700637/107976766-ebea0400-6f6e-11eb-9829-8129a15005da.png)
> 
> https://www.pixiv.net/artworks/72525281

We have an opened issue for downloading using long press (the contextual menu) see https://github.com/mozilla-mobile/fenix/issues/17716#issuecomment-770937645
