### ISSUE TITLE
Reenable options to select tabs and share all tabs in private browsing

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#17026] opened 2020-12-14 17:38 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently we're not able to select tabs from the tab tray in private browsing like is possible for normal tabs. The "Share all tabs" and "Select all tabs" options are also missing from the three dot menu.

### How do you know that this problem exists today? Why is this important?
It feels inconsistent to have this functionality in one place but not the other. I understand it was probably removed because those options might not feel as "private", however private browsing has other use cases than keeping things private (ie. keeping logins separate, loading pages without existing cookies/cache). I don't see any reason not to allow users the option of using these things, it would be really hard to click them by accident.

### Who will benefit from it?
Users who want to share multiple private tabs, send them to another device, easily bookmark them, etc.

**Comment by eliserichards** [comment] 2021-04-08 17:22
Closing as duplicate of #15865

**Closed by eliserichards** 2021-04-08 17:22 UTC
Labels: Feature:PrivateBrowsing, Feature:Tabs
