### ISSUE TITLE
FNX-5350 ⁃ Add prompt before loading QR code

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#1955] opened 2019-04-23 22:30 UTC
## Steps to reproduce
* Open fenix and tap into the address bar
* tap on the scan button
* Scan a QR code

### Expected behavior
* User action is required to load a URL/preform a search

### Actual behavior
* URL / Search is automatically preformed

### Device information
* Android device: ?
* Fenix version: ?

**Comment by vesta0** [comment] 2019-04-23 23:12
@kbrosnan I believe this is intended behaviour. @mheubusch please confirm.

**Comment by kbrosnan** [comment] 2019-04-23 23:55
The user can't know what the QR code contains. Providing some feedback on what information the user is getting from the QR code would prevent the user from getting an unexpected destination. Could we have the user confirm the information retrieved is useful?

    | https://evil.example.com |
    |          [Load] [Cancel] |
    
    |              Evil string |
    |        [Search] [Cancel] |

**Comment by colintheshots** [comment] 2019-04-24 00:20
We're well aware of this and were seeking feedback on the exact message.

**Comment by topotropic** [comment] 2019-04-24 14:20
@colintheshots We can show a prompt similar to what we do when we ask for permission. 
![Prompt](https://user-images.githubusercontent.com/353960/56666760-c1013280-66ac-11e9-9b67-b80bd215df95.png)

**Comment by colintheshots** [comment] 2019-04-26 17:40
@topotropic Is it okay if I use quotes or italics for the URL part? Not all barcodes contain URLs. It could be an ISBN for a book, for example?

**Comment by sv-ohorvath** [comment] 2019-05-02 12:00
Verified as fixed on Master. build 5/2.

**Closed** 2020-08-11 13:24 UTC
Labels: Feature: QRCode, P1, eng:qa:verified
