### ISSUE TITLE
Use dark background before page loads when in dark mode

### ISSUE THREAD

**Issue by theRealPadster** [mozilla-mobile/fenix#15037] opened 2020-09-13 01:47 UTC
### What is the user problem or growth opportunity you want to see solved?
When I'm using dark mode (browser UI, my phone, and the dark reader addon), and I load a page, it flashes white for a brief second before loading the page. Maybe change the default page background colour to black if the user is in dark mode?

### How do you know that this problem exists today? Why is this important?
It happens to me and is pretty disruptive if you're browsing in a dark environment, like before bed. 

### Who will benefit from it?
Anyone using dark mode, especially in the dark. 

Also, I'm not sure if this is a Firefox bug or something that would be controlled by the Dark Reader addon, so I've filed a bug there as well. This one can be closed if it's under the control of Dark Reader.

**Comment by OddEvans** [comment] 2020-09-13 03:34
Please add this, it just need to be the loading page at least as we have dark reader but this will 100% make the browser better

**Comment by hwinnemoe** [comment] 2020-09-13 07:59
Duplicate of #6313 and BZ-1663732

**Closed** 2020-09-13 12:35 UTC
Labels: needs:triage
