### ISSUE TITLE
The Today's tab is duplicated every time when tapping on it

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#761] opened 2019-03-01 12:55 UTC
## Steps to reproduce
1. Install and launch Fenix.
2. Open 2-3 random websites. 
3. The websites are displayed in **`Today's`**  tab/section.
4. Tap on the **`Today`** tab.

### Expected behavior
The **`Today`** tab is duplicated with all the current opened websites.
### Actual behavior
Nothing should happen here when tapping on the **`Today's`** tab.
### Device information

* Android device: **`Samsung Galaxy Note 9 (Android 8.1.0), Google Pixel 3(Android 9/P)`**.
* Fenix version:  **`1.0.1909 (Build #10591638 🦎 67.0a1-20190227104426)`**.
### Notes
The extra Today's tab are not deleted after a restart, only if deleting them one by one.
For more details please see the attachments:
[Video](https://drive.google.com/file/d/11_NnBCZWsuH7bMRA1h1cu0hInXe1Yy-f/view?usp=sharing)
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/2919441/logcat.txt)

**Comment by sv-ohorvath** [comment] 2019-03-01 13:44
Dupe of #741.

**Closed** 2019-03-01 13:44 UTC
Labels: 🐞 bug
