### ISSUE TITLE
[Bug]paste/select all dialog not showing

### ISSUE THREAD

**Issue by Hubfront** [mozilla-mobile/fenix#3378] opened 2019-06-12 09:24 UTC
## Steps to reproduce
Try to paste data into an input/user name/passwords field on web.de

### Expected behavior
Should show dialog for select all/paste/copy

### Actual behavior
Nothing happens (but works as expected on computerbase.de. Fennec works on both sites as expected).

### Device information
Samsung S9 plus

* Android device: ?
* Fenix version: 1.0.1924 (Build #11630620 :lizard: 68.0-20190604110028)

**Comment by Hubfront** [comment] 2019-06-12 09:27
Tested on web.de

But works as expected on computerbase.de

**Comment by kbrosnan** [comment] 2019-07-06 18:58
Dupe of #2590

**Closed** 2020-08-26 23:25 UTC
Labels: P2, needs:gv, 🐞 bug, 🙅 waiting
