### ISSUE TITLE
Play Store has new permission [Read phone status and identity] on update from 97 to 98 Nightly

### ISSUE THREAD

**Issue by shtstorm** [mozilla-mobile/fenix#23389] opened 2022-01-25 02:37 UTC
### Steps to reproduce

Go to Play Store and try to update Nightly from 97 to 98. There is a new permission **Read phone status and identity** being required for 98 Nightly.  I cannot find any info or commit why the new permission is needed and how intentional this change is.

### Expected behaviour

No new permissions should be required with the update without reason and explanation. Additional new permissions for established apps are bad sign for privacy and security.

### Actual behaviour

New permission **Read phone status and identity** is required. Privacy-conscious browsers should not need this permission.

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1

**Comment by tasosb** [comment] 2022-01-25 15:15
While building fenix:
```
uses-permission#android.permission.READ_PHONE_STATE
IMPLIED from \fenix\app\src\debug\AndroidManifest.xml:1:1-24:12 reason: org.mozilla.geckoview.thirdparty has a targetSdkVersion < 4
```
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1751923 as well since it might be a geckoview issue

**Comment by Amejia481** [comment] 2022-01-25 15:54
cc @agi @jonalmeida

**Comment by tasosb** [comment] 2022-02-02 00:22
This is fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1751923 and can no longer be reproduced in Nightly 98.0a1 Build 2015860683

**Closed** 2022-02-05 20:59 UTC
Labels: 🐞 bug, needs:triage

**Comment by shtstorm** [comment] 2022-02-05 21:02
Fixed by GekoView. See comment above. Thanks @tasosb !
