### ISSUE TITLE
[Bug] Tapping on "Deny" from the camera permission doesn't redirect the user to the previous screen (Turn on Sync)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#9464] opened 2020-03-27 16:14 UTC
## Steps to reproduce
1. Launch Fenix.
2. Reach the Turn on Sync from settings.
3. Tap on the `Ready to scan` button.
4. Tap on the `Deny` button.
### Expected behavior
The user is redirected to the previous screen, in this case, `Turn on Sync`.
### Actual behavior
Tapping on "Deny" from the camera permission doesn't redirect the user to the previous screen (Turn on Sync).
### Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 3/27.**

![20200327-175801](https://user-images.githubusercontent.com/42831109/77776470-bc7c9100-7056-11ea-9d15-ad21672e2a6a.gif)

**Comment by Diana-Rus** [comment] 2020-04-15 05:08
Hi, i reproduce the issue with Google Pixel 3 XL (Android 9) on Beta 4.3.0-beta.1

**Comment by corneliuze** [comment] 2020-04-18 20:10
Hello @abodea , @Diana-Rus , @ekager , I have reproduced the issue. I will like to work on fixing this bug

**Comment by ekager** [comment] 2020-04-18 20:11
Go for it @corneliuze !

**Comment by corneliuze** [comment] 2020-04-22 19:33
hi, @ekager sent you a message on riot, I cannot add reviewers to my pull request.

**Comment by ekager** [comment] 2020-04-28 05:49
Should be closed by #10258, leaving open for QA

**Comment by sv-sdeiac** [comment] 2020-04-28 07:07
Hi, I can confirm that the issue is fixed using the latest version of Firefox Preview Nightly 4/28 #21190603.

Devices:
- Google Pixel (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG G7 fit (Android 8.1).

**Closed by sv-sdeiac** 2020-04-28 07:07 UTC
Labels: Feature: QRCode, S2, eng:qa:needed, eng:ready, good first issue, help wanted, 🐞 bug
