### ISSUE TITLE
Option to keep toolbars always visible 

### ISSUE THREAD

**Issue by mcosmin222** [mozilla-mobile/fenix#14265] opened 2020-08-27 05:23 UTC
### What is the user problem or growth opportunity you want to see solved?

One of the most annoying features of Android browsers is to collapse the toolbars (address bars and acrion bars) when scrolling the web page. In order to access this from that toolbar, like refresh, find on page, add to favorites or use an extension feature, one has to perform an additional action to scroll up a bit to show the toolbar again. Old Firefox had an option to disable that and keep the toolbars anyways on. For people who use the browser extensively, and not just read stuff on Facebook, the extra action is a huge usability problem. 

### How do you know that this problem exists today? Why is this important?

The option existed before, and had its users. It should contine to exist today. 

### Who will benefit from it?

People who need to access the toolbars on a frequent basis.

**Comment by miDeb** [comment] 2020-08-27 06:12
Duplicate of https://github.com/mozilla-mobile/fenix/issues/10240.

**Comment by kbrosnan** [comment] 2020-08-27 06:18
Closing as a duplicate

**Closed by kbrosnan** 2020-08-27 06:18 UTC
Labels: needs:triage
