### ISSUE TITLE
Open corresponding application for websites like Twitter or YouTube

### ISSUE THREAD

**Issue by czapek1337** [mozilla-mobile/fenix#2600] opened 2019-05-17 09:19 UTC
### Why/User Benefit/User Problem
I'm pretty sure most people with installed applications corresponding to given websites would prefer to for example watch YouTube video in the app and not the mobile version of the website. Some people might not be logged in on the website, but in the app.

### What/Requirements
When navigating, check if any application registered any actions for given URL, if so stop navigating and let the application handle the URL. Otherwise navigate.

### Acceptance Criteria (how do I know when I’m done?)
Try to navigate to the URL: https://youtu.be/dQw4w9WgXcQ
The browser should let you choose whether you want to open YouTube application if installed, or continue with Fenix.

**Comment by raygervais** [comment] 2019-05-17 15:52
I'm a beginner to Android development (have done a few apps, unreleased), but would to help enable this feature. I will be available to start development and learning this within a week (vacation coming up)! Is it possible to get some pointers that I can reference? Ala where to look?

**Comment by pwd-github** [comment] 2019-05-17 15:54
Dupe of #2355 ?

**Comment by yoasif** [comment] 2019-05-17 16:32
This is a dupe of https://github.com/mozilla-mobile/android-components/issues/1132

@raygervais you can ask for information there and the bug has been broken into additional bugs (see comments) if you would like to contribute.

**Comment by vesta0** [comment] 2019-05-21 17:29
Will be addressed by mozilla-mobile/android-components#1132 as @yoasif mentioned :)

**Closed** 2020-08-26 05:56 UTC
Labels: feature request 🌟
