### ISSUE TITLE
Search that ends with a / should check to see if the host is present before preforming a search

### ISSUE THREAD

**Issue by Mossop** [mozilla-mobile/fenix#12641] opened 2020-07-16 17:55 UTC
## Steps to reproduce
On my network I have a hub that can be accessed at `http://hubitat/`. This address is in my history.

1. Open url bar and enter `hubitat`
1. Press enter

### Expected behavior
The website `http://hubitat/` loads.

### Actual behavior
While the top result in the autocomplete results is the correct address the url bar autofills with `hubitat/` and pressing enter searches for that term on google.

<img width="325" src="https://user-images.githubusercontent.com/437326/87705425-b966f700-c752-11ea-82cd-3803cc1027ec.png">

### Device information
* Android device: Moto G7 Android 10
* Fenix version: 7.9.0.0-beta.4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3549)

**Comment by ekager** [comment] 2020-09-09 19:32
Dupe of https://github.com/mozilla-mobile/fenix/issues/13768

**Comment by ekager** [comment] 2020-09-09 19:32
FYI @boek if you want to reassign yourself to https://github.com/mozilla-mobile/fenix/issues/13768 ?

**Comment by chrishamm** [comment] 2022-01-25 09:41
@boek Is there any chance this issue will be ever resolved? A fix doesn't seem terribly difficult to me at first glance.

**Comment by AndrolGenhald** [comment] 2022-11-27 04:25
This has affected me too, I'd like to see it fixed eventually.

**Comment by cpeterso** [comment] 2022-12-27 22:17
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807733

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2022-12-27 22:17 UTC
Labels: 🐞 bug, needs:ac, Feature:Search
