### ISSUE TITLE
[Feature request] Option to use OS share

### ISSUE THREAD

**Issue by FernandoMiguel** [mozilla-mobile/fenix#10214] opened 2020-04-25 13:16 UTC
### Why/User Benefit/User Problem
Nightly uses Firefox own Share menu.
it tries to memorize most recent apps

android OS does a slight better job at guessing which apps users want to share.
not only that the scroll is vertical and has more space.
finding apps on the firefox menu take a lot of time due to so much half screen horizontal scrolling.

if there was a setting/flag to choose between firefox and OS share menu, would be great

**Comment by cadeyrn** [comment] 2020-04-25 14:59
I vote against this proposal for one simple reason: While I understand that some people prefer the Android share menu while others prefer the Fenix share menu I also think that it would be a) an unnecessary waste of ressources to offer both and b) confusing for users to have this option. How would you explain this option to users without using the words "better" and "worse"? In my opinion a settings makes only sense if both options provide their own advantages and if it's not possible to have all advantages in one solution.

I don't know the reasons why Mozilla decided to use an own solution but there were probably reasons for that. So maybe it would be more useful to make suggestions how to improve the used solution?

**Comment by LittleAngelwings** [comment] 2020-04-25 15:57
I'm also in favor with @cadeyrns opinion. Mozilla had decided for his own way. And the goal is fully okay in usability and look.

**Comment by FernandoMiguel** [comment] 2020-04-25 16:11
If we have to choose only one, than follow the OS one for consistency with the entire OS and other apps.
Using a lesser version, a very different ui/ux is a poor choice.

**Comment by s-ankur** [comment] 2020-08-02 09:40
Duplicate of #2819

**Comment by kbrosnan** [comment] 2020-08-27 01:08
Closing as duplicate

**Closed by kbrosnan** 2020-08-27 01:08 UTC
Labels: Feature:ShareSheet, feature request 🌟
