### ISSUE TITLE
FNX-12066 ⁃ [Bug] Items behind the dynamic toolbar cannot be clicked even when made visible by scrolling

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#11189] opened 2020-06-03 13:50 UTC
## Steps to reproduce
1. Go to https://staktrace.github.io/moz-pages/bug/fenix-11189.html
1. Scroll down to reveal the button
1. Click on button

### Expected behavior
JS alert shows text "success"

### Actual behavior
Button never gets clicked

### Device information
* Android device: Sony Xperia XZ1C, Android 9
* Fenix version: Nightly 200602 06:01 (Build #2015743859) 44.0.20200531130125, 2ac91e358 GV: 78.0a1-20200529095426 AS: 0.59.0

**Comment by hwinnemoe** [comment] 2020-06-03 14:13
Sound like a possible duplicate of or related to #10720

**Comment by ekager** [comment] 2020-06-03 14:59
cc @Mugurell @sblatz does anyone know if there are already tracked tickets for this / a GV ticket? Seems like a recent regression we should definitely be looking into

**Comment by theres-waldo** [comment] 2020-06-04 00:20
This regressed between the May 10 and May 11 Fenix nightlies, and it's related to hit testing, leading me to suspect it's a regression from [bug 1556556](https://bugzilla.mozilla.org/show_bug.cgi?id=1556556).

**Comment by ekager** [comment] 2020-06-04 01:23
@theres-waldo thanks for the info :) do you want me to file a new Bugzilla for this then?

**Comment by theres-waldo** [comment] 2020-06-04 01:34
@ekager Please do -- thanks!

**Comment by ekager** [comment] 2020-06-04 01:36
Filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1643212

**Comment by astarq** [comment] 2020-06-04 17:22
A bit late, but on scrolling to the bottom of the reddit.com homepage, clicking next either opens the post nearest to the button or does nothing - sorry if this is a Reddit issue, I haven't used it before

**Comment by Better-hack** [comment] 2020-06-07 04:52
The topic is closed. The bug remained

**Comment by hiikezoe** [comment] 2020-06-07 22:26
@Better-hack that's because the build including the fix hasn't yet published on Google Play Store.

**Comment by Augures01** [comment] 2020-06-08 06:20
Can confirm as fixed in latest Nightly 200608 06:00

**Comment by Better-hack** [comment] 2020-06-08 10:09
99% fixed. 1% remained. Attach the link. There is no response if the button rests at the very bottom. There is a response when just above the bottom and when only half extended. Very strange.

https://drive.google.com/file/d/1KCBck6ynloLFKfXsT2MyWQ3d3F2XMiMa/view?usp=sharing

**Comment by Augures01** [comment] 2020-06-08 10:56
> 
> 
> 99% fixed. 1% remained. Attach the link. There is no response if the button rests at the very bottom. There is a response when just above the bottom and when only half extended. Very strange.
> 
> https://drive.google.com/file/d/1KCBck6ynloLFKfXsT2MyWQ3d3F2XMiMa/view?usp=sharing

Can reproduce when
1. Open https://m.vk.com/like?act=members&object=wall-22822305_1097944
2. Go to bottom
3. Click on "likes" page number (2-3, for example)
4. Click on another page number (but not last page)
No response, until you interact with page (scroll page)

**Comment by Better-hack** [comment] 2020-06-08 11:22
> > 99% fixed. 1% remained. Attach the link. There is no response if the button rests at the very bottom. There is a response when just above the bottom and when only half extended. Very strange.
> > https://drive.google.com/file/d/1KCBck6ynloLFKfXsT2MyWQ3d3F2XMiMa/view?usp=sharing
> 
> Can reproduce when
> 
> 1. Open https://m.vk.com/like?act=members&object=wall-22822305_1097944
> 2. Go to bottom
> 3. Click on "likes" page number (2-3, for example)
> 4. Click on another page number (but not last page)
>    No response, until you interact with page (scroll page)

The problem is a little different. But I think they have a common source of problems. I was able to reproduce.
https://drive.google.com/file/d/1Kh3651lZUkGigQuXRxuPo-aQV5oaZkyo/view?usp=sharing

**Comment by ekager** [comment] 2020-06-08 22:18
cc @theres-waldo what do you think about the above comments? Do you think that's also related?

**Comment by theres-waldo** [comment] 2020-06-08 22:39
It's possible. It would be useful to know if the issue can be reproduced in the May 10 Fenix nightly. If so, it's a pre-existing issue and likely unrelated.

**Comment by Augures01** [comment] 2020-06-09 02:15
> Can reproduce when
> 
>     1. Open https://m.vk.com/like?act=members&object=wall-22822305_1097944
> 
>     2. Go to bottom
> 
>     3. Click on "likes" page number (2-3, for example)
> 
>     4. Click on another page number (but not last page)
>        No response, until you interact with page (scroll page)

@theres-waldo 
Can reproduce on "may 10" build
So, it's other bug then

**Comment by hiikezoe** [comment] 2020-06-09 02:59
It's worth opening a new issue for the case.
One thing I realized is that on Fenix when the step 4 is done, the scroll positions keeps at the bottom, whereas on Chrome it's reset to the top for some reasons.

**Comment by Better-hack** [comment] 2020-06-09 03:46
> Стоит открыть новый выпуск для дела.
> Я понял одну вещь: в Fenix ​​после выполнения шага 4 позиция прокрутки остается внизу, а в Chrome по некоторым причинам она сбрасывается в верхнюю часть.

When submit as a new BUG, leave a comment in this thread with a link to a new BUG, so that we can track

**Comment by Augures01** [comment] 2020-06-09 04:11
> 
> 
> > Can reproduce when
> > ```
> > 1. Open https://m.vk.com/like?act=members&object=wall-22822305_1097944
> > 
> > 2. Go to bottom
> > 
> > 3. Click on "likes" page number (2-3, for example)
> > 
> > 4. Click on another page number (but not last page)
> >    No response, until you interact with page (scroll page)
> > ```
> 
> @theres-waldo
> Can reproduce on "may 10" build
> So, it's other bug then
> 
> upd. Old FF for Android affected too ☹

Looks like it's site-related issue
Sometimes it resets to the top, sometimes stucks until interaction
Can reproduce on Chrome (and Samsung Browser)/old Firefox/Fenix

**Comment by Better-hack** [comment] 2020-06-09 07:10
> > > Can reproduce when
> > > ```
> > > 1. Open https://m.vk.com/like?act=members&object=wall-22822305_1097944
> > > 
> > > 2. Go to bottom
> > > 
> > > 3. Click on "likes" page number (2-3, for example)
> > > 
> > > 4. Click on another page number (but not last page)
> > >    No response, until you interact with page (scroll page)
> > > ```
> > 
> > 
> > @theres-waldo
> > Can reproduce on "may 10" build
> > So, it's other bug then
> > upd. Old FF for Android affected too ☹
> 
> Looks like it's site-related issue
> Sometimes it resets to the top, sometimes stucks until interaction
> Can reproduce on Chrome (and Samsung Browser)/old Firefox/Fenix

I could not reproduce the problem in chrome

**Comment by Augures01** [comment] 2020-06-09 07:35
> I could not reproduce the problem in chrome
Me too for now 🤔
I'll open new issue later

**Comment by ekager** [comment] 2020-06-09 21:59
Closing because we opened a new issue for #11356

**Closed** 2020-08-11 03:22 UTC
Labels: Feature:Toolbar, needs:gecko, 🐞 bug
