### ISSUE TITLE
Enable WebAuth with Google Services on Firefox beta

### ISSUE THREAD

**Issue by mhalano** [mozilla-mobile/fenix#19612] opened 2021-05-22 21:36 UTC
Firefox nightly has support for Webauthn (using Google Services) usable for a quite long time now. The idea is enable for Firefox Beta too, except if someone has any strong motive to not do it.

**Comment by jonalmeida** [comment] 2021-06-02 23:27
Duplicate of https://github.com/mozilla-mobile/fenix/issues/19785

**Closed by jonalmeida** 2021-06-02 23:27 UTC
Labels: needs:triage
