### ISSUE TITLE
FNX-5048 ⁃ [Bug] Crash on opening homescreen

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#1465] opened 2019-04-08 16:59 UTC
## Steps to reproduce
1. Open webpage through other app by setting fenix as default browsing app.
1. Immediately click the tab button as it starts loading.
    1. Expected behavior
The homescreen open and you can see the tabs.
    1. Actual behavior
The app crash and the crash reporter displays.
(It happens most of the time this is the only steps which can reproduce the behaviour reliably) 
    1. Device information

* Android device: 8.0.0
* Fenix version: 1.0.1915 (Build #10981205
68.0a1-20190403060632)
Monday 4/8 @ 12:05 PM
    1. Screenshot
![Screenshot](https://user-images.githubusercontent.com/42364681/55742753-f9074500-5a1f-11e9-9c0b-f172c9b77499.png)UNITO-UNDERSCORE!20190408-213536!

**Comment by Scripterr** [comment] 2019-04-08 17:06
This issue started after the session and tab components both merged in the PR #1446 .

**Comment by ekager** [comment] 2019-04-08 17:29
>  10:07:11.982 9517-9517/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: org.mozilla.fenix.debug, PID: 9517
>     java.lang.IllegalArgumentException: navigation destination org.mozilla.fenix.debug:id/action_browserFragment_to_homeFragment is unknown to this NavController
>         at androidx.navigation.NavController.navigate(NavController.java:816)
>         at androidx.navigation.NavController.navigate(NavController.java:757)
>         at androidx.navigation.NavController.navigate(NavController.java:743)
>         at androidx.navigation.NavController.navigate(NavController.java:875)
>         at org.mozilla.fenix.components.toolbar.ToolbarIntegration$$special$$inlined$run$lambda$1.invoke(ToolbarIntegration.kt:44)
>         at org.mozilla.fenix.components.toolbar.ToolbarIntegration$$special$$inlined$run$lambda$1.invoke(ToolbarIntegration.kt:20)
>         at org.mozilla.fenix.components.toolbar.TabCounterToolbarButton$createView$$inlined$apply$lambda$1.onClick(TabCounterToolbarButton.kt:41)
>         at android.view.View.performClick(View.java:6597)
>         at android.view.View.performClickInternal(View.java:6574)
>         at android.view.View.access$3100(View.java:778)
>         at android.view.View$PerformClick.run(View.java:25885)
>         at android.os.Handler.handleCallback(Handler.java:873)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.app.ActivityThread.main(ActivityThread.java:6718)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ekager** [comment] 2019-04-08 18:08
Thanks for the report! I am able to reproduce and I don't think it is related to #1446 as I can repro on older branches as well. 

This happens when Fenix is not open in the background and you send a link to open in Fenix and then try to click the tabs icon.

**Comment by cadeyrn** [comment] 2019-04-08 20:07
Duplicate of #1406.

**Comment by ekager** [comment] 2019-04-08 22:43
Closing as a dupe of #1406 for QA purposes

**Comment by Scripterr** [comment] 2019-04-09 16:16
I'm still experiencing the crash but now it's random as it doesn't depends on the progress bar status i don't have concrete steps but i have 2 crashes related to this after updating to the latest build.

**Closed** 2020-08-11 11:43 UTC
Labels: b:crash
