### ISSUE TITLE
[Bug]: Private tab in reader-mode is forcibly unloaded with no network access

### ISSUE THREAD

**Issue by issue-dispenser** [mozilla-mobile/fenix#25754] opened 2022-06-24 23:44 UTC
### Steps to reproduce

1. Open reader-capable page in a private tab
2. Enter reader-mode in the tab
3. Turn on airplane mode (or disable all forms of internet access)
4. Leave the tab via the tab menu
5. Enter the tab via the tab menu

### Expected behaviour

The page should still be in reader-mode with no content change.

### Actual behaviour

The page is unloaded and Fenix appears to have attempted to reload it, as the content is replaced with the following:

"No internet connection
Check your network connection or try reloading the page in a few moments."

### Device name

Samsung Galaxy S7

### Android version

Android 8.0

### Firefox release type

Firefox Nightly

### Firefox version

103.0a1 2022-06-23

### Additional information

For some reason, this only occurs when there is no network access. With network access, there doesn't appear to be any attempt to unload/refresh the tab.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20807)

**Comment by kbrosnan** [comment] 2022-07-15 04:59
This sounds like we got killed in the background. Which makes this a duplicate of https://github.com/mozilla-mobile/fenix/issues/18933

**Closed by kbrosnan** 2022-07-15 04:59 UTC
Labels: 🐞 bug, Feature:PrivateBrowsing, Feature:ReaderMode, needs:triage, qa-triaged
