### ISSUE TITLE
FNX-5101 ⁃ [Bug] RaptorRelease signing is failing with exception 'runtime task doesn\'t match any rebuilt definition'

### ISSUE THREAD

**Issue by ncalexan** [mozilla-mobile/fenix#1565] opened 2019-04-11 17:52 UTC
Pushes to master appear to be failing, see https://tools.taskcluster.net/groups/B_ScD6xmSzeHdH808vTJDw/tasks/byKyRrzJRLmk92luPsKLXA/runs/0/logs/public%2Flogs%2Fchain_of_trust.log:

```
scriptworker.exceptions.CoTError: 'signing:parent B_ScD6xmSzeHdH808vTJDw: the runtime task doesn\'t match any rebuilt definition!\n["[(\'change\', \'payload.env.MOBILE_TRIGGERED_BY\', (\'ekager\', \'boek\')),\\n"\n " (\'change\',\\n"\n "  \'metadata.owner\',\\n"\n "  (\'ekager@users.noreply.github.com\', \'boek@users.noreply.github.com\'))]"]'
```

These tasks were green just before, in my push to fix bustage for #1321, at https://tools.taskcluster.net/task-group-inspector/#/QditNdvfQfG97sSgvoCxLQ.

**Comment by ncalexan** [comment] 2019-04-11 17:52
@mitchhentges @JohanLorenzo can you dig into this?  No bueno.

**Comment by mitchhentges** [comment] 2019-04-11 17:58
This may be related to [this](https://github.com/mozilla-mobile/reference-browser/pull/716)

**Comment by JohanLorenzo** [comment] 2019-04-12 08:49
https://tools.taskcluster.net/groups/B_ScD6xmSzeHdH808vTJDw/tasks/B_ScD6xmSzeHdH808vTJDw/runs/0 was created before the fix got in. Yesterday, I [marked these failures](https://treeherder.mozilla.org/#/jobs?repo=fenix&revision=dad4149b813e26dbb646988e5681df58962389c5&selectedJob=239548937) and linked them to the issue Mitch called out.

Moreover, I see [this PR](https://github.com/mozilla-mobile/fenix/pull/1559) was merged by a different person, after the scriptworker patch was deployed and no [Chain of Trust issue came up](https://treeherder.mozilla.org/#/jobs?repo=fenix&revision=070b7a397d31d81a1078a6ead024f184480f149c).


Therefore, I think we can close this issue as being a dupe of https://github.com/mozilla-releng/scriptworker/issues/326

**Closed** 2020-08-11 12:09 UTC
Labels: eng:release, 🐞 bug
