### ISSUE TITLE
[Bug] Adding to a collection closes the tab

### ISSUE THREAD

**Issue by thewhitetulip** [mozilla-mobile/fenix#4987] opened 2019-08-28 12:21 UTC
## Steps to reproduce

Open a site in new tab and add it to collection

### Expected behavior
Should not close current tab, just add it to collection

### Actual behavior

Adds to collection and closes tab

### Device information

* Android device: ?
* Fenix version: ?

**Comment by boek** [comment] 2019-12-28 04:27
This is working as intended.

**Comment by thewhitetulip** [comment] 2019-12-31 06:11
It should not work like this. user might want to read the article, they first think 'lets add it to collections so that we don't miss this link' and when we add it to collections, poof, the tab is gone and we have to open the tab again.

**Comment by vesta0** [comment] 2020-01-21 18:50
@brampitoyo please take a look and advise as to the correct behaviour that matches user expectation most closely.

**Comment by brampitoyo** [comment] 2020-03-16 04:16
@thewhitetulip As far as I’m aware: after a tab is added to a collection, it’s not closed. Would you be able to confirm this behaviour using the latest Firefox Preview Nightly?

If confirmed, this is no longer a bug, and we can close this issue.

**Comment by topotropic** [comment] 2020-03-16 12:04
Tabs still get closed when you add them to a Collection. 
I agree with @thewhitetulip here that it makes sense to leave them open and let users close them once they are done with them.

**Comment by sflorean** [comment] 2020-03-30 11:02
Verified as fixed on Nightly build 200330 - 3/30. The tabs are not closed after they are being added to a collection.
Devices: Nokia 6 (Android 7.1.1), Xiaomi Mi Pad 2 (Android 5.1), Samsung Galaxy Note 10 (Android 10).

**Closed by sflorean** 2020-03-30 11:02 UTC
Labels: Feature:Collections, eng:qa:needed, eng:ready, 🐞 bug
