### ISSUE TITLE
[Bug] "Zoom on all websites" not working.

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#6658] opened 2019-11-18 04:12 UTC
## Steps to reproduce

1. Set general.useragent.override to desktop version as "Mozilla/5.0 (X11; Linux x86_64:72.0) Gecko/20100101 Firefox/72.0" in about:config.
2. Check "Zoom on all websites" enable.
3. Force stop Fenix Nightly.
4. Open https://mbd.baidu.com/newspage/data/landingsuper?context=%7B%22nid%22%3A%22news_9488899134225353999%22%7D&n_type=0&p_from=1
5. Zoom not working. if disable then enable "Zoom on all websites", it works. But force stop Fenix Nightly again, Zoom still not working.

### Expected behavior

Can Zoom.

### Actual behavior

Can't Zoom.

### Device information

* Android device: ?
* Fenix version: 72.0a1-20191115095319

**Comment by sv-ohorvath** [comment] 2019-11-18 10:04
Dupe of #2477.

**Closed by sv-ohorvath** 2019-11-18 10:04 UTC
Labels: 🐞 bug
