### ISSUE TITLE
[Bug]: Tabs view always scrolled the top

### ISSUE THREAD

**Issue by noscript** [mozilla-mobile/fenix#22933] opened 2021-12-21 09:58 UTC
### Steps to reproduce

1. Open as many tabs as needed, so they don't fit on the screen and the view becomes scrollable.
2. Open a new tab.
3. Go to the tabs view.

### Expected behaviour

The view is scrolled down, so the current tab is visible.

### Actual behaviour

The view is scrolled to the beginning. Every single time the user has to scroll down to find the current tab.

### Android version

11

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1

**Comment by marcel263** [comment] 2021-12-21 10:49
Appearing as duplicate of #19231

**Comment by noscript** [comment] 2021-12-21 10:57
> Appearing as duplicate of #19231

Not necessarily. This issue is more general, while #19231 emphasizes that the problem happens only when switching between normal & incognito modes.

**Comment by marcel263** [comment] 2021-12-21 11:14
#22929 also mentions scrolling. 

temporary fix seems to be disabling tab groups

**Comment by noscript** [comment] 2021-12-21 11:18
> temporary fix seems to be disabling tab groups

Thank you, that fixes the scrolling problem.

**Comment by SoftVision-LorandJanos** [comment] 2021-12-23 10:58
Hi @noscript . Thank you for your report!
I can reproduce the issue you described.
I think the fix for the above mentioned [ticket](https://github.com/mozilla-mobile/fenix/issues/19231) should cover this one, so I will close this one as a duplicate.
If the fix for the ticket mentioned won't fix this one, this can be reopened or a new one filed. Thank you!
Tested on the latest Nightly 97.0a1.
Device used: Xiaomi Mi11 Lite (Android 11).

**Closed by SoftVision-LorandJanos** 2021-12-23 10:58 UTC
Labels: 🐞 bug, needs:triage
