### ISSUE TITLE
FNX-5548 ⁃ Support for custom searches

### ISSUE THREAD

**Issue by bjo81** [mozilla-mobile/fenix#2257] opened 2019-05-03 10:15 UTC
### Why
Users would like to use e.g. searx instances like they did with firefox.

### What
Atm Fenix has no "add search engine" icon. Adding https://searxinstance/opensearch.xml works somehow, as Fenix states "already exists" when trying to add it again, but it does not appear in the search engines overview.

**Comment by maverick74** [comment] 2019-05-10 17:30
duplicate of #1437  ?

**Comment by kbrosnan** [comment] 2019-05-10 17:35
Yes. Thank you.

**Closed** 2020-08-11 14:34 UTC
Labels: P3, feature request 🌟
