### ISSUE TITLE
[Bug]: 3 dot menu icons in Bookmarks are displayed as close ("X") icons

### ISSUE THREAD

**Issue by czlucius** [mozilla-mobile/fenix#26093] opened 2022-07-19 09:33 UTC
### Steps to reproduce

1. Open the bookmarks menu

### Expected behaviour

Each element should have a 3 dot menu at its right

### Actual behaviour

The elements have a "x" icon which implements the same functionality as the 3 dot menu. As there are other options other than clearing items in the bookmarks (e.g. Share), this would confuse users.

### Device name

Samsung Galaxy S20 FE 5G 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

104.0a1 (Build #2015892963), e9de331b0+ AC: 104.0.20220718174753, 8c96b863dc GV: 104.0a1-20220718132938 AS: 93.6.0

### Additional information

![Screenshot_20220719-120507_Firefox Nightly](https://user-images.githubusercontent.com/58442255/179718350-a942884d-820f-4045-a604-ef13673703f9.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21057)

**Comment by SoftVision-LorandJanos** [comment] 2022-07-20 05:16
Hi @czlucius ! Thanks for your report!
I will modify this to a feature request as this is an intended behavior at the moment.

**Comment by Mugurell** [comment] 2022-07-20 11:05
There is no issue for history. The "x" button will delete a single history entry. 
More options are available for history items if long pressing on them.

There is a recent regression though for bookmarks from https://github.com/mozilla-mobile/fenix/issues/25937.
For technical notes: happens because the [layout used for bookmarks](https://github.com/mozilla-mobile/fenix/blob/05e6ba40b4bba2179e775a2e2b380095ee999910/app/src/main/java/org/mozilla/fenix/library/bookmarks/viewholders/BookmarkNodeViewHolder.kt#L112) will [show a LibrarySiteItemView](https://github.com/mozilla-mobile/fenix/blob/05e6ba40b4bba2179e775a2e2b380095ee999910/app/src/main/res/layout/bookmark_list_item.xml#L5) which was recently updated to [show that "X" image](https://github.com/mozilla-mobile/fenix/blob/3111c8bf8b0c8e1a646b1860608b946317505a78/app/src/main/res/layout/library_site_item.xml#L82) for the "overflow_menu".

**Comment by SoftVision-LorandJanos** [comment] 2022-07-20 12:35
As mentioned above, there was no issue with history, the described issue is only on bookmarks, and I was able to reproduce it on the latest Nightly 104.0a1 (2022-07-20) build. The 3 dot menu is replaced by the "X" with the context menu function.
Device used: Google Pixel 4 (Android 12).
I edited the details of the issue to be clear it's only about bookmarks.
I will switch back the feature request label to the bug label. Thank you!

**Comment by LaurentiuApahideanSV** [comment] 2022-08-23 09:14
The issue also occurs on Firefox Beta 105.0b1.
### Device used:
- Huawei MediaPad M3 (Android 7)
- OnePlus 6T (Android 9)

**Comment by DavidJCobb** [comment] 2022-08-26 22:37
Just got this issue on the release build. I don't recall it being a problem before, so I guess this bug just made it through to ship with no one stopping it -- and this'll be affecting a lot more people now.

> For technical notes: happens because the layout used for bookmarks will show a LibrarySiteItemView which was recently updated to show that "X" image for the "overflow_menu".

Does this mean that the Fenix team are updating UI views without even knowing what uses them?

**Comment by czlucius** [comment] 2022-08-30 04:05
> There is no issue for history. The "x" button will delete a single history entry. More options are available for history items if long pressing on them.
> 
> This is a recent regression from the for bookmarks from #25937. For technical notes: happens because the [layout used for bookmarks](https://github.com/mozilla-mobile/fenix/blob/05e6ba40b4bba2179e775a2e2b380095ee999910/app/src/main/java/org/mozilla/fenix/library/bookmarks/viewholders/BookmarkNodeViewHolder.kt#L112) will [show a LibrarySiteItemView](https://github.com/mozilla-mobile/fenix/blob/05e6ba40b4bba2179e775a2e2b380095ee999910/app/src/main/res/layout/bookmark_list_item.xml#L5) which was recently updated to [show that "X" image](https://github.com/mozilla-mobile/fenix/blob/3111c8bf8b0c8e1a646b1860608b946317505a78/app/src/main/res/layout/library_site_item.xml#L82) for the "overflow_menu".

@Mugurell 
It seems that HistoryListItemViewHolder already overrides the default 3 dot icon with a close icon.
https://github.com/mozilla-mobile/fenix/blob/6ad87373ffb1032a4b36de86b6d8b1b70fce8d3e/app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt#L37
Hence, `ic_close` is not needed in `library_site_item.xml`, and it can use `ic_menu` to ensure that the bookmark menu (or any other menu that uses the `LibrarySiteItemView` will have a 3 dot icon instead of a close icon.

**Comment by czlucius** [comment] 2022-08-30 04:06
I shall make a PR on this.

**Comment by czlucius** [comment] 2022-08-30 04:15
The attached PR solves the issue, and allows History to keep its close icon.

**Comment by SoftVision-LorandJanos** [comment] 2022-08-31 04:30
Verified as fixed on the latest Nightly 106.0a1 (2022-08-30T17:07:53.356749) build.
Deice used: Oppo Find X5 (Android 12).
Closing the ticket as verified.

**Closed by SoftVision-LorandJanos** 2022-08-31 04:30 UTC
Labels: 🐞 bug, Feature:History, eng:qa:needed, Feature:Bookmarks, needs:triage, qa-triaged
