### ISSUE TITLE
[Bug] URL is not overridden by new input but gets appended on

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#8502] opened 2020-02-18 19:22 UTC
> https://bugzilla.mozilla.org/show_bug.cgi?id=1615795

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:73.0) Gecko/20100101 Firefox/73.0

Steps to reproduce:

Firefox for Android Nightly: 200215
GV: 75.0a1-20200214100511

1. Click inside the adress bar at the bottom with the goal to enter a new url.
2. Keyboard opens and url is selected
3. Start inputting the new url

Actual results:

The input gets appended to the old url which was selected.

Expected results:

When text is selected it should be deleted on new input.

**Comment by henningBunk** [comment] 2020-02-18 19:47
captured a small video of it: 
https://youtu.be/QizJAQc2gxA

if you look closely not only the url is selected in gray but also the last two letters (r/) in purple. is this a feature to switch the path quickly?

**Comment by softvision-miralobontiu** [comment] 2020-11-18 13:25
I'm not able to reproduce this anymore. On the 11/18 Nightly build, when the text from the URL bar is selected it is deleted by the new input.
Tested with Samsung Galaxy Tab S6 (Android 10), and Xiaomi mi4i (Android 5.0.2).
I'll close this issue.

**Closed by softvision-miralobontiu** 2020-11-18 13:25 UTC
Labels: Feature:Search, needs:triage, 🐞 bug
