### ISSUE TITLE
FNX-4370 ⁃ New tab tray should center on selected tab

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#10547] opened 2020-05-10 19:54 UTC
### Why/User Benefit/User Problem
When opening the new tab tray, it always show the first tab. It would be better to show the selected tab.

**Comment by cadeyrn** [comment] 2020-05-11 06:16
Duplicate of #10496.

**Comment by mcarare** [comment] 2020-05-11 07:27
Closing as duplicate of #10496.

**Closed** 2020-08-11 01:00 UTC
Labels: needs:triage
