### ISSUE TITLE
[Bug] no shield icon using web archives - search by image

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#15451] opened 2020-09-26 12:00 UTC
## Steps to reproduce
1. Install search by image or web archive
2. Use it (reverse search an image or search archive for a web page)
### Expected behavior
The new tab it just opened have the shield icon
### Actual behavior
The shield icon is not visible
### Device information

* Android device: Pocophone F1
* Fenix version: Nightly 200926 06:03

<img src="https://i.ibb.co/FJbNnXz/Screenshot-20200926-135916-Firefox-Nightly.png">

Ping @dessant, the developper of these addons. You may be interested to follow this issue or maybe help

**Comment by s-ankur** [comment] 2020-09-26 20:58
Duplicate of https://github.com/mozilla-mobile/fenix/issues/14271

**Comment by softvision-miralobontiu** [comment] 2020-10-01 12:05
Closing this as dupe of #12848.

**Closed by softvision-miralobontiu** 2020-10-01 12:05 UTC
Labels: needs:triage
