### ISSUE TITLE
[Bug] Error messages affected by fx-fenix_error_* in tab title

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#14620] opened 2020-09-02 15:20 UTC
## Steps to reproduce
1. Go to https://demo.cyotek.com/features/redirectloop.php
2. Tap on "Test" button.
3. Tap on the tabs tray and inspect tab title for the tab with error.

### Expected behavior
Tab title displays: The page isn't redirecting properly.
### Actual behavior
Tab title displays: fx-fenix_error_9
### Device information

* Android device: Google Pixel 3XL (Android 9)
* Fenix version: Firefox Preview Beta 81.1.0

Notes:
It reproduces for all error messages:
- No internet connection - fx-fenix_error_3 (removing wi-fi access or mobile data)
- Unable to connect - fx-fenix_error_4 (tessline.com)

Similar error massages for which the page title has the same format: 
- #14517 -> "Address Not Found"- fx-fenix_error_4
- #14610 -> Secure connection Failed error page - fx-fenix_error_5

**Comment by ekager** [comment] 2020-09-02 15:26
Likely related to https://github.com/mozilla-mobile/android-components/issues/8315

**Comment by jonalmeida** [comment] 2020-09-11 00:53
@Diana-Rus could you re-test this? I'm no longer able to reproduce this so I have a suspicion it was fixed as a side-effect of another change, but I don't know how.

**Comment by sflorean** [comment] 2020-09-16 11:50
@jonalmeida Tested on the latest Nightly, Beta and Release builds and I'm unable to reproduce the issue, following the steps provided or closing the wifi, with Google Pixel 3 (Android 11).

@s-ankur since you filed the same issue, could you please check on your device if the issue is still reproducible? Thank you!

**Comment by s-ankur** [comment] 2020-09-16 14:14
Cannot reproduce on my device! Although I think @gcp should also test it since it was their issue originally

**Comment by gcp** [comment] 2020-09-16 14:48
Haven't noticed this recently, WORKSFORME.

**Comment by jonalmeida** [comment] 2020-09-17 04:42
Thanks folks!

**Closed by jonalmeida** 2020-09-17 04:42 UTC
Labels: Feature:ErrorMessages, S2, eng:qa:verified, 🐞 bug
