### ISSUE TITLE
[Experiment] The MR onboarding is displayed for the Control and Treatment B branches for new users

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/fenix#26958] opened 2022-09-13 14:07 UTC
**[Affected Versions]:**
- Firefox Nightly 106.0a1 (Build #2015903787), 67ba299f7+, AC: 106.0.20220912143111, 54c57f88d7, GV: 106.0a1-20220912094615, AS: 94.1.0

**[Affected Platforms]:**
- Android 9 - Samsung Galaxy S8

**[Prerequisites]:**
- Have a Firefox build set to have the [[QA] Firefox Android Nightly MR New User Onboarding](https://experimenter.services.mozilla.com/nimbus/qa-firefox-android-nightly-mr-new-user-onboarding/details#recipe-json) recipe added to the main initial_experiments.json file.
- Have a way to observe logcat.

**[Steps to reproduce]:**
1. Open Firefox with a [telemetry command](https://mozilla.github.io/glean/book/user/debugging/android.html) and observe events to make sure you are enrolled into the Control or Treatment B branch.
2. Observe the Onboarding.

**[Expected result]:**
- The non-MR Onboarding is displayed.

**[Actual result]:**
- The MR onboarding is displayed.

**[Notes]:**
- The issue is not reproducible for the existing users version, which is not displayed for the Control and Treatment B branches of that [experiment](https://experimenter.services.mozilla.com/nimbus/qa-firefox-android-nightly-mr-existing-user-onboarding). 
- Attached is a recording of the issue.

![control onb](https://user-images.githubusercontent.com/53752296/189919354-2e5a7295-2466-4594-8a4b-59e3c4507796.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21556)

**Comment by Amejia481** [comment] 2022-09-13 21:19
Thanks for the information @heres-maria !

1. Would you mind sharing which version on Fenix are you building locally (Nightly, Beta, Release or debug)?
2. Could you share the `initial_experiments.json` file that you are using for testing? And in which path it's located as we have two at the moment.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/773158/189967659-af222a93-1a71-4d7e-ae97-ea1a6acbfbba.png">


Looking at the [json recipe](https://experimenter.services.mozilla.com/nimbus/qa-firefox-android-nightly-mr-new-user-onboarding/details#recipe-json), it looks like both should not show, based on what the branch indicate to do ("`home-onboarding-dialog-new-users": false)`.


### Treatment b
```json
        {
          "feature": {
            "enabled": true,
            "featureId": "mr2022",
            "value": {
              "sections-enabled": {
                "home-onboarding-dialog-existing-users": false,
                "home-onboarding-dialog-new-users": false,
                "jump-back-in-cfr": false,
                "sync-cfr": false,
                "tcp-cfr": true,
                "wallpapers-selection-tool": false
              }
            }
          },
          "ratio": 1,
          "slug": "treatment-b"
        }
```

### Control branch
 ```json
     {
          "feature": {
            "enabled": true,
            "featureId": "mr2022",
            "value": {
              "sections-enabled": {
                "home-onboarding-dialog-existing-users": false,
                "home-onboarding-dialog-new-users": false,
                "jump-back-in-cfr": false,
                "sync-cfr": false,
                "tcp-cfr": false,
                "wallpapers-selection-tool": false
              }
            }
          },
          "ratio": 1,
          "slug": "control"
        }
```

**Comment by gabrielluong** [comment] 2022-09-13 22:37
We explicitly removed the Nimbus flag for the first run onboarding for the new users. All users will just see the new designs for the first run onboarding since it did not make sense to nimbus flag the old vs new design since there were no new telemetry to measure.

**Comment by heres-maria** [comment] 2022-09-14 08:34
- The build used is Nightly built from main, with 
```
nimbus.remote-settings.url = https://firefox.settings.services.mozilla.com
debuggable = true
``` 
set in local.properties and a new ".nimbus" file created in the main project file (.../fenix/.nimbus, where local.properties is also located) containing the ```https://firefox.settings.services.mozilla.com``` line.
- This is [the initial_experiments.json](https://drive.google.com/file/d/1OvnsIm_R6O9WkgX8XDOw7N4OnTebbd39/view?usp=sharing) file I am using and it is the one at ".../app/src/main/res/raw/initial_experiments.json". I have not modified the other one.

- Related to the onboarding itself, I will refer the experiment owner, @athomasmoz, for the expected behavior of the onboarding of new users, as I am unfamiliar with the details of that [change](https://github.com/mozilla-mobile/fenix/issues/26958#issuecomment-1246016872). Should users in the Control and Treatment B branches of the holdback study also see the updated onboarding?

**Comment by shell1** [comment] 2022-09-15 16:46
@cpeterson is checking with @gabrielluong - to see if there was a misunderstanding about the Nimbus flag needing to be checked.  The features are shipping default on - but believe it's the Nimbus flag that needs to respected for the users put in the hold-back experiment.

**Comment by shell1** [comment] 2022-09-15 20:09
tagging @kbrosnan  as well

**Comment by cpeterso** [comment] 2022-09-15 21:04
@gabrielluong and @dnarcese confirmed that this is the expected behavior on Android, so we can close this bug.

* New users in any branch (Control, Treatment A, or Treatment B) should be taken directly to the familiar new user onboarding screen:

![image](https://user-images.githubusercontent.com/629193/190508321-f62a78c2-f7bf-4962-b190-e0939ab0a469.png)

* New users will NOT see the following MR onboarding screens. They will ONLY be shown to existing users upgrading to v106.

![image](https://user-images.githubusercontent.com/629193/190508035-90aae3d1-a06a-4e2c-85da-44785664f05d.png) 
![image](https://user-images.githubusercontent.com/629193/190508066-cee2f7c6-ea65-4e13-8d6b-c9831f4d5b9d.png)

**Comment by heres-maria** [comment] 2022-09-23 06:39
I am reopening this ticket as I saw a Slack discussion that made me think there was a misunderstanding regarding the actual and expected behavior of this issue. I am attaching a screenshot of the differences between the onboarding in 106 ("MR") and the onboarding from version 105. The incorrect behavior observed was that the onboarding from 106 was displayed in the Control and Treatment B branches instead of the one from 105.
![new users onboarding](https://user-images.githubusercontent.com/53752296/191904668-e31ec052-aaba-44b9-9015-fb5cff802564.png)

**Comment by heres-maria** [comment] 2022-09-28 13:43
Based on further discussion with @gabrielluong, the behavior described was expected. As a result, I will close this issue and mark it as won't fix.

**Comment by heres-maria** [comment] 2022-10-12 12:18
I am reopening this issue based on [this comment](https://mozilla-hub.atlassian.net/browse/QA-1597?focusedCommentId=599253).

**Comment by cpeterso** [comment] 2022-10-13 19:01
After talking with Kevin and gl, I think this is the expected behavior so I'll close this issue.

**Closed by cpeterso** 2022-10-13 19:01 UTC
Labels: 🐞 bug, S2, needs:triage
