### ISSUE TITLE
[Sync] Can't sync logins, history, can't un-sync bookmarks

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#9103] opened 2020-03-11 16:01 UTC
1. Log into your Firefox account on Fenix
2. Go to Settings -> Sync
3. Tap on checkboxes for logins, history and bookmarks 

Expected:
Items are checked/unchecked when you tap

Actual:
You can't check/uncheck items

See video
https://cl.ly/f3b7c76b1546

**Comment by ekager** [comment] 2020-03-11 17:21
Dupe of #9027

**Closed by ekager** 2020-03-11 17:21 UTC
Labels: Feature:Sync, implementation review, needs:triage, 🐞 bug
