### ISSUE TITLE
enable extension "redirect amp to html"

### ISSUE THREAD

**Issue by tortino** [mozilla-mobile/fenix#14240] opened 2020-08-26 19:40 UTC
### What is the user problem or growth opportunity you want to see solved?
I don't want to see Gogole AMP pages, so please enable the Firefox extension "Redirect AMP to HTML" by Aleksandersen.
Thanks.

**Comment by amkcpu** [comment] 2020-08-26 19:48
Duplicate of #13058

**Comment by kbrosnan** [comment] 2020-08-26 19:50
Closing as dupe. See also #11308

**Closed by kbrosnan** 2020-08-26 19:50 UTC
Labels: needs:triage
