### ISSUE TITLE
Address bar autocomplete regression

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#20564] opened 2021-07-29 07:27 UTC
### Steps to reproduce

1. On my nightly, write "bugz" on the address bar.
2. See how autocomplete recommends the least used of the bugzilla instances that I use (bugzilla.redhat.com) and doesn't even autocomplete bugzilla.mozilla.org even when history is full of entries for that.

### Expected behaviour

The most visited bugzilla domain gets autocompleted. Release with the same profile (via sync) behaves as expected.

### Actual behaviour

The wrong domain is autocompleted.

### Device name

moto G8 plus

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1 (Build #2015824779) AC: 92.0.20210726143050, b9ac2d1c1b GV: 92.0a1-20210726093430 AS: 81.0.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17390)

**Comment by marcel263** [comment] 2021-07-29 11:24
Hello, I can reproduce the issue, it seems to be a duplicate of #20351

**Comment by emilio** [comment] 2021-07-29 16:01
@marcel263 not sure it's the same. #20351 is about autocomplete not working properly. This is about it working, just giving the wrong autocomplete results.

**Comment by Mugurell** [comment] 2021-08-03 14:09
I see no recent change that could've impacted this in `ToolbarAutoCompleteFeature` or `InlineAutocompleteEditText`.
Only see changes in `PlacesHistoryStorage` related to history metadata. It's a shot in the dark but maybe [places.reader().matchUrl(query)](https://github.com/mozilla-mobile/android-components/blob/71e124a5dbafffb800168ea615fdbc54d7398f50/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt#L133) now queries the metadata storage which didn't yet had enough data to order the results? @grigoryk ?

**Comment by Mugurell** [comment] 2021-08-03 14:10
@emilio I'm also interested in whether the situation has improved over time, if the autocomplete result is more of what you'd expect?

**Comment by emilio** [comment] 2021-08-04 08:18
@Mugurell the autocomplete results are still quite borked, is like if the suggested URI was the least relevant one.

For example, entering "ph" says `phabricator.wikimedia.org` even though I only have one visit to that domain, and I have hundreds for `phabricator.services.mozilla.com`.

**Comment by LaurentiuApahideanSV** [comment] 2021-08-04 16:06
I tried to reproduce the issue on Firefox Preview RC 90.1.3 and Nightly 2021-08-04, but was unable to. I tried opening a lot of webpages and keeping track of my browsing history in order to compare it with the suggestions offered.

### Devices used:
- OnePlus 6T (Android 9)
- Samsung Galaxy S9 (Android 8.0.0)
- OnePlus Nord N10 (Android 10)

**Comment by Mugurell** [comment] 2021-08-20 12:28
Since we were unable to reproduce this and the issue was reported on Nighty I'm curious on whether the situation might have improved or it needs more investigation.

**Comment by emilio** [comment] 2021-08-20 13:25
It still seems bad locally. The only thing that I have tweaked on Nightly is the default search engine to be ddg, but switching back to the default doesn't fix it.

**Comment by ohhai** [comment] 2021-08-20 13:27
Just in case: I put some steps to reproduce here:  https://github.com/mozilla-mobile/fenix/issues/20351#issuecomment-894859923
See also next comment regarding 15 min wait.

**Comment by Mugurell** [comment] 2021-09-09 12:17
The different than expected autocomplete results issue probably depends on AS. Will leave this for @grigoryk .

**Comment by amedyne** [comment] 2022-02-01 18:51
@grigoryk Do you think any of the recent changes in autocomplete might have addressed the problem here?

**Comment by ohhai** [comment] 2022-11-26 11:48
Making activity since the current status is not clear

**Comment by boek** [comment] 2023-01-30 18:44
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813662

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-30 18:44 UTC
Labels: 🐞 bug, a-s
