### ISSUE TITLE
[Bug] Scrolling through tabs accidentally swipes the tab overview away

### ISSUE THREAD

**Issue by kolaente** [mozilla-mobile/fenix#12168] opened 2020-07-01 19:23 UTC
## Steps to reproduce
1. Open enough tabs to have the overview scroll (around 10 should be enough)
1. Open a tab at the very bottom of the list
1. Open the tab overview again, try to reach the top tab which requires you to scroll to the top

### Expected behavior
Overview scrolls to the top and lets me open the tab at the top.

### Actual behavior
Overview scrolls to the top and then hides away, requiring me to open the tab overview again and scroll _carefully_ slowly to not accidentally hide the tab overview again, leaving me frustrated behind. Often even while trying this carefully, it does not work as intended which means I have to do this a few times until I finally get to open the tab I want.

### Device information
* Android device: Oneplus 6 with lineage os, android 10
* Fenix version: 5.2.0 (Build #21701706)

**Comment by Dunexus** [comment] 2020-07-02 08:29
Duplicate of #11042, should be fixed by #11842 in nightly

**Comment by kbrosnan** [comment] 2020-07-02 14:26
Closing as a duplicate.

**Closed** 2020-08-28 21:26 UTC
Labels: needs:triage, 🐞 bug
