### ISSUE TITLE
FNX-12691 ⁃ [Bug] Tabs flicker when switching from private tabs to normal tabs

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11711] opened 2020-06-18 00:08 UTC
## Steps to reproduce
* Open a tab, load a page
* Open tabs tray
* Click Private tabs
* Click normal tabs

### Expected behavior
See normal tabs, no flicker

### Actual behavior
See normal tabs, flicker. Here's a video: https://drive.google.com/file/d/1Qpmv_bHSV0DgeZfXU3Gp5DBXxFeEAGGh/view?usp=sharing

### Device information
* Android device: P2, Galaxy S5
* Fenix version: Nightly 200617

**Comment by cadeyrn** [comment] 2020-06-19 06:15
Duplicate of #11560.

**Comment by cadeyrn** [comment] 2020-06-23 18:19
Fixed by #11826.

**Closed** 2020-08-11 04:42 UTC
Labels: Feature:Tabs, Skittle, 🐞 bug
