### ISSUE TITLE
[Bug] reddit site no notification 

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17674] opened 2021-01-28 04:19 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open reddit site in any chromium browser it shows the option to allow or deny push notification 
In fenix this does not show 
https://www.reddit.com/r/firefox/comments/l62nrn/is_localcdn_better_then_decentraleyes_should_i/

### Expected behavior
Site should show push notification enable message

### Actual behavior
Not showing the push notification message

### Device information

* Device vendor / model and Android version: ? Rog3 
* Firefox for Android version: ? (go to Settings -> About Firefox) latest

![Screenshot_20210128-094620338](https://user-images.githubusercontent.com/58127841/106089479-0427e980-614e-11eb-8bea-55b41afbe737.jpg)

**Comment by ale82to** [comment] 2021-01-29 02:30
I ve never been able to get a single notification with fenix 🤢

**Comment by jonalmeida** [comment] 2021-02-09 10:29
Duplicate of https://github.com/mozilla-mobile/fenix/issues/15028

**Closed by jonalmeida** 2021-02-09 10:29 UTC
Labels: Feature:Notifications, 🐞 bug

**Comment by sheikh-azharuddin** [comment] 2021-02-09 11:13
But the issues are different.. In twitter there is a dedicated button to configure push notification.. In reddit there is no such settings. For chromium the allow push notification message automatically pops on visiting the site which is not happening in fenix
