### ISSUE TITLE
[Bug]网页显示问题

### ISSUE THREAD

**Issue by 90du** [mozilla-mobile/fenix#9018] opened 2020-03-06 09:09 UTC
![Screenshot_2020_0306_170716](https://user-images.githubusercontent.com/35375370/76068945-11d00000-5fcd-11ea-84d1-632d679abd5d.png)

网页显示有明显问题，亲尽快修正

**Comment by Dunexus** [comment] 2020-03-06 10:19
Google Translate
> The webpage has obvious problems, please fix it as soon as possible

If it is about the bottom bar offset, it is probably a duplicate of https://github.com/mozilla-mobile/fenix/issues/8757

**Comment by liuche** [comment] 2020-03-17 01:14
Thanks for filing! I will dupe this to #8757. Please follow along there for the fix!

**Closed by liuche** 2020-03-17 01:14 UTC
Labels: needs:triage, 🐞 bug
