### ISSUE TITLE
FNX-4484 ⁃ Add change the download path

### ISSUE THREAD

**Issue by ndnddkoeo3dkej9** [mozilla-mobile/fenix#10704] opened 2020-05-16 17:12 UTC
### Description
In Firefox Preview is not available as in Firefox Desktop.  The possibility to change the download path.

Add this in Firefox Preview.  Create a new category under Settings e.g. Settings -> Downloads

* Download Path
* Always ask me where to save files

### Version
Android 9

Firefox Preview 5.0.0
https://github.com/mozilla-mobile/fenix/releases/tag/v5.0.0

**Comment by cadeyrn** [comment] 2020-05-16 18:34
Duplicate of #5764.

**Comment by ekager** [comment] 2020-05-16 20:20
Closing for #5764

**Closed** 2020-08-11 01:29 UTC
Labels: needs:triage
