### ISSUE TITLE
do not send URL keystrokes to search provider by default in Private mode

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#5985] opened 2019-10-12 23:44 UTC
Privacy issue: open a Private tab, start typing and observe there are suggestions from Google search. This should not be the default behaviour for Private tabs. Even Chrome does not do this by default! If users want this behaviour, they should have to go manually choose so, it should not be the default behaviour.

**Comment by NotWoods** [comment] 2019-10-13 18:53
Duplicate of #1019. It's getting worked on!

**Closed by NotWoods** 2019-10-13 18:53 UTC
