### ISSUE TITLE
[Request]Opening new tab by double clicking tab icon 

### ISSUE THREAD

**Issue by reyabo** [mozilla-mobile/fenix#17608] opened 2021-01-24 08:12 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
It would be great to open a new tab by double clicking the tab icon. Instead of clicking the tab icon and then the plus icon.

**Comment by Matth7878** [comment] 2021-01-24 08:38
Duplicate with issue #15025
Would love it as well right now opening a new tab is really annoying. You can't avoid going to tab tray.

**Comment by mcarare** [comment] 2021-01-25 10:22
Closing as duplicate of #15025.

**Closed by mcarare** 2021-01-25 10:22 UTC
Labels: needs:triage
