### ISSUE TITLE
[Bug] [a11y] On Onboarding the focus jumps on the header of the screen instead of Theme card after a theme is selected

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#3418] opened 2019-06-13 12:41 UTC
### Prerequisites
Make sure to have a clean profile.

### Steps to reproduce
1. Enable Talkback.
1. Open Firefox Preview and go to Theme card.
1. Tap on Dark theme.
1. Double tap on Dark theme to activate it.

### Expected behavior
The theme is changed, and the focus remains on Theme card.

### Actual behavior
The theme is changed, but the focus moves to the search bar. The same behavior is encountered if Automatic selected, or Light theme.

### Device information
* Android device: OnePlus 5T (Android 9)
* Fenix version: 6/13

[logcat.talkback.txt](https://github.com/mozilla-mobile/fenix/files/3286017/logcat.talkback.txt)

![talkbackthemes](https://user-images.githubusercontent.com/40694158/59432903-0f02fe80-8df1-11e9-8bfb-76532fdfaa98.gif)

**Comment by nicolashleon** [comment] 2019-06-28 23:35
After doing some research on the issue, it seems that the focus change with the talkback activated is caused by the activity recreation after setting the new theme thru the function `OnboardingThemePickerViewHolder.setNewTheme(mode: Int)`.

Inside the mentioned function is a call to [`AppCompatDelegate.setDefaultNightMode(mode) `](https://developer.android.com/reference/androidx/appcompat/app/AppCompatDelegate.html#setDefaultNightMode(int)) where its documentation states _"If this method is called after any host components with attached AppCompatDelegates have been 'started', a uiMode configuration change will occur in each. This may result in those components being recreated, depending on their manifest configuration."_

Additionally, the `uiMode` configuration change is not set inside the manifest.

I would like to have some technical input on how to address the situation because it is the expected behavior from the OS. There are some alternatives such as forcing the ´uiMode´ on the manifest but I believe it requires further discussion. 

## Technical Details
- Device: Android Emulator 
- OS : Android 7.1.1 API 25
- Talkback version:  Android Accessibility Suite 7.3.0.239841594
- Firefox Preview Version: 1.0.11926

**Comment by NotWoods** [comment] 2019-09-30 03:38
I think we could check if the theme chooser was focused and store that in a viewmodel or shared preferences here. If the chooser was focused, it should be refocused when the activity is created again.

**Comment by softvision-miralobontiu** [comment] 2019-10-18 11:14
This issue is still reproducible on OnePlus 5T (Android 9) on the latest Nightly build 10/18 (#12910609).

**Comment by BranescuMihai** [comment] 2019-11-01 16:03
Looked a bit into this one, de-assigned myself for a few reasons:

1. Seems like a majority of the android community highly opposes any accessibility auto-focus (maybe the accessibility users know that changes to the page move the focus on the top?)
2. Even disregarding the first reason, at this moment, I can't find a way to programatically set the accessibility focus WITHOUT the actual talk-back voice (which makes it a bit weird for the user to hear again that the focus is set on the theme selector)
3. Furthermore, since Talkback scans the screen and then traverses the children, it takes some time to set its focus on the first element. So setting the focus accessibility event will get overridden if we do it too early, and using delays could lead to inconsistent behaviour on different phones

There might be a way by changing the traversal order of this element to before the first focusable element in the activity, but again, the first 2 reasons still apply

**Comment by softvision-miralobontiu** [comment] 2019-12-06 08:25
I was able to reproduce this issue, again, on 3.0.0-beta.3 build. After selecting a theme, the selection jumps on the header of the screen selecting the element that is displayed there.
Reproduced with LG G7 Fit (Android 8.1).

**Comment by sflorean** [comment] 2020-04-01 12:19
This is reproducible with Talkback disabled, when the dark theme is selected. Not reproducible when the theme is changed from automatic to light. 
Nightly build 01/04.

![20200401_150644](https://user-images.githubusercontent.com/58466444/78136301-0afda700-742c-11ea-80b7-3931e3cb540c.gif)

**Comment by Diana-Rus** [comment] 2020-04-22 09:24
Hi, issue is still reproducible with Sony Xperia Z5 (Android 7) on Firefox Nightly 4/22.
Note:
- After activating/enabling dark theme the talk back starts from the private browsing button. The same outcome is present when selecting white theme.

**Comment by softvision-miralobontiu** [comment] 2020-09-10 07:28
I was able to reproduce this issue on the latest Nightly build from 9/10 with HTC 10 (Android 8). 
The focus jumped on the three-dot menu after selecting the dark theme.

**Comment by softvision-miralobontiu** [comment] 2021-02-16 07:34
Reproducible on beta 86.0.0-beta.5 with Talkback on, with Xiaomi Mi 8 Lite (Android 9).

**Comment by lobontiumira** [comment] 2021-06-15 06:25
This issue reproduces on the Beta 90.0.0-beta.3 build with Talkback on, on OnePlus 5T (Android 10).

**Comment by lobontiumira** [comment] 2021-11-02 12:50
I was able to reproduce this issue on the 11/2 Nightly build with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by sflorean** [comment] 2022-05-05 11:26
This is no longer available since the "Choose your theme card" is the first displayed. Closing as worksforme.

**Closed by sflorean** 2022-05-05 11:26 UTC
Labels: 🐞 bug, access, Feature:Onboarding, help wanted, wontfix
