### ISSUE TITLE
[Bug]: Search in a new tab does not scroll to that tab

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#21705] opened 2021-10-05 10:06 UTC
### Steps to reproduce

Open a tab
Search for anything eg "cat"
Go to the tab tray

### Expected behaviour

The tab list should scroll to show that tab

### Actual behaviour

The tab list does not scroll to the "cat" search

(I think sometimes the "cat" search also does not get the blue focus ring, but I am unsure of STR, still working on it)

### Device name

Galaxy A40

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Today's

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18173)

**Comment by SoftVision-LorandJanos** [comment] 2021-10-05 13:06
Hi @Cheap-Skate ! Thank you for the report.
I could reproduce this issue.

Verified on the latest Nightly (94.0a1 - 2021-10-05T05:10:10.350256).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Redmi 11 Lite (Android 11).

**Comment by tennox** [comment] 2022-03-01 13:20
Still happening and quite nasty.
Is there a workaround?

It sounds like it will not be fixed soon (see https://github.com/mozilla-mobile/fenix/issues/23584#issuecomment-1039030740) :(

**Comment by travisterrell** [comment] 2022-08-04 21:51
> Still happening and quite nasty. Is there a workaround?
> 
> It sounds like it will not be fixed soon (see [#23584 (comment)](https://github.com/mozilla-mobile/fenix/issues/23584#issuecomment-1039030740)) :(

It really is a miserable issue for users who keep large numbers of tabs open. It happens at least 50% of the time I open the tab switcher. l feel like this must not be affecting all users--or I think this issue would have much more attention. (Though it's not really named properly to reflect the full scope of the problem. Maybe there's a more popular issue I overlooked?)

As it takes 5-10 swipes to reach the bottom of my tab list, quickly switching back to a recent tab is extremely inconvenient. My latest workaround is to repeatedly close and reopen the tab list. Within a few tries, it usually opens properly scrolled to the active tab.

**Comment by tennox** [comment] 2022-08-05 18:19
It's still a thing in `105.0a1 (Build #2015896299), 926daabe1+`
![Screenshot_20220805-191129.jpg](https://user-images.githubusercontent.com/2084639/183137706-f21812a9-d5e6-412a-a3d6-4980882451c5.jpg)

I have to say that I still occasionally have this issue with the setting disabled. So I guess it's a race condition?

**Comment by bigConifer** [comment] 2022-09-23 23:57
I think this ticket should be closed as duplicate of #23584.

At the moment there are at least 5 open tickets about this bug. As there are already some debugging information in https://github.com/mozilla-mobile/fenix/issues/23584#issuecomment-1039030740, please add further details there.

**Closed** 2023-01-17 16:02 UTC
Labels: 🐞 bug, Feature:Tabs, S3, qa-triaged, Feature:SearchTermTabs
