### ISSUE TITLE
[Bug] "Closed tab" bar doesn't disappear

### ISSUE THREAD

**Issue by RavingSombra** [mozilla-mobile/fenix#8566] opened 2020-02-20 08:08 UTC
## Steps to reproduce
1. Open a new tab
2. Access any website
3. Close the tab

### Expected behavior
After closing the tab a bar should appear above the address bar for a few seconds, with the option to undo

### Actual behavior
That bar appears, but doesn't go away. Once I've managed to make it go away, but I don't remember the trick.

### Device information
Google Pixel 3XL
Android 10 feb-2020 patch
(build QQ1.200205.002)

### Firefox Preview version
3.2.1 (Build #20250350)
28.0.3, f0dc2cadd

**Comment by cadeyrn** [comment] 2020-02-20 09:13
Duplicate of #7799.

**Closed** 2020-02-20 16:50 UTC
Labels: needs:triage, 🐞 bug
