### ISSUE TITLE
[Bug] touching back while the address bar is enabled navigates to the previous page, instead of just leaving the address bar to the current page.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#4717] opened 2019-08-14 04:11 UTC
## Steps to reproduce
Browse some pages
Touch the address bar
Touch the device's back button

### Expected behavior
Fenix leaves the address bar and goes back to the current page.

### Actual behavior
Fenix leaves the address bar and goes back to the previous page.

### Device information

* Android device: Galaxy A5 2017
* Fenix version: 190813

**Comment by ekager** [comment] 2019-10-07 20:31
Could you clarify this a bit with maybe a video/gif? And is this always reproducible? I'm not quite sure what you mean

**Comment by Lululalu** [comment] 2019-10-11 17:15
@ekager I recorded a video: https://streamable.com/hk13c

When I touch the back button on my device I shouldn't be sent back to the serp.

**Comment by topotropic** [comment] 2020-02-12 13:29
@Lululalu could you briefly verify if this is still an issue? Unfortunately the recorded video isn't available anymore. Thanks!

**Comment by ekager** [comment] 2020-02-14 05:11
@Lululalu please close this if you aren't seeing it anymore

**Closed** 2020-02-17 13:11 UTC
Labels: P2, b:navigation, needs:STR, 🐞 bug

**Comment by softvision-miralobontiu** [comment] 2020-03-11 09:50
I was not able to reproduce the issue on the latest Nightly from 3/11 with Xiaomi Redmi Note 8T (Android 9), and HTC Desire 820 (Android 6.0.1).
Removing the needs:STR label.
