### ISSUE TITLE
FNX-12482 ⁃ A "download with" option so we can easily use download managers to download files

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#11532] opened 2020-06-12 19:38 UTC
### What is the user problem or growth opportunity you want to see solved?
A lot of people use download managers such as ADM to speed up downloads much faster than fenix or any other browser. However using them is cumbersome and we have to manually copy paste the download link to download something. 

I propose that in the download popup there can be two options:

1. download ,which already exists
1. Download with option which allows you to select the download app

### Who will benefit from it?
People who use download managers extensively.

**Comment by hakkikaancaliskan** [comment] 2020-06-12 19:56
Duplicate of #7620

**Closed** 2020-08-11 04:17 UTC
Labels: needs:triage
