### ISSUE TITLE
[Bug] Blocking of autoplay videos does not work as expected

### ISSUE THREAD

**Issue by elonus** [mozilla-mobile/fenix#8987] opened 2020-03-05 11:42 UTC
## Steps to reproduce
Open Firefox Preview Nightly.
Under settings -> permissions, enable blocking of autoplaying video and audio.
Open [www.nrk.no](www.nrk.no) and scroll down until you find a autoplaying video.

### Expected behavior
I would expect that the video would be prevented from autoplaying

### Actual behavior
The video autoplays, however the sound is disabled. I am however unsure if this is because Fenix is blocking it or if nrk is being considerate and having it by default disabled.

### Device information

* Android device: OnePlus 7t
* Fenix version: Nightly 200304 06:01 (Build #20640607)

**Comment by Amejia481** [comment] 2020-03-05 15:10
This happened because at the moment we are not disabling autoplay for muted content. We are working on an advance settings for autoplay  for more info see https://github.com/mozilla-mobile/fenix/issues/8017

**Comment by sv-ohorvath** [comment] 2020-07-31 12:10
Now the auto-play videos on nrk.no are always blocked for me (no matter which setting I have), but on twitter.com they are not being blocked with Block video and audio set.

**Comment by Iey4iej3** [comment] 2020-10-05 06:36
I don't know whether it is related. In some sites, no matter where I click on the webpage, the media will start to play. For example,
https://www.lachainemeteo.com/meteo-france/ville-33/previsions-meteo-paris-aujourdhui
This is also bad. I consider this as a variant of autoplay.

**Comment by Amejia481** [comment] 2020-11-03 20:18
I was doing some tests on www.nrk.no, from a user perspective no video/audio was played while I was testing. I also tested on Firefox desktop (with allow video/audio) and Chrome and neither browser video or audio played, not sure if the site has changed its behaviour so far. From code perspective, I saw the permissions for `ContentAutoPlayInaudible` and`ContentAutoPlayAudible` requested and allowed/denied depending on the settings on Fenix.

**Comment by elonus** [comment] 2020-11-04 20:18
Thanks for looking into this! I think www.nrk.no might have changed the behaviour of their videos as I no longer see any autoplay, neither with blocking enabled nor disabled.

**Comment by Amejia481** [comment] 2020-11-12 19:54
The issue is address on https://github.com/mozilla-mobile/android-components/pull/8944 and will be fixed when Fenix update to the new ac version.

**Comment by abodea** [comment] 2020-11-17 10:12
Verified as fixed on the latest Nightly **17/11** with **Google Pixel 4 XL (Android 11).**
Note that the auto-play was blocked and when tapping on the play button everything works as expected and the video/audio started to play.

**Closed by abodea** 2020-11-17 10:12 UTC
Labels: E8, Feature:Media, S2, eng:qa:needed, 🐞 bug
