### ISSUE TITLE
[Bug] When adding new tabs, tabs tray does not scroll to position of new tab

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8334] opened 2020-02-11 23:21 UTC
## Steps to reproduce
- Open more than a screen length of tabs
- Scroll to the bottom of the homescreen
- Press + to open a new tab & load a new page
- Press tabs tray

### Expected behavior
Selected tab is visible on the screen

### Actual behavior
Homescreen is scrolled to the bottom so selected tab is not visible on the screen. I believe this was still broken before but marcleclair recently changed the behavior to restore the scroll position when the view is recreated: we'll have to update that offset when adding new tabs.

### Device information

* Android device: P2
* Fenix version: Nightly 200212

**Comment by mcarare** [comment] 2020-02-17 15:58
@mcomella , I think this is a duplicate of https://github.com/mozilla-mobile/fenix/issues/7356.
Feel free to reopen if you were referring to something different. TY!

**Closed by mcarare** 2020-02-17 15:58 UTC
Labels: needs:triage, 🐞 bug
