### ISSUE TITLE
[Bug] Several buttons for expanding sections do not work

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#9661] opened 2020-04-03 09:51 UTC
## Steps to reproduce
1. Go to https://www.arcgis.com/apps/opsdashboard/index.html#/f94c3c90da5b4e9f9a0b19484dd4bb14
2. Try to expand the menus highlighted in the attachment.
![expand](https://user-images.githubusercontent.com/50983519/78347762-a10b0c00-75a9-11ea-9608-499b2876f600.jpg)
### Expected behavior
Tapping the buttons should expand the corresponding sections.
### Actual behavior
The buttons are unresponsive.
### Device information

* Android device: OnePlus 6T (Android 9), Huawei MediaPad M3 lite 10 (Android 7.0)
* Fenix version: Firefox Preview Beta 200403 (Build #20940610) 4/3

**Comment by kbrosnan** [comment] 2020-04-08 00:35
This looks like webcompat. Please check with that team for diagnosis steps and possibly open an issue at https://webcompat.com.

**Comment by denschub** [comment] 2020-04-09 13:27
It's fair to say that the people building this dashboard did not have mobile users in mind. However, the difference is interesting nonetheless.

In Fennec, clicking the buttons works just fine. In Fenix, however, the buttons marked with red don't work, while others do. On checking which elements receive a touch/click event when I try to press the affected buttons, I see that we end up clicking on `div#ember70` instead, if you click the "UK Daily" button. That's interesting, because even though there is some overlap, hitting the button should be possible:

<img width="413" alt="Screenshot 2020-04-09 at 15 25 33" src="https://user-images.githubusercontent.com/344777/78900002-7ff95e00-7a76-11ea-9640-eef2a5dbbc93.png">

As this works fine in Fennec, I have to wonder: Is there a difference in how Fenix and Fennec determine the object that was tapped on? Different finger-radius assumption or something along the lines of that? Is that even a thing? :)

**Comment by kbrosnan** [comment] 2020-04-11 17:42
Thank you @denschub for having a look from a webcompat angle. Seems like we are running into Gecko behavior here. @LaurentiuApahideanSV please open a Gecko bug at bugzilla.mozilla.org when you have a moment.

**Comment by denschub** [comment] 2020-04-27 09:45
This is, essentially, https://bugzilla.mozilla.org/show_bug.cgi?id=1632941 - which is a regression from re-enabling `ui.mouse.radius.enabled`. So this could be closed as a duplicate of that issue.

**Comment by karlcow** [comment] 2020-04-29 01:48
another webcompat instance could be https://github.com/webcompat/web-bugs/issues/50270

**Comment by ekager** [comment] 2020-07-10 16:30
Looks like the fix for bugzilla.mozilla.org/show_bug.cgi?id=1632941 landed, so let's recheck this in FEnix

**Comment by AndiAJ** [comment] 2020-07-13 10:31
Hi, **verified as fixed** on the latest **`Fenix Nightly Build 200713 from 7/13`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

As the link @LaurentiuApahideanSV provided isn't available anymore, I've used the following websites to re-check this matter:
• https://instnsp.maps.arcgis.com/apps/opsdashboard/index.html#/5eced796595b4ee585bcdba03e30c127
• https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4
• https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

► Video
![20200713-130608](https://user-images.githubusercontent.com/51314259/87294493-8df2cb00-c50c-11ea-8408-b6e7f8ce41b9.gif)

► Video
![20200713-130714](https://user-images.githubusercontent.com/51314259/87294626-b084e400-c50c-11ea-97e3-15af521ac888.gif)

► Video
![20200713-132354](https://user-images.githubusercontent.com/51314259/87294852-02c60500-c50d-11ea-8fbb-dcb641975fc5.gif)

**Closed by AndiAJ** 2020-07-13 10:31 UTC
Labels: Feature:Browsing, S2, b:webcompat, eng:qa:needed, 🐞 bug
