### ISSUE TITLE
[Bug] javascript: scheme is not handled inside Fenix

### ISSUE THREAD

**Issue by makotom** [mozilla-mobile/fenix#4286] opened 2019-07-25 04:37 UTC
## Steps to reproduce
1. Open https://makotom.net/tc-20190725.html .
2. Tap the text `javascript:console.log('fired')`.

### Expected behavior
Nothing noticeable should happen in any tab. (Observed behaviour in the conventional Firefox Mobile for Android.)

### Actual behavior
A: In the case the page was opened in a normal tab, Chrome was opened upon tapping the text.
B: In the case the page was opened in a private tab, a prompt saying "Open in app? Your activity may no longer be priate." was shown.

### Device information

* Android device: Pixel 3a, Build PQ3B.190705.003
* Fenix version:
![Screenshot_20190725-133105](https://user-images.githubusercontent.com/872612/61846056-a2474d80-aee0-11e9-9055-c1d045221fcf.png)

### Footnotes
* I recognize some relation between this issue and #1570 , because I see this issue reappeared aftter #1570 was fixed.
* I personally thought that this issue could be the root cause of #2871 - but this is just my guess.

**Comment by makotom** [comment] 2019-07-25 04:41
I'm uploading the content of https://makotom.net/tc-20190725.html as [tc-20190725.html.txt](https://github.com/mozilla-mobile/fenix/files/3429741/tc-20190725.html.txt).

**Comment by bogas04** [comment] 2019-07-25 18:32
Can face the issue on [Amazon website](https://amazon.in). 

![Screen cast of the issue on Amazon's reviews section](https://thumbs.gfycat.com/SpeedyTerribleAzurewingedmagpie-size_restricted.gif)

**Comment by makotom** [comment] 2019-07-30 14:15
> I recognize some relation between this issue and #1570 , because I see this issue reappeared aftter #1570 was fixed.

Maybe, the issue in interest should be #4114.

**Comment by johnsto** [comment] 2019-08-01 19:05
Same issue here on build 1.1.0#12042112:

![edit_20190728_091533_1](https://user-images.githubusercontent.com/1548274/62320189-85d68280-b497-11e9-9b79-52ddaff54e81.gif)

**Comment by johnsto** [comment] 2019-08-08 04:49
Seems fixed in 1.2.0 (Build #12181645)!

**Comment by makotom** [comment] 2019-08-20 00:08
This should have been fixed in https://github.com/mozilla-mobile/android-components/commit/688d1f236598a1ec3b548e324265c589a9557b87 for https://github.com/mozilla-mobile/android-components/issues/3944.

Can we close this issue for now?

**Comment by NotWoods** [comment] 2019-11-15 03:37
Also could not reproduce on Nightly 191109.

**Comment by AndiAJ** [comment] 2019-11-15 14:16
Hi, **verified as fixed** on the latest **Nightly Build #13190606 from 11/15** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191115_154052](https://user-images.githubusercontent.com/51314259/68949594-04df9480-07c3-11ea-80c6-59fc43846ef2.gif)

► Video
![20191115_154248](https://user-images.githubusercontent.com/51314259/68949639-293b7100-07c3-11ea-8445-42f00ae30066.gif)

**Closed by AndiAJ** 2019-11-15 14:16 UTC
Labels: b:webcompat, eng:qa:verified, 🐞 bug
