### ISSUE TITLE
[Bug] Adress bar does not correspond to correct tab

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#19563] opened 2021-05-19 13:14 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- In settings, under private browsing make sure "Open links in private tab" is turned on
- Close the browser
- In a different app, click on a link 
- Once the page is loaded, click the address bar and press enter

### Expected behavior
The private tab should be reloaded

### Actual behavior
The tab itself is not reloaded, instead the page gets opened in a non private tab. If you had a normal tab open already, the page gets loaded in this tab.

### Device information

* Device vendor / model and Android version: Huawei Nova 6 (Android 10)
* Firefox for Android version: 90.0a1 (Build #2015811147)

**Comment by SoftVision-LorandJanos** [comment] 2021-05-19 15:17
Hi @mobd ! Thank you for your report! I was not able to reproduce the issue described above on the Nightly version Build #2015811147) mentioned by you and on the latest Nightly (Build #2015811241). Aside from set the links to open in private tab, I set the browser to be default, searched for a link from a non-browser app, opened it and then refreshed the page with the steps you described. The page was successfully refreshed in private browsing. 
Tested using a Motorola Nexus 6 with Android 7.1.1 and a Samsung Galaxy Tab3 with Android 9.

Using a Google Pixel 3 XL (Android 9) with the latest Nightly, the issue was reproducible with the difference that the link was opened in both private tab and normal browsing. 

Could you please try the same steps after a clear data, with the latest Nightly? Thank you!

**Comment by mobd** [comment] 2021-05-25 19:37
Hi, I can still reproduce yes. Also after testing again it seems like it happens in normal browsing too if I have "open links in private tabs" turned off. The page will get loaded in an already open tab instead of the newly opened tab

**Comment by SoftVision-LorandJanos** [comment] 2021-11-22 07:03
This issue is not reproducible on the latest Nightly 96.0a1 (2021-11-22).
Device used: Xiaomi Mi11 Lite (Android 11).
Closing the ticket.

**Closed by SoftVision-LorandJanos** 2021-11-22 07:03 UTC
Labels: 🐞 bug, Feature:PrivateBrowsing, needs:triage, wontfix, qa-triaged
