### ISSUE TITLE
FNX-4328 ⁃ [Bug] Tab tray doesn't scroll down to recently viewed tab

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#10496] opened 2020-05-07 15:48 UTC
## Steps to reproduce
Open tabs until you filled up the whole screen and 1 more

### Expected behavior
Tab tray scrolls down a bit to highlight the tab you currently have open

### Actual behavior
Tab tray remains in the top position, so you can’t see the tab you currently have open

**Comment by jonalmeida** [comment] 2020-05-20 21:38
I closed the [a-c bug](https://github.com/mozilla-mobile/android-components/issues/6922) for this since it's something the app should do that we can't provide for free.

**Comment by AndiAJ** [comment] 2020-05-29 09:55
Hi, **still reproducible** on the latest **`Nightly Build 200529 from 5/29`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200529-124535](https://user-images.githubusercontent.com/51314259/83247040-a5b7ff00-a1ab-11ea-830f-cb6be36cbfb2.gif)

**Comment by boek** [comment] 2020-05-29 15:34
@AndiAJ sorry! The PR didn't get merged last night

**Comment by AndiAJ** [comment] 2020-06-02 14:25
Hi, **verified as fixed** on the latest **`Nightly 200602 from 6/2`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200602-172202](https://user-images.githubusercontent.com/51314259/83531684-f86c2080-a4f5-11ea-8a06-56c548defa81.gif)

**Closed** 2020-08-11 00:54 UTC
Labels: E3, Feature:Tabs, P1, Skittle, eng:qa:verified
