### ISSUE TITLE
[Bug] "Report site issues" from the three-dot menu doesn't display the icon with light theme

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#19558] opened 2021-05-19 08:49 UTC
### Prerequisites:
Make sure to have the light theme enabled.

## Steps to reproduce
1. Open a page.
2. Tap on the three-dot menu.
3. Observe the "Report site issues" option.

### Expected behavior
The "Report site issues" option has an icon, like all the other options.

### Actual behavior
The "Report site issues" option does not have an icon. An uncertain icon is displayed very briefly - please see the short video below.

### Device information
* Device: OnePlus 5T (Android 10), Google Pixel 4 XL (Android 11), Samsung Galaxy S10+ (Android 10)
* Firefox for Android version: 5/19 Nightly build

https://user-images.githubusercontent.com/40694158/118783810-19a95680-b898-11eb-9662-5f63d9adfa0b.mp4

**Comment by amedyne** [comment] 2021-06-24 15:05
@topotropic or @brampitoyo what Icon should we use for this one?

**Comment by codrut-topliceanu** [comment] 2021-06-30 10:38
> @topotropic or @brampitoyo what Icon should we use for this one?

I think there's already an icon there, the problem is it's white.
![image](https://user-images.githubusercontent.com/60002907/123946960-7411f880-d9a8-11eb-989d-bd67c347c97a.png)

**Comment by sflorean** [comment] 2021-07-05 13:58
Verified as fixed on Nightly 7/5 with Samsung Note 10 (Android 11).

**Closed by sflorean** 2021-07-05 13:58 UTC
Labels: Feature:MainMenu, Feature:Settings, S4, 🐞 bug

**Comment by brampitoyo** [comment] 2021-07-06 00:43
@amedyne Yes. The icon that @codrut-topliceanu suggested was the correct one to use. Thanks!

**Comment by Nickoriginal** [comment] 2021-07-17 19:42
Fixed in 91.0.0-beta.1 for future developer releases.
