### ISSUE TITLE
[Bug]: Homepage/Address Bar Opens New Tab

### ISSUE THREAD

**Issue by JingleDjango** [mozilla-mobile/fenix#22470] opened 2021-11-17 01:54 UTC
### Steps to reproduce

1. Have a tab open
2. Tap the address bar
3. Tap any of the grid of familiar shortcuts

### Expected behaviour

Redirect the active tab to the chosen site.

### Actual behaviour

A new tab is opened at the chosen site. I could open a new tab using the new tab button if desired. 

### Device name

Samsung S9

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

94

**Comment by czlucius** [comment] 2021-11-17 05:25
Hi there
I think this issue is discussed in #13336 and #20012, you may want to take a look.

**Comment by SoftVision-LorandJanos** [comment] 2021-11-17 07:13
Hi @JingleDjango. Thank you for your report!
I can reproduce the issue you described.
However it is covered by #20012 as mentioned above, and I've seen it in the details of other tickets as well.
Also as far as I know, it is intended this way at the moment.
Based on these, I will close this ticket, please follow the mentioned ticket, or if you find any other that covers the issue you described, and you can leave a comment on one of them with additional information, if you have. Thank you!

**Closed by SoftVision-LorandJanos** 2021-11-17 07:13 UTC
Labels: 🐞 bug, needs:triage
