### ISSUE TITLE
[Bug] distribution_id is unexpectedly Null in just under half of metrics pings received: indicative of release telemetry skew?

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#19386] opened 2021-05-04 22:24 UTC
_Breakout from #19366._

Over a 2-day period, [only 55.7% of metrics pings received on release have a `distribution_id` set](https://sql.telemetry.mozilla.org/queries/79834). There are a few possibilities:
- Someone forked the code and does not transmit a distribution id
- there is a race condition since the `distribution_id` is set after `Glean.initialize` is called
- this is impossible because we only ever set `distribution_id` to "Mozilla" or "MozillaOnline":
https://github.com/mozilla-mobile/fenix/blob/f421f82f2cae96d2c3e926a64eaa05082df85d17/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L134-L139

**In the worst case, this means that just under half our data could be coming from a source that isn't our production builds.** For example, this could be a fork that removes the `distribution_id` field with a non-trivial user population that **is skewing our release data**. We should investigate 1) if the analysis is correct and this is a real issue, 2) what is the cause?, and 3) how we might work around this.

Caveat: a better analysis should reduce the impact one weird client (e.g. that submits an unrepresentative large amount of data) would have on the results.

### By app version
Curiously:
- as expected, in some app versions `Mozilla` is the dominant distribution ID (e.g. in 88.1.1, 96.4% of metrics pings received over a 2 day period have `Mozilla` as the app ID)
- **unexpectedly,** in some app versions, Null is the dominant distribution ID (e.g. in 86.1.1, **85.5% of metrics pings received over a 2 day period have `Null` as the app ID**)

This backs up the possibility that there is a fork (e.g. it's a few versions behind our latest release). Here are [the results of the query I wrote that is the `distribution_id` summed by `app_display_version` for a 2 day period](https://sql.telemetry.mozilla.org/queries/79831). 

Caveat: I am not an experienced data analyst or SQL user and may have made mistakes.

**Comment by jonalmeida** [comment] 2021-05-04 22:56
@rocketsroger is this similar or a duplicate of https://github.com/mozilla-mobile/fenix/issues/19147?

**Comment by mcomella** [comment] 2021-05-05 15:10
badboy said they'd take a look into why this is happening this week or next week.

Since this is growing outside the scope of my original telemetry analysis, I'm going to hand it off and not plan to work on it. I look forward to the results though! 😄

**Comment by badboy** [comment] 2021-05-05 15:11
We track that on the Glean side here: https://bugzilla.mozilla.org/show_bug.cgi?id=1694343

I suspect some unexpected interaction between Glean startup and Fenix startup.
I plan to look into this within a week.

**Comment by rocketsroger** [comment] 2021-05-05 15:11
> @rocketsroger is this similar or a duplicate of #19147?

Yes this is a duplicate.  The workaround has been merged.

**Comment by mcomella** [comment] 2021-05-12 22:07
> > @rocketsroger is this similar or a duplicate of #19147?
> 
> Yes this is a duplicate. The workaround has been merged.

@rocketsroger So to be explicit, can this be closed? e.g. `distribution_id` is a specific metric that we're considering for #19147?

**Comment by rocketsroger** [comment] 2021-05-12 23:41
Yes, I have a follow up issue created https://github.com/mozilla-mobile/fenix/issues/19251.   Once Glean investigation is completed, I'll remote the workaround and update the implementation with the new solution.

**Closed** 2021-05-12 23:54 UTC
Labels: needs:triage, 🐞 bug
