### ISSUE TITLE
FNX2-13393 ⁃ [Bug][crash] Fenix crashes when deleting 2 saved logins in a row

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#11227] opened 2020-06-04 14:18 UTC
## Steps to reproduce
1. Sign in with valid credentials.
1. Go to Settings - Logins and passwords and delete 2 saved logins.

### Expected behavior
No issues encountered. The deleted saved logins are not displayed anymore.

### Actual behavior
Fenix crashes. The deleted saved logins are not displayed anymore.

### Device information
* Android devices: Sony Xperia Z5 Premium (Android 7.1.1), Motorola Moto G6 (Android 8)
* Fenix version: 6/4 Nightly build
* Reproducible 3/5 times

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4730545/logcat.txt)

![](https://user-images.githubusercontent.com/40694158/83768302-47958b00-a687-11ea-86a1-dbcd797114e1.gif)

**Comment by ebalazs-sv** [comment] 2020-06-29 14:09
This issue is still reproducible on Fenix Beta 78.0.1-beta.1 GV 78 from 6/27 with Motorola Moto G6 (Android 8).

**Comment by liuche** [comment] 2020-07-01 18:47
If we can fix this in the next sprint, it will be part of the fast-follow release.

**Comment by BranescuMihai** [comment] 2020-07-07 07:00
Tried this with OnePlus 7TPro (Android 10), Pixel 3(Android 7.1.1 emulator) and Pixel 2 (Android 5 emulator) at least 5 times each, can't reproduce it, it's probably device specific.  

Relevant part from the attached logcat:
`2020-06-04 16:57:59.587 12096-12122/? D/logins_ffi: sync15_passwords_get_all
2020-06-04 16:57:59.624 12096-12122/? I/glean/Dispatchers: Task queued for execution and delayed until flushed
2020-06-04 16:57:59.637 12096-12173/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.util.NoSuchElementException: List is empty., breadcrumbs=[Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jun 04 16:55:52 GMT+03:00 2020), Breadcrumb(message=Changing to fragment settingsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jun 04 16:57:49 GMT+03:00 2020), Breadcrumb(message=Changing to fragment savedLoginsAuthFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jun 04 16:57:51 GMT+03:00 2020), Breadcrumb(message=Changing to fragment savedLoginsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jun 04 16:57:52 GMT+03:00 2020), Breadcrumb(message=Changing to fragment loginDetailFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jun 04 16:57:55 GMT+03:00 2020), Breadcrumb(message=Changing to fragment savedLoginsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jun 04 16:57:58 GMT+03:00 2020), Breadcrumb(message=Changing to fragment loginDetailFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jun 04 16:57:59 GMT+03:00 2020)], uuid=1b525bc4-04be-40c6-8ece-8b3cb0e3d099)`

**Comment by Mugurell** [comment] 2020-07-10 07:48
Very few such issues seen in Sentry

Sentry issue: [FENIX-NIGHTLY-385](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8631468/?referrer=github_plugin)

**Comment by softvision-miralobontiu** [comment] 2020-07-17 09:49
Verified as fixed on the latest Nightly build from 7/17 with Sony Xperia Z5 Premium (Android 7.1.1).

**Closed** 2020-08-12 17:29 UTC
Labels: E2, Feature:Logins, S1, b:crash, eng:qa:verified, 🐞 bug
