### ISSUE TITLE
FNX-5142 ⁃ Fenix crashes at about:about [Bug]

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#1623] opened 2019-04-13 22:27 UTC
## Steps to reproduce
Enter about:about

### Expected behavior
Fenix shows the list of abouts

### Actual behavior
Fenix crashes

### Device information
* Android device: Samsung Galaxy Tab A (2016) SM-T580, Stock Android 8.1.0
* Fenix version: 1.0.1915 (Build #11031226) German localization

**Comment by AaronMT** [comment] 2019-04-15 16:56
Dupe of #1624

**Closed** 2020-08-11 12:18 UTC
Labels: b:crash, 🐞 bug
