### ISSUE TITLE
[Bug] Latest nightly crashes

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#7608] opened 2020-01-10 20:38 UTC
## Steps to reproduce
Install latest nightly 
https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly/latest
Start it

### Expected behavior
not crash
### Actual behavior
crash
### Device information

* Android device: OnePlus 5t
* Fenix version: nightly

**Comment by andreicristianpetcu** [comment] 2020-01-10 20:39
Can I see the stack trace? I have adb setup locally.

**Comment by marcinwiacek** [comment] 2020-01-10 20:56
01-10 21:10:18.163 25266 25306 E AndroidRuntime: Process: org.mozilla.fenix.nightly, PID: 25266
01-10 21:10:18.163 25266 25306 E AndroidRuntime: java.lang.ExceptionInInitializerError
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at mozilla.appservices.push.LibPushFFI.<clinit>(Unknown Source:0)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at mozilla.appservices.push.PushManager.<init>(PushManager.kt:6)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at mozilla.components.feature.push.RustPushConnection.updateToken(Connection.kt:13)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at mozilla.components.feature.push.AutoPushFeature$$special$$inlined$let$lambda$1.invokeSuspend(AutoPushFeature.kt:10)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: Caused by: mozilla.appservices.support.native.IncompatibleMegazordVersion: Incompatible megazord version: library "push" was compiled expecting app-services version "0.48.1", but the megazord "fenix" provides version "0.44.0"
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at mozilla.appservices.support.native.HelpersKt.lookupMegazordLibrary(Helpers.kt:13)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at mozilla.appservices.support.native.HelpersKt.findMegazordLibraryName(Helpers.kt:4)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	at mozilla.appservices.push.LibPushFFI$Companion.<clinit>(LibPushFFI.kt:2)
01-10 21:10:18.163 25266 25306 E AndroidRuntime: 	... 9 more

**Comment by marcinwiacek** [comment] 2020-01-10 20:57
looks like dup for #7607

**Comment by cadeyrn** [comment] 2020-01-10 20:57
should be fixed by #7601 in the next build.

**Closed** 2020-01-10 20:58 UTC
Labels: 🐞 bug

**Comment by andreicristianpetcu** [comment] 2020-01-10 22:06
How can I get the stack trace? Sorry not an Android dev :) @marcinwiacek

**Comment by marcinwiacek** [comment] 2020-01-10 22:44
1. you need to enable developer options in phone and option for ADB debugging

2. you need ADB tool, for example from https://developer.android.com/studio/releases/platform-tools

3. then 

adb logcat > logfile.txt 

from command line and don't forget to disable debugging from point 1 (for any case)

Some good startup point: https://developer.android.com/studio/command-line/adb
