### ISSUE TITLE
[Bug]: incorrect youtube sizing in landscape

### ISSUE THREAD

**Issue by Tikkoneus** [mozilla-mobile/fenix#22597] opened 2021-11-25 21:24 UTC
### Steps to reproduce

1. Browse to a youtube video
2. Have screen in landscape mode

### Expected behaviour

Video should be sized correctly to fit screen.

### Actual behaviour

Video is sized larger than screen. Only the upper left 3/4 or so of the video is visible. 

If the full-screen toggle is clicked while in portrait mode then the video and the controls overlay both rotate to landscape and the video is the wrong size but the controls are the correct size (the playback bar and the fullscreen toggle are sized correctly and visible).

If the full-screen toggle is clicked after rotating the device to landscape mode then the video is the wrong size and the controls overlay is also wrongly sized (apparently to the same size as the video): the central pla/pause controls are there, but the bottom and right (time bar and fullscreen toggle) appear to be off the bottom right of the screen.

Additionally, normally a portrait-mode video sized to the width of the screen will be pinned to the top of the screen so scrolling reveals comments without scrolling the video off the top of the screen; and a normal full-screen video in landscape mode when scrolled will scroll off the top of the screen. In these affected videos the latter of those doesn't happen: in landscape mode the scroll-bar can be seen moving on the right but the enlarged video hovers over the page itself and doesn't scroll with the page.

This does not occur for all videos, but it occurs every time for videos in which it occurs at all. I don't really know how to read youtube debugging information, but one video where it was incorrectly sized showed "optimal resolution 720p60" and a video where it was correctly sized showed "optimal resolution 720p". Perhaps it only occurs with 60fps videos? Or maybe that's a red herring.

### Device name

Samsung Galaxy S21 Ultra

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

Firefox Daylight 94.1.2

### Device logs

no crash

### Additional information

This change coincided with my device's update to Android 12 / Samsung OneUI. Unfortunately, I don't know what version of Firefox I had before that so it's hard to say if the change was due to the OS update or to a Firefox update.

**Comment by Tikkoneus** [comment] 2021-11-25 21:30
I tried this on a separate device which has the same version of Firefox 94.1.2 but has Android 9 / OneUi 1.0 and discovered two things: landscape mode full-screened videos don't scroll (which they seem to in correctly-sized Android 12 videos); but are also correctly sized (videos which don't size properly on 12 do size properly on 9).

**Comment by kbrosnan** [comment] 2021-11-29 18:20
Duplicate of bz-1731980. If you can provide any more details please comment on the Bugzilla bug

**Closed by kbrosnan** 2021-11-29 18:20 UTC
Labels: 🐞 bug, needs:triage

**Comment by Darkspirit** [comment] 2021-12-17 05:30
If you open about:support in the address bar and search for "Compositing" (Main menu > Search in page), does it say "WebRender" or "WebRender (Software OpenGL)"?

**Comment by Tikkoneus** [comment] 2021-12-17 22:45
It says "WebRender", for both Android 11 (which works fine) and Android 
12 (which doesn't).
