### ISSUE TITLE
FNX-14548 ⁃ [Bug] Strictmode violation on cold startup for SharedPrefs in LeanplumMetricsService.init

### ISSUE THREAD

**Issue by sraturi** [mozilla-mobile/fenix#13368] opened 2020-08-06 20:46 UTC
There is a strict mode violation (on disk read) caused by sharedpref on startup inside `LeanplumMetricsService`

Tested on pixel 2 and samsung

*** Here are the logs from the violation

```
2020-08-06 13:40:54.156 10765-10765/org.mozilla.fenix.debug D/StrictMode: StrictMode policy violation; ~duration=20 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=196671 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1438)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:807)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:565)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:556)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:512)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:704)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:372)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
        at org.mozilla.fenix.components.metrics.LeanplumMetricsService.<init>(LeanplumMetricsService.kt:82)
        at org.mozilla.fenix.components.metrics.LeanplumMetricsService.<init>(LeanplumMetricsService.kt:57)
        at org.mozilla.fenix.components.Analytics$metrics$2.invoke(Analytics.kt:91)
        at org.mozilla.fenix.components.Analytics$metrics$2.invoke(Analytics.kt:36)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.mozilla.fenix.components.Analytics.getMetrics(Unknown Source:2)
        at org.mozilla.fenix.FenixApplication.startMetricsIfEnabled(FenixApplication.kt:231)
        at org.mozilla.fenix.FenixApplication.setupInMainProcessOnly(FenixApplication.kt:146)
        at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:93)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by liuche** [comment] 2020-08-18 18:15
This is a high priority because it's blocking automation and causing problems both on our testrunner emulators as well as on some OnePlus and Huawei devices.

**Comment by ekager** [comment] 2020-08-18 19:36
Probably related to #13229

**Comment by MarcLeclair** [comment] 2020-09-08 19:12
This has been completed, closing.

**Closed by MarcLeclair** 2020-09-08 19:12 UTC
Labels: eng:performance, hershey, 🐞 bug

**Comment by mcomella** [comment] 2020-09-14 20:21
> This has been completed, closing.

This was suppressed in https://github.com/mozilla-mobile/fenix/pull/14193 and there's a stalled WIP to fix it in https://github.com/mozilla-mobile/fenix/pull/13971. I feel like we shouldn't just accept this regression lying down and should refile suggesting it gets addressed. Then again, we have bigger fish to fry than pushing this, probably? @MarcLeclair what do you think?
