### ISSUE TITLE
[Bug] Fenix should report fenix version in crash reports

### ISSUE THREAD

**Issue by willkg** [mozilla-mobile/fenix#7245] opened 2019-12-17 16:05 UTC
## Steps to reproduce

Crash Fenix and look at crash report on Crash Stats.
Fenix currently reports the version as the GeckoView version instead of the Fenix version. Further, it doesn't report the Fenix version at all.

For example, in this crash report:

https://crash-stats.mozilla.org/report/index/e092fa61-9a27-4bd8-854a-84ac80191217#tab-metadata

The `Version` annotation is 73.0a1.

### Expected behavior

Fenix crash reports should report the Fenix version as `Version` and include the GeckoView version as a new annotation like GeckoViewVersion.

### Device information

* Android device: all
* Fenix version: all

**Comment by kbrosnan** [comment] 2020-03-06 00:14
Looking at the patch it looks like A-C will sent the app's version as the Socorro version field. @willkg will that mess with Socorro/Crash-stats design where the version has always been Gecko based?

**Comment by willkg** [comment] 2020-03-06 14:09
I think there are a couple of ways changing what `Version` is affects things.

Will changing what the `Version` value means now affect Crash Stats machinery? It'll fix existing issues. Crash Stats fully expects `Version` to be the product version--not the version of one of the libraries it uses. Crash Stats uses `Version` in computing the drop down for versions in the header,  the "featured versions" on the product page (https://crash-stats.mozilla.org/home/product/Fenix), and it's got a special field in super search. I'm +1 on this and think the sooner we fix this the better.

Will changing what the `Version` value means now affect crash analysis? Reports and other things on this data that use the Crash Stats APIs or the `socorro_crash` dataset in Telemetry will need to be fixed. I have no idea what exists out there. I don't do crash analysis myself. When this change is made, a very large and prominent announcement should be made so people know. Having said that, the value will change so much that it should be pretty obvious that something happened.

I think it was a mistake to use `Version` to mean `GeckoVersion` and the sooner this gets fixed, the less likely this becomes ingrained for all time making analysis more complex for everyone.

If there are other fields that have meanings that are drastically different from what Firefox and Firefox for Android do (https://hg.mozilla.org/mozilla-central/file/tip/toolkit/crashreporter/CrashAnnotations.yaml), we should fix those, too.

**Comment by rocketsroger** [comment] 2020-04-09 20:43
Confirmed with https://crash-stats.mozilla.com/home/product/Fenix this is now fixed.  Closing.

**Closed by rocketsroger** 2020-04-09 20:43 UTC
Labels: Feature:CrashReporting, P3, S2, 🐞 bug
