### ISSUE TITLE
[Bug] Standard "hold and swipe" gesture does not work for three dot menu

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#3720] opened 2019-06-27 18:46 UTC
Posted from [reddit](https://www.reddit.com/r/Android/comments/c65tl0/firefox_preview_100_released/es6p2ob/).

## Steps to reproduce

1. Open Fenix
2. Tap and hold on three dot menu, then drag finger down 

### Expected behavior

Menu appears. I can select an entry in the menu when removing finger when it is highlighted. This feels basically like how classic Mac OS used to work, or how menus in Windows work if using click and hold (like how classic Mac OS used to work). 

### Actual behavior

Menu does not appear.

### Device information

* Android device: Pixel 2
* Fenix version: latest

**Comment by NotWoods** [comment] 2019-06-27 22:01
Duplicate of mozilla-mobile/android-components#3587.

Thanks for pointing it out 😄

**Closed by NotWoods** 2019-06-27 22:01 UTC
Labels: Feature:Android Integration, Feature:Main menu ⋮, 🐞 bug
