### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by Xi-PP** [mozilla-mobile/fenix#24545] opened 2022-03-31 16:46 UTC
[comment]: # add gradient theme on dark mode, violet & blue or some attractive color. Or add option to theme manually like telegram app

### What is the user problem or growth opportunity you want to see solved?
Normal dark colour and the non transparent status is looks boring. Make this browser look more attractive as well as privacy focused.
### How do you know that this problem exists today? Why is this important?
Looks are matter!
### Who will benefit from it?
Every user will get benifit.

**Comment by unforgettableid** [comment] 2022-04-01 17:44
Likely a duplicate of #10032.

@Xi-PP:  Thank you for filing this feature request!  Next time, before you send in a feature request, please try to search for duplicate copies.  This will help to save time for the Mozilla staff.  :)

**Comment by delia-pop** [comment] 2022-04-04 11:20
Hello, @Xi-PP, 
Thank you for the suggestion. I will mark this ticket as a feature request, if case this is something to be taken into consideration in the future.

**Closed** 2022-04-04 11:23 UTC
Labels: needs:triage
