### ISSUE TITLE
[Bug] Blank oage without any responses after closing all the tabs

### ISSUE THREAD

**Issue by TheMadRuffian** [mozilla-mobile/fenix#4937] opened 2019-08-27 01:58 UTC
### Device information: Xiaomi Mi A1, Android 10 beta 6

* Android device: Yes
![Screenshot_20190827-095002](https://user-images.githubusercontent.com/42994263/63735067-29f1f480-c8b1-11e9-9179-4b43b7031db1.png)

* Fenix version:  Nightly 190826 18:07

**Comment by ekager** [comment] 2019-09-17 04:19
Could you clarify what you mean by "close all tabs quickly"? Are you swiping them from the homescreen?

**Comment by ekager** [comment] 2019-09-17 04:23
Closing as a dupe of #4788

**Closed by ekager** 2019-09-17 04:23 UTC
Labels: 🐞 bug
