### ISSUE TITLE
FNX-5464 ⁃ Support for Android API 19..?

### ISSUE THREAD

**Issue by dwaal** [mozilla-mobile/fenix#2112] opened 2019-04-27 21:00 UTC
### Why/User Benefit/User Problem
Users with Android 4.4 could use Fenix

### What / Requirements
Change API Level to 19 (from 21)

I tried to revert the codebase to API Level 19. It seemed like a lot of changes since all mozilla-libs are Level 21. I doubt this is really necessary in most places since Firefox still supports Level 19 and they both share a lot of code.

Maybe you thought it wouldn't really affect a lot of people by switching to 21 and probably it is a little bit of a hassle to still support 19.
On the other hand one could argue that you could make the switch to Level 23 or even 24 without excluding too many users and saving a lot of tedious workarounds to support older API Levels. Also, everybody excluded could still use Firefox.

I doubt you will switch to 19 but at least I wanted to give it a shot by telling you that a lot of Android 4.4 users are still out there, especially in poorer areas of the world.

**Comment by kbrosnan** [comment] 2019-04-27 21:05
Dupe of #2100

**Closed** 2020-08-11 13:59 UTC
