### ISSUE TITLE
UI Tests for (beta) releases incorrectly use the nightly/debug build variant

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#16120] opened 2020-10-22 13:43 UTC
We created the `releases/v83.0.0` branch and landed the update to use A-C `63.0.0`. This resulted in a lot of UI test failures, that we had not seen before.

After investigaging, it turn ous that the UI tests that run on the beta releases are actually run against the nighly/debug build variant, which uses the _next_ GV version and not the version that we built the beta release with.

I think the short version is this: for builds on the release branches, we need to run tests against the correct GV version.

cc @JohanLorenzo

**Comment by csadilek** [comment] 2020-10-28 20:27
The problem we have is that UI tests run against the debug build type by default, and the debug build type/variant is configured to use GV Nightly.

Solution 1: Use [testBuildType](https://developer.android.com/studio/build/gradle-tips#change-the-test-build-type) to configure which build type to use for tests. Then configure [CI](https://github.com/mozilla-mobile/fenix/blob/c93a29f89a25bd0dc0f966deebcfa9e52a36aed5/taskcluster/ci/ui-test/kind.yml#L14) to upload the right APK. Unfortunately, we're seeing issues with `testBuildType`: 
  - It only seems to work as a global configuration which will break when running tests from Android Studio on the beta/release branch (this may be acceptable)
  - We're running into build errors caused by R8. The problem is described in this [ticket](https://issuetracker.google.com/issues/122924648) and more recently [here](https://issuetracker.google.com/issues/140851070). I've already tried upgrading to latest R8 but still running into issues transforming classes. We could introduce separate build variants for testing beta/release and set `minifyEnabled` to false (turn off R8), but then we might as well use the debug build type and reconfigure it instead?

Solution 2: On beta branches, configure the debug build type to use beta. Here's an [example](https://github.com/csadilek/fenix/commit/999c3a2a46dec6b8d2f05467b4ea1d035f516e18). This wouldn't need any changes to CI and another advantage is that testing on the branch locally would use the right GV by default. It's not perfect, but it solves our problem for now?

@pocmo @JohanLorenzo @st3fan wdyt?

**Comment by isabelrios** [comment] 2020-11-05 13:17
Please let me add my two cents here since sometime ago I worked on trying similar scenario to get tests running on Nightly, not debug build. I started with Solution 1, and now I tried what I did before but for beta:

> Solution 1: Use testBuildType to configure which build type to use for tests. Then configure CI to upload the right APK. Unfortunately, we're seeing issues with testBuildType:

That's right, adding this line: `testBuildType "beta"` in build.gradle file after the buildTypes definition will work adding the fix below to R8 erros.

>     It only seems to work as a global configuration which will break when running tests from Android Studio on the beta/release branch (this may be acceptable)
>     We're running into build errors caused by R8. The problem is described in this ticket and more recently here. I've already tried upgrading to latest R8 but still running into issues transforming classes. We could introduce separate build variants for testing beta/release and set minifyEnabled to false (turn off R8), but then we might as well use the debug build type and reconfigure it instead?

To get rid of this error I had to add `-dontoptimize` to the proguard-rules.pro file. I don't know if that could be an option but found that and use it while doing some testing.

With that I got `org.mozilla.firefox_beta` and `org.mozilla.firefox_beta.test` apks which in theory would be the necessary apks to run tests on Firebase. 
Unfortunately, while trying with similar nightly apks, even though the app was launched on Firebase, it was crashing. We created a gcloud VM to run directly the command to upload and run the tests in Firebase. There were errors realted to unkown signature. 
Locally I can run the tests fine on beta from Android Studio.

I have not tried to run the tests on Firebase with those beta apks yet, but I guess the error will be the same. Once I do that I will update the comment if there is something different that could help.

**Comment by isabelrios** [comment] 2020-11-10 18:26
I would like to share a small update in case that's helpful. Finally, with the changes mentioned in previous comment, and those apks, tests are running on Firebase for Fenix Beta. Link to the [Firebase build](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.8aa02013b8194c9b/matrices/7375632177329020552/executions/bs.7c647e681ee24d84/videos)

Need to investigate why tests are failing, but if you see the video, the app is launched and tests start. It shows Firefox Browser and Welcome to Firefox Beta message.

To be honest, I don't know if we could apply those changes and how to manage that for only the beta/release builds and no the current builds. But thought I should share that progress while thinking about that.

**Comment by st3fan** [comment] 2020-11-13 15:51
That is great news!

> To be honest, I don't know if we could apply those changes and how to manage that for only the beta/release builds and no the current builds. But thought I should share that progress while thinking about that.

I think we need some releng help to do those changes conditionally for integrations that run on the release branch. Going to talk a bit more about that to see what can be done there.

**Comment by JohanLorenzo** [comment] 2020-11-18 13:56
For the record, I chatted with @pocmo, @st3fan, @csadilek, and @MihaiTabara last Friday. We weren't sure what how to tackle this. @isabelrios scheduled a meeting with me tomorrow.

**Comment by isabelrios** [comment] 2020-12-04 17:25
Some more news on this issue, hopefully good news 🤞 
Thanks to @pocmo who added the changes mentioned in previous comment above as [flags](https://github.com/mozilla-mobile/fenix/pull/16787) and to @JohanLorenzo who managed to put together the changes needed on TC, tests can run on Fenix Beta on Firebase now. 

As you can see in this [PR](https://github.com/mozilla-mobile/fenix/pull/16786), there are debug and beta tests in the tasks, each one using [Fenix Preview](https://github.com/mozilla-mobile/fenix/pull/16786/checks?check_run_id=1499491355) or [Fenix Beta](https://github.com/mozilla-mobile/fenix/pull/16786/checks?check_run_id=1499491353). 

So far it is defined so that debug tests keep working as they are per Github-push and Github-pr and beta tests will run per Github-push.

Do you think this will help solving this original issue or similar in the future? We would like to hear your feeback about this @st3fan @csadilek . Thanks!
cc @AaronMT @rpappalax

**Comment by isabelrios** [comment] 2021-01-18 15:10
I think we can close this issue now. Related PRs mentioned above landed both in master and release branch (v_85.0.0).
Now on release branches we will have a task: `ui-test-x86-beta` which will run the [UI tests using the beta build]( https://github.com/mozilla-mobile/fenix/runs/1721575848) not the nightly/debug.
On master we still have `ui-test-x86-debug` which will work as usual, running UI tests against debug build. This task will not run in release branches.

If something is still pending or not working as desired please re-open or open a new follow up issue. Thanks!

**Closed by isabelrios** 2021-01-18 15:10 UTC
Labels: eng:automation, eng:build, eng:ui-test
