### ISSUE TITLE
[Bug] Twitter asks to turn on notifications when already enabled

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#16411] opened 2020-11-06 02:05 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Log into Twitter.
2. Go to Settings > Push notifications.
3. Toggle the switch on.
4. Observe the Fenix site permissions prompt that asks for permission.
5. Click 'Always'.
6. Toggle the switch off then on again.
5. Observe the page.

### Expected behaviour
 - At 7, we should either see the twitter notification settings because the site permissions already allow twitter.com OR we are prompted again to allow site permissions.

### Actual behavior
- At 7, Twitter says to enable notifications from browser settings but we are never prompted for it.

### Device information

* Android device: Android 11, Pixel 4
* Fenix version: Nightly, 201105 17:04 (Build #2015773899)

**Comment by Amejia481** [comment] 2020-11-12 19:56
The issue is address on https://github.com/mozilla-mobile/android-components/pull/8944 and It will be fixed when Fenix update to the new ac version.

**Comment by Amejia481** [comment] 2020-11-17 14:46
QA team could you please help us to verify if this is still reproducible in nightly ?

**Comment by jonalmeida** [comment] 2020-11-17 17:53
I just tested this out and it works for me now. :)

**Comment by ebalazs-sv** [comment] 2020-11-18 14:49
Verified as fixed on the latest Nightly 201118 05:01 (Build #2015776297) GV 85 from 11/18 with Pixel 2 (Android 9).
I will close this issue and remove the qa:needed label.

**Closed by ebalazs-sv** 2020-11-18 14:49 UTC
Labels: Feature:Push, eng:qa:needed, needs:triage, 🐞 bug
