### ISSUE TITLE
[Bug] Private Theme is not applied correctly when opening from external app

### ISSUE THREAD

**Issue by Meshikhah** [mozilla-mobile/fenix#18496] opened 2021-03-16 11:11 UTC
## Steps to reproduce
Enable open external link in private tab
Open a link from twitter then open it in Firefox nightly.
Open Enhanced tracking protection.

### Expected behavior
it should be readable 
### Actual behavior
It is white and unreadable
<img src=https://user-images.githubusercontent.com/29687018/111299516-42795980-8665-11eb-8d38-863f99a65082.jpg width = 45%>
### Device information

* Device vendor / model and Android version: ? j7 prime
* Firefox for Android version: ? (go to Settings -> About Firefox) 
Firefox Nightly 210315 17:01 (Build #2015798857)
AC: 74.0.20210313190118, 05dcfd7b3
GV: 88.0a1-20210313094300
AS: 73.0.1

**Comment by mcarare** [comment] 2021-03-18 11:33
I have not been able to reproduce this. Can QA also take a look? Thank you!

**Comment by abodea** [comment] 2021-03-19 15:45
I was not able to reproduce this issue on the latest Nightly 3/19 with Google Pixel 4 XL (11), Samsung Galaxy S10+ (10), Samsung Galaxy S7 (7).
Note that I tried with light and dark them setup but with 0 success on reproducing it.
@Meshikhah  can you please provide more information and also a video/gif?
Until further notice, I will remove `eng:qa:needed`.

**Comment by Meshikhah** [comment] 2021-03-21 21:57
@abodea i can't record the screen because it opens in private tab.

**Comment by Amejia481** [comment] 2021-03-22 13:31
@Meshikhah you can enable this under **Settings** -> **Private Browsing** -> **Allow screenshots in private browsing**.

**Comment by Meshikhah** [comment] 2021-03-22 13:39
Here is the [video](http://imgur.com/gallery/GmGTJp6)

**Comment by mcarare** [comment] 2021-03-24 13:31
@Meshikhah Thank you for the video!
I still cannot reproduce this following the steps in shown. 
What setting do you have for Theme? Does this reproduce with other settings for Theme options? Thank you.

**Comment by Meshikhah** [comment] 2021-03-24 13:57
@mcarare I am using light theme. And i have enabled "open links in private tab"

**Comment by mcarare** [comment] 2021-03-24 14:12
@Meshikhah What Android version does your J7 prime phone have?

**Comment by Meshikhah** [comment] 2021-03-24 14:13
Andorid 8.1.0

**Comment by sflorean** [comment] 2021-03-24 14:40
I was able to reproduce this issue on Nightly 3/24, following the steps/video with LG G7 Fit (Android 8.1.0).

**Comment by mcarare** [comment] 2021-03-25 11:49
Also noticed that stats bar color is also wrong, not just the preference screen background.

**Comment by mcarare** [comment] 2021-03-26 12:05
Eng note:  When switching from external app to browser fragment the `windowBackground` is the one from the current theme applied to the app (light or dark) and not from the private theme. This is the color used for the preference screen background and it's the color displayed on the status bar since the status bar is transparent.

**Comment by mcarare** [comment] 2021-04-19 10:33
Reopened for QA.

**Comment by ebalazs-sv** [comment] 2021-04-20 14:08
Verified as fixed on Nightly 4/20 with Motorola Moto G6 (Android 8).

**Closed by ebalazs-sv** 2021-04-20 14:08 UTC
Labels: Feature:PrivateBrowsing, Feature:Themes, b:a11y, eng:qa:needed, qa-triaged, 🐞 bug
