### ISSUE TITLE
[Bug] Some GIFs on old reddit don't animate

### ISSUE THREAD

**Issue by marthinwurer** [mozilla-mobile/fenix#15797] opened 2020-10-09 07:03 UTC
## Steps to reproduce
Go to: 
https://old.reddit.com/r/dataisbeautiful/comments/j7pj62/oc_one_hour_of_active_satellites_orbiting_earth/

### Expected behavior
The animation plays

### Actual behavior
It doesn't

### Device information

* Android device: S8
* Fenix version: 81.1.1 (Build #2015764547)
AC: 57.0.6, bdbd5ccfd
GV: 81.0-20200917005511
AS: 61.0.13

**Comment by kbrosnan** [comment] 2020-10-09 16:30
The default setting of Firefox is to block video and audio playback. 

* in Firefox
* Tap 3 dot menu
* Settings
* Site permissions
* Autoplay
* Choose either of the other options

Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/8987

**Closed by kbrosnan** 2020-10-09 16:30 UTC
Labels: needs:triage, 🐞 bug
