### ISSUE TITLE
Allow users to manually reorder pinned shortcuts

### ISSUE THREAD

**Issue by ris58h** [mozilla-mobile/fenix#28363] opened 2023-01-02 19:26 UTC
### What is the user problem or growth opportunity you want to see solved?
Pinned shortcuts can't be reordered.

### How do you know that this problem exists today? Why is this important?
Pinned shortcuts reordering seems natural. 

### Who will benefit from it?
Users who pin shortcuts.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22215)

**Comment by neonota** [comment] 2023-01-03 08:09
+1

**Comment by cadeyrn** [comment] 2023-01-03 11:27
Duplicate of #20068.

**Closed** 2023-01-09 16:08 UTC
Labels: needs:triage
