### ISSUE TITLE
[Bug] "open link PB mode Fenix" and hit back, IllegalStateExceptionandroidx.fragment.app.FragmentManager in ensureExecReady, FragmentManager has been destroyed

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#8374] opened 2020-02-13 09:26 UTC
6/3 UPDATE
There's a recent significant spike of this crash in Nightly starting May, 19:
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6457309/

Various cases of this fixed before: https://github.com/mozilla-mobile/fenix/issues?q=is%3Aissue+FragmentManager+has+been+destroyed+is%3Aclosed

-----

## Steps to reproduce
1. start Fenix
2. switch into PB mode
2. go to devices launcher
3. open a PWA

### Expected behavior
The PWA will be launched

### Actual behavior
The PWA activity appears briefly, but then fenix crashes.

### Logcat
```
02-13 10:18:37.498 22826 22899 W FirefoxAccountStateMachine: Got invalid event Event$Init for state AuthenticatedWithProfile.
02-13 10:18:37.524  1929  3234 I InputDispatcher: Focus entered window: Window{e806487 u0 org.mozilla.fenix.nightly/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity}
02-13 10:18:37.530  1929  3234 I ActivityManager: Displayed org.mozilla.fenix.nightly/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity: +333ms (total +608ms)
02-13 10:18:37.531  1929  3234 I ActivityManager: Fully drawn org.mozilla.fenix.nightly/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity: +333ms (total +608ms)
02-13 10:18:37.551 22826 22826 D GeckoSession: handleMessage GeckoView:PageStart uri=about:blank
02-13 10:18:37.555 22826 22826 D GeckoSession: handleMessage GeckoView:LocationChange uri=about:blank
02-13 10:18:37.555 22826 22826 D GeckoSession: handleMessage GeckoView:PageStop uri=null
02-13 10:18:37.556 22826 22826 D GeckoSession: handleMessage GeckoView:OnLoadRequest uri=https://web.telegram.org/?utm_source=web_app_manifest
02-13 10:18:37.559 22826 22826 D GeckoSession: handleMessage GeckoView:OnLoadRequest uri=https://web.telegram.org/?utm_source=web_app_manifest
02-13 10:18:37.571 22826 22826 W GeckoEventDispatcher: No listener for GeckoView:AccessibilityEnabled
02-13 10:18:37.573 22826 25271 D SessionStorage/AutoSave: Saved state to disk [446ms]
02-13 10:18:37.577 22826 22885 D GeckoScreenOrientation: unlocking
02-13 10:18:37.696 22826 22899 W FirefoxAccountStateMachine: Got invalid event Event$Init for state AuthenticatedWithProfile.
02-13 10:18:37.711 22826 22826 W DecorView[]: The visibility of the navigation bar is low, color=ffffffff, hasLightNavBar=false
02-13 10:18:37.732  1929  3800 I InputDispatcher: Focus entered window: Window{7a586aa u0 org.mozilla.fenix.nightly/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity}
02-13 10:18:37.752 22826 22826 D AndroidRuntime: Shutting down VM
02-13 10:18:37.753 22826 22826 E AndroidRuntime: FATAL EXCEPTION: main
02-13 10:18:37.753 22826 22826 E AndroidRuntime: Process: org.mozilla.fenix.nightly, PID: 22826
02-13 10:18:37.753 22826 22826 E AndroidRuntime: java.lang.IllegalStateException: FragmentManager has been destroyed
02-13 10:18:37.753 22826 22826 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:4)
02-13 10:18:37.753 22826 22826 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1)
02-13 10:18:37.753 22826 22826 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
02-13 10:18:37.753 22826 22826 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
02-13 10:18:37.753 22826 22826 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-13 10:18:37.753 22826 22826 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:280)
02-13 10:18:37.753 22826 22826 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6744)
02-13 10:18:37.753 22826 22826 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-13 10:18:37.753 22826 22826 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-13 10:18:37.753 22826 22826 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-13 10:18:37.754 22826 22885 D GeckoScreenOrientation: unlocking
```

### Device information

* Android device: SONY Xperia 10 Android 9
* Fenix version: Nightly 2002112 18:00 (Build #20431806) 32.0.0, 747da16b0

**Comment by ValentinTimisica** [comment] 2020-02-21 10:49
I tried to reproduce this but for me the PWA opens and functions correctly. Can someone from QA try to reproduce this?

**Comment by sv-sdeiac** [comment] 2020-02-21 14:23
I tried to reproduce this issue but without any success.
The PWA is working properly and any crash is presented.

Devices:
- Samsung Galaxy S8 (Android 9);
- OnePlus 6T (Android 9);
- Google Pixel 3a (Android 9).
Build: Firefox Preview Nightly 2/21 #20520606.

**Comment by TitanNano** [comment] 2020-02-25 22:22
I also can no longer reproduce this.

**Comment by ekager** [comment] 2020-02-26 06:33
Closing as fixed

**Comment by AndiAJ** [comment] 2020-02-26 09:48
Hi, Still reproducible on the latest **`Nightly Build #20570604 from 02/26`** using the following devices:
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

❗ Not reproducible on Google Pixel 3a (Android 9)

► Video
![20200226-113451 (1)](https://user-images.githubusercontent.com/51314259/75332912-de36fc80-588d-11ea-86c6-71910bed2cdb.gif)

► Crashlog
```kotlin
  --------- beginning of crash
2020-02-26 11:35:06.682 29357-29357/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 29357
    java.lang.RuntimeException: Unable to resume activity {org.mozilla.fenix.nightly/org.mozilla.fenix.nightly.App}: java.lang.RuntimeException: Failed to call observer method
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4278)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4319)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2065)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
     Caused by: java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:6)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:2)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:1)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:1)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:9)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:12)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:7)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:108)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:218)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:14)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:108)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:218)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:18)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
        at android.app.Activity.performStart(Activity.java:7364)
        at android.app.Activity.performRestart(Activity.java:7439)
        at android.app.Activity.performResume(Activity.java:7444)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4246)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4319) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2065) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7555) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963) 
     Caused by: java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity Other activity: ExternalAppBrowserActivity
        at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:17)
        at mozilla.components.feature.session.EngineViewPresenter.renderSession$feature_session_release(EngineViewPresenter.kt:1)
        at mozilla.components.feature.session.SessionFeature.start(SessionFeature.kt:6)
        at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.start$support_base_release(ViewBoundFeatureWrapper.kt:1)
        at mozilla.components.support.base.feature.LifecycleBinding.start(ViewBoundFeatureWrapper.kt:1)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:4)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:2) 
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:1) 
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:1) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3) 
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:9) 
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:12) 
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5) 
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2) 
        at androidx.fragment.app.Fragment.performStart(Fragment.java:7) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:108) 
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:218) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3) 
        at androidx.fragment.app.Fragment.performStart(Fragment.java:14) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:108) 
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:218) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3) 
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:18) 
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340) 
        at android.app.Activity.performStart(Activity.java:7364) 
        at android.app.Activity.performRestart(Activity.java:7439) 
        at android.app.Activity.performResume(Activity.java:7444) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4246) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4319) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2065) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7555) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963) 
     Caused by: java.lang.IllegalStateException: Display already acquired
        at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:5)
2020-02-26 11:35:06.682 29357-29357/? E/AndroidRuntime:     at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:7)
        at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:10)
        	... 39 more
2020-02-26 11:35:06.683 29357-29357/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.RuntimeException: Unable to resume activity {org.mozilla.fenix.nightly/org.mozilla.fenix.nightly.App}: java.lang.RuntimeException: Failed to call observer method, breadcrumbs=[Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 11:34:40 GMT+02:00 2020), Breadcrumb(message=Changing to fragment settingsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 11:34:43 GMT+02:00 2020), Breadcrumb(message=Changing to fragment privateBrowsingFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 11:34:44 GMT+02:00 2020), Breadcrumb(message=Changing to fragment settingsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 11:34:54 GMT+02:00 2020), Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 11:34:55 GMT+02:00 2020), Breadcrumb(message=Changing to fragment externalAppBrowserFragment, isCustomTab: true, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 11:34:58 GMT+02:00 2020), Breadcrumb(message=Changing to fragment externalAppBrowserFragment, isCustomTab: true, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 11:35:06 GMT+02:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 11:35:06 GMT+02:00 2020)])
2020-02-26 11:35:06.683 29357-29357/? I/mozac/CrashReporter: Showing prompt
```

**Comment by ekager** [comment] 2020-02-26 15:59
Thanks @AndiAJ ! Slightly different trace now but that's good info to keep looking into

**Comment by ekager** [comment] 2020-04-18 00:01
With the original STR I'm still seeing on my Pixel 

> 2020-04-17 17:00:54.708 18721-18721/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: org.mozilla.fenix.debug, PID: 18721
>     java.lang.IllegalStateException: FragmentManager has been destroyed
>         at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1783)
>         at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1843)
>         at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
>         at android.os.Handler.handleCallback(Handler.java:883)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7356)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by kbrosnan** [comment] 2020-05-27 01:24
This seems to be related to one of the most common signatures we are seeing on Nightly. Crash in [@ java.lang.IllegalStateException: at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java)] [bug 1641040](https://bugzilla.mozilla.org/show_bug.cgi?id=1641040)

**Comment by liuche** [comment] 2020-06-03 15:03
I'm going to dupe these to #10709, and I've moved STRs over bc these all have the same crash signature.

**Comment by liuche** [comment] 2020-06-03 17:36
My bad, this is not the same bug as #10709, will do some un-duping.

**Comment by liuche** [comment] 2020-06-03 17:38
This is currently our top crasher on Firefox Beta at 5% rollout: https://crash-stats.mozilla.org/topcrashers/?product=Fenix&version=77.0.0-b

and on Firefox Preview too, top crashes 1 & 2 with an uptick in the past few days:
https://sentry.prod.mozaws.net/operations/fenix/?query=release%3Aorg.mozilla.fenix-5.1.0&sort=priority&statsPeriod=14d

(crash-stats link for reference) https://crash-stats.mozilla.org/topcrashers/?product=Fenix&version=5.1.0-b

also updating the title to make this more searchable by crash signature.

**Comment by st3fan** [comment] 2020-06-03 18:20
@grigoryk @NotWoods what do you think of this one?

**Comment by liuche** [comment] 2020-06-03 18:28
fwiw this is probably some kind of race, bc this STR has been around for a while, but has really [spiked on Nightly as of May 19](https://crash-stats.mozilla.org/signature/?product=Fenix&version=0.0a1&signature=java.lang.IllegalStateException%3A%20at%20androidx.fragment.app.FragmentManager.ensureExecReady%28FragmentManager.java%29&date=%3E%3D2020-05-03T18%3A18%3A00.000Z&date=%3C2020-06-03T18%3A18%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#graphs).

**Comment by kbrosnan** [comment] 2020-06-03 19:44
From: https://www.reddit.com/r/firefox/comments/gvaru6/firefox_preview_nightly_still_crashing_on_samsung/

> I have been running the Joey Reddit app as a standalone app and I will occasionally open a post externally in Firefox Preview Nightly to bookmark it. Then I hit the back button twice to go back to the Joey app and as soon as it goes back, I get the message that Firefox has crashed. I tried to duplicate the problem just now and I wasn't able to. It only occasionally happens.

**Comment by liuche** [comment] 2020-06-03 20:59
@ekager backx2? #10718

**Comment by liuche** [comment] 2020-06-04 17:43
@grigoryk if you're looking into this, might be related to app restarts when swapping themes (because Private Browsing is a separate theme and requires application recreate to apply).

Chatted w/ @boek and @ekager about one solution being, removing the PB theming and instead, dynamically setting UI colors for PB Mode.

**Comment by ekager** [comment] 2020-06-04 17:46
Yeah the backx2 issue was #10718 🤔

**Comment by st3fan** [comment] 2020-06-04 18:07
@ekager this landed on the 18th and fits the STR https://github.com/mozilla-mobile/fenix/commit/d46369696f1d43385f335936f50abb31176845ef

**Comment by ekager** [comment] 2020-06-04 18:12
Yes, I'm convinced that the spike is related to https://github.com/mozilla-mobile/fenix/commit/d46369696f1d43385f335936f50abb31176845ef but think it is just exposing another pathway to an issue that already existed when finishing activities (ie the previous STR also involved "open in Fenix" which finishes an activity). There's clearly another root issue at play here - probably some race condition as the activity finishes, but for now we can revert the finish.

**Comment by ekager** [comment] 2020-06-04 18:22
I just repro-ed the crash on the original STR. 
1. Have Fenix open in PBM 
2. Background Fenix, Open PWA
3. Click away from main PWA scope to get toolbar 
4. Select "Open in Fenix" from toolbar 

Took me about 10-15 tries and then reproed a second time as well.

**Comment by liuche** [comment] 2020-06-04 19:12
@ekager does this still repro with the backout?

**Comment by liuche** [comment] 2020-06-05 00:01
A few things we decided to do here for this bug:
- for 5.1, made a 5.1.1 branch with a backout of https://github.com/mozilla-mobile/fenix/commit/d46369696f1d43385f335936f50abb31176845ef - this means that #10718 will show up again in that build
- on master, #11240 will add some crash checks and then we'll monitor to see if this crash decreases on Nightly

**Comment by softvision-miralobontiu** [comment] 2020-06-05 09:36
I was able to reproduce the crash on OnePlus 5T (Android 9) on 6/5 Nightly build, with the following steps:
1. Sign in with valid credentials, with an old account.
2. Open several tabs (I had 10).
3. Share all opened tabs to all the connected devices.
Fenix either crashes or displayed the "Unable to send RETRY" snackbar.

https://crash-stats.mozilla.org/report/index/4e6c3a43-8992-4286-bed1-701680200605

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4735165/logcat.txt)

**Comment by sv-ohorvath** [comment] 2020-06-05 14:32
> I just repro-ed the crash on the original STR.
> 
> 1. Have Fenix open in PBM homescreen
> 2. Background Fenix, Open PWA
> 3. Click away from main PWA scope to get toolbar
> 4. Select "Open in Fenix" from toolbar
> 
> Took me about 10-15 tries and then reproed a second time as well.

I got an ANR error with these steps on 77.0.0-beta2.
[logANR.txt](https://github.com/mozilla-mobile/fenix/files/4736656/logANR.txt)

**Comment by liuche** [comment] 2020-06-05 19:43
@softvision-miralobontiu I think this might be a different bug, but is also fragmentmanager related.

Stack trace here specifically is `java.lang.IllegalStateException: FragmentManager has been destroyed
androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:4)
androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1)`

**Comment by liuche** [comment] 2020-06-11 16:06
I've been seeing this crash somewhat consistently:
STR:

Have open links in Private Browsing turned on
Open a link from another app (like from gmail)
Background the app

Crash seems to happen at some point afterwards. No "triggering' steps though.
Maybe related to PB mode notification? Re-opening after crash is still in PB mode (so is the theme not changing?).

**Comment by ekager** [comment] 2020-06-18 13:54
@liuche with those step, I can repro on Nightly ~1/5 times, but I'm seeing a native crash (id bc606679-2815-41ea-9c81-e0b87e3809fb) , not this FragmentManager trace :/

**Comment by liuche** [comment] 2020-06-18 17:09
I also just repro-ed this on the most recent Nightly, and I'm also getting a native crash, here's the socorro link: https://crash-stats.mozilla.org/report/index/c2d90164-a401-4802-bd6d-7658f0200618

Not sure why it changed.

**Comment by ekager** [comment] 2020-06-19 00:32
I was able to repro the fragmentmanager crash once, but of the 5 times I crashed with similar STR to https://github.com/mozilla-mobile/fenix/issues/8374#issuecomment-642777126, 4 were the native crash

**Comment by liuche** [comment] 2020-06-26 16:33
Do we know why this was a native crash sometimes - is it two issues somehow, and we're only handling one of them? Or the native crash is getting triggered racily.

**Comment by sv-ohorvath** [comment] 2020-06-30 10:05
We've tried the steps to reproduce this on Fenix Beta 78.0.1 & 79.0.1 and looks like it is fixed. Marking this as fixed and closing.

**Closed by sv-ohorvath** 2020-06-30 10:05 UTC
Labels: b:crash, eng:qa:needed, eng:ready, help wanted, 🐞 bug
