### ISSUE TITLE
[Bug] youtube.com - Footer bar is not at the bottom when turn in landscape mode

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16425] opened 2020-11-06 14:09 UTC
## Steps to reproduce
1. Open the firefox beta
2. Go to youtube.com
3. Scroll down and up till footer bar appear
4. Turn the phone to landscape mode
5. Scroll down
### Expected behavior
When turned phone to landscape mode, the footer bar will be displayed at the very bottom
### Actual behavior
When turning to landscape mode, the bar is not displayed at the very bottom
### Device information
 Xiaomi Redmi Note 4X - Android 7.0,
Vestel Venüs V3 (Andoid 6.0.1)
* Android device: yes
* Fenix version: firefox beta 82.0.0
 
![image](https://user-images.githubusercontent.com/66958331/98375129-c20d7100-2052-11eb-9c69-c650ff0750ff.png)

**Comment by s-ankur** [comment] 2020-11-06 18:42
Seems to be fixed in Nightly, can you confirm?

**Comment by BigSamSampson** [comment] 2020-11-09 06:38
Hi, bug continues in Nightly
![3](https://user-images.githubusercontent.com/66958331/98507402-8ea72e00-226e-11eb-9c3f-1817dfdfc23e.PNG)
![image](https://user-images.githubusercontent.com/66958331/98507440-a7afdf00-226e-11eb-8ca9-d26d2b71db3c.png)

**Comment by ekager** [comment] 2020-12-18 06:58
Can you still reproduce this? Do you have the toolbar set to top or bottom?

**Comment by Mugurell** [comment] 2021-02-02 15:36
I think this was a very short lived bug that is by now fixed.
Closing the ticket.

@BigSamSampson If you still encounter this issue or similar please update and we'll investigate more.

**Closed by Mugurell** 2021-02-02 15:36 UTC
Labels: b:web-content, 🐞 bug
