### ISSUE TITLE
[Bug] OOM / TransactionTooLargeException / corrupt BrowserState when opening a big data url

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#7341] opened 2019-12-23 11:00 UTC
Taken from: https://bugzilla.mozilla.org/show_bug.cgi?id=1605630

## Steps to reproduce
User Agent: Mozilla/5.0 (Android 10; Mobile; rv:71.0) Gecko/71.0 Firefox/71.0

Steps to reproduce:

Using the build #13502256 of Firefox Preview 3.0.1 on my Google Pixel 3 running Android 10 build QQ1A.191205.008, I went onto this site: https://www.color-blindness.com/coblis-color-blindness-simulator/ , set it to desktop mode, and uploaded the attached image of my home screen. Then I set the desired simulation filter to the "green-weak" option. To try to save the image, I clicked the "Open simulated image in new window" link. I performed this bug a 2nd time on the same Preview version and on Preview Nightly 191221 18:00 (Build #13551810) as well.

### Expected behavior
Expected a new tab to be created with just the image so I could hold and save the image.

### Actual behavior
After creating a new tab from the link, the entire app locked up. Force closing the app and restarting my device did not change anything and the browser would freeze up in an instant upon launching.

**Comment by Diana-Rus** [comment] 2019-12-23 11:24
Environment
Device: Google Pixel 3a XL (Android 10)
Build: Firefox Preview Nightly 191220 (Build #13540608) with GV: 73.0a1-20191216095052

The STR are:
1. Open Firefox Preview browser.
2. Go to: https://www.color-blindness.com/coblis-color-blindness-simulator/ .
3. Tap on the "3 dots" from bottom right corner.
4. Enable "Desktop Site" option.
5. Tap on the "Browse" button and choose the image you want to change.
6. Choose "Green-Week/Deuteranomaly".
7. Refresh the page.
8. Choose again the same image.
9. Tap on the link generated "Open simulated image in new window".

Expected Result:
The image is correctly displayed in the new window. A context menu is displayed.

Actual Result:
- I did encounter a lag in the image being displayed.

Notes:
- In case of long tapping on the tab with the image in order to download, a crash was present.
- Please check [video](https://drive.google.com/open?id=1hCiQepdGSVHq31lgq166iO_YurC954zw).
- After reopening the browser, takes a couple of seconds to have the opened tabs displayed.
- I also encountered a crash after reopening the application with the same tabs present and wanting to make an action as tapping on the "Menu".

**Comment by Diana-Rus** [comment] 2020-03-10 10:07
Hi, unfortunately the issue is still reproducible. No new tab present. Crash is still present.
Build: Firefox Preview Nightly 200310 (Build #20700606) GV:75.0a1-20200309091841
Devices: One Plus 7T Pro(Android 10), Samsung Galaxy S8+ (Android 8) and Sony Xperia Z5 (Android 7)

GIF - Sony Xperia Z5 (Android 7)
![20200310-112834](https://user-images.githubusercontent.com/49859863/76301744-750cab80-62c7-11ea-8e40-8b0665f8fab8.gif)

GIF - One Plus 7T Pro(Android 10)
![20200310-120039](https://user-images.githubusercontent.com/49859863/76301752-78a03280-62c7-11ea-9fe4-02ff7daf9a06.gif)

Note: I will attach logcat [Crash.txt](https://github.com/mozilla-mobile/fenix/files/4311590/Crash.txt)  maybe will help in solving the issue.

**Comment by Mugurell** [comment] 2020-03-31 16:11
This is the old humongous data url issue.
The `Open simulated image in new window` links to a `data:image/png;base64...` url.
This could definitely cause a `TransactionTooLargeException` or `OutOfMemoryException` 
Corrupting app's state / session so that the user has to clear app data / reinstall makes this particularly bad.
I think we should check data urls against a specific size cap and if they are bigger we should just do what Chrome does: nothing. (pressing the `Open simulated image in new window` href does nothing)

First thought that of essence to reproduce the issue on this particular website was having "desktop mode" enabled. But the `Browse` button may be hidden in mobile view due to the improper layout - on landscape part of the `Browse` button can be seen which allow for the issue to happen in mobile mode also.

**Comment by Mugurell** [comment] 2020-03-31 16:28
Webcompat issue for the above website - https://github.com/webcompat/web-bugs/issues/51006

Irrespective of this, the data url issue needs to be resolved in Fenix / A-C.

**Comment by Mugurell** [comment] 2020-04-01 16:59
The STRs can be reduced to 
1) Open Firefox Preview browser.
2) Go to: https://www.color-blindness.com/coblis-color-blindness-simulator/ .
3) Choose any of the filters to apply, like "Green-Week/Deuteranomaly".
4) Tap on the "Browse" button and choose the image you want to change 
(pick one having a few MBs in size)
    If the "Browse" button is not showing it might overflow the screen. To see it:
    - put the device in landscape mode or
    - tap on the "3 dots" from bottom right corner -> enable "Desktop Site" option.
5) Wait for the image to be processed and the website to show a "Open simulated image in new window"

Result:
- Long pressing on the above link will throw an "OutOfMemoryException"
- Pressing on the link will open a new tab but crash with a "TransactionTooLargeException"
Browser session would also get corrupted and so a user would have to clear data / reinstall.

Interestingly Fennec is more resilient and will load pages of a few hundreds of kBs.

**Comment by Mugurell** [comment] 2020-04-01 17:23
Submitted a new GeckoView bug for this - https://bugzilla.mozilla.org/show_bug.cgi?id=1626687

**Comment by Mugurell** [comment] 2020-06-17 06:32
This should've been fixed by now in GV.
@Diana-Rus Can you please check if all works good now?

**Comment by Diana-Rus** [comment] 2020-06-22 08:59
Hey verified the issue with Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL (Android 9) with the following files sizes:
- 11.5 MB - no crash encounter - the loading bar for the file is present but seems to stop
- 5 MB - no crash encounter - the loading bar for the file is present but seems to stop
- 3.79 MB - no crash encounter - the loading bar for the file is present but seems to stop
- 2.79 MB - no crash encounter - the loading bar for the file is present but seems to stop
-1.9 MB - no crash encounter - the loading bar for the file is present but seems to stop
-1.8 MB - no crash encounter - the loading bar is working, the file is processed, When tapping on the "Open simulated image in new window" link a new tab is opened but not with the file - it displays the "Drag and drop or paste you file..." box
- 1.65 MB - no crash encounter - but the loading bar with the file stops, just like it's the case with files over 1.8 MB (will put a GIF  after the verification)
- 1.5 MB - same case as for 1.8 MB outcome
- 1.4 MB - same case as for 1.8 MB outcome
- 1.31 MB - same case as for 1.8 MB outcome
- 1.2 MB - same case as for 1.8 MB outcome
- 1.15 MB - the file loaded correctly in the new tab
- 736 KB - same outcome is present as for 1.8 MB case

**GIF**
![20200622-113307](https://user-images.githubusercontent.com/49859863/85268756-990f8980-b47f-11ea-8bd6-d400cb9253b0.gif)

**Comment by vthg2themax** [comment] 2021-03-07 18:57
Please don't close this issue, it's very important to keeping Firefox relevant against other browsers!

**Comment by Mugurell** [comment] 2021-03-09 07:02
I think this is actually fixed. Asking QA for a confirmation.

**Comment by vthg2themax** [comment] 2021-03-09 16:36
It would also be great to know the file size being used to test this. I think a reasonable amount would be 250MB, but if more could be done. That would be great!

**Comment by Mugurell** [comment] 2021-03-09 20:54
> It would also be great to know the file size being used to test this. I think a reasonable amount would be 250MB, but if more could be done. That would be great!

We will drop all data URLs bigger than 2MB, the same as Chrome does.
A bit more context - https://chromium.googlesource.com/chromium/src/+/master/docs/security/url_display_guidelines/url_display_guidelines.md#url-length

If websites want to load bigger objects there are better ways of doing so.

**Comment by Mugurell** [comment] 2021-03-09 21:06
@vthg2themax Can you offer an example of where bigger data URLs would be useful?

**Comment by vthg2themax** [comment] 2021-03-09 21:26
Yes, currently I have an app that runs with the Rust / Wasm bindgen, and it can only access the innerHTML property of an HtmlAnchorElement. I cannot create a dataURL in JavaScript, because the bindings will not carry over between JavaScript, and Rust, and instead I must pass it through as a DataURL which does not work in Firefox Mobile currently. Here is my project:
https://github.com/vthg2themax/rust_money_manager/blob/9c996d9ced3b7de29e71f8599b50140effec5fb9/src/utility/html_helper_utility.rs#L1069
This seems the most straight forward way to do it, but if there was another way, that would be fine too, however I think other people would also like to keep big data URLs around as well.

**Comment by abodea** [comment] 2021-03-10 11:28
Verified as fixed on the latest Nightly 3/10 with Google Pixel 4 XL (11).
Note that I followed the steps from this https://github.com/mozilla-mobile/fenix/issues/7341#issuecomment-607370645.
I didn't encounter any crashes and I tried with a different file sieze.

**Closed by abodea** 2021-03-10 11:28 UTC
Labels: P2, S2, eng:qa:needed, needs:ac, needs:gv, 🐞 bug

**Comment by vthg2themax** [comment] 2021-03-10 12:57
Can you try with a different device running Android 10? I have a One Plus 7 Pro running Android 10, on the latest 3/10 Nightly, and I still cannot get it to work with a file size above 3.9MB.

**Comment by Mugurell** [comment] 2021-03-10 17:07
@vthg2themax This ticket was for resolving a crash of Firefox when trying to load too long URLs.
And now that is verified as fixed - the app won't crash anymore when trying to load such URLs because it will simply drop them if they have more than 2MB in size.

As such, the scenario you are describing is the expecting outcome.
Supporting larger length URLs has big implications, you can open a new ticket on https://bugzilla.mozilla.org/enter_bug.cgi?product=GeckoView&component=General or here if you don't have a Bugzilla account to ask re-evaluating the current approach.

**Comment by vthg2themax** [comment] 2021-03-10 17:42
That is a very disappointing outcome. I will have to continue using a different browser in that case. Thank you for answering at least!

**Comment by usemoslinux** [comment] 2021-03-10 20:52
@Mugurell Please take a look at #17878 for a similar issue.  
Firefox & Chromium based desktop browsers, as well as all Chromium based browsers for Android support large base64 src strings for audio, video and image elements. Only Firefox for Android seems to have a problem with this. You can follow the steps described in #17878 to reproduce.
In my case, it prevents me from using a tts service that provides base64 audio. I believe many users will feel disappointed with this limitation and migrate to other browsers. Please, consider reviewing this issue once again.

**Comment by Mugurell** [comment] 2021-03-11 07:24
@vthg2themax Please follow https://bugzilla.mozilla.org/show_bug.cgi?id=1697727 for more updates.
