### ISSUE TITLE
[Bug] During Onboarding, user can use tabs tray to browse, and keep Onboarding in backstack

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#15990] opened 2020-10-17 01:26 UTC
### Acceptance Criteria
UX recommendation: Onboarding should be present until the user visits a url (by hitting enter, clicking the suggestion, etc), or opening a new tab.

[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Start Fenix fresh install
See Onboarding show up
Tap on Tabs Tray tab counter icon (0) (or swipe up on bottom of screen for gesture)

### Expected behavior
Maybe nothing should happen? but this could be a UX question.

- disable opening tabs tray during onboarding?
- Open tabs tray but make sure we do a better job of dismissing onboarding if user start browsing? or going through Settings?

### Actual behavior
Tabs Tray opens "Your open tabs will be shown here"

You can then get into some weird states:
- Onboarding can be in your history back stack (by opening tabs tray, opening a new tab, browsing, then hitting back)
- Putting Onboarding into private mode (by opening tabs tray and opening a private tab)
- Get into Tabs settings (by clicking on 3-dot menu)

You can also long-press the tab icon to show the "Open new Private Tab" quick action, which will put Onboarding into private mode.

### Device information

* Android device: any
* Fenix version: 83 Nightly

**Comment by mcarare** [comment] 2020-10-20 11:53
This issue https://github.com/mozilla-mobile/fenix/issues/16018 is also relevant for this discussion.

**Comment by apbitner** [comment] 2020-10-30 20:04
Onboarding was intended to go away whenever the user visited a page whether that be through search, typing in a URL, a bookmark, etc. I agree that even if the user opens a new tab, this should dismiss the onboarding as well and replace it with the standard home screen.

**Comment by liuche** [comment] 2020-11-05 19:32
Onboarding should be present until the user **visits** a url (by hitting enter, clicking the suggestion, etc).

**Comment by violasong** [comment] 2020-11-12 05:56
As mentioned in issue #16353, I think this will be affected by the new conversation around changing homescreen to a new tab so that it's part of the backstack. In that case, onboarding can also be treated as a real link that ends up in the backstack. CC: @lime124

**Comment by mcarare** [comment] 2020-11-25 09:44
For QA, also see: https://github.com/mozilla-mobile/fenix/pull/16613#issue-522379526.

**Comment by sflorean** [comment] 2020-11-27 14:42
Verified as fixed on Nightly 11/27 with Samsung Galaxy Note 10(Android 10)

**Closed by sflorean** 2020-11-27 14:42 UTC
Labels: Feature:Onboarding, Feature:Tabs, eng:qa:needed, eng:ready, 🐞 bug
