### ISSUE TITLE
Add support for all extensions and open local html files

### ISSUE THREAD

**Issue by mueenulit** [mozilla-mobile/fenix#22864] opened 2021-12-15 02:35 UTC
Firefox Android should add support for all extensions. So, we can Install third party extensions easily (like Kiwi Browser) ...

** When I try to open a local html file firefox not showing on prompt. Please solve this asap

...

**Comment by cadeyrn** [comment] 2021-12-15 07:20
Duplicate of #7546 for opening local files. For an expanded add-on support there is already a large number of other issues.

**Closed** 2021-12-15 14:50 UTC
Labels: needs:triage
