### ISSUE TITLE
FNX-5436 ⁃ [Bug] Some videos on Bloomberg.com give an error message

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#2070] opened 2019-04-26 13:37 UTC
## Steps to reproduce
* Load https://www.bloomberg.com/news/articles/2019-04-25/uber-is-said-to-plan-ipo-price-range-of-about-44-to-50-a-share?srnd=technology-vp
* Click the play button 

### Expected behavior
* Video would play

### Actual behavior
* Video gives the message "An error has occurred. Reload the web page or use another browser. Error 4"
* Reloaded the browser doesn't have an effect on making the video play

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1917 (Build #11160057)

**Comment by mozillamarcia** [comment] 2019-05-07 19:27
Using the latest build, on my device I see an error on every single video under the top left menu category "Watch Popular Videos"

**Comment by sv-ohorvath** [comment] 2019-05-17 12:01
I can reproduce this with a Note 8 & S8 (Android 9 both).
Not reproducing on P9 lite (Android 9), P20 lite (Android 8), HTC 10 (Android 8), Sony Xperia (A. 7.1.1 )

**Comment by sarentz** [comment] 2019-05-29 18:08
@sv-ohorvath  do you think this could be a related to tracking protection? would you mind testing with TP on/off?

**Comment by sv-ohorvath** [comment] 2019-05-30 12:42
Still getting the error with TP on or off: Pixel (Android 9)

**Comment by vesta0** [comment] 2019-05-30 19:14
This works in Fennec.

**Comment by cpeterso** [comment] 2019-05-31 21:53
I think this is a regression in Gecko 68. The video plays fine for me in Fennec 67 on my Moto G5 Plus, but I can reproduce the error in Fennec 68 Beta, Fennec 69 Nightly, Focus 8.0.9 (GV 68.0.20190401094905), and Fenix 1.0.1922 (GV 68.0-20190527103257). (I haven't tested Focus 8.0.12 like Vesta because my phone has not updated to Focus 8.0.10 or later yet. 🤔)

I filed a new Gecko media bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1556094

The video reliably crashes R-B, so I filed a new R-B issue: https://github.com/mozilla-mobile/reference-browser/issues/780

**Comment by bifleming** [comment] 2019-06-05 21:32
@vesta0 the related GV bug is a P2 priority for them.

**Comment by cpeterso** [comment] 2019-06-06 00:43
> @vesta0 the related GV bug is a P2 priority for them.

The Gecko team is still investigating, but this bug might be a problem with Bloomberg video. If that is the case, the Gecko Media team will have to work around the problem or ask Bloomberg to fix their video.

Also, Fennec has the same bug, so this is not a regression. :)

**Comment by bifleming** [comment] 2019-06-06 17:49
@vesta0 can we bump this down to a P1?

**Comment by vesta0** [comment] 2019-06-06 17:51
@bifleming Done :)

**Comment by cpeterso** [comment] 2019-07-02 19:32
Can anyone still reproduce this Bloomberg video bug?

I had previously been able to reproduce it in Focus 8.0.9, Fennec 68 Beta, Fennec 69 Nightly, and Fenix.

I can still reproduce in Focus 8.0.15, but not in Fennec 68 Beta, Fennec 69 Nightly, or Fenix. Since this works in Fennec and Fenix now, can close this bug as WORKSFORME?

**Comment by sv-ohorvath** [comment] 2019-07-03 08:50
> I can still reproduce in Focus 8.0.15, but not in Fennec 68 Beta, Fennec 69 Nightly, or Fenix.

Same here. Tried with a Pixel 3, Galaxy S8 (Android 9) & Pixel (Android Q).

**Comment by ekager** [comment] 2019-07-30 22:46
Let's close this bug especially because we're now on 69. Please reopen if you're still seeing this.

**Closed** 2020-08-11 13:49 UTC
Labels: Feature:Media, P2, b:web-content, needs:gv, 🐞 bug, 🙅 waiting
