### ISSUE TITLE
save as PDF

### ISSUE THREAD

**Issue by clientenq** [mozilla-mobile/fenix#14099] opened 2020-08-23 21:18 UTC
### What is the user problem or growth opportunity you want to see solved?
The previous stable versions of Firefox for Android supported save page as pdf. This functionality is removed from the latest version without any valid reason to withold this from user functionality.

### How do you know that this problem exists today? Why is this important?
Reasons it is important to (re)introduce this functionality:
1 this was core functionality in previous stable versions
2 users rely on this functionality
3 the functionality is removed without any solid reason to remove it (a new version is not a solid reason to remove functionality users could rely on in previous stable versions)
4 addons / extensions also supporting this functionality as a workaround also have been disabled

### Who will benefit from it?
All users
Mozilla / Firefox for being more reliable again to care about user needs, instead of developer needs to push a product lacking core features from previous stable versions

There is really **no benefit** in removing this functionality from users. It is a pitty the Mozilla Firefox team cares more about push a version as stable while many many functionality that was previously available to users is not available and thus removed.

**Comment by s-ankur** [comment] 2020-08-23 21:20
This is a very popular feature request. Duplicate of #3709

**Comment by ekager** [comment] 2020-08-23 21:36
Closing for #3709

**Closed by ekager** 2020-08-23 21:36 UTC
Labels: needs:triage

**Comment by mohibo** [comment] 2020-12-05 13:15
> 
> 
> This is a very popular feature request. Duplicate of #3709

and no update at all since previous year
