### ISSUE TITLE
Fenix private mode doesn't trigger Gboard private mode.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#489] opened 2019-02-13 20:46 UTC

**Comment by pocmo** [comment] 2019-02-14 12:49
It will after #347. Currently private mode `Session`s are regular `Session`s.

**Comment by pocmo** [comment] 2019-02-14 12:49
@sblatz Do you want to close this as a duplicate of #347 or do you want to keep the bug open to verify this after #347 is closed?

**Comment by sblatz** [comment] 2019-02-14 15:32
Made a note of this in #347!

**Closed by sblatz** 2019-02-14 15:32 UTC
