### ISSUE TITLE
[Bug] "Firefox Search" not working in custom tabs

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#9460] opened 2020-03-27 15:49 UTC
## Steps to reproduce
1. Set Nightly as the default browser.
2. Go to Gmail and open a link.
3. Select a word. 
4. From the text selection menu, tap on **Firefox Nightly Search**.

### Expected behavior
A page is opened in Nightly with the search results for the word selected at step 3.

### Actual behavior
Nothing. The option is not working.

### Device information
* Android device: Samsung Galaxy Note10 (Android 10), Pixel 3 XL (Android 9), Pixel 2 (Android 9).
* Fenix version: Nightly 3/27, 4.2.0-beta.3.

![gif1](https://user-images.githubusercontent.com/58466444/77773878-74824d80-7007-11ea-84ae-d879a49dc29f.gif)

**Comment by Diana-Rus** [comment] 2020-04-14 14:01
Hi, issue reproduces with Google Pixel 3 XL (Android 9) and Samsung Galaxy S9 (Android 8) with Beta 4.3.0-beta.1.

**Comment by softvision-miralobontiu** [comment] 2020-06-09 12:48
This issue still reproduces on the latest Nightly build from 6/9 with Google Pixel (Android 10).

**Comment by sv-ohorvath** [comment] 2020-07-24 11:03
On 79.1.0-beta1 the app is just opened but the search is not done.

**Comment by Mugurell** [comment] 2020-08-06 09:16
Tried to reproduce this but I can't.
@softvision-miralobontiu / @sv-ohorvath can you please confirm if this is still happening?
And if so post a short video with the exact flow?
In the meantime the contextual menu went through some changes..

**Comment by softvision-miralobontiu** [comment] 2020-08-06 09:22
Hi all,
I think we can close this issue because it is investigated in #9056 
Thanks!

**Closed by softvision-miralobontiu** 2020-08-06 09:22 UTC
Labels: E3, Feature:CustomTabs, Feature:TextSelection, S2, needs:triage, 🐞 bug
