### ISSUE TITLE
[webcontent] Site loop using Mobile Mode. Can't continue clicking on link.

### ISSUE THREAD

**Issue by PandoraDay** [mozilla-mobile/fenix#9526] opened 2020-03-30 18:17 UTC
## Site with issue and any steps to reproduce
1. While using Firefox Fenix Mobile Mode, go to [https://translations.telegram.org/](https://translations.telegram.org/)
2. Click on "Start Translating"

### Expected behavior
The site should show a list of languages.

### Actual behavior
Clicking on "Start Translating" deploys a loop which makes seem the browser like is loading the next page. When the load finishes, the initial page is shown again, like it only did a Refresh. 

To fix it, I must type [https://translations.telegram.org/?start=1](https://translations.telegram.org/?start=1) manually or Enable Desktop Version.

Tried with Android Google Chrome's and Android New Microsoft Edge's Mobile Mode and works fine. 

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
Disabling Tracking Protection does not fix the issue while Mobile Mode.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes. Same problem with Firefox for Android.

### Can you reproduce in Chrome (or other non-Mozilla browser)?
The problem does not happen using Chrome or Edge.

### Device information

* Android device: Unrooted Nexus 6P with Android 8.1.0
* Fenix version: 4.2.0

**Comment by LaurentiuApahideanSV** [comment] 2020-03-31 10:56
I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 3/31 (Build #20910607).

Device: OnePlus 6T (Android 9);

**Comment by kbrosnan** [comment] 2020-04-11 20:52
This seems like a webcompat issue. Reporting it to https://webcompat.com may be better than reporting it here. Cannot reproduce the behavior in Desktop with responsive design mode and a Firefox Preview user agent. Can reproduce the problem in Firefox Preview Nightly.

**Comment by PandoraDay** [comment] 2020-04-11 22:06
> This seems like a webcompat issue. Reporting it to https://webcompat.com may be better than reporting it here. Cannot reproduce the behavior in Desktop with responsive design mode and a Firefox Preview user agent. Can reproduce the problem in Firefox Preview Nightly.

Thank you for the reply. Sorry, I am new into this. So, ¿Does that mean that this issue can get Closed?

**Comment by kbrosnan** [comment] 2020-04-11 23:39
It is unclear if this is a website bug or a Firefox bug so the team at webcompat are great at pulling apart the code for websites to understand what is causing the underlying issue.

**Comment by PandoraDay** [comment] 2020-04-12 01:05
> It is unclear if this is a website bug or a Firefox bug so the team at webcompat are great at pulling apart the code for websites to understand what is causing the underlying issue.

That is good to know. I will keep the issue opened and report any progress.

Thanks again ^^

**Comment by kbrosnan** [comment] 2020-04-20 17:53
This looks like a website bug. Going close this. Thank you for reporting this.

**Closed by kbrosnan** 2020-04-20 17:53 UTC
Labels: S2, b:webcompat

**Comment by PandoraDay** [comment] 2020-04-22 07:00
> This looks like a website bug. Going close this. Thank you for reporting this.

Thanks for your time into checking this regard. Greetz 🙂
