### ISSUE TITLE
Problems with scrolling and links with in a Web page

### ISSUE THREAD

**Issue by mm1ck** [mozilla-mobile/fenix#16530] opened 2020-11-12 16:09 UTC
## Steps to reproduce
scroll through or tap a link on any web page leaving at least 10 seconds between swipes as if you are reading an article.

### Expected behavior
to be able to scroll first time, or open a link first tap

### Actual behavior
scrolling through a website doesn't always work first time.  Every 3rd or 4th time it seems to ignore a swipe to scroll the screen. You either get a flicker  or no movement of the screen. Second time will work fine. Same goes for tapping a link where it will be ignored until you tap again.

### Device information
Sony Xperia 1

* Android device: ? android 10
* Fenix version: ?82.1.3

**Comment by mcomella** [comment] 2020-11-13 17:33
@mm1ck We haven't seen this ourselves so the best way for us to understand what's going on would be if you could grab a profile for us. Would you be able to? There are two methods:
1) Preferred: use the Firefox Profiler https://profiler.firefox.com/docs/#/./guide-remote-profiling?id=setup
2) Less preferred, may contain sensitive data (so perhaps send to us individually rather than posting on GH): use the system tracer built into Android: https://developer.android.com/topic/performance/tracing/on-device

We haven't used the second option yet so I'm not sure if it'd give us granular enough info to help us debug this but it may give us info outside of Firefox that may also be useful for debugging.

Let us know, thanks!

**Comment by mm1ck** [comment] 2020-11-14 16:24
Ok. I have had a read through the steps required to do this.. seems straight forward enough, I'll give it a go during the week when I have some time.

**Comment by wodnicc** [comment] 2020-11-14 18:47
I think it's the same bug as already discussed here #14527

**Comment by solomonfentonmiller** [comment] 2020-11-14 21:27
Yeah, this is the major bug #14527 ... affecting Android 10 users. I hope it can get prioritization because many OnePlus, Sony, and LG users are switching away.

**Comment by sskodje** [comment] 2020-11-15 01:01
I remember the bug being in the Firefox Beta app 2-3 months ago. It's honestly a disappointing an issue completely breaking the app, which is reported and discussed in detail is pushed to the release version months later, just because it only happens on less popular phone brands. If this issue affected Samsung it would be fixed on the hour.

**Comment by mm1ck** [comment] 2020-11-16 11:47
> @mm1ck We haven't seen this ourselves so the best way for us to understand what's going on would be if you could grab a profile for us. Would you be able to? There are two methods:
> 
> 1. Preferred: use the Firefox Profiler https://profiler.firefox.com/docs/#/./guide-remote-profiling?id=setup
> 2. Less preferred, may contain sensitive data (so perhaps send to us individually rather than posting on GH): use the system tracer built into Android: https://developer.android.com/topic/performance/tracing/on-device
> 
> We haven't used the second option yet so I'm not sure if it'd give us granular enough info to help us debug this but it may give us info outside of Firefox that may also be useful for debugging.
> 
> Let us know, thanks!

Hi

Just got this all connected (option 1) and as soon as I click record the issue goes away.

Tried this tree times, as soon as I disconnect the USB lead the issue returns.  Connect the USB , the issue remains until I click record then doesn't come back until the USB is disconnected.

Not much help I suppose, but that is what happens.

**Comment by mcomella** [comment] 2020-12-02 22:49
The fix from https://github.com/mozilla-mobile/fenix/issues/14527#issuecomment-729503652 seems like it may have addressed this.

@mm1ck (or anyone else) Can you still reproduce this issue in the latest nightly?

**Comment by mm1ck** [comment] 2020-12-03 08:36
> The fix from [#14527 (comment)](https://github.com/mozilla-mobile/fenix/issues/14527#issuecomment-729503652) seems like it may have addressed this.
> 
> @mm1ck (or anyone else) Can you still reproduce this issue in the latest nightly?

I have already confirmed a few days ago in #14527 that it is fixed in the latest nightly.

It is now also fixed in the  84.0.0-beta.2 (Build #2015776763)

Cheers.

**Closed** 2020-12-09 22:37 UTC
Labels: eng:performance, needs:triage
