### ISSUE TITLE
[Bug] pull to refresh on form submission is buggy

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#9799] opened 2020-04-08 12:05 UTC
## Steps to reproduce
submit a form, then pull to refresh. dialog pops up to resend form contents. hit cancel

### Expected behavior
spinner disappears

### Actual behavior
spinner doesn't disappear

![ThrobberIsNotDismissedAfterCance](https://user-images.githubusercontent.com/11428869/88170306-25030580-cc26-11ea-9a2b-e08de3e8295d.gif)
https://drive.google.com/file/d/1zDICfILbpbeh-lSyOlarajBrpnAc_icD/view?usp=sharing

### Device information

* Android device: ?
* Fenix version: ?

**Comment by abodea** [comment] 2020-04-08 12:58
Thank you for this report @staktrace note that this feature is currently removed from Nightly.
I verified the revert changes today https://github.com/mozilla-mobile/fenix/issues/9770#issuecomment-610916270 here you can find more information.
Note that you will be able to see the changes in the next Nightly.

**Comment by Mugurell** [comment] 2020-07-22 11:25
This is both a visual issue and one that would prevent other pull to refresh gestures.
Always reproducing in a somewhat common scenario.
Should be fixed for when we enable pull to refresh again.

Reopening it as a breakout of the meta bug.

**Comment by Mugurell** [comment] 2020-08-14 10:16
Filed a new Bugzilla ticket for this - https://bugzilla.mozilla.org/show_bug.cgi?id=1659073
We need a sure way to identify this kind of prompts.

**Comment by liuche** [comment] 2020-08-14 23:25
It looks like Agi has responded, so if that's an approach that works, could you remove this from the GV high priority list?

**Comment by Mugurell** [comment] 2020-08-17 06:33
> It looks like Agi has responded, so if that's an approach that works, could you remove this from the GV high priority list?

I understand Agi laid down a plan for what should be done in GeckoView for supporting this, we still need the patch, so I think this should still be a priority.

**Comment by amedyne** [comment] 2020-09-21 17:37
https://bugzilla.mozilla.org/show_bug.cgi?id=1659073 is fixed.

**Comment by LaurentiuApahideanSV** [comment] 2020-10-19 10:12
Verified as fixed on Firefox Preview Nightly 201019 (Build #2015770539).

### Devices used:
- OnePlus 6T (Android 9)
- Samsung Galaxy S9 (Android 8.0.0)

**Closed by LaurentiuApahideanSV** 2020-10-19 10:12 UTC
Labels: Feature:Gesture, eng:qa:needed, 🐞 bug
