### ISSUE TITLE
make about:config working

### ISSUE THREAD

**Issue by U-B-Glade** [mozilla-mobile/fenix#14191] opened 2020-08-25 20:12 UTC
### What is the user problem or growth opportunity you want to see solved?
We feel forced by you, we are able to decide, we dont need the Big Brother who decide what the dump User have to like

### How do you know that this problem exists today? Why is this important?
about:confic dont work, you decide what I have to see / like

### Who will benefit from it?
The mature User
the free Internet

**Comment by hwinnemoe** [comment] 2020-08-27 22:11
Duplicate of #7865

**Comment by kbrosnan** [comment] 2020-08-27 22:14
Closing as a duplicate.

**Closed by kbrosnan** 2020-08-27 22:14 UTC
