### ISSUE TITLE
[Bug] Cannot login into slack app using Fenix

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3528] opened 2019-06-18 13:11 UTC
## Steps to reproduce
Regression of https://github.com/mozilla-mobile/fenix/issues/1213

### Expected behavior
Return to slack and log in.

### Actual behavior
Fenix gets stuck on a white page after dual auth is completed.

### Device information
* Android device: Galaxy Note 8 (Android 9), HTC 10 (Android 8)
* Fenix version: 1.0.0 RC 1

**Comment by vesta0** [comment] 2019-06-19 15:49
@kbrosnan was this caused because we reverted the app intent work?

**Comment by kbrosnan** [comment] 2019-06-19 16:18
Yes. This is a dupe of #1213. The code that was the fix was backed out. Should we reopen the older bug and move it out of Done and Sprint it was completed?

**Comment by vesta0** [comment] 2019-06-19 16:51
Yes please. @bifleming ^^

**Comment by sblatz** [comment] 2019-06-20 21:35
Closing as dupe of #1213.

**Closed** 2020-08-27 00:19 UTC
Labels: P1, 🐞 bug
