### ISSUE TITLE
Allow adding link to home screen when site is a webapp

### ISSUE THREAD

**Issue by davidmegginson** [mozilla-mobile/fenix#22361] opened 2021-11-08 10:39 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
I want to save a specific link to my home screen, but when a site is a webapp, the option disappears and is replaced with "install" (e.g. twitter.com).

For sites that are web apps, I would like the "Add to hone screen" option to remain available in addition to "Install"

### How do you know that this problem exists today? Why is this important?

Verified in latest Androud Firefox beta.   Use cases:

1. A user wants to save a deep link into a site, e.g. to a specific tag or forum ("Install" forces you always to link to the top level).
2. A user wants the link to open in their regular browser tabs, not standalone, because they use their tabs for workflow management.
3.  A user does not want the link to appear as a separate app in their tasks.
4. A user wants to avoid the buggy web app support in FF (after a few hours, they often freeze up).

### Who will benefit from it?
All advanced FF users who save links to their home screens. See use cases above.

**Comment by klint** [comment] 2021-11-08 12:56
There are many duplicates... But this proves that is an highly expected feature... For many reasons including, but not limited to, the freeze of webapps after some time or action, as stated.

**Comment by LaurentiuApahideanSV** [comment] 2021-11-18 11:49
This is indeed a duplicate of https://github.com/mozilla-mobile/fenix/issues/20612. I will mark this issue as closed as it will be handled there.

**Closed by LaurentiuApahideanSV** 2021-11-18 11:49 UTC
Labels: needs:triage
