### ISSUE TITLE
Salon.com front page crashes Android Firefox Beta

### ISSUE THREAD

**Issue by PeteOSuch** [mozilla-mobile/fenix#26534] opened 2022-08-18 19:11 UTC
### Steps to reproduce

1. Navigate to salon.com via the address bar.
2. Witness the crash.

This repeated a few times in a row, even after force-closing the browser and restarting.

### Expected behaviour

The page should open and be available for use.

### Actual behaviour

The page renders and then the whole browser crashes and dumps back to the device home screen after maybe 1 or 2 seconds.

### Device name

OnePlus 7T

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

104.0b6 (Build #2015897611)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21332)

**Comment by kbrosnan** [comment] 2022-08-18 21:06
Please provide crash IDs. https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by SoftVision-LorandJanos** [comment] 2022-08-19 12:01
Hi @PeteOSuch. Thanks for your report!
I've tried to reproduce your issue using the following builds:
- latest RC (104.1.0)
- latest Beta (104.0b7)
- the Beta this issue was reproduced with (104.0b6)
- latest Nightly 105.0a1 (2022-08-19).

Device used: Oppo Find X5 (Android 12).

As mentioned above, please provide crash IDs. Thanks!

**Comment by PeteOSuch** [comment] 2022-08-19 17:44
I hesitated because my Firefox Beta doesn't fully align with what I was
told to look for. I don't know if it's localization or a setting I changed,
but the trail stops for me at crashes>share. There I can get to these
recent entries:


bb63c396-4101-4831-ba26-4636e9764936
<native crash>
----
<native crash>


4767aef9-fa07-4a42-8f73-0b94ef1d8dcb
<native crash>
----
<native crash>


3929f323-f447-44a1-8152-610740ee1032
<native crash>
----
<native crash>


07008dd8-18ec-40d1-a341-b407109ee637
<native crash>
----
<native crash>


Those all occurred in the span of 8 minutes. No more detail seems to be
available there.
Thanks,
Pete

**Comment by kbrosnan** [comment] 2022-08-20 04:19
Those are the raw crash IDs. We need the crash URLs.

**Comment by PeteOSuch** [comment] 2022-08-21 16:09
> Those are the raw crash IDs. We need the crash URLs.

I guess I need a more explicit description of what you want me to provide.  I provided the URL of the site that the crash occurs on up above in "Steps to reproduce", and I've provided the text offered up by the crash page's share links.  Here's a screenshot of the crash page entries for these incidents:
![f63ed98ff7c42709945f63e0fc4bef33c775a1cf-1](https://user-images.githubusercontent.com/111533150/185800149-7a5f1743-0b02-4da9-8069-db29e47539cb.jpeg)
If there's something else you wish me to provide, I need very precise and explicit instructions on how to do that.

Thank you.

**Comment by kbrosnan** [comment] 2022-08-22 18:34
These are unsubmitted crashes, there is not any way to get data out from these. It is possible that sending data was denied. If this happens again and you are near a computer using logcat directions on the Logging Crash Information would work.

**Comment by PeteOSuch** [comment] 2022-08-23 00:21
No opportunity to submit crash data was presented as these crashes happened.  I was in the Firefox, then I was staring at my phone's home screen, with nothing in-between.  Is that a separate bug?

**Comment by boek** [comment] 2023-01-30 22:01
Hey @PeteOSuch, I'm going to close this as we were unable to reproduce. If you are still able to reproduce this please file a new issue on Bugzilla with more information.

**Closed by boek** 2023-01-30 22:01 UTC
Labels: 🐞 bug, needs:triage, qa-triaged
