### ISSUE TITLE
[Bug] about:debugging missing

### ISSUE THREAD

**Issue by clientenq** [mozilla-mobile/fenix#14097] opened 2020-08-23 20:58 UTC
Since Mozilla choose to make thousends and thousends of addons / extentions incompatible there is a huge need for development of new addons / extensions. For this functionality was created to support addon / extention developers. One of these is the "about:debugging" functionality to temporary install addons / extentions for testing.

According to the documentation at the following location there is no limitation for browser support:
https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

1 the browser should support functionality we heavily rely on for testing.
2 the documentation is (again) incompatible with the latest browser and does not reflect the limitations

## Steps to reproduce
open Firefox
enter "about:debugging" in the URL bar

### Expected behavior
debugging functionality to temporary install addon / extention

### Actual behavior
no such functionality

### Device information
* Fenix version: 79.x

**Comment by cadeyrn** [comment] 2020-08-23 21:01
There is no need for "about:debugging" in Fenix. What you really want is sideloading of add-ons. It's a duplicate of #11308. See also #14034.

**Comment by liuche** [comment] 2020-08-25 01:57
Thanks for providing the extra info! I'm going to close this because this is already covered.

**Closed by liuche** 2020-08-25 01:57 UTC
Labels: needs:triage, 🐞 bug

**Comment by mohibo** [comment] 2020-12-03 15:06
> 
> 
> There is no need for "about:debugging" in Fenix. You can use Mozilla's web-ext tool. See also #11308 for sideloading add-ons and #14034 for installing arbitrary add-ons in Firefox Nightly.

both are only exclusive to nightly,is there something for fucking stable?
