### ISSUE TITLE
FNX-12666 ⁃ [Bug]Unresponsive tab tray items on first touch

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#11689] opened 2020-06-17 11:52 UTC
## Steps to reproduce
1. Have several tabs open
1. Open tab tray
1. Tap on tab to open

### Expected behavior
* tapped tab should open

### Actual behavior
* first touch on a tab item has no effect. Opening a tab requires 2 taps

### Device information
* Android device: Pixel 3XL (Android 10)
* Fenix version: latest nightly

![unresponsive tab tray items](https://user-images.githubusercontent.com/60002907/84894751-f84d5280-b0a9-11ea-8fa2-dbc8b4633459.gif)

**Comment by cadeyrn** [comment] 2020-06-17 12:00
Duplicate of #11558.

**Closed** 2020-08-11 04:40 UTC
Labels: Feature:Tabs, needs:triage, 🐞 bug
