### ISSUE TITLE
FNX2-15052 ⁃ [Bug] Overwriting files with same name when downloading to some folders

### ISSUE THREAD

**Issue by marcobellaccini** [mozilla-mobile/fenix#12159] opened 2020-07-01 15:49 UTC
## Steps to reproduce
* create a subfolder of _Download_, named _test_
* move a file (e.g.: _foofile_) to _Download/test_
* download another file with the same name (e.g.: _foofile_) from a website

### Expected behavior
I end up having two files:

* _Download/foofile_
* _Download/test/foofile_

### Actual behavior
I have only one file:

* _Download/test/foofile_

the old _foofile_ has been overwritten without any notice.

### Device information
* Android device: Nokia 6.2 - Android 10, June 5 Patch
* Fenix version: 5.2.0 build 21701706, AC 46.0.0 bca4c5c91, GV 78.0-20200612174529, AS 60.0.0

**Comment by Amejia481** [comment] 2020-07-31 00:07
After https://github.com/mozilla-mobile/fenix/pull/12823 we want to verify if this issue is still present on nightly

**Comment by marcobellaccini** [comment] 2020-08-02 14:59
Hi, I've just tested the current nightly.
The behavior changed but it's still not the right one.
Now the old file isn't overwritten anymore but, despite the "Download Completed" message, the new file is missing.

Nightly 200802 06:16 (Build #22150627)
AC: 53.0.20200801130512, c6137485e
GV: 81.0a1-20200730093956
AS: 61.0.10

**Comment by LaurentiuApahideanSV** [comment] 2020-08-05 12:24
We tried to reproduce the issue one Firefox Preview Nightly 200805 (Build #22180855) on Samsung Note 10 (Android 10), Google Pixel 4 XL (11), OnePlus6T (Android 9) and Nokia 6 (Android 7.1.1) but were unable to.
@marcobellaccini Could you provide with further information on how to reproduce the issue or even a video highlighting it?

**Comment by marcobellaccini** [comment] 2020-08-05 13:20
Hi, I'm attaching some screenshots of current Nightly behavior (which is a bit different from what I described in my last comment).
In the first screenshot, you can see a PDF file in _Download/test_.
I renamed it to match the name of the file I'm going to download, yet you can see it's a document about astronauts with size 3.04MB.
In the next 3 screenshots, you can see that I download a file with the same name (this time a 0.10MB PDF from GitHub).
In the 5th screenshot, you can see the first weird thing: file size did not change, but now Android is failing to generate the preview icon.
In fact, the new file has not been downloaded to _Download_.
Instead, it has somehow partly overwritten the file in  _Download/test_, generating a corrupted file (see 6th screenshot).

Nightly 200802 06:16 (Build #22150627)
AC: 53.0.20200801130512, c6137485e
GV: 81.0a1-20200730093956
AS: 61.0.10

![Screenshot_20200805-145238.png](https://user-images.githubusercontent.com/24960638/89417327-d3cb3980-d72e-11ea-8956-9fc1aa9008da.png)
![Screenshot_20200805-145324.png](https://user-images.githubusercontent.com/24960638/89417364-dfb6fb80-d72e-11ea-81f4-3f90df09bff3.png)
![Screenshot_20200805-145340.png](https://user-images.githubusercontent.com/24960638/89417378-e6457300-d72e-11ea-97d8-5cf8a4fe9bb7.png)
![Screenshot_20200805-145352.png](https://user-images.githubusercontent.com/24960638/89417411-f1989e80-d72e-11ea-97c3-d826d9befd30.png)
![Screenshot_20200805-145414.png](https://user-images.githubusercontent.com/24960638/89417594-2a387800-d72f-11ea-9654-70342ee3787b.png)
![Screenshot_20200805-145457.png](https://user-images.githubusercontent.com/24960638/89417610-2f95c280-d72f-11ea-8837-29713b594646.png)

**Comment by Amejia481** [comment] 2020-08-09 20:37
Thanks, for all the info @marcobellaccini, I was trying to simulate the issue but I wasn't able to replicate. It would be great if
you could help us to  clarify the steps to reproduce. Additionally if you could share which file manager are you using and  the file test (url where to download), I would appreciate it very much.

**Comment by marcobellaccini** [comment] 2020-08-10 13:50
Hi, 
my file manager is the Android built-in one (_Files by Google_).

Here are the steps to reproduce the issue:

- Create _Internal Storage/Download/test_ folder
- Download [first test file](https://www.debian.org/doc/manuals/debian-faq/debian-faq.en.pdf)
- Move it to _Internal Storage/Download/test_ folder
- rename the file to _git-cheat-sheet-education.pdf_
- Download the [second test file](https://education.github.com/git-cheat-sheet-education.pdf)

The first test file is now corrupted (maybe you'll be able to open it, but the content will be damaged).

Nightly 200810 06:01 (Build #2015757107)
AC: 54.0.20200807130552, 1d5e94f0d
GV: 81.0a1-20200806033456
AS: 61.0.10

**Comment by marcobellaccini** [comment] 2020-08-10 15:21
I edited the previous comment, please make sure you read the latest version.

**Comment by Amejia481** [comment] 2020-08-10 15:36
Thanks!

**Comment by Amejia481** [comment] 2020-08-10 18:46
> Hi,
> my file manager is the Android built-in one (_Files by Google_).
> 
> Here are the steps to reproduce the issue (I changed test files because the GitHub App has a peculiar behavior when trying to open links from their domain):
> 
>     * Create _Internal Storage/Download/test_ folder
> 
>     * Download [first test file](https://www.linuxmint.com/documentation/user-guide/Cinnamon/english_18.0.pdf)
> 
>     * Move it to _Internal Storage/Download/test_ folder
> 
>     * rename the file to _debian-faq.en.pdf_
> 
>     * Download the [second test file](https://www.debian.org/doc/manuals/debian-faq/debian-faq.en.pdf)
> 
> 
> The (renamed) first test file is now corrupted (in my case, with these files, I'm still able to open it, but the content of the first pages is damaged).
> 
> When trying to reproduce the bug, please make sure not to have other copies of the files somewhere else.
> 
> Nightly 200810 06:01 (Build #2015757107)
> AC: 54.0.20200807130552, 1d5e94f0d
> GV: 81.0a1-20200806033456
> AS: 61.0.10

Now I was able to reproduce, thanks for the extra details. After applying https://github.com/mozilla-mobile/android-components/pull/7842, I'm not able to reproduce, it looks like it will fix it.

**Comment by abodea** [comment] 2020-08-13 15:03
Verified as fixed on the latest Nightly build from 8/13 with Google Pixel 4 XL (11).
Following the steps from here https://github.com/mozilla-mobile/fenix/issues/12159#issuecomment-671365909 everything worked as expected and the issue cannot be reproducible.

**Closed by abodea** 2020-08-13 15:03 UTC
Labels: E3, Feature:Download, eng:qa:needed, hershey, 🐞 bug

**Comment by Amejia481** [comment] 2020-08-13 15:04
@marcobellaccini  does the latest latest nightly fix the issue for you?

**Comment by marcobellaccini** [comment] 2020-08-14 08:43
Yes, I've just tried and now it works as expected.
Thank you for your great job! 🥳

**Comment by Amejia481** [comment] 2020-08-14 13:33
Happy to hear that :)
@BranescuMihai did all the work, I just reviewed :sweat_smile:

**Comment by xNul** [comment] 2022-08-25 23:35
> Hi, my file manager is the Android built-in one (_Files by Google_).
> 
> Here are the steps to reproduce the issue (I changed test files because the GitHub App has a peculiar behavior when trying to open links from their domain):
> 
>     * Create _Internal Storage/Download/test_ folder
> 
>     * Download [first test file](https://www.linuxmint.com/documentation/user-guide/Cinnamon/english_18.0.pdf)
> 
>     * Move it to _Internal Storage/Download/test_ folder
> 
>     * rename the file to _debian-faq.en.pdf_
> 
>     * Download the [second test file](https://www.debian.org/doc/manuals/debian-faq/debian-faq.en.pdf)
> 
> 
> The (renamed) first test file is now corrupted (in my case, with these files, I'm still able to open it, but the content of the first pages is damaged).
> 
> When trying to reproduce the bug, please make sure not to have other copies of the files somewhere else.
> 
> Nightly 200810 06:01 (Build #2015757107) AC: 54.0.20200807130552, 1d5e94f0d GV: 81.0a1-20200806033456 AS: 61.0.10

This exact bug has been reintroduced somehow. I have reproduced on the latest version of Nightly. Possibly has to do with #9597.

@Amejia481

**Comment by xNul** [comment] 2022-08-26 00:07
It seems as though this has already been reported at https://github.com/mozilla-mobile/fenix/issues/24346
