### ISSUE TITLE
FNX-505 ⁃ [Bug] video playback aborted due to a network issue

### ISSUE THREAD

**Issue by rmbq** [mozilla-mobile/fenix#2159] opened 2019-04-30 10:32 UTC
## Steps to reproduce
Open this video:
https://www.facebook.com/trynottolaughpets/videos/418428262272505/

and jump straight to an unbuffered point.

Step to reproduce video:
https://youtu.be/z8HvI7bkRTM

### Expected behavior
video plays at desired point

### Actual behavior
error popup "video playback aborted due to a network issue"

### Device information
* Android device: Oneplus 6 lastest stable
* Fenix version: 1.0.1920 (Build#11370606 68.0a1-20190508111321

**Comment by rmbq** [comment] 2019-05-17 09:04
update OP with step to reproduce

**Comment by sv-ohorvath** [comment] 2019-05-17 14:40
@rmbq URL signature expired. Can't access the link you shared.

**Comment by rmbq** [comment] 2019-05-17 14:48
> @rmbq URL signature expired. Can't access the link you shared.

updated, should be fine now. it's another video but you can reproduce the issue

**Comment by sv-ohorvath** [comment] 2019-05-20 07:53
I was able to reproduce this on the latest build: 5/20. 
Device: P9 lite (Android 6). 
Also reproducing on Fennec, but not Chrome.

**Comment by vesta0** [comment] 2019-05-29 18:15
@cpeterso this seems like a GV issue since it's also reproducing on Fennec. Do we have a bug for it?

**Comment by cpeterso** [comment] 2019-05-29 19:09
I filed a new Gecko media bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1555452

Is this bug reproducible in Chrome? A similar Facebook video seeking bug was reported in Fennec 10 months ago, but it was a Facebook network bug and was also reproducible in Chrome:

https://bugzilla.mozilla.org/show_bug.cgi?id=1477649#c14

**Comment by rmbq** [comment] 2019-05-29 19:16
I can't reproduce it on Chrome, usually i use chrome to watch the video because of this bug

**Comment by cpeterso** [comment] 2019-05-30 02:11
> I can't reproduce it on Chrome, usually i use chrome to watch the video because of this bug

Thanks for checking. That's helpful information. This bug must be a different issue than the old bug 1477649.

**Comment by cpeterso** [comment] 2019-10-21 15:53
This bug is in the Gecko Media team's backlog, but we don't have an estimate of when they will have time to investigate.

A related Gecko Media bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1566572

**Comment by liuche** [comment] 2019-11-11 19:07
@cpeterso I added this `needs:gecko` label, for things that also need a Gecko change (not just GV). Could you update the labels for the other bugs to reflect that? (and updating the `needs:gv` if that's still relevant, or simply a Gecko change)

**Comment by liuche** [comment] 2019-11-11 19:08
@cpeterso I added this needs:gecko label, for things that also need a Gecko change (not just GV). Could you update the labels for the other bugs to reflect that? (and updating the needs:gv if that's still relevant, or simply a Gecko change)

cc @boek @bifleming

**Comment by cpeterso** [comment] 2019-11-11 21:40
> @cpeterso I added this needs:gecko label, for things that also need a Gecko change (not just GV). Could you update the labels for the other bugs to reflect that? (and updating the needs:gv if that's still relevant, or simply a Gecko change)

OK. I'll add `needs:gecko` and remove `needs:gv` as needed for these bugs:

https://github.com/mozilla-mobile/fenix/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Aneeds%3Agv+-label%3Aneeds%3Agecko

**Comment by boek** [comment] 2019-11-20 18:43
The media team has investigated this and it is blocked on a 3rd party

**Comment by fluffyemily** [comment] 2020-05-12 18:41
Bryce from the media team has spoken to @ekager about https://bugzilla.mozilla.org/show_bug.cgi?id=1566572. The media team can not reproduce and would like to get confirmation from the Fenix team that it is no longer an issue before they close the bug.

**Comment by ekager** [comment] 2020-05-12 21:05
Closing because the media teams can't reproduce anymore. We can revisit if we get this report again.

**Closed** 2020-08-11 14:06 UTC
Labels: Feature:Media, P1, needs:gecko, needs:gv, 🐞 bug, 🙅 waiting
