### ISSUE TITLE
FF says: Limit reached for top sites - but only two top sites are present

### ISSUE THREAD

**Issue by OlliKn** [mozilla-mobile/fenix#23408] opened 2022-01-25 19:57 UTC
FF tells me the Limit for top Sites is reached and i shall delete one when I try to add a new site via three dot menue. But there are only three sites pinned on homescreen.

Samsung tab4 Android 10
Honor 6x Android 9

98.0a1 (Build #2015858857), 250af1e0e+
AC: 98.0.20220121232326, 9d058c8de5
GV: 98.0a1-20220121104506
AS: 90.0.0

**Comment by anghelos** [comment] 2022-01-30 14:33
Have the same issue, but I currently have no pinned sites. The pinned sites section is automatically from my history.

98.0a1 (Build #2015860299), 3bdf1d812+
AC: 98.0.20220129143244, d2c2a49bb6
GV: 98.0a1-20220129091708
AS: 90.0.1

**Comment by Rodze** [comment] 2022-02-01 06:11
I get limit reached and I had 5 top sites pinned.

I guess something is making this message appear always regardless of the amount of top sites.

**Comment by petergaultney** [comment] 2022-02-02 03:13
Same issue. I had only three. I deleted one as a test, and I still get the same message - "Top site limit reached" followed by "To add anew top site, remove one. Touch and hold the site and select remove."

**Comment by LaurentiuApahideanSV** [comment] 2022-02-02 13:27
I can confirm the issue is reproducible on Firefox Nightly 2022-02-02.

### Devices used:
- Google Pixel 6 (Android 12)
- Realme GT Master Edition (Android 11)

**Comment by santo998** [comment] 2022-02-21 16:26
Same issue, Firefox Nightly 99.0a1, Android 8.1, Samsung J7 Prime.
Top sites is just unusable!!!

**Comment by SoftVision-LorandJanos** [comment] 2022-02-24 07:18
Verified as fixed on the latest Nightly 99.0a1 (2022-02-24).
Device used: Oppo Reno 6 (Android 11).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-02-24 07:18 UTC
Labels: 🐞 bug, eng:qa:needed, S2, Feature:TopSites, needs:triage, qa-triaged
