### ISSUE TITLE
[Bug] Emojis aren't visible on Twitter

### ISSUE THREAD

**Issue by bogas04** [mozilla-mobile/fenix#3643] opened 2019-06-25 05:26 UTC
### Steps to reproduce
Open mobile.twitter.com
Compose a tweet
Type emojis

### Expected behavior
It should appear

### Actual behavior
It doesn't

### Device information

* Android device: OP3T, 9.0 Pie
* Fenix version: 1.0.1926 (Build #11751810 🦎 68.0-20190611143747)

Screencast: ![https://gfycat.com/blackdearbufflehead](https://thumbs.gfycat.com/BlackDearBufflehead-size_restricted.gif)

**Comment by kbrosnan** [comment] 2019-06-28 02:32
Does this happen using Firefox for Android? Does this happen if you use Light mode?

**Comment by bogas04** [comment] 2019-06-28 02:39
Happens in light mode as well. I don't have Firefox installed as of now, will try it.

**Comment by bogas04** [comment] 2019-06-28 07:06
BTW they're visible once the tweet has been made. So the issue is really with textarea not rendering emojis

🙈😕🤮😕🤮💄<--- It's happening here as well

**Comment by ekager** [comment] 2019-06-28 20:59
Opened GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1562316

**Comment by cpeterso** [comment] 2019-07-03 22:14
@bogas04 - Can you still reproduce this emoji bug on your OnePlus 3T and the latest Fenix? Are you using a non-default keyboard?

I can't reproduce this bug in Fenix 1.0.1926 (Build #11790617 🦎 GV 68.0-20190612114833) on my Moto G5 Plus running Android 8.1.0. snorp wasn't able to reproduce on his Pixel 2 running Android Q. This suggests the problem might be something specific about the OnePlus 3T or the keyboard.

**Comment by bogas04** [comment] 2019-07-04 02:23
I'm using Google board. Can still reproduce on Nightly 190703 18:02 (Build #11841814)
📦: 3.0.0
🦎: 68.0-20190612114833

**Comment by bogas04** [comment] 2019-07-10 08:04
It works on an older device, so it might be unrelated maybe. If QA can't reproduce in any of the test devices then I guess it's safe to close this.

**Comment by Scripterr** [comment] 2019-07-10 08:34
@bogas04 this may be caused by a webrender bug because i can reproduce it with webrender enabled.
Maybe you have enabled webrender in past which is causing this problem.

**Comment by bogas04** [comment] 2019-07-10 09:08
Oh yeah you're right. I did have it enabled. Maybe we should have this part
of bug report checklist for graphic related issues.

**Comment by cpeterso** [comment] 2019-07-10 16:55
> i can reproduce it with webrender enabled.

I moved the GeckoView Bugzilla bug to the WebRender team. Whether we should keep this Fenix issue open is up to the Fenix team.

https://bugzilla.mozilla.org/show_bug.cgi?id=1562316#c5

**Comment by ekager** [comment] 2019-08-06 20:55
I'm closing this bug, the fix is in GV70

**Closed by ekager** 2019-08-06 20:55 UTC
Labels: b:web-content, needs:gv, 🐞 bug, 🙅 waiting
