### ISSUE TITLE
Add Startpage.com as search provider

### ISSUE THREAD

**Issue by pashinskikh** [mozilla-mobile/fenix#5172] opened 2019-09-09 05:32 UTC
It would be great to have Startpage as search provider - it's respect users privacy, but also provides accurate search results from Google.

**Comment by cadeyrn** [comment] 2019-09-09 06:21
Duplicate of #1437.

**Comment by NotWoods** [comment] 2019-12-23 07:31
Closing since custom search engines work now 😄

**Closed by NotWoods** 2019-12-23 07:31 UTC
Labels: 🌟 feature request
