### ISSUE TITLE
[Bug] Bing.com freezes the browser

### ISSUE THREAD

**Issue by BrokenShoeLace** [mozilla-mobile/fenix#17987] opened 2021-02-13 11:25 UTC
Open Firefox, go to bing.com, view a news article. Use a swipe up gesture to go back one page to bing.com again but it refuses to return. Click the tab number and close it. Open a new tab for bing.com and then repeat.

Bing.com images still freeze the browser.

Have bing.com as your default search engine, type something in the address bar to search for to see that most of the time its added a fullstop in the middle of the search text. Doesnt happen in Google.

Example:

What timezone is London in
What timezone.is London in

Then you will get an error like cannot open page timezone.is

Upgrading to a new version of Firefox from Google Play usually adds all those unwanted searches like Duck2Go, Amazon...

**Comment by amedyne** [comment] 2021-02-15 16:08
@BrokenShoeLace what Android device and version are you using, and what Firefox version are you experiencing this issue?

**Comment by BrokenShoeLace** [comment] 2021-02-15 16:16
It happens on Samsung S10+ and Samsung S21 Ultra. Still does it on 85.1.3 and all previous versions when it changed from an excellent browser to the newly designed version that no-one (including me) likes.

**Comment by kbrosnan** [comment] 2021-02-16 08:20
This sounds like a duplicate of bz-1686002 which is fixed in 86

**Comment by lobontiumira** [comment] 2021-03-31 14:05
Thank you for the report, @BrokenShoeLace!

I was not able to reproduce any of the mentioned issues on bing.com on Samsung Galaxy Note 8 (Android 9), on the 3/31 Nightly build.
Could you retry, please?

**Comment by BrokenShoeLace** [comment] 2021-04-05 21:42
Hi,

I am using Android 11, Firefox 87.0.0-rc.1 (Build #2015799099) and it is still happening.

To reproduce:

Open the above version of Fenix
Open an tab, write bing.com and it redirects to https://bing.com/?toWww=1&NUMBER_SHERE
Scroll down the page to the news pages trending on Bing, choose any of them
Now use the gesture BACK (MINIMISE | CLOSE | BACK) to see nothing happens
Click the number in the address bar and close the current tab (only one open in this example)
Click the (0) then click the ADD button to add a new tab.
Goto bing.com again and open any news item like before
Use the BACK gesture and now it will go back whereas the first time trying and closing the tab it never went back.

@kbrosnan this is not fixed in 86 if it still happens in 87.

**Comment by lobontiumira** [comment] 2021-04-07 11:55
Hi @BrokenShoeLace!
I was able to reproduce partially your issue with Samsung Galaxy Note 8 (Android 9).
I followed these steps:
- open Firefox, 
- go to bing.com, it redirected me to https://www.bing.com/?toWww=1&redig=B89CDCD5640A4C4FB61328BFA8220DAC  
- I searched for "Bezos", and selected one of the articles,
- tapped the back arrow from menu, I was redirected to the previous page, BUT tapping back again **did nothing**.  The forward button was greyed out and disabled, the back arrow was not responsive.

This issue is reproducible on all the builds: 87.0.0 RC, Beta 88.0.0-beta.4, and 4/7 Nightly.
Not reproducible on Chrome.
I recorded a short video. Is this the same behavior you're experiencing?


https://user-images.githubusercontent.com/40694158/113862340-efe91400-97b0-11eb-8070-24ed58de186b.mp4

**Comment by mcarare** [comment] 2021-06-24 09:20
The issue is reproducible on GV Example. The reason behind it is that bing adds additional history entries that prevent you from reaching the bing home page after performing a search. The workaround is to either press the back button fast until you reach that page or just simply press and hold the back button and select the history entry from the list you want to go back to.

**Comment by amedyne** [comment] 2021-06-24 14:15
Closing this one and will track https://bugzilla.mozilla.org/show_bug.cgi?id=1643554

**Closed by amedyne** 2021-06-24 14:15 UTC
Labels: Feature:Browsing, needs:gv, qa-triaged, 🐞 bug
