### ISSUE TITLE
Address bar has janky animation on autohide/show

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10065] opened 2020-04-20 20:47 UTC
## Steps to reproduce
1. Set address bar to top (this may apply to bottom as well, but I'm not using this configuration on this hardware, so I have not tested this). Also set to dark mode in customize (I don't see this in light mode, but it may still exist).
1. Open any page
1. Slowly scroll up and down on the page without removing finger from screen

### Expected behavior
The addressbar, including the toolbar (the panel containing the open tab switcher and hamburger menu) should animate smoothly OR follow the speed of my finger's scroll action.

The panel items should remain static within the toolbar, not move around within it. 

### Actual behavior
The address bar seems to animate within the toolbar panel, dancing up and down within the toolbar. This is distracting and looks very janky. It is easier to see when performing this action slowly, but looks and feels bad when doing this quickly, especially on pages which have a sticky top nav. 

See screen recording: [recording_20200420_163550.zip](https://github.com/mozilla-mobile/fenix/files/4506073/recording_20200420_163550.zip)

### Device information
* Android device: Moto G XT1031
* Fenix version: latest nightly from play store.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-86)

**Comment by mcomella** [comment] 2020-04-23 01:42
Thanks for filing. Front-end perf triage: we haven't typically focused on issues like these – animations and other forms of dropped frames instead on absolute durations – so we're hoping the Fenix team can take a look as part of their polish efforts. ecsmyth mentioned that the animations we introduce may perform well on higher end devices but can be disruptive to the user experience on lower end devices so we should ensure we're testing across the range of devices we support (perhaps we can leverage QA here?).

**Comment by liuche** [comment] 2020-04-23 20:48
This is a good bug to try out some profiling stuff from the training, and @csadilek can help if you get stuck. Since Fenix should start picking up new perf bugs and owning performance, we should put this or another perf bug into an upcoming sprint.

**Comment by mcomella** [comment] 2020-05-14 16:52
@MarcLeclair Please add a profile.

**Comment by mcomella** [comment] 2020-06-03 23:40
@MarcLeclair Please explain the behavior you experienced on the g5 (unable to reproduce?) and elaborate on the action item for Eric (is it important given low reproduce rate on G5?).

**Comment by kbrosnan** [comment] 2020-08-27 00:56
Possibly a duplicate of #10008

**Comment by cpeterso** [comment] 2022-12-23 20:54
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807362

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2022-12-23 20:54 UTC
Labels: 🐞 bug, performance, Feature:Toolbar, pin, perf:animation
