### ISSUE TITLE
FNX-4770 ⁃ Tracking Protection

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#1065] opened 2019-03-18 20:01 UTC
Owner: Product Manager
Purpose: PM to describe a feature and track overall activities, dependencies, progress

### Why/User Benefit/User Problem
* Description of Feature (Added by PM)
* Add any additional links or research related to this feature.
* Immediate task: Convert to epic and move to appropriate milestone

### Acceptance Criteria (Added by PM. For EPM to track when a Meta feature is done)
-UX completed
-User stories completed
-Strings written and approved
-QA completed
-Localization done

### What / Requirements (Added by PM and Eng Manager)
-UX Designs (Immediate task: Assign UX issue to this epic)
-User stories (to be created by PM)
-List dependencies on other issues/teams etc.

**Comment by vesta0** [comment] 2019-03-19 21:35
Duplicate of #97

**Closed** 2020-08-11 01:20 UTC
