### ISSUE TITLE
[Bug] Auto-sign in doesn't work on Beta

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#6521] opened 2019-11-08 12:07 UTC
## Steps to reproduce
1. login on Fennec.
2. Open a freshly installed Fenix Beta.
3. Observe the Sign in card on the onboarding section.
### Expected behavior
The "Sign me in" button is displayed to sign in automatically with the same account.
### Actual behavior
The app doesn't detect that you are signed in on Fennec.
*Works on Nightly and RC-3.2.1
### Device information

* Android device: any
* Fenix version: 3.0.0 Beta1

**Comment by softvision-miralobontiu** [comment] 2020-02-27 13:13
Reproducible also on Beta v4.0.0-beta.2 on Google Pixel (Android 10).

**Comment by liuche** [comment] 2020-02-27 16:37
@pocmo is this concerning?

**Comment by Diana-Rus** [comment] 2020-03-13 12:22
Hi, the issue is still reproducible with Samsung Galaxy S8+ (Android 8) build Firefox Preview Beta 4.1.0-beta.2.

**Comment by grigoryk** [comment] 2020-06-30 16:39
@liuche we don't need to worry about auto-sign-in in this context, now that Fenix is fully replacing Fennec. We do need to revise this functionality to have Fenix act as a sign-in provider for our other applications, at some point.

**Comment by softvision-miralobontiu** [comment] 2020-07-02 08:58
This issue still reproduces on the latest Beta build 79.0.0-beta.4 with Samsung Galaxy Tab S6 (Android 9).

**Comment by softvision-miralobontiu** [comment] 2020-07-15 08:32
This issue still reproduces on the latest Beta build 79.0.0-beta.6 with Samsung Galaxy Tab S6 (Android 9).

**Comment by pocmo** [comment] 2020-07-15 10:46
So, at this point we should just remove the auto-sign in card from Fenix.

**Comment by Mugurell** [comment] 2020-10-05 15:16
> @liuche we don't need to worry about auto-sign-in in this context, now that Fenix is fully replacing Fennec. We do need to revise this functionality to have Fenix act as a sign-in provider for our other applications, at some point.

Created for this https://github.com/mozilla-mobile/fenix/issues/15694

**Comment by Mugurell** [comment] 2020-10-05 15:20
I'd say that at the moment,
similar to what we've done in https://github.com/mozilla-mobile/fenix/issues/13949 where we've just disabled the code but kept it for future uses
since this is no-op
we don't have anything to do, not even a need to remove it from the app
since the intent is to add the functionality that would make this useful again, in https://github.com/mozilla-mobile/fenix/issues/15694.
Asking @liuche to confirm.

**Comment by liuche** [comment] 2020-10-07 15:35
@Mugurell let's remove that card from the first-run onboarding (if it's still there). And to be safe, until we hear about whether we need the auto-signin code for future work, let's keep it in.

@grigoryk do you think you'll need the auto-sign-in code (that backed the auto-signin card) as a base to support Fenix acting as a sign-in provider? Otherwise we could remove it.

**Comment by Mugurell** [comment] 2020-11-02 10:35
I went with just removing the code that would trigger this banner but kept it for when #15694 would make this a usable feature again.

**Comment by Mugurell** [comment] 2020-11-06 12:43
The PR is merged but giving that the change doesn't touch anything else and the banner didn't appear recently anyway I'll closing this.

**Closed by Mugurell** 2020-11-06 12:43 UTC
Labels: Feature:Sync, P2, S3, 🐞 bug
