### ISSUE TITLE
SCROLLING ENHANCEMENT

### ISSUE THREAD

**Issue by Dev-i-l** [mozilla-mobile/fenix#15447] opened 2020-09-26 08:47 UTC
ADD A SCROLLING BAR LIKE THE ONE IN SAMSUNG BROWSER FOR A SMOOTH SCROLLING EXPERIENCE.

**Comment by Dunexus** [comment] 2020-09-26 13:21
Duplicate of https://github.com/mozilla-mobile/fenix/issues/1758

**Closed** 2020-09-26 13:55 UTC
Labels: needs:triage
