### ISSUE TITLE
Private mode button should be close to address bar

### ISSUE THREAD

**Issue by PhilippMundhenk** [mozilla-mobile/fenix#3754] opened 2019-06-28 07:38 UTC
When switching often between standard and private mode, the placement of private mode button at the top of the screen is not ideal. Closer to bottom of the screen (like address bar) would be useful, especially considering large phones nowadays.

**Comment by NotWoods** [comment] 2019-07-09 19:03
Duplicate of #561

**Closed by NotWoods** 2019-07-09 19:03 UTC
