### ISSUE TITLE
FNX-3438 ⁃ [Bug] Nightly crashex

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#10328] opened 2020-04-30 19:03 UTC
## Steps to reproduce
update nightly
start nightly

### Expected behavior
not crash

### Actual behavior
crash

### Device information
* Android device: one plus 5t
* Fenix version: nightly

**Comment by eliserichards** [comment] 2020-04-30 19:25
Related to #10320

**Comment by TitanNano** [comment] 2020-04-30 23:36
Probably a dupe of #10334

**Comment by andreicristianpetcu** [comment] 2020-05-01 07:29
it's fixed now

**Closed** 2020-08-11 00:29 UTC
Labels: P1, 🐞 bug
