### ISSUE TITLE
Backing out to the New Tab Page can cause extra tabs to be opened

### ISSUE THREAD

**Issue by cartr** [mozilla-mobile/fenix#13775] opened 2020-08-13 05:10 UTC
## Steps to reproduce

Let's say you currently have no tabs open, and you want to visit Wikipedia.

1. Tap the Google top-sites icon. Whoops! That was the wrong one!
2. No worries, happens to the best of us. Press the system back button to return to the new tab page.
3. Tap the Wikipedia top-sites icon.

### Expected behavior

You now have one tab open, with Wikipedia.

### Actual behavior

You now have two tabs open, one with Google and one with Wikipedia.

### Device information

* Android device: ASUS ZenFone 6
* Fenix version: Nightly 200812 06:01 (Build #2015757491)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4941)

**Comment by s-ankur** [comment] 2020-08-13 08:30
Duplicate of #8254

**Comment by liuche** [comment] 2020-08-17 23:58
Need UX to chime in here on whether this is working as intended.

**Comment by Standard8** [comment] 2020-08-18 07:34
My slightly different reasoning from #8254 is that I use top-sites/collections for viewing my regular sites. I visit one, read it, go back, read the next etc.

Unfortunately due to the current design, after reading one or more sites I have to spend time and interactions going to open the tab list and closing them.

If I forget to do that, I discovering later on that I've got a load of now useless tabs open. They're useless to me because they would need reloading - which is lots of extra interactions compared to just tapping one of the top sites on my new tab page.

**Comment by apbitner** [comment] 2020-08-18 16:30
@topotropic thoughts on this flow?

**Comment by topotropic** [comment] 2020-08-20 20:29
I agree that it would be more intuitive to NOT create a new tab when navigating back to home and opening a new site; but I also remember that we discussed this in the past and it was difficult to implement due to the hub/home model we follow.

**Comment by liuche** [comment] 2020-10-08 01:40
Would this be handled by the homescreen flow changes that you're working on @ekager ? If so, could you dupe, otherwise, this might be something that we want to pull into a sprint.

**Comment by Smaehtin** [comment] 2020-11-12 20:02
I agree. The current behavior is really unintuitive and inconsistent.
Navigating back from a tab that was opened by the "Open link in new tab" action does close the tab, but navigating back from a tab that was opened from the homepage does not close the tab. This inconsistent behavior is really confusing and annoying.

**Comment by Smaehtin** [comment] 2021-03-13 22:46
Any updates on this? Is this still something that is being looked into?

**Comment by Smaehtin** [comment] 2021-07-30 08:02
I can't believe this has not been addressed yet. This is honestly some of the worst, most frustrating user-experience I have encountered in an app.
Take literally any other browser app on Android and:
1. Open a new tab
2. Go to google.com
3. Trigger the Android "back action" (back gesture, hardware/software back key)

What happens in all other browers except for Firefox? The tab is closed. On Firefox, the tab is still open. Why?

**Comment by b1100111** [comment] 2022-01-26 17:03
Please do not make this stale.  It still is a super annoying bug in FF Android.  Lots of changes get made around it but it is never fixed and it use to work perfectly before the graphics rewrite.

**Comment by boek** [comment] 2023-01-27 01:54
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812915

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-27 01:54 UTC
Labels: 🐞 bug, Feature:Tabs, pin
