### ISSUE TITLE
[Bug]: wrong behaviour when tapping url bar Fenix nighlty

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#20880] opened 2021-08-17 05:34 UTC
### Steps to reproduce

latest nighlty recently introduced old fennec behaviour to show top sites when tapping url bar.
I was so happy to finally see this that I did not even noticed that top sites still insist opening in a new tab just like the "wrong' behaviour of the home button (which is totally useless since it's nothing more that a NEW tab button without keyboard) is there any hope to have ever see opening top sites in the existing tab just like old fennec or Samsung internet? 

### Expected behaviour

top sites MUST open in the existing tab

### Actual behaviour

top sites open in New tab 

### Device name

xiomi 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

93

**Comment by sflorean** [comment] 2022-02-16 13:56
Tested with OnePlus 9 (Android 11) on latest Firefox versions and indeed the behavior is as described.
I will close this as duplicate of #15866, please follow the discussions there. Thank you!

**Closed by sflorean** 2022-02-16 13:56 UTC
Labels: 🐞 bug, Feature:HomeScreen, Feature:TopSites, wontfix
