### ISSUE TITLE
[Bug] Bottom right-edge swipe gesture blocked on initial page

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#19048] opened 2021-04-15 09:24 UTC
Firefox blocks the bottom right-edge swipe-up gesture on the initially launch page.

I have my system configured with swipe-up gestures for Recent, Home, and Back, in that order. When running Firefox, the Back gesture, assigned to the bottom right of the screen, doesn't work on the initially opened page. The other two gestures work.

The issue only appears to happen on having launched Firefox via an external link and even then just for that page, i.e., if following a link on the launched page, one can navigate back to the original page but then one cannot use back to exit Firefox.

### Version
Nightly 210414 17:01 (Build #2015804619)

##s Device
Samsung Note 9, Android 10

**Comment by mrandreastoth** [comment] 2021-04-15 09:32
### Device settings
![Screenshot_20210415-112925_Settings](https://user-images.githubusercontent.com/26897855/114847595-25f44c80-9dde-11eb-8026-52c63c6a099b.png)

**Comment by sflorean** [comment] 2021-05-28 09:46
Tested on latest Nightly 5/28 with Samsung Note 10 (Android 11) and Pixel 4XL (Android 11) and couldn't reproduce the issue. 
@mrandreastoth is this still reproducible for you?

**Comment by mrandreastoth** [comment] 2021-05-28 11:16
> 
> 
> Tested on latest Nightly 5/28 with Samsung Note 10 (Android 11) and Pixel 4XL (Android 11) and couldn't reproduce the issue.
> @mrandreastoth is this still reproducible for you?

Seems OK now and this on 5/27.

**Comment by sflorean** [comment] 2021-05-28 12:16
Based on the above comment, I will close this. If the issue reappears, please comment/open the bug.

**Comment by mrandreastoth** [comment] 2021-06-05 05:01
> Based on the above comment, I will close this. If the issue reappears, please comment/open the bug.

The issue just reappeared...

Firefox Nightly: 91.0a1 (Build #2015814411)
AC: 91.0.20210603145049, e9c3f15a2
GV: 91.0a1-20210603094827
AS: 78.0.0

**Comment by mrandreastoth** [comment] 2021-06-23 19:33
Still happening.

Firefox Nightly 91.0a1 (Build #2015817867

**Comment by mrandreastoth** [comment] 2021-06-23 19:38
Note that the issue is now dependent on launched link. Some links will behave whilst others won't.

**Comment by SoftVision-LorandJanos** [comment] 2021-06-28 11:30
Hi @mrandreastoth ! I've tested on the the latest Nightly (91.0a1 - 2021-06-28T05:09:42.643) and I cannot reproduce the issue you described.
Tested devices: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).
As this issue is link dependent, could you give us some examples where you had the issue? Thank you!

**Comment by mrandreastoth** [comment] 2021-06-30 08:43
> 
> 
> Hi @mrandreastoth ! I've tested on the the latest Nightly (91.0a1 - 2021-06-28T05:09:42.643) and I cannot reproduce the issue you described.
> Tested devices: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).
> As this issue is link dependent, could you give us some examples where you had the issue? Thank you!

Just in case my reaction didn't make much sense: yes, I will provide an example when it next happens.

**Comment by SoftVision-LorandJanos** [comment] 2021-12-27 14:04
As this is still not reproducible on the latest builds, I will close this ticket.
If any further details or example will be provided, the ticket can be reopened.
Tested on the:
- latest Nightly 97.0a1 (2021-12-27).
- latest Beta 96.0.0-beta5.
- latest Release 95.2.0.
Devices used:
- Google Pixel 4 (Android 11).
- Samsung Galaxy Tab 3 (Android 9).
- Motorola Nexus 6 (Android 7.1.1).

**Closed by SoftVision-LorandJanos** 2021-12-27 14:04 UTC
Labels: 🐞 bug, needs:triage, wontfix, qa-triaged
