### ISSUE TITLE
FNX-12358 ⁃ [Bug] Crash when tap the password input box on some website

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#11424] opened 2020-06-10 14:35 UTC
## Steps to reproduce
open https://mail.163.com
tap the password input box
crash

https://imgur.com/55axd9u.mp4

`0b7edf67-3fd8-465d-8802-d78664c85e0f

## java.lang.IllegalStateException: origin must not be null
java.lang.IllegalStateException: origin must not be null
	at kotlin.jvm.internal.ArrayIteratorKt.checkExpressionValueIsNotNull(ArrayIterator.kt:1)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.toLogin(GeckoPromptDelegate.kt:3)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.access$toLogin(GeckoPromptDelegate.kt:1)
	at mozilla.components.browser.engine.gecko.prompt.-$$LambdaGroup$ks$hn0Qifo2sAuTkYiPOrS3tHhq-z4.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:22)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.concept.engine.EngineSession.notifyObservers(Unknown Source:7)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.onLoginSelect(GeckoPromptDelegate.kt:4)
	at org.mozilla.geckoview.GeckoSession.handlePromptEvent(GeckoSession.java:14)
	at org.mozilla.geckoview.GeckoSession$Listener.handleMessage(GeckoSession.java:4)
	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:1)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

`

### Device information
* Android device: ?
* Fenix version: ?
null (Build #2015744507)
45.0.20200603130110, f33bbcb22
GV: 78.0-20200601142750
AS: 60.0.0
Friday 6/5 @ 3:45 PM

**Comment by lindongbin** [comment] 2020-06-15 10:15
> 
> 
> I think this was fixed by [mozilla-mobile/android-components#7182](https://github.com/mozilla-mobile/android-components/pull/7182)
> 
> Could you download the latest Nightly and try again?

I use the fennec-production:

null (Build #2015746379)
45.0.20200603130110, f33bbcb22
GV: 78.0-20200601142750
AS: 60.0.0
Monday 6/15 @ 9:21 AM

this is crash report
https://crash-stats.mozilla.org/report/index/d1cd30b9-7f0c-4011-a4aa-68e020200615

**Comment by liuche** [comment] 2020-06-23 00:48
If this landed in AC 6/1, it should be in the 5.2 release which has AC 46 (released 6/16).

@ekager is there some flag that could be causing this to break on the release channel (Firefox Preview)? https://sentry.prod.mozaws.net/operations/fenix/issues/8818653/?query=release%3Aorg.mozilla.fenix-5.2.0

**Comment by lindongbin** [comment] 2020-06-23 01:15
not crash on fennec production
5.2.0 (Build #2015747019)
AC: 46.0.0, bca4c5c91
GV: 78.0-20200612174529
AS: 60.0.0
Thursday 6/18 @ 5:05 PM

**Comment by lindongbin** [comment] 2020-06-23 01:21
crash on fennec production

5.2.0 (Build #2015747019)
AC: 46.0.0, bca4c5c91
GV: 78.0-20200612174529
AS: 60.0.0
Thursday 6/18 @ 5:05 PM

https://crash-stats.mozilla.org/report/index/a0214587-f755-4bad-91e3-e46fe0200623

**Comment by ekager** [comment] 2020-06-25 18:09
Not seeing it on Nightly at all 🤔 
https://sentry.prod.mozaws.net/operations/fenix-nightly/?query=is%3Aunresolved+origin+must+not+be+null&statsPeriod=14d

**Comment by ekager** [comment] 2020-06-25 18:10
Oh it's because I never updated the GV beta dimension with the fix 😭 adding now

**Comment by ekager** [comment] 2020-06-25 18:14
Should be resolved by https://github.com/mozilla-mobile/android-components/pull/7515

**Comment by lindongbin** [comment] 2020-07-03 12:12
fixed on
null (Build #2015749827)
AC: 48.0.3, ce6247fb8
GV: 79.0-20200629163142
AS: 61.0.7
Friday 7/3 @ 8:43 AM

**Comment by sflorean** [comment] 2020-07-03 14:26
I was able to reproduce the crash on an affected build with Xiaomi Redmi Note 8T (Android 9) and I can confirm that the browser is not crashing following the steps from the description on Firefox Nightly 7/3 on the same device.

**Closed** 2020-08-11 04:01 UTC
Labels: Feature:Logins, b:crash, eng:qa:verified, needs:triage, 🐞 bug
