### ISSUE TITLE
Open current private page in non-private mode (and reverse) by long pressing the nav bar

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#5170] opened 2019-09-08 13:56 UTC
### Why/User Benefit/User Problem
As a user browsing in private mode, I want a quick and easy way to open the current page in normal mode, in order to retrieve all the context (session and cookies).
My preferred navigation mode is private mode, but sometimes I end up on a page where I want to go on browsing in a logged-in context (like an Amazon page, or a Gihub page ;) ). 
As the normal mode has all the session cookies, I just need to open the same page in normal mode. 
The opposite could also be considered (open the "normal" current page in private mode).

### What/Requirements
Long pressing on the nav bar in private mode could offer an option like "Leave Private mode", or something like "Copy & Go public" (and reverse, in normal mode, an option like "Copy & Go private")

### Acceptance Criteria (how do I know when I’m done?)
- In non-private mode, I can quickly choose to open the current page in private mode by long pressing on the URL bar
- In private mode, I can quickly choose to open the current page in non-private mode by long pressing on the URL bar

**Comment by klint** [comment] 2019-09-08 15:20
Responding here a question asked by @Djfe in #4155.
History wise, it would be the same as now when you long click on a link in a page in normal and choose to open it in a new tab in private mode: a brand new tab is opened in the other mode, with no history there. And of course the original page stays in the tab of the original mode.

Actually, this makes me notice that in private mode, there is no option to open a link (within the page) in the normal mode when long pressing on the link (which could be useful for the same reason as explained above), while there is one in normal mode to open the link in private mode.

So, having in *both* modes:
- a simple way to open the current page in the other mode (with no history) by long press in the nav bar, 
- and a simple way to open a link within a page in the other mode (with no history) by long press on the link itself 
...that would be quite useful :)

**Comment by ekager** [comment] 2019-09-12 03:49
We just added toolbar quick actions on long press in #4155 so we have the ability to add something like this now

**Comment by liuche** [comment] 2020-09-10 00:06
Dupe of #10132

**Closed by liuche** 2020-09-10 00:06 UTC
Labels: Feature:PrivateBrowsing, feature request 🌟
