### ISSUE TITLE
FNX-12582 ⁃ [Bug] loading bar hidden when navigating within a domain

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#11613] opened 2020-06-15 21:14 UTC
## Steps to reproduce
Use the top position for the search bar
Go to a web page
Hide the search bar by scrolling down
Click on a link
The loading bar is nowhere to be seen

### Expected behavior
The loading bar is clearly shown at the top of the screen

### Actual behavior
The loading bar is hidden with the search bar

### Device information
* Android device: 9
* Fenix version: nightly as of 15/06/2020

**Comment by sblatz** [comment] 2020-06-15 21:32
This sounds like a regression. We definitely used to do this. Is `expand()` not getting triggered?

**Comment by sblatz** [comment] 2020-06-15 21:33
@Octoton does this happen on all sites for you?
The toolbar should expand anytime you navigate to a new domain, but not within the same site, I believe.

**Comment by Octoton** [comment] 2020-06-16 07:35
You're right, when I change website, the search bar expande correctly
However, on the same one the problem occure, for example on github when going from issues to pull request

**Comment by sblatz** [comment] 2020-06-16 20:42
Is this a security concern if users are staying within the same domain? My guess is no, but I'll put this in group triage just in case!

**Comment by liuche** [comment] 2020-06-23 17:41
Action item here:
- Check with GV if this is intended behavior (that the nav bar isn't re-showing when loading within a domain) - should we use something else like `onProgressChanged`? If that's the intended behavior, we could fix this for release
- if not, we can do this after release

**Comment by sblatz** [comment] 2020-06-23 19:41
I remember why we don't do `onProgressChanged` now. Basically our force expand doesn't have a "force expand and LOCK until done loading" functionality yet. So, if we `expand` in each progressChanged, if the user is scrolling down, the behavior will be that the toolbar is fighting with them to stay expanded which feels really odd. 

I don't think it's feasible that we add this "locked" behavior before release (given how many issues we've had with toolbars & GV interacting in the past).

@vesta0 / @liuche what should we do here?

**Comment by sblatz** [comment] 2020-06-23 19:48
Emily suggested a couple more places we could try. Will take a look in a bit!

**Comment by Octoton** [comment] 2020-06-23 20:07
Can't you just show the loading bar by putting it outside the search bar instead of inside, thus when the search bar is hidden, the loading bar will always be shown

**Comment by abodea** [comment] 2020-06-30 14:42
Verified as fixed on **Fenix** **Beta** **79.0.1 & 79.0.2** with **Google Pixel 4 XL (10).**

![20200630-172715](https://user-images.githubusercontent.com/42831109/86140024-15960e00-baf9-11ea-909c-5976eafeeb6e.gif)

**Closed** 2020-08-11 04:30 UTC
Labels: Feature:Toolbar, eng:qa:verified, needs:product, 🐞 bug
