### ISSUE TITLE
FNX-11904 ⁃ Add Reader Mode only (not Open in App) to address bar

### ISSUE THREAD

**Issue by apbitner** [mozilla-mobile/fenix#11045] opened 2020-05-29 16:07 UTC
## User Story
As a user, I want to easily know if a site supports reader mode so I have the option to easily switch to reader mode and back, without being distracted by the blue dot every time. 

This features are currently not as easily discoverable in the toolbar menu and there are issues with the current implementation of the blue dot notification.

### Acceptance Criteria
* I am notified if a site supports reader mode without having to open the toolbar menu.
* Reader mode button appears in URL bar when available.
* I don't see the reader mode option in the toolbar menu.
* Telemetry ticket: #11269 11269

## UX
**Specs**: [Abstract](https://share.goabstract.com/ea3f49e5-5ff9-45b4-a44b-3aad13846467)

*Note in the mocks that reader mode appearance settings is being moved to the app settings

**Comment by Dunexus** [comment] 2020-05-29 19:05
Looking at the abstract, it will reduce the amount of text shown in the address bar.
We already had issues about the address bar not showing enough text, see https://github.com/mozilla-mobile/fenix/issues/3727.

**Comment by SS1113** [comment] 2020-05-29 23:37
@Dunexus Having the Reader Mode button in the adress bar is intuitive, I can confirm that I have rarely used it or even forgot it's even there. Having it in the address bar will definitely make me use it more instead of having it in the toolbar menu. But I also agree that it'll make text show in the address bar even shorter.

**Comment by yoasif** [comment] 2020-05-30 07:14
See also https://github.com/mozilla-mobile/fenix/issues/6639

@apbitner Have you given any thought to https://github.com/mozilla-mobile/fenix/issues/7912 ? I think it makes sense to make reader mode appearance options more discoverable - desktop just did a revamp of this as well in https://bugzilla.mozilla.org/show_bug.cgi?id=1550836

**Comment by cadeyrn** [comment] 2020-05-30 07:22
> Looking at the abstract, it will reduce the amount of text shown in the address bar.
We already had issues about the address bar not showing enough text, see #3727.
Won't this be an issue ?

Since #3727 was filed the "https://" and "www." was removed from the URL in the address bar and the spacing between the toolbar icons was shortened. When #3727 was filed Fenix showed less of the URL in the address bar than Fennec. Now Fenix shows even a bit more of the URL in the address bar than Fennec. I don't say it's perfect if the visible length of the URL will be reduced again but the result shouldn't be worse than in Fennec with one icon added. If there was an app and the reader mode available Fennec showed even two icons in the address bar and according to the description of this issue Fenix will show not more than one icon (if the hypothesis holds) so in these situations Fenix will still have a longer visible part of the URL in the address bar than Fennec.

**Comment by apbitner** [comment] 2020-06-02 16:01
@Dunexus Yes, to @cadeyrn 's point when we removed "https://www" it freed up some room for us to add an additional icon without losing too much screen real estate.

**Comment by apbitner** [comment] 2020-06-02 16:04
@yoasif so far our research has shown that reader mode preferences are not something users change very often, and therefore we feel comfortable moving it to the app settings. The desktop revamp is nice, but on mobile we just don't have as much screen real estate to make those options as easily accessible.

**Comment by liuche** [comment] 2020-06-04 16:43
We're going to scope this down JUST for reader mode.

**Comment by sblatz** [comment] 2020-06-05 18:31
Changing this down to an E3 as it only includes moving ReaderView and not the appearance controls now.

**Comment by sblatz** [comment] 2020-06-05 18:33
Breakout issue to move reader appearance: https://github.com/mozilla-mobile/fenix/issues/11282

**Comment by softvision-miralobontiu** [comment] 2020-06-09 09:05
Verified as fixed on the latest Nightly build from 6/9 with Google Pixel (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1):
* I am notified if a site supports reader mode without having to open the toolbar menu,
* the reader mode button appears in the URL bar when available,
* I don't see the reader mode option in the toolbar menu.

**Closed** 2020-08-11 02:44 UTC
Labels: E3, Feature:Discovery, Feature:OpenInApp, Feature:ReaderMode, eng:qa:verified, eng:ready

**Comment by yoasif** [comment] 2020-09-04 03:02
Filed https://github.com/mozilla-mobile/fenix/issues/14705 for the open in app feature.
