### ISSUE TITLE
FNX2-15138 ⁃ [Bug]Chinese Pinyin input issue

### ISSUE THREAD

**Issue by lomomcat** [mozilla-mobile/fenix#12282] opened 2020-07-05 04:12 UTC
## Steps to reproduce
Input Chinese anywhere in the browser include URL bar with Chinese Pinyin input.
[Bug demo](https://youtu.be/0TSfe_CypdE)

### Expected behavior
Correct input.

### Actual behavior
More letters before.

### Device information
* Android device: Xiaomi Redmi Note 8 Pro
* Fenix version: Nightly 200704 06:01
* Android Version: 10 (MIUI 12, latest patch)
* SoC: MediaTek Helio G90T(ARM64, ARMv8.2-A)

**Comment by lomomcat** [comment] 2020-07-05 23:34
Have anyone whom is Chinese or uses Chinese Pinyin input met this problem?

One time i showed **_Fenix_** to a friend of mine to encourage him to change **Chrome** to **Firefox** (**_Fenix_**).

But when i was inputting Chinese with Pinyin input,there were always some extra English letters before the Chinese sentence that I want to input.

That's so embarrassing.😭

**Comment by kyouma** [comment] 2020-07-07 21:53
As for me, both the Samsung Keyboard and the Multiling O Keyboard work correctly on different sites and in the address bar.
Nightly 200706 06:01 (Build #21880609), English language UI
Galaxy S10e, Android 10, Russian language UI

**Comment by lomomcat** [comment] 2020-07-07 23:55
@kyouma But Chinese Pinyin input is a little bit special. Some English letters can only be spelled into one Chinese character. Each spelling has a fixed form of ending.

In the environment I encountered, every time a Chinese character was successfully created by the Pinyin input method, the English that made it up would be redundant before.

This does not happen sometimes, but it happens often.

There is no such problem in other software such as Google Chrome, Twitter, Youtube and _**Fennec**_.

**Comment by ekager** [comment] 2020-07-08 01:33
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1651257

**Comment by makotokato** [comment] 2020-07-08 02:33
@lomomcat What's you IME?  As long as watching this video, it may not be GBoard. So could I get it from Play store?

**Comment by lomomcat** [comment] 2020-07-08 06:17
@makotokato 

The MIUI12 (based on Android 10) built-in Chinese Pinyin IME. This IME is specially designed for MIUI, so you may think it looks like the IME of iOS. You can get it only from Xiaomi App Store which provides service in China. Moreover, the OS of you phone must be MIUI such as Xiaomi MI 10 and so on.

[Xiaomi App Store](https://app.mi.com/)

There is no complete Chinese lexicon database in Google Pinyin IME. What's more, Google Pinyin IME does not support speech recognition. As a result, Google Pinyin IME may not be applicable in China now.

Thank you for understanding.

Yours truly.
![Xunfei Pinyin IME Xiaomi Version](https://user-images.githubusercontent.com/62339707/86884010-835bbe80-c125-11ea-9d8e-66d3fb6b0fcf.jpg)

**Comment by lomomcat** [comment] 2020-07-08 06:54
@makotokato 

I leave a package here. But if your device is not by Xiaomi, it may not apply.

**Firefox Send** is improving and unavailable. I can only leave a **Google Drive** Share link.

[Share link](https://drive.google.com/file/d/1-2QtexOqStw37HlIGm9pNf_oETAwr12I/view?usp=drivesdk)

Thanks!

**Comment by makotokato** [comment] 2020-07-08 07:24
Thanks, I got one. Hmm, input is often broken when using Xiomi's keyboard. I am looking this.

**Comment by lomomcat** [comment] 2020-07-14 02:41
> Thanks, I got one. Hmm, input is often broken when using Xiomi's keyboard. I am looking this.

Problem has already been sloved in _Nightly 200713 06:47_, I can close it.

**Comment by makotokato** [comment] 2020-07-14 03:59
I can still reproduce this on 200713 since this is timing issue of GeckoView's input system.

**Comment by lomomcat** [comment] 2020-07-14 04:22
> I can still reproduce this on 200713 since this is timing issue of GeckoView's input system.

Yes, I found it.
[YouTube link](https://youtu.be/B1hLsTJt0pc)

**Comment by makotokato** [comment] 2020-08-04 07:33
@lomomcat
Could you verify on the latest Firefox (Fenix) Nightly since I have landed the fix to GeckoView?  As long as I test this, this is fixed.

**Comment by lomomcat** [comment] 2020-08-04 09:37
> @lomomcat
> Could you verify on the latest Firefox (Fenix) Nightly since I have landed the fix to GeckoView?  As long as I test this, this is fixed. 

Yes! Thank you!

**Comment by lomomcat** [comment] 2020-08-10 17:07
@makotokato 
I found another problem.
![video](https://github.com/lomomcat/fenix/blob/master/issue/Screenrecorder-2020-08-11-00-47-58-79.mp4)

**Comment by makotokato** [comment] 2020-08-11 10:40
> @makotokato
> I found another problem.
> https://github.com/lomomcat/fenix/blob/master/issue/Screenrecorder-2020-08-11-00-47-58-79.mp4

This is another issue. So, could you file new issue instead of reopen?  As long as I look your screencast, it might be address bar (GeckoView doesn't handle address bar)

**Comment by lomomcat** [comment] 2020-08-11 11:12
> > @makotokato
> > I found another problem.
> > https://github.com/lomomcat/fenix/blob/master/issue/Screenrecorder-2020-08-11-00-47-58-79.mp4
> 
> This is another issue. So, could you file new issue instead of reopen?  As long as I look your screencast, it might be address bar (GeckoView doesn't handle address bar)

fine

**Comment by lomomcat** [comment] 2020-08-11 11:12
> > @makotokato
> > I found another problem.
> > https://github.com/lomomcat/fenix/blob/master/issue/Screenrecorder-2020-08-11-00-47-58-79.mp4
> 
> This is another issue. So, could you file new issue instead of reopen?  As long as I look your screencast, it might be address bar (GeckoView doesn't handle address bar)

Okay.

**Comment by lomomcat** [comment] 2020-08-11 11:40
@makotokato 
[#13500](https://github.com/mozilla-mobile/fenix/issues/13500)

**Comment by lomomcat** [comment] 2020-11-20 00:23
@makotokato The problem is repeated in the latest Nightly version.
Version: Nightly 201119 17:01

**Closed** 2021-05-27 04:22 UTC
Labels: Feature:IME, needs:gv, wontfix, 🐞 bug
