### ISSUE TITLE
Tab reorganization

### ISSUE THREAD

**Issue by thepooptoob** [mozilla-mobile/fenix#14415] opened 2020-08-29 07:17 UTC
Tab reorganization is extremely important, especially to the way I use the app. Please implement this as soon as possible.

**Comment by cadeyrn** [comment] 2020-08-29 08:04
What exactly does "Tab reorganization" means for you? Chaning the order of the tabs? Then it's a duplicate of #2487.

**Comment by Derpy4** [comment] 2020-08-29 22:09
I'm not speaking for them because I don't know the proper term for the issue I'm having is, but if I had to call it anything it would be tab reorganization so maybe. 

My problem is that when I look at my list of tabs there is only one column of tabs and the picture of the web page is too small and there is way too much text on the right-hand side. 

Before the update there were two columns of tabs and the information about the site was very very brief and just above each tab. 

That was a lot better for me because I always have 100+ tabs because it's more efficient than having 100+ bookmarks and deleting them when I'm done with them. I figure there must be other people who need their tabs organized in a specific way in order to use the app efficiently the way they like to.

**Comment by kbrosnan** [comment] 2020-08-30 08:22
Closing as a duplicate of #2487.

**Closed by kbrosnan** 2020-08-30 08:22 UTC
Labels: needs:triage
