### ISSUE TITLE
[Bug]:  browser deleted history

### ISSUE THREAD

**Issue by SimonGray653** [mozilla-mobile/fenix#22379] opened 2021-11-09 02:37 UTC
### Steps to reproduce

I don't know how to reproduce this bug

### Expected behaviour

Keep my history

### Actual behaviour

I had a small panic. When it looked like the mobile browser deleted my history, but it was just a glitch. Now I am afraid to log back into my account on mobile.

### Device name

Samsung A51 5G

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

94.1.1 (Build #2015842491)

### Additional information

It didn't crash when this happened, so I can't give a log file.

Update: Looks like it was the mobile browser running out of ram to display the history. After deleting some history from the mobile side of the browser anyways, it looks like error fixed itself. I will keep ya'll posted.

**Comment by amedyne** [comment] 2021-11-09 18:37
@SimonGray653 Thank you for the update on what you experienced about this issue. Keep us posted if you encounter the problem again.

**Comment by LaurentiuApahideanSV** [comment] 2022-04-20 12:36
Since the reporter has not responded in a long time and we are unable to reproduce the issue, I will close this issue as fixed.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)

**Closed by LaurentiuApahideanSV** 2022-04-20 12:36 UTC
Labels: 🐞 bug, needs:triage
