### ISSUE TITLE
HomeFragment should observe wallpaper changes.

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26555] opened 2022-08-19 17:23 UTC
With the upcoming wallpaper selection tool defined in https://mozilla-hub.atlassian.net/browse/FNXV2-21134, we need a way to actively observe changes to the current wallpaper when they are updated from the tool. The following conditions should be met:

- there is no noticeable flashing from an already selected wallpaper that loads after the rest of the home screen during startup or returning to home from anywhere else in the app
- wallpapers behave correctly during orientation changes
- the current wallpaper is observed and updated

For context, this issue is a result of conversation that took place in this comment thread: https://github.com/mozilla-mobile/fenix/pull/26515#discussion_r948479481

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21342)

**Comment by Mugurell** [comment] 2022-08-23 09:11
With the code from https://github.com/mozilla-mobile/fenix/pull/26515/commits/b22e500e13c4ba32e59ea7c8573c0362cfa246f8 applied I see cases in which the wallpaper is not applied until coming back to the hoomescreen.

https://user-images.githubusercontent.com/11428869/186119906-2e39309a-04b4-4c6b-a945-aefb483b885d.mp4

**Comment by Mugurell** [comment] 2022-08-23 11:59
Testing the implementation from https://github.com/mozilla-mobile/fenix/commit/b22e500e13c4ba32e59ea7c8573c0362cfa246f8 on a OnePlus 7T Pro I see that :
- `onCreateView` from which the wallpaper is set (synchronously) already takes ~140ms.
- `setWallpaperToCurrent` would add another ~100ms.
(Looks like there is enough time to offload the most heavy processing to another thread while `onCreateView` is churning and we should have all data ready in `onStart`)
- `requireComponents.useCases.wallpaperUseCases.loadBitmap(wallpaper)` takes ~80ms
- `bitmap.scaleToBottomOfView` takes ~2
(Adding this here just because I think that loading and scaling the bitmap can be done together on a separate thead).

At a quick glance it seems like we can set the wallpaper without affecting performance or at least significantly reducing the slowdown.

An important issue that remains is shown in the above video and seems like a newly introduced one: reading the current wallpaper from the appState may happen too soon and then we would not show the wallpaper.
Seems like previously we were waiting for state updates.

**Comment by Mugurell** [comment] 2022-08-23 12:35
Looking at this more it seems like the previous idea of parallelizing setting the wallpaper with all the setup in `HomeFragment` up until `onStart` is blocked by `wallpaperUseCases.initialize` which updates the wallpaper in store and takes ~250ms-~300ms. We're in a race with that.
Trying to read the current wallpaper a bit higher in `HomeFragment` would get the `default` wallpaper so it looks like we're left with 2 scenarios:
- stick with the current implementation which observes store updates and automatically sets the wallpaper **when** available. Just move [`displayWallpaperIfEnabled` ](https://github.com/mozilla-mobile/fenix/blob/7bfd6caa5b04fe15f4a296a937abdb78b29509c2/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L393) higher and observe the store from at least the start of `onCreatedView` - switch off from the current [`store.flow`](https://github.com/mozilla-mobile/fenix/blob/7bfd6caa5b04fe15f4a296a937abdb78b29509c2/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L928) call which will only start observing in `onStart`.
In my opinion this is the best approach and would allow setting the wallpaper as soon as that is available, certainly faster than currently (just because we don't wait until `onStart` to start those 100ms needed for setting the wallpaper).
- use the approach proposed in https://github.com/mozilla-mobile/fenix/pull/26515 complete with the `observeWallpaperChanges` call which would improve things but might skip some first wallpaper setups because of the race with wallpapers initialization. Don't think we have a way of knowing now home many times we'd loose the race, I'd say it's highly dependent on the device and future app refactorings.

**Comment by MatthewTighe** [comment] 2022-08-23 16:16
I don't have a strong opinion about the direction we take with this, but wanted to add some additional context. 

> `wallpaperUseCases.initialize` which updates the wallpaper in store and takes ~250ms-~300ms.

At a glance, these numbers look pretty concerning. However, we are now loading metadata about wallpapers from the remote server. Accounting for network time, this actually looks like it could be on the low-end, especially if there's ever problems with our service. 

The current implementation waits until this networking is finished before setting the current wallpaper. This is in order to check whether the current wallpaper is part of an expired promotion or not. It also allows us to construct the fully qualified data type of the current wallpaper using the remote metadata. 

Thinking about it more now, I don't think there's any good reason for for this because:
- we let users keep expired wallpapers that are currently selected
- we can cache the other metadata required for general use. this would be things like the `textColor` and `cardColor` properties, but we don't really need to care about the `collection` for the purposes of actually showing the wallpaper on the home screen.

I had planned to improve storage for wallpapers generally as part of https://github.com/mozilla-mobile/fenix/issues/26033, but it slipped the time constraints of the MR. I think a more robust Room or DataStore implementation would be good now that the data is growing in complexity, but I'm also not sure it's worth doing until the shape of the data has stabilized. I'm not convinced that's happened yet.

For now, we could also cache the other properties I mentioned in settings and construct a useful `Wallpaper` instance during `wallpapersUseCases.initialize` rather than waiting for the network, if there are cases where it is not available to us when we need it. I'm also concerned that users with slower network connections may experience the problem more frequently.

**Comment by MatthewTighe** [comment] 2022-08-23 16:18
Actually, since this is a bug that will affect beta and release I am going to hack together a caching mechanism to add to https://github.com/mozilla-mobile/fenix/pull/26515 so that we can resolve the bug ASAP

**Comment by MatthewTighe** [comment] 2022-08-23 20:04
> switch off from the current [store.flow](https://github.com/mozilla-mobile/fenix/blob/7bfd6caa5b04fe15f4a296a937abdb78b29509c2/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L928) call which will only start observing in onStart.
In my opinion this is the best approach and would allow setting the wallpaper as soon as that is available, certainly faster than currently (just because we don't wait until onStart to start those 100ms needed for setting the wallpaper).

I think the issue here is actually that `store.flow()` is launched in `viewLifecycleOwner.lifecycleScope`, which will not run its coroutines until the it is in at least the `CREATED` lifecycle state, as I commented on in https://github.com/mozilla-mobile/fenix/pull/26515#discussion_r948499212. I think this means that the observation won't start until after the screen is rendered, causing the pop-in. I may be wrong about that and would be happy to be. I'm not sure if there's a way to observe the store before rendering if I'm right, though.

**Comment by Mugurell** [comment] 2022-08-25 14:03
> > switch off from the current [store.flow](https://github.com/mozilla-mobile/fenix/blob/7bfd6caa5b04fe15f4a296a937abdb78b29509c2/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L928) call which will only start observing in onStart.
> > In my opinion this is the best approach and would allow setting the wallpaper as soon as that is available, certainly faster than currently (just because we don't wait until onStart to start those 100ms needed for setting the wallpaper).
> 
> I think the issue here is actually that `store.flow()` is launched in `viewLifecycleOwner.lifecycleScope`, which will not run its coroutines until the it is in at least the `CREATED` lifecycle state, as I commented on in [#26515 (comment)](https://github.com/mozilla-mobile/fenix/pull/26515#discussion_r948499212). I think this means that the observation won't start until after the screen is rendered, causing the pop-in. I may be wrong about that and would be happy to be. I'm not sure if there's a way to observe the store before rendering if I'm right, though.

The issue with that call is actually the usage of `flow` which will only start observing the `Store` [once the owner get's past `onStart`](https://github.com/mozilla-mobile/android-components/blob/a037bcefcf3772b133e032be58e4a87fda6fc254/components/lib/state/src/main/java/mozilla/components/lib/state/ext/StoreExtensions.kt#L231-L233) - once the screen is visible.
This is a much too later time. If only now we start observing the store and then actually setting the wallpaper takes ~100ms than on 60Hz we are loosing 6 frames. This will be noticeable no matter how fast downloading and persisting the wallpapers happen to make them available to the HomeFragment.

For a Fragment the `onCreate` state actually refers to `onCreateView` so `viewLifecycleOwner.lifecycleScope` will help run a coroutine once the Fragment is at least in the `onCreateView` state which would be great since at this time we are not being displayed on the screen - we're only now creating the View to be displayed.

Not sure why we chose to use `onStart` - it is a given that this will cause delays in what gets displayed. I propose using `onCreate` [here](https://github.com/mozilla-mobile/android-components/blob/a037bcefcf3772b133e032be58e4a87fda6fc254/components/lib/state/src/main/java/mozilla/components/lib/state/ext/StoreExtensions.kt#L231-L233) instead. @csadilek 

In regards to being able at this time to observe the store which is updated from FenixApplication with a new wallpaper before the Homescreen is displayed using [observeManually](https://github.com/mozilla-mobile/android-components/blob/a037bcefcf3772b133e032be58e4a87fda6fc254/components/lib/state/src/main/java/mozilla/components/lib/state/Store.kt#L67-L87) seems to work great for me.
As per the above numbers, with `onCreateView` taking ~140ms, ~80ms of which are needed just to inflate the layout then we can have a headstart of ~60ms to set the wallpaper which is enough to set it around the time `onStart` completes (and the HomeFragment is visible).

**Comment by delia-pop** [comment] 2022-09-02 14:59
Tested with the latest Nightly from 09/02 with Google Pixel 6 (Android 13). Issues https://github.com/mozilla-mobile/fenix/issues/26511 and https://github.com/mozilla-mobile/fenix/issues/26638 are still reproducible in the current version. 
I will re-test when the issues are fixed and leave the QA needed label until then.

**Comment by Mugurell** [comment] 2022-09-14 14:07
Issue fixed by Matt in https://github.com/mozilla-mobile/fenix/pull/26949

**Comment by delia-pop** [comment] 2022-09-21 07:38
Verified as fixed on Nightly 107.0a1 from 09/20 with Google Pixel 6 (Android 13). The wallpaper set is properly displayed on homepage when the app is opened, when navigating to and from homepage and when the orientation is changed.

**Closed by delia-pop** 2022-09-21 07:38 UTC
Labels: eng:qa:needed, Feature:Wallpapers
