### ISSUE TITLE
[webcontent] Mozilla logo hidden on accounts.firefox.com

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12104] opened 2020-06-29 20:47 UTC
## Site with issue and any steps to reproduce
Try to log in to your firefox account.
Remember to keep the bottom toolbar option
Accounts.firfox.com/oauth.... Opens 

### Expected behavior
The mozilla sign is visible

### Actual behavior
The mozilla logo is half hidden behind the toolbar. It looks very unpolished

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
No. It does not have bottom bar

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by hakkikaancaliskan** [comment] 2020-06-29 21:31
Could you please share screenshot? Because no problem on my device.

![resim](https://user-images.githubusercontent.com/17825767/86058140-13846e80-ba69-11ea-8e30-f4cc5cf815f8.png)

**Comment by s-ankur** [comment] 2020-06-30 09:33
![Screenshot_20200630-021742_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/86110134-b3b3b500-bab4-11ea-9154-d79f55b3ac8b.png)

On your device it is completely hidden but on mine you can see half of it in the bottom left corner

**Comment by s-ankur** [comment] 2020-06-30 09:36
Really it is suppose to look like this
![Screenshot_20200630-150555_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/86110496-27ee5880-bab5-11ea-9fa1-f052635100dc.png)

**Comment by hiikezoe** [comment] 2020-07-15 02:13
The body element in the page has `min-height: 100vh`, vh units means it's including the dynamic toolbar height.  So, the Firefox Account page shouldn't use it there.

**Comment by karlcow** [comment] 2020-07-15 03:41
Another case here https://github.com/webcompat/web-bugs/issues/55285

**Comment by Mugurell** [comment] 2021-02-03 19:35
The page has been changed in the meantime and now the mozilla logo isn't there anymore to be hidden but the toolbar can be scrolled while i'd expect it to be fixed in place.
I think it's a the same issue as https://github.com/mozilla-mobile/fenix/issues/12295

**Comment by Mugurell** [comment] 2021-04-13 15:26
@sflorean Can you please post videos for the above scenarios for letting UX to decide if and what should be changed?

**Comment by sflorean** [comment] 2021-04-13 15:47
![20210413_184537](https://user-images.githubusercontent.com/58466444/114581720-a143ea00-9c88-11eb-993e-b3ec39c40ff7.gif)

**Comment by sflorean** [comment] 2021-04-15 14:44
Found https://github.com/mozilla/fxa/issues/8150 and this issues seems to be by design. Asking UX to confirm if there's something here to change.

**Comment by topotropic** [comment] 2021-05-03 18:56
Thanks, @sflorean! 

What options do we have here? Is it just a rare case or could a fix also address other issues for example the ones linked above?

**Comment by mariansima** [comment] 2021-11-01 14:35
Reproduced as per previous comments, the mozilla logo is not displayed in portrait orientation, only in landscape. Tested on Samsung Galaxy A8 (Android 9) with Firefox Nightly 95.0a1 2021-11-01

**Comment by sflorean** [comment] 2022-05-06 12:04
This is still an issue on Fenix versions.

**Comment by hiikezoe** [comment] 2022-05-08 22:14
IIRC, this is a case of using 100vh and overflow:hidden? Then using 100svh in the Firefox Account page would solve this issue.

**Comment by Mugurell** [comment] 2022-05-11 12:30
I see that element having the id `about-mozilla` and in the css imported from https://accounts-static.cdn.mozilla.net/styles/23d20f13.main.css

we use:
```
@media(min-width:521px),
(orientation:landscape)and (min-width:641px) {
	#about-mozilla {
		background: url("/images/c86df1d3.mozilla.svg") no-repeat center center;
		cursor: pointer;
		display: block;
		height: 48px;
		margin: 24px 0;
		transition: opacity 150ms;
		width: 128px
	}

	#about-mozilla:hover {
		opacity: 1
	}

	#about-mozilla:focus {
		outline-color: #fbfbfe
	}
}

@media(max-width:520px),
(orientation:landscape)and (max-width:640px) {
	#about-mozilla {
		display: none
	}
}
```

As such only seeing that in landscape is the expected behavior.

**Closed by Mugurell** 2022-05-11 12:30 UTC
Labels: 🐞 bug, needs:UX-feedback, Feature:Accounts, qa-triaged
