### ISSUE TITLE
[Bug]FxA Signin causes crash when password is changed on Desktop

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#3036] opened 2019-05-31 09:36 UTC
## Steps to reproduce
1. Sign in on 2 devices (Android and Desktop)
1. Change the password on Desktop.
1. Go to Android to Settings and try to sign in again.

### Expected behavior
Not crash.

### Actual behavior
Crash.

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1)
* Fenix version: 1.0.1922 (#11510609)

Not reproducible all the time.
![crash](https://user-images.githubusercontent.com/40694158/58696651-abb0af80-83a0-11e9-9dc0-d1a0ae6b4568.gif)

### logcat:
```
05-31 12:07:21.342 24994-25109/? I/CrashMetricService: Startup metric for 'PRIMES_CRASH_MONITORING_INITIALIZED' dropped.
05-31 12:08:54.345 25336-25336/? W/CrashLoopRemedyLog: unable to delete remedy log, instaCrash: false
05-31 12:08:54.346 25336-25336/? W/CrashLoopRemedyLog: unable to delete remedy log, instaCrash: true
05-31 12:08:54.613 25336-25355/? I/dalvik-internals: installed sigmux crash handler for crash log
05-31 12:08:55.135 25336-25336/? W/MDCLAN_FCH: Bypassing deoptimization check for FCIPCL failure
    Failed to find class in boot class loader (may not be fatal): descriptor=Lcom/google/firebase/crash/FirebaseCrash; hash=3139922863 boot_class_path_.size()=18
05-31 12:09:09.134 2470-2483/? W/ActivityManager: Scheduling restart of crashed service com.android.chrome/org.chromium.content.app.PrivilegedProcessService1 in 1000ms
05-31 12:09:09.134 16432-16532/? W/cr_ChildProcessConn: onServiceDisconnected (crash or killed by oom): pid=24461
05-31 12:09:09.142 16432-16532/? W/cr_ChildProcessConn: onServiceDisconnected (crash or killed by oom): pid=24473
05-31 12:09:09.143 2470-18511/? W/ActivityManager: Scheduling restart of crashed service com.android.chrome/org.chromium.content.app.SandboxedProcessService3 in 1000ms
05-31 12:09:10.470 2470-3752/? W/ActivityManager: Scheduling restart of crashed service org.mozilla.fenix/org.mozilla.gecko.process.GeckoServiceChildProcess$tab in 1000ms
05-31 12:09:32.594 2470-2483/? W/ActivityManager: Scheduling restart of crashed service org.mozilla.fenix/org.mozilla.gecko.process.GeckoServiceChildProcess$tab in 1000ms
05-31 12:09:39.344 25336-25349/? W/CrashLoopRemedyLog: unable to delete remedy log, instaCrash: true
05-31 12:17:26.279 2470-18511/? I/BroadcastQueue: am_broadcast_enqueue: [background,1,Intent { act=com.sonymobile.crashmonitor.CRASH_STATUS flg=0x10 (has extras) },1]
05-31 12:17:26.319 2470-16986/? I/BroadcastQueue: am_broadcast_finished: [background,1,Intent { act=com.sonymobile.crashmonitor.CRASH_STATUS flg=0x10 (has extras) }]
05-31 12:21:34.601 25823-25823/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.RuntimeException: Failed to call observer method)
    Showing prompt
05-31 12:21:34.624 2470-16988/? I/ActivityManager: START u0 {flg=0x10018000 cmp=org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity (has extras)} from uid 10395 on display 0
05-31 12:21:34.635 2470-2910/? D/ActivityManager: New dropbox entry: org.mozilla.fenix, data_app_crash, 9bb96e34-e441-4c16-90a0-1aa366405f77
05-31 12:21:34.653 676-676/? I/JavaDumper:JavaDumperThread: addEvent: data_app_crash@1559294494652.txt processName: org.mozilla.fenix
05-31 12:21:34.653 676-751/? I/JavaDumper:JavaDumperThread: Event: data_app_crash@1559294494652.txt TimeStamp: 1559294494
05-31 12:21:34.667 676-751/? E/JavaDumper:FW:  utils.c(256): mkdir (/data/crashdata) failed. File exists
05-31 12:21:34.753 2470-2507/? I/BroadcastQueue: am_broadcast_enqueue: [background,1,Intent { act=com.sonymobile.crashmonitorsystemservice.DIR_UPDATED flg=0x10 (has extras) },2]
05-31 12:21:34.829 2470-3156/? I/ActivityManager: Start proc 27054:org.mozilla.fenix:mozilla.components.lib.crash.CrashReporter/u0a395 for activity org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity
05-31 12:21:34.890 2470-2923/? I/BroadcastQueue: am_broadcast_enqueue: [background,1,Intent { act=com.sonymobile.crashmonitor.CRASH_STATUS flg=0x10 (has extras) },1]
05-31 12:21:34.949 27041-27041/? I/RcaHandler: Forwarding intent: com.sonymobile.crashmonitorsystemservice.DIR_UPDATED
05-31 12:21:34.953 2470-3765/? I/BroadcastQueue: am_broadcast_finished: [background,1,Intent { act=com.sonymobile.crashmonitorsystemservice.DIR_UPDATED flg=0x10 (has extras) }]
05-31 12:21:34.959 2470-3746/? I/BroadcastQueue: am_broadcast_finished: [background,1,Intent { act=com.sonymobile.crashmonitor.CRASH_STATUS flg=0x10 (has extras) }]
05-31 12:21:35.005 27041-27072/? I/RcaHandler: Handle JAVA-dumpfile with UUID:7259E914-2335-BDE8-9C74-5C91C3AC1A33-B95B76DC from:JavaDumper named:/data/crashdata/tlcore_java_09
05-31 12:21:35.122 27041-27072/? I/RcaHandler: Added event. Result: 0, crashId: 7259E914-2335-BDE8-9C74-5C91C3AC1A33-B95B76DC, Probe: RcaInfoProbeExtended
05-31 12:21:35.124 27041-27072/? I/RcaHandler: Added event. Result: 0, crashId: 7259E914-2335-BDE8-9C74-5C91C3AC1A33-B95B76DC, Probe: RcaInfoProbeCompact
    Saved JAVA_SYSTEM_APP (ID:29f540fe-e532-4246-aefe-bdd91b6f1bc4) to IDD
05-31 12:21:35.560 2470-2510/? I/ActivityManager: Displayed org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity: +743ms
    Displayed com.sonyericsson.home/com.sonymobile.home.HomeActivity: +702ms
05-31 12:21:35.624 2470-2510/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{c4b0ac7 u0 org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity t284} time:13556498 diff:490 start:lukewarm|cch-empty batt:53|2 mw:off|1 mem:859228|0|58|9|16 cpu:[1478400, 1478400, 1478400, 1478400, 864000, 0, 0, 0]
05-31 12:21:49.847 2470-2910/? I/ActivityManager: Killing 25823:org.mozilla.fenix/u0a395 (adj 900): crash
05-31 12:21:49.871 2470-2504/? I/InputDispatcher: Focus entered window: Window{646c9dd u0 org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity}
05-31 12:21:50.675 27054-27069/? I/mozac/CrashReporter: Crash report submitted to 2 services
05-31 12:23:44.329 27450-27450/? D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
05-31 12:23:44.361 27450-27464/? V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
05-31 12:23:44.401 27450-27450/? I/CrashlyticsCore: Initializing Crashlytics 2.6.8.32
05-31 12:23:44.417 27450-27450/? I/CrashlyticsInitProvider: CrashlyticsInitProvider initialization successful
05-31 12:24:03.430 27109-27109/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.RuntimeException: Failed to call observer method)
05-31 12:24:03.431 27109-27109/? I/mozac/CrashReporter: Showing prompt
05-31 12:24:03.443 2470-18511/? I/ActivityManager: START u0 {flg=0x10018000 cmp=org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity (has extras)} from uid 10395 on display 0
05-31 12:24:03.450 2470-3750/? D/ActivityManager: New dropbox entry: org.mozilla.fenix, data_app_crash, 8f62ab51-f184-4e1c-af49-4f6ff6707134
05-31 12:24:03.471 676-676/? I/JavaDumper:JavaDumperThread: addEvent: data_app_crash@1559294643464.txt processName: org.mozilla.fenix
05-31 12:24:03.472 676-751/? I/JavaDumper:JavaDumperThread: Event: data_app_crash@1559294643464.txt TimeStamp: 1559294643
05-31 12:24:03.476 676-751/? E/JavaDumper:FW:  utils.c(256): mkdir (/data/crashdata) failed. File exists
05-31 12:24:03.564 2470-2507/? I/BroadcastQueue: am_broadcast_enqueue: [background,1,Intent { act=com.sonymobile.crashmonitorsystemservice.DIR_UPDATED flg=0x10 (has extras) },2]
05-31 12:24:03.576 27041-27041/? I/RcaHandler: Forwarding intent: com.sonymobile.crashmonitorsystemservice.DIR_UPDATED
05-31 12:24:03.580 2470-16989/? I/BroadcastQueue: am_broadcast_finished: [background,1,Intent { act=com.sonymobile.crashmonitorsystemservice.DIR_UPDATED flg=0x10 (has extras) }]
05-31 12:24:03.595 27041-27673/? I/RcaHandler: Handle JAVA-dumpfile with UUID:A26EEF78-B8EA-6832-69E7-86CD9A21E64A-8BA673A4 from:JavaDumper named:/data/crashdata/tlcore_java_00
05-31 12:24:03.625 2470-3272/? I/BroadcastQueue: am_broadcast_enqueue: [background,1,Intent { act=com.sonymobile.crashmonitor.CRASH_STATUS flg=0x10 (has extras) },1]
05-31 12:24:03.628 27041-27673/? I/RcaHandler: Added event. Result: 0, crashId: A26EEF78-B8EA-6832-69E7-86CD9A21E64A-8BA673A4, Probe: RcaInfoProbeExtended
05-31 12:24:03.629 27041-27673/? I/RcaHandler: Added event. Result: 0, crashId: A26EEF78-B8EA-6832-69E7-86CD9A21E64A-8BA673A4, Probe: RcaInfoProbeCompact
    Saved JAVA_SYSTEM_APP (ID:288046e2-7973-4476-b979-4a9b228990ee) to IDD
    Added entry JAVA to rca-list
05-31 12:24:03.632 2470-18512/? I/BroadcastQueue: am_broadcast_finished: [background,1,Intent { act=com.sonymobile.crashmonitor.CRASH_STATUS flg=0x10 (has extras) }]
05-31 12:24:04.397 2470-2510/? I/ActivityManager: Displayed org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity: +450ms (total +13s631ms)
    Displayed com.sonyericsson.home/com.sonymobile.home.HomeActivity: +386ms
05-31 12:24:04.456 2470-2510/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{695631b u0 org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity t284} time:13705331 diff:1005 start:lukewarm|cch-empty batt:52|2 mw:off|1 mem:1081132|0|56|8|13 cpu:[1555200, 1555200, 1555200, 1555200, 0, 1248000, 0, 0]
05-31 12:24:07.136 2470-3750/? I/ActivityManager: Killing 27109:org.mozilla.fenix/u0a395 (adj 900): crash
05-31 12:24:07.169 2470-2851/? I/InputDispatcher: Focus entered window: Window{cc59bd5 u0 org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity}
05-31 12:24:18.029 2470-2510/? I/ActivityManager: Displayed org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity: +528ms (total +570ms)
05-31 12:24:18.114 2470-2510/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{695631b u0 org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity t284} time:13718992 diff:625 start:lukewarm|cch-empty batt:52|2 mw:off|1 mem:1155508|0|58|8|14 cpu:[1478400, 1478400, 1478400, 1478400, 864000, 0, 0, 0]
```

**Comment by colintheshots** [comment] 2019-06-03 17:50
I can't reproduce this. It appears to be a duplicate of #3031, which is fixed as of late last week.

**Closed** 2020-08-26 20:49 UTC
Labels: Release Blocker, b:crash, 🐞 bug
