### ISSUE TITLE
FNX2-13018 ⁃ [Bug] Sometimes the dynamic address bar at the bottom cannot disappear.

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#12066] opened 2020-06-28 06:58 UTC
the dynamic address bar at the bottom cannot disappear when enable ublock origin on http://m.ceriah.com/qingyunian/2107287.html

https://imgur.com/5HWlS1d.mp4

Nightly 200626 06:01 (Build #21780613)
AC: 48.0.20200625130125, d51b5b208
GV: 79.0a1-20200624093107
AS: 61.0.6
Friday 6/26 @ 6:12 AM

**Comment by SS1113** [comment] 2020-06-28 07:41
Refer this https://github.com/mozilla-mobile/fenix/issues/10073#issuecomment-639003404, I think it is intentional and has been asked before in the issue #11471.

**Comment by jakefleming156** [comment] 2020-08-25 18:54
Thanks for filing this bug. For now, I will close this as a duplicate of #11858. If you have any further insights go ahead and comment there.

**Closed by jakefleming156** 2020-08-25 18:54 UTC
Labels: needs:triage, 🐞 bug
