### ISSUE TITLE
YouTube white space

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#14170] opened 2020-08-25 14:53 UTC
Open a video on Youtube then go to the bottom and open the comments and go back to the top, a white space appears at the top
Lenovo k6 note Android Q old version

![Screenshot_20200825-174349_Iceweasel_1](https://user-images.githubusercontent.com/60405617/91189900-a9501900-e6fb-11ea-921a-04bdf32f6595.png)

**Comment by s-ankur** [comment] 2020-08-25 15:23
Duplicate of #10598

**Comment by ekager** [comment] 2020-12-18 05:03
Closing for #10598

**Closed by ekager** 2020-12-18 05:03 UTC
Labels: needs:triage, 🐞 bug
