### ISSUE TITLE
Expose 'Send to device' options to Firefox Focus

### ISSUE THREAD

**Issue by keunes** [mozilla-mobile/fenix#18187] opened 2021-02-26 08:09 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Note: not sure I'm doing the right thing adding the request here - please let me know if the issue should be created in the Focus repo. Thanks!

### What is the user problem or growth opportunity you want to see solved?

I use Firefox Focus as my default browser. Once every two days or so I want to send something (GH issue, long article) to Firefox on my laptop. I have Fenix installed and sync set up.
Currently to get a tab to my laptop I open the page in Focus (default), share with 'Firefox' (Fenix), from there share again to send it to my laptop.
Exposing 'Send to device' to Focus (as it once was, IIRC) would take out that extra step.

### How do you know that this problem exists today? Why is this important?

Send to device is a great feature. Allowing its use from Firefox Focus will help users stay private while enjoying the Send functionality when desired.

### Who will benefit from it?

Users that use Firefox Focus (e.g. because they appreciate the simple interface and privacy orientation)

**Comment by hakkikaancaliskan** [comment] 2021-02-26 08:46
This repo is just for firefox mobile (codename fenix), please open this issue in [focus repo](https://github.com/mozilla-mobile/focus-android)

**Comment by kbrosnan** [comment] 2021-02-26 16:50
Duplicate of https://github.com/mozilla-mobile/fenix/issues/1523

**Closed by kbrosnan** 2021-02-26 16:50 UTC
Labels: needs:triage

**Comment by keunes** [comment] 2021-02-27 08:21
Thanks for that link @kbrosnan. Sad I can't give a thumbs-up there :(
