### ISSUE TITLE
[Bug] ebay login with Google account leads to a blank page

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#2640] opened 2019-05-19 23:54 UTC
## Steps to reproduce
1. Go to https://ebay.it/
1. Tap the top right icon with the human profile.
1. Select Google for login choice
1. Enter the parameters for login

### Expected behavior
log in to ebay

### Actual behavior
Blank page.

### Device information
* Android device: Pixel 2. Android 9.
* Fenix version: 68.0a1-20190508111321

Reported initially on https://github.com/webcompat/web-bugs/issues/30186
This is working on Firefox Nightly Android 68
This is failing on Firefox Nightly Desktop 68 (with RDM, touch on, and Firefox Android UA and content blocking on)

**Comment by reinhart1010** [comment] 2019-05-20 08:16
Duplicate of #2638?

**Comment by sblatz** [comment] 2019-06-26 21:24
I'm able to reproduce this on Sample Browser & Reference Browser. This seems like it's a GV bug not redirecting us properly?

**Comment by denschub** [comment] 2019-06-27 20:41
This is actually caused by #3702!

**Closed** 2020-08-26 06:04 UTC
Labels: P1, needs:gv, needs:investigation, 🐞 bug, 🙅 waiting
