### ISSUE TITLE
[Bug]: DropDown Menu not working

### ISSUE THREAD

**Issue by HuMuK** [mozilla-mobile/fenix#23395] opened 2022-01-25 11:19 UTC
### Steps to reproduce

 I have the last Firefox nightly available from app store

The DropDown Menu is not working.
On all pages, examples:
https://www.nvidia.com/Download/index.asp
https://www.globalsqa.com/demo-site/select-dropdown-menu/x
https://www.amd.com/en/support (left side not working)

### Expected behaviour

The selection should show list with options. 

### Actual behaviour

The DropDown Menu is not reacting on clics.

### Device name

Sony Xperia 10 II

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1 (Build #2015859435), ff4b19434+

### Additional information

The Firefox info:

AC: 98.0.20220124150849, 0a4caecc8d
GV: 98.0a1-20220124093541
AS: 90.0.0
2022-01-25T05:10:17.550964

**Comment by cadeyrn** [comment] 2022-01-25 11:38
Duplicate of #23370 that was closed as an duplicate of the upstream issue https://bugzilla.mozilla.org/show_bug.cgi?id=1751674. A fix is already in progress.

**Closed** 2022-01-25 16:28 UTC
Labels: 🐞 bug, needs:triage
