### ISSUE TITLE
FNX-3295 ⁃ [Bug] The Login capture panel is incorrectly displayed when opening the keyboard

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#10116] opened 2020-04-22 14:37 UTC
## Steps to reproduce
1. Launch Fenix.
1. Access any website and login.
1. On the Login capture panel tap on the username or password field.
    1. Expected behavior
The Login capture panel should be fully displayed with all the buttons in order to save or not after editing the password.
    1. Actual behavior
The Login capture panel is incorrectly displayed when opening the keyboard
    1. Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 4/22.**

![20200422-171352-1](https://user-images.githubusercontent.com/42831109/79995394-da0b1200-84bf-11ea-8d3d-7133e4dbb2e9.gif)

**Comment by ekager** [comment] 2020-04-27 22:34
I think this in theory would impact all of our bottom sheet dialogs, but this is the only dialog with edit texts AFAIK. [This dialog lives in Android Components here ](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/LoginDialogFragment.kt)

**Comment by liuche** [comment] 2020-05-11 20:56
Bottom-sheet w/ edit text is in AC, but Fenix can work on it.

**Comment by sblatz** [comment] 2020-05-18 17:54
My AC fix landed and this should be fixed in master now 😄

**Comment by ValentinTimisica** [comment] 2020-05-19 13:22
Hello @sblatz, found this bug (login dialog is shown in the middle of the screen and the keyboard disappears - [Video](https://drive.google.com/file/d/1-U0lyayx2gYb18Va2cXkHJiZoz0C29aA/view?usp=sharing)) which appeared after https://github.com/mozilla-mobile/android-components/pull/6997 was merged. Posted it here because it's related and it's not closed yet.

**Comment by sblatz** [comment] 2020-05-19 19:04
Hmm this seems to be happening because the keyboard is visible at first but dismisses as the fragment is showing. This does seem like a much less severe bug than the original, but I will investigate to see if I can fix both.

**Comment by AndiAJ** [comment] 2020-05-20 08:05
> Hello @sblatz, found this bug (login dialog is shown in the middle of the screen and the keyboard disappears - [Video](https://drive.google.com/file/d/1-U0lyayx2gYb18Va2cXkHJiZoz0C29aA/view?usp=sharing)) which appeared after [mozilla-mobile/android-components#6997](https://github.com/mozilla-mobile/android-components/pull/6997) was merged. Posted it here because it's related and it's not closed yet.

Reproducible on **`Beta 5.1.0-beta.1`** and **`Nightly 200520 from 5/20`** after signing in to:
• yahoo.com
• instagram.com

using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

**Comment by sblatz** [comment] 2020-05-22 17:21
The other AC fix I made for this has landed. Let's test one more time 😄

**Comment by sblatz** [comment] 2020-05-22 23:40
The new AC patch hasn't been merged yet. I'll put the qa needed on again once it lands in Fenix.

**Comment by sblatz** [comment] 2020-05-26 16:20
We've updated AC now so I'll put a qa needed on this 😄

**Comment by AndiAJ** [comment] 2020-05-29 06:41
Hi, **verified as fixed** on the latest **`Nightly Build 200529 from 5/29`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video Instagram
![20200529-093303](https://user-images.githubusercontent.com/51314259/83229278-59ab9100-a190-11ea-8784-3fbf8f9bda92.gif)


► Video Yahoo
![20200529-093450](https://user-images.githubusercontent.com/51314259/83229396-96778800-a190-11ea-8931-713f74944b81.gif)

**Comment by sblatz** [comment] 2020-06-12 17:27
I updated the delay to be a bit longer in AC, this should be fixed now!

**Comment by sflorean** [comment] 2020-06-15 12:38
Verified as fixed on Nightly 6/15 with the following devices:
- Samsung  Galaxy S9 (Android 8) 
- Pixel 3XL (Android 9)
- Samsung Galaxy Note 10 (Android 10)
- Nokia 6 (Android 7.1.1)
- Huawei MediaPad M2	(Android 5.1.1)

**Closed** 2020-08-10 19:01 UTC
Labels: AC-by-Fenix, E3, Feature:IME, Feature:Logins, S1, eng:qa:verified, eng:ready, help wanted, needs:ac, 🐞 bug
