### ISSUE TITLE
[Bug] Inconsistent info about blocking by Android

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6081] opened 2019-10-17 11:33 UTC
## Steps to reproduce
1. open any URL
2. click on the icon on the left side of site URL - there will be displayed popup with site info
3. go into Settings \ Site Permissions

### Expected behavior
Settings \ Site Permissions is displaying "Blocked by Android" like popup with site info (when some setting was blocked by Android permission)

### Actual behavior
In the Settings \ Site Permissions we have info about every setting for situation, when Android will not block it -> this is confusing.

### Device information

* Android device: S7
* Fenix version: 2.1.0

**Comment by marcinwiacek** [comment] 2020-01-07 23:26
I think, it was resolved in meantime...

**Comment by kbrosnan** [comment] 2020-01-08 04:52
Thank you for following up. I also cannot reproduce comment 0. Closing

**Closed by kbrosnan** 2020-01-08 04:52 UTC
Labels: Feature:AndroidIntegration, Feature:Settings, P2, 🐞 bug
