### ISSUE TITLE
Translation Feature

### ISSUE THREAD

**Issue by Androiduser-7** [mozilla-mobile/fenix#18938] opened 2021-04-11 11:24 UTC
Please Add Translation feature to translate websites.

**Comment by cadeyrn** [comment] 2021-04-11 11:53
Duplicate of #6133.

**Comment by sheikh-azharuddin** [comment] 2021-04-11 12:32
> Please Add Translation feature to translate websites.

Better use extension...mozilla has not added in firefox desktop  since years so don't expect ..they could add Google translator but they are not interested citing privacy issue yet their default search engine is Google! They have a deal also with Google...

**Comment by Androiduser-7** [comment] 2021-04-11 12:40
No Translator extension is available for Firefox Android

**Comment by cadeyrn** [comment] 2021-04-11 12:43
> mozilla has not added in firefox desktop since years so don't expect

They are working on a translation feature for the desktop Firefox without any cloud service. It is a project funded by the European Union, called Project Bergamot. I wouldn't rule out this being an option for Android at some point.

> they are not interested citing privacy issue yet their default search engine is Google! They have a deal also with Google

These things really don't have the slightest thing to do with each other.

**Comment by Androiduser-7** [comment] 2021-04-11 12:44
> > Please Add Translation feature to translate websites.
> 
> Better use extension...mozilla has not added in firefox desktop since years so don't expect ..they could add Google translator but they are not interested citing privacy issue yet their default search engine is Google! They have a deal also with Google...

Not a single extension is available for translating web pages on Firefox Android.

**Comment by cadeyrn** [comment] 2021-04-11 12:49
> mozilla has not added in firefox desktop since years so don't expect

They are working on a translation feature for the desktop Firefox without the need to contact any cloud service. It is a project funded by the European Union, called Project Bergamot. I wouldn't rule out this being an option for Android at some point.

> they are not interested citing privacy issue yet their default search engine is Google! They have a deal also with Google

A cloud translation feature and a default search engine are totally different things and really have nothing to do with each other.

Since this is a duplicate issue further discussion about a translation feature should happen in #6133.

**Comment by sheikh-azharuddin** [comment] 2021-04-11 14:58
> > mozilla has not added in firefox desktop since years so don't expect
> 
> They are working on a translation feature for the desktop Firefox without the need to contact any cloud service. It is a project funded by the European Union, called Project Bergamot. I wouldn't rule out this being an option for Android at some point.
> 
> > they are not interested citing privacy issue yet their default search engine is Google! They have a deal also with Google
> 
> A cloud translation feature and a default search engine are totally different things and really have nothing to do with each other.
> 
> Since this is a duplicate issue further discussion about a translation feature should happen in #6133.

That project I am hearing since ages.....no progress not sure when they will implement .. probably project discarded...

Yes they have to do...both are Google products..mozilla is not dumb to have default search engine as Google there is a deal and Google is paying hefty amount...what's the harm in having same deal for the translation feature by same Google.?

**Comment by sheikh-azharuddin** [comment] 2021-04-11 15:00
> > > Please Add Translation feature to translate websites.
> > 
> > 
> > Better use extension...mozilla has not added in firefox desktop since years so don't expect ..they could add Google translator but they are not interested citing privacy issue yet their default search engine is Google! They have a deal also with Google...
> 
> Not a single extension is available for translating web pages on Firefox Android.

It's available bro like Google translation...in page translation
You need to install firefox nightly and use custom add on called Translate web pages

![Screenshot_20210411-202937029 (1)](https://user-images.githubusercontent.com/58127841/114309425-b09a2a80-9b04-11eb-80d0-16ca4d4c115c.jpg)

**Comment by cadeyrn** [comment] 2021-04-12 18:13
> That project I am hearing since ages.....no progress not sure when they will implement .. probably project discarded...

This is not true at all. Please inform yourself better before you spread something like that. A lot of progress is made and it can already be tested…

https://github.com/mozilla-extensions/bergamot-browser-extension/releases

> Yes they have to do...both are Google products..

Yes, both are Google products. And still both things have nothing to do with each other at all. For this reason and because I already referred to #6133 I am done here.

**Comment by eliserichards** [comment] 2021-04-12 21:51
Closing as duplicate. Thanks @cadeyrn!

**Closed by eliserichards** 2021-04-12 21:51 UTC
Labels: feature request 🌟

**Comment by sheikh-azharuddin** [comment] 2021-04-13 07:11
> I already referred to #6133 so I won't answer to the other things in this issue but one thing has to be clarified so that no untruth is spread:
> 
> > That project I am hearing since ages.....no progress not sure when they will implement .. probably project discarded...
> 
> This is not true at all. A lot of progress has been made and it can already be tested…
> 
> https://github.com/mozilla-extensions/bergamot-browser-extension/releases

124MB size extension...are you kidding?? Twice the size of the browser🤣🤣😂

No thanks

**Comment by Dunexus** [comment] 2021-04-13 15:24
This is the price for offline/cloudless translation.
