### ISSUE TITLE
[Bug] Still see FAB after dismissing new tab tray

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#18885] opened 2021-04-08 20:16 UTC
Open the tab tray, dismiss it, still see the FAB

![Screenshot (Apr 8, 2021 10 07 47 PM)](https://user-images.githubusercontent.com/353960/114090588-e9918f80-98b7-11eb-9563-4144008f4758.png)

**Comment by jonalmeida** [comment] 2021-04-08 20:45
For this, we need to re-introduce the `BottomSheetBehavior.BottomSheetCallback` and dismiss the tray when the sheet is dragged off the screen.

Not sure why this isn't already handled for us by the default behaviour, but if it doesn't take too much time, let's see if we've overloaded something incorrectly, that made it disappear.

The original implementation is [here](https://github.com/mozilla-mobile/fenix/blob/db9b3676d3c02c1814cf154a98557a871b235e05/app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt#L121-L142), but we probably don't need everything there.

**Comment by cadeyrn** [comment] 2021-04-09 13:19
Looks like a duplicate of #18860 with the difference that the FAB was not yet implemented when I filed #18860.

**Comment by jonalmeida** [comment] 2021-04-11 05:28
Thanks @cadeyrn , sorry I seemed to have missed your issue earlier. I'm going to close it as a duplicate since I've started to add some activity to this one. Expect a fix soon! 🙃

**Closed** 2021-04-13 20:00 UTC
Labels: E2, Feature:SyncTabs, Feature:Tabs, MR1, 🐞 bug
