### ISSUE TITLE
Firefox Daylight Android

### ISSUE THREAD

**Issue by siggiengelbrecht** [mozilla-mobile/fenix#21954] opened 2021-10-15 12:43 UTC
Talking about FF 93.1.0 build 2015836707, running on Huawei MediaPad M5 SHT-W09 build 9.1.0.360.

Right after actualization to 93.1.0 via Google play store, ff began to hang/crash repeatedly and without apparent reason. I had to resort to shut down/relaunch the tablet and even then had some difficulties to convince FF to stop/exit. Error report attached. Not being an expert, I have no idea what's going on here. First time ever to see FF crashing!
![Screenshot_20211015_033024_org mozilla firefox](https://user-images.githubusercontent.com/92584498/137488471-5169b41f-4b5c-4bad-b8cb-a26e706f0515.jpg)
.

**Comment by pocmo** [comment] 2021-10-15 13:53
@csadilek @grigoryk Is this already known/fixed?

**Comment by csadilek** [comment] 2021-10-15 14:21
Thanks for filing @siggiengelbrecht. We have a 93.**2**.0 dot release which should be rolling out today with a fix.

Dupe of: https://github.com/mozilla-mobile/fenix/issues/21948

**Closed by csadilek** 2021-10-15 14:22 UTC
Labels: 🐞 bug, b:crash, needs:triage
