### ISSUE TITLE
FNX2-13360 ⁃ [Bug] Third party cookie blocking not working in custom mode when tracking content is blocked in private tabs

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#11128] opened 2020-06-02 06:52 UTC
## Steps to reproduce
1. Enable ETP in custom mode with cookies: all third party, tracking content: only in private tabs
1. Open https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled in private mode

### Expected behavior
Third party cookies are blocked. 

### Actual behavior
Third party cookies are not blocked. 

### Device information
* Android device: Pixel 2
* Fenix version: 75.0.0-beta.6 (Build #2015735819)
37.0.5, e5f14c288
GV: 75.0-20200403064004
AS: 0.55.3

This works correctly in Nightly.

**Comment by Amejia481** [comment] 2020-07-03 21:35
QA please help us to confirm is this still an issue

**Comment by Amejia481** [comment] 2020-07-03 21:53
@vishalnandagopal  are you still seeing the issue? Which site are you using for testing fingerprinting as the one above doesn't include it.

**Comment by vishalnandagopal** [comment] 2020-07-04 04:59
This seems to be fixed now.

For Fingerprint testing, I used same site and Duckduckgo.

When privacy.resist.fingerprinting is ON, websites don't get the theme we have set (to lower fingerprinting chances)

With that off, DDG will use dark mode, when browser is in dark mode. With that on, DDG should use light mode, even when browser is in dark mode.


Also, the version number will be the same for everyone, who has set to resist fingerprinting. whatismybrowser.com showed same version number, even is fingerprint resisting is on

**Comment by ebalazs-sv** [comment] 2020-07-07 09:34
I had tested this on Nightly 200707 GV 80 from 7/7 and Beta 79.0.0-beta.5 GV 79 from 7/3 with Pixel 2 (Android 9), following the steps from the description and these are the results:
To the question: "Are Third-Party Cookies enabled?" the answer is:
- "Yes" for both private and normal browsing on Beta 79.0.0-beta.5 GV 79 from 7/3;
- "No" for both private and normal browsing on Nightly 200707 GV 80 from 7/7;

@yoasif Did you received the same result when did bug was filed? Is this still reproducible for you? Thanks!

**Comment by Amejia481** [comment] 2020-07-10 18:57
> I had tested this on Nightly 200707 GV 80 from 7/7 and Beta 79.0.0-beta.5 GV 79 from 7/3 with Pixel 2 (Android 9), following the steps from the description and these are the results:
> To the question: "Are Third-Party Cookies enabled?" the answer is:
> 
>     * "Yes" for both private and normal browsing on Beta 79.0.0-beta.5 GV 79 from 7/3;
> 
>     * "No" for both private and normal browsing on Nightly 200707 GV 80 from 7/7;
> 
> 
> @yoasif Did you received the same result when did bug was filed? Is this still reproducible for you? Thanks!
> I will remove the qa:needed label for now.

As @ebalazs-sv mentioned, I'm only able to simulate this issue on Android 9 with this specific build  `79.0.0-beta.5 GV 79` but on Android 9 on nightly `Nightly 200707 GV 80` the issue is not reproducible anymore. It looks like it was an issue on `GV 79` and now it's fixed on `GV 80`. I'm not sure if this is something that we should continue investigating for uplifting to `79.0.0-beta.5 GV 79` or should we just wait for the new GV `80` go to beta. @liuche what do you think?

**Comment by yoasif** [comment] 2020-07-10 20:12
Not seeing this on Firefox 79 beta 4 or nightly.

**Comment by Amejia481** [comment] 2020-07-14 15:41
I think we can close this one, and re-open if need it

**Closed** 2020-08-11 21:36 UTC
Labels: Feature:PrivateBrowsing, needs:ac, 🐞 bug
