### ISSUE TITLE
[Bug] white screen prior to loading website

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#5206] opened 2019-09-11 02:06 UTC
## Steps to reproduce
1. Set fenix as default 
2. Click this link from another app https://www.theverge.com/2019/9/10/20860023/apple-ar-headset-starboard-garta-luck-franc-holokit

### Expected behavior
3. Fenix loads custom tab and starts drawing the page

### Actual behavior
4. Fenix loads custom tab but for 2-5 seconds shows this white screen
![Screenshot_20190910-190015_Firefox Preview](https://user-images.githubusercontent.com/4879954/64662649-0032e480-d3fe-11e9-9234-cd859ec7037f.jpg)

### Device information

* Android device: note 10
* Fenix version: today's

**Comment by colintheshots** [comment] 2019-09-20 17:57
I believe this should be fixed by upgrading GeckoView to the latest 71 version.

**Comment by sv-ohorvath** [comment] 2019-10-09 13:05
I can't reproduce this on the latest Nightly 10/9, probably fixed with the above GV bug.
devices: Pixel 3 (Android 9), HTC Desire 820 (Android 6.0.1)

**Closed by sv-ohorvath** 2019-10-09 13:05 UTC
Labels: eng:qa:needed, 🐞 bug
