### ISSUE TITLE
Custom search engines do not provide search suggestions

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#7866] opened 2020-01-22 18:39 UTC
## Steps to reproduce
1. Add a new custom search engine (e.g. ecosia.org/search?q=%s)
2. Make it your default
3. Start typing a search

### Expected behavior
1. Search suggestions are presented

### Actual behavior
1. No search suggestions are given

### Device information
* Android device: Galaxy S9 Android 9
* Fenix version: Nightly 1/22

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15329)

**Comment by ghoppaccia** [comment] 2020-01-23 12:56
> ## Steps to reproduce
> 
>     1. Add a new custom search engine (e.g. ecosia.org/search?q=%s)
> 
>     2. Make it your default
> 
>     3. Start typing a search
> 
> 
> ### Expected behavior
> 
>     1. Search suggestions are presented
> 
> 
> ### Actual behavior
> 
>     1. No search suggestions are given
> 
> 
> ### Device information
> 
>     * Android device: Galaxy S9 Android 9
> 
>     * Fenix version: Nightly 1/22

Thank you @sblatz for opening this bug.

I would add that the search engine is neither using the real icon of the webpage, should I open another bug for that?

**Comment by Cheap-Skate** [comment] 2020-01-23 18:06
@ghoppaccia re generic search favicon I already filed #7491

**Comment by ghoppaccia** [comment] 2020-01-27 12:27
Perfect, thank you!

**Comment by sflorean** [comment] 2020-02-05 15:21
This is also reproducible with Amazon.com, both issues. 
Device: Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by lime124** [comment] 2020-02-06 21:05
per @boek there's some sort of API thing we need to be able to do this. not a bug but a feature request :)

**Comment by ernstp** [comment] 2020-02-28 06:16
Well you can get search suggestions with duckduckgo on desktop Firefox but I haven't been able to with Fenix...

**Comment by snaggen** [comment] 2020-06-05 13:46
Since Firefox Preview is quite privacy focused, it is a little strange that search suggestions doesn't work for anything else than Google and hence pushing the users to a privacy-hostile actor.

**Comment by EmberHeartshine** [comment] 2020-06-12 16:20
I have seen this before when using the [Add Custom Search Engine](https://addons.mozilla.org/en-US/firefox/addon/add-custom-search-engine/) add-on in Fennec. The plugin in question requires you to insert the JSON format search suggestion URL, in this case:

```
https://www.startpage.com/cgi-bin/csuggest?query={searchTerms}&limit=5&lang=english&format=json
```

(`{searchTerms}` is the required keyword for this particular plugin; most other options use `%s` instead)

There does not appear to be any field to insert this on Firefox Preview/Beta.

**Comment by Nojuuu** [comment] 2021-06-23 09:47
Why not just add another input field to the "Add search engine" and "Edit search engine" menus, where users could add the add search suggestions URL themselves.

**Comment by plwt** [comment] 2022-04-21 20:05
User feedback:  https://support.mozilla.org/en-US/questions/1374368

**Comment by ajhall** [comment] 2022-06-14 01:55
I created https://github.com/mozilla-mobile/fenix/pull/25402 to add a search suggestion URL field on the custom search engine page. Just waiting for some feedback on that PR.

**Comment by FunctionalHacker** [comment] 2022-08-15 09:59
Honestly, I feel like we should implement adding search engines the way Firefox desktop does it. That would be an option in the menu when long pressing the address bar. This should then fetch the favicon, name and opensearch.xml for the current page.

The current custom search engine option is good to have too, in case someone wants to use a custom suggestion provider for example.

**Comment by Nebukadneza** [comment] 2022-08-15 10:04
From a user-perspective, I agree that a convenient workflow based on opensearch.xml would be beneficial. However, I will take "having to manually enter the URLs" any day over not having auto-suggestions. In this light, I really do wonder why the current PR has been open so long without any maintainer attention. If possible, I’d suggest focussing on getting the current PR in as quickly as possible, and then taking up making the workflow convenient for opensearch.xml-enable sites would be a super nice second step …

… However, here I’m just a dumb user, also with no knowledge about how fennec/fenix work on the inside :sweat:

**Comment by ajhall** [comment] 2022-08-15 15:30
I totally agree that the opensearch.xml approach would be better in the long run. My PR mostly just adds a UI on top of some existing code, so I was hoping it was simple and unobtrusive enough that it would fill in the gap until a something more fully-featured was implemented. I'm not sure who to ping to get some attention on it.

**Comment by Nebukadneza** [comment] 2022-08-20 21:35
I’m also not sure, but I’m a bit desperate. So, I’m going to do something that maaay be a tad offensive, and I hope the team-members/contributors will forgive me for this :sweat_smile: .

The last few people who touched similar content, or who merged the respective PRs were:
@pocmo 
@eliserichards 
@ekager 
@boek
@mcarare 

I know your time is probably scrace, but … IMO the work by @ajhall is a raisin you just need to pick off a tray presented right in front of you :gem:. It would be great if his PR got the attention that fixing this user-crippling regression deserves. Thanks and sorry for the rude ping :bow: :bow: :bow: .

**Comment by cpeterso** [comment] 2022-12-26 07:16
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807573

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2022-12-26 07:16 UTC
Labels: feature request 🌟, Feature:SearchProvider, Feature:Search
