### ISSUE TITLE
FNX-5598 ⁃ [Bug] Tab count in toolbar displays incorrect "0" tabs after opening app from long idle

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#2331] opened 2019-05-07 23:30 UTC
## Steps to reproduce
I don't know the exact STR but I see this regularly through normal daily use. My guess at the STR:

* Open Fenix
* Visit a page
* Press home so that app is backgrounded with web site in foreground
* Let Fenix sit unused for a while (hours?)
* Open Fenix from the app launcher

I'm guessing this is a state restoration problem but I was unable to reproduce with Don't Keep Activities.

### Expected behavior
Last viewed web site opens with correct tab count (1)

### Actual behavior
Last view web site opens with incorrect "0" tab count

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1919

**Comment by mcomella** [comment] 2019-05-07 23:37
Related? #2329 #1909 #2332

**Comment by softvision-miralobontiu** [comment] 2019-05-29 11:24
I couldn't reproduce this issue on the latest build 5/29, on Google Pixel (Android 9).
@mcomella can you please try again with the latest build?
Thank you!

**Comment by softvision-miralobontiu** [comment] 2019-06-03 13:53
I will close this issue.
I couldn't reproduce it with the latest build 1.0.1922 (#11530616), with Google Pixel (Android 9).
If anyone can reproduce this, please reopen it.
Thank you!

**Comment by mcomella** [comment] 2019-06-03 20:57
I don't have consistent steps to reproduce but I'll reopen it if I see it again.

**Closed** 2020-08-11 14:50 UTC
Labels: Feature:Tabs, P1, Release Blocker, 🐞 bug
