### ISSUE TITLE
[Bug] session lost when open link in private tab

### ISSUE THREAD

**Issue by nanake** [mozilla-mobile/fenix#3599] opened 2019-06-21 03:31 UTC
## Steps to reproduce
1. Open Fenix in private session
1. Enter address (me enter https://bugzilla.mozilla.org/)
1. Login
1. Long press any link and choose "Open link in private tab" (me long press on "Documentation" on first page of BMO)
1. Refresh page.

### Expected behavior
Still login.

### Actual behavior
It log me out of BMO.

### Device information
* Android device: HMD Global Nokia 6.1 Plus, Android 9
* Fenix version: Fenix 1.0.1925 (Build #11711823 :lizard: 68.0.20190611143747)

**Comment by NotWoods** [comment] 2019-06-22 15:38
Duplicate of #609

**Closed** 2020-08-27 00:39 UTC
Labels: 🐞 bug
