### ISSUE TITLE
[Bug] Unable to download from resumake.io

### ISSUE THREAD

**Issue by Sgt-Miller** [mozilla-mobile/fenix#6433] opened 2019-11-04 15:48 UTC
## Steps to reproduce
Go to resumake.io.     
Click make resume
Click make again. 
Now try to download the (empty) PDF.
### Expected behavior
In Firefox for Android, it downloads as usual.
### Actual behavior
In Firefox preview, I get "Firefox preview can't download this filetype".
![Screenshot_20191104-211211](https://user-images.githubusercontent.com/17806210/68134577-3c745400-ff1a-11e9-8fef-3e653368fb36.png)

### Device information

* Android device: 8
* Fenix version : 
2.2.0 (Build #12901947)
📦: 16.0.0, ab2555b20
🦎: 70.0-20191007080030

**Comment by NotWoods** [comment] 2019-11-05 20:50
Duplicate of mozilla-mobile/android-components#1159. We currently do not support `blob:` URLs, which is what resumake.io uses. Once BZ-1501735 is fixed we can add support.

**Comment by Amejia481** [comment] 2020-05-15 14:57
Now we have support for blob URLs. QA please help us to verify if this website is working as expected.

**Comment by AndiAJ** [comment] 2020-05-18 06:29
Hi, **verified as fixed** on the latest **`Nightly Build #200518 from 5/18`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200518-092417](https://user-images.githubusercontent.com/51314259/82180827-03199980-98ea-11ea-9166-5c455448e3cc.gif)

**Closed by AndiAJ** 2020-05-18 06:29 UTC
Labels: Feature:Download, eng:qa:needed, 🐞 bug
