### ISSUE TITLE
Multiple tabs opened from the same page open in reverse order

### ISSUE THREAD

**Issue by deanis74** [mozilla-mobile/fenix#20217] opened 2021-07-01 13:27 UTC
When I am reading a page and open multiple tabs, I assume the tabs will be listed in the order I opened them. Instead they're opened in reverse. 

## Steps to reproduce
Open a page with multiple links. We'll use https://www.nhl.com/oilers/roster/ for this example. 
1. Open "L. Draisaitl (A)" In a new tab. 
2. Open "R. Nugent-Hopkins (A)" in a new tab. 
3. Saving the best to read for last, open "C. McDavid (C)" in a new tab. 

### Expected behavior
My new tabs are listed in the order I opened them. First is Draisaitl, next Nugent-Hopkins, and finally McDavid. 

### Actual behavior
My new tabs re listed in reverse order from how I opened them. First is McDavid, then Nugent-Hopkins, and finally Draisaitl. 
This behavior is counter-intuitive. If I'm opening links as I come across them, that's the order I plan to read them in. Instead I get a reverse order which, if I've opened a half-dozen tabs as I often do, gets a bit confusing to work backwards through. 

### Device information
* Device vendor / model and Android version: Pixel 2 XL / Android 11
* Firefox for Android version: ? 89.1.1 (Build #2015812947)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16945)

**Comment by Nickoriginal** [comment] 2021-07-01 14:32
It seems to be feature request, nor the bug, because this works as expected, if reading tab list down-up, but additional setting in the "Tabs" can be useful for us!

https://user-images.githubusercontent.com/85299944/124141436-1a85f880-da92-11eb-983a-cb2e308018ec.mp4

**Comment by SoftVision-LorandJanos** [comment] 2021-07-02 09:52
Hi @deanis74 ! Thank you for your report! As @Nickoriginal mentioned above, this might not be considered a bug, I think it's intended this way, and that an option through Tab settings could help make it more intuitive whichever you prefer.
Tested on the latest Nightly (91.0a1 2021-07-02T05:07:53.859).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0).

**Comment by deanis74** [comment] 2021-07-02 15:08
I'm going to have to disagree with @Nickoriginal, for two reasons. 

First, I don't know many people who make a list and read it from the bottom up. 

Second, this behavior is counter to how Firefox  behaves on the desktop. When I open links in new tabs they open from left to right, so first Draisaitl and last McDavid. As someone who uses both mobile and desktop interchangeably, this is not consistent. 

(thanks for the video @Nickoriginal)

**Comment by Nickoriginal** [comment] 2021-07-02 15:43
> (thanks for the video **@Nickoriginal**)

You can insert my video into your issue freely, using this link: https://user-images.githubusercontent.com/85299944/124141436-1a85f880-da92-11eb-983a-cb2e308018ec.mp4

**Comment by deanis74** [comment] 2021-07-10 15:25
I still disagree with @Nickoriginal and @SoftVision-LorandJanos that this is a feature request and not a bug. Repeat my steps but instead of dropping down the list of tabs, swipe left on the address bar. 

Expected: Draisaitl, Nugent-Hopkins, McDavid
Actual: McDavid, Nugent-Hopkins, Draisaitl

Again,counter-intuitive.

**Comment by deanis74** [comment] 2021-07-10 16:22
Follow these previous steps in another mobile browser, eg. Chrome, and the behavior is as I would expect it and not like the broken Firefox behavior.

**Comment by Nickoriginal** [comment] 2021-07-12 06:25
It **cannot be** a bug, because it was provided by the developers in this way and even though this is wrong behavior (flaw), it does not cause _errors or faults_.
I think it's better to call this "flaw with unexpected behavior", as I said, than a bug.

**Comment by Nickoriginal** [comment] 2021-07-12 06:39
I don't deny the existence of this problem and don't underestimate its importance.

**Comment by Nickoriginal** [comment] 2021-07-19 18:26
#20417

**Comment by Glitchy-Tozier** [comment] 2021-07-19 19:38
No idea what this should be called but i agree, it's **definitely** counter-intuitive. 

The current behaviour only messes up the workflows all of us know from desktop-browsers and, at least in my opinion, provides no large upsides that could justify confusing users.

**Comment by Nickoriginal** [comment] 2021-07-19 19:59
I support @deanis74 and @Glitchy-Tozier that this is counter-intuitive (earlier I explained why it can't be a bug) and I want to see this problem solved. Waiting for @deanis74 feedback.

**Comment by Nickoriginal** [comment] 2021-07-19 20:07
No matter what it is: feature request or bug, but when it will be fixed, many Firefox users will like it. Should be focused discussing the problem, not its qualities.

**Comment by deanis74** [comment] 2021-07-20 02:27
Sorry @Nickoriginal, I didn't realize there was anything for me to comment on. I agree with your last comment; let's focus on getting the behavior working properly. 

> To resolve this problem, special setting about the order of opening tabs should be implemented to not mislead users who are already accustomed to this behavior and mainly don't consider it as a bug.

I don't like the setting approach for changes like this which are obviously counter-intuitive to most, if not all. This can be addressed by changing the behavior to what is consistent with Firefox desktop and with other mobile browsers, then adding a "we changed the new tab opening behavior to match what all sane people expect" release note item.

**Comment by Nickoriginal** [comment] 2021-07-20 04:45
> This can be addressed by changing the behavior to what is consistent

> then adding a "we changed the new tab opening behavior to match what all sane people expect" release note item.

Yes, it seems to be a good solution too.

**Comment by gwarser** [comment] 2021-09-27 15:20
I personally prefer A321 order of tabs. When I read something I open links to read them later, but when something more interesting pops up I want to switch to it immediately and I don't want to scroll full list of tabs to get to this one I opened just now - I want most current new tab to be just next to source tab.

**Comment by Glitchy-Tozier** [comment] 2021-09-27 15:35
@gwarser I see where you're coming from, but personally I use the button on the "switch immediately"-banner that pops up when opening something in a new tab. :)

**Comment by gwarser** [comment] 2021-09-27 15:44
> I use the button on the "switch immediately"-banner that pops up when opening something in a new tab. :)

This one is rather annoying: disappear to fast to tap it when needed, covers the content for too long when not needed.

**Comment by boek** [comment] 2023-01-26 23:50
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812871

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by boek** 2023-01-26 23:50 UTC
Labels: 🐞 bug, feature request 🌟, Feature:Tabs, S3, needs:triage, qa-triaged
