### ISSUE TITLE
[Bug]: Private Window button is faded in Private window while using in dark mode 

### ISSUE THREAD

**Issue by mMARUF** [mozilla-mobile/fenix#21428] opened 2021-09-22 07:21 UTC
### Steps to reproduce

1. Open Firefox Nightly in Android 
2. Select Dark Theme
3. Press the Private Window button to switch to the private window
4. Observe the private window button now

### Expected behaviour

The private window button should be perfectly visible, But the button is faded into white color.

### Actual behaviour

The button should retain its original color 

### Device name

Xiomi Redmi Note 7

### Android version

10

### Firefox release type

Firefox Nightly

### Firefox version

Mozilla/5.0 (Android 10; Mobile; rv:94.0) Gecko/94.0 Firefox/94.0

### Window Size

 (inner width and height): 396 x 756

### Screenshot

![Private Window button is not properly visible in dark mode ](https://user-images.githubusercontent.com/45368054/134300045-c07690b8-2d12-4ca0-ac2f-3e9128c86cac.PNG)

**Comment by SoftVision-LorandJanos** [comment] 2021-09-23 08:17
Hi @mMARUF ! Thank you for your report!
This issue was covered in #19862.
As I mentioned in that ticket, I couldn't reproduce this issue. The contrast is clear with the Private browsing icon in dark mode.
Could you clear your data and see if it still reproduces? And write it as a comment for the mentioned bug, because as that was logged before, I will close this one as duplicate. Thank you!

**Closed by SoftVision-LorandJanos** 2021-09-23 08:17 UTC
Labels: 🐞 bug, needs:triage
