### ISSUE TITLE
[Bug] Crash on downloading file with duplicate name

### ISSUE THREAD

**Issue by Yzoni** [mozilla-mobile/fenix#7805] opened 2020-01-19 16:25 UTC
## Steps to reproduce

1. Download a file, for instance fenix from taskcluster.
2. After the download is finished, download the same file again.

### Expected behavior
Downloading the same file without crashing.

### Actual behavior
Fenix crashes completely, while the notification remains indefinitely.

### Device information

* Android device: Xiaomi mi2 A2 Lite
* Fenix version: Build #20181816

```
01-19 17:03:19.263 27543 27543 D GeckoSession: handleMessage GeckoView:PageStart uri=https://firefoxci.taskcluster-artifacts.net/ctBzfe65Sc-ZdxX0293DwQ/0/public/build/arm64-v8a/geckoNightly/target.apk
01-19 17:03:19.292   468 28901 E ResolverController: No valid NAT64 prefix (114, <unspecified>/0)
01-19 17:03:19.383 27543 27663 D sql_support::conn_ext: Transaction commited after 320.967031ms
01-19 17:03:19.384 27543 27664 D places_ffi: places_note_observation
01-19 17:03:19.463 27543 27664 D sql_support::conn_ext: Transaction commited after 78.560938ms
01-19 17:03:19.794 27543 27543 D GeckoSession: handleMessage GeckoView:StateUpdated uri=null
01-19 17:03:19.794 27543 27543 W GeckoSession: No history entries found.
01-19 17:03:20.112 27543 27543 D GeckoSession: handleMessage GeckoView:ProgressChanged uri=null
01-19 17:03:20.114 27543 27543 D GeckoSession: handleMessage GeckoView:PageStop uri=null
01-19 17:03:20.114 27543 27543 I SessionStorage/AutoSave: Save: Load finished
01-19 17:03:20.114 27543 27543 D SessionStorage/AutoSave: Skipping save, other job already in flight
01-19 17:03:20.505 27543 27597 D GeckoScreenOrientation: unlocking
01-19 17:03:20.675 27543 27664 D SessionStorage/AutoSave: Saved state to disk [51ms]
01-19 17:03:21.574  1441 15192 E InputDispatcher: Window handle Window{d42128c u0 org.mozilla.fenix.nightly/org.mozilla.fenix.HomeActivity} has no registered input channel
01-19 17:03:22.488  1806  1806 D InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix.nightly|-1812106464|null|10094
01-19 17:03:22.500 27106 27125 E SQLiteDatabase: Error inserting bucket_display_name=Download owner_package_name=org.mozilla.fenix.nightly parent=24 volume_name=external_primary _display_name=target(1).apk mime_type=application/vnd.android.package-archive _data=/storage/emulated/0/Download/target(1).apk _size=63442370 title=target(1) group_id=-815631089 is_download=true is_pending=1 date_added=1579449802 primary_directory=Download bucket_id=540528482 media_type=0 relative_path=Download/
01-19 17:03:22.500 27106 27125 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE)
01-19 17:03:22.500 27106 27125 E SQLiteDatabase:    at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
01-19 17:03:22.500 27106 27125 E SQLiteDatabase:    at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
01-19 17:03:22.500 27106 27125 E SQLiteDatabase:    at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
01-19 17:03:22.500 27106 27125 E SQLiteDatabase:    at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
01-19 17:03:22.500 27106 27125 E SQLiteDatabase:    at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1599)
01-19 17:03:22.500 27106 27125 E SQLiteDatabase:    at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1468)
01-19 17:03:22.500 27106 27125 E SQLiteDatabase:    at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:2713)
01-19 17:03:22.500 27106 27125 E SQLiteDatabase:    at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3254)
01-19 17:03:22.500 27106 27125 E SQLiteDatabase:    at com.android.providers.media.MediaProvider.insert(MediaProvider.java:2903)
01-19 17:03:22.500 27106 27125 E SQLiteDatabase:    at android.content.ContentProvider$Transport.insert(ContentProvider.java:309)
01-19 17:03:22.500 27106 27125 E SQLiteDatabase:    at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:154)
01-19 17:03:22.500 27106 27125 E SQLiteDatabase:    at android.os.Binder.execTransactInternal(Binder.java:1021)
01-19 17:03:22.500 27106 27125 E SQLiteDatabase:    at android.os.Binder.execTransact(Binder.java:994)
01-19 17:03:22.504 27543 27664 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=kotlin.KotlinNullPointerException, breadcrumbs=[Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Sun Jan 19 16:56:40 GMT+01:00 2020), Breadcrumb(message=Changing to fragment searchFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Sun Jan 19 16:56:41 GMT+01:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Sun Jan 19 16:56:45 GMT+01:00 2020), Breadcrumb(message=Changing to fragment searchFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Sun Jan 19 17:03:03 GMT+01:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Sun Jan 19 17:03:11 GMT+01:00 2020)])
01-19 17:03:22.504 27543 27664 I mozac/CrashReporter: Showing notification
01-19 17:03:22.530 27543 27664 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-7
01-19 17:03:22.530 27543 27664 E AndroidRuntime: Process: org.mozilla.fenix.nightly, PID: 27543
01-19 17:03:22.530 27543 27664 E AndroidRuntime: kotlin.KotlinNullPointerException
01-19 17:03:22.530 27543 27664 E AndroidRuntime:    at androidx.transition.CanvasUtils.throwNpe(CanvasUtils.java:1)
01-19 17:03:22.530 27543 27664 E AndroidRuntime:    at mozilla.components.feature.downloads.AbstractFetchDownloadService.useFileStreamScopedStorage(AbstractFetchDownloadService.kt:18)
01-19 17:03:22.530 27543 27664 E AndroidRuntime:    at mozilla.components.feature.downloads.AbstractFetchDownloadService.useFileStream$feature_downloads_release(AbstractFetchDownloadService.kt:8)
01-19 17:03:22.530 27543 27664 E AndroidRuntime:    at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$1.invoke(AbstractFetchDownloadService.kt:20)
01-19 17:03:22.530 27543 27664 E AndroidRuntime:    at mozilla.components.concept.fetch.Response$Body.useStream(Response.kt:1)
01-19 17:03:22.530 27543 27664 E AndroidRuntime:    at mozilla.components.feature.downloads.AbstractFetchDownloadService.performDownload$feature_downloads_release(AbstractFetchDownloadService.kt:19)
01-19 17:03:22.530 27543 27664 E AndroidRuntime:    at mozilla.components.feature.downloads.AbstractFetchDownloadService.startDownloadJob$feature_downloads_release(AbstractFetchDownloadService.kt:3)
01-19 17:03:22.530 27543 27664 E AndroidRuntime:    at mozilla.components.feature.downloads.AbstractFetchDownloadService$onStartCommand$1.invokeSuspend(AbstractFetchDownloadService.kt:5)
01-19 17:03:22.530 27543 27664 E AndroidRuntime:    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
01-19 17:03:22.530 27543 27664 E AndroidRuntime:    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
01-19 17:03:22.530 27543 27664 E AndroidRuntime:    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
01-19 17:03:22.530 27543 27664 E AndroidRuntime:    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:15)
01-19 17:03:22.533  1441 28912 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
01-19 17:03:22.533  1441 15192 W ActivityTaskManager:   Force finishing activity org.mozilla.fenix.nightly/org.mozilla.fenix.HomeActivity
01-19 17:03:22.542  1441 28912 W DropBoxManagerService: Dropping: data_app_crash (1600 > 0 bytes)
01-19 17:03:22.558 27543 28804 E FA      : Task exception on worker thread: java.lang.IllegalStateException: Not initialized: com.google.android.gms.internal.measurement.zzhj.zzch(Unknown Source:11)
01-19 17:03:22.558 27543 28804 E FA      : Task exception on worker thread: java.lang.IllegalStateException: Not initialized: com.google.android.gms.internal.measurement.zzhj.zzch(Unknown Source:11)
01-19 17:03:22.558 27543 28804 E FA      : Persisted config not initialized. Not logging error/warn
01-19 17:03:22.558 27543 28804 E FA      : Persisted config not initialized. Not logging error/warn
01-19 17:03:22.566 27543 27664 I Process : Sending signal. PID: 27543 SIG: 9
```

**Comment by ekager** [comment] 2020-01-30 15:11
cc @sblatz

**Comment by sblatz** [comment] 2020-02-07 17:43
I'm not able to reproduce this. QA can you please verify?

**Comment by Yzoni** [comment] 2020-02-08 07:39
This issue is really strange. It appears to happen only to files called `target.apk`. For instance I tried putting video file called `target.apk` on my own server and then download it twice: Firefox crashes
Any other file download works fine when dowloading twice.  So the duplicate name is not necessarily the problem.

I made a video as the problem happens:

https://yrck.nl/fp/screenrecord-20200208-081655.mp4

**Comment by sv-sdeiac** [comment] 2020-02-10 09:15
Hello, I can't reproduce this issue using the latest version of Firefox Preview Nightly 2/10 #20410605.

Devices:
- Motorola Moto G6 (Android 8);
- Samsung Galaxy S8 (Android 9).

@Yzoni I can't view your video. Can you please send us a video? Also, please use the latest version of Firefox Preview Nightly to ensure that the issue is reproducible using the newest version. Till we have confirmation from the reporter about the issue, I'll remove the qa:needed and let the issue open, thanks.

**Comment by Yzoni** [comment] 2020-02-10 23:52
Hi, I gave this a closer look and as can be observed from the log I submitted initially. The first exception is thrown by the android media storage application, and not Firefox. After clearing the data of this service, the issue is no longer present.

It appears the the file remained in the database of media storage even after the file was deleted, which is probably a bug in Android. 

Nevertheless, Firefox should catch this (if possible), instead of crashing.

**Comment by Mugurell** [comment] 2020-03-03 16:06
@Yzoni Can you still reproduce this?
I know it's of the essence to use a device with Android 10 and I don't think the issue is device-specific but in all my tries I could not reproduce this.

**Comment by Yzoni** [comment] 2020-03-03 17:19
I can no longer reproduce since I cleared the data of the "media provider" app. To reproduce the corruption you could probably manually add the row from the log file above to Android 10's mediaproviders sqlite database but I doubt it is worth the effort.

**Comment by sv-sdeiac** [comment] 2020-03-05 12:05
Since the reporter can't reproduce anymore the issue, I'll close this issue. 
If anyone can reproduce the problem or have additional information regarding this ticket, please don't hesitate to reopen it, thanks.

**Closed by sv-sdeiac** 2020-03-05 12:05 UTC
Labels: Feature:Download, b:crash, needs:triage, 🐞 bug
