### ISSUE TITLE
[Bug] Push notificación don't work

### ISSUE THREAD

**Issue by joelocandol** [mozilla-mobile/fenix#15477] opened 2020-09-27 13:04 UTC
## Steps to reproduce

Give to webpage like facebook mobile, the permission to send push notifications everytime you get a message or another type of notification

### Expected behavior

The push notification is received even if the browser isn't open, like in the case of Samsung internet browser

### Actual behavior

The notification never is received even if you open the browser and enter in the webpage where the notification should has been send

### Device information

Oukitel c5

* Android device: 7.0
* Fenix version: Nightly 200927 06:04

**Comment by ale82to** [comment] 2020-09-27 14:48
I ve reported this multiple times the developer did not even respond, happy to hear someone else is having same issue,maybe they will bother listening...

**Comment by jonalmeida** [comment] 2021-02-09 10:28
Duplicate of https://github.com/mozilla-mobile/fenix/issues/15028

**Closed by jonalmeida** 2021-02-09 10:28 UTC
Labels: Feature:Notifications, 🐞 bug
