### ISSUE TITLE
[Bug] File is uploaded only the second time, after a page refresh

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [mozilla-mobile/fenix#9651] opened 2020-04-03 06:57 UTC
**Browser / Version**
Firefox Preview Nightly 200402 (🦎: 76.0a1-20200401095134)

**Operating System**
Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)

**Prerequisites:**
- Clear Fenix's Data.

**Steps to reproduce:**
1. Go to https://gofile.io/?t=uploadFiles
2. Tap the "Click here" button.
3. Grant permissions.
4. Select a file.

**Expected Behavior:**
The file is uploaded.

**Actual Behavior:**
The file is not uploaded.

**Notes:**
1. Screenshot attached.
2. Refreshing the page and following STR 2 and 4, works.
3. The browser does not crash.

![Screen capture](https://user-images.githubusercontent.com/16573771/78332822-6c8b5600-7591-11ea-9736-f90ed4702e8c.gif)

**Comment by softvision-sergiulogigan** [comment] 2020-04-03 06:57
See also

**Comment by softvision-miralobontiu** [comment] 2020-10-21 14:48
I was not able to reproduce this issue on the latest Nightly build from 10/21 with Samsung Galaxy tab S6 (Android 10), and Xiaomi Mi4i (Android 5.0.2).
I'll close this issue.

**Closed by softvision-miralobontiu** 2020-10-21 14:48 UTC
Labels: S2, b:webcompat, needs:triage, 🐞 bug
