### ISSUE TITLE
"tab closed" snackbar doesn't go away on its own

### ISSUE THREAD

**Issue by harshlele** [mozilla-mobile/fenix#8490] opened 2020-02-18 17:28 UTC
## Steps to reproduce:
1. Close a tab and switch to another tab

##  Expected behavior
The snackbar showing "tab closed" should go away after some time.

## Actual behavior 
The snackbar never goes away until you click the "undo" button on the snackbar (and the actual undo action doesn't happen when you do that)

Device: Nokia 6.1

OS: Android 10

**Comment by cadeyrn** [comment] 2020-02-18 18:29
Duplicate of #7799.

**Closed** 2020-02-20 02:23 UTC
Labels: needs:triage
