### ISSUE TITLE
[Bug] cancelling closed tab do nothing (regression)

### ISSUE THREAD

**Issue by sloft** [mozilla-mobile/fenix#17753] opened 2021-02-02 10:12 UTC
Hello, cancelling closed tab do nothing on Firefox Browser.
This bug is still there since several versions.

## Steps to reproduce
Click the square icon to show tabs list
Click on a cross (x) to close a tab
Click "cancel" on the little purple pop-up "tab closed"
Nothing happen

### Expected behavior
The closed tab should reappear in the tabs list.

### Actual behavior
Nothing happen, the closed tab doesn't show up again.

### Device information
Not device-dependent

* Device vendor / model and Android version: Android 10
* Firefox for Android version: 85.1.1

**Comment by mcarare** [comment] 2021-02-03 08:54
I cannot reproduce this on any Firefox version (Release, Beta, or Nightly).

**Comment by amedyne** [comment] 2021-02-03 14:26
@sloft Can you revalidate? Also note that after clicking "cancel" or "undo", the tab that you closed goes to the top of the list of open tabs.

**Comment by sloft** [comment] 2021-02-03 15:04
@amedyne I confirm the tab goes to the top of the list. So this is not really a bug but... the problem is :
With hundreds of pages in the list, it is not really possible to get the page back.

Would it be possible to keep the page index position in the list when restored ?
Thank you.

**Comment by amedyne** [comment] 2021-02-03 15:30
Thank you for checking @sloft. We will re-evaluate the index position when a tab is restored.

**Comment by Dunexus** [comment] 2021-02-03 15:43
Keeping the index position when a tab is restored is covered by https://github.com/mozilla-mobile/fenix/issues/10986

**Comment by ekager** [comment] 2021-02-04 00:27
Closing for #10986

**Closed by ekager** 2021-02-04 00:27 UTC
Labels: needs:UX-feedback, 🐞 bug
