### ISSUE TITLE
Huawei App Galery

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#15067] opened 2020-09-14 10:27 UTC
Why is there no firefox android browser in huawei app gallery store?

**Comment by kbrosnan** [comment] 2020-09-29 17:34
Duplicate of #8754

**Closed by kbrosnan** 2020-09-29 17:34 UTC
Labels: needs:triage

**Comment by anotherus3r** [comment] 2020-09-29 18:04
> Duplicate of #8754
@kbrosnan do you mean #13420? Huawei AppGallery is an app store.

**Comment by kbrosnan** [comment] 2020-10-01 14:32
Yep. Sorry I misunderstood the issue report at first we see a lot more reports of the downloads gallery one.
