### ISSUE TITLE
[Bug]WebPages [tabs] reload after losing focus, rather than redisplay

### ISSUE THREAD

**Issue by abitawoods1** [mozilla-mobile/fenix#19291] opened 2021-04-28 15:22 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
A.
Open a web page.   Change to other tabs, and return to the first web page.   Rather than [re]displaying the page, it is reloaded from the web, and then displayed.   This is annoying, as it also will regenerate the page with current conditions [say, that web-based javascript is turned off via add on]

B.
Open a web page.   Change to another app.   On returning to FoxAndroid, the webPage is reloaded from the web

### Expected behavior
In either case, the page should just redisplay, rather than reload from the web.
### Device information
Samsung A11, using Android 10
FoxAndroid: 87.0.0-rc. 1

Note:  This behavior is new to my fox.  Did not do this on the older Samgung Galaxy, using older android.   Feels like a firefox behavior, particularly because of the A. case, above.

Note: I am not aware of any FoxAndroid switch with will defeat the auto-reload-from-web

**Comment by SoftVision-LorandJanos** [comment] 2021-04-29 07:44
Hi @abitawoods1 ! Thank you for your report. I am able to reproduce the issue described above on Firefox Release 87.0.0-rc. 1, using a HTC Nexus 9 with Android 7.1.1, however on the latest Nightly (210429 05:01) GV90.0a1 this issue is not reproducible (using the same device and Android version)

**Comment by abitawoods1** [comment] 2021-05-01 03:10
Hi, @SoftVision-LorandJanos ...  I appreciate your request's intent, but i don't have any nightlies installed to my phone.    I can, when I make the next update to FoxAndroid, report back.

**Comment by schuyler1d** [comment] 2021-05-01 14:02
Hi, I have the same issue on Samsung Galaxy A10e.
I tried on the nightly:
90.0a1 (Build #2015807689)
AC: 90.0.20210430143137, 699977fb1
GV: 90.0a1-20210430092829
AS: 75.2.0

And still have the problem. There was no nightly in the app store for yesterday so I'm guess maybe there was a rollback?

**Comment by schuyler1d** [comment] 2021-05-02 17:22
Maybe also worth noting that for me this was a regression of the major rewrite release from Aug 2020 (80.0?)

**Comment by schuyler1d** [comment] 2021-07-14 01:05
I think this is a duplicate of https://github.com/mozilla-mobile/fenix/issues/12731

**Comment by abitawoods1** [comment] 2021-07-14 03:58
Yes.   Sure does look like a duplicate.   Though the use cases might differ; can't tell.

Also, I don't have the nightly.  Using 89.1.1 and the bug still flourishes , , ,

**Comment by pocmo** [comment] 2021-07-15 12:00
-> #12731

**Closed by pocmo** 2021-07-15 12:00 UTC
Labels: needs:triage, qa-triaged, 🐞 bug
