### ISSUE TITLE
[Bug] Horizontal scroll bar moves with top toolbar when scrolling vertically

### ISSUE THREAD

**Issue by yump** [mozilla-mobile/fenix#10220] opened 2020-04-26 03:15 UTC
## Steps to reproduce
1. Set toolbar to "top".
1. Pinch-to-zoom or visit desktop site, to cause horizontal scroll bar to appear at bottom of viewport.
1. Scroll down until URL bar is absorbed into top of viewport.

### Expected behavior
Horizonal scroll bar remains stuck to bottom of viewport.

### Actual behavior
Horizontal scroll bar moves up the page and stops, about 1 URL bar's width from the bottom.

### Device information
* Android device: Nokia 6.1, Android 10
* Fenix version: 75.0.0-beta.6 (Build #2015735819)

**Comment by yump** [comment] 2020-04-27 15:09
Here is a picture of what it does:

![flying_scrollbar](https://user-images.githubusercontent.com/2214413/80387937-dfc17880-886e-11ea-9884-f57f48810db2.png)

**Comment by sv-sdeiac** [comment] 2020-04-28 06:03
Hi, I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 4/27 #21181807.

Devices:
- Google Pixel (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG G7 fit (Android 8.1).

### Notes
- It seems that the issue is somehow reproducible even using the Bottom toolbar but is not so visible as the Top toolbar.

**Comment by yump** [comment] 2020-04-28 06:09
Turns out this doesn't just affect the horizontal scrollbar.  It seems to be a general problem with floating page elements anchored to the bottom of the viewport.  One example is Tumblr's "install our app pwease" nag box:

![fenix-floaters](https://user-images.githubusercontent.com/2214413/80452900-dd056880-88ec-11ea-8e7f-604df68aa0ff.jpg)

**Comment by tim-elmer** [comment] 2020-04-28 19:36
May be duplicate of https://github.com/mozilla-mobile/fenix/issues/8768, seems to be same (mis)behavior.

**Comment by yump** [comment] 2020-04-29 03:14
Ah, yes, on Nightly the scrollbar behaves like the video from [this comment](https://github.com/mozilla-mobile/fenix/issues/8768#issuecomment-614545619), so almost certainly the same cause.  Nightly's fix for #8768 does reduce this from a big distraction to a papercut.

As a user, I absolutely prefer to accept some jankiness in the web content in exchange for low-latency asynchronous scrolling. CPU-guzzling websites are everywhere and deserve only "best-effort" scheduling.  However, the scrollbar, as part of the browser itself, should perhaps be drawn synchronously with the scrolling?

**Comment by tim-elmer** [comment] 2020-04-29 03:20
Without any real knowledge of what's going on, it looks to me like FF forgets that the viewport should no longer exclude the bottom toolbar's space when it's on the top. That would, in my mind, explain why the scrollbars also "float".

**Closed** 2021-03-01 05:33 UTC
Labels: Feature:Gesture, Feature:Toolbar, S2, wontfix, 🐞 bug
