### ISSUE TITLE
[Bug] Open links in the background

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#17060] opened 2020-12-16 00:51 UTC
Are there any chances that opening links in the background that gone with fennec will be re-implemented?
I'm surprised I couldn't find an open issue.

**Comment by jonalmeida** [comment] 2020-12-16 05:45
Duplicate of https://github.com/mozilla-mobile/fenix/issues/470

**Closed by jonalmeida** 2020-12-16 05:45 UTC
Labels: needs:triage, 🐞 bug
