### ISSUE TITLE
[Feature Request] When the toolbar is on the top, the new tab button should also be near the top

### ISSUE THREAD

**Issue by DavidJCobb** [mozilla-mobile/fenix#14403] opened 2020-08-29 05:34 UTC
### What is the user problem or growth opportunity you want to see solved?

Opening a new tab is slower and more annoying in Fenix versus Fennec due to the position of the new tab button. Even if you have the browser toolbar set to appear at the top of the screen, the new tab button displayed in the tab tray is displayed near the bottom of the screen.

(Side note: per #12774 it's not actually a "new tab button" and it does not "create a new tab." Pretending that it is, and does, is a useful simplification for the purposes of this feature request.)

### How do you know that this problem exists today? Why is this important?

I know that the new tab button is at the bottom of the screen because on the current release of Firefox for Android, it is at the bottom of the screen.

To get to the tab tray in the first place, you need to press a button on the toolbar. If the toolbar is set to display at the top of the screen, then your fingers are therefore going to be near the top of the screen immediately after pressing that button. Now, having opened the tab tray, there are really only three actions that you're going to take: interact with one of the visible tabs anywhere on the screen, attempt to scroll the tab list (and probably fail due to #14205), or open a new tab. The former two interactions require you to move your fingers to varying locations on the screen. The latter interaction only requires you to move your finger to the position of the new tab button.

On Fennec, the new tab button was displayed in more or less the same place as the button to open the tab list. This meant that you could open a new tab almost instantly just by double-tapping, and then immediately interact with the address bar, which (being part of the very same toolbar as the tab list button) would be almost directly under your finger. On Fenix, you have to move your hand all the way down the screen, tap the new tab button, and then move your hand all the way back up to the top of the screen to then interact with the address bar and actually use your new tab.

### Who will benefit from it?

People who open new tabs and then proceed to use them.

**Comment by Poopooracoocoo** [comment] 2020-09-05 10:48
Also see: #13098 (unfortunately locked and kinda censored)

**Comment by dsvk** [comment] 2021-03-04 16:40
Duplicate of #12703?

**Closed** 2021-09-07 23:07 UTC
Labels: Feature:Tabs, wontfix
