### ISSUE TITLE
[Bug] Extra empty space in the middle of search widget

### ISSUE THREAD

**Issue by jyeontaek** [mozilla-mobile/fenix#4385] opened 2019-07-30 17:24 UTC
## Steps to reproduce
1. Place search widget on home screen.
2. Adjust the widget size to 2x1.
### Expected behavior
The Firefox logo and microphone icon should be adjacent without much blank space in the middle.
### Actual behavior
There is extra space in the middle.
<img width="387" alt="Screen Shot 2019-07-30 at 10 22 29 AM" src="https://user-images.githubusercontent.com/11740983/62150953-181e3100-b2b4-11e9-923d-26cfc99dbf74.png">

### Device information

* Android device: Nexus 5 API 24
* Fenix version: ?

**Comment by lime124** [comment] 2019-07-30 17:55
@jyeontaek the screenshot i'm seeing doesn't seem to match up with verdi's spec. it looks like in the screenshot there's a lot more blank space which is causing it to look unbalanced as you point out. is something happening with the text that it's getting cut out?

For reference:
https://mozilla.invisionapp.com/share/UJQJP4IC7WN#/screens/349402550_Searchwidget

/cc @Verdi

**Comment by jyeontaek** [comment] 2019-07-30 18:06
In the screenshot, the widget is 2x1 cell size, so no text is placed inside (just like we want). No issues here.
The problem is that the spec says 2x1 cell size should be 100x50 dp, but this doesn't fully cover the cells and causes a couple other problems. So, I stretched out the widget to fully cover the cells (just like how Fennec does).

**Comment by Verdi** [comment] 2019-07-30 18:09
> The problem is that the spec says 2x1 cell size should be 100x50 dp, but this doesn't fully cover the cells and causes a couple other problems. 

What problems does this cause?

**Comment by jyeontaek** [comment] 2019-07-30 18:14
All the unoccupied, invisible space in the cells are still part of the widget, so the user can move the widget by holding this space. The user also can't place another widget directly next to the search widget because of this invisible space.

**Comment by sblatz** [comment] 2019-07-30 18:16
To be clear, this is the current behavior of Fennec as well: 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/62154372-65ea6780-b2bb-11e9-8b6f-b8f4657ad0c3.png">

**Comment by Verdi** [comment] 2019-07-30 18:16
> All the unoccupied, invisible space in the cells are still part of the widget, so the user can move the widget by holding this space. The user also can't place another widget directly next to the search widget because of this invisible space.

That's fine. I think that's an acceptable trade-off.

**Comment by sblatz** [comment] 2019-08-07 17:26
Closing this as it's expected behavior according to UX :)

**Comment by Verdi** [comment] 2019-08-07 17:31
The extra space in the middle of the widget is not the expected behavior. I said the acceptable tradeoff was the invisible space around the widget. The 2x1 widget should be 100 x 50 dp.

**Comment by jyeontaek** [comment] 2019-08-07 17:33
The extra space in the middle of the widget has been fixed. I think we can close this issue now.

<img width="346" alt="Screen Shot 2019-08-07 at 10 33 04 AM" src="https://user-images.githubusercontent.com/11740983/62644370-cce0cf80-b8fe-11e9-973e-24e610ee7f0f.png">

**Comment by Verdi** [comment] 2019-08-07 17:34
Perfect. Thank you.

**Closed by Verdi** 2019-08-07 17:34 UTC
Labels: feature:SearchWidget, 🐞 bug
