### ISSUE TITLE
White stripe at the top of Firefox when scrolling down on OneUI

### ISSUE THREAD

**Issue by yuspensky** [mozilla-mobile/fenix#23585] opened 2022-02-05 13:34 UTC
Hi,
Short bug description:
When I open web site and scroll it down - at the very top of browser under the phone status bar - there appears thin white stripe that is not supposed to be there. When scrolling upwards - it disappears. Having white stripe to appear and disappear on black header website looks irritating to the eye. 
Steps to reproduce:
1. Phone: I have Samsung s20FE with OneUI 4.0, gesture navigation and dark mode theme selected in phone settings.

2. Apps: The issue appears on all versions of firefox: Firefox stable (v. 96.3.1), Firefox beta (97.0.0-beta.6) and Firefox Nightly (98.0a1). 
Navigation bar is at the bottom as per settings.

3. Web Sites - you would need a web site that has black header but does not have black theme - those make it super easy to see the issue. I post several examples for such web sites below:
a. Engadget - https://www.engadget.com/
b. Macrumors - https://www.macrumors.com/
However even google search will have that white stripe when scrolling down.
The web sites that do have dark theme don't have such an issue - however it might be that black stripe is added and it is not easily visible because status bar is black.

4. Action: you would need to scroll page down for white stripe to appear, when you scroll up it disappears. 

5. I attach several pictures of the issue - first from engadget, second is from google search.

![Screenshot_20220205-152507_Firefox~2](https://user-images.githubusercontent.com/23138179/152644165-1ce6b784-75e8-4375-afa3-800fa9d78924.jpg)
![Screenshot_20220205-152443_Firefox~2](https://user-images.githubusercontent.com/23138179/152644167-0dcc5a4e-61d0-4131-8acb-8085c8deb2e1.jpg)

**Comment by yuspensky** [comment] 2022-02-05 14:16
Small correction: you would need to scroll web page from bottom to top (so effectively upward) to see the white stripe.

**Comment by LaurentiuApahideanSV** [comment] 2022-02-07 14:46
I can confirm the issue is reproducible on Firefox Preview Nightly 2022-02-07. The issue has also been reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=1734261. I will close this issue as it will be handled there.
### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android 9)

**Closed by LaurentiuApahideanSV** 2022-02-07 14:46 UTC
Labels: needs:triage
