### ISSUE TITLE
FNX-12870 ⁃ [Bug]  crashes when opening a bookmarks folder (Samsung Galaxy Tab S5e)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#11874] opened 2020-06-24 05:41 UTC
## Steps to reproduce
From https://www.reddit.com/r/firefox/comments/hetdkv/firefox_preview_nightly_crashes_when_i_open_a/

This is consistent and happens everytime. I am running on Samsung Galaxy Tab S5e running Android 9. Here is about:crashes. https://imgur.com/a/xeh0y8b

Here are the first two Socorro links. 

https://crash-stats.mozilla.org/report/index/6c0f2cf5-48c5-4323-9b86-5bf8b0200624 
https://crash-stats.mozilla.org/report/index/e2ac7897-114a-4869-b3a1-b16130200624

The process was as follows: I have turned off all my Add-ons. I quit out of Firefox which deletes tabs, history, cookies, cache, site permissions. I close all apps. I open Firefox Preview Nightly. I go to bookmarks and open the Great Bookmarks folder and it crashes.

Before this it would crash after going to that folder for the 2nd or third time. It has gotten worse. 

### Expected behavior
No crash. 

### Actual behavior
Crash

### Device information
* Android device: Samsung Galaxy Tab S5e running Android 9
* Fenix version: nightly

**Comment by sv-ohorvath** [comment] 2020-06-24 07:57
Same as https://github.com/mozilla-mobile/fenix/issues/11838. Closing as a duplicate.

**Comment by Dan884** [comment] 2020-06-24 18:58
I cleared the Storage data, uninstalled the app, reinstalled it and setup all the settings, bookmarks, Add-ons, etc the same way. For now the problem is fixed.

**Comment by Dan884** [comment] 2020-06-24 20:08
Nope. The problem started happening again after going through several Bookmarks. At least it didn't do it the first time.

**Closed** 2020-08-11 05:06 UTC
Labels: needs:triage, 🐞 bug
