### ISSUE TITLE
[Bug] Can't enable push notifications

### ISSUE THREAD

**Issue by braedon** [mozilla-mobile/fenix#16338] opened 2020-11-03 07:01 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Navigate to the [Microsoft web push demo](https://webpushdemo.azurewebsites.net/) (or any other site that implements web push),
2. Click the "Initiate push" button (or equivalent),
3. Select "Always" in the resulting popup (if first time).

### Expected behavior
Receive an Android notification from the site.

### Actual behavior
No notification arrives.

Debugging shows the [PushManager.subscribe()](https://developer.mozilla.org/en-US/docs/Web/API/PushManager/subscribe) promise resolves to `DOMException: User denied permission to use the Push API.`, even though the user selected "Always" allow in the popup, and clicking the padlock in the address bar shows notifications are "Allowed".

### Device information

* Android device: Oneplus 5T, Android 10, OxygenOS 10.0.0
* Fenix version: 84.0a1, buildID 20201029
 
The issue is not present in versions 82 (current) or 83 (beta).

**Comment by jonalmeida** [comment] 2020-11-06 17:27
cc: @Amejia481 looks like someone else already filed this. 🙂

**Comment by jonalmeida** [comment] 2020-11-16 22:50
For the issue: @Amejia481 has fixed the root cause of this bug that is in the latest AC update. Unfortunately, Fenix is a few versions behind at the moment. Will update when this is in.

**Comment by jonalmeida** [comment] 2020-11-17 17:27
@braedon this should be fixed now in Nightly if you could re-test this for us as well.

**Comment by braedon** [comment] 2020-11-18 04:08
@jonalmeida Seems to be working on Nightly again, thanks!

**Comment by jonalmeida** [comment] 2020-11-18 04:34
Closing as resolved. I don't think we need QA to verify this since the OP has done that for us.

**Closed by jonalmeida** 2020-11-18 04:34 UTC
Labels: Feature:Push, 🐞 bug
