### ISSUE TITLE
print option is not present in android firefox

### ISSUE THREAD

**Issue by holequantum** [mozilla-mobile/fenix#26568] opened 2022-08-21 08:32 UTC
it is present in firefox desktop but not in the firefox mobile can we have this feature.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21347)

**Comment by kbrosnan** [comment] 2022-08-21 15:24
Duplicate Duplicate of https://github.com/mozilla-mobile/fenix/issues/10217

**Closed by kbrosnan** 2022-08-21 15:24 UTC
Labels: needs:triage
