### ISSUE TITLE
[Bug] Address bar shows different URL when clicked

### ISSUE THREAD

**Issue by nielmistry** [mozilla-mobile/fenix#18517] opened 2021-03-17 13:57 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Don't know what triggered it. 

But afterwards, navigate to any website. 
Click on the address bar. 

### Expected behavior
The selected address bar should show the URL of the page you are currently on.

### Actual behavior
Shows address of an older webpage (same address even when navigating to different webpages)

### Device information

* Device vendor / model and Android version: Google Pixel 4a Android version 11 (build number: RQ1A.210205.004)
* Firefox for Android version: 86.1.1 (Build #2015794883)

**Comment by abodea** [comment] 2021-03-17 14:12
Thank you for adding this issue!
I was not able to reproduce it on the latest Nightly 3/17 with Google Pixel 4 XL (11).
Can you please mention what websites you accessed? 
And also, can you please attach a video/gif?

**Comment by nielmistry** [comment] 2021-03-17 15:07
Yeah here's a video:

https://youtube.com/shorts/C85NuM4rwF8

And even after a force stop the error persisted (although a different
website was stuck in the address bar)

But after leaving my phone for a while and revisiting, it works as expected
now.

**Comment by kbrosnan** [comment] 2021-03-18 14:38
Fairly sure this is a duplicate of https://github.com/mozilla-mobile/fenix/issues/17791

**Closed by kbrosnan** 2021-03-18 14:38 UTC
Labels: Feature:Toolbar, qa-triaged, 🐞 bug
