### ISSUE TITLE
[Bug] Crash when opening a private tab while normal tab is loading

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#16634] opened 2020-11-18 15:29 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Make sure "open links in private tabs" is set to false
- Completely close the browser
- In another app, click on a link
- While the opened tab is loading, quickly open a new private tab

### Actual behavior
The browser crashes (native crash)

### Device information

* Android device: Huawei Nova 6 (Android 10)
* Fenix version: Nightly 201117 20:41 (Build #2015776235)

**Comment by softvision-miralobontiu** [comment] 2020-11-18 17:03
@mobd could you give us the details from Settings - About Firefox Nightly - crashes?
Thank you!

**Comment by mobd** [comment] 2020-11-18 18:02
I dont know if its helpful since there is no stacktrace but here you go:

5e086782-4ccc-402d-b8d0-8c621ade6a64
<native crash>
----
<native crash>

**Comment by ekager** [comment] 2020-11-18 19:44
Could you make sure to report the crash when you get a crash dialog and then post the link from about:crashes? I can't repro with the app/link combo I'm trying

**Comment by mobd** [comment] 2020-11-18 19:59
@ekager https://crash-stats.mozilla.org/report/index/bp-ce058612-5853-4e7d-82b7-206950201118

I think this is similar to #16442 but I reported a new bug since the crash information is different

**Comment by mobd** [comment] 2020-11-18 20:21
Also this one: https://crash-stats.mozilla.org/report/index/bp-7c621bf4-6c10-404e-b416-9c5be0201118

For this one I didn't open a private tab but only opened a link from another app when the browser was closed

**Comment by ekager** [comment] 2020-11-20 07:24
Gotcha, this looks like it could be https://bugzilla.mozilla.org/show_bug.cgi?id=1532456

**Comment by sflorean** [comment] 2021-05-25 11:46
@mobd could you please re-check if this is still reproducible for you? The dependency for Bugzilla bug is closed.
 Tested on Nightly 5/25 and couldn't reproduce the issue.

**Comment by mobd** [comment] 2021-05-25 19:28
I can no longer reproduce either

**Comment by sflorean** [comment] 2021-05-26 13:04
Closing based on the above comment. Thank you @mobd for the update.

**Closed by sflorean** 2021-05-26 13:04 UTC
Labels: b:crash, needs:gv, qa-triaged, 🐞 bug
