### ISSUE TITLE
FNX-3262 ⁃ [Bug] Cannot select text in a text field on long press

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10058] opened 2020-04-20 13:51 UTC
## Steps to reproduce
1. Go to: https://github.com/mozilla-mobile/fenix/issues/new
1. Type in something in the title field/description and try to select it. 
1. Observe that the text selector doesn't appear.

### Expected behavior
Should be able to select the text 

### Actual behavior
Not able to select the text

### Device information
* Android device: Motorola One Power, Android 10
* Fenix version: 4.3.0 (Build #21082025)
And Nightly 200420 06:01 (Build #2015735603)
![20200420](https://user-images.githubusercontent.com/42088907/79758541-0d596f80-830d-11ea-98da-5c89ec28e029.gif)UNITO-UNDERSCORE!185713!

**Comment by eliserichards** [comment] 2020-05-06 19:26
Closing as dupe of #2038

**Closed** 2020-08-10 18:26 UTC
Labels: Feature:ContextMenu, b:web-content, needs:triage, 🐞 bug
