### ISSUE TITLE
[Bug] Newly-available addons that were installed before Preview cannot be enabled

### ISSUE THREAD

**Issue by BeeeWall** [mozilla-mobile/fenix#9994] opened 2020-04-16 15:23 UTC
## Steps to reproduce
1. Using a pre-Fenix version of Nightly, install a few addons that are now available, like Dark Reader and HTTPS Everywhere, as well as uBlock Origin.
2. (For comparison) Install the build of Fenix where uBlock got enabled. It worked fine.
3. Install the latest update and try to enable HTTPS Everywhere and Dark Reader.
4. (For comparison) Install another newly-available addon, such as NoScript.

### Expected behavior
They will enable fine and work, just like the uBlock update did if you had uBlock previously, and just like newly-installed addons do.

### Actual behavior
The addon says it's enabled, but it does not move to the Enabled section, and does not work when browsing. If the app is closed and reopened, the addon page shows it as disabled again.

### Device information

* Android device: Samsung Galaxy S10e on the Android 10-based One UI 2.1
* Fenix version: 200416 8:30 (Build #2015734851)

**Comment by Amejia481** [comment] 2020-04-16 21:46
This will be fixed after this pr lands https://github.com/mozilla-mobile/android-components/pull/6693 and Fenix picks the new version on AC that contains it

**Comment by BeeeWall** [comment] 2020-04-16 21:55
Oops, didn't realize an issue had been filed over there already. Didn't think to check.

Thanks for fixing it so quickly!

**Comment by Amejia481** [comment] 2020-04-17 18:36
This should be fixed in master, @AndiAJ would you mind taking a look? :)
Related issue https://github.com/mozilla-mobile/android-components/issues/6685

Be aware that now we are enabling the newly supported add-ons when the notification is shown.

**Comment by AndiAJ** [comment] 2020-04-22 17:14
Hi @Amejia481 , I've just checked this matter using a Google Pixel 3a (Android 10) using the following scenarios:

## 1st scenario
### Fennec → Fenix GV 76 from 4/6 → Fenix GV 77 from 4/16 →Latest Fenix GV 77 from 4/22
#### ► Video after migrating from Fenix GV 76 from 4/6 → Fenix GV 77 from 4/16
![20200422-183212](https://user-images.githubusercontent.com/51314259/80009072-3cb8d980-84d1-11ea-9ebf-7a850d9fa043.gif)

❌ **The Add-ons are disabled** after the migration
❌ If you enable them, **each time you re-open them they are enabled over and over**
❌ The **notification is displayed each time you open Fenix**
❓ Bumped into a **"Failed to querry Add-ons!"error** after closing Fenix and resuming it.
     Due to this **no notification get's displayed**

#### ► Video after migrating from Fenix GV 77 from 4/16 →Latest Fenix GV 77 from 4/22
![20200422-184805](https://user-images.githubusercontent.com/51314259/80010560-43485080-84d3-11ea-8197-8f0040466d76.gif)

❌ **The Add-ons are disabled** after the migration
❌ If you enable them, **each time you re-open them they are enabled over and over**
❓  **No notification is displayed**
❓ Bumped into a **"Failed to querry Add-ons!"error** after closing Fenix and resuming it.

## 2nd scenario
### Fennec → Fenix GV 77 from 4/16 →Latest Fenix GV 77 from 4/22
#### ► Video after migrating Fennec → Fenix GV 77 from 4/16
![20200422-192354](https://user-images.githubusercontent.com/51314259/80011297-59a2dc00-84d4-11ea-9010-72ba447df481.gif)

✔️  The **Add-ons are enabled** after the migration
✔️  The **enable/disable state is properly displayed**
✔️  **No notification is displayed** (as they are installed)
❓ Bumped into a **"Failed to querry Add-ons!"error** after closing Fenix and resuming it.

#### ► Video after Fenix GV 77 from 4/16 →Latest Fenix GV 77 from 4/22
![20200422-192523](https://user-images.githubusercontent.com/51314259/80011875-23b22780-84d5-11ea-98bd-0f1dfcac26c0.gif)
✔️  The **Add-ons are enabled** after the migration
✔️  The **enable/disable state is properly displayed**
✔️  **No notification is displayed** (as they are installed)
❓ Bumped into a **"Failed to querry Add-ons!"error** after closing Fenix and resuming it.

Please review and share your thoughts. ☺️ 
I'll remove the QA needed label until further notice.

**Comment by BeeeWall** [comment] 2020-04-22 21:13
It seems to have been fixed (at least for me) so I'm gonna close this.

**Comment by Amejia481** [comment] 2020-04-22 21:15
Sorry, @AndiAJ would you mind re-testing. Test the latest build from master, as it will have the fix. Also be aware, if you have a previous open instance of Fenix, you have kills from the task switcher and open it again.

**Comment by Amejia481** [comment] 2020-04-22 21:17
@BeeeWall Thanks for verifying :) 
I opened it again as we need QA verifies the issue in multiple devices.

**Comment by BeeeWall** [comment] 2020-04-22 21:18
Oops, my bad then.

**Comment by AndiAJ** [comment] 2020-04-23 12:58
Hi, **verified as fixed** after updating to the latest **`Nightly Build #2015736177 from 4/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• Samsung Galaxy S7 (Android 7)

Performed the following updates:
**Fennec → Fenix GV 76 from 4/6 → Fenix GV 77 from 4/16 →Latest Fenix GV 77 from 4/23**

**► Video after migrating Fenix GV 77 from 4/16** 
![20200423-150525](https://user-images.githubusercontent.com/51314259/80102128-0899f300-857b-11ea-9366-0c04c5959f74.gif)

**► Video after migrating to the latest Fenix GV 77 from 4/23** ✔️ 
![20200423-150640](https://user-images.githubusercontent.com/51314259/80102265-2e26fc80-857b-11ea-9465-b5a552043c6d.gif)

**Comment by Amejia481** [comment] 2020-06-09 15:55
We receive [a report](https://bugzilla.mozilla.org/show_bug.cgi?id=1643898) of this issue. It would be pretty helpful if QA can help us to determine if this still an issue.

The user was using  77.0.0-beta.2

**Comment by Amejia481** [comment] 2020-06-11 15:49
It will be ideal if we can test on Xiaomi devices, as it was the device where the user is experiencing the issue.

**Comment by sflorean** [comment] 2020-06-16 10:12
Tested this with Xiaomi Redmi Note 8T (Android 9) on Nightly and Beta channels, and couldn't reproduce the issue.  Performed 2 scenarios: 
- disable the addons > migrate > enable them;
- enable > migrate > disable/enable.

**Comment by Amejia481** [comment] 2020-06-29 13:42
> It will be ideal if we can test on Xiaomi devices, as it was the device where the user is experiencing the issue.

We can close this issue, as we discovered that the reported bug is not related to add-ons, it's due to some devices that are not able to run WorkManager, we are going to open a new issue for it.

**Closed by Amejia481** 2020-06-29 13:42 UTC
Labels: Feature:WebExtensions, 🐞 bug

**Comment by csadilek** [comment] 2020-07-08 22:35
> It's due to some devices that are not able to run WorkManager, we are going to open a new issue for it:

https://github.com/mozilla-mobile/android-components/issues/7659
