### ISSUE TITLE
[Bug] Nightly and Beta for Android not consistently following Android 10 system default theme

### ISSUE THREAD

**Issue by LordLogjam** [mozilla-mobile/fenix#12342] opened 2020-07-07 12:55 UTC
## Steps to reproduce
Set system dark mode to automatic based on sunset-sunrise times.
Set Nightly/Beta theme to "follow device theme"

### Expected behavior
Firefox should follow the device theme with dark mode being turned on at sunset and light mode at sunrise.

### Actual behavior
Either the switch does not occur or it switches back after a few minutes. This happens most when switching to dark mode from light.
The Dark Reader add-on seems to also suffer from this (perhaps it is pulling the data for what mode to be in from Firefox?).
Other apps set to the same thing follow the system theme just fine (eg Telegram, Sync for Reddit, Twitter, Google apps).

### Device information
* Android device: Samsung Galaxy S10e. Android 10 with June security patch.
* Fenix version: Nightly 200707 06:01 (Build #21890608) but it also happens on Beta for Android and was happening on Preview as well.

**Comment by sflorean** [comment] 2020-07-20 14:58
Duplicate of #11372.

**Closed** 2020-08-28 21:56 UTC
Labels: needs:triage, 🐞 bug
