### ISSUE TITLE
[Bug]: Occasional "Couldn't change wallpaper" when opening

### ISSUE THREAD

**Issue by bjherbison** [mozilla-mobile/fenix#27072] opened 2022-09-20 09:00 UTC
### Steps to reproduce

1. Don't use Nightly for a while.
2. Open Nightly.

Alternate:
1. Touch the mask for private browsing.
2. Touch the mask to leave private browsing.

### Expected behaviour

Opens with no annoying message.

### Actual behaviour

A message like "Couldn't change wallpaper" is displayed over the URL bar for a few seconds.

### Device name

Google Pixel 6 Pro

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

107.0a1

### Additional information

I was told in the Matrix room that issue 26997 would  fix the issue. That issue has been "Verified as fixed on latest Nightly 107.0a1" so I updated my Nightly and still have the issue.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21616)

**Comment by bjherbison** [comment] 2022-09-20 09:20
Build information:

107.0a1 (Build #2015905131), 8fa1924e8+
AC: 107.0.20220919190141, 7776657743
GV: 107.0a1-20220919105141
AS: 94.2.0

2022-09-20T05:09:55.432352

The last part is 2022-09-20, and the other bug says fixed in Nightly "from 09/19".

Another way to reproduce: Enter and leave settings.

**Comment by quadriflax** [comment] 2022-09-20 09:45
Been having this issue for a while now, but it happens every time. See here for first notice: https://github.com/mozilla-mobile/fenix/issues/26999#issuecomment-1248351555

I just updated to latest nightly from Play and it persists:

107.0a1 (Build #2015905129), 8fa1924e8+
AC: 107.0.20220919190141, 7776657743
GV: 107.0a1-20220919105141
AS: 94.2.0

**Comment by rvandermeulen** [comment] 2022-09-20 14:16
Dupe of #27055

**Closed by rvandermeulen** 2022-09-20 14:16 UTC
Labels: 🐞 bug, needs:triage
