### ISSUE TITLE
[Bug] Firefox and Android becoming unresponsive when opening www.vogelwarte.ch

### ISSUE THREAD

**Issue by dafadllyn** [mozilla-mobile/fenix#17988] opened 2021-02-13 18:03 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

* Open the Firefox app.
* Type www.vogelwarte.ch in the address bar. (It's the website of the Swiss Ornithological Institute.)
* Hit the go button on the keyboard (right pointing arrow).

### Expected behavior

* The website displays.

### Actual behavior

* After the website has loaded about 80%, Firefox and the Android smartphone become unresponsive. (The device needs to be force shut down.)

### Device information

* Device vendor / model and Android version: Nokia 6.1 / Android 10
* Firefox for Android version: 85.1.3 (Build 2015792283)

**Comment by Oxygemo** [comment] 2021-02-14 01:00
Can reproduce! Notifications got cleared, app crashed.

Firefox 85.1.3

**Comment by sheikh-azharuddin** [comment] 2021-02-14 05:51
Working fine now

**Comment by drohdekage** [comment] 2021-02-14 20:35
Under 85.1.3 reproducable, app is crashing.

**Comment by test491** [comment] 2021-02-24 04:31
works fine

on 86.1.1
normal and private browsing modes
(android 9, Galaxy J7 Nxt)
https everywhere (also enabled: Encrypt All Sites Eligible is ON) addon and 

etp settings:
strict
custom: cookies: all cookies, cryptominers, fingerprinters, redirect trackers, tracking contents: all tabs (checked)

on Nightly 210220 05:00 (Build #2015794345) AC: 73.0.20210218143118, 525591d8b GV: 87.0a1-20210218092411 AS: 70.0.0

however, it shows pop up "Informationen Corona-Virus" with both above etp settings in normal and private browsing mode

**Comment by sflorean** [comment] 2021-05-25 14:33
Tested on latest Release build 88.1.4 and Nightly 5/25 and couldn't reproduce the issue. 
Devices: Xiaomi Redmi Note 8T (Android 9) and Pixel 3 (Android 11).

@dafadllyn this is still reproducible for you?

**Comment by dafadllyn** [comment] 2021-05-25 18:41
@sflorean:
> @dafadllyn this is still reproducible for you?

Yes, still the same problem with Firefox 88.1.4 on my Nokia 6.1 with Android 10.

**Comment by SoftVision-LorandJanos** [comment] 2021-11-22 10:32
I tested the page on the following release builds: 81, 85, 87, 88, 90 with the following result:
- On older builds, including 85.1.3 the page works as expected.
- On 87 and newer, the page is loading to about 80%, as mentioned, but it finishes loading after a long wait (up to 30 seconds).
- Accessed links from the page have the same behavior, with the last 20% taking long time to load.

Also tested on the latest builds:
- latest Nightly 96.0a1 (2021-11-22).
- latest Beta (95.0.0 beta4).
- latest Release 94.1.2.

The behavior is similar here as well.
There was no crash on any tested builds.
Tested on Chrome as well where the page works as expected.
Device used: Xiaomi Mi11 Lite (Android 11).
Since the page doesn't crash the app, only loads slowly, I will close this ticket.
@dafadllyn if you encounter the same issue, the bug can be reopened, in which case, please provide with the crashlog and a video of the issue. Thank you!

**Closed by SoftVision-LorandJanos** 2021-11-22 10:32 UTC
Labels: 🐞 bug, b:crash, wontfix, qa-triaged

**Comment by dafadllyn** [comment] 2021-11-22 18:03
@SoftVision-LorandJanos: Unfortunately, the Firefox app (currently in version 94.1.2) still can't fully load https://www.vogelwarte.ch/. It never loads more than this:

![Screenshot_20211122-182452](https://user-images.githubusercontent.com/79018751/142908665-0c291f6b-8a0a-4a1e-81f0-8cdc2c70e561.png)

Often, the Firefox app and the smartphone become unresponsive. (This is always the case while doing a screen record). If it doesn't become unresponsive, it reloads the page after about 1.5 minutes.

Where can i find the log files?
