### ISSUE TITLE
FNX-5289 ⁃ [Bug] Fenix crashes when clicking 'Rate on Google Play'

### ISSUE THREAD

**Issue by iadeelzafar** [mozilla-mobile/fenix#1859] opened 2019-04-20 17:53 UTC
## Steps to reproduce
1- Go to settings
2- Rate on Google Play

### Expected behavior
Should not crash and take to the Google Play page of Fenix to rate it.

### Actual behavior
Fenix crashes.

### Device information
Galaxy Nexus API 24

### GIF:
![](https://user-images.githubusercontent.com/36811908/56460631-0bd62e00-63bf-11e9-9507-61d19b03b198.gif)

**Comment by mauryat** [comment] 2019-04-22 06:00
This is likely because there's no play store on the device you tried this on. Good to handle the error. @boek can I work on this?

**Comment by LittleAngelwings** [comment] 2019-04-22 07:49
For me Fenix don't crashes, but there is no Fenix at Play Store yet. So a info site appears that Fenix couldn't be found.

**Comment by mauryat** [comment] 2019-04-22 08:02
@LittleAngelwings, that's normal. Fenix is not released to play store yet.
Eventually, when it's released, things should look alright.

**Comment by iadeelzafar** [comment] 2019-04-22 09:16
@LittleAngelwings same message should appear here and if play store is not available on the device then we should at least push a toast message.

**Comment by LittleAngelwings** [comment] 2019-04-22 10:06
I know that Fenix isn't available on play store ;) I only explained the opener the actual expected behavior :)

**Comment by vesta0** [comment] 2019-04-30 16:51
This will be fixed once Fenix is in a general availability track.

**Closed** 2020-08-11 13:10 UTC
Labels: b:crash, 🐞 bug
