### ISSUE TITLE
[Bug]: Dark mode theme isn't very dark

### ISSUE THREAD

**Issue by tobz1000** [mozilla-mobile/fenix#24240] opened 2022-03-12 17:57 UTC
### Steps to reproduce

1. Enable dark theme
2. View any part of the UI
3. The "dark" colors are a fairly light grey

e.g:
![image](https://user-images.githubusercontent.com/1471978/158029144-e3d3c912-28b3-4012-b01b-06583f7a3b86.png)

### Expected behaviour

The UI used to be much darker and more suitable for dark environments. I *think* this coincides with v98, but I don't have screenshots of earlier versions to be sure when this change was introduced.

### Actual behaviour

Colors are lighter than expected.

### Device name

Google Pixel 4a

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

98.1.1

**Comment by PandoraHayami** [comment] 2022-03-13 17:47
If I remember correctly, this was to match the proton color scheme from desktop Firefox.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-03-25 23:18
For AMOLED screens, this is not useful. Consequently, I would significantly prefer solely #000000 and #ffffff to constitute the interface.

**Comment by notDevagya** [comment] 2022-04-07 06:25
+1, I don't like the colors aswell, it should have an option to make it pitch black or maybe just use background / accent colors from the OS or let the user pick his own colors, possibily related to #1938

**Comment by amocirean** [comment] 2022-04-28 09:50
Hello @tobz1000 and thank you for submitting the issue.
As far as I can see, this is more a feature request than a bug. Also, as the previous comment said, this is related to #1938, where this feature you're asking for should be implemented.

Based on the following situation, I will close this ticket.

**Closed** 2022-04-28 09:51 UTC
Labels: 🐞 bug, Feature:Themes, needs:triage, S4, qa-triaged

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-05-01 11:15
@SoftVision-LorandJanos, why not merely modify the title rather than close this issue?

**Comment by SoftVision-LorandJanos** [comment] 2022-05-25 09:27
@BEEDELLROKEJULIANLOCKHART, I agree with @amocirean, the issue described here should be fixed/implemented by resolving the mentioned ticket.
Also as there are no specs according to which this is not functioning (looks like) as should, it wouldn't be considered a bug, and as a feature request, as mentioned, should be done along with #1938, otherwise this should be closed anyway as a duplicate of that.
