### ISSUE TITLE
~200ms until GeckoRuntime.create is called during COLD start up

### ISSUE THREAD

**Issue by mstange** [mozilla-mobile/fenix#9261] opened 2020-03-19 21:38 UTC
Startup profile: https://perfht.ml/2WsFa0Z

In the profile, it took around 417ms until `GeckoRuntime.create` was called. The profile is from a debuggable build, so it's exaggerating the problem a little bit, but it shows a number of things getting initialized earlier.

The earlier `GeckoRuntime.create` is called, the earlier Gecko can kick off network requests. This improves the app link startup experience.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16334)

**Comment by mcomella** [comment] 2020-03-19 23:14
top of the head notes:
- We need to validate in non-debuggable builds but in debuggable builds there appears to be a long time spent in dex: https://github.com/mozilla-mobile/fenix/issues/8979
- Glean init was moved to execute extremely early for the data migration. The glean team says glean should be initialized as early as possible but unclear if this is best for performance
- We're currently starting the async megazord before gecko but we can move that later

**Comment by mcomella** [comment] 2021-02-25 23:35
Action item: we can identify how long it takes to get to `GeckoRuntime.create` through duration timestamps (rather than trying to use profiles). Once we have this duration, we can better prioritize this issue.

**Comment by mcomella** [comment] 2021-03-02 00:31
> Action item: we can identify how long it takes to get to `GeckoRuntime.create` through duration timestamps (rather than trying to use profiles). Once we have this duration, we can better prioritize this issue.

On a moto G5, I measured from `FenixApplication.init` to the line before `GeckoRuntime.create` ([commit](https://github.com/mcomella/fenix/commit/9f34247ebafdb75cc375f70799a83f0dc940c792)):
> 15 runs, average: 199.86666666666667ms
[212, 197, 200, 204, 196, 209, 200, 194, 202, 193, 197, 196, 192, 200, 206]

This seems like a lot: I believe the only thing we _really_ need is crash reporting.

While this is a large amount, it's not the most critical measurement in performance.
- For VIEW, we want to make sure `loadUrl` is called as early as possible. If gecko is always started when that's called in the current implementation, then it probably doesn't matter if we start it earlier.
- For MAIN to home screen, we care more about overall time to first frame drawn – when Gecko is started doesn't matter (I think – maybe we block on something though).
- For MAIN to tab restoration, I'm not sure – maybe onCreate is the most important thing (it depends on who is telling Gecko to restore the tab)

Perhaps the real win here is **to investigate what that 200ms is and see if it can run _after_ our critical points** rather than trying to make `GeckoRuntime.create` happen earlier as the end goal:
- VIEW: loadUrl
- MAIN to homescreen: first frame drawn

**Comment by mcomella** [comment] 2021-03-02 18:57
There are a few ways we can investigate what happens in that 200ms:
- mstange suggested we could use `Debug.startMethodTracingSampling`
- MarcLeclair's hack to start the Gecko profiler earlier (while building a custom GV)
- simpleperf (I've had hits and misses with this. Seems fickle to get it working)

**Comment by mcomella** [comment] 2021-03-02 20:25
I took two profiles using `Debug.*` on my Moto G5, in a Nightly build with a few SDKs enabled and a few disabled (things I haven't figured out how to enable yet). The raw trace files (for AS) are here: [geckoRuntime-traces.zip](https://github.com/mozilla-mobile/fenix/files/6071507/geckoRuntime-traces.zip)

I used a WIP profiler PR https://github.com/firefox-devtools/profiler/pull/2458 (which mstange says should create accurate profiles but to let them know if you see bugs) to import them into the Firefox Profiler:
- 1ms sampling interval: https://share.firefox.dev/3uMHdfg – ~183ms overhead (383ms until GeckoRuntime.create)
- 5ms sampling interval: https://share.firefox.dev/306tVw8 – ~140ms overhead (340ms until GeckoRuntime.create)

**Comment by mcomella** [comment] 2021-03-02 20:29
Briefly glancing through the profiles, the main slowdowns (durations from 1ms profile) are:
- installing content providers (42%)
- getSettings (18%)
- initing native Glean stuff to execute PerfStartup.applicationOnCreate (13%)
- getCrashReporter (5%)

**Comment by acreskeyMoz** [comment] 2021-03-02 20:31
Very interesting.
The FireBase init, `com.google.firebase.provider.FirebaseInitProvider.attachInfo` called under `installing content providers (42%)` stood out to me as a good candidate to try disabling.

**Comment by mcomella** [comment] 2021-03-02 23:31
I tried to remove `FirebaseInitProvider` but it still took about 200ms to start. In the original profile, FirebaseInitProvider got stuck on `androidx.core.app.AppOpsManagerCompat.checkNotNull1`. In the new profile, `mozilla.components.lib.crash.service.MozillaSocorroService.<init>` gets stuck on the same class: `androidx.core.app.AppOpsManagerCompat.getLongVersionCode`. https://share.firefox.dev/2Oeeb7q

The `AppOps...` class doesn't appear to have that method so either:
- the profile is being imported incorrectly
- ProGuard is doing some optimization that's changing the call stack (it sometimes inlines things)

That being said, when I took a profile in the debug build variant, I no longer saw that class. It's possible:
- it's not included because some SDKs are disabled in debug
- proguard is making a poor optimization
- it gets initialized in a different place (debuggable=true causing race conditions?)

**Comment by mstange** [comment] 2021-03-02 23:34
It sounds like there's some lazy initialization work happening. It could be happening in C++ code that won't show up in the Java stacks. Pairing the Java profile with a simpleperf profile might provide insights.

**Comment by mcomella** [comment] 2021-03-02 23:50
> the profile is being imported incorrectly

Probably not this: it appears in the Android Studio profile.

> ProGuard is doing some optimization that's changing the call stack (it sometimes inlines things)

I no longer see it in profiles with `minifyEnabled false` and `shrinkResources false`: https://share.firefox.dev/3qagt4W (though I didn't measure absolute timing). I wonder:
- is R8 full mode causing this problems?
- Should we update our version of R8?
- Do we have an optimization enabled that doesn't perform well?

Another approach could be to remove MozillaSocorroService and see if we still see the issue.

**Comment by mcomella** [comment] 2021-03-03 00:24
> is the experimental R8 full mode causing this problems?

I still see it with r8 full mode disabled.

> Should we update our version of R8?

I still see it with a newer R8 (2.1.75)

I also tried:
* removed the `proguard-android-optimize-3.5.0-modified.txt` file from the proguard config and still see it.
* turn off `shrinkResources` but not `minifyEnabled` and still see it (you can't do it the other way around)

I think we'll have to take mstange's suggestion and check with simpleperf to really see what's going on here.

**Comment by mcomella** [comment] 2021-03-03 00:55
I noticed that:
- on master, `getCrashReporter` takes 11ms
- after we remove FirebaseProvider init, `getCrashReporter` takes 81ms (due to 67 ms `androidx.core.app.AppOpsManagerCompat.getLongVersionCode`)
- with `minifyEnabled false`, where that method goes away, `getCrashReporter` **still takes a long time**: 66ms. However, the profile indicates that not many methods are called from the bottom-most crash reporter node:

![image](https://user-images.githubusercontent.com/759372/109735301-645be200-7b77-11eb-8b4d-a541d6cbe799.png)

That's very suspicious. Some type of lazy native thing seems plausible. If we remove `Analytics.getCrashReporter`, I wonder if something else will grow in duration.

**Comment by mcomella** [comment] 2021-03-03 01:54
I replaced the `CrashReporter` implementation with null and now I get another interesting profile: https://share.firefox.dev/3sHSw6z

`androidx.core.app.AppOpsManagerCompat.settings` takes 95ms and is called directly from `onCreate`. It then calls our code `org.mozilla.fenix.components.Components.getSettings` which is weird because we're not calling it.

Perhaps it's time to try simpleperf.

**Comment by mcomella** [comment] 2021-03-08 19:17
At MarcLeclair's suggestion I dumped the stack in Settings but it doesn't tell me much: I see the AppOpsManagerCompat call but no additional info:
```
03-08 10:42:19.884 10236 10236 W System.err: java.lang.Exception: Stack trace
03-08 10:42:19.884 10236 10236 W System.err:    at java.lang.Thread.dumpStack(Thread.java:1348)
03-08 10:42:19.884 10236 10236 W System.err:    at org.mozilla.fenix.utils.Settings.<init>(Settings.kt:2)
03-08 10:42:19.884 10236 10236 W System.err:    at org.mozilla.fenix.components.Components$settings$2.invoke(Components.kt:1)
03-08 10:42:19.884 10236 10236 W System.err:    at org.mozilla.fenix.perf.LazyMonitored$lazyValue$1.invoke(LazyMonitored.kt:2)
03-08 10:42:19.884 10236 10236 W System.err:    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
03-08 10:42:19.884 10236 10236 W System.err:    at org.mozilla.fenix.perf.LazyMonitored.getValue(LazyMonitored.kt:1)
03-08 10:42:19.884 10236 10236 W System.err:    at org.mozilla.fenix.components.Components.getSettings(Unknown Source:2)
03-08 10:42:19.884 10236 10236 W System.err:    at androidx.core.app.AppOpsManagerCompat.settings(AppOpsManagerCompat.java:1)
03-08 10:42:19.884 10236 10236 W System.err:    at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:7)
03-08 10:42:19.885 10236 10236 W System.err:    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1141)
03-08 10:42:19.885 10236 10236 W System.err:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5854)
03-08 10:42:19.885 10236 10236 W System.err:    at android.app.ActivityThread.-wrap1(Unknown Source:0)
03-08 10:42:19.885 10236 10236 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1697)
03-08 10:42:19.885 10236 10236 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
```

**Comment by mcomella** [comment] 2021-05-03 18:05
Last I touched this, my status is that I wanted to move `GeckoRuntime.create` as early as possible to see if it even made a difference in time to nav start (mach perftest VIEW) - this may be blocked on https://github.com/mozilla-mobile/fenix/issues/17645. However, running it on perftest, the perf _got worse_ after moving it early, implying there is too much noise in perftest to figure out if it's an improvement. I began to do an analysis on the amount of noise in perftest. If that turns into too much of a rabbit hole, we could try creating an alternative to perftest with less noise (e.g. read time of process start to `PageStart` log, which might be similar).

Assuming this change improves the perf, there were two things to do:
- Optimize our code to move `GeckoRuntime.create` earlier
- Figure out cause of `AppOpsManageCompat` (with a simpleperf profile? see if something native is happening?) and address that

**Comment by mcomella** [comment] 2021-05-14 00:09
#17645 is complete and seems like it won't help: here's the new status.

First off, we want to make sure moving `GeckoRuntime.create` earlier actually improves our key metrics (e.g. processToNavStart). We can either:
- Figure out the noise in perftest and whether or not we can measure the changes
- Write a new test without browsertime to measure the changes

Assuming moving it earlier helps, we can then make improvements:
- Improve our code. In particular, Glean & settings take a while
- Identify the root cause of `AppOpsManagerCompat` injection by r8: see the earlier comments for details on what we know about that

**Comment by mcomella** [comment] 2021-06-03 21:02
Broke down into other issues:
- https://github.com/mozilla-mobile/fenix/issues/19804
- https://github.com/mozilla-mobile/fenix/issues/19805

**Comment by mcomella** [comment] 2021-07-12 20:22
@MarcLeclair Please explain what approaches we have available to this bug before moving it to Low Impact. Thanks!

**Comment by MarcLeclair** [comment] 2021-07-12 21:09
After finding out that GV starting earlier would improve our start up time, some of the possible solutions we have found were the following:

1) #20078. Using Content Provider was an idea we've had to try to initialize GV faster

2) Perf metrics glean native takes approx 20ms

3) Async Load Tab View

4) AppOpsManager that seems to be introduced by firebase before GV (To be clear, this seems to always be called somewhere in the start up timeline, but we could maybe try to push it after GV has been initialized)

**Comment by cpeterso** [comment] 2022-12-23 20:54
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807361

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by cpeterso** 2022-12-23 20:54 UTC
Labels: 🐞 bug, performance, pin, perf:startup
