### ISSUE TITLE
[Bug] Private browsing toggle button behavior

### ISSUE THREAD

**Issue by neha-b2001** [mozilla-mobile/fenix#19862] opened 2021-06-06 18:27 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open the app homepage. 
2. On the top right corner lies the **private browsing toggle button**. Click on it to enable the private browsing mode. 
3. Observe the button. 

### Screenshot
![image](https://user-images.githubusercontent.com/67039214/120935677-7ffbf900-c721-11eb-9792-c4f86ce5e581.png)

### Doubts regarding button behavior
1. The private browsing mode icon has an eye-mask-like symbol (`private_browsing_button.xml`) surrounded by a white circle. The two elements almost merge into each other i.e. there **isn't much contrast between them**. Is this intentional? Or should the contrast between the symbol and surrounding circle be adjusted so that `private_browsing_button.xml` is more clearly visible? 

2. Wherever you click this private browsing toggle button near its circumference, there’s a small faint white circle indicating where you touched the button (visible below when I touch the toggle button). Should this be visible? 

https://user-images.githubusercontent.com/67039214/120935845-5099bc00-c722-11eb-9823-90a6d35cf4ea.mp4

### Device information

* Device vendor / model and Android version: Redmi Note 8 Pro (Android 10)
* Firefox for Android version: Firefox Nightly Build #2015814603 (Saturday 6/5)

**Comment by SoftVision-LorandJanos** [comment] 2021-06-30 12:54
Hi @neha-b2001 ! Thank you for the report! Starting with your second point, as far as I know it's an intentional behavior, I noticed it on Download button and Install button as well. I couldn't however reproduce the Private browsing icon issue, The contrast is clear, the mask is dark in white theme and white only on dark theme with normal browsing. I've tested both on the Nightly version you logged the issue with (6/5) and on the latest one (91.0a1 2021-06-30T05:09:53.235). Also I checked on the following devices: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0) and the icon seems with clear contrast on all of them.
Could you check on a different device than the one you tested with? And maybe see if it still reproduces on the latest build with the same device? Thank you!

**Comment by SoftVision-LorandJanos** [comment] 2021-12-28 07:31
As this issue is partially intended, partially not reproducible, I will close this ticket.
Retested with a Xiaomi Mi11 Lite (Android 11).
Using the latest Nightly build (2021-12-28).

**Closed by SoftVision-LorandJanos** 2021-12-28 07:31 UTC
Labels: 🐞 bug, Feature:PrivateBrowsing, Feature:HomeScreen, wontfix, qa-triaged
