### ISSUE TITLE
[Bug] Enabling accessibility feature (example talkback) causes app to crash on loading tabs tray

### ISSUE THREAD

**Issue by abhijitvalluri** [mozilla-mobile/fenix#14540] opened 2020-08-31 17:09 UTC
## Steps to reproduce
1. Enable TalkBack accessibility feature in Android settings.
1. Open firefox app.
1. Open the tabs tray by clicking on the tab count on the URL bar
1. App crashes!

### Expected behavior

I expect the app to not crash when accessibility features are enabled and you use the tabs tray in the app.

### Actual behavior

The app crashes when the tabs tray is opened with the accessibilty feature, such as TalkBack, enabled.
It appears that the culprit for this crash is this chunk of code: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt#L188

```
if (hasAccessibilityEnabled) {
    tabsAdapter.notifyDataSetChanged()
}
```

Somehow when `notifyDataSetChanged()` is called, I get an IndexOutOfBounds exception. When I remove that code, there is no crash. I am not sure what accessibility feature notify data set changed method call provides. 

The following is the error:
```
2020-08-31 17:50:34.173 28972-28972/network.novak.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: network.novak.fenix.debug, PID: 28972
    java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
        at java.util.ArrayList.get(ArrayList.java:437)
        at mozilla.components.browser.tabstray.TabsAdapter.onBindViewHolder(TabsAdapter.kt:52)
        at org.mozilla.fenix.tabtray.FenixTabsAdapter.onBindViewHolder(FenixTabsAdapter.kt:67)
        at org.mozilla.fenix.tabtray.FenixTabsAdapter.onBindViewHolder(FenixTabsAdapter.kt:59)
        at org.mozilla.fenix.tabtray.FenixTabsAdapter.onBindViewHolder(FenixTabsAdapter.kt:22)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7308)
... (truncated)
```

### Device information

* Android device: Android 10, Pixel 2
* Fenix version: Issue still exists on latest Firefox production and latest Firefox Nightly (Nightly 200831 06:01 (Build #2015761139)) and also on latest master (commit https://github.com/mozilla-mobile/fenix/commit/4a00131fa15bdf8d1144e25642a318377b2fa797)

**Comment by liuche** [comment] 2020-08-31 17:33
Could you take a look at this @mcarare? I'm wondering if this is some fallout from the a11y changes we were making - I was also seeing these show up in the Google Play pre-launch report https://sentry.prod.mozaws.net/operations/fenix-fennec/?query=is%3Aunresolved+sealed

**Comment by abhijitvalluri** [comment] 2020-08-31 21:41
As per this webpage on Android Developers Documentation: https://developer.android.com/reference/androidx/recyclerview/widget/ConcatAdapter

> When an added adapter calls one of the notify methods, ConcatAdapter properly offsets values before reporting it back to the RecyclerView. If an adapter calls RecyclerView.Adapter.notifyDataSetChanged(), ConcatAdapter also calls RecyclerView.Adapter.notifyDataSetChanged() as calling RecyclerView.Adapter.notifyItemRangeChanged(int, int) will confuse the RecyclerView. You are highly encouraged to to use SortedList or ListAdapter to avoid calling RecyclerView.Adapter.notifyDataSetChanged(). 

So, it looks like calling `notifyDataSetChanged` is not a good idea with `ConcatAdapter` perhaps. For some reason doing this is causing a call in `FenixTabAdapter`'s `onBindViewHolder` with a position value that is more than the number of tabs. What I am noticing is that it is calling this method with a position value that is upto 2 times the number of tabs available. So, if I have 3 tabs open, then this method is called with `position` = 0 to 5, and if I have 2 tabs open, `position` is 0 to 3 and so on. Hope that helps.

**Comment by mcarare** [comment] 2020-09-01 07:21
I will take a look at this. It was working just fine , but there were a great deal of changes in Tab Tray since I have implemented this. Including adding the `ConcatAdapter`.

**Comment by Diana-Rus** [comment] 2020-09-01 14:34
Hi, I can reproduce the issue on Nightly 9/1 with:
- Google Pixel 3XL (Android 9)
Crash link - with only one tab opened: https://crash-stats.mozilla.org/report/index/bp-574f4226-ea0e-4a90-8be3-d0aba0200901
- Samsung Galaxy S9 (Android 8)
Crash link - with only one tab opened: https://crash-stats.mozilla.org/report/index/54eff846-45a2-4ea3-9014-420020200901

Note:
- Didn't encounter the issue when there was no tab in tabs tray
- I've encounter the issue by having at least one tab opened in tabs tray and than following the STR.
- It can be encountered as well when you follow the STR, with an extra step, after step2 you add a tab and then continue with step 3:
STR
1. Enable TalkBack accessibility feature in Android settings.
2. Open firefox app.
3. Make a search after a site.
4. Open the tabs tray by clicking on the tab count on the URL bar
Actual Result:  App crashes!

<details closed><summary>Check GIF</summary>

![20200901-172345-2](https://user-images.githubusercontent.com/49859863/91864630-1a05b100-ec79-11ea-91dd-b28b554a5bbf.gif)
</details>

**Removing QA-needed until issue is fixed.**

**Comment by sflorean** [comment] 2020-09-10 12:37
Verified as fixed on Nightly 9/10 with the following devices:
- Samsung Galaxy Note 10 (Android 10)
- Google Pixel 3 (Android 11)

Note: I was able to reproduce the crash on Beta and Release.

**Closed by sflorean** 2020-09-10 12:37 UTC
Labels: E3, b:a11y, b:crash, eng:qa:needed, 🐞 bug
