### ISSUE TITLE
[Bug] In full screen, when I rotate the screen the statusbar doesn't hide again 

### ISSUE THREAD

**Issue by joelocandol** [mozilla-mobile/fenix#9166] opened 2020-03-15 22:36 UTC
## Step to reproduce it 
Enter in full screen video and the rotate the screen to landscape mode or viceversa 

### Expected behavior
Hide the statusbar again (inmersive mode) 

### Actual behavior
The statusbar still, at least I quit the full screen mode and enter in it again 

### Device information
Oukitel c5
* Android device: 7.0
* Fenix version: nightly 200315

**Comment by sv-sdeiac** [comment] 2020-03-17 10:17
Hi @joelocandol, I was not able to reproduce your problem using the latest version of Firefox Preview Nightly 3/17 #20770605. The video pages I was tried are youtube, CNN, twitch, twitter.

Devices:
- LG g7 fit (Android 8);
- Samsung Galaxy Tab S6 (Android 9);
- Google Pixel 3 (Android Q).

Can you provide some pages where you encounter the issue?
I'll wait for your updates, thanks.

**Comment by joelocandol** [comment] 2020-03-19 18:12
It's not a problem of a specific website, all encounter it on every video in full screen

**Comment by sflorean** [comment] 2020-11-06 13:42
@joelocandol Thanks for report!
 Now, most of the videos are forced to be displayed in landscape mode and will close this bug based on the changed behavior. If you find videos where the issue is still reproducible, please leave a comment and we will investigate.

**Closed by sflorean** 2020-11-06 13:42 UTC
Labels: needs:triage, 🐞 bug
