### ISSUE TITLE
Paste, Paste and go for home search bar

### ISSUE THREAD

**Issue by kawaiiDango** [mozilla-mobile/fenix#9758] opened 2020-04-07 06:38 UTC
### Why/User Benefit/User Problem
Paste, paste and go already exists for long press on the url bar when a tab is open.
![Screenshot_20200407115921](https://user-images.githubusercontent.com/1066519/78637156-5a632d80-7899-11ea-9f2d-e7d2fa1c019e.jpg)
This however, doesn't exist for the search bar on home. Adding this would make Firefox quite convinient.
### Acceptance Criteria (how do I know when I’m done?)
(already described)

**Comment by mcarare** [comment] 2020-04-07 06:45
Duplicate of https://github.com/mozilla-mobile/fenix/issues/6846.

**Closed by mcarare** 2020-04-07 06:45 UTC
Labels: needs:triage, 🌟 feature request
