### ISSUE TITLE
[webcontent] white gap appears above navbar on many bootstrap-powered sites

### ISSUE THREAD

**Issue by kasperireland** [mozilla-mobile/fenix#22380] opened 2021-11-09 03:54 UTC
## Site with issue and any steps to reproduce
Simply navigate to getbootstrap.com or swivro.net on Firefox Mobile with Dark Theme enabled, and you can see a white gap above the navbar, if you scroll down and then back up.

### Expected behavior
There should be no white space/gap above the navbar (this appears to only apply to pure bootstrap sites such as the ones I have listed above).

### Actual behavior
A small white gap/space appears above the navbar of the website if you scroll down the page and back up. This only occurs on Firefox Mobile (I am using Android) with Dark theme enabled.

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No.

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No. This only applies to Firefox Mobile with Dark Theme enabled.

### Device information

* Android device: 11

**Comment by kbrosnan** [comment] 2021-11-09 22:27
sounds like a duplicate of bz-1734261

**Closed by kbrosnan** 2021-11-09 22:27 UTC
Labels: needs:triage
