### ISSUE TITLE
FNX-12836 ⁃ Feature which allow Firefox Preview to trust custom self-signed certificates.

### ISSUE THREAD

**Issue by UtkarshMish** [mozilla-mobile/fenix#11849] opened 2020-06-23 16:51 UTC
### What is the user problem or growth opportunity you want to see solved?
Firefox utilizes it's Own Root Certificate Store and thus the new **Firefox Preview doesn't allow external certificates** to be installed .

### How do you know that this problem exists today? Why is this important?
It allows users to work with  custom self-signed certificates and let applications like Adguard (which utilizes their own self-signed Certificates),etc to work without an issue .

### Who will benefit from it?
All of the users who use the application daily who want to check their self-signed certificates, and let applications like Adguard to work flawlessly.

**Comment by ekager** [comment] 2020-06-23 16:53
Is this a dupe of https://github.com/mozilla-mobile/fenix/issues/3728 ?

**Comment by sheikh-azharuddin** [comment] 2020-06-23 16:57
There is one preference item through which firefox trust installed certificate .

security.enterprise_roots.enabled

In desktop version with this preference set to true it trust windows certificate store similar to chrome or any other browser. In mobile version too I believe enabling this setting will allow to trust the certificate installed in the system. Please try.

**Comment by UtkarshMish** [comment] 2020-06-23 17:04
@ekager , something similar to that, It's like the old Firefox Mobile type where user can install custom certificates in firefox itself unlike using all the certificates in android device .

**Closed** 2020-08-11 05:04 UTC
Labels: needs:triage
