### ISSUE TITLE
copy link text

### ISSUE THREAD

**Issue by 772602825** [mozilla-mobile/fenix#25597] opened 2022-06-12 13:10 UTC
the link text can not been copied.
This feature is very useful and important.Many people have suggested ,why this feature is not haved.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20692)

**Comment by kbrosnan** [comment] 2022-06-12 20:48
Duplicate of https://github.com/mozilla-mobile/fenix/issues/16582

**Closed** 2022-06-13 18:03 UTC
Labels: needs:triage
