### ISSUE TITLE
FNX-12824 ⁃ [Bug]Tapping the Desktop Bookmarks folder crashes Fenix : java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11838] opened 2020-06-23 07:19 UTC
## Prerequsites
The user should be signed in to sync

## Steps to reproduce
1. Open the Bookmarks section
1. Tap the X (close) button
1. Open again the Bookmarks section
1. Tap and open the "Desktop Bookamrks"

### Expected behavior
Properly opens the Desktop Bookmarks folder

### Actual behavior
Crash

### Device information
* Android device: Google Pixel 3a (Android 10)
* Fenix version: Nightly Build 200623 from 6/23

### Notes
Noticed while checking #10462 

:x: Didn't manage to reproduce it on these devices:
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

❗ No Soccoro link

►Crash log
7d91a8c4-f4f6-449c-9098-0419e2fea666

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

```kotlin
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
at android.view.ViewGroup.addViewInner(ViewGroup.java:5150)
at android.view.ViewGroup.addView(ViewGroup.java:4979)
at android.view.ViewGroup.addView(ViewGroup.java:4951)
at androidx.appcompat.widget.Toolbar.addSystemView(Toolbar.java:10)
at androidx.appcompat.widget.Toolbar.setTitle(Toolbar.java:13)
at androidx.appcompat.widget.ToolbarWidgetWrapper.setWindowTitle(ToolbarWidgetWrapper.java:4)
at androidx.appcompat.app.ToolbarActionBar.setWindowTitle(ToolbarActionBar.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl.setTitle(AppCompatDelegateImpl.java:5)
at androidx.appcompat.app.AppCompatActivity.onTitleChanged(AppCompatActivity.java:2)
at android.app.Activity.setTitle(Activity.java:6676)
at org.mozilla.fenix.library.LibraryPageView.updateToolbar(LibraryPageView.kt:1)
at org.mozilla.fenix.library.LibraryPageView.setUiForNormalMode(LibraryPageView.kt:7)
at org.mozilla.fenix.library.bookmarks.BookmarkView.update(BookmarkView.kt:19)
at org.mozilla.fenix.library.bookmarks.BookmarkFragment$onViewCreated$1.invoke(BookmarkFragment.kt:3)
at mozilla.components.lib.state.ext.FragmentKt$consumeFrom$1.invokeSuspend(Fragment.kt:8)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

► Video
![20200623-101229](https://user-images.githubusercontent.com/51314259/85372710-e866c000-b53a-11ea-8dab-83407109275c.gif)

**Comment by Dan884** [comment] 2020-06-25 04:07
I had a similar problem. See #11874.
I cleared the Storage data, uninstalled the app, reinstalled it and setup all the settings, bookmarks, Add-ons, etc the same as before. For now the problem is fixed. It only crashed once and I have been using it heavily for days.

**Comment by ekager** [comment] 2020-06-25 18:27
Closing for #11892

**Closed** 2020-08-11 05:04 UTC
Labels: Feature:Bookmarks, S1, b:crash, needs:triage, 🐞 bug
