### ISSUE TITLE
[Bug] doesn't start on Samsung Galaxy S4 Mini (gt-i9195 / serranoltexx - LineageOS-15.1 / Android-8.1)

### ISSUE THREAD

**Issue by kolAflash** [mozilla-mobile/fenix#3680] opened 2019-06-26 12:04 UTC
## Steps to reproduce
This is my exact LineageOS version: https://www.mediafire.com/file/f63hte5fqoh3bjb/lineage-15.1-20190413-UNOFFICIAL-serranoltexx.zip/
https://forum.xda-developers.com/galaxy-s4-mini/orig-development/rom-lineageos-15-0-s4-mini-t3702272
1. Install on a Samsung i9195, running LineageOS-15.1 / Android-8.1
2. Start app.

I tried the app on several other phones - also those running LineageOS-15.1 - and the app works fine.

### Expected behavior
App starts.

### Actual behavior
Screen is black (except Android bar at the top).
[i9195_los-15.1_start-crash.log](https://github.com/mozilla-mobile/fenix/files/3329891/i9195_los-15.1_start-crash.log)

### Device information
* Android device: Samsung Galaxy S4 Mini" (a.k.a gt-i9195 / serranoltexx)
* Fenix version: https://github.com/mozilla-mobile/fenix/releases/download/v1.0.0/firefox_preview-1.0.0.arm.apk (I tried this APK and I tried installing via PlayStore - same result)

**Comment by kbrosnan** [comment] 2019-06-27 22:17
```
06-26 13:40:55.059  4217  4271 W GeckoLinker: /data/app/org.mozilla.fenix-RsRvr7C6NiQvA7rmJiHJUw==/lib/arm/libxul.so: unhandled flags #8 not handled
06-26 13:40:55.059  4217  4271 W GeckoLinker: /data/app/org.mozilla.fenix-RsRvr7C6NiQvA7rmJiHJUw==/lib/arm/liblgpllibs.so: unhandled flags #8 not handled
06-26 13:40:55.067  4217  4217 E KeyFrames: unable to load
06-26 13:40:55.067  4217  4217 E KeyFrames: java.lang.NoSuchMethodException: <init> []
06-26 13:40:55.067  4217  4217 E KeyFrames:     at java.lang.Class.getConstructor0(Class.java:2320)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at java.lang.Class.getConstructor(Class.java:1725)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.constraintlayout.motion.widget.KeyFrames.<clinit>(KeyFrames.java:2)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.constraintlayout.motion.widget.MotionScene.<init>(MotionScene.java:18)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.constraintlayout.motion.widget.MotionLayout.init(MotionLayout.java:6)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.constraintlayout.motion.widget.MotionLayout.<init>(MotionLayout.java:64)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at java.lang.reflect.Constructor.newInstance0(Native Method)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.view.LayoutInflater.createView(LayoutInflater.java:647)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:2)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:88)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:6)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:54)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:11)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:4)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:4)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:9)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:99)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:210)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:9)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.app.Activity.performStart(Activity.java:7029)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.os.Handler.dispatchMessage(Handler.java:106)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.os.Looper.loop(Looper.java:164)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at android.app.ActivityThread.main(ActivityThread.java:6494)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at java.lang.reflect.Method.invoke(Native Method)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
06-26 13:40:55.067  4217  4217 E KeyFrames:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by kbrosnan** [comment] 2019-06-27 22:22
Not seeing this crash on the Sentry or Play console.

**Comment by kolAflash** [comment] 2019-06-28 23:44
I don't know what Sentry or the Play console is.
Maybe you don't see the crash, because the app doesn't even start up correctly?

Please tell me if and how I can help reproducing or solving this.

**Comment by klausenbusk** [comment] 2019-07-04 18:46
Same/similar issue with [LineageOS 16/Android 9](https://forum.xda-developers.com/galaxy-s4-mini/orig-development/rom-lineageos-16-0-s4-mini-t3833063). The app is just stuck at a white screen.

Relevant logcat:
```
07-04 20:45:30.674  8476  8476 E KeyFrames: unable to load
07-04 20:45:30.674  8476  8476 E KeyFrames: java.lang.NoSuchMethodException: <init> []
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at java.lang.Class.getConstructor0(Class.java:2327)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at java.lang.Class.getConstructor(Class.java:1725)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.constraintlayout.motion.widget.KeyFrames.<clinit>(KeyFrames.java:2)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.constraintlayout.motion.widget.MotionScene.<init>(MotionScene.java:18)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.constraintlayout.motion.widget.MotionLayout.init(MotionLayout.java:6)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.constraintlayout.motion.widget.MotionLayout.<init>(MotionLayout.java:64)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:2)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:88)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:6)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:54)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:11)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:4)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:4)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:9)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:99)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:210)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:9)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.app.Activity.performStart(Activity.java:7165)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.os.Looper.loop(Looper.java:193)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at java.lang.reflect.Method.invoke(Native Method)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-04 20:45:30.674  8476  8476 E KeyFrames: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-04 20:45:30.704  8476  8522 W Settings: Setting animator_duration_scale has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only global URI.
```

**Comment by klausenbusk** [comment] 2019-07-04 19:02
Is this a duplicate of https://github.com/mozilla-mobile/fenix/issues/2945?, which was fixed in https://github.com/mozilla-mobile/fenix/pull/3854. I will test with [v1.0.1-rc.1](https://github.com/mozilla-mobile/fenix/releases/tag/v1.0.1-rc.1) when a apk is ready.

**Comment by klausenbusk** [comment] 2019-07-04 19:15
> Is this a duplicate of #2945?, which was fixed in #3854. I will test with [v1.0.1-rc.1](https://github.com/mozilla-mobile/fenix/releases/tag/v1.0.1-rc.1) when a apk is ready.

I just tried the [latest Nightly](https://queue.taskcluster.net/v1/task/F5caWFM-S4qGj7W9Awc13A/runs/0/artifacts/public/target.arm.apk) and the app starts now, so I assume it was fixed by #3854.

**Comment by sv-ohorvath** [comment] 2019-07-05 07:58
Thanks @klausenbusk  for verifying! I'll close this now.

**Closed by sv-ohorvath** 2019-07-05 07:58 UTC
Labels: 🐞 bug, 💥 crash

**Comment by kolAflash** [comment] 2019-07-06 08:06
Confirming, it's fixed.
