### ISSUE TITLE
Chrome like tab switcher?

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12853] opened 2020-07-23 14:14 UTC
I know a lot of research and work has gone into the current tabs tray, but I would like to know why they were not designed like chrome's tab switcher. Because chrome has most of the marketshare on android, and almost everybody likes its tabs switcher. It shows the tab title, it shows a preview of the page as well, it allows to close tabs by a cross icon as well as by swipe, it looks cool, it feels fast, and IMO, it is much better and easier to use than the current tabs tray on fenix (or the one on fennec). So was such a design considered for fenix, if yes, why was it not chosen, if no, why not?

(My main problem with the current tabs tray is that it is very annoying to use with one hand on a big phone)

**Comment by Dunexus** [comment] 2020-07-23 17:04
Could you tell more about what is hard to achieve with one hand ?

Feedback on tabtray is welcome, please provide as much detail as you can about use cases that are sub-optimal. It will allow UX team to dig the issue and improve the new tab tray.

**Comment by s-ankur** [comment] 2020-07-26 19:12
This is actually a duplicate of #3758

**Comment by kbrosnan** [comment] 2020-07-26 22:22
Closing as a dupe

**Closed** 2020-08-28 22:45 UTC
Labels: needs:triage
