### ISSUE TITLE
[Bug] Videos in landscape mode have a wrong positioning when you enable the top navbar

### ISSUE THREAD

**Issue by Knocks83** [mozilla-mobile/fenix#17332] opened 2021-01-06 11:58 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

I had opened this issue in webcompat using the in-app report button (webcompat/web-bugs#64941) but they told me to open it here.

## Steps to reproduce
- Enable the top navigation bar
- Try to reproduce a video in landscape mode

### Expected behavior
It should be in the correct position

### Actual behavior
It's like it's in "fit horizontally" mode, if you tap on the screen (at least on YouTube) the video gets the correct position.
Some websites, once the controls disappear, revert to the wrong video position

https://user-images.githubusercontent.com/22529815/103765893-35653c00-501e-11eb-89a5-3c297a15836e.mp4

In this video I also set the dark mode, but it doesn't really change anything.
(the video kinda sucks because I had to compress it)

### Device information

* Android device: Xiaomi Mi 10 - 1080 x 2340 pixels, 19.5:9 ratio (~386 ppi density) - MIUI 12.0.6
* Fenix version: I honestly have no idea, I'm using Firefox 85.0.0-beta.4

**Comment by ekager** [comment] 2021-01-06 18:48
I think this is a dupe of #8252 . Closing for that.

**Closed by ekager** 2021-01-06 18:49 UTC
Labels: needs:triage, 🐞 bug
