### ISSUE TITLE
FNX2-12997 ⁃ [Bug] Memory leak in BrowserAnimator

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#12101] opened 2020-06-29 19:17 UTC
┬───
│ GC Root: System class
│
├─ android.provider.FontsContract class
│    Leaking: NO (DebugFenixApplication↓ is not leaking and a class is never leaking)
│    ↓ static FontsContract.sContext
├─ org.mozilla.fenix.DebugFenixApplication instance
│    Leaking: NO (BrowserFragment↓ is not leaking and Application is a singleton)
│    DebugFenixApplication does not wrap an activity context
│    ↓ DebugFenixApplication.components$delegate
├─ kotlin.SynchronizedLazyImpl instance
│    Leaking: NO (BrowserFragment↓ is not leaking)
│    ↓ SynchronizedLazyImpl._value
├─ org.mozilla.fenix.components.Components instance
│    Leaking: NO (BrowserFragment↓ is not leaking)
│    ↓ Components.useCases$delegate
├─ kotlin.SynchronizedLazyImpl instance
│    Leaking: NO (BrowserFragment↓ is not leaking)
│    ↓ SynchronizedLazyImpl._value
├─ org.mozilla.fenix.components.UseCases instance
│    Leaking: NO (BrowserFragment↓ is not leaking)
│    ↓ UseCases.sessionManager
├─ mozilla.components.browser.session.SessionManager instance
│    Leaking: NO (BrowserFragment↓ is not leaking)
│    ↓ SessionManager.delegate
├─ mozilla.components.browser.session.LegacySessionManager instance
│    Leaking: NO (BrowserFragment↓ is not leaking)
│    ↓ LegacySessionManager.$$delegate_0
├─ mozilla.components.support.base.observer.ObserverRegistry instance
│    Leaking: NO (BrowserFragment↓ is not leaking)
│    ↓ ObserverRegistry.observers
├─ java.util.LinkedHashSet instance
│    Leaking: NO (BrowserFragment↓ is not leaking)
│    ↓ LinkedHashSet.map
├─ java.util.LinkedHashMap instance
│    Leaking: NO (BrowserFragment↓ is not leaking)
│    ↓ LinkedHashMap.tail
├─ java.util.LinkedHashMap$LinkedHashMapEntry instance
│    Leaking: NO (BrowserFragment↓ is not leaking)
│    ↓ LinkedHashMap$LinkedHashMapEntry.key
├─ org.mozilla.fenix.browser.BrowserFragment instance
│    Leaking: NO (Fragment#mFragmentManager is not null)
│    ↓ BrowserFragment.browserAnimator
│                      ~~~~~~~~~~~~~~~
├─ org.mozilla.fenix.browser.BrowserAnimator instance
│    Leaking: UNKNOWN
│    ↓ BrowserAnimator.viewLifecycleScope
│                      ~~~~~~~~~~~~~~~~~~
├─ androidx.lifecycle.LifecycleCoroutineScopeImpl instance
│    Leaking: UNKNOWN
│    ↓ LifecycleCoroutineScopeImpl.lifecycle
│                                  ~~~~~~~~~
├─ androidx.lifecycle.LifecycleRegistry instance
│    Leaking: UNKNOWN
│    ↓ LifecycleRegistry.mObserverMap
│                        ~~~~~~~~~~~~
├─ androidx.arch.core.internal.FastSafeIterableMap instance
│    Leaking: UNKNOWN
│    ↓ FastSafeIterableMap.mEnd
│                          ~~~~
├─ androidx.arch.core.internal.SafeIterableMap$Entry instance
│    Leaking: UNKNOWN
│    ↓ SafeIterableMap$Entry.mKey
│                            ~~~~
├─ org.mozilla.fenix.settings.OnSharedPreferenceChangeListener instance
│    Leaking: UNKNOWN
│    ↓ OnSharedPreferenceChangeListener.listener
│                                       ~~~~~~~~
├─ org.mozilla.fenix.utils.Settings$setSitePermissionSettingListener$1 instance
│    Leaking: UNKNOWN
│    Anonymous subclass of kotlin.jvm.internal.Lambda
│    ↓ Settings$setSitePermissionSettingListener$1.$listener
│                                                  ~~~~~~~~~
├─ org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$15 instance
│    Leaking: UNKNOWN
│    Anonymous subclass of kotlin.jvm.internal.Lambda
│    ↓ BaseBrowserFragment$initializeUI$$inlined$also$lambda$15.$view$inlined
│                                                               ~~~~~~~~~~~~~
╰→ androidx.coordinatorlayout.widget.CoordinatorLayout instance
​     Leaking: YES (ObjectWatcher was watching this because org.mozilla.fenix.browser.BrowserFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks))
​     key = 998bd3b1-0dc5-4dd4-a9d5-17e3dc97ee03
​     watchDurationMillis = 72293
​     retainedDurationMillis = 67293
​     mContext instance of org.mozilla.fenix.HomeActivity with mDestroyed = false
​     View#mParent is null
​     View#mAttachInfo is null (view detached)
​     View.mID = R.id.browserLayout
​     View.mWindowAttachCount = 1

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: Google
LeakCanary version: 2.3
App process name: org.mozilla.fenix.debug
Analysis duration: 47984 ms

- - -
Not entirely sure what I did to get this Leak Canary notification.

**Comment by ekager** [comment] 2020-07-20 17:50
Closing as dupe of #10784

**Closed** 2020-08-17 21:56 UTC
Labels: eng:performance, needs:triage, 🐞 bug
