### ISSUE TITLE
[Bug] It is too hard to save/move a selection of tabs into collections via tab tray

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10371] opened 2020-05-02 16:18 UTC
## Steps to reproduce
1. Open a page
1. Go to open tabs
1. tap and hold on a tab

### Expected behavior
UI appears that allows me to save tab into a collection, like what used to happen on home. 

### Actual behavior
Nothing happens. Unless I try to save a collection and hit back (not very discoverable), I am forced to save my entire open tab stack to a collection any time I want to add tabs to a collection. 

### Device information
* Android device: pixel 2
* Fenix version: latest nightly

**Comment by cadeyrn** [comment] 2020-05-02 17:28
Duplicate of #10163.

**Comment by yoasif** [comment] 2020-05-02 18:05
I don't think this is a dupe of that; you can already save individual tabs into collections, but the UI differs from the Library.

**Comment by cadeyrn** [comment] 2020-05-02 18:17
#10163 is about implementing the a multiselect behaviour that is consistent with the multiselect behaviour of the library. It's not possible to have both, #10163 and the long press behaviour of the old start screen. So it's clearly a duplicate of #10163 because #10163 will implement the long press behaviour which allows to add a single tab to a collection.

**Comment by yoasif** [comment] 2020-05-02 18:27
@cadeyrn You can still get the same multi-select in tab tray as previously appeared in home, just tap "Save to collection" and hit the back button. The styling  there is clearly different from the Library, and that is my understanding of #10163. 

My issue here is that it is simply far too undiscoverable to get to the point of selection, because Fenix *really* wants me to save all my tabs to a collection every time.

**Comment by cadeyrn** [comment] 2020-05-02 18:34
> You can still get the same multi-select in tab tray as previously appeared in home, just tap "Save to collection" and hit the back button. 

I know. But my comment was not about this behaviour at all…

Your issue is about the behaviour when long pressing a tab, I refer to **_your_** "steps to reproduce". And #10163 is about exactly the same: To get a consistent behaviour with the library the multiselect mode has to be enabled when long pressing a row. Long pressing a tab can only trigger one behaviour. And this is covered by #10163.

**Comment by yoasif** [comment] 2020-05-02 18:39
If it is a dupe, it is a dupe. I'll point out that #10163 says "update" the tab tray multiselect, which to me meant that we'd simply be updating the screen that appears when you tap "Save to collection" and hit the back button.

**Comment by vesta0** [comment] 2020-06-28 04:50
@yoasif for now you could still add a single tab to a collection by tapping on "save to collection" in the tab toolbar menu -  without having to save all your tabs to a collection every time.

![Screenshot_20200628-004338](https://user-images.githubusercontent.com/42752644/85938207-1c463a80-b8d9-11ea-8eca-4e2d4df5c7cc.png)

**Comment by ekager** [comment] 2020-07-30 16:09
Can we close this issue now that we can "tap and hold on a tab" in the tabs tray as part of multiselect and adding a single tab is available in the browsing menu?

**Comment by yoasif** [comment] 2020-07-30 16:13
@ekager happy to close. I honestly hadn't tried the new feature - it looks good!

**Closed** 2020-08-27 17:52 UTC
Labels: Feature:Collections, Feature:Tabs, Skittle, 🐞 bug
