### ISSUE TITLE
[Bug] Crash when entering sync password

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#7629] opened 2020-01-12 18:06 UTC
## Steps to reproduce
https://vimeo.com/384360861
### Expected behavior
not crash
### Actual behavior
crash
### Device information
OnePlus 5t

* Android device: ?
* Fenix version: ?

**Comment by xscd** [comment] 2020-01-12 18:51
I guess this is a duplicate of https://github.com/mozilla-mobile/fenix/issues/7625

**Comment by sv-ohorvath** [comment] 2020-01-13 09:51
Closing as dupe. If it's not, please reopen.

**Closed by sv-ohorvath** 2020-01-13 09:51 UTC
Labels: 🐞 bug
