### ISSUE TITLE
FNX2-13365 ⁃ [Bug] Files fail to load or write, first time after Permission is Approved

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#11150] opened 2020-06-02 16:46 UTC
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1641499

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0

Steps to reproduce:

Tested on Android 8.1 / Nightly 78
(after a fresh install)

Attempt to load a file, triggers Permission Approval Request to allow FF to access files and camera.
After granting FF the permissions, the initiated file-load, which triggered the request fails, which may crash site's (web-app's) functionality.

Attempt to save a file, triggers Permission Approval Request to allow FF to write/store files.
After granting FF the permissions, the initiated file-save, which triggered the request, fails. There is a "pop-up" notifying the user the file is "Downloading", but then nothing gets saved/downloaded.

After granting permission followed by a failed operation, successive file operations succeed.

**Comment by Mugurell** [comment] 2020-07-22 06:58
The "can't upload immediately after granting permission" issue will be resolved in https://github.com/mozilla-mobile/android-components/issues/7788

Downloading immediately after granting permissions seems to work. May have been resolved in the meantime.

**Comment by sv-ohorvath** [comment] 2020-07-30 15:06
I was able to reproduce the upload issue on squoosh.app, and now it's fixed on Nightly 7/30. The download part I couldn't reproduce before the fix either.

**Closed** 2020-08-12 06:47 UTC
Labels: Feature:Download, eng:qa:needed, eng:qa:verified, hershey, 🐞 bug
