### ISSUE TITLE
[Bug]about:config doesn't work in Firefox Release version 

### ISSUE THREAD

**Issue by freebrowser1** [mozilla-mobile/fenix#14707] opened 2020-09-04 06:13 UTC
Note: This is a duplicate of #7865 which was considered as off-topic and hence it is closed, while it is not. Many users complain about missing settings like proxy setting. That topic contains many user requests to enable it, but it appears to be ignored.

Even the beta version does contain about:config, so it is as simple as setting a switch / variable from off to on in the code.
Is there really such a strong reason to withhold users from this option ?

**Comment by cadeyrn** [comment] 2020-09-04 06:26
I think it's cheeky to open an issue just to circumvent the locking of another issue. It's a duplicate of #7865. And your comment does not any new arguments to the discussion so it was not even necessary.

**Comment by miska** [comment] 2020-09-04 06:30
Seems not locked, just simply broken at least according to the error.
![Screenshot_20200904-082312](https://user-images.githubusercontent.com/188214/92207028-d1bcdd80-ee88-11ea-882a-57476409ddab.png)

**Comment by cadeyrn** [comment] 2020-09-04 06:32
> Seems not locked, just simply broken at least according to the error.

This is because the feature is not enabled in stable releases.

**Comment by kbrosnan** [comment] 2020-09-04 07:23
This is a duplicate

**Closed** 2020-09-04 07:22 UTC
Labels: needs:triage, 🐞 bug

**Comment by miska** [comment] 2020-09-04 08:38
Ok, I don't like the fact but I can live with removing stable release and using Beta, but the error message is really confusing and should be probably fixed.

**Comment by freebrowser1** [comment] 2020-09-04 12:19
> > Seems not locked, just simply broken at least according to the error.
> 
> This is because the feature is not enabled in stable releases.
Exactly and that is why i report this.
