### ISSUE TITLE
Closing all tabs on exit (Android) [Bug]

### ISSUE THREAD

**Issue by Oleophobic** [mozilla-mobile/fenix#17779] opened 2021-02-03 00:31 UTC
i have to manually close tabs and open separate menus just to do this, the option to close tabs on exit has been missing waiting almost a year now and there is still no fix, quit option is not the solution to this ongoing problem the entire desktop and mobile experiences are inconsistent and an inconvenience for every user.

**Comment by yoasif** [comment] 2021-02-03 02:27
Dupe of https://github.com/mozilla-mobile/fenix/issues/5865

**Comment by kbrosnan** [comment] 2021-02-03 06:18
Closing as a duplicate

**Closed by kbrosnan** 2021-02-03 06:18 UTC
Labels: needs:triage, 🐞 bug
