### ISSUE TITLE
[Bug]: wrong tab focused in tab tray with activated Search Groups

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#23584] opened 2022-02-05 08:38 UTC
### Steps to reproduce

I Go to Tab Settings
Activate Search grouping
Set tab tray as a list 
Open multiple tabs (more than the height of the screen on the tab tray) 
Open the last tab 
Click on the Tab Tray button 

### Expected behaviour

The focus should be on the last tab at the bottom of the list

### Actual behaviour

The focus is on the first tab in the tray 

### Device name

Redmi note 7

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

98

### Additional information
The same issue happens in grid mode actually

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19394)

**Comment by Cheap-Skate** [comment] 2022-02-06 07:15
Duplicate of #21705??

**Comment by klint** [comment] 2022-02-06 08:49
Quite possible, but this one provides a more specific context when both issues happens : only when search is grouped.

**Comment by LaurentiuApahideanSV** [comment] 2022-02-07 15:01
I can confirm the issue is reproducible on Firefox Nightly 2022-02-07.

### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android 9)

**Comment by Alexandru2909** [comment] 2022-02-14 12:29
While debugging this issue I found that when the `Search groups` option is enabled, `TabGroupBinding` submits an empty list as the [currentList](https://github.com/mozilla-mobile/fenix/blob/8ced6758179b02b2950a040e755bc174253a31f8/app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt#L130). Also, if there are tabs opened in search groups, the [activeTabsList](https://github.com/mozilla-mobile/fenix/blob/8ced6758179b02b2950a040e755bc174253a31f8/app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt#L149) contains the tabs opened in the search groups instead of the tabs opened in `Other tabs`.

This issue should be looked into after the `TabsTray` compose refactoring. Solving it now does not mean it will not resurface after refactoring is complete.

**Comment by bigConifer** [comment] 2022-09-24 00:20
@klint can you please update the issue title to make clear, that this bug is about the tab tray showing the top of the tab list instead of the focused tab?

At the moment there are at least 5 open tickets about this bug. A precise title would help to concentrate the discussion on this ticket here.

**Comment by jonalmeida** [comment] 2023-01-17 16:02
Closing as won't fix as this feature has been removed until it's re-worked.

**Closed by jonalmeida** 2023-01-17 16:02 UTC
Labels: 🐞 bug, Feature:Tabs, S3, qa-triaged, Feature:SearchTermTabs

**Comment by travisterrell** [comment] 2023-01-17 16:16
Hi @jonalmeida,
Can you clarify this for me, please? Will this issue be tracked in one of the other (duplicate) tickets going forward? Or are you suggesting that this bug will disappear as a result of removing the feature? (If so, do you know approx. when to expect that change in Firefox Beta?)

Thanks in advance! I've been trying to keep a watch on this, since it's been such a source of grief for many users.

**Comment by jonalmeida** [comment] 2023-01-17 16:23
@travisterrell we've removed search groups in Fenix all together for now until the team works to fix the core issues with that this original version had.
