### ISSUE TITLE
[Bug] Custom tabs and PWA don't open in private mode with Open links in private On

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#8929] opened 2020-03-03 13:11 UTC
## Steps to reproduce
1. Set Open links in private On. Set Fenix as default browser.
2. Fenix is opened in normal browsing mode.
3. Open a custom tab or a PWA.

### Expected behavior
The custom tab & the PWA open in private mode.
### Actual behavior
The custom tab & the PWA open in normal mode. Links opened in Fenix, from them, are opened in private.
If Fenix is left in private mode, then the custom tabs and PWAs are opened in PB too.
### Device information

* Android device: Motorola Moto G6 (Android 8.0)
* Fenix version: Nightly 3/3. Not reproducing on Beta 4.0-build2

**Comment by kbrosnan** [comment] 2020-03-04 08:29
Looks like a dupe of #7996

**Closed by kbrosnan** 2020-03-04 08:29 UTC
Labels: Feature:CustomTabs, Feature:PWA, Feature:PrivateMode, needs:triage, 🐞 bug
