### ISSUE TITLE
Selecting text is not working properly [Bug]

### ISSUE THREAD

**Issue by jawadalkassim** [mozilla-mobile/fenix#5037] opened 2019-08-30 14:28 UTC
## Steps to reproduce
1-Launch Fenix
2-Go to any website for example: https://en.wikipedia.org/wiki/Main_Page
3-long press on any paragraph to select a word and try to slide the selector bubble to select more words from the article.
### Expected behavior
Select word by word or maybe by letters it depends on how fast you move the selector bubble
### Actual behavior
when long press on a word it will be selected but when trying to select more words the selector goes to the  other direction, it's quite impossible to select a sentence.
### Device information
Huawei P8 lite 2017
* Android device: Android 8.0
* Fenix version: 
Nightly 190830 06:05 (Build #12420615)
📦: 10.0.1, a573b4116
🦎: 70.0a1-20190826094255

**Comment by nahuhh** [comment] 2019-09-06 11:58
Same issue
8.1.0 BlackBerry KeyOne

**Comment by nahuhh** [comment] 2019-09-11 19:53
Trying to select the paragraph
From "when" to "sentence."

 ![20190911_154945](https://user-images.githubusercontent.com/50635951/64729857-0a132100-d4ac-11e9-823b-28200e639b52.gif)

**Comment by ekager** [comment] 2019-09-12 03:30
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1580669

**Comment by cpeterso** [comment] 2019-09-16 19:02
This bug is a Gecko regression in GV 70 from some changes made to improve Android input responsiveness on Fire TV (layout.reflow.synthMouseMove [bug 1545393](https://bugzil.la/1545393)). @makotokato says he will back out that change:

https://bugzilla.mozilla.org/show_bug.cgi?id=1580669#c15

**Comment by kolAflash** [comment] 2019-09-23 05:54
Same here.

Device: Fairphone 2 / FP2
OS: LineageOS-15.1
FirefoxPreview: 2.0.0 (Build #12610150)
Not using Beta in Play Store.

Guess the bug appeared since 1.4.0 or 2.0.0.

**Comment by sv-ohorvath** [comment] 2019-09-25 13:06
Looks like this is fixed on nightly 9/24.

**Closed by sv-ohorvath** 2019-09-25 13:06 UTC
Labels: P2, eng:qa:needed, needs:gv, 🐞 bug

**Comment by sv-ohorvath** [comment] 2019-09-30 11:58
This was not included in the 2.1.0 RC, still reproducing.

**Comment by cpeterso** [comment] 2019-09-30 21:46
> This was not included in the 2.1.0 RC, still reproducing.

What GeckoView version does Fenix 2.1.0 RC use? I assume it is using some version of GeckoView 70 Beta. However, the fix for bug 1580669 was uplifted to GeckoView Beta only three days ago. To get the fix, Fenix will need to update to GeckoView version 70.0.20190930090044 or later.

https://bugzilla.mozilla.org/show_bug.cgi?id=1580669#c28

**Comment by kolAflash** [comment] 2019-10-07 20:10
Looks like it's fixed in 2.1.0-final.
https://github.com/mozilla-mobile/fenix/releases/tag/v2.1.0
