### ISSUE TITLE
Homescreen elements should be be interactable when keyboard is up

### ISSUE THREAD

**Issue by violasong** [mozilla-mobile/fenix#16351] opened 2020-11-03 18:42 UTC
This is an offshoot of the Fenix homescreen issue: https://github.com/mozilla-mobile/fenix/issues/12065

@brampitoyo and I have been discussing the new homescreen with keyboard behavior in Nightly. With the latest two changes — 1. last used tab seen on launch, and 2. new tab starting with keyboard up (with a scrim over the homescreen) — it now takes an extra taps to get to top sites compared to before.

## Acceptance criteria
1. We are proposing that we remove the keyboard scrim from the homescreen so that top sites are still tappable. It should look like this:

<img src="https://user-images.githubusercontent.com/55994/97935690-26b48d00-1d2e-11eb-969c-f09c5addd7ed.png" width="300px">

2. Also, if the user scrolls either up or down on the homescreen when the keyboard is up, the keyboard should be dismissed (same as when you scroll up/down on the search suggestions view).

3. Add a 1dpx dividing line to differentiate the keyboard from the homescreen (see #15359)

## Stretch goal

The keyboard goes away in a smooth fashion as seen on iOS :). (And this can be applied in the future to the search suggestions view and other places with keyboards.)

![RPReplay_Final1604349131](https://user-images.githubusercontent.com/55994/97935861-9fb3e480-1d2e-11eb-98b1-bab677880719.gif)

**Comment by eliserichards** [comment] 2020-11-04 21:39
Notes from UX handoff: 
- This should also include the shadow in between the toolbar and homescreen
- There might be some difficulty animating the "scroll to minimize keyboard" animation. Time box this investigation and see what's possible

**Comment by eliserichards** [comment] 2020-11-04 21:40
https://medium.com/androiddevelopers/animating-your-keyboard-fb776a8fb66d
https://medium.com/androiddevelopers/animating-your-keyboard-reacting-to-inset-animations-839be3d4c31b

**Comment by liuche** [comment] 2020-11-05 04:09
@boek I remember when you implemented this that there were some edge cases that made this problematic - could you share what those were? And if they would still apply with this mock?

**Comment by maverick74** [comment] 2020-11-10 21:07
My major interest is about being able to reuse the current tab I'm on and substitute it by a bookmark or a history page or a search.

I'm not sure this bug addresses it... Can you please clarify this to me @violasong @ekager ?

Thank you.

(I've thought about opening an issue about it, but I don't believe nobody done it before. So I've tried (very much) to find a bug report about it - with no luck... So, hence, my request for clarification)

**Comment by brampitoyo** [comment] 2020-11-10 21:16
@maverick74 You can open bookmark or history on the current tab by either tapping the main application menu → Bookmarks/History, or by typing into the address bar → look for ⭐️ icon in search results.

Would this answer your interest, or are you interested in something else?

**Comment by maverick74** [comment] 2020-11-10 23:14
@brampitoyo If I go to address bar and search for a bookmark I end up with more taps than going all the way into main menu > bookmarks!

so, if it worked as you say and one could load a page into the current tab by going menu>bookmarks or menu > history, my problem would be solved. 

The problem is that it does not work as you say!!!

If I'm on a page and go to menu>bookmarks and tap on a bookmark it will load that bookmark into a new tab and I end up having to go manually close the tab I was in before

**Comment by ekager** [comment] 2020-11-10 23:33
@maverick74 you're probably looking for https://github.com/mozilla-mobile/fenix/issues/13336

**Comment by maverick74** [comment] 2020-11-11 09:48
@ekager  The time I already spent looking for this........ Thank you!!!!

**Comment by softvision-miralobontiu** [comment] 2020-12-14 12:37
Verified as fixed on the 12/14 Nightly build with Samsung Galaxy tab S6 (Android 10), OnePlus 5T (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
The homescreen elements are interactable when the keyboard is up.

**Closed by softvision-miralobontiu** 2020-12-14 12:37 UTC
Labels: Feature:HomeScreen, eng:qa:needed
