### ISSUE TITLE
I want

### ISSUE THREAD

**Issue by RaniCloud** [mozilla-mobile/fenix#6099] opened 2019-10-18 10:10 UTC
There are features that you would like to add to the Android Preview version. Changing tabs on left/right swipe in the address bar. It's so convenient. Add more features!

**Comment by cadeyrn** [comment] 2019-10-18 10:18
Duplicate of #3481.

And please give your issue a useful title the next time. It should be clear what this issue is about without the need to read the full description. Thank you.

**Closed** 2019-10-18 12:11 UTC
Labels: 🌟 feature request
