### ISSUE TITLE
[Bug]: Can not edit bookmark on Firefox Android without open the marked page

### ISSUE THREAD

**Issue by Flying-Miko** [mozilla-mobile/fenix#26725] opened 2022-08-31 09:43 UTC
### Steps to reproduce

1. Open the "Bookmarks" menu

### Expected behaviour

there should be a way for me to edit the book mark's name, folder etc., without needing to open the bookmarked page

### Actual behaviour

It doenst let me do it anymore, I cant find the option to edit. 

### Device name

Samsung Galaxy A71

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

104.1.0 (Build #2015898515), 99759dd72+ AC: 104.0.8, 3dc0ff00e7 GV: 104.0-20220816115024 AS: 93.7.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21429)

**Comment by nrmhrk** [comment] 2022-09-01 02:06
Same issue. Edit button is displayed as "X". When tapping on "X", the edit menu shows up.

**Comment by bigConifer** [comment] 2022-09-01 10:34
Duplicate of #26093.
This bug has already been fixed.

**Comment by Flying-Miko** [comment] 2022-09-01 13:19
> Duplicate of #26093. This bug has already been fixed.

When will the fix go live on "regular" firefox? Right now there is still X

**Comment by bigConifer** [comment] 2022-10-02 18:44
@Flying-Miko Would you be so kind to close this ticket as duplicate.

**Closed** 2022-10-03 15:30 UTC
Labels: 🐞 bug, needs:triage
