### ISSUE TITLE
Home button opens new tab instead of going to home

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#20090] opened 2021-06-19 12:14 UTC
Fenix's home button just opens the new tab instead of going home.

Current Behaviour:
1) open "domain name"
2) click home button
3) new tab opens but "domain name" tab exists.

Required Behaviour:
1) open "domain name"
2) click home button
3) new tab must open and "domain name" tab must not exist.

Required behaviour is same behaviour seen in Firefox desktop and Chrome browsers(both desktop and mobile).

Please correct it to perform required behaviour. if not, atleast rename the button to "new tab" button(which then becomes rebundant imo.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11073)

**Comment by cadeyrn** [comment] 2021-06-19 14:38
I disagree with your expected behaviour. I definitively **not** want that going to the home screen will result in a lost of my current tab. 🤔

>  if not, atleast rename the button to "new tab" button(which then becomes rebundant imo.

Nope, the home button and the new tab button are not the same even if they open the same screen, so neither is redundant. Both have a different use case. The new tab button allows you to directly enter the URL of a website since the keyboard is already opened. The home button gives a quick accesss to the top sites and collections in one instead of three actions. So for me the home button is a really big usability improvement while I still want to keep the new tab button for every other website that I don't have pinned to the home screen.

**Comment by ale82to** [comment] 2021-06-19 17:44
> Fenix's home button just opens the new tab instead of going home.
> 
> Current Behaviour:
> 
>     1. open "domain name"
> 
>     2. click home button
> 
>     3. new tab opens but "domain name" tab exists.
> 
> 
> Required Behaviour:
> 
>     1. open "domain name"
> 
>     2. click home button
> 
>     3. new tab must open and "domain name" tab must not exist.
> 
> 
> Required behaviour is same behaviour seen in Firefox desktop and Chrome browsers(both desktop and mobile).
> 
> Please correct it to perform required behaviour. if not, atleast rename the button to "new tab" button(which then becomes rebundant imo.

totally agree as for now home button is crap is nothing like opening a new tab without the keyboard!

**Comment by ale82to** [comment] 2021-06-19 17:47
> I disagree with your expected behaviour. I definitively **not** want that going to the home screen will result in a lost of my current tab. 🤔
> 
> > if not, atleast rename the button to "new tab" button(which then becomes rebundant imo.
> 
> Nope, the home button and the new tab button are not the same even if they open the same screen, so neither is redundant. Both have a different use case. The new tab button allows you to directly enter the URL of a website since the keyboard is already opened. The home button gives a quick accesss to the top sites and collections in one instead of three actions. So for me the home button is a really big usability improvement while I still want to keep the new tab button for every other website that I don't have pinned to the home screen.

could not disagree more, why on earth has fenix so special behavior? 
every mobile and desktop browsers have the expected behavior (open in existing tab) not current behavior (always open new tab 🤢).

**Comment by Cheap-Skate** [comment] 2021-06-21 17:58
Partial duplicate of #20012, perhaps we can resolve

Some fairly harsh criticism of the Fenix UI here, I hope developers take it in the right spirit, I think this is a crucial issue.


Fenix adopts a new paradigm for tab opening and the Home screen. As far as I know this new tab paradigm has never been used on another browser, mobile or desktop. In particular it’s not used on Firefox Desktop, or major competing desktop or mobile browsers.

IMHO adopting a new tab paradigm by default is a very dangerous thing to do. Even more so when it seems to bring disadvantages; the advantages seem limited; and it seems to contradict the way median users use their mobile browser. 

The new tab paradigm is hard to describe but its main differences from other browsers seem to be
1. pretty much everything opens in a new tab
2. the Home screen is a kind of metastate not associated with any particular tab
3. the New Tab button doesn’t immediately open a new tab
4. the New Tab button and the Home button do the same thing, except one invokes the keyboard while the other does not
5. from the Home screen the Android Back button/gesture exits the browser
6. there is a unique “Jump back in” button which might be a fix to overcome issue 5

For me (and at least some others eg on Github and Google Play Store reviews) the new tab paradigm brings significant disadvantages
- it’s different to other browsers so there is a learning curve and it’s hard to swap between browsers
- it’s confusing, particularly features 2 through 5
- feature 1 means a constant game of whack-a-mole to keep the number of tabs manageable
- or, feature 1 can lead to a cluttered tab tray and a slow phone due to memory pressure

My guess is that the new tab paradigm comes from the need to make Collections work. Personally I don’t use Collections, I am just a casual user and I find them bafflingly complicated. 

The Mozilla blog* says that the median user has only a handful of tabs open, I assume this is on Desktop. I expect that the median Fenix user has the same or fewer.  I am that median user, I typically have 2 or 3 tabs open in Fenix, a few more in Desktop.  I described in https://github.com/mozilla-mobile/fenix/issues/20012#issuecomment-863913320 how just a ten minute reading break on Fenix led to eleven open tabs (way more than I want), a game of tab whack-a-mole to close them, and a phone under severe memory pressure.

My questions:- Could Mozilla be alienating its casual/median users (like me) with Fenix's unconventional, confusing and memory hungry new tab paradigm? Could the only beneficiaries of the new tab paradigm be those who use extensively Collections? Is that trade off worth it? If so could there be a way to integrate Collections while still maintaining a more conventional tab paradigm?

I suspect the new tab paradigm is turning a lot of casual users away from Fenix. I'm certainly using Fenix less and less. It's just not worth the hassle.

Thanks again for your time

 * "Based on our research, we found out that more than half of you have 4+ tabs open all the time, and some of you have more, a lot more" https://blog.mozilla.org/en/products/firefox/fresh-new-look-for-firefox/

**Comment by ale82to** [comment] 2021-06-21 18:04
> Partial duplicate of #20012, perhaps we can resolve
> 
> Some fairly harsh criticism of the Fenix UI here, I hope developers take it in the right spirit, I think this is a crucial issue.
> 
> Fenix adopts a new paradigm for tab opening and the Home screen. As far as I know this new tab paradigm has never been used on another browser, mobile or desktop. In particular it’s not used on Firefox Desktop, or major competing desktop or mobile browsers.
> 
> IMHO adopting a new tab paradigm by default is a very dangerous thing to do. Even more so when it seems to bring disadvantages; the advantages seem limited; and it seems to contradict the way median users use their mobile browser.
> 
> The new tab paradigm is hard to describe but its main differences from other browsers seem to be
> 
>     1. pretty much everything opens in a new tab
> 
>     2. the Home screen is a kind of metastate not associated with any particular tab
> 
>     3. the New Tab button doesn’t immediately open a new tab
> 
>     4. the New Tab button and the Home button do the same thing, except one invokes the keyboard while the other does not
> 
>     5. from the Home screen the Android Back button/gesture exits the browser
> 
>     6. there is a unique “Jump back in” button which might be a fix to overcome issue 5
> 
> 
> For me (and at least some others eg on Github and Google Play Store reviews) the new tab paradigm brings significant disadvantages
> 
>     * it’s different to other browsers so there is a learning curve and it’s hard to swap between browsers
> 
>     * it’s confusing, particularly features 2 through 5
> 
>     * feature 1 means a constant game of whack-a-mole to keep the number of tabs manageable
> 
>     * or, feature 1 can lead to a cluttered tab tray and a slow phone due to memory pressure
> 
> 
> My guess is that the new tab paradigm comes from the need to make Collections work. Personally I don’t use Collections, I am just a casual user and I find them bafflingly complicated.
> 
> The Mozilla blog* says that the median user has only a handful of tabs open, I assume this is on Desktop. I expect that the median Fenix user has the same or fewer. I am that median user, I typically have 2 or 3 tabs open in Fenix, a few more in Desktop. I described in [#20012 (comment)](https://github.com/mozilla-mobile/fenix/issues/20012#issuecomment-863913320) how just a ten minute reading break on Fenix led to eleven open tabs (way more than I want), a game of tab whack-a-mole to close them, and a phone under severe memory pressure.
> 
> My questions:- Could Mozilla be alienating its casual/median users (like me) with Fenix's unconventional, confusing and memory hungry new tab paradigm? Could the only beneficiaries of the new tab paradigm be those who use extensively Collections? Is that trade off worth it? If so could there be a way to integrate Collections while still maintaining a more conventional tab paradigm?
> 
> I suspect the new tab paradigm is turning a lot of casual users away from Fenix. I'm certainly using Fenix less and less. It's just not worth the hassle.
> 
> Thanks again for your time
> 
>     * "Based on our research, we found out that more than half of you have 4+ tabs open all the time, and some of you have more, a lot more" https://blog.mozilla.org/en/products/firefox/fresh-new-look-for-firefox/

exactly for example because of this both my mother and father (in their 50s) could not get used to fenix even if I explained them the advantage of having ublock, and switched to Samsung browser wich they do love.

**Comment by amedyne** [comment] 2021-06-21 18:56
@topotropic @vesta0 Here's some more feedback on the Home behavior.

**Comment by DavidJCobb** [comment] 2021-11-06 13:24
> Partial duplicate of #20012,

Yeah, not only is this issue just a side effect of the home screen being so counterintuitive in that particular way; it actually makes the home screen *more* counterintuitive. It's completely nonsensical to have a button that looks like the "home page" button in every other browser, and is meant to be treated by the user like the "home page" button in every other browser... but instead, it's just a second "pretend to open a new tab" button, which is itself apparently a Fenix-only concept.

Fenix having a fake "new tab" button is already confusing. Now it has a fake "home" button that's actually a fake "new tab" button. I don't think I've ever even seen a mainstream piece of software with this sort of doubly fake button before.

**Comment by M-Reimer** [comment] 2022-05-09 20:42
The home button is still broken. And as it does the same as if I just tap on the address bar, the button probably should be removed altogether.

**Comment by SergiiGalai** [comment] 2022-05-22 20:18
I love FF because of it privacy orientation. Even if it is a bit slower than competitors. 
I thought this is a bug for a long time and was patient. Even switched to other browser for a year to let time developers to fix it. But it is as usually not a bug but feature.
I find it really counterintuitive and not user friendly. This is so confusing. 
I find the current behavior as not sequencial.
Let's assume a very easy use case - user has several favorite web sites in collection: Open the browser > click on saved to collection page >  site main page opened > open some article, swipe back. Now as expected user is on main page of the site (back action). Swipe back again. It looks as it went back, number of tabs is the same, site disappeared, default page is opened. Opened web sites are zero, only the home page. So far so good. 
Click the same item from the collection again. And now we have two same opened sites. Why it was 0 now became 2. Make swipe back again. And click another favorite site. Now there 3 tabs opened. Why Carl? Why back action actually opens a new tab.
Usually I have several tabs opened for a long. And in a new tab read news. But with this 'feature' after each reading session I have to manually close just opened tabs and leave untouched what was present before. This is a real deal breaker.

**Comment by Matth7878** [comment] 2022-05-29 08:44
> The home button is still broken. And as it does the same as if I just tap on the address bar, the button probably should be removed altogether.

It does not exactly the same : 
- doesn't popup keyboard. A huge plus for me as keyboard hide most of the homepage...
- back button kick you out of Firefox. I don't understand it has not been fixed.. Sadly it's one more thing which show that devs probably don't use Firefox on Android... 😕

**Comment by M-Reimer** [comment] 2022-11-26 08:57
Still issues with the home button. Is there maybe a way to hide it altogether? I would like to try reimplementing it with an add-on.

**Comment by csadilek** [comment] 2023-01-20 21:51
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811604

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2023-01-20 21:51 UTC
Labels: 🐞 bug, needs:triage
