### ISSUE TITLE
In-app crash reporter: React to "crashed" flag instead of Intent

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#22722] opened 2021-12-06 18:00 UTC
(I was pretty sure I filed this before. But I can't find it. So filing it again)

When a content process crashes then this doesn't crash the whole app. Instead affected tabs are considered crashed and can be restored. For that Fenix implemented an in-app UI that says "this tab crashed" and offers the user to "restore" or "close" the tab. To make this possible Fenix is listening to an `Intent` from the crash reporter ([code](https://github.com/mozilla-mobile/fenix/blob/6a3adb5aeba976a7146eb96a2ef3794fae909304/app/src/main/java/org/mozilla/fenix/home/intent/CrashReporterIntentProcessor.kt#L16)).

This implementation has multiple problems. Primarily it is only able to show the crash reporter if the app is in the foreground listening to this intent. There can be multiple reasons that a tab crashes in the background and the intent does not get processed. If a crash reporter was never shown for a tab then this tab has a crashed `GeckoSession` attached to it. This crashed tab will not be able to render content (and may show content of another tab) and the user cannot interact with it.

Instead Fenix should show the crash reporter for the current tab whenever `tab.engineState.crashed` is true - and ignore the `Intent`. This will make sure that the crash reporter will always overlay a crashed tab, forcing the user to make a decision (restore or close).

Furthermore this will make it possible to build a better UI. Currently, with the `Intent`, Fenix only sees the `Intent` and knows that _a_ tab crashed. But not which one. By reading this flag Fenix can show the crash reporter for the specific, crashed tab - as well as list all crashed tab and/or allow to restore subsets.

**Comment by kbrosnan** [comment] 2021-12-13 22:57
Added this to the backlog.

**Comment by Mugurell** [comment] 2021-12-17 10:32
Looked a bit at this and I think more approaches are possible.
Looking at home Chrome handle tab crashes maybe we should have a similar approach, one closer to how we show the error pages allowing the user to freely interact with the app even switch between tabs:

| Chrome handling crashed tabs | Fenix handling error pages | Fenix handling crashed tabs |
| --- | --- | --- |
| <video src="https://user-images.githubusercontent.com/11428869/146524967-b6de6b87-95a2-4aca-8d77-b1ae3e8c3e7a.mp4" /> | <video src="https://user-images.githubusercontent.com/11428869/146525022-7f80e98c-9977-49c2-b8c4-5fa02463371a.mp4" /> | <video src="https://user-images.githubusercontent.com/11428869/146525094-bc307bb3-6ac2-40dc-abc8-2a119cac2967.mp4" /> |

though not sure how we'd show a new crash reporter page if the content process crashed?
Maybe if restarting the same process immediately and switching to a crash reporter page we could get into a crashing loop?

Using this similar approach for error pages and crash reporter allows for a cohesive experience regarding browsing issues and neatly integrates this in how users interact with the browser.
Having possibly multiple crashed tabs in the tabs tray and allowing users to later decide what should be the next action - report/close/reopen seems the most unobtrusive and useful scenario.

@topotropic , @pocmo ?

**Comment by pocmo** [comment] 2021-12-17 15:02
> one closer to how we show the error pages allowing the user to freely interact with the app even switch between tabs:

Yes, I think that would be fantastic and would be possible if we read the `crashed` flag and stop relying on the `Intent`, which kind of requires us to block everything because we do not know better.

> though not sure how we'd show a new crash reporter page if the content process crashed?

On the app level you do not need to care about the specific process (or which one in the case where we have multiple). If `tab.engineState.crashed` is `true` then you show the in-app UI for "oops, this tab crashed". Via the `CrashRecoveryUseCase` you can restore tabs if the user wants to.

> Maybe if restarting the same process immediately and switching to a crash reporter page we could get into a crashing loop?

There should be no crash loop, because the tab gets restored only if you invoke the use case. And you can show the custom UI (native UI!) without restoring it. So as long as the user doesn't actively decide to do that, there will not be a new crash (if it always crashes).

**Comment by topotropic** [comment] 2021-12-20 20:00
Sounds like you're good to go, but please ping me if you need anything from UX. Thanks!

**Comment by Mugurell** [comment] 2021-12-28 16:01
Saw that `about:crashcontent` is crashing two sessions even in GVE, opened https://bugzilla.mozilla.org/show_bug.cgi?id=1747802

**Comment by Mugurell** [comment] 2022-01-03 13:50
Looked at how we could pair a crash to a session/tab and then persist this info.
Seems to me like we can't easily at the moment.
I don't see a clear connection between a tab and an `EngineSession` and then between a session and a crash received in `CrashHandlerService`.

Maybe the [`EngineState`](https://github.com/mozilla-mobile/android-components/blob/af95a0445737549087bd202ec3701990ee604eb0/components/browser/state/src/main/java/mozilla/components/browser/state/state/EngineState.kt#L29) should contain beside the `crashed` flag also the id of the current `EngineSession`?
And then the crash details could be persisted locally by GV in `/<EngineSession.id>. ...` files? Easy for us to query after?
@pocmo @csadilek ?

**Comment by pocmo** [comment] 2022-01-03 18:04
@Mugurell I do not understand what you are trying to achieve? What/why do you want to persist?

**Comment by Mugurell** [comment] 2022-01-03 18:33
> @Mugurell I do not understand what you are trying to achieve? What/why do you want to persist?

Allowing users to continue using the app with otherwise crashed tabs would also give the possibility to postpone actually sending a crash report until later, even after app restarts.
The crashes are already persisted locally but I don't know how to link a tab to a crash.

Even if we are to start fresh after an app restart (avoid thinking about persisting the crash data and status) I still don't see a way currently to link an `EngineSession` crash to the `EngineState`.
The crash event comes through a [`ContentDelegate`](https://searchfox.org/mozilla-central/rev/fac07284a9a996ddf968ea53adaf25c2a8b7c520/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSession.java#390) at which time we don't have any data about the crash. We'll just set the `.crashed` state.
[GV then starts the crash service](https://searchfox.org/mozilla-central/rev/fac07284a9a996ddf968ea53adaf25c2a8b7c520/toolkit/crashreporter/nsExceptionHandler.cpp#1248-1253) (in another process) and passes the crash data through the start Intent which is [easily read in `CrashHandlerService`](https://github.com/mozilla-mobile/android-components/blob/71e124a5dbafffb800168ea615fdbc54d7398f50/components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/CrashHandlerService.kt#L70) but that [`Crash` doesn't allow us to identify which session crashed](https://github.com/mozilla-mobile/android-components/blob/71e124a5dbafffb800168ea615fdbc54d7398f50/components/lib/crash/src/main/java/mozilla/components/lib/crash/Crash.kt#L62-L67). This is what gives us the Intent to work with in Fenix's `CrashReporterIntentProcessor` -> `CrashReporterFragment`.

This scenario works okay with the current crash reporter which overlays the entire app and doesn't need to link a crash to a particular tab but for the scenario in which a background tab crashes and we need to show that the next time the user comes to that tab / tabs tray it seems to me like we need a way to link the session to a tab and then the crash to contain info about the crashed session allowing us to link them all together.
The current implementation has the `Crash` received by `CrashReporterFragment` passed to the Controller [which knows how to submit that Crash if users checked that action](https://github.com/mozilla-mobile/fenix/blob/4f55f16bd772a9516a4f4a3c9975c3e4ab82ee53/app/src/main/java/org/mozilla/fenix/crashes/CrashReporterController.kt#L74).

**Comment by pocmo** [comment] 2022-01-04 13:54
Yeah, let's ignore persistence for now. That's a completely separate problem. The crashed flag only matters during runtime. On (cold) restart of the app, the engine session will be restored if needed (selected) - and may crash again or not.

However, the problem you are having right now is that you do not have access to a `Crash` object, so you cannot report it from the UI if the user decides to do that, right?

We indeed do not have any way to map a crash to a tab (and a crash can affect multiple tabs). But, the only crashes we are able to handle in the app, are content process crashes. Everything else will crash the app process. We could consider adding them to browser-state(*) (in a list, with no link to the tab) and consider sending all of them (or removing them). In most cases there will actually only be one - and the UI will make the user decide between sending it or removing it.

(*) Since we are receiving them in a different process, we may still need to send them to the main process via an `Intent` and then add them to browser-state. However we could hide that in the crash component and don't need the app to handle that. 🤔

**Comment by pocmo** [comment] 2022-01-04 14:49
> But I don't see a way to link a Crash coming to the app to a specific session/tab that we then have to show as crashed and allow the user to report a specific crash dump.

Yes, this is not possible. And may not be a 1:1 mapping, as one crash can affect multiple tabs / engine sessions. Maybe we don't need that, though. We can show the user the UI to ask them whether they want to restore this tab or not. And at the same time ask them to send the "pending" crash reports. As mentioned above, the crashes we can handle here are all about crashed tabs (content processes). Do we really need a mapping?

Also take a look at https://github.com/mozilla-mobile/android-components/issues/11358 - soon we will have other "background" crashes that we want to prompt the user about. And they are not linked to tabs either and the tabs continue to work and are not "crashed". So maybe this is now a good time to make the in-app UI for reporting crashes independent  from a crashed tab? 🤔

**Comment by SoftVision-LorandJanos** [comment] 2022-02-21 12:30
Verified on the latest Nightly 99.0a1 (2022-02-21).
Device used: Oppo Reno 6 (Android 11).
Closing the ticket as fixed.

**Closed by SoftVision-LorandJanos** 2022-02-21 12:30 UTC
Labels: 🐞 bug, eng:qa:needed, Feature:CrashReporting, needs:triage

**Comment by jamienicol** [comment] 2022-03-14 15:44
@pocmo @Mugurell This change appears to have stopped GPU process crash reports from being submitted. You can see [here](https://crash-stats.mozilla.org/topcrashers/?product=Fenix&version=100.0a1&process_type=gpu) we've only received 3 reports in the past week.

GPU process crashes start a crash intent with `fatal="false"` and `processType="BACKGROUND_CHILD"`. I don't believe they set any `crashed` flag. (I'm not familiar with that flag, is it set by geckoview or android-components?)

From local testing I can see that if I cause a GPU process crash then the crash reporter UI no longer appears. However, if I subsequently cause a content-process crash it does appear. And clicking submit will then submit both the GPU process crash and the content process one. Is that the intended behaviour? Are these "queued" crashes persisted across restarts? I'm guessing not, otherwise I'd expect us to have received a few more crash reports.

Is there anything I can change on gecko's end to make Fenix submit these crash reports again? Or is it possible for Fenix to start asking to submit crashes from the intent again?

**Comment by Mugurell** [comment] 2022-03-14 16:26
@jamienicol Thanks for the ping.
Is there an easy way to force a gpu crash to test what's happening?

**Comment by jamienicol** [comment] 2022-03-14 16:37
`adb shell run-as org.mozilla.fenix.debug killall org.mozilla.fenix.debug:gpu -s SIGSEGV` should do the trick

**Comment by Mugurell** [comment] 2022-03-14 16:48
Christian pointed that this might happen as a followup to https://bugzilla.mozilla.org/show_bug.cgi?id=1755375

**Comment by Mugurell** [comment] 2022-03-14 16:58
Seems like we continue to get the crash report in the app but the tab is not marked as crashed (following #1755375)  and as such we won't be showing the in-app crash reporter.

**Comment by csadilek** [comment] 2022-03-14 17:03
Just to clarify. The patch above (1755375) made sure that process kills are not reported as crashes, so it's related but not the cause. We would still need https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSession.java#3100 to be invoked for GPU crashes to show a dialog to the user, at least with this latest logic. 

Possibly we need to expose a separate callback / flag here? @agi

**Comment by csadilek** [comment] 2022-03-14 17:09
(The [description](https://github.com/mozilla-mobile/fenix/issues/22722#issue-1072439748) above has all the details of the downsides of reacting just to the intent e.g. missing crashes when the app is in the background).

**Comment by agi** [comment] 2022-03-14 20:48
I responded here: https://github.com/mozilla-mobile/android-components/issues/11358#issuecomment-1067268657 (we can use that issue to keep tracking this problem)
