### ISSUE TITLE
FNX-4877 ⁃ Cannot login into slack app using Fenix

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#1213] opened 2019-03-27 02:11 UTC
## Steps to reproduce
* Try to login into slack from an non authenticated phone
* Complete dual authentication auth0 steps on phone

### Expected behavior
Control is given back to Slack and login is successful.

### Actual behavior
Fenix gets stuck on a white page after dual auth is completed.

* Android device: Samsung S10e
* Fenix version: 1.0.1913

**Comment by agi90** [comment] 2019-03-27 03:30
![Screenshot_20190327-091219_Fenix](https://user-images.githubusercontent.com/4297388/55048579-ee06ea80-5005-11e9-836b-f95c9496483d.jpg)

**Comment by vesta0** [comment] 2019-04-03 21:16
This could be caused by Tracking Protection. Will verify once tracking protection feature landed.

**Comment by kbrosnan** [comment] 2019-04-26 00:07
Works for me using April 25th build and request desktop site on a Pixel 3. Request desktop site is required to bypass the Slack app download redirect.

**Comment by agi90** [comment] 2019-04-26 17:51
This is still broken for me (and works on other browsers like Chrome)

Note for STR:

- Logout from Slack *app*
- Login again
- Select Auth0 (this opens Fenix if it's your default browser)
- Log in
- White page (instead of getting back to Slack app)

**Comment by jonalmeida** [comment] 2019-04-26 17:54
This is _might_ be the app not having intent handling to external apps: https://github.com/mozilla-mobile/android-components/issues/1132

**Comment by kbrosnan** [comment] 2019-04-27 04:42
I thought you were trying to use the web version of Slack on Fenix.

**Comment by agi90** [comment] 2019-04-30 00:24
I want to add that this is especially frustrating because users have to change the default browser to unblock themselves, I wouldn't even expect most users to even know how to get there from the settings.

**Comment by vesta0** [comment] 2019-04-30 00:50
Thanks @agi90. We have prioritized the related. A-C issue.

**Comment by bifleming** [comment] 2019-06-03 18:06
@kbrosnan can you re-test now that the applink work has landed?

**Comment by jonalmeida** [comment] 2019-06-04 16:10
In our sprint planning I said I would re-test this since I still had the issue showing up. There was a crash issue that was in the way of testing it yesterday itself.

I retested this now and I still see the blank screen after logging in without being redirected to the Slack app.

Device: Pixel 2, Android 9.

cc: @jhugman

**Comment by jhugman** [comment] 2019-06-05 13:16
Thanks, @jonalmeida : I'll take a look.

**Comment by sv-ohorvath** [comment] 2019-06-11 11:16
Verified I can now login to Slack using Fenix default browser. Build: 6/11. Devices: HTC Desire 820 (Android 6.0.1), Pixel (Android 9)

**Comment by sblatz** [comment] 2019-06-20 21:35
Re-opening per: https://github.com/mozilla-mobile/fenix/issues/3528#issuecomment-503630172

**Comment by jhugman** [comment] 2019-07-15 14:22
This is blocked on re-enabling app-links for custom schemes and intents.

**Comment by sblatz** [comment] 2019-07-23 19:52
I believe this we re-enabled by @jhugman? https://github.com/mozilla-mobile/fenix/pull/4117

**Comment by sv-ohorvath** [comment] 2019-07-24 08:45
Can now login into Slack using Fenix Nightly 190724 Build #12050609.

**Closed** 2020-08-11 05:49 UTC
Labels: Feature:OpenInApp, P2, eng:qa:verified, needs:ac, 🐞 bug
