### ISSUE TITLE
[Bug]: main menu is missing on fresh install/cleared storage

### ISSUE THREAD

**Issue by gwarser** [mozilla-mobile/fenix#22754] opened 2021-12-08 20:30 UTC
### Steps to reproduce

1. open fresh browser
2. tap on "start browsing" button
3. new tab with keyboard opens
4. no main menu button
5. tap on home page background to dismiss keyboard
6. main menu still missing

### Expected behaviour

I wan to access menu to configure something in fresh browser / familiarize myself with settings.

### Actual behaviour

No access to any configuration.

### Device name

Samsung Galaxy j3

### Android version

7.1.2 (lineage os 14.1)

### Firefox release type

Firefox Nightly

### Firefox version

2015850217

**Comment by gwarser** [comment] 2021-12-09 16:46
Bonus issue: if "adjust home page" button appear at the bottom of home page, nothing happens after tapping on it. It's weird, because it seem to react by changing color, but nothing more happens - no access to configuration as in ↑

**Comment by bli-mozbj** [comment] 2021-12-23 06:59
This issue can be reproduced on Fenix 96 Beta 4 (Build #2015852627)

**Comment by SoftVision-LorandJanos** [comment] 2021-12-23 08:50
I could reproduce this issue on the latest Beta (96.0.0-beta4) and latest Nightly 97.0a1 also.
However a similar one was logged before here: #22736.
Also there are some devices we couldn't reproduce this issue on:
- Samsung Galaxy Tab A6 (Android 5.1.1) - Nightly and Beta.
- Sony Xperia Z5 Premium (Android 7.1.1) - Nightly and Beta.
- Xiaomi Mi8 Lite (Android 10) - Nightly and Beta.
- Google Pixel 3 (Android 12) - Beta.

Reproduced on:
- Samsuns S10E (Android 10) - Nightly and Beta.
- Xiaomi Mi11 Lite (Android 11) - Nightly and Beta.

**Comment by SoftVision-LorandJanos** [comment] 2021-12-23 10:32
Also, as mentioned [here](https://github.com/mozilla-mobile/fenix/issues/22736#issuecomment-1000154358), when this issue occurs, the "Customize homepage" button from the bottom of the homepage doesn't work.

**Comment by rocketsroger** [comment] 2021-12-23 15:24
This issue is due to a conflict of requirements.  One requirement is to hide the keyboard when user scrolls/touch the home page.  The other requirement is to show the keyboard so the user knows that they are still in edit mode on the awesome bar.  Currently on Nightly we show the cursor/highlighted url when the keyboard is hidden to give a hint that the user have to press back to go back to display mode.  I don't see a good solution to this problem.  We can either:

1. Consume the first touch event on the home page to switch the awesome bar back to display mode.  This causes a perception of lag/performance issue which was rejected.
2. Do not hide the keyboard when user touch/scroll on the home page.  This is the current behaviour on release.  However, this was deemed unacceptable from the user experience perspective. See https://github.com/mozilla-mobile/fenix/issues/20701.

**Comment by kbrosnan** [comment] 2021-12-23 15:30
Sounds then like this is a wontfix? Does UX have any other suggestions?

**Comment by rocketsroger** [comment] 2021-12-23 15:33
> Also, as mentioned [here](https://github.com/mozilla-mobile/fenix/issues/22736#issuecomment-1000154358), when this issue occurs, the "Customize homepage" button from the bottom of the homepage doesn't work.

This issue does require some investigation though.  The user should always be able to tap on customized homepage button if it is visible.

**Comment by rocketsroger** [comment] 2021-12-23 15:33
> Sounds then like this is a wontfix? Does UX have any other suggestions?

I am looking into the "Customize homepage" button issue.  It is reproducible.

**Closed** 2021-12-23 20:34 UTC
Labels: 🐞 bug, Feature:HomeScreen, Feature:Search, Feature:MainMenu, qa-triaged

**Comment by SoftVision-LorandJanos** [comment] 2022-01-04 07:49
Verified as fixed on the latest Nightly (2022-01-04).
Device used: Oppo Reno 6 (Android 11).
