### ISSUE TITLE
Firefox contacts Telemetry Servers although Telemetry is disabled!

### ISSUE THREAD

**Issue by tegutistgut** [mozilla-mobile/fenix#20384] opened 2021-07-15 19:43 UTC
Hi,
I installes NetGuard from Github today and i saw that Firefox connects to these domains every 5-15 minutes:

`location.services.mozilla.com`
`firefox.settings.services.mozilla.com`
`incoming.telemetry.mozilla.org`

And yes, i had Telemetry disabled since day 1 of my usage. I enabled and disabled Telemetry again, but it didnt changed anything.

If other users can confirm this, or if they have the same issue, please respond. 

Thanks

**Comment by hakkikaancaliskan** [comment] 2021-07-15 20:13
Duplicate of #18660?

**Comment by tegutistgut** [comment] 2021-07-15 21:35
> Duplicate of #18660?

Yeah you are right. But i will leave this issue open, because i wanna know what the current development status of this bug is.

so: devs, what's the status? 
Ty

**Comment by kbrosnan** [comment] 2021-07-15 23:19
Closing as a duplicate. The other issue is closed because the team that owns the code responsible for fixing it uses Bugzilla.

**Closed by kbrosnan** 2021-07-15 23:19 UTC
Labels: needs:triage
