### ISSUE TITLE
Phone freeze while browsing (twitter?)

### ISSUE THREAD

**Issue by JonatasVi** [mozilla-mobile/fenix#21979] opened 2021-10-17 13:07 UTC
## Steps to reproduce
I'm just playing in the browser and out of nowhere freezes on some site

### Expected behavior
I expected the browser to work normally

### Actual behavior

the browser freezes and my phone is frozen for a while, only to return to normal later and this only happened in firefox and browsers based on it

### Device information

* Android device: Moto G9 Play
* Fenix version: 93.1.0

**Comment by mcomella** [comment] 2021-11-03 20:45
@JonatasVi There are instructions on this page: https://profiler.firefox.com/docs/#/./guide-remote-profiling Thank you!

**Comment by JonatasVi** [comment] 2021-11-04 18:13
is to take a capture of what?

Em qua., 3 de nov. de 2021 16:45, Michael Comella ***@***.***>
escreveu:

**Comment by JonatasVi** [comment] 2021-11-04 18:17
Em qui., 4 de nov. de 2021 às 14:13, Jonatas de Almeida Barros <
***@***.***> escreveu:

**Comment by mcomella** [comment] 2021-11-10 23:57
@JonatasVi When you start experiencing performance issues, can you start the profiler and continue to interact with the app? A profile tells us what is happening in the application so we might be able to diagnose your performance issue with it.

**Comment by JonatasVi** [comment] 2021-11-11 15:34
it is not possible to reproduce the error as it can happen at any time.

Em qua., 10 de nov. de 2021 19:57, Michael Comella ***@***.***>
escreveu:

**Comment by mcomella** [comment] 2021-11-17 22:49
@JonatasVi Does this happen only on specific sites or can it happen on any site?

We can't reproduce the issue currently. If we can't get more information that lets us reproduce the issue, we'll have to close the bug unfortunately because there's nothing we'll be able to do to solve it. Let us know if you have more information that would let us reproduce the bug!

**Comment by JonatasVi** [comment] 2021-11-17 23:03
happens a lot when I'm using Twitter, and I use other tabs

Em qua., 17 de nov. de 2021 18:50, Michael Comella ***@***.***>
escreveu:

**Comment by jonalmeida** [comment] 2021-11-28 01:10
This is happened to me today but I don't see anything useful in the profile by the time I was able to attach the profiler so might have lost some important events that led up to it: https://share.firefox.dev/3CVWEo9

**Comment by mcomella** [comment] 2021-12-01 22:12
Looking at the profile, it looks like the profile is empty because we're unable to sample (see the blue bar at the bottom of each track, where a slice will indicate we've taken a sample – it's one giant blue bar instead of thousands of small ones). @jonalmeida If you see this again, maybe try waiting a little longer before capturing the profile so we can see if we can get some samples.

Action item @MarcLeclair : try to reproduce by clicking on a video in a twitter PWA.

**Comment by mcomella** [comment] 2021-12-08 21:40
Triage: there is a bug in PWAs that prevent jonalmeida from reproducing. MarcLeclair was unable to reproduce (black screen).

> I was scrolling through a twitter PWA and clicked on a video that was playing fine until it started freezing. Backing out of the video worked for a brief second and then it was a perma freez.

This was also doom scrolling. Maybe using too much memory and we never unload it (would depend on the content).

**Comment by JonatasVi** [comment] 2021-12-11 19:45
were they able to find the problem?

Em qua., 8 de dez. de 2021 17:40, Michael Comella ***@***.***>
escreveu:

**Comment by MarcLeclair** [comment] 2021-12-16 01:18
Triage: Closing for now and we'll reopen if this happens again.

**Closed by MarcLeclair** 2021-12-16 01:18 UTC
Labels: performance, needs:triage
