### ISSUE TITLE
Bottom address bar covers floating bottom website content

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#830] opened 2019-03-04 21:56 UTC
## Steps to reproduce
* Open https://www.wunderground.com
* Tap full forecast
* Scroll up and down

### Expected behavior
* Address bar does not cover website bottom bar
* [Today | Hourly | 10-Day | Calendar |>]

### Actual behavior
* Address bar interacts poorly website content

### Device information

* Android device: All
* Fenix version: March 1

Websites with similar problems
* https://maps.google.com - quick actions bar
* https://www.tesla.com - when buillding a car

**Comment by pocmo** [comment] 2019-03-05 11:19
Related: https://github.com/mozilla-mobile/reference-browser/issues/464

**Comment by vesta0** [comment] 2019-03-27 06:20
Duplicate of #552

**Closed by vesta0** 2019-03-27 06:20 UTC
Labels: a-c, 🐞 bug
