### ISSUE TITLE
Speed dial when press on the address bar

### ISSUE THREAD

**Issue by JonDous** [mozilla-mobile/fenix#20468] opened 2021-07-22 08:56 UTC
Firefox before 70 version has a nice behavior: when you click on the address bar you also see a speed dial, history, bookmarks. 

### What is the user problem or growth opportunity you want to see solved?
Now when you click on the address bar a site makes darken and you just can type a request in the address bar. 
Users are not able to open bookmarked site in the same tab and have to open a new one. It makes to many actions and clicks for simple steps as it was before. 

Firefox <70: click address bar, click pin site. 
Firefox >70: click new tab, click pin site, click show tabs, click close old tab, click new opened tab. 

### Who will benefit from it?
Users of Firefox Russian community

**Comment by cadeyrn** [comment] 2021-07-22 09:15
Duplicate of #15866.

**Comment by kbrosnan** [comment] 2021-07-22 15:38
Closing as a duplicate

**Closed by kbrosnan** 2021-07-22 15:38 UTC
Labels: needs:triage
