### ISSUE TITLE
[Bug] Keyboard doesn't always come up when tapping url bar

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#9500] opened 2020-03-29 17:30 UTC
## Steps to reproduce

Be reading a webpage
Tap on Url bar

### Expected behavior

Keyboard appears on the url entry screen

### Actual behavior

URL entry screen loads but no keyboard comes up. Can't enter URL or search. Seems to happen roughly 30% of the time, only noticing it today so maybe a recent regression.

### Device information

* Android device: Android 9 on Sony xperia xz1c
* Fenix version: 
Nightly 200328 18:00 (Build #20881806)
38.0.20200326160141, d34bd466f
GV: 76.0a1-20200325093457
AS: 0.55.0

**Comment by cadeyrn** [comment] 2020-03-29 17:50
I don't have STR and and most times it works for me but I saw the same issue two times today. It's definitively a recent regression.

**Comment by quadriflax** [comment] 2020-03-29 17:51
See here: https://github.com/mozilla-mobile/fenix/issues/9497

Also, on my Moto G5+, it happens at the home screen, too, so it's not just when a website is loaded.

**Comment by ekager** [comment] 2020-03-29 18:38
Likely a regression from 
https://github.com/mozilla-mobile/fenix/pull/8576

**Comment by ekager** [comment] 2020-03-29 18:46
Or if it's only happening from browser possibly https://github.com/mozilla-mobile/fenix/pull/8988

**Comment by ekager** [comment] 2020-03-29 18:48
cc @codrut-topliceanu @mcarare when ya'll log on Monday morning could you take a look at this?

**Comment by tom-james-watson** [comment] 2020-03-29 22:50
This happens 100% of the time I click on the url bar for me on latest nightly. Have had to switch to Firefox Preview stable.

**Comment by shawnz** [comment] 2020-03-30 00:58
I think this is a dupe of #9478, copying my comments from there.

As a workaround, if I go to a different app, show the keyboard there, and then switch back to Firefox Preview using recent apps, then the keyboard still appears and I can type.

Also, if I click the "scan QR code", then click back, it temporarily fixes the issue.

**Comment by mcarare** [comment] 2020-03-30 07:34
> Or if it's only happening from browser possibly #8988

 `           view?.hideKeyboard()` is not called when navigating to search screen. Also, I have been able to reproduce this bug without that part of code being called. 

The workaround is the one mentioned in https://github.com/mozilla-mobile/fenix/issues/9497#issue-589823463

**Comment by shawnz** [comment] 2020-03-30 22:08
The issue is now fixed for me after installing the latest Play store update. Thank you everyone!

**Comment by quadriflax** [comment] 2020-03-30 22:12
Also seems fixed here after latest update.

**Closed** 2020-03-30 22:16 UTC
Labels: Feature:NavBar, Feature:Search, S1, needs:group-triage, needs:triage, 🐞 bug
