### ISSUE TITLE
[Design Bug] Undo Collection deletion

### ISSUE THREAD

**Issue by jtagcat** [mozilla-mobile/fenix#12375] opened 2020-07-08 01:38 UTC
## Steps to reproduce
Delete a collection

### Expected behavior
No confirmation, get an undo prompt.

### Actual behavior
No confirmation.

### Device information
* Android device: Oneplus 5T
* Fenix version: 200707

**Comment by Djfe** [comment] 2020-09-15 10:36
yes, please. It could look similar to the purple undo dialogue when you delete a tab.

**Comment by AndiAJ** [comment] 2020-11-03 15:20
Dupe of #2783

**Closed by AndiAJ** 2020-11-03 15:20 UTC
Labels: needs:triage, 🐞 bug
