### ISSUE TITLE
[Bug] Firefox Preview crashing when file picker tries to open

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/fenix#6279] opened 2019-10-25 18:40 UTC
## Steps to reproduce
Open a page with an "attach file" button (signed in twitter or facebook are what I've tried).
Tap the "attach file" button.

### Expected behavior
The file picker should open, and I should be able to attach an image to the tweet or facebook post.

### Actual behavior
Firefox crashes, rather than opening the file picker ui.

### Device information

* Android device: Pixel 3, Android 10
* Fenix version: Nightly 191025 06:21 (Build #12980628)
I had this issue prior to this morning's Fenix Nightly update, unsure what the older build version was.

**Comment by KWierso** [comment] 2019-10-25 18:46
I've also hit this crash trying to upload a file to onedrive.live.com, so it's not just the image picker that's hitting this, it's any file picker, as far as I can tell.

**Comment by pocmo** [comment] 2019-10-25 20:39
Caused by AC issue: https://github.com/mozilla-mobile/android-components/issues/4854

**Comment by pocmo** [comment] 2019-10-28 13:03
Is any release / RC affected so that we'd need to uplift the AC fix?

**Comment by KWierso** [comment] 2019-10-28 16:07
This only started for me three days ago on Nightly, so unless the offending change was upliftedsince then, I doubt it.

I don't have anything other than Nightly installed to prove that, though.

**Comment by AndiAJ** [comment] 2019-10-31 10:25
Hi, **verified as fixed** on the latest **Nightly Build #13040608 from 31/10** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► **Twitter**
✔️ Add profile picture
✔️ Create a tweet containing pictures and videos

► **Instagram**
✔️ Add profile picture
✔️ Share a photo

► **Facebook**
✔️ Add profile picture
✔️ Create a post containing pictures and videos

► **Gmail**
✔️ Attach pictures and videos while composing a new email

**Comment by softvision-oana-arbuzov** [comment] 2019-11-08 11:32
@AndiAJ I was able to reproduce the issue when trying to add photo in a post on Facebook.
![CrashAddPhoto](https://user-images.githubusercontent.com/12184325/68473619-232a1b00-022c-11ea-8b34-a9c8a2cdda18.gif)

**Tested with:**
Browser / Version: Firefox Preview Nightly 191108 06:01 (Build #13120608) 📦: 21.0.0, 09da19708 🦎: 72.0a1-20191105095755
Operating System: Huawei P20 Lite (Android 8.0.0) - 1080 x 2280 pixels, 19:9 ratio (~432 ppi density)

**Comment by sv-ohorvath** [comment] 2019-11-08 12:12
@NotWoods see comment above

**Comment by sv-ohorvath** [comment] 2019-11-11 14:28
> Is any release / RC affected so that we'd need to uplift the AC fix?

v3.0.0-beta 1 is affected.

**Comment by cadeyrn** [comment] 2019-11-11 14:34
The current stable release Fenix 2.3.0 is also affected.

**Comment by pocmo** [comment] 2019-11-11 16:41
Are you able to reproduce that with Nightly?

**Comment by massic80** [comment] 2019-11-11 17:33
I just tested with Nightly 191109 06:20 (Build #13130627) and still got a crash.

**Comment by TitanNano** [comment] 2019-11-13 11:33
https://photos.google.com is also affected by this. https://mail.google.com on the other hand not.

**Comment by NotWoods** [comment] 2019-11-14 00:07
This may be caused by conflicting file providers for downloads and the file picker. The original cause has been resolved but a new crash showed up.

**Comment by NotWoods** [comment] 2019-11-18 18:50
Assigning to @Amejia481 since he's working on a fix for the new crash bug

**Comment by Amejia481** [comment] 2019-11-22 18:35
This should be fixed on nightly

**Comment by KWierso** [comment] 2019-11-22 18:51
Opening the file picker on Facebook in my Firefox Preview Nightly did not crash.

**Comment by massic80** [comment] 2019-11-23 08:24
Same here, on FB

**Comment by massic80** [comment] 2019-11-23 08:43
I confirm for Facebook

**Comment by julienw** [comment] 2019-11-24 12:54
This works on Twitter too now. Thanks for the fix!

**Comment by softvision-miralobontiu** [comment] 2019-11-25 08:53
Verified as fixed on the latest Nightly build 11/25 with Google Pixel 3 (Android Q), and Huawei P9 Lite (Android 7).

**Closed by softvision-miralobontiu** 2019-11-25 08:53 UTC
Labels: b:crash, eng:qa:needed, needs:ac, 🐞 bug

**Comment by SoftVision-PaulOiegas** [comment] 2019-11-26 07:10
> 
> 
> Is any release / RC affected so that we'd need to uplift the AC fix?

Sadly this reproduces also on Release version 2.3.0 (Build #13031728) on my Huawei P30.
 
Experienced the crash on Google desktop website when trying to upload a picture for search and on a market website where I wanted to attach an image for a product review. Might wanna consider that uplift. 😁

**Comment by cadeyrn** [comment] 2019-11-26 07:44
FWIW there was a AC dot release (18.0.1) two weeks ago only for this issue so that a bugfix release for Fenix can be shipped to fix the bug for release users but it never happened. Considering the really large number of reports the last few weeks and that 3.0.0 won't be released before December I still think a bugfix update 2.3.1 should be released.
