### ISSUE TITLE
Fenix doesn't show up in recent apps menu

### ISSUE THREAD

**Issue by PopeRigby** [mozilla-mobile/fenix#3434] opened 2019-06-13 15:27 UTC
# Steps to reproduce
1. Open Fenix
1. Click home (circle) button
1. Click recent apps (square) button

# Actual behavior
Fenix isn't shown

# Expected behavior
Fenix should show up in recent apps menu

# App information
![](https://i.imgur.com/JZImAfB.png)

**Comment by AaronMT** [comment] 2019-06-13 17:12
Which version of Android and launcher are you using?

**Comment by PopeRigby** [comment] 2019-06-13 17:18
Android version: 8.1 Oreo
Launcher: Lawnchair

**Comment by PopeRigby** [comment] 2019-06-13 17:22
It seems to come and go. It was happening earlier and now it's not. It'll probably happen again later.

**Comment by Terryvanderjagt** [comment] 2019-06-14 19:04
I experience the same bug.
Android version: 9
Launcher: Oneplus Launcher

**Comment by sblatz** [comment] 2019-07-20 00:38
I'm closing this as fixed as I'm not able to reproduce and neither can @Terryvanderjagt in the latest build.

@PopeRigby please re-open if you're still having issues 😄

**Closed** 2020-08-26 23:30 UTC
