### ISSUE TITLE
[Bug] “Find in page“ toolbar randomly disappears while searching certain web pages

### ISSUE THREAD

**Issue by oakkitten** [mozilla-mobile/fenix#20216] opened 2021-07-01 12:21 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

When searching certain web pages, the bottom toolbar that is opened when you do “Find in page“ can randomly disappear along with the software keyboard, if any. Here's a demonstration:

https://user-images.githubusercontent.com/1710718/124123219-f369ff80-da6e-11eb-9d83-7b50dab4f02c.mp4

### Steps to reproduce

1. Open this URL: https://livebook.manning.com/book/kotlin-in-action/chapter-11/17
2. Open “Find in page“ and search for various words and tap the Previous match/Next match buttons

### Expected behavior

“Find in page“ toolbar stays until manually dismissed

### Actual behavior

“Find in page“ toolbar disappears by itself

### Device information

* Device vendor / model and Android version: Xiaomi Mi A2 / LineageOS 18.1 (Android 11)
* Firefox for Android version: 91.0a1, Build #2015819211

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16943)

**Comment by Nickoriginal** [comment] 2021-07-01 17:29
Reproducible in Firefox 89.1.1, 90.0.0-beta.6 and Nightly 91.0a1 2021-06-30T17:07:09.023, but Stable and Beta gave me the opportunity to press Previous match/Next match in "Find in page" several times before its closing, while Nightly closes after first pressing instantly.

**Comment by Nickoriginal** [comment] 2021-07-01 20:05
Nightly 2021-07-01T17:41:24.496 have the same behavior as Stable and Beta

**Comment by LaurentiuApahideanSV** [comment] 2021-07-02 16:29
I can confirm the issue is reproducible on Firefox RC 89.1.1 and Nightly 07/01.

### Devices used
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)

**Comment by matteobtt** [comment] 2021-12-05 06:54
It happens on sites that call [`history.replaceState()`](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) during scroll to change the URL. Discourse-based forums like https://discourse.mozilla.org/ also have this problem.

**Comment by oakkitten** [comment] 2022-11-23 16:27
Still an issue in yesterday's Nightly. While we wait and ponder, how about a few raccoon facts?

Fact №1. Raccons are named for their unique hands! Raccoons have some of the most dexterous hands in nature, as anyone who's had a garden, cooler, or garbage can broken into by one of them knows. Native Americans were the first to note their unusual paws. The English word raccoon comes from the Powhatan word [aroughcun](http://www.pbs.org/wnet/nature/raccoon-nation-raccoon-fact-sheet/7553/), which means "animal that scratches with its hands." The Aztecs went in a similar direction when naming the raccoon. They named it [mapachitli](https://books.google.com/books?id=L-G-DgAAQBAJ&pg=PA148&lpg=PA148&dq=mapache+Aztecs+one+who+takes+everything+in+its+hands+raccoon&source=bl&ots=H_rBE5X95D&sig=XPxRi-vuHzxV1tq59jSk_qjFbEk&hl=en&sa=X&ved=0ahUKEwi-4ZaV5e7YAhUD9IMKHQggCYYQ6AEIPzAG#v=onepage&q=mapache%20Aztecs%20one%20who%20takes%20everything%20in%20its%20hands%20raccoon&f=false) or "one who takes everything in its hands." Today mapache means "raccoon" in Spanish.

**Comment by csadilek** [comment] 2022-12-22 20:52
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807145

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by csadilek** 2022-12-22 20:52 UTC
Labels: 🐞 bug, Feature:FindBar, needs:triage, qa-triaged
