### ISSUE TITLE
FNX-4886 ⁃ In-app Page Support for Dark Content

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1227] opened 2019-03-27 17:22 UTC
As a user, I want to view Fenix pages in dark mode when my browser displays web content in dark mode using the `prefers-color-scheme` CSS specification. 

### Acceptance Criteria (Added by PM)
I can do …  (e.g. add a bookmark)
I can do …   (e.g. track usage)

**Comment by vesta0** [comment] 2019-03-28 22:07
duplicate of #1164

**Closed** 2020-08-11 06:05 UTC
