### ISSUE TITLE
[Bug] There is bug in synchronized. It shows last synchronized in 1970. 

### ISSUE THREAD

**Issue by Ansarmughal99** [mozilla-mobile/fenix#17659] opened 2021-01-27 14:19 UTC
[comment]: #When try to synchronized. It shows error with last synchronized on 1 Jan 1970

### Error in synchronizing and login 
![Uploading Screenshot_20210127_101026_org.mozilla.firefox.jpg…]()

### Honor 8x

* Android device:  yes
* Fenix version: ? 85.1.0

**Comment by amedyne** [comment] 2021-01-27 14:22
@Ansarmughal99 Can you re-attach the screenshot please? Also, can you provide the make, brand and model and Android version of the device you are using?

**Comment by Dynamith** [comment] 2021-01-30 15:36
@amedyne I have the same issue on XiaomiPad4 with Mokee of Android 9. But it can operate normally on OnePlus8T with H2OS of Andriod 11.
![1da3c07cdf30107455d4d787724bb2f](https://user-images.githubusercontent.com/64576195/106360523-c4325380-6353-11eb-83fc-162ab8600ec8.jpg)

**Comment by sflorean** [comment] 2021-03-31 14:50
Closing as dupe of #7784, your scenario will be tested when the issue is fixed. Thank you for filing this!

**Closed by sflorean** 2021-03-31 14:50 UTC
Labels: Feature:Sync, 🐞 bug
