### ISSUE TITLE
[Bug] Sharing image shares URL, not the image

### ISSUE THREAD

**Issue by davidegts** [mozilla-mobile/fenix#17613] opened 2021-01-24 20:14 UTC
## Steps to reproduce

1. Open an image in a tab in Firefox for Android
2. Hit the 3-dot menu --> Share --> share to an app that would accept images (like Hangouts, Signal, etc.)

### Expected behavior
Image shows up for sharing (this used to work and currently works this way with Chrome for Android)

### Actual behavior
URL for image shows up for sharing

### Device information

* Android device: Pixel 4a
* Fenix version: 84.1.4

**Comment by Dunexus** [comment] 2021-01-24 23:02
Duplicate of https://github.com/mozilla-mobile/fenix/issues/12414

**Comment by mcarare** [comment] 2021-01-25 09:43
Closing as duplicate.

**Closed by mcarare** 2021-01-25 09:43 UTC
Labels: needs:triage, 🐞 bug
