### ISSUE TITLE
Add search option in bookmarks.

### ISSUE THREAD

**Issue by SureshCBE** [mozilla-mobile/fenix#20849] opened 2021-08-14 04:25 UTC
Hi,
Every time i need to scroll and select a particular bookmark from many bookmarks. So i request you to add search option for find a particular bookmark quickly.

**Comment by cadeyrn** [comment] 2021-08-15 18:59
Duplicate of #12717.

**Comment by amedyne** [comment] 2021-08-17 17:46
Closing this as duplicate of #12717.

**Closed by amedyne** 2021-08-17 17:46 UTC
Labels: needs:triage
