### ISSUE TITLE
still get "Display already acquired" crash (only private mode; with STR)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#897] opened 2019-03-07 18:50 UTC
Looks like "Display already acquired" should be fixed by #706. The fix landed on March 4th. My Fenix build is from March 5th and it crashes after opening a link from WhatsApp.

```
2019-03-07 19:38:34.778 13678-13678/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 13678
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity}: java.lang.RuntimeException: Failed to call observer method
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5035)
        at android.app.ActivityThread.-wrap18(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1655)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:180)
        at android.app.ActivityThread.main(ActivityThread.java:6950)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
     Caused by: java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:225)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:193)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:184)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:355)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:293)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:333)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:138)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:124)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2576)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:921)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1233)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1299)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2619)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2585)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2574)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:921)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1233)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1299)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2619)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2585)
        at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:258)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:533)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:179)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1385)
        at android.app.Activity.performStart(Activity.java:7003)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2873)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5035) 
        at android.app.ActivityThread.-wrap18(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1655) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:180) 
        at android.app.ActivityThread.main(ActivityThread.java:6950) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835) 
     Caused by: java.lang.IllegalStateException: Display already acquired
        at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:1802)
        at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:360)
        at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:323)
        at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:56)
        at mozilla.components.feature.session.EngineViewPresenter.renderSession$feature_session_release(EngineViewPresenter.kt:51)
2019-03-07 19:38:34.779 13678-13678/org.mozilla.fenix.debug E/AndroidRuntime:     at mozilla.components.feature.session.EngineViewPresenter.start(EngineViewPresenter.kt:31)
        at mozilla.components.feature.session.SessionFeature.start(SessionFeature.kt:27)
        at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.start$support_base_release(ViewBoundFeatureWrapper.kt:157)
        at mozilla.components.support.base.feature.LifecycleBinding.start(ViewBoundFeatureWrapper.kt:193)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:215)
        	... 36 more
2019-03-07 19:38:34.781 1736-2144/? E/ActivityManager: App crashed! Process: org.mozilla.fenix.debug
```

### Device information

* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 8b793cd43ea0b816fece4266c2dbc990e24ceae1

**Comment by cadeyrn** [comment] 2019-03-07 19:05
I updated to the latest version from master (revision 9ea5a02b8212e186fd42468709f1b853d4758b47) and it still crashes. The good news: I have STR which crashes in 100% for me:

1. Start Fenix
2. Switch to private mode
3. quit Fenix via the Android "Recent Apps"
4. click on a link via an external app, for example WhatsApp

Steps 2 and 3 are important: The crash only happens if Fenix is in private mode and only after quitting Fenix via Recent Apps.

**Comment by sblatz** [comment] 2019-03-20 19:55
Haven't had a chance to look at this yet. I will un-assign in case someone has time to tackle it.

**Comment by colintheshots** [comment] 2019-03-20 20:40
Well, fix #706 was only a workaround to avoid crashing by not setting the theme when it was already set correctly. I can maybe pick this up when I have some of my Bookmarks code checked in.

**Comment by kbrosnan** [comment] 2019-03-22 18:29
Sentry issue: [FENIX-57](https://sentry.prod.mozaws.net/operations/fenix/issues/5319054/)

**Comment by cadeyrn** [comment] 2019-04-02 21:17
I can no longer reproduce.

**Comment by sblatz** [comment] 2019-04-03 20:36
I'm still able to reproduce this if the app I'm opening from is _not generating a custom tab_

**Comment by ekager** [comment] 2019-04-08 23:55
I looked into this a bit today. The root cause seems to be that private mode is not the default theme, so in HomeActivity onCreate when we are applying the private theme for the first time on activity start up, we need to recreate the app to apply the new theme so onCreate is called twice when sending a View intent in private mode. Then I believe the session is in some half created (or fully created state) when we try to create it again, causing the crash.

**Comment by ekager** [comment] 2019-04-09 19:56
@cadeyrn are you able to reproduce in master anymore? A fix landed yesterday that I think should fix this.

**Comment by cadeyrn** [comment] 2019-04-09 20:10
No, I can no longer reproduce.

**Comment by sv-ohorvath** [comment] 2019-04-10 12:32
Verified as fixed on Master. Devices: Samsun S8(Android 9).

**Closed by sv-ohorvath** 2019-04-10 12:32 UTC
Labels: P1, QA needed, 🐞 bug, 💥 crash
