### ISSUE TITLE
[Homescreen] Match Android notifications gesture to swipe to delete gesture on Open tabs

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#3747] opened 2019-06-28 03:04 UTC
## Steps to reproduce

Swipe to close tabs. 

### Expected behavior

 Use the same swipe sensitivity as is used in Android notifications

### Actual behavior

Right now the swipe to delete gesture is is too hard to perform and it's hard to actually close tabs.

The change in  #3135 introduced this.

### Device information

* Android device: Pixel 2
* Fenix version: latest

**Comment by kbrosnan** [comment] 2019-06-28 04:26
Dupe of #3738

**Closed by kbrosnan** 2019-06-28 04:26 UTC
Labels: 🐞 bug

**Comment by yoasif** [comment] 2019-06-28 04:30
This isn't a dupe of #3738 -- that bug asks to be able to "close and next" - I'm simply asking for an improvement to the close gesture.
