### ISSUE TITLE
[Bug] Back Button does not work on UBO->logger

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13380] opened 2020-08-07 07:03 UTC
## Steps to 
Open UBO on a page and click on logger
Click back
### Expected behavior
Home screen opens
### Actual behavior
Nothing
### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix

**Comment by csadilek** [comment] 2020-08-07 13:49
Dupe of https://github.com/mozilla-mobile/fenix/issues/8771.

**Closed by csadilek** 2020-08-07 13:49 UTC
Labels: needs:triage, 🐞 bug
