### ISSUE TITLE
[Bug] Tiny font on URL bar on some devices

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#5358] opened 2019-09-16 13:06 UTC
## Steps to reproduce
1. Open a tab. Check the URL bar.
2. Tap the URL to edit. Check the font size.
3. Clear the URL text and observe the placeholder text.
### Expected behavior
The text has the default font of the device.
### Actual behavior
The URL text is very tiny, unreadable.
### Device information

* Android device: Samsung Tab A6 (Android 5.1.1), 
Not reproducing on: Xiaomi MiPad 2 (Android 5.1), Nexus 5 (Android 6)
* Fenix version: Nightly 9/16

![screencap](https://user-images.githubusercontent.com/4037709/64960405-e7ae4880-d89b-11e9-8ad5-87da6ba4e323.png)

**Comment by pocmo** [comment] 2019-09-16 17:22
Duplicate of https://github.com/mozilla-mobile/fenix/issues/5344

**Closed by pocmo** 2019-09-16 17:22 UTC
Labels: a-c, 🐞 bug
