### ISSUE TITLE
Issue with downloading PDF files

### ISSUE THREAD

**Issue by Rouse-A** [mozilla-mobile/fenix#6184] opened 2019-10-22 14:04 UTC
Use Firefox Preview on an Android phone to visit a site from which you can download a PDF file. The notification bar shows it downloading

The notification bar pull-down shows the name of the file, from which it should open in the default PDF reader app. 

However, instead it opens a directory of the phone's memory. You can scroll down to the Download folder, but the newly-downloaded file isn't at the top. If you scroll down to it then you can open it. 

OnePlus 2 running Android 9

**Comment by BranescuMihai** [comment] 2019-10-25 16:19
Might need a bit of help from UX, I looked in the code and seems like for now this is the way it's designed, just open Downloads folder for every time of file ([Issue referencing this](https://github.com/mozilla-mobile/fenix/issues/4525)). Should this be a to-do feature in the [A-C : Download Manager backlog](https://github.com/orgs/mozilla-mobile/projects/34) ?

**Comment by NotWoods** [comment] 2019-10-25 19:14
Duplicate of #5959. The download notification is being redesigned with these changes (and more).

**Closed by NotWoods** 2019-10-25 19:14 UTC
Labels: a-c, needs:UX-feedback, 🐞 bug
