### ISSUE TITLE
FNX-4326 ⁃ [Bug] Fenix is stuck after a few second

### ISSUE THREAD

**Issue by ValentinTimisica** [mozilla-mobile/fenix#10494] opened 2020-05-07 14:38 UTC
## Steps to reproduce
* Open Fenix
* Open fast the 3 dot menu
* Wait a few second (I waited around 10 second)
* Press outside the menu

### Expected behavior
* The app works without issues.

### Actual behavior
* The app is stuck. You can only select the items from the menu (check the video below).

### Device information
* Android device: Samsung Galaxy Note 10 (Android 10)
* Fenix version: latest master

### Additional info
* Very similar to #10110 and #10488. It may be the same problem.
* After I tested a few times I noticed that is 100% reproducible if you tap fast on the 3 dot menu after you opened the app. In case you wait a few seconds (let's say 10s) before opening the menu the bug will not reproduce.
* I don't know if it's related, but I was already logged in.
* [Video](https://drive.google.com/file/d/1anaoCIPtZmSobGZPvIOnIF6nIRHCwIjg/view?usp=sharing)

**Comment by ekager** [comment] 2020-05-07 16:09
I just saw this and it's quite disruptive.

**Comment by ValentinTimisica** [comment] 2020-05-13 12:03
After further investigation I found out that you need to be logged in to reproduce the bug.
I discovered that commenting the code inside [onAuthenticated](https://github.com/mozilla-mobile/fenix/blob/1e83f54a942efe8bc866da1ad67be6794f324701/app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt#L183) will no longer reproduce the bug.

Another interesting thing is that if you open the app and don't press the 3 dot menu 3 callbacks related to FxaAccount will be triggered:
1) in `HomeMenu.kt` - [line](https://github.com/mozilla-mobile/fenix/blob/1e83f54a942efe8bc866da1ad67be6794f324701/app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt#L183)
2) in `Mode.kt` - [line](https://github.com/mozilla-mobile/fenix/blob/6c38b773151e1c17a8016d851407bb3cd7de4ef9/app/src/main/java/org/mozilla/fenix/home/Mode.kt#L75)
3) in `HomeFragment.kt` - [line](https://github.com/mozilla-mobile/fenix/blob/f7b4f1c9594bc6e942941252d7539e4649f76aef/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L417)

If you open the app and press fast the 3 dot menu (in order to reproduce the bug), only the callback from `HomeMenu.kt` will be triggered. After commenting this line, 2 and 3 triggers.

Checked [notifyObservers](https://github.com/mozilla-mobile/android-components/blob/e39b6af4a197a6800c070679459a6dac04f1f744/components/support/base/src/main/java/mozilla/components/support/base/observer/ObserverRegistry.kt#L134) method and seems like if you press the 3 dot menu, it will not notify the same observers as when you open the app and don't press anything.

You can check this log to see what observers are notified in each case:
1) When you don't press the 3 dot menu

```
Same observers
...
mozilla.components.service.fxa.sync.SyncManager$PassThroughSyncStatusObserver@f80bdeb
mozilla.components.service.fxa.manager.FxaAccountManager$SyncToAccountsIntegration@13aef34
org.mozilla.fenix.components.AccountAbnormalities@fd57ad2
org.mozilla.fenix.home.HomeMenu$4$1@225eaff
org.mozilla.fenix.home.CurrentMode@2e9922a
org.mozilla.fenix.home.HomeFragment$onStart$1$1@a2a4db8
mozilla.components.service.fxa.manager.FxaAccountManager$AccountsToSyncIntegration@6e0c207
org.mozilla.fenix.components.TelemetryAccountObserver@131e15d
org.mozilla.fenix.components.AccountAbnormalities@fd57ad2
org.mozilla.fenix.home.HomeMenu$4$1@225eaff
org.mozilla.fenix.home.CurrentMode@2e9922a
org.mozilla.fenix.home.HomeFragment$onStart$1$1@a2a4db8
```
2) When you press the 3 dot menu
```
Same observers
...
org.mozilla.fenix.components.AccountAbnormalities@7ce3c82
org.mozilla.fenix.home.HomeMenu$4$1@60024fc
mozilla.components.service.fxa.sync.SyncManager$PassThroughSyncStatusObserver@baf9d8d
mozilla.components.service.fxa.manager.FxaAccountManager$SyncToAccountsIntegration@66a6f6
```

I hope this helps solving the issue.

**Comment by astarq** [comment] 2020-05-22 15:24
This has been happening for me occasionally for about a month. Sometimes the triple dot menu doesn't close when I open bookmarks or settings from it 🤔

**Comment by grigoryk** [comment] 2020-05-22 17:51
This reproduces reliably for me.

**Comment by grigoryk** [comment] 2020-05-22 18:54
Problem was that we were trying to process menu changes (in response to account manager events) on some background thread as that's what account manager emits them on, so some code internally in PopupWindow's dismiss handling was silently giving up and we'd get into a bad state.

The reason this seemingly only happened if you quickly opened a menu on startup is because account manager isn't initialized until sometime after the startup finished. So the trick was to open the menu (and register account manager state callbacks) _before_ it got initialized, so that the callbacks are invoked.

This should also reproduce in other, much more obscure ways, e.g. if you open the menu right before sync is scheduled to run in the background, change FxA password on another connected client, and then eventually receive a `onAuthenticationProblem` callback.

Patch incoming.

**Comment by astarq** [comment] 2020-05-22 18:58
Thanks for explaining, I suppose this thread can be closed now 🙂

**Comment by grigoryk** [comment] 2020-05-22 18:59
Once we land the patch and verify that it is, indeed, fixed :)

**Comment by astarq** [comment] 2020-05-22 19:00
Great!

**Comment by grigoryk** [comment] 2020-05-25 22:06
@ValentinTimisica #10863 should be on nightly by now, can you verify that this doesn't happen anymore? Thanks :)

**Comment by ValentinTimisica** [comment] 2020-05-26 06:35
Tested and it doesn't stuck anymore for me but I saw that the 3 dot menu is automatically dismissed after a few seconds. @grigoryk is this intended?

Adding the QA label for an extra check.

**Comment by ekager** [comment] 2020-05-26 13:49
Yeah @grigoryk mentioned in the #10863
> One "problem" this introduces is that if you open the menu right after the startup, it will be dismissed in a few seconds (as account manager is initialized). Fixing that will require changes to a-c, so I'll leave that to a follow-up.

Is there an AC bug open for this Grisha?

**Comment by ValentinTimisica** [comment] 2020-05-26 13:55
Thanks @ekager, I missed this info when I tested earlier. That means it works well for me now.

**Comment by grigoryk** [comment] 2020-05-26 16:59
Thanks, @ValentinTimisica ! I'll close this issue for now then.

**Comment by Diana-Rus** [comment] 2020-06-10 11:32
Hi, issue is fixed, i cannot reproduce it, checked with Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL (Android 9) on Beta 5.2.0-beta.1 GV:78.0

**Closed** 2020-08-11 00:54 UTC
Labels: Feature:HomeScreen, Feature:MainMenu, S1, eng:qa:verified, eng:ready, help wanted, 🐞 bug
