### ISSUE TITLE
FNX3-16628 ⁃ [Bug] Switch to tab snack bar no longer appears

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2858] opened 2019-05-25 21:02 UTC
## Steps to reproduce
1. Open a webpage
1. Long press a link
1. Tap open in new tab

### Expected behavior
Fenix should display a snack bar notification that offers to switch to the new tab

### Actual behavior
Nothing

### Device information
* Android device: Android 8, LG G6
* Fenix version: 1.0.1921

**Comment by vesta0** [comment] 2019-05-30 22:55
This seems to be a regression.

**Comment by softvision-miralobontiu** [comment] 2019-06-03 11:33
Verified as fixed on build 1.0.1922 (#11530616), with Samsung Galaxy Tab S3 (Android 8(, Nokia 6 (Android 7.1.1), and Motorola Moto G6 (Android 8).

**Closed** 2020-08-12 17:41 UTC
Labels: Feature:Tabs, Release Blocker, eng:qa:verified, 🐞 bug
