### ISSUE TITLE
Add "Search for selected text" to context menu

### ISSUE THREAD

**Issue by crabel** [mozilla-mobile/fenix#5188] opened 2019-09-10 09:56 UTC
### Why/User Benefit/User Problem
It is a very common usecase for me to search for terms I find on webpages. Currently I have to select the text, copy it and paste it into the address bar or a search box.

I believe that it would be a really useful feature to be able to search directly.

### Acceptance Criteria (how do I know when I’m done?)
The user selects a text and the context menu shows a menu entry "search for ...". Clicking the menu entry opens a new tab (same tab?) with the url of the search provider. The selected text is used as the search term.

**Comment by Brandon-Davison** [comment] 2019-09-12 02:15
Could I work on this?

**Comment by Lululalu** [comment] 2019-10-01 20:36
I believe it's the same as #5695

**Comment by NotWoods** [comment] 2019-12-23 07:55
Yup, duplicate of #5695

**Closed by NotWoods** 2019-12-23 07:55 UTC
Labels: 🌟 feature request
