### ISSUE TITLE
[Bug] Closing private tabs running PiP videos from notification panel

### ISSUE THREAD

**Issue by botistreamer** [mozilla-mobile/fenix#20097] opened 2021-06-20 09:06 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open any video in **private tab**
2. Put that video in full screen.
3. Put video in Picture in Picture (PiP mode) by pressing on home button.
4. From notification panel, click on "Close private tabs"

Note: seems related to #18727

### Expected behavior
PiP window dissappears. (This is the behavior in [Bromite](https://www.bromite.org/) a chromium based browser)
### Actual behavior
Bugged PiP window remains on screen. 
![demo](https://user-images.githubusercontent.com/47123395/122668398-84221f00-d1d5-11eb-98ab-4ae2e98b455d.jpg)
_I couldn't take screenshots or screen recording since PiP window appears blank while screen recording._
_Bugged PiP window looks like the one from the issue mentioned above. Screenshot from mentioned issue._
### Device information

* Device vendor / model and Android version: Poco X3, Android 11, ArrowOS 
* Firefox for Android version: 89.1.1

**Comment by jonalmeida** [comment] 2021-06-21 15:22
Duplicate of https://github.com/mozilla-mobile/fenix/issues/18727

**Closed by jonalmeida** 2021-06-21 15:22 UTC
Labels: Feature:Media, Feature:PrivateBrowsing, 🐞 bug
