### ISSUE TITLE
[Bug]: grey bar at the bottom of images after scrolling down in landscape

### ISSUE THREAD

**Issue by JamesG3D** [mozilla-mobile/fenix#24072] opened 2022-03-03 04:11 UTC
### Steps to reproduce

1. in a website that has an image
2. long press image
3. Select 'open image in a new tab'
4. rotate to landscape orientation if not already
5. zoom image until able to scroll down
6. scroll down
7. there is a grey bar at the bottom of the screen, the same height as the url bar
![Screenshot_20220303-165539_Firefox](https://user-images.githubusercontent.com/8207645/156494655-f7e28d35-e9ac-4c5d-aefa-475fbd57ebca.jpg)

### Expected behaviour

the image should fill the available screen space, and there should not be a grey bar at the bottom

### Actual behaviour

there is a grey bar at the bottom of the image in landscape mode after zooming in and scrolling down

### Device name

Samsung Galaxy S20 ultra 5G

### Android version

12

### Firefox release type

Firefox

### Firefox version

97.2.0 (Build #2015863827), fc8bbf84c+ AC: 97.0.12, ce42514f73 GV: 97.0.1-20220216172458 AS: 87.1.0

**Comment by delia-pop** [comment] 2022-03-03 15:07
Hi @JamesG3D,
Thank you for your report!

I can confirm the issue you described is reproducible.
Tested and reproduced on the latest Nightly 99.0a1(from 03/03), RC 97.2.0 and GVE.
Device used: Google Pixel 6 (Android 12), Motorola Moto G30 (Android 11).

Since this issue is also present on GVE, I will close this ticket and move it to Bugzilla, where you can follow the progress.

**Comment by delia-pop** [comment] 2022-03-03 15:10
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1757945

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by delia-pop** 2022-03-03 15:10 UTC
Labels: 🐞 bug, Feature:Toolbar, S3, needs:triage, qa-triaged
