### ISSUE TITLE
[Bug]: Audio player controls disappear immediately

### ISSUE THREAD

**Issue by hebu** [mozilla-mobile/fenix#24016] opened 2022-02-27 22:37 UTC
### Steps to reproduce

Open a URL that directs to an audio file (e.g. mp3 file).

### Expected behaviour

The audio player is shown with it's play/pause, volume and play position controls.

### Actual behaviour

The GUI of the audio player disappears very shortly after the playback starts and an empty gray box is left. The audio is played, but you can't interact with it as the controls have disappeared.

### Device name

Huawei P10 Lite

### Android version

Android / EMUI 8.0.0

### Firefox release type

Firefox

### Firefox version

97.2.0

### Additional information

Screen recording:

https://user-images.githubusercontent.com/5539230/155902789-88974aed-01c1-4139-9b51-bded9efee8dc.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19668)

**Comment by delia-pop** [comment] 2022-03-02 10:37
Hello @hebu,

Thanks for the report!

I tested the flow, but I was not able to reproduce the issue. The audio player is properly displayed and works as expected.

![Screenshot_20220302-115724](https://user-images.githubusercontent.com/89388888/156345063-aa081626-48e7-4d59-ae42-2404510dc8f5.png)

Can you please re-test the issue on the latest Firefox Nightly and Firefox Beta builds and let me know if you are still able to reproduce it? And if so, please also provide the URLs on which you encounter this issue.

Tested on the latest Nightly from 02/03, RC 97.2.0, GVE and Chrome.
Devices used: Huawei P9 Lite (Android 8), Google Pixel 6 (Android 12).

**Comment by hebu** [comment] 2022-03-02 20:47
Hi @delia-pop 

I tried once again in the same browser and the problem has disappeared as suddenly as it had appeared. I'm not sure what has changed in the meantime. So I think, the bug ticket can be closed.

Best wishes
HeBu

**Comment by hebu** [comment] 2022-03-13 19:05
I have to reopen this issue. Sometimes the player controls are there, sometimes they're gone....

**Comment by hebu** [comment] 2022-03-13 19:13
It is independent of the URL ... but here are some examples:

- https://srv-2.pdcst.space/wrint/wrint.de/WR1333_Mehr_Flaschen_aus_Sizilien.mp3
- https://www.dosgameclub.com/wp-content/uploads/2022/02/ep64.mp3
- https://meinscrumistkaputt.de/wp-content/uploads/folge-109-agile-dokumentation.mp3?ptm_source=download&ptm_context=select-button&ptm_request=a1111ee5c658&ptm_file=folge-109-agile-dokumentation.mp3

There's also no difference whether you share the URL from an app, copy it via clipboard or open it from a website.

**Comment by hebu** [comment] 2022-04-23 08:16
https://user-images.githubusercontent.com/5539230/164886402-021d3a18-3c5b-4176-8d8e-9e2f852f97c3.mp4

Next level ... the player disappears completely (but still plays back and you can long-tap to download the file).

Firefox 99.2.0 (Build #2015874211), 3fbd94a59+
AC: 99.0.10, 2cf4dbe50f
GV: 99.0.1-20220411174855
AS: 91.1.1

**Comment by hebu** [comment] 2022-11-19 21:37
Still reproducable.

107.1.0 (Build #2015915067), a4c625827+
AC: 107.0.7, 7d69de3da4
GV: 107.0-20221110173214
AS: 94.2.2

**Comment by delia-pop** [comment] 2023-01-17 14:58
Hi, @hebu. Are you still experiencing this issue? I am still unable to reproduce it on the latest Nightly 111.0a1 from 01/17 with Xiaomi 12 Pro (Android 13). The audio player controls are displayed correctly on the links mentioned above. 
 
https://user-images.githubusercontent.com/89388888/212932319-b6d88b82-84b6-4e7b-be57-df4415711019.mp4

**Comment by jonalmeida** [comment] 2023-01-30 20:52
@hebu yes, please report a bug with the addon provider. Closing as not reproducible.

**Closed by jonalmeida** 2023-01-30 20:52 UTC
Labels: 🐞 bug, Feature:Media, S3, qa-triaged
