### ISSUE TITLE
Fenix inserting text unexpectedly into text input

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/fenix#6838] opened 2019-11-27 16:02 UTC
## Steps to reproduce

1. Install Fenix on a fresh Samsung Galaxy S5 phone
2. Go to any web form on Fenix, like FxA sign in
3. Type an email address

### Expected behavior
* Email address can be typed

### Actual behavior
* On the second character after the @ symbol, the previously entered characters are pasted. This is strange because this is a fairly fresh Android install and the keyboard preferences were reset.
<img width="251" alt="image" src="https://user-images.githubusercontent.com/68213/69739099-1c911400-1105-11ea-9884-a7396c4db193.png">

I could reproduce this on other websites, but not in the other Samsung "Internet" browser.

### Device information

* Android device: Samsung Galaxy S3
* Fenix version: Latest

**Comment by jonalmeida** [comment] 2019-11-28 20:31
@ryanfeeley Did some more digging into this. It seems like it's related to predictive text being on, but didn't affect Samsung's Browser.

**Comment by makotokato** [comment] 2019-11-30 06:08
@ryanfeeley What IME/keyboard do you reproduce this?

**Comment by ebalazs-sv** [comment] 2020-05-21 13:31
Hi!
This issue is reproducible on the latest Fenix Nightly from 5/21, Fenix Beta 5.1.0-beta.1 from 5/19,  Fenix Release 5.0.0 from 4/30 with Samsung Galaxy Tab S3 (Android 8). 
Steps to reproduce:
1. Go to Settings - Turn on Sync
2. In the address field type an email address;
3. Delete some characters and retype the email address;

Step 3 must be done multiple times to reproduce this issue.

Expected result:
The email address is typed in the address field as you type.

Actual result:
The inserted characters are duplicated after deleting some characters and then retyping them, multiple times.

![20200521_161802](https://user-images.githubusercontent.com/48799384/82563383-a9320180-9b7f-11ea-8528-b005bdab10c5.gif)

Looks like a duplicate of the issue https://github.com/mozilla-mobile/fenix/issues/4208.
I will remove the qa:needed unti further notice.

**Comment by Poopooracoocoo** [comment] 2020-05-25 06:40
oh hey another s5!

**Closed** 2021-02-11 22:55 UTC
Labels: Feature:Browsing, P2, needs:gv, wontfix, 🐞 bug
