### ISSUE TITLE
[Bug]Open in external app not available for embedded YouTube

### ISSUE THREAD

**Issue by superbonaci** [mozilla-mobile/fenix#18304] opened 2021-03-03 07:42 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Go to this website and try to open embedded YouTube video in native Android app:
https://screenrant.com/super-mario-64-fps-parody-speedrunning-sensation/amp/

![](https://i.imgur.com/mLt8L5x.jpg)

### Expected behavior
Show option

### Actual behavior
Does not show option.

### Device information

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)
Galaxy S10 with Android 11.
```
Firefox Nightly is produced by Mozilla.
Nightly 210302 17:01 (Build #2015796363)
AC: 74.0.20210301143120, 8a55899f2
GV: 88.0a1-20210301093612
AS: 72.1.0
Tuesday 3/2 @ 5:06 PM
```

**Comment by LaurentiuApahideanSV** [comment] 2021-03-03 13:08
This is duplicate of https://github.com/mozilla-mobile/fenix/issues/18223. I will mark this issue as closed as it will be handled there.

**Closed** 2021-03-03 13:08 UTC
Labels: qa-triaged, 🐞 bug
