### ISSUE TITLE
Concept of "Master Password" in Firefox mobile edition to stop non-admin users from viewing saved login credential.

### ISSUE THREAD

**Issue by PranavBhattarai** [mozilla-mobile/fenix#17090] opened 2020-12-17 06:24 UTC
Humans share their smartphones due to various reasons. Since not everyone owns a device to play with.
If u don't give them a phone, they might think u might have something bad running in the phone, or might take this as egotistic behavior. So you have to give your device depending on different circumstances one might experience.
The problem with this dilemma is **privacy**. You can trust your family members, relatives, close friends but every time there a question might pop in your brain like, "**what if**".

Currently, FF asks for a user fingerprint or pin to control who can and who can't view saved logins, which is nice but not enough. This can be still too dangerous in day-to-day "family" life. A new fingerprint can be added easily, password pin can be shared with the person whom you are giving your phone for many reasons/circumstances.

The only nice solution toward this issue is the concept of **[MASTER PASSWORD](https://imgur.com/oN1mrIp)** we see the Firefox desktop version.
This is great. 

[Anyone trying to go see **about:logins** will require a master password to see the content](https://imgur.com/WKY8WTY). I think this concept should be on Firefox mobile version too.

By **keeping** the current mechanism, there should be an alternative option that blocks people from viewing saved logins.

**Comment by cadeyrn** [comment] 2020-12-17 08:00
Duplicate of #14501 and #15147.

**Comment by PranavBhattarai** [comment] 2020-12-17 12:04
@cadeyrn This is bad news. Ignoring major issue which can be technically solved using Master Password.
@liuche Please rethink this scenario and open the #14501 issue.

**Comment by ekager** [comment] 2020-12-17 18:54
We will not be adding support for master password re this comment https://github.com/mozilla-mobile/fenix/issues/14501#issuecomment-683888369

**Closed by ekager** 2020-12-17 18:54 UTC
Labels: Feature:Logins, feature request 🌟
