### ISSUE TITLE
[Bug] Wrong copy is seen when there are no synced tabs or devices

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#11499] opened 2020-06-12 01:21 UTC
## Steps to reproduce
1. Sign-in to Sync.
1. Do not have other Sync devices.
1. Open Sync Tabs UI.

### Expected behaviour
* The copy to tell me to sign-in on other devices should be there (as per [these designs](https://app.abstract.com/share/cb14ade9-a5a1-4ca9-8012-4350363cf5b4?collectionId=4d5f57be-0965-4faa-8ed4-8635c1f16660&collectionLayerId=abff443a-93d9-4dd1-a95a-93dbc135beb1&present=true&preview=false&sha=91ef9094d50e98eec299dbf1fb1f2d8783e2898a)).

![](https://user-images.githubusercontent.com/1370580/84454432-8055d700-ac28-11ea-8466-17ebc00d61db.png)

### Actual behaviour
* We show the text, "Connect another device.".

### Device information
* Android device: Android 10, Pixel 4
* Fenix version: Nightly, 10/06/20

**Comment by ekager** [comment] 2020-06-12 03:31
prelanding strings in https://github.com/mozilla-mobile/fenix/pull/11503

**Comment by sflorean** [comment] 2020-08-04 16:11
Tested on Nightly 8/4 and
- for **No tabs opened on other devices**: "You don't have any tabs open in Firefox on your other devices" is displayed.
- for **No other devices connected**: "Connect another device" message is displayed. 

@BranescuMihai looking at the description seems that the issue is still reproducible. ref #https://github.com/mozilla-mobile/fenix/issues/11499#issue-637419220.

**Comment by sflorean** [comment] 2020-08-12 08:41
> Tested on Nightly 8/4 and
> 
> * for **No tabs opened on other devices**: "You don't have any tabs open in Firefox on your other devices" is displayed.
> * for **No other devices connected**: "Connect another device" message is displayed.
> 
> @BranescuMihai looking at the description seems that the issue is still reproducible. ref #[#11499 (comment)](https://github.com/mozilla-mobile/fenix/issues/11499#issue-637419220).

@BranescuMihai could you please add your input regarding the above results?

**Comment by sflorean** [comment] 2020-09-16 11:27
Closing this as verified, since if we don't have other sync devices, the "Connect another device" is correct from our point.

**Closed by sflorean** 2020-09-16 11:27 UTC
Labels: Feature:SyncTabs, Skittle, eng:ready, help wanted, 🐞 bug
