### ISSUE TITLE
[Bug] Edit Bookmark not showing error state when URL is empty

### ISSUE THREAD

**Issue by joc-a** [mozilla-mobile/fenix#15508] opened 2020-09-28 19:18 UTC
## Steps to reproduce

1. Have a bookmark saved
2. Edit bookmark -> clear name and URL -> click save -> you will see that nothing changes in the name and URL
3. Edit bookmark -> clear the name -> click save -> you will see that the name now becomes the same as the URL (I think this behavior is fine, but please correct me if I'm wrong)
4. Edit bookmark -> clear the url -> click save

The above steps are displayed in the video attachment.

### Expected behavior
After steps 2 and 4, we should not be able to save an empty URL in a bookmark. The Save icon on the top right should be disabled when the URL is in the error state.

### Actual behavior
We can save an empty URL in a bookmark. The Save icon remains enabled and after pressing it, the password field briefly shows a red error icon in its error state before leaving the Edit Bookmark screen.

### Device information

* Android device: Samsung A50, Android 10
* Fenix version: 81.1.1

![Edit Bookmark Bug](https://user-images.githubusercontent.com/38375996/94475624-05fd9280-01d8-11eb-9a8d-8f21686bfb00.gif)

I'd be happy work on this when it gets UX feedback 🙂

**Comment by s-ankur** [comment] 2020-09-28 20:14
I think it is a duplicate of https://github.com/mozilla-mobile/fenix/issues/14450, not sure

**Comment by joc-a** [comment] 2020-09-28 20:24
@s-ankur oh it's not crashing with me, it's just not showing the error state, but these two issues are related

**Comment by ekager** [comment] 2020-09-28 22:30
Looking at the code it looks like we currently do allow the title to be empty, but not the URL. We should definitely be showing an error on empty URL at least and looks like we have an error string: `bookmark_invalid_url_error`. Let's figure out why that isn't working and make sure you can't submit a blank or invalid URL!

**Comment by ebalazs-sv** [comment] 2020-11-19 12:15
Verified as fixed on Beta 84.0.0-beta.1 from 11/18 and Nightly 201119 from 11/19 with Samsung Galaxy Tab S3 (Android 8).
When trying to save an empty or invalid bookmark "Invalid URL" message is displayed.

I will close this issue.

**Closed by ebalazs-sv** 2020-11-19 12:15 UTC
Labels: Feature:Bookmarks, S2, 🐞 bug
