### ISSUE TITLE
[Bug]: homepage is scrollable even if there is no content

### ISSUE THREAD

**Issue by ris58h** [mozilla-mobile/fenix#28393] opened 2023-01-04 15:39 UTC
### Steps to reproduce

1. Disable all homepage blocks in Settings > Homepage
2. Open homepage 
3. Scroll it down

### Expected behaviour

Homepage shouldn't be scrolled because there is no content to scroll.

### Actual behaviour

Homepage is scrolled.

### Device name

Samsung Galaxy S10e

### Android version

12

### Firefox release type

Firefox

### Firefox version

108

### Additional information

https://user-images.githubusercontent.com/511242/210592160-b7192e61-8d16-411d-9e8a-b15897668d83.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22227)

**Comment by AdinaPetridean** [comment] 2023-01-05 07:34
@ris58h thank you for your report! I was able to reproduce the issue on Firefox 108.1.1 with Xiaomi Pad5 (Android 12). However, I can't reproduce it on Firefox 109.0b5 or on the latest Nightly 110.0a1 from 01/05.

**Comment by Dunexus** [comment] 2023-01-05 10:20
Duplicate of https://github.com/mozilla-mobile/fenix/issues/8545
It has been fixed by https://github.com/mozilla-mobile/fenix/commit/630edbb70922d51fc1ea8e64909756cf2b668233 and should be on next release (109)

**Comment by AdinaPetridean** [comment] 2023-01-05 14:14
Following the comment above, I close this ticket as duplicate.

**Closed by AdinaPetridean** 2023-01-05 14:14 UTC
Labels: 🐞 bug, Feature:HomeScreen, S3, needs:triage, qa-triaged
