### ISSUE TITLE
[Bug]Website notifications are truncated in landscape mode on tablets

### ISSUE THREAD

**Issue by vladbencovici** [mozilla-mobile/fenix#8482] opened 2020-02-18 14:11 UTC
## Steps to reproduce
1. Open fenix app.
2. Navigate to a website containing notifications (http://www.codecademy.com).
3. Rotate the device to activate landscape mode.
4. Check the website notifications.

### Expected behavior
The screen should resize to fit the landscape mode.

### Actual behavior
The website notifications are truncated

### Device information

* Android device: Google Pixel C (Android 8.0.0)
* Fenix version: Firefox Preview Nightly 200218 (Build #20490606) GV: 75.0a1-20200217095003

Note:
The issue was not reproduced on Huawei MediaPad M3 Lite 10

![Screenshot_20200218-155451](https://user-images.githubusercontent.com/57618010/74743510-3015cc00-5269-11ea-8bf4-611b3825a049.png)

**Comment by softvision-miralobontiu** [comment] 2020-11-18 13:06
@vladbencovici I was not able to reproduce this issue on the 11/18 Nightly build. 
I've tested with HTC 10 (Android 8), and Samsung Galaxy Tab S6 (Android 10).
Could you, please, retry?

**Comment by sflorean** [comment] 2021-03-31 15:17
Closing this due to lack of information/not reproducible state. If the issue is still reproducible, please re-open.

**Closed by sflorean** 2021-03-31 15:17 UTC
Labels: S2, b:web-content, 🐞 bug
