### ISSUE TITLE
Remember "desktop site" setting per site

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#17333] opened 2021-01-06 12:13 UTC
### What is the user problem or growth opportunity you want to see solved?
Some websites can happen to only work in "desktop site" mode. Currently user needs to enable "desktop site" switch every time he visits such website. It would be better if this would be remembered until switched off.

### How do you know that this problem exists today? Why is this important?
For example youtube.com mobile site hides some settings from user, until you visit their desktop site.

### Who will benefit from it?
Everyone.

**Comment by kbrosnan** [comment] 2021-01-06 17:24
duplicate of #11552

**Closed by kbrosnan** 2021-01-06 17:24 UTC
Labels: needs:triage

**Comment by BynariStar** [comment] 2021-03-01 11:12
Hi, #11552 is a bug, and this is an unrelated feature request. However, I'm unsure about the premise, perhaps a way to specifically mark certain domains to always load in desktop mode would be better. Regardless, requesting to retriage 🙂
