### ISSUE TITLE
The "forget about this website” feature disappeared. I want to get it back.

### ISSUE THREAD

**Issue by pierrefrancois** [mozilla-mobile/fenix#14575] opened 2020-09-01 12:23 UTC
In former versions of Firefox for Android, there was a feature in the history to delete every entry relayed to a website. I don't find this in version 79.0.5.

**Comment by hwinnemoe** [comment] 2020-09-01 12:41
Duplicate of #7981

**Comment by kbrosnan** [comment] 2020-09-01 17:31
Closing as a duplicate.

**Closed by kbrosnan** 2020-09-01 17:31 UTC
Labels: needs:triage
