### ISSUE TITLE
FNX-4785 ⁃ Fenix settings "Account" section briefly flashes "Sign In" UI, even though I'm already signed in

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#1082] opened 2019-03-19 20:45 UTC
## Steps to reproduce
1. Sign in to sync (Menu | Settings | Sign in, complete sign-in process)
1. (Probably optional) Quit & restart Fenix
1. Go to Menu | Settings

### Expected behavior
Your logged-in sync account should show up at the top of the settings pane, where "Sign In" was previously.

### Actual behavior
For a noticeable fraction of a second, the original "Sign In" UI is still present at the top of the Settings page. This immediately fades out and then is replaced by my Sync account. This animation plays every time I open the Settings page now.

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1912 (latest version, via google play store updates, at the moment)

**Comment by dholbert** [comment] 2019-03-19 20:48
Screencast of bug: https://www.dropbox.com/s/7wkib838y4kuwth/fenix-account-bug.mp4?dl=0

**Comment by yoasif** [comment] 2019-03-19 21:57
This is a dupe of  #933

**Comment by kbrosnan** [comment] 2019-03-19 22:02
Thanks @yoasif, closing as a dupe.

**Closed** 2020-08-11 01:54 UTC
