### ISSUE TITLE
[Bug] Muted autoplay videos are not playing

### ISSUE THREAD

**Issue by TheEvilPotatoe** [mozilla-mobile/fenix#16125] opened 2020-10-22 15:38 UTC
# Steps to reproduce
Go to https://ff-video-issue.surge.sh with your FF mobile
Notice the black square, the video doesn't play

### Expected behavior
The video should play once the page is loaded

### Actual behavior
The video is not autoplaying (despite the muted flag)

### Device information
 Android device: ? Xiaomi Redmi Note Pro 5 / Android 10 
* Fenix version: ? 81.1.5

**Comment by kbrosnan** [comment] 2020-10-22 18:50
The default setting of Firefox is to block video and audio playback. 

* in Firefox
* Tap 3 dot menu
* Settings
* Site permissions
* Autoplay
* Choose either of the other options

Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/8987

**Closed by kbrosnan** 2020-10-22 18:50 UTC
Labels: needs:triage, 🐞 bug
