### ISSUE TITLE
No paste option

### ISSUE THREAD

**Issue by sunkavallivijay** [mozilla-mobile/fenix#3791] opened 2019-06-29 07:41 UTC
On long press and hold in input box of websites there is no paste option shown. Unable to paste copied text. 

Android 9
Redmi note 5 pro 
MIUI global 10.3.1

**Comment by hakkikaancaliskan** [comment] 2019-06-29 18:14
There is but wrong place.
![Screenshot_20190629-211232](https://user-images.githubusercontent.com/17825767/60387913-d92d6d80-9ab2-11e9-9236-212dbe161e73.png)
Android 9 XZ1

**Comment by sunkavallivijay** [comment] 2019-06-30 03:08
Thanks for your reply. So it's an issue. Because of its position it might
not be visible.

Attached screenshot of what I am seeing.

**Comment by kumarharsh** [comment] 2019-07-01 05:20
It seems like the paste popover doesn't always trigger either. In the GitHub issues comment box, just try doing this: write some text, the long press. You'll see the paste popover. Now tap somewhere inside the box again to dismiss it, and then tap again (without doing anything else) - you won't get the popover.

Reproduced in OnePlus 6.

**Comment by vrudesai** [comment] 2019-07-05 19:28
Dupe of Issue [#1207](https://app.zenhub.com/workspaces/fenix-all-5bfedb154b5806bc2bf8d48c/issues/mozilla-mobile/fenix/1207)

**Comment by kumarharsh** [comment] 2019-07-06 02:55
It's opening zenhub for me...

**Comment by kbrosnan** [comment] 2019-07-06 18:57
Not a dupe of Verdi's issue which is describing address bar interactions. This is about content and is a GV bug.

**Comment by kbrosnan** [comment] 2019-07-06 18:58
Dupe of #2590

**Closed by kbrosnan** 2019-07-06 18:58 UTC
