### ISSUE TITLE
Intermittent UI test failure - < CustomTabsTest. customTabCopyToolbarUrlTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25058] opened 2022-05-02 05:20 UTC
### Stacktrace:
04-29 18:10:40.466: I/WindowManager(479): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity.  Reason: d9a6939 org.mozilla.fenix.debug/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity (server) is not responding. Waited 5040ms for MotionEvent(deviceId=-1, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (540.0, 1711.0)]), policyFlags=0x6b000000
04-29 18:10:40.501: E/Finsky(8096): [2] alff.run(14): Error while cleaning up task
04-29 18:10:40.501: E/Finsky(8096): java.util.concurrent.ExecutionException: com.google.common.util.concurrent.TimeoutFuture$TimeoutFutureException: Timed out (timeout delayed by 40 ms after scheduled time): bvj@83cf9f2[status=PENDING, info=[tag=[class akjm]]]
04-29 18:10:40.501: E/Finsky(8096): 	at awuc.s(PG:3)
04-29 18:10:40.501: E/Finsky(8096): 	at awuc.get(PG:2)
04-29 18:10:40.501: E/Finsky(8096): 	at awxe.a(PG:1)
04-29 18:10:40.501: E/Finsky(8096): 	at awvz.r(Unknown Source:9)
04-29 18:10:40.501: E/Finsky(8096): 	at alff.run(Unknown Source:4)
04-29 18:10:40.501: E/Finsky(8096): 	at android.os.Handler.handleCallback(Handler.java:938)
04-29 18:10:40.501: E/Finsky(8096): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-29 18:10:40.501: E/Finsky(8096): 	at android.os.Looper.loop(Looper.java:223)
04-29 18:10:40.501: E/Finsky(8096): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
04-29 18:10:40.501: E/Finsky(8096): 	at java.lang.reflect.Method.invoke(Native Method)
04-29 18:10:40.501: E/Finsky(8096): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-29 18:10:40.501: E/Finsky(8096): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
04-29 18:10:40.501: E/Finsky(8096): Caused by: com.google.common.util.concurrent.TimeoutFuture$TimeoutFutureException: Timed out (timeout delayed by 40 ms after scheduled time): bvj@83cf9f2[status=PENDING, info=[tag=[class akjm]]]
04-29 18:10:40.502: I/Finsky(8096): [2] VerifyInstallTask.mC(6): Verification complete: id=12, package_name=org.mozilla.fenix.debug.test
04-29 18:10:40.596: I/ActivityManager(479): Killing 10848:com.google.android.projection.gearhead:shared/u0a95 (adj 975): empty #17
04-29 18:10:40.613: I/Zygote(289): Process 10848 exited due to signal 9 (Killed)
04-29 18:10:40.619: I/ActivityManager(479): Force stopping org.mozilla.fenix.debug appid=10151 user=0: finished inst
04-29 18:10:40.619: I/ActivityManager(479): Killing 12568:org.mozilla.fenix.debug/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-29 18:10:40.621: W/ActivityTaskManager(479): Force removing ActivityRecord{e85c8fc u0 org.mozilla.fenix.debug/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity t10 f}}: app died, no saved state
04-29 18:10:40.622: I/ServiceChildProcess(13491): Destroying GeckoServiceChildProcess
04-29 18:10:40.627: W/Binder(12483): Caught a RuntimeException from the binder stub implementation.
04-29 18:10:40.627: W/Binder(12483): java.lang.SecurityException: Calling from not trusted UID!
04-29 18:10:40.627: W/Binder(12483): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
04-29 18:10:40.627: W/Binder(12483): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
04-29 18:10:40.627: W/Binder(12483): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
04-29 18:10:40.627: W/Binder(12483): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
04-29 18:10:40.627: W/Binder(12483): 	at android.os.Binder.execTransact(Binder.java:1123)
04-29 18:10:40.630: I/ServiceChildProcess(13289): Destroying GeckoServiceChildProcess
04-29 18:10:40.640: D/AndroidRuntime(12483): Shutting down VM
04-29 18:10:40.646: I/libprocessgroup(479): Successfully killed process cgroup uid 10095 pid 10848 in 44ms
04-29 18:10:40.656: W/ActivityTaskManager(479): Force removing ActivityRecord{4cd84ab u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
04-29 18:10:40.664: I/fenix.debug:gp(13491): System.exit called, status: 0
04-29 18:10:40.664: I/AndroidRuntime(13491): VM exiting with result code 0, cleanup skipped.
04-29 18:10:40.680: I/ActivityManager(479): Killing 13289:org.mozilla.fenix.debug:tab28/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-29 18:10:40.681: I/ActivityManager(479): Killing 13491:org.mozilla.fenix.debug:gpu/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-29 18:10:40.684: D/WindowManager(479): notifyANR took 225ms

**Comment by AndiAJ** [comment] 2022-05-05 04:19
Flaky 1x on 5/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8329290398798209765/executions/bs.a54146bf82b170c/test-cases)

**Comment by sv-ohorvath** [comment] 2022-05-12 13:26
dupe of https://github.com/mozilla-mobile/fenix/issues/24999

**Closed by sv-ohorvath** 2022-05-12 13:26 UTC
Labels: b:crash, eng:intermittent-test, needs:triage, eng:ui-test
