### ISSUE TITLE
[Bug] Opening custom tab shows blank page

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/fenix#15095] opened 2020-09-14 20:57 UTC
###  Steps to reproduce

* Open Gmail app
* Click on link to custom tab (doesn't happen always, but e.g. for Redfin emails I can reproduce consistently somehow)
* video here: https://imgur.com/a/eharBgR
* logs: [open-custom-tab-bug.log](https://github.com/mozilla-mobile/fenix/files/5220945/open-custom-tab-bug.log)

### Expected behavior

* Page loads and it's visible

### Actual behavior

* Blank page

### Device information

* Android device: Samsung S10e
* Fenix version: Latest Nightly

**Comment by s-ankur** [comment] 2020-09-15 10:52
Open in firefox is able to display the page however

**Comment by pocmo** [comment] 2020-12-01 14:46
That looks like it is the same as https://bugzilla.mozilla.org/show_bug.cgi?id=1641715

@agi if you can still reproduce this... can you verify that it is the same problem and reducing the `processCount` fixes it?

**Comment by agi** [comment] 2020-12-01 17:35
@pocmo that's not possible, the processCount fix landed 15ish days ago, this bug was reproducible months ago.

**Comment by agi** [comment] 2020-12-01 17:57
FWIW I can still reproduce (and I have `processCount=1`)

**Comment by pocmo** [comment] 2020-12-07 16:17
The only time I could reproduce it via gmail, it turned out that uBlock was blocking the page. But in the custom tab I just got a blank page. (Re)loading the same URL in the browser showed the "ublock original has prevented..." error page.

@agi Is that similar to what you are seeing? Do you have ublock enabled and does disabling it help?

**Comment by agi** [comment] 2020-12-07 17:12
@pocmo I don't think ublock was responsible in my case because sometimes the page does open and displays correctly.

I just tried though and I cannot reproduce anymore, so it's hard to say.

**Comment by pocmo** [comment] 2020-12-14 15:49
I filed a new issue for the blank page when ublock blocks the page:
https://github.com/mozilla-mobile/android-components/issues/9210

Let's fix that first and then see what cases remain here.

**Comment by s-ankur** [comment] 2021-06-13 16:24
havent seen this bug in a while

**Comment by s-ankur** [comment] 2021-06-14 13:48
Regret to inform that this is happening reproducibly with zoom SSO signins

**Comment by s-ankur** [comment] 2021-06-14 14:11
STR:
Zoom App-> Sign in with SSO -> enter company name-> open custom tab -> blank page

only happened recently

**Comment by pocmo** [comment] 2021-06-15 10:21
@s-ankur Which app version is that? We recently had a similar bug in Nightly, but this should have been fixed in the latest version.

**Comment by s-ankur** [comment] 2021-07-01 17:52
No longer reproducible @pocmo

**Closed** 2022-01-04 22:17 UTC
Labels: 🐞 bug, needs:ac, Feature:CustomTabs, wontfix
