### ISSUE TITLE
FNX3-16774 ⁃ [Bug] First collection not visible on the Select Collections screen by default

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3080] opened 2019-06-03 11:14 UTC
## Steps to reproduce
1. Create a long list of collections.
1. Select a tab to add to a collection.
1. Observe the Select collection screen.
    1. Expected behavior
The first collection from the bottom should be visible (!?).
    1. Actual behavior
The screen is displayed by default starting from the second collection. 
![Screenshot](https://user-images.githubusercontent.com/4037709/58797913-dea9ac00-8609-11e9-94ef-142a19a2900b.jpg)UNITO-UNDERSCORE!20190603-141306!UNITO-UNDERSCORE!Firefox Preview!

### Device information
* Android device: Galaxy S8, Nexus 5
* Fenix version: 6/3

**Comment by mheubusch** [comment] 2019-06-05 22:58
@AmyYLee is this a dupe of https://github.com/mozilla-mobile/fenix/issues/3004?

**Comment by colintheshots** [comment] 2019-06-07 01:53
According to @AmyYLee when I asked, the Collections and Tabs should be aligned to the top of the list.

**Comment by AmyYLee** [comment] 2019-06-07 17:03
> @AmyYLee is this a dupe of #3004?

No, this is a different issue. This is addressing the positioning of tabs when in Saving to collection mode. The other bug is about expanding/closing tabs on homescreen.

**Closed** 2020-08-17 21:55 UTC
Labels: P1, 🐞 bug
