### ISSUE TITLE
[Bug] Ad trackers in org.mozilla.firefox version 81.1.2 and org.mozilla.fennec_fdroid version 81.1.1

### ISSUE THREAD

**Issue by fp-supporter** [mozilla-mobile/fenix#15820] opened 2020-10-10 07:38 UTC
## Steps to reproduce

- I always download my apps from the F-Droid client. But this time F-Droid promotes Fennec F-Droid as:
1. This app promotes non-free add-ons
2. **[NEW] This app tracks and reports your activity**
3. The upstream source code is not entirely Free

- Open (F-Droid Fennec Browser: https://reports.exodus-privacy.eu.org/en/reports/org.mozilla.fennec_fdroid/latest/
- There are two ad trackers listed:
1. Adjust
2. LeanPlum
- Open (Firefox Browser: https://reports.exodus-privacy.eu.org/en/reports/org.mozilla.firefox/latest/
- There are three ad trackers listed:
1. Adjust
2. Google Firebase Analytics
3. LeanPlum

### Expected behavior

1. To use an ad free variant version of Fennec on f-droid.org.
2. To use an ad free variant version of Firefox Browser for mobile.

### Actual behavior

1. Fennec and Firefox Browser is tracking the user activity and promotes ads.

### Device information

* Android device: Fairphone 3
* Fennec F-Droid version: 81.1.1
* Fenix version: 81.1.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8048)

**Comment by jawz101** [comment] 2020-10-11 02:55
Close this.  It's been addressed many times.  This is not an issue

**Comment by anotherus3r** [comment] 2020-10-11 14:14
Might be a duplicate of #12809.

Also, you might be interested in:
- https://support.mozilla.org/en-US/kb/send-usage-data-firefox-mobile-browsers
- https://github.com/mozilla-mobile/fenix/issues/12809#issuecomment-662199501

**Comment by grravity** [comment] 2020-10-12 00:19
I'm extremely disappointed. I expected this stuff to be removed as well, and was met with great disappointment when it was published to F-Droid like this.

I fail to understand why you (op) has 4 downvotes..
Do people not want privacy in a browser that claims to be privacy friendly? These are the issues we are trying to escape.
The add-ons were the best part and even those aren't finished, if these privacy issues don't get fixed I'm sorry but I cannot recommend Fenix to anyone (as much as I'd like to, because I do not like Chromium), I will also be forced to use Chromium because at least they actually are doing something right here.

I highly encourage all the trackers to be removed, there is absolutely zero real reason for them to be in there. At the very least the F-Droid version, where people expect privacy. This is terrible and I am disappointed greatly, I truly wish this wasn't the case. Fenix had a lot of potential, but the two biggest features (privacy friendly, and addon support) still after years is like going backwards.

Also #12809 is related, howver it was closed and nobody can actually chat and share their feelings about it.

**Comment by anotherus3r** [comment] 2020-10-12 08:19
Such a build would be good to have, but wouldn't turning off the settings in "Menu > Settings > Data collection" be (at least to some extent) sufficient or am I missing something?

I suppose the Firefox devs need to collect at least some usage data for development. How else would they know which features to focus on, which ones need more work, which are less important to users, are there any crashes or slowdowns, etc.? The vast majority of users most likely don't really provide feedback, whether through the feedback page, Play Store reviews or other channels. People can't expect a fast, feature-rich, useful browser without providing any kind of feedback/data.

Mozilla also needs to market their own services in their products, so other users start using them. Expecting Mozilla to just silently launch services without marketing them to existing and/or future users of their other products isn't realistic. That would just make them financially more dependent on third-parties.

Lastly, as far as I know, there isn't a stable build of pure Chromium, so I don't know which Chromium browser you'd use that doesn't collect usage data.

**Comment by grravity** [comment] 2020-10-12 16:38
No, the trackers are baked in. Ontop of this the toggles Mozilla provides (even on desktop) seems to still not completely disable telemetry, usually this is done with custom user.js, look at ghacks.

And I never disagreed with mozilla wanting telemetry, however it should be opt in, self-hosted by them, and if users choose to not opt in, there should be zero telemetry going to Mozilla.

Either way, I'd be ok with manually disabling about:config flags, given Adjust, Leanplum and Firebase weren't present, they however are present.

**Comment by crisalis2** [comment] 2020-10-26 00:40
As for Fennec F-Droid:
"I removed all tracking I found. (Firebase, Adjust and Leanplum libraries were replaced with stubs, so some analyzers can erroneously report their presence in the APK.)"
https://forum.f-droid.org/t/welcome-a-new-fennec-f-droid/11113

**Comment by amedyne** [comment] 2021-06-23 17:15
We no longer integrate with Leanplum. See #19040.

**Comment by kbrosnan** [comment] 2023-01-21 03:15
Duplicate https://github.com/mozilla-mobile/fenix/issues/12809.

**Closed by kbrosnan** 2023-01-21 03:15 UTC
Labels: feature request 🌟
