### ISSUE TITLE
[Bug] Keyboard remains raised after loading page on Galaxy S5

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#16973] opened 2020-12-10 20:31 UTC
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Click URL bar
- Enter URL (I used apple.com but it happens on every site I tried)
- Hit enter to load page

### Expected behavior
Keyboard lowers

### Actual behavior
Keyboard lowers and re-raises despite not focusing an input field. Here's a video of the issue: https://drive.google.com/file/d/1FtPpHNG_CBl4eaRoY4EOxuNHdjotRmix/view?usp=sharing

### Device information
* Android device: GS5, stock keyboard
* Fenix version: Latest master 9a984f10f1a09763310c0900d11efc84d17c178b

I can't reproduce this on my Pixel 2.

**Comment by ekager** [comment] 2020-12-10 22:46
Urgh. Thought I fixed these in https://github.com/mozilla-mobile/fenix/pull/16907 
I can't repro on any of my devices, so I may need to send you some APKs to test :(

**Comment by DiegoARL38** [comment] 2020-12-11 01:38
This issue is reproducible also ona Xiaomi Redmi Note 8 with MiUI 11.0.12 Global.

**Comment by s-ankur** [comment] 2020-12-11 05:18
My device as well (Asus Zenfone m1)

**Comment by ekager** [comment] 2020-12-11 05:39
Could you all also repro within the last few weeks? https://github.com/mozilla-mobile/fenix/issues/16668

Or only the last few days?

**Comment by DiegoARL38** [comment] 2020-12-11 05:45
For me, it's been recent, a week or so.

**Comment by ekager** [comment] 2020-12-11 21:12
Could one of you test the APK from this speculative fix PR? Should be able to access them here: https://firefox-ci-tc.services.mozilla.com/tasks/FIqxP2JpTlqKSH1AsjIO_g#artifacts

**Comment by ale82to** [comment] 2020-12-11 21:44
this build fixes the issue luckily

**Comment by DiegoARL38** [comment] 2020-12-11 21:59
The issue seems to be fixed on the latest nightly, at least for me.

Nightly 201210 17:02 (Build #2015780619)
AC: 70.0.20201210143138, ae9cdf4bb
GV: 85.0a1-20201210092800
AS: 67.0.0

**Comment by ekager** [comment] 2020-12-11 22:03
@ale82to or @mcomella could you confirm that this _is_ still happening in Nightly for you AND the APK linked fixes the remaining issue? Don't want to merge code that isn't needed :)

**Comment by ale82to** [comment] 2020-12-11 22:35
I ve tried nighlty half hour ago and issue was still there (I use swiftkey) I don't use nighlty from playstore but I download from here https://firefoxci.taskcluster-artifacts.net/dkslPJ5XQGGB3hoAQLGW0A/0/public/build/arm64-v8a/target.apk

**Comment by ekager** [comment] 2020-12-11 22:38
Thank you! So I'll get that fix reviewed/merged

**Comment by philipmgrant** [comment] 2020-12-14 18:17
I have the same problem on a Moto G5S Plus using SwiftKey.  It appeared to be fixed in the 12/11 and 12/12 Nightly builds in the Play Store, but has reappeared in 12/13.

**Comment by ekager** [comment] 2020-12-14 18:47
@philipmgrant and does the APK linked here fix your problem?  https://github.com/mozilla-mobile/fenix/issues/16973#issuecomment-743429379

**Comment by sflorean** [comment] 2020-12-16 09:14
Tested on Nightly 12/16 with Xiaomi Redmi Note 8 (from the affected devices) and couldn't reproduce the issue. Based on the above comments from users, I will close this as fixed.

**Closed by sflorean** 2020-12-16 09:14 UTC
Labels: Feature:IME, eng:qa:needed, 🐞 bug
